### ISSUE TITLE
`InteractiveEditorInput` does not declare `editorId`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#134088]
From https://github.com/microsoft/vscode/issues/131587#issuecomment-929698271

The interactive editor is registered to the resolver here:

https://github.com/microsoft/vscode/blob/f06e8d715c2d32fa49a1da1fc2e7d7db8136e8da/src/vs/workbench/contrib/interactive/browser/interactive.contribution.ts#L188

and here

https://github.com/microsoft/vscode/blob/f06e8d715c2d32fa49a1da1fc2e7d7db8136e8da/src/vs/workbench/contrib/interactive/browser/interactive.contribution.ts#L205

But the `InteractiveEditorInput` does not provide a matching `editorId` override.

Besides, I would probably suggest to register the editor with `InteractiveEditorInput.ID` to stay in sync and prevent the input from having a dependency to the editor.

@lramos15 fyi, maybe we need to log a warning when a registered editor is not implementing `editorId`?

Moving to September to unblock https://github.com/microsoft/vscode/issues/131587

**Comment by rebornix** [comment]
Fixed the interactive editor input. @bpasero is there any way to exclude a editor type from the list? We register an internal notebook view type for interactive window but it's an embed notebook so it doesn't make sense to have it on the lock list.

**Comment by lramos15** [comment]
> @lramos15 fyi, maybe we need to log a warning when a registered editor is not implementing `editorId`?

I don't think a warning is enough. What are your thoughts on throwing since we need this to be defined in a lot of places and all registered editors are almost always assumed to have it?

**Comment by bpasero** [comment]
@rebornix thats a good question that I need @lramos15 advice for: does the resolver have a way of indicating "internal" editors that I can filter on? I am currently using this call:

https://github.com/microsoft/vscode/blob/da0fa2dc8fc8f5ae6ea878a9c449e0eb930b510d/src/vs/workbench/browser/parts/editor/editorConfiguration.ts#L50

> I don't think a warning is enough. What are your thoughts on throwing since we need this to be defined in a lot of places and all registered editors are almost always assumed to have it?

Makes sense, filed https://github.com/microsoft/vscode/issues/134184

**Comment by lramos15** [comment]
> @rebornix thats a good question that I need @lramos15 advice for: does the resolver have a way of indicating "internal" editors that I can filter on? I am currently using this call:

Not currently, no. We do have the exclusive editors which we hide from the Re-open with picker. If you want we can add internal as well as I'm not sure exclusive is enough for your use case as you still want to allow locking on things like the terminal.
