### ISSUE TITLE
[BUG] The vscode can't correctly parse definition!

### ISSUE THREAD

**Issue by TonyPythoneer** [Microsoft/vscode#13403]
- VSCode Version: 1.5.3
- OS Version: Ubuntu 16.04.1 LTS

I was using `bluebird` and `fs` to do something but the `promise.map` shows incorrect type.

Demo:
```
    let readdir = Promise.promisify(fs.readdir);
    let templatesDir = `${__dirname}/templates`;
    readdir(templatesDir).map(filename => filename)
```

The map shows type is `(method) Bluebird<string[]>.map<{}, {}>(mapper: (item: {}, index: number, arrayLength: number) => {} | Promise.Thenable<{}>, options?: Promise.ConcurrencyOption): Promise<{}[]>`.

Ideally, it should show `Bluebird<string[]>.map<string, string>`. Why is it `Bluebird<string[]>.map<{}, {}>`?

I used `sublime` is okay but `vscode` not. What happened?

**Comment by TonyPythoneer** [comment]
I had installed v1.6.0
It still can't solve.

**Comment by waderyan** [comment]
@TonyPythoneer thank you for opening this issue. Can you share your workspace or a simplified repo that reproduces the issue so I can reproduce this on my end?

**Comment by TonyPythoneer** [comment]
@waderyan I had already created [a simplified repo](https://github.com/TonyPythoneer/vscode-bug). Please take a look.

**Comment by waderyan** [comment]
@TonyPythoneer this is an issue in the *.d.ts file. You can see this when you F12 (Go to definition) into the method. 

Please file an issue / make a PR on the [Definitely Typed repo](https://github.com/DefinitelyTyped/DefinitelyTyped) (bluebird file is [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/bluebird/bluebird.d.ts)) which provides this information.

**Comment by TonyPythoneer** [comment]
But why sublime can correctly parse and pass type, vscode not?
