### ISSUE TITLE
Only show one testing output terminal

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#134060]
When I open the testing output terminal via the terminal button or `Test: Show Output`, I want it to reuse the existing testing output terminal if one is already open, instead of possibly opening a new one. My first preference would be to enable this behavior with a toggleable entry on the `...` menu of the testing view. My second preference would be a regular setting

**Comment by connor4312** [comment]
This _should_ already happen but doesn't always.

**Comment by connectdotz** [comment]
does this only apply in the TestController scope? If we have a multi-root project, i.e. multiple TestControllers, do we expect one terminal per controller? If that is the case, is there a way to "name" the terminal? Right now I see multiple terminals, each with a different time-stamp, so not sure which terminal is from what controller...

**Comment by connectdotz** [comment]
@connor4312 not sure if this has been requested, is there a way to append a more meaningful name to the output terminals? In multi-root workspaces where multiple terminals/controllers are shown, the current naming scheme (append timestamp) is not very useful...
