### ISSUE TITLE
Reconsider default value of `scm.alwaysShowRepositories`

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#134015]
This commit changed the default value of `scm.alwaysShowRepositories`: https://github.com/microsoft/vscode/commit/53c5d3cb4ac0449292d3e4dc8eb70294f4b2dbec

I don't think this is a good out-of-the-box experience:

![image](https://user-images.githubusercontent.com/22350/135098291-380b6fb5-51b6-46b8-949f-21f9c9747516.png)

As opposed to:

![image](https://user-images.githubusercontent.com/22350/135098389-d2aabb1c-f2b9-46be-bd71-43762f476eb6.png)

**Comment by IllusionMH** [comment]
I think that's what confused me today and I was looking if I unintentionally opened file with another git repo or created another inside of current.

**Comment by gjsjohnmurray** [comment]
Counter-argument is that new users may not spot that there's a useful and significant panel for a git repo on the left end of the status bar. They don't discover how to switch branches, nor benefit from the indicators about how many commits behind / ahead they are.

**Comment by jrieken** [comment]
> This aims to improving the pushing/pulling experience for new users as after you commit there’s no indication in the view as what to do next.

Can we use something more light-weight like shadow text and/or commands inside the input box? The only addition is the sync button and the number of incoming/outgoing changes (the commit and sync commands are just rendered a line further below)

**Comment by lszomoru** [comment]
Will be closing this issue as:
* The default value of the setting has been reverted
* There is now a "Commit" action button that should guide users on what to do next
