### ISSUE TITLE
Debian packages repo appears unsigned

### ISSUE THREAD

**Issue by Red54** [microsoft/vscode#134097]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.1
- OS Version: Deepin 20.2.3

Steps to Reproduce:

1. Run `sudo apt update` in DEB-based **Linux**

> $ sudo apt update
...
Get:12 https://packages.microsoft.com/repos/code stable InRelease [9,890 B]
Err:12 https://packages.microsoft.com/repos/code stable InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists... Done         
E: Failed to fetch https://packages.microsoft.com/repos/code/dists/stable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.microsoft.com/repos/code stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by sjones-and** [comment]
![image](https://user-images.githubusercontent.com/47328516/135238193-6bae4832-2a13-422b-a34e-c7ce90401ad7.png)

Looks like missing gpg signature, something went wrong with an update this morning 🤦‍♂️

**Comment by sjones-and** [comment]
![image](https://user-images.githubusercontent.com/47328516/135241208-a0f6b6f0-5f73-45ba-9443-d0b9a159ad80.png)

InRelease is the same size as Release, but it's meant to contain the GPG key inline (so should be a larger file size).  Something went screwy during a release process...

GitHub status for @Tyriar says he's taking some time off work, can anyone tag in someone that might be able to fix this ASAP?

**Comment by BrunoCarvalhoAlvim** [comment]
I'm having the same error in Pop!_OS 21.04.

`
$ sudo apt update
Hit:1 http://dl.google.com/linux/chrome/deb stable InRelease
Get:2 https://cli.github.com/packages stable InRelease [3,743 B]                                                                                                                             
Hit:3 https://download.docker.com/linux/ubuntu hirsute InRelease                                                                                                                             
Hit:4 http://us.archive.ubuntu.com/ubuntu hirsute InRelease                                                                                                                                  
Hit:5 http://us.archive.ubuntu.com/ubuntu hirsute-security InRelease                                                                            
Hit:6 http://ppa.launchpad.net/system76/pop/ubuntu hirsute InRelease                                                                            
Get:7 http://packages.microsoft.com/repos/code stable InRelease [9,890 B]                                                 
Err:7 http://packages.microsoft.com/repos/code stable InRelease                                                         
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Hit:8 http://us.archive.ubuntu.com/ubuntu hirsute-updates InRelease             
Hit:9 http://apt.pop-os.org/proprietary hirsute InRelease
Hit:10 http://us.archive.ubuntu.com/ubuntu hirsute-backports InRelease
Reading package lists... Done
E: Failed to fetch http://packages.microsoft.com/repos/code/dists/stable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'http://packages.microsoft.com/repos/code stable InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

`

**Comment by sjones-and** [comment]
Assuming you followed [these](https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions) instructions to install...

Workaround if you're not trying to update or install VS Code:
```sudo rm /etc/apt/sources.list.d/vscode.list```

Horrible hack **NOT RECOMMENDED, UNSAFE, DON'T DO THIS** if you are trying to update or install VS Code:
```sudo sh -c 'echo "deb [trusted=yes] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'```

**Comment by sjones-and** [comment]
Tagging in some other Microsoft people, sorry if this isn't your thing (I just got you off other recent issues), but it needs fixing (and the triage bot probably needs to not assign stuff to people who are off work!):

@eamodio @alexdima @bpasero @rebornix @sandy081

**Comment by joaomoreno** [comment]
Creating an internal ticket. Thanks for letting us know.

**Comment by rjh1970** [comment]
Just updated to 1.60.2 successfully after previously unsuccessful attempts (20 mins ago) with the above error. Ubuntu 20.04.03.

**Comment by joaomoreno** [comment]
This has been fixed 10 mins ago (~ 13:46 UTC). Thanks for the ping everyone!

**Comment by kilobyte** [comment]
It's broken again today.

**Comment by Bananas-Are-Yellow** [comment]
> It's broken again today.

For me, it's Microsoft Edge that's broken today, not VS Code.
```
Err:6 http://packages.microsoft.com/repos/edge stable InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
```

InRelease and Release are the same size:

https://packages.microsoft.com/repos/edge/dists/stable/

**Comment by joaomoreno** [comment]
I've notified our partner team internally.

**Comment by selfprogrammed** [comment]
> > It's broken again today.
> 
> For me, it's Microsoft Edge that's broken today, not VS Code.
> 
> ```
> Err:6 http://packages.microsoft.com/repos/edge stable InRelease
>   Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
> ```
> 
> InRelease and Release are the same size:
> 
> https://packages.microsoft.com/repos/edge/dists/stable/

Same for me. Vscode is fine. Edge is having this error. PopOs 21.04

**Comment by sugatoray** [comment]
> > > It's broken again today.
> > 
> > 
> > For me, it's Microsoft Edge that's broken today, not VS Code.
> > ```
> > Err:6 http://packages.microsoft.com/repos/edge stable InRelease
> >   Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > InRelease and Release are the same size:
> > [packages.microsoft.com/repos/edge/dists/stable](https://packages.microsoft.com/repos/edge/dists/stable/)
> 
> Same for me. Vscode is fine. Edge is having this error. PopOs 21.04

Same for me. Edge is the culprit this time. I checked the site (https://packages.microsoft.com/repos/edge/dists/stable/) and the browser did not show a locked icon initially. But later the locked icon reappeared. Yet, `sudo apt update` does throw the same error.

```sh
Get:17 http://packages.microsoft.com/repos/edge stable InRelease [6,817 B]
Err:17 http://packages.microsoft.com/repos/edge stable InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists... Done         
E: Failed to fetch http://packages.microsoft.com/repos/edge/dists/stable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'http://packages.microsoft.com/repos/edge stable InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by sugatoray** [comment]
Checked now again: seems it's been fixed now. No more error while running `sudo apt update`. [Refer: [error report (comment)](https://github.com/microsoft/vscode/issues/134097#issuecomment-985725629)]

**Comment by Bananas-Are-Yellow** [comment]
Yes, it's fixed now.
