### ISSUE TITLE
Compact status bar action hover is annoying when moving to link

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#134048]
Testing #133746

1. Hover over the TypeScript/Javascript menu status bar action
2. Move your mouse directly to one of the actionable links
3. The hover dismisses

Video: https://memes.peet.io/img/21-09-03fe36f4-9cc2-4f73-9008-8f966008b97a.mp4

**Comment by bpasero** [comment]
Let's merge into https://github.com/microsoft/vscode/issues/134049, since both entries provide their own hover, you end up triggering the other hover.
