### ISSUE TITLE
Why is keepScrollPosition needed?

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#134002]
Testing #133891

Creating this more for discussion. 

Why do we need `keepScrollPosition` field? Shouldn't we always keep the scroll position? What is an example of quickPick usage when the user would not want the scroll position to be kept?
We keep the scroll position in all our UI elements, from Debug to Explorer to SCM. Why is Quick Pick different?

Bonus question: if you decide to go with the `keepScrollPosition` field, why is `false` the default?

Thanks

**Comment by TylerLeonhardt** [comment]
> Why do we need keepScrollPosition field? Shouldn't we always keep the scroll position? What is an example of quickPick usage when the user would not want the scroll position to be kept?

Remember that the `quickpick` object gives you full control of the quickpick so something like this isn't too out of the ordinary:
```
const listA = ['a', 'b', 'c'];
const listB = ['d', 'e', 'f'];
quickpick.items = listA;
quickpick.onDidAccept(() => {
    // more logic
    quickpick.items = listB;
    // more logic
});
```
The user selects an item from listA and is presented listB. If we did `keepScrollPosition` `false` by default, that would break existing extensions that assumed that setting `.items` caused the scroll to jump to the top (where perhaps listB was sorted by "most likely picked") and if we didn't have a `keepScrollPosition` they would have no way to reuse the same quickpick and reset that scroll position.

> Bonus question: if you decide to go with the keepScrollPosition field, why is false the default?

@jrieken said most of our booleans are `false` by default so I followed that.

**Comment by isidorn** [comment]
This makes sense. Thanks for answering. Closing.
