### ISSUE TITLE
2 VS code windows

### ISSUE THREAD

**Issue by Valerie-24** [microsoft/vscode#134079]
After my npm (chai & mocha) install, I got a new VS Code window with a different path.  Is there a way to merge the two?  One window has my files w/history and the other has the Node_modules I need.  Need all to be in one.

C;\Users\valer\OneDrive\Desktop\Projects  and the other is in C;\Users\valer\projects.

**Comment by bpasero** [comment]
https://code.visualstudio.com/docs/editor/multi-root-workspaces
