### ISSUE TITLE
Reviving terminal process not working on Windows

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#134063]
Testing #133516

Maybe I misunderstand what processes are supposed to be restored, but I ran these processes,
- `yarn run compile`
- `yarn run test`
- `python hello.py` which exits after 30 seconds
```python
import time

print("Printed immediately.")
time.sleep(30)
print("Printed after 30 seconds.")
```

used `workbench.action.quit` command to exit, but only the buffer is restored.

![image](https://user-images.githubusercontent.com/13199757/135170991-855e4e24-a855-4eef-8446-4c3e9e89bd14.png)

Is this expected?

**Comment by meganrogge** [comment]
According to this, I'd expect it to work 

https://github.com/microsoft/vscode/issues/131634#issuecomment-905494775

**Comment by meganrogge** [comment]
Perhaps these particular processes aren't recreated and that's by design. I'm not sure.

**Comment by karrtikr** [comment]
It works when I reload the window, but not when exiting or closing and reopening the window, so I guess that comment is still accurate.

**Comment by meganrogge** [comment]
Clarified with @Tyriar and this is working as-designed.

**Comment by karrtikr** [comment]
I see, can you give me some examples of processes it is supposed to restore?

**Comment by Tyriar** [comment]
@karrtikr I think the confusion is it doesn't "restore" processes, it restores the buffer, and then re-created a new process at what we know the current working directory to be (cwd detection is not supported right on Windows so it uses the initial directory).

**Comment by karrtikr** [comment]
Got it, thanks.
