### ISSUE TITLE
Outline cannot follow correct side in split editor case

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#134008]
We need a similar fix as with breadcrumbs to update on control change.

//cc @jrieken

**Comment by rzhao271** [comment]
@bpasero What are some verification steps for this issue?

**Comment by bpasero** [comment]
@rzhao271 split an editor into 2 (into the same tab, not across 2 groups), open the Outline view and verify that clicking on the left and right side updates the outline accordingly and that selection applies to the currently focused side.

**Comment by rzhao271** [comment]
The breadcrumbs are updating but the outline is staying the same when I switch between the two sides.

**Comment by bpasero** [comment]
Forgot to mention, you need to enable "Follow Cursor":

![image](https://user-images.githubusercontent.com/900690/135703838-5b2630e3-a389-4375-a326-6f9d6ca2dc8c.png)

**Comment by hediet** [comment]
Works in latest insiders.
