### ISSUE TITLE
Terminal tab titles - Unexpected ${process} updating

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#134027]
Testing #133549

1. Change terminal tab title to `${workspaceFolder}`
2. Open folder `helloWorld`
3. Change takes effect, i.e. terminal tab title reads `helloWorld`
4. Change terminal tab title setting to `${process}`
5. Terminal tab still reads `helloWorld`

![image](https://user-images.githubusercontent.com/25310137/135122374-989cc95a-d0dc-4548-8fa4-22981fea870b.png)

6. Reload, tab still reads `helloWorld`
7. Close folder, tab now reads `powershell`
8. Reopen `helloWorld` folder, tab remains as `powershell`

If I'm misunderstanding the role of `${process}` and this is expected, please let me know.

**Comment by meganrogge** [comment]
tried to repro this but couldn't

![recording (74)](https://user-images.githubusercontent.com/29464607/135159619-cb8c9b7a-5af1-402d-bdbf-41caf644ffd0.gif)
