### ISSUE TITLE
Outline allow to copy string

### ISSUE THREAD

**Issue by duckimann** [microsoft/vscode#134083]
![image](https://user-images.githubusercontent.com/46382253/135199848-0a59eab2-c24c-4ee0-a137-8db7257c6f43.png)

With the picture above as an example, i want to copy the "Outline view" string on top pointed to the line 24. As Javascript / Json, the expected string should using dot notation and have array index.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"breadcrumbs"

**Comment by duckimann** [comment]
Maybe the #58678 is the one you talk about? It's 1 year ago and i'll be patient 😁 Thanks btw.
