### ISSUE TITLE
Unfolded region not preserving when dragging file to new window

### ISSUE THREAD

**Issue by lydiayschung** [microsoft/vscode#134064]
Testing #133747

Sometimes the unfolded or expanded regions are not preserving when I drag the files to a new window. Attached screenshots of two different files. 
<img width="1673" alt="Screen Shot 2021-09-28 at 3 23 24 PM" src="https://user-images.githubusercontent.com/60596156/135174695-eed5e9a0-18a2-4d97-8ebe-ad63e518b73d.png">
<img width="1680" alt="Screen Shot 2021-09-28 at 3 18 18 PM" src="https://user-images.githubusercontent.com/60596156/135174718-00d1d94f-a8d3-4633-9277-841a2083d8c8.png">

**Comment by bpasero** [comment]
I cannot really reproduce, do you have reliable steps?

**Comment by lydiayschung** [comment]
In the videos below I'm using the README from the [call hierarchy extension sample](https://github.com/microsoft/vscode-extension-samples/tree/main/call-hierarchy-sample). The first video shows when it's not preserving, but there are times when it does work as shown in the second video.

https://user-images.githubusercontent.com/60596156/135317782-f23240fe-3b18-4264-a8bb-1dc31c17175d.mov

https://user-images.githubusercontent.com/60596156/135318000-68e50da9-b619-4e0c-a6ba-565acef31a7c.mov

**Comment by bpasero** [comment]
@lydiayschung it looks like there is a bit of flickering involved when you try, as if the folding is right in the beginning but then changes later. I wonder if any extension you have could trigger this?

Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code-insiders --disable-extensions`.

Besides, I wonder if any setting could play a role too, so best to try on a fresh user data dir: `code-insiders --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by lydiayschung** [comment]
The combination of starting with an empty folder and no extensions running worked! Thanks!
