### ISSUE TITLE
Command Palette doesn't prioritize intuitively-best match

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#134016]
Issue Type: <b>Bug</b>

- Open Command Palette
- Type `open settings json`
- Be surprised that the desired command (`Preferences: Open Settings (JSON)`)  isn't first

![image](https://user-images.githubusercontent.com/6726799/135099265-925d4ca8-54fb-4a7d-a159-72af74487e1c.png)

Even better would be if merely typing `p o s j` or `posj` surfaced it at the top of the list.

VS Code version: Code - Insiders 1.61.0-insider (214ac689ca9874a8a4be386f73d5cb60e15af25e, 2021-09-28T05:18:06.850Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by bpasero** [comment]
/duplicate https://github.com/Microsoft/vscode/issues/1964

Adding fuzzy search to commands can break muscle memory: we keep results in strict alphabetic order to keep commands together that are belonging together and have a stable sorting order.
