### ISSUE TITLE
Scroll performance while creating a bunch of files

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#134075]
Testing #133753

So I created a folder in vscode called `foo` and make sure I "open it" with the twisty so that files under it would be shown. then ran this script which simply:

* creates 10000 files
* waits 30s
* and then removes them all:
```ps1
1..10000 | % {
    $_ > "$_.txt"
}
sleep 30
1..10000 | % {
    Remove-Item "$_.txt"
}
```

Scroll performance is pretty rough when the creation is happening. Once the creation stops happening, then perf returns back to normal almost instantly.

**Comment by bpasero** [comment]
@TylerLeonhardt scroll performance in the explorer or where? Can you run a perf profile and attach it? Maybe run out of sources too to get good method names.

**Comment by TylerLeonhardt** [comment]
> scroll performance in the explorer or where?

Yeah in the explorer. This was on macOS.

> Can you run a perf profile and attach it? Maybe run out of sources too to get good method names.

Can do.

**Comment by TylerLeonhardt** [comment]
This is the first time I'm using the profile feature so just lmk if there's anything I can do to be more helpful.
[Profile-20210929T110623.json.zip](https://github.com/microsoft/vscode/files/7254119/Profile-20210929T110623.json.zip)

**Comment by bpasero** [comment]
Thanks, I tried to reproduce this with a simple node.js script:

```js
const fs = require("fs");

for (let i = 0; i < 10000; i++) {
	fs.writeFileSync(`<PATH TO VSCODE>/foo/${i}.txt`, 'Hello World');
}

setTimeout(() => {
	for (let i = 0; i < 10000; i++) {
		fs.unlinkSync(`<PATH TO VSCODE>/foo/${i}.txt`);
	}
}, 30000);
```

And scrolling was super snappy even when `foo` was expanded and indicating all the files coming in.

The profile I created didn't show anything suspicious. 

Can you maybe do a profile again, this time via the classic tools:

![image](https://user-images.githubusercontent.com/900690/135408141-9873a5ef-bd25-4e6f-bc34-a782fc87759a.png)

You might have to bring that one in via:

![image](https://user-images.githubusercontent.com/900690/135408198-3d7061b1-cfc2-4325-b3e4-810843285fc4.png)

Also: is this a fresh instance, with no special settings or extensions?

**Comment by TylerLeonhardt** [comment]
it was.... pretty smooth that time but had moments where the scroll wasn't fluid. I don't have any extensions or settings installed. I'm running out of sources. I feel like maybe the other programs on my machine could be hurting it.

[CPU-20210930T120002.cpuprofile.zip](https://github.com/microsoft/vscode/files/7261878/CPU-20210930T120002.cpuprofile.zip)

**Comment by bpasero** [comment]
idk, I see most time is spend in the scrolling callback getting decorations:

![image](https://user-images.githubusercontent.com/900690/135591743-cec0e87c-f5d8-46de-8dad-bf268292df08.png)

**Comment by jrieken** [comment]
I'll use that as a chance to re-measure if all the allocation avoiding the tst is doing is actually worth it or if we should start splitting strings.

**Comment by jrieken** [comment]
It's actually two things: one is the performance of the search tree and second is how the decoration service organizes its data. Internally each provider has its own search tree which was OK when it started because there were only two providers, not it is at least 10. So, whatever the search tree costs needs to be multiplied by 10.

**Comment by jrieken** [comment]
So, while rendering is hot I believe it's not the cause any of the stalls/freezes. There is a lot going on with rendering but we only render a few items on screen and therefore only ask for decorations of a few items (32 on my screen/sizing). It all happens in nice chunks of work. I do see one long (~1sec) plateau in the profile and that's when 10 thousand file events are being proceed. It also happens to be the search tree and @bpasero I wonder if you have adopted the `fill`-function? (That's the workaround for the tree not rebalancing)

<img width="489" alt="Screen Shot 2021-10-01 at 11 49 17" src="https://user-images.githubusercontent.com/1794099/135600598-81f9c2a1-925f-457f-b9b8-f88a48b7e938.png">

**Comment by jrieken** [comment]
> I wonder if you have adopted the fill-function? (That's the workaround for the tree not rebalancing)

Nevermind - its consumer checking if they are affected by some changes. Most time is actually spend in doing the "ignore case compare". Maybe it is faster to create throw-away strings and compare them for equality than doing what we do. 

<img width="511" alt="Screen Shot 2021-10-01 at 11 57 44" src="https://user-images.githubusercontent.com/1794099/135601646-ece34ef6-f7e0-42cb-9067-e007bc39f13d.png">
es

**Comment by jrieken** [comment]
Actually still interested in how the search tree is being build. Benchmarking shows that the compare ignore case is better than lower-casing strings but not by much: https://jsben.ch/Z79zb. Tho, the former also creates many strings which GC will need to take care of

**Comment by jrieken** [comment]
Actually still interested in how the search tree for events is created. On the measuring front it turns out that our custom compare ignore case is faster but only marginally and not in safari: https://jsben.ch/FvFx7

**Comment by jrieken** [comment]
So, tweaking how the event is build does matter. I adopted the fill-function for file events (after changing it so that it actually fits here) and handling deletes is now at 100ms (from ~1sec). That's because we likely avoid the tree becoming a flat list here (it's a workaround for not rebalancing but given the tree is build and thrown out it might actually be a good solution...)

<img width="459" alt="Screen Shot 2021-10-01 at 13 03 20" src="https://user-images.githubusercontent.com/1794099/135609755-9e118d60-7eb0-43b4-88c5-54f7fda5f50c.png">

**Comment by bpasero** [comment]
@jrieken cool findings, yeah I forgot to adopt the `fill` function when you added it. 

2 milestones ago I was making a lot of changes to introduce throttling in the renderer and cut off events if a very large number occurs:

https://github.com/microsoft/vscode/blob/dbeff882f511cc2a3427ed9370780687668590ce/src/vs/platform/files/common/fileService.ts#L977-L982

Still, the tst is created in the renderer as before:

https://github.com/microsoft/vscode/blob/33c149f3ad49db462cb451f4db2e01d64b15e40b/src/vs/platform/files/common/files.ts#L665-L688

One thing we have not yet explored: what if the tst is actually created in the file watcher process and then serialised over? That would require some kind of `toJSON` / `fromJSON` method on the tst but would actually offload all the compute for creating the tree to another process. It would probably not help much for the reading side though, only when creating the event...

**Comment by jrieken** [comment]
> what if the tst is actually created in the file watcher process and then serialised over? 

I don't think that will help. Building the tst isn't the bottleneck, e.g it takes ~15ms for 10K deletes (see below). The problem occurs when it is build to a skinny shape so that it basically morphs into a list

<img width="411" alt="Screen Shot 2021-10-01 at 15 33 58" src="https://user-images.githubusercontent.com/1794099/135628828-bb28ef02-1297-4fa7-8bbf-132a8d055043.png">
