### ISSUE TITLE
Forwarded ports still available after disconnecting from codespaces (web)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#134035]
Testing #133889

**Steps to repro**
* Open github codespaces & open a repo
* Start a server
* Open browser and confirm it works
* Close github codespaces browser, the port is still open

Based on the test plan item https://github.com/microsoft/vscode/issues/133889, when we close the window the port should no longer be exposed.

Not sure whether we're supposed to stop exposing ports in this scneario or not, but thats the scenario we're attempting to resolve in the test plan item.

Note: In the above scenario, I'm not using VS Code insiders desktop (everything is in the browser).
Also note, I've test the same scenario with desktop vscode insiders & it works as expected.

**Comment by alexr00** [comment]
Codespaces doesn't use the port forwarding mechanism from https://github.com/microsoft/vscode/issues/133889. I will forward this to the Codespaces folks.
