### ISSUE TITLE
Missing rule for not inserting spaces after/before braces

### ISSUE THREAD

**Issue by shahata** [Microsoft/vscode#13401]
- VSCode Version: 1.5.3
- OS Version: macOS Sierra

Steps to Reproduce:

1. Add `"javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false` to the workspace settings
2. Type `const a = {b: 1};`
3. Format Code
4. Code is now formatted `const a = { b: 1 };`

I guess this is similar to https://github.com/Microsoft/TypeScript/issues/7540 and this rule considers only `[` and `]` as *brackets* and actually a new rule `javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces` should be added to support *braces*: `{` and `}`

**Comment by jrieken** [comment]
fyi - the pre-commit hooks goes with [`tsfmt.json`](https://github.com/Microsoft/vscode/blob/joh/fmtprio/tsfmt.json#L16), so if we change default we should keep them in sync

**Comment by waderyan** [comment]
@shahata thank you for opening this issue. 

@dbaeumer this is confirmed on latest. Is this a feature request for TypeScript language service? Or something we need to implement on our end?

**Comment by dbaeumer** [comment]
@waderyan  Yes, I think so.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11630
