### ISSUE TITLE
File Watcher Linux causes VS Code crash

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#134031]
Testing #133753

1. Have the VS Code repo cloned
2. Open it in the latest stable
3. Launch according to #133753.
4. Run `yarn`
5. Observe file watch changes
6. Run `git clean -xfd` 
7. 🐛 No file watch changes
8. Attempt to rename a file in stable or insiders
9. 🐛 ❗ Both windows will eventually stop responding and crash

This is running on an Ubuntu 20.04 VM, but the native UI remains snappy leading me to believe this is a problem with VS Code and not the VM

**Comment by bpasero** [comment]
As discussed, does it repro without `verbose` and without devtools.

**Comment by lramos15** [comment]
No crashes without `verbose` and without devtools. Will close since this won't affect everyday users
