### ISSUE TITLE
Provide context variables that will allow extension authors to hide commands (menus) based on selected kernel

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#134057]
Jupyter extension exposes a lot of commands, menu items for notebooks & interactive window
Similarly other extension (.NET, julia, node, etc) that support ipynb files also have their contributions.
When installing them, all of these commands are displayed when only some of them are relevant.

E.g. if i open an ipynb file and select a .NET kernel, then there's no point in me seeing the following:
* Jupyter commands in command palette (variables, debugging, etc)
* Jupyter menu contributions (toolbar, cells, etc)

If we have a context variable `kernelExtensionId` or the like, then extension authors can use when clauses to hide them based on the selected kernel.

Yes, today we can do this via `setContext` as well, but that async, hence as you toggle between notebooks icons will flash as the value fro `setContext` will get initialized asynchronously.

**Comment by roblourens** [comment]
If we add a category for kernels, this could be based on that

**Comment by gjsjohnmurray** [comment]
I think #143163 has resolved this.

**Comment by roblourens** [comment]
Thanks @gjsjohnmurray, I think so
