### ISSUE TITLE
Unclear error message when dragging added file

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#134041]
Testing #133922

Dragged a file from local window into a remorehub window. Dragged it from remotehub window into different remotehub window. Got this error which is unlcear:
<img width="708" alt="Screen Shot 2021-09-28 at 11 07 37 AM" src="https://user-images.githubusercontent.com/8586769/135141852-c869d8b8-39a7-43f3-93f4-f912a2c86ec3.png">

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/134047
