### ISSUE TITLE
Terminal tab title - using cwdFolder

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#134003]
Testing #133549

See the recording below:
- cwdFolder appears twice in the title
- Terminal title is not maintained on window reload

![recording (1)](https://user-images.githubusercontent.com/3372902/135088110-d5287b5a-b5fb-4139-87a1-af2c2d07df49.gif)

**Comment by meganrogge** [comment]
you have title set to ${cwd} and description, by default, is ${cwd} .
the single tab view will show title - description. so ${cwd} - ${cwd} is expected given the settings you used

**Comment by lszomoru** [comment]
@meganrogge, why does the title/description change on reload?

**Comment by meganrogge** [comment]
Sorry - did not see that part - will investigate
