### ISSUE TITLE
Can not select text in terminal created in editor area

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#134068]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders
- OS Version: Windows 10

* git log
* double click on a commit sha
* kept seeing

![image](https://user-images.githubusercontent.com/876920/135178455-adbacfc9-4980-4f0f-9f0d-4641baa5856e.png)

**Comment by meganrogge** [comment]
can you attach a gif of this? I can't repro the issue
