### ISSUE TITLE
Support customized highlight color for the item in outline view (Follow Cursor option)

### ISSUE THREAD

**Issue by raymond-wh-leung** [microsoft/vscode#134051]
The cpp extension supports a "Follow Cursor" option in the outline view. For example, the selected item in the outline view will be based on the current function the cursor is in in the source *.cpp file. The selected / highlighted item in the outline view however is hard to see especially in dark theme. The default color is light grey (and in dark theme it is hard to see.) The bug is about allowing the selected / highlighted color item in the outline view to be customized.

**Comment by jrieken** [comment]
Can be done with normal list theming. Add this to your settings.json-file and tweaks `list.XYZ` colors to your likings

```
"workbench.colorCustomizations": {
        "list.XYZ": green;
    },
```

**Comment by raymond-wh-leung** [comment]
> Can be done with normal list theming. Add this to your settings.json-file and tweaks `list.XYZ` colors to your likings
> 
> ```
> "workbench.colorCustomizations": {
>         "list.XYZ": green;
>     },
> ```

Nice!! Worked great, thanks!!
