### ISSUE TITLE
No way to interact with definition hover preview

### ISSUE THREAD

**Issue by freebroccolo** [Microsoft/vscode#13402]
Since @joaomoreno's work in [#2330](https://github.com/Microsoft/vscode/issues/2330#issuecomment-245214728), hovers use a widget with scrollable cells and it works very nicely for type info, docs, etc.

Definition previews for a symbol (shown when holding ⌘ on hover) can also show up in the hover widget in a scrollable cell. But in this case it seems impossible to interact with the scrollable definition preview content because the hover disappears as soon as you mouse over it if you are holding ⌘.

Is there a way to fix this?

**Comment by joaomoreno** [comment]
We can maybe make the <kbd>⌘</kbd> sticky.

**Comment by joaomoreno** [comment]
#2330 didn't actually break this, it's been like this for a while.

**Comment by jrieken** [comment]
> impossible to interact with the scrollable definition preview content

As in scroll, copy&paste or what else do you have in mind

**Comment by joaomoreno** [comment]
I believe he just wants to use the mouse to select text in there and copy-paste stuff yeah. I guess for that we'd need to be able to release <kbd>⌘</kbd> and still see the preview.

**Comment by freebroccolo** [comment]
@jrieken I was really only hoping for being able to scroll the preview since sometimes it will show up with more content than fits in the cell. So anything beyond that (e.g., copy&paste) would be icing on the cake.

**Comment by aniljava** [comment]
I like to add following for consideration:

- Similar to eclipse, click on hover box makes it sticky.
- Currently mouse out of box closes the  hover box. If the hover box is sticky close only after mouse is clicked outside the box or after mouse out for certain time. That way if some one was selecting or scrolling do not have to restart the scrolling and selecting process again if mouse accidentally leaves the boundary. 
- Along with H/V scroll, allow resize after the click. This helps wrapped content to get unwrapped and provide a better view.
- For links in the content of hover. If pointed object can be rendered in hover, render on same box for normal click, and new tab if it is a ctrl + click.
- User configurable option to specify preference on location of hoover (when screen/editor permits). Possible selections : [bottom, bottom-start-at-end-of-identifier, top .. ]

**Comment by jrieken** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
