### ISSUE TITLE
Built in renderers for notebook outputs not overridden by renderers contributed by extension authors

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#134172]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders
- OS Version: Ubuntu

Steps to Reproduce:

* New machine
* Install VS Code insiders
* Open an existing notebook
* text/latext output is rendered by built-in renderer
* Install jupyter based on VSCodes recommendation
* Re-load VSCode
* text/latext output is still rendered by built-in renderer

Note: This workflow is not going to work as we know of a lot of text/latext that doesnt' work with the built-in renderer, & novice users won't know that they need to change the renderer to Jupyter Notebook renderer.

I've submitted a PR to remove the text/latex renderer from VS Code https://github.com/microsoft/vscode/pull/134168

**Comment by mjbvz** [comment]
I believe this is where we select the renderer (we currently always take the first one):

https://github.com/microsoft/vscode/blob/245fffbce1b39a5891d7f9c56b6caabd05f1f07d/src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts#L887

I agree that automatically deprioitizing built-in renderers makes sense

**Comment by alexr00** [comment]
How do I get the latex mime types to show in that picker? I only see one: 
![image](https://user-images.githubusercontent.com/38270282/139677267-dac97a26-aa61-4ad8-aa77-5763d6a8886c.png)

**Comment by mjbvz** [comment]
To verify:

1. Make sure you have the jupyter extension installed and are in an ipynb notebook
2. Run 
```
%%latex
\begin{align}
\nabla \cdot \vec{\mathbf{E}} & = 4 \pi \rho \\
\nabla \times \vec{\mathbf{E}}\, +\, \frac1c\, \frac{\partial\vec{\mathbf{B}}}{\partial t} & = \vec{\mathbf{0}} \\
\nabla \cdot \vec{\mathbf{B}} & = 0
\end{align}
```

3. Confirm the output is rendered nicely 

<img width="515" alt="Screen Shot 2021-11-01 at 9 20 35 AM" src="https://user-images.githubusercontent.com/12821956/139704991-38ad339e-5156-44ab-88d1-d8a047a3fbc4.png">
