### ISSUE TITLE
Does it makes sense that `files.watcherInclude` can be configured for a workspace?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#134145]
Testing #133753

Is there a scenario where this makes sense? Just an open question.

**Comment by bpasero** [comment]
Yeah I think it does: if someone wants to check-in this configuration because a workspace is known to have symlinks then this would allow a nice self-contained experience, not requiring users having to configure that. 

I didn't want to artificially limit the setting to global scope.
