### ISSUE TITLE
Re-open with does not focus inactive editor

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#134131]
Attempting to fix https://github.com/microsoft/vscode/issues/127083 I discovered that it isn't easy to focus a replaced editor. Activation options are ignored and calling open afterwards no-ops. 

Take the following code snippet for example
```js
			await resolvedEditor.group.replaceEditors([
				{
					editor: editor,
					replacement: resolvedEditor.editor,
					forceReplaceDirty: editor.resource?.scheme === Schemas.untitled,
					options: resolvedEditor.options
				}
			]);
			await resolvedEditor.group.openEditor(resolvedEditor.editor, resolvedEditor.options);
```

**Comment by bpasero** [comment]
You cannot pass the `resolvedEditor.options` in: there is a property `inactive` within that tells the editor control to not open it as active. Sorry for that, I forgot about this yesterday when we talked. Will push a change to open the editor after replacing.

**Comment by bpasero** [comment]
**Verification:**
* open some editors
* right click on an inactive editor tab -> Re-open with
* select a custom editor
* make sure the editor becomes active after opening
