### ISSUE TITLE
Comments in a .json file should be highlighted as invalid syntax

### ISSUE THREAD

**Issue by Vannevelj** [Microsoft/vscode#1341]
A JSON structure [cannot contain comments](http://stackoverflow.com/a/4183018/1864167). However when you create a `.json` file and insert something like this:

```json
{
    "TEST": "Some value", // some comment
}
```

it will highlight the `// some comment` part as a comment. For `.js` files this should be okay but for `.json` files it hides the issue that you can't use a comment in that location.

It would be helpful if the highlighting could be dropped and even be highlighted as a syntax error.

**Comment by dbaeumer** [comment]
@aeschli can you please comment.

**Comment by aeschli** [comment]
You are right, comments are not part of regular JSON, but for several of our configuration files (settings.json, launch.json...) we use a variant of JSON that has comments. Other tools do the same. 
Our tokenizer is friendly and renders these comments nicely. We'd like to keep it friendly.
