### ISSUE TITLE
VSCODE FREEZE

### ISSUE THREAD

**Issue by Noel-Emmanuel16** [microsoft/vscode#134174]
Issue Type: <b>Bug</b>

Anytime I open vscode, my system freezes and i have to restart it to unfreeze. It s really discouraging me from coding. Please i need a solution to fix this issue. I'm using a 4gb RAM, 64 bits computer with Ubuntu 20.04

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:01:43.795Z)
OS version: Linux x64 5.4.0-86-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Pentium(R) Dual-Core  CPU      E5300  @ 2.60GHz (2 x 2593)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|5, 5, 3|
|Memory (System)|3.72GB (0.11GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id aebc3b38-dc9d-4a98-827f-045bfd92749c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.6.15
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|3.1.1
prettier-vscode|esb|9.0.0
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
material-icon-theme|PKi|4.10.0
vscode-wakatime|Wak|17.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis400:30374798

```

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by deepak1556** [comment]
Can you attach the output of `code --verbose`

**Comment by Noel-Emmanuel16** [comment]
> /needsMoreInfo
> 
> Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
