### ISSUE TITLE
git status information is repeated

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#134162]
```
Version: 1.61.0-insider
Commit: 4fbe0344a0cedaf2a04edef728c9a3f27777cc6c
Date: 2021-09-29T05:28:54.500Z
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```
Noticed while selfhosting and having a single folder opened:
<img width="403" alt="Screen Shot 2021-09-29 at 22 16 02" src="https://user-images.githubusercontent.com/5047891/135342126-07b76a38-4636-4fe7-9ded-d7f7df7b0891.png">

**Comment by gjsjohnmurray** [comment]
A consequence of the changed default for `scm.alwaysShowRepositories`

See https://github.com/microsoft/vscode/issues/133950#issuecomment-929033776 and subsequent discussions.

**Comment by hediet** [comment]
Also related: https://github.com/microsoft/vscode/issues/133588

I was missing the sync button when only dealing with a single repo.
