### ISSUE TITLE
VSCode does not installs extension dependencies automatically

### ISSUE THREAD

**Issue by aniketnitrr** [microsoft/vscode#134104]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: macOS 0.15.7

Steps to Reproduce:

1. Create an extension with some dependencies under 'dependencies:' [ ] in package.json. 
2. Add node_modules/** in .vscodeignore.
3. Package it using `vsce package`.
4. Install the extension using 'Install using VSIX'.
5. The extension installs but while activating its throws error - Activating extension failed: Cannot find module.
Note - Doing npm install in extension directory does the job. But i want vscode to autmatically install my extension dependencies.

**Comment by gjsjohnmurray** [comment]
The dependencies should have been packaged by vsce so they ship within your VSIX.

What version of vsce are you using?

I also notice that your VS Code version isn't current. The latest is 1.60.2.

**Comment by aniketnitrr** [comment]
Thanks.
Is it necessary to ship it within VSIX ? can they be fetched by vscode when the extension is installed ?
vsce version - 1.100

**Comment by gjsjohnmurray** [comment]
I am not aware of a built-in way to have an extension download dependencies after installation. I think some extension developers code their own mechanism to do this.

**Comment by aniketnitrr** [comment]
Ok thanks. I was assuming vscode automatically installs dependencies. I have to remove `node_modules/**` from my .vscodeignore file.
