### ISSUE TITLE
Hovering over readonly icon does not say "Readonly"

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#134120]
Testing #133743

1. Have a readonly file, hover over its name -> you get a nice hover that says "Readonly" at the end
2. Hover over the lock icon on that file -> you get the same hover but without the "Readonly" 🐛 

Similar problem: in Open Editors when you hover over the lock icon you do not get any hover at all.

![Screenshot 2021-09-29 at 13 47 07](https://user-images.githubusercontent.com/1926584/135262413-8be25875-9b24-4dbc-b7d1-dac32e36cbb6.png)

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"file-decorations"

**Comment by bpasero** [comment]
I get the same in other places like SCM or Explorer: hovering over a decoration does not bring up the tooltip.

**Comment by bpasero** [comment]
Sounds a bit like https://github.com/microsoft/vscode/issues/122427
