### ISSUE TITLE
Make your programme safe (trial and full version) in c#

### ISSUE THREAD

**Issue by sofide13** [microsoft/vscode#134125]
https://www.youtube.com/watch?v=Lv2n6icoGx0&t=48s
download the source code 
01-Form main 
https://bit.ly/3EqJMbL
02-Form for code generation 
https://bit.ly/3tQ5Szo
03-Form for validating the code and activating
https://bit.ly/2VTo9zn
Reference of fox learn
https://bit.ly/3kPVXXC
thank you

**Comment by jrieken** [comment]
The appears to spam and unrelated to vscode

**Comment by sofide13** [comment]
I searched a lot on the activation of a form and I found in your site
several author who speaks on this subject


Le mer. 29 sept. 2021 16:09, Johannes Rieken ***@***.***> a
écrit :
