### ISSUE TITLE
Cell toolbar should be shown on focus and on hover

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#134139]
Testing #133903

Currently we show the cell toolbar only for cells that have focus.
I think we should also show it for cells that are being hovered over.
That way me as a user can run by line just by using the mouse and without clicking into the cell first.

**Comment by roblourens** [comment]
We do have `notebook.cellToolbarVisibility` for this. I think the default was picked to avoid noise from moving the cursor around.
