### ISSUE TITLE
CLI(macOS): explore open command path for older versions

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#134111]
Refs https://github.com/microsoft/vscode/issues/134023

We have been using the `--stdout` and `--stderr` option of the `open` command which mocks the standard pipes of the launched application and writes the data to the provided file path. We then read and print contents from this file via the node cli process to print `--verbose` and `--status` outputs. Turns out these options were recently added and we don't have a good way to perform this pre Big Sur. Issue is mainly to explore alternatives,

1) Explore building a wrapper app around https://developer.apple.com/documentation/appkit/nsworkspace/1534810-launchapplication (the non-deprecated version is only available from 10.15+) that cli can use. 

*Pros*:

* Achieves the same effect as `open`

*Cons*:

* We would end up replacing the node cli with this native cli
* There is no option for mocking the standard outputs, so we have create a trampoline system using `NSTask` https://developer.apple.com/documentation/foundation/nstask that can mock it (ie) Cli script --LaunchService-> Native wrapper app --NSTask-> Application 

2) Electron now has option to log to file https://github.com/electron/electron/blob/main/docs/api/command-line-switches.md#--enable-loggingfile and VSCode can also log data to file. We can launch via `open` without standard output mocks and read data from the pre defined files.

*Pros*:

* No need to write a wrapper app
* Still achieves the effect of launching from `open`

*Cons*:

* Since the log files are written by different processes, cli will provide output non-synced

3) Only use the `open` command path on versions that support `--stdout` and `--stderr` options.

*Pros*:

* Well tested path still gets used for the older versions

*Cons*:

* We won't be able to address https://github.com/microsoft/vscode/issues/60579 for these versions

4) Use `open` on all versions and only switch to old code path for `--verbose`, `--status` when the relevant support is not available

*Pros*:

* Well tested path still gets used for all versions

*Cons*:

* It is possible https://github.com/microsoft/vscode/issues/60579 might reappear as the launch process of the app is now mixed depending on the cli option used.

**Comment by bpasero** [comment]
I like option 2 and do not think that `Since the log files are written by different processes, cli will provide output non-synced` is an issue because that is exactly what we have now when `open` is used (we write to a file and poll from it).

**Comment by rzhao271** [comment]
It looks like we've implemented option 3; there's an if statement that checks whether the user's on Big Sur or newer in `cli.ts`.
