### ISSUE TITLE
terminal font is super small

### ISSUE THREAD

**Issue by zhanglongqi** [microsoft/vscode#134193]
Issue Type: <b>Bug</b>

terminal font is super small

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (22.68GB free)|
|Process Argv|. --crash-reporter-id 1448b3cf-9bc8-4f73-8551-af1cbd1a8938|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
python-manifest-template|ben|1.0.1
django-html|bib|1.3.0
django-snippets|bib|1.1.1
systemd-unit-file|coo|1.0.6
mysql-syntax|jak|1.3.1
python|ms-|2021.10.1282820105-dev
remote-containers|ms-|0.194.3
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
shellman|Rem|5.6.0
shebang-snippets|rpi|0.1.4
code-settings-sync|Sha|3.4.3
gitconfig|sid|2.0.1
vscode-icons|vsc|11.6.0
material-theme|zhu|3.13.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis300:30374797

```

</details>

**Comment by zhanglongqi** [comment]
![image](https://user-images.githubusercontent.com/956693/135426156-af2de91c-6a03-4f42-824b-a614c1f34545.png)

**Comment by zhanglongqi** [comment]
![image](https://user-images.githubusercontent.com/956693/135427284-55ee12d8-ef6e-4618-b959-b8a1c4f3472a.png)

**Comment by Tyriar** [comment]
It's because the font '' was being used, this is changing in 1.75 so it shouldn't be possible to see this anymore.
