### ISSUE TITLE
No background highlighting after F4 - Find Next

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/vscode#134114]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.2
- OS Version: 10

Steps to Reproduce:

```
{
    "workbench.colorCustomizations": {

        "editor.lineHighlightBackground": "#000000"
    }
}
```

1. Use Find in Files to search for something
2. Hit F4
3. No background highlighting.
4. Press right
5. Background highlighting.

On big windows, this makes it quite hard to find the current line.

![image](https://user-images.githubusercontent.com/2218936/135259485-b7e8c532-0b73-4dc9-b971-6e37a776ba49.png)

![image](https://user-images.githubusercontent.com/2218936/135259511-a8da020a-4ba2-4a01-9e12-ca495bf9a82a.png)

**Comment by alexdima** [comment]
We have two distinct concepts coming together here.

The line highlight is always rendered in code editors when there is no selection (even when not using search). In the default light theme it looks like this:


https://user-images.githubusercontent.com/5047891/135281608-ae05ff1b-1c64-48a3-b8b1-61712442cb12.mp4


The second concept comes from search which highlights a find match in the editor when the find match is clicked. It looks like this. I have noticed that this highlight is now very nervous, it sometimes removes itself very quickly:

https://user-images.githubusercontent.com/5047891/135282020-97f72c3a-a163-494e-9aff-e3fb659e1a2f.mp4

@roblourens I think the yellow line highlight is added by the search viewlet. Could you please investigate why it often disappears quickly?

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/106209#issuecomment-805290211

**Comment by roblourens** [comment]
I think this is a dupe then. Reopen if there is something about the editor line highlight to discuss here.
