### ISSUE TITLE
File annotated as read-only although it isn't

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#134122]
See screen cast

https://user-images.githubusercontent.com/1931590/135268106-59eb0c05-1351-4cb6-bcce-1192b5a8e2f1.mp4

Steps to reproduce using the github remote repository extension (latest insider)

- open the remote repository microsoft/lsif-node
- enable rich navigation (press the layer button in the lower left) and selected `Latest Indexed`
- open tsc/src/typescripts.ts
- observe: file is readonly
- close file
- switch index mode to `Current commit & latest index`
- open another file
- Observe: it is writeable
- open typescripts.ts again
- Observe it is writable but marked as readonly (lock in explorer and tab)

**Comment by bpasero** [comment]
@dbaeumer any chance you could try out of sources? I pushed a fix for https://github.com/microsoft/vscode/issues/133947 earlier and that could be a reason for this. Basically decorations would linger around after an editor is closed...

**Comment by dbaeumer** [comment]
Can give it a try.

**Comment by dbaeumer** [comment]
Is fixed in source.

**Comment by bpasero** [comment]
Thanks!
