### ISSUE TITLE
Parsing recursive make problemMatcher: Resolved (worked around)

### ISSUE THREAD

**Issue by behines** [microsoft/vscode#134165]
_Originally posted by @alexr00 in https://github.com/microsoft/vscode/issues/11663#issuecomment-544418645_

With respect to the original issue https://github.com/microsoft/vscode/issues/11663, I could not find any satisfactory answers in any of the threads here; all had been prematurely closed, it seems.

In any event, the problem seems to be that problemMatcher can't be trained to scan multiple lines.  But the "awk" program can.  Since I am building on a Linux host, I constructed an awk command to insert absolute pathnames into any error message that is emitted.

So I thought I would share in case it helps someone else.  I simply pipe the output of make into awk, which patches up the pathnames in the output to be digestible by the problemMatcher.  Here are the key lines from my new tasks.json.  

      "command": "make |& mawk -Winteractive 'BEGIN{ORS=\"\"} /Entering directory/ { curdir=substr($4,2,length($4)-2) }  /(warning|error):/ { print curdir \"/\" } { print $0 \"\\n\" }'",
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "problemMatcher": {
        "owner": "cpp",
        "fileLocation":  [
          "absolute"
        ],

It's a little clunky-looking because you have to escape the " and \ characters in the awk command.  But it works.

Well, it works for folders beneath the main build folder.  It watches for the recursive make process to say "Entering directory", then remembers the folder name.  Then when it sees an error or warning line, it prepends the folder name to that line.  Since there is no "Entering directory" for the top-level build folder, it won't work for errors in that folder.  I'm sure it can be improved to handle that case as well, but I don't need that for what I'm doing.

Note that I use "mawk -Winteractive" rather than awk.  This is because awk otherwise buffers all its output, so you don't see anything in the Terminal window until the build is done.  The -Winteractive flag of mawk causes it to not buffer, so you can watch the build in realtime.

**Comment by alexr00** [comment]
@behines thanks for posting your workaround! I will leave the issue open for a little while for visibility and then close it.
