### ISSUE TITLE
Weird visual artifact (triangle/caret) rendered in terminal after yarn install

### ISSUE THREAD

**Issue by srmagura** [microsoft/vscode#134138]
Issue Type: <b>Bug</b>

### Steps to Reproduce

1. Set the `terminal.integrated.gpuAcceleration` setting to auto, on, or canvas. The bug does not occur with GPU acceleration off.
1. Clone [my repo](https://github.com/srmagura/vscode-triangle-repro), or create your own with:
```bash
yarn set version berry
yarn set version latest
yarn init
yarn add --dev rimraf
```
The choice of `rimraf` as a dependency is completely arbitrary. The important thing is that you have at least one dependency.

2. If this isn't your first time testing this, reset everything by killing and restarting the integrated terminal and then running `yarn cache clean`.
3. Run `yarn` to install packages.
4. Switch from the Light+ theme to the Dark+ theme (or vice versa). This step isn't truly necessary, but it makes the triangle artifact more obvious.

**Actual behavior:**
A visual artifact in the shape of a triangle/caret is displayed in the integrated terminal. It stays in the same position for the entire terminal session, regardless of what commands are run after `yarn install`. The color of the triangle will be white if you started in the Light+ theme, or black if you started in the Dark+ theme.

Look at the first "PS" after the `yarn install` completed:
![image](https://user-images.githubusercontent.com/801549/135308516-cc0e61ca-a307-4780-bf4b-dee04855a860.png)

**Expected behavior:**
There is no triangle artifact.

### Additional Context

* The bug **does** occur with all extensions disabled. (`code --disable-extensions`)
* Resizing the integrated terminal causes the triangle to disappear.
* Changing `terminal.integrated.gpuAcceleration` causes the triangle to disappear.
* I am using PowerShell 7.1.4.
* The issue does not occur when running in a standalone PowerShell window.
* This is a super low priority issue, I just think it's kind of amusing and had some free time. 😆

--------------------

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z). Also tested with 1.61.0-insider (4fbe0344a0cedaf2a04edef728c9a3f27777cc6c).
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (5.06GB free)|
|Process Argv|-n --crash-reporter-id 24f0b409-7147-40a8-84cc-a20f14042031|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis300:30374797

```

</details>

**Comment by Tyriar** [comment]
If you see this again, could you run the new show texture atlas command and paste in the resulting image?

![image](https://user-images.githubusercontent.com/2193314/194886300-d7e4ded9-d0f8-4f61-9ca1-2c55cfb59697.png)

**Comment by Tyriar** [comment]
It's not garbled, just the background is transparent.

Could you run the toggle escape sequence logging and check what gets logged when running yarn? This will tell us what character the shell is sending the terminal to display.

**Comment by Tyriar** [comment]
Let's close this out and reopen if it looks like a bug with more info
