### ISSUE TITLE
The text box in the issue reporter is a bit too crowded

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode#134148]
Testing microsoft/vscode-python#17041

Consider making the textbox bigger. Those 3 dropdowns could be on a single row to make some space.

![image](https://user-images.githubusercontent.com/20347396/135164487-10dcad95-b849-47cb-81ed-15194467585b.png)

**Comment by JacksonKearl** [comment]
@TylerLeonhardt owns issue reporter.
