### ISSUE TITLE
Readonly lock decoration should be to the left of the filename

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#134121]
Testing #133743

Currently we put the readonly lock decoration next to the clickable X. This has the following problem:
* It is the same size as X, it looks like an icon, everything looks like an `ActionBar` -> users want to click it, but it is not clickable. It has no effect!

Due to that I suggest that we put the icon decorations to the left of the file name, and not to the right so there is a distinction between the clickable and non clickable ones.

The only distinction I found now is that there is no hover feedback. Which is cool.
Maybe we could introduce another distinction so that we do not have to move it left.

![Screenshot 2021-09-29 at 13 51 22](https://user-images.githubusercontent.com/1926584/135262971-c580c2e3-5b15-4141-9a8d-b0c9e6448c70.png)

**Comment by gjsjohnmurray** [comment]
Moving it to the left will give the same problem for users who set `"workbench.editor.tabCloseButton": "left"`

I think the lack of hover feedback is a good enough clue that it's not an action button, but equivalent to the file decorations (e.g. git U, M etc).

**Comment by isidorn** [comment]
Good point, but I do not care about less than 1% of users that changed that setting :) We should have good defaults.

**Comment by bpasero** [comment]
Not sure I would agree: all our decorations today appear at the end of the label very consistently throughout the entire UI.

**Comment by isidorn** [comment]
I am not saying we have to move it to the left. I am saying currently it looks like an actionBar, let's do something else except the hover to make sure users do not click on it. I am open for ideas!

**Comment by bpasero** [comment]
@isidorn maybe https://github.com/microsoft/vscode/issues/133422 would help you

**Comment by isidorn** [comment]
Aha that would definitely help!

**Comment by gjsjohnmurray** [comment]
Maybe faded so it looks like a disabled button?
