### ISSUE TITLE
Please add c++ build and run 

### ISSUE THREAD

**Issue by GH0STH4CKER** [microsoft/vscode#134181]
I would like if vscode has a way to build c++ projects and run easily

**Comment by IllusionMH** [comment]
VS Code doesn't ship support for C++ out of the box and it's provided by extensions and (supported) compiler of your choise.

Please see steps https://code.visualstudio.com/docs/languages/cpp and https://code.visualstudio.com/docs/cpp/introvideos-cpp for setup steps and other information on how to use C++ in VS Code.

**Comment by GH0STH4CKER** [comment]
I have tried  everything but nit working
