### ISSUE TITLE
Be able to specify Chrome web store extensions to install when using `"pwa-chrome"`

### ISSUE THREAD

**Issue by davetapley** [microsoft/vscode#134167]
Be able to specify Chrome web store extensions to install when using `"pwa-chrome"` per:
https://code.visualstudio.com/docs/nodejs/browser-debugging#_launch-configuration

---

e.g. https://chrome.google.com/webstore/detail/fake-data-a-form-filler-y/gchcfdihakkhjgfmokemfeembfokkajj/related?hl=en

**Comment by connor4312** [comment]
It looks like there is a [`--load-extension` command line](https://peter.sh/experiments/chromium-command-line-switches/#load-extension) flag, where if you downloaded the extension locally you can load it from -- that argument can be specified in the `runtimeArgs` property in the package.json.

Not sure that I want any more intricate built-in support here

**Comment by davetapley** [comment]
> that argument can be specified in the `runtimeArgs` property in the package.json.

@connor4312 I presume you meant launch.json? 😁 

If so then that's so nearly a great workaround, except I forgot to mention this is for use in a Codespace, and I suppose that puts this issue in the awkward _devcontainers isn't Codespaces_ area 😑 

For the record this approach won't work in a Codespace because the extension path has to be local since Chrome runs local, and that would require user to manually copy the `.crx` local, which is as burdensome as just reinstalling extension every time.

---

Perusing those [command line switches](https://peter.sh/experiments/chromium-command-line-switches/) I couldn't see anything which implied that you could pass profiles/sync options in directly (i.e. not ultimately referencing a local path), so I fear this is a non-starter for Codespaces? 😞

**Comment by connor4312** [comment]
Yes, launch.json, sorry.

If we had some official support for this it would be _possible_ to automatically copy the extension directories to the local machine if they don't already exist...
