### ISSUE TITLE
vscode not running correctly in node child_process

### ISSUE THREAD

**Issue by jonnytest1** [microsoft/vscode#134197]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.2
- OS Version:

Steps to Reproduce:

1. create a file like
```
const { exec } = require("child_process");
exec("code --help", (err, sdout, stderr) => {
  console.log(err, sdout ,stderr);
});
```
2. run the file with node
3. no output

**Comment by roblourens** [comment]
Works for me

**Comment by aeschli** [comment]
Works for me too (Ubuntu, Windows)

**Comment by jonnytest1** [comment]
> Works for me too (Ubuntu, Windows)

ok weird - it owrks on my host machine but inside my vm i get no output 🤔
