### ISSUE TITLE
Trying to install Python extension on VS Code but getting error Cannot read property 'uri' of null

### ISSUE THREAD

**Issue by prashantrpatil** [microsoft/vscode#134157]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.18363
- Extensions: none
---

Steps to Reproduce:

1.
2.
![image](https://user-images.githubusercontent.com/15776092/135325927-b52d38e4-c781-4453-9367-e82d24bddf21.png)

**Comment by TarunavBA** [comment]
@prashantrpatil first update `VSCode`

**Comment by sandy081** [comment]
Please update VS Code and try again. If you repro the issue still, please reopen with steps to repro,
