### ISSUE TITLE
Permalink Copy in github web editor 

### ISSUE THREAD

**Issue by Sondeyy** [microsoft/vscode#134126]
Please provide the ability to copy links/urls to specific line numbers like it already works in github.com. 

For example I can create this permalink on the github website. https://github.com/microsoft/vscode/blob/cb5a2323b1024a0ae2db4575b88dfe77ca1c62c1/README.md#L1
(`https://github.com/microsoft/vscode/blob/cb5a2323b1024a0ae2db4575b88dfe77ca1c62c1/README.md#L1`)
This is done by clicking on the line number and copynig the link/permalink.

I want to be able to also do that when using the github web editor, which is opened by pressing '.' (dot key) while viewing a repository. Since I often use that to navigate through files, it would be very useful to be able to copy a line link immediately. 
![grafik](https://user-images.githubusercontent.com/64478507/135276188-4169a3da-2712-4eb3-815f-251fd1d6d43d.png)

**Comment by eamodio** [comment]
This would require some new gutter support in the extension api. Although if you have the GitHub Pull Requests and Issues extension installed, you can right-click on any line and copy a permalink from the `Copy as` submenu

**Comment by alexdima** [comment]
We could simply create a command for this that could take the editor selection.
