### ISSUE TITLE
Want to increase the multi-cursor function

### ISSUE THREAD

**Issue by cw19931024** [Microsoft/vscode#13412]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 
Like the multi-cursor function, hoping to have the same function as sub3
2. 
Sorry，English is bad

**Comment by isidorn** [comment]
Can you please provide more details. What exact multi cursor funcitonlity from sublime 3 are you missing. If you english is bad you can also attach a gif which shows the functionlity in sublime 3 which is missing in vscode

**Comment by isidorn** [comment]
Closing this issue until more data is provided.
Thank you for the understanding
