### ISSUE TITLE
Info/Error Bar messages should specify their source

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#13410]
As a user, it can be difficult to diagnose issues when there are multiple extensions installed because it's not always clear whether it's an extension, or vscode, and if it's an extension, which one is it? This causes confusion like https://github.com/Microsoft/vscode/issues/13356. 

What if infobars also specified the original source, rather than putting the onus on extension authors to be sufficiently descriptive with every single message string they write? Or maybe we could provide a standard way of jumping to further documentation about the message? (Right now, you can sort of do that by specifying a custom button, but it may be worth providing a little more consistency here)

**Comment by sandy081** [comment]
@mousetraps To be sure, is this related to the message prompt we get on the top ? Or problems view?

**Comment by mousetraps** [comment]
@sandy081 Will clarify the title. It's related to the message prompt at the top. 

It may also be worth thinking about for the problems view, but for different reasons - convenience rather than disambiguation - so we can file a separate issue for that.

**Comment by sandy081** [comment]
@mousetraps We already show the source of the problem in the Problems view.

**Comment by bpasero** [comment]
This landed via https://github.com/Microsoft/vscode/pull/43770 and can be tried out in our preview release: https://code.visualstudio.com/insiders/
