### ISSUE TITLE
Keeps setting up the GIT as Master not Main

### ISSUE THREAD

**Issue by BelleCode** [microsoft/vscode#134170]
Issue Type: <b>Bug</b>

This should be changed and automatic?!!?

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (6.13GB free)|
|Process Argv|-n --crash-reporter-id b03ad6ad-eacc-4c27-8c5c-c151e9a6fffc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
bootstrap-5-snippets-by-coder-foundry|Cod|1.2.0
vscode-eslint|dba|2.1.25
auto-rename-tag|for|0.1.8
beautify|Hoo|1.5.0
theme-monokai-pro-vscode|mon|1.1.19
csharp|ms-|1.23.15
vscode-edge-devtools|ms-|1.3.1
cpptools|ms-|1.6.0
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.6.1
bootstrap4-vscode|the|6.1.0
savecode|thi|0.1.4
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.6.0
JavaScriptSnippets|xab|1.8.0
five-server|yan|0.0.33
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis300:30374797

```

</details>

**Comment by yume-chan** [comment]
Code follows your git config. Change with

```sh
git config --global init.defaultBranch main
```

**Comment by BelleCode** [comment]
Thanks!
