### ISSUE TITLE
titlebar zooms in and out when I zoom in and out

### ISSUE THREAD

**Issue by ZainMalik00** [microsoft/vscode#134166]
Issue Type: <b>Feature Request</b>

Why does the titlebar zoom in and out when I zoom in and out? I doesnt make sense, no other title bar does this with zoom. I fixed this on my own electron application, feel free to contact me at zain.superman@gmail.com

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by sbatten** [comment]
@ZainChen This is an accessibility feature when the menubar is in the title bar. If you don't use the menubar, you can set `window.menuBarVisibility` to `hidden` and the titlebar will remain unzoomed
