### ISSUE TITLE
Cant shrink terminal if i resize it all the way to top , video attached

### ISSUE THREAD

**Issue by Shomy032** [microsoft/vscode#134160]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.2
- OS Version: Ubuntu 20.04.3 LTS

Steps to Reproduce:

1. open vscode
2. open new terminal
3. resize terminal all the way to top
4. you cannot resize it back
5. if you close it and open new one position is remembered

video attached :

https://user-images.githubusercontent.com/79797151/135335416-d38c1421-c28c-4ea6-bf31-450a8f9cfa17.mp4

**Comment by meganrogge** [comment]
I can't reproduce this on Insider's. Can you?

**Comment by Shomy032** [comment]
@meganrogge 
Yes i can reproduce it both in vscode and insiders ,
are you doing it like in my video?
 
 new video attached :

https://user-images.githubusercontent.com/79797151/135351066-ed4f6207-fb6d-4c57-877f-1abadcc1fbb8.mp4

**Comment by meganrogge** [comment]
@sbatten thoughts?

**Comment by sbatten** [comment]
![image](https://user-images.githubusercontent.com/6561887/135665162-8b2f9593-21e3-4f32-8e35-036ef5e0bf6f.png)
