### ISSUE TITLE
Theme by project

### ISSUE THREAD

**Issue by FranGomezVenegas** [microsoft/vscode#134191]
In the case you have one 'r&d' project to develop new features that you want to move to your dev project then it would be great to find a better and visual way to distinguish in which one you are currently in than just the project name in the window title.

I was thinking about applying one different theme for each project might be a great thing but themes are not project-based AFAIK.

Thanks in advance

**Comment by IllusionMH** [comment]
/question

You already can set `workbench.colorTheme` in workspace settings (select Wokrspace tab in settings editor of manually create/edit `.vscode/settings.json` file in project folder).

Alternatively you can use `workbench.colorCustomizations` in Workspace settings to override colors of separate parts of interface.
For this approach it's probably better to use [Peacock extension](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) to customize them for you.

**Comment by FranGomezVenegas** [comment]
Great! Thanks, it seems to be a gap in my knowledge, cool
