### ISSUE TITLE
IW doesn't work with "View: Join All Editor Groups"

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode#134158]
### What happened?

Calling "View: Join All Editor Groups" from the command palette frequently leads to visual artifacts when using the IW.

In this screen recording, after calling "View: Join All Editor Groups", I expect to only see the Python file. Instead the file is overlayed by a remnant of the IW. There's no reliable way of getting rid of this artifact. Just playing around with the tabs and editor groups sometimes makes it disappear.

https://user-images.githubusercontent.com/30958850/135086657-7408e37f-b8a7-4cb2-9fb0-22b55267ed32.mp4

### VS Code Version

1.60.2

### Jupyter Extension Version

v2021.8.2041215044

**Comment by janosh** [comment]
Checking in for updates. This bug is occurring a lot lately and hard to recover from.

**Comment by r3m0t** [comment]
This affects notebooks as well.

Version: 1.72.0-insider (user setup)
Commit: a12109a6ac8cdb070d94d63a5dc3a3a8f53bad8c
Date: 2022-10-04T12:24:00.023Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes
