### ISSUE TITLE
Lock icon not the best for readonly files

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#134118]
Testing #133743

I do not like the use of the lock icon for readonly files because:
1) We already use the Lock for Locking Output 
2) Lock does not really represent read only for me
3) Lock icon makes me want to click it to unlock it. And this decoration is not clickable (unlike the Output lock button)

By googling "readonly icon" I found the following, which is more clear to me.
Did we consider using the crossed out pencil?

![Screenshot 2021-09-29 at 13 41 52](https://user-images.githubusercontent.com/1926584/135261569-eefd6ea8-6e44-4afd-a3f3-3a9299ec1681.png)

**Comment by bpasero** [comment]
I am happy to change it to anything we can come up with but personally feel this icon is good, esp. since other IDEs also seem to be using such an icon.
