### ISSUE TITLE
Non-menu bar shortcuts are mapped incorrectly on Dvorak

### ISSUE THREAD

**Issue by chendo** [Microsoft/vscode#13417]
- VSCode Version: 1.5.3
- OS Version: 10.12.0

Steps to Reproduce:
1. Set keyboard layout to Dvorak
2. Use a keyboard shortcut that isn't in the system menu bar. For example, `Cmd+Shift+]` for indent.
3. Code zooms the interface, as the physical key for `]` in Dvorak is `=`.

Shortcuts that are defined in the menu bar work correctly as they are handled by the system.

Other keyboard layouts where symbol keys are remapped may exhibit the same problem.

**Comment by HookyQR** [comment]
See https://github.com/Microsoft/vscode/issues/15624#issuecomment-261412779 and PR https://github.com/Microsoft/vscode/pull/15687

**Comment by alexandrudima** [comment]
I have validated that we now (i.e. after PR #22894 aka #17521 -- in today's upcoming Insiders build) appear to behave correctly for this keyboard layout

![image](https://cloud.githubusercontent.com/assets/5047891/24288943/8f2ce4dc-107f-11e7-8f48-162d2ea3a0aa.png)
