### ISSUE TITLE
TypeScript language service crashes with a specific file

### ISSUE THREAD

**Issue by warpdesign** [microsoft/vscode#134194]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, x64)
- OS Version: macOS 11.5.2

Steps to Reproduce:

1. Open a new Tab
2. Paste the following code:
```
Type '{ validateOnChange?: boolean | undefined; validateOnBlur?: boolean | undefined; validateOnMount?: boolean | undefined; isInitialValid?: boolean | ((props: {}) => boolean) | undefined; ... 35 more ...; unregisterField: (name: string) => void; }' is not assignable to type 'IntrinsicAttributes & ((Pick<{ handleBlur: any; handleChange: any; setFieldValue: any; values: any; errors: any; touched: any; isUtagReady: any; prevpage: any; updateStep: any; isValid: any; isSubmitting: any; hasCV: any; }, never> & Pick<...> & Pick<...>) | (Pick<...> & ... 1 more ... & Pick<...>) | (Pick<...> & Pi...'.
  Type '{ validateOnChange?: boolean | undefined; validateOnBlur?: boolean | undefined; validateOnMount?: boolean | undefined; isInitialValid?: boolean | ((props: {}) => boolean) | undefined; ... 35 more ...; unregisterField: (name: string) => void; }' is missing the following properties from type 'Pick<InferProps<{ handleBlur: Validator<(...args: any[]) => any>; handleChange: Validator<(...args: any[]) => any>; setFieldValue: Validator<(...args: any[]) => any>; values: Validator<...
```

After a few seconds this message will pop up, and Intellisense is switched off:

![image](https://user-images.githubusercontent.com/199648/135427313-88bd77b4-ad51-424c-9306-82cbb36c56a6.png)

Note: I know this is not valid TS code. I simply copied/pasted the Intellisense warning I had and pasted it in a new file in order to make it more readable and noticed it was detected as TS code and then the Language Service crashed.

**Comment by yume-chan** [comment]
Looks like it has already been fixed in latest TypeScript version.

You can try the [JavaScript and TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) extension.
