### ISSUE TITLE
git bash on Windows still using \ as the path separator instead of /

### ISSUE THREAD

**Issue by tclimis** [microsoft/vscode#134178]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.2
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. set git-bash as the default shell.
2. run the following task:
```
{
	"label": "echo",
	"type": "shell",
	"command": "echo ${pathSeparator}"
}
```
![image](https://user-images.githubusercontent.com/8691145/135382286-395a4803-121c-4bb8-8461-289bd703910a.png)

The incorrect path separator is also used in the ${workspaceFolder} and ${file} variables.
According to #109300, this was supposed to be fixed by #38381, but that does not seem to be the case.  It added the variable, but it's still the wrong value.

**Comment by lszomoru** [comment]
@alexr00 is this an issue with tasks or the terminal? Thanks!

**Comment by alexr00** [comment]
All `${}` variables use the OS path separator. Marking as a feature request to use the shell's path separator.
