### ISSUE TITLE
Better icons for language status

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#134102]
Follow up on https://github.com/microsoft/vscode/issues/129037#issuecomment-927986152

**Comment by jrieken** [comment]
This is what I am pushing for now. In individual states use single check, info, and error (which corresponds to the tbd severities). For the status bar icon it always check-all but it would nice to have an annotated variant for it, like "check-all-dot" and "check-all-x"

<img width="770" alt="Screen Shot 2021-09-29 at 15 18 46" src="https://user-images.githubusercontent.com/1794099/135276286-dbdc8b8b-2115-470b-b56b-93e96fdf921f.png">

**Comment by daviddossett** [comment]
Some quick initial ideas here. I explored the check-all variations and some other possible approaches. One of the challenges I have with the check-all version is that the main icon represents "all ok" but then we're introducing this sort of "actually it's not all ok" status icon nested in there. Something to think about. 

The other options would be visually heavier in a status bar context but thought I'd include them here in case they spark any other ideas.

<img width="942" alt="CleanShot 2021-09-29 at 11 22 47@2x" src="https://user-images.githubusercontent.com/25163139/135326791-3e91adaf-db7a-45b7-9af5-cd849916a92a.png">

@misolori how have you decided between filled and stroke containers for the nested status icons? I see both across the codicons library. Included a version for both in the check-all option pictured.

**Comment by misolori** [comment]
We tend to use the solid ones because they got hard to read at smaller scales. But there are some places where we use the outline (search-stop and test-stop).

**Comment by jrieken** [comment]
❤️ the check-all and code variants

**Comment by daviddossett** [comment]
Examples in context:

## Check-all

<img width="610" alt="CleanShot 2021-09-30 at 11 20 00@2x" src="https://user-images.githubusercontent.com/25163139/135509778-e040637f-bdba-436c-9cfb-bcee72be57ce.png">


## Code 

<img width="696" alt="CleanShot 2021-09-30 at 11 19 05@2x" src="https://user-images.githubusercontent.com/25163139/135509695-c849a620-9ee5-4d01-95f2-f8f230ad0fa6.png">

**Comment by jrieken** [comment]
While I still prefer the check-all variant there some some feedback in todays standup that the code icon might be a better fit (since it's about the current code editor). Tho, there is question about the code icon being to html/jsx heavy and if code should be rather abstracted with curly brackets...

Nevertheless it would be great if we can get any variant shipping with the September release. @daviddossett The code is all prepared for it and awaits icons. Since the release window is closing, feel free to change these lines once icons are ready

https://github.com/microsoft/vscode/blob/bde7d28924dc3192ab95c6fed193ae91b821f773/src/vs/workbench/contrib/languageStatus/browser/languageStatus.contribution.ts#L261-L268

**Comment by daviddossett** [comment]
@jrieken Done. Updated codicons and language status with the new icons https://github.com/microsoft/vscode/commit/4b9f535c9491a1d6e59303ed281400e5ee349834

**Comment by IllusionMH** [comment]
Can we go back to double checkmark or something proposed earlier?
Two bare `{}` look like regular text and broken placeholder (as in emails `Dear {username},`).

Maybe at least wrap in document like proposed above?
![image](https://user-images.githubusercontent.com/1312662/135997078-7210a26b-17ed-4c84-9a31-add0c7fc2a19.png)

**Comment by gjsjohnmurray** [comment]
Adding the document outline would also reinforce that this side of the  status bar relates more to files than to workspace.

Current appearance feels like there's a bit too much space between the icon and the text:

![image](https://user-images.githubusercontent.com/6726799/136006535-b70cde7d-118d-45aa-8673-4666233b7536.png)

In https://github.com/microsoft/vscode/issues/129037#issuecomment-920708460 @bpasero says he originally used 2px padding on the relevant sides of the compact-left and compact-right styles, giving a combined padding of 4px. They are currently 3px, so total is 6px. Maybe revert to 2px:

![image](https://user-images.githubusercontent.com/6726799/136007737-a7105711-31f3-485b-9586-bd1eac6f075d.png)

Or even reduce to 1px:

![image](https://user-images.githubusercontent.com/6726799/136007866-023cfeef-829e-420e-8271-e7e86529ad78.png)

**Comment by gjsjohnmurray** [comment]
Simulation with file-code and 1px paddings:

![image](https://user-images.githubusercontent.com/6726799/136008293-cfbd923d-0e17-44df-8a22-e4054c67d79e.png)

Personally I think the document outline makes it look too indistinct and heavy, even without the extra indicator for warning or error.

**Comment by daviddossett** [comment]
@gjsjohnmurray that was my thinking as well. The document-style icons add to much clutter to the status bar.

Agreed on reduced padding.

**Comment by IllusionMH** [comment]
What about removing folded corner and using better spaced taller curly braces. Because curly braces (even with smaller padding) looks like regular text and not an icon.

Rough example
![image](https://user-images.githubusercontent.com/1312662/136083567-b56dd51b-93d2-42a5-86f0-d72dc9f02059.png)
_(please don't hate quality, it was literally done in Paint)_
