### ISSUE TITLE
Automatic formatting on HTML files ruins the file termination

### ISSUE THREAD

**Issue by KristofHorvath** [microsoft/vscode#134186]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.2 (system setup)
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Open an HTML document
2. Select 'Format Document' command (Shift+Alt+F)
3. If the file terminated with a newline character, that's not the case anymore

**Comment by yume-chan** [comment]
`"html.format.endWithNewline": true`

Note that it can only be `true` or `false`, so always insert or trim the final new line, there is no leaving as-is

**Comment by KristofHorvath** [comment]
@yume-chan Thank you, it's a perfect workaround for me. However, a leaving option (perhaps by default) may be helpful as well. (I got used to it formatting C++ files.)

**Comment by yume-chan** [comment]
I remember there was a discussion about changing final new line to default, but I can't find the issue now.

**Comment by KristofHorvath** [comment]
Probably that could also cause some problems. I think leaving as-is by default would be the best solution, but that leads to some compatibility/legacy issues.

**Comment by aeschli** [comment]
The `leaving as-is` variant would have to come from js-beautify, which we use as the underlying formatter. 
You want to check in https://github.com/beautify-web/js-beautify/issues if they already have that request.
