### ISSUE TITLE
Issues when resizing side panel 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#134147]
Testing #133919

I placed the output on the side panel, and once I resized it I noticed a "..." with an additional views option, even though only output is displayed there so no other view options are available. Also if you look at the GIF, once you resize it by dragging the line towards the right, the items on the right side of the menu disappear from the window, it doesn't seem there's a "boundary" defined. 
 
![sidepaneloutputbug](https://user-images.githubusercontent.com/45497113/135318824-9a26af6b-cc23-4aea-ab7a-c44582982f7d.gif)

**Comment by sbatten** [comment]
this bug would affect all composite bars along with a few other bugs I discovered while fixing. I made some improvements to the overall calculation that should squash them all and hopefully not introduce new ones. If you are verifying, this change will allow the active tab to be hidden into the overflow menu if the width is super small
