### ISSUE TITLE
Feature Requestp

### ISSUE THREAD

**Issue by Hong-Xiang** [Microsoft/vscode#13419]
When we hover our mouse on a method, VS code will provide its help docs in a flowing window, however it is scrolled to the end of the help document automatically. For those method with long documents, we can't see the beginning part of the help documents, which is always the most important part. A scrollbar like peek window in Visual Studio 2015 maybe a solution for this.

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/19237344/aecb103e-8efc-11e6-9f4f-87d19da28778.png)

The documentation is scrolled to the top. Can you show me a screenshot of what you mean?

**Comment by mjbvz** [comment]
Closing as fixed.

@Hong-Xiang Please let us know if you have any additional concerns about displaying long documentation strings in the UI

Thanks
