### ISSUE TITLE
The window crashes (reason: 'clean-exit',code:0)

### ISSUE THREAD

**Issue by Abhishek321Kumar** [microsoft/vscode#134291]
This issue happens whenever I try to open a folder in Vs code editor.
![error](https://user-images.githubusercontent.com/89536995/135655775-ebb33a9d-e1c3-4e6c-987e-fe6640e0be12.png)

Please rectify this issue as soon as possible.

**Comment by Testaak** [comment]
https://user-images.githubusercontent.com/89536995/136146008-6154291b-82d2-4562-bba4-a84987c312ec.mp4

**Comment by deepak1556** [comment]
Can you exclude the `desktop.ini` from the folder and see if the crash happens.

**Comment by Testaak** [comment]
I cant find any desktop.ini file in this folder. Not even in hidden items
