### ISSUE TITLE
VSCode doesn't reflect system font in it's menu on Fedora 24 MATE spin

### ISSUE THREAD

**Issue by rbukovansky** [Microsoft/vscode#13429]
- VSCode Version: Code - Insiders 1.6.0-insider (093d09e9e8a6b76ec09af97da45e242e317d8d95, 2016-10-07T19:01:55.625Z)
- OS Version: Linux x64 4.7.6-200.fc24.x86_64
- Extensions: DavidAnson.vscode-markdownlint-0.5.0, DougFinke.vscode-pandoc-0.0.8, EditorConfig.EditorConfig-0.3.3, MattiasPernhult.vscode-todo-0.8.0, Nuuf.theme-hackershaze-1.2.1, Poorchop.theme-darktooth-0.0.2, Shan.code-settings-sync-2.3.1, akamud.vscode-theme-onedark-0.2.7, andischerer.theme-atom-one-dark-0.0.1, azemoh.theme-onedark-0.3.1, bogdan-sinitsa.theme-dark-monokai-0.3.0, christian-kohler.path-intellisense-1.0.2, dbankier.vscode-instant-markdown-0.1.0, donjayamanne.githistory-0.1.0, gerane.Theme-Dark-Dracula-0.0.2, joshbax.mdhelper-0.0.9, lukehoban.Go-0.6.43, mdickin.markdown-shortcuts-0.3.0, ms-vscode.Theme-1337-0.1.2, ms-vscode.Theme-MarkdownKit-0.1.1, ms-vscode.Theme-TomorrowKit-0.1.3, ornithologist.ios-snippets-0.0.14, qinjia.md2pdf-0.0.1, rbukovansky.dark-win16-theme-0.0.4, robertohuertasm.vscode-icons-3.0.1, shinnn.swiftlint-0.1.3, waderyan.gitblame-1.3.0

Steps to Reproduce:

1. Install Fedora 24 MATE spin and then update packages
2. Install VS Code Insiders using RPM

I'm using Apple's San Francisco font (Display or Mono variant) for all system-wide defined font settings. But VSCode is not reflecting it in it's UI... See screenshot:

![font_used_menu](https://cloud.githubusercontent.com/assets/1004491/19239533/c1f8a766-8f06-11e6-912e-3ffbbc3abf36.png)

**Comment by bpasero** [comment]
Please report against Electron.

**Comment by rbukovansky** [comment]
Benjamin @bpasero, I'm sorry but I don't have a clue what Electron is... And to be honest, I don't care. I have issue with VSCode, not with Electron. If it's issue with some library VSCode is using, it's IMHO your job to make sure that library behaves correctly -> report bug to their bugtracking system.

**Comment by bpasero** [comment]
@rbukovansky that is not practical because you are the one having issues and if Electron has questions they should talk to you and not me. Their repository is here: https://github.com/electron/electron

Thanks for helping out in a way that makes open source better 👍

**Comment by rbukovansky** [comment]
Reported here: https://github.com/electron/electron/issues/7609

**Comment by rbukovansky** [comment]
Well, the new VM with Fedora and lastest VSCode Insiders and problem is probably gone.

Anyway, how the menu of app (File, Edit, View...) is generated with Electron? It doesn't seem to be HTML...

**Comment by bpasero** [comment]
@rbukovansky on Linux and Windows custom, Chrome does this for Electron.

**Comment by rbukovansky** [comment]
OK. We can probably close this one. Thanks.
