### ISSUE TITLE
C++11/14/17 auto keyword autocomplete problem

### ISSUE THREAD

**Issue by byzeagle** [microsoft/vscode#134218]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.2
- OS Version: Big Sur 11.6

Steps to Reproduce:

1. Auto complete doesn't work for auto keyword for C++11/14/17.
2. VS Code can't deduce the type of auto keyword.

**Comment by IllusionMH** [comment]
/extCpp

This functionality for C++ provided by extension. Please report it in extension's repo.
