### ISSUE TITLE
launch.json args not working for a python module with active virtualenv

### ISSUE THREAD

**Issue by bbiney1** [microsoft/vscode#134239]
I hope that if I'm doing something wrong then someone can spot it, I haven't been able to get an answer elsewhere.

- VS Code Version: Version: 1.60.2 (Universal)
- OS Version: Mac/OSX, Darwin x64 19.6.0

I'm having the same problem talked about here https://github.com/Microsoft/vscode/issues/2167 but I'm not making the error that this user was.

I have a Python module called `__main__.py` that I want to run in VScode's debugger. The full path of this is `~/Code/APPRES-483/cqs/update-query-definition/__main__.py`. The module uses a virtualenv located at `~/Code/APPRES-483/venv-cqs`. I have it active in my vscode terminal.

Here's the command I would be using to run the script in a normal terminal: `python3 . --verbose --file-to-write ../../LOCAL-query-definition.yml`

This is my launch.json file

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Module",
            "type": "python",
            "python":"${env:HOME}/Code/APPRES-483/venv-cqs/bin/python",
            "request": "launch",
            "module": "__main__", 
            "args":[
                "--verbose",
                "--file-to-write", "/../../LOCAL-query-definition.yml"
            ],
        }
    ]
}
```

When I try to run the debugger, I see this in my terminal:

```
cd /Users/bineyb/Code/APPRES-483/cqs/update-query-definition ; /usr/bin/env /Users/bineyb/Code/APPRES-483/venv-cqs/bin/python /Users/bineyb/.vscode/extensions/ms-python.python-2021.9.1246542782/pythonFiles/lib/python/debugpy/launcher 50826 -- -m __main__ --verbose --file-to-write /../../LOCAL-query-definition.yml 
debugpy 1.4.3
See https://aka.ms/debugpy for documentation.

Usage: debugpy --listen | --connect
               [<host>:]<port>
               [--wait-for-client]
               [--configure-<name> <value>]...
               [--log-to <path>] [--log-to-stderr]
               <filename> | -m <module> | -c <code> | --pid <pid>
               [<arg>]...

Error: unrecognized switch --verbose
```

The first argument always causes this error message, "error unrecognized switch". I can't find out what's going wrong.

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
