### ISSUE TITLE
Unnecessary announcement of "Publisher Name" while navigating the "Microsoft" button.

### ISSUE THREAD

**Issue by 12-shweta** [microsoft/vscode#134262]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags**:#A11yMAS;#A11yTCS;#VisualStudioCode-Win32-Apr2021;#Visual Studio Code Client;#A11ySev2;#WCAG4.1.2;#Benchmark;#DesktopApp;#Win10;#NVDA;#JAWS;

### Environment Details:
Visual Studio Code - Insiders
Azure Function
Operating System: Windows 10 Pro 21H1

### Steps to Reproduce:
Launch the Visual studio code.

1. TAB to on "Extension" button and search for "Azure Functions" and select it using ENTER key.
2. "Azure Function" screen should open.
3. Start NVDA and TAB to "Microsoft" control.
4. Observe the announcement for "Microsoft" control.

### Actual:
When the NVDA focus shifts to the "Microsoft" button, NVDA announces "Microsoft  button  Publisher name" but "Publisher name" text is not there.

### Expected:
The NVDA should not unnecessarily announce "Publisher name" text along with "Microsoft" button.

### User Impact:
Screen reader users will get incorrect information about  "Microsoft" button.

Please find below attachment for reference:
![134262_Unnecessary announcement of Publisher Name while navigating the Microsoft button](https://user-images.githubusercontent.com/54656883/135586851-85d66f45-7f2d-4606-b381-ddf20924c206.gif)

**Comment by isidorn** [comment]
This is the screen reader just reading the `title` of the element at the end. We can not control this.
I think this is fine.
I will just change that the hover is "Publisher" not "Publisher name". That way it is more concise and I think better.

**Comment by Rama8345** [comment]
**Github Tags:**#Closed;
