### ISSUE TITLE
The keybindings are missing from the editor menu

### ISSUE THREAD

**Issue by anatsegev** [Microsoft/vscode#13421]
- VSCode Version: 0.7.0
- OS Version: All

Steps to Reproduce:

1. Call editor.addAction with id, label, run and keybindings 
2. Right click on the editor - the label is displayed in the menu but not the keybindings.
(See playground "Adding an action to an editor instance" example.)

**Comment by isidorn** [comment]
Please update to the latest version of vscode this issue is fixed
