### ISSUE TITLE
Pin folders landing page

### ISSUE THREAD

**Issue by GuillaumeQuenneville** [microsoft/vscode#134216]
I use a workspace per project with vs code. They are especially useful for remote development so I don't have to navigate and reopen a window with the folder/file I want. 
I also use vscode to open a lot of single files and folders.

The issue I have is that opening folders bumps my workspaces off the recent list in the landing page. When they're gone I have to navigate back to the location to reopen. In general, there doesn't seem to be a nice way to list/track all your workspaces builtin (I found some interesting extensions)?

Suggestions for landing page:
1. Allow us to pin folders/workspaces on the landing page. This would also be a solution for recent places that aren't workspaces.
2. Give special treatment to workspaces on the vscode's initial landing page. e.g. a separate box with just workspaces.

Thanks!

**Comment by JacksonKearl** [comment]
This is a fair feature request, but in the mean time does the `Ctrl+R` (or `File: Open Recent` in command palette) menu help you? It should present a much larger list of recent files, folders, and workspaces.

**Comment by GuillaumeQuenneville** [comment]
That's great! It even supports text search. 3 years and im still learning new hotkeys ahah.

This wasn't a big issue even before I knew this so of course it helps.

Thank you
