### ISSUE TITLE
cant use git in terminal

### ISSUE THREAD

**Issue by yaaniu** [microsoft/vscode#134230]
Issue Type: <b>Feature Request</b>

same as title

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by IllusionMH** [comment]
/needsMoreInfo
Title does not provide any useful information about about steps you are doing and results for these steps.
