### ISSUE TITLE
Typescript suggestions are very often broken 

### ISSUE THREAD

**Issue by louy** [Microsoft/vscode#1342]
Hi,

Typescript suggestions are always out of sync whenever any change like a git operation happens. 
For someone like me who relies on the terminal, the experience is horrible.
If I understand it correctly, it's caused by changes to files outside the IDE. "atom-typescript" had a sync button to fix this. You should too.

If it's relevant, I'm using VSCode version 0.10.3 with Typescript v1.7.3 on OSX 10.11.2.

**Comment by gileze33** [comment]
+1 this is killing my workflow!

**Comment by dbaeumer** [comment]
We could add a reload action to VS Code to reload all projects. However there is a bug open in the TypeScript repository as well since the tsserver should handle this correctly without user interaction.

@louy: does the git operation change files outside your open workspace folder and those files affect the TS compile?

**Comment by louy** [comment]
@dbaeumer So it is as I thought. Well user intervention is better than nothing. And no, each workspace is a git project.

Another tricky solution would be to trigger the reload command when the project window restores focus after it was in the background for some set duration (like 10-30 secs). 

This is a big issue for me. It's really annoying.

**Comment by dbaeumer** [comment]
For Dec I added a TypeScript: Reload Projects command which is available via F1. The TS team is still looking into fixing this in the tsserver we use.

**Comment by louy** [comment]
Awesome. Thanks!

**Comment by jrieken** [comment]
When TS isn't launched yet, you get this error

![screen shot 2015-12-16 at 14 23 23](https://cloud.githubusercontent.com/assets/1794099/11841929/a857888c-a400-11e5-80bc-97ba26f2c9b9.png)

**Comment by dbaeumer** [comment]
Created #1383

**Comment by dbaeumer** [comment]
Closing.
