### ISSUE TITLE
Extension that runs a request to a server that has a Let's Encrypt CA stopped working

### ISSUE THREAD

**Issue by randrade23** [microsoft/vscode#134245]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.60.2
- OS Version: Windows 10 21H1

Steps to Reproduce:

1. Install an extension that runs a request to a server protected by a Let's Encrypt CA
2. An error is thrown in the VS Code developer tools indicating the certificate is expired, when it is not

I have an extension (for private use, under an NDA, so I cannot share its code) that runs a request, using axios, to a server which has HTTPS and uses a Let's Encrypt CA.

The request now fails indicating the certificate is expired, even though the certificate was renewed today and is valid for another 3 months. It started happening this afternoon after DST Root CA X3 expired.

The certificate shows as valid when browsing with Chrome, Firefox, Edge or on a smartphone.

The following error is thrown in the VS Code developer tools menu:

```stack trace: Error: certificate has expired	at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)	at TLSSocket.emit (events.js:315:20)	at TLSSocket.EventEmitter.emit (domain.js:467:12)	at TLSSocket._finishInit (_tls_wrap.js:932:8)	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)```

Possibly related issue: https://github.com/electron/electron/issues/31212
Relevant PR: https://github.com/electron/electron/pull/31213

**Comment by AlencarGabriel** [comment]
For those who use GOT this may be a temporary solution, until the VSCode update comes out: https://github.com/sindresorhus/got/issues/1148

**Comment by randrade23** [comment]
Closing as already reported in #134244 .

**Comment by AlencarGabriel** [comment]
This issue reoccurred in version 1.62.1.
