### ISSUE TITLE
Feature Request: Bracket Guides Should Consider Indentation

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#134267]
Currently, bracket guides just start from the opening bracket and go to the closing bracket.

The BP2 extension computes the indentation for all lines in between and draws the bracket guide at the column of the minimal indentation.

We should do that too, as it would fix #133916 and scenarios like this:

![image](https://user-images.githubusercontent.com/2931520/135595035-2addaf3e-77f0-4644-ae40-d7947954ef7a.png)

This is not entirely trivial, as we don't want to walk all lines in between every time to compute the minimal indentation.

**Comment by hediet** [comment]
@pouyarezvani wait about 2h and install the hopefully then published update of VS Code ;)

**Comment by pouyarezvani** [comment]
@hediet Awesome, I see that it is fixed in version 1.62 
Thanks for your quick reply! I appreciate that
