### ISSUE TITLE
Unwanted behavior due to mouse position

### ISSUE THREAD

**Issue by glhfior** [microsoft/vscode#134253]
Open the File menu and place the mouse cursor on the "Preferences" option.

Hit [Esc] twice to close the file menu.

Attempt to save the current file via [Alt][F][S] (not the [Ctrl][S] shortcut).

The mouse position prevents the normal behavior of initiating the save and instead leave the mouse hovering over Preferences

**Comment by yume-chan** [comment]
Duplicate of #110594
