### ISSUE TITLE
Broken layout in a freshly opened Notebook

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#134290]
Issue Type: <b>Bug</b>

Just opened an ipynb file locally (after restarting VS Code) and the code/image output segments did not overlay wildly.

Scrolling up and down once in the notebook fixed it.

(green overlays added in post for, as this is a WIP analysis)

![image](https://user-images.githubusercontent.com/8599/135655406-74823284-ff13-4998-b31b-2d569f11518d.png)

VS Code version: Code - Insiders 1.61.0-insider (6fed60f8f4dd21fb16dcbe64a742296b339ff0ee, 2021-09-30T05:17:41.877Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|64.00GB (0.05GB free)|
|Process Argv|--enable-proposed-api donjayamanne.kusto --log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.1
emojisense|bie|0.9.0
vscode-tailwindcss|bra|0.7.0
npm-intellisense|chr|1.4.0
vscode-github-actions|csc|0.21.3
postcss|css|1.0.9
vscode-eslint|dba|2.1.25
kusto|don|0.3.8
typescript-notebook|don|2.0.3
gitlens-insiders|eam|2021.7.1905
tsl-problem-matcher|eam|0.4.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|9.0.0
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
codespaces|Git|1.0.7
copilot|Git|1.5.2864
remotehub-insiders|Git|2021.10.10204
vscode-pull-request-github|Git|0.30.0
restore-git-branch-tabs|gko|0.4.1
headwind|hey|1.7.0
gzipdecompressor|Hyu|1.2.0
theme-monokai-pro-vscode|mon|1.1.19
vscode-docker|ms-|1.17.0
vscode-edge-devtools|ms-|1.3.1
python|ms-|2021.10.1270484629-dev
vscode-pylance|ms-|2021.9.5-pre.1
jupyter|ms-|2021.9.1001294413
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.200.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
azure-account|ms-|0.9.8
cpptools|ms-|1.6.0
live-server|ms-|0.2.8
vsliveshare|ms-|1.0.4836
debugger-for-edge|msj|1.0.15
java|red|0.82.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
smart-css-autocomplete|sai|1.5.3
mdx|sil|0.1.0
msft-todo-unofficial|tyl|0.0.15
glean|wix|5.2.2
markdown-all-in-one|yzh|3.4.0
vscode-proto3|zxh|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30364496
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsqsis200:30374795

```

</details>

**Comment by rebornix** [comment]
We have pushed quite a ton of polish to the layout. Closing it for now and reopen if we are still seeing it.
