### ISSUE TITLE
Can drag and drop vsix with wrong platform to Extensions viewlet and it gets installed

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#134278]
Testing #133868

Client: Mac x64
Container: Linux x64
Extensions allowed me to drop an Alpine ARM64 VSIX downloaded from https://marketplace.visualstudio.com/items?itemName=chrmarti.test-platform-specific-extensions and it was installed.

**Comment by yume-chan** [comment]
Related to #134080
