### ISSUE TITLE
Set target of compilerOptions for current javascript file

### ISSUE THREAD

**Issue by Daijobou** [microsoft/vscode#134233]
I have several projects where the javascript files should be sometimes ECMAScript 2015 sometimes ECMAScript 2018 compliant. It would be nice to be able to quickly switch between the versions for the syntax check. Currently, it does not even show which version is currently in use.

**Comment by mjbvz** [comment]
Try setting  `target` in a [`jsconfig`](https://code.visualstudio.com/docs/languages/jsconfig)
