### ISSUE TITLE
Duplicate entries in Keyboard Shortcuts

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#134246]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.61.0-insider
Commit: 6fed60f8f4dd21fb16dcbe64a742296b339ff0ee
Date: 2021-09-30T05:17:41.877Z
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Steps to Reproduce:

1. add this keybinding to your keybindings.json:
```
{
		"key": "shift shift",
		"command": "workbench.action.editor.changeLanguageMode",
		"when": "!notebookEditorFocused"
}
```
2. Go to the gui Keyboard Shortcuts and search for "language" and notice 4 entries show up:
![image](https://user-images.githubusercontent.com/2644648/135528420-114e7c85-44ad-4536-ae60-e4f0199ede8c.png)

**Comment by sandy081** [comment]
This seems to be coming from the `KeybindingsService` - `KeybindingsService.getKeybindings()` is returning 5 user keybinding items for this command.

**Comment by alexdima** [comment]
@sandy081 I think the keybindings editor eventually calls `ResolvedKeybindingItem.resolvedKeybinding.getLabel()`. That could be used to dedup them. The alternative would be for me to do this filtering inside `IKeybindingService.getKeybindings()`, but to be honest I think that method is good as is, as it allows for example unit testing this.

**Comment by sandy081** [comment]
De-duped in the editor.

**Comment by alexdima** [comment]
Thank you @sandy081 !
