### ISSUE TITLE
vscode closes when cancelling a save file dialog

### ISSUE THREAD

**Issue by soulshined** [microsoft/vscode#134211]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60
- OS Version: Windows

Steps to Reproduce:

1. Open vscode without a workspace
2. Create a new file (<kbd>CTRL</kbd> + <kbd>N</kbd>)
3. Start typing in the new file
4. Press <kbd>CTRL</kbd> + <kbd>S</kbd>
5. Once the file dialog box appears, press <kbd>Escape</kbd> 

The dialog dismisses but vscode also closes, without prompting you to save the file you just made changes on

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by soulshined** [comment]
@bpasero so interesting development. it does not happen once i upgraded to 1.60.2 - didn't know there was a new version at the time of writing this (i was currently on 1.60.1) I don't use nightly. Also, some minor feedback, weird that i would need to download an entirely different type of vscode just to test it, when i included the steps to reproduce, but that's not a big deal, just my 2 cents :) 

I have a theory, but don't want to throw out assumptions or create unnecessary red herrings for anyone. For now it's **not** reproducible on 1.60.2! I'll reopen if it is because what i think it is and can definitively recreate the issue based off that. Thanks for the quick response!
