### ISSUE TITLE
[BUG] side bar background

### ISSUE THREAD

**Issue by 0407chan** [microsoft/vscode#134205]
Does this issue occur when all extensions are disabled?: `Yes`

- VS Code Version: 1.60.2
- OS Version: mac OS Big Sur 11.6

Steps to Reproduce:

1. on `Explorer` tab, my project
2. press `enter` to rename folder
3. rename input is activated and sidebar has dark background.
4. press 'new file' button
5. no file added, dart background is still there.

### demo
![vscode sidebar bug](https://user-images.githubusercontent.com/19217576/135461268-cb4bd0f2-71a3-4d92-bebe-45a2ca8ac5d5.gif)

**Comment by lramos15** [comment]
Attempted to reproduce in the latest version with no luck
