### ISSUE TITLE
git auto refresh does not work with Google Drive for desktop

### ISSUE THREAD

**Issue by leosdad** [microsoft/vscode#134223]
- VS Code Version: 1.60.2
- OS Version: Windows 10 Pro 20H2 19042.1237

I've created a project inside a Google Drive for Desktop folder. Google Drive, as you may already know, is mapped as a virtual drive (in my case it's G:, the default). Bit the git auto refresh feature does not work for this particular project. Of course the respective settings are not disabled anywhere. As a test, I moved the whole project to a folder in OneDrive (which is not mapped as a drive), and now git auto refresh works again as expected.

The command Git: Refresh (issued manually) works normally in any case. 

So perhaps VS Code does not like mapped drives, maybe this issue is related to https://github.com/microsoft/vscode/issues/42821.

**Comment by leosdad** [comment]
> @leonm1, apologies for not getting back to you on this until now. Given that this issue has been open for quite some time I was wondering if you are still able to reproduce this issue as since the bug has been opened there have been quite some improvements to file watching, as well as the git functionality in VS Code. Thank you!

I have actually changed my strategy since. I don't use Google Drive (or OneDrive, for that mattter) for Node projects anymore (node_modules folders are huge). I make daily backups to OneDrive, but git is not working from there. So I cannot tell you if this problem still persists, sorry. Thanks anyway.
P.S. it's @leosdad ;)

**Comment by lszomoru** [comment]
@leosdad, thank you vey much for the update, and apologies for the incorrect @. Given that this is not part of your workflow, I will go ahead and close the issue but in case you will still be able to reproduce the problem, please feel free to reopen the issue. Thanks!
