### ISSUE TITLE
Consider enabling word wrapping by default in test failure inline diff editor

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#134232]
When a test fails, it might sometimes look like this:

![image](https://user-images.githubusercontent.com/5047891/135515941-c3f9fab4-e67b-420d-9050-935bffbb424c.png)

By pressing `alt+z` in both editors, I can get it to look like this, which is more helpful for long strings:

![image](https://user-images.githubusercontent.com/5047891/135516038-538e0e73-4ddd-40bf-be74-66a3e22c9c03.png)

It might be better to enable word wrapping by default for string comparisons.

**Comment by connor4312** [comment]
Code pointer: https://github.com/microsoft/vscode/blob/c78811c1a7d2b2438ce69670f290008700037221/src/vs/workbench/contrib/testing/browser/testingOutputPeek.ts#L762

**Comment by vincentrohde** [comment]
@alexdima @connor4312 Is this issue up for grabs? I would love to implement this 👍

**Comment by vincentrohde** [comment]
Could you assign me to this issue?

**Comment by connor4312** [comment]
No, only people in the Microsoft org can be assigned issues. You can open a PR without being assigned though 🙂
