### ISSUE TITLE
Feature Request: Revert to Save Point

### ISSUE THREAD

**Issue by ivanthewebber** [microsoft/vscode#134237]
When debugging interpreted languages (I'm thinking of python) it would be nice to be able to "save" at a breakpoint and then return to that point and state after continuing in order to try some hot code replacements to fix a bug.

```
if __name__ == "__main__":
    df = load_filtered_data('in.ss') # takes 5 minutes; create a save point to debug from here

```

**Comment by roblourens** [comment]
This isn't something that vscode can do, it would be a feature request for a particular language/runtime
