### ISSUE TITLE
Support multi target debugging 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#13426]
Support multiple debug sessions in a single instance of VS Code.

This helps with the following scenarios:
- debug a client and a server
- debug a clustered program
- debug a multi process application
- debug an extension and its debug adapter and/or language server at the same time

Problems to address:
- multiple debug models or one 'super model'?
- how to launch multiple sessions with a single 'F5'?
- UI: Process view vs. Windows vs. tabs...

**Comment by siegebell** [comment]
Debugging a language-server & client in one instance would be nice...

**Comment by atian25** [comment]
+1 for this, and please consider about auto attach to the new worker since it will be auto reload at development.

**Comment by weinand** [comment]
The plan is to allow multiple debug sessions in a single VS Code instance. This requires that the debug model/service can be instantiated multiple times. How multiple debug sessions are presented in the UI is an independent issue: probably we will start with something simple, e.g. a simple session switcher or by introducing processes as the top level elements in the call stack view.

**Comment by isidorn** [comment]
We have added support for mutliple debug sessions. The current way to enable this might change in the future, it is still **experimental**. 

For enabling set the `"type"` of a launch configuration to `"composite"` and add an array field `"configurationNames"` which will list all the configuration names which should be launched as part of this configuration.

**Comment by daviwil** [comment]
This is awesome, thanks a lot!

**Comment by gerich-home** [comment]
How do I know when it will be released?

**Comment by isidorn** [comment]
@gerich-home https://github.com/Microsoft/vscode/issues/13342

Also this experimental feature is currently available in the vscode insiders

**Comment by Gama11** [comment]
For anyone stumbling upon this issue via Google (like me), the syntax for compound launch configs has changed since @isidorn's earlier comment. There's a usage example here:

https://github.com/Microsoft/vscode/issues/14842#issuecomment-262730707

**Comment by Deathangel908** [comment]
Also it would be great if there were an ability to switch between target outputs, (atm they are merged):

![image](https://user-images.githubusercontent.com/1336703/28566175-0c2dd24e-7137-11e7-848b-2be0920c9985.png)

**Comment by weinand** [comment]
@Deathangel908 please create a new issue since this issue is already closed.
