### ISSUE TITLE
Launching compound targets should open in a split terminal. 

### ISSUE THREAD

**Issue by Marsfan** [microsoft/vscode#134251]
Currently, if a compound launch configuration is defined in a _launch.json_ file, each configuration is launched in a different terminal. within the terminal list. It would be nice if in the future, launching compound configurations could create split terminals, to allow viewing the programs side-by-side. 

Currently creating a compound configuration will open terminals separately, like this: 

![image](https://user-images.githubusercontent.com/9311953/135539784-8ecf9e83-b10e-4edd-9e98-4355ef468d24.png)

It would be nice in the future to have a configuration option to make the debugger automatically open the terminals in a split form: 

![image](https://user-images.githubusercontent.com/9311953/135539811-ced29c52-9cf4-4ffb-b4ee-61995a8a771a.png)

While simply dragging the windows can fix this, code does not properly recognize split windows in this case and will then create a new terminal: 

![image](https://user-images.githubusercontent.com/9311953/135539966-7679fd28-65f0-4746-9508-c8d59187d866.png)

**Comment by roblourens** [comment]
> code does not properly recognize split windows in this case and will then create a new terminal:

Not sure what you mean here?
