### ISSUE TITLE
inconsistent hacky and buggy placement of fake UI menus

### ISSUE THREAD

**Issue by duckgirl27** [microsoft/vscode#134206]
Does this issue occur when all extensions are disabled?: Yes/No

Steps to Reproduce:
![print2](https://user-images.githubusercontent.com/91676010/135461658-89158dda-5f92-4973-a21d-ba0d094086fa.png)

1. Verify screenshot
Instead of providing a true native menu, microsoft developers took the lazy option and turned it into a dom menu instead. 
Notice that is not impossible to have things done with quality, as you can see that the terminal menu dropdown is implement properly.

**Comment by duckgirl27** [comment]
Why is it that the terminal hove menu works properly and can be shown outside the vscode window like proper menus, but the terminal tabs cannot, and instead drops up when it can't fit the vscode window?

**Comment by sbatten** [comment]
Our menu system is intended to be themeable, accessible, and work across a variety of platforms such as web.

**Comment by sharedrory** [comment]
Isn't there a setting that enables native electron menus? I think it also changes the menubar
