### ISSUE TITLE
script type="application/ld+json" is Not Supported

### ISSUE THREAD

**Issue by khashabawy** [microsoft/vscode#134298]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1
- OS Version: Windows 10

Steps to Reproduce:

1. Write any script with type="application/ld+json"

![image](https://user-images.githubusercontent.com/400698/135668506-56c5fe8e-fd8d-4538-8fed-fd88a0ee608c.png)

**Comment by aeschli** [comment]
For syntax highlighting we are using the TextMate grammar from https://github.com/textmate/html.tmbundle

There's already a related feature request there: https://github.com/textmate/html.tmbundle/issues/103
