### ISSUE TITLE
Show inline values in source when stepping through code

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#13424]
1. in the debug protocol add a scope boundary (start, end position) to the scope object.
2. implement this in node-debug2.
3. VS Code starts to use that information to fix the hover experience by only showing a hover when inside the scope boundaries.
4. node.debug2 and (node-debug) implement the one line 'preview' for objects and arrays. This is not a new protocol request but just improves what's get returned as the `value`attribute in a Variables request for objects and arrays. 
5. VS Code implements the 'show inline values' feature as outlined in #12256

**Comment by isidorn** [comment]
Assigning to @roblourens until this is implemented in the adapters. Once that is done assign back to me and I can pick it up in the UI

**Comment by weinand** [comment]
I will create an issue for Rob in his repository.

**Comment by roblourens** [comment]
I added the scope locations to node-debug2. Will be in the next Insiders

**Comment by isidorn** [comment]
Once we have this feature we should use it to market our new node2 debugger. It looks fancy so it can draw people to swtich to node2.

**Comment by weinand** [comment]
We will make swap 'node' and 'node2' as soon as the electron version of node supports CDP. Without that extension host debugging does not work in node2.

**Comment by isidorn** [comment]
And when we do the switch we can use this feature as one of the user visible improvements

**Comment by isidorn** [comment]
First version of this has been pushed to master.
If a debug adapter is providing scope ranges those will be used, otherwise we show inlinve values from lineNumber 0 to the current lineNumber of the stack frame
