### ISSUE TITLE
Triple clicking + CTRL-C to copy text from output area of Jupyter cell copies the cell contents instead when selected output text line is generated by printing a spaCy Doc object

### ISSUE THREAD

**Issue by e-nesse** [microsoft/vscode#134249]
## Environment data

-   VS Code version: 1.60.2 (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): v2021.9.1246542782
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Home
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used: poetry venv
-   Jupyter server running: Local

## Expected behaviour

When selecting (by triple clicking, for example, or by click-dragging to select from beginning past the final character of the line) an entire line of text from the *output* area of a Jupyter cell, using CTRL-C should always copy the selected _output_ text, possibly including a newline character. 

## Actual behaviour

If a spaCy Doc object's text is printed (via **print(name_of_doc_object)** or simply via **name_of_doc_object**) to the output area of a Jupyter cell, selecting that entire line of text output in the output area such that the selection highlight extends PAST the final character of the line (seemingly including a newline character), CTRL-C copies the contents *of the cell itself* and not the selected text from the output area.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

- Use Jupyter notebooks within VSCode,
- Having installed both spaCy and a spaCy model (such as via "python -m spacy download en_core_web_sm"),
- Import spaCy and generate a Doc object, e.g.:

> import spacy
> nlp = spacy.load('en_core_web_sm') # or any other model, I think
> doc = nlp("A sentence string here.")

- Print the resulting Doc object to a Jupyter cell's output area, whether by **print(doc)** or simply **doc**, then run the cell
- Triple click select the entire printed text of the doc object / the entire printed output line in the output area ("A sentence string here"), OR select the _entire_ line by click-dragging from the beginning of the output line all the way past the final character, such that the highlight area extends beyond the final character as if to include a newline character. Note that copy/paste will behave correctly if only a portion of the line is selected.
- Use CTRL-C to copy, then paste the copied text somewhere - the copied text will be the *code from the cell* ("import spacy // nlp = spacy.load(...)..." etc.) and not the selected text from the output area.

I have no idea if this works with other output from other objects' __str__ methods (which I just assume is what's happening here, but am not sure).

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by ldorigo** [comment]
Just as a note, this happened to me as well with the output of `pwd` (which is a jupyter magic function I think?). It's not completely reproducible, though, sometimes ctrl-c works, sometimes it does not...
