### ISSUE TITLE
Visual Studio Code ignores .gitignore entry

### ISSUE THREAD

**Issue by matteodev8** [microsoft/vscode#134204]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.60.2
- OS Version: macOS Big Sur 11.6

Steps to Reproduce:

1. Create a file called `config.json`
2. Add to `.gitignore`
3. Commit and Push
4. File will show on GitHub

**Comment by IllusionMH** [comment]
VS Code uses git to commit and push changes.
Do you see same behavior if you do absolutely same steps with git cli directly?

More details about exact steps needed.
