### ISSUE TITLE
Lots of screen cheese when switching themes on Welcome Page

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#134214]
1. Open Getting Started / Welcome
2. Click on switching a theme
3. 🐛 The themes flash on desktop. On web you don't see flashing but there is a brief glimpse of the images at the top of the screen before they get laid out.

**Comment by lramos15** [comment]
Maybe I'm abusing it too much but if you cycle through and click the themes it still glitches out.

**Comment by JacksonKearl** [comment]
How fast were you cycling? I was able to see a glitch maybe once when cycling as fast as possible on my MBP, though it may happen more often on different hardware

**Comment by lramos15** [comment]
![recording](https://user-images.githubusercontent.com/4544166/144465411-fe2dd8f8-c52c-4893-8fe8-8b99a5633038.gif)
Not very fast. See the buttons just dissapear.

**Comment by JacksonKearl** [comment]
Oh, interesting, I haven't seen that one before.
