### ISSUE TITLE
Code Assistance stopped working after update

### ISSUE THREAD

**Issue by abacomartin** [microsoft/vscode#134281]
Issue Type: <b>Bug</b>

After the latest update to VS Code, code assistance has stopped working - find references, ctrl-click follow etc.

I'm using VS Code on Windows 10 (x64 / latest), the C/C++ language, it's not working with either. Here is some simple/sample code to demonstrate the issue:

```
#include <stdio.h>
#include <stddef.h>
static void hello_world(char* string);

int global=0;

int main(int argc, char** argv) {
    if (argc > 1) {
        hello_world(argv[1]);
    }
    else {
        hello_world(NULL);
    }
    global = 1;

    return 0;
}

void hello_world(char* string) {
    if (!string) {
        printf("hello world\n");
    }
    else {
        printf("%s\n", string);
    }
}
```

I have tried uninstalling / reinstalling vs code, restarting machine (just in case...).

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.72GB (46.97GB free)|
|Process Argv|--crash-reporter-id aa7a2101-b014-4e49-bee2-973b48c3f11c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.3.2
gitlens|eam|11.6.0
vscode-pull-request-github|Git|0.30.0
better-cpp-syntax|jef|1.15.10
vscode-docker|ms-|1.17.0
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.4
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.3
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
cmake-tools|ms-|1.8.1
cpptools|ms-|1.7.0-insiders2
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4836
vsliveshare-audio|ms-|0.1.91
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis400:30374798

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command to investigate whether one of your extensions is causing the Extension Host to crash.

**Comment by abacomartin** [comment]
No difference with Bisect running (Bisect is active and disabled 22 extensions), followed by Bisect is done but no extension has been identified...

**Comment by jrieken** [comment]
A good start would be to mention the programming language that you are using and to share a full code snippet that you are trying this with

**Comment by abacomartin** [comment]
The key was uninstalling AND manually deleting the .vscode and AppData/Roaming/vscode folders. Then reinstalling.
