### ISSUE TITLE
Settings Sync should not remove an installed extension if the extension location cannot be resolved

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#134224]
<img width="1004" alt="Screen Shot 2021-09-30 at 15 45 15" src="https://user-images.githubusercontent.com/1794099/135467144-04d9784e-5a99-4e3d-81c7-409b922cb7a6.png">

**Comment by misolori** [comment]
Would this also exclude when there are server issues with the marketplace, like if the site is ever down? I'd appreciate a notification that told me what extensions were excluded (maybe a link that opens the list of the extension names and logs it somewhere in case it was an error).

**Comment by sandy081** [comment]
Idea is not to exclude any extensions but just sync them even if they are not found. Its like we maintain an extension manifest locally and it will be synced as is. If services are down, settings sync cannot install extensions and in this case I maintain skipped extensions and will be installed in next sync. Not sure showing a link for these skipped extensions is useful.

**Comment by misolori** [comment]
Ah ok, I was thinking that the skipped extensions would be removed but your logic makes more sense!

**Comment by sandy081** [comment]
Yes, logs capture these details.

**Comment by sandy081** [comment]
Fixed by https://github.com/microsoft/vscode/commit/dda747f19d6674b0494f983967dee21a993259e2
