### ISSUE TITLE
Feature Request: Allow to define recommended configurations for recommended workspace extensions

### ISSUE THREAD

**Issue by distante** [microsoft/vscode#134263]
I am asking for the possibility to set an object with the recommended configurations that should be added to the workspace settings when a recommended extension is defined.

I have a real-life example of this. 

On a big project, I wanted to set [vscode-jest](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest) as a recommended extension. The problem was that the project was so big, it took too much time for the first run to be done every time vscode opened that project.

That first run can be disabled using [a specific extension configuration](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest#how-to-trigger-the-test-run), but there is no way to make that automatically and every developer had to change it manually.

**Comment by sandy081** [comment]
You can write those configurations in workspace settings of that project/folder and all users using that project will get those settings.
