### ISSUE TITLE
Add option to disable TypeScript diagnostics on custom file system or read-only files

### ISSUE THREAD

**Issue by olafurpg** [microsoft/vscode#134271]
I'm writing a VS Code extension that implements a custom read-only `vscode.FileSystemProvider`. When I open documents with the `*.ts` file extension the TypeScript language server publishes error diagnostics. These diagnostics are noisy, I can't fix the errors because the file system is read-only. 

![CleanShot 2021-10-01 at 11 39 32@2x](https://user-images.githubusercontent.com/1408093/135599452-d856b522-5470-4083-8446-b375cae76f84.png)

One workaround is to programmatically disable diagnostics entirely with the configuration `  "typescript.validate.enable": false`. However, my extension needs to make sure that  we re-enable TypeScript validation when my file system is no longer in focus. It would be nice if there was a way to tell TS Server to skip publishing diagnostics. For example,

- don't publish diagnostics in read-only files, OR
- don't publish diagnostics for documents matching a `vscode.DocumentSelector`. This would make it possible to disable diagnostics by directory, or the URI scheme.

I tried to search for duplicate issues but couldn't find any matching results.

**Comment by mjbvz** [comment]
Would be fixed by #134175
