### ISSUE TITLE
Get started items keep coming back

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#134231]
I haven't seen this happen before so maybe a recent change affected this. I've hidden all of the walkthroughs and they flash back when I do a refresh and re-opening the welcome page makes them permanently show up.

https://user-images.githubusercontent.com/35271042/135511164-9b9dde6d-d4cb-4ddd-9340-282c4ae33130.mp4

Version: 1.61.0-insider (Universal)
Commit: 6fed60f8f4dd21fb16dcbe64a742296b339ff0ee
Date: 2021-09-30T05:17:41.877Z
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0

**Comment by JacksonKearl** [comment]
Hm I did make a small change here yesterday but I don't think it'd affect here... I'll look more into this.

**Comment by JacksonKearl** [comment]
It did indeed affect here. Good catch, thanks!

**Comment by JacksonKearl** [comment]
It did indeed affect here. Good catch, thanks!
