### ISSUE TITLE
Timeline panel leaks internal (?) name

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#134208]
* trigger view picker, e.g F1 _replace_ all text with `view<space>`
* :bug: notice how one panel (its the timeline) has a bogous name

<img width="849" alt="Screen Shot 2021-09-30 at 15 26 20" src="https://user-images.githubusercontent.com/1794099/135463977-48b16612-966d-4fd1-9e0a-6986b6ea4de6.png">

**Comment by gjsjohnmurray** [comment]
Have you moved Timeline into the new second sidebar?

**Comment by jrieken** [comment]
Just the bottom panel

**Comment by sbatten** [comment]
really thought this was going to be a regression, but its an old regression. either way, should be fixed now. the new side panel is not included in this fix, but will be added after the release.
