### ISSUE TITLE
Incorrect Highlighting of Underline Bold in Markdown 

### ISSUE THREAD

**Issue by LeNouveau** [Microsoft/vscode#13425]
Hi, 

Little bug on markdown format. 
After 2 bold stuffs (ex : `Hello **foor** and **bar**, how are you ?`), all the text is bold. 
- VSCode Version: 1.5.3
- OS Version: Windows 8.1

**Comment by mjbvz** [comment]
Can you please try upgrading to VSCode 1.6+ and see if the problem still repos. I do not see this problem:
 
<img width="384" alt="screen shot 2016-10-13 at 3 48 24 pm" src="https://cloud.githubusercontent.com/assets/12821956/19369816/8a490d1c-915c-11e6-85b7-0354cbffbda9.png">

Thanks.

**Comment by LeNouveau** [comment]
Hi, 

Updated to 1.6.1, but no difference found. 

I understood why I have my problem : I used text with '_' inside. 
![VSCode - Markdown](https://cloud.githubusercontent.com/assets/3670305/19428960/6c568d2c-944d-11e6-9aff-52b329f0dc0b.PNG)

When using "\_", there is no problem anymore. 
So, I'm misusing it ? 

Regards

**Comment by mjbvz** [comment]
@LeNouveau Thanks. Based on the new exampled, I confirmed that we do not properly handle underscores inside of bold blocks:

```md
**a_b** c **d_e** f
```

![image](https://cloud.githubusercontent.com/assets/12821956/19454490/2c760d24-946e-11e6-8476-d6e39b80c4c5.png)

Looks like we match the first `_` after the `a` and then never close the bold block or the italic started by the underscore. Changing the text to `**a_b_**` fixes the highlighting.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-markdown-tm-grammar#5

**Comment by ramya-rao-a** [comment]
@mjbvz I cant repro this in stable 1.22.2
