### ISSUE TITLE
Feature: Support Multiple Version of the Same of Extension(s)

### ISSUE THREAD

**Issue by sgtoj** [Microsoft/vscode#13427]
Is it possible to add ability to support and subscribe to multiple version/build/branch of the same extension(s)? This would allow users to opt-in and subscribe to a beta or development branch of an extension without the need to install another addon (eg [Node Debug](https://marketplace.visualstudio.com/items?itemName=ms-vscode.node-debug2) and [TS and JS Grammar](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar)) or manual install an addon (eg [PowerShell](https://github.com/PowerShell/vscode-powershell/issues/311)). My vision of this feature would allow the user to easily switch between branches from the Extension UI if the extension developer exposes the different versions via the extension manifest.

**Comment by joaomoreno** [comment]
Supporting beta/development versions already works today. An extension can publish a new version, indicating that it is compatible from a specific version of Code. Users would opt in only by updating Code.

This choice makes everyone's life easier. Enabling multiple versions would open the door for functionality conflicts and increased management from the user's part: both things we want to keep at a minimum.

**Comment by gerane** [comment]
cc: @daviwil
