### ISSUE TITLE
Auto save on window focus change still asks to save on close, triggering the save

### ISSUE THREAD

**Issue by cateyes99** [microsoft/vscode#134250]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: **_1.60.2 x64 zip_**
- OS Version: **_Windows 10 Enterprise_**

Steps to Reproduce:

1. Open an file, and make some changes to it.
2. Without saving those changes, try to directly close the file by clicking the `X` button on the editor tab. Now there is a popup coming out, asking `Do you want to save the changes you made ...? Your changes will be lost if you don't save them.` But at this point, the changes are just immediately saved automatically 😮. If you click on either `Cancel` or `Don't Save`, you can be confirmed. I think it's because of the fact, now **VSCode** automatically save changes for existing files when **VSCode** loses its focus. But in this case, the popup window **shouldn't** be treated as not part of **VSCode**.
![image](https://user-images.githubusercontent.com/19678455/135536628-b9661768-dbb0-469e-8d35-9215f4374a9b.png)

**Comment by bpasero** [comment]
This is similar to https://github.com/microsoft/vscode/issues/108752 where I fixed it for when auto save is configured to `onFocusChange` but here it seems that a window focus change is triggered from the dialog too, at least when native dialogs appear.

**Comment by bpasero** [comment]
@cateyes99 to confirm, what is your auto save setting?

**Comment by cateyes99** [comment]
@bpasero it's `onWindowChange`
