### ISSUE TITLE
workbench.colorCustomization.editor.background does not respect transparency

### ISSUE THREAD

**Issue by rowanG077** [microsoft/vscode#134213]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.2
- OS Version: NixOS unstable

Steps to Reproduce:

1. Add `workbench.colorCustomization.editor.background` to the `settings.json` and set it to some color which has transparency. For example `#ff000059`.
2. The editor does NOT show any transparency.

Expected behaviour:
The editor pane should be transparent according the `workbench.colorCustomization.editor.background` setting. This probably extends to most color options.

**Comment by rowanG077** [comment]
In fact there used to be a pr for this: https://github.com/microsoft/vscode/pull/52707

But it got closed for no apparent reason.

**Comment by alexdima** [comment]
I think this is about having the window be transparent.

**Comment by rowanG077** [comment]
@alexdima Yes this is what I expected to happen if I added transparency to the background.
