### ISSUE TITLE
Problems view problems should include direct link for code actions/quick fixes

### ISSUE THREAD

**Issue by chrisjones314** [microsoft/vscode#134296]
I am working with Dart, and it produces warnings that unused package imports should be removed.   On various occasions I have refactored code such that I end up with many files with these warnings.   I also recently upgraded dart, and it started suggesting that I alphabetize imports, which required going through many files to fix warnings.

There is a quick fix/code action which will remove the unused imports automatically.  Currently, in order to use it I double click the message in the problem view, opening the file.  Then I click on the problematic line in the imports, then I hit "command ." to bring up the code actions, then I select "Organize Imports".   I can also achieve this by clicking the little "light bulb" next to the error.  

For these kind of "obvious fix" problems, I wish I could click the lightbulb right in the error message itself in the problem view, and have the fix applied.  This would save time on a task that doesn't really add any value.  It would also be nice to be able to apply certain safe fixes like organize imports across all files in my project, rather than having to choose them manually for each file.

Thanks, I love vscode!

**Comment by sandy081** [comment]
Problems view do show quick fixes

Light bulb:
![image](https://user-images.githubusercontent.com/10746682/136179030-ae252fdf-0c99-40b0-a37e-23c0cda8c881.png)

On right click:
![image](https://user-images.githubusercontent.com/10746682/136179044-8e0fe106-2901-410c-a2a0-91a438c3e307.png)

If you do not see them, please check with Dart extension
