### ISSUE TITLE
Auto show the suggest-widget details after some elapsed time

### ISSUE THREAD

**Issue by anatsegev** [Microsoft/vscode#13420]
- VSCode Version: 0.7.0
- OS Version: All

If user stands on specific suggestion more than x seconds, we would like to show him the detailed documentation regarding the suggestion option (as if he clicked the docs-details icon).

Is there a way to do it with the current api?
If not, we would like request this feature.

Thanks!

**Comment by ramya-rao-a** [comment]
@joaomoreno Given that we are now investing in auto-expanding the details part #18582, we can close this one?

**Comment by joaomoreno** [comment]
Yeah, awesome.
