### ISSUE TITLE
Autocomplete does not work at times

### ISSUE THREAD

**Issue by jaideeprana** [microsoft/vscode#134320]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Attached video to demonstrate the steps to replicate:

https://user-images.githubusercontent.com/3875065/135715659-0c3c437b-5e3d-43f5-a098-8bef3a1940ae.mov

**Comment by jaideeprana** [comment]
**VS Code Version:** 1.60.2
**OS:** macOS 11.6 20G165 x86_64

**Comment by faisalsayed10** [comment]
I think it's a normal behaviour that autocomplete doesn't work when you are using a snippet?

**Comment by ullaskunder3** [comment]
@jaideeprana I had a same problem... It's because of builtin typescript & JavaScript language features extension 
solution #134321

**Comment by mjbvz** [comment]
Try setting `"editor.suggest.snippetsPreventQuickSuggestions": false`

**Comment by ullaskunder3** [comment]
@mjbvz that doesn't fix the issue, the cause of issue is built-in vs code typescript & JavaScript language features extension #134321

**Comment by mjbvz** [comment]
@ullaskunder3 The video shows snippets blocking completions. You're talking about a different issue with a different cause

**Comment by jaideeprana** [comment]
Thanks @mjbvz and @ullaskunder3 . I appreciate both of you reaching out to help me and responding to the issue so fast.

I can confirm that the fix proposed by @mjbvz has fixed the issue for me.

However I have one question @mjbvz why is this setting on the disabled or false by default?
