### ISSUE TITLE
Linux: File watcher confuses symlink with actual directory

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#134369]
In Linux.

Create a repro folder:

```
mkdir repro
cd repro
mkdir client node_modules server
cd node_modules
ln -s ../client client
ln -s ../server server
```

Then:

1. Open `repro` in VS Code
2. Externally create a file in `client`, VS Code explorer reacts to changes
2. Externally create a file in `server`

🐛 VS Code fails to react to changes, the file watcher things the change came from the symlinked `node_modules/server` directory.

```
[2021-10-04 11:16:39.408] [remoteagent] [trace] [File Watcher (nsfw)]  >> ignored /home/joao/tmp/repro/node_modules/server/file
```

**Comment by bpasero** [comment]
This is something `parcel-watcher` should actually be able to fix.

**Comment by bpasero** [comment]
Confirmed 👍
