### ISSUE TITLE
add "are you sure" popup conformation  for "clear recently opened"

### ISSUE THREAD

**Issue by lusicsmusics1** [microsoft/vscode#134356]
for speed of human actions it is possible clear these data mistakenly and it is not good thing 
it must double check for this clear action to prevent mistakenly clearing 

![image](https://user-images.githubusercontent.com/78613940/135763907-5544436f-52c8-4eae-a8fb-ec1a5ac2f367.png)

**Comment by gjsjohnmurray** [comment]
Previously requested in #125727 but didn't get enough upvotes to progress.

**Comment by gjsjohnmurray** [comment]
@mikejpoole you may like to upvote the opening post on this thread since you created the previous issue, which didn't make it past Backlog Candidate.

@lusicsmusics1 remember to add your upvote to your opening post. You may need to lobby colleagues for their votes too.

**Comment by mikejpoole** [comment]
@gjsjohnmurray thanks, I've upvoted (i.e. gave a thumbsup reaction to the issue description).
