### ISSUE TITLE
Suggestions broken on embedded languages

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#134328]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.61.0-insider (system setup)
Commit: 4fbe0344a0cedaf2a04edef728c9a3f27777cc6c
Date: 2021-09-29T05:38:00.706Z
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Investigation from:
https://github.com/styled-components/vscode-styled-components/issues/322#issuecomment-932751877

### Steps to Reproduce:

1.  Install the VSCode Styled Components extension https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components
2. Clone https://github.com/styled-components/vscode-styled-components
3. Navigate to src/tests/suite/colorize-fixtures/segmented-component.js file and add `max-width: 100`  underneath the padding: 3px line
4. Now add % to max-width
5. You should see something like this:
![bad](https://user-images.githubusercontent.com/936006/135726391-ea449ae6-7349-4f09-8b10-c3ff18df929a.gif)6. If you 
hit `;` you end up getting a bad suggestion (like above): 

### What's Expected

In a CSS file doing the same yields a much better experience. It only suggests the `100%` and not others, and doesn't give weird textinputs when hitting semicolon or enter.
![good](https://user-images.githubusercontent.com/936006/135726433-f8b11acf-4c57-4085-88c2-308ee0bb2573.gif)

We have [debugged](https://github.com/styled-components/vscode-styled-components/issues/322#issuecomment-932751877) this problem in depth and it seems to be a UI issue. This used to work as expected but over the past year it has been behaving like this, the extension hasn't changed and an old version of the extension does the same thing, so I believe something in the VSCode UI has changed to cause this. Any help would be appreciated.
I checked the language server, and that responds the same to both the embedded language and a native CSS file so I don't think the issue is there.

**Comment by mjbvz** [comment]
Have you tested using older TypeScript versions to see if the Typescript update caused this?

**Comment by jasonwilliams** [comment]
@mjbvz yep
![015](https://user-images.githubusercontent.com/936006/135911622-4ad60f52-985a-46b3-b919-b9ec2d8e23eb.gif)

This is using version 0.15.0 of the typescript styled plugin which is using an old "v3.6.4" of typescript

**Comment by jasonwilliams** [comment]
@mjbvz i appreciate you may not have time to properly look at this, but do you have any suggestions where we can look to figure out what’s going on?

I’ve looked at the language server results (from both css and typescript styled plugin) and they seem to be ok, so it could be the UI messing this up.

**Comment by mjbvz** [comment]
If the TS server responses to VS Code are correct (you can check this using `"typescript.tsserver.trace": "verbose"`), you probably need to debug in VS Code itself to figure out why they are not showing up:

https://github.com/microsoft/vscode/blob/2c991637922e4733c7c97d3900d81fb041066d43/src/vs/editor/contrib/suggest/suggest.ts#L194

You should be able to confirm that the completion items are returned but then getting filtered out for some reason

**Comment by jasonwilliams** [comment]
Progress report:

I've populated `replacementSpan` [here](https://github.com/microsoft/typescript-styled-plugin/blob/main/src/_language-service.ts#L394-L406)

![image](https://user-images.githubusercontent.com/936006/142723841-9c0484e4-611d-475c-bdf0-aa4719f294cb.png)

And now i can see a range making its way to VSCode:
<img width="1516" alt="Screenshot 2021-11-20 at 11 01 11" src="https://user-images.githubusercontent.com/936006/142723879-07e9deb5-e316-490b-9950-6c31ea517f99.png">

j wasn't populated before. The only issue now is the range is wrong. It seems what ever is being used in the first image isn't yielding the correct value.

It looks like `start: doc.offsetAt((item as any).textEdit.range.start)` isn't correct?

**Comment by jasonwilliams** [comment]
Finally managed to fix this here: https://github.com/microsoft/typescript-styled-plugin/pull/156 @mjbvz will need a review
