### ISSUE TITLE
Maven repo usage - feature request

### ISSUE THREAD

**Issue by raxim1** [Microsoft/vscode#13437]
- VSCode Version: Who knows, it is not under help menu, can be a new feature.
- OS Version: Ubuntu 16.04

Steps to Reproduce:

I tried to use "maven mate plugin" without success.

I think the java editor is useless, if i cannot attach jar files or folder to the project, but it would be very easy, if i can just point out to my maven repository, and it can figure out the libraries according to the pom file. (It is not necessary to make a maven build, but it would be good if i can browse my project, wherever there is java source)

**Comment by aeschli** [comment]
Please file this request against the Java extension: https://github.com/redhat-developer/vscode-java/issues
