### ISSUE TITLE
Shortcut to Collapse/Show html all tag's class/attribute values

### ISSUE THREAD

**Issue by devmahdi404** [microsoft/vscode#134353]
**Shortcut** to Collapse/Show html all tag's class/attribute values.

Like this,
`<div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden"><div>`
to
`<div class="..."><div>`

When you are using things like [Tailwindcss](https://tailwindcss.com) or [Alpinejs](https://alpinejs.dev) / [hyperscript](https://hyperscript.org), it could be pretty helpful there.

**Comment by aeschli** [comment]
VS Code only supports folding full lines. #50840 is the feature request for folding inside a line.
