### ISSUE TITLE
Suggest widget color customizations

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#134326]
Issue Type: <b>Bug</b>

The foreground color is too dark to make the eyes look tired for a long time. I cannot customize the font foreground color of the code document description. You can tell me where I can customize the font color.
I used red boxes and arrows to make detailed annotations. . .
![代码文档描述信息字体太黑了无法修改](https://user-images.githubusercontent.com/54253524/135722356-67c7f5e4-483d-4091-97cd-83e47333c843.png)

VS Code version: Code - Insiders 1.61.0-insider (c9e8266ee24f34107ff52d836a4e8f533afb93c5, 2021-10-01T14:45:54.159Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|9.59GB (1.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by varun0308** [comment]
Hey @zhouxinghong , as for as I know, we don't have control over font color, but you can change your theme to high contrast (Settings button left bottom then color theme), which I think solves your issue.
If that doesn't work, you can add extensions which will allow you to change font color and opacity.
I hope this helps.

**Comment by zhouxinghong** [comment]
> Hey @zhouxinghong , as for as I know, we don't have control over font color, but you can change your theme to high contrast (Settings button left bottom then color theme), which I think solves your issue. If that doesn't work, you can add extensions which will allow you to change font color and opacity. I hope this helps.

In the past, the foreground color of Intellij IDEA document information was very dark, but now it can be customized and modified. I think Intellij IDEA can allow users to customize the foreground color settings for applications as complex as Intellij IDEA. Then you can also make changes from the VSCode UI elements. More freedom of setting power is left to the user's own decision, not that you can't do it. It's just that you are willing to consider the user's development experience and make changes. VSCode is still very young and the road ahead is long. I think it is not difficult to make changes from VSCode UI elements. . .

**Comment by zhouxinghong** [comment]
> Hey @zhouxinghong , as for as I know, we don't have control over font color, but you can change your theme to high contrast (Settings button left bottom then color theme), which I think solves your issue. If that doesn't work, you can add extensions which will allow you to change font color and opacity. I hope this helps.

It is the most sensible way to add the foreground color setting item of the code document description information to the setting.json and leave it to the user to handle it by himself. The previous Intllij IDEA is also the same as the current VSCode. The UI elements do not allow users to set up by themselves, which leads to a very poor user programming experience and loses many users... But after the experience... Now Intllij IDEA users can change themselves according to the comfort of their own coding Yes, this is a very user-friendly coding experience improvement.

It is recommended to redefine all UI black (obsolete) elements so that users can decide how to modify the settings. I have summarized a large number of UI black (obsolete) unfriendly UI elements in the previous feedback, but no one has dealt with them. ....

**Comment by aeschli** [comment]
@zhouxinghong You can customize colors in the settings. For example the foreground color in the suggest widget:
```
	"workbench.colorCustomizations": {
		"editorSuggestWidget.foreground": "#ff0000"
	}
```
@jrieken I didn't see a color for the status bar. Is it using opacity? Maybe a separate color would be good.

**Comment by jrieken** [comment]
> @jrieken I didn't see a color for the status bar. Is it using opacity? Maybe a separate color would be good.

Yeah, it uses opacity 0.5

**Comment by zhouxinghong** [comment]
> @zhouxinghong You can customize colors in the settings. For example the foreground color in the suggest widget:
> 
> ```
> 	"workbench.colorCustomizations": {
> 		"editorSuggestWidget.foreground": "#ff0000"
> 	}
> ```
> 
> @jrieken I didn't see a color for the status bar. Is it using opacity? Maybe a separate color would be good.
Hello! After trying, it has nothing to do with the "editorSuggestWidget.foreground" setting

**Comment by zhouxinghong** [comment]
> > @jrieken I didn't see a color for the status bar. Is it using opacity? Maybe a separate color would be good.
> 
> Yeah, it uses opacity 0.5

Hello! Such a simple problem can be modified with a simple effort. As long as you modify a CSS font color, it can be fixed. Don't wait for the community to vote. Wait for the community to vote. I don't know how long and how long it will take to fix it. It may never be fixed. VSCode A good IDE should be developed based on an excellent user experience. At present, it doesn't matter if some features are less. Doing every detail and stability well is what users want most. Hope you can fix this problem. thank you very much!

**Comment by zhouxinghong** [comment]
> @zhouxinghong You can customize colors in the settings. For example the foreground color in the suggest widget:
> 
> ```
> 	"workbench.colorCustomizations": {
> 		"editorSuggestWidget.foreground": "#ff0000"
> 	}
> ```
> 
> @jrieken I didn't see a color for the status bar. Is it using opacity? Maybe a separate color would be good.

Hello! Such a simple problem can be modified with a simple effort. As long as you modify a CSS font color, it can be fixed. Don't wait for the community to vote. Wait for the community to vote. I don't know how long and how long it will take to fix it. It may never be fixed. VSCode A good IDE should be developed based on an excellent user experience. At present, it doesn't matter if some features are less. Doing every detail and stability well is what users want most. Hope you can fix this problem. thank you very much!

**Comment by jrieken** [comment]
I have pushed a change that allows to configure the color of suggest status items: `editorSuggestWidgetStatus.foreground`, for instance like so <img width="293" alt="Screen Shot 2021-11-03 at 16 28 41" src="https://user-images.githubusercontent.com/1794099/140091567-4f0e2385-0552-4fae-adb3-fd378c14da63.png">

**Comment by zhouxinghong** [comment]
> I have pushed a change that allows to configure the color of suggest status items: `editorSuggestWidgetStatus.foreground`, for instance like so
> 
> <img alt="Screen Shot 2021-11-03 at 16 28 41" width="293" src="https://user-images.githubusercontent.com/1794099/140091567-4f0e2385-0552-4fae-adb3-fd378c14da63.png">

Um! Teacher, your idea is great! Great! But I don’t know if your idea can solve this problem: [https://github.com/microsoft/vscode/issues/134326], if it can be solved directly in the next milestone, then thank you very much, teacher, You are really very, very great, very, very awesome 👍👍👍😜!

**Comment by zhouxinghong** [comment]
Hello, teacher!
If you confirm my needs, please reply, thank you very much!

**Comment by zhouxinghong** [comment]
> I have pushed a change that allows to configure the color of suggest status items: `editorSuggestWidgetStatus.foreground`, for instance like so
> 
> <img alt="Screen Shot 2021-11-03 at 16 28 41" width="293" src="https://user-images.githubusercontent.com/1794099/140091567-4f0e2385-0552-4fae-adb3-fd378c14da63.png">

Hello, teacher!
If you confirm my needs, please reply, thank you very much!

**Comment by zhouxinghong** [comment]
> > I have pushed a change that allows to configure the color of suggest status items: `editorSuggestWidgetStatus.foreground`, for instance like so
> > <img alt="Screen Shot 2021-11-03 at 16 28 41" width="293" src="https://user-images.githubusercontent.com/1794099/140091567-4f0e2385-0552-4fae-adb3-fd378c14da63.png">
> 
> Um! Teacher, your idea is great! Great! But I don’t know if your idea can solve this problem: [https://github.com/[/issues/134326](https://github.com/microsoft/vscode/issues/134326)], if it can be solved directly in the next milestone, then thank you very much, teacher, You are really very, very great, very, very awesome 👍👍👍😜!
> 
> It may be that what I described earlier is not clear enough or detailed enough. . . Here again, the detailed explanation is as follows: Hello, teacher! It is recommended that the font foreground color of the widget needs to be changed. I used red numbers and green arrows to make detailed marking instructions. I also used the green box to mark the range of the font foreground color that needs to be changed. Please see the picture below: ![66666666666666](https://user-images.githubusercontent.com/54253524/140309160-5988199c-0cd3-46f9-ac96-f59d76e114a7.png)

Hello, teacher!
If you confirm my needs, please reply, thank you very much!

**Comment by zhouxinghong** [comment]
Hello, teacher! Please confirm with the relevant personnel the foreground color of the area that needs to be improved. Please pay attention to the red number (1, 2, 3) and the area foreground color marked with the green box. These are the foreground colors that need to be modified for this feedback. Teachers, please confirm your needs with relevant personnel so as not to omit relevant information. Thank you very much! I wish you a good mood every day! all the best! Thank you!

**Comment by zhouxinghong** [comment]
> > @jrieken I didn't see a color for the status bar. Is it using opacity? Maybe a separate color would be good.
> 
> Yeah, it uses opacity 0.5

Hello, teacher! Please confirm with the relevant personnel the foreground color of the area that needs to be improved. Please pay attention to the red number (1, 2, 3) and the area foreground color marked with the green box. These are the foreground colors that need to be modified for this feedback. Teachers, please confirm your needs with relevant personnel so as not to omit relevant information. Thank you very much! I wish you a good mood every day! all the best! Thank you!

**Comment by jrieken** [comment]
To _verify_ make sure there is this new theme color `editorSuggestWidgetStatus.foreground`

**Comment by jrieken** [comment]
Oh, forget to mention that. There is a setting for this `"editor.suggest.showStatusBar": true`

**Comment by rchiodo** [comment]
Thanks. Works for me 👍 

![image](https://user-images.githubusercontent.com/19672699/144287055-1c68b412-dc36-44c0-9ea9-c713fed6d8a5.png)


@zhouxinghong you should be able to set these two settings once the next release ships:

```json
    "workbench.colorCustomizations": {
      "editorSuggestWidgetStatus.foreground": "#ff0000"
    },
    "editor.suggest.showStatusBar": true,
```
