### ISSUE TITLE
Command for opening keybindings (JSON) of different platform

### ISSUE THREAD

**Issue by zardoy** [microsoft/vscode#134338]
Type: Command request. Useful when settings sync is enabled.

There is builtin command *Preferences: Open Keyboard Shortcuts (JSON)*. But it opens keybindings only of current platform, but sometimes I need to view / copy / or even modify shortcuts of different platforms.

I found only one solution. I need to go *Troubleshooting* tab of *Settings Sync* View, open `lastSynckeybindings.json` (Last Synced Remotes -> Keyboard Shortcuts). And parse via script, that will give JSON for each platform e.g.
```json
{
    "windows": keybindings.json,
    "mac": keybindings.json
}
```

**Comment by zardoy** [comment]
But why? I don't see a reason to not have it builtin.

I need sometimes to look at windows shortcuts when I'm on macos.

Implemented in [extra-commands#openShortcutsOfAnotherPlatform](https://marketplace.visualstudio.com/items?itemName=zardoy.extra-commands)...

**Comment by goodshort** [comment]
Thanks for pointing this out @zardoy I was really surprised by default it is not possible to see the keybindings from different platform... Going to the troubleshooting tab did the trick
