### ISSUE TITLE
Unexpected changes to in-memory file paths parsing

### ISSUE THREAD

**Issue by merceyz** [microsoft/vscode#134304]
Issue Type: <b>Bug</b>

The in-memory file path parsing changes introduced in https://github.com/microsoft/vscode/commit/8731be5e78343f8960c2c70f16dd7eb6c92d0d6b causes file paths that would have been parsed successfully by `vscode.Uri.parse` to no longer match. The Uri is now required to start with a slash and use a slash to seperate the schema from the path which is unexpected and seems like a bug
```diff
-^zip:/c:/foo/bar.zip/package.json
+^/zip//c:/foo/bar.zip/package.json
```

VS Code version: Code - Insiders 1.61.0-insider (c9e8266ee24f34107ff52d836a4e8f533afb93c5, 2021-10-01T14:45:54.159Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by mjbvz** [comment]
What problem does this cause?

**Comment by merceyz** [comment]
"Go to Definition" is broken for `tsserver` instances that return in-memory schemas, in our case Yarn PnP / https://github.com/microsoft/vscode/issues/75559. I can update our `tsserver` to return paths that work with the changes but it's odd a valid `vscode.Uri` isn't valid anymore.

**Comment by mjbvz** [comment]
Thanks for the details

Yes I recommend changing it on the plugin side. These paths are used internally by TS Server, so they don't follow `vscode.URI` and we don't make any guarantees about their format. That said, if you have a proposal on how to change the format in a way that won't cause regressions to other features, I'd be happy to merge that in

**Comment by arcanis** [comment]
@mjbvz Why was the old `vscode.Uri.parse(filepath.slice(1))` incorrect? The commit message mentions errors in untitled files, but the format change doesn't seem directly connected to this, is it? Or is there another place where this new format is necessary?

**Comment by mjbvz** [comment]
The change gets TS to see in-memory files as part of the same project, instead of treating them as individual units

**Comment by mjbvz** [comment]
I'm closing this as we don't plan on taking any action on the VS Code side (and as noted, these paths are an internal implementation details)

Will still take a PR if someone submits a reasonable one
