### ISSUE TITLE
Feature Request: Add language support for Vala/Genie

### ISSUE THREAD

**Issue by joeljose350** [microsoft/vscode#134346]
VS Code does not recognise .vala files and users have to install extensions like [Vala](https://marketplace.visualstudio.com/items?itemName=prince781.vala) in order to get basic syntax highlighting and error detection.

**Comment by gjsjohnmurray** [comment]
Adding support for specific languages is one of the purposes of VS Code's extension architecture. What is the problem about expecting Vala/Genie users to install the appropriate extension?
