### ISSUE TITLE
Check language status bar contributions

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#134375]
Check current status bar contributions and provide recommendation on how to move forward

- [ ] Python https://github.com/microsoft/vscode-python/issues/18040
- [ ] C# https://github.com/OmniSharp/omnisharp-vscode/issues/4898
- [ ] C++ https://github.com/microsoft/vscode-cpptools/issues/8405
- [ ] Java - waiting for better API support for progress status bar items

Previous discussion https://github.com/microsoft/vscode/issues/129037

fyi @jrieken

**Comment by isidorn** [comment]
We have reached out to the language partner teams. I suggest we do not reach out to more language extensions until the above extensions adopt it and we finalise the API.

I know @dbaeumer is also waiting for API finalisation before adopting it for `eslint`.
@jrieken let me know if you think we should reach out to anyone else this milestone.

**Comment by isidorn** [comment]
No more action planned for this milestone thus moving to December. Then we can see if we want to reach out to more extension partners.

**Comment by isidorn** [comment]
We have finalized the language status bar API.
Python has adopted to this.
Java plans to adopt to it soon.
C++ I will bring this up in my sync with their extension team on Thursday.

Thus closing this issue.

**Comment by brettcannon** [comment]
To be clear, we have an experiment to adopt the language status API for Python, but the experiment is ongoing.
