### ISSUE TITLE
LIT cAOURIER

### ISSUE THREAD

**Issue by newlit2020** [microsoft/vscode#134364]
Issue Type: <b>Bug</b>

LIT cAOURIER

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.22454
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.86GB (0.75GB free)|
|Process Argv|--crash-reporter-id 0d35c6fa-e34a-4159-85a3-9953092019fe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-django|bat|1.6.0
doxdocgen|csc|1.3.2
c-cpp-compile-run|dan|1.0.14
python-preview|don|0.0.4
python-extension-pack|don|1.6.0
better-cpp-syntax|jef|1.15.10
MagicPython|mag|1.1.0
vscode-language-pack-ru|MS-|1.60.4
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.4
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.3
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
cmake-tools|ms-|1.8.1
cpptools|ms-|1.7.0-insiders2
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4836
vsliveshare-audio|ms-|0.1.91
platformio-ide|pla|2.3.3
python|tht|0.2.3
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.14
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis200:30374795
vsaa593cf:30376535

```

</details>

**Comment by CodeCrazy-ywt** [comment]
???

**Comment by CodeCrazy-ywt** [comment]
What do u mean?
