### ISSUE TITLE
LICENSE icon does not read as keys at icon size

### ISSUE THREAD

**Issue by CAD97** [microsoft/vscode#134358]
Issue Type: <b>Bug</b>

1. Open a folder with a LICENSE file
2. Observe the icon

At icon size, it looks like a humanoid walking to the right, rather than keys on a keyring.

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis200:30374795
vsaa593cf:30376535

```

</details>

Example:

![image](https://user-images.githubusercontent.com/5992217/135771131-f0f3c430-1175-408b-9fcd-16eda7d73f64.png)

![image](https://user-images.githubusercontent.com/5992217/135771138-f6d6f3a6-1cd0-4dea-82d2-731e056ab644.png)

![image](https://user-images.githubusercontent.com/5992217/135771160-c99c805c-40f9-4141-bb38-a83a75044e66.png)

**Comment by aeschli** [comment]
We get the icons from https://github.com/jesseweed/seti-ui. Can you file the issue there?
