### ISSUE TITLE
Problem running Go executable on VSCode Windows 11

### ISSUE THREAD

**Issue by Paul-Fomichov** [microsoft/vscode#134361]
Issue Type: <b>Bug</b>

Hello,

I'm using VS Code for Go (Golang) development.

However recently when trying to run any Go project (F5 or Ctrl + F5) I get an error prompt: "Failed to launch fork/exec

This version of %1 is not compatible with the version of Windwos you're running. Check your computer's system information and then contact the software publisher".

This error is not replicated if I run my Go project using the command line `go run .` or when I launch it using other IDE, such as Goland. It's not even replicated in other Go projects in VS Code, but I quickly stumble upon it sooner or later. The workaround I found is to copy my source files and move them to a new folder - then I can launch my project again. But after a short while I again get that error prompt preventing me to launch my project using Ctrl+F5.

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HS with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.41GB (17.45GB free)|
|Process Argv|--crash-reporter-id de7cfa1c-fe05-4140-9fc8-9e4808991a40|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
atom-icons|emr|1.2.0
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
go|gol|0.28.1
vscode-docker|ms-|1.17.0
remote-containers|ms-|0.194.3
remote-wsl|ms-|0.58.2
sqltools|mtx|0.23.0
sqltools-driver-mysql|mtx|0.2.0
vscode-icons|vsc|11.6.0
material-theme|zhu|3.13.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis300:30374797
vsaa593:30376534

```

</details>

**Comment by IllusionMH** [comment]
/causedByExtension

VS Code doesn't provide Go functionality and doesn't run executables directly - this is handled by Go extension.
Please make sure that you have proper configuration for this project (because it's strange that other work as expected) and then report in extension's repo https://github.com/golang/vscode-go/issues if it wasn't reported earlier.
