### ISSUE TITLE
gdb substitute-path like behavior for terminal links

### ISSUE THREAD

**Issue by capiro** [microsoft/vscode#134323]
The project I'm working on compiles the code from a different directory. Prior to compilation the code is copied over (rsync).
As a result the errors in the terminal point to the compilation directory and not to the source code directory.
Using the terminal link to navigate to the file often leads to fixing the error in that file, which will soon be overridden on the next compilation cycle.
The gnu gdb debugger has a feature that allows path substitution when looking for source files.
https://sourceware.org/gdb/onlinedocs/gdb/Source-Path.html#set-substitute_002dpath

I wish there was a way to customize via settings the behavior of the terminal links to apply some substitutions so the link that gets opened is not the original link.

**Comment by Tyriar** [comment]
Extensions can setup link providers to handle links.
