### ISSUE TITLE
Use warning language status for TS partial mode

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#134385]
Suggestion to use the warning severity when TS run in partial mode, esp not that the warning is less "loud" (see https://github.com/microsoft/vscode/issues/134102#issuecomment-930170687 and https://github.com/microsoft/vscode/issues/134102#issuecomment-932422528)

![image](https://user-images.githubusercontent.com/1794099/135869567-6339305f-85c3-4352-9262-bf62eb6b8b4b.png)

**Comment by jrieken** [comment]
cc @egamma

**Comment by mjbvz** [comment]
Here's what this looks like:
<img width="709" alt="Screen Shot 2021-10-04 at 9 19 04 AM" src="https://user-images.githubusercontent.com/12821956/135887603-dfbfddff-e6ac-4039-9c6d-f65dc19351af.png">
