### ISSUE TITLE
gitActions.ts - cannot read property length of undefined

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1343]
Latest vscode, out of workbench, with my weird workspace i sometimes get these esceptions.
Maybe add a null guard since `getRemotes()` returns `null`

![screen shot 2015-12-15 at 17 20 51](https://cloud.githubusercontent.com/assets/1926584/11816350/41de4e02-a350-11e5-9a99-eb8375774d3b.png)

**Comment by joaomoreno** [comment]
Thanks!

**Comment by joaomoreno** [comment]
I don't see how this exception can happen.

Can you still effectively reproduce? If so, let me know how so I catch it.

**Comment by isidorn** [comment]
No I can not repro. It just happened out of nowhere

**Comment by joaomoreno** [comment]
Let's see if it comes up in error telemetry.
