### ISSUE TITLE
Welcome page as preview page

### ISSUE THREAD

**Issue by yankyhoffman** [microsoft/vscode#134381]
I really enjoy having the welcome page open in new empty vscode windows, what does get me wrong is the fact that once I start working on a new file etc I need to still close the welcome page, I would love something in the sense that as soon as I open a new page or project that the welcome page should be closed

**Comment by JacksonKearl** [comment]
It should open in preview already, but if you interact with it it moves out of preview. Is that what is happening here? We could be more specific about what interactions cause it to become non-preview.
