### ISSUE TITLE
The brackets in the comments remain colored

### ISSUE THREAD

**Issue by Levsha1337** [microsoft/vscode#134357]
Issue Type: <b>Bug</b>

In TSX syntax if i comment line 5 (in example) (by pressing ctrl + /) brackets remains colored blue until i switch to the other tab and go back or until i add any symbols in line to move brackets.

Example:
```
1 <Button
2     icon='save'
3     name='saveRole'
4     shape='round'
5     disabled={!this.state.isButtonActive}
6 />
```

VS Code version: Code - Insiders 1.60.0-insider (c08913337cb8b95493be8e99d62e0b3241563f6b, 2021-08-19T05:15:46.693Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (0.53GB free)|
|Process Argv|--crash-reporter-id 9c5de59b-1f2e-4507-99a7-e7aed846a0ce|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.25
gitlens|eam|11.6.0
copilot|Git|1.4.2795
clone-pilot|Goe|0.1.1
mayukaithemevsc|Gul|3.0.1
vscode-typescript-next|ms-|4.5.20210929
material-icon-theme|PKi|4.10.0
vscode-xml|red|0.18.0
vscode-sftp|sun|1.1.1

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30364496
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsqsis400:30374798

```

</details>

**Comment by hediet** [comment]
Can you update your insiders build? "2021-08-19" is quite outdated.

**Comment by Levsha1337** [comment]
> Can you update your insiders build? "2021-08-19" is quite outdated.

Okay, I can't reproduce the bug in the latest version. Sorry to bother you.
