### ISSUE TITLE
Do not default to mouse position selection when intellisense or dropdowns are spawned by keyboard actions

### ISSUE THREAD

**Issue by roa-nyx** [microsoft/vscode#134360]
When the intellisense menu spawns it will normally select the first item. That is my expectation and I sometimes press Tab to accept the first option without even waiting to read it because I know it'll pick the right thing.

However if menu happens to spawn under the mouse cursor the item that the mouse is over will be selected instead of the first item. Because I don't wait to see what is selected the result is unexpectedly triggering functionality, that requires an undo, and moving the mouse cursor out of the way before I can continue coding.

The feature I'd like to see is one of the following:
- A) Do not allow the intellisense menu to spawn under a mouse cursor.
- B) Add an option to hide the mouse cursor while typing (which should treat it as if the mouse is off-screen and not make it possible to select anything with it).
- C) When intellisense is triggered by a keyboard press, do not allow the initial mouse position to select an item until the mouse is moved.

Love VS Code. You guys rock.

**Comment by gjsjohnmurray** [comment]
Maybe a duplicate of #110594

**Comment by roa-nyx** [comment]
@gjsjohnmurray Yes it is! Sorry about that. I didn't think of it as a bug so when I searched "features" and didn't see it I figured it wasn't tracked anywhere. Feel free to close this, I'll follow along on that task.
