### ISSUE TITLE
High CPU usage while working on notebook

### ISSUE THREAD

**Issue by Syndorik** [microsoft/vscode#134396]
## Environment data

-   VS Code version: 1.61.0-insider c9e8266ee24f34107ff52d836a4e8f533afb93c5 x64
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1001294413
-   Python Extension version (available under the Extensions sidebar): v2021.9.1246542782
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04 (via WSL2)
-   Python and/or Anaconda version: Python 3.9.7 conda 4.10.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote

I'm filing a bug report based on my comment on [#7439](https://github.com/microsoft/vscode-jupyter/issues/7439.) issue. I don't know if it is related.

My CPU consumption is toward 100% when working on jupyer vscode. It freezes a bit when I'm just scroling on a notebook. It usually happens with a notebook of 10 empty cells, and it seems that the CPU usage increases as the number of increases too.

I have the following cpu profiler
[CPU-20210930T114733.cpuprofile.txt](https://github.com/microsoft/vscode-jupyter/files/7278292/CPU-20210930T114733.cpuprofile.txt)

However when I'm working on other files (not ipynb files), the CPU usage is stable and doesn't increase. Also, my jupyter server is remote, so this cannot be linked to some code running in the background.

[EDIT]
I have just seen that just by moving the mouse on the unfocused vscode window, the high memory consumption happens

**Comment by rebornix** [comment]
did you have cell executing while this happened? It seems that every few seconds there are huge chunk of data coming to the UI side so I wonder if it was caused by output changes.

**Comment by Syndorik** [comment]
This is actually happening on a notebook with 12 empty cells or more. And when I did the CPUprofile, there were no running cells. If you want, I did another CPU profile with an empty notebook.
[CPU-20211011T161953.982Z.cpuprofile.txt.txt](https://github.com/microsoft/vscode/files/7323956/CPU-20211011T161953.982Z.cpuprofile.txt.txt)
