### ISSUE TITLE
Mac VSCode Debugger Not Work

### ISSUE THREAD

**Issue by huizhifan** [microsoft/vscode#134307]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.60.2
- OS Version: OSX

![Screen Shot 2021-10-01 at 2 40 22 PM](https://user-images.githubusercontent.com/60024380/135689448-04be2cb7-ca25-4e94-aed6-68397832decd.png)
![Screen Shot 2021-10-01 at 2 01 40 PM](https://user-images.githubusercontent.com/60024380/135689451-c0594ea6-73bf-41b9-9245-49bcaf40415f.png)

It worked before but broken suddenly.

**Comment by roblourens** [comment]
Please file this on the repo for the extension that you are using. Maybe the app is not actually starting, using the wrong port, or something else
