### ISSUE TITLE
Insertion of space before closing non-empty parenthesis does not work

### ISSUE THREAD

**Issue by hubbergit** [Microsoft/vscode#13430]
- VSCode Version: 1.5.3
- OS Version: Win10

Steps to Reproduce:

1. Configuration: "typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": true

2. Format this code:
```
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'x-com',
    templateUrl: './app/x-com.html',
    providers: [XComSer]
})
export class XComponent {
}
```
3. There is no space before the closing parenthesis just before the export class XComponent line

**Comment by waderyan** [comment]
@hubbergit thank you for opening this issue. To make sure I understand what you expect to see, you expect to see the following:

```typescript
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'x-com',
    templateUrl: './app/x-com.html',
    providers: [XComSer]
} )
export class XComponent {
}
```

Is that correct?

**Comment by hubbergit** [comment]
Yes, I would expect to see a space not only after the opening parenthesis, but also after the closing parenthesis:

 

import { Component, OnInit } from '@angular/core';
 
@Component( {
    selector: 'x-com',
    templateUrl: './app/x-com.html',
    providers: [XComSer]
} )
export class XComponent {
}

 

 

Von: Wade Anderson [mailto:notifications@github.com] 
Gesendet: Dienstag, 11. Oktober 2016 19:03
An: Microsoft/vscode
Cc: hubbergit; Mention
Betreff: Re: [Microsoft/vscode] Insertion of space before closing non-empty parenthesis does not work (#13430)

 

@hubbergit <https://github.com/hubbergit>  thank you for opening this issue. To make sure I understand what you expect to see, you expect to see the following:

import { Component, OnInit } from '@angular/core';
 
@Component({
    selector: 'x-com',
    templateUrl: './app/x-com.html',
    providers: [XComSer]
} )
export class XComponent {
}

Is that correct?

**Comment by hubbergit** [comment]
Yes, I would expect to see a space not only after the opening parenthesis, but also after the closing parenthesis:
```
import { Component, OnInit } from '@angular/core';
 
@Component( {
    selector: 'x-com',
    templateUrl: './app/x-com.html',
    providers: [XComSer]
} )
export class XComponent {
}
```

**Comment by waderyan** [comment]
@hubbergit thank you for the explanation. This is a language service issue. I am moving this to the language service repo.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11626
