### ISSUE TITLE
Retry as Admin does not work on Windows 11.

### ISSUE THREAD

**Issue by NeeleyG** [microsoft/vscode#134310]
Issue Type: <b>Bug</b>

1. Open "C:\Windows\System32\drivers\etc\hosts" with VS Code.
2. Make changes to the file.
3. Try to save.
4. Recieve error message in lower left corner. 
5. Click Retry as Admin button
6. Recieve "Failed to save 'host': User did not grant permissions
7. Click Rety
8. Goto 4

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (20.44GB free)|
|Process Argv|--crash-reporter-id 06e2f95f-33ed-46c7-9556-e6d3ac2984cc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-json|and|1.5.0
insert-unicode|bru|0.13.1
highlight-line-vscode|cli|0.0.1
gitlens|eam|11.6.0
vscode-html-css|ecm|1.10.2
vscode-highlight|fab|1.5.1
vscode-projects-plus|fab|1.23.4
vscode-projects-plus-todo-plus|fab|1.6.10
vscode-todo-plus|fab|4.18.4
plantuml|jeb|2.15.1
labeled-bookmarks|koa|1.1.10
git-graph|mhu|1.30.0
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.4
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
powershell|ms-|2021.9.2
fix-json|oli|0.1.2
fabric8-analytics|red|0.3.3
java|red|0.82.0
vscode-commons|red|0.0.6
code-spell-checker|str|2.0.8
python|tht|0.2.3
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-pack|vsc|0.18.5
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis400:30374798

```

</details>

as too large to send. Please paste.

**Comment by bpasero** [comment]
This works fine for me on Windows 11, so I am not quite sure this is related to the OS but maybe rather specific to your setup.
