### ISSUE TITLE
Slow response form vs code emmet due to @builtin TS & JS language feature extension 

### ISSUE THREAD

**Issue by ullaskunder3** [microsoft/vscode#134321]
Issue Type: <b>Performance Issue</b>

Everything work's fine for smaller projects, but as I started working on larger backend project I felt the response from vs code Emmet getting slow on some point it's just took several seconds to show the suggestion

https://user-images.githubusercontent.com/66258652/135718106-1c087fc9-43fd-4252-8912-c0fe0be1674e.mp4

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.69GB (2.86GB free)|
|Process Argv|--crash-reporter-id b13aa7f5-b359-41cf-928a-e98c0833ffd2|
|Screen Reader|no|
|VM|0%|
</details><details>

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● user.js - FullStackApps - Visual Studio Code)
|    Folder (FullStackApps): 23 files
|      File types: js(8) json(2) md(1) env(1) gitignore(1) sh(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.44.3
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|9.0.0
vscode-language-babel|mgm|0.0.35
js-debug-nightly|ms-|2021.9.2817
debugger-for-chrome|msj|4.13.0
material-icon-theme|PKi|4.10.0
vscode-thunder-client|ran|1.9.1
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.14
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis200:30374795
vsaa593cf:30376535

```

</details>

**Comment by ullaskunder3** [comment]
Okk I think I know why vs code JavaScript Emmet slowing down, firstly
- I reinstalled vs code [didn't work]
- Then I tried insider the same problem [didn't work]
finally:
- I deleted node modules folders then I reload window surprisingly Emmet is working fine

```package.json
  "dependencies": {
    "cookie-parser": "^1.4.5",
    "cors": "^2.8.5",
    "dotenv": "^10.0.0",
    "express": "^4.17.1",
    "express-jwt": "^6.1.0",
    "express-validator": "^6.12.2",
    "formidable": "^1.2.2",
    "jsonwebtoken": "^8.5.1",
    "lodash": "^4.17.21",
    "mongoose": "^5.13.9",
    "morgan": "^1.10.0",
    "shortid": "^2.2.16",
    "slugify": "^1.6.0",
    "string-strip-html": "^8.3.0"
  }
```

**Comment by ullaskunder3** [comment]
Ahaa... I did it solution: Emmet slow down because of builtin ts&js extension

- Go to extension tab or `Ctrl+Shift+X`
- Search by `@builtin`  
- In feature disable __TypeScript and JavaScript language Features v1.0.0__
- Finally from command palette `Ctrl+Shift+P` `Reload Window` 🐱‍👤.

**Comment by jaideeprana** [comment]
@ullaskunder3 Thanks for sharing the link.

However, that fix didn't work for me.
Still experiencing the issue.

**Comment by rzhao271** [comment]
Is the loading preventing one from using Emmet commands? CC @mjbvz

**Comment by mjbvz** [comment]
Possibly. All suggestions providers have to resolve before any suggestions are shown

That said, disabling JS/TS disables all JS/TS IntelliSense features so it's not really a solution unless you're ok without IntelliSense 

@ullaskunder3  Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all (non-builtin) [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? If so, please share a small example project that demonstrates the issue

**Comment by ullaskunder3** [comment]
@mjbvz sir I did as you told... 
to be honest I'm confused what exactly causing the Emmet delay **TypeScript and JavaScript Language feature**  extension

Task

- Using VS Code insider with all (non-builtin) extensions disabled.

https://user-images.githubusercontent.com/66258652/135897241-dcd11b05-69fa-4033-9929-63231925939f.mp4

conclusion same problem with Emmet delay of 5s 

I find out something else as well

- I tried another similar project with enabled  `TypeScript and JavaScript Language feature` IT WORKED fine

https://user-images.githubusercontent.com/66258652/135896075-4097dedb-1848-4aa6-bb9e-b65fcd5cf392.mp4

my conclusion some node packages might causing the Emmet to delay or slow down

**Comment by ullaskunder3** [comment]
Sir @mjbvz @rzhao271  Some node packages might causing the TS & JS language feature extension to delay or slow down
- I tried installing each node package at a time and test the extension... 
- I saw there's a problem while using mongoose. 


https://user-images.githubusercontent.com/66258652/136050072-50b34b34-fa72-45f4-8f3f-6af85ae3d049.mp4

**Comment by ullaskunder3** [comment]
"emmet.showSuggestionsAsSnippets": true,
  "emmet.triggerExpansionOnTab": true,
  "workbench.settings.enableNaturalLanguageSearch": false,
 "vsintellicode.typescript.completionsEnabled": true,

"workbench.enableExperiments": false,

It worked...

**Comment by ullaskunder3** [comment]
"emmet.showSuggestionsAsSnippets": true,
"emmet.triggerExpansionOnTab": true,
"workbench.settings.enableNaturalLanguageSearch": false,
"vsintellicode.typescript.completionsEnabled": true,
"workbench.enableExperiments": false,

  "javascript.suggest.enabled": false,

It worked...

**Comment by mjbvz** [comment]
Again, we need a project that demonstrates the issue to investigate this

**Comment by mjbvz** [comment]
Please share the project code, such as a GitHub repo I can clone

It is not a good use of my time to fiddle around setting up a project in order to reproduce a rather vague issue like this

**Comment by ullaskunder3** [comment]
@mjbvz my bad...
The project link git repo https://github.com/ullaskunder3/nodejs-http-route

*I included the setting.json file as well named as vsSettings.json

**Comment by ullaskunder3** [comment]
@mjbvz sir finally done its working...
I reinstalled everything node, git and vs code and set it to it's default settings...

*I think earlier I messed up vs code settings.json or may be in nodejs
