### ISSUE TITLE
Code cannot launch on Fedora due to missing libXss dep

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#13439]
/cc @chrmarti

**Comment by Tyriar** [comment]
Pushed and cherry picked to `release/1.6` branch

**Comment by MrSparc** [comment]
openSUSE fails to resolving the package dependency "libXScrnSaver" because the bin package is called "libXss1" (for more info see https://bugzilla.suse.com/show_bug.cgi?id=967340)

```
 $ sudo zypper install ./code-1.6.0-1476123947.el7.x86_64.rpm                                              
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libXScrnSaver needed by code-1.6.0-1476123947.el7.x86_64
 Solution 1: do not install code-1.6.0-1476123947.el7.x86_64
 Solution 2: break code-1.6.0-1476123947.el7.x86_64 by ignoring some of its dependencies

```

**Comment by Tyriar** [comment]
@MrSparc thanks for the report, do you think something like this will work in the rpm?

```
Requires: glibc >= 2.15, libXScrnSaver or libXss1
```

**Comment by MrSparc** [comment]
@Tyriar I don't know much about rpm specs but googling (or binging) looks like the use of Boolean dependency feature is supported as of RPM 4.13 http://www.rpm.org/wiki/PackagerDocs/BooleanDependencies

Boolean expressions are not supported in previous RPM versions:  http://serverfault.com/questions/299179/can-one-require-this-or-that-package-in-an-rpm-spec-file

**Comment by romu70** [comment]
Same issue with Fedora 25. Problem is the libXss.so.1 library is not installed by the libXScrnSaver package.

**Comment by Tyriar** [comment]
@romu70 this should have been fixed by the https://github.com/Microsoft/vscode/pull/15128 PR, coming to the stable build soon. In the meantime you can just ignore the warning.

**Comment by romu70** [comment]
It doesn't work this way. Indeed F25 refuses to install the rpm because of this missing library. Indeed, the library is present on the system, but on 64 bit computer, it is in /usr/lib64, not in /usr/lib. I just created a symbolic link in /usr/lib and it works. Don't know who is to blame though, libXScrSaver, Fedora ou VSC?

**Comment by Tyriar** [comment]
After the PR it now points based on the bitness of the package, which I believe fixes the issue. See https://github.com/Microsoft/vscode/pull/15128/files#diff-188db2ba2b1e47c34c14a1ab98ea76e4R13

**Comment by romu70** [comment]
do you know when it'll be released? I'll do some testing.

**Comment by Tyriar** [comment]
You can see the plan here https://github.com/Microsoft/vscode/issues/15099
