### ISSUE TITLE
Need to be able to run a script from watch window

### ISSUE THREAD

**Issue by Ma-XX-oN** [microsoft/vscode#134355]
Allowing calling gdb script functions to modify view in watch window.  Maybe extending the current pretty-print functionality, something like:
```python
class StdVectorIteratorPrinter(object):
    "Print a std::vector::iteraotr"

    def __init__(self, val):
        self.val = val

    def to_string(self, *args):
        return extended(*args) or self.val['_M_current']

    def display_hint(self):
        return 'string'
        
    def extended(name, *args):
        if len(args) == 0
            return
        if name == "range":
            return "{"+','.join([str(elem) for args])+"}"
            
    # something similar could be done with children.
```

and then in watch type, use a modifer:
```
a, range(b)
```

**Comment by roblourens** [comment]
Watches can take any expression, so you can call whatever functions you want. I think that is what you are asking for? If I am not understanding correctly, could you explain some more?

**Comment by roblourens** [comment]
I see. This needs to be filed on the repo for the C++ debug extension
