### ISSUE TITLE
Sort test files after the files they test

### ISSUE THREAD

**Issue by mpvosseller** [microsoft/vscode#134382]
In the file explorer sort test files _after_ the files they test.

VS Code sorts files alphabetically but I think it would be a nice improvement to always sort test files _after_ the files they test. I think this is a more natural and intuitive ordering.

This happens to work when using JavaScript because `.test.js` alphabetically sorts _after_ `.js` 
Unfortunately it does not work in TypeScript because `.test.ts`  alphabetically sorts _before_ `.ts`

The below screenshot shows an example of this. I think it would be an improvement if `user.test.ts` was listed after `user.ts` and if `post.test.ts` was listed after `post.ts`.

It is worth noting that this may be tricky because of other possible file naming conventions. For example some projects may use a naming scheme to differentiate between unit and integration tests:
- `user.ts`
- `user.unit.test.ts`
- `user.int.test.ts`

<img width="917" alt="Screen Shot 2021-10-04 at 8 33 46 AM" src="https://user-images.githubusercontent.com/566863/135859840-ab0fbcab-2ae7-42e8-beb1-6d1d16d913d6.png">

**Comment by connor4312** [comment]
This is a request for the file explorer

**Comment by JacksonKearl** [comment]
#27286 captures the many different sorts requested for explorer/open editors. This is a pretty specific request (there are potentially many different "test file" naming conventions, it would be impossible to capture them all), so I don't really see it happening absent the introduction of an extension point to contribute custom sorting, which poses a technical challenge (sorting is typically assumed to be sync, but communication with the extension host is async). I will close this in favor of #27286.
