### ISSUE TITLE
Allow for setting a editor background image

### ISSUE THREAD

**Issue by v3ss0n** [microsoft/vscode#134317]
Currently we need hacks and workarounds just to make a simple feature work : Setting Background Images.

This is what i could do 7 years ago in ATOM editor : Could add background with translucency and CSS text effect.
https://github.com/v3ss0n/steam-pirate-ui
![image](https://user-images.githubusercontent.com/419606/135713300-2ee9f742-03b5-43ca-a789-00442be146a6.png)

I understand that enabling full CSS features could be performance problem , so what i am requesting is only following features.
- A Proper API to set Background
- Optional Translucency/Tinting support
- Optional Blurring support

It was requested here : https://github.com/microsoft/vscode/issues/84120
but shot down  : https://github.com/microsoft/vscode/issues/84120#issuecomment-551072767
> How does that increase productivity? I find it unlikely that we would allow this, but maybe there is a good argument to do it.

This is not just for "Looking Good' as  It have a lot of productivity use cases and could make a lot of useful extensions that:

- Cheatsheets as Background Images , changes depending on programming languge/framework 
- Charts / Graphs / {Stock,Crypto} Prices / Process Monitors  Dynamically updated at the back ground.
- Motivational / Quotes chaning every set hours.
  
This is some of very few usecases that is not just for looks but

**Comment by darren4321** [comment]
+1 this request - adjustable transparency and blur
