### ISSUE TITLE
Find in files should search only files on disk

### ISSUE THREAD

**Issue by Jasper-Bekkers** [microsoft/vscode#134306]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.60.2 (user setup)
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:00:31.514Z (1 wk ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Switch branches quite a bit on the commandline in git, do replacements in files / changes to files
2. Use find in files feature in vscode

It appears that vscode will use it's stale in-memory representation of some of the previously edited files (left open) when searching, rather then looking at the files on disk. This often leads to incorrect search results; for example when searching for ">>>>>" to find all outstanding merges they often won't show up because vscode seems to keep a in-memory cache of the files I've previously touched leading to incorrect merges or missed files.

**Comment by roblourens** [comment]
If you have the file open in an editor, we will search in the editor. Are you saying that the contents of the editor don't update when switching branches?

**Comment by Jasper-Bekkers** [comment]
I'm saying I wouldn't want the contents of the editors searched at all - my expectation is that the search results mirror the on-disk content exactly.

**Comment by Jasper-Bekkers** [comment]
"By design" has led me to may faulty merges and an incomplete view of the code base that's on my filesystem.

Is there at least a setting to get sane behavior here?

**Comment by Jasper-Bekkers** [comment]
@roblourens I respectfully disagree - It's caused my quite a few headaches to be honest given that this design (ever since it's behavior changed) already led to quite a few bad merges. Having to remember to close all the windows also feels like a bit of a workaround, would an alternative design where the Find in Files dialog show these discrepancies be an option otherwise?

**Comment by Jasper-Bekkers** [comment]
Something about this is very broken:

If I look for `>>>>>` with a folder open (and as instructed, all tabs closed):
![image](https://user-images.githubusercontent.com/49594/139962944-f6f48e50-cb4f-4730-8fc0-4342db170415.png)

However, if I manually open the file and then search for the same string:
![image](https://user-images.githubusercontent.com/49594/139963054-ba4726b0-24b1-4333-bcef-8f1876780e60.png)

**Comment by roblourens** [comment]
Can you find other strings in that file? Is it possible that the file is excluded by a setting or .gitignore file? Excluded files are still searched when they are open

**Comment by MarijnS95** [comment]
![image](https://user-images.githubusercontent.com/2325264/140034471-4f1fc389-67d7-45bf-aef8-0ba7d3d04a93.png)

From the screenshot I can tell that you have the "Search only in Open Editors" (book button on the right) enabled :grimacing:

**Comment by Jasper-Bekkers** [comment]
> From the screenshot I can tell that you have the "Search only in Open Editors" (book button on the right) enabled 😬

... My kingdom for a button that does "Search only in Filesystem" instead, oh boy. Looks like a user error this time at least, I didn't even know this was possible, very confusing.

**Comment by roblourens** [comment]
Good eye @MarijnS95, thank you
