### ISSUE TITLE
Add setting to disable all default keybindings

### ISSUE THREAD

**Issue by github-account1111** [microsoft/vscode#134332]
Often times I will press some key or key combination by accident, and it will do something, and, if it's apparent what it did, I would revert it, and, if it's not, I will have to dig for a bit trying to undo the damage.

That's a bit frustrating having to worry about this constantly, especially considering how many default keybindings there are in VSCode. Given I will never use 90% of them, I wanted to just remove every single keybinding, then add them back one-by-one as the need arises. I expect in a week's time, I will have figured out all the bindings I need.

This would be super easy to accomplish if the keybinding JSON listed every single binding and action. However, the way it works currently is one has to *negate* default keybindings to remove them. Not only is it a bit counterintuitive (at least to me), it also makes what I want to accomplish incredibly cumbersome.

Maybe change it to the way, say, mpv do it with a file that lists every single binding and let the user do whatever they want with it. That would simplify things quite a bit.

**Comment by canelhasmateus** [comment]
Please, this so much. 
My current keybinds file is nearing 5k lines, and out of 978 "command" entries, 753 of them are just negations. My old configurations spanned more than 30k lines, before being foced to revert to factory. Since them i'm being very cautious about installing extensions and un-mapping defaults.
Take this with a bit of salt, since this one issue hits me *so* deeply, but the currently state of keybinds is ridiculous and absolutely impossible to improve and maintain.

**Comment by NotWearingPants** [comment]
@canelhasmateus If you're contributing for the first time, follow [this guide](https://github.com/microsoft/vscode/wiki/How-to-Contribute) to create a local development environment where you can make changes and rebuild VSCode to test it.

The first step to fix this is to find where the keybindings are parsed, especially the minus syntax. Try searching for key words like `keybindings.json`, or maybe try adding a breakpoint on a command that you know where to find, triggering it with a keybinding, and looking at the call stack to see where the keybinding was mapped to the command.

btw I don't think this needs any real globbing, just special-casing `if (command === "-*")` to remove all keybindings.

**Comment by github-account1111** [comment]
Followup question regarding nooping everything before reenabling the commands individually: does it negatively affect performance?
