### ISSUE TITLE
Linux: vscode 1.60.* crashes on start on linux systems with nvidia driver

### ISSUE THREAD

**Issue by lemmy04** [microsoft/vscode#134368]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: code-1.60.2-1632313693.el7.x86_64
- OS Version: openSUSE Tumbleweed 20210929

Steps to Reproduce:

1. install nvidia drivers
2. install VScode
3. try to start VScode
4. see it crash

VScode --verbose log is here:
https://paste.opensuse.org/70239110

code-insiders 1.61 works fine.
code-1.60.2 from the same rpm works on my laptop when I use the intel card, crashes when I use the nvidia card through gamemoderun.

**Comment by lemmy04** [comment]
> /duplicate #133593

I'm not sure about that at all.

As I said, on my tumbleweed laptop it works fine when I use the intel card, and only crashes when I use the nvidia card.
also, running it with sandboxing disabled (--no-sandbox) does not make it work either, with --no-sandbox and the nvidia driver i get an empty black window instead of a crash.

**Comment by deepak1556** [comment]
Can you provide the version of glibc on your system.

The exit code of the gpu process in your log matches the sandbox crash observed in the other issue and also you have mentioned that the insiders version works fine. The insiders version carries the fix mentioned in the other issue. It will be available in `1.61` stable release this week.

**Comment by lemmy04** [comment]
mathias@mio:~> rpm -q glibc
**glibc-2.34-1.2.x86_64**

mathias@mio:~> ssh root@kumiko rpm -q glibc
**glibc-2.34-1.2.x86_64**

**Comment by deepak1556** [comment]
Thanks it does confirm the root issue linked in https://github.com/microsoft/vscode/issues/133593
