### ISSUE TITLE
Please give us more visual control over the Explorer (root folder presentation, font size, indent of the first item, and line height).

### ISSUE THREAD

**Issue by AndrewHawes** [microsoft/vscode#134472]
There have been several feature requests here for adjustments to the Explorer. Most of them seem to have been closed and dismissed (aside from workbench.tree.indent, which has provided an immense improvement).

I switched to VS Code from PyCharm, and though there are a few features I miss, I've generally been very happy with VS Code.

But I opened PyCharm the other day and immediately noticed how much more comfortable I was with the Explorer window. I worked with it for a couple days (after reassigning keyboard shortcuts to be more similar to VS Code), and though I still prefer VS Code, the PyCharm explorer was much more comfortable. I'm honestly not completely sure why this is. But there are several things I noticed that seemed to be important:

1) The root directory is selectable and can be interacted with as if it were any other folder in the project.
2) The font size is smaller.
3) The line height is greater than it is in the editor. (I think this might be important, as it makes the window appear to be less cluttered.)
4) There's a little bit less horizontal space between the expansion arrow icon and the folder icon. (I think this might be less impactful than I think it is. I read another issue about the alignment of the arrows, and I might be unconsciously attributing importance to this because I read that issue.)

Again, I'm not sure why the PyCharm explorer is so much easier to work with than the explorer in VS Code. I think that issues 1-3 would address this. (4 might be important, too. I don't know.)

I understand why you might think this is unimportant. When you're working on anything, it's easy to get used to the patterns you're familiar with. Every user has a different subjective experience of the interface and the layout, and like the designers, we all get used to what we're accustomed to working with, and we might not recognize there's anything that could use improvement until we experience something that's different.

Anyway, I think the user experience could be vastly improved by giving us a little more control over the visual presentation of the Explorer.

**Comment by JacksonKearl** [comment]
> The root directory is selectable and can be interacted with as if it were any other folder in the project.

We support this in workspaces, see:
![image](https://user-images.githubusercontent.com/8586769/136328757-e05f1bcc-9c58-4ada-a224-b815d4c4cf95.png)

2 and 3 are fair feature requests.
