### ISSUE TITLE
Markdown cells jump up and down

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#134445]
* download and follow the notebook of this sample https://www.tensorflow.org/tutorials/images/classification#predict_on_new_data
* run all cells
* open another notebook to the side
* move slider
* 🐛 markdown headers move up and down

https://user-images.githubusercontent.com/1794099/136049921-6534d6bd-1b3e-4569-94d0-1c46ec7122fe.mov

**Comment by roblourens** [comment]
Remind me which optimization that is. One of the things you have worked on recently?

**Comment by rebornix** [comment]
This issue was fixed via the scroll top optimization for the webview.
