### ISSUE TITLE
Notebook intellisense showing different highlight colors

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#134403]
This reproduces also on 1.60 so it looks like this has been broken for a while.

1. Set theme to default light theme
2. Start typing in code cell
3. :bug: See the the highlight color for non-selected items are the wrong

<img width="350" src="https://user-images.githubusercontent.com/35271042/135922231-8d037e74-3d93-4718-9b7e-0ed3e77e14c6.png">

and compare it to a regular file:

<img width="220" alt="CleanShot 2021-10-04 at 13 43 38@2x" src="https://user-images.githubusercontent.com/35271042/135922189-3b617a3c-5230-40f7-938b-e07d2c9a7472.png">

**Comment by roblourens** [comment]
FYI @jrieken I just tweaked the suggest widget styles here
