### ISSUE TITLE
Incorect regexp highlight in TS file

### ISSUE THREAD

**Issue by aleksey-pastuhov** [Microsoft/vscode#13449]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. create TS file with content
```typescript
         /^created file "([^"]*)" with content "([^"]*)"$/,
```
2. choose DARK+ highlight.. it is awkward..

![image](https://cloud.githubusercontent.com/assets/11784219/19252229/639d9690-8f4c-11e6-8adf-6606a9f6f712.png)

**Comment by waderyan** [comment]
@aleksey-pastuhov thank you for opening this issue. Can you try this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) to see if it solves your problem? Its in beta right now and is a candidate to pull into the product.

**Comment by aleksey-pastuhov** [comment]
I've already install it. And it is ok without that plugin. Thanks for solving my issue 👍 

![image](https://cloud.githubusercontent.com/assets/11784219/19283736/abf19fa4-8ffb-11e6-87f7-0bf54205bc5b.png)

![image](https://cloud.githubusercontent.com/assets/11784219/19283777/df0a9c7e-8ffb-11e6-8ca3-7397c5ffd7ba.png)
