### ISSUE TITLE
Interactive window lost when switching workspaces

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#134468]
Issue Type: <b>Bug</b>

1. Create an Jupyter interactive window
2. Write stuff in it
3. Switch the current window to a different workspaces
4. Then switch back to the original workspace

**Bug**
The interactive window is not restored, so the interactive window content's are lost. This is frustrating if you've done a lot of work in it

VS Code version: Code - Insiders 1.61.0-insider (Universal) (71ca6e8e74591ae5c577d52a2aa1bd0c3df5ac32, 2021-10-05T01:23:40.704Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|32.00GB (2.53GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
salesforce-soql-editor|all|1.8.0
comment-tagged-templates|bie|0.3.1
docs-view|bie|0.0.9
emojisense|bie|0.9.0
folder-source-actions|bie|0.2.1
jsdoc-markdown-highlighting|bie|0.0.1
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-yaml-preamble|bie|0.1.0
test-ext|bie|0.0.1
vscode-eslint|dba|2.1.25
typescript-notebook|don|2.0.3
gitlens|eam|11.6.0
tsl-problem-matcher|eam|0.4.0
EditorConfig|Edi|0.16.4
codespaces|Git|1.1.0
remotehub|Git|0.14.0
vscode-pull-request-github-insiders|Git|2021.10.6309
vscode-drawio|hed|1.6.2
vscode-postfix-ts|ipa|1.9.4
latex-workshop|Jam|8.20.2
vscode-platform-specific-sample|joa|1.15.0
vscode-platform-specific-sample|joa|1.5.0
vscode-memfs|jri|0.0.3
template-string-converter|meg|0.5.3
vscode-azurefunctions|ms-|1.5.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.17.0
vscode-language-pack-de|MS-|1.61.1
vscode-edge-devtools|ms-|1.3.1
python|ms-|2021.10.1288721932-dev
vscode-pylance|ms-|2021.9.5-pre.1
jupyter|ms-|2021.9.1001294413
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.201.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
azure-account|ms-|0.9.9
hexeditor|ms-|1.8.2
js-debug-nightly|ms-|2021.9.2817
live-server|ms-|0.2.9
vscode-github-issue-notebooks|ms-|0.0.108
vscode-typescript-next|ms-|4.5.20211004
vsliveshare|ms-|1.0.4962
debugger-for-chrome|msj|4.13.0
vetur|oct|0.34.1
code-spell-checker|str|2.0.8
rest-book|tan|4.2.0
ayu|tea|1.0.5
luna-paint|Tyr|0.9.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.14

(2 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
It can be restored now by turning on `interactiveWindow.restore`
