### ISSUE TITLE
Changing lineNumbers config through API doesn't work

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#13446]
- VSCode Version: 1.6.0
- OS Version: OSX

Steps to Reproduce:

1. Set `editor.lineNumbers` as `on`
2. Change this option by running`vscode.workspace.getConfiguration("editor").update("lineNumbers", "off", true);`
3. The line numbers become relative ones immediately but once you move the cursor, it becomes absolute ones again.
4. Check `settings.json`, the configuration value is already `relative`.

![linenumbers](https://cloud.githubusercontent.com/assets/876920/19250528/9ab77ba8-8eef-11e6-9dcb-36140fa85296.gif)

**Comment by aeschli** [comment]
Not sure how 'relative' is related here. I tried it with sample code based on our [hello world extension sample](https://code.visualstudio.com/docs/extensions/example-hello-world) and everything looks fine for me. The settings are modified correctly, and are not reverted on moving the cursor.
```
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    let values =  [ "off", "on"];
    let i = 0;
    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        vscode.workspace.getConfiguration("editor").update("lineNumbers", values[i], true);
        i = (i + 1) % values.length;
    });

    context.subscriptions.push(disposable);
}

export function deactivate() {
}
```

**Comment by aeschli** [comment]
Closing. Please reopen with a code that demonstrates the issue.
