### ISSUE TITLE
Zlib error: invalid distance too far back

### ISSUE THREAD

**Issue by kkat-zero** [microsoft/vscode#134429]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.60.2
- OS Version:Windows_NT x64 10.0.19042

This is a problem that occurs when connecting the target OS to Linux from the Windows host OS using Remote Development.
If you check the logs, the extension host will start when you make a remote connection.
However, the extension host exits immediately.
"Extension Host Process exited with code: 1, signal: null." Is displayed on the log.

I guess the extended host function is timing out because the processing speed of the target OS is slow.
I set "Remote-SSH: Connect Timeout" to 500 seconds to solve this problem, but the problem still persists.

Are there any other measures?

```
[2021-10-05 17:57:11.242] [remoteagent] [info] Extension host agent started.
[2021-10-05 17:57:16.696] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
[2021-10-05 17:57:16.995] [remoteagent] [info] [<unknown>][fae5c6c7][ManagementConnection] New connection established.
[2021-10-05 17:57:17.184] [remoteagent] [info] [<unknown>][6346e60b][ExtensionHostConnection] New connection established.
[2021-10-05 17:57:17.364] [remoteagent] [info] [<unknown>][6346e60b][ExtensionHostConnection] <6182> Launched Extension Host Process.
[2021-10-05 17:57:22.028] [remoteagent] [error] No ptyHost heartbeat after 12 seconds
[2021-10-05 17:57:29.762] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
[2021-10-05 17:57:36.051] [remoteagent] [info] [<unknown>][6346e60b][ExtensionHostConnection] <6182> Extension Host Process exited with code: 1, signal: null.
[2021-10-05 17:57:36.072] [remoteagent] [info] Last EH closed, waiting before shutting down
[2021-10-05 17:57:36.686] [remoteagent] [error] [<unknown>][6346e60b][ExtensionHostConnection] Unknown reconnection token.
[2021-10-05 17:57:37.094] [remoteagent] [info] [<unknown>][fae5c6c7][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
```

**Comment by kkat-zero** [comment]
@alexdima We will inform you of additional information.

A) In rare cases, this phenomenon can be connected without error. (When retrying many times)
However, even after the connection is established, the remote connection is often disconnected on the way.

B) This embedded device has a very small internal RAM of 256MB.
Therefore, the memory capacity is increased by setting the virtual memory.
The additional RAM capacity setting is 512MB.
The additional memory is set to the built-in flash ROM (eMMC).
Therefore, the total RAM of the system is 768MB.

When VS Code makes a remote connection, I'm checking that a memory swap is occurring because the internal RAM alone isn't enough.

When I checked the memory used when the startup was successful, it was confirmed that a total of about 300MB of RAM was used.

**Comment by kkat-zero** [comment]
@alexdima Thank you for the quick response.
It is very difficult to build the same environment.
This is because there is generally no embedded linux VM environment.
(Usually, the test is performed on the actual machine)

However, I think it is possible to create an environment that combines only the limited memory environment with a VM.

First, build a virtual environment to install Debian OS on VMWare.
At this time, set the internal RAM memory to be mounted as small as 256MB. (Set an appropriate size for the built-in ROM, about 8 to 16GB)

Once the virtual environment can be built, set the virtual memory under that environment.
In our environment, 512MB is set as virtual memory.

There are two points of concern.

One thing to worry about is whether it is possible to install a general Debian OS on a PC with limited RAM.
If you cannot install it, you need to adjust the RAM size to an appropriate size as much as possible.
(It is necessary to build a state in which the internal RAM usage after OS installation is moderately overused.)

Second, when using a VM environment, there is a high possibility that the CPU processing speed and memory access speed will be faster than the actual machine.
Even if you set the virtual memory in the VM environment, the same problem may not occur if the problem is caused by the processing speed.
(If the problem depends on the virtual memory mechanism, it may be reproduced.)

For reference, the following sites are shown.

[How to build VMware]
https://kb.vmware.com/s/article/1018415

[Virtual memory setting method]
https://www.techwalla.com/articles/how-to-increase-virtual-memory-in-linux

**Comment by aeschli** [comment]
@alexdima Is this something we can verify? Do you have a simple setup with steps?

**Comment by alexdima** [comment]
Unfortunately I was only able to reproduce by making changes to the source code (e.g. to add artificial delays to the extension host startup path).

**Comment by kkat-zero** [comment]
@alexdima Thank you for corresponding to solve this issue.
I did the same test with Ver1.63.0-insider.
As a result, it was confirmed that it operates stably.
This issue can be closed.

Thank you.
