### ISSUE TITLE
Webviews are broken, they display a blank window instaed of their content

### ISSUE THREAD

**Issue by stefanobartoletti** [microsoft/vscode#134451]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.2 (and previous versions)
- OS Version: openSUSE Tumbleweed Linux (vscode was installed from the main repo from microsoft)

Webviews aren't working and display a blank window instead of their content.
![Screenshot_20211005_185336](https://user-images.githubusercontent.com/36746429/136069032-6dae553a-0dbb-48ca-97a3-47781cc195c8.png)
![Screenshot_20211005_185357](https://user-images.githubusercontent.com/36746429/136069073-876584b8-2f3a-4086-802b-3f377b5df08a.png)
![Screenshot_20211005_185427](https://user-images.githubusercontent.com/36746429/136069103-e03e91fe-b57e-47d9-996c-96c3749f152d.png)

I've tried to uninstall and reinstall it, to start it with disabled extensions, to start from scratch with a completely new configuration folder, but the problem still remains.

I've also tried to downgrade to a previous version, I've tested until 1.59, and it still happens. This problem started all of a sudden.

**Comment by mjbvz** [comment]
How specifically did you install VS Code? With the snap package?

**Comment by stefanobartoletti** [comment]
No, I installed it with from the Microsoft repository for openSUSE, as described here https://code.visualstudio.com/docs/setup/linux#_opensuse-and-slebased-distributions

**Comment by stefanobartoletti** [comment]
Thank you. 
I've tried this, but selecting `Developer: Toggle developer tools` does nothing. I don't know it it's related to the previous problem.

**Comment by stefanobartoletti** [comment]
Here it is 
[trace.txt](https://github.com/microsoft/vscode/files/7300025/trace.txt)

**Comment by deepak1556** [comment]
Thanks for the logs, they look good. Are you starting the application as sudo user ? Can you try starting with `code --no-sandbox` and see if devtools open ?

**Comment by electricfungi** [comment]
I can verify this issue with md files. have any md file open and select preview, and get "Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.."

**Comment by deepak1556** [comment]
@stefanobartoletti can you also confirm if `1.61` fixes the issue for you ?

**Comment by stefanobartoletti** [comment]
Yes, I've just updated it, it now works perfectly!

Thank you for your support!
