### ISSUE TITLE
Github.dev crashing both on safari and chrome while trying to use iPad without connected keyboard

### ISSUE THREAD

**Issue by RuzgarEken** [microsoft/vscode#134494]
I want to edit my scripts with ipad screen keyboard but i can not use github.dev it keeps saying “setting up your editor” for several times and crashing after that. This is same for chrome and safari.

**Comment by lszomoru** [comment]
@isidorn, any idea who should look into this? Thanks!

**Comment by isidorn** [comment]
@RuzgarEken I will have to close this since we can not reproduce this.
If you can reproduce still can you please attach a video showing the crash. Then we can reopen this and forward to the owners. Thank you
