### ISSUE TITLE
import Visual Studio theme into Visual Studio Code

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/vscode#13444]
I have defined my own theme for Visual Studio and I'd like to have an option to import it into Visual Studio Code.

I think many Visual Studio users would be happy if they could import / sync the theme to Visual Studio Code.

**Comment by mjbvz** [comment]
Closing as out of scope of core VS Code. This could be implemented as a script. See the vscode-theme-generator for example: https://github.com/Tyriar/vscode-theme-generator
