### ISSUE TITLE
Multiline interactive window inputs get collapsed if you switch to another editor

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#134457]
Issue Type: <b>Bug</b>

1. Open Jupyter interactive window
1. Type a multiline expression in the run box
1. Before running it, switch to another tab in the same group
1. Now switch back to the interactive window

**bug**
The run box has collapsed back down to a single line with a scrollbar:

<img width="339" alt="Screen Shot 2021-10-05 at 10 36 10 AM" src="https://user-images.githubusercontent.com/12821956/136074277-96028fcf-74b8-45c3-b657-8b28fb8ba446.png">

VS Code version: Code - Insiders 1.61.0-insider (Universal) (71ca6e8e74591ae5c577d52a2aa1bd0c3df5ac32, 2021-10-05T01:23:40.704Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (3.05GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
salesforce-soql-editor|all|1.8.0
comment-tagged-templates|bie|0.3.1
docs-view|bie|0.0.9
emojisense|bie|0.9.0
folder-source-actions|bie|0.2.1
jsdoc-markdown-highlighting|bie|0.0.1
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-yaml-preamble|bie|0.1.0
test-ext|bie|0.0.1
vscode-eslint|dba|2.1.25
typescript-notebook|don|2.0.3
gitlens|eam|11.6.0
tsl-problem-matcher|eam|0.4.0
EditorConfig|Edi|0.16.4
codespaces|Git|1.1.0
remotehub|Git|0.14.0
vscode-pull-request-github-insiders|Git|2021.10.6309
vscode-drawio|hed|1.6.2
vscode-postfix-ts|ipa|1.9.4
latex-workshop|Jam|8.20.2
vscode-platform-specific-sample|joa|1.15.0
vscode-platform-specific-sample|joa|1.5.0
vscode-memfs|jri|0.0.3
template-string-converter|meg|0.5.3
vscode-azurefunctions|ms-|1.5.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.17.0
vscode-language-pack-de|MS-|1.61.1
vscode-edge-devtools|ms-|1.3.1
python|ms-|2021.10.1288721932-dev
vscode-pylance|ms-|2021.9.5-pre.1
jupyter|ms-|2021.9.1001294413
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.201.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
azure-account|ms-|0.9.9
hexeditor|ms-|1.8.2
js-debug-nightly|ms-|2021.9.2817
live-server|ms-|0.2.9
vscode-github-issue-notebooks|ms-|0.0.108
vscode-typescript-next|ms-|4.5.20211004
vsliveshare|ms-|1.0.4836
debugger-for-chrome|msj|4.13.0
vetur|oct|0.34.1
code-spell-checker|str|2.0.8
rest-book|tan|4.2.0
ayu|tea|1.0.5
luna-paint|Tyr|0.9.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.14

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30364496
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsqsis300:30374797
vsaa593cf:30376535

```

</details>

**Comment by greazer** [comment]
Not reproing this anymore
