### ISSUE TITLE
Incorrect coloring of HTML elements containing hyphens

### ISSUE THREAD

**Issue by jkaldenbach** [Microsoft/vscode#13448]
- VSCode Version: 1.6.0
- OS Version: Mac OSX 10.11.5

This just showed up after I updated to 1.6.0.

Steps to Reproduce:

1. Add an html element that includes a hyphen (-)
2. Everything after the first hyphen is colored like an attribute

![untitled-1 - preclose-ionic 2016-10-10 17-20-41](https://cloud.githubusercontent.com/assets/8710635/19251653/681209ec-8f0e-11e6-836f-dec2c80636b1.png)

**Comment by isidorn** [comment]
Two users reported this in less than 12 hours - adding important to raise awarness

**Comment by DethAriel** [comment]
Same for OS Version: Windows_NT ia32 10.0.14393

**Comment by infinnie** [comment]
@isidorn Now three.

**Comment by jbw91** [comment]
Can confirm same for me on macOS Sierra 10.12

<img width="559" alt="screen shot 2016-10-11 at 8 46 15 pm" src="https://cloud.githubusercontent.com/assets/5883616/19295738/e3bf01b8-8ff3-11e6-87b5-ea10ce14c8b2.png">

**Comment by pufanalexandru** [comment]
Same for OS Version: Windows_NT ia32 6.1.7601

**Comment by aeschli** [comment]
Original issue: https://github.com/textmate/html.tmbundle/issues/46

**Comment by rictic** [comment]
Related upstream PR: https://github.com/textmate/html.tmbundle/pull/47
