### ISSUE TITLE
Non-existent debugger configuration

### ISSUE THREAD

**Issue by TriStarGod** [microsoft/vscode#134466]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.2 (user setup)
- OS Version: Windows 10 Pro x64

Steps to Reproduce:

1. Click on Debug symbol
2. Click "Run and Debug" drop down
![image](https://user-images.githubusercontent.com/8272754/136101284-7989e7d3-3c1b-4258-9ba8-bf83e1427079.png)

Yet my configuration only has
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${file}"
    }
  ]
}
```

Every project has a mysterious "Run Script: dev"

It is very similar to issue #121148 .
I tried
1. Deleting and recreating launch.json
2. Examined my user settings
3. Deleting everything under C:\Users\<userid>\AppData\Roaming\Code\Local Storage

**Comment by TriStarGod** [comment]
I tried testing it on my fastify instance with the assumption its trying to npm dev. I keep getting an error "Could not read source map for internal...." and then nodemon logs (clean exit - waiting for changes before restart). I already have a debug script that works but this option keeps popping up everywhere.

**Comment by connor4312** [comment]
Yes, this is a dynamic launch config which js-debug contributes to debug an npm script. I'm not sure why it would appear on _every_ project, from testing and a reading of the source it should only appear when it's been used in a workspace (everything debug stores is `StorageScope.WORKSPACE`).

Maybe there should be a way to clear dynamic configs, however. Perhaps a 🗑️ icon in the debug quick access/quickpick?
