### ISSUE TITLE
Missing layout call in terminal

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#134460]
Notice the gap to the right of the scrollbar:

![image](https://user-images.githubusercontent.com/22350/136080654-617d1510-096b-4cc4-870b-404de9c981a8.png)

Resizing the workbench called layout and fixed it. I can't repro unfortunately, sorry.

**Comment by joaomoreno** [comment]
Actually, there's an extra pixel, even after a proper layout. Seems to be a separate issue.

![image](https://user-images.githubusercontent.com/22350/136080871-7c6480a5-ea5a-478f-83d5-65f225d7768c.png)

**Comment by Tyriar** [comment]
The vertical gap is intentional, the scroll bar is provided by xterm.js and we add some padding to the bottom within VS Code to ensure underscores are easily visible.

**Comment by joaomoreno** [comment]
Could that padding be on the content only, the same way the Explorer has one row of padding at the bottom, yet its scrollbar aligns completely?
