### ISSUE TITLE
Selecting a kernel from the marketplace does not show other notebooks

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#134406]
<img width="815" alt="CleanShot 2021-10-04 at 15 05 45@2x" src="https://user-images.githubusercontent.com/35271042/135931179-6e100319-21aa-4567-ad9b-ff4485ab5586.png">

Originally filed in https://github.com/microsoft/vscode/issues/129652. 

When opening a .NET notebook for the first time and selecting a kernel, you are always shown the Jupyter extension and there is no clear guidance about needing the .NET Interactive Notebook. It would be great if VS Code could detect the various languages used in a notebook and then show a list of relevant notebooks.

@ 00:05 is where I select a kernel

https://user-images.githubusercontent.com/35271042/135929628-21320177-a40a-4350-9976-9e121aebc7a3.mp4

**Comment by roblourens** [comment]
If you run a cell from a .ipynb polyglot notebook and don't have any notebook extensions installed, then you get a prompt to search `@tag:notebookKernelJupyterNotebook` in the marketplace. That just finds the Jupyter extensions. Should the Polyglot extension also have that tag @rebornix?

**Comment by DonJayamanne** [comment]
@roblourens Are these tags documented?

**Comment by roblourens** [comment]
Not that I know, @rebornix?

**Comment by joyceerhl** [comment]
@DonJayamanne they are documented here: https://code.visualstudio.com/api/extension-guides/notebook#controller

**Comment by roblourens** [comment]
I think that doc should say _why_ you should do that

**Comment by DonJayamanne** [comment]
Updated the docs https://github.com/microsoft/vscode-docs/commit/244fd9c421faa6c3821001dfe46a016a56703ef0
