### ISSUE TITLE
Loses text when maximizing the integrated terminal

### ISSUE THREAD

**Issue by manhuyhong** [microsoft/vscode#134448]
Issue Type: <b>Bug</b>

When I maximize the terminal, only visible text at the bottom of the original size terminal remains. All the text above (which I can see if I scroll up) disappears and they won't come back even if I minimize the terminal back.

https://user-images.githubusercontent.com/83082904/136067623-ad40c8fc-3c0e-4813-a1f3-90b63cbc52dc.mp4

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.78GB (2.42GB free)|
|Process Argv|--crash-reporter-id 9b16d291-2aed-420a-aeff-d4f481c88df8|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
vscode-markdownlint|Dav|0.44.4
vscode-eslint|dba|2.1.25
es7-react-js-snippets|dsz|3.1.1
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.0
auto-close-tag|for|0.5.12
code-runner|for|0.11.5
beautify|Hoo|1.5.0
latex-workshop|Jam|8.20.2
better-cpp-syntax|jef|1.15.10
vsc-python-indent|Kev|1.14.2
MagicPython|mag|1.1.0
vscode-language-babel|mgm|0.0.35
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.4
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.58.2
cmake-tools|ms-|1.8.1
cpptools|ms-|1.6.0
cpptools-extension-pack|ms-|1.0.0
js-debug-nightly|ms-|2021.9.2817
java|red|0.82.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-spell-checker|str|2.0.8
tabnine-vscode|Tab|3.4.29
cmake|twx|0.0.17
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.5
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.0
quokka-vscode|Wal|1.0.402

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis200:30374795
vsaa593:30376534

```

</details>

**Comment by Tyriar** [comment]
@zadjii-msft when resizing the viewport to include more columns, the normal behavior of a terminal is to push the scrollback back into the viewport, but WT/conpty seems to assume the scrollback remains. Is there a way to change this behavior or do we need a special mode that handles resizes differently?

**Comment by zadjii-msft** [comment]
> Feels a little wrong to piggy back on win32 input mode as something else might adopt that in the future.

Oh sorry, that's confusing. Those are actually two separate flags to conpty that got added in a really small window. There's the aforementioned `--win32input` flag for telling conpty to request win32-input-mode, but then there's `--resizeQuirk` for "I know what I'm doing, I'm hosting a conpty, do the new resize thing". I never _really_ polished it for external use, it was added in the bugfix sprint for Terminal 1.0 so it's a little quirky. We didn't want to inadvertantly break someone who was relying on the old behavior, but never had the time to really evaluate 
1. if the old behavior was _ever correct_
2. if the new behavior would work _in general_ for everyone. 

My worry was about point 2 - I was worried that running `cmd.exe` inside something like `gnome-terminal` in `wsl` with `--resizeQuirk` on by default would be _more_ broken than today, which is what I was trying to avoid.

Relevant source: https://github.com/microsoft/terminal/blob/6268a4779c9b3f49b7f3c30471bda7ae292ac423/src/winconpty/winconpty.cpp#L100-L113

**Comment by Achuan-2** [comment]
This is a defect that greatly affects the experience

**Comment by nullgit** [comment]
I have also encountered this problem. But this problem only occurs on Windows terminal, not on linux, and it doesn't occur on Windows VSCode which SSH remote connect to linux.

**Comment by Achuan-2** [comment]
> I have also encountered this problem. But this problem only occurs on Windows terminal, not on linux, and it doesn't occur on Windows VSCode which SSH remote connect to linux.

yes，I also had this problem

**Comment by rafrafek** [comment]
It is common bug for Windows programs, e.g. Intellij: 

video:

https://www.youtube.com/watch?v=owrgc3gnoWg 

issue:

https://youtrack.jetbrains.com/issue/IDEA-290119/Terminal-output-is-lost-on-terminal-vertical-resizing

**Comment by graynjo** [comment]
It seems to be an exclusive mistake of conpty in win11, and I can't reproduce it on win10 and Windows server 2022.

**Comment by Tyriar** [comment]
Conpty support is only available from Windows 10 build 18309, that's probably why you see it on some but not others:

https://github.com/microsoft/vscode/blob/ff18720449d635d0cec7476d50541107a2150538/src/vs/platform/terminal/node/terminalProcess.ts#L162

When using winpty it may work but a lot of other things degrade, it's a worse experience overall.

**Comment by Rahulrai1998** [comment]
@Tyriar I am using Win 11 and I am getting the same text trimming issue while minimizing the terminal , can anyone tell me in decent way that what I need to do ??

**Comment by rafrafek** [comment]
> @Tyriar I am using Win 11 and I am getting the same text trimming issue while minimizing the terminal , can anyone tell me in decent way that what I need to do ??

I found working solution. I moved from Windows to MacOS and now this issue is gone. You can also switch to Linux. There are also other benefits of this move:

- encoding is now standard `UTF-8` instead of non-standard `WIN-123456`,
- lines end with standard `\n` instead of non-standard `\r\g\b`,
- unix terminal is way better than cmd,
- if you prefer PowerShell you can install it easily.

Switching to Linux is free, switching to MacOs is not free but their devices are really good, so it is worth consideration.

**Comment by Eugeny** [comment]
> > @Tyriar I am using Win 11 and I am getting the same text trimming issue while minimizing the terminal , can anyone tell me in decent way that what I need to do ??
> 
> I found working solution. I moved from Windows to MacOS and now this issue is gone. You can also switch to Linux. There are also other benefits of this move:
> 
> - encoding is now standard `UTF-8` instead of non-standard `WIN-123456`,
> - lines end with standard `\n` instead of non-standard `\r\g\b`,
> - unix terminal is way better than cmd,
> - if you prefer PowerShell you can install it easily.
> 
> Switching to Linux is free, switching to MacOs is not free but their devices are really good, so it is worth consideration.

As a macOS and Linux user, this is cringe.

**Comment by rafrafek** [comment]
> As a macOS and Linux user, this is cringe.

I don't know if you helped investigating this issue. I tried at least. I recorded video presenting this bug and reported it to IntelliJ developers and here to VS Code developers. 

It has been months of not being able to use terminal on Windows properly, not only in apps mentioned, but in any app that uses terminal, including Windows Terminal.

I provided working solution, which is switching to other operating system. It may be useful for some people. For some people it may not. But it is the only workaround we have, at least for now. 

I strongly encourage people to try using UNIX-like systems, and I provided valid arguments for it. Unless there is something I don't know and Windows is now able to use common accepted standards. 

I hope you will live cringe-free life from now. Have a nice day.

**Comment by nitedani** [comment]
This is super annoying.

**Comment by rishabh-ibexlabs** [comment]
Recently I encountered same problem of losing test from vscode terminal when resizing on windows 11. 
Sharing a fix that worked for me -
In vscode > File > Preferences >  Settings > Features>Terminal>Integrated:WIndows Enable Conpty (In setting search terminal conpty) > Uncheck the checkbox and restart vscode
Hope this helps.

**Comment by nullgit** [comment]
> Recently I encountered same problem of losing text from vscode terminal when resizing on windows 11. Sharing a fix that worked for me - In vscode > File > Preferences > Settings > Features>Terminal>Integrated:WIndows Enable Conpty (In setting search terminal conpty) > Uncheck the checkbox and restart vscode Hope this helps.

it work for me too, thanks!

**Comment by rishabh-ibexlabs** [comment]
> > > Recently I encountered same problem of losing text from vscode terminal when resizing on windows 11. Sharing a fix that worked for me - In vscode > File > Preferences > Settings > Features>Terminal>Integrated:WIndows Enable Conpty (In setting search terminal conpty) > Uncheck the checkbox and restart vscode Hope this helps.
> > 
> > 
> > it work for me too, thanks!
> 
> I've had the same problem since the update but I seem to be able to consitantly recreate the bug even after turning this setting off. Weirdly it doesn't remove the entire history only the previous command. Occasionally the whole terminal bugs out and I get overlapping text which I think is caused by shrinking the window too small but I can't consistently repeat this.
> 
> Any other ideas would be much appreciated.
> 
> Edit:
> 
> ```
> Version: 1.76.2 (user setup)
> Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
> Date: 2023-03-14T17:55:54.936Z
> Electron: 19.1.11
> Chromium: 102.0.5005.196
> Node.js: 16.14.2
> V8: 10.2.154.26-electron.0
> OS: Windows_NT x64 10.0.22621
> Sandboxed: No
> ```

You can also try these, but I cannot confirm if it will work or not but still you can try once.

You can check if increasing scrollback works for you or not i.e. - 
In vscode > File > Preferences > Settings > Features>Terminal>Integrated:Scrollback (in setting search scrollback) > increase value to 3000 > restart vscode.

You can try unchecking vscode compatiblity mode.
rightclick vscode icon > properties > compatiblity (tab) > uncheck the check box in compatiblity mode and open vscode.

Hope this helps.
You can also try and check if combination of these fixes and one mentioned above works for you or not.

**Comment by notesbytom** [comment]
> Recently I encountered same problem of losing text from vscode terminal when resizing on windows 11. Sharing a fix that worked for me - In vscode > File > Preferences > Settings > Features>Terminal>Integrated:WIndows Enable Conpty (In setting search terminal conpty) > Uncheck the checkbox and restart vscode Hope this helps.

Restart of vscode was not enough for me. I needed to Delete the existing terminal sessions as they kept using conpty with the same issue. Fresh (new) terminal windows after changing that setting and restarting vscode work correctly for me. Thanks for the tip! This is an embarrassing bug impacting the latest releases of vscode, both stable and insider builds.

**Comment by oldshensheep** [comment]
> > Recently I encountered same problem of losing text from vscode terminal when resizing on windows 11. Sharing a fix that worked for me - In vscode > File > Preferences > Settings > Features>Terminal>Integrated:WIndows Enable Conpty (In setting search terminal conpty) > Uncheck the checkbox and restart vscode Hope this helps.
> 
> Restart of vscode was not enough for me. I needed to Delete the existing terminal sessions as they kept using conpty with the same issue. Fresh (new) terminal windows after changing that setting and restarting vscode work correctly for me. Thanks for the tip! This is an embarrassing bug impacting the latest releases of vscode, both stable and insider builds.

Disable the `Terminal › Integrated: Windows Enable Conpty` works! After that, just open a new terminal, don't need restart.
But the fonts looks ugly, and missing fonts. (Disable Conpty)
![image](https://user-images.githubusercontent.com/29306733/229105876-25b627d3-7046-4b07-95e2-8c10a6c32f1e.png)

Enable Conpty:
![image](https://user-images.githubusercontent.com/29306733/229106080-ca393f15-48ed-4aa9-addb-b4761f1c6ca7.png)

**Comment by Tyriar** [comment]
After being confused for a while trying to reproduce this in xterm.js, it turns out we already fixed this with `windowsMode` in xterm.js:

https://github.com/xtermjs/xterm.js/blob/22a4dc4b6b8c17a099d4f0f4354cd3d84a59b85b/src/common/buffer/Buffer.ts#L181-L184

But we have since disabled that post Windows built 21376 to avoid the wrapping heuristics:

https://github.com/microsoft/vscode/blob/44b766dcae0411af58d62942506985bd15b5521a/src/vs/platform/terminal/node/ptyService.ts#L719

We need greater granularity in the backend used on xterm.js
