### ISSUE TITLE
Can't view full chart in interactive window

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#134459]
Issue Type: <b>Bug</b>

1. Open Jupyter interactive window
2. Run some stuff so that you have to scroll vertically
3. Now run:

```py
import numpy as np
import matplotlib.pyplot as plt

# setup some generic data
N = 37
x, y = np.mgrid[:N, :N]
Z = (np.cos(x*0.2) + np.sin(y*0.3))

# mask out the negative and positve values, respectively
Zpos = np.ma.masked_less(Z, 0)
Zneg = np.ma.masked_greater(Z, 0)

fig, (ax1, ax2) = plt.subplots(figsize=(8, 3), ncols=2)

# plot just the positive data and save the
# color "mappable" object returned by ax1.imshow
pos = ax1.imshow(Zpos, cmap='Blues', interpolation='none')

# add the colorbar using the figure's method,
# telling which mappable we're talking about and
# which axes object it should be near
fig.colorbar(pos, ax=ax1)

# repeat everything above for the the negative data
neg = ax2.imshow(Zneg, cmap='Reds_r', interpolation='none')
fig.colorbar(neg, ax=ax2)

plt.show()
```

(from https://matplotlib.org/2.0.2/examples/api/colorbar_basics.html)

**Bug**
I can only see the top of the output chart:

<img width="1232" alt="Screen Shot 2021-10-05 at 11 00 20 AM" src="https://user-images.githubusercontent.com/12821956/136077946-a613d6fa-0ae0-470a-a844-2753af5d7569.png">

I cannot scroll to view the whole thing

If I run some other code (such as just running `1`), then I can view the full plot by scrolling

<img width="1009" alt="Screen Shot 2021-10-05 at 11 04 25 AM" src="https://user-images.githubusercontent.com/12821956/136078279-c500be70-dbc3-40ad-8f2c-3ff51c652646.png">

VS Code version: Code - Insiders 1.61.0-insider (Universal) (71ca6e8e74591ae5c577d52a2aa1bd0c3df5ac32, 2021-10-05T01:23:40.704Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (2.97GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30364496
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsqsis300:30374797
vsaa593cf:30376535

```

</details>

**Comment by amunger** [comment]
fixed with auto scroll improvements
