### ISSUE TITLE
Default build doesn't run in split pane, sometimes

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#134431]
1. Open our selfhost repo: microsoft/vscode
2. Press <kbd>Ctrl Shift B</kbd> to start the default build

🐛 Sometimes you get 2 build tasks in separate terminals, not in split mode
🐛 Sometimes <kbd>Ctrl C</kbd> in one of them will close the panel, despite the fact that there is still a terminal open and the other task running.

![image](https://user-images.githubusercontent.com/22350/135994929-d226b978-7a7c-44cb-a90f-89e3ca857f7d.png)

**Comment by meganrogge** [comment]
I haven't been able to reproduce this on windows or mac.

**Comment by meganrogge** [comment]
When I run the build task via the command pallette ->` Run Task: VS Code - Build`, I see that they're not split terminals. When I do ctrl + shift +b IE "workbench.action.tasks.build", they are in split terminals. @alexr00 thoughts?

**Comment by meganrogge** [comment]
could have to do with this?

https://github.com/microsoft/vscode/blob/dccb659623d0fb032a3a915837446c5b32b1c96d/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1305

**Comment by alexr00** [comment]
To verify, add tasks that are similar to the following to your tasks.json in an open folder:
```json
{
            "label": "repos",
            "dependsOn": [
                "repo1",
                "repo2",
            ],
            "problemMatcher": [],
        },
        {
            "label": "repo1",
            "type": "process",
            "command": "bash",
            "options": {
                "cwd": "${workspaceFolder}/src",
            },
            "isBackground": true,
            "problemMatcher": [],
            "presentation": {
                "group": "repos-group",
                "echo": false,
                "focus": false,
                "panel": "dedicated",
            }
        },
        {
            "label": "repo2",
            "type": "process",
            "command": "bash",
            "options": {
                "cwd": "${workspaceFolder}/out",
            },
            "isBackground": true,
            "problemMatcher": [],
            "presentation": {
                "group": "repos-group",
                "echo": false,
                "focus": false,
                "panel": "dedicated",
            }
        }
```
Then, run the task "Repos".  Verify that you see two tasks in a split terminal. Run 2-3 more times to double check, as this was a race.

**Comment by joaomoreno** [comment]
I still see this in selfhost. 😢

**Comment by joaomoreno** [comment]
In fact I hit the bug more often than not.

**Comment by connor4312** [comment]
@joaomoreno have you seen this bug since?

**Comment by joaomoreno** [comment]
Nope, good to close!
