### ISSUE TITLE
DecorationOptions performance

### ISSUE THREAD

**Issue by wmaurer** [Microsoft/vscode#13442]
- VSCode Version: 1.5.3
- OS Version: Windows 10

I have released an alpha of extension `vscode-jumpy` [(marketplace)](https://marketplace.visualstudio.com/items?itemName=wmaurer.vscode-jumpy) [(repo)](https://github.com/wmaurer/vscode-jumpy).

The extension creates many decorators in the currently activated editor by calling `createTextEditorDecorationType` (once) and then `setDecorations` with each decoration referencing a different SVG file via `contentIconPath`.

I have noticed a slightly slow rendering performance that is perceptible to the user.

I haven't managed to be able successfully use data urls, which I would have presumed would be faster than references to files on the file system. Is this supposed to be supported, or is this planned? I would like to be able use `DecorationOptions` as follows:
```
return {
    range: new vscode.Range( ... ),
    renderOptions: {
        dark: {
            after: {
                contentIconPath: `data:image/svg+xml;utf8,<svg ... > ... </svg>`
            }
        }
    }
};
```

**Comment by jrieken** [comment]
fyi - with yesterdays release VS Code allows to  define [`contentIconPath`](https://github.com/Microsoft/vscode/blob/joh/fmtprio/src/vs/vscode.d.ts#L821) as `string` or `Uri`. You can use the latter to provide a data-url, ala `vscode.Uri.parse('data:image/...')`

**Comment by wmaurer** [comment]
@jrieken thanks, I'll give that a try very soon.
That [vscode.d.ts](https://github.com/Microsoft/vscode/blob/joh/fmtprio/src/vs/vscode.d.ts#L821) you referenced looks different to the one that comes with a scaffolded extension.
A scaffolded extension uses the npm package [vscode-extension-vscode](https://www.npmjs.com/package/vscode).
Shouldn't this package be updated with the latest typings for VSCode 1.6?

**Comment by jrieken** [comment]
yeah - it depends on the vscode-engine you have specified in your package.json. With that we try to find a release on GH and use that file

**Comment by wmaurer** [comment]
Ok, got it, thanks ;-)

**Comment by wmaurer** [comment]
Thanks @jrieken, Data Uris are working nicely for `contentIconPath`. I've released a new version of Jumpy!
