### ISSUE TITLE
Node debugger breakpoints not bound

### ISSUE THREAD

**Issue by leqwasd** [microsoft/vscode#134482]
- VS Code Version: 1.60.2 and Insider version (tested 06.10.2020)
- OS Version: Windows 10

My project setup is like this: I build the project locally (typescript, express, node), then create a docker, copy it into it. I launch it with docker-compose up.

In the docker, this command is used to launch the app in debug mode: nodemon --exec \"node --inspect=0.0.0.0:9229 build/service.js\" --legacy-watch --watch build

Ports used here are mapped to different ports in docker-compose.yml

        ports:
            - 9000:3030 #app port
            - 8999:9229 #debugger port
My launch.json contains this relevant block:

        {
            "name": "Attach to service",
            "port": 8999,
            "address": "localhost",
            "remoteRoot": "/app/build",
            "localRoot": "${workspaceFolder}/build/",
            "protocol": "inspector",
            "restart": true,
            "sourceMaps": true,
            "type": "node",
            "request": "attach",
        },
All of this was working some time ago. It doesn't any more. So I downloaded multiple versions of Visual Studio code, to try to find the point, where it broke. It was working since version of April 2021 till July 2021. August 2021 broke it.

The issue is - no breakpoints are bound. The debugger still connects to the app through debug port (I can see that in the service console output), but no breakpoints are bound, so no breakpoints are hit..

In the changelog: https://code.visualstudio.com/updates/v1_60#_javascript-debugging relevant line (perhaps): Legacy node debuggers are gone

I did try to install that https://marketplace.visualstudio.com/items?itemName=ms-vscode.node-debug with type: "legacy-node" but it did nothing different..

type: "pwa-node" was never working for me.

So my question is - what is the problem?

Steps to Reproduce:
1. clone https://github.com/leqwasd/bug-breakpoint/tree/main
2. follow readme

**Comment by connor4312** [comment]
You should set your local/remote root like:

```
            "remoteRoot": "/app",
            "localRoot": "${workspaceFolder}",
```

This is because webpack bundles always contain paths relative to the "root" folder, such as `webpack://bug-breakpoint/./src/server.ts`. When using the localRoot, we use that as the "root" folder, which caused the path to be formed incorrectly as `${workspaceFolder}/build/src/server.ts`
