### ISSUE TITLE
Markdown preview scollbar disappear on edit in split mode

### ISSUE THREAD

**Issue by micnic** [Microsoft/vscode#13445]
- VSCode Version: 1.6
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. Open a .md (markdown) file
2. Click on "Split Editor"
3. In one tab use the source in another - the file preview
4. Edit the source
5. Updates are made, but the scrollbar in the file preview disappeared (scroll behavior is still available using mouse or keyboard)

**Comment by aakrem** [comment]
<img width="311" alt="screen shot 2016-10-11 at 09 20 46" src="https://cloud.githubusercontent.com/assets/6608260/19261851/1b94865e-8f94-11e6-84d8-c915022581c4.png">
markdown  Preview button is not available anymore.
Visual code version: 1.6
OS version: El Capitan 10.11.6

**Comment by rhbecker** [comment]
same bug for me ...

version 1.6.1
windows 7

I can sometimes get it to reappear if I switch to a different tab on the same side of the split editor as the preview tab, monkey around a bit, and then switch back, but I can't yet discern any pattern to what exact action is triggering it to reappear.

**Comment by mjbvz** [comment]
I believe that this was fixed by #19394, which worked around an upstream chrome issue

Please try VSCode 1.9 and let me know if you still see this

Thanks
