### ISSUE TITLE
Cursor kann nicht von fett nach normal gewechselt werden

### ISSUE THREAD

**Issue by copterhans** [microsoft/vscode#134422]
Issue Type: <b>Bug</b>

Ich arbeite mit Mac Vscode zum anpassen meiner daten in Marlin nun habe ich das Problem das ch keine Zeile ändern kann da der curser fett blinkt und nicht zum normalen wechselt

VS Code version: Code 1.60.2 (Universal) (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T11:59:27.195Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (6.34GB free)|
|Process Argv|--crash-reporter-id 92e352fa-c98b-40ab-ad02-5a44f6e7b4df|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
code-gnu-global|aus|0.2.2
c-cpp-compile-run|dan|1.0.14
CppSnippets|har|0.0.15
ccpp-extension-pack|Leo|1.1.0
auto-build|mar|2.1.34
vscode-clang|mit|0.2.4
vscode-language-pack-de|MS-|1.60.4
cmake-tools|ms-|1.8.1
cpptools|ms-|1.6.0
cpptools-extension-pack|ms-|1.0.0
platformio-ide|pla|2.3.3
cmake|twx|0.0.17
vim|vsc|1.21.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis200:30374795
vsaa593cf:30376535

```

</details>

**Comment by alexdima** [comment]
It looks like you have installed the `vim` extension and you probably did not want to. Please uninstall the `vim` extension.

**Comment by copterhans** [comment]
Yes it worked thanks
