### ISSUE TITLE
debug.startDebugging cannot find preLaunchTask

### ISSUE THREAD

**Issue by antounas** [microsoft/vscode#134496]
I am trying to create an extension that will be used for debugging Python code running in an embedded interpreter in another software. I have registered a command which is used to start the debugging process like this.

```
	vscode.debug.startDebugging(undefined,             {
		"name": "Remote Debug",
		"type": "python",
		"request": "attach",
		"connect": {
			"host": "localhost",
			"port": 5678
		},
		"preLaunchTask": "my-debug"
	});
```

The task is configured in my package.json like this

```
		"taskDefinitions": [
			{
				"type": "my-debug",
				"properties": {
					"isBackground": true
				}
			}
		],
		"problemMatchers": [
			{
				"name": "debug-problem-matcher",
				"owner": "custom",
				"pattern":[
					{
						"regexp": "."
					}
				],
				"background": {
					"activeOnStart": true,
					"beginsPattern": ".",
					"endsPattern": "Ready to attach the debugger"
				}
			}
		]
```

and this is the function I use to activate the Task

```
function registerTaskProvideDebug(context: vscode.ExtensionContext) {
    vscode.tasks.registerTaskProvider("my-debug", {
        provideTasks(token?: vscode.CancellationToken) {
            let shellCommand = .....;

            var execution = new vscode.ShellExecution(shellCommand);
            var problemMatchers = ["debug-problem-matcher"];
            return [
                new vscode.Task({type: "my-debug"}, vscode.TaskScope.Workspace,
                    "my-debug", "my-extension-name", execution, problemMatchers)
            ];
        },
        resolveTask(task: vscode.Task, token?: vscode.CancellationToken) {
            return task;
        }
    }
    );
}
```

However when I run my command I get the message Could not find the task "my-debug". The task runs find from the Terminal > Run Task. I have also tried to set it as "my-extension: my-debug" in startDebugging with no success.

Am I doing something wrong, is this a bug or it just this isn't possible to be done?

**Comment by weinand** [comment]
- Is the `vscode.tasks.registerTaskProvider("my-debug", ...` actually called when running the `vscode.debug.startDebugging(...)`?
- is the `my-debug` task found if you add it to your `tasks.json`?

**Comment by antounas** [comment]
- Yes, it is called.
- If the tasks.json is in the workspace folder I am working on it isn't found. It is found only if the task is manually added in the tasks.json located in User/tasks.json

**Comment by antounas** [comment]
I prefer to make it work even without workspace folders, just like if the Task was defined in User/tasks.json. That's why I used undefined in vscode.debug.StartDebugging.

**Comment by alexr00** [comment]
I need to update the task documentation to account for user tasks, but there's a note here that says tasks only work when there's a folder open: https://code.visualstudio.com/Docs/editor/tasks

From a tasks perspective, if no folder is open and an extension contributed task is passed into `getTask` that task just doesn't exist. The behavior in the issue sounds by design to me.
