### ISSUE TITLE
Backspace in `.md` file not working.

### ISSUE THREAD

**Issue by TechStudent11** [microsoft/vscode#134400]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.2
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Open a markdown file
2. Try to backspace
3. It doesn't work (it doesn't backspace)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo

**Comment by TechStudent11** [comment]
@mjbvz I'll do that later, but here is a video I forgot to upload:

https://user-images.githubusercontent.com/76978184/135928155-5dbcabc1-a896-4fff-bcac-0305719804f8.mp4

**Comment by TechStudent11** [comment]
update: so it's working again. however, it's really random.

**Comment by TechStudent11** [comment]
@mjbvz the issue hasn't happened in a while (probably a bit too soon to say it, but whatever) so I am gonna close this issue. I'll reopen it or create a new one if it ever happens again.
