### ISSUE TITLE
API: Allow an extension to clear memento storage

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#134424]
We (python extension) have accidentally stored large contents in the memento store, due to which users are facing perf issues https://github.com/microsoft/vscode-python/issues/17488. This could be a dup of https://github.com/microsoft/vscode/issues/87110, except I'm not sure how to easily clear keys just using the `Memento.keys` object that is exposed.

Simply using `globalState.update("key", undefined)` as suggested here https://github.com/microsoft/vscode/issues/87110#issuecomment-566508516 does not work as it sets the value of `key` as `undefined` instead of deleting the entry of the key. And we wish to reset the key to its default value which may not be `undefined`.

 It seems to reset a `key`, we also need to keep track of the default values associated with key, which may also change. Looking for an API to clear the storage for a particular key.

Open to alternatives.

**Comment by jrieken** [comment]
> sets the value of key as undefined instead of deleting the entry of the key. And we wish to reset the key to its default value which may not be undefined.

For us the default is `undefined`, like there is no way to check for the presence of a key with value `undefined` vs the lack of that key. The backing storage treats `undefined` or `null` as ["remove this key"](https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/storage/common/storage.ts#L100-L101)

**Comment by karrtikr** [comment]
I see, we treat `undefined` as just another value in a couple places in the extension, we'll correct that on our side then, thanks. Can we append the API description to make this clearer?
```typescript
/**
 * Store a value. The value must be JSON-stringifyable.
 *
 * @param key A string.
 * @param value A value. MUST not contain cyclic references.
 */
update(key: string, value: any): Thenable<void>;
```
with something like "Updating to `undefined` will remove the entry under the key."

This issue can be closed from my end.
