### ISSUE TITLE
Extensions Viewlet layout issue in Codespaces (Safari on iPadOS and MacOS)

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#134492]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:Codespaces (Insiders)
- OS Version:MacOS and iPadOS

Steps to Reproduce:

1.Open Extensions View
2.Choose any extension
3.Below the extension details, you should see a label describing `This extension is enabled globaly`. Instead you just see `This`

![Screen Shot 2021-10-06 at 07 44 20](https://user-images.githubusercontent.com/3781424/136189325-73eda9ad-8d4a-489a-8314-67b5988b8bf1.png)

Compared to VS Code, it seems the layout for that label is broken.

I just could test on Safari, both on iPadOS and MacOS BigSur.

Thank you

**Comment by sandy081** [comment]
/duplicate

It is an issue in codespaces.

**Comment by alefragnani** [comment]
Hi @sandy081 ,

Is there a proper repo (or other channel) to report issues related to Codespaces?
