### ISSUE TITLE
Small improvement to the Semantic Token Colors inspection for syntax colors

### ISSUE THREAD

**Issue by TamirCode** [microsoft/vscode#134446]
(I am talking about the syntax colors of code)
So when I do `ctrl + shift + p` and click `Developer: Inspect Editor Tokens and Scopes` there is a neat tool that shows each element so I can customize their colors properly. However, when pointing at brackets, for example in HTML, it considers them as part of the element even though they can have a different color. So then I have no idea how to customize the brackets of elements such as <div>.
The brackets are a different color from div, yet when u highlight or click the brackets they show as the same color of div itself.

**Comment by gjsjohnmurray** [comment]
Sounds like the bracket pair colorization feature, but you didn't say what version you are using.

/needsMoreInfo

**Comment by TamirCode** [comment]
(issue was with bracket extension, apologies)
