### ISSUE TITLE
Notebooks - Diff indicator in scroll bar area missing

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#134474]
- VS Code Version: 1.61.0-insider 

Notebooks doesn't have the diff indication in the scroll bar area like Python files

![image](https://user-images.githubusercontent.com/19276747/136142438-1653f93c-c388-4cd7-b673-0b62abafaca6.png)

**Comment by rebornix** [comment]
Yeah this is as designed as it's weird to show nested diff indictor.
