### ISSUE TITLE
Some syntax highlighting does not work in TypeScript when a function has several return types 

### ISSUE THREAD

**Issue by itayperry** [microsoft/vscode#134440]
- VS Code Version: 1.60.2

If all return types are aligned in one line than the coloring works - but beautifying packages such as prettier will always make it fall down. I don't understand why the highlighting doesn't work.

Steps to Reproduce: just write a function in `TypeScript` that has many types of return value:

![image](https://user-images.githubusercontent.com/37377389/136027863-dc1687ea-1386-45b3-97d0-66e97e488ed7.png)

As you can see, the `const` and the `return` don't get highlighted :(

Another (silly) example:

![image](https://user-images.githubusercontent.com/37377389/136029840-eb5b20d2-fab7-4717-9aed-f8772e136bda.png)

**Comment by Lemmingh** [comment]
Minimum reproducible case:

```typescript
class c {
    m(): number
        | Promise<boolean> {
        return 5;
    }
}
```

The `meta.method.declaration.ts` and `meta.return.type.ts` scopes are lost after a line ending. Then, the last generic makes it further wrong, causing `meta.objectliteral.ts`.

**Comment by Lemmingh** [comment]
This case is so similar to <https://github.com/microsoft/TypeScript-TmLanguage/issues/812#issuecomment-606228610> that I guess it might be a good one to push forward #77140

**Comment by itayperry** [comment]
@Lemmingh thank you for replying and looking into it so quickly :)
