### ISSUE TITLE
terminal.integrated.useWslProfiles: true can cause other profiles to not be detected

### ISSUE THREAD

**Issue by ToySin** [microsoft/vscode#134418]
Issue Type: <b>Bug</b>

The '+' button to open terminal in my visual studio code does not work. Also, the default profile selection button does not work.

The only thing I changed was from "launch.json" to "externalConsole: false->true". Even if I try to restore it to its original state, it remains the same. I tried reinstalling the VSCode, deleted the "setting.json" file, and recreated it. But... :(

Originally, I was using git bash as a standard, but there is only "JavaScript Debug Terminal" left.

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (7.57GB free)|
|Process Argv|--crash-reporter-id 9216e01f-2f83-4d12-8aec-e416db292dde|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.3.2
githistory|don|0.6.18
norminette-42|evi|1.0.8
vscode-pull-request-github|Git|0.30.0
better-cpp-syntax|jef|1.15.10
42header|kub|0.42.9
vscode-language-pack-ko|MS-|1.60.4
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.4
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.3
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
cmake-tools|ms-|1.8.1
cpptools|ms-|1.6.0
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4836
vsliveshare-audio|ms-|0.1.91
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis200:30374795
vsaa593cf:30376535

```

</details>

**Comment by ToySin** [comment]
![터미널먹통 (소형)](https://user-images.githubusercontent.com/40738437/135958614-49e4dbda-a3f5-4849-9e2b-ce3631c1e070.jpg)

**Comment by ToySin** [comment]
Youtube link

https://youtu.be/_xlv64Tc9FI

**Comment by meganrogge** [comment]
thoughts @Tyriar ?

**Comment by ToySin** [comment]
As you said, I added `"terminal.integrated.useWslProfiles": false` to the setting.json file and it returned to its original state. After that, it worked well even if it was changed to true, and even if it was deleted from the setting.json file, the terminal worked well. I think it's back now!
Thank you so much.

**Comment by nielsuit227** [comment]
Thought I'd comment on this as well. Experienced the same issue. Tried many different solutions, as this issue seems to have been around for a while. @Tyriar solution worked for me "terminal.integrated.useWslProfiles": false"

- VS Code Version: 1.61.0
- OS Version: Windows 10 Pro 21H1 19043.1237

**Comment by pleshakovalexander** [comment]
Had same problem. `"terminal.integrated.useWslProfiles":false` worked for me, but if i commented it or set to `true` terminal wiil go blank.
I tried other versions. The issue start appears from version 1.60

**Comment by meganrogge** [comment]
@pleshakovalexander do you have wsl installed?

**Comment by pleshakovalexander** [comment]
@meganrogge yes, i have wsl. Now I'm using 1.61.2 version of vs code.  I can't check what wsl version because i'm using Windows 10 1709 build 16299.2166

**Comment by pleshakovalexander** [comment]
@meganrogge 
My windows updated to version 20H2 build 19042.1288 and terminal work normal without `terminal.integrated.useWslProfiles` option setted to false

**Comment by meganrogge** [comment]
Was just able to reproduce this. in an external or integrated terminal, when I was able to repro the issue, running wsl.exe was hanging as described here. 
https://github.com/microsoft/WSL/issues/4144
