### ISSUE TITLE
Emit event when active workspace changes

### ISSUE THREAD

**Issue by d-koppenhagen** [microsoft/vscode#134441]
Hey, when making extensions [multi-root](https://code.visualstudio.com/docs/editor/multi-root-workspaces) ready it can be necessary to react on changes when for example the active text editor switches to a file within another workspace in the multi-root environment.

There is already an event fired when workspaces are added or removed from the config by listing to [`workspace.onDidChangeWorkspaceFolders`](https://github.com/microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs).
But there is an event that fires once the activity used workspace changes.

Therefore two things should be implemented:
- An event one can subscribe that will emit every time the active workspace changes - e.g. `workspace.onDidChangeActiveWorkspace`
- A additional prop inside the result of `window.onDidChangeActiveTextEditor` that references the currently active workspace

Here some use-cases:

- switching the theme settings dynamically depending on workspace for the open / active file
- switching a referenced file based on the current active file within a project

**Comment by sandy081** [comment]
Multi-root workspace has no concept of active folder and we do not have plans to add that. Sorry about it.
