### ISSUE TITLE
Weird letter spacing in integrated terminal

### ISSUE THREAD

**Issue by Quitch** [microsoft/vscode#134428]
Issue Type: <b>Bug</b>

1. Configure VSC for pwsh usage
2. Launch Visual Studio Code
3. Open integrated terminal

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (20.57GB free)|
|Process Argv|--crash-reporter-id 45a9fff1-a123-47ff-b465-ffd0536f06de|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.44.4
vscode-eslint|dba|2.1.25
prettier-vscode|esb|9.0.0
code-spell-checker|str|2.0.8
vscode-stylelint|sty|0.87.6
sort-lines|Tyr|1.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis300:30374797
vsaa593cf:30376535

```

</details>

**Comment by Quitch** [comment]
![image](https://user-images.githubusercontent.com/5182715/135985583-05306190-f6da-4659-a91a-0fde38740c1d.png)

Issue is the same as reported in #120004 and goes away when the window is resized.

**Comment by Tyriar** [comment]
Can you share your settings.json file?

**Comment by Quitch** [comment]
My client updated to v1.61.0 when I opened to reproduce and now I struggle to. It appears to reoccur every so often, but I can't find a way to reliably reproduce. It now mostly works.

**Comment by meganrogge** [comment]
great to hear. please comment on this issue if you see it again and can repro it reliably. otherwise, closing this to keep our issue count manageable 😄
