### ISSUE TITLE
Can't duplicate file

### ISSUE THREAD

**Issue by d-noll** [microsoft/vscode#134414]
I'd like to cut down on redundancy and use ⌘D to duplicate a file, rather than having to ⌘C ⌘V.

Oddly enough, the Selection menu _does_ have something called "Duplicate Selection" that sounds like it would do the job, but it does not. And it's in the wrong menu anyway, duplicating something would go in Edit.

Usually Duplicate is near Rename and Delete. Delete is also missing from the Edit menu. Rename is a bit more annoying to support because it means different things if you are in an editor vs the file tree.

**Comment by JacksonKearl** [comment]
Are you referring to this menu?
![image](https://user-images.githubusercontent.com/8586769/135950729-d4c3cb8e-d2f1-4340-838d-f9865408c469.png)

Extensions can contribute to this menu, that may be what you're seeing, but I do not see "Duplicate Selection" here.

**Comment by d-noll** [comment]
No, the main menu.
<img width="449" alt="Screen Shot 2021-10-05 at 14 27 30" src="https://user-images.githubusercontent.com/4900565/135955370-848bff78-4031-4896-a9e6-156d6edb9bbd.png">

**Comment by d-noll** [comment]
I also discovered what it actually does as well, it takes the selected _text_ and duplicates that. Which is really unexpected if I just put focus on the file tree.
