### ISSUE TITLE
Unable to Login and Sync settings

### ISSUE THREAD

**Issue by ManojKshetrapalam** [microsoft/vscode#134480]
Issue Type: <b>Bug</b>

Hi Team,
I am unable to login to my GIT account to sync all the VS code settings. 

Regards
Manoj
bnmanoj@outlook.com

VS Code version: Code - OSS 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-29T02:43:56.744Z)
OS version: Linux x64 5.14.9-zen2-1-zen
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz (4 x 2751)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|7.71GB (0.19GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.1
prettier-vscode|esb|8.1.0
python|ms-|2021.9.1246542782
jupyter|ms-|2021.8.12

</details>

**Comment by gjsjohnmurray** [comment]
Exactly what steps are you taking to log in, and at what point does the attempt fail? Maybe post screenshots, but make sure you mask any confidential areas of the images.

/gifPlease

**Comment by ManojKshetrapalam** [comment]
John,

I click on the login icon on the VSCode, I get a popup - loading and 
nothing happens furtherLoading

**Comment by ManojKshetrapalam** [comment]
![recording](https://user-images.githubusercontent.com/85968969/136155009-7924e2e8-867b-4169-ae23-3d91ba5763ae.gif)

**Comment by gjsjohnmurray** [comment]
What brand of Linux are you using? Where did you install VS Code from?

**Comment by ManojKshetrapalam** [comment]
I am using Garuda Arch linux. I installed using Discover

**Comment by ManojKshetrapalam** [comment]
unsitalled and reinstalled by using yay. Now its working fine. Thanks for the support.
