### ISSUE TITLE
Obscure errors when developing extension in macOS Sierra & vscode 1.6.0

### ISSUE THREAD

**Issue by johnfn** [Microsoft/vscode#13451]
- VSCode Version: 1.6.0
- OS Version: macOS Sierra

Steps to Reproduce:

1. Clone my extension: https://github.com/VSCodeVim/Vim
2. `npm install` 
3. Open it in VSCode and run the "Launch Extension" debug configuration.
4. See the following errors:

```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
```

I don't know what this means, but it is concerning.

**Comment by isidorn** [comment]
I also get similar errors on my macOS Sierra when running vscode out of source

**Comment by joaomoreno** [comment]
electron/electron#6727
