### ISSUE TITLE
Shift+numpad1 is not respected (Shift+End)

### ISSUE THREAD

**Issue by evandrocoan** [microsoft/vscode#134541]
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:54:37.513Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Linux x64 5.4.0-47-generic
```

Steps to Reproduce:
1. Set keybind:
```json
    { "key": "shift+numpad1",             "command": "cursorEnd",
        "when": "textInputFocus",
        "args": {"sticky":false} },
```
2. Press `Shift+numpad1` in the middle of the line

The expected behavior is to not call the `cursorEndSelect` command, but `cursorEnd` when pressing `Shift+numpad1`.
```json
{ "key": "shift+end",             "command": "cursorEndSelect",
                                     "when": "textInputFocus",
                                     "args": {"sticky":false} },
```

But it does call `cursorEndSelect` instead of `cursorEnd` (causing the text to be selected), instead of jumping to the end of the line.

If I actually pressed my `End` key with `Shift+End`, then, I would expect the text to be selected (cursorEndSelect). But as I actually pressed `Shift+numpad1`, I would expected to this to be equivalent to just pressing `End` (cursorEnd).

This would be the expected behavior the because on the numpad keyboard, the numpad1, is an alternative/alias to the `end` key when the `Shift` modifier is pressed, i.e., `Shift+numpad1` is equal to just pressing `End`:
![image](https://user-images.githubusercontent.com/5332158/136307328-7e393868-6418-4898-88c4-5e03868e7afa.png)

Related to:
1. https://github.com/microsoft/vscode/pull/17027 - Standardize cursor movement with home and end keys
1. https://github.com/microsoft/vscode/issues/10807 - Standard Keyboard Functionality: Shift + End/Home doesn't work

**Comment by evandrocoan** [comment]
Hi, Sublime Text can differentiate between a keypad on and a keypad off. When keypad is on, it does accept the key bind `shift+keypad1` as just the `End` keypress:
```json
	{ "keys": ["shift+keypad1"], "command": "move_to", "args": {"to": "eol", "extend": false} },
```

But when the keypad is off, then the key bind is read as `Shift+End` (as VSCode always does).

VSCode has no way of knowing when the keypad is on or off to respect this behavioror?

**Comment by alexdima** [comment]
@evandrocoan I have to be honest, I am not sure, I think these keybindings might be distinguishable. To test it out, could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press `Numpad1` with `NumLock` off and on and separate the outputs so we can look at them together.
* Paste here the output and we can check if we can distinguish them.

**Comment by evandrocoan** [comment]
Thanks for looking into it. This is the output, it looks they are doing what the need to, I just wonder why the keybinds I tried to use on the first post did not work.

1. Keypad key press from `off` to `on`
    ```
    20:22:18.969 / Received  keydown event - modifiers: [], code: NumLock, keyCode: 144, key: NumLock
    20:22:18.969 | Converted keydown event - modifiers: [], code: NumLock, keyCode: 78 ('NumLock')
    20:22:18.969 | Resolving [NumLock]
    20:22:18.969 \ No keybinding entries.
    ```

1. Keypad key press from `on` to `off`
    ```
    20:22:56.699 / Received  keydown event - modifiers: [], code: NumLock, keyCode: 144, key: NumLock
    20:22:56.699 | Converted keydown event - modifiers: [], code: NumLock, keyCode: 78 ('NumLock')
    20:22:56.700 | Resolving [NumLock]
    20:22:56.700 \ No keybinding entries.
    ```

1. `numpad1` key press with keypad `off`
    ```
    20:19:52.992 / Received  keydown event - modifiers: [], code: Numpad1, keyCode: 35, key: End
    20:19:52.992 | Converted keydown event - modifiers: [], code: Numpad1, keyCode: 13 ('End')
    20:19:52.992 | Resolving [End]
    20:19:52.992 \ From 5 keybinding entries, matched cursorEnd, when: textInputFocus, source: built-in.
    ```

1. `numpad1` key press with keypad `on`
    ```
    20:20:55.307 / Received  keydown event - modifiers: [], code: Numpad1, keyCode: 97, key: 1
    20:20:55.308 | Converted keydown event - modifiers: [], code: Numpad1, keyCode: 94 ('NumPad1')
    20:20:55.309 | Resolving [Numpad1]
    20:20:55.309 \ No keybinding entries.
    ```

1. `Shift+numpad1` key press with keypad `off`
    ```
    20:22:04.218 / Received  keydown event - modifiers: [shift], code: ShiftRight, keyCode: 16, key: Shift
    20:22:04.219 | Converted keydown event - modifiers: [shift], code: ShiftRight, keyCode: 4 ('Shift')
    20:22:04.220 \ Keyboard event cannot be dispatched in keydown phase.
    20:22:04.610 / Received  keydown event - modifiers: [shift], code: Numpad1, keyCode: 97, key: 1
    20:22:04.611 | Converted keydown event - modifiers: [shift], code: Numpad1, keyCode: 94 ('NumPad1')
    20:22:04.612 | Resolving shift+[Numpad1]
    20:22:04.612 \ No keybinding entries.
    20:22:04.825 + Storing single modifier for possible chord shift.
    20:22:05.126 + Clearing single modifier due to 300ms elapsed.
    ```

1. `Shift+numpad1` key press with keypad `on`
    ```
    20:21:41.240 / Received  keydown event - modifiers: [shift], code: ShiftRight, keyCode: 16, key: Shift
    20:21:41.241 | Converted keydown event - modifiers: [shift], code: ShiftRight, keyCode: 4 ('Shift')
    20:21:41.241 \ Keyboard event cannot be dispatched in keydown phase.
    20:21:41.698 / Received  keydown event - modifiers: [shift], code: Numpad1, keyCode: 35, key: End
    20:21:41.699 | Converted keydown event - modifiers: [shift], code: Numpad1, keyCode: 13 ('End')
    20:21:41.700 | Resolving shift+[End]
    20:21:41.700 \ From 2 keybinding entries, matched cursorEndSelect, when: textInputFocus, source: built-in.
    20:21:42.298 + Storing single modifier for possible chord shift.
    20:21:42.601 + Clearing single modifier due to 300ms elapsed.
    ```
