### ISSUE TITLE
No webviews can load 

### ISSUE THREAD

**Issue by m-hilgendorf** [microsoft/vscode#134580]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```bash
$ code --version
1.60.2
7f6ab5485bbc008386c4386d08766667e155244e
x64
```
- OS Version:
```bash
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
Steps to Reproduce:

1. Install VS Code 1.60.2 from the [website](https://code.visualstudio.com/docs/?dv=linux64_deb)
2. Open Release Notes (Ctrl + Shift + P, "Show Release Notes")
3. See error message : 
```
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
````

![Peek 2021-10-07 10-28](https://user-images.githubusercontent.com/28515218/136416071-b988b755-8715-4ebb-a852-9ad60339fa24.gif)

**Comment by flavianojs** [comment]
If this issue is duplicated, there should be a link for the original one. I have looked over three issues and still didn't find where it was solved.
