### ISSUE TITLE
Task doesn't run to completion when terminal is in editor area

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#134533]
Repasting from https://github.com/microsoft/vscode-cpptools/issues/8183:

1. Clone https://github.com/rzhao271/named-pipe-sample (the code is specific to Windows).
2. In the settings editor, set `terminal.defaultLocation` to `editor`.
3. Run the configured build task.
4. 🐛 The task terminal opens up in the editor area, but the task never finishes.

Note that the build task works fine when `terminal.defaultLocation` is set to `view`.

According to https://github.com/microsoft/vscode-cpptools/issues/8183#issuecomment-934966315, the issue has to do with the way `${file}` is being resolved.

**Comment by alexr00** [comment]
Related: https://github.com/microsoft/vscode/issues/136355, https://github.com/microsoft/vscode/issues/136356.

In the mean time, I've set task terminals to always be `view`.

**Comment by rchiodo** [comment]
/verified

Tasks always run in the view.
