### ISSUE TITLE
Two "show more" links being shown in stdout output

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#134508]
Version: 1.60.0-insider (user setup)
Commit: 58454f7bec838f79fe2422ab5914419147d82e40
Date: 2021-08-13T05:15:29.421Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Unfortunately, I'm not sure what I did to make this happen, but I certainly shouldn't see two "show more" links in one set of output. I had been modifying a particular cell over and over, and not really paying attention to the output, till I scrolled down. I'm trying to repro again with a simpler cell, but so far, no go.

![image](https://user-images.githubusercontent.com/11685408/129454806-d945b71c-6960-497d-a7ce-e0cbf2005534.png)

**Comment by rchiodo** [comment]
Show more output is put there by VS code core.

**Comment by rebornix** [comment]
we have size limit for each individual output.
