### ISSUE TITLE
how to replace characters as newline break

### ISSUE THREAD

**Issue by chwentao** [Microsoft/vscode#13459]
- VSCode Version: 1.6
- OS Version: win7

vscode怎么把某个字符替换成换行

**Comment by Jacksing** [comment]
Maybe there should be an english edition of this issue.

"How to replace a character with a new line in vscode?"

I feel curious about what exactly the issue is, is there any more detail description of it?

**Comment by chwentao** [comment]
Yes, my mean is "How to replace a character with a new line in vscode?".

for example I want to replace the '|' use \r\n.
before replace:
dfdsalfsljdafjjjjafdsfsad|fsdfdsfdsfsff|dfsdfdsfsdfd

after replace:
dfdsalfsljdafjjjjafdsfsad
fsdfdsfdsfsff
dfsdfdsfsdfd

**Comment by fibric** [comment]
You can do this when enabling ReGex in the find and replace dialog.
![image](https://cloud.githubusercontent.com/assets/623932/19270806/201252be-8fc2-11e6-809d-d0c21428b9eb.png)

The little `.*` enables ReGex. The pipe sign is a regex `or` operator and special meaning; therefore it must be escaped in the search field.

I'm not sure if `\r\n` is the correct replacement for CRLF. I think `\n` is enough when CRLF is enabled. But I'm not sure nor certain about the CRLF mode.

Replacing with `\r\n`
before
```
dfdsalfsljdafjjjjafdsfsad|fsdfdsfdsfsff|dfsdfdsfsdfd
```
after
```
dfdsalfsljdafjjjjafdsfsad\r
fsdfdsfdsfsff\r
dfsdfdsfsdfd
```

Replacing with `\n`
before
```
dfdsalfsljdafjjjjafdsfsad|fsdfdsfdsfsff|dfsdfdsfsdfd
```
after
```
dfdsalfsljdafjjjjafdsfsad
fsdfdsfdsfsff
dfsdfdsfsdfd
```

**Comment by chwentao** [comment]
thanks, I see
