### ISSUE TITLE
Ctrl+Cmd not working

### ISSUE THREAD

**Issue by pchen54627** [microsoft/vscode#134546]
Issue Type: <b>Feature Request</b>

Ctrl+Cmd not working, should be link to function definition

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by mjbvz** [comment]
Please share steps the reproduce the issue

/needsMoreInfo
