### ISSUE TITLE
Better UX for recommended extensions

### ISSUE THREAD

**Issue by jaime-olivares** [Microsoft/vscode#13456]
Suggestions for improving the recommended extensions functionality:
1. Whenever I choose the new 'Configure Workspace Recommended Extensions" option, the list of currently installed extensions should be included rather than an empty json array. Adding one by one is really painful.
2. When viewing the list of installed extensions and I click one of them for looking at the details, in the header topbar, next to the [Uninstall] button, there should be another [Recommend] button for automatically adding it to the current workspace.
3. When looking at the list of recommended extensions (filter @recommended:workspace), there should be an 'install all' option.

**Comment by joaomoreno** [comment]
1. Probably not a good idea since most of the cases you'd end up deleting lines from the file. What you'd want there is language services (similar to intellisense in `package.json` dependencies).
2. We could add a `Add to Workspace Recommendations` context action to the extension in the viewlet. I wouldn't make it too prominent.
3. Good idea, which we could apply to a lot of other concepts, like `Update all`.

**Comment by jaime-olivares** [comment]
For 1 intellisense would help. Whatever avoids me to manually copy/paste the extension names.
As a second alternative, deleting the unneeded extension names is still better than copy/paste.

**Comment by sandy081** [comment]
I think providing intellisense will be helpful and makes sense than copying the installed extensions.

**Comment by sandy081** [comment]
1 is implemented. Leaving to @ramya-rao-a for the rest as she currently working on improving it.

**Comment by ramya-rao-a** [comment]
The 3rd point is done as well. There is "Install All" action on the header of the workspace recommendations section.

**Comment by ramya-rao-a** [comment]
In the latest Insiders and in the upcoming stable update of 1.25.0, there are new commands that will let you add an extension to Workspace recommendations 

![image](https://user-images.githubusercontent.com/16890566/41940618-2f9c0884-794e-11e8-9c06-ec431b68016f.png)

With this all points mentioned in the initial list is complete.
So closing
