### ISSUE TITLE
1.6 Bug with a redirect in preview html

### ISSUE THREAD

**Issue by anthonydresser** [Microsoft/vscode#13454]
- VSCode Version: 1.6.0
- OS Version: Mac 10.11.6

As of 1.6 there has been a problem with an extension I am working on where it is not properly reloading the preview pane on content update or when multiple previews are open.

Specifically the first time the provideTextDocumentContent is called, the content that is returned is correctly shown (the string is a simple html page with an embedded script that redirects the page to a local webserver via window.location.href) and the page redirects correctly. 

When the onDidChange emitter is fired and the provideTextDocumentContent is called again, it used to be that the preview pane when once again update with the redirect html and everything worked fine. However, in 1.6 nothing happens once the provideTextDocumentContent is called and the preview pane does not update.

Additionally, when a new document is created with the same TextDocumentContentProvider, the provideTextDocumentContent is called, but it seems as though the preview pane uses the same exact same webview as the first document (not just a copy) because there is no visual reload when switching between the two documents, and everything that happens in one (scrolling, etc) happens to the other. Additionally, the redirect never seems to fire, as the local webserver that would catch the redirect never receives a request (it does on the very first document).

This seems like odd behavior and I've tried looking up the call stack from provideTextDocumentContent to see if I can figure out the problem, however, I haven't been able to track anything down through the promise chain. Let me know if you need any other information.

**Comment by jrieken** [comment]
@anthonydresser Please provide more details such that I can reproduce this. I have tried with the following extension code and see the preview updating.

```ts
    const contentProvider = new class implements vscode.TextDocumentContentProvider {

        private _lastUri: vscode.Uri;
        private _emitter = new vscode.EventEmitter<vscode.Uri>();
        private _counter = 0;

        fire() {
            if (this._lastUri) {
                console.log('FIRE for ' + this._lastUri);
                this._emitter.fire(this._lastUri);
            }
        }

        get onDidChange() {
            return this._emitter.event;
        }

        provideTextDocumentContent(uri: vscode.Uri, token: CancellationToken): string {
            this._lastUri = uri;
            const ret = `${this._counter++} FOR ${uri.toString(true)}`;
            console.log(ret);
            return ret;
        }
    }

    vscode.workspace.registerTextDocumentContentProvider('testing', contentProvider);

    vscode.commands.registerCommand('extension.sayHello', function (range) {
        vscode.commands.executeCommand('vscode.previewHtml', vscode.Uri.parse('testing:foo/bar/' + Date.now()));
    });

    vscode.commands.registerCommand('extension.update', function () {
        contentProvider.fire();
    });
```

![oct-11-2016 09-53-17](https://cloud.githubusercontent.com/assets/1794099/19262664/93c321c2-8f98-11e6-922c-4dc0f10b7583.gif)

**Comment by anthonydresser** [comment]
I've recreated the problem in https://github.com/anthonydresser/vscodeRedirectTest as a simplified version of the problem. In the image in the readme you can see the two uri's don't change between the two preview panes. On older versions of vscode they would (tested on 1.5.3).

**Comment by jrieken** [comment]
Thanks for the repo - I understand the issue. It seems that the new version of Chrome got more strict - when a web view updates we replace the whole document using [`open`, `write`, and `close`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/webview.html#L114).  This generally works but fails in your case with this error: `webview.html:115 Uncaught SecurityError: Failed to execute 'open' on 'Document': Can only call open() on same-origin documents.` 

I'd guess that is because your html code [changes](https://github.com/anthonydresser/vscodeRedirectTest/blob/master/src/extension.ts#L73) the location href of the page and that doesn't seems to be allowed anymore... I'll digg deeper but it might require different html code on your side.

**Comment by jrieken** [comment]
I am not an html-spec wizard but I have found this behaviour to be specified here: https://www.w3.org/TR/DOM-Level-2-HTML/html.html#ID-72161170

For now and to unblock you, you can change the html to not use a redirect but an (fullscreen) iframe:

```ts
    provideTextDocumentContent(uri: vscode.Uri): string {
        let sourceUri = encodeURIComponent(uri.toString());
        return `
        <html>
        <head>
        </head>
        <body style="margin: 0; padding: 0; height: 100%; overflow: hidden;">
        <iframe width="100%" height="100%" frameborder="0" style="position:absolute; left: 0; right: 0; bottom: 0; top: 0px;" src="http://localhost:${this.port}/?uri=${sourceUri}"/>
        </body>
        </html>
        `
    }
```

**Comment by anthonydresser** [comment]
I see. That makes sense. Thanks for the help, hopefully I don't run into infamous iframe problems. 😣

**Comment by mjbvz** [comment]
In VSCode 1.11, we disabled redirection inside of the html preview entirely. Using the example extension, you should now see a message: `prevented webview navigation` in the developer console. This was done for security reasons

If you need this functionality, @jrieken's example using an iframe looks to be the best approach
