### ISSUE TITLE
Add option to set the default color for the terminal on workspace folder

### ISSUE THREAD

**Issue by albertoxamin** [microsoft/vscode#134566]
I often work with workspaces, when I open a new terminal it asks me on which directory I would like to start the terminal
![image](https://user-images.githubusercontent.com/6067659/136385795-73abe091-5e72-420d-8b02-b4233b96cf85.png)

It would be nice if in the `settings.json` located in the `.vscode` folder you could specify the default color (and names too) for terminals.

![image](https://user-images.githubusercontent.com/6067659/136386163-9f162860-6326-4b42-985e-b8751652f63f.png)

That would make terminals easier to distinguish, without having to change the colors and names every time.

**Comment by Tyriar** [comment]
You can kind of do this right now by creating a profile for your workspace, it would be a pain to maintain and get working across all users though. For this let's have 2 new settings:

- `terminal.integrated.tabs.defaultColor`
- `terminal.integrated.tabs.defaultIcon`

These two settings could then override the color or icon of the shell if the terminal is going to use the fallback. So the color for the below would change, but the icon for pwsh wouldn't as it has a explicitly set in the profile:

![image](https://user-images.githubusercontent.com/2193314/137979131-49dd5ab1-5248-41df-91d4-c809c70b7e2e.png)
