### ISSUE TITLE
Extension host process management

### ISSUE THREAD

**Issue by cveld** [microsoft/vscode#134549]
Issue Type: <b>Bug</b>

I admit that I have installed quite a few extensions. Nevertheless, I think they are all common and broadly applied. My expectations would be that vscode would be capable of handling these extensions with low amount of cpu usage.

Unfortunately I experience 10-20% CPU usage per vscode instance which makes vscode unusable when having many instances. Regularly I have to use 4 or 5 instances.

When I try to correlate the Windows Task Manager process consumption information with the internal dev process explorer, I cannot make sense out of it. The Windows Task Manager reports many vscode processes with a nice cpu usage breakdown, whereas the internal process explorer only shows cpu usage per vscode instance it seems.

It would be great if the extension host process manager could improve so that I could get better insights in which extension is bugging. Based on the current information it seems that the extension host itself has issues.

If some extension is consuming this huge amount of cpu, maybe it is possible to implement some cpu throttling inside the extension host. Regularly my desktop is completely coming to a halt when the range of vscode instances are digesting stuff. I just take a cup of coffee while waiting for the mouse cursor becoming responsive again after some minutes of intransparent processing.

![image](https://user-images.githubusercontent.com/6196260/136334186-b8e180b3-3fbc-476f-8f2e-6c81e2b9eba4.png)
![image](https://user-images.githubusercontent.com/6196260/136334302-d3a766a4-75a4-462c-990c-aa0a25692cab.png)

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (5.99GB free)|
|Process Argv|--folder-uri file:///c%3A/work/github/cveld/gameengine --crash-reporter-id 5ed5d6f6-dfc2-4c7c-8d01-9cba6511c0a5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|12.2.0
azurepolicyextension|Azu|0.2.1
armview|ben|0.4.5
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
go|gol|0.28.1
terraform|has|2.15.0
beautify|Hoo|1.5.0
file-downloader|min|1.0.11
vscode-azurefunctions|ms-|1.5.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.17.0
vscode-dotnet-runtime|ms-|1.3.0
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.4
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.3
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.9
azurecli|ms-|0.5.0
powershell-preview|ms-|2021.9.2
vscode-markdown-notebook|ms-|0.0.25
azurerm-vscode-tools|msa|0.15.3
vscode-commons|red|0.0.6
vscode-yaml|red|0.23.0
git-autoconfig|shy|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis300:30374797
vsaa593cf:30376535

```

</details>

**Comment by Tyriar** [comment]
We don't have plans to allow throttling of the extension host as you suggest. instead we now have the extension bisect to try find misbehaving extensions
