### ISSUE TITLE
Debugger does not connect in WSL but works fine in native Windows

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#134523]
_@connor4312 feel free to punt this over to the TypeScript team, I'm raising here as the debugger is unable to connect._

I use the debugger to debug an extension, in this case: https://github.com/styled-components/vscode-styled-components 
I need to debug a typescript language server plugin, so I load https://github.com/microsoft/typescript-styled-plugin into the same workspace and start  the debugger there too.

Basically the extension has a [port set](https://github.com/styled-components/vscode-styled-components/blob/master/.vscode/launch.json#L17) when it starts up. I got this from the [typescript docs](https://github.com/microsoft/TypeScript-wiki/blob/main/Debugging-Language-Service-in-VS-Code.md#debugging-tsserver-server-side). Then the styled plugin starts up with the same [port set](https://github.com/microsoft/typescript-styled-plugin/blob/main/.vscode/launch.json#L10) using `node attach`. 

On Windows the 2 connect, but on WSL it cannot connect. Is there some sort of isolation going on with extension launches? It looks like the open port is not being seen from the other debugger, or its not starting up properly at all.

Steps to reproduce:
- Clone: https://github.com/microsoft/typescript-styled-plugin
- Clone: https://github.com/styled-components/vscode-styled-components
- Open both in the same workspace
- npm/yarn install in both
- in the debug pane, click "Launch Extension"
- Then after a new VSCode instance has started up click Debug Styled Plugin
- on Windows, this connects fine

Gif of it working fine (on windows)
![native](https://user-images.githubusercontent.com/936006/135920875-62a8717d-d8ce-48cb-bb8e-ac08bb28dbda.gif)

## Breaking
- On WSL open the same workspace (or make a new one with the same 2 folders)
- in the debug pane, click "Launch Extension"
- Then after a new VSCode instance has started up click Debug Styled Plugin
- in WSL they don't connect

Here I do the same thing in WSL and it fails
![wsl](https://user-images.githubusercontent.com/936006/135921178-89cd1988-d316-40d4-a1bc-a5953ee8b4df.gif)

Error
`console.ts:137 [Extension Host] Error: Could not connect to debug target at http://localhost:9229: Could not find any debuggable target`

Version: 1.61.0-insider (system setup)
Commit: 4fbe0344a0cedaf2a04edef728c9a3f27777cc6c
Date: 2021-09-29T05:38:00.706Z
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by connor4312** [comment]
I tracked this to us not passing through the environment when launching the remote extension host -- it's set on the renderer window, but not passed all the way through:

https://github.com/microsoft/vscode/blob/6d7222d52412f7c6e557ae448795f834e48ba0a1/src/vs/workbench/services/extensions/common/remoteExtensionHost.ts#L112

Unlike the local process host

https://github.com/microsoft/vscode/blob/82b8de69a72653a00610ca08e1d3b56d88cfec8d/src/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.ts#L227

The clear fix is to use the ShellEnvironmentService (with some tweaks) but this is only accessible when running in the Electron sandbox. @bpasero what's the right direction to go here? My initial thought is that we'd need to add the configured `userEnv` on an environment somewhere, or make IShellEnvironmentService common and have an ElectronShellEnvironmentService, etc.

**Comment by connor4312** [comment]
I mean that currently the remoteExtensionHost lives in common. Maybe this is not the right place for it to live, I will ping him.

Yes, we want to resolve the remote shell always, since trying to use the local environment will undoubtedly cause issues, only user-specific overrides should be preserved in the remote.

**Comment by bpasero** [comment]
> Yes, we want to resolve the remote shell environment

We do that today.

**Comment by connor4312** [comment]
I put together a PR for that approach here, just adding another CLI option to pass the environment like we do other debug information, like the debugId: https://github.com/microsoft/vscode/pull/134586
