### ISSUE TITLE
Debugger doesn't start in remote linux

### ISSUE THREAD

**Issue by dixonqmg** [microsoft/vscode#134584]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.62
- OS Version:Windows 10, various linux versions

Steps to Reproduce:

1. At some point after 1.60 (not sure exactly which version is causing it) when I try to start a debugger in a remote linux session, nothing at all happens. Well, something happens - a debugger menu bar appears, but nothing is being printed in a terminal window, no processes get started, no errors that I could see in any of the logs/output windows. Not sure how to investigate it further, can try whatever. Attempted remedies: reinstalling remote part. Reinstalling local windows setup and remote part. Trying different remote servers. No effect whatsoever. 

Rolled back to 1.59.1 - immediately started to work, with absolutely no configuration changes.  
2.

**Comment by weinand** [comment]
What debugger are you using in the remote linux?

**Comment by weinand** [comment]
- What debugger are you starting remotely? gdb or python?
- How are you starting the debugger in a remote linux session?

**Comment by dixonqmg** [comment]
Then I select appropriate config in "run and debug" sidebar, and click the run button. All of it works just fine in 1.59, but doesn't do anything besides popping up debug toolbar in 1.61

**Comment by dixonqmg** [comment]
I assume it works for most people, otherwise we'd hear about it. I'd like to know if there're any steps I can do to try to debug the issue here?

Integrated terminal works fine

**Comment by dixonqmg** [comment]
It got fixed in one of the latest updates

**Comment by dixonqmg** [comment]
It got fixed in one of the latest updates

**Comment by weinand** [comment]
@dixonqmg thanks a lot for letting us know!
