### ISSUE TITLE
Inconsistent behavior of autoclosing tags

### ISSUE THREAD

**Issue by kiyutink** [microsoft/vscode#134516]
Issue Type: <b>Bug</b>

1. Type any jsx tag at the top of the file. The tag autocloses
2. Type any jsx tag inside other jsx code. The tag doesn't autoclose (check out the attached video)
https://user-images.githubusercontent.com/16495771/136247895-c1f88969-8e8d-444e-8582-d041a99bbb14.mov

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T11:59:27.195Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|16.00GB (1.47GB free)|
|Process Argv|cookbook --crash-reporter-id 18caba5a-0781-4274-a065-434f8fe159d9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
scratchpads|bue|0.0.7
vscode-eslint|dba|2.2.1
xml|Dot|2.5.1
gitlens|eam|11.6.0
prettier-vscode|esb|9.0.0
shell-format|fox|7.1.0
go|gol|0.28.1
terraform|has|2.15.0
svg|joc|1.4.12
vscode-scss|mrm|0.10.0
vscode-kubernetes-tools|ms-|1.3.3
vscode-commons|red|0.0.6
vscode-yaml|red|0.23.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
shellcheck|tim|0.16.2
vscode-todo-highlight|way|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis200:30374795
vsaa593:30376534

```

</details>

**Comment by IllusionMH** [comment]
There was a fix related to nested tags https://github.com/microsoft/TypeScript/issues/45802

Do you see this issue if you use TypeScript Nightly (not sure if Insiders already already has 4.5).
Can be done with https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next

**Comment by kiyutink** [comment]
@IllusionMH 
Typescript 4.5 indeed fixed the issue. Big thanks. 

I guess this can be closed. Does anybody have a hint as to when approx TS 4.5 will hit the stable build of VScode?

**Comment by mjbvz** [comment]
Thanks @IllusionMH! Closing as fixed upstream
