### ISSUE TITLE
Vertical terminal scroll bar can be small 

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#134513]
![image](https://user-images.githubusercontent.com/2193314/136246123-e1493dbe-2216-4c33-9a82-6ac230b4f6b3.png)

This is happening because the scrollable element adds `overflow: hidden` to terminal wrapper which has margin/padding. The fix here would be to add another element as a parent to terminal wrapper and add that as the scrollable element's element.

**Comment by Tyriar** [comment]
We should also have the content go to the very edge when the scrollable element is cutting it off:

![image](https://user-images.githubusercontent.com/2193314/136248544-60a28235-9ab6-404a-8c9a-2508005dc029.png)

**Comment by meganrogge** [comment]
@Tyriar I don't think this is what we want. I've spent many hours on this, can you give it a try?

My branch is merogge/scroll
![recording - 2021-10-15T125231 935](https://user-images.githubusercontent.com/29464607/137545858-53b65a33-546b-4973-97dc-b2933e8d8e26.gif)

**Comment by meganrogge** [comment]
This also happens when not using fixed dimensions
