### ISSUE TITLE
Opening with a fresh user data directory causes walkthrough theme to appear empty

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#134591]
Steps to Reproduce:

1. open vs code with a fresh user data directory `code-insiders --user-data-dir . --extensions-dir .`
2. :bug: first walkthrough content detail is empty

Going to the next step or reloading the window fixes it, but it's not a great start for new users.

<img width="1024" alt="CleanShot 2021-10-07 at 10 12 14@2x" src="https://user-images.githubusercontent.com/35271042/136432388-abe56b6e-56a3-458f-b9d5-12a045c6918d.png">

Version: 1.61.0-insider (Universal)
Commit: 2dc8b9580809148e312356852affc4b8d4feb7da
Date: 2021-10-06T08:24:49.272Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0

**Comment by JacksonKearl** [comment]
I believe this is now fixed, made some improvements to reduce rerenderings.
