### ISSUE TITLE
Display warning for why toggle developer tools isn't working

### ISSUE THREAD

**Issue by Suven-p** [microsoft/vscode#134542]
Toggle developer tools from the help menu works only when it can be enabled via keyboard binding. 
Would it be possible to either:
1. Keybinding works only in development mode but the command itself can be accessed via the help menu. It seems to me that `Reload window` keybinding works only in development mode but it can also be accessed from the command palette.
2. Display some form of message(maybe a dialog box) describing why toggle developer tools doesn't work from the help menu.

[This comment from alexdima](https://github.com/microsoft/vscode/issues/40389#issuecomment-352404326) in #40389 mentions that menus can't make decisions requiring context. Not sure if it applies here since the button remains the same and showDialog is triggered after pressing the button.
This can be trivially fixed by adding  additional keybinding. It is also not commonly used by non-developers. It would still be nice to have some indication that it doesn't work because it is designed not to and not because vs code isn't responding or has a bug.

**Comment by sbatten** [comment]
@Suven-p what platform are you on?

**Comment by Suven-p** [comment]
Linux

**Comment by sbatten** [comment]
Okay, I am not sure what your repro is. I tried activating the dev tools from the help menu, and it works. What are the repro steps for it not to work?

**Comment by Suven-p** [comment]
Well, it was 10 months ago so I dont really remember :( sorry. Closing this issue.

**Comment by sbatten** [comment]
Sorry we got to this so late, our tooling must have resurrected it from the abyss
