### ISSUE TITLE
Notebooks - Creating new notebook taking a long time

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#134526]
- VS Code Version: 1.61.0-insider
- OS Version: Windows

I was screen recording for a different reason and a new notebook was taking a long time to open.

![notebook load time long](https://user-images.githubusercontent.com/19276747/136273274-ee2deb19-3004-437d-96e2-93bb95620a65.gif)
 
Grabbed the logs and it was a bit faster this second time around but still slower than anticipated
[Long Notebook Load Time.zip](https://github.com/microsoft/vscode/files/7296765/Long.Notebook.Load.Time.zip)

**Comment by roblourens** [comment]
This looks like effectively 3.5s to activate the dotnet interactive extension, just to require its file. Does this still happen @claudiaregio? If so we can try the test that deepak suggests
