### ISSUE TITLE
Incorrect HTML syntax highlight

### ISSUE THREAD

**Issue by infinnie** [Microsoft/vscode#13455]
- VSCode Version: 1.6.0
- OS Version: 10.0.10586

Steps to Reproduce:

1. Write an HTML file with elements whose tag names contain a `-` character.
2. Only the letters to the left of the `-` is highlighted as the tag name, and other letters, to its right and the `-` itself, is highlighted as if they were attributes.

![10](https://cloud.githubusercontent.com/assets/8168391/19255243/630e81ac-8f8e-11e6-8db3-4a596cad4b4e.png)

**Comment by isidorn** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/13448
