### ISSUE TITLE
The Number replacements its wrong.

### ISSUE THREAD

**Issue by lfrasae** [microsoft/vscode#134581]
Issue Type: <b>Bug</b>

The Number replacements its wrong.

When a code segment is selected to replace it, the number of matches is erroneous and variable.

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz (2 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|4.00GB (1.13GB free)|
|Process Argv|--crash-reporter-id 24c5780d-ee2b-45a7-9538-778eef879c00|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
phpserver|bra|3.0.2
vscode-html-css|ecm|1.10.2
php-debug|fel|1.19.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
HTMLHint|mka|0.10.0
vscode-language-pack-es|MS-|1.60.4
notepadplusplus-keybindings|ms-|1.0.7
debugger-for-chrome|msj|4.13.0
java|red|0.82.0
php-debug|rob|1.14.0
php-debug|tia|0.1.6
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.5
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.0
html-css-class-completion|Zig|1.20.0

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you please provide short example of content, search query (and settings case, boundries etc.) to reproduce problem and expected result.
