### ISSUE TITLE
Find all references, Go to definition, etc. are not working in Javascript

### ISSUE THREAD

**Issue by atsats** [Microsoft/vscode#13452]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: dbaeumer.vscode-eslint-1.0.7, ivangabriele.vscode-tfs-0.5.2, ms-vscode.csharp-1.4.1, msjsdiag.debugger-for-chrome-1.1.0, vsmobile.cordova-tools-1.2.3

Steps to Reproduce:

1. Open any JavaScript file with functions
2. Find a function invocation, right click on "Go to definition", nothing happens. Previous release went to definition.

**Comment by isidorn** [comment]
Works for me, assigning to @waderyan to investigate deeper

**Comment by atsats** [comment]
I'd like to downgrade to the previous release to see if it resolves the issue, where can I find previous VS Code releases?

I also tried with the Insider build and the issue happens in that version. 

No changes were done on this machine except the upgrade to VS Code yesterday, the feature was working with no issues in the preceding version.

**Comment by waderyan** [comment]
@atsats this is working for me. Can you share your workspace so I can recreate what you are seeing? 

You can install a separate build per [this comment](https://github.com/Microsoft/vscode/issues/11796#issuecomment-246267049).

**Comment by atsats** [comment]
When I reverted back to 1.5.0 stable, it worked right away. Unfortunately, I can't share the workspace as this is a confidential project for a client. I will try on another machine and also try to create a minimal project in which this issue recurs and report back. Give me about one day.

**Comment by waderyan** [comment]
@atsats thank you. Let me know. I cannot recreate this on my machine but I believe this happens a non-trivial amount of time.

**Comment by atsats** [comment]
Sorry for the delay, I will let you know by end of day if I can recreate

**Comment by atsats** [comment]
Hi Wade -

I think I found the issue.

I compared the non-working dev machine running 1.6.1 with another machine freshly installed with 1.6.1. I originally suspected it was one of the installed extensions on the non-working machine, so I installed each extension in turn on the freshly installed machine, but could not recreate the issue.

Then I noticed a small icon in the Code status bar prompting me to create a jsconfig.json file for a "better experience" - I did and, again, on the fresh install machine, it worked fine. 

I then compared the jsconfig.json file with the one I had on the non-working machine and they were different. The latter had a timestamp of 4/18/2016 so it's been there for a while. When I copied the file to the fresh-install machine, it stopped working as well. So, here's what I suspect:

_The latest version of Code uses any existing jsconfig.json and this may prevent the "Get Def.." functionality from working properly if the file has an applicable exclude statement. The last version of Code that worked for me was 1.5, so maybe you added this support in 1.6?_

Here are the contents of my file if you need them:

`{
    "exclude": [
        "node_modules",
        "www/scripts",
        "www/legacy",
    ]    
}`

Anyway, my issue is resolved now and I'm running the latest again. Thanks for the follow-up!
