### ISSUE TITLE
No file type icon preview in Windows Explorer

### ISSUE THREAD

**Issue by kadhirr** [microsoft/vscode#134543]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.2
- OS Version: Windows 10 20H2

![vscode error](https://user-images.githubusercontent.com/53949365/136311872-f1da92e8-19d4-4ad2-bb56-595f1c816bc8.jpg)

Cannot find File Icon Previews with the specific file type.
I tried a complete reinstall after clearing all data. I have installed custom file icon themes, but I'm currently using the Seti theme.
I have included a photo of the file icon for a python file. I have Python 3.9 installed.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/105681
