### ISSUE TITLE
C# error detection does not work at all in 1.6

### ISSUE THREAD

**Issue by rudolfdobias** [Microsoft/vscode#13453]
- VSCode Version: 1.6
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Upgraded from 1.5.3 to 1.6. by deb package 
2. Reopened my last project
3. Error detection does literally nothing. I can write "aownrafucktheworldqwerrtoiyl .<[}}#$%}@" in the code, nothing happens, no error detected.
4. Reinstall C# extension - same result.
5. Restart computer - same result.
6. Open any other project - same result
7. Nope, downgrading to 1.5.3, see you next time ...

Regards

**Comment by chrmarti** [comment]
@rudolfdobias What does the Output panel (Ctrl+Shift+U) show in the Omnisharp Log?

**Comment by rudolfdobias** [comment]
Unfortunatelly I already downgraded so I cannot post exactly...
There was omnisharp downloading, installation, starting server and then request processing. It looked ok ... 

I'll install it again in order to show you exact log.

**Comment by haydenmc** [comment]
I'm experiencing this issue on a couple of different machines (both Windows 10 RS2 builds, 14951 on my current box). I edit some text, Omnisharp errors/suggestions appear (green + red squigglies), but then about a second later, they all go away until I type again.

Omnisharp log looks like this:
```
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 1ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 9ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 4ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /codecheck: 200 8ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 6ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /codecheck: 200 85ms
```

I notice the second `/codecheck` (last line in the above log) is when the code error/suggestion marks disappear.

**Comment by chrmarti** [comment]
Thanks @haydenmc, that looks like a different problem. Could you open an issue for the C# extension: https://github.com/OmniSharp/omnisharp-vscode/issues

@rudolfdobias I'm closing this one for now, please reopen with more information.
