### ISSUE TITLE
[feature request] add partially choosed relative function

### ISSUE THREAD

**Issue by cty8998** [Microsoft/vscode#13469]
- VSCode Version: v1.6
- OS Version: windows 10

I prefer to format css/scss partially(expended or compact), but it seems the vscode can just format globally

**Comment by jrieken** [comment]
@cty8998 Did you try having selection and then pressing format? AFAIK css/scss support range formatting

**Comment by aeschli** [comment]
VSCode doesn't support formatting css/scss out-of-the box. There are extensions that provide it, e.g. https://marketplace.visualstudio.com/items?itemName=aeschli.vscode-css-formatter.
The latter one supports range formatting (make a selection and invoke 'Format' from the context menu). If you use a different extension that lacks formatting a range, please file an issue against that extension.

**Comment by cty8998** [comment]
Thanks @aeschli @jrieken  I got it, and it will be appreciate if **vscode can bind some extension commend/or keyboard shortcuts choosed by myself to context menu.** : )
e.g.
[sublime context menu screenshot](http://7xrktr.com1.z0.glb.clouddn.com/sublime%20context%20menu.png)

**Comment by jrieken** [comment]
extensions can do that: https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus
