### ISSUE TITLE
Bracket Pair line is wrongly displayed to the right of Python code

### ISSUE THREAD

**Issue by mystiquewolf** [microsoft/vscode#134677]
Issue Type: <b>Bug</b>

When the Bracket Pair Colorizer extension was enabled and the VS Code native feature disabled the lines connecting the brackets were to the left of the code and it was surrounding the code inside them. Now with the native feature enabled and the extension disabled the bracket pair lines is to the right of the code and does not surround the code. Please see the screenshots below.

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:11:02.929Z)
OS version: Linux x64 5.11.0-37-lowlatency
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|7.64GB (0.45GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 9cc3662d-ccfb-4569-83fb-26560f111f8b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasmawayland|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.2.2
laravel-extra-intellisense|ami|0.6.1
vscode-diff-viewer|cap|1.1.14
path-intellisense|chr|2.4.0
gitignore|cod|0.7.0
laravel-goto-view|cod|1.3.4
vscode-eslint|dba|2.2.1
gitlens|eam|11.6.1
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
vscode-firefox-debug|fir|2.9.4
shell-format|fox|7.1.0
copilot|Git|1.5.2993
gc-excelviewer|Gra|3.0.44
output-colorizer|IBM|0.1.2
icon-fonts|idl|2.5.2
vscode-colorize|kam|0.11.1
vscode-gutter-preview|kis|0.27.1
vscode-jumpy|krn|1.0.2
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.17.0
csharp|ms-|1.23.15
python|ms-|2021.10.1317843341
vscode-pylance|ms-|2021.10.0
jupyter|ms-|2021.9.1001312534
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.202.1
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
live-server|ms-|0.2.9
es6-css-minify|olb|3.3.2
laravel-blade|one|1.25.0
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.13.0
vscode-versionlens|pfl|1.0.9
bash-debug|rog|0.3.9
laravel-artisan|rya|0.0.28
partial-diff|ryu|1.4.3
vscode-javascript-booster|sbu|14.0.1
laravel-goto-controller|ste|0.0.15
code-spell-checker|str|2.0.9
teamhub|Tea|14.0.5
vscode-pets|ton|1.8.1
sort-lines|Tyr|1.9.0
vscode-icons|vsc|11.6.0
local-history|xyz|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30378364
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis400:30374798
vsaa593cf:30376535

```

</details>

**Comment by crash5** [comment]
duplicate/related: https://github.com/microsoft/vscode/issues/134644
