### ISSUE TITLE
[html] Multivalue autocompletion of attribute not working

### ISSUE THREAD

**Issue by bijenderk82** [Microsoft/vscode#13465]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:28:55.412Z)
- OS Version: Darwin x64 15.6.0
- Extensions: PeterJausovec.vscode-docker-0.0.6, Tyriar.terminal-tabs-0.0.6, abusaidm.html-snippets-0.0.16, dbaeumer.vscode-eslint-1.0.7, dkundel.vscode-npm-source-0.0.3, eg2.vscode-npm-script-0.0.20, formulahendry.terminal-0.0.5, jaymorrow.NodeAssertionSnippets-0.1.0, johnpapa.Angular1-0.1.16, msjsdiag.debugger-for-chrome-1.1.0, remcoros.startanyshell-0.3.1, robinbentley.sass-indented-1.1.0, saviorisdead.Theme-GitHubCleanWhite-0.0.3, sidthesloth.html5-boilerplate-1.0.1, vsmobile.cordova-tools-1.2.3, waderyan.gitblame-1.3.0, xabikos.JavaScriptSnippets-1.2.0, zhuangtongfa.Material-theme-1.0.3

Steps to Reproduce:

1. Added sandbox attribute to iframe element
2. First selected "allow-forms"
3. Then want to select one more value "allow-modals" but unable to do.

In the previous version, it was working fine.

**Comment by aeschli** [comment]
fixed
