### ISSUE TITLE
Unicode characters ↮ (U+21AE) and ≢ (U+2262) not rendered correctly in text editor

### ISSUE THREAD

**Issue by Erik0x42** [microsoft/vscode#134641]
Issue Type: <b>Bug</b>

1. Insert unicode characters ↮ and ≢ into text editor (U+21AE and U+2262 respectively)
2. Observe that the symbols appear to be exploded, each symbol into two component symbols (component glyphs presumably?)
   - a side effect is that the right-most glyph overlaps with next character (instead of being merged with left-most glyph)

Same issue confirmed in markdown preview pane.

![image](https://user-images.githubusercontent.com/43793099/136529148-472caade-1353-4355-9856-eaad1715cec4.png)

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.11GB free)|
|Process Argv|-redacted-|
|Screen Reader|no|
|VM|80%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30378365
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis300:30374797
vsaa593:30376534

```

</details>

**Comment by alexdima** [comment]
@Erik0x42 I think this might depend on the font once you enable ligatures. Have you tried different fonts. Here I found somewhat better support for ≢ in Cascadia Code:

![image](https://user-images.githubusercontent.com/5047891/136741517-53fc765e-003b-494d-a66d-7accfb7b24d2.png)

**Comment by Erik0x42** [comment]
I believe this open issue covers the problem: 
https://bugs.chromium.org/p/chromium/issues/detail?id=591346

This duplicate and closed issue mentions one of the specific unicode characters (≢ (U+2262), HTML entity `&#8802;`) :
https://bugs.chromium.org/p/chromium/issues/detail?id=1230181

**Comment by alexdima** [comment]
The issue has been reported upstream. Once it is addressed upstream, we will automatically benefit from the resolution. There is no need to keep this issue open on our side.
