### ISSUE TITLE
`Toggle Size to Content Width` freezes after a few times

### ISSUE THREAD

**Issue by thanhph111** [microsoft/vscode#134623]
The <kbd>Toggle Size to Content Width</kbd> can only be toggled a few times, before freezing completely. Resizing terminal could reset it.

https://user-images.githubusercontent.com/60842560/136497808-a2499e8f-304d-43ff-9a2f-7c2cc04a4035.mp4

Does this issue occur when all extensions are disabled?: Yes

System info:
```
Version: 1.61.0
Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date: 2021-10-07T18:11:02.929Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-37-generic
```

**Comment by thanhph111** [comment]
@meganrogge Thank you for your detailed explanation. I did test on the insider version, the blur seems to decreased with smaller canvas required but this freezing issue still happens all the time. Moreover, the issue is only on _Linux_ so I'm not sure the explanation is quite sufficient to describe this. Let me know if there's anything I missed, thanks again.

**Comment by meganrogge** [comment]
This actually is working by design - when you copy and paste, it includes newline line endings that will indicate to the terminal that line isn't wrapped.

**Comment by Tyriar** [comment]
Because of the way this feature works where it stretches the canvas to the size of the content we are limited by the canvas API. As a compromise I'm going to add a cap to the number of columns the terminal can take up.
