### ISSUE TITLE
subset of cursor keys randomly stop working

### ISSUE THREAD

**Issue by PaulForgey-Discovery** [microsoft/vscode#134669]
Issue Type: <b>Bug</b>

When using the editor, a subset of arrow keys still stop working. For example, sometimes arrow right and delete stop working, but the rest still function.

The only apparent way to clear the state is to restart Visual Studio Code.

This happens very infrequently and I cannot reproduce it at will. Sometimes I will go for months without a reproduction.

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:11:58.853Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (12.69GB free)|
|Process Argv|--crash-reporter-id bf630b71-a464-49ff-98a3-dfd0c541fb6a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
go-group-imports|ale|1.1.4
go|gol|0.28.1
vscode-docker|ms-|1.17.0
python|ms-|2021.10.1317843341
vscode-pylance|ms-|2021.10.0
jupyter|ms-|2021.9.1001312534
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.202.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.23.0

</details>

**Comment by alexdima** [comment]
When this reproduces, please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by PaulForgey-Discovery** [comment]
it reproduced again, but toggling the keyboard shortcuts troubleshooting unjammed it, so nothing useful came out.

**Comment by alexdima** [comment]
@PaulForgey-Discovery Thank you for following up. Please keep an eye out and if you find some hints / steps that might reproduce please don't hesitate to reach out. Thanks again!
