### ISSUE TITLE
Discoverability of Show Running Extensions

### ISSUE THREAD

**Issue by lychung7** [microsoft/vscode#134673]
# Discoverability of Show Running Extensions

## Idea 1: At the end of Extension Bisect

- When Extension Bisect hasn't identified an extension, we could direct them to Show Running Extensions
![image](https://user-images.githubusercontent.com/60596156/136466867-ae4f1474-87df-41b5-b97f-15be624df90b.png)

- When a user clicks Stop Bisect, a second notification can appear for users to discover Show Running Extensions.
![Frame 21](https://user-images.githubusercontent.com/60596156/136466761-0bb8d006-c43a-49f5-8d85-fa104cae9eaf.png)
![Frame 22](https://user-images.githubusercontent.com/60596156/136467155-d9413840-acde-4ae6-9ee4-28d78fb05f72.png)

## Idea 2: Link from Extensions Sidebar

- Top ellipsis menu item
![Top ellipsis menu](https://user-images.githubusercontent.com/60596156/136467771-c8ef1e28-381c-4785-92c2-58e9fcfe7000.png)

- Start Extension Host Profile menu item from the Gear icon. This would open up the Show Running Extensions tab and automatically start profiling. 
![Gear menu](https://user-images.githubusercontent.com/60596156/136467825-d1f3780b-a362-4810-adbc-34ca600b04b5.png)

- We could put a link to Start Extension Host Profile in the dialog that shows on hover over the extension row. 
![Link in pop up](https://user-images.githubusercontent.com/60596156/136467856-393fd98d-bdff-4c31-a6eb-b82d0a9d2499.png)

- When the entry point is from the Start Extension Host Profile link, we can indicate via a notification that profiling has started and they can click on the Stop icon to stop profiling.
![Start profile](https://user-images.githubusercontent.com/60596156/136467916-65a67625-abef-4804-a494-e40fe747f223.png)

## Idea 3: Filter installed extensions

- Be able to filter the list of installed extensions to those that are running. They can then Start Extension Host from the dialog on hover or from the Gear menu item.
 
https://user-images.githubusercontent.com/60596156/136601115-dac3f0cc-f164-48ee-897d-7a74346041f4.mp4

## Idea 4: View within the Extensions Sidebar

- Make 'Running' an option for sidebar view. We could put the actions in the section header and have the profile information show up next to the activation time. This would replace the original running extensions view that is within its own tab. Once profiling is done, the CPU file will show. 

https://user-images.githubusercontent.com/60596156/136601387-0ca7df69-9530-4d3e-9cd9-19de771b39c6.mp4

## Idea 5: Issue Reporter (WIP)

- Will include this idea soon.

**Comment by alexdima** [comment]
Thank you, I found the idea 2 to be the least invasive way to make this more discoverable, so I've added an entry in the menu above "Start Extension Bisect":

<img width="538" alt="image" src="https://user-images.githubusercontent.com/5047891/156380597-6ad553bf-555a-4a24-8413-7299bb0d65dd.png">
