### ISSUE TITLE
I want something like webstorm's shortcut key ctrl+w (select successively increasing code blocks)

### ISSUE THREAD

**Issue by bluewaitor** [Microsoft/vscode#13466]
#- VSCode Version: 1.6.0
- OS Version: win7

Steps to Reproduce:

1. 
2. 

As the title

**Comment by chiyx** [comment]
agreed!

**Comment by jrieken** [comment]
Try `F1 > [Shrink|Expand] Selection`

**Comment by bluewaitor** [comment]
Thanks. But I think it expand too fast.

**Comment by jrieken** [comment]
Shortcomings are tracked here #4795
