### ISSUE TITLE
'Initialize Repository' welcome view should not be shown in virtual workspace

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#134613]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.61
- OS Version: Windows 10

Steps to Reproduce:

1. Open an Azure Repo in the GitHub Repositories extension
2. Open the SCM view
3. 🐛 we show a welcome view saying that there's no git repository in this folder
![image](https://user-images.githubusercontent.com/30305945/136475680-7dc3c19c-2876-4456-85b7-e9cde5cd235f.png)

Clicking 'Initialize Repository' leads to 

![image](https://user-images.githubusercontent.com/30305945/136475870-bb53da7a-7d20-4140-871d-8bbf22c7d14b.png)

```
Validating found git in: C:\Program Files\Git\cmd\git.exe
Using git 2.32.0.windows.2 from C:\Program Files\Git\cmd\git.exe
Opening repository for path='\microsoft\OS\os' failed; ex=spawn C:\Program Files\Git\cmd\git.exe ENOENT {
  "gitErrorCode": "NotAGitRepository"
}Error: spawn C:\Program Files\Git\cmd\git.exe ENOENT
    at Process.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
> git init
> git init
```

**Comment by lszomoru** [comment]
This has been addressed.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/3372902/140522992-aa5122f3-d98f-4c50-a2ea-cc584814bc54.png">
