### ISSUE TITLE
Shift enter to empty cell doesn't place the new cell in a visible location on screen

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#134607]
Not 100% sure what's happening here, but it might just be the output arriving and pushing down the focused cell. But it's not a good shift enter experience as my cell focus is on the next cell, but I can't see it on screen at all. 

![ShiftEnterFocus](https://user-images.githubusercontent.com/812783/136091498-e0389f62-1c1a-4825-86a9-f2e631fafa98.gif)

**Comment by rchiodo** [comment]
This is a VS code core issue.

**Comment by rebornix** [comment]
There is another request https://github.com/microsoft/vscode-jupyter/issues/5186 which asks for exactly the opposite.

**Comment by roblourens** [comment]
Exactly, but Jupyter lab's behavior doesn't make sense to me

**Comment by rebornix** [comment]
Playing around this again, what VS Code does now is, shift+enter reveals cell B in center and focuses it, since it's focused cell, the height change of cell A won't change the visual position of cell B. @roblourens correct me if it's not the behavior you would expect.
