### ISSUE TITLE
run button is missing

### ISSUE THREAD

**Issue by Fender1992** [microsoft/vscode#134656]
Idk what happened but a couple days ago I noticed that the run button in the top right corner went missing but it remained in all the old files I created in VSC while using py. Additionally, all new files I create auto switches to plain text. How do I fix. please hel
![Screenshot 2021-10-08 085216](https://user-images.githubusercontent.com/92167269/136569024-0de0fd2d-3802-47e6-91f9-fa4770b5dacf.png)
p.

**Comment by weinand** [comment]
@isidorn I just tried to verify the context key `resourceLangId` for untitled files and I see the same bug: in the status bar "Python" is shown (because I've manually assigned the language to the untitled file), but there is no "Run" button.
If I use `editorLangId` in Python's "when" clause for the "Run" contribution, it works fine.

@alexdima could you please comment on my [question](https://github.com/microsoft/vscode/issues/134656#issuecomment-939923011) from above.

**Comment by alexdima** [comment]
@weinand Sure, here is my understanding:

* `editorLangId` is the language id of a text buffer shown inside a code editor. This is something that I own code-wise and will be available to contexts where the focus is a descendant of a code editor widget dom node. This is maintained [here](https://github.com/microsoft/vscode/blob/38422cb1c524bf28bae0ffd6bff91c235f7fdb84/src/vs/editor/browser/widget/codeEditorWidget.ts#L1958).
* From my understanding, `resourceLangId` is a more generic workbench concept that exists for all kind of things, not just for code editors. For example, I think even files shown in the explorer have this context key for handling things like right clicking where you can add a context menu item for typescript files, but not for javascript files. This would be available even without having a code editor or a text model. I am not sure who exactly owns this, I think @jrieken or @bpasero . In any case, it looks like `resourceLangId` is always using [the guessed language for a resource](https://github.com/microsoft/vscode/blob/690de80fbd3d5f33ffb7efd849a3c1ef13064be9/src/vs/workbench/common/resources.ts#L70), and does not check if there is a text model instantiated, if the associated language is different than the guessed language. It also doesn't check if the language has been overriden by the user using the status bar. I remember seeing a recent PR mentioning where the workbench stores the user choices (I think in an EditorModel class somewhere), but I lost that code pointer.
