### ISSUE TITLE
Add Wayland Electron Arguments to argv.json

### ISSUE THREAD

**Issue by sclel016** [microsoft/vscode#134612]
This is half feature, half bug report. In a full Wayland environment `code` fails to launch. That's probably expected as the packaged `code` install doesn't use system electron and thus ignores `electron-flags.conf`.

The feature request is pretty simple. Can you please parse the following extra arguments in `argv.json` and forward to electron?

- `--enable-features=UseOzonePlatform`
- `--ozone-platform=wayland`

Alternatively`code` could simply parse the electron flags in `$XDG_CONFIG/electron-flags.conf`. Either of these options would help make `code` much simpler to use in a Wayland environment.

**Comment by Yash621** [comment]
@sclel016  can I work on this ?

**Comment by sclel016** [comment]
By all means, that would be great!

**Comment by numfin** [comment]
@Yash621 any progress?

**Comment by deepak1556** [comment]
Refs https://github.com/microsoft/vscode/pull/135191#issuecomment-1216527129
