### ISSUE TITLE
Allow kernel picker textbox to accept paths

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#134604]
Based on the survey monkey feedback we have received, some users have been attempting to add paths to the kernel picker textbox when their environment does not show up in the quick pick. 

Would be nice if the kernel picker worked similarly to the select interpreter command

**Comment by rchiodo** [comment]
This requires changes to the select kernel quick pick

Probably needs an API change too. What does a path mean to say .NET?
