### ISSUE TITLE
Type 'IQuickPickSeparator | Awaited<T>' is not assignable to type 'T | undefined'

### ISSUE THREAD

**Issue by wuhaih** [microsoft/vscode#134639]
[watch-client    ] [16:34:03] Error: /Users/whh2017/vscode/ds-vscode/src/vs/base/parts/quickinput/browser/quickInput.ts(1445,16): Expected 1 type arguments, but got 2.
[watch-client    ] [16:34:03] Error: /Users/whh2017/vscode/ds-vscode/src/vs/base/parts/quickinput/browser/quickInput.ts(1447,6): Type 'IQuickPickSeparator | Awaited<T>' is not assignable to type 'T | undefined'.
[watch-client    ]   Type 'IQuickPickSeparator' is not assignable to type 'T'.
[watch-client    ]     'T' could be instantiated with an arbitrary type which could be unrelated to 'IQuickPickSeparator'.
[watch-client    ] [16:34:03] Error: /Users/whh2017/vscode/ds-vscode/src/vs/base/parts/quickinput/browser/quickInput.ts(1449,6): Type 'IQuickPickSeparator | Awaited<T>' is not assignable to type 'readonly (IQuickPickSeparator | T)[]'.
[watch-client    ]   Type 'IQuickPickSeparator' is missing the following properties from type 'readonly (IQuickPickSeparator | T)[]': length, concat, join, slice, and 18 more.
[watch-client    ] [16:34:03] Error: /Users/whh2017/vscode/ds-vscode/src/vs/base/parts/quickinput/browser/quickInput.ts(1451,35): Property 'filter' does not exist on type 'IQuickPickSeparator | Awaited<T>'.
[watch-client    ]   Property 'filter' does not exist on type 'IQuickPickSeparator'.
[watch-client    ] [16:34:03] Error: /Users/whh2017/vscode/ds-vscode/src/vs/base/parts/quickinput/browser/quickInput.ts(1451,42): Parameter 'item' implicitly has an 'any' type.
[watch-client    ] [16:34:03] Error: /Users/whh2017/vscode/ds-vscode/src/vs/platform/diagnostics/node/diagnosticsService.ts(243,22): Expected 1 type arguments, but got 2.
[watch-client    ] [16:34:03] Error: /Users/whh2017/vscode/ds-vscode/src/vs/platform/diagnostics/node/diagnosticsService.ts(244,8): Type '{ name: string; cmd: string; pid: number; ppid: number; load: number; mem: number; children?: ProcessItem[] | undefined; }' must have a '[Symbol.iterator]()' method that returns an iterator.
[watch-client    ] [16:34:03] Finished compilation with 7 errors after 209959 ms

VS Code Version: 1.60.2
OS Version: macOS Big Sur 11.6
Steps to Reproduce:

cd vscode
yarn
Try to yarn watch vscode

**Comment by TylerLeonhardt** [comment]
Hi 👋 it looks like our CI isn't hitting this issue so my guess is that you're just in a bad state somehow.

Try pulling the latest changes and try again. If it still happens, you may need to totally reset the state of the repo (`git clean -fdx` or re clone).

Make sure that you're using the workspace version of TypeScript and not whatever version is globally installed.
