### ISSUE TITLE
"Visual Studio Code - Insiders" needs to be updated on macOS Monterey

### ISSUE THREAD

**Issue by targos** [microsoft/vscode#134635]
Does this issue occur when all extensions are disabled?: Don't know. The message appears only once.

- VS Code Version:
- OS Version:
Version: 1.62.0-insider
Commit: 0dae77d06e33eaf1616cc1a53d77e717b284a626
Date: 2021-10-08T05:22:27.408Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.1.0

Steps to Reproduce:

1. Install the latest insiders version and run it on macOS Monterey (v12.0 beta)

![image](https://user-images.githubusercontent.com/2352663/136518792-72d6e59b-97a7-4cde-b2b6-190c48d95444.png)

It's not clear what needs to be done. I tried to click on "Learn more..." but the dialog disappeared and nothing else was opened. The dialog does not open again if I restart vscode.

**Comment by rorymurdock** [comment]
Fresh install on Monty RC and no prompt, as soon as I install the python extension and it finds all versions the prompt is triggered. VSCode v1.61.1
![image](https://user-images.githubusercontent.com/9400108/137850324-150884ec-2369-4871-89e5-84925e36e6cf.png)

**Comment by deepak1556** [comment]
It looks like with `12.1 beta` the notification is not aggressive, I am only able to trigger it once per application install. Looks like the notification is now cached per bundle id, I don't see any explicit mention of this in the release notes. Anyone else seeing the same behavior ?

Also the python extension team has landed a fix in their nightly insiders, please give it a try and check if the notification pops-up on activating the extension or trying to select the interpreter. Would be great to get it tested from users on `12.0.1`

```
Steps:
1) Download the Insiders version of the Python extension (“python.insidersChannel”: “daily” in your user settings), make sure it’s 2021.12.1418235384-dev or later
2) Activate the Python extension
3) Check if the "Visual Studio Code - Insiders" needs to be updated dialog appears
4) If it appears, use the Python: Clear Internal Extension Cache command and reload VS Code
5) Activate the Python extension, wait for interpreter discovery, check if the dialog appears
6) When selecting an interpreter (either by clicking the interpreter in the bottom-left corner or using the Python: Select Interpreter command), check that /usr/bin/python doesn’t appear in the list of interpreters
```

/cc @kimadeline

**Comment by CryptoKingoftheheavens** [comment]
@deepak1556 I just updated my mac and had this error coming up in VSC. Your instructions helped in fixing this on 12.0.1. Thanks

**Comment by StefanScherer** [comment]
Hey, Docker team here, we also have a few reports that "Docker" needs to be updated popup appears on macOS Monterey sometimes. This happens when a user clicks on our "Open in Visual Studio Code" button from the Docker Desktop UI for a Docker Compose app.
We investigated the problem and narrowed it down. When this popup appears Docker Desktop has called the "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code" bash script.


<img width="1280" alt="dd-vscode-bash-calls-python" src="https://user-images.githubusercontent.com/207759/142721238-975586b0-9672-43c1-b450-fedfd0692fef.png">

Looking into the bash script shows me the usage of `python` in the `realpath()` function. And macOS Monterey has Python 2.7.18 installed. I assume this function needs some attention.

```
#!/usr/bin/env bash
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

function realpath() { python -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0"; }
CONTENTS="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
ELECTRON="$CONTENTS/MacOS/Electron"
CLI="$CONTENTS/Resources/app/out/cli.js"
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --ms-enable-electron-run-as-node "$@"
exit $?
```

**Comment by aerohoff** [comment]
Modifying this file to "python3" and removing the resulting quarantine attribute seems to be working for me.

**Comment by emmahsax** [comment]
I know everyone here is onto leads to fix, but I just wanted to say this isn't just with VS Code - Insiders... it also pops up with the official version.

**Comment by leotm** [comment]
For what its worth n anyone else landing here on Monterey 12.3 in similar situation, but downgrading ain't no option atm

```sh
brew install visual-studio-code
brew install visual-studio-code-insiders

code
/opt/homebrew/bin/code: line 6: python: command not found
/opt/homebrew/bin/code: line 10: ./MacOS/Electron: No such file or directory

code-insiders
/usr/local/bin/code-insiders: line 6: python: command not found
/usr/local/bin/code-insiders: line 10: ./MacOS/Electron: No such file or directory

# panic 😅
```

Cheers to above 🍺

```diff
# vim /opt/homebrew/bin/code
# vim /usr/local/bin/code-insiders
- function realpath() { python -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0"; }
+ function realpath() { python3 -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0"; }
CONTENTS="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
ELECTRON="$CONTENTS/MacOS/Electron"
CLI="$CONTENTS/Resources/app/out/cli.js"
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --ms-enable-electron-run-as-node "$@"
exit $?
```

Got me finally vimming and back up n running, befo updates ref'ed above land on Homebrew

**Comment by pepelsbey** [comment]
> I know everyone here is onto leads to fix, but I just wanted to say this isn't just with VS Code - Insiders... it also pops up with the official version.

Yes, it’s happening to me in the stable VS Code 1.64.2 on macOS 12.2.1

**Comment by WardsParadox** [comment]
As of Monterey Beta 12.3, python2 is removed.
the `/usr/bin/python3` stub is just that. If you have installed the xcode command line tools you'll get a python3 build. If not it'll just prompt and should not be used.

Perhaps this should be converted to pure shell?

**Comment by mesqueeb** [comment]
For me it was:
```
nano /usr/local/bin/code
```
and then change `python -c` to `python3 -c` in that file.

However, please note you always need to redo this after certain updates. Not sure if it's VSCode updates or macOS updates. But I already had to do this same thing twice so far!

**Comment by spaquet** [comment]
We can edit the code file and replace by:
```
#!/usr/bin/env bash
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

function realpath() {
  if [[ ! -z $(which python3 | grep "/python3") ]]; then
    # python3 is installed and will be used
    python3 -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0";
  elif [[ ! -z $(which python | grep "/python") ]]; then
    # Didn't find python3, let's try python
    python -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0";
  else
    # Python is not installed at all. Exit with error.
    echo "Python is not installed."
    exit
  fi
}

CONTENTS="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
ELECTRON="$CONTENTS/MacOS/Electron"
CLI="$CONTENTS/Resources/app/out/cli.js"
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --ms-enable-electron-run-as-node "$@"
exit $?
```
That actually should be the code used by VSCode as it checks for either python3 or python and returns an error message when none is installed on the machine.

**Comment by WardsParadox** [comment]
If you use the changes mentioned by @aimileus (https://github.com/microsoft/vscode/commit/fc8a61280bf880d384278bc98d907a1e04bd6cfd) it works perfectly, no python needed at all.
