### ISSUE TITLE
Long Compose Layers on rendering png

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#134610]
Does this issue occur when all extensions are disabled?: Yes/No

Rendering a png output in the notebook editor can trigger a long "Compose Layer" call and block the whole UI, not sure what's triggering this.

![image](https://user-images.githubusercontent.com/876920/136464572-ec387c9f-de98-47b1-b33a-8fa579a50226.png)

**Comment by deepak1556** [comment]
Can you run the following steps to get a trace from the runtime,

```
1) Start the app like

code-insiders --enable-gpu-service-tracing --enable-tracing="blink,cc,gpu,renderer.scheduler,sequence_manager,v8,toplevel,viz,disabled-by-default-viz.overdraw" --trace-startup-file="<fill-some-absolute-path-to-trace-filename.log>"

2) Perform the steps to repro the slowdown and quit the app
3) Log file will be generated at the path you have provided for --trace-startup-file
```

**Comment by rebornix** [comment]
I'm not seeing this particular error on latest Electron.
