### ISSUE TITLE
Workspace Default Build Task doesn't seem to work when a User Default Build Task has already been defined

### ISSUE THREAD

**Issue by pied2porc** [microsoft/vscode#134605]
Issue Type: <b>Bug</b>

I've set a User Default Build Task with those lines:
```
"group": {
    "kind": "build",
    "isDefault": true
}
```
so that I can press ctrl+shit+B to launch the compiler and skip the annoying drop down menu.
But when I configure a Workspace Default Build Task and press the shortcut, it only launches the User's task and ignores the Workspace settings.
The only way I've found to make it work is to not set the build task to default in the User's file, which is annoying because I'm losing the default configuration for projects relying on the User's settings.
Any workaround? or am I doing something wrong?

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by alexr00** [comment]
If you have multiple `default` build tasks, then we should be showing you a picker to choose which build task you want.

**Comment by rchiodo** [comment]
/verified

Folder trumps user.
