### ISSUE TITLE
Project structure changed but refresh shows old structure

### ISSUE THREAD

**Issue by Lythix** [Microsoft/vscode#13460]
- VSCode Version: 1.5.2
- OS Version: Windows 7 (build 7601: sp1)

Steps to Reproduce:
1. Used Angular CLI to generate new component but did it in subfolder. 
2. VSCode shows the new folder automatically.
3. From explorer deleted new folder and all generated files.
4. Generated new component again this time in correct folder
5. VSCode still shows old file structure. Click refresh does not reload new structure. Click files will prompt file does not exist, would you like to create it. 

I think the file changes on disk should be updated when clicking refresh button in VSCode.

**Comment by bpasero** [comment]
@Lythix are you seeing a warning about .NET 4.5. being required for file watching? I suspect the file watcher is not running.

**Comment by Lythix** [comment]
No, not seeing any warnings like that. 
I did notice later that I was running Ng serve so it's possible the files were locked?

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
