### ISSUE TITLE
Hiding and showing vscode terminal causes the terminal scroll position to reset to top

### ISSUE THREAD

**Issue by aureq** [microsoft/vscode#134692]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.0
- OS Version: Windows 10 10.0.19043

Steps to Reproduce:

1. Launch vscode, with or without extensions enabled
2. Open a terminal
3. Run a command that generates many lines (`dir C:\Windows\System32`)
4. Note the terminal scrollbar position. It should be at the bottom
5. Hide the terminal windows using the `X` icon in the terminal top right corner, or using CTRL+`
6. Reveal the terminal window using CTRL+`
7. Note the terminal scrollbar position. It should be at the top. Even though the content displayed is at the bottom
8. Use your mouse wheel to scroll and the position resets to the top

**Comment by meganrogge** [comment]
Just confirmed this still reproes
