### ISSUE TITLE
right click context editor

### ISSUE THREAD

**Issue by cookhe** [microsoft/vscode#134606]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

When I right click to open the context editor and the cursor is low enough in the screen such that the menu must open higher with the cursor somewhere in the middle and aligned with one of the menu items, the cursor highlights that menu item during mid-click and ends up being selected as I release the mouse button. The result is that I end up selecting menu items or executing commands without actually seeing what was selected. Numerous times I have wondered what happened and have been unable to determine if my code was effected. This occurs both when I use a USB mouse and my laptop's touchpad physical right click but not when I use a two finger tap to "right click". If I right click and hold, I am able to move the cursor away from the context menu and release it without selecting an option, and the menu fortunately stays open. This is a workaround I can use in the meantime, but when I forget to do this, the problem persists.

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:01:43.795Z)
OS version: Linux x64 5.10.0-1045-oem
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 3536)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.08GB (18.77GB free)|
|Process Argv|--unity-launch --crash-reporter-id 6769aaf4-46b7-475e-a5ff-0af4a73b725d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.10.0
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
cpptools|ms-|1.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30378364
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis400:30374798
vsaa593:30376534

```

</details>

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/113175
