### ISSUE TITLE
Slow environment resolution notification with latest insider

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#134608]
```
Version:          Code - Insiders 1.61.0-insider (2dc8b9580809148e312356852affc4b8d4feb7da, 2021-10-06T08:26:07.427Z)
OS Version:       Darwin arm64 20.6.0
CPUs:             Apple M1 (8 x 24)
Memory (System):  16.00GB (0.08GB free)
```

With the latest insiders I get the following notification **immediately** when opening a remote-ssh window. No changes have been made to the shell initialization scripts. I didn't have this notification before.

![image](https://user-images.githubusercontent.com/4674940/136459764-41e42265-5384-427a-818f-073fbcc69dca.png)

**Comment by bpasero** [comment]
@roblourens any clues? do you see the same?

**Comment by bpasero** [comment]
I cannot reproduce, here are my steps:
* install Parallels, Ubuntu 20.04
* enable ssh server: `sudo apt install openssh-server`
* fresh VS Code insiders with SSH extension installed
* from the command line start with `--force-user-env` to forcefully enable shell environment

I do not see the warning.

**Comment by kieferrm** [comment]
Sorry for the delayed answer. Here is what I see: https://cln.sh/KBCadX/download

**Comment by bpasero** [comment]
We only attempt to resolve the shell environment once on startup:

https://github.com/microsoft/vscode/blob/3583edcc0b224b091b84d4f06d9160b8f1c93039/src/vs/platform/environment/node/shellEnv.ts#L69-L73

And this gives up to resolve after 10 seconds. Any subsequent attempts to resolve the shell environment will fail if the initial one failed. We have always been behaving like that.

I pushed a change to only show this notification once and not more than that, which was an issue reported also in https://github.com/microsoft/vscode/issues/136272

//cc @joaomoreno
