### ISSUE TITLE
[BUG] New update not show CSS class in intellisense anymore

### ISSUE THREAD

**Issue by kjngstars** [Microsoft/vscode#13467]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: abusaidm.html-snippets-0.0.16, donjayamanne.jquerysnippets-0.0.1, lonefy.vscode-JS-CSS-HTML-formatter-0.2.1, mkaufman.HTMLHint-0.0.3, Zignd.html-css-class-completion-1.0.3

Steps to Reproduce:

1.
2.

Currently i'm working with Semantic UI, before the latest update all thing work properly, but after this one, the intellisense not show CSS class in Semantic UI anymore.
![image](https://cloud.githubusercontent.com/assets/11659446/19258343/40a7c0e8-8fa1-11e6-82bb-8be263c3a773.png)

**Comment by aeschli** [comment]
VSCode doesn't support class completion out-of-the box. There might be some extensions that add that. Maybe 'Zignd.html-css-class-completion'? If that extension works no longer, please file a bug request directly against the extension (https://github.com/Zignd/HTML-CSS-Class-Completion)
