### ISSUE TITLE
Group command palette actions by language

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#13468]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:28:55.412Z)
- OS Version: Darwin x64 16.1.0

We can category command palettes by programming language.
I installed go and python extensions.
Press `F1`, then type `test`, and shows as below.
![](http://o8z0dg641.bkt.clouddn.com/QQ20161011-1@2x.png)

It would be better only show language relative command in the red rect area.

**Comment by alefragnani** [comment]
It's a similar idea from this https://github.com/Microsoft/vscode/issues/10154, to _filter_ the commands based on some  _context_. 
Looking forward to this :+1:

**Comment by mjbvz** [comment]
#19345 allowed extensions to selectively enable commands in the command palette based on the current language
