### ISSUE TITLE
Source control shifts focus

### ISSUE THREAD

**Issue by estebanff** [microsoft/vscode#134666]
Issue Type: <b>Bug</b>

1. Have workspace (I am using one with two folders)
2. Make commits in either of them.
3. Modify a file and stage the commit.
4. Start typing the commit message.

Expected behavior:
One should be able to type the message and push the changes.

What is happening:
When typing the field, after like 2 seg, focus shifts to the other repo commit box. Doesn't matter what repo you are typing the commit, it shifts to the other commit field.

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:10:20.463Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 1f7dc647-4d37-466e-818b-b936c645fa51|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.2
vscode-intelephense-client|bme|1.7.1
vscode-tailwindcss|bra|0.7.0
dart-code|Dar|3.27.1
flutter|Dar|3.27.0
vscode-eslint|dba|2.2.1
xml|Dot|2.5.1
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
auto-rename-tag|for|0.1.8
svg|joc|1.4.12
volar|joh|0.28.0
vscode-phpfmt|kok|1.0.30
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.17.0
python|ms-|2021.10.1317843341
vscode-pylance|ms-|2021.10.0
remote-containers|ms-|0.202.1
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
vsliveshare|ms-|1.0.4962
debugger-for-chrome|msj|4.13.0
laravel-artisan|rya|0.0.28
svelte-vscode|sve|105.4.2
vscode-icons|vsc|11.6.0
vscode-import-cost|wix|2.15.0
material-theme|zhu|3.13.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30378364
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis400:30374798
vsaa593cf:30376535

```

</details>

**Comment by lramos15** [comment]
We're taking #135143 as the candidate and this should fix this one as well so closing.
