### ISSUE TITLE
Source Control is buggy after the latest update

### ISSUE THREAD

**Issue by kabampsong** [microsoft/vscode#134699]
Issue Type: <b>Bug</b>

Since the latest update, the source control panel may sometimes showing the wrong name for a submodule repository -- this happens when switching branch or making a new commit on either the parent repo or the submodule repo.

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:11:58.853Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|13, 22, 14|
|Memory (System)|32.00GB (1.33GB free)|
|Process Argv|--crash-reporter-id 6f92dd02-fb70-47f3-88a4-2d2261624a24|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
vscode-standardjs-snippets|cap|0.8.15
bracket-pair-colorizer|Coe|1.0.61
vscode-redis-client|cwe|1.2.8
vscode-eslint|dba|2.2.1
javascript-ejs-support|Dig|1.3.1
gitlens|eam|11.6.1
permute-lines|ear|1.1.0
git-graph|mhu|1.30.0
node-debug2|ms-|1.43.0
indent-rainbow|ode|8.1.0
subtle-brackets|raf|3.0.0
vscode-sort-json|ric|1.20.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.14
vscode-redis|vit|2.0.1
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
luahelper|yin|0.1.58
vscode-open-in-github|ziy|1.3.6

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30378364
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis300:30374797
vsaa593:30376534

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/134638#issuecomment-938471497 for a workaround.
