### ISSUE TITLE
Add "new folder" option -- to make starting a new project easier.

### ISSUE THREAD

**Issue by ultraGentle** [microsoft/vscode#134651]
I may be doing something wrong, but the experience of starting a new project from within VSCode is clunky / unintuitive. 

On the welcome screen and menu, there's "new file" -- but when starting a new project, I'd actually want a new folder.  

After all, for existing projects one typically opens the folder, not an individual file, so why should project creation be any different?

As it is, I create the new file, and then when I go to save the the file for the first time, I create a folder using the "new folder" button in the OS's "save as" dialog -- 

but even then, VSCode's file explorer doesn't switch into that folder.  

So, I'd suggest "new folder" as a both a menu item and on the Welcome screen.  

For the best UX, you'd then probably want to highlight or make obvious a "new file" button, either in the file explorer sidebar, or in the empty/open folder.

**Comment by ultraGentle** [comment]
There's "open" -- but presumably that's for existing projects?  
Of course, you can create a new folder from withing the system dialog, 
but if I'm thinking of the new-user experience, it wouldn't occur to me to use "open" to start a new project.  

I'm using Mac OS 11, and latest stable for VSCode.

**Comment by ultraGentle** [comment]
@vscode-triage-bot @JacksonKearl 

Hi, just suggesting we un-close, unless there's been behind-the-scenes discussion (which is fine!).

**Comment by julie777** [comment]
@ultraGentle 
If you are starting a new project then wouldn't "new workspace" be more accurate than "new folder"?

Create "new workspace" can create a folder, create the .vscode folder, and whatever else is needed to get you started.

**Comment by AndreyChursin** [comment]
I don't understand what everyone is talking about... the problem really exists and there are only workarounds for creating a root directory for a new project!

<img width="661" alt="Image" src="https://github.com/user-attachments/assets/2e3ad207-49a6-4e1e-adb3-6a4d28f456be" />

and there no "new workspace" or "new folder" or something else...

<img width="759" alt="Image" src="https://github.com/user-attachments/assets/495e6bd0-848e-46b3-af78-0aec6f284379" />
