### ISSUE TITLE
[Inline Suggestions] Support accepting suggestions that are not on tab-stops

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [microsoft/vscode#134664]
Currently, when we display indented inline suggestion, the user needs to tab until the cursor is at the same location as the beginning of the text in the inline suggestion. 
This however is problematic if the suggestion is not exactly at the tab stop point (for example tab is set to 4 spaces in editor setting but displayed suggestion is on 6 spaces indentation) - it means users are often accidentally dismissing suggestion (by moving the cursor past suggestion). The workaround from a user point of view is that they need to use space to move the cursor precisely to the location of ghost text, however it's not super discoverable/obvious to users

I could potentially see 2 solutions here: 
* If the user press tab in a situation where it would move the cursor past suggestion, insert only as many spaces as required to put the cursor at the suggestion (from my earlier example - insert only 2 spaces, to put the cursor at 6 spaces), and next tab would accept suggestion normally.
* Or, if the tab would move the cursor past the suggestion, accept the suggestion. 

CC: @hediet

**Comment by orph** [comment]
Here's a user submitted [video](https://github.com/github/copilot-preview/discussions/897) of this behavior:

https://user-images.githubusercontent.com/26822551/126787880-500f6faf-5e41-4cdf-97e2-4ecb85213086.mp4

@hediet I think this is high priority as we've had reports of people quitting Copilot over this issue.

**Comment by orph** [comment]
> I think in both cases the user experience as shown in @orph's video is not very nice - the user has to press tab very often until the suggestion is being accepted.

This is an early copilot iteration I think we nailed actually - pressing tab enough times to "meet" the insertion is learnable. Whereas if we just accept the current indented suggestion on Tab, it would not allow you to create a different indent from what the AI suggests.

**Comment by orph** [comment]
Here's another test case I just experienced - insert a space at the start of the suggestion, and Tab never accepts the suggestion. It's always off-by-one. I think this is the base case that the first video demonstrates.

https://user-images.githubusercontent.com/28068/136679670-a5afaaa9-6be4-49df-a695-84ccd30a1c09.mov

**Comment by hediet** [comment]
> Or is the choice about what the Tab key should do made at an earlier stage that makes it hard for it to both?

Yes, currently the command "accept inline suggestion" is bound to tab (potentially override the "insert tab character" command), but only active if the suggestion does not start with whitespace.

But I just got an idea:
"accept inline suggestion" could be active (overriding the default tab command) if and only if the suggestion starts with an indentation that is less than tab-width.

**Comment by hsenag** [comment]
Sorry for the delay - we were very busy with Universe last week.

I've had a play with Insiders versus the current release and it seems to behave better on one example we originally saw with Copilot, but I'm having trouble characterising exactly what was wrong before and whether it's gone now. In one example a closing `}` still jumps around quite a bit in ways I can't quite predict.

@orph @Krzysztof-Cieslak could you take a look too?
