### ISSUE TITLE
Visual Studio Code plugin that autocompletes filenames can't work

### ISSUE THREAD

**Issue by minjunlan** [Microsoft/vscode#13477]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: christian-kohler.path-intellisense-1.0.2

Visual Studio Code plugin that autocompletes filenames can't work。
all path autocompletes can not work

**Comment by isidorn** [comment]
I belive this functionality is coming from chrisitan kohler paht-intellisense extension which you have installed. Can you please file this issue in the repository of that particular extension.
Thank you

**Comment by minjunlan** [comment]
but any extension that path autocomplate in html can't work , it is't one extension. i think it is your bug

**Comment by isidorn** [comment]
ping @aeschli to assess
