### ISSUE TITLE
Terminal Find: Highlight all instances of term in current viewport and don't manipulate selection

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#134790]
Forked off from https://github.com/microsoft/vscode/issues/28768

Upstream issue: https://github.com/xtermjs/xterm.js/issues/1653

We want find to highlight all matches in the viewport using a different highlight to regular selection, just like in the editor:

![image](https://user-images.githubusercontent.com/2193314/136784743-d87b5632-ede8-4e4c-add4-fab8113e10a6.png)

**Comment by ican2056** [comment]
Why not open the search function of Chrome. Just do not disable the shortcut keys.

**Comment by Tyriar** [comment]
@ican2056 the terminal is normally displayed on a canvas, the browser's find has no access to that. Plus even when it is rendered in the DOM, only the viewport is, not the entire buffer.
