### ISSUE TITLE
[ext api] expose last activity info

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#134795]
We would like to track a last user activity in the window, like keyboard and mouse events. For now we just use all kind of events in the extension host process as proxies, but for instance there does not seem to be an event for typing in terminals. Would it be possible instead track DOM events in the window and expose the last activity in milliseconds as an API. It could be updated for instance with an interval 0.5s.

**Comment by akosyakov** [comment]
Alternatively there can be some way to register a listener for idle time, i.e. `window.onIdle(2 * 1000, () => {})`

**Comment by jrieken** [comment]
We are no exposing UI details for extensions https://code.visualstudio.com/api/extension-capabilities/overview

**Comment by akosyakov** [comment]
I did not mean to expose DOM events, but rather use them to provide info about whether a window is actually used or not. There are already exposing such information in similar fashion like `focused`. But it is not useful enough `focused` does not really tell whether a user interacting with the window.

**Comment by jrieken** [comment]
> but rather use them to provide info about whether a window is actually used or not. 

Why would you need that?

**Comment by akosyakov** [comment]
> Why would you need that?

When users are using VS Code Remote SSH to connect to a Gitpod workspace container we would like to time out a container if a window is not used after 30 mins. We ask a user to install a special extension which tracks different events right now, but it is not always enough. Especially when terminals are mostly used, e.g. we don't have a way to detect typing. I thought this problem is rather easy to solve by tracking keyboard and mouse DOM events and propagating idle time to the extension host process than using other ext API events as proxies.

I wonder how timeouts are implemented in Codespaces? I heard internally that there are similar issues.

**Comment by jrieken** [comment]
> I thought this problem is rather easy to solve by tracking keyboard and mouse DOM events and propagating idle time ...

I don't believe that's sufficient, esp. not in your case. I can type a command in the terminal which takes hours to finish. Because of that I leave the computer alone and go for lunch or for a bike ride and wouldn't want the lack of mouse activity be causing cancellation of that operation.
