### ISSUE TITLE
No icons in 1.6

### ISSUE THREAD

**Issue by seemsindie** [Microsoft/vscode#13479]
- VSCode Version:
Version 1.6.0
Commit e52fb0bc87e6f5c8f144e172639891d8d8c9aa55
Date 2016-10-10T18:30:01.819Z
Shell 1.3.7
Renderer 52.0.2743.82
Node 6.5.0

- OS Version:

Antergos Linux release 16.9 (ISO-Rolling)
NAME="Antergos Linux"
VERSION="16.9-ISO-Rolling"
Linux tardis 4.7.6-1-ARCH

Steps to Reproduce:

1. Update packages with yaourt -Syyu --aur
2. Run vscode

Here is the image ![](http://i.imgur.com/WpNWZg9.png)

**Comment by isidorn** [comment]
@seemsindie you also need to choose the file icon theme? Did you do that?
I agree this is a bit confusing, ping @bpasero 

![screen shot 2016-10-11 at 10 43 28](https://cloud.githubusercontent.com/assets/1926584/19264071/9584fb6e-8f9f-11e6-8c94-94a41efc83f3.png)

**Comment by seemsindie** [comment]
@isidorn Thanks

**Comment by isidorn** [comment]
@seemsindie nema na cemu
