### ISSUE TITLE
Intellisense stuck on loading - Apple M1

### ISSUE THREAD

**Issue by chudoklates** [microsoft/vscode#134793]
Issue Type: <b>Bug</b>

Working on a large Javascript-React project, the Intellisense service works for about a minute or two, then stops working. To reproduce, simply open a large javascript project, and wait for a few minutes. Disabling my extensions seems to not do anything. VSCode does not log any issues.

VS Code version: Code 1.61.0 (Universal) (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:11:58.853Z)
OS version: Darwin arm64 20.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 16e1fa5e-0620-42bf-8c3c-c103fb97c69a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.1
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
file-icons|fil|1.0.29
vscode-typescript-next|ms-|4.5.20211010
vscodeintellicode|Vis|1.2.14

</details>

**Comment by mjbvz** [comment]
Can you please share an example project that demonstrates the issue
