### ISSUE TITLE
Terminal tabs hover no longer seems to work

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#134794]
Mousing over this doesn't show the hover for me:

![image](https://user-images.githubusercontent.com/2193314/136799073-43c658fc-78de-4d80-8da2-861b6b701870.png)

Terminal editor tab hover works fine.

**Comment by yume-chan** [comment]
Extension list hover and status bar hover also stopped working #134808.

After reverting f92df8b8d0be69b1237d8613c12c53a0c74fddd2 it works again @aeschli 

![image](https://user-images.githubusercontent.com/1330321/136893643-9f817aee-7a29-4f1a-a0ce-0839e88c42fa.png)
