### ISSUE TITLE
VSCode editor vertical line appear

### ISSUE THREAD

**Issue by Koushikon** [microsoft/vscode#134717]
Does this issue occur when all extensions are disabled?: Yes/No
It nothing to do with extension

- VS Code Version: 1.61.0
- OS Version: Windows 10_19043.1266

Steps to Reproduce:

1. When I write like 1 👇 and without closing the string single quote or like 2 👇 don't close inside the closing parenthesis a white vertical line appears in the `VSCode` editor. I have the picture if you want, I can show it to you.
2. I close `VSCode` and try to re-open and the line appears when below i write one of the below codes.

```SQL
-- 1
SELECT ('MEOW MEOW)

-- 2
('MEOW MEOW'
```

**Comment by Koushikon** [comment]
Sorry for that It's a feature of `VSCode` recently released `editor.guides.bracketPairs` because of this this line is appearing.

Please remove this issue I try but could not find any option.
Sorry again for the mistake🙏

**Comment by gjsjohnmurray** [comment]
@Koushikon please use the button to close the issue.
