### ISSUE TITLE
vscode git checkout branch bug

### ISSUE THREAD

**Issue by casercyl** [microsoft/vscode#134763]
Issue Type: <b>Bug</b>

在工作区中以文件夹的形式放入两个项目A，B分别处于不同分支branchA，branchB，然后将项目A切换到branchB分支，此时A，B项目都处于branchB分支，此时切换A项目到branchA分支，问题就出现了，B项目也会同时切换到branchA分支，我明明只切换了A项目，但是它会影响到B项目。

Put two items in the workspace in the form of folders, itemA and itemB are in different branches branchA and branchB respectively, and then switch itemA to branchB branch. At this time, itemA and itemB are in branchB branch. At this time, switch item a to branchA branch, and the problem occurs. ItemB will also switch to branchA branch at the same time. I obviously only switched itemA, But it will affect itemB.

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (4.17GB free)|
|Process Argv|--crash-reporter-id 9299864f-24e3-4d79-910c-89a0074e0ede|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.4.0
laravel-goto-view|cod|1.3.4
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.2.1
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
auto-rename-tag|for|0.1.8
vscode-language-pack-zh-hans|MS-|1.61.3
vetur|oct|0.34.1
minapp-vscode|qiu|2.3.4
vscode-scss-formatter|sib|2.2.4
vscode-stylelint|sty|0.87.6
react-redux-es6-snippets|tim|2.1.0
codelf|unb|11.7.0
ReactSnippets|xab|2.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30378364
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis300:30374797
vsaa593:30376534
vssld246cf:30379912

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/134638#issuecomment-938471497 for a workaround.
