### ISSUE TITLE
Chinese characters are duplicated in the pwsh terminal under vscode

### ISSUE THREAD

**Issue by Odland** [microsoft/vscode#134701]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: win7
- pwsh Version: 7

Steps to Reproduce:

1. I wrote a command line tool to get data, but the returned Chinese is duplicated
2. And I am on pwsh, the data displayed is normal, and there is no duplicate in Chinese
3. The screenshot of the returned data is here
![1688373273](https://user-images.githubusercontent.com/29625229/136642876-f05f07fd-41de-4982-a4eb-eb3985e4fe8d.jpg)

**Comment by khuccui2002** [comment]
> what's the program that you're running? I can't reproduce the issue. ![recording - 2021-10-11T102935 655](https://user-images.githubusercontent.com/29464607/136831117-62c6c877-446f-4007-93b1-29730ea0e60d.gif)
It happened in vs code terminal
![CleanShot 2021-10-12 at 10 48 58](https://user-images.githubusercontent.com/48780373/136888179-6e2d0ecd-1a39-496d-801b-99c928a6ab80.png)

**Comment by khuccui2002** [comment]
@meganrogge please review
![CleanShot 2021-10-12 at 15 21 08](https://user-images.githubusercontent.com/48780373/136919399-ea6d471b-8f9f-4127-b2a0-a86e6cc86061.gif)

**Comment by shizhx** [comment]
@meganrogge insider version has same issue, I find the key point is typing **at least two characters** in IME.
```
Version: 1.62.0-insider
Commit: 284e0db6c4cac1e557a43cd6691babdaafc2e1a9
Date: 2021-10-12T05:44:48.500Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.124-1-MANJARO
```
My IME info:
```
fcitx-sogoupinyin 2.4.0.3469-1
```

**Comment by meganrogge** [comment]
if you try in an external powershell on win7 does it work?

**Comment by khuccui2002** [comment]
@Tyriar I'm using Mac and I still get this error

**Comment by Tyriar** [comment]
@khuccui2002 this issue is about doubling characters in _output_ on Windows, your issue seems to be related to _input_.
