### ISSUE TITLE
cannot start code via command line on windows 10

### ISSUE THREAD

**Issue by chantisnake** [Microsoft/vscode#1347]
I have checked the path variable, it is set properly:
![capture1](https://cloud.githubusercontent.com/assets/10100995/11824025/65f4b584-a345-11e5-8966-8af38d29cc8e.PNG)

and the `code.cmd` is there.
![capture2](https://cloud.githubusercontent.com/assets/10100995/11824039/718294ac-a345-11e5-8062-da266dca66f7.PNG)
double clicking on `code.cmd` do launches vs code.

but, when I go to power shell or cmd:
![capture](https://cloud.githubusercontent.com/assets/10100995/11824061/896c3514-a345-11e5-9a06-2aa7443888d9.PNG)

I don't know what happened...

**Comment by felixfbecker** [comment]
It works for me...
Try adding the extension `code.cmd .` and see what happens

**Comment by dbaeumer** [comment]
This works for me  as well in both cmd and powershell.

**Comment by dbaeumer** [comment]
Closing.

@chantisnake pls ping me when you have more info regarding this issue

**Comment by chantisnake** [comment]
adding to system environment works, but VScode by default add to user path, which don't work for me.

Thank for the support anyway.
