### ISSUE TITLE
Terminal Find: Show result count

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#134791]
Forked off from #28768

Upstream issue: https://github.com/xtermjs/xterm.js/issues/1659

Add "No results" label, need to think about what to show in the gap when there are results. We probably shouldn't be searching the entire buffer when we don't have to for performance reasons. We want to align with the editor's behavior as close as possible.

**Comment by amanasifkhalid** [comment]
Hi, may I work on this one? Thanks!

**Comment by Tyriar** [comment]
@amanasifkhalid sorry, we've already started work on it 🙂

**Comment by meganrogge** [comment]
@rbadapanda that's been fixed now
