### ISSUE TITLE
Empty HoverWidget is visible at startup

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#134750]
- VS Code Version: stable and from sources

This small square :arrow_down: . It annoys me :smile: 

![image](https://user-images.githubusercontent.com/25115070/136707474-28e2a2d1-0e01-4592-ac1c-f3460ccabed6.png)
![image](https://user-images.githubusercontent.com/25115070/136707428-e0f45bce-1557-4a6d-a8b8-d81ae6840e35.png)

**Comment by WebFreak001** [comment]
thanks, I just spent half an hour being annoyed at this pixel until I realized I could update to fix it. Truly a critical bug that somehow got past the testers!
