### ISSUE TITLE
Color theme breaks in .TS files if HTML contains tags that do not require closing

### ISSUE THREAD

**Issue by Nikki1993** [Microsoft/vscode#13478]
- VSCode Version: 1.6
- OS Version: 10.12

Steps to Reproduce:

1. Setup an Angular 2.0 project
2. In the template add hr tag. 
3. Watch as no theme color applied unless break is added to the ending of hr tag which is not required

Non-working color with hr tag as it is http://d.pr/i/auGg

![screen shot 2016-10-11 at 10 57 51](https://cloud.githubusercontent.com/assets/1446529/19262909/2e58bcca-8fa2-11e6-8adf-d369ac06176d.png)

Working color with hr tag closed/removed https://d.pr/RG9c# 

![screen shot 2016-10-11 at 10 58 01](https://cloud.githubusercontent.com/assets/1446529/19262913/32438b8a-8fa2-11e6-8c5c-28f7a42b3a34.png)

Default or custom theme, both break.

**Comment by aeschli** [comment]
@Nikki1993 Can you add the code snippet that shows the problem?

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#309
