### ISSUE TITLE
Git status is wrong

### ISSUE THREAD

**Issue by cwang1221** [microsoft/vscode#134772]
We have written the needed data into your c
Issue Type: <b>Bug</b>

I have multiple projects opened in VS Code. On the source control page, each project has its own status. When I change the status of one project (e.g switch to master branch, synchornize change), the status of a neighbour project is also changed (looks changed, but not actually changed).

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (3.73GB free)|
|Process Argv|--crash-reporter-id ca0cee24-5f1b-4e0a-98b8-483184988433|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
tailwind-docs|aus|1.4.0
vscode-tailwindcss|bra|0.7.0
vscode-eslint|dba|2.2.1
githistory|don|0.6.18
vscode-jest-runner|fir|0.4.47
auto-close-tag|for|0.5.12
panelnotepad|I32|0.0.1
vscode-styled-components|jpo|1.6.6
vetur|oct|0.34.1
psi-header|psi|1.15.2
vscode-xml|red|0.18.0
markdown-preview-enhanced|shd|0.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30378365
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis200:30374795
vsaa593:30376534
vssld246:30379911

```

</details>

lipboard because it was too large to send. Please paste.

**Comment by dkms-its** [comment]
Note, sometimes even the cursor jumps into the first commit message field while typing in a subsequent one.
