### ISSUE TITLE
tmTheme bold fontStyle not working for 1.6, works fine on 1.5

### ISSUE THREAD

**Issue by dyu** [Microsoft/vscode#13470]
- VSCode Version: 1.6
- OS Version: Ubuntu 16.04 x64

The code that handles the setting is in:
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/themes/electron-browser/stylesContributions.ts#L129

I tried underline and italic ... worked fine.  So it seems to be specific to the bold property and maybe the version of chromium shipped with vscode and my OS?

This works totally fine when using vscode 1.5.

**Comment by aeschli** [comment]
On Linux, the preferred font is "Droid Sans Mono" which doesn't seem to support bold.

**Comment by dyu** [comment]
Thanks.  I'll have to change the font.  My OS is Ubuntu 14.04 btw (not 16.04, was a typo)

**Comment by alexandrudima** [comment]
This is something to consider when picking a new default font in #5742

Since Ubuntu 16.04 no longer carries "Droid Sans Mono", let's track in #5742
