### ISSUE TITLE
tabs working are scewed after updating to latest version. now tabs are adding 6 spaces instead of 4. Please fix.

### ISSUE THREAD

**Issue by ajeet2511** [Microsoft/vscode#13472]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: donjayamanne.python-0.4.0, fabianlauer.vs-code-xml-format-0.1.2, lukehoban.Go-0.6.43, magicstack.MagicPython-0.5.16, ms-vscode.Theme-MaterialKit-0.1.1, msjsdiag.debugger-for-chrome-1.1.0, msjsdiag.debugger-for-edge-0.4.1, tht13.python-0.2.3

Steps to Reproduce:
1. create a python file
2. when you tab it adds 6 spaces instead of 4

**Comment by isidorn** [comment]
@ajeet2511 You can change this setting in the lower right by clicking on the tab size button in the status bar. 
However what settigns python is enforcing I am not sure thus forwarding to @DonJayamanne

**Comment by DonJayamanne** [comment]
@ajeet2511 ,
The default setting for tabs in python is 4 spaces (this is inherited from the vs code settings).
However, when a python file (generally any file) is opened, the tab size is determined based on the contents of the file.
Anyways, I tested this at my end and am unable to replicate it.

Please could you do the following:
- Create a python file (empty)  
- Open it (**do nothing else**)  
- Check the tab size (value for ```Spaces:``` on the bottom right of the status bar)
- What is this value?
- Next press tab in the python file and check the value of this value in the status bar once again

If in both of the instances the value of ```Spaces:``` in the status bar is ```6```, then:  
- Please open your workspace and user settings and check if tabsize is overwritten to 6 (```editor.tabSize```)

If there is no setting in workspace or user settings (```settings.json```) that overrides the value to ```6```, then try the following:
- Please uninstall each of the following three extensions one by one to try and isolate the problem:
    + donjayamanne.python-0.4.0  
    + magicstack.MagicPython-0.5.16   
    +  tht13.python-0.2.3

**Comment by Tyriar** [comment]
Closing due to no response.
