### ISSUE TITLE
After upgrade to 1.6.0, set font-family 'URW Gothic L' fail

### ISSUE THREAD

**Issue by Tean2016** [Microsoft/vscode#13473]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:30:01.819Z)
- OS Version: Linux x64 4.4.0-42-generic
- Extensions: DotJoshJohnson.xml-1.6.0, HookyQR.beautify-0.4.0, NoHomey.theme-realgithub-1.0.4, Nuuf.theme-hackershaze-1.2.1, PKief.material-icon-theme-1.1.1, RoscoP.ActiveFileInStatusBar-1.0.2, abusaidm.html-snippets-0.0.16, be5invis.vscode-icontheme-nomo-dark-1.1.4, bernardodsanderson.theme-material-neutral-0.6.0, chenxsan.vscode-standardjs-1.0.1, donjayamanne.python-0.4.0, eg2.tslint-0.5.39, eg2.vscode-npm-script-0.0.20, gerane.Theme-Blackboard-0.0.2, karyfoundation.theme-karyfoundation-themes-5.2.0, liuji-jim.vue-0.1.3, mohsen1.prettify-json-0.0.3, ms-vscode.Theme-1337-0.1.2, ms-vscode.js-atom-grammar-0.1.9, msjsdiag.debugger-for-chrome-1.1.0, samverschueren.yo-0.8.5, shinnn.stylelint-0.17.0, stevencl.addDocComments-0.0.8, tht13.python-0.2.3, vsmobile.cordova-tools-1.2.3, xabikos.JavaScriptSnippets-1.2.0

Steps to Reproduce:

1.
2.

**Comment by alexandrudima** [comment]
@Toybreak What is your exact `"editor.fontFamily"` setting. Do other fonts work for you?

**Comment by Toybreak** [comment]
@alexandrudima Hi,  this is my setting
> "editor.fontFamily": "'URW Gothic L','Microsoft Yahei'"

used to work well, till this upgrade. Other fonts work well

**Comment by alexandrudima** [comment]
We have updated Electron and with it came a newer version of Chromium. I do not know what Chromium changed w.r.t. font family names and their resolving, anything they would have changed would impact any website. 

@Tyriar have you heard anything regarding this (on linux) ?

@Toybreak Can you please try if any of the browsers you have pick up the correct font when you go to http://jsbin.com/yaxehunoco/edit?html,output

**Comment by Tyriar** [comment]
Haven't seen anything like this personally, I'd guess it's related to the font string being incorrect or being installed incorrectly?

**Comment by Toybreak** [comment]
hi @alexandrudima i've tried in chrome and chromium, both not working. i think i installed it correctly

**Comment by Toybreak** [comment]
![screenshot from 2016-11-02 15-26-42](https://cloud.githubusercontent.com/assets/18119297/19920415/7fd43908-a113-11e6-8c92-2122a0d0aa81.png)

**Comment by Toybreak** [comment]
it works in firefox.

**Comment by alexandrudima** [comment]
@Toybreak Thank you for following up on this.

In this case, may I please ask you to search for an existing issue / create a new issue against Chromium and link to it in the comments -- https://bugs.chromium.org/p/chromium/issues/list

If Firefox can find your installed font, then IMHO Chromium should be able to find it too.

**Comment by Tean2016** [comment]
sorry, recently i can not recreate this bug. so i will close this issue
