### ISSUE TITLE
Unable to install Python extension on remote server.

### ISSUE THREAD

**Issue by Longday0923** [microsoft/vscode#134700]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0
- OS Version: (Local)Linux x64 5.4.0-86-generic (Remote) Linux version 4.15.0-55.60(gcc version 7.4.0(Ubuntu 7.4.0-1ubuntu1~18.04.1))

Steps to Reproduce:
- Just install extension on the remote server, stuck for a long period of time, and failed. The log is as follow:
![image](https://user-images.githubusercontent.com/65357559/136642288-51f03ccd-464e-4cac-a494-bc6fdcaee1c1.png)

**Comment by sandy081** [comment]
Please update to latest VS Code version and try again.
