### ISSUE TITLE
cmd window is not closing after opening vscode using run command

### ISSUE THREAD

**Issue by m-naeem66622** [microsoft/vscode#134734]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.61.0 (user setup)
- OS Version: 10.0.19043 Build 19043

Steps to Reproduce:

1.Open run command using window+R
2.Type "code"

When i opened vscode using command prompt. It opens the code but on the other cmd window not closed which is launced by hitting enter on the run command.

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" terminal
