### ISSUE TITLE
github shows main branch instead of master

### ISSUE THREAD

**Issue by pelikhan** [microsoft/vscode#134716]
Issue Type: <b>Bug</b>

source control pane showing main brain branch for submodule that has master branch.

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:11:58.853Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (3.34GB free)|
|Process Argv|--crash-reporter-id ee01b6e9-f40a-4a47-a4c5-0b145a968d50|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.1
gitlens|eam|11.6.0
prettier-vscode|esb|9.0.0
file-icons|fil|1.0.29
todo-tree|Gru|0.0.214
vscode-drawio|hed|1.6.2
base64viewer|Jas|1.2.1
svg|joc|1.4.12
vscode-docker|ms-|1.17.0
remote-containers|ms-|0.202.1
vsliveshare|ms-|1.0.4962
polacode|pnp|0.3.4
LiveServer|rit|5.6.1
mdx|sil|0.1.0
vscode-dtdl|vsc|1.0.0
vscode-import-cost|wix|2.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30378364
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis200:30374795
vsaa593cf:30376535

```

</details>

**Comment by sbland** [comment]
Related to #134722

**Comment by pelikhan** [comment]
We have one repo with several sub modules.

https://GitHub.com/Microsoft/jacdac-docs
________________________________

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/134638#issuecomment-938471497 for a workaround.
