### ISSUE TITLE
Feature request: Enable/disable/configure plugins by workspace

### ISSUE THREAD

**Issue by Dracks** [Microsoft/vscode#13475]
I've got multiple types of projects and sometimes I work with grunt & angular, other ones with node, other ones with python...

My main project  was with grunt & angular, I have fully configured the vscode with jshint and other features for the grunt & angular, but when I change to other ones, VSCode launch me an error, because it doesn't found the jshint configuration, etc.  

Also in my house, I've been working with plantuml, and that plugin (I don't remember the name of the plugin) uses the same shortcut that markdown to do the preview, and when I've been doing something with plantuml, the shortcut doesn't work, because vscode always launch the markdown preview. 

Thanks.

**Comment by joaomoreno** [comment]
#2882, which is planned for October.
