### ISSUE TITLE
showTextDocument returned the wrong editor when called multiple times concurrently

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#134786]
It seems like there may be some race condition in `showTextDocument` where if it's called multiple times before the previous has completed, each call returns the last editor to be opened.

Here I have an array of two items `short_test.dart` and `short2_test.dart` and I call `openTextDocument` and `showTextDocument` for each. However the resulting editors both point at `short2_test.dart`:

<img width="892" alt="Screenshot 2021-10-11 at 12 15 52" src="https://user-images.githubusercontent.com/1078012/136781355-5776301f-5e14-4149-a2f8-a4a78271e67c.png">

The results from `openTextDocument` are correct in both cases, it's only `showTextDocument` that seems to be misbehaving.

**Comment by jrieken** [comment]
I cannot copy-paste a screen shot into the editor to reproduce this. If you already make a repo how about sharing its full source code?

**Comment by jrieken** [comment]
nvm - that should be thrown as error... Tho, that will also be the only possible fix, e.g checking that the editor is for the desired document and throw iff not. The fastest will win...

**Comment by DanTup** [comment]
Not anywhere I can find. I checked in both the main VS Code window, and the extension host it spawns to run the test, including the DevTools there (I added a delay to stop it closing after the code ran):

![Screenshot 2021-10-11 at 14 31 34](https://user-images.githubusercontent.com/1078012/136798804-81ba236c-fa21-42ef-91ef-fe52797654fb.png)

I have seen those errors in the past, but I think they resulted in `showTextDocument` rejecting rather than returning the wrong result.

**Comment by DanTup** [comment]
Out of interest, what's the cause of this? Why can't VS Code handle multiple requests like this? As an extension author, it seems like one request blocking behind the other would be much preferred than it just throwing. I actually have seen those errors in tests before, and have a helper that retries myself:

```
	try {
		return await vs.window.showTextDocument(doc);
	} catch (e) {
		logger.warn(`Failed to show ${fsPath(file)} on first attempt, trying again...`, LogCategory.CI);
		logger.warn(e, LogCategory.CI);
		return await vs.window.showTextDocument(doc);
	}
```

(it didn't work here because the call resolved successfully though).

**Comment by jrieken** [comment]
> I still end up with two "editors", even though presumably the first one no longer exists?

Yes, the first editor has then gone stale. That can always happens, like have a single editor reference and the user closes that. We guarantee that events are send to get this right but we cannot force extensions be correct. For text documents we have [`isClosed`](https://github.com/microsoft/vscode/blob/03cc7e9ddb3361336411dce222337516718aa31e/src/vs/vscode.d.ts#L134) but we don't anything like that for editors, it would basically be `vscode.window.visibleTextEditors.includes(someEditorReference)`

**Comment by jrieken** [comment]
There is actually an underlying bug in the workbench logic, when an editor for A is already open and two requests for A and B come in than B opens A. 

* adjust and run the commands from above (https://github.com/microsoft/vscode/issues/134786#issuecomment-940021250)
* close all editors, all good
* keep the one editor open -> bad


<img width="556" alt="Screen Shot 2021-10-15 at 14 34 35" src="https://user-images.githubusercontent.com/1794099/137487574-1ae1a9cc-a6a8-4819-8c53-127324e106bd.png">

```
diff --git a/src/vs/workbench/api/browser/mainThreadEditors.ts b/src/vs/workbench/api/browser/mainThreadEditors.ts
index d458ccae1ac..e4727bcfd84 100644
--- a/src/vs/workbench/api/browser/mainThreadEditors.ts
+++ b/src/vs/workbench/api/browser/mainThreadEditors.ts
@@ -151,11 +151,12 @@ export class MainThreadTextEditors implements MainThreadTextEditorsShape {
 			resource: uri,
 			options: editorOptions
 		};
-
+		console.log('BEFORE', uri.path);
 		const editor = await this._editorService.openEditor(input, columnToEditorGroup(this._editorGroupService, options.position));
 		if (!editor) {
 			return undefined;
 		}
+		console.log('AFTER', uri.path, 'ACTUAL', editor.input?.resource?.path);
 		return this._documentsAndEditors.findTextEditorIdFor(editor);
 	}
```

**Comment by bpasero** [comment]
@jrieken even when all editors are closed and I run the command for the first time, I see this:

```
BEFORE /Users/bpasero/Desktop/test-ts/src/extension.ts
mainThreadEditors.js:113 BEFORE /Users/bpasero/Desktop/test-ts/.eslintrc.json
mainThreadEditors.js:118 AFTER /Users/bpasero/Desktop/test-ts/src/extension.ts ACTUAL /Users/bpasero/Desktop/test-ts/.eslintrc.json
mainThreadEditors.js:118 AFTER /Users/bpasero/Desktop/test-ts/.eslintrc.json ACTUAL /Users/bpasero/Desktop/test-ts/.eslintrc.json
```

I am not sure the intended outcome, but I assume you had expected that the result of:

https://github.com/microsoft/vscode/blob/64081da3c8c12eddc28eaff05672fe9515e7e502/src/vs/workbench/api/browser/mainThreadEditors.ts#L156

Is matching the resource you pass in, but that is not guaranteed. The return type of `openEditor` is `IEditorPane` which is the actual container of the code editor. And we do not allow to have 2 code editors open at the same time unless you have multiple groups, so the first `openEditor` call will get cancelled from the second `openEditor` call. You still get a valid `IEditorPane` back because the pane is still the code editor container, but the `input` of that pane will be the last thing that was successfully opened.

I am not sure how to improve this, throwing an error does not seem like a wise idea.

Any suggestions?

**Comment by bpasero** [comment]
I pushed a change to return `undefined` when `openEditor` operation is cancelled by another operation. 

Given the sample code in this issue, I see that we now throw an exception back to the extension:

```
ERR [Extension Host] Error: Could NOT open editor for "file:///Users/bpasero/Desktop/test-ts/package.json".
	at ExtHostEditors.showTextDocument (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostTextEditors.js:69:23)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Originating from:

https://github.com/microsoft/vscode/blob/f523f65f3985eb6493cae5d219de35f1d7ba6f7a/src/vs/workbench/api/common/extHostTextEditors.ts#L91

I suppose extensions had to deal with this error before already as it is not a new error, but it may appear now in more cases.

**Comment by DanTup** [comment]
@bpasero in latest Insiders, I actually don't see the exception - everything seems to work fine. I tried writing it several different ways, including for ex.:

```
const testFiles = [
	vs.Uri.file("/Users/danny/Dev/Dart-Code/src/test/test_projects/hello_world/test/short_test.dart"),
	vs.Uri.file("/Users/danny/Dev/Dart-Code/src/test/test_projects/hello_world/test/skip_test.dart"),
];
const editor1promise = vs.workspace.openTextDocument(testFiles[0]).then((doc) => vs.window.showTextDocument(doc));
const editor2promise = vs.workspace.openTextDocument(testFiles[1]).then((doc) => vs.window.showTextDocument(doc))
const editor1 = await editor1promise;
const editor2 = await editor2promise;
console.log(editor1.document.uri.toString());
console.log(editor2.document.uri.toString());
```

But both documents seem to be returned as expected:

```
file:///Users/danny/Dev/Dart-Code/src/test/test_projects/hello_world/test/short_test.dart
file:///Users/danny/Dev/Dart-Code/src/test/test_projects/hello_world/test/skip_test.dart
```

This is ofc better than throwing, although it makes me wonder if I'm not triggering it correctly so not sure if the testing is valid.

**Comment by bpasero** [comment]
Ok thanks for trying, this is probably timing dependent too. I had reproduced it with the sample code running out of sources back when I had tried:

```
const testFiles = [
	vs.Uri.file("/Users/danny/Dev/Dart-Code/src/test/test_projects/hello_world/test/short_test.dart"),
	vs.Uri.file("/Users/danny/Dev/Dart-Code/src/test/test_projects/hello_world/test/short2_test.dart"),
];
await Promise.all(testFiles.map(async (testFile) => {
	const doc = await vs.workspace.openTextDocument(testFile);
	const editor = await vs.window.showTextDocument(doc);
	console.log(`Opened ${testFile}\nGot ${editor.document.uri}\n`);
}));
```

**Comment by DanTup** [comment]
Yeah, I tried that one first too, but it also worked (did the thing I wanted, without exceptions). I don't know if that really verifies the fix or not though, but I certainly can't reproduce any bug now :-)
