### ISSUE TITLE
Can't enable Open with Code from the context menu while installing from Windows 11 Store

### ISSUE THREAD

**Issue by manuelelucchi** [microsoft/vscode#134743]
As the title hints, when I install Vscode from the installer, I get the option to enable the Open with Code shortcut in the context menu, while installing from the store completely skips the option.
Can it be enabled from VSCode settings? If not, can you prompt the question even while installing from the store or add the option in the vscode settings?

Regards,
Manuele

**Comment by EnesToptas** [comment]
Definitely not a duplicate.

**Comment by Silver-Fang** [comment]
In fact, this issue is exactly the only reason left on my way to the Store version of VS Code.

**Comment by Diegorro98** [comment]
#134470
This issue is speaking about this, they are waiting for 20 upvotes!
