### ISSUE TITLE
[bug] all thing seems like {}

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#13471]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:28:55.412Z)
- OS Version: Darwin x64 16.1.0
- Extensions: Tyriar.lorem-ipsum-1.0.0, Tyriar.theme-glacier-0.0.10, christian-kohler.npm-intellisense-0.1.3, christian-kohler.path-intellisense-1.0.2, codezombiech.gitignore-0.2.0, dbaeumer.vscode-eslint-1.0.7, deerawan.vscode-dash-1.1.2, donjayamanne.githistory-0.1.0, donjayamanne.python-0.4.0, eg2.tslint-0.5.39, eg2.vscode-npm-script-0.0.20, gnhuy91.vscode-theme-onedark-0.0.2, humao.rest-client-0.8.4, lukehoban.Go-0.6.43, mitaki28.vscode-clang-0.2.1, ms-vscode.cpptools-0.9.2, ms-vscode.typescript-javascript-grammar-0.0.4, msjsdiag.debugger-for-chrome-1.1.0, tnaseem.theme-seti-0.0.2, vscodevim.vim-0.3.5, waderyan.gitblame-1.3.0

After update to 1.6 
all thing seems as `{}`

![](http://o8z0dg641.bkt.clouddn.com/QQ20161011-2@2x.png)

**Comment by jrieken** [comment]
@leaxoy Please, it's called *reproducible steps*

**Comment by leaxoy** [comment]
Just open vscode-go project with all typings file downloaded,  and this appears.
PS: [deps] typescript version is 2.0.3 and vscode version is 1.0.0.

**Comment by jrieken** [comment]
Not for me

![screen shot 2016-10-11 at 13 04 47](https://cloud.githubusercontent.com/assets/1794099/19268199/4e01c95c-8fb3-11e6-92d3-966f3cef6162.png)

**Comment by leaxoy** [comment]
Do you use the latest of typescript and vscode dependencies?

**Comment by jrieken** [comment]
Closing until steps allowing to reproduce this are supplied
