### ISSUE TITLE
Showing false error

### ISSUE THREAD

**Issue by Menor25** [microsoft/vscode#134705]
Issue Type: <b>Bug</b>

Visual Studio Code is showing false error in php. I have unistall intellesense and it didnt stop it. I update my vscode, still the problem continue. What should i do to savage the situation? I await your response. Thanks

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 540  @ 2.53GHz (4 x 2527)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.67GB free)|
|Process Argv|--crash-reporter-id 9d5b281c-ea2d-4387-bb59-2b88d33403a3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
GetterAndSetterGenerator|afm|1.0.3
project-manager|ale|12.4.0
laravel-extra-intellisense|ami|0.6.1
laravel-blade-spacer|aus|2.1.3
vscode-intelephense-client|bme|1.7.1
vscode-tailwindcss|bra|0.7.0
c-compiler|bra|0.0.4
gitignore|cod|0.7.0
laravel-goto-view|cod|1.3.4
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.2.1
git-extension-pack|don|0.1.3
githistory|don|0.6.18
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
vscode-phpmd|eco|1.3.0
vscode-great-icons|emm|2.1.79
prettier-vscode|esb|9.0.0
php-debug|fel|1.19.0
php-pack|fel|1.0.2
auto-close-tag|for|0.5.12
code-runner|for|0.11.5
vscode-pull-request-github|Git|0.31.0
php-snippets|heb|0.0.3
phpcs|ika|1.0.5
vscode-gutter-preview|kis|0.27.1
vscode-github|Kni|0.30.6
vscode-phpfmt|kok|1.0.30
code-beautifier|mic|2.3.3
vscode-docker|ms-|1.17.0
csharp|ms-|1.23.15
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.4
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
cpptools|ms-|1.6.0
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.7.0
laravel-blade|one|1.25.0
laravel5-snippets|one|1.13.0
material-icon-theme|PKi|4.10.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
laravel-artisan|rya|0.0.28
git-merger|sha|0.4.1
phpcs|she|1.0.8
code-spell-checker|str|2.0.9
vscodeintellicode|Vis|1.2.14
vsc-php-snippets|vsc|0.0.30
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.5
vscode-maven|vsc|0.34.0
php-sniffer|won|1.3.0
JavaScriptSnippets|xab|1.8.0
emmet-live|yse|1.0.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30378365
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis400:30374798
vsaa593cf:30376535

```

</details>

**Comment by gjsjohnmurray** [comment]
I suggest you use the Start Extension Bisect command from Command Palette to investigate.

**Comment by Menor25** [comment]
It is a PHP code. Code is correct and running properly but vscode is
showing red like there is an error all over the code.
