### ISSUE TITLE
revealCursor moves the cursor to the first non-whitespace character

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#134773]
From @ygoe

---
From https://github.com/microsoft/vscode/issues/132156#issuecomment-939088767

Almost perfect in version 1.61: While the cursor remains at the same column as good as it can, it will move one line up if it was in the last empty line of a document, even before the cursor leaves the viewport. Not as annoying as before but still strange.

---
From https://github.com/microsoft/vscode/issues/132156#issuecomment-939096386

I've just found a similar situation. I wanted Ctrl+PgUp/Down to behave as in Visual Studio. (*) I used this code, based on something I found, fixed to not scroll down a line for partially visible lines at the bottom.

```
	{
		"key": "ctrl+pageup",
		"command": "cursorMove",
		"args": {
			"to": "viewPortTop"
		},
		"when": "editorTextFocus"
	},
	{
		"key": "ctrl+pagedown",
		"command": "cursorMove",
		"args": {
			"to": "viewPortBottom",
			"value": 2
		},
		"when": "editorTextFocus"
	},
```

(The "value" parameter fixes the undesired scrolling.)

Again, the cursor is moved to the first non-whitespace character of the first or last visible line, respectively, no matter where it was before. There seems to be a pattern behind this. I just can't figure out what use that should have. Is that "first non-whitespace position" thing somehow intentional and we broke it now? Or is it a systematic error that might still appear in many other places?

*) Judging by the similarities in the keyboard hotkeys, VSCode should not have the name "Visual Studio" in it. There's almost no similarity, not even by Windows UI standards (Alt+Backspace isn't working by default).

**Comment by alexdima** [comment]
Looking at the PR that initially added these commands, this appears to be intentional: https://github.com/microsoft/vscode/pull/9536

**Comment by ygoe** [comment]
That's still annoying. How can I change that or will I have to live with it?

**Comment by alexdima** [comment]
IIRC we added the `viewPortTop`, `viewPortBottom` and `viewPortCenter` arguments to support specific vim motions and the intent was that the vim extension would invoke those commands. Modifying them would break the vim extension. I wonder if you could use the `editorScroll` command for your use case?

```
	{
		"key": "ctrl+up",
		"command": "editorScroll",
		"when": "editorTextFocus",
		"args": 
		{
			"to": "up",
			"by": "page",
			"revealCursor": true
		}
	},
	{
		"key": "ctrl+down",
		"command": "editorScroll",
		"when": "editorTextFocus",
		"args": 
		{
			"to": "down",
			"by": "page",
			"revealCursor": true
		}
	},
```
