### ISSUE TITLE
Incorrect Java syntax highlighting for parentheses inside strings inside parentheses beginning a new line

### ISSUE THREAD

**Issue by david-russo** [Microsoft/vscode#13489]
- VSCode Version: 1.6.0
- OS Version: Windows 7 (64-bit)

Steps to Reproduce:

1. Open a new file a select the Java language mode
2. Paste the following code into the editor:

```java
new String 
    ("(A)" + "B");
new String("Following line");
```

"String", the quoted string literal, and all syntax following this line will be miscoloured. Compare:

```java
new String("(A)" + "B");
new String("Following line");
```

![java-syntax-highlighting-problem](https://cloud.githubusercontent.com/assets/757021/19267853/f303aebc-8fa8-11e6-8e64-57dbce4b9b97.png)

Interestingly, GitHub's colourizer also seems to suffer from the same issue.

**Comment by aeschli** [comment]
This issue was moved to textmate/java.tmbundle#46

**Comment by david-russo** [comment]
There already seems to be [an issue there from 2014](https://github.com/textmate/java.tmbundle/issues/28) relating to this. And having the issue closed here, where's it's causing a problem, signals to me that no one here is interested in getting this problem fixed... Am I wrong, or is this essentially being ignored?
