### ISSUE TITLE
html files autocomplete can't work

### ISSUE THREAD

**Issue by minjunlan** [Microsoft/vscode#13481]
- VSCode Version: Code - Insiders 1.7.0-insider (cf203e09145586b96497eab230253d686c2b2a2d, 2016-10-11T06:11:07.928Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: aeschli.vscode-css-formatter-0.0.2, christian-kohler.npm-intellisense-0.1.3, christian-kohler.path-intellisense-1.0.2, DSKWRK.vscode-generate-getter-setter-0.3.4, eg2.tslint-0.5.39, hnw.vscode-auto-open-markdown-preview-0.0.3, ikappas.phpcs-0.6.1, johnpapa.Angular2-1.0.2, Kasik96.format-indent-1.3.0, lukehoban.Go-0.6.43, MattiasPernhult.vscode-todo-0.8.0, mattn.Runner-0.1.12, mohsen1.prettify-json-0.0.3, ms-vscode.csharp-1.4.1, ms-vscode.Theme-MarkdownKit-0.1.1, nwallace.language-vscode-javascript-angular2-0.0.11, odonno.new-cmd-0.2.0, plrenaudin.gotolastedit-0.2.1, qinjia.filenamecomplete-0.0.3, qinjia.view-in-browser-0.0.3, reflectiondm.ClassyNaming-1.0.0, saviorisdead.RustyCode-0.18.0, Telerik.nativescript-0.3.1, tht13.html-preview-vscode-0.0.3, vstirbu.vscode-mermaid-preview-0.4.1, wcwhitehead.bootstrap-3-snippets-0.0.7, wwwalkerrun.nativescript-ng2-snippets-1.2.0, zhuangtongfa.Material-theme-1.0.3, Zignd.html-css-class-completion-1.0.3

Steps to Reproduce:

1.use any path autocomplate in html , i.e  christian-kohler.path-intellisense
2.can't work

**Comment by aeschli** [comment]
You have to file this issue against the extension, e.g. christian-kohler.path-intellisense.
HTML does not support path completion out of the box. The request for this is #2037
