### ISSUE TITLE
Double '' when writing a comment

### ISSUE THREAD

**Issue by br1luca** [Microsoft/vscode#13485]
- VSCode Version: 1.6.0
- OS Version: OS Sierra

Please, when i'm writing a comment i would like to have one ' instead of two.

**Comment by Zarel** [comment]
This would also be nice when writing a `"` or `` ` `` string.

**Comment by rmunn** [comment]
Probably related:

#8850
#8539
#11222
#10068

**Comment by jdforsythe** [comment]
+1 on this - at least for the apostrophe/single-quote. I'm not sure of the use case for not wanting two double-quotes or two back-ticks but I constantly write "can't" or the like in comments and get an extra apostrophe

**Comment by atif089** [comment]
+1

Also, happens during multiple selections on a file. I cannot use multiple selections (Ctrl+D) anymore because it messes up my code with double quotes.

**Comment by rebornix** [comment]
Can everyone share in which language you are running into this problem? It's configurable by language extension, for example, you don't see this issue any more in TypeScript as we already disable auto closing for comments. It can be done in other languages as well.

**Comment by atif089** [comment]
In my case it must have been either js or custom language (perl template)

**Comment by rebornix** [comment]
Since this issue is pretty old, I'd like to close it right now. If anyone can provide a valid repro step (with snippets) in latest Stable or Insider, please leave messages and I'll reopen.
