### ISSUE TITLE
How to set default selected suggestion?

### ISSUE THREAD

**Issue by CrisLi** [Microsoft/vscode#13486]
- VSCode Version: 1.6.0
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. Install Reactjs snippets extension.
2. Change the user config `"editor.snippetSuggestions": "top"`.
3. Type rcc in a new jsx file

The snippet suggestion for the react is on the TOP, but default selected suggestion is `RTCDtlsTransportStateChangedEvent`.

How to make the default selected suggestion is the snippet suggestion.
How to disable the suggestions such like `RTCIceCandidate` and `WebGLBuffer`? I don't use Web API too much.

<img width="560" alt="screen shot 2016-10-11 at 5 51 17 pm" src="https://cloud.githubusercontent.com/assets/360767/19266348/bda7e7c8-8fdb-11e6-8a13-5a327f37d4d3.png">

**Comment by jrieken** [comment]
The default pick is derived form the text before the cursor. We have recently (post 1.6) improved it so that now the best pick also includes snippets

![screen shot 2016-10-11 at 12 52 13](https://cloud.githubusercontent.com/assets/1794099/19267899/a1cfdf9e-8fb1-11e6-9366-ba0ffdae3861.png)

**Comment by CrisLi** [comment]
@jrieken  I am using VSCod 1.6.0 on OS X 10.11.5. Before 1.6.0, it worked fine. After I upgraded to 1.6.0, the suggestion of snippet is always not the default selected option. Do you think it will be issue of Reactjs snippets extension?

**Comment by CrisLi** [comment]
@jrieken As you can see in the screenshot, the `rcc` snippet is the one exactly match the text I typed. But the `RTCIceCandidatePair` is the default selected.

<img width="1036" alt="screen shot 2016-10-12 at 10 01 14 am" src="https://cloud.githubusercontent.com/assets/360767/19295427/1664c3c8-9067-11e6-891d-c80a9ecfbab5.png">

**Comment by jrieken** [comment]
Yes - I was talking about 1.7.0 insiders. More people are seeing this - we might consider for sept recovery (#13498)
