### ISSUE TITLE
Not displaying the current branch name of a workspace in source control but rather sharing a name to all repos

### ISSUE THREAD

**Issue by mateusmento** [microsoft/vscode#134818]
Issue Type: <b>Bug</b>

It seems that for all workspaces in source control is displaying the same branch name from the branch of the last interacted repo in source control. If I try to pull changes or refresh a repo, the all branch names displayed in the source control updates to the branch of that repo.

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (8.00GB free)|
|Process Argv|--crash-reporter-id 598151a0-f8d1-4ddc-bf94-e46736073071|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
beardedicons|Bea|0.14.0
gitlens|eam|11.6.1
vscode-great-icons|emm|2.1.79
vsc-material-theme-icons|equ|2.2.1
vscode-lombok|Gab|1.0.1
vue|jcb|0.1.5
cpptools|ms-|1.6.0
seti-icons|qin|0.1.3
fabric8-analytics|red|0.3.4
java|red|0.82.0
vscode-commons|red|0.0.6
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.5
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.0
snippet-generator|wen|0.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30378365
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis300:30374797
vsaa593cf:30376535
vssld246cf:30379912

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/134638#issuecomment-938471497 for a workaround.
