### ISSUE TITLE
Zoom In/Out should not modify whole window.

### ISSUE THREAD

**Issue by MiguelLattuada** [Microsoft/vscode#1348]
Editor window should not be modified when zooming in/out.
![screen shot 2015-12-15 at 5 46 52 pm](https://cloud.githubusercontent.com/assets/5618566/11824245/4003b19c-a357-11e5-85f1-1e78ada534bd.png)

**Instead of that, just code rows (.view-lines div) should be scaled (transformed or font resized).**
![screen shot 2015-12-15 at 6 02 23 pm](https://cloud.githubusercontent.com/assets/5618566/11824390/12ee72ea-a358-11e5-9c77-3e7fca40907d.png)

**This is kind of shortcut for resizing, does not mean anything.**
![screen shot 2015-12-15 at 6 15 24 pm](https://cloud.githubusercontent.com/assets/5618566/11824463/6f3bb0c6-a358-11e5-841e-6d112160eac9.png)

**And sure, kind of zoom status should be displayed at the bottom status bar.**
![screen shot 2015-12-15 at 6 04 12 pm](https://cloud.githubusercontent.com/assets/5618566/11824409/34074984-a358-11e5-97c3-1de38faee6c6.png)
- Images under bolded text, has been modified.

**Comment by stkb** [comment]
Don't agree: the current zoom behavior is exactly what I want. You can always change the ```editor.fontSize``` setting for larger or smaller editor text. Though it's true that there aren't shortcut keys for that.

**Comment by dbaeumer** [comment]
@alexandrudima assigning to you because of the short cut request.

**Comment by stkb** [comment]
I should add though, thanks to the new persisted ```window.zoomLevel``` setting, it's now more a set-and-forget thing for me. So as long as that stays, I wouldn't mind if the existing ```ctrl+-/=``` shortcuts were remapped to just change the editor text size instead.

**Comment by gamtiq** [comment]
> Don't agree: the current zoom behavior is exactly what I want.

+1
It's quite a useful feature.
Unfortunately zoom level that is set in work session isn't restored after VS Code is closed and the reopened (#291).

**Comment by purplecabbage** [comment]
+1 Please map ctrl+- to editor view, or better yet, whichever view has focus.
The icons in the top left changing size makes it obvious that the whole window is just one big webview ...
personally, I would not expect the icons to be zoomable via ctrl-+

**Comment by anyong** [comment]
I would really like to be able to set CTRL+/- to increase `editor.fontSize` and `editor.lineHeight` equally. The current zoom behavior is not good for me, because I work with different languages and some have characters with smaller fonts (Thai, Chinese) and I would like to be able to easily increase the font size when working with those characters.

I recently looked into hacking this out in an extension, only to find out that it's basically impossible to set a user preference via an extension (which makes sense), so it appears there's currently no way to do this.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

Based on issue #14979 with [comment](https://github.com/Microsoft/vscode/issues/14979#issuecomment-259390808).

1- Ctrl + + It should zoom in on the editor, the file we're moving, not the zoom of the whole program.
2- Ctrl + - You should zoom out within the editor, the file you are moving, not the zoom of the entire program.
3- Ctrl + 0 You should zoom back to the default, the file you are moving, not the zoom of the entire program.

4- Ctr + +, Ctr + - should work the same way when we use "editor.mouseWheelZoom", by only zooming the file. And using Ctrl + 0 returns to the default.

5- Ctr + = You should do nothing. The zoom continues. You must unlink this function.
6- Ctrl + 0 of the non-numeric keyboard does not reset the zoom.

These shortcut keys should be valid for both numeric and non-numeric keys. In the menu you should change the registration `Ctr + =` by `Ctrl + +`

Why not set specific sizes for the UI? Maybe some [problems](https://github.com/Microsoft/vscode/issues/14979#issuecomment-265772474) mentioned by @alexandrudima would decrease!!

> In fact I am 100% in favor of eliminating the entire UI zoom we're shipping with, it causes many issues with font anti-aliasing for example and I have to maintain extraneous code to work around it (i.e. not using translate3d when the UI zoom is not 100%)

Example: Small, Normal, Large, Extra large. To set proportions, do a search with someone who uses sizes other than their normal size.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
