### ISSUE TITLE
New version has an error that prevents "Find in Files"

### ISSUE THREAD

**Issue by mesosteros** [Microsoft/vscode#13482]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: abusaidm.html-snippets-0.0.16, akamud.vscode-javascript-snippet-pack-0.1.5, christian-kohler.path-intellisense-1.0.0, dbaeumer.jshint-0.10.15, dbaeumer.vscode-eslint-1.0.7, eg2.tslint-0.5.39, florentulve.vstortoise-0.6.0, HookyQR.beautify-0.4.0, johnpapa.Angular1-0.1.16, ms-vscode.csharp-1.4.1, ms-vscode.mono-debug-0.11.0, msjsdiag.debugger-for-chrome-1.1.0, oderwat.indent-rainbow-0.4.1, qinjia.view-in-browser-0.0.3, sandcastle.whitespace-0.0.4, sandy081.todotasks-0.4.0, seanmcbreen.Spell-0.8.6, sidthesloth.html5-boilerplate-1.0.1, wcwhitehead.bootstrap-3-snippets-0.0.7

Steps to Reproduce:

1. CTRL+SHIFT+F or the Edit > Find in Files option
2. Error message displays: "Cannot read property 'toCustomLabel' of undefined"

**Comment by isidorn** [comment]
Looks like a dup of https://github.com/Microsoft/vscode/issues/13447

**Comment by mesosteros** [comment]
@isidorn It is. I had not seen that other issue yet.

**Comment by isidorn** [comment]
Closing this as a duplicate then
