### ISSUE TITLE
[themes] Accessibility: High Contrast White

### ISSUE THREAD

**Issue by ncthbrt** [microsoft/vscode#134823]
I use the high contrast color theme, however in certain lighting conditions (namely in very bright light), the colour scheme becomes very hard to read. It'd be great to also have a white version of the high contast mode as well, for these situatiohns

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
The only ideal solution to this problem isautomatic adaptation to the high-contrast theme of the system, because otherwise this solution is only partially more improvemental.

**Comment by ncthbrt** [comment]
I would agree. I do alternate between OS level high contrast dark/light depending on the conditions. So that would be a suitable solution for me.
