### ISSUE TITLE
Source control displays wrong status for git repository

### ISSUE THREAD

**Issue by beyse** [microsoft/vscode#134887]
Issue Type: <b>Bug</b>

Step 1: Open a folder which contains two different git repositories (each in its own sub-folder). 
Step 2: Make a change to a file in one of the git repositories. Do not change the other. 
Step 3: Open the SOURCE CONTROL tab on the left (Ctrl+Shift+G) in VSCode.
Step 4: Stage the file with the change. Write a commit message and commit that change to your local repo.
Step 5: Push the change using the "Synchronize Changes" button in the tab.

Observed result:
1) A "synchronize" animation is displayed for all two repositories.
2) Also an indication that 1 Commit is currently being pushed is shown for both repositories, not just the one where the commit actually happened.

Expected result:
1) A "synchronize" animation is displayed for only the one repository where the push is actually happening, not for both.
2) An indication that 1 Commit is currently being pushed is shown for only the one repository, where the commit actually happened, not for both. 

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (20.25GB free)|
|Process Argv|. --crash-reporter-id ad4019e1-b24f-4aee-90c8-e578f12a6132|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
git-temporal-vscode|bee|1.0.0
vscode-path-tools|cg-|0.0.4
doxdocgen|csc|1.3.2
gitlens|eam|11.6.1
json-tools|eri|1.0.2
vscode-diff|fab|1.4.2
vscode-pull-request-github|Git|0.31.0
better-cpp-syntax|jef|1.15.10
vscode-graphviz|joa|0.0.6
guid|kos|0.0.1
git-graphy|mar|1.0.14
indent-nested-dictionary|mge|0.0.1
git-graph|mhu|1.30.0
binary-viewer|mom|0.0.1
python|ms-|2021.10.1317843341
vscode-pylance|ms-|2021.10.0
jupyter|ms-|2021.9.1001312534
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.202.1
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
cmake-tools|ms-|1.8.1
cpptools|ms-|1.6.0
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4962
vsliveshare-audio|ms-|0.1.91
beautify-json|ran|1.0.2
protobuf-helper|rip|0.2.9
markdown-preview-enhanced|shd|0.6.0
vscode-hexdump|sle|1.8.1
cython|tcw|0.1.0
remove-whitespace-aka-join-words|tnr|0.0.1
pdf|tom|1.1.0
cmake|twx|0.0.17
sort-lines|Tyr|1.9.0
change-case|wma|1.0.0
clang-format|xav|1.9.0
vscode-proto3|zxh|0.5.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30378364
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis200:30374795
vsaa593cf:30376535
vssld246cf:30379912

```

</details>

**Comment by sperry94** [comment]
I am also seeing this issue. In addition to the behavior described above, I am also seeing the current branch name being affected:

Repo A with branch A
Repo B with branch B

Observed result:
1. Both Repo A and Repo B will show current branch as A
2. Pressing refresh on Repo B will update the display for both Repo A and B to show branch B
3. Pressing refresh on Repo A will update the display for both Repo A and B to show branch A
4. New branch in either Repo A or B will also the display for both repositories

Doesn't seem to actually be applying these changes in the Git repo, just in the display

Expected result:
1. Repositories always show their current branch names

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/134638#issuecomment-938471497 for a workaround.

Scheduled to be fixed in upcoming recovery release.
