### ISSUE TITLE
ESlint: using an async function as a Promise executor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#134873]
You are in this issue because you have code that violates this new ESLint rule: https://eslint.org/docs/rules/no-async-promise-executor

Using `async` in the `Promise` executor is dangerous because any exception that is raised from the executor will end up as unhandled promise rejection.

* [x] [`macAddress.ts`](https://github.com/microsoft/vscode/blob/3fb483e7fff42559b5f93e8aa92d0354021ee5ff/src/vs/base/node/macAddress.ts#L21) @sbatten
* [x] [`externalTerminalService`](https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/externalTerminal/node/externalTerminalService.ts#L276) @Tyriar 
* [x] [`diagnosticsService`](https://github.com/microsoft/vscode/blob/9e5ee5521a2142d4314660ce1d022082e61f137a/src/vs/platform/diagnostics/node/diagnosticsService.ts#L69) @Tyriar 
* [x] [`tunnel`](https://github.com/microsoft/vscode/blob/a15378a9db1d0546f43f0d18f9ebff5de3c865b4/src/vs/platform/remote/common/tunnel.ts#L221) @alexdima 
* [x] [`requestService`](https://github.com/microsoft/vscode/blob/c70170a480419639005f1a9d166885063016e1bd/src/vs/platform/request/node/requestService.ts#L101) @chrmarti 
* [x] [`ptyService`](https://github.com/microsoft/vscode/blob/1f2103f8faf59075aec8e3a0d64b9e1c800f466c/src/vs/platform/terminal/node/ptyService.ts#L107) @Tyriar 
* [x] [`windowsShellHelper`](https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/terminal/node/windowsShellHelper.ts#L131) @Tyriar 
* [x] [`mainThreadTerminalService`](https://github.com/microsoft/vscode/blob/9b196d5fd23ccf31a9a3e32dc75c2fb6f90471f9/src/vs/workbench/api/browser/mainThreadTerminalService.ts#L143) @Tyriar 
* [x] [`extHostTask`](https://github.com/microsoft/vscode/blob/4a67ae2ade8d7d272542c9b7550212b9aefd92ad/src/vs/workbench/api/common/extHostTask.ts#L645) @alexr00 
* [x] [`extHostTerminalService`](https://github.com/microsoft/vscode/blob/8b9aed760a815ce90a858639a837fec808757c54/src/vs/workbench/api/common/extHostTerminalService.ts#L719) @Tyriar 
* [x] [`debugTaskRunner`](https://github.com/microsoft/vscode/blob/e6e61368ff5ed7765dddc4bac36563c3c2771748/src/vs/workbench/contrib/debug/browser/debugTaskRunner.ts#L203) @alexr00 
* [x] [`terminals`](https://github.com/microsoft/vscode/blob/b989bc6f78624c6bea3ee6aea843a3181edfad69/src/vs/workbench/contrib/debug/node/terminals.ts#L56) @Tyriar 
* [x] [`outputChannelModel`](https://github.com/microsoft/vscode/blob/f43d80f02f161d3cb1274b7338d07c1de00a607a/src/vs/workbench/contrib/output/common/outputChannelModel.ts#L225) @sandy081 
* [x] [`keybindingWidget`](https://github.com/microsoft/vscode/blob/bff1cf8076d7978fd9af76f4e6e60fbf44a5b5da/src/vs/workbench/contrib/preferences/browser/keybindingWidgets.ts#L228) @sandy081 
* [x] [`tunnelFactory`](https://github.com/microsoft/vscode/blob/a15378a9db1d0546f43f0d18f9ebff5de3c865b4/src/vs/workbench/contrib/remote/common/tunnelFactory.ts#L54) @alexdima 
* [x] [`remote`](https://github.com/microsoft/vscode/blob/6e84c224f443f863954e7b47dc1192a777b49942/src/vs/workbench/contrib/remote/browser/remote.ts#L268) @alexdima 
* [x] [`insertSnippet`](https://github.com/microsoft/vscode/blob/ad312980ae18e555e32bf5168a31e0faffa2a878/src/vs/workbench/contrib/snippets/browser/insertSnippet.ts#L93) @jrieken 
* [x] [`abstractTaskService`](https://github.com/microsoft/vscode/blob/d4c222488de817d491f7c5686cf1161e9cceb7d4/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L929) @alexr00 
* [x] [`abstractTaskService`](https://github.com/microsoft/vscode/blob/d4c222488de817d491f7c5686cf1161e9cceb7d4/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L2364) @alexr00 
* [x] [`abstractTaskService`](https://github.com/microsoft/vscode/blob/d4c222488de817d491f7c5686cf1161e9cceb7d4/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L3039) @alexr00 
* [x] [`terminalInstance`](https://github.com/microsoft/vscode/blob/b0c930bdbb865ff18fb6f5d93c59e5dfdb79d7ed/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L599) @Tyriar 
* [x] [`workspace.contribution`](https://github.com/microsoft/vscode/blob/a91a307436c31831705a19a7c862a367145b1e11/src/vs/workbench/contrib/workspace/browser/workspace.contribution.ts#L283) @lszomoru 
* [x] [`treeView`](https://github.com/microsoft/vscode/blob/a5c8bc90f196e591fe467e1a61355de0592191ac/src/vs/workbench/browser/parts/views/treeView.ts#L922) @alexr00 
* [x] [`simpleFileDialog`](https://github.com/microsoft/vscode/blob/23f8788a8b167ef8ec597967374c96bd27d456aa/src/vs/workbench/services/dialogs/browser/simpleFileDialog.ts#L269) @alexr00 
* [x] [`localFileSearch`](https://github.com/microsoft/vscode/blob/b71da6410350696e3ed6eed4108d4d5ac53a7f6c/src/vs/workbench/services/search/worker/localFileSearch.ts#L219) @JacksonKearl 
* [x] [`bulkEditPreview`](https://github.com/microsoft/vscode/blob/2dfc39c6949f32c21ee56b5ed85f96cfbedfae34/src/vs/workbench/contrib/bulkEdit/browser/preview/bulkEditPreview.ts#L432) @jrieken 
* [x] [`walkThroughContentProvider`](https://github.com/microsoft/vscode/blob/15ecc8de589969a9be8bded54e1c1312d53bbeec/src/vs/workbench/contrib/welcome/walkThrough/common/walkThroughContentProvider.ts#L57) @JacksonKearl 
* [x] [`AADHelper`](https://github.com/microsoft/vscode/blob/15616f8d9368ef676f80227a646113e8b6bf161d/extensions/microsoft-authentication/src/AADHelper.ts#L319) @TylerLeonhardt 
* [x] [`extension`](https://github.com/microsoft/vscode/blob/d02ba4670428fe7021ed601e6edcc030663a85d5/extensions/vscode-test-resolver/src/extension.ts#L27) @aeschli 
* [x] [`extension`](https://github.com/microsoft/vscode/blob/d02ba4670428fe7021ed601e6edcc030663a85d5/extensions/vscode-test-resolver/src/extension.ts#L133) @aeschli 
* [x] [`validationProvider`](https://github.com/microsoft/vscode/blob/b35a7919879d8ddaf3f5c9444da7b4b96a9e5a28/extensions/php-language-features/src/features/validationProvider.ts#L177) @roblourens

**Comment by sandy081** [comment]
@bpasero I assume this adoption is to use the utility even though it is being handled correctly

https://github.com/microsoft/vscode/blob/3cda269c800d40446613722c528d0f8ba0377bc1/src/vs/workbench/contrib/output/common/outputChannelModel.ts#L226-L242

**Comment by bpasero** [comment]
@sbatten @alexr00 @lszomoru friendly reminder to look into this during debt week

**Comment by lszomoru** [comment]
Fixed the last item with c7a84f93d36a052754a21b4f2086c2e7559b397b. Closing the issue.
