### ISSUE TITLE
Control font size in suggest, hover, parameter hints widgets

### ISSUE THREAD

**Issue by OshotOkill** [microsoft/vscode#13480]
- VSCode Version: 1.6.0
- OS Version: Windows 10 14393.222

I appreciate that 1.6 improves Hover & IntelliSense UI which makes hints become more readable. However the IntelliSense & Snippets dropdowns seem not as good as before, since the font-size grows quite large:

![1](https://cloud.githubusercontent.com/assets/6079112/19264037/bca424e0-8fd1-11e6-865e-d0cd3bfe3779.png)

I have no idea whether the change was on purpose or not, shall we move this weird appearance back to normal ? Or maybe there could be a config option to adjust font-size in dropdowns.

**Comment by joaomoreno** [comment]
It isn't released in 1.5, but the insiders release has a `editor.suggestFontSize` setting which lets you control this. We might want to make this setting more general, to make it work for other widgets, so let's keep this issue open to fix that.

**Comment by anatsegev** [comment]
We also prefer the old appearance of the suggest widget.

1. We prefer the type label to be left aligned as before and blue.
2. The font size is too big.
3. We set lineHeight to 16 in  monaco.editor.create options. We need it for the editor , but with this setting the line height of each suggestion is too small. (not enough padding).

This is how the new suggest widget looks like in our project with the Monaco editor version 0.7.0:

![image](https://cloud.githubusercontent.com/assets/17318937/19524888/e5b89ed6-9627-11e6-8e4a-5eff305e242e.png)

After overriding some css we get to this:

![image](https://cloud.githubusercontent.com/assets/17318937/19525171/bfa592e8-9628-11e6-9d5a-60eef139d00d.png)

**Comment by winduptoy** [comment]
What about adjusting the maximum width for the widget? In most cases I can only see the first few characters in the name of the first parameter. I'd love to be able to see all of the parameters to a function.

**Comment by SuperV1234** [comment]
There also needs to be a way to control the font size of the documentation displayed when auto-completing, not only the list of items. And also the size of the documentation box.

**Comment by ciel** [comment]
It would also be great if we could adjust the wrapping, and widget width. I'm so tired of this happening ...
![2017-08-21-19-34-001](https://user-images.githubusercontent.com/438196/29543595-cfaa52b2-86a7-11e7-8318-0eedb8272efe.png)

I prefer the code to be pretty large font, but I'd really appreciate being able to tool all of these pop-ups with thinner fonts, and better layout control overall.

**Comment by octref** [comment]
Suggest widget is already very different today. Please open new feature requests.
