### ISSUE TITLE
Built-in extensions lose their translations during build

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#13488]
cc @weinand @dbaeumer

**Comment by weinand** [comment]
@joaomoreno we should backport this to the 1.6 branch because @dbaeumer already got new translations for 1.6 which only make sense if they are not overwritten by the build process.

**Comment by joaomoreno** [comment]
Cherry-picked to e2c3fb6. @weinand Don't forget to change the version numbers of the extensions.

**Comment by weinand** [comment]
verified on macOS, linux64 and Windows.
