### ISSUE TITLE
can't move a folder to root with drag or cut/paste

### ISSUE THREAD

**Issue by mhamri** [microsoft/vscode#134877]
just try to drag one folder out to root, it will get locked and eventually it shows an error

https://user-images.githubusercontent.com/8991783/136927074-dc37034b-f425-4766-aee9-d9b8d1e82854.mp4

 extensions are disabled?: No

Version: 1.61.0 (user setup)
Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date: 2021-10-07T18:13:09.652Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by mhamri** [comment]
look like the issue is not drag/drop, but copying a folder from another vscode instance into another instance lock the folder completely

**Comment by JacksonKearl** [comment]
> look like the issue is not drag/drop, but copying a folder from one vscode instance (source) into another instance (destination), lock the folder completely and doesn't let in the destination instance after paste, move it to another folder.

I am not sure what you mean by this and I am not able to reproduce the issue by following the steps in the recording above. Could you include a recording of the entire set of steps that results in this?

**Comment by mhamri** [comment]
i tried it again with two fresh drive and it didn't happen, probably something was wrong at my side. sorry
