### ISSUE TITLE
Can anyone bundle marketplace plugins with the install?

### ISSUE THREAD

**Issue by Jackbennett** [Microsoft/vscode#13484]
- VSCode Version: 1.6
- OS Version: windows 7 x64

On the release notes [you can bundle extensions](https://code.visualstudio.com/updates/v1_6#_builtin-extensions) and I wondered if that's exposed in the installer in some way? Having trouble finding any docs.

I want to put the python extensions onto all the computers here as our mandatory profiles wipe their installed locations for users.

**Comment by joaomoreno** [comment]
This feature is build-time, not meant for redistributing Code with extra extensions.

If you provide Code to your computers in a ZIP archive, feel free to add extensions in the `extensions` folder of that ZIP.
