### ISSUE TITLE
SCM: Fine grained provider.onDidChange event

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#134885]
From https://github.com/microsoft/vscode/pull/134881, we left a [TODO](https://github.com/microsoft/vscode/blob/3c1274461db33dec3be39c9d58b62c8326e40b64/src/vs/workbench/contrib/scm/browser/scmRepositoryRenderer.ts/#L114) behind.

Suggestion:

2. Enrich the [`onDidChange`](https://github.com/microsoft/vscode/blob/3c1274461db33dec3be39c9d58b62c8326e40b64/src/vs/workbench/contrib/scm/common/scm.ts/#L70) event to include details on what features have changed.
3. Make sure listeners only react when features interesting to them have actually changed.
4. Remove the TODO, and verify the issue is still fixed.

**Comment by lszomoru** [comment]
This has been done as we have adopted observables.
