### ISSUE TITLE
Custom hovers on extension list and status bar stopped working

### ISSUE THREAD

**Issue by yume-chan** [microsoft/vscode#134808]
Issue Type: <b>Bug</b>

Hover on item in extension list: nothing happens

![image](https://user-images.githubusercontent.com/1330321/136821874-0402865b-bd14-44f7-9fde-67702d8154b5.png)

Hover on status bar item with custom hover: nothing happens

![image](https://user-images.githubusercontent.com/1330321/136821938-4d938fcb-68ed-4b70-90e8-9a7185739d36.png)

VS Code version: Code - Insiders 1.62.0-insider (e96a97448aae1572246bf7c438b7c2ee68a964c0, 2021-10-11T05:16:36.885Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (21.09GB free)|
|Process Argv|--crash-reporter-id 549e7bb8-b8be-425a-81f8-9316a0f7060a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-repl|ach|0.7.2
Bookmarks|ale|13.2.2
gitlens|eam|11.6.1
copilot-nightly|Git|1.5.3015
remotehub|Git|0.15.0
rest-client|hum|0.24.5
monkey-patch|ioc|0.1.15
search-node-modules|jas|1.3.0
vscode-docker|ms-|1.17.0
vscode-edge-devtools|ms-|1.3.1
remote-containers|ms-|0.202.1
remote-ssh-edit-nightly|ms-|2021.10.5220
remote-ssh-nightly|ms-|2021.10.5220
remote-wsl|ms-|0.58.2
hexeditor|ms-|1.8.2
js-debug-nightly|ms-|2021.10.817
vscode-typescript-next|ms-|4.5.20211010
debugger-for-edge|msj|1.0.15
vetur|oct|0.34.1
explorer-exclude-vscode-extension|Red|1.2.0
reveal|smu|1.2.7
luna-paint|Tyr|0.10.0
vscode-icons|vsc|11.6.0
cloudmusic|YXL|9.2.4
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.13.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythonvspyt639:30291487
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30377800
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsqsis300:30374797
vsaa593cf:30376535

```

</details>

**Comment by aeschli** [comment]
dup of #134808
