### ISSUE TITLE
[Source Control]Additional list of modifications is required.

### ISSUE THREAD

**Issue by qq326943819** [microsoft/vscode#134871]
Issue Type: <b>Feature Request</b>

I hope to have the function of extra list like git tortoise's submission list, which can be used to place some files that I will not submit for a long time, most of which are environment files. The files in this list will not be included when I press Ctrl+Enter to use "smart commit" after I type the message in commit message, unless I manually remove them.

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by lramos15** [comment]
Since this isn't part of the normal git workflow there are no current plans to include it in the git extension. Another extension could solve this nicely for you
