### ISSUE TITLE
vscode always auto change display Language to default

### ISSUE THREAD

**Issue by llk2yq** [microsoft/vscode#134844]
Issue Type: <b>Bug</b>

After update vscode, or restart vscode, the display Language  of vscode always auto changes to default.

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by llk2yq** [comment]
1. Install vscode, install `Chinese (Simplified) (简体中文) Language Pack for Visual Studio Code` extension.
2. Press `F1` and choose `Configure Display Language` and choose `zh-cn`.
3. When there is an update, click setting icon to update vscode and restart.
4. The Language will set to `en`, not `zh-cn`, I need to set it to `zh-cn` again by press `F1`.

**Comment by llk2yq** [comment]
The latest version(1.62.0) has the same problem.

**Comment by funnywwh** [comment]
1.检查根目录有没有.git
2.或者在package.json添加scripts 
"buildwin64":"BUILD_SOURCEVERSION=$(git log -1 --format=format:\"%H\") node --max_old_space_size=8192 ./node_modules/gulp/bin/gulp.js vscode-win32-x64-min",
目的是在product.json中自动产生commit字段
