### ISSUE TITLE
HTML header contents in markdown notebook cells not correctly populated in breadcrumbs

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#134853]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: github.dev
- OS Version: Windows 10

Steps to Reproduce:

1. Visit https://github.dev/lostintangent/python-tuples
2. Select any of the markdown cells
3. 🐛 breadcrumb preview says 'empty cell', this is apparently because the cell headers are created with HTML; if I rewrite them to be Markdown the breadcrumbs are accurate
![image](https://user-images.githubusercontent.com/30305945/136889752-2f099e4c-1ae0-48ed-93a9-9e00a4a6fba3.png)

**Comment by mjbvz** [comment]
Here's the relevant code:

https://github.com/microsoft/vscode/blob/5c8ba90f12af6cc02ceb40989b400ce77003fd1e/src/vs/workbench/contrib/notebook/browser/contrib/outline/notebookOutline.ts#L416

We currently only look for markdown headers. Instead, we'd likely want to get the headers from the rendered markup. That would nicely support other types of rendered markup or extensions to the markdown rendering

**Comment by IanMatthewHuff** [comment]
This would also be a big improvement for Outline view I believe. Jupyter picks up HTML headers and adds them to the table of contents view, but in VS Code we miss out on them so the structure looks funny with some notebooks.

**Comment by rebornix** [comment]
Pushed a fix to parse the content for h1 to h6 headers written as HTML tags. It's synchronous and performant, doesn't require the full rendering of all markdown cells either. The catch with this is we are only finding headers, the markdown cells with `<p>` will still be rendered as empty cells in TOC.

cc @mjbvz what's your recommendation of improving this further more? `marked` plaintext renderer will skip all `html` tags, does it mean to get proper gist of a markdown cell, we do need to have it rendered in the webview?

**Comment by mjbvz** [comment]
@rebornix Do you mean handling cases where the user has written raw html tags inside their markdown? For that we could turn on `supportHtml`:

https://github.com/microsoft/vscode/blob/48f1eceabc5b354277fa881eb1f9d7aeaf9cb728/src/vs/base/browser/markdownRenderer.ts#L192

That will let the tags through, which I think is ok so long as are only looking at the tokens and not actually rendering the resulting html
