### ISSUE TITLE
Coffee script - Weird syntax highlighting

### ISSUE THREAD

**Issue by johnsoncze** [Microsoft/vscode#13483]
When color theme that highlights property name definition is selected and property name starts with ‘it’ and is indented, color highlighting is broken, see printscreen.

http://prntscr.com/csf61j

- VSCode Version: Version 1.6.0 (1.6.0)
- OS Version: OS X El Capitan Version 10.11.6

Steps to Reproduce:

1. Create coffee file
2. Write following code
```
item = yes
if item
  itemText = 'Yeah'
```

**Comment by aeschli** [comment]
I'm not able to reproduce this in the latest:
![image](https://cloud.githubusercontent.com/assets/6461412/19278261/df7c068a-8fdc-11e6-8990-bbfdc321d183.png)
