### ISSUE TITLE
Notebooks - Create new notebook not honoring default kernel 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#134830]
## Environment data

-   VS Code version: 1.61.0 - insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1001294413

## Steps to reproduce:

1. Create new notebook 
2. Select kernel is always available despite having the default kernel for jupyter notebooks selected 
![image](https://user-images.githubusercontent.com/19276747/135936848-6e5ba9f0-f775-4c78-bdd4-f64aea642392.png)

## Expected behavior

Notebook to be created with the default kernel selected 

## Actual behavior

Select kernel always available 
![image](https://user-images.githubusercontent.com/19276747/135936891-939c353b-618c-48f9-870c-d5171753193d.png)

*On a related note, is this a regression? Before core supported notion of default kernel, Jupyter extension used to automatically assign the kernel that was last used in a notebook.

**Comment by greazer** [comment]
Automatically selecting a kernel on a new notebook is something that the jupyter extension can't do on it's own. 

Related to #130946. We're also getting survey feedback asking for this.

**Comment by DonJayamanne** [comment]
@claudiaregio @greazer heres an issue used to track configuring default kernels https://github.com/microsoft/vscode/issues/130946

**Comment by burkeholland** [comment]
Ran into this in the Golden Scenario. It seems odd to me to pick a different interpreter for Notebooks that are in the same "project" if you will. It also takes several seconds for VS Code to connect to the interpreter.

https://user-images.githubusercontent.com/686963/144905828-3819b31c-ec38-4543-932d-85c332e3a4b5.mp4

**Comment by xkz0777** [comment]
> Ran into this in the Golden Scenario. It seems odd to me to pick a different interpreter for Notebooks that are in the same "project" if you will. It also takes several seconds for VS Code to connect to the interpreter.
> 
>  select-interpreter.mp4

I'm learning d2l now and I also feel very inconvenient about it. Want some configuration options in the workspace's settings.json to solve this problem.

**Comment by DonJayamanne** [comment]
Given this is a very old issue and predates most of the kernel work done
I believe the underlying issue has been resolve since, or we can close this in favour of https://github.com/microsoft/vscode/issues/130946
