### ISSUE TITLE
Transparency Not going Even after clean reinstall and deleting the VSCode Settings 

### ISSUE THREAD

**Issue by dipankarcode** [microsoft/vscode#134804]
Issue Type: <b>Bug</b>

I earlier used an Extention [ GlassIt-VSC  ], I didn't Like It, thus uninstalled It, 
But its changes were not gone [ transparency was still there ] 
I reInstalled it to decrease the transparency as much as possible to make it look like Default VS Code, But Still, some transparency was there,
I Uninstalled VS Code, Deleted ALL its chaced Files, Reinstalled.
Then also that effect was not going away, 
I deleted the VS code Settings's JSON File's ALL content.
I thought Finally, I would be able to get rid of it, But It somehow again came back [ Transparency ] 😓

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.22471
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.43GB free)|
|Process Argv|--crash-reporter-id f8336d8a-9057-447d-bffc-03f4907b82e7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (67)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
codesnap|adp|1.3.4
include-autocomplete|ajs|0.0.4
icons-carbon|ant|0.2.4
vscode-django|bat|1.6.0
beardedicons|Bea|0.14.0
path-intellisense|chr|2.4.0
vscode-eslint|dba|2.2.1
competitive-programming-helper|Div|5.8.7
vscode-html-css|ecm|1.10.2
vscode-great-icons|emm|2.1.79
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.0.0
comment-anchors|Exo|1.9.6
vscode-install-vsix|fab|1.4.0
vscode-firefox-debug|fir|2.9.4
auto-close-tag|for|0.5.12
code-runner|for|0.11.6
c-cpp-runner|fra|1.4.1
mayukaithemevsc|Gul|3.0.1
cpp-reference|Guy|0.1.6
helium-icon-theme|hel|1.0.0
intalicons|int|1.5.0
path-autocomplete|ion|1.17.1
better-cpp-syntax|jef|1.15.10
vscode-peacock|joh|3.10.1
vscode-fix-checksums|leh|1.1.0
pop-n-lock-theme-vscode|Lux|3.32.7
fluent-icons|mig|0.0.12
theme-monokai-pro-vscode|mon|1.1.19
python|ms-|2021.11.1313923388-dev
vscode-pylance|ms-|2021.10.0
jupyter|ms-|2021.9.1001312534
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
cpptools|ms-|1.6.0
cpptools-extension-pack|ms-|1.0.0
js-debug-nightly|ms-|2021.10.817
vscode-typescript-next|ms-|4.5.20211010
debugger-for-edge|msj|1.0.15
color-highlight|nau|2.5.0
deepdark-material|Nim|3.3.0
material-icon-theme|PKi|4.10.0
polacode|pnp|0.3.4
try-material-icon-theme|raf|3.9.0
java|red|0.82.0
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.1.1
comment-divider|sta|0.4.0
tabnine-vscode|Tab|3.4.29
ayu|tea|1.0.5
html-preview-vscode|tht|0.2.5
c-cpp-flag-debugging|uts|0.0.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.5
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.0
vscode-icons|vsc|11.6.0
quokka-vscode|Wal|1.0.403
vscode-todo-highlight|way|1.0.4
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.13.2

(38 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30378365
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis400:30374798
vsaa593cf:30376535
vssld246:30379911

```

</details>

**Comment by connor4312** [comment]
Please open the issue on the glassit extension. It hacks into a lot of OS APIs and vscode internals. They may know how to successfully purge it.
