### ISSUE TITLE
Build Failure: VSCode Smoke Tests (Web)        Search

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#134904]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=138447&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=aaa04083-6c0b-5a33-e907-3d845b07f0b5

**Comment by roblourens** [comment]
Will add some retry, closing for https://github.com/microsoft/vscode/issues/132218 which has more details
