### ISSUE TITLE
Use different font for non-ASCII text

### ISSUE THREAD

**Issue by yamatsum** [microsoft/vscode#134960]
If it is not non-ASCII like iTerm, I want it to be displayed in a different font. 
In other words, I want to be able to set two fonts. Especially on the terminal
<img width="580" alt="CleanShot 2021-10-13 at 15 50 59@2x" src="https://user-images.githubusercontent.com/42740055/137081946-1b036475-b862-464f-b52a-f70af040f5ce.png">

**Comment by rublev** [comment]
desparately need this. options are between using terrible nerd hack font and rendering non-ascii "icons", or not rendering non-ascii "icons" and having my desired font:

1) 
![image](https://user-images.githubusercontent.com/470273/154184022-c5f18823-302e-4377-b5a2-f4445a173067.png)

2) 
![image](https://user-images.githubusercontent.com/470273/154184042-abd7f696-c8a3-45f7-8ab6-5537817aaedb.png)

**Comment by TFlaxx** [comment]
How about adding that font to your VSCode settings?

`"terminal.integrated.fontFamily": "'YourMainFontHere', 'Hack Nerd Font"`

**Comment by Tyriar** [comment]
I think since we have fallback already that should be sufficient for the majority of cases. I double checked and we explain fallback in the docs as well https://code.visualstudio.com/docs/terminal/appearance#_text-style
