### ISSUE TITLE
HTML folding not working as expected with unformatted code

### ISSUE THREAD

**Issue by milannankov** [Microsoft/vscode#13495]
- VSCode Version: 1.6.0
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Open test.html from the provided .zip file.
2. Try folding the first div (class="bars")
3. It seems that folding does not work when the code is not formatted correctly and it will stop at the first problematic element as demonstrated on the following screenshot.
![problematic-fold](https://cloud.githubusercontent.com/assets/2611068/19269108/2a041060-8fc1-11e6-8027-ee2b9e897bef.PNG)

Maybe that is expected but I think that it makes it difficult to work with random html files which might be an everyday life for some people. I would expect that the whole div is collapsed no matter what the formatting of the child elements is. Not sure if other people expect the current behavior. Ideally there might be an option that dictates different folding modes for HTML.

I hope that this is not a duplicate but I couldn't find this exact issue in the list. Thank you. 

[folding-issue.zip](https://github.com/Microsoft/vscode/files/521699/folding-issue.zip)

**Comment by aeschli** [comment]
The currently implemented folding strategy is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To be more smart and to, for example, understand html tags, we will have to go one step further and introduce language agnostic folding regions. We have issue #3422 for this.
