### ISSUE TITLE
Auto-formatting TSX removes signifigant whitespace

### ISSUE THREAD

**Issue by marcomorain** [Microsoft/vscode#13490]
When VSCode formats a TSX document it can remove significant white-space, altering the output of the program.

## VSCode Version: 

- Version: 1.6.0
- Commit: e52fb0bc87e6f5c8f144e172639891d8d8c9aa55
- Date: 2016-10-10T18:37:40.189Z
- Shell: 1.3.7
- Renderer: 52.0.2743.82
- Node: 6.5.0

## OS Version

- OS Name: Microsoft Windows 10 Pro
- Version: 10.0.14393 Build 14393

## Example code
File: https://gist.github.com/marcomorain/9b84f35ada35e0eceb030ff27fba2e1f

```tsx
import * as React from 'react'

var restaurantName = 'My Restaurant'
var closedAlert: JSX.Element = (
  <h4>{restaurantName} is Closed</h4>
)
```

## Steps to Reproduce:

1.  Open a `.tsx` file in vscode with some significant whitespace in a JSX element.
2.  Format the document (via command palette or format on save).

## Expected:

The space between `}` and `is Closed` is preserved, ultimately producing the string `My Restaurant is Closed`

## Actual

The space between `}` and `is Closed` is removed, ultimately producing the string `My Restaurantis Closed`

**Comment by waderyan** [comment]
@marcomorain thank you for opening this issue and for the clear bug report. I have confirmed this with the latest bits. Moving to the language service repo.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11619

**Comment by marcomorain** [comment]
Thanks Wes.

**Comment by marcomorain** [comment]
Auto-correct fail.

Thanks Wade!
