### ISSUE TITLE
Font size zooming with touchpads

### ISSUE THREAD

**Issue by elemongw** [Microsoft/vscode#13497]
Using a touchpad to zoom in or out is very hard as with the slightest movement the font changes by a lot. There is also no way to reset back to the original font size that I can find (and good luck doing it manually). If smooth scrolling can't be implemented at least the amount of zooming should be significantly decreased. I am using a macbook.
My suggestions are:
1) workbench.action.zoomReset should be binded by default to Cmd/Ctrl+0 (standard shortcut in all Apps)
2) workbench.action.zoomReset should probably also be used to reset the zoom level of the font
3) Smooth zooming of font size
I could do the work and submit a patch for the first two but I am not sure how to proceed with the third.

**Comment by fibric** [comment]
Setting `editor.mouseWheelScrollSensitivity` doesn't change the behavior for you? Setting it to maybe `0.1` is worth a try, IMO.

**Comment by elemongw** [comment]
That setting changes nothing as it isn't considered in the code for zooming. It is used only when scrolling.

**Comment by fibric** [comment]
Okay, got it.
You are right about the font. It's not reset when invoking `workbench.action.zoomReset`

```
[ 
  { "key": "ctrl+0", "command": "workbench.action.zoomReset" },
  { "key": "ctrl+shift+0", "command": "workbench.action.zoomReset" }
]
```

**Comment by bpasero** [comment]
@elemongw I think you are confusing the editor font zooming with the overall workbench zooming. the one is unrelated to the other and the actions for workbench zooming do not change anything in the editor zoom land.

Moving to Alex to decide if the editor zoom should be reset when the workbench zoom is reset.

**Comment by elemongw** [comment]
@bpasero I am not, my suggestions are about font zooming.

**Comment by alexandrudima** [comment]
Indeed, we have two parallel "zoom" stories:
* editor font zoom (only accessible when turning on the option `editor.mouseWheelZoom`):
  * it can only be triggered via `ctrl + mousewheel`
  * it has no UI indication that it is changed
  * it has no UI indication to reset or change it
  * it is not persisted
* workbench zoom
  * driven by the setting `window.zoomLevel`
  * has three actions, to increase, decrease and reset in the view menu
  * it is now persisted via settings

No editor I've ever used has the workbench zoom concept, but many have the editor font zoom concept. Our editor font zoom concept is a bit unbaked yet (it came in as a very targeted PR and was not driven by a story)

I think we need some UX guidance on how to proceed with both zoom concepts.

@bgashler1 @stevencl How should this work?

**Comment by elemongw** [comment]
editor font zoom:
- ability to increase, decrease and reset from the view menu and via shortcuts (cmd+-, cmd+=, cmd+0)
- not persisted
- turn editor.mouseWheelZoom on by default
workbench zoom
- driven by the setting window.zoomLevel
This is how I believe this should work (as workbench zoom feels more like an accessibility feature and having it accessible only from a setting seems enough). Considering no decision has been made yet, should I submit a pull request with these changes and then go from there?

**Comment by stevencl** [comment]
I don't have a strong opinion but it seems at first glance that we should at least have a way to reset the font zoom. I'm not convinced about resetting the font zoom when resetting the workbench zoom though. 

To begin with, I think we should keep the workbench and font zoom separate and see if we can take a small step to improve the overall experience by changing the property for editor zoom to match the window zoom so that it has a zoom level instead of just being enabled or disabled. Then 0 could reset the font zoom similarly to how it resets the workbench zoom.

I'd rather start with this than start by making more substantial changes.

**Comment by bgashler1** [comment]
I agree with Steven that we want to take a small incremental step before considering something big.  I think some way to reset the font zoom would be important.

Proposed keyboard shortcuts:

| Action  | Keyboard Shortcut |
| ------------- | ------------- |
| Font zoom  | <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>+</kbd>  |
| Font zoom **reset**  | <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>0</kbd>  |
| Window zoom  | <kbd>Cmd</kbd> + <kbd>+</kbd>  |
| Window zoom **reset**  | <kbd>Cmd</kbd> + <kbd>0</kbd>  |

Adding a <kbd>Shift</kbd> to window zoom commands could cause a change to font zoom instead and help you move in predictable increments like you can with window.

**Comment by fseitun** [comment]
I think this issue should be reopened, I have massive trackpad issues on a mac

**Comment by Noushad-web** [comment]
> I think this issue should be reopened, I have massive trackpad issues on a mac

Yeah me too, I'm also facing this issue in trackpad on a window and there is no way I can find to solve it.

**Comment by arjunivor** [comment]
Is it possible to map zooming to  `Cmd Shift +` incrementally? so instead of zooming by one or two it would increment through .1 .2 and so on, facilitating smooth zooming in and out.
