### ISSUE TITLE
Have multiple repositories open gives rendering issues wrt branch name and push state

### ISSUE THREAD

**Issue by wiljanvanravensteijn** [microsoft/vscode#134989]
Issue Type: <b>Bug</b>

Open 2 repositories , go to source control tab, switch branch on one of the repos, observe that "branch name" changes on all open repos to the selected branch, even though the branch does not even exist on the other repo. Similar issues occur with synchronizing changes

New on latest version

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/134638#issuecomment-938471497 for a workaround.

Scheduled to be fixed in upcoming recovery release.
