### ISSUE TITLE
handle localhost for `http.proxy` on remotes with `--use-host-proxy`

### ISSUE THREAD

**Issue by Banyc** [microsoft/vscode#134964]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.0
- OS Version: Windows 10

Steps to Reproduce:

1. Set "http.proxy" in settings, which should be a loopback address.
2. Reinstall c/cpp extension.
2. Wait for the extension to start downloading its internal packages.
3. In the "Output", the extension returns "Failed to establish a socket connection to proxies", where the address it tried to access is localhost.

I reckon that vscode doesn't realize the network domain of WSL2 is different from that of the host, not like WSL1.

**Comment by aeschli** [comment]
Isn't typically `http.proxy` the address of a machine in the network, accessible also from WSL2?
What's the point to set it to a loopback address?
What do you expect VS Code to do in WSL? Ignore the setting?

**Comment by Banyc** [comment]
@aeschli or it could treat WSL2 as a remote machine, allowing it set the value differently.
