### ISSUE TITLE
v8debug is not defined

### ISSUE THREAD

**Issue by dennisfrostlander** [Microsoft/vscode#13491]
- VSCode Version: 1.6.0
- OS Version: Windows 10
- NodeJS: 4.6.0, 6.7.0, does not matter

After recent upgrade of VSCode (not sure which), language client does not utilize debug parameters sent to it because variable v8debug is not defined when debugging through vscode.

Steps to Reproduce:
1. Create a new extension according to official documentation https://code.visualstudio.com/Docs/extensions/example-language-server
2. Launch the extension in debug mode and set a breakpoint in language client, main.js
See the following code for reference:
https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/main.ts#L1027
The variable v8debug is not defined, therefore the next line json = runDebug.debug; is never executed.

**Comment by weinand** [comment]
VS Code 1.6 uses a newer version of Electron which uses a newer node version. That could explain why v8debug is no longer defined.

**Comment by dennisfrostlander** [comment]
Ok, does it mean that vscode-languageserver-node should keep up and update their sources to whatever is needed for newer version of node?
Let me know if you want me to move this issue to the language server project.

**Comment by weinand** [comment]
@dennisfrostlander yes, if vscode-languageserver-node uses node version specific APIs, then it has to keep up with node versions. I've assigned @dbaeumer to provide more details.

**Comment by dennisfrostlander** [comment]
@weinand ok, let's then close this issue and track this in the language server repository.
