### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by ted1030** [microsoft/vscode#134907]
1.https://github.com/microsoft/vscode/blob/f1449c4cdc34a149941ceb8bcb3e69cc634cc8cd/src/vs/workbench/contrib/terminal/browser/terminalMenus.ts#L745

![image](https://user-images.githubusercontent.com/37107237/136968891-1ea814c4-4808-45e0-9abd-deea1ff056f9.png)

Because 'Split...' doesn't be localized, the string is still not be translated.

2.https://github.com/microsoft/vscode/blob/a2b4f09c6ab5bcf74e34543af8779e8410b598e2/src/vs/workbench/contrib/terminal/common/terminalStrings.ts#L33
https://github.com/microsoft/vscode/blob/a2b4f09c6ab5bcf74e34543af8779e8410b598e2/src/vs/workbench/contrib/terminal/common/terminalStrings.ts#L61
https://github.com/microsoft/vscode/blob/a3843b395ff8f4458fbb8477dcfe62d3e59bd496/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L1870
https://github.com/microsoft/vscode/blob/a3843b395ff8f4458fbb8477dcfe62d3e59bd496/src/vs/workbench/contrib/terminal/browser/terminalMenus.ts#L509
https://github.com/microsoft/vscode-loc/blob/87ef4f3cfb28df68e99858859288775d0f0efa70/i18n/vscode-language-pack-zh-hant/translations/main.i18n.json#L8184
The string "moveToEditorShort" and "workbench.action.terminal.sizeToContentWidthInstance"was translated in main.i18n.json, but it may be doesn't apply.
![image](https://user-images.githubusercontent.com/37107237/136996001-2af3bc21-b3f0-4aac-a393-2569f9ef700c.png)

3.https://github.com/microsoft/vscode/blob/a3843b395ff8f4458fbb8477dcfe62d3e59bd496/src/vs/workbench/contrib/notebook/browser/view/renderers/cellEditorOptions.ts#L201
Same as 1., there should be a localize().

**Comment by Tyriar** [comment]
@meganrogge if they're already in `localize` calls they probably just haven't got translated yet, nothing to do if that's the case.
