### ISSUE TITLE
VS Code does not detect Git even with correct path

### ISSUE THREAD

**Issue by samdeesh** [microsoft/vscode#134967]
Issue Type: <b>Bug</b>

VS code Source control does not recognize Git intermittently. The frequency and behavior are not predictable. when I do 'which git' i get '/usr/local/bin/git' on terminal and same is set in '"git.path": "/usr/local/bin/",' settings.json

At times it works like a breeze and at times it does not work even after a couple of restarts.  

VS Code version: Code 1.61.0 (Universal) (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:11:58.853Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 7cba955f-04f7-41fb-a603-4547ad688de1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|12.2.1
vscode-eslint|dba|2.2.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|9.0.0
angular-essentials|joh|12.0.0
Angular2|joh|12.0.0
read-time|joh|1.0.0
vscode-peacock|joh|3.10.1
vscode-docker|ms-|1.17.0
remote-containers|ms-|0.202.3
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-edge|msj|1.0.15
material-icon-theme|PKi|4.10.0
markdown-preview-enhanced|shd|0.6.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30378365
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis400:30374798
vsaa593:30376534
vssld246:30379911

```

</details>

**Comment by Wynston** [comment]
I've been struggling with the same thing (macOS v12.2.1). 

The only way to get it to load consistently is to disable all extensions (which obviously isn't a viable solution). I don't know what we're doing wrong because I feel like this would be fixed immediately if it was a common problem

**Comment by lszomoru** [comment]
@Wynston, we have recently detected an issue with extension activation that can result in the `vscode.git` extension not being activated, which explains why in your case everything is working as expected when all extensions are disabled. That problem has been fixed today, and tomorrow's (2022-03-11) Insiders release will contain the fix. Could you please update to the latest Insiders release on Friday, 2022-03-11 and let me know if you are still able to reproduce the problem. Thanks!

**Comment by samdeesh** [comment]
I got my laptop replaced due to some other issues, it is working fine on the new one

**Comment by lszomoru** [comment]
@samdeesh, thank for the update. Glad to hear that everything is working now.
