### ISSUE TITLE
"editor.snippetSuggestions": "top" Stopped working as intended

### ISSUE THREAD

**Issue by Cardinal90** [Microsoft/vscode#13498]
- VSCode Version: 1.6.0
- OS Version: Windows 10

Steps to Reproduce:

I have the following js snippet:

```
"Console.log": {
		"prefix": "cl",
		"body": ["console.log(${1:obj});$0"],
		"description": "Console log"
	},
```
There is a problem after last update. While the snippet shows on top in autocomplete, the term immediately after it (`class` in this case) is always selected by default. I have to use up arrow to select the snippet. Generally it just selects the most relevant autocomplete term not paying attention to snippets.

**Comment by isidorn** [comment]
@jrieken I feel like multiple users complained about this snippet top issue. Sounds like a regression

**Comment by jrieken** [comment]
@Cardinal90 It depends on what's already on the line. Can add info about that?

**Comment by Cardinal90** [comment]
@jrieken It doesn't seem to depend on anything. Happens both on empty line and not. Just tried in an empty file - same problem.

**Comment by soncodi** [comment]
The suggestion ordering is correct, but the popup scrolls past the 'top' suggestions, as it opens.

**Comment by jrieken** [comment]
This is a regression from https://github.com/Microsoft/vscode/commit/8150e1c4bed0117b8549d88838b5ac878f3f0a54. Since we have fixed the bug on master/insiders differently now it would be save to revert that change

**Comment by eggboxio** [comment]
Oh my, this regression makes 1.6 irritating to use! What's the roadmap for fixing this?

**Comment by jrieken** [comment]
reverted the bad change referenced above and pushed for the September Recovery release.

**Comment by ramya-rao-a** [comment]
@jrieken #11423 should be re-opened then?

**Comment by jrieken** [comment]
@ramya-rao-a In theory yes, but I have made already a different change for that. It now double fixed ;-)
