### ISSUE TITLE
No longer able to debug typescript after VSCode update

### ISSUE THREAD

**Issue by chris-jones-pixitmedia** [Microsoft/vscode#13499]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: christian-kohler.npm-intellisense-0.1.3, christian-kohler.path-intellisense-1.0.2, EditorConfig.EditorConfig-0.3.3, eg2.tslint-0.5.39, msjsdiag.debugger-for-chrome-1.1.0

Steps to Reproduce:

1. Try to launch program using launch.json configuration
2. Get error: Cannot launch program 'XXXX\index.ts'; setting the 'outFiles' attribute might help
3. Setting the outFiles attribute has no effect

Config:

        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/src/index.ts",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "console": "internalConsole",
            "sourceMaps": true,
            "outFiles": [ "${workspaceRoot}/dist/**/*.js" ]
        },

**Comment by isidorn** [comment]
Sounds like a potential regression - adding important to raise awarness. @weinand feel free to remove the tag if I am mistaken.

**Comment by mclaudio76** [comment]
I experienced a very similar issue.

**Comment by weinand** [comment]
I tried to reproduce this problem on Windows 10 with a similar setup, but I could not get this to fail.

Could you please add a trace attribute for source maps ('sm') to your launch config:
```json
  "trace": "sm"
```
and relaunch debugging.
Do you see any problems being logged to the debug console?

**Comment by chris-jones-pixitmedia** [comment]
I can't get to that point, the error pops up before anything is traced

**Comment by chris-jones-pixitmedia** [comment]
"sm" or "all" - makes no difference

**Comment by weinand** [comment]
@chris-jones-pixitmedia I've just tried to simulate your problem and before getting the error pop up I get this trace output:
```
3480: _findSourceMapUrl: source map url found at end of generated file 'c:/Users/weinand/Projects/TestData/TS/out/bug_1746.js'
3480: _findSourceMapUrl: source map url found at end of generated file 'c:/Users/weinand/Projects/TestData/TS/out/bug_1047.js'
3480: _findSourceMapUrl: source map url found at end of generated file 'c:/Users/weinand/Projects/TestData/TS/out/bug_xyz.js'
3480: _registerSourceMap: c:/users/weinand/projects/testdata/ts/src/bug_1047.ts -> c:/users/weinand/projects/testdata/ts/out/bug_1047.js
3480: _registerSourceMap: c:/users/weinand/projects/testdata/ts/src/bug_xyz.ts -> c:/users/weinand/projects/testdata/ts/out/bug_xyz.js
3480: _registerSourceMap: c:/users/weinand/projects/testdata/ts/src/bug_1746.ts -> c:/users/weinand/projects/testdata/ts/out/bug_1746.js
```

This output is the result from scanning the `"outFiles"` glob pattern.

Since you are not seeing this output it means that VS Code is not finding anything under your  `"${workspaceRoot}/dist/**/*.js"`. Could you please make sure that:
- there are in fact generated JavaScripts files,
- that those files have a `//# sourceMappingURL=` and a path at the end, 
- and that path points to a valid source map,
- and the paths in that source map point to the source.

**Comment by chris-jones-pixitmedia** [comment]
Hi @weinand,

I managed to get "trace": "all" working.

JS files have been compiled and are in the out directory, all have //# sourceMappingUrl = and a path, all of which point to valid source maps.

Trace outputs a ton of _findSourceMapUrl messages, followed by corresponding _registerSourceMap messages. Final message is:

disconnectRequest: send response

**Comment by weinand** [comment]
And in the trace output a "_registerSourceMap" exists for your "${workspaceRoot}/src/index.ts" file?

**Comment by chris-jones-pixitmedia** [comment]
Yes

**Comment by weinand** [comment]
Please copy the full path of your "index.ts" from the trace output in the debug console into the launch config as the value for the "program" attribute and then start debugging.
My theory is that the drive letter in "${workspaceRoot}/src/index.ts" uses a different case than what node.js sees.

**Comment by weinand** [comment]
BTW, what version of node are you using?

**Comment by chris-jones-pixitmedia** [comment]
Got it working! Looks like this was to do with gulp-sourcemaps rather than vscode - not sure why it was working before the upgrade and not after though.

sourceRoot in each map was set to 'source'. Explicitly set the sourceRoot option in gulp-sourcemaps to "../src" and it started working again.

Thanks for you help.

**Comment by weinand** [comment]
@chris-jones-pixitmedia great to hear that you got this working again.
Yes, gulp-sourcemaps is a mixed blessing. Just Yesterday their 1.8 version was breaking everyone:  https://github.com/floridoo/gulp-sourcemaps/issues/238

**Comment by akshaysinghal** [comment]
In my case, explicitly mentioning the `index.js` / `server.js`  file against `outFiles`  property did the trick..

My `outFiles` property:
```
"outFiles": [
	"${workspaceRoot}/build/local/server.js",
	"${workspaceRoot}/build/local/app/**/*.js"
]
```

**Comment by weinand** [comment]
@akshaysinghal hmm, having to break your single pattern into two sounds strange. I'll investigate...

**Comment by Ciwan1859** [comment]
@weinand any update on this? I have this set up

`"outFiles": ["${workspaceRoot}/js"]`

but when I run it via `Ctrl + F5`, it says:

> Cannot launch program 'd:\Work\datachimp\app.ts'; setting the 'outFiles' attribute might help.

My `.ts` files are compiling fine and are being outputted to the **js** directory.

**Comment by weinand** [comment]
The values of the attribute `outFiles` must be glob patterns.
So if your generated *.js files live anywhere in the 'js' directory, the pattern would be:
`"${workspaceRoot}/**/*.js"`

**Comment by Ciwan1859** [comment]
Nice @weinand, that did it! :+1:

**Comment by pavankumar58** [comment]
Hi I am getting the same problem and I mentioned my outfiles path as
 "outFiles": [
                "${workspaceRoot}/**/*.js"
            ]
but it still is showing error of setting outfiles  attribute might help?

**Comment by weinand** [comment]
@pavankumar58 this issue was closed. Please file a new issue with detailed steps for how to reproduce.
