### ISSUE TITLE
stange quick info for python functions

### ISSUE THREAD

**Issue by largezhou** [Microsoft/vscode#13494]
![default](https://cloud.githubusercontent.com/assets/13796692/19269161/820294ec-8feb-11e6-87d0-d1ba8395dc2f.jpg)
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: donjayamanne.python-0.4.0, robertohuertasm.vscode-icons-3.0.1, spywhere.guides-0.5.1

Steps to Reproduce:

1.type a function name, and then you type a '('. 
2.you can see the stange quickinfo...

**Comment by isidorn** [comment]
This is coming from a pyhton extension - can you please file this issue against donjayamanne.python extension.
fyi @DonJayamanne

**Comment by DonJayamanne** [comment]
@isidorn , isn't this an upstream issue (issue with VS Code), not displaying the tooltip correctly?
All the extension is doing is displaying a tooltip. It feels like the new scrolling behaviour added into the tooltips isn't working here.

**Comment by largezhou** [comment]
add some settings only disable docstring display, and keep the  function and class parameters display??

**Comment by DonJayamanne** [comment]
@largezhou, the tooltip content is provided by the python extension. If you would like changes to the content displayed, them please discuss that in the python git repo.

**Comment by DonJayamanne** [comment]
@isidorn , found the issue, the contents of the label was too large. VS Code expects it to be one liner text.
