### ISSUE TITLE
iPadOS editor invisiable when "floating keyboard" lose focus in PWA mode

### ISSUE THREAD

**Issue by oxkenshin** [microsoft/vscode#134955]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: v1.60.0
- Code-server Version: v3.12.0
- OS Version: iPadOS 15.1

Steps to Reproduce:

1. Open VsCode in PWA mode (safari)
2. Tap editable area to pop up the keyboard
3. Shrink the virtual keyboard to floating keyboard mode
4. Tap anywhere that is uneditable, e.g. "tap on explorer, or long press on editor to show pop up menu"
 
![floating keyboard](https://i.imgur.com/FRKi9md.jpeg)
![bug](https://i.imgur.com/lds6Ft2.jpeg)

**Comment by alexdima** [comment]
@bpasero I am not super familiar with this iPad mode. I find it very weird that the entire workbench becomes black and only the status bar remains visible.

**Comment by bpasero** [comment]
I don't know either, Rebornix and Isidor own iPadOS.

**Comment by egbertwong** [comment]
I have the same issue on the latest vscode.dev. When using vscode.dev under PWA mode on iPad, the interface always shows like this. It's hard to work with it. I'm using iPad Pro 2021 with iPad OS 15.4.1

**Comment by TylerLeonhardt** [comment]
This seems to be working now.
