### ISSUE TITLE
High load in extension host wrecks main process

### ISSUE THREAD

**Issue by ovidijusr** [Microsoft/vscode#13492]
- VSCode Version: 1.6.0
- OS Version: windows 10

When I open this file most of the time I cannot save the file (tried ctrl+s save all) 
And after a few minutes whole visual code freezes.

I attached file which freezes visual code
[styles.zip](https://github.com/Microsoft/vscode/files/521695/styles.zip)

Thank you for support

**Comment by isidorn** [comment]
@ovidijusr Works for just fine both on win10 and os x.
Do you see this issue also with the previous vscode release?

**Comment by aeschli** [comment]
I also can not reproduce on Linux Ubuntu.

@ovidijusr Do you have any extensions installed? If yes, can you start VSCode with `--disable-extensions` and see if the crash still happens?

**Comment by fifafu** [comment]
For me saving also stops working randomly with 1.6 however I didn't have freezes yet. I assume it's caused by one of the installed extensions. Will try to figure out which one.

**Comment by fifafu** [comment]
For me downloading a fresh copy of VSCode seems to have fixed the issue. Maybe one of the extensions was causing the update to break?

**Comment by ovidijusr** [comment]
![image](https://cloud.githubusercontent.com/assets/6230536/19281038/e83e7064-8ff0-11e6-989c-f9b9d66854aa.png)
Ok adding more info

it crashes when I try to type something  and get recommendation. It not happens instantly but in about 5th  and reopen window doesn't help. It just stays frozen

**Comment by aeschli** [comment]
@ovidijusr Do you have any extensions installed? If yes, can you start VSCode with --disable-extensions and see if the crash still happens?

**Comment by ovidijusr** [comment]
I turned off all the extensions. It still prevents me to save files and still freezes

**Comment by aeschli** [comment]
I'm not able to reproduce on Windows 10 but see slowness when making edits. The performace measurements show that most time is spent updating folding ranges.

@ovidijusr Can you turn off the folding markers and see if that's the problem?
Add `"editor.folding": false` in the user settings.

**Comment by eppsilon** [comment]
I am seeing this issue on OS X with VS Code 1.6.1. I can save normally for about 10-15 minutes, and then saving (via Cmd-S or the UI) stops working. The UI continues to show the file as modified. My extensions:

```
AdamCaviness.theme-monokai-dark-soda-0.0.5
DSKWRK.vscode-generate-getter-setter-0.4.0
EditorConfig.EditorConfig-0.3.3
PeterJausovec.vscode-docker-0.0.6
akamud.vscode-caniuse-0.5.3
andrejunges.Handlebars-0.1.2
benjaminromano.typings-installer-0.2.0
casualjim.gotemplate-0.1.1
cazzar09.Gradle-1.0.1
danwahlin.angular2-snippets-0.10.15
dcortes92.FreeMarker-0.0.3
donjayamanne.githistory-0.1.0
donjayamanne.python-0.4.2
eg2.tslint-0.5.39
eg2.vscode-npm-script-0.0.21
fknop.vscode-npm-3.3.0
georgewfraser.vscode-javac-0.0.23
gerane.Theme-FlatlandMonokai-0.0.4
glen-84.sass-lint-0.0.2
johnpapa.Angular2-1.0.2
krizzdewizz.refactorix-0.3.0
lukehoban.Go-0.6.44
ms-vscode.csharp-1.4.1
ms-vscode.mono-debug-0.11.0
msjsdiag.debugger-for-chrome-1.2.1
robertohuertasm.vscode-icons-3.0.5
seanmcbreen.Spell-0.8.6
searKing.preview-vscode-1.1.1
shanoor.vscode-nginx-0.3.0
shinnn.stylelint-0.17.3
steoates.autoimport-1.0.3
steoates.autoimport-1.2.1
waderyan.gitblame-1.3.0
wholroyd.HCL-0.0.5
```

**Comment by eppsilon** [comment]
I disabled all of my extensions (by running VS Code with the flag mentioned above) and the problem went away. I've uninstalled all of them and I'm going to gradually put them back as I need them. I'll report back if one of them re-introduces the issue.

**Comment by eppsilon** [comment]
I believe the Auto-Import extension is causing the problem. Not sure yet if it is doing something to trigger this issue that other extensions might do also.

**Comment by soates** [comment]
Auto-Import author here.. Ill take a look at this :) sorry for any inconvenience!

**Comment by bpasero** [comment]
@jrieken fyi, not sure if this is still an issue but people are reporting they cannot save when Auto Import is installed as extension (see https://github.com/soates/Auto-Import/issues/24). No matter how bad the extension is behaving, I think we should eventually just save, and I thought we had a timeout like that in place but maybe there is an exception thrown somewhere that bubbles up badly?

**Comment by jrieken** [comment]
I don't think it has anything to do with the save logic but more with the sheer load auto import puts on the extension host. Indeed, I couldn't find any onWill/Did-save code, but it causes high load. For instance with calls like [that](https://github.com/soates/Auto-Import/blob/master/src/import-scanner.ts#L37)

I think it's a good show-case of an extension being able to wreck VS Code

**Comment by soates** [comment]
@jrieken @bpasero Is there anything I could change in my code to alleviate this? .. or should I really  be using a language server for the scanning?

**Comment by jrieken** [comment]
@soates I will reverse a little time and drill into this. Surely one bug on our side is that searching for many, many files will squeeze a large array across many processes - that is something where we can improve. Generally, you shouldn't do heavy lifting in the extension host because that it unfair towards other extensions. However, it is not yet clever why that affects the main thread. Needs more investigation

**Comment by jrieken** [comment]
@soates I am trying to wreck VS Code to validate/invalidate some ideas. I have installed your extension (v1.2.2) and configured it like so `autoimport.filesToScan": "**/*.{ts,tax}`. Still, the only noticeable thing is a status bar item reading `{..} : 5012`. No crash, No hang, No CPU load, also no progress or none of the promised feature. What am I missing?

**Comment by soates** [comment]
@jrieken I am having troubles reproducing it my self - how do you mean none of the promised features?

**Comment by jrieken** [comment]
this faded out. we have done many changes in the meantime and no actionable information from this issue.
