### ISSUE TITLE
“Edit in `settings.json`” fails to create key

### ISSUE THREAD

**Issue by mavenor** [microsoft/vscode#134908]
Issue Type: <b>Bug</b>

### Description/TL;DR
The September 2021 (stable) release **does not insert** an **earstwhile nonexistent** JSON key after opening `settings.json`, when the *"Edit in settings.json"* link against any *unmodified* setting is clicked.
This seems to be for **both *"User"* and *"Workspace"* scopes.**

### Expected Results
On clicking *Edit in settings.json*, the corresponding key (ID) is focused in the `settings.json` file, whether or not it was earstwhile present.

### Actual Results
While `settings.json` always successfully opens each time, the corresponding key ID is only brought under cursor focus when it was already present in the file (i.e., previously set).

### Steps to Reproduce
1. Open Settings
2. Find a setting that *must* be edited in the JSON file (e.g., `editor.codeActionsOnSave`) ***and*** *has not been `@modified`.*
3. Click on *“Edit in settings.json”*
4. The editor should open said file either to your last edit location, or to the first line.

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

https://user-images.githubusercontent.com/69630953/136983345-935bfa46-bdcf-4ce6-9b38-bf02178af783.mp4

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.95GB free)|
|Process Argv|--crash-reporter-id 242528f1-feb2-4d92-8ed2-3ba6ac8503ac|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Gruntfuggly** [comment]
This is a bit of a show stopper when an extension only provides a single setting which needs to be set in the settings.json. You have to go back to the GUI view, copy the path of the setting and then go back to the json view and search for the setting.

**Comment by sandy081** [comment]
This seems to work for me now. Please try the latest VS Code and revalidate. If you still see the issue provide us with the steps to repro.
