### ISSUE TITLE
代码提示功能还不行

### ISSUE THREAD

**Issue by male110** [Microsoft/vscode#135]
我用PHP，感觉代码提示功能还不行。变量提示不出来。
跟PHPStorm比差远了。
这东东感觉现在还是个实验品。不可取。

**Comment by OshotOkill** [comment]
@male110 这个编辑器主打的是前端，自己去官网看一下language的overview，带intellisense功能的包括HTML/CSS/JS/JSON/TS/C#，也包括Sass和Less，PHP目前还不支持

另外在issue里不要说中文，say English please

**Comment by infinnie** [comment]
@OshotOkill “Speak” English…

**Comment by OshotOkill** [comment]
@infinnie Sorry, already fixed it.

**Comment by bpasero** [comment]
@male110 can you please edit your post into english?

**Comment by karl20888** [comment]
@male110 我觉得php的代码提示功能已经很强大了啊

**Comment by zhengbli** [comment]
Translation: 
the intellisense for php is not comparable to what phpStorm has to offer. There is no support for variables.

To be honest, I don't think this issue is too general to provides any constructional value.

**Comment by diryboy** [comment]
OP was complaining about the lack of PHP supports like variable completion, in comparisons with PHPStorm. And he considered vscode an experimental product, not ready for serious use.

This sounds more like a discussion rather than an actionable issue report.

**Comment by kinosang** [comment]
English please. And if you have any suggests, please list them on your comment instead of complaining incessantly.

**Comment by infinnie** [comment]
@kinosang Nice to meet you.
