### ISSUE TITLE
A funny bug in the about window:

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#13505]
- VSCode Version: 1.6.0
- OS Version: macOS - El Capitan

I don't know if this is even worth sharing but I found a funny bug within the Code's about page... I believe it's a padding calculation problem:

![about](https://cloud.githubusercontent.com/assets/2157285/19271580/258d204c-8fd2-11e6-86f8-9344bf22f333.gif)

**Comment by isidorn** [comment]
This seems to have been fixed in latest

**Comment by pmkary** [comment]
No. My vscode insider just updated and it still is there...

**Comment by isidorn** [comment]
Does not repro for me and I do no think it is important enough to continue investigating.
Even if you see that issue it is probably not in vscode's control since we do not specaily style that dialog. It comes as part of electron

**Comment by pmkary** [comment]
Ah yeah I also did say in my text that it's not ever worth investigating. But well I thought it might be good to tell...
