### ISSUE TITLE
source control section moves commit message focus unexpectedly when several repos are listed

### ISSUE THREAD

**Issue by mkniswonger** [microsoft/vscode#135047]
Issue Type: <b>Bug</b>

I have a workspace with several folders in it. Each has its own repo. When i open the SCM view and try to make a commit message, it will frequently move my focus from the message field i was typing in to another (usually further up the list). this will happen in the middle of typing, so my commit message will be half in one message field and half in another. The one it ends up in is NOT the one i intended, and the commit i make is not for that repo. This issue is consistent when several folders are in the workspace.

I have also seen it show the same branch name for two repos, even tho they dont have the same branches. And it will persist that fiction into the pop-up list of branches for the other repo. But when I go to another tool, such as sourcetree, and look at the repo there, it has the correct branches. So VS Code is having a display problem NOT making weird branches (tho it looks that way). This issue seems intermittent, but may be related to allowing VScode to "sync" or "publish" with a new branch, and not using Push and "yes i want to send that new branch to the remote", which was the older functionality. When i use the older approach, it seems not to have the issue as much. The newer function appears to be related to the display problem.

This began after my most recent update tot he latest VS code version.

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:11:58.853Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (2.02GB free)|
|Process Argv|--crash-reporter-id b9ffdf3f-7569-4b8d-ae9e-753543c87c8c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
yaml2json|ahe|0.0.3
project-manager|ale|12.4.0
toml|be5|0.5.1
habitat|cnu|0.4.1
vscode-markdownlint|Dav|0.44.4
githistory|don|0.6.18
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
shell-format|fox|7.1.1
vscode-rufo|jnb|0.0.4
vscode-rufo|mbe|0.2.1
python|ms-|2021.10.1336267007
vscode-pylance|ms-|2021.10.0
jupyter|ms-|2021.9.1001312534
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
vscode-groovy-lint|Nic|1.4.0
vscode-yaml-sort|Pas|5.1.0
ruby|reb|0.28.1
vscode-yaml|red|0.23.0
code-spell-checker|str|2.0.10
vscode-ruby|win|0.28.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30378365
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis400:30381677
vsaa593cf:30376535
vssld246:30379911

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/134638#issuecomment-938471497 for a workaround.

Scheduled to be fixed in upcoming recovery release.
