### ISSUE TITLE
Path broken in output

### ISSUE THREAD

**Issue by devgaspa** [Microsoft/vscode#13504]
- VSCode Version: 1.6.0
- OS Version: Windows 7 Service Pack 1

Steps to Reproduce:
1. When attempting to run a script, the path breaks, causing error.

Even in quotes. http://imgur.com/a/Oz8eF

**Comment by isidorn** [comment]
If I understand your issue correctly it is a dup of https://github.com/Microsoft/vscode/issues/8717
Some ansi characters are not supported in output
