### ISSUE TITLE
Allow re-named commands to map to the new one in the command palette

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#135096]
Similar to how we deprecate settings and mention that in the UI, we should have for a way for re-named commands to map to the new ones in the command palette. Example below of when we renamed "Welcome" => "Get Started" and how this will help make it more discoverable for users:

<img width="652" alt="CleanShot 2021-10-14 at 09 40 47@2x" src="https://user-images.githubusercontent.com/35271042/137360691-e105a156-9e66-47c1-8945-c5c7cb676092.png">

We could additionally add a label to mention the new command name

**Comment by TylerLeonhardt** [comment]
I think this is either covered by https://github.com/microsoft/vscode/issues/50836 or covered by simply keeping the old command around (with the same behavior of the new command name) until it's time to delete the old name.
