### ISSUE TITLE
Option to exclude items from Git branch checkout list

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#13506]
- VSCode Version: Version 1.7.0-insider 
- OS Version: 10.12

When I click the "git branch" item at the left of the status bar, a popup appear with all the branches I might want to switch to, which is expected.

However, this menu lists all of our tags first, and we have dozens of tags on remote releases of our app.  It also lists the remote branches of the repo.

I always just want to switch between LOCAL branches I have already tracked.  This is the way the "git plus" extension for Atom works.  I find it hard to find the branch I am looking for in the list, even with type-ahead.  

I realize some people may want the current setup, so how about a prefs setting for "checkout shows local branches only" or something similar?  Or preference line items to exclude tags and/or remote branches?

**Comment by Krzysztof-Cieslak** [comment]
Hey, @joaomoreno what would be desirable solution for this? I can take a look at it in some free time

**Comment by joaomoreno** [comment]
@Krzysztof-Cieslak We could introduce a `git.checkout` setting with the values of `all` or `local`.

**Comment by joaomoreno** [comment]
Fixed by #16792
