### ISSUE TITLE
Autocompletion not working properly in python since last update

### ISSUE THREAD

**Issue by ParisNeo** [microsoft/vscode#135068]
Issue Type: <b>Bug</b>

Since the last update, my autocompletion (python) is not working properly. Either it is not showing any thing or it is partially working. For example with tensorflow, it can see that there is a submodule called keras, but can't see what's inside keras!!!

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by alexdima** [comment]
Please create an issue directly against the Python extension at https://github.com/Microsoft/vscode-python/issues
