### ISSUE TITLE
Rg taking up significant resources / freezing choppy file editing (frame drops) in monorepo

### ISSUE THREAD

**Issue by thesimpledev** [microsoft/vscode#135019]
- VS Code Version: 1.61.0
  - I was previously using a newer version. My coworker wasn't having this issue so I downgraded expecting this issue to clear up.
- OS Version: macOS Big Sur 11.6

Steps to Reproduce:

1. Open power platform ux repo (large mono repo w/ many packages)
2. Work as usual, not sure explicitly what action triggers this--but it's not a search. Use cmd+click quite a bit and editing a file tends to be very choppy/frame drops.
3. CPU usage spikes and vscode freezes up
4. Open terminal and enter `ps aux | grep rg` and there are many `rg` processes

Attempts to fix:
*Neither of these had any impact*
- Removed most extensions
- Added: `"search.followSymlinks": false` to settings (based on a similar issue found in another bug)
  - #98594

Ways I've "fixed" this:
- Turn off javascript/typescript server
  - #55649

I have to run `pkill rg` after this happens and then reduce the scope of the folders open otherwise I'm unable to work at all. For instance, I'll open this monorepo and this problem will occur. So, I'll open a specific folder which is much smaller and doesn't contain all the packages. The problem with this is that I no longer have click to definition of other packages/cmd+click for node modules/auto import no longer works.

Note: After starting to file this bug, I haven't seen this rg problem pop up (in the last hour). But, VSCode has completely frozen twice (for a few minutes each time). So, any tips on how to improve overall performance would be helpful. Can I scope down my VSCode project to only focus on 3/4 folders, without having to exclude 50+ packages manually?

Any thoughts/debugging help would be incredibly appreciated as my work productivity has drastically been reduced and I prefer not swapping back to Webstorm right now.

Feel free to shoot me a message on teams @ `androdri` if that would help.

Another note: When I look at processes in my activity monitor, `Code Helper Renderer` tends to spike pretty often. Even while I'm not editing/navigating. Not sure if this is related.

<img width="961" alt="Screen Shot 2021-10-13 at 8 58 36 AM" src="https://user-images.githubusercontent.com/37192643/137185557-4b626a01-b3e6-4d6a-8c40-d5da7ffb30f8.png">

**Comment by roblourens** [comment]
This probably comes from an extension searching for `ts,tsx` files to activate itself. Do you have any other TS-related extensions still installed? If you disable everything does it help?

**Comment by roblourens** [comment]
Let me know if you learned anything and I can take another look
