### ISSUE TITLE
Markdown preview table cell contents shift on mouseover only in github.dev

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#135037]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: github.dev
- OS Version: Windows 10

Steps to Reproduce:

1. Visit https://github.dev/microsoft/vscode-anycode
2. Mouse over the cell contents in the table
3. 🐛 cell contents shift around on mouse over. This does not happen on VS Code Desktop
![recording (37)](https://user-images.githubusercontent.com/30305945/137207338-a0f7d99c-79e1-4b45-8df3-bdb2d85ac376.gif)

**Comment by joyceerhl** [comment]
Edge 94.0.992.38 (Official build) (64-bit)

**Comment by IllusionMH** [comment]
Unable to reproduce with 
Version 94.0.992.47 (Official build) (64-bit)
Version 96.0.1032.0 (Official build) dev (64-bit)

maybe some extension?

**Comment by IllusionMH** [comment]
@joyceerhl Thanks for the tip about switching online version to Insiders, missed that menu item!

Yes, reproducible if I switch online version to Insiders.
Moreover it's reproducible in VS Code insiders, but more likely to happen if I hover over second column and rarely if I hover over text in first column.

![image](https://user-images.githubusercontent.com/1312662/137227231-0179cd82-7855-4acd-92af-62d6030928eb.png)

Version: 1.62.0-insider (user setup)
Commit: cca2d71a825cf1cdf893d245127fe430f2407249
Date: 2021-10-13T11:19:13.789Z
OS: Windows_NT x64 10.0.19041
