### ISSUE TITLE
Useless linking to libdbus-1.so.3?

### ISSUE THREAD

**Issue by artem-sidorenko** [Microsoft/vscode#13501]
- VSCode Version: 1.6.0
- OS Version: Ubuntu 15.10

I'm packaging [vscode via OBS](https://build.opensuse.org/package/show/home:artem_sidorenko:testing/vscode) for myself. 

Today I noticed following warning [in the logs](https://build.opensuse.org/package/live_build_log/home:artem_sidorenko:testing/vscode/Ubuntu_15.10/x86_64):
`[  309s] dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/vscode/opt/vscode/code was not linked against libdbus-1.so.3 (it uses none of the library's symbols)`

Steps to Reproduce:

```bash
$ ldd /opt/vscode/code  | grep dbus
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f9df1580000)
...
```

Is linking with libdbus required?

**Comment by Tyriar** [comment]
@artem-sidorenko this would be either an Electron or Chromium problem.
