### ISSUE TITLE
Unit tests should be faster 🐎 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#135075]
This the continuation of https://github.com/microsoft/vscode/issues/134972

📢 Another shout the the [`runWithFakedTimers`-util](https://github.com/microsoft/vscode/blob/b88626977819c490fa22e5b88eaec0f251aa97d6/src/vs/base/test/common/timeTravelScheduler.ts#L226)

---

- [x] 252ms, Provider should not be retriggered if previous help is canceled first @mjbvz 
- [x] 253ms, asyncRenderCallback should not be invoked if result is immediately disposed @mjbvz 
- [x] 254ms, corrupt DB recovers @bpasero 
- [x] 255ms, Orcale -> position changed @mjbvz 
- [x] 257ms, Orcale -> marker added @mjbvz 
- [x] 257ms, Lightbulb is in the wrong place, #29933 @mjbvz 
- [x] 263ms, Retrigger while a pending resolve is still going on should preserve last active signature #96702 @mjbvz  
- [x] 303ms, Provider should be retriggered if already active @mjbvz 
- [x] 311ms, Orcale -> should only auto trigger once for cursor and marker update right after each other @mjbvz 
- [x] 323ms, test donotMakeRequestsUntil is reset after retry time is finished @sandy081 
- [x] 325ms, clear @bpasero 
- [x] 329ms, test donotMakeRequestsUntil is checked and reset after retreived @sandy081 
- [x] 380ms, createFile (mixed parallel/sequential) @JacksonKearl 
- [x] 411ms, resolve terminal encoding (detect) @bpasero 
- [x] 503ms, asyncRenderCallback should not be invoked if dispose is called before code block is rendered @mjbvz 
- [x] 545ms, buffered sending - simple data @bpasero

**Comment by mjbvz** [comment]
I reviewed mine and adopted `runWithFakeTimers` for most. A handful are still slow, specifically the ones where I'm trying to test that something has not happened. Keeping them for now
