### ISSUE TITLE
IntelliSense design goes wrong with custom fonts.

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#13503]
- VSCode Version: 1.6
- OS Version: macOS / El Capitan

In 1.6 custom font-family & font-size also effects the intelliSense view. First of all thanks for that. However it has some problems. Padding is wrong and also the text is not in the aligns it has to be

<img width="525" alt="screen shot 2016-10-11 at 4 25 09 pm" src="https://cloud.githubusercontent.com/assets/2157285/19271083/e6a4b84c-8fcf-11e6-89e0-70e20a3c3ee2.png">

when you set light heights it goes even more wrong:

<img width="565" alt="screen shot 2016-10-11 at 4 25 37 pm" src="https://cloud.githubusercontent.com/assets/2157285/19271157/319059f6-8fd0-11e6-85c4-e9117b328de5.png">
 
If the be a good way of padding. A flex box vertical align or even the `vertical-align` of the CSS be used to center the text for good it would be so cool of you.

P.S: I tried to fix this one but there was a node version conflict on my system. If you could give me advice on how to keep my node version to the latest while having a version for vscode development I can try to fix it myself.

As always thanks for VS Code

**Comment by joaomoreno** [comment]
What are your full settings?

**Comment by pmkary** [comment]
I believe the relevant settings would be:
```
	"editor.fontSize": 				13,
	"editor.lineHeight": 26,
	"editor.fontFamily":            "Hasklig-Medium",
	"editor.tabSize": 				4,
	"editor.wrappingColumn": 		90,
	"editor.wrappingIndent":        "same",
```

**Comment by joaomoreno** [comment]
Can you try in the latest insiders release?

This is what I get:

![image](https://cloud.githubusercontent.com/assets/22350/19603621/2bf02fa0-97b2-11e6-925a-9e9a7c52bf84.png)

**Comment by pmkary** [comment]
With pleasure! let me install it...

**Comment by pmkary** [comment]
<img width="599" alt="screen shot 2016-10-21 at 7 24 00 pm" src="https://cloud.githubusercontent.com/assets/2157285/19604879/109cb644-97c4-11e6-8d46-fa98e6c727dc.png">

@joaomoreno It works more than perfect, Thanks a lot as always! 👍
