### ISSUE TITLE
support install multi vsixs via cli in one command

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#135000]
In a offline env of Windows.
I need to install a lots of offline-visxs.
could we install vsixs via one command:
` code --install-extension .\snippets-plus-1.2.0.vsix .\vscode-gerrit-helper-0.0.9.vsix`
thanks
```
 code --install-extension .\snippets-plus-1.2.0.vsix .\vscode-gerrit-helper-0.0.9.vsix
Installing extensions...
(node:22012) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
Extension 'snippets-plus-1.2.0.vsix' was successfully installed.
```

**Comment by sandy081** [comment]
You have to repeat `--install-extension` for each vsix. say: `code --install-extension .\snippets-plus-1.2.0.vsix  --install-extension .\vscode-gerrit-helper-0.0.9.vsix`
