### ISSUE TITLE
display the Chinese garbled code in the search results

### ISSUE THREAD

**Issue by chenghaitao** [microsoft/vscode#135077]
Issue Type: <b>Bug</b>

打开工程，在包含中文的文件搜索对应关键词，在搜索结果中中文显示乱码

Open the project, search the corresponding keywords in the files containing Chinese, and display the Chinese garbled code in the search results

VS Code version: Code 1.61.0 (Universal) (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:11:58.853Z)
OS version: Darwin x64 20.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 6, 4|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv|--crash-reporter-id b0aa21dd-b9ec-4503-b97b-ea333d1da64d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.49.0
ccs-flutter-color|cir|1.0.1
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.27.2
flutter|Dar|3.27.0
githistory|don|0.6.18
xml|Dot|2.5.1
gitlens|eam|11.6.1
json-tools|eri|1.0.2
code-runner|for|0.11.6
html-preview-vscode|geo|0.2.5
go|gol|0.28.1
githd|hui|2.2.4
vscode-github|Kni|0.30.6
git-graph|mhu|1.30.0
vscode-language-pack-zh-hans|MS-|1.61.5
python|ms-|2021.10.1336267007
vscode-pylance|ms-|2021.10.0
jupyter|ms-|2021.9.1001312534
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
cpptools|ms-|1.7.0
sqltools|mtx|0.23.0
awesome-flutter-snippets|Nas|3.0.2
git-file-history|pom|1.0.1
java|red|0.82.0
vscode-yaml|red|0.23.0
partial-diff|ryu|1.4.3
tabnine-vscode|Tab|3.4.30
local-lua-debugger-vscode|tom|0.2.3
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.5
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30378365
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis300:30381676
vsaa593cf:30376535
vssld246cf:30379912

```

</details>

**Comment by chenghaitao** [comment]
> What was the encoding of the file? And what's the value of `files.encoding`?

Both file's encoding and the value of `file.encoding` is GB2312.

I guess the reason for the problem is that the search results use utf-8 encoding by default, but the file encoding is GB2312, even if I have checked  automatic detection file encoding ( "files.autoGuessEncoding": true ) in settings.json 

Please help confirm this problem and fix it. Thank you~

**Comment by roblourens** [comment]
I suspect your setting for `files.encoding` is not gb2312, because if it is for me then I don't get that DESCRIPTION result in the utf8 file (because the file is being parsed as gb2312). So I just see the expected behavior here.
