### ISSUE TITLE
Align notebook layout commands

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#135014]
ipynb-notebooks have toggle breadcrumbs, outline and variables but GHI-notebooks only have toggle breadcrumbs. I understand that toggle variables makes no sense for them (lack of support) but there is outline and the same rules should apply for these different notebook types

**Comment by greazer** [comment]
Seems like this one can be handled by core VS Code notebook support (at least toggling outline). So leaving in this repo.

**Comment by rebornix** [comment]
Let's track it in #137185
