### ISSUE TITLE
Source control panel behaves oddly when there are submodules

### ISSUE THREAD

**Issue by cvalerio** [microsoft/vscode#135080]
Issue Type: <b>Bug</b>

I'm using VS Code on a project with 3 GIT submodules, with remote to WSL (Ubuntu).
When I set the cursor on one of the commit message text inputs (e.g. main repository), after a couple of seconds the focus is moved to another of the 4 text inputs (e.g. 3rd submodule).
This is particularily annoying when typing commit messages, that I'm forced to type in terminal, now.

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (11.66GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu/home/claudio/repos/goldengoose-sneaker-maker --crash-reporter-id d60c7e35-33c8-4994-a4cc-df1f2fe2a3c5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|15.43GB (4.19GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-csharp-snippets|jor|1.1.0
remote-containers|ms-|0.202.4
remote-wsl|ms-|0.58.2
vscode-eslint|dba|2.2.1
quicktype-refresh|dog|0.1.1
gitlens|eam|11.6.1
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|9.0.0
auto-using|Fud|0.7.15
rest-client|hum|0.24.5
csharpextensions|jch|1.3.1
vscode-docker|ms-|1.17.0
csharp|ms-|1.23.16
vscode-typescript-tslint-plugin|ms-|1.3.3
vetur|oct|0.34.1
advanced-new-file|pat|1.2.2
preview-vscode|sea|2.2.5
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30378365
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis200:30381674
vsaa593cf:30376535
vssld246:30379911

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/134638#issuecomment-938471497 for a workaround.

Scheduled to be fixed in upcoming recovery release.
