### ISSUE TITLE
Scrolling with touchpad on Dell XPS 13 9343 Lagging

### ISSUE THREAD

**Issue by Nevey** [Microsoft/vscode#13509]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: be5invis.vscode-icontheme-nomo-dark-1.1.4

Since the update, the scrolling (only with touchpad) is lagging on my laptop. Quite annoying if I'm working without a mouse. Scrolling with a mouse seems fine!

Steps to Reproduce:

1. Open a file
2. Scroll with touchpad

**Comment by EgejVencelj** [comment]
I second this: On my Lenovo 500s-14YSK with windows 10.

The touchpad scroll (two finger) scrolls very fast and it actually moves the carret up and down the lines (I think a few at the time).

If it has to change the context (ie. actually scroll) it becomes really slow and unresponsive, taking several seconds to load that segment (even in a file that only has like 200 lines).

If I grab the slider and move it, it works normally.

**Comment by jhasse** [comment]
Duplicate of #13612?

**Comment by Nevey** [comment]
Agreed
