### ISSUE TITLE
Console has empty lines/lines out of alignment

### ISSUE THREAD

**Issue by corey-waymark** [Microsoft/vscode#13500]
- VSCode Version: 1.6.0
- OS Version: Windows 10 version 1607

Steps to Reproduce:
1. Use console

As you may have gathered, I haven't got a set series of steps to reproduce this - I had a gulp watch running in the console, which is when the extra characters/lines appeared.

![vsc-console-issue](https://cloud.githubusercontent.com/assets/17826711/19269964/6191ff3a-8fb5-11e6-8931-6c7b8bda0d46.png)

I have the html for the the indented line, and the one above it, and as you can see there appears to be lines output when there is no console output, with some non-breaking spaces appearing before the contents of a line. I've never seen this in cmd, or in previous versions of the in-built terminal, and the task itself hasn't changed since the last update to vsc.

**Comment by Tyriar** [comment]
This should be fixed, however there's a similar problem that affects the latest version of windows (Creator Update) https://github.com/Microsoft/vscode/issues/19665.
