### ISSUE TITLE
add setting for enabling breakpoints per language

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#13507]
With support for languages that are transpiled to JavaScript, an end user needs a quick and simple way to enable breakpoints for new languages (without having to wait for a new extension to appear).

Since a new 'language' cannot be easily introduced as a user or workspace setting, I suggest to implement a pragmatic solution proposed by @isidorn: a setting `debugger.allowBreakpointsEverywhere` for enabling breakpoints for all (text) files.

**Comment by isidorn** [comment]
So we would go with `debugger.` not `debug.`?

**Comment by weinand** [comment]
Yes, to keep it aligned with `editor` (which is not using `edit`). But I don't have strong opinions.
Let's get @egamma's opinion on this...

**Comment by isidorn** [comment]
I vote for `debug.` because we do not use `debugger.` anywhere else in the UI, while debug is used everywhere. Also it is shorter

![screen shot 2016-10-12 at 10 20 47](https://cloud.githubusercontent.com/assets/1926584/19302711/a1b55232-9065-11e6-8e0a-563f283582f4.png)

**Comment by egamma** [comment]
No strong opinion as long as we are consistent. 

Keeping `Debug` is fine by me, I could argue that this would be what we show as the menu name in the menu bar.

**Comment by weinand** [comment]
ok, let's go with 'debug' then.
