### ISSUE TITLE
Quick Fix: Keyboard shortcut CTRL+.  shows a small 'e'

### ISSUE THREAD

**Issue by fsoft72** [microsoft/vscode#135084]
Issue Type: <b>Bug</b>

In the latest version of VSCode, when I click CTRL+. to open the quick fix menu, a small "e" char is shown and nothing happens.
If I click on the link "Quick Fix (CTRL+.)" the menu is correctly shown.

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:11:02.929Z)
OS version: Linux x64 5.13.0-19-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|31.26GB (10.92GB free)|
|Process Argv|--crash-reporter-id a0dc1666-12e7-4565-9d4e-b62ded5c9ed9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.1
vscode-redis-client|cwe|1.2.8
vscode-eslint|dba|2.2.1
gitlens|eam|11.6.1
php-intellisense|fel|2.3.14
godot-tools|gee|1.1.2
todo-tree|Gru|0.0.214
vscode-mocha-test-adapter|hbe|2.13.0
vscode-test-explorer|hbe|2.21.1
beautify|Hoo|1.5.0
path-autocomplete|ion|1.17.1
regexp-preview|Lou|0.1.5
vscode-docker|ms-|1.17.0
python|ms-|2021.10.1336267007
vscode-pylance|ms-|2021.10.0
jupyter|ms-|2021.9.1001312534
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.202.4
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
cpptools|ms-|1.7.0
test-adapter-converter|ms-|0.1.3
typescript-javascript-grammar|ms-|0.0.55
vscode-typescript-tslint-plugin|ms-|1.3.3
sqltools|mtx|0.23.0
sqltools-driver-mysql|mtx|0.2.0
autodocstring|njp|0.5.4
material-icon-theme|PKi|4.10.0
vscode-thunder-client|ran|1.9.1
vscodeintellicode|Vis|1.2.14
vim|vsc|1.21.8
quokka-vscode|Wal|1.0.405
explicit-folding|zok|0.19.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30378364
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis300:30381676
vsaa593cf:30376535
vssld246:30379911

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also what keyboard layout are you using?
