### ISSUE TITLE
Option to check diff of editor’s current buffer and on-disk data

### ISSUE THREAD

**Issue by schuelermine** [microsoft/vscode#135123]
Sometimes, it may be difficult to decide whether or not to save a dirty editor.
In particular, sometimes, editors get marked as dirty while they really aren’t different from the on-disk version or simply have no undo states (like after a reload).
In these cases, an existing procedure is to save the file under a temporary name and diff the files, but this is cumbersome.

I suggest a command, either through the command palette, a button, the context menu or a keyboard shortcut that compares the current state of the editor with the on-disk state of its associated file in a diff editor.

**Comment by cateyes99** [comment]
It's already there. Just use this command `File: Compare Active File With Saved` 😄
