### ISSUE TITLE
In side by side editor, vertical seems to be horizontal and horizontal seems to be vertical

### ISSUE THREAD

**Issue by a5hk** [microsoft/vscode#135185]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.1 (user setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Split editor side by side
2. Toggle layout

Setting is vertical but splitting has been done horizontally:

![vsv](https://user-images.githubusercontent.com/5412540/137547238-19e0aa2d-8984-46cb-a215-6f32205b913a.png)

And when I comment vertical:

![vsh](https://user-images.githubusercontent.com/5412540/137547404-585a982a-6f53-4b6c-9304-3f24179d99aa.png)

**Comment by bpasero** [comment]
This setting already shipped, so I do not really want to change it. I will document how it behaves.
