### ISSUE TITLE
Class and function dropdown boxes for code navigation

### ISSUE THREAD

**Issue by daarong** [Microsoft/vscode#13517]
Requesting navigation feature that has been in Visual Studio (since before .NET, at least VS 6).

For relevant languages, at the top of each editor window would be one or more dropdown boxes for navigating classes and functions.  The easier implementation would be a single dropdown that contained function names in alphabetical order, allowing you to jump directly to it.  If implementing more like Visual Studio, then two dropdown boxes, one for objects (classes, structs etc) and another dropdown for functions.

Image of Visual Studio implementation:
<img src="http://daarong.com/temp/vs_code_feature_request.png" />

Side note:
It seems the current methods available for navigation are either A) a lot of haphazard scrolling or B) use "Find" feature.  The latter is not the right tool for the job because often a large amount of extraneous results are present, making it tedious.

Thanks team!  Loving VS Code

**Comment by isidorn** [comment]
Did you try quick outline? Ctrl + shift + O? It works quite nice for javascript, I did not try it for .cs

**Comment by daarong** [comment]
I have not, and that looks significantly better than standard Find!  Thank you.  I did notice it's not in alphabetical order, so using the realtime filtering may be required for many/most.  It's separated by the "type" in Typescript (classes, functions, variables) which is great.

The alphabetizing aspect is a separate issue, and I may raise a separate feature request for that option.

At this point I think the only advantage this proposal has is for allowing a "legacy" method of navigation.  Otherwise it has no additional value.

Thanks!

**Comment by isidorn** [comment]
Yes - making quick outline alphabatically sorted makes sense as configuration option.
You can also easily filter by typing in there which does the trick for me most of the time.
Closing this issue since there is a replacement feature and I do not think we would consider adding a 'legacy' method of navigation that does not really fit in an editor.
