### ISSUE TITLE
html editing is not working on django

### ISSUE THREAD

**Issue by professorJair** [microsoft/vscode#135194]
Nós escrevemos os dados necessários em sua área de transferência porque era muito grande para ser enviado. Por favor, Cole.
![image](https://user-images.githubusercontent.com/91439806/137565435-16bc6a27-c8d5-4050-84e5-1755e9c4cc90.png)

**Comment by aeschli** [comment]
Django support needs to come from an extension. Please look for extensions in the marketplace.
