### ISSUE TITLE
`.inspect` does not return the updated setting but `.get` does

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#135121]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.61.0 (user setup)
OS: Windows_NT x64 10.0.22471

Steps to Reproduce:

**Started happening after VSCode release.** FYI we haven't been able to reproduce this issue locally, happens with Github action: https://github.com/microsoft/vscode-python/pull/17708 cc @karthiknadig 

1. Update a setting, for eg.
```
    const pythonConfig = vscode.workspace.getConfiguration('python');
    await pythonConfig.update('defaultInterpreterPath', 'pythonPath', false);
```
2. Wait for the change event to fire via `workspace.onDidChangeConfiguration`.
3. Query configuration via `.inspect` and `.get`:
```
    const currentConfig = this.workspace.getConfiguration('python', this.workspaceRoot);
    console.log(`Changed path [default]: ${currentConfig.get<string>('defaultInterpreterPath')}`);
    console.log('Inspect path [default]', JSON.stringify(currentConfig.inspect('defaultInterpreterPath')));
```
4. Notice `.get` returns the correct info and `inspect` doesn't.

**Comment by karthiknadig** [comment]
Still working on getting a minimal repro.
