### ISSUE TITLE
Sym link files under Git control always show all lines as updated

### ISSUE THREAD

**Issue by HiroKws** [microsoft/vscode#135198]
Issue Type: <b>Bug</b>

In Git system, a sym link  has the original file path saved as a blob.
When opened any sym link, it display content of original linked file. However the content is different with file path, so all line display green(updated) line on start of each line.

VS Code version: Code 1.61.1 (c13f1abb110fc756f9b3a6f16670df9cd9d4cf63, 2021-10-14T01:15:35.620Z)
OS version: Linux x64 5.14.9-1-default
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 1|
|Memory (System)|7.74GB (1.10GB free)|
|Process Argv|--unity-launch --crash-reporter-id ac747015-cbee-4775-af3d-27e77ec3ebb3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/default|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
laravel-extra-intellisense|ami|0.6.1
laravel-blade-spacer|aus|2.1.3
vscode-intelephense-client|bme|1.7.1
vscode-tailwindcss|bra|0.7.1
gitignore|cod|0.7.0
laravel-goto-view|cod|1.3.4
vscode-eslint|dba|2.2.1
sync-scroll|dqi|1.3.0
vscode-firefox-debug|fir|2.9.4
remotehub|Git|0.16.0
triggertaskonsave|Gru|0.2.17
google-translate|han|1.2.6
vscode-awk-hint|han|0.0.2
php-cs-fixer|jun|0.2.8
AWK|lug|0.0.2
tailwind-sass-syntax|mac|1.3.0
php-namespace-resolver|Meh|1.1.8
file-downloader|min|1.0.11
vscode-html-format|moh|0.0.4
vscode-docker|ms-|1.17.0
vscode-language-pack-ja|MS-|1.61.5
remote-containers|ms-|0.202.4
engplus|myj|1.1.3
vetur|oct|0.34.1
laravel-blade|one|1.27.0
vscode-yaml|red|0.23.0
edit-with-shell|ryu|1.3.0
multi-command|ryu|1.5.1
japanese-word-handler|sgr|1.3.0
vscode-blade-formatter|shu|0.7.29
vscode-scss-formatter|sib|2.3.0
vscode-tailwindcss|sid|0.1.0
pdf|tom|1.1.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis400:30381677
vsaa593:30376534
vssld246:30379911

```

</details>

**Comment by HiroKws** [comment]
![Screenshot_20211016_103101](https://user-images.githubusercontent.com/1240652/137568448-796ce219-3842-4b76-befb-cd90f0f37191.png)

**Comment by lszomoru** [comment]
Adding support for symbolic links is tracked in this issue: https://github.com/microsoft/vscode/issues/5970. I will close this issue as duplicate and I would like to ask you to subscribe to that issue in order to be notified when work is being scheduled. Thank you!
