### ISSUE TITLE
Bracket pair guides incorrectly shown with Markdown fenced code blocks

### ISSUE THREAD

**Issue by bshoshany** [microsoft/vscode#135125]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.0
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Enable `editor.guides.bracketPairs`
2. Create a new Markdown document
3. Insert the following content:

``````
```cpp
{
```

This is just normal text and not part of the code block.
``````

Here is the result:

![image](https://user-images.githubusercontent.com/61846320/137402184-0b765add-0103-4edf-9b98-ebe491a90f4a.png)

The problem: The bracket pair guides continue past the end of the actual code block and continue into the text. This happens whenever a code block contains non-matching brackets.

Proposed solution: The bracket pair guides should only be drawn within each individual code block, and should not continue past the end of the block (nor start before the beginning of the block).

**Comment by Zotyamester** [comment]
@hediet 
It would still highlight non-code lines until the next closing bracket.
Consider the following markdown:

```cpp
{
```

This is just normal text and not part of the code block.

```cpp
}
```

**Comment by Zotyamester** [comment]
Modifying the markdown a bit made me realize, that it actually tries to find the closing bracket in a code block of the same language.

![image](https://user-images.githubusercontent.com/40998048/137619191-5f27adbd-0766-4508-8d70-62d2803d5f89.png)
![image](https://user-images.githubusercontent.com/40998048/137619196-8f0c1da1-4fff-4523-9a26-0e6552d50d45.png)

**Comment by fivemru** [comment]
Faced the same problem in html with parentheses in data attributes:

![image](https://user-images.githubusercontent.com/30273470/137993284-31899cc1-fbe7-4f48-832e-fe8f395a51ce.png)

**Comment by hediet** [comment]
@fivemru can you make the text in your screenshot copyable?

**Comment by hediet** [comment]
I fixed #135549 to improve the situation, but I think this issue is more a feature request than a bug report.

What is the use-case of unbalanced brackets in markdown code blocks?

**Comment by bshoshany** [comment]
I think it **is** a bug, because obviously the line in my example above shouldn't exist, right?

I'm writing lecture notes for a course on C/C++ in Markdown, so I have many short code examples throughout the document, and some of them do not have balanced brackets because I'm displaying the program line by line, explaining the meaning of each line as text after the block. This is how I encountered this bug in the first place. Certainly you cannot expect that every single code block within a Markdown document will be a complete program with all its brackets balanced.

Isn't it possible to simply treat each fenced code block as an individual entity for the purpose of matching brackets, such that pair guides must always stay within the "fence"?

**Comment by SjoerdV** [comment]
Hi @bshoshany I would consider disabling code fencing altogether for markdown files. It feels to me markdown is not the right use case te enable this editor feature for IMHO
``` 
  "[markdown]": {
    "editor.guides.bracketPairs": false
  }
```
I would recommend splitting your 'markdown' from your 'code'.

My proposed workflow would be:
1. SWITCH TO ASCIIDOC LANGUAGE WITH BUILTIN INCLUDE DIRECTIVES AND MORE
* write your code in the actual coded files (ts, json, php, etc.) and have code fencing (ie. 'guides.bracketPairs') active
* use [include statements](https://asciidoctor.org/docs/asciidoc-writers-guide/#listing-and-source-code-blocks) in Vscode
* doing advanced stuff like 'includes' is probably a good reason to switch from markdown editing to a truly formal language syntax like [Asciidoc](https://asciidoctor.org/docs/asciidoc-writers-guide/) and use the [Asciidoctor](https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode) vscode extension
2. ALTERNATIVELY KEEP USING MARKDOWN BUT USE 'IMPORT' STATEMENTS THROUGH EXTENSION
* write your code in the actual coded files (ts, json, php, etc.) and have code fencing (ie. 'guides.bracketPairs') active
* install [markdown preview enhanced](https://shd101wyy.github.io/markdown-preview-enhanced/#/file-imports) extension for Vscode
* use [file import statements](https://shd101wyy.github.io/markdown-preview-enhanced/#/file-imports) in Vscode
3. ALTERNATIVELY USE MANUAL COPY/PASTE
* write your code in the actual coded files (ts, json, php, etc.) and have code fencing (ie. 'guides.bracketPairs') active
* copy/paste from the actual code files into the markdown files code blocks is always possible of course
