### ISSUE TITLE
Support win32 input mode in the terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#135127]
Newer versions of Conpty feature a win32 input mode which will cause it to _always_ request this particular when it's support by conpty with:

```
CSI ? 9001 h
```

If the terminal supports it, it can then send full blown native input records encoded as strings, see docs here: https://github.com/microsoft/terminal/blob/main/doc/specs/%234999%20-%20Improved%20keyboard%20handling%20in%20Conpty.md

This would enable a whole bunch of keybindings that work in the older Windows terminals to work, for example:

- Ctrl+Space
- Shift+Enter
- Ctrl+Break
- Ctrl+Alt+?
- Ctrl, Alt, Shift, (without another keydown/up)

Upstream issue: https://github.com/xtermjs/xterm.js/issues/2357

**Comment by Tyriar** [comment]
We support this via shell integration atm which is a cross platform solution. We could revisit this later if there's a good reason to do so.

**Comment by rikrdo89** [comment]
Could you please clarify if inline bash expansion is supported in the VScode bash/wsl integrated terminal? `ctrl+alt+r` works well in wsl outside of VScode but fails to expand a bash alias in VScode terminal.

**Comment by Tyriar** [comment]
@rikrdo89 if this is something other terminals do we should support it. Could you create an issue and point to some docs or provide steps on how to use it as I'm not familiar with that feature?
