### ISSUE TITLE
Can we make the new sync button give better feedback

### ISSUE THREAD

**Issue by mcarpenterjr** [microsoft/vscode#135172]
Issue Type: <b>Feature Request</b>

![image](https://user-images.githubusercontent.com/11430497/137521746-52ac2468-1365-4ac6-9b1d-2dba13c99d42.png)

The newish sync button is a pain point for me, it fails to give any feedback when it's syncing. I'm also curious why this was added since there are a number of other ways to trigger a sync, especially since the UI in the bottom bar delivers much better feedback.

It would be nice to see this updated to give feedback and to have the ability to toggle it on or off.

VS Code version: Code - Insiders 1.62.0-insider (284e0db6c4cac1e557a43cd6691babdaafc2e1a9, 2021-10-12T05:44:48.500Z)
OS version: Linux x64 5.4.0-87-generic
Restricted Mode: No

**Comment by lszomoru** [comment]
Adding @misolori to consider this feedback as we tweak the SCM viewlet.

**Comment by misolori** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/140731 that's already on the plan
