### ISSUE TITLE
ShellExecution does not escape file paths with spaces properly

### ISSUE THREAD

**Issue by ryanrosello-og** [microsoft/vscode#135118]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- Version: 1.61.0 (user setup)
Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date: 2021-10-07T18:13:09.652Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

- OS Version:
- Windows 10/Mac Big Sur

I've been banging my head trying to fix an issue with [an VSCode extension](https://github.com/ryanrosello-og/playwright-vscode-trace-viewer) I have created. This extension obtains the file path of the currently selected item in the VScode explorer tree. It then passes the path to a task for execution. The extension works fine for items that do not contain spaces in its file path but fails miserably when a path with a space is encountered.

Here is a simplified snippet:

```typescript
import * as vscode from 'vscode';

export async function activate(context: vscode.ExtensionContext) {
  let disposable = vscode.commands.registerCommand('playwright-vscode-trace-viewer.show', async (...args) => {
    let path = args[0].fsPath;

    const p: vscode.ShellQuotedString = {
      value: path,
      quoting: vscode.ShellQuoting.Escape
    }

    const shellExec = new vscode.ShellExecution('npx', ['playwright', 'show-trace', p]);
    let tsk = new vscode.Task({ type: `trace-viewer${Math.random()}` },
      vscode.TaskScope.Workspace,
      'trace-viewer',
      'trace-viewer',
      shellExec,
      'npx');
    vscode.tasks.executeTask(tsk);
  });

  context.subscriptions.push(disposable);
}

export function deactivate() { }
```

When I execute the extension against a filepath:

`c:\Users\ryanr\_repo\pw-tyscript\test-results\tests-start_server-bar-cw\trace (1).zip`

It garbles up the path and fails ...
```
> Executing task: npx playwright show-trace c:\Users\ryanr\_repo\pw-tyscript\test-results\tests-start_server-bar-cw\trace` `(1`).zip <

No such file or directory: c:\Users\ryanr\_repo\pw-tyscript\test-results\tests-start_server-bar-cw\trace
```
I can execute the command manually using powershell like so:

```
npx playwright show-trace c:\Users\ryanr\_repo\pw-tyscript\test-results\tests-start_server-bar-cw\trace` `(1`).zip
```
I suspect I'm not calling `vscode.ShellExecution` correctly?

**Comment by alexr00** [comment]
@ryanrosello-og did you try the other `vscode.ShellQuoting` enum values when creating your `ShellQuotedString`?

**Comment by ryanrosello-og** [comment]
hey @alexr00 , yup I tried all of the other options offered by the `vscode.ShellQuoting` enum.  Unfortunately, I still encounter the error.

**Comment by alexr00** [comment]
I made a very simple example to test with. My command:
```ts
		const path = 'c:\\users\\alros\\documents\\testing\\test a space';

		const p: vscode.ShellQuotedString = {
			value: path,
			quoting: vscode.ShellQuoting.Strong
		};

		const shellExec = new vscode.ShellExecution('dir', ['-AD', p]);
		const tsk = new vscode.Task({ type: `shell` },
			vscode.TaskScope.Workspace,
			'TheTask',
			'shell',
			shellExec);
		vscode.tasks.executeTask(tsk);
```

This worked when I used both cmd and powershell for task execution. cmd doesn't have an escape character, which is why I went with `ShellQuoting.Strong`. 

What shell are you using for task execution?

**Comment by ryanrosello-og** [comment]
@alexr00 thanks for your help.  The snippet you provided fixed my issue. 🎉
