### ISSUE TITLE
Add a setting to hide folder icons

### ISSUE THREAD

**Issue by wagerfield** [Microsoft/vscode#13518]
- VSCode Version: 1.6.0
- OS Version: 10.11.6

I use `vscode-icons` as my preferred icon set, but would prefer not to have the folder icons display in the explorer. I filed an issue with `vscode-icons` letting them know that the `vsicons.hideFolders` flag was no longer working and was told that this was a limitation of the api exposed by the latest version of VS Code (1.6.0).

Please could you provide an api to control the rendering of folder icons?

The issue I filed [can be found here](https://github.com/robertohuertasm/vscode-icons/issues/298#issuecomment-252939149).

**Comment by bpasero** [comment]
I think we should not have settings like that but encourage theme authors to provide themes without folder icons in the same way we do it for our VS Seti icon theme:

![image](https://cloud.githubusercontent.com/assets/900690/19339287/dac2945a-9122-11e6-8a3e-662520949457.png)

**Comment by julien-c** [comment]
Hmm, I would be looking for the exact opposite: I would love the default theme to display folder icons (as the layout is really weirdly-aligned without them)

**Comment by julien-c** [comment]
(See #11762 for instance)

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
