### ISSUE TITLE
Debugging vscode extension node module AND separate react UX module

### ISSUE THREAD

**Issue by lovettchris** [microsoft/vscode#135192]
This [lean4 vscode extension](https://github.com/leanprover/vscode-lean4) contains the main vscode-lean4 extension node module written in typescript, and this I can debug no problem.

But the extension also contains a separate react module named "lean4-infoview" with compilerOption "jsx": "react-jsx".  is there a way to setup debugging for the extension so I can set breakpoints in both places?

Currently setting a breakpoint in the react .tsx files doesn't work, even when I add "sourceMaps": true to the  "lean4-infoview"  tsconfig.json.  I get the "unbound breakpoint" tooltip on the breakpoint.

It would be super useful if you added a way to make this work.

**Comment by connor4312** [comment]
Certainly, though I'm not totally clear on what experience you're after. [Compound launch configs](https://code.visualstudio.com/docs/editor/debugging#_compound-launch-configurations) might do what you need...

Because the infoview is in a subfolder, you will most likely have to set `"webRoot": "${workspaceFolder}/lean4-infoview"` if you have a `chrome` or `msedge`-type debug configuration.

**Comment by lovettchris** [comment]
Thanks that looks promising, I'm using this launch config, and this launches vscode with my vscode-lean4 extension installed and running and debuggable.  But  it does not allow me to debug the .tsx code in the lean4-infoview node module that the vscode-lean4 extension is dependent on for some of the UI that shows up inside vscode.  I can debug that code at the .js level inside vscode using Ctrl+Shift+I `Toggle Developer Tools` but that is a low level view of the computed javascript, I'd rather debug the .tsx code instead and using the same vscode debugger instance rather than the web browser-ish `Toggle Developer Tools` .  I'm thinking the second launch configuration would need to be an "attach" perhaps to attach to the instance of vscode I'm debugging...or something...
```json
        {
            "name": "Launch Extension",
            "type": "pwa-extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": ["--extensionDevelopmentPath=${workspaceRoot}/vscode-lean4" ],
            "stopOnEntry": false,
            "sourceMaps": true,
            "outFiles": [ "${workspaceRoot}/vscode-lean4/out/**/*.js" ],
            "preLaunchTask": "watch"
        }
```

**Comment by lovettchris** [comment]
Awesome, thanks that is getting me very close because I now see 2 things in the the call stack window:
![image](https://user-images.githubusercontent.com/18707114/137603381-157206d7-9139-4a8f-9772-951e25081d81.png)

Perhaps you could help me by showing how to use this debugging with this [sample code](https://github.com/microsoft/vscode-extension-samples/blob/main/webview-sample/README.md).  I tried adding your `"debugWebviews": true` to this launch.json, and I see the 2 call stacks, but cannot hit breakpoints in main.js.  I also tried adding this:
```
    "rendererDebugOptions": {
         "webRoot": "${workspaceFolder}/media"
     },
```
to point to where main.js lives, but no luck either.  Interestingly I can set a breakpoint here using the "Toggle Developer Tools" 
![image](https://user-images.githubusercontent.com/18707114/137603887-71730628-613c-4fe9-b00f-9c08e0a4d45b.png)
and when I do, the same breakpoint is highlighted in my vscode debugger!, and I can continue stepping from there in VS code, but the breakpoint still remains unbound... ???

**Comment by lovettchris** [comment]
Hey I did just notice this debug output, could it be this is stopping other source maps from being loaded?

> DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to **load timeout**

**Comment by connor4312** [comment]
It looks like you're webpacking the infoview twice, so you need to use the [source-map-loader](https://webpack.js.org/loaders/source-map-loader/) to preserve the transitive sourcemaps.

Here's the changes that make breakpoints work:

```difff
diff --git a/.vscode/launch.json b/.vscode/launch.json
index e9b12f9..d98ba1a 100644
--- a/.vscode/launch.json
+++ b/.vscode/launch.json
@@ -6,6 +6,7 @@
             "name": "Launch Extension",
             "type": "extensionHost",
             "request": "launch",
+            "debugWebviews": true,
             "runtimeExecutable": "${execPath}",
             "args": ["--extensionDevelopmentPath=${workspaceRoot}/vscode-lean4" ],
             "stopOnEntry": false,
diff --git a/lean4-infoview/tsconfig.json b/lean4-infoview/tsconfig.json
index c643bf5..f1726a3 100644
--- a/lean4-infoview/tsconfig.json
+++ b/lean4-infoview/tsconfig.json
@@ -1,5 +1,6 @@
 {
   "compilerOptions": {
+    "sourceMap": true,
     /* Code generation */
     "target": "ES2021",
     "module": "ES6",
diff --git a/package.json b/package.json
index 9effa2e..d986339 100644
--- a/package.json
+++ b/package.json
@@ -8,6 +8,7 @@
   },
   "devDependencies": {
     "lerna": "^4.0.0",
+    "source-map-loader": "^3.0.0",
     "typescript": "^4.3.4"
   }
 }
diff --git a/vscode-lean4/webpack.config.js b/vscode-lean4/webpack.config.js
index 5eb016a..f9f5fde 100644
--- a/vscode-lean4/webpack.config.js
+++ b/vscode-lean4/webpack.config.js
@@ -14,7 +14,12 @@ function getWebviewConfig(env) {
 					test: /\.tsx?$/,
 					use: 'ts-loader',
                         		exclude: /node_modules/,
-				}
+				},
+				{
+					test: /\.js$/,
+					enforce: "pre",
+					use: ["source-map-loader"],
+				},
 			]
 		},
 		resolve: {
@@ -74,4 +79,4 @@ module.exports = function (env) {
 	env = env || {};
 	env.production = !!env.production;
 	return [getWebviewConfig(env), getExtensionConfig(env)];
-};
\ No newline at end of file
+};
```

**Comment by lovettchris** [comment]
It works :-)  Very happy customer :-)

![image](https://user-images.githubusercontent.com/18707114/137988745-6655b391-0061-4e03-83b9-439ca3fcfff9.png)
