### ISSUE TITLE
`Win + .` blocks typing

### ISSUE THREAD

**Issue by sumneko** [microsoft/vscode#135153]
Issue Type: <b>Bug</b>

![emoji-block-typing](https://user-images.githubusercontent.com/5213431/137466973-c5d7e12f-80f1-429c-ac8a-d369fc2d5bb1.gif)

1. Press `Win + .` to open emoji panel
2. Press `A` to close the emoji panel without selecting any emoji
3. Press `Backspace`

After thease, you can not typing anything at other position.
I have tried click other position, press `Esc` and press `Enter`, but none works.

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (13.83GB free)|
|Process Argv|D:\\github\\pretty-derby --crash-reporter-id 3f5990f0-ecc4-439e-881c-b2e6c5f5fcb2|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis300:30381676
vsaa593cf:30376535
vssld246:30379911

```

</details>

**Comment by sumneko** [comment]
@alexdima I found this problem on the company's win11 computer. I can't reproduce it on my home win10 computer. Maybe it's a problem only in win11?

**Comment by alexdima** [comment]
It is possible that this reproduces only on win11. I just took another look at your initial GIF, and I noticed that you might be using a different language than English. Are you by any chance using a different keyboard layout on your work computer than on your personal computer ?

**Comment by alexdima** [comment]
@sumneko Thank you for the extra information. I can reproduce what you describe also in Chrome and in Notepad, not just in VS Code. If I switch my keyboard layout to Chinese - Pinyin, open the emoji picker using <kbd>win</kbd>+<kbd>.</kbd>, and press <kbd>A</kbd>, nothing happens. The emoji picker does not react to my pressing <kbd>A</kbd>. Only pressing `Escape` will dismiss the emoji picker. If I try the same steps with the English keyboard layout, then the emoji picker appears to filter based on <kbd>A</kbd>. Given this issue reproduces in all kind of other software on Windows, I will close this issue as `upstream`.

**Comment by sumneko** [comment]
Do I need to report this issue to Microsoft? Or have you reported it internally?

**Comment by alexdima** [comment]
I have reported the issue internally.
