### ISSUE TITLE
ES6 methods don't work with typescript syntax check

### ISSUE THREAD

**Issue by m3l7** [Microsoft/vscode#13514]
- VSCode Version: 1.6
- OS Version: fedora 23

my current tsconfig.json is

      {
          "compilerOptions": {
              "target": "es6",
              "module": "commonjs",
              "sourceMap": true,
              "outDir": "src",
              "typeRoots": ["./typings/modules", "./typings/globals"]
          },
          "include":[
              "src/**/*"
          ]
      }

let's say I have this:

      Object.assign({});

if I compile the project with tsc --lib es6 or with a gulp task, it works correctly. However, vscode syntax check gives: 

      [ts] Property 'assign' does not exist on type 'ObjectConstructor'

**Comment by m3l7** [comment]
the same happens with Promise

**Comment by waderyan** [comment]
@m3l7 thank you for opening this issue. I have confirmed this happens with the latest bits. This is a language service issue. Moving to that repo. 

![image](https://cloud.githubusercontent.com/assets/2449568/19390403/d40f6d80-91dc-11e6-9a63-dbcb89b17977.png)

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11621
