### ISSUE TITLE
Mac code command switches to desktop when vscode is maximised

### ISSUE THREAD

**Issue by z5267282** [microsoft/vscode#135138]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

Version
<img width="273" alt="image" src="https://user-images.githubusercontent.com/80458779/137420053-bf22f450-3751-44fa-82d1-4ec886b10970.png">

1. Installed code command
2. Maximise vscode with the green button 
<img width="75" alt="image" src="https://user-images.githubusercontent.com/80458779/137420168-3c3194e5-9618-4637-96d3-c935f5d9b767.png">

3. try to enter the code command to open a file in the terminal
4. File opens in vscode but instead of staying in vscode my application switches to the desktop

Any help would be appreciated

**Comment by z5267282** [comment]
![My Movie 1](https://user-images.githubusercontent.com/80458779/137606800-550321fa-149c-4351-ba00-6ac9b2656759.gif)

When I run the code command my application switched out of vscode and into the desktop automatically.
Normally when I run the code command, the window will stay in vscode

**Comment by rzhao271** [comment]
Closing in favour of https://github.com/microsoft/vscode/issues/135291
