### ISSUE TITLE
emmet 기능

### ISSUE THREAD

**Issue by raonstar** [microsoft/vscode#135139]
너무 커서 보낼 수 없었기 때문에 필요한 데이터를 클립보드에 썼습니다. 붙여 넣으세요.

**Comment by CodeCrazy-ywt** [comment]
The necessary data was written to the clipboard because it was too large to send. Paste it.
___
seems that this user forgot to paste the needed data 😥

**Comment by rzhao271** [comment]
I'm closing the issue due to lack of activity. Please file a new issue if your problem continues to occur.
