### ISSUE TITLE
UX meeting agenda 12 October 2016

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#13519]
Retrospective on UX meeting

As discussed last week, we'd like to spend time discussing how best to use this meeting. Before the meeting, please think about what we can improve, what we should keep the same and what we should do differently.

@Microsoft/vscode - let me know if you want to join our meeting tomorrow.

**Comment by isidorn** [comment]
@bpasero is out tomorrow so it might not be the best time for a retrospecitve. Though it works for me.
On a seperate note, I would like to discuss https://github.com/Microsoft/vscode/issues/7314

**Comment by stevencl** [comment]
OK, let's leave the retrospective until we are all back (I'm out next week). 

We'll discuss #7314 tomorrow instead.

**Comment by bgashler1** [comment]
Let's also discuss #13529, if possible.  (Watermark logo/tips animation)

**Comment by stevencl** [comment]
For #7314 we agreed that we should add a workbench command that will toggle the horizontal panel between the current state and the maximised state. Maximised continues to mean 80% of the editor height, thus avoiding the need to introduce new UI to to manage the visibility of the document well/editor area and the horizontal panel.

We also discussed the watermark logo animation. Brad will report back to the team on ways to experiment with the animation timing and logo visibility.
