### ISSUE TITLE
Color tabs based on directory

### ISSUE THREAD

**Issue by qpwo** [microsoft/vscode#135175]
### Problem: forgetting your folder

When editing a workspace that has very different directories, such as `client` and `server`, it's easy to accidentally write insecure code if you think you're in client when you're in server.

### Solution: Assign a color to a directory/folder in project and color the tab/file everywhere

Right click on a folder and click 'color directory'. This adds a line to your `settings.json`:

```json
{
    "workbench.colorCustomizations": {
         "directories": {
             "server": "red",
             "client": "blue",
         }
    }
}
```

The tab's / file's color will be shown in explorer, git diff, the tab on top, ctrl-tab, and command-p.

### See also

- #135082 : They propose a more modest and less useful solution of colorizing specific files
- https://marketplace.visualstudio.com/items?itemName=orepor.color-tabs-vscode-ext : can only colorize title bar & status bar based on folder. I don't think it would be possible for an extension to do all the colorizations necessary.

**Comment by NotWearingPants** [comment]
Sounds useful, but this should use general glob paths rather then just directories. This way you can color specific file extensions in different colors.

**Comment by qpwo** [comment]
Also related to #62432  #38857 #62104 #97146 #28717 #31308 #21030 #10748 #66640  #92050 #108667 #115792 #124982 #121738 #126689 #129033 #74404  #75719 #35379  . I would judge there is significant demand for this feature.

**Comment by mark-pictor-csec** [comment]
My use case would be to color tabs based on which "project folder" the file was under, where `project folder` means a top level folder in the workspace (not sure if there's a better name).

This would allow me to tell at a glance which repo/project a file belonged to, without having to click the tab and look at the displayed path.

To generate unique but persistent colors, I would hash the folder path (or workspace name + folder name) and use the first 3 bytes as the color. It'd also be nice to be able to override the colors - perhaps based on regex - in the settings file. This would mean the colors were still useful even if two folders resulted in very similar hashes.
