### ISSUE TITLE
Support inputs in user tasks.

### ISSUE THREAD

**Issue by CareyLikeMariah** [microsoft/vscode#135161]
A simple task such as below will produce the following error: "Undefined input variable 'variableID' encountered. Remove or define 'variableID' to continue."

```json
{
    "version": "2.0.0",
    "tasks": [
    {
        "label": "echo",
        "command": "echo ${input:variableID}"
    }
    ],
    "inputs": [
    {
        "id": "variableID",
        "type": "promptString",
        "description": "Description: ",
        "default": "Hi"
    }
    ]
}
```

VS Code version: Code 1.61.1 (c13f1abb110fc756f9b3a6f16670df9cd9d4cf63, 2021-10-14T01:15:35.620Z)
OS version: Linux x64 5.10.0-9-amd64
Restricted Mode: No
Remote OS version: Linux x64 5.4.17-2102.204.4.4.el7uek.x86_64

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
TabOut|alb|0.2.1
vscode-quick-select|dba|0.2.9
python|ms-|2021.10.1336267007
vscode-pylance|ms-|2021.10.1
jupyter|ms-|2021.9.1101343141
jupyter-renderers|ms-|1.0.3
autodocstring|njp|0.5.4
indent-rainbow|ode|8.2.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis400:30381677
vsaa593:30376534
vssld246cf:30379912

```

</details>

**Comment by alexr00** [comment]
I'm not able to reproduce this issue. Do you have any other repro steps?
