### ISSUE TITLE
No "Put Back" option for file/folder which was deleted by VS Code (macOS version)

### ISSUE THREAD

**Issue by ansidev** [microsoft/vscode#135113]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.61.0
Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date: 2021-10-07T18:11:58.853Z (1 wk ago)
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: macOS BigSur 11.5.2

Steps to Reproduce:
1. Create a new project in VS Code.
2. Create a new file/folder in VS Code.
3. Right-click on the file/folder and select "Delete".
4. Click on the button "Move to Trash" in the next dialogue.
5. Open Trash and find the deleted item.
6. Right-click on it.

Expected: You should see the "Put Back" option. You can see it if you delete the item using Finder.
Actual: There is no option "Put Back". The only way to restore it is to open the target folder, then drag and drop the deleted item into it.

**Comment by JacksonKearl** [comment]
We use this Electron API for trashing files: https://www.electronjs.org/ru/docs/latest/api/shell#shelltrashitempath, looks like it doesn't support file recovery. I see some editors (Sublime text) have "Put Back" entries for their deleted items, but it puts it back in the wrong spot... 

@ansidev are you aware of any applications besides Finder that allow for this?

**Comment by ansidev** [comment]
Hmm! It's unbelievable that Apple didn't fix a silly bug like this!
