### ISSUE TITLE
Cannot Open Default Settings 

### ISSUE THREAD

**Issue by nogorilla** [Microsoft/vscode#13513]
- VSCode Version: 1.6.0
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Attempt to open user settings: Code > Preferences > User Settings
2. User settings `settings.json` will open, however, Default Settings will not open and an error message will appear: `Unable to open 'Default Settings': Cannot read property 'length' of null.`

**Comment by isidorn** [comment]
Can not reproduce on my machine -> can you please open dev console Help > Toggle developer tools and paste the full stack of the exception that you see there?

**Comment by nogorilla** [comment]
```
workbench.main.js:125 Cannot read property 'length' of null: TypeError: Cannot read property 'length' of null
    at t.n._validatePosition (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:56:3049)
    at t.n.validateRange (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:56:3520)
    at Function.e._createDecorationRange (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:69:16156)
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:69:16005
    at Array.map (native)
    at Function.e.setMarkers (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:69:15974)
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:69:20738
    at Array.forEach (native)
    at e._handleMarkerChange (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:69:20687)
    at e.invoke (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29:21008)
```

**Comment by jrieken** [comment]
This happens when diagnostics are added to disposed models. Unsure if your json language service does that?

**Comment by jrieken** [comment]
@nogorilla Also please run this again after having started code from the command line using the `--disableExtensions` flag to see if this is triggered by an extension or not

**Comment by nogorilla** [comment]
@jrieken issue does not occur when running with `--disableExtensions`.

**Comment by jrieken** [comment]
Can you list the installed extension here?

**Comment by jrieken** [comment]
@nogorilla ping

**Comment by nogorilla** [comment]
* erb - 0.0.1
* TypeScript Toolbox - 0.4.0
* beautify - 0.4.1
* One Dark Theme - 0.2.7
* ESLint - 1.0.8
* Ruby Language Colorization - 0.0.6
* ruby-linter - 1.0.0
* Angular 1 Javascript and TypeScript snippets
* Prettify JSON - 0.0.3
* Tomorrow and Tomorrow Night Theme - 0.1.3
* Liquid Languages Support - 0.0.2
* language-vscode-javascript-angular2 - 0.0.11
* Ruby - 0.9.0
* vscode-icons - 2.0.4
* Align - 0.2.0

**Comment by linkdesu** [comment]
Have you ever installed some package like "JavaScript Standard Format" ? I got the same problem today, but after I uninstalled "JavaScript Standard Format", the preferences can be open successfully !

Well, I uninstall "JavaScript Standard Format" just for testing if eslint can work the same .

**Comment by sandy081** [comment]
@jrieken What are the steps to verify this?

**Comment by jtaivainen** [comment]
I had the same problem but the problem vanished after removing beautify plugin. It was the only same plugin as nogorilla

**Comment by jrieken** [comment]
@sandy081 Code review? The problems that the model is disposed, the `cleanup` call would trigger another marker change event but our internal book keeping didn't know that the model is disposed yet

**Comment by sandy081** [comment]
@jrieken Looks good. 👍
