### ISSUE TITLE
Cannot Copy Error Messages in Interactive Output, Need to change MimeType

### ISSUE THREAD

**Issue by michaelmiscanuk** [microsoft/vscode#135211]
Hi,

When I make some error in code, and error message appears, I am not able to copy it to the clipboard - I found a workaround - clicking ... (three dots) in upper left corner of this message - it gives me the ability to choose different MimeType, there are 2 to choose from, I select second and now copy is possible:

![image](https://user-images.githubusercontent.com/37830487/137590015-bb0889e5-1839-4d0a-888a-5a9772876931.png)

![image](https://user-images.githubusercontent.com/37830487/137589939-78945525-56de-452e-a0b4-82d62162184a.png)

VSCode About:
![image](https://user-images.githubusercontent.com/37830487/137589991-3ac96afc-0fd6-4072-9e1f-86407eefcd3c.png)

Is it something on my side? Or is it a bug? 
Can you normally copy messages??
Thanks

**Comment by rebornix** [comment]
We are going to merge these two renderers.
