### ISSUE TITLE
Lightbulb doesn't open when editor.action.quickFix is executed in current insider build

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode#13528]
In the current insider build the lightbulb appears left of the line number. Now when I execute `editor.action.quickFix` using `CTRL+.` the lightbulb disappears for ~0.5s and shows up again. I'd expect to open a list displaying the possible quick fixes. It's working good in the current stable.

I'm on a Windows 10 machine.

**Comment by jrieken** [comment]
@Wosi Can add some details in what language, extension, and error you see this?

**Comment by Wosi** [comment]
Hmm..that was strange. It only appeared to me in the insider build and only with my own extension (OmniPascal) when I tried to get the quick fixes by pressing `CTRL+.`. Clicking on the lightbulb and selecting a quick fix worked as expected. So I thought it's a bug in VSCode. 
I saw my extension automatically resent file diagnostics when quickfixes are requested. That didn't show any side effect until VSCode 1.6.0. In 1.7.0 that behaviour leads VSCode to request the quickfixes again and agian when the lightbulb is opened via shortcut. 

I could fix it on my own. You can seafely close this issue.
