### ISSUE TITLE
SCM should close associated editors when associated resources are committed or discarded

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#135276]
One of my biggest SCM papercut issues is that the diff editors I had opened when reviewing an outgoing change remain open even after I committed the changes or discarded them. That makes my quick open history picker get polluted with diff editors that are no longer valid.

Would be great if any editor that was opened from a change get's discarded when done.

**Comment by omidantilong** [comment]
I left a comment in the other thread about this. I love VS Code but this bugs me a lot, every day. At its most basic surely this could be accomplished with a command palette action to close any tabs with `(Working Tree)` in their title. **I don't mind doing it once.** It's the messing around with X number of tabs in no coherent order after reviewing big changes that really annoys me. A one shot "dumb" command to kill them all would save so much time.
