### ISSUE TITLE
Cursor jumps across submodules in SCM

### ISSUE THREAD

**Issue by nicholasrq** [microsoft/vscode#135280]
Issue Type: <b>Bug</b>

- Add multiple submodules
- Switch to SCM tab on the left sidebar
- Cursor jumps across commit message fields randomly

This is verry annoying especially when one's trying to type a commit message and the cursor jumps to another field for no reason.

Seems it happens when VS Code is fetching data from the remote – Git option "Auto Fetch" is on.

Same happens when syncing changes with the remote or pushing something.

VS Code version: Code 1.61.1 (c13f1abb110fc756f9b3a6f16670df9cd9d4cf63, 2021-10-14T01:23:30.274Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|4, 4, 5|
|Memory (System)|64.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
haml-lint|aki|0.2.0
stylus|Ala|0.0.4
TabOut|alb|0.2.1
vscode-django|bat|1.6.0
vscode-gemfile|bun|0.4.2
path-intellisense|chr|2.4.0
dart-code|Dar|3.27.2
flutter|Dar|3.27.0
vscode-eslint|dba|2.2.1
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.1
vscode-npm-script|eg2|0.3.22
copy-relative-path-and-line-numbers|ezf|0.3.1
nasc-touchbar|fel|1.12.0
bloc|Fel|6.0.1
file-icons|fil|1.0.29
flutter-mobx|Flu|0.0.6
vscode-nginx-conf-hint|han|0.1.0
output-colorizer|IBM|0.1.2
error-gutters|Igo|1.0.1
pubspec-assist|jer|2.3.0
svg|joc|1.4.13
vscode-colorize|kam|0.11.1
flutter-img-sync|Lih|0.1.4
theme-monokai-pro-vscode|mon|1.1.19
graphql|mqu|0.1.2
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.17.0
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.10.1336267007
vscode-pylance|ms-|2021.10.1
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
env-cmd-file-syntax|Nix|0.3.0
vscode-versionlens|pfl|1.0.9
vscode-xml|red|0.18.0
vscode-yaml|red|0.23.0
explorer-exclude-vscode-extension|Red|1.2.0
vscode-nginx|sha|0.6.0
mdx|sil|0.1.0
sass-indented|syl|1.8.18
language-stylus|sys|1.13.0
open-in-browser|tec|2.0.0
stylus-supremacy|thi|2.16.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-icons|vsc|11.6.0
gitblame|wad|8.1.0
jinja|who|0.0.8

</details>

**Comment by nicholasrq** [comment]
Here's a video example of what's happening.

https://user-images.githubusercontent.com/767890/137722245-861cc317-5cfe-4393-b954-533753783547.mov

**Comment by lramos15** [comment]
Using #134666 To track a collection of focus issues that all get fixed by the same workaround. /duplicate #134666
