### ISSUE TITLE
Syntax highlighting html tag incorrectly

### ISSUE THREAD

**Issue by jbw91** [Microsoft/vscode#13525]
- VSCode Version: 1.6.0
- OS Version: macOS Sierra 10.12

Steps to Reproduce:

1. Open an HTML file in VSCode
2. Note (or add) any HTML custom tags (i.e. in Angular projects) that use dashes in the tag name. For example, `<app-root>Loading...</app-root>`
3. Notice the syntax highlighting of any theme, how `app` is one color and `-root` is another color.

Screenshot: 

![screen shot 2016-10-11 at 11 07 31 am](https://cloud.githubusercontent.com/assets/5883616/19280563/b218358a-8fa3-11e6-9358-36f1d921bae4.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/13448
