### ISSUE TITLE
JavaScript IntelliSense doesn't recognize class syntax

### ISSUE THREAD

**Issue by benjaminmillhouse** [Microsoft/vscode#13521]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: andischerer.theme-atom-one-dark-0.0.1, dbaeumer.vscode-eslint-1.0.7, donjayamanne.githistory-0.1.0, HookyQR.JSDocTagComplete-0.0.2, joelday.docthis-0.3.4, johnpapa.Angular1-0.1.16, ms-vscode.csharp-1.4.1, ms-vscode.js-atom-grammar-0.1.9, robertohuertasm.vscode-icons-3.0.3, wcwhitehead.bootstrap-3-snippets-0.0.7, Zignd.html-css-class-completion-1.0.3

JavaScript IntelliSense parser no longer seems to recognize class syntax when written inside of an IIFE.

Steps to Reproduce:
1. Define a class using this syntax
```
var MyClass = (function () {
  function MyClass() {
      this.id = 0;
  }
  return MyClass;
}());
```
2. Trigger IntelliSense for new MyClass(). -- nothing is shown
3. Remove IIFE and return statement
```
function MyClass() {
  this.id = 0;
}
```
4. Trigger IntelliSense for new MyClass(). -- IntelliSense is provided again

In the previous version of VS Code this format was supported and provide auto-complete options for the class as expected. I ended up going with this syntax because that is what I saw TypeScript converting class syntax down to.  However, as of the latest patch I no longer get IntelliSense on any of these classes unless I remove the IIFE and return statement.
Was this an intentional change?  Is there any official documentation on what types of class syntax VS Code will support for auto-completion?

**Comment by waderyan** [comment]
@benjaminmillhouse thank you for opening this issue. In [Feb](http://code.visualstudio.com/updates/vFebruary#_languages-javascript) we switched to a new language service for JavaScript and TypeScript. There were a number of improvements but some features that were missing in the new language service. 

This is a valid request to have added to the language service we use today. I am moving this issue to the language service repo.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11622
