### ISSUE TITLE
Markdown Preview relative link to an opened project do not work.

### ISSUE THREAD

**Issue by Alex2357** [microsoft/vscode#135241]
- VS Code Version: 1.61
- OS Version: Ubuntu 18.04 5.4.0-87-generic

Steps to Reproduce:

1. Run next
```bash
mkdir a b 
cat << EOF > a/a.md
For more details [see](/b/b.md)
EOF
cat << EOF > b/b.md
This file kinda should have more details and I should be navigated from a/a.md once I click see link there.
EOF
```
2. Open file a/a.md
3. Press Ctrl + Shift + V, click `see` link

I expect it to navigate to `b/b.md` but it says `Unable to open 'b.md': Unable to read file '/b/b.md' (Error: Unable to resolve nonexistent file '/b/b.md').`

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
