### ISSUE TITLE
Show welcome page after update

### ISSUE THREAD

**Issue by wadeanderson7** [Microsoft/vscode#1352]
Many developers that have used code for a while can't remember the welcome page. We discussed showing the welcome page for each upgrade.

**Comment by dbaeumer** [comment]
@bpasero

**Comment by bpasero** [comment]
You can always show the welcome page from the help menu.

**Comment by egamma** [comment]
@bpasero the idea is to 'force' that the user sees the welcome page. 

@wadeanderson7 In the update info message we currently have 'release notes' and 'restart' button. What would go into the release notes and what would be shown in the welcome page? Is the idea to run the welcome page into a realease notes page? Would it make sense to show the new information you would show in the welcome page in the release notes page?

**Comment by wadeanderson7** [comment]
@egamma ah the release notes is a good place for now. Let's pull back on that (edited the original description). 

Yes its possible that we could move what we want to be shown on the welcome page to the release notes page. 

Our idea was to encourage more extensions installs by making developers more aware that they could install extensions. We've seen a drop in the number of installs and so we were looking for places to prompt them to install extensions. The welcome page seemed to be a good place. 

On further discussion with the team, we have come up with better ideas and aren't sure this is the route we want to go. 

Let's table this issue for now.

**Comment by egamma** [comment]
Closing this issue. 

I've added the following sentence in the [release notes](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/latest.md):

These release notes only capture whats new in the core of Visual Studio Code. Do not forget to checkout the [marketplace](https://marketplace.visualstudio.com/#VSCode) for extensions.
