### ISSUE TITLE
[html] Support composite folding strategy

### ISSUE THREAD

**Issue by apupier** [microsoft/vscode#135279]
it would be nice to allow users to use both indentation and foldingProvider at the same time. It will be even nicer to support full composite power to enable/disable foldingProvider and indentation.

For instance, see https://github.com/zokugun/MrCode/blob/master/docs/settings/editor.foldingStrategy.md#composite-strategy

**Comment by aeschli** [comment]
Merging the ranges of two providers is not easily possible if the ranges overlap. All we currently have (TypeScript, HTML, CSS, Markdown, JSON, ...) would all conflict.
