### ISSUE TITLE
Search Option isn't available

### ISSUE THREAD

**Issue by eduardonunesp** [Microsoft/vscode#13526]
- VSCode Version: Version 1.6.0 (1.6.0) 2016-10-10T18:26:55.336Z
- OS Version: macOS 10.12

Steps to Reproduce:

1. Update VSCode to latest version (1.6.0)
2. Click on Search Button 

When click on search option the side menu is empty, also rises an error when try to access by the keyboard shortcut

```
Cannot read property 'toCustomLabel' of undefined
```

http://imgur.com/a/eA4JB

**Comment by wallverb** [comment]
https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=toCustomLabel%20

**Comment by eduardonunesp** [comment]
After removed everything, with the help of [AppCleaner](https://freemacsoft.net/appcleaner/) and reinstall a new version, it back to normal :(

**Comment by eduardonunesp** [comment]
Found something, looks like the problem have some relation with the keyboard shortcut, I have a custom file for it, if the keyboard config is empty the left menu works correctly, but after setting my config, it stop to work again. So, my two cents is "Keyboard shortcut have some relation with this bug"

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/13447
