### ISSUE TITLE
Preview Should Open in Same Tab

### ISSUE THREAD

**Issue by cawoodm** [microsoft/vscode#135216]
This should be a no-brainer - when I am editing a document I want to preview it on the right **in the same tab** and not in a separate tab or tab group. The default behaviours (open in new tab or open in new tab in new group) both mean that when I navigate away I have to manually manage getting back to 2 tab groups.

Back story - this was originally requested in #58525 and incorrectly closed and marked as a duplicate of #37883 which is a different issue/request.

The wish is that HTML/Markdown previews can open in the same TAB:
![image](https://user-images.githubusercontent.com/498834/137596955-956fca53-9e72-400e-abd7-62b643359841.png)

**Comment by cawoodm** [comment]
@mjbvz Yes, this opens the preview in a new tab. Please re-open my request.

![image](https://user-images.githubusercontent.com/498834/137846369-76ddf22e-b010-4a91-b031-f56192f93f16.png)

**Comment by mjbvz** [comment]
For that, use `View: toggle editor type` or `view: reopen editor with`

**Comment by cawoodm** [comment]
Hope this makes it plainer:
![image](https://user-images.githubusercontent.com/498834/137877198-575dc4bf-cb93-4adc-9590-9ebf07a22f6e.png)

**Comment by macintacos** [comment]
For context, I use the following setting to automatically open Markdown Previews to the side when I open a Markdown file:

```
  "markdown.extension.preview.autoShowPreviewToSide": true,
```

However, the annoying thing about this is that when you close out one of the tabs, you have to manually navigate over to the preview (or the editor) and close it out. I like to treat the markdown raw text and the preview as a single "entity", and close them/open them at the same time. That seems to be essentially what @cawoodm is asking for here, and I don't believe that this is possible. I'm in agreement that this issue should be reopened, as it's not currently possible in VSCode.
