### ISSUE TITLE
Poor Performance

### ISSUE THREAD

**Issue by dineshkumarv-ict** [microsoft/vscode#135230]
We have written the needed data into your cl
Issue Type: <b>Bug</b>

Hi,
   In recent times of few updates I'm getting VS Code run's very slow even a proper scroll is not working. I tested by switching to latest version too but it stills remains the same.

  Could you help to fix this performance issue of VS Code responding slowly?

STEPS TO REPRODUCE:
1. Open the application
2.Wait for every plugin to get loaded
3.After that scroll is not working

VS Code version: Code 1.61.1 (c13f1abb110fc756f9b3a6f16670df9cd9d4cf63, 2021-10-14T01:19:42.089Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.73GB free)|
|Process Argv|--crash-reporter-id bcdb3b43-b3b6-45ec-98a9-e197a4431359|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
angular2-snippets|dan|1.0.21
vscode-eslint|dba|2.2.1
githistory|don|0.6.18
githd|hui|2.2.4
code-beautifier|mic|2.3.3
vscode-typescript-tslint-plugin|ms-|1.3.3
es6-string-html|Tob|2.11.0
vscode-java-debug|vsc|0.36.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis400:30381677
vsaa593cf:30376535
vssld246:30379911

```

</details>

ipboard because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.
