### ISSUE TITLE
Don't provide closing paren if there are unmatched closed parens

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#13523]
- VSCode Version: 1.6

Steps to Reproduce:

Type <kbd>(</kbd> before `)`, end up with `())`
Type <kbd>{</kbd> before `}`, end up with `{}}`

**Comment by joaomoreno** [comment]
What's the language you are using in this example?

**Comment by octref** [comment]
@joaomoreno TypeScript.

**Comment by rebornix** [comment]
Let's merge this issue into https://github.com/Microsoft/vscode/issues/11222, the lack of bracket matching validation leads to this problem.
