### ISSUE TITLE
Running Code In Interactive Mode Displays Upper Part of the Window, Instead of Lower part

### ISSUE THREAD

**Issue by michaelmiscanuk** [microsoft/vscode#135212]
Hi,

I think this started quite recently.

Here is a setup.
I have screen separated to 2 sides, I have script on left and right. 

I do some work with script on the left, running it, and output always is displayed immediately on the right - on lower part.
So now everything is OK.

Here comes the change - on the right (where I have my Interactive output) I switch to different script.
Now I go back to the script on the left and run it. AND NOW the interactive output appears - BUT IT IS ON THE TOP, NOT BOTTOM - So I always have to drag it manually down to see the output.

I hope the description is understandable.

Also a picture:
![image](https://user-images.githubusercontent.com/37830487/137590332-fc06d32b-30fb-4b91-9805-842f404081e7.png)

Is it only on my side?
Thanks

**Comment by connor4312** [comment]
Duplicates #131742
