### ISSUE TITLE
You can't run code on the Browser version (GitHub.dev)

### ISSUE THREAD

**Issue by Griphcode** [microsoft/vscode#135207]
I want the to have a run button and a working terminal on the Web version of Vscode [GitHub.dev](https://github.dev/)

**Comment by gjsjohnmurray** [comment]
https://docs.github.com/en/codespaces/the-githubdev-web-based-editor#continue-working-on-codespaces

> ![image](https://user-images.githubusercontent.com/6726799/137596142-18bfda94-9f6b-40d2-b0b1-df0062dfeb72.png)

This is as designed. When using github.dev's web-based editor you don't have any provisioned execution environment. If you need one and aren't prepared to set it up locally, use GitHub Codespaces.

**Comment by Tyriar** [comment]
This is tracked in https://github.com/microsoft/vscode/issues/135565 now
