### ISSUE TITLE
XHR Failed on VScode for Mac for any extension

### ISSUE THREAD

**Issue by r-abishek** [microsoft/vscode#135259]
### Version of VScode: (Updated to latest 1.61.1)
![image](https://user-images.githubusercontent.com/52214183/137660420-82f35fa8-e6bb-48c7-8a9e-de4cda13a733.png)

### OS: MacOS Big Sur
![image](https://user-images.githubusercontent.com/52214183/137660464-92f1c300-0a52-426a-a7bf-15e43c404ecd.png)

### Issue:
I am unable to update any extensions I have - C/C++, CMake Tools, Jupyter, Python, Remote- Containers etc.. 
#### It gives the same error on clicking the extension:
![image](https://user-images.githubusercontent.com/52214183/137661672-d05e966d-c3e6-4bd7-b03f-a68f3478780a.png)
#### And gives the same error on clicking the "Update to 1.7.0" (latest version for C/C++ extension)
![image](https://user-images.githubusercontent.com/52214183/137661728-18d76e8f-feff-4cdd-9809-d560cdc9af38.png)
#### Here is the Developer Tools log:
![Screen Shot 2021-10-17 at 7 49 24 PM](https://user-images.githubusercontent.com/52214183/137661953-860b3669-297a-4dc0-99bd-fba2c687a7c7.png)
#### Here is the Logs (Shared):
![image](https://user-images.githubusercontent.com/52214183/137663186-06b53c41-924e-46f4-9bee-f48a842836d5.png)

### Similar issues for which I found no resolve. Not sure if any of these are on MacOS:
https://github.com/microsoft/vscode/issues/134985
https://github.com/microsoft/vscode/issues/133226
https://github.com/microsoft/vscode/issues/132849
https://github.com/microsoft/vscode/issues/131272
https://github.com/microsoft/vscode/issues/130962

**Comment by sandy081** [comment]
It seems that you have issues connecting to marketplace, could be proxy related too.

**Comment by deepak1556** [comment]
Can you attach the log file following the steps below,

* Launch `code --log-net-log=/tmp/netlog.json`
* Perform actions that trigger the XHR failure
* Quit the application
* Attach `netlog.json` from `/tmp` in this issue
