### ISSUE TITLE
`Collapse All` button is still grayed out after a tree view  with a `when` clause activated through `setContext`

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#135260]
Version: 1.62.0-insider (Universal)
Commit: 34eeebdd66033633ac22efd5fab928ae37916168
Date: 2021-10-15T05:15:40.239Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0

Let us define a tree view with a `when` clause, e.g., `tree-view-sample:enabled`. After setting the condition `true` with `executeCommand('setContext', 'tree-view-sample:enabled', true)`, `Collapse All` button is still grayed-out even after the tree view appeared. The button does not work.

Steps to Reproduce:

1. Execute the following sample: https://github.com/tamuratak/vscode-extension-samples/tree/use_when_for_tree/tree-view-sample
2. After `Test View` appeared, `Collapse All` button is still grayed-out. The button does not work.

![スクリーンショット 2021-10-18 12 07 25](https://user-images.githubusercontent.com/10665499/137663199-f74d0d47-d542-4612-87ff-39fc9424da3f.png)

**Comment by gjsjohnmurray** [comment]
Maybe #134762
