### ISSUE TITLE
Text is super blurry now

### ISSUE THREAD

**Issue by JoeArizona** [Microsoft/vscode#13527]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: abusaidm.html-snippets-0.0.16, cssho.vscode-svgviewer-1.2.0, dbaeumer.vscode-eslint-1.0.7, donjayamanne.python-0.4.0, DotJoshJohnson.xml-1.6.0, hnw.vscode-auto-open-markdown-preview-0.0.3, HookyQR.beautify-0.4.0, Ionide.Ionide-fsharp-2.6.9, lukehoban.Go-0.6.43, mohsen1.prettify-json-0.0.3, ms-vscode.cpptools-0.9.2, ms-vscode.csharp-1.4.1

Steps to Reproduce:
1. Update to 1.6
2. Reopen

Text has never been as crisp as Sublime, but now it's super blurry, from the menus on top to text in the workspace. At some point, you really ought to show some MS-pride and use DirectWrite since it's your tech and it's how Sublime achieves the crispest text of all editors. Something specific broke in 1.6, but I'm just mentioning DirectWrite as a long-term play.

Display is 1080p 24" with Skylake HD 530 graphics. This model: http://www.dell.com/support/home/us/en/19/product-support/servicetag/F111B22/diagnose

**Comment by bgashler1** [comment]
Can you take a side-by-side screenshot of Sublime and VS Code?

Do you have ClearType enabled?  To check go to **Start menu** and type in "cttune".  Click on
<img width="341" alt="screen shot 2016-10-11 at 11 06 19 am" src="https://cloud.githubusercontent.com/assets/11839736/19282331/c1eabc04-8fa2-11e6-9852-3b9020f5b94b.png">
And see if the box is checked to enable it.

**Comment by JoeArizona** [comment]
Sure, see attached. ClearType is enabled.

![2016-10-11_13-10-50](https://cloud.githubusercontent.com/assets/8071692/19287072/29b78454-8fb5-11e6-8bf9-022205314cba.png)

**Comment by bgashler1** [comment]
This is very unusual.  Thanks for sharing.  It's affecting your icons, too.  It seems be either a Chromium or Electron bug.  Forwarding to @bpasero to see what he thinks.

**Comment by JoeArizona** [comment]
FWIW, I see similar blurring in Opera and Brave on this machine. (Brave is Brendan Eich's new browser, also based on Chromium.) It's much less of a problem on my Ivy Bridge laptop (Intel HD 4000 GPU), for all three applications. There might be an issue with Chromium and the Skylake GPUs (though I see no blurring in Chrome itself.)

**Comment by bpasero** [comment]
likely nothing we can fix on our end up rely on electron to pick up a newer chrome. I encourage you to file bugs against other electron apps to get more attention.

**Comment by JoeArizona** [comment]
Bummer. Note that I filed a Brave bug on this back in August: https://github.com/brave/browser-laptop/issues/3556

The difference is that this has always been an issue with Brave, but only just now became an issue with VS Code 1.6.

Possible clue on reddit, where a poster attributes the same issue on Atom to the use of `translate3d`: https://www.reddit.com/r/webdev/comments/4dl0pg/i_love_atom/d6y4xmx/

It turns out Atom is blurry on this machine too, though not as blurry as VS Code 1.6. It puzzles me that there would be so much variance in the degree of blurriness across affected Electron clients. It also puzzles me that Chrome itself is never blurry, but all these Chromium projects are, so whatever Google does for Chrome makes a difference. Actually, this might be because they use DirectWrite – they implemented it a couple of years ago.

In any case, a web platform is suboptimal for a text editor, or any desktop/workstation software. Too late for that kind of architectural couch quarterbacking, I know, but maybe something can be done with 2.0 or 3.0. UltraEdit is blazing fast, even faster than Sublime, because it uses bread-and-butter C++ APIs, not shoehorned browser engines. And the UWP version of OneNote is stunningly fast and crisp. VS Code is pretty awesome, and was non-blurry before 1.6, so I hope the team can iron this one out. I love the new UI features, extension manager, etc.

**Comment by bpasero** [comment]
@JoeArizona I am playing around with a newer version of Electron and was wondering if you could give this build a try that includes it to see if something has changed with this issue: https://az764295.vo.msecnd.net/insider/d47c8ba23ff35913052db316aaeef1bb92b0dd99/VSCode-win32-1.8.0-insider.zip

Thanks

**Comment by JoeArizona** [comment]
Hi @bpasero, it's much less blurry in your new build. Screenshot below:

![vs code 1 8 insider blurriness test 3](https://cloud.githubusercontent.com/assets/8071692/20263628/cf1c141c-aa24-11e6-9adf-138ca60d82cd.PNG)

Note that the screenshot is introducing some blurriness – it's not as blurry as this in real life, and it's much better than before.

**Comment by bpasero** [comment]
Thanks, that is some good news.

**Comment by bpasero** [comment]
@JoeArizona if you agree, can we close this issue? do you expect it to become even better from what it is with the Electron update?

**Comment by JoeArizona** [comment]
Sure, close it. It looks like it's fixed (though I still hope you leverage DirectWrite in the future, which is noticeably clearer...)
