### ISSUE TITLE
[markdown] cell interpretation online for Notebooks

### ISSUE THREAD

**Issue by YoniChechik** [microsoft/vscode#135321]
feature to view markdown cell as you type.
a good extantion that does this for .md files is [markdown-all-in-one](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one)

**Comment by mjbvz** [comment]
I believe this is either asking for a wysiwyg editor for markdown cells or a side by side preview while writing the cell. Closing this as I  believe both cases are out of scope for VS Code core at this time
