### ISSUE TITLE
No highlight for invalid line of markdown

### ISSUE THREAD

**Issue by aleksey-pastuhov** [Microsoft/vscode#13539]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: alefragnani.project-manager-0.10.0, christian-kohler.npm-intellisense-0.1.3, christian-kohler.path-intellisense-1.0.2, DavidAnson.vscode-markdownlint-0.5.0, donjayamanne.githistory-0.1.0, donjayamanne.python-0.3.24, DotJoshJohnson.xml-1.6.0, eg2.tslint-0.5.39, kisstkondoros.vscode-codemetrics-1.1.3, mkaufman.HTMLHint-0.0.3, QassimFarid.ejs-language-support-0.0.1, stevejpurves.cucumber-0.9.6, stevencl.addDocComments-0.0.8, swyphcosmo.spellchecker-1.2.1, xabikos.JavaScriptSnippets-1.2.0

Steps to Reproduce:
1. just write invalid markdown
2. you see lint error on the ruller and on the bottom info line, but there is no highlight on the line inside of the editor

![image](https://cloud.githubusercontent.com/assets/11784219/19285071/64fc78c0-9001-11e6-895f-703e27227c46.png)

**Comment by mjbvz** [comment]
@aleksey-pastuhov Can you please provide the source for the invalid markdown file you are using. The markdown in the screenshot seems valid. Thanks.

**Comment by aleksey-pastuhov** [comment]
Fixed in last VSCode update
