### ISSUE TITLE
[i18n FR] Incorrect (or missing) translations

### ISSUE THREAD

**Issue by Elarcis** [Microsoft/vscode#13538]
- VSCode Version: 1.6.0
- OS Version: Windows 10

Some localized strings were (very) wrongly translated to french. It doens't just sound bad, it definitely makes no sense for most of them. Here are the ones I found (the N/A section is probably due to the last release not being translated yet, though I decided I could help to avoid errors)

| English string | Current translation | Should be |
| --- | --- | --- |
| Render whitespace | Restituer l'espace | Afficher les espaces |
| Format code | Code de format | Formater le code |
| Center group | Centre de groupe | Groupe central |
| Replace all | Remplacer tout | Tout remplacer |
| Report issues | Signaler les problèmes | Signaler des problèmes _(ok this one is /a bit/ subjective but it's probably more correct)_ |
| Go to symbol in file | N/A | Atteindre le symbole dans le fichier |
| Go to symbol in workspace | N/A | Atteindre le symbole dans l'espace de travail |
| Auto save | N/A | Sauvegarde automatique |
| Show workspace recommended extensions | N/A | Afficher les extensions recommandées de l'espace de travail |
| Configure workspace recommended extensions | N/A | Configurer les extensions recommandées de l'espace de travail |
| for the documentation about the extensions.json format | N/A | pour en savoir plus sur le format d'extensions.json |
| Install from VSIX | N/A | Installer depuis un VSIX |

These are the ones I've found for now, but I might have missed others and haven't reviewed `settings.json` yet.

Do I let you know if I find new ones? Is there a system in place to report these things? I downloaded the source, but apparently the localization in it has been automatically generated by an external tool.

EDIT: typos.

**Comment by chaskim** [comment]
VS Code 1.6.0, macOS 10.11.6

Here's one that I found as well. When you click the ellipsis that is on the top right of the editor window, the option "Fermer tout" should be "Tout fermer".

**Comment by johnliu2016** [comment]
@Elarcis, thanks for suggested translations.

@lukaschal, please send following strings to linguistic review, fix in loc as appropriate.

"**Render whitespace**"
fra/vscode/src/vs/code/electron-main/menus.nls.resx.lcl
ResID: miToggleRenderWhitespace

/fra/vscode/src/vs/editor/contrib/indentation/common/indentation.nls.resx.lcl
ResID: toggleRenderWhitespace

"**Format code**"
/fra/vscode/src/vs/editor/contrib/format/common/formatActions.nls.resx.lcl
ResID: formatAction.label

/fra/vscode/src/vs/editor/contrib/format/common/format.nls.resx.lcl
ResID: formatAction.label

"**Center group**"
/fra/vscode/src/vs/workbench/browser/parts/editor/editor.contribution.nls.resx.lcl
ResID: centerEditorGroupPicker

/fra/vscode/src/vs/code/electron-main/menus.nls.resx.lcl
ResID: miFocusSecondGroup

fra/vscode/src/vs/workbench/browser/parts/editor/editorActions.nls.resx.lcl
ResID: showEditorsInCenterGroup

"**Replace all**"
/fra/vscode/src/vs/workbench/parts/search/browser/searchWidget.nls.resx.lcl
ResID: search.action.replaceAll.disabled.label

/fra/vscode/src/vs/editor/contrib/find2/find.nls.resx.lcl
ResID: replace.replaceAll

/fra/vscode/src/vs/editor/contrib/find/browser/findWidget.nls.resx.lcl
ResID: abel.replaceAllButton

"**Report issues**"
/fra/vscode/src/vs/code/electron-main/menus.nls.resx.lcl
ResID: miReportIssues

/fra/vscode/src/vs/workbench/electron-browser/actions.nls.resx.lcl
ResID: reportIssues

**Comment by johnliu2016** [comment]
For translation 'N/A' strings, they're translated but seem late to build, @lukaschal please also review current French strings against suggested.

"**Go to symbol in file**"
/fra/vscode/src/vs/workbench/parts/quickopen/browser/quickopen.contribution.nls.resx.lcl
ResID: gotoSymbolDescription

"**Go to symbol in workspace**"
/fra/vscode/src/vs/workbench/parts/search/browser/search.contribution.nls.resx.lcl
ResID: openSymbolDescriptionNormal

"**Auto save**"
/fra/vscode/src/vs/code/electron-main/menus.nls.resx.lcl
ResID: miAutoSave

"**Show workspace recommended extensions**"
/fra/vscode/src/vs/workbench/parts/extensions/electron-browser/extensionsActions.nls.resx.lcl
ResID: showWorkspaceRecommendedExtensions

"**Configure workspace recommended extensions**"
/fra/vscode/src/vs/workbench/parts/extensions/electron-browser/extensionsActions.nls.resx.lcl
ResID; configureWorkspaceRecommendedExtensions

"**for the documentation about the extensions.json format**"
Not found in current loc pool, instead "for the documentation about the jsconfig.json format" is seen in comment line, @dbaeumer, can you check if mentioned version will be dropped to loc?

"**Install from VSIX**"
/fra/vscode/src/vs/workbench/parts/extensions/electron-browser/extensionsActions.nls.resx.lcl
ResID: installVSIX

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by dbaeumer** [comment]
@johnliu2016 this will be in the next drop that I will do tomorrow. I was a late string change in our 1.6 release.

**Comment by lukaschal** [comment]
Fixed.
