### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yk121238** [microsoft/vscode#135376]
- [ ] 打开谷歌浏览器出现黑色边框是为什么，不用vscode打开谷歌就没有，然后用vscode打开谷歌后，再用谷歌开一个页面就开不了

**Comment by CodeCrazy-ywt** [comment]
When I open Chrome, why there is a black border? If I open chrome **not** using vscode there **won't** be black borders. Then when I open Chrome using vscode, and I will fail opening another tab.
