### ISSUE TITLE
New Items button should always be rendered the same

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#135395]
Notice how the New Items button height depends on row height. Thus it looks like inconsitent rendering and it looks broken.
I suggest that we always render it as a one line height button for consistency.

fyi @misolori

![Screenshot 2021-10-19 at 16 25 40](https://user-images.githubusercontent.com/1926584/137930556-1bd85655-7c3b-45de-b54d-0ed79feef395.png)

**Comment by misolori** [comment]
Also would love to shorten `New Items` to `New` or `Updated`

**Comment by gjsjohnmurray** [comment]
@JacksonKearl I don't see how your change addresses the height issue raised by @isidorn.

**Comment by JacksonKearl** [comment]
Hm I was thinking it was wrapping due to the word break but I agree it may just be inheriting the height. Thanks, I will investigate more.

**Comment by gjsjohnmurray** [comment]
> Hm I was thinking it was wrapping due to the word break but I agree it may just be inheriting the height. Thanks, I will investigate more.

Also, don't assume that all language translations will be a single word.

**Comment by isidorn** [comment]
Thanks for fixing this. let's assign to November so we get this verified.

**Comment by misolori** [comment]
@JacksonKearl are the titles not limited to one line? Seeing this in OSS:

<img width="341" alt="CleanShot 2021-11-04 at 09 21 52@2x" src="https://user-images.githubusercontent.com/35271042/140378474-99abe14a-c4e3-4c2b-a4e2-0f17965c8fb2.png">
