### ISSUE TITLE
Panel background color implies its editor-level in visual hierarchy

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#13534]
Panels (including terminal) should appear much higher in visual hierarchy than an editor, since they can display info or run commands at the Folder level.  We should explore what background color and styles to use to differentiate it from the editor level whilst keeping it completely legible (including with colorization of text) and not detracting from the concept that some panels (like terminal) can receive user input like an editor.

![screen shot 2016-10-11 at 12 01 14 pm](https://cloud.githubusercontent.com/assets/11839736/19284351/6edfc02e-8faa-11e6-8662-b0f0f731dc99.png)

**Comment by bgashler1** [comment]
Related to #6979

**Comment by bpasero** [comment]
Closing, a theme can set the background of the panel as needed.
