### ISSUE TITLE
Feedback widget: allow to theme the checkbox

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#135383]
Originally from https://github.com/microsoft/vscode/issues/120866

```
  "workbench.colorCustomizations": {
    "checkbox.background": "#ff0000",
    "checkbox.border": "#ff0000",
    "checkbox.foreground": "#ff0000",

  }
```
should affect the feedback widget
https://user-images.githubusercontent.com/63160225/114091047-763c4d80-98b8-11eb-807b-17593a16d508.png

**Comment by bpasero** [comment]
I found no way to apply the colors on a native checkbox. We would have to go custom for checkboxes in the feedback widget.
