### ISSUE TITLE
Integrated terminal launch issue

### ISSUE THREAD

**Issue by BravesDevs** [microsoft/vscode#135363]
Issue Type: <b>Bug</b>

Whenever I try to launch the integrated terminal in the vscode it's pop up with the blank tab, it was perfectly working fine before I have installed the Jetbrains Webstorm, I have uninstalled the webstore but then after issue is not getting resolved I reinstalled vscode but still issue is there. Please help me out to resolve the issue.

VS Code version: Code 1.61.1 (c13f1abb110fc756f9b3a6f16670df9cd9d4cf63, 2021-10-14T01:19:42.089Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.10GB free)|
|Process Argv|--crash-reporter-id 822ed95c-d52d-4164-877a-019812a8ac22|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.6.1
python|ms-|2021.10.1336267007
vscode-typescript-next|ms-|4.5.20211018

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis200cf:30381675
vsaa593:30376534
vssld246:30379911

```

</details>

**Comment by abhinav-chittora** [comment]
I too have the problem with integrated terminal. For me it started with recent upgrade to latest version `1.61.1 (Universal)`. I am running visual code on MacOSx. It seems the setting up the profile to zsh or any bash isn't working. Let me know if you need more logs/configuration from my side.
