### ISSUE TITLE
in-product release notes doesn't use editor.fontSize

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#13530]
- VSCode Version:1.6.0
- OS Version: Windows 10

Steps to Reproduce:

1. Set "editor.FontSize": 20
2. Help > Release Notes

Release notes are rendered in a font size that looks smaller than the default fontSize of 14 (maybe 12?).
For users, with poor eyesight this may be an issue. Zoom is not an option due to https://github.com/Microsoft/vscode/issues/5745 which is an external Electron issue.

Workaround: go to release notes on website

**Comment by joaomoreno** [comment]
Unfortunately, we have to wait for #5745.

Release notes isn't an editor, it should not listen on the editor's font size.
