### ISSUE TITLE
Green apperance 

### ISSUE THREAD

**Issue by marisolher** [microsoft/vscode#135328]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.Install vscode in w10 (it still happen when reinstall)
2.open vscode

![image](https://user-images.githubusercontent.com/79177231/137805450-15435340-1fd3-4be0-82f3-61b2f1829c7b.png)

**Comment by TarunavBA** [comment]
@marisolher try removing the appdata folder and again installing vscode from code.visualstudio.com
