### ISSUE TITLE
不懂怎么解决

### ISSUE THREAD

**Issue by Osccar1985** [microsoft/vscode#135357]
Issue Type: <b>Performance Issue</b>

Debugging information is available via VSCode > Help > Toggle Developer Tools > Console.
Failed to install PlatformIO IDE.

VS Code version: Code 1.61.1 (c13f1abb110fc756f9b3a6f16670df9cd9d4cf63, 2021-10-14T01:19:42.089Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (11.96GB free)|
|Process Argv|--crash-reporter-id 2e07197b-9402-4a76-9ea3-09303f06f763|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    95	 10148	code main
    1	   102	  2340	   gpu-process
    0	    24	  5048	   utility
    0	   163	  5572	   window (扩展: PlatformIO IDE - Osccar1985 - Visual Studio Code [管理员])
    0	    33	  3608	     watcherService
    0	   226	  9668	     extensionHost
    0	    53	  5648	   window (问题报告程序)
    0	    65	  7388	   shared-process
    0	    34	  8032	     ptyHost
    0	    50	  9416	   window (undefined)
    0	    10	  9976	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (扩展: PlatformIO IDE - Osccar1985 - Visual Studio Code [管理员])
|    Folder (Osccar1985): 1 files
|      File types:
|      Conf files:;
```

</details>
<details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
cake-vscode|cak|1.0.0
doxdocgen|csc|1.3.2
vscode-pull-request-github|Git|0.31.0
better-cpp-syntax|jef|1.15.10
vscode-esp8266fs|kas|1.1.0
Arduino|moo|0.0.4
vscode-language-pack-zh-hans|MS-|1.61.5
csharp|ms-|1.23.16
python|ms-|2021.10.1336267007
vscode-pylance|ms-|2021.10.1
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.202.4
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
cmake-tools|ms-|1.9.0
cpptools|ms-|1.7.0
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4991
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.13.0
platformio-ide|pla|2.3.3
vscode-hack|pra|2.11.0
python|tht|0.2.3
cmake|twx|0.0.17
vscode-arduino|vsc|0.4.6
tconda|zhp|0.0.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis200cf:30381675
vsaa593:30376534
vssld246:30379911

```

</details>

**Comment by CodeCrazy-ywt** [comment]
你为什么一个issue要发三遍

**Comment by Osccar1985** [comment]
不好意思，当时网络卡。以为没法出去。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CodeCrazy-ywt ***@***.***&gt;
发送时间: 2021年10月20日 13:10
收件人: microsoft/vscode ***@***.***&gt;
抄送: Osccar1985 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[microsoft/vscode] 不懂怎么解决 (Issue #135357)





 
你为什么一个issue要发三遍
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CodeCrazy-ywt** [comment]
> 不好意思，当时网络卡。以为没法出去。
> 
> 
> 
> 发自我的iPhone
> 
> 
> ------------------ 原始邮件 ------------------
> 发件人: CodeCrazy-ywt ***@***.***&gt;
> 发送时间: 2021年10月20日 13:10
> 收件人: microsoft/vscode ***@***.***&gt;
> 抄送: Osccar1985 ***@***.***&gt;, Author ***@***.***&gt;
> 主题: 回复：[microsoft/vscode] 不懂怎么解决 (Issue #135357)
> 
> 
> 
> 
> 
>  
> 你为什么一个issue要发三遍
>  
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

ok, 行吧
