### ISSUE TITLE
Narrow intellisense

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#13537]
- VSCode Version: Code - Insiders 1.7.0-insider (cf203e09145586b96497eab230253d686c2b2a2d, 2016-10-11T06:04:58.177Z)
- OS Version: Darwin x64 16.0.0

Steps to Reproduce:

1. Split Editor
2. Hover something close to the split area

![image](https://cloud.githubusercontent.com/assets/1723815/19284933/016963da-8fc6-11e6-8d99-401dacf013f8.png)

**Comment by joaomoreno** [comment]
#13004
