### ISSUE TITLE
Feature Request: per language settings for default tab size 

### ISSUE THREAD

**Issue by wulftone** [Microsoft/vscode#13532]
The tabSize defaults to the editor default value when making a new file, and there are different standards in different languages.  It would be super helpful to have a per-language default tab size option available.  I've encountered that even after adding some content with the correct number of spaces per indent, saving the new file, then re-opening it, it still doesn't correctly detect the right tabSize all the time.  A per-language default would make this a much simpler operation.

**Comment by rmunn** [comment]
The [EditorConfig plugin](https://github.com/editorconfig/editorconfig-vscode) can help with that if you create an .editorconfig file at the root of each repo, but a per-language default setting would be easier.

**Comment by sandy081** [comment]
Duplicates #1587
