### ISSUE TITLE
Line numbers should be toggle-able for current cell AND subsequent cells (or multiple cells)

### ISSUE THREAD

**Issue by gowrishankarnath** [microsoft/vscode#135329]
In the normal Jupyter notebooks, we can add line numbers by pressing the *L* key after selecting the cell. All the subsequent cells for that notebook will have line numbers automatically.

But this is missing in VSCode. Every time a new cell is created, we need to select the cell and press the *L* key to enable the numbering for that cell which is very tiresome.

Is there a way to automatically enable line numbering for all the cells in the VSCode Jupyter notebook?

Thank you.

**Comment by rebornix** [comment]
`notebook.lineNumbers` can set line numbers for all cells and persist for all notebooks.
