### ISSUE TITLE
De

### ISSUE THREAD

**Issue by GlacianNex** [Microsoft/vscode#13533]
- VSCode Version: 1.6
- OS Version: OSX Sierra

In 1.6 features that allowed using custom runtimes was added. I tried using it to debug my program that is usually started with a grunt script. Although grunt does start, run and execute correctly debugger never gets attached to the process.

Steps to Reproduce:

1. Setup Grunt Launch config per 1.6 release note.
**This is my launch configuration:** 
{
        "name": "Launch via Grunt",
        "stopOnEntry": true,
        "type": "node",
        "request": "launch",
        "runtimeExecutable": "grunt",
        "cwd": "${workspaceRoot}",
        "preLaunchTask": null,
        "runtimeArgs": [
            "--nolazy",
            "run"
        ],
        "env": {
            "NODE_ENV": "development"
        },
        "console": "internalConsole",
        "sourceMaps": false,
        "outFiles": []
    }

2. Start the process. Program runs and does what it supposed to, but debugger never gets attached. No break points are ever hit. I tried adding "port" argument into configuration but it had no effect. 

3. My old way of doing it still works great. Here is my old launch config:
{
        "name": "Launch via Node",
        "stopOnEntry": false,
        "type": "node",
        "request": "launch",
        "program": "${workspaceRoot}/node_modules/grunt/bin/grunt",
        "args": ["run"],
        "cwd": "${workspaceRoot}",
        "preLaunchTask": null,
        "runtimeExecutable": null,
        "runtimeArgs": [
            "--nolazy"
        ],
        "env": {
            "NODE_ENV": "development"
        },
        "console": "internalConsole",
        "sourceMaps": false,
        "outFiles": []
    }

**Comment by weinand** [comment]
@GlacianNex with your "Launch via Grunt" configuration VS Code will run grunt like this:
```
grunt --debug-brk=12345 --nolazy run
```

I don't think that this makes any sense. Does grunt accept a '--debug-brk' or '--nolazy' argument? I don't think so.

Please use the correct grunt arguments to run grunt in debug mode and specify a port.

And BTW, why are you using a new approach to run grunt in debug mode if you already have found a good way to do this?
