### ISSUE TITLE
MarkdownString.supportHtml isn't in the release

### ISSUE THREAD

**Issue by eddierock1994** [microsoft/vscode#135394]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61
- OS Version: Windows 10

Steps to Reproduce:

Try accessing the supportHtml property of MarkdownString. It is in the [release notes](https://code.visualstudio.com/updates/v1_61#_markdownstringsupporthtml), but isn't supported yet. Attaching sample code below with screenshot. 

<img width="344" alt="error" src="https://user-images.githubusercontent.com/7565560/137928836-5b9d8dc2-07d6-4ab8-8502-8c895c0b0878.png">
<br>
<img width="869" alt="version" src="https://user-images.githubusercontent.com/7565560/137928945-c07ff247-0b13-4800-915e-336b995c9437.png">
<br>
<img width="805" alt="markdown-docs" src="https://user-images.githubusercontent.com/7565560/137928975-2ab7d340-44a7-4488-83fd-7fb2ebb4d82f.png">

**Comment by mjbvz** [comment]
This was a proposed api in 1.61. It will be finalized fo 1.62

See https://code.visualstudio.com/updates/v1_61#_proposed-extension-apis for how to test proposed apis

**Comment by eddierock1994** [comment]
My bad. Thanks for the clarification. Appreciate it
