### ISSUE TITLE
Add an option to hide files that are excluded by .gitignore in Explorer

### ISSUE THREAD

**Issue by cnshenj** [Microsoft/vscode#13535]
- VSCode Version: 1.6.0
- OS Version: Windows 10 1607

Steps to Reproduce:

1. Open a folder
2. Go to Explorer

A single source file may have several corresponding generated files. For example, `foo.ts` has `foo.js`, `foo.js.map`, `foo.d.ts`. It would be convenient to hide those files in Explorer, and only show them when user chooses to.

We can use files such as `.gitignore` to determine which file to hide, or use a separate file, such as `.vscignore` in `.vscode` directory.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/78
