### ISSUE TITLE
VS Code is consuming too much memory. Please fix it.

### ISSUE THREAD

**Issue by rishat5081** [microsoft/vscode#135312]
I have been using vs code for almost 3 years but from this update, it is killing my ram and I am having issues while coding.
It would be great if you could make it lightweight and it consumes less memory.
Using of extension is mandatory, I have 2 extensions but still, it is taking almost 726.2 MB of memory.
Thank you.
![image](https://user-images.githubusercontent.com/43773752/137782846-93f9d352-7ad9-4eb5-a97b-63c8b1e8bbc5.png)

![image](https://user-images.githubusercontent.com/43773752/137782777-77d656ef-476c-4593-a41c-08c21c359587.png)

**Comment by mjbvz** [comment]
Closing as not actionable. 750MB  is perfectly reasonable depending on what your workspace contains
