### ISSUE TITLE
Allow to Disable / Enable breakpoints using <kbd> + Click

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#135324]
Today, if you want to enable/disable a breakpoint, you may choose between:
* Using the context menu (Left Click and select `Disable Breakpoint`)
* Assigning a shortcut to the `"debug.enableOrDisableBreakpoint"` command

The idea is to add a new alternative, combining some Modifier Key + Mouse Click, right in the Gutter. 

By _Modifier Key_, I mean the regular ones, like <kbd>Shift</kbd>, <kbd>Alt</kbd> or <kbd>Ctrl</kbd> keys.

I'm not sure about VS, but it seems it uses <kbd>Shift</kbd>. I have used Delphi for a long time and it uses <kbd>Ctrl</kbd>. JetBrains Rider, on the other hand, uses <kbd>Alt</kbd> 🤦 .

Thank you

**Comment by roblourens** [comment]
I have also wanted this. ctrl+click will bring up the context menu currently

**Comment by roblourens** [comment]
This was implemented with shift+click in https://github.com/microsoft/vscode/issues/147597
