### ISSUE TITLE
Issue with checkout branch

### ISSUE THREAD

**Issue by danieltodor** [microsoft/vscode#135320]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.1 and todays insiders build
- OS Version: Windows 10, Archlinux

Few days ago i noticed when i checkout to another branch, vscode always asks me if i want to stash before the checkout (the "git.autoStash" setting is turned on).

Steps to Reproduce:
Basically you just need two branches and a dirty file.

1. Create a git repository.
2. Create a file, write something in it, then commit to master.
3. Create a new branch, modify the file, then commit to this branch.
4. Checkout to master, modify the file, then save it.
5. Checkout to the other branch.

Even if the autostash option is enabled, vscode will ask you if you want to stash before the checkout.
If i click on stash and press enter (empty name), then the restore/drop part works fine (if you dont't have a merge conflict).

**Comment by lszomoru** [comment]
@danieltodor, apologies for not getting back to you on this until now. The `git.autoStash` setting, is only being used to stash changes during before a pull operation is initiated so I am afraid that the current behaviour is expected.
