### ISSUE TITLE
libXScrnSaver package does not exist on openSUSE

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#13544]
From @MrSparc in https://github.com/Microsoft/vscode/issues/13439#issuecomment-252988235

> openSUSE fails to resolving the package dependency "libXScrnSaver" because the bin package is called "libXss1" (for more info see https://bugzilla.suse.com/show_bug.cgi?id=967340)
> 
> ```
>  $ sudo zypper install ./code-1.6.0-1476123947.el7.x86_64.rpm                                              
> Loading repository data...
> Reading installed packages...
> Resolving package dependencies...
> 
> Problem: nothing provides libXScrnSaver needed by code-1.6.0-1476123947.el7.x86_64
>  Solution 1: do not install code-1.6.0-1476123947.el7.x86_64
>  Solution 2: break code-1.6.0-1476123947.el7.x86_64 by ignoring some of its dependencies
> 
> ```

**Comment by dmazuronak** [comment]
The same situation on SLES 12 SP 1:

```
# rpm -Uvh code-1.6.0-1476123947.el7.x86_64.rpm   
error: Failed dependencies:
        libXScrnSaver is needed by code-1.6.0-1476123947.el7.x86_64
```

**Comment by Tyriar** [comment]
This is the result when I change the dep to be `libXss.so.1` on openSUSE (it runs fine after install):

<img width="618" alt="screen shot 2016-10-12 at 9 35 10 am" src="https://cloud.githubusercontent.com/assets/2193314/19318899/51941d98-905f-11e6-9dda-50e66b404f09.png">

And Fedora (runs fine):

<img width="725" alt="screen shot 2016-10-12 at 9 40 33 am" src="https://cloud.githubusercontent.com/assets/2193314/19319089/1e5eaf6e-9060-11e6-9b9c-c94c1e6aaddf.png">

So moving forward with this, I created https://github.com/Microsoft/vscode/issues/13616 to only install the package with the correct bitness which will be a more involved change.

**Comment by Tyriar** [comment]
Pushed to master and cherry picked to release/1.6

**Comment by Tyriar** [comment]
Verified on stable 1.6.1 @9e4e44c19e393803e2b05fe2323cf4ed7e36880e with the following:

- Fedora 64-bit installed via Software
- Fedora 64-bit installed via dnf/terminal
- Fedora 32-bit (live CD) installed via Software
- Fedora 32-bit (live CD) installed via dnf/terminal
- openSUSE 64-bit via zypper/terminal

**Comment by alexandrio** [comment]
HI, just installed RHEL 7.2 and downloaded vscode rpm, same issue, it needs libxss that its not included in fresh installation of RHEL 7.2. It works after "yum install libXScrnSaver-1.2.2-6.1.el7.x86_64"

**Comment by Tyriar** [comment]
@alexandrio this is on v1.6.0? So the libXss.so.1 dependency doesn't work on RHEL?

**Comment by alexandrio** [comment]
Yes it's v. 1.6.1 installed by rpm downloaded from the vscode page, rhel 7.2 does not have libXss.so.1 in fresh install

**RHEL Info:**
RedHat Enterprise Linux Server 7.2
Gnome 3.14.2
setup as server with GUI, development toolset

**VSCode  official RPM**
Versión 1.6.1
Confirmación 9e4e44c19e393803e2b05fe2323cf4ed7e36880e
Fecha 2016-10-13T15:43:46.054Z
Shell 1.3.7
Representador 52.0.2743.82
Node 6.5.0

**Comment by MetaiR** [comment]
```
error: Failed dependencies:
	libXScrnSaver is needed by CycligentGitTool-0.5.2-1.fc24.x86_64
```
on opensuse tumbleweed
