### ISSUE TITLE
lag in new windows of vscode containing __init__.py file

### ISSUE THREAD

**Issue by TarunavBA** [microsoft/vscode#135400]
Does this issue occur when all extensions are disabled?: Yes\No

Version: 1.61.1 (user setup)
Commit: c13f1abb110fc756f9b3a6f16670df9cd9d4cf63
Date: 2021-10-14T01:19:42.089Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. Open a fresh window of vs code 
2. experience the lag. 

## Screen gif
![recording](https://user-images.githubusercontent.com/89698728/137940016-f6411764-2062-4647-aaf4-a9ef88114aa3.gif)

**Comment by deepak1556** [comment]
Windows 7 is no longer supported, please refer https://code.visualstudio.com/docs/supporting/faq#_can-i-run-vs-code-on-windows-7 for additional context.
