### ISSUE TITLE
Latest release does not open text file on double click in Windows

### ISSUE THREAD

**Issue by kakins** [Microsoft/vscode#13543]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: DotJoshJohnson.xml-1.6.0, ms-vscode.csharp-1.4.1

This was working fine right before I installed the latest updates. 

Steps to Reproduce:

1.  Double click a .txt file with the default program set to use VS Code
2.  VS Code opens but the file does not display

**Comment by isidorn** [comment]
Might this be due to the experiments of opening vscode empty?

**Comment by joaomoreno** [comment]
I can't reproduce. Is there any information in the `Developer Tools` console? What actually happens in Code? Can you share a screenshot?

**Comment by kakins** [comment]
Well I seem to have resolved it, here's how:  I right clicked a .txt file and chose Open With -> Choose Default Program.  Text files were already set to use Code as the default program on my machine, but I selected to use VS Code again.  The file opened in Code and the contents of the .txt file displayed.  I then closed Code and reopened the file, this time by double-clicking (which was not working before).  It now opens and displays the contents of the file.

To answer your question, prior to doing what I described above, I would double click a .txt file and VS Code would open, but it would not open the file.  I saw no errors displayed, and I did not get a chance to look at the developer tools console.  It was as if I just clicked on code.exe by itself.

**Comment by joaomoreno** [comment]
Strange. I'm glad you fixed it though. 👍

**Comment by fdefouchier** [comment]
FYI I had the same issue since last update and fixed it the same way

**Comment by StillLearnin** [comment]
Same problem, same fix.
After Visual Studio Code update, double clicking a txt file would open code but wouldn't load the text file. Re-selecting vs code as the default program fixed the issue and double clicking a txt file now not only opens vs code but also loads the txt file.
