### ISSUE TITLE
dialog appear in wrong monitor in multi-monitor setup

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/vscode#135441]
Issue Type: <b>Bug</b>

SUMMARY

I have 2 monitors, one is a 4k monitor and the other is a 2K monitor. The 4k monitor is my main monitor, however dialog box from apps keeps popping up in the smaller monitor.

This is happening for vscode insider.

STEPS TO REPRODUCE
1. open vscode
2. press ctrl+n to open a new editor window
3. type anything 
4. type ctrl+w to close editor without saving

OBSERVED RESULT

The "do you want to save" dialog box pops-up in other monitor.

If you cannot reproduce, try moving the app to the other monitor, for me this happens all the time. It never did this before.

EXPECTED RESULT

The dialog box should appear centered of the app window.

SOFTWARE/OS VERSIONS

Operating System: openSUSE Tumbleweed 20211016
KDE Plasma Version: 5.23.0
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.14.11-1-default (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3080/PCIe/SSE2

ADDITIONAL INFORMATION

VS Code version: Code - Insiders 1.62.0-insider (34eeebdd66033633ac22efd5fab928ae37916168, 2021-10-15T05:15:40.814Z)
OS version: Linux x64 5.14.11-1-default
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 4199)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|62.71GB (49.27GB free)|
|Process Argv|/home/yadav/dev/docs/guides --crash-reporter-id 210d9130-10f4-4cf9-ad76-187d60112fd6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/default|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (71)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.2
vscode-base64|ada|0.1.0
vscode-tomcat|ada|0.11.3
markdown-navigation|Ala|1.0.3
Bookmarks|ale|13.2.2
aws-toolkit-vscode|ama|1.31.0
ng-template|Ang|12.2.2
vscode-apollo|apo|1.19.7
vscode-browser-preview|auc|0.7.2
vscode-tailwindcss|bra|0.7.1
dep|car|0.1.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.44.4
vscode-eslint|dba|2.2.1
java-decompiler|dgi|0.0.2
java-debug|DSn|0.0.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
terraform|has|2.16.0
haskell|has|1.7.1
markdown-preview-bitbucket|hbr|1.0.0
java-properties|ith|0.0.2
vscode-peacock|joh|3.10.1
solidity|Jua|0.0.133
language-haskell|jus|3.4.0
sort-typescript-imports|mic|1.4.1
vscode-docker|ms-|1.17.0
python|ms-|2021.10.1336267007
vscode-pylance|ms-|2021.10.1
jupyter|ms-|2021.10.1001358390
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
cpptools|ms-|1.7.0
vscode-typescript-tslint-plugin|ms-|1.3.3
angular2-inline|nat|0.0.17
vetur|oct|0.35.0
vscode-boot-dev-pack|Piv|0.1.0
vscode-manifest-yaml|Piv|1.28.0
vscode-spring-boot|Piv|1.28.0
platformio-ide|pla|2.3.4
java-ide-pack|pve|1.2.1
vscode-thunder-client|ran|1.9.1
fabric8-analytics|red|0.3.4
java|red|1.0.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|1.0.0
vue-vscode-snippets|sdr|2.2.1
markdown-preview-enhanced|shd|0.6.0
vscode-checkstyle|she|1.4.1
java-generate-setters-getters|soh|7.4.0
sonarlint-vscode|Son|3.0.0
sass-indented|syl|1.8.18
language-stylus|sys|1.13.0
serverless-ide-vscode|Thr|0.5.32
find-then-jump|tra|2.0.5
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.7.0
better-align|wwm|1.1.6
vscode-java-saber|You|0.1.2
markdown-pdf|yza|1.4.4
vscode-aspell|zap|0.1.4

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30382699
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsqsis300:30381676
vsaa593cf:30376535

```

</details>

**Comment by bpasero** [comment]
This sounds more like an Electron issue to me because we just use Electron APIs to bring up native dialogs.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/110162
