### ISSUE TITLE
What do you think about improving LUA support?

### ISSUE THREAD

**Issue by TyKonKet** [Microsoft/vscode#13545]
Lots of videogames provides a modding experience based on LUA scripting, I think, by adding supports for code formatting and intellisense you could provide a great product even to them.

**Comment by isidorn** [comment]
Thanks for the suggestion - but this should be done in a LUA extension and not be a part of the core vscode product (as all other languages, eg: pythong, go...)

**Comment by TyKonKet** [comment]
@isidorn you are right, I know, I wrote here because I saw on the marketplace that some extension (especially the most complex) are provided by Microsoft.
Thanks for the answer, have a nice day.
