### ISSUE TITLE
Response to the git commands is slow 

### ISSUE THREAD

**Issue by dipsonu10** [microsoft/vscode#135461]
the git changes especially when in **WSL2** where git add or git push or git branch changes does not show in the GUI but 
```bash
git branch -a
```
to resolve it have to *reload the window*
![image](https://user-images.githubusercontent.com/65275144/138074199-a1483413-2cd2-41f6-9e8d-ac2606ee3339.png)

Does this issue occur when all extensions are disabled? Yes

- VS Code Version: 1.61.2
- OS Version: Windows 10 21H1 (19043.1288)

Steps to Reproduce:

1.  Open the project in wsl
2. git commands like branch changes

**Comment by lramos15** [comment]
Using https://github.com/microsoft/vscode/issues/134921 to track slow updating git ui
