### ISSUE TITLE
Settings editor displays redundant category label for extensions using snake case

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode#135433]
Most extensions have a camelCased setting namespace, e.g. `gitTreeCompare.someSetting`. The extension name itself often doesn't match this namespace, in this case `git-tree-compare`, and therefore the display logic of the settings editor doesn't remove the namespace. This is unfortunate, since changing the extension name or the setting namespace is typically not an option. The [official docs page](https://code.visualstudio.com/api/references/extension-manifest) for the extension manifest says "The name of the extension - should be all lowercase with no spaces", so it's clear there is some inconsistency here if it was expected that the two should match, since setting names must be camelCased to be pretty-printed.

![image](https://user-images.githubusercontent.com/530988/137991624-355d0a79-721c-4eee-b17a-1d22955cc5cf.png)

versus

![image](https://user-images.githubusercontent.com/530988/137991678-365970a3-d89b-47fb-bc78-852e55cc9e06.png)

A good solution should be found that avoids those problems for new extensions.

Ideally, some way for existing extensions to appear nicely in the settings editor would be found as well, possibly through a UI-hint in the `"configuration"` section to ignore a given prefix for display purposes.

**Comment by rzhao271** [comment]
Yeah, I think the Settings editor should be able to recognize when the heading name is the same as the formatted namespace.

**Comment by rzhao271** [comment]
I'm changing this to a bug, but won't be fixing up the docs.

**Comment by rzhao271** [comment]
Verification steps:
1. Install the `letmaik.git-tree-compare` extension
2. Open the Settings editor, and scroll down to the settings for that extension
3. The setting names should _not_ start with the "Git Tree Compare:" string like in https://github.com/microsoft/vscode/issues/135433#issue-1030768208
