### ISSUE TITLE
Find exits multiple cursors mode

### ISSUE THREAD

**Issue by vilcans** [microsoft/vscode#135475]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. In a document, create one or more additional cursors, for example by pressing Ctrl+Alt+Down.
2. Hit Ctrl+F for search.
3. Notice that you no longer have multiple cursors.

Alternatively, press F3 (find next) in multiple cursors mode, and notice that you no longer have multiple cursors.

# Use case

I typically want this when editing lines containing some kind of separator character. The document can be code, bash commands, structured data, etc.

For example if I have a cursor at the beginning of each line in this document (that uses space as the separator):

```
abc/def First some data on this line
ghi/j/k/l Then some more
```

I want to skip the first value (the path-like string) and go to the first space, so the cursors are at the words `First` and `Then`. If it weren't for the slashes, I could press Ctrl+Right to go to the next word, but that only moves to the next slash (as it's a word separator). Searching for a space with Find would do the right thing if it didn't multiple cursor mode.

**Comment by amunger** [comment]
this could be accomplished by altering `editor.wordSeparators` and using word navigation. 
I'm also not sure how finding with multiple cursors could be done with consistently predictable behavior.
