### ISSUE TITLE
Two "New File" menus are confusing and notebook editor isn't loaded when language is set to "Jupyter" 

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode#135416]
- VS Code Version: 
Version: 1.62.0-insider (user setup)
Commit: 34eeebdd66033633ac22efd5fab928ae37916168
Date: 2021-10-15T05:16:57.817Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Click on menu File
2. There are two New File menu items, which is confusing.
![image](https://user-images.githubusercontent.com/26419852/137972703-552466c6-36e2-4c6f-8cfe-8ce8b80cd579.png)
3. Choose "New File" and select "Jupyter" from the language list. 

Expected: Notebook editor to load
Actual: The notebook editor isn't loaded
![image](https://user-images.githubusercontent.com/26419852/137972997-9d89d4da-4cd6-44ea-9ee5-1090fc0e2413.png)

**Comment by rchiodo** [comment]
@rebornix do you think we should eliminate the 'jupyter' language? It doesn't really make any sense (and drives expectations like Rong has here)

**Comment by roblourens** [comment]
I renamed "Jupyter" to "Jupyter (JSON)" as a result of this and was hoping that helps

**Comment by ronglums** [comment]
@roblourens that definitely helps! Another suggestion would be to move the two "New File" items next to each other. :)

**Comment by roblourens** [comment]
I did that in https://github.com/microsoft/vscode/issues/137328, so hopefully it's ok to close this.
