### ISSUE TITLE
Description is not viewed in intellisense if the function is a property on an object

### ISSUE THREAD

**Issue by slowmove** [Microsoft/vscode#13541]
- VSCode Version: 1.6.0
- OS Version: macOS 10.12

Steps to Reproduce:

1. Write jsdoc descriptions on your methods
2. Hover over a global function - you see the description
3. Hover over a function of an object - you do not see the description

![vscode_intellisense_description](https://cloud.githubusercontent.com/assets/624182/19287167/e866faba-9000-11e6-8ac7-f24b4e017c5a.gif)

![skarmavbild 2016-10-11 kl 22 20 57](https://cloud.githubusercontent.com/assets/624182/19287206/0d402ca8-9001-11e6-8028-79f3316a1f8b.png)

![skarmavbild 2016-10-11 kl 22 21 04](https://cloud.githubusercontent.com/assets/624182/19287212/121cc650-9001-11e6-9db1-a26acc5840b0.png)

**Comment by waderyan** [comment]
@slowmove thank you for opening this issue. This is a language service issue. Moving to the language service repo.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11624
