### ISSUE TITLE
Error: invalid marker service state

### ISSUE THREAD

**Issue by basarat** [Microsoft/vscode#13548]
- VSCode Version: Monaco latest

This is resurfacing of https://github.com/Microsoft/vscode/issues/12635 (VSCode users seem to be getting it too : https://github.com/Microsoft/vscode/issues/12635#issuecomment-252901539).

# Call stack 

Calling `monaco.editor.setModelMarkers` with an empty array reproduces it: 

![image](https://cloud.githubusercontent.com/assets/874898/19291404/93c4f1fa-9060-11e6-9e63-0a4ffb809a7e.png)

The final error location: 

![image](https://cloud.githubusercontent.com/assets/874898/19291421/a6db9b72-9060-11e6-9c91-1528f1c3c7b6.png)

You can see that `a` is undefined 

# Symptom

Markers can be set, but not cleared.

Thanks in advance :rose:

/cc  @jrieken

**Comment by basarat** [comment]
More context:

`byResource` map has key `10`:

![image](https://cloud.githubusercontent.com/assets/874898/19292035/d05ea684-9064-11e6-9301-c90227cb2450.png)

Whereas the resource url is `11`

![image](https://cloud.githubusercontent.com/assets/874898/19292043/e23643e4-9064-11e6-9cb9-d029183d8765.png)

**Comment by basarat** [comment]
Actually either this section is invalid : https://github.com/Microsoft/vscode/blob/1889442ff090ef8170814a98698506300962dbba/src/vs/platform/markers/common/markerService.ts#L158-L160  or the `remove` function of mapmap is invalid. 

# Reason:

The maps are still in sync, as seen below: 

### By Resource
![image](https://cloud.githubusercontent.com/assets/874898/19292839/d94fe220-906a-11e6-86c2-7c651ebcf26e.png)

### By Owner
![image](https://cloud.githubusercontent.com/assets/874898/19292845/e4b22e84-906a-11e6-917c-d040b295f434.png)

**Comment by jrieken** [comment]
Thanks for the info - I'll investigate

**Comment by VladimirAmiorkov** [comment]
+1 https://github.com/Microsoft/vscode/issues/12635#issuecomment-252901539

**Comment by joint-song** [comment]
+1
vscode 1.6.0 on os x 10.11.5.

**Comment by RedGlow** [comment]
+1
can confirm it's still in vscode 1.6.1 (running on windows 8).

**Comment by 0ovickyo0** [comment]
+1
monaco on win7

**Comment by jrieken** [comment]
It would be helpful if someone has reproducible steps for this

**Comment by basarat** [comment]
> It would be helpful if someone has reproducible steps for this

Sorry, after investigation, the steps for monaco were: markers are set to non empty array on one model and then set to `[]` on another model :rose:

**Comment by jrieken** [comment]
Thanks @basarat. The `MapMap.remove` function seems flawed. Surprised to have learned this

```js
a = Object.create(null);
delete a['fff'] === true
```

**Comment by alexandrudima** [comment]
@jrieken @basarat How critical is this -- should we ship a new monaco editor version?

**Comment by jrieken** [comment]
Unsure - in VS Code this doesn't seem to happen often. I guess that is because of the call patterns of the extension host. For the editor it might be a different story

**Comment by basarat** [comment]
> should we ship a new monaco editor version?

I'm fine, but thanks for asking :heart: . I've been using a custom monaco build from the beginning with [alm](http://alm.tools/) as I like to play with code, and removed the check just to get around it : https://github.com/basarat/monaco/blob/e553c2166f54bf13eb8a0b41f347d821c1a29a59/extensions/preBuild.ts#L498-L513 :rose:

I'll remove my removal of the check now :)

**Comment by VladimirAmiorkov** [comment]
To me this happens on random as stated by @jrieken . My project does not use monaco, but is a [NativeScript](https://www.nativescript.org/) application.

**Comment by BlairLeduc** [comment]
Similar to @VladimirAmiorkov, but with C++. Random; never ending "busy" indicator. VS Code 1.6.1.

**Comment by aeschli** [comment]
Verified in the moncao-editor test page
- add `monaco.editor.setModelMarkers(model, 'foo', []);` [here](https://github.com/Microsoft/monaco-editor/blob/master/test/index.js#L36)
- add `monaco.editor.setModelMarkers(model, 'foo', [{startColumn: 1, startLineNumber: 1, endColumn: 2, endLineNumber: 1, message: 'foo', severity: 1, source}]);` [here](https://github.com/Microsoft/monaco-editor/blob/master/test/index.js#L96)
- run simpleserver, open `http://localhost:8080/monaco-editor/test/?editor=dev#Y___DefaultJS` press Ctrl + F10

**Comment by ato9000** [comment]
Hi, I am hitting this issue. These are my repro steps (same as mentioned before)
    1) monaco.editor.setModelMarkers(model1, "", [/*someMarkers ...*/]);
    2) monaco.editor.setModelMarkers(model2, "", []);

Is there a workaround for this? 
Perhaps I am doing something wrong. Is there a better way to reset the editor markers?
