### ISSUE TITLE
Keystroke to open up Mac emoji/speciak key is not working from keyboard.

### ISSUE THREAD

**Issue by andriesfc** [microsoft/vscode#135480]
Issue Type: <b>Bug</b>

Open up IDE on mac.
Press ^-command-spsace, sometimes does not work. Still need to go the menu. breaks my flow.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id a951880c-ed38-4800-9d01-259cc3d1db29|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (110)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.6.4
go-outliner|766|0.1.20
vscode-tomcat|ada|0.11.3
hugofy|akm|0.1.1
markdown-navigation|Ala|1.0.3
vscode-database|baj|2.2.3
github-markdown-preview|bie|0.1.0
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-mermaid|bie|1.12.1
markdown-preview-github-styles|bie|0.2.0
markdown-yaml-preamble|bie|0.1.0
mermaid-markdown-syntax-highlighting|bpr|1.2.2
language-hugo-vscode|bud|1.3.1
npm-intellisense|chr|1.4.0
csvtojson-converter|Chu|1.0.2
ktfmt|crd|1.0.1
vscode-ssh|cwe|1.8.1
markdown-table-prettify|dar|3.5.0
vscode-markdownlint|Dav|0.44.4
jsonpath-extract|dav|1.2.3
java-decompiler|dgi|0.0.2
githistory|don|0.6.18
javadebugger|don|0.1.5
prettier-java|dot|0.1.1
xml|Dot|2.5.1
vscode-pandoc|Dou|0.0.8
gitlens|eam|11.6.1
vscode-npm-script|eg2|0.3.23
vscode-front-matter|eli|5.2.0
vscode-hugo-themer|eli|0.0.2
kotlin-formatter|esa|0.0.6
prettier-vscode|esb|9.0.0
git-project-manager|fel|1.7.1
kotlin|fwc|0.2.23
vscode-lombok|Gab|1.0.1
vscode-javac|geo|0.2.39
vscode-pull-request-github|Git|0.31.1
go|gol|0.28.1
cloudcode|goo|1.15.0
markdown-image|han|1.1.14
vscode-drawio|hed|1.6.2
vscode-remark-hugo|Hit|0.2.13
codewind-openapi-tools|IBM|0.14.1
java-properties|ith|0.0.2
vscode-edit-csv|jan|0.6.4
markdown-extended|jeb|1.0.19
vscode-insertdatestring|jsy|2.3.0
vscode-sshfs|Kel|1.23.1
vscode-gutter-preview|kis|0.28.0
go-to-spec|Lou|0.1.3
copy-json-path|Mal|1.0.2
jablo-pdf|Mar|1.0.1
reflow-markdown|mar|2.1.0
Kotlin|mat|1.7.1
markdown-shortcuts|mdi|0.12.0
markdown-formatter|mer|0.9.6
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
designessentials|mik|0.0.1
file-downloader|min|1.0.11
mindaro|min|1.0.120210803
vscode-docker|ms-|1.17.0
vscode-kubernetes-tools|ms-|1.3.3
mssql|ms-|1.10.1
remote-containers|ms-|0.202.5
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
go-doc|msy|1.0.1
sqltools|mtx|0.23.0
gradle-language|nac|0.2.3
gotestexplorer|pre|0.1.13
vscode-jsp|pth|0.0.3
vscode-data-preview|Ran|2.3.0
fabric8-analytics|red|0.3.4
java|red|1.0.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|1.0.0
java-development-extensions-pack|ric|1.4.0
java-sysout|ric|1.0.1
vscode-gradle-extension-pack|ric|0.0.4
vscode-spotless-gradle|ric|1.1.8
vscode-statusbar-json-path|ric|1.4.5
vscode-hugo|rus|0.24.0
HOCON|sab|0.0.1
svg-preview|Sim|2.8.3
vscode-taskexplorer|spm|2.5.7
code-spell-checker|str|2.0.10
even-better-toml|tam|0.14.2
vscode-markdown-paste-image|tel|0.13.8
html-preview-vscode|tht|0.2.5
vscode-markdown-table-format|Tom|1.0.1
vscode-status-bar-format-toggle|tom|2.0.0
pdf|tom|1.1.0
todo-list|Tza|1.6.0
vscodeintellicode|Vis|1.2.14
vscode-gradle|vsc|3.8.0
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.0
vscode-spring-initializr|vsc|0.7.0
vscode-icons|vsc|11.6.0
vscode-java-saber|You|0.1.2
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0
go-snippets|zsh|0.0.4
hocon-colorizer|zzz|0.4.0

(12 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis200cf:30381675
vsaa593cf:30376535
vssld246cf:30379912

```

</details>

**Comment by janmonschke** [comment]
@alexdima I am facing a similar issue. 

The emoji keyboard shortcut was working just this morning but it just stopped working. (macOS Big Sur)
I noticed one thing. The keyboard shortcut in _Edit -> Emoji & Symbols_ in Code shows a globe icon:

<img width="266" alt="Screenshot 2021-11-07 at 12 13 17" src="https://user-images.githubusercontent.com/68591/140642695-e0b48997-f30c-4061-bcf0-6e7839047be0.png">

Whereas the same menu item in other applications (in this case Firefox) shows the actual keyboard shortcut:

<img width="210" alt="Screenshot 2021-11-07 at 12 13 32" src="https://user-images.githubusercontent.com/68591/140642709-c2a2809b-447c-49b1-b724-ff4ec8d21c49.png">

Would it be possible to open the issue again?

**Comment by alexdima** [comment]
@bpasero @deepak1556 The "Emoji & Symbols" menu entry is not going through our keybinding dispatching logic, and sometimes its keybinding changes to a globe 😮 ...

**Comment by janmonschke** [comment]
@alexdima Yes, I do have a touch bar but I set it to show the expanded control strip.

However, after you mentioned it, I checked the settings and lo and behold, there is a switch for the emoji selector 🤯 

<img width="635" alt="Screenshot 2021-11-09 at 09 58 14" src="https://user-images.githubusercontent.com/68591/140893858-f1a734f6-21f1-487e-b050-7770ab90aa65.png">

I changed the `Press 🌐 to (...)` back to `Change input source` and the emoji shortcut works like before in VSCode 🎉 

Thanks for your help :) 

I still wonder how it got into this state in the first place. And I wonder where the 🌐 key would be on my keyboard / touch bar...

**Comment by bpasero** [comment]
I believe the globe key is present on some keyboards to switch input language (refs: https://discussions.apple.com/thread/7408870). 

I am not sure what is expected here from us to change.

**Comment by janmonschke** [comment]
IMO this turned out not to be an issue of VSCode and this issue can be closed
