### ISSUE TITLE
language-specific setting for format on save

### ISSUE THREAD

**Issue by skybrian** [Microsoft/vscode#13547]
- VSCode Version: 1.6.0
- OS Version: Ubuntu 14.04.5 LTS

Steps to Reproduce:
1. Turn on "format on save":
2. Edit json file
3. Save the file

```
  "editor.formatOnSave": true,
```

I'd like to use "format on save" for source code in my main language, but not for JSON or any other language. So it seems like this setting should be language-specific? Instead of a boolean, perhaps have a list of languages (or perhaps file extensions) for which format on save should be turned on?

**Comment by mjbvz** [comment]
Related to #1587, which tracks support for general language specific settings.
