### ISSUE TITLE
Can't open terminal when opening a Chinese named directory

### ISSUE THREAD

**Issue by Menci** [Microsoft/vscode#13549]
- VSCode Version: 1.5.3
- OS Version: Windows 7

Steps to Reproduce:

1. Create a directory `D:\呵呵da`
2. Right-click the directory, click `Open with code`.
3. <kbd>Ctrl + `</kbd> to open terminal.
4. The error message is '通过退出代码 1 终止的终端进程'

Can't reproduce it under Linux.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/7727
