### ISSUE TITLE
css

### ISSUE THREAD

**Issue by FelipeNunesLucho** [microsoft/vscode#135489]
Issue Type: <b>Bug</b>

{
	"resource": "/c:/Users/Felipe NUNES/Desktop/meu site/css/index.css",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "{ expected",
	"source": "css",
	"startLineNumber": 14,
	"startColumn": 4,
	"endLineNumber": 14,
	"endColumn": 4
}
quando digito algo no meu style.css aparece esse erro

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Atom(TM) x5-Z8300  CPU @ 1.44GHz (4 x 1440)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|1.85GB (0.22GB free)|
|Process Argv|--crash-reporter-id 3d5d444f-a9de-4ea0-a51e-a64cf7d98b2d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-pt-BR|MS-|1.61.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis200cf:30381675
vsaa593cf:30376535
vssld246cf:30379912

```

</details>

. sempre que digitalizo na minha pasta css da esse erro

**Comment by aeschli** [comment]
Can you share a small css code sample that shows the error?
