### ISSUE TITLE
Language extension settings: zoom breaks layout

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#135437]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Insiders 1.62
- OS Version: macOS 11.6

Steps to Reproduce:

1. Navigate to Settings > TypeScript
2. Find a setting or group of settings with images 
3. Adjust editor zoom

Example:
![CleanShot 2021-10-19 at 15 27 51@2x](https://user-images.githubusercontent.com/25163139/138002626-c311116c-dbaa-4ba7-8116-ea0073c2931e.png)

**Comment by rzhao271** [comment]
Closing in favour of https://github.com/microsoft/vscode/issues/134001
