### ISSUE TITLE
Wrong slash used for wsl untitled file display

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#135506]
1. Open a wsl window
2. In the terminal, create an untitled file by running `code-insiders newFile.txt`
3. This should open a untitled file called `newFile.txt`
4. Hover over the new file's tab

**bug**
The path uses `\` even though we are on wsl

![Screen Shot 2021-10-20 at 12 40 23 PM](https://user-images.githubusercontent.com/12821956/138161034-8aa647d0-a024-4db9-8e6b-aceda22dfe52.png)

Once the file is saved, the path starts using `/` as expected

**Comment by julie777** [comment]
I think using forward slash for paths on all systems is reasonable.

I have been writing python with forward slashes on Windows for 20 years. 
They work for all win32 APIs. 
They work in powershell and WSL. 
The only place the don't work is cmd.exe.
