### ISSUE TITLE
"You don't have permission to view this page" error when trying to enable Settings Sync with a Microsoft Account on vscode.dev

### ISSUE THREAD

**Issue by pranavAbe** [microsoft/vscode#135514]
While trying to enable Settings Sync on insiders.vscode.dev using a Microsoft Account, the authentication prompt to enter my credentials pops up, and after entering the right credentials, the following screen is displayed: 

![image](https://user-images.githubusercontent.com/29583966/138183967-62a68365-bba6-41a0-9d8a-e6c550739816.png)

I have tried checking my local VS Code installation to see if this issue presented itself, but it seems like the issue is confined to the vscode.dev website solely. 

---

Version: 1.62.0-insider
Commit: 2ae9352ae33ced58772683b60d961c604c9576ff
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.18 Safari/537.36
Embedder: vscode.dev

**Comment by TylerLeonhardt** [comment]
Nice catch @pranavAbe! This is fixed now. Can you confirm on your end?
