### ISSUE TITLE
Unable to move one folder to other giving error

### ISSUE THREAD

**Issue by abhijitchikane** [microsoft/vscode#135547]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61
- OS Version: Windows 11

Steps to Reproduce:

1. Drag folder with multiple files to moved the files into another folder

![image](https://user-images.githubusercontent.com/50770619/138253860-bb13c1d3-1c57-4e76-9ea0-c358ce90e881.png)

**Comment by gjsjohnmurray** [comment]
Related to #135528
