### ISSUE TITLE
VScode will crash  When open C/C++ floder

### ISSUE THREAD

**Issue by ZCShou** [Microsoft/vscode#13553]
- VSCode Version: Code - Insiders 1.7.0-insider (cf203e09145586b96497eab230253d686c2b2a2d, 2016-10-11T06:11:07.928Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: robertohuertasm.vscode-icons-3.0.3

Steps to Reproduce:

1. When VSCdoe opens last  floder including some C/C++ file  automatically, It will crash.
2.  Maybe related to  vscode-cpptools
3. Only display on the last updates

**Comment by isidorn** [comment]
I would put my money that your vscode-icons extension is causing this. This extension is modifying the source code of vscode in a bad way. Uninstrall that extension and start using vscode's built in support for icons please.
If it still does not work then let me know and I will reopen the issue.
