### ISSUE TITLE
add more reasons to onDidChangeTextDocument workspace event

### ISSUE THREAD

**Issue by Aviortheking** [microsoft/vscode#135545]
It is impossible to differienciate change events coming from the user keyboard than from other sources 

ex:
- Replace/ReplaceAll are emitting to this event
- liveshare extension is also emitting to this event

It would be great to add more reasons to help discerning thoses different events with reasons like

- "Keyboard" or "UserChange"
- "Replace"
- "Extension"

It is needed for extensions like Code::Stats that use it for coding stats

**Comment by PEZ** [comment]
It would be great to be able to pass custom reasons as strings to to `TextEditor.edit()`. I generate edits in this event and need a way to know if it is ”my own” edits that are coming in/back.

**Comment by PEZ** [comment]
Like @Aviortheking I am very curious about why this is deemed out of scope. Are there alternative routes an extension developer can take to achieve similar results as what this suggestion would enable?

**Comment by jrieken** [comment]
I guess you have read and acknowledged https://github.com/Microsoft/vscode/wiki/Issue-Grooming#out-of-scope-feature-requests. Closing as "out-of-scope" means being honest about not tackling/completing this issue in the foreseeable future. This doesn't mean never but it means we won't carry it around as dead weight until we do tackle it.
