### ISSUE TITLE
In macOS fullscreen, 'New Window' instead opens new tab

### ISSUE THREAD

**Issue by kamcma** [Microsoft/vscode#13550]
- VSCode Version: 1.6.0
- OS Version: macOS Sierra 10.12

Steps to Reproduce:
1. Take a VS Code window full-screen
2. From the File menu, select New Window

This is possibly related to the new behavior in Sierra that gives applications using NSDocument Safari-style tabs for free.

**Comment by bpasero** [comment]
You should report this against Electron where we depend on for a fix it seems.

**Comment by andrekosak** [comment]
actually being able to open `new window` as `new tab` is a nice feature. i would like to be able to open a project in a new tab not only in the full-screen mode.

it would look like the **Maps** application in macOS. If you go to menu `File` -> you have options `New Window` and `New Tab`

**Comment by Ibrasau** [comment]
"New Window" now literally opens new window in fullscreen mode using latest version. Is there a way to revert this and make "New Window" open new tab again? Haven't found any option in settings that does it.

**Comment by bpasero** [comment]
No, not until Electron supports native tabs properly.

**Comment by ben-moore** [comment]
It's a shame this changed, I preferred the tabbed window behaviour we had prior to the last release, made it much easier to manage the 4 or 5 instances I often have running.

**Comment by extrame** [comment]
miss it too...

**Comment by kamcma** [comment]
To be clear: I was never against there _being_ a 'New Tab' option at all, just pointing out that it was explicitly incorrect platform behavior to open a new tab when a Mac user invokes a 'New Window' menu item or keyboard shortcut. Look at your Safari menu; 'New Window' and 'New Tab' happily coexist. Just have them each do what they say they do.

**Comment by yan-foto** [comment]
This is the kind of OCD "bug/feature" fixes are not out of *necessity*, but of (definition) *correctness*. I bet there are enough mac users who enjoyed this option and it would have been possible to keep it alive along a new `new window` menu option.

I use VSCode on both mac an Linux and I had come to terms with having tabs in mac and the lack of it in Linux. Now I guess I could be *glad* to have the same behavior on both operating systems(?).

**Comment by sunfshine** [comment]
Really like this feature, hope it can back in other style
