### ISSUE TITLE
Ability to refresh problems 

### ISSUE THREAD

**Issue by SergeyBeloglazovRL** [microsoft/vscode#135542]
I want to duplicate this closed issue:
https://github.com/microsoft/vscode/issues/111443
My VSCode shows an inexistent problem:
![изображение](https://user-images.githubusercontent.com/67962205/138249294-8e4c8224-fd62-498c-845c-2d3e577a2a02.png)
It doesn't related to any extension or the extension isn't showed.
There have to be a way to refresh it.

Another problems problem is "show active file only" filter. It doesn't work often.
It shows nothing. But if I uncheck it, it shows problems in active file. 
May be it is related to a problems cache.

**Comment by sandy081** [comment]
Can you please provide steps to reproduce the issue

**Comment by SergeyBeloglazovRL** [comment]
Here is an example for "T_IF" error:
![изображение](https://user-images.githubusercontent.com/67962205/138289837-2d49bb96-ac87-427e-b5ee-e193a47757d4.png)
Then I edited it to this:
![изображение](https://user-images.githubusercontent.com/67962205/138290199-f86a4ef1-d457-4bc5-b08b-c102a5007c4b.png)
And received a persistent "T_IF" error:
![изображение](https://user-images.githubusercontent.com/67962205/138290385-c81cc2c0-f53a-4d11-91e4-7c0830b05289.png)
Even if I has deleted the "if" block, it is still displayed:
![изображение](https://user-images.githubusercontent.com/67962205/138290581-a78ed471-4bce-4fd9-8fe9-258746234ce0.png)
