### ISSUE TITLE
VS Code Setup Error - uc.micro folder creation access is denied by Antivirus

### ISSUE THREAD

**Issue by ybng** [Microsoft/vscode#13559]
- VSCode Version: 1.6
- OS Version: Windows Server 2012
- Antivirus: McAfee

Antivirus treat the uc.micro folder creation as Ransomware virus and cause the setup failure.

Steps to Reproduce:

1. Download VS Code installer
2. Setup by accepting all default configuration
3. We will get setup error in uc.micro folder creation access is denied, exact error below:-

```
---------------------------
Error
---------------------------
C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\markdown\node_modules\uc.micro\CHANGELOG.md



An error occurred while trying to create a file in the destination directory:

Setup was unable to create the directory "C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\markdown\node_modules\uc.micro".



Error 5: Access is denied.



Click Retry to try again, Ignore to skip this file (not recommended), or Abort to cancel installation.
---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by joaomoreno** [comment]
Please file this issue with McAfee.

**Comment by remojansen** [comment]
Hi guys, we updated vscode to the latest version this week and all the developers in the company could not work as a result of this issue. We have resolved it but It might be interesting to check this out it could affect a lot of organizations.

**Comment by maddin2016** [comment]
Same for us. We are not able to install vscode!!

**Comment by joaomoreno** [comment]
Also, as a workaround, download the zip archive and run Code from there: https://vscode-update.azurewebsites.net/latest/win32-archive/stable

**Comment by oliver-moran** [comment]
I noticed `uc.micro` isn't included in the zip archive. Is there any particular danger associated with just ignoring it on installation?

Reporting the issue to McAffee sounds like the meeting of an unstoppable force and an immovable object.

**Comment by CRyuzo** [comment]
I've fixed this just uninstalling my Anti-Virus temporalily.

Hope this help you.

**Comment by robotbroken** [comment]
@oliver-moran I was just hitting "ignore" when the error(s) popped up during installation. Everything seemed to work fine but I may just not have tried to use the bit that was broken...
