### ISSUE TITLE
I'm unable to watch variables in visual studio code when working on csharp

### ISSUE THREAD

**Issue by djbreen7** [Microsoft/vscode#13555]
I'm unable to watch variables in visual studio code when working on csharp

**Error CS1525: Invalid expression term '<term>'**

- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: ms-vscode.csharp-1.4.1, ms-vscode.mono-debug-0.11.0, ms-vscode.PowerShell-0.7.2

Steps to Reproduce:

1. Create a new csharp project
2. Create a variable of any type (int, string, double, ...)
3. Add a breakpoint with the debugger
4. Start the dubugger
5. Add your variable to watch
![capture](https://cloud.githubusercontent.com/assets/13296622/19294360/065dcc3c-8fe9-11e6-8edf-3958965ba485.PNG)

![capture2](https://cloud.githubusercontent.com/assets/13296622/19294379/30497ed8-8fe9-11e6-8f3c-d366f474871a.PNG)

**Comment by isidorn** [comment]
Thanks for reporting this issue but the problem is coming from the csharp extension. Can you please file this issue here https://github.com/OmniSharp/omnisharp-vscode

Thanks

**Comment by djbreen7** [comment]
You bet. Thanks for the quick reply. @isidorn
