### ISSUE TITLE
When remote with Windows 10 host, paths in Terminal window are not ctrl-clickable

### ISSUE THREAD

**Issue by weichensw** [microsoft/vscode#135569]
- VSCode Version: 1.42.0 insider
- Local OS Version: Windows 10 18363.592 with official OpenSSH Client
- Remote OS Version: Windows 10 18363.592 with official OpenSSH Server
- Remote Extension/Connection Type: SSH (Nightly)

Steps to Reproduce:

1. Connect to Windows 10 remote host
2. Run a command in terminal that will print paths. In this case, TypeScript compiler (`tsc`) was ran.
3. Note that all paths are not ctrl-clickable. An example of such path would be:
```
C:/r/project/modules/runtime/tsconfig.json
```
4. Note the same path when using VSCode locally is clickable.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by Tyriar** [comment]
This should work now, let me know if not and I can reopen.
