### ISSUE TITLE
vscode 1.6 terminal typing problem

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#13554]
- VSCode Version: 1.6
- OS Version: osx

Steps to Reproduce:

1. start a terminal
2. type `123456789abcd-`
3. type `c`
4. then the `c` show at next line
5. type `d`
6. `cd` resume

![vscode-termial-typing-bug](https://cloud.githubusercontent.com/assets/227713/19294265/74c2c096-905d-11e6-9f43-95ca5120c4af.gif)

**Comment by Tyriar** [comment]
@atian25 can you use dev tools (Help > Toggle Developer Tools) and inspect the terminal? I'm interested in:

- How wide the terminal panel is
- How wide the problem terminal row is and its contents
- How wide `.xterm-rows` is

**Comment by atian25** [comment]
![image](https://cloud.githubusercontent.com/assets/227713/19332039/19fa1bc8-911b-11e6-8bc9-10e12e7254f1.png)

![image](https://cloud.githubusercontent.com/assets/227713/19332018/f53b8a2e-911a-11e6-9526-fb419bd1cb28.png)

![image](https://cloud.githubusercontent.com/assets/227713/19332026/04416e30-911b-11e6-8d12-f59bc518e60d.png)

![image](https://cloud.githubusercontent.com/assets/227713/19332052/40d8f962-911b-11e6-9b00-a91852a67d69.png)

**Comment by Tyriar** [comment]
@atian25 do you have a custom font in settings? Can you try changing it to a different one and see if it still reproduces?

Related: https://github.com/sourcelair/xterm.js/issues/227

**Comment by atian25** [comment]
not,  `editor.fontFamily` is default as `"editor.fontFamily": "Menlo, Monaco, 'Courier New', monospace"`

and after some try, it' must be `Menlo` problem, remove it and everything is ok

**Comment by atian25** [comment]
so @Tyriar the only way is to remove this font ?

**Comment by Tyriar** [comment]
@atian25 well that may be a temporary fix if it's super annoying. This looks like an [upstream](https://github.com/sourcelair/xterm.js) issue to do with width not being uniform on some fonts.

**Comment by Tyriar** [comment]
Thing I managed to repro this (or something very similar) using my normal font Hack on Ubuntu:

![image](https://cloud.githubusercontent.com/assets/2193314/19738505/96308a46-9b6c-11e6-971c-7616bdcdcd27.png)

Adding styles `.xterm-rows { right: 0; }` *OR* `.xterm-rows > div { white-space: nowrap; }` fix it. It's strange how inconsistent this wrapping is though considering that the lines should fit inside the container.

**Comment by Tyriar** [comment]
Put out a PR upstream and pulled the change into vscode since we forked the css file.
