### ISSUE TITLE
Add shortcuts for nextDiff and prevDiff in DiffEditor

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#1355]
It would be handy to have shortcuts for both buttons in **DiffEditor**.

Suggestions: 
* **nextDiff**: `Ctrl + Shift + N` 
* **prevDiff**: `Ctrl + Shift + P`

**Comment by bpasero** [comment]
The default keybinding is (complicated because we are running out of keys): `Cmd+K Cmd+Left` for previous change and `Cmd+K Cmd+Right` for next change. Will only work if a text diff editor is visible.
