### ISSUE TITLE
Can we please get a JSON Explorer like in Visual Studio?

### ISSUE THREAD

**Issue by AaronSaikovski** [Microsoft/vscode#13552]
- VSCode Version: 1.6.0
- OS Version: 14393.321

can we please get a JSON explorer added like in Visual studio

**Comment by aeschli** [comment]
We have no plans of adding that to VSCode but this would be a great opportunity for an an extension. Check out the various previews such as the [css preview](https://marketplace.visualstudio.com/items?itemName=eg2.vscode-css-properties) as an example on how to do that.
