### ISSUE TITLE
Integrated Terminal: Triple-click-drag-up should select initial line too

### ISSUE THREAD

**Issue by matt-kempster** [microsoft/vscode#135567]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: all
- OS Version: Windows 10

Steps to Reproduce:

1. Open an integrated terminal
2. Triple click a line, and hold down the third click
3. Drag upwards (not downwards)
4. Note that the bottom-most (aka first) line is no longer selected.

I believe this is a bug because when dragging down, the first line remains selected.

**Comment by roryokane** [comment]
This segment of code [within xterm.js’s file `SelectionService.ts`][code] looks related to this issue:

[code]: https://github.com/xtermjs/xterm.js/blob/f4da8af2e948f8f7ae48163153f243152dd3efce/src/browser/services/SelectionService.ts#L601-L608

```typescript
  /**
   * Handles the mousemove event when the mouse button is down, recording the
   * end of the selection and refreshing the selection.
   * @param event The mousemove event.
   */
  private _onMouseMove(event: MouseEvent): void {
    // ...

    // Select the entire line if line select mode is active.
    if (this._activeSelectionMode === SelectionMode.LINE) {
      if (this._model.selectionEnd[1] < this._model.selectionStart[1]) {
        this._model.selectionEnd[0] = 0;
      } else {
        this._model.selectionEnd[0] = this._bufferService.cols;
      }
    } else if (this._activeSelectionMode === SelectionMode.WORD) {
```

**Comment by meganrogge** [comment]
fixed with the update of xterm.js
