### ISSUE TITLE
File body scrolls until last line reaches the top 

### ISSUE THREAD

**Issue by rogeriotaques** [Microsoft/vscode#13558]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:28:55.412Z)
- OS Version: Darwin x64 15.6.0
- Extensions: EditorConfig.EditorConfig-0.3.3, HookyQR.minify-0.2.4, HvyIndustries.crane-0.2.1, Kasik96.format-indent-1.3.0, SirTori.indenticator-0.2.1, TwentyChung.jsx-0.0.1, Zignd.html-css-class-completion-1.0.3, bcmarinacci.theme-material-1.3.0, emmanuelbeziat.vscode-great-icons-1.1.11, flowtype.flow-for-vscode-0.3.2, hnw.vscode-auto-open-markdown-preview-0.0.3, robinbentley.sass-indented-1.1.0, wmaurer.html2jade-0.2.0

Steps to Reproduce:

1. Open any source-code file, such as: *.php or *.js;
2. Scroll down until it stops scrolling;

Whenever you scroll down a source-code file, it will just stop scrolling when the last line of code (or text) reaches the very top of the text-editor window. It's also possible to scroll down the file, even if file content is smaller than window height!

If file content is longer than window height, at end it makes user see a big empty space in the editor between the last code line and the bottom of editor window, as if we just had only one line of code.

**Comment by isidorn** [comment]
Do you also see this issue when you start vscode with `--disable-extensions`
