### ISSUE TITLE
Couldn't find a debug adapter descriptor for debug type 'msedge' (extension might have failed to activate)

### ISSUE THREAD

**Issue by IvoLeist** [microsoft/vscode#135551]
When using the Remote Development feature of vscode
I get the following error message when trying to launch Edge (on my local system) via Run and debug.

> Couldn't find a debug adapter descriptor for debug type 'msedge' (extension might have failed to activate)

Without using the remote Development feature it is working as intended.
In the past (do not remember which vscode version) this was working without any issues.

Does this issue occur when all extensions are disabled?: Yes/No
-> Not tested yet

- VS Code Version:  1.61.2
- OS Version: Linux x64 5.4.150-1-MANJARO

Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:58:13.605Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.150-1-MANJARO

Steps to Reproduce:

launch.json
 ```
{
            "type": "edge",
            "request": "launch",
            "name": "Launch Edge",
            "runtimeExecutable": "/usr/bin/microsoft-edge-beta",
            "urlFilter":"http://remote-ip:4000/",
            "port": 2015,
            "webRoot": "${workspaceFolder}/client",
            "trace": true,
            "sourceMaps": true,
            "userDataDir": "${workspaceFolder}/.vscode/edge",
            "sourceMapPathOverrides": {
                 "webpack:///./src/*": "${workspaceFolder}/client/src/*"
      },
            "skipFiles": [
                "<node_internals>/",
                "${workspaceFolder}/client/node_modules//*.js",
            ],
}

```
1. Connect via vscode to remote PC
2. Run there via vscode the React client
3. Try to start the debugger (via Run and debug) 

Please let me know if you need further information.

**Comment by IvoLeist** [comment]
Do not want to reopen that issue, just for the ones stumbling about it.
If I understood it correctly it is a clash between JavaScript Debugger (https://github.com/microsoft/vscode-js-debug)
and debugger for Microsoft Edge (https://github.com/Microsoft/vscode-edge-debug2)

If I disable the JavaScript debugger globally and now try to start the debugger with the launch.json in the initial post
everything works as intended :)

**Comment by weinand** [comment]
@connor4312 are you aware of this clash?

**Comment by connor4312** [comment]
Yea, we both register the `msedge` debug type. Vscode-edge-debug2 is [deprecated](https://github.com/Microsoft/vscode-edge-debug2#rotating_light-important) and should generally no longer be used except if needed to debug IE or legacy Edge.

**Comment by IvoLeist** [comment]
Interesting to know but why does then the launch.json below not work when using vscode remote?

```
{
      "name": "pwa-msedge",
      "request": "launch",
      "type": "pwa-msedge",
      "runtimeExecutable": "/usr/bin/microsoft-edge-beta",
      "url": "http://localhost:3000/*",
      "port": 9222,
      "trace": true,
      "webRoot": "${workspaceFolder}/client/src",
      "sourceMaps": true,
      "sourceMapPathOverrides": {
        "webpack:///./src/*": "${workspaceFolder}/client/src/*"
      },
      "skipFiles": [
        "<node_internals>/**",
        "${workspaceFolder}/client/node_modules/**/*.js"
      ]
    },
```

It runs remotely always into:

> Could not connect to debug target at http://localhost:9222: Cancelled GET http://localhost:9222/json/version

Non-remote everything works as expected.
Therefore, my current workaround for that issue is to use vscode-edge-debug2
