### ISSUE TITLE
Enable "blockCommentCommand" to comment out the first and last characters of the lines in the selected range

### ISSUE THREAD

**Issue by koshieguchi** [microsoft/vscode#135532]
Issue Type: **Feature Request**

![download](https://user-images.githubusercontent.com/55349055/138230516-8ffd4115-5d92-4763-ace8-a00befe3189e.gif)

``blockCommentCommand`` comments out the selected range with the cursor, but it doesn't comment out the first and last characters of the lines in the selected range, so the characters are sometimes broken in the middle. So we need a new feature that comments out the first character of the first line to the last character of the last line in the selected range even if we select it from the middle of a sentence.
(If we use ``lineCommentCommand`` instead, we cannot fold the selected range of the code so it would be nice to have this feature.)

**Comment by gjsjohnmurray** [comment]
@koshieguchi but suppose I intentionally selected only part of the first and/or last line of the block that I want to comment out?

Also, if you display line numbers then you can click on the line number of the first line in the block you want to comment out, then shift-click on the line number of the last line.
