### ISSUE TITLE
onDidChangeActiveTerminal can fire wrongly multiple times

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#135575]
Report:

1. Add `vscode.window.onDidChangeActiveTerminal(() => console.log('change terminal'))`
1. Create a new terminal, or change between terminals
1. Notice the event is fired twice

It also seems like closing a terminal triggers this three times (each with the same terminal):

```
change terminal: bash (57140)
change terminal: bash (57140)
change terminal: bash (57140)
close terminal: bash (57299)
```

**Comment by meganrogge** [comment]
think this is fixed bc cannot reproduce

https://user-images.githubusercontent.com/29464607/205999908-e6d0d5ff-bed6-4620-bfcd-3faeda42a001.mov
