### ISSUE TITLE
How to publish platform specific extensions correctly

### ISSUE THREAD

**Issue by actboy168** [microsoft/vscode#135543]
My extension has multiple targets in the same OS, such as win32-ia32 and win32-x64. When I use github actions to build extensions and release them, they cannot be released at the same time (a few minutes apart). 

When I have released the win32-ia32 extension and the win32-x64 extension has not been released yet, a user who should have downloaded the win32-x64 extension will download the win32-ia32 extension by mistake.

How can I avoid this from happening?

**Comment by sandy081** [comment]
How about releasing `win32-x64` first and `win32-ia32` after?

**Comment by isidorn** [comment]
No plans to change this at the moment. Closing for now and we will reopen if we get more user feedback. Thanks
