### ISSUE TITLE
Sorting the tabs in VSCode IDE

### ISSUE THREAD

**Issue by 2kiranns** [microsoft/vscode#135564]
Sorting of tabs in the IDE is a very fundamental requirement. From a usability perspective, no one can remember the order in which files are opened and there should be an option to enable/disable tab sorting. All the IDEs provide this functionality except for VS Code.

There was a ticket raised on the same in Jan 2021 (#113717) but looks like it is closed by bot since there were not enough upvotes. While bots can help, on such fundamental usability requirements which every other IDE provides, why is this development team, first of all, looking for someone to create a ticket and then get enough upvotes? I am only trying to emphasize the importance of this functionality. Request you to consider this on priority without waiting for 60 upvotes.

**Comment by gjsjohnmurray** [comment]
>  without waiting for 60 upvotes

The threshold is **20** upvotes withing 60 days.
