### ISSUE TITLE
bug report about markdown

### ISSUE THREAD

**Issue by bubifengyun** [Microsoft/vscode#13560]
- VSCode Version: 1.6, 1.5.3 64bit
- OS Version: linux deepin 15.3 64bit

I like write markdown files in vscode.  Many files were opened at the same time. But when i click preview current markdown file. It will not preview current one but the last file. I click preview again on current markdown file, then it will preview current markdown file.
It should preview current markdown file everytime in my opinion.
Thank you.

**Comment by gregvanl** [comment]
Pretty frustrating. Duplicate of https://github.com/Microsoft/vscode/issues/12335
