### ISSUE TITLE
No Intellisense for node packages

### ISSUE THREAD

**Issue by royaldark** [Microsoft/vscode#13562]
- VSCode Version: 1.6.0
- OS Version: Windows 10 Build 14393

I followed the [instructions for installing typings](https://code.visualstudio.com/docs/languages/javascript) for Node modules, as well as the [Node.js specific instructions](https://code.visualstudio.com/docs/runtimes/nodejs), but I can't get any Intellisense completions for node modules with installed typings definitions.

**jsonfig.json**
```
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs"
    },
    "exclude": [
        "node_modules"
    ],
    "files": [
        "src/"
    ]
}
```

I ran the following commands:
```
npm install --save lodash
npm install --global typings
typings install dt~lodash --global --save
```

This gives the following folder structure under `typings`:
![typings](https://cloud.githubusercontent.com/assets/1669397/19297568/ece842f0-900b-11e6-9d4c-06d01c26db06.png)

However, in `src/index.js`, no completions are included for Lodash:
![no suggestions](https://cloud.githubusercontent.com/assets/1669397/19297580/feba762e-900b-11e6-89b2-001a29a2d07c.png)

Am I missing something obvious here?

**Comment by waderyan** [comment]
@royaldark thank you for opening this issue. This can be quite a pain. I have personally dealt with a fair amount of angst getting this to work. As an aside we are working on many improvements in this area to roll out hopefully soon. 

You can solve your issue by removing either the `exclude` attribute or the `files` attribute. They cannot both be present at once.

**Comment by royaldark** [comment]
@waderyan Thanks for the tip! While removing `exclude` didn't fix the issue, removing `files` did. Getting my completions now!
