### ISSUE TITLE
VS Code window is blank white under Plasma Wayland

### ISSUE THREAD

**Issue by Maia-Everett** [microsoft/vscode#135696]
Does this issue occur when all extensions are disabled?: Yes

When I launch VS Code under an X11 session, it works correctly. However, launching it under a Wayland session opens a blank white window instead.

- VS Code Version: 1.61.1-1634175470
- OS Version: Kubuntu 21.10
- GPU: NVIDIA GeForce GTX 1060 (proprietary driver 470.74)

Steps to Reproduce:

1. Switch the desktop session to Plasma Wayland. Under Ubuntu, it can be installed via the `plasma-workspace-wayland` package.
2. Launch VS Code.

With the `--disable-gpu` command line option, VS Code launches correctly, but is unacceptably slow.

**Comment by marcelovbcfilho** [comment]
Same issue here with Gnome on Wayland.

 - VS Code Version: 1.62.0
 - OS Version: Fedora 35
 - GPU: NVIDIA GeForce GTX 1080 (proprietary driver 495.44)
![Screenshot from 2021-11-07 22-18-17](https://user-images.githubusercontent.com/51462138/140670197-e6fba0d3-7967-4880-8da5-e0fc908ca9d2.png)

**Comment by deepak1556** [comment]
Does it work when you launch with `--enable-features=UseOzonePlatform --ozone-platform=wayland`

**Comment by marcelovbcfilho** [comment]
> Does it work when you launch with `--enable-features=UseOzonePlatform --ozone-platform=wayland`

Yes with the params that you provided VSCode starts, but without window manager buttons
![Screenshot from 2021-11-08 17-41-56](https://user-images.githubusercontent.com/51462138/140815359-3c63ee1a-178e-4d15-aedc-1d22ba71edbe.png)

**Comment by kon14** [comment]
> Yes with the params that you provided VSCode starts, but without window manager buttons

That's due to Gnome refusing to support SSD on Wayland and Electron lacking support for drawing titlebars with CSD.
Electron should support this eventually, but in the meantime you can just enable VS Code's own titlebar support by adding the following to _settings.json_:

`"window.titleBarStyle": "custom"`

**Comment by marcelovbcfilho** [comment]
Found a similar issue #134255, I think that this could be closed.
The other has many more info and all work around are described there.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/109176
