### ISSUE TITLE
Spelling error in the Go debugger on mac

### ISSUE THREAD

**Issue by pawlh** [microsoft/vscode#135601]
Issue Type: <b>Bug</b>

When debugging a Go application on a Mac, entering an invalid command in the debug console returns the string "Unable to process `evaluate`: debuggee is running" where "debugger" is mistakedly spelled "debuggee"

VS Code version: Code 1.61.1 (Universal) (c13f1abb110fc756f9b3a6f16670df9cd9d4cf63, 2021-10-14T01:23:30.274Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.53GB free)|
|Process Argv|--crash-reporter-id b75c457d-f473-45d1-930c-63fa3e418f1a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-go-syntax|dun|0.0.18
go|gol|0.28.1
vscode-docker|ms-|1.17.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
cpptools|ms-|1.7.0
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis300:30381676
vsaa593cf:30376535
vssld246:30379911

```

</details>

**Comment by connor4312** [comment]
"Debugee" is referring to the program running under the debugger (like "employee" and "employer"). Regardless this is an issue on the Go extension, rather than vscode

/extGo
