### ISSUE TITLE
merge on pull that results in no changes after resolving conflicts won't commit

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/vscode#135652]
Issue Type: <b>Bug</b>

1.  change something locally and commit
2.  someone else changes the same line (but slightly different) and push
3.  you click Sync which indicates conflicts.
4.  you open the file with a conflict and "Accept Current" because of course your code is better ;)
4.  you save and click "Stage Changes" on the conflicted file, which results in no change.
5.  you try to commit but it says there are no changes to commit
6.  git still thinks you're in a merge operation and gives the error "a MERGE_HEAD exists" for many commands
7.  to resolve the merge, you run `git commit -m "complete merge"` at the terminal

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (15.97GB free)|
|Process Argv|--folder-uri file:///c%3A/source/iti/identity-server --crash-reporter-id f98b4540-53af-4472-8651-57333f87f83b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
libman|adr|1.0.1
vscode-eslint|dba|2.2.1
gitlens|eam|11.6.1
EditorConfig|Edi|0.16.4
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|9.0.0
auto-rename-tag|for|0.1.9
dotnet-test-explorer|for|0.7.7
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.24.5
vscode-nuget-package-manager|jmr|1.1.6
react-native-snippet|jun|0.5.6
vscode-jest-test-adapter|kav|0.8.1
vscode-docker|ms-|1.17.0
csharp|ms-|1.23.16
vscode-edge-devtools|ms-|1.3.1
remote-containers|ms-|0.194.3
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
azure-account|ms-|0.9.9
cpptools|ms-|1.7.1
powershell|ms-|2021.10.1
test-adapter-converter|ms-|0.1.3
vsliveshare|ms-|1.0.5027
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.7.1
vetur|oct|0.35.0
vscode-jest|Ort|4.2.1
vscode-nuget-gallery|pat|0.0.24
vscode-coverage-gutters|rya|2.8.2
code-spell-checker|str|2.0.10
es6-string-html|Tob|2.11.0
vscode-icons|vsc|11.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis400:30381677
vsaa593:30376534
vssld246cf:30379912

```

</details>

**Comment by lszomoru** [comment]
@burtonrodman, apologies for not getting back to you on this until now. Over the last several months we have made some improvements in this area and I believe that as part of that work this scenario was also addressed. I will go ahead and optimistically close this issue, but in case you are still able to reproduce the problem please feel free to reopen this issue so that I investigate this further. Thanks!
