### ISSUE TITLE
Unable to View or Install Extensions

### ISSUE THREAD

**Issue by TylorS** [Microsoft/vscode#13561]
- VSCode Version:
  - v1.6.0 stable
  - v.1.7.0 insider
- OS Version:
  - Ubuntu 16.04

Steps to Reproduce:
1. Open Visual Studio Code
2. Click Extensions tab on left-hand side or press ctrl+shift+x

An error appears across the top

``` sh
# exact error from vscode 1.7.0 insider
connect ENOENT /tmp/tylor/Code - Insiders-dbef50-1.7.0-insider-shared.sock
```

virtually the same exact error, only different file name, occurs in v1.6.0 stable.

After doing a tiny bit of investigating, it seems this file is being created at `/tmp` and _not_ `/tmp/tylor` (where tylor is my username), which is not consistent with versions previous to v1.6.0, where there seem to be many `.sock` files located in my `/tmp/tylor` folder.

``` sh
ls -la /tmp | grep Code
drwx------  2 tylor tylor  4096 Oct 10 14:41 VSCode Crashes
srwxrwxr-x  1 tylor tylor     0 Oct 12 00:02 Code - Insiders-dbef50-1.6.0-insider-shared.sock
srwxrwxr-x  1 tylor tylor     0 Oct 12 00:03 Code - Insiders-dbef50-1.7.0-insider-shared.sock
srwxrwxr-x  1 tylor tylor     0 Oct 12 00:03 Code - Insiders-dbef50-1.7.0-insider.sock
srwxrwxr-x  1 tylor tylor     0 Oct 11 23:43 Code-dbef50-1.5.3-shared.sock
srwxrwxr-x  1 tylor tylor     0 Oct 12 00:12 Code-dbef50-1.6.0-shared.sock
srwxrwxr-x  1 tylor tylor     0 Oct 12 00:12 Code-dbef50-1.6.0.sock


ls -la /tmp/tylor
total 40
drwx------  6 tylor tylor  4096 Oct 12 00:15 .
drwxrwxrwt 18 root  root  20480 Oct 12 00:12 ..
drwxrwxr-x  3 tylor tylor  4096 Oct 11 23:29 npm-12071-4dc52ad8
drwxrwxr-x  3 tylor tylor  4096 Oct 11 23:41 npm-13633-0035ceb9
drwxrwxr-x  3 tylor tylor  4096 Oct 11 22:23 npm-6428-edb6f29f
drwxrwxr-x  3 tylor tylor  4096 Oct 11 22:39 npm-7499-fd441190
srwxrwxr-x  1 tylor tylor     0 Oct 12 00:02 vscode-0034836885a5d6c647a5f096cf39f0fca56fa745.sock
srwxrwxr-x  1 tylor tylor     0 Oct 11 23:55 vscode-06b467bc5f4aa27ca69e588b3a24d0bbf486ff85.sock
srwxrwxr-x  1 tylor tylor     0 Oct 12 00:03 vscode-21a443416bb962d7562c0c42e212316c65a4c6c6.sock
srwxrwxr-x  1 tylor tylor     0 Oct 10 16:04 vscode-24f8d58c4be4ae1966dd0da358a0b4a0f304564f.sock
srwxrwxr-x  1 tylor tylor     0 Oct 10 19:05 vscode-37b3958f2dd770a8e6168208ee73a88a02c76557.sock
srwxrwxr-x  1 tylor tylor     0 Oct 12 00:02 vscode-42212eeb579351206136b342b2fdbbe1892954bd.sock
srwxrwxr-x  1 tylor tylor     0 Oct 10 19:12 vscode-461eb8e95e6fe54cdd41df6d95766dbbba3d55f2.sock
srwxrwxr-x  1 tylor tylor     0 Oct 12 00:12 vscode-4d4b611d9276974e1a1e03c42a233163f0656311.sock
srwxrwxr-x  1 tylor tylor     0 Oct 12 00:03 vscode-6d9dacf651f7e6096922769b2bac7eebb5b63a62.sock
srwxrwxr-x  1 tylor tylor     0 Oct 12 00:06 vscode-776e6eb3618ebc6edb1a6edcd86d21661df69a71.sock
srwxrwxr-x  1 tylor tylor     0 Oct 11 23:55 vscode-99b861b5516595663bf64ee7cc024baa0b94d616.sock
srwxrwxr-x  1 tylor tylor     0 Oct 10 16:04 vscode-a78362506d68646b6666e488629ad58c968d8254.sock
srwxrwxr-x  1 tylor tylor     0 Oct 10 19:12 vscode-b5cb330bc35996e9674feb601d2dfc966974245f.sock
srwxrwxr-x  1 tylor tylor     0 Oct 10 19:05 vscode-c4051632746dc328267c6a677360ac7cb6e64be0.sock
srwxrwxr-x  1 tylor tylor     0 Oct 10 14:41 vscode-d3c939996fb90cce07f69734359b140c55314c96.sock
srwxrwxr-x  1 tylor tylor     0 Oct 10 14:41 vscode-ed31d2c69aa720c6f7565d0c16472150315b6f02.sock

```

Here's a screenshot of the error in v1.7.0 insider

![image](https://cloud.githubusercontent.com/assets/6282473/19297185/5d44072e-9010-11e6-8310-ef9074b9e1c4.png)

**Comment by joaomoreno** [comment]
@TylorS If you get 1.5.0 ([ia32](https://az764295.vo.msecnd.net/stable/5be4091987a98e3870d89d630eb87be6d9bafd27/code-stable-code_1.5.3-1474534134_i386.tar.gz), [x64](https://az764295.vo.msecnd.net/stable/5be4091987a98e3870d89d630eb87be6d9bafd27/code-stable-code_1.5.3-1474533365_amd64.tar.gz)), does it _still_ work fine?

What's the value of ` echo $TMPDIR` when running from a shell? Does this value change due to one of your `.bashrc` (or similar) scripts?

**Comment by TylorS** [comment]
Hi @joaomoreno thanks for the quick response.

Yes, 1.5.0 has continued to work for me.

![image](https://cloud.githubusercontent.com/assets/6282473/19302563/9b0b6f76-9032-11e6-9e23-dd9898b5406a.png)

```sh
~ ❯❯❯ echo $TMPDIR
/tmp/tylor
```

I do not have any scripts that touch the value of $TMPDIR, didn't even know it existed until now. 

Literally the only commands I have in my `.zshrc` 
```sh
export PATH=./node_modules/.bin/:$PATH

export NVM_DIR="/home/tylor/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
```

**Comment by joaomoreno** [comment]
Let's do something in both versions:

1. Open the developer tools (<kbd>F1</kbd>, `Developer Tools`)
2. Type `require('os').tmpdir()`

What do you get in both 1.5 and 1.6?

**Comment by joaomoreno** [comment]
@BenMaruchu Can you also try the steps I mentioned in my previous comment?

**Comment by BenMaruchu** [comment]
for `sh echo $TMPDIR `
it returns /tmp/benson

for version 1.6 ` require('os').tmpdir();`
returns "/tmp/benson"

for version 1.5.3 ` require('os').tmpdir();`
returns "/tmp/benson"

**Comment by BenMaruchu** [comment]
version 1.5.3 works fine

**Comment by TylorS** [comment]
Here is version v1.6.0

![image](https://cloud.githubusercontent.com/assets/6282473/19317108/f20e39d6-9071-11e6-9c14-8911696566d4.png)

Here is version v1.5.3

![image](https://cloud.githubusercontent.com/assets/6282473/19317164/1ebc8816-9072-11e6-8f40-63f0792ae9d8.png)

**Comment by TylorS** [comment]
I did a re-installation of my OS and these issues have gone away.

**Comment by joaomoreno** [comment]
Wow, that is odd. You reinstalled your whole OS?

**Comment by TylorS** [comment]
Yeah, I did a fresh install of Ubuntu 16.04.1. 100% of everything I have that is important is on GitHub or Google Drive so it's an easy thing for me to do. 

I still can't explain the errors I was having, because I've never touched the $TMPDIR environment variable.

**Comment by joaomoreno** [comment]
Got it. I will look into it.

**Comment by anuragsoni** [comment]
@joaomoreno Hi. I am getting the same error on Linux Mint 18 (Basically Ubuntu 16.04)
Version of VSCODE: Version 1.7.0-insider

**Comment by junwatu** [comment]
i have the same bug

**Comment by jweg** [comment]
Just ran into the same problem with Version 1.6.1 Commit 9e4e44c19e393803e2b05fe2323cf4ed7e36880e.
I had the line 'export TMPDIR="/tmp/$LOGNAME"' in my .zshrc. After removing the /$LOGNAME, the problem went away. Nothing else ever had a problem with that, though...

**Comment by Mallfurion** [comment]
I can confirm. Had the same problem, removed from (.zprofile for me, maybe others have it in .zshrc) the `/$LOGNAME` from the `export TMPDIR="/tmp/$LOGNAME` line.

**Comment by BenMaruchu** [comment]
Now it works thanks @jweg

**Comment by junwatu** [comment]
Ah yes that trick works for me, thanks @jweg

**Comment by tatsumi33** [comment]
I have the same issue. The error message was shown when VSCode is launched from Ubuntu MATE application menu, but it was launched from MATE Terminal then no error was occurred.

`require('os').tmpdir()` on the developer tools console in both cases and `echo $TMPDIR` on the terminal had same output `/tmp/username`.

Environment:

- Visual Studio Code 1.6.1 ( Commit 9e4e44c19e393803e2b05fe2323cf4ed7e36880e )
- Ubuntu 16.04.1 LTS

**Comment by joaomoreno** [comment]
This was a **great** catch! Thanks for all the tips guys.

Requirements:

- User must have a definition of the `TMPDIR` environment variable in his `.bashrc` or equivalent. The new value must differ from whatever `require('os').tmpdir()` returns.
- Code must be launched by double click or similar, not by running it from a shell.

Description:

The main process was eagerly computing the location for the shared process socket file, thus getting the `tmpdir` location before the new `TMPDIR` value kicked in via the shell env patching.

**Comment by dragosdm** [comment]
any way to fix this on macOS? or time before pushing this to 1.6.2?
I've tried removing /$LOGNAME from $TMPDIR but it's not working.

**Comment by joaomoreno** [comment]
The fix will come out with 1.7.0.

Meanwhile there's this **workaround**:

Run `code` from a shell.

**Comment by trichetriche** [comment]
Hi, 
The same problem seems to appear on version 1.8.1

Running `code` from the shell resolves it, but I just wanted to let you know (fresh install of Ubuntu 16.04.1)

**Comment by ruionwriting** [comment]
The same for 1.9.0-insider.

**Comment by alexedev** [comment]
Same problem in todays update (1.9.0) on sierra 10.12.3
Opening VS from terminal using `code` solves the problem, but...you know:)

**Comment by ibeex** [comment]
Same problem in todays update (1.9.0) on ubuntu 16.10, from shell works from menu don't

**Comment by mingliangguo** [comment]
got the same problem on Mac 10.12.3 with 1.9.0

**Comment by stkevintan** [comment]
same problem in 1.9.0 on Deepin 15.3

**Comment by alexreardon** [comment]
I can confirm that this is occurring on 1.9.0 on Sierra 10.12.3. Starting `code` from the shell gets around the problem

**Comment by joaomoreno** [comment]
@jrieken We might've broken something here.

**Comment by joaomoreno** [comment]
@jrieken Yep, this is now definitely broken. To reproduce:

- Have a `TMPDIR=/something` line in your `.bash_profile` or equivalent

It was broken by removing the user env computation from the startup path. That code was setting the correct `TMPDIR` environment into the main process (and thus into all its children). After that was set, the environment service [computed the shared process ipc handle](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/environment/node/environmentService.ts#L119).

Now, that handle is being computed based on the `TMPDIR` before the user env is discovered.

**Comment by jrieken** [comment]
Wow, crazy... I think we can
1. revert the performance fix 🐌,
2. start the shared process once the env is resolved, or
3. use a different path for the sock-files

My preference would be 2. Objections? Risks?

**Comment by joaomoreno** [comment]
Tricky.

The problem doesn't lie in starting the shared process, but in connecting to it. But I think we can pull it off by delaying the connection to it until we have the right env.

Another issue with the change:

I just noticed that the same happens for the [main process IPC hook](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/environment/node/environmentService.ts#L116) used to detect whether there is another instance of Code running. We might be hitting bugs there, by trying to put IPC hooks in directories that don't exist or the user has no permissions to do so.

**Comment by chrmarti** [comment]
Verified a custom `TMPDIR` is used. It still fails if that folder doesn't exist yet, but I assume that is expected.

**Comment by abimelex** [comment]
Had the same error after some kind of update. Solution was just to simple hit the "restart to update" button in the menu. Just in case somebody else is googling for solution instead of doing the "obvious" ;)

**Comment by chuckb** [comment]
I am having this issue and had a ticket opened, which was auto-closed. See #30624

**Comment by simonsteiner** [comment]
I still have this issue in v1.15.1 on macOS Sierra v10.12.6 when I start VSCode from Finder.

Workaround with starting from terminal via `code` works. I can see plugins then without an error.

**Comment by SkeLLLa** [comment]
@jrieken Same issue in v1.16.1 on Linux.

**Comment by styk-tv** [comment]
Same issue in v1.16.1 on Mac

**Comment by gopalyadav5** [comment]
"http.proxyStrictSSL": false

This user setting worked for me.

**Comment by SkeLLLa** [comment]
Linux also don't have windows registry :). And launching from command-line not helps. So it's definitely a bug of App, not DE or OS.

**Comment by alexeyvax** [comment]
Hy guys, I have updated vscode to v1.16.1 and I have got the same issue, my list of extensions and plugins were disappeared. OS Linux

**Comment by alexeyvax** [comment]
Hi guys, I have updated vscode to v1.16.1 and I have got the same issue, my list of extensions and plugins were disappeared. OS Linux

**Comment by simonsteiner** [comment]
Issue seems to be gone with v1.17.2 on macOS Sierra v10.12.6. It's not reproducible anymore. 🎉
