### ISSUE TITLE
[html] Format document create tab identities

### ISSUE THREAD

**Issue by baio** [Microsoft/vscode#13563]
- VSCode Version:
1.6
- OS Version:
Windows 10
Steps to Reproduce:

1.  Open html file in editor
2.  Ctrl + Alt + F to format

Some lines now have tab identities instead of spaces, though settings have indents using spaces.

**Comment by Maximaximum** [comment]
I'm having this issue too. Seems to apply only to html files.
Please also see the discussion here: https://github.com/editorconfig/editorconfig-vscode/issues/78#issuecomment-253143968

**Comment by Maximaximum** [comment]
Please also note that this issue appeared only after update to VSCode 1.6.0

**Comment by aeschli** [comment]
Can you add a small code example that shows that?
My guess is that this is a the same as in #12978.

**Comment by Maximaximum** [comment]
What kind of code do you need? You mean a sample html file that, when formatted, results with the issue described?

**Comment by SEGEEK** [comment]
This sample code will do it as I demonstrate below (note I have removed all of my extensions), you can see that spaces:2 is set in the status bar but when I format it converts the spaces to a tab

![format-to-tab2](https://cloud.githubusercontent.com/assets/3335010/19314939/806d6c3a-9061-11e6-9ea4-c0cfa4288711.gif)

Here is the code so you can try to reproduce it:
```
<body>
  <div>Should be indented with spaces</div>
</body>
```

**Comment by aeschli** [comment]
Thanks a lot!
