### ISSUE TITLE
vs-icon unable to use, markdown error......I WANT BACK TO OLD VERSION, STOP UPDATING!!!!!!!! ITS REALLY AWAIST OF TIME!!!!!!!!!!!!!!! WTF!!!1

### ISSUE THREAD

**Issue by huanglianghua** [Microsoft/vscode#13564]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:28:55.412Z)
- OS Version: Darwin x64 16.0.0
- Extensions: donjayamanne.python-0.4.1, ms-vscode.PowerShell-0.7.2, ms-vscode.cpptools-0.9.2, ms-vscode.latex-0.1.1, robertohuertasm.vscode-icons-3.0.3, xabikos.JavaScriptSnippets-1.2.0

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Please read our release notes http://code.visualstudio.com/updates
In short, the vscode-icons extensions that you are using is badly modifying the source of VSCode thus you should uninstall it and start using the built in icons in vscode.

Thanks

**Comment by robertohuertasm** [comment]
@huanglianghua please see [this](https://github.com/Microsoft/vscode/issues/13588#issuecomment-254037242). vscode-icons **does not modify any source code** since its version 3.0.0.

**Comment by isidorn** [comment]
@robertohuertasm thanks for pointing this out, was unware of the new version - my appologies.

**Comment by huanglianghua** [comment]
Thanks for your reply, I have worked it out, and the new way of styling icons is convenient. 

Select 
Menu - Preference - File Icon Themes 
and choose the favorite theme among the options.

BTW, apologize for the rudeness. = =
