### ISSUE TITLE
Support auto save when delay is 0ms

### ISSUE THREAD

**Issue by przemolb** [microsoft/vscode#135635]
Issue Type: <b>Bug</b>

Hello,

I always setup VSC to immediately save to disk any modifications of any file

```
grep -i save .config/Code/User/settings.json 
    "files.autoSaveDelay": 0,
    "files.autoSave": "afterDelay"
```

But it looks like my autoSave settings doesn't work anymore and whenever I change anything in a file the change is not immediately saved and I need to press CTRL-S.
It used to work very well before.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:58:13.605Z)
OS version: Linux x64 5.4.0-87-generic
Restricted Mode: No

**Comment by przemolb** [comment]
What would negative numbers mean in this particular case ?

**Comment by bpasero** [comment]
Setting now supports a value of `0` but not below.
