### ISSUE TITLE
Ctrl+Alt+ keybindings should not be used

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#13567]
- VSCode Version:

![2016-10-12_08h51_04](https://cloud.githubusercontent.com/assets/3082812/19298797/154db85e-9059-11e6-85da-7cd8e4276cff.png)

- OS Version: win7 pro

Steps to Reproduce:

1. open VSCode

Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  41009  for  workbench.action.files.saveAll

![2016-10-12_08h51_20](https://cloud.githubusercontent.com/assets/3082812/19298810/29242d4a-9059-11e6-9157-519f22887ce1.png)

**Comment by chrmarti** [comment]
Thanks @bpasero !
