### ISSUE TITLE
about git

### ISSUE THREAD

**Issue by xhonker** [Microsoft/vscode#13569]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14936
- Extensions: azemoh.theme-onedark-0.3.1, christian-kohler.npm-intellisense-0.1.3, christian-kohler.path-intellisense-1.0.2, donjayamanne.jquerysnippets-0.0.1, ecmel.vscode-html-css-0.0.27, humao.rest-client-0.8.4, msjsdiag.debugger-for-chrome-1.1.0, nicolasalcaraz.cssclasshint-0.0.3, SirTori.indenticator-0.2.1, wcwhitehead.bootstrap-3-snippets-0.0.7

Steps to Reproduce:

1.git unavailable
2.Last version Can use
3.Prompt By exit code 1 termination Theterminal process

**Comment by joaomoreno** [comment]
Can you provide a screenshot?

**Comment by xhonker** [comment]
![qq 20161012174519](https://cloud.githubusercontent.com/assets/20201169/19305510/d297fede-90a3-11e6-9a3a-4b61946438e2.png)
Shortcut key ctrl+`  
Open terminal At the time of

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the full window?

**Comment by xhonker** [comment]
![qq 20161013142808](https://cloud.githubusercontent.com/assets/20201169/19338715/5b8f6c4c-9151-11e6-9f3e-356180eac9df.png)

**Comment by joaomoreno** [comment]
Git seems to be available, if you click in git view you can see the changes, right?

@rebornix What does the error message say exactly?

**Comment by xhonker** [comment]
ctrl+`  Open this Appeared   
Could not use the terminal

**Comment by xhonker** [comment]
New folder Also 
git Is able to submit  ，but Can open the terminal before

**Comment by xhonker** [comment]
I think there is a problem
Don't know other people are like this

**Comment by joaomoreno** [comment]
@Tyriar take a look

**Comment by Tyriar** [comment]
This was a long standing issue that was actually fixed yesterday by a community contribution :tada: https://github.com/Microsoft/vscode/issues/7727
