### ISSUE TITLE
rename label `uiTheme` for future workbench theme

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#13565]
In current version, we can only modify `editor(syntax)` theme.
But related #3112, it more fancy to customize the whole workbench.
Now we use `uiTheme` labeled `editor(syntax)` theme.

So, I suggest use **`editorTheme`** or **`syntaxTheme`** for current **`uiTheme`**.
And left **`uiTheme`** for workbench.

**Comment by aeschli** [comment]
The current thinking is to expand the editor color themes to also contain workbench colors.
'uiTheme' which describes the base theme would still be needed to e.g. describe the icon theme.

Closing as dup of #3112
