### ISSUE TITLE
Backslash at end of comment messes up syntax highlight

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#13568]
If a single line comment is ended with a backslash (last non-whitespace character) it is mysteriously syntax highlighted. 

A multiline comment that directly follows is also affected.

![comment_backslash](https://cloud.githubusercontent.com/assets/1297882/19300655/b94a7580-905b-11e6-8b9e-758ab4abd4ab.gif)

**Comment by aeschli** [comment]
@csholmq For what language is that?

**Comment by csholmq** [comment]
@aeschli Sorry, forgot to mention. It's C.

**Comment by aeschli** [comment]
What you see is intended:
A backslash at the end of the line removes following the new line character (merges the two lines).
So '/*' is now also part of the first line and part of the single line comment.
See
http://lessonsincoding.blogspot.ch/2012/03/backslash-line-splicing-in-c-c.html

**Comment by csholmq** [comment]
@aeschli Yes, quite right :) But shouldn't a whitespace following the backslash effectively "protect" the newline character?

**Comment by aeschli** [comment]
Oh, now I see. Sorry.

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#175
