### ISSUE TITLE
The Keyboard focus moves out of the Pop up on pressing Tab.

### ISSUE THREAD

**Issue by v-gitsay** [microsoft/vscode#135636]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#VisualStudioCode-Win32-Apr2021;#Visual Studio Code Client;#DesktopApp;#WCAG2.4.3;#AINotInScope;#FTP;#FocusOrder;#Keyboard;

### Environment Details:
Screen Reader: NVDA/JAWS
Operating system: Windows 10

### Repro Steps:

1. Launch VS Code application.
2. Tab till "Azure" and press enter.
3. Tab till "app service " dropdown and press enter.
4. Tab till "Files" dropdown and press enter.
5. Tab to any file and press enter.
6. Edit by adding "make changes" and save(ctrl + S) the "SRC" file..
7. Tab till the Pop up Saving "hostingstart.html".
8. Check if the keyboard focus moves out of the Pop up on pressing Tab.

### Actual:
The Keyboard focus moves out of the Pop up on pressing Tab.

Note: This issue is observed with all the Notification Pop up that appear for "Initializing SSH" Pop up scenario.

### Expected:
The Keyboard focus should remain in the Pop up on pressing Tab.

### User Impact:
Keyboard users will be confused if the keyboard focus moves out of the Pop up on pressing Tab key.

**Please find the below attachment for reference:**
![134297964-74742e25-70df-4dde-9a8b-3e1e5ffe73c3](https://user-images.githubusercontent.com/86710911/138439756-ff10dd1f-f5c9-4251-83e2-8fd7264558f6.gif)

**Comment by isidorn** [comment]
@v-gitsay The upper right toolbar in the notifications is following best examples of aria toolbar https://www.w3.org/TR/wai-aria-practices/examples/toolbar/toolbar.html
Which means that the toolbar is only one tab stop, it should not be multiple tab stops as that would make the navigation harder for the user. You should use left / right to navigate inside a tooblar.

Everything is behaving as designed here, thus closing this issue and we have heard positive feedback from users regarding this. Thanks
