### ISSUE TITLE
Typing lag when using tsc watch

### ISSUE THREAD

**Issue by eetee** [Microsoft/vscode#13573]
- VSCode Version: 1.6.0
- OS Version: Windows 10
- TypeScript Version:  2.0.3 

I'm not sure whether or not to post this in Typescript repo or this one. 

I am getting quite bad typing lag when I've got my tsc transpile task running. The extent of the lag is if I type "hello world" it takes me about 2secs to finish the keystrokes but only fully on the screen after 7-8 seconds. 

I've tried the same with Atom and the atom-typescript plugin which does not have the same issue, I'm not sure what they're using under the hood to do the watch and transpile. I am very happy to debug and provide further diagnostics but not sure what the best way forward is.

I also use the vim extension, but have got the same result with all extensions removed. The typing lag only happens if I initiate the Task > tsc.

Project size: around 200 files (.ts + .js)

tasks.json:

``` json
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "0.1.0",
  "command": "tsc",
  "isShellCommand": true,
  "args": ["--watch", "--project", "./app"],
  "showOutput": "silent",
  "isWatching": true,
  "problemMatcher": "$tsc-watch"
}

```

tsconfig.json:

``` json
{
  "version": "2.0.0",
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "isolatedModules": false,
    "jsx": "react",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "noLib": false,
    "preserveConstEnums": true,
    "suppressImplicitAnyIndexErrors": true,
    "watch": true
  },
  "include": [
    "./**/*.ts",
    "./**/*.tsx"
  ],
  "exclude": [
    "!./node_modules/**/*",
    "!./.sass-cache/**/*",
    "!./.vscode/**/*",
    "!./logs/**/*",
    "!./public/dist/**/*",
    "!./public/lib/**/*"
  ]
}
```

**Comment by dbaeumer** [comment]
@eetee are you able to share your project. That would be the easiest to track this down. If not could you do the following:

- Help > Toggle Developer tools
- In the Dev tools select Profiles
- Take a JS CPU Profile
- Do your typings...
- Attach the profile here.

**Comment by eetee** [comment]
Sorry unable to share the project.

The typing lag didn't happen when I opened the project and started to do some typings. Thinking back it's entirely possible that it happens after a period of having the editor open. 
Would it be best if I proceed with something like the investigation steps in #4114? i.e. take the heap snapshots and then also the profile when it starts lagging?

**Comment by dbaeumer** [comment]
@eetee yes, that would be perfect.

**Comment by dbaeumer** [comment]
Without the additional information we can't work on this issue. Please ping when the information is available and we will reopen the issue.
