### ISSUE TITLE
HTML add img:src Emmet alias

### ISSUE THREAD

**Issue by NeboCode** [microsoft/vscode#135725]
Hello,

I would like to propose a tiny QoL tweak to Emmet. 

I write a lot of HTML and I type quite fast. so a lot of times I find myself writing `img:src` and pressing enter, thinking Emmet would generate an `<img src="">` however, it instead generates `<img:src></img:src>` which is not a valid HTML tag and I don't think that's used in any syntax.

I am aware that `img:s` does what I want, however, the `s` is quite ambigous. .. s.. `style`, `sizes`, `srcmap`, `src`.. multiple attributes exist for `img` tag and my mind just doesn't connect the letter `s` with `src`.

I've been writing a large project and I use the `img` tag a lot, but I keep forgetting that it's `s` and not `src`..
I always think "Oh, I need an image with a source of ___" and then I just type `img:src` and end up with `<img:src></img:src>`...

So my feature request is,
Would it be possible to add an alias for `img:s`  ˙which would be `img:src` ?

It would certainly make my development in VSC much smoother (since, I swear I have generated at least 40 `img:src` thus far) and I think some other people run into this tiny issue.

I understand I could make a custom snippet for it, but currently, `img:src` is not used as an alias for anything and I believe it should be an built-in alias of `img:s` and not something I have to manually created on all my development machines.

**Comment by rzhao271** [comment]
Actually, take a look at https://code.visualstudio.com/docs/editor/emmet#_using-custom-emmet-snippets because custom snippets should be able to resolve this issue.
Feel free to comment if there's more to the feature request, though.
