### ISSUE TITLE
Webview not working in explorer view

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode#135783]
Version: 1.61.2
OS: Darwin x64 20.6.0

I'm using a Webview which is placed in the explorer view.
The same WebView (a different instance, of course) is also placed in the debug view.
The html and the js-code files are exactly the same for both.
Yet, the js-code file is found/loaded only in the debug view and not in the explorer view.

Here the error from the developer tools:
![Bildschirmfoto 2021-10-25 um 17 49 44](https://user-images.githubusercontent.com/3081973/138728543-5c6b7892-ec7f-4ef5-9ec1-925d1eb53407.jpg)
I checked the path and it exists.

The explorer view with the error looks like this (because the view is not filled correctly by the js-code):
![Bildschirmfoto 2021-10-25 um 17 51 14](https://user-images.githubusercontent.com/3081973/138728760-53762053-6504-4cea-961d-7176296d4c94.jpg)

Whereas the debug view works correctly (and loads the js-file):
![Bildschirmfoto 2021-10-25 um 17 53 27](https://user-images.githubusercontent.com/3081973/138729116-1604784b-ce6a-403a-84c4-9dbb6edff741.jpg)
This also loads the css correctly. Therefore one button is yellow.

What is the difference between a Webview inside the explorer view and a Webview inside the debug view?
Is it maybe something about access rights?

If you would like to try yourself, here is the link to the extension:
https://marketplace.visualstudio.com/items?itemName=maziac.asm-code-lens

**Comment by mjbvz** [comment]
Ok closing this as not-reproducible based on the comments
