### ISSUE TITLE
Simple file dialog shows windows path with lowercase drive letter from POSIX system

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#135762]
When you connect to Windows from a POSIX operating system (I am on macOS) and use the simple file dialog, paths appear with lowercase drive letter, when I would expect uppercase. I wonder if we are not properly using the remote label provider for paths in that case. 

![image](https://user-images.githubusercontent.com/900690/138670509-3ac8f626-fa5e-4497-99a8-72ff1bef7f17.png)

//cc @isidorn

**Comment by isidorn** [comment]
cc @JacksonKearl for label service
