### ISSUE TITLE
JS: Can't search function symbol when set as property of an object

### ISSUE THREAD

**Issue by irvinhg** [Microsoft/vscode#13574]
- VSCode Version: 1.6
- OS Version: Reproduced in Windows 8.1 / 7

Steps to Reproduce:

1.  Open a `.js` file and add the following:

```
var foo = {
    bar: function barBar () {}
};
```
2. Do a symbol search `ctrl + shift + o` . `bar`  or `barBar` are not listed.

**Comment by waderyan** [comment]
@irvinhg thank you for opening this issue. This is a valid request and one that is dependent on the JavaScript language service. Moving this issue to that repo.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11625
