### ISSUE TITLE
engines.vscode does not accept ranges

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#13572]
- VSCode Version: 1.6
- OS Version: macOS Sierra

Steps to Reproduce:

1. In your extension, set `engines.vscode` to something like `>=1.6`
2. Run the extension
3. An error is shown with the message ``Could not parse `engines.vscode` value >=1.6. Please use, for example: ^0.10.0, ^1.2.3, etc.``

So currently, because my extension uses the new `onWillSaveTextDocument` API, it should only be installable from versions higher then `1.6.x`. This is possible with `^1.6.0` as the carret indicates minor updates as well. BUT, what if VS Code (some day) hits `2.0.0`. Does this mean all breaking changes and thus no extension will work anymore. OR, some breaking changes and most of the extensions still work. This would mean that if `vscode.engines` is set to `^1.6.0`, it will not be available in `vscode@2.0.0` and above.

FYI @joaomoreno

**Comment by joaomoreno** [comment]
Code needs a way to break API. And going `2.0.0` is that way. If and when that happens, everyone will require manual adoption. That's the whole point of semver.

**Comment by SamVerschueren** [comment]
Fair point, thanks for clarifying :)!
