### ISSUE TITLE
VSCode installation has 2 node-debug folders

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#13579]
- VSCode Version: 1.6.0
- OS Version: Windows 10

Updated VS Code form 1.5.3 to 1.6 and detected two node-debug folders:

![capture](https://cloud.githubusercontent.com/assets/1931590/19303167/ecfb189c-9067-11e6-9908-66d38f48f0ec.png)

**Comment by weinand** [comment]
@dbaeumer please see release notes ;-)
![2016-10-12_11-49-00](https://cloud.githubusercontent.com/assets/1898161/19305594/eeab768c-9071-11e6-8e1b-0eaf1bb32cc3.png)

**Comment by weinand** [comment]
@roblourens it would have been less confusing if the name of the folder would be `ms-vscode.node2-debug`.

**Comment by dbaeumer** [comment]
Agree with Andres suggestion

**Comment by roblourens** [comment]
It's not too late to change, I guess, if people are looking at the extension IDs. It would look like a new extension to the marketplace, but since it's builtin, we can add a new one and unpublish the old one.
