### ISSUE TITLE
require statement in typescript gets syntax error sometimes

### ISSUE THREAD

**Issue by m3l7** [Microsoft/vscode#13576]
- VSCode Version: 1.6
- OS Version: fedora23

if I have this one line file:

```
  let mosca = require("mosca");
```

the syntax check says: "[ts] Cannot find name 'require'". However, if I add an import line:

```
  import * as express from "express";
  let mosca = require("mosca");
```

I get no errors. Of course the file compiles correctly using directly tsc or a task.

**Comment by waderyan** [comment]
@m3l7 thank you for opening this issue. Can you share more about your workspace? I cannot create this on my own. For example, what is in your `tsconfig.json` file?

**Comment by m3l7** [comment]
this is related to #13514 . Setting outDir the same as include results in this issue
