### ISSUE TITLE
[markdown] Tabbing when writing a word replaces it with an HTML element

### ISSUE THREAD

**Issue by Elarcis** [Microsoft/vscode#13578]
- VSCode Version: 1.6.0
- OS Version: Windows 7

Steps to Reproduce:
1.  Create a mardown file.
2.  Type a word, like `test`
3. Press `TAB`. It replaces `test` with `<test></test>`. Why so?

**Comment by mjbvz** [comment]
This seems to be coming from emmet. After disabling `emmet.triggerExpansionOnTab`, I no longer see this completion.

**Comment by mjbvz** [comment]
Ok, I believe a workaround is to add the setting:

```json
"emmet.excludeLanguages": ["markdown"]
```

This is that triggered for markdown files in the first place because the parent syntax of a markdown document is `html`. Since you can have any html content inside of markdown files, I believe this behavior is intended.
