### ISSUE TITLE
workspace with java projects not being detected until a file is opened

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/vscode#135789]
Issue Type: <b>Bug</b>

Create a folder, cd into the folder and open vscode insider in the folder.

Create 2 new Java projects, using maven inside the workspace folder. 
Make sure to add each project to the workspace at the end.
Close all editors, then close vscode.
Now reopen vscode from the workspace folder.

Notice workspace in not detected as a Java project, until you open one of the java files in one of the projects.

Here is a video showing the problem: https://www.youtube.com/watch?v=xEGxgIYltng

VS Code version: Code - Insiders 1.62.0-insider (34eeebdd66033633ac22efd5fab928ae37916168, 2021-10-15T05:15:40.814Z)
OS version: Linux x64 5.14.11-2-default
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 4199)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.71GB (51.51GB free)|
|Process Argv|. --crash-reporter-id 210d9130-10f4-4cf9-ad76-187d60112fd6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/default|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (72)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.2
vscode-base64|ada|0.1.0
vscode-tomcat|ada|0.11.3
markdown-navigation|Ala|1.0.3
Bookmarks|ale|13.2.2
aws-toolkit-vscode|ama|1.32.0
ng-template|Ang|12.2.2
vscode-apollo|apo|1.19.7
vscode-browser-preview|auc|0.7.2
vscode-tailwindcss|bra|0.7.1
dep|car|0.1.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.44.4
vscode-eslint|dba|2.2.2
java-decompiler|dgi|0.0.2
java-debug|DSn|0.0.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
vscode-lombok|Gab|1.0.1
terraform|has|2.16.0
haskell|has|1.7.1
markdown-preview-bitbucket|hbr|1.0.0
java-properties|ith|0.0.2
vscode-peacock|joh|3.10.1
solidity|Jua|0.0.134
language-haskell|jus|3.4.0
sort-typescript-imports|mic|1.4.1
vscode-docker|ms-|1.17.0
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.2
jupyter|ms-|2021.10.1001380329
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
cpptools|ms-|1.7.1
vscode-typescript-tslint-plugin|ms-|1.3.3
angular2-inline|nat|0.0.17
vetur|oct|0.35.0
vscode-boot-dev-pack|Piv|0.1.0
vscode-manifest-yaml|Piv|1.28.0
vscode-spring-boot|Piv|1.28.0
platformio-ide|pla|2.3.4
java-ide-pack|pve|1.2.1
vscode-thunder-client|ran|1.9.1
fabric8-analytics|red|0.3.4
java|red|1.0.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|1.0.0
vue-vscode-snippets|sdr|2.2.1
markdown-preview-enhanced|shd|0.6.1
vscode-checkstyle|she|1.4.1
java-generate-setters-getters|soh|7.4.0
sonarlint-vscode|Son|3.0.0
sass-indented|syl|1.8.18
language-stylus|sys|1.13.0
serverless-ide-vscode|Thr|0.5.32
find-then-jump|tra|2.0.5
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.7.0
better-align|wwm|1.1.6
vscode-java-saber|You|0.1.2
markdown-pdf|yza|1.4.4
vscode-aspell|zap|0.1.4

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30382699
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsaa593cf:30376535
vscrecpromptt3:30387009

```

</details>

**Comment by JacksonKearl** [comment]
We made some changes here recently that I believe should address this, can you check if this is working in the latest Insiders?
