### ISSUE TITLE
Issue with file extension when saving XML files

### ISSUE THREAD

**Issue by fedor333** [Microsoft/vscode#13577]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: DotJoshJohnson.xml-1.6.0

Steps to Reproduce:

1. Create a new file
2. Change the language to XML
3. Save the file as, with a type of XML
4. Navigate to the file in explorer
5. The extension of the file is actually ASCX and not XML

If you open an existing file with the XML extension and save the file then there is no issue, this only seems to be a problem with new files.

**Comment by sandy081** [comment]
Removing the verification tag as it needs to be verified on Windows too
