### ISSUE TITLE
[PWA] Add an offline fallback for index.html

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#135781]
To hit the [PWA install criteria](https://web.dev/install-criteria/), all VS Code is missing is a SW that handles index.html. When we check that off, Edge and Chrome will show the "Install" banner.

As making all of vscode.dev offline capable is a bigger item, an intermediate step is serving an offline fallback from a SW for index.html. More details in https://web.dev/offline-fallback-page/

@mattbierner, as on origin can only have one SW attached, will this have to integrate with the existing [webview/browser/pre/service-worker.js](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/webview/browser/pre/service-worker.js)? I know github.dev had SW issues in Firefox but could not get Chrome to load a SW so don't fully understand when it is initialized.

cc @bamurtaugh @bpasero

**Comment by joaomoreno** [comment]
Good to close!
