### ISSUE TITLE
Odd keybindings

### ISSUE THREAD

**Issue by benkaiser** [Microsoft/vscode#1357]
I currently have these in my user `keybindings.json`:

```
[
	{ "key": "ctrl+down", "command": "editor.action.moveLinesDownAction",
                             "when": "editorTextFocus" },
	{ "key": "ctrl+up",   "command": "editor.action.moveLinesUpAction",
                             "when": "editorTextFocus" }
    { "key": "ctrl+i",    "command": "expandLineSelection",
                             "when": "editorTextFocus" },
]
```

ctrl+up and ctrl+down are standard are used in [atom](https://github.com/nwinkler/atom-keyboard-shortcuts#editing) (similar product to vscode) and used as ctrl+shift+up and ctrl+shift+down in sublime text. Any chance these can at least be bound to something?

Also regarding ctrl+l, it is the default for selecting a line in atom editor as well as sublime text. Could this be changed from ctrl+i to match this?

**Comment by ctlajoie** [comment]
Another one is ctrl+d, which is "duplicate line/selection" in Sublime Text, Notepad++ and SciTE. As far as I can tell, Code doesn't even have a command for this so I can't add a keybinding. It's been a little difficult to adapt.

**Comment by benkaiser** [comment]
Ctrl+D makes sense for its current use (multiple selection, same as atom).

But yeah its common that the commands just aren't there. Did you check the list of available commands underneath the default keybindings?

**Comment by alexandrudima** [comment]
@benkaiser We kept `ctrl+up/down` intentionally free, with the December update `ctrl+up/down` do scroll line up/down. Please see https://code.visualstudio.com/docs/customization/keybindings
