### ISSUE TITLE
No debug output: Unsupported protocol "vscode-file:"

### ISSUE THREAD

**Issue by MaxGyver83** [microsoft/vscode#135724]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-20T00:21:59.656Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-38-generic
- OS Version: Ubuntu 20.04

I tried debugging VS Code itself. But I don't get any output in the debug console. Only this error:

```
Could not read source map for vscode-file://vscode-app/home/max/repos/vscode/out/vs/base/browser/dompurify/dompurify.js: Unexpected 503 response from vscode-file://vscode-app/home/max/repos/vscode/out/vs/base/browser/dompurify/purify.es.js.map: Unsupported protocol "vscode-file:"
 INFO [FileService]: Using sandbox ready file system provider
[Extension Host] debugger listening on port 5870
 INFO [LocalProcessExtensionHost]: IExtensionHostStarter.createExtensionHost() took 871 ms.
 INFO [LocalProcessExtensionHost]: IExtensionHostStarter.start() took 26 ms.
[Extension Host] debugger inspector at chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5870/8b30cbb9-60e9-40a6-b577-0e5ee91abacb
```

(I expect to see the lines printed with `console.log` and `console.info` in the VS Code instance being debugged.)

This seems to be similar to #125841, but #125841 has been fixed/closed already.

Steps to Reproduce:

1. Start VS Code (in my case: Codium)
2. Open folder with git repository of VS Code (in my case `/home/max/repos/vscode/`, commit 45fdad3a10d)
3. Click "Run and Debug"
4. Select "Launch VS Code"
5. Click "Start Debugging" (or press F5)

**Comment by MaxGyver83** [comment]
Here's a gif:
![2022-01-19 19-57 VS Code](https://user-images.githubusercontent.com/13970628/150196851-14abbf81-a6cd-47e6-8c8b-da0efe0453a8.gif)

**Comment by connor4312** [comment]
Okay, thanks. The log line you see is fine. Where are the console.log's that you're expecting to see? I'm guessing they're being hit in a process other than the renderer, so when you debug only the renderer you don't see them.

**Comment by MaxGyver83** [comment]
When I add a line like this:

```diff
$ git diff
diff --git a/src/vs/workbench/contrib/preferences/browser/keybindingWidgets.ts b/src/vs/workbench/contrib/preferences/browser/keybindingWidgets.ts
index 0b996a9ea8e..274fb7bcad7 100644
--- a/src/vs/workbench/contrib/preferences/browser/keybindingWidgets.ts
+++ b/src/vs/workbench/contrib/preferences/browser/keybindingWidgets.ts
@@ -276,6 +276,7 @@ export class DefineKeybindingWidget extends Widget {
          this._chordPart = chordPart;
          dom.clearNode(this._outputNode);
          dom.clearNode(this._showExistingKeybindingsNode);
+         console.log(this._firstPart);

          this.keybindingLabelStylers.clear();
```

How/where can I see this console.log's output? (Of course, I tried changing some keybindings for provoking a logging output.)
How can I debug another component than the renderer?
