### ISSUE TITLE
startup time is slower on KDE Plasma compared to GNOME

### ISSUE THREAD

**Issue by tur1ngb0x** [microsoft/vscode#135720]
Issue Type: <b>Bug</b>

The startup time on Ubuntu 20.04.3 LTS and PopOS 20.04 LTS is around 1-2 seconds  compared to KDE Neon (Ubuntu 20.04.3 LTS) which is around 5-6 seconds.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:58:13.605Z)
OS version: Linux x64 5.11.0-38-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 845)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|7.65GB (2.50GB free)|
|Process Argv|--unity-launch --crash-reporter-id fdb1a24a-4a32-48f2-8b06-ea887d2690ba|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|4.10.0

</details>

```
 ~ $ cat /etc/os-release 
NAME="KDE neon"
VERSION="5.23"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User - Plasma 25th Anniversary Edition"
VARIANT="User Edition"
VARIANT_ID=user
VERSION_ID="20.04"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
LOGO=start-here-kde-neon
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
 ~ $ plasmashell --version
plasmashell 5.23.1
```

```
 ~ $ lspci -nnk | grep -iE 'vga|3d'
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07)
01:00.0 3D controller [0302]: NVIDIA Corporation GP108M [GeForce MX150] [10de:1d10] (rev a1)
```

```
 ~ $ lsmod | grep -i nouveau
nouveau              1986560  1
mxm_wmi                16384  1 nouveau
drm_ttm_helper         16384  1 nouveau
ttm                    73728  2 drm_ttm_helper,nouveau
i2c_algo_bit           16384  2 i915,nouveau
drm_kms_helper        237568  2 i915,nouveau
drm                   548864  20 drm_kms_helper,drm_ttm_helper,i915,ttm,nouveau
wmi                    32768  5 intel_wmi_thunderbolt,acer_wmi,wmi_bmof,mxm_wmi,nouveau
video                  53248  3 acer_wmi,i915,nouveau

```

**Comment by deepak1556** [comment]
Can you share the profile based on https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly and also the startup timers https://github.com/microsoft/vscode/wiki/Performance-Issues#read-the-startup-timers
