### ISSUE TITLE
debugger not working

### ISSUE THREAD

**Issue by fafamnzm** [microsoft/vscode#135756]
Issue Type: <b>Bug</b>

I had a nuxt2 project and i could have used the debugger.
usually i start the terminal and then i launch the debugger with the green button
after the latest update for some unknown to me reason, i am unable to work with it
i hit the green button and the window in chrome would come up 
but as soon as i interact with the project, the chrome would crash giving the only error of `crbug/1173575, non-JS module files deprecated.`

i can run the project on chrome or firefox, but i cannot use the debugger and the issue is solely with debugger

i even run yarn dev in debugger terminal and I still cannot use the debugger, like breakpointrs, etc.

it was working perfectly fine before the latest update. after this update, this issue has come up

thank you 
faramarz

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (4.66GB free)|
|Process Argv|--folder-uri file:///c%3A/Personal/Projects/Avakatan/pwa-jeanswest-app --crash-reporter-id 4d16300f-0a30-451a-ba9a-62da2cd12706|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-apollo|apo|1.19.7
emojisense|bie|0.9.0
path-intellisense|chr|2.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.2.2
githistory|don|0.6.18
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.1
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.0.0
git-project-manager|fel|1.7.1
vscode-firefox-debug|fir|2.9.4
auto-rename-tag|for|0.1.9
go|gol|0.28.1
rest-client|hum|0.24.5
easy-icons|jam|0.3.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.17.0
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.2
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
vetur|oct|0.35.0
indent-rainbow|ode|8.2.1
material-icon-theme|PKi|4.10.0
ayu|tea|1.0.5
vuetify-vscode|vue|0.2.0
JavaScriptSnippets|xab|1.8.0

(14 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by connor4312** [comment]
Thanks for the info. Unfortunately this seems to be an error in Chrome itself; as soon as we call `Debugger.enable()`, the page crashes. Please open an issue for them: https://bugs.chromium.org/p/chromium/issues/list
