### ISSUE TITLE
always be stuck

### ISSUE THREAD

**Issue by huhutm** [Microsoft/vscode#13581]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14931
- Extensions: auiworks.amvim-1.13.0, donjayamanne.python-0.4.1, hars.CppSnippets-0.0.5, lukasz-wronski.ftp-sync-0.3.1, mitaki28.vscode-clang-0.2.1, ms-vscode.cpptools-0.9.2, ms-vscode.csharp-1.4.1, webfreak.debug-0.12.2

Steps to Reproduce:

1.  Just write code, It will be stuck for a few seconds.

**Comment by isidorn** [comment]
Can you reproduce this problem when running code with `--disable-extensions`?

**Comment by huhutm** [comment]
It seems ok with --disable-extensions. But it is difficult to write code without externsions. 
These are my extensions : amVim, Python, c/c++ snippets, ftp-sync, c/c++ Clang, c/c++, c#, Native Debug.

**Comment by isidorn** [comment]
I would uninstall your extensions one by one to try to find the one which is to blame for slowing down your vscode. Once you find that extension I would repor this issue to that extension.
There is nothing we can do on the vscode side to fix this.

**Comment by huhutm** [comment]
I found it! It's amVim. I'will report this issue.

**Comment by isidorn** [comment]
@huhutm great - thanks!
