### ISSUE TITLE
Intellisense slow

### ISSUE THREAD

**Issue by PieCodez** [microsoft/vscode#135877]
Issue Type: <b>Performance Issue</b>

My intellisense takes 4s to load and when I hover over something it used to display info instantly. But now i takes 5s. Help me

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.11GB free)|
|Process Argv|--crash-reporter-id 16b703ad-54b0-4015-b2d5-b5fac807ee0f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    84	 15004	code main
    0	   176	  1804	   window (Header.js - linkedin-clone - Visual Studio Code)
    0	   107	 15540	     extensionHost
    0	   226	  9312	       electron_node tsserver.js 
    0	    85	  9372	         electron_node typingsInstaller.js typesMap.js 
    0	   111	 14752	       electron_node tsserver.js 
    0	    69	 15664	     watcherService
    0	    37	  6664	   utility
    1	    81	  9708	   window (Issue Reporter)
    0	   141	 11540	   gpu-process
    0	    25	 16368	   crashpad-handler
    0	    85	 16624	   shared-process
    0	    67	 16360	     ptyHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Header.js - linkedin-clone - Visual Studio Code)
|    Folder (linkedin-clone): 43 files
|      File types: svg(20) js(5) json(3) png(3) css(2) gitignore(1) ico(1)
|                  html(1) txt(1) md(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|3.1.1
vscode-styled-components|jpo|1.6.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by dylantf** [comment]
I'm not sure how to file a "proper issue report" but I wanted to add that I'm experiencing a pretty significant slowdown too with the internal language server stuff, like intellisense for typescript, eslint, and so on. Code to reproduce is any valid JS/TS code - it shows the autocomplete window with Loading... for several seconds when it was instant before the latest update. I'm on 1.61.2 on Windows 11, and tried it with both remote WSL (my usual setup) and also running it straight from windows and it's super slow on both. The UI/file opening/etc all seems fine.

**Comment by mjbvz** [comment]
@dylantf  See the issue reporting guidelines: https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

For performance issues, see https://github.com/microsoft/vscode/wiki/Performance-Issues
