### ISSUE TITLE
editor.guides.bracketPairs causing scroll lag

### ISSUE THREAD

**Issue by MariuzM** [microsoft/vscode#135844]
I've noticed and not sure if this is from last couple of updates or my code is just getting bigger but using `editor.guides.bracketPairs` when scrolling on lets say `tsx` document scroll becomes really slow / lagy, but when i scroll to the area where there is only 1-2 of `editor.guides.bracketPairs` lines it's fine but when it's 5 or more scroll is lagy. 

`editor.guides.bracketPairs` disabling it solves the issuse.

Version: 1.61.2
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0

MacBook Air M1

**Comment by hediet** [comment]
Closing, as this does not seem to be a common problem. We tried the feature on huge documens and it is sufficient fast.
Please reopen if you can reproduce consistently.
