### ISSUE TITLE
Debugging through IIS

### ISSUE THREAD

**Issue by Dave3of5** [Microsoft/vscode#13587]
- VSCode Version: 1.6
- OS Version: Windows 7

Steps to Reproduce:

1.  Create a Asp.Net MVC or WebForms App.
2. Try to attach Visual Studio Code to IIS for debugging purposes.

Don't see any real option to debug...

**Comment by isidorn** [comment]
This issue should be filed to the vscode c# extension. Can you please file it there?
https://github.com/OmniSharp/omnisharp-vscode
Thanks you!
