### ISSUE TITLE
bug; unexpected behavior when using shift+tab to reduce indent

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#135819]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version:1.62.2
- OS Version:win7 win10 win11
- 

hi, vscoder,  I think that is an bug of vsocde, and that is serious for editing:

Steps to Reproduce:
1. set tabsize = 4 and use space
2. use those code  which contains block comments that padding one space in left
```csharp
    /*
     * THIS IS IN CSharp
     */
    Boolean IsOnlyWriteWithin32Bit { get; }

```
![image](https://user-images.githubusercontent.com/1876302/138790054-fb65bca0-5e74-4433-8009-69b37b29be0a.png)
![image](https://user-images.githubusercontent.com/1876302/138790102-77f24f5c-dab4-41cb-9087-1dd662edcd58.png)

3. select the  code block
4. use shift+tab
5. the code indent reduce with in 4 space, but the block comment just reduce one space
6. hit shift+tab again, block comment reduce 4 sapce
expected behavior:
1. frist time hit shift+tab, code and block comment should be reduced 4 space at the same time, 

THIS IS VERY IMPORTANT  FOR C/C++ DEVELOPMENT:
Because we normal add one space to the start of block comment lines.
![image](https://user-images.githubusercontent.com/1876302/138790685-805fe0ae-d70c-4c1b-a0d7-d8fb945e65b0.png)

**Comment by heartacker** [comment]
😫

**Comment by rebornix** [comment]
It looks like that the indentation rules for C#/C++ is not covering this case. Currently the indentation rules for  auto indent feature in VS Code is regex based, which doesn't really understand the scope (function, statement) etc. Formatting works more consistently in this scenario, so I would recommend to enable formatting on type or save. Closing this as we don't expect to get around it in the near future.
