### ISSUE TITLE
viewport gets pushed up repeatedly when toggling size to content width

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#135804]
![recording - 2021-10-25T132205 620](https://user-images.githubusercontent.com/29464607/138765111-ce32e8f2-5adc-4bb8-aa7e-b54c104c8345.gif)

**Comment by rzhao271** [comment]
Got a repro on pwsh

![Repro](https://user-images.githubusercontent.com/7199958/139483494-4a15149c-bcdf-4dcf-8b85-1097e643bf23.gif)

**Comment by meganrogge** [comment]
are you on the latest insider's @rzhao271 ?

**Comment by meganrogge** [comment]
I fixed this 2 days ago.

**Comment by rzhao271** [comment]
Yep
Potential regression?

Version: 1.62.0-insider (user setup)
Commit: ff1e16eebb93af79fd6d7af1356c4003a120c563
Date: 2021-10-29T05:16:23.014Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by meganrogge** [comment]
I find it really strange that everyone but me can reproduce this
![recording - 2021-10-29T112759 377](https://user-images.githubusercontent.com/29464607/139484416-44b366d7-aaf8-41af-900d-dbb28dc19297.gif)
.

**Comment by meganrogge** [comment]
@rzhao271 can you try in OSS off of main? I also can't repro it there.

**Comment by rzhao271** [comment]
It's fine in OSS. Will see if it's from an extension

**Comment by rzhao271** [comment]
It happens at a specific zoom level. In my case, it's zoom level 2.

**Comment by meganrogge** [comment]
interesting. @Tyriar thoughts?

**Comment by Tyriar** [comment]
Can't reproduce, I do see size is not correct when zoom level is 2 though:https://github.com/microsoft/vscode/issues/136374
