### ISSUE TITLE
Notebooks - Diff indicator shown despite same output

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#135820]
- VS Code Version: 1.62.0-insider
- OS Version: WIndows

Diff color indicators on output that is the same 

![image](https://user-images.githubusercontent.com/19276747/138790778-0fe16c10-9701-4bd6-83b9-27ec3a2f8f85.png)

**Comment by claudiaregio** [comment]
There are other changes in the document, since all I do is run I believe it's flagging the output ID changing

**Comment by burkeholland** [comment]
Hit this in the Golden Scenario today. I am unable to tell from the diff what has changed and what has not as the output looks *identical* to me. Perhaps this is a matter of just knowing that the underlying JSON changed, but I found it confusing as I was looking for differences in places where there really is none of material importance.

**Comment by rebornix** [comment]
Thanks for the file provided above and the screen recording!

Dig into this and found it interesting, is there an output change? Yes, but it is not anything that one can tell from the Diffing. What are the changes?

* The output contains metadata, which includes the execution count, thus they are different on different runs. Not sure if they are saved to disk, but our diff view doesn't really tell you if it's output metadata change, or output value change. This is something we should improve in the diff editor
* If we then compare the output, the sequence of `text/html`/`text/plaintext' is flipped. This is when you see no change in the rich diff editor, but you see an entry in SCM cc @roblourens @DonJayamanne

**Comment by roblourens** [comment]
Maybe they need to be sorted along with other keys in https://github.com/microsoft/vscode/issues/129435

**Comment by roblourens** [comment]
We already sort all keys in the notebook when serializing, so the order of the mimetypes should have been sorted. Which order did you see it in? Maybe it started out wrong?

**Comment by tanhakabir** [comment]
+1 from golden scenario run by me

**Comment by greazer** [comment]
Reopening this as it contains a lot of extra info and it's been repro'd and re-entered at least 2 other times. We really should do something to address the problem.

**Comment by roblourens** [comment]
Could you link the dupe issues?

**Comment by greazer** [comment]
Basically, looks like the same issue was found 3 separate times during golden scenario runs.

* https://github.com/microsoft/vscode/issues/141966
* https://github.com/microsoft/vscode/issues/137836
* https://github.com/microsoft/vscode/issues/121622#issuecomment-915595123 (first example)
* https://github.com/microsoft/vscode/issues/133554 (essentially same as above)

**Comment by rebornix** [comment]
Should be fixed in today's Insiders.
