### ISSUE TITLE
Chinese translation is not completed

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/vscode#135831]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2
- OS Version: MacOS Big Sur

I already installed Chinese (Simplified) (简体中文) Language Pack for Visual Studio Code
v1.62.0, but there are still some texts which aren't translated to Chinese:

![image](https://user-images.githubusercontent.com/8640918/138821889-2d39fe50-1a67-4ccc-96fa-95fcd1578a69.png)

![image](https://user-images.githubusercontent.com/8640918/138821938-5b23e359-ffed-4a4e-a93f-b00646d8f1ad.png)

**Comment by TylerLeonhardt** [comment]
Looks like the translation is there now:
https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L2816

Closing this. @HaoboGu please give this another go with the latest Language Pack and let us know.

**Comment by rzhao271** [comment]
The "Open Workspace from File..." has been translated now, and I can see it on Insiders. I'll leave the verified label for the endgame.

![Evidence](https://user-images.githubusercontent.com/7199958/142050365-b1e6185c-b118-4213-903c-6d37726bd255.PNG)
