### ISSUE TITLE
[i18n] Fix Korean Translation

### ISSUE THREAD

**Issue by appetizermonster** [Microsoft/vscode#13586]
- VSCode Version: 1.6.0
- OS Version: Windows 7 SP1 x64

There is a translation error in `i18n/kor/src/vs/workbench/browser/actions/configureLocale.i18n.json`

```
"doc": "지원되는 언어 목록은 {0}을(를) 참조하세요."
```
this text should be
```
"doc": "지원되는 언어 목록은 {0} 을(를) 참조하세요."
```

`{0}` is replaced with url `https://go.microsoft.com/fwlink/?LinkId=761051`.
then, the hyperlink in original text is interpreted as `https://go.microsoft.com/fwlink/?LinkId=761051을(를)`.
so when you click the link, you only can see the wrong page.

**Comment by johnliu2016** [comment]
@lukaschal need to insert a space after the placeholder '{0}'

[configureLocale.nls.resx.lcl](https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fkor%2Fvscode%2Fsrc%2Fvs%2Fworkbench%2Fbrowser%2Factions%2FconfigureLocale.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";doc" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[See {0} for a list of supported languages.]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[지원되는 언어 목록은 {0}을(를) 참조하세요.]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>

**Comment by lukaschal** [comment]
Fixed.

File: src\vs\workbench\browser\actions\configureLocale.nls.resx
ID: ".resx", 0; "doc"
SRC: See {0} for a list of supported languages.
TGT: 지원되는 언어 목록은 {0} 을(를) 참조하세요.
