### ISSUE TITLE
120hz ProMotion scrolling is not supported in latest Macbook Pro 2021

### ISSUE THREAD

**Issue by hxssgaa** [microsoft/vscode#135857]
VS Code Version: Latest 1.61.2
OS Version: Latest MacOS 12.0.1
Hardware: 14-inch Macbook Pro 2021 with 120hz ProMotion display

Steps to Reproduce:

1. Open any project
2. Open any long code file and scroll

Expectet:
120hz scrolling

Actual:
60hz scrolling

I can see it clearly in my eyes it's definitely not 120hz scrolling and confirmed with Quartz Debug tool.

Please fix the error and let new Mac users move to 120hz coding experience. Thanks.

**Comment by TylerADavis** [comment]
It looks like this may actually be a Chromium / macOS bug

https://bugs.chromium.org/p/chromium/issues/detail?id=1261194#c16
https://9to5mac.com/2021/10/29/not-so-smooth-scrolling-macbook-pro/

**Comment by xzbdmw** [comment]
Is it still not fixed?

**Comment by ArtemBernatskyy** [comment]
wtf, abandonware

**Comment by jokerwyt** [comment]
It's 2024.3.24 now, seems still not fixed.....

**Comment by xzbdmw** [comment]
> It's 2024.3.24 now, seems still not fixed.....

Hmm, 120hz is working well now

**Comment by jokerwyt** [comment]
> > It's 2024.3.24 now, seems still not fixed.....
> 
> Hmm, 120hz is working well now

Is there any special setting? I am using Macbook Pro 2021 m1pro, and I can tell definitely that it's not 120hz when I am scrolling the code editor over 1k lines of code.

**Comment by xzbdmw** [comment]
> > > It's 2024.3.24 now, seems still not fixed.....
> > 
> > 
> > Hmm, 120hz is working well now
> 
> Is there any special setting? I am using Macbook Pro 2021 m1pro, and I can tell definitely that it's not 120hz when I am scrolling the code editor over 1k lines of code.

you can try full screen the app, fresh rate is not stable when not full screen

**Comment by jokerwyt** [comment]
> > > > It's 2024.3.24 now, seems still not fixed.....
> > > 
> > > 
> > > Hmm, 120hz is working well now
> > 
> > 
> > Is there any special setting? I am using Macbook Pro 2021 m1pro, and I can tell definitely that it's not 120hz when I am scrolling the code editor over 1k lines of code.
> 
> you can try full screen the app, fresh rate is not stable when not full screen

Thanks, but it still doesn't work for me😭

**Comment by hckhanh** [comment]
Is it resolved?

**Comment by hxssgaa** [comment]
it’s confirmed working with my side.

**Comment by jokerwyt** [comment]
Restarting Vscode helps. I think it may be some memory leak issues.
