### ISSUE TITLE
editor.formatOnSave

### ISSUE THREAD

**Issue by CedrikWinter** [microsoft/vscode#135840]
Issue Type: <b>Bug</b>

On "merged by git" files, lines `<<<<< HEAD` and similars are formatted with spaces... And vscode doesn't recognize this git differences anymore.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Remote OS version: Linux x64 5.10.47-linuxkit

<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
crontab-syntax-highlight|hog|0.0.1
vscode-peacock|joh|3.10.1
vscode-language-pack-fr|MS-|1.61.5
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.202.5
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.3
vscode-remote-extensionpack|ms-|0.21.0
gitlens|eam|11.6.1
rest-client|hum|0.24.5
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.2
jupyter|ms-|2021.9.1101343141
jupyter-renderers|ms-|1.0.3

</details>

**Comment by CedrikWinter** [comment]
Sorry for late response...
Here are some screenshots :

with `formatOnSave: false` :
![merge-formatOnSave-False](https://user-images.githubusercontent.com/15106995/140038286-4bff9d96-a932-481b-9efe-8e2b52769f04.png)

with `formatOnSave: true` & a _file save action_ `ctrl + s` :
![merge-formatOnSave-True](https://user-images.githubusercontent.com/15106995/140038271-cf455dd8-90e8-470e-a518-b7df18506815.png)

**Comment by jrieken** [comment]
what language is this?

**Comment by CedrikWinter** [comment]
This is python (3.7.9). As you can see in the settings (right panel).

**Comment by CedrikWinter** [comment]
➡️ https://github.com/microsoft/vscode-python/issues/17914

thanks ;)

**Comment by karthiknadig** [comment]
@jrieken Is there a way to find out if we are in the git-diff mode somehow? I don't see anything on the `TextDocument` object about this. I would like to avoid looking for these patterns in the file.

**Comment by jrieken** [comment]
No, we have no generic knowledge about this... I know that TypeScript detects the merge syntax, independent of the actual git state, it's purely textual (see below). Another option is to ignore formatting requests in the presence of syntax errors

<img width="402" alt="Screen Shot 2021-11-04 at 08 36 50" src="https://user-images.githubusercontent.com/1794099/140274826-9d105cb9-2309-47fc-aa79-558e1a604cf4.png">
