### ISSUE TITLE
icon indentetion is wrong

### ISSUE THREAD

**Issue by envergokmen** [Microsoft/vscode#13580]
files seems belong to folder which is in the same path/dept.  You can see in the image, my index.html is not under the node modules. I think there is an indentetion problem with icons.

- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: abotteram.typescript-react-snippets-0.1.9, atefth.ruby-on-rails-snippets-0.0.1, CraigMaslowski.erb-0.0.1, g3ortega.crystal-0.1.8, rebornix.Ruby-0.9.0

Steps to Reproduce:

1. activate seti icons
2. add a folder and file to root. and see result. 

![image](https://cloud.githubusercontent.com/assets/8162657/19303103/fc49266a-906f-11e6-9d2c-f5e8008f9908.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11762
