### ISSUE TITLE
Detect file renames across windows

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#135888]
Testing #135653

Re: 
> changes to files are reflected in the editor if the file is opened in the editor

1. Open same repo in two VS Code windows (one Insiders, one Stable)
2. Open same file in both windows
3. Rename file from the Stable window
4. 🐛 Renamed file stays open in Stable window with the new file name, but the open file in the Insiders window shows up as deleted instead of renamed

**Comment by bpasero** [comment]
Given what I have seen so far with regards to watcher support, this is unrealistic to get from our libraries.
