### ISSUE TITLE
Moving folders inside lasts too long and don't even complete

### ISSUE THREAD

**Issue by animanoir** [microsoft/vscode#135873]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2
- OS Version: W10

Steps to Reproduce:

1. Move folder with mouse around the workplace
2. 
![image](https://user-images.githubusercontent.com/5607826/138913598-b0bc6908-e0e1-4f17-a271-33ec806e802c.png)

**Comment by JacksonKearl** [comment]
Could you provide a sample directory where you see this behaviour?
