### ISSUE TITLE
Grunt build error when using integrated terminal (Git Bash)

### ISSUE THREAD

**Issue by IanOvenden** [Microsoft/vscode#13589]
- VSCode Version: 1.6.0
- OS Version: Windows 7 Enterprise (Service Pack 1)
- Git Bash Version: GNU bash, version 4.3.42(3)-release (x86_64-pc-msys)
- Node Version: 4.2.2

Hi,

I've recently begun to experience an issue with my Grunt build when executing through the integrated terminal.  I can't pinpoint exactly when the issue started occurring, but it was prior to the latest build - possibly from 1.5.

Our build is pretty complex and highly modular, so it would prove difficult to list it all out here.  I don't think it's particularly relevant at this stage, but I know it could prove useful.

Steps to Reproduce:
1. Open VS code and run the Grunt build without making any changes, it completes successfully. 
2. Make a change to a module, for example a scss partial. 
3. Re-run the build and encounter one of the following errors:

```
Running "requirejs:hub2" (requirejs) task                                                                                                                  
{ [Error: Error: EPERM: operation not permitted, stat 'C:\development\projects\wdp-versionable\cluster\external\hub2\scripts\facades']                     
  originalError:                                                                                                                                           
   { [Error: EPERM: operation not permitted, stat 'C:\development\projects\wdp-versionable\cluster\external\hub2\scripts\facades']                         
     errno: -4048,                                                                                                                                         
     code: 'EPERM',                                                                                                                                        
     syscall: 'stat',                                                                                                                                      
     path: 'C:\\development\\projects\\wdp-versionable\\cluster\\external\\hub2\\scripts\\facades' } } 
```

**OR**

```
Running "requirejs:hub2" (requirejs) task                                                                                                                  
{ [Error: Error: ENOTEMPTY: directory not empty, rmdir 'C:\development\projects\wdp-versionable\cluster\external\hub2\scripts']                            
  originalError:                                                                                                                                           
   { [Error: ENOTEMPTY: directory not empty, rmdir 'C:\development\projects\wdp-versionable\cluster\external\hub2\scripts']                                
     errno: -4051,                                                                                                                                         
     code: 'ENOTEMPTY',                                                                                                                                    
     syscall: 'rmdir',                                                                                                                                     
     path: 'C:\\development\\projects\\wdp-versionable\\cluster\\external\\hub2\\scripts' } }
```

![integrated-terminal-error](https://cloud.githubusercontent.com/assets/5471026/19306529/0858be86-906e-11e6-8711-e29a9f600baf.PNG)
1. Attempting to run the build outside of VS Code, in Git Bash also then leads to one of the same errors being thrown.
2. Tried killing the terminal session in VS Code, opening up a new one and running the build again.  This leads to same error.
3. Close VS Code and run the build externally in Git Bash - Build **completes successfully**

**Comment by Tyriar** [comment]
Strange... Does `C:\development\projects\wdp-versionable\cluster\external\hub2\scripts` or the files within it have special permissions?

**Comment by IanOvenden** [comment]
No, I suspected permissions as well but I've dropped security level right down. It also works outside of VS Code (as long as VS Code is closed).

The error regarding the empty directory is odd too, as when I check it in Explorer it appears empty.

**Comment by Tyriar** [comment]
Strange, well the main difference here is that cmd is being spawned by VS Code and inheriting its permissions. I would expect them to be the same though so I'm not sure why this would happen.

**Comment by Tyriar** [comment]
@IanOvenden please let me know if you're still experiencing this issue, there was a major change for the terminal on Windows in v1.9

**Comment by IanOvenden** [comment]
Hey @Tyriar ,

Thanks for the update.  Now that you mention it, I haven't noticed this issue when previously I would have expected it.  I'll continue to monitor.
