### ISSUE TITLE
Allow persistent cell input collapse [Notebooks]

### ISSUE THREAD

**Issue by duartefdias** [microsoft/vscode#135872]
I'm running Jupyter notebook files (.ipynb) in a GitHub codespace.
I know I am able to collapse the cell input manually:

![image](https://user-images.githubusercontent.com/24175831/138909364-b3ef6c9b-9171-45f3-ab0d-8498a47ba5ca.png)

I would like to make the cell input remain collapsed even after restarting the codespace.

This feature appears to exist in Jupyter notebooks by using cell metadata tags:
https://jupyterbook.org/interactive/hiding.html#hide-cell-inputs

I tried adding the "hide-input" tag in the cell metadata:

![image](https://user-images.githubusercontent.com/24175831/138910873-64bc162f-e4a7-4104-9fa6-4944ef3f0176.png)

But when restarting the codespace the cell input has its input expanded although still having the "hide-input" tag.

Is there currently any way of keeping the input of specific cells hidden by default?
If not, is this going to be implemented in the future?

This would increase the user experience as we would be able to hide the code of cells where, for example, we perform package inputs or define functions.

@joaomoreno

**Comment by rebornix** [comment]
The collapse state should now be persistent on window reload.
