### ISSUE TITLE
Overlapping title bar entries when switching tabs

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#135886]
## Environment data

-   VS Code version:
Version: 1.62.0-insider (user setup)
Commit: dc1a6699060423b8c4d2ced736ad70195378fddf
Date: 2021-10-26T08:49:04.076Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22483
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1001384888
-   Python Extension version (available under the Extensions sidebar): v2021.10.1365161279
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Python and/or Anaconda version: Python 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Testing https://github.com/microsoft/vscode/issues/135666

I keep switching between tabs as I try the different export settings
I notice the title bar area with notebook options has overlapping/conflicting text: 

![image](https://user-images.githubusercontent.com/25310137/138927509-f7e0d3ad-1de0-468e-947f-6518889d027d.png)

It goes away if I close the notebook, but happens again if I:
- Reopen Trapezoid.ipynb
- Switch tabs
- Quickly switch back to Trapezoid.ipynb

**Comment by rebornix** [comment]
No longer reproduce in latest Insiders.
