### ISSUE TITLE
Error launching browser: command 'js-debug-companion.launchAndAttach' not found

### ISSUE THREAD

**Issue by ryansutc** [microsoft/vscode#135882]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2
- OS Version: Windows 10 Pro (10.0.19043)

Steps to Reproduce:

1. Run an app in wsl2. Set up a debugger for chrome or node app.
2. Get a connection failed to connect error somehow.
3. Click the popup that takes you to the JavaScript Debugger Extension (built-in). 
4. Click 'disable`. Restart VSCode
5. Retry running debugger. 
6. Get this error:
```Error launching browser: command 'js-debug-companion.launchAndAttach' not found```
Check the JavaScript Debugger. It is enabled. 

I suddenly ran into an issue where my configured chrome docker debugger for an app was failing to connect upon startup. Clicking on the popup brought me to the JavaScript Debugger Extension. I know that this is a built-in feature but I figured I'll try disabling and reenabling it. See what happens. After hitting 'disable' and restarting VSCode, running the debugger immediately throws the above error (6). I go back to the JavaScript Debugger extension but it shows itself as enabled.
I've tried reinstalling VSCode for Windows no change. I've tried other projects, launch configurations doesn't matters same error persists. Debugging apps within windows is fine. Only wsl based ones fail. 

What needs to be done for this?

**Comment by connor4312** [comment]
> Click 'disable`. Restart VSCode

I'm thinking you disabled the JS Debug Companion here. That causes the that command, contributed by the disabled extension, to not show.

> Get a connection failed to connect error somehow.
> Click the popup that takes you to the JavaScript Debugger Extension (built-in).

I'm not familiar with this popup, do you recall any details or can you grab a screenshot of it? ( @aeschli do you know? )

**Comment by EECSMiner** [comment]
you may disble the **js-debug-companion**  extension
see more :[https://github.com/microsoft/vscode-js-debug-companion#js-debug-companion](url)
