### ISSUE TITLE
Use of LGPL Licence within an MIT Licenced Product is incorrect.

### ISSUE THREAD

**Issue by buxtonpaul** [microsoft/vscode#135853]
Yes

- VS Code Version: All versions
- OS Version: All OS's

VSCode uses an LGPL 2.1 library JSChardet, which is licensed under an LGPL2.1 licence. As the library is bundled and packaged with the product as it is distributed, I believe this means that the licence should be applied to VSCode as well.

If there is a reason why this doesn't apply it would be useful to know why.

Thanks,
Paul

**Comment by chrisdias** [comment]
Hi, thanks for opening this issue and asking the question!

To start, please know that I am not a lawyer :). I will do my best to answer your question here, but if you have additional concerns, it may be best for you to consult with an attorney.

In a nutshell, JSChardet is JavaScript port of Python’s chardet. It is not statically linked to either the binary or source of VSCode, it is an independent package. As a result, it does not change the licensing of VSCode. 

I hope this helps!
Chris
