### ISSUE TITLE
Opening local VS Code repo in the web shows task error

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#135803]
Does this issue occur when all extensions are disabled?: Yes/No

_Originally reported by @sandy081_ 

Steps to Reproduce:

1. Go to https://vscode.dev/
2. Open local folder, choose [VS Code repo](https://github.com/microsoft/vscode) cloned locally from the disk (not remotely/through GitHub Repositories)
3. Get following prompt: `There are task errors. See the output for details.`

![image](https://user-images.githubusercontent.com/25310137/138763358-956daabc-f707-4286-b297-b4bf198f712e.png)

Following warnings in output:

> Warning: shell tasks are unavailable in the current environment.
> 
> Warning: npm tasks are unavailable in the current environment.
> 
> Error: there is no registered task type 'gulp'. Did you miss to install an extension that provides a corresponding task provider?
> Warning: shell tasks are unavailable in the current environment.

@sandy081 reported opening the `src` folder to get this prompt. I get it when just opening the root VS Code folder.

@alexr00 As this is related to tasks, assigning to you, but please let me know if someone else should also investigate here. Thank you!

**Comment by dbaeumer** [comment]
Verified that VS Code in Web is not showing a notification anymore The errors are still printed to the tasks output which IMO is correct
