### ISSUE TITLE
Notebooks opening in JSON view

### ISSUE THREAD

**Issue by chamini2** [microsoft/vscode#135911]
## Environment data

-   VS Code version:  1.61.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1101343141
-   Python Extension version (available under the Extensions sidebar): v2021.10.1365161279
-   OS (Windows | Mac | Linux distro) and version: macOS 11.4 (20F71)
-   Python and/or Anaconda version: 2.7.17
-   Type of virtual environment used: I use pyenv command
-   Jupyter server running: Local

## Expected behaviour

It opens in Notebook view.

If I run the command `Jupyter: Create NEw Jupyter Notebook` it works

## Actual behaviour

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/2745502/138972156-24a29b9d-6b96-41ca-87b7-b95a2069a8d5.png">

## Steps to reproduce:

1. clone https://github.com/omnata-labs/dbt-ml-pipeline
2. open notebooks/Bank churn, preprocessed.ipynb

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Info 2021-10-26 18:46:17: Experimentation service retrieved: [object Object]
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 2021-10-26 18:46:18: ZMQ install verified.
```

</p>
</details>

**Comment by rebornix** [comment]
@chamini2 can you check if you have `workbench.editorAssociations` changed in your settings?

**Comment by chamini2** [comment]
That was it, I removed the ipynb line I had in there and it works now. Thanks!
