### ISSUE TITLE
Active Tab indicator too close to terminal's first line

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#135951]
Sometimes the Active Tab indicator is too close to terminal's first line:

<img width="414" alt="2021-10-27_15-13-03" src="https://user-images.githubusercontent.com/1898161/139072679-aa21b9c7-8a3a-49a5-8afa-dfe1b13f930e.png">

This looks somewhat cramped...

The gap between the Active Tab indicator and the first line depends on the size of the terminal as can be seen in this recording:

![2021-10-27_15-14-39 (1)](https://user-images.githubusercontent.com/1898161/139072960-31d5fefd-7dc6-4079-bd9d-d927e133a67e.gif)

So most of the time the gap is OK, but sometimes it is not.

I would expect that the gap is constant (and the position of the terminals first line adjusts to the Active Tab indicator).

**Comment by Tyriar** [comment]
This is one that would be good to get to the bottom of as this class of issues can obscure text and make the terminal look weirs when resizing or zooming.
