### ISSUE TITLE
Breakpoint Alarm / Sound

### ISSUE THREAD

**Issue by theUpsider** [microsoft/vscode#135908]
**While debugging:**
In Visual Studio it is possible to trigger an alarm sound, whenever a breakpoint is hit. This is extremely useful when having a long running code and after maybe hours a breakpoint is being hit. [Tutorial on how to activate](https://stackoverflow.com/questions/80564/visual-studio-how-to-trigger-an-alarm-when-a-breakpoint-is-hit)

We definitely need that feature in VS Code!

**Comment by dev-manuel** [comment]
I'll work on that. Could you please assign me?

**Comment by weinand** [comment]
@dev-manuel done

/cc @isidorn

**Comment by isidorn** [comment]
This is a fair request, but as a pre-request it has the ability for VS Code to play sounds. This is captured in this issue https://github.com/microsoft/vscode/issues/130565

After we have that we plan to add a sound when a user navigates to a line that has a breakpoint.
However we can also add a different sound when a breakpoint gets hit.

So I suggest to follow that issue for details, and once we have that we can continue on this one.

fyi @hediet

**Comment by Tyriar** [comment]
@isidorn @deepak1556 should we have vscode issue labelled electron to track enabling sounds and all related issues? I believe it doesn't work on some environments due to how Electron is packaged. This is the terminal issue tracking the audible bell https://github.com/microsoft/vscode/issues/47711

**Comment by isidorn** [comment]
Even though this issue is too specific, it captures our first steps into making sounds by vscode https://github.com/microsoft/vscode/issues/130565
So I suggest to not create any new issue and depending on how that issue goes we can adopt sounds in other parts of VS Code.

fyi @hediet

**Comment by isidorn** [comment]
We are introducing sounds to VS Code. And we have already done so when a user navigates to a line with a breakpoint as part of our audioCue for breakpoints. More details here https://github.com/microsoft/vscode/issues/90842#issuecomment-1007553602

We are also thinking of adding a sound when a breakpoint is hit.
What I am not sure if the sound of a breakpoint hit should be different from a sound of when you navigate across a breakpoint. I think not. I think it should be the same sound, and the user can figure out the context based on if he or she is using keyboard to navigate or not.

We currently have a `audioCues` setting that can be "on" | "off" | "auto". I think we need another setting which would be "breakpointHit" or "importantOnly". The point is that I think a lot of users would want sounds when a brekpoint is hit, but not other sounds which are aimed more for our screen reader audance.

@hediet what do you think?

Sound design by @gino-scarpino

**Comment by hediet** [comment]
Implemented in 7057aac64f031956a2b57ca328d21924a9b192de.

You can set `audioCues.debuggerStoppedOnBreakpoint` to `on`, `off` or `auto`. Default is `auto`.

**Comment by isidorn** [comment]
I tried it out and works as expected -> adding verified label.

Users try this out by setting `"audioCues.debuggerStoppedOnBreakpoint": "on"` in your settings.
Feedback is very much welcome. Thank you!

**Comment by roblourens** [comment]
I also like `audioCues.onDebugBreak`, although it's not a big deal if you don't want to change the setting at this point.

A similar phrase is used in these settings

<img width="427" alt="image" src="https://user-images.githubusercontent.com/323878/155393658-1d8bf4fd-f3d7-4b20-b9c1-fa1118b39d25.png">

**Comment by isidorn** [comment]
@hediet I think it is not too late to change. What do you think? Can we change to `audioCues.onDebugBreak`?

**Comment by hediet** [comment]
Fixed in 643cf95e.
