### ISSUE TITLE
rg process kill my Mac ever

### ISSUE THREAD

**Issue by ottopic** [microsoft/vscode#135936]
Issue Type: <b>Bug</b>

I work on samba volumes of linux lan network. When I open folder of my work rg process start consuming a lot of processor. Every time I open vcode I need to kill rg process to preserve my mac and server resources put under stress.

Steps to Reproduce:

1. Open folder on linux Samba volume
2. See rg process become more and more big

An additional problem is that if vcode is closed and reopened the number of rg processes increases.

I have also configured the exclusion of the search paths without 100% resolving:

"search.exclude": {
        "/Volumes/": true,
        "/Volumes/**": true
}

"files.watcherExclude": {
        "/Volumes/": true,,
        "/Volumes/**": true
}

On Windows PC without any custom setting it's seems this problem doesn't exists.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 776dd4c1-b9cb-4d2c-a2c5-b82cb1e56d87|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-titanium|Axw|0.12.4
bracket-pair-colorizer-2|Coe|0.2.1
macros|ctf|0.0.4
xml|Dot|2.5.1
setting-toggle|Ho-|1.4.1
uuid-generator|net|0.0.4
material-icon-theme|PKi|4.10.0
format-html-in-php|rif|1.7.0
reveal|smu|1.2.7
highlight-matching-tag|vin|0.10.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by roblourens** [comment]
You probably have some extension starting a slow search. You could try using the "start extension bisect" command to figure out which one it is.

The `search.exclude` setting only takes a relative path inside your workspace folder.

**Comment by ottopic** [comment]
> You probably have some extension starting a slow search. You could try using the "start extension bisect" command to figure out which one it is.
> 
> The `search.exclude` setting only takes a relative path inside your workspace folder.

Ok, founded extension that create the problem.
https://marketplace.visualstudio.com/items?itemName=axway.vscode-titanium

**Comment by ewanharris** [comment]
@roblourens, I guess just an FYI for the VS Code team here. The fix for the issue was to remove `workspaceContains:**/timodule.xml` from our `activationEvents`. So I'm guessing that's either a bad value or the root cause might lie with how VS Code uses these?

**Comment by roblourens** [comment]
We are supposed to limit this search to 7s but it seems like that might not be happening

**Comment by roblourens** [comment]
Interesting - we weren't actually killing the ripgrep process when the timeout was hit. We stopped the processing of results that happens in our process, but should also kill ripgrep. So in the next Insiders, you should still see this rg process but only for 7s.
