### ISSUE TITLE
Switching to test explorer when users clicks 'run tests'

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#135999]
Some Java customers give feedback that they are not aware of the existence of test explorer.

I'm not sure if making VS Code automatically switching to test explorer when users clicks 'run tests' could solve this issue. @connor4312 do you think this is a good UX? 

// reference https://github.com/microsoft/vscode-java-test/issues/1325

**Comment by jdneo** [comment]
> Are your users only executing tests through gutter icons, or through some other way?

The Java test extension has some other integrations with different UI entries: the Java Projects explorer & the run button in the editor title area. But the usage ratio of them are really small(~4%).

So most of the users run/debug their tests via the gutter icons or the test explorer.

**Comment by Trass3r** [comment]
A related issue arises when the sidebar is hidden manually or by the [autohide extension](https://marketplace.visualstudio.com/items?itemName=sirmspencer.vscode-autohide) (which really just implements functionality that should be builtin and has been requested for years #3742).

**Comment by jdneo** [comment]
@connor4312 I guess this issue can be closed given https://github.com/microsoft/vscode/issues/140596 has been resolved?

**Comment by connor4312** [comment]
Oh, right. I looked for a duplicate issue but missed this.
