### ISSUE TITLE
Bad API config documentation

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#13599]
Here's the [documentation for `vscode.workspace.getConfiguration`](https://github.com/Microsoft/vscode/blob/760b880ee486359ef1aa0e398d5056c6055d87f0/src/vs/vscode.d.ts#L3840):

```
		 * When a section-identifier is provided only that part of the configuration
		 * is returned. Dots in the section-identifier are interpreted as child-access,
		 * like `{ myExt: { setting: { doIt: true }}}` and `getConfiguration('myExt.setting.doIt') === true`.
```

The snippet `getConfiguration('myExt.setting.doIt') === true` is impossible, since `getConfiguration()` returns something of the `WorkspaceConfiguration` type.

The real snippet which matches the implementation should be: `getConfiguration('myExt.setting').get('doId') === true`.

**Comment by jrieken** [comment]
Good catch!
