### ISSUE TITLE
Settings search query is wrongly restored

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#135910]
- Open settings gui
- Do a search, "encoding"
- Delete the search query, close the settings editor
- Reload the window
- Open the settings editor
- "encoding" is prepopulated in the search field, I can't get rid of it

@rzhao271 did something change in how the search query is persisted?

**Comment by rzhao271** [comment]
A note that it's much easier to repro this issue by switching between two workspaces with different search queries in the settings editor.

**Comment by rzhao271** [comment]
When we want the query to be restored: when the user drags the settings editor to another editor group.
When we do not want the query to be restored: when the window is reloaded (the call stack in this case contains https://github.com/microsoft/vscode/blob/8d5348aba635b8aec54ed8643fd0dfa212b26d19/src/vs/workbench/browser/workbench.ts#L131).
When we currently restore the query: whenever a settings editor model is created, which includes both cases above.

The code deciding when to restore the cache is within https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts#L1047-L1070. Currently, if a new model must be used, then the cache is restored.

**Comment by rzhao271** [comment]
A mitigation for now that I'd like to try is to destroy the memento during `onWillShutdown`, and then add a flag to prevent future saving of the memento for the rest of the shutdown.
Note that the settings editor does not have complete control over when `saveState`, which saves the memento, is run.

**Comment by rzhao271** [comment]
I see a similar issue with the SCM commit message inputbox, so I wonder if the problem is more general than editorMementos in the Settings editor.

**Comment by rzhao271** [comment]
I pushed a mitigation. We _do_ want to save the memento for reloads, but I'm clearing it out during `saveState` whenever we don't pass the `isVisible` condition.

**Comment by rzhao271** [comment]
Closing for verification.

**Comment by roblourens** [comment]
I hadn't seen this in awhile, then I was reproing it again for a bit, then I was trying to debug it, but it went away. It still seems like sometimes the memento gets "stuck" and is not cleared. But I can't repro an issue right now so I'll mark it as verified for now.
