### ISSUE TITLE
Unwanted spacing around works with inlay hints

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#135955]
* enable inlay hints
* go here https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/markers/common/markerService.ts#L17
* notice how mark occurrences has extra padding on the right and how the cursor doesn't stick to the character

<img width="433" alt="Screen Shot 2021-10-27 at 16 27 13" src="https://user-images.githubusercontent.com/1794099/139086249-eff5f9d5-1ac2-4182-9dbd-1e193c530f59.png">

**Comment by hediet** [comment]
I think it might be better if you use a non-break whitespace instead of a css padding, as that improves word-wrapping and column-navigation.
That would also fix this issue.

**Comment by jrieken** [comment]
We should try that. Tho, today the whitespace is without background color. So, it must be a separate decoration (as I do for links/parts) and than breaking vs non-breaking might not matter any more
