### ISSUE TITLE
Bad "Add to Watch" for Private Fields

### ISSUE THREAD

**Issue by robpalme** [microsoft/vscode#135944]
Issue Type: <b>Bug</b>

1.  Debug a program with ES2022 `#` private fields.
2.  In the Variable Inspector, right-click a private field and choose _"Add to Watch"_

VS Code incorrectly uses a computed field `i["#foo"]` instead of a literal field `i.#foo`.  Whereas Chrome DevTools gets it right.

**VS Code experience**
![private-add-to-watch-vscode](https://user-images.githubusercontent.com/6939381/139048826-e2a7c464-a3e4-4c9d-8695-b70b97146dde.PNG)

**Chrome DevTools experience**
![private-add-to-watch-chrome](https://user-images.githubusercontent.com/6939381/139048855-fee776e1-34ad-42d8-b5a9-a2c934a21f73.PNG)

VS Code version: Code - Insiders 1.62.0-insider (0f7f6e338a4e86306474d4d01bdea9b8fe798017, 2021-10-27T05:15:07.768Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by roblourens** [comment]
Still getting the same


![image](https://user-images.githubusercontent.com/323878/144305477-1f97aa96-a026-4cd1-9ee9-a5568b1f450b.png)

**Comment by IanMatthewHuff** [comment]
![image](https://user-images.githubusercontent.com/812783/151236569-32a7f303-4afe-4750-953e-f8d0b74e121a.png)
verified, looks right now.
