### ISSUE TITLE
Source control can't sync local commits with latest git.

### ISSUE THREAD

**Issue by cebor** [microsoft/vscode#135964]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.61.2
- OS Version: macOS 12.0.1 (21A559)

Steps to Reproduce:

1. Install git 2.33.1
2. ensure you have only default settings in ~/.gitconfig, no push settings
2. Clone a Repo of you choice
3. Create a local commit
4. Press the Sync Button in Source Control.

You will get following error:
```console
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
```

Fix proposal:

Think the Source Control needs to add the `--no-rebase` flag to the pull command, than users will not get issues with default git settings.

**Comment by robertkruk** [comment]
Got same issue in VSCODE, can use GitHub desktop to sync successfully.

**Comment by robertkruk** [comment]
`git config pull.rebase false`
seems to have fixed it for me

**Comment by cebor** [comment]
> `git config pull.rebase false` seems to have fixed it for me

Yes, seems tobe an issues with git and not related to vscode.

`pull.rebase false` should be the default, but must be set explicitly since some of the lastest versions of git.
