### ISSUE TITLE
vscode logo rarely visible with dark color themes

### ISSUE THREAD

**Issue by christianmalek** [Microsoft/vscode#13596]
- VSCode Version: 1.6.0
- OS Version: Windows 10

Light theme:
![image](https://cloud.githubusercontent.com/assets/2873986/19308791/baa41898-9081-11e6-8990-7db59b96b022.png)

Dark theme:
![image](https://cloud.githubusercontent.com/assets/2873986/19308796/c2c4bece-9081-11e6-8cde-c91aebfa0adc.png)

What about using an SVG instead of an image for the logo and just use the default text color (with an little transparency) for the fill color of the SVG logo? Then it would be visible in all themes.

**Comment by bpasero** [comment]
Closing "as designed". We also changed the logo in the meantime.
