### ISSUE TITLE
[broken reference link] build/lib/i18n.js

### ISSUE THREAD

**Issue by passerby-1** [microsoft/vscode#135931]
Does this issue occur when all extensions are disabled?: doesn't matter (code comment)

- VS Code Version: doesn't matter (code comment)
- OS Version: doesn't matter (code comment)

Steps to Reproduce:

In build/lib/i18n.js, line 865
https://github.com/microsoft/vscode/blob/0f7f6e338a4e86306474d4d01bdea9b8fe798017/build/lib/i18n.js#L865

1. Transifex's old documentation page (https://dev.befoolish.co/tx-docs/public/projects/updating-content#what-happens-when-you-update-files) is no longer available. (whole dev.befoolish.co/* is no longer available.)
2. New documentation is at "https://docs.transifex.com/projects/updating-content#what-happens-when-you-update-files".

**Comment by TylerLeonhardt** [comment]
I did this as some point, just don't know when.
