### ISSUE TITLE
[css] Need to remove old CSS grid syntax and add new syntax 

### ISSUE THREAD

**Issue by Ollie-w** [Microsoft/vscode#13595]
- VSCode Version: Version 1.6.0 (1.6.0)
- OS Version:

Steps to Reproduce:
1. type some CSS grid properties. 
2. look at suggestions and look at linter

Linter is displaying "unknown property" for valid CSS grid syntax. Autocomplete suggestions only show old syntax( which should be removed)

You can find the syntax here: 
https://css-tricks.com/snippets/css/complete-guide-grid/
or
http://www.w3.org/TR/css3-grid-layout/

**Comment by lannonbr** [comment]
I am interested in helping out with this. Would updating the CSS extension (and related extensions, i.e. sass, less) JSON specifications be the only requirement, or are there any other files to look into and modifying.

**Comment by aeschli** [comment]
Thanks for offering help. The database of properties used for the css code completions is in https://github.com/Microsoft/vscode-css-languageservice/blob/master/build/css-schema.xml which gets converted to [browser.js](https://github.com/Microsoft/vscode-css-languageservice/blob/master/src/data/browsers.js)
But manually adding data isn't the preferred way. All the underlying data is now publicly available at http://schemastore.org/css/. So the best way would be to change the script to get the data from there. Alternatively we want to look into getting the data from the MDN team at https://github.com/mdn/data/tree/master/css

**Comment by hamer86** [comment]
What is the status of this. I'm really starting to use CSS Grid and i can't do it in my favorite editor :(

**Comment by lannonbr** [comment]
I've been busy with University work as the end of the semester usually gets for me, but I can now begin looking at since the semester just ended.

**Comment by lannonbr** [comment]
@aeschli Would it be fine if I manually inserted the schema for grid-layout for now and then in another PR we could work on getting the data from one of those sources?

**Comment by lannonbr** [comment]
Also, how would you recommend testing the addition before doing a PR?

**Comment by aeschli** [comment]
You can make a PR, but there's the risk of the work getting lost once we update.

**Comment by aeschli** [comment]
Yes, testing is difficult here given that the new input data is in a different form.
I'd try to make the output (the browser.js file) as similar as possible (same order of fields) so we can see from a diff that we are on the right track.

**Comment by aeschli** [comment]
We have some unit tests for completion that also test the data. But I admit that's covering only a few cases.

**Comment by lannonbr** [comment]
So I'm reading through the schema and it seems that a decent amount of the content is already there starting here: https://github.com/Microsoft/vscode-css-languageservice/blob/master/build/css-schema.xml#L3160. I have been updating the browsers attribute to include the browsers that support CSS Grid and I've run the generate_browserjs.js which has included them into the browsers.js file.

Is there something I am not seeing or is that basically all that I need to do?

**Comment by aeschli** [comment]
Yes, that's it for the quick fix.

**Comment by lannonbr** [comment]
Okay, going to commit and then push the PR

**Comment by lannonbr** [comment]
@aeschli Any updates on reviewing my PR?
