### ISSUE TITLE
Renaming property with space

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#13593]
```ts
interface Test {
    "alpha beta": string
}

const a : Test = {
    "alpha beta": "test"
}
```

Put cursor inside `beta` of interface and rename with F2

![image](https://cloud.githubusercontent.com/assets/1723815/19276731/574b9eba-8fa5-11e6-855a-6dc10a0d29f1.png)

Box to rename shows only `beta` - shall it show `alpha beta` ?

Rename to `beta2`

Result:

![image](https://cloud.githubusercontent.com/assets/1723815/19276764/73d7bafa-8fa5-11e6-9f84-f3cab654002f.png)

Should be `alpha beta2`

https://github.com/Microsoft/TypeScript/issues/11531

**Comment by jrieken** [comment]
The issue is that VS Code decides based on the word-definition what the box is populated with. However, the rename operation is being run with the position/offset - meaning it should yield a valid result. The UX is confusion and improvements (also to the API) are being tracked here: #7340
