### ISSUE TITLE
VS Code not reading jsconfig.json

### ISSUE THREAD

**Issue by malte-timmermann** [Microsoft/vscode#13597]
I also have the issue the jsconfig.json is not being read (see old/closed issue #703)

Tested with Visual Studio Code v1.5.3 and v1.7.0 insider, on Windows x64 (version 1607). No 3rd party antivirus, just Windows defender.

When using Sysinternals process monitor, I see that VS Code is getting some information about jsconfig.json (QueryAllInformationFile), but does NOT read the file (ReadFile).

Log when opening VS Code (with the current project) (reduced to jsconfig.json and my test file)

http://pastebin.com/GTKHPCZC

Log when actually opening jsconfig.json inside VS Code (so something like that should also happen when launching VS Code):

http://pastebin.com/je8Y3p4C

Not reading jsconfig.json unfortunately means that "go to definition" doesn't work for me with my own js files, what hinders me from switching from Netbeans to VS Code :(

I would really appreciate if this issue could be fixed. If you need further information, or my stripped down example, just let me know!

**Comment by malte-timmermann** [comment]
[vscode-test-prj-root.zip](https://github.com/Microsoft/vscode/files/524330/vscode-test-prj-root.zip)

In case it helps, here is my stripped down example. 

It has a complex folder hierarchy because it's part of a larger project. I tried using open folders with prj-root as well as with prj-root\ui\apps\com.mydomain\mycomponent for testing purpose, that's why there are two jsconfig.json files.

Problem 1:
When editing prj-root\ui\apps\com.mydomain\mycomponent\baseframework\app\baseapplication.js, it's not possible to go to the definition of Utils.doSomething()
Possible root cause: jsconfig.json not used

Problem 2: 
Quick-Open (Ctrl+P) utils.js only ignores the copies in "node_modules" (default), but nit in "ignore" (configured as exclude in jsconfig.json)
Possible root cause: jsconfig.json not used

**Comment by waderyan** [comment]
@malte-timmermann thank you for opening this issue. 

@bowdenk7 can I get your eyes on this one? OP seems to have set everything up correctly (see his zip file). If I try to trigger IntelliSense in node_modules/utils.js I get nothing. 

![image](https://cloud.githubusercontent.com/assets/2449568/19391328/f5968c8c-91e0-11e6-8e4f-f8940aeca2be.png)

**Comment by bowdenk7** [comment]
Hey @malte-timmermann, unfortunately we are unable to resolve AMD modules at the moment. To resolve this, you would need to update your codebase to use either ES6 modules or commonjs modules. 

The other issue with this specific code sample is that we can't resolve the expando pattern either. For example:
```js
var Utils = {};
Utils.foo = function(bar) {return bar};

Utils.    //<------ we don't know function foo exists
```
To resolve this one, you would just need to declare object properties at declaration time as opposed to tacking them on later. Like this:
```js
var Utils = {
    foo: function(bar) {return bar};
}
```

Like Wade said, we really appreciate you taking the time to open this issue. It helps us **a lot**. If you are interested in chatting more or trying to convert some of your code, I would be happy to help.

**Comment by malte-timmermann** [comment]
Hi bowdenk7,

thanks for looking into this. 

Too bad that VS Code wont support this, as this works fine in Netbeans, and changing code is not an option.

Given that ES6 is currently not used by most people developing web apps - really no chance to support it?

At least you wrote "at the moment" - so there is hope?

Best regards
Malte.

**Comment by mjbvz** [comment]
Amd module support is being tracked here: https://github.com/Microsoft/TypeScript/issues/6942

I believe the properties issues is now being tracked here: https://github.com/Microsoft/TypeScript/issues/7632

Closing as upstream
