### ISSUE TITLE
Improving the default SCM user experience

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#135992]
## Problem

This is a continuation of https://github.com/microsoft/vscode/issues/110882#issuecomment-928784945. One of the areas of friction that I see in our default SCM experience is how the actions and flows of staging => committing > pushing happen in different areas of the UI (primarily pushing). Additionally, it's not always immediately clear why the "commit" action is above the input when in most forms (even in the GHPR extension) has them below, not to mention that the ✅ takes some time to get used to.

<img width="370" alt="CleanShot 2021-10-27 at 15 47 30@2x" src="https://user-images.githubusercontent.com/35271042/139158257-ee55ee81-aca8-440f-b1a0-41624c1304e8.png">

## Proposal

What if instead of making the sync actions live in the status bar we updated the default view to contain these actions and to keep with the hierarchy of "bottom" to "top" view. This means some actions would need to be re-arranged. This proposal aims to:
- Moves the commit action to a primary action below the input
- Adds the sync actions above the commit input box (and spaced between to allow for longer branch names and a consistent hit target)
- Also adds the branch next to sync to be conveniently located never the rest of the scm actions
- Allow for this view to be toggle off via a setting (to accommodate those who prefer less UI)

<img width="353" alt="CleanShot 2021-10-27 at 16 04 53@2x" src="https://user-images.githubusercontent.com/35271042/139159857-0f057592-5e86-4b6b-942d-7e31ef0fb34b.png">

https://user-images.githubusercontent.com/35271042/139158645-5b73bc7e-392f-44ff-85a8-2363c7ccd676.mp4

**Comment by heartacker** [comment]
@misolori could you please consider about the `amend` workflow。
just like VS, that is great have some UX like VS
![gitamend](https://user-images.githubusercontent.com/1876302/141087887-5ae5bd50-7837-414b-8e63-9cb51c2e9645.gif)

**Comment by gjsjohnmurray** [comment]
Button text is "Commit to main" but placeholder says "commit **on** main". I suggest the placeholder text gets changed.

**Comment by eamodio** [comment]
In general, I like it. I'd like it even more if the commit button was a drop-down button - where you could choose other commit options, e.g. amend and maybe commit & push. The button text should also reflect the auto-push setting imo.

**Comment by misolori** [comment]
@eamodio so something along the lines of (if you had previously selected commit & push):

<img src="https://user-images.githubusercontent.com/35271042/144275652-505cef21-9bbf-452a-b66c-439eede2a52a.png" width="344">

**Comment by lszomoru** [comment]
I think that the button should always have the "Commit" label and that should be the action if you press on it.
Expanding the dropdown should reveal the extra commands, and picking any of them should perform the action.

**Comment by eamodio** [comment]
I mostly agree with @lszomoru that the main button should be commit (though imo it should reflect the commit vs commit and push setting). And then drop-down would provide access to other commit related operations (amend etc)

**Comment by lszomoru** [comment]
Linking comment https://github.com/microsoft/vscode/issues/136275#issuecomment-1014163311 to adopt the dropdown for the `Sync` button as well to provide additional functionality.

**Comment by lszomoru** [comment]
Today's Insiders release (2022-06-27) contains a new `Commit` action button. Give it a try and let us know your feedback.

**Comment by heartacker** [comment]
and about amend
> In general, I like it. I'd like it even more if the commit button was a drop-down button - where you could choose other commit options, e.g. amend and maybe commit & push. The button text should also reflect the auto-push setting imo.



> @misolori could you please consider about the `amend` workflow。 just like VS, that is great have some UX like VS ![gitamend](https://user-images.githubusercontent.com/1876302/141087887-5ae5bd50-7837-414b-8e63-9cb51c2e9645.gif) [ ](https://user-images.githubusercontent.com/1876302/141087887-5ae5bd50-7837-414b-8e63-9cb51c2e9645.gif)

**Comment by heartacker** [comment]
Several times I Click the commit button， there is no respon, and I realize we have to add file frist.

so, is it better to grayout/disenable the commit button and give tip for guiding user to add first until added, if the `smartCommit `and `SuggestSmartCommit` are both off 

![image](https://user-images.githubusercontent.com/1876302/176317099-7e1e13fc-5396-439f-9760-ca57f28c8d58.png)

ex: 
1. We usually turn off the `suggest smart submit` prompt, because we notice that the prompt make teammate(s) easy to select `always`(enable smartCommit), after that they will commit all file(so many dummy files) 
2. we have to disable `smartCommit` otherwise some of them will commit all files. 😢

**Comment by misolori** [comment]
Closing this since we launched this in the last iteration https://code.visualstudio.com/updates/v1_69#_commit-action-button-for-git-repositories

<img width="477" alt="CleanShot 2022-08-04 at 09 32 39@2x" src="https://user-images.githubusercontent.com/35271042/182903424-bdd896d5-6d65-4f19-a986-9dc1d907d0ba.png">
