### ISSUE TITLE
"Path must be a string. Received null" in Git view

### ISSUE THREAD

**Issue by arggh** [Microsoft/vscode#13598]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:28:55.412Z)
- OS Version: Darwin x64 15.6.0
- Extensions: HookyQR.beautify-0.4.0, abusaidm.html-snippets-0.0.16, cssho.vscode-svgviewer-1.2.0, dbaeumer.vscode-eslint-1.0.7, robertohuertasm.vscode-icons-3.0.3, vuhrmeister.vscode-meteor-0.1.1

Steps to Reproduce:

1. Open a project that's using Git
2. Make change to some file + save
3. Open Git view
4. Click on the file with changes to view diff

Prompted with this error message: `Path must be a string. Received null`.

I started to get these prompts after the latest update. Doesn't happen with all my projects, just some.

**Comment by nguymin4** [comment]
Duplicated to #13496

**Comment by arggh** [comment]
....I started posting this yesterday and double checked that it hasn't been reported already, but then forgot about it until now. Closing.
