### ISSUE TITLE
Run odoo application can't stop or restart

### ISSUE THREAD

**Issue by hulb** [Microsoft/vscode#13594]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:28:55.412Z)
- OS Version: Darwin x64 16.0.0
- Extensions: donjayamanne.python-0.4.1

Steps to Reproduce:

1.set a breakpoint
2.run debug mode
3.hit the breakpoint
4.restart the debug
5.it shows the address my web application used before is already in use.It tells me that the previous process doesn't end properly.

**Comment by isidorn** [comment]
What language are you trying to debug? Node?
Can you share your workspace on github so we look into this issue?

**Comment by hulb** [comment]
No,not node,python,in fact,it's odoo application.my luanch setting is:
{
            "name": "odoo",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "/Users/xxx/.virtualenvs/odoo/bin/python",
            "program": "/Users/xxx/Documents/workspace/code/yy/start",
            "args": [
                "-c",
                "/Users/xxx/Documents/workspace/code/yy/openerp-server.conf"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
and I'm using virtualenv,the python version is 2.7.11,do you need more information?I don't know what else you may want to know, thanks

**Comment by isidorn** [comment]
Can you please file this issue against the python extension here
https://github.com/DonJayamanne/pythonVSCode
Thanks!

**Comment by hulb** [comment]
ok, thank you~

**Comment by hulb** [comment]
[https://github.com/DonJayamanne/pythonVSCode/issues/376](url)
