### ISSUE TITLE
"Run VS Code outside the Developer Command Prompt" instructions in documentation do not work

### ISSUE THREAD

**Issue by cncz42** [microsoft/vscode#135994]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.61.2
- OS Version: Windows 11 Pro 22000.258

Steps to Reproduce:

1. Create c++ code and install msvc as specified in [this documentation](https://code.visualstudio.com/docs/cpp/config-msvc)
2. Amend tasks.json according to [this section](https://code.visualstudio.com/docs/cpp/config-msvc#_run-vs-code-outside-the-developer-command-prompt)
3. Hit ctrl+shift+b
4. Code doesn't compile, showing the error:
 `'C:/Program' is not recognized as an internal or external command,
operable program or batch file.
The terminal process "cmd.exe /C "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools/VsDevCmd.bat" && cl.exe /Zi /EHsc /Fe: "c:\Users\cncz4\OneDrive\Code Projects\CppTest\test.exe" "c:\Users\cncz4\OneDrive\Code Projects\CppTest\test.cpp"" terminated with exit code: 1.` 
It does compile correctly when run out of a developer command prompt and the bat is in the right path, so either there's an obscure configuration error on my end or that documented tasks.json edit is wrong/out of date.

**Comment by raz0r89** [comment]
I met the same issue too.
OS: Windows 10 Professional Edition (Simplified Chinese)
Vs Code version: 1.62.3
Repro steps are same as @cncz42 's

**Comment by alexr00** [comment]
I still can't reproduce this when I copy verbatim from https://code.visualstudio.com/docs/cpp/config-msvc#_run-vs-code-outside-the-developer-command-prompt.

If you make a mistake while copying then you could see the described error. Note that the line in question has `\"` in it:
```jsonc
[
    "\"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools/VsDevCmd.bat\"", // this is correct
    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools/VsDevCmd.bat" // this is incorrect
]
```

**Comment by drakmaniso** [comment]
I have the same issue ("'C:/Program' is not recognized as an internal or external command"). The path I use *does* contain `\"`:

```
	"windows": {
		"options": {
			"shell": {
				"executable": "cmd.exe",
				"args": [
					"/C",
					// The path to VsDevCmd.bat depends on the version of Visual Studio you have installed.
					"\"C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/Tools/VsDevCmd.bat\"",
					"&&"
				]
			}
		}
	},
```

The workaround proposed by @cncz42 doesn't work for me. Typing `cmd /C "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/Tools/VsDevCmd.bat"` directly in a terminal works correctly.

**Comment by Guyutongxue** [comment]
I ran into this problem too. But eventually found out that I had misspelled the path. If the text in quotes passed into `cmd /C` is not an executable file or script, then the pair of quotes will not be preserved.

**Comment by drakmaniso** [comment]
Unfortunately, in my case, the path is correct, and corresponds to the actual script. The exact same path works if copy-pasted into a terminal.
The other parts of the build task are probably correct too, since the task works if vscode is started from a developper command prompt.
