### ISSUE TITLE
Clean up refreshProperty generics

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#136041]
```ts
	async refreshProperty<T extends ProcessPropertyType>(type: T): Promise<IProcessPropertyMap[T]> {
		await this.processReady;
		return this._processManager.refreshProperty(type);
	}

	async updateProperty(type: ProcessPropertyType, value: any): Promise<void> {
		return this._processManager.updateProperty(type, value);
	}
```

**Comment by meganrogge** [comment]
still not sure why the type check is necessary
https://github.com/microsoft/vscode/blob/ac04bdd298b673f029387d33939a81891d9f2bf9/src/vs/platform/terminal/node/terminalProcess.ts#L424

**Comment by meganrogge** [comment]
what should these do for the terminalPRocessExtHostProxy?

https://github.com/microsoft/vscode/blob/ac04bdd298b673f029387d33939a81891d9f2bf9/src/vs/workbench/contrib/terminal/browser/terminalProcessExtHostProxy.ts#L172-L178
