### ISSUE TITLE
Quote matching when writing a comment (JavaScript)

### ISSUE THREAD

**Issue by M4v3R** [Microsoft/vscode#13607]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:28:55.412Z)
- OS Version: Darwin x64 16.0.0
- Extensions: PaulOlteanu.theme-railscasts-1.0.0, bogdan-sinitsa.theme-dark-monokai-0.3.0, designbright.theme-suicidesquad-0.1.0, donjayamanne.githistory-0.1.0, humao.rest-client-0.8.5, msjsdiag.debugger-for-chrome-1.1.0, qinjia.seti-icons-0.1.1, vscodevim.vim-0.3.7, vuhrmeister.vscode-meteor-0.1.1

Steps to Reproduce:

1. Create a JavaScript File
2. Start writing a comment (either single-line with `//` or multi-line with `/*`
3. Type a single quote: `'`

The single quote will be duplicated because of the quote matching feature. This should not happen when writing a comment (so you can write proper english 😄)

**Comment by waderyan** [comment]
@M4v3R thank you for opening this issue. 

@dbaeumer this seems like a basic editing feature... or is this something the language service provides?

**Comment by dbaeumer** [comment]
Yes, basic language feature.

**Comment by waderyan** [comment]
@isidorn can you advise on who this should go to?

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/8850
