### ISSUE TITLE
color brackets display error

### ISSUE THREAD

**Issue by ChiShouWu** [microsoft/vscode#136088]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.61.2
- OS Version: MacOS 11.5.2

Steps to Reproduce
<img width="274" alt="截圖 2021-10-29 下午2 03 26" src="https://user-images.githubusercontent.com/30040102/139383838-5a61feec-d8e9-4423-a1e6-b805a229b043.png">
:

1.Just typing

**Comment by hediet** [comment]
Thanks for reporting this bug!
Can you share the contents of the document? I cannot reproduce the bug just from the screenshot.
