### ISSUE TITLE
bracket pair unexpectedBracket foreground not always applied

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#136052]
I have set `"editorBracketHighlight.unexpectedBracket.foreground": "#ff0000",`, but I see at end of line 129 that the paren isn't colored red:
![image](https://user-images.githubusercontent.com/8586769/139317097-2282c9a5-8398-4653-9dfc-4fffd8162ed5.png)

https://github.com/microsoft/vscode-github-triage-actions/blob/fc9badb5421470d905e571e14f34fd1ab33e426f/classifier-deep/apply/apply-labels/index.ts#L129

I cant repro in other similar situation, seems to be some sort of edge case where that particular paren isn't identified as being in error.

**Comment by hediet** [comment]
This is as designed.
The unexpected brackets are in line 131. The closing `)` in line 129 closes the `(` from the same line. The `{` in line 129 is marked as unclosed.

Maybe unclosed brackets should also colored red?

**Comment by Cloud7050** [comment]
> This is as designed. The unexpected brackets are in line 131. The closing `)` in line 129 closes the `(` from the same line. The `{` in line 129 is internally marked as unclosed.
> 
> Maybe unclosed brackets should also be colored red?

![image](https://user-images.githubusercontent.com/44526554/148307436-3cbd5404-669e-4a3b-8832-704f95b3ce1b.png)

I feel it would be helpful to also mark the unclosed brackets as red, not just the unexpected ones, which would help differentiate them from closed ones.
