### ISSUE TITLE
Crash when running from terminal

### ISSUE THREAD

**Issue by maxlein** [microsoft/vscode#136033]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Go to folder with a git repository
2. `code .`  

If I open vs code from shortcut, it opens, but I see a popup saying something crashed.   
And my git repo is not detected as git repo.

Crash report:  

[vscode-crash.zip](https://github.com/microsoft/vscode/files/7434565/vscode-crash.zip)

**Comment by deepak1556** [comment]
Crash in jemalloc, VSCode uses a custom memory allocator from chromium, looks like a bad library injection via `LD_PRELOAD`.
