### ISSUE TITLE
New Window Creation Is Slow On M1 Max

### ISSUE THREAD

**Issue by brianmichel** [microsoft/vscode#136050]
Issue Type: <b>Performance Issue</b>

I recently got a new 14" MacBook Pro with an M1 Max and I noticed that the time it takes VSCode to create a new window is 4-6 seconds which seems a bit high. These rough numbers were taken after I disabled all my extensions so it seems like something specific to VSCode itself maybe?

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 21.0.1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|21, 17, 18|
|Memory (System)|64.00GB (6.36GB free)|
|Process Argv|--crash-reporter-id c5eb5271-96c8-4e02-87c1-60f58bef7d8a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    8	   197	 13460	code main
    2	    66	 13463	   gpu-process
    0	     0	 13466	   utility
    8	   197	 13847	   shared-process
    0	    66	 13848	     ptyHost
    0	     0	 14485	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    4	   328	 14437	   window (Untitled-1)
    0	   131	 14438	     extensionHost
    2	    66	 14479	     searchService
   84	    66	 14483	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by brianmichel** [comment]
I've followed the instructions on the link you've shared so please let me know if there's more I can help dig into. I wanted to note that a few of the instructions listed didn't work, or actively created a crash within the application (I'll note which below).

### Running `code --status`
```
Version:          Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS Version:       Darwin x64 21.1.0
CPUs:             Apple M1 Max (10 x 24)
Memory (System):  64.00GB (8.36GB free)
Load (avg):       2, 3, 2
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id c5eb5271-96c8-4e02-87c1-60f58bef7d8a
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  metal:                      disabled_off
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %	Mem MB	   PID	Process
    4	   197	  8554	code main
    1	    66	  8557	   gpu-process
    0	    66	  8559	   utility
    0	   197	  8976	   shared-process
    0	    66	  8977	     ptyHost
    0	   262	  9397	   window (Untitled-1)
    0	   131	  9399	     extensionHost
```

### Running `code --prof-startup`
```
FAILED to start profiling for 'extHost' on port '25099'
```

This ended up launching a new version of VS Code in my dock, but no windows ever loaded in that instance of the application.

### Profiling the render process
Please find the attached render process cpuprofile from the developer tools menu. The steps I used to profile this are as follows:

1. Start profiling
2. Launch 2 new windows through keyboard commands

[javascript-profile.cpuprofile.zip](https://github.com/microsoft/vscode/files/7444032/javascript-profile.cpuprofile.zip)

### Profiling VS Code ([defined here](https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-sluggish))
Following these instructions and trying to create a new window consistently produced a crash for me. Please see the attached log.

[vscode-profile-newwindow-crash.txt](https://github.com/microsoft/vscode/files/7444057/vscode-profile-newwindow-crash.txt)

—

I also wanted to see if this issue reproduced on the insiders edition of the app so I downloaded the Apple Silicon and Universal binary for the insiders edition of the application and I don't see a similar lag! It seems this issue is being significantly mitigated in a future version of the code.

This got me to just reinstall my main version of VS Code (I tried both the Apple Silicon and Universal binary) and the issue has gone away (yay!), but I can't say why. 

I suppose something could have gone poorly when migrating my data from my old computer to this one, but a fresh install seems to resolve the issue. I'm happy to help keep debugging if you'd like, but I'm not sure the issue is with VS Code at this point.

**Comment by deepak1556** [comment]
Thanks for confirming, missed that you were running x64 version. The slowdown can be attributed to rosetta translation, can you share the numbers from https://github.com/microsoft/vscode/wiki/Performance-Issues#read-the-startup-timers

Will merge this to https://github.com/microsoft/vscode/issues/132598 eventually as we don't recommend running the x64 version on M1
