### ISSUE TITLE
incorrect/inconsistent ANSI rendering in integrated terminal for reverse video+dimmed

### ISSUE THREAD

**Issue by T3sT3ro** [microsoft/vscode#136029]
Issue Type: <b>Bug</b>

- open integrated terminal
- print the following string in terminal (colors must be enabled)

( is escape sequence - either insert with `Ctrl+V`, `Esc` or use `\e` with `echo -e`)
```[0;92;49mtest[0;2;92;49mtest[0;7;92;49mtest[0;2;7;92;49mtest[0m```

This is how it looks in order in gnome-terminal, xterm and in vscode:
![ansi colors](https://i.imgur.com/aeB7dty.png)

the value of `$TERM` in vscode is `xterm-256color`

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:58:13.605Z)
OS version: Linux x64 5.4.0-89-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|19.43GB (3.31GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 134570e7-1a1d-479b-a63b-30f0e98adab2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (75)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
overtype|ada|0.2.0
numbered-bookmarks|ale|8.1.0
ocaml-formatter|bad|1.14.0
lit-html|bie|1.11.1
markdown-mermaid|bie|1.12.1
vscode-intelephense-client|bme|1.7.1
ink|bru|1.3.1
better-toml|bun|0.3.2
vscode-glsllint|CAD|1.5.1
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
glsl-canvas|cir|0.2.14
gitignore|cod|0.7.0
vscode-zonefile|Com|0.0.4
doxdocgen|csc|1.3.2
vscode-svgviewer|css|2.0.0
c-cpp-compile-run|dan|1.0.15
vscode-markdownlint|Dav|0.44.4
vscode-eslint|dba|2.2.2
javascript-ejs-support|Dig|1.3.1
gitlens|eam|11.6.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.23
code-runner|for|0.11.6
reasonml|fre|1.0.38
todo-tree|Gru|0.0.214
vscode-drawio|hed|1.6.2
latex-workshop|Jam|8.21.1
vscode-graphviz|joa|0.0.6
presentationmode|jsp|1.1.5
intellij-idea-keybindings|k--|1.4.5
vscode-cudacpp|kri|0.1.1
autoconf|mae|0.1.0
marp-vscode|mar|1.4.3
Kotlin|mat|1.7.1
rust-analyzer|mat|0.2.792
vscode-docker|ms-|1.17.0
csharp|ms-|1.23.16
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.3
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.202.5
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.4
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.7.1
debugger-for-chrome|msj|4.13.0
gradle-language|nac|0.2.3
linux-desktop-file|nic|0.0.18
vscode-versionlens|pfl|1.0.9
vscode-unitymeta|PTD|0.0.7
vscode-yaml|red|1.1.0
LiveServer|rit|5.6.1
bash-debug|rog|0.3.9
vscode-scss-formatter|sib|2.3.2
shopify-liquid|sis|2.3.0
shader|sle|1.1.5
vscode-3dviewer|sle|0.2.2
vscode-multiclip|sle|0.1.5
datapack-language-server|SPG|3.3.14
rewrap|stk|1.14.0
code-spell-checker|str|2.0.10
lua|sum|2.4.7
pdf|tom|1.1.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.14
vscode-gradle|vsc|3.8.1
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0
vscode-proto3|zxh|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by kenpozzsd** [comment]
****
