### ISSUE TITLE
OSX VS Code fails to update

### ISSUE THREAD

**Issue by designnotdrum** [Microsoft/vscode#13604]
- VSCode Version: 1.5.3
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Launch VS Code
2. Get prompted to update & restart VS Code
3. Click "Update Now"
4. VS Code terminates
5. VS Code does not update
6. Manually restart VS Code
7. Verify that version has not changed

**Comment by designnotdrum** [comment]
I will add that this is not a new problem - I have experienced it for the past several releases, since at least March 2016.

The only solution I have found is to manually download the latest release and install.

**Comment by Nikki1993** [comment]
Can't reproduce it on macOS 10.12, successfully installed 1.6 on top of 1.5.3 update. Have you tried running permission check in macOS disk utility?

**Comment by designnotdrum** [comment]
@Nikki1993 - I just repaired all permissions and am still encountering the same issue.

**Comment by joaomoreno** [comment]
#7426

**Comment by sheljohn** [comment]
It looks like this issue persists (#7426 is still in the backlogs).

In the meantime, you can update manually with the following steps:
 - Detach the VSCode icon(s) from your Dock if any (Right click - Options - Remove from dock).
 - Locate the folder(s) `Visual Studio Code.app`. Most likely in `/Applications`, but could be anywhere else, depending on where you put it/them (eg `~/local/app`), and there can be several ones in different places.
 - Delete this/these folder(s). **Your preferences will not be affected, as these should be stored separately in `~/.vscode/`.**
 - Download the latest version from [the official webpage](https://code.visualstudio.com/Download), uncompress it, and move the `.app` folder wherever you like.
 - Open a terminal, and type the following commands:
```
xattr -srd com.apple.quarantine "/path/to/VSCode"
command ls -alR@ "/path/to/VSCode" | grep quarantine -B 1
```
The first command removes the quarantine attributes from everything within the `.app` folder, the second makes sure no quarantine attribute is left; there should be **no output** to the second command. Obviously you should replace `"/path/to/VSCode"` with wherever you put the `.app` folder.
 - Finally you can drag the `.app` folder to your Dock, if you want to have it there.
