### ISSUE TITLE
right click automatically selects options after installing python intellisense plugin.

### ISSUE THREAD

**Issue by jithinthomas0011** [microsoft/vscode#136016]
Does this issue occur when all extensions are disabled?: No .

- VS Code Version: 1.61.2
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1.Install Python intellisense (Pylance) plugin by Microsoft .
2. Right click anywhere on any file in the workspace . It automatically selects some option from menu list.

**Comment by jithinthomas0011** [comment]
![recrd](https://user-images.githubusercontent.com/34642677/139831814-2f223264-950b-4d44-8ac3-ad2ab9a732ff.gif)

Found a similar issue here :- https://github.com/microsoft/vscode/issues/113175 .
Also when I reset the zoom level in Vs code, this issue seems to be not happening. But this is not a permanent fix , because I need to have a custom zoom level. 
Previously i thought this issue started coming after I installed Python intellisense (Pylance) plugin , but now even if i uninstall it , the issue persists.

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/113175

**Comment by jithinthomas0011** [comment]
Hi, 
Before closing this ticket, can someone suggest a fix for this issue, as I'm not able to find any proper fix from other similar ticket as well (#113175) .

**Comment by sbatten** [comment]
@jithinthomas0011 the simplest fix is to use the custom title bar style. Since you are on Ubuntu it will not look native, but it will workaround this issue. `window.titleBarStyle` => `custom`

**Comment by jithinthomas0011** [comment]
@sbatten Thanks  .
