### ISSUE TITLE
Extensions getting corrupt

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode#13603]
- VSCode Version: 1.7.0-Insiders
- OS Version: Windows 10

It appears this started to happen on 10/6/2016. I have had some odd behavior occur to some of my extensions, and it appears at least one was corrupt in the process. Old versions of extensions are some how partially getting installed or having something odd go on with them. Here is an example of an extension.

- New Version: EditorConfig.EditorConfig-0.3.3 - Folder Modified 10/6/2016 at 3:00 PM (File Contents all say last modified 9/29/2016 2:32 PM)
- Old Version: EditorConfig.EditorConfig-0.3.1 - Folder Modified 10/6/2016 at 3:05 PM

This Extension is broken and you get errors about `EditorConfig.EditorConfig-0.3.1\package.json` failing to be read and `EditorConfig.EditorConfig-0.3.3/out/src/editorConfigMain` unable to be activated because it is missing. What is odd about this, is the directory `EditorConfig.EditorConfig-0.3.3` shows modified 10/6/2016 at 3:05 PM, but the contents show 9/29/2016 at 2:32 PM, which makes sense to me since the extension was update 9/24. So it appears that the extension was some how broken after it was already installed. It is missing the `out` directory, but if I look in `EditorConfig.EditorConfig-0.3.1` it only has `Node_Modules` and `out`  directories.

This is the only module that appears to have fully broken, but I have about 8 total that error that have files dated 10/6/2016 at 3:05 PM. The old version directories only have a couple directories left in them, like `Node_Modules` and `out` or `Node_Modules` and `dist` or `file-types` and `lib` etc, so Code errors when it can't find the `package.json`

Steps to Reproduce:

1.  "extensions.autoUpdate": true
2.  "window.reopenFolders": "all"

**Comment by joaomoreno** [comment]
There is definitely something wrong. We broke the removal of deprecated extensions and we can improve the detection of deprecated extensions at load time too.

**Comment by joaomoreno** [comment]
**Repro steps**

Have an old version of an extension laying around and remove its `package.json`. Eg:

```
EditorConfig.EditorConfig-0.3.0  // remove the package.json
EditorConfig.EditorConfig-0.3.1
```

When launching, Code shouldn't attempt to load the extension and should successfully remove the folder.

**Comment by gerane** [comment]
I've kept these all in a broken state so I can test the eventual fix. Thanks!
