### ISSUE TITLE
cell metadata appears changed in liveshare session

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#136001]
- Open a notebook
- Start a liveshare session
- A guest joins the liveshare session
- Edit and run some cells
- The notebook shows up in the git diff with a `vsls_cell_id` key that appears removed

![image](https://user-images.githubusercontent.com/323878/139183317-035c9266-0e8d-4526-a3b3-11523a17df50.png)

**Comment by rebornix** [comment]
This should be marked as transient.

**Comment by alyssajotice** [comment]
Previous discussion: https://github.com/microsoft/vscode/issues/120127
