### ISSUE TITLE
Unable to open any file from a particular workspace from terminal

### ISSUE THREAD

**Issue by anishmittal2020** [microsoft/vscode#136094]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.61.2
- OS Version: Ubuntu 20.04.2

# Description

I am not able to open any file from a particular workspace from terminal. Also I am unable to open that particular workspace. Although I am able to open those file using other editors. Restarted my computer, but I am facing the same problem.

Since, its strange, I suspect that some cache has got corrupted. How can I clear all cache (without deleting any extension or vscode settings)?

# What I tried?

```bash
cd "${HOME}/.config/Code"
rm CachedData/* Cache/* User/workspaceStorage/*
```

# Help

How can I delete all kinds of cache stored by vscode except extension and settings?

**Comment by anishmittal2020** [comment]
@IllusionMH 

> What error or behavior do you see when you try to do that?

Nothing happens, the file won't open. No error. Even when opening from terminal like `code "${FilePath}"`, nothing happens!

> Can you open VS Code and than open that workspace trough UI?

No

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by anishmittal2020** [comment]
@bpasero  I would like to substantiate my issue with recent observations:

I start a workspace from cron, when my Ubuntu 20.04 reboots. I can see that the vscode opens the workspace but without GUI  as can be seen in the following when I check the status:

```bash
$ code -s
(code:12560): Gtk-WARNING **: 09:57:56.472: Theme parsing error: gtk.css:10:4: Expected semicolon

(code:12560): Gtk-WARNING **: 09:57:56.472: Theme parsing error: gtk.css:12:4: Expected semicolon
(code:12560): Gtk-WARNING **: 09:57:56.500: Theme parsing error: gtk.css:8916:21: Not using units is deprecated. Assuming 'px'.
Version:          VScode 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-12T00:22:43.314Z)
OS Version:       Linux x64 5.4.0-90-generic
CPUs:             Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 1275)
Memory (System):  7.67GB (2.12GB free)
Load (avg):       13, 10, 5
VM:               0%
Screen Reader:    no
Process Argv:     --ms-enable-electron-run-as-node --new-window --extensions-dir /home/nikhil/Documents/Git/Life/PersonalManagement/PersonalManagementSrc/Workspace/Linux/.Ws/Extension /home/nikhil/Documents/Git/Life/PersonalManagement/PersonalManagementSrc/Workspace/Linux/.Ws/Linux.gen.code-workspace
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     enabled_on
                  rasterization:              disabled_software
                  skia_renderer:              enabled_on
                  video_decode:               disabled_software
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %   Mem MB     PID  Process
    0      149    2928  code main
    0       39    2931     zygote
    0      259    2993       gpu-process
    0       24    3030         broker
    0       39    2933     zygote
    0        8    2938       zygote
    0       55    3044     utility
    0      220    3108     window (Linux.gen (Workspace) - DisplayFunctions.sh)
    0      149    3526       extensionHost
    0       79    8078         electron_node server.js 
    0        0   12562         git status -z -u
    0       71    3541       watcherServiceParcel
    0      118    3509     shared-process
    0       71    3557       ptyHost
    0        8    3769         /bin/bash
    0        8    8455         /bin/bash
    0        0   12543           sh /usr/bin/code -s
    0       63   12548             /usr/share/code/bin/../code /usr/share/code/bin/../resources/app/out/cli.js --ms-enable-electron-run-as-node -s
    0      118   12560               /usr/share/code/code --ms-enable-electron-run-as-node -s
    0       39   12565                 zygote
    0       63   12595                   gpu-process
    0       24   12601                     broker
    0       39   12566                 zygote
    0        8   12568                   zygote
    0       47   12610                 utility
    0        0   12621                 /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0        0   12622                   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0      212    8399     window (VScode)
    0      110    8429       extensionHost

Workspace Stats: 
|  Window (Linux.gen (Workspace) - DisplayFunctions.sh)
|    Folder (TestRepository): 151 files
|      File types: md(17) 0(11) ~1~(11) trashinfo(11) tsv(9) json(9) mp4(6)
|                  ~2~(6) ~3~(6) ~4~(6)
|      Conf files:
|    Folder (DotFiles): 939 files
|      File types: py(70) json(69) md(44) log(40) wav(33) desktop(32)
|                  backup(30) mp3(30) sh(27) txt(23)
|      Conf files: settings.json(3) package.json(1)
|    Folder (Backintime): 169 files
|      File types: md(15) 0(11) markdown(9) ~1~(9) trashinfo(9) tsv(8) log(8)
|                  json(7) 1(4) html(4)
|      Conf files:
|    Folder (Architecture): 9644 files
|      File types: md(3301) png(489) ~1~(372) ~2~(247) txt(221) ~3~(184)
|                  sh(165) html(159) ~4~(138) ~5~(107)
|      Conf files: makefile(16) package.json(3) grunt.js(1)
|    Folder (GitScripts): 1232 files
|      File types: md(273) sh(60) js(58) png(55) json(54) gif(53) markdown(31)
|                  txt(29) diff(24) ~1~(22)
|      Conf files: package.json(8) tslint.json(2) launch.json(2)
|                  webpack.config.js(2) settings.json(1) tasks.json(1)
|    Folder (AmazingNotes): 2602 files
|      File types: md(345) sh(129) js(82) markdown(70) trashinfo(64) pdf(60)
|                  html(56) css(54) ~1~(49) png(47)
|      Conf files: makefile(29) package.json(6) dockerfile(2) launch.json(1)
|                  settings.json(1) gulp.js(1)
|      Launch Configs: bashdb(3) python
```

And, since the vscode is running (with the workspace), I am unable to start the same workspace again (even though it does not let me access its GUI).

So, is it possible to show the GUI?

**Comment by bpasero** [comment]
Is it intentional that you see no GUI or a bug?

//cc @deepak1556 on the GTK warnins

**Comment by deepak1556** [comment]
> I start a workspace from cron

What command are you using to launch vscode from the cron ? Also, are you using snap or deb installation ?

**Comment by anishmittal2020** [comment]
I am sorry, I corrected my last comment. 

I start vscode using systemd (user daemon) and not cron.

```
[Unit]
Description=Editor Service

[Service]
ExecStart=/bin/bash -c '. "$0" && exec "$@"' %h/.bashrc.d/Custom.bash %h/.config/MySettings/WsBeforeShutdown.sh
Type=forking
Restart=on-failure
RestartSec=10
SyslogIdentifier=EditorService

[Install]
WantedBy=graphical-session.target
```

This executes bash script `~/.config/MySettings/WsBeforeShutdown.sh`, which executes Vscode with the path to the workspace last opened before Shutdown:

`code /home/nikhil/Documents/Git/Life/PersonalManagement/PersonalManagementSrc/Workspace/Linux/.Ws/Linux.gen.code-workspace`

**Comment by deepak1556** [comment]
Are you able to open other GUI application via systemd with that configuration ?

> This executes bash script ~/.config/MySettings/WsBeforeShutdown.sh, which executes Vscode with the path to the workspace last opened before Shutdown:

VSCode should restore the workspace it had open when re-launching the application from the dock or cli. Can you avoid using a systemd setup to perform this operation if it is the only use case ?

**Comment by anishmittal2020** [comment]
1. Yes I am able to run Firefox, Thunderbird with similar scripts.
2. Actually my script does a little bit more stuff. If there were multiple workspaces it opens both. Also, it populates the PATH environment variable differently depending on the workspaces.

**Comment by anishmittal2020** [comment]
> Also, are you using snap or deb installation ?

It is installed using deb file

**Comment by bpasero** [comment]
@anishmittal2020 can you clarify why you need to start VSCode with a `cron` job exactly?

**Comment by anishmittal2020** [comment]
@bpasero I start it with systemd as corrected  in my previous comment. I have also included the unit file.

I use it to start vscode automatically after reboot.

**Comment by bpasero** [comment]
@anishmittal2020 is there maybe another way on Linux to let an application run on startup that would ensure the UI is also visible?

**Comment by anishmittal2020** [comment]
@bpasero as I mentioned above I am able to use systemd to start other gui applications like Firefox, thunderbird. Also, sometimes the vscode gui starts perfectly, but other times there is no gui.

**Comment by bpasero** [comment]
Does it help if you configure `--disable-gpu` as argument to launching VSCode?
