### ISSUE TITLE
Signing in Microsoft account Failed !

### ISSUE THREAD

**Issue by ChenaniahShe** [microsoft/vscode#136080]
Issue Type: <b>Bug</b>

1. VSCode左下角账号图标，几乎每天都会显示Microsoft账号断开登录，Account图标角标显示“①”提醒登录账号。右下角“Notifications”中也有“Settings sync is suspend ...”的“Sign in”通知。
2. 点击“Sign in to sync settings”，然后点击上方出现的“Settings sync”对话框、点击之前Microsoft 账号记录之后，左下角“Account”图标和右下角“Notifications”图标，仍显示账号没有登录。
3. 登录失败。

The detail of this issue:
1. Notification Message: “Settings sync is suspended because of successive authorization failures. Please sign in again to continue synchronizing”.
2. Microsoft VS Code shows one notification message of "Sign in to Sync Settings" almost everyday, even if I never log out my account.
3. After I click on the "Sign in to Sync Settings" in the Accounts, or "Sign in" in the notification box, and click the previous login records in Command Palette, there are still the notification message popping up, showing sign in account failed.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by ArtVS** [comment]
> I'm getting same issues as well ![image](https://user-images.githubusercontent.com/40742924/139470943-bb2f184a-17fa-4497-b22b-40238e2ea856.png)

Same here

**Comment by johntony366** [comment]
Been facing the same issue for the last few days

**Comment by modscleo4** [comment]
It's happening for me too on KDE Neon and Arch Linux (latest release), using Microsoft Account

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/133201
