### ISSUE TITLE
Allow to open multiple files from file quick open

### ISSUE THREAD

**Issue by softcraft-development** [Microsoft/vscode#13608]
When I open Go To File (typically with Ctrl-P), I'm presented with a list of files (fuzzy filtered by the characters I type if applicable). I can arrow through the list and press Enter to open the file.

What I'd like to be able to do is Shift-Arrow to select multiple files and then press Enter to open *all* of them.

Here's my use case: I want to add code/functionality to an existing file while also adding tests to it's corresponding test file. The code file and test file both have nearly identical names (the test file typically having `.spec` in the file name), and so are conveniently listed at the top of the list when I enter characters into the fuzzy filter. However, since I can only open a single file, I have to repeat the entire process to open both files.

Shift-Arrow selection would eliminate the issue and improve the workflow. (Reusing the existing principles of multi-select, such as discontinuous selection with Ctrl-Space, would be nice, but is not required.)

- VSCode Version: 1.6.0 (and presumably earlier)
- OS Version: Windows 7 (and presumably all others)

**Comment by bpasero** [comment]
This landed: https://github.com/Microsoft/vscode/issues/13711
