### ISSUE TITLE
Issue opening directories with same name but different casing

### ISSUE THREAD

**Issue by DylanDmitri** [microsoft/vscode#136081]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.1
- OS Version: Windows 10 Pro  (19043.1288)

Steps to Reproduce:

1. Have two folders with the same name but different capitalization (eg. "foo" and "FOO")
2. Open one of them open in VS Code
3. From the command line, try to open the other in VS Code

It looks like your comparison check of "is this directory already open" ignores cases.

**Comment by bpasero** [comment]
Is this connecting to WSL or local?
