### ISSUE TITLE
Incorrect highlighting when colon is used inside yaml literal style

### ISSUE THREAD

**Issue by tnikodym** [Microsoft/vscode#13601]
- VSCode Version: 1.6.0
- OS Version: OS X El Capitan (10.11.6)

See the screenshot below. When a colon is used inside [literal content](http://www.yaml.org/spec/1.2/spec.html#id2795688) (indicated by | character), the entire line up to the colon is highlighted as a property. 

![screen shot 2016-10-12 at 16 27 17](https://cloud.githubusercontent.com/assets/19610642/19314007/cfe269a0-9098-11e6-94b5-46cb3438850f.png)

Note: I have not seen this issue in the previous version of VSCode.

**Comment by aeschli** [comment]
This issue was moved to textmate/yaml.tmbundle#17

**Comment by aeschli** [comment]
Looks like a limitation of TextMate.
Moving away from TextMate for yaml would be major investment and currently not planned.
