### ISSUE TITLE
Suggest widget message overflows in notebooks

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#136031]
* Be in a notebook editor
* trigger suggest so that it shows a message (loading or no results)
* :bug: the message overflows onto the border

<img width="312" alt="Screen Shot 2021-10-28 at 09 35 16" src="https://user-images.githubusercontent.com/1794099/139264796-d0e66586-db4c-4d8b-96fb-178a5c5f823f.png">

**Comment by IanMatthewHuff** [comment]
Verified. Looks good now.
![image](https://user-images.githubusercontent.com/812783/144507888-1885ce1f-e37c-4dc0-80e9-72a580ceff95.png)
