### ISSUE TITLE
Multiline test output is truncated at first newline

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#136036]
I'm appending multiline test output from my test runner with the `appendOutput()` message but only the top line is visible in VS Code.

Example (where `run` is a `TestRun` and `item` is a `TestItem`:

```
run.appendOutput(`this is a multiline\r\nmessage\r\n`, undefined, item);
```

This shows up like this:

<img width="862" alt="Screenshot 2021-10-28 at 15 07 55" src="https://user-images.githubusercontent.com/1078012/139272751-64ae192d-3f8f-4b12-81e5-3491b3f34442.png">

As far as I can see, there's no way for the user to expand this and see the full message.

**Comment by DanTup** [comment]
@connor4312 is this still likely to make the November release? I put in a workaround for this (splitting the lines up), but I think it's making things more confusing (https://github.com/Dart-Code/Dart-Code/issues/3704), but if I remove it, it's not possible to get to the output in the peek window.

**Comment by connor4312** [comment]
I was on vacation so didn't get to this. I'll take care of it this week or today but it won't be released until the end of Jan.

**Comment by connor4312** [comment]
![](https://memes.peet.io/img/21-12-5e352861-b238-4915-8d8b-49a201ad0d18.png)

**Comment by connor4312** [comment]
![](https://memes.peet.io/img/21-12-29c8d705-a601-4192-bfde-c62390daca04.png)

**Comment by Tyriar** [comment]
I reverted https://github.com/microsoft/vscode/commit/267c9f8d487a8554dc5189bd4baca70a31ef0e32 to fix the build:

```
[valid-layers-check] [build/lib/layersChecker.ts]: Reference to 'trimEnd' from '@types/node' violates layer '**/vs/**/browser/**' (/mnt/vss/_work/1/s/src/vs/workbench/contrib/testing/browser/testingOutputPeek.ts (1150,35)
```

https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=146620

**Comment by connor4312** [comment]
Fixed!

**Comment by connor4312** [comment]
@DanTup you may be able to help verify this 🙂

**Comment by DanTup** [comment]
@connor4312 yep, this seems fixed - although the experience of reading the output feels significantly worse in this split pane to me. Output from tests comes in events but usually many of them are related and you want to scan them all.

<img width="1242" alt="Screenshot 2022-01-25 at 09 25 22" src="https://user-images.githubusercontent.com/1078012/150949392-264519e1-2f50-4739-8097-4a7def410b09.png">

I think it would be better if the tree on the right didn't try to show the output at all and was just the runs, and then the left pane showed the full output?
