### ISSUE TITLE
在远程模式下使用 ctrl + / 注释大段代码会直接导致程序退出

### ISSUE THREAD

**Issue by lexgooo** [microsoft/vscode#136010]
Issue Type: <b>Bug</b>

打开 wsl 环境中的项目 -> 选中一大段代码 -> 使用 `ctrl + /` 快捷键注释这段代码。有机率会导致程序退出

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (4.16GB free)|
|Process Argv|--crash-reporter-id 7750bcb7-1de0-41b9-86e0-c5e64e336104|
|Screen Reader|no|
|VM|40%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|Memory (System)|12.37GB (8.09GB free)|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.4.0
color-info|bie|0.7.0
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.1
auto-close-tag|for|0.5.13
vscode-drawio|hed|1.6.2
vscode-simple-icons|Lau|1.16.0
vscode-language-pack-zh-hans|MS-|1.61.5
remote-wsl|ms-|0.58.4
material-icon-theme|PKi|4.10.0
js-jsx-snippets|sky|11.0.0
ayu|tea|1.0.5
open-in-browser|tec|2.0.0
vscode-ant-design-vue-helper|ant|1.0.6
markdown-preview-github-styles|bie|0.2.0
npm-intellisense|chr|1.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.2.2
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
auto-close-tag|for|0.5.13
code-runner|for|0.11.6
todo-tree|Gru|0.0.214
vscode-drawio|hed|1.6.2
iceworks-generator|ice|1.0.1
vscode-osu2|lxf|3.3.6
milkdown|mir|0.0.10
vscode-language-pack-zh-hans|MS-|1.61.5
azure-account|ms-|0.9.9
vetur|oct|0.35.0
postcode|roh|1.3.9
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|2.2.1
code-spell-checker|str|2.0.10
vscode-status-bar-format-toggle|tom|3.0.0
vscode-jumpy|wma|0.3.1

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by CodeCrazy-ywt** [comment]
### Title:
In remote mode, commenting a lot of code using `ctrl` + `/` will cause vscode to stop running.
### Content: 
1. Open a project in wsl.
2. Select a lot of code.
3. Press `ctrl` +`/` to comment this code out.
There are chances that vscode will stop working.

**Comment by aeschli** [comment]
For what editor language mode do you see it?

**Comment by alexdima** [comment]
@lexgooo It looks like you are using a lot of extensions that have been abandoned or that are know to cause crashes. e.g. `bracket-pair-colorizer`, `bracket-pair-colorizer2`, `auto-close-tag`. Does this crash reproduce when disabling all extensions?
