### ISSUE TITLE
Intellisense stops after setting sync.

### ISSUE THREAD

**Issue by smitbarmase** [microsoft/vscode#136096]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2
- OS Version: Linux x64 5.13.19.2 Manjaro

Steps to Reproduce:

1. Intellisense was working on settings.json, keybindings.json, etc.
2. I did settings sync. (Even tried to clear cloud data, to start from a clean slate)
2. Intellisense stopped working.
3. Tried to sign out from vscode. It's still doesn't work.

The only way to make it work is, to uninstall vscode. Remove all the cache.
I have experienced this on Linux as well as Windows.

**Comment by sandy081** [comment]
I do not think this distribution is offered by VS Code - I would request to please file the issue against the source from where you got this distribution.

**Comment by smitbarmase** [comment]
I solved it by Setting Sync -> More Actions -> Clear Data in Cloud. Now sync and intellisense are working fine.
