### ISSUE TITLE
Terminal output is trimmed

### ISSUE THREAD

**Issue by Betristor** [microsoft/vscode#136092]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.61.2 (user setup)
- OS Version: Windows_NT x64 10.0.22000
Steps to Reproduce:
I still don't know how this happen. At first I thought it's due to substitution of ffmpeg file for usage of netease extension, but  I changed ffmped back and this still exists. Example is posted below, which is generated from my visual studio code.

1. make a long output in terminal, toggle the panel;
2. then toggle back, my output is trimmed;
3. the more times I toggled, the less is shown in the terminal.

![](https://i.stack.imgur.com/dCjkD.png)
![](https://i.stack.imgur.com/vlX9C.png)
![](https://i.stack.imgur.com/WwZHe.png)

**Comment by Python-37** [comment]
I met the same bug, outputs in terminal was gone except the last line after minimize the terminal.

**Comment by Betristor** [comment]
Will it be the problem of Windows 11? I'm using Windows 11 too.

**Comment by Python-37** [comment]
> 
> 
> Will it be the problem of Windows 11? I'm using Windows 11 too.

Maybe, computers I am using for work all runs Win 10, didn't meet this bug.

**Comment by Betristor** [comment]
> > Will it be the problem of Windows 11? I'm using Windows 11 too.
> 
> Maybe, computers I am using for work all runs Win 10, didn't meet this bug.

That's true, I asked others who're using visual studio code on windows 10, they don't have the same trouble. This is really annoying in error trace.

**Comment by meganrogge** [comment]
fixed in insider's and /duplicate #134692

**Comment by meganrogge** [comment]
actually, I can still reproduce this

**Comment by Prateek2709** [comment]
So what's the solution to this issue? I raised the same query a few days back but it was closed down and marked as duplicate. Any ideas of how to solve this?

**Comment by Tyriar** [comment]
It's a conpty problem: https://github.com/microsoft/vscode/issues/134448

/duplicate
