### ISSUE TITLE
With `md.supportHtml = true`, an img tag on the markdown document cannot load the URI of a local resource

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#136027]
Version: 1.62.0-insider (Universal)
Commit: f961b92f0faec5c68124ab4d89922d38cf6f513d
Date: 2021-10-28T05:14:00.367Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0

Setting `md.supportHtml = true`, on the markdown document of a completion item, an `img` tag cannot load a PNG file if the path given as a URI with `vscode.Uri.file`. If the path given as the path of a local filesystem, it can load the file.

Steps to Reproduce:

1. Execute https://github.com/tamuratak/vscode-extension-samples/tree/supporthtml_img_local/completions-sample
2. Execute `Trigger Suggest`
3. Only one of images cannot be loaded.

![スクリーンショット 2021-10-28 20 51 23](https://user-images.githubusercontent.com/10665499/139251098-47126baa-f74b-499c-8ef5-b7a2f7095e4e.png)

```ts
import * as vscode from 'vscode';
import * as path from 'path';

export function activate(context: vscode.ExtensionContext) {

	const provider1 = vscode.languages.registerCompletionItemProvider('plaintext', {

		provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext) {

			const pngPath = path.join(__dirname, '..', 'a.png')
			const pngPathUriString = vscode.Uri.file(pngPath).toString()

			const snippetCompletion = new vscode.CompletionItem('Good part of the day');
			snippetCompletion.insertText = new vscode.SnippetString('Good ${1|morning,afternoon,evening|}. It is ${1}, right?');
			const md = new vscode.MarkdownString(`1 <img src="${pngPathUriString}"> 2 <img src="${pngPath}"> 3 ![a](${pngPathUriString}) 4 ![a](${pngPath})`);
			md.supportHtml = true
			snippetCompletion.documentation = md

			// return all completion items as array
			return [
				snippetCompletion
			];
		}
	});
	context.subscriptions.push(provider1);
}
```

**Comment by RyanAfrish7** [comment]
@mjbvz Can I pick this up?

**Comment by mjbvz** [comment]
Sure, the relevant code where we fix image paths is: 

https://github.com/microsoft/vscode/blob/d209aa2b02f6cc99f3c985b23c99eb2346f9dbdb/src/vs/base/browser/markdownRenderer.ts#L112

**Comment by RyanAfrish7** [comment]
For the markdown syntax images, if the URI schema is `file:`, that's being changed to `vscode-file:`. For the HTML tag images, the file URI remains as is.

The HTML image with `file:` URI doesn't load due to CSP violation.

### Raw
```Markdown
1 <img src=\"file:///workspaces/vscode-extension-samples/completions-sample/a.png\"> 2 <img src=\"/workspaces/vscode-extension-samples/completions-sample/a.png\"> 3 ![a](file:///workspaces/vscode-extension-samples/completions-sample/a.png) 4 ![a](/workspaces/vscode-extension-samples/completions-sample/a.png)
```

### Rendered Markdown
```
<p>1 <img src=\"file:///workspaces/vscode-extension-samples/completions-sample/a.png\"> 2 <img src=\"/workspaces/vscode-extension-samples/completions-sample/a.png\"> 3 <img src=\"vscode-file://vscode-app/workspaces/vscode-extension-samples/completions-sample/a.png\" alt=\"a\"> 4 <img src=\"/workspaces/vscode-extension-samples/completions-sample/a.png\" alt=\"a\"></p>
```

**Comment by mjbvz** [comment]
Yes `file` uris are blocked for security reasons. The problem is that raw html tags don't go through the transform that I linked to

One thing to try would be to look for image nodes in the rendered markdown and then transform their uris instead of relying on the markdown parser to handle the transform. Try looking at [DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) for that
