### ISSUE TITLE
Improper parsing of commonmark link-destination

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode#136073]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2
- OS Version: macOS Big Sur

Steps to Reproduce:

1. Create a new markdown file.
2. Type `[x]: <x y> "x y"`

![image](https://user-images.githubusercontent.com/2845433/139343873-b380b586-321c-43b0-a253-4feb11c2e632.png)

But according to https://spec.commonmark.org/0.30/#link-destination it isn't necessary to escape spaces when the text is enclosed in `<` `>`:

> a sequence of zero or more characters between an opening < and a closing > that contains no line endings or unescaped < or > characters, or

> a nonempty sequence of characters that does not start with <, does not include ASCII control characters or space character, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses. (Implementations may impose limits on parentheses nesting to avoid performance issues, but at least three levels of nesting should be supported.)

**Comment by mjbvz** [comment]
Removing help wanted since this is a bit more complicated than anticipated
