### ISSUE TITLE
Not able to do global search getting spawn

### ISSUE THREAD

**Issue by rahulsalesforcesydney** [microsoft/vscode#136005]
trying to do search in VS code but getting error as spawn /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg EACCESS

**Comment by rahulsalesforcesydney** [comment]
No, it was working fine for me earlier.

**Comment by roblourens** [comment]
Is it possible that you have a workspace folder which doesn't exist anymore, or had its permissions changed?

**Comment by rahulsalesforcesydney** [comment]
Workspace folder does exist and same permissions.

**Comment by roblourens** [comment]
Can you also check the permissions on `/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg`?

Maybe we can get some clue if you get the search logs

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" and "Log (Extension Host)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by rahulsalesforcesydney** [comment]
I just restarted my mac and seems search is working fine.

**Comment by roblourens** [comment]
Let me know whether it starts happening again. Looking at this in #136373 as well where a workaround was found.
