### ISSUE TITLE
Introduce local echo auto setting which disables in local workspaces

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#136063]
There are too many issues with local echo and can really degrade the experience right now for local workspaces. We should add an on/off/auto setting where auto is disabled in local workspaces, so opt-in ssh in local terminal support is there.

**Comment by rchiodo** [comment]
@Tyriar what steps would we take to verify? Looks like there's a new setting?

**Comment by roblourens** [comment]
I tested the `terminal.integrated.localEchoEnabled` setting
