### ISSUE TITLE
Settings Editor filter string `java.` includes JavaScript settings as well

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#136028]
Issue Type: <b>Bug</b>

See https://github.com/microsoft/vscode-java-pack/issues/794

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by nickzhums** [comment]
Hello folks, if we could bump the priority of this one, it'd be great. Right now when you search ".java" in the settings, all JavaScript settings shows up and it's rather counter-intuitive for our users. cc @brunoborges

**Comment by rzhao271** [comment]
Code pointer so that I don't lose track: https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/preferences/common/preferencesModels.ts#L80

My idea is to implement a better ordering that takes into consideration the name of the setting.
