### ISSUE TITLE
Unable to Get Local issuer Certificate

### ISSUE THREAD

**Issue by basijan** [Microsoft/vscode#13600]
- VSCode Version: 1.5.1
- OS Version: Windows 7

Steps to Reproduce:

1. Set up Team Foundation Server with Git
2. Manage repos using Git in VSCode 

This has always worked, but today whenever I open VSCode I get this message: 

> Error:  unable to get local issuer certificate

And when I try syncing any of my repos: 

 > Error: Authentication failed on the git remote.

I tried running `git config --global credential.helper wincred` but this does nothing.

#### My config file: 

	[credential]
		helper = store

I am still able to use git perfectly with Visual Studio 2015 (with the same TFS server)

_____________

What steps can I take to find the problem?

**Comment by joaomoreno** [comment]
Code just spawns git as if from the command line. So, make sure you can run `git fetch` from the command line and it works. If it doesn't please reach out to the TFS support.
