### ISSUE TITLE
markdown preview wrongly creates links

### ISSUE THREAD

**Issue by 4015-dev** [microsoft/vscode#136198]
## Versions info

- VS Code Version: 1.61.2
- OS Version: Ubuntu 20.04.2 LTS

## Related issues

[#81891][1] (cloased)
[#59999][2] (cloased)

## Steps to Reproduce:

1. Edit a markdown file with following content:
    ```
    hello.py
    hello.name
    ```
2. Open markdown preview

the entries are displayed as an html links

## Does this issue occur when all extensions are disabled?

Yes

## Source of the issue

- VS Code use [markdown-it][3] which use [linkify-it][4] to display the links preview. 
- in linkify-it **fuzzyLink** option - used to recognize URL-s without http(s):// head - has a default value of **true**.

 ## Possible solution
 
 Set `fuzzyLink` to `false`, using markdown-it linkfy function as follow:
 
 ```js
 md.linkify.set({ fuzzyLink: false });  // disables converting URL without http(s):// head  to link
 ```
as explained [here][5]. But, I don't know where should I add this code snippet, nor how to edit Markdown-it rendering options in VS Code,

Thank you. 

---
[1]:https://github.com/microsoft/vscode/issues/81891
[2]:https://github.com/Microsoft/vscode/issues/59999
[3]:https://github.com/markdown-it/markdown-it
[4]:https://github.com/markdown-it/linkify-it#new-linkifyitschemas-options
[5]:https://github.com/markdown-it/markdown-it#linkify

**Comment by mjbvz** [comment]
As you note, this is expected behavior from markdown-it: https://markdown-it.github.io/#md3=%7B%22source%22%3A%22hello.py%5Cnhello.name%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

You can set `"markdown.preview.linkify": false` to disable automatic linkifying

**Comment by 4015-dev** [comment]
Yes, VS Code designed to use the default options of markdown-it for linkify.

But, while `"markdown.preview.linkify": false` will disable linkify features entirely,  setting `md.linkify.fuzzyLink` to false, will disable it only for links without http(s) header. which , I think, is a better alternative, and it's already supported by markdown-it.

So, my question is: is it possible to edit markdown-it options in VS Code ? and if so, how can I do it?

Thank you.

**Comment by mjbvz** [comment]
Thanks, yes actually let's try disabling fuzzy links for now since it's come up a few times

I'd prefer not having an option for this but if a few people happen to be relying on these fuzzy links, we could always add an option

**Comment by 4015-dev** [comment]
You welcome, I've just forked vscode to try to do that, and was happily surprised to find that you've already made the change

![Selection_001](https://user-images.githubusercontent.com/91027619/139774303-03c0295a-76a9-4d48-8bf0-63e2b1f1ce7c.png)

Can you please indicate which files I need to work on if I want to make Markdown-it options editable through, settings.json file ?

**Comment by 4015-dev** [comment]
/verified

on:

```
Version: 1.64.0-insider
Commit: f67a8b753f55e452f38b61497662839c4691fb12
Date: 2021-12-16T05:15:28.698Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-41-generic
```

Sorry for the late response, I've moved to an open source build of VS Code, instead of Visual Studio Code since then.

Thanks
