### ISSUE TITLE
Debug process won't start until vscode get focus

### ISSUE THREAD

**Issue by taooceros** [microsoft/vscode#136148]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.0-insiders
- OS Version: Windows 11

Steps to Reproduce:

1. Press F5 to start building and debugging
2. Go to other windows and do other things
3. The debug process will only start after switching back to vscode

**Comment by gjsjohnmurray** [comment]
What language are you coding and debugging?

**Comment by taooceros** [comment]
C# dotnet 5
