### ISSUE TITLE
tab bug

### ISSUE THREAD

**Issue by wangding07034** [microsoft/vscode#136182]
Issue Type: <b>Bug</b>

select all rows 。 ctrl + [   create bug;

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by ArturoDent** [comment]
<kbd>Ctrl</kbd>+<kbd>[</kbd> is `outdent line`

<kbd>Ctrl</kbd>+<kbd>]</kbd> is `indent line`

Which are you trying to do?
