### ISSUE TITLE
VSC with Python reads / as floor division (// works fine)

### ISSUE THREAD

**Issue by Pawlowskieiro** [Microsoft/vscode#13610]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:28:55.412Z)
- OS Version: Darwin x64 16.0.0
- Extensions: donjayamanne.python-0.4.2

Steps to Reproduce:

1. simply try to divide an odd number by an even number
2. see if it prints an integer or perfomrs a floor division

I have no idea how to deal with it, I've just started using VSC. Would be massively grateful for any help. I'm using VSC on Mac, with Sierra 10.12

**Comment by isidorn** [comment]
This behavior is coming from the python extension ,so pleae report it here
https://github.com/DonJayamanne/pythonVSCode
