### ISSUE TITLE
Right-most editor tab becomes unclickable

### ISSUE THREAD

**Issue by hl2guide** [microsoft/vscode#136146]
Issue Type: <b>Bug</b>

1. Open up 5 files (creates 5 tabs) 
2. Try to naviate the tabs from the first to fifth
3. Notice the tab becomes unclickable

(tested on a 1920x1080 monitor with the window docked at half width, bug seems related to the buttons to the right of the set of tabs)

[Example Screenshot](https://user-images.githubusercontent.com/17044982/139517358-afb06296-4ddd-41f7-8add-985b70e9c0b5.png)

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (18.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.2.2
path-intellisense|chr|2.4.1
bracket-select|chu|2.0.2
bracket-pair-colorizer-2|Coe|0.2.1
smoothscroll|cya|1.0.4
vscode-texty|dat|1.1.2
whitespace-plus|dav|0.0.5
vscode-html-css|ecm|1.10.2
hungry-backspace|ekl|1.0.0
prettier-vscode|esb|9.0.0
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
reg|ion|1.0.3
hungry-delete|jas|1.6.0
dupchecker|jia|0.1.7
vscode-insertdatestring|jsy|2.3.0
vscode-icon-theme|jtl|1.6.6
vscode-colorize|kam|0.11.1
markdown-shortcuts|mdi|0.12.0
rainbow-csv|mec|1.9.1
code-beautifier|mic|2.3.3
fluent-icons|mig|0.0.14
vscode-filesize|mkx|3.1.0
vsce-show-linecount|MPe|2.0.0
selecta|mrv|0.0.1
vscode-language-pack-en-GB|MS-|1.54.1
vs-sequential-number|nep|1.1.0
indent-rainbow|ode|8.2.2
css-alphabetize|Pol|0.2.0
text-power-tools|qcz|1.30.0
remove-tabs-on-save|red|1.2.1
datetime|rid|2.1.0
ActiveFileInStatusBar|Ros|1.0.3
vscode-paste-and-indent|Rub|0.0.8
text-marker|ryu|1.11.0
px-to-rem|sai|1.3.1
vscode-indent-line|san|1.0.1
select-quotes|StA|0.0.2
code-spell-checker|str|2.0.12
selectline-statusbar|tom|0.0.2
sort-lines|Tyr|1.9.0
incrementor|use|0.1.4
remove-empty-lines|use|0.0.8
colonize|vms|2.2.2
highlight-bad-chars|wen|0.0.5
vscode-surround|yat|1.2.2
html-css-class-completion|Zig|1.20.0

</details>

**Comment by gjsjohnmurray** [comment]
There should be a thin horizontal scrollbar between your 4 visible tabs and the editing area below the tabs.

IIRC there's a setting to increase the height of that scrollbar so it is easier to grab.

There are also settings controlling whether tab widths get limited, and whether they wrap rather than scrolling horizontally.

**Comment by bpasero** [comment]
You can scroll tabs into view as https://github.com/microsoft/vscode/issues/136146#issuecomment-955142158 indicates and there are many settings to control how tabs appear, including to wrap them instead of showing a scrollbar.
