### ISSUE TITLE
Open Tab to specific layout group by regex match

### ISSUE THREAD

**Issue by sirius0xff** [microsoft/vscode#136162]
As title.

I am working with c++. 
I have two layout groups, and usually open .cpp to the left and .h & other files to the right side.
But I have to manually move them around every time.
So I think have them default open to specific group would be handy.

**Comment by gjsjohnmurray** [comment]
#103497 was similar but didn't attract enough upvotes.

**Comment by gjsjohnmurray** [comment]
Proposed API at #133532 may allow an extension to do this.
