### ISSUE TITLE
Install rpm deps with correct bitness

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#13616]
https://github.com/Microsoft/vscode/issues/13544 introduces libXss.so.1 as a dependency to the rpm package, this installs both 32-bit and 64-bit packages which is less than ideal. We should include only he necessary one in the build step.

<img width="725" alt="screen shot 2016-10-12 at 9 40 33 am" src="https://cloud.githubusercontent.com/assets/2193314/19319083/18f2337a-9060-11e6-8971-08917ad8c647.png">

**Comment by polygotdev** [comment]
I could help out here. I've have some initial thoughts outlined in this gist...
https://gist.github.com/polygotdev/8110b92e8b2d1ce20998c4bbc4e41c0b

I have done some initial validation with a change to the RPM spec file to include a **conditional**.
I've also validated package build and installation on the following platforms:
- CentOS-7-x86_64-DVD-1610-01
- rhel-server-7.2-x86_64-dvd
- Fedora-Workstation-Live-i386-24-1.2
- Fedora-Workstation-Live-x86_64-24-1.2

I can throw in some screenshots as well.

I can do a pull request if this is of value, there is a standard fork/branch with the change incorporated for your review.

https://github.com/polygotdev/vscode/tree/debt_13616_linux_rpm_depends_bitness

Cheers

**Comment by Tyriar** [comment]
Thanks a lot for looking into this @polygotdev, I was thinking doing something like this would be necessary. A PR would be awesome :smiley:

**Comment by polygotdev** [comment]
a followup on the insiders build installation, looking good, results at

https://gist.github.com/polygotdev/8610fff8d0c0419c0b22215850517433#file-code-insiders-1-8-0-1478617894-el7-x86_64-rpm-log

**Comment by Tyriar** [comment]
Awesome :smile: I'll close this off, it'll get another test at release time.

To verifier: Please test that the libXss/libXScrnSaver is installed with the correct bitness on both fedora 32-bit and 64-bit.
