### ISSUE TITLE
English Int'l keyboard - " typing does not behave the right way in Terminal

### ISSUE THREAD

**Issue by benjguin** [microsoft/vscode#136105]
Issue Type: <b>Bug</b>

I'm on Windows 10 + WSL2. Terminal default is bash WSL2.

Open VSCode
Open a text file
Open a terminal
use a QWERTY US Keyboard
Set keyboard driver to be United States-International

NB: with this setup, to type é, you type 'e, to type ', you type '{SPACE}
To make things easier, if you type '', you get ''
As ' is used for é, Á etc..., " is used for letters like ë, Ä, etc.

In the text file type the following sequence
git commit -m ""{LEFT ARROW}my message
you get
git commit -m "my message"

In the terminal type the following sequence
git commit -m ""{LEFT ARROW}my message
you get 
git commit -m ""my message

In the terminal type the following sequence
git commit -m ""{LEFT ARROW}{LEFT ARROW}my message
you get 
git commit -m "my message"

Text editor has a behavior which is consistent with the rest of Windows, not the terminal.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.88GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/benjguin/code/be-id-edlp --remote=wsl+Ubuntu --crash-reporter-id 07cb883f-786c-4e3c-ad37-71683f87d08a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Bertelsmann ID - EDLP|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2903)|
|Memory (System)|12.39GB (6.63GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2903)|
|Memory (System)|12.39GB (6.63GB free)|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.3.3
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.202.5
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.4
vscode-remote-extensionpack|ms-|0.21.0
vsonline|ms-|1.0.3076
markdown-mermaid|bie|1.12.1
markdown-preview-github-styles|bie|0.2.0
gitlens|eam|11.6.1
rest-client|hum|0.24.5
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.3
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
azure-account|ms-|0.9.9
vsliveshare|ms-|1.0.5043
vscode-mermaid-editor|tom|0.11.4
azure-iot-toolkit|vsc|2.16.6

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535

```

</details>

**Comment by Tyriar** [comment]
Can reproduce, it also behaves differently with backspace. To clarify the cases here are:

- Type ' twice, left arrow should move the cursor (but 2 are required)
- Type ' twice, backspace should delete a ' (but 2 are required)

**Comment by benjguin** [comment]
The bug seems to be fixed in the following version of VSCode - maybe a side effect of another bug fix or update

Version: 1.64.0 (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z (5 days ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
