### ISSUE TITLE
Visual Studio code seems to have Windows 10 style window controls/decorations instead of Windows 11

### ISSUE THREAD

**Issue by 1ctinus** [microsoft/vscode#136132]
I know that the window controls are not done natively because the program is made in Javascript, but the window decorations/controls are in the style of Windows 10, which only effect the maximize/minimize button.
![image](https://user-images.githubusercontent.com/72636637/139501187-36fe71a6-a776-4fbd-a6ea-09bb706f28a5.png)
VSCode controls
![image](https://user-images.githubusercontent.com/72636637/139501214-da43c3c1-01c1-45cd-be3b-1cde96a00266.png)
Native Windows 11 controls

**Comment by 1ctinus** [comment]
Looking into the issue, it seems like the asset that decides the look for a window icon is actually a font, not an image

**Comment by 1ctinus** [comment]
This seems to be an issue with the codicons needing to be updated on more research,

**Comment by misolori** [comment]
@sbatten given that Win 11 has a specific icon style for their windows controls, can we specify custom icons for windows?
