### ISSUE TITLE
Cannot copy selected text from pop-ups that show on hover

### ISSUE THREAD

**Issue by david-cortes** [microsoft/vscode#136199]
Does this issue occur when all extensions are disabled?: Not applicable

Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:58:13.605Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.14.0-3-amd64

**Steps to Reproduce:**

1. Click the "extensions" button in the left side pane.
2. Hover the mouse over some extension, such as the python extension.
3. In the pop-up that shows up next to the extension when hovering the mouse, try to copy the version of the extensions from that pop-up.

**Expected behavior:** should copy the version to the clipboard.

**Actual behavior:** shows an error pop-up at the bottom-right that says "endIndex 1 out of boundary".

**Comment by sandy081** [comment]
It works for me - anyway forwarding to @Tyriar as it is related to hover.

**Comment by Tyriar** [comment]
Also works for me on Windows. Sounds like the error happens during copy so maybe there's a problem with clipboard access on Linux? Passing over to @deepak1556, might want to close as no repro?

**Comment by deepak1556** [comment]
Closing as unable to repro the issue.
