### ISSUE TITLE
not formatting

### ISSUE THREAD

**Issue by PERA2008** [microsoft/vscode#136192]
Issue Type: <b>Bug</b>

I tried everything but... every tipe of file is formatting , but js is not. everything you are thinking of, I already did but stiil any of .js files arent formated. even "prettier" isnt working. don't know what to do help. for exmp: document.queriSelector it must have color right? it si just white text, it is functional but still. 

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.4
prettier-vscode|esb|9.0.0
material-icon-theme|PKi|4.10.0
prettier-now|rem|1.4.9
LiveServer|rit|5.6.1
prettier-vscode|Sim|2.0.7
prettier-plus|svi|4.2.2
bootstrap4-vscode|the|6.1.0
bootstrap-3-snippets|wcw|0.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by PERA2008** [comment]
helpp

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by PERA2008** [comment]
prettier isnt working at all, even other type of files aren't formatting, for example cpp files. format on save is on. in json settings file everything is alright defaultformatter is set on prettier but it still isnt formatting.

**Comment by mjbvz** [comment]
Please start by filing this against your formatting extensions
