### ISSUE TITLE
Large notebook text outputs can't be wrapped

### ISSUE THREAD

**Issue by thanhph111** [microsoft/vscode#136184]
Does this issue occur when all extensions are disabled?: Yes

As described in the title and the clip below will say the rest, the canvas seems overwhelmed with the output and doesn't wrap it.

https://user-images.githubusercontent.com/60842560/139567418-a38697ff-0a3e-4880-80de-21afd37963f5.mp4

The log:

```
[36297:1031/112848.622152:ERROR:gl_utils.cc(314)] [.RendererMainThread-0x1414a4079800] GL_INVALID_FRAMEBUFFER_OPERATION: Draw framebuffer is incomplete
```

Because the lower trimmed part are wrapped, it thinks it don't have to show the scrollbar so we can't view the rest if the line is long enough. This is critical.

![image](https://user-images.githubusercontent.com/60842560/139568037-acf04901-8d0a-4eee-bde8-d2d3b2719435.png)

If we put some colors, we will see the lines overflow at the edge:

![Screenshot](https://user-images.githubusercontent.com/60842560/139567742-067e8177-2d70-46dc-b5df-f931c22f50a1.png)

Smaller outputs are fine:

![Screenshot](https://user-images.githubusercontent.com/60842560/139567681-1bc6a73d-4cc4-4af9-b7bf-c914d5f1fead.png)

<details>
<summary>System info</summary>

Version: 1.62.0-insider
Commit: ff1e16eebb93af79fd6d7af1356c4003a120c563
Date: 2021-10-29T07:49:33.336Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-38-generic

</details>

I haven't got a chance to test on other OSs.

This is my test notebook: https://gist.github.com/thanhph111/b6471bfa16603e56af351447c3cd29de.

**Comment by greazer** [comment]
@rebornix, this is just a bug, but could probably be considered as part of the discussion about https://github.com/microsoft/vscode-jupyter/issues/7096.

**Comment by greazer** [comment]
@thanhph111, thanks for the feedback. What are your thoughts on the current behavior, where we supply a link at the top of the output that allows you to open the output in a separate editor tab? This behavior can indirectly essentially solve problems like this.

**Comment by rchiodo** [comment]
@rebornix I'm taking this with the assumption you're not currently looking at it.
