### ISSUE TITLE
C# dotnet capacity to build VS Code Extensions

### ISSUE THREAD

**Issue by HarrisonOfTheNorth** [microsoft/vscode#136167]
I'd like the capacity to build VS Code extensions using dotnet C# technologies under the forwards-looking "C# Everywhere" paradigm that is driving client-to-cloud technologies forwards in an ever-accellerating rate.

I recently looked at an official Visual Studio Code team  [YouTube video](https://www.youtube.com/watch?v=PGAu06_E_BU) here and although I was dissapointed to have missed the livestream, I was even further dissapointed that my request for information was deleted from the video comments.  

I had made a comment asking about this, and as has been answered by the VS Code team in another issue raised on this GitHub account about why there isn't a VS Code forum, the answer from the VS Code team was that they prefer this Github isues section instead. Hence I'm raising the same issue and presenting the same comment that was deleted. The comments made were genuine, and presented without malice.

To give further context, this view as expressed here and in the attachment is a genuine view of a career C# client-to-cloud engineer, I've been on teams producing over 40 apps in the app stores, and I am presently full-time on a Maui app and we are looking for VS Code functionality to support the dotnet tools that we have made and are continuing to make for the open source libraries that we are releasing.

However because we are C# client-to-cloud engineers without any Javascript or Typescript experience - and because of the "C# Everywhere" initiative that has driven such projects as WASM and Maui forwards, we are unlikely to acquire Javascript or Typescript skills - so it seems our hands are currently tied with the prospect of VS Code not being a useful tool for the ilk of we until we can create extensions using dotnet and C#.

I'd love some positive feedback about the prospect of VS Code Extensions being capable of being created using dotnet and C# technologies, with VS Code Technical Evangellists presenting their tutorials about VS Code Extensions being created using dotnet and C# without any reference to non-dotnet frameowrks such as npm, etc, as the ilk of these are unfamiliar to us. 

To me it's all about "dotnet tools for dotnet engineers" and I'd like to see acceptance of this need and a prospective timeline.

Naturally, if it is not possible, for any reason, I'd also like to understand why as this would have to make us rethink our dotnet everywhere policy.

![Screenshot 2021-10-30 at 16 57 59](https://user-images.githubusercontent.com/25448533/139541106-579353d3-f4bd-46ab-b29b-1261d21331f2.png)

**Comment by isidorn** [comment]
@HarrisonOfTheNorth thanks for your feedback. I have closed this issue as this is not something we plan to work on in the next 6 months, however let me answer your question.
The VS Code extensions have to run in a Node context, thus the core of each extension can be written in Typescript / Javascript. However, each extension can choose it's dependencies and libraries as it wants. And those libraries can be written in C#, it is up to the extension author.

Also Typescript is getting more and more features and almost everything you can do in C# can be done in Typescript. We hope you give it a try.

**Comment by HarrisonOfTheNorth** [comment]
Thanks, but I don't intend getting involved in Typescript - vis-a-vis my expressed usecase - "dotnet tools for dotnet engineers"

This has made me look at Kotlin multiplatform, however, they seem commited to an end-to-end solution in the one language.
