### ISSUE TITLE
Intellisense not working on event attributes in HTML templates

### ISSUE THREAD

**Issue by ArtVS** [microsoft/vscode#136128]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2
- OS Version: Windows 10 19043

Steps to Reproduce:

1. Open HTML template
2. Try to add event listener attribute to a tag

So, basically, when I' trying to add an event listener in parenthesis in my HTML template, I get no intellisense options for common events, only for the events I added manually in my components/directives
So it looks like this: 
![Screenshot_107](https://user-images.githubusercontent.com/92225500/139497505-14accb54-0c90-4123-af05-017716ff56bb.jpg)

**Comment by aeschli** [comment]
What templating language is that?

VS Code only has support for pure HTML.
Support for templating languages needs to come from an extension.

**Comment by ArtVS** [comment]
> What templating language is that?
> 
> VS Code only has support for pure HTML. Support for templating languages needs to come from an extension.

that's an Angular template html file

**Comment by aeschli** [comment]
thanks. You need to look for an Angular extension then.

**Comment by ArtVS** [comment]
> thanks. You need to look for an Angular extension then.

Okay, will do that then, thank you!
