### ISSUE TITLE
sometimes `toggle size to content width` doesn't do anything

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#136110]
Windows 
![recording (70)](https://user-images.githubusercontent.com/38270282/139446813-708330ac-58d2-4965-8b6b-71e2872c2a7f.gif)

_Originally posted by @alexr00 in https://github.com/microsoft/vscode/issues/134623#issuecomment-954761179_

**Comment by jwarkentin** [comment]
This seems like it might be related to #134623

**Comment by meganrogge** [comment]
Nothing actionable here
