### ISSUE TITLE
Unsecure node included, needs update

### ISSUE THREAD

**Issue by danielgp** [Microsoft/vscode#13619]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

Steps to Reproduce:
1. Goto Help menu, choose About, notice Node 6.5.0
2. Goto https://nodejs.org/en/ and notice a big "Important security notes for recent OpenSSL and Node.js vulnerabilities" and click on it
3. Take notice of all vulnerabilities
4. Change the dependencies for this package to Node 6.7.0 or newer from active LTS branch
5. Launch a new version with not vulnerable Node included

**Comment by bpasero** [comment]
We will eventually.

**Comment by bpasero** [comment]
**Update:** 

VS Code is using [Electron](https://github.com/atom/electron) and depends on the node.js version bundled within (currently 6.5.0). There is no newer release currently that includes a newer node.js version. 

We have two options:
* we wait for Electron to provide a new stable version and update next milestone (February) to it
* we provide a PR to Electron to update the node.js version on top of the Electron version we are running with

We should decide after assessing the security risks for VS Code itself. It seems that the security problems have larger exposure in a web-server environment and not on a desktop application.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/23159

**Comment by danielgp** [comment]
Hi Benjamin,

I am not sure why this was closed as both 1.11.1 release and 1.12.0-insider
still displays Node.js 6.5.0 on the Help - About...
