### ISSUE TITLE
Customize Open recent command

### ISSUE THREAD

**Issue by andvant** [microsoft/vscode#136143]
Issue Type: <b>Feature Request</b>

Currently using Open recent command (Ctrl+R) I'm shown 100 recent folders first and then 100 recent files. I for one definitely don't need that many folders remembered, and would prefer files coming up first (and maybe increase their count to 150). Would be nice to have it customizable in settings.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by bpasero** [comment]
Slightly related, I just merged https://github.com/microsoft/vscode/pull/135741 that increases the limit to 500.
