### ISSUE TITLE
Ctrl+Click Links with filename:line:text don't work 

### ISSUE THREAD

**Issue by coezbek** [microsoft/vscode#136190]
Issue Type: <b>Bug</b>

1. Create a file with name `my_file.rb` in a new repository and enter three lines of random text.
2. Open a Terminal
3. enter `my_file.rb:1:in`
4. Try to Ctrl+Click this go open the editor on line 1
5. Observe that VSCode shows "No result"

This bug manifests when running `ruby` scripts in Terminal and getting a stacktrace such as:

```ruby
~/$ ruby my_file.rb 
Traceback (most recent call last):
my_file.rb:2:in `<main>': Oh oh Crash (RuntimeError)
```

Screenshot: 

![image](https://user-images.githubusercontent.com/12127567/139591276-4352580b-8f79-4914-9a05-c05323079de3.png)

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Fetching remote diagnostics for 'WSL: Ubuntu-20.04' failed: Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (4.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|57%|

Fetching remote diagnostics for 'WSL: Ubuntu-20.04' failed: Canceled
</details>Extensions: none

**Comment by coezbek** [comment]
Associated question on StackOverflow: https://stackoverflow.com/q/69784676/278842

**Comment by Tyriar** [comment]
It actually works when running using `./`:

![image](https://user-images.githubusercontent.com/2193314/139866873-8a9c22da-6a52-45db-b1bf-0a8d25b8e77b.png)

Since the other case is falling back to the "word link" provider, it ends up searching the workspace for the whole path (`my_file.rb:2:in`). Since all these errors in ruby [seem to have `:in` added to the end](https://stackoverflow.com/q/69784676), let's add some smarts around handling that.

**Comment by coezbek** [comment]
Thanks! @Tyriar This is awesome!
