### ISSUE TITLE
Breakpoints are not working as expected

### ISSUE THREAD

**Issue by Jason3S** [microsoft/vscode#136156]
Issue Type: <b>Bug</b>

I'm going to be brief, because this feels like a regression of
[ts-jest (and maybe ts-node) files do not get source mapped when debugging. · Issue #1100 · microsoft/vscode-js-debug](https://github.com/microsoft/vscode-js-debug/issues/1100)

Insider build a few days ago was working. After updating today, it stopped.

Now my breakpoints get moved to a random location and may or may not stop.

I'll try the steps listed in https://github.com/microsoft/vscode/issues/133138#issuecomment-921943687

I know it is not related to the issue, but I have to express my frustration at how painful this breakpoint issue has made debugging Extensions and Tests the past few months.

Please keep up the good work with VS Code.

VS Code version: Code - Insiders 1.62.0-insider (ff1e16eebb93af79fd6d7af1356c4003a120c563, 2021-10-29T05:14:09.436Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|32.00GB (1.61GB free)|
|Process Argv|--crash-reporter-id 8a187fff-41be-45e7-828b-45e2d22eebd7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.0.0
language-haskell|jus|3.4.0
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.3
jupyter|ms-|2021.10.1001398262
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.13.0
vshaxe|nad|2.23.2
code-spell-checker|str|2.0.12
code-spell-checker-russian|str|2.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
vsc_aa:30263845
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30382699
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedc:30350118
pythonvspyt187:30365360
pydsgst2:30361790
vsaa593:30376534

```

</details>

**Comment by Jason3S** [comment]
[vscode-debugadapter-53984913.json.gz](https://github.com/microsoft/vscode/files/7459026/vscode-debugadapter-53984913.json.gz)

**Comment by connor4312** [comment]
Everything looks fine from the logs. Do you have a repo you can share?

**Comment by Jason3S** [comment]
No problem:

Repository: https://github.com/streetsidesoftware/cspell

Steps:

- Setup

  ```sh 
  npm install
  npm run build
  npm test
  ```

- open Workspace: `cspell.code-workspace`
- open File: `packages/cspell-lib/src/Settings/InDocSettings.test.ts`
- Pick Launch Profile: `cspell-lib: Jest current-file` or `test: Jest current-file`, both worked in the past.
  ![image](https://user-images.githubusercontent.com/3740137/140020518-be6c2f78-36cf-4e58-9d7e-4a215f705f4d.png)
- Set a breakpoint on line 104: 
  ![image](https://user-images.githubusercontent.com/3740137/140021130-a684fe62-0c7b-4657-89fe-ae5235445b4c.png)
- `F5`
- It stops on line 90: 
  ![image](https://user-images.githubusercontent.com/3740137/140021259-285f25ae-8265-4661-b087-95180692874e.png)

**Comment by connor4312** [comment]
Hm, both of those configurations work for me following your instructions

**Comment by Jason3S** [comment]
That is frustrating. Any way I can help debug it on my end?

**Comment by llldar** [comment]
I've encountered similar issue

**Comment by llldar** [comment]
Turns out it's the problem with tsconfig.json,
It need to have `"sourceMap": true` to work correctly

**Comment by Jason3S** [comment]
In this case `"sourceMap": true` has been set.

**Comment by brianzinn** [comment]
hi @Jason3S I don't know if you have solved this, but if you haven't and this sounds ridiculous try renaming your project root folder.  For me it has something to do with the state of that folder and VS Code.  If I rename the folder back then it breaks debugging again.  This was so frustrating it took me hours to solve...  still ❤️ VS Code though!

@connor4312 is there a way to completely remove saved state from VS Code?  I had cleared out the directory `C:\Users\brian\AppData\Local\Programs\Microsoft VS Code` and OP is on Mac. Thanks.
