### ISSUE TITLE
[php] highlighting  for mysql in php file

### ISSUE THREAD

**Issue by ingxii** [Microsoft/vscode#1361]
$sql = "SELECT \* FROM users  WHERE id=1";
Can you highlight  the keyword  "SELECT" , "FROM" and  "WHERE",  please?

**Comment by felixfbecker** [comment]
Not only PHP related. SQL should be highlighted also when I'm doing a query in NodeJS, just like it should highlight HTML inside strings. The feature is called language injection in WebStorm.
