### ISSUE TITLE
Error occurs when extension is activating: [exthost] [error] Error: Encountered errors while disposing of store.

### ISSUE THREAD

**Issue by betterRunner** [microsoft/vscode#136150]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.61.2 
- OS Version: Darwin x64 20.6.0

Steps to Reproduce:

1.  Run command 'xxx'. to active my extension which is installed by local vsix
2. see the error message "[exthost] [error] Error: Encountered errors while disposing of store." and the activation failed.

![image](https://user-images.githubusercontent.com/7123136/139522562-cb4e35d7-4f51-45d1-9d43-7d725d74cee7.png)

**Comment by alexdima** [comment]
@betterRunner This looks like a programming error with your extension. It appears that you are pushing objects that do not have a `.dispose()` method to the `ctx.subscriptions` array.

**Comment by betterRunner** [comment]
@alexdima thanks for the reply. I just use the `vscode.languages.registerCompletionItemProvider` command, it should have the dispose method. What is more, the error does not show while debugging. It only occurs in production mode which is built by `vsce packge`

**Comment by alexdima** [comment]
@betterRunner I am happy to take a look if you can provide an example extension that reproduces the problem. Here is the `_deactivate` method that appears in the callstack, I looked at it and cannot identify any flaws there. I think the `subscriptions` array contains a bad disposable:

https://github.com/microsoft/vscode/blob/ff1e16eebb93af79fd6d7af1356c4003a120c563/src/vs/workbench/api/common/extHostExtensionService.ts#L298

I am happy to take a look if you create a reproducible sample.
