### ISSUE TITLE
Add `<>` to `surroundingPairs` for JavaScript and TypeScript.

### ISSUE THREAD

**Issue by jespertheend** [microsoft/vscode#136127]
At first I wanted `<` to autoclose but I realised this would probably be annoying when typing things such as `i < 5`.
But I have added arrow brackets to `surroundingPairs` and it's working pretty nicely so far. I think it could be nice if this were the default.

**Comment by mjbvz** [comment]
Looks like it's been enabled for TS for a long time already:

https://github.com/microsoft/vscode/blob/d6b2e78477e9ac881278b838993f1f9b2900464f/extensions/typescript-basics/language-configuration.json#L28

Just missing from JS

**Comment by jespertheend** [comment]
/verified
thanks!
