### ISSUE TITLE
Module identifiers with jsx extension won't work anymore

### ISSUE THREAD

**Issue by codeart1st** [Microsoft/vscode#13618]
- VSCode Version: 1.6.0
- OS Version: Windows 10.1 x64

With the previous version of VS Code it was possible to inspect module imports from jsx files by using this:

`import reducer from './reducer/index';`
`import App from './components/App';`

So an import without an extension. This is no problem for webpack...

But now in VS Code 1.6 with the new Typescript version the inspection doesn't work anymore. Maybe because of this: [https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#including-built-in-type-declarations-with---lib](url)

So using
`import reducer from './reducer/index.jsx';`
`import App from './components/App.jsx';`
also doesn't work.

The only thing that work is the js extension, but for jsx this is not a good solution

`import reducer from './reducer/index.js';`
`import App from './components/App.js';`

**Comment by waderyan** [comment]
@codeart1st thank you for opening this issue. Can you clarify what you mean by "inspect module imports"? Do you mean "Go to Definition"? 

The vernacular can be different for different developers. A short animation would clarify for me.

**Comment by codeart1st** [comment]
![inspect](https://cloud.githubusercontent.com/assets/581407/19397683/22be0fba-9249-11e6-82e0-c2f4537b88af.png)

Yeah "Go to Definition" (F12) not working and also and also the overlay while using CTRL and mouseover. The example above is the situation after renaming the .jsx file to .js

**Comment by codeart1st** [comment]
![anim](https://cloud.githubusercontent.com/assets/581407/19397863/f3a909ea-9249-11e6-8781-08e0d13b2224.gif)

Shift+F12 also found nothing with .jsx extension

**Comment by waderyan** [comment]
@codeart1st thank you for your explanation. Can you share your repo or a minimal repo I can reproduce this on my end? 

@mhegazy any thought on why this is happening? Looks like we have this filtered correctly in tsserver.js

```
ts.supportedJavascriptExtensions = [".js", ".jsx"];
```

**Comment by codeart1st** [comment]
https://github.com/codeart1st/demo

**Comment by mhegazy** [comment]
@codeart1st, thanks for reporting this. As a workaround in your `jsconfig.json` please specify `"jsx": "react"`, e.g.:
```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "es6",
    "allowSyntheticDefaultImports": true,
    "jsx": "react"
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by mhegazy** [comment]
@waderyan can you port this to the TS issue tracker, this is something we need to fix on our side as well.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11718
