### ISSUE TITLE
[remote] support opening an ssh workspace file in a wsl terminal

### ISSUE THREAD

**Issue by psauvage0** [microsoft/vscode#136157]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.61.2
- OS Version: 10.0.18363

Steps to Reproduce:

1. Open a (non wsl) remote-ssh workspace with vscode
2. Save workspace locally using "Save Workspace As..."
3. Quit VScode, open a wsl terminal
4. Navigate to the .code-workspace file saved earlier
5. Open with `code workspace.code-workspace`

VScode will then try to connect to WSL and fail to open the workspace, regardless of the fact that the workspace is remote.

**Comment by aeschli** [comment]
Ok, I understand and agree it's a reasonable request.
Unfortunately, it's not easy to implement given the way we have layered the remote code.
