### ISSUE TITLE
Python Formatting using black conflicting with prettier

### ISSUE THREAD

**Issue by KunalTanwar** [microsoft/vscode#136179]
Issue Type: <b>Bug</b>

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

Steps to Reproduce:

1. I setup **black** as my default python formatter `"python.formatting.provider": "black"`
2. My default formatter is **prettier** `"editor.defaultFormatter": "esbenp.prettier-vscode"`
3. Also I have `"editor.formatOnSave": true`

But **black** is only working when I am commenting out `"editor.defaultFormatter": "esbenp.prettier-vscode"` from settings.json

**Comment by gjsjohnmurray** [comment]
Doe https://github.com/microsoft/vscode/issues/108447#issuecomment-733176851 help?

**Comment by KunalTanwar** [comment]
## I solved my problem by

**Setup Black as Python Formatter**
```json
"python.formatting.provider": "black",
"python.formatting.blackPath": "/home/<username>/.local/bin/black"
```

**Removing _prettier_ as `defaultFormatter` for python**
```json
"editor.defaultFormatter": "esbenp.prettier-vscode",
"[python]": { "editor.defaultFormatter": null }
```
