### ISSUE TITLE
wrong syntax highlighting

### ISSUE THREAD

**Issue by TarunavBA** [microsoft/vscode#136169]
Issue Type: <b>Bug</b>

VSCode wrongly highlights syntax when typing 
```python
# image viewer

# import pyglet module
import pyglet

# set the window
window = pyglet.window.Window()
# GET the image
image = pyglet.resource.image('pyglet.jpg')
```
you can observe that in `pyglet` `y` gets a dark shade of yellow.
> Note:- you should use dracula theme not soft dracula.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       U 470  @ 1.33GHz (4 x 1330)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.80GB (0.74GB free)|
|Process Argv|. --crash-reporter-id cccec2f2-906a-4f1d-b46b-5174a534ad28|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
emoji-log-vscode|ahm|1.0.0
vscode-django|bat|1.6.0
markdown-emoji|bie|0.2.1
path-intellisense|chr|2.4.1
codestream|Cod|12.0.2
bracket-pair-colorizer-2|Coe|0.2.1
flask-snippets|cst|0.1.2
githistory|don|0.6.19
gitlens-insiders|eam|2021.10.2305
codespaces|Git|1.3.3
copilot-nightly|Git|1.7.3568
remotehub|Git|0.17.0
todo-tree|Gru|0.0.214
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.14
mongodb-vscode|mon|0.6.14
vscode-dotnet-runtime|ms-|1.3.0
python|ms-|2021.11.1400738762-dev
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
sqltools|mtx|0.23.0
sqltools-driver-mysql|mtx|0.2.0
indent-rainbow|ode|8.2.2
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.10
code-spell-checker|str|2.0.12
luna-paint|Tyr|0.10.0
intellicode-api-usage-examples|Vis|0.0.5
vscodeintellicode-insiders|Vis|1.1.5
vscode-icons|vsc|11.6.0
vscode-wakatime|Wak|17.1.0
vscode-import-cost|wix|2.15.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

What language? Does this only happen with a specific theme?

Command Palette offers a command to examine semantic tokens and/or TextMate scopes. Does this reveal anything unusual about the problem character?

Screenshots may help.

/gifPlease
