### ISSUE TITLE
Support to copy content in pages from integrated terminal window

### ISSUE THREAD

**Issue by hanbaobao2005** [Microsoft/vscode#13617]
- VSCode Version: 1.6.0
- OS Version: windows10

Steps to Reproduce:
1. Execute a code(E.g.: Python) in terminal which its output more than 1 page
2. Because selection limitation, It only could copy the content in the current page, the selection is cleared when down/up page by mouse

Expectation:
step2, Refer to windows command line, the selection should not be cleared when down/up page by mouse

**Comment by Tyriar** [comment]
Duplicate https://github.com/sourcelair/xterm.js/issues/69
