### ISSUE TITLE
"Go to file" doesn't provide any options to choose from

### ISSUE THREAD

**Issue by aaronsnyder** [Microsoft/vscode#13613]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:28:55.412Z)
- OS Version: Darwin x64 15.0.0
- Extensions: lonefy.vscode-JS-CSS-HTML-formatter-0.2.1, wmaurer.join-lines-0.1.5

Steps to Reproduce:

1. cmd+p
2. type the name of a file in the root of the project
3. the blue status indicator moves at the bottom of the search box, but it never provides a link to the file.

**Comment by chrmarti** [comment]
@aaronsnyder Could you copy your search.exclude and files.exclude settings here? If you have customized these at all.

**Comment by aaronsnyder** [comment]
Hey @chrmarti, 

I have an files.exclude setting, but no search.exclude:

`"files.exclude": { "**/._*": true }`

Also, since I posted this issue, I have seen this feature work *_some of the time_*. This makes me think that it's worth noting that the code I'm editing lives in a shared drive on a dedicated development server, and I'm accessing the code via a samba share. While I could see that this might cause some delay in indexing the file system, I also never had this problem with Sublime Text, so am hoping it's fixable. 

Let me know if you have any further questions!

Aaron

**Comment by chrmarti** [comment]
@aaronsnyder Could you run `time (find . -type file | wc -l)` from the folder you open VSCode on and copy the output here?

**Comment by aaronsnyder** [comment]
@chrmarti 84244

For the record, I had to ssh to my dev vm, because running that from my Mac took several minutes until I finally cancelled it. 😃

**Comment by chrmarti** [comment]
We are using `find` to list the files in cmd+p, if that is slow, cmd+p will be slow. I'm surprised it is as slow as you report for 84k files, maybe there is an underlying problem?

**Comment by aaronsnyder** [comment]
Ok, well, knowing that you're using find, I'm willing to say that this is probably something on my end. Admittedly, one of the reasons I switched to Code from Sublime Text was that Sublime Text never updated my file structure when changes occurred, so I'd rather this be slow than wrong. 😄 

Thanks very much for taking the time, @chrmarti!

**Comment by chrmarti** [comment]
I wonder if `find` gets stuck. Does running `find . -type file` from the folder you open VSCode on produce any output?

**Comment by aaronsnyder** [comment]
I get pretty steady output, but it does take forever (maybe two results a second, on average). In looking at the output, however, I wonder if it wouldn't benefit me to have Code ignore my vendor directory, which houses the brunt of the code in these projects, and I never use cmd+p for...

**Comment by aaronsnyder** [comment]
Filtering out the vendor/ directory made CMD+P significantly more useful-- it now works exactly like I'd expect. Not sure if this is the ideal solution, but will leave that up to you and your team. I'm ok with it in this case.

**Comment by chrmarti** [comment]
`find` being so slow is unexpected. Using more exclusion filters is a good solution. Thanks.
