### ISSUE TITLE
[vscode.dev] vscode.env.openExternal doesn't invoke protocol handler for `vsls:` scheme 

### ISSUE THREAD

**Issue by jramsay** [microsoft/vscode#136139]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:55:21.000Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36 Edg/95.0.1020.30

Steps to Reproduce:

1. Guest joins a Live Share session on vscode.dev
2. Guest attempts to use the `Open in VS' option that is available from the _Remote Indicator_ & _Command Palette_

Expected: 
The protocol handler for vsls links should be invoked, or the user should be presented with a dialog if they don't have a default app selected for the "VSLS" scheme 

Actual:
A new tab opens  and simply loads vscode.dev

Internally this calls:

**vscode.env.openExternal(vscode.Uri.parse("vsls:?action=join&workspaceId=633224A091B8262AD7F605B5D29B59994D6Y"));**

If you paste the same uri into a browser address bar you do see the expected behavior. 

![image](https://user-images.githubusercontent.com/8161247/139511119-fb8384cc-9614-4902-aa71-e8be3e9ecb13.png)

You can then select Visual Studio 2022.

- Does  vscode.env.openExternal support schemes other than `vscode:`?
- Is there something we should be doing differently on our end to invoke the `vsls:` protocol handler?

thanks!

**Comment by joaomoreno** [comment]
This is happening because the string vsls is both used as the scheme for LiveShare workspace URIs as well as the scheme for the system protocol handler.

Moving the discussion to another issue.

**Comment by jramsay** [comment]
Hi @joaomoreno! Can you add the other issue here or @ me on it so I can keep track of it?
