### ISSUE TITLE
Provide Access to a TextEditors Decorations for Testing Purposes

### ISSUE THREAD

**Issue by swissmanu** [microsoft/vscode#136164]
## Context

I am the developer of https://github.com/swissmanu/rxjs-debugging-for-vscode. The extension augments vscode with RxJS specific information when debugging code using text editor decorations.

In order to improve test coverage, I currently look into e2e/integration testing for vscode extensions. My first test case runs fine so far (https://github.com/swissmanu/rxjs-debugging-for-vscode/blob/issue-49/packages/extension-e2e/src/extension.test.ts#L69). Unfortunately though, I could not find a way to assert text editor decorations using the API exposed by vscode.

## Feature Request

Provide a way to access and assert decorations of a `TextEditor` for testing purposes.

----

Let me know if I can provide any further insight regarding this request or if there are any loose ends I could pick up for a prototype implementation.

**Comment by alexdima** [comment]
@swissmanu I think you want to assert that you are adding text editor decorations from your code. Making sure that those decorations are there and rendered is something that we test in vscode, so you should not need to test that. I suggest to use an injection pattern, where you inject a different implementation that spies on all calls that you make. e.g.

```ts
interface ITextEditorDecorationsSetter {
  set(textEditor: TextEditor, decorationType: TextEditorDecorationType, rangesOrOptions: readonly Range[] | readonly DecorationOptions[]): void;
}

// the default implementation just forwards the call to the vscode API
class TextEditorDecorationsSetter implements ITextEditorDecorationsSetter {
  set(textEditor: TextEditor, decorationType: TextEditorDecorationType, rangesOrOptions: readonly Range[] | readonly DecorationOptions[]): void {
      textEditor.setDecorations(decorationType, rangesOrOptions);
  }
}

// logic that will be tested
class MyDecorationLogic {
  constructor(
    private readonly decorationsSetter: ITextEditorDecorationsSetter = new TextEditorDecorationsSetter()
  ) { }

  // Use this.decorationsSetter for setting decorations on text editors
}

// ... in test:
const decorationsSetterSpy = new class implements ITextEditorDecorationsSetter {
  // ... implement here a `set` method that collects all the set decorations
}
// ... assert decorations have been set
}
```

**Comment by swissmanu** [comment]
@alexdima mmmh, i see! thank you for your reply. i tried something similar by sneaking a mock into vscode's API, but this approach is much more clear (and will probably actually work 😅).

will give it a try. 🙏🙌
