### ISSUE TITLE
add a command like triggerSuggest that only opens if there are suggestions

### ISSUE THREAD

**Issue by Gregoor** [microsoft/vscode#136178]
I am currently using

```ts
vscode.commands.executeCommand("editor.action.triggerSuggest")
```

to trigger suggestions after my extension takes over typing.

Now that always opens the suggestion box even if there are no suggestions. This make it feel quite clunky. I'd much prefer it behaving like normal typing in VSCode, where the box asynchronously pops up if there are suggestions. Can we have a new command for that?
Or is there a manual way to listen for suggestions and only trigger the box if necessary?

**Comment by jrieken** [comment]
There are two modes for IntelliSense: `Explicit` and `Auto`. With auto the UI is more "shy" eg won't show while loading and when there are no event. I have now pushed a change that allows to set `Auto` mode when using the `triggerSuggest` command, this should do it

```
vscode.commands.executeCommand("editor.action.triggerSuggest", { auto: true})
```

**Comment by Gregoor** [comment]
/verified

Lovely, works as expected. Thanks again for the swift help!
