### ISSUE TITLE
Accessibility: escape HTML entities in screenreader-only messaging 

### ISSUE THREAD

**Issue by zersiax** [microsoft/vscode#136161]
In some messaging for screen readers, possibly extension-specific, the string sent to the ARIA-marked up region isn't getting extraneous HTML entities filtered out which leads to some ...interesting output. Please observe:

```
choices, choices (iterable): An iterable yielding options; will only be unrolled, Handles fuzzy choice of an attribute. Args:\ &nbsp;&nbsp;&nbsp;&nbsp;choices (iterable): An iterable yielding options; will only be unrolled\ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;on the first call.\ &nbsp;&nbsp;&nbsp;&nbsp;getter (callable or None): a function to parse returned values, hint 
``` 

This is coming from the Python extension's typehinting; I don't know if others do this as well or if they are hooking into a VS code-general mechanism. I would expect the latter.
Can these be sanitized so we don't get a bunch of non-breaking space glyphs in our output? Much thanks :)
@isidorn this one may be of interest to you.

**Comment by isidorn** [comment]
@zersiax thanks for filling this, I understand the issue, however I can not reproduce it.
Can you share a small python program for which you can reproduce this problem? Just so I try to get it on my machine and investigate more. Thanks!

**Comment by isidorn** [comment]
@zersiax django-based app might also work. Whatever is the easiest for you that you can consistently reproduce. Thanks!

**Comment by zersiax** [comment]
In this repo: https://github.com/zersiax/django-allthefoods
is the code that I initially got the problem in. In the nomspot app's factories.py,  line 16, the problem came up when entering the first parenthesis, it telling me what kind of argument it was expecting. Does that help?

**Comment by isidorn** [comment]
@zersiax I just tried to repro using that issue and I could not.
I believe the screen reader will read just whatever is coming from the python extension. We do not specially message this content.

@brettcannon might you have an idea when would the python extension offer parameter hints which contain non breaking spaces: `&nbsp;&nbsp;&nbsp;&nbsp`

**Comment by brettcannon** [comment]
@zersiax which language server are you using? Pylance or Jedi?
