### ISSUE TITLE
Uninstall extension goes back to previous version

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#13611]
- VSCode Version: 1.6
- OS Version: OS X 10.11.6

1. Get Vim extension at 0.3
2. Updating it to 0.3.7
3. Uninstalling it, it goes back to 0.3. Instead should have removed Vim extension altogether.

This is caused by when upgrading packages VSCode doesn't clean up previous versions of the same extension. 

```bash
Code > ls ~/.vscode/extensions
vscodevim.vim-0.3.0  vscodevim.vim-0.3.7
```

**Comment by isidorn** [comment]
@octref always try to assign issues to owners :) If you are not sure who is an owner of an area a good hint is to look in a history of some file on gitHub - in this case any extension file would match mr Moreno

**Comment by octref** [comment]
@isidorn Thanks. Will do next time!

**Comment by joaomoreno** [comment]
#12761
