### ISSUE TITLE
copy workspace path keybinding

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#136151]
Issue Type: <b>Feature Request</b>

i use external terminal for starting my servers (windows terminal preview). in order to get to the workspace i have to right click on any folder -> copy path, go to WTP paste the path -> remove the folder name from path and then start server.
is there any way i can copy the root workspace path directly (assign keybinding i mean).
i have key binding to copy folder path, however in this case i have to manually highlight the folder and then the keybinding works (and still need to remove the folder name if i want to get to the root workspace folder)

expected:
keybinding for copying the path to root workspace folder.

VS Code version: Code - Insiders 1.62.0-insider (ff1e16eebb93af79fd6d7af1356c4003a120c563, 2021-10-29T05:16:23.014Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Maybe use an extension. A Marketplace search yielded https://marketplace.visualstudio.com/items?itemName=Malashevskyi.copy-workspace-path

But also see the author's "sad story" in case you end up not actually needing to install it.

https://github.com/malashevskyi/vs-code-copy-workspace-path#copy-workspace-path-extension

**Comment by sanket-bhalerao** [comment]
`ctrl + shift +c` works as expected. thanks.
