### ISSUE TITLE
Intellisense autocomplete not working on debug console on C# console projects 

### ISSUE THREAD

**Issue by devmet34** [microsoft/vscode#136140]
Issue Type: <b>Bug</b>

To reproduce problem; open a new folder then create a c# console project entering "dotnet new console" command on terminal window. In the Main method place a breakpoint, debug the app. After progam paused on breakpoint test intellisense on debug console.

Vscode and extensions are up to date. 

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.16
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.3
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
node-debug2|ms-|1.43.0
powershell|ms-|2021.10.2
java|red|1.0.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1

</details>

**Comment by gjsjohnmurray** [comment]
/extC#

Extensions are responsible for providing this feature.
