### ISSUE TITLE
QuickPick: `$(loading~spin)` is broken on typing `S`

### ISSUE THREAD

**Issue by zardoy** [microsoft/vscode#136172]
Steps to Reproduce:

1. Code:
```ts
await vscode.window.showQuickPick(['$(loading~spin) start'])
```
2. Type s
### Actual result:

![image](https://user-images.githubusercontent.com/46503702/139552782-bf94c46d-bb5f-4e72-8dcd-1f79e9cc1889.png)

### Expected Result:

First s of *start* is highlighted and icon isn't broken

**Comment by TylerLeonhardt** [comment]
verification: steps in issue are good
