### ISSUE TITLE
Incorrect class definition suggestion

### ISSUE THREAD

**Issue by oleg-slapdash** [microsoft/vscode#136252]
Issue Type: <b>Bug</b>

1. Create a typescript jsx file, e.g. test.tsx,
2. Write the following code:
```
export default function Test() {
  return null;
}
```
3. Remove `null` and type `<div class` press TAB. It suggest creating a new class with in JSX syntax which is incorrect:
```
export default function Test() {
  return <div class name {
    constructor(parameters) {
      
    }
  }
}
```

Demo:
![2021-11-01 18 01 08](https://user-images.githubusercontent.com/73438352/139749324-44589e14-9c17-44a8-aea0-b27a4b4cfa66.gif)

Would also appreciate any workaround, including disabling that specific suggestion.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.13GB free)|
|Process Argv|-psn_0_14380470 --crash-reporter-id 598b540e-1f56-4323-af49-94f26544babf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-modules|cli|0.3.2
js-codeformer|cms|2.4.1
jsrefactor|cms|3.0.1
bracket-pair-colorizer-2|Coe|0.2.1
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
pgsql|dou|0.1.3
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
auto-rename-tag|for|0.1.9
stylelint-disable-snippets|hed|1.0.3
search-node-modules|jas|1.3.0
intellij-idea-keybindings|k--|1.5.0
refactorix|kri|0.3.6
git-graph|mhu|1.30.0
vscode-duplicate|mrm|1.2.1
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.3
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
cpptools|ms-|1.7.1
color-highlight|nau|2.5.0
tsserver-live-reload|rbu|1.0.1
partial-diff|ryu|1.4.3
svg-preview|Sim|2.8.3
vscode-fileutils|sle|3.4.5
rewrap|stk|1.14.0
code-spell-checker|str|2.0.12
move-ts|str|1.12.0
vscode-stylelint|sty|1.0.3
vscode-open-in-github|sys|1.15.0
local-history|xyz|1.8.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
That's just the standard class snippet kicking in

You can disable if by setting `"editor.snippetSuggestions": "none"` or by getting proper Intellisense by adding a import so that VS Code knows you are working with JSX

**Comment by oleg-slapdash** [comment]
@mjbvz Can you please clarify "by adding a import" ? In this example react is clearly imported and it clearly suggests `className` but still suggests syntactically incorrect snippet FIRST.

<img width="651" alt="Screen Shot 2021-11-01 at 20 16 37" src="https://user-images.githubusercontent.com/73438352/139759307-3792d46c-19ff-4ef7-8d17-d3e44c74b18f.png">


Disabling the global option (`"editor.snippetSuggestions": "none"`) may disable some other snippets that are actually useful.

**Comment by mjbvz** [comment]
Looks like you already have the import since `className` is showing. The snippet just shows up first because it matches the word `class` 

See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_can-i-remove-snippets-from-intellisense if you want to just hide a specific snippet
