### ISSUE TITLE
css not working

### ISSUE THREAD

**Issue by vpsingh000** [microsoft/vscode#136208]
Issue Type: <b>Feature Request</b>

my body css is not perfect working by coding

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

**Comment by aeschli** [comment]
Can you please add more details on what you are trying to achieve?
- add a small HTML code sample
- describe the steps you are doings
- describe what you are are seeing
- describe what you are expecting to see
Screenshots are also helpful
