### ISSUE TITLE
After javascript debugger can't find session it never shows as connected

### ISSUE THREAD

**Issue by Hadakajime** [microsoft/vscode#136200]
Issue Type: <b>Bug</b>

If something causes your javascript debug process to terminate (even when just trying to stop your debugger)

![image](https://user-images.githubusercontent.com/20448845/139604095-73ab0750-a8a0-4f74-9485-a24e611fcf02.png)

then the first attempt you try to restart the debugger it will say "cannot find session"

![image](https://user-images.githubusercontent.com/20448845/139604056-dd90c40b-03ec-48c3-a3ee-9ad0ebeb6d8d.png)

subsequent attempts will actually start the process, but the debug controls still display a disconnected state.

disconnected stepper control bar:
![image](https://user-images.githubusercontent.com/20448845/139604128-b4fc3727-4d39-418b-ad93-1bb1cc01d8ab.png)

blue status bar:
![image](https://user-images.githubusercontent.com/20448845/139604148-67b4a7b2-207f-4dc2-ba7c-f2e992018ca0.png)

If you set a breakpoint that halts the process, then it will finally change to the orange status bar and the stepper control bar becomes active.

shouldn't it show as connected straight from restarting the process? not requiring a breakpoint to catch it?

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (4.51GB free)|
|Process Argv|--crash-reporter-id 9d1b4a74-6c23-44d3-9db5-383def926efe|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|24.92GB (2.09GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
remote-containers|ms-|0.202.5
remote-wsl|ms-|0.58.4
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
restore-terminals|Eth|1.1.6
vscode-graphql|Gra|0.3.18
vscode-docker|ms-|1.17.0
vsliveshare|ms-|1.0.5065
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vetur|oct|0.35.0
prisma|Pri|3.3.0
indenticator|Sir|0.7.0
language-stylus|sys|1.13.0
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by weinand** [comment]
A "restart" only makes sense if there is a an active debug session. If the session has terminated, restart should not be disabled (and the debug toolbar should no longer be visible anyway). 

I was not able to reproduce your "If something causes your javascript debug process to terminate (even when just trying to stop your debugger)". When stopping the debugger, the debug sessions ends and the debug toolbar disappears.

Could you please provide an example for how to do this?

**Comment by Hadakajime** [comment]
closed/reopened vscode. plugin RestoreTerminals runs 3 terminal commands to start 2 web frontend services ,and tsc for the backend:

![image](https://user-images.githubusercontent.com/20448845/139751676-52801104-1564-4f83-86f1-a6d8caacf34b.png)

launch profile in use:

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-node",
      "request": "launch",
      "name": "DEV launch",
      "envFile": "${workspaceFolder}/../build/wywm-dev-local.env",
      "outputCapture": "std",
      "program": "${workspaceFolder}/dist/graphql/server.js",
      "args": [
        "migrate",
        "--novalidation"
      ],
      "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js",
        "<node_internals>/**/*.js"
      ]
    },
```
started the debugger:

![image](https://user-images.githubusercontent.com/20448845/139752359-46906bb4-831b-41ab-bbec-1631259cffc6.png)

startup sequence connects to the database and may run a bunch of migrations if necessary.

Clicked stop button:

![image](https://user-images.githubusercontent.com/20448845/139752474-c19979f6-baa8-4ebe-81d3-031be33f29c2.png)

clicked stop button again (just because i want to see what happens):

![image](https://user-images.githubusercontent.com/20448845/139752525-49b65c7a-0f9e-4a74-a92d-356e08fdc2ac.png)

click restart debugger:

![image](https://user-images.githubusercontent.com/20448845/139752890-5f7b8abf-fa00-42fa-96dc-8884da304551.png)

click stop (only once):

![image](https://user-images.githubusercontent.com/20448845/139752922-f0fa3a85-632b-48be-9078-f05cad869714.png)

click restart:

![image](https://user-images.githubusercontent.com/20448845/139752964-b657a420-4751-415c-b5e3-4ddffbb31885.png)

click restart again (i didnt dismiss the session notification, so it's still visible):

![image](https://user-images.githubusercontent.com/20448845/139753043-57032c63-4203-4b73-aea1-41b8fee925eb.png)

**Comment by Hadakajime** [comment]
We can do a screen share if you like?

It's reproducible on demand. 
Affects me all day every day...

**Comment by Hadakajime** [comment]
I have attached a trace log of the following actions:
[vscode-debugadapter-763a0cc6.json.gz](https://github.com/microsoft/vscode/files/7929218/vscode-debugadapter-763a0cc6.json.gz)


1. Start debugger
2. Wait till startup routines complete
3. Stop Debugger once
4. Attempt restart debugger once

Here is a screenshot after stopping the debugger once:
![1_after_stop](https://user-images.githubusercontent.com/20448845/150875018-17e15dfb-cc28-4a60-81b4-751ad678e553.png)

Here is a screenshot after then attempting a restart once:
![2_attempt_restart](https://user-images.githubusercontent.com/20448845/150875109-f197000b-dd04-4f92-b38b-09e075af7961.png)

**Comment by maziac** [comment]
What is the status on this?
I'm also seeing the "cannot find session".
