### ISSUE TITLE
Dynamic debug configs are never removed from the debugging menu

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode#136250]
Does this issue occur when all extensions are disabled?: No, relies on extensions that provide dynamic debug configs

- VS Code Version: 1.62.0-insider (Universal)
- OS Version: Darwin x64 20.6.0

Full version info:
<details>

Version: 1.62.0-insider (Universal)
Commit: ff1e16eebb93af79fd6d7af1356c4003a120c563
Date: 2021-10-29T05:14:09.436Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

</details>

Steps to Reproduce:

In this example I'll use the Node.JS dynamic debug configurations that it creates for npm scripts inside the package.json. This repros with any repo with npm scripts in a package.json. But for clarity I'm using https://github.com/alexweininger/StartupAdventurer.

1. Ctrl + P, type "debug", select Node.js... select a "Run Script: build" pick.
2. Run "Run Script: build" from the Run and Debug view.
3. Delete the "build" script from package.json.
4. Reload VS Code.

Expected: 
"Run Script: build" should not appear in the Run and Debug view dropdown. 

Actual:
"Run Script: build" appears in the Run and Debug view dropdown. And when run gives an error with message: `Configuration 'Run Script: build' is missing in 'launch.json'.`

Maybe the experience should be more like:

When an extension provides dynamic debug configurations [A, B, C] from calling `provideDebugConfigurations`. And the next time `provideDebugConfigurations` is invoked it returns configurations [A, B]. Since configuration C is no longer being provided, it should be removed from cache/UI/etc.

One issue might be how to determine if one configuration is equal to another, and I think the easiest would be to just use the name of the configuration. Or maybe an id property could be added.

If this is too complicated, I think at the very least providing a way to clear the cached debug configurations that the extension has provided in the past would be useful.

cc: @isidorn this isn't a blocker for static web apps debugging, however I feel strongly that with a little love the dynamic debug configs could become 10x more useful.

**Comment by weinand** [comment]
Yes, the proposed behavior makes sense and we should fix this:
the set of dynamic configs returned from `provideDebugConfigurations` should replace the set previously returned from that method. Today it seems we are merging the sets.

**Comment by isidorn** [comment]
@alexweininger thanks for providing feedback and keep the good issues coming 👏 
@roblourens let me know if I can help somehow here. All the dynamic config handling is done by the debug configuration manager somewhere around [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugConfigurationManager.ts#L410)

**Comment by connor4312** [comment]
A while ago I added an option to the debug quick access to remove such configs:

<img width="757" alt="image" src="https://user-images.githubusercontent.com/2230985/206801696-ccf26157-d41e-43f6-9681-011d00416a62.png">
