### ISSUE TITLE
Characters come from IME always duplicated in terminal

### ISSUE THREAD

**Issue by shizhx** [microsoft/vscode#136271]
Issue Type: <b>Bug</b>

This bug first occur on 1.61, but still not fixed on latest insiders edition.
Not only chinese charaters, all charaters(len >= 2) come from IME be duplicated.
Here is the reproduce gif:

![Peek 2021-11-02 14-53](https://user-images.githubusercontent.com/7520007/139800017-f8d1393b-be1a-4d9b-831d-3df35978a8be.gif)

VS Code version: Code - Insiders 1.62.0-insider (673165ca934c05d63fcab74bac7c819c32528c64, 2021-11-01T08:36:36.991Z)
OS version: Linux x64 5.4.124-1-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.51GB (1.63GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id d7f43e64-0004-4b98-b5af-f7f5e7961c5d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by meganrogge** [comment]
I can't reproduce the issue. can you turn on escape sequence logging and provide me with the logs?
