### ISSUE TITLE
Messy code in filename after enabling indexing

### ISSUE THREAD

**Issue by imba-tjd** [microsoft/vscode#136276]
If the filename is not english, it will show messy code after enabling indexing

Tried github.dev and vscode.dev in FF and Edgium

![image](https://user-images.githubusercontent.com/24759802/139814119-b4799a24-2e8f-4cf3-bd7a-c3b53e2b6f1c.png)

![image](https://user-images.githubusercontent.com/24759802/139814452-4d677b5f-5af8-4901-a93e-d14fa1b56033.png)

![image](https://user-images.githubusercontent.com/24759802/139814077-e1a3452b-4666-44f4-a302-51fe95567232.png)

Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
Embedder: github.dev

**Comment by JacksonKearl** [comment]
Thanks for reporting, could you give a link to a repo where you observed this happening?

**Comment by imba-tjd** [comment]
https://github.dev/imba-tjd/test2

**Comment by JacksonKearl** [comment]
Thanks, this should be fixed in an upcoming release.
