### ISSUE TITLE
Ranger features!!!

### ISSUE THREAD

**Issue by happysmile12321** [microsoft/vscode#136289]
Open a float window of terminal in vscode!!!
In vim,we use current window to open a pop menu float on the center with ranger,
so is there to let the terminal to float the center?
or just a panel on the center,and we can develop plug to operate files like ranger.

**Comment by happysmile12321** [comment]
By the way,thanks microsoft,vscode is No1 editor or IDE in the universe.😂

**Comment by IllusionMH** [comment]
Separate floating windows are already tracked in #10121

However you already can position terminal in bottom (if you position Panel in bottom), in sidebar that is linked to Activity bar, in editor area and with #132893 in alternative sidebar - just pick one while there are no floating windows (I doubt that there are plans for floating "panels").
