### ISSUE TITLE
Debug Call Stack viewport vertical scroll cuts off the bottom item

### ISSUE THREAD

**Issue by jcward** [Microsoft/vscode#1362]
In debug mode, in the Call Stack viewport, whenever the list is larger than the view area and the vertical scrollbar appears, the bottom item is not reachable by scrolling.

Note that even with multiple threads, it cuts off exactly one item.

The same is not true for the variables viewport, the variables viewport works correctly.

**Comment by jcward** [comment]
This gif highlights the problem -- the highlighted item at the end can't be reached by scrolling the viewport:

![test](https://cloud.githubusercontent.com/assets/2192439/11831799/499b20b0-a36f-11e5-94e6-90e007024a47.gif)

**Comment by isidorn** [comment]
Thanks - nice catch!
