### ISSUE TITLE
Popular Extensions badge displays an inflated count

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#136259]
Not all 31k extensions are popular. :-)

![image](https://user-images.githubusercontent.com/8586769/139759646-6d659737-3c96-4689-b021-ddd7d7b32f49.png)

**Comment by sandy081** [comment]
Popular section is not a limited set. It shows all extensions sorted by popularity which is installed count. 
- May be we can rename this section or 
- Show only top 10/20/100 or
- Do not show the number badge

Note that we also show the same when you select **Most Popular** filter.

@isidorn any opinions?

**Comment by isidorn** [comment]
Showing top100 or not showing the badge at all both work for me.
Badge showing this random number does not bring any value.
And showing more than 100 does not bring any value to the user.

**Comment by sandy081** [comment]
I would go with not showing the badge for this section. Since we support infinite scrolling, it is up to user to scroll down to see more.
