### ISSUE TITLE
Ctrl + W stopped working

### ISSUE THREAD

**Issue by herealways** [microsoft/vscode#136230]
Issue Type: <b>Bug</b>

Press Ctrl + W, it will not close the current editor. When changing keyboard shortcuts, it cannot even catch Ctrl + W.
It should not be my keyboard's issue, since I can use Ctrl + W to close a chrome tab.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-84-generic
Remote OS version: Linux x64 5.4.0-84-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (19.99GB free)|
|Process Argv|--crash-reporter-id ced28bcf-009f-4cb9-88c8-5e56c3c23eaa|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: node2|
|OS|Linux x64 5.4.0-84-generic|
|CPUs|AMD Ryzen 7 4800U with Radeon Graphics (16 x 1397)|
|Memory (System)|30.85GB (21.33GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: node2|
|OS|Linux x64 5.4.0-84-generic|
|CPUs|AMD Ryzen 7 4800U with Radeon Graphics (16 x 1397)|
|Memory (System)|30.85GB (21.33GB free)|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/wiki/Keybinding-Issues for troubleshooting tips.

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `Ctrl+W`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by herealways** [comment]
> Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `Ctrl+W`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):
> 
> * Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
> * This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
> * Press exactly the keybinding you desire.
> * check what VS Code detects and what command is invoked.
> 
> If you are having trouble understanding the output, please feel free to paste here and I can try to help.

Hi alexdima, thank you for your help. I'm sorry I didn't provide enough information. Here is the debug log when hitting "Ctrl + W"

```
[2021-11-03 09:26:30.422] [renderer1] [info] Starting extension host with pid 11624.
[2021-11-03 09:26:30.622] [renderer1] [error] [Extension Host] (node:11624) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
[2021-11-03 09:26:41.535] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
[2021-11-03 09:26:41.535] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
[2021-11-03 09:26:41.536] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2021-11-03 09:26:42.000] [renderer1] [info] [KeybindingService]: + Ignoring single modifier ctrl due to it being pressed together with other keys.
[2021-11-03 09:26:46.206] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
[2021-11-03 09:26:46.206] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
[2021-11-03 09:26:46.206] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2021-11-03 09:26:46.594] [renderer1] [info] [KeybindingService]: + Ignoring single modifier ctrl due to it being pressed together with other keys.
```

Here is my `keybindings.json` config. (for now I use "Ctrl + Shift + W" to replace "Ctrl + W" since "Ctrl + W doesn't work on my machine")

```
// Place your key bindings in this file to override the defaultsauto[]
[
    {
        "key": "ctrl+n",
        "command": "extension.advancedNewFile"
    },
    {
        "key": "ctrl+alt+n",
        "command": "-extension.advancedNewFile"
    },
    {
        "key": "ctrl+down",
        "command": "workbench.action.terminal.focusNext",
        "when": "terminalFocus"
    },
    {
        "key": "ctrl+up",
        "command": "workbench.action.terminal.focusPrevious",
        "when": "terminalFocus"
    },
    {
        "key": "ctrl+e",
        "command": "ctrl+e",
        "when": "terminalFocus"
    },
    {
        "key": "ctrl+f4",
        "command": "-workbench.action.closeActiveEditor"
    },
    // {
    //     "key": "ctrl+w",
    //     "command": "-workbench.action.closeGroup",
    //     "when": "activeEditorGroupEmpty && multipleEditorGroups"
    // },
    // {
    //     "key": "ctrl+w",
    //     "command": "-workbench.action.terminal.killEditor",
    //     "when": "terminalEditorFocus && terminalFocus && terminalProcessSupported && resourceScheme == 'vscode-terminal'"
    // },
    {
        "key": "ctrl+shift+w",
        "command": "workbench.action.closeActiveEditor"
    },
    {
        "key": "ctrl+w",
        "command": "workbench.action.closeActiveEditor"
    }
]
```

Thank you!

**Comment by alexdima** [comment]
@herealways Thank you for the extra information. From your log, it looks like `Ctrl+W` does not reach VS Code:
```
/ Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
| Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
\ Keyboard event cannot be dispatched in keydown phase.
+ Ignoring single modifier ctrl due to it being pressed together with other keys.
/ Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
| Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
\ Keyboard event cannot be dispatched in keydown phase.
+ Ignoring single modifier ctrl due to it being pressed together with other keys.
```

There is nothing we can do on our side if we don't receive the keybinding from the OS. Most likely, there is some software or driver that you have on that machine that is "eating up" keybindings at a global level or perhaps there is some OS feature that is bound to `ctrl+w`. For reference, this is how pressing `ctrl+w` looks like on a clean Windows installation:

```
/ Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
| Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
\ Keyboard event cannot be dispatched in keydown phase.
/ Received  keydown event - modifiers: [ctrl], code: KeyW, keyCode: 87, key: w
| Converted keydown event - modifiers: [ctrl], code: KeyW, keyCode: 53 ('W')
| Resolving ctrl+W
\ From 3 keybinding entries, matched workbench.action.closeActiveEditor, when: no when condition, source: built-in.
```
