### ISSUE TITLE
SCM - Action button polish

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#136275]
- [x] Left alignment is incorrect as the input field has a larger left margin
- [x] Sync icon should appear before the text to be consistent with the `Publish` button
- [x] Sync and Publish icon should not have a left margin so that the content is centred
- [x] Rows that contain the input field and button should not have a hover feedback

<img width="605" alt="image" src="https://user-images.githubusercontent.com/3372902/139813597-bf740fc1-3b2e-4079-99db-e1d6e6209c65.png">

<img width="604" alt="image" src="https://user-images.githubusercontent.com/3372902/139813686-1e9bfdcf-022e-4260-b6ae-396a6ca6dd11.png">

//cc @misolori

**Comment by lszomoru** [comment]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/3372902/139834817-2cc4b027-c36e-4ab4-9e61-18de0b3bcdb0.png">

<img width="494" alt="image" src="https://user-images.githubusercontent.com/3372902/139834888-b89aad52-5144-4893-ac16-b5799278cbec.png">

**Comment by misolori** [comment]
Beautiful!

**Comment by kimadeline** [comment]
When using VS Code 1.63.0-insider commit 0cc0904 I noticed the following:
- the "Sync" button isn't as wide as the message text box
- when resizing the panel to be at its minimum size the buttons overflow:

![image](https://user-images.githubusercontent.com/51720070/144329198-ea75b0d3-806d-4f33-af10-01438df18795.png)

- when clicking on the rows there is a selection outline; clicking on the message row focuses on the text box, but clicking on the button row doesn't select the button. Is it expected?

https://user-images.githubusercontent.com/51720070/144329321-95bf6d62-39a5-4e72-89a6-cec02a93da49.mp4

**Comment by lramos15** [comment]
Reopening as verification found based on @kimadeline's comments

**Comment by lszomoru** [comment]
Thanks @lramos15. I will push this out to the next milestone.

**Comment by heartacker** [comment]
hi, @lszomoru  could you please add an option to git sync button
1. sync by default
2. sync with rebase
like:
https://github.com/microsoft/vscode/issues/135992#issuecomment-983825268
![image](https://user-images.githubusercontent.com/1876302/149714461-4ee8a114-c178-4583-862c-01d37ffb0f73.png)

and if 
```
"git.rebaseWhenSync": true
```
then the default button action will be sync change with rebase

**Comment by lszomoru** [comment]
Closing this issue as it is scoped to the sync button overflow functionality. We have settled on the following:

Full label when there is enough space:
![image](https://user-images.githubusercontent.com/3372902/150799177-8cdc8bdd-071e-4121-8bb1-f4e0a4691990.png)

Trimmed label where there is not enough space:
![image](https://user-images.githubusercontent.com/3372902/150799311-b5b2ea6c-6b30-43f8-a398-e60921c7e916.png)

**Comment by LinqLover** [comment]
Very nice, thank you!
