### ISSUE TITLE
Unable to save with sudo on M1 Mac

### ISSUE THREAD

**Issue by merrellb** [microsoft/vscode#136223]
To recreate:
Edit a file requiring sudo (eg `/private/etc/hosts`)
When saving, VSCode will request sudo permissions and, after granting, gives the following error:
```
Failed to save 'hosts': Command failed: ./applet /bin/sh: ./applet: Bad CPU type in executable
```

I do NOT have Rosetta installed but understand VS Code is supposed to be M1 compatible.  Here is the version info:
```
Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:03:09.437Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.1.0
```

**Comment by bpasero** [comment]
I cannot reproduce and I am on a M1 as well.

@deepak1556 thoughts?

**Comment by deepak1556** [comment]
Not sure if that applet can be converted to universal, might also be worth looking at alternatives for sudo-prompt given that repo is now archived.

**Comment by bpasero** [comment]
I would suggest to fork the module and convert that applet to universal if that is straightforward.

**Comment by deepak1556** [comment]
I don't see the source for the applet under the user repositories, will have to reach out to the author.

**Comment by bpasero** [comment]
Maybe: https://github.com/nathanielks/electron-sudo

**Comment by bpasero** [comment]
@merrellb would you be able to test this scenario again from the following build that includes a potential fix: https://az764295.vo.msecnd.net/insider/5db2a238c6395722f1240121fdf7e248aafc6825/VSCode-darwin-arm64.zip

**Comment by merrellb** [comment]
Thanks for all your efforts on this @bpasero (and @deepak1556) .  I discovered this on a new M1 Mac where I had not yet installed Rosetta but eventually caved in and installed it.  Unfortunately it doesn't appear Rosetta can be easily uninstalled for testing.   Happy to give this another go the next time I have a fresh Mac install but don't foresee that in the immediate future...

**Comment by bpasero** [comment]
**Verification**
* on a mac with ARM chip
* without Rosetta 2 installed ([1])
* use [build](https://az764295.vo.msecnd.net/insider/5db2a238c6395722f1240121fdf7e248aafc6825/VSCode-darwin-arm64.zip)
* open `/etc/hosts`
* try to edit (in the comment area!!!)
* from the error retry as sudo
* verify you get a prompt and save works

**Comment by DonJayamanne** [comment]
@bpasero I take it you just re-compiled the applet for universal & updated the package with the base64 encoded string (is that right?)

**Comment by bpasero** [comment]
@DonJayamanne yes! Here is what I did:
* decode the base64 encoded value
* unzip it
* open the apple script in apple script editor
* export it as application bundle (I have Rosetta 2 installed so it seems to export as universal bundle by default)
* zip it
* base64 encode it
* release as fork from https://github.com/bpasero/sudo-prompt/tree/vscode
