### ISSUE TITLE
Syntax highlighting bug with struct variables in C++

### ISSUE THREAD

**Issue by johntony366** [microsoft/vscode#136217]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.61.2
- OS Version: Windows 11 Pro (21H2) OS build: 22000.282

Steps to Reproduce:

1. Write code in C++ to create a struct variable.
2. Observe that the code for struct variable creation does not undergo syntax highlighting.

In Visual Studio Code
![image](https://user-images.githubusercontent.com/88877609/139667664-4dce5548-231f-442b-8d3d-efa35a8d1254.png)

In Visual Studio 2019 the syntax highlighting works as expected
![image](https://user-images.githubusercontent.com/88877609/139667039-893d343c-b86b-4dbf-bddc-e7e51c5b44ee.png)

**Comment by alexr00** [comment]
Can you share a copy/pastable code snippet that I can use to reproduce the issue?

**Comment by alexr00** [comment]
Thank you! Highlighting the struct properly requires semantic syntax highlighting. We don't offer that out of the box for C++. You could try installing the C/C++ extension for semantic coloring!
