### ISSUE TITLE
removing unused vars and imports on save

### ISSUE THREAD

**Issue by diw-fc** [microsoft/vscode#136287]
Although I tried many editor settings as below:
"go.lintOnSave": "off",
 "editor.codeActionsOnSave": {
     "source.fixAll": false,
 },
 "editor.formatOnSave": false,

Still editor is removing unused imports and vars. It will remove other unreached statements too... eg. after "return" whatever is written in code. Many times we do test and it is not letting us to do that. Please disable this feature ASAP. This is sucking.

This is working for reactJS, nodeJS and golang. Not tested on other languages.

**Comment by IllusionMH** [comment]
/needsMoreInfo

You forgot to fill in issue template.

Is it reproducible with all extensions disabled? Because VS Code doesn't support code operations on Go

You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by diw-fc** [comment]
> /needsMoreInfo
> 
> You forgot to fill in issue template.
> 
> Is it reproducible with all extensions disabled? Because VS Code doesn't support code operations on Go out of the box
> 
> You can try this with F1 and `>Developer: Reload Window With Extensions Disabled`

When I tried with reload with extensions disabled, it does not remove anything. It works fine. But extensions make it easier to work with specific language. In my case it is JavaScript(node.js, react.js) and golang. It is removing the unused and unreachable code in both of languages.

I have installed ESLint, jshint, Go, JSON tools, Debugger for Firefox and Docker extensions.

**Comment by IllusionMH** [comment]
Not sure why you want jshint when ESLint should provide same kind of checks and more (if configured).

Anyway you can use https://code.visualstudio.com/updates/v1_52#_troubleshooting-extension-bisect to find extension that does this and then configure it or remove if unised.

**Comment by diw-fc** [comment]
After removing the jslint, it works correctly.
Thank you for support guys....appreciated.
