### ISSUE TITLE
Add display of Unicode-chars to core to prevent malicious injections

### ISSUE THREAD

**Issue by DotCoyote** [microsoft/vscode#136290]
After finding tis new method to[ inject malicious code via unicode](https://github.com/nickboucher/trojan-source), it'd be very nice if VSCode would display unicode-chars directly out of the box, like Jetbrains does.

![unknown](https://user-images.githubusercontent.com/3854991/139852578-c61b73f8-4bac-4bb1-8a58-01e07b5d8510.png)

**Comment by yume-chan** [comment]
#116939
