### ISSUE TITLE
Built in is always used for notebook renderers

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#136247]
Issue Type: <b>Bug</b>

Create a python file with these contents:

```python
# %% Cell Error
raise new Exception('Test')
```

Run this cell in the interactive window.

Expected result:
Links show up to jump back to where the exception was thrown

Actual result:
Links are not there.

The jupyter notebook renderer is not being picked to render the error.

![image](https://user-images.githubusercontent.com/19672699/139739828-7853dea5-4d24-4a9a-b66c-b3f5acc53298.png)

VS Code version: Code - Insiders 1.62.0-insider (673165ca934c05d63fcab74bac7c819c32528c64, 2021-11-01T08:36:27.543Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (17.34GB free)|
|Process Argv|. --crash-reporter-id 108b1212-dd8c-4594-8252-c1351bf31268|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.1
prettier-vscode|esb|9.0.0
remotehub|Git|0.17.0
better-cpp-syntax|jef|1.15.10
vscode-position|jtr|1.0.3
regexp-preview|Lou|0.1.5
python|ms-|2021.11.1408613116-dev
vscode-pylance|ms-|9999.0.0-dev
jupyter|ms-|2021.10.1001408933
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.203.0
remote-ssh-edit-nightly|ms-|2021.10.19620
remote-ssh-nightly|ms-|2021.10.36984
remote-wsl|ms-|0.58.4
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.0.0
vscode-github-issue-notebooks|ms-|0.0.112
vscode-selfhost-test-provider|ms-|0.3.8
vscode-typescript-next|ms-|4.5.20211025
rpa-eslint-snippets|rav|0.0.2
rest-book|tan|4.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30382699
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsaa593:30376534

```

</details>

**Comment by connor4312** [comment]
This is using the following algorithm: https://github.com/microsoft/vscode/issues/125876#issuecomment-949004386

How do you think we should change this?

**Comment by rchiodo** [comment]
Shouldn't the second item here be being used?

- If the user has explicitly selected a renderer for X, in this notebook type and workspace, use that.
- Otherwise, if the extension providing the notebook also provides a renderer for X, use that. <-- Seems like this should be picked up
- Otherwise, if there is a built-in renderer for X, use that. (From previous comments)
- Otherwise, if there is another extension who renders mimetype X, use that.

**Comment by rchiodo** [comment]
Oh no wait. The renderers for jupyter are from a separate extension. That's the failure. Blech

**Comment by rchiodo** [comment]
I think we need something extra then. Some sort of preference for a renderer extension in our kernel?

**Comment by rchiodo** [comment]
Woot! Thanks @connor4312

**Comment by alexr00** [comment]
@connor4312 moving to November, since this isn't in the October release.
