### ISSUE TITLE
Brackets Highlight error in template string

### ISSUE THREAD

**Issue by naptestdev** [microsoft/vscode#136268]
- VS Code Version: 1.61.2
- OS Version: MacOS Big Sur 11.6

<img width="730" alt="image" src="https://user-images.githubusercontent.com/88878684/139790067-034a148d-23a3-45bc-9b54-7d9ae3f598a1.png">

**Comment by Meghpal** [comment]
Reproducible on windows as well with the setting "Bracket Pair Colorization" enabled.

![image](https://user-images.githubusercontent.com/40922889/139794065-8ad11bd8-8769-4cf5-a6c3-e447db11a294.png)

Need to handle string content inside backticks to not colorize.

![image](https://user-images.githubusercontent.com/40922889/139794775-04b731a5-aba0-40b5-97d7-93cb78b68561.png)

**Comment by hediet** [comment]
The problem here is that the typescript grammar marks that string as "other":

![image](https://user-images.githubusercontent.com/2931520/140026884-c8220050-dc97-4553-83ef-bef18a2e6501.png)

Only brackets in tokens that are marked as "string", "regex" or "comment" are ignored.

**Comment by mjbvz** [comment]
Here's what I see for:

```
`${"content {{{}}}"}`;

`${"".replace("{", "").replace("}", "")}`;
```

![Screen Shot 2021-11-05 at 1 57 26 PM](https://user-images.githubusercontent.com/12821956/140577574-3d1a7d79-e8af-4392-b879-dbffd1d42ee2.png)


Please test in VS Code insiders with extensions disabled. If you still see this issue, please the text of the code so we can make sure we're on the same page

**Comment by hediet** [comment]
I can verify that it works now in the latest VS Code insider build.

![image](https://user-images.githubusercontent.com/2931520/140623707-93098f43-0688-4859-bcc1-e3696a970c36.png)
