### ISSUE TITLE
Web Extension incorrect breakpoints positions 

### ISSUE THREAD

**Issue by devhawk** [microsoft/vscode#136242]
Issue Type: <b>Bug</b>

When I try and debug a web extension - even a trivial extension such as https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-web-sample - the breakpoints are positioned incorrectly.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.59GB (4.09GB free)|
|Process Argv|. --crash-reporter-id 7a9bf18a-2fcc-4551-8784-d5b4c66586f7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-path-tools|cg-|0.0.4
gitlens|eam|11.6.1
dotnet-test-explorer|for|0.7.7
codespaces|Git|1.3.3
remotehub|Git|0.17.0
vscode-pull-request-github|Git|0.31.1
vscode-nuget-package-manager|jmr|1.1.6
git-graph|mhu|1.30.0
vscode-docker|ms-|1.17.0
csharp|ms-|1.23.16
remote-containers|ms-|0.202.5
remote-wsl|ms-|0.58.4
test-adapter-converter|ms-|0.1.4
vscode-versionlens|pfl|1.0.9
vscode-gitignore-generator|pio|1.0.3
rest-book|tan|4.2.0
vscode-icons|vsc|11.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by devhawk** [comment]
Breakpoints as I set them in the editor before debugging:

![image](https://user-images.githubusercontent.com/8965/139727142-e5f0d4ba-4a99-4636-aa69-66e9ab35ef0e.png)

breakpoints as they appear during debugging

![image](https://user-images.githubusercontent.com/8965/139727253-fc56bcf4-adba-4b13-abc8-1d40c6945936.png)

**Comment by weinand** [comment]
I suspect this to be a problem of the generated source maps...

**Comment by rchiodo** [comment]
This seems to still be happening for me?

![image](https://user-images.githubusercontent.com/19672699/144301857-f6e72227-5621-4a75-96f9-ea8aeb620169.png)

**Comment by rchiodo** [comment]
Repro steps I took:

- Refreshed https://github.com/microsoft/vscode-extension-samples.git on my local machine
- cd to 'helloworld-web-sample'
- open folder in vs code
- Set breakpoints
- F5

**Comment by rchiodo** [comment]
/verified

![image](https://user-images.githubusercontent.com/19672699/151461808-2e2847d9-482f-44e3-8571-ba00c4dcbba0.png)
