### ISSUE TITLE
support download bin file to local device via local serial port after remote compile

### ISSUE THREAD

**Issue by githubusr2** [microsoft/vscode#136262]
HI I am working on Windows with a remote SSH session to a Linux environment in Visual Studio Code. After I compile program i need to download program to my device connected to my local serial port, but when i select flash in vscode, it let me select port :
ttys0,ttys1, obviously it is serial port from remote machine, i dont need flash to remote but to local serial port device, so how do i ? mybe it is a bug of vscode.

**Comment by yume-chan** [comment]
> but when i select flash in vscode

Where is the "flash" thing? Maybe provided by an extension?

**Comment by githubusr2** [comment]
ESD-IDF extension

**Comment by githubusr2** [comment]
![1](https://user-images.githubusercontent.com/29746247/139828817-d6c60812-4b16-4adf-a8e9-617be58537aa.png)
