### ISSUE TITLE
Icons dont appear

### ISSUE THREAD

**Issue by gwynjudd** [Microsoft/vscode#13622]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: cazzar09.Gradle-1.0.1, dbaeumer.vscode-eslint-1.0.3, donjayamanne.javadebugger-0.0.2, DotJoshJohnson.xml-1.6.0, eg2.tslint-0.5.34, heaths.vscode-guid-1.0.0, ms-vscode.csharp-1.4.1, ms-vscode.PowerShell-0.7.2, msjsdiag.debugger-for-chrome-0.5.2, redhat.java-0.0.4

Steps to Reproduce:

1. Open any workspace including files that should have icons in the explorer
2. You don't see icons

![image](https://cloud.githubusercontent.com/assets/314188/19323490/ac0551ba-9119-11e6-9bbe-cfbf680db3f3.png)

**Comment by ozanorhan** [comment]
Same here. Also I removed vscode-icons after update.

**Comment by kaiwood** [comment]
Have you tried enabling them / changing the icon theme first? In the command palette (cmd+shift-p / ctrl-shift-p), there is a command called "Preferences: File Icon Theme" where you can explicitly enable/disable them.

**Comment by ozanorhan** [comment]
@kaiwood it worked. i tried looking for a command but missed it the first time i looked. Thanks

**Comment by isidorn** [comment]
Thanks @kaiwood for helping here
This is as designed
