### ISSUE TITLE
Keyboard fails to open for mobile devices on web when editing a notebook code cell

### ISSUE THREAD

**Issue by Devon7925** [microsoft/vscode#136256]
When tapping on a code cell in a notebook the keyboard should open as it does in the regular editor. Instead it opens and then immediately closes itself, making editing impossible.

Tested on iPhone 7, in both insiders and stable on [vscode.dev](vscode.dev).

**Comment by TylerLeonhardt** [comment]
I can't reproduce this anymore. Tested on iPhone running iOS 18.2 and an iPad running iPadOS 18.2.

**Comment by Yoyokrazy** [comment]
Verified on ipad (os 18.1.1) and iphone (os 18.3). Don't have devices on hand old enough or with older OS versions to test the author's platform.
