### ISSUE TITLE
Terminal not showing.

### ISSUE THREAD

**Issue by saisuvanth** [microsoft/vscode#136212]
Issue Type: <b>Bug</b>

When I press Cntrl+T terminal isn't opening. Even if i drag it fron downwards its just showing blank screen and is not opening powershell(default).

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3450U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.94GB (0.82GB free)|
|Process Argv|-n --crash-reporter-id 918a4322-3f7a-4478-b6b8-8a896c278c14|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.27.2
flutter|Dar|3.27.0
code-runner|for|0.11.6
discord-leaderboard|Fre|2.2.0
copilot|Git|1.6.3571
vscode-pull-request-github|Git|0.31.1
discord-vscode|icr|5.7.0
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.3
remote-wsl|ms-|0.58.4
cpptools|ms-|1.7.1
vscode-react-native|msj|1.7.1
java|red|1.0.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-pack|vsc|0.18.6
vscode-icons|vsc|11.7.0
vim|vsc|1.21.10
material-theme|zhu|3.13.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/label "needs more info" terminal
