### ISSUE TITLE
Support opening a local file in a remote session via its path

### ISSUE THREAD

**Issue by carlfriedrich** [microsoft/vscode#136218]
I am working on Windows with a remote SSH session to a Linux environment in Visual Studio Code. Sometimes I want to open a local file from my Windows system in this session.

When I press <kbd>Ctrl</kbd> + <kbd>O</kbd> to open a file, Visual Studio Code offers me a button "Show local", which opens a file browser on my local computer to search a file:

![open file](https://i.stack.imgur.com/IiFoo.png)

Unfortunately it's not possible to enter my file path directly (say ```c:\myfile.txt```). Obviously in remote setups only remote paths can be entered.

I would like to see some syntax I could use to directly enter a local file path, without needing to open the file browser.

**Comment by alexr00** [comment]
@carlfriedrich you can use the setting `"files.simpleDialog.enable": true` to always use this file picker and not open the OS file picker.

**Comment by carlfriedrich** [comment]
Thanks for this quick solution @alexr00!
