### ISSUE TITLE
Distribute as msi(x)

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/vscode#136227]
Please, consider distributing the official Visual Studio Code installer for Windows as msi or msix instead of a exe binary blob. Distributing installers as exe is a bad practice from security standpoint.

**Comment by IllusionMH** [comment]
Looks like duplicate of #61793 (which doesn't include msi)

**Comment by AsciiWolf** [comment]
Yeah, I did not notice that ticket, thanks! Will write my comment there.
