### ISSUE TITLE
Github pull request not appearing in gitHub.dev VSCode instance.

### ISSUE THREAD

**Issue by littlespex** [microsoft/vscode#136234]
After navigating to a github.dev instance of VSCode, by pressing the `.` key on a pull request page, the pull request UI no longer appears. This worked previously and seems to have stopped after syncing my VSCode settings.

Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
Embedder: github.dev

**Comment by alexr00** [comment]
@littlespex what are you seeing show in this case?

**Comment by littlespex** [comment]
Just the explorer. When I click the GitHub item in the left side menu it displays the GitHub side bar, but is stuck loading.
