### ISSUE TITLE
Search In Files does not respect state (expanded/unexpanded) of Search Details

### ISSUE THREAD

**Issue by afeinman** [microsoft/vscode#136299]
Issue Type: <b>Bug</b>

Every time I restart/reload VSCode, the Include/Exclude portion of the Search Pane is once again expanded.

Repro steps:

1. Open the Search tab.  Observe the Include/Exclude area is shown. **(Edit: Make sure you have text in one/both fields)**
2. Hide the the search details via the … menu.
3. Reload VS Code (Ctrl-P -> Reload)
4. Observe that the Include/Exclude area is shown again.

I would like this state to either be persisted, or (since I can see how some people with larger monitors might want to always see it) to have a pref that allows control over whether it is expanded by default.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
I assume you have some text in "files to include" or "files to exclude", is that the case? I force it to expand in that case because otherwise people often don't realize there is text there. I really want to keep this because I already get issue reports from people not realizing there are changes in there.

**Comment by afeinman** [comment]
Understood! Would it be possible to preference-ize it? I always have the same things in there (e.g. package-lock.json, which I don't want to ignore for other reasons).

**Comment by roblourens** [comment]
If you always have that in there, it sounds like you might want to add those to your exclude settings
