### ISSUE TITLE
Is "Visual Studio Code for the Web" open source?

### ISSUE THREAD

**Issue by carljones4** [microsoft/vscode#136265]
Hello- I would like to host the [web based version of VS Code](https://code.visualstudio.com/docs/editor/vscode-web) on my website.  Is it part of this open source repo?  Perhaps [this](https://github.com/microsoft/vscode/tree/main/src/vs/editor/standalone/browser) is it?

This question probably belongs on a forum rather than an 'issue', but apparently MS [likes it this way](https://github.com/Microsoft/vscode/issues/21685#issuecomment-283590971).

**Comment by Igorgro** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/136168

**Comment by joyceerhl** [comment]
Closing as duplicate of #136168
