### ISSUE TITLE
Paste from clipboard in console

### ISSUE THREAD

**Issue by lennertcc** [microsoft/vscode#136213]
Issue Type: <b>Bug</b>

Some times, mostly after a fresh startup the first time I paste some text from clipboard in the powershell console after a Read-Host, some characters are missing in the pasted text. When the Read-Host ends and the console returns to the prompt, those missing characters appear after the prompt.

So when that happens the console could look something like this:

PS C:\> Read-Host 'Paste someting?'
Paste someting?: http://ww.google.co/
http://ww.google.co/
PS C:\> swm

Example from today:
- I run line 67 using F8
- I copy the url from line 69
- I paste in the console

![image](https://user-images.githubusercontent.com/4930747/139654778-1ffa073c-072f-4705-807b-146eacfe508b.png)

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.90GB free)|
|Process Argv|--crash-reporter-id 0c6aef1d-4524-47aa-b87c-dcafa1ef938c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
random-string-password-generator|bib|1.0.2
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
gitlens|eam|11.6.1
url-encode|fle|1.1.0
vscode-guid|hea|1.4.20
vscode-edit-csv|jan|0.6.4
pretty-formatter|mbl|0.2.2
ecdc|mit|1.4.0
vscode-bicep|ms-|0.4.1008
vscode-dotnet-runtime|ms-|1.3.0
powershell|ms-|2021.10.2
markdown-preview-enhanced|shd|0.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by lennertcc** [comment]
Edited with example of today

**Comment by marvinthepa** [comment]
Could be related to #127699
