### ISSUE TITLE
Make manual language mode selection persistent across VSCode sessions

### ISSUE THREAD

**Issue by mechatroner** [microsoft/vscode#136263]
Currently "Select language mode" dialog doesn't make the new language mode persist across VSCode sessions.
The following sequence also discards the user-selected language mode:
1. Open a new file "path/to/file_test"
2. Manually select the new language mode e.g. "Diff"
3. Close "path/to/file_test"
4. Open "path/to/file_test" again
5. Observe that the previously selected "Diff" language mode was discarded.

I think that the language mode should be preserved at step 5.

**Comment by yashpalgoyal1304** [comment]
hi @mechatroner can u see if #136822 can help with ur use case?

**Comment by mechatroner** [comment]
Hi @yashpalgoyal1304, my proposal is very narrow-scoped, it is just to save users some time and avoid repetitive language selection for the same file.  I guess this can technically be done on the extension side too, but I am not sure if this is a good approach.
