### ISSUE TITLE
Menu contributions to a menu that doesn't exist where the `when` is false shouldn't show an error

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#136222]
See https://github.com/microsoft/vscode-pull-request-github/issues/3073 for a specific example.

Repro:
1. Create an extension that contributes a command to a menu that doesn't exist.
2. Add a `when` to that contribution that evaluates to `false`.
3. Run the extension and see an error "<menuName> is not a valid menu identifier".

Since the `when` is false, I would not expect to see that error.

**Comment by joaomoreno** [comment]
The error also shows up even if you don't have a `when` clause right?

**Comment by joaomoreno** [comment]
What is the use case here?

I believe the current behavior is to show a warning, not an error, which makes sense for the author of that extension. Would you suggest to just print to devtools?

**Comment by alexr00** [comment]
For GitHub Pull Requests and Issues, we want to contribute a "Create PR" command to a menu the Remote Repositories extension adds. When the Remote Repositories extension isn't installed, we have this warning surfacing in several places:

![image](https://user-images.githubusercontent.com/38270282/139690669-52ab705b-3050-4d98-a69a-0f9c457df8c9.png)

Ideally, this wouldn't show anywhere as it makes it looks like something is wrong when in reality there's no problem.

**Comment by joaomoreno** [comment]
I didn't really test it... but does the warning actually pop up in the UI, or is it only a devtools thing?

**Comment by alexr00** [comment]
It shows in the Running Extensions editor.

**Comment by joaomoreno** [comment]
I think this is fine for two reasons:

- There's no user notification popup. It actually appears in the Running Extensions editor, a UI piece mainly targetting extension authors, who happen to be the right people that should see the message.
- It's a warning, not an error

I suggest we just close it.

I'm wondering, though, how did @EugeneGohh actually find it out and filled an issue about it?

**Comment by EugeneGohh** [comment]
It pops out on my VS Code notification when I'm opening up my VS Code.

**Comment by joaomoreno** [comment]
> It pops out on my VS Code notification when I'm opening up my VS Code.

Can you show me a screenshot, as I can't reproduce this?

**Comment by Allevry** [comment]
@joaomoreno hope this helps 
![Screenshot_20211115_222331](https://user-images.githubusercontent.com/68745123/141822017-ac5a4fb9-69d8-4ecd-bf6a-262abaaaa16c.png)

**Comment by joaomoreno** [comment]
That notification is unrelated to the warning.
