### ISSUE TITLE
Cannot column-select over remote desktop

### ISSUE THREAD

**Issue by Websure-Denzil** [microsoft/vscode#136249]
VSCode Version:alpha 1.61.2
OS Version:Windows 10
Steps to Reproduce:

Try Ctrl+Shift+Alt+arrow keys to "draw" a rectangle.
Nothing happens
Shift+Alt and mouse works correctly.

I am having exactly the same issue as the OP for #4391
Only a problem when remoting to the machine.  This works on other editors such as notepad++ and management studio which use the same binding.
I don't see how #3130 fixes the issue, it only provides a workaround.

_Originally posted by @alexdima in https://github.com/microsoft/vscode/issues/4391#issuecomment-231111573_

**Comment by alexdima** [comment]
Let's first try to find out what command executes on the machine, with your settings and your keybindings when pressing `Ctrl+Shift+Alt+Arrow Right`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by jschroedl** [comment]
I am seeing the same issue. Ctrl+Alt+Up/Dn do not work for me. Neither to Ctrl+Alt+Shift+Up/Dn. All are set to Default in key shortcuts.  If I try to manually edit the shortcut for Ctrl+Alt+Up, in the "Press desired key combination.." prompt it will show ctrl+alt as I press them but when I press up or down arrows, nothing happens - they are not added.  I am also using remote desktop. Remoting from Win 11 into a Win 10 machine which is the machine running VS Code.

Here's my troubleshooting output when pressing Ctrl+Alt+Down

```
[2021-11-02 16:10:31.987] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
[2021-11-02 16:10:31.987] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
[2021-11-02 16:10:31.988] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2021-11-02 16:10:31.989] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,alt], code: AltLeft, keyCode: 18, key: Alt
[2021-11-02 16:10:31.991] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,alt], code: AltLeft, keyCode: 6 ('Alt')
[2021-11-02 16:10:31.991] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2021-11-02 16:10:32.453] [renderer1] [info] [KeybindingService]: + Ignoring single modifier ctrl due to it being pressed together with other keys.
```

**Comment by alexdima** [comment]
@jschroedl Thank you for the trace. It looks like the key combination `ctrl+alt+down` does not reach VS Code. There is nothing we can do on our side when the OS does not send us a keybinding. Most likely this is a problem with a driver or a piece of other software that is "eating up" that keybinding.

**Comment by jschroedl** [comment]
Any idea why it would reach you if I only press the arrows? ie arrowing around works fine and traces down arrow etc. I'll see if there are any RDP settings which look related

**Comment by Websure-Denzil** [comment]
> Let's first try to find out what command executes on the machine, with your settings and your keybindings when pressing `Ctrl+Shift+Alt+Arrow Right`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):
> 
> * Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
> * This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
> * Press exactly the keybinding you desire.
> * check what VS Code detects and what command is invoked.
> 
> If you are having trouble understanding the output, please feel free to paste here and I can try to help.

I cannot replicate today, as I working locally and have no secondary machine to hand.  I'll try and replicate tomorrow with the log, and see if I have the same as @jschroedl  does

**Comment by alexdima** [comment]
> Any idea why it would reach you if I only press the arrows? ie arrowing around works fine and traces down arrow etc. I'll see if there are any RDP settings which look related

@jschroedl I am sorry, I don't have any idea. You can also try opening e.g. https://w3c.github.io/uievents/tools/key-event-viewer.html in a browser in the remote machine and see if the browser receives the keybindings or not.

---

> any idea why Notepad++ manages it, and so does Management Studio?

@Websure-Denzil We ship with different default keybindings on various OSes. It is possible that we have a different binding for `Ctrl+Shift+Alt+arrow keys` on Linux compared to Windows. Please run the troubleshooting steps I posted [above](https://github.com/microsoft/vscode/issues/136249#issuecomment-957159835) and let me know what is detected and what command is invoked.
