### ISSUE TITLE
Cursor misbehaving and common key bindings not working

### ISSUE THREAD

**Issue by Ak-Shaw** [microsoft/vscode#136291]
Issue Type: <b>Bug</b>

I was an active Ubuntu user and wasn't facing any issue. I got a Macbook Pro (new to macOS), and so installed VS Code and signed in with GitHub (Ak-Shaw) for the settings sync and extensions installation. Now, the issue arised right after I did that.

https://drive.google.com/drive/folders/1RmkguiWAK4uP9cdEGUNQToCGBGDxdkRQ?usp=sharing

The link above contains 2 videos. One for macOS and one for Ubuntu.

In macOS: 
My cursor is a line cursor in the settings and not a block. But, whenever I open a new file, a block is displayed, and most of the keys don't work when I'm typing, but, as soon as I press A, the cursor turns to normal. Now, here at least the common keybindings of cut (command + X) and copy (command + C) were working.

In Ubuntu:
My cursor, again had the same behaviour what it had in case of macOS, but now here the cut, copy keybindings were not working. It's really frustrating to right click and do a cut, copy, from the menu

VS Code Details:
 
(macOS) 
Version: 1.61.2 (Universal)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:49:28.381Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.1.0

(Ubuntu)
Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:58:13.605Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-38-generic

OS Version: 

(macOS) -> Monterey v12.0.1 
(Ubuntu) -> 20.04.3 LTS (Focal Fossa)

Hoping to get a fix soon. Just the mere keybindings of cut and paste not working in ubuntu is making it hell!

VS Code version: Code 1.61.2 (Universal) (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv|--crash-reporter-id 16e43021-9980-45b7-8f79-40dec517b06f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
git-urgent|ara|1.0.0
vscode-browser-preview|auc|0.7.2
vscode-django|bat|1.6.0
c-cpp-compile-run|dan|1.0.15
python-extension-pack|don|1.6.0
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.1
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|9.0.0
vscode-open-in-github|fab|1.3.0
copilot|Git|1.6.3571
vscode-graphql|Gra|0.3.18
vscode-git-add-and-commit|iva|2.1.1
workspace-terminals|jos|0.3.1
google-search|kam|0.0.1
git-tree-compare|let|1.13.2
MagicPython|mag|1.1.0
git-graph|mhu|1.30.0
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.3
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
cpptools|ms-|1.7.1
vscode-typescript-next|ms-|4.5.20211101
vsliveshare|ms-|1.0.5065
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
gradle-language|nac|0.2.3
emoji|Per|1.0.1
vscode-spring-boot|Piv|1.28.0
material-icon-theme|PKi|4.10.0
java|red|1.0.0
vscode-gradle-extension-pack|ric|0.0.4
LiveServer|rit|5.6.1
code-stats-vscode|riu|1.0.18
vscode-checkstyle|she|1.4.1
code-spell-checker|str|2.0.12
teamhub|Tea|14.0.7
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
vscode-spring-initializr|vsc|0.7.0
vim|vsc|1.21.10
quokka-vscode|Wal|1.0.411
jinja|who|0.0.8
material-theme|zhu|3.13.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by Ak-Shaw** [comment]
As it's already obvious, I've created this issue on my Mac.

**Comment by alexdima** [comment]
It looks like you have installed the `vim` extension and you don't want to use it. The solution is to uninstall the vim extension.

**Comment by Ak-Shaw** [comment]
I totally forgot about that. 😅 

Thanks a ton! @alexdima 

Also, apologies for the inconvenience.
