### ISSUE TITLE
Figure out what we're going to do with pty.js

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#13625]
Currently pty.js drives communication to and from the terminal's shell process but there are some issues with the way it's setup:
- To get it building with the newer node.js and to integrate with our Windows code signing I was forced to fork it to [Tyriar/pty.js](https://github.com/Tyriar/pty.js).
- The fork is a fork ([Tyriar/pty.js](https://github.com/Tyriar/pty.js)) of a fork ([platformio/pty.js](https://github.com/platformio/pty.js)) of a fork ([jeremyramin/pty.js](https://github.com/jeremyramin/pty.js)) of the original ([chjj/pty.js](https://github.com/chjj/pty.js)) 😕 and it probably doesn't have to be.
- The original is not really maintained anymore.
- ~~The current commit being used is on a branch called prebuilt but the prebuilt assets were removed to get signing working on [Tyriar/pty.js](https://github.com/Tyriar/pty.js).~~ The prebuilt branch was copied over the master branch https://github.com/Tyriar/pty.js/tree/master
- All versions of pty.js depends on a fork ([peters/winpty](https://github.com/peters/winpty)) of a very old version of [rprichard/winpty](https://github.com/rprichard/winpty) which includes quite a few changes, including changes to the API. I believe this old version of winpty is the root cause for several [windows-specific terminal issues](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aintegrated-terminal+label%3Abug+label%3Awindows).
- We should publish to Tyriar/pty.js to npm, particularly since it [now has more consumers](https://github.com/zeit/hyper/pull/946) than just vscode https://github.com/Tyriar/pty.js/issues/9

**Comment by supnate** [comment]
Hi @Tyriar , thanks for your work on this! Just FYI I also tried [ptyw.js](https://github.com/iiegor/ptyw.js) but with no luck. Finally I had to fallback to use `cmd.exe` to get result of a command. Looking forward to a stable `pty.js`! 👏

**Comment by the-ress** [comment]
The winpty version used in [Tyriar/pty.js](https://github.com/Tyriar/pty.js) is a little newer than [peters/winpty](https://github.com/peters/winpty).

It's from jeremyramin/winpty@a988fe99934c59e5f518f6f90a60f52c72ee3f31

**Comment by Tyriar** [comment]
@the-ress thanks for pointing that out, I wasn't aware :smiley:

**Comment by Tyriar** [comment]
I've enabled issues on Tyriar/pty.js so I can better organize the issues.

**Comment by Tyriar** [comment]
I replaced the master branch with the prebuilt branch and set the default back to `master`. It's fine to point at master now.

**Comment by Tyriar** [comment]
Here's the plan:

- [x] Replace the master branch with the prebuilt branch and set master back to the default.
- [x] Evaluate if any changes are needed from peters/winpty
- [x] Uplevel winpty 0.2.x -> 0.3.1 https://github.com/Tyriar/pty.js/pull/8
- [ ] Uplevel winpty 0.3.1 -. 0.4.0 https://github.com/Tyriar/pty.js/issues/10
- [ ] Update README with relevant information https://github.com/Tyriar/pty.js/issues/11
- [ ] Rename the repo and module and publish to npm. https://github.com/Tyriar/pty.js/issues/9

**Comment by Tyriar** [comment]
0.3.1 itself is unstable due to https://github.com/rprichard/winpty/issues/80

**Comment by be5invis** [comment]
Mr @Tyriar You should ask WDG to include an OFFICIAL PTY API into Creaters’ update.
cf. Microsoft/BashOnWindows#1117

**Comment by Tyriar** [comment]
@be5invis while that would be nice, it won't fix the problem from my end (for a long time) as we will need to support legacy Windows. 👍'd though.

**Comment by Tyriar** [comment]
An update on this: I've currently put the upgrade on hold as my initial testing of winpty 0.4.1 shows some breakages such as git bash moving the cursor in the wrong direction after <kbd>backspace</kbd> and many glitches in Bash for Windows. This is still a stretch goal for this iteration so I'm going to focus on finishing up the other stuff I have assigned this iteration before looking further into this.

I have however published the lib with all the fixes from before (what we ship in stable) as `node-pty@0.4.1` npm so other consumers are safe to use that npm package if they were previously pointing to `c75c2dc` on Tyriar/pty.js. The only change was in the package.json metadata.

**Comment by Tyriar** [comment]
I filed https://github.com/rprichard/winpty/issues/96 on the winpty repo outlining the major issues I see

**Comment by Tyriar** [comment]
Once of the issues was node-pty's fault which has been fixed, the one last issue I believe has already been fixed (https://github.com/rprichard/winpty/commit/40d5b72c43165875724825fab5b5e5303fa5c3c3) and is just waiting for the new winpty version! :tada:

**Comment by Tyriar** [comment]
I just pushed to master to use node-pty@0.6.0-beta3 which includes the winpty fix for applications within WSL. If all goes well I'll release the new version of node-pty.
