### ISSUE TITLE
Cmd+F on an empty line - can't deselect Find in Selection

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#13621]
If I cmd+f on an empty line, and the find widget is empty, then Find in Selection keeps reselecting itself. I'm trapped until I type something into the box.

![oct-12-2016 11-31-19](https://cloud.githubusercontent.com/assets/323878/19322868/8ce7c3e4-906f-11e6-871b-268d94b46013.gif)

**Comment by wulftone** [comment]
Also experiencing this in the latest insiders build.  It defaults to selecting "in selection" that with `cmd+f` as well.

**Comment by roblourens** [comment]
I think it might be this? @isidorn  https://github.com/Microsoft/vscode/commit/6832950cedeae70b122ab7b430a114394f36b294

**Comment by isidorn** [comment]
@roblourens I was also suspecting that since that is the only change in that area in the previous year. Thanks for pointing out!
