### ISSUE TITLE
Go to definition (F12) not working with node.js project in VS-Code

### ISSUE THREAD

**Issue by sidswnt** [microsoft/vscode#136203]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. **VS Code version information:**
    Version: 1.61.2
    Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
    Date: 2021-10-19T15:49:28.381Z (1 wk ago)
    Electron: 13.5.1
    Chrome: 91.0.4472.164
    Node.js: 14.16.0
    V8: 9.1.269.39-electron.0
    OS: Darwin x64 19.6.0

- jsconfig has been created at root of the project as uggested in similar issues reported before. the content of the file is : 

{
    "compilerOptions": {
        "module": "commonjs",
        "target": "ES6"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}

2. F12 on the function showing definition not found

Please let me know if any more information is needed.

**Comment by mjbvz** [comment]
Please share a minimal example project that demonstrates this issues

**Comment by sidswnt** [comment]
Here you go

/src/handlers/abc-handler.js

`
import { Xyz } from '../businessObjects/impl/xyz-v1';

function handleEvent (context, payload) {
  return new Xyz(context).func1(payload);
}

module.exports = {
  handleEvent: handleEvent
};
`

/src/businessObjects/impl/Xyz

`
class Xyz extends Base {
  constructor (context) {
       super(context)    
  }

  async func1 (payload) {
   .
   .
   .
}
    
}

module.exports = {
  Xyz
};
`

**Comment by mjbvz** [comment]
Can you share it as a minimal GitHub repo? Also where are you running go to definition?
