### ISSUE TITLE
v1.7.0-insider 2016-10-12T06:11:05.325Z build unresponsive

### ISSUE THREAD

**Issue by dlong500** [Microsoft/vscode#13628]
- VSCode Version: 1.7.0-insider
(Commit 1889442ff090ef8170814a98698506300962dbba)
2016-10-12T06:11:05.325Z
- OS Version: Windows 7 x64

Steps to Reproduce:

1. After updating to this latest insider version the app is unresponsive except to open the about window.  Eventually the OS displays a popup stating "The windows is no longer responding".  The only way to close the app is to kill the processes (or wait for the OS to issue the unresponsive prompt).

**Comment by isidorn** [comment]
Can you repro this if you run with --disable-extensions?
Do you always get this no matter what workspace you open?

**Comment by bpasero** [comment]
Assuming this is https://github.com/Microsoft/vscode/issues/13667

**Comment by dlong500** [comment]
@bpasero you are correct.  My issue is definitely #13667.  I'll follow up there.
