### ISSUE TITLE
Settings sync is suspended because of successive authorization failures.

### ISSUE THREAD

**Issue by jankalfus** [microsoft/vscode#136269]
Issue Type: <b>Bug</b>

I keep getting the same error that was reported (and allegedly fixed) in https://github.com/microsoft/vscode/issues/114231, that is `Settings sync is suspended because of successive authorization failures. Please sign in again to continue synchronizing`. 

I'm using a Microsoft account for Settings Sync. The issue goes away for a few days after hitting Sign in and selecting the Microsoft account from the menu. But it re-appears after a few days again.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (13.15GB free)|
|Process Argv|--crash-reporter-id 846c7bdd-ea07-491a-b013-70a62b828080|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-sqlite|ale|0.13.0
jest-snippets|and|1.8.0
svelte-intellisense|ard|0.7.1
vscode-tailwindcss|bra|0.7.1
vscode-eslint|dba|2.2.2
vscode-deno|den|3.9.1
gitlens|eam|11.6.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
vscode-jest-runner|fir|0.4.47
vscode-svelte-snippets|fiv|0.5.0
auto-rename-tag|for|0.1.9
vscode-postfix-ts|ipa|1.9.4
vscode-styled-components|jpo|1.6.6
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
abracadabra|nic|6.6.0
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.10.0
quicktype|qui|12.0.46
svelte-preview|Raf|2.3.1
vscode-yaml|red|1.1.0
LiveServer|rit|5.6.1
vscode-javascript-booster|sbu|14.0.1
mdx|sil|0.1.0
code-spell-checker|str|2.0.12
svelte-vscode|sve|105.5.0
sass-indented|syl|1.8.18
even-better-toml|tam|0.14.2
sapling|tea|1.2.0
luna-paint|Tyr|0.10.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.14
colonize|vms|2.2.2
vscode-todo-highlight|way|1.0.5
vscode-jumpy|wma|0.3.1
vscode-mdx-preview|xyc|0.3.0
vscode-surround|yat|1.2.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by thinkedem** [comment]
I am also having the same issue. Tried to login (again) with my MS account, but the problem persisted.
(MacOS 12.0.1 / Monterey; but the issue appeared last week on Big Sur too.)
