### ISSUE TITLE
Problem accessing redirected schema

### ISSUE THREAD

**Issue by abdulkareemnalband** [microsoft/vscode#136267]
Unable to acquire json schema

Issue Type: <b>Bug</b>

```json
{
    "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.11/MicrosoftTeams.schema.json"
}
```

```json
[{
	"resource": "Untitled-1",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "768",
	"severity": 4,
	"message": "Unable to load schema from 'https://developer.microsoft.com/json-schemas/teams/v1.11/MicrosoftTeams.schema.json': connect ECONNREFUSED 127.0.0.1:80.",
	"startLineNumber": 2,
	"startColumn": 16,
	"endLineNumber": 2,
	"endColumn": 101
}]
```

VS Code version: Code - Insiders 1.62.0-insider (673165ca934c05d63fcab74bac7c819c32528c64, 2021-11-01T08:36:27.543Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|4.00GB (2.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30382699
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsaa593:30376534

```

</details>

**Comment by crystalfp** [comment]
Also as #137299

**Comment by aeschli** [comment]
Is `https://developer.microsoft.com/json-schemas/tsdoc/v0/tsdoc.schema.json` accessible in a browser?

Do you use a http proxy that uses `127.0.0.1:80` ?

**Comment by tkvw** [comment]
Same issue here, It happens on both WSL2 and desktop. 

Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by tkvw** [comment]
It looks like this relates to a redirect issue on the server, see https://github.com/microsoft/tsdoc/issues/253#issuecomment-675248131

**Comment by chrmarti** [comment]
@aeschli The first URL responds with a 301 status with the second as the target location. It is up to the extension to handle redirection. Did this change on your side?

**Comment by aeschli** [comment]
The problem is the request-light library: https://github.com/microsoft/node-request-light/pull/8
