### ISSUE TITLE
Certain themes break after code cell is changed

### ISSUE THREAD

**Issue by monsieur40a** [microsoft/vscode#136201]
## Environment data

-   VS Code version: Version: 1.62.0-insider (user setup) Commit: ff1e16eebb93af79fd6d7af1356c4003a120c563 
-   Jupyter Extension version (available under the Extensions sidebar): Jupyter v2021.10.1001398262
-   Python Extension version (available under the Extensions sidebar): Python v2021.11.1400738762-dev
-   OS (Windows | Mac | Linux distro) and version: Windows 
-   Python and/or Anaconda version: conda 4.10.3, Python 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): WSL
-   Jupyter server running: Remote WSL

## Expected behaviour

Using bluloco/other themes the color scheme doesn't change after editing a cell.

## Actual behaviour

Using Bluloco theme, edit code cell and the theme colors completely change after editing code. This also happens under Monokai theme and it doesn't happen under Abyss theme.

Before
![image](https://user-images.githubusercontent.com/33198723/139539148-f9d5c7d4-44c4-41ad-a1fd-6d6a05f91278.png)
After
![image](https://user-images.githubusercontent.com/33198723/139539168-e12ffb46-a590-4fe1-a631-d4a4e01b41af.png)

## Steps to reproduce:

Windows WSL, Insiders VSCode (happens on non-insiders as well), Jupyter, Python, Pylance extensions, Bluloco/Monokai theme. Edit a code cell (e.g. delete a colored word and type it again) and see that the theme completely changes.

This behavior doesn't happen when editing a plain old .py file.

If I reselect the theme from preferences the colors sometimes revert and sometimes don't.

**Comment by BCGardner** [comment]
- VS Code version: 1.63.0-insider
- Jupyter Extension version: v2021.11.1001493992
- Python Extension version: v2021.12.1482249642-dev
- OS: Linux Mint 19.3 (Ubuntu 18.04 LTS)
- Python and/or Anaconda version: conda 4.11.0, Python 3.8.6
---
I'm also experiencing this issue with Jupyter notebooks: using the 'Dark+' colour theme can intermittently trigger incorrect syntax colouring, as in the above images. This is usually triggered by the addition / deletion of code cells. Changing the colour theme to 'Dark' or restarting the editor resolves this problem. This issue exists for my latest installation of VS Code insider (1.63.0-insider) and stable (1.62.3). I don't have this issue with Python scripts (.py).

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, as its been over 2 years since this issue was filed, I suspect this may have been fixed.
I'm sorry this wasn't look into and we didn't get back.
I'm closing this with the above assumption, if it hasn't then I'm sorry and please do ping here and I'll reopen this and we can look into this. Or feel free to create a new issue.
