### ISSUE TITLE
Extension update available to older versions of VSCode

### ISSUE THREAD

**Issue by wmaurer** [Microsoft/vscode#13620]
- VSCode Version: 1.5.3
- OS Version: Windows 10 x64

A user has reported that an extension update for [vscode-jumpy](https://marketplace.visualstudio.com/items?itemName=wmaurer.vscode-jumpy) is available: wmaurer/vscode-jumpy#3
However the newest update requires engine ^1.6.0.

Clicking the update button doesn't apply the newest extension version (correct, as expected).

The bug is, that the newest update requiring ^1.6.0 should not be available to users of 1.5.3. Or at least a warning should be displayed saying the newest version of the extension is only compatible with newer versions of VSCode.

**Comment by joaomoreno** [comment]
We fixed this for 1.6 in #11573.

Before the fix, users got notifications (bug) but the new version would not be installed (as expected).

With the fix, the notification doesn't even come up.

**Comment by wmaurer** [comment]
Ok, thanks!
