### ISSUE TITLE
Red colors looking pixeled on 4k monitors

### ISSUE THREAD

**Issue by eduardo-loyica** [microsoft/vscode#136239]
Issue Type: <b>Bug</b>

Red colors looking pixeled on 4k monitors

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id 886328e9-1850-41e7-ab2a-48faead3db8b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-intelephense-client|bme|1.7.1
simple-react-snippets|bur|1.2.4
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.1
dart-code|Dar|3.28.0
flutter|Dar|3.28.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
php-debug|fel|1.21.1
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
go|gol|0.29.0
theme-monokai-pro-vscode|mon|1.1.19
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.3
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
cpptools|ms-|1.7.1
synthwave-vscode|Rob|0.1.10
ayu|tea|1.0.5
material-theme|zhu|3.13.2
html-css-class-completion|Zig|1.20.0

(31 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593:30376534
vssld246:30386377

```

</details>
<img width="427" alt="Screen Shot 2021-11-01 at 11 55 56" src="https://user-images.githubusercontent.com/26910184/139717745-069703ff-1340-404b-a61b-93989e904abc.png">

**Comment by IllusionMH** [comment]
Do you see same issue on screenshot in browser?

I guess only photo of screen can help other to see issue that you see. Screenshot looks good (.

**Comment by eduardo-loyica** [comment]
> Do you see same issue on screenshot in browser?
> 
> I guess only photo of screen can help other to see issue that you see. Screenshot looks good (at least with 216ppi and 96ppi displays).

Thanks @IllusionMH. You are right, screenshot looks good on other screens, but it keeps pixeled over my monitor. So I think is an issue with the monitor not the app.
