### ISSUE TITLE
Incorrect syntax highlighting in method when its return type ends with a digit

### ISSUE THREAD

**Issue by muhamedparic** [Microsoft/vscode#13624]
- VSCode Version: 1.6.0
- OS Version: Windows 7 Ultimate 64-bit

![52b3a02d1b41db8613640eebd5acfc47](https://cloud.githubusercontent.com/assets/17408083/19323694/4bbc74e2-90be-11e6-8d01-b450afc2e573.png)
![11084e2699fc5974741ae34d11117827](https://cloud.githubusercontent.com/assets/17408083/19323699/4ea4a0ee-90be-11e6-8ae2-f63238dca1fe.png)

It seems to be caused by the return type ending in a digit (or multiple digits). Having a digit in the return type before the last character does not cause it. Same issue appears when the return type ends with the $ character.

**Comment by Velok** [comment]
This is fixed in the beta of the new TS Grammar. Use this extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar

**Comment by isidorn** [comment]
Thanks @Velok for pointing this out
Closing as this is an issue in typescript and we will have it fixed once we have the new grammer
fyi @waderyan
