### ISSUE TITLE
Arrows in interactive environment stop working

### ISSUE THREAD

**Issue by david-cortes** [microsoft/vscode#136311]
## Environment data

-   VS Code version: 1.61.2
-   Extension version (available under the Extensions sidebar): v2021.10.1365161279
-   OS and version: debian sid
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.7 (conda)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: Python
-   Value of the `python.languageServer` setting: XXX

## Steps to reproduce:

(not sure if all these steps are necessary, this is what I was doing while I came upon the bug)

1. Open some python files in vscode.
2. Ctrl+Shift something in the file to run it in the interactive environment that opens up on the right pane.
3. Open another vscode instance, run also some python code in there in the interactive environment.
4. Switch to the earlier vscode instance.
5. Import some module from a non-installed package, for example by `os.chdir` to the folder and importing it by name in the interactive environment.
6. Open one of the files from the imported module.
7. Put a breakpoint somewhere in that file.
8. Without doing anything additional, try going back to the environment and pressing the "up" arrow.

## Expected behaviour

Should keep working, bringing up the last issued command in the interactive environment.

## Actual behaviour

Up and down arrows do not work anymore in the interactive environment.

**Comment by rebornix** [comment]
@david-cortes do you mind sharing a screen recording of what you were seeing to help troubleshoot?

**Comment by david-cortes** [comment]
> @david-cortes do you mind sharing a screen recording of what you were seeing to help troubleshoot?

Cannot reproduce it anymore with these steps. Perhaps I missed something. Although, when this happens, I've also noticed that the arrow functionality will work again for the full history after I manually execute something in the right pane by typing it in the prompt and pressing shift+enter. I'm nevertheless attaching a screenshot showing the pane and the prompt where one can press up and down arrows to bring up previous commands.
![vs_arrow_dont_work](https://user-images.githubusercontent.com/11860098/140652777-1787ac0c-83ee-43d6-94e1-dede27584353.png)

**Comment by david-cortes** [comment]
@rebornix  Found a way to reproduce it reliably:
* In the interactive pane, run `help(something_with_long_docs)`
* In the docs that show up, click on the blue text that says "show more (open the raw output data in a text editor) ..."
* In the newly opened tab showing the full docs, select something with the mouse, maybe scroll around, and then close the tab.
* Now that the tab is closed and the interactive environment is on focus again, press the up arrow in the command prompt. It will not bring up the previous command. Then enter some new command manually, run it, and the up arrow will work again as expected (including previous commands).

**Comment by david-cortes** [comment]
Issue is still present.

**Comment by rebornix** [comment]
We have pushed fixes for this in the last few months (sorry can't remember when). I verified with steps in https://github.com/microsoft/vscode/issues/136311#issuecomment-974398921 and didn't reproduce anymore.
