### ISSUE TITLE
How auto run Javascript on devtools at startup?

### ISSUE THREAD

**Issue by faustinoaq** [Microsoft/vscode#13635]
Hi @bpasero @dilijev :sweat_smile: and VS Code community!
- VSCode Version: 1.6.0
- OS Version: Manjaro KDE Ellada 16.08

Steps to Reproduce: _(hide activity bar)_

1. Open devtools console
2. Copy and paste this line `document.getElementById("workbench.parts.activitybar").remove();`
3. Execute and then the node is removed
4. `ctrl + b` for autofix layout

I do this almost every time when I use VS Code, Can I automate it?

The trick source is [here](https://github.com/Microsoft/vscode/issues/1105#issuecomment-214830681) 

This is related to #1105 and others.
Also I know that the idea is _on going_, but How can I do it :point_up_2: while I wait for this new awesome feature?

I tried to edit the vscode internal files as `workspace.main.js` and `index.js` without successful results.
Also I tried via extension, but [VS Code don't allow it](https://code.visualstudio.com/docs/extensions/our-approach)

Bye  :raising_hand_man:

**Comment by isidorn** [comment]
Awesome 😁
Just for this kind of effort I propose that we look into hiding the activity bar in November. @bpasero ok with you I take that issue and assign to november?

**Comment by bpasero** [comment]
Just make sure to coordinate with UX.

**Comment by isidorn** [comment]
@bpasero ay ay. But this issue is about auto running javascript on startup, I do not think we want to support this?
I assigned the hide activity bar issue to me...

**Comment by bpasero** [comment]
Yup unlikely we would want to support that.

**Comment by faustinoaq** [comment]
Ok, Thanks you for response! :-)

**Comment by Xiltch** [comment]
So now you can simply move the bar using View -> Move Side Bar

But no feature to Hide it :(

**Comment by dilijev** [comment]
@faustinoaq nice trick! I will probably not use it very often, but it's nice to know it's there!
