### ISSUE TITLE
preLaunchTask fails debugging session

### ISSUE THREAD

**Issue by evdenaxas** [microsoft/vscode#136354]
Issue Type: <b>Bug</b>

If I enable preLaunchTask in my launch.json debugging configuration for C++, the computer shoots up in resources and never enters the debugging session. I have a pre-launch task that just prints an echo statement, if I switch the preLaunchTask from null to the task, the computer shoots up in CPU utilization and the debugging session never starts. If I set the preLaunchTask to null and call the task manually, debugging enters successfully. This feature used to work so this is a functional regression. 

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:58:13.605Z)
OS version: Linux x64 5.11.0-38-generic
Restricted Mode: No
Remote OS version: Linux x64 5.11.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2999)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|24, 13, 11|
|Memory (System)|62.52GB (14.50GB free)|
|Process Argv|--unity-launch --crash-reporter-id 6c529226-9ade-46f9-9f8f-605035834569|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Container 233885420847.dkr.ecr.us-east-1.amazonaws.com/ottoware-development:4.1.8-opengl (av-stack-dev-env)|
|OS|Linux x64 5.11.0-38-generic|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 3000)|
|Memory (System)|62.52GB (14.51GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.202.5
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.66.0
vscode-bazel|Baz|0.5.0
vscode-cpputf-test-adapter|drl|1.2.5
vscode-test-explorer|hbe|2.21.1
vscode-docker|ms-|1.17.0
cpptools|ms-|1.7.1
test-adapter-converter|ms-|0.1.4
vscode-yaml|red|1.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by christopherchong94** [comment]
I ran into the similar issue here — where my prelaunchtask has finished executing the command, but the debugging session never starts.

I can see the prelaunchtask output printed on terminal (indicating it has finished), however the debugger never get started, and on the side of my terminal it shows that the prelaunchtask is still running (shown in picture below)

![image](https://user-images.githubusercontent.com/91880232/143521880-5b362c57-5fa4-4cae-97b5-f22af97b40d3.png)

My launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
      {
          "name": "Ansible",
          "type": "python",
          "request": "launch",
          "program": "/Users/christopher.chong/Documents/src/infra_cloud/bpdeploy",
          "console": "integratedTerminal",
          "args": ["ansible", "datascience"],
          "preLaunchTask": "bpgen_task"
      }
]
```

My tasks.json:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
      {
        "label": "bpgen_task",
        "type": "shell",
        "command": "source venv/bin/activate; ./bpdeploy bpgen christopherchong-mysdev00",
        "presentation": {
            "panel": "new",
            "reveal": "always"
        }
      }
    ]
  }
```

VS Code version: Version: 1.62.3 (Universal)
OS version: macOS Monterey version 12.0.1

**Comment by christopherchong94** [comment]
hi @weinand , I don;t have any C++ extension installed though, below is my list of extensions.

asciidoctor.asciidoctor-vscode-2.8.10
axetroy.vscode-npm-import-package-version-0.8.1
dbaeumer.vscode-eslint-2.2.2
extensions.txt
geeksharp.openssl-configuration-file-0.0.1
grapecity.gc-excelviewer-3.0.44
hashicorp.terraform-2.16.0
lextudio.restructuredtext-167.0.0
ms-azuretools.vscode-docker-1.18.0
ms-mssql.data-workspace-vscode-0.1.0
ms-mssql.mssql-1.11.1
ms-mssql.sql-database-projects-vscode-0.13.1
ms-python.python-2021.11.1422169775
ms-python.vscode-pylance-2021.11.2
ms-toolsai.jupyter-2021.10.1101450599
ms-toolsai.jupyter-keymap-1.0.0
ms-toolsai.jupyter-renderers-1.0.3
ms-vscode-remote.remote-containers-0.205.2
ms-vscode-remote.remote-wsl-0.58.5
msjsdiag.debugger-for-chrome-4.13.0
njpwerner.autodocstring-0.5.4
pflannery.vscode-versionlens-1.0.9
redhat.vscode-commons-0.0.6
redhat.vscode-yaml-1.2.1
rogalmic.bash-debug-0.3.9
rogalmic.zsh-debug-0.1.3
searking.preview-vscode-2.2.5
serayuzgur.crates-0.5.10
trond-snekvik.simple-rst-1.5.1
zhuangtongfa.material-theme-3.13.3
zhuangtongfa.material-theme-3.13.4

**Comment by sean-mcmanus** [comment]
@weinand Please re-activate -- it's not a C/C++ extension issue.

**Comment by evdenaxas** [comment]
@weinand any updates here? Thanks

**Comment by alexr00** [comment]
@evdenaxas can you share:
- launch.json
- tasks.json
- the output from your pre-launch task

@christopherchong94 can you share the output of your prelaunch task?

**Comment by christopherchong94** [comment]
@alexr00 here you go, that's what printed on terminal - the prelaunch task successfully finished but the debugger never got started.

![image](https://user-images.githubusercontent.com/91880232/146907424-35a32d1f-4fc1-4e56-9acf-a4892d54d475.png)

**Comment by alexr00** [comment]
@christopherchong94 thank you.

It looks like the command (`source venv/bin/activate; ./bpdeploy bpgen christopherchong-mysdev00`) that you run in your task doesn't actually exit. It sits there waiting for more input. Because of this, the task can never complete.

There are two possible ways you can change your task to use it as a prelaunch task:
1. Change your command in some way such that it exits. 
2. Add `"isBackground": true,` and a `problemMatcher` to your task. https://code.visualstudio.com/Docs/editor/tasks#_background-watching-tasks

**Comment by evdenaxas** [comment]
@alexr00 it could very well be the case that Christopher's root cause is different from mine. I am kind of surprised how your team handles bug tickets.

**Comment by alexr00** [comment]
@evdenaxas if you provide the [info requested](https://github.com/microsoft/vscode/issues/136354#issuecomment-997756151) then we can know for sure 😊.

**Comment by evdenaxas** [comment]
Sure but you have to understand that between the 14 seconds it took to take the ticket from needs more info to closed I cant anonymize my launch and task jsons to post here. I can't just share my files and expose internal details of our code base so I have to take time to repro on a separate sandbox. Anyways. I was hoping that coming from Microsoft VSCode would not have the level of support of a prototype open source tool but I was mistaken.

**Comment by alexr00** [comment]
@evdenaxas you could still provide the information I requested.
