### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by thunderface88** [microsoft/vscode#136305]
- Issue Type: `Bug`
- Extension Name: `configuration-editing`
- Extension Version: `1.0.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.62.0-insider`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rzhao271** [comment]
@thunderface88 looks like you forgot to paste. What was the issue?

**Comment by thunderface88** [comment]
thnx mate
