### ISSUE TITLE
unbind alt arrow key for terminal not taking effect

### ISSUE THREAD

**Issue by TTTPOB** [microsoft/vscode#136339]
Does this issue occur when all extensions are disabled?: 
not applicable, I have to use ssh-remote extension to open a linux terminal

- VS Code Version: 1.61.2
- OS Version: windows 20h1 19043.1288
- remote host OS version: `3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`, Cent OS 7

## Steps to Reproduce:

1. add this to keybind json file
```
 {
        "key": "alt+up",
        "command": "-workbench.action.terminal.focusPreviousPane",
        "when": "terminalFocus"
    },
    {
        "key": "alt+down",
        "command": "-workbench.action.terminal.focusNextPane",
        "when": "terminalFocus"
    },
    {
        "key": "alt+left",
        "command": "-workbench.action.terminal.focusPreviousPane",
        "when": "terminalFocus"
    },
    {
        "key": "alt+right",
        "command": "-workbench.action.terminal.focusNextPane",
        "when": "terminalFocus"
    }
```
2. have a `tmux` session running with `alt` + `arrow` keys set to switch panes
3. press `alt` + `arrow` key not working for the `tmux` session

## Expected Behavior:
`alt` + `arrow` keys work

## Additional Information
when looking help over the internet, I saw him encountered the same problem as me.
https://stackoverflow.com/questions/60148184/unable-to-swtich-tmux-pane-with-altarrow-in-vscode

**Comment by meganrogge** [comment]
It looks like it's switching panes for me. What are you expecting to see? 

![recording - 2021-11-04T064803 187](https://user-images.githubusercontent.com/29464607/140325051-d1cb9c4f-8b80-42e6-8cc2-d2255d624c98.gif)

**Comment by TTTPOB** [comment]
> It looks like it's switching panes for me. What are you expecting to see?
> 


sure if i use built-in terminal pane of vscode it works well, but in order to preserving work state i am using `tmux`, which requires `alt + arrow` keys to be "pass through" to the terminal. now, as i mentioned in the issue, after unbound the keys, vscode still captures `alt + arrow` key event and thus the key combination cannot be sent to `tmux`(or to say, an terminal application).

**Comment by TTTPOB** [comment]
in order to show `vscode` eats the key combination after unbound the keys
below is what happens when pressing `alt+arrow` in windows terminal, you can see the key sequence
![normal](https://user-images.githubusercontent.com/19909103/140446264-057f8b0c-e25f-43f0-8ae7-9737e261c08e.gif)
I pressed the same key in vscode, and nothing happens, thus, `alt+arrow` keys are not sent to terminal app and captured by vscode
![code](https://user-images.githubusercontent.com/19909103/140446272-1d6072b5-b101-45d2-b39c-5b3bef906271.gif)

**Comment by Tyriar** [comment]
Your keybinding removal doesn't remove the right rules as the builtin `when` clause differs now:

```
{ "key": "alt+left",              "command": "workbench.action.terminal.focusPreviousPane",
                                     "when": "terminalFocus && terminalHasBeenCreated || terminalFocus && terminalProcessSupported" },
```

The way to do this that should always work across versions is to remove the command from being handled specially in your settings:

```
  "terminal.integrated.commandsToSkipShell": [
    "-workbench.action.terminal.focusPreviousPane",
    "-workbench.action.terminal.focusNextPane",
    "-workbench.action.terminal.focusPreviousPane",
    "-workbench.action.terminal.focusNextPane",
  ]
```

When this is done alt+left/right sends sequences:

![image](https://user-images.githubusercontent.com/2193314/140519570-ed9c4d7b-fa11-4f50-a550-6d6fbf32bcab.png)

**Comment by TTTPOB** [comment]
thank you, and apologize for the question, I thought it was a bug

**Comment by TTTPOB** [comment]
```json
[
  {
    "key": "alt+left",
    "command": "workbench.action.terminal.sendSequence",
    "args": { "text": "\u001b[1;3D" },
    "when": "terminalFocus"
  },
  {
    "key": "alt+right",
    "command": "workbench.action.terminal.sendSequence",
    "args": { "text": "\u001b[1;3C" },
    "when": "terminalFocus"
  }
]
```
In addition to the answer above, the default behavior of xterm.js when pressing alt + left is to jump backward a word, just like ctrl + left(same for right). In order to let alt + left send the right sequence tmux needs, you have to add the above two keybindings to keybindings.json
