### ISSUE TITLE
Updating two configs through API in sequence may break settings file

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#13634]
- VSCode Version: 1.7.0-Insiders
- OS Version: macOS

Steps to Reproduce:

1. Create a hello world extension sample by `yo code`
2. change `activate` method to below code
    ```
'use strict';

export function activate(context: vscode.ExtensionContext) {
    let values =  [ "on", "off"];
    let i = 0;
    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
    vscode.workspace.getConfiguration("editor").update("cursorStyle", "block", true);
    vscode.workspace.getConfiguration("editor").update("lineNumbers", values[i], true);
        i = (i + 1) % values.length;
    });

    context.subscriptions.push(disposable);
}

export function deactivate() {
}
```
3. Compile and launch debugger
4. Open user settings
5. Open Command palette and run `Hello World` action multi times (more than 4 or 5)

After running `Hello World` multiple times, the user settings file is broken. Take my settings file as example

```
// Place your settings in this file to overwrite the default settings
{
  "vim.useCtrlKeys": true,
  "editor.wrappingColumn": 0,
  "files.autoSave": "afterDelay",
  "files.autoSaveDelay": 3000,
  "editor.rulers": [
    140
  ],
  "editor.insertSpaces": false,
  "vim.otherModesKeyBindings": [
    {
      "before": [
        " "
      ],
      "after": [
        "/"
      ]
    }
  ],
  "editor.lineNumbers": "on",
  "window.zoomLevel": 1,
  "editor.cursorStyle": "block"
}}
```

There is an additional `}` at the end.

Run into this issue while trying to repro #13446

**Comment by rebornix** [comment]
![break-settings](https://cloud.githubusercontent.com/assets/876920/19332010/2b13f786-909d-11e6-87a1-e6b5dcdf6185.gif)

Above gif demonstrates what I'm running into.

**Comment by rebornix** [comment]
![setting-error](https://cloud.githubusercontent.com/assets/876920/19332160/642639a2-909e-11e6-90f5-3dfae00fd014.gif)
If I clean all my user settings, the problem is more severe.

**Comment by jrieken** [comment]
@rebornix The `update`-call returns a promise and you should *wait* on that

**Comment by rebornix** [comment]
async/await works in this case, but we can't guarantee that there is no config updating elsewhere.

**Comment by aeschli** [comment]
Assigning to @bpasero. The writeConfiguration is async but it should avoid concurrent operations by queing all calls.

**Comment by bpasero** [comment]
@rebornix wanna provide a PR? writing code lives in configurationEditingService

**Comment by rebornix** [comment]
@bpasero sure, I'll take a look.

**Comment by bpasero** [comment]
This is actually tricky...
