### ISSUE TITLE
`Close Remote Connection` blocked due to a veto from terminal

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#136358]
From https://github.com/microsoft/vscode-remote-release/issues/5811

- Run the command `Remote-Containers: Clone Repository in Container Volume...`
- Enter: `https://github.com/chrmarti/smktst-fail-in-dockerfile`
- In the eventual modal dialog, press `Close Remote`
Expecting a window reload, but there is an error instead.

You can also call the command `Remote: Close Remote Connection`

I debugged it down to veto from terminal. Exception thrown while serializing the terminal:
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/terminal/electron-sandbox/localTerminalService.ts#L143

The veto hander should handle all exceptions and return false, unless it really wants to veto the window close.

**Comment by alexr00** [comment]
Closing for verification as it looks like this has been merged into release/1.62

**Comment by vuppalaprasanth** [comment]
Remote connection is going in a restarting loop. 
Restart remote connection is the only thing that we are getting now. 
Not possible to work at all with vscode.
