### ISSUE TITLE
Program crashed when click functions within the same file

### ISSUE THREAD

**Issue by PandoraV** [microsoft/vscode#136365]
Issue Type: <b>Bug</b>

When I hold the cmd and click the function's name which is in the same source file and go to its definition location, the program will crash.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (4.67GB free)|
|Process Argv|-psn_0_2564722 --crash-reporter-id 692cb630-0b2b-45a9-86df-1593a93c9ded|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.12.1
matlab-formatter|Aff|2.9.0
code-gnu-global|aus|0.2.2
matlab-code-run|bra|1.0.2
flask-snippets|cst|0.1.2
vscode-eslint|dba|2.2.2
binary-plist|dni|0.7.0
xml|Dot|2.5.1
matlab|Gim|2.2.1
gc-excelviewer|Gra|3.0.44
vscode-drawio|hed|1.6.2
vscode-edit-csv|jan|0.6.4
vscode-nuget-package-manager|jmr|1.1.6
rainbow-csv|mec|1.9.1
vscode-clang|mit|0.2.4
vscode-language-pack-zh-hans|MS-|1.61.5
csharp|ms-|1.23.16
data-workspace-vscode|ms-|0.1.0
mssql|ms-|1.11.0
sql-database-projects-vscode|ms-|0.13.0
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.3
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
cpptools|ms-|1.7.1
vscode-data-preview|Ran|2.3.0
java|red|1.0.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-checkstyle|she|1.4.1
vscodeintellicode|Vis|1.2.14
vscode-arduino|vsc|0.4.6
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
vscode-spring-initializr|vsc|0.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by gjsjohnmurray** [comment]
Please us the `Start Extension Bisect` command to investigate whether one of your extensions is causing this.

If none is found, tell us what language you are coding in.
