### ISSUE TITLE
Windows vscode:// URL handler registry entry doesn't open URLs correctly all the time

### ISSUE THREAD

**Issue by Xaeroxe** [microsoft/vscode#136328]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2
- OS Version: Windows 10 x86_64

Steps to Reproduce:

1. Install Visual Studio Code
2. Use https://crates.io/crates/webbrowser in a rust project to open a `vscode://` style URL

Workaround:

Edit registry key `HKEY_CLASSES_ROOT\vscode\shell\open\command` to use the `bin\code.cmd` file instead of `Code.exe`.

Possible solution:

`HKEY_CLASSES_ROOT\vscode\shell\open\command` should not use `Code.exe` with `--open-url`, as that interface seems to only work with `bin\code.cmd`.

**Comment by joaomoreno** [comment]
No, I don't think that's correct. Without editing the Registry, can you paste that `vscode://` into the File Explorer or a browser, and does that get handled correctly by VS Code?

If it does, which I'm sure it does since a lot of our flows depend on that, then something is broken around the webbrowser crate.

**Comment by Xaeroxe** [comment]
Please note that my issue description acknowledged this works sometimes. There are multiple paths to opening these links in Windows. Some work, and some don't. I am able to reproduce this issue without the webbrowser crate, however I referenced it because it was the quickest way to get a minimal reproduction example.

**Comment by joaomoreno** [comment]
And could that be related to the crate itself, rather than VS Code?

**Comment by Xaeroxe** [comment]
The crate is using the windows API ShellExecuteW, with the “open” command. That API is documented here https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutew

Prior to making my registry edit, attempting to open this link yields an error from Code.exe `C:\Program Files\Microsoft VS Code\Code.exe: bad option: --open-url` after I make my registry edit, this works fine. Clearly the registry entry is relevant somehow, because the VS code installer put that entry there, not me. I just altered the entry to use `bin\code.cmd`.

The documentation for [`ShellExecuteExW`](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecuteexw) notes that you may register your application to handle URLs, so it seems pretty reasonable to assume that `ShellExecute[Ex]W` is a way to open URLs on Windows, yes?

**Comment by joaomoreno** [comment]
Running something like

```
PATH\TO\Code.exe --open-url vscode-insiders://vscode.git/clone
```

Runs just fine on my machine. Can you reproduce if you run it in your machine's Command Prompt?

**Comment by Xaeroxe** [comment]
That works on my machine too. My interest in this issue has expired, I'm no longer using VS code. If my description isn't sufficient to convince you there's a problem feel free to close this issue.

**Comment by joaomoreno** [comment]
Too bad. I obviously can't reproduce so I rely on your help me get to the bottom of it. If you're out, then my hands are tied. Thanks for trying anyway.
