### ISSUE TITLE
Terminal scrollbar resets to top after close/reopen

### ISSUE THREAD

**Issue by nzakas** [microsoft/vscode#136321]
We have written the needed data into your clipboard because it was too
Issue Type: <b>Bug</b>

1. Open Terminal
2. Run a command that results in multiple lines of output such that the vertical scrollbar moves (i.e., `npm test`)
3. Close the Terminal
4. Open the Terminal again.

Expected: Terminal scrollbar thumb to remain at the bottom (last position before closing).

Actual: Terminal scrollbar thumb is reset to the top of the scrollbar.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (8.29GB free)|
|Process Argv|--crash-reporter-id 6fc032af-f5bd-4f81-ac94-df9dc8e463fa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.7.1
vscode-eslint|dba|2.2.2
code-runner|for|0.11.6
dotenv|mik|1.0.1
vscode-docker|ms-|1.17.0
remote-containers|ms-|0.202.5
sublime-keybindings|ms-|4.0.10
vetur|oct|0.35.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.1.0
sort-lines|Tyr|1.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246:30386377

```

</details>

 large to send. Please paste.

**Comment by meganrogge** [comment]
fixed in insider's, /duplicate #134692
