### ISSUE TITLE
Unable to override Ctrl+P with Meta+P on Ubuntu

### ISSUE THREAD

**Issue by f-squirrel** [microsoft/vscode#136312]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  Version: 1.61.2
- OS Version: Ubuntu 20.04 (Linux x64 5.10.0-1050-oem)

Steps to Reproduce:

1. Replace key binding "Ctrl + P" with "meta + P" in settings
2. Press "meta + P" => nothing happens
3. Press "Ctrl + P" => nothing happens

Notes:
* The same  problem happens with Ctrl+O
* Ctrl+T and Ctrl+W work as expected

I also tried to set up the keys manually in the `keybindings.json` file, please see below:
```
// Place your key bindings in this file to override the defaults
[
    {
        "key": "meta+b",
        "command": "workbench.action.toggleSidebarVisibility"
    },
    {
        "key": "ctrl+b",
        "command": "-workbench.action.toggleSidebarVisibility"
    },
    {
        "key": "meta+t",
        "command": "workbench.action.showAllSymbols"
    },
    {
        "key": "ctrl+t",
        "command": "-workbench.action.showAllSymbols"
    },
    {
        "key": "meta+w",
        "command": "workbench.action.closeActiveEditor"
    },
    {
        "key": "ctrl+w",
        "command": "-workbench.action.closeActiveEditor"
    },
    {
        "key": "meta+o",
        "command": "workbench.action.files.openFile"
    },
    {
        "key": "ctrl+o",
        "command": "-workbench.action.files.openFile"
    },
    {
        "key": "meta+p",
        "command": "workbench.action.quickOpen"
    },
    {
        "key": "ctrl+p",
        "command": "-workbench.action.quickOpen"
    }
]
```

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `meta+o`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by f-squirrel** [comment]
@alexdima, thank you for the quick reply. There is no output when I press either "meta+o" or "meta+p".

**Comment by alexdima** [comment]
@f-squirrel Thank you for getting back to me. This indicates that VS Code does not receive `"meta+o"`, nor `"meta+p"` from the OS. There is nothing we can do on our side if we don't receive the keybindings from the OS. In most cases, I have heard that there is some piece of software that "steals" keybindings globally or that the OS itself does so for some built-in features.
