### ISSUE TITLE
Emmet Extension Unresponsive.

### ISSUE THREAD

**Issue by Prathamesh-Shanbhag** [microsoft/vscode#136350]
- Issue Type: `Bug`
- Extension Name: `emmet`
- Extension Version: `1.0.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.61.2`
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 15,
		"activateCallTime": 3178,
		"activateResolvedTime": 993,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "vscode.emmet",
				"_lower": "vscode.emmet"
			},
			"activationEvent": "onStartupFinished"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by rzhao271** [comment]
Does this problem still occur for you on [Insiders](https://code.visualstudio.com/insiders/)?
I changed the activation events recently so that it'd take a command or the appropriate file type for the extension to activate.
