### ISSUE TITLE
editor.action.quickFix to select the first item in the suggestions by default (C#)

### ISSUE THREAD

**Issue by CarlosTorrecillas** [Microsoft/vscode#13631]
- VSCode Version: 1.6.0
- OS Version: 10.12

Steps to Reproduce:
1. Get the quickfix bulb to appear after you need something that needs fixing
2. You then need to press the arrow down to select the first item on the suggestions

Ideally it would be an enhancement if the shortcut can auto select the first item in the list by default.

**Comment by jrieken** [comment]
fyi - in latest insiders (https://code.visualstudio.com/insiders) this is now using the native context menu. We can also think about adding hot keys for each of them (like Cmd+1, Cmd+2, etc)

<img width="357" alt="screen shot 2016-10-13 at 10 31 01" src="https://cloud.githubusercontent.com/assets/1794099/19342083/9a585e6e-9130-11e6-8905-62cc74b81fec.png">

**Comment by bpasero** [comment]
@jrieken Electron provides API to automatically select a specific index of a context menu, we just did not expose it in our internal service API, but that is easy to do.

Maybe if there is only 1 quick fix we select it by default?

**Comment by bpasero** [comment]
Looks like only on macOS electron allows to set the index of the selected context menu entry.

**Comment by bpasero** [comment]
PR ready: https://github.com/Microsoft/vscode/pull/33881

**Comment by jrieken** [comment]
This is related to the sorting/ranking which isn't a solved problem yet: #33756

**Comment by bpasero** [comment]
@jrieken my main use case is actually getting an import in and for that case there is only one proposal:

![image](https://user-images.githubusercontent.com/900690/30107887-7022fa64-9300-11e7-8e83-706ff1f280c6.png)

So a variant of my change could be to only select the first item automatically if there is just 1 quick fix overall. That would help me, but maybe not the author of this issue.

**Comment by CarlosTorrecillas** [comment]
I'm going to add some extra information to this issue because by look of the comments it perhaps wasn't clearly described. The proposa itself was to automatically navigate to the first element of the possible "fixes" when I press Ctrl+. In none of the case my proposa was to automatically choose and apply that fix, was only to navigate to the first element on the list so just "Enter" would select the element chosen therefore it would save the coder from having to press the arrow down to start navigating through the list. It is what happens in ReSharper, you press Alt+Enter and you get the list of solutions and the first one is selected by the default. If you then press Enter it would then apply your selections which normally turns to be the first item. Hope it is clearer now

**Comment by bpasero** [comment]
@CarlosTorrecillas yes, that is what my PR basically does.
