### ISSUE TITLE
Remove typescript-vscode-sh-plugin

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#136389]
Tracks removing `typescript-vscode-sh-plugin`

This TypeScript service plugin added support for semantic highlighting before a proper api was exposed to VS Code

Semantic highlighting has been supported for three major TS releases now, so I think we should remove the `typescript-vscode-sh-plugin`. Users only older TS versions can install it to their workspace if they rely on semantic highlighting

**Comment by aeschli** [comment]
No concerns!
