### ISSUE TITLE
Long lines of ghost text get wrapped incorrectly

### ISSUE THREAD

**Issue by mtaran** [microsoft/vscode#136316]
Issue Type: <b>Bug</b>

1. Install and enable Copilot
2. Put in some text like

```java
class Foo {
    public void bar() {
        int x = 0;//
        if (x == 0) {
```

3. Try to complete on a new line at the end, with a very narrow viewport

## Expected: 

Ghost text suggestion for 

```java
            System.out.println("x is 0");
        }
```

The first line of ghost text should be wrapped and show up before the closing `}`.

## Actual:

Ghost text does show up, but when it's wrapped the wrapped piece of the first line appears *after* the `}`, which looks broken and confusing.

This repros in the current prod build and insiders.

VS Code version: Code - Insiders 1.62.0-insider (0f7f6e338a4e86306474d4d01bdea9b8fe798017, 2021-10-27T05:15:36.866Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|64.00GB (1.96GB free)|
|Process Argv|--crash-reporter-id c7f5de1e-17f9-4102-a676-dc1fa20b59e2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
better-toml|bun|0.3.2
flip|Chr|0.0.3
jump-to-last-cursor|ctf|0.0.1
native-ascii-converter|cwa|1.0.9
vscode-eslint|dba|2.2.2
vscode-dash|dee|2.4.0
githistory|don|0.6.19
kusto|don|0.3.8
xml|Dot|2.5.1
gitlens|eam|11.6.1
vscode-npm-script|eg2|0.3.23
flow-for-vscode|flo|1.9.2
duplicate|gee|1.0.2
codespaces|Git|1.3.3
copilot|Git|1.6.3615
remotehub|Git|0.17.0
vscode-pull-request-github|Git|0.31.1
go|gol|0.29.0
gc-excelviewer|Gra|3.0.44
vscode-mocha-test-adapter|hbe|2.13.0
vscode-test-explorer|hbe|2.21.1
highlight-string-code|iuy|0.4.5
svg|joc|1.4.13
jq-syntax-highlighting|jq-|0.0.2
language-haskell|jus|3.4.0
nim|kos|0.6.6
vscode-mocha-sidebar|mat|0.22.2
go-prof|Max|0.0.4
vscode-docker|ms-|1.17.0
remote-containers|ms-|0.205.0
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.66.0
remote-wsl|ms-|0.58.4
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.9
cpptools|ms-|1.7.1
sublime-keybindings|ms-|4.0.10
test-adapter-converter|ms-|0.1.4
vscode-typescript-tslint-plugin|ms-|1.3.3
negate-numbers|mta|0.0.1
vscode-paste-image|mus|1.0.4
elm|sbr|0.26.0
rewrap|stk|1.14.0
vscode-open-in-github|sys|1.15.0
remove-blank-lines|tha|1.1.1
vscode-input-sequence|tom|0.2.0
faster-new|wen|1.4.3
clang-format|xav|1.9.0
markdown-all-in-one|yzh|3.4.0
sublime-commands|Zar|0.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30382699
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsaa593cf:30376535

```

</details>

**Comment by mtaran** [comment]
screenshot of issue:
![image](https://user-images.githubusercontent.com/65346/139962927-a5ea8d2b-a23c-4a65-b595-3d01ce78d71d.png)

**Comment by aeschli** [comment]
Verified in 1.64.0-insider
Commit: b8178e3e2f3f620ebdd31dfbfba937ff1b12ee04

![image](https://user-images.githubusercontent.com/6461412/151573049-06d43431-7213-4bad-a4bf-33afbeb9fe52.png)
