### ISSUE TITLE
编译自己的代码时,控制台输出编译报错

### ISSUE THREAD

**Issue by janvie** [microsoft/vscode#136343]
Issue Type: <b>Feature Request</b>

编译自己的代码时,控制台输出编译报错,无法像visual studio一样通过双击报错信息快速定位到错误的代码行

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

**Comment by CodeCrazy-ywt** [comment]
When compiling my code, the output message says that compilation fails, and I'm unable to navigate to the error code by double-clicking the error message just like Visual Studio.
