### ISSUE TITLE
PWA install on iPad gets stuck in auth flow

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#136382]
Steps to Reproduce:

1. install PWA on iPad
2. open it and open a github repo to trigger the auth flow
3. go through the flow
4. when you finish, you end up on the vscode.dev callback page and it doesn't close automatically. It also doesn't show any chrome to close the page and return back to the editor.

**Comment by TylerLeonhardt** [comment]
This is because we have been opening the page with `noopener` for safari:
https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/dom.ts#L1200

for security reasons, this is a good idea... however, we should allow an embedder like vscode.dev to specify trusted urls that are allowed to open with the opener set so that `window.close()` will work.

If you're curious why noopener is needed for this case, look at the html spec:
https://html.spec.whatwg.org/multipage/window-object.html#dom-window-close

**Comment by TylerLeonhardt** [comment]
verification: follow steps, you shouldn't get stuck you should end up back in vscode.dev.

**Comment by weinand** [comment]
worked fine for me.
