### ISSUE TITLE
Improve the User Experience of the SCM during refresh 

### ISSUE THREAD

**Issue by aelgasser** [microsoft/vscode#136366]
The SCM view often takes time (several seconds) on my computer to refresh the status of the repo after staging a file (due to a combination of multiple files to stage and high CPU usage from other processes).

During those refresh times, the `Status Letter` disappears and the `Stage`, `Discard`, `Open file` buttons are shifted to the right. See the two screenshots below, showing, first, the view when it's not refreshing and second when it's refreshing.

(I'm talking about the `Status Letters` at the right of the line [U for Untracked, M for Modified, and so on]).

![image](https://user-images.githubusercontent.com/3692722/140097856-c4edc57b-94c9-4877-9482-ca0503718e1f.png)

![image](https://user-images.githubusercontent.com/3692722/140098018-7dcb460a-383e-445d-b630-2024e1c944f6.png)

This issue, In this case,  is that if I click on the next file to stage at the position where the `Stage` button should be (muscle memory and fast clicking), my cursor is now in fact on top of a `Discard` button as they all shifted to the right. This triggers a discard operation, which luckily for me prompts a dialog to confirm the discard (which I immediately dismiss).

This is for now really annoying and could become dangerous if the discard dialog is someday removed or gets a "Do not show again" option. 

Could you reserve the size of the status letter and/or don't move the button when the status letter is not available?

Here is the version of VSCode I'm using, but I had this issue for as long as I remember:

VS Code Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:49:28.381Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

**Comment by lszomoru** [comment]
//cc @misolori

**Comment by misolori** [comment]
agreed, the decorators should not be moving here on refresh and always remain visible

**Comment by lszomoru** [comment]
@aelgasser, over the years we have done work to make this experience better. I can confirm that the file decorations remain there when refreshing the Source Control view. I will go ahead and optimistically close this issue but please feel free to reopen it in case you are still able to reproduce this problem. Thank you!
