### ISSUE TITLE
Keyboard shortcut to navigate Working files

### ISSUE THREAD

**Issue by sarbbottam** [Microsoft/vscode#1363]
It will be great to have a keyboard shortcuts / commands to access the `Working files`.
Navigate `Working files`, remove from `Working files`.

**Comment by takumif** [comment]
There already are some keyboard shortcuts for navigating working files:
```javascript
Default Keyboard Shortcuts

{ "key": "cmd+k enter",           "command": "workbench.files.action.addToWorkingFiles" },

// removes all files from Working Files
{ "key": "cmd+k cmd+w",           "command": "workbench.files.action.closeAllFiles" },

// removes the current file from Working Files
{ "key": "cmd+k w",               "command": "workbench.files.action.closeFile" },

{ "key": "cmd+k down",            "command": "workbench.files.action.openNextWorkingFile" },
{ "key": "cmd+k up",              "command": "workbench.files.action.openPreviousWorkingFile" },
```
And there's some more discussion at #435.

**Comment by sarbbottam** [comment]
>>```js
Default Keyboard Shortcuts
{ "key": "cmd+k enter",           "command": "workbench.files.action.addToWorkingFiles" },
// removes all files from Working Files
{ "key": "cmd+k cmd+w",           "command": "workbench.files.action.closeAllFiles" },
// removes the current file from Working Files
{ "key": "cmd+k w",               "command": "workbench.files.action.closeFile" },
{ "key": "cmd+k down",            "command": "workbench.files.action.openNextWorkingFile" },
{ "key": "cmd+k up",              "command": "workbench.files.action.openPreviousWorkingFile" },
```

I am aware of the suggested key bindings, they are also specified at [Key Bindings for Visual Studio Code - File Management](https://code.visualstudio.com/Docs/customization/keybindings#_file-management).

I am looking for more specific key bindings / commands for `Working files`, management.

For example, navigating the `Working files` just as you can navigate the `Explorer`. With `⇧⌘E`/`workbench.view.explorer` followed by `↑↓←→` keys, one can easily navigate the `Explorer` and then with `⌘↓` open the highlighted file in editor. I have requested for similar features/functionality for `Working files`

**Comment by bpasero** [comment]
I added Cmd+K E as keybinding.

**Comment by sarbbottam** [comment]
Thanks @bpasero

**Comment by sarbbottam** [comment]
I don't see this feature in [0.10.6](https://github.com/Microsoft/vscode/releases/tag/0.10.6) which was release a day after this issue was closed.
<img width="458" alt="screen shot 2016-02-05 at 6 14 04 pm" src="https://cloud.githubusercontent.com/assets/949380/12863994/598212ca-cc34-11e5-8259-57fe0e8aa16f.png">

Could you please confirm if the fix was part of [0.10.6](https://github.com/Microsoft/vscode/releases/tag/0.10.6)?

Thanks!!

**Comment by bpasero** [comment]
@sarbbottam this will be in >= 0.10.7. You could try it out from our insiders release or wait until next week. https://code.visualstudio.com/insiders

**Comment by sarbbottam** [comment]
Thanks for the ⌘K E shortcut. Looks like its a generalized panel focusing utility. Its great. But could there be a similar utility (may be ⇧⌘W) just like ⇧⌘E to focus the Working Files panel?

**Comment by bpasero** [comment]
@sarbbottam Cmd+K E is for focussing the working files list!

**Comment by sarbbottam** [comment]
@bpasero I am only able to focus the header of the panel not the file list. In order to focus the files in working file I have to `tab` it through. Was wondering if it could behave similar to ⇧⌘E.
![cmd-k-e](https://cloud.githubusercontent.com/assets/949380/13405172/07f9eb70-ded2-11e5-999a-d667f6fc7560.gif)

**Comment by bpasero** [comment]
Looks like I fixed this only for February release which we will get out this week.

**Comment by sarbbottam** [comment]
Awesome!! Thanks @bpasero.

**Comment by sarbbottam** [comment]
Great to see this feature!! Thanks

**Comment by mnpenner** [comment]
`workbench.files.action.openPreviousWorkingFile` doesn't appear to exist anymore. What was it replaced with?
