### ISSUE TITLE
Terminal editors don't respect waitOnExit

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#136355]
1. Set `"terminal.integrated.defaultLocation": "editor"`.
2. Open a folder and add this task:
```json
		{
			"label": "My Task",
			"type": "shell",
			"command": "echo hello",
			"problemMatcher": [],
		}
```
3. Run that task

Expected: The terminal stay after the task completes and shows the usual default re-use message
Actual: The terminal immediately closes after the tasks completes.

**Comment by meganrogge** [comment]
Fixed this with https://github.com/microsoft/vscode/pull/168341
