### ISSUE TITLE
Explorer window auto expands all projects/folders every time you run VS code

### ISSUE THREAD

**Issue by jmihalich** [microsoft/vscode#136332]
Issue Type: <b>Bug</b>

This is occuring as of version 1.61.0.  Versions before this do not exhibit this problem.

Create an install of VS Code, with only the basic java extensions.  
Create a workspace, add some projects with folders.
Collapse all folders/projects
Exit VS Code
Restart VS Code
All projects/folders are auto expanded.
It used to remember your last expanded state of all folders.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (24.04GB free)|
|Process Argv|--crash-reporter-id 392ddeb3-a168-4a50-824b-15c580a08b57|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.58.4
quicktype|qui|12.0.46
java|red|1.0.0
vscode-checkstyle|she|1.4.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate and fixed in upcoming 1.62 due to ship later this week.
