### ISSUE TITLE
Bootstrap native autocompletion

### ISSUE THREAD

**Issue by Misato-best-woman** [microsoft/vscode#136333]
Issue Type: <b>Feature Request</b>

Can we have native support for Bootstrap classes suggestions & autocompletion?
like here: 
![Suggestions](https://user-images.githubusercontent.com/14796646/140012745-2e5d29c5-8572-4e8c-8895-ca9145b68715.png)

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:58:13.605Z)
OS version: Linux x64 5.14.13-200.fc34.x86_64
Restricted Mode: No

**Comment by IllusionMH** [comment]
This is candidate for an extension.
