### ISSUE TITLE
Have real example of unit tests

### ISSUE THREAD

**Issue by juli1** [microsoft/vscode#136385]
The current page about testing explains how to have a test runner but does not explain how to actually write a test with VS Code. For example, there is no guidance on how to write test that create a project and then invoke functions and test their correct behavior. There is also no guidance on how to read test data that might be collected with tests.

Having more test examples from the VS Code website would tremendously help the developer community. Otherwise, we are fishing for existing code/patterns on GitHub/stackoverflow, which may be the bad or outdated patterns to follow.

**Comment by connor4312** [comment]
This is handled by extensions and not in the scope of VS Code itself. For example, if you were using JavaScript and writing Jest tests, you would install and use the [Jest extension](https://github.com/jest-community/vscode-jest).
