### ISSUE TITLE
Terminal internal API `setActiveInstance` doesn't work when terminal is in editor

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#136356]
1. Set `"terminal.integrated.defaultLocation": "editor"`.
2. Open a folder and add this task:
```jsonc
		{
			"label": "My Task",
			"type": "shell",
			"command": "echo hello", // or command of your choice, such as sleep 5
			"problemMatcher": [],
		}
```
3. Run that task

The task runs, but there is an error that shows in a notification:
```
Terminal with ID 1 does not exist (has it already been disposed?)
src/vs/workbench/browser/parts/notifications/notificationsAlerts.ts:42
  ERR Terminal with ID 1 does not exist (has it already been disposed?): Error: Terminal with ID 1 does not exist (has it already been disposed?)
    at TerminalGroupService._getIndexFromId (vscode-file://vscode-app/d:/repos/Microsoft/vscode/out/vs/workbench/contrib/terminal/browser/terminalGroupService.js:92:23)
    at TerminalGroupService.setActiveInstance (vscode-file://vscode-app/d:/repos/Microsoft/vscode/out/vs/workbench/contrib/terminal/browser/terminalGroupService.js:87:48)
    at TerminalService.setActiveInstance (vscode-file://vscode-app/d:/repos/Microsoft/vscode/out/vs/workbench/contrib/terminal/browser/terminalService.js:245:44)
    at TerminalTaskSystem.executeInTerminal (vscode-file://vscode-app/d:/repos/Microsoft/vscode/out/vs/workbench/contrib/tasks/browser/terminalTaskSystem.js:823:38)
```

**Comment by Tyriar** [comment]
`TerminalGroupService` shouldn't be getting used in the stack trace

**Comment by meganrogge** [comment]
when I set default location to editor and run the build task, terminals are appearing in the panel. is that by design @Tyriar ?

**Comment by alexr00** [comment]
Currently that is by design as tasks + terminals in the editor don't work.

**Comment by Tyriar** [comment]
@alexr00 that might just be a matter of removing location here? https://github.com/microsoft/vscode/blob/b1dc0b0ebf7d4f4c20464601878fb8e2c2549b32/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1214

**Comment by alexr00** [comment]
@Tyriar I added the location to work around the `setActiveInstance` issue: https://github.com/Microsoft/vscode/issues/134533

**Comment by meganrogge** [comment]
`isDisposed` is `true` here when the terminal is in the editor, so we must be listening to `_onExit` somewhere in terminal editor code and disposing of the terminal 
![Screenshot 2022-12-07 at 2 53 46 PM](https://user-images.githubusercontent.com/29464607/206293360-bd6c660a-e65f-4204-9f70-4b8d0e18b21b.png)

**Comment by meganrogge** [comment]
yep, here

https://github.com/microsoft/vscode/blob/5ef734c4bcfe2ba50a9315bd5f94cfc873c6c16c/src/vs/workbench/contrib/terminal/browser/terminalEditorInput.ts#L165

**Comment by meganrogge** [comment]
active instance does get updated for me, but could repro an issue where `waitOnExit` wasn't respected - fix for that incoming 

https://user-images.githubusercontent.com/29464607/206294132-fbe4861f-e901-46c6-adff-eb6c8237a61f.mov
