### ISSUE TITLE
"Unable to resolve your shell environment" error after macOS restart

### ISSUE THREAD

**Issue by adrianbienias** [microsoft/vscode#136346]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
```
Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:49:28.381Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.4.0
```
- OS Version: `macOS Big Sur 11.3.1`

Steps to Reproduce:

1. Restart macOS
2. Open VS Code (it can be automatically reopened by macOS after a restart, but it can also be opened manually for the first time after the system start)
3. VS Code shows the following error
`Unable to resolve your shell environment in a reasonable time. Please review your shell configuration.`
4. When VS Code is closed using the red "X" icon, the error shows each time VS Code is reopened, but when it's closed using CMD + Q (so there's no dot below the icon in the dock) then the error doesn't show until next system restart.

Here's how it works: https://thumbs.gfycat.com/ScrawnyRightAmericanbobtail-mobile.mp4

---

There is an existing issue https://github.com/microsoft/vscode/issues/113869 but it's closed so I wasn't able to add a comment to it and had to create a new issue.
Is there a reason for closing not-solved issues?

Also, there's a guide:
https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fails
but it doesn't solve my problem.

> If, after 10 seconds, the shell environment has still not been resolved or resolving failed for any other reason

In my case, the error shows within less than 1 second so it doesn't wait 10 seconds to resolve the shell env for sure.
I measured execution times for `source ~/.zshrc` (using [gnomon](https://github.com/paypal/gnomon) package) and they are always below 1 second.

**Comment by gjsjohnmurray** [comment]
Maybe #136272

**Comment by bpasero** [comment]
@gjsjohnmurray 👍 , thanks!
