### ISSUE TITLE
Allow extensions to disable the "Open Preview to the Side" button for markdown preview

### ISSUE THREAD

**Issue by SeriousBug** [microsoft/vscode#136388]
VSCode automatically adds a "Open Preview to the Side" button which displays the default markdown preview when the button is pressed. This can be confusing for extensions like Markdown Preview Enhanced and Dendron which add custom markdown previews. 

I suggest adding a mechanism for extensions to disable the default button. The extensions then can add their own buttons, or leave the preview button removed.

https://github.com/microsoft/vscode/pull/136273

**Comment by mjbvz** [comment]
Fixed by #136273

**Comment by rchiodo** [comment]
Looks good as far as the button being disabled, but should this be disabled too?

![image](https://user-images.githubusercontent.com/19672699/144149137-8eb8c192-0b8a-4083-900a-f248ec43c945.png)

**Comment by mjbvz** [comment]
Thanks for testing. @SeriousBug Do you also want to submit a PR that handles the editor context menus? Not sure if you see users being confused by those as well

**Comment by SeriousBug** [comment]
@mjbvz Haven't seen users confused by that yet, but it makes sense for this option to apply to that as well. I'll look into this and create another issue/PR, thanks for the suggestion!

**Comment by SeriousBug** [comment]
@mjbvz @rchiodo I have a PR up for this!

https://github.com/microsoft/vscode/pull/139241
