### ISSUE TITLE
MicrosoftSqlToolsServiceLayer asking for keychain password

### ISSUE THREAD

**Issue by DanielBabcock** [microsoft/vscode#136302]
Issue Type: <b>Bug</b>

When I open VSC I get a popup:
  'MicrosoftSqlToolsServiceLayer wants to use your confidential information stored in "a" in your keychain.
The authenticity of "MicrosoftSqlToolsServiceLayer" cannot be verified. To allow this, enter the "login" keychain password'

This message pops up three to five more times after clicking deny and shows up everytime I open VSC, or a new window in VSC, or a new repo in the same window. 
![Screen Shot 2021-11-02 at 12 51 57 PM](https://user-images.githubusercontent.com/28121171/139911624-cecd1908-3e2d-43e1-9056-2655a5f986d4.png)

https://user-images.githubusercontent.com/28121171/139911647-7700f369-6572-4e26-998c-4b48389c1da4.mov

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: 
![Screen Shot 2021-11-02 at 12 51 57 PM](https://user-images.githubusercontent.com/28121171/139910959-e5918786-1d2c-490e-a315-320cceedb58e.png)
disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (1.22GB free)|
|Process Argv|--crash-reporter-id e1a30e0f-7e01-4b1d-902a-1575afae3e6d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.1
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
data-workspace-vscode|ms-|0.1.0
mssql|ms-|1.11.0
sql-database-projects-vscode|ms-|0.13.0
code-settings-sync|Sha|3.4.3
twig|wha|1.0.2
eno|Wsc|2.3.53
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by metju90** [comment]
How can we identify which extension is causing this issue?

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command.

**Comment by lopezvit** [comment]
I encounter similar problem and run that command. The culprit extension is `ms-mssql.mssql`. I will "Report Issue & Continue"

**Comment by metju90** [comment]
> Please use the `Start Extension Bisect` command.

With this I identified the problematic extension - `ms-mssql.mssql `. Thanks!

I found this: https://github.com/microsoft/vscode-mssql/issues/17064
