### ISSUE TITLE
vscode-web: Image-preview fails in diffEditor

### ISSUE THREAD

**Issue by zWingz** [microsoft/vscode#136338]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.61.2
- Chrome: 90

example in https://github1s.com/conwnet/github1s/pull/353

![image](https://user-images.githubusercontent.com/13031838/140023126-38842a11-ef54-4561-b4a2-07cbf0f62ed4.png)

![image](https://user-images.githubusercontent.com/13031838/140023427-07ff7440-f6b2-4436-bfc3-862e89b74f7f.png)

![image](https://user-images.githubusercontent.com/13031838/140023469-6ff5a624-2555-4f30-80e5-7e8815325de2.png)

But if you try a few more times, It works

![image](https://user-images.githubusercontent.com/13031838/140023049-1b8ccfe2-cfd4-4b73-877e-8ac0591e54f4.png)

[workderReady](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/webview/browser/pre/main.js#L201) should after service-worker [activate](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/webview/browser/pre/service-worker.js#L199)

**Comment by mjbvz** [comment]
GitHub1s isn't officially supported. Do you see this on vscode.dev / GitHub.dev?

**Comment by zWingz** [comment]
It work on github.dev&vscode.dev ...
I don't know why

**Comment by zWingz** [comment]
I found that vscode.dev/github.dev uses `https://{{uuid}}.vscode-webview.net/stable/{{commit}}/out/vs/workbench/contrib/webview/browser/pre/` as `webviewEndpoint`

If change to `https://fa6ae1e7-83c7-4116-99ea-4938d64938b3.vscode-webview.net/stable/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/workbench/contrib/webview/browser/pre/` (a fixed address), It will recurrent

I thinks It is because `{{uuid}}.vscode-webview.net` is a dynamic address, so the WebView has a `serviceWorker` to itself
But if change to a fixed address, WebViews share a serviceWorker

In the diffEditor, two webview share a serviceWorker. 
![image](https://user-images.githubusercontent.com/13031838/140255047-a9177ab8-c8c9-4c86-b70f-94fa5920a250.png)

When the second webview's serviceWorker installed and activated, the first webview's serviceWorkder will be abandon

**Comment by zWingz** [comment]
some debug log
![image](https://user-images.githubusercontent.com/13031838/140266433-aba5a376-ac0b-4c1f-ac9e-4779a5052c17.png)

![image](https://user-images.githubusercontent.com/13031838/140266476-e4ddb6c1-6e29-4560-8961-513398e70891.png)

![image](https://user-images.githubusercontent.com/13031838/140269802-aa5db162-3e8a-4c11-b6c3-19ddd67390ec.png)
![image](https://user-images.githubusercontent.com/13031838/140269812-a226b330-8743-4210-bec9-db852265b551.png)

**Comment by mjbvz** [comment]
Are you not seeing this working on GitHub.dev?

Each webview is supposed to have its own service worker. That's why we serve them from a unique host. Why are they getting served from localhost:5000 in your examples?

**Comment by zWingz** [comment]
That means I can't set `webviewEndpoint` to a static URL in Code - OSS ?

**Comment by mjbvz** [comment]
Yes every webview needs a unique origin to work as expected. You can configure OSS to use this using the `{{uuid}}` part of the endpoint url (you also need a cdn/server that can serve up the webview content from these unique endpoints)
