### ISSUE TITLE
Windows 11 Context Menus

### ISSUE THREAD

**Issue by FBI-AGENT-MERLOT** [microsoft/vscode#136340]
Issue Type: <b>Feature Request</b>

Add the "Open with Visual Studio Code" legacy context menu entry to the modern Windows 11 context menu in order to reduce clicks required to open something in VSC.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: Yes

**Comment by yume-chan** [comment]
#127365
