### ISSUE TITLE
Please come up with a way to not highlight entire files/methods with errors

### ISSUE THREAD

**Issue by MarkKahn** [microsoft/vscode#136363]
Quite often an error will be triggered on a class, method, or sometimes an entire file and the entire thing gets highlighted, making the editor a giant mess of red squiggles for one error.

e.g. with eslint if I have:

    doSomething(function() {
                ^ error points here

then literally everything inside of that function gets highlighted, no matter how long it is.  Or with JSON an error will often point at `[0, 0]`, thus highlighting the entire file.

e.g. this is one error, "too many statements" in some old code I'm refactoring.  I'd ***much*** rather have the error just highlight the word "function" or similar:

<img width="628" alt="Screen Shot 2021-11-03 at 4 39 23 PM" src="https://user-images.githubusercontent.com/320562/140093149-c2a6c398-3b74-4855-b07f-804925a0b822.png">

**Comment by IllusionMH** [comment]
ESLint provides error range that includes whole function (which is annoying) so IMHO it's for ESLint to check approach used for max-statements, complexity etc. rules. VS Code shows and navigates only to start of range.

Maybe it can be done in ESLint extension however it will be non-trivial as it doesn't deal with AST, same for VS Code editor. However ignoring error ranges on VS Code editor side looks incorrect especially in generic case for different languages.

**Comment by mjbvz** [comment]
This sounds like an UX issue for the eslint extension. Please start by filing it against them. They can follow up with VS Code if they determine there's an issue with our problems implementation
