### ISSUE TITLE
IntelliSense: Some format problems of the new version of vscode (1.6.0)

### ISSUE THREAD

**Issue by Kongsea** [Microsoft/vscode#13636]
When I upgraded the vscode to the new version (version 1.6.0), there are some problems of IntelliSense shown in the following screenshots.

- VSCode Version: 1.6.0
- OS Version: Ubuntu 14.04

Problems:

1. When writing code, if the IntelliSense is too long:
![selection_004](https://cloud.githubusercontent.com/assets/4168984/19333819/54696228-912a-11e6-887e-4232e15b78f1.png)
It only happened when writing the code. After written completed, I hover the mouse on the function, the problems didn't occurred.

2. When hovering the mouse on a function:
![selection_006](https://cloud.githubusercontent.com/assets/4168984/19333921/02430bc4-912b-11e6-88b1-17f6330c04e9.png)

3. When hovering the mouse on a function:
![selection_007](https://cloud.githubusercontent.com/assets/4168984/19333955/3a801ffe-912b-11e6-8e45-f7e50f18e523.png)

**Comment by joaomoreno** [comment]
What language are you developing on? What extension do you use for it?

**Comment by Kongsea** [comment]
@joaomoreno I develop using Python language with the extension Python by Don.(https://marketplace.visualstudio.com/items?itemName=donjayamanne.python)

**Comment by CaselIT** [comment]
I've had a problem similar to 1 using typescript.

Also the hover seems to be limited to the current editor when using split editors. This leads to unfortunate formatting like (also in typescript):
![image](https://cloud.githubusercontent.com/assets/16175304/19386742/3fabb326-9216-11e6-8fe6-b935715c9fc7.png)
(Let me know it it's better to open a new issue for this)

**Comment by joaomoreno** [comment]
@CaselIT that's 13004

**Comment by CaselIT** [comment]
@joaomoreno Had not found it. Thanks

**Comment by DonJayamanne** [comment]
@Kongsea , @joaomoreno this is an issue (https://github.com/DonJayamanne/pythonVSCode/issues/368) with the [Python extension](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python).
The issue (in the Python extension) has been resolved and fix will be in the next release.
