### ISSUE TITLE
[Regression] Precision touchpad scrolling is broken

### ISSUE THREAD

**Issue by nathanielwarner** [Microsoft/vscode#13630]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Steps to Reproduce:

1. Open Visual Studio Code 1.6.0
2. Attempt to scroll with a precision touchpad

Scrolling is now choppy and imprecise, while it worked in previous versions of VS Code. Scrolling with the scroll bar is normal.

**Comment by isidorn** [comment]
Dup of #12637
