### ISSUE TITLE
Broken env on terminal startup in current Insiders version

### ISSUE THREAD

**Issue by lumaxis** [microsoft/vscode#136317]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.62.0-insider (Universal)
Commit: 4bbec283c36a51cf80f9b77c7a81c140a76a363b
Date: 2021-11-02T08:57:34.388Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.1.0

Steps to Reproduce:

1. Have a `.zshenv` file that uses `#!/usr/bin/env bash`
2. Open a terminal in VS Code Insiders
3. See `env: bash: No such file or directory`

It seems when the terminal starts in the current Insiders version, the env seems to be broken/missing important pieces. This appears to be a regression from Stable, works as expected in 1.61.2

**Comment by Tyriar** [comment]
This type of issue is typically related to environment differences between VS Code's terminal and the external terminal. You can try diffing the two environments by printing them (eg. `env`, `Get-ChildItem env:`) and investigating any differences.

Closing this off as it doesn't look actionable on our end, you can read more about our [issue process here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label *question

**Comment by lumaxis** [comment]
> You can try diffing the two environments by printing them (eg. `env`, `Get-ChildItem env:`) and investigating any differences.

Thanks @Tyriar but that's actually where my issue starts 😅 When I try to print my environment e.g. at the beginning of my `.zshenv` file, not even that works:

```
/Users/lukas/.zshenv:1: command not found: env
env: bash: No such file or directory
```

Sorry if I'm being dense and missing something but is there anything else I should try to debug thos?

**Comment by Tyriar** [comment]
@lumaxis that's odd... Those programs not being available means they're not on the PATH, you could `echo $PATH` and see the value there and then try investigate why it's not showing up. I think on mac these are added via `path_helper`, maybe only in a login shell? Not sure if you've customized your terminal profile but does running `zsh -l` or `bash -l` inside the broken terminal fix the problem?

**Comment by lumaxis** [comment]
Okay, mystery solved @Tyriar! Not sure what or why but something added an explicit `PATH` to my `terminal.integrated.env.osx` setting and that caused all the problems.
It worked in stable Code because due to a sync conflict, the modified setting hadn't synced over there yet and made all of this double confusing. Thanks for helping me through this 🙇🏼‍♂️
