### ISSUE TITLE
Suggestion: Quickfix should respect arrow keys if given scrollbar

### ISSUE THREAD

**Issue by delasteve** [Microsoft/vscode#13638]
- VSCode Version: 1.6
- OS Version: OS X El Capitan (10.11.6)

![](http://i.imgur.com/YBjoBL6.gif)

Steps to Reproduce:

1. Open quick fix (`alt + .` / `cmd + .`) 
2. Use Arrow keys
3. Observe you are able to move up and down but the scroll bar doesn't move when you move past the top or bottom suggestion

Note: You are able to scroll with the mouse wheel

I honestly don't remember if this was the case pre-1.6. I thought that it showed all available suggestions in the window and didn't need to scroll.

**Comment by jrieken** [comment]
We have changed many things around the light bulb - it now shows in the gutter and the menu used the native context menu. You can try this today with latest insider - https://code.visualstudio.com/insiders

<img width="357" alt="screen shot 2016-10-13 at 10 31 01" src="https://cloud.githubusercontent.com/assets/1794099/19341981/28d50fbc-9130-11e6-9a19-d9dd3891e816.png">
