### ISSUE TITLE
Duplicate tabs in extension description

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/vscode#136334]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.61.2
- OS Version: Mac OS Big Sur

There are duplicate tabs in the description of extension:
![image](https://user-images.githubusercontent.com/8640918/140017451-6044be16-99a8-4879-bd43-0fde59bc53ab.png)

![image](https://user-images.githubusercontent.com/8640918/140017431-e494163b-bd44-44a0-a972-60eeb2d78441.png)

**Comment by gjsjohnmurray** [comment]
Doesn't happen for me (Windows, English):

![image](https://user-images.githubusercontent.com/6726799/140049758-20854ddc-f937-4264-a896-78d0e2983abe.png)

In your screenshot there is a star icon at the start of the sentence just above the red box you drew. What does that sentence translate as?

**Comment by HaoboGu** [comment]
> In your screenshot there is a star icon at the start of the sentence just above the red box you drew. What does that sentence translate as?

It's "This extension is recommended based on the files you recently opened."

**Comment by gjsjohnmurray** [comment]
:+1:

Still doesn't repro for me:

![image](https://user-images.githubusercontent.com/6726799/140060964-f1f9af3f-791f-4dc2-bc1c-fb06f08b5b15.png)

/assign @sandy081

**Comment by DouglasMarq** [comment]
What language are you using? I have bot m1 mac and intel mac (both are monterey), so i can try to repro the bug.

**Comment by HaoboGu** [comment]
I'm using Chinese on an intel mac. It happened after I changed the current theme and switched to a new extension's homepage. I can't reproduce it right now. It seems that this occurs randomly

**Comment by HaoboGu** [comment]
Oh I reproduced it just by quickly switching between extensions. It occurs in both English and Chinese version. I'll attach a gif later

**Comment by HaoboGu** [comment]
Here's how I reproduce it:

![1](https://user-images.githubusercontent.com/8640918/140063216-10081654-4d4e-473a-b002-276fc578c9a5.gif)

**Comment by sandy081** [comment]
I can repro it. Thanks for the video.
