### ISSUE TITLE
Suggestion: improve the presentation of the API documentation

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#13637]
I have a hunch you guys already know this is important, but I can't see any other issues to this effect.

Is it just me, or is the [API documentation](https://code.visualstudio.com/docs/extensionAPI/vscode-api) user experience pretty awful right now? I posted this issue just now in response to trying to find out what the API has to offer with respect to some ideas I have. Key questions in mind are "is it directly capable of X" and "can I get a sense of how much additional work would be required to extend certain base features to support my ideas?"

Problems:
- It's a giant scrolling page; clumping everything together makes it hard to differentiate between different sections and judge how they relate to each other.
- There is nowhere to get a quick overview of everything the API has to offer.
- There is no obvious table of contents that I can use to quickly jump to the section I need.
- There is no clear document hierarchy.
- I can't quickly search for symbols and drill down to find what I need (other than via CTRL+F)
- It's not very readable. The typography makes everything look kind of "same-ish", so it's hard to scroll through and scan for what I need. The font sizes don't make a lot of sense with respect to representing importance of items and their relationship to the document hierarchy.
- Weird line spacing- way more space between property list items than headings and so forth. Again, scannability is an issue.

Would love to see this presented in a way that encourages better absorption and exploration of what the API has to offer, and I'm sure doing so would promote a faster-growing extension ecosystem.

![image](https://cloud.githubusercontent.com/assets/298883/19334565/13ad6778-9140-11e6-8c84-58009ad59729.png)

As an aside; "Complex Commands API" - The intro text is completely unhelpful: _"They are called complex commands because they require parameters and often return a value"_ - this is a description of almost every function in existence.

**Comment by octref** [comment]
Thanks for the thoughtful feedback. The API doc is currently generated from https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts, and it could get some more polish to improve developer experience.

But I guess this should be moved to vscode-docs @waderyan .

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#939
