### ISSUE TITLE
steal focus only when a child window is focused

### ISSUE THREAD

**Issue by pknowles** [microsoft/vscode#136399]
When debugging a GUI app, particularly one that hides the mouse cursor, it is convenient to have vscode take focus when a breakpoint is hit, i.e. issue #118493

This can even be disabled by changing `debug.focusWindowOnBreak`.

However, focus stealing can also be problematic when interacting with other windows, as described well in #115226

Can this be solved by only taking focus when the window of a child application is in focus, i.e. one being debugged?

One caveat is when attaching to a running process, it would not be a child.

**Comment by weinand** [comment]
I'm not aware of a cross-platform API to find out whether a child application is in focus.
