### ISSUE TITLE
Shift-Enter stops advancing to next cell after some time

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/vscode#136310]
Intermittently, but frequently, when I run a cell in a notebook the vertical bar that denotes the active cell doesn't advance from the current to the next cell when I run via Shift-Enter. This seems to occur after working with the same notebook for some time. Closing and reopening "fixes" the issue for a time then eventually it re-occurs. I'm using python notebooks 

This started a few releases ago, I'm fairly sure when the "new" notebook system was released.

## Environment data

-   VS Code version: 1.61.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1101343141
-   Python Extension version (available under the Extensions sidebar): v2021.10.1365161279
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04
-   Python and/or Anaconda version: 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pyenv
-   Jupyter server running: Local

## Expected behaviour

Running a cell via Shift-Enter should move the cursor to the next cell

## Actual behaviour

After working with any notebook for some time, eventually Shift-Enter keeps running the same cell.

## Steps to reproduce:

Intermittent so not able to reproduce reliably.

## Logs

I've not seen anything in the logs when this occurs.

**Comment by roblourens** [comment]
Do you see the blue line move to the next cell? Is it running a cell different from the selected one (with the blue line on the left)?

**Comment by david-waterworth** [comment]
No the blue line stays on the same cell rather than moving to the next. So Shift-Enter keeps running the same cell over and over

**Comment by roblourens** [comment]
Not sure what the issue would be here, a gif/screen recording might help.

**Comment by david-waterworth** [comment]
Next time it happens I'll try and remember to record. As I said it's intermittent, and I don't use notebooks every day so there may be a delay before I get to it.

**Comment by david-waterworth** [comment]
So just an update on this, it's happened several times since I reported. The problem is I cannot make a screen recording.

The issue is "fixed" by switching focus away from the vscode window and then back again. So there's no way to start recording as each time it happens I have to switch focus from vscode and when I switch back the problem has gone.

**Comment by harripj** [comment]
Looks to be the same as #133038. I don't know if there if there is a fix for this yet, but there is a larger discussion there.

**Comment by david-waterworth** [comment]
@harripj yes I think you're right. I'll close this.
