### ISSUE TITLE
Vscode@1.61.2 crashes a lot

### ISSUE THREAD

**Issue by codTango** [microsoft/vscode#136370]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.61.2
- OS Version: macOS Catalina Version 10.15.7

Steps to Reproduce:

1. Normal use of vscode
2. Dialogs like the attached screenshot shows up randomly
3. Sometimes, it could continue to work when click on "Keep waiting"
4. Sometimes, I have to click on "reopen" to make it continue to work.
Attached(problem-report.dmp.zip) is a problem report when it crashes recently.

![image-2021-10-19-13-13-20-225](https://user-images.githubusercontent.com/5359697/140114300-86bdd6d8-baad-4a29-80a8-f0c41bff710e.png)
![image-2021-10-19-13-13-52-179](https://user-images.githubusercontent.com/5359697/140114531-a633c8f2-6991-4c41-bd96-3eb7c7685ad1.png)

[problem-report.dmp.zip](https://github.com/microsoft/vscode/files/7469374/problem-report.dmp.zip)

**Comment by Grimmstar** [comment]
I've experienced this issue as well, running VS Code + WSL on Windows 10, so it's not OS exclusive.  For me, I'll get the dialog pop-up every 10-15 minutes, and sometimes clicking "Keep Waiting" just causes the entire program, dialog included, to freeze and become unresponsive.

**Comment by deepak1556** [comment]
@codTango when the hang happens can you take a process sample using the activity monitor,

Check for `Code Helper (Renderer)` process that has high CPU usage and select the following option
<img width="554" alt="Screen Shot 2021-11-05 at 8 45 33 PM" src="https://user-images.githubusercontent.com/964386/140505783-5a4012aa-90c5-4aac-a028-00d9134a76b1.png">

**Comment by codTango** [comment]
@deepak1556 I'm able to get a sample process when it hangs, check the attached file.
[Sample of Code Helper (Renderer).txt](https://github.com/microsoft/vscode/files/7486440/Sample.of.Code.Helper.Renderer.txt)

**Comment by codTango** [comment]
@deepak1556 any update?

**Comment by codTango** [comment]
just checking, it's been a month, any findings so far?
