### ISSUE TITLE
Cannot open more than one tab of code simultaneously 

### ISSUE THREAD

**Issue by ppicom** [microsoft/vscode#136493]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.0
b3318bc0524af3d74034b8bb8a64df0ccf35549a
arm64
- OS Version:
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165

Steps to Reproduce:

1. Open VS Code
2. On side bar, click to open a file and edit the file (the tab name goes from italic to normal).
3. Click another file on the sidebar to open, it should open in another tab but it doesn't.
4. It also happens with any other kind of tab, not only code. Happens with: release notes tab, settings tab, etc

https://user-images.githubusercontent.com/15328250/140479849-30d76092-426f-437d-ade6-fc7a320106e8.mov

**Comment by yume-chan** [comment]
Either you disabled tabs (F1 -> Toggle Tab Visibility) or you are in Zen mode (F1 -> Toggle Zen Mode)

**Comment by ppicom** [comment]
Oh snap, how stupid of me! I didn't know about the Tab Visibility toggle... That solved it for me. Thanks!
