### ISSUE TITLE
[zsh] Integrated Terminal Keeps Printing Current Path When Using zsh with 256-color

### ISSUE THREAD

**Issue by lixin-wei** [microsoft/vscode#136487]
- VS Code Version: 
```
Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:49:28.381Z (2 wks ago)
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```
- OS Version: MacOS Big Sur 11.6 (20G165)

# Description

See the following video:

https://user-images.githubusercontent.com/19600697/140468780-dd45ffeb-b180-4157-86ce-4187e10701be.mov

Steps to Reproduce:
1. install zsh
2. select zsh as default profile for vscode's terminal
3. open a integrated terminal
4. keep typing `enter`.

**Comment by meganrogge** [comment]
I can't reproduce the issue. It looks like you have some styling of zsh or have customized it in some way. Could you provide me with the contents of your `.zshrc` file and any terminal settings?

**Comment by lixin-wei** [comment]
@meganrogge Thank you for your reply! After debugging for a while, I think it's something related to themes and `export TERM=screen-256color`.

Would you please follow the following steps:
1. install zsh
2. install oh-my-zsh
3. edit ~/.zshrc, update `theme='candy'` and add `export TERM=screen-256color`
4. open vscde, open integrated terminal with zsh profile.
5. `cd` to a long file path(the default path `~` is too short to recognize)
6. keeps typing `enter`

**Comment by Tyriar** [comment]
Why are you setting `$TERM`? We set that to the value that works best for our terminal, it's meant to indicate the capabilities of the terminal.
