### ISSUE TITLE
Support inline completions for TypeScript extension.

### ISSUE THREAD

**Issue by Kingwl** [microsoft/vscode#136411]
TypeScript has plugin api and we can use them to customization the behavior of language service.

And we need to support the feature at ts extension before we use the plugin.

**Comment by mjbvz** [comment]
Upstream PR https://github.com/microsoft/TypeScript/pull/46681

**Comment by mjbvz** [comment]
The inline completion API has now been finalized on the VS Code side but I'm going to close this until the feature has been accepted by typescript: https://github.com/microsoft/TypeScript/issues/45001
