### ISSUE TITLE
Multiple command not found errors for any extensions installed on code 1.61.2 on Intel chip macOS 12.0.1 (Monterey) 

### ISSUE THREAD

**Issue by filfreire** [microsoft/vscode#136439]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: `1.61.2 (Universal) Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643`
- OS Version:   macOS 12.0.1 (21A559) (Monterey) - Darwin 21.1.0

![Screenshot 2021-11-04 at 14 15 55](https://user-images.githubusercontent.com/11976836/140329821-4217be5e-a54c-452b-9cca-f8811ae2d4bf.png)

```
Version: 1.61.2 (Universal)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:49:28.381Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```

Steps to Reproduce:

1. Install vscode on macOS 12.0.1.
2. Install a few extensions (example: `shardulm94.trailing-spaces-0.3.1`, `streetsidesoftware.code-spell-checker-2.0.12`, `yzhang.markdown-all-in-one-3.4.0`)
3. Try to edit an `.md` file through vscode.

Most installed extensions seem to no longer work, all of them returning some form of `command '<some command>' not found` error messages and dialogues, examples:

![Screenshot 2021-11-04 at 14 13 25](https://user-images.githubusercontent.com/11976836/140331243-fdc7a1cf-855f-4f30-9853-28d66020d263.png)

![Screenshot 2021-11-04 at 14 18 04](https://user-images.githubusercontent.com/11976836/140331265-3063b61d-4753-4a98-afed-59ee3fa226d3.png)

![Screenshot 2021-11-04 at 14 13 52](https://user-images.githubusercontent.com/11976836/140331293-2e56b482-a608-4756-8a2e-c8f3f70690a3.png)

![Screenshot 2021-11-04 at 14 24 34](https://user-images.githubusercontent.com/11976836/140331360-bb10baa2-fb16-4601-a026-12ded0c573a4.png)

![Screenshot 2021-11-04 at 14 24 39](https://user-images.githubusercontent.com/11976836/140331365-b9e06e36-1c87-4215-abf8-773d97a0e153.png)

> Note: The same extension versions and VSCode 1.61.2 seem work fine on Windows 10 Pro. Could be something macOS specific.

**Comment by joyceerhl** [comment]
Do you still see this problem with the latest release (1.62)?

**Comment by filfreire** [comment]
@joyceerhl I've also seen this problem happen in the latest release.

My running theory is that it might be something due to using the new macOS Shortcuts to launch the VS Code app - as I've hit a similar issue with the Docker Desktop App.

I was launching VS Code (and VS Code Insiders) from a macOS shortcut. It seems that by doing so - it caused the extensions to not load - and remain in this state where for every action that would trigger a command in an extension, we get command not found.

![Screenshot_2021-11-05_at_11_59_36](https://user-images.githubusercontent.com/11976836/140507534-ef47616e-5e4e-4968-80ed-8074cf7d08c9.png)

This does not seem to happen if, right after initial boot, I launch VS Code from Automator or from Terminal (using `code` on PATH).

**Comment by deepak1556** [comment]
@filfreire can you provide the step by step instruction on how you created the vscode shortcut, since the issue is associated with a specific setup, it would help us repro it. Thanks!

**Comment by filfreire** [comment]
@deepak1556  sure thing, here goes:

## Before creating the shortcut
1. Install vscode on macOS 12.0.1.
2. Install a few extensions (example: `shardulm94.trailing-spaces-0.3.1`, `streetsidesoftware.code-spell-checker-2.0.12`, `yzhang.markdown-all-in-one-3.4.0`)
3. Try to edit and save an .md file through vscode.

## After installing and setting up VSCode
1. Open Shortcuts app (comes with macOS 12.0.1)
![Screenshot 2021-11-09 at 10 36 34](https://user-images.githubusercontent.com/11976836/140908977-c2fa28bd-ee3b-4bb7-b9b9-c17a6c268e66.png)

2. Create new shortcut
![Screenshot 2021-11-09 at 10 38 17](https://user-images.githubusercontent.com/11976836/140909243-aa27dfda-38c8-4aad-ac03-a67d5d8b65b1.png)

3. Add open app step, assign VS Code to it, and save the shortcut
![add_open_app](https://user-images.githubusercontent.com/11976836/140910038-611729bd-022c-4ba5-b9cd-3b343924ec24.png)

4. Restart the mac

5. Run the saved shortcut

6. Once VS Code is open, try to open edit the markdown file. If the issue is happening, you should be getting `command not found` errors when trying to press `Enter` or `Tab` key, and you should also notice that the extensions aren't properly loaded and aren't doing anything on the open file.

**Comment by deepak1556** [comment]
Unable to repro the issue with latest insiders.
