### ISSUE TITLE
Incorrect handling of -c in shell args when launching a task

### ISSUE THREAD

**Issue by owtaylor** [microsoft/vscode#136459]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2 (via Flathub Flatpak)
- OS Version: Fedora Linux 35

Steps to Reproduce:

1. Add a terminal profile with args that contain "-c", in `settings.json`:
```json
"terminal.integrated.profiles.linux": {
    "chatty": {
        "path": "bash",
        "args": ["-c", "echo Hi; exec \"$@\"", "-", "/bin/bash"],
    },
}
```
2. Set this as the default profile, in `settings.json`:
```json
"terminal.integrated.defaultProfile.linux": "chatty"
```

3. Create a task - e.g., the basic example shell task - `tasks.json`:
``` json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "echo Hello"
        }
    ]
}
```

4. Run the the task, see it fail:
```
> Executing task: echo Hello <

Hi
/bin/bash: echo Hello: No such file or directory
The terminal process "bash '-c', 'echo Hi; exec "$@"', '-', '/bin/bash', 'echo Hello'" failed to launch (exit code: 127).
```

The problem here is that there is supposed to be an extra -c added before `'echo Hello'` so that bash executes the command "echo Hello" rather than trying to run a script called "echo Hello", but that is omitted because there already is a `-c` in args - I believe the relevant code is:

https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1141

I'm unclear about the intent of this code - of all the arguments that can be in `toAdd`, the only one it seems to make sense for is the `/d` parameter to cmd.exe. For other flags, skipping adding an additional flag can't make things better and may make things worse.

The above example is obviously artificial - original context is https://github.com/owtaylor/toolbox-vscode/issues/11 where `capsh -- -c` is being used to avoid unexpected capabilities inside a container.

**Comment by alexr00** [comment]
Some quick testing indicates that adding the same arguments more than once can have negative consequences:
```
PS D:\repos\Microsoft\vscode> wsl.exe -e echo hello
hello
PS D:\repos\Microsoft\vscode> wsl.exe -e -e echo hello
PS D:\repos\Microsoft\vscode>
```
So the fix isn't as simple as always adding duplicate arguments. Additionally, I would be surprised if some users haven't come to rely on the de-duping of arguments.

It might be a good heuristic to only add the `toAdd` arguments when the _last_ argument isn't already in the `toAdd`. I'll need to think about it a bit more.

**Comment by owtaylor** [comment]
Ah, I missed the fact that the args could be coming from `task.options.shell.args` not just the configured terminal - in that case, yeah, it's possible to imagine that someone is accidentally relying on `shell: 'wsl.exe'; args: ['-e]'` working.

For arguments from the default profile or `terminal.integrated.shellArgs.<platform>`, something like 'wsl.exe -e' doesn't seem possible since the arguments have to work by itself. (Since you just added `terminal.integrated.automationProfile`  added and its not yet released, I assume that nobody is relying on any particular behavior with the arguments there!)

Certainly, if a reliable heuristic could be found, that would be the best combination of backwards compatibility and not doing something weird in the edge cases like the one I hit :-) Better than treating the args differently depending on their source.

The way that bash and related shells work with -c is that it can be followed by short options (-x, say), but not by long options ('--init-file /opt/bashrc`), so I think a fully correct heuristic for that is "if -c is in the arguments and all arguments after -c start with -, don't add another -c". For cmd.exe/powershell.exe/wsl.exe, it seems plausible to me that your "last argument" heuristic is fully correct.

**Comment by IanMatthewHuff** [comment]
Verified as fixed on insiders (stable on the right in screenshot for comparison)
![image](https://user-images.githubusercontent.com/812783/151607876-28bf18ae-77ed-4229-ad7d-b1f0947cb729.png)
