### ISSUE TITLE
Inconsistent syntax highlighting for C#

### ISSUE THREAD

**Issue by gustavo-shigueo** [microsoft/vscode#136442]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2
- OS Version: Windows 10 21H1

Some keywords have the wrong scope causing weird syntax highlighting

Steps to Reproduce:

1. Use more recent C# features such as target-typed new or the is not operation or the and/or keywords in a switch statement
2. Open the command pallete
3. Use the command "Developer: Inspect Editor Tokens and Scopes"

Sample code
```cs
using System;

namespace HelloWorld
{
	public class MyClass 
	{
		public MyClass()
		{
		}
	}

	class Program
	{
		static void Main(string[] args)
		{
			var stringArr = new[] { "", "" }; // new shows as keyword which is probably the expected behavior
			MyClass myClassInstance = new(); // new shows as a function call

			if (myClassInstance is not null) // is shows as keyword but not shows as a type annotation
			{
			}

			int x = 10;
			switch (x)
			{
				case > 1 and < 5 or 10: // both and and or show as variable names
					break;
				default:
					break;
			}
		}
	}
}
```

Screenshots:
![image](https://user-images.githubusercontent.com/58121396/140332929-2f4ec8be-d6d2-4427-9cc0-9f057a02c751.png)
![image](https://user-images.githubusercontent.com/58121396/140333007-a061d152-1b74-463e-8330-801a7e6ed917.png)
![image](https://user-images.githubusercontent.com/58121396/140333120-bb086646-cdde-4d14-a098-7e1bdab7d374.png)
![image](https://user-images.githubusercontent.com/58121396/140333208-a33ca5fc-fc67-4ff7-b552-4d6771f4d183.png)
![image](https://user-images.githubusercontent.com/58121396/140333330-1af40b4e-7d65-4e96-8cd1-8ef9341f2caf.png)

**Comment by alexr00** [comment]
Thank you for the clear sample and screenshots! I've moved the issue into the repository that we pull our C# syntax highlighting grammar from: https://github.com/dotnet/csharp-tmLanguage/issues/232
