### ISSUE TITLE
Add FTP Syncing 

### ISSUE THREAD

**Issue by cosmegt** [Microsoft/vscode#13643]
Please, I would be grateful if you were to add FTP uploading/downloading from VS code, I use VS 2015 but if you add this, I would immediately switch.

I think a lot of people would like this feature.

Sincere thanks.

**Comment by ggregoire** [comment]
2 extensions provide what you are asking for:

* [ftp-simple](https://marketplace.visualstudio.com/items?itemName=humy2833.ftp-simple)

* [ftp-sync](https://marketplace.visualstudio.com/items?itemName=lukasz-wronski.ftp-sync)

Hope it can help.

**Comment by joaomaridalho** [comment]
None of the plugins compare to a native FTP Solution like Netbeans, VS etc...

**Comment by LawJolla** [comment]
@joaomaridalho agreed.  I use tired old Coda to deal with remote files for its FTP client.  Many of us don't want to sync files -- we want to log on to a remote server and edit them on the server.

**Comment by joaomaridalho** [comment]
@LawJolla I love VS code but it's one major deal breaker when you use ftp alot,  when I'm developing electron applications VS code is simply the best tho

**Comment by LawJolla** [comment]
@joaomaridalho Good news... the docs are horrendous, but the ftp-simple package does what I (and I think you) need.  It looked to be a synchronizer, but it allows server editing and saving.  Give it a try and let me know -- I'd be surprised if it didn't work for you.  https://marketplace.visualstudio.com/items?itemName=humy2833.ftp-simple

**Comment by joaomaridalho** [comment]
Thanks @LawJolla I will look into it

**Comment by technbuzz** [comment]
@ggregoire for some reason these two packages slow down my VSCode. So the only way to go is to wait for built support.

**Comment by realee94** [comment]
I hope there will be a native, built-in FTP feature with multiple servers (selectable default one as well) and directory mapping (so I don't have to browse to which folder I want to sync my file in the project).

**Comment by JMCA2** [comment]
+1

This was one of the most requested features on UserVoice: https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7752729-ftp-editing

**Comment by Alex360hd** [comment]
Testes ftp-simple and ftp-sync. It's ok for automatic file upload on save, which is a good time saver.

But I would love to see a ftp browser on the explorer sidebar, that allow me to quickly pick a file on the remote server and edit it. which is something I do everytime in my job, as a lot of web developpers.

When you use CMS like drupal, wordpress, or magento, you just don't want to sync the whole project of several thousand of files in order to make minor modifications...

**Comment by balohmatevz** [comment]
The two suggested plugins break endlessly and hang on websites with lots of files, fail to maintain sessions, don't upload reliably, etc. They are a cause of a lot of frustration. A native implementation of FTP file download/upload (or a reliable plugin) is the only thing keeping me from moving to VS Code as my main scripting tool.

**Comment by VaclavElias** [comment]
+1

**Comment by emkographics** [comment]
+2
This would be deal breaker. I'm trying to stop using coda as i keep going back to it due to the remote ssh folder view that allows direct editing on the server.

**Comment by LawJolla** [comment]
@emkographics Agreed.  That's the only reason Coda is still on my hard drive.  Their FTP implementation is perfect.  (The text editor... well, it's fine for 2007 🥇 )

**Comment by ArkhipovK** [comment]
+3
The ftp-explorer is indispensible. Also as  password hiding (inside config) and multiserver manager.

**Comment by Alex360hd** [comment]
+1 vote for this. Even if there are external plugins that provide FTP syncing, a good FTP explorer is missing (same than the file explorer, but remotly) and I'm not sure if the VS code architecture can allow external plugin to implement that.

**Comment by realee94** [comment]
Regarding FTP deploy/download, I suggest using [VS-Deploy](https://github.com/mkloubert/vs-deploy)

**Comment by Alex360hd** [comment]
There is no remote file browser like the explorer sidebar in VS-Deploy

**Comment by balohmatevz** [comment]
Here is a visual representation of precisely how I would like this to work: http://l1m.eu/f0uv2qm3 (video)

I've gone back to Notepad++ as a plugin for it adds precisely the capability I want and that's worth more to me than the benefits VS Code has over Notepad++.

**Comment by Fire-Brand** [comment]
+1

**Comment by yolo2013** [comment]
+1

**Comment by yolo2013** [comment]
@realee94 vs-deploy is so sloooooooow..... coda 2 and Webstorm is better than all vs code plugins now.

**Comment by pwwang** [comment]
+1 I switched back to KomodoEdit until this feature is added.

**Comment by fulldecent** [comment]
I use Atom. If VS Code can successfully implement this feature (which has only been done correctly a few times in the history of all text editors) then I will switch.

**Comment by jens1o** [comment]
Well, since there is a new api, it can be better integrated as an extension.

**Comment by fulldecent** [comment]
@jens1o Would you be able to provide insight on which new APIs would enable @balohmatevz's vision above (https://github.com/Microsoft/vscode/issues/13643#issuecomment-291084609) to be built?

Everyone in this discussion has probably suffered through second-class remote file editing a la Atom and Code. If a new API allows this to be done, which has never been done before, then maybe people will contribute to a bounty to get it done.

**Comment by jens1o** [comment]
https://github.com/bpasero/vscode-ftp-example
Extensions are now able to add a new tree to the sidebar

Screenshot here: https://github.com/Microsoft/vscode/issues/26948#issuecomment-303036936

**Comment by emkographics** [comment]
@fulldecent what is your issue with Atoms remote file editing? The Remote-FTP package looks promising. I've just installed it and will try using it. I'd like to know what issues you were having with it since I'm fairly new to it.

**Comment by fulldecent** [comment]
Thanks for the survey. The issue it it requires setup:

---
https://atom.io/packages/remote-ftp

Getting started

- Open an existing project or create a new one (File -> Open folder...)
- Open remote-ftp sidebar (Packages -> Remote-FTP -> Toggle)
- Create a configuration file for your project (Packages -> Remote-FTP -> Create (s)FTP config file)
- Once connected you should be seeing the content of the remote connection
- All basic commands (connect, disconnect, ...) are available from the sidebar context menu and the Command Palette
---

Instead I am hoping for File->Open->Network Folder and then you type in `sftp://root@server:/var/www` and then it just works.

Currently I pay Panic $50 for that convenience and I get their abandonware Coda app. Panic makes it look good. And Coda makes it very clear that you are getting first-class support for SFTP not some afterthought.

**Comment by pwwang** [comment]
@fulldecent You would like to try Komodo Edit, which does a good job in opening remote folders, and it's free.

**Comment by fulldecent** [comment]
@pwwang Very nice, thank you!

**Comment by Qibbles** [comment]
Atom just feels really sluggish to me, but remote-ftp did what I needed with it's remote file explorer. If VSCode has support for that, it'd be perfect!

**Comment by rtpm** [comment]
+1

**Comment by JulianBerger** [comment]
+1 , also using atom because of remote-ftp

**Comment by NickolasGame** [comment]
I think we need something better then just built in ftp. For example it can be somehing like built-in deploy manager with support of ftp , sftp, other managers, remote edit files on server, downloads from server and other wide options set. Making all two using the extension is good if extension is very good and give all features and if target which extensions provide is not so popular to include it.
The best approach is maintaining support of ftp as extension but with support of it from core team and bundle it with VSCode

**Comment by Qibbles** [comment]
Actually I've just found out that ftp-simple for vscode has a beta feature called remote working woe something like that that works pretty well so far for remote file explorer and remote editing. Was a bit confusing when I was trying to set it up but now it works quite well and feels snappier than atom ever would! Give it a try!

**Comment by Fire-Brand** [comment]
@Qibbles, there are still many issues with ftp-simple that could be solved with a native ftp solution from the VSCode team. For exmaple - i'm unable to connect to any remote server on my Macbook with MacOS 10.12.4 
Hopefully this feature will come soon....

**Comment by pwwang** [comment]
@Fire-Brand Yes, you are right. Here is another issue. A watch function is definite necessary. I pulled files from github on the server, but ftp-simple did not sense that. I modified files in vscode and all codes messed up, as the files being opened in vscode was not updated. I was really frustrated. This happened to me twice!

**Comment by sonyarianto** [comment]
SFTP built-in is a must to increase VSCode credibility, since this feature is very importance puzzle piece on software development. I like the SFTP plugin in Sublime Text.

**Comment by NickolasGame** [comment]
Native ftp solution is very good idea, but i think it would be better to move this feature to next milestone, because this milestone is near to its close and ftp need to big time for solid implementation

**Comment by pwwang** [comment]
@NickolasGame Where can we find the milestone information? Thanks.

**Comment by NickolasGame** [comment]
What did you mean "the milestone information"

**Comment by pwwang** [comment]
@NickolasGame I mean what's included in the plan and when a milestone closes, and what will be included and when for the next one.

**Comment by vfhky** [comment]
we can explore or edit remote files just like in our local windows machine.
![sftp](https://user-images.githubusercontent.com/982423/29057940-1f5645c2-7c40-11e7-8dfa-722c9cc15ee5.png)

**Comment by elabx** [comment]
Pus one on this, I'd suggest taking a look at how easy emacs does this, you just write the address and boom you are connected on ssh or ftp. Then you can just bookmark the address and you can connect directly to a directory i see this working amazingly on the search bar. It would be a killer feature for VS Code.

**Comment by jpldev** [comment]
+1

**Comment by architchandra** [comment]
+1

**Comment by jiamings** [comment]
+1

**Comment by javicorvus** [comment]
+1

**Comment by andregce** [comment]
+1

**Comment by greglamb** [comment]
+1

**Comment by Chinafreak** [comment]
+1

**Comment by shrowdes** [comment]
+1

**Comment by Dark-Bow** [comment]
+1 This really needs to happen, ftp-sync is fine if you are working on small projects. When it comes to magento, you cant keep downloading 1000's of files each time.

**Comment by cwberick** [comment]
+1

**Comment by pwwang** [comment]
I guess it will happen soon. In 1.17 preview version, a Remote File System API was provided.
https://code.visualstudio.com/updates/v1_17#_preview-remote-file-system-api

**Comment by TomS-** [comment]
I would love for this to happen, it's the ONLY reason I jump back to Atom every now and again because they have a very good Remote-FTP module, https://atom.io/packages/remote-ftp 

With the API to build something like this, that would be amazing

**Comment by Izopi4a** [comment]
i am pretty sure i am not the only one not using vscode just because of that.

just with ftp include and sftp as well.

hopefully we will see a native remote deployment some day

**Comment by manuman94** [comment]
+1

**Comment by ajmariduena** [comment]
+1

**Comment by keywest1** [comment]
+1

**Comment by keepalot** [comment]
👍

**Comment by imnickvaughn** [comment]
+1

**Comment by benoitlemay** [comment]
+1

**Comment by MarcoUsai** [comment]
+1

**Comment by wuwb** [comment]
+1

**Comment by GuillaumeHumbert** [comment]
Please give a thumbs up on the first post of this thread instead of "+1ing" in replies, maintainers are not able to sort issues by the amount of "+1" present in the thread, and it clutters the thread

**Comment by khimaros** [comment]
I've authored a remote SFTP plugin using the proposed RemoteFilesystem API available in code-insiders. Check it out here: https://github.com/khimaros/vscode-remote-sftp

**Comment by frank-dspeed** [comment]
This topic should be closed i think this is totally wrong next we build a operating system into VSCODE=? and as Arcade Gaming is importent while building and running CI tests we should insert a PS3 Emulator?.

## Deploy your vscode projects 
- use a taskrunner
- if your a nodejs user use the package.json that already exist
- if your a php user write some bash scripts or php scripts for deployment
- and so on.

Greetings.

**Comment by einord** [comment]
@frank-dspeed I disagree. With the same kind of logic IDEs should not exists, since it's better to use separate applications for source code editing, compiling and debugging?

In a modern source code editor where a lot of code is on the web and often on an FTP, this functionality can great.

And as an example, if a separate ftp client is used listening for file changes, it is a lot harder when using git to determine a selected branch that should be uploaded only.

**Comment by frank-dspeed** [comment]
@einord i disagree for the same reason as git is already used you should setup general CI tests and Deploy from them if they pass as we do with the Linux Kernel the IDE should not matter for Deployment its a Code Editor with Coding Helpers it don't Replaces all that.

**Comment by einord** [comment]
@frank-dspeed It all comes down to usability.
If a significant group of the users will benefit from a feature when working with an application, and it will not disrupt the workflow for those not interested, it might be a good idea to implement it.

For a lot of users this is very useful. Maybe they are maintaining a simple web site where testing or complicated deploy processes is not the case. They just want to publish the site from the master branch (or no branch at all for that matter), whenever they feel done with their work.

I have a LOT of cases where this would help me a lot, where I just want to quickly upload my changes when done without the hassle of finding and configuring a separate application to sync my files for each project.

Also, please do not spam emoji reactions on critics just because you disagree.

**Comment by frank-dspeed** [comment]
@einord sorry that don't exist and leads to bad coding Practice i can't push this kind of work ethic on the Internet i will not tolerate such flows and will blame and even law SUE in the US and EU any Developers doing such stuff on client work!

**Comment by Alex360hd** [comment]
Completely agree with @einord (and so, disagree with @frank-dspeed). 

When you develop web application, ftp sync is essential and having it integrated to a sidebar can have several benefits over using an external application. Just the fact to have the FTP remote access embeded to the IDE sidebar let me do that 2 functions in only one screen, letting the second screen for another useful application.

Sounds anecdotic ? Maybe but actually, this is THE missing feature that prevent me (and all developpers in my company) to use VScode in my everyday job and I prefer to use ATOM just because there is that FTP sidebar (whereas globally, I prefers VScode).

So, finally, if a feature prevent a lot of developpers to adopt the application, it would be an error to ignore them and letting them to use concurrent app.

**Comment by TomS-** [comment]
@frank-dspeed What? 
> next we build a operating system into VSCODE=? and as Arcade Gaming is importent
I'm sorry, but that's just a silly comparison. I'm not going to jump into debating with you why Remote FTP access is good. I don't need to. Surely all the "+1" and people thumb's up-ing the OP is enough. For what reason you are against adding new features is beyond me.

All I'll say is, It's like saying this new Live Share (https://code.visualstudio.com/blogs/2017/11/15/live-share) is silly because it can all be done in Git. Everyone has their own way of working. Some people who work alone (freelancers) and on multiple computers (freelancers) like to host their development server using something like Digital Ocean rather than developing locally and using something like Docker.

**Comment by khimaros** [comment]
Interestingly, if Live Share could be run headless, it could be used to power some of the same use cases as SFTP.

**Comment by frank-dspeed** [comment]
@Alex360hd why don't u just use the integrated terminal and create a sync batch that runs your favorit sync to upload your changes to the FTP?

There are tons of clients for that it means round about 1 line of code 1 extra file that also holds deployment information?

is that really blocking?

**Comment by emkographics** [comment]
No, @frank-dspeed, no. We want to click on, open, and close things, browse through directories using the UI, and use ctrl+s to save right then and there, on the spot, in real time. Why? We just do. This doesnt have anything to do with making live code changes on prod. Im not sure how you came to this assumption in first place. Other IDEs out there support it. I've used all sorts of sync solutions and plugins on this one and it's simply not satisfying.

**Comment by frank-dspeed** [comment]
@emkographics sounds like a perfect use case for mounting a sftp/ftp folder?

**Comment by einord** [comment]
Please, this is a request that several users would benefit from, and would help them in their work.
Of course you can solve a problem in multiple ways, and some may even be better than the requested feature sometimes. But as long as a big enough group of people would benefit from this it is a good idea to implement it.

This is not a discussion about how to solve a problem, it is a feature request people would be happy to see in a (hopefully soon) future update.

**Comment by frank-dspeed** [comment]
@einord ok i accept that sure but its also importent that a lot of people understand that the current problem of open source is not about missing features its about missing knowleg about the existing tech.

Duplicating functionality all over the opensource world in general is waisting time of tons of developers that could focus on new edge tech and not 70 year old ftp Tech

**Comment by TomS-** [comment]
@frank-dspeed You are getting increasingly annoying.

Where did you get them numbers from? There are plenty of FTP extensions available: https://marketplace.visualstudio.com/search?term=ftp&target=VSCode&category=All%20categories&sortBy=Relevance 

I very much doubt that these are manned by 15+ people spending 8 hours a week over years of work. All people are asking for is a remote file tree, which is already in the works with VSCode in which one of the developers for VSCode created an FTP as an example (https://code.visualstudio.com/updates/v1_17#_preview-remote-file-system-api, https://github.com/jrieken/ftp-sample). 

Now if you would like to explain to the developers of VSCode why they should stop working on this go ahead. However, if you aren't prepared to do that, then please stop commenting nonsense.

**Comment by pwwang** [comment]
@TomS- +10
@frank-dspeed Just stop commenting if you haven't really worked on a project that needs remote editing. You just don't understand what kind of convenience it will bring to us if you can just simply operate the remote files/folders on the sidebar.

**Comment by cosmegt** [comment]
@frank-dspeed 
>Duplicating functionality all over the opensource world in general is waisting time of tons of developers that could focus on new edge tech and not 70 year old ftp Tech.

Okay, yes... FTP is old... You know what else is old? Basic, Assembly, C, actually, most old technologies are about the best ones, that's why they are still relevant... Just because you don't see other use of FTP other than web development, doesn't mean is not useless, FTP is just another way to save files into a server, FTP could work for saving code, just like github, but without the GitHub environment. 

If you don't understand what you are talking about, you better not talk, or you make yourself look dumb. 

>but as all in here are developers they can integrate what ever they like and fits the needs. as own VSCode Extension. Also most of the Atom Extensions are easy to Convert as its all JS.

Yea just as an extension? Then why is GitHub Sync integrated? And not an extension?

**Comment by SteffNC** [comment]
Actually the ftp-simple extension https://github.com/humy2833/FTP-Simple is almost doing the same job like the remote-ftp for Atom https://github.com/icetee/remote-ftp 
BUT:
The missing support for FTP over TLS is simply my reason **not to use** that.
Maybe someone is able to change the node module jsftp that it supports FTP over TLS?
Cheers

**Comment by javicorvus** [comment]
@SteffNC ftp-simple is a great extension, I can add another reason to **use it at your own risk** : [Contents Erased Issue](https://github.com/humy2833/FTP-Simple/issues/94) , my solution so far is to use [FreeFileSync](https://www.freefilesync.org/) and synchronize a local copy of the project with the remote.

**Comment by suzeeparker** [comment]
I'm trying to use ftp-simple (see below).  Is it true that Microsoft is developing an internal capability, and that they are the authors of ftp-simple -- keeping it in sync with their development?  

I will second the need for editing remote files in cloud servers.  VSCode is close to providing a UI with a file explorer on the left, an editor that can silently download, save and upload remote files in the middle pane and an SSH shell at the bottom to run commands.  The first time I saw such a clean UI was SSH Explorer, even though Coldfusion and Frontpage came close.  Notepad++'s NPP-FTP plugin currently creates this ability.   

Here is what I've done so far --

 - I've installed ftp.simple, 
 - I've watched the YouTube video, 
 - I've created a SFTP config for a remote server in the ftp-simple-temp-json, and 
 - I've run the command: Open the file directly from FTP server, among others. 
 - I'm using SFTP, not FTP, 
 - I've tried a site with a UserID and Password, and 
 - I've tried a site with a certificate key, 
 - I can SSH into the server from the command line, 
 - I'm on a Windows 10 machine
 
 But nothing happens -- no messages as sent in the video. Any ideas about what is going wrong? 
 
 Is there a log file that I can look at? 
 
 Thanks, Sue.

**Comment by suryasr007** [comment]
As @SteffNC  mentioned, The atom remote-FTP is fully matured and solves every problem mentioned above. I use it every day.
If someone could able to port it to VS code, It would be benefit to VScode community

**Comment by Adobe-Android** [comment]
I'd also be interested to see a more native implementation that rivals Visual Studio.
