### ISSUE TITLE
Can drag inner window in mac fullscreen leaving empty background

### ISSUE THREAD

**Issue by n-smits** [microsoft/vscode#136451]
Issue Type: <b>Bug</b>

1. enter full screen with a side by side app
2. there is a small margin that when dragged wont resize window but instead resizes "inner" window leaving empty background (see screen recording: https://media.giphy.com/media/ynJ7AGy8j4rvztVlN4/giphy.gif)

VS Code version: Code 1.61.2 (Universal) (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|64.00GB (43.42GB free)|
|Process Argv|--crash-reporter-id 5b93b044-0933-447d-8064-99fe56bf5669|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
toggle-hidden|adr|1.0.2
svelte-intellisense|ard|0.7.1
make-hidden|dev|3.0.3
vscode-coffeescript-preview|dre|1.0.1
prettier-vscode|esb|9.0.0
vscode-markdown-todo|fab|1.1.1
wordcount|gab|0.0.1
todo-tree|Gru|0.0.214
tablegenerator|Jay|1.0.4
hide-gitignored|npx|1.1.0
scope-to-this|rha|0.2.1
vscode-fileutils|sle|3.4.5
svelte-vscode|sve|105.5.0
sass-indented|syl|1.8.18
language-stylus|sys|1.13.0
markdowntable|Tak|0.7.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.13.2

(3 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
experimental side panel leakage

**Comment by rzhao271** [comment]
Worked after I turned off the flag and reloaded.
