### ISSUE TITLE
Search in files, field files to include, option 'Only in Open Editors'

### ISSUE THREAD

**Issue by JensInBerlin** [microsoft/vscode#136449]
Issue Type: <b>Bug</b>

When I search (with regular expressions, I searched for \r) in all my files and have not activated the 'Search only in Open Editors' it seems, that some (but seemingly not all) files which _are_ open in an editor (maybe those in the active group?) are excluded from the search. As soon as I closed one of the files which have not been searched in the group and refresh the search the file appears in the search results

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (18.30GB free)|
|Process Argv|--crash-reporter-id f37fa1e4-663d-4ba4-9ba2-760c0f9b3cba|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.6.4
swagger-viewer|Arj|3.1.2
vscode-postgres|cko|1.1.19
xml|Dot|2.5.1
gitlens|eam|11.6.1
vscode-docker|ms-|1.17.0
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.11.0
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.66.0
proto|pet|0.0.2
vscode-yaml|red|1.1.0
local-history|xyz|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by roblourens** [comment]
It's not possible to search for the CR character in open editors, and when a file is open, workspace search only searches in that editor. https://github.com/microsoft/vscode/issues/31449
