### ISSUE TITLE
Search icons overlay the placeholder text

### ISSUE THREAD

**Issue by stone-zeng** [microsoft/vscode#136482]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.0 (Universal), Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
- OS Version: macOS 12.1, Darwin x64 21.1.0

Steps to Reproduce:

1. Click the search panel, and focus on the text box.
2. Resize the panel, then you can see the following:

<img width="182" alt="Screen Shot 2021-11-05 at 14 04 40" src="https://user-images.githubusercontent.com/18233088/140465767-6089fdc1-22c1-416d-b333-8aef43fe3ada.png">

**Comment by roblourens** [comment]
The sizing of input boxes is convoluted and probably should be refactored
