### ISSUE TITLE
Will show code of old function object which steped before while step in at second function object

### ISSUE THREAD

**Issue by flyingcodes** [Microsoft/vscode#1364]
![1](https://cloud.githubusercontent.com/assets/12825770/11834843/f570dac4-a40a-11e5-8399-3091155f89e9.GIF)
![2](https://cloud.githubusercontent.com/assets/12825770/11834847/f57dce96-a40a-11e5-90ff-9c8f33ea05c6.png)
![3](https://cloud.githubusercontent.com/assets/12825770/11834844/f573eb1a-a40a-11e5-9be8-d3028064f7b6.png)
![4](https://cloud.githubusercontent.com/assets/12825770/11834845/f5768dfc-a40a-11e5-870d-f6a8de40c9ea.GIF)
![5](https://cloud.githubusercontent.com/assets/12825770/11834846/f579cfd0-a40a-11e5-90bb-5c0fd4614659.GIF)

var fun1 = new Function("return 1 + 2; // in fun1"); // break point
var fun2 = new Function("return 3 + 4; // in fun2");
var r = fun1(); // the folow will step in code of fun1 if step in at this line
r = fun2(); // will step in code of fun1 if step in at above line, else step in code in fun2
console.info("r = " + r); // but the result is valid

**Comment by weinand** [comment]
@flyingcodes I can reproduce this, great find!

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-node-debug#24
