### ISSUE TITLE
Initialize the codespace with locally installed extensions when creating the codespace in Desktop

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#136424]
From @matthewisabel

**Describe the bug**
I'm not sure if this is intentional, but it is leads to a frustrating experience at times. For example, I have installed the GitHub Copilot extension in VS Code and it is synced.

![Screen Shot 2021-10-04 at 3 29 24 PM](https://user-images.githubusercontent.com/2132776/136065678-2565092f-612b-40c1-860d-cde4f04d3676.png)

If I create a new codespace in the browser, the extension is installed into the codespace. If I create a codespace from the VS Code desktop client, I can "Install in codespaces" when looking at my extension list.

The difference in desktop and web seems odd here as to why my synced extensions only install by default in one case.

![Screen Shot 2021-10-04 at 3 26 08 PM](https://user-images.githubusercontent.com/2132776/136065786-c877159c-1c0d-4f08-a4e2-bdfa8c8ab07e.png)

**To Reproduce**
1. Install an extension (one that requires to run on the remote extension host like GitHub Copilot) to your VS Code desktop
2. Sync that extension
3. Create a codespace from desktop, see that it's not installed without additional step
4. Create a codespace from web, see that it is installed

**Expected behavior**
Extension is installed

**Comment by sandy081** [comment]
The reason why we do not initialize extensions in a remote set up because not all remotes would like to get initialized with all local/synced extensions. For eg., If user has extensions like pthon/java/c++ installed and synced then installing these extensions in remote containers does not makes sense. Hence we left remotes (resolvers) to have their custom solutions: 

Remote containers defines a setting `remote.containers.defaultExtensions` using which user can provide list of extensions to be installed while creating the container. 

Also same with Remote SSH - `remote.SSH.defaultExtensions`

May I know if it is possible for Codespaces also to follow similar approach?

CC @jkeech @matthewisabel

**Comment by Chuxel** [comment]
@sandy081 It's important that Codespaces on the web and desktop do not have different behaviors here. I think the remote type needs to be able to dictate the appropriate behaviors so that we can be consistent and not confuse customers.

In the case of SSH and Remote - Containers, we opted to have always install extensions partly due to the absence of settings sync at the time of their release. I actually think allowing people to opt into sync'ing there makes sense. Codespaces made a conscious decision not to do that and to sync your desktop extensions with a one-time push.  We'd want to do the same thing on desktop.

The current dichotomy is confusing customers and I think it would be difficult to walk back the current web behaviors.

**Comment by jkeech** [comment]
Agreed that we don't want to have to have users set another setting to pick which extensions to sync/install. We just want Settings Sync to sync the extensions that users have already chosen to sync across machines.

**Comment by sandy081** [comment]
I would like this to be decided by the resolver as @Chuxel mentioned so that the interested resolver would opt in to initialize extensions on create.

**Comment by jkeech** [comment]
@sandy081 Are there remotes which would not want settings sync to install remote extensions? If so, would you expect that to be the majority or minority of remotes? I'm wondering if it should be an opt-out API instead of an opt-in API. And if there are no known cases where resolvers would opt out, then perhaps the opt-out API could be deferred until there's a request for it.

**Comment by sandy081** [comment]
As of now other than codespaces, no remote resolver has asked for auto initializing the remote machine with all local extensions. I also think most of the remote users are fine with the existing behaviour. Since, it is specific to codespaces, it makes sense for the resolver to opt-in.

**Comment by sandy081** [comment]
@jkeech May I know if you want to initialize the new codespace with local extensions always or only when settings sync is enabled?

**Comment by jkeech** [comment]
> @jkeech May I know if you want to initialize the new codespace with local extensions always or only when settings sync is enabled?

@sandy081, we don't want to sync local extensions per-se, but rather to sync the extensions which are set to sync in settings sync. Ideally we would always do the one-time downloaded regardless of the client's settings sync status, since the behavior of the remote side should mostly be independent of the client that is connecting. Then we would enable syncing in both directions if the client has settings sync turned on, which matches the web behavior and gives users the ability to sync extensions out if they manually install them in a codespace.

**Comment by sandy081** [comment]
Thanks for clarifying - I am planning to expose a flag (name/where is yet to be thought about). On enabling this flag, desktop when connected to a remote for the first time, initializes the remote with local extensions (all except those user flagged not to sync). 

Settings Sync from there on syncs local and remote extensions - this behavior exists already and is available for all defaults.

**Comment by sandy081** [comment]
> On enabling this flag, desktop when connected to a remote for the first time, initializes the remote with local extensions (all except those user flagged not to sync).

@jkeech please note that, this is independent of the desktop client's settings sync status/account. It means user would have not enabled settings sync at all or might be using another account for settings sync. So, there is still a possibility of mis-match with the web codespace.

**Comment by sandy081** [comment]
I am assuming that the codespaces extension can provide account info while resolving the resolver - ie., when the following method is called

https://github.com/microsoft/vscode/blob/1423849df0961e57065cb7b4c0effa13f7406595/src/vs/vscode.proposed.d.ts#L130

If that is true, I would like to add the following option to the returned result of the above API

```ts
export interface ResolvedOptions {
		
		initializeUsingAccount?: { providerId: string, sessionId: string };
	}
```

If the resolver provides account info for initialization, then VS Code will initialize the remote with the extensions synced using that account.

Please confirm. Thanks.

**Comment by jkeech** [comment]
Sounds good. We do have access to the account during resolve and can return that account info as part of the resolver's return object.

**Comment by sandy081** [comment]
Here is the proposal for above API

```
/**
 * When provided, remote server will be initialized with the data synced using given user account.
 * **Note:** Initialization happens only when VSCode is opened in Desktop and only extensions are initialized as of now.
 */
authenticationSession?: AuthenticationSession & { providerId: string };
```

Other options:

- authenticationSessionForInitialization
- authenticationSessionForInitializingExtensions

**Comment by jkeech** [comment]
@sandy081, the `authenticationSession` would be part of the `ResolverResult`, right? If so, that sounds great 👍. I don't have a strong preference on the naming.

**Comment by sandy081** [comment]
> the authenticationSession would be part of the ResolverResult, right?

Yes.

I will be getting some feedback on this API in our API meet today and confirm the name.

**Comment by sandy081** [comment]
Since this is specific scenario specific to codespaces, we decided to go with the name that explains what it says, which is `authenticationSessionForInitializingExtensions`

**Comment by jkeech** [comment]
Thanks @sandy081! I have a PR out for the Codespaces extension to use the new API, and in manual testing it seems to work well so far. 👍

**Comment by jkeech** [comment]
GitHub Codespaces extension 1.4.0 just shipped with this new API resolver property included.

**Comment by sandy081** [comment]
Verification steps:

- Open VS Code insiders and enable settings sync using your github account
- Make sure you have atleast one workspace extension installed and synced. Eg: GitLens
- Install GitHub Codespace extensions
- Create a codespace from the Remote explorer view
- When the Codespace is opened, verify that Gitlens (all synced extensions) are installed in the codespace.
