### ISSUE TITLE
[remote] opening folder dialog in broken remote window hangs

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#136425]
- run out of sources
- add at https://github.com/microsoft/vscode/blob/3ed654b8e8d0310e0fcdd4a08ef12d873c73816a/extensions/vscode-test-resolver/src/extension.ts#L353
```
	actions.push({
		title: 'Open Folder',
		execute: () => {
			vscode.commands.executeCommand('vscode.openFolder');
		}
	});
```
- run and in the OSS Dev window set `"testresolver.startupError": true`
- open a TestResolver window
- in the modal dialog pick `Open Folder`
- No dialog shows, resolver progress is spinning, nothing happens

**Comment by aeschli** [comment]
Not sure that ever worked. Not everything is working when still in a resolver.
The open folder dialog depends on `remoteAgentService.getEnvironment` which depends on the resolver to be completed.

I suggest to close the issue unless there is a demand for this to work. The issue from which this came out of (https://github.com/microsoft/vscode-remote-release/issues/5811) doesn't.

Speak up if you disagree @bpasero @alexdima

**Comment by bpasero** [comment]
Is this specific to the test resolver then? Or could this happen for others that are used too?

**Comment by aeschli** [comment]
It would happen with all resolvers. But there are only few resolvers out there, written all by us and the API is still proposed.
