### ISSUE TITLE
Source Control commit message field switching focus while typing

### ISSUE THREAD

**Issue by james-cast** [microsoft/vscode#136421]
Issue Type: <b>Bug</b>

While typing my commit message it will switch to a different commit box (when I have multiple folders/projects in the same editor).

Seems to have started since I last updated VS Code.

VS Code version: Code 1.61.1 (Universal) (c13f1abb110fc756f9b3a6f16670df9cd9d4cf63, 2021-10-14T01:23:30.274Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 60f58aac-70dd-436f-be6a-2a7320ba0de9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.6.1
EditorConfig|Edi|0.16.4
go|gol|0.29.0
vscode-go-template|jin|0.2.1
workspace-terminals|jos|0.3.1
mongodb-vscode|mon|0.6.14
vscode-docker|ms-|1.17.0
vsliveshare|ms-|1.0.5065
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
sqltools|mtx|0.23.0
vetur|oct|0.35.0
sqltools-clickhouse-driver|ult|0.2.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by gjsjohnmurray** [comment]
Please update to 1.61.2

/duplicate
