### ISSUE TITLE
Add breakpoints that have the ability to overwrite variables

### ISSUE THREAD

**Issue by joshmakar** [microsoft/vscode#136448]
I find myself setting breakpoints after a variable is set and then, using the debug console, I'll modify the variable to satisfy an `if` statement for testing. I think it would be great if there was a way to overwrite variables via breakpoints, similar to how conditional breakpoints work, but not necessarily stop the code execution.

```php
$result = false;

// Add a breakpoint (or whatever you'd call it) with some var overwrite
// the breakpoint would then set $result = true;
if ($result) {
  // do some other stuff
  // maybe add a generic breakpoint
}
```

This way you could run the code over and over without having to hit the breakpoint, manually change the variable, and then tell the debugger to continue. This would be increasingly more useful as the number of variables you have to overwrite increases.

**Comment by yume-chan** [comment]
Using the JavaScript debugger I can set a conditional breakpoint to execute any code (including modifying a variable) there. Don't know if it works for PHP.

**Comment by weinand** [comment]
Yes, if the debugger you are using supports variable assignments in conditions, then you have the feature already.

**Comment by joshmakar** [comment]
> Using the JavaScript debugger I can set a conditional breakpoint to execute any code (including modifying a variable) there. Don't know if it works for PHP.

I tried modifying a variable in a conditional breakpoint using PHP, but it doesn't seem to work.
![image](https://user-images.githubusercontent.com/9956440/140511595-13918e2f-3486-4aaf-b00a-ef3d0f4dd719.png)

**Comment by weinand** [comment]
@joshmakar I suggest to file an issue against the PHP extension.
