### ISSUE TITLE
probléme avec setting json

### ISSUE THREAD

**Issue by Zorro58** [microsoft/vscode#136458]
Issue Type: <b>Bug</b>

otput false 
kastupdate"check": 1635341759307

domment puis he résoudre le ptroblème d"avance merci  

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 6.2.9200
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A4-6300 APU with Radeon(tm) HD Graphics     (2 x 3700)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.19GB (0.92GB free)|
|Process Argv|C:\\WINDOWS\\system32\\package-lock.json --crash-reporter-id 5b69ad2a-0fc9-4a1b-9e4e-72076c981920|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
tailwindcss-extension-pack|and|1.1.4
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.1
vscode-babel-coloring|dza|0.0.4
gitlens|eam|11.6.1
react-native-react-redux-snippets-for-es6-es7-version-standard|EQu|1.0.3
vscode-angular-html|gha|1.7.0
dna-snippets|jai|0.1.0
vscode-react-pug|kam|0.0.5
vscode-language-pack-fr|MS-|1.61.5
vscode-edge-devtools|ms-|1.4.0
test-adapter-converter|ms-|0.1.4
vscode-react-native|msj|1.7.1
vscode-react-emotion|muh|0.1.0
java|red|1.0.0
js-jsx-snippets|sky|11.0.0
json-template|sto|0.3.1
java-imports-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.14
vscode-maven|vsc|0.34.1
JavaScriptSnippets|xab|1.8.0
es6-string-javascript|zjc|1.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by aeschli** [comment]
Can you please provide detailed steps to reproduce?
