### ISSUE TITLE
activeScopeCSS & scopeLineCSS for bracket pair colorizer

### ISSUE THREAD

**Issue by vuppalaprasanth** [microsoft/vscode#136483]
current BCP2 provides, 
"bracket-pair-colorizer-2.activeScopeCSS": [
    "borderStyle : solid",
    "borderWidth : 1px",
    "borderColor : {color}",
    "opacity: 0.5"
]
"bracket-pair-colorizer-2.scopeLineCSS": [
    "borderStyle : solid",
    "borderWidth : 1px",
    "borderColor : {color}",
    "opacity: 0.5"
]

Some colors are too brighter for the eyes and at times taking the focus out. 
It's better to have these settings so that we can modify accordingly.

**Comment by hediet** [comment]
You can tweak the colors by configuring
```
"workbench.colorCustomizations": {
    "editorBracketPairGuide.activeBackground1": "#ff0000",
    "editorBracketPairGuide.background1": "#ff0000"
}
```

**Comment by vuppalaprasanth** [comment]
Yeah, but I can't change the opacity and thickness of the indent lines.

**Comment by hediet** [comment]
You can give them a transparent color. The thickness cannot be changed currently.

**Comment by vmatyi** [comment]
for the impatient (or in case the upvoting couldn't make it) settings.json :
"workbench.colorCustomizations": {
    "editorBracketPairGuide.activeBackground1": "#ffc51560",
    "editorBracketPairGuide.activeBackground2": "#db63a280",
    "editorBracketPairGuide.activeBackground3": "#199dff90"
}
