### ISSUE TITLE
bracket pair colorization: horizontal guides within bracket pairs on the same line

### ISSUE THREAD

**Issue by jc9108** [microsoft/vscode#136475]
request: show horizontal guides within bracket pairs on the same line, like CoenraadS's Bracket Pair Colorizer 2 does::
![image](https://user-images.githubusercontent.com/31039318/140437301-19e238b5-d520-49cc-b858-6c6ec92d8d77.png)

default::
![image](https://user-images.githubusercontent.com/31039318/140437032-8582746f-35a0-41a0-a8d3-7ae3b4479ce9.png)

**Comment by hediet** [comment]
Should this always happen or just for wrapped lines?

We explicitly don't render horizontal guides when the opening and closing bracket are on the same line.

**Comment by j9108c** [comment]
i'd prefer it to always happen, it is helpful for wrapped lines and for clarity of nested brackets on the same line. if some people dont like it they could turn it off.

**Comment by danFromTelAviv** [comment]
is there an expectation for when this might make it in? 
this seems like a super awesome feature!!

**Comment by hediet** [comment]
This will be the default behavior in next insiders build:

![image](https://user-images.githubusercontent.com/2931520/161212614-7137412f-2e8d-4409-be27-7fa72beb5659.png)
