### ISSUE TITLE
accounts problems

### ISSUE THREAD

**Issue by lummine** [microsoft/vscode#136481]
Issue Type: <b>Bug</b>

accounts isn't oppening

VS Code version: Code - OSS 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-10T18:20:55.439Z)
OS version: Linux x64 5.13.19-2-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 2200)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 2, 1|
|Memory (System)|15.58GB (11.37GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
MagicPython|mag|1.1.1
python|ms-|2021.10.1365161279
jupyter|ms-|2021.9.100
tabnine-vscode|Tab|3.4.33

</details>

**Comment by ArmoryNode** [comment]
Hi, I'm having the same problem and I noticed that you closed this issue. Did you happen to find a solution?

**Comment by lummine** [comment]
It fixed its self?? IDK its working now though

**Comment by ArmoryNode** [comment]
Strange, I tried running it as root in the terminal and that seemed to have fixed it somehow. Thanks for the response though. Really bizarre.
