### ISSUE TITLE
bug in file creation

### ISSUE THREAD

**Issue by spandan455** [microsoft/vscode#136407]
i created file i/o.cpp 
 and it seems like this

![o cpp - LearnC++ - Visual Studio Code 11_3_2021 8_49_37 PM (2)](https://user-images.githubusercontent.com/79681324/140251375-fb1eddfc-e016-4569-8176-42ec81eca361.png)

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

What platform are you working on? Outside VS Code are you able to create a file named `i/o.cpp`?

I don't remember any VS Code platform that allows the `/` character in filenames.

**Comment by JacksonKearl** [comment]
This is as-designed for ease of creating nested files. I am not aware of a way to have a real slash in a path segment, doing so would likely break many areas where we assume slashes denote path segments. 

If you're on MacOS, you can try using a `:` instead, which the macOS finder and various other OS utils will render as a `/`, but internally it is just a `:` (and VS Code displays `:` as well).

**Comment by spandan455** [comment]
I am working on windows 10

**Comment by spandan455** [comment]
Thank you for the Help
