### ISSUE TITLE
Show helpful message in Debug Welcome View if no debuggers are available

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#136450]
While investigating https://github.com/microsoft/vscode-remote-release/issues/5794:

If VS Code's built-in debugger "js-debug" becomes disabled (for whatever reason), the contents of the "Run and Debug" viewlet is not really helpful:

<img width="1056" alt="2021-11-04_17-00-48" src="https://user-images.githubusercontent.com/1898161/140378657-cc7d2b59-d2bb-4fb5-bc4b-1f370111c5f5.png">
 
I suggest that we show the debug Welcome View with a message along the lines of:

> "The built-in JavaScript debugger is disabled.
You can enable it or install another debugger from the Marketplace"

If there are additional installed but disabled debuggers, the message could reflect that.

**Comment by roblourens** [comment]
How about this? 

![image](https://user-images.githubusercontent.com/323878/140424418-5938b60c-c3f1-4067-ace1-14378a0f9930.png)

**Comment by weinand** [comment]
Yep, sounds good - ship it,!

**Comment by joyceerhl** [comment]
Verified: 
![image](https://user-images.githubusercontent.com/30305945/144483664-27a37c5a-3e59-45bf-a749-46c7f61b92e4.png)
