### ISSUE TITLE
OnDidChangeDiagnostics triggers twice on same diagnostics

### ISSUE THREAD

**Issue by Kenozakesy** [microsoft/vscode#136434]
We have written the needed
Issue Type: <b>Bug</b>

We wrote an extension that automatically (via a command in the command window) adjust our code (AL code) to comply with our own guidelines. The extension works fine unless you are trying to adjust a file with over 100 diagnostics. This leads to unexpected and inconsistent result.
This is due to the OndidChangeDiagnostics event triggering twice on the same diagnostics.

Steps to repoduce:

1. Have a file with over 100 errors or warnings (warnings in our case)
2. Change the file multiple times programmatically 
3. at this point the onDidChangeHandler began to trigger twice in the same diagnostics

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (3.54GB free)|
|Process Argv|--crash-reporter-id cf6dae3e-174d-4e72-8ab9-7e58f7892a51|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
al-code-outline|and|3.0.19
vscode-eslint|dba|2.2.2
gitlens|eam|11.6.1
rest-client|hum|0.24.5
al-object-designer|mar|0.2.4
xml-format|mik|1.1.2
al|ms-|8.1.525271
remote-wsl|ms-|0.58.5
nab-al-tools|nab|1.6.0
partial-diff|ryu|1.4.3
markdown-preview-enhanced|shd|0.6.1
vjeko-al-objid|vje|2.1.3
vscode-icons|vsc|11.7.0
crs-al-language-extension|wal|1.4.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593:30376534
vssld246:30386377

```

</details>

 data into your clipboard because it was too large to send. Please paste.

**Comment by jrieken** [comment]
I am not aware of any different behaviour once 100 diagnostics are reached and the behaviour should always be consistent. So, can you please attach an extension snippet that allows me to reproduce this?

**Comment by Kenozakesy** [comment]
The problem is that I cannot attach a piece of code that has 100+ warnings. Because we have another tool that creates these warnings so we can more easily manage our guidelines. And obviously I am not allowed to distribute that. If I give you a file with 100+ AA errors would that be sufficient?

**Comment by jrieken** [comment]
The question if it depends on those exact 100+ errors or if random error do it too? I have the following snippet which adds 1 diagnostics. 

```ts

    const col = vscode.languages.createDiagnosticCollection();

    vscode.languages.onDidChangeDiagnostics(e => {
        console.log('CHANGED_DIAG', e.uris.map(String))
    })

    vscode.commands.registerCommand('extension.helloWorld', async (args) => {

        if (vscode.window.activeTextEditor) {
            col.set([[vscode.window.activeTextEditor.document.uri, [new vscode.Diagnostic(new vscode.Range(0, 0, 1, 0), 'Hello')]]])
        }
    });
```

I also do see the event firing twice which because of the following reason. When the extension adds the diagnostics to the collection it synchronously fires the event. Now the data travels to the renderer which sends it back to all extension host. This triggers the second event (after a short delay). So, there should be no reason that this is any different with 100 diagnostics but it should always be the same.

**Comment by Kenozakesy** [comment]
Thats seems like the issue I am having. So how would one prevent the event from firing twice? or is this not possible?

**Comment by jrieken** [comment]
> So how would one prevent the event from firing twice? or is this not possible?

Not easy, needs some thinking... We don't send the actual diagnostics back and forth but just the data we need to show them. That makes identifying them tricky

**Comment by Kenozakesy** [comment]
Anyway for now I have created a workaround that seems to work fine. So to recap if 100+ diagnostics exist then the onDidChangeDiagnostics event triggers twice, Correct? 
finally I would like to thank you for your quick responses.

**Comment by jrieken** [comment]
> So to recap if 100+ diagnostics exist then the onDidChangeDiagnostics event triggers twice, Correct?

No, even with a single diagnostic you'll see two events

**Comment by jrieken** [comment]
I have drilled into this and there is an easy way to prevent this. There is actually some guard in place that should prevent this but there is a flaw in its logic

**Comment by Kenozakesy** [comment]
Could you put in the chat the prevention method you have found or where I can find it?
