### ISSUE TITLE
Completions items are overlapped in debug console

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#13645]
I've seen this randomly a bunch of times, but if the person investigating can't repro it, I can try to nail it down a little.

![oct-12-2016 22-59-01](https://cloud.githubusercontent.com/assets/323878/19338105/9751abe6-90cf-11e6-9eaf-40b74186b312.gif)

**Comment by roblourens** [comment]
I don't remember ever seeing it in the editor intellisense list.

**Comment by octref** [comment]
I've seen this too today in editor completion. Didn't find consistent repro though.

**Comment by isidorn** [comment]
This is nothing specific in the repl, it is an issue with the rendering of the suggest widget and as @octref points out it also happens in the editor, thus assigning to @joaomoreno

**Comment by joaomoreno** [comment]
It would be kick ass to repro it. I saw it recently in the editor's suggest widget too.

**Comment by joaomoreno** [comment]
Has been fixed since.
