### ISSUE TITLE
Minimap horizontal movement with mouse

### ISSUE THREAD

**Issue by phnetltd** [microsoft/vscode#136444]
When the main window contains long lines then it would be useful to be able to move the minimap horizontally with the mouse as well as vertically.

**Comment by alexdima** [comment]
Currently it is possible to use `shift+mouse wheel` to scroll horizontally. I am not quite sure how the minimap could be dragged horizontally.

**Comment by itcareerswitch** [comment]
... the minimap can be dragged horizontally with the mouse in SublimeText
