### ISSUE TITLE
VSCode expands all folders when opening a workspace

### ISSUE THREAD

**Issue by robinheidrich** [microsoft/vscode#136436]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2 (user setup)
- OS Version: Windows 10

Steps to Reproduce:

1. Open a workspace in VSCode
2. All folders will be expanded in the explorer (not the subfolders, only the main folders)

---

Previously, VSCode expanded only the folders from which files were open. Now all folders are expanded every time, even if no file of them is open.

Is this intentional or a bug?

**Comment by gjsjohnmurray** [comment]
/duplicate and will be fixed in 1.62, which may ship later today.
