### ISSUE TITLE
Online VS Code squished image

### ISSUE THREAD

**Issue by Haltarys** [microsoft/vscode#136467]
The grey VS code logo as a background image is squished.

## REPRODUCTION STEPS

Go to [vscode.dev](https://vscode.dev) and press Escape to see the squished image.

Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
Embedder: vscode.dev

**Comment by joaomoreno** [comment]
Cam you share a screenshot?

**Comment by Haltarys** [comment]
![image](https://user-images.githubusercontent.com/45515869/140631039-d3295efd-0447-48cc-84b7-a624402ffc19.png)

**Comment by Haltarys** [comment]
Firefox 94.0, it's all in the first message above.

**Comment by joaomoreno** [comment]
Can't reproduce.

Can you disable all browser extensions?

**Comment by filiptronicek** [comment]
Happening to me as well [Brave browser] but running in a private window with all extensions disabled seems to fix the issue.

**Comment by Haltarys** [comment]
Same. I tried on another PC with a clean Firefox and it works fine. I must have tweaked something in the settings.
