### ISSUE TITLE
`typescript.suggest.completeFunctionCalls` should work with arrow functions

### ISSUE THREAD

**Issue by zardoy** [microsoft/vscode#136414]
Issue Type: <b>Bug</b>

1. Code:
```ts
function func(file: string) {}
const funcArr = (file: string) => {}

const obj = {
    func(file: string) {},
    funcArr: (file: string) => {}
}
```

2. Setting: `"typescript.suggest.completeFunctionCalls": true`

### Actual result

Works only with `func` and `obj.func` and never with arrow

### Expected

Works with any function / method here  

I suppose Function Declaration and Arrow Functions should have the same rights. Isn't it looking at type signature to make function completion?

VS Code version: Code - Insiders 1.62.0-insider (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T13:19:17.847Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-typescript-next|ms-|4.6.20211103

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30382699
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsaa593:30376534

```

</details>

**Comment by zardoy** [comment]
Probably a duplicate of https://github.com/microsoft/vscode/issues/60901.
So this is still an issue on TypeScript side? I just saw that linked issue was closed, however it still doesn't work on nightly.

**Comment by OliverJAsh** [comment]
Is there a reason for this limitation or is it a bug?

**Comment by zardoy** [comment]
Firstly I think it's a limitation from TypeScript repo, since it should say that something like `const a = () => {}` actually has method kind, not variable.

Secondly from my POV TypeScript support in VSCode is hardcoded in too many places. For example, [filtering suggestion](https://github.com/microsoft/vscode/blob/main/extensions/typescript-language-features/src/languageFeatures/completions.ts#L94) only for method completions. You can open [outline](https://code.visualstudio.com/docs/getstarted/userinterface#_outline-view) and see that these two declarations have different TS kinds:

```ts
const a = () => {} // variable (even it is actually a method)
function b() {} // method (purple box in UI)
```

Anyway, I don't think parsing documentation is a good decision, this work should be done at the server side.
So if you really need solution for this, you can use TypeScript Service Plugin that will use `type.getCallSignatures` for the just applied suggestion.

And also as I understand @mjbvz forgot to reopen #60901, otherwise I might missing something.

---

Good news is that [relatively new](https://code.visualstudio.com/updates/v1_68#_object-method-snippets) *object literal method snippets* supports signature completions for arrow functions inside of objects.

**Comment by mjbvz** [comment]
Moving to https://github.com/microsoft/TypeScript/issues/51758
