### ISSUE TITLE
About Chinese Path

### ISSUE THREAD

**Issue by ijrys** [Microsoft/vscode#13642]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: ms-vscode.cpptools-0.9.2, ms-vscode.csharp-1.4.1, tushortz.java-snippets-0.0.1

Steps to Reproduce:

When I open VSCode at a path with chinese,shell can't work and exit code is 1;

OS:Windows 10 x64
![q](https://cloud.githubusercontent.com/assets/15842103/19335964/07aad7e0-913a-11e6-8adf-765b2d1eb117.GIF)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/7727
