### ISSUE TITLE
save a modified file, the code Shaking up and down

### ISSUE THREAD

**Issue by xixilifans** [microsoft/vscode#136404]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1
- OS Version: windows 11
- language:Golang

Steps to Reproduce:

1.after modified a file, i try to save(ctrl+s) the file, the code will Shaking up and down
2.

**Comment by xixilifans** [comment]
Did not do some compiler job

**Comment by gjsjohnmurray** [comment]
Please update to the current release 1.61.2 and retest.

**Comment by xixilifans** [comment]
solved by update 1.61.2
thanks
