### ISSUE TITLE
Colorization of collapsed code in interactive window doesn't match expanded

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#136468]
Collapsed code:

![image](https://user-images.githubusercontent.com/19672699/139910071-2c7e74de-622c-4b8f-a6a7-cbf1573dde69.png)

Expanded code:

![image](https://user-images.githubusercontent.com/19672699/139910131-e440ed72-895c-4b76-91f1-cc6047817ddc.png)

Need to figure out how to get the collapsed code to make the same token requests.

**Comment by rebornix** [comment]
@rchiodo does the final colorization contain semantic syntax highlighting?

**Comment by rchiodo** [comment]
Not sure what you mean by final. The expanded code has semantic tokens enabled. I can see the request being made when the expansion happens.

**Comment by rebornix** [comment]
We use `tokenizeToStringSync` to tokenize the content, which won't take semantic syntax highlighting into account (which is async).

**Comment by TylerLeonhardt** [comment]
<img width="198" alt="image" src="https://user-images.githubusercontent.com/2644648/214937043-dd735400-738e-45c4-a715-4bd20fab6222.png">

though mine didn't include the comment like Rich's did. Expected @rebornix?

**Comment by rebornix** [comment]
@TylerLeonhardt that should be fine and irrelevant.
