### ISSUE TITLE
the window has crashed (reason: 'crashed', code: '132')

### ISSUE THREAD

**Issue by cangfeng110** [microsoft/vscode#136479]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: June 2021 (version 1.58)
- OS Version: Ubuntu16.04

Steps to Reproduce:

1.
2.

**Comment by cangfeng110** [comment]
when use code to open the gui, it will display 
![image](https://user-images.githubusercontent.com/26113709/140494107-891e5a42-3c43-4fea-9478-13ddb2664226.png)

**Comment by deepak1556** [comment]
Can you update to latest stable `1.62` and check if the crash happens ?

**Comment by cangfeng110** [comment]
the problem has solved，it ’s due to two memory is not compatibility发自我的华为手机-------- 原始邮件 --------发件人： Robo ***@***.***>日期： 2021年11月5日周五 晚上7:28收件人： microsoft/vscode ***@***.***>抄送： cangfeng110 ***@***.***>, Author ***@***.***>主    题： Re: [microsoft/vscode] the window has crashed (reason: 'crashed', code: '132') (Issue #136479)
Can you update to latest stable 1.62 and check if the crash happens ?
