### ISSUE TITLE
"invalid regular expression" after enabling indexing

### ISSUE THREAD

**Issue by imba-tjd** [microsoft/vscode#136406]
This issue happens after enabling indexing.

Edgium:

![image](https://user-images.githubusercontent.com/24759802/140250103-0f83d24f-220d-4bc8-85cc-7ee01dd8abb9.png)

FF:

![image](https://user-images.githubusercontent.com/24759802/140250128-c1ed75ea-9bd9-429b-8584-0e91ae63023b.png)

Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36 Edg/95.0.1020.40
Embedder: github.dev

**Comment by JacksonKearl** [comment]
Thanks, this should be fixed in the next release.
