### ISSUE TITLE
Hover description is not showing the correct description. 

### ISSUE THREAD

**Issue by shizhao1100** [Microsoft/vscode#13647]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: donjayamanne.python-0.4.1

Steps to Reproduce:

1.
![image](https://cloud.githubusercontent.com/assets/14040327/19339111/ebcbe7e8-9153-11e6-9b6f-be216be1f35d.png)

The real hint is 

![image](https://cloud.githubusercontent.com/assets/14040327/19339198/9571a5bc-9154-11e6-9ab2-05f9434a0f8a.png)

maybe it is a bug maybe not

I saw and i submit

**Comment by waderyan** [comment]
@shizhao1100 thank you for opening this issue. I am having a hard time understanding what you are seeing? 

Are you pointing out that there should be commas (`,`) instead of semi colons (`;`)?

**Comment by waderyan** [comment]
Closing until more info is obtained.
