### ISSUE TITLE
Unable to highlight text/code using a pen

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vscode#136465]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.0
- OS Version: Windows 10 21H1

Steps to Reproduce:

1. Try to select any code with your pen while pushing the corresponding key on your pen
2. Note that only the right click menu pops up, but no text is highlighted

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/47770
