### ISSUE TITLE
Limit max number of terminal input

### ISSUE THREAD

**Issue by molly-w** [microsoft/vscode#136405]
- VS Code Version: 1.61.2
- OS Version: Windows Version 2004 (Os Build 19041.1288)

Steps to Reproduce:

1. Code:
```
import java.util.Scanner;
public class Demo{
    public static void main(String[] args) {
        Scanner sc=new Scanner(System.in);
        int N = sc.nextInt();
        int[] arr = new int[N];     
  
        for(int i=0; i<N; i++){
          arr[i] = sc.nextInt();
        }
      
        for(int elem: arr){
          System.out.println(elem+" "); 
    }
   
}
}
```
2. test_input: https://drive.google.com/file/d/1ayXET85FsCjQUJa6TDSVd7MA0OangykB/view
3. run java code, copy all the numbers shown in the above file but only part of them can be pasted to terminal

So i want to know what's the maximum input number in terminal. Is there any settings or option to edit its limitation?

Original Post: https://stackoverflow.com/questions/69826575/max-limit-on-number-of-input-in-vs-code-java

**Comment by meganrogge** [comment]
when I paste your example input into the terminal, it succeeds (although takes quite awhile) - what you might be seeing is the output (pasted text) trimmed relative to what you're expecting because of the maximum terminal scrollback which can be configured with `terminal.integrated.scrollback`
