### ISSUE TITLE
Add support for dynamic view type - Allow to switch between `tree` and `webview` dynamically

### ISSUE THREAD

**Issue by softmarshmallow** [microsoft/vscode#136484]
Currently displaying a webview content on a activity bar registered view is allowed by 
```json
{
	"id": "grida-explorer-components-web",
	"name": "Components",
	"type": "webview",
	"contextualTitle": "Components"
},
```

And

```ts
  context.subscriptions.push(
    vscode.window.registerWebviewViewProvider(
      "grida-explorer-components-web",
      new MyWebviewProvider()
    )
  );
```

What i'de like to do is providing the ui as native tree view as default, and when user commands "switch to grid view", I'de like to show a grid view with image previews as webview.

This is possible with scripts, but won't get affected (`registerWebviewViewProvider` on non explicitly "webview" set view will be ignored)

**Comment by sandy081** [comment]
Cant this be possible by your extension by

- having a context key say `showGridView` which is false by default
- register tree and grid view by setting above context key in `when` condition
- have a command that toggles this context key - which toggles the views?

**Comment by softmarshmallow** [comment]
@sandy081  For webview, it should be pre-defined statically `"type": "webview"` in package.json

Sadly Can't do somehow by using `when` condition - AFAIK
