### ISSUE TITLE
php syntax checker broken with annonymous function

### ISSUE THREAD

**Issue by creanovo-admin** [microsoft/vscode#136431]
Issue Type: <b>Bug</b>

The syntax checker for php reports an error when there is none.

<img src="https://imgur.com/0iBpBCM.png"><img src="https://imgur.com/vc5Q6vv.png">

Code to test:

```php
<?php

(function() {
    echo "but it works!";
})();
```

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.55GB free)|
|Process Argv|-n --crash-reporter-id 7c4edd94-e8d5-4fdd-85fa-eebfee1b63c2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-de|MS-|1.61.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by roblourens** [comment]
Works for me, what version of PHP?

**Comment by creanovo-admin** [comment]
I don't remember that I ever changed the php version in visual studio code so whatever version is default. Where is the setting for that?

The error is consistent and it doesn't look like it's because of going out of sync.
<img src="https://imgur.com/JvlMg0u.gif">

**Comment by roblourens** [comment]
It uses whatever php version you have installed, so what version is that?

Do you see weird errors for other php code samples?

**Comment by creanovo-admin** [comment]
> 
> Do you see weird errors for other php code samples?

I don't see any other weird errors.

> 
> 
> It uses whatever php version you have installed, so what version is that?

Oh wow okay. I'm only developing on our dev server not locally. I do have xampp with php 7.2.11 installed.

Can I change it to ignore the locally installed php?
