### ISSUE TITLE
Find widget is covered by explorer

### ISSUE THREAD

**Issue by SArnesenFara** [microsoft/vscode#136497]
Issue Type: <b>Bug</b>

Steps to reproduce

1. Open a file in vscode and have the explorer closed.
2. Open the find widget using ctrl+f
3. Double tap the leftmost edge to expand the find widget size to max
4. Press the explorer button in the sidebar

Actual result

The find widget is not resized to fit the new editor window. Parts of the find widget is hidden behind the explorer.

Expected result

The find widget should be resized to fit the editor window size when explorer is opened.

Additional observation

The find widget is in fact resized when you close and reopen the explorer. The issue only occurs on the first explorer opening event.

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.83GB (2.11GB free)|
|Process Argv|--crash-reporter-id 74b0e073-05ef-4df3-a130-f80268cd5967|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.4.0
vscode-json|and|1.5.0
markdown-checkbox|bie|0.3.2
vscode-markdownlint|Dav|0.45.0
docs-markdown|doc|0.2.100
xml|Dot|2.5.1
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
vscode-drawio|hed|1.6.2
l13-diff|L13|1.0.3
markdown-shortcuts|mdi|0.12.0
git-graph|mhu|1.30.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.0
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-wsl|ms-|0.58.5
cpptools|ms-|1.7.1
sublime-keybindings|ms-|4.0.10
vscode-markdown-notebook|ms-|0.0.26
vscode-commons|red|0.0.6
vscode-yaml|red|1.1.0
selectline-statusbar|tom|0.0.2
sort-lines|Tyr|1.9.0
vscode-counter|uct|2.3.0
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.7.0
markdown-pdf|yza|1.4.4

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246cf:30386378

```

</details>
![sad_find_widget](https://user-images.githubusercontent.com/70317264/140483067-cc3b9879-99cf-4712-bc2d-68046b3d491f.png)

**Comment by JacksonKearl** [comment]
I am not able to reproduce this..

![recording](https://user-images.githubusercontent.com/8586769/140841536-085a8a8e-95ef-4b20-92c8-620c32cb0c50.gif)

\gifPlease

**Comment by SArnesenFara** [comment]
> I am not able to reproduce this..
> 
> ![recording](https://user-images.githubusercontent.com/8586769/140841536-085a8a8e-95ef-4b20-92c8-620c32cb0c50.gif)
> 
> \gifPlease

Well, turns out I'm struggling to reproduce myself now 😅  Maybe just a once in a life time glitch.. I guess we just close this. I can reopen it if I'm able to encounter this again somehow.
