### ISSUE TITLE
ts(2339) errors are occurring in JavaScript files

### ISSUE THREAD

**Issue by thebinarysearchtree** [microsoft/vscode#136417]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2
- OS Version: MacOS Monterey

Create a new JavaScript file with this code:

```javascript
import { useState, useRef, useEffect } from 'react';

function BalanceHeading() {
  const [balance, setBalance] = useState({ amount: 10 });
  const prevBalance = usePrevious(balance);
  useEffect(() => {
    setBalance({ amount: 100 });
  }, []);
  return <h1>Now: {balance.amount}, before: {prevBalance ? prevBalance.amount : 0}</h1>;
}

function usePrevious(value) {
  const ref = useRef();
  useEffect(() => {
    ref.current = value;
  });
  return ref.current;
}

export default BalanceHeading;

```

The ```usePrevious``` hook is copied directly from the React website. The whole thing is just a slightly modified version of the Counter example at https://reactjs.org/docs/hooks-faq.html. Notice that TypeScript is reporting error ts(2339) on ```prevBalance.amount``` because it claims that ```usePrevious``` only ever returns ```undefined```, when in reality, it does not and the code works perfectly fine. The TypeScript team said this is "working as intended", so therefore, I am submitting this bug here.

**Comment by mjbvz** [comment]
Typescript powers VS Code's JS intellisense so if the team already weighed in, their response is correct. If you disagree, please follow up with typescript again
