### ISSUE TITLE
gulpfile.ts support

### ISSUE THREAD

**Issue by aaroncowie** [microsoft/vscode#136418]
Gulp supports typescript via ts-node (https://gulpjs.com/docs/en/getting-started/javascript-and-gulpfiles#transpilation) however vscode only seems to detect tasks within gulpfiles with js file extensions.

This has been discussed previously in https://github.com/microsoft/vscode/issues/11482 but was closed as inactive.

At a glance, it seems like the .ts extension just needs be added to the hasGulpfile function
https://github.com/microsoft/vscode/blob/main/extensions/gulp/src/main.ts#L177

This function was added recently in https://github.com/microsoft/vscode/pull/113505

**Comment by aaroncowie** [comment]
Hi, apologies I'm not too familiar with the process for verifying.

Do I need to set up a build environment locally to build from source, or is there somewhere that I can get a prebuilt binary?

I just ask because I'm running on windows so configuring a build environment that can handle native dependencies can be a little challenging.

By the way, many thanks for addressing this so quickly!

**Comment by alexr00** [comment]
@aaroncowie thanks for the reply and your interest in helping to verify! The fix is now available in out insiders build and the bot has added instructions for how to verify above.

**Comment by aaroncowie** [comment]
/verified

I can confirm that it's working perfectly now, thanks so much!

I can also confirm that it works for a directory named "gulpfile.ts" with an index.ts file below it as per https://gulpjs.com/docs/en/getting-started/javascript-and-gulpfiles#splitting-a-gulpfile

**Comment by alexr00** [comment]
@aaroncowie thank you for verifying!
