### ISSUE TITLE
Notebook file stuck open on vscode.dev

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#136464]
- VS Code Version: 1.62.0
- OS Version: Windows 11 Enterprise
Version	21H2
Installed on	‎10/‎11/‎2021
OS build	22000.258
Experience	Windows Feature Experience Pack 1000.22000.258.0

While debugging Live Share notebooks in vscode.dev, at some point a notebook file got "stuck" open. I am not sure what the exact repro steps were, but it was from opening a notebook files. It's been stuck for at least a week. 

![stuck-nb-file](https://user-images.githubusercontent.com/22576531/140405751-102b2edf-e8a4-43da-a2c1-8a503a3de40c.gif)

**Comment by jrieken** [comment]
When this happens, a start to drill into things is the dev tools log and network traces as well as the VS Code log
