### ISSUE TITLE
in 1.6 any path Extensions dont work

### ISSUE THREAD

**Issue by minjunlan** [Microsoft/vscode#13644]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: christian-kohler.path-intellisense-1.1.0

Steps to Reproduce:

1. note any any any path Extensions dont work , it not one  path Extensions 
2.christian-kohler.path-intellisense-1.1.0 work in 1.5 ,but work in 1.6

**Comment by kumarharsh** [comment]
@minjunlan there's been an update to the path-intellisense extension. Update and don't forget to reload the vscode instance. See here for updates: https://github.com/ChristianKohler/PathIntellisense/issues/30

**Comment by minjunlan** [comment]
I use the newest extension  christian-kohler.path-intellisense-1.1.0 ,reboot my pc , **it still dont work!!!**

**Comment by djx339** [comment]
I have the same issue. Path Intellisense and HTML CSS Class Completion won't work.

**Comment by isidorn** [comment]
This seems to be an issue with an extension. Please file it here https://github.com/ChristianKohler/PathIntellisense/issues/30

@ChristianKohler did we break something on the vscode side in 1.6?

**Comment by ChristianKohler** [comment]
@isidorn I don't know. Could not reproduce the bug yet. Could anyone of you? It seems that for many people it works after a restart.

**Comment by minjunlan** [comment]
it work good in vscode 1.6.1, in 1.6 like christian-kohler.path-intellisense or ionutvmi.path-autocomplete can't work. it is't Extensions bug, in 1.6.1 that Extensions work good

**Comment by ChristianKohler** [comment]
@isidorn Could you have a look at https://github.com/ChristianKohler/PathIntellisense/issues/30? 
#yangg posted the error message. Do you have an idea what the issue could be?

**Comment by isidorn** [comment]
@alexandrudima or @aeschli would now better to comment on that endles loop grammar error

**Comment by alexandrudima** [comment]
The endless loop grammar error does not have anything to do with intellisense, it is detected and logged when a TextMate grammar is incorrect. Please find the body of text that reproduces this message and file a spearate issue against VSCode or against the repo that contains the truth for the grammar that VSCode uses for the respective language.
