### ISSUE TITLE
Make it easier to create new files/folders from the explorer when many files are present

### ISSUE THREAD

**Issue by innerlee** [Microsoft/vscode#13641]
- VSCode Version: 1.6
- OS Version: ubuntu

Steps to Reproduce:

1. create a lot of folders under a project folder (folders only, no files at project root folder).
2. then it's hard to add new file to project folder because you cannot get any empty space for this. see figure below for what I mean.

![cannot new file](https://cloud.githubusercontent.com/assets/9464825/19335658/952c7b1c-9137-11e6-8795-82c66607d677.png)

**Comment by kumarharsh** [comment]
+1 this is irritating when a lot of my folders (like node_modules) are open, and I have to scroll *a LOT* to just find a file at the root level to click/focus, just so that I can create a new file.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1043
