### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Nathan0995** [microsoft/vscode#136453]
Issue Type: <b>Feature Request</b>

VS Code terminal is asking a permission for something that I dunno when I want to run the compiler. I am struggling with running the compiler.
I'm using latest chrome os intel cpu based and I have enabled linux features.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:58:13.605Z)
OS version: Linux x64 5.4.155-17098-gfcb18339ac69
Restricted Mode: No

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" terminal
