### ISSUE TITLE
Rename cancellation 

### ISSUE THREAD

**Issue by jihunleekr** [microsoft/vscode#136428]
Issue Type: <b>Bug</b>

if I copy and paste a directory  and try to rename it immediately(in 150ms), it gets canceled. I think it is a process of updating the screen as the directory is copied. 

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:58:13.605Z)
OS version: Linux x64 4.15.0-161-generic
Restricted Mode: No

**Comment by JacksonKearl** [comment]
Duplicate of #112293
