### ISSUE TITLE
Aspect Ratio syntax highlighting broken

### ISSUE THREAD

**Issue by mikeybinnswebdesign** [microsoft/vscode#136435]
Issue Type: <b>Bug</b>

1. Open VS Code with extensions disabled.
2. Open a new file, and choose CSS as the language
3. Paste in the following:
```css
.test {
  color: #fff;
  aspect-ratio: 1;
  aspect-ratio: 1 / 1;
}
```
What should happen:
the aspect-ratio property text should be the same colour as the color property

What actually happens:
the aspect-ratio text is a different color

Possible explaination:
The hover information for aspect-ratio says it is an experimental property, but this is not the case any more. It's now fully implemented for all modern browsers.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (6.81GB free)|
|Process Argv|--crash-reporter-id 0bb0fd92-3111-45fe-9222-08f88c4f9565|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by alexr00** [comment]
Thanks for clear repro steps! I've moved this issue to the repository that we pull our css syntax highlighting grammar from: https://github.com/atom/language-css/issues/190
