### ISSUE TITLE
Crash on opening large files with bracket pair colorization

### ISSUE THREAD

**Issue by kasvtv** [microsoft/vscode#136470]
So my bracket pair colorizer plugin was causing VScode to become extremely slow when viewing a large file. I discovered this feature has been built into the editor now, so I migrated away from it. However, now, when opening this same file, the editor actually completely freezes.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Enable bracket pair colorization:
```json
{
  "editor.bracketPairColorization.enabled": true,
  "editor.guides.bracketPairs": "active",
  "editor.guides.bracketPairsHorizontal": "active",
  "workbench.colorCustomizations": {
    "editorBracketPairGuide.activeBackground1": "#0064c899",
    "editorBracketPairGuide.activeBackground2": "#00a00099",
    "editorBracketPairGuide.activeBackground3": "#00eaff99",
    "editorBracketPairGuide.activeBackground4": "#e0000099",
    "editorBracketPairGuide.activeBackground5": "#ee00ff99",
    "editorBracketPairGuide.activeBackground6": "#eeee0099",
    "editorBracketHighlight.foreground1": "#0064c8dd",
    "editorBracketHighlight.foreground2": "#00a000dd",
    "editorBracketHighlight.foreground3": "#00eaffdd",
    "editorBracketHighlight.foreground4": "#e00000dd",
    "editorBracketHighlight.foreground5": "#ee00ffdd",
    "editorBracketHighlight.foreground6": "#eeee00dd"
  }
}
```
2. Open a file that's >10MB and >100k lines 
3. Editor becomes unresponsive

**Comment by hediet** [comment]
I'm sorry. Due to an oversight while refactoring, opening a very large document causes an endless loop when bracket pair colorization is enabled.
This is a regression, as it used to work in 1.61.

**Comment by alexr00** [comment]
Looks like this has made it into release/1.62.
