### ISSUE TITLE
Editors - pathsToEditors should ignore folders

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#136491]
There is a scenario in which `vscode.dev` tries to open an editor with a path that points to a folder instead of a file. This ends up in an error message. Instead of showing an error `pathsToEditors()` should ignore the path if it points to a folder. This has already been fixed in `main` with e31a18ea8c6cf53e205e481c98f290e6d8c20460 but I would like to port the change to the next recovery release.

**Comment by lszomoru** [comment]
This has been verified with Insiders + insiders.vscode.dev.

**Comment by eamodio** [comment]
@lszomoru While this did show an error notification, it also did select the folder in the explorer view, which was valuable -- imo, we'd ideally suppress the error message instead of ignoring to the folder.

**Comment by lszomoru** [comment]
@eamodio, I have filed https://github.com/microsoft/vscode/issues/137301 to track the regression.
