### ISSUE TITLE
Support Microsoft Edge Immersive Reader  links

### ISSUE THREAD

**Issue by sahil48** [microsoft/vscode#136455]
Microsoft Edge Reader View has an option to use an immersive reader to view articles. The URLs start with read instead of https. Please support following read links with ctrl-click and opening these links in Edge.

Reader Link (no underline)
![image](https://user-images.githubusercontent.com/6100774/140388032-18c8fa7a-f52f-4145-8901-140a99daa82d.png)

http url (has underline and option to follow link)
![image](https://user-images.githubusercontent.com/6100774/140388567-8952d790-cb23-4305-a753-1f52baee0881.png)

**Comment by joyceerhl** [comment]
This can be implemented by a link provider extension: https://code.visualstudio.com/api/references/vscode-api#DocumentLinkProvider

**Comment by mjbvz** [comment]
Yes I agree this should likely be an extension. Our built-in link recognizer is intentionally conservative as highlighting something that is not a link can be pretty annoying
