### ISSUE TITLE
Wrong syntax highlighting after updating VS Code to latest version

### ISSUE THREAD

**Issue by lakshits11** [microsoft/vscode#136559]
After updating VS code to latest version, i am facing wrong syntax highlighting issues.
I am using Babel Javascript extension and has set semantic highlighting to off. 
But using the same set of extensions and same settings in VS Code Insiders, I don't face the issue.

here for example see:

In VS Code:

![code_syntax](https://user-images.githubusercontent.com/54276661/140596446-4e0c8e6d-bdd7-411e-99d2-23b3156bf128.PNG)

In VS Code Insiders:

![insiders_syntax](https://user-images.githubusercontent.com/54276661/140596462-7c89a01f-1d22-46db-9d00-04254b0b4ebf.PNG)

Why I think it is a VS Code issue is that it happens only after updating VS Code and also I can't reproduce the issue in Insiders. And also this extension is same as it is and it works in Insiders build and not in VS Code after updating so I do't think it is a extension issue.

To reproduce the issue, install the  [Babel JS Extension](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel) and add following to your settings.json

`"editor.semanticHighlighting.enabled": false,`

and also please leave `editor.semanticTokenColorCustomizations` to default.

Does this issue occur when all extensions are disabled?: No

- VS Code Version:1.62.0
- OS Version: Can reproduce it on every os. I use dual boot Manjaro Arch and Win 10. Both have the issue after updating.

Please look into it. Thank You!

And also I wanted to ask that do I need this extension anymore since VS Code hass been improving greatly so what are the cases I need this extension for best syntax highlighting which VS Code itself cannot give to me.

**Comment by lakshits11** [comment]
Edit: Now I am also facing same issue in Insiders build. I dont know why but it was working fine this morning almost 2 hrs ago and now I didnt change a single setting and I am having problem in insiders build also.

**Comment by lakshits11** [comment]
Ok that I know how to inspect editor styles but can we change the styles by self like it treats it as string, so cant we manually change it? And also please answer the second question that is Babel JS extension necessary in your personal opinion like do you know cases where vscode inbuilt syntax highlighting didn't worked correctly but Babel JS extension made it correct? 

Thank You.

**Comment by aeschli** [comment]
I don't know if/where the Babel JS extension adds any benefit as I'm not a Babel user myself. (I'm using Typescript)

Sorry, didn't get your question. The scopes are generated by a grammar and users can't customize that expect by installing an extension that provides a different grammar.
Colorization of the scopes is done by themes. Users can tune themes as [described here](https://code.visualstudio.com/docs/getstarted/themes#_editor-syntax-highlighting).
