### ISSUE TITLE
Feature request: Stop execution of code

### ISSUE THREAD

**Issue by dkgaraujo** [microsoft/vscode#136570]
It would be very helpful to have a "stop" button with an associated keyboard shortcut that stops code execution. For example, when currently running a python code there is no way to stop it other than killing the process or Cmd+Q-exiting VS Code. I assume the same happens with other languages.

**Comment by weinand** [comment]
@dkgaraujo how are you running "a Python code"?

**Comment by dkgaraujo** [comment]
Hi @weinand - thanks for your inquiry and further info. I was running through the command line; more specifically, it was a *.py file that I ran through "control-option-N" (the output was in a separate "Code" session, not in the terminal session in the window below). Unfortunately "Control-C" didn't pause it.

**Comment by weinand** [comment]
I'm not aware of a "control-option-N" command for running Python programs. 
Are you using a (Jupyter-) Notebook? A screenshot would be helpful.
Thanks.

**Comment by dkgaraujo** [comment]
Sorry, only now I realised - this control+option+N option to run the code is from the extension "CodeRunner". It creates a "play" button on the top right where users can run the code by clicking it, or by pressing the key command I mentioned. But regardless of how the code runs, there is no button in VS Code native that will stop the code. 

(Incidentally, I actually tried to record the screen with this issue but a pop-up saying it needed to be updated - when it had just been updated - showed up and did not go away no matter how many times I clicked 'OK'. If you think it's worth it I can file a new issue and post that video.)

**Comment by weinand** [comment]
@dkgaraujo since the "Coderunner" extension provides the "play" button, only that extension could provide the corresponding "stop" button. VS Code knows nothing about the processes "Coderunner" is launching.

**Comment by dkgaraujo** [comment]
Many thanks @weinand - makes complete sense. I thought a “stop button” should be part of VS Code by default but then, you are right - given the play button comes from an extension, I should discuss it with them. Thanks for your time!

**Comment by weinand** [comment]
@dkgaraujo please note that the Python extension already provides a "Run" and "Debug" button in the same location as the CodeRunner extension:

<img width="857" alt="2021-11-10_09-21-41" src="https://user-images.githubusercontent.com/1898161/141076391-bec99100-e2f3-4b32-8169-30a0e66bbdea.png">

**Comment by dkgaraujo** [comment]
That's excellent, @weinand, thanks. That's exactly what I was looking for. Thanks for all your time!
