### ISSUE TITLE
nbformat 3 notebooks show as empty

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#136544]
## Repro 

1. Open a nbformat 3 notebook in VS Code, such as https://raw.githubusercontent.com/waltherg/notebooks/master/2013-12-03-Crank_Nicolson.ipynb

## Bug
A blank notebook is shown

![Screen Shot 2021-11-05 at 1 29 46 PM](https://user-images.githubusercontent.com/12821956/140574588-5b480a77-f621-4d2d-a48f-452364f32a89.png)

We should show an error message if this old format is unsupported or, even better, find a way to render these

**Comment by roblourens** [comment]
Now if you try to open a v3 notebook, you will see this: 
![image](https://user-images.githubusercontent.com/323878/140576755-ef3ad353-882b-4b72-8784-c7d5783ab53d.png)

**Comment by rchiodo** [comment]
That commit seems weird? 

Wouldn't it be less than 4?
```
		if (json.nbformat && json.nbformat < 5) {
			throw new Error('Only Jupyter notebooks version 4+ are supported');
		}
```

**Comment by roblourens** [comment]
Dangit. Did that for testing. Thanks for keeping me from breaking all notebooks
