### ISSUE TITLE
使用remote -ssh连接wsl时，json文件警告

### ISSUE THREAD

**Issue by cmw-big** [microsoft/vscode#136598]
Issue Type: <b>Bug</b>

1、使用ssh连接wsl2
2、打开package.json文件
3、呈现问题警告信息为：
[{
	"resource": "/mnt/c/Users/cmw10/Desktop/codes/jest-learn/package.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "768",
	"severity": 4,
	"message": "Problems loading reference 'https://json.schemastore.org/package': Unable to load schema from 'https://json.schemastore.org/package': Failed to establish a socket connection to proxies: [\"PROXY 127.0.0.1:7890\"].",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}]

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (22.70GB free)|
|Process Argv|--crash-reporter-id a5919c04-2bde-446f-bd0c-0ca0aca65faa|
|Screen Reader|no|
|VM|36%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor (16 x 3800)|
|Memory (System)|15.59GB (14.59GB free)|
|VM|0%|
</details><details><summary>Extensions (97)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
color-info|bie|0.7.0
vscode-weapp-api|cod|0.1.8
es7-react-js-snippets|dsz|3.1.1
Vue2|duc|0.1.3
LogFileHighlighter|emi|2.13.0
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
vscode-react-typescript|inf|1.3.1
vscode-language-pack-zh-hans|MS-|1.62.2
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.66.0
remote-wsl|ms-|0.58.5
material-icon-theme|PKi|4.10.0
js-jsx-snippets|sky|11.0.0
highlight-matching-tag|vin|0.10.1
vscode-icons|vsc|11.7.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.13.2
html-snippets|abu|0.2.1
eggjs|ati|0.3.1
color-info|bie|0.7.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.2
regex|chr|0.4.0
vscode-weapp-api|cod|0.1.8
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
es7-react-js-snippets|dsz|3.1.1
Vue2|duc|0.1.3
gitlens|eam|11.6.1
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.23
LogFileHighlighter|emi|2.13.0
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.0.0
mithril-emmet|Fal|0.7.6
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
code-runner|for|0.11.6
copilot|Git|1.7.3689
todo-tree|Gru|0.0.214
beautify|Hoo|1.5.0
vscode-power-mode|hoo|2.2.0
rest-client|hum|0.24.5
vscode-react-typescript|inf|1.3.1
comment-translate|int|1.5.0
path-autocomplete|ion|1.17.1
webpack|jer|2.2.0
volar|joh|0.28.10
vscode-typescript-vue-plugin|joh|0.28.10
vscode-gutter-preview|kis|0.29.0
vscode-leetcode|Lee|0.18.0
template-string-converter|meg|0.5.4
vscode-fileheader|mik|0.0.2
vscode-filesize|mkx|3.1.0
vscode-autoprefixer|mrm|3.0.1
vscode-language-pack-zh-hans|MS-|1.62.2
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.0
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
live-server|ms-|0.2.9
vscode-typescript-next|ms-|4.6.20211106
color-highlight|nau|2.5.0
vetur|oct|0.35.0
material-icon-theme|PKi|4.10.0
vscode-css-peek|pra|4.2.0
view-in-browser|qin|0.0.5
minapp-vscode|qiu|2.4.1
LiveServer|rit|5.6.1
postcode|roh|1.3.9
any-rule|rus|0.3.12
markdown-preview-enhanced|shd|0.6.1
js-jsx-snippets|sky|11.0.0
autoimport|ste|1.5.4
code-spell-checker|str|2.0.12
sass-indented|syl|1.8.18
pdf|tom|1.1.0
codelf|unb|11.7.0
highlight-matching-tag|vin|0.10.1
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.7.0
vscode-js-console-utils|wht|0.7.0
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.13.2
html-css-class-completion|Zig|1.20.0

(20 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by CodeCrazy-ywt** [comment]
1. Connect to wsl2 using ssh.
2. Open package.json.
3. An error will show up:
```
[{
"resource": "/mnt/c/Users/cmw10/Desktop/codes/jest-learn/package.json",
"owner": "generated_diagnostic_collection_name#0",
"code": "768",
"severity": 4,
"message": "Problems loading reference 'https://json.schemastore.org/package': Unable to load schema from 'https://json.schemastore.org/package': Failed to establish a socket connection to proxies: ["PROXY 127.0.0.1:7890"].",
"startLineNumber": 1,
"startColumn": 1,
"endLineNumber": 1,
"endColumn": 2
}]
```

**Comment by hare0319** [comment]
Get this issue occasionally with wsl2.
As mentioned in [vscode document](https://code.visualstudio.com/docs/setup/network#_proxy-server-support), the issue can be solved by --no-proxy-server option to disable proxy or simply specify the http_proxy and https_proxy using wsl server ip, which can be find from /etc/resolv.conf. The file is generated by wsl
