### ISSUE TITLE
CSS outline property doesn't apply border-radius property when rendered with Simple Browser: Show

### ISSUE THREAD

**Issue by Tigrich** [microsoft/vscode#136526]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.0 and also in 1.63.0-insider
- OS Version: Windows 10 21H1

Steps to Reproduce:

1. create index.html file and enter the code:
```
 <style>
    div {
    width: 100px;
    height: 150px;
    background-color: pink;
    outline: 10px solid black;
    border-radius: 40px;
}
</style>
<div>
</div>
```
2. Open command palette Ctrl+Shift+P and enter "Simple Browser: Show" and enter URL to this file.

3. Notice outline isn't rounded which means border-radius didn't apply to outline
![Simple_Browser_-_WebDev_-_Visual_Studio_Code_2021-11-05_15-46-42](https://user-images.githubusercontent.com/90102138/140537675-a6b3cb62-2edc-4cf1-822d-120141ed2dd5.png)

4. Same code in browsers like Chrome or Edge has rounded outline
![127 0 0 13000testindex_copy html_-_Google_Chrom_2021-11-05_15-32-33](https://user-images.githubusercontent.com/90102138/140537862-6b2052ca-7e01-4f6c-b5e9-a8ff75e0340b.png)

**Comment by mjbvz** [comment]
The simple browser is just an iframe so if some css isn't working in it, it's an upstream issue with chromium. Since it works in the current chrome release though, I suspect it's already been fixed
