### ISSUE TITLE
Special character "˝" is inserted into text editor first time I type.

### ISSUE THREAD

**Issue by Pigotka** [Microsoft/vscode#13651]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Open Code
2. Press any printable key or space (for example x key)
3. See that ˝x was printed into text file.

I've verified that this issue is not related to any exptensions.

**Comment by isidorn** [comment]
I can not reproduce this

**Comment by Pigotka** [comment]
Yes it will he rly hard to repro this. What can I do to help you. I can record it on video that it is happening. I don't have any more repro steps to help though.

**Comment by Velok** [comment]
Do you use a special Keyboard Layout? What if you update VSCode to Version 1.6? Any Extensions installed?

**Comment by Pigotka** [comment]
@Velok Is was actually good point. I verified that it's keyboard related. With ENG keyboard settings it does not occurs. It only occurs with keyboard layout: Czech Programmers. can you verify?

**Comment by Velok** [comment]
@Pigotka Yep I can reproduce this. It only happens if you type without any Modifiers. If you press control one time before typing all is okay. Maybe the Start of Atom is triggering a dead key or something like that. Or it is related to the layout itself.

**Comment by Pigotka** [comment]
I'm using this layout all the time and no other application does that.

**Comment by alexandrudima** [comment]
Fixed on master and in insiders build. Please see #11417.
