### ISSUE TITLE
window.customMenuBarAltFocus does nothing?

### ISSUE THREAD

**Issue by sebasijan** [microsoft/vscode#136596]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.0
- OS Version: Linux Mint 20.2

Steps to Reproduce:

1. Navigate to settings -> Window
2. Read the description for setting `window.customMenuBarAltFocus`
3.From what I can tell, it says that it does nothing:

> Controls whether the menu bar will be focused by pressing the Alt-key. This setting has no effect on toggling the menu bar with the Alt-key.

After toggling this, I can still press alt to show the menu-bar (as expected?)

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/98240#issuecomment-642803404

**Comment by sbatten** [comment]
thanks @gjsjohnmurray
