### ISSUE TITLE
Update should not force VS Code to restart or it should be configurable

### ISSUE THREAD

**Issue by telion2** [microsoft/vscode#136515]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

When the version of VS Code changes/updates, it restarts VS Code. 

This can be from annoying to having consquences. 
For instance it means that the terminals are closed but the processes (e.g. servers) still run. Meaning they need to be restartet. 

What I like to see is either a setting where I can control, when what is updated 
OR 
a notification, that gives me the choice to update. 
But I want to control when my IDE shuts down, restarts or is running. 

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:18:44.904Z)
OS version: Linux x64 5.11.0-38-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|31.11GB (4.62GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id e8642964-0c57-41a5-ac86-62ba2f3a0d27|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
scss-lint|ada|0.1.10
ng-template|Ang|13.0.0
angulardoc-vscode|Ang|6.1.3
npm-intellisense|chr|1.4.0
gitignore|cod|0.7.0
vscode-eslint|dba|2.2.2
FreeMarker|dco|0.0.9
githistory|don|0.6.19
xml|Dot|2.5.1
vscode-babel-coloring|dza|0.0.4
gitlens|eam|11.6.1
vscode-html-css|ecm|1.10.2
tslint|eg2|1.0.47
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
vscode-firefox-debug|fir|2.9.4
vscode-jest-runner|fir|0.4.47
terminal|for|0.0.10
html-slim-scss-css-class-completion|gen|1.7.8
sass-lint|gle|1.0.7
vscode-jasmine-test-adapter|hbe|1.7.1
vscode-test-explorer|hbe|2.21.1
vue-snippets|hol|1.0.4
rest-client|hum|0.24.5
vue|jcb|0.1.5
vscode-jest-test-adapter|kav|0.8.1
node-module-intellisense|lei|1.5.0
vscode-language-babel|mgm|0.0.35
git-graph|mhu|1.30.0
HTMLHint|mka|0.10.0
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.17.0
data-workspace-vscode|ms-|0.1.0
mssql|ms-|1.11.0
sql-database-projects-vscode|ms-|0.13.0
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
powershell|ms-|2021.10.2
test-adapter-converter|ms-|0.1.4
angular2-inline|nat|0.0.17
vetur|oct|0.35.0
vuehelper|oys|0.1.0
vue-beautify|pea|2.0.4
typescript-hero|rbb|3.0.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.1
vscode-yaml|red|1.1.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vscode-scss-formatter|sib|2.3.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by joaomoreno** [comment]
Code will never restart without your approval. When VS Code applies an update it tells you about it and waits for your approval to restart VS Code.

Isn't this what you see?

**Comment by telion2** [comment]
No. It appears to "randomly" restart and it shows the release notes right after.

**Comment by telion2** [comment]
I need to guess, but around once or twice every 2 or 3 weeks at least. 
I installed it using Ubuntu Software, but that is a while back.

**Comment by joaomoreno** [comment]
As I mentioned above, Code won't ever shut itself down without your approval, so it might be something in Ubuntu or the Snap store doing that. I suggest following up with them.

**Comment by HynekS** [comment]
I'am afraid it is not that simple. Today, I was performing an interactive rebase:

- `$ git rebase -i HEAD~2` <-- opens VS Code as it is my default editor. 
- Did a squash using GitLens interactive editor,
- VS Code switches to the classic 'Vim like' interface, I want to edit the commit message,
- _VS Code Updates, closes the editor **without asking for permission**_. Changes are  '`Successfully rebased and updated refs/heads/main`'.

No harm done (I just had to correct the message), but it seems like a **very** dangerous bug (or feature?). I am using Windows 10, so it is definitely not an Ubuntu issue.

**Comment by joaomoreno** [comment]
> * _VS Code Updates, closes the editor **without asking for permission**_. Changes are  '`Successfully rebased and updated refs/heads/main`'.

This is very odd. It definitely should not close automatically. I also can't really reproduce. 😕
