### ISSUE TITLE
Implement a search field in the References list

### ISSUE THREAD

**Issue by buondevid** [microsoft/vscode#136551]
It would be nice to have a **search field** in the references list so that we can search some strings (normal search or regex) only in the list of references. Basically, implement the search function VSCode already has into the list of references too, so that we can look only in the file holding references of a function, component, type, etc...

At the moment only **Refresh**. **Collapse All** and **Clear** are the buttons available in the list.

For example, after clicking "Find all references" on a React component, a list with 100 files holding a reference would open, and with this new feature, I'll be able to find specific words (for example props names) only among these references file.

**Comment by jrieken** [comment]
In all VS Code tree views you can just type to filter or find. Simply start typing and you'll see a filter/find overlay, like so

<img width="536" alt="Screen Shot 2021-11-08 at 08 44 35" src="https://user-images.githubusercontent.com/1794099/140702788-a21ce201-538a-4395-a224-f07f5d80e911.png">

**Comment by buondevid** [comment]
@jrieken You can only **filter** the words that appear in the references list.

My feature request is to do a proper **Search** in those files. This means to search _inside_ the files, at the moment you can filter only between the words appearing in the reference list (so the file name, or the couple of lines that get shown).

**Comment by jrieken** [comment]
It doesn't seems like a core feature of reference search, which is about find concrete code references, e.g line & column of usages. What you are looking for sounds like a great extension candidate, you can use an API command (see https://code.visualstudio.com/api/references/commands) to retrieve references and than you can do things with those files
