### ISSUE TITLE
[css] cssParser incomplete for at-rules

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#1365]
Few of issues I’ve seen in the parser for at-rules:
- @supports flagged as unknown at-rule. https://drafts.csswg.org/css-conditional-3/#at-supports . This is supported by all browsers now.
- @-ms-keyframes isn't flagged. This never existed. It is added [here](https://github.com/Microsoft/vscode/blob/master/src/vs/languages/css/common/parser/cssParser.ts#L480) . There is a note below saying it [doesn't exist](https://github.com/Microsoft/vscode/blob/master/src/vs/languages/css/common/parser/cssParser.ts#L487) but this code doesn't seem to do anything. Removing L480 above fixes it, but I don't know if there should be a more specific error message to show that the prefix was never needed and thus is redundant?
- For @viewport the method is named _parseMSViewPort instead of _parseViewPort, and only includes the -ms- version. Opera Presto (so Opera Mini still) [supports @-o-viewport](https://dev.opera.com/articles/an-introduction-to-meta-viewport-and-viewport/) and it is a good idea to allow the unprefixed version for forwards compatibility. It is supported behind a flag in Chrome/Opera 15+.
- Same issue as above for @document, except the method name is named more generically.
- @counter-style missing. Supported by Firefox (33+). This could hit the two browser rule, but @document is included.
- Same as above for  @font-feature-values. Firefox 34+.

of the new ones, @supports is probably the most critical to fix as it is widely supported now and we'd like to promote it as a better alternative to UA detection for CSS.

Most of these including all @keyframes also don't syntax highlight properly (beyond general broken CSS highlighting in the insider release), but I can look to fix that in CSS.plist separate from this.

**Comment by dstorey** [comment]
For @document, it has been postponed to Conditional Rules L4, which doesn't exist yet, so that one can probably stay as it is.

**Comment by chrispepper1989** [comment]
I get a lot of errors for "@apply" with polymer

**Comment by kzhui125** [comment]
meet this

```
@keyframes {
    from {top: 0px;}
    to {top: 200px;}
}
```

**Comment by aeschli** [comment]
@supports will be supported for 1.17 (September)
I went through the rest of the suggestions and they got fixed no action is needed
