### ISSUE TITLE
Search editor does not honor 'focusResults' option

### ISSUE THREAD

**Issue by rbadapanda** [microsoft/vscode#136541]
Issue Type: <b>Bug</b>

I use the following keybinding to start the search editor
```
  {
    "key": "shift+cmd+f",
    
    // ** For none of the below commands, focusResults works **
    
    "command": "search.action.openNewEditor",
    // "command": "search.action.openEditor",
    // "command": "workbench.action.findInFiles",
     "args": {
      "focusResults": true,
    },
  },
  {
    "key": "shift+cmd+f",
    "command": /*same key. use my commands above*/"-workbench.action.findInFiles"
  },
```
Expected:
After the search the cursor should be in the result area

Actual:
the cursor is still in the search box

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:24:41.297Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 5|
|Memory (System)|16.00GB (1.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by ArturoDent** [comment]
Is `focusResults` an argument to the `findInFiles` command?

**Comment by rbadapanda** [comment]
> Is `focusResults` an argument to the `findInFiles` command?

Looks like it is: https://github.com/microsoft/vscode-docs/issues/4033#issuecomment-709454455

**Comment by ArturoDent** [comment]
That is for the `search.action.openNewEditor` command not `findInFiles`.

**Comment by rbadapanda** [comment]
> That is for the `search.action.openNewEditor` command not `findInFiles`.

focusResults does not work for onenNewEditor either.

**Comment by ArturoDent** [comment]
It is unclear how you are using this command and the `focusResults` argument.  Typically, you would have a keybinding like:

```jsonc
"command": "search.action.openNewEditor",
  "args": {
    "query": "RegisterModel",   // some query
    "triggerSearch": true,          // trigger the search for there to be results
    "focusResults": true            // then focus the results - this works
  },
}
```

You are opening a **new** editor - it will have no results to focus unless you give it a query and trigger the search.

--------------------

If you are trying to reuse an existing searchEditor with results then this is the command:

```jsonc
"command": "search.action.openEditor",
  "args": {
    "query": "RegisterModel",
    "triggerSearch": true,
    "focusResults": true     // this works
  },
}
```

This does not appear to work:

```jsonc
"command": "search.action.openEditor",
  "args": {
    // "query": "RegisterModel",   // no query
    // "triggerSearch": true,          // no trigger
    "focusResults": true
  },
}
```

So if you are trying to open an existing searchEditor and focus the results with no new query and trigger, then it looks like that will not work at present.

You could make a macro that opens an existing searchEditor and focuses the results.

**Comment by rbadapanda** [comment]
Two things I want to achive:
1. when there is no selection, the search should start (seeded with) the current word
2. when there is selection, the search should use the selected text. Which the default search does. just wanted to focus on the results

The context of this ticket the #2 above

**Comment by ArturoDent** [comment]
Okay, for when you have a selection here are my results for the three commands:

```jsonc
{
  "key": "shift+ctrl+f",
  
  "command": "search.action.openNewEditor",
  "command": "search.action.openEditor",
  "command": "workbench.action.findInFiles",
  
  "args": {

    "triggerSearch": true,
    "focusResults": true   // works for search.action.openNewEditor

    "triggerSearch": true,
    "focusResults": true    // works for search.action.openEditor

    "triggerSearch": true,
    "focusResults": true  // not an argument to workbench.action.findInFiles
  },
},
```

run separately of course.  So `focusResults` works for the `search.action.openNewEditor` and `search.action.openEditor` commands **if** you have ` "triggerSearch": true` set as well.  That makes sense, you have to have results in order to focus them.

`focusResults` is not currently an argument for `workbench.action.findInFiles` so it won't do anything there.

**Comment by rbadapanda** [comment]
Thanks for your suggestion for #2.

what is your suggestion for #1 ?
> when there is no selection, the search should start (seeded with) the current word (under cursor) ?

I am planning to use a macro. probably with search.action.openEditor and type command with ${TM_CURRENT_WORD}

**Comment by ArturoDent** [comment]
There is this setting: `Search: Seed With Nearest Word`.    It is disabled by default.  Enable it.  But it only seems to work for the `workbench.action.findInFiles` command - where `focusResults` does not work.  

I would think that the `Seed` setting above should work with the other two search commands but it doesn't for me.  Maybe you will have better luck.

**Comment by rbadapanda** [comment]
Yes, it did not work for me either. Yes I also +1 vote that it should work for the other two.

I have circumvented it using the following macro:

`        "searchAllCurrentWord":[
            "cursorWordRightSelect",
            "cursorRight",
            "cursorWordLeftSelect",
            {
                "command":"search.action.openEditor",
                "args": {
                    "focusResults": true,
                    "triggerSearch": true,
                }
            },
        ],`

**Comment by JacksonKearl** [comment]
Could one of you help me understand what is missing here? It's expected that `workbench.action.findInFiles` does not work with `focusResults` as the find in files command can be handled by either the search view or search editor. Is the concern then that it is not possible to have both `"focusResults": true` and `Search: Seed With Nearest Word` in effect on the same command?

**Comment by rbadapanda** [comment]
```
  {
    "key": "shift+cmd+f",
    "command": "search.action.openEditor",
    // "command": "search.action.openNewEditor",
    // "command": "workbench.action.findInFiles",
    "args": {
      "focusResults": true,
      "triggerSearch": true,
    },
  },
  ```
  
  with the above keybinding in place. select some text and start a "Search Editor: Open Search Editor" command
  
  Issue is: it will not place the cursor on results after the search is finished.
  
  This is issue #1.
  
  
  Issue #2:
  I have the following set:
  ```
  "search.seedWithNearestWord": true,
  "search.seedOnFocus": true,
  "search.searchEditor.reusePriorSearchConfiguration": true
```
  when I start a search (in editor), it is not seeded with the current word if there is no active selection.

**Comment by JacksonKearl** [comment]
I made a change to allow `"search.seedWithNearestWord": true,` to apply to the search editor. I was not able to reproduce the issue where `"focusResults": true,` does not apply.
