### ISSUE TITLE
Sizing terminal to content width should not set fixed rows

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#136525]
Repro:

- Focus a terminal
- Run ls
- alt+z to toggle size to content width (a horizontzal scrollbar should appear)
- Increase size of panel, notice the height of the terminal is fixed to what it was when alt+z was pressed

The reason it's like this is because the scroll bar takes additional width, but maybe we can include that when calculating `_rows`?

**Comment by meganrogge** [comment]
haven't seen other reports of this and don't think we will get to it
