### ISSUE TITLE
Cycle trough previous searches

### ISSUE THREAD

**Issue by janhancic** [Microsoft/vscode#13659]
One feature I miss dearly from sublime is it's ability to remember my previous searches. So I can open the search box (either global or file) and press up/down and cycle trough things I've searched for before (same for other fields in the global search).

Is this something you guys are planning on implementing?

**Comment by isidorn** [comment]
Cool idea, @sandy081 if you are interseted in this feature you could reuse the [History](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/replHistory.ts#L16) which we use for the debug repl input.

**Comment by sandy081** [comment]
@janhancic This feature was implemented in September (1.6) release. Keyboard shortcuts to use this <kbd>alt</kbd> + <kbd>up</kbd> and <kbd>alt</kbd> + <kbd>down</kbd>.

Ref: #5508, #12645

**Comment by janhancic** [comment]
Sweet, thanks!

I did change the defaults to just up and down as that's more intuitive. Thanks!
