### ISSUE TITLE
I couldn't type anything in the editor.

### ISSUE THREAD

**Issue by harishrd** [microsoft/vscode#136504]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by harishrd** [comment]
Issue Type: <b>Bug</b>

I couldn't type anything in the editor..the coursor is of type 'line' but in editor it's showing as underline.

VS Code version: Code 1.58.2 (Universal) (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin arm64 20.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id fc2aa163-ac23-4194-8015-d207493f23f6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eclipse-keybindings|alp|0.14.0
vscode-html-css|ecm|1.10.2
live-html-previewer|hdg|0.3.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
csharp|ms-|1.23.16
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.11.0
jupyter|ms-|2021.8.1054968649
cpptools|ms-|1.6.0
java|red|1.0.0
html-preview-vscode|tht|0.2.5
c-cpp-flag-debugging|uts|0.0.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.34.1
vim|vsc|1.21.10


</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by CodeCrazy-ywt** [comment]
This user **did paste** the needed data! 😡
The github-actions is sometimes not so smart.
Please reopen!
