### ISSUE TITLE
onDidCloseTextDocument not fired when close a file document in .vscode folder

### ISSUE THREAD

**Issue by Arichy** [microsoft/vscode#136558]
Does this issue occur when all extensions are disabled?: Not sure

- VS Code Version: 1.63.0-insider
- OS Version: macos monterey 12.0.1

Steps to Reproduce:

1. Write a vscode extension demo like this:
```typescript
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
  vscode.workspace.onDidCloseTextDocument((document) => {
    console.log('close', document.fileName);
  });
}

export function deactivate() {}

```
2. Run this extension. Open any folder with `.vscode` sub-folder. When I close other file document, the `onDidCloseTextDocument` fired. But when I close file document such as `settings.json` `launch.json` which is in `.vscode` folder, the callback does not fire.

**Comment by bpasero** [comment]
This is maybe happening because these editors are not text editors but UI editors?

**Comment by Arichy** [comment]
Sorry, I didn't make it clear. Only `settings.json` will reproduce. Look carefully your gif, when you close `settings.json`, only `settings.json.git` fired, no `settings.json`

> Does not reproduce for me:
> 
> ![recording](https://user-images.githubusercontent.com/900690/140799659-73c50f9b-5c5d-48de-bd14-c52c6467bf1a.gif)

**Comment by bpasero** [comment]
I can reproduce and the underlying issue is that the settings editor seems to create a model reference for this file that is not cleaned up when the editor closes.

You can run the command "Log Working Copies" after having closed `settings.json` and see how the working copy for the file still hangs around.

The culprit seems to be this stack:

![image](https://user-images.githubusercontent.com/900690/140872725-72febb42-55c1-48ba-ab20-0cfba52dbb8e.png)

**Comment by Arichy** [comment]
> I can reproduce and the underlying issue is that the settings editor seems to create a model reference for this file that is not cleaned up when the editor closes.
> 
> You can run the command "Log Working Copies" after having closed `settings.json` and see how the working copy for the file still hangs around.
> 
> The culprit seems to be this stack:
> 
> ![image](https://user-images.githubusercontent.com/900690/140872725-72febb42-55c1-48ba-ab20-0cfba52dbb8e.png)

I see. So is it a bug or something else?

**Comment by rzhao271** [comment]
Verification steps
1. Open a project, close any open editors, reload, and open devtools.
2. Run the "Log Working Copies" command. `settings.json` should not show up in the devtools console output.
3. Add (if one doesn't already exist) and open a `.vscode/settings.json` file for that project.
4. Repeat step 2. `settings.json` should show up in the output.
5. Close the editor for the `settings.json` file.
6. Repeat step 2. `settings.json` should not show up in the output.
