### ISSUE TITLE
Cutting file copying the file without delete the origin

### ISSUE THREAD

**Issue by kimlimjustin** [microsoft/vscode#136564]
Issue Type: <b>Bug</b>

1. Open two workspaces
2. Right click on a file from first workspace and click Cut
3. Paste it on second workspace
4. The file successfully copied but the origin file does not being deleted. (I mean cut supposed to delete the origin, isn't it?)

Thanks,

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (20.18GB free)|
|Process Argv|--crash-reporter-id 764f0631-6594-4b5e-bed6-3335a3412ce3|
|Screen Reader|no|
|VM|40%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by JacksonKearl** [comment]
It's expected that the cut operation doesn't work across windows, the operating system doesn't tell us when a file is pasted so the best we can do is monitor if it gets pasted somewhere in the same window. In theory we could support the case where the other window is also a vscode window, but the interprocess communication needed to do so would be fairly involved for this narrow use-case. I will leave this open as a feature request candidate.
