### ISSUE TITLE
Add MathJax support in Markdown Preview

### ISSUE THREAD

**Issue by raztd** [Microsoft/vscode#13657]
https://github.com/mathjax/MathJax

Right now the Markdown Preview  does not interpret the MJ syntax correctly.
![mdpreview](https://cloud.githubusercontent.com/assets/6805609/19342491/bd54da14-913a-11e6-9ed5-170c5b44ba5a.jpg)

**Comment by mjbvz** [comment]
Closing as duplicate of #6529

**Comment by goessner** [comment]
see 

[Markdown+Math](https://marketplace.visualstudio.com/items?itemName=goessner.mdmath)
