### ISSUE TITLE
Files with a '#' character can't be opened when an error occurs ('Problems' menu)

### ISSUE THREAD

**Issue by Jiogo18** [microsoft/vscode#136588]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.0
- OS Version: Windows 10
- Extensions: Debugger (C# and C/C++ from Microsoft)

Steps to Reproduce:

1. Create a Workspace with a '#' in the path
2. Create a project (C# or C++) which contains an intentional error
3. Run the project, the "error" occurs (this is normal, we wanted it)
4. Open the 'Problems' menu, the file with the "error" can't be opened because the path is cut before the '#'

Example:

I create a project with `C:\Code\C#\tools\main.cpp`
```c++
#include <iostream>
int main()
{
	std::cout << "Hello world!" << std::endl;
	int foo = "bar";
	return 0;
}
```
Then I execute the project using VS Code (with tasks.json and launch.json) to get the "error" ("bar" can't be converted to int, legit)
- What happens:
I got the "error", but the path is `C:\Code\C` and I can't open it because this file doesn't exist.
![image](https://user-images.githubusercontent.com/30299784/140625131-54ea8fe4-2704-4343-b2c6-d98ef294cb3b.png)
- What I expected:
When I rename the folder `C#` to `CS`, the "error" opens `C:\Code\CS\tools\main.cpp` as expected.
![image](https://user-images.githubusercontent.com/30299784/140625888-1e33a53c-3285-415b-a265-795c918b5954.png)

I guess this also happens for '?' characters, but I can't test it on Windows.

**Comment by gifhupp** [comment]
#include <iostream>
int main()
{
	std::cout << "Hello world!" << std::endl;
	int foo = "bar";
	return 0;
}

**Comment by jrieken** [comment]
This works just fine with TypeScript and other extension. It must be a case of double encoding/decoding with the C++ extension. Please forward this issue to them

<img width="571" alt="Screen Shot 2021-11-08 at 12 13 25" src="https://user-images.githubusercontent.com/1794099/140732356-31158c1b-4f0a-4e3b-96c2-24ff5917d5c5.png">

**Comment by jrieken** [comment]
Re-open, need to know where the problem definition comes from. @Jiogo18 Is that your own problem matcher or one from the extension?

**Comment by Jiogo18** [comment]
Ok, so without the C++ extension, the task can't be executed (and I don't know how to link a local gcc with problemMatcher).
But in C# we don't need the extension to run the task, and the same thing happens :
```json
{
"label": "build",
"command": "msbuild",
"problemMatcher": "$msCompile"
},
```
(created with `dotnet new console`)
```css
using System;
namespace Calendar
{
	class Program
	{
		static void Main(string[] args)
		{
			Console.WriteLine("Hello world!");
			Console.WriteLine(this_is_a_non_defined_variable_to_do_an_error);
		}
	}
}
```
![image](https://user-images.githubusercontent.com/30299784/140736358-646848c4-bd7f-4d84-9adc-22ca2be7ded3.png)

And the build has the full path:
![image](https://user-images.githubusercontent.com/30299784/140737735-467366b5-a73a-4167-a6b7-30c77f6510f9.png)

**Comment by jrieken** [comment]
Adding @alexr00 for the problem matcher specifics
