### ISSUE TITLE
Resizable columns in Process Explorer

### ISSUE THREAD

**Issue by JakubDrozd** [microsoft/vscode#136521]
Issue Type: <b>Feature Request</b>

Hi, I have recently posted an issue [#136510](https://github.com/microsoft/vscode/issues/136510), in which I reported a bug with Process Explorer, and there was also a feature request for resizable columns. Can you add them, please? I would really appreciate.

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/136510

The same fix for both issues
