### ISSUE TITLE
Intellisense is not working

### ISSUE THREAD

**Issue by aman1503** [microsoft/vscode#136568]
Issue Type: <b>Feature Request</b>

intellisence is not working

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

What language? Are you using any extensions? If so, does the "Start Extension Bisect" command identify an extension causing the problem.

**Comment by aman1503** [comment]
C++

**Comment by CodeCrazy-ywt** [comment]
Maybe caused by extension.
