### ISSUE TITLE
Settings sync suspended because of successive auth failures

### ISSUE THREAD

**Issue by TechFounder** [microsoft/vscode#136556]
Issue Type: <b>Bug</b>

Need to constantly re-sign in in order to sync. Error: Settings sync is suspended because of successive authorization failures. Please sign in again to continue synchronizing

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:13.307Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 3, 2|
|Memory (System)|8.00GB (0.22GB free)|
|Process Argv|. --crash-reporter-id 94c1ac2e-9ca4-471e-a897-60908b4a3dfd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.15.1
simple-react-snippets|bur|1.2.4
solargraph|cas|0.23.0
vscode-eslint|dba|2.2.2
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
code-runner|for|0.11.6
copilot|Git|1.7.3689
vscode-pull-request-github|Git|0.32.0
gc-excelviewer|Gra|3.0.44
vscode-gutter-preview|kis|0.29.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
ruby-rubocop|mis|0.8.5
vscode-docker|ms-|1.17.0
remote-containers|ms-|0.205.1
atom-keybindings|ms-|3.0.9
vsliveshare|ms-|1.0.5090
ruby|reb|0.28.1
pdf|tom|1.1.0
gitblame|wad|8.1.0
vscode-ruby|win|0.28.0
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details>

**Comment by Omdal** [comment]
Same problem on Windows 11:

Version: 1.62.0 (user setup)
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-03T15:23:01.379Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (20.08GB free)|
|Process Argv|. --crash-reporter-id 35b31689-e65d-4968-8ea6-b9fad854c645|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
svelte-vscode|sve|105.5.0


</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by yume-chan** [comment]
#133201
