### ISSUE TITLE
Question about registerEvaluatableExpressionProvider

### ISSUE THREAD

**Issue by zobo** [microsoft/vscode#136518]
Current hover experience in https://github.com/xdebug/vscode-php-debug isn't that great.  I have found that registerEvaluatableExpressionProvider can help with it, but the RegEx in javascript isn't that powerful like PCRE, so no recursive matches can be built that would mach stuff like `$this->prop[$that->prop]['a']['b']->more`...

`\$([a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*)((->(?1))|\[(\d+|'[^']+'|"[^"]+"|(?0))\])*`

However, since there is a PHP language extension, and I have taken stewardship of the original https://github.com/zobo/vscode-php-intellisense I was wondering how I would go about using these language features to determine if the cursor is in an expression and get the whole range to be passed to the debugger.

I did found this mention https://github.com/microsoft/vscode/issues/89084#issuecomment-593878980 from @weinand but not sure how to behave as a client in this operation...

Any help appreciated.

Sorry, I know this is not a feature request, but wanted to have this discussion in the open in case somebody else needs it.

**Comment by weinand** [comment]
Yes, registering a `EvaluatableExpressionProvider` in the PHP language extension is the right way to go because there you have access to the AST. If this is not possible, then you could try to use a minimal PHP-parser.

**Comment by zobo** [comment]
Hi!
I looked and didn't yet found a proper implementation of `EvaluatableExpressionProvider` in the context of a language extension/server. Also `registerEvaluatableExpressionProvider` [documentation](https://code.visualstudio.com/api/references/vscode-api) states that:
> If multiple providers are registered for a language an arbitrary provider will be used.

That is why I was thinking of implementing the `EvaluatableExpressionProvider` in debug extension, see if there are any language services for PHP available (via other extensions) use those if possible and fall back to naïve/best-effort RegEx.
Question is, is there an API for using language services from the debug extension. I haven't yet found what the best [language feature](https://code.visualstudio.com/api/language-extensions/programmatic-language-features) would solve this problem...

Thanks!

**Comment by weinand** [comment]
The only difference between a debug extension and a language extension is that the latter has "natural" access to the language services (because it implements the service) whereas the former has not. 

So contributing an `EvaluatableExpressionProvider` from a debug extension does not help you because debug extensions typically don't access the language service (because they don't need to).

And even if a debug extension would have the need to access a language extension, then there is no public API for doing this. Even if the language extension uses an LSP-based "Language Server", then this is an implementation detail of the language extension and there is currently no way to access the LSP-based "Language Server" from another extension.

**Comment by weinand** [comment]
Closing, since there is nothing actionable left.

**Comment by zobo** [comment]
Hi. Sorry to leave the issue hanging for so long...

I just want to give feedback I managed to hack something together in the language extension:

```
    context.subscriptions.push(
        vscode.languages.registerEvaluatableExpressionProvider('php', {
            async provideEvaluatableExpression(
                document: vscode.TextDocument,
                position: vscode.Position,
                token: vscode.CancellationToken
            ): Promise<vscode.ProviderResult<vscode.EvaluatableExpression>> {
                const resp = await client
                    .sendRequest(
                        lsp.HoverRequest.type,
                        client.code2ProtocolConverter.asTextDocumentPositionParams(document, position),
                        token
                    )
                    .then(client.protocol2CodeConverter.asHover)
                if (resp?.range !== undefined) {
                    return new vscode.EvaluatableExpression(resp!.range)
                }
                return undefined // nothing evaluatable found under mouse
            },
        })
    )
```

This doesn't really dive into the AST, it just _abuses_ the already existing LSP hover functionality. Most results are ok.
The issue that I am having is that I have no idea if users have both php-debug extension and php-intellisense installed.

One idea I had was that the php-debug extension could query [getExtension](https://code.visualstudio.com/api/references/vscode-api#extensions.getExtension) and the php-intellisense could expose the needed functionality via its public API.  If the needed extension is not available, fall back to regex.
So both extensions would implement registerEvaluatableExpressionProvider, and the one from php-intellisense would be preferred by means of this extension public API _hack_.

Thanks for all the feedback so far! I'll experiment some more around this.
