### ISSUE TITLE
VSCode insiders document URI scheme changes from "file" to "git" and it feels counterintutive

### ISSUE THREAD

**Issue by osobeso** [microsoft/vscode#136591]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Insiders Version:  version 1.63
- OS Version: Windows 11

Steps to Reproduce:
1) Open a text document located on the extension installation path by using the vscode api as follows:

const readmeTextUri = Uri.file(path.join(context.extensionPath, "readme.txt"));
const document = await workspace.openTextDocument(readmeTextUri);
window.showTextDocument(document);

2) Subscribe to workspace.onDidCloseTextDocument((closedDocument) => {
       
});

3) When 'closedDocument' is the same document you opened in the previous step, they have a difference in their URI properties. as One has the file scheme (the original) and the closed one has the git scheme. Even though they still point to the same path, doing this:

const closedUri = Uri.file(closedDocument.uri.path).path;
const licenseUri = Uri.file(document!.uri.path).path;

ends up in having this result:
closedUri: "/readme.txt.git"
licenseUri: "/readme.txt"

I said it felt counter intuitive because both documents are obtained from the same API I would expect there was a direct way for me to compare when that document is closed, without having to clean the strings/data myself.

**Comment by jrieken** [comment]
When a document is opened, the GIT extension opens another document which represents the documents original state. When closing the editor, the GIT document is closed but the actual document is kept around and the close event is send at a later point.

**Comment by osobeso** [comment]
@jrieken thanks for the clarification!
