### ISSUE TITLE
A bug about the search of github.dev

### ISSUE THREAD

**Issue by Glacier-Luo** [microsoft/vscode#136567]
I know that this function is to directly call github's search.
However, when the results of its search come from other branches, it is still considered to be the content of the current branch.
![image](https://user-images.githubusercontent.com/30594509/140606911-d871fcc5-2ed6-4064-ad07-75be9ee8e6bf.png)
![image](https://user-images.githubusercontent.com/30594509/140606920-238dfceb-6a1d-4764-b2f6-99ad4573cd90.png)
![image](https://user-images.githubusercontent.com/30594509/140606924-b57691b5-6550-4b57-af0c-40932dfa40c3.png)

Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
Embedder: github.dev

**Comment by JacksonKearl** [comment]
What branch are you trying to search on? When on non-default branches I'd expect it to show a warning like this:
![image](https://user-images.githubusercontent.com/8586769/140838770-4034575f-cdaf-4b21-a0fd-e48dfe776546.png)
