### ISSUE TITLE
Difftool breaks when inserting cells

### ISSUE THREAD

**Issue by ebw44** [microsoft/vscode#136524]
## Environment data

-   VS Code version: 1.62.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1001414422
-   Windows 10

## Expected behaviour

Difftool should be able to use cell id to detect insertion of cell and show as new cell

## Actual behaviour

Difference after the inserted cell is offset, so not useful anymore. Removing the inserted cell (or merging with the one before or after partially fix the problem)

**Comment by rebornix** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/133645
