### ISSUE TITLE
Use custom styled tooltips everywhere

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode#136575]
There is an awkward mix of native and custom styled tooltips currently. Some examples from Windows:

![image](https://user-images.githubusercontent.com/530988/140614228-5a007ea3-ce26-4249-b724-c7467fb0bb53.png)

![image](https://user-images.githubusercontent.com/530988/140614230-09431332-bdda-4907-a7ee-0dc5eab6beab.png)

![image](https://user-images.githubusercontent.com/530988/140614233-3510f1b7-66f8-45bf-8f9b-5fa763e38211.png)

![image](https://user-images.githubusercontent.com/530988/140614236-c56ab3d1-fe94-4472-81a6-bd5d02947faa.png)

![image](https://user-images.githubusercontent.com/530988/140614238-eade3c22-7fe9-4914-9346-06fd83b77f20.png)

If window zoom is used (as above), then the mix is most apparent, since native tooltips don't zoom.

I think it would be best if all tooltips would use custom styling to make things consistent and more accessible.

**Comment by Tyriar** [comment]
There are also some users who hate the custom hover and think everything should be native. Unfortunately because of how differently they're used (a function on hover vs `title` attr which _must be there on hover_) it's difficult to have a setting to drive this.

**Comment by misolori** [comment]
I personally would prefer to switch all to custom tooltips, but I think also in the past we've talked about the perf hit that this could introduce.

**Comment by Tyriar** [comment]
Probably wouldn't impact performance as hovers can be evaluated lazily with the custom hover.

**Comment by keenbowl3009** [comment]
The problem with "native hovers" vs "custom hovers" lies simply in the ability to show things outside of the vscode window borders. 

The only reason why people keep this option still turned on is because of that limitation.

**Comment by keenbowl3009** [comment]
> There are also some users who hate the custom hover and think everything should be native. 

Because the native parts can be shown outside of the vscode window when vscode is not maximized.

**Comment by Tyriar** [comment]
@keenbowl3009 I don't think that's the only reason, some people are just fundamentally opposed to the window looking different to the OS. Same reason people use the native title bar when the custom one is superior at this point.

**Comment by JennyStig** [comment]
> @keenbowl3009 I don't think that's the only reason, some people are just fundamentally opposed to the window looking different to the OS. Same reason people use the native title bar when the custom one is superior at this point.

The custom title bar is not superior, because it cannot be shown outside the window borders. 

The only reason why people use the custom title bar is because it's a default setting, and has been like that for a long time. 
You know it, I know it, and everyone who has worked on vscode knows it. 

Pretending otherwise imho is a cynical act.

**Comment by Tyriar** [comment]
Here's that issue I alluded to above where people want to disable the custom hovers: https://github.com/microsoft/vscode/issues/134203

**Comment by letmaik** [comment]
I'm going to close this, I realized this is way less important than dealing with the frequency/occurence of tooltips (https://github.com/microsoft/vscode/issues/15667) which is something that trips me up way more than styling inconsistencies. If people feel strongly about styling, then please keep up/down-voting the first post in this issue and maybe at some point it can be addressed one way or another.

**Comment by ShanConn** [comment]
I hate these custom hovers and those tooltips. On top of that, they are all inconsistently placed, they are extremely distracting, and they don't work with the native titlebar on windows. 

Each day vscode is getting more privacy invasive and unpleasant to use, making developers more and more unproductive and implementing addictive social networking UI patterns.
