### ISSUE TITLE
padding issue on integrated terminal (insiders only)

### ISSUE THREAD

**Issue by EllipticElysium** [microsoft/vscode#136514]
Issue Type: <b>Bug</b>

the padding/margin on the left side of the integrated terminal (bash) is missing in the insiders version so the text is shoved rigt up against the side.

works as expected on an up to date version of the regular vs-code

VS Code version: Code - Insiders 1.63.0-insider (552af97a0170b43c9323bec62211feb184da9749, 2021-11-05T05:16:20.583Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3403)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.72GB free)|
|Process Argv|--crash-reporter-id 39fb7dae-3747-496d-a8ee-f25193692d3c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.2.3
simple-react-snippets|bur|1.2.4
node-snippets|chr|1.3.2
npm-intellisense|chr|1.4.0
bracket-pair-colorizer-2|Coe|0.2.1
githistory|don|0.6.19
gitlens|eam|11.6.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
vscode-firefox-debug|fir|2.9.4
auto-rename-tag|for|0.1.9
vscode-pull-request-github|Git|0.32.0
phpcs|ika|1.0.5
vscode-react-typescript|inf|1.3.1
vue|jcb|0.1.5
git-graph|mhu|1.30.0
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
vetur|oct|0.35.0
indent-rainbow|ode|8.2.2
LiveServer|rit|5.6.1
vs-code-prettier-eslint|rve|3.0.4
vue-vscode-snippets|sdr|2.2.1
code-settings-sync|Sha|3.4.3
vs-code-node-require|tgr|1.10.2
vscode-icons|vsc|11.7.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30382699
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsaa593cf:30376535

```

</details>

**Comment by Tyriar** [comment]
Can you show a screenshot? FYI I currently have a PR out which changes how the terminals get laid out which could affect whatever you're seeing https://github.com/microsoft/vscode/pull/136522

**Comment by bpasero** [comment]
I had the same issue after updating for existing terminals, went away when I closed the terminal and opened again

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/140605554-6c49eaea-e022-44e6-8e2b-97c4dd44c07f.png)

**Comment by EllipticElysium** [comment]
@Tyriar as @bpasero  mentioned, it seems to happen for terminals that are restored on startup as seen here
![image](https://user-images.githubusercontent.com/67951653/140702262-d2ad309c-0ca2-4176-a445-3fa9ce1b1b03.png)
any new terminals i open work perfectly
![image](https://user-images.githubusercontent.com/67951653/140702407-c86167c9-dbd6-4c48-b627-ab1a852611da.png)

**Comment by Tyriar** [comment]
Thanks, this should be fixed when https://github.com/microsoft/vscode/pull/136522 gets merged.
