### ISSUE TITLE
Creating hidden file inside vscode does not create the file in project folder

### ISSUE THREAD

**Issue by tomdelahaba** [microsoft/vscode#136594]
Issue Type: <b>Bug</b>

I created hidden file (by clicking with RMB on my project folder, selecting "new file" and writing naming it .env). Unfortunately, this file was not created in the project folder.
When I went into terminal and listing all the files (including hidden ones) by `ls -a`, this file (.env) was missing. My code, because of that, didnt work properly and process.env.XY variable couldnt be recognized. After creating this file inside terminal (touch .env), another file appeared in the project structure and everything started to work fine.

I think there is a problem creating unnamed (hidden) files through visual code.

![image](https://user-images.githubusercontent.com/89455229/140629475-59a2c37f-30b0-4174-8513-eb10f130d6a6.png)
![image](https://user-images.githubusercontent.com/89455229/140629497-34e48468-33e1-48bf-9f7c-af747236d0bd.png)
![image](https://user-images.githubusercontent.com/89455229/140629512-a210c36e-7a00-45dc-b1dc-465cfc1fd8f2.png)
![image](https://user-images.githubusercontent.com/89455229/140629552-e7db5a2a-551f-495a-8fd5-38fb9bd409eb.png)

VS Code version: Code 1.62.0 (Universal) (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:24:41.297Z)
OS version: Darwin x64 20.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|8.00GB (0.48GB free)|
|Process Argv|--crash-reporter-id e42836b4-6d81-4847-80f8-7cb285c5cb7a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.4.2
vscode-eslint|dba|2.2.2
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|9.0.0
vscode-pull-request-github|Git|0.32.0
vscode-graphql|Gra|0.3.18
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.0
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
ReactSnippets|xab|2.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by PiotrKono** [comment]
It can be user mistake. I tested and file .env created correctly.

**Comment by JacksonKearl** [comment]
From the posted photos it looks like you actually created the file in `.vscode/.env`, as you opened the context menu on the `.vscode` folder rather than the explorer's root. I agree is a bit awkward to select the root, but this seems to be working as-designed. Can you verify that you can create the file when the root folder is correctly selected? A good way to do this is to click on either the title of the explorer view or empty space in the explorer.

**Comment by tomdelahaba** [comment]
> It can be user mistake. I tested and file .env created correctly. 
> 
> I have following version:
> 
> Version: 1.62.0 (user setup)
> 
> Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
> 
> Date: 2021-11-03T15:23:01.379Z
> 
> Electron: 13.5.1
> 
> Chrome: 91.0.4472.164
> 
> Node.js: 14.16.0
> 
> V8: 9.1.269.39-electron.0
> 
> OS: Windows_NT x64 10.0.18363 

Maybe platform specific bug? As provided in screenshots, that bug is in there (and its not user mistake).

Only one what I have been thinking about is, that I am opening the project as following:
I have a folder ("project" folder) in which i have those files (as seen on my printscreens). This folder is made by react-crete-app. I am opening this project by command "code ." In terminal (cmd).
Right click on the .vscode folder and proceed the steps above. But, all other files and folders (unhidden) are created inside the folder without any problem. Unfortunately the problem is only hidden files.

**Comment by JacksonKearl** [comment]
\gifPlease
