### ISSUE TITLE
VS Code - Tabs reload when switching between them

### ISSUE THREAD

**Issue by yonist** [Microsoft/vscode#13656]
- VSCode Version: 1.6
- OS Version: Windows 10
- Plugins: Python , C#

Every time I switch tabs on VS Code the content of the tab is being reloaded. It might not be a problem when developing on local machine, but I'm connected to a remote a machine using WinSShFS.

Can I cache the file locally and only access the remote server on save and first load?

Steps to Reproduce:

1. Connect to a remote linux server using WinSshFS
2. Open  a folder 
3. Open a file and than another file
4. Switch between the tabs

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/13665
