### ISSUE TITLE
Turning off Indentation Guides does not work (they are still rendered)

### ISSUE THREAD

**Issue by ZinoKader** [microsoft/vscode#136505]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Set `"editor.guides.indentation": false` in settings.json.
2. See how the vertical indentation guides still show

<img width="105" alt="Screenshot 2021-11-05 at 11 02 42" src="https://user-images.githubusercontent.com/6842167/140493927-a578defb-38c3-44b3-8a87-98a2265f7738.png">

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:24:41.297Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.62GB free)|
|Process Argv|. --crash-reporter-id 83c670c0-4239-4eff-a624-6f1b30a6a687|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
path-intellisense|chr|2.4.2
vscode-mac-color-picker|dae|1.0.2
vscode-eslint|dba|2.2.2
gitlens|eam|11.6.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
auto-close-tag|for|0.5.13
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.9
go|gol|0.29.0
vscode-env|Iro|0.1.0
vscode-graphviz|joa|0.0.6
svg|joc|1.4.13
vscode-wordpress-hooks|joh|0.6.0
vscode-styled-components|jpo|1.6.6
language-haskell|jus|3.4.0
vscode-language-babel|mgm|0.0.35
vscode-docker|ms-|1.17.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.0
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.1
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.66.0
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.7.1
vsliveshare-pack|ms-|0.4.0
color-highlight|nau|2.5.0
vscode-versionlens|pfl|1.0.9
java|red|1.0.0
vscode-sort-json|ric|1.20.0
rust|rus|0.7.8
autoimport|ste|1.5.4
haskelly|UCL|0.5.5
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
vscode-todo-highlight|way|1.0.5
vscode-import-cost|wix|2.15.0
city-lights-icon-vsc|Yum|1.1.3
material-theme|zhu|3.13.2

</details>

**Comment by hediet** [comment]
Can you post your full settings.json file? I'm very sure these are the bracket pair guides.

**Comment by ZinoKader** [comment]
> Can you post your full settings.json file? I'm very sure these are the bracket pair guides.

Oh wow, it turned out to be the bracket pair guides. Thank you! Although I would have liked to keep the bracket pair highlighting when focusing inside a bracket pair (introduced in 1.62) too, is that possible?
