### ISSUE TITLE
Clear Terminal on Run setting

### ISSUE THREAD

**Issue by githubgitgit** [microsoft/vscode#136552]
I'd like to see this feature that automatically clears the terminal output when ever you click the run button, say when you're running a python file. 
I've looked everywhere on google, SO, and Git and couldn't find anything related to this.

This is a basic feature that is lacking in vs code

**Comment by ArturoDent** [comment]
Do these help?

`Debug > Terminal: Clear Before Using` setting

https://stackoverflow.com/questions/67075228/vs-code-terminal-clear-terminal-before-each-run-of-code

https://stackoverflow.com/questions/69238029/how-to-clear-terminal-in-visual-studio-code-just-before-running-code

**Comment by githubgitgit** [comment]
"Debug: Terminal clear before reusing" is already on. This doesn't seem to make any difference. I do not want to press CMD+K everytime to clear the terminal everytime. There should be a setting that does that automatically whenever you press the run button on the top right corner

**Comment by meganrogge** [comment]
Don't you want to see the output of the run? Not sure why you'd want it to get cleared on run.

**Comment by githubgitgit** [comment]
Expected: Press the run button. The previous output in the terminal is erased, so only the output from the latest run remains.
I would like the output from the previous run to be cleared (clear everything in the terminal that was before, when your press the Run button). So the new output is all that remains in the terminal.

**Comment by Tyriar** [comment]
This depends on how you're running the Python file, it's likely handled by the Python extension or the code runner extension

**Comment by weinand** [comment]
Please set the `"debug.terminal.clearBeforeReusing"` setting to true.
