### ISSUE TITLE
Inline math in markdown doesn't get highlighted if it is at the end of a sentence ending in a period

### ISSUE THREAD

**Issue by kzvi** [microsoft/vscode#136584]
If you open the markdown file

    asdf $\frac{1}{2}$.

then the math doesn't get syntax highlighted, but if you remove the period at the end of the sentence then it is syntax highlighted.

Version: 1.63.0-insider
Commit: 552af97a0170b43c9323bec62211feb184da9749
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
Embedder: vscode.dev

**Comment by mjbvz** [comment]
Note that after this fix, you can't have a word character after the closing `$`. Jupyter lab supports this, but it results in it incorrectly highlighting things like:

```
a $10 b $20
```
