### ISSUE TITLE
Check Update: Unable to create directory c:\tmp Access Denied

### ISSUE THREAD

**Issue by lqlau** [microsoft/vscode#136530]
vscode 1.61.2 has no problems checking for update...but then over time, all of the sudden every time I do a check update, I get a "Setup was unable to create directory, access denied" in the C:\tmp folder.

![image](https://user-images.githubusercontent.com/2287783/140540333-f6cca437-fbe9-4c08-877d-dbdcd935b11c.png)

I always need to re-install vscode and then it works for a while and then over time, again, I get the error whenever I do a check update.

**Comment by gjsjohnmurray** [comment]
Does a Windows restart resolve this? Perhaps a previous update process is still accessing a file in the folder.

**Comment by lqlau** [comment]
No..restart doesn't fix this....every time a check update is done, it's trying to create a random .tmp folder.

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by lqlau** [comment]
> /duplicate #47841
> 
> As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.

Yes.  This only fixes during launch.  When I select "Check Update" and then it "Restart to Update(1)", then I see the pop-up dialog with Access Denied error.  So I can't update vscode.
