### ISSUE TITLE
break point in typescript not stop, source map generated

### ISSUE THREAD

**Issue by jonygli** [Microsoft/vscode#13654]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: austin.code-gnu-global-0.2.1, dbaeumer.jshint-0.10.15, dbaeumer.vscode-eslint-1.0.8, donjayamanne.python-0.4.2, eg2.tslint-0.5.39, Kasik96.format-indent-1.3.0, ms-vscode.cpptools-0.9.2, msjsdiag.debugger-for-chrome-1.1.0, tht13.python-0.2.3, vscodevim.vim-0.3.7

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/13499

**Comment by weinand** [comment]
@jonygli please add this attribute to your launch configuration:
```json
  "trace": "sm"
```
an try to debug again. Do you spot any problems in the log output that is showing up in the debug console?

Could you share the launch configuration you are using?
