### ISSUE TITLE
Add clean build instructions to README.md

### ISSUE THREAD

**Issue by rayogunjimi** [microsoft/vscode#136597]
Please add the instructions for making a clean build and removing previous build artifacts to README.md

**Comment by joaomoreno** [comment]
![image](https://user-images.githubusercontent.com/22350/140888528-7e7e51e0-4186-47b3-9ed3-3ccb780ebef8.png)

https://github.com/microsoft/vscode/wiki/How-to-Contribute

**Comment by rayogunjimi** [comment]
@joaomoreno This link didn't seem to have clean build instructions, the very first build, and even that only incremental.

I think I'm looking for something like:
$node --max_old_space_size=4095 ./node_modules/gulp/bin/gulp.js compile

**Comment by joaomoreno** [comment]
`yarn compile` will do it as well.
