### ISSUE TITLE
Unsaved file should be available after editor closed

### ISSUE THREAD

**Issue by pptyasar** [Microsoft/vscode#13650]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:30:01.819Z)
- OS Version: Linux x64 3.13.0-92-generic
- Extensions: Tyriar.lorem-ipsum-1.0.0, medzhidov.font-awesome-codes-html-0.0.3

Steps to Reproduce:

1.When closing editor unsaved files are gone
2.If unsaved files are available even after window closed that would be good

**Comment by kaiwood** [comment]
See #101 for the ongoing discussion about this feature.

**Comment by pptyasar** [comment]
thanks

**Comment by isidorn** [comment]
@kaiwood thanks for pointint out that this is a duplicate
