### ISSUE TITLE
Semantic highlighting flickers on 1.62.0 and later

### ISSUE THREAD

**Issue by Veykril** [microsoft/vscode#136540]
Does this issue occur when all extensions are disabled?: Yes(except for rust-analyzer as that provides the highlighting)

- VS Code Version: 1.62.0-insider b3318bc0524af3d74034b8bb8a64df0ccf35549a
- OS Version: Windows 10

Steps to Reproduce:

1. Open a rust project with the rust-analyzer installed
2. Type in a rust file where semantic highlighted tokens can be observed.

All the semantic tokens will lose their coloring until the server resends the highlighting response that has been requested by the client. This does not occur on VSCode 1.61.0 it does occur on 1.62.0(non-insider) though.

cc https://github.com/rust-analyzer/rust-analyzer/issues/10690
> 
> 
> I'm not sure when this started since I only started to notice it and get annoyed by it earlier yesterday but as of recently the syntax highlighting that underlines mutable bindings in VSCode has been persistently annoying. Everytime I start and stop typing, every mutable binding on my screen briefly loses its underlining. This occurs even if I'm not changing any actual code
> 
> Even weirder, it only really happens when I type two characters consecutively. Typing one, pausing, then typing another doesn't trigger it. See below:
> 
> ![bfa7682f-e613-4871-bdaf-00d0edd77481](https://user-images.githubusercontent.com/20936452/140256338-a8cd6fa2-0c79-4894-9749-24073bd79549.gif)
> 
> Let me know if there's anything else I can provide, but here are my relevant versions:
> 
> rust-analyzer version: [a824768](https://github.com/rust-analyzer/rust-analyzer/commit/a8247685cfa09084bd620c0877ea1eb3d605d8a2) 2021-11-04 nightly vscode-insiders version: 1.62.0-insider b3318bc0524af3d74034b8bb8a64df0ccf35549a OS: Win 10

**Comment by alexdima** [comment]
@Veykril I cannot reproduce the flicker on Linux. I believe this is not a problem with semantic tokens, but a problem with the rendering of underlines. To rule out a problem related with underlines, could you please configure the following:

```
  "editor.semanticTokenColorCustomizations": {
    "rules": {
      "parameter": "#ff0000"
    }
  }
```


https://user-images.githubusercontent.com/5047891/141199601-417054c1-36d7-4a39-b7b0-1427a81e6d7c.mp4


To give you an idea, this is the kind of issue we have seen in the past: https://github.com/microsoft/vscode/issues/76642

**Comment by Veykril** [comment]
This is unfortunately not just an issue with underlines as can be seen here, the issue becomes more apparent in bigger rust files(when the server takes longer to calculate the highlighting again) ![MIF0HEaPFI](https://user-images.githubusercontent.com/3757771/141201005-01086aa6-82e3-4487-993d-2cc5303510ca.gif)

**Comment by alexdima** [comment]
Steps to verify
* clone https://github.com/rust-analyzer/rust-analyzer
* install rust and the rust analyzer extension
* configure:
```
  "editor.semanticTokenColorCustomizations": {
    "rules": {
      "parameter": "#ff0000"
    }
  }
```
* open a Rust file and type in it

In `1.62.1`, depending on your speed, tokens would flicker.

**Comment by weinand** [comment]
No more flicker in VS Code 1.62.2 (b87304b8e799b5ce827be46f8e185d37)
(And I could reproduce the flicker in 1.62.0 - and I noticed that the flicker starts after some time, not immediately...)
