### ISSUE TITLE
bracker pair highlighter vertical & horizontal lines question

### ISSUE THREAD

**Issue by vuppalaprasanth** [microsoft/vscode#136506]
Some scripting languages doesn't support brackets, they work with letters. 
for example, in shell script, we can provide 
![image](https://user-images.githubusercontent.com/16701037/140494120-c97bb290-2958-46a8-9fa0-a09526b26737.png)

if we add "if & fi" to the language colorings, it will highlight that. 
``` json 
    "[shellscript]": {
        "editor.language.colorizedBracketPairs": [
            ["[", "]"], 
            ["{", "}"],
            ["(", ")"],
            ["do", "done"], 
            ["if", "fi"],
            ["case", "esac"]
        ]
    }
``` 

![image](https://user-images.githubusercontent.com/16701037/140494218-dee9df81-aedb-462d-a84b-ef61eefa2748.png)
Is it possible that we can add multiple things for a line? 
So that it can check which matches the existing one and highlight accordingly? 
Something like 
So that it can consider all the things and highlight based on which is passed? 

``` json 
    "[shellscript]": {
        "editor.language.colorizedBracketPairs": [
            ["[", "]"], 
            ["{", "}"],
            ["(", ")"],
            ["do", "done"], 
            ["if", "elif", "else", "fi"],
            ["case", "esac"]
        ]
    }
``` 
Just throwing out an open question. 
Thanks!

**Comment by hediet** [comment]
You want `elif` and `else` also to be yellow?

I think this is doable, but it is not super easy. Thus I would only do it if there is significant demand for this feature.

**Comment by byehack** [comment]
also would be nice to support for character and previous indention level:
```json
"[python]": {
        "editor.language.colorizedBracketPairs": [
            [":"]
        ]
    }
```
this will colorize like this:
![image](https://user-images.githubusercontent.com/26390254/140622981-b9621268-a96a-44fb-8fd3-17f1344dfa2e.png)
