### ISSUE TITLE
"Settings sync suspended because of successive authorization failures" despite already being signed into an account

### ISSUE THREAD

**Issue by NixieLake** [microsoft/vscode#136516]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.0
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Be signed into a synced account
2. Use VS Code

![VSCode-Sync_error](https://user-images.githubusercontent.com/31080981/140511576-0d7e850b-13b1-4b05-9493-fbbf2cd1a01c.png)

Looking at other reports of this bug, they all seem to have been merged and closed back in January of this year 2021. It looked like there was an issue with an interval sync competing with a usage-triggered sync and the interval one succeeded but the token for the usage-triggered sync was then denied.

I tried to add to the other issue but as it was closed, no further comments were allowed so I'm submitting a new issue.

**Comment by NixieLake** [comment]
The previous issue was this one: https://github.com/microsoft/vscode/issues/114231

And the bug persists when all extensions are disabled, yes.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/133201
