### ISSUE TITLE
Command palette terminal sorting should be fine tuned

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#136549]
I was in a user study with @stevencl where we were asking a new user to VS Code to open a terminal.
He smartly found the command palette and typed "Terminal" and you could see a bunch of commands but none of them are "Open the Terminal" because it is sorted to the bottom. He did not scroll and was disappointed that he can not simply open the terminal. So I suggest if we can somehow make sure that the `Terminal: Create New Terminal` is at the top.

Repro steps
1. Start VS Code Insiders with a new user data dir
2. Command palette, type "Terminal"
3. Notice the results, no easy action at the top to just open the terminal

![Screenshot 2021-11-05 at 22 24 14](https://user-images.githubusercontent.com/1926584/140580497-02c43a01-c504-41ea-90d5-edaa1f43512e.png)

**Comment by bpasero** [comment]
One thing to note is that the command palette is not sorting by relevance to the search term but alphabetically. The original intent with this was to:
* keep commands that belong together sorted together (e.g. all commands from one extension that have the same prefix)
* make it easier for users to orientate themselves in the list of commands by having predictable sorting order

cc @TylerLeonhardt

**Comment by isidorn** [comment]
Yup I see that it is sorted alphabetically. Changing the sort order approach would make sense if there are other use cases like this.
Maybe a low hanging solution would be to just change the naming of the `Change Color` and `Change Icon` commands which I think are not so important, so we push them to the end and hopefully get some more useful commands near the top. We could name them "Terminal Set Color" for example...
Two entries after `clear selection` is the one we want `Create new terminal`

**Comment by Tyriar** [comment]
We should be hiding the duplicate change color/icons, but I don't think we should get into renaming so "create" comes first. Maybe we should have a special relevance mode where if "Terminal" is searched exactly, "Create new terminal" shows up in a new "relevance" group up the top?

**Comment by Tyriar** [comment]
Tracking just removal of the duplicate change color/icon commands in this, @TylerLeonhardt you might want to fork this into a quick pick feature request for handling exact matches like this.

**Comment by TylerLeonhardt** [comment]
> you might want to fork this into a quick pick feature request for handling exact matches like this

as in like a setting that has: "show duplicates" "first one wins" "last one wins"?
