### ISSUE TITLE
Elements keep deselecting, shifting focus

### ISSUE THREAD

**Issue by svArtist** [microsoft/vscode#136509]
Issue Type: <b>Bug</b>

Reproduction unsure, but sometimes, the active UI element keeps losing focus, making it sometimes impossible to do anything, like adding a config item via text input.
See video attached:
https://user-images.githubusercontent.com/13470026/140500990-0ad7bed9-230e-4b35-971e-0688c2335db9.mp4

Disabling extensions did not help.

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6300 Six-Core Processor              (6 x 3490)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>

webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (20.12GB free)|
|Process Argv|--crash-reporter-id 143bf0e7-84bd-4340-b6a3-b569938d752e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-export|asl|1.2.0
code-gnu-global|aus|0.2.2
vscode-icontheme-nomo-dark|be5|1.3.6
working-sets|ber|1.4.0
jshint|dba|0.11.0
vscode-eslint|dba|2.2.2
open-files|Div|0.0.4
file-icons|fil|1.0.29
csharp|ms-|1.23.16
brackets-keybindings|ms-|0.1.1
cpptools|ms-|1.7.1
vscode-opened-editors|Nic|0.1.2
prettier-now|rem|1.4.9
tabster|rib|0.0.6
reopenclosedtab|uyi|1.1.0
vscode-backup|Wes|0.0.6

</details>

**Comment by svArtist** [comment]
> Please use the "Start Extension Bisect" command to investigate.

It shouldn't have anything to do with extensions, this happens with extensions disabled as well (in the video, I left t he notification on screen confirming that extensions are disabled)

**Comment by joyceerhl** [comment]
Seems to be in the settings UI so assigning @rzhao271 to start.

**Comment by svArtist** [comment]
> Seems to be in the settings UI so assigning @rzhao271 to start.

Not contained to settings UI, this also happens with other things of similar nature (happened on some kind of in-place pop-up menu, but I can't remember which)

**Comment by WebMechanic** [comment]
probably related to
- https://github.com/microsoft/vscode/issues/134001
- https://github.com/microsoft/vscode/issues/137293

All involving version 1.62. So this is a recent phenomenon.

**Comment by WebMechanic** [comment]
> Not contained to settings UI, this also happens with other things of similar nature 

the terminal selection popup is also affected:
- https://github.com/microsoft/vscode/issues/137293#issuecomment-974773935

Getting rid of the [proposed culprit](https://github.com/microsoft/vscode/issues/137293#issuecomment-970488357) also mentioned in this thread, did solve the issue for me. For now.

**Comment by svArtist** [comment]
> the terminal selection popup is also affected:
> 
> * [Unable to edit filtered settings via UI #137293 (comment)](https://github.com/microsoft/vscode/issues/137293#issuecomment-974773935)
> 
> Getting rid of the [proposed culprit](https://github.com/microsoft/vscode/issues/137293#issuecomment-970488357) also mentioned in this thread, did solve the issue for me. For now.

Can confirm; removing my terminal settings "solves" the issue for me as well!

FWIW, my settings are/were:
```
    ...
    "terminal.integrated.defaultProfile.windows": "Powershell in Folder b",
    "terminal.integrated.profiles.windows": {
        "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe (migrated)": {
            "path": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
            "args": []
        },
        "Powershell in Folder": {
            "path": "C:\\Windows\\System32\\cmd.exe",
            "args": ["/c", "CD /D \"${workspaceFolder}\" & powershell -noexit -command \"Set-location -LiteralPath '${workspaceFolder}'\""]
        },
        "Powershell in Folder b": {
            "path": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
            "args": ["powershell -noexit -command \"Set-location -LiteralPath '${workspaceFolder}'\""]
        }
    }
    ...
```

**Comment by rzhao271** [comment]
Hint to repro the issue: https://github.com/microsoft/vscode/issues/137293#issuecomment-976857768
Root cause: I think there's infinite recursion going on while trying to get the available profiles right after terminal creation. I noticed that while checking whether the profiles have changed, `true` gets returned because variables such as `${workspaceFolder}` get resolved in between.

<img src="https://user-images.githubusercontent.com/7199958/143091311-e1895e68-7b23-4a5c-88a9-69fb04aed1ee.PNG" width="400px" alt="Stack trace showing infinite recursion for available profiles">
 
<img src="https://user-images.githubusercontent.com/7199958/143092208-a5ea1d36-fc7f-4308-afef-67c3c8717c3e.PNG" alt="Profile and availableProfile variables don't match">
