### ISSUE TITLE
editor.language.bracketPairs does not support per-language configuration for Ruby

### ISSUE THREAD

**Issue by alexeyr** [microsoft/vscode#136654]
Based on the release notes (and on https://github.com/microsoft/vscode/issues/132209), I've tried to customize Ruby and ERB bracket pairs. However, the setting editor says "This setting does not support per-language configuration". In both cases the customization doesn't actually seem to be applied.

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No
Remote OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (7.95GB free)|
|Process Argv|--crash-reporter-id 8c4d2ab1-bf4d-4602-909f-8e4b35d4a047|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.219.173.78|
|OS|Linux x64 4.15.0-45-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (16 x 2594)|
|Memory (System)|31.38GB (9.09GB free)|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.66.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246:30386377

```

</details>

Steps to Reproduce:

1. Add 
  ```
    "[erb]": {
        "editor.language.bracketPairs": [
            [
                "def",
                "end"
            ],
            [
                "case",
                "end"
            ],
            [
                "do",
                "end"
            ],
            [
                "fn",
                "end"
            ],
            [
                "if",
                "end"
            ],
            [
                "def",
                "end"
            ],
            [
                "while",
                "end"
            ],
            [
                "class",
                "end"
            ],
            [
                "module",
                "end"
            ],
            [
                "<%=",
                "%>"
            ],
            [
                "<%",
                "%>"
            ],
        ],
    },
    "[ruby]": {
        "editor.language.bracketPairs": [
            [
                "def",
                "end"
            ],
            [
                "case",
                "end"
            ],
            [
                "do",
                "end"
            ],
            [
                "fn",
                "end"
            ],
            [
                "if",
                "end"
            ],
            [
                "def",
                "end"
            ],
            [
                "while",
                "end"
            ],
            [
                "class",
                "end"
            ],
            [
                "module",
                "end"
            ],
        ],
    }
  ```
  to the user settings
2. See the warning under `"[ruby]" > "editor.language.bracketPairs"`.
3. Create an untitled Ruby file with these contents:
```
def x
end
```
Note the `def/end` pair is not colorized.
4. Create an untitled ERB file with these contents:
```
<%= x 
%>
```
Note the `<%=/%>` pair is not colorized.
(but maybe I misunderstood https://github.com/microsoft/vscode/issues/132209 and 3 isn't supposed to work anyway? Then only 1,2 are the problem.)

**Comment by alexeyr** [comment]
`editor.language.brackets` works, thank you. 

1. Should a separate issue be submitted to fix the release notes?
2. Does it make sense to submit an issue for the extension to add its own support?

**Comment by hediet** [comment]
> Does it make sense to submit an issue for the extension to add its own support?

Definitely!

> Should a separate issue be submitted to fix the release notes?

Yes, please do so in the [vscode docs repo](https://github.com/microsoft/vscode-docs)!

**Comment by alexeyr** [comment]
Thank you again!
