### ISSUE TITLE
References to other files not working in Webview in explorer view

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode#136691]
Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-03T15:24:41.297Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

In my extension I use a Webview create 2 instances of it and put one into the explorer view and one in the debug view.
The one in the debug view works correctly but the one in the explorer view does not work.
It references a css and a js file that cannot be loaded in the explorer view:

![Bildschirmfoto 2021-11-08 um 20 32 59](https://user-images.githubusercontent.com/3081973/140805940-2a94935d-19cd-4257-bd7e-1acac9ec23a7.jpg)

The debug view Webview uses exactly the same reference and here I get no error.

What is the difference? What do I have to do to load the referenced files also in the explorer view?

**Comment by mjbvz** [comment]
Please share a minimal example extension that demonstrates the problem

**Comment by maziac** [comment]
You can get it here: 
https://github.com/maziac/asm-code-lens

The html code is provided by the class HexCalcProvider which is called in extension.ts activate().

**Comment by maziac** [comment]
Hi,
I attached a minimal project (webview-problem.zip) with this problem.
[webview-problem.zip](https://github.com/microsoft/vscode/files/7507099/webview-problem.zip)

And I also investigated some more.
The problem seems to happen when the extension is installed and at the same time the extension is being debugged.

What I did now to reproduce is:
1. Install the included vsix
2. Launch the extension from the debugger. -> The explorer webview is loaded correctly:
![Bildschirmfoto 2021-11-09 um 19 22 51](https://user-images.githubusercontent.com/3081973/140982210-c0ebb0cb-e5e3-436b-a490-f0735032d5c6.jpg)
3. Don't stop the debugger.
4. Open a new window. The explorer webview is not loaded correctly (the referenced js file is not executed/found):
![Bildschirmfoto 2021-11-09 um 19 25 03](https://user-images.githubusercontent.com/3081973/140982630-d5839336-9b2d-497d-a3b8-0222e0309795.jpg)

Here is a short screencast with the problem:
![webview](https://user-images.githubusercontent.com/3081973/140983450-5a758dcc-10a6-4b4b-8231-f73f506a1499.gif)

Strange is that this problem does not occur for the same webview when it is launched in the Debug View.

**Comment by mjbvz** [comment]
When you create a new window, it will not pick up  the extension being debugged. I just tested this and only see the `wexadecimal calculator` view in the first window. It looks like the difference is because there are two different versions of the extension being picked up by the windows?

**Comment by maziac** [comment]
Because I suspected that it might be something with the version I put the number in the bottom right corner of the webview.
Both webviews are from the same version. Maybe it makes a difference if once the extension is being debugged and once it is installed. But why?
1. Why is the installed extension not finding it's files?
2. Why is the installed version able to find the files if running in the debug view?

**Comment by mjbvz** [comment]
What version are you seeing activated, the one being debugged or the installed version? Does the extension work if you aren't debugging VS Code?

**Comment by maziac** [comment]
I modified the debugged code such that it also shows the text "debug".

![Bildschirmfoto 2021-11-11 um 17 13 18](https://user-images.githubusercontent.com/3081973/141331226-a5e717bc-89fd-4375-a0aa-e753a2cadfe2.jpg)

In the background window you see the debugged extension and in the foreground you see the new window with the installed version.
Both show the right html-file, but the installed version is not working.
When I close the debugged extension, the windows with the installed version is still not working (but that is expected because the html is not reloaded).
But if you open another window, the installed version is working there.

Maybe it has something to do with rights or maybe the files are taken from the wrong resource. If it's going wrong the javascript file that is loaded from the html is not found and that happens in case the extension is being debugged.

**Comment by maziac** [comment]
Is there any idea why this happens?

**Comment by maziac** [comment]
There has not been a solution to this problem and it is still strange. 
However if it helps you, you can close.

**Comment by mjbvz** [comment]
I see both working now:

![Screen Shot 2022-02-07 at 9 27 30 AM](https://user-images.githubusercontent.com/12821956/152840182-546e905a-fd2c-4cf9-b775-1abe8315a85f.png)

![Screen Shot 2022-02-07 at 9 27 26 AM](https://user-images.githubusercontent.com/12821956/152840226-c3dfbe13-c7dc-44fd-a0f3-8a159aaa3ecd.png)


Have you tested on the lates insiders build?

**Comment by maziac** [comment]
Yes, right. I tested and in the current 1.64.0 it seems to work.
So maybe some other fix has made this work.
Anyhow, we can close I think.
