### ISSUE TITLE
Php: syntax highlighting probem

### ISSUE THREAD

**Issue by eco747** [microsoft/vscode#136659]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.62.0
- OS Version: windows 10

Steps to Reproduce:

1. just create a php source (save it as php) with this content:
```php
<?php
     echo "hello <p world";
     // now your syntax highlighting is broken.
     echo "bad"
```
2. remove the < character in the string "hello <p world" now everything is ok.

**Comment by roblourens** [comment]
What theme? I don't see a problem. Can you share a screenshot?

**Comment by eco747** [comment]
Yes,
 here are the screenshots
![2021-11-18_09-11-44](https://user-images.githubusercontent.com/2598404/142377293-b35871c5-e410-4290-b685-26e768ea830d.png)
![2021-11-18_09-12-57](https://user-images.githubusercontent.com/2598404/142377341-1c21bb1d-5183-4625-8ab2-2a120b7a8fe3.png)
![2021-11-18_09-13-13](https://user-images.githubusercontent.com/2598404/142377360-ff4c4e71-6704-4d3d-96ba-64b8b608c5a4.png)
