### ISSUE TITLE
Messages from apparently not installed extensions

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#136655]
Issue Type: <b>Bug</b>

After installing the latest update, I got this message:

![image](https://user-images.githubusercontent.com/1658949/140730008-f6cc8635-eff2-439d-b2ca-b2910095d64b.png)

I don't really care for it or any npm support, so I went into my extensions only to find that I have no extension installed named "NPM support for VS Code". So where is this coming from?

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3598)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (28.24GB free)|
|Process Argv|--crash-reporter-id f825acfe-92fa-4526-a38a-f8815cf9f7ea|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (31.36GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (31.36GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (31.36GB free)|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.5.0
javascript-ejs-support|Dig|1.3.1
eslint-disable-snippets|drK|1.3.0
output-colorizer|IBM|0.1.2
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.205.1
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.66.0
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
vscode-icons|vsc|11.7.0
tsl-problem-matcher|amo|0.5.0
vscode-zipfs|arc|2.3.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.2.2
javascript-ejs-support|Dig|1.3.1
xml|Dot|2.5.1
eslint-disable-snippets|drK|1.3.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
vs-code-xml-format|fab|0.1.5
generateuuid|Fir|0.0.5
shell-format|fox|7.2.2
vscode-graphql|Gra|0.3.18
yarn2-dependency-explorer|hah|0.0.1
terraform|has|2.16.0
vscode-test-explorer|hbe|2.21.1
vscode-esformatter|how|1.6.0
output-colorizer|IBM|0.1.2
innosetup|idl|1.6.1
vscode-random|jre|1.10.0
template-string-converter|meg|0.5.4
code-beautifier|mic|2.3.3
vscode-docker|ms-|1.17.0
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.0
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
test-adapter-converter|ms-|0.1.4
vscode-js-profile-flame|ms-|0.0.21
vscode-paste-image|mus|1.0.4
monolit|Oli|0.0.33
vscode-yaml|red|1.1.1
vscode-icons|vsc|11.7.0
docker|vsc|1.0.0
yaml|vsc|1.0.0

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Probably a built-in extension.

Try this search in Extensions view:

`@builtin npm`

"Built-in" is one of the options from the Filter command button above the filter field.

You can disable built-in extensions but not uninstall them.

**Comment by oliversalzburg** [comment]
@gjsjohnmurray Nice. Naturally, when I wanted to check this myself before opening this issue, I searched for `npm @builtin`. Quite the different outcome.

**Comment by oliversalzburg** [comment]
After having disabled the extension, I now get an error every time VS Code starts:
> Error: there is no registered task type 'npm'. Did you miss to install an extension that provides a corresponding task provider?

**Comment by alexr00** [comment]
@oliversalzburg we show that message when you have a .vscode\tasks.json file with task of `"type": "npm"` in it and the extension that provides npm tasks is not enabled.

It is ugly that this error is shown on startup though. This error showing so early is a bug (https://github.com/microsoft/vscode/issues/135803) which will be fixed in our November release.

**Comment by oliversalzburg** [comment]
Hah, awesome. I figured it must be something in my configuration causing this, but I couldn't figure out. Thanks a lot!
