### ISSUE TITLE
--disable-direct-write stopped working

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#13664]
- VSCode Version: 1.6.0
- OS Version: Windows 7

Steps to Reproduce:
1.  add `--disable-direct-write` when starting vscode

Related: https://bugs.chromium.org/p/chromium/issues/detail?id=579678

This behaviour makes vscode unusable for me as I work with clear type disabled and use Courier New as font to get pixel perfect font rendering (at least that's how it was before 1.6). All font rendering in vscode is now blurry. I have a standard dpi display (~96dpi).

![screenshot of vscode 1.6](https://cloud.githubusercontent.com/assets/530988/19344829/0d7a0ffe-913c-11e6-81ca-dd6f2f0a8cee.PNG)

EDIT: I downgraded to 1.5.3 now. Nice crisp fonts again...

![screenshot of vscode 1.5](https://cloud.githubusercontent.com/assets/530988/19345679/c12e1498-913f-11e6-9b05-a8faf6ea4de1.PNG)

**Comment by bpasero** [comment]
@letmaik I am playing around with a newer version of Electron and was wondering if you could give this build a try that includes it to see if something has changed with this issue: https://az764295.vo.msecnd.net/insider/d47c8ba23ff35913052db316aaeef1bb92b0dd99/VSCode-win32-1.8.0-insider.zip

Thanks

**Comment by letmaik** [comment]
@bpasero I just tested it with the `--disable-direct-write` flag but no improvement.

**Comment by bpasero** [comment]
They (Chrome) might have taken out this feature for good...

**Comment by bpasero** [comment]
Todays VS Code insider build comes with Electron 1.6.x, would be interesting to hear if this update solves this issue for anyone: http://code.visualstudio.com/Download#insiders

**Comment by letmaik** [comment]
This is clearly an upstream issue (see the linked Chromium issue) and won't be fixed by Google, unfortunately. So, I guess, let's all switch to high-DPI displays and live our lives, I got one now.

**Comment by eladkarako** [comment]
<code>--disable-directwrite-for-ui</code> <sub><a href="http://icompile.eladkarako.com/disable-direct-write-alternative-for-chrome/" title="#disable-direct-write Alternative For Google Chrome"><em>source</em></a></sub>

**Comment by letmaik** [comment]
@eamodio Afaik this option is only for the UI elements like the main application menu, not for regular content.

**Comment by eladkarako** [comment]
oh you're right..
well <em>not quite the same thing as directwrite font fallback</em> but this improves the clarity of the content for me <code>--disable-lcd-text</code>+<code>--disable-font-antialiasing</code>.

<sub>also available (optional, overkill) <code>--ppapi-antialiased-text-enabled=0 --ppapi-subpixel-rendering-setting=0 --disable-composited-antialiasing=1</code></sub>

**Comment by letmaik** [comment]
It's not pixel perfect though with Courier New, right?
