### ISSUE TITLE
Call stack items aren't opening tabs with correct contents

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#136684]
While debugging extensions, if I stop at a break point and try to walk back up the call stack, the tabs that get opened from the call stack view have the correct tab name, but don't initially have the correct contents. But if you switch to a different tab and then back, the proper contents get shown.

This started quite recently (in insiders).

![missing-debug-content](https://user-images.githubusercontent.com/641685/140791529-3afbc53c-680c-43e9-8ed2-0c29760d4f28.gif)

/cc @connor4312 @bpasero

**Comment by roblourens** [comment]
I saw this yesterday but didn't have time to debug. Nothing has changed in debug's end. Any idea @bpasero @lramos15?

**Comment by bpasero** [comment]
No idea from my end, would be good to have a simple repro.

**Comment by bpasero** [comment]
One thing I did change recently, not sure whether it could be the reason though: when you call `openEditor` and there is another call right after that would cancel the first one, `undefined` is returned. Previously we would return the editor pane even though the opening was cancelled.

Refs: https://github.com/microsoft/vscode/commit/6ed67dd61ebbd218892b3c47008cac33da0ac899

**Comment by weinand** [comment]
I couldn't reproduce this.
Does the problem reproduce if you run VS Code without extensions?

**Comment by rchiodo** [comment]
I can reproduce this consistently. You just need an item in the callstack that is from a file that's different from the topmost item.

**Comment by rchiodo** [comment]
Repro steps for me
- Disable all extensions
- Clone  https://github.com/microsoft/vscode-extension-samples.git
- Open the tree-view sample
- Stick a breakpoint in jsonOutline.ts::refresh()
- Click on the extension.activate call frame

It activates the tab, but the contents are from the jsonOutline.ts file:

![image](https://user-images.githubusercontent.com/19672699/140971780-8005145e-bcb6-4d26-9d5c-2ace24747545.png)

**Comment by weinand** [comment]
@rchiodo thanks for the steps, now I can reproduce!

(without your detailled steps I was trying a web-packed extension which only has one underlying *.js file but maps to many *.ts files). 

In my case (on macOS) I do not see the wrong contents, but no contents at all:

![2021-11-09_18-40-16 (1)](https://user-images.githubusercontent.com/1898161/140976246-d16469bf-cb1e-47d2-93e8-367a1e822f54.gif)

**Comment by rchiodo** [comment]
/verified. Opened tabs are correct.
