### ISSUE TITLE
github-actions sometimes not so smart.

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [microsoft/vscode#136604]
This issue is not about the software, but one of your bots.
Sometimes a user does paste the data written to his/her clipboard, but github-actions still shows up saying “It looks like you did not paste the text generated into the created issue” and closes this issue, which is really annoying and frustrating.
![IMG_20211101_182918](https://user-images.githubusercontent.com/62426149/140639051-c4e6ac5a-0154-4dce-b7ef-cd45f17f5495.jpg)
![IMG_20211105_235119](https://user-images.githubusercontent.com/62426149/140639104-2809ecc8-d4a4-4b0e-b81b-4e228af6d0ca.jpg)

**Comment by JacksonKearl** [comment]
Thanks for reporting this. While I understand that it's frustrating to have your issue closed out like that, the bot is designed to only read from the issue body and act based on it, so this behaviour is as-designed and understanding comment replies is out of scope for the bot.

It may help that GitHub has a "reference in new issue" action that can be invoked on any comment to create a new issue from it.
![image](https://user-images.githubusercontent.com/8586769/140837907-7839fc84-7b35-4251-b821-70e2ea80b04a.png)

**Comment by CodeCrazy-ywt** [comment]
This mechanism is really not smart. I had met several such cases. Why cannot github-actions be more considerate?
