### ISSUE TITLE
setDecorations looks like not work when such line has chinese word.

### ISSUE THREAD

**Issue by Sean10** [microsoft/vscode#136622]
![image](https://user-images.githubusercontent.com/9395594/140651835-19152086-1ddd-4f69-b3e2-51c230bdb0cc.png)

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62
- OS Version: mac 10.14.6

Steps to Reproduce:

1. install `markless_sean10` from marketplace.
2.  open a markdown file. 
3.  write like following:

``` markdown
* 1
* 2
* 我
```

Expected result:  (In 1.61.2, no such problem)
![image](https://user-images.githubusercontent.com/9395594/140651835-19152086-1ddd-4f69-b3e2-51c230bdb0cc.png)

Actual result:
![image](https://user-images.githubusercontent.com/9395594/140651813-70b80c42-713e-4acf-9ada-de1b9bdef3aa.png)

**Comment by alexdima** [comment]
@Sean10 Can you please provide a small snippet that reproduces the problem? e.g. 

* `package.json`:
```json
{
    "name": "136622",
    "publisher": "alex",
    "version": "0.0.1",
    "engines": {
        "vscode": "^1.22.0"
    },
    "activationEvents": ["*"],
    "main": "main.js"
}
```
* `main.js`:
```js
const vscode = require('vscode');

exports.activate = function() {
    const dec = vscode.window.createTextEditorDecorationType({});
    vscode.window.activeTextEditor.setDecorations(dec, [{
        range: new vscode.Range(2, 0, 2, 1),
        renderOptions: {
            after: {
                contentText: 'x'
            }
        }
    }]);
};
```
* `file.txt`:
```
* 1
* 2
* 我
```

**Comment by Sean10** [comment]
> * 1
> * 2
> * 我

Are your vscode version is `1.62`? 

This problem in my device only occur when i upgrade vscode to `1.62`

**Comment by pokey** [comment]
From what I can tell there are currently 4 open issues caused by the same problem introduced in 1.62.0:

- https://github.com/microsoft/vscode/issues/136622
- https://github.com/microsoft/vscode/issues/136813
- https://github.com/microsoft/vscode/issues/136676
- https://github.com/microsoft/vscode/issues/136690

The issue seems to be that decorations don't work if the line contains non-ASCII characters.  This issue appeared in 1.62.0

**Comment by alexdima** [comment]
To verify, see [this comment](https://github.com/microsoft/vscode/issues/136622#issuecomment-963893760) for an example extension and steps to reproduce. Make sure you have (`"editor.renderControlCharacters": true`) (the default).
