### ISSUE TITLE
Ctrl+D (EOF) in debug mode VSCode

### ISSUE THREAD

**Issue by AlexanderZhirov** [microsoft/vscode#136610]
```
Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-04T20:38:29+02:00
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
ОС: Solus 4.3 Fortitude, Linux x64 5.14.16-204.current
```

There is a program written in D. In the loop, a string is fed to the input, read and further execution of the algorithm takes place. When running in normal mode, the program works without any problems.

![Image](https://i.stack.imgur.com/BwMpp.png)

When running in debug mode, I can't continue running the program because it hangs on the input process. I can't continue executing my code after pressing "Enter".

![Image](https://i.stack.imgur.com/nydCy.png)

My **launch.json**:

    "version": "0.2.0",
    "configurations": [
        {
            "type": "gdb",
            "request": "launch",
            "name": "Launch Program",
            "target": "./lesson_2/bin/lesson_2",
            "cwd": "${workspaceRoot}",
            "valuesFormatting": "parseText"
        }
    ]

I tried to connect an external terminal, but it didn't work out.
Did so:

    "version": "0.2.0",
    "configurations": [
        {
            "type": "gdb",
            "request": "launch",
            "name": "Launch Program",
            "target": "./lesson_2/bin/lesson_2",
            "cwd": "${workspaceRoot}",
            "valuesFormatting": "parseText",
            "console": "externalTerminal",
            "debugOptions": [
                "RedirectOutput"
            ]
        }
    ]

And that's it:

    "version": "0.2.0",
    "configurations": [
        {
            "type": "gdb",
            "request": "launch",
            "name": "Launch Program",
            "target": "./lesson_2/bin/lesson_2",
            "cwd": "${workspaceRoot}",
            "valuesFormatting": "parseText",
            "externalConsole": true
        }
    ]

I also tried adding this option, but nothing has changed:

    "console": "integratedTerminal"

I use [Native debug](https://github.com/WebFreak001/code-debug).
In general, I don't know what to do. I ask for help.

**Comment by weinand** [comment]
@AlexanderZhirov please note that programs that are launched in VS Code's "Debug Console" cannot read input (e.g. your "stdin.byline").
Try to use VS Code's "Integrated Terminal" or "External Terminal" if the debugger you are using (e.g. "Native debug") supports this.
If that doesn't work, please file the issue against "Native debug".
