### ISSUE TITLE
Missfunction of Ctrl+Y

### ISSUE THREAD

**Issue by ElRafeta697** [microsoft/vscode#136647]
Issue Type: <b>Bug</b>

In all PC where I used VSCode, I am not able to redo with Ctrl+Y. When I try to redo with Ctrl+Y, VSCode deletes entirely the line the cursor is placed while in the Edit menu, Ctrl+Y is specified as Redo shortcut. I'm experimenting this issue many versions ago. Thanks

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.31GB free)|
|Process Argv|--crash-reporter-id 312dc21a-87ab-4e01-9d8e-c7024d8b6b11|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
lolcode|arw|1.0.0
vscode-html-css|ecm|1.10.2
wlang|gde|0.4.0
resxformatter|gir|1.0.1
intellij-idea-keybindings|k--|1.5.0
kvlang|Mon|0.0.6
vscode-language-pack-es|MS-|1.62.2
csharp|ms-|1.23.16
dotnet-interactive-vscode|ms-|1.0.2554010
vscode-dotnet-pack|ms-|1.0.4
data-workspace-vscode|ms-|0.1.0
mssql|ms-|1.11.0
sql-database-projects-vscode|ms-|0.13.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.0
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
cpptools|ms-|1.7.1
live-server|ms-|0.2.9
mono-debug|ms-|0.16.2
godot-csharp-vscode|nei|0.1.3
java|red|1.0.0
vscode-xml|red|0.18.1
cod-sense|se2|1.0.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `Ctrl+Y`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by ElRafeta697** [comment]
This behaviour is provided by IntelliJ IDEA Keybindings extension, but I can't find any setting from that extension to modify the keybinding

**Comment by alexdima** [comment]
@ElRafeta697 All keybindings can be modified by you. You can open the keybindings editor (ctrl+k ctrl+s), search for the action or command you want and assign to it a different keybinding.
