### ISSUE TITLE
Code.exe stops working 

### ISSUE THREAD

**Issue by MerlinMagicka** [microsoft/vscode#136631]
Issue Type: <b>Bug</b>

I am getting the error that I keep needing to reinstall visual studio code since each time it tries to updates, it deletes code.exe, uninstalling itself...

This only started recently since a recent update of visual studio code. 

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (7.17GB free)|
|Process Argv|--crash-reporter-id a2e2a12f-e171-4277-a552-359ef1f1a6be|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-css-formatter|aes|1.0.1
node-essentials|afr|1.1.0
project-manager|ale|12.4.0
laravel-extra-intellisense|ami|0.6.1
laravel-blade-spacer|aus|2.1.3
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-intelephense-client|bme|1.7.1
htmltagwrap|bra|0.0.7
better-phpunit|cal|1.5.3
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.2
snippets-creator|cla|1.0.0
gitignore|cod|0.7.0
laravel-goto-view|cod|1.3.4
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.1
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
php-debug|fel|1.22.0
php-intellisense|fel|2.3.14
auto-rename-tag|for|0.1.9
vscode-pull-request-github|Git|0.32.0
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
full-stack-development-extension-pack|iqb|2.0.0
lara-pack|iqb|1.0.3
php-cs-fixer|jun|0.2.8
axios-snippets|loy|1.0.2
pretty-formatter|mbl|0.2.2
markdown-shortcuts|mdi|0.12.0
php-namespace-resolver|Meh|1.1.8
dotenv|mik|1.0.1
vscode-kubernetes-tools|ms-|1.3.3
remote-wsl|ms-|0.58.5
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.5090
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.7.1
vetur|oct|0.35.0
laravel-blade|one|1.28.0
laravel5-snippets|one|1.13.0
vscode-jest|Ort|4.2.1
advanced-new-file|pat|1.2.2
material-icon-theme|PKi|4.10.0
fabric8-analytics|red|0.3.4
java|red|1.0.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.1.1
LiveServer|rit|5.6.1
vscode-paste-and-indent|Rub|0.0.8
laravel-artisan|rya|0.0.28
vscode-sass-format|sas|1.1.7
vscode-fileutils|sle|3.4.5
css-auto-prefix|spo|0.1.7
guides|spy|0.9.3
code-spell-checker|str|2.0.12
open-in-browser|tec|2.0.0
highlight-matching-tag|vin|0.10.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
quokka-vscode|Wal|1.0.411
vscode-import-cost|wix|2.15.0
txt-syntax|xsh|0.2.0
axios-snippets|Ygg|1.0.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by joaomoreno** [comment]
Can you try uninstalling VS Code and reinstalling it once again? After that, let me know if the issue resurfaces.

**Comment by MerlinMagicka** [comment]
I've done that before, and it will work for a while, but whenever you close the program and it checks for an update and tries to update, it will cause this issue again. The update crashes and says code.exe not found, then the icon of VScode is gone from my toolbar and my desktop, all files are intact, but code.exe is missing. Even after removing all files and installing vscode again, this issue will surely come back whenever there is an update. 

I've whitelisted VScode on my antivirus (Malwarebytes), so I doubt it would be an issue from that. All other software and windows updates work with no issues.

**Comment by joaomoreno** [comment]
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by MerlinMagicka** [comment]
This does fix the issue since it won't do any background updates, manual updates work fine. What could be the reason that background Updates cause code.exe to uninstall vscode?

**Comment by joaomoreno** [comment]
Actually it will still do automatic updates, just not in the background. It will tell you it's ready to apply an update and then will take a little bit longer to apply, while Code is shut down.
