### ISSUE TITLE
Visual Studio triggers changes check multiple times in nodemon for one save

### ISSUE THREAD

**Issue by 9ae8sdf76** [microsoft/vscode#136641]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.62.0 (Universal)
- OS Version: OS: Darwin x64 20.6.0

This is similar to #48501, except it's not related to the debugger.

Steps to Reproduce:

1. Open Visual Studio Vode
2. Open Terminal
3. Run nodemon 
4. Save a file (doesn't even require changing the file)

It happens more often than not, but sometimes it'll take multiple saves to get the avalanche of restarts. Running `nodemon --verbose` tells me it's the same file each time. I originally had the project folder on Google Drive, and to rule out that as the culprit I copied the folder to my desktop and restarted VS Code and used the desktop version. ~~The problem continued to exist.~~ The problem does go away, so it does seem to be the Google Drive.

**Comment by 9ae8sdf76** [comment]
I hope there is something VS Code can do to mitigate the extraneous file change notifications when saving the file? Otherwise, feel free to close the ticket.

**Comment by gjsjohnmurray** [comment]
Maybe related to #106879?

**Comment by bpasero** [comment]
Any save ends up to be a `truncate` and 1-many `write` calls. Quite possible that this emits more than one event but maybe `nodemon` could add a bit of delay and only react after having listened to events for a bit?

**Comment by 9ae8sdf76** [comment]
@bpasero Good idea. I also created https://github.com/remy/nodemon/issues/1952.
