### ISSUE TITLE
We would like to get an event when the user clicks on the suggest-widget doc-details icon

### ISSUE THREAD

**Issue by anatsegev** [Microsoft/vscode#13669]
- VSCode Version: 0.7.0

We would like to have telemetry when user clicks on the doc-details icon in the suggestion window. 
To do that we request to expose an event when the detail documentation is shown.

**Comment by isidorn** [comment]
@anatsegev please update to the latest version of vscode, 0.7.0 was used by dinosaurs

**Comment by anatsegev** [comment]
It is the latest version here: https://microsoft.github.io/monaco-editor

**Comment by isidorn** [comment]
@anatsegev oh so you are using the monaco editor - not vscode. VSCode latest version is 1.6.0, editor is 0.7.0. My appologies

**Comment by joaomoreno** [comment]
@jrieken API

**Comment by jrieken** [comment]
@joaomoreno not API, he uses the monaco editor and since the asks for telemetry specifically we should maybe just send that telemetry event.

**Comment by joaomoreno** [comment]
The monaco editor has no telemetry. He seems to be talking about his own telemetry service. He wants to be pinged when the details view show. The monaco-editor exposes Intellisense as CompletionItemProviders right?

**Comment by jrieken** [comment]
Well, it has a telemetry service which you set when creating the editor. I guess we need some clarification from @anatsegev

**Comment by anatsegev** [comment]
@joaomoreno is right, we would like our own telemetry service to be pinged when the details view show (to see if users use this feature).

**Comment by jrieken** [comment]
@anatsegev I am against adding events only for the purpose of driving another telemetry service, instead you should hook into our telemetry infrastructure and filter those events you are interested in. We have what's needed in place.

**Comment by anatsegev** [comment]
@jrieken Can you provide me more details on how to hook into your telemetry infrastructure?

**Comment by jrieken** [comment]
When calling the [`create`](https://github.com/Microsoft/vscode/blob/master/src/vs/monaco.d.ts#L748)-function you can pass in an object literal like `{telemetryService: telemeterServiceImpl}` where the latter must implement [this](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/telemetry/common/telemetry.ts#L24) interface

**Comment by anatsegev** [comment]
I created my own telemetry service:
               var editorTelemetryService = {
                   publicLog: function (eventName, data) {
                       console.log("eventName:" + eventName);
                       console.log("data:" + JSON.stringify(data));
                   },
               };
and sent it to the editor. It works like charm!
Nevertheless there is no telemetry for showing the details view of the suggestion.
Can you please add a call to publicLog for this event?

**Comment by joaomoreno** [comment]
The event is `suggestWidget:toggleDetails`.
