### ISSUE TITLE
SVG decorations no longer appear on a line containing certain characters

### ISSUE THREAD

**Issue by pokey** [microsoft/vscode#136676]
Issue Type: <b>Bug</b>

If an extension creates a decoration that uses an svg, the decoration doesn't appear if the line contains a `£`, or any of several other characters (eg Swedish characters with accents).  This issue appeared in the most recent 1.62 release

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:24:41.297Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 4|
|Memory (System)|32.00GB (0.13GB free)|
|Process Argv|-psn_0_2118149 --crash-reporter-id 99d35f96-61a9-461b-a60d-f915d32f3eee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.2.2
vscode-neovim|asv|0.0.82
All-Autocomplete|Ati|0.0.23
markdown-checkbox|bie|0.3.2
turbo-console-log|Cha|2.1.7
path-intellisense|chr|2.4.2
regex|chr|0.4.0
vscode-eslint|dba|2.2.2
chmod|dle|1.1.1
githistory|don|0.6.19
xml|Dot|2.5.1
viml|dun|0.1.7
gitlens|eam|11.6.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
remotehub|Git|0.18.0
vscode-pull-request-github|Git|0.32.0
mdmath|goe|2.7.4
rest-client|hum|0.24.5
jq-syntax-highlighting|jq-|0.0.2
bash-ide-vscode|mad|1.11.0
syntax-project-pbxproj|mar|0.1.3
rainbow-csv|mec|1.9.1
metago|met|4.2.0
MetaJump|met|1.4.0
MetaWord|met|1.3.0
git-graph|mhu|1.30.0
goto-next-previous-member|mis|0.0.5
vscode-edits-history|mis|0.1.6
vscode-talonscript|mro|0.3.2
vscode-docker|ms-|1.17.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.0
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.1
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.66.0
cpptools|ms-|1.7.1
vsliveshare|ms-|1.0.5090
vscode-react-native|msj|1.7.1
autodocstring|njp|0.5.4
command-server|pok|0.7.0
cursorless|pok|0.23.0
parse-tree|pok|0.9.0
ruby|reb|0.28.1
LiveServer|rit|5.6.1
format-code-action|roh|0.1.0
multi-command|ryu|1.5.1
vscode-fileutils|sle|3.4.5
code-spell-checker|str|2.0.12
vscode-open-in-github|sys|1.15.0
tabnine-vscode|Tab|3.4.34
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.7.0
vscode-ruby|win|0.28.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by alexdima** [comment]
Let's track in #136622
