### ISSUE TITLE
still show suggestions in string when disable string suggestion

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#136611]
Version:

```
Version: 1.63.0-insider (Universal)
Commit: 552af97a0170b43c9323bec62211feb184da9749
Date: 2021-11-05T05:15:13.016Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```

some config:

```json
{
  "editor.lightbulb.enabled": false,
  "editor.linkedEditing": true,
  "editor.minimap.enabled": false,
  "editor.quickSuggestions": {
    "strings": false,
    "comments": false,
    "other": true
  },
  "editor.smoothScrolling": true,
  "editor.stickyTabStops": true,
  "editor.suggest.preview": true,
  "editor.suggest.shareSuggestSelections": true,
  "editor.suggest.snippetsPreventQuickSuggestions": false,
  "editor.suggestSelection": "first",
}
```

Steps to Reproduce:

1.reload VSCode with extension disable
2.open a ts file and type quote, the suggestions still display

![image](https://user-images.githubusercontent.com/41773861/140642388-e48922e6-4876-48f1-a776-73a49e25f6ac.png)

**Comment by jrieken** [comment]
Looks like `'` is registered as trigger character... Unsure if there is anything from TS. What's unhappy is that snippets are also invoked and showing. I need to remember why that was done

**Comment by mjbvz** [comment]
Yes we register `'` as a trigger character for import paths:

https://github.com/microsoft/vscode/blob/f1581dcad7b4282dda36b2504ef3721ad5c83a4f/extensions/typescript-language-features/src/languageFeatures/completions.ts#L642

**Comment by jrieken** [comment]
> What's unhappy is that snippets are also invoked and showing. I need to remember why that was done

Snippets are invoked with forgein trigger characters because of https://github.com/microsoft/vscode/issues/37166

**Comment by mrhyde** [comment]
Having the same issue
```Version: 1.63.0-insider (user setup)
Commit: 552af97a0170b43c9323bec62211feb184da9749
Date: 2021-11-05T05:16:20.583Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22494
```

**Comment by DanTup** [comment]
This just came up for Dart too:

https://github.com/Dart-Code/Dart-Code/issues/3670

Dart registers a bunch of trigger characters and because we can't make them conditional based on context, we check them on the server and return 0 completions if the context didn't make sense (for example, when `/` is the trigger, we won't return anything unless the location is within an import path).

The comments in https://github.com/microsoft/vscode/issues/37166 suggest that snippets should only be showing up if the snippet starts with the trigger character, but that doesn't seem to be what's happening here.

**Comment by hediet** [comment]
> Yes we register ' as a trigger character for import paths:

But this still works in stable. Has there been a recent change here?

**Comment by jrieken** [comment]
Yeah - there was a change in how prefixes to compare snippets against are determined. This is the PR: https://github.com/microsoft/vscode/pull/136210. The challenge with snippets is that their insert positions aren't as well defined as with language completions. I have relaxed the rules and now more unwanted snippets show, esp after trigger characters. I am planning to fix this for November
