### ISSUE TITLE
Default Markdown rendering for code cells is incomplete/ugly

### ISSUE THREAD

**Issue by jeanga** [microsoft/vscode#136679]
## Environment data

-   VS Code version: 1.63.0-insider 
-   Jupyter Extension version : v2021.10.1001414422
-   Python Extension version : v2021.12.1414334249-dev
-   OS : Windows 11
-   Python and/or Anaconda version: 3.9.7
-   Type of virtual environment used : N/A
-   Jupyter server running: Local 
- 
## Expected behaviour

Render correctly the Markdown text using the default renderer:
![image](https://user-images.githubusercontent.com/7120091/140740902-49d872bd-a038-4571-841f-d969ce1e8e4d.png)

## Actual behaviour

This is the correct rendering for this:
![image](https://user-images.githubusercontent.com/7120091/140740973-f4095fdc-34c1-432b-9778-26ac9905fcd2.png)

## Steps to reproduce:

1. Create a new Jupyter notebook

2. Create a new cell code with the following Python:

```python
class MyClass:
    def _repr_markdown_(self):
        return '### Process `userland.exe pid:0x178c`  \n| Name| Value |  \n|  :--- |  :---  |  \n|EPROCESS|`{P:0x0000000038d97080,V:0xffffa10610e86080@0xffffa10610e86080}`|  \n|Parent PID|`0x1550`|  \n|Peb|`nt!_PEB@{V:0x000000fe82345000@0xffffa10610e86080}`|  \n|DirBase|`0x000000005bbe3000`|  \n\n'

MyClass()
```
3. Press Ctrl-Enter to render cell

## Details

Via "Choose Output Minetype", selecting the "non default" renderer (i.e. the one with "(vscode.markown-language-feature") for Markdown:
![image](https://user-images.githubusercontent.com/7120091/140741386-26515314-b810-4bbb-be96-b34c262ac063.png)

Gives the expected result:

![image](https://user-images.githubusercontent.com/7120091/140741720-398c6de3-d525-4d2e-baca-dbaf4741679d.png)

Also, I could not find a setting allowing me to make the functioning "Output Mimetype" the default...

Thanks!

**Comment by rchiodo** [comment]
@connor4312 this might be another example of the wrong renderer being chosen.

**Comment by IanMatthewHuff** [comment]
I get the correct default renderer first time now. text/plain is the only other output option.
![image](https://user-images.githubusercontent.com/812783/144331581-a1fdd203-0bfb-4d7f-9857-7ddf12dc6bc2.png)
