### ISSUE TITLE
JSON schema validation become broken after update from 1.60.2

### ISSUE THREAD

**Issue by OlehHarmash** [microsoft/vscode#136658]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.1or higher
- OS Version: Windows 10
- Error "Unable to load schema from 'https://bitbucket.${SOME_DOMAIN}/projects/${PROJECT_NAME}/repos/onboarding-document-schemas/raw/named-values.schema.json': unable to get issuer certificate.(768)"
- Chrome and Edge works fine;
- For VPN connection I am using GlobalProtect;
- I've tried to use addon "win-ca";
- I've tried to use other JSON addons with disabling the default one.

Steps to Reproduce:

1. Install version 1.60.2
2. Import CA certificates
  * On that step it works.
3.  Update VSCode to new version.
  * Stop working.

**Comment by chrmarti** [comment]
@aeschli Where do you load the schema? (Nothing has changed that I'm aware of.)

**Comment by aeschli** [comment]
Schemas are loaded in the extension host with node's `http` and `https` (Also no changes here, except for a fix to give out a proper reason why the request failed)

**Comment by louisgv** [comment]
This issue still persist. For example:

```
{
  "$schema": "https://turborepo.org/schema.json"
}
```

I got the error below:

![image](https://user-images.githubusercontent.com/6723574/157098922-0be6de4d-5da7-4bf5-b987-e16eb6c99c4c.png)

**Comment by chrmarti** [comment]
@louisgv Are you behind a network proxy? Did this work previously?

Could you try with VS Code Insiders (https://code.visualstudio.com/insiders/)? That comes with a newer Node version which might included renewed certificates.

**Comment by 93Akkord** [comment]
> @louisgv Are you behind a network proxy? Did this work previously?
> 
> Could you try with VS Code Insiders (https://code.visualstudio.com/insiders/)? That comes with a newer Node version which might included renewed certificates.

@chrmarti I had the same issue as @louisgv with version 1.65.2 that runs Node version 14.16.0.  I tried again with VS Code Insiders version 1.66.0 that runs Node version 16.13.0 and it worked just fine.

**Comment by shuebner** [comment]
and its broken again in 1.76 :-(
1.75.1 still works

**Comment by chrmarti** [comment]
@shuebner Could you open a new issue including the error you are seeing? Closing this issue as the originally report problem was resolved. Thanks.
