### ISSUE TITLE
add shortcut keybinding for new file and new folder when focus on file explorer

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#136662]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: all
- OS Version: all

Steps to Reproduce:

1. focus on file explorer tree
2. trigger <kbd>ctrl+n</kbd> can not create new file as the new file icon
![image](https://user-images.githubusercontent.com/1876302/140744087-64676555-4ba6-453a-bebc-eaf34f8b7d07.png)

3. trigger <kbd>ctrl++shift+n</kbd> can not create new folder as the new folder icon

![image](https://user-images.githubusercontent.com/1876302/140744191-30315eed-39df-44e3-baf0-16047d0d7a5e.png)

**Comment by heartacker** [comment]
when: filesExplorerFocus

**Comment by gjsjohnmurray** [comment]
Adding these as defaults would be a breaking change.

**Comment by heartacker** [comment]
@gjsjohnmurray  thanks your remind, but it‘s that is better and should be by default IMO. 
reason:
1. user focused on file tree means that user have a clear purpose
2. the icon of new file and new folder can be clicked, just means that we can use same short cut to execute that command.

so I don’t  think that is a break change, just a little

## and the purpose:
1. when focused on editor area, <kbd>Ctrl+n</kbd> <kbd>Ctrl+shift+n</kbd> as before.
2. when focused on file tree.  <kbd>Ctrl+n</kbd> <kbd>Ctrl+shift+n</kbd> should act as the icons actions
3. and also, that will havs a new way to create new file and folder directly, what comfortable way

**Comment by JacksonKearl** [comment]
You're free to add these keybindings to your own installation's `keybindings.json`:
```json
  {
    "key": "cmd+n",
    "command": "explorer.newFile",
    "when": "explorerViewletFocus"
  },
  {
    "key": "cmd+shift+n",
    "command": "explorer.newFolder",
    "when": "explorerViewletFocus"
  }
```
But we will not change this in core as it would break quite a lot of muscle memory.
