### ISSUE TITLE
In the intellisense suggestions, focus randomely jumps to first or last suggestion

### ISSUE THREAD

**Issue by SuperKXT** [microsoft/vscode#136648]
Issue Type: <b>Bug</b>

- VS Code Version: 1.62.0
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:
1. Type any code that triggers intellisense suggestions.
2. Scroll through the suggestions with the mouse or using arrow keys.

The problem keeps happening when I try going through intellisense suggestions. The problem happens both with mouse scrolling and arrow keys.
I've been experiencing this for 2 months now.

This gif illustrates the problem. Apologies if I slowed it down too much.
![Animation](https://user-images.githubusercontent.com/6242472/140707445-4e37ee66-8978-4b8e-ac05-7c4e0b3ff155.gif)

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.45GB free)|
|Process Argv|--crash-reporter-id 8032cb10-3d09-490e-82ce-ef693454a9b5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
vscode-sql-formatter|adp|1.4.4
vscode-nginx-conf|ahm|0.1.3
project-manager|ale|12.4.0
jest-snippets|and|1.8.0
vscode-database|baj|2.2.3
vscode-node-readme|ben|3.0.2
turbo-console-log|Cha|2.1.7
nebula-theme|Chi|1.3.3
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|3.1.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.23
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
code-runner|for|0.11.6
todo-tree|Gru|0.0.214
helium-icon-theme|hel|1.0.0
beautify|Hoo|1.5.0
minifyall|jos|2.10.0
vscode-colorize|kam|0.11.1
theme-karyfoundation-themes|kar|25.0.2
node-module-intellisense|lei|1.5.0
template-string-converter|meg|0.5.4
vscode-language-babel|mgm|0.0.35
fluent-icons|mig|0.0.14
vscode-autoprefixer|mrm|3.0.1
vscode-docker|ms-|1.17.0
remote-containers|ms-|0.205.1
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.66.0
remote-wsl|ms-|0.58.5
vscode-typescript-tslint-plugin|ms-|1.3.3
env-cmd-file-syntax|Nix|0.3.0
indent-rainbow|ode|8.2.2
material-icon-theme|PKi|4.10.0
vscode-yaml|red|1.1.1
LiveServer|rit|5.6.1
mongo-snippets-for-node-js|roe|1.3.10
markdown-preview-enhanced|shd|0.6.1
code-spell-checker|str|2.0.12
single-line-multi-line|Sup|0.1.1
ayu|tea|1.0.5
errorlens|use|3.4.0
vscode-icons|vsc|11.7.0
vscode-import-cost|wix|2.15.0
bracket-lens|wra|1.5.1
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.20.0

(11 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether this is being caused by one of your extensions.

**Comment by SuperKXT** [comment]
The issue was caused by an extension indeed, I'll report the issue to the extension. 
Thank you. I had no idea about Extension Bisection. It's pretty awesome.
