### ISSUE TITLE
Green circle emoji not rendering in vscode

### ISSUE THREAD

**Issue by tifDev** [microsoft/vscode#136614]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.1

Steps to Reproduce:

1. Copy this emoji 🟢
2. Paste in vscode

It will show as exclamation mark:
![image](https://user-images.githubusercontent.com/39730484/140643361-e5adad57-cb07-41f3-b4bc-10197b20bb0f.png)

**Comment by CodeCrazy-ywt** [comment]
Does this emoji turn into an exclamation mark in other apps (e.g. Microsoft Word)?

**Comment by tifDev** [comment]
Sorry I don't use MS office tools, idk.

**Comment by joyceerhl** [comment]
I cannot reproduce this in the latest version of VS Code, which is 1.62. Please consider upgrading and let us know if you still see the same behavior.

**Comment by tifDev** [comment]
I just updated to 1.62 version but the issue persists...

**Comment by alexdima** [comment]
@tifDev What OS are you on?

**Comment by tifDev** [comment]
Tested on Linux but I just also tested on Windows and it's the same.
Can you pls provide me the emoji or source of the website where you took it that worked fine?

**Comment by alexdima** [comment]
The `🟢` emoji works for me on macOS:

![image](https://user-images.githubusercontent.com/5047891/141745480-001640a8-2799-4cb6-b54a-2ebc54afe817.png)

and on Windows:

![image](https://user-images.githubusercontent.com/5047891/141745671-f47e8a71-4671-4be1-b36e-eedc1d62cebf.png)

and on Ubuntu:

![image](https://user-images.githubusercontent.com/5047891/141745807-d668b6a9-bfb1-4f17-adc5-6919608c6feb.png)

**Comment by tifDev** [comment]
This is really strange. I tested from many sources (F.e. https://www.emojicopy.com/) and still the same behaviour.

I see that you are using vscode Insiders. Also installed that on a windows machine to test but still the same.

What could be causing this?

**Comment by alexdima** [comment]
> What could be causing this?

Fonts (e.g. configured `editor.fontFamily` or system installed fonts)

**Comment by tifDev** [comment]
I've disabled all *font* settings in my user settings configs and also tested changed the color theme but still the same.

**Comment by alexdima** [comment]
@tifDev Can you please also try in the editor at https://vscode.dev/ ? Can you please try opening that in a Chromium based browser and also in Firefox? Also, you mention you tested both on Windows and Linux. Can you please try in both Windows and Linux? How about this page -- https://github.com/microsoft/vscode/issues/136614 -- does this character render here: "🟢" ?

**Comment by tifDev** [comment]
> @tifDev Can you please also try in the editor at https://vscode.dev/ ? Can you please try opening that in a Chromium based browser and also in Firefox? Also, you mention you tested both on Windows and Linux. Can you please try in both Windows and Linux? How about this page -- #136614 -- does this character render here: "green_circle" ?


Hi Alex, sorry for the delay.

Yes it renders well there:

![image](https://user-images.githubusercontent.com/39730484/144603984-6f88b9f0-0d04-48cf-bbfc-ac4055b5d8ef.png)

**Comment by alexdima** [comment]
@tifDev Thank you for your screenshot. I believe you have customized heavily the fonts available on your machine. Here is how VS Code normally looks like (notice the non-monospace font used for tabs):
