### ISSUE TITLE
VSCode Typescript debugger breaks on __webpack make namespace ogjet

### ISSUE THREAD

**Issue by PMoransais** [microsoft/vscode#136682]
The vscode typescript debugger breaks on the following webpack code

// define __esModule on exports
__webpack_require__.r = (exports) => {
	BREAKS HERE if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {**
		Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
	}
	Object.defineProperty(exports, '__esModule', { value: true });
};

This happens immediately at start up and ocasionaly while editing.

I do not know if this is a typescript issue or a vscode issue or my issue?

This code can be found at c:/dev/PROJECT DIR/webpack/runtime/make namespace object

The project uses Angular 13 but problem existed with angular 12.
The typescript version is 4.4.4 (updated Angular 13 was installed

the tsconfig module resobultion is node and the target is es6. Changing target to es5 did not work.

My tsconfig file is:

/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
	"baseUrl": "./src",
	"paths": {
		"@common/*": ["common/*"],
		"@entities/*": ["common/entities/*"],
		"@identity/*": ["common/identity/*"],
		"@services/*": ["common/services/*"],
		"@iBreeder/*": ["site/iBreeder/*"],
		"@breeder/*": ["site/breeder/*"],
		"@public/*": ["site/public/*"],
		"@visitor/*": ["site/visitor/*"],
		"@search/*": ["site/public/search/*"],
		"@styles/*": ["styles/*"]
	},

    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "strictPropertyInitialization": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es6",
	"module": "es2020",
	"types": ["node"],
    "esModuleInterop": false,
    "lib": [
      "es2018",
      "dom"
    ],
	"removeComments": true
  },
  "angularCompilerOptions": {
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true,
    "fullTemplateTypeCheck": true
  }
}

changing esModuleInterop to true does not resolve the problem.

Thanks 

Philippe Moransais

**Comment by connor4312** [comment]
Thanks for your emailed logs. It looks like there's likely a `debugger` statement on line 10 of your vendor.js. This is not a sourcemapped location, so because `smartStep` is enabled (default) so we step into the next mappable location.

I recommend looking into what on that line is causing the runtime to pause.

**Comment by PMoransais** [comment]
Thanks Connor,

There was a breakpoint set in the browser, not vsCode, probably by accident.

This solved my problem. I feel bad I dis not think of this

Philippe Moransais

Sent from Mail for Windows
