### ISSUE TITLE
Make it easier to navigate to files/folders in explorer by typing their name

### ISSUE THREAD

**Issue by laggingreflex** [Microsoft/vscode#13666]
[feature-request]

In the file explorer, typing the name of a file should take you to that file, just like it does in Windows explorer.

![vscodefrexplorer](https://cloud.githubusercontent.com/assets/2523987/19346628/16b4bd96-9162-11e6-887c-a222b233cca8.png)

**Comment by bpasero** [comment]
Please search for duplicates.

**Comment by laggingreflex** [comment]
#10026
