### ISSUE TITLE
Add minimize editor group command

### ISSUE THREAD

**Issue by freezlite** [microsoft/vscode#136675]
Let's assume you have layout:
![image](https://user-images.githubusercontent.com/3983804/140768989-ac04647b-068e-4d5b-982a-14891b30a288.png)

And you want to minimize 2nd editor group, without minimize command you can do this only with mouse.

**Comment by bpasero** [comment]
There is commands to maximize the current group, wouldn't that be sufficient?

**Comment by freezlite** [comment]
@bpasero no, because I want to maximize 1 and 3 editor group at same time
