### ISSUE TITLE
Search in selection keeps turning itself on

### ISSUE THREAD

**Issue by janhancic** [Microsoft/vscode#13660]
- VSCode Version: Version 1.7.0-insider (1.7.0-insider) (1889442ff090ef8170814a98698506300962dbba)
- OS Version: OSX 10.11.6

Whenever I hit `cmd+f` the `search in selection` is enabled, regardless if I have a selection active or not. See this or demonstration: http://recordit.co/G1a8RveXgL (I'm hiding the search box with `esc`). It's making search practically unusable for me.

**Comment by isidorn** [comment]
This should only happen if you have a selection that spanes more than 1 line
I can not reproduce this issue on my machine.
Do you maybe have some extensions which alter the state of the selection. Can you repro with --disable-extensions
Do you repro this for any file?

**Comment by janhancic** [comment]
Same happens when I disable all extensions. And I can reproduce in any file. What else can I tell you to help with this?

**Comment by janhancic** [comment]
Actually is  there a way to disable the "find in selection" functionality entirely? I don't think I've ever used it and it's just getting in the way.

**Comment by isidorn** [comment]
@janhancic no, there is no way to disable it. We can do a debugging session to figure out what is wrong on your machine. If this is critical for you we can do it today, though I would prefer next week since then I will have more time.

**Comment by janhancic** [comment]
I'm working around the problem by selecting all before I search for now. Ping me next week and we can figure this out. Thanks!

**Comment by isidorn** [comment]
@janhancic deal

**Comment by wallverb** [comment]
https://github.com/Microsoft/vscode/issues/13695

**Comment by roblourens** [comment]
This is #13621
