### ISSUE TITLE
VS Code doesn't focus after closing the last focused window

### ISSUE THREAD

**Issue by Unlimiter** [microsoft/vscode#136626]
Issue Type: <b>Bug</b>

**Steps to reproduce**:
- focus VS Code
- focus another window
- close that window

**Expected result**: VS Code focuses.
**Actual result**: VS Code doesn't focus.

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (5.01GB free)|
|Process Argv|--crash-reporter-id 9116907a-e1e1-4629-a2e6-aee9802a89dc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
better-toml|bun|0.3.2
doxdocgen|csc|1.3.2
vscode-html-css|ecm|1.10.2
vscode-pull-request-github|Git|0.32.0
vscode-ebnf|igo|1.0.3
latex-workshop|Jam|8.21.1
better-cpp-syntax|jef|1.15.10
remote-containers|ms-|0.205.1
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.66.0
remote-wsl|ms-|0.58.5
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.0.0
powershell|ms-|2021.10.2
vscode-autohotkey|sle|0.2.2
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by rzhao271** [comment]
I'm unable to repro the issue locally.
\gifPlease
