### ISSUE TITLE
side bar

### ISSUE THREAD

**Issue by seonwifi** [microsoft/vscode#136621]
Issue Type: <b>Feature Request</b>

I really don't like your sidebar.
Please let me know if you have any options or products to change to docking panel

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please clarify problems and expected behavior. Otherwise it's hard to see it what exactly you are referring to and want
