### ISSUE TITLE
please add a Keyboard Shortcut to close the Exporer

### ISSUE THREAD

**Issue by vrms** [microsoft/vscode#136661]
- Keyboard Shortcut `Ctrl+Shift+E` brings out the Explorer. 
- It looks like there is missing a shortcut for closing it though. 
- I think it should be there.

**Comment by gjsjohnmurray** [comment]
`Ctrl+B` will close it (or anything in the sidebar), or will open the sidebar if currently closed.

**Comment by vrms** [comment]
yea, sorry. I just found that half a minute ago
