### ISSUE TITLE
[C#] #region could not folding code when there is a tab or space int left of it

### ISSUE THREAD

**Issue by sharksangels** [Microsoft/vscode#13663]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: keyring.Lua-0.0.8, mohsen1.prettify-json-0.0.3, ms-vscode.csharp-1.4.1, Unity.unity-debug-1.0.4

Steps to Reproduce:

1. Write a #region #endregion in a .cs file.
2.Insert a tab or space in left of #region.
3.The folding icon near by the line number will disapear.

**Comment by aeschli** [comment]
The current folding strategy is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.
Entering a space will therefor change the available folding sections.

To be more smart and to, for example, understand go #region and #endregion we will have to go one step further and introduce language agnostic folding regions. We have issue #3422 for this.
