### ISSUE TITLE
close folder from explorer sidebar

### ISSUE THREAD

**Issue by yashpalgoyal1304** [microsoft/vscode#136669]
### Summary
Having an option to close the folder from the explorer side bar would be nice

### Details
1. Since the option to open the folder was there in the sidebar, 
![image](https://user-images.githubusercontent.com/19423063/140756996-3c850c7b-5136-4285-8216-bd8285f8418c.png)
2. my mind automatically searches for the option to close the folder there itself.
![image](https://user-images.githubusercontent.com/19423063/140756873-7e2f2467-dc1e-467e-8a92-5099adc06e88.png)
3. But it's found only in the "file" menu option
![image](https://user-images.githubusercontent.com/19423063/140756907-36546480-8791-4541-bcdb-680250b03739.png)

Duplicate 🔍 [close folder from explorer sidebar ](https://github.com/microsoft/vscode/issues?page=2&q=is%3Aissue+is%3Aopen+close+folder+from+explorer+sidebar)

**Comment by JacksonKearl** [comment]
Those sidebar buttons are for "welcome" content; basically listing ways to put content into an otherwise empty view. If you really want a close option the explorer context menu is open for extension contributions, but for in-core we will leave it to the file menu.
