### ISSUE TITLE
Quick option to disable synced scrolling

### ISSUE THREAD

**Issue by yashpalgoyal1304** [microsoft/vscode#136681]
### Describe
some quick button to toggle the scroll synchronisation on-the-go will be helpful.

### Use Case
Useful whenever some part of a file has to be referred for changing other part, so like:
* doing assignment works ...
where questions are at the top, and the attempt has to go thereafter
* restructuring/improving a **long** markup document.
* translating a document

That document can be anything:
* release notes
* README files
* instructions
* documentations
* guidebooks
* etc.

### Alternates considered:
* Toggle Synchronisation (globally in ⚙️ - [ref🡭]) but that doesnt seem to be otg
* opening the MD preview in some other application/editor

### Environment
- VSCode: 1.61.2
- OS: Win 10 20H2

Duplicate 🔍 [markdown scroll preview synchronization]

[ref🡭]: https://code.visualstudio.com/docs/languages/markdown#_editor-and-preview-synchronization
[markdown scroll preview synchronization]: https://github.com/microsoft/vscode/issues?page=2&q=is%3Aissue+markdown+scroll+preview+synchronization

**Comment by Binly42** [comment]
With extensions like `Settings Cycler`, we could toggle the two setting items for synced scroll by a shortcut.

However, currently, the toggled setting would not work immediately, until:
switch to another tab except the source nor the preview, and then switch back

**Comment by yashpalgoyal1304** [comment]
> Settings Cycler

This one right:
1. [hoovercj.vscode-settings-cycler]
2. [z0al.settings-toggle]
3. 🔍 : [settings cycler]

[hoovercj.vscode-settings-cycler]: https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler
[z0al.settings-toggle]: https://marketplace.visualstudio.com/items?itemName=z0al.settings-toggle
[settings cycler]: https://marketplace.visualstudio.com/search?term=settings%20cycler&target=VSCode&category=Other&sortBy=Relevance

**Comment by Binly42** [comment]
> 

Yah, I use the first one.
To be honest, the logic is very simple, which is just toggle the two setting items:
```json
"settings.cycle": [
        {
            "id": "markdownPreviewSyncScroll", // must be unique
            "overrideWorkspaceSettings": true,
            "values": [
                {
                    "markdown.preview.scrollEditorWithPreview": false,
                    "markdown.preview.scrollPreviewWithEditor": false,
                },
                {
                    "markdown.preview.scrollEditorWithPreview": true,
                    "markdown.preview.scrollPreviewWithEditor": true,
                },
            ],
        },
    ],
```

**Comment by Binly42** [comment]
> However, currently, the toggled setting would not work immediately, until: switch to another tab except the source nor the preview, and then switch back
> 
> (tested even when manually toggle the settings in a all-extensions-disabled-window)

For this issue, a workaround workaround may be:
Use extensions like `multi` to make one single shortcut do followings: (Not tested...
1. toggle the settings said above
2. switch to another tab (e.g. the left tab to the preview)
3. switch back

---

What I most want before is that a command to quick sync the scroll position without keeping sync scroll, I just workaround it by considering something like `Go to line` ...
however
