### ISSUE TITLE
vscode.dev: Make UI more stable when opening a PR URL

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#136660]
Open a PR from the navbar, e.g. https://vscode.dev/github/microsoft/vscode/pull/124803

Observe the activity bar and notice the appearance of:
- the Explorer view
- the GHPRI view
- the Explorer view
- the GHPRI view

**Comment by alexr00** [comment]
Turns out this is coming from GHPRI. There was some flow added 9 months ago that aimed to improve the perceived performance of loading all the views. There is a gap between when views are shown and hidden, which causes the Explorer view to show in-between.
