### ISSUE TITLE
I am not able to create folder/file using vscode

### ISSUE THREAD

**Issue by muoco** [microsoft/vscode#136643]
Issue Type: <b>Bug</b>

When I press file/folder create button and press a key button it closes. Then I can not give a name to file/folder

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:18:44.904Z)
OS version: Linux x64 5.11.0-38-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2312)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|7.20GB (2.03GB free)|
|Process Argv|--unity-launch --crash-reporter-id 5ca16bc4-cc40-4a79-a7da-80a95b769dca|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
tslint|eg2|1.0.47
vsc-material-theme|Equ|33.2.2
prettier-vscode|esb|9.0.0
go|gol|0.29.0
vscode-env|Iro|0.1.0
fluent-icons|mig|0.0.14
vscode-docker|ms-|1.17.0
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.66.0
vscode-typescript-tslint-plugin|ms-|1.3.3
material-icon-theme|PKi|4.10.0
LiveServer|rit|5.6.1
default-keys-windows|smc|0.0.8

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.
