### ISSUE TITLE
Editor decorations don't apply when a line contains Chinese characters

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#136690]
Originally reported on https://github.com/Axosoft/vscode-gitlens/issues/1713

It seems that any line that contains Chinese characters causes before/after decorations to not be applied to the line.

This can easily be seen with GitLens -- if you add a line like `const foo = '你好';` the end of line annotation will not show (and if you toggle on the full file blame annotations) they won't show for that line either.

/cc @alexdima

**Comment by alexdima** [comment]
Let's track in #136622
