### ISSUE TITLE
onDidChangeActiveTextEditor always reports active selection of 0,0

### ISSUE THREAD

**Issue by fvclaus** [microsoft/vscode#136618]
Does this issue occur when all extensions are disabled?: Bug is about extension API

- VS Code Version: 1.61
- OS Version: Ubuntu 20.04.3 LTS

When a user opens a new file at any position other than `(0,0)` (for example, by using `Go to definition`), `onDidChangeActiveTextEditor` will report `(0,0)` until the `onDidChangeTextEditorSelection` reaches the extension host. An extension that wants to act on the active selection has to implement a waiting logic similar to
```
onDidChangeActiveTextEditor(document => {
  // Wait a short period until an optional selection update reaches the extension host
  setTimeout(() => {
    // Execute logic here
  }, 500);
}
```
Needless to say that this is a brittle workaround, but I cannot think of any else, because the `onDidChangeTextEditorSelection` is not triggered if the document is opened at `(0,0)`.

Out of curiosity, I dug around the source code to understand where the problem is coming from. Here is my understanding:  In `textFileEditors.ts`, the `onDidChangeActiveTextEditor` event is triggered by updating the text model:
```
textEditor.setModel(textFileModel.textEditorModel);
```
The selection is updated shortly afterwards:
```
applyTextEditorOptions(options, textEditor, ScrollType.Immediate);
```
Flipping these statements around is not enough, because the selection is internally transported by an event and will not reach the code that generates the event that is sent to the extension host in time.

**Comment by jrieken** [comment]
> Needless to say that this is a brittle workaround, but I cannot think of any else, because the onDidChangeTextEditorSelection is not triggered 

Why don't you listen to the `onDidChangeTextEditorSelection`-event instead? Selection is something that can always change and that should be honored. Why do you need the exact selection after restore/open?

**Comment by fvclaus** [comment]
@jrieken If the user opens a file at `(0,0)` the `onDidChangeTextEditorSelection` is not triggered. I want to know the exact position to move the cursor to the main declaration of a Java class file when opened through `workbench.action.showAllSymbols`.  Currently this will put the cursor at `(0,0)` (selection provided by the language server). The language server cannot provide the selection for the main declaration during `workspace/symbols`, because it is too resource intensive (requires opening and parsing of all matching class files). The other way to open class files is through `Go to definition`. I need a way to distinguish between them.  I am fully aware that one could also argue that the responsiblity is on me and I need to refactor the language server to have this information available at all times.

Independently of my use case, I feel like most developer would not expect this behaviour. It seems to be a side effect of the event architecture, not an intentional decision. I would argue that vscode knows the desired position before sending the `onDidChangeActiveTextEditor` and should therefore include it.

**Comment by jrieken** [comment]
> @jrieken If the user opens a file at (0,0) the onDidChangeTextEditorSelection is not triggered.

Yes, but once the position is updated than the event is fired, right? So, you can have a "once listener" that you install when the active editor changes. 

>  I am fully aware that one could also argue that the responsiblity is on me and I need to refactor the language server to have this information available at all times.

I am not still not sure that I understand your use-case. Do you want to somehow use "go to def" when calling the "showAllSymbols" command? How is opening the document? VS Code or your extension?

**Comment by fvclaus** [comment]
I need to know when an editor is opened through `workspace/symbols`. I want to move the cursor to the line that contains the class declaration (`public class ....`). 

The problem: The user might also open a class file using `Go to definition`, in which case I don't want to move the cursor. Therefore I need a way to distinguish between the two:


`Go to definition`
- `onDidChangeActiveTextEditor`
- `onDidChangeTextEditorSelection`

`workspace/symbols`
- `onDidChangeActiveTextEditor`

With the current implementation, I need to test for the absence of the `onDidChangeTextEditorSelection` event, which can only be accomplished by waiting a certain amount of time.

Does that answer your question? If not, I can provide an extension with code to demonstrate the issue.

**Comment by jrieken** [comment]
Also, have you seen that there is [`resolveWorkspaceSymbol`](https://github.com/microsoft/vscode/blob/2c083a7bc92a86077f32a0d700c3821b76372e62/src/vs/vscode.d.ts#L3151) which is there to help delay expensive computations

**Comment by fvclaus** [comment]
> How do you know an editor is being opened though that command?

Because I am the one issuing the command

> Also, have you seen that there is resolveWorkspaceSymbol which is there to help delay expensive computations

No, I did not know that. I will look into it and report back whether or not this is a solution for my problem.

**Comment by fvclaus** [comment]
@jrieken , I looked at `resolveWorkspaceSymbol` and it seems it would solve my problem, but I cannot get it working. My implementation is never called. 
I dug around the vscode source code and found something, but I am not sure, if I am looking in the right places: Vscode seems to only call `resolveWorkspaceSymbol`, if `symbol.location.range` is falsy:
https://github.com/microsoft/vscode/blob/de17f447c348dfaab1b4a5584b070b78d813f5d1/src/vs/workbench/contrib/search/browser/symbolsQuickAccess.ts#L232-L238

I removed `range` from the symbol information:
```
    {
        "name": "StringBuilderHelper",
        "kind": 5,
        "location": {
            "uri": "jdt://contents/java.base/java.math/BigDecimal$StringBuilderHelper.class?=vscode-import-bug/%5C/home%5C/dev%5C/.sdkman%5C/candidates%5C/java%5C/11.0.11.hs-adpt%5C/lib%5C/jrt-fs.jar%60java.base=/maven.pomderived=/true=/=/javadoc_location=/https:%5C/%5C/docs.oracle.com%5C/en%5C/java%5C/javase%5C/11%5C/docs%5C/api%5C/=/%3Cjava.math(BigDecimal$StringBuilderHelper.class"
        },
        "containerName": "java.math.BigDecimal"
    }
```

This output is from `vscode-languageclient`. I verified that this actually gets passed to vscode (breakpoint in `provideWorkspaceSymbols`) and that seems to be the case:

https://github.com/microsoft/vscode-languageserver-node/blob/859a8ece3e14b130d531c6102b2d108196436bc4/client/src/common/client.ts#L1983-L2003
![symbolinformation](https://user-images.githubusercontent.com/2384738/140999028-ca10b2fe-6cfe-4796-97c7-426b09b1fa52.png)

The symbol picker does not display SymbolInformation without range information. It just shows `No matching workspace symbols`.

**Comment by jrieken** [comment]
This works for me with this provider

```ts
vscode.languages.registerWorkspaceSymbolProvider(new class implements vscode.WorkspaceSymbolProvider {
        provideWorkspaceSymbols(query: string, token: vscode.CancellationToken): vscode.ProviderResult<vscode.SymbolInformation[]> {
            return [new vscode.SymbolInformation('Hello', vscode.SymbolKind.Array, 'container hello', new vscode.Location(vscode.Uri.parse('hello:///test.txt'), undefined!))]
        }
        resolveWorkspaceSymbol(symbol: vscode.SymbolInformation) {
            console.log('resolveWorkspaceSymbol');
            return symbol
        }
    })
```

@dbaeumer Any chance this is getting lost in the lsp client lib? Returning incomplete symbol information isn't really "type correct" as strict null checks mandate all locations to have a range. Yet it still works for workspace symbol search so that lazily resolving locations while opening a symbol is supported

**Comment by fvclaus** [comment]
@jrieken I debugged around the source code and found out where the location information gets lost. `vscode-languageclient` is calling the deprecated `SymbolInformation` constructor which does not set the location (I can't see it in the debugger):

https://github.com/microsoft/vscode-languageserver-node/blob/859a8ece3e14b130d531c6102b2d108196436bc4/client/src/common/protocolConverter.ts#L816-L819

If I change this line to 
```
let result = new code.SymbolInformation(
	item.name, asSymbolKind(item.kind),
	asRange(item.location.range),
	new code.Location(item.location.uri ? _uriConverter(item.location.uri) : uri), undefined);
```
then I can see the symbols in the symbol picker and my `resolveWorkspaceSymbol` is actually called. The code should probably be updated to call the new constructor, but that looks like a bug in the constructor code:

https://github.com/microsoft/vscode/blob/042a6e36a495db9830029d87c12dd9b65c7e3b47/src/vs/workbench/api/common/extHostTypes.ts#L1094-L1110

It seems like there is a missing `else if` statement to cover `locationOrUri` being a URI

**Comment by jrieken** [comment]
That a good find. Can you file that as separate issue in the lsp-client project? /cc @dbaeumer

**Comment by fvclaus** [comment]
@jrieken I created a PR. What about the constructor? An invocation of the legacy constructor is expected to take this branch

https://github.com/microsoft/vscode/blob/042a6e36a495db9830029d87c12dd9b65c7e3b47/src/vs/workbench/api/common/extHostTypes.ts#L1105-L1107

but doesn't because the `instanceof` check fails, because `rangeOrContainer` is not definied. This is consistent with the typings which do not allow `undefined` or `null` for `range`.

**Comment by dbaeumer** [comment]
@jrieken got a PR that addresses this.

**Comment by jrieken** [comment]
ok, closing this issue than
