### ISSUE TITLE
Tab drawing glitch when icons are enabled and kick in later

### ISSUE THREAD

**Issue by sgtoj** [Microsoft/vscode#13668]
OS: Microsoft Windows [Version 10.0.14942]
Version 1.7.0-insider
Commit 5dd716eaedc5a239379013863568c7f7dea708a5
Date 2016-10-13T08:02:00.080Z
Shell 1.3.7
Renderer 52.0.2743.82
Node 6.5.0

![Tab Length Issue](http://i.imgur.com/qYpzaG2.png)

Steps to Reproduce:

1.  Open a Folder
2.  Create a file with a long name.
3.  Save the file.
4. Close VS Code
5. Launch VS Code

Note: Selecting another tab forces VS Code to correctly re-evaluate the length.

**Comment by bpasero** [comment]
This is due to the icons kicking in later and seems some weird Chrome layouting issue. Help wanted if someone has an idea.
