### ISSUE TITLE
Add a color for focused notification item.

### ISSUE THREAD

**Issue by a5hk** [microsoft/vscode#136627]
Currently the color is controlled by `list.focusBackground` which also is used other places:

![list1](https://user-images.githubusercontent.com/5412540/140657192-940a5b05-39f4-4370-8eec-8f75bf5891c6.png)

Using the same color for notifications interferes with buttons that might there. Those buttons don't have a dedicated color setting.

![list2](https://user-images.githubusercontent.com/5412540/140657303-96732724-9322-481e-9e42-66fc3b80b55e.png)

That makes `list.focusBackground` somewhat hard to use and limits the colors that can be used. Currently I think I should rely on `list.focusOutline` to create a focus indicator.

**Comment by ArturoDent** [comment]
You could play around with the button colors:

```jsonc
    "button.border": "#fff",
    "focusBorder": "#ff0000"
    // "button.foreground": "#ff0000",
    // "button.background": "#ff0000",
    // "button.hoverBackground": "#ff0000",
    // "button.secondaryForeground": "#ff0000",
    // "button.secondaryBackground": "#ff0000",
    // "button.secondaryHoverBackground": "#ff0000"
```

and/or the notification colors such as 
`notifications.background`: Notification background color.

to possibly get something better for you.
