### ISSUE TITLE
WSL Projects Freezing randomly

### ISSUE THREAD

**Issue by eastwood** [microsoft/vscode#136642]
Issue Type: <b>Bug</b>

After about 30 mins of use, VS Code freezes for some reason. I can't tell exactly what's causing it, but it doesn't seem to be extensions, I suspect it could be WSL integration on windows machine running Windows 11.

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.43.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (18.62GB free)|
|Process Argv|--crash-reporter-id 0e16580f-d3db-4461-a7a3-5240bbc062f6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.43.3-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 3600)|
|Memory (System)|15.61GB (14.40GB free)|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
cloudformation-yaml-snippets|dst|3.38.0
Lisp|mat|0.1.11
dotenv|mik|1.0.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.205.1
remote-wsl|ms-|0.58.5
material-icon-theme|PKi|4.10.0
vscode-nginx|sha|0.6.0
vim|vsc|1.21.10
vscode-ruby|win|0.28.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
material-theme|zhu|3.13.2
markdown-mermaid|bie|1.13.0
npm-intellisense|chr|1.4.0
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
cloudformation-yaml-snippets|dst|3.38.0
gitlens|eam|11.6.1
nib-commands|eas|0.0.1
vscode-npm-script|eg2|0.3.23
vscode-jest-runner|fir|0.4.47
vscode-pull-request-github|Git|0.32.0
go|gol|0.29.0
vscode-mocha-test-adapter|hbe|2.13.0
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.24.5
plantuml|jeb|2.16.0
vscode-styled-components|jpo|1.6.6
Lisp|mat|0.1.11
dotenv|mik|1.0.1
vscode-docker|ms-|1.17.0
csharp|ms-|1.23.16
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.0
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
powershell|ms-|2021.10.2
test-adapter-converter|ms-|0.1.4
material-icon-theme|PKi|4.10.0
ruby|reb|0.28.1
vscode-yaml|red|1.1.1
rust|rus|0.7.8
vscode-nginx|sha|0.6.0
org-mode|vsc|1.0.0
vscode-ruby|win|0.28.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.13.2

(8 theme extensions excluded)

</details>

**Comment by meganrogge** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.

**Comment by aeschli** [comment]
Can you describe what you mean by 'freezing'? Is the UI frozen (Mouse clicks don't have an effect)? Or the connection to WSL is lost?
Please also check if there are busy processes in Windows as well as inside WSL.

**Comment by eastwood** [comment]
Hi @aeschli - sure can.

Essentially all actions within the vscode window are ineffective; mouse clicks, keybinds etc. 
The WSL container is still active and I am able to access it via the terminal etc. It *could* be the WSL connection to windows being lost, but i'm not sure what is causing it. Usually I could "reconnect to wsl" via VSCode, but because everything is locked, I'm forced to force quit the process.

Next time it happens i'll make a recording of it to help with the process. I know i'm not the only one that's had the issue. Some other suggestions were to set the "Host Network Service" to automatic to allow it to restart correctly.

I'll also perform do a windows 11 update and see if I can continue to reproduce.

**Comment by eastwood** [comment]
Leave it with me and i'll see if I can get more information for you next time it occurs. It usually occurs about once per workday

**Comment by aeschli** [comment]
Closing the issue for now. Please reopen if you see it again.
