### ISSUE TITLE
Can I exclude the Definition and Declaration from the result of Find All Reference

### ISSUE THREAD

**Issue by iceice** [microsoft/vscode#136600]
In vscode Find All Reference always show the function self Definition and Declaration,I hope there is a method to exclude them.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"editor-symbols"
