### ISSUE TITLE
Add a possibility to use different default terminal profiles depending on OS for as in user settings

### ISSUE THREAD

**Issue by michael-motornyi** [microsoft/vscode#136686]
I am working on different machines - Windows PC and Macbook and using user sync option for syncing settings. 
I want to have ability to use Powershell on PC and bash on Macbook

**Comment by meganrogge** [comment]
you can do this with `terminal.integrated.defaultProfile.windows` and `terminal.integrated.defaultProfile.osx` and  `terminal.integrated.profiles.windows` and `terminal.integrated.profiles.osx`
