### ISSUE TITLE
Error: cannot connect to runtime process (timeout after 5000ms) when debug vscode

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode#1366]
When I want to press f5 to start debug vscode source using chrome develop tool,it throws the following error:
![mmmddd](https://cloud.githubusercontent.com/assets/15098626/11836143/a694dc44-a413-11e5-9398-4695f0652c65.png)

Anyone know what's the problem?

**Comment by dbaeumer** [comment]
@isidorn not sure if this is actually a bug. If the timeout is expected we should not have an error in the console.

**Comment by isidorn** [comment]
@dbaeumer message service is automatically loging all .show(error) also to console I believe
@BleyChen what is your chosen launch config? What are you trying to debug?

**Comment by BleyChen** [comment]
I am trying to debug suggestion Intellisense and i choose debug config option "Attach to Extension host".

**Comment by isidorn** [comment]
@BleyChen do you have the extension host running as part of a seperate app outside of VSCode? How I usually do this is run `scripts/code.sh` and then attach from VSCode. Does runnings `scripts/code.sh` say that it is listening on `port 5870` - the one specified in your `launch.json`

**Comment by egamma** [comment]
@BleyChen Also given the questions in #1319 I wonder whether you are trying to debug code that is running in the renderer process and not in the extension host. This could explain the timeout. So what is your debugging scenario and setup?

**Comment by BleyChen** [comment]
Yes , I just followed the following instruction:

Using the Chrome Developers Tools
•Run the  Developer: Toggle Developer Tools  command from the Command Palette in your development instance of Code to launch the Chrome tools.

The extension host process runs code implemented by a plugin. To debug extensions (including those packaged with Code) which run in the extension host process, you can use VS Code itself. Switch to the Debug viewlet, choose the  Attach to Extension Host  configuration, and press  F5 .

I try to debug suggestion Intellisense as following steps:
1. Open vscode source code using vscode
2. Run Chrome tools.
![21a](https://cloud.githubusercontent.com/assets/15098626/11922734/bbf1ab98-a7d4-11e5-8d37-04a6bef67f77.png)
3.Change the debug mode to "Attach to Extension host"
![21b](https://cloud.githubusercontent.com/assets/15098626/11922769/26f01240-a7d5-11e5-9998-566ea7e759ca.png)
4. Press F5 ,it will throw the Error
![21d](https://cloud.githubusercontent.com/assets/15098626/11922823/be008e30-a7d5-11e5-9cbf-3b1d5d873fa2.png)

**Comment by isidorn** [comment]
Looking at your screenshots I think you do not have a second instance of VSCode running.
In total you need 2 vscode instances - the debugger and the debugee (the one reflecting your changes).
From our [development docs](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#development-workflow) you are missing the following step it seems:
`scripts\code --remote-debugging-port=9222`

**Comment by BleyChen** [comment]
can you tell me the detail steps how to start two vscode instance , i just using the Chrome Developer Tools and the doc didn't tell me that need to using this command:  scripts\code --remote-debugging-port=9222

**Comment by isidorn** [comment]
Please check the validate your changes part of the doc
https://github.com/Microsoft/vscode/wiki/How-to-Contribute#validate-your-changes

**Comment by BleyChen** [comment]
yes ,I have checked and it says that To debug code running in the render you can either use VS Code or the Chrome Developer Tools. so I just following the instruction:
Using the Chrome Developers Tools
•Run the  Developer: Toggle Developer Tools  command from the Command Palette in your development instance of Code to launch the Chrome tools.

The extension host process runs code implemented by a plugin. To debug extensions (including those packaged with Code) which run in the extension host process, you can use VS Code itself. Switch to the Debug viewlet, choose the  Attach to Extension Host  configuration, and press  F5 .

**Comment by BleyChen** [comment]
when I run the command  "scripts\npm install" on windows 10,it throw the following error ,do you know what's the problem?



C:\Users\v-blchen\vscode>scripts\npm install
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN engine prettyjson@0.8.1: wanted: {"node":">= 0.6.0 < 0.11.0"} (current: {"node":"5.2.0","npm":"3.3.12"})

> alexandrudima-oniguruma@6.0.1 install C:\Users\v-blchen\vscode\node_modules\vscode-textmate\node_modules\alexandrudima-oniguruma
> node-gyp rebuild


C:\Users\v-blchen\vscode\node_modules\vscode-textmate\node_modules\alexandrudima-oniguruma>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0005: Failed to locate: "CL.exe". ??????????? [C:\Users\v-blchen\vscode\node_modules\vscode-textmate\node_modules\a
lexandrudima-oniguruma\build\oniguruma.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:88:13)
gyp ERR! stack     at ChildProcess.emit (events.js:173:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\v-blchen\vscode\node_modules\vscode-textmate\node_modules\alexandrudima-oniguruma
gyp ERR! node -v v5.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
Code@0.10.4 C:\Users\v-blchen\vscode
├─┬ gulp@3.9.0
│ └─┬ chalk@1.1.1
│   └── escape-string-regexp@1.0.4
├─┬ gulp-bom@1.0.0
│ └─┬ through2@2.0.0
│   └── readable-stream@2.0.5
├─┬ gulp-filter@3.0.1
│ └─┬ streamfilter@1.0.5
│   └── readable-stream@2.0.5
├─┬ gulp-minify-css@1.2.2
│ └── readable-stream@2.0.5
├─┬ gulp-sourcemaps@1.6.0
│ └─┬ strip-bom@2.0.0
│   └── is-utf8@0.2.1
├─┬ gulp-symdest@1.0.0
│ └─┬ vinyl-fs@1.0.0
│   └─┬ duplexify@3.4.2
│     └── readable-stream@2.0.5
├─┬ gulp-watch@4.3.5
│ ├─┬ anymatch@1.3.0
│ │ └─┬ micromatch@2.3.7
│ │   └── braces@1.8.3
│ └── readable-stream@2.0.5
├─┬ jsdom-no-contextify@3.1.0
│ ├─┬ htmlparser2@3.9.0
│ │ └── readable-stream@2.0.5
│ └─┬ request@2.67.0
│   └─┬ bl@1.0.0
│     └── readable-stream@2.0.5
└── sax@1.1.2

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! alexandrudima-oniguruma@6.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alexandrudima-oniguruma@6.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexandrudima-oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexandrudima-oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\v-blchen\vscode\npm-debug.log

**Comment by BleyChen** [comment]
@isidorn thanks , I can debug now.
