### ISSUE TITLE
web extension webview can't load latest content

### ISSUE THREAD

**Issue by xsro** [microsoft/vscode#136668]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-03T15:28:42.479Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.44

Steps to Reproduce:

I. download file from <https://xsro.vscode-unpkg.net/xsro/vscode-dosbox/0.1.6/extension/web/dist/index.js?target%3Dalpine-x64>
2. download zip from <https://marketplace.visualstudio.com/_apis/public/gallery/publishers/xsro/vsextensions/vscode-dosbox/0.1.6/vspackage?targetPlatform=alpine-x64> and find file in `\extension\web\dist\index.js`
3. the two should be the same, but they are different

I test with <vscode.dev> and find the web extension use file in step 1 which may be an old version. This make my extension doesn't work in browser

**Comment by joaomoreno** [comment]
I just downloaded them and verified the files are 100% the same. Can you pin point exactly the differences you see in them, with `diff`?

**Comment by xsro** [comment]
For example, in the end of the two files

<img width="882" alt="2021-11-09 10 03 18" src="https://user-images.githubusercontent.com/64292434/140937983-3cf5f3d8-1d6c-4229-bab8-88efa3b258d7.png">

**Comment by joaomoreno** [comment]
Can you redownload those URLs and verify? Cause I can't really see that difference.

**Comment by xsro** [comment]
Hello, Can you offer a screenshot of what you see?

Are they all look like the file in the right part of my screenshot, or left part?

**Comment by joaomoreno** [comment]
Interesting, I just saw the file change myself. Did you somehow republish this extension's version? I thought this wasn't supported at all.

**Comment by xsro** [comment]
I use [Github Action](https://github.com/dosasm/vscode-dosbox/actions/runs/1420443497) for publishing.

I think there are no way to republish the extension

**Comment by joaomoreno** [comment]
I see now, the problem is the URL:

- https://xsro.vscode-unpkg.net/xsro/vscode-dosbox/0.1.6/extension/web/dist/index.js?target%3Dalpine-x64
- https://xsro.vscode-unpkg.net/xsro/vscode-dosbox/0.1.6/extension/web/dist/index.js?target=alpine-x64

That `=` is being URL encoded somehow. Where did you get that URL from?

cc @sandy081

**Comment by xsro** [comment]
from develop console

<img width="1095" alt="截屏2021-11-10 下午5 50 18" src="https://user-images.githubusercontent.com/64292434/141090655-f9edcb09-9a34-41e0-9beb-1807aafbcf7f.png">

**Comment by xsro** [comment]
I find we just need to convert from `Uri` to `string` with parameter `skipEncoding=true`. 

```
var {URI} = require("vscode-uri");
const link="https://xsro.vscode-unpkg.net/xsro/vscode-dosbox/0.1.6/extension/web/dist/index.js?target=web"
const uri=URI.parse(link)
console.assert(uri.toString(true)===link)//ok
console.assert(uri.toString()===link)//wrong
console.log(link,uri.toString(),uri.toString(true))
```

Thank you very much.  Maybe it's necessary to doc about this.

**Comment by joaomoreno** [comment]
Glad to know you're unblocked here. I think the [current documentation](https://github.com/microsoft/vscode/blob/042a6e36a495db9830029d87c12dd9b65c7e3b47/src/vs/vscode.d.ts#L1397-L1414) should be enough.
