### ISSUE TITLE
Add "Open in new window" option to Explorer context menu for folders types

### ISSUE THREAD

**Issue by mahee96** [microsoft/vscode#136683]
The (file)**EXPLORER** which contains the file and folder tree structure of opened working directory **can be enhanced to have an additional context menu** **_"Open in new window" for folder types_**.

**Request reason:** when I have to open a directory which contains lot of repos, the current working directory is a reference root and I want it to be in vscode. So If I want to open a subdir containing an actual repo that I want to work on, I have to either open a new instance/window of vscode and issue open folder to the target subdir. This is at least a 2-3 step procedure and sometimes I tend to write lot of notes using vscode and a simple context menu would prove to be useful.

I understand that this could be implemented as a plugin, but for something like this which would be considered as a core part of the product, I hence request this feature to be added to the official source than a third party plugin.

**Alternatives to achieve the same motive**: 
1. Using visual elements:
 - click File on the menubar.
 - click "New Window" which is the second option.
 - now again select "Open Folder" option from the dropdown menu when selecting File in the menu bar of the opened new window.
 - choose the target dir to work with.
2. Using Terminal:
 - use "cd" command to navigate to the target dir
 - now type in "code ." to use this as working dir for the new window.
 or
 - use "code $path" to open a new window/instance using this folder as working directory.

**Constraints:**
- added **_only on explorer context menu_**
- available _**only for folders and not files**_. (makes much sense). Files can be opened in new tabs under same window.

**Changes proposed in pull request:**
- added new constants for the new context option.
- added registration of the new explorer context menu item
- added handler for the command processing of request "Open in new window"

This feature or addon should be a non intrusive and user friendly request. Please consider adding this to the official product code. 

Thanks

<img width="396" alt="vscode_explorer_context_menu_addon" src="https://user-images.githubusercontent.com/47920326/140794391-4710bcdc-405a-4690-85ba-0e7f224c1b44.png">

**Comment by gjsjohnmurray** [comment]
Maybe try this extension from @chrisdias 

https://marketplace.visualstudio.com/items?itemName=chrisdias.vscode-opennewinstance

**Comment by mahee96** [comment]
I have checked this extension earlier and it really helps with my needs, but I felt like this to be an integral function of the product and can go with the default core package without need for any extensions.

**Comment by mahee96** [comment]
@gjsjohnmurray Thanks for getting back pretty quick on this!

**Comment by gjsjohnmurray** [comment]
@mahee96 glad to have helped by referring you to the extension. You'll have seen [my comment](https://github.com/microsoft/vscode/pull/136685#issuecomment-963415768) on the PR about why I don't have high hopes of it getting merged.

**Comment by mahee96** [comment]
@gjsjohnmurray, sure I understand that the core dev team may have a different view on this request. Thanks again!

**Comment by JacksonKearl** [comment]
It's worth noting that Chris Dias (the author of the above extension) is actually part of the core dev team.
