### ISSUE TITLE
VS Code automatically Delete My Project Files!!!!!

### ISSUE THREAD

**Issue by RosterMouch** [microsoft/vscode#136723]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.61.2
- OS Version:Windows11 21H2

Steps to Reproduce:

I dont know why that: my vs code notice me to update and i close down my current window and update it.But the update programm crashed in 5 min and it says there are some other vscode progress still running.
I checkout all my process but no related to vscode,so then i hit retry button.Finally it auto close by another crashed.
I just thinking there was something wrong with my vscode bin files,then i try to reinstall it.
And,were boom.My project files were gone!!!!!!!!!!!!!!!!!!!!
Even the most weried : the project bones still there,but the source code files and the data are all gone.
So please Microsoft!I am the only vscode user among my classmates there.I really dont wanna using the f**ing jetbrains.Plz!!
Fix this bug!!!

**Comment by joaomoreno** [comment]
In which location did you install VS Code?

**Comment by RosterMouch** [comment]
> We're sorry that happened to you.
> 
> In which location did you install VS Code?

Well i have create a root folder callled Visual Studio Code in my E:/ Partition
And under it there were two folder : code config and project.
I have install it on code config and projects are storaged all code such aa ipynb notebooks and data sets.

**Comment by joaomoreno** [comment]
> And under it there were two folder : code config and project.

This is *very much not recommended*. Do not put your code inside the same folder where you have installed any application, since that application owns that folder and might just delete it.

I recommend you do this:

- `E:\Programs\Microsoft VS Code`, install VS Code here
- `E:\Code`, put your code here

This way, VS Code won't ever delete anything in `E:\Code`.

**Comment by joaomoreno** [comment]
Thanks for letting us know. Unfortunately this is as designed. In order for VS Code to automatically update itself, it must delete the old version. It will delete everything it finds within that `Microsoft VS Code` folder.

**Comment by RosterMouch** [comment]
> Thanks for letting us know. Unfortunately this is as designed. In order for VS Code to automatically update itself, it must delete the old version. It will delete everything it finds within that `Microsoft VS Code` folder.

Well why not using Incremental update to instead reinstall method although it would be let vs code cotains more data on disk.But it seems a more stable and safety update strategy.
