### ISSUE TITLE
1.62.1 - Sanity testing Windows64 server is failing

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#136753]
Sanity testing Windows server using the instructions here - https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers#macos
I'm using using VS Code 1.62.1 Stable and `ms-vscode-remote.remote-ssh@0.66.0` on macOS  and connect to Windows 11 running in a Parallels VM. This setup works fine with VS Code 1.62.0 (stable)

With VS Code 1.62.1 the remote window fails with:
<img width="1193" alt="2021-11-09_14-41-44" src="https://user-images.githubusercontent.com/1898161/140934610-d1849d89-6f35-4427-acbd-8791dee8a735.png">

**Comment by weinand** [comment]
Most likely this is a duplicate of #136743

**Comment by alexdima** [comment]
Let's track in #136743
