### ISSUE TITLE
Don't show inline suggestions when undoing/redoing

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#136764]
ghost text should show only after a keypress edit, not after Undo (*addition from @hediet) or Redo*. Here, the highlighted text is was just reinserted after an undo, but ghost text is visible after the cursor.

![](https://user-images.githubusercontent.com/28068/140601322-9cd25ff1-7a1f-4ee2-845e-880c4496c064.png)

(originally from @orph, @hsenag and @Krzysztof-Cieslak might also be interested in this)

**Comment by hediet** [comment]
Fixed by 9fbabfcd

**Comment by hediet** [comment]
@orph, @hsenag, @Krzysztof-Cieslak: Can you please verify in tomorrows insider build that it works as intended now?

**Comment by Krzysztof-Cieslak** [comment]
OK, so on current insider I'm seeing:
* If an inline suggestion is already displayed we are getting new requests after undo/redo
* If there's no inline suggestion, we won't get request after undo/redo

That seems to be good behaviour for me (but @orph should confirm if that's the behaviour he has in mind)

**Comment by orph** [comment]
Just my $0.02 but I think this feels wonderful. Thank you @hediet!
