### ISSUE TITLE
1.62.1 - Sanity testing Mac server is failing

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#136743]
- Download 1.62.1 stable bits
- Sanity testing Mac server using the instructions here - https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers#macos
- Remote window fails with too many authentication failures
`[11:41:54.426] Resolver error: Error: Too many authentication failures`
- Same error while doing remote ssh from linux and mac to mac
- Same works with 1.62.0 with the same remote SSH extension - `ms-vscode-remote.remote-ssh@0.66.0`

**Comment by alexdima** [comment]
I also get the same error when doing mac `localhost`
![image](https://user-images.githubusercontent.com/5047891/140928904-dc83a423-51f3-4614-b70f-91e2efa6dc5c.png)

**Comment by hediet** [comment]
Works on windows 32 bits, using my AAD password to authenticate:

![image](https://user-images.githubusercontent.com/2931520/140947447-3ba70d28-b5f2-4d40-8e25-6bc75eb0fc52.png)

**Comment by roblourens** [comment]
Was fixed by https://github.com/microsoft/vscode-remote-ssh/pull/154

**Comment by ZhengLiu9** [comment]
> Was fixed by https://github.com/microsoft/vscode-remote-ssh/pull/154

Having the same issue, but the above link is expired. Could you share the link that fixes this issue?

**Comment by roblourens** [comment]
That's a PR that is not publicly accessible
