### ISSUE TITLE
VSCode breaks on linux every time I upgrade, I have to downgrade from 4.11.xx to 1.62.xx version to be able to use it

### ISSUE THREAD

**Issue by yonasuriv** [microsoft/vscode#136795]
LIke said in the title, why is this happening? I don't know if it's a bug or it's something that I'm doing wrong

I'm using Parrot OS, a debian linux distro.

I've downloaded the official version from the page (1.62.1-1636111026)
But when doing sudo apt upgrade it upgrades my vscsode to 4.11.5.

**Comment by IllusionMH** [comment]
Please clarify what is 4.11.xx and how do you install it?
AFAIK latest published packages for linux are 1.62

**Comment by yonasuriv** [comment]
> Please clarify what is 4.11.xx and how do you install it? AFAIK latest published packages for linux are 1.62
> 
> Also please provide info about your system

I've downloaded the official version from the page (1.62.1-1636111026)
But when doing sudo apt upgrade it upgrades my vscsode to 4.11.5, as shown below:

`sudo apt install vscode     `                                                                          
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
**vscode is already the newest version (4.11.5).**
The following packages were automatically installed and are no longer required:
alsa-tools gstreamer1.0-pulseaudio libcmis-0.5-5v5 liblibreoffice-java libqrcodegencpp1 libunoloader-java ure-java
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

So I've to do `dpkg -i code_1.62.1-1636111026_amd64.deb` every time I do an upgrade


**dpkg: warning: downgrading code from 4.11.5 to 1.62.1-1636111026**

**Comment by chrmarti** [comment]
What do you get for running `apt-cache show code` and `apt-cache show vscode`?

**Comment by yonasuriv** [comment]
> apt-cache show code

Package: code
Priority: optional
Section: devel
Installed-Size: 265032
Maintainer: Microsoft Corporation <vscode-linux@microsoft.com>
Architecture: amd64
Version: 1.51.1-1605051630
Replaces: visual-studio-code
Provides: visual-studio-code
Depends: libnss3 (>= 2:3.26), gnupg, apt, libxkbfile1, libsecret-1-0, libgtk-3-0 (>= 3.10.0), libxss1, libgbm1
Conflicts: visual-studio-code
Filename: pool/main/c/code/code_1.51.1-1605051630_amd64.deb
Size: 65066582
MD5sum: d796f283391a446e0a0e0a5dff3eefa1
SHA1: bc71be71476e0275b2f4b1ea7bbe3cac399f77b1
SHA256: d101b6ee4445875ee115fd19ad6488a70a0780f12659602229bfb433860823cc
SHA512: 5e31b8ef7e72bf465bdb1d6cfccbed6472bfaa5ec0228b2aace8825e21ae33b739a97968dd9161553fff01a23a155cf9d1f6896d7b51130c1981279472c13beb
Description: Code editing. Redefined.
 Visual Studio Code is a new choice of tool that combines the simplicity of a code editor with what developers need for the core edit-build-debug cycle. See https://code.visualstudio.com/docs/setup/linux for installation instructions and FAQ.
Description-md5: b38f8538d3cead7a194af6aeeaf02e6a
Homepage: https://code.visualstudio.com/

> apt-cache show code

Package: vscode
Source: parrot-tools
Version: 4.11.5
Architecture: all
Maintainer: Parrot Team <team@parrotsec.org>
Installed-Size: 11
Depends: codium
Breaks: vscodium (<= 1.35)
Replaces: vscodium (<= 1.35)
Homepage: https://www.vscodium.com
Priority: optional
Section: metapackages
Filename: pool/main/p/parrot-tools/vscode_4.11.5_all.deb
Size: 4448
SHA256: 5cf5945b69786fa1bda40c5751aa94f3ff716e607d77b0acb59a418023df6d2d
SHA1: b740271bd124ec0a0b58c4a1c8afaf5d14b2bfc3
MD5sum: 1f4c9ca37c2a00cbaa8686211fe3eca7
Description: Free/Libre Open Source Software Binaries of VSCode (VSCodium)
 Transitional package. Moved to codium.
 .
 This metapackage provides the compilers, interpreters and tools
 for various programming languages.
Description-md5: 215787939154b0c971c69bb73b933587

> apt-cache show vscodium

Package: vscodium
Source: parrot-tools
Version: 4.11.5
Architecture: all
Maintainer: Parrot Team <team@parrotsec.org>
Installed-Size: 11
Depends: codium
Breaks: vscodium (<= 1.35)
Replaces: vscodium (<= 1.35)
Homepage: https://www.vscodium.com
Priority: optional
Section: metapackages
Filename: pool/main/p/parrot-tools/vscodium_4.11.5_all.deb
Size: 4436
SHA256: 2e223aed213c2c51078ca54c7711c393df3be79a43e2d54247c43d08f7bdc2ac
SHA1: 6a7e2298578592ea99bbdb2ffa631ee910aed4e7
MD5sum: 37c1fecb08b055bce2e7c474076dc2ec
Description: Free/Libre Open Source Software Binaries of VSCode
 Transitional package. Moved to codium.
 .
 This metapackage provides the compilers, interpreters and tools
 for various programming languages.
Description-md5: f10e67c721c4110c5c23713115172259

**Comment by yonasuriv** [comment]
[
![image](https://user-images.githubusercontent.com/59540565/141209154-9efb697b-e729-4622-bf22-5fcfd8c1cffa.png)
](url)

**Comment by chrmarti** [comment]
The `vscode` and `vscodium` packages are not from Microsoft. It looks like these bring in the higher version number. Try uninstalling VS Code or VS Codium.

**Comment by yonasuriv** [comment]
> The `vscode` and `vscodium` packages are not from Microsoft. It looks like these bring in the higher version number. Try uninstalling VS Code or VS Codium.

I uninstalled everything, downloaded again the package from microsoft and still getting the same problem, it upgrades to the version 4.11.5 and can't see anymore to run it

**Comment by chrmarti** [comment]
One of the Parrot packages might declare it 'replaces' `code` or maybe there is a Parrot package called `code`. See https://community.parrotsec.org/t/vscode-is-automatically-removed-when-upgrading-the-system/18884 for a related discussion.
