### ISSUE TITLE
Walkthrough content feels crammed

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#136774]
I've noticed the left column feeling a little tight in our default window size:

<img width="1024" alt="CleanShot 2021-11-09 at 10 25 34@2x" src="https://user-images.githubusercontent.com/35271042/140982769-37b39182-7c38-4554-ae86-5f2423aeeb7b.png">

And more so with the sidebar in a larger window:

<img width="1278" alt="CleanShot 2021-11-09 at 10 27 04@2x" src="https://user-images.githubusercontent.com/35271042/140982943-52103b94-7394-4b8f-9147-79f848c711d7.png">

## Proposal

Can we bump the column size from `4fr` to `5fr`?

https://github.com/microsoft/vscode/blob/9472f261093ca7a1a6ac7b07c03614db2a707b27/src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.css#L481

<img width="1024" alt="CleanShot 2021-11-09 at 10 30 22@2x" src="https://user-images.githubusercontent.com/35271042/140983414-f4fa63cd-d4ec-41cb-b625-4d3a8110be15.png">

cc @digitarald

**Comment by digitarald** [comment]
That works well for the SVG images which scale nicely. How does it work for more dense markdown content on the right though?

**Comment by misolori** [comment]
Shouldn't have too much of an impact:

<img width="1024" alt="CleanShot 2021-11-09 at 11 19 44@2x" src="https://user-images.githubusercontent.com/35271042/140990339-5917bc4a-56f3-419e-9afd-b48d0485917e.png">

**Comment by misolori** [comment]
Since this was a minor change decided to push it and test it out. Let me know what you all think after playing with it.
