### ISSUE TITLE
Pressing enter in terminal find searches backwards. 

### ISSUE THREAD

**Issue by Marsfan** [microsoft/vscode#136768]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.0
- OS Version: Windows NT x64 10.0.19042 (20H2)

When using the find functionality in the terminal, pressing <kbd>enter</kbd> moves the search to the previous item (updards) instead of to the next item (downwards), like using the find options elsewhere

Steps to Reproduce:

1. Open a terminal inside VS Code
2. Run some commands in the terminal
3. Open the find menu in the terminal using <kbd>ctrl</kbd>+<kbd>f</kbd>
4. Enter a term that occurs more than once in the terminal into the find bar
5. Press <kbd>enter</kbd> to cycle through the found occurrences of the search term

**Comment by IllusionMH** [comment]
This is intended. In terminal most recent info is at the bottom so Find highlight most recent match at the botto. <kbd>Enter</kbd> navigates to next most recent match - therefore from bottom to top.

You can change this behavior by swapping keybindings for `workbench.action.terminal.findPrevious` and `workbench.action.terminal.findNext`, however I don't think that it's possible to start matching from the top (first highlighted match will be at the bottom).
