### ISSUE TITLE
Auto Scroll in the Jupyter output

### ISSUE THREAD

**Issue by raniarielly** [microsoft/vscode#136702]
## Environment data

-   VS Code version: 1.62.0
-   Jupyter Extension version (available under the Extensions sidebar): 2021.10.1001414422
-   Python Extension version (available under the Extensions sidebar): 2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: Windows 10 pro build 19043.1288
-   Python and/or Anaconda version: Anaconda 3.8.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | N/A: local

## Expected behaviour

This follows a previous discussion: https://github.com/microsoft/vscode-jupyter/issues/1511
When running file in Interactive window, the window should auto scroll to display the last output.

## Actual behaviour

The auto scroll in the Interactive window output doesn't work properly.
I noticed that it scrolls properly if the execution time of the program is under ~1.2 seconds

## Steps to reproduce:

1. Run this code:
import time
start_time = time.time()
t=1
for i in range(100): print(i)
time.sleep(t)
print(f'\nDuration: {time.time() - start_time:.6f} seconds')

2. Change the value of "t" and run the code again. For me, when t<1.1, the auto scroll worked properly, and when t>1.3 it didn't. Values of 1.1<t<1.3 produces inconsistent results.

**Comment by amunger** [comment]
should be fixed with latest auto scroll improvements
