### ISSUE TITLE
Add .gitignore entries as exclude pattern when doing a search

### ISSUE THREAD

**Issue by tbassetto** [Microsoft/vscode#13679]
- VSCode Version: 1.6.0
- OS Version: maxOS 10.12 (16A323)

Steps to Reproduce:

1. Open a project and do a search on all files.
2. See that build artefacts are among the results.

Atom is the only text editor I know having excluding "gitignored" files and olders from the search by default, and honestly it's very smart. Most JS projects will have a `build` or `dist` or `.tmp` that will clutter any search results..

**Comment by joaomoreno** [comment]
I'd only do this behind a setting.

**Comment by bpasero** [comment]
@tbassetto use the search feature at GH please

**Comment by tbassetto** [comment]
I did, but with the wrong keywords apparently (I rewrote the title several times before posting). Duplicate of https://github.com/Microsoft/vscode/issues/78
