### ISSUE TITLE
Feature request: One-click jump to vscode.dev

### ISSUE THREAD

**Issue by curoky** [microsoft/vscode#136726]
It would be very helpful to add a button to redirect to `vscode.dev` like this [plugin](https://chrome.google.com/webstore/detail/sourcegraph/dgjhfomjieaadpoljlnidmbgkdffpack) below provided by **sourcegraph**.

![image](https://user-images.githubusercontent.com/53091022/140860879-0c84a86c-3459-4f48-b448-61139207972a.png)

When click souregraph buttom, it will goto `https://sourcegraph.com/github.com/microsoft/vscode` and we need to goto `https://vscode.dev/github/Microsoft/vscode`.

**Comment by joaomoreno** [comment]
> When click souregraph buttom, it will goto `https://sourcegraph.com/github.com/microsoft/vscode` and we need to goto `https://vscode.dev/github/Microsoft/vscode`.

That is very likely a browser extension doing that for you. Feel fre to write a browser extension which does the same for vscode.dev

**Comment by curoky** [comment]
@joaomoreno  Yes,  what I want to express is to provide an extension. Although it is a very simple extension, it can provide great convenience.

(Forgive my poor english 🙈)
