### ISSUE TITLE
The extension host has stopped unexpectedly

### ISSUE THREAD

**Issue by stephane2018** [microsoft/vscode#136720]
Issue Type: <b>Bug</b>

I get this message every time I reopen my editor "The extension host has stopped unexpectedly".

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (3.79GB free)|
|Process Argv|--crash-reporter-id 671cb189-7ff8-40ff-a463-70d6a5177bfb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (72)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
codesnap|adp|1.3.4
vscode-flutter-helper|aks|0.2.5
flutter-snippets|ale|3.0.0
auto-add-brackets|ali|0.12.0
html-class-suggestions|And|1.1.1
icons-carbon|ant|0.2.4
vscode-intelephense-client|bme|1.7.1
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.1
vscode-office|cwe|2.4.1
dart-code|Dar|3.28.0
flutter|Dar|3.28.0
vscode-markdownlint|Dav|0.45.0
vscode-faker|dee|1.5.0
githistory|don|0.6.19
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|3.1.1
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
carbon-now-sh|eri|1.2.0
prettier-vscode|esb|9.0.0
vscode-flutter-i18n-json|ess|0.28.0
pubspec-dependency-search|eve|1.1.0
vscode-todo-plus|fab|4.18.4
bloc|Fel|6.1.0
provision-lens|Foo|4.0.0
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
get-snippets|get|4.2.0
vscode-flutter-files|gor|4.1.1
complete-flutter-extension-pack|Gul|1.1.0
mayukaithemevsc|Gul|3.0.1
vscode-auto-open-markdown-preview|hnw|0.0.4
jquery-snippets|Hri|1.0.0
rest-client|hum|0.24.5
vscode-env|Iro|0.1.0
vscode-edit-csv|jan|0.6.4
pubspec-assist|jer|2.3.2
statusbarerror|Joe|0.4.0
vscode-gutter-preview|kis|0.29.0
flutter-intl|loc|1.16.0
flutter-tree|mar|1.0.0
vscode-language-pack-fr|MS-|1.62.2
awesome-flutter-snippets|Nas|3.0.2
indent-rainbow|ode|8.2.2
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.10.0
getxresources|Rau|0.1.4
phpdoc-comment-vscode-plugin|rex|1.3.0
format-html-in-php|rif|1.7.0
gi|rub|0.2.11
myci-extension|Set|0.0.3
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.6.1
php-ci|sma|0.4.2
tabnine-vscode|Tab|3.4.34
bootstrap4-vscode|the|6.1.0
todo-list|Tza|1.6.0
errorlens|use|3.4.0
highlight-matching-tag|vin|0.10.1
vscode-todo-highlight|way|1.0.5
change-case|wma|1.0.0
vscode-jumpy|wma|0.3.1
bracket-lens|wra|1.5.1
markdown-all-in-one|yzh|3.4.0
flutter-provider-snippets|Zar|1.5.0
material-theme|zhu|3.13.2
html-css-class-completion|Zig|1.20.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by stephane2018** [comment]
thanks I solved my problem by using develloper Tools which showed me the exact extension. In fact, the problem was caused by a todoList extension that always crashed when the editor loaded the extensions at startup. i just unistall it
