### ISSUE TITLE
VsCode in remote a wsl2ubuntu : Can't run yarn tasks since 1.62.1

### ISSUE THREAD

**Issue by iuliust** [microsoft/vscode#136799]
Issue Type: <b>Bug</b>

Hi everyone !
Since 1.62.1, none of my tasks can run anymore.
I'm running VSCode in windows, tied with a wsl2 ubuntu container.
Yarn is installed on my windows machine, but it can be run from the integrated linux terminal.
In the integrated terminal, yarn --help runs just fine.
But if I run a task that dose pretty much the same thing, I get the following error:
> Executing task: yarn back start --watch <

/mnt/c/Users/EXT-Julien.Teyteau/AppData/Roaming/npm/yarn: 11: exec: node: not found
Échec du lancement du processus de terminal "zsh '-c', 'yarn back start --watch'" (code de sortie : 127).

I think it may be because $wsl\Ubuntu\mnt\c is not accessible from within windows (and yarn is only installed in windows, not within Ubuntu container). Maybe it's something else. It's probably linked to a security fix.
If it's how things are supposed to run from now, what should I do to prevent that error? Am I supposed to install yarn in the container or is there a more convenient way to prevent that error?

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.43.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.64GB (13.62GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu/home/julien/programmers/Src/WebUi --crash-reporter-id 7dc5599a-5121-4310-803e-9045cdb3905e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.43.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|15.45GB (11.31GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
vscode-language-pack-fr|MS-|1.62.2
remote-containers|ms-|0.205.2
remote-wsl|ms-|0.58.5
debugger-for-chrome|msj|4.13.0
material-icon-theme|PKi|4.10.0
ng-template|Ang|13.0.0
npm-intellisense|chr|1.4.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.6.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.23
beautify|Hoo|1.5.0
angular2-switcher|inf|0.3.4
sort-typescript-imports|mic|1.4.1
vscode-docker|ms-|1.17.0
vscode-language-pack-fr|MS-|1.62.2
vsliveshare|ms-|1.0.5090
vscode-npm-scripts|tra|0.2.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by bbangert** [comment]
Just updated and yes, tasks no longer run in remote linux machine via ssh.

**Comment by Taskle** [comment]
I believe that v1.62.1 is causing serious regressions for people on WSL2 Ubuntu. I've just filed https://github.com/microsoft/vscode/issues/136809 accordingly as well.

**Comment by Fedrius** [comment]
I'm getting the same issue. I reverted back to 1.61.2 and it's working again.

**Comment by fenying** [comment]
Same here

with configuration

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build (Watching)",
            "type": "npm",
            "script": "build",
            "problemMatcher": [
                "$tsc-watch"
            ],
            "isBackground": true
        }
    ]
}
```

> `npm run build-watch` equals to `tsc --build -w $(find packages/ -type f -name tsconfig.json -exec dirname {} \\;)`

it shows error like:

```
> Executing task: npm run build-watch <

/usr/bin/bash: line 1: npm: command not found
The terminal process "bash '-c', 'npm run build-watch'" failed to launch (exit code: 127).

Terminal will be reused by tasks, press any key to close it.
```

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/136791
