### ISSUE TITLE
Auto indent on new-line broken 

### ISSUE THREAD

**Issue by amks1** [microsoft/vscode#136701]
Issue Type: <b>Bug</b>

I'm using it for Python and the auto indent suddenly broke after working well for months. When I hit enter, it's supposed to add indent based on context like a function definition or a for loop, but instead it goes back to (nearly) the beginning of the line. Sometimes it indents 2 spaces or sometimes 5. Everything seems to be ok in the settings. 

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.80GB (16.81GB free)|
|Process Argv|--crash-reporter-id a9957413-6361-4f37-8c33-4f9b5cd34d7e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-sqlite|ale|0.14.0
vscode-django|bat|1.6.0
bracket-pair-colorizer-2|Coe|0.2.1
python-preview|don|0.0.4
python-environment-manager|don|1.0.2
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.1
vscode-npm-script|eg2|0.3.23
json-tools|eri|1.0.2
pip-packages|etm|0.4.3
copilot|Git|1.7.3689
gc-excelviewer|Gra|3.0.44
Untabify|ili|0.0.2
vscode-requirements|jan|0.1.0
vsc-python-indent|Kev|1.14.2
MagicPython|mag|1.1.0
json|Mee|0.0.1
vscode-docker|ms-|1.17.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.0
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
autodocstring|njp|0.5.4
java|red|1.0.0
jinjahtml|sam|0.16.0
html5-boilerplate|sid|1.1.1
svg-preview|Sim|2.8.3
tabnine-vscode|Tab|3.4.34
vscode-counter|uct|2.3.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
jinja|who|0.0.8
jinja2-snippet-kit|Wya|2.0.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by TurnipGuy30** [comment]
I'm having the same problem.
VS version: `1.63.2 (user setup)`
OS version: `Windows_NT x64 10.0.19042`

**Comment by rebornix** [comment]
It looks like that the indentation rules for Python is not covering this case. Currently the indentation rules for  auto indent feature in VS Code is regex based, which doesn't really understand the scope (function, statement) etc. Formatting works more consistently in this scenario, so I would recommend to enable formatting on type or save. Closing this as we don't expect to get around it in the near future.
