### ISSUE TITLE
JavaScript IntelliSense

### ISSUE THREAD

**Issue by anonimo82** [microsoft/vscode#136717]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.6
- OS Version: Windows 10

Steps to Reproduce:

1. Initialize any JavaScript API (Canvas, Web Audio, etc)
2. Try to access API methods (eg, with Canvas, 2D context, try to access the context's lineTo method)

More info:
Hello everyone.
I'm looking to get this: https://pasteboard.co/c0mEEXDVf8NA.png

But I don't know which extension I need.
Usually, I get fillRect and fillStyle, among other editor dependent suggestions (they're rarely the same from editor to editor) .
Screenshot above is from DreamWeaver.

Here is my code:
https://pastebin.com/EshzzGHm

I need this on Android device (I'm using Termux with code-server, but I'm also using Visual Studio Code in Windows 10)
I tried various editors, no luck.

In truth, I have code suggestions, but they're wrong.
The only working intellisense I had is the Dreamweaver's one, but I don't want to pay ~30 €/Month for it.

Here is a screenshot of the code completion I get from VSCode https://pasteboard.co/9UOfwWAHfaNj.png

Notice the differences with the Dreamweaver's one.

Thanks in advance for any help.

**Comment by mjbvz** [comment]
Try adding a type annotation:

```js
/** @type {HTMLCanvasElement} */
var canvas = document.getElementById("myCanvas");
```

**Comment by anonimo82** [comment]
@mjbvz where shoul I put it?

**Comment by anonimo82** [comment]
Dear, you solved this issue!!!
I made it to have Canvas' API entries in code completion.
Obviously, there's not only that, but it's already a great start.

Thanks a lot!!!

**Comment by anonimo82** [comment]
@mjbvz help =)
