### ISSUE TITLE
Markdown Document links

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#136738]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=141889&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=ff86458e-371d-5daa-d7a2-208b9a858585&l=754

```
2 failing
  1) Markdown Document links
       Should navigate to markdown file in directory:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/work/1/s/extensions/markdown-language-features/out/test/documentLink.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) Markdown Document links
       Should navigate to fragment by title in file:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ '/Users/runner/work/1/s/extensions/markdown-language-features/test-workspace/a.md'
- '/Users/runner/work/1/s/extensions/markdown-language-features/test-workspace/sub/c.md'
      + expected - actual

      -/Users/runner/work/1/s/extensions/markdown-language-features/test-workspace/a.md
      +/Users/runner/work/1/s/extensions/markdown-language-features/test-workspace/sub/c.md
      
      at assertActiveDocumentUri (extensions/markdown-language-features/src/test/documentLink.test.ts:143:9)
      at Context.<anonymous> (extensions/markdown-language-features/src/test/documentLink.test.ts:83:3)

```

**Comment by bpasero** [comment]
This starts to block our insiders releases: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=142158&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=ff86458e-371d-5daa-d7a2-208b9a858585&l=695

**Comment by mjbvz** [comment]
Has anything changed in core with how editors are opened or closed. It seems like these tests only recently become flaky and I don't much relevant code changed in the md extension 

Specifically it looks like the file we are opening hasn't actually opened when the promise for it resolve. Will keep investigating but still the test if I can't make progress

**Comment by mjbvz** [comment]
Only seems to happen on Mac browser. 

Before one of the time outs I saw:

```
The Web Worker Extension Host did not start in 60s, that might be a problem. [
  'The Web Worker Extension Host did not start in 60s, that might be a problem.'
]
```

But this also happens on runs where all tests pass


Another suspicious thing is that the tests sometimes take a really long time: 

https://monacotools.visualstudio.com/Monaco/_build/results?buildId=141889&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&s=a56e7651-4213-56af-9488-c25fe636c10c&t=ff86458e-371d-5daa-d7a2-208b9a858585&l=624

On linux/windows, most of the tests take 200ms or so at most

**Comment by mjbvz** [comment]
Passes locally for me but I did have to upgrade playwright to run the tests. I ran the markdown tests about 10 times and they succeeded every time

Checked in some logging to see if I can catch a failure in CI

**Comment by bpasero** [comment]
@mjbvz yeah one thing did change: https://github.com/microsoft/vscode/commit/6ed67dd61ebbd218892b3c47008cac33da0ac899

Specifically, if from an extension you open an editor and that operation is canceled by another editor opening, the first one will fail with an error. See https://github.com/microsoft/vscode/issues/134786#issuecomment-955998745

But I am not sure this applies to your test and the change has been out very early in this month cycle and I have not seen your test failing then.
