### ISSUE TITLE
Vscode not import types and values declaration correctly when they are in same file

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#136769]
Does this issue occur when all extensions are disabled?: yes

- VS Code Version: 
Version : 1.62.0 (user setup)
Commit : b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date : 2021-11-03T15:23:01.379Z
Electron : 13.5.1
Chrome : 91.0.4472.164
Node.js : 14.16.0
V8 : 9.1.269.39-electron.0
OS : Windows_NT x64 10.0.19042

Steps to Reproduce:

1. create 2 file , examle A.ts and B.ts
2. add in file A.ts type and concret variable
3. try import in B.ts , A.ts stuff, and let vscode help you to import stuff, it will not fellow rule correctly.

---

Hi everyone, is it possible to maybe add a option to separate type and value import correctly, because this give big head hash if we use a ts rule like:
` "importsNotUsedAsValues": "error",` 

Example if we have 2 file without `import`:
test1.ts
```ts
export type helperA = any;
export const A = "Concret";
```
test2.ts
```ts
export const b:helperA = {};
const x:string = A
```
---

And we mouse hover `const x:string = A`;
Vscode will suggest fix to import value 
![image](https://user-images.githubusercontent.com/24865815/140973825-3b11f29e-2dad-4ef2-b1ea-af9e5941f14e.png)
And vscode will write for you the import, this is perfect and super productive !

result:`import { A } from './test1';`

---

After if we mouse over the second declaration
Vscode will suggest import as value in same import declaration
![image](https://user-images.githubusercontent.com/24865815/140974015-cc1acd11-fd52-465e-a873-7a29d3b703e9.png)

result:`import { A, helperA } from './test1';`

This is maybe correct but is not what we want if we use rule like
`"importsNotUsedAsValues": "error",`

---

Vscode should understand this rule and suggest **add this as type separately **
Expected result:
```ts
import { A } from './test1';
import type { helperA } from './test1';
```

---

Because actually import type and value in the same import make broken some bundler like vitejs.
Error like 
`
Uncaught SyntaxError: The requested module '/src/core/test1.ts?t=1636477934311' does not provide an export named 'Interpreters'
`
So i need to always manually change the import made by vscode, where is little waste of time ! 
or change my rule by ` "importsNotUsedAsValues": "remove"` where is not what i want !

Here related discutions that's explain this new issue.
https://github.com/evanw/esbuild/issues/1525
https://github.com/microsoft/TypeScript/issues/43393

So to make everything fine, i think **if we can maybe add a setting in vscode to say `Prefer import type and value separately` it will be nice** 

No more need to hack manually what Vscode suggest when import stuff !
I say add a new option, if for you,  because i dont know this can affect some other pattern of project, but on my side i want keep error, and allowed to import type and concret from same file 
_(i know it recommend to separate types and values, but it recommend, is not a law !)._
thanks

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with TS 4.5+?

**Comment by djmisterjon** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with TS 4.5+?

yep, 
![image](https://user-images.githubusercontent.com/24865815/141009630-0691bf04-fcc9-478b-8fca-d0d785bcf4b2.png)
if the last vscode is 1.62.0

**Comment by mjbvz** [comment]
The current insiders version is 1.63. Please test using it and also make sure the workspace version of TS is 4.5+ (not just tsc)

**Comment by djmisterjon** [comment]
> The current insiders version is 1.63. Please test using it and also make sure the workspace version of TS is 4.5+ (not just tsc)

sry , it taked me time to have a free moment.

I installed Insider and confirm the insider have same behavior with the rule `"importsNotUsedAsValues": "error",`
Vscode always merge types in values in the same import, and will make crash esBuild.
Tested on 
```
Version: 1.63.0-insider (user setup)
Commit: c1096372119bcf83b9bd8ccee96dcf266f35de76
Date: 2021-11-11T13:18:41.690Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
```
and seem ts 4.5.1-rc

![image](https://user-images.githubusercontent.com/24865815/141459535-582d5dc3-f5ab-4ae2-ab31-17b76566ff26.png)

![image](https://user-images.githubusercontent.com/24865815/141459069-72f337be-996a-40fd-a78d-72926a7bb021.png)

here a little gif also if it can help to understand what i mean with my lack of English 😁
![vscode import as type separatly](https://user-images.githubusercontent.com/24865815/141460367-0ec0b1c4-5b57-46cb-bb6a-ac385899f8eb.gif)
Thanks for all your awesome work !

**Comment by mjbvz** [comment]
Thanks for testing. As you note, the way the import is added is fine — and seems preferable in most cases to having two imports for the same file. We generally don't adapt our generic TS behavior to very specific eslint rules like this unless we get significant feedback (and the existing behavior has been in place for a while)

Therefore I'm closing this as by-design
