### ISSUE TITLE
c++ language is missing in languages

### ISSUE THREAD

**Issue by rajat9897** [microsoft/vscode#136721]
Issue Type: <b>Feature Request</b>

c++ language is missing in language type like plain text ,html,c#,c++ objective please help

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Did you follow the instructions here? 

https://code.visualstudio.com/docs/languages/cpp

**Comment by rajat9897** [comment]
C++ is missing here

**Comment by CodeCrazy-ywt** [comment]
Where is c++ missing?

**Comment by rajat9897** [comment]
![IMG20211109115832](https://user-images.githubusercontent.com/93966615/140874563-7108cf7b-05ae-4b1a-9e37-16ddf72f11c4.jpg)
![IMG_20211109_115930](https://user-images.githubusercontent.com/93966615/140874584-66039a4f-7a6b-4416-a1a4-ee60eb8b9af7.jpg)


 C++ is missing here so I can't change file type to c++

**Comment by gjsjohnmurray** [comment]
> Did you follow the instructions here?
> 
> https://code.visualstudio.com/docs/languages/cpp

Well, did you?

**Comment by rajat9897** [comment]
> > Did you follow the instructions here?
> > https://code.visualstudio.com/docs/languages/cpp
> 
> Well, did you?



Yes I have
 installed  c++ intelisence extension
Code runner

And installed mingw compiler ( it's running in command prompt)

**Comment by rajat9897** [comment]
Please reply

**Comment by chrmarti** [comment]
Try installing the C/C++ extension:
<img width="458" alt="image" src="https://user-images.githubusercontent.com/9205389/140891181-3f138626-e843-437b-afae-459577ab48f0.png">

**Comment by rajat9897** [comment]
Can any one tell me how to correct this open close state modification

**Comment by rajat9897** [comment]
I have reinstalled vs code many times

**Comment by CodeCrazy-ywt** [comment]
Seems that you haven't installed the c++ extension. Just a c++ intrllisense extension may not work.

**Comment by rajat9897** [comment]
Thanks to all I got it 
By mistake I have did some modifications in setting
I just reseted the default setting and it was done🙂🙂🙂🙂
