### ISSUE TITLE
Terminal Issue in VSCode WSL fish shell

### ISSUE THREAD

**Issue by lakshits11** [microsoft/vscode#136718]
I installed Ubuntu WSL. and Installed fish shell in it. But I am getting this in VS code terminal .

![vscode fish shell](https://user-images.githubusercontent.com/54276661/140857191-78da8103-4df1-47cf-ad2f-c5de8805cd12.PNG)

I typed hello but it shows `ello` and also it shows a h infront of coder@LAKSHIT (completely unrelated to command hello) . It just not showing things correctly in vscode terminal. In powershell, or in cmd

![cmd fish shell](https://user-images.githubusercontent.com/54276661/140857405-2ce39357-a399-4654-84d9-6886f6fd0d3b.PNG)

Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.62.0
- OS Version: Win 10

Steps to Reproduce:

1. Just install wsl ubuntu. open vscode terminal install fish. And see yourself.

**Comment by meganrogge** [comment]
can't reproduce looks similar to #122676
![recording - 2021-11-09T140405 039](https://user-images.githubusercontent.com/29464607/141012231-57982cc5-047f-4809-807c-588ea1defb45.gif)
