### ISSUE TITLE
Unable to debug extensions when being offline

### ISSUE THREAD

**Issue by f111fei** [Microsoft/vscode#13670]
- VSCode Version: 1.6.0
- OS Version: windows7

Steps to Reproduce:

1.  Create a vscode extension project.
2.  Pull off the cable to keep offine.
3.  Launch Extension (F5)

I can`t set breakpoint in my source file. 
And I find some warn information in Extension Development Host Window :
```
[Extension Host] Could not find a free port for debugging
```

I change the code in https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/ports.ts#L61

`client.connect(startPort, '127.0.0.1');`

It`s works.   fyi  @vscodeteam.

**Comment by isidorn** [comment]
Sounds like a potential PR
fyi @weinand

**Comment by bpasero** [comment]
Yeah, PR welcome.

**Comment by f111fei** [comment]
@bpasero  https://github.com/Microsoft/vscode/pull/13739

**Comment by bpasero** [comment]
@f111fei can you elaborate why your change is fixing this? If I look at the docs of `client.connect` I can see that host per default is `localhost`.  https://nodejs.org/docs/v6.3.0/api/net.html#net_socket_connect_options_connectlistener

**Comment by f111fei** [comment]
`localhost` can`t be resolved when being offline.  And fyi
https://github.com/daaku/nodejs-freeport/blob/master/lib/freeport.js

**Comment by bpasero** [comment]
@f111fei thanks
