### ISSUE TITLE
HTML word definition changed

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#13675]
- VSCode Version: 1.6.0
- OS Version:

The refactoring that turned the HTML/Razor/Handlebar mode into an extension modified the word regexp (copy paste from the JSON mode).

Before:
html & handlebars: `/(-?\d*\.\d\w*)|([^\\`\~\!\@\$\^\&\*\(\)\=\+\[\{\]\}\\\|\;\:\'\"\,\.\<\>\/\s]+)/g`
razor: `/(-?\d*\.\d\w*)|([^\`\~\!\@\$\^\&\*\(\)\-\=\+\[\{\]\}\\\|\;\:\'\"\,\.\<\>\/\s]+)/g`

The word reg exp is used for:
Populating the find widget, word proposals, intellisense replace positions.

**Comment by aeschli** [comment]
Fixed pushed to master and to release/1.6 branch.

**Comment by Tyriar** [comment]
verified * 2
