### ISSUE TITLE
vscode.html-language-features: `html.format.wrapAttributesIndentSize` does nothing

### ISSUE THREAD

**Issue by nmlgc** [microsoft/vscode#136767]
Issue Type: <b>Bug</b>

It appears that [there is no code that accesses this setting](https://github.com/microsoft/vscode/search?q=wrapAttributesIndentSize), outside the documentation?

Actual results:
- Set `""editor.defaultFormatter": "vscode.html-language-features"`
- Set `"html.format.wrapAttributes"` to `"force-aligned"` or `"aligned-multiple"`, as required by `"html.format.wrapAttributesIndentSize"`
- Format a HTML document
- Set `"html.format.wrapAttributesIndentSize"` to some integer value
- Format the HTML document again
- Nothing changes in the formatting behavior of long lines

Expected results:
- The HTML document should look different depending on the `"html.format.wrapAttributesIndentSize"` value. Preferably, wrapped attribute lines should be indented by the given fixed amount of spaces, rather than be vertically aligned to the first attribute after the opening tag.

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by aeschli** [comment]
We're using js-beautify as formatter in the background, currently as version `1.14.0`.
https://github.com/beautify-web/js-beautify/blob/main/README.md#css--html

It looks I got the description of the setting wrong. It should say *Ignored* if wrapAttributes is set to aligned.

I tested with
```html
<html>

    <body>
        <div foo=asdasdasdad bar=asdasdasdasdasds
                                   coo=asdasdasdsdads>
        </div>
    </body>

</html>
```

Settings:
```
{
        "html.format.wrapLineLength": 40,
       "html.format.wrapAttributesIndentSize": 27,
       "html.format.wrapAttributes": "force"
}
````
and can see that `wrapAttributesIndentSize` is used

**Comment by aeschli** [comment]
Verify that the settings description is now correct.
Should be: `Ignored if wrapAttributes is set to aligned.`

**Comment by rzhao271** [comment]
Nitpick: there doesn't seem to be an `aligned` option, though there do seem to be some options with "aligned" as part of the value.

**Comment by aeschli** [comment]
Yes, I think there are 3 options with 'aligned'.
I didn't want to list them all. Also the jsbeautify doc does it the same way.
