### ISSUE TITLE
Double click .ipynb files doesn't open the notebooks editor

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode#136777]
Version: 1.63.0-insider (user setup)
Commit: 93ce4397a2cbc88707c3ed8b34a813b87457568c
Date: 2021-11-09T15:23:39.737Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. In the File explorer, double click on an ipynb file

Expected: notebooks editor is opened
Actual: notebooks editor is not opened
![image](https://user-images.githubusercontent.com/26419852/140987713-16743771-fee9-4bad-b6b2-14cb4fe10277.png)

Other observations: single click and context menu "Open to the side" both works as expected.

**Comment by rebornix** [comment]
Not sure if it's a regression of any recent change in the editor area but it's a long standing issue. What happens in double click is `setInput` was called first, and notebook will ask for data from the extension host, and before it finishes, the setInput was cancelled.

**Comment by bpasero** [comment]
optimistically assuming that https://github.com/microsoft/vscode/commit/42f10bb643c63c91421a62e6fa8d08d5297dd09f fixes this, but please confirm.

**Comment by bpasero** [comment]
@ronglums can I ask you to verify whether this is fixed with our latest insider release?

You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by rebornix** [comment]
I can confirm that I don't reproduce this anymore with latest Insiders.

**Comment by rebornix** [comment]
@bpasero this is a regression/new-issue only in Insiders, right? I didn't reproduce this bug at all in Stable but you can correct me.

**Comment by ronglums** [comment]
Doesn't repro for me in Stable

Version: 1.62.1 (user setup)
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-05T10:57:55.946Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
