### ISSUE TITLE
"Configured debug type 'python' is installed but not supported in this environment" if using shellExecutionSupported in package.json

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#136712]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.62.0, 1.63.0-insider commit a7104f13f 
- Python extension version: 2021.11.1422169775 (stable), 2021.12.1436712109-dev (nightly)
- OS Version: macOS Big Sur 11.6.1

(originally reported in https://github.com/microsoft/vscode-python/issues/17952)

We recently added `shellExecutionSupported` to the `when` clause of features of the Python extension that shouldn't be exposed in virtual workspaces following the recommendation in https://github.com/microsoft/vscode-python/issues/17493#issuecomment-928986146. 

However, this now causes a `Configured debug type 'python' is installed but not supported in this environment` warning to be displayed:

![image](https://user-images.githubusercontent.com/51720070/140842790-21281e37-bd4d-4725-9dcb-23e5e00b1003.png)

Steps to Reproduce:

1. Install the Python extension (either stable or nightly/Insiders) in local VS Code
2. Activate it in a workspace with Python files
3. Go to Run and Debug and add a new debug configuration of type `Python File`
4. Open `launch.json` and note the squiggles under the configuration type.

If I remove the `&& shellExecutionSupported` part on https://github.com/microsoft/vscode-python/blob/5f46b3daf288e91e825e03adf83516f35b8cc457/package.json#L1490 and rebuild the extension, the squiggles won't appear.

**Comment by weinand** [comment]
I can reproduce this in VS Code 1.62 (Stable) and 16.3 (Insiders).
The Python debugger contribution is not enabled, which explains the squiggly in the launch.json and the missing Python entry in the "environment Quickpick":

<img width="1136" alt="2021-11-09_11-10-03" src="https://user-images.githubusercontent.com/1898161/140910298-1b5a7e82-f4aa-4443-97b1-bedd22286835.png">

However, running Python programs works fine...

The Python extension uses this when clause: `"!virtualWorkspace && shellExecutionSupported"`.
Removing the "&& shellExecutionSupported" makes it work fine.

@alexr00 I noticed that "npm tasks" are controlled by a `"when": "shellExecutionSupported"`and they don't show this issue. Is there anything that we need to do in debug land to make the `"shellExecutionSupported"`context work correctly?

**Comment by isidorn** [comment]
@weinand I have not verified that the `shellExecutionSupported` context works. I have saw that this is being used by @alexr00 and @aeschli mentioned it so I thought it makes sense for this.

**Comment by weinand** [comment]
@alexr00 Thanks, that would explain it. What should we do?

**Comment by alexr00** [comment]
@weinand is there a way you can listen for the appropriate context change and and then update your contributions? Worth noting: I named those contexts after kinds of tasks, so it feels a little strange to use them in other places.

**Comment by weinand** [comment]
@alexr00 thanks for the suggestion

I agree that it was not a good idea to recommend piggy-backing on `shellExecutionSupported` in unrelated areas...

I think we have two options now:
- tell clients (e.g. Python) to stop using `shellExecutionSupported` because it doesn't work outside of tasks (and it's semantically a stretch anyway), or
- to promote it to a first-class context key with clear semantics and fixed behavior (i.e. early initialisation).

@alexr00 @aeschli @roblourens opinions?

**Comment by marknelson** [comment]
Seeing this pop up in my launch.json is a little perplexing, I don't follow the comments above, and from what I can see, the settings seem to apply to executing in a browser maybe? My apps are server-side command line apps, so the stuff being mentioned here seems to not even be germane to me.

**Comment by weinand** [comment]
the "popup in your launch.json" is just wrong  - it's a bug in VS Code.

**Comment by jordanbui23** [comment]
I have run into this issue as well. I was following a Django tutorial on YouTube and one of the steps was to create a launch.json file and then run the debugger. It is giving me the error:

- Configured debug type 'python' is installed but not supported in this environment.

I think I am in a shell virtual environment as well if that helps. Any input would be helpful.

**Comment by Olsthoorn** [comment]
I downgraded to the previous version, which solved the problem, including crashing of integrated terminal

**Comment by jordanbui23** [comment]
@Olsthoorn that got rid of the error. Thanks for the suggestion!

**Comment by roblourens** [comment]
What are we trying to capture by using this context key? Is it, "the EH has 'real' compute"?

I see that the context key initially is false when we evaluate it to add that message to the debug adapter's schema, but becomes true later.

**Comment by weinand** [comment]
@kimadeline above you said: 
> We recently added `shellExecutionSupported` to the when clause of features of the Python extension that shouldn't be exposed in virtual workspaces following the recommendation in microsoft/vscode-python#17493 (comment).

Does this mean that the `!virtualWorkspace` when clause was not sufficient?

**Comment by alexr00** [comment]
@weinand I would opt for option 1, where `shellExecutionSupported` isn't used outside of tasks. The context is documented and suggested for task definitions as is.

**Comment by marknelson** [comment]
> the "popup in your launch.json" is just wrong - it's a bug in VS Code.

Would be nice to have some end user advice on this - right now it's all insider talk about resolution. Agreed that this is necessary but I hate having a non-empty problem list.

**Comment by weinand** [comment]
@kimadeline I agree with @alexr00 that our earlier recommendation was wrong and that the context key `shellExecutionSupported` should **not be used outside of tasks**.

I suggest that you remove the `shellExecutionSupported` from the when-clauses and publish a new version of the Python extension to the Marketplace.

If the reason for adding `shellExecutionSupported` was a problem with the `virtualWorkspace` context key, please create a new issue for this.

**Comment by weinand** [comment]
@kimadeline so `"!virtualWorkspace"` is not sufficient?

**Comment by kimadeline** [comment]
afaik `!virtualWorkspace` doesn't work when opening local folders in vscode.dev, so we added `shellExecutionSupported`.

**Comment by weinand** [comment]
@kimadeline please file a feature request for a new context key for this situation.

**Comment by aeschli** [comment]
@weinand Regardless of which content key we recommend, debug needs to listen for changes to the context key is depends on and trigger a schema update. [Example](https://github.com/microsoft/vscode/blob/a4d426a1c2ece4222f1343459d31fe948098b2f6/src/vs/platform/actions/common/menuService.ts#L77)

@kimadeline Until we conclude whether we need a new key or not, you can always define your own context key in the extension matching exactly your use case. [here](https://github.com/microsoft/vscode-remote-wsl-recommender/blob/daf4a4ca1f94d5f50c61a9bcf7277d66228557ca/src/extension.ts#L22) is an example to that.

**Comment by weinand** [comment]
@aeschli you said:
> Regardless of which content key we recommend, debug needs to listen for changes to the context key is depends on and trigger a schema update.

That shows exactly the problem: context keys are not scoped, so the Python extension can use Task's `shellExecutionSupported` context key to control a Debug contribution. We did not plan that, so we are not listening for `shellExecutionSupported` changes (and we have no intentions to do so because the semantics of `shellExecutionSupported` is not obvious for debug).

**Comment by aeschli** [comment]
@weinand The set of context variable that can be used in `when` clauses is open. But you can ask the `when` clause for the variables it contains. (`IContextKeyExpression.keys`) and listen for context key changes (`IContextKeyService.onDidChangeContext` with `IContextKeyChangeEvent.affectsSome`)

**Comment by roblourens** [comment]
We don't listen to updates for individual context keys, we just listen to any change in the context and update the schema to show or hide the warning.

**Comment by roblourens** [comment]
Sorry, needed to refresh the page before commenting

**Comment by shanewazabbas** [comment]
When does the fix get released. I had to downgrade two versions to remove the message.

**Comment by hunglnguyen** [comment]
Uninstall Jupyter, then re-install should resolve it.
<img width="398" alt="Jupyter Screenshot" src="https://user-images.githubusercontent.com/25139650/143257869-087e8f59-16d7-4b8d-ae28-705e3299e6b3.png">
er

**Comment by zchrissirhcz** [comment]
> Uninstall Jupyter, then re-install should resolve it.

So magic! Works for me. Thanks very much.

**Comment by subfuzion** [comment]
Strange, but for me I also had to uninstall and reinstall python in addition to Jupyter. In any case, uninstalling was definitely the nudge in the right direction. (Thanks @hunglnguyen)

**Comment by BrendanSimon** [comment]
Uninstalling and reinstalling Jupyter also worked for me.

```text
Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by thejoecodes** [comment]
Had to uninstall Python and Jupyter and restart VS Code. It worked! Thank you

**Comment by floatingpurr** [comment]
> Uninstalling and reinstalling Jupyter also worked for me.
> 
> ```
> Version: 1.62.3 (user setup)
> Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
> Date: 2021-11-17T08:11:14.551Z
> Electron: 13.5.2
> Chrome: 91.0.4472.164
> Node.js: 14.16.0
> V8: 9.1.269.39-electron.0
> OS: Windows_NT x64 10.0.19043
> ```

Any idea to get rid of this error without dealing with Jupyter?

**Comment by yang-yuke** [comment]
> Uninstall Jupyter, then re-install should resolve it. <img alt="Jupyter Screenshot" width="398" src="https://user-images.githubusercontent.com/25139650/143257869-087e8f59-16d7-4b8d-ae28-705e3299e6b3.png"> er

Bro, thank you so much. Your reply is the exactly one we need. It works like magic!

**Comment by Csega** [comment]
> > Uninstall Jupyter, then re-install should resolve it. <img alt="Jupyter Screenshot" width="398" src="https://user-images.githubusercontent.com/25139650/143257869-087e8f59-16d7-4b8d-ae28-705e3299e6b3.png"> er
> 
> Bro, thank you so much. Your reply is the exactly one we need. It works like magic!

Not working for me... :(

**Comment by srcolinas** [comment]
Lol, very unexpected fix
