### ISSUE TITLE
Add submenu to `View` > `Render Whitespace` with all values

### ISSUE THREAD

**Issue by rayogunjimi** [microsoft/vscode#136779]
View menu for "render whitespaces" only has a checkbox. There are 5 options for whitespace rendering: none, all, boundary, selection, trailing. When users first start VSCode the menu item is checked but it doesn't give any clues as to what is turned on. Personally, I thought it was a bug until I looked further into the settings. Could this be a dropdown menu with the 5 different options or are dropdowns only allowed for specific items?

vscode version 1.60.0

**Comment by IllusionMH** [comment]
/needsMoreInfo

You forgot to fill issue template and at least provide VS Code version.

In latest Stable build and Insiders as well it has dropdown.
![image](https://user-images.githubusercontent.com/1312662/140999464-ab921075-6e0e-4715-b1b2-fe8f1d935253.png)

**Comment by rayogunjimi** [comment]
@ill

> /needsMoreInfo
> 
> You forgot to fill issue template and at least provide VS Code version.
> 
> In latest Stable build and Insiders as well it has dropdown. ![image](https://user-images.githubusercontent.com/1312662/140999464-ab921075-6e0e-4715-b1b2-fe8f1d935253.png)

Actually, I am not talking about the settings menu but the top menu bar.  That's the part I fend confusing.
