### ISSUE TITLE
Errors from mypy/pylint lints have super tiny hitbox

### ISSUE THREAD

**Issue by Redoubts** [microsoft/vscode#136711]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.0 
- OS Version: MacOS 11.6

Steps to Reproduce:

1. Observe an error from mypy or pylint (for example)
2. Try to hover over error
3. Note that cursor has to be in a precise 1 to 2 pixel wide area at the beginning of the word to see a tooltip.

Oddly I do NOT see this with Pylance lints, I can hover over any part of the word for that

**Comment by chrmarti** [comment]
@Redoubts Could you attach a screenshot?

**Comment by Redoubts** [comment]
Attaching a movie. Pylance and MyPy show the same error, but on different lines -- mypy's squiggle is on `def` and pylance's is on the type in the line below. Note how the line below is easy to get the type hint to trigger. But it takes a lot of effort to get the popup on `def` to appear.

https://user-images.githubusercontent.com/2435101/140986594-3d4bba5a-33fe-41fe-9653-c7025f854d73.mov

**Comment by DevilXD** [comment]
This issue still appears to happen on the `1.63.0` Insiders build, for which it was supposed to be fixed: https://i.imgur.com/aFbWFIy.png

Tested using Python 3.8, latest MyPy 0.910 and fresh Insiders installation (default settings).

Is it supposed to be like this, or was this moved to `1.64.0`?

**Comment by alexdima** [comment]
@DevilXD To clarify, our fix is that you can now hover even these minuscule errors. I don't know where these errors come from or why they are so minuscule, that needs to be addressed in the extension that creates the errors. Does that match your observation as well? That despite the errors being minuscule (only 1 char wide), you can hover them?

**Comment by DevilXD** [comment]
Right, it does, it's easier to hover over them now. Is there an issue that addresses why they underline only one character then? Given that this comes from the Python extension, I'm guessing I should search there instead?

**Comment by alexdima** [comment]
@DevilXD Yes, please report directly against the extension at https://github.com/Microsoft/vscode-python/issues

**Comment by alexr00** [comment]
Marking as verified because of https://github.com/microsoft/vscode/issues/136711#issuecomment-982405050

**Comment by ahmafi** [comment]
So the extensions shouldn't show errors only on a single character? There is no way to hover over them?

**Comment by alexdima** [comment]
@ahmafi The commit https://github.com/microsoft/vscode/commit/e08f4b5bce2951e6934ea557c1d018cdaa4e483d which has made its way to Insiders 26 days ago and will make its way to Stable 1.63 in a couple of days improves the hit-box for these small hovers. So despite having a very small error squiggly, it is possible now to hover over it. Have you tried with the latest Insiders?

**Comment by ahmafi** [comment]
@alexdima I just downloaded and tested it and it's fixed. thanks.
