### ISSUE TITLE
Allow Powershell to update automatically

### ISSUE THREAD

**Issue by VashJuan** [microsoft/vscode#136782]
Its great Powershell has lots of frequent updates! I just would love to set it to auto update (others obviously may not), so I don't have to click through to the info page, then to the download page, then download and install it. With the download its a minute or two of lost productivity, every time.

I'd love to have a "Keep Powershell always up to date" option, or at least a one-click install. It currently looks like:

```
PowerShell 7.1.5
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

   A new PowerShell stable release is available: v7.2.0 
   Upgrade now, or check out the release page at:       
     https://aka.ms/PowerShell-Release?tag=v7.2.0
```

I'm on Win 10, on the Insider Edition.

**Comment by VashJuan** [comment]
Dang, I just noticed this screen during the most recent Powershell update. Maybe my answers have just been answered?! Maybe not.
![image](https://user-images.githubusercontent.com/8594671/140998207-f8089824-cc2d-4286-98a1-16e18695140b.png)

**Comment by meganrogge** [comment]
please file an issue for this in the powershell repo
