### ISSUE TITLE
diff view for large files scroll to wrong position when click on diff map panel

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#13672]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: donjayamanne.githistory-0.1.0, formulahendry.code-runner-0.3.4, slevesque.vscode-hexdump-1.0.0, waderyan.gitblame-1.3.0

Steps to Reproduce:
1. edit any large text file (15000+ lines)
2. Git / open diff view for modified file
3. click on any place of diff map panel (where we can see red/green bars)

Expected: New scroll position = position of bottom part highlighted zone of diff panel.

Actual: New scroll position = position of bottom part of scroll bar. Visually it looks like I click on scrollbar of "diff map panel", but scroll work like I click on real scrollbar, which is on nearest but another panel.

**Comment by alexandrudima** [comment]
For huge files, I agree it is a bit difficult to jump to the change using the diff overview ruler. But that is why we have the two actions to jump to next/prev change...

![13672](https://user-images.githubusercontent.com/5047891/45916569-93c77a00-be68-11e8-9495-6723efed5270.gif)
