### ISSUE TITLE
terminal closed soon after opening 

### ISSUE THREAD

**Issue by rajat9897** [microsoft/vscode#136745]

**Comment by rajat9897** [comment]
![Uploading IMG20211109160618.jpg…]()

**Comment by rajat9897** [comment]
![IMG20211109160618](https://user-images.githubusercontent.com/93966615/140915502-970664f8-f147-4dee-8b6c-171be4198684.jpg)

 Every time this message is displayed

**Comment by rajat9897** [comment]
Can any one help me

**Comment by meganrogge** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You will need to upgrade Windows to use conpty. You can read more about ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423) and [here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue).

/duplicate https://github.com/Microsoft/vscode/issues/45693
