### ISSUE TITLE
Event handler prior to disposal of webview

### ISSUE THREAD

**Issue by gcampbell-msft** [microsoft/vscode#136707]
I'm working on an extension that contains a WebView View. Currently, the WebView view uses a "when" clause in package.json that tells the WebView to be visible during debug. However, it seems to just unceremoniously kill the WebView when the debug session is closed.

The goal I have is to be able to do something, specifically in the webview, when the webview view is being closed, prior to when the webview view code is inaccessible due to having been disposed, due to VSCode leaving the "when" clause. 

Ideally, this would come in the form of a similar event handler to onDidDispose, but is invoked prior to the webview view becoming unavailable. This would allow more messages to get passed to and from the webview prior to the disposal, and thus the inaccessibility of the webview code.

**Comment by mjbvz** [comment]
I believe this is already tracked by #66842
