### ISSUE TITLE
Double clicking on a stack frame in the node debugger does not open the correct source

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#136706]
Issue Type: <b>Bug</b>

1. Debug any node based application (I'm debugging an extension to VS code, but also repros with test code)
2. Hit a breakpoint
3. Double click on a stack frame

Expected result:
Code opens and is pointing to function in stack frame

Actual result:
A window opens with the correct name, but its contents don't match the real file. It looks like the contents are from the file in the top most frame.

VS Code version: Code - Insiders 1.63.0-insider (a7104f13ff61bcd9f4c827d8fe3c0d27bb479fd8, 2021-11-08T05:14:49.440Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (16.25GB free)|
|Process Argv|--crash-reporter-id 108b1212-dd8c-4594-8252-c1351bf31268|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.0.0
remotehub|Git|0.18.0
better-cpp-syntax|jef|1.15.10
vscode-position|jtr|1.0.3
regexp-preview|Lou|0.1.5
python|ms-|2021.12.1422279751-dev
vscode-pylance|ms-|2021.11.0
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.1
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.66.0
remote-ssh-edit-nightly|ms-|2021.11.3789
remote-ssh-nightly|ms-|2021.11.3793
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.0.0
vscode-github-issue-notebooks|ms-|0.0.112
vscode-selfhost-test-provider|ms-|0.3.8
vscode-typescript-next|ms-|4.6.20211107
rpa-eslint-snippets|rav|0.0.2
rest-book|tan|4.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30382699
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsaa593:30376534
vsc1dsc:30394499

```

</details>

**Comment by rchiodo** [comment]
![stackframe](https://user-images.githubusercontent.com/19672699/140829039-605bd111-4f13-4106-8447-9613e64a6601.gif)

**Comment by bpasero** [comment]
Probably the same as https://github.com/microsoft/vscode/issues/136684
