### ISSUE TITLE
Fatal: Not possible to fast-forward, aborting

### ISSUE THREAD

**Issue by techmatlock** [microsoft/vscode#136714]
Issue Type: <b>Bug</b>

After making a commit and writing a message, the <Sync Changes> button appears in Source Control.

If I click on <Sync Changes>, I get an error in the Git log that says 'fatal: not possible to fast-forward, aborting.'

However, if I click on the 3-dot menu and push the changes, the <Sync Changes> button goes away.

I'd like to use the <Sync Changes> button to skip having to go into the menu and select <Push>.

I tried disabling my extensions (besides Python & Pylance) and the error still occurs.

It doesn't happen on my macOS, or Windows.  Only on Ubuntu.

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:18:44.904Z)
OS version: Linux x64 5.11.0-38-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor (12 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.59GB (11.82GB free)|
|Process Argv|--unity-launch --crash-reporter-id 270f98ee-2d62-4c45-84d9-99ea37b69b7b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.0
material-theme|zhu|3.13.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by lszomoru** [comment]
@techmatlock, are you using WSL or just running VSCode on Ubuntu?
Also do you have settings sync enabled across all these machines?

**Comment by techmatlock** [comment]
@lszomoru I'm just running VSCode on Ubuntu.  I just turned on settings sync for my Ubuntu machine.  It was having issues signing in using my Microsoft account, but it appears to be signed in without problems right now.

**Comment by lszomoru** [comment]
@techmatlock, and you are still experiencing the issue even after setting sync has been turned on? Thanks!

**Comment by techmatlock** [comment]
@lszomoru I also just got this settings sync error "...because of successive authentication failures" - https://imgur.com/Oilk2H0

**Comment by techmatlock** [comment]
@lszomoru I apologize.  I realized on my Mac that I was using Sync Settings with my Github account rather than my Microsoft account which was used on my Ubuntu machine.

Would this really cause a fatal error for Git though?

**Comment by ntduan** [comment]
I have the same issue. I'm having this issue on my mbp m1x. And I am not logged into any account. Using git push in the terminal is successful. But use the vscode, will get this error
```
> git pull --tags origin xxxx
From github.com:xxxxx
 * branch            xxxx       -> FETCH_HEAD
fatal: Not possible to fast-forward, aborting.
```

**Comment by JBlond** [comment]
I found out what causes the issue.
It is the order. First, you do a local commit. Then VSCode does a `git pull --tags origin BRANCHNAME`. Of cause, it can't do that, since your local branch is ahead of the remote.

this happens when you have ff only in your git settings.

```ini
[pull]
	ff = only
```

**Comment by lszomoru** [comment]
@techmatlock, can this issue be closed given this https://github.com/microsoft/vscode/issues/136714#issuecomment-964914431?

**Comment by JBlond** [comment]
@lszomoru With the last Git for windows version, this issue no longer exists even with `ff = olny` .

**Comment by JBlond** [comment]
See also https://github.com/microsoft/vscode/issues/135186 and https://github.com/microsoft/vscode/issues/135208

it was fixed in https://github.com/git/git/blob/master/Documentation/RelNotes/2.34.0.txt

I think all of these can be closed with the hint of the new Git for windows version.

**Comment by lszomoru** [comment]
Thanks for the update! Will be closing the various issues.
