### ISSUE TITLE
Service vscode.dev have not optimized for mobile devices, add some scroll.

### ISSUE THREAD

**Issue by AndreyChursin** [microsoft/vscode#136762]

**Comment by IllusionMH** [comment]
Monaco editor itself is not optimized for mobile devices if site is up to date in this matter.

> The Monaco editor is not supported in mobile browsers or mobile web frameworks.

https://microsoft.github.io/monaco-editor/

This should be implemented first before adopting VS Code UI for mobile devices.

**Comment by joaomoreno** [comment]
We're currently not targetting or supporting mobile devices for vscode.dev right now. Closing it as out of scope until we do.
