### ISSUE TITLE
Task in task.json does not auto-start in a dev container

### ISSUE THREAD

**Issue by anthonyma94** [microsoft/vscode#136715]
Issue Type: <b>Bug</b>

`tasks.json`
```javascript
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Serve API",
            "type": "shell",
            "command": "yarn nx run api:serve",
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "dedicated",
                "showReuseMessage": true,
                "clear": true
            },
            "runOptions": {
                "runOn": "default"
            },
            "problemMatcher": []
        },
        {
            "label": "Serve Client",
            "type": "shell",
            "command": "yarn nx run client:serve",
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "dedicated",
                "showReuseMessage": true,
                "clear": true
            },
            "runOptions": {
                "runOn": "default"
            },
            "problemMatcher": []
        },
        {
            "label": "Serve API & Client",
            "dependsOn": [
                "Serve API",
                "Serve Client"
            ],
            "runOptions": {
                "runOn": "folderOpen"
            },
            "problemMatcher": []
        }
    ]
}
```

**Expected behaviour**
Dev container starts and runs "Serve API & Client"

**Actual behaviour**
Dev container starts and nothing happens. No prompts to allow tasks to auto-start either.

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-89-generic
Remote OS version: Linux x64 4.19.128-microsoft-standard

**Comment by anthonyma94** [comment]
@alexr00 I noticed your fix was to wait for workspace trust. I should mention that I have that feature disabled for my VSCode. I'm also not using WSL, the data is just stored locally on my machine.

**Comment by alexr00** [comment]
Using WSL or not doesn't matter, I was testing with a dev container. 

You have `"security.workspace.trust.enabled": false`?

**Comment by anthonyma94** [comment]
Yes that's correct.

**Comment by sdegutis** [comment]
Just tried out dev containers today for the first time (they're great) but hit this bug. Will the fix be released soon?

**Comment by roblourens** [comment]
Reopening based on the comments above

**Comment by alexr00** [comment]
@sdegutis were you using VS Code Insiders?

**Comment by alexr00** [comment]
@anthonyma94 could you try out VS Code insiders and see if the issue still occurs for you?

**Comment by sdegutis** [comment]
Nope

**Comment by alexr00** [comment]
@sdegutis any chance you could try out [VS Code insiders](https://code.visualstudio.com/insiders/)? It has a fix to an issue that definitely causes auto tasks to not start. It would be great to confirm whether it's the same issue you were hitting. Insiders installs side by side with stable, so it won't impact your current set up.

**Comment by anthonyma94** [comment]
@alexr00 sorry, I removed dev containers from my workflow, I found it a little too buggy to be incorporated.

**Comment by sdegutis** [comment]
I will see if I can find time, but I'm swamped and behind on other duties.

**Comment by sdegutis** [comment]
Quick thought fwiw while I'm stuck on a problem at work: I'm looking forward to using Win15 in 2031 which somehow has containers/docker/wsl2 so deeply integrated into the system (and maybe even using new underlying tech), that it takes up literally 0 extra resources (compared to just using cmd.exe + git-bash) to do isolated dev in a linux env, as isolated/encapsulated as docker, while being no more inefficient/difficult than being just another folder on c:/

**Comment by alexr00** [comment]
Closing since we don't have anyone who's currently encountering the issue (likely fixed). Happy to open the issue back up if that changes though!
