### ISSUE TITLE
Notebook: Execute above cells not working

### ISSUE THREAD

**Issue by vrodriguezf** [microsoft/vscode#136766]
## Environment data

-   VS Code version: 1.61.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1101343141
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.20 (in a docker container)
-   Python and/or Anaconda version: 3.8.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda/docker
-   Jupyter server running: Local | Remote | N/A (Remote)

### Issue

I just cannot make the command "Notebook: Execute above cells" work. however, "Run all" and "Execute cell and below" work as expected.

**Comment by roblourens** [comment]
Works for me. What happens when you use that command?

**Comment by rchiodo** [comment]
The cell doesn't run for me.

**Comment by rchiodo** [comment]
Something like this
![image](https://user-images.githubusercontent.com/19672699/141199670-7a20cef4-7cb2-4c84-b0c1-05a6f111e34d.png)

Put focus in the second cell and run 'Execute Above Cells'

**Comment by roblourens** [comment]
It works fine for me, do you see any errors in devtools? Maybe I can show you where to debug

![Nov-10-2021 14-33-17](https://user-images.githubusercontent.com/323878/141204640-2e64e859-da3c-448c-a053-a13371c31638.gif)

**Comment by rchiodo** [comment]
Ah it works fine if I use the toolbar. Doesn't work if I use the command palette.

**Comment by vrodriguezf** [comment]
oh yes, I hadn't seen that button. It's only the command not working
