### ISSUE TITLE
Can't create a new folder in the root path (Similar to old issue #51143, but NOT) 

### ISSUE THREAD

**Issue by comtechnet** [microsoft/vscode#136751]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.  Using VSCode UI - it will NOT let u create a data folder a the project - this always results in the data folder nested in another directory
2.  Must use a poershell terminal, cd to project root then mkdir data, then copy/past my contents from prev data subdirectory and delete the prev data subdirectory

**Comment by JacksonKearl** [comment]
\gifPlease

**Comment by gjsjohnmurray** [comment]
Also

/needsMoreInfo including version and platform

**Comment by comtechnet** [comment]
The issue is/was self evident - but I do see the typos, sorry;

Steps to Reproduce:

Using VSCode UI - it will NOT let u create a data folder for the project - this always results in the data folder nested in another directory.  As a result, I must use a powershell terminal, cd to the project root directory, then mkdir data, then copy/paste my contents from prev data subdirectory and delete the prev data subdirectory.
