### ISSUE TITLE
Two notifications about Browser Preview/Live Preview even if I don't have deprecated extension.

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#136780]
Issue Type: <b>Bug</b>

In my case I saw this notification after few runs of `> Developer: Reload Window` in VS Code repo workspace (**UPD.** And now in other workspace as well).

In this case it looks excessive to show two notifications for what may look like single intention - replace one extension with another.

Moreover these notifications looks out of place as I don't have Browser Preview extension installed at this moment.

![image](https://user-images.githubusercontent.com/1312662/140996563-d73d0ae2-71df-4e45-89cc-10cd79cd53e1.png)

VS Code version: Code - Insiders 1.63.0-insider (93ce4397a2cbc88707c3ed8b34a813b87457568c, 2021-11-09T15:23:39.737Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (16.24GB free)|
|Process Argv|--crash-reporter-id cf52dbde-2c94-45c3-9bf3-45d8b9966b04|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.2.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.6.1
toggle-excluded-files|eam|1.7.0
EditorConfig|Edi|0.16.4
LogFileHighlighter|emi|2.13.0
vscode-pull-request-github-insiders|Git|2021.11.12520
rest-client|hum|0.24.5
vscode-postfix-ts|ipa|1.9.4
vscode-peacock|joh|3.10.1
fluent-icons|mig|0.0.14
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
hexeditor|ms-|1.8.2
js-debug-nightly|ms-|2021.11.417
test-adapter-converter|ms-|0.1.4
vscode-jest|Ort|4.2.1
material-icon-theme|PKi|4.10.0
markdown-pdf|yza|1.4.4

</details>

**Comment by IllusionMH** [comment]
Reproduced on fresh standalone 1.62.1
![image](https://user-images.githubusercontent.com/1312662/140999111-5365d99f-576d-4d63-90dc-e40a31b60e90.png)

**Comment by craig-seeman** [comment]
Confirming this on multiple installs, I don't believe I had ever used these extensions either. One of the tests I just did was a fresh install on mac and prompted me this immediately as well.

**Comment by digitarald** [comment]
I am sorry about the interruption and confusion caused by these notifications. This was an experiment aimed to improve deprecation flow for extensions, but which ran for too many users due to incorrect configuration.

As soon as we saw the first reports we disabled it, so nobody will get those notifications anymore.
