### ISSUE TITLE
WSL Extension instalation failure

### ISSUE THREAD

**Issue by ldobre** [microsoft/vscode#136710]
Issue Type: <b>Bug</b>

Hello,

On the latest version (1.62.0) when I try to install an extension on WSL:Ubuntu 20.04 I get an error saying that:
unable to get local issuer certificate.

On the version (1.61.2) I'm able to install the extension, even though the log show a similar error.

Pls note that this behaviour happens behind an enterprise proxy (ZScaller). I haven't tested it on a machine without it.

log for 1.61.2:
[2021-11-09 01:28:52.963] [renderer1] [error] Error while installing 'ms-python.vscode-pylance' extension in the remote server. unable to get local issuer certificate
[2021-11-09 01:28:52.963] [renderer1] [info] Downloading the 'ms-python.vscode-pylance' extension locally and install

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400H CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.61GB (2.33GB free)|
|Process Argv|--crash-reporter-id 4db86faf-d3b6-44d1-874d-99c578500e53 --crash-reporter-id 4db86faf-d3b6-44d1-874d-99c578500e53|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-10400H CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|12.17GB (9.94GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
cloudformation-yaml-snippets|dst|3.38.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.202.5
remote-wsl|ms-|0.58.5
aws-toolkit-vscode|ama|1.33.0
cform|aws|0.0.24
gitlens|eam|11.6.1
go|gol|0.29.0
vscode-cfn-lint|kdd|0.20.1
vscode-docker|ms-|1.17.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.0
jupyter|ms-|2021.9.1101343141
jupyter-renderers|ms-|1.0.3
vscode-yaml|red|1.1.1

</details>

**Comment by chrmarti** [comment]
@sandy081 Nothing changed on the certificates support side. Is there anything that has changed on the extension installation's side?

**Comment by sandy081** [comment]
Yes, I changed the fallback on the local side

In 1.62.0, I have made retry downloading (fallback) from local bit more strict and is triggered only when we see specific errors as it does not makes sense to retry if it failed for some obvious reasons.

https://github.com/microsoft/vscode/blob/5e0d7da4072cb1b7fe3be450920b0ce2f7290da5/src/vs/workbench/services/extensionManagement/electron-sandbox/remoteExtensionManagementService.ts#L61-L72

I would be interested to know what error (name) is thrown in your case. So I added a debug statement for that. Can you please try with tomorrow's insiders and let me know that.

For those users, who have connectivity issues on remote, there is a setting you can use to always download the extension locally - `remote.downloadExtensionsLocally`. I would recommend to set this setting instead of relying on fallback we have.

**Comment by sandy081** [comment]
Workaround is to set `remote.downloadExtensionsLocally` setting to `true`

**Comment by sandy081** [comment]
Reopened for candidate discussion

**Comment by sandy081** [comment]
To verify:

- From VS Code connect to (WSL/Dev Container) remote
- Open extensions view and browse for any extension that is not installed anywhere - say Python extension.
- Click on that extension to open it in the editor
- Disable internet on your machine (If you can disable internet only on remote that would be great)
- Click on install action in the extension editor
- Open the window log in the output view and make sure you can find following log statement `Downloading the '${id}' extension locally and install`. This verifies that extension is attempted to download locally and install in remote.
- If you disabled internet also on local machine, it is expected that extension installation fails
- If you could manage to disable internet only on remote then verify that extension is installed on remote.

**Comment by joaomoreno** [comment]
All good.

![image](https://user-images.githubusercontent.com/22350/141303491-7df7a3bb-e2e6-4fb8-bcb1-837441dabd53.png)
