### ISSUE TITLE
Stable Peek doesn't behave as expected

### ISSUE THREAD

**Issue by AlabasterAxe** [microsoft/vscode#136757]
Does this issue occur when all extensions are disabled?: Yes/No

## Versions:
Version: 1.62.0 (Universal)
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-03T15:24:41.297Z (5 days ago)
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Steps to Reproduce:

1. Enable `vscodevim` Extension
1. enable Stable Peek setting
1. Ctrl or cmd click a symbol to find references
1. Hit ESC in the peek window

Expected Behavior:

The peek window stays open

Observed Behavior:

The peek window closes

**Comment by jrieken** [comment]
> Enable vscodevim Extension

Does that mean it doesn't reproduce when the extension is disabled?

**Comment by AlabasterAxe** [comment]
Yeah, this looks like it's WAI if vscodevim is not enabled.
