### ISSUE TITLE
notebook cell overlapping explorer

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#136811]
![image](https://user-images.githubusercontent.com/8586769/141028246-cd162f89-a2ef-4cfc-aa54-a3d897ce09bf.png)

**Comment by rebornix** [comment]
This seems new, @JacksonKearl do you have stable reproduce? (like toggle visibility of a pane/view)

**Comment by JacksonKearl** [comment]
Pretty much a 100% repro for me, the sidebar needs to be on the right but besides that it always happens. It actually doesn't even need the explorer open, it clips the sidebar too.
![recording (1)](https://user-images.githubusercontent.com/8586769/141036504-d8077de5-ebe9-4cc1-8d13-4f3ead94db50.gif)

**Comment by rebornix** [comment]
The min width of the editor is larger than the workbench and we don't have a `overflow-x: hidden` for it. Nice catch.
