### ISSUE TITLE
Following "Your First Extension" and getting "The terminal process "C:\WINDOWS\System32\wsl.exe -d Ubuntu -e npm run watch" terminated with exit code: 1." after presisng F5

### ISSUE THREAD

**Issue by mastevb** [microsoft/vscode#136844]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62
- OS Version: Windows 11 10.0.22000.318

Steps to Reproduce:

1. Generate example `Your First Extension`  and press `F5`
2. Getting `The terminal process "C:\WINDOWS\System32\wsl.exe -d Ubuntu -e npm run watch" terminated with exit code: 1.`

I didn't change any of the code from the example extension, searched through the web, and couldn't find a solution. This problem not only happens with wsl, but also happens with all of the other terminals (Powershell, Command Prompt, etc.).

**Comment by meganrogge** [comment]
what happens if you just run `C:\WINDOWS\System32\wsl.exe -d Ubuntu` ? exit code 1 means the shell process could not be launched, likely due to having the wrong path.

**Comment by mastevb** [comment]
> C:\WINDOWS\System32\wsl.exe -d Ubuntu

Thanks for the reply, just running that code in powershell gets me into the wsl shell, no errors.

**Comment by meganrogge** [comment]
I think you have some sort of path issue
