### ISSUE TITLE
Consider tweaking verified publisher link on extension details page

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#136895]
Thoughts:

- Having a raw URL there is ugly
- Long URLs cause a horizontal scroll bar 

![image](https://user-images.githubusercontent.com/2193314/141173212-fa8f4e1e-b398-4487-91a3-c6b494baaf36.png)

cc @isidorn

**Comment by isidorn** [comment]
What I mentioned to @tyriar in our discussion:
We want to make the verified domain more visible in case the author verifies with some domain which is suspicious.
And in case the user wants to learn more about the publisher. I think it makes sense showing it.

However I do agree that on small monitors it is ugly.
@sandy081 can we at least do some elipsses so the end of the domain overflows and we do not render a scroll bar

fyi @misolori @chgill-MSFT

**Comment by misolori** [comment]
Can we just add the ellipsis and use the title to surface the full URL?

**Comment by chgill-MSFT** [comment]
I'm not sure why it's showing "www." as opposed to just the domain name... @rheajain is this something we can fix on our side or does it need to be trimmed client side?

![image](https://user-images.githubusercontent.com/15097183/141192580-3674cd55-23c1-464e-9bdb-2f5cec416b9c.png)

I'm also okay with using an ellipsis. The full domain is available on multiple tooltips including the tooltip when hovering over the domain in the list 👍

**Comment by misolori** [comment]
@chgill-MSFT I meant the title tooltip, which already shows the full URL:

<img width="323" alt="CleanShot 2021-11-10 at 13 31 55@2x" src="https://user-images.githubusercontent.com/35271042/141196734-9a155014-017b-4c50-8793-7cdb2cba2d1b.png">

**Comment by chgill-MSFT** [comment]
@misolori ah then I completely agree 🙂

**Comment by rheajain** [comment]
> I'm not sure why it's showing "www." as opposed to just the domain name... @rheajain is this something we can fix on our side or does it need to be trimmed client side?

This is something that will have to be trimmed on client side. Also, being done on Marketplace website.
This domain name was added before we had the no-subdomains (including www) check in place.
While trying to overwrite the URL with only- https://growingwiththeweb.com, I get an error when checking the URL- `The remote certificate is invalid according to the validation procedure.`
Hence, not able to remove "www" and we should not also, if it isn't secure.
@chgill-MSFT  Should we reach out to the Publisher to check if he could fix the cert for the domain?

**Comment by chgill-MSFT** [comment]
@Tyriar any idea why omitting the "www." doesn't seem to work when trying to visit your domain?

**Comment by sandy081** [comment]
Ellipsis is shown now

![image](https://user-images.githubusercontent.com/10746682/141310267-a95ce2eb-a46a-4c6e-b5b0-c9035ee04fa2.png)

**Comment by Tyriar** [comment]
@chgill-MSFT I think I only have it set up for www in dns, reasoning being I didn't know what I was doing 10 years ago.
