### ISSUE TITLE
question mark not working in code

### ISSUE THREAD

**Issue by ShaniBaddiel** [microsoft/vscode#136885]
Hi, 
I recently upgraded to Windows 11. Might be an issue with that, but I'm using VSCode and for some reason, when I try to insert a question mark within the code, it doesn't let me. any idea why and how to fix this please? 
 (Please email me to let me know)
Thank you

**Comment by gjsjohnmurray** [comment]
Please follow the advice at https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by alexdima** [comment]
@ShaniBaddiel 
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `shift+/`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by ShaniBaddiel** [comment]
Thanks.
I've tried to run the command developer but I'm not sure how to do this.
Sorry!

**Comment by gjsjohnmurray** [comment]
Please see https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette to learn about Command Palette.

Have you used the walkthroughs on the Get Started page (available from the Help menu)? Command Palette is introduced there in "Get Started with VS Code", under the section "One shortcut to access everything"

**Comment by ShaniBaddiel** [comment]
Thanks. have done like you said, thanks for your detailed explanation and
help!
this is what it returns me:
[image: image.png]
for some reason, it switches the ? with /
how do I change this?
Also, when I do / then it works fine though.
Thank you!

**Comment by alexdima** [comment]
@ShaniBaddiel Unfortunately we cannot see any image you attach via email. Could you please attach images using the UI at https://github.com/microsoft/vscode/issues/136885 ?

**Comment by ShaniBaddiel** [comment]
![image](https://user-images.githubusercontent.com/65166494/141486933-c41deb1f-c6cf-421b-915e-baf6a5b135c7.png)
hope that's better!

**Comment by ShaniBaddiel** [comment]
doesn't work for some reason, replaces ? with / 
/ works fine as it is though.

**Comment by alexdima** [comment]
@ShaniBaddiel Thank you for uploading the logs. From your screenshot, it looks like `shift+/` is not bound to any shortcut by our keybindings system, so it should result in the default browser behavior (which under the US keyboard layout would be to produce `?`).

However, extensions have a chance to intercept typing in the editor and do something else. Does the issue reproduce when disabling all extensions?

**Comment by ShaniBaddiel** [comment]
Hi
No, I actually don't have any extensions installed (to the best of my
knowledge) and it's still not working.
How can I get this to work please?
Thanks!

**Comment by alexdima** [comment]
@ShaniBaddiel What keyboard layout are you using in Windows? What happens if you open Chrome or Edge at https://vscode.dev/ . Can you type `?` using `shift+/` there?

**Comment by ShaniBaddiel** [comment]
I'm using a standard english one as far as I know!
Yes, it does work on there.
but not in the one installed.
Not sure why?
Thank you

**Comment by alexdima** [comment]
@ShaniBaddiel I also don't know why `shift+/` would not produce a `?` for you, this is the first time I've heard about such an issue. Can you please try two more inputs in VS Code:

1. Open the Settings UI (ctrl+,). Can you type `?` by pressing `shift+/` in the input box (Search Settings) over there?
    ![image](https://user-images.githubusercontent.com/5047891/142496063-20277616-7a30-4f08-b21f-1ee6704f6929.png)


2. Open the Search viewlet on the left. Can you type `?` by pressing `shift+/` in the input box (Search) over there?

    ![image](https://user-images.githubusercontent.com/5047891/142496204-e4c5f2cb-595e-4587-99a2-40656eb89dcf.png)

**Comment by ShaniBaddiel** [comment]
Hi,
Thank you for your help.
It's still not working, nothing happens when I try to do a ? in js. and in
css, it makes a comment! /* */, when I press the ?.

However, in the search bar and in the settings, it works fine.

Would you know what else I could try?
I'm wondering if maybe it's a shortcut possibly, but in js though, it
doesn't work at all.

Thank you!

**Comment by alexdima** [comment]
> nothing happens when I try to do a ? in js. and in
css, it makes a comment! /* */, when I press the ?.

This is not a feature that we have out-of-the-box.

> However, in the search bar and in the settings, it works fine

Can you please try to disable all your extensions? It looks like one of your installed extensions is intercepting the `type` command:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by ShaniBaddiel** [comment]
Tried.
It just did it once, and then it said that (since it didn't help) that
might be a problem with the code.

**Comment by alexdima** [comment]
@ShaniBaddiel Could you please take a look at your keybindings.json file? Press <kbd>F1</kbd> and then `Preferences: Open Keyboard Shortcuts (JSON)`. Are there any keybindings there? Can you share them here? Can you try commenting them out?

**Comment by ShaniBaddiel** [comment]
Great!!
it works now, thank you so much for all your help!

**Comment by alexdima** [comment]
@ShaniBaddiel Can you please share with us what was the root problem?

**Comment by ShaniBaddiel** [comment]
I removed the extensions over there, and that did the trick!
