### ISSUE TITLE
Way to detect in what current function I am currently in

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#136853]
From @jvesouza
"Is there any way in VSCode to identify the function name that contains the line being edited?"

I think it would be cool if opening the Quick Outline the current function / element that you are in would get auto selected in the quick pick.
Currently when doing Quick Outline always the first item gets selected.

**Comment by dbescr** [comment]
Hi,
isn't that already a think ? I mean you can see what function/block you are in from the top view and the outline can follow the cursor like so:

![image](https://user-images.githubusercontent.com/94051192/141104750-bf0b332d-4a44-456c-8c2b-f3ae268e1620.png)

**Comment by jrieken** [comment]
@jvesouza Did you try breadcrumbs? They always show the current function and all its containing parents. The `cmd+shift+;` keybinding will focus the breadcrumbs and its last element and therefore should also read the function you are currently in

**Comment by jvesouza** [comment]
> @jvesouza Did you try breadcrumbs? They always show the current function and all its containing parents. The `cmd+shift+;` keybinding will focus the breadcrumbs and its last element and therefore should also read the function you are currently in

Exactly what I need. It works perfectly.
Thank you very much.

**Comment by isidorn** [comment]
@jrieken feel free to close this then.
Thanks!

**Comment by jrieken** [comment]
Alright - closing. Thanks for the speedy response!
