### ISSUE TITLE
Watcher stops working when adding to the workspace a directory in a WSL2 disk

### ISSUE THREAD

**Issue by mydatamodels** [microsoft/vscode#136894]
Issue Type: <b>Bug</b>

Add to the workspace a directory in a WSL2 disk.

Notification: "File changes watcher stopped unexpectedly. Please reload the window to enable the watcher again."

nsfw logs:
[2021-11-10 19:18:13.410] [renderer1] [error] [File Watcher (nsfw)] Unexpected error: NSFW was unable to start watching that directory. (EUNKNOWN)

parcel logs:
[2021-11-10 19:18:58.604] [renderer1] [error] [File Watcher (parcel)] Unexpected error: Failed to read changes (EUNKNOWN) (path: \\wsl$\Ubuntu\home\mvm\docker\pypy)
[2021-11-10 19:18:58.606] [renderer1] [error] [File Watcher (parcel)] restarting watcher after error: Failed to read changes
[2021-11-10 19:18:58.869] [renderer1] [error] [File Watcher (parcel)] Unexpected error: Failed to read changes (EUNKNOWN) (path: \\wsl$\Ubuntu\home\mvm\docker\pypy)
[2021-11-10 19:18:58.872] [renderer1] [error] [File Watcher (parcel)] restarting watcher after error: Failed to read changes
[2021-11-10 19:18:59.078] [renderer1] [error] [File Watcher (parcel)] Unexpected error: Failed to read changes (EUNKNOWN) (path: \\wsl$\Ubuntu\home\mvm\docker\pypy)
[2021-11-10 19:18:59.081] [renderer1] [error] [File Watcher (parcel)] restarting watcher after error: Failed to read changes
[2021-11-10 19:18:59.219] [renderer1] [error] [File Watcher (parcel)] Unexpected error: Failed to read changes (EUNKNOWN) (path: \\wsl$\Ubuntu\home\mvm\docker\pypy)
[2021-11-10 19:18:59.225] [renderer1] [error] [File Watcher (parcel)] restarting watcher after error: Failed to read changes
[2021-11-10 19:18:59.357] [renderer1] [error] [File Watcher (parcel)] Unexpected error: Failed to read changes (EUNKNOWN) (path: \\wsl$\Ubuntu\home\mvm\docker\pypy)
[2021-11-10 19:18:59.361] [renderer1] [error] [File Watcher (parcel)] restarting watcher after error: Failed to read changes
[2021-11-10 19:18:59.534] [renderer1] [error] [File Watcher (parcel)] Unexpected error: Failed to read changes (EUNKNOWN) (path: \\wsl$\Ubuntu\home\mvm\docker\pypy)
[2021-11-10 19:18:59.537] [renderer1] [error] [File Watcher (parcel)] gave up attempting to restart watcher after error: Failed to read changes

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1697)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.33GB (19.99GB free)|
|Process Argv|--crash-reporter-id 50b35e8c-cd9b-421e-9cb4-1b64f9d7a0a6 --crash-reporter-id 50b35e8c-cd9b-421e-9cb4-1b64f9d7a0a6 --crash-reporter-id 50b35e8c-cd9b-421e-9cb4-1b64f9d7a0a6 --crash-reporter-id 50b35e8c-cd9b-421e-9cb4-1b64f9d7a0a6 --crash-reporter-id 50b35e8c-cd9b-421e-9cb4-1b64f9d7a0a6 --crash-reporter-id 50b35e8c-cd9b-421e-9cb4-1b64f9d7a0a6|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by bpasero** [comment]
> Add to the workspace a directory in a WSL2 disk.

Is this possible via the normal windows file explorer? Can you share steps?

**Comment by mydatamodels** [comment]
> > Add to the workspace a directory in a WSL2 disk.
> 
> Is this possible via the normal windows file explorer? Can you share steps?

Sure!

![image](https://user-images.githubusercontent.com/52713225/141275433-377d11c2-a4d6-4dcb-a9bf-3367f7049fe7.png)

Select "Open Folder"

![image](https://user-images.githubusercontent.com/52713225/141275650-16d00f9e-5e7c-4b01-ae36-20a3ac3b8f50.png)

Select a WSL2 directory

![image](https://user-images.githubusercontent.com/52713225/141275879-babef438-b7d8-4d02-a878-fdbcd79ad8e7.png)

File watcher stops no matter how many time I reload the window.

**Comment by bpasero** [comment]
You might be able to workaround this by configuring the `files.watcherExclude` to include the path you are adding.

**Comment by aeschli** [comment]
I see the same
- 10.0.22000 (Windows 11)
- latest WSL version (`wsl --status` says 'Updated on 25/10/2021, Kerner version 5.10.60.1)
- open a distro on the the user folder in the mounted windows drive:
  I reproduced with `/mnt/c/Users/martinae` and `/mnt/c/Users/martinae/AppData`
`[error] [File Watcher (parcel)] Unexpected error: Bad file descriptor (EUNKNOWN) (path: /mnt/c/Users/martinae)`

**Comment by aeschli** [comment]
Can't reproduce on my machine that runs Windows 10

**Comment by bpasero** [comment]
@aeschli @mydatamodels besides this error, is file watching working OK for the other local folders? I am having a hard time to reproduce because I cannot get that setup to work right now so please try for me.

Bottom line: it might be possible that `ReadDirectoryChangesW` does not support these special folders and then fails. We might then wrongly assume all file watching is broken when maybe only file watching for that particular folder is broken.

**Comment by mydatamodels** [comment]
It only fails for me when I open a WSL directory.

**Comment by aeschli** [comment]
No updates when I make file changes in the integrated terminal.
When the VS Code window gets the focus the explorer and editors update.

WSL2 has a known problem with watching on the  Windows mount: https://github.com/microsoft/vscode-remote-release/issues/5000. So also on Windows 10 updates don't come reliably.

**Comment by bpasero** [comment]
I verified that even with our old watcher we saw issues, though we did not report them to our users. I have filed https://github.com/microsoft/WSL/issues/7674 as upstream and see nothing VSCode can do here. As it stands, file watching will not be supported if you open `\\$wsl\` paths today.

**Comment by ropieur** [comment]
I am suffering the same issue
- Ubuntu 20.04
- VSCode 1.62.3
@bpasero , how can I investigate the root cause of the issue? Are there some log files to look at?

**Comment by ropieur** [comment]
I found the root cause in Output Log(Window)
`[2021-11-26 11:34:32.907] [renderer1] [error] [File Watcher (parcel)] Unexpected error: inotify_add_watch failed: No such file or directory (EUNKNOWN) (path: <path>)`
I don't reflect `<path>` here for privacy purpose. But I can tell that the <path> in question exists well (verified with ls command)

**Comment by gpayo** [comment]
> I found the root cause in Output Log(Window) `[2021-11-26 11:34:32.907] [renderer1] [error] [File Watcher (parcel)] Unexpected error: inotify_add_watch failed: No such file or directory (EUNKNOWN) (path: <path>)` I don't reflect `<path>` here for privacy purpose. But I can tell that the `<path>` in question exists well (verified with ls command)

I am having the same issue here.

* Ubuntu 21.10
* VSCode 1.62.3

**Comment by m3nd0r** [comment]
Same problem.

- Ubuntu 21.10
- VSCode 1.62.3

**Comment by gabrielDonnantuoni** [comment]
> Update:
The problem has been solved by deleting folder without enough permissons from workspace.

Thanks a lot for this update, @m3nd0r .
It solve for me too.
