### ISSUE TITLE
[only repros on v1.62.1] WSL2 Ubuntu: git commands and UI are unresponsive

### ISSUE THREAD

**Issue by Taskle** [microsoft/vscode#136809]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.1
- OS Version: WSL2, 

Note that this may be also causing https://github.com/microsoft/vscode/issues/136799 (not sure, just a hypothesis) as I am also on wsl2 ubuntu.

Steps to Reproduce:
1. Upgrade to v1.62.1 on WSL2, Windows 11, Ubuntu.
2. Type "git pull" in the VSCode terminal (or click the refresh icon in the bottom status bar to git pull via the UI).
3. Observe no response, just a hanging command (or, if done via the status bar click, observe the loading icon you clicks is permanently stuck loading).

When downgrading back to v1.61.2 this does not repro. I've downgraded and upgraded and consistently reproduce this issue only on the latest VSCode.

Note that using git pull via a WSL terminal window (not using VScode) does not reproduce this issue.

**Comment by cyberbiont** [comment]
Probably related: I'm getting an error trying to make a commit via Git viewlet, when husky pre-commit hook is active:
```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
/mnt/c/Program Files/nodejs/npm: 11: exec: node: Permission denied
husky - pre-commit hook exited with code 126 (error)
```

Making commit via command line works normally
Downgrade to 1.61.2 solves the problem

**Comment by chrichts** [comment]
I have the same setup as @Taskle (V1.62.1 on WSL2, Ubuntu) but on Windows 10 and I am having the same issue. 
Downgrade to 1.61.2 solves the problem for me.

Not sure this is only a git issue. I am also unable to run `npm start` and it crashes with a memory error on V1.62.1 but works fine on V1.61.2. 

Unable to find anything in the logs that could be causing the issue, but happy to help debug if there are specific things I can look at.

**Comment by rozpuszczalny** [comment]
Same issues here (1.62.1 on Windows 10 with WSL2 Ubuntu 20.04). I'm using `zsh` shell, when I'm trying to run a shell task from VSCode, that were working on 1.61.2, now are failing with `exited with code 127`, with details like `npm not found` or `ionic not found` . If I open the terminal manually, I am able to run `npm -v` and `ionic -v` without a problem.

For now, as a workaround, I'm using 1.61.2.

**Comment by chrmarti** [comment]
Tracked as https://github.com/microsoft/vscode/issues/136837.

**Comment by PaulCorbeau** [comment]
Same issue for me, (1.62.1 Windows 10, WSL 2 Ubuntu 20.04 and debian)
Git pull / push are stuck without any error messages.
I found that if you disable the extension @builtin : Git and Github I'm able to use again the git Pull/push

**Comment by iSar44** [comment]
same here (VSCode v1.62.1, Win10, WSL2, Debian  #10)
VSCode's GUI as well as git's CLI **aren't working at all**, i really hope this gets resolved asap..
