### ISSUE TITLE
Slow visual studio insiders

### ISSUE THREAD

**Issue by Dovernh** [microsoft/vscode#136860]
Issue Type: <b>Bug</b>

open visual code insiders and it takes several seconds to do anything including typing. Get a modal saying window is not responding. I disabled all extensions, no change. I uninstalled and reinstalled, no change. visual code stable works fine. see this error in console

console.ts
![image](https://user-images.githubusercontent.com/1800249/141122005-fa71c4b3-f331-45be-a4b5-2e3dde6bb5c9.png)

VS Code version: Code - Insiders 1.63.0-insider (bef4dba21f68bbdb8d9f08fe04b2e1858597722b, 2021-11-10T07:59:05.913Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (5.52GB free)|
|Process Argv|--crash-reporter-id 3a5a4d2f-39da-4ebe-a72c-db9473acc309|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30382699
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsaa593:30376534
vsc1dst:30396469
vsena315:30395853

```

</details>

**Comment by chrmarti** [comment]
Please follow these instructions: https://github.com/Microsoft/vscode/wiki/Performance-Issues#sluggish-ui

**Comment by Dovernh** [comment]
this morning things r back to normal
