### ISSUE TITLE
[themes] Selecting theme from marketplace using the color theme picker doesn't set it

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#136887]
https://user-images.githubusercontent.com/35271042/141159948-b12d0eab-f7fa-4ea7-93d0-3cf6be550249.mp4

Steps to Reproduce:

1. Open new instance of VS Code (web or desktop)
2. Change themes
3. Select a theme that is from the marketplace
4. :bug: Extension is installed but is not set

Appears to flash for a second. Subsequent installs do set this, so this is just for the first initial install.

**Comment by aeschli** [comment]
Fixed with the latest changes
