### ISSUE TITLE
Display test message/stack trace in panel

### ISSUE THREAD

**Issue by baincd** [microsoft/vscode#136812]
The error of a failed test can only be displayed in the peek window of the editor for the test class.  When viewing a different file, the error is no longer visible.

For errors like Java stack traces, it would be helpful if there was a way to display the stack trace in the panel (either in the Debug Console or in an Output panel) so the stack trace can still be displayed while viewing different files when researching the cause of the test failure.

**Comment by connor4312** [comment]
You can always click the "open" icon in the top right corner of the peek to open the message in a dedicated editor:

![image](https://user-images.githubusercontent.com/2230985/141149760-9f6fc408-56f6-4c94-9d43-1cbf6872659a.png)

Does that solve what you're after?

**Comment by baincd** [comment]
Hi @connor4312,

Thank you for pointing out the "open" icon now available in VS Code.  This kind of solves the issue - it opens the stack trace in a separate editor (yay!), but as markdown which makes it more difficult to consume (boo).  Should it be opening in a markdown preview editor instead? 

![image](https://user-images.githubusercontent.com/5075659/144728469-4e648843-3a44-4a64-af8c-084b00226365.png)

**Comment by connor4312** [comment]
I'm working on solving that in https://github.com/microsoft/vscode/issues/138389#issuecomment-993832313, I'll close this as a dupe!
