### ISSUE TITLE
Enable extentsion after use --disable-extension in CLI

### ISSUE THREAD

**Issue by hxse** [microsoft/vscode#136847]
When i use --disable-extension in CLI, the extentsoin is not can be enabled, until restart VSC. Is very confusing.
And this function is very useful:
https://github.com/microsoft/vscode/issues/39272#issuecomment-964975395

**Comment by chrmarti** [comment]
Have you tried enabling it from the Extensions viewlet in the VS Code window?

**Comment by hxse** [comment]
> Have you tried enabling it from the Extensions viewlet in the VS Code window?
Yes, That's enabled in the  Extensions viewlet.

**Comment by sandy081** [comment]
Yes, this is designed. When disabled from CLI one cannot change it from UI.
