### ISSUE TITLE
"Session contents restored…" date shown in US format

### ISSUE THREAD

**Issue by krzysztofjeziorny** [microsoft/vscode#136855]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.1
- OS Version: MacOS 11.6.1

Steps to Reproduce:

1. open the integrated terminal
2. quit VSCode
3. launch VSCode again
4. the "Session contents restored from" shows the date in US format ("11/5/2021 at 1:10:47 PM") ignoring the OS's region settings (Austria in my case, with UK English set as user's language)
5. changing the user's language (i.e. to German to reflect the region) doesn't fix the format, just changes the language of the message ("Sitzungsinhalte aus 11/10/2021 um 1:26:09 PM wiederhergestellt")

<img width="513" alt="Screenshot 2021-11-10 at 11 57 57" src="https://user-images.githubusercontent.com/872730/141113073-6d90e4c6-0343-46fb-a1a6-62854e7a2bf6.png">

**Comment by stacklast** [comment]
I have the same Issue:
- Windows 11 Home
   - Version: 21H2
   - Compilation: 22000.318
- VS Code Version: 1.62.1

The same steps to reproduce.

**Comment by Tyriar** [comment]
Hmm this is actually already using locale to string, I guess that means Electron's locale isn't set based on the system 🤔 

https://github.com/microsoft/vscode/blob/950e89beacff64928098d513b590a80401f42e2e/src/vs/platform/terminal/node/ptyService.ts#L140

**Comment by Tyriar** [comment]
This is working fine for me on Windows:

![image](https://user-images.githubusercontent.com/2193314/141484325-37c136e2-b825-430c-9b3c-e57473a2a222.png)
![image](https://user-images.githubusercontent.com/2193314/141484411-98240b3e-ba85-496d-936d-d7585b830b9d.png)

**Comment by Tyriar** [comment]
I can reproduce on macOS despite having Australia set in Region and `"locale": "en-gb"` in runtime arguments. @deepak1556 @TylerLeonhardt any idea why `Date.toLocaleDateString` isn't respecting the locale on mac?

**Comment by deepak1556** [comment]
@Tyriar this issue might have the same root cause as https://github.com/microsoft/vscode/issues/85675, locale being broken in `ELECTRON_RUN_AS_NODE` processes.

**Comment by Tyriar** [comment]
@deepak1556 ah ok this makes sense as the date is formatted on the pty host. We might be able to format the date on the renderer to work around this.

**Comment by Tyriar** [comment]
Actually, let's pass the locale over from the renderer process when reviving processes:

https://github.com/microsoft/vscode/blob/cd66eec870313c3a4cccc5932a5d9def6b385cb6/src/vs/platform/terminal/node/ptyService.ts#L125-L141

**Comment by JacksonKearl** [comment]
verified, only the most recent message has "hot swapping", but I think that's roughly expected.

![image](https://user-images.githubusercontent.com/8586769/151633127-d3296fac-acdd-4548-be7e-8ae0403faad2.png)

**Comment by Tyriar** [comment]
Yep after it's written to the terminal it's fixed text and won't change just like the rest of the buffer
