### ISSUE TITLE
Extenciones

### ISSUE THREAD

**Issue by ferhira** [microsoft/vscode#136806]
Issue Type: <b>Bug</b>

I cannot install the extensions in WSL, error getaddrinfo EAI_AGAIN ritwickdey.gallery.vsassets.io

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.13GB free)|
|Process Argv|--crash-reporter-id e31b8fed-0676-4355-91ba-159cb29e7b46|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz (4 x 2207)|
|Memory (System)|3.77GB (3.46GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-firefox-debug|fir|2.9.4
auto-rename-tag|for|0.1.9
fluent-icons|mig|0.0.14
vscode-language-pack-es|MS-|1.62.2
remote-wsl|ms-|0.58.5
material-icon-theme|PKi|4.10.0
open-in-browser|tec|2.0.0
material-theme|zhu|3.13.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by CodeCrazy-ywt** [comment]
Google:
I cannot install the extensions in WSL, error getaddrinfo EAI_AGAIN ritwickdey.gallery.vsassets.io

**Comment by chrmarti** [comment]
What do you get for running `nslookup ritwickdey.gallery.vsassets.io` in WSL? This looks like a local DNS configuration issue.

**Comment by ferhira** [comment]
> What do you get for running `nslookup ritwickdey.gallery.vsassets.io` in WSL? This looks like a local DNS configuration issue.

It appears ";; connection timed out; no servers could be reached"

**Comment by chrmarti** [comment]
This is not an issue with VS Code then. Please check your WSL distro's DNS configuration.
