### ISSUE TITLE
Feature Request: Incremental TypeScript Building/Transpiling

### ISSUE THREAD

**Issue by tonyeung** [Microsoft/vscode#13687]
Add task option: JS files are created/recreated only when the corresponding TS file has been added/modified.

In the meantime, I will be trying out the "Incremental build support using the language services" section of  [using the compiler api](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) instead of the built in typescript task.

Let me know if I there's anything I can do to help this along. If its a PR, I'm going to need a bit of help going through the PR process.

**Comment by waderyan** [comment]
@tonyeung thank you for opening this issue. 

@dbaeumer can you guide me in the direction of where to send this? Is this a task issue? Is this a language service issue?

**Comment by dbaeumer** [comment]
This is a tsserver issues. Will land in TS in 2.1. I made a PR for them a while ago to support this. So close as dup somewhere in TS land :-)

**Comment by waderyan** [comment]
@dbaeumer great thanks!
