### ISSUE TITLE
Intellisense CPU usage high

### ISSUE THREAD

**Issue by h0rdak** [Microsoft/vscode#1368]
Whenever I use intellisense in my C# projects, the CPU usage spikes and makes my fans go crazy and my laptop unbearably hot to the point it's completely unusable.

This is with vs code 0.10.3 on OSX 10.10.5, on a macbook pro. 

![screenshot 2015-12-16 09 46 20](https://cloud.githubusercontent.com/assets/7004085/11836275/e1181bcc-a3d9-11e5-81f0-89ce53df1292.png)

Activity monitor points to vs code -> electron helper -> mono-sgen

![screenshot 2015-12-16 09 44 49](https://cloud.githubusercontent.com/assets/7004085/11836260/c131ab52-a3d9-11e5-973c-fba72f7b4423.png)

Installed mono is:

Mono JIT compiler version 4.2.1 (Stable 4.2.1.102/6dd2d0d Wed Dec  2 14:02:16 PST 2015)

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#367
