### ISSUE TITLE
C# syntax highlighting broken by file-scoped namespace

### ISSUE THREAD

**Issue by jtlowe** [microsoft/vscode#136886]
Syntax highlighting does not work properly when using a file-scoped namespace. It is not consistent with the highlight coloring used for namespace blocks.

![image](https://user-images.githubusercontent.com/766226/141156818-6c7a61ed-46d6-4b4b-a8a7-e1ddb6ea5b1b.png)

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.1
- OS Version: Windows 10 and macOS 12

I have version v1.23.16 of Microsoft's C# extension installed.

Sample code:
```csharp
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Caching.Memory;

namespace App;

public class CachingService
{
    IMemoryCache _mCache;
    IDistributedCache _dCache;

    public CachingService(IMemoryCache mCache, IDistributedCache dCache)
    {
        _mCache = mCache ?? throw new ArgumentNullException(nameof(mCache));
        _dCache = dCache ?? throw new ArgumentNullException(nameof(dCache));
    }
}


namespace App
{
    public class CachingService
    {
        IMemoryCache _mCache;
        IDistributedCache _dCache;

        public CachingService(IMemoryCache mCache, IDistributedCache dCache)
        {
            _mCache = mCache ?? throw new ArgumentNullException(nameof(mCache));
            _dCache = dCache ?? throw new ArgumentNullException(nameof(dCache));
        }
    }
}
```

**Comment by GabenGitHub** [comment]
I have the same issue. In Visual Studio 2022 the highlight is correct, but in vscode is broken.

**Comment by chrmarti** [comment]
This seems to be fixed in VS Code Insiders. Could you give that a try: https://code.visualstudio.com/insiders/

**Comment by deckerbd** [comment]
I'm noticing highlighting differences as well when using file-scoped namespace and records.

VS Code (1.62.1):
![image](https://user-images.githubusercontent.com/2205008/141364461-c87899cb-bb27-4921-a9f1-eb826f5e8ef8.png)

VS Code Insider (Version: 1.63.0-insider (Universal) commit: c1096372119bcf83b9bd8ccee96dcf266f35de76):
![image](https://user-images.githubusercontent.com/2205008/141364959-2178c559-68ae-4f6d-9845-79f8b3744d5a.png)

VS 2022 for Mac Preview (17.0 Build 4172):
![image](https://user-images.githubusercontent.com/2205008/141364790-10d8cbe7-242b-4ad2-b641-af7b707fe2c5.png)

Code snippet used:
```csharp
namespace MyTestNamepace;

public record MyRecord(int Id, string GivenName, string? MiddleName, string Surname);
```

**Comment by jtlowe** [comment]
@chrmarti Yes, the latest Insider version appears to fix this. Thank you very much!

I get the same result as @deckerbd while using positional syntax for records and structs with the latest Insider, even when placed in a namespace block.

**Comment by chrmarti** [comment]
Thanks, closing as fixed.
