### ISSUE TITLE
Should not highlight object properties - it's not a reserved word

### ISSUE THREAD

**Issue by ericmdantas** [Microsoft/vscode#13682]
- VSCode Version: 1.6.0
- OS Version: Windows 7

Steps to Reproduce:

This is about javascript and typescript.

- Create the following object: 
```js
let myObj = {
  in: '123', 
  of: '9876',
  delete: () => {},
  instanceof: false,
  as: '',
  is: 'something',
  new: () => {},
  typeof: '',

  yo: '!'
}
```

- Try to access any of the props of `myObj` and all of them, but `yo`, will be highlighted as a reserved word.

```js
myObj.in // highlights 'in', as a reserved keyword
myObj.instanceof // highlights 'instanceof', as a reserved keyword
// and on and on
myObj.yo // works properly
```

- Just as a comparison, atom doesn't highlight any of those properties.

**Comment by ericmdantas** [comment]
Regex that'll have to be fixed:

https://github.com/Microsoft/vscode/blob/master/extensions/javascript/syntaxes/JavaScript.tmLanguage.json#L256,

https://github.com/Microsoft/vscode/blob/master/extensions/typescript/syntaxes/TypeScript.tmLanguage.json#L275

and

https://github.com/Microsoft/vscode/blob/master/extensions/typescript/syntaxes/TypeScriptReact.tmLanguage.json#L255


I'm going to prepare a PR.

**Comment by waderyan** [comment]
@ericmdantas we have created a new grammar that is in beta right now? Can you try it from the [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) to see if it resolves your issue? 

If it doesn't resolve your issue please open an issue / PR on the [grammar's repo](https://github.com/Microsoft/TypeScript-TmLanguage)

**Comment by ericmdantas** [comment]
@waderyan it's working as expected, thanks!
