### ISSUE TITLE
terminal not working

### ISSUE THREAD

**Issue by wadjih-bencheikh18** [microsoft/vscode#136800]
Issue Type: <b>Bug</b>

terminal not working

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.90GB (5.49GB free)|
|Process Argv|. --crash-reporter-id f6280d01-f6da-405e-a0e4-2c7a155a85aa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-tailwindcss|bra|0.7.2
npm-intellisense|chr|1.4.0
c-cpp-compile-run|dan|1.0.15
c-cpp-project-generator|dan|1.2.4
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
gitlens|eam|11.6.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.23
git-project-manager|fel|1.8.1
vscode-pull-request-github|Git|0.32.0
vscode-azureappservice|ms-|0.23.0
vscode-azureresourcegroups|ms-|0.4.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.0
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-wsl|ms-|0.58.5
azure-account|ms-|0.9.10
vscode-jest|Ort|4.2.1
material-icon-theme|PKi|4.10.0
LiveServer|rit|5.6.1
vs-code-prettier-eslint|rve|3.0.4
bootstrap4-vscode|the|6.1.0
ReactSnippets|xab|2.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please describe steps to reproduce, errors/behavior that you see, and profiles configuration.

**Comment by wadjih-bencheikh18** [comment]
I uninstalled vs code and trying to reinstall it now

**Comment by wadjih-bencheikh18** [comment]
still dont working
i have this error:

> This is deprecated, the new recommended way to configure your default shell is by creating a terminal profile in #terminal.integrated.profiles.windows# and setting its profile name as the default in #terminal.integrated.defaultProfile.windows#. This will currently take priority over the new profiles settings but that will change in the future.

in front of :
` "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",`
in settings.json

**Comment by meganrogge** [comment]
Does it work if you comment out your settings file?

**Comment by wadjih-bencheikh18** [comment]
its working thnx

**Comment by wadjih-bencheikh18** [comment]
idk what was the problem but the terminal is working now (i didn't do anything) i just remove and install vscode again
