### ISSUE TITLE
How to configure Black with Prettier?

### ISSUE THREAD

**Issue by edchelstephens** [microsoft/vscode#136807]
Hi, I'm working on a Django React project.
I configured python's autoformatter as black,
using:
{
  "python.formatting.provider": "black"
}
in the .vscode/settings.json 

But with this my Prettier extension does not automatically format my javascript files.

How can I setup VSCode to autoformat python with black, and the html, css, js, json, and jsx with Prettier?

**Comment by IllusionMH** [comment]
This type of questions better suited for StackOwerflow.

You should check description of Prettier extension and section Default Formatter
https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

Either configure Prettier as default and override formatter for Python or other way around.

**Comment by edchelstephens** [comment]
> This type of questions better suited for StackOwerflow.
> 
> You should check description of Prettier extension and section Default Formatter https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
> 
> Either configure Prettier as default and override formatter for Python or other way around.

Thank you, I got it working by following a tutorial on setting the formatter for each file type. 👍
