### ISSUE TITLE
Git does not return an error if authentication is required

### ISSUE THREAD

**Issue by Jademalo** [microsoft/vscode#136879]
Issue Type: <b>Bug</b>

I am running a private repo on GitHub through WSL.
When setting everything up two weeks ago, I put in my credentials. These seem to have been cached for two weeks, I'm not sure.

When trying to fetch the repo today, the arrows just kept spinning and I had no feedback. I tried going into the terminal in VSCode to manually fetch, but the command returned no output, even verbose.

I then went into the WSL prompt directly through the terminal app, and after trying git fetch it prompted me for a github username and password. 

For some reason, this error and prompt was not shown on the bash terminal session within VSCode, nor when using any of the built in git management tools. 

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz (12 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (5.14GB free)|
|Process Argv|--crash-reporter-id 75d2bff3-b4ef-4cb2-9b19-e7eeeba2b392|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz (12 x 4008)|
|Memory (System)|7.69GB (6.92GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
arm|dan|1.5.2
remote-wsl|ms-|0.58.5
material-icon-theme|PKi|4.10.0
material-theme|zhu|3.13.2
tasks|act|0.9.0
githistory|don|0.6.19
git-commits|Exe|3.10.2
vscode-pull-request-github|Git|0.32.0
poryscript|kar|2.2.1
cpptools|ms-|1.7.1
hexeditor|ms-|1.8.2
pin-up|sae|1.4.1
vscode-taskexplorer|spm|2.5.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate - see https://github.com/microsoft/vscode/issues/136873#issuecomment-965402902 for advice.
