### ISSUE TITLE
Angular language service doesn't run

### ISSUE THREAD

**Issue by smlombardi** [microsoft/vscode#136872]
Issue Type: <b>Bug</b>

After the most recent insiders update, I get this error:

```
[Error - 9:57:13 AM] Failed to run ngcc for /Users/st016lo/github/projectname/client/tsconfig.json, language service may not operate correctly:
    ngcc for /Users/st016lo/github/projectname/client/tsconfig.json returned exit code null, stderr: 
[Info  - 9:57:13 AM] Enabling Ivy language service for /Users/st016lo/github/pojectname/client/tsconfig.json.
```

We do not have a `tsconfig.json` file here.  We have a `tsconfig.app.json` file:
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": ""
  },
  "files": [
    "main.ts",
    "polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
````

This worked fine with the version of Insiders before this one.

VS Code version: Code - Insiders 1.63.0-insider (bef4dba21f68bbdb8d9f08fe04b2e1858597722b, 2021-11-10T07:52:49.529Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 6, 4|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 2989f78b-23b4-466d-ae73-bbe6c5fe1c40|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|2.6.0
Bookmarks|ale|13.2.2
project-manager|ale|12.4.0
ng-template|Ang|13.0.0
json-flattener|App|1.0.5
change-color-format|bbu|1.2.0
markdown-preview-github-styles|bie|0.2.0
vscode-multi-line-tricks|big|0.0.3
turbo-console-log|Cha|2.1.7
path-intellisense|chr|2.4.2
vscode-eslint|dba|2.2.2
gitlens|eam|11.6.1
vscode-npm-script|eg2|0.3.23
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|9.0.0
auto-rename-tag|for|0.1.9
copilot|Git|1.7.3733
todo-tree|Gru|0.0.214
helium-icon-theme|hel|1.0.0
json-to-ts|Mar|1.7.5
web-accessibility|Max|0.2.83
rainbow-csv|mec|1.9.1
fluent-icons|mig|0.0.14
ecdc|mit|1.4.0
HTMLHint|mka|0.10.0
theme-monokai-pro-vscode|mon|1.1.19
vscode-edge-devtools|ms-|1.4.1
debugger-for-edge|msj|1.0.15
live-server-preview|neg|0.1.4
vscode-versionlens|pfl|1.0.9
quicktype|qui|12.0.46
vscode-yaml|red|1.2.0
code-settings-sync|Sha|3.4.3
rewrap|stk|1.14.0
vscode-stylelint|sty|1.1.0
vscode-input-sequence|tom|0.2.0
sort-lines|Tyr|1.9.0
errorlens|use|3.4.0
vscode-icons|vsc|11.7.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.4.0

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30382699
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsaa593:30376534
vsc1dst:30396469
vsena315cf:30395854

```

</details>

**Comment by mjbvz** [comment]
Please start by filing this against the angular extension

**Comment by wallace41290** [comment]
@smlombardi I am seeing this pop up on a ton of our repositories just recently. Did you file a ticket against the angular language service repo or determine the issue?

**Comment by smlombardi** [comment]
See https://github.com/angular/vscode-ng-language-service/issues/1565

It was confirmed to happen after updating to Insiders 1.62.1
