### ISSUE TITLE
Search button missing

### ISSUE THREAD

**Issue by Thomas-daily-life** [microsoft/vscode#136836]
The search icon on the left has become the icon of the source code management tool. I forgot how to reproduce it... Unloading and reloading can't do. I have a headache and look uncomfortable..

**Comment by Thomas-daily-life** [comment]
The search icon on the left has become the icon of the source code management tool. I forgot how to reproduce it... Unloading and reloading can't do. I have a headache and look uncomfortable....

**Comment by gjsjohnmurray** [comment]
Try `View: Reset View Locations` command.

**Comment by chrmarti** [comment]
Also check if it is enabled in the context menu when right-clicking on the activity bar (where the icon used to be). Does that help?
