### ISSUE TITLE
remote explorer terminal can't input git password

### ISSUE THREAD

**Issue by wilsonParm** [microsoft/vscode#136825]
today I update vscode to last version, and use remote explorer connet remote linux server, when I write "git pull" in my project, I did not see password input windows like usual, so it make me can't git pull my project in terminal. thank 
 you to debug

**Comment by marcusnewton** [comment]
I think latest update just broke a tonne of things when tunnelling into remote linux device. I can't call a bunch of commands I normally could before today.

**Comment by gjsjohnmurray** [comment]
Try [reverting to 1.62.0](https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions)

**Comment by wilsonParm** [comment]
> Try [reverting to 1.62.0](https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions)

1.62.0 can solve my problem that passwprd not place to input

**Comment by marcusnewton** [comment]
Likely related to https://github.com/microsoft/vscode/issues/136791
