### ISSUE TITLE
October 2021 Recovery 2 Endgame

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#136841]
- [x] Create a milestone `October 2021 Recovery 2` **@alexr00**
- [x] Bump the version number **@alexr00**
- [x] [🔖candidate issues](https://github.com/issues?utf8=✓&q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22October+2021+Recovery+2%22)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `main`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **@alexr00**
- [x] Issues are verified on `stable` build and the `verified` label is added **@alexr00**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **@alexr00**
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [x] Sanity check of installable bits ([server instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers))
  - [x] Windows 32 bit **@rzhao271**
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
    - [x] server 32-bit
  - [x] Windows 64 bit **@tanhakabir**
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
    - [x] server 64-bit
  - [x] Windows ARM64 **@sbatten**
    - [x] signed installer ARM64
    - [x] signed user installer ARM64
    - [x] zip ARM64
  - [x] macOS
    - [x] Universal **@rzhao271**
    - [x] Intel **@rzhao271**
    - [x] Intel server **@rzhao271**
    - [x] Apple Silicon **@misolori**
  - [x] Linux x64
    - [x] deb **@lramos15**
    - [x] rpm **@rzhao271**
    - [x] archives **@rzhao271**
    - [x] snap (`sudo snap install --classic --dangerous <file>.snap`) **@lramos15**
  - [x] Linux server **@TylerLeonhardt**
    - [x] x64
    - [x] x64 Alpine
    - [x] ARM32
    - [x] ARM64
- [x] Publish website **@gregvanl**
- [ ] Publish stable build **owner**
- [x] Create an official release **owner**
  - [x] Create a tag: `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)

**Comment by lramos15** [comment]
1.62.2 released

**Comment by JoshStrobl** [comment]
@lramos15 The commit for 1.62.2 points to the same as 1.62.0, which is b3318bc0524af3d74034b8bb8a64df0ccf35549a

![image](https://user-images.githubusercontent.com/156574/141421818-3801f76a-28a5-4c0b-a6c2-3821bf783833.png)

**Comment by lramos15** [comment]
@JoshStrobl Good catch, this was due to me forgetting to pull the new commits before creating the tag 🙃. I've updated the tag to point to the correct commit.
