### ISSUE TITLE
Integrated terminal session restore should inherit some ENV vars instead of restoring them 

### ISSUE THREAD

**Issue by tadpol** [microsoft/vscode#136871]
The current terminal session restore overwrites all ENV vars.  I want to be able to supply a list of ENV names to never overwrite.  

Specifically, after a computer reboot, the value of `SSH_AUTH_SOCK` changes.  I want the new value to propagate into all processes and terminals and such.  However with the terminal session restore, it overwrites `SSH_AUTH_SOCK` with the old value that is no longer valid.  So I would like to have a config somewhere to say that when restoring the session, don't overwrite these names if they exist all ready.

**Comment by Tyriar** [comment]
I hit this while setting up my new PC and it was definitely a little confusing.
