### ISSUE TITLE
Format on Save will create a bad format with cshtml files

### ISSUE THREAD

**Issue by Thoorium** [Microsoft/vscode#13681]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:28:55.412Z)
- OS Version: Darwin x64 15.6.0
- Extensions: PKief.material-icon-theme-1.1.1, abusaidm.html-snippets-0.0.17, be5invis.vscode-icontheme-nomo-dark-1.1.4, donjayamanne.python-0.4.2, k--kato.docomment-0.0.7, lukehoban.Go-0.6.44, ms-vscode.csharp-1.4.1, robertohuertasm.vscode-icons-3.0.4

Steps to Reproduce:

Project type: Aspnet Core MVC

1. In a cshtml file for a view, add a model on the first line then a block of code  
```
@model MyModel  
@{  
    ViewData["Title"] = "My title";  
 }
```
2. Save the file. The new format will be
`@model MyModel @{ ViewData["Title"] = "My title";}`
3. Because it is all on one line, a compilation error will be thrown when the view is loaded

**Comment by jrieken** [comment]
@Thoorium That is the responsibility of the `cshtml` formatter. Not really where that comes from - @aeschli is that our?

**Comment by aeschli** [comment]
We use the regular html formatter for that.

I guess I'll disable the formatter there then
