### ISSUE TITLE
Expose a context key that reflects opening local folders in vscode.dev

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#136897]
Following the recommendation in https://github.com/microsoft/vscode-python/issues/17493#issuecomment-928986146, we are restricting features of the Python extension with `"when": "!virtualWorkspace && shellExecutionSupported"` when they shouldn't be exposed in the following cases:
- virtual workspaces;
- virtual and local folders in github.dev and vscode.dev. 

However, `shellExecutionSupported` is not supported everywhere we use it, which causes issues like https://github.com/microsoft/vscode/issues/136712 (originally reported in https://github.com/microsoft/vscode/issues/136712), where we use it to gate debugging features.

Following https://github.com/microsoft/vscode/issues/136712#issuecomment-965550267, which combination of context keys should we use for features that we want to disable in virtual workspaces and github.dev/vscode.dev (both local and virtual folders)?

**Comment by bpasero** [comment]
@aeschli maybe you wanna take a stab, I think you introduced various methods to figure out in what kind of remote setup one is in?

**Comment by aeschli** [comment]
It's not that some context variables are not supported everywhere. It's just that each context variable has its own meaning which might not fit your scenario.
IMO the underlying issue of #136712 is that debug isn't listening for changes to context variables.

IMO `shellExecutionSupported` would fit your need as you want to know if you can run a shell.

But if not, you can also define your own context variable. [Example](https://github.com/microsoft/vscode-remote-wsl-recommender/blob/daf4a4ca1f94d5f50c61a9bcf7277d66228557ca/src/extension.ts#L22).

A context variable that would be useful would be to find out if extensions are running in a node or web environment.
A bit like https://github.com/microsoft/vscode/blob/8d3536c7f7c572d89bdbff68a9f30a167a09914a/src/vscode-dts/vscode.proposed.extensionRuntime.d.ts#L18

The tricky thing is that the context variable is global and not extension specific. So if we are in an environment where there is a node and web ext host, it depends on what the extension defines as main and browser.

My suggestion would be `hasNodeExtensionRuntime`

**Comment by Tyriar** [comment]
I'm not sure how `shellExecutionSupported` works exactly but the terminal has `terminalProcessSupported` which is essentially Martin's suggestion; there is a backend registered in the terminal that supports launching real processes.

**Comment by kimadeline** [comment]
Now that https://github.com/microsoft/vscode/issues/137219 was merged, I don't need this feature anymore since `shellExecutionSupported` is now supported for debugging contributions. 

Do you still want to leave this open?

**Comment by aeschli** [comment]
Ok, closing then.
