### ISSUE TITLE
Disassembly View support for custom debuggers

### ISSUE THREAD

**Issue by SURYASPR** [microsoft/vscode#136827]
I'm able to see the disassembly code for a c/cpp file using "Open Disassembly View" for cppdbg debugger type (using gdb debugger). But I'm not able to find this option while debugging using a LLDB ARM/custom debugger.

If the disassembly view support for LLDB ARM/custom debuggers is already planned, please let me know the timelines. If not planned, can you please support this ?

**Comment by weinand** [comment]
The "LLDB ARM/custom debugger" will have to opt-into the disassembly feature (by implementing DAP's [disassembly request](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Disassemble)).
