### ISSUE TITLE
When hover basic const it pop up color picker?

### ISSUE THREAD

**Issue by milosveljkovic** [microsoft/vscode#136850]
When I do double click on apiConfig(upper one) I hover it after I get color picker and intreface definition like on picture below..?
File content was similar to code under:

```
const apiConfig = {
	apiPrefix: '/xxx',
	versionSuffix: '/yyy'
}

export default apiConfig
```
![image](https://user-images.githubusercontent.com/47954575/141099799-75d3ef97-a537-4d0a-85ca-3ad6c297075f.png)

**Comment by mjbvz** [comment]
/needsMoreInfo

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
