### ISSUE TITLE
How to avoid wrap line when format code in react project ?

### ISSUE THREAD

**Issue by jasonsun001** [microsoft/vscode#136826]
How to avoid wrap line when format code in react project ?
Too many short lines make code hard to read.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version, and which formatter you are using.

**Comment by mjbvz** [comment]
This is almost certainly coming from one of your installed extensions, such as prettier. VS Code generally does not wrap text when formatting js/ts
