### ISSUE TITLE
Side Panel: Bad state if application is restarted when References is only view and visible

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#136805]
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Use Find All References and drag in to Side Panel
2. Close/open application or just run `> Developer: Reload Window`
3. Looks as Side Panel while application is loaded - "Drag a view into the panel to display." is shown for a moment and then disappear.
4. Open Developer Tools and try to drag other view e.g. Problems into Side Panel - nothing happens with view but console has bunch of errors (comes in batches of 3)

<details>
<summary>Errors</summary>

```
bootstrap-window.js:244 [uncaught exception]: TypeError: Cannot read property 'left' of undefined
b @ bootstrap-window.js:244
(anonymous) @ bootstrap-window.js:51
emit @ events.js:315
window.onerror @ electron/js2c/renderer_init.js:105
D.globals.onerror @ workbench.desktop.main.js:622
error (async)
installErrorListeners @ workbench.desktop.main.js:622
E @ workbench.desktop.main.js:621
L @ workbench.desktop.main.js:622
hs @ workbench.desktop.main.js:1913
_createInstance @ workbench.desktop.main.js:606
createInstance @ workbench.desktop.main.js:606
safeCreateInstance @ workbench.desktop.main.js:1554
doInstantiateByPhase @ workbench.desktop.main.js:1554
(anonymous) @ workbench.desktop.main.js:1554
Promise.then (async)
instantiateByPhase @ workbench.desktop.main.js:1554
(anonymous) @ workbench.desktop.main.js:1554
start @ workbench.desktop.main.js:1554
(anonymous) @ workbench.desktop.main.js:2636
invokeFunction @ workbench.desktop.main.js:606
startup @ workbench.desktop.main.js:2636
open @ workbench.desktop.main.js:2918
async function (async)
open @ workbench.desktop.main.js:2918
w @ workbench.desktop.main.js:2918
m.load.configureDeveloperSettings @ workbench.js:32
(anonymous) @ bootstrap-window.js:174
i._invokeFactory @ loader.js:1185
i.complete @ loader.js:1195
i._onModuleComplete @ loader.js:1821
i._onModuleComplete @ loader.js:1833
i._resolve @ loader.js:1781
i.defineModule @ loader.js:1424
v @ loader.js:1871
define @ loader.js:1947
(anonymous) @ workbench.desktop.main.js:3003
(anonymous) @ workbench.desktop.main.js:3003

bootstrap-window.js:247 TypeError: Cannot read property 'left' of undefined
    at K (workbench.desktop.main.js:2564)
    at Object.onDragOver (workbench.desktop.main.js:2564)
    at Object.onDragOver (workbench.desktop.main.js:2392)
    at HTMLDivElement.<anonymous> (workbench.desktop.main.js:2392)
b @ bootstrap-window.js:247
(anonymous) @ bootstrap-window.js:51
emit @ events.js:315
window.onerror @ electron/js2c/renderer_init.js:105
D.globals.onerror @ workbench.desktop.main.js:622
error (async)
installErrorListeners @ workbench.desktop.main.js:622
E @ workbench.desktop.main.js:621
L @ workbench.desktop.main.js:622
hs @ workbench.desktop.main.js:1913
_createInstance @ workbench.desktop.main.js:606
createInstance @ workbench.desktop.main.js:606
safeCreateInstance @ workbench.desktop.main.js:1554
doInstantiateByPhase @ workbench.desktop.main.js:1554
(anonymous) @ workbench.desktop.main.js:1554
Promise.then (async)
instantiateByPhase @ workbench.desktop.main.js:1554
(anonymous) @ workbench.desktop.main.js:1554
start @ workbench.desktop.main.js:1554
(anonymous) @ workbench.desktop.main.js:2636
invokeFunction @ workbench.desktop.main.js:606
startup @ workbench.desktop.main.js:2636
open @ workbench.desktop.main.js:2918
async function (async)
open @ workbench.desktop.main.js:2918
w @ workbench.desktop.main.js:2918
m.load.configureDeveloperSettings @ workbench.js:32
(anonymous) @ bootstrap-window.js:174
i._invokeFactory @ loader.js:1185
i.complete @ loader.js:1195
i._onModuleComplete @ loader.js:1821
i._onModuleComplete @ loader.js:1833
i._resolve @ loader.js:1781
i.defineModule @ loader.js:1424
v @ loader.js:1871
define @ loader.js:1947
(anonymous) @ workbench.desktop.main.js:3003
(anonymous) @ workbench.desktop.main.js:3003

workbench.desktop.main.js:2564 Uncaught TypeError: Cannot read property 'left' of undefined
    at K (workbench.desktop.main.js:2564)
    at Object.onDragOver (workbench.desktop.main.js:2564)
    at Object.onDragOver (workbench.desktop.main.js:2392)
    at HTMLDivElement.<anonymous> (workbench.desktop.main.js:2392)
K @ workbench.desktop.main.js:2564
onDragOver @ workbench.desktop.main.js:2564
onDragOver @ workbench.desktop.main.js:2392
(anonymous) @ workbench.desktop.main.js:2392
```

</details>

**Workaround: Resize Side Panel. "Drag a view into the panel to display." will be shown again and now you can drag other views.**

3. Close/open application or just run `> Developer: Reload Window` again
4. Side Panel now has `...` menu as in case of overflow and only item is `workbench.views.service.auxiliarybar.8faea8d1-01e3-4b4e-a97d-fa362304f2ed`
![image](https://user-images.githubusercontent.com/1312662/141020675-d4ddc9df-44a2-460e-925d-c0ce361bb8dc.png)

In this case it's possible to drag other view to the `...` and then it will be possible to select it from `...`. There will be same errors as described above.

5. Use Find All References - `workbench.views.service.auxiliarybar.8faea8d1-01e3-4b4e-a97d-fa362304f2ed` replaces with References view

VS Code version: Code - Insiders 1.63.0-insider (93ce4397a2cbc88707c3ed8b34a813b87457568c, 2021-11-09T15:23:39.737Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (17.18GB free)|
|Process Argv|--crash-reporter-id cf52dbde-2c94-45c3-9bf3-45d8b9966b04|
|Screen Reader|no|
|VM|0%|
</details>
Extensions: none

**Comment by IllusionMH** [comment]
@sbatten I've tried latest build. It's no longer broken as before but still shown a bit unexpected behavior:

1. Use Find All References and drag in to Side Panel (only view)
2. Close/open application or just run `> Developer: Reload Window`
In this case you can still see References tab and it looks selected but also has "Drag a view into the panel to display."
![image](https://user-images.githubusercontent.com/1312662/143849540-8a84486e-cc12-46d9-bad8-80100a5da2e5.png)

3.a. Drag other view into Side panel - References view is replaced with dropped view.

3.b. Use Find All References - action buttons for References view are shown, but results aren't and "Drag a view into the panel to display." is still in place.
![image](https://user-images.githubusercontent.com/1312662/143850441-9f3f11e1-848f-444f-b92a-471d050964f7.png)

**Workaround: Try to resize panel or switch between view in panel**

Should this issue be reopened or I need to create new one.

**Comment by sbatten** [comment]
@IllusionMH thanks, will take a look today
