### ISSUE TITLE
Pigments Extension

### ISSUE THREAD

**Issue by asp-dot-net** [Microsoft/vscode#13689]
Is there any possible way someone would be able to create an extension for VS Code such as the extension for Atom https://atom.io/packages/pigments.

**Comment by isidorn** [comment]
Closing this issue as there is nothing to be done on the vscode side.
Hopefully somebody from the community will create that extension.

**Comment by landonalder** [comment]
If anyone is still looking, this does the same thing as pigments: https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight

**Comment by AlexandreKilian** [comment]
@landonalder unfortunately it doesn't... Pigments can highlight colors that have been defined as less/scss-Variables, this extension can't, not even in the same file 😞

**Comment by jmvelazquezr** [comment]
@AlexandreKilian this one does, although that's all it does, highlighting colors. It lacks other Pigments features like showing the project's palette, or finding all colors. 
https://marketplace.visualstudio.com/items?itemName=kamikillerto.vscode-colorize
