### ISSUE TITLE
Side Panel: References list missing when dragged from Pannel

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#136802]
Issue Type: <b>Bug</b>

Only happens if you drag from Panel and doesn't happen you drag from Action Bar.
Doesn't happen if Side Panel has other views already (e.g. Problems) - Preferences should be first dragged in to Side Panel. Althrough doesn't matter if Side Panel is visible before drag or revealed when user grages References to the edge of the screen.

Workaround: `> Developer: Reload Window` after Preferences dragged into Side panel and run fing references again.

With `"workbench.experimental.sidePanel.enabled": true`.
Side panel view is empty.

0. `> Developer: Reload Window` (to make sure that there were no other view in Side Panel already, otherwise might not be reproduced)
1. Use Find All References to see Reverences View
2. Drag References View into Panel (at the bottom) if needed - see that list of found references is visible
![image](https://user-images.githubusercontent.com/1312662/141015302-7c11c07a-e75e-4a14-a59f-5898b2a1debf.png)

3. Drag References View to Side Panel - see that list is missing.
![image](https://user-images.githubusercontent.com/1312662/141015334-cb56ff95-2c87-4b8d-a227-880e2506006e.png)

Strange enough - element with list/tree is in DOM but hidden, if shown - it has recent list. If show clicks on items will navigate to proper references, however new searches won't update references list.
![image](https://user-images.githubusercontent.com/1312662/141015348-80414096-bc18-420a-99d4-e078596e2ee8.png)

4. Hide Side Panel
5. Use Find All References on other identifier - Side Panel is shown, results/files counts updated, list not visible (with `.monaco-list-rows` empty now), and console has next error

<details>
<summary>Error trace</summary>

```
workbench.desktop.main.js:77 [Extension Host] stack trace: Error: TreeError [references-view.tree] Data tree node not found: [object Object]    at Y.getDataNode (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:191:19876)    at Y.expand (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:191:17944)    at vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2343:126494    at Array.map (<anonymous>)    at me.expand (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2343:126483)    at u.reveal (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1529:62202)    at vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1529:61342    at processTicksAndRejections (internal/process/task_queues.js:93:5) (at c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:31577)
E @ workbench.desktop.main.js:77
$logExtensionHostMessage @ workbench.desktop.main.js:1536
_doInvokeHandler @ workbench.desktop.main.js:1536
_invokeHandler @ workbench.desktop.main.js:1536
_receiveRequest @ workbench.desktop.main.js:1536
_receiveOneMessage @ workbench.desktop.main.js:1536
(anonymous) @ workbench.desktop.main.js:1536
fire @ workbench.desktop.main.js:69
fire @ workbench.desktop.main.js:85
_receiveMessage @ workbench.desktop.main.js:85
(anonymous) @ workbench.desktop.main.js:85
fire @ workbench.desktop.main.js:69
acceptChunk @ workbench.desktop.main.js:85
(anonymous) @ workbench.desktop.main.js:85
k @ workbench.desktop.main.js:3002
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
workbench.desktop.main.js:609   ERR TreeError [references-view.tree] Data tree node not found: [object Object]: Error: TreeError [references-view.tree] Data tree node not found: [object Object]
    at Y.getDataNode (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:191:19876)
    at Y.expand (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:191:17944)
    at vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2343:126494
    at Array.map (<anonymous>)
    at me.expand (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2343:126483)
    at u.reveal (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1529:62202)
    at vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1529:61342
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
</details>

If dragged back to Panel/Action Bar - sometimes list is visible and sometimes you might need to press refresh to see references list.

VS Code version: Code - Insiders 1.63.0-insider (93ce4397a2cbc88707c3ed8b34a813b87457568c, 2021-11-09T15:23:39.737Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (16.09GB free)|
|Process Argv|--crash-reporter-id cf52dbde-2c94-45c3-9bf3-45d8b9966b04|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by sbatten** [comment]
I remember a while back that the references view had an issue with restoring its state across drag and drop because we destroy and recreate the view with that operation. I am actually surprised this shows anything when moving from side bar to panel. @jrieken does that sound familiar?

**Comment by jrieken** [comment]
Yes - I do remember something vaguely... Tho, I am just a tree data provider and I don't believe there is anything I can do except wait for someone to ask me for data, right?

**Comment by alexr00** [comment]
@sbatten is there some event I should listen to to know that I should refresh tree views when the view is moved?

**Comment by sbatten** [comment]
@alexr00 maybe here? https://github.com/microsoft/vscode/blob/fb4c12bfff2710e00eabac84d63bb304ea184574/src/vs/workbench/browser/parts/views/treeView.ts#L228-L232

**Comment by alexr00** [comment]
@sbatten did some debugging, and it look like the issue is that the `dispose` of the tree view ends up happening after the view has been registered in the new location. 

To demonstrate, take 
https://github.com/microsoft/vscode/blob/96c0bfba4cc76dff725dd5189d8606e858e3cf41/src/vs/workbench/browser/parts/views/viewsService.ts#L125-L128

and change it to 
```js
	private onDidChangeContainerLocation(viewContainer: ViewContainer, from: ViewContainerLocation, to: ViewContainerLocation): void {
		this.deregisterPaneComposite(viewContainer, from);
		setTimeout(() => this.registerPaneComposite(viewContainer, to), 200);
	}
```

With that, the view moving works. Is there an even you can wait for after your `deregister` call before calling your `register`?

**Comment by sbatten** [comment]
After discussing with @alexr00, we've decided to use the setTimeout fix of 0 to delay the events for the next tick and allow all listening events to finish processing. @alexr00 will look into a `TreeViewPane` specific fix to remove this if determined to be mostly `TreeViewPane` specific.

**Comment by alexr00** [comment]
Tested with webview views, and there's no issue there.

The `setVisible` call on dispose needs to be kept: https://github.com/microsoft/vscode/issues/42978

I've made the change @sbatten and I discussed to only make the `setVisible` call when the tree's container hasn't changed and I've reverted the `setTimeout` change.

**Comment by IanMatthewHuff** [comment]
Verified with the original repro steps + tried a few more dragging locations. Looked fine everywhere I tried.
