### ISSUE TITLE
VS Code Doesn't show credentials prompt on Windows 11

### ISSUE THREAD

**Issue by cod3rshotout** [microsoft/vscode#136892]
I've the latest version of Windows 11 KB5007215 and the latest version of VS Code 1.62.1.
After the update KB5007215 for some reason when I need to push some commits on my git repository, the login prompt doesn't appear anymore.

**Comment by gjsjohnmurray** [comment]
Maybe caused by the 1.62.1 update. See https://github.com/microsoft/vscode/issues/136873#issuecomment-965402902 for downgrade advice until 1.62.2 ships.

**Comment by bsaunders23** [comment]
Verifying that I'm facing the same issue with latest release of VS Code Insiders

**Comment by yheuhtozr** [comment]
Seems the same issue here. I upgraded to Win 11 yesterday and caught by this today.
