### ISSUE TITLE
нет доступа к connect ECONNREFUSED 127.0.0.1;8016

### ISSUE THREAD

**Issue by Topilin** [microsoft/vscode#136876]
Not connect ECONNREFUSED 127.0.0.1;8016 for PlatformIO

**Comment by Topilin** [comment]
нет доступа к connect ECONNREFUSED 127.0.0.1;8016

**Comment by Topilin** [comment]
PlatformIO IDE

**Comment by Topilin** [comment]
Not connect ECONNREFUSED 127.0.0.1;8016 for PlatformIO IDE

**Comment by IllusionMH** [comment]
/causedByExtesion

Errors from extensions should be reported in extension repo.

Check for duplicates before creating issue in extension repo. E.g. https://github.com/platformio/platformio-vscode-ide/issues/2667

**Comment by IllusionMH** [comment]
/causedByExtension

Errors from extensions should be reported in extension repo.

Check for duplicates before creating issue in extension repo. E.g. https://github.com/platformio/platformio-vscode-ide/issues/2667
