### ISSUE TITLE
Git ignore count problem

### ISSUE THREAD

**Issue by Pvybhav** [microsoft/vscode#136821]
Issue Type: <b>Bug</b>

in source control tab, ignored files also showing. after updating the gitignore, it is not recognising the ignored files.

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.02GB free)|
|Process Argv|--crash-reporter-id 10d4186b-f7ec-46af-bb6a-ff7287a740fe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (75)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.1.0
jest-snippets|and|1.8.0
vscode-color|ans|0.4.5
vscode-styled-jsx|bla|2.0.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.2
bracket-pair-colorizer|Coe|1.0.61
enzyne-snippet|cru|0.0.2
vscode-jest-runner|cst|0.0.6
vscode-eslint|dba|2.2.2
eslint-disable-snippets|drK|1.3.0
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.23
vscode-great-icons|emm|2.1.79
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|9.0.0
vscode-jest-runner|fir|0.4.47
flow-for-vscode|flo|1.9.2
auto-close-tag|for|0.5.13
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.9
pyformat|giy|1.0.2
Python-autopep8|him|1.0.2
vscode-power-mode|hoo|2.2.0
rest-client|hum|0.24.5
react-jest-vscode-snippets|jal|0.0.3
react-native-snippet|jun|0.5.6
robotframework|kei|0.2.8
node-module-intellisense|lei|1.5.0
expand-region|let|0.1.4
vscode-language-babel|mgm|0.0.35
code-beautifier|mic|2.3.3
vscode-docker|ms-|1.17.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.0
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-wsl|ms-|0.58.5
vscode-typescript-next|ms-|4.6.20211109
vsliveshare|ms-|1.0.5090
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.8.0
color-highlight|nau|2.5.0
fix-json|oli|0.1.2
vscode-jest|Ort|4.2.1
material-icon-theme|PKi|4.10.0
pluralsight|Plu|0.4.2
tsimporter|pmn|2.0.1
vscode-css-peek|pra|4.2.0
java|red|1.0.0
LiveServer|rit|5.6.1
robotframework-lsp|rob|0.28.0
code-settings-sync|Sha|3.4.3
indenticator|Sir|0.7.0
autoimport|ste|1.5.4
code-spell-checker|str|2.0.12
insert-special-symbol|swi|1.3.0
python|tht|0.2.3
ReactSnippetsStandard|Tim|1.1.0
rf-intellisense|Tom|2.8.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
vscode-icons|vsc|11.7.0
quokka-vscode|Wal|1.0.417
vscode-import-cost|wix|2.15.0
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by lszomoru** [comment]
@Pvybhav, could you please provide an example of what you have entered in the `.gitignore` file that is not being honoured? Thanks!

**Comment by Pvybhav** [comment]
I added **node_modules** in **.gitignore** to ignore node modules. After this if I navigate to source control tab, node_modules contents are also showing. **If I try re-opening, then node_module directory contents are ignored.**

**Comment by lszomoru** [comment]
Thanks @Pvybhav. I am unable to reproduce the same behaviour in the latest Insiders release. Could you please give it a try? 
If you are still able to reproduce the problem, do you mind create a gif recording using https://gifcap.dev? Thank you!
