### ISSUE TITLE
yarn watch之后，长时间无响应，也不报错

### ISSUE THREAD

**Issue by lichangwei123** [microsoft/vscode#136861]
2975 ms
[watch-extensions] [20:20:01] Starting watch-extension:debug-server-ready ...
[watch-extensions] [20:20:01] Finished clean-extension-extension-editing after 2987 ms
[watch-extensions] [20:20:01] Starting watch-extension:extension-editing ...
[watch-extensions] [20:20:01] Finished clean-extension-github after 2996 ms
[watch-extensions] [20:20:01] Starting watch-extension:github ...
[watch-extensions] [20:20:01] Finished clean-extension-gulp after 3007 ms
[watch-extensions] [20:20:01] Starting watch-extension:gulp ...
[watch-extensions] [20:20:01] Finished clean-extension-grunt after 3016 ms
[watch-extensions] [20:20:01] Starting watch-extension:grunt ...
[watch-extensions] [20:20:01] Finished clean-extension-image-preview after 3023 ms
[watch-extensions] [20:20:01] Starting watch-extension:image-preview ...
[watch-extensions] [20:20:01] Finished clean-extension-jake after 3033 ms
[watch-extensions] [20:20:01] Starting watch-extension:jake ...
[watch-extensions] [20:20:01] Finished clean-extension-markdown-math after 3043 ms
[watch-extensions] [20:20:01] Starting watch-extension:markdown-math ...
[watch-extensions] [20:20:01] Finished clean-extension-markdown-language-features-preview-src after 3052 ms
[watch-extensions] [20:20:01] Starting watch-extension:markdown-language-features-preview-src ...
[watch-extensions] [20:20:01] Finished clean-extension-simple-browser after 3060 ms
[watch-extensions] [20:20:01] Starting watch-extension:simple-browser ...
[watch-extensions] [20:20:01] Finished clean-extension-merge-conflict after 3070 ms
[watch-extensions] [20:20:01] Starting watch-extension:merge-conflict ...
[watch-extensions] [20:20:01] Finished clean-extension-vscode-notebook-tests after 3092 ms
[watch-extensions] [20:20:01] Starting watch-extension:vscode-notebook-tests ...
[watch-client    ] [20:20:02] Starting compilation...
[watch-extensions] [20:20:02] Finished clean-extension-vscode-colorize-tests after 4242 ms
[watch-extensions] [20:20:02] Starting watch-extension:vscode-colorize-tests ...
[watch-extensions] [20:20:04] Finished clean-extension-css-language-features-server after 5949 ms
[watch-extensions] [20:20:04] Starting watch-extension:css-language-features-server ...
[watch-extensions] [20:20:04] Finished clean-extension-css-language-features-client after 5968 ms
[watch-extensions] [20:20:04] Starting watch-extension:css-language-features-client ...
[watch-extensions] [20:20:04] Finished clean-extension-github-authentication after 5977 ms
[watch-extensions] [20:20:04] Starting watch-extension:github-authentication ...
[watch-extensions] [20:20:04] Finished clean-extension-emmet after 5990 ms
[watch-extensions] [20:20:04] Starting watch-extension:emmet ...
[watch-extensions] [20:20:04] Finished clean-extension-html-language-features-client after 6013 ms
[watch-extensions] [20:20:04] Starting watch-extension:html-language-features-client ...
[watch-extensions] [20:20:04] Finished clean-extension-git after 6026 ms
[watch-extensions] [20:20:04] Starting watch-extension:git ...
[watch-extensions] [20:20:04] Finished clean-extension-json-language-features-client after 6046 ms
[watch-extensions] [20:20:04] Starting watch-extension:json-language-features-client ...
[watch-extensions] [20:20:04] Finished clean-extension-ipynb after 6058 ms
[watch-extensions] [20:20:04] Starting watch-extension:ipynb ...
[watch-extensions] [20:20:04] Finished clean-extension-markdown-language-features after 6067 ms
[watch-extensions] [20:20:04] Starting watch-extension:markdown-language-features ...
[watch-extensions] [20:20:04] Finished clean-extension-json-language-features-server after 6089 ms
[watch-extensions] [20:20:04] Starting watch-extension:json-language-features-server ...
[watch-extensions] [20:20:04] Finished clean-extension-search-result after 6101 ms
[watch-extensions] [20:20:04] Starting watch-extension:search-result ...
[watch-extensions] [20:20:04] Finished clean-extension-npm after 6113 ms
[watch-extensions] [20:20:04] Starting watch-extension:npm ...
[watch-extensions] [20:20:04] Finished clean-extension-vscode-api-tests after 6127 ms
[watch-extensions] [20:20:04] Starting watch-extension:vscode-api-tests ...
[watch-extensions] [20:20:04] Finished clean-extension-vscode-custom-editor-tests after 6145 ms
[watch-extensions] [20:20:04] Starting watch-extension:vscode-custom-editor-tests ...
[watch-extensions] [20:20:04] Finished clean-extension-vscode-test-resolver after 6155 ms
[watch-extensions] [20:20:04] Starting watch-extension:vscode-test-resolver ...
[watch-extensions] [20:20:04] Finished clean-extension-php-language-features after 6296 ms
[watch-extensions] [20:20:04] Starting watch-extension:php-language-features ...
[watch-extensions] [20:20:04] Finished clean-extension-microsoft-authentication after 6326 ms
[watch-extensions] [20:20:04] Starting watch-extension:microsoft-authentication ...
[watch-extensions] [20:20:04] Finished clean-extension-typescript-language-features after 6349 ms
[watch-extensions] [20:20:04] Starting watch-extension:typescript-language-features ...
[watch-extensions] [20:20:08] Finished clean-extension-html-language-features-server after 10334 ms
[watch-extensions] [20:20:08] Starting watch-extension:html-language-features-server ...
[watch-extensions] [20:20:29] Finished webpacking extension media markdown-language-features with 0 errors.
[watch-extensions] [20:20:29] Finished webpacking extension media simple-browser with 0 errors.
[watch-extensions] [20:20:42] Finished compilation extensions with 0 errors after 41640 ms
[watch-client    ] [20:21:42] Finished compilation with 0 errors after 100636 ms

**Comment by lichangwei123** [comment]
桌面应用并没有弹出来，卡在这里了

**Comment by lichangwei123** [comment]
![image](https://user-images.githubusercontent.com/46671582/141126985-dc4a8c28-f3c8-4702-812a-8e8f70e516d5.png)

**Comment by CodeCrazy-ywt** [comment]
After yarn watch, there's no response, even no error.

**Comment by chrmarti** [comment]
The last line indicates compilation was successful. Watch mode then lets the process wait for file changes and recompiles as needed. If you only want to compile once and expect the process to finish try `yarn compile`.
