### ISSUE TITLE
updating imports when files are renamed

### ISSUE THREAD

**Issue by raghavthind2005** [microsoft/vscode#136883]
When a file is renamed by the user, the imports that were using this file name are not being updated automatically. It gets tedious to update the imports (with the new name of the file) manually, especially when working on a bigger project. 

**PROPOSED FEATURE :**
A feature allowing the user to automatically update the the imports upon updating the file name .

This could be done in form of a dialogue box (prompted when the user renames the file) , asking the user if he wants to automatically update the imports. 

This feature could save the users some precious time.

**Comment by IllusionMH** [comment]
/needsMoreInfo

You can start with what VS Code version and languages you are using and how you are renaming files.

VS Code supports this for JS/TS (e.g. `javascript.updateImportsOnFileMove.enabled` etc.)

**Comment by mjbvz** [comment]
Yes this feature is already implemented. If you are not seeing it working in a specific case, please share a small example project that demonstrates the problem
