### ISSUE TITLE
Debug indicator looks odd

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#136824]
![image](https://user-images.githubusercontent.com/900690/141060096-874f48be-cfdc-4500-949a-9c580a383340.png)

Running out of sources and debugging.

**Comment by hediet** [comment]
Thanks for reporting!

Looks much better now:

![image](https://user-images.githubusercontent.com/2931520/141100766-3a37aaaa-9159-4d03-8431-529cb42dce66.png)

![image](https://user-images.githubusercontent.com/2931520/141100813-0181b399-34df-45f1-b42c-b6f8db35f110.png)
