### ISSUE TITLE
Broken Snap panel in Code

### ISSUE THREAD

**Issue by JakubDrozd** [microsoft/vscode#136839]
Issue Type: <b>Bug</b>

HI, I would like to have the Windows 11 Snap layouts panel when getting the mouse cursor on the maximalize button, but I don't get any response. You can see the working Snap in Chrome and the broken Snap in VS Code on the screenshots. Could you fix this, please?

![2021-11-10 (2)](https://user-images.githubusercontent.com/70533786/141078831-50c209f2-f9d1-42b6-9c31-e127694ff399.png)

![2021-11-10 (1)](https://user-images.githubusercontent.com/70533786/141078611-6e04b7b9-3372-4d76-a137-552477ccc844.png)

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (8.58GB free)|
|Process Argv|--crash-reporter-id f667050e-cd55-4c9b-8828-622f51c58fbd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
vscode-eslint|dba|2.2.2
copilot|Git|1.7.3733
vscode-pull-request-github|Git|0.32.0
better-cpp-syntax|jef|1.15.10
vscode-language-pack-pl|MS-|1.62.3
cpptools|ms-|1.7.1
markdown-preview-enhanced|shd|0.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by deepak1556** [comment]
merging to https://github.com/microsoft/vscode/issues/127449
