### ISSUE TITLE
everything is blank cant do anyting

### ISSUE THREAD

**Issue by AbhishekZambaremPHATEK** [microsoft/vscode#136832]
Does this issue occur when all extensions are disabled?: Yes/No

everything is blank cant do anyting

- VS Code Version: 1.62.1
- OS Version: windows 10

![image](https://user-images.githubusercontent.com/83326863/141069640-cfe92121-20dd-4801-a98b-ee7c2ea24958.png)

**Comment by AbhishekZambaremPHATEK** [comment]
and by removing code folder in AppData it is now totally black

![image](https://user-images.githubusercontent.com/83326863/141070559-34b4cda9-973e-4af0-a562-b70b214d5e3c.png)

**Comment by bpasero** [comment]
Can you run from the command line `code --open-devtools` and click on the `Console` tab and see if any output gets printed?

**Comment by AbhishekZambaremPHATEK** [comment]
I have resolved that issue by uninstalling  vscode with its user data files and reinstall
