### ISSUE TITLE
Cannot close Visual Studio Code

### ISSUE THREAD

**Issue by sps-gold** [microsoft/vscode#136808]
Issue Type: <b>Bug</b>

An unexpected error was thrown while attempting to change the workspace of the window (VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.).

- attach an external drive with wsl
- open vscode in wsl folder
- reboot machine with external drive disconnected
- launch vscode, it will report the error mentioned above (as wsl drive is not connected)
- try to close visual studio -> the error reappears and vscode window do not close
- try to close remote connection -> the error reappears and vscode is still showing 'Disconnected from WSL'
- try to open folder from local -> the error reappears and vscode do not switch to local folder

only option is to force quit vscode
ps: earlier I could close vscode, its a recent regression

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Fetching remote diagnostics for 'WSL: Ubuntu-18.04' failed: VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (9.64GB free)|
|Process Argv|--crash-reporter-id f5d8792d-3848-47f3-85a8-be232ade1e25|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu-18.04' failed: VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by moven0831** [comment]
Same issue here, lol

**Comment by dennis8989** [comment]
same issue T_T

**Comment by aeschli** [comment]
Caused by https://github.com/microsoft/vscode/issues/136358.

**Comment by liamoconnor9** [comment]
Me too.

**Comment by LittleQBerry** [comment]
same error

**Comment by sps-gold** [comment]
@LittleQBerry the issue is now fixed for me after the update. Check for your [vscode version](https://code.visualstudio.com/docs/supporting/FAQ#_how-do-i-find-the-version)
and apply updates if any. If you still hit into it on the latest vscode I would suggest to log a new issue with your steps.
PS: My vscode version
![image](https://user-images.githubusercontent.com/79571312/141663715-d93d66f7-af18-47f1-8557-7bed8bd04d4c.png)

**Comment by theUpsider** [comment]
same problem with newer version. I opened a new bug report, since it this is a critical bug.
