### ISSUE TITLE
Prefer tabs crash

### ISSUE THREAD

**Issue by to2false** [microsoft/vscode#136820]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version: MacOS Monterey 12.0.1 (21A559)

Version: 1.62.1 (Universal)
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-05T09:23:14.144Z (4 days ago)
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

Steps to Reproduce:

1. click upgrade the it crashed because I open the prefer tabs, and I can't open it again because it keeps crashed.
2. I closed the prefer tabs, it works well again

**Comment by to2false** [comment]
![image](https://user-images.githubusercontent.com/21302817/141059966-eab189c4-0e9c-46f0-8e9a-2d3fa0a5811b.png)

I add the details of this problem, this feature is the new version of macos, and I turned on vscode window nativeTabs option.
It crashes when I am in full screen mode with multiple tabs and click update.

If need a gif, I can not provide it for now, until the next version update

**Comment by bpasero** [comment]
> and click update

You mean when a VSCode update is there and it wants to apply the update and restart?

Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by to2false** [comment]
> You mean when a VSCode update is there and it wants to apply the update and restart?

Yes, then start again, it quickly crash and disappear

> Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

I'll try it out when the time comes

**Comment by bpasero** [comment]
Thanks
