### ISSUE TITLE
CTRL + Click on link in script:src or link:href can't find the file.

### ISSUE THREAD

**Issue by felixpis** [Microsoft/vscode#13688]
- VSCode Version: 1.6
- OS Version: Windows 7

Steps to Reproduce:

1. Open html file
2. CTRL + Click on link of script or css

**Comment by aeschli** [comment]
@felixpis Can you add code snippet that shows an example?

**Comment by felixpis** [comment]
I see that problem is when path starts with "/"
<link href="/test/style.css" rel="stylesheet">
If I set relative path so it's ok
<link href="../test/style.css" rel="stylesheet">
It worked in 1.5 version

**Comment by aeschli** [comment]
I fixed the link resolving so that when a link is absolute (starts with /) it is resolved to the workspace path.

**Comment by felixpis** [comment]
Great! Thanks! :)
