### ISSUE TITLE
C# multiline function header syntax highlight promlem

### ISSUE THREAD

**Issue by vladtcvs** [microsoft/vscode#136977]
If I declare function with multiple lines in header, syntax highlight is broken
![image](https://user-images.githubusercontent.com/3390973/141345292-4f2b0240-c122-43f5-a309-84386faa6c2e.png)

Single-line function headers have correct highlight:
![image](https://user-images.githubusercontent.com/3390973/141345439-c0a6ebd2-4742-4358-87bf-5e9701b476b4.png)

**Comment by chrmarti** [comment]
Could you check if VS Code Insiders still has this problem? I think we have recently updated the grammar there. https://code.visualstudio.com/insiders/

**Comment by vladtcvs** [comment]
No, problem also exists.

Version: 1.63.0-insider
Commit: 3bd29c1d6c6ef5b6265614def99b7257b671ae19
Date: 2021-11-12T12:02:57.068Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-38-generic

**Comment by vladtcvs** [comment]
simplest example with the problem:

```
using System;

namespace Test {
	class Test {
		public (int x, int y, int z)
		function(int a)
		{
			return (a, a, a);
		}

		public void foo()
		{
			var res = function(0);
			var x = res.x;
			var y = res.y;
			var z = res.z;
		}
	}
}
```

**Comment by alexr00** [comment]
Moved to the repo that we pull our C# syntax highlighting grammar from: https://github.com/dotnet/csharp-tmLanguage/issues/230
