### ISSUE TITLE
VSCode window not focussed opening a new file from file explorer

### ISSUE THREAD

**Issue by sumitkmr** [Microsoft/vscode#13697]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: ms-vscode.csharp-1.4.0

Steps to Reproduce:

1. Open VSCode
2. Open FileExplorer
3. Try opening some file in VSCode, it just flashes in the status bar but doesn't focus the vscode window.

**Comment by bpasero** [comment]
This got fixed in insiders. 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
