### ISSUE TITLE
Feature request: iterative code search

### ISSUE THREAD

**Issue by MichaelTontchev** [microsoft/vscode#136997]
I have a scenario where I need to search some code and open tasks based on complex results:

- Search for files that contain any of 3-4 different functions in them
- Concatenate that result set
- Within that combined result set, search for an OnCall attribute in those files
- Using this final list of results, determine whether the OnCall attribute has enough file coverage to be able to use it to open tasks for teams to update their usage of these functions

This is just one case where being able to execute further searches on an initial result set would have been useful.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/118128
