### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by chrisbguillermo** [microsoft/vscode#136924]
- Issue Type: `Bug`
- Extension Name: `typescript-language-features`
- Extension Version: `1.0.0`
- OS Version: `Darwin x64 21.1.0`
- VS Code version: `1.62.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by chrisbguillermo** [comment]
> Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.
> 
> Happy Coding!

It's unresponsive. It's taking unnecessarily too much time to run or activate. Thanks!

**Comment by mjbvz** [comment]
That's not enough information to work with. Please follow the issue reporting guidelines

For example, does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
