### ISSUE TITLE
VS Code sometimes inappropriately activates rust-analyzer extension

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#136981]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.63-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Have a non-rust workspace open
2. Install rust-analyzer extension
3. After a while, get an error message from the rust-analyzer about the workspace not being a rust workspace
4. VS Code reports in the Log (Extension Host) output channel that the extension is being activated because the workspace contains a Cargo.toml or rust-project.json file. There are no such files in the directory

```
[2021-11-11 07:36:29.219] [6c1e87d0-f23e-41b6-a6f4-40e6b45ec694] [info] ExtensionService#_doActivateExtension matklad.rust-analyzer, startup: true, activationEvent: 'workspaceContainsTimeout:*/Cargo.toml,*/rust-project.json'
```

I cannot always reproduce this even on the same workspace, and the rust-analyzer extension declares very reasonable activation events https://github.com/rust-analyzer/rust-analyzer/blob/d83b76d83461d99ec4a4eecd75283853d1c892a5/editors/code/package.json#L63-L70 so I suspect that VS Code is inappropriately activating the extension in this case. Please let me know if I can provide any additional logs to track this down.

**Comment by alexdima** [comment]
@joyceerhl I think you might be running into https://github.com/microsoft/vscode/issues/73656 given the `startup: true` part. This indicates that when you open the folder, we launch a file search for these filenames, but if the file search doesn't return in 7s we currently just activate the extension.
