### ISSUE TITLE
Ctrl+delete in integrated terminal maps to "enter" key

### ISSUE THREAD

**Issue by Ranguna** [microsoft/vscode#136994]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.62.1
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-10T00:23:38.003Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.14.16-arch1-1

Steps to Reproduce:

1. Open vscode
2. Open the integrated terminal
3. Write "some random text"
4. Move the cursor the the space between "some" and "random"
5. Press ctrl+delete

What was expected to happen:
6. the word "random" gets deleted, leaving "some text" in the terminal

What actually happened:
6. ctrl+delete is mapped to enter, the the line in the terminal is executed.

(for extra adrenaline and to free space on your disk, replace "some random text" with "rm -rf ~". PLEASE DON'T DO THIS, but I can imagine someone doing a destructive operation thinking that ctrl+delete will delete a word)

Also, the above steps are not reproducible in:
Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-20T00:21:59.656Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.14.16-arch1-1

**Comment by meganrogge** [comment]
logs when I press `ctrl+delete`
```
xterm.js: parsing data [5C
LogService.ts:62 xterm.js: parsing data 

LogService.ts:62 xterm.js: parsing data [91msome: The term 'some' is not recognized 
LogService.ts:62 xterm.js: parsing data 
[24;40H as a name of a cmdlet, function, script 
[24;40H file, or executable program.
LogService.ts:62 xterm.js: parsing data 

LogService.ts:62 xterm.js: parsing data [38;5;9mCheck the spelling of the name, or if a 
LogService.ts:62 xterm.js: parsing data 
[24;40H path was included, verify that the path 
LogService.ts:62 xterm.js: parsing data [m
[38;5;9m[24;40H is correct and try again.
LogService.ts:62 xterm.js: parsing data [?25l[m
PS C:\Users\merogge\repos\vscode>       [25;35H[?25h
```
logs when I press `enter`
```
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data [5C
LogService.ts:62 xterm.js: parsing data 

LogService.ts:62 xterm.js: parsing data [91msome: The term 'some' is not recognized 
LogService.ts:62 xterm.js: parsing data 
[24;40H as a name of a cmdlet, function, script 
[24;40H file, or executable program.
LogService.ts:62 xterm.js: parsing data 

LogService.ts:62 xterm.js: parsing data [38;5;9mCheck the spelling of the name, or if a 
LogService.ts:62 xterm.js: parsing data 
[24;40H path was included, verify that the path 
LogService.ts:62 xterm.js: parsing data [m
[38;5;9m[24;40H is correct and try again.
LogService.ts:62 xterm.js: parsing data [?25l[m
PS C:\Users\merogge\repos\vscode>       [25;35H[?25h
```

**Comment by meganrogge** [comment]
I think what you're looking for is Ctrl+backspace - that deletes the word before the cursor. @Ranguna

**Comment by meganrogge** [comment]
removing the duplicate keybinding for terminal send sequence fixes the issue 
![keybinding](https://user-images.githubusercontent.com/29464607/142792920-607fd25f-7370-4149-b1bc-860e14f03045.PNG)

**Comment by meganrogge** [comment]
sendSequence adds a new line, thus why it seems like enter is pressed

**Comment by meganrogge** [comment]
@Tyriar I think it would make sense to either change or remove this keybinding

**Comment by Ranguna** [comment]
@meganrogge Ctrl+backspace deletes a word before the cursor (to the left side of the cursor). What I'm describing, deletes a word on the right side of the cursor.

It's incredibly dangerous to have this mapping assigned to anything+backspace/delete, since backspace and delete are usually never related with these kind of operations. It can seriously lead to some pretty catastrophic scenarios and I would appreciate that any new keybindings would first get checked if they already exist as a native OS binding before being added to vscode, specially on the terminal.

I'm going to remove this on my end, thank you for all the info!

**Comment by Tyriar** [comment]
Thanks for the report and investigation, not sure how it was working at all but I fixed it to correctly send the sequence for alt+d (ESC + d).

**Comment by Ranguna** [comment]
Perfect, thank you <3
