### ISSUE TITLE
Show Whitespace Differences button does not work

### ISSUE THREAD

**Issue by M393** [microsoft/vscode#136971]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.62.1 (user setup)
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-05T10:57:55.946Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 6.1.7601
- OS Version: 
Windows 7

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/56256405/141321702-3783689c-a74a-4b94-b4e5-344ce3e277cc.png)

1. Open a versioned file and make a whitespace-only change
2. Click the small vertical blue line at the start of the text line to view the change inlined
3. Click the big button 'Show Whitespace Differences'
4. Nothing happens

**Comment by lszomoru** [comment]
@alexdima, I believe that you own the "Show Whitespace Differences" button. Is that button supposed to show up in the in-line diff view? I was under the impression that this button should only appear in the full diff editor. Thanks!
