### ISSUE TITLE
Hovering over disabled menu item doesn't keep the menu alive

### ISSUE THREAD

**Issue by anohren** [microsoft/vscode#136958]
Issue Type: <b>Bug</b>

Hovering over e.g. "file > open recent > reopen closed editor" when "reopen closed editor" is grayed out will make the menus disappear after a timeout. Also happens with other built-in disabled menu items.

It only happens if the disabled item is the *first* item you hover over in that submenu.

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:18:44.904Z)
OS version: Linux x64 5.13.0-21-generic snap
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz (4 x 2425)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 1, 0|
|Memory (System)|3.74GB (1.14GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id f338a353-05bd-46e4-b956-1195ec2c8eee|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-wayland|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-wayland|
|XDG_SESSION_TYPE|wayland|
</details>Extensions: none

**Comment by sbatten** [comment]
seems like an upstream issue for https://github.com/electron/electron

**Comment by deepak1556** [comment]
Unable to repro with latest stable `1.74`
