### ISSUE TITLE
The branch list appears with a delay

### ISSUE THREAD

**Issue by Yadro** [microsoft/vscode#136975]
Issue Type: <b>Bug</b>

When I press on the branch button I see that the branch list appears with a delay (there are about 1000 branches)

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T09:23:14.144Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 4.4.114-50

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
material-icon-theme|PKi|4.10.0
vscode-todo-highlight|way|1.0.5
material-theme|zhu|3.13.2
template-generator-vscode|Den|0.4.1
gitlens|eam|11.6.1
json-pretty-printer|eus|1.1.0
git-graph|mhu|1.30.0
vscode-typescript-tslint-plugin|ms-|1.3.3
language-stylus|sys|1.13.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by Yadro** [comment]
Please have a look at screencast:
![recording 2](https://user-images.githubusercontent.com/3994873/141954206-40f801cf-f61a-4065-8421-02a4409ef41a.gif)

Note: I use remote-ssh extention (https://code.visualstudio.com/docs/remote/ssh)

**Comment by Yadro** [comment]
I've also created empty repo with 1k branches on remote machine, but delay didn't reproduce.

**Comment by lszomoru** [comment]
@Yadro, apologies for not getting back to you on this until now. Are you still experiencing this issue? Given that we are unable to reproduce the problem in an empty repo with 1k branches I would say that there is something specific to the repository where this occurs. One thing that you could try is to use the `git.checkoutType` setting to control the types of references that are being shown to reduce the list.

**Comment by lszomoru** [comment]
Closing the feature request due to inactivity.
