### ISSUE TITLE
Microsoft VS Code\Code.exe -e not work after update

### ISSUE THREAD

**Issue by kosday** [microsoft/vscode#136951]
Issue Type: <b>Bug</b>

I have an extension that uses the XMLHTTPRequest library to make requests to an API. These requests are made synchronously. Since the last update 1.62.1 the library has stopped working, tracing the code I have seen that the problem is in the following line:

syncProc = spawn(process.argv[0], ["-e", execString]);

Where:
process.argv[0]= InstallPath\Microsoft VS Code\Code.exe
execString= the code to be executed. 

The execString code works correctly if you run it in a new vscode instance but not using the Code.exe -e command ...

The spawn function 

var spawn = require("child_process").spawn;

returns nothing in stdout or stderr but an output code 1.

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (2 x 3599)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.99GB (4.05GB free)|
|Process Argv|mvbasiclinkar --crash-reporter-id cbf6abe8-7288-4d68-90a2-4adb464763ad|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
mvbasiclinkar|kos|1.0.6
csharp|ms-|1.23.16
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
microsoft-office-add-in-debugger|mso|0.2.0
sqltools|mtx|0.23.0
vscode-powerquery|Pow|0.1.23
java|red|1.0.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by chrmarti** [comment]
You need to pass `--ms-enable-electron-run-as-node` to the `Code.exe` in addition to setting `ELECTRON_RUN_AS_NODE=1`. This is to fix security issue https://github.com/microsoft/vscode/issues/136771.
