### ISSUE TITLE
Snippet shortcuts are now buried in 1.6.0.

### ISSUE THREAD

**Issue by jkyoutsey** [Microsoft/vscode#13694]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:28:55.412Z)
- OS Version: Darwin x64 15.6.0
- Extensions: LaurentTreguier.vscode-simple-icons-0.1.6, PKief.material-icon-theme-1.1.1, UVBrain.Angular2-0.3.5, eg2.tslint-0.5.39, hnw.vscode-auto-open-markdown-preview-0.0.3, johnpapa.Angular2-1.0.2

My user snippet shortcuts are now so buried under other things that they take as much time to find as just typing in the snippet!

Steps to Reproduce:

1. Add a user code snippet for TypeScript
	"Import Component": {
		"prefix": "ic",
		"body": [
			"import { $2 } from \"$1\";$3"
		]
	},
2. Now try to use that code snippet in a ts file:

![image](https://cloud.githubusercontent.com/assets/3846466/19360668/ad75cdf4-913c-11e6-90f4-c37917f30328.png)

Where is my shortcut?

If you scroll all the way down you can find it near the end of the intellisense list:

![image](https://cloud.githubusercontent.com/assets/3846466/19360644/92e559fa-913c-11e6-99b1-d18113067e55.png)

Snippets shortcuts should be the first things offered.

**Comment by jrieken** [comment]
That was done on purpose: https://github.com/Microsoft/vscode/issues/10467. Please provide feedback there such that every involved is in the loop
