### ISSUE TITLE
HTML Tag suggestion in JS file is not shown in latest vscode insider

### ISSUE THREAD

**Issue by rogueanx9** [microsoft/vscode#136940]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.63.0-insider (user setup)
Commit: 3a79384dbf81dc6eba781ff669996d2042ca3b72
Date: 2021-11-11T05:15:37.996Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Open any js file (or create new js file)
2. Type some HTML tag (h1, span, img, etc)
3. No Html Suggestion show

Additional Info:
2 days ago, this feature still working.

Image: (All extension disabled)
![image](https://user-images.githubusercontent.com/59089013/141263780-3604c077-2bbb-4146-ac2a-89fea2a8c43c.png)
![image](https://user-images.githubusercontent.com/59089013/141263845-b8020034-7ce3-450b-a3fe-30ec1d8cf530.png)

**Comment by mjbvz** [comment]
Here's what I see in a new project:

![Screen Shot 2021-11-11 at 9 15 50 AM](https://user-images.githubusercontent.com/12821956/141340622-fbb4e5ce-721f-4671-8f9e-e077f55d44ca.png)

Please share a project that demonstrates this issue

**Comment by rogueanx9** [comment]
I am sorry there is some misunderstanding on my end. I try with js function, it works as intended. Maybe I will recheck my project file as it uses js function but does not show any suggestion. Sorry.

![image](https://user-images.githubusercontent.com/59089013/141396381-92e2e5c8-447e-4e40-b162-3e614904c8bf.png)
