### ISSUE TITLE
wish to set the display 0x00008000 to 0x0000_8000, just display

### ISSUE THREAD

**Issue by wxj1819** [microsoft/vscode#136915]
When programming, 0x00008000 is not easy to read. I wish to set the display 0x00008000 to 0x0000_8000, which is only a display, and the code is still 0x00008000 when the code is actually saved.

**Comment by chrmarti** [comment]
You would need that feature in the programming language you are using first. Only then can VS Code adopt that support. Closing as upstream.

**Comment by wxj1819** [comment]
> You would need that feature in the programming language you are using first. Only then can VS Code adopt that support. Closing as upstream.

I use C language to program, and I often write some register addresses in the code

**Comment by chrmarti** [comment]
C doesn't have digit separators from what I read.
