### ISSUE TITLE
open folder on diconnected network drive fails and removes folder from recent list

### ISSUE THREAD

**Issue by Osturrock** [Microsoft/vscode#13699]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: alefragnani.numbered-bookmarks-0.5.0, donjayamanne.githistory-0.1.0, dzannotti.vscode-babel-coloring-0.0.4, hbenl.vscode-firefox-debug-0.6.6, HookyQR.beautify-0.4.0, humao.rest-client-0.8.5, lukehoban.Go-0.6.44, MattiasPernhult.vscode-todo-0.8.0, mohsen1.prettify-json-0.0.3, ms-vscode.Theme-MaterialKit-0.1.1, robertohuertasm.vscode-icons-3.0.4, Tyriar.lorem-ipsum-1.0.0, zhuangtongfa.Material-theme-1.0.3

I have my development folders on a VM and use VS Code from my Windows machine. The folders are shared but I need to provide my credentials occasionally when I reconnect. If I attempt to open the folder (e.g. from the Recent folder list or by typing \\server\share) whilst the drive is not authenticated, then VS Code logs a failure and removes the folder from the recent folder list.

Steps to Reproduce:

1. open a network share which is valid but which requires credentials to be provided as a folder from the recent folder list.
2. VS Code fails to open - does not provide a way of providing credentials.

Ideally, VS Code would detect the failure mode and allow credentials to be entered. At least, it would be nice if the folder was not removed from the recent list.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/13665
