### ISSUE TITLE
Enabling formatOnSave doesn't cause formatting provider to be invoked during save

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#13690]
- VSCode Version: 1.6.0
- OS Version: Windows 10

Steps to Reproduce:

1. Install [Dart-Code](https://marketplace.visualstudio.com/items?itemName=DanTup.dart-code)
2. Add `"editor.formatOnSave": true` to user options
3. Type some Dart into a dart file
4. Press `Alt`+`Shift`+`F` and observe formatting work
5. Insert some whitespace
6. Press `Ctrl`+`S`

Formatting works fine when I invoke it directly, but `provideDocumentFormattingEdits` never gets called when I press Save.

It works fine for JSON files, so I presume there's something specific about my extension, but I can't find anything in the docs suggesting I need to do anything specific to enable this?

I'm registering my formatter on activation like this:

```ts
context.subscriptions.push(vs.languages.registerDocumentFormattingEditProvider(DART_MODE, new DartFormattingEditProvider(analyzer)));
```

I've got a breakpoint in the first line of `provideDocumentFormattingEdits` but it never seems to trigger (full code for this file is [here](https://github.com/Dart-Code/Dart-Code/blob/18196fbc8586ec245acb4c0afbaa987efa37e513/src/providers/dart_formatting_edit_provider.ts)).

**Comment by DanTup** [comment]
Is it possible this only works with a range formatter? If so, is there any way this could be changed? I can't currently provide a range formatter and since the whole file is being saved it seems like an unnecessary restriction :(

**Comment by jrieken** [comment]
Good point - it current picks range formatters first, but that an unnecessary limitation.

**Comment by DanTup** [comment]
@jrieken When you say "first", do you mean it should still fall back to the doc formatter? (It doesn't seem to, but if that's the expectation I can do some further debugging)

**Comment by jrieken** [comment]
*first* as in only

**Comment by DanTup** [comment]
@jrieken Thanks, works great! 👍

**Comment by ramya-rao-a** [comment]
Verified using Go extension (from source with some changes tracked in https://github.com/Microsoft/vscode-go/issues/540) which also uses `provideDocumentFormattingEdits`
