### ISSUE TITLE
[Feature] Moving progress icon while scrolling down

### ISSUE THREAD

**Issue by rrmistry** [microsoft/vscode#136999]
It would be good if the progress icon of currently running cell could scroll down as well to be always visible

Visually this is especially useful for a cell with a long block of code.

For example (from Google Colab):
<img src="https://user-images.githubusercontent.com/25514145/140626019-de6e628d-a658-4866-8dac-66976e51c528.gif" width=42% />

**Comment by misolori** [comment]
I think this is the same request as https://github.com/microsoft/vscode/issues/130611#issuecomment-919582034

**Comment by rrmistry** [comment]
@misolori , agreed.

https://github.com/microsoft/vscode/issues/130611#issuecomment-919582034 makes this request redundant.

Thanks for all your efforts though!
