### ISSUE TITLE
changing the font size of the editor doesn't change it

### ISSUE THREAD

**Issue by Christophe98** [microsoft/vscode#136902]
Issue Type: <b>Bug</b>

When I change the font size of the editor in the settings under the user or workbench tab or when I change it in the settings.json file it doesn't actually change the size of the font in the editor. When I do this for the font size of the terminal in the settings.json file it works.

VS Code version: Code 1.62.1 (Universal) (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T09:23:14.144Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 2|
|Memory (System)|16.00GB (6.18GB free)|
|Process Argv|--crash-reporter-id 052ff7f5-83ae-41da-9de6-4691ef8a22cc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.9.4
fontsize-shortcuts|fos|1.5.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.0
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
material-theme|zhu|3.13.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by alexdima** [comment]
@Christophe98 Does this reproduce when opening a new window (File > New Window)? Perhaps you have defined workspace or folder level settings (they override the user level settings).

**Comment by Christophe98** [comment]
No, I opened a new window and in it another directory and I was able to change the font size. But when I opened the original directory(github repo) in the new window it reverted back to the smaller font size I cannot seem to change.

**Comment by alexdima** [comment]
@Christophe98 The folder that is problematic will have a `.vscode` folder with a file called `settings.json`. That is probably the one which is overriding your user settings. The solution is to remove the setting from `.vscode/settings.json`.

**Comment by Christophe98** [comment]
That worked. Thank you very much!
