### ISSUE TITLE
In diff view seeing output metadata changed, but metadata not changed.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#136909]
Ran a notebook that resulted in a diff in this cell: 
![image](https://user-images.githubusercontent.com/11685408/141213989-69c5b7ef-9729-495a-8a25-a855ddaa3c00.png)

As you can see it tells me output metadata changed. But if I look at the backing json, output metadata has not changed. Just literally the output. 

![image](https://user-images.githubusercontent.com/11685408/141214158-5ab699db-d967-4fa4-bf15-0589f9256d1d.png)

**Comment by rebornix** [comment]
This should already be fixed. Pushed a change recently to mitigate this. Feel free to reopen if you see this again.
