### ISSUE TITLE
Messses up with settings.json eventhough it's set for another file extension, not json

### ISSUE THREAD

**Issue by ibehnam** [microsoft/vscode#136930]
The extension ignores the file extension restriction. For example, I have set substitutions for `*.xyz` where `xyz` is not `json`. But the extension messes up with the settings.json too.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo


>  But the extension messes up with the settings.json too.

/needsMoreInfo 

Which extension does this? 

What VS Code version are you using? On what platform? 

What are the exact minimal steps to reproduce the issue?

**Comment by ibehnam** [comment]
> 
> 
> /needsMoreInfo
> 
> > But the extension messes up with the settings.json too.
> 
> /needsMoreInfo
> 
> Which extension does this?
> 
> What VS Code version are you using? On what platform?
> 
> What are the exact minimal steps to reproduce the issue?

Hi, thanks for your reply. Here's my VSC info:
```
  Version: 1.62.1 (user setup)
  Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
  Date: 2021-11-05T10:57:55.946Z
  Electron: 13.5.2
  Chrome: 91.0.4472.164
  Node.js: 14.16.0
  V8: 9.1.269.39-electron.0
  OS: Windows_NT x64 10.0.19043
```
Extension version: `v0.4.2`.

I have recorded a short gif to explain it better. As you can see, the extension 

![Latex-1636639377377](https://user-images.githubusercontent.com/58621210/141320908-7319c40b-87f7-4dd3-95f1-fc19e007d03f.gif)

**Comment by gjsjohnmurray** [comment]
/causedByExtension please report this to the author of the mystery v0.4.2 extension that you haven't told us the name of.
