### ISSUE TITLE
"shift+command+[" cannot be recognized by Mac

### ISSUE THREAD

**Issue by shirakiya** [microsoft/vscode#136934]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.1
- OS Version: macOS 12.0.1  - MacBook Pro（14inch, 2021）

Steps to Reproduce:

1. Nothing. It occurs in the default keyboard shortcut settings.

My investigations are below.

- The inputs of "shift+command+[" is recognized by macOS, but VSCode recognizes as "shift+command" only. (The logs in the Keyboard Shortcuts Troubleshooting window are pasted below.)
- "shift+command+[" shortcut is not overwrapped in Visual Studio Code.
- Keyboard dispatch is set as "KeyCode", it cannot resolve this problem.
- Even if all extensions are disabled, this problem occurs.
- The other "shift+command+[" is not found in macOS settings.

<details><summary>The logs in Keyboard Shortcuts Troubleshooting window.</summary>

```
# Try "shift+command+]" => recognized
[2021-11-11 15:20:34.941] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [shift,meta], code: MetaLeft, keyCode: 91, key: Meta
[2021-11-11 15:20:34.943] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [shift,meta], code: MetaLeft, keyCode: 57 ('Meta')
[2021-11-11 15:20:34.943] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2021-11-11 15:20:35.049] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [shift,meta], code: BracketRight, keyCode: 221, key: ]
[2021-11-11 15:20:35.050] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [shift,meta], code: BracketRight, keyCode: 89 (']')
[2021-11-11 15:20:35.050] [renderer1] [info] [KeybindingService]: | Resolving shift+meta+[BracketRight]
[2021-11-11 15:20:35.050] [renderer1] [info] [KeybindingService]: \ From 2 keybinding entries, matched workbench.action.nextEditor, when: no when condition, source: built-in.
[2021-11-11 15:20:35.208] [renderer1] [info] [KeybindingService]: + Ignoring single modifier meta due to it being pressed together with other keys.

# Try only "["
[2021-11-11 15:20:37.801] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: BracketLeft, keyCode: 219, key: [
[2021-11-11 15:20:37.802] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: BracketLeft, keyCode: 87 ('[')
[2021-11-11 15:20:37.802] [renderer1] [info] [KeybindingService]: | Resolving [BracketLeft]
[2021-11-11 15:20:37.803] [renderer1] [info] [KeybindingService]: \ No keybinding entries.

# Try "shift+command+["
[2021-11-11 15:20:39.648] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [shift], code: ShiftLeft, keyCode: 16, key: Shift
[2021-11-11 15:20:39.649] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [shift], code: ShiftLeft, keyCode: 4 ('Shift')
[2021-11-11 15:20:39.649] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2021-11-11 15:20:39.705] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [shift,meta], code: MetaLeft, keyCode: 91, key: Meta
[2021-11-11 15:20:39.707] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [shift,meta], code: MetaLeft, keyCode: 57 ('Meta')
[2021-11-11 15:20:39.707] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
```
</details>

The following gif shows that `open previousEditor` does not work though "shift + command + open_bracket" are pressed.
![Nov-11-2021 15-38-54](https://user-images.githubusercontent.com/7492121/141250148-749b6e76-73da-4a4d-b73f-638215bf4af3.gif)

<img width="887" alt="screenshot 2021-11-11 15 44 32" src="https://user-images.githubusercontent.com/7492121/141251099-b8ec4012-9f1d-4096-852b-4150df8c1d4d.png">

**Comment by alexdima** [comment]
@shirakiya This indicates that VS Code does not receive the keypress <kbd>shift</kbd>+<kbd>command</kbd>+<kbd>[</kbd> from the OS. There is nothing we can do on our side if the OS does not send us the keybinding. I have seen many reports in the past of similar issues, and they are always one of the following:
* the OS is configured to do something on this keybinding and therefore intercepts and "steals" it from all applications. You can try looking in detail at the OS settings around keyboard shortcuts.
* there is another application installed on the machine which is intercepting and "stealing" this particular keybinding.

**Comment by shirakiya** [comment]
I see what you mean, thanks to the quick response. Do you know of a good way to tell which other apps are stealing this shortcut?

**Comment by alexdima** [comment]
I'm sorry, I didn't read carefully that the keybinding works in other apps. Could you please try the following:

1) Download and open https://www.electronjs.org/fiddle for you platform
2) Load https://gist.github.com/deepak1556/69b8930b819f82115df50d0f466dd1ba via `Load Fiddle` button on the top right corner
3) Choose Electron version `v13.5.2` from top left dropdown
4) Run the app
5) With the input box focused, press `shift+command+[`
6) Take Screenshot

It would look something like this:
![image](https://user-images.githubusercontent.com/5047891/134949552-aa599bfb-f5f8-4f3e-94fe-cb814ab3ecf8.png)

**Comment by shirakiya** [comment]
@alexdima Don't worry. When I did the step 2, this error message was shown x(

<img width="1312" alt="screen 2021-11-11 17 42 41" src="https://user-images.githubusercontent.com/7492121/141266223-802e4cb3-8b46-40b8-ad2f-de62edf1f475.png">

**Comment by alexdima** [comment]
Here is the fiddle content. You can paste the following in `main.js`:

```js
// Modules to control application life and create native browser window
const {app, BrowserWindow} = require('electron')
const path = require('path')

function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      sandbox: true
    }
  })

  // and load the index.html of the app.
  mainWindow.loadURL('https://w3c.github.io/uievents/tools/key-event-viewer.html')

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  createWindow()
  
  app.on('activate', function () {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
```

**Comment by shirakiya** [comment]
I succeeded to take a screenshot, here you are. I tried "shift+command+[" in two times.

<img width="1545" alt="screen 2021-11-11 17 50 50" src="https://user-images.githubusercontent.com/7492121/141267793-7a582bf7-2931-4ef7-955c-fc6b79d2a181.png">

**Comment by alexdima** [comment]
@shirakiya Thank you for trying. This proves that all Electron applications do not receive this keybinding on your machine (not just VS Code).

Could you please also try using Chrome and opening https://w3c.github.io/uievents/tools/key-event-viewer.html . Is Chrome able to receive the keybinding?

**Comment by shirakiya** [comment]
1~4 are the group of first try and 5~8 are the group of the second try.

<img width="1349" alt="screen 2021-11-11 17 57 57" src="https://user-images.githubusercontent.com/7492121/141268610-de5ca218-c1cb-4ee8-913a-195456e7955e.png">

**Comment by alexdima** [comment]
@shirakiya Thank you for trying. This shows that all Chromium based apps do not get this keybinding on your machine (not just Electron applications, not just VS Code).

You could also try https://w3c.github.io/uievents/tools/key-event-viewer.html in Safari or in Firefox to see if those applications get the keybinding or not.

**Comment by shirakiya** [comment]
### Safari
Try in two times. "shift+command+[" works in Safari.
<img width="1214" alt="screen 2021-11-11 21 25 04" src="https://user-images.githubusercontent.com/7492121/141298095-fb2d0763-ca49-434d-8e39-d19961493027.png">

The following screenshot shows that I also tried "shift+command+]".
<img width="1214" alt="screen 2021-11-11 21 25 35" src="https://user-images.githubusercontent.com/7492121/141298670-b771f195-2cf9-4c7e-8a12-58fe711c4240.png">

### Firefox
BracketLeft appeared!
<img width="1373" alt="screen 2021-11-11 21 34 17" src="https://user-images.githubusercontent.com/7492121/141298900-65ff8a25-7e32-46d7-9b61-f199f8117448.png">

**Comment by shirakiya** [comment]
For your information, this "shift+command+[" shortcut works in macOS 11.6 (MacBook Pro 13-inch 2016) with VSCode 1.62.1 and the same settings.  macOS Monterey may be doing bad.

**Comment by masakiaota** [comment]
I've had same problem with macOS Big Sur and Monterey. Not only VSCode but Electron apps didn't receive "cmd [" combination.
I fixed this with 3 times of Macintosh HD format and 3 times of macOS reinstallation. (Even if no other apps or extensions is in my Mac, I encountered this issue 2 times).
I don't know the reason why I could fix this but I can suggest the following steps.

1. Update the macOS to latest version.
2. Shutdown and boot with "cmd R".
3. reinstall macOS. (macOS reinstallation don't erase your data. Format Macintosh HD if you want to erase yours.)

**Comment by shirakiya** [comment]
I realized the input "shift+command+fn+[" works like "shift+command+[" shortcut.

**Comment by alexdima** [comment]
@shirakiya Looking again at the screenshots you have from Safari I think both `shift+command+]` and `shift+command+[` do not work in Safari. That is because they are browser shortcuts to move focus to the next tab/previous tab. But I can see from the Firefox screenshot that `shift+command+[` worked in Firefox. I honestly don't know why we would not receive the keybinding on your machine, but I can only believe it is an OS configuration problem. I will close this issue because there is nothing we can do on our side to improve things.
