### ISSUE TITLE
Broken support with github

### ISSUE THREAD

**Issue by werlang** [microsoft/vscode#136907]
Issue Type: <b>Bug</b>

Use any command that require github authentication. Vscode will hang forever.

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.22494
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.36.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (5.29GB free)|
|Process Argv|--crash-reporter-id 88f3837b-95e0-4fea-84db-3bb0abc2dc6d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: local_VM|
|OS|Linux x64 3.10.0-1160.36.2.el7.x86_64|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (4 x 2995)|
|Memory (System)|1.79GB (0.54GB free)|
|VM|100%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
debugger-for-edge|msj|1.0.15
Bookmarks|ale|13.2.2
c-cpp-compile-run|dan|1.0.15
githistory|don|0.6.19
docker-explorer|for|0.1.7
vscode-mysql|for|0.4.1
easy-less|mrc|1.7.3
es6-css-minify|olb|3.3.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate - see https://github.com/microsoft/vscode/issues/136873#issuecomment-965402902 for advice.

Will be fixed in upcoming 1.62.2
