### ISSUE TITLE
Notifications: fully show source details even when buttons are large

### ISSUE THREAD

**Issue by xmnboy** [microsoft/vscode#136989]
Issue Type: <b>Bug</b>

A call to `showInformationMessage(message: string, ...items: string[])` that includes a list of "items" to be presented as "action" buttons covers the "Source: name-of-extension" message. Compare the resulting toast message to a call to `showInformationMessage()` that does not include any action buttons. 

There are actually two issues:

* the action buttons are placed such that you cannot read the "Source: name-of-extension" string added to the bottom of the notification message (particularly if there are a lot of buttons or they include a lot of text)

* there are no `^` and `v` controls to collapse or expand the notification message

The first bullet is the bigger issue, thus the name of this issue.

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:56:50.217Z)
OS version: Linux x64 5.4.0-90-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|3.84GB (0.15GB free)|
|Process Argv|--no-sandbox --crash-reporter-id b1f9ded4-f94e-4ecd-be87-f57354ae91ce|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
fortran|Gim|0.2.0
devcloud|int|0.0.5
oneapi-analysis-configurator|int|0.1.2
oneapi-environment-configurator|int|0.2.2
oneapi-gdb-debug|int|0.1.0
oneapi-samples|int|0.0.37
vscode-oneapi-devcloud-connector|int|0.1.2
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
cpptools|ms-|1.7.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by xmnboy** [comment]
Here are two images with examples of what I mean. The first image shows two notification toasts, one that calls with the `...items: string[]` parameter and one that does not. Notice the toast without the `...items: string[]` includes the collapse (`v`) control and the other does not. Without the `v` control in the notifications that include buttons it's hard to manage situations with a large number of notifications (due usually to ignoring and/or procrastinating 😃)
![vscode-toast-no-toggle](https://user-images.githubusercontent.com/1023095/142329127-8f8d29e1-1ee2-408e-91c1-a0e83fb3fe0d.gif)

This second image does a better job of showing how the buttons obscure the "Source:" of the notification. That "Source:" line at the bottom of the notification is very helpful, especially if you have a number of notifications stacked up, so you can get some useful context for the message.

![vscode-toast-three-sets](https://user-images.githubusercontent.com/1023095/142331168-7c1ec4cb-9d15-4922-9002-ee65d70fa92d.gif)

I logged this issue as a "bug" but I would consider it to be a usability issue, not so much a "bug" since the functionality is not broke, it's just the presentation that is impeding on the usability.

**Comment by bpasero** [comment]
So what is the suggestion to improve this? Btw I think you can still hover over the source label to see it in full.

**Comment by xmnboy** [comment]
Modify the layout of the "Source: name-of-extension" message and the "action buttons" so you can read the "Source: name-of-extension" string without interference from the "action buttons."

It would also be nice if the `^` and `v` controls were also included in a notification message that includes "action buttons," but that is a lesser issue.

**Comment by bpasero** [comment]
//cc @misolori
