### ISSUE TITLE
Unable to install via Windows 11 Store

### ISSUE THREAD

**Issue by bnkamalesh** [microsoft/vscode#136962]
- VS Code Version: -
- OS Version: Windows 11 Pro, build: 22000.318

Unable to install from the Windows Store, other apps on the store work fine.

```
The connection was lost during download
Code: 0x80072EE2
```

![image](https://user-images.githubusercontent.com/1092882/141314760-d40146aa-61b2-42f0-9aea-923d5e0efa19.png)

**Comment by sbatten** [comment]
@bnkamalesh, is this reproducing today?

**Comment by bnkamalesh** [comment]
@sbatten does not look like an issue anymore! Thanks for the help.
