### ISSUE TITLE
Git stop working

### ISSUE THREAD

**Issue by aluchitskiy** [microsoft/vscode#136943]
Issue Type: <b>Bug</b>

I updated today and 

git checkout -b new-branch 

does not show new branch.

git commit

also don't do nothing.

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.41GB free)|
|Process Argv|--crash-reporter-id 3f9486de-7844-4a8c-a7b8-5d3cb3cfd61d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3407)|
|Memory (System)|12.40GB (8.19GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
vscode-react-typescript|inf|1.3.1
Angular2|joh|12.0.0
remote-wsl|ms-|0.58.5
html5-boilerplate|sid|1.1.1
swyx-react-typescript-snippets|swy|1.0.19
ReactSnippets|xab|2.4.0
githistory|don|0.6.19
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/136837#issuecomment-966107817 for a workaround.
