### ISSUE TITLE
Duplicate entry in symbols view

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#13691]
- VSCode Version: 1.7 Insider
- OS Version: OS X 10.11.6

This is for `vscode.d.ts`. Seems both VSCode and TS extension are providing the symbols.

![image](https://cloud.githubusercontent.com/assets/4033249/19358545/23b07f9e-912b-11e6-92b1-749247c9a08b.png)

**Comment by waderyan** [comment]
@octref thank you for opening this issue. 

@dbaeumer any idea why this would be happening? I could use your help in investigating to see if this is something on our end or on TS's end.

**Comment by dbaeumer** [comment]
This is a problem in the tsserver land. I added work around code for this for 2.0.3 server and in 2.0.6 tsserver has a fix for this. It is the same as the bug we have for JS. Feel free to mark as duplicate.

**Comment by dbaeumer** [comment]
![capture](https://cloud.githubusercontent.com/assets/1931590/19392071/7b87ee6e-922f-11e6-85bd-0c2a48152a60.png)
