### ISSUE TITLE
Feature: Allow individual bracket types to be colored separately like Bracket Colorizer 2 "colorMode" "Independent"

### ISSUE THREAD

**Issue by bbugh** [microsoft/vscode#136979]
Hi 👋🏻 I'm excited about the new built-in bracket color pairs, but it seems to be missing a major feature of Bracket Pair Colorizer 2 - individual bracket types have their own colors. This is enabled by setting `"bracket-pair-colorizer-2.colorMode": "Independent". 

For example, if the colors are "purple, blue, yellow", it would look like this:

```
{ 🟣                 // purple
    { 🔵             // blue
       [ 🟣          // purple, starting over!
          { 🟡       // yellow
              [] 🔵  // blue
          } 🟡       // yellow
       ] 🟣          // purple
    } 🔵             // blue
} 🟣                 // purple
```

This is super helpful for knowing what scope you're in, like for -> function -> class, or for parsing your JSON object -> object -> array -> array.

But the new VS code feature colors all brackets regardless of their nesting, and I don't see an option for independent coloring, so that's the feature request! It does this:

```
{ 🟣                 // purple
    { 🔵             // blue
       [ 🟡          // purple, starting over!
          { 🟣       // yellow
              [] 🔵  // blue
          } 🟣       // yellow
       ] 🟡          // purple
    } 🔵             // blue
} 🟣                 // purple
```

Thanks for reading and the amazing vscode!

**Comment by hediet** [comment]
/duplicate #131027

Thanks for the example!
