### ISSUE TITLE
editors open with large font size

### ISSUE THREAD

**Issue by mark-hahn** [microsoft/vscode#136908]
Issue Type: <b>Bug</b>

For some time my font size inside editor windows has been larger than I left it when I open a new window.  I set up a keyboard shortcut to change the size and I use it every time I open a window.  I don't remember if I made this shortcut before or after the problem started.

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (22.16GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/mlap/apps/toy-cam --crash-reporter-id e91815df-8fb2-44a9-9518-77c16318fe2d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-gcode-syntax|app|0.6.2
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.3.2
gitlens|eam|11.6.1
vscode-pull-request-github|Git|0.32.0
base64viewer|Jas|1.2.1
better-cpp-syntax|jef|1.15.10
select-highlight-minimap|mde|0.1.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.1
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.5090
vsliveshare-audio|ms-|0.1.91
platformio-ide|pla|2.4.0
LiveServer|rit|5.6.1
vscode-3dviewer|sle|0.2.2
linter-marlint|tra|1.2.1
cmake|twx|0.0.17

(1 theme extensions excluded)

</details>

**Comment by mark-hahn** [comment]
Imagine an editor with font size 10.  Now imagine one with font size 12.  The former is what I see when closing the window and the latter when I open the window.  I don't see how screen shots could make that clearer.

If no one else is seeing this then I understand I will have to exert some effort to track down the circumstances.  I'll give it a try.

**Comment by bpasero** [comment]
Thanks
