### ISSUE TITLE
Where is `vscode.proposed.d.ts`?

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#136964]
The `vscode.proposed.d.ts`-file has been split up into separate files, each representing one proposal. This enables scoped access to proposals (see  https://github.com/microsoft/vscode/issues/131165 for details and discussion) 

Extensions need to opt into specific proposals via the new `package.json#enabledApiProposals`-property. The `enableProposedApi`-property will stop working soon.

### Migration Guide

1. First, validate that you still need proposed API access. Often proposals have been finalized and using proposed API isn't needed anymore. Try this:
   1. get latest `vscode.d.ts` via `@types/vscode` or `>npx vscode-dts main`
   2. delete the `vscode.proposed.d.ts`-file
   3. compile your project
   4. iff there are no errors, you are done. You can also delete the `package.json#enableProposedApi`-property. 
   5. go to step 3 ❗ 
   
1. You have validated that your extension still depends on proposed API. Do the following:
   1.  Spell out each proposal you want at `package.json#enabledApiProposals`. It's this property that enables proposals! 
   1. delete the `vscode.proposed.d.ts`-file
   2. get latest [`vscode-dts`](https://www.npmjs.com/package/vscode-dts) and run `npx vscode-dts dev` to fetch the proposal-definitions you need. 
   5. go to step 3 ❗ 

1. More tricky is proposed API usage that isn't TypeScript, namely proposed contribution points or properties of `package.json`. This is fortunately rare and but some manual labor and diligence is needed. Check the `vscode.proposed.contribXYZ.d.ts` files for `package.json`-properties you are using and add the proposal names to the `package.json#enabledApiProposals`-property

##### Sample

This is a sample commit https://github.com/microsoft/vscode-anycode/commit/cf73d4de8b0d6efca9da9212833be298568fc3ea that migrates anycode onto a specific API proposal.

##### Is this a breaking change?

Not yet. For now we are breaking up `vscode.proposed.d.ts` but we still honor the `enableProposedApi`-property for a bit. So, you likely see TypeScript compile errors but the runtime behavior isn't changed yet. 

##### Are changes to `package.json` and to `vscode.proposed.XYZ.d.ts` needed?

The changes to `package.json#enabledApiProposals` are absolutely needed, they are the truth while `dts` files are "only" needed for the TypeScript compiler. 

##### What about `package.json#enableProposedApi`

When your extension is enabled via our `product.json`-file you can safely remove the property. VS Code will enable your extension, also older version which don't support `enabledApiProposals` yet.

**Comment by daimor** [comment]
```
npx vscode-dts main
Downloading vscode.d.ts
To:   /Users/daimor/git/vscode-cos/vscode.d.ts
From: https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/vscode.d.ts
(node:29175) UnhandledPromiseRejectionWarning: Failed to get https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/vscode.d.ts
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29175) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29175) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jrieken** [comment]
Yeah, very sorry about that. We have trouble releasing `vscode-dts`. In the meantime you have two options

*  run `vscode-dts release/1.62`, or
* copy the file(s) from here: https://raw.githubusercontent.com/microsoft/vscode/main/src/vscode-dts/vscode.d.ts

**Comment by daimor** [comment]
Well, and for the proposed APIs, previously I had just this in my package.json
```
    "download-api": "vscode-dts dev",
    "postdownload-api": "vscode-dts master",
    "postinstall": "npm run download-api"
```
which I where I would need to change master to main
```
    "download-api": "vscode-dts dev",
    "postdownload-api": "vscode-dts main",
    "postinstall": "npm run download-api"
```
But, if I would need to select a particular proposes to download, how to find those names?

**Comment by daimor** [comment]
So, probably just by simple search in vscode-dts folder

**Comment by jrieken** [comment]
> So, probably just by simple search in vscode-dts folder

Yes - I assume that future proposal issues will link to their corresponding definition file. There is also IntelliSense for  `package.json#enabledApiProposals` listing all proposals that are known to that particular build. Last, there is the idea to treat the `enabledApiProposals` as truth and fetch the corresponding files from them, see https://github.com/microsoft/vscode-dts/pull/10#issuecomment-966506896

**Comment by joyceerhl** [comment]
@jrieken will it still be possible for extensions to pass `--enable-proposed-api` at the CLI? It seems to not work in VS Code Stable at the moment.

**Comment by jrieken** [comment]
Yes, it will still be possible to use the `--enable-proposed-api` option but that isn't backwards compatible, e.g it will require to keep the old and new properties in package.json

**Comment by Krzysztof-Cieslak** [comment]
> Yes, it will still be possible to use the --enable-proposed-api option but that isn't backwards compatible, e.g it will require to keep the old and new properties in package.json

@jrieken, is there any CLI option for the new `enabledApiProposals` syntax? Or do we need to keep the old syntax too in our package.json if we want to give users the option to use proposed APIs?

**Comment by jrieken** [comment]
> @jrieken, is there any CLI option for the new enabledApiProposals syntax?

The "old", existing CLI option works for the new property. When passed it enables all proposals for an extension. However, it isn't backwards compatible, e.g when users have an old version of VS Code with a new version of your extension than it won't enable the "old world". Tho, I would argue that's a corner-case as the CLI option is intended for special cases.

**Comment by Krzysztof-Cieslak** [comment]
Thanks for the details @jrieken, that makes sense 👍 
Just to confirm - have those changes been released in the current stable version of VSCode (1.63.2)?

We do have user reporting that Code OSS 1.63.2 have problems with the latest Copilot (using `enabledApiProposals`) despite using `enable-proposed-api` CLI arg (in `argv.json`).  

https://github.com/github/feedback/discussions/6629#discussioncomment-2033599

**Comment by jrieken** [comment]
Yes, this should work with 1.63.2

**Comment by mjbvz** [comment]
Closing as we have shipped with the split up `vscode.proposed.d.ts` for a few iterations now
