### ISSUE TITLE
HTML NOT FUNCTIONG

### ISSUE THREAD

**Issue by peterccoxx** [microsoft/vscode#136980]
Issue Type: <b>Feature Request</b>

I am trying to code but the ai doesn't work correctly. what might be the problem?

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

**Comment by CodeCrazy-ywt** [comment]
Screenshot, please

**Comment by aeschli** [comment]
Closing the issue. Not enough information is provided.
