### ISSUE TITLE
Snippet doesn't work for cocos-effect

### ISSUE THREAD

**Issue by smallp** [microsoft/vscode#136938]
- VS Code Version:1.62.1
- OS Version: Mac 11.6

Steps to Reproduce:

1. Set setting:
```
    "files.associations": {
        "*.effect": "cocos-effect"
    },
```
Add snippets in cocos-effect.json:
```
{
	"smoothstep": {
		"prefix": "smoo",
		"body": "smoothstep($0,$1,$2);",
		"description": "nimei"
	}
}
```
2. Type `smoo` and nothing happens.
![image](https://user-images.githubusercontent.com/10028968/141262929-8664bb5f-7d5b-430c-879c-290b80ae66b7.png)

Disabling extensions is useless. Snippet works for js and others, except cocos-effect.

**Comment by jrieken** [comment]
What's the file's associated language? You can see that the the lower right bottom

**Comment by smallp** [comment]
Yep, I upload the wrong screenshot.
![image](https://user-images.githubusercontent.com/10028968/141394764-4088be32-5360-45fb-8dc1-43487496509a.png)

**Comment by smallp** [comment]
I know. Vs code doesn't have the language ID `cocos effect`. It cannot recognize this file. There is an extension that registers this language ID but changes something. I know what should I do.
