### ISSUE TITLE
WSL Tasks Do Not Inherit/Source Shell Environment

### ISSUE THREAD

**Issue by bramankp** [microsoft/vscode#136966]
Before the most recent update to 1.62.1 I could run tasks (tasks.json) that properly inherited my WSL shell's environment. Specifically ...

My .bashrc might contain something like
```
export PATH=${PATH}:/something/new/here
```
and a task that simply did
```
"command": "echo ${PATH}"
```
would reflect this setting. This seems to have changed and now tasks don't seem to get my proper environment (which obviously breaks a lot of them).

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/136791
