### ISSUE TITLE
`onDidChangeDiagnostics` different behavior when "extensionKind" `ui` running on remote workspace

### ISSUE THREAD

**Issue by microhobby** [microsoft/vscode#136955]
Issue Type: <b>Bug</b>

When using `languages.onDidChangeDiagnostics` in a extension "globally enabled" with the configuration:

```
"extensionKind": [ "ui" ],
```

some events, for example when using `DiagnosticCollection.clear` or `DiagnosticCollection.set` with a empty `Diagnostic[]`, are not being delivered when running from a remote workspace. 

A workaround is to force the remote installation:

```
"extensionKind": [ "workspace" ],
```

that way all events are delivered.

This looks like kind of bug to me, it was expected to behave the same in the local and remote workspaces.

VS Code version: Code - Insiders 1.63.0-insider (bef4dba21f68bbdb8d9f08fe04b2e1858597722b, 2021-11-10T07:59:05.913Z)
OS version: Windows_NT x64 10.0.22499
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2894)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.37GB (12.15GB free)|
|Process Argv|--crash-reporter-id 3d9c88e4-3dfe-4b4c-a1ea-3126556e988c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-CommPrev|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics (16 x 2894)|
|Memory (System)|15.63GB (12.31GB free)|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
better-comments|aar|2.1.0
icons-carbon|ant|0.2.4
QML|bbe|1.0.0
vscode-icontheme-nomo-dark|be5|1.3.6
bracket-pair-colorizer-2|Coe|0.2.1
arm|dan|1.5.2
el-vsc-product-icon-theme|ElA|0.1.8
vbnet|gor|1.0.2
output-colorizer|IBM|0.1.2
better-cpp-syntax|jef|1.15.10
bats|jet|0.1.7
vscode-icon-theme|jtl|1.6.6
fluent-icons|mig|0.0.14
theme-monokai-pro-vscode|mon|1.1.19
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
debugger-for-chrome|msj|4.13.0
material-product-icons|PKi|1.1.1
vscode-autohotkey|sle|0.2.2
vscode-il|sol|0.0.1
ayu|tea|1.0.5
vscode-icons|vsc|11.7.0
windows-nt-vscode-theme|was|0.0.9
vscode-cil-complete|wk-|0.0.5
material-theme|zhu|3.13.2
vscode-eslint|dba|2.2.2
gitlens|eam|11.6.1
EditorConfig|Edi|0.16.4
bash-ide-vscode|mad|1.11.0
diagnostic-related-information-sample|mic|0.0.1
linuxkerneldev|mic|0.4.2
vscode-docker|ms-|1.17.0
cpptools|ms-|1.7.1
powershell|ms-|2021.10.2
vscode-yaml|red|1.1.1
errorlens|use|3.4.0

(14 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30382699
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593cf:30376535
vsc1dst:30396469
vscexrecpromptc:30397557

```

</details>

**Comment by jrieken** [comment]
Likely a regression from https://github.com/microsoft/vscode/commit/6ef5dbec55f2eed2a1d3d1a337f16b688fc6b92c

**Comment by jrieken** [comment]
The extensionKind trick only works because than you increase the chances of being in the same extension host as the extension that generates in the diagnostics. The bug is the the mirror'ing ignores empty arrays to prevent double events.

**Comment by rzhao271** [comment]
What are some verification steps for this issue?
