### ISSUE TITLE
New file doesn't open from file explorer if there is already an VSCode instance running as Admin.

### ISSUE THREAD

**Issue by sumitkmr** [Microsoft/vscode#13696]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: ms-vscode.csharp-1.4.0

Steps to Reproduce:

1. Open VSCode as admin.
2. Now, try opening another file from file explorer.
It won't open.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/4921
