### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by Paulsonps** [microsoft/vscode#136956]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.56.2 (Universal)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z (6 mos ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
- OS Version: Darwin x64 20.6.0

Steps to Reproduce:

1. ERR Extension host terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, vscode.typescript-language-features, markis.code-coverage, ms-vscode.vscode-typescript-tslint-plugin, VisualStudioExptTeam.vscodeintellicode, vscode.debug-auto-launch, vscode.git, alexiv.vscode-angular2-files, BananaAcid.compile-superhero, ecmel.vscode-html-css, gornivv.vscode-flutter-files, teeLang.vsprettier, vscode.npm, circlecodesolution.ccs-flutter-color, pranaygp.vscode-css-peek, vscode.github, ms-vscode.js-debug, vscode.emmet, vscode.merge-conflict, vscode.testing-editor-contributions, bradlc.vscode-tailwindcss, nrwl.angular-console, vscode.github-authentication
2.
<img width="410" alt="Screenshot 2021-11-11 at 4 23 31 PM" src="https://user-images.githubusercontent.com/13959864/141305619-f876926a-cb9f-469b-b2a9-9107eac84c4a.png">

**Comment by chrmarti** [comment]
/needsMoreInfo

Does this occur with all extensions disabled? (`F1` > `Developer: Reload With Extensions Disabled` or `code --disable-extensions`)
