### ISSUE TITLE
Terminal font rendering in vscode is blurry  | vs code 1.62.1 with Intel HD Graphics 630 driver 30.0.100.9955

### ISSUE THREAD

**Issue by insinfo** [microsoft/vscode#136985]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.1
- OS Version: Windows 11 21H2 22000.318

Terminal font rendering in vscode is blurry  | vs code 1.62.1 with Intel HD Graphics 630 driver 30.0.100.9955

### vs code
![image](https://user-images.githubusercontent.com/12227024/141355066-76204cf2-89c9-45ad-9bac-a74a36a1d4f2.png)

### windows terminal
![image](https://user-images.githubusercontent.com/12227024/141355236-728bc84f-83d2-46d4-ace3-292f14d8eb99.png)

the rendering is only blurry in the terminal in vs code

**Comment by meganrogge** [comment]
does changing `terminal.integrated.gpuAcceleration` help?
