### ISSUE TITLE
Console height issues

### ISSUE THREAD

**Issue by seedtigo** [Microsoft/vscode#13698]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14942
- Extensions: bajdzis.vscode-twig-pack-1.0.0, dbaeumer.vscode-eslint-1.0.8

Steps to Reproduce:

1. Start a Grunt server
2. Save a file

Expected: console height be updated

Issue: the console does not update its height, if I scroll I can't see all lines. If I resize the console height it readjust itself

**Comment by Tyriar** [comment]
Can you provide a screenshot of the issue?

**Comment by seedtigo** [comment]
@Tyriar I think the problem was solved. After update VS Code I couldn't reproduce the problem, thanks.
