### ISSUE TITLE
Resolve Variable and Command Inputs after `preLaunchTask` or provide means of expressing Command Inputs dependency

### ISSUE THREAD

**Issue by josh-hemphill** [microsoft/vscode#136900]
Right now there's not a good way to have variables and command input variables specifically that depend on the `preLaunchTask` in the `launch.json` to set up environment variables that are needed to be substituted in the `env` and `args` of a launch configuration.

It might be a bit of a chicken-and-egg problem, but if there could be a way of postponing variable substitution (which would mean no use of variables in the pre-launch-task id) then that would resolve this.

**Comment by bpasero** [comment]
Should this issue close then?
