### ISSUE TITLE
Add Settings to Control Error/Warning/Info Highlights in Scrollbar

### ISSUE THREAD

**Issue by ooobii** [microsoft/vscode#136926]
Hi there! I am curious about the highlights within the scrollbar are shown for errors, warnings, and informational messages (listed in the "Problems" tab):
![image](https://user-images.githubusercontent.com/60083197/141235864-cbeb9dd2-5af0-4a11-b428-407f8c146e13.png)

These are signified by colors (red, yellow, and blue respectively) on the right side of the scrollbar, while git changes are located on the left.

It would be nice to be able to control the colors that these show _outside_ of theming (e.g. settings to control color / transparency of particular message levels), or to enable/disable certain highlights that are shown in the scrollbar.

**Comment by aeschli** [comment]
You can already customize the colors in the user settings:
```
	"workbench.colorCustomizations": {
		"editorOverviewRuler.warningForeground": "#f0f"
	}
```
Set them to transparent will hide them.

See https://code.visualstudio.com/api/references/theme-color#editor-colors for all color names (look out for `editorOverviewRuler`)

Not sure what additional settings could add to that. Please give an example of what you are missing.

**Comment by ooobii** [comment]
@aeschli thank you so much! I can't believe I missed this. Worked like a charm!
