### ISSUE TITLE
Go to definition does not work for network mapped drive

### ISSUE THREAD

**Issue by carlhua** [Microsoft/vscode#13693]
- VSCode Version: 1.6.0
- OS Version: Windows 10

Steps to Reproduce:

1. open any folder that is a network mapped drive
2. go to def on any item, takes extremely long time.

**Comment by bpasero** [comment]
@carlhua does it eventually work or not at all? Is it the same speed opening a file? Can you share a video? It is hard to know if the slowness happens from the language server or opening files in general.

**Comment by carlhua** [comment]
Yes eventually it works. It takes very very long time. Opening a file is not an issue as the search function searches all files ok. 

I should mention this is a Linux drive mapped via samba.

**Comment by bpasero** [comment]
Ok I suspect an issue with the language service then. @carlhua what files are you using?

**Comment by carlhua** [comment]
What is the language service if you can further explain?

It's .c and .h files. Typical c project.

**Comment by bpasero** [comment]
@carlhua I then suggest to report it to the C extension that is providing this feature. It seems to be the one taking long time here.
