### ISSUE TITLE
Python Multi-line Quote Creation Adds Extra Double Quote

### ISSUE THREAD

**Issue by dgomer** [Microsoft/vscode#13692]
- VSCode Version: 1.6.0
- OS Version: OSX 10.11.6

Steps to Reproduce:

1.  Create any Python file.
2. Try to create a multi-line quote, which in Python is indicated by `"""` on each side, like in the screenshot here:
![screen shot 2016-10-13 at 1 18 54 pm](https://cloud.githubusercontent.com/assets/13522377/19359309/a2b6f716-9147-11e6-9351-0ea6b192a88b.png)

3.  VS Code will attempt to double the final quotation mark, leaving you with one extra `"`:
![screen shot 2016-10-13 at 1 20 16 pm](https://cloud.githubusercontent.com/assets/13522377/19359346/cedfc78c-9147-11e6-9044-3c8e2d4c73b6.png)

**Comment by isidorn** [comment]
This should be handled by the python extension, so please file it here
https://github.com/DonJayamanne/pythonVSCode

In the meantime set 	`"editor.autoClosingBrackets": false`
in your settings
