### ISSUE TITLE
install golang plugin failed

### ISSUE THREAD

**Issue by Oscarzhao** [Microsoft/vscode#137]
Operating System: windows 10 x64
Two problems:
1. remind me "The 'godef' command is not available. Use 'go get -u github.com/rogpeppe/godef' to install.“ at the top.  However, godef.exe is already under %PATH%
2. Remind me "Analysis tools missing"  at the right bottom. If i click it, a remind on top "Some Go analysis tools are missing from your GOPATH. Would you like to install them?" comes out; choose "install", an empty page with title ”Output for 'Go'" comes out, and nothing happens then

**Comment by mattn** [comment]
You have to add `%GOPATH%\bin` into `%PATH%` maybe.

**Comment by lukehoban** [comment]
@Oscarzhao See https://github.com/Microsoft/vscode-go/issues/10 for details on this.  I believe this is the same issue so I'll close this one for now.
