### ISSUE TITLE
Source control (git) panel shows publish button too soon

### ISSUE THREAD

**Issue by robotdesigner4** [microsoft/vscode#137060]
Issue Type: <b>Bug</b>

When working on a merge that has conflicts, if you resolve the conflicts and stage the changes the new "Publish Changes" button appears over the contents of the source control panel. You still haven't committed the merge result.

`git status` shows that you've resolved all changes but still need to commit. The prior version showed that you had a number of staged changes in this state but you can't see that anymore.

VSCode rocks, and the git integration is so good I walked away from all other UI tools for git. This is one place where being a little too helpful caused some confusion though.

VS Code version: Code 1.61.1 (c13f1abb110fc756f9b3a6f16670df9cd9d4cf63, 2021-10-14T01:19:42.089Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 1700 Eight-Core Processor       (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (2.42GB free)|
|Process Argv|--folder-uri file:///c%3A/src/ECAP7 --crash-reporter-id 724458b0-23e1-4d2e-bd5a-40f7596a5bbf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
gitdiffer|aag|0.0.3
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|11.6.1
specgen|Ene|1.0.0
html-slim-scss-css-class-completion|gen|1.7.8
angular2-switcher|inf|0.3.4
git-graph|mhu|1.30.0
vscode-antlr4|mik|2.2.4
xml-format|mik|1.1.2
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
remote-containers|ms-|0.202.5
azure-account|ms-|0.9.10
powershell|ms-|2021.10.2
vsliveshare|ms-|1.0.5090
gitpatch|par|0.2.1
material-icon-theme|PKi|4.10.0
code-spell-checker|str|2.0.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by IllusionMH** [comment]
> VS Code version: Code 1.61.1

Is it still reproducible in latest stable version 1.62.2?

**Comment by robotdesigner4** [comment]
I think something else odd is going on here. I resolved all of the changes by "keep current" which meant that the index actually does match the current state of the branch. So it is mostly correct to show that there are no changes, although it leaves no way to complete the merge other than going to the command line and saying git commit -m "message".

It is an edge-enough case that it is probably not worth the time of the community. I'll close the issue.
