### ISSUE TITLE
Word missing from description of `workbench.welcomePage.walkthroughs.openOnInstall` setting

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#137027]
Issue Type: <b>Bug</b>

English text reads:

"When enabled, an extension's walkthrough will open upon install the extension."

It should end "upon install of the extension."

I will submit a PR.

VS Code version: Code - Insiders 1.63.0-insider (c1096372119bcf83b9bd8ccee96dcf266f35de76, 2021-11-11T13:18:41.690Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
![image](https://user-images.githubusercontent.com/6726799/141444152-c6644c14-612e-4546-a6ea-c1755f3c8882.png)

**Comment by JacksonKearl** [comment]
Thanks!

**Comment by IanMatthewHuff** [comment]
![image](https://user-images.githubusercontent.com/812783/144333594-eec43f58-95ca-4652-a3fa-13d091670b3e.png)
Verified. Thanks for the fix.
