### ISSUE TITLE
Editor hangs and cannot save document when editing JavaScript ES6 React files

### ISSUE THREAD

**Issue by mrkam** [Microsoft/vscode#13708]
- VSCode Version: 1.6.1
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Edit large JavaScript React ES6 files with a lot of various constructs, including JSX tags, `${somethin}`, spread operators, etc.
2. Have some mismatched tags
3. At some point it still continues to work but you no longer able to save file
4. Later it would stop responding and offer to reopen the window.

**Comment by mrkam** [comment]
Here is a particular code fragment:

```
const notHandled = row => row.handled < row.count;

export const HandledMatches = React.createClass({
    propTypes: {
        row: PropTypes.object.isRequired
    },
    statics: {
        key: 'Handled',
        title: '',
        sortField: "handled"
    },
    render: function() {
        const {row} = this.props;
        return (
            <HandledTD handled={row.handled} total={row.count}>
                {notHandled(row) ? <i className="orange warning sign fitted icon" title={`Match of ${row.failures} failures is not handled`}/> : ""}
            </HandledTD>
        );
    }
});
```

I was replacing `notHandled `with `notHandled(row)` inside `HandledTD` tag.

Version info:
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: alechp.react-toolbox-snippets-0.12.0, alefragnani.Bookmarks-0.9.2, cmstead.jsrefactor-0.5.3, donjayamanne.githistory-0.1.0, dzannotti.vscode-babel-coloring-0.0.4, formulahendry.auto-close-tag-0.3.3, formulahendry.auto-rename-tag-0.0.7, jameshrisho.redux-snippets-0.0.1, krizzdewizz.tag-rename-0.1.0, ledragon.d3-helpers-snippets-0.2.2, SirTori.indenticator-0.2.1, taichi.react-beautify-0.2.0, timothymclane.react-redux-es6-snippets-1.0.4, TwentyChung.jsx-0.0.1, vsmobile.vscode-react-native-0.2.0, xabikos.JavaScriptSnippets-1.2.0, xabikos.ReactSnippets-1.2.0

**Comment by mrkam** [comment]
Any recommendation on how to collect more debug info? It's happening way to often and is very disappointing. The app becomes partially responding. While being in hung I tried to open Developer Tools and pause execution. But Pause button becomes pressed and nothing happens after that. It is shown as not paused. Then I tried to record JavaScript CPU Profile. After pressing Stop it is still shown as "Recording..." and Developer Tools tabs ("Elements, Console, ,,,") are no longer switchable. Although the current "Profiles" tab is responsive...

**Comment by waderyan** [comment]
@mrkam thank you for opening this issue. 

Can you share your workspace or a minimal repo where the issue occurs? 

Can you start VS Code with extensions disabled (`--disable-extensions`). Does the issue still occur if all extension are disabled? 

@jrieken can you comment to @mrkam on how to provide debug info?

**Comment by jrieken** [comment]
@mrkam Are you using the `react.beautify.onSave` option from the `taichi.react-beautify-0.2.0` extension?

**Comment by mrkam** [comment]
I've disabled the extensions and wasn't able to reproduce the issue so far. I'm still watching for it.

This is my config file so far:
```
{
    "http.proxy": "...",
    "files.autoSave": "onFocusChange",
    "auto-close-tag.SublimeText3Mode": true,
    "editor.renderIndentGuides": true,
}
```

**Comment by mrkam** [comment]
I've also filed https://github.com/formulahendry/vscode-auto-rename-tag/issues/9 but I'm not sure if that particular plugin is causing the issue

**Comment by waderyan** [comment]
I'm going to close this for now. If it reappears please let me know and we'll re investigate. 

Thank you for opening the issue and for helping us make VS Code better.

**Comment by mrkam** [comment]
I still questions. 

Do you want to keep it vulnerable to extensions? Shouldn't it be protected somehow? What's most nasty about this is that editor continues to work while you can no longer save the file and you cannot notice when this "no longer possible" begins. Is it possible to add some level of protection? 

Also what are the tools to figure out which extension is responsible for this? Seems like switching them on and off by one is not very helpful and time consuming.

**Comment by vladimirivanoviliev** [comment]
Same issue on my side - started disabling the extensions one-by-one and in my case it appears to be the "SpellChecker 1.2.1" extension. This leads me to the question that @mrkam asked - why the VSCode is not protected in some way from the addons?

**Comment by waderyan** [comment]
@jrieken can you address @mrkam's question above? We run the extension in a separate process and strictly adhere to many separation of concern principles. I am surprised as @mrkam is that this could happen.

**Comment by jrieken** [comment]
My guess is that the following happens: (1) document is being saved, (2) formatter receives event, makes edits, and *saves*, (3) document is being saved, (4) formatter receives event make again changes (doesn't check for no-op), makes edits, and *saves* . That can go on forever. 

Extensions are separated well from the main side of things but we do allow extensions to call into the main side (like saving a document, appending data to an output channel, opening editors). In principle any call like that is a problem because if an extension goes crazy it puts load on the main side. There is some protected in place for that but it is a problem that is hard to solve. Feedback welcome

**Comment by mrkam** [comment]
@jrieken If that's what actually happens, then probably it may be detected, reported and stopped. What do you think?
