### ISSUE TITLE
Autocomplete of php class name is invalid

### ISSUE THREAD

**Issue by momala454** [microsoft/vscode#137061]
Issue Type: <b>Bug</b>

code :
```php
<?php

$this_is_a_test = true;

class ThisIsATest
```

Vscode is autocompleting the class name to $this_is_a_test instead of leaving it as it is

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.10.0-8-amd64
Remote OS version: Linux x64 3.10.0-1160.36.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (8.64GB free)|
|Process Argv|--crash-reporter-id e49b9d87-d333-41ad-a41a-a47c2c7ba436|
|Screen Reader|no|
|VM|22%|

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by roblourens** [comment]
VS Code's built in code completion is very naive. I recommend using one of the PHP extensions.

**Comment by momala454** [comment]
i am using intelephense, it doesn't make any change

**Comment by momala454** [comment]
is it possible to vscode be less naive instead of relying on third party plugins (which in this case doesn't help)

**Comment by momala454** [comment]
hello?

**Comment by roblourens** [comment]
You can file an issue on Intelephense if that's what you are using. The built-in support isn't going to improve however.
