### ISSUE TITLE
Visual problem or Visual issue

### ISSUE THREAD

**Issue by aghfree** [microsoft/vscode#137042]
hi, when i set my Visual Studio Code on maximum windows size, there is an visual problem or visual issue on top of the windows.

https://user-images.githubusercontent.com/47518385/141469880-50fb3824-d2c1-4f17-a472-942d7b128d6a.mp4

**Comment by aliasgharbabaeian** [comment]
I just restarted my windows and the problem solved

**Comment by sbatten** [comment]
@aliasgharbabaeian can you try to repro after launching with `--disable-gpu`?
