### ISSUE TITLE
CMakeUserPresets.json parsed incorrectly by "presetManager"

### ISSUE THREAD

**Issue by riffmasterv7** [microsoft/vscode#137052]
Diamond inheritance does not accepted by "presetManager", but parsed without errors.
CMake console is parsing same CMakeUserPresets.json successfully.

1) define preset1;
2) define preset2 and inherite it from preset1;
3) define preset3 and inherite it from preset1;
4) define preset4 with multiple inheritance, like:
      {
         "name": "preset4",
         "inherits": [
            "preset2",
            "preset3"
         ]
      }
5) preset4 will be successfully parser and verified by "presetManager":
"[presetController] Successfully validated presets in CMakeUserPresets.json"

6) But it won't be possible to select preset4 as nor configure preset, nor build preset;

[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version: 1.62.2 (user setup)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:56:38.428Z (17 hrs ago)
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

[OK] [Copy]

**Comment by IllusionMH** [comment]
/causedByExtension

VS Code doesn't work with `CMakeUserPresets.json` directly and functionality provided by an extension.
You should report this issue in extension's repo.

If you are sure that VS Code incorrectly works with JSON Schema for this file you should provide corresponding details.
