### ISSUE TITLE
Editor display and breadcrumb is misleading when a slow FileSystemProvider is used

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#137057]
Issue Type: <b>Bug</b>

To demonstrate, modify the fsprovider-sample so that the readFile method of the memfs scheme delays 5 seconds before returning.

A branch containing a suitable amendment is at https://github.com/gjsjohnmurray/vscode-extension-samples/tree/slow-memfs-read

Launch the amended extension in the Extension Host, and use Command Palette to run "MemFS: Setup Workspace" followed by "MemFS: Create Files"

In Explorer view, expand the workspace. Double-click on "file.css" and confirm its contents load after 5 seconds.

Now doubleclick on "file.html".

Observe that a new tab gets correctly created and selected, and the breadcrumb shows the correct filename.

:bug: the contents of "file.css" continue to display in the file area until after 5 seconds the FSP returns the new contents.

:bug: the section of the breadcrumb after the filename continues to display what it was previously showing for the first tab.

![junk](https://user-images.githubusercontent.com/6726799/141484765-c08f3a94-f137-454d-8baf-a422a61b343a.gif)

VS Code version: Code - Insiders 1.63.0-insider (3bd29c1d6c6ef5b6265614def99b7257b671ae19, 2021-11-12T12:04:20.740Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by jrieken** [comment]
Breadcrumbs update as the tab updates, the contents being wrong is a known issue

**Comment by gjsjohnmurray** [comment]
@jrieken I'm not seeing the breadcrumbs update completely. My gif show how everything up to and including the filename changes correctly as soon as the tab switches, but the part beyond file.html doesn't get cleared. Maybe that'll get fixed automatically once the contents problem gets resolved. I think the contents should initially become empty, or possibly after a debounce interval of, say, 200ms so as to avoid unnecessary flicker when the FSP is fast.

**Comment by jrieken** [comment]
Ah, now I see what you mean... Yeah, today the symbol portion doesn't clear when getting a new file but it updates once new symbols are computed. Strictly speaking that's unrelated to file switching and can also happen when removing all content from a file or when pasting a new code over some code.

**Comment by gjsjohnmurray** [comment]
Found #34697 as the original about contents being wrong during slow load. @bpasero proposed a timeout-driven clear in https://github.com/microsoft/vscode/issues/34697#issuecomment-330859598

**Comment by gjsjohnmurray** [comment]
> Strictly speaking that's unrelated to file switching and can also happen when...

@jrieken does it make sense to keep this one open to cover the breadcrumb problem?
