### ISSUE TITLE
Background/selection colour in Jupyter Notebook

### ISSUE THREAD

**Issue by AnettLangova** [microsoft/vscode#137085]
Issue Type: <b>Bug</b>

When I set colour theme Solarized light, I am unable to see in the Jupyter Notebook in input mode selected text. I think it is almost the same colour as the background colour. I guess it got worse after last update.

It would be useful to repair this bug. Thank you

![image](https://user-images.githubusercontent.com/56040351/141537752-f2cc78d8-7073-4f7e-8901-c11f5f4341d2.png)

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows
Restricted Mode: No

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3

</details>

**Comment by misolori** [comment]
Update the notebook editor background to make the line background stand out:

![image](https://user-images.githubusercontent.com/35271042/142027282-bebf8d7b-8143-43d9-bbf8-b75d901ac616.png)

**Comment by IanMatthewHuff** [comment]
@misolori was looking to verify this. Honestly the color of selected text is still really close to the background color. Is this enough contrast?
![image](https://user-images.githubusercontent.com/812783/144332531-65bb8b9e-8383-4a2f-9169-eb8de4c91e29.png)

**Comment by AnettLangova** [comment]
In my opinion, it is much better @IanMatthewHuff
