### ISSUE TITLE
Word wrap is applied to inline test error display where it probably shouldn't

### ISSUE THREAD

**Issue by jenom** [microsoft/vscode#137070]
Does this issue occur when all extensions are disabled?: No (e.g. needs Python testing)

- VS Code Version: 1.62.2
- OS Version: Windows 10 20H2 + WSL2 Ubuntu

Steps to Reproduce:

1. Enable Editor: Word Wrap -> wordWrapColumn
2. Run a pytest Python test with an error

The error message is displayed inline next to the method name. With **disabled word wrap** this extents the scrollable area horizontally as shown below: 
![grafik](https://user-images.githubusercontent.com/1188467/141512385-44b48ccc-66f2-41b9-842e-f022523b60e5.png)

With **enabled word wrap** this error message is wrapped as well such that for long error messages the editor view can become arbitrarily long, e.g.
![grafik](https://user-images.githubusercontent.com/1188467/141512565-56ce8b67-4e72-4d24-bb9b-202d071c9841.png)

Word wrap should probably only have an effect on the code and not change that behaviour or the inline display needs to be truncated. The peek view and mouse over tool tip show already the full error message properly formatted.

Example Code:
```
def test_long_error():
    text = "ಠ_ಠ " * 300
    raise RuntimeError(text)
```
edit: removed useless imports

**Comment by alexdima** [comment]
I believe this is intentional, otherwise horizontal scrollbars would be necessary.

**Comment by hediet** [comment]
Probably the test runner should shorten the inline value.

**Comment by jenom** [comment]
This probably the best solution as without word wrap it creates a very long horizontal scrollbar as can be seen below. The information value in this scenario is very limited so it could be shortened quite a lot.

![grafik](https://user-images.githubusercontent.com/1188467/141755607-4679d551-a13b-4677-9fdf-4ce4375fc5c7.png)
