### ISSUE TITLE
Issue in RTL languages in recent versions

### ISSUE THREAD

**Issue by YassineXM** [microsoft/vscode#137036]
![Untitled](https://user-images.githubusercontent.com/34407036/141463706-0fa2ff35-a6fa-43b9-9178-385f9121b55a.png)

this issue was not exist in previous versions

**Comment by alexdima** [comment]
@YassineXM Can you please provide the content also in text form?

**Comment by YassineXM** [comment]
`<option value="العربية">العربية</option>`

**Comment by SMSadegh19** [comment]
Hi! @alexdima 
Can I solve this issue as a good-first-issue?
Is it easy or hard for a first-time contributor?

**Comment by SMSadegh19** [comment]
In vscode editor if we inspect, we have this code:
```
<span dir="ltr">
    <span class="mtk1">
          &lt;option&nbsp;
    </span>
    <span class="mtk5">
          value
     </span>
    <span class="mtk1">
        =
     </span>
    <span class="mtk11">
        "العربية"
    </span>
    <span class="mtk1">
        &gt;العربية&lt;/option&gt;
    </span>
</span>
```
And as a result we see this:
![image](https://user-images.githubusercontent.com/45296858/147136504-b0582a7d-c395-4dec-b085-fe1de77d4711.png)

If we write this HTML code instead:
```
<span dir="ltr">
    <span class="mtk1">
          &lt;option&nbsp;
    </span>
    <span class="mtk5">
          value
     </span>
    <span class="mtk1">
        =
     </span>
    <span class="mtk11" dir="auto">
        "العربية"
    </span>
    <span class="mtk1">
        &gt;العربية&lt;/option&gt;
    </span>
</span>`
```
Then we see the result like this:
![image](https://user-images.githubusercontent.com/45296858/147137243-c9302f9d-ec2a-4977-8c63-74406bb44acd.png)

I've just added `dir="auto"` to the `mtk11` class.
