### ISSUE TITLE
A Javascript error occurred in the main process.

### ISSUE THREAD

**Issue by monoael** [microsoft/vscode#137046]
Does this issue occur when all extensions are disabled?: NA

- VS Code Version: 1.62.1 & 1.62.2
- OS Version: Windows 10 Enterprise 21H1 19043.1348

Steps to Reproduce:

1. Launch Visual Studio Code
2. A Javascript error occurred in the main process.

![image](https://user-images.githubusercontent.com/94178405/141472193-729f8a14-3b05-402e-84e7-2b84cd1862ca.png)

Whole \resources\app\out folder missing.

This happened to 5-6 users until now and they were working normally before two days.

**Comment by gjsjohnmurray** [comment]
Do those users have the same antivirus product on their workstations?

**Comment by monoael** [comment]
Windows Defender yes.
Strangely this did not happen to me.

**Comment by chrmarti** [comment]
Did the antivirus quarantine those files? Does reinstalling help?

**Comment by monoael** [comment]
There are no entries in Defender regarding Visual Studio Code.
A reinstallation resolves the issue.
