### ISSUE TITLE
Emmet does not work in js/jsx files for VS Code 1.62.2(Universal)

### ISSUE THREAD

**Issue by shiraz** [microsoft/vscode#137012]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.2
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Download VS Code v1.62.2 on a Mac.
2. Create an file in the path `pages/index.js`.
3. Create a simple functional component like:
```
function HomePage(props) {
  return (
    <div>       
        <title>NextJS Events</title>
    </div>
  );
}
```
4. Type `div.test` in the `div` and press Tab.
5. Observe that nothing happens.
6. Disable all extensions.
7. Restart VS Code.
8. Observe that the same issue occurs.

Notes:
I added the following code in settings.json and then restarted VS Code. The same issue occurs when I try to use Emmet.
```
{
   "emmet.includeLanguages": {
      "javascript": "javascriptreact"
    }
}
```

**Comment by rickyalmeidadev** [comment]
I've noticed the same, commenting here to keep up with any updates.

**Comment by rzhao271** [comment]
Emmet is an extension, so disabling the extensions wouldn't work.
I'm unable to reproduce the issue on 1.62.2 or Insiders (though I'm on macOS 11.6.1), unless you tried passing tab when there weren't any suggestions, in which case the setting `emmet.triggerExpansionOnTab` needs to be enabled.

**Comment by rzhao271** [comment]
\gifPlease

**Comment by BurnyLlama** [comment]
This is kinda what @shiraz means @rzhao271 :
![recording](https://user-images.githubusercontent.com/37349525/141655326-16f69f36-71b0-4144-a8e3-090e35744ac7.gif)

**Comment by BurnyLlama** [comment]
Basically emmet does not include the `emmet.includeLanguages`...

**Comment by BurnyLlama** [comment]
**I found a fix!**

I could solve this by enabling `emmet.triggerExpansionOnTab`:
```json
"emmet.triggerExpansionOnTab": true
```

I don't know why this setting has to be enabled for it to work, but it works!

@shiraz @rickyalmeidadev

**Comment by rzhao271** [comment]
This regression is from the extension not activating in time for those file types. For example, if you manually expand an abbreviation with the command in the command palette, then the extension activates, and suggestions show up again.

**Comment by matteing** [comment]
Yup, emmet stopped working on here as well for JSX. Latest version on macOS.

**Comment by preIdiot** [comment]
I am experiencing this issue after updating to version: 1.62.3

**Comment by gjsjohnmurray** [comment]
> I am experiencing this issue after updating to version: 1.62.3

@preIdiot the fix by @rzhao271 is in 1.63, so either use Insiders or wait for the next release, due in early December.

**Comment by TarasIvaschuk** [comment]
I tried "emmet.triggerExpansionOnTab": true on Windows though it couldn't help me (

**Comment by TarasIvaschuk** [comment]
So figured out the workaround. I opened a *.html file found Emmet working there. After heading back to javascript files they got the Emmet abbreviations working.  I do not know why but it helps

**Comment by preIdiot** [comment]
I switched to v1.61, everything is working fine on that.

**Comment by rzhao271** [comment]
Verification steps:
1. Add the following setting
```json
"emmet.includeLanguages": {
    "javascript": "javascriptreact"
}
```
2. Open a folder or workspace
3. Close all open editors and reload the window
4. Create a JS file
5. Do Steps 3 and 4 of https://github.com/microsoft/vscode/issues/137012#issue-1051532703

Expected: Emmet should activate more readily now, meaning that suggestions should show up during the last step.
Previous behaviour: Emmet wasn't activating when users opened a JS file, meaning suggestions would not show up.

**Comment by preIdiot** [comment]
Not working

https://user-images.githubusercontent.com/61873006/142968832-c5fd5db9-96ab-445a-b250-9af27649a062.mp4

**Comment by gjsjohnmurray** [comment]
@preIdiot your test seems to be done with Stable, so not 1.63 which is still Insiders.

**Comment by rzhao271** [comment]
@preIdiot you have to use https://code.visualstudio.com/insiders/

**Comment by aeschli** [comment]
Verified. You also need to make sure your file has set `JavaScript React` as language.

**Comment by sahilsuman933** [comment]
> **I found a fix!**
> 
> I could solve this by enabling `emmet.triggerExpansionOnTab`:
> 
> ```json
> "emmet.triggerExpansionOnTab": true
> ```
> 
> I don't know why this setting has to be enabled for it to work, but it works!
> 
> @shiraz @rickyalmeidadev

It worked for me
