### ISSUE TITLE
Error creating new notebook with "ctrl + n"

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode#137005]
## Environment data

-   VS Code version: 1.62.0 (Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.22000
-   Python and/or Anaconda version: conda, Python 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda (but N/A for issue)
-   Jupyter server running: Local

## Expected behaviour

1. Create a new file in VS Code with "ctrl + n"
2. Save the file as .ipynb file (would be nice if the UI changed immediately to a notebook interface, but that's not the bug being filed)
3. Close the file
4. Reopen the file, and file should open with notebook UI

## Actual behaviour

In step 4, file does not open with error "Unable to open '<filename>.ipynb': Unexpected token in JSON at position 0."

## Steps to reproduce:
Note: first method (ctrl+n) errors out, but second method (clicking "new untitled file") works
![Error creating new nb with ctrl n](https://user-images.githubusercontent.com/10833267/141385659-0ec15348-98c0-414c-8dfc-d2d31d809568.gif)

## Logs

N/A

**Comment by claudiaregio** [comment]
Related to https://github.com/microsoft/vscode/issues/114958 and https://github.com/microsoft/vscode/issues/81832 

@rebornix Can you close if this is covered in the issues above?

**Comment by byehack** [comment]
`Ctrl+Alt+Win+N`:

![image](https://user-images.githubusercontent.com/26390254/141457370-81d0f79e-1c5e-4b29-a26a-9bfa6a6f5c8a.png)

you can customize keybindings.

**Comment by roblourens** [comment]
That is indeed an invalid .ipynb file. I suggest creating it with the method that @byehack mentions (or File > New File...). The issues @claudiaregio mentioned are also relevant, thanks for linking.
