### ISSUE TITLE
VScode disappeared 

### ISSUE THREAD

**Issue by erlacla** [microsoft/vscode#137003]
I closed vscode and quickly shut down my laptop last night and might not have let vscode finish downloading all the automatic updates it does when you shut it off. Oops.
Then today when I went to code again, vscode was gone. It was like it had been completely uninstalled.
Anyone else had this happen?

**Comment by inrcode** [comment]
Yes, about 30 minutes ago my Windows 10 vscode disappeared after it failed to update itself when I closed the application. I did not shut down my computer, and looked but could not find the vscode executable or installation.  This is beyond bad.

**Comment by joaomoreno** [comment]
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by inrcode** [comment]
Yes I will try setting update.enableWindowsBackgroundUpdates to false, however I first need to re-install VSCode (and all my extensions!!), as it deleted itself last night during its failed auto-update.  Maybe the VSCode installer can first make a backup of the existing VSCode installation, and revert back to that if the update fails...just a thought.
