### ISSUE TITLE
Attach debugger to existing node.js process

### ISSUE THREAD

**Issue by dpkirchner** [microsoft/vscode#137084]
It would be useful to have a way to attach to an existing node.js process, perhaps by pid, and specifically one that was not started from within VSCode. There is a "Debug: Attach to node process" option, but it doesn't show all processes, and sometimes shows none.

This is related to this an already reported bug[0] and someone (in another issue that I can't find now) suggested this extension: https://github.com/aprilandjan/vscode-node-debug-process-picker but it no longer works (doesn't provide the documented command).

I'm calling it a feature request for this GH issue as it seems like it's not currently supported (or intended to be supported).

0: https://github.com/Microsoft/vscode/issues/10050

**Comment by dpkirchner** [comment]
Actually, I think I made a mistake. This should be filed under the vscode-js-debug project, shouldn't it? If so I'll move it over.

**Comment by connor4312** [comment]
@dpkirchner can you give an example/reproduction of a process where you expect to be able to attach but cannot?

**Comment by connor4312** [comment]
Thanks, I made that regex a bit more lenient.
