### ISSUE TITLE
CAN NOT SHOW FIND Widget in terminal

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#137017]
Does this issue occur when all extensions are disabled?: Yes

版本: 1.63.0-insider (system setup)
提交: c1096372119bcf83b9bd8ccee96dcf266f35de76
日期: 2021-11-11T13:18:41.690Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.14393
Steps to Reproduce:
<kbd>ctrl+f</kbd> in terminal
![image](https://user-images.githubusercontent.com/1876302/141415211-ba1dd55f-5737-4bcc-a73c-f1f92632f61b.png)

1.62.2 is ok

**Comment by muendelezaji** [comment]
Same here after today's update

Version: 1.63.0-insider
Commit: 3bd29c1d6c6ef5b6265614def99b7257b671ae19
Date: 2021-11-12T12:39:26.447Z (10 hrs ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

![image](https://user-images.githubusercontent.com/1127221/141569255-e6868c83-81c3-48f0-9ed9-a8a171fcb273.png)
