### ISSUE TITLE
Allow folder view hide expandable/foldable indicator to have a better recognizability of folder structure

### ISSUE THREAD

**Issue by cloudhan** [microsoft/vscode#137014]
Currently, the folder view have the following visual design:
![folder](https://user-images.githubusercontent.com/1279292/141403414-b724c8e6-cb55-4ab7-9409-42fe3303d5f8.png)

It still offen makes me confuse about folder structure if I am in a large project folder with deeply nested structure. The community also has long standing complaining about it, for example: #13518, #11762, #11898, etc. Previously, a verticle indicator bar was added to address the issue. However, the indicator is deteched from the folder content.

I'd like to hide the expandable(">") /foldable("V") indicator from the tree view. So that it looks like as following:
![folder_new](https://user-images.githubusercontent.com/1279292/141404097-4da079b3-b218-496f-b706-fe214e411700.png)

An animated diff:
![folder_animated](https://user-images.githubusercontent.com/1279292/141404141-6703ecf5-aa82-4ed8-b75e-b3de5d7bc880.gif)

**Comment by djmisterjon** [comment]
for your indent , you can add custom setting  `"workbench.tree.indent": 20,`

Also dont gorget vscode is run on chromium, so you can open dev tool, find the element and hack your own css rule !
![image](https://user-images.githubusercontent.com/24865815/141465720-78f80ac7-4ff0-446b-adf4-9240fddaae0b.png)

**Comment by JacksonKearl** [comment]
I recommend using a different file icon theme. See the examples here:
![Uploading recording (6).gif…]()

**Comment by cloudhan** [comment]
OK, this can be addressed by file icons, I will open an request in my favourite icon package repo then. Still hope there can be a uniform switch to toggle it on and off, whatever.

**Comment by cloudhan** [comment]
Oops, the icon package has already supported it 😂
