### ISSUE TITLE
please :)

### ISSUE THREAD

**Issue by spkinguy1** [microsoft/vscode#137078]
Hi boys ! please don't forget we had full-fledged IDEs like jetbrains stuffs 
if you want to be bloats vscode , we will immigrate to something else ,,, even as a begginer i will try hard on something like vim ... 
keep your lightweight and handy software . you can be around 15 mb code-edditor . vscode is best tool for coding ever ... 
thank's a lot for your serves  <3 love too much from Iran

**Comment by CodeCrazy-ywt** [comment]
What are you talking about?
