### ISSUE TITLE
Tasks take ~1 second to stop

### ISSUE THREAD

**Issue by macromaniac** [microsoft/vscode#137066]
Issue Type: <b>Bug</b>

A 2 ms command line program can take over 2 seconds to complete when it is a vscode task. Hitting F5 often more time is spent waiting on vscodes prelaunch task system than waiting on the actual compiler.

For comparison hitting F5 in visual studio on a c# hello world console application after cleaning is nearly instant while in vscodes there is a fairly large delay due to this slowness in the task system.

```
//example tasks.json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "displayTimes",
            "type": "shell",
            "command": "'elapsed ms: ' + ($(get-date) - [DateTime](cat time.txt)).TotalMilliseconds",
            "dependsOrder": "sequence",
            "dependsOn":["getTime"]
        },
        {
            "label": "getTime",
            "type": "shell",
            "command": "Get-Date -Format HH:mm:ss.fff > time.txt"
        }
    ]
}
```

Steps to Repro (win only):
1. copy the json into your tasks.json
2. run task displayTimes (ctrl + p) "task displayTimes"
3. observe a time of e.g. "elapsed ms: 2013.7653" (data from my computer)
4. run `Get-Date -Format HH:mm:ss.fff > time.txt; 'elapsed ms: ' + ($(get-date) - [DateTime](cat time.txt)).TotalMilliseconds;` and observe a time of e.g. "elapsed ms: 2.1692" (data from my computer)

The slowness occurs but is slightly better for prebuilt tasks (still around a second) but I didn't create a testcase for that

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (32 x 3493)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (20.27GB free)|
|Process Argv|--crash-reporter-id f353addb-c90e-446c-9f70-858f35af1648|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by alexr00** [comment]
Tasks are not run as shown in step for. Instead, they are run using your shell. In your example using powershell, the tasks are run by doing `powershell -Command <your command>`. It is not expected that they will ever be as fast as writing your own script.

**Comment by macromaniac** [comment]
ONice, you are right. Yall have to spin up a terminal so then the ideal time should be closer to

powershell -Command "Get-Date -Format HH:mm:ss.fff > time.txt"; powershell -Command "'elapsed ms: ' + ((get-date) - [DateTime](cat time.txt)).TotalMilliseconds;"
which I get elapsed ms: **174.3678**

So at best a 10x speedup, not 100x (unless you pool terminals but bad idea probably). I'm not expecting super fast really. The above script has gone from 500ms in earlier vscode versions to 2000ms due to sleeps caused by issues (neatly listed in here https://github.com/microsoft/vscode/blob/950e89beacff64928098d513b590a80401f42e2e/src/vs/platform/terminal/node/terminalProcess.ts and also some sleeps in node-pty ithink )

mb yall could use https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-flushfilebuffers in node-pty to wait for the pipe to be empty instead of sleeping to wait for the pipes to be flushed (idk throwing out ideas lol)

**Comment by macromaniac** [comment]
I think fast builds are important and make coding fun and shaving 1s off build time I think would be sick esp since I hit that build button a few hundred times a day.
