### ISSUE TITLE
it often shows  "the windows has crashed" when I use vscode

### ISSUE THREAD

**Issue by dengwu08** [microsoft/vscode#137034]
it is very easy to show below error:
the windows has crashed(reason:'crashed', code:'-1073741819')

No special steps to reproduce, just normal operation as below:
1.when start vscode
2.Open a folder,  ctrl+p to find a file, choose the file to edit

reinstall or reboot can not help to improve.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version  and platform.

Also, please investigate whether one of your extensions is causing this. The "Start Extension Bisect" command from Command Palette can be useful here.
