### ISSUE TITLE
Debugger configurator selector self close

### ISSUE THREAD

**Issue by polyclash** [microsoft/vscode#137073]
Issue Type: <b>Bug</b>

Set some configuration for the debugger and try to select one from the menu.
The menu self close after randomly time.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.58.5
cpptools|ms-|1.7.1

</details>

![Debugger_conf_selector_self_close](https://user-images.githubusercontent.com/40276897/141517101-254127e0-cff9-4bb1-a4f4-775e463b1f93.gif)

**Comment by weinand** [comment]
@polyclash I cannot reproduce this.
Are you able to reproduce this in latest VS Code?

**Comment by polyclash** [comment]
With the 1.63.2 version the strange behaviour is disappeared.

**Comment by weinand** [comment]
@polyclash thanks for trying this in the latest
