### ISSUE TITLE
Separately disable grammars contribution from an extension

### ISSUE THREAD

**Issue by sumneko** [microsoft/vscode#137018]
I'm the author of [Lua extension](https://marketplace.visualstudio.com/items?itemName=sumneko.lua).
Since the default Lua tmLanguage of VSCode is too old, my extension provides a new [tmLanguage](https://github.com/sumneko/vscode-lua/blob/db7b5b8d95fe920624e169b62f1bd79ae79008b2/package.json#L1479-L1485).
However, some users want to use other extensions to provide coloring, which creates conflicts.
Therefore, I hope you can provide a way to disable the grammars contribution of the extension separately so that users can use other extensions.

**Comment by aeschli** [comment]
We currently only have the mechanism of disabling extensions (your or ours).
Would it make sense to separate out your grammar in a separate extension, so users have the freedom to choose?

We're also open updating our grammar to a better one (e.g. yours). But it sounds that there are various grammars out there, and different users prefer? Can you list the other extesions?

**Comment by sumneko** [comment]
Sorry for my late reply.

Separate out my grammar in a separate extension is indeed a way, I can pop up a prompt in the extension to suggest that users also install this extension.

I did this initially because VSCode's built-in grammar file is a bit poor, and the default dark+ theme does not support it well (many tokens are displayed as white or purple in dark+, he color is very monotonous).
So I modified these tokens and used some other tokens according to the color scheme of the dark+ theme.
However, this has had a negative impact on some themes that have good support for the built-in Lua grammar files, some users reported that because he is partially color-blind, he needs to use a specific theme, and my modified token leads to a bad experience.

Perhaps the best way is to keep the original token unchanged, just add new tokens (new syntax and new basic API), and then improve dark+'s support for Lua.

**Comment by aeschli** [comment]
+1 for improving the bult-in lua grammar with some additional scopes. Not sure if https://github.com/textmate/lua.tmbundle is still maintained, but I suggest starting with a PR there. If nothing happens, and you are willing to setup a new repo with the improved grammar, we're happy to switch it.

Closing as we don't intend to add configuration that allows to just disable a grammar.

**Comment by sumneko** [comment]
OK, I will do some works about it.
By the way I have opened a [PR](https://github.com/textmate/lua.tmbundle/pull/13) there long long ago.
