### ISSUE TITLE
Notebook "show more" has poor formatting with many small text outputs

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#137098]
I have a notebook which will produce a new `"text/plain"` output for each `console.log` in a program. This works well enough in-notebook:
![image](https://user-images.githubusercontent.com/8586769/141599920-d8600af1-6646-4bad-855e-79fa0db04414.png)

but as soon as I click "show more", I get this formatting, which is much harder to work with:
![image](https://user-images.githubusercontent.com/8586769/141599935-f37009a8-fae6-4ed5-a95f-e3987e85bcb8.png)

IMO if they're all plaintext outputs, they should be fomatted exactly as they are in-notebook.

**Comment by rebornix** [comment]
@JacksonKearl I just verified with latest Insiders and this issue is gone. Please reopen if you are still seeing it.

**Comment by JacksonKearl** [comment]
Still not in love with the rendering of large outputs. Couple issue cases:
```
for (var i = 0; i < 1000; i++) {
  await new Promise(c => setTimeout(c, 10))
  console.log(`this is my ${i}, there are many like it, but this one is mine`)
}
```
After the 500'th output, all outputs stop being rendered, but there's no message saying as much: 
![image](https://user-images.githubusercontent.com/8586769/152599393-a95d5b3b-2488-47eb-94eb-a7c2de873977.png)

What's interesting is if I change the promise delay to 1 ms, I do get the message:
![image](https://user-images.githubusercontent.com/8586769/152599462-fb690d5d-fb10-42f8-9c75-f4fea72c8d86.png)

However when I click into it, the rendering is still in an undesirable format:
![image](https://user-images.githubusercontent.com/8586769/152599517-04db1540-823c-4593-8138-5eabbea30483.png)

IMO it'd be much nicer to collapse all the `text/plain` outputs into a single block of raw text. 

---

On the other hand, if I don't use async at all, forcing as much text into one output line as possible:
```
for (var i = 0; i < 10000; i++) {
  // await new Promise(c => setTimeout(c, 1))
  console.log(`this is my ${i}, there are many like it, but this one is mine`)
}
```
I get a bunch of segments of truncated text:
![image](https://user-images.githubusercontent.com/8586769/152599837-68cb01a0-280f-4f7b-b555-02e37917cca4.png)
Where each "Open the full output data[ in a text editor]()` link takes me to about 100 lines of text:
![image](https://user-images.githubusercontent.com/8586769/152599868-15a3e13f-804a-4279-8589-f064382873f4.png)
![image](https://user-images.githubusercontent.com/8586769/152599891-f2a9e479-3a6b-4995-b6cf-77a0abc4066b.png)

This is better than the above JSON, but still it'd be ideal if there was some way to view all of the text output of a command in one buffer. I often will log a bunch of lines of stats/runtime progress/whatever in a cell and would like to have a single buffer I can use to look through them all, just as I would if I were using a terminal.

**Comment by rchiodo** [comment]
I still repro this problem? The output format of the text seems good, but it doesn't show all the outputs if the sleep happens.
