### ISSUE TITLE
Feature request: Show inline completions when IntelliCode's InlineCompletionProvider returns a result

### ISSUE THREAD

**Issue by vivlimmsft** [microsoft/vscode#137004]
In Visual Studio, IntelliCode only shows gray text when our model has returned a prediction:

https://user-images.githubusercontent.com/27872315/141383936-6879fc22-466c-48f0-a136-80394b75a013.mp4

In VSCode, the gray text is shown for every completion item, regardless of whether there is a prediction from our provider or not:

https://user-images.githubusercontent.com/27872315/141383940-150e6ddf-a262-4380-a668-7568785a2df1.mp4

I believe this is a consequence of our extension setting `editor.suggest.preview` to `true`, but without that setting we will not get *any* gray text while the suggest widget is visible. We'd like our provider to always be called and be able to display gray text while the suggest widget is visible, though my understanding is that this is the opposite of the Copilot experience where gray text and suggest widget are mutually exclusive. Can we differentiate our provider in some way that allows us to have behavior consistent with our VS experience?

This may also be somewhat related to my request in #137000 - since we set `editor.suggest.preview` to `true`, gray text is shown for every completion, including snippets, where it displaces the following lines in the document in a distracting way.

cc @hediet @ayim @juihanamshet1 @DavidObando

**Comment by hediet** [comment]
Implemented by 52dbedd03481d94134ed2c1fbdeb82eb9c19cf3d.

@vivlimmsft it would be awesome if you could verify that it works as expected now!

Even if `editor.suggest.preview` is set to false (which it is by default), a preview should be shown if an inline suggest provider provides an inline suggestion the augments the current suggest widget selection.

**Comment by hsenag** [comment]
> It should have no effect on the copilot experience.

@hediet doesn't it mean we'll get the autocomplete popup and ghost text in some situations where we don't now?

**Comment by hediet** [comment]
> doesn't it mean we'll get the autocomplete popup

The autocomplete popup still does not show automatically when there are inline completions.

However, if the user manually opens the autocomplete popup (ctrl+.) and selects an item that is the prefix of a copilot suggestion, then a preview of that item including the copilot suffix (in non-italic) is shown.

If you really don't like this, there is also a way you can opt out of that - however, I don't recommend that.
In `provideInlineCompletionItems`, you can return `[]` if `context` indicates that a suggest item is being selected.

**Comment by hsenag** [comment]
> The autocomplete popup still does not show automatically when there are inline completions.

What about if the autocomplete popup has already appeared and then the inline completion provider returns a result (after waiting for the network)?

Thanks for the opt-out suggestion. I think our policy at present is not to show both together, but when time allows, we definitely want to do some proper experiments on the user impact of having them both appear in certain scenarios.

**Comment by hediet** [comment]
> What about if the autocomplete popup has already appeared and then the inline completion provider returns a result (after waiting for the network)?

Then it will show as soon as the result comes in, but only if it agrees with the currently selected suggestion.

**Comment by orph** [comment]
@hediet can you change the default settings so that the Copilot experience
is not effected in any way, as per our prior discussions?

**Comment by hediet** [comment]
Please try out the feature in tomorrows insider build.

If you still do not like it, you can opt out of it as described.

**Comment by vivlimmsft** [comment]
I tried the change and it looks good to me.

As a heads up: In the future we may need to revisit having the ability to *not* suppress the autocomplete popup.

Current behavior with our extension *does* usually raise the autocomplete popup and the gray text at the same time, which *is the behavior we want*. I think it's possible that this could be caused by instability in the predictions we offer (they currently can change in the middle of typing a line), or timing-based coincidence. It doesn't sound like it's intentional per the comments on this issue.

If we have a more concrete request after the prediction typing stabilization work lands (cc @juihanamshet1) then we'll open a new issue to discuss it further.

**Comment by orph** [comment]
Ok I just tried out latest nightly - I think it’s a pretty drastic change:

1. Result from pressing TAB is ambiguous. When both autocomplete and ghost text are displayed, TAB only inserts the autocomplete text - often I just want the full ghost text.
1. Favoring autocomplete will likely eat into Copilot key metrics. This is because autocomplete is shown exclusively until no matches exist with typed prefix, matching is fuzzy, and the autocomplete list contains many things like identifiers in the file, language keywords, snippets, etc. In practice ghost text doesn't show nearly as often.

Because of uncertain impact this change may have, I would prefer to revert to the previous behavior by default. If we can choose this new behavior with a setting we can run an experiment to learn more soon.

**Comment by Krzysztof-Cieslak** [comment]
> In provideInlineCompletionItems, you can return [] if context indicates that a suggest item is being selected.

@hediet, will the editor call `provideInlineCompletionItems` again when the user dismisses the autocomplete widget with ESC?

**Comment by hediet** [comment]
@Krzysztof-Cieslak yes, it will be called again.

**Comment by isidorn** [comment]
@orph and @vivlimmsft thank you very much for trying it out and providing feedback.
Based on this we have two options:
1. Copilot changes `provideInlineCompletionItems` by returning `[]` if context indicates that a suggest item is being selected. We believe this is not a large change which will have no impact on anything else.
2. VS Code can add a flag `showInSuggestPreview` that can be set per suggestion item (defaults to `false`). If set to `false`, it does not augment the selected suggest item. No ghost text will be shown for such items if the suggest widget is up. 

@Krzysztof-Cieslak @hsenag @orph please let us know if `option 1` works for you. If that does not work for you, @hediet and me will work on `option 2` which will require no changes from Copilot.

Just to clarify the timing, VS Code stable will be released in 2 weeks. So we should do either 1 or 2 until then.

**Comment by orph** [comment]
For reference here is the behavior change which is most likely to effect Copilot metrics. As far as I can tell neither of these [proposals](https://github.com/microsoft/vscode/issues/137004#issuecomment-979132550) revert to the current behavior wrt initially showing ghost text - this is the behavior we need to maintain by default.

Stable (current behavior):

https://user-images.githubusercontent.com/28068/143454028-019edb96-a416-4b2d-bc1c-0f7792d648ff.mov

Insiders (new beavior):

https://user-images.githubusercontent.com/28068/143454170-287326ad-0c59-48c9-96ce-741d7e02107a.mov

In both cases response was cached so race conditions are not a factor.

**Comment by hediet** [comment]
> Insiders (new beavior):

The shown difference is not intended and also not what the requested feature is about.

I did not (intentionally) change any logic regarding surpression of the autocomplete popup.
Afaik we prevent the suggest popup from showing if there is already ghost text.

Are you sure this is not a timing issue? I.e. that the autocomplete widget just happens to be faster or the inline completion provider slower in your second gif?

Is this a public file, so I can try to reproduce this difference in behavior?

**Comment by isidorn** [comment]
I just tried to reproduce this and I could not. This works the same for me in Stable and Insiders - the suggest widget always gets shown. Attached you can see a gif and you can correct me in what I am doing differently than you.

@orph it would be great if you can provide repro steps. Make sure that you also try with fresh `--user-data-dir`. I noticed in your gif that you waited considerably longer before pressing the `m` key for the stable build - might that have an influence?
@hsenag @Krzysztof-Cieslak can you reproduce?

![recording (1)](https://user-images.githubusercontent.com/1926584/143458965-d4ca983c-900c-43fb-ad42-dbce6864f1b2.gif)

**Comment by orph** [comment]
> it would be great if you can provide repro steps.

1. Open this file to line 338: https://github.com/Microsoft/vscode/blob/main/src/vs/editor/common/config/editorOptions.ts#L339
1. Press enter at the end of 338, so you are on a blank line
1. Start typing the next line m-o-u. The inline completion should show up after the first character press.

**Comment by orph** [comment]
Somewhat related to this I wrote up my old proposal to remove the race condition when deciding between showing inline/autocomplete UI: https://github.com/microsoft/vscode/issues/137886

**Comment by isidorn** [comment]
@orph thanks for great steps! I have tried them and I see 100% of the same behaviour in Stable and Insiders. That is:
1. I press `m` -> suggest widget shows
2. I press `o` -> suggest widget still visible
3. I press `u` -> suggest widget no longer visible, inline completions shown

Let's wait and see if @hsenag  and @Krzysztof-Cieslak can repro
@orph In the meantime if you from the terminal open `code --user-data-dir SOME_PATH` and `code-insiders --user-data-dir SOME_OTHER_PATH`. If code and code-insiders are not on the path, you can from VS Code `F1 > "install code to path"`Can you still repro?

Thanks for the race condition proposal, for that one we can continue the discussion in that issue.

**Comment by orph** [comment]
@isidorn You may need to repeat the steps a couple times so that network result is in cache. Otherwise, something has clealry changed - the behavior favoring autocomplete until autocomplete matching fails is a new. It happens frequently in insiders, and I don't see it on stable.

**Comment by isidorn** [comment]
I just now tried 10 times on both Stable and Insiders. Out of 10 times on both sides only 1 did it happen that the inline completions got shown after pressing `m` both for Stable and Insiders. It took too long for my gif tool to process the recording.
After this I am fairly certain that nothing changed on our side, this process was not really deterministic before and maybe we can improve that in the future via #137886

As I said let's wait for @hsenad and @Krzysztof-Cieslak Or @orph can try with a new `user-data-dir`

**Comment by Krzysztof-Cieslak** [comment]
I can't repro this, I see the exact same behaviour as @isidorn. On the right - Stable, on the left - Insiders

https://user-images.githubusercontent.com/5427083/143465088-1eeb2d72-bebb-45ba-a20a-c7725047df45.mov

**Comment by Krzysztof-Cieslak** [comment]
I can, however, repro on my "normal" Insiders (i.e. without `--user-data-dir`).
My bet would be:
`"editor.suggest.showSnippets": false,` or `"editor.wordBasedSuggestions": false,`

**Comment by orph** [comment]
@isidorn @Krzysztof-Cieslak thank you for investigating! It was a user error on my part!! I had `"editor.snippetSuggestions": "none",` set on my stable build but not my insiders build. So sorry for the noise!

**Comment by Krzysztof-Cieslak** [comment]
OK, now that this mystery is solved, let's circle back to the core issue here.

At least in short term, I think we all agree that should be fine with `option 1` proposed by @isidorn and @hediet in this comment - https://github.com/microsoft/vscode/issues/137004#issuecomment-979132550.

**Comment by isidorn** [comment]
@Krzysztof-Cieslak great, thanks for investigating.
@orph no problem for the noise. This is why it is best that we always start discussing things in issues with repro steps.

@Krzysztof-Cieslak yeah if we can go with `option 1` that would be great! Try it out and let us know how it works for you. Thanks!
