### ISSUE TITLE
Feature request: Inline completions: Exclude some kinds of intellisense items

### ISSUE THREAD

**Issue by vivlimmsft** [microsoft/vscode#137000]
Currently, IntelliCode's InlineCompletionProvider is called for every [kind of completion item](https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions) in the IntelliSense list.
We'd like to either not be called for, or have the ability to ignore, the following types of completion items which are not based on type information:

* `file`
* `folder`
* `color`
* `unit`
* `snippet`
* `text`

In Visual Studio, we exclude completion items that are not derived from type information - this effectively functions as a filter, excluding some unusable predictions which are not representing valid type information (i.e. attempting to call a method which doesn't exist)

As well, `snippet` items will often consist of multiple lines, which will displace the following lines and be distracting when scrolling through the list; here's a video:

https://user-images.githubusercontent.com/27872315/141377011-6df2ac90-e509-4fd5-8b20-a4d59837455f.mp4

This issue may be related to our extension setting a default of `editor.suggest.preview` to `true`, which is necessary because of #137004 .

cc @hediet @ayim @juihanamshet1 @DavidObando

**Comment by hediet** [comment]
I think the way to go here would be passing the suggestion kind back to the inline suggestion provider.

**Comment by vivlimmsft** [comment]
That sounds good to me if the InlineCompletionProvider could also control whether its response results in gray text being shown with the suggest widget visible. (#137004)

> has no real semantic meaning.

Can you expand on this a bit more please? In my experience, `snippet` and `text` items are unhelpful to derive inline suggestions from, so it seems reasonable to me to filter at least those out.

**Comment by hediet** [comment]
`SelectedCompletionInfo` now has the members `completionKind` and `isSnippetText`.
You should check both to skip snippet suggestions.

Please let me know if that works for you.
