### ISSUE TITLE
Do not show Welcome Page after opening a project

### ISSUE THREAD

**Issue by cbrnr** [microsoft/vscode#137021]
I use the Welcome Page primarily to open one of my recent projects. Once the project is open, the Welcome Page doesn't make too much sense anymore, because I'm already in my working environment and ready to start editing. However, the Welcome Page stays open and the first thing I need to do is to close it, which is an unnecessary step.

Would it be possible to automatically close the Welcome Page after opening a project? If not, at least a configuration option to do so would be great.

**Comment by gjsjohnmurray** [comment]
See #134381

Is your Welcome Page's label italicised, i.e. _Get Started_ ? If so, when you open a file in your project the tab should get reused.

**Comment by cbrnr** [comment]
You are right, I never noticed that! Thanks!
