### ISSUE TITLE
in-product release notes don't display from update banner release note button

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#13700]
- VSCode Version:1.6.0
- OS Version: Windows 10, 7

Steps to Reproduce:
1. Install VS Code 1.6.0
2. Run VS Code and wait for update banner to display.
3. Click "Release Notes" button on banner.

A new preview editor is opened with the title "Release Notes: {0}" and no content.
Help > Release Notes correctly displays a preview editor titled "Release Notes: 1.6.0" with content.

**Comment by gregvanl** [comment]
Still repro's in upgrade from 1.6.1 to 1.7.0 stable.

![1 7 0repro](https://cloud.githubusercontent.com/assets/12818376/19947463/7bdeff9e-a105-11e6-9bdc-e374b0979c6f.png)

**Comment by joaomoreno** [comment]
The fix only lands on 1.7.0.

**Comment by gregvanl** [comment]
Doh, of course.
