### ISSUE TITLE
how to config sourcemap for develop a vs-code extension 

### ISSUE THREAD

**Issue by ELISHELL** [microsoft/vscode#137020]
when debug a extension project, the console's window print some error msgs ... how to open it as a stackflow tree or open the sourcemap suport . now it only report `.../app/out/bootstrap-fork.js:5....` . yet i dont know how to config the lauch.config! the official docs also not have a notes !

**Comment by weinand** [comment]
Please follow these steps: https://code.visualstudio.com/api/get-started/your-first-extension
