### ISSUE TITLE
Repeating error: Settings sync is suspended because of successive authorization failures. Please sign in again to continue synchronizing.

### ISSUE THREAD

**Issue by olexandr-perepiyaka** [microsoft/vscode#137064]
Issue Type: <b>Bug</b>

Microsoft Authentication Log:
[Info  - 14:55:22.727] Reading sessions from keychain...
[Info  - 14:55:23.70] Got stored sessions!
[Trace  - 14:55:23.70] Read the following session from the keychain with the following scopes: email offline_access openid profile
[Info  - 14:55:23.70] Refreshing token for scopes: email offline_access openid profile
[Info  - 14:55:23.636] Token refresh success for scopes: email offline_access openid profile
[Info  - 14:55:23.642] Getting sessions for all scopes...
[Info  - 14:55:23.642] Token available from cache (for scopes email offline_access openid profile), expires in 4103993 milliseconds
[Info  - 14:55:23.642] Got 1 sessions for all scopes...
[Info  - 14:56:01.735] Getting sessions for all scopes...
[Info  - 14:56:01.735] Token available from cache (for scopes email offline_access openid profile), expires in 4065900 milliseconds
[Info  - 14:56:01.735] Got 1 sessions for all scopes...
[Info  - 15:56:18.662] Getting sessions for all scopes...
[Info  - 15:56:18.662] Token available from cache (for scopes email offline_access openid profile), expires in 448973 milliseconds
[Info  - 15:56:18.662] Got 1 sessions for all scopes...
[Info  - 15:56:18.751] Getting sessions for all scopes...
[Info  - 15:56:18.752] Token available from cache (for scopes email offline_access openid profile), expires in 448883 milliseconds
[Info  - 15:56:18.752] Got 1 sessions for all scopes...
[Info  - 16:03:17.636] Refreshing token for scopes: email offline_access openid profile
[Info  - 16:03:18.169] Token refresh success for scopes: email offline_access openid profile
[Info  - 16:03:18.172] Getting sessions for all scopes...
[Info  - 16:03:18.172] Token available from cache (for scopes email offline_access openid profile), expires in 3848996 milliseconds
[Info  - 16:03:18.172] Got 1 sessions for all scopes...
[Info  - 16:38:02.530] Getting sessions for all scopes...
[Info  - 16:38:02.530] Token available from cache (for scopes email offline_access openid profile), expires in 1764638 milliseconds
[Info  - 16:38:02.531] Got 1 sessions for all scopes...

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200G with Radeon Vega Graphics     (4 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.95GB (8.47GB free)|
|Process Argv|--crash-reporter-id e0a2e0ad-954d-4dcf-95a5-469341cf6ea8 --crash-reporter-id e0a2e0ad-954d-4dcf-95a5-469341cf6ea8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode-standard|bys|0.22.1
vscode-sql-beautify|cla|0.2.8
ini-for-vscode|Dav|0.0.4
vscode-diff|fab|1.4.2
php-debug|fel|1.22.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
seito-openfile|Fr4|1.8.8
gc-excelviewer|Gra|3.0.44
vscode-test-explorer|hbe|2.21.1
customize-ui|ioc|0.1.54
monkey-patch|ioc|0.1.15
mysql-syntax|jak|1.3.1
svn-scm|joh|2.15.0
php-xdebug|kak|0.0.7
formate|Mik|1.2.1
test-adapter-converter|ms-|0.1.4
gistfs|vsl|0.3.0
twig|wha|1.0.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by ArnieGA** [comment]
Same here

**Comment by bbrefeld** [comment]
Same here, Been having this issue for about 2 weeks now. However for me it seems to only happen on Ubuntu 20.04 and not on Windows 10.
Can also confirm this issue happening on other devices running Ubuntu 20.04 and different vsCode configurations.
All of us are using Microsoft accounts to sync settings

**Comment by gmccullo** [comment]
This has been going on for a while now. I have it on Windows10.

**Comment by AndyPresto** [comment]
I've also been seeing this issue for around 2 weeks when using a Microsoft account to sync, on Fedora Linux.

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/133201
