### ISSUE TITLE
search then mark and select filtered records 

### ISSUE THREAD

**Issue by rudrajitdas** [microsoft/vscode#137019]
In a file if you search for a word/ phrase then there can be multiple occurrence of the that word/phrase in multiple lines.
User should be able to mark the selected record and copy only those lines.
This is a very common and useful feature found in Notepad++ but missing in VSCode

**Comment by gjsjohnmurray** [comment]
Have you tried using the [Search Editors](https://code.visualstudio.com/updates/v1_43#_search-editors) feature?

**Comment by roblourens** [comment]
You can also add multiple cursors to the lines with results (alt+enter) then copy those lines
