### ISSUE TITLE
error opening a project with the command "code . " [1112/135458.759:ERROR:registration_protocol_win.cc(102)] CreateFile: The system cannot find the specified file. (0x2)

### ISSUE THREAD

**Issue by insinfo** [microsoft/vscode#137067]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.1
- OS Version: Windows 11

Steps to Reproduce:

1. open the vs code terminal 
2. run the command "code . "

![image](https://user-images.githubusercontent.com/12227024/141506163-cbba81ae-3105-49d9-828b-d2a1259faec2.png)

**Comment by coding-chris-kao** [comment]
I got the same issue on my Windows 10 device
