### ISSUE TITLE
Crazy formatting issues after running tests in iterm

### ISSUE THREAD

**Issue by benadam11** [Microsoft/vscode#13703]
- VSCode Version: Version 1.6.1 (1.6.1)
- OS Version: OSX 10.11.6

Steps to Reproduce:
1.  Save changes 
2. Run mocha test suite in iTerm
3. Git status
4. See that VSCode has made crazy formatting changes on multiple files 
   <img width="1897" alt="screen shot 2016-10-13 at 2 16 47 pm" src="https://cloud.githubusercontent.com/assets/6645985/19367387/caedc068-914f-11e6-8488-a329223c4e82.png">

**Comment by isidorn** [comment]
Assigning to @rebornix to do some investigation what is going on here since I have no clue who to assign to from the description

**Comment by benadam11** [comment]
@rebornix I can make a screen recording if that would be helpful ... doesnt make any sense but it is super frustrating

**Comment by rebornix** [comment]
@benadam11 the git status output is somewhat annoying but right now I'm not sure who contributes to that. Can you help provide

1. `git status` before running your test cases
2. Close VS Code before running test cases and see if this still exists
3. If it still exists, provide me your mocha test related config and extensions then we can have an idea who is doing the real formatting

Does this make sense to you?
