### ISSUE TITLE
If the editor is designed by fluent design ，including  filleted corner，it will be perfect

### ISSUE THREAD

**Issue by Arcer22** [microsoft/vscode#137008]

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/115641#issuecomment-886804684

**Comment by Arcer22** [comment]
> /duplicate
> 
> See [#115641 (comment)](https://github.com/microsoft/vscode/issues/115641#issuecomment-886804684)

Will  Visual Studio Code use fluent design  in the future？
