### ISSUE TITLE
Can't open developer tools

### ISSUE THREAD

**Issue by flleeppyy** [microsoft/vscode#137088]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.62.2
- OS Version: Windows 10 Enterprise LTSB

Steps to Reproduce:
1. Use a portable version of vscode (Download zip file of VSCode > Create "data" directory in vscode directory)
2. Attempt to open developer tools
3. nothing happens
4. Same goes for process explorer, but nothing shows in the window.
![image](https://user-images.githubusercontent.com/18307183/141555632-2710be23-83ca-4c74-b72c-3f88c79dd61b.png)

**Comment by kirillsafin** [comment]
I can't open developer tools too. I am using Debian. I have installed VS code from the official .deb package. But I can open process explorer.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/122951
