### ISSUE TITLE
Auto new line in integrated terminal.

### ISSUE THREAD

**Issue by gringonivoli** [Microsoft/vscode#13702]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:43:46.054Z)
- OS Version: Linux x64 3.11-2-amd64
- Extensions: AdamCaviness.theme-monokai-dark-soda-0.0.5, Nuuf.theme-hackershaze-1.2.1, Tyriar.lorem-ipsum-1.0.0, abusaidm.html-snippets-0.0.17, akamud.vscode-theme-onedark-0.2.7, andischerer.theme-atom-one-dark-0.0.1, benjaminromano.typings-installer-0.2.0, ceps.theme-darcula-0.0.4, dbaeumer.jshint-0.10.15, donjayamanne.githistory-0.1.0, eg2.tslint-0.5.39, gerane.Theme-Dark-Dracula-0.0.2, gerane.Theme-Ocean-Dark-Soda-0.0.2, joelday.docthis-0.3.5, johnpapa.Angular1-0.1.16, jrieken.tsd-recommender-0.0.2, ms-vscode.Theme-MarkdownKit-0.1.1, ms-vscode.Theme-MaterialKit-0.1.1, ms-vscode.Theme-TomorrowKit-0.1.3, ms-vscode.jscs-0.1.9, msjsdiag.debugger-for-chrome-1.1.0, rid9.datetime-1.0.5, vsmobile.cordova-tools-1.2.3, zhuangtongfa.Material-theme-1.0.3

Steps to Reproduce:

1. Open Integrated Terminal.
2. Write, for example, ls -lha
![code_bug](https://cloud.githubusercontent.com/assets/907275/19366310/12c30778-916d-11e6-97a3-b49a6b7f2371.png)

**Comment by Tyriar** [comment]
@gringonivoli what font is that you're using?

**Comment by gringonivoli** [comment]
The font is Droid Sans Mono.

`"editor.fontFamily": "'Droid Sans Mono', 'Courier New', monospace, 'Droid Sans Fallback'"`

and this is the terminal configuration..

`"terminal.integrated.fontFamily": "",
 "terminal.integrated.fontLigatures": false,
 "terminal.integrated.fontSize": 0,
 "terminal.integrated.lineHeight": 1.2,
 "terminal.integrated.cursorBlinking": false,`

**Comment by gringonivoli** [comment]
@Tyriar Today I can not reproduce the error.. maybe it was a bad configuration.

**Comment by Tyriar** [comment]
@gringonivoli good to hear. Comment here if you hit it again.

**Comment by gringonivoli** [comment]
@Tyriar in the first image the bug no appear, but in second image it is appear..

![code_not_bug](https://cloud.githubusercontent.com/assets/907275/19483331/5b7dab42-952a-11e6-8ba6-56e5bf50e5fa.png)
![code_bug2](https://cloud.githubusercontent.com/assets/907275/19483344/645ee0b4-952a-11e6-9cc6-836dfdfbc56e.png)

**Comment by GooseCoder** [comment]
I have the same error, in my case it happens after repeating the ls -al like 3 times, also I have zsh as my default shell with an extension named prezto, it seems that your shell it's not the default bash, maybe this is related to our common problem.

Regards.

**Comment by Tyriar** [comment]
This should be fixed in the [Insiders build](https://code.visualstudio.com/insiders) as it's a duplicate of https://github.com/Microsoft/vscode/issues/13554
