### ISSUE TITLE
Feature request: Add reverse continue for TimeTravel Debugging feature for Node

### ISSUE THREAD

**Issue by aruneshchandra** [Microsoft/vscode#13705]
This request builds on the following work that was done earlier to support TTD for Node in VSCode 
- [UI support for TimeTravel Debugging for Node ](https://github.com/Microsoft/vscode-node-debug/issues/72)
- [Adding step back capability to VSCode node-debug adapter for TTD](https://github.com/Microsoft/vscode-node-debug/issues/77)
- [UI support for TimeTravel Debugging](https://github.com/Microsoft/vscode/issues/7652)

According to some internal usability testing, we discovered a need to have a reverse continue button on the debug bar in order to enhance the usability of the time travel debugging for more complex scenarios.

/cc: @Weinand, @isidorn, @roblourens, @mrkmarron

**Comment by weinand** [comment]
@aruneshchandra please explain the semantics of "reverse continue"

**Comment by aruneshchandra** [comment]
"Reverse continue" is suppose to work exactly like the "Debug Continue" with the difference being that it goes backwards and is only available while debugging a TTD trace.  So, when the debugger is broken into while debugging a TTD trace, hitting reverse continue should execute backwards until the first (previous) break point is hit.  To enable this VSCode can pass a stepback:continue command to the debug adapter and the TTD enabled runtime should handle the rest. 

@mrkmarron - do you have anything else to add ?

**Comment by weinand** [comment]
@roblourens are you supporting back-in-time debugging in node-debug2 too?

**Comment by roblourens** [comment]
I don't think Node-chakra supports `--inspect` yet, although I think they're working on it.

**Comment by aruneshchandra** [comment]
@roblourens is right, `--inspect` is not supported in Node-ChakraCore yet , but we do plan to support it.
/cc: @digitalinfinity @agarwal-sandeep

**Comment by aruneshchandra** [comment]
any update on this ?

**Comment by weinand** [comment]
This is planned for the November release.

**Comment by aruneshchandra** [comment]
cool - when is the Nov release ? do we have a date ?

**Comment by isidorn** [comment]
@aruneshchandra the plan with the dates will be posted soon on GitHub - to get notified on each iteration plan you can follow Erich on twitter https://twitter.com/erichgamma?lang=en

**Comment by aruneshchandra** [comment]
Do we know when this might show up in Nightlies ? We will be showing a demo at NodeInteractive at the end of this month and wanted to see this in action before that.

**Comment by weinand** [comment]
We can make this happen.

**Comment by weinand** [comment]
@aruneshchandra what is the exact name for the `stepaction` attribute of the `continue` that is passed to chakra? For stepping back it was 'back'. The `stepback:continue` that you've mentioned above does not look proper.

**Comment by agarwal-sandeep** [comment]
Since the command is continue stepaction:"reverse" may be appropriate. @aruneshchandra @mrkmarron?

**Comment by weinand** [comment]
node-debug uses a value `reverse` for the `stepaction` attribute of the continue request.

**Comment by weinand** [comment]
@aruneshchandra 'reverse continue' has arrived in the Insiders build. If you install the "Mock Debug" extension, you can try the feature:

![2016-11-11_14-44-09-1](https://cloud.githubusercontent.com/assets/1898161/20216922/a007d232-a81d-11e6-8631-df5f285d623b.gif)

**Comment by aruneshchandra** [comment]
Thanx @weinand and @isidorn - this is great!
