### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by leenpaws** [microsoft/vscode#137039]
Issue Type: <b>Bug</b>
Not sure if this should be a bug report or a feature request. 

Given that it's an IDE, it'd be nice to be able to edit files without having to press buttons to enable editing.  

I'm not sure how but you managed to create something that fails at the only thing it's required to do.  I am truly amazed, also, before you try to claim it's a feature. I guarentee you that absolutely noone has ever asked for an IDE that doesn't edit.

Steps to Reproduce: 
1. open visual studio
2. try to type
3. close visual studio
4. open notepad
5. use notepad

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T09:24:32.081Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

**Comment by IllusionMH** [comment]
/needsMoreInfo

You posted a lot of text but it doesn't contain exact description of the problem and how it can be reproduced.

Please describe exactly what you try to do and how it doesn't work. Screenshots may be useful too.

P.S. VS Code not referred as an IDE :)

**Comment by leenpaws** [comment]
when I open a file and try to edit code, it doesn't edit anything.  The cursor moves around but no changes are made, I'm not sure whether a screenshot of nothing happening would be all that useful.  I am literally just trying to edit a file.  
When using linux, I'd have to press "insert" in order to be able to type, and even then the editor would do more harm than good as keybindings are mapped to unnatural and illogical commands.  Currently I'm using a Mac, so no insert key, I googled  it, but realized, even if there's a solution, this is a fundamental bug in the entire application, simply editing a file is as basic a function as you can get.    

So the best solution I found is to stop using visual studio, switch to IntelliJ, I figured I'd open a ticket just in case you're interested.  Feel free to close this issue or not.

**Comment by gjsjohnmurray** [comment]
@leenpaws I think it is reasonable to assume that your reported experience with VS Code is atypical. If you are willing to provide more information and try some diagnostic steps we may be able to help.

**Comment by IllusionMH** [comment]
Do you have any extension installed? Especially Vim extension.

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by leenpaws** [comment]
Oh man, you called it.  It was a vim extension.  Thank you for your help.
