### ISSUE TITLE
Left Arrow Key not functioning

### ISSUE THREAD

**Issue by Dartis4** [microsoft/vscode#137007]
Issue Type: <b>Bug</b>

My left arrow key does not function for moving to the left within an editor. I know the key works and it registers with other key commands (i.e. shift + left arrow) but for some reason it doesn't let me move left in editors. In the status bar it is also showing a vim like message asking for multiple inputs for a chord, but I disabled and uninstalled the vim keymap and it still does it even after restarting VSCode. I've looked through the keyboard shortcuts and mappings and I haven't found any problems yet. Really frustrating issue that really complicates editing.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (4.48GB free)|
|Process Argv|--crash-reporter-id 1f88c434-a7df-4a5d-bee3-62534efc63e4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icalendar|af4|1.0.1
vscode-javascript-snippet-pack|aka|0.1.6
Bookmarks|ale|13.2.2
code-gnu-global|aus|0.2.2
vscode-node-readme|ben|3.0.2
npm-intellisense|chr|1.4.0
bracket-pair-colorizer-2|Coe|0.2.1
doxdocgen|csc|1.3.2
vscode-eslint|dba|2.2.2
opencv-intellisense|did|0.0.4
gitlens|eam|11.6.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.23
php-debug|fel|1.22.0
php-pack|fel|1.0.2
vscode-pull-request-github|Git|0.32.0
mdmath|goe|2.7.4
todo-tree|Gru|0.0.214
opencv-snippets|gsG|1.2.2
better-cpp-syntax|jef|1.15.10
vscord|Leo|4.1.6
sftp|lix|1.12.9
vscode-docker|ms-|1.17.0
csharp|ms-|1.23.16
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.0.0
js-debug-nightly|ms-|2021.11.417
vs-keybindings|ms-|0.2.1
vscode-typescript-next|ms-|4.6.20211111
vsliveshare|ms-|1.0.5090
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
erlang|pgo|0.8.1
open-php-html-js-in-browser|Pri|2.0.1
java|red|1.0.0
vscode-xml|red|0.18.1
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.6.1
bootstrap4-vscode|the|6.1.0
pdf|tom|1.1.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
gitblame|wad|8.1.0
JavaScriptSnippets|xab|1.8.0
markdown-pdf|yza|1.4.4
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the information at https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `ArrowLeft`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
