### ISSUE TITLE
Context Menu Gets Clicked On Open

### ISSUE THREAD

**Issue by terminal-root** [microsoft/vscode#137093]
Issue Type: <b>Bug</b>

# Steps to Reproduce

1. Right click on a mid-screen section and leave cursor still.

# Expected Result

Context menu opens

# Actual Result

Context menu is opened and is clicked by cursor immediately.

# Attachments

https://user-images.githubusercontent.com/24536673/141596791-b23324b0-98cf-4aca-8b18-e38ee445e71b.mp4

# System Info

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:51:30.084Z)
OS version: Linux x64 5.13.0-21-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|31.21GB (11.26GB free)|
|Process Argv|--unity-launch --crash-reporter-id 501c7c00-cef7-4642-911d-06bd9533318f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
doxdocgen|csc|1.3.2
vcard|cst|1.0.1
vscode-autohotkey-plus|cwe|2.6.2
apt-source-list-syntax|dei|0.1.5
vscode-html-css|ecm|1.10.2
vscode-edit-csv|jan|0.6.4
better-cpp-syntax|jef|1.15.10
csharp|ms-|1.23.16
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.0.0
powershell|ms-|2021.10.2
vscode-typescript-next|ms-|4.6.20211111
vsliveshare|ms-|1.0.5090
vsliveshare-audio|ms-|0.1.91
linux-desktop-file|nic|0.0.18
vscode-autohotkey|sle|0.2.2
cmake|twx|0.0.17
colonize|vms|2.2.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by gjsjohnmurray** [comment]
Probably a duplicate of #113175

**Comment by terminal-root** [comment]
> Probably a duplicate of #113175

Thank you @gjsjohnmurray
