### ISSUE TITLE
Files in a folder not aligned to the folder they belong

### ISSUE THREAD

**Issue by alebrozzo** [Microsoft/vscode#13707]
- VSCode Version: 1.6.1 and prev as well
- OS Version: Win10

The files in a folder are not aligned to the folder they belong. This gives the impression that the files belong to a subfolder that is actually at the same level of files.

See this sample:
![image](https://cloud.githubusercontent.com/assets/18177576/19369092/b31d6806-9179-11e6-9f84-650a6812e26b.png)
all files seem to be under the "typings" folder when they are actually at root level

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11762

**Comment by alebrozzo** [comment]
thanks, I did a quick search and didn't find a similar one. I guess my search skills suck :)
