### ISSUE TITLE
UI issue - clicking on more actions on a cell activates the delete cell button

### ISSUE THREAD

**Issue by imprs** [microsoft/vscode#137041]
Does this issue occur when all extensions are disabled?: NA

- VS Code Version: 1.62.1
- OS Version: Ubuntu 18.04.5

Steps to Reproduce:

There is an old issue which summarises the issue nicely: https://github.com/microsoft/vscode/issues/114311

**Comment by roblourens** [comment]
I still can't repro this, can you explain the problem some more?

**Comment by imprs** [comment]
Hi @roblourens, hope this gif helps. It only does this when the menu opens up. And you can see that when the menu opens up, the Delete Cell button is very near to the mouse cursor and somehow both actions (More Actions + Delete Cell) are happening together, unless we are very careful.

![vscode-issue](https://user-images.githubusercontent.com/16346552/142485550-32811f68-fbf3-4c47-91b2-b4b89379b0f3.gif)

**Comment by roblourens** [comment]
I can repro, only on Linux, not Windows where we also use the custom context menu. @sbatten this is a normal dropdown action where we use the `...` button element as an anchor, any idea why the menu is showing up in the wrong place?

**Comment by sbatten** [comment]
this is a result of this longstanding issue. https://github.com/microsoft/vscode/issues/113175... from our side we cannot tell the size of the menu before it is opened so we rely on electron
