### ISSUE TITLE
Command "View: Toggle Terminal" is not working if focus is not in terminal

### ISSUE THREAD

**Issue by HapLifeMan** [microsoft/vscode#137048]
Issue Type: <b>Bug</b>

Hello,

I customized my keybinding for the `View: Toggle Terminal` to `CMD+SHIFT+T` without any condition ("When" is "-"), and it's working only if I have the focus within the terminal.

**If I'm not focused:**
- the first time I do the shortcut, it's making the focus within the terminal
- then the second time it's doing what it must do the first time: toggling the terminal view

Could you please fix it? Thanks!

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:13.307Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|64.00GB (5.52GB free)|
|Process Argv|--crash-reporter-id 76f8cf06-3585-4998-b0ff-260e0d8c8fdf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
tailwind-docs|aus|1.4.0
vscode-tailwindcss|bra|0.7.2
vscode-eslint|dba|2.2.2
gitlens|eam|11.6.1
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
gc-excelviewer|Gra|3.0.44
todo-tree|Gru|0.0.214
hungry-delete|jas|1.6.0
dotenv|mik|1.0.1
vscode-language-pack-fr|MS-|1.62.2
vscode-dotnet-runtime|ms-|1.3.0
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.66.1
vetur|oct|0.35.0
material-icon-theme|PKi|4.10.0
ruby|reb|0.28.1
java|red|1.0.0
vscode-stripe|str|2.0.8
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
vscode-ruby|win|0.28.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by Tyriar** [comment]
We changed how the toggle view commands works to only close when it's focused quite a while ago now. I recommend for your case either getting used to the close panel keybinding (cmd+j on mac I think) or setup your own keybinding to handle `CMD+SHIFT+T` differently when it's not focused.
