### ISSUE TITLE
[json] editor stops validating: `Invalid regular expression`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#137054]
Version: 1.62.2 (user setup)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:56:38.428Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Have the settings file
```json
{
	"remote.portsAttributes": {
	
        }
}
```
- add a syntax error (e.g. `xxx` at the end

- no errors reported
- JSON language server log says
```
[Error - 12:08:50 PM] Error while computing document colors for vscode-userdata:/home/martin/.config/Code%20-%20Insiders/User/settings.json: Invalid regular expression: /(^\d+(\-\d+)?$)|(.+)/: Invalid escape
SyntaxError: Invalid regular expression: /(^\d+(\-\d+)?$)|(.+)/: Invalid escape
    at new RegExp (<anonymous>)
    at x (/usr/share/code-insiders/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain.js:1:32092)
    at /usr/share/code-insiders/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain.js:1:44469
    at Q (/usr/share/code-insiders/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain.js:1:46279)
    at /usr/share/code-insiders/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain.js:1:44326
    at Q (/usr/share/code-insiders/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain.js:1:46279)
    at e.getMatchingSchemas (/usr/share/code-insiders/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain.js:1:43320)

```

**Comment by aeschli** [comment]
Fails on a regular expression `(^\d+(\-\d+)?$)|(.+)` which is part of the validation schema for the setting `remote.portsAttributes`
`-` does not need to be escaped

With the changes for https://github.com/microsoft/vscode-json-languageservice/issues/103/ we now create regular expression with flag `u` which is more restrictive regarding unnecessary escapes.

**Comment by aeschli** [comment]
The fix is to
a.) handle malformed regular expression
b.) if creating a regular expression with `u` fails, try a second time without `u`

**Comment by alexr00** [comment]
Closing for verification since it looks like this is in the release branch.
