### ISSUE TITLE
The documentation of notebook.focusedCellBorder seems incorrect

### ISSUE THREAD

**Issue by a5hk** [microsoft/vscode#137072]
Issue Type: <b>Bug</b>

The [documentations](https://code.visualstudio.com/api/references/theme-color#notebook-colors) says:
> `notebook.focusedCellBorder`: The color of the cell's top and bottom border when the cell is focused.

but the border is on the left side:
![image](https://user-images.githubusercontent.com/5412540/141514713-56243547-27b5-4237-b728-1e57495e63b2.png)

My setting is:
`"notebook.focusedCellBorder": "#006600"`

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-scilla|a5h|0.2.1
es7-react-js-snippets|dsz|3.1.1
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
vimL|fal|0.0.3
Kotlin|mat|1.7.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
vscode-icons|vsc|11.7.0
vscode-ruby|win|0.28.0
material-theme|zhu|3.13.2
tabulate|a5h|0.4.0
vscode-tailwindcss|bra|0.7.2
better-toml|bun|0.3.2
markdown-table-prettify|dar|3.6.0
dart-code|Dar|3.28.0
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.0.0
crystal-lang|fau|0.4.0
shell-format|fox|7.2.2
go|gol|0.29.0
vscode-graphql|Gra|0.3.18
todo-tree|Gru|0.0.214
beautify|Hoo|1.5.0
elixir-ls|Jak|0.8.1
language-haskell|jus|3.4.0
language-gettext|mro|0.2.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
hexeditor|ms-|1.8.2
vetur|oct|0.35.0
synthwave-vscode|Rob|0.1.10
rust|rus|0.7.8
vscode-fileutils|sle|3.4.5
code-spell-checker|str|2.0.12
sort-lines|Tyr|1.9.0

(19 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Thanks, the docs should be updated.
