### ISSUE TITLE
Accelerators in menu do not update btw restarts

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#1370]
* remove a keybinding (e.g. zoom in)
* quit and start vscode
* observe: the menu accelerator is still there

**Comment by alexandrudima** [comment]
Steps:
* open vscode (dev mode will do)
* edit keybindings.json
```
[
{ "key": "ctrl+=",                "command": "" }
]
```
* this effectively removes the keybinding for `"workbench.action.zoomIn"`
* close vscode
* open it again
* observe, menu still shows a keybinding for zoom in:
![image](https://cloud.githubusercontent.com/assets/5047891/11839101/8eaf21c0-a3eb-11e5-9b1f-6b690dabb19a.png)

This is especially bad on mac where the menu does the first keybinding dispatching

**Comment by bpasero** [comment]
Hm bad... will check
