### ISSUE TITLE
Unable to use github signin 

### ISSUE THREAD

**Issue by amanv8060** [microsoft/vscode#137063]
Issue Type: <b>Bug</b>

I am unable to use git authentication in vscode. 

Error:

remote: No anonymous write access.
fatal: Authentication failed for 'https://github.com/amanv8060/testingvscode/' 

By turning off 

git.terminalAuthentication i can do git operations normally using userid and PAT as password.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:51:30.084Z)
OS version: Linux x64 5.11.0-40-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 3, 3|
|Memory (System)|15.52GB (4.65GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 8658f06a-7cee-4cdf-be81-2831d25d660f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.0.0
copilot|Git|1.7.3733

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by amanv8060** [comment]
Update : Installed previous version from [here](https://update.code.visualstudio.com/1.61.2/linux-deb-x64/stable) 
Was able to see a prompt to allow access. 

Looks like an issue with this release itself. 

To confirm tried reinstalling latest version multiple times with deletion of ~/.vscode & ~/.config/Code , didn't work

**Comment by enricodias** [comment]
Same issue here. Solved by rolling back to version 1.62.1.

For Mac users: https://update.code.visualstudio.com/1.62.1/darwin-universal/stable

**Comment by saarcoder** [comment]
Same issue here. Rolling back to version 1.61.2 helped as well.

**Comment by warum7** [comment]
Same issue here as well. Rolling back to 1.61.2 helped.

**Comment by salimkanoun** [comment]
Same problem, downgrading vscode solved it

**Comment by fridrichmrtn** [comment]
The problem appears to be hitting 1.63 Insiders on Ubuntu 20.04.3.

**Comment by jasbel** [comment]
I have some problem in vscode windows
` Failed authenticated git remoto `
 but working with github desktop.

**Comment by cliftonamccook** [comment]
I was having the same issue. I resolved it by reverting to version 1.61.2

**Comment by RocketManNum1** [comment]
Same problem here, downgrading to previous release solved it.

**Comment by KoljaL** [comment]
Same here, but how to downgrade?

    sudo apt-get install code=1.62.1
Will not find the version.

**Comment by phhphc** [comment]
> Same here, but how to downgrade?
> 
> ```
> sudo apt-get install code=1.62.1
> ```
> 
> Will not find the version.
use `sudo apt-cache policy code` to see all version
or just `sudo apt install code=1.62.1-1636111026` in your case

**Comment by paulobordignon** [comment]
Same problem, use terminal on linux solved it

**Comment by rmarting** [comment]
Same issue in Fedora 34! Downgraded to code-1.61.2 fixed the issue (basically as a local fix, but waiting for a real fix in next version)

**Comment by iamCristYe** [comment]
is it a dup of https://github.com/microsoft/vscode/issues/137183?

**Comment by saarcoder** [comment]
> is it a dup of #137183?

GitHub signin still works with 1.62.1, so this is probably a separate issue.

**Comment by whiskybar** [comment]
1.62.3 has fixed the problem for me! Thanks!

**Comment by avishka964** [comment]
> 1.62.3 has fixed the problem for me! Thanks!

version 1.62.3 still not working for me.

**Comment by saarcoder** [comment]
1.62.3 works for me as well, hooray! 

Operating System: elementary OS 5.1.7 Hera
Kernel: Linux 5.4.0-90-generic
Architecture: x86-64

**Comment by warum7** [comment]
Confirming that 1.62.3 is working for me too. Thanks!

**Comment by avishka964** [comment]
> > 1.62.3 has fixed the problem for me! Thanks!
> 
> version 1.62.3 still not working for me. VS Code - version 1.62.3 OS - Ubuntu 20.04.03 LTS

After reinstalling **version 1.62.3** worked for me.

**Comment by DimitrisGkoutzounis** [comment]
version 1.62.3 officialy fixed the issue, works for me now!

**Comment by amanv8060** [comment]
1.62.3 working as expected for me.

**Comment by rmarting** [comment]
Version 1.62.3 works also fine in Fedora 35! Thank you so much!

**Comment by lszomoru** [comment]
Duplicate of #137183
