### ISSUE TITLE
Unable to save CPU profiles as files

### ISSUE THREAD

**Issue by miladghiravani** [Microsoft/vscode#13704]
- VSCode Version: 1.6.1
- OS Version: Windows 8.1 Enterprise 64-bit

Steps to Reproduce:
New VS Code now is update but I have problem to save **CPU profile** on version 1.6.0 and 1.6.1.
When I Start CPU profile and stop, profile is created but when I save this, see zero (empty) size file saved!
I have only 1 extension ([beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify)).
![ashampoo_snap_2016 10 14_00h53m44s_007_](https://cloud.githubusercontent.com/assets/5067331/19367587/b7a04a5e-91a8-11e6-90f1-2e8ccaa90c3e.jpg)

**Comment by isidorn** [comment]
This is a chrome bug which should hopefully get fixed soon and which we would get with an electron update in the future.
@bpasero can provide more details if needed

**Comment by bpasero** [comment]
Yup, got fixed in newer electron releases. We can keep this open to track the issue.

**Comment by joaomoreno** [comment]
electron/electron#7403
