### ISSUE TITLE
Be able to open multiple repos at a time.

### ISSUE THREAD

**Issue by LawrenceHwang** [Microsoft/vscode#13709]
Hello,

- VSCode Version:1.6
- OS Version: Windows 10

Steps to Reproduce:
Consider following scenario: multiple Git repos are clones under one base directory (not Git initialized). The user want to be able to open more than one repo at the same time.

```
Repositories (base folder, not Git initialized)
  |
  |-- Project 1
  |-- Project 2
  |-- Project 3
.....
  |-- Project N

```
At the moment, if opening the Repositories folder in VSCode workspace, everything below will be considered as non-Git initialized even though they are.

Thank you kindly.

Lawrence

**Comment by joaomoreno** [comment]
Sorry, we don't plan on supporting this scenario.

**Comment by ischyron** [comment]
why?

**Comment by joaomoreno** [comment]
@ischyron You should check #396, there's some work being done there.
