### ISSUE TITLE
suggestions not showing

### ISSUE THREAD

**Issue by OmkarGharat** [microsoft/vscode#137038]
Issue Type: <b>Bug</b>

When I type in javascript and in react, it is not showing suggestions. I have downloaded and tried a lot of extensions but it is not working. I don't know the reason. When I start typing, it should show a list of properties of ReactJS that match my typing initials

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.88GB free)|
|Process Argv|--crash-reporter-id 6b37e759-55ad-40be-ad31-1f59935b101a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
All-Autocomplete|Ati|0.0.23
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|3.1.1
prettier-vscode|esb|9.0.0
auto-close-tag|for|0.5.13
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.9
code-runner|for|0.11.6
vscode-language-babel|mgm|0.0.35
vscode-typescript-next|ms-|4.6.20211111
material-icon-theme|PKi|4.10.0
vscode-thunder-client|ran|1.9.1
LiveServer|rit|5.6.1
codelf|unb|11.7.0
vscodeintellicode|Vis|1.2.14
JavaScriptSnippets|xab|1.8.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the "Start Extension Bisect" command to see if the problem is being caused by one of your extensions.
