### ISSUE TITLE
Module load gone

### ISSUE THREAD

**Issue by Riya7500** [microsoft/vscode#137069]
Issue Type: <b>Bug</b>

bash-4.2$ module load
bash: module: command not found
bash-4.2$ module load python
bash: module: command not found
bash-4.2$ module load Trimmomatic/0.36
bash: module: command not found

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
material-theme|zhu|3.13.2

(3 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Please update to 1.62.2 in case you are hitting one of the problems it fixed.
