### ISSUE TITLE
unable to run saved programs

### ISSUE THREAD

**Issue by indianprogrammer01** [microsoft/vscode#137136]
Issue Type: <b>Bug</b>

when we save programs in c drive(desktop) the code execute without any error but when we save the same program in other directories ,this program terminated with error of g++.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (7.37GB free)|
|Process Argv|--crash-reporter-id df583420-6141-41ba-af23-6f14ba2e5fb6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
doxdocgen|csc|1.3.2
code-runner|for|0.11.6
vscode-pull-request-github|Git|0.32.0
better-cpp-syntax|jef|1.15.10
data-workspace-vscode|ms-|0.1.0
mssql|ms-|1.11.0
sql-database-projects-vscode|ms-|0.13.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.5090
vsliveshare-audio|ms-|0.1.91
sqltools|mtx|0.23.0
sqltools-driver-mssql|mtx|0.2.0
cmake|twx|0.0.17
plsql-language|xyz|1.8.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by chrmarti** [comment]
Do you see this error when you run the program without VS Code?

**Comment by indianprogrammer01** [comment]
Sir,
I had run the program in different compilers but they give me correct
result.
But in vs code,it shows gcc error and cc1plus error no such file exists in
directory.
When i run program the .exe file is not creating.i dont know the exact
reason behind it.

**Comment by chrmarti** [comment]
This sounds like you might have your paths setup incorrectly. Please check the documentation https://code.visualstudio.com/docs/languages/cpp or introductory videos https://code.visualstudio.com/docs/cpp/introvideos-cpp to see some working setups.

**Comment by indianprogrammer01** [comment]
Sir i already done everything correctly with the path of mingW.

**Comment by chrmarti** [comment]
Could you attach a screen recording of what you do to run it in VS Code?
