### ISSUE TITLE
Allow disabling release notes popup tab

### ISSUE THREAD

**Issue by matkoniecz** [microsoft/vscode#137137]
When new version appears an unwanted (at least for me) popup tab appears. Please, allow to disable showing this release notes.

I use this editor because it requires far less configuration, management and handling than Sublime Text required.

Maybe assuming that people in general are interested in internal iteration plans, but please give option to opt-out from that.

In case that there is some actually significant feature I will learn about it - and looking through release notes is not an effective way to do this. Especially as it starts from things that are of interest for people following internal plans, rather than from changes directly affecting users.

When I open code editor I intended to work and distractions are not really welcome. Please, allow disabling them.

In some cases when I was interested in internal development I can easily subscribe to them, check them manually or use one of many ways to consume that content. I do not want it displayed in my code editor.

![screen](https://user-images.githubusercontent.com/899988/141657602-66501e83-7961-46f7-8dd5-a234ae7418f5.png)

Searches that I used to avoid duplicates: https://github.com/microsoft/vscode/issues?q=disabling+release+notes+is%3Aopen and looked through https://github.com/microsoft/vscode/issues/9539 including search for word "release"

**Comment by gjsjohnmurray** [comment]
`"update.showReleaseNotes": false` should do it.
