### ISSUE TITLE
Command-clicking window title while moving cursor results the strange behavior

### ISSUE THREAD

**Issue by dnicolson** [microsoft/vscode#137176]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.2
- OS Version: macOS 11.6 (20G165)

Steps to Reproduce:

1. Command-click window title while moving cursor down and to the right

![command click](https://user-images.githubusercontent.com/2276355/141692299-2f4ef775-dfd5-4659-8362-e56ef98476ca.gif)

It is possible to change the selection while the cursor does not move. The issue does not exist with `"window.titleBarStyle": "native"` or clicking without moving the cursor.

**Comment by sbatten** [comment]
that's a native menu, so something weird in electron @deepak1556

**Comment by deepak1556** [comment]
I am unable to repro with latest insiders, please check if the issue still persists https://code.visualstudio.com/insiders
