### ISSUE TITLE
remote: No anonymous write access.

### ISSUE THREAD

**Issue by faresdjefaflia** [microsoft/vscode#137178]
There is a problem with the latest version, an error with GitHub, and the code cannot be submitted and push

**Comment by faresdjefaflia** [comment]
**https://github.com/microsoft/vscode/issues/137161#issuecomment-968833263**

**Comment by SerhiyAndryeyev** [comment]
I have the same issue, but I can't downgrade VSCode. Can I wait and hope that it will be fixed soon?

**Comment by faresdjefaflia** [comment]
> I have the same issue, but I can't downgrade VSCode. Can I wait and hope that it will be fixed soon?

Why can't you go back? It is better to come back as well, they said that the problem will be fixed in the next update

**Comment by exposir** [comment]
I have the same problem 

>remote: No anonymous write access.
fatal: Authentication failed for 'https://github.com/exposir/app.git/'

**Comment by ArshadRahim** [comment]
I have the same problem. can't push the code.  It says "No anonymous write access" although I've add the SSH, configured my user and email,  changed origin a lot of times,  restarted vs code and everything. But seems like I'm having no luck.

**Comment by HelenFess** [comment]
I hope so, I am having the same issue. I can't push my work.

**Comment by faresdjefaflia** [comment]
Guys, the solution is to go back to the old version or wait for the new one
Alternatively, you can use the command line if you are using Linux

**Comment by gjsjohnmurray** [comment]
@HelenFess see tps in https://github.com/microsoft/vscode/issues/137161#issuecomment-968726316

But 1.62.3 may be out within the next 24 hours.
