### ISSUE TITLE
Duplicate editor.renderWhitespace setting in split JSON editor

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode#137122]
Issue Type: <b>Bug</b>

The following appears twice in `settings.json`.
```json
  // Controls how the editor should render whitespace characters.
  //  - none
  //  - boundary: Render whitespace characters except for single spaces between words.
  //  - selection: Render whitespace characters only on selected text.
  //  - trailing: Render only trailing whitespace characters.
  //  - all
  "editor.renderWhitespace": "selection",
```

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.36.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (2.30GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 255a4b22-d8e4-4854-9527-eb963404bbb6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: csd3|
|OS|Linux x64 3.10.0-1160.36.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz (32 x 3399)|
|Memory (System)|187.37GB (146.04GB free)|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by janosh** [comment]
![Screen Shot 2021-11-13 at 15 50 24](https://user-images.githubusercontent.com/30958850/141650346-c8f9fb1d-74e0-45b6-97f8-aec5a70d3a37.png)
![Screen Shot 2021-11-13 at 15 50 39](https://user-images.githubusercontent.com/30958850/141650347-813da8b0-465c-4e65-98c7-e9f1e2f11800.png)

**Comment by gjsjohnmurray** [comment]
Based on the comments in your `settings.json` these sections seem to have been copied from defaultSettings.json which you can view via the command `Preferences: Open Default Settings (JSON)`. It looks like the "editor.renderWhitespace" section was copied twice. I don't think VS Code would have done that.

I suggest you delete the duplicate section. If you discover steps to reproduce the duplication please add them to this issue.

**Comment by janosh** [comment]
> I suggest you delete the duplicate section. If you discover steps to reproduce the duplication please add them to this issue.

@gjsjohnmurray I should have made myself more clear. The screenshots above _are_ from the `defaultSettings.json`, i.e. from the lhs of the JSON settings editor which is not user-editable. I cannot delete this duplication.

**Comment by gjsjohnmurray** [comment]
Doesn't reproduce for me. I am on Windows:

![image](https://user-images.githubusercontent.com/6726799/141683798-baf5f7ab-8a90-4a7f-aa1b-1bb2f7348f89.png)

**Comment by rzhao271** [comment]
Repro'd with `workbench.settings.useSplitJSON` set to true.

**Comment by rzhao271** [comment]
Potential code pointer
https://github.com/microsoft/vscode/blob/c8e2fd7baeaa8cd9dc43d3051db66a7428309c97/src/vs/workbench/services/preferences/browser/preferencesService.ts#L397

@sandy081 I'm wondering how those default setting file contents are created?

**Comment by sandy081** [comment]
Model for default settings file is created here:

https://github.com/microsoft/vscode/blob/c8e2fd7baeaa8cd9dc43d3051db66a7428309c97/src/vs/workbench/services/preferences/browser/preferencesService.ts#L121

**Comment by rzhao271** [comment]
Ok I see it now. https://github.com/microsoft/vscode/blob/df97a577be1d3f8848e7bb1b8f97fe669086af71/src/vs/workbench/services/preferences/common/preferencesModels.ts#L741 combines the groups into text, and because the "most commonly used" groups pulls settings from other groups, there are some repeats.

**Comment by rzhao271** [comment]
@janosh the `editor.renderWhitespace` setting in particular is duplicated because it shows up both in the "mostCommonlyUsed" settings group, as well as the editor settings group. I'm therefore wondering if you would prefer that the current split json editor get rid of the mostCommonlyUsed settings group on the left-hand side? I personally think it is worth keeping, because it allows commonly used settings to immediately show up when opening that editor for the first time.

**Comment by janosh** [comment]
@rzhao271 I never realized mostCommonlyUsed settings show up at the top. I always do cmd+f to jump to settings. Maybe worth looking at the top settings before doing that in the future. But I'd still say it's better behavior for settings to only show up once.

**Comment by sandy081** [comment]
@rzhao271 I think keeping most commonly used settings on the top makes sense if the settings are grouped and I think they are not. So, IMO it is better to show distinct settings if it is a flat list.

**Comment by rzhao271** [comment]
Reopening because the fix somehow broke settings search for the UI editor https://github.com/microsoft/vscode/commit/cdcc51d52106fe9412caf5ab0d1da812c3a06f72
