### ISSUE TITLE
Find/Replace should default to Find in Selection when multiple lines are selected

### ISSUE THREAD

**Issue by dannypike** [microsoft/vscode#137177]
The Visual Studio IDE defaults to searching in the selection (i.e. Alt_l mode), if a multi-line selection is active when I start a search. Currently, I have to remember to hit `Alt-L` after every `Ctrl-F` or `Ctrl-H`, or I the selection gets lost and Code resets to acting on the whole file.

It would be nice if there was an option to make Visual Studio Code to use the same behaviour as the Visual Studio IDE.

**Comment by yume-chan** [comment]
`"editor.find.autoFindInSelection": "multiline"`

**Comment by dannypike** [comment]
Thank you!
