### ISSUE TITLE
notebook can't  select any kernel 

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#137187]
Does this issue occur when all extensions are disabled?: Yes

版本: 1.63.0-insider (system setup)
提交: 3bd29c1d6c6ef5b6265614def99b7257b671ae19
日期: 2021-11-12T12:04:20.740Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22499
Steps to Reproduce:
![image](https://user-images.githubusercontent.com/1876302/141704584-723a8c9c-6bb1-4ac9-becb-cbaaf40be6e5.png)
BTW
V1.62.2 WORK WELL

**Comment by roblourens** [comment]
Sorry for the slow response. Is this still happening in Insiders?
