### ISSUE TITLE
Mouse support for tmux on Windows 10 RDP Sessions

### ISSUE THREAD

**Issue by rbreaves** [microsoft/vscode#137147]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.2
- OS Version: Windows 10 (any build)

Steps to Reproduce:

1. RDP into a Windows 10 system
2. Open VSCode and the terminal (assumably Powershell)
3. ssh into either a Linux VM or WSL
4. Run tmux w/ mouse support enabled (via ~/.tmux.conf)
5. Split Tmux session w/ 2 panes (left & right) - C+b, % - that should do the split
6. Attempt to grab the vertical bar in the center and move it left and right

This may also fail to work directly on Windows 10 when tried through Powershell or WSL. I am not sure why, when I tested this under Windows 11 via RDP it all works fine. So I am not sure what changes with 11 - but the handling of this type of input I guess was improved or changed and it would be great to see that fix get backported or accounted for concerning Windows 10.

From the best of my knowledge this is not a duplicate bug - I recognize that there are a lot of similar tickets to this that are close, but I do not believe they are the same and certainly did not lead to a resolution of this problem. There has to be a better fix than upgrading to Windows 11.

**Comment by Tyriar** [comment]
We use "conpty" as the terminal's backend which is a component built into Windows. Unfortunately upgrading to Windows 11 (or waiting for a new 10 drop) is the way to fix this.
