### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by sanxing91221** [Microsoft/vscode#13713]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: anseki.vscode-color-0.1.11, be5invis.vscode-icontheme-nomo-dark-1.1.4, emmanuelbeziat.vscode-great-icons-1.1.11, hdg.live-html-previewer-0.0.1, herrherrmann.angular-bootstrap-4.0.6, idleberg.icon-fonts-1.0.8, idleberg.icon-fonts-legacy-1.0.7, johnpapa.Angular1-0.1.16, justinjames.ionic1-snippets-1.0.1, LaurentTreguier.vscode-simple-icons-0.1.6, PKief.material-icon-theme-1.1.1, qinjia.seti-icons-0.1.1, robertohuertasm.vscode-icons-3.0.4, SirTobi.code-bing-0.2.0, wcwhitehead.bootstrap-3-snippets-0.0.7

Steps to Reproduce:

1."ctrl + /" in HTML
2.<style></style> in html

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/11081
