### ISSUE TITLE
Terminal: part of terminal content gets overlapped with terminal tab

### ISSUE THREAD

**Issue by raviteja83** [microsoft/vscode#137113]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.2
- OS Version: MacOS Big Sur 11.6

Steps to Reproduce:

1. open terminal
![image](https://user-images.githubusercontent.com/6763261/141645443-1154ff73-4868-4c9e-b2e4-cdde062bd3a6.png)

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
