### ISSUE TITLE
Allow to Open multiple files in background tabs from quick open

### ISSUE THREAD

**Issue by rosslavery** [Microsoft/vscode#13711]
- VSCode Version: 1.6
- OS Version: Windows 10x64

While developing components that span across multiple files (.ts, .html, .css), it is quite common to need to open all related files for a given component. In Sublime, this is achieved by pressing `ctrl+right-arrow` while highlighting a result in their "quick open" panel. This opens the highlighted file in a background tab while keeping the existing results set open.

In VSCode, you have to perform the same query multiple times, each time selecting the next file.

Demo Gif:
[Background Open](http://i.imgur.com/nJ4T0aB.gifv)

**Comment by bpasero** [comment]
Maybe an area for a PR 👍

**Comment by wprater** [comment]
I could implement this, but do we have consensus on the key modifiers and their behavior?  currently we can open in a new group using the `cmd` modifier.

**Comment by bpasero** [comment]
If we can use what other editors typically use here, sounds good.

**Comment by wprater** [comment]
> If we can use what other editors typically use here, sounds good.

looks like in ST, it's just the right arrow!  I'll push a PR.
