### ISSUE TITLE
CodeLens isn't properly rendering html elements anymore

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#13714]
- VSCode Version: `Version 1.7.0-insider (1.7.0-insider)` 5dd716eaedc5a239379013863568c7f7dea708a5
- OS Version: `macOS Sierra 10.12 (16A323)`

In 1.7:
>![image](https://cloud.githubusercontent.com/assets/641685/19373256/9cb94136-9190-11e6-9764-015684fcc7ce.png)

in 1.6:
>![image](https://cloud.githubusercontent.com/assets/641685/19373291/e5fa0f7e-9190-11e6-8ad6-485551bdbc4a.png)

**Comment by jrieken** [comment]
That was done on purpose to fix an issue that would allow arbitrary code execution via code lens (https://github.com/Microsoft/vscode/issues/13242)

Sorry, for forgetting to release note that. May the unicode arrow table can help you: http://unicode-table.com/en/sets/arrows-symbols/

**Comment by eamodio** [comment]
Ah ok thanks -- this is affecting [VersionLens](https://github.com/vscode-contrib/vscode-versionlens) /cc @pflannery
