### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by C8338Soner** [microsoft/vscode#137186]
- Issue Type: `Bug`
- Extension Name: `git`
- Extension Version: `1.0.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.62.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
