### ISSUE TITLE
Please provide a UI option to enter commandline arguments when running Python programs

### ISSUE THREAD

**Issue by nav9** [microsoft/vscode#137129]
I've worked with a team that created one Python package (which contained an `__init__.py` file). Inside that package, they'd create multiple `.py` files, each meant to perform various tasks. Many of those files had their own main functions too. So these guys were running those files from the commandline, and passing commandline arguments to it (like `python3 prog1.py --file \somedir\somefile.csv --n 23`. This is clearly a misuse of Python, but they had their deadlines to meet.
Now I'm expected to use and debug those programs, and I'm unable to run the program from VS Code, because the IDE does not have an option to specify commandline parameters. I know you offer a method of editing the config file, but there are two issues with this:  
1. There are many files in this project that have their own main function. So even though all these files belong to one package, I have to be able to run it by specifying custom commandline options for each file I have currently opened. So right next to the triangular run button, if you provide a textfield to specify commandline arguments that are specific to the file currently opened, it'd help.
2. One should not have to open and edit a config file for functionality that should be available via the UI options.

**Comment by gjsjohnmurray** [comment]
/extPython

The run and debug features are always contributed by language-specific extensions.
