### ISSUE TITLE
Improve language detection for small inputs

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#137104]
The current language detection model typically is unable to provide high-confidence results for small inputs. It'd be nice if we could develop a model that excelled at guessing languages based on limited tokens.

**Comment by Igorgro** [comment]
@JacksonKearl  Excuse me, where the source code of 'vscode-regexp-languagedetection' can be found?

**Comment by JacksonKearl** [comment]
I have not received approval from legal to release the model I developed publicly at the moment. I can try to answer any questions you might have about it.

**Comment by Igorgro** [comment]
@JacksonKearl Thank you. I'm just disappointed that this repository claims to be open-source but depends on proprietary blobs like this 😕
