### ISSUE TITLE
onDidChangeTextEditorSelection would not fire when select across word like Ctrl + Shift + Right

### ISSUE THREAD

**Issue by GitPopcorn** [microsoft/vscode#137118]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.2 x64
- OS Version: Windows 10 20H2 19042.1288

Steps to Reproduce:

1. Create a vscode extension and event listener for , or you can just use the exist project <https://github.com/pranshuagrawal/vscode-toggle-case.git>.
2. Try create a breakpoint or log point, then select word using Ctrl + Shift + Right, see if the listener will be triggered.

**Comment by alexdima** [comment]
@GitPopcorn I cannot reproduce. Here is what I have tried:
* `package.json`:
```
{
    "name": "137118",
    "publisher": "alex",
    "version": "0.0.1",
    "engines": {
        "vscode": "^1.22.0"
    },
    "activationEvents": ["*"],
    "main": "main.js"
}
```
* `main.js`:
```
const vscode = require("vscode");

exports.activate = function (ctx) {
  vscode.window.onDidChangeTextEditorSelection((e) => {
    console.log(`selection change`, e);
  })
};
```

When I open a file and do ctrl+shift+right which causes the selection to change, I see the console log statement.

**Comment by GitPopcorn** [comment]
> @GitPopcorn I cannot reproduce. Here is what I have tried:
> 
> * `package.json`:
> 
> ```
> {
>     "name": "137118",
>     "publisher": "alex",
>     "version": "0.0.1",
>     "engines": {
>         "vscode": "^1.22.0"
>     },
>     "activationEvents": ["*"],
>     "main": "main.js"
> }
> ```
> 
> * `main.js`:
> 
> ```
> const vscode = require("vscode");
> 
> exports.activate = function (ctx) {
>   vscode.window.onDidChangeTextEditorSelection((e) => {
>     console.log(`selection change`, e);
>   })
> };
> ```
> 
> When I open a file and do ctrl+shift+right which causes the selection to change, I see the console log statement.

Sorry dude, I forgot the validation of incoming param and put the breakpoint at the wrong position. This issue was a farce.

Thank you for your test and sorry for wasting your time, I'll create a brand new enviroment and plugin demo to test issues after this.
