### ISSUE TITLE
problemas pos atualizações

### ISSUE THREAD

**Issue by thiagovieira7** [microsoft/vscode#137150]
Issue Type: <b>Bug</b>

Estou tendo problemas que o vs code nao realiza push para o github. Isso ocorreu apos a ultima atualização.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:51:30.084Z)
OS version: Linux x64 5.4.0-90-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2253)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.63GB (1.18GB free)|
|Process Argv|--unity-launch --crash-reporter-id d8d25e37-ffae-432d-a9c0-07032e5c5cdd|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
jsonviewer|cci|1.2.2
vscode-devtools-for-chrome|cod|0.0.7
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.2.2
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
code-runner|for|0.11.6
vscode-pull-request-github|Git|0.32.0
mongodb-vscode|mon|0.6.14
vscode-language-pack-pt-BR|MS-|1.62.3
material-icon-theme|PKi|4.10.0
vscode-thunder-client|ran|1.9.1
LiveServer|rit|5.6.1
tabnine-vscode|Tab|3.4.35

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe #137063
