### ISSUE TITLE
make .devcontainer work on github.dev!

### ISSUE THREAD

**Issue by lucaszanella** [microsoft/vscode#137191]
github.dev's online editor is REAAAAAALLY useful. However, for complex languages like C, C++, Rust you cannot run anything on the browser. I'd pay for being able to edit something inside github.dev and it would open the .devcontainer/devcontainer.json file from the VSCode Remote Devcontainer plugin (https://code.visualstudio.com/docs/remote/create-dev-container) on a VM, build the docker image and let me test things on browser. 

Imagine being able to share your project with other people and they just build and do changes inside the browser without ever cloning anything. Just press "." and you have an editor with a compilable project

**Comment by Lemmingh** [comment]
<https://github.co/codespaces-editor-help>

You should purchase [Codespaces](https://github.com/features/codespaces) to get a VM.

**Comment by lucaszanella** [comment]
Nice, there should be a button on the future saying that it's possible, at least when there's a .devcontainer folder on the project, or you try to install the devcontainer plugin on the github dev editor. Thanks!
