### ISSUE TITLE
Bug emmet inculdelanguages javascriptreact

### ISSUE THREAD

**Issue by adrian1426** [microsoft/vscode#137131]
is not autocomplete or suggestions with emmet javascriptreact.

emmet for this is activated.
"emmet.includeLanguages": {
        "javascript": "javascriptreact"
    }

before this update worked good

**Comment by harryghgim** [comment]
Same here with different language.

```
  "emmet.includeLanguages": {
    "django-html": "html"
  }
```

django-html used to be shipped with html snippet suggestion with the settings above, but not anymore. 

Fix would be much appreciated.

**Comment by rzhao271** [comment]
Thanks for the info. Merging with #137012
