### ISSUE TITLE
"Shift + Tab" in VS Code like Jupyter Notebook

### ISSUE THREAD

**Issue by alfredojoseneto** [microsoft/vscode#137162]
Hi! I would like to recommend the "shift + tab" functionality into VS Code like the behavior from Jupyter Notebook. I like to hover the mouse on a function, but this "shift+tab" will be great! Thanks in advance

**Comment by rebornix** [comment]
You can add following snippet to your Keybindings file (ctrl+k, ctrl+s and then open the text file from the editor toolbar)

```
	{
		"key": "shift+tab",
		"command": "editor.action.showHover",
		"when": "editorTextFocus"
	}
```
