### ISSUE TITLE
REPLS for vscode

### ISSUE THREAD

**Issue by carellagermano** [microsoft/vscode#137184]
I would suggest to create an internal REPL for HTML, css and javascript and one for vscode extensions, for playing with javascript.
I'm visually empaired and I work with REPLS, such as node.js, but, for some frameworks, such as electron, there is no REPL that work under windows.
if this already exists, can you suggest? I searched on google, but I found nothing.

**Comment by aeschli** [comment]
Check out https://www.electronjs.org/docs/latest/tutorial/repl/. I that what you meant?
If not, can you describe what functionality you expect from a REPL?
