### ISSUE TITLE
Sluggish integrated terminal

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode#137123]
Issue Type: <b>Bug</b>

As soon as the integrated terminal has enough text to start scrolling, it becomes sluggish and very unpleasant to use.

Happens with all extensions disabled. On macOS Moneterey and Big Sur.

Tried the fix suggested [here](https://github.com/microsoft/vscode/issues/108590#issuecomment-745503151) several times. Not helping

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.36.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (2.25GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 255a4b22-d8e4-4854-9527-eb963404bbb6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: csd3|
|OS|Linux x64 3.10.0-1160.36.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz (32 x 1943)|
|Memory (System)|187.37GB (146.29GB free)|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by meganrogge** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.


also please provide a gif

**Comment by janosh** [comment]
@meganrogge Sorry about the lack of information. Hope this helps:

https://user-images.githubusercontent.com/30958850/141979667-e9d505f3-4714-41c5-a610-0e7c2cb7bdb3.mp4

[Profile-20211116T114235.zip](https://github.com/microsoft/vscode/files/7545983/Profile-20211116T114235.zip)

**Comment by meganrogge** [comment]
thanks for that. can you open dev tools and capture a performance profile while you are scrolling/seeing the sluggish behavior?

**Comment by janosh** [comment]
I did. See the zip attachment on my earlier comment.￼

**Comment by Tyriar** [comment]
The perf profile is a little weird, looks like there isn't a renderer JS problem:

![image](https://user-images.githubusercontent.com/2193314/142887095-16886a9c-771b-4ef2-b5d5-c39b5d8c1393.png)

Can you try changing the `terminal.integrated.gpuAcceleration` setting and seeing if that helps?

**Comment by janosh** [comment]
That helps! It was set to `"terminal.integrated.gpuAcceleration": "auto"`. Changing it to `"on"` did nothing. But `"off"` and `"canvas"` make scrolling much smoother.

**Comment by Tyriar** [comment]
Ah ok, looks like your machine is one of the edge cases where the webgl isn't playing nicely with your graphics card/drivers for some reason.

**Comment by janosh** [comment]
MacBook Pro 16-inch from 2019. Shouldn't this be addressed in additional edge case detection? These machines are going to be around for quite some time to come.

**Comment by Tyriar** [comment]
I'm not sure there's a reliable way to detect this, plus your machine seems like a one off, it doesn't happen on the majority of macbooks or this would be reported more (from within the team and the public). Updating your OS might help if it's not up to date.

**Comment by janosh** [comment]
This occurred on multiple OS versions. Started under macOS 11 and stayed under 12.0.1 (running now).
