### ISSUE TITLE
[Feature Request] Folder explorer and the opened files should be separated.

### ISSUE THREAD

**Issue by ithieund** [Microsoft/vscode#13717]
The folder explorer is always focusing to the opened files. Which is not good and sometimes inconvenient .

**For example:**
- I purposely opened a file at root to edit
- After that, I tried to open another file at /path/path/file1.php. The folder explorer is focus to this file in /path/path/. It seems goods, but
- The file1.php have no information I needed then I close this file and intended to open file2.php in the folder /path/path. But after closing file1.php, the folder explorer automatically focus back to the opened file at root.
- To open /path/path/file2.php, I have to relocate the folder /path/path again, which take time in inconvenience for me.

**Suggested feature:**
- There should be a configuration to set auto-focus on opened file or not. User can select which option is best suite.
- In case the auto-focus is off. User can right click at the opened file name in editor to select 'Locate in Folder Explorer' option.

This feature is what Nusphere PHP ED supported and I think it is really smart.
Thanks.

**Comment by bpasero** [comment]
@ithieund try `explorer.autoReveal": false`

**Comment by ithieund** [comment]
@bpasero ,
It tried it, it worked. But we have no way to reveal the opened file again in Folder Explorer, right?
Then I then it's better to have context menu option in the opened file name to 'Locate in Folder Explorer'.

Thanks.

**Comment by bpasero** [comment]
There is Command Palette > Show Active File In Explorer
