### ISSUE TITLE
Add more detailed scopes to C# language rules, to allow finer syntax coloring control

### ISSUE THREAD

**Issue by kraybit** [microsoft/vscode#137159]
## Feature Request Description ##
- I'd like to be able to set different colors for different storage modifers like `public` and `private`, in C# code. For this I believe we'd need more detailed scopes.
- Right now, both the `public` and `private` modifier has the textmate scope `storage.modifier.cs, source.cs`, which means it's impossible (?) to distinguish between them when coloring.

**Suggestion**
- Add finer scopes, such as `storage.modifier.public.cs` for the `public` modifier, and so on.
- So that settings like these would work:

```json
"editor.tokenColorCustomizations": {
  "textMateRules": [
    {
      "scope": "storage.modifier.public",
      "settings":{"foreground": "#F00"}
    }
  ]
}
```
*Example of what does **not** work right now, as `storage.modifier.public` does not exist.*

## Environment information ##
**VSCode version**: 1.62.2
**C# Extension**: 1.23.16

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.402
 Commit:    e9d3381880

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.402\

Host (useful for support):
  Version: 5.0.11
  Commit:  f431858f8b

.NET SDKs installed:
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.402 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
</details>

<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|bio-dark-theme|studiobio|0.1.5|
|cpptools|ms-vscode|1.7.1|
|csharp|ms-dotnettools|1.23.16|
|material-icon-theme|PKief|4.10.0|
|theme-dracula|dracula-theme|2.24.0|
|todo-tree|Gruntfuggly|0.0.214|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-debug|Unity|3.0.2|
|vscode-counter|uctakeoff|2.3.0|
|vscode-theme-onedark|akamud|2.2.3|
|vscode-unitymeta|PTD|0.0.7|;

</details>

**Comment by yume-chan** [comment]
Please file your feature request to the C# extension repository: https://github.com/OmniSharp/omnisharp-vscode/issues
