### ISSUE TITLE
Why is solution loading project rather than Nuget Package? - help

### ISSUE THREAD

**Issue by patricknolan** [Microsoft/vscode#13715]
Hi, I'm running VS 2015 Update 3 and am seeing something quite strange.

I created a .xproj project (lets call it "ProjectA") which I deployed as a Nuget package to the Nuget store.

I then created a new solution and a new .xproj project (lets call it "ProjectB") from which I referenced the Nuget package for ProjectA.

There seemed to be an issue so I removed the package reference from my project.json file, added the ProjectA .xproj to my solution and debugged the issue successfully. I then removed ProjectA from my solution, re-deployed  ProjectA to the Nuget store and referenced the updated Nuget Package for ProjectA from ProjectB.

However, for some reason, whenever I open my solution or try and restore my packages, it still tries to load the ProjectA .xproj into my solution... even though there is no reference to it in the Solution file.

This is extremely strange behaviour. Does anyone know why this is happening and how to stop the .xproj loading into the solution when it has been removed?

**Comment by isidorn** [comment]
Hey @patricknolan I believe you are at the wrong repository. This one is for filling issues for visual studio code, more about our product can be found here https://code.visualstudio.com/
