### ISSUE TITLE
No authentication bar in git

### ISSUE THREAD

**Issue by AlexandreAndrade00** [microsoft/vscode#137144]
Issue Type: <b>Bug</b>

When i try to push to gitlab, push fail without requesting autentication.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:51:30.084Z)
OS version: Linux x64 5.11.0-40-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1600)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 0|
|Memory (System)|7.46GB (2.55GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id b3fecbee-7be6-486f-8271-af9c274ca7bf|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
yash|dao|0.2.8
es7-react-js-snippets|dsz|3.1.1
better-cpp-syntax|jef|1.15.10
vscode-docker|ms-|1.17.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.0.0
vscode-react-native|msj|1.8.0
material-icon-theme|PKi|4.10.0
markdown-preview-enhanced|shd|0.6.1
pdf|tom|1.1.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the Git channel of the OUTPUT tab of Panel give any details you are able to share?

**Comment by gjsjohnmurray** [comment]
Maybe a duplicate of #137063

**Comment by AlexandreAndrade00** [comment]
Duplicate of #137063.
