### ISSUE TITLE
Smoke: Flaky `Search replaces first search result with a replace term`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#137195]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=142831&view=logs&j=306b2268-2a17-5e97-ab97-f41a26dc5206&t=ac333dbf-2cf5-57c7-3dca-c00ab22505d6&l=86

```
1) VSCode Smoke Tests (Electron)
       Search
         replaces first search result with a replace term:
     Error: Timeout: get text content '.search-view .messages .message' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:180:19)
      at async Code.waitForTextContent (D:\a\1\s\test\automation\out\code.js:244:16)
      at async Search.waitForResultText (D:\a\1\s\test\automation\out\search.js:91:9)
      at async Context.<anonymous> (out\areas\search\search.test.js:59:13)

```
![VSCode_Smoke_Tests__Electron__Search_replaces_first_search_result_with_a_replace_term](https://user-images.githubusercontent.com/900690/141730943-4110878d-2ff6-42d6-854f-c0c291400f9c.png)

**Comment by roblourens** [comment]
Seems like it at least tried to click the replace button, but the replace didn't happen.

**Comment by bpasero** [comment]
Happened again today in win32 tests, twice:
* https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=143848&view=logs&j=306b2268-2a17-5e97-ab97-f41a26dc5206&s=27eddb93-7805-576c-c80f-37b2176e40f7&t=e0502e0c-f9d6-51c4-6284-857392e0724b&l=88
* https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=143848&view=logs&j=24a3b84e-db50-5143-6e9a-d87cf4b12ca4&s=40b405d8-d9ea-5f38-8ab3-8db0b216e2d0&t=54076648-d3c6-55a5-6f57-4b9b481d56a9&l=88

**Comment by roblourens** [comment]
The screenshots always show the same thing where it looks like the button is being hovered but maybe was not clicked. Did anything change in the smoke test recently, like with how clicks happen? Nothing changed in the search view. Gonna disable the test for now

**Comment by bpasero** [comment]
Not to my knowledge.

**Comment by bpasero** [comment]
Similar, without remote: https://github.com/microsoft/vscode/issues/139269

**Comment by bpasero** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=146780&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=6e7e74bd-a473-53b1-acea-ad5f8c1f1ec9&l=73

```
1) VSCode Smoke Tests (Electron)
       Search
         replaces first search result with a replace term:
     Error: Timeout: get text content '.search-view .messages .message' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:65:19)
      at async Code.waitForTextContent (D:\a\1\s\test\automation\out\code.js:168:16)
      at async Search.waitForResultText (D:\a\1\s\test\automation\out\search.js:96:9)
      at async Context.<anonymous> (out\areas\search\search.test.js:60:13)

```

![replaces_first_search_result_with_a_replace_term](https://user-images.githubusercontent.com/900690/146024410-86a2b6fb-049f-4374-bf42-f671f629ac79.png)

**Comment by bpasero** [comment]
```
  1) VSCode Smoke Tests (Electron)
       Search
         replaces first search result with a replace term:
     Error: Timeout: click '.search-view .results .filematch[data-resource$="app.js"]' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:65:19)
      at async Code.waitAndClick (D:\a\1\s\test\automation\out\code.js:172:9)
      at async D:\a\1\s\test\automation\out\search.js:90:13
      at async retry (D:\a\1\s\test\automation\out\search.js:16:9)
      at async Search.replaceFileMatch (D:\a\1\s\test\automation\out\search.js:89:9)
      at async Context.<anonymous> (out\areas\search\search.test.js:59:13)

```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=147049&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=6e7e74bd-a473-53b1-acea-ad5f8c1f1ec9&l=73

**Comment by bpasero** [comment]
Merged some duplicates in. The trend for yesterday looks good, not sure if something changed.

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_test/analytics?definitionId=111&contextType=build

![image](https://user-images.githubusercontent.com/900690/146526750-bb95e2b5-edd2-4e19-bbdb-76e381d266b1.png)

Still a few failures though.

**Comment by bpasero** [comment]
Curious if this test runs any better now that we have moved to playwright, maybe we enable it again in May and see?

**Comment by roblourens** [comment]
Sure, I'll try it, what do you mean by "moved to playwright", I thought that is what we used?

**Comment by roblourens** [comment]
Failed twice with the same error
