### ISSUE TITLE
Autofill issue

### ISSUE THREAD

**Issue by mraloo** [microsoft/vscode#137120]
Issue Type: <b>Bug</b>

I have a problem with the autofill feature because when i write a tag in html or any other language it gives suggestions but when i enter it i doesnt complete the autofill.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.53GB free)|
|Process Argv|--crash-reporter-id 56e34477-194b-4180-bd1c-cc61ce2a6490|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscodeintellicode|Vis|1.2.14

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by gjsjohnmurray** [comment]
What is your `editor.acceptSuggestionOnEnter` setting set to?

Does the <kbd>Tab</kbd> key select a suggestion?

**Comment by mraloo** [comment]
with the Tab key its working fine thank you for the help.

**Comment by jrieken** [comment]
> What is your editor.acceptSuggestionOnEnter setting set to?

@mraloo So, do you have this setting configured? Can you try to reproduce when starting like so `code --user-data-dir ~/Desktop/testdata`
