### ISSUE TITLE
Unable to open new terminal after loading a folder into the project workspace for a minute

### ISSUE THREAD

**Issue by logankilpatrick** [microsoft/vscode#137168]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.62.0 (Universal)
- OS Version: macOS 12.0.1 (21A559)

Steps to Reproduce:

It is actually quite difficult for me to re-produce this in a consistent manner. It always happens, but it takes a varying amount of time.

1.  Open a new VS code window
2. Draw a folder into the project pane
3. Create a new terminal session
4. Do something with the terminal
5. Remove the project from the project pane
6. Repeat back to step 2

This is my workflow for grading programming assignments and even single time, after maybe 5-6 assignments, I can no longer open a new terminal session. It is grayed out on the top toolbar for a certain amount of time. And then for example, by the time I finished writing this issue, it was accessible again at the top toolbar. This issue has persisted across different computers and operating systems for me. I will try to do set actual timer next time this takes place.

**Comment by logankilpatrick** [comment]
Just did a quick timing, it was initially unavailable when I loaded the project. I clicked over to safari, and then back, and the "New terminal" button as accessible within 19 seconds.

**Comment by meganrogge** [comment]
could you create a gif? i'm not able to reproduce the issue

**Comment by logankilpatrick** [comment]
https://user-images.githubusercontent.com/35577566/145695781-8f02a2af-1e0a-4df7-a989-3fbe26d22612.mov

@meganrogge here is the first steps:

1. Have a project open in VS Code
2. Have the terminal running (in my case, a django server)
3. Delete the project code outside of VS Code
4. Remove the project from VS Code
5. Kill the server that was running in the terminal

Then, you can open a new folder in the same vs code window and the terminal will not be accessible if you try to create a new one unless you click out of VS code and then back into it.

**Comment by logankilpatrick** [comment]
Uploading Screen Recording 2021-12-11 at 4.15.52 PM.mov…

Here is a video showing this happening ^

**Comment by logankilpatrick** [comment]
I know this seems like a weird set of steps but it is my workflow when grading django projects which is how I came about it.
