### ISSUE TITLE
Intellisense not showing undefined variables in javascript

### ISSUE THREAD

**Issue by gyandeeps** [microsoft/vscode#137103]
Issue Type: <b>Bug</b>

```js
import React from "react";

const TestApplication = ({ showHeader }) => {
    const [selectLocale] = useState("en-US");
    return (
        <>
            <div>{selectLocale}</div>
            <div>{showHeader}</div>
        </>
    );
};

export default TestApplication;
```

![image](https://user-images.githubusercontent.com/5554486/141603809-ed4c7759-6df9-4f35-a44c-c923359e789a.png)

Since I have not imported `useState`, it should put a red squiggly line underneath it but it no longer does that. Last time it worked was version `1.61.0`. It broke with `1.61.1` or `1.61.2`, can't remember forsure. Even tried re-installing vscode but no change.
I am to reproduce this in vscode.dev webpage as well.

Let me know if you guys need more info 

VS Code version: Code 1.62.2 (Universal) (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 5|
|Memory (System)|16.00GB (5.88GB free)|
|Process Argv|--crash-reporter-id d4a72f22-5c38-413b-880b-f0e5e50e3f27|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
copilot|Git|1.7.3733
vscode-docker|ms-|1.17.0
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
material-icon-theme|PKi|4.10.0
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.14
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246cf:30386378

```

</details>

#### Log (Window)

```sh
[2021-11-15 13:19:44.653] [renderer1] [info] Starting extension host with pid 75802.
[2021-11-15 13:19:44.654] [renderer1] [info] [LocalProcessExtensionHost]: IExtensionHostStarter.start() took 23 ms.
[2021-11-15 13:19:45.559] [renderer1] [error] [Extension Host] (node:75802) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
[2021-11-15 13:19:55.033] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
```

**Comment by mjbvz** [comment]
Try enabling semantic checking: https://code.visualstudio.com/docs/nodejs/working-with-javascript#_type-checking-javascript

**Comment by gyandeeps** [comment]
our whole team is confused because we never had the above setting like you mentioned and it used to work before. That's why i logged this issue. So basically for javascript files, vscode applies no smarts unless you apply the setup mentioned above. thats little surprising.
