### ISSUE TITLE
temporary file created at home directory

### ISSUE THREAD

**Issue by RedHeadphone** [microsoft/vscode#137151]
Issue Type: <b>Bug</b>

When I try to format my code without saving it gives me this error
![image](https://user-images.githubusercontent.com/55500003/141667669-ef20695d-0598-442b-b3df-bfa471c47e98.png)

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (3.35GB free)|
|Process Argv|--crash-reporter-id c7fcae81-7537-4392-a7bf-ce9c7981907e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.7.0
vscode-intelephense-client|bme|1.7.1
bracket-pair-colorizer|Coe|1.0.61
doxdocgen|csc|1.3.2
dart-code|Dar|3.28.0
flutter|Dar|3.28.0
es7-react-js-snippets|dsz|3.1.1
prettier-vscode|esb|9.0.0
godot-tools|gee|1.1.2
copilot|Git|1.7.3822
vscode-pull-request-github|Git|0.32.0
better-cpp-syntax|jef|1.15.10
vscode-cloak|joh|0.3.0
dotenv|mik|1.0.1
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.0.0
remove-comments|pli|1.2.2
java|red|1.0.0
cmake|twx|0.0.17
highlight-matching-tag|vin|0.10.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
What formatter extension is this? What language is this?

**Comment by RedHeadphone** [comment]
default python extension (ms-python.python) and provider for formatting is black
