### ISSUE TITLE
Cannot sign in to github and got an undefined error

### ISSUE THREAD

**Issue by Sheey11** [microsoft/vscode#137160]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.2
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Just click `Sign in with Github to use Copilot`

---

Details:
1. Click the `Sign in` and vscode opened a web page, which is correct.
    ![image](https://user-images.githubusercontent.com/13375959/141678901-95b62658-be5a-45f9-abc9-a31ad26744ab.png)
2. In the opened page, click `Continue` and the `vscode-auth.github.com` responds with empty.
    ![image](https://user-images.githubusercontent.com/13375959/141679043-5bcbdd62-21b2-438c-939a-da209a40bb1e.png)
3. After a while, vscode report `Sign in failed: undefined`.
    ![image](https://user-images.githubusercontent.com/13375959/141678831-aa3cd2bc-9e20-4d9a-94ac-2e84d7508e0f.png)

---

log of `Github Authentication` ext:
```
[Info  - 10:28:14.785] Reading sessions from keychain...
[Info  - 10:28:14.805] Getting sessions for all scopes...
[Info  - 10:28:14.805] Getting sessions for all scopes...
[Trace  - 10:28:14.805] Token acquired from secret storage.
[Info  - 10:28:14.805] Got stored sessions!
[Trace  - 10:28:14.805] Read the following session from the keychain with the following scopes: read:user,user:email,repo
[Info  - 10:28:14.810] Got 1 verified sessions.
[Info  - 10:28:14.810] Got 1 sessions for all scopes...
[Info  - 10:28:14.810] Got 1 sessions for all scopes...
[Info  - 10:28:14.996] Getting sessions for read:user,user:email,repo...
[Info  - 10:28:14.998] Got 1 sessions for read:user,repo,user:email...
[Info  - 10:28:15.110] Getting sessions for read:user,user:email,repo...
[Info  - 10:28:15.110] Got 1 sessions for read:user,repo,user:email...
[Info  - 10:28:16.833] Getting sessions for read:user,user:email...
[Info  - 10:28:16.834] Got 0 sessions for read:user,user:email...
[Info  - 10:28:20.272] Getting sessions for read:user...
[Info  - 10:28:20.272] Got 0 sessions for read:user...
[Info  - 10:28:33.738] Getting sessions for read:user...
[Info  - 10:28:33.738] Got 0 sessions for read:user...
[Info  - 10:28:34.777] Logging in for the following scopes: read:user
[Info  - 10:59:32.427] Getting sessions for all scopes...
[Info  - 10:59:32.427] Got 1 sessions for all scopes...
[Info  - 10:59:33.826] Logging in for the following scopes: read:user
[Info  - 11:00:07.883] Getting sessions for all scopes...
[Info  - 11:00:07.883] Got 1 sessions for all scopes...
[Info  - 11:00:08.794] Logging in for the following scopes: read:user
[Info  - 11:00:20.784] Getting sessions for all scopes...
[Info  - 11:00:20.784] Got 1 sessions for all scopes...
[Error  - 11:00:33.849] undefined
```

---

log of `Github Copilot` ext:

(empty)

**Comment by rgoubet** [comment]
Possibly related, it is impossible to push/pull to/from a private repo since 1.62.1 (authentication failed). See [here](https://stackoverflow.com/questions/69979522/fix-for-fatal-authentication-failed-for) for other reports.

**Comment by TylerLeonhardt** [comment]
@rgoubet git authorization doesn't use this flow so that's unrelated.

**Comment by rgoubet** [comment]
OK. Submitted as a [separate issue](https://github.com/microsoft/vscode/issues/137258).

**Comment by TylerLeonhardt** [comment]
@Sheey11 were there any additional webpages displayed between the two you have shown above? Can you share the full url of the error page?

**Comment by Sheey11** [comment]
There might be pages but seems browser not shown, I found something might useful.

I tried this using another browser(Edge InPrivate, without any extension) that is **not signed into github**, after clicking `Continue`, it redirects me to `github.com` to let me sign in. and after that, it redirects me to the following url:
```
https://vscode-auth.github.com/?browser_session_id=random_hash_with_length_64&code=random_hash_with_length_20&state=some_random_string%2FeyJhdXRoU2VydmVyIjoiaHR0cHM6Ly9naXRodWIuY29tIiwiY2FsbGJhY2tVcmkiOiJ2c2NvZGU6Ly92c2NvZGUuZ2l0aHViLWF1dGhlbnRpY2F0aW9uL2RpZC1hdXRoZW50aWNhdGU_d2luZG93aWQ9MSIsInJlc3BvbnNlVHlwZSI6ImNvZGUiLCJzdGF0ZSI6InNvbWUtdXVpZCIsImlkIjoibXktaXAtZ29lcy1oZXJlIn0
```
this probably is where it got the `ERR_EMPTY_RESPONSE`

**Comment by Sheey11** [comment]
I finally managed to sovle this!

the reason I got error is I visit `github.com` through a http proxy.
to solve this, just set a rule letting all `*.github.com` requests using proxy except `vscode-auth.github.com`.
