### ISSUE TITLE
Uninstalling an extension without enabling it should not suggest restart of VSCode

### ISSUE THREAD

**Issue by haricharan** [Microsoft/vscode#13712]
- VSCode Version: 1.6.0
- OS Version: Mac OS X El Capitan

Steps to Reproduce:

1. Install an extension from Marketplace and don't enable the extension or restart VSCode
2. Uninstall the extension
3. Message shows 

> _{Extension}_ was successfully uninstalled. Restart to deactivate it

The issue is that no restart is necessary since the extension was never active. I thought I would edit the` run()` method of `UninstallAction` to check for extension's state before uninstalling and display a different message and submit a Pull Request, but it uses a localized string _postUninstallMessage_. I am not sure how to go about changing it, please advise.

**Comment by joaomoreno** [comment]
This behaviour will change with the work being done by @sandy081 this iteration.

**Comment by haricharan** [comment]
Thanks @joaomoreno  and @sandy081 .
