### ISSUE TITLE
fatal error: 'conio.h' file not found

### ISSUE THREAD

**Issue by gyurmey** [microsoft/vscode#137179]
Been trying to find a way to solve this error for importing certain headers in C in vscode, but it give error. And i am on MacOS. i have install mingw-w64 and also did the installation of vcpkg as suggested by vscode but still the error still there -_- . any suggestion would be great. thank you in advance    "^_^"

**Comment by mikeroyal** [comment]
Hi @gyurmey, conio.h is an old header, almost never used anymore. The same functionality is now in curses.h. So make sure that curses (or ncurses) is installed on your machine, and give it a try.

#include <stdio.h>
#include <stdlib.h>
#include <curses.h>

**Comment by gyurmey** [comment]
> Hi @gyurmey, conio.h is an old header, almost never used anymore. The same functionality is now in curses.h. So make sure that curses (or ncurses) is installed on your machine, and give it a try.
> 
> #include <stdio.h> #include <stdlib.h> #include <curses.h>

Thank you @mikeroyal for answer. i am kind of new veteran in this field. was wondering is there any list where it mentioned  all new header that replace the old one. Now windows.h and MMsystem.h giving same error. -_-
