### ISSUE TITLE
Editor Zoom is not saved

### ISSUE THREAD

**Issue by lakani** [microsoft/vscode#137109]
Issue Type: <b>Bug</b>

each time , i reopen the VSCode , i have to readjust the Editor Zoom level 

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.95GB free)|
|Process Argv|--crash-reporter-id 852413da-17a0-481d-8172-3a09c4b21960|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|1.10.2
vscode-javac|geo|0.2.39
vscode-pull-request-github|Git|0.32.0
gitpod-desktop|git|0.0.27
csharp|ms-|1.23.16
data-workspace-vscode|ms-|0.1.0
mssql|ms-|1.11.0
sql-database-projects-vscode|ms-|0.13.0
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
powershell|ms-|2021.10.2
vscode-spring-boot|Piv|1.28.0
fabric8-analytics|red|0.3.4
java|red|1.0.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.1
javafx-support|shr|0.0.1
vscodeintellicode|Vis|1.2.14
vscode-gradle|vsc|3.8.2
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
vscode-spring-initializr|vsc|0.7.0
Java-extension-pack|wal|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/75397#issuecomment-516457315

**Comment by lakani** [comment]
> See [#75397 (comment)](https://github.com/microsoft/vscode/issues/75397#issuecomment-516457315)

many thanks, it works fine
