### ISSUE TITLE
On Windows, after session contents restored, the current directory is reset to workspace root

### ISSUE THREAD

**Issue by mastazi** [microsoft/vscode#137180]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.63.0-insider (user setup)
Commit: 3bd29c1d6c6ef5b6265614def99b7257b671ae19
Date: 2021-11-12T12:04:20.740Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
- OS Version: Windows 11
- Important: in VS Code Integrated Terminal I am using PowerShell 7.2.0 which I installed from Microsoft Store

Steps to Reproduce:

1. Open a workspace on VS Code
2. In the integrated terminal, cd to a sub directory in the workspace e.g. `cd .\src\`
3. Observe the prompt, it will inform you that you are now located in `src` directory
3. Close VS Code
4. Reopen VS Code
5. Observe the prompt below the message "Session contents restored from "...
6. The prompt is now back in the root of the project, not in `src`
7. Following the same steps on Mac, after restoring the session contents, I am still in `src` 
8. This inconsistency between Windows and Mac behaviour, leads me to believe that there is a bug in the Windows version.

**Comment by meganrogge** [comment]
On Windows, we aren't able to detect when the `cwd` has changed, so we have to use the `initialCwd` on restore of the process.
