### ISSUE TITLE
TypeScript service keeps crashing

### ISSUE THREAD

**Issue by anmpog** [microsoft/vscode#137102]
Issue Type: <b>Bug</b>

I have no idea, I'm not sophisticated enough to help you debug this. It's a core extension for VSCode and it crashes CONSTANTLY. The extension is up to date, so is my version of code. 

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|16.00GB (2.76GB free)|
|Process Argv|. --crash-reporter-id 5a63760e-eedf-48a7-9fed-7a1c8dc533c5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
github-markdown-preview|bie|0.1.0
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-preview-github-styles|bie|0.2.0
markdown-yaml-preamble|bie|0.1.0
npm-intellisense|chr|1.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.6.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
vscode-firefox-debug|fir|2.9.4
beautify|Hoo|1.5.0
lorem-whatever|job|1.0.2
sublime-babel-vscode|jos|0.2.10
graphql-for-vscode|kum|1.15.3
dotenv|mik|1.0.1
vscode-docker|ms-|1.17.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
atom-keybindings|ms-|3.0.9
vsliveshare|ms-|1.0.5090
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
markdown-preview-enhanced|shd|0.6.1
mdx|sil|0.1.0
js-jsx-snippets|sky|11.0.0
lorem-ipsum|Tyr|1.3.0
vscode-icons|vsc|11.7.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
