### ISSUE TITLE
PowerShell Write-Host rendering

### ISSUE THREAD

**Issue by PeterWone** [microsoft/vscode#137198]
Issue Type: <b>Bug</b>

Write a script with multiple uses of Write-Host.  The output of each is rendered as LF without a CR. Same script renders as expected in a Windows Terminal.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8260U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.87GB (8.14GB free)|
|Process Argv|--crash-reporter-id 2468ae4e-d85d-44d9-beb4-ad13f8b9e08e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.4.2
xml|Dot|2.5.1
mdmath|goe|2.7.4
terraform|has|2.16.0
flux|inf|0.6.9
git-graph|mhu|1.30.0
azure-pipelines|ms-|1.194.1
vscode-docker|ms-|1.17.0
vscode-language-pack-fr|MS-|1.62.3
vscode-language-pack-qps-ploc|MS-|1.62.3
blazorwasm-companion|ms-|1.1.0
csharp|ms-|1.23.16
vscode-dotnet-runtime|ms-|1.4.0
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.11
powershell|ms-|2021.10.2
vsliveshare|ms-|1.0.5090
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vscode-print|pdc|0.9.14
autoimport|ste|1.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by PeterWone** [comment]
This is what it looks like in VS Code terminal
![image](https://user-images.githubusercontent.com/5498936/141733887-11500651-cd2b-4caa-b25d-1050ec00a3a1.png)

and this is the same script in Windows Terminal
![image](https://user-images.githubusercontent.com/5498936/141734091-c79886cc-dfae-4bf7-92f1-e3207f2659ac.png)

**Comment by meganrogge** [comment]
can you pls include a gif ?

**Comment by PeterWone** [comment]
Sure but I'm not clear what you need that isn't already illustrated by the two snaps above.

**Comment by meganrogge** [comment]
I'd like to see the whole window and how you have the panel sized
