### ISSUE TITLE
Consumption of CPU resources

### ISSUE THREAD

**Issue by daiyue3** [microsoft/vscode#137189]
Issue Type: <b>Performance Issue</b>

When to start， Consumption of CPU resources

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.75GB free)|
|Process Argv|--crash-reporter-id b723d6e6-d5e4-4793-bed5-b1e33a993525|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    89	 15052	code main
    2	    81	  2524	   window (问题报告程序)
    0	    24	  3400	   crashpad-handler
    0	   178	  5844	   window (index.html - vtrace-org-ui - Visual Studio Code)
    0	    68	  4312	     watcherServiceNSFW
    0	   158	  7944	     extensionHost
    0	   114	  8052	       "C:\Users\dy\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\dy\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=7944
    0	    65	 13016	       c:\Users\dy\.vscode\extensions\ms-mssql.mssql-1.11.0\sqltoolsservice\3.0.0-release.139\Windows\MicrosoftSqlToolsServiceLayer.exe
    0	    10	  9204	         console-window-host (Windows internal process)
    0	    69	 13272	       "C:\Users\dy\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\dy\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=7944
    0	    77	 16004	       "C:\Users\dy\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\dy\.vscode\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js --node-ipc --clientProcessId=7944
    0	    34	 16712	       c:\Users\dy\.vscode\extensions\ms-mssql.mssql-1.11.0\sqltoolsservice\3.0.0-release.139\Windows\SqlToolsResourceProviderService.exe --log-file c:\Users\dy\AppData\Roaming\Code\logs\20211115T094819\exthost1\ms-mssql.mssql\resourceprovider.log --tracing-level Critical
    0	    10	  9088	         console-window-host (Windows internal process)
    2	    87	  6292	   shared-process
    0	    68	  2536	     ptyHost
    0	    39	  7056	   utility
    1	   393	 16780	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - vtrace-org-ui - Visual Studio Code)
|    Folder (vtrace-org-ui): 1117 files
|      File types: png(348) js(235) vue(136) css(47) scss(35) jpg(33) woff(16)
|                  ttf(14) json(5) svg(3)
|      Conf files: package.json(2) settings.json(1) dockerfile(1);
```

</details>
<details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
gitee-code-settings-sync|Ale|0.1.20
path-intellisense|chr|2.4.2
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
gitlens|eam|11.6.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.23
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.0.0
json2ts|Gre|0.0.6
debug-visualizer|hed|2.2.4
path-autocomplete|ion|1.17.1
svn-scm|joh|2.15.0
ts-extension-pack|loi|0.3.0
vscode-docker|ms-|1.17.0
vscode-language-pack-zh-hans|MS-|1.62.3
data-workspace-vscode|ms-|0.1.0
mssql|ms-|1.11.0
sql-database-projects-vscode|ms-|0.13.0
debugger-for-chrome|msj|4.13.0
korofileheader|OBK|4.8.18
vetur|oct|0.35.0
tsimporter|pmn|2.0.1
typescript-hero|rbb|3.0.0
vs-code-prettier-eslint|rve|3.0.4
vscode-hexdump|sle|1.8.1
move-ts|str|1.12.0
sass-indented|syl|1.8.18

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by mikeroyal** [comment]
Hi @daiyue3, I had a similar issue to this and it ended up being caused by an entension I was using at the time. I would look at any extension you installed recently installed or one that maybe out-of-date.

**Comment by gjsjohnmurray** [comment]
The Start Extension Bisect command may be able to help you.
