### ISSUE TITLE
I am trying to open folder in vscode.dev

### ISSUE THREAD

**Issue by movlamovnasir** [microsoft/vscode#137196]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: vscode.dev (15 november 2021)
- OS Version: Kali 2021.3a

Steps to Reproduce:

1. Open vscode.dev website
2. Try to make open folder

**Comment by JacksonKearl** [comment]
\gifPlease

**Comment by CodeCrazy-ywt** [comment]
And what happened?

> 
> 
> 
> 
> 
> 
> 
> Does this issue occur when all extensions are disabled?: Yes/No
> 
> 
> 
> - VS Code Version: vscode.dev (15 november 2021)
> - OS Version: Kali 2021.3a
> 
> Steps to Reproduce:
> 
> 1. Open vscode.dev website
> 2. Try to make open folder 
>
