### ISSUE TITLE
Ability to make integration tests for binary files

### ISSUE THREAD

**Issue by dnicolson** [microsoft/vscode#137171]
As of Visual Studio Code v1.62.2, it doesn't appear to be possible to run integration tests against binary files, this is because the user must click the "Do you want to open it anyway?" link.

Consider the following code:
```
try {
    const document = await vscode.workspace.openTextDocument(vscode.Uri.file("path/to/file"));
    vscode.window.showTextDocument(document);
} catch (err) {
    const msg = err.toString();
    if (msg.includes("File seems to be binary and cannot be opened as text")) {
        await vscode.commands.executeCommand("vscode.open", vscode.Uri.file(uri));
    }
}
```

It is possible to circumvent the error but it still does not appear to be possible to open a binary document.

**Comment by bpasero** [comment]
To clarify, you have a test for opening a binary file in a text editor? Or do you provide a custom editor that allows to open binary files that you want to test?

**Comment by dnicolson** [comment]
Yes, the test is to open a binary file in a text editor (an extension opens the text representation in another tab).

It seems that a custom editor could achieve something similar in a single tab but limited to a web view. In such a case you would need something like https://github.com/microsoft/monaco-editor which seems like a worse tradeoff than having an additional tab.
