### ISSUE TITLE
bracketPairs conflicts with indentation

### ISSUE THREAD

**Issue by tsker** [microsoft/vscode#137190]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:  1.62.2
- OS Version: windows 21h1

Steps to Reproduce:

1. When only editor.guides.highlightActiveIndentation is enabled, the html indentation line in tsx can be activated normally
![Snipaste_2021-11-15_10-34-15](https://user-images.githubusercontent.com/5285733/141713992-46c5f550-1b7c-4a62-9dde-e4368ff34da1.png)

2. But after opening editor.guides.bracketPairs at the same time, the html indentation line in tsx has no response in the active state.
![2](https://user-images.githubusercontent.com/5285733/141714021-2a9f8c51-b3ec-4d73-99f4-7d8af7306641.png)

How can I set it up?

**Comment by hediet** [comment]
This is by design. If there is a bracket pair guide, is has precedence over indent guides.

I'm open to be convinced that giving indent guides precendence over bracket pair guides is better, but I don't think I want to highlight the active indent guide here:

```ts
function test() {
    const x = (1 + 1
        + 1 + 1 + 1); // When placing the cursor in this line, the bracket pair guide should be the active one
}
```

**Comment by SvenSchoene** [comment]
I'm not sure I understand why both features have to be exclusive to each other?

I'm working on a lot of *.vue-files. Here is an example file (not my own; just found it by a quick Google search): https://github.com/gothinkster/vue-realworld-example-app/blob/master/src/components/ArticleMeta.vue

I love the new bracket pair guide feature!

But now when I'm working in the template part at the top, I don't get indent guides anymore -- which is a feature I really rely on a lot. So much so, that I'm disabling the bracket pair guide now.

Can you explain to me where my thinking / understanding of these features is wrong?

**Comment by Kevin-Hamilton** [comment]
BPC2 allowed them both to be active and there are many times, especially in JSX, where this can be very helpful.  

For example in the below screenshot, the bracket scope starts 150 lines earlier and ends 170 lines later.  The <Canvas> component continues on for an additional 50 lines beyond the end of the view.  Being able to follow that highlighted <Canvas> indent guide down to the close of the component makes it much easier to navigate the code.

![image](https://user-images.githubusercontent.com/508865/146602860-ad92ea63-14a6-4835-93d7-946e2282800a.png)
