### ISSUE TITLE
"Problems" ignores tsconfig.json

### ISSUE THREAD

**Issue by sfrooster** [microsoft/vscode#137149]
Issue Type: <b>Bug</b>

I have created a nodejs project which uses typescript. I have a "src" directory which contains my source files and which also contains a "prior-art" directory. In the "prior-art" directory are several .ts files which I'm looking at while I build my new code (under "src", but not in "prior-art"). I have configured my tsconfig to (among other things):
"include": ["./src/**/*.ts"],
"exclude": ["./src/prior-art/*.ts"]

The version of TS in my package.json (4.4.4) matches that of vscode but I, nonethelesss, have this workspace setting (because of this error I'm reporting):
"typescript.tsdk": "/Users/<pii-here>/AppDev/node/tracker/node_modules/typescript/lib"

If I run "npx tsc -p ." from the project root, it correctly reports 7 errors.

However, the "Problems" tab on the terminal pane and the "errors" (problems) count in the bottom-most information bar (the one which also displays cursor position, indentation setting, encoding etc) indicates 7 (as above) plus the errors it finds in any file - even if it's excluded by my tsconfig - I've opened AND viewed (if vscode opens and has a file in a tab, but I haven't yet viewed the tab, then it won't add that files errors to the count until I view it).

If I close the tabs, then the error counts are reduced accordingly.

Shouldn't it be the case that you can view an ignored file without its "problems" being processed and reported?

VS Code version: Code 1.62.2 (Universal) (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.11GB free)|
|Process Argv|--crash-reporter-id 057cb589-ffa1-40bd-8f2d-dacb6e9efd7a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.6.1
EditorConfig|Edi|0.16.4
go|gol|0.29.0
terraform|has|2.16.0
cypher-query-language|jak|1.0.2
dotenv|mik|1.0.1
vscode-docker|ms-|1.17.0
remote-containers|ms-|0.205.2
vscode-direnv|Rub|0.0.2
html-preview-vscode|tht|0.2.5
luna-paint|Tyr|0.10.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by gjsjohnmurray** [comment]
Tip from a related issue, suggesting using negated filter on Problems tab

https://github.com/microsoft/vscode/issues/117732#issuecomment-906718907

Not perfect though, as status bar counts still include problems from open excluded files.

**Comment by mjbvz** [comment]
Can you please share a minimal example project that demonstrates this issue?

**Comment by sfrooster** [comment]
No, I don't have time at the moment to recreate this for you, but all the detail needed is in the description. Create a TS Node project with one valid (no errors) .ts file and one invalid (some error, syntax or otherwise) file. Use "include" in the tsconfig to include them both, then "exclude" to exclude the invalid one.

Running tsc from the command line ("npx tsc -p .") succeeds and reports no errors. However, the "Problems" tab on the internal terminal and the bottom info bar will both report the issues from the excluded files, which they should not.
