### ISSUE TITLE
npm cannot found

### ISSUE THREAD

**Issue by amin1979** [microsoft/vscode#137108]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ npm update express
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.49GB free)|
|Process Argv|--crash-reporter-id 05e6ca42-42b1-4721-8ff4-6fed82805c1c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   104	  3308	code main
    0	   194	  2148	   window (tsconfig.json - ALDES - Visual Studio Code)
    0	   100	  3112	     extensionHost
    0	    71	  8076	       "C:\Users\USER\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=3112
    0	    72	  3616	     watcherServiceNSFW
    0	    25	  4684	   crashpad-handler
    0	    88	  6500	   shared-process
    0	    78	  9248	     ptyHost
    0	    93	  1784	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	  4688	       console-window-host (Windows internal process)
    0	    38	  7084	   utility
    1	    81	  7160	   window (Issue Reporter)
    0	   174	  8640	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (tsconfig.json - ALDES - Visual Studio Code)
|    Folder (ALDES): 116 files
|      File types: ts(37) css(15) html(14) json(7) js(7) browserslistrc(1)
|                  editorconfig(1) firebaserc(1) gitignore(1) sqlite(1)
|      Conf files: package.json(1) tsconfig.json(1);
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.16.4
vscode-firefox-debug|fir|2.9.4
vscode-docker|ms-|1.17.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
debugger-for-chrome|msj|4.13.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by Lemmingh** [comment]
Looks like you were running `npm update express` in PowerShell in the integrated terminal in VS Code?

Then, could you run the following two commands to inspect the environment:

```powershell
Get-Command npm | Select-Object -ExpandProperty Definition

$env:Path -split ';'
```

Besides, did you change any related settings, like `terminal.integrated.env.windows` and `terminal.integrated.profiles.windows`?

**Comment by chrmarti** [comment]
Does this still happen after closing and reopening VS Code? (We have seen the shell env probing time out when the machine is busy.)
