### ISSUE TITLE
Move cursor to final position on leaveSnippet

### ISSUE THREAD

**Issue by W4RH4WK** [microsoft/vscode#137164]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.2
- OS Version: Win 10 21H1

Steps to Reproduce: 

1. Insert a snippet that has multiple place holders and a final position (`$0`)
2. Invoke `leaveSnippet` (default `Shift + Esc`)

Notice that the cursor remains at the current position.

I think the cursor should move to the final position as leaveSnippet would be typically used when no more place holders need to be changed and one would like to move on.

**Comment by jrieken** [comment]
The `leaveSnippet` command is to be understood as cancel/abort snippet mode, but there is also the `acceptSnippet` command which does what you want.
