### ISSUE TITLE
Git push dont open credential console

### ISSUE THREAD

**Issue by SER61O** [microsoft/vscode#137133]
Issue Type: <b>Performance Issue</b>

I cant do git push origin master" because :
remote: No anonymous write access.
fatal: Authentication failed for 'http

And visual code dont ask me to insert my credentials on any upper panel

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by kinghat** [comment]
duplicate: https://github.com/microsoft/vscode/issues/137063
