### ISSUE TITLE
Launch.json prop default value as URL?

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#13716]
vscode-chrome-debug sets the default value of 'url' as "http://mysite.com/index.html", but when I use autocomplete in the launch.json to get the default value, it shows up as `"url": "//mysite.com/index.html"`. Tried debugging a little but all I see is that it's loaded properly into the JSON schema. Don't know where it goes from there. Any ideas @weinand or @isidorn?

**Comment by isidorn** [comment]
This is done by @aeschli json schema logic. If you are properly contributing the default value it seems like there is an issue in JSON that the 'http:' gets removed
