### ISSUE TITLE
Extension pty terminals may not receive early respect dimension overrides events

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#137155]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=142815&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=dccbe8b6-2cf2-56ce-ca99-720e7791a9c0&l=423

```
1) vscode API - terminal
       Terminal
         Extension pty terminals
           should respect dimension overrides:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/1/s/extensions/vscode-api-tests/out/singlefolder-tests/terminal.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

```

**Comment by Tyriar** [comment]
Failed on remote electron integration tests/Linux.

**Comment by bpasero** [comment]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=143229&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&s=a56e7651-4213-56af-9488-c25fe636c10c&t=88928627-a399-54e7-2f20-a03c2cf00dcd&l=430

**Comment by Tyriar** [comment]
Failed in remote again, will disable for remote only and need to repro locally.

**Comment by Tyriar** [comment]
Just ran 15 times locally on mac and it passed all of them

**Comment by Tyriar** [comment]
Tried many more times and didn't happen, also tried injecting latency into exthost <-> renderer comms and that didn't make a difference. Pushing a tweak to the test which could be why it failed and also some logs which will help diagnose incase it doesn't

**Comment by Tyriar** [comment]
Saw it again yesterday 😭 

https://github.com/microsoft/vscode/runs/4243708929?check_suite_focus=true

This time it failed in local as well, will disable again.

Extra logs:

```
      Extension pty terminals
        √ should fire onDidOpenTerminal and onDidCloseTerminal
listening for window.onDidChangeTerminalDimensions, current dimensions = undefinedxundefined
rejected promise not handled within 1 second: undefined
        1) should respect dimension overrides
```

**Comment by Tyriar** [comment]
The above logs show that this is actually a bug, no onDidChangeTerminalDimensions events are being fired sometimes which means the terminal likely remains undefined x undefined as well.

**Comment by Tyriar** [comment]
Struggling to figure this out, will keep the test skipped and defer this issue as it's not that important of an issue.
