### ISSUE TITLE
`Toggle Terminal` hotkey will show `Unbound` when click out side of vscode

### ISSUE THREAD

**Issue by Megrax** [microsoft/vscode#137192]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- OS Version:

Version: 1.62.2
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:59:05.913Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Steps to Reproduce:

1. launch vscode, close all open files and a default page with some hotkey hint will display
2. click outside of vscode, the `Toggle Terminal` hotkey will be shown as `Unbound`

![Kapture 2021-11-15 at 11 31 11](https://user-images.githubusercontent.com/56376387/141718268-cbab4115-45f3-41d4-8363-ea167e576440.gif)

**Comment by yume-chan** [comment]
Related to #28088
