### ISSUE TITLE
Word Wrap Bug is not disabled when setting is specified as disabled

### ISSUE THREAD

**Issue by apacheli** [microsoft/vscode#137148]
Version: 1.63.0-insider (user setup)
Commit: 3bd29c1d6c6ef5b6265614def99b7257b671ae19
Date: 2021-11-12T12:04:20.740Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

```json
    "diffEditor.wordWrap": "off",
    "editor.accessibilitySupport": "off",
    "editor.wordWrapColumn": 1,
    "editor.wrappingIndent": "none"
```
    
    
![image](https://user-images.githubusercontent.com/43933794/141666105-252c066a-9291-44bc-8ad2-864700e0a2dc.png)

The setting is disabled. Why is word wrapping still there? I don't think the answer should be *too* complicated, but it seems like 432,000 people also face the same issue according to this StackOverflow question: https://stackoverflow.com/questions/31025502/how-can-i-switch-word-wrap-on-and-off-in-visual-studio-code which also does not solve my issue.

While I'm using Insiders, it should not make any difference as I also have this exact same issue with production version.

**Comment by gjsjohnmurray** [comment]
The first setting you reported your value of is named **diff**Editor. wordWrap

What have you set for **editor**. wordwrap?

**Comment by apacheli** [comment]
> The first setting you reported your value of is named **diff**Editor. wordWrap
> 
> What have you set for **editor**. wordWrap?

Hey gjsjohnmurray,

Toggling `editor.wordWrap` to `on` and `off` has not made a difference. However, all options seem to be ignored except `editor.accessibilitySupport`, which correctly disabled word wrapping for me.

In other words:

This **DOES NOT** disable word wrap:

```json
    "diffEditor.ignoreTrimWhitespace": false,
    "editor.accessibilitySupport": "off",
    "editor.wordWrap": "off",
    "editor.wrappingIndent": "none",
    "editor.wordWrapColumn": 1,
    "diffEditor.wordWrap": "off"
```

This **DOES** disable word wrap:

```json
    "editor.accessibilitySupport": "on",
    "editor.wordWrap": "on",
    "editor.wrappingIndent": "same",
    "editor.wordWrapColumn": 1,
    "diffEditor.wordWrap": "on"
```

All other options are ignored and only `editor.accessibilitySupport"` seems to work:

```json
    "editor.accessibilitySupport": "on"
```

This seems like an oversight, but this current workaround should suffice for now. I do not think my issue should be closed, unless this behavior of ignoring all other options is intentional.

**Comment by alexdima** [comment]
@apacheli Are you opening files which consist mostly (>50%) of very long lines? Could you please share an example file that reproduces the problem? We have a code-path that tries to guess that you are opening e.g. a minified JS file and then enables wrapping automatically.
