### ISSUE TITLE
Notifica infinita

### ISSUE THREAD

**Issue by aron1997** [microsoft/vscode#137107]
Issue Type: <b>Bug</b>

Esce una notifica a schermo ripetitiva in cui si dice che "Non è stato possibile avviare il processo del terminale. Il percorso <path> dell'eseguibile della shell non esiste". Io ho solo aperto Visual Studio Code, ma esce questa notifica fastidiosa che non posso elimianre

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (1.54GB free)|
|Process Argv|C:\\Users\\Aron Raffaele\\Desktop\\gruppo11.lisp --crash-reporter-id ed34ff5f-5f18-4b4e-8207-295e21240638|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
commonlisp-vscode|ail|0.3.2
debugger-for-mainframe|Bro|1.5.1
batch-rename-extension|Jan|0.0.4
Lisp|mat|0.1.11
vscode-language-pack-it|MS-|1.62.3
common-lisp|qin|0.0.2
java|red|1.0.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
ZwLisp|Zws|1.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by CodeCrazy-ywt** [comment]
Google translate: A repetitive screen notification comes out saying "The terminal process could not be started. The path to the shell executable does not exist." I have only opened Visual Studio Code, but this annoying notification comes out that I cannot eliminate

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
