### ISSUE TITLE
PHP Language Basics is missing in remote

### ISSUE THREAD

**Issue by pelayog** [microsoft/vscode#137117]
Issue Type: <b>Bug</b>

Steps to reproduce the problem:

1.- Connect to a server using Remote SSH
  (*Expecting: PHP language server features as usual.*)
2.- PHP language server features are missing.
3.- Check Extensions finding by `@builtin php`
`PHP Language Basics` is disabled and shows the next message:
```
This extension is disabled in this workspace because it is defined to run in the Remote Extension Host. Please install the extension in 'SSH: subdomain.example.com' to enable.
```
However, since is a built-in extension, I can't perform any of the extension-related commands (install, uninstall, reinstall...).

Happens since last week. Sometimes, I can recover PHP Language Basics if there is an update from VSC. In that case, I restart to update and the extension starts to working again in remotes.

On local machine, extensions is running normally.

I've tried to remove `.vscode` server files from remote  and connect again but it can't help.

Also tried `Developer: reload with extensions disabled` and `Developer: Restart Extension Host`, same result. 

Remote servers are Linux running CentOS 7.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.42.2.el7.x86_64
Remote OS version: Linux x64 3.10.0-514.21.1.el7.x86_64

**Comment by roblourens** [comment]
That extension basically just provides syntax highlighting, not language server features. Is the PHP Language Features extension enabled? This is what it should look like:

![image](https://user-images.githubusercontent.com/323878/141876592-d0769ad4-cb4a-459f-838e-a009f2f32a13.png)

**Comment by pelayog** [comment]
Ey, @roblourens; thanks for your reply.

Yes, it is the code highlighting that I am missing in remote. In my case, the language server features are provided by `Intellephense`, so the `PHP Language Features` extension is disabled (as stated in [the Intelephense docs](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client)).

In [this related issue](https://github.com/microsoft/vscode-remote-release/issues/5856), @daiyam has found that an extension that disables VSC built-in snippets causes the same unexpected behavior.

I suspect it's the same problem: in my case, I've disabled Language Features manually; in his case, via an extension. Both can't see code highlighting when connected to a remote server.

**Comment by roblourens** [comment]
I can't repro, but it sounds like the behavior is inconsistent anyway. Any idea @sandy081?

**Comment by sandy081** [comment]
Can you please check in your settings files (all -user/remote/workspace) if you have configured following setting`remote.extensionKind`

**Comment by pelayog** [comment]
Yes, it's present in local's `defaultSettings.json`:

```JSON
	"remote.extensionKind": {
		"pub.name": [
			"ui"
		]
```

But not in the remote `settings.json` neither in the local user's one.

**Comment by sandy081** [comment]
I cannot reproduce too. 

@pelayog Can you please try following:

- Install `ms-vscode-remote.remote-containers` extension 
- Try a PHP dev container sample by running the command `Remote Container: Try a Dev Container Sample...`

Can you please let us know if the PHP extension is working?
