### ISSUE TITLE
Windows 11 screen sizing

### ISSUE THREAD

**Issue by richtera** [microsoft/vscode#137233]
Issue Type: <b>Bug</b>

Visual Studio Code works very well under Windows 11, but I have noticed, that sometimes it gets the wrong size after the computer wakes up or the monitors get unplugged. In that case the top menu is no longer reachable and the bottom of the window extends on top of the toolbar. Obviously I can't really tell whether this is a window manager problem in windows 11 or a window positioning problem inside of Visual Studio Code.
Please advise.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (35.03GB free)|
|Process Argv|--crash-reporter-id db2c49a0-c178-4fe7-b9ea-930397e91764|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (4 x 3600)|
|Memory (System)|31.36GB (15.51GB free)|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
quokkasyntax|aid|1.2.4
project-manager|ale|12.4.0
language-hugo-vscode|bud|1.3.1
bracket-pair-colorizer-2|Coe|0.2.1
vscode-edge-devtools|ms-|1.4.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
fish-vscode|sky|0.2.1
vscode-nvm|abu|0.0.1
project-manager|ale|12.4.0
github-markdown-preview|bie|0.1.0
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-preview-github-styles|bie|0.2.0
markdown-yaml-preamble|bie|0.1.0
gitignore|cod|0.7.0
vscode-eslint|dba|2.2.2
git-extension-pack|don|0.1.3
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|11.6.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
vscode-jest-runner|fir|0.4.47
go|gol|0.29.0
go-nightly|gol|2021.11.602
gc-excelviewer|Gra|3.0.44
vscode-docker|ms-|1.17.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
cpptools|ms-|1.7.1
angular-console|nrw|17.12.3
prettier-vscode|pre|3.14.1
markdown-preview-enhanced|shd|0.6.1
vsfire|tob|1.4.1
pdf|tom|1.1.0
har-viewer|unc|0.0.1
docker|vsc|1.0.0
yaml|vsc|1.0.0
clang-format|xav|1.9.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by richtera** [comment]
I agree, it happened several times but I can't readily repeat it. The worst part was that I was unable to quite code to restart it, because the top of the display was off screen but Alt-F4 did the trick. It happened to me about 3 or 4 times but not each time the device woke up from sleep. I will add screenshots when I get them. I was hoping it would be something someone else also saw.

**Comment by nostrilia** [comment]
It happened to me too several times (but also with other applications).
No need to close via Alt-F4 and reopen.

Just press Alt-Space to open standard window menu:
![image](https://user-images.githubusercontent.com/47560932/142592363-0a0d1c3e-e366-4b42-9f42-c6a07cf1393e.png)
Does not matter if it is off the screen.
Press M, then use arrows to move window. Press Enter.

**Comment by richtera** [comment]
I did try that of course but only minimize was available. The other menu items were dimmed so windows though the window was properly maximized but the position was off

**Comment by richtera** [comment]
Ok this seems to be a windows problem and not a code problem. It happens to all maximized apps. After some random time or connect/disconnect the maximum window size overlaps the tray at the bottom of the screen. Disconnecting and reconnecting the monitors makes windows reconsider the size and work correct (I have a KVM so I just switch to another computer and back) but it's probably not a solution for a normal user.
