### ISSUE TITLE
Excute above cells

### ISSUE THREAD

**Issue by mohamadhussien** [microsoft/vscode#137245]
Issue Type: <b>Bug</b>

When right click on a jupyter notebook cell and chossing excute above cells nothing happens.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (3.46GB free)|
|Process Argv|--crash-reporter-id 29c6b1ae-f44f-403e-87e2-594eea2b0a4a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.33.0
armview|ben|0.4.5
codespaces|Git|1.3.6
copilot|Git|1.7.3822
remotehub|Git|0.18.0
vscode-pull-request-github|Git|0.32.0
go|gol|0.29.0
cloudcode|goo|1.16.0
mongodb-vscode|mon|0.6.14
azure-pipelines|ms-|1.194.1
vscode-azureappservice|ms-|0.23.0
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
vscode-azurevirtualmachines|ms-|0.4.1
vscode-bicep|ms-|0.4.1008
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.17.0
vscode-dotnet-runtime|ms-|1.4.0
data-workspace-vscode|ms-|0.1.0
mssql|ms-|1.11.0
sql-database-projects-vscode|ms-|0.13.0
gather|ms-|2021.9.1
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
vscode-ai|ms-|0.6.27
vscode-ai-remote|ms-|0.5.0
remote-containers|ms-|0.205.2
azure-account|ms-|0.9.11
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.2.1
vsliveshare|ms-|1.0.5090
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
azurerm-vscode-tools|msa|0.15.4
vscode-sanddance|msr|3.3.0
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0
java|red|1.0.0
scala|sca|0.5.5
scala-snippets|sca|0.1.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
vscode-aws-console|vsc|0.0.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by roblourens** [comment]
Fixed in #136766
