### ISSUE TITLE
QuickPick: filter not reset on value set programmatically

### ISSUE THREAD

**Issue by stevenguh** [microsoft/vscode#137279]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.2
- OS Version: Darwin x64 20.6.0

Steps to Reproduce:

1. Setup a QuickPick as follows
```typescript
const qp = window.createQuickPick();
qp.items = [
	{ label: "This is first" },
	{ label: "This is second" },
];
const clearIcon = { iconPath: new ThemeIcon('trash') };
qp.buttons = [clearIcon];
const disposables = [
	qp.onDidTriggerButton((button) => {
		if (button === clearIcon) {
			qp.value = "";
		}
	}),
	qp
];
qp.onDidHide(() => {
	for (const d of disposables) {
		d.dispose();
	}
});
qp.show();
```

2. Run the code above
3. When the quickpick is shown, type `first`
4. The menu should only show one item because of the filter word `first`
5. Click the trash button to clear the value programmatically
6.

ACTUAL: The filter doesn't update, and only show one menu items
EXPECTED: The filter updates, and show two menu items

https://user-images.githubusercontent.com/3455662/141921763-0521887c-ef66-4280-8db4-c1b5cd7b2e17.mov

**Comment by TylerLeonhardt** [comment]
Nice catch!

**Comment by TylerLeonhardt** [comment]
I need to revert the change because it turns out this behavior was relied on in the Command Palette. Looking into this further.

**Comment by TylerLeonhardt** [comment]
I may need to revert this change for a different reason... ^

**Comment by TylerLeonhardt** [comment]
Unfortunately, I needed to revert the change as I didn't have enough time to investigate before my vacation next week. This will be on my radar for December.
