### ISSUE TITLE
Not being able to git push in the Integrated terminal in Ubuntu after latest VSCode update

### ISSUE THREAD

**Issue by arjuna-dev** [microsoft/vscode#137206]
Issue Type: <b>Bug</b>

Not being able to git push in the Integrated terminal in Ubuntu after latest VSCode update.

Another user reported the same behaviour in a StackOverflow: https://stackoverflow.com/a/69953323/8408861

Git push from other Linux terminals is possible though.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:51:30.084Z)
OS version: Linux x64 5.11.0-40-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|14.88GB (5.32GB free)|
|Process Argv|--unity-launch --crash-reporter-id 4dae3895-17fa-4e74-a5f0-0777e99440f1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|budgie-desktop|
|XDG_CURRENT_DESKTOP|Budgie:GNOME|
|XDG_SESSION_DESKTOP|budgie-desktop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
vscode-django|bat|1.6.0
django|big|1.0.2
htmltagwrap|bra|0.0.7
vscode-tailwindcss|bra|0.7.2
notes|can|1.1.0
node-snippets|chr|1.3.3
glsl-canvas|cir|0.2.14
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
code-runner|for|0.11.6
go|gol|0.29.0
vscode-drawio|hed|1.6.2
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
vscode-power-mode|hoo|2.2.0
vue|jcb|0.1.5
vscode-styled-components|jpo|1.6.6
theme-by-language|jsa|1.2.0
cortex-debug|mar|0.4.7
vscode-wrap-console-log|mid|1.7.2
python|ms-|2021.11.1422169775
cpptools|ms-|1.7.1
vetur|oct|0.35.0
platformio-ide|pla|2.4.0
LiveServer|rit|5.6.1
mongo-snippets-for-node-js|roe|1.3.10
arduino-snippets|ron|1.0.2
markdown-preview-enhanced|shd|0.6.1
open-in-browser|tec|2.0.0
vscode-djaneiro|the|1.4.2
rf-intellisense|Tom|2.8.0
simple-rst|tro|1.5.0
expresssnippet|vla|0.2.4
vscode-icons|vsc|11.7.0
JavaScriptSnippets|xab|1.8.0
vscode-preview-server|yui|1.3.0
linkerscript|Zix|1.0.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by deepak1556** [comment]
Thanks @gitbrent 

Merging to https://github.com/microsoft/vscode/issues/137183
