### ISSUE TITLE
The foreground here is very dark, hope we can allow us to modify it ourselves

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#137270]
Hello, great teacher!
        In the long-term use of vscode, I found that the number of method parameter overloads has a dark foreground color, and my eyes will be tired if I see it for a long time. I ask the teacher to allow us to modify the foreground color to our own suitable foreground color. It will be great for people who have been coding for a long time! Hope this problem can get your support and help from the teacher to improve it in the next milestone. Thank you very much!
![方法参数前景色很黑暗](https://user-images.githubusercontent.com/54253524/141884081-116eed92-4eb3-480b-9454-d648d4f1e98a.png)

**Comment by Sheey11** [comment]
I would advise you to change to light theme, `Ayu Light` is what I recommand.

![image](https://user-images.githubusercontent.com/13375959/141889839-53fa655f-6275-4175-ac54-72611e87bc92.png)

**Comment by zhouxinghong** [comment]
> I would advise you to switch to light theme, `Ayu Light` is what I recommand.
> 
> ![image](https://user-images.githubusercontent.com/13375959/141889839-53fa655f-6275-4175-ac54-72611e87bc92.png)

Thanks for your answer! But looking at the light theme for a long time will make the eyes more tired. These are one of the UI elements that are used very, very frequently. Improving it will be very friendly to most people.
From the picture you provided, it can be seen that even in the light theme, it is also very dark, and it takes a very difficult time to recognize it.

**Comment by luukkoe** [comment]
Hi! I might be able to take a stab at this if someone could direct me to the code location where the color is specified.

**Comment by zhouxinghong** [comment]
If you want to improve the situation more perfect, it is recommended to add the following oval background color settings, which will be very beautiful and modern, and can bring people a very pleasant coding experience more in line with ergonomics.
![2021-11-17_背景颜色](https://user-images.githubusercontent.com/54253524/142088169-ba534089-fa79-4b98-a946-51a41f544cff.png)

**Comment by mjbvz** [comment]
The contrast on the numbers needs be be increased. Here's the relevant css:

https://github.com/microsoft/vscode/blob/f1291d0456240ac2d22eb13edba1654d4ec49a94/src/vs/editor/contrib/parameterHints/parameterHints.css#L95

**Comment by rghdrizzle** [comment]
> 
> 
> Hello, great teacher! In the long-term use of vscode, I found that the number of method parameter overloads has a dark foreground color, and my eyes will be tired if I see it for a long time. I ask the teacher to allow us to modify the foreground color to our own suitable foreground color. It will be great for people who have been coding for a long time! Hope this problem can get your support and help from the teacher to improve it in the next milestone. Thank you very much! ![方法参数前景色很黑暗](https://user-images.githubusercontent.com/54253524/141884081-116eed92-4eb3-480b-9454-d648d4f1e98a.png)

I would recommend these themes below :
1. dracula official 
2. one dark pro 
3. winter is coming (dark black)
Choose the one which is comfortable for you after trying with all the three 
hope i was helpful

**Comment by zhouxinghong** [comment]
> > Hello, great teacher! In the long-term use of vscode, I found that the number of method parameter overloads has a dark foreground color, and my eyes will be tired if I see it for a long time. I ask the teacher to allow us to modify the foreground color to our own suitable foreground color. It will be great for people who have been coding for a long time! Hope this problem can get your support and help from the teacher to improve it in the next milestone. Thank you very much! ![方法参数前景色很黑暗](https://user-images.githubusercontent.com/54253524/141884081-116eed92-4eb3-480b-9454-d648d4f1e98a.png)
> 
> I would recommend these themes below :
> 
> 1. dracula official
> 2. one dark pro
> 3. winter is coming (dark black)
>    Choose the one which is comfortable for you after trying with all the three
>    hope i was helpful

Thank you for your reply! I tried these topics a long time ago and can't solve this problem.

**Comment by zhouxinghong** [comment]
> The contrast on the numbers needs to be increased. Here's the relevant css:
> 
> https://github.com/microsoft/vscode/blob/f1291d0456240ac2d22eb13edba1654d4ec49a94/src/vs/editor/contrib/parameterHints/parameterHints.css#L95

Hello, teacher! Is it convenient to modify the style of this css?

**Comment by zhouxinghong** [comment]
> The contrast on the numbers needs to be increased. Here's the relevant css:
> 
> https://github.com/microsoft/vscode/blob/f1291d0456240ac2d22eb13edba1654d4ec49a94/src/vs/editor/contrib/parameterHints/parameterHints.css#L95

Hello, teacher!
       This problem is really important to me because my eyesight is not very good, so I hope you can accept it and help solve it in the next milestone. After solving this problem, I will no longer report UI-related problems in the future. I really hope you can help solve it, thank you very much!

**Comment by zhouxinghong** [comment]
Hello, teacher!
This problem is really important to me, because my eyesight is not very good, so I hope you can accept it and help solve it in the next milestone. After solving this problem, I will no longer report UI-related problems in the future. I really hope you can help solve it, thank you very much for your hard work and efforts! 😜👍👍👍👍👍

**Comment by Sheey11** [comment]
you can just modify the css just like @mjbvz said. go to `VSCode\resources\app\out\vs\workbench\workbench.desktop.main.css`, then search for `.monaco-editor .parameter-hints-widget .overloads`, find `opacity:.5` next to it, and change it to `opacity:1`.

**Comment by Shubham29012001** [comment]
If possible you can switch to the Cobalt theme. I am using it from long time and it's too good.

**Comment by zhouxinghong** [comment]
thanks for your help! I tried the solution you gave, but a similar solution could not solve my problem.

**Comment by zhouxinghong** [comment]
> 

Dear teacher! Can you solve this problem in the next milestone?

**Comment by zhouxinghong** [comment]
> The contrast on the numbers needs to be increased. Here's the relevant css:
> 
> https://github.com/microsoft/vscode/blob/f1291d0456240ac2d22eb13edba1654d4ec49a94/src/vs/editor/contrib/parameterHints/parameterHints.css#L95

Dear teacher! Can you solve this problem in the next milestone?

**Comment by najmieh** [comment]
I edited this issue. I appreciate any feedback on the PR

**Comment by zhouxinghong** [comment]
Hello, teacher!
The new year has come, I wish the teachers a happy new year! ! !
In the new year, I hope that the teacher can help solve this problem in time, thank you very much!

**Comment by zhouxinghong** [comment]
> The contrast on the numbers needs to be increased. Here's the relevant css:
> 
> https://github.com/microsoft/vscode/blob/f1291d0456240ac2d22eb13edba1654d4ec49a94/src/vs/editor/contrib/parameterHints/parameterHints.css#L95

Hello, teacher!
        VSCode is a great project that gives users the greatest autonomy from the very beginning, allowing users to personalize configurations according to their own habits, so it can fully surpass the long-born jetbrion series in just 5 years. The most important reason is that VSCode's open source thinking and allowing users to customize and configure VSCode development methods to the greatest extent can achieve today's achievements. I hope VSCode can continue to develop this way of thinking and development, focusing on every reasonable request of users and need. Thank you here!
                                                             vscode contributors
                                                             20220126

**Comment by zhouxinghong** [comment]
Hello, teacher!
        VSCode is a great project that gives users the greatest autonomy from the very beginning, allowing users to personalize configurations according to their own habits, so it can fully surpass the long-born jetbrion series in just 5 years. The most important reason is that VSCode's open source thinking and allowing users to customize and configure VSCode development methods to the greatest extent can achieve today's achievements. I hope VSCode can continue to develop this way of thinking and development, focusing on every reasonable request of users and need. Thank you here!
                                                             vscode contributors
                                                             20220126

**Comment by zhouxinghong** [comment]
Thank you very much!

**Comment by Balastrong** [comment]
Hey! I also think that text should be more readable.

I created a PR to fix that: #141828
