### ISSUE TITLE
Scroll bar mouse down color has changed in Insiders

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#137238]
Version: 1.63.0-insider (user setup)
Commit: 035eaab2cb31798c6ae90a35928c62117cb52fcd
Date: 2021-11-15T05:17:52.250Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by Tyriar** [comment]
![recording (8)](https://user-images.githubusercontent.com/2193314/141814925-883c2be5-99b0-4d1b-892c-43ea1c261669.gif)

**Comment by misolori** [comment]
Weird, I am not able to reproduce. Can you try with a fresh usr data directory?

**Comment by misolori** [comment]
@alexdima might also be related to https://github.com/microsoft/vscode/issues/137337

**Comment by alexdima** [comment]
@Tyriar I am also unable to reproduce in latest Insiders or when running from source. Is it possible that you have customized the color `"scrollbarSlider.activeBackground"`?

**Comment by Tyriar** [comment]
Doesn't happen on latest build, pretty sure I didn't have that set 🤷

**Comment by alexdima** [comment]
cc @aeschli @bpasero if you're aware of any recent changes you might have done that could impact this

**Comment by alexdima** [comment]
@Tyriar could have been https://github.com/microsoft/vscode/issues/137337
