### ISSUE TITLE
Visual Studio Code Error on MacBook Pro 2021 (M1 Pro chipset)

### ISSUE THREAD

**Issue by sanhitmehta** [microsoft/vscode#137295]
On running any code, I run into an error with the following message:

"/Users/sanhit711/Desktop/CBasic/Codes2/" && gcc tempCodeRunnerFile.c -o tempCodeRunnerFile && "/Users/sanhit711/Desktop/CBasic/Codes2/"tempCodeRunnerFile
zsh: killed     "/Users/sanhit711/Desktop/CBasic/Codes2/"tempCodeRunnerFile

Can someone let me know what the issue seems to be?

**Comment by jrieken** [comment]
Seems unrelated to VSCode
