### ISSUE TITLE
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)src\index.tsx (120:13)

### ISSUE THREAD

**Issue by luismendes070** [microsoft/vscode#137277]
Issue Type: <b>Bug</b>

[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)src\index.tsx (120:13)

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  J1800  @ 2.41GHz (2 x 2417)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.31GB free)|
|Process Argv|C:\\Users\\Luis\\Documents\\GitHub\\poligonosapp --crash-reporter-id d129a162-225f-4e00-8ef3-621459994f59|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.9.1
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.0.0
vscode-firefox-debug|fir|2.9.5
vscode-pull-request-github|Git|0.32.0
vscode-android-webview-debug|mpo|1.2.0
vscode-docker|ms-|1.18.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
vscode-typescript-next|ms-|4.6.20211115
vscode-yaml|red|1.2.0
browserslist|web|1.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

You need to provide more info about steps how to reproduce this error. Minimal code repro, project config etc.

Os it reproducible with `tcs`?
