### ISSUE TITLE
[Feature Request] Enable to open a file in string path

### ISSUE THREAD

**Issue by ithieund** [Microsoft/vscode#13720]
It's better if we can open a file by right-clicking in a string path in code.
Ex: include('path/path/file.php');
Just right click in the string 'path/path/file.php' and select Open File command.

This feature is supported in Nusphere PHP ED.
Thanks.

**Comment by bpasero** [comment]
@ithieund it should work by Ctrl+clicking on such imports and links. But this needs to be implemented by the PHP extension to work properly so I suggest you file this issue to them.
