### ISSUE TITLE
Configurable Middle-click paste in terminal on non-Linux

### ISSUE THREAD

**Issue by marvinthepa** [microsoft/vscode#137218]
It would be nice to be able to configure middle-click-paste on Mac and Windows, too. #136633 was rejected for this, but after #3130 is implemented (hopefully soon), this can be revisited by providing an action that can be mapped to middle click in terminal.

**Comment by Tyriar** [comment]
Let's track this in https://github.com/microsoft/vscode/issues/3130, note that some work has happened there and it's looking like we'll be able to support your ask in a mousebindings.json file or similar.
