### ISSUE TITLE
Jumpy Scroll

### ISSUE THREAD

**Issue by Chryogenic** [Microsoft/vscode#13726]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: donjayamanne.githistory-0.1.0, ms-vscode.PowerShell-0.7.2, xaver.clang-format-0.11.0

Steps to Reproduce:

1. Scrolling up and down using laptop scroll gesture. I have noticed it in the last 2 updates.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/13612
