### ISSUE TITLE
VSCode Extension: Shell command written in the extension code failed everytime I restarted my computer.

### ISSUE THREAD

**Issue by WanWenjia** [microsoft/vscode#137291]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.2
- OS Version: macOS Big Sur 11.3.1

Steps to Reproduce:

1. Install FlapBundleProducer extension in the extension marketplace and restart computer
2. Run the extension and VSCode shows "Resolving Shell Environment fails"
3. Then the output console will show Command Failed: which dart. "which dart" is a shell command i want to run in my extension.
![image](https://user-images.githubusercontent.com/93123708/141960714-bd81c83d-d2c9-4e7e-aab5-c08f6a509b36.png)

But after I quit VSCode with Command +  Q（if just close the window or use restart extension host, error still exists）and restart the VSCode, everything works fine. I wonder this error may be something related to the shell resolving. But why everything is good after quit? Could you please help to figure out? Thanks a lot!!

**Comment by sandy081** [comment]
I would recommend to file the issue against the FlapBundleProducer extension first to get initial analysis if the issue is in the extension or not.
