### ISSUE TITLE
"file -> help -> report issue" not working.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#137209]
report an issue feature is not working 

go to file -> help -> report issue

current output: no popup is visible
expected: report issue popup should be visible.

can be reproduced in latest insiders build with and without extensions.
VSCODE details:
Version: 1.63.0-insider (user setup)
Commit: 035eaab2cb31798c6ae90a35928c62117cb52fcd
Date: 2021-11-15T05:17:52.250Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by sanket-bhalerao** [comment]
there is a weird issue with my VSCode.
This is a work system so I am always connected on a VPN.
After a while, a few things stop working in my VSCode (no notification of any issue or network loss.). if I go to the extension panel, I just see the progress indicator, but no extensions show up in the panel.
The issue raised here `" file -> help -> report an issue" not working` happened during such episode.

i will provide the gif once I face this issue again. meanwhile is there any logs i can provide while this issue reoccurs?

**Comment by sanket-bhalerao** [comment]
there is a weird issue with my VSCode.
This is a work system so I am always connected on a VPN.
After a while, a few things stop working (no notification of any issue or network loss.). if I go to the extension panel, I just see the progress indicator, but no extensions show up in the panel.
The issue raised here `" file -> help -> report an issue" not working` happened during such episode.

**Comment by sanket-bhalerao** [comment]
GIF showing the extension panel with spinner and no extensions being loaded, and the report issue popup not opening.

![recording](https://user-images.githubusercontent.com/9264813/142419592-d80bda96-2262-474a-b103-d7e428e59442.gif)

please let me know if i can provide any additional logs for this.

**Comment by TylerLeonhardt** [comment]
Sometimes the issue reporter can get rendered _behind_ the editor. Can you confirm that this isn't the case?

**Comment by sanket-bhalerao** [comment]
@TylerLeonhardt no it is not rendered at all I checked it a few times.

**Comment by TylerLeonhardt** [comment]
@sanket-bhalerao can you share what is in your user settings?
