### ISSUE TITLE
Unable to collapse sidebar by default

### ISSUE THREAD

**Issue by CrendKing** [Microsoft/vscode#13724]
- VSCode Version: 1.6.1
- OS Version: Windows 10

Steps to Reproduce:
Before VSCode 1.6, the sidebar is collapsed by default. It works fine for smaller display, as well as non-project files. Since 1.6, the sidebar is expanded when VSCode launches. I'm yet to find any mention of this change in the release note, nor find way to set a preference to reverse this. I'm not sure if this change is intentional or a regression.
1. Launch VSCode.
2. Examine the sidebar.

**Comment by bpasero** [comment]
@seanmcbreen @chrisdias @chrmarti experiments?!

**Comment by Bill-Stewart** [comment]
I have noticed the same behavior - the sidebar is always opened when I start vscode (even if I closed it before quitting vscode previously).

**Comment by bpasero** [comment]
@Bill-Stewart for workspace where you open a folder or when you open VS Code empty / single file?

**Comment by bpasero** [comment]
This seems to be https://github.com/Microsoft/vscode/issues/13825

**Comment by Bill-Stewart** [comment]
+1: Setting `"telemetry.experiments.showDefaultViewlet": false` fixed this for me.
