### ISSUE TITLE
The workspace is frozen after opening any project

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#13727]
- VSCode Version:
![2016-10-14_09h20_33](https://cloud.githubusercontent.com/assets/3082812/19377506/7939712c-91ef-11e6-86c3-e4fd6721f12b.png)

- OS Version: win7 pro

The workspace is frozen after opening any project. And the console displays the error:
_Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError_

Steps to Reproduce:

1. Open VSCode

2. Open any project

3. In the developer console diplays an error
   
   > _Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError_

4. All workspace element does not respond to any user action

**Comment by IgorNovozhilov** [comment]
Repeated in:
![2016-10-14_09h57_57](https://cloud.githubusercontent.com/assets/3082812/19378342/b0f657c4-91f4-11e6-8b5b-9997aa0fbb7e.png)

**Comment by IgorNovozhilov** [comment]
Error disappears if you manually delete the following files and directories:
```
C:\Users\user1\AppData\Roaming\Code - Insiders\Cache
C:\Users\user1\AppData\Roaming\Code - Insiders\GPUCache
C:\Users\user1\AppData\Roaming\Code - Insiders\Local Storage
C:\Users\user1\AppData\Roaming\Code - Insiders\User\workspaceStorage
C:\Users\user1\AppData\Roaming\Code - Insiders\Cookies
C:\Users\user1\AppData\Roaming\Code - Insiders\Cookies-journal
C:\Users\user1\AppData\Roaming\Code - Insiders\Preferences
```

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13667
