### ISSUE TITLE
Submenu items incorrectly have aria-checked set and role checkbox

### ISSUE THREAD

**Issue by Shivanikupatkar** [microsoft/vscode#137214]
### GitHubTags
#A11yTCS; #A11ySev2; #A11yMAS; #A11yWCAG; #DesktopApp; #Visual Studio Code Client; #WCAG1.3.1;#BM-VisualStudioCode-Win32-Nov2021;#Win32; #ScreenReader; #Element:listitem; #NVDA; #Narrator;#Win10; #AINotInscope;

### Actual Result
Narrator/NVDA is reading incorrect role for appearance & layout as "checkbox".

### Expected Result
Narrator/NVDA  should read correct role for appearance & layout as list item under view menu button.

### Environment Details
Application Name: Visual Studio Code Client
Version:1.62.1 (user setup)
Windows Version: Windows 10  (21H1)

### Repro Steps
1)Start Narrator/NVDA.
2)Open Visual studio code editor
3) Using "Alt+F" key navigate to the "File" menu bar option .                                                                                              3)Using 
4)"Alt+E" key navigate to the "Edit" menu bar option                                                                   
5)Using "Alt+S" key navigate to the "Selection" menu bar option .                                                      
6)Using "Alt+V" key navigate to the "View" menu bar option                                                                   
7)Using "Alt+G" key navigate to the "Go" menu bar option.                                                        
8)Using "Alt+D" key navigate to the "Help" menu bar option.                                                       
9)Using "Alt+T" key navigate to the "Tasks" menu bar option.                                                              
10)Using "Alt+H" key navigate to the "Help" menu bar option.                                                           
11) Using "Down" arrow key navigate to the menu items in the file menu option and observe that screen reader is announcing the correct label information.

### User Impact
Screen reader users  will face difficulty as Narrator/NVDA is reading incorrect role.

![A11y_Visual Studio Code Client_Menu bar Options_Screen reader](https://user-images.githubusercontent.com/94344363/141767847-d7a56e00-301a-4598-a8b7-d3595b03ccfe.gif)
![A11y_Visual Studio Code Client_Menu bar Options_Screen reader_nvda](https://user-images.githubusercontent.com/94344363/141767939-31c48846-bf29-4190-a131-1a88b5f8ea48.gif)

**Comment by isidorn** [comment]
@Shivanikupatkar thanks for filling this issue

@sbatten no need to read the long description. The problem seems to be that we are setting role=checkbox and aria-checked for submenu items in the main menu. This is incorrect. This is probably just a corner case from your fix https://github.com/microsoft/vscode/issues/120597

**Comment by isidorn** [comment]
I have verified the fix indeed fixes the issue -> verified
