### ISSUE TITLE
خاصية طي العناصر collapse element

### ISSUE THREAD

**Issue by AndroidMdarwish** [microsoft/vscode#137235]
عند بلوغ الملف HTML لعدد معين يزيد تختفي خاصية الطي للعناصر
when the HTML file reached to specific lines the collapse elements feature disappear!

**Comment by aeschli** [comment]
Yes, we have a maximum of 5000 folding ranges for performance reasons.
This is currently not configurable by users

The feature request for that is https://github.com/microsoft/vscode/issues/72994
