### ISSUE TITLE
Extension views tooltip empty

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#137239]
![image](https://user-images.githubusercontent.com/35271042/141817953-538a4845-450e-4cc1-b5cd-44df03d0e5a7.png)

Steps to Reproduce:

1. Install Node Dependencies extension https://marketplace.visualstudio.com/items?itemName=idered.npm
2. Hover over activity bar item
3. :bug: tooltip is empty

Looks like something weird is going with the view titles:

<img width="240" alt="CleanShot 2021-11-15 at 08 37 40@2x" src="https://user-images.githubusercontent.com/35271042/141819513-58d9170a-1235-4199-90c2-69cd671f357e.png">

**Comment by sandy081** [comment]
It seems the contributed view container has no title

![image](https://user-images.githubusercontent.com/10746682/142222051-eaf5805c-7b04-4e9a-bc6f-a632b6a70512.png)

Falls back to id if no title is present.
Also generates a warning in the console while reading such containers.
