### ISSUE TITLE
Copy Path and Copy Relative Path commands are only available when editor is not focused.

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode#137216]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.1
- OS Version: Mac OS 11.6

Steps to Reproduce:

1. Open a file
2. Right click on the file tab, there is a copy file command and a keybinding to use it
3. Try and use the suggested keybinding (`cmd + alt + c`) (whilst the editor is focused)
4. Nothing is added to the clipboard and nothing is shown to the user explaning why.

I would expect the path to be copied to clipboard but it isn't.

The when clauses in this file, specify that the keybinding is only active when the editor is not focused.
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/files/browser/fileCommands.ts#L293-L319

I did some digging to see when that when clause was added and found this:

Related change: https://github.com/microsoft/vscode/commit/c88e58fc7a6aa47293ced091122f2afe9dadce1f
Which fixed bug: https://github.com/microsoft/vscode/issues/47947

> The find widget has 3 toggles:
> * match case - cmd+alt+C
> * match whole word - cmd+alt+W
> * use regular expression - cmd+alt+R
> 
> From those 3 there are 2 commands which now overwrite :
> * `revealFileInOS` steals cmd+alt+R
> * `copyFilePath` steals cmd+alt+C
> 
> @isidorn Please leave cmd+alt+R and cmd+alt+C for the find widget toggles when focus is in the editor.

_Originally posted by @alexdima in https://github.com/microsoft/vscode/issues/47947#issuecomment-383911912_

It looks like the exclusion is correct, but it is a bit confusing for a user as when you right click on a tab, you are shown a command to copy the relative path, but then when you try and use it, it doesn't work. (Editor being focused is probably the most common use case in vscode.)

As an alternative suggestion, perhaps we could use `!findWidgetVisible` as the when clause instead - that would avoid conflicting with the find widget commands but would allow the command to be used in the editor.

It also has the advantage that something would always happen, either the path would be copied, or the icon in the find widget would change.

I have created a draft CL with a change that would potentially improve this.

WDYT?

**Comment by a-stewart** [comment]
Related change:
https://github.com/microsoft/vscode/commit/c88e58fc7a6aa47293ced091122f2afe9dadce1f
https://github.com/microsoft/vscode/issues/47947

**Comment by a-stewart** [comment]
Ok, I think I have the answer to what is happening here:

> The find widget has 3 toggles:
> * match case - cmd+alt+C
> * match whole word - cmd+alt+W
> * use regular expression - cmd+alt+R
> 
> From those 3 there are 2 commands which now overwrite :
> * `revealFileInOS` steals cmd+alt+R
> * `copyFilePath` steals cmd+alt+C
> 
> @isidorn Please leave cmd+alt+R and cmd+alt+C for the find widget toggles when focus is in the editor.

_Originally posted by @alexdima in https://github.com/microsoft/vscode/issues/47947#issuecomment-383911912_

Perhaps we could use `!findWidgetVisible` as the when clause instead - that would avoid conflicting with the find widget commands but would allow the command to be used in the editor.

**Comment by bpasero** [comment]
Related PR: https://github.com/microsoft/vscode/pull/137217

@rebornix assigning this issue also to you given the change in https://github.com/microsoft/vscode/issues/49231. I think the check for `EditorContextKeys.focus` is too strict now (hence this issue). The PR seems to solve https://github.com/microsoft/vscode/issues/49231 slightly better by explicitly checking for the find input box having focus, but to be honest I find such hardcoding from the explorer world weird. I would have somehow expected the find widget keybinding to have higher priority than the one from the workbench, but maybe that is not the case.

**Comment by a-stewart** [comment]
@rebornix - was just wondering if you had any opinions on this - I'm happy to look into alternatives if you have a preferred alternative approach?

**Comment by a-stewart** [comment]
@rebornix @bpasero - Was just wondering if there was any update on this? PR #137217 is ready for reviewing if that is the approach you would like to take.

**Comment by a-stewart** [comment]
@rebornix @bpasero - small bump - it's not a major issue but was wondering if you had any thoughts about this?

**Comment by rebornix** [comment]
I'll take a look this week and see the impact of merging the PR and decide if having it merged this week or next.

**Comment by rebornix** [comment]
Experimented with the PR and a couple of variations of `when` clauses, but found we could'n't really get rid of `editorFocus`. Toggle Match Case is not only used in Find Widget, but that also drives how `cmd+d` works. So users should be able to press `cmd+alt+c` in the editor (without Find Widget being visible) and then select words that match the current selection.

> It looks like the exclusion is correct, but it is a bit confusing for a user as when you right click on a tab, you are shown a command to copy the relative path, but then when you try and use it, it doesn't work

This is a different/bigger issue though for Menu. Our keybindings on menu/toolbars don't present `when` clause, there is no guarantee that pressing the keybinding from the menu anywhere can work.

**Comment by bpasero** [comment]
@alexdima fyi this is about the fact that a context menus shows a keybinding even though the context does not match. I am pinging you because I see similar issue https://github.com/microsoft/vscode/issues/40389 which was closed.

The commands in question are the "Copy" commands in the tab context menu:

![image](https://user-images.githubusercontent.com/900690/183241234-ab7c8b0b-bb20-4563-9b17-08d12ddbcf00.png)

The command is registered with a `when` clause here:

https://github.com/microsoft/vscode/blob/cb79d015557d546d0d48cea97d7fc3ac0d3dc590/src/vs/workbench/contrib/files/browser/fileCommands.ts#L266-L278

And the menu contributed here:

https://github.com/microsoft/vscode/blob/cb79d015557d546d0d48cea97d7fc3ac0d3dc590/src/vs/workbench/contrib/files/browser/fileActions.contribution.ts#L154-L168

My question is whether there is something the context menu does wrong or whether we simply do not support `when` in context menus.

I think bottom line, the desired output would be to:
* show the command in the context menu
* do not show the keybinding unless the `when` condition matches

**Comment by bpasero** [comment]
This was fun to investigate, learnings:
* if a command only has 1 keybinding assigned, we always show that in the menus even if context keys do not match as a way to let the user learn a possible keybinding ([explainer](https://github.com/microsoft/vscode/issues/126306#issuecomment-866290395))
* this means we have to register another rule for when editor does have focus to properly show it in the context menu

I decided to go with a chord in that case:

<img width="319" alt="image" src="https://user-images.githubusercontent.com/900690/185561231-987e173c-19e9-4289-a69e-b4a0e16ab612.png">

As a nice side effect, you can now copy path and copy relative path from within the editor without having to rebind keybindings.
