### ISSUE TITLE
Extend file watch to support Images

### ISSUE THREAD

**Issue by ykis-0-0** [microsoft/vscode#137296]
As mentioned in the title,
Is it possible to extend the file watcher to support image files like `.png`s?
It causes some inconveniences as I need to reopen the generated image to check the results manually.

**Comment by bpasero** [comment]
File watching works for any file types, if the editor does not update as a result then maybe it is an issue with the editor you use for watching images. What extension are you using?

**Comment by bpasero** [comment]
cc @Tyriar this almost sounds related to the other issue with Luna paint

**Comment by Tyriar** [comment]
Yeah it does look the same https://github.com/microsoft/vscode/issues/137574
