### ISSUE TITLE
print out

### ISSUE THREAD

**Issue by shagariboy** [microsoft/vscode#137232]
Issue Type: <b>Bug</b>

Please why do i get this print out with the brackets and quotes?

`def vaccine(id, v_Id):
    print('User with ID', id, 'has been vaccinated with', v_Id)
    
vaccine(20211987, 'Pfizer')    
vaccine(20219383, 'Johnson&Johnson')
vaccine(20219910, 'Otondos')`      

Print out on Terminal:

('User with', 20211987, 'has been vaccinated with', 'Pfizer')
('User with', 20219383, 'has been vaccinated with', 'Johnson&Johnson')
('User with', 20219910, 'has been vaccinated with', 'Otondos')

VS Code version: Code 1.62.2 (Universal) (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin x64 17.7.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id 13fb1e6e-808e-4808-b74b-a9b4f7bf40b9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.6.0
vscode-markdownlint|Dav|0.45.0
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
vscode-html-css|ecm|1.10.2
vscode-optimize-images|fab|1.1.1
code-runner|for|0.11.6
vscode-pull-request-github|Git|0.32.0
language-haskell|jus|3.4.0
vsc-python-indent|Kev|1.14.2
MagicPython|mag|1.1.0
markdown-converter|man|5.0.1
code-beautifier|mic|2.3.3
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.17.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
autodocstring|njp|0.5.4
code-compass|Nok|1.0.4
java|red|1.0.0
LiveServer|rit|5.6.1
python|tht|0.2.3
haskelly|UCL|0.5.5
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
jinja|who|0.0.8

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by CodeCrazy-ywt** [comment]
The only possibility I can think out is that you're using Python 2 (where `print` is a keyword) but using Python 3 syntax (where `print` is a function).
