### ISSUE TITLE
I go in explorer trying to create 3.c and I notice that vs code make 3.c++

### ISSUE THREAD

**Issue by MrCode00** [microsoft/vscode#137231]
Issue Type: <b>Bug</b>

I go in explorer trying to create 3.c and I notice that vs code make 3.c++ file but  I want to create c file kindly you fix it thanks for Such great IDE I Love VS code 
If this problem is only  with me then message me 

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 6.3.9600
Restricted Mode: No

**Comment by JacksonKearl** [comment]
\gifPlease
