### ISSUE TITLE
Extensions get activated by visiting their Marketplace page

### ISSUE THREAD

**Issue by tillig** [microsoft/vscode#137236]
Issue Type: <b>Bug</b>

I noticed that if you have a given extension installed and then look at it in the Marketplace, you have the possibility of getting that extension _activated_ because the context changes. I can consistently get it to activate with the Scala Metals extension, for example, because it activates `onLanguage:scala` and the Marketplace will apparently change the language to Scala when you visit the page.

1. Install the "Scala (Metals)" extension - `scalameta.metals`
2. Exit VS Code.
3. Start VS Code. No project needs to be loaded.
4. Open the Output window and view the `Log (Extension Host)` window.
5. Open the Extensions panel, enter `@installed` to see the installed extensions, and select `Scala (Metals)`.

In the extension host log you'll see something like:

`[2021-11-15 07:32:53.993] [exthost] [info] ExtensionService#_doActivateExtension scalameta.metals, startup: false, activationEvent: 'onLanguage:scala'`

This is a problem if you're in an unrelated project. The Metals extension, for example, when it starts up, assumes you're in a Scala project and starts laying down cache and log objects for building Scala.

I don't expect that viewing the Marketplace page for an extension should change the language context or do anything that would cause an extension to be activated.

Related: https://github.com/scalameta/metals-vscode/issues/411

VS Code version: Code 1.62.2 (Universal) (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (24.73GB free)|
|Process Argv|. --crash-reporter-id a21085e6-5ee1-4061-97ea-5194a6748695|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (85)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.6.4
better-comments|aar|2.1.0
project-manager|ale|12.4.0
cucumberautocomplete|ale|2.15.1
color-info|bie|0.7.0
markdown-emoji|bie|0.2.1
prettier-toml|bod|0.1.0
better-toml|bun|0.3.2
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.2
gitignore|cod|0.7.0
vscode-code-review|d-k|1.29.1
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
git-extension-pack|don|0.1.3
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|11.6.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.23
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
dotnet-test-explorer|for|0.7.7
remotehub|Git|0.18.0
go|gol|0.29.0
todo-tree|Gru|0.0.214
terraform|has|2.16.0
yaml-plus-json|hil|1.8.0
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
plantuml|jeb|2.16.0
vscode-graphviz|joa|0.0.6
docomment|k--|0.1.30
restructuredtext|lex|167.0.0
rainbow-csv|mec|1.10.1
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
ecdc|mit|1.4.0
nc-gcode|ML|0.13.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.17.0
csharp|ms-|1.23.16
vscode-kubernetes-tools|ms-|1.3.4
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.11
cpptools|ms-|1.7.1
powershell|ms-|2021.10.2
polacode|pnp|0.3.4
fabric8-analytics|red|0.3.4
java|red|1.0.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.1
vscode-yaml|red|1.2.0
vscode-coverage-gutters|rya|2.8.2
scala|sca|0.5.5
metals|sca|1.10.15
rewrap|stk|1.15.2
spectral|sto|0.2.5
code-spell-checker|str|2.0.12
msbuild-project-tools|tin|0.3.15
vscode-json-stable-stringify|Tra|1.2.1
simple-rst|tro|1.5.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.14
vscode-arduino|vsc|0.4.8
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
vscode-icons|vsc|11.7.0
jwt-debugger|yok|0.4.2
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.13.2
html-css-class-completion|Zig|1.20.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by sandy081** [comment]
This is coming from Markdown Renderer

![image](https://user-images.githubusercontent.com/10746682/142218097-113a2865-1ebe-4855-8065-a3ffb19a19d0.png)

![image](https://user-images.githubusercontent.com/10746682/142218134-c1c35fc4-a7b3-44a8-a10c-29bd7a8e1a86.png)

@mjbvz Not sure if it is intended/required

**Comment by mjbvz** [comment]
I believe calling `triggerMode` is required to ensure the grammar is loaded. Is that correct @alexdima?

Here's there the language encounter triggers activation: 

https://github.com/microsoft/vscode/blob/11862795ea2dc6491018addf3696ef0c0b440aee/src/vs/workbench/services/mode/common/workbenchModeService.ts#L154

**Comment by IanMatthewHuff** [comment]
Verified. Looks good now.
![image](https://user-images.githubusercontent.com/812783/151464011-4d0171c1-4938-4a66-be4a-8760b7c0ba6a.png)
