### ISSUE TITLE
Code dissapearing while testing PHP

### ISSUE THREAD

**Issue by Zingo21** [microsoft/vscode#137228]
Issue Type: <b>Bug</b>

I am testing my PHP code so it's all clear when i upload it to my domain. While I was in my browser it went ok but when I came back in VS Code, then some of the files I wrote was deleted. When i closed my opened file tabs and tested in my browser then it was okay and none of the files I wrote in was deleted. I'm not sure but I think it can be some problem with the version of VS Code.🤔

VS Code version: Code 1.62.2 (Universal) (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 32038472-23da-4d4c-ab49-4e25654c066a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.1
icons-carbon|ant|0.2.4
git-urgent|ara|1.0.0
vscode-intelephense-client|bme|1.7.1
dart-code|Dar|3.28.0
flutter|Dar|3.28.0
vscode-markdownlint|Dav|0.45.0
xml|Dot|2.5.1
gitlens|eam|11.6.1
fauna|fau|1.8.1
php-debug|fel|1.22.0
remotehub|Git|0.18.0
vscode-pull-request-github|Git|0.32.0
vscode-pull-request-github-insiders|Git|2021.11.14945
vscode-git-add-and-commit|iva|2.1.1
intellij-idea-keybindings|k--|1.5.0
swift|Kas|0.2.0
unity-code-snippets|kle|1.3.0
git-tree-compare|let|1.13.2
google-fonts|lio|0.0.1
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.14
csharp|ms-|1.23.16
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
brackets-keybindings|ms-|0.1.1
brackets-pack|ms-|0.1.1
cpptools|ms-|1.7.1
live-server|ms-|0.2.9
vs-keybindings|ms-|0.2.1
debugger-for-chrome|msj|4.13.0
material-icon-theme|PKi|4.10.0
vscode-css-peek|pra|4.2.0
java|red|1.0.0
LiveServer|rit|5.6.1
teamhub|Tea|14.0.8
html-preview-vscode|tht|0.2.5
unity-tools|Tob|1.2.12
luna-paint|Tyr|0.10.0
unity-debug|Uni|3.0.2
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
unity-snippets|Ycl|0.1.2
html-css-class-completion|Zig|1.20.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by roblourens** [comment]
Sorry this happened but I don't really understand, can you tell me exactly what you did that caused files to be deleted? I think this was most likely due to an external tool you are using or possibly some extension.

**Comment by Zingo21** [comment]
Yes I can. When I was done editing my PHP files, I saved them so it could be visible on my local server on my computer. 

Then I went to the window for the browser Opera GX and tested out the new changes. When I went back to my VS code workspace, some of the files I edited earlier was completely gone.
I had to use cmd+Z to get my changes back. 

I also wanted to what will happen if I closed VS code, I saved the changes I did for the PHP files and closed VS code. I tested put the code in Opera GX and it went good. When I opened up VS code again some of the edited files where gone again and this time I couldn't get the changes back by cmd+Z. 
Luckily, I had some files I used for an earlier assignment that I could just paste it in and change the heading location when I clicked on buttons.
Then I saved and closed the opened files I was editing on, and by that I mean the files that was affected when I was using my browser. When I came back this time, all the changes I did to the files wasn't gone. When I was satisfied with my work, I uploaded it to my domain page and did tests to see if it was working and did not give me errors. It all passed. 👍

That's all I did.

**Comment by roblourens** [comment]
Sorry but I'm not sure what would have happened. In the second instance it sounds like the files disappeared while vscode was closed, which makes it sound like vscode probably wasn't involved?

**Comment by Zingo21** [comment]
I have now read that it can be some problems with the new macOS update. There the custom mouse cursor randomly takes huge amounts of memory. I don't know if maybe this can cause the problem I had.

**Comment by roblourens** [comment]
I don't think there's anything I can do here, sorry

**Comment by Zingo21** [comment]
Well thanks!😃
