### ISSUE TITLE
API to create a task with problem matcher definition as opposed to name only

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode#137221]
I was not able to find a way to create a task (from the code base of the extension I am developing, as opposed to defining one as a user in .vscode/tasks.json) with a custom define of a problem matcher object. I could only provide a list of names for problem matchers that are defined in the package.json of the "Makefile Tools" extension.

We need to give our users the possibility to define their own problem matchers without releasing updates of "Makefile Tools". We could read into tasks.json for the global defined problem matcher but since it doesn't have a name or label available to set, we can't make our extension pass that global problem matcher of .vscode/tasks.json into new vscode.Task().

**Comment by andreeis** [comment]
Related feature request in your backlog: https://github.com/microsoft/vscode/issues/61497.

**Comment by alexr00** [comment]
@andreeis to make sure I understand:
1. The extension provides tasks with a task provider.
2. The extension wants to add a problem matcher to the tasks it provides.
3. Specifically, the extension wants to create it's own problem matcher and add it to the tasks it provides.

Is that correct?

**Comment by andreeis** [comment]
Yes, yes and no. If the extension adds its own problem matcher, things work fine. And with the upcoming release our users will be able to benefit of a command that will make our extension create via your API a task and point its problem matcher to the name of what we define in our own package.json.

But we want to let our users be able to write their own new problem matchers, different than the ones we provide and we'd like us to be able to create a problem matcher object (not just name string) to feed into vscode.Task constructor.

        let myTaskCommand: vscode.ShellQuotedString = {value: configuration.getConfigurationMakeCommand(), quoting: vscode.ShellQuoting.Strong};
        let myTaskArgs: vscode.ShellQuotedString[] = makeArgs.map(arg => {
            return {value: arg, quoting: vscode.ShellQuoting.Strong};
        });
        let shellExec: vscode.ShellExecution = new vscode.ShellExecution(myTaskCommand, myTaskArgs);
        let myTask: vscode.Task = new vscode.Task({type: "shell", group: "build", label: makefileBuildTaskName},
            vscode.TaskScope.Workspace, makefileBuildTaskName, "makefile", shellExec);

        // This returns an array of string. What can I do to be able to load an object here, with name or label, source, regular expression, severity, etc...  Everything that is possible to define in a .vscode/tasks.json.
        myTask.problemMatchers = configuration.getConfigurationProblemMatchers();

        myTask.presentationOptions.clear = clearTerminalOutput;
        myTask.presentationOptions.showReuseMessage = true;

        await vscode.tasks.executeTask(myTask);

**Comment by alexr00** [comment]
I see now, thank you for the example. This would be solved by https://github.com/microsoft/vscode/issues/59337
