### ISSUE TITLE
Markdown in vscode does not support todo list preview

### ISSUE THREAD

**Issue by Firestar-Reimu** [microsoft/vscode#137272]
In default vscode markdown preview, todo list:

```
- [x] item 1
- [ ] item 2
```

display like this:

![image](https://user-images.githubusercontent.com/65082432/141884261-8e980d6f-3a16-4826-81c1-26256b5f4dd5.png)

but it should display like this: (which is part of GFM)

- [x] item 1
- [ ] item 2

versions:

- VS Code Version: 1.62-2
- OS Version: Windows 11/Manjaro Linux Qonos

**Comment by mjbvz** [comment]
See https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox

**Comment by Firestar-Reimu** [comment]
So why don't you support it by default? Isn't it a necessary feature by markdown?
