### ISSUE TITLE
open current file again in new window

### ISSUE THREAD

**Issue by nr1995** [microsoft/vscode#137202]
Hi, noob here.
Is there a hotkey/shortcut to open the current file
(i.e. the file whose name is currently in your window title bar)
in a new window, while leaving the old window as is?

Sometimes you want to keep your current position in your current window,
but you've left some dumb little mistake thousands of lines away,
and it demands your attention for a few seconds first.
Does this exist?  Or am I asking for a new feature?
Thanks!

**Comment by gjsjohnmurray** [comment]
Try the "Split in Group" option from the tab's context menu. This splits right by default, but a button in the upper right lets you swap that to below.

**Comment by nr1995** [comment]
> Try the "Split in Group" option from the tab's context menu. This splits right by default, but a button in the upper right lets you swap that to below.

Thanks for the help!
But I find the messing around with diving different areas in the current window is just frustrating.
There's too many ways to do it, it's too badly explained, too unintuitive, and too hard to undo.
If I could just quickly open a new window, fix the thing, then close the window,
that would be a lot more quick/friendly.
Is there no method as of yet?
Thanks!

**Comment by gjsjohnmurray** [comment]
Not that I know of.

BTW, after you have used "Split in Group" that option becomes "Join in Group". Seems pretty straightforward to me.

**Comment by nr1995** [comment]
The other thing is that my relatively small monitor
is already split into three in that one window.  A split which I try to keep relatively permanent.

Is there a way to open **_any_** file in a new window?
Then maybe I could use a bit of AHK to achieve the desired effect.

**Comment by sbatten** [comment]
<img width="546" alt="Screen Shot 2021-11-16 at 10 07 18 AM" src="https://user-images.githubusercontent.com/6561887/142041237-e84777f9-7955-4d5a-b663-695030d199c3.png">
