### ISSUE TITLE
workspace.onDidChangeWorkspaceFolders not triggered when open Folder as a single-root workspace

### ISSUE THREAD

**Issue by luyu12** [microsoft/vscode#137263]
- VS Code Version:1.62.0
- OS Version: MACOS 11.6

The api workspace.onDidChangeWorkspaceFolders is not firing when open folder as a single-root workspace initially.
But it works normally with adding folders to the existing workspace.
I checked out the api docs and not sure if this is the expected behavior since the description of the 'onDidChangeWorkspaceFolders' is "An event that is emitted when a workspace folder is added or removed."

**Comment by bpasero** [comment]
This is due to https://github.com/microsoft/vscode/issues/69335, I will push a change to document this better.

**Comment by luyu12** [comment]
ok, Thank you! If I understand this correct, this is the current expected behavior. 
I'm working on the extension need to add the listener to the open folder event. Is there any other APIs as a workaround?

**Comment by bpasero** [comment]
Yes, expected behaviour and no workaround currently.
