### ISSUE TITLE
'Search in files' drops comment markers

### ISSUE THREAD

**Issue by nicsav** [microsoft/vscode#137265]
Issue Type: <b>Bug</b>

If searching for 

in a file that contains

                    // pr = dgrs_djf_ptr->sdfhg_dsgff.total_unique_data_rows * sadhdsa_sdsa;

'Search' will display:

pr = dgrs_djf_ptr->sdfhg_dsgff.total_unique_data_rows * sadhdsa_sdsa;

thus losing that fact that that line of code is a comment

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.42.2.el7.x86_64
Remote OS version: Linux x64 3.10.0-1160.42.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (7.72GB free)|
|Process Argv|--crash-reporter-id 7d4ed872-0453-4e1a-8447-65309c686acd|
|Screen Reader|no|
|VM|33%|

|Item|Value|
|---|---|
|Remote|SSH: 101.101.210.13|
|OS|Linux x64 3.10.0-1160.42.2.el7.x86_64|
|CPUs|AMD EPYC 7542 32-Core Processor (128 x 2894)|
|Memory (System)|755.37GB (32.29GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 101.101.210.13|
|OS|Linux x64 3.10.0-1160.42.2.el7.x86_64|
|CPUs|AMD EPYC 7542 32-Core Processor (128 x 2894)|
|Memory (System)|755.37GB (32.25GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
gitlens|eam|11.6.1
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
cpptools|ms-|1.7.1
veriloghdl|msh|1.5.1
sort-lines|Tyr|1.9.0
debug|web|0.25.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by nicsav** [comment]
This is the sample file: [blah.cpp.gz](https://github.com/microsoft/vscode/files/7542509/blah.cpp.gz)

**Comment by nicsav** [comment]
Screen shot: ![search_removes_comment_markers](https://user-images.githubusercontent.com/80062537/141876700-66c03322-7cb6-4a41-a597-b49e458ea72f.png)

**Comment by IllusionMH** [comment]
Search results show limited context around match and it looks like `//` is just is just further from matched term that context will show.

You can click on Open in editor that will show whole lines and even lines before/after match for more contex.

**Comment by roblourens** [comment]
Exactly, the search view is not designed to be a place to read full lines of code.
