### ISSUE TITLE
VSCode 1.6.1 x64 rpm require some i686 rpm

### ISSUE THREAD

**Issue by liaoya** [Microsoft/vscode#13721]
- VSCode Version: 1.6.1
- OS Version: CentOS 7.2.1511

Steps to Reproduce:
1. Run "yum install code-1.6.1-1476373175.el7.x86_64.rpm"
Some output are
Loading mirror speeds from cached hostfile
--> Running transaction check
---> Package libXScrnSaver.i686 0:1.2.2-6.1.el7 will be installed
--> Processing Dependency: libc.so.6(GLIBC_2.4) for package: libXScrnSaver-1.2.2-6.1.el7.i686
--> Processing Dependency: libXext.so.6 for package: libXScrnSaver-1.2.2-6.1.el7.i686
--> Processing Dependency: libX11.so.6 for package: libXScrnSaver-1.2.2-6.1.el7.i686
--> Running transaction check
---> Package glibc.i686 0:2.17-106.el7_2.8 will be installed
--> Processing Dependency: libfreebl3.so(NSSRAWHASH_3.12.3) for package: glibc-2.17-106.el7_2.8.i686
--> Processing Dependency: libfreebl3.so for package: glibc-2.17-106.el7_2.8.i686
---> Package libX11.i686 0:1.6.3-2.el7 will be installed
--> Processing Dependency: libxcb.so.1 for package: libX11-1.6.3-2.el7.i686
---> Package libXext.i686 0:1.3.3-3.el7 will be installed
--> Running transaction check
---> Package libxcb.i686 0:1.11-4.el7 will be installed
--> Processing Dependency: libXau.so.6 for package: libxcb-1.11-4.el7.i686
---> Package nss-softokn-freebl.i686 0:3.16.2.3-14.2.el7_2 will be installed
--> Running transaction check
---> Package libXau.i686 0:1.0.8-2.1.el7 will be installed
--> Finished Dependency Resolution

Then I run "rpm -qpR code-1.6.1-1476373175.el7.x86_64.rpm", the output are
glibc >= 2.15
libXss.so.1
/bin/sh
/bin/sh
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(CompressedFileNames) <= 3.0.4-1

I find libXScrnSaver rpm contains libXss.so.1. I remember 1.6.0 has not such problem, so I run "rpm -qpR code-1.6.0-1476123947.el7.x86_64.rpm", the output are.
glibc >= 2.15
libXScrnSaver
/bin/sh
/bin/sh
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(CompressedFileNames) <= 3.0.4-1

I want to keep my pure 64 bits system and don't install any unncessary i686 rpm.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/13616
