### ISSUE TITLE
Explorer disappears

### ISSUE THREAD

**Issue by jeannew** [microsoft/vscode#137261]
View-> Explorer
Explorer shows up in the left pane
click on any icon in the left pane, like the  Explorer icon or search icon and the Explorer icon disappears.
Expected:
The Explorer icon should not disappear.
This worked for a long time until about 4 months ago after an update it stopped working.

**Comment by JacksonKearl** [comment]
Have you maybe hidden the explorer on accident? 
![image](https://user-images.githubusercontent.com/8586769/141873133-a4a2d0a2-7e0a-4511-ae5d-5a73028119cd.png)
