### ISSUE TITLE
Hyperlinks gone. Cannot navigate to files from Search editor results 

### ISSUE THREAD

**Issue by rbadapanda** [microsoft/vscode#137276]
Issue Type: <b>Bug</b>

Open a folder in vscode insiders.

Open a global search editor(find some text)

Note that the results are not clickable (even after pressing ctrl/alt buttons). in vscode I can click on those hyperlinks to go to the related file. This has regressed in code insiders.
I have the following settings related to searchEditor.
    "search.searchEditor.doubleClickBehaviour": "selectWord",
    "search.searchEditor.reusePriorSearchConfiguration": true,
    "search.searchEditor.defaultNumberOfContextLines": null,

VS Code version: Code - Insiders 1.63.0-insider (035eaab2cb31798c6ae90a35928c62117cb52fcd, 2021-11-15T05:14:30.466Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.147-83.259.amzn2int.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: myDevDesktop_AL2|
|OS|Linux x64 5.4.147-83.259.amzn2int.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz (16 x 3409)|
|Memory (System)|30.36GB (23.62GB free)|
|VM|0%|
</details>

**Comment by JacksonKearl** [comment]
This should be fixed in today's insiders, there was an issue with a migration to a new form of proposed API I was not aware of.
