### ISSUE TITLE
Indent guides interrupt bracket guides

### ISSUE THREAD

**Issue by HookyQR** [microsoft/vscode#137275]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.2 Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
- OS Version: macOS Big Sur 11.6 (20G165)

Steps to Reproduce:

1. Enable `editor.guides.bracketPairs` and `editor.guides.bracketPairsHorizontal`
2. ![CleanShot 2021-11-16 at 10 57 27](https://user-images.githubusercontent.com/14353068/141887729-aece9a42-eede-42a7-b098-e97a3bef2edc.gif)

With only spaces (or no characters) exceeding the left guide edge, the horizontal marker sits above the closing bracket line. It is also set behind the vertical tab markers, which breaks it at each tab position.

Adding any text on the same line drops the horizontal guide to the bottom of the line containing the closing bracket. I feel this is where it should be in all cases, since all text before the closing brace is part of the enclosed section (including no characters).

---

*Edit by @hediet:
The indent guides interrupt the bracket guides.

**Comment by hediet** [comment]
> With only spaces (or no characters) exceeding the left guide edge, the horizontal marker sits above the closing bracket line.

This is by design and inspired from the bracket pair colorizer extension.
I'm open to be convinced that your suggestion makes more sense.

> It is also set behind the vertical tab markers, which breaks it at each tab position.

Please open a separate issue for that! I think this is a bug.
