### ISSUE TITLE
listen for all context keys used in the "when" clause of debugger contributions

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#137219]
As explained in https://github.com/microsoft/vscode/issues/136712#issuecomment-968767827 we need to listen for all context keys used in the "when" clause of debugger contributions and trigger a schema update. Without that we are running into issues like https://github.com/microsoft/vscode/issues/136712

**Comment by roblourens** [comment]
This works but @aeschli should I be able to see the impact of updating the schema without closing/reopening launch.json?

Also the current code calls `registerSchema` multiple times, is there a difference between that and `notifySchemaChanged`?

**Comment by aeschli** [comment]
registerSchema and notifySchemaChanged both trigger the same event. So `notifySchemaChanged` is good enough if you make changes to the existing schema.

The JSON server doesn't yet update the diagnostics of the affected open documents. I can look at that.

**Comment by rchiodo** [comment]
/verified using steps in https://github.com/microsoft/vscode/issues/136712
