### ISSUE TITLE
Run and Debug fails to start when working in a workspace folder

### ISSUE THREAD

**Issue by Nikostito** [microsoft/vscode#137242]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.62.2 - Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
- OS Version: MacOS Big Sur 11.6

Steps to Reproduce:

1. Open a folder which has debug configurations by running `code .` in terminal. The folder will open in VSCode and the debug configurations will work and can be run successfully.
2. Now add the same folder in a new workspace. The debug configurations will fail to start!

There is no debug log, or problem shown

I specifically work with node configurations. This started happening after updating today to "October 2021 Recovery 2"

**Comment by Nikostito** [comment]
So I have a bit more info. The problem appears when a workspace is saved in a file. That's when run&debug stops working.

If I just add the folders to a workspace without saving the workspace, run&debug works fine.

**Comment by Nikostito** [comment]
Temporary fix for anyone with the same problem: Open up your terminal and run 
`code /path/to/workspaceFile`

Maybe is a permissions issue with the new update?

The problem is present if I do a fresh install of the VSCode.app

**Comment by roblourens** [comment]
> The debug configurations will fail to start!

Does anything happen at all? You click the start button and there is no response?

Can you check for error messages in the devtools? (Help > Toggle Developer Tools)

> Temporary fix for anyone with the same problem: Open up your terminal and run code /path/to/workspaceFile

Is this just reopening the workspace in a new window? Do you notice anything different about this window?

**Comment by Nikostito** [comment]
For anyone else finding this issue. The problem was than VSCode did not recognize node installed through nvm.
Add this to the top of your ~/.zprofile file (if you use zsh, bash_profile if you use bash) and then vscode will recongize node correctly.

`
 export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion`
