### ISSUE TITLE
not defined 

### ISSUE THREAD

**Issue by themohh** [microsoft/vscode#137250]
We have written the needed data into your clipboard be
Issue Type: <b>Bug</b>

the whole screen tells me print is not defined pls help 

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.77GB free)|
|Process Argv|--crash-reporter-id de429c53-876e-423f-bf20-8d2fdd64cc4d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
dart-code|Dar|3.28.0
prettier-vscode|esb|9.0.0
code-runner|for|0.11.6
pubspec-assist|jer|2.3.2
kite|kit|0.147.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
awesome-flutter-snippets|Nas|3.0.2
material-icon-theme|PKi|4.10.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246cf:30386378

```

</details>

cause it was too large to send. Please paste.

**Comment by CodeCrazy-ywt** [comment]
> We have written the needed data into your clipboard be
> Issue Type: <b>Bug</b>
> 
> the whole screen tells me print is not defined pls help 
> 
> VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
> OS version: Windows_NT x64 10.0.19042
> Restricted Mode: No
> 
> <details>
> <summary>System Info</summary>
> 
> |Item|Value|
> |---|---|
> |CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
> |GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
> |Load (avg)|undefined|
> |Memory (System)|3.88GB (0.77GB free)|
> |Process Argv|--crash-reporter-id de429c53-876e-423f-bf20-8d2fdd64cc4d|
> |Screen Reader|no|
> |VM|0%|
> </details><details><summary>Extensions (13)</summary>
> 
> Extension|Author (truncated)|Version
> ---|---|---
> bracket-pair-colorizer-2|Coe|0.2.1
> dart-code|Dar|3.28.0
> prettier-vscode|esb|9.0.0
> code-runner|for|0.11.6
> pubspec-assist|jer|2.3.2
> kite|kit|0.147.0
> python|ms-|2021.11.1422169775
> vscode-pylance|ms-|2021.11.1
> jupyter|ms-|2021.10.1101450599
> jupyter-keymap|ms-|1.0.0
> jupyter-renderers|ms-|1.0.3
> awesome-flutter-snippets|Nas|3.0.2
> material-icon-theme|PKi|4.10.0
> 
> 
> </details><details>
> <summary>A/B Experiments</summary>
> 
> ```
> vsliv368:30146709
> vsreu685:30147344
> python383:30185418
> vspor879:30202332
> vspor708:30202333
> vspor363:30204092
> pythontb:30283811
> pythonptprofiler:30281270
> vshan820:30294714
> vstes263:30335439
> vscorecescf:30384386
> pythondataviewer:30285071
> vscod805cf:30301675
> pythonvspyt200:30340761
> binariesv615:30325510
> vsccppwt:30382697
> bridge0708:30335490
> dockerwalkthru:30377721
> bridge0723:30353136
> pythonrunftest32:30373476
> pythonf5test824:30373475
> javagetstartedt:30391933
> pythonvspyt187:30373474
> vsqsis300:30386381
> vsaa593:30376534
> vssld246cf:30386378
> 
> ```
> 
> </details>
> 
> cause it was too large to send. Please paste.

What programming language?
