### ISSUE TITLE
new bracket paring

### ISSUE THREAD

**Issue by perlohmann** [microsoft/vscode#137225]
Issue Type: <b>Bug</b>

The bracket guide does not match scope highlighting.

```
const initialVersion =
      selectedVersion || asset?.versions?.length > 0
        ? asset?.versions?.reduce((a, b) => {
            if (a.revisionKey >= b.revisionKey) {
              return a;
            }
            return b;
          })
        : null;
```
When you position the marker between the "}" and the ")" in the above code (2nd last line) then the new bracket matching does not match the scope highligthing which in my opinion is a bug. If you move the marker to after the ")" then it is correctly matching.

error: ![image](https://user-images.githubusercontent.com/43436115/141783598-892e195b-6942-4be5-8f90-ee1fd2601ef3.png)
correct: ![image](https://user-images.githubusercontent.com/43436115/141783670-6b7676c6-3f00-464d-99b3-0ea6a5f7ab44.png)

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (7.29GB free)|
|Process Argv|--crash-reporter-id b8b1eef1-3f43-47cc-b1db-ed15deb2e5ff|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
auto-rename-tag|for|0.1.9
vscode-pull-request-github|Git|0.32.0
go|gol|0.29.0
gc-excelviewer|Gra|3.0.44
vscode-graphql|Gra|0.3.18
vscode-styled-components|jpo|1.6.6
dotenv|mik|1.0.1
vscode-docker|ms-|1.17.0
csharp|ms-|1.23.16
remote-containers|ms-|0.205.2
debugger-for-chrome|msj|4.13.0
vscodeintellicode|Vis|1.2.14

</details>

**Comment by hediet** [comment]
Should be easy to fix.

**Comment by coder-abhi** [comment]
Can someone tell me how should I enable scope highlighting, I am trying out this issue

**Comment by perlohmann** [comment]
> Can someone tell me how should I enable scope highlighting, I am trying out this issue

Search for: editor.guides.bracketPairs in settings and set it to active

**Comment by hediet** [comment]
Fixed, though the old behavior was also not that bad.
