### ISSUE TITLE
Autocomplete does not suggest the reference class's fields and methods in PHP

### ISSUE THREAD

**Issue by ithieund** [Microsoft/vscode#13723]
Ex:
// Account.php
class Account {
      var $property = "";

      public aMethod() {
            echo "a";
      }
}

// Logic.php
require_once('Account.php');
$acc = new Account();
$acc->p // Right here, it is not suggesting 'property' or 'aMethod' when typing or pressing CTRL + SPACEBAR

This feature is supported in Visual Studio but not in VSCODE.
Please fix this.
Thanks.

**Comment by leaxoy** [comment]
Current version not support PHP for jump source code.
You can use third_party extensions.

**Comment by kaiwood** [comment]
Handled by the same extensions I mentioned in #13722

**Comment by isidorn** [comment]
@mousetraps assigning PHP issues to you so you are aware of the feature request and you can close them / ask people to move them in some php extension repo

**Comment by mousetraps** [comment]
@ithieund see #13722. And to clarify the "expected" behavior... the only PHP completions the core editor currently supports are global variables, global functions, compile time constants, and keywords. In addition, within a document, we will provide completions for function identifiers, and variable names. In this case, you are attempting to access a property defined in a different document, so we won't pick it up.

Closing this issue as the behavior is expected, but I do have a Q, if you don't mind: you mentioned that it works in Visual Studio, and AFAIK we don't provide any support for PHP in VS out of the box (beyond syntax highlighting in VS "15" Preview). Are you using PHP Tools for Visual Studio by any chance?
