### ISSUE TITLE
Go to Definition does not work for PHP

### ISSUE THREAD

**Issue by ithieund** [Microsoft/vscode#13722]
When clicking on the class name and hit F12 (Go to Definition), nothing happens.
Ex: $acc = new Account();
Is it a bug or anything else should be installed or configured?

Thanks.

**Comment by kaiwood** [comment]
That's handled via extensions, not a bug. AFAIR [Crane](https://marketplace.visualstudio.com/items?itemName=HvyIndustries.crane) supports Go to Definition currently. 

There is a newer project that started implementing the [Language Server Protocol](https://code.visualstudio.com/blogs/2016/06/27/common-language-protocol) called [PHP IntelliSense](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense), but some features are still on the Todo list.

**Comment by mousetraps** [comment]
Hey @ithieund! @kaiwood is correct, and I second the suggestion to check out both Crane and PHP IntelliSense, and file issues on their repos if you're still missing any functionality, as we don't intend to beef up support in the core editor.

That said, I do think we could do better on the discoverability front, and I think as those extensions evolve, it will make sense to see how we can surface up better extension recommendations.
