### ISSUE TITLE
Missing fsPath or something from element parent causes issues refreshing tree node using onDidChangeTreeData

### ISSUE THREAD

**Issue by maurice-ellis** [microsoft/vscode#137251]
Issue Type: <b>Bug</b>

1. I followed the following [code sample](https://github.com/microsoft/vscode-extension-samples/blob/main/tree-view-sample/src/ftpExplorer.ts) with a few tweaks for my need like filtering out "." and ".." items.
2. I called the refresh function with an element of `FtpNode` and works great until trying to call refresh on the parent node of an element retrieved through the `getParent` method on [line 140](https://github.com/microsoft/vscode-extension-samples/blob/main/tree-view-sample/src/ftpExplorer.ts#L140). No error is thrown, but an actual refresh of the parent node never happens.

```
public getParent(element: FtpNode): FtpNode {
    const parent = element.resource.with({ path: dirname(element.resource.path) });
    return parent.path !== '//' ? { resource: parent, isDirectory: true } : null;
}
```

I believe the issue is with [line 141](https://github.com/microsoft/vscode-extension-samples/blob/main/tree-view-sample/src/ftpExplorer.ts#L141) and the fact that the `with` method does not return a `_fsPath` property, which I believe is necessary to properly match I believe on [line 543](https://github.com/microsoft/vscode/blob/13d8a09ec8945502ceecb23f04af99f0eafbd301/src/vs/workbench/api/common/extHostTreeViews.ts#L543) and reference the URI of the node that needs to be refreshed. I tried setting `authority`, but that does not fix the issue.

```
private getHandlesToRefresh(elements: T[]): TreeItemHandle[] {
    const elementsToUpdate = new Set<TreeItemHandle>();
    const elementNodes = elements.map(element => this.nodes.get(element));
```

For a workaround, I add a reference to the parent to each child node on [line 66](https://github.com/microsoft/vscode-extension-samples/blob/main/tree-view-sample/src/ftpExplorer.ts#L66) so it can be referenced in the `FtpNode` that is passed into when an item is clicked or selected. I then use this reference to the parent and pass it to the refresh and it works as intended.

```
public getChildren(node: FtpNode): Thenable<FtpNode[]> {
    return new Promise((c, e) => {
        this._client.list(node.resource.fsPath, (err, list) => {
            if (err) {
                return e(err);
            }

        return c(this.sort(list.filter(entry => entry.name !== '.' && entry.name !== '..').map(entry => ({ resource: Uri.parse(`ftp://${node.resource.fsPath}/${entry.name}`), isDirectory: entry.type === 'd', parent: node }))));
        });
    });
}
```

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T09:24:32.081Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id a8a27011-88a7-44a5-9379-df21cf4a04bb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.4.0
tsl-problem-matcher|amo|0.5.0
vscode-eslint|dba|2.2.2
vscode-html-css|ecm|1.10.2
php-debug|fel|1.22.0
go|gol|0.29.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
atom-keybindings|ms-|3.0.9
twig|wha|1.0.2
material-theme|zhu|3.13.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by alexr00** [comment]
@maurice-ellis do you have a complete example I can try out?

**Comment by maurice-ellis** [comment]
@alexr00 , I created a sample [here](https://github.com/maurice-ellis/ftp-test) based off the coding sample, unfortunately, the credentials provided do not work, so you have to provide your own.

There is a `FTP Explorer` view and items have a context menu, Refresh and Refresh Parent. Refresh works with no issues, but Refresh Parent, which attempts to get the parent of the element using the function in the Tree Provider does not refresh at all. You can see the difference between the element coming directly through the command and the element coming from the `getParent` method and it's missing `_fsPath`.

**Comment by alexr00** [comment]
It looks like what you're hitting is that the value that you fire `onDidChangeTreeData` with **must** be the same object as an object already in the tree, just having an object with the same properties and values is not correct.

**Comment by maurice-ellis** [comment]
@alexr00 I'm not sure why this is closed, this is based on the sample code that Microsoft provides and with it, the getParent function does not work.

**Comment by alexr00** [comment]
`getParent` is called by VS Code to support `TreeView` `reveal`, and it works for that. If you want to refresh a parent tree element, which the sample does not do, then you will need a different implementation of `getParent`.
