### ISSUE TITLE
Unable to edit filtered settings via UI

### ISSUE THREAD

**Issue by leogzyl** [microsoft/vscode#137293]
Issue Type: <b>Bug</b>

Steps to reproduce:
- Open settings (Ctrl-comma)
- Use the filter to reduce the number of settings (e.g. files:exclude)
- Try to change the value of a setting (e.g. adding an exclusion)

Expected results: The change is persisted

Actual result:  The UI becomes "jumpy" and resets your changes

After clearing the filter and manually navigating to the setting everything works as expected. Tried disabling all extensions and restarting VSCode to no avail.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (4.75GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/sale1004/projects/rtc-pipeline --crash-reporter-id ddc179bc-53eb-4930-8d62-271b326752f3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.6.1
MagicPython|mag|1.1.0
vscode-docker|ms-|1.18.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
vscode-ai|ms-|0.6.27
vscode-ai-remote|ms-|0.5.0
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
azure-account|ms-|0.9.11
azurecli|ms-|0.5.0
partial-diff|ryu|1.4.3
local-history|xpo|1.4.0
material-theme|zhu|3.13.2

(1 theme extensions excluded)

</details>

**Comment by rzhao271** [comment]
Is this the same issue as https://github.com/microsoft/vscode/issues/134001?
I'm unable to reproduce the issue locally with your steps.
\gifPlease

**Comment by leogzyl** [comment]
Ok, so here it goes: 
![Alt Text](https://github.com/leogzyl/pub_imgs/blob/main/recording.gif?raw=true)

... and while preparing a clean workspace for the video, I found the cause.
This snippet in my settings.json file causes the issue:

```json
{
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell",
            "args": [
                "powershell -NoLogo -NoExit -ExecutionPolicy ByPass -Command ${env:USERPROFILE}\\Miniconda3\\shell\\condabin\\conda-hook.ps1"
            ]
        },
    },
    "terminal.integrated.defaultProfile.windows": "PowerShell"
}
```

The reason for the above snippet is so that I can have a working conda terminal inside VScode, similar to what I have on Windows Terminal (I installed Miniconda without PATH modifications)

Why would that snippet cause that weird UI error?

**Comment by leogzyl** [comment]
> Is this the same issue as #134001? I'm unable to reproduce the issue locally with your steps. \gifPlease

Sure looks like it.

**Comment by WebMechanic** [comment]
how does gifcap help inside VSCode? 
And where are these Screen recordings stored? Can't find them 😯

Win10 with Code 1.62.3

**Comment by WebMechanic** [comment]
> Is this the same issue as #134001? I'm unable to reproduce the issue locally with your steps. 

it is. I am having the same issues with the Settings UI shifting, input focus jumping around, and at times becomes unusable.

Also the **Terminal Selector** is equally jumpy making it hard to impossible to open another terminal using the drop down -- if you're not fast enough. I presume this is related as italso started to happen only recently.

![vscode-terminal-selector-jump](https://user-images.githubusercontent.com/638340/142754910-616618d0-07e1-4cb4-9fd2-8d807e5a633e.gif)

**Comment by WebMechanic** [comment]
> @leogzyl wrote
>  ... and while preparing a clean workspace for the video, I found the cause. This snippet in my settings.json file causes the issue:
> ```json
> {
>     "terminal.integrated.profiles.windows": {
>(snip)
>     },
>     "terminal.integrated.defaultProfile.windows": "PowerShell"
> }
> ```

I also removed any custom `terminal.integrated` settings (although there was nothing fancy about them) and the twitching and jumps are gone.

> Why would that snippet cause that weird UI error?

indeed.

I guess I need to thank you @leogzyl for finding the potential culprit, 'cos this was driving me nuts!! Now let's find out if there is some particular setting causing this.

**Comment by rzhao271** [comment]
Confirmed the bug in Stable with the settings from https://github.com/microsoft/vscode/issues/136509#issuecomment-975674737 and the steps from https://github.com/microsoft/vscode/issues/137293#issuecomment-970488357

**Comment by rzhao271** [comment]
Merging with https://github.com/microsoft/vscode/issues/137293
