### ISSUE TITLE
"Right Click -> Copy Remote File URL" Does not add selected line numbers to URL with Stash/Bitbucket

### ISSUE THREAD

**Issue by rockboynton** [microsoft/vscode#137249]
Issue Type: <b>Bug</b>

If you "Right Click -> Open File on Remote" the link that opens contains the selected line numbers highlighted, however if you "Right Click -> Copy Remote File URL" and paste it, that link does not have the line numbers.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-81-generic
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (16.30GB free)|
|Process Argv|--crash-reporter-id 6da5d16f-f659-414e-8903-e16d034b5abf|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ci-dev11|
|OS|Linux x64 5.4.0-81-generic|
|CPUs|AMD EPYC 7742 64-Core Processor (255 x 1472)|
|Memory (System)|503.70GB (67.83GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|Memory (System)|24.88GB (22.50GB free)|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
Bookmarks|ale|13.2.2
Doxygen|bbe|1.0.0
bracket-pair-colorizer-2|Coe|0.2.1
better-cpp-syntax|jef|1.15.10
vscode-valgrind|kro|0.0.1
Kotlin|mat|1.7.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
material-icon-theme|PKi|4.10.0
scala|sca|0.5.5
rewrap|stk|1.15.3
vscode-icons|vsc|11.7.0
spice|xua|0.1.0
material-theme|zhu|3.13.2
gitlens|eam|11.6.1
shell-format|fox|7.2.2
better-cpp-syntax|jef|1.15.10
dbc|lha|1.2.3
vscode-docker|ms-|1.18.0
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.0.0

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the GitLens extension. Please file a new issue for it: https://github.com/Axosoft/vscode-gitlens/issues
