### ISSUE TITLE
Support xml namespaces in JSX

### ISSUE THREAD

**Issue by mstijak** [Microsoft/vscode#13728]
Visual Studio Code reports syntax errors if namespaces are used inside JSX.

Namespaces are not supported by React (babel-plugin-transform-react-jsx), 
but Babel correctly parses them (babel-plugin-syntax-jsx).

Is this something that should be added directly to VSCode or an extension would be a better choice?

WebStorm and Sublime Text do not have this problem.

**Comment by waderyan** [comment]
@mstijak thank you for opening this issue. Would you mind sharing a simple code example? I believe this is an issue for the JavaScript language service.

**Comment by mstijak** [comment]
I'm developing a framework which offers advanced data-binding options. It's a non-standard use case, but namespaces provide a very convenient syntax. 

This is how you declare a two-way data binding.
```
NumberField value:bind="person.height" />
````
You can see the full example here:
http://cx.codaxy.com/fiddle/?f=luv00Rpw

Also, I noticed that of the leading React developers is considering using `react` namespace to distinguish React-related attributes from everything else (e.g. react:key).

https://github.com/facebook/jsx/issues/66

**Comment by waderyan** [comment]
@mstijak very cool! I don't believe this is supported through an extension today. This may be a good candidate for a PR on the JavaScript language service or an extensibility point for the language service. 

@mhegazy and @dbaeumer can you advise @mstijak on what he can do here?

**Comment by dbaeumer** [comment]
@waderyan this needs to be done by the tsserver since according to @mstijak we report an syntax error here.

**Comment by mstijak** [comment]
It looks like this:

![error](https://cloud.githubusercontent.com/assets/433394/19683121/36a4e2c2-9ab1-11e6-8e0d-de9dae4adbba.png)

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11833
