### ISSUE TITLE
Auto declare Angular 2.0 components when moving components

### ISSUE THREAD

**Issue by Avivbens** [microsoft/vscode#137234]
When moving angular components from one folder to the other, the wrapper module does not change the declarations array to use the component.

Also, as known from other issues, moving a few folders/files in one shot will cause imports problems, so I need to use this extension to move the files without breaking the files.

Like in this video: 
```
https://user-images.githubusercontent.com/77183871/141810610-06b4b4cf-8bd2-42ce-a514-784ddfea479d.mov
```

As for the angular declarations, video here:

```
https://user-images.githubusercontent.com/77183871/141809765-64f5a1b5-e579-4b01-b172-61678cd70a59.mov
```

**Comment by mjbvz** [comment]
Please file this feature request against the angular extension

**Comment by Avivbens** [comment]
How about the imports fixes problem as described above?
