### ISSUE TITLE
Behavior changed: workbench.action.navigateBack

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#137274]
The behavior of `workbench.action.navigateBack` appears to have changed unexpectedly. When the same file is open in multiple editor groups it used to navigate within the same editor group. Now, it will prefer to navigate to any editor group where the file is visible before navigating to same file in the current group.

This is a little subtle to explain, but it substantially hinders my ability to edit because I can't predict where focus is going to jump based on where I actually moved the cursor.

Imagine I have 2 files: A and B. I open A in 2 editor groups, side-by-side, like this:

<(A)> | (A)

Here the parenthesis denote visibility, angle brackets denote focus, and the vertical pipe denotes separate editor groups. Next, I "Go to definition" on a symbol in the left group that navigates to another file in a new editor:

A <(B)> | (A)

Now B is focused in the left group. Next I `workbench.action.navigateBack` to return my cursor to the previous location. I expect this to focus A in the left group, because that's where my cursor actually was. Instead, this focuses A in the right group:

A (B) | <(A)>

I don't know exactly when this changed, but I believe it was in the last 2-3 months.

Issue Type: <b>Bug</b>

 

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (21.64GB free)|
|Process Argv|--crash-reporter-id ba5ddb4a-051a-4a6e-a317-30ba05374695|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
auto-align|bla|0.0.13
graphviz-preview|EFa|1.5.0
vsc-material-theme-icons|equ|1.2.2
vscode-pull-request-github|Git|0.32.0
customize-ui|ioc|0.1.54
monkey-patch|ioc|0.1.15
vsc-space-block-jumper|jmf|1.2.2
Lua|key|0.0.9
polacode-fixed-edition|mrr|0.3.6
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.7.1
code-settings-sync|Sha|3.4.3
dot|Ste|0.0.1
vscode-todo-highlight|way|1.0.5

(1 theme extensions excluded)

</details>

**Comment by akbyrd** [comment]
I'm confused. I swear this changed because it's a core part of my workflow, but I'm seeing issues 5 years old (!!!) with a ton of upvotes.

https://github.com/microsoft/vscode/issues/9526
https://github.com/microsoft/vscode/issues/45233
https://github.com/microsoft/vscode/issues/130663
https://github.com/microsoft/vscode/issues/108422
https://github.com/microsoft/vscode/issues/89903

**Comment by bpasero** [comment]
There were no changes as far as I can tell, but the linked issues make sense to me.
