### ISSUE TITLE
Terminal session contents restored

### ISSUE THREAD

**Issue by nic3point0** [microsoft/vscode#137200]
I think this feature should be optional. Maybe there can be save & restore icons on the terminal so a user can save or restore a previous session. As well as be able to select dates and see previews of previous sessions.

![bitmap](https://user-images.githubusercontent.com/54269299/141726745-32a50f9a-b4f7-4373-a5c5-74cc834c15b5.png)
.

**Comment by gjsjohnmurray** [comment]
Does `"terminal.integrated.persistentSessionReviveProcess": "never"` help?

**Comment by Tyriar** [comment]
Icon/color restoring was fixed in Insiders last week, the feature is already optional as @gjsjohnmurray called out. We wanted to keep it lightweight and not keep backups around without always restoring them, similar to how hot exit works.

**Comment by nic3point0** [comment]
> terminal.integrated.persistentSessionReviveProcess

It works, accept I personally think this is a cool feature that should be available on demand.
