### ISSUE TITLE
dev container breaks hot reloading

### ISSUE THREAD

**Issue by anthonyma94** [microsoft/vscode#137340]
Issue Type: <b>Bug</b>

When I'm using a dev container, hot reloading no longer works. I have to restart the task for my program to rebuild. I'm building a NextJS & Express app within a NX monorepo, but I've tested it on a brand new NextJS app with no success.

`devcontainer.json`
```json
{
    "name": "Node.js & Mongo DB",
    "dockerComposeFile": "docker-compose.yaml",
    "service": "app",
    "workspaceFolder": "/workspace",
}
```

`docker-compose.yaml`
```yaml
version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 14-buster
    env_file: ../.env
    volumes:
      - ..:/workspace:cached
      - app:/workspace/node_modules
    command: sleep infinity
volumes:
  app:
```

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (10.11GB free)|
|Process Argv|--crash-reporter-id a42a78e2-7555-4f96-a47c-97d77872f0ce|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js & Mongo DB|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor (24 x 3699)|
|Memory (System)|24.99GB (17.48GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
language-postcss|cpy|1.1.0
es7-react-js-snippets|dsz|3.1.1
LogFileHighlighter|emi|2.13.0
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
remotehub|Git|0.18.0
expressjs-4-snippets|gur|1.0.2
dotenv|mik|1.0.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
material-icon-theme|PKi|4.10.0
open-in-browser|tec|2.0.0
vscode-nginx|wil|0.7.2
npm-intellisense|chr|1.4.0
prettier-vscode|esb|9.0.0
volar|joh|0.29.5
vscode-docker|ms-|1.18.0
angular-console|nrw|17.12.3
advanced-new-file|pat|1.2.2
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by roblourens** [comment]
I think this would be an issue with the hot reloader/watcher, or devcontainer configuration, maybe it's missing a dependency that nextJS needs?
