### ISSUE TITLE
Keybinding for command notebook.selectKernel results in 'notebook.selectKernel not found' for interactive window and .ipynb files

### ISSUE THREAD

**Issue by ldorigo** [microsoft/vscode#137378]
Issue Type: <b>Bug</b>

(Edited the issue - I originally thought it was only for the interactive window but it appears to fail for notebooks as well)

Extension version: 2021.10.1101450599
VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-74-generic
Remote OS version: Linux x64 5.4.0-74-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.50GB free)|
|Process Argv|--crash-reporter-id 89aeed25-8dc2-46ce-b17c-1f93ab95c565|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: xxx.sdma.nzcorp.net|
|OS|Linux x64 5.4.0-74-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2687W v3 @ 3.10GHz (12 x 3092)|
|Memory (System)|58.88GB (0.53GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: xxx.nzcorp.net|
|OS|Linux x64 5.4.0-74-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2687W v3 @ 3.10GHz (12 x 3092)|
|Memory (System)|58.88GB (0.53GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Are you trying to add a keybinding that brings up the kernel picker?

**Comment by ldorigo** [comment]
Hi, yes - the command appears in the keybindings window: 

![image](https://user-images.githubusercontent.com/8631181/142602460-e14bfcba-3dca-44d0-8085-5f9baa087e11.png)

I'm pretty sure it used to work in previous versions?

**Comment by rebornix** [comment]
We make `notebook.selectKernel` an API command which exists in the extension host, for the UI side, please use `_notebook.selectKernel`
