### ISSUE TITLE
Jade colors strings in light blue in light theme

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1373]
They should be red like for all other languages

![screen shot 2015-12-16 at 11 45 52](https://cloud.githubusercontent.com/assets/1926584/11838961/a0f282ce-a3ea-11e5-8681-e1c4da859195.png)

**Comment by aeschli** [comment]
That's consistent on how HTML and XML render attribute values.
This is how it was in 0.9 and also how VS does it.
![image](https://cloud.githubusercontent.com/assets/6461412/11839151/e34b2e72-a3eb-11e5-9960-35fa76023f96.png)

![image](https://cloud.githubusercontent.com/assets/6461412/11839162/f11e16fe-a3eb-11e5-92a0-bcbf80a1d826.png)

![image](https://cloud.githubusercontent.com/assets/6461412/11839196/363f5446-a3ec-11e5-91e1-0a9cb60ab710.png)
