### ISSUE TITLE
remote: HTTP Basic: Access denied

### ISSUE THREAD

**Issue by gasparassi** [microsoft/vscode#137376]
When running git commands, the IDE gives the error "**remote: HTTP Basic: Access denied**" and does not even ask for the username and password to proceed with the command.

Versão: 1.62.2
Confirmar: 3a6960b964327f0e3882ce18fcebd07ed191b316
Data: 2021-11-11T20:51:30.084Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
SO: Linux x64 5.11.0-40-generic

**Comment by gjsjohnmurray** [comment]
/duplicate of #137183 which is scheduled to be fixed in upcoming recovery release (1.62.3)

Fix also became available today in Insiders.
