### ISSUE TITLE
Control the flags / mode used when creating a new file

### ISSUE THREAD

**Issue by Stargateur** [microsoft/vscode#137342]
Issue Type: <b>Bug</b>

On windows when I create a new file using explorer window file have exec mode, I use cygwin terminal emulator.

This is a bit anoying cause I don't want my files to be +x 99.9% of time.

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (29.76GB free)|
|Process Argv|--crash-reporter-id a57e86fb-a70f-434b-9c89-4ffd84bc2424|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.6.4
vscode-ron|a5h|0.9.0
swagger-viewer|Arj|3.1.2
spellright|ban|3.0.60
vscode-drawio|hed|1.6.2
MagicPython|mag|1.1.0
rust-analyzer|mat|0.3.811
vscode-docker|ms-|1.18.0
vscode-language-pack-fr|MS-|1.62.4
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
sqltools|mtx|0.23.0
vscode-yaml|red|1.2.0
spectral|sto|0.2.5
even-better-toml|tam|0.14.2
vscodeintellicode|Vis|1.2.14
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by Stargateur** [comment]
I should have probably not put bug, since windows do this as default, but more about a feature request to control this behavior, for example `touch` in my shell don't put +x flag but `cargo new` do add +x. But at least I don't use cargo new everyday.

**Comment by JacksonKearl** [comment]
cc @isidorn / @bpasero have we considered customizing the flags used when creating a new file?

**Comment by isidorn** [comment]
Not to my knowledge. Sounds like a fair feature request.

**Comment by JacksonKearl** [comment]
@Stargateur to be clear, you want an option for all newly created files in VS Code to not have the exec flag set?

**Comment by Stargateur** [comment]
> @Stargateur to be clear, you want an option for all newly created files in VS Code to not have the exec flag set?

exactly, sorry not very good english.
