### ISSUE TITLE
`code --new-window` fails with exit code 1

### ISSUE THREAD

**Issue by ottumm** [microsoft/vscode#137390]
Issue Type: <b>Bug</b>

From a terminal (either inside of VS Code or outside of VS Code), run `code --new-window`.

Observe that nothing happens, and the exit code is 1.

Expected results: a new VS Code window is opened.

VS Code version: Code 1.62.2 (Universal) (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.83GB free)|
|Process Argv|--crash-reporter-id 8f42ca99-4aee-44d8-a76d-c3ad38aadefe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.6.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
vscode-pull-request-github|Git|0.32.0
go|gol|0.29.0
skill|her|0.1.1
bats|jet|0.1.7
AWK|lug|0.0.2
vscode-docker|ms-|1.18.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
cpptools|ms-|1.7.1
vsliveshare|ms-|1.0.5090
markdown-preview-enhanced|shd|0.6.1
html-preview-vscode|tht|0.2.5
pdf|tom|1.1.0
vscode-svg-previewer|vit|0.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246cf:30386378
vscexrecpromptt1:30400061

```

</details>

**Comment by ottumm** [comment]
For usage context, I have my `EDITOR` environment variable set to `code --new-window --wait`, so this bug is quite impactful for me.

**Comment by WesleyBryie** [comment]
Could it have something to do with the low amount of free memory on your mac?

**Comment by ottumm** [comment]
@WesleyBryie hmmmm I think that stat might be deceptive. Memory pressure isn't currently all that high on my Mac and this still fails. I can restart VS Code successfully (and open other applications) for instance.

**Comment by ottumm** [comment]
My fault, I had a custom bash wrapper that was necessary in a previous environment, but it wasn't supported. Getting rid of that fixes this. Sorry for the spam.
