### ISSUE TITLE
Wrong repository selected on session restore (multi root workspace)

### ISSUE THREAD

**Issue by kielnino** [microsoft/vscode#137330]
Issue Type: <b>Bug</b>

I'm working with a multi-root workspace where each project has its own git repository. On startup VSCode restores my last session with all the open files and the tree-view updates correctly, selecting the file which has the focus in the editor. 
But the SCM status bar does not switch to the right repository, but shows the status of the repository from the first folder in the workspace.

Steps to reproduce (or see the attached screencast):
1. Open VSCode with a (multi-root)-workspace with two projects (project_a, project_b)
2. Switching the focus of files correcly selects the corresponding repository
3. Close VSCode while the focus is on a file from the second project (project_b)
4. Start VSCode
2. VSCode restores the last session (open editor tabs,  tree-view, etc.) correctly
3. The SCM status bar stays with the repository project_a, although the file in focus belongs to project_b

Expected behaviour:
I would expect that when restoring a session, the correct repository to the file that is in focus in the editor would be selected automatically. The problem here is only occurs when restoring the session. As soon as I actively change the focus in the editor, the associated repositories are correctly selected.

https://user-images.githubusercontent.com/15856124/142190649-92294237-f966-4a71-b9bf-ccefb168a73a.mp4

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:51:30.084Z)
OS version: Linux x64 5.4.0-54-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 2369)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.62GB (8.69GB free)|
|Process Argv|--unity-launch --crash-reporter-id 9ae0a461-683d-467c-906f-613fea2ea251|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.6.1
vscode-docker|ms-|1.18.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
hexeditor|ms-|1.8.2
material-theme|zhu|3.13.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by kielnino** [comment]
I think this is just a refresh issue with the SCM status bar. When I open VSCode, the status bar assumes that I am working on the first repository in my workspace. However, all open editors only refer to files from another repository (the file tree is also expanded correctly). The status bar shows a branch that I already deleted a few days ago, but since it assumes the wrong repository, it suggests publishing the "new" branch.

**Comment by kielnino** [comment]
Any updates on this? I'm facing the same issue on Mac and find it quite annoying.

**Comment by lszomoru** [comment]
@kielnino, sorry for not getting back to you on this until now. I do have a repro for this, and I have couple of ideas on how to address this problem, though there is some added complexity around the way repositories are discovered. I will try to have a fix for this later this week or next week.
