### ISSUE TITLE
toggleTerminal command randomly fails sometimes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#137360]
![recording](https://user-images.githubusercontent.com/2193314/142202330-3c570911-97aa-4b15-ae5d-db30be593388.gif)

Likely fix as this was reproducible in smoke tests: https://github.com/microsoft/vscode/pull/137079/commits/9371d14575e7dfcb7dfedf6c23edeae9e5e544b6

cc @sbatten

**Comment by alexr00** [comment]
What is the best way to verify this?

**Comment by meganrogge** [comment]
@alexr00 run the smoketests on webkit

**Comment by alexr00** [comment]
Looks like the webkit smoketests all fail on Windows. Leaving for someone else to verify.

**Comment by Tyriar** [comment]
This is actually still an issue in https://github.com/microsoft/vscode/issues/137514, closing in favor of that since there are more details.
