### ISSUE TITLE
Copy relative path key sequence

### ISSUE THREAD

**Issue by bincsh** [microsoft/vscode#137395]
Issue Type: <b>Bug</b>

It says "Ctrl+K Ctrl+Shift+C". 
On the status bar it says "The combination Ctrl-K Ctrl+Shit+C is not a command."

Sounds like a bug to me! :)

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (15.55GB free)|
|Process Argv|--crash-reporter-id 257c6818-9ca6-4567-ac6d-689506cc9f38|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
preview-pdf|ana|1.0.0
markdown-mermaid|bie|1.13.0
vscode-task-manager|cns|0.6.0
doxdocgen|csc|1.3.2
vscode-markdownlint|Dav|0.45.0
gitlens|eam|11.6.1
vscode-pull-request-github|Git|0.32.0
better-cpp-syntax|jef|1.15.10
csharp|ms-|1.23.16
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
powershell|ms-|2021.10.2
vsliveshare|ms-|1.0.5090
vsliveshare-audio|ms-|0.1.91
vscode-taskexplorer|spm|2.5.7
cmake|twx|0.0.17
markdown-auto-toc|wib|0.3.0
riscv|zhw|0.0.8
linkerscript|Zix|1.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vshan820:30294714
vscod805cf:30301675
vsccppwt:30393681
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535

```

</details>

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `Ctrl+K Ctrl+Shift+C`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire `Ctrl+K` followed quickly by `Ctrl+Shift+C`.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
