### ISSUE TITLE
vscode.dev can't open empty file from Azure Repos

### ISSUE THREAD

**Issue by davidcorrigan714** [microsoft/vscode#137375]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: VSCode.dev
- OS Version: Windows 10/Chrome

Steps to Reproduce:

1. Create an empty file in a Git Repo hosted in Azure Repos.
2. Open the repo in vscode.dev
3. Try to navigate to the file
4. Observe error in the bottom right
...
5. Add content to the file in Azure DevOps
6. Repeat 1 - 3, observe that the file now opens
![image](https://user-images.githubusercontent.com/47994662/142238156-c43701f9-8c58-4bb1-9eff-4e4089c7c527.png)

**Comment by lszomoru** [comment]
This issue has been fixed.
