### ISSUE TITLE
[json] update diagnostics when schema changes

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#137309]
_Originally posted by @aeschli in https://github.com/microsoft/vscode/issues/137219#issuecomment-970152474_

The JSON server doesn't yet update the diagnostics of the affected open documents. I can look at that.

**Comment by aeschli** [comment]
- In a schema file
`bar.schema.json`:
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "bar": {
        },
    },
    "required": [
        "bar1"
    ]
}
````
- bar.json
```
{
    "$schema": "./bar-schema.json"
}
```

- verify that the error in `bar.json` is `Missing property bar1`
- change the required property in the schema to "foo1"
- verify that the error in `bar.json` is `Missing property foo1`

**Comment by rchiodo** [comment]
/verified

![image](https://user-images.githubusercontent.com/19672699/144136927-82c9ae88-7849-44c3-b8bf-b2914978b0f1.png)
