### ISSUE TITLE
Notebook output won't scroll horizontally - can't see error explanation

### ISSUE THREAD

**Issue by kjohnsen** [microsoft/vscode#137333]
Issue Type: <b>Bug</b>

Open an interactive Python window
Execute this:
```python
raise Exception("when there something really long.............................................................................................................................................................................................you can't see the end")
```

VS Code version: Code - Insiders 1.63.0-insider (3bd29c1d6c6ef5b6265614def99b7257b671ae19, 2021-11-12T12:04:20.740Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (15.83GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/johns/OneDrive%20-%20Georgia%20Institute%20of%20Technology/Rozell%20Lab/presentations/cleosim --crash-reporter-id 13862219-8062-4bb8-969d-b654fdb7b5e1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|Memory (System)|24.85GB (22.11GB free)|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
dart-code|Dar|3.28.0
flutter|Dar|3.28.0
gitlens|eam|11.6.1
matlab|Gim|2.2.1
vscode-pull-request-github|Git|0.32.0
gc-excelviewer|Gra|3.0.44
latex-workshop|Jam|8.21.1
better-cpp-syntax|jef|1.15.10
svg|joc|1.4.14
language-julia|jul|1.5.4
rainbow-csv|mec|1.9.1
theme-monokai-pro-vscode|mon|1.1.19
python|ms-|2021.12.1441722766-dev
vscode-pylance|ms-|2021.11.2-pre.1
jupyter|ms-|2021.11.1001452373
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.63.0
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.0.0
powershell-preview|ms-|2021.11.0
vsliveshare|ms-|1.0.5090
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
color-highlight|nau|2.5.0
autodocstring|njp|0.5.4
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.0
synthwave-vscode|Rob|0.1.10
code-spell-checker|str|2.0.12
even-better-toml|tam|0.14.2
html-preview-vscode|tht|0.2.5
pdf|tom|1.1.0
cmake|twx|0.0.17
vscode-lldb|vad|1.6.10
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.7.0
vim|vsc|1.21.10
mplstyle|yy0|1.8.6
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.13.2

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593cf:30376535
vsc1dst:30396469
vscexrecpromptc:30397557

```

</details>

**Comment by IanMatthewHuff** [comment]
Verified. LGTM now. There is a H-Scroll on the input and the output wraps correctly.
![image](https://user-images.githubusercontent.com/812783/144502038-e8a10ad4-85ea-49dd-9c9f-8911fef31972.png)
