### ISSUE TITLE
Debug: Restart All command

### ISSUE THREAD

**Issue by RandScullard** [microsoft/vscode#137385]
I often debug two processes at the same time. Starting them both is easy with a compound launch configuration, but I would love to also have a way to restart them both with a single command.

This comes up when I change some code that is shared by both processes, and I want to rebuild and re-debug both of them. It's not a huge deal to pick each one from the dropdown and click the Restart button, but I do this dozens of times a day and it would be really nice to do it with a single command.

**Comment by ArturoDent** [comment]
This might help:, see https://marketplace.visualstudio.com/items?itemName=ArturoDent.launch-config&ssr=false#overview

* Run an array of launch configurations from any launch.json in the workspace, in settings.json:

```jsonc
  "launches": {          // (in settings.json)
    "RunLaunchArray": ["Launch File (Project A)", "Launch File (Project B)"]
  }
```

```
  {               // (in keybindings.json)
    "key": "alt+j",
    "command": "launches.RunLaunchArray"
  }
```

**Comment by RandScullard** [comment]
@ArturoDent That is helpful, thanks! I just set it up and it seems to do the trick in my project.

I still think it would make sense for VSCode to have a Restart All command, though - it would require zero configuration and would just restart whatever processes happen to be running at the moment you trigger it. (A Stop All command would also make sense, come to think of it...)

**Comment by roblourens** [comment]
You can set `"stopAll": true,` on your compound so that stopping one will stop all configs in the compound. Doing something like that for restart might make sense too.

**Comment by RandScullard** [comment]
@roblourens That's cool, I didn't notice that option. Yeah, `"restartAll": true` would help in some cases, but in my current use case it would actually be better to have the choice of restarting just the current process or all processes, depending on the change I just made. So I would vote for adding a Restart All command.
