### ISSUE TITLE
'The editor could not be opened because the file was not found' Issue

### ISSUE THREAD

**Issue by chromadevlabs** [microsoft/vscode#137325]
Issue Type: <b>Bug</b>

Source files are missing after opening a vscode session. They are deleted from finder too.

This is what appears in the logs:
Session contents restored from 11/15/2021 at 7:02:01 PM 

VS Code version: Code 1.62.2 (Universal) (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (1.69GB free)|
|Process Argv|--crash-reporter-id 06e12186-c6f3-4a54-9e06-f983d221b85b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
xml2json|bui|1.2.4
doxdocgen|csc|1.3.2
xml|Dot|2.5.1
vscode-pull-request-github|Git|0.32.0
n64-assembly|is0|1.1.5
better-cpp-syntax|jef|1.15.10
mips|kda|0.0.9
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5090
partial-diff|ryu|1.4.3
cmake|twx|0.0.17
vscode-lldb|vad|1.6.8
vscode-arduino|vsc|0.4.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246cf:30386378
vscexrecpromptt2:30400062

```

</details>

**Comment by roblourens** [comment]
Sorry you're having trouble. Most likely there is an external tool or an extension that is responsible for this. Can you tell us exactly what you did when you saw this happen?
