### ISSUE TITLE
Support file with subitems

### ISSUE THREAD

**Issue by rayncc** [Microsoft/vscode#13730]
- VSCode Version: 1.6.0
- OS Version: Windows 10.0.14393

For webapp framework like angular2, a web component is designed to contains multiple files. For example:

mycomponent.ts
mycomponent-template.html
mycomponent-style.css

I hope there is a way to collapse these items together:
mycomponent.ts
   \\_mycomponent-template.html
   \\_mycomponent-style.css

Just like *.xaml, *.xaml.cs for WPF in Visual Studio

**Comment by isidorn** [comment]
Dup of some older issue which I can not find now
@bpasero prorbably has the link to that issue. 
@rayncc please search our open feature requests if you would like to find the original request

**Comment by bpasero** [comment]
Yeah, look for derived resources or solution explorer for similar requests.
