### ISSUE TITLE
Be able to combine semantic textmate scopes with modifiers in color themes

### ISSUE THREAD

**Issue by TamirCode** [microsoft/vscode#137352]
(I am working with semantic scopes for syntax highlighting in color themes)
I would like to select methods with the modifier of `defaultLibrary` , by combining the scope and checking for the modifier, but I tried everything I could think of and as far as I can tell it's not possible to do such. It seems to me the only way to select the scope of modifiers is their more broad fallback scope, in this case would be `entity.name.function.member` . However, this scope would select other methods that do not have the `defaultLibrary` modifier, which defeats the whole purpose of modifiers increasing the specificity of what I want to select. Thank you.

![image](https://user-images.githubusercontent.com/66864667/142174170-3cf6748b-5b13-4745-8c05-5fe346475c00.png)

**Comment by TamirCode** [comment]
After a bit further digging, the core of the issue is that both of type `method` - one with modifier of `defaultLibrary`, and the other with modifier of `declaration` - have the foreground fallback scope of `entity.name.function.member`, hence I can't differentiate the two when styling them even though they have different modifiers. So built-in methods and non-built-in methods (for example functions inside objects) will look the same color

so my new request is to have a different fallback scope for types of method that are of modifier defaultLibrary, or a new fallback scope for the declarative modifier of type method, either one will work

**Comment by aeschli** [comment]
Are you a theme author or a user that wants to customize a theme?
It's possible to define coloring rules directly for semantic tokens. 
That's described in https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-coloring-in-color-themes

**Comment by TamirCode** [comment]
> Are you a theme author or a user that wants to customize a theme? It's possible to define coloring rules directly for semantic tokens. That's described in https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-coloring-in-color-themes

Thanks I solved with the the thing you linked. 
```
"semanticTokenColors": {
    "method.defaultLibrary:javascript": "#c74a8a"
  }
 ```
