### ISSUE TITLE
[completion] CompletionList#isIncomplete ignored on empty or fully filtered items

### ISSUE THREAD

**Issue by svenefftinge** [Microsoft/vscode#13735]
- VSCode Version: 1.6.1

When a CompletionList returns an empty array of items but has set `isIncomplete: true`, the content proposal provider is not asked again on further typing.

I think it is because
 https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/common/completionModel.ts#L167
is not reached if no item exists or all items are filtered.

Is this intentional?

It can be reproduced easily with monaco's playground: 
https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example

Paste the following snippet into it:

```
function createDependencyProposals(contents) {
    if (contents.length%4 === 0) {
        return {
            isIncomplete: true,
            items: []
        }
    }
    return {
        isIncomplete: true,
        items: [
            {
                label: contents + "!!",
                kind: monaco.languages.CompletionItemKind.Function,
                documentation: contents + "!!",
                insertText: contents + "!!"
            }
        ]
    };
}


monaco.languages.registerCompletionItemProvider('json', {
    provideCompletionItems: function(model, position) {
        // find out if we are completing a property in the 'dependencies' object.
        var textUntilPosition = model.getValueInRange({startLineNumber: 1, startColumn: 1, endLineNumber: position.lineNumber, endColumn: position.column});
        return createDependencyProposals(textUntilPosition);
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: "",
    language: "json"
});
```

**Comment by jrieken** [comment]
An empty result is considered no result and doesn't even make it [into](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/common/suggest.ts#L84) the view model - so, yes that is that is on purpose. 

Incomplete but not empty lists will trigger the *ask-again-on-type* if the very first time result wasn't filtered to empty. I think that is fair because completions should always match the current line value before the position.

**Comment by svenefftinge** [comment]
The problem is that if I use the isIncomplete mode, to return different results based on the offset and prefix and there is a position that returns nothing, I don't get retriggered in that same context anymore.  E.g. I have a prefix of `i` where completion returns two elements, then I type `s` which retriggers, because previous was set to`isIncomplete`, now I type another character, retriggering happens again and the result is empty. If I now press backspace I no longer get proposals, because VSCode has forgotten about the 'isIncomplete' flag but treats it as the same context.
