### ISSUE TITLE
git push doesn't work

### ISSUE THREAD

**Issue by dipanshparmar** [microsoft/vscode#137351]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.2
- OS Version: Pop OS 21.04

Steps to Reproduce:

1. Initialize a git repo
2. try to push the code. You will get the "No anonymous write access" error

Please note that **git push** works fine in Android Studio

**Comment by gjsjohnmurray** [comment]
/duplicate of #137183 which is scheduled to be fixed in upcoming recovery release (1.62.3)

**Comment by dipanshparmar** [comment]
@gjsjohnmurray Please reopen the issue if possible. This issue still persists for me in v1.62.3.

**Comment by gjsjohnmurray** [comment]
> @gjsjohnmurray Please reopen the issue if possible. This issue still persists for me in v1.62.3.

Pinging @lszomoru

**Comment by lszomoru** [comment]
Could you please ensure that after you have updated to `1.62.3` all windows are closed again, and restart VS Code? Thanks!

**Comment by dipanshparmar** [comment]
> Could you please ensure that after you have updated to `1.62.3` all windows are closed again, and restart VS Code? Thanks!

Yeah! I can confirm that I restarted VS Code and the issue is still there.

**Comment by dipanshparmar** [comment]
Hey, @gjsjohnmurray @lszomoru I'm not sure how but the git push seems to be working fine now. It asked me to log in again and after login, it is working fine.
