### ISSUE TITLE
There is no key binding for show next global find mach.

### ISSUE THREAD

**Issue by Aukstkalnis** [Microsoft/vscode#13731]
Please add show next find match when global search is used. It is not fast to select find result with mouse.

**Comment by kaiwood** [comment]
I was curious and played around a little bit with this… Although there is no dedicated "Next Result" command, you actually don't need the mouse. 

Down Arrow / Up Arrow moves to the next / previous result in the side bar. Then, if you press Space, the window opens – but the focus stays in the side bar. If you found what you where looking for, you can press Return to edit the file. 

This way you can at least zip through the results with a combination of 2 keys.

**Comment by Aukstkalnis** [comment]
To press space didn't cross my ming. Thanks :) It is good enough for me :)
