### ISSUE TITLE
Request: Make the file jump to command show files relative to the current file first

### ISSUE THREAD

**Issue by MarkKahn** [microsoft/vscode#137304]
Issue Type: <b>Feature Request</b>

Our main project has literally hundreds of sub-repos in it, so using cmd+p to find `package.json`, for instance, is almost useless.

<img width="151" alt="image" src="https://user-images.githubusercontent.com/320562/141995932-686374b2-3c00-46e5-aaba-f780509861cc.png">

Would love to see the `package.json` file relative to the current file I'm looking at displayed first, or any other solution that allows us to navigate easier

e.g. if I'm looking at `/src/foo/bar/baz.ts`, I'd want to see `/src/foo/package.json` first

VS Code version: Code 1.62.2 (Universal) (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-77-generic

**Comment by MarkKahn** [comment]
This isn't exactly a dupe of that issue.  #133438 is asking for the ability to type `./`.  I'm asking VSCode to sort the type-ahead automatically based on relevance.

**Comment by TylerLeonhardt** [comment]
Fair enough. Let's see what folks say.
