### ISSUE TITLE
Put "New File..." next to "New File"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#137328]
I think the new file option would be more discoverable if it is next to the original option. if I open the File menu and am trying to create a new file, I should be able to easily see that there are two.

![image](https://user-images.githubusercontent.com/323878/142054170-0d537ef2-b33f-4258-9456-67ea24568a6a.png)

**Comment by gjsjohnmurray** [comment]
See #135416 for user confusion about having both items.
