### ISSUE TITLE
Never stop on breakpoints when debug react-native app (android)

### ISSUE THREAD

**Issue by alexicum** [Microsoft/vscode#13737]
- VSCode Version: 1.6.1
- OS Version: Windows 10 x 64, home

Steps to Reproduce:
1. setup breakpoints in react-native app (android) js code

Previous VSCode version (1.5.3) working as expected.

**Comment by isidorn** [comment]
Please file this issue against the react-native debug vscode extension here 
https://github.com/Microsoft/vscode-react-native

**Comment by alexicum** [comment]
> MSLaguana commented: I've started looking into the issue with vscode insiders 1.6.0, and it looks like the node debugger that we depend on has made some changes in how they handle source maps which break us. We'll have to adapt to deal with that before breakpoints work in the next vscode release.
https://github.com/Microsoft/vscode-react-native/issues/311#issuecomment-250804821

**Comment by isidorn** [comment]
@MSLaguana be aware of this https://github.com/Microsoft/vscode/issues/13499#issuecomment-253742486
