### ISSUE TITLE
When in the 'search' activity, escape should return to editor

### ISSUE THREAD

**Issue by kenmckaba** [microsoft/vscode#137396]
When I am in the Search activity to find a string in files, it'd be handy if the cursor returned to my editor when I press escape. Now it just stays in the search field and I have to use the mouse to click back on the editor.

Same with all the other activities and modes- escape should leave the current mode and return to the editor.

**Comment by roblourens** [comment]
You can set up a keybinding to do this if you want. But escape does other things and in our layout model, the sidebar and editors are sort of equal views so I wouldn't expect esc to move from one view to another.
