### ISSUE TITLE
search in editors is a missing feature

### ISSUE THREAD

**Issue by theodore-wilson-amd** [microsoft/vscode#137319]
Issue Type: <b>Feature Request</b>

Other editors provide 'search in buffers' which in VsCode would likely be search in editors.  This is a key productivity feature that is not met by search in files.  Search in files will open many files that are not yet open and in large projects becomes useless unless this is the actual intent of the user.  A more common use case is to search across already opened files.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.24.1.el7.x86_64

**Comment by ArturoDent** [comment]
Is this what you are looking for: https://stackoverflow.com/a/65851872/836330
