### ISSUE TITLE
A Javascript error occured during the main process

### ISSUE THREAD

**Issue by sl0wl1** [microsoft/vscode#137353]
Does this issue occur when all extensions are disabled?: Not tested

- VS Code Version: VS Code Version: 1.62.1 & 1.62.2
- OS Version: Windows 10 Enterprise/21H1/19043.1288

Steps to Reproduce:

1. After updates of VS Code to 1.62.1 or 1.62.2, VS Code won't start anymore. 
2. I noticed some function losses in extensions like Jupyter Notebook. E.g., the variable viewer did not work anymore.
3. After closing and restarting VS Code, the app shows attached error message. 

This happened now three times in a row. A reinstallation does not solve this problem for me.
Note: I work on a company notebook with restrictions. In the issue search, I found threads with similar problems. Only Windows Defender is installed and it has no history of removing the missing folders. 

<img width="404" alt="Error" src="https://user-images.githubusercontent.com/56339600/142176228-92668eaa-6c90-45a8-b13c-2b2d7312903e.png">

**Comment by sl0wl1** [comment]
I'm just spitballing....after an administrator updated VS Code the and could not start after that, the Windows EventViewer reported: Microsoft VS Code\Code.exe' cannot be restarted - Application SID does not match Conductor SID

Is there a connection?

**Comment by joaomoreno** [comment]
Any chance you can use the User Installer instead? Can you give that a try?

**Comment by sl0wl1** [comment]
> Any chance you can use the User Installer instead? Can you give that a try?

I don't think so. The IT guidelines are very strict. 

Would it be of any help if I ask IT to perform a clean VS Code installation with the current version, to see wether the error occures after that or if the error is (likely) update related?

**Comment by joaomoreno** [comment]
> Would it be of any help if I ask IT to perform a clean VS Code installation with the current version, to see wether the error occures after that or if the error is (likely) update related?

Absolutely. Let me know how that goes.

**Comment by sl0wl1** [comment]
> > Would it be of any help if I ask IT to perform a clean VS Code installation with the current version, to see wether the error occures after that or if the error is (likely) update related?
> 
> Absolutely. Let me know how that goes.

Sorry, IT is very slow.

**Comment by joaomoreno** [comment]
No worries, I'll be waiting.
