### ISSUE TITLE
Cannot find module 'C:\Program Files\Microsoft VS Code\resources\app\out\main'

### ISSUE THREAD

**Issue by papanito** [microsoft/vscode#137303]
Does this issue occur when all extensions are disabled?: Yes/No

While working with VS code I suddenly cannot use it anymore and also not start it as I get:
![image](https://user-images.githubusercontent.com/15034009/141994274-6bec8c16-8df0-419f-8cd0-78d7afd7ddf1.png)

When I check, the folder `out` is gone
![image](https://user-images.githubusercontent.com/15034009/141994315-df19ec9c-7cd3-4dc2-a8f8-c90ef161f01b.png)

I reinstall VS code using `choco install vscode --force` so I can start vscode again. But after a while same issue happens again.

I use VS code since > 1 year on the same machine and never had such an issue. 

- VS Code Version:  v1.53.0
- OS Version: Windows Server 2019

Steps to Reproduce:

I don't have proper reproduction steps
1. (Re-)Install VS code using chocolate `choco install vscode`
2. Work with VS code

**Comment by gjsjohnmurray** [comment]
Is an antivirus app removing it?

Also I noticed that you are nine releases behind the current (v1.62).

**Comment by papanito** [comment]
> Is an antivirus app removing it?
I also thought that, but I checked and does not seem so

> Also I noticed that you are nine releases behind the current (v1.62)
Yep, I already upgraded the choco package

**Comment by roblourens** [comment]
There is surely an antivirus or similar program removing it. Does it work if you install it from https://code.visualstudio.com/?
