### ISSUE TITLE
Untitled files are totally broken

### ISSUE THREAD

**Issue by joseph-of-wheel** [microsoft/vscode#137326]
Issue Type: <b>Bug</b>

Hit command-n. Type some stuff. Hit command-s. Observe that nothing happens. Try and close the tab. Observe that nothing happens.

VS Code version: Code 1.62.1 (Universal) (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T09:23:14.144Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.32GB free)|
|Process Argv|--crash-reporter-id 32f1210d-2f57-4395-aa2e-b6dd36231c3a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.0.0
smarty|imp|0.3.0
vscode-docker|ms-|1.18.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
vetur|oct|0.35.0
code-spell-checker|str|2.0.12

</details>

**Comment by joseph-of-wheel** [comment]
Additional info: If I refresh/reload the app, there is a very brief window just after refresh during which I can close an untitled tab.

**Comment by ArturoDent** [comment]
I can't repro with W11 Insiders or Stable.  I get a `Save As` dialog.  Did you try with all extensions disabled?

**Comment by gjsjohnmurray** [comment]
Or use the Start Extension Bisect command to investigate.
