### ISSUE TITLE
Any way to custom myself css?

### ISSUE THREAD

**Issue by shalldie** [Microsoft/vscode#13732]
- VSCode Version: 1.6.1

I want to custom myself css into vscode in a extension.

For example , change the panel's background-image .

What i'm doing now is that , i change the vscode's system file (workbench.main.css) , which  is not recommended. 
I want to know is there any recommend way to do it.

THX. Sorry for my english  :D

**Comment by isidorn** [comment]
Hi,

Currently we do not support extensions that can modify the UI any way they want. More about our extension model can be found here https://code.visualstudio.com/Docs/extensions/overview
