### ISSUE TITLE
View: Zoom In/Out step size too large

### ISSUE THREAD

**Issue by BillDenton** [microsoft/vscode#137358]
Does this issue occur when all extensions are disabled?: Not tested

- VS Code Version: 1.62.2 (system setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. View: Zoom In or Out
2. Too large a change in GUI elements (fonts, etc) between steps. Impossible to get an optimal zoom setting.

**Comment by GDYendell** [comment]
You can manually set the zoom value to a decimal in the settings. `Window: Zoom Level` in UI or use `window.zoomLevel` in JSON

**Comment by BillDenton** [comment]
#147713 is a duplicate of this issue. So as #147713 has received enough votes this issue can be closed.
@deepak1556 @roblourens
