### ISSUE TITLE
Revisit extension disablement implementation

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#13734]
Although it supports all use cases, the current solution seems far from optimal, especially considering the architecture changes it creates and its implementation.

We started off the story by saying _we want to support disabling extensions globally and per workspace_. We figured out user settings were not the best place for that since workspace settings are usually checked into SCM. At the same time we decided that we want the files to be manually edited by the user. That excluded the storage service. A new concept was needed of global storage (`extensions.json`) that the user could edit by hand.

This introduced a [new method](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/node/storage.ts#L199) in the storage service which creates a bit of debt. Its implementation is also *way* far from optimal: it's filled with synchronous IO calls. We definitely don't want to do that.

Later this week we decided to do UI for disablement. This drops the requirement for having the files be user-editable. We don't need this new storage concept anymore.

I suggest to take a step back and simply store the disablement state in the `IStorageService` available to the renderer, removing the newly introduced storage concept.

**Comment by joaomoreno** [comment]
@sandy081 Sync up with @bpasero next week if you have questions.

**Comment by bpasero** [comment]
+1 for not changing storage service for this if not needed. there is still some open debt in the area of storage for all the use cases we have but that can be looked at individually.

**Comment by sandy081** [comment]
Agreed. 

Will move it to local storage

**Comment by bpasero** [comment]
Thanks
