### ISSUE TITLE
Always open two workspace

### ISSUE THREAD

**Issue by yetendra07** [microsoft/vscode#137370]
Issue Type: <b>Bug</b>

when ever I open workspace and click to open then always open two workspace

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.25GB free)|
|Process Argv|--crash-reporter-id e3c8c71a-01c8-42b4-8c03-a2d2fdf0f4ef|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-json|and|1.5.0
terraform|has|2.16.0
vscode-azureterraform|ms-|0.3.2
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
azure-account|ms-|0.9.11

</details>

**Comment by gjsjohnmurray** [comment]
/gifPlease

Maybe also check with all extensions disabled. The "Start Extension Bisect" command can help do this.
