### ISSUE TITLE
Hot Exit: Support hot exit on empty workspaces

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#13733]
Hot exit (#101) should work on empty workspaces (those with no opened folder).

**Comment by Tyriar** [comment]
Restoring files in empty workspaces is probably a pre-requisite to this: https://github.com/Microsoft/vscode/issues/207

**Comment by Tyriar** [comment]
I looked into Electron's window ID, looks like it's 0 and incremented each time so we wouldn't be able to use that as a (empty) window identifier across sessions.

**Comment by rsenna** [comment]
Not working for me when multiple windows open.
The first window hasa open folder, the second with no folder opened.
When I create a new document into the second window, and thenI close it, VSCode warns me that I'll lose changes if I not save them.
Related settings: `  "files.hotExit": "onExitAndWindowClose"`
