### ISSUE TITLE
Activating an extension that loads a `.node` binary fails with a code signing error in VS Code Insiders

### ISSUE THREAD

**Issue by isc-bsaviano** [microsoft/vscode#137312]
Issue Type: <b>Bug</b>

The [InterSystems Language Server extension](https://github.com/intersystems/language-server) uses the `ref-napi` and `ffi-napi` modules to call out to native C++ libraries. The `ref-napi` module is shipped with prebuilt `.node` binaries. When activating the InterSystems Language Server extension in VS Code insiders on Mac, it fails with the following text written to the Output channel:

> electron/js2c/asar_bundle.js:5
/*! no static exports found */function(t,e,r){"use strict";(function(t,n){Object.defineProperty(e,"__esModule",{value:!0}),e.wrapFsWithAsar=void 0;const s=r(/*! buffer */"buffer"),i=r(/*! path */"path"),a=r(/*! util */"util"),o=t._linkedBinding("electron_common_asar"),c=t._linkedBinding("electron_common_v8_util"),f=r(/*!
...

After running the extension in debug mode, I found this error written to the debug console:

> Uncaught Error: dlopen(/Users/bsaviano/Documents/GitHub/language-server/server/node_modules/ref-napi/prebuilds/darwin-x64/electron.napi.node, 0x0001): tried: '/Users/bsaviano/Documents/GitHub/language-server/server/node_modules/ref-napi/prebuilds/darwin-x64/electron.napi.node' (code signature in <CCE47DE4-A5FB-37F6-93DA-0752138DEEA3> '/Users/bsaviano/Documents/GitHub/language-server/server/node_modules/ref-napi/prebuilds/darwin-x64/electron.napi.node' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/lib/electron.napi.node' (no such file)

This error only occurs on Insiders and only on Mac. After some research I think this has to do with the [Hardened Runtime](https://developer.apple.com/documentation/security/hardened_runtime) flag in Xcode. Has anything changed between 1.62.2 and 1.63.0-insiders related to how VS Code is built? 

VS Code version: Code - Insiders 1.63.0-insider (Universal) (6a25ae3a24929f35aabf8a051531c0716032e0a0, 2021-11-16T05:13:23.962Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (2.30GB free)|
|Process Argv|--crash-reporter-id a3bf9c34-8ccb-4f82-9693-8f13aeea9669|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
servermanager|int|2.0.6
vscode-objectscript|int|1.1.2-beta.3
language-server|int|1.2.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593cf:30376535
vsc1dst:30396469
vscexrecpromptt2:30397559

```

</details>

**Comment by MrAndersen1** [comment]
I ran into this issue as well, on insiders on mac (no extensions), but with a different, local, package with prebuilt binaries which were bundled into an extension I'm working on. When starting with said extension the developer-tools show the same message.
I couldn't figure out a workaround so I went back to regular VSCode. Hopefully this change doesn't make it into the regular VSCode from Insiders.

**Comment by AntonioMeireles** [comment]
same here. hit it when trying locally to get [back](https://github.com/bartosz-antosik/vscode-spellright/issues/459) vscode-spellright to the future :-)

**Comment by deepak1556** [comment]
Thanks for testing with insiders and catching the issue early on. Yes there is a change in architecture between `1.62.x` and `1.63-insiders` wrt to from which parent process we now launch the extension host. Previously we were launching the extension host from the renderer process and so it inherited the entitlements of this process which are basically https://github.com/microsoft/vscode/blob/main/build/azure-pipelines/darwin/helper-renderer-entitlements.plist. Now moving forward we now launch the extension host from the main process so the entitlements inherited are bit different https://github.com/microsoft/vscode/blob/main/build/azure-pipelines/darwin/app-entitlements.plist. The entitlement `com.apple.security.cs.disable-library-validation` from the renderer was previously helping unsigned native modules to be loaded which is not present in the main process which leads to the above error.

**Comment by IanMatthewHuff** [comment]
Verified. I was hitting this myself, and looks good in current builds.

**Comment by abdullah-saqer** [comment]
This issue caused by "some" VScode extensions.
