### ISSUE TITLE
Create directory on opening directory

### ISSUE THREAD

**Issue by strarsis** [microsoft/vscode#137386]
It would be great if a directory can be created while opening a directory.
Currently the user gets an error message that the specified directory doesn't exist.
Adding an action to quickly create that directory (and entering/selecting it) would be a nice timesaver.

**Comment by JacksonKearl** [comment]
I'm not sure what you mean here, is this the native OS's folder picker? A screen recording would help.

\gifPlease

**Comment by strarsis** [comment]
@JacksonKearl: Ah right. The WSL picker, not the native OS dialog.

**Comment by gjsjohnmurray** [comment]
Related to #137368

**Comment by alexr00** [comment]
Duplicate of #137368
