### ISSUE TITLE
Renderer Crash 139

### ISSUE THREAD

**Issue by jackokring** [microsoft/vscode#137308]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
1.62.2
3a6960b964327f0e3882ce18fcebd07ed191b316
x64

- OS Version:
Linux bramble 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Linux Mint

Steps to Reproduce:

1. launch code

code --verbose
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[9269:1116/144646.125985:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 2021-11-16T14:46:46.197Z] Starting VS Code
[main 2021-11-16T14:46:46.200Z] from: /usr/share/code/resources/app
[main 2021-11-16T14:46:46.200Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  'ms-enable-electron-run-as-node': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': '5001617b-e530-44bd-a54c-d962f54ac18a',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: '/home/jacko/.config/Code/logs/20211116T144646'
}
[main 2021-11-16T14:46:46.202Z] Resolving machine identifier...
[main 2021-11-16T14:46:46.202Z] Resolved machine identifier: 86fbef492b1e30283ff5ade7deacd70dda1e87d22bc17691186efa240f642d24
[main 2021-11-16T14:46:46.203Z] Main->SharedProcess#connect
[main 2021-11-16T14:46:46.225Z] StorageMainService: creating global storage
[main 2021-11-16T14:46:46.225Z] lifecycle (main): phase changed (value: 2)
[main 2021-11-16T14:46:46.226Z] windowsManager#open
[main 2021-11-16T14:46:46.226Z] windowsManager#open pathsToOpen [
  {
    backupPath: '/home/jacko/.config/Code/Backups/1637073771112',
    remoteAuthority: undefined
  }
]
[main 2021-11-16T14:46:46.228Z] IPC Object URL: Registered new channel vscode:f8194fca-6bb4-4edd-9ef0-2e465e2ecfc9.
[main 2021-11-16T14:46:46.228Z] window#validateWindowState: validating window state on 1 display(s) { mode: 1, x: 54, y: 102, width: 1024, height: 768 }
[main 2021-11-16T14:46:46.228Z] window#validateWindowState: 1 monitor working area { x: 0, y: 0, width: 1600, height: 870 }
[main 2021-11-16T14:46:46.229Z] window#ctor: using window state { mode: 1, x: 54, y: 102, width: 1024, height: 768 }
[main 2021-11-16T14:46:46.338Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 1, emptyToOpen: 0)
[main 2021-11-16T14:46:46.356Z] lifecycle (main): phase changed (value: 3)
[main 2021-11-16T14:46:46.356Z] update#setState idle
[main 2021-11-16T14:46:46.357Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[main 2021-11-16T14:46:46.543Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[9236:1116/144647.228112:INFO:CONSOLE(602)] "%cTRACE color: #888 Renderer->SharedProcess#connect", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (602)
[main 2021-11-16T14:46:47.251Z] StorageMainService: creating workspace storage (1637073771112)
[9236:1116/144647.295545:INFO:CONSOLE(602)] "%cTRACE color: #888 [lifecycle] starting up (startup kind: 1)", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (602)
[9236:1116/144647.301086:INFO:CONSOLE(602)] "%cTRACE color: #888 Skipping initializing user data in desktop", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (602)
/dev/fd/3: No such file or directory
Server response:
Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
[main 2021-11-16T14:46:48.828Z] CodeWindow: renderer process crashed (reason: crashed, code: 139)
[main 2021-11-16T14:46:51.210Z] IPC Object URL: Removed channel vscode:f8194fca-6bb4-4edd-9ef0-2e465e2ecfc9.
[main 2021-11-16T14:46:51.210Z] Lifecycle#window.on('closed') - window ID 1
[main 2021-11-16T14:46:51.211Z] Lifecycle#onWillShutdown.fire()
[main 2021-11-16T14:46:51.215Z] Lifecycle#app.on(window-all-closed)
[main 2021-11-16T14:46:51.216Z] Lifecycle#app.on(before-quit)
[main 2021-11-16T14:46:51.216Z] Lifecycle#onBeforeShutdown.fire()
[main 2021-11-16T14:46:51.217Z] [WindowsStateHandler] onBeforeShutdown {
  lastActiveWindow: {
    workspaceIdentifier: undefined,
    folder: undefined,
    backupPath: '/home/jacko/.config/Code/Backups/1637073771112',
    remoteAuthority: undefined,
    uiState: [Object: null prototype] {
      mode: 1,
      x: 54,
      y: 102,
      width: 1024,
      height: 768
    }
  },
  lastPluginDevelopmentHostWindow: undefined,
  openedWindows: []
}
[main 2021-11-16T14:46:51.217Z] Lifecycle#app.on(will-quit)
[main 2021-11-16T14:46:51.228Z] StorageMainService: closed workspace storage (1637073771112)
[main 2021-11-16T14:46:51.229Z] StorageMainService: closed global storage

**Comment by deepak1556** [comment]
Can you attach the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports

**Comment by sgk-000** [comment]
I have same issue on Ubuntu 20.04. Kernel version is 5.11.0-43-generic
