### ISSUE TITLE
FileSystemWatcher does not notice changes in UNC paths

### ISSUE THREAD

**Issue by dalle** [microsoft/vscode#137361]
When debugging an extension to VS Code (https://github.com/prettier/prettier-vscode) I saw that FileSystemWatcher does not notice changes in UNC paths.

### Environment
Version: 1.62.2 (user setup)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:56:38.428Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

### Steps to Reproduce

1. Start code from a UNC path, such as `\\wsl$\Ubuntu-20.04\home\dalle\vscode`.
2. Use `workspace.createFileSystemWatcher('**/package.json')`, combined with `onDidChange` to listen changes to any package.json file in the workspace.
3. Modify and save any package.json file in the workspace.
4. Notice that the callback registered in the `onDidChange` was not called.

**Comment by bpasero** [comment]
https://github.com/microsoft/WSL/issues/7674
