### ISSUE TITLE
Make Hot Exit less confusing in conjunction with Git

### ISSUE THREAD

**Issue by anohren** [microsoft/vscode#137398]
First of all, the title only reflects my subjective experience, i.e. I think it's confusing and hard to wrap my head around. 

Here's the problem I've had:

1. Open a folder with Code that's also a Git repo. 
2. Make some small change to a file in Code, perhaps even by mistake. 
3. Close Code with Hot Exit enabled. 
4. Checkout another branch with external git tool (e.g. CLI)
5. Open Code again, and the entire file that was changed slightly and I forgot to save is now basically entirely the version of the file from the previous branch (?) in the editor, but not in the working directory. 

As you can see, I'm still not entirely sure that I've described the current Hot Exit behavior correctly, which I think is the problem I'm trying to illustrate: I'm unsure in this situation (but it was much worse before I was aware of the Hot Exit feature). VSCode now shows lots of errors from changes I can't remember having made in the current branch, but with external tools the code compiles just fine and git shows no diff. 

Also, when this happens (I forget to save, or accidentally make an edit) and Code is still running when I switch branch, it once again seems like I'm unintentionally "transferring" the entire unsaved file between branches and get lots of errors in the editor. It's nice that edits aren't lost, but I feel lost instead. 

The big problem with this I think is that I don't get notified the original of the edited file was swapped out on disk but not in the editor (even when Code is running). 

I don't know if this can be improved in any way, but I'm opening it as a request in case it makes sense. I think I would appreciate if the editor told me that "the original of this unsaved file has been changed on disk" both when restoring the unsaved version upon launching Code, as well as while the unsaved file is being edited while the original file is swapped out. That way I can go "oh yes, I just checked out another branch — whatever changes I made and didn't save weren't important; reload file from disk please". 

Does this make sense, or did I miss something? I am a bit tired while writing, so feel free to point it out.

**Comment by bpasero** [comment]
//cc @Tyriar

**Comment by anohren** [comment]
Sorry but I don't understand this voting system. 

Is every request guaranteed to be considered by more than 20 people before being closed? Or is the system's purpose to disguise a desire to be able to close feature requests even if they've received zero consideration by anyone?

Am I as an end user with a feature request expected to run an individual ad campaign in order to funnel at least the minimum required number of eyeballs into the issue? Because I can't seem to find any indication of how many, if any, people have considered or read the rationale 50 days after posting it. I think this would be useful to know the answer to these questions so that potential requestors can decide whether it's worth the energy to type a request for something that might not even be read. 

How is this system beneficial compared to, say, having a designer consider a request and conclude whether it makes sense in context of the product?

Well, like I said, I don't understand the system, only that it seems a bit pointless to write things that simply by chance aren't going to be read.

**Comment by Tyriar** [comment]
@anohren it's a mechanism to deal with the huge amount of issues we get to weed out the ones that don't matter and save us some time. If the issue gets 20 votes in 60 days, which does happen organically sometimes, it's worth considering. Also, you could argue that going out and petitioning your followers or something like that is gaming the system. But still, this is not a guarantee that it would happen, just that we would use that as an additional signal for prioritization.

Your ask is to detect and handle an edge case when you checkout a folder via an external tool and then have a window open that has changes in affected files. It's a pretty niche request imo as you can easily workaround it by just closing your files, if you saved a file accidentally you can easily do a `git checkout` to clear it. The fix will probably take much more effort than it's worth, unless we underestimated how much people want it which is where the votes come in.

> How is this system beneficial compared to, say, having a designer consider a request and conclude whether it makes sense in context of the product?

You would have to pay the engineer/designer to consider it, and that time is taken away from working on other things.

**Comment by anohren** [comment]
Thanks for your reply @Tyriar. 

> If the issue gets 20 votes in 60 days, which does happen organically sometimes, it's worth considering.

That sounds like a good indicator for something that might be worth the effort, however what confused me about the system was kind of the opposite: how the absence of such votes are a good indicator for not considering something, which is how I understood it. Though looking at the issue number I see your point about the huge number of issues. 

Thanks for the feedback on this particular request. Although the problem described might happen — as you say — while a window is open, the bigger problem is that it happens when the application isn't running (hence the focus on Hot Exit) and that this creates confusion. When I'm confused about what's going on, I can't reasonably be expected to figure out a workaround the way you suggest, since at that point I'm just witnessing inexplicable behavior. 

If you manage to figure it out then yes, it's easy to work around, but that was never the problem; the confusion was the problem. Hot Exit + Git + closed VSCode = confusion when opening VSCode the next time. 

I'm not sure whether you intended to close the issue, but since I doubt even 20 people will look at it in the next 7 days I guess it doesn't matter.

**Comment by Tyriar** [comment]
Thanks for the feedback 👍

Yeah I closed as it wouldn't hit 20 so no point keeping it open.
