### ISSUE TITLE
Drag style isn't applied to markdown cells

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#137399]
- Drag a code cell, see the dragged cell becomes a little grayed out
- Drag a markdown cell, see no change in style

From https://github.com/microsoft/vscode/issues/131808#issuecomment-971101909

**Comment by roblourens** [comment]
Can't just use cell decorations because if you start dragging in the webview, the code that adds DRAGGING_CLASS is not running, it's different code in the webview that drives the dragging.

**Comment by amunger** [comment]
It looks like the cell does go partially transparent when being moved, as intended, but I don't see a difference with the stable version. Is that expected?
