### ISSUE TITLE
Cannot detect tsconfig or jsconfig in workspace folder

### ISSUE THREAD

**Issue by mahdi-farnia** [microsoft/vscode#137349]
Issue Type: <b>Bug</b>

I tried these and i faced same issue that i mentiond in title:
```
$ tsc --init
```
```
$ touch tsconfig.json
```
This issue cause a problem in intellisensing typescript files:
> Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.ts(1219)

Even i set ```"experimentalDecorator": true``` in both tsconfig.json and jsconfig.json

I know this bug does not affect the typescript compiler but too annoying...

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.23GB free)|
|Process Argv|--crash-reporter-id 3abd098e-8913-45d9-9e68-58217d58edc2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.7
solargraph|cas|0.23.0
npm-intellisense|chr|1.4.0
vscode-svgviewer|css|2.0.0
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.1
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
auto-rename-tag|for|0.1.9
better-cpp-syntax|jef|1.15.10
dotenv|mik|1.0.1
ruby|reb|0.28.1
sass-indented|syl|1.8.18
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.7.0
vscode-todo-highlight|way|1.0.5
vscode-ruby|win|0.28.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by mjbvz** [comment]
Please share an example project that demonstrates the issue
