### ISSUE TITLE
Stop sending output contents to the extension host

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#13736]
Since we are using an editor for the output, every thing that is added here is being sent over to the extension host process side. If you have an extension producing tons of output you basically put the extension host under DDOS attack both ways (extension sending to renderer, renderer sending back to extension host).

I do not see a use case for having the model of the output sent over to the extension host. 

@alexandrudima @jrieken can you see a reason why we would want this? Is there a way to prevent sending over data to the extension host?

I believe this is similar to the debug console that is using an editor too.

@isidorn we should look into this for October.

**Comment by jrieken** [comment]
I see the challenge but I know of extensions that make use of the output-document - like rendering links, adding decorations, etc. There are also request to enrich this, such that when creating an output channel we allow to define the language such that more *language* features can be enabled for this. 

In short, I am 👎 on just blocking but we should be somehow less aggressive. Tho unsure how...

**Comment by bpasero** [comment]
I was not aware of extensions contributing to the output channel. If this is an area where we want to allow extensions then I agree we cannot just block it.

**Comment by jrieken** [comment]
Yeah - I think it's pretty cool what they do (https://github.com/Microsoft/vscode/issues/11005, https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner, https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer) and we should keep allowing that.

**Comment by bpasero** [comment]
@jrieken I was aware of extensions that override/contribute colorization for output and my understanding is that if we stop sending output to the extension host we would still support colorization. 

If an extension wants to add more to output based on the content of output, then we need to continue sending output over but I am not sure if such an extension exists today or is planned.

**Comment by jrieken** [comment]
Fair point - @ArtemGovorov regarding #11005. Is this about colorisation or also about adding things like link detection, and other [`languages`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3887)-features.

**Comment by bpasero** [comment]
Does this require access to the output content?

**Comment by ArtemGovorov** [comment]
We do access the passed document content (not sure if that's what you're asking about though):

```javascript
vscode.languages.registerDocumentLinkProvider({language: 'wallaby-output'}, {
        provideDocumentLinks: doc => {
          const textLine = doc.lineAt(0);
          ...
        }
});
```

However, we only need to access it because of the [current limitation](https://github.com/Microsoft/vscode/issues/11005) - when using the text/x-code-output mime type, the languages and its grammar gets applied to **all** output channels, so we have to access the document content to make sure we are not providing the links for some other output channel.

**Comment by bpasero** [comment]
Ok thanks.
