### ISSUE TITLE
Save backup files to different folder

### ISSUE THREAD

**Issue by boyvinall** [Microsoft/vscode#13738]
One feature I used to love from Borland CodeWright was the ability to specify a folder where backup files would be saved.  It would take the entire path on the local disk to the current file and create that tree under a specified folder.

For example, if I'm working on `c:\apps\foo\bar.c` and I specified the backup folder to be `c:\backups` then  any file save of `bar.c` would place the previous version as `c:\backups\apps\foo\bar.c.bak`

Can be useful in situations where a working file tree is accidentally deleted, but also handy to keep the current working directory clean.

**Comment by bpasero** [comment]
This is related to hot-exit work, @Tyriar fyi

**Comment by Tyriar** [comment]
@boyvinall I'm currently working on a feature called hot exit #101 which will backup all dirty files in a workspace (clearing them out once they are no longer dirty). One of the final pieces of this work is to enable crash protection; if vscode crashes the backups are retained and restored on re-launch. These backups are currently stored in some backup folder but the idea is that the user won't need to seek them out as it will restore them seamlessly.

Would this in addition to the OS' recycling bin cover your use case? Files deleted through the explorer should end up in the bin unless <kbd>shift</kbd>+<kbd>delete</kbd> was used to delete them. There's always source control as well to help manage backups.

**Comment by boyvinall** [comment]
> There's always source control as well to help manage backups.

@Tyriar yes, I use git constantly 😄  but sometimes I don't checkin frequently enough, or I'll commit something locally and not push it.  Then if I suffer finger trouble in the morning and delete the folder (including local git repo) then I'm stuffed.  This is a "hardly ever" type use-case but, on those rare occasions, it can be extremely useful.

Perhaps what I'm after is an option on your hot exit work, where I can set it to not purge the backups, or possibly only delete them after they're a month or two old.

**Comment by Tyriar** [comment]
@boyvinall ah ok, I'd consider that another feature, let's just keep this open for now 😃

**Comment by Tyriar** [comment]
An extension could probably do something like this; listen for file changes and save them (after a delay) to some folder just in case. Perhaps distribute them by date changed and purge the older ones periodically? I don't see something like this making it into vscode to support such a infrequent use case.

**Comment by weeblr** [comment]
Hi

@Tyriar: In light of #329 and also https://github.com/Microsoft/vscode/issues/14638#issuecomment-267964108, I wonder **where** the hot exit feature is storing its files? would that be compatible with a portable usage of vscode? 

If vscode does NOT use the user data dir already (which is subject to the --user-data-dir CLI option), could there be a cli option to set a hot exit saving folder  when in portable mode?

If I exit vscode and hot exit saves all my (unsaved) files in a local folder no computer A, but next time vscode is fired (from a USB stick), it's on computer B, then hot exit will fail restoring.

Cheers

**Comment by Tyriar** [comment]
@weeblr hot exit stores everything inside `<userDataDir>/Backups` which already needed write permissions.
