### ISSUE TITLE
Settings Sync landing page image is missing

### ISSUE THREAD

**Issue by justingolden21** [microsoft/vscode#137345]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62
- OS Version: Windows 10

Steps to Reproduce:

1. Sign in using settings sync
2. 
![image](https://user-images.githubusercontent.com/30274440/142134331-af5707f8-5668-4897-9a53-f2e530b52b0d.png)

**Comment by gjsjohnmurray** [comment]
Is this a settings sync extension that you have installed, or the built-in Settings Sync feature?

**Comment by sandy081** [comment]
Yes this is coming from Settings Sync extension, please file issue against that extension.
