### ISSUE TITLE
Unable to launch debugger worker process (vsdbg) through the terminal. 

### ISSUE THREAD

**Issue by wernerkellens** [microsoft/vscode#137362]
1. Create a launch.json
2. Create a dotnet configuration like this one
        {
            "name": "ClientUI",
            "type": "coreclr",
            "request": "launch",
            "program": "${workspaceFolder}/ClientUI/bin/Debug/netcoreapp3.1/ClientUI.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "console": "externalTerminal",
            "stopAtEntry": false
        },
3. make sure "externalTerminal" is selected
4. Run/debug the this configuration

**Result**
Unable to launch debugger worker process (vsdbg) through the terminal. /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/externalTerminal/node/TerminalHelper.scpt:0:13: script error: A real number can’t go after this identifier. (-2740)

**Expected result**
Open a Terminal and run the application

VS Code version: Code 1.62.2 (Universal) (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|--crash-reporter-id eb2829b6-7eda-4c6d-9777-9f71ac3891bf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.16
remote-containers|ms-|0.205.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246cf:30386378
vscexrecpromptt1:30400061

```

</details>

**Comment by wernerkellens** [comment]
I've just did an extra test: I've created a new .NET Core 3.1 console application ('Hello World') and I got the same issue:

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/25681989/142207215-db27ed1f-0790-41f8-851f-95b0c5aee704.png">

**Comment by weinand** [comment]
Does it make a difference if you remove the "3.1" from the `netcoreapp3.1` folder (or replace it with a "3_1")?

**Comment by wernerkellens** [comment]
> Does it make a difference if you remove the "3.1" from the `netcoreapp3.1` folder (or replace it with a "3_1")?

No, it apparently doesn't matter what I set as value for the folder (empty, remove netcoreapp3.1). I looks like it throws the error before

**Comment by wernerkellens** [comment]
Today I got an update from Visual Studio Code

<img width="255" alt="image" src="https://user-images.githubusercontent.com/25681989/142595133-0df2e592-fcf1-4c14-8b4a-3ad71a6a0a71.png">

And now it appears to work 😮.

**Comment by weinand** [comment]
Great, thanks for letting us know.
