### ISSUE TITLE
Misleading error message about proposal APIs when attempting to use a feature of an extension

### ISSUE THREAD

**Issue by glektarssza** [microsoft/vscode#137365]
Does this issue occur when all extensions are disabled?: N/A

```
Version: 1.63.0-insider (system setup)
Commit: d450b04c783dfa6f83dc439017767acccd4e9fac
Date: 2021-11-17T05:21:29.351Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
```

Steps to Reproduce:

1. Install `ms-dotnettools.csharp`
2. Create a .NET project using `dotnet new classlib`
3. Attempt to select a project using the command `Omnisharp: Select Project`

Expected Results:
* Quick picker for selecting a project opens

Actual Results:
* An error notification appears with the following text, which is misleading/confusing as it says that the extension both does and does not use an proposal API:
```
Extension 'ms-dotnettools.csharp' CANNOT use API proposal: quickPickSeparators.
According to its package.json#enabledApiProposals-property it wants: <none>.
 You MUST start in extension development mode or use the following command line switch: --enable-proposed-api ms-dotnettools.csharp
```

Other Notes:
* Was working before the this morning's Insider's update
* Issue manifests in the following repository: https://github.com/glektarssza/sdl2-dotnet

**Comment by gjsjohnmurray** [comment]
See #136964 for details of migrating extensions which use proposed API.

**Comment by jrieken** [comment]
> which is misleading/confusing as it says that the extension both does and does not use an proposal API:

I see how it is misleading but the gist is that the extension doesn't name the proposal in its `package.json#enabledApiProposals`-property and therefore cannot use it
