### ISSUE TITLE
cant enable/disable extensions?

### ISSUE THREAD

**Issue by RSUIAutomation** [microsoft/vscode#137322]
Issue Type: <b>Bug</b>

Open extensions

Right click on any disabled extension

Ennable extension button is greyed out with no resolutions or mentions anywhere as to why 

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (7.16GB free)|
|Process Argv|--crash-reporter-id a82b0e89-f1b8-43ac-bd0f-5a1a8c7472ec|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.4.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
copilot|Git|1.6.3503
vscode-cfn-lint|kdd|0.20.1
vscode-docker|ms-|1.17.0
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.3
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.202.5
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.0
tabnine-vscode|Tab|3.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe start by updating to the current VS Code version, then retesting.

**Comment by sandy081** [comment]
Please update and try again as @gjsjohnmurray suggested
