### ISSUE TITLE
Bad coloring numbers in powserhell with Solarized Light

### ISSUE THREAD

**Issue by udirona** [microsoft/vscode#137449]
Issue Type: <b>Bug</b>

It is nearly impossible to read numbers in a powershell terminal with color theme Solarized Light.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by CodeCrazy-ywt** [comment]
Screenshot?

**Comment by udirona** [comment]
Here a Screenshot.

![terminal](https://user-images.githubusercontent.com/45492029/142585004-cca2aa32-90db-4a9a-aa64-8c940b440896.PNG)
