### ISSUE TITLE
error when creating Scaffold movie pages

### ISSUE THREAD

**Issue by dlappdev** [microsoft/vscode#137494]
Issue Type: <b>Bug</b>

dotnet-aspnet-codegenerator controller -name MoviesController -m Movie -dc MvcMovieContext --relativeFolderPath Controllers --useDefaultLayout --referenceScriptLibraries -sqlite

target dontnet 6 

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.32GB free)|
|Process Argv|-psn_0_2753184 --crash-reporter-id 05795b1a-cff0-47f7-ad05-e0e4c06c1fba|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
add-reference|adr|1.0.2
asp-net-core-switcher|adr|2.0.2
blazor-snippet-pack|adr|2.6.1
csharp-to-typescript|adr|1.12.1
libman|adr|1.0.1
namespace|adr|1.1.2
terminal-commands|adr|1.0.5
toggle-hidden|adr|1.0.2
user-secrets|adr|2.0.1
codeigniter-extension|als|0.0.5
ci-snippets2|Ani|1.0.1
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.2
gitignore|cod|0.7.0
supersharp|cra|0.1.4
vscode-markdownlint|Dav|0.45.0
jshint|dba|0.11.0
vscode-eslint|dba|2.2.2
netcore-extension-pack|dog|1.5.2
netcore-snippets|dog|3.15.2
quicktype-refresh|dog|0.1.1
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.23
dotnet|for|0.0.4
dotnet-test-explorer|for|0.7.7
fire-snippets|Gan|0.0.5
vscode-pull-request-github|Git|0.32.0
sentinel|has|0.0.3
beautify|Hoo|1.5.0
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.1.30
csharpextensions|kre|1.5.2
csharpfixformat|Leo|0.0.84
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.16
vscode-kubernetes-tools|ms-|1.3.4
remote-containers|ms-|0.205.2
atom-keybindings|ms-|3.0.9
debugger-for-chrome|msj|4.13.0
vscode-versionlens|pfl|1.0.9
quicktype|qui|12.0.46
java|red|1.0.0
vscode-yaml|red|1.2.0
aspnet-helper|sch|0.6.4
ci-snippets|sec|0.0.2
myci-extension|Set|0.0.3
php-ci|sma|0.4.2
reveal|smu|1.2.7
cacherelationship|Swi|0.0.5
msbuild-project-tools|tin|0.3.15
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
CodeIgniter-extension-pack|wal|1.0.0
vscode-todo-highlight|way|1.0.5
vscode-proto3|zxh|0.5.5

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please specify how this issue is related to VS Code editor itself.
