### ISSUE TITLE
"Cannot compare files because one file is too large."

### ISSUE THREAD

**Issue by bzaar** [microsoft/vscode#137479]
Seeing the above message when diffing two versions of a large file. Apparently, there is a limit which is hard-coded (duh!) and set to 50 MB:

https://github.com/microsoft/vscode/blob/11479ca7596c8f3404316e2c353324e8e545bf37/src/vs/editor/common/model/textModel.ts#L191

What I would like to see instead is VS Code doing as much as it can with my hardware, and if the diffing is taking too long, present an option to cancel it. If there is not enough memory, say so and display a partial diff.

Also see #105797.

Please give it a thumbs-up below if you like this feature request. It needs 20 upvotes before 23 Jan 2022 to ever see the light of day.

**Comment by bzaar** [comment]
@roblourens, thank you for looking an this suggestion. Does the assignment mean that this issue is being worked on? No discussions, no designs?

**Comment by roblourens** [comment]
It means that I assigned it to the person who owns this area to look at

**Comment by alexdima** [comment]
This is something that can be configured using `"diffEditor.maxFileSize"`, which is a number expressed in MB.
