### ISSUE TITLE
[json] always add a trailing comma when adding a property to avoid multiple line changes

### ISSUE THREAD

**Issue by Zocker1999NET** [microsoft/vscode#137469]
Currently, if you use the workspace settings UI to edit the `.vscode/settings.json` of a workspace, if it appends a new key, it requires to not only add a new line but also add a comma to the line before. This then shows in git as editing two lines, including changing a line which has nothing to do with the current change.

This would vastly improve git diffs and make commits more robust.

### before edit
```json
{
  "first": "val",
  "second": "val"
}
```

### after edit
```json
{
  "first": "val",
  "second": "val",
  "third": "val"
}
```
### diff
```diff
 {
   "first": "val",
-  "second": "val"
+  "second": "val",
+  "third": "val"
 }
```

### before edit
```json
{
  "first": "val",
  "second": "val",
}
```

### after edit
```json
{
  "first": "val",
  "second": "val",
  "third": "val",
}
```
### diff
```diff
 {
   "first": "val",
   "second": "val",
+  "third": "val",
 }
```

**Comment by aeschli** [comment]
What exctly do you want to be improved? The way the diff editor shows a change? Or git diff?

**Comment by Zocker1999NET** [comment]
Sorry, my explanation was probably not the best. It's not about how VS Code displays anything but about how VS Code manages its `.vscode/settings.json` file, which most probably is tracked by a git repository.

What I wish is that if I edit a setting in the settings editor UI, then Visual Studio Code should append trailing commas to every entry of `.vscode/settings.json`, so that git only registers one changed line per changed setting.

## Step-By-Step of current state

1. Have following settings.json in a workspace directory: 
![image](https://user-images.githubusercontent.com/1645646/142690521-0a2876a3-39d4-4e70-afbc-5602c3387c1c.png)

2. Choose a setting in the UI, e.g.:
![image](https://user-images.githubusercontent.com/1645646/142690570-df552169-3f78-4448-933b-6168b6126c6c.png)

3. Change it (for the workspace):
![image](https://user-images.githubusercontent.com/1645646/142690627-b47af5b6-b9e1-4093-bdc8-eca25819ab22.png)

4. View modified settings.json:
![image](https://user-images.githubusercontent.com/1645646/142690690-9555a046-0b3d-4699-a408-e8aa432ee69b.png)

## My request

Because Visual Studio Code omits trailing commas (which are unfortunately not valid in JSON per se), the diff in a git repository now looks like this:
![image](https://user-images.githubusercontent.com/1645646/142690944-7c3ac884-1f67-4186-afb8-ca46b879d146.png)

VS Code had to change the former line to append a new setting. But this leads git into thinking, that

However, if VS Code would add additional trailing commas to its entries, the diff generated by git would make more sense and improve the usage of features like git blame and etc.

## Step-By-Step of hopeful future state

1. Have settings.json with trailing commas:
![image](https://user-images.githubusercontent.com/1645646/142691473-cae0d4b0-48ca-40ad-9e46-786e09e40db7.png)

2. Choose & change a setting as above

3. View modified settings.json and the git diff:
![image](https://user-images.githubusercontent.com/1645646/142691537-832ffc52-58ce-49ec-bd43-5c56de850c2d.png)
![image](https://user-images.githubusercontent.com/1645646/142691585-d58c52e6-6241-4139-a833-a93926d46300.png)

**Comment by aeschli** [comment]
Thanks for the explanation, now I understand. I updated the issue title.
