### ISSUE TITLE
Why do we have to specify ES5/ES6 target?

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#1374]
This isn't strictly an issue, but a colleague of mine said he didn't understand why it was necessary to specify an ES target.

He said he started using arrow functions and let statements and the editor underlined them in red stating that if he wants to use ES6 then he should set the target in his jsconfig file to ES6. He said if the editor was smart enough to give a descriptive error message, then it should be smart enough to automatically use ES6.

So that brings me to the question. Why do we have to explicitly specify ES5/ES6 target? I am aware that WebStorm also requires you to set ES6 for the project, and I am aware that code completion etc is provided by a modern modular compiler, and being a compiler it needs to know what language version you want to work on. But I still wanted to know if you could comment further on this.

**Comment by louy** [comment]
I believe it's for the same reason we use `lint` programs. To make sure no one breaks anything.
This is super helpful in case you are working on multiple projects with different targets. It's like a safety check to make sure that you (or anyone else) won't break anything by accident.

**Comment by dbaeumer** [comment]
@jrieken we changed this for December. Right?

**Comment by louy** [comment]
@dbaeumer  I don't think this is about why "es6" isn't the default target, if that's what you mean. It's more about why doesn't vscode predicts which version of js is being used automatically.

**Comment by louy** [comment]
@massimocode furthermore, it's not possible to find out which version is being used just by analysing a file. All ES5 code is valid ES6, but not vice versa, so an ES6 file might be incorrectly flagged as an ES5 one if it doesn't use any features of ES6.

**Comment by jrieken** [comment]
yes, the new default is ES6. if your target platform doesn't support ES6 (think of old browser etc) set the option to be notified when you stuff that isn't supported.
