### ISSUE TITLE
Opening folder closes the opened files.

### ISSUE THREAD

**Issue by ravitejapavuluri** [microsoft/vscode#137414]
Issue Type: <b>Bug</b>

steps to reproduce:
Open VSCode and open any few code files from your local machine.
Now go to explorer and open any folder.

expected:
all open files should remain open and folder also should open.
what actually happens:
all open files are closed and explorer opens a folder in the left pane.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:51:30.084Z)
OS version: Linux x64 5.11.0-40-generic snap
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1045-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1891)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (7.48GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id c923c656-5d69-4b3c-b6a6-a0d2bc6a4c89|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|

|Item|Value|
|---|---|
|Remote|SSH: athena|
|OS|Linux x64 5.4.0-1045-aws|
|CPUs|AMD EPYC 7571 (16 x 2537)|
|Memory (System)|61.71GB (4.59GB free)|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
Does https://github.com/microsoft/vscode/issues/79167#issuecomment-521774261 match what you are doing?

**Comment by gjsjohnmurray** [comment]
@JacksonKearl maybe we should enhance the "NO FOLDER OPENED" assistance to be more helpful in this case. I prototyped this:

![image](https://user-images.githubusercontent.com/6726799/142394241-675c0f86-a70b-45a1-94ad-9e792966d8be.png)

Or a less heavyweight alternative:

![image](https://user-images.githubusercontent.com/6726799/142396924-4aa38c4d-c1ed-4c6f-8551-db4f2aff2867.png)

It uses the 'editorIsOpen' context key to add the extra text and the second command button. Only snag so far is that the context key is also true when non-text editors such as "Get Started" or "Settings" are open, as you'll see in my second screenshot above. I haven't found a context key that will avoid this.

Let me know if you'd like a PR from me.

**Comment by JacksonKearl** [comment]
I like that second lighterweight version, cc @digitarald as he has been doing some investigations in the welcome views

**Comment by digitarald** [comment]
Second version looks good.

_Add Folder_ does behave a bit odd as it creates a multi-folder workspace and asks to save workspace config on close. As alternative solution: What about not closing loose files when a folder is opened? VS Code allows opening loose file when a folder is open as well, so why close them?

**Comment by gjsjohnmurray** [comment]
@JacksonKearl @digitarald thanks for the feedback. I have submitted a PR implementing the second version.

**Comment by JacksonKearl** [comment]
> What about not closing loose files when a folder is opened? VS Code allows opening loose file when a folder is open as well, so why close them?

I'd like this too, cc @bpasero is this possible? It's always felt a bit odd that we make folks save their buffers before opening a folder, but I get that there's a lot of working copy logic going on behind the scenes. 
![image](https://user-images.githubusercontent.com/8586769/142668023-116a9bd0-9a63-4e11-bce3-5cd8e599ee3c.png)

**Comment by bpasero** [comment]
I think this goes a little bit into the direction of being able to switch workspaces without that window reload we do. Ideally opening a folder would just add it to the explorer when previously the workbench was empty and then probably all view state is preserved. The interesting question is what should happen with the editors that were previously opened in that folder you now open? Should all editors merge?

We have an issue for that but I cannot find it.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/35109

**Comment by JacksonKearl** [comment]
Changed the explorer welcome view to be more explicit about this behaviour and provide a workaround. Thanks @gjsjohnmurray
