### ISSUE TITLE
Be able to add context menus after installation too

### ISSUE THREAD

**Issue by CyberRex0** [microsoft/vscode#137491]
I'm experienced deleted vscode's context menus suddenly after update Windows 10 21H2. 
I had to re-install. 
I am solved this problem, however, reinstalling it was time-consuming.

So I want you to be able to add context menus after installation.
This means that users who did not choose the setting to add a context menu during installation can easily configure it.

Since it is possible that VSCode is not the cause of this issue, i have changed the type of this Issue to Feature Request.

**Comment by gjsjohnmurray** [comment]
Previously requested at #33125 but ultimately closed as out-of-scope.

**Comment by joaomoreno** [comment]
Thanks @gjsjohnmurray. Closing it as a duplicate.
