### ISSUE TITLE
Files don't show in some projects

### ISSUE THREAD

**Issue by arudp** [microsoft/vscode#137439]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.2
- OS Version: Ubuntu 20.04.3 LTS

Steps to Reproduce:

1. Open up a project.
2. Try to find some file either from command palete with `ctrl+p` or with the explorer.
3. Verify files are there using the system explorer/terminal/whatever other tool.

My guess is that at some point VSCode had some issues with Git versions? It's happening in all of my projects from a couple of versions back, but I thought it might be fixed already. I'm not seeing that there are more complaints about this so I wonder if this is only happening to me and if there might be some weird caching somewhere involved that won't let VSCode refresh disk contents if not already indexed?

Sorry for not being able to give more info, you guys are doing a great job!

**Comment by JacksonKearl** [comment]
Could you give an example of what files don't show? It's expected that git ignored and `search.exclude`'d/`files.exclude`'d files don't appear.

**Comment by arudp** [comment]
![vscode-no-files](https://user-images.githubusercontent.com/44339057/143027573-ca004933-8631-4dae-afaa-0b392403f28f.png)

As you can see both the terminal and the Git extension can find the file `image_path_builder.py`. Of course if I do `code ${file}` it will open the file, but I can't open it from the explorer, command palette or include it in searches. This file is of course not excluded as it's a normal python file.

**Comment by arudp** [comment]
This is something that jus happens when I pull new changes and it started happening a couple of versions back

**Comment by JacksonKearl** [comment]
do you have `files.exclude` configured in either a local settings.json file or your global settings?

**Comment by arudp** [comment]
So sorry, I stubbornly thought that that couldn't be it and I see that it just happens that at least in this specific case that happened. I have no way to see if the other instances where it happened it fell under this coincidence, but I'm guessing that's it :facepalm: 

As you guessed one of the excluded expressions was `"**/storage/**/*": true,`.

Very sorry for the inconvenience and keep up the great work!

**Comment by JacksonKearl** [comment]
No worries, I'm glad we figured it out :)
