### ISSUE TITLE
Search methods by name in the focused file only

### ISSUE THREAD

**Issue by pa0694** [microsoft/vscode#137434]
It would be useful to search a method by its name _in the editor focused file only_ with a contextual box like the CTRL+T or CTRL+P shortcut.
CTRL+T search for the methods in all the project, which is useful, but not in all case.

**Comment by KristjanTammekivi** [comment]
ctrl+R

**Comment by pa0694** [comment]
> 
> 
> ctrl+R

In my VScode, CTLR+R opens a menu for workspace selection

**Comment by pa0694** [comment]
Well I figured that CTRL+shift+/ does the trick
sorry for inconvenience

**Comment by KristjanTammekivi** [comment]
Ah my bad, I'm using Sublime Text keymap out of habit, glad you found it though
