### ISSUE TITLE
VS Code hangs when clicking on "Open Folder"

### ISSUE THREAD

**Issue by vidhyasagarreddy** [microsoft/vscode#137440]
Issue Type: <b>Bug</b>

Open VS code
Explorer window > No Folder Opened section > "Open Folder"

VS Code version: Code - Insiders 1.63.0-insider (d450b04c783dfa6f83dc439017767acccd4e9fac, 2021-11-17T05:21:29.351Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.66GB (18.94GB free)|
|Process Argv|--crash-reporter-id f843d11f-45aa-459c-88f1-e2c0ae8fca01|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.6.1
vscode-docker|ms-|1.18.0
dotnet-interactive-vscode|ms-|1.0.2567061
vscode-dotnet-runtime|ms-|1.4.0
jupyter|ms-|2021.11.1001475629
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.206.0
remote-wsl|ms-|0.63.2
vscode-node-azure-pack|ms-|0.2.1
java|red|1.0.0
vscode-xml|red|0.18.1
vscode-yaml|red|1.2.0
vscode-scss-formatter|sib|2.3.2
vscodeintellicode|Vis|1.2.14
vscode-maven|vsc|0.34.1
vscode-icons|vsc|11.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593cf:30376535
vsc1dst:30396469
vscexrecpromptt3:30397560

```

</details>

**Comment by gjsjohnmurray** [comment]
Does this also happen after you run the Command palette command "Developer: Reload with Extensions Disabled"?

It doesn't repro for me. The Open Folder button correctly opens the Windows native "Open Folder" dialog.

My Insiders is today's, whereas yours is yesterday's.

Did this previously work for you?

Does "Open Folder..." off the File menu give the same result?

**Comment by vidhyasagarreddy** [comment]
@gjsjohnmurray - I haven't tried this with disabling extensions. I can do that in sometime and let you know how it behaves. Will also try "Open Folder" from File.
And yes, it worked fine in previous builds.

**Comment by JacksonKearl** [comment]
@vidhyasagarreddy yes can you please check in the latest insiders, and with extensions disabled? I haven't seen other reports of this.

**Comment by vidhyasagarreddy** [comment]
Faced this issue again today, on latest insiders build. 

**Steps**:
1. Opened some random File(s) via VS Code
2. Worked on them. Some were "Saved" and some were "Not Saved"
3. After couple of minutes, I clicked on "Open Folder", which then had stuck

**VS Code details:**
Version: 1.63.0-insider (system setup)
Commit: bedf867b5b02c1c800fbaf4d6ce09cefbafa1592
Date: 2021-11-18T05:14:59.750Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by vidhyasagarreddy** [comment]
I will try to open w/o extensions nxt time when I try
