### ISSUE TITLE
Auto imported file path is wrong (absolute vs relative) and raises error at runtime

### ISSUE THREAD

**Issue by DavideViolante** [microsoft/vscode#137446]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.2
- OS Version: Ubuntu 20.03

Steps to Reproduce:

1. I've a TypeScript project with the following folders: `server/validators/*` and `server/shared/*`
2. When I try to automatically import something from `server/shared/constants.ts` to `server/validators/file.ts` the import string is:
3.  `import { usernameRegexp } from 'shared/constants';` that gives me an error because the correct path should be:
4. `import { usernameRegexp } from '../shared/constants';` 

Short vid of what I mean with autoimport:

https://user-images.githubusercontent.com/6844116/142427865-3c08218a-6283-408a-b6d4-9af2fa516a7f.mp4

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you have these folders in `paths` in `tsconfig.json`?
Please provide used configuration

**Comment by DavideViolante** [comment]
I don't have any `paths` configured in tsconfig. I tried some configs of paths but without luck. Example:
```json
"baseUrl": "",
  "paths": {
    "shared/*": ["shared/*"]
  },
```

But anyway I would like any folder to import correctly, shared is just an example.

tsconfig is the [same as this](https://github.com/DavideViolante/Angular-Full-Stack/blob/master/server/tsconfig.json). Also the project strucure is very similar to that repo.

**Comment by mjbvz** [comment]
Please share a minimal example project that demonstrates the issue

**Comment by DavideViolante** [comment]
Ok I found that it happens in the parent project too, so you can repro with this:
1. `git clone git@github.com:DavideViolante/Angular-Full-Stack.git`
2. Open the project in VS Code
3. Edit controllers/cat.ts, delete line 1
4. Auto import Cat using suggested action by VS Code
5. Line added in the top file will be `import Cat from 'models/cat';` instead of `import Cat from '../models/cat';`
6. `npm run predev`
7. `npm start`
8. `Error: Cannot find module 'models/cat'`

**Comment by mjbvz** [comment]
Have you tried configuring `"typescript.preferences.importModuleSpecifier": "relative"`?

**Comment by DavideViolante** [comment]
> Have you tried configuring `"typescript.preferences.importModuleSpecifier": "relative"`?

This works! I didn't know about this config. I wonder now if `relative` should be the default one or not, but I don't have enough knowledge to give credit to either cases.

**Comment by mjbvz** [comment]
Thanks for testing! Closing as by-design / question

The type of the path used by default depends on your jsconfig / tsconfig. Try changing it something like `es2020` if you don't want node style paths by be allowed 

The setting then offers more fine grained control over which path style is selected
