### ISSUE TITLE
Dim backgound of non-focused editors

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#137476]
Issue Type: <b>Feature Request</b>

This would need a change in VS Code itself to be done right (can't be just an extension), since it would require each theme to have a dimmed-background color variable.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by bpasero** [comment]
//cc @misolori

**Comment by misolori** [comment]
This would be interesting:

<img width="1210" alt="CleanShot 2021-11-19 at 10 47 31@2x" src="https://user-images.githubusercontent.com/35271042/142675443-f8d6192d-c6f6-4341-bba2-630417a2dcb4.png">

**Comment by sdegutis** [comment]
Oh wait, maybe this wouldn't need new colors, just `opacity /= 2` or something.

**Comment by sdegutis** [comment]
Similar thing for Emacs https://github.com/mina86/auto-dim-other-buffers.el that I made this in 2013 to show a basic idea of what I had in mind. But your sshot looks better: it'd be nicer if foreground colors were dimmed instead. (Hence opacity idea. Should even work with "unused vars" if it's `opacity/N`.)

**Comment by misolori** [comment]
I think opacity might be the simpler option, but it might also require some more work like possibly hiding the current line in other editors.

iTerm also does a similar thing:

<img width="650" alt="CleanShot 2021-11-19 at 12 16 28@2x" src="https://user-images.githubusercontent.com/35271042/142686223-10499afa-804c-4808-ab16-a3f6b4df8ee5.png">

**Comment by sdegutis** [comment]
Also worth considering an overlay with bg = #0002 or #fff2 as alternative implementation.

**Comment by sdegutis** [comment]
Btw I don't know anyone, have no twitter, and have no ability to raise upvotes, so if you guys want to tweet this or whatever, feel free, otherwise I expect it will auto-close due to "no interest".
