### ISSUE TITLE
we need url lists of marketplace

### ISSUE THREAD

**Issue by taronlee** [microsoft/vscode#137404]
Hello.
for security issue, we have to use proxy in our environment.

so in order to download extension from marketplace,
we need `proxy exception request`.

please let us know the url lists of marketplace.

>13.107.6.175
>marketplace.visualstudio.com
>ms-vscode.gallery.vsassets.io

**need more?**

when we got an extension,
some people requests `marketplace.visualstudio.com`,
another requests `ms-vscode.gallery.vsassets.io`.

**Comment by taronlee** [comment]
+ `dc.services.visualstudio.com`

**Comment by taronlee** [comment]
\+default.exp-tas.com
\+dc.services.visualstudio.com

**Comment by taronlee** [comment]
External access is blocked by default.
so we need all the lists.

**Comment by joaomoreno** [comment]
https://code.visualstudio.com/docs/setup/network#_common-hostnames

**Comment by taronlee** [comment]
`default.exp-tas.com`
`dc.services.visualstudio.com`

those url doesn't need ??
so why they are blocked ??

**Comment by joaomoreno** [comment]
Adding @sbatten so he adds `default.exp-tas.com` to the docs.

I'm not sure what `dc.services.visualstudio.com` is used for. @taronlee Can you show me an example request to this endpoint?

**Comment by taronlee** [comment]
>Can you show me an example request to this endpoint?
>>we just run the command `code --install-extension ms-vscode.cpptools`.
>>you mean the request header?

after proxy exception request about https://github.com/microsoft/vscode/issues/137404#issuecomment-974093652,
our security team still say `default.exp-tas.com` and `dc.services.visualstudio.com` are blocked..

Then, after only `default.exp-tas.com` request proxy exception,
I will test it again.

**Comment by sbatten** [comment]
added tas to docs
