### ISSUE TITLE
Scrolling problems in Surface Pro 4 touchpad

### ISSUE THREAD

**Issue by papmodern** [Microsoft/vscode#13749]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: aeschli.vscode-css-formatter-0.0.2, akamud.vscode-theme-onedark-0.2.7, christian-kohler.npm-intellisense-0.1.3, hbenl.vscode-firefox-debug-0.6.6, iradul.debugger-for-phantomjs-0.0.2, johnpapa.Angular2-1.0.2, mrmlnc.vscode-pugbeautify-1.0.2, msjsdiag.debugger-for-chrome-1.1.0, msjsdiag.debugger-for-edge-0.4.1, UVBrain.Angular2-0.3.5, web-dave.ng2-dg-0.0.3, zhuangtongfa.Material-theme-1.0.3

Steps to Reproduce:

1. Open a long code file
2. Try to scrolling with touchpad :)))

**Comment by isidorn** [comment]
Dup of #12637
