### ISSUE TITLE
Breakpoint Indicator Is Missing For Active Line

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#137436]
![recording](https://user-images.githubusercontent.com/2931520/142404819-f115f2f0-2688-4f06-8b28-707b39bd365a.gif)

It could be that I caused this, but I doubt it (injected text has nothing to do with the gutter, maybe they shared a CSS rule).

**Comment by weinand** [comment]
I can reproduce but I'm not aware of any changes in that area from debug.

**Comment by mamphis** [comment]
@weinand @roblourens 
I would like to work on this issue!

**Comment by weinand** [comment]
Before fixing anything we should do a "git bisect" to find the commit that broke this.

**Comment by mamphis** [comment]
@roblourens @weinand 

commit 49efe65bc3769cff56182bfd5ce881fa4654ca6a.
it should fix #136824

**Comment by hediet** [comment]
@mamphis thanks for pointing out the commit! If you like, you can provide a PR, that would be awesome!

**Comment by mamphis** [comment]
@hediet PR #137471
