### ISSUE TITLE
M1 Mac Emmet issue

### ISSUE THREAD

**Issue by arvobrendon** [microsoft/vscode#137485]
Mac os M1 Mac monstery

Having trouble using Emmet 
![IMG_20211118_190612](https://user-images.githubusercontent.com/59163547/142558011-300b2ae0-27c7-4c62-846d-6bf6b42c02ba.jpg)
![16372910761661164814976319255683](https://user-images.githubusercontent.com/59163547/142558062-c2ddf862-b824-410f-aee7-ba46456097ff.jpg)

**Comment by gjsjohnmurray** [comment]
/gifPlease

Screenshots from a phone camera are suboptimal.

See https://github.com/microsoft/vscode/issues/137012 in case this applies to you. I can't tell if it does, since you haven't stated your VS Code version. 

/needsMoreInfo
