### ISSUE TITLE
"Learn More" link about Partial Mode uses a faulty anchor fragment

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#137462]
Issue Type: <b>Bug</b>

It goes to https://aka.ms/vscode/jsts/partial-mode which redirects to `https://code.visualstudio.com/docs/nodejs/working-with-javascript#partial-intellisense-mode`

However the right section is actually at `https://code.visualstudio.com/docs/nodejs/working-with-javascript#_partial-intellisense-mode`

(Note the leading underscore needed on the anchor)

Extension version: 0.0.42
VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by mjbvz** [comment]
Thanks for noticing this. Should be fixed now (just a service side update to the link so no code changes required)
