### ISSUE TITLE
Passwords are shown in terminal

### ISSUE THREAD

**Issue by bajosiaa** [microsoft/vscode#137474]
![image](https://user-images.githubusercontent.com/48413508/142494456-5f14eef7-c420-4982-b4bd-9b5de4690d7a.png)

- VS Code Version: I dont know but this happened in Sunday October 3, so you can find the latest version of the that day.
- OS Version: Windows 11
- Note: This happened when i fresh-install the vscode. There was only C# Omni extension afaik.

**Comment by gjsjohnmurray** [comment]
Maybe local echo? See #136063
