### ISSUE TITLE
RegExp variable-length lookbehinds only partially supported: Searching within a file is supported, but not with multiple files 

### ISSUE THREAD

**Issue by tommai78101** [microsoft/vscode#137456]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.2
- OS Version: Ubuntu 20.04.3 LTS

I have encountered a peculiar bug where you can do a regex variable-length lookbehind search in the File Search, but not in the other Search, as shown below (blacking out the middle, because it is showing personal and corporate info):

![image](https://user-images.githubusercontent.com/6444116/142446803-be13cebf-b0cb-4f53-a3a0-888a2b6f09ed.png)

Steps to Reproduce:

1. Open Visual Studio Code. 
2. Open any projects.
3. Do a CTRL+SHIFT+F to open the Search panel.
4. In the top text field, type the following: `(?<=.+)a`
5. Observe that you will get an error message, saying **Regex parse error: lookbehind assertion is not fixed length**.
6. In any file in the opened project, do CTRL+F to open the Search inset dialog.
7. In the text field, type the following: `(?<=.+)a`    (This should be the same regex search pattern as in Step 4.)
8. Observe that you can actually find tokens from this lookbehind regex pattern.

There should be some consistency between these search functionalities, and they both should be able to handle lookbehinds of variable length. If one of them can work with variable-length lookbehinds, why can't the other one do the same?

Hence, I feel the RegExp lookbehind searching is only partially supported in Visual Studio Code.

**Comment by roblourens** [comment]
There are two search implementations here, one in the editor using JS regexes, the other across the workspace using ripgrep which uses a different regex engine. Unfortunately there are some subtle differences in what they support, you found one of them. Nothing we can do about this right now, we won't search the workspace using JS because that's too slow.

**Comment by tommai78101** [comment]
Ah, that's what it is. Thanks for letting me know.
