### ISSUE TITLE
Settings Sync keeps reporting successive authorization failures

### ISSUE THREAD

**Issue by BradL-Msft** [microsoft/vscode#137477]
**
Issue Type: <b>Bug</b>

When I sign in it seems to work, but then an hour or two later I'll see a popup indicating Settings Sync has been disabled due to successive authorization failures.  

If I need to sign in every 2 hours (more or less), then settings sync is more trouble than it's worth.

VS Code version: Code - Insiders 1.63.0-insider (c1096372119bcf83b9bd8ccee96dcf266f35de76, 2021-11-11T13:18:41.690Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (17.06GB free)|
|Process Argv|--crash-reporter-id 2f3b771b-fd3e-4208-9190-23c3b96edf17|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
git-graph|mhu|1.30.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.11.1001475629
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
cpptools|ms-|1.7.1
hide-gitignored|npx|1.1.0
vscode-text-tables|Rom|0.1.5
rewrap|stk|1.15.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593cf:30376535
vsc1dst:30396469
vsena315cf:30400349
vscexrecpromptt1:30397558

```

</details>

**

**Comment by sandy081** [comment]
Please update to latest insiders and try again. This issue has been fixed recently
