### ISSUE TITLE
code-completion suggestions need context

### ISSUE THREAD

**Issue by SirCameron** [microsoft/vscode#137453]
I've posted about this before and it was ignored (https://github.com/microsoft/vscode/issues/123356)

Code completion is offering suggestions that are out of context...
here is an example:
<img width="584" alt="Screenshot 2021-11-18 at 16 07 43" src="https://user-images.githubusercontent.com/74608/142441985-2670f53d-27cc-4703-88a0-b9decf293bb5.png">

I'm importing a module and typing in the path, but getting suggestions for snippet creators that make no sense.
This makes these suggestions useless and actually annoying.

Suggestion: VSCode should be passing some kind of context on to the plugins to ensure suggestions are valid.

Note: I'm not familiar with how VSCode interacts with plugins.

**Comment by jrieken** [comment]
> Suggestion: VSCode should be passing some kind of context on to the plugins to ensure suggestions are valid.

Snippets aren't dynamically computed by extensions but retrieved from static files and always shown without context.

**Comment by jrieken** [comment]
Unfortunately, we cannot use token information to further limit static snippets.

You can control/disable this with the `editor.snippetSuggestions` setting.

**Comment by mex511511mno** [comment]
J
