### ISSUE TITLE
Auto attach no longer functioning

### ISSUE THREAD

**Issue by donaldcarnegie** [microsoft/vscode#137445]
Issue Type: <b>Bug</b>

Using yarn to start a typescript node app from the terminal. VS code used to auto attach but has now stopped since the latest update. I have auto attach set to always and it still doesn't attach.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (3.97GB free)|
|Process Argv|--folder-uri file:///c%3A/local/ --crash-reporter-id 77f9bcb2-62a1-4003-a950-c1a3b7b10e13|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
durablefunctionsmonitor|Dur|5.1.0
gitlens|eam|11.6.1
vscode-npm-script|eg2|0.3.23
vscode-great-icons|emm|2.1.79
terraform|has|2.16.0
xstate-vscode|mat|1.4.1
vscode-azurecache|ms-|0.1.0
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azureterraform|ms-|0.3.2
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.16
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
remote-wsl|ms-|0.58.5
azure-account|ms-|0.9.11
powershell|ms-|2021.10.2
databricks-vscode|pai|0.8.9
scala|sca|0.5.5
vscode-counter|uct|2.3.0
vscode-icons|vsc|11.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593:30376534
vssld246cf:30401891

```

</details>

**Comment by connor4312** [comment]
- What Node.js version are you using?
- What is the value of the NODE_ENV environment variable in the terminal?
- Does toggling auto attach to disabled and back to always, then launching a new teminal, fix it?

**Comment by AL0403791** [comment]
Sorry i missed this reply!
Node v14.17.6
Node_env == development
Toggling does not fix it, however toggling then opening a new terminal does! thank you!
