### ISSUE TITLE
Boiler code

### ISSUE THREAD

**Issue by dembee909** [microsoft/vscode#137489]
Issue Type: <b>Feature Request</b>

My VSC code generation stopped to generate boiler codes.WHat is the problem?

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
What language are you coding in?

Are you using any extensions?

Sounds like this used to work for you. What changed around the time it stopped working?

**Comment by roblourens** [comment]
What do you mean "boiler codes"?
