### ISSUE TITLE
Git checkout dropdown includes non-existing remote

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/vscode#137425]
Issue Type: <b>Bug</b>

When trying to switch branches in VSCode, the dropdown includes branches from a remote that no longer exists:
![grafik](https://user-images.githubusercontent.com/17641229/142384291-bf66e364-6081-429a-88ca-1dc5278d6378.png)

Attempting to check out these branches results in an error
```
Git: fatal: Cannot setup tracking information; starting point 'AlexCPU/vitrum-fixes' is not a branch.
```

Neither `git remote -v` nor `git branch -vv` include any reference to this remote. It also does not appear in `~/.gitconfig` nor the local `.git/config`.

How can I remove these entries?

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (17.38GB free)|
|Process Argv|--folder-uri file:///c%3A/Repositories/node-zwave-js --crash-reporter-id 334f021d-210d-4760-a7f9-f7e771ce0905|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.2.1
tsl-problem-matcher|amo|0.5.0
vscode-zipfs|arc|2.3.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.6.1
toggle-excluded-files|eam|1.7.0
EditorConfig|Edi|0.16.4
RunOnSave|eme|0.2.0
json-tools|eri|1.0.2
prettier-vscode|esb|9.0.0
copilot|Git|1.7.3862
vscode-pull-request-github|Git|0.32.0
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.24.5
template-string-converter|meg|0.5.4
git-graph|mhu|1.30.0
compare-folders|mos|0.22.2
vscode-json5|mrm|1.0.0
vscode-docker|ms-|1.18.0
vscode-language-pack-de|MS-|1.62.4
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.11
cpptools|ms-|1.7.1
hexeditor|ms-|1.8.2
node-debug|ms-|1.45.0
node-debug2|ms-|1.43.0
powershell|ms-|2021.10.2
test-adapter-converter|ms-|0.1.4
vscode-js-profile-flame|ms-|0.0.21
vsonline|ms-|1.0.3076
hide-gitignored|npx|1.1.0
vscode-jest|Ort|4.2.1
typescript-mono-repo-import-helper|q|0.0.6
java|red|1.0.0
vscode-sort-json|ric|1.20.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
vscode-icons|vsc|11.7.0
vscode-todo-highlight|way|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593:30376534
vssld246cf:30401891

```

</details>

**Comment by AlCalzone** [comment]
> Were those remotes ever present in the repository?

Yes

> If so, were the branches deleted on the remote?
> Was the remote deleted?

The remote came from locally checking out a pull request from a contributor. I removed the remote from my local repository. The remote on Github still exists, but the branch that contained the PR commits doesn't any longer.


> Is it set to ["local", "remote", "tags"]?

Yes

> `code --disable-extensions`

Still there.

**Comment by lszomoru** [comment]
@AlCalzone, thank for the update. Will take a look at this today and will update the issue with my findings.

**Comment by AlCalzone** [comment]
@lszomoru I'm afraid I can't reproduce anymore.

In the meantime another PR from the problematic remote was opened, I checked it out locally with the Github extension and then removed the remote again when done.

Now the entries no longer appear in the list. Commands 1 and 2 also return no reference, but I guess this is expected.

**Comment by lszomoru** [comment]
@AlCalzone thanks for the update. Based on your update I will go ahead and close this issue.
Please feel free to reopen it in case you run into this issue again. Thanks!
