### ISSUE TITLE
Make terminal just like other windows, so it's present as a tab

### ISSUE THREAD

**Issue by alvipeo** [microsoft/vscode#137459]
This is really required when working in codespaces. I'd like to have a terminal as a full windows and it must be present in tabs, just like others.

Also, if I work with multiple monitors I'd like to have a terminal on a separate monitor (while working in codespaces).

**Comment by gjsjohnmurray** [comment]
See https://code.visualstudio.com/updates/v1_58#_terminals-in-the-editor-area for your first wish.

**Comment by alvipeo** [comment]
Thanks, @gjsjohnmurray!

But please leave it here open for the second.

**Comment by gjsjohnmurray** [comment]
Second is covered by #34442

/duplicate
