### ISSUE TITLE
Add staging hunks in Git

### ISSUE THREAD

**Issue by alnorris** [Microsoft/vscode#13740]
SourceTree has this feature, would be great if VS Code had it also.

**Comment by isidorn** [comment]
Changes view > click on elipses on top > stage selected ranges

![screen shot 2016-10-14 at 11 05 48](https://cloud.githubusercontent.com/assets/1926584/19381934/30faff0c-91fe-11e6-80fc-fe14326288e3.png)

**Comment by Matheus-de-Souza** [comment]
@isidorn Is it working on version 1.11.11 (Windows)?

**Comment by Kamahl19** [comment]
I think this disappeared  in latest version, at least I dont see it on windows

**Comment by isidorn** [comment]
@Kamahl19 yes. It is now possible to do this via the command palette (F1)

**Comment by Matheus-de-Souza** [comment]
@isidorn How can I do this? I've tried to add only the selected lines typing 'stage' on the command palette, but I received these options. Am I doing something wrong?

![screenshot 2017-04-24 11 30 38](https://cloud.githubusercontent.com/assets/865597/25342194/9ec74480-28e1-11e7-81d6-82f93dc810dc.png)

**Comment by Matheus-de-Souza** [comment]
Ah, I got it. Indeed, the vscode I have installed on my machine has the 'Stage Selected Ranges' option, in the first screenshot it is there, hehe. (I figure it out now). But I can only stage the entire hunk not a few lines, as the package Magit in the Emacs editor allows me to do. It will be nice if vscode could do that. Thanks for your help and time @isidorn.

**Comment by isidorn** [comment]
@Matheus-de-Souza the issue you are explaining now is captured in another issue (you can search for it) and it will be fixed in a couple of days

**Comment by troyibm** [comment]
Wish this was easier, like in SourceTree.  I have to select the lines, right click, choose "Command Palette" at the bottom of the menu, then click the first item (Git: Stage Selected Ranges) in the command selection (if it was the last thing you did).  How about just highlight, right click and choose "Git: Stage Selected Ranges" (i.e. put that command on the context menu).  Even that isn't as good as SourceTree, but better.
