### ISSUE TITLE
Disable all default Key Bindings feature please...

### ISSUE THREAD

**Issue by NazmusSayad** [microsoft/vscode#137423]
I'd like to request a setting to disable all default keybindings and to use only those keybindings provided explicitly by the user. Currently, I have to manually disable each and every default keybinding explicitly and check after every update whether further additions or modifications are needed. This is annoying at best and error-prone at worst.

**Comment by alexdima** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/134332
