### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ice-penguin** [microsoft/vscode#137422]
Issue Type: <b>Bug</b>

do nothing then it shows this bug

VS Code version: Code 1.61.1 (Universal) (c13f1abb110fc756f9b3a6f16670df9cd9d4cf63, 2021-10-14T01:23:30.274Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 3, 3|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id c575fc96-50f2-4b2c-b3b1-a9aaf7f6a6b3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.19
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
vue|jcb|0.1.5
vscode-language-pack-zh-hans|MS-|1.62.4
data-workspace-vscode|ms-|0.1.0
mssql|ms-|1.11.1
sql-database-projects-vscode|ms-|0.13.1
vetur|oct|0.35.0
java|red|1.0.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246cf:30401891

```

</details>

**Comment by CodeCrazy-ywt** [comment]
What kind of bug?

> 
> Issue Type: <b>Bug</b>
> 
> do nothing then it shows this bug
> 
> VS Code version: Code 1.61.1 (Universal) (c13f1abb110fc756f9b3a6f16670df9cd9d4cf63, 2021-10-14T01:23:30.274Z)
> OS version: Darwin x64 19.6.0
> Restricted Mode: No
> 
> <details>
> <summary>System Info</summary>
> 
> |Item|Value|
> |---|---|
> |CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
> |GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
> |Load (avg)|6, 3, 3|
> |Memory (System)|8.00GB (0.04GB free)|
> |Process Argv|--crash-reporter-id c575fc96-50f2-4b2c-b3b1-a9aaf7f6a6b3|
> |Screen Reader|no|
> |VM|0%|
> </details><details><summary>Extensions (16)</summary>
> 
> Extension|Author (truncated)|Version
> ---|---|---
> githistory|don|0.6.19
> gitlens|eam|11.6.1
> prettier-vscode|esb|9.0.0
> vue|jcb|0.1.5
> vscode-language-pack-zh-hans|MS-|1.62.4
> data-workspace-vscode|ms-|0.1.0
> mssql|ms-|1.11.1
> sql-database-projects-vscode|ms-|0.13.1
> vetur|oct|0.35.0
> java|red|1.0.0
> vscodeintellicode|Vis|1.2.14
> vscode-java-debug|vsc|0.36.0
> vscode-java-dependency|vsc|0.18.8
> vscode-java-pack|vsc|0.18.6
> vscode-java-test|vsc|0.32.0
> vscode-maven|vsc|0.34.1
> 
> 
> </details><details>
> <summary>A/B Experiments</summary>
> 
> ```
> vsliv368:30146709
> vsreu685:30147344
> python383cf:30185419
> vspor879:30202332
> vspor708:30202333
> vspor363:30204092
> vswsl492:30256859
> pythontb:30283811
> pythonvspyt551cf:30345471
> pythonptprofiler:30281270
> vshan820:30294714
> vstes263:30335439
> pythondataviewer:30285071
> vscod805:30301674
> pythonvspyt200:30340761
> binariesv615:30325510
> bridge0708:30335490
> dockerwalkthru:30377721
> bridge0723:30353136
> pythonrunftest32:30373476
> pythonf5test824:30373475
> javagetstartedt:30391933
> pythonvspyt187:30373474
> vsqsis400:30386382
> vsaa593cf:30376535
> vssld246cf:30401891
> 
> ```
> 
> </details>
> 
>
