### ISSUE TITLE
code command not creating a file in wsl2

### ISSUE THREAD

**Issue by alexmondaini** [microsoft/vscode#137409]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Open up vscode in wsl2 
2. code somefile.txt

The code command does work for opening up a directory, but not creating a new file.

**Comment by abhishekmittal15** [comment]
I am facing the same issue. This in fact doesn't work for any remote server in general. I was having this problem while using ssh on vscode

**Comment by sdygt** [comment]
Same here using ssh remote server
```
Version: 1.62.3 (system setup)
commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363
```
The `code` command in integrated terminal does open up folders or existing files, but cannot create and open new files.

**Comment by aeschli** [comment]
I can reproduce.
- run out of source
- open test resolver
- in the integrated terminal type `code.sh|bat newFile.txt`
- nothing happens

Debugged it down to 
https://github.com/microsoft/vscode/blob/3a81c25c7abd5b1ebf76fb10e8b3b7a27aef9000/src/vs/workbench/common/editor.ts#L1157

The `type` is undefined as the file does not exist.
Change got introduced by https://github.com/microsoft/vscode/commit/e31a18ea8c6cf53e205e481c98f290e6d8c20460

FYI @lszomoru @bpasero

**Comment by lszomoru** [comment]
Thanks @aeschli for the repro steps. Will take a look at this today.
