### ISSUE TITLE
Double clicking .cs file opens the editor but not the file

### ISSUE THREAD

**Issue by Corstiaan** [Microsoft/vscode#13743]
- VSCode Version:
1.61

- OS Version:
Window7 sp1

Steps to Reproduce:
1. Double click a C# (.cs) file, registered to open in VS Code
2. VS opens but not the file.

I was using VS Code a s quick code viewer/editor (Visual Studio 2015 takes to long for quick file view) but since my files don't open on double click it's no use anymore. Reverting to Sublime for now.

**Comment by joaomoreno** [comment]
To confirm: it was working in 1.5 and stopped working in 1.6?

**Comment by vullefort** [comment]
I was noticing the same issue with .txt files.  joaomoreno's advice worked (had to do the right-click -> "Open With..." routine)

**Comment by joaomoreno** [comment]
Yeah somehow Windows is breaking this for us... 👎  Same as #13543

**Comment by Corstiaan** [comment]
Yes, it's fixed when you re-register the file to open with VSCode
- Hold SHFT, Right-click the file you want to register to VSCode 
- select "Open with.." -> "Choose default program" from context menu
- Select VS Code
- check "Always use selected.." bottom-left
- click OK

**Comment by joaomoreno** [comment]
Thanks for letting us know!

**Comment by Corstiaan** [comment]
no prob, keep it up!

**Comment by Zueuk** [comment]
Having the same problem, both with double-click and "Open with...", but not with "Open with Code" menu command.
Re-registering as above does not help.

**Comment by douglasg14b** [comment]
@Corstiaan Having the same issue, but sadly re-associating didn't work :/
