### ISSUE TITLE
Use `dist` from `jschardet` and not sources

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#137495]
We use `jschardet` for encoding detection. This library itself ships a minified distribution:

https://github.com/aadsm/jschardet/tree/master/dist

We seem to tell our loader to use that distribution:

https://github.com/microsoft/vscode/blob/ec5486b98f8b12d397025035b9f3da81b80ca632/src/bootstrap-window.js#L143

However, we also tell our build machine to exclude the `dist` folder:

https://github.com/microsoft/vscode/blob/85c5eb7281c69c4a83ba923163f0f6f1f6d904a7/build/.moduleignore#L54

@alexdima do you have an idea why we still successfully load `jschardet`, do we fallback to loading it normally through `index.js` if the file is missing?

@lramos15 I think you did implement some logic to automatically generate loader configuration based on the modules we ship in web, is that true? Are we configuring the web to load from `dist` folder?

I actually wonder how this works in web, where we also seem to exclude the `dist` folder 🤷‍♂️ 

https://github.com/microsoft/vscode/blob/e2b2cf2050fcd549e0d591d2c0be89543a3f371a/build/.webignore#L17

//cc @chrisdias

**Comment by bpasero** [comment]
Oh I was wrong: in web we explicitly include `dist/jschardet.min.js` and that seems to work just fine. 

Trying now to do the same for desktop: https://github.com/microsoft/vscode/commit/c717404bd9be3947388397495b14fb5678d86679

**Comment by mumu-baba** [comment]
Missing dependency: jschardet

**Comment by mumu-baba** [comment]
1.63 版本 svn 扩展会报Missing dependency: jschardet ，导致svn 扩展不可用

**Comment by chrisdias** [comment]
https://github.com/JohnstonCode/svn-scm/issues/1542
