### ISSUE TITLE
command 'extension.handleEnter' not found

### ISSUE THREAD

**Issue by Alion5** [microsoft/vscode#137463]
In style.css folder when i try do go to next line by pressing enter, there is being written ''command 'extension.handleEnter' not found''

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version, platform and whether the Start Extension Bisect command identifies an extension as causing the problem.

**Comment by aeschli** [comment]
`extension.handleEnter` is a command that comes from an extension. You can find out which extension it is by using the `Start Extension Bisect command`, as described by @gjsjohnmurray

**Comment by Alion5** [comment]
Thanks!

пт, 19 нояб. 2021 г., 13:25 Martin Aeschlimann ***@***.***>:
