### ISSUE TITLE
[loc][Query][VSCode] Please clarify string

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#13745]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Toggle Terminal

File Name:
src\vs\workbench\parts\watermark\watermark.nls.resx

Resource ID:
".resx", 0; "watermark.toggleTerminal"

Query:
Is Toggle a verb here?

**Comment by bpasero** [comment]
@josefhosek yes 👍
