### ISSUE TITLE
git for windows using 64 GB of RAM

### ISSUE THREAD

**Issue by austinorion** [microsoft/vscode#137483]
Issue Type: <b>Bug</b>

Don't have a reliable repro, but I was just doing my normal work and noticed my machine had become incredibly slow. I opened Task Manager to see hundreds of "git for windows" processes each taking up ~100MB of RAM, and my total memory usage was at 99% on my 64GB machine. Closing VS Coded ended all the processes, so I assume the issue is here.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10940X CPU @ 3.30GHz (28 x 3312)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.72GB (50.85GB free)|
|Process Argv|--crash-reporter-id f779572e-764f-4bd4-8d5f-3aab1596e91f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
togglehs|bbe|0.1.2
gitlens|eam|11.7.0
tdpcode|Mic|1.5.2
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
cpptools|ms-|1.7.1
vscode-gn|npc|1.1.0
vscode-pets|ton|1.8.1
sort-lines|Tyr|1.9.0
clang-format|xav|1.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vshan820:30294714
vscod805cf:30301675
vsccppwt:30393681
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535

```

</details>

**Comment by austinorion** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/58865467/142515533-75d26a0e-e4c2-4a06-85ff-2d24b0379d4f.png)

**Comment by tanhakabir** [comment]
seems related to https://github.com/microsoft/vscode/issues/137472

**Comment by lszomoru** [comment]
What version of "Git for Windows" are you running?

**Comment by austinorion** [comment]
Sorry I didn't see your question. Git version is 2.28.0.windows.1

This just happened to me again, and I found this old bug that seems to be the same problem
https://github.com/Microsoft/vscode/issues/71085

They say updating git solved it for them, so I will try that and come back if this happens again.
