### ISSUE TITLE
Spawning child processes on Windows open up new terminals

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#137481]
See https://github.com/microsoft/vscode/pull/137241#issuecomment-973206239

1. On Windows, build from the electron-16.x.y branch
2. Run OSS
3. :bug: Some terminals will pop up during the load (such as ripgrep, or types-registry)
4. After loading, switch between files in the file explorer
5. :bug: More terminals pop up from git

![Screencap](https://user-images.githubusercontent.com/7199958/142508293-45e6affc-4220-452b-8483-976875265746.gif)

**Comment by deepak1556** [comment]
Fixed with https://github.com/microsoft/vscode/pull/137241/commits/69c531abd4a8efaad5c0530d817bf75f8d9484db
