### ISSUE TITLE
Horizontally scroll with mouse

### ISSUE THREAD

**Issue by sondresorbye** [microsoft/vscode#137466]
Does this issue occur when all extensions are disabled?: Yes

I cant scroll horizontally with logitech mx master 2 in vscode. This would be nice. 

- VS Code Version: latest stable
- OS Version: windows 11

**Comment by seesemichaelj** [comment]
FWIW, I've had various performance issues with the same mouse for years. Works most of the time, sometimes breaks, and [sometimes] works again after dragging the horizontal scroll bar with the cursor manually. Uninstalling Logitech Options ultimately has had the _best, but not perfect,_ experience for me. I use AutoHotkey for any remapping I need to do with the MX Master.

**Comment by mex511511mno** [comment]
I
