### ISSUE TITLE
Enable lgtm check for vscode.

### ISSUE THREAD

**Issue by LeuisKen** [microsoft/vscode#137411]
I find that there are 132 alerts for vscode repo on lgtm.com, you can see the issue report here: https://lgtm.com/projects/g/microsoft/vscode/alerts/?mode=list

And some of the alerts like `Useless conditional` make sense

I think we could enable LGTM pull request integration to vscode repo, this may help to find some code quality issues.

**Comment by Tyriar** [comment]
We periodically review alerts from tools like this, I don't think we need to integrate it though, typically they're just cleanliness things and integrating would bring up some false flags and slow us down.
