### ISSUE TITLE
Make smoke tests work offline

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#137455]
Right now smoke tests fail when offline or internet is flaky as they rely on cloning a git repo. I suggest we add a new `--test-folder <dir containing the cloned test repo>` flag that would get copied to the tmp dir instead of the git clone.

**Comment by meganrogge** [comment]
this already works with the `test-repo` argument. https://github.com/microsoft/vscode/blob/f66bc86da89d9f0ca91715b2b9c8569b06dafa03/test/smoke/src/main.ts#L208-L216
https://github.com/microsoft/vscode/commit/9da0f472dd9f6f92ba513c0ee914ce3aa41feeb2
