### ISSUE TITLE
Feature Request: Restart running npm script.

### ISSUE THREAD

**Issue by mrfy** [microsoft/vscode#137424]
Please add the functionality to restart the current running npm script on VS Code. A similar function exists e.g. in IntejiJ:

![image](https://user-images.githubusercontent.com/22953614/142382315-dd050eec-6e92-43bd-ab02-552c4db252fd.png)

Until now, I need to close the terminal running the npm script and start it again.

![image](https://user-images.githubusercontent.com/22953614/142382349-83d73aad-a6d7-4c74-9cb3-beb8fca13187.png)

**Comment by Tyriar** [comment]
Extensions aren't able to add buttons there yet, we'd need that to come first. Something you could try is pull the npm scripts pane into the terminal panel.

@sbatten is there an issue tracking allowing users to contribute actions to views? I couldn't find it.

**Comment by sbatten** [comment]
I don't recall one for arbitrary views
