### ISSUE TITLE
${fileBasename} with extension, any variable without extension?

### ISSUE THREAD

**Issue by bayesrule** [Microsoft/vscode#13742]
- VSCode Version: 1.6.1
- OS Version: Window 7

Hi,

When using cl.exe in VS Code for C++, without other specification the output program is automatically named as {fileNameWithoutExt}.exe. In current VS Code, we already have ${fileBasename} with extension and ${fileExtname} (the extension). Is it possible to add another variable without the extension?

Below is an example in my launch.json file.

```json

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch (Windows)",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceRoot}/${fileBasename}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": false
        },
        {
            "name": "C++ Attach (Windows)",
            "type": "cppvsdbg",
            "request": "attach",
            "processId": "${command.pickProcess}"
        }
    ]
}

```
It doesn't work since the "program" property will end up with foo.cpp.exe

Many thanks!

**Comment by isidorn** [comment]
Hi @bayesrule this launch.json is generated by the C++ debug extension. Can you please file this issue against their repository here https://github.com/Microsoft/vscode-cpptools
