### ISSUE TITLE
Json language server

### ISSUE THREAD

**Issue by Lrlk** [microsoft/vscode#137452]
We have written the needed data into your clipboard because it was too large to send. Please paste.when i open vs code it start to open repeatedly new windows with a single tab (the json language server) and it floods my pc, it only stops when i close all the windows it opened

**Comment by aeschli** [comment]
Do you have `"security.workspace.trust.untrustedFiles": "newWindow"` in your settings and opening a remote file? That would be https://github.com/microsoft/vscode/issues/136106

If not, does it reproduce if you remove all settings?

**Comment by Lrlk** [comment]
Mine is "security.workspace.trust.untrustedFiles": "prompt".
What do you mean by "remove all settings"?

**Comment by aeschli** [comment]
I meant to unset all your user settings and try out if the issue depends on any user settings.
An alternative way, without changing the settings files:
- close all VSCode windows
- start from the command line `code --user-data-dir=someEmptyDirectory`

On what version are you and what platform?
Does the issue reproduce if extension are disabled?

**Comment by Lrlk** [comment]
i installed again the vscode by the .deb package and not by flatpack this time, and it not occurring anymore, if the problem start happening again withing this week i will send a message here, if not, consider it fixed
