### ISSUE TITLE
Slow performance returning to window

### ISSUE THREAD

**Issue by seesemichaelj** [microsoft/vscode#137472]
Issue Type: <b>Bug</b>

Within the last few days, I've been having some fairly slow performance returning to the VSCode window from other windows. Looking at the task manager, I notice a CPU spike for code when I return to the code window. I have disabled extensions and even made sure to close all open tab. The performance spike is enough to cause audio playing in the background (I have  tried both the Spotify desktop application as well as YouTube in a chrome tab) to stutter like my CPUs are completely clocked out. Moving around the window is slow, and when switching back to another window, it's still fairly slow for a few seconds before whatever VS Code was doing finishes. I usually only notice this kind of user experience slow down when I'm compiling a heafty application that takes all 32 of my logical cores.

I am running on the Dev Insider channel of Windows 11. I currently have `Build 22499.rs_prerelease.211105-1550`. I'm using 2-folder workspace that I've been using for several months without issues.

This issue is also seen on Insider build 1.63.0-insider commit `bedf867`. I also put together a video capture of it happening with both stable and insider builds with the task manager showing a bunch of processes being kicked off when it does occur.

https://user-images.githubusercontent.com/549323/142494188-c7903cdb-94fb-43f7-8866-36888357600f.mp4

**NOTE:** Another interesting datapoint: returning to August's 1.60.2 does not resolve the issue. This must be related to the interaction of VSCode with some other app that got updated (Git or Windows are the only two that come to mind). Git for Windows from https://git-scm.com is at version `2.33.0`. 

Might be related to #137397

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.22499
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (32 x 3493)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (41.84GB free)|
|Process Argv|--crash-reporter-id 4c41e6da-9652-41d9-a1cb-f219ff67a4d1|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30402085
vsaa593:30376534
vssld246:30401890

```

</details>

**Comment by seesemichaelj** [comment]
Upgrading Git for Windows to `2.34.0` does not resolve the issue.

**Comment by roblourens** [comment]
Can you tell which process is getting the CPU spike (the full command line args)? Is it different if you start with `--disable-extensions`?

**Comment by roblourens** [comment]
I guess you answered the extensions question already. But if you can figure out which process it is, we can get a profile of that process.

How long have you seen this? Could it be related to the win11 dev channel?

**Comment by seesemichaelj** [comment]
@roblourens I've only seen this for maybe a few days, so it very much could be related to the Win11 Dev channel, but it should be noted I don't see this issue occur in any other application so there may be a new compatibility issue here (or still possible to be a bug on Windows's side).

Since my last post, I also updated Windows 11 to the insider build 22504, but the problem is still around.

Figuring out *which* process has a spike is difficult because as seen in the video, lots of new processes are initiated during the spike, and they all seem to be smaller CPU percentages. Here's just one screenshot of the video showing multiple processes adding up to 0.6% CPU usage, but task manager is reporting VSCode as a whole is using 8% (note that 3.1% is ~100% of 1 logical core on my machine, assuming all 3.1% is coming from a single process in a single thread):

![image](https://user-images.githubusercontent.com/549323/142513675-91c84879-3d18-497a-b105-1bcaf5a4a6a1.png)

My eyeballs seem to say `Console Window Host` has the most processes created with the most ~1%, but the multiple `code.exe` processes do seem to take a heavy hit.

Any recommendations on how I can measure a more technically correct answer? I'm willing to build VSCode from source if necessary (or whatever else is needed to get to the bottom of this) as this is a big frustration with my day-to-day activities.

I'm going to try disabling the built in git extension as well as use powershell as my default terminal instead of git bash to see if that provides better performance

**Comment by roblourens** [comment]
Can you get profiles of the extension host and renderer process?

- EH:
  - Run the "Show running extensions" command
  - In the top right corner, there is a sort of Record button to reload with the profiler on
  - Repro the issue, go back to that page, save the profile
- Renderer process
  - Help > Toggle Developer Tools
  - Use the Performance tab to get a profile

@lszomoru maybe git is doing something wrong here, or maybe that is normal

**Comment by seesemichaelj** [comment]
These were two separate tests since it was less easy to reproduce. Both are with a barebones 1.63.0-insider build with built-in extensions enabled (no other extensions). The replication in both is usually in the last 5-10 seconds. Looks like the EH profile is showing some (potentially?) long times for `spawn` from the git extension. Disabling Git did seem to have much better performance

[Profile-20211118T164000.zip](https://github.com/microsoft/vscode/files/7566957/Profile-20211118T164000.zip)

**Comment by seesemichaelj** [comment]
It should be noted that the workspace I'm using has 2 git repositories which collectively have 11 submodules, totally 13 different repos to check. I'm going to try to proceed with Auto Fetch disabled as I'm guessing that's what's triggering for things to run. I'm not sure why a simple child process call to fetch git data would cause some system-wide slow downs, but 🤷

**Comment by seesemichaelj** [comment]
While I was having great performance last night with autofetch disabled for the whole workspace, today, I've reproduced the issue a handful of times :/ I'm mostly operational though, but do let me know if you need any more data or need me to try out an Insider build. Happy to help however I can.

**Comment by seesemichaelj** [comment]
Just as an update on this one, I realized that I had installed [Incredibuild](https://www.incredibuild.com) roughly around when I may have started having this issue. Since that works by hooking into the kernel to intercept tasks that are parallelizable and distribute the bytecode to other machines, I now have a running hypothesis it's basically slowing most processes including these simple git processes that the git extension makes.

I uninstalled Incredibuild, did a restart to ensure it was out of the kernel, and now will see if the problem arises with VSCode's Git enabled and Autofetch enabled. As of now, I *have* seen lots of processes open like before when returning to the window after a few minutes (I'm guessing after the auto fetch 180s timer), but it no longer hogs enough CPU to make my music stutter or notice any other performance issues.

I'll keep monitoring this and report any findings. I'll also contact the Incredibuild team to see if they have any thoughts.

**Comment by seesemichaelj** [comment]
Unfortunately while the issue seemed to go away at first, eventually I was able to reproduce this issue multiple times with Incredibuild completely uninstalled (I never reinstalled it after it was uninstalled). I'm still waiting to hear back from the Incredibuild team to see if they have any thoughts on the situation. It should also be noted that I *would hope* that this isn't a Disk IO issue as both of my drives (where VSCode is installed and where the workspace is located) are faster NVMe drives (Samsung 970 EVO 1TB M.2 NVMe and Samsung 980 PRO 2TB M.2 NVMe respectively).

**Comment by seesemichaelj** [comment]
Ok, I have some more concise info now:
- "The issue" is defined as having the below symptoms
    - Background music stutters/crackles as if 100% CPU is being used (but it's not)
    - System input (Windows cursor and keyboard input) has high latency (cursor hangs and jumps to another location, keyboard input takes awhile [0.5+ seconds] to be processed)
    - The symptoms are temporary, usually start when I see a lot of child processes spawn from VS Code
- The issue goes away after a system (Windows) restart
- The issue comes back after several hours of having VS Code open (I'm guessing it doesn't matter if VS Code is open, but I haven't tested it otherwise)
- After I start noticing the issue, it usually happens every time I come back to the window after a few minutes (mainly trying to get all repos to elapse their 180s autofetch timer)
- Restarting the extension host does not resolve the issue
- Closing all windows of VS Code and opening again does not resolve the issue
- The issue is *somewhat* reproducible (no noticeable mouse/keyboard input latency, only a single crack is heard with music); I am completely okay with these symptoms on my machine, but it may indicate issues for others with less powerful machines
- While it's possible Incredibuild might make the symptoms appear sooner, the issue reproduces without it
- The above is tested with the Git extension enabled, autofetch is enabled (180s timer)
- Chrome starts having weird load issues

Here's my gut feeling analysis after looking at the Git extension code:
- The fact that Windows restarting is the only thing resets symptoms and things work fine 1-2 (more maybe? my testing wasn't that fine) makes me think there's something new with Windows 11 Dev Channel builds (or normal Windows 11) that is causing this issue. I'm not sure if WIndows or VS Code is at fault yet. I would have to test the issue on Windows 10 on another machine, then install Windows 11 and test again. It would be pretty prohibitive to take my current machine and do a clean install down to Windows 10 to see if it produces there.
- The issue is exacerbated with more Git repositories in the same workspace. The code checks to see if a single `Repository` is idle before doing this system things, but here's no global mutex to prevent 13 `updateStateModel` calls happening simultaneously on 13 repos. Having some mutex to prevent these from updating simultaneously would probably be enough of a bandaid to call this "resolved" for now. There's definitely no reason to have all of these actions done all at once (which it shows there's been some work to spread out spawning processes on a single `Repository`
- There's probably a more complicated solution which would prevent even a single stutter in background music, but it's likely not worth the time

I will be away for a week so my responses will be heavily delayed, and I won't be able to do more testing until 12/1

**Comment by seesemichaelj** [comment]
@lszomoru Just an update on this one:

- I'm still using VS Code 1.62.3
- Windows 11 insider updated from 22504 to 22509 on 12/1
- I've reinstalled Incredibuild
- I did not purposely do any driver updates, but I can't speak for anything that was automatically updated
- I've tried leaving VS Code open over night (I used to not be able to go 8 hours without the issue start showing up)
- Git extension's Autofetch is still enabled

While I'm still seeing the CPU spikes, I believe this last Windows update has prevented/fixed a bug such that these spikes from causing lagging/stuttering/halting in other system-level stuff (i.e. audio, human input devices).

**So outside of monitoring the Task Manager, my symptoms have disappeared, likely due to the Windows 11 insider 22509 update. I'm not sure if that necessarily means that the issue is resolved; there are still improvements that could be made to the autofetch logic described in my last comment. However, it's no longer "breaking" for my specific setup. I'll leave it up to you @lszomoru if this issue should be closed for now; I can always reopen (or open a new one) if the issues return.**

**Comment by lszomoru** [comment]
@seesemichaelj, thank you very much for the update. I will close the issue for now but please feel free to reopen it in case the issue reoccurs. I will also be looking at potential optimisations to reduce resource consumption for workspaces with multiple repositories.
