### ISSUE TITLE
Electron 16: Integration test fails to start on mac when loading spdlog

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#137431]
Refs https://github.com/microsoft/vscode/pull/137241

Currently the issue is only seen in CI runs, haven't been able to repro the issue locally.

```
 Module did not self-register: '/Users/runner/work/vscode/vscode/node_modules/spdlog/build/Release/spdlog.node'
```

The error means that spdlog is trying to be loaded more than once in the same process when it is not context aware and currently the error is triggered from the main process.

```
    at createSpdLogLogger (/Users/runner/work/vscode/vscode/out/vs/platform/log/node/spdlogLog.js:12:35)
    at SpdLogLogger._createSpdLogLogger (/Users/runner/work/vscode/vscode/out/vs/platform/log/node/spdlogLog.js:63:34)
    at new SpdLogLogger (/Users/runner/work/vscode/vscode/out/vs/platform/log/node/spdlogLog.js:53:48)
    at /Users/runner/work/vscode/vscode/out/vs/code/electron-main/main.js:56:47
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CodeMain.startup (/Users/runner/work/vscode/vscode/out/vs/code/electron-main/main.js:43:17)
```

**Comment by bpasero** [comment]
Seeing this:

```
The module '/Users/bpasero/Development/Microsoft/vscode-electron-16.x/node_modules/spdlog/build/Release/spdlog.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 99. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

**Comment by deepak1556** [comment]
[Version 99](https://github.com/nodejs/node/blob/340b770d3f4c3b50a5d36c0776afd63d9b4f22de/doc/abi_version_registry.json#L7) is Electron 16 and [Version 93](https://github.com/nodejs/node/blob/340b770d3f4c3b50a5d36c0776afd63d9b4f22de/doc/abi_version_registry.json#L13) is Node 16 , so looks like the headers and libraries were downloaded incorrectly not based on the `.yarnrc`. Lets try deleting your node-gyp cache.

**Comment by bpasero** [comment]
👍 , how to?

**Comment by deepak1556** [comment]
`rm -rf ~/Library/Caches/node-gyp/16.0.0`

**Comment by deepak1556** [comment]
Fixed in https://github.com/microsoft/vscode/pull/137241/commits/ae4ddcd4f0c6ee12270c90a402a832d61b9bf16d
