### ISSUE TITLE
Incorrect (potentially) indentation of function arguments spanning multiple lines

### ISSUE THREAD

**Issue by nomaed** [Microsoft/vscode#13748]
- VSCode Version: 1.6.1
- OS Version: macOS Sierra 10.12

Steps to Reproduce:

* Write a function (or a method) with several arguments (I did it with JavaScript and TypeScript files, but I believe any would work).
```javascript
function myFunc(arg1, arg2, arg3, ...args) {
}
```
 * Split arguments to several lines by hitting Enter before arguments
```javascript
function myFunc(arg1,
arg2,
arg3,
...args) {
}
```

Auto-formatting produces this result:
```javascript
function myFunc(arg1,
    arg2,
    arg3,
    ...args) {
}
```

I would expect to see this result instead though:
```javascript
function myFunc(arg1,
                arg2,
                arg3,
                ...args) {
}
```

Also, when manually formatting the arguments to appear in the same column (note: this is also the default/recommended setting in `tslint` and maybe other linters), then further lines will start with wrong indentation:
```javascript
function myFunc(arg1,
                arg2,
                arg3,
                ...args) {
                    console.log('huh...');
}
```

![vscode-multi-line-args-indent](https://cloud.githubusercontent.com/assets/9551921/19384766/a89ed4d8-9213-11e6-9890-ec41080e8843.gif)

**Comment by waderyan** [comment]
@nomaed thank you for opening this issue. 

@dbaeumer can I get some other eyes on this? I think I actually prefer this result with auto formatting:

```
function myFunc(arg1,
    arg2,
    arg3,
    ...args) {
}
```

But that might simply be my preference. Possibly there should be an option for OP to customize the auto formatting for his preference?

**Comment by waderyan** [comment]
@bowdenk7 if you have a thought on this too that would be helpful. Don't know if this has come up much in your user studies...

**Comment by dbaeumer** [comment]
@waderyan I prefer yours as well. Agree that this should be a setting in the TS formatter. The good thing is if you formatted it once it will leave it as is.

**Comment by nomaed** [comment]
It's definitely shouldn't be the only option. I personally grew to like it a lot (it's the default setting in JetBrains' IDEs) and since it's a default for TSLint (https://github.com/palantir/tslint/blob/master/src/rules/alignRule.ts), I am thinking that it's not uncommon to use this setting.

**Comment by waderyan** [comment]
Moving this to TS language service to address adding the setting. Thank you for your feedback @nomaed. It is valued very highly.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11629
