### ISSUE TITLE
In Solarized Light theme, selected text in jupyter code block is indistinguishble from background

### ISSUE THREAD

**Issue by FanShupei** [microsoft/vscode#137537]
## Environment data

-   VS Code version: 1.62.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: Windows 19043
-   Python and/or Anaconda version: N/A
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: N/A

## Expected behaviour

The background color of selected text shall be different from background color of text block.

## Actual behaviour

The color of selected text is the same (or too similar to) as the background color. (See screenshot below)

## Steps to reproduce:

1. Change VsCode theme to Solarized Light
2. Open a jupyter notepad in VsCode
3. Type some code, and select part of them

The selected text is too hard to identify due to the same color.

## Screenshot

Selected text in `Light+` theme
![image](https://user-images.githubusercontent.com/15810674/142615529-65748165-0768-4116-bbf1-70fa396faa3d.png)

Selected text in `Solarized Light` theme. (All text is selected, but the selection is invisible)
![image](https://user-images.githubusercontent.com/15810674/142615951-aaf01f42-dd82-457c-a646-d3e7fc6f3467.png)

**Comment by misolori** [comment]
This was recently fixed via https://github.com/microsoft/vscode/issues/137085 please try it out on [Insiders](https://code.visualstudio.com/insiders/) to see the update
