### ISSUE TITLE
Unable to resolve filesystem with relative file path <absolute path>

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#137524]
I'm doing this in Luna Paint:

```
candidateFolder = 'C:\\Users\\Daniel\\Pictures';
const exists = !!(await workspace.fs.stat(Uri.parse(candidateFolder)));
```

And it's causing VS Code to throw the following error:

![image](https://user-images.githubusercontent.com/2193314/142649279-34dbab9b-d854-4c26-adcc-78d75e0c1474.png)

This was a recent regression as it definitely worked a few versions ago. See https://github.com/lunapaint/vscode-luna-paint/issues/107, this breaks creating new images/icons in Luna Paint completely in untitled workspaces.

**Comment by jrieken** [comment]
You cannot call `parse` of a path, either have a full uri or use the `file` util

**Comment by Tyriar** [comment]
@jrieken is this how you would do that in a portable way?

```ts
Uri.from({
  scheme: env.uriScheme,
  path
});
```

**Comment by jrieken** [comment]
What do you mean by "portable". The scheme is kinda fixed and nothing that changes. You should already have a scheme and always use that

**Comment by Tyriar** [comment]
I mean works across web/remote/local since `Uri.file` always uses the file scheme which doesn't work in remote. Reading https://code.visualstudio.com/api/extension-guides/web-extensions I guess context.extensionUri.scheme is what I want?

> Look out for usages of path, URI.file, context.extensionPath, rootPath. uri.fsPath. These will not work with virtual workspaces (non-file system) as they are used in VS Code for the Web. Instead use URIs with URI.parse, context.extensionUri. The vscode-uri node module provides joinPath, dirName, baseName, extName, resolvePath.

Also, should vscode.d.ts call out the fact that absolute paths don't work in `Uri.parse`? Or throw a better error about the extension doing something wrong?

**Comment by jrieken** [comment]
> Reading https://code.visualstudio.com/api/extension-guides/web-extensions I guess context.extensionUri.scheme is what I want?

Unsure what you want, `context.extensionUri` is the source of your extension, e.g https://unpgk.xyz... So, yes if you want to load a resource that is shipped with your extension. If you want to load a workspace resource you need to use the workspace API to find its root folder/folders.
