### ISSUE TITLE
`Close Remote Connection` not working when resolver failed

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#137527]
Latest Insiders on macOS.

Similar to #136358, when the resolver failed (e.g., because the Dockerfile contains an error), I cannot use `Close Remote Connection` (or any other command using the `vscode.openFolder` command passing a URI to it).

@Tyriar @meganrogge Is this the terminal vetoing the reload? /cc @aeschli

**Comment by jkeech** [comment]
Possibly related to https://github.com/microsoft/vscode/issues/137468
