### ISSUE TITLE
Workspace setting not reading proxy values - self signed certificate

### ISSUE THREAD

**Issue by amarth1982** [Microsoft/vscode#13755]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: johnpapa.Angular2-1.0.2

Steps to Reproduce:

1. New install of VS code, shift+ctrl+P type workspace setting, under setting set http.proxyStrictSSL: false and set http.proxy:"someproxy" then try installing a extension, getting self signed certificate issue
2. However moving the setting to user settings fixed the issue
3. also note I have already set HTTP_PROXY and HTTPS_PROXY set in user environment variable, which as per the documentation should also have worked

**Comment by joaomoreno** [comment]
Proxy needs to be a user setting, they don't work at a workspace level. The `HTTP_PROXY` and `HTTPS_PROXY` variables work, but it's the `http.proxyStrictSSL` setting that makes the self signed certificate issue go away.
