### ISSUE TITLE
git connecting to server suddenly not working ubuntu

### ISSUE THREAD

**Issue by darwin808** [microsoft/vscode#137567]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.62.3
- OS Version: ubuntu 20

Steps to Reproduce:

1.open project 
2.git pull/push origin dev

suddenly after i update vscode this does not work properly 

now i have to manually use the terminal so that  I can perform git remote commands

**Comment by lszomoru** [comment]
We have had several regressions in this space but all should be fixed with `1.62.3`.
Can you please close all instances of VSCode, and restart the application? Thanks!

**Comment by darwin808** [comment]
yes its resolved now , you can close this thread
