### ISSUE TITLE
Triggering find widget with the cursor on an empty line starts selection mode

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#13757]
1. Put cursor on an empty line
2. <kbd>Ctrl F</kbd>

The find widget will search for a selection between the empty line and the previous line, failing to actually find occurrences in the whole document.

![bug](https://cloud.githubusercontent.com/assets/22350/19388304/2580909e-921f-11e6-9b13-750df908bdad.gif)

**Comment by isidorn** [comment]
Fixed
