### ISSUE TITLE
macOS: Process explorer not put to front if minimized

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#137598]
Steps to Reproduce:

1. open process explorer on macOS
2. minimize the window
3. try to open the process explorer again

=> 🐛  the window is not restored

**Comment by Tyriar** [comment]
I can't repro on windows or mac:

![recording (2)](https://user-images.githubusercontent.com/2193314/142880012-be4db2c3-c824-4645-b46f-abe6f5e7c083.gif)

**Comment by bpasero** [comment]
I can no longer reproduce when I `restore` the window if minimized. Pushed a change also for issue reporter, please check i tout.
