### ISSUE TITLE
Alt + click not working on fedora 34 Xfce

### ISSUE THREAD

**Issue by HenraL** [microsoft/vscode#137531]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: `vs code 1.62.2`
- OS Version: `Fedora 34 (Xfce)  (version: 4.16)`

Steps to Reproduce:
0. fedora info:
    1. Device: `fedora`
    2. OS Name: `Fedora 34 (Xfce)`
    3. OS Type: `64-bit`
    4. xfce Version: `4.16`
    5. CPU: AMD Ryzen 9 4900hs
    6. GPU: AMD Renoir (512.0 MiB)

0. VS code issue
1. Open a code workspace in the latest (`vs code 1.62.2`)
```3a6960b964327f0e3882ce18fcebd07ed191b316```
`x64`
2. make sure that the multi-cursor is not set to `ctrl` + `click`
3. in any file try to select many lines using `alt` + `click` (for each line)
4. If is not present anymore please close this post.

**Comment by alexdima** [comment]
@HenraL In many Linux desktop environments, alt+click or ctrl+click are reserved by the desktop environment for moving windows. Is alt+click available for you in other applications on this system?

**Comment by HenraL** [comment]
Dear @alexdima,
The key bind alt+click or ctrl+click is not reserved by any application or global keybinding of the environement.
The key bind alt+click is not common for the applications I use (except for vs code) so I do not have other software on wich I can test alt+click
By the way, I do know that ctrl+click works (this is why I specified that setting in bulet-point 2 of the VS code issue set.

**Comment by alexdima** [comment]
@HenraL Could you please open http://vscode.dev/ in Chromium and Firefox and do `alt+click`. Does `alt+click` work there to add multiple cursors?

**Comment by HenraL** [comment]
Well I was using your software, and I do not have chrominium.

**Comment by alexdima** [comment]
@HenraL VS Code is built with Electron, which is built with Chromium. I was trying to ask if there is other Chromium-like software on your machine that is able to receive alt+click. How about Firefox (or your system web browser), does alt+click work at https://vscode.dev/ (which hosts our sources in a web browser) to add multiple cursors?

**Comment by HenraL** [comment]
I am afraid that even in firefox alt+click is not working.
But that might be because alt click is already bound to moving the whole firefox window/

**Comment by alexdima** [comment]
> I am afraid that even in firefox alt+click is not working.
> But that might be because alt click is already bound to moving the whole firefox window.

Thank you for your reply. This indicates to me that other software is also unable to receive alt+click in your desktop environment, so most likely a desktop environment setting must be changed in order for windows to receive alt+click.

**Comment by HenraL** [comment]
thank you for your answer, and yes, there are a few binds of alt in the system such as alt+F4 for closing a window.
