### ISSUE TITLE
ECMAScript - Autocomplete Bug - Import path is missing .js file extension

### ISSUE THREAD

**Issue by JaredMathis** [microsoft/vscode#137593]
Issue Type: <b>Bug</b>

Video of bug (45 seconds long): https://www.youtube.com/watch?v=JuHqdgkd7KI

I am coding in JavaScript

Visual Studio Code automatically adds an "import ... from '...';" statement using ES modules syntax.

The path is missing the '.js' file extension.

For example it autocomplete inserts:
import bug from "./bug";

Instead, it should be:
import bug from "./bug.js";

When the file is ran from "node", node errors because it's missing the .js file extension:

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '.../bug' imported from .../cat.js
Did you mean to import ../bug.js?
    at finalizeResolution (internal/modules/esm/resolve.js:276:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.anonymous (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

VS Code version: Code 1.55.2 (Universal) (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.42GB free)|
|Process Argv|--crash-reporter-id b8b70a06-2a42-4bce-8e17-274e6d64d7fa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.12
vetur|oct|0.35.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30402085
vsaa593:30376534
vssld246cf:30401891
vscexrecpromptt2:30400062

```

</details>

**Comment by IllusionMH** [comment]
/question

This is not a bug. This is intended default behavior that predates ESM and it's requirement to have `.js` in imports.

You can change it in settings using `"javascript.preferences.importModuleSpecifierEnding": "js"` (or similar settings for TS)
