### ISSUE TITLE
Indicate symlinks in search by an arrow ↪

### ISSUE THREAD

**Issue by lzm0** [microsoft/vscode#137521]
VS Code currently does not display arrows ↪ for files that are symbolic links in the following two places, at least not by default.
1. Search files by name
2. Search text in all files

It makes sense for them to behave just like the Explorer:
![image](https://user-images.githubusercontent.com/7163127/142647383-48a26f44-882a-4055-8392-4183f864aeec.png)

**Comment by eleanorjboyd** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue.
