### ISSUE TITLE
Word Wrap Not Working

### ISSUE THREAD

**Issue by oliversielski** [microsoft/vscode#137575]
Issue Type: <b>Bug</b>

Word wrap setting are not being applied from setting or from the View menu. Alt-Z shortcut not working either.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (19.03GB free)|
|Process Argv|--crash-reporter-id 6fc44fef-3e0e-49a3-84f6-5af32bf23cdb|
|Screen Reader|no|
|VM|25%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.4
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.7.0
vscode-firefox-debug|fir|2.9.5
cloudcode|goo|1.16.1
file-downloader|min|1.0.11
mindaro|min|1.0.120210803
vscode-docker|ms-|1.18.0
vscode-kubernetes-tools|ms-|1.3.4
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
vscode-react-native|msj|1.8.0
vscode-yaml|red|1.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593cf:30376535
vssld246cf:30401891

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command to check whether any of your extensions are causing this.

**Comment by alexdima** [comment]
@oliversielski Are you perhaps opening a very large file?

**Comment by Loogeek** [comment]
"accessibilitySupport" set off can solve this problem
