### ISSUE TITLE
shoing there is language error while coding

### ISSUE THREAD

**Issue by satyambholi** [microsoft/vscode#137594]
Issue Type: <b>Feature Request</b>

when i start coding alwat there is showing language not supported ..please help

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
What language?

/needsMoreInfo

/gifPlease
