### ISSUE TITLE
remoteCli: support opening new windows, including other remotes and locals

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#137529]
The following options got added to the remote cli

- `-n` to open a new window of the same remote as the current window
- `-n` `--remote=wsl+ubuntu` to open a new window of a different remote
- `-n` `--remote=local` to open a new local window

**Comment by rchiodo** [comment]
Sorry I'm a bit confused what should happen here. 

The ```-n``` flag seems to have no impact?

The other commands were already there as far as I can tell?

I tried these combinations:

- code-insiders --remote wsl+ubuntu /mnt/d/source/Testing_7 == Opens Testing_7 folder in WSL
- code-insiders -n --remote wsl+ubuntu /mnt/d/source/Testing_7 == Brings focus to other window (is it supposed to open a new window?)
- code-insiders -n --remote wsl+ubuntu /mnt/d/source/Testing_6 == Opens Testing_6 folder in WSL
- code-insiders --remote local == Gives an error
![image](https://user-images.githubusercontent.com/19672699/144136451-9234b80e-d690-4f14-b06c-7b7be3d1c2d2.png)

**Comment by aeschli** [comment]
@rchiodo That's with the integrated terminal in a remote window, e.g. WSL or containers.
`--remote` is there only supported in combination with `-n`, not by itself

**Comment by rchiodo** [comment]
@aeschli Sorry, but I still don't understand.

These command line flags are for 'code.exe'? And they only make sense when running them from within a remote terminal from an already connected VS code?

So I would test this by?
1. Open WSL connected VS code
2. Open terminal
3. Type 'code-insiders -n --remote local'

**Comment by aeschli** [comment]
Yes, in the integrated terminal. There the `code-insiders` command is a command that we provide. It talks directly to the remote server.
![recording (4)](https://user-images.githubusercontent.com/6461412/144385593-82638587-522f-48b0-9124-e310271c85a6.gif)

**Comment by rchiodo** [comment]
/Verified. Thanks. Makes sense now.
