### ISSUE TITLE
Synchronization of Mac OS and windows account settings

### ISSUE THREAD

**Issue by fanxiangyang** [microsoft/vscode#137591]
Issue Type: <b>Feature Request</b>

As for synchronization settings, I often develop on two platforms, windows and MacOS, but each synchronization has conflicts. Can I synchronize different data on completely different platforms, can I synchronize different functions of each platform independently, or can some functions be synchronized in general,
Can I completely separate MacOS from window because the development environment, settings, or plug-ins I deploy on different platforms are different

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.22494
Restricted Mode: No

**Comment by CodeCrazy-ywt** [comment]
About the issue of settings sync: I often develop on two OSes: Windows & MacOS. However, everytime I sync, conflicts occur. Can (part of) data on different OSes synced separately?

**Comment by sandy081** [comment]
@fanxiangyang Please let us know what data you are seeing in conflicts?
