### ISSUE TITLE
Feature request:  Add setting for MDN Reference links in hover to be double-click instead of single-click

### ISSUE THREAD

**Issue by TamirCode** [microsoft/vscode#137503]
The hover is useful, especially in programming languages like Javascript where the MDN Reference link doesnt show, however in HTML for example it includes a MDN Reference link which I always accidently click and its super annoying. Hence, I don't want to disable hover completely because I would like it to be there but I want a setting to make the link double-click instead of single-click so I don't accidently click it and it opens browser and ruins my work flow. Thank you!
![image](https://user-images.githubusercontent.com/66864667/142617637-01df76ea-f373-418a-969d-e36da229d10b.png)

**Comment by gjsjohnmurray** [comment]
What makes you click it? Are you trying to click something else?

**Comment by TamirCode** [comment]
> What makes you click it? Are you trying to click something else?

for example when I intend on clicking the element tag above the one i am hovering over (if i was hovering on it for less than 2 seconds) then unexpectedly the popup will appear and I would click the link instead. Happens to me all the time.

**Comment by TamirCode** [comment]
> Would #111016 suit you?

It would definitely help decrease the amount of accidental clicks, but I think my solution would solve it better because there will still be some cases where the person will attempt to click the element above which is off to the right, so moving it to the right might be a step up but it's just kicking the can down the road.
