### ISSUE TITLE
ApplicationInsights timesout in Azure DevOps build task (node js)

### ISSUE THREAD

**Issue by kh-yash** [microsoft/vscode#137540]
I have an azure devops task extension that is installed in our pipeline. This task sends telemetry to Azure App Insights to record metrics and events. App Insights js library is throwing this error in some of the builds. 

ApplicationInsights:AzureVirtualMachine [ { Error: connect ETIMEDOUT 169.254.169.254:80
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '169.254.169.254',
    port: 80 } ]

Does anyone know what could be the potential problem?

**Comment by roblourens** [comment]
This doesn't sound related to vscode, and I can't help, sorry
