### ISSUE TITLE
Red things 

### ISSUE THREAD

**Issue by Sh0rtyyy** [microsoft/vscode#137577]
Hello, I uptade my windows 11 on last update (20/11/2021). And after i finish it. It shows a red things in my program. 
![image](https://user-images.githubusercontent.com/94754507/142733384-81487bea-1625-4b08-86b4-f16079234467.png)

**Comment by gjsjohnmurray** [comment]
Is this setting checked for you (the default)?

![image](https://user-images.githubusercontent.com/6726799/142733990-4d486158-8dff-4595-a764-7d5f1ddfcd57.png)

If yes, do the "red things" disappear?

If they do, it looks like your program file contains control characters.

**Comment by Sh0rtyyy** [comment]
> 
I have it checked, but red things not disappear. And it started doing random after update windows to newest for windows11

**Comment by gjsjohnmurray** [comment]
I meant to write "do they disappear if you uncheck it?"

**Comment by Sh0rtyyy** [comment]
When i uncheck, it disappear. But there is some bugy things 
![image](https://user-images.githubusercontent.com/94754507/142734990-c2374844-4433-401f-9d43-1c8cd4622162.png)

**Comment by gjsjohnmurray** [comment]
If you load your program file into a different editor (maybe Notepad) does it look OK? If not, the problem isn't specific to VS Code.

**Comment by Sh0rtyyy** [comment]
Oh, its same in notepad. 
Can it be because i install new update to windows 11  ?

**Comment by roblourens** [comment]
You have some control characters in this file. Maybe it got corrupted somehow. Or they were added by some other program.
