### ISSUE TITLE
Eliminate the need for ELECTRON_RUN_AS_NODE

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#137510]
With the new argument `--ms-enable-electron-run-as-node`, can we now eliminate the need that the env variable 'ELECTRON_RUN_AS_NODE` needs to be set?

That means, to use the Electron executable to run a node program all that would be needed is the `--ms-enable-electron-run-as-node` argument.

This would simplify our code:
- at all the places where we need to make sure that ELECTRON_RUN_AS_NODE is unset and not inherited by child processes to not impact the execution of other ELECTRON programs
- in the WSL extension where it's quite a dance to set the env variable on the Windows side when starting VS Code from the Linux side

**Comment by aeschli** [comment]
@alexdima, speak up if that is not a good idea

**Comment by deepak1556** [comment]
The argument `--ms-enable-electron-run-as-node` will go away when https://github.com/electron/electron/pull/40579 is adopted. Closing as not actionable.
