### ISSUE TITLE
Add extension profiles

### ISSUE THREAD

**Issue by rickstaa** [microsoft/vscode#137505]
https://github.com/microsoft/vscode/issues/15611 gives users the option to disable and enable specific extensions for a given workspace. This feature is excellent, but I think it can be improved even further with extension profiles. An extension profile is a particular set of extensions that are enabled when this profile is set in your vscode `settings.json` file:

```json
{
    "extensions.profile": "CPP",
}
```

Users would then be able to add extensions to a profile and enable these sets for specific workspaces.

**Comment by gjsjohnmurray** [comment]
/duplicate

See #116740, #40239, #39272

**Comment by rickstaa** [comment]
@gjsjohnmurray Thanks I missed those.

**Comment by g13013** [comment]
coupled with #137091 it would be awesome !
