### ISSUE TITLE
Fail to create a project. Error: end of central directory record signature not found

### ISSUE THREAD

**Issue by aleparrado** [microsoft/vscode#137582]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.3 (Universal) 
- OS Version: macOs 12.0.1
Steps to Reproduce:

1. Fail to create a project. Error: end of central directory record signature not found spring initializr

**Comment by Juuuanvelasquez** [comment]
I have the same problem

**Comment by roblourens** [comment]
This doesn't sound like an issue with vscode. Please give more details if you think it's a vscode issue.

**Comment by Patpat125** [comment]
Currently having the same problem. 

Fail to create a project. Error: end of central directory record signature not found
source: Spring initializer

This is after trying to create a new maven project using Spring Initializer extension, so I am not sure if this is a vscode or extension problem

**Comment by weinand** [comment]
Please file this issue against the Java extension.
