### ISSUE TITLE
new search seed option for Ctrl+F3 behavior

### ISSUE THREAD

**Issue by hansifer** [microsoft/vscode#137550]
I'd like an option for "Seed Search String From Selection" that does the same things as "selection" EXCEPT for Ctrl+F3 initiated searches. For that particular case, I'd like the search to also be possible to be seeded by the word at the cursor position. This is the way other editors (eg, Sublime) behave and makes sense since Ctrl+F3 is then always predictably a seeded search and F3 a repeated search. Currently however with the "selection" option Ctrl+F3 and F3 behave the same (as a repeat search) when there is no selection.

I'd also be happy if the behavior of the "selection" option was changed to above, but I'm guessing a new option is more likely.

**Comment by hansifer** [comment]
Oh and it would be cool if Ctrl+F3 auto-selected whole word (and possibly case-sensitive) search when seeded from word at cursor position.

**Comment by nikita-r** [comment]
I believe that the `"editor.find.seedSearchStringFromSelection": "never"` choice should behave the way the OP requested.

As of now, with this option choice, Ctrl+F3 behaves the same as F3, which **contradicts** Ctrl+F3 command name (*nextSelectionMatch*):
```json
"key": "ctrl+f3",               "command": "editor.action.nextSelectionMatchFindAction"
```
<br />
On a related note, `"ctrl+shift+f"` does not respect this setting at all; would be nice if devs created a more thorough issue to make these different commands behaviour more consistent with their descriptions and this setting.

**Comment by nikita-r** [comment]
Intuitively, Ctrl+F3 should pick its search term in the same way as Ctrl+D does (in which case, this setting would not be relevant at all — maybe a new issue is in order.)
