### ISSUE TITLE
Visual Studio Code  Terminal Not Synced With Github Now

### ISSUE THREAD

**Issue by RichardTimothy1307** [microsoft/vscode#137534]
Issue Type: <b>Bug</b>

1. When Pushing code to github the terminal says 
remote: No anonymous write access.
fatal: Authentication failed for 'https://github.com/RichardTimothy1307/CodeForces.git/'

Please Fix it Quickly

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.11.0-40-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1899)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 2|
|Memory (System)|7.65GB (0.16GB free)|
|Process Argv|--unity-launch --crash-reporter-id a870ef67-e833-4a0f-8e49-1c177a62d072|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
doxdocgen|csc|1.3.2
vscode-eslint|dba|2.2.2
javascript-ejs-support|Dig|1.3.1
vscode-toggle-column-selection|eri|1.0.6
prettier-vscode|esb|9.0.0
file-icons|fil|1.0.29
auto-close-tag|for|0.5.13
CppSnippets|har|0.0.15
stylelint-plus|hex|0.56.6
better-cpp-syntax|jef|1.15.10
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.10.0
LiveServer|rit|5.6.1
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593:30376534
vssld246cf:30401891

```

</details>

**Comment by deepak1556** [comment]
Can you provide the output of following command from the vscode terminal,

```
env | grep VSCODE_GIT_ASKPASS_EXTRA_ARGS
```

**Comment by RichardTimothy1307** [comment]
VSCODE_GIT_ASKPASS_EXTRA_ARGS=

**Comment by rojserbest** [comment]
Same problem on same platform.

**Comment by rojserbest** [comment]
I had the same problem on the same platform, I was able to resolve it, like this:

- I clicked the profile icon on the bottom left, and signed out of GitHub.
- I opened the Source Control Tab Ctrl+Shift+G.
- I clicked on the three dots in that tab.
- I clicked push.
- It asked me to sign in to GitHub again.
- I authorized it and it was fixed.

**Comment by deepak1556** [comment]
@RichardTimothy1307 it looks like you are using a restored terminal session, once `1.62.3` is updated can you create a new terminal session and check the output of same command. It would also be great if you can attach a screen recording of the steps you are performing. Thanks!

**Comment by RichardTimothy1307** [comment]
export VSCODE_GIT_ASKPASS_EXTRA_ARGS="--ms-enable-electron-run-as-node"
The above worked for me and yes it was a restored terminal session so i created a new terminal session 
Thankss....

**Comment by deepak1556** [comment]
You don't have to export the variable, it should have already been set within the application. Can you also clarify if the issue is still present ?

**Comment by RichardTimothy1307** [comment]
No it isnt present its solved

**Comment by rojserbest** [comment]
@deepak1556 I'm not and wasn't using a restored terminal session. :)
