### ISSUE TITLE
Improvement on 'Search in Files'

### ISSUE THREAD

**Issue by nicsav** [microsoft/vscode#137581]
Issue Type: <b>Bug</b>

It seems that the feature tries to display some snippet of a line so as show the search target string as well as have it fit in a small horizontal space. I could not find this documented in the feature description.

While this is worthwhile, I see two problems with the current implementation: 

1. it can drop useful information (e.g. the fact that the line is commented out)
2. it is not indicating that there was elided text

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.42.2.el7.x86_64
Remote OS version: Linux x64 3.10.0-1160.42.2.el7.x86_64

**Comment by nicsav** [comment]
See example in: https://github.com/microsoft/vscode/issues/137265

**Comment by IllusionMH** [comment]
Do you have any suggestions for improvement or just question (which makes title misleading)?

Comments are language specific so simple text search can't tell if it's comment or not etc.

As was mentioned in linked issue "Open in editor" that is displayed above search results was created to show more context that you are looking for.

> it is not indicating that there was elided text

Is it suggested improvement to include some ellipsis if text was trimmed before?

**Comment by nicsav** [comment]
Yes, my improvement suggestions when the entire line cannot be displayed would be to 

 1. include the first few (I think 3 is usually enough) non-whitespace characters so as to keep useful information that usually resides there (is the code a commment, preprocessor, etc line)
 2. use ... to indicate where code was elided on the left hand side, much like it's done on the right hand side of the search pane

'Open in Editor' is good when full context is needed but results in unwanted context switches when the line I click on just turns out to be a comment line that I would not care to look at.

**Comment by nicsav** [comment]
Here's one example where the find shows a rather unhelpful snippet.

The snapshot:
![find_in_files](https://user-images.githubusercontent.com/80062537/143986714-90a8d2e4-3cea-473f-ae69-eae92ed3765e.png)

The file:
[find_in_files_ellision.txt](https://github.com/microsoft/vscode/files/7622962/find_in_files_ellision.txt)

**Comment by roblourens** [comment]
Will address this in https://github.com/microsoft/vscode/issues/95375
