### ISSUE TITLE
Some time backspace and arrow and some commands and many other buttons are not working 

### ISSUE THREAD

**Issue by SureshKumar311** [microsoft/vscode#137542]
Issue Type: <b>Bug</b>

Some time backspace and arrow and some commands and many other buttons are not working  but after  i unfocus the editior it's working fine 

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.22489
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.42GB (0.97GB free)|
|Process Argv|--crash-reporter-id 10c8d6e7-4585-4fb6-8b63-8d12a2c2af46|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|13.0.0
ccs-flutter-color|cir|1.0.1
dart-code|Dar|3.28.0
flutter|Dar|3.28.0
getx-template|duc|1.1.4
prettier-vscode|esb|9.0.0
bloc|Fel|6.2.0
pubspec-assist|jer|2.3.2
awesome-flutter-snippets|Nas|3.0.2
indent-rainbow|ode|8.2.2
quicktype|qui|12.0.46
getxresources|Rau|0.1.4
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30402085
vsaa593:30376534
vssld246:30401890
vscexrecpromptc:30400060

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command to investigate whether any of your extensions are causing this.

**Comment by SureshKumar311** [comment]
yea I had tried but the issue is not coming always and it's some time comes when mostly working after for long hours

**Comment by roblourens** [comment]
The command "Toggle Keyboard Shortcuts Troubleshooting" could help you check whether a different command is being run instead of the one you expect
