### ISSUE TITLE
make php heredoc/nowdoc use syntax highlighting from extension

### ISSUE THREAD

**Issue by heyjoe1984** [microsoft/vscode#137539]
right now, in PHP heredoc/nowdoc, we can syntax highlight certain languages

for example, HTML:

![](https://i.imgur.com/iV1hLDA.png)

notice how the HTML tags are green, but the Laravel Blade syntax is not coloured

now, if I try and change the nowdoc tag to BLADE, I get no colouring:

![](https://i.imgur.com/R4wl9YQ.png)

I want to mention I have an extension installed which does colour the contents of `.blade.php` files properly:

![](https://i.imgur.com/qPUUk33.png)

my goal is to have the same effect inside of the heredoc/nowdoc.

I have tried various extensions for Laravel Blade syntax highlighting and none of them work inside heredoc/nowdoc. I looked at their source codes and most of them only scope to `.blade.php` file types, but some of them were scoped to html, yet it still does not work when using HTML heredoc/nowdoc.

I am willing to create my own extension for this if you can tell me how I can apply syntax colouring inside of php heredoc/nowdoc scopes.

thanks for your time.

**Comment by KapitanOczywisty** [comment]
https://github.com/atom/language-php/pull/432 PR pending

**Comment by KapitanOczywisty** [comment]
@roblourens You can close the issue. I've tested `<<<BLADE` syntax with following extension: https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade

**Comment by roblourens** [comment]
Looks like we have updated our php grammar since that PR 👍
