### ISSUE TITLE
Add padding between the glyph margin and editor; or allow a user preference to disable breakpoints in the glyph margin and collapse arrows

### ISSUE THREAD

**Issue by aminomancer** [microsoft/vscode#137596]
I know it's a minor thing but the breakpoints drive me crazy, and the only way I know of to hide them is to disable the glyph margin. But a lot of addons use the glyph margin to display things that are far more useful to me than breakpoints, so turning the whole thing off is worse than putting up with the breakpoints. It would be nice to not have to waste time compulsively aiming and clicking to remove breakpoints I accidentally made. I have literally never made a breakpoint on purpose, and I've made hundreds, if not thousands, by mistake, just trying to move my caret to the first column in the editor. And then I feel the need to get rid of them for some asinine psychological reasons.

If there was some horizontal padding in the editor such that you didn't have to aim so precisely to click into the first column, that would be fine too. As it is, the first column requires pretty precise aiming, which is too bad because it's the column you're most likely to want to select, when multiple columns of a given row are filled with text at least. If there was some additional padding there, such that you could click like 5px into the gutter and still select the first column rather than selecting nothing (or accidentally clicking a collapse arrow or breakpoint button), then this wouldn't be so much of an issue for me. But becuse the clickable area is so small, it forces me to move my mouse really close to the margin before clicking. Which means I often end up clicking the margin instead.

Normally I would prefer to keep font size at 14 and zoom at its default value. But because of this I have to use zoom 2 or font size 16 (and zoom seems to be better for my purposes). I'm still clicking in the gutter all the time, but if I had everything set to the default values it would be happening way more often. I'm using a 4K monitor for most of this work, but that's with 150% scaling, and it's a big monitor. Truth be told the problem is worse on my laptop, since even though the pixels are smaller, the input device is way less precise than the mouse I ordinarily use.

**Comment by gjsjohnmurray** [comment]
Related to #135114

/assign @alexdima

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/135114
