### ISSUE TITLE
terminal

### ISSUE THREAD

**Issue by TimothyRioux** [microsoft/vscode#137556]
Issue Type: <b>Performance Issue</b>

terminal fails to launch claims the starting directory doesn't exist

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.76GB (6.63GB free)|
|Process Argv|--crash-reporter-id 0250c510-6de3-4d24-a735-c44e9928ff80|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    85	 12284	code main
    0	    37	   700	   utility
    0	   202	  1020	   window (main_1.cpp - a3 - Visual Studio Code)
    0	   124	  7928	     extensionHost
    0	    68	 14904	       "C:\Users\tmrki\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\tmrki\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=7928
    0	    39	 16316	       c:\Users\tmrki\.vscode\extensions\ms-vscode.cpptools-1.7.1\bin\cpptools.exe
    0	    21	  9972	         c:\Users\tmrki\.vscode\extensions\ms-vscode.cpptools-1.7.1/bin/cpptools-srv.exe 16316 {3910EA77-585C-4140-87CD-8665FFC7A8C9}
    0	    10	 13164	         console-window-host (Windows internal process)
    0	    65	 13140	     watcherServiceNSFW
    0	   304	  4092	   gpu-process
    0	    90	  4796	   shared-process
    0	    67	  1328	     ptyHost
    0	    24	  5664	   crashpad-handler
    0	    81	 16176	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (main_1.cpp - a3 - Visual Studio Code)
|    Folder (a3): 9 files
|      File types: cpp(6) cppcount_first(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.4.0
gitignore|cod|0.7.0
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|11.7.0
better-cpp-syntax|jef|1.15.10
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
cpptools|ms-|1.7.1
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30402085
vsaa593:30376534
vssld246:30401890

```

</details>

**Comment by meganrogge** [comment]
check your path / settings
