### ISSUE TITLE
Python formatter very slow

### ISSUE THREAD

**Issue by chemelli74** [microsoft/vscode#137573]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.3 (and previous one as well)
- OS Version: Windows 10 21H1

Steps to Reproduce:

1. Using dev container for Python development
2. Save a file
3. Wait foe the action to complete; takes up to 2 minutes

Message shown:

![image](https://user-images.githubusercontent.com/57354320/142726280-320f5336-d384-4e7b-b3fd-2b18d1ea1b6a.png)

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
