### ISSUE TITLE
Sometimes cannot drag .ipynb notebook cells to reorder

### ISSUE THREAD

**Issue by p-i-** [microsoft/vscode#137549]
Issue Type: <b>Bug</b>

Create a .ipynb notebook
Create 2 cells, maybe:
```
a=1
```
and
```
b=2
```

Now try dragging to reorder so that `b=2` is the top cell.

This will likely work on a fresh notebook, but often it doesn't work.

It's SUPER annoying. I have to create a new cell and cut-paste the old cell into it and delete the old cell.

A minimap of cells that supports drag-drop reordering would be nice. Even at the best of times, reordering cells by drag-drop is clumsy as slow scroll speed.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 208511c2-dba0-4576-b4d0-606dd0e49428|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
rtf|ale|2.4.0
bracket-pair-colorizer-2|Coe|0.2.1
dart-code|Dar|3.28.0
flutter|Dar|3.28.0
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.7.0
php-debug|fel|1.22.0
go|gol|0.29.0
lldb-vscode|lan|0.2.3
vscode-docker|ms-|1.18.0
vscode-kubernetes-tools|ms-|1.3.4
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
terraform-advanced-syntax-highlighting|pjm|1.4.0
java|red|1.0.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.0
LiveServer|rit|5.6.1
cmake|twx|0.0.17
vscode-lldb|vad|1.6.10
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
debug|web|0.25.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30402085
vsaa593:30376534
vssld246:30401890

```

</details>

**Comment by p-i-** [comment]
Ok so I can workaround buy "cut cell" and "paste cell", but "paste cell" should surely be 2 options: "paste cell above" and  "paste cell below", otherwise it is ambiguous. Does it mean:
- paste above this cell
- replace this cell
- paste below this cell

**Comment by roblourens** [comment]
What exactly happens when it doesn't work? Can you get the blue line to show up when dragging over the top cell?

A tip, you can also use "alt+up/down" to move a cell up/down

**Comment by p-i-** [comment]
https://user-images.githubusercontent.com/693495/143532571-81b5d95a-f6cf-4310-90da-59a9fd1beca3.mov

**Comment by p-i-** [comment]
PS Thanks for the tip!

**Comment by roblourens** [comment]
I'm not sure what's going on here, might have to add some logging

**Comment by p-i-** [comment]
Just throwing it out as an idea:
How about:
- hover over the left-of-cell region (currently gives a HAND cursor) lights the background of the  cell
- left clicking selects that cell, maybe puts a green outline around it
- now hovering over same region of a cell 3 cells below and And SHIFT+leftclick selects that range of cells.
- and you can CMD+x/c/v to cut/copy/paste. maybe  they go dark once CMD+x has been used to CUT them.
- also allow CMD+click to add/remove a cell to/from the selection
i.e. just like selecting files on File Explorer

- And hovering over the space between cells brings up the DIVIDER line
- clicking on that selects that divider line, and a CMD+v PASTES the cells at that location.

It's really not practical to be dragging cells around on multipage notebooks anyway.
I'd rather someone addressed the bigger problem of easy UX for shuffling cells around notebooks.

**Comment by roblourens** [comment]
I randomly was able to repro this, and debugging it was an adventure. But it turns out that the webview is eating drag events because pointer-events has been set and is overriding a CSS rule 
![image](https://user-images.githubusercontent.com/323878/146293755-facf89c2-3f9c-4c7f-afb4-e5d121f27f19.png)

That gets set when you drag a sash in vscode by this code

https://github.com/microsoft/vscode/blob/e7ea07d358a3a3892df36ba4f992af27c553e0f1/src/vs/base/browser/ui/sash/sash.ts#L561

So the repro steps are simply to resize the sidebar, then try to drag a cell. Back when I was using DND more, the webview was not an iframe.

@joaomoreno can we do this differently, like with CSS or reset pointer-events to '' instead of 'auto'? Or if needed, record all the original values then restore them. I can fix it

**Comment by joaomoreno** [comment]
Old old change: https://github.com/microsoft/vscode/commit/88b42168b39d15472e2441583e82d9326aa06eb0

**Comment by IanMatthewHuff** [comment]
Verified. Looks good for me using the repro specified here (resize sidebar then drag cells).
