### ISSUE TITLE
After updating to 1.6.1 any file is automatically touched upon opening it

### ISSUE THREAD

**Issue by mkjsix** [Microsoft/vscode#13759]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 15.6.0
- Extensions: DotJoshJohnson.xml-1.6.0, EditorConfig.EditorConfig-0.3.3, PeterJausovec.vscode-docker-0.0.6, johnpapa.Angular2-1.0.2, ms-vscode.typescript-javascript-grammar-0.0.4, rbbit.typescript-hero-0.8.0

Steps to Reproduce:

1. Open any file
2. Even if I don't touch anything, it appears like it has been modified and the IDE asks if I want to save it.

This behavior happened today, after I updated to from 1.6.0 to release 1.6.1

**Comment by isidorn** [comment]
Do you also see this behavior if you run with `--disable-extensions`?

**Comment by mkjsix** [comment]
Hi @isidorn 
I disabled all extensions and found the issue is due to the [EditorConfig](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) plugin, because if I reactivate it the issue appears again.

I will open a ticket in their repository, thank you!
