### ISSUE TITLE
Replace `enablePromptUseWorkspaceTsdk` with workspace trust workflow

### ISSUE THREAD

**Issue by DuncanWalter** [microsoft/vscode#137538]
Essentially a followup to https://github.com/microsoft/vscode/pull/95566. I think this fits better as a feature request than a bug or security issue, but 🤷 . My understanding of the security guidelines we follow leads me to believe workspace trust is a much better, more convenient solution than the `typescript.enablePromptUseWorkspaceTsdk` setting I added previously. I'd be happy to contribute this change or leave it for the team. I think the behavior should be:

- if workspace isn't trusted, then use vs code's built in ts version
- if `typescript.useWorkspaceTsdk: true` is set AND the workspace is trusted, use the workspace version
- if `typescript.useWorkspaceTsdk` isn't explicitly set to false AND `typescript.tsdk` is set, prompt the user to set `useWorkspaceTsdk` either at the workspace or user level
- the extension reevaluates these conditions whenever workspace trust or the two relevant settings change

Today,  https://github.com/microsoft/vscode/pull/95566 works but is a bit clunky and nonstandard

**Comment by mjbvz** [comment]
Duplicate of #135713
