### ISSUE TITLE
stuck on "uploading files"

### ISSUE THREAD

**Issue by heyjoe1984** [microsoft/vscode#137559]
- VS Code Version: 1.62.3
- OS Version: Mac monterey

Steps to Reproduce:

1. push laravel project to GitHub

pushing to GitHub is stuck on "uploading files" and it just hangs forever

![](https://i.imgur.com/xT525bI.png)

**Comment by joaomoreno** [comment]
Does this always reproduce? If you try again what happens?

Can you show me the full output of `Git: Show Git Output`?

**Comment by heyjoe1984** [comment]
It looks like it was actually a GitHub issue they have resolved now.
