### ISSUE TITLE
"Copy" is non functional in process explorer

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#137597]
When I select "Copy" on a process from the process explorer I would have actually expected it copies the full command line. But nothing was added to the clipboard.

Besides fixing this, it would also be nice to have a command to copy the command line so that issue reporting becomes easier.

"Copy All" works btw.

**Comment by bpasero** [comment]
@Tyriar should "Copy" support multi selection?

**Comment by Tyriar** [comment]
Yep, reopening
