### ISSUE TITLE
This issue report is returning a broken link to github

### ISSUE THREAD

**Issue by KirkH420** [microsoft/vscode#137532]
Issue Type: <b>Bug</b>

Why is there a dropdown option on this feedback form, the field called "File on," why does it have a non-acceptable choice? If I forget to select something from the dropdown, it's supposed to remind me.  But it's currently got the option "Don't Know" which I can select. However if I select it, I get a message that says "An issue source is required."

That's goofy. Probably take that out and only set it to Nag the user if they forget to select a dropdown item.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by TylerLeonhardt** [comment]
Hi @KirkH420 can you let me know what choice was a non-acceptable choice? Was this some extension? It's possible that the extension needs to update a field to point to their new issue URL.
