### ISSUE TITLE
Bracket pair highlighting of folders in Explorer

### ISSUE THREAD

**Issue by kevinmckinley** [microsoft/vscode#137554]
I'd like to be able to have folder range highlighting in the Explorer view similar to how Bracket Pair highlighting works.

**Comment by JacksonKearl** [comment]
Not sure what this would look like We do have the indent guides, do they help here? 
![image](https://user-images.githubusercontent.com/8586769/144336592-2def60f1-3833-487f-a187-a893b7835994.png)
