### ISSUE TITLE
FileSystemWatcher.onChange isn't firing when the file is changed outside of vscode

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#137574]
In Luna Paint I create a file watcher like this:

```ts
const watcher = workspace.createFileSystemWatcher(uri.fsPath, true, false, false);
watcher.onDidChange(async () => {
  ...
});
```

`onDidChange` is firing whenever I save the file in VS Code but not when I git checkout the file or save the file in another app. This was reported in https://github.com/lunapaint/vscode-luna-paint/issues/105 and it used to work in an older version of VS Code.

cc @bpasero for parcel watcher

**Comment by bpasero** [comment]
Cannot reproduce with this code:

```ts
const watcher = vscode.workspace.createFileSystemWatcher(vscode.window.activeTextEditor!.document.uri.fsPath, true, false, false);
watcher.onDidChange(uri => console.log(uri));
```

I open the file with an external program and make changes and the event is triggered.

**Couple of thoughts:**
* is the file "out of workspace" or "inside workspace"?
* is the file maybe deleted and recreated, then you might need to listen to creates too (refs https://github.com/microsoft/vscode/issues/136460)
* what OS is this on?

**Comment by Tyriar** [comment]
It's inside the workspace and on Windows 11.

I just tried it now and noticed that the tab's scm color does change back to normal so the file watcher is working, just the extension doesn't get the event. I'll try get a minimal repro

**Comment by Tyriar** [comment]
I cannot reproduce with a text file but I can with a png:

![recording](https://user-images.githubusercontent.com/2193314/142884912-7473ceb1-8971-4ad5-8354-a88b97c24320.gif)

Ext code used:

```
	const p = `c:\\Github\\Tyriar\\dotfiles\\terminal.png`;
	console.log('setup watcher for ' + p);
	const watcher = vscode.workspace.createFileSystemWatcher(p, true, false, false);
	watcher.onDidChange(uri => console.log('change event', uri));
```

**Comment by bpasero** [comment]
@Tyriar to rule out this is triggered by how Luna paint saves changes back to disk, can you try with a different editor or even hex editor to see if it is related to Luna paint?

**Comment by Tyriar** [comment]
It's the git operation that's not triggering the file command, Luna Paint and Hex Editor saves both trigger change events.

**Comment by bpasero** [comment]
@Tyriar did you try what I suggested to NOT ignore create events?

```ts
const watcher = vscode.workspace.createFileSystemWatcher(p);
```

**Comment by Tyriar** [comment]
@bpasero `createFileSystemWatcher(p);` and `createFileSystemWatcher(p, false, false, false);` both don't work still

**Comment by Tyriar** [comment]
Noticed full version info wasn't on the issue:

Version: 1.63.0-insider (user setup)
Commit: 4e303fcc52269ab578affa6cb1eb455eacab445f
Date: 2021-11-22T05:28:15.683Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by bpasero** [comment]
One thing I forgot to mention: when listening to creates and deletes, the event handler needs to be `watcher.onDidCreate` because `onDidChange` only fires for changes.

The underlying issue is that parcel detects git operation changes on files as creates and not as changes, likely because there is a rapid delete and create that previously our old watchers would detect as change. Upstream: https://github.com/parcel-bundler/watcher/issues/72

**Comment by Tyriar** [comment]
I noticed some inconsistent behavior just now when I tried to reproduce it again:

- Sometimes 2 change events are fired when I save a file with Luna Paint
- Sometimes a change event _does_ fire when I do a git checkout, but it's inconsistent
- Create events fire when saved with Luna Paint, but not delete events, shouldn't delete be fired first?

It would be great if it was more consistent, but for now it looks like I can work around my issue by just treating `onDidCreate` as an update event. We should consider adding to `createFileSystemWatcher` docs about this common delete/create mechanism for updating so extensions don't need to investigate this same issue all over again.

**Comment by bpasero** [comment]
I have a PR opened to address this because I think the current behaviour is not ideal: https://github.com/parcel-bundler/watcher/pull/84

**Comment by Tyriar** [comment]
Nice thanks! Yes this is on Windows 11

**Comment by bpasero** [comment]
@Tyriar I am not able to reproduce the 2 change events for saving an image with Luna paint, maybe if you have steps and a sample image, I can try to reproduce and see if the flags in parcel watcher cause this.

**Comment by Tyriar** [comment]
I was using the extension code in https://github.com/microsoft/vscode/issues/137574#issuecomment-975620634 with the image https://github.com/Tyriar/dotfiles/blob/master/terminal.png, drawing some squiggles and saving using machine in https://github.com/microsoft/vscode/issues/137574#issuecomment-975729915.

The 2 change events doesn't cause any problems for me fyi, just a bit weird.

**Comment by bpasero** [comment]
Hm ok I can still not reproduce. 

@Tyriar to proof my point, could you do this:
* `git clone https://github.com/parcel-bundler/watcher.git`
* find the usage of `ReadDirectoryChangesW` in the sources
* change the flags to `FILE_NOTIFY_CHANGE_FILE_NAME | FILE_NOTIFY_CHANGE_DIR_NAME | FILE_NOTIFY_CHANGE_LAST_WRITE`
* `yarn`
* replace the `node_modules/@parcel/watcher/build/Release/watcher.node` with the version you just built

I mainly wonder if the flags to `ReadDirectoryChangesW` are the culprit here or not.

Thanks!
