### ISSUE TITLE
VSCE Package fails on tsc -p ./

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#13756]
- VSCode Version: 1.6
- OS Version: wind 10

Im getting following error in making the package of extension.

![capture](https://cloud.githubusercontent.com/assets/8774556/19388106/59dc49f6-9237-11e6-8c1c-de893eb3dbb4.PNG)

 **Package.json**

```
 "scripts": {
    "vscode:prepublish": "tsc -p ./",
    "compile": "tsc -watch -p ./",
    "postinstall": "node ./node_modules/vscode/bin/install"
  },
 "devDependencies": {
    "typescript": "^2.0.3",
    "vscode": "^1.0.0"
  },
  "dependencies": {
    "@types/es6-shim": "^0.31.32",
    "@types/node": "^6.0.45",
    "adm-zip": "^0.4.7",
    "fs": "^0.0.2",
    "github": "^2.6.0",
    "ncp": "^2.0.0",
    "node-watch": "0.4.0",
    "open": "^0.0.5",
    "rimraf": "^2.5.4",
    "temp": "^0.8.3"
  }
```

**Comment by joaomoreno** [comment]
What happens if you run `tsc -p ./` in your command line?

**Comment by shanalikhan** [comment]
Im getting this error in es6-shim and other node packages. how i can exclude these one not to compile.

my **TSconfig.json**

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "outDir": "out",
        "lib": [
            "es6"
        ],
        "sourceMap": true,
        "rootDir": "."
    }, 
    "exclude": [
        "node_modules",
        ".vscode-test"
    ]
}
```


![capture](https://cloud.githubusercontent.com/assets/8774556/19408381/066add98-92d5-11e6-9e07-60f1db5152a7.PNG)

**Comment by bsed** [comment]
kelvin@gnux:~/rls_vscode> vsce package
Executing prepublish script 'npm run vscode:prepublish'...
Error: Command failed: npm run vscode:prepublish
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! rls-vscode@0.0.1 vscode:prepublish: `tsc -p ./`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the rls-vscode@0.0.1 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kelvin/.npm/_logs/2017-06-17T06_57_22_882Z-debug.log

kelvin@gnux:~/rls_vscode>                            (ma
