### ISSUE TITLE
Opening PNG file crashes VSCode

### ISSUE THREAD

**Issue by foucdeg** [microsoft/vscode#137501]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

- Open a PNG file from the explorer
- the file doesn't appear
- I see an error notification: 

`Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..`

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.4.0-89-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2478)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|5, 4, 4|
|Memory (System)|15.52GB (1.01GB free)|
|Process Argv|--no-sandbox . --crash-reporter-id 3b63fda6-abd5-4a74-bb2c-203be5950901|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
django-html|bib|1.3.0
better-toml|bun|0.3.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
hadolint|exi|1.1.0
vs-code-xml-format|fab|0.1.5
vscode-graphql|Gra|0.3.18
vscode-styled-components|jpo|1.6.6
dotenv|mik|1.0.1
language-gettext|mro|0.2.0
vscode-docker|ms-|1.18.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
vsliveshare|ms-|1.0.5090
vscode-jest|Ort|4.2.1
shellcheck|tim|0.18.2
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593:30376534
vssld246cf:30401891
vscexrecpromptt3:30400063

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command to check whether any of your extensions are involved in this issue.
