### ISSUE TITLE
Open a blank diff view

### ISSUE THREAD

**Issue by nyctef** [microsoft/vscode#137516]
Sometimes there's just arbitrary text that I'd like to see a diff view of (eg output from sharplab.io). In this case, the text for both sides of the diff will come from the clipboard.

Current workaround: 
- Open a random file
- Ctrl-Shift-P and "Compare Active File With..." a random other file
- Paste the text to diff over the existing file contents
- View the diff
- When done, revert changes to the affected files

**Comment by kartikeyporwal** [comment]
Can I suggest another usecase for the same?

Usecase:

- Allow comparison of two snippets of text in a single file

Sometimes I select two snippets of text in a file using `Alt` and there is a need to check their comparison; VS code can allow to open a temporary diff window if the selected text block count is 2 by `selecting text` &#8594; `right click` &#8594; `compare the selected text`.

Current workaround I follow:
- Create two random files
- Put content in each file
- Compare the result
- Delete the files


Please let me know if it needs a fresh issue!
