### ISSUE TITLE
Add to watch adds an invalid expression

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#1375]
I have an array of objects, each of which object exposes two fields. I inspect the array in the debugger, expand one of the items in the array, then right click on one of the fields and 'Add to Watch'. E.g., I click on myArray[1].firstField then choose add to watch. I expect to see myArray[1].firstField added as a watch expression but instead I get myArray.[1].firstField  (a dot is added between myArray and the array index.

See below:
![debugger](https://cloud.githubusercontent.com/assets/1704059/11839123/4fb3e4d6-a3e3-11e5-9964-a176703ebaad.gif)

**Comment by isidorn** [comment]
Nice catch will fix for January

**Comment by isidorn** [comment]
@stevencl I fixed the issue, assigning it to you know so you can verify. Once you do that just add a **verified** tag to this bug.
