### ISSUE TITLE
[BUG?] VS Code server not asking to open local service in browser

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#137545]
Does this issue occur when all extensions are disabled?: Not possible, because it needs the Remote extensions.

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Connect to a remote server with Remote-SSH
2. Run a Spring Boot app on port 8080
3. VS Code does not ask me to open the localhost:8080 URL in my browser.

The box I was expecting to pop up, but didn't, should look something like this:

```
Your application running on port 9000 is available. See all forwarded ports
| Open In Browser |     | Preview in Editor |
```

When I run other apps, for example the Node.js-based `npx serve .` to start a web server, that works fine, and VS Code somehow picks it up and asks me if I want to open the app in my browser.

For some reason VS Code just doesn't do this when I run a Spring Boot server.

**Comment by alexr00** [comment]
@trusktr can you share the following:
- The value of the setting `remote.autoForwardPortsSource`
- The terminal output of your Spring Boot app

SSH by default sets `remote.autoForwardPortsSource` to `output`, meaning that the terminal output is read to determine when to auto forward ports and show the prompt.
