### ISSUE TITLE
Can not open newfile on WSL

### ISSUE THREAD

**Issue by thanhphatit-pmc** [microsoft/vscode#137572]
I can not open new file when use console on wsl with:
code dataset.yaml
Note: dataset.yaml is a new file, but it's not open to my VS

**Comment by bpasero** [comment]
Maybe https://github.com/microsoft/vscode/issues/137409

**Comment by lszomoru** [comment]
Could you please try with today's Insiders as it contains a fix for #137409. Thank you!

**Comment by aeschli** [comment]
Closing as dup of https://github.com/microsoft/vscode/issues/137409. If you still see the issue, please speak up.
