### ISSUE TITLE
Sync getting started walkthrough state

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#137526]
I don't think the state of walkthrough progress is synced between machines, so I see this on each new machine I setup:

![image](https://user-images.githubusercontent.com/2193314/142650959-269d37fd-bb2c-4e10-b3d0-dcf0d088cf77.png)

**Comment by JacksonKearl** [comment]
Again, we do try to sync the state but there may be a race where it's not available in time. I'll investigate more..

**Comment by sandy081** [comment]
Fixed it by adding the context to the installation event when extensions are synced by settings sync. Walk through component shall simply ignore walk through for those extensions which are installed by settings sync (irrespective of the walk through state is synced or not).
