### ISSUE TITLE
Emmet not working for js/jsx files for vscode 1.62.3 (Ubuntu 20.04)

### ISSUE THREAD

**Issue by preIdiot** [microsoft/vscode#137566]
This issue is similar to [issue for v1.62.2](https://github.com/microsoft/vscode/issues/137012), but I am experiencing this after updating to v1.62.3.

https://user-images.githubusercontent.com/61873006/142715720-c1f2ec56-7efa-48e7-85e9-06fa8c2d2d9a.mp4

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/issues/137012#issuecomment-974750802

/duplicate
