### ISSUE TITLE
Accessiblity bug: New activity bar flow requires mouse to create PRs

### ISSUE THREAD

**Issue by nschonni** [microsoft/vscode#137517]
- Extension version: v0.23.0
- VSCode Version:
1.53.0 (user setup)
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
- OS: Windows 10

Steps to Reproduce:

1. Create a new PR from command palet
2. Activity window opens, but you can't focus on the Create button without the mouse

In the old flow, you could accomplish creating a PR from the keyboard alone:
1. Create pull request from command pallet
2. Use enter key and text inputs for adjust value

**Comment by alexr00** [comment]
@mjbvz I'm only sometimes able to tab into sidebar webviews. If I try to get there from the activity bar, it's ok, but if I click around then try to tab in I can't always get into the webview.

**Comment by mjbvz** [comment]
Closing as we haven't seen other reports of this issue over the past year
