### ISSUE TITLE
maintain history of past search and replace

### ISSUE THREAD

**Issue by theodore-wilson-amd** [microsoft/vscode#137535]
Issue Type: <b>Feature Request</b>

A comparative editor slickedit maintains a history of past regex used in the current session.  This is missing from vscode in that if I start editing a new file I don't have the regex history of edits on other files immediately available for the current file.  slickedit's feature in this regard is imperfect in that updating a past regex for a new search/replace will replace the previous... the history of regex could be more carefully managed for a user.   regex are an extremely powerful and fast way to perform consistent updates within and across files.

Best regards,

Ted

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.24.1.el7.x86_64

**Comment by roblourens** [comment]
You can access history by using the up/down arrow keys

**Comment by theodore-wilson-amd** [comment]
I can easily open a new file and have no past regex search and replace to chose from via up/down arrows in which case I have to retype the regex from memory and hence the original ticket.
