### ISSUE TITLE
[Inline suggestions] Clicking the command in the inline suggestion tooltip resets editor zoom

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [microsoft/vscode#137512]
- VS Code Version: Latest insider
- OS Version: macOS 12.0.1

Originally reported in https://github.com/github/feedback/discussions/7833

Steps to Reproduce:

1. Change the zoom level in the editor
2. Hover on the inline suggestion to get the tooltip with commands
3. Click any command
4. Observe how to zoom level was changed

https://user-images.githubusercontent.com/5427083/142630743-b2273a26-256b-4448-90cd-3869848c720c.mov

CC: @hediet

**Comment by hediet** [comment]
`applyZoom` is not being called. This is really weird.
Also note that zoom in/zoom out will start with the last zoom level, even if triggering one of those commands will reset it temporarily.

@bpasero do you have an idea?

**Comment by bpasero** [comment]
Can you open settings to the side in a text editor and find the `"window.zoomLevel": 1` entry and see if that is updated?

**Comment by bpasero** [comment]
@hediet you can repro?

**Comment by hediet** [comment]
yes, always, and I think it does not change the zoomLevel setting

**Comment by bpasero** [comment]
Steps?

**Comment by rchiodo** [comment]
I can't repro this with 1.62 but I don't have copilot access. @hediet is there a way to repro without copilot?

**Comment by hediet** [comment]
@rchiodo unfortunately, there is no easy way yet to test this without copilot.

@Krzysztof-Cieslak can you repro?

**Comment by Krzysztof-Cieslak** [comment]
I'm unable to repro on the latest Insiders.
