### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by BelyMendoza** [microsoft/vscode#137564]
- Issue Type: `Bug`
- Extension Name: `typescript-language-features`
- Extension Version: `1.0.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.62.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by mjbvz** [comment]
Nothing to do here without more information about what is going wrong
