### ISSUE TITLE
Can't open more than 8 tabs simultaneously 

### ISSUE THREAD

**Issue by AyubM** [microsoft/vscode#137548]
Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: 1.62.3
- OS Version: Windows 10

Steps to Reproduce:

1. Open 8 files
2. Try to open more

When I try to open a tab after having 8, VS code closes the oldest one and replaces it with the newest.

Is this a setting I'm supposed to disable?

**Comment by ArturoDent** [comment]
What is the setting `Workbench > Editor > Limit: Value` set to?
