### ISSUE TITLE
Inline parameter hints are missing or duplicated

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/vscode#137500]
Issue Type: <b>Bug</b>

See screenshot:
![grafik](https://user-images.githubusercontent.com/17641229/142607472-dc8bae6a-1338-460c-b8ae-d0f6a789474a.png)

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (16.43GB free)|
|Process Argv|--crash-reporter-id 334f021d-210d-4760-a7f9-f7e771ce0905|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.2.1
tsl-problem-matcher|amo|0.5.0
vscode-zipfs|arc|2.3.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
toggle-excluded-files|eam|1.7.0
EditorConfig|Edi|0.16.4
RunOnSave|eme|0.2.0
json-tools|eri|1.0.2
prettier-vscode|esb|9.0.0
copilot|Git|1.7.3862
vscode-pull-request-github|Git|0.32.0
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.24.5
template-string-converter|meg|0.5.4
git-graph|mhu|1.30.0
compare-folders|mos|0.22.2
vscode-json5|mrm|1.0.0
vscode-docker|ms-|1.18.0
vscode-language-pack-de|MS-|1.62.4
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.11
cpptools|ms-|1.7.1
hexeditor|ms-|1.8.2
node-debug|ms-|1.45.0
node-debug2|ms-|1.43.0
powershell|ms-|2021.10.2
test-adapter-converter|ms-|0.1.4
vscode-js-profile-flame|ms-|0.0.21
vsonline|ms-|1.0.3076
hide-gitignored|npx|1.1.0
vscode-jest|Ort|4.2.1
typescript-mono-repo-import-helper|q|0.0.6
java|red|1.0.0
vscode-sort-json|ric|1.20.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
vscode-icons|vsc|11.7.0
vscode-todo-highlight|way|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593:30376534
vssld246cf:30401891

```

</details>

**Comment by AlCalzone** [comment]
Okay, now I can't reproduce anymore but the behavior is really inconsistent. I've enabled the hints for literal parameters, but they don't show up in a changed file unless I open the diff first:
![inlay_hints](https://user-images.githubusercontent.com/17641229/142608475-dece8d99-40e3-4729-b1dd-b40b0cb86720.gif)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by AlCalzone** [comment]
It's different now, but still not correct. In the diff view, I get the inlay hints once:
![grafik](https://user-images.githubusercontent.com/17641229/142698564-ccbb6e08-8686-4ae9-b1b6-5a277a8285d9.png)

In the normal file view I get none:
![grafik](https://user-images.githubusercontent.com/17641229/142698596-d646a88e-5898-4fd0-af4c-c303350913af.png)

**Comment by mjbvz** [comment]
Please a minimal example to reproduce this issue

**Comment by AlCalzone** [comment]
I cannot reproduce anymore. Closing until it shows up again.

**Comment by toshafaye** [comment]
Tosha Wade
