### ISSUE TITLE
VSC not recognizing system env. variables (Windows 11) 

### ISSUE THREAD

**Issue by Johnrobmiller** [microsoft/vscode#137682]
I reset my PC recently and was needing to install node.js and yarn.  So, I installed both and triple checked to make sure that the env. variables were set up correctly in Windows 11 (my Windows 11 version is 10.0.22000 build 22000).  Then, I verified that they were working in the terminal, and they were.  However, VSC failed to recognize node.js and yarn.  So, I restarted my computer several times and reinstall VSC.  Same problem.  Then, I installed a different IDE (atom) to see if node.js and yarn worked there.  It did.  

I could not fix this myself.  VSC is broken on my PC.

However, I found a hacky work-around.  If I start VSC from the terminal using "code", then it recognizes node.js and yarn.  However, if I launch VSC from an .exe, then it breaks.

Please fix this soon.  This bug consumed two hours of my work day, and it'll likely waste time for many other people as well.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
