### ISSUE TITLE
Indicate when multiple carets are in play

### ISSUE THREAD

**Issue by Ma-XX-oN** [microsoft/vscode#137671]
It would be very helpful if I could get some indication that multiple text carets are in play.  I've been bitten more than once where I've not escaped out of this mode and have overwritten text somewhere off screen.  A change of colour or shape of the text caret would be extremely helpful.

**Comment by IllusionMH** [comment]
It's already displayed in Status bar as "Editor Selection" (usually has "Ln XX, Col XX" instead of number of selections)

Example with 5 cursors in editors
![image](https://user-images.githubusercontent.com/1312662/142925734-6990b08e-1b38-4def-aa4c-102dc5e2dc2a.png)

**Comment by Ma-XX-oN** [comment]
Yes, that's fine, but that isn't where my eye is going when I type.  It would be better to have that information visible at the actual caret.

**Comment by Ma-XX-oN** [comment]
Yes, that's fine, but that isn't where my eye is going when I type.  It would be better to have that information visible at the actual caret.

**Comment by alexdima** [comment]
Let's track in #85630

**Comment by Ma-XX-oN** [comment]
That's cool.. Thx @alexdima.
