### ISSUE TITLE
cannot create files in left explorer pane

### ISSUE THREAD

**Issue by E-T-II** [microsoft/vscode#137606]
Issue Type: <b>Bug</b>

Whenever I click the radio button to create a file, as i'm typing the file name in, i get kicked out.

VS Code version: Code 1.59.0 (Universal) (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (2.37GB free)|
|Process Argv|--crash-reporter-id 0913caca-b5f7-4fda-b7fb-78ef3e72afec|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593:30376534
vssld246:30401890

```

</details>

**Comment by mxrachel** [comment]
Your version is a bit outdatet. The latest stable version is 1.62.3.

**Comment by JacksonKearl** [comment]
Do you have any operations ongoing that might be causing the workspace contents to change? Builds, for intance.

**Comment by E-T-II** [comment]
No. I'm the only one working on the project. The issue seemed to be resolved after uninstall and reinstall.

**Comment by JacksonKearl** [comment]
Probably 112293
