### ISSUE TITLE
Account sign-out dialog "Sign out" button caption should be "Sign Out"

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#137651]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/6726799/142880817-0278ea9a-413f-4495-88b3-8f3aab877b34.png)

The item triggering it from the Account icon's menu is captioned "Sign Out".

VS Code version: Code - Insiders 1.63.0-insider (4e303fcc52269ab578affa6cb1eb455eacab445f, 2021-11-22T05:28:15.683Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by misolori** [comment]
@TylerLeonhardt i believe this is related to the accounts sign in cc @sbatten for whether we sentence or capitalize buttons in dialogs

**Comment by sbatten** [comment]
Purely based on "Don't Save", I suppose we are not using sentence casing.
![image](https://user-images.githubusercontent.com/6561887/142935483-68dc816c-48f6-457a-8901-f0a47974ad10.png)
