### ISSUE TITLE
Can't run my Code

### ISSUE THREAD

**Issue by jani333** [microsoft/vscode#137657]
Issue Type: <b>Bug</b>

Currently I am using the latest version of Visual Studio Code and editing C language code but due to some problem I am not able to run the code as it shows some error occurring. I also tried deleting and reinstalling VS code but still can't run the code. 

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.78GB (1.30GB free)|
|Process Argv|--crash-reporter-id c2f6f8a2-e7c6-4d51-a1e7-fc1755cf9603|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593:30376534
vssld246:30401890

```

</details>

![Screenshot (1)](https://user-images.githubusercontent.com/57277829/142895338-49b41b8a-eae2-4041-a159-8d847ff90607.png)

**Comment by IllusionMH** [comment]
/question

Doesn't looks like this issue is related to VS Code editor itself.

Moreover it looks like error in code and compiles shows correct place even if message is cryptic - you forgot to specify parameters list for function `()`
https://riptutorial.com/c/example/795/hello-world
