### ISSUE TITLE
Implement the ability to swap the caret position between beginning and end of selected region.

### ISSUE THREAD

**Issue by Ma-XX-oN** [microsoft/vscode#137620]
When selecting text, I would like to be able to move the cursor to the other end of the selected text block so that I can expand it in that direction.  E.g.  If I have the following text:
```
Here is some text to select.
```
and I start selecting from the beginning of  `some` to the end of `some`, I'd then like to be able to expand the selection in the direction of `Here is`, whereas atm I can only select in the direction of `text to select.`.

Main use case is if I select a bracketed region by way of `Select to bracket`, I'd like to be able to expand the selection from the left bracket, whereas atm I can only expand the selection from the right bracket. There is a way to do this in Visual Studio, which was called `Edit.SwapAnchor` and can be seen in this SO post: [Visual Studio - keyboard shortcut to move caret/cursor to start or end of selection](https://stackoverflow.com/questions/11899015/visual-studio-keyboard-shortcut-to-move-caret-cursor-to-start-or-end-of-select).  Vim has a command `v_o` as seen by this SO post [Adjust the other end of a visual selection](https://superuser.com/questions/599717/adjust-the-other-end-of-a-visual-selection/599726#599726).

I did look through the commands available by filtering them by the keyword `select`, `anchor` and `swap`, but didn't find anything that did the job.

**Comment by roblourens** [comment]
An extension could do this

**Comment by ArturoDent** [comment]
For example: [Select By](https://marketplace.visualstudio.com/items?itemName=rioj7.select-by)  extension can swap cursor positions around a selection.
