### ISSUE TITLE
Editor save html takes longer after upgrade to 1.6.1

### ISSUE THREAD

**Issue by rayzik** [Microsoft/vscode#13762]
- VSCode Version: 1.6.1
- OS Version: Win 7 64bit

Steps to Reproduce:

1. Upgrade from 1.6 to 1.6.1
2. Enabled ``"editor.formatOnSave": true,`` 
3. When I try to save index.html with 2164 lines. It save after 2 minute or so. 
4. with this configuration ``code  --disable-extensions .``

Sometimes when I try to do something it freezes.

**Comment by isidorn** [comment]
Can you please upload the file for which it takes you a long time to save?

**Comment by rayzik** [comment]
Sorry I am out of office. I will post it next Monday.

**Comment by rayzik** [comment]
Here you go, 

Here is link to file, I was not able to upload zip.
https://drive.google.com/file/d/0Bw_W5Yz5MtywTnZoVWdhTzZ0YTQ/view?usp=sharing

**Comment by jrieken** [comment]
@rayzik What extensions do you have installed?

**Comment by jrieken** [comment]
Also, note that format on save will timeout after [750ms](https://github.com/Microsoft/vscode/blob/joh/fmtconfig/src/vs/workbench/api/node/mainThreadSaveParticipant.ts#L99)

**Comment by rayzik** [comment]
@jrieken 
All extensions are latest except __HookyQR.beautify__
__extensions__: 
dbaeumer.vscode-eslint
HookyQR.beautify ___0.4.0___
joelday.docthis
seanmcbreen.Spell
Shan.code-settings-sync
TwentyChung.jsx

**Comment by jrieken** [comment]
Do you have beautify configured to format html and format on save?

**Comment by jrieken** [comment]
Closing until steps that allow to reproduce this are supplied
