### ISSUE TITLE
Document how to develop under Windows 11

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#137654]

**Comment by dbaeumer** [comment]
Wiki is updated and a script to simplify builds under Windows is deployed.

**Comment by JacksonKearl** [comment]
Got it working based on the wiki with a few modifications:
```diff
-open a command prompt and run `npm config set msvs_version 2019`
+open a command prompt and run `npm config set msvs_version 2017`
```

also I needed to change the build scripts to `--max-old-space-size=8096` from `4095`, using 4095 threw out of memory errors.

**Comment by dbaeumer** [comment]
@JacksonKearl did you install the 2019 version of the Visual Studio build tools? 

And which error did you receive when using `npm config set msvs_version 2019`

**Comment by JacksonKearl** [comment]
I'm unable to get back into the broken state, but I found that while I did have the VS 2019 build tools installed, the "Desktop Development with C++"  was not checked, so that's probably the source of the issue. I

t's a 7GB download so I'll wait until I'm broken before putting it on my VM.

**Comment by dbaeumer** [comment]
@JacksonKearl makes sense. And thanks for getting back.
