### ISSUE TITLE
Process explorer has weird selection behaviour

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#137600]
When I click on a process it looks as if another process gets highlighted, though without focus color but somewhat disabled color:
![recording (1)](https://user-images.githubusercontent.com/900690/142753410-f58932ee-26b2-4352-9561-ae451c519544.gif)

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/115227, https://github.com/microsoft/vscode/issues/120342
