### ISSUE TITLE
terminal no longer able to paste python function definitions, each line executes individually and adds indentation unexpectedly.

### ISSUE THREAD

**Issue by TedKus** [microsoft/vscode#137673]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.62.3 (user setup)
- OS Version:  Windows_NT x64 6.1.7601 (Windows 7 Pro)

Steps to Reproduce:

1.  open vscode
2.  open new terminal
3. conda activate base
4. ipython
5. copy python definition such as:
def foo(bar):
    x = bar
    return ~x
6. go to terminal window and paste function
7. press enter to execute input
In [8]: def foo(bar):
   ...:         x = bar
   ...:             return ~x
  File "<ipython-input-8-fbe332d2fdce>", line 3
    return ~x
    ^
IndentationError: unexpected indent
8. try another function:
def get_smbalert_addr(pmbus_device) -> list:
    addrs = []
    while check_smbalert:
        addrs.append(pmbus_device.get_alert_response_address())
    return addrs
9. paste into terminal, results in:
In [9]: def get_smbalert_addr(pmbus_device) -> list:
   ...:         addrs = []
   ...:             while check_smbalert:
   ...:                         addrs.append(pmbus_device.get_alert_response_address())
  File "<ipython-input-9-c1a97e89105b>", line 3
    while check_smbalert:
    ^
IndentationError: unexpected indent
In [10]:     return addrs
10. note how the return statement hasn't been "executed" into the terminal yet, but prior lines of the function definition have been.
11. in prior versions of vscode i could copy-paste an entire python file into the terminal and it would not "execute" the input until i pressed the "enter" key at the end of the paste.  While pasting functions into the terminal is not a great way to go about coding, it was very helpful in development where processes were interrupted and needed command line debugging (without restarting the process to use the debugger).

The problem seems to be: 
1. that extra indentations are being added, as-if i typed the pasted content and pressed enter myself at the end of each line before pasting in the next line.  Note that when a python function is defined from the command line in terminal, the editor automatically indents the following lines as needed.  Seems some intelligence about when to insert the indents was lost.

hope this is helpful to finding what happened, it was a really nice feature to have break unexpectedly.
I searched, didn't find any reports or related settings I could try to massage this behavior with.

**Comment by meganrogge** [comment]
I'd be surprised if something changed here recently. I suspect what gets copied is the text with new lines/carriage returns at the end of each, so when it's pasted in the terminal, the terminal behaves appropriately and sends enter. @Tyriar thoughts?

**Comment by meganrogge** [comment]
```
xterm.js: sending data "def foo(bar):
x = bar
return ~x" (31) [100, 101, 102, 32, 102, 111, 111, 40, 98, 97, 114, 41, 58, 13, 120, 32, 61, 32, 98, 97, 114, 13, 114, 101, 116, 117, 114, 110, 32, 126, 120]
LogService.ts:62 xterm.js: parsing data [?25l
LogService.ts:62 xterm.js: parsing data [93mde[?25h
LogService.ts:62 xterm.js: parsing data [?25l[m[93m[15;11Hdef [?25h
LogService.ts:62 xterm.js: parsing data [?25l[m[93m[15;11Hdef [mf[?25h
LogService.ts:62 xterm.js: parsing data [?25l
LogService.ts:62 xterm.js: parsing data [93m[15;11Hdef [mfoo([93mbar[m):[?25h
LogService.ts:62 xterm.js: parsing data 
```

**Comment by Tyriar** [comment]
This works fine in the python.exe repl:

![image](https://user-images.githubusercontent.com/2193314/146978426-ad33001f-12e8-4321-8b80-9b1ad731429e.png)

On version:

Version: 1.64.0-insider (user setup)
Commit: e8a26d3ebf5095d4324ad4bf794787540ed3b33e
Date: 2021-12-21T05:15:30.501Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Note that the Windows version may impact this.
