### ISSUE TITLE
Inconsistent download flow between small and large file

### ISSUE THREAD

**Issue by rongxin-liu** [microsoft/vscode#137683]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247)
- OS Version: Chrome Version 96.0.4664.55 (Official Build) (x86_64), macOS Version 11.6.1

Steps to Reproduce:

1. Ctrl-click on a small file(e.g., 50kib), then select "Download..." and the file will be downloaded automatically to the "Downloads" folder on macOS.
2. Ctrl-click on a large file (e.g., 50mib) then select "Download...", a save file dialog prompted instead of downloading the file automatically (like step 1). The file can not be saved because VSCode complains "can't open this folder because it contains system files".

I was wondering why ctrl-click then choose "Download" on file with different sizes will trigger different download flows? And I'm not sure why the file with smaller size is able to download but not the larger one?

Downloading a 50kib file:
<img width="2160" alt="Screen Shot 2021-11-22 at 17 06 23" src="https://user-images.githubusercontent.com/10591665/142942198-6a731739-166b-47a5-99d8-526ae8decc2b.png">

Downloading a 50mib file:
<img width="2160" alt="Screen Shot 2021-11-22 at 17 06 37" src="https://user-images.githubusercontent.com/10591665/142942222-9d0ed50e-7d26-4ee3-83b7-85c64d277f76.png">

<img width="2160" alt="Screen Shot 2021-11-22 at 17 06 42" src="https://user-images.githubusercontent.com/10591665/142942234-d55fc076-4a43-425c-8f6d-0c1f8434a29e.png">

**Comment by rongxin-liu** [comment]
cc @dmalan

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/blob/23f8788a8b167ef8ec597967374c96bd27d456aa/src/vs/workbench/contrib/files/browser/fileImportExport.ts#L624-L625

**Comment by rongxin-liu** [comment]
Thanks for clarifying @bpasero! Just curious, could the file not just be streamed as application/octet-stream from some server process to the browser?
