### ISSUE TITLE
With `md.supportHtml = true` and VS Code Remote SSH, a PNG file in remote workspaces cannot be loaded on completion items

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#137607]
Version: 1.63.0-insider (Universal)
Commit: bedf867b5b02c1c800fbaf4d6ce09cefbafa1592
Date: 2021-11-18T05:17:00.890Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0

Related to  #136027

Setting `md.supportHtml = true` and VS Code Remote SSH, on the markdown document of a completion item, a PNG file in remote workspaces cannot be loaded.

Steps to Reproduce:

1. Open a remote workspace with VS Code Remote SSH
2. Copy a file `img.png` to the workspace.
1. Execute https://github.com/tamuratak/vscode-extension-samples/tree/supporthtml_img_remote/completions-sample 
2. Execute `Trigger Suggest`
3. None of images cannot be loaded.

Developer Tools says VS Code Insiders fails to load a file `vscode-file://vscode-app/home/ubuntu/img.png`. `ubuntu` is a username on my remote server.

![スクリーンショット 2021-11-21 20 07 45](https://user-images.githubusercontent.com/10665499/142759432-647e0f05-c920-4b9c-8bdd-0d7f8faa0100.png)

```ts
import * as vscode from 'vscode';
import * as path from 'path';

export function activate(context: vscode.ExtensionContext) {

	const provider1 = vscode.languages.registerCompletionItemProvider('plaintext', {

		provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext) {

			const activeFolder = vscode.workspace.workspaceFolders?.[0]
			if (!activeFolder) {
				return
			}
			const pngPathUri = vscode.Uri.joinPath(activeFolder.uri, 'img.png')
			const pngPath = pngPathUri.fsPath
			const pngPathUriString = pngPath.toString()

			const snippetCompletion = new vscode.CompletionItem('Good part of the day');
			snippetCompletion.insertText = new vscode.SnippetString('Good ${1|morning,afternoon,evening|}. It is ${1}, right?');
			const md = new vscode.MarkdownString(`1 <img src="${pngPathUriString}"> 2 <img src="${pngPath}"> 3 ![a](${pngPathUriString}) 4 ![a](${pngPath})`);
			md.supportHtml = true
			snippetCompletion.documentation = md

			// return all completion items as array
			return [
				snippetCompletion
			];
		}
	});
	context.subscriptions.push(provider1);
}
```

**Comment by roblourens** [comment]
I think this is https://github.com/microsoft/vscode/issues/97759, cc @mjbvz

**Comment by tamuratak** [comment]
I don't think so. Paths, on my example, are absolute, not relative.

**Comment by tamuratak** [comment]
I have found that my description of the issue is not correct. I will open a new issue.

**Comment by tamuratak** [comment]
Done #137632
