### ISSUE TITLE
Using git on terminal does not prompt for username anymore

### ISSUE THREAD

**Issue by dbtrnl** [microsoft/vscode#137648]
Does this issue occur when all extensions are disabled?: **Yes**

---

- VS Code Version: 1.62.3-1637137107
- OS Version: 5.11.0-40-generic 44~20.04.2-Ubuntu SMP

I've noticed that the login prompt when using Git does not appear anymore when using the terminal.
I always use git with Bash, and VS Code always prompted me for username and password, but since i last updated from 1.62.2-1636665017 last Friday, this doesn't happen anymore.

Steps to Reproduce:

1. Type `git fetch` (or push/pull, etc) on terminal (i'm using Bash on Ubuntu 20.04);
2. Immediately fails with "remote: HTTP Basic: Access denied / Authentication failed for '[ORIGIN-URL]'"

**Expected result**: The username/password prompt that appears on top of VS Code. When i fetch from the version control menu, this prompt appears without any problems.
Tried disabling all extensions (only have 5, and GitLens is the only one git-related) but problem persists.
Also tried the options`git.terminalAuthentication: true` `github.gitAuthentication" true` on settings.json but nothing changed as well.

**Comment by lszomoru** [comment]
We had several regression in this area. Can you please upgrade to `1.62.3`, close all windows and reconnect to WSL? Thanks!

**Comment by lszomoru** [comment]
Thanks for the update. Closing the issue for now.
