### ISSUE TITLE
python syntax highlight errors

### ISSUE THREAD

**Issue by mikisama** [microsoft/vscode#137694]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- OS Version: win10 21h2

Steps to Reproduce:
```py
# This is not an f-string, but VSCode highlights `workspaceFolder' like a variable.
a = "${workspaceFolder}"
```
```powershell
> echo 'a="${workspaceFolder}"' > 1.py
> code 1.py
```
![1](https://user-images.githubusercontent.com/41532794/142966350-3b27d10f-6730-4df1-a806-76093381b0f3.png)

**Comment by alexr00** [comment]
Moved to the repository that we get our python syntax highlighting grammar from: https://github.com/MagicStack/MagicPython/issues/245
