### ISSUE TITLE
Semicolon automatically added at the end of `one import` statement 

### ISSUE THREAD

**Issue by finscn** [microsoft/vscode#137642]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. enable 
```
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
```
3.  enable  `no Semicolon` rule in ESLint
4. save file
5.  If there is just one  import ,  vscode always add Semicolon at the end of line.
if many import,  everything will be ok.

I don't want it.

Is there some config to remove it ?

**Comment by IllusionMH** [comment]
Do you have `javascript.format.semicolons` configured to remove semicolons?

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
