### ISSUE TITLE
Anchor tag href value is not visible.

### ISSUE THREAD

**Issue by ziaontech** [Microsoft/vscode#13761]
- VSCode Version:  1.6.1
- OS Version: Ubuntu 16.04LTS

Steps to Reproduce:

1. Open any html file which have anchor tag with href attribute.
2. the value of href is always displayed as "".
![untitled](https://cloud.githubusercontent.com/assets/6224386/19390534/1afde0be-9246-11e6-9d5f-d201b0c67022.png)

**Comment by aeschli** [comment]
I fixed that the empty href looks like a link.
Is that the bug you are referring to? If not, please reopen with a html code example.
