### ISSUE TITLE
proxy exception request

### ISSUE THREAD

**Issue by taronlee** [microsoft/vscode#137699]
I can not re-open the issue, so I made new issue.
https://github.com/microsoft/vscode/issues/137404

**I was disappointed a bit about your unconsidible reply.
I said we need all lists `when download the vsix from marketplace`.**

we are done proxy execption request of all the url lists that you said.
but it doesn't work.
https://code.visualstudio.com/docs/editor/extension-marketplace#_install-an-extension

our security team said `dc.services.visualstudio.com`, `default.exp-tas.com` are still blocked.

1. what are `dc.services.visualstudio.com`, `default.exp-tas.com` for ?
we have to provide the reason when proxy execption request
2. all the lists when download from marketplace

**Comment by joaomoreno** [comment]
> I can not re-open the issue, so I made new issue.

You don't need to re-open the issue to still comment on it. Moving the discussion to the original issue.
