### ISSUE TITLE
Incorrect modifier key in placeholder text for committing straight to branch on MacOS

### ISSUE THREAD

**Issue by tyler2grass** [microsoft/vscode#137679]
When using the web editor to commit to a remote branch, the text states to use <kbd>Ctrl</kbd>+<kbd>Enter</kbd> to commit; however, on MacOS this is done by pressing  <kbd>Cmd</kbd>+<kbd>Enter</kbd>.

![image](https://user-images.githubusercontent.com/88393125/142938255-4b7d0731-4879-4084-9615-d6966675351d.png)

Version: 1.62.3
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36
Embedder: github.dev

**Comment by joyceerhl** [comment]
This message is contributed by RemoteHub, but I don't believe extensions have a way to look up the keybinding for a given command (which is what we'd need to do to correct this message from RemoteHub itself). Some ideas for resolving this:

- ask for a VS Code API to expose the keybinding for a command to extensions
- move this message into core, e.g. into the git-base extension (IIRC builtin extensions do have access to the keybindings service)
- provide a different way to nudge users towards using the simplified commit experience and drop mention of the specific keybinding from the input
- change the keybinding to not use the ctrl key
- other ideas?

**Comment by tyler2grass** [comment]
Is the full message contributed from RemoteHub, or the message without the keybinding?
Do you happen to know where the RemoteHub source is? I tried searching for it to take a look and only found an archived GitHub repo.

**Comment by joyceerhl** [comment]
We're blocked on something like https://github.com/microsoft/vscode/issues/162433 to implement this.

**Comment by lszomoru** [comment]
Closing this issue as we are currently blocked from implementing this.
