### ISSUE TITLE
error

### ISSUE THREAD

**Issue by arm32739** [microsoft/vscode#137653]
Issue Type: <b>Bug</b>

	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "syntax error, unexpected 'try' (T_TRY)",
	"startLineNumber": 19,
	"startColumn": 1,
	"endLineNumber": 19,
	"endColumn": 1.7976931348623157e+308

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.94GB (5.58GB free)|
|Process Argv|--crash-reporter-id de4d8fea-5b0c-442f-96da-4b22c87e7ae4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-color|ans|0.4.5
bracket-pair-colorizer|Coe|1.0.61
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.0.0
php-debug|fel|1.22.0
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
live-html-previewer|hdg|0.3.0
ftp-simple|hum|0.7.6
vscode-phpfmt|kok|1.0.30
auto-save|mcr|1.0.3
vsliveshare|ms-|1.0.5090
color-highlight|nau|2.5.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
highlight-matching-tag|vin|0.10.1
vscode-icons|vsc|11.7.0
JavaScriptSnippets|xab|1.8.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593:30376534
vssld246cf:30401891

```

</details>

**Comment by arm32739** [comment]
![image](https://user-images.githubusercontent.com/43534783/142882647-ca306d81-e10d-4382-a2e3-11239beaaa5d.png)

**Comment by roblourens** [comment]
Is the file correct? Please share the full text. And are you using a PHP extension or is this from the builtin PHP support?
