### ISSUE TITLE
Nested Dependent tasks are run multiple times

### ISSUE THREAD

**Issue by OldStarchy** [microsoft/vscode#137698]
I'd like to reopen this issue https://github.com/microsoft/vscode/issues/43076 as it's basically the same thing except that my task setup is slightly different.

My abridged tasks.json

```json
{
	"tasks": [
		{
			"label": "dev",
			"dependsOn": ["yarn watch", "yarn dev"],
			"isBackground": true
		},
		{
			"label": "yarn watch",
			"dependsOn": ["start container"],
			"isBackground": true
		},
		{
			"label": "yarn dev",
			"dependsOn": ["start container"],
			"isBackground": true
		},
		{
			"label": "start container",
		}
	]
}
```

Starting "dev" causes "start server" to start twice, they conflict with each other, and then both fail.

My workarounds are

1. Remove the "dependsOn" property from "yarn dev". This way I can run "dev", wait for the watch to start, then run "dev" again. No different to manually starting the server before running "dev" though.
2. Globally install "concurrently" and merge the two watch tasks into one.

I don't have a root-level package.json (or equivalent) for this project.

- VS Code Version: 1.63.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.22000

**Comment by alexr00** [comment]
Same root cause as https://github.com/microsoft/vscode/issues/118238, except this one has a work around:
```
{
	"tasks": [
		{
			"label": "_dev",
			"dependsOn": ["yarn watch", "yarn dev"],
			"isBackground": true
		},
		{
			"label": "dev",
			"dependsOn": ["start container", "_dev"],
			"dependsOrder": "sequence",
			"isBackground": true
		},
		{
			"label": "yarn watch",
			"isBackground": true
		},
		{
			"label": "yarn dev",
			"isBackground": true
		},
		{
			"label": "start container",
		}
	]
}
```
