### ISSUE TITLE
Why there is a gap in terminal? And termial also not responding properly

### ISSUE THREAD

**Issue by Suvam67** [microsoft/vscode#137621]
We have written the needed data into your clipboard because it was too large to send. Please 

- paste.[](url)
<img width="960" alt="VS Code problem" src="https://user-images.githubusercontent.com/76938694/142775755-f7f4851d-bfe6-41f4-a47b-9937029c8f48.png">

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" terminal

**Comment by CodeCrazy-ywt** [comment]
> We have written the needed data into your clipboard because it was too large to send. Please 
> 
> - paste.[](url)
> <img width="960" alt="VS Code problem" src="https://user-images.githubusercontent.com/76938694/142775755-f7f4851d-bfe6-41f4-a47b-9937029c8f48.png">
> 

Can you show the whole code?

**Comment by meganrogge** [comment]
?

**Comment by CodeCrazy-ywt** [comment]
Sorry I don't know what you mean by just a question mark.

**Comment by meganrogge** [comment]
You need to provide specifics/details about what you're expecting vs what you're seeing.

**Comment by meganrogge** [comment]
Also try in an external terminal to confirm that your expectations are appropriate
