### ISSUE TITLE
createTextEditorDecorationType rendering or line height calculation goes wrong when Windows 10 scaling is not 100%.

### ISSUE THREAD

**Issue by leodevbro** [microsoft/vscode#137609]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3 (user setup)
- OS Version: Windows 10 Pro (21H1), Build 19043.1348

Steps to Reproduce:

As you can see, <a href="https://marketplace.visualstudio.com/items?itemName=leodevbro.blockman">Blockman</a> extension renders the blocks very well when `scaling` is 100%, but when the Windows `scaling` is anything other than 100%, the horizontal 1px gaps appear somehow.

**To be more clear:** Blockman does not render one block as an entire HTML div, it renders one block line by line, which means it creates a div for each line, and these divs must be exactly the height of a line, so they will touch each other perfectly and so there will be illusion of entire block. It works fine when Windows scaling is 100%, but when it's not 100%, 1px horizontal gaps appear.

Blockman calculat**ed** line height by this instruction:
https://github.com/microsoft/vscode/issues/125341#issuecomment-854812591

Currently Blockman is just using simple CSS `height: 100%;` value to achieve line height for each line.

And it seems, achieving exact line height does not work very well when Windows scaling is other than 100%.

My monitor is classic 1920x1080, so I can keep 100% scaling, but this is a big problem for people who have 4K monitors, they need to set Windows scaling to about 150-200%.

![Untitled Project-scccc222](https://user-images.githubusercontent.com/54504880/142760748-c1f2e3d6-c732-4742-9e29-e8e528790720.gif)

**Comment by leodevbro** [comment]
@alexdima, things changed very positively. After the [version 1.66 update](https://code.visualstudio.com/updates/v1_66#_electron-17-update) (with **Electron 17**) of VS Code, this issue (strange horizontal lines) seems mostly fixed.

I tested on 3 Windows machines and 1 Mac OS machine, and the issue seems like 99.9% fixed, yeah, the 0.1% is about very rare horizontal lines, like I may see one or two lines in rare edge case scenarios of some very abnormal zooming settings.

Also, as you can see here:
https://github.com/leodevbro/vscode-blockman/issues/52
https://github.com/leodevbro/vscode-blockman/issues/75

at least 4 people confirmed that it is fixed. So far only one person reported that it is not fixed enough for his/her machine.

I'm not sure whether this issue should be closed or not. Maybe it needs some more investigation.

**Comment by alexdima** [comment]
I will close this since there's nothing more planned here from our side.
