### ISSUE TITLE
when escape sequence logging toggled on and dev tools isn't open, open dev tools

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#137629]
and the opposite (close when it gets toggled off)

**Comment by meganrogge** [comment]
layering issue. @tyriar thoughts?

**Comment by Tyriar** [comment]
@meganrogge to get around the layering problem you would need to inject the ability to open/close devtools into `ITerminalService` via `TerminalNativeContribution`, see `setNativeDelegate`.
