### ISSUE TITLE
Multiple consecutive identical dialogs

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#13768]
- VSCode Version: 1.6.1
- OS Version: macOS Sierra 10.12.1 Beta

Steps to Reproduce:

1. Open a file
2. Make some changes
3. Repeat N times `cmd+w`
4. Close the dialog
5. The same dialog will be opened N -1 more times

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time or this time if you are curious about the progress of the issue.
