### ISSUE TITLE
Can vscode do Chinese automatic association extensions?

### ISSUE THREAD

**Issue by lichangwei123** [microsoft/vscode#137603]
for example

![1637490540(1)](https://user-images.githubusercontent.com/46671582/142758322-07bff943-7705-4588-a0f9-4915d4827abc.png)
but only keywords have space symbol  

![1637490669(1)](https://user-images.githubusercontent.com/46671582/142758378-c886257b-8627-4975-afe2-0a15623631cd.png)
no space symbol  can't realize
![1637490840(1)](https://user-images.githubusercontent.com/46671582/142758442-d94f4b67-5ff6-4877-a0d6-86082d65b265.png)

**Comment by rebornix** [comment]
Currently the suggestion is based on word segmentation but Chinese word segmentation requires dictionary look up, we currently don't have support for it yet.

**Comment by lichangwei123** [comment]
> Currently the suggestion is based on word segmentation but Chinese word segmentation requires dictionary look up, we currently don't have support for it yet.

thank you
