### ISSUE TITLE
Quiet authentication requests with different scopes might not be distinct on Accounts icon

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#137601]
Consider this line:

https://github.com/microsoft/vscode/blob/ce15e23a06afd39d3a3ddc06ff1e49fa91250b40/src/vs/workbench/services/authentication/browser/authenticationService.ts#L616

Suppose an extension runs this code:
```ts
  const session1 = await vscode.authentication.getSession('myProvider', ['A', 'BC'], {createIfNone: false});
  const session2 = await vscode.authentication.getSession('myProvider', ['AB', 'C'], {createIfNone: false});
```
The Account icon badge will report only 1 login request.

A potential solution might be to change the line to be:
```ts
   const scopesList = JSON.stringify(scopes);
```

**Comment by TylerLeonhardt** [comment]
verification:

Using the code above... you should get 2 logins.

Before the fix:

![image](https://user-images.githubusercontent.com/6726799/142768231-e908431b-c06f-4264-b068-206ba8e4cd98.png)

After:

![image](https://user-images.githubusercontent.com/6726799/142768457-1f2bd4c1-0137-40cf-b66e-98e11ee86416.png)

The two quiet logins are now accessible, but the screenshot reveals another issue, which is that the menu item prompts for the two different-scopes requests are identical. I will open a separate issue for this.
