### ISSUE TITLE
Doesn't render on broken 3D chip/no graphics card.

### ISSUE THREAD

**Issue by SkybuckFlying** [microsoft/vscode#137667]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Damage 3D chip or buy broken laptop or disable graphics chip/card in windows.
2. Switch to windows classic, non-accelerated graphics mode.
3. Try and install vs code
4. Watch the black screen in action.

(Other applications do work, like firefox, opera by disabling hardware acceleration, some games don't work because of missing 3D chip/broken chip, CPU has embedded GPU that is why laptop still works and can render GDI and other things, or perhaps the 2D part of the 3D chip is still working, not exactly sure).

I will try to install an intel graphics driver, maybe that will help, cu for now ! hope it doesn't screw up what is left of this system/laptop ! =D wish me luck ! LOL.

**Comment by IllusionMH** [comment]
Have you tried to launch whit `--disable-gpu` flag?

**Comment by SkybuckFlying** [comment]
I solved problem as follows:

Disabled radeon 5000 graphics in windows.

Ran VS code in vga mode, then:

Disable GPU acceleration#

We have heard issue reports from users that seem related to how the GPU is used to render VS Code's UI. These users have a much better experience when running VS Code with the additional --disable-gpu command-line argument. Running with this argument will disable the GPU hardware acceleration and fall back to a software renderer.

To make life easier, you can add this flag as a setting so that it does not have to be passed on the command line each time.

To add this flag:

    Open the Command Palette (Ctrl+Shift+P).
    Run the Preferences: Configure Runtime Arguments command.
    This command will open a argv.json file to configure runtime arguments. You might see some default arguments there already.
    Add "disable-hardware-acceleration": true.
    Restart VS Code.

Note: Do not use this setting unless you are seeing issues!
Editor#

Also add a comma.

Then re-enabled hd 5000.

^ did not require a reboot that is cool.

All of this worked.

I did also install a intel arrandale graphics driver but it didn't seem to do much, maybe it allows this switching now to be done without a reboot at best ! ;)

Bye,
  Skybuck.
