### ISSUE TITLE
VSCode opens different file with the same name while debugging

### ISSUE THREAD

**Issue by RahulSisondia** [microsoft/vscode#137630]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2
- OS Version:  Amazon Linux 2  

**Steps to Reproduce:**

1.  Debugging the open source mysql code in Amazon linux. I set the breakpoint on the file  sql/dd/upgrade_57/table.cc and launch the mysqld to debug. 
2.  The debugger hits in the  different file with same name present at different location that is sql/table.cc . It hits the same line number though in that file. As you can see from the attache screenshots.

<img width="1393" alt="Screenshot 2021-11-22 at 7 51 09 AM" src="https://user-images.githubusercontent.com/4783163/142793347-30835139-14cd-4aff-a326-0f482983715e.png">
<img width="1386" alt="Screenshot 2021-11-22 at 7 51 25 AM" src="https://user-images.githubusercontent.com/4783163/142793364-b3d85856-a27e-44aa-bd49-b3fdbb9cee63.png">

**From the debug console logs** 
Attached the filtered logs. 
[filtered.txt](https://github.com/microsoft/vscode/files/7578024/filtered.txt)

**Comment by RahulSisondia** [comment]
Not exactly similar but a partially close match that I found https://github.com/microsoft/vscode-python/issues/4166 which is reported for python but this issue happens with cpp extension.

**Comment by roblourens** [comment]
Please file this issue on the repo for the vscode-cpptools extension:

https://github.com/microsoft/vscode-cpptools/issues

Thanks!
