### ISSUE TITLE
workbench.colorTheme restores to Default Dark+ automatically

### ISSUE THREAD

**Issue by zzz0906** [microsoft/vscode#137635]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.3 (Universal)
- OS Version: macOS Monterey 12.0.1

Steps to Reproduce:

I know there are many similar issues here. But I cannot find the same problem I have now.

for my /USR/setting.json:

> {
    "tabnine.experimentalAutoImports": false,
    "security.workspace.trust.untrustedFiles": "open",
    "workbench.preferredDarkColorTheme": "Quiet Light",
    "workbench.preferredLightColorTheme": "Quiet Light",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "window.autoDetectColorScheme": true,
    "workbench.colorTheme": "Default Dark+",
}

1.  If I delete 'workbench.colorTheme', this line will be added at the end of this file and it will be set to Default Dark+ automatically
2. If I modify it, it will be set to Default Dark+ automatically
3. If I modify it in the command control or setting interface, it will turn into another theme. If I just use the mouse to see the file, the theme won't change. **BUT if I type anything in the file, it will restore to Default Dark+ again.**

My installed theme-related extensions: C/C++ theme, Theme

Thanks for your help!

**Comment by gjsjohnmurray** [comment]
Are you using [Settings Sync](https://code.visualstudio.com/docs/editor/settings-sync)?

Did you try the `Start Extension Bisect` command to investigate whether any of your extensions are causing this?

Does it still happen if you //-comment out these other color-related settings in your setting**s**.json file?

> "workbench.preferredDarkColorTheme": "Quiet Light",
> "workbench.preferredLightColorTheme": "Quiet Light",
> "window.autoDetectColorScheme": true,

**Comment by zzz0906** [comment]
@gjsjohnmurray 
1. No, I am not. I never turn on settings sync. And Setting sync: Ignored Extensions, Ignored Settings.
2. How can I do the `Start Extension Bisect`? could you please give some tutorial to use this command?
3. Yes, it will add a new line "workbench.colorTheme": "Default Dark+" automatically.

**Comment by gjsjohnmurray** [comment]
`Start Extension Bisect` is a command you run from [Command Palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette).

There's a blog about Extension Bisect [here](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect).

**Comment by zzz0906** [comment]
@gjsjohnmurray 
oh, thanks. After disabling 46 extensions, this problem is gone!

How can I find out which extension brings this problem?

**Comment by gjsjohnmurray** [comment]
Also, are you able to use the [color theme picker](https://code.visualstudio.com/docs/getstarted/themes#_selecting-the-color-theme) to set a different theme? Does this change the setting in settings.json?

**Comment by zzz0906** [comment]
I have found the virus extension: 

`https://marketplace.visualstudio.com/items?itemName=abelcour.asp-syntax-highlight`
`Answer Set Programming syntax highlighter`

disable it and I can modify the color theme. Thanks for your help!
