### ISSUE TITLE
comment should be // inside HTML <script /> and /* */ inside HTML <style /> tags

### ISSUE THREAD

**Issue by didrip** [microsoft/vscode#137644]
When editing an HTML file with script tag and selecting one or multiple lines and hitting Ctrl + K an HTML comment (`<!-- -->`) is inserted instead of the valid comment for the type of tag the lines are in (`//` when inside `<script />` and `/* */` when inside `<style />`).

Intellisense is working inside the script tag so I guess VSCode has a way to know which language is associated with each line and could therefore input the right type of comment.

VSCode 1.54.3

**Comment by ArturoDent** [comment]
I have seen this reported (see https://stackoverflow.com/a/59131077/836330 for example) due to an extension. 

Did you try it with all extensions disabled or try the `Start Extension Bisect` to see if you get correct behaviour?

I cannot reproduce on the Insiders or Stable Build W11.

**Comment by didrip** [comment]
Wow. I did not know about Extension Bisect and it is amazing. The culprit is was Jinja extension ([wholroyd.jinja](https://github.com/wholroyd/vscode-jinja)).

Sorry I did not go through the debugging steps before opening the issue, I actually thought it was not a bug but the normal behavior because I have always seen it as far as I remember.

Thank you so much 🙏
