### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by jplatte** [microsoft/vscode#137647]
- Extension version: 0.26.0
- VSCode Version: 1.56.1
- OS: arch linux

Steps to Reproduce:

1. Install extension
2. Click sign in button
3. Click Continue on the "Authorize Visual Studio Code to access GitHub" page that opens
4. Get error message

![Screenshot_2021-05-12_200122](https://user-images.githubusercontent.com/951129/118022650-da8d7980-b35c-11eb-88ce-aa9a3dc96e6f.png)

**Comment by TylerLeonhardt** [comment]
We've done a lot of work in this space. Can you confirm if you still see this behavior?

**Comment by TylerLeonhardt** [comment]
@jplatte do you see anything here?
![image](https://user-images.githubusercontent.com/2644648/154570094-e6b34a5e-9513-4078-a1c4-7fef4f9b4b97.png)

(ignore the undefineds ... I fixed that)

**Comment by jplatte** [comment]
Trying to sign in on my other computer I'm at now, it immediately prompts me for a personal access token instead of opening the auth page. What could be the reason for that?

**Comment by TylerLeonhardt** [comment]
Not sure... how did you install it? What package are you using?

**Comment by jplatte** [comment]
Oh, seems like on this computer it's installed through OpenVSX (https://open-vsx.org/extension/GitHub/vscode-pull-request-github). Could that be problematic?

**Comment by TylerLeonhardt** [comment]
I'm suspicious that you're not actually using VS Code and are instead using Code OSS or VSCodium. We don't use OpenVSX in VS Code and install extensions from the VS Code official marketplace.

**Comment by jplatte** [comment]
Yeah, I currently use that, though I'm pretty sure I had the official build at the point of reporting the bug. Let me just install that again to check there.

**Comment by jplatte** [comment]
Works! Sorry for the unnecessary extra back-and-forth.
