### ISSUE TITLE
Cannot open any file in code insiders

### ISSUE THREAD

**Issue by rbadapanda** [microsoft/vscode#137661]
Issue Type: <b>Bug</b>

Got the update this morning. After which I am not able to open any file.

error I am getting for every file is:
```
Unable to open 'blah.md': Cannot find module 'jschardet' Require stack: - electron/js2c/renderer_init.
```

repros without any enabled extensions.

VS Code version: Code - Insiders 1.63.0-insider (4e303fcc52269ab578affa6cb1eb455eacab445f, 2021-11-22T05:26:03.776Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.156-94.273.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: myDevDesktop_AL2|
|OS|Linux x64 5.4.156-94.273.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz (16 x 3412)|
|Memory (System)|30.36GB (14.24GB free)|
|VM|0%|
</details>

**Comment by IllusionMH** [comment]
May be OS specific - can't repro on Windows (open from Explorer, drag'n'drop from Windows Explorer, context menu in Windows Explorer, CLI) for same version.

Version: 1.63.0-insider (user setup)
Commit: 4e303fcc52269ab578affa6cb1eb455eacab445f
Date: 2021-11-22T05:28:15.683Z
OS: Windows_NT x64 10.0.19041

**Comment by rbadapanda** [comment]
Reinstalled. I think it is caused by some customization I have via monkey patch.

FWIW, I don't see this corruption on code (with the same customization via monkey patch).

Please feel free to leave this ticket or close it if you want. If I get any new data points I will share.

**Comment by deepak1556** [comment]
Closing based on above comment, if the issue repros without any extension involved then we can reopen to investigate further. Thanks!
