### ISSUE TITLE
Authentication API refactoring in #135503 broke quickpick feature of `vscode.authentication.getSession()`

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#137615]
Does this issue occur when all extensions are disabled?: Yes/No - not applicable, as it is a bug in an extension API

- VS Code Version: 1.62.3
- OS Version:: Windows_NT x64 10.0.19043

Steps to Reproduce:

1.  Have an extension implementing an AuthenticationProvider and some test commands which invoke getSession() with parameters which on 1.61 would present the quickpick that the API documents.
2.  Run it on 1.62 or on current 1.63 Insiders and observe that the quickpick no longer appears.

I intend to provide a repo which demonstrates this.

/assign @TylerLeonhardt

**Comment by gjsjohnmurray** [comment]
https://github.com/gjsjohnmurray/vscode-extension-samples/tree/show-137615 is a branch in which I have added a new sample, authenticationprovider-using-scopes-sample

See its README.md for instructions.

The core-provided quickpick which displays as expected when the instructions are followed on 1.61

![image](https://user-images.githubusercontent.com/6726799/142782421-c37eada8-788a-4bed-ac5d-92ebe39f5b30.png)

The extension-provided quickinput when appears instead on 1.62 and 1.63 Insiders

![image](https://user-images.githubusercontent.com/6726799/142782480-4642a911-30b4-4f9a-868c-8130f45b0f46.png)

I think the refactoring done in #135503 caused this issue.

**Comment by TylerLeonhardt** [comment]
Nice find! I broke clearSessionPreference entirely... fixed, with a test!
