### ISSUE TITLE
can't right-click menu on windows taskbar mini window

### ISSUE THREAD

**Issue by zsedcbm** [microsoft/vscode#137688]
Because of the external monitor, sometimes the software location is too high to manually drag the window by pressing the title bar, so you need to use the right-click menu on the small taskbar window to move. I tried it locally. Windows Explorer can operate the right-click menu, but the Visual Studio Code software cannot operate the right-click menu.
![taskbar](https://user-images.githubusercontent.com/5986396/142959606-585fc239-a7c8-402f-afe3-a7017b7e93a9.gif)

**Comment by sbatten** [comment]
this is a known issue and is upstream... 

workarounds:
1. Alt+Space, M will trigger the menu you want when VS Code is focused, then move the window with the arrow keys
2. Use `window.titleBarStyle` native
