### ISSUE TITLE
Synchronizing changes... stays in a loop

### ISSUE THREAD

**Issue by G-R-A-F-F** [microsoft/vscode#137690]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.2
- OS Version: Win 10 - 20H2 - 19042.1348

Steps to Reproduce:
1. Use an ssh key with a passphrase
2. Open repo
3. make code changes and commit them
4. Run git Sync
5. It will stuck in a loop

It would be nice if VS Code would prompt for an ssh key passphrase. Otherwise, the workaround below should work.

Related issue
https://github.com/microsoft/vscode/issues/130898

# Workaroud
After troubleshooting this I realized that ssh key I am using was configured with a passphrase.
To Fix this issue: generate a new key without a passphrase and set to use it as an identity in your .ssh/config
```
Host 192.168.0.123
    HostName git_server
    User git
    port 22
    IdentityFile ~.ssh/id_git_no_pass
```

**Comment by lszomoru** [comment]
Can you please upgrade to `1.62.3` and see if that resolves the issue? Thanks!

**Comment by G-R-A-F-F** [comment]
> Can you please upgrade to `1.62.3` and see if that resolves the issue? Thanks!

Upgraded this morning to 1.62.3 That did not solve the problem. Sync continued without stopping.

**Comment by lszomoru** [comment]
Support for an SSH key with a passphrase has even added in [the September 2022 release](https://code.visualstudio.com/updates/v1_72#_add-support-for-ssh-keys-with-a-passphrase).
I will optimistically close this issue but please feel free to reopen it can se you are still seeing issues. Thanks!
