### ISSUE TITLE
string not formatting correctly in get set

### ISSUE THREAD

**Issue by andreweberle** [Microsoft/vscode#13767]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:43:46.054Z)
- OS Version: Linux x64 4.4.0-31-generic
- Extensions: gerane.Theme-FlatlandMonokai-0.0.4, gerane.Theme-Metropolis-0.0.2, ms-vscode.csharp-1.4.1

Steps to Reproduce:

1. NOT WORKING - public string Wage{
            get{
                return this.wage;
            }
            set{
                this.wage = string.Format("{0:C2}",value);
            }
        }
2. - WORKING -    public string Wage{
            get{
                return this.wage;
            }
            set{
                this.wage = value.ToString().Insert(0,"$");
            }
        }
    }
string formats dont appear to be working in OOP.

**Comment by isidorn** [comment]
This seems to be a format bug with the csharp extension - please file it here 
https://code.visualstudio.com/Docs/languages/csharp
