### ISSUE TITLE
can't seem to open multiple projects

### ISSUE THREAD

**Issue by skewballfox** [microsoft/vscode#137618]
Issue Type: <b>Bug</b>

for some reason it seems that multiple projects won't open, either through the getting started page, the recent projects under file, or the open folder menu.

It seems to allow some projects, before disabling all extensions, it allowed a python project (the other project I tried was either proto or rust) then after disabling the extensions and reloading, it allowed me to open multiple cpp projects but not python or rust.

it could be some configuration error or some sort of invalid state for those projects that were recently opened, the ones it allowed hadn't been opened in weeks at the point this bug occured.

this one error message has been spamming the console:

```
Violation] Forced reflow while executing JavaScript took 35ms
console.ts:94 

[Violation] 'setInterval' handler took 57ms
```

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.14.18-300.fc35.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700 Eight-Core Processor (16 x 1550)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 1, 1|
|Memory (System)|15.55GB (0.35GB free)|
|Process Argv|--enable-features=UseOzonePlatform --ozone-platform=wayland --crash-reporter-id 8209f1c7-78b8-4c88-bedb-a2cdc62a51d2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|sway|
|XDG_SESSION_DESKTOP|sway|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
sourcetrail|ast|0.0.2
better-toml|bun|0.3.2
yo|cam|0.9.10
path-intellisense|chr|2.4.2
gitignore|cod|0.7.0
bracket-pair-colorizer-2|Coe|0.2.1
systemd-unit-file|coo|1.0.6
doxdocgen|csc|1.3.2
vscode-markdownlint|Dav|0.45.0
algorithm-mnemonics-vscode|dav|1.0.3
vscode-eslint|dba|2.2.2
vscode-dash|dee|2.4.0
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|11.7.0
shell-format|fox|7.2.2
vscode-yarn|gam|2.0.0
graphviz-markdown-preview|gee|0.0.8
vscode-pull-request-github|Git|0.32.0
todo-tree|Gru|0.0.214
debug-visualizer|hed|2.2.4
realtime-debugging|hed|0.1.0
better-cpp-syntax|jef|1.15.10
tera|kar|0.0.9
bash-ide-vscode|mad|1.11.0
rust-analyzer|mat|0.3.821
git-graph|mhu|1.30.0
vscode-docker|ms-|1.18.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
color-highlight|nau|2.5.0
autodocstring|njp|0.5.4
material-icon-theme|PKi|4.10.0
trusty-rusty-snippets|pol|0.0.5
scheme|reb|0.0.2
java|red|1.0.0
bash-debug|rog|0.3.9
vscode-qt-for-python|sea|1.1.4
fish-vscode|sky|0.2.1
java-generate-setters-getters|soh|7.4.0
code-spell-checker|str|2.0.12
best-dark-themes-pack|the|1.0.2
html-preview-vscode|tht|0.2.5
vscode-status-bar-format-toggle|tom|3.0.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
vscode-spring-initializr|vsc|0.7.1
vscode-todo-highlight|way|1.0.5
pestfile|xor|0.2.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.13.2
vscode-proto3|zxh|0.5.5

(10 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593cf:30376535
vssld246cf:30401891
vscexrecpromptt1:30400061

```

</details>

**Comment by roblourens** [comment]
Please expand on `won't open`, what happens when you try to open them?

Any different if you start vscode with `--disable-extensions`?

**Comment by skewballfox** [comment]
won't open as in nothing happens at all, no visible change in the
application.

yesterday I had ran the with disabled extensions from the issue panel,
after being prompted because I wasn't sure if it was an extension issue or
not, though this morning it vscode refuses to launch with that option at
all, but seems to launch fine without `--disabled-extensions`.

looking though the logs (via journalctl), I'm seeing quite a few logs about
process code dumping core, both this morning and yesterday when the issue
first appeared.

I can post any system information that will help, just let me know what you
need.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by skewballfox** [comment]
trying with insiders makes seems to solve the apparent issue, I can open those projects, though I'm still getting logs that the process dumped-core. those core dumps aren't currently being saved

**Comment by skewballfox** [comment]
when trying to launch regular code I had an issue where it was using 100% of all cpus and seemed to be deadlocked (no change in cpu usage or visible application until manually killed), and it seems this was caused by ripgrep-code.
![Dominion-26-11-2021_09-14-47](https://user-images.githubusercontent.com/29311431/143603152-1b8799ec-e649-40dd-8f89-129c46fe4ff3.png)

this isn't the only issue though, in the most recent launch of `code` I'm only getting a box, and this was the case both with the `--disable-extensions` flag and without

![Dominion-26-11-2021_09-37-38](https://user-images.githubusercontent.com/29311431/143604252-5058329f-5b17-4a24-a911-9d5efa484a75.png)

is there any way to clear out application state without removing configuration files?  the fact that vscode-insiders worked, and code doesn't (with or without extensions) has me wondering if something is off with whatever it is using for persistent state across sessions

**Comment by bpasero** [comment]
Yeah you can just delete the entire `$HOME/.config/Code` folder. That will nuke settings and UI state. As for extensions, those live in `$HOME/. vscode/extensions`

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by skewballfox** [comment]
same result as before when disabling extensions: the problem persists.
whatever state is being changed or corrupted is shared by the entire
application across sessions, whether or not extensions are enabled.

I can redelete the configuration again, and try to the process that led to
this state. what tools should I use to try to monitor/collect information
on what is going on when it occurs?

**Comment by bpasero** [comment]
@skewballfox are you still seeing high CPU utilization from ripgrep?
