### ISSUE TITLE
code auto-complete not work

### ISSUE THREAD

**Issue by alvin-7** [microsoft/vscode#137640]
Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

VSCode code auto-complete it not work

Double-screen computers

use vscode while disabling all plugins, using Chrome while Vscode will not be able to code auto-complete

**Comment by IllusionMH** [comment]
/needsMoreInfo

You should provide more details about code where you try to get completions. Repo with minimal project that reproduces problem will be helpful.

> Double-screen computers

does it work with single screen?

**Comment by zhuye-7** [comment]
> /needsMoreInfo
> 
> You should provide more details about code where you try to get completions. Repo with minimal project that reproduces problem will be helpful.
> 
> > Double-screen computers
> 
> does it work with single screen?

I find it works with the project which to P4.
when the project uses git to manage, the vscode code auto-complete is not worked.
It`s not just me, my colleague showed up with the issue, and work well with p4.

**Comment by mjbvz** [comment]
We cannot investigate this issue without an example project and steps to reproduce the problem. From the sounds of this though (specifically the stuff about`P4`), this is likely caused by an extension

**Comment by alvin-7** [comment]
I find if remove node_modules directory will recover auto complete.
Below is my directory structure:
root
|
|----others...
|----project1
|--------|-----node_modules
|--------|-----others...
|----project2
|--------|-----node_modules
|--------|-----others...

Matt Bierner ***@***.***> 于2022年1月27日周四 08:36写道：

**Comment by alvin-7** [comment]
> /needsMoreInfo
> 
> You should provide more details about code where you try to get completions. Repo with minimal project that reproduces problem will be helpful.
> 
> > Double-screen computers
> 
> does it work with single screen?

Mac air m1.  Single screen is not work when has node_modules directory.

**Comment by alvin-7** [comment]
> Please provide an example project and steps to reproduce the issue using it

I find it is mongoose lib generate auto-complete not work.
If I remove mongoose lib, auto-complete will work right
This is an issue link with mongoose, it has a video to show this question.
https://github.com/microsoft/vscode/issues/134321
