### ISSUE TITLE
Smoke test driver connection sometimes cannot be established

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#137731]
This test flaked 11 times in the past month (91.4% pass rate):

![image](https://user-images.githubusercontent.com/2193314/143060531-05da2772-5050-41aa-a3f5-d2bcbe9d128d.png)

Example failing build: https://monacotools.visualstudio.com/Monaco/_build/results?buildId=143487&view=results

```
Error: connect ENOENT \\.\pipe\z4j91yglbudclif
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
```

**Comment by bpasero** [comment]
That looks to me like a broken connection to our driver that is exposed via a socket.

**Comment by joaomoreno** [comment]
Connections don't just break. `ENOENT` means the named pipe doesn't exist. So either VS Code failed to launch, or failed to reach the _socket creation point_ in the time we hoped it would.

**Comment by joaomoreno** [comment]
@bpasero I am not the owner of this smoketest.

**Comment by bpasero** [comment]
@joaomoreno easy cowboy

Another variant of this seems to be:

```
1) VSCode Smoke Tests (Electron)
       Preferences
         "before all" hook for "turns off editor line numbers and verifies the live change":
     Error: connect ENOENT /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp-45659aw4mF7EHcpih
      at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
```

From https://dev.azure.com/monacotools/Monaco/_build/results?buildId=144271&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=fff0fe4e-512d-573e-9d0b-0e9f3e677ab7&l=87

**Comment by bpasero** [comment]
Having refactored a lot of the smoke test lifecycle code, I feel that the origin of this issue could be where we try to connect to the IPC driver handle:

https://github.com/microsoft/vscode/blob/e71b28a444783d6b1cec4a6c68dc41a3a4d5d7ae/test/automation/src/electronDriver.ts#L113-L141

This code is basically attempting to connect to the starting VSCode instance for a while until eventually giving up. If the instance does not start (which can be simulated by changing the driver handle), the error is very similar:

```
1) VSCode Smoke Tests (Electron)
       Data Migration (insiders -> insiders)
         verifies opened editors are restored:
     Error: connect ENOENT /var/folders/fv/p__j7gw9097crr40g7sf2pxw0000gn/T/tmp-60384-Rw9kPPKJlgyi2
      at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
```

I have slightly increased the duration of time we allow to retry with my changes.

**Comment by bpasero** [comment]
Somehow I have not seen this issue for a long time, and I have looked at 1-2 weeks of falures.

**Comment by Tyriar** [comment]
Same, let's close this off

**Comment by Tyriar** [comment]
Just happened again https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=147380

**Comment by bpasero** [comment]
This is no longer relevant when moving to playwright.
