### ISSUE TITLE
The number of uint8arrays transmissable from webviews is limited

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#137757]
I recently hit an error in the Hex Editor. In the hex editor, edits (including find and replaces that can target thousands of substrings) are transmitted back and forth between the webview and extension host in some scenarios. There is optimizations we can do here, but one thing I ran into was larger edits not being transmitted correctly between the extension host and webview.

Edits are done on binary and are therefore transmitted as Uint8Arrays which are spread as arguments into this method:

https://github.com/microsoft/vscode/blob/eace6a0af1a94cb7896bbef6efbe3501458c4153/src/vs/workbench/api/common/extHost.protocol.ts#L794

However, when this is encoded in the protocol, the number of arguments is serialized as a uint8. This prevents all the arrays from being transmitted:

https://github.com/microsoft/vscode/blob/eace6a0af1a94cb7896bbef6efbe3501458c4153/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L646

---

There are a couple ways to fix this. The point fix would be to use a large integer or [variable length integers](https://developers.google.com/protocol-buffers/docs/encoding#varints). However ultimately this will hit the argument limit in the browser, which is 125,114 in Edge right now.

Another would be for binary serialization to be possible inside of a message arguments. This is a decent workaround and would make dealing with binary data easier, though comes with a runtime performance impact.

Another approach would be something I suggested tangentially before, which is to have protocol methods have an additional runtime presence, somewhat similar to @hediet's [typed-json-rpc](https://github.com/hediet/typed-json-rpc). For example, I might define:

```js
const extHostWebviewsShape = protocol({
  $onMessage: {
    args: [
      /* webview handle */ $.string(),
      /* json stringified message */ $.string(),
      /* serialized buffers */ $.array($.binary()),
    ],
  },
});
```

An approach like this would serialization to be 'solved' statically, which would allow cheap binary replacement and possibly more advanced serialization in the future (e.g. the size benefits of protobuf or the performance benefits of [fast-json-stringify](https://github.com/fastify/fast-json-stringify)). And more pursuant to my original desire for this, it allows de/serialization to be handled entirely within the definition of the protocol and not leaked into other logic (think of all those URI.revives which could be a `$.uri()` in the protocol)

**Comment by mjbvz** [comment]
Good find

The current implementation with the spread was a hack to work around how our old IPC handled buffers. We can avoid the spread now and instead use `SerializableObjectWithBuffers`

**Comment by mjbvz** [comment]
@connor4312 Can you please test this out and let me know if you see any problems. I quickly tested it with the md preview but didn't test it for an actual extension

**Comment by alexdima** [comment]
🚀  thank you @mjbvz
