### ISSUE TITLE
Smoke test flake: VSCode Smoke Tests (Electron) Quick Access quick access respects fuzzy matching

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#137733]
This test flaked 3 times in the past month, including yesterday:

![image](https://user-images.githubusercontent.com/2193314/143063738-b5670c82-2bed-44e7-9226-fb02f155e4dd.png)

Example failing build: https://monacotools.visualstudio.com/Monaco/_build/results?buildId=143928&view=results

```
Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.
    at poll (D:\a\1\s\test\automation\out\code.js:181:19)
    at async Code.waitForElements (D:\a\1\s\test\automation\out\code.js:261:16)
    at async QuickInput.waitForQuickInputElements (D:\a\1\s\test\automation\out\quickinput.js:25:9)
    at async Context.<anonymous> (out\areas\search\search.test.js:88:13)
```

I checked the builds and this seems to fail exclusively on windows 64+32 bit

**Comment by roblourens** [comment]
Should use the same retry from https://github.com/microsoft/vscode/commit/6f28593438fceb1da65e4b92e1cea8f84b777a07

**Comment by Tyriar** [comment]
This is still failing:

![image](https://user-images.githubusercontent.com/2193314/143911797-09801922-414e-4827-8088-33bba6cf956b.png)

https://monacotools.visualstudio.com/Monaco/_build/results?buildId=144582&view=results

**Comment by Tyriar** [comment]
nvm, devops reset the branch file, that was probably based on an old main.

**Comment by roblourens** [comment]
Or possibly #138045, the same thing failed in a different way
