### ISSUE TITLE
VScode crashing while debugging using Perl Language Server

### ISSUE THREAD

**Issue by thalia2809** [microsoft/vscode#137761]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.3 and 1.61.2
- OS Version: Windows_NT x64 and Ubuntu 20.10

Steps to Reproduce:

Hello, new here so ANY ADVISE will be MUCH APPRECIATED. 

I am using Perl Language Server to debug a long perl script. VScode will crash (no error in the log file or in the output) when the debugger hits a loop or anything "laborious". This happened on my laptop running Ubuntu so I switched to a workstation that has ~80GB of available memory. I couldn't find a way to increase the heap size of VScode but this is the only thing I can suspect for the crashes. If I run the debugger line by line I get get through the same loop fine (!) but if I hit the "Run" button it will crash.. 

Any ideas?
thank you

**Comment by weinand** [comment]
Please file issue against Perl extension
