### ISSUE TITLE
Test: Finalization of `keepScrollPosition: boolean` in quickpick API

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#137740]
Refs: #132068

- [x] anyOS @roblourens
- [x] anyOS @dbaeumer

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23137740%0A%0A&assignees=TylerLeonhardt)

---

This iteration we added a new property on the `QuickPick` object that allows you to control whether or not the scroll position (`cursorTop`) in the quickpick moves back to the top of the list.

* Create a new extension
* Get the latest vscode.d.ts: `npx vscode-dts main`
* using the `QuickPick` object you get back from the `window.createQuickPick()` API, play with the new `keepScrollPosition: boolean`

Usecases:
* Implementing a "remove this item from the list" [using the also being finalized `QuickPickItemButton`s](https://github.com/microsoft/vscode/pull/130519) (think, Ctrl/Cmd + P `x` QuickPickItemButton)
* Implementing a "toggle this item in someway" [using the also being finalized `QuickPickItemButton`s](https://github.com/microsoft/vscode/pull/130519) (think, "Insert Snippet" command)
* Asynchronously loading items in the quickpick (like `setInterval` adding an item to the list by reassigning the `.items` property... scroll shouldn't jump to the top)

### Useful stuff

* [Create an extension guide](https://code.visualstudio.com/api/get-started/your-first-extension)
* [Extensions samples repo](https://github.com/Microsoft/vscode-extension-samples)
* Add a finalized API: `npx vscode-dts main`
* Add a proposed API:
  * First add the proposed API to the `package.json` (see below)
  * Then run `npx vscode-dts dev` to get the typings
```json
	"enabledApiProposals": [
		"quickPickSeparators"
	],
```
> Note the name of the proposed API is gathered from the [file name in the vscode-dts folder](https://github.com/microsoft/vscode/tree/main/src/vscode-dts)

**Comment by dbaeumer** [comment]
Nice work! All cases worked as expected for me.

**Comment by roblourens** [comment]
I must be missing something, the most basic case isn't working for me:

```
vscode.commands.registerCommand('extension.helloWorld', async (args) => {
	const quick = vscode.window.createQuickPick();
	quick.keepScrollPosition = true;

	const items: vscode.QuickPickItem[] = [
		{ label: 'Hello', description: 'World 1' },
		{ label: 'Hello', description: 'World 2' },
		{ label: 'Hello', description: 'World 3' },
	];
	quick.items = items;
	setInterval(() => {
		items.push({ label: 'Hello: ' + Date.now() });
		quick.items = items;
	}, 1000);

	quick.show();
});
```

The scroll position is reset when the items are updated
