### ISSUE TITLE
Smoke test flake: VSCode Smoke Tests (Electron) Search replaces first search result with a replace term

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#137726]
This test consistently flakes on the main branch, it should be fixed or disabled so it stops breaking the build:

![image](https://user-images.githubusercontent.com/2193314/143056742-d564e242-ce1f-4f1e-8555-0823d4f80076.png)

**Comment by Tyriar** [comment]
Disregard if you've already disabled, hard to tell from the graph

**Comment by roblourens** [comment]
I disabled it yesterday, there's another issue for it
