### ISSUE TITLE
Split Termian Horiaontally in Panel Not in Editor.

### ISSUE THREAD

**Issue by kahsa** [microsoft/vscode#137768]
Currently, it can only be split vertically, please make it possible to split horizontally.
Strings are supposed to extend horizontally in the first place.
It is difficult to read various commands result such as `lsof`.

**Comment by Tyriar** [comment]
You can only split in one dimension currently, we may explore 2d splitting inside the panel as part of https://github.com/microsoft/vscode/issues/34442
