### ISSUE TITLE
Microsoft Edge - WebAssembly is not defined

### ISSUE THREAD

**Issue by Jimmy-Blue** [microsoft/vscode#137704]
![image](https://user-images.githubusercontent.com/60958064/142989234-cf2ec2b9-80d5-4f60-a5d5-2512507aced2.png)
On Microsoft Edge browser, anycode extension will never work, which make color scheme for the code become useless, since it won't display anything, which make it harder for me to look into the code. Please fix this, as when I use github.dev or vscode.dev on Mozilla Firefox, everything works fine.

I tried to install WebAssembly extension just in case it was my fault, but the same thing still happen. anycode won't load and make it harder for me to see and organize my code.
![image](https://user-images.githubusercontent.com/60958064/142989669-30364d15-bf4e-4d4e-958b-6e0e1485f45d.png)

Please fix this as soon as possible. Thank you.

**Comment by Jimmy-Blue** [comment]
> It looks like in your case Edge doesn't support WebAssembly. WebAssembly is a web technology that is vital for vscode.dev/gh.dev and without it multiple parts won't work, like colorization (which isn't done by anycode btw) and syntax analysis (which is done by anycode).
> 
> @Jimmy-Blue Do you run Edge in some special mode, like Private Browsing?

@jrieken I use github.dev in a normal mode. I don't use Private Browsing. I also set all values in the Settings to the default and even uninstall all extentions like AdBlock just in case they are the problem creator but even I did all of that, the WebAssembly is not defined continue to happen.

**Comment by jrieken** [comment]
What version of Edge do you use @Jimmy-Blue? This is compatibility table: https://developer.mozilla.org/en-US/docs/WebAssembly#browser_compatibility

**Comment by Jimmy-Blue** [comment]
> What version of Edge do you use @Jimmy-Blue? This is compatibility table: https://developer.mozilla.org/en-US/docs/WebAssembly#browser_compatibility

@jrieken My current Microsoft Edge version is ``Version 96.0.1054.29 (Official build) (64-bit)``, which is the latest stable build.

**Comment by jrieken** [comment]
Please select "Tools > Developer > JavaScript Console" and share the readings here

**Comment by Jimmy-Blue** [comment]
![image](https://user-images.githubusercontent.com/60958064/143014475-446ce392-daab-4d49-bdfb-01b5b35633f4.png)
@jrieken

**Comment by srberard** [comment]
I had the same issue.  It was due to me having enabled some of the browser security settings.  Check to see if you have **Enable security mitigations for a more secure browser experience** enabled in the Privacy, search, and services setting.  If so, disable it and try again.

**Comment by Jimmy-Blue** [comment]
@srberard Thank you so much. It was because of that setting. I turned it off and WebAssembly can load up perfectly fine now.

**Comment by phyllisstein** [comment]
Same deal here. You're a lifesaver.

**Comment by jasonjgardner** [comment]
Thanks @srberard! This solved the problem I was having with CodeSandbox.io

One should also consider setting up exceptions, rather than disabling enhanced security entirely. Here's the Edge settings URL: `edge://settings/privacy/secureModeExceptions`

(The list of exceptions will probably be short anyway.)

![Edge settings screenshot](https://user-images.githubusercontent.com/1903667/147695996-add1d05a-801b-4452-b2f0-b1e03d41d157.png)
