### ISSUE TITLE
Insiders not honoring auto-update settings

### ISSUE THREAD

**Issue by lollobaldo** [microsoft/vscode#137764]
Issue Type: <b>Bug</b>

As title, sometimes VSCode does not honor the disables updates.

I'm using 1.59 as a workaround #136982 , but sometimes it auto updates to 1.63.
I'm not able to reproduce this consistently, however if both settings show it shouldn't.

Am I missing something?

![image](https://user-images.githubusercontent.com/7450490/143147599-247c889f-e5f9-4cb5-aabf-8e8d76687a42.png)

VS Code version: Code - Insiders 1.63.0-insider (3bd29c1d6c6ef5b6265614def99b7257b671ae19, 2021-11-12T12:04:20.740Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (5.29GB free)|
|Process Argv|--crash-reporter-id c70b8d75-cacb-48f9-962d-e4774c4a2e10|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
haskell|has|1.7.1
language-haskell|jus|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593cf:30376535
vsc1dst:30396469
pythonvs932:30404738
vscexrecpromptt1:30397558
vscop804cf:30404767
vscop341:30404997

```

</details>

**Comment by joaomoreno** [comment]
Make sure there are no other installations of VS Code in your system, usually this happens when multiple installations are around.

**Comment by lollobaldo** [comment]
Indeed I have the stable 1.62 installed, which I regularly use and is set to auto-update. However, shouldn't settings be per-installation? I'd expect the insiders to honor its own settings?

**Comment by joaomoreno** [comment]
I mean, a second Insiders.

**Comment by lollobaldo** [comment]
Indeed I had 2 insiders.
