### ISSUE TITLE
Errors not shown inline when using keyboard only

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode#13775]
_From @atombender on October 13, 2016 5:2_

On linter/build errors, the "Problems" panel is populated, and if you mouse over the error location there's a box shown after a delay. But there's no inline error shown when you have the cursor on the line where the error occurs. Compare VSCode:

![screen shot 2016-10-13 at 01 03 09](https://cloud.githubusercontent.com/assets/50314/19337201/da5db086-90e0-11e6-97e0-dff000c2d328.png)

And Atom with the go-plus plugin:

![screen shot 2016-10-13 at 01 00 35](https://cloud.githubusercontent.com/assets/50314/19337172/85dcf7f6-90e0-11e6-9f82-159cd0b4d703.png)

For me, Atom is a lot better here. I don't want to shift my focus to the "Problems" panel every time there's an error, and using the mouse isn't how I work in an editor.

Interestingly, the "go to next marker" keyboard shortcut (F8 by default) _does_ trigger an inline error description. But only then:

![screen shot 2016-10-13 at 01 06 01](https://cloud.githubusercontent.com/assets/50314/19337256/7af130e0-90e1-11e6-8bac-3b829085e852.png)

(That particular behaviour is a bit visually unsettling as it actually _inserts_ a line in the editor, rather than showing a floating tooltip. Inserting lines immediately on error would be fine, but it removes the line when you jump to the next error. It also doesn't go away if you fix the error.)

_Copied from original issue: Microsoft/vscode-go#527_

**Comment by ramya-rao-a** [comment]
Thanks for reporting this @atombender! This is a VS Code specific issue, I can see the same while coding in typescript too. Will move this issue to the VS Code repo

**Comment by isidorn** [comment]
@ramya-rao-a please try to assign issues to owners in our repo. If you are not sure who is the owner the easiest heuristic is to look into file history for a specific file that seems related to he problem :)

**Comment by jrieken** [comment]
This is about showing the hover when navigating with keys, right @atombender?

**Comment by atombender** [comment]
@jrieken Yes.

**Comment by isidorn** [comment]
Closing as designed / will not tackle.
Our approach for errors accessibilty is via F8 / shift + F8 for the Go to Next Problem and Go to Previosu Problem.

An alternative apporach is to show hover for the location you are at. You can do that via cmd + k / cmd + i. Or F1 > show hover
