### ISSUE TITLE
Telemetry property: experiments has been trimmed to 8192, the original length is 9701

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#137703]
* open https://insiders.vscode.dev/github/microsoft/vscode
* check the dev tools console
* the trimming warning appears, likely meaning that the experiments telemetry is broken

<img width="658" alt="Screen Shot 2021-11-23 at 09 33 00" src="https://user-images.githubusercontent.com/1794099/142992126-34009f61-60f0-4895-a64e-8ff55562eda9.png">

**Comment by lramos15** [comment]
Looks like this warning comes in handy after all. We were logging an entire JSON file, switched to just logging ids.
