### ISSUE TITLE
How do you change the non-editor font

### ISSUE THREAD

**Issue by trajano** [Microsoft/vscode#13772]
- VSCode Version: 1.6.1
- OS Version: Windows

Steps to Reproduce:

1. Preference -> User Settings
2.  find "fontFamily"
3. was expecting a result that would allow me to change the fonts for the non-editor parts such as the file lists and the tab labels.

Though I would think that CSS would be better to set those up.

````
workbench editor {
   font: ...
}

workbench tab:active {
   font: ...
}
```

**Comment by bpasero** [comment]
Currently you cannot change the font of the workbench, but there are other feature requests opened that ask for it.
