### ISSUE TITLE
quickPick ranking gives priority to class name then to file

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1377]
What is the reasoning for the following ranking?
My preference would be to first get the file, though that is just my preference.
Also the second results fits the casing better.

![screen shot 2015-12-16 at 12 14 53](https://cloud.githubusercontent.com/assets/1926584/11839519/cfa974b6-a3ee-11e5-8964-70ffb99a7cc9.png)

**Comment by bpasero** [comment]
Should revisit the scoring algorithm for this case, maybe upper case bonus should not be given to beginning of word or segments.
