### ISSUE TITLE
alphabet key i not working in the editor workspace

### ISSUE THREAD

**Issue by OrignalCarl** [microsoft/vscode#137791]
Issue Type: <b>Bug</b>

All keys are working perfectly fine, but I  can't use " i " key in the editor. I thought this was a keyboard issue , but I can use i key in all other applications, even when writing this query. I tried using virtual keyboard but the problem remains.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|1.10.2
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
open-in-browser|tec|2.0.0

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30402085
vsaa593:30376534
vssld246:30401890
pythonvs932cf:30404740
vscexrecpromptt2:30404948
vscop804cf:30404767
vs360cf:30404996

```

</details>

**Comment by gjsjohnmurray** [comment]
Please run the `Open Keyboard Shortcuts (JSON)` command from Command Palette (F1) to see if you have added a custom mapping.

If none shows up in that file, run the `Start Extension Bisect` command to see if any of your extensions is causing the problem.

**Comment by OrignalCarl** [comment]
I accidently forgot to delete my custom shortcut of inserting snippits ( I + S ) and I just forgot about it. After deleting the shortcut I'm able to use the key. The editor is perfectly fine now . thanks a lot !

**Comment by gjsjohnmurray** [comment]
:+1: Please close your issue.
