### ISSUE TITLE
Lost my settings.json after VS Code update and settings sync returning 404

### ISSUE THREAD

**Issue by sebszocinski** [microsoft/vscode#137760]
Had an update to VS Code today and it reset all of my settings (corrupt installation message) and now when I try to restore using settings sync i'm getting a 404, after trying countless times i've now cleared my sync activity history and I no longer have any settings from yesterday (when it was last up to date)

Please help!

**Comment by sandy081** [comment]
I am sorry that you lost your settings. First of all wondering why & how your settings got reset. Do they got reset during what phase of update? From which version to which version are you updating? 

Regarding 404 - how are you trying to restore?
