### ISSUE TITLE
Certain Fonts Not Rendering Correctly

### ISSUE THREAD

**Issue by 4n41yz3r** [microsoft/vscode#137730]
Issue Type: <b>Bug</b>

1. Install "Source Code Pro" font on Windows 10: https://fonts.google.com/specimen/Source+Code+Pro
2. Set editor.fontFamily="Source Code Pro" in settings.
3. Open a new editor window and type "external library". Observe the result.
Expected result: The text is rendered correctly.
Actual result: The two words partially overlap.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (4.31GB free)|
|Process Argv|--crash-reporter-id faffdb8f-52ed-4caa-807d-c6edaa94ba23|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.5.0
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
vscode-npm-script|eg2|0.3.23
dotnet-test-explorer|for|0.7.7
gc-excelviewer|Gra|3.0.44
search-node-modules|jas|1.3.0
dotenv|mik|1.0.1
vscode-azureappservice|ms-|0.23.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.16
data-workspace-vscode|ms-|0.1.0
mssql|ms-|1.11.1
sql-database-projects-vscode|ms-|0.13.1
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
azure-account|ms-|0.9.11
powershell|ms-|2021.10.2
vetur|oct|0.35.0
java|red|1.0.0
vscode-xml-complete|rog|0.3.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30402085
vsaa593:30376534
vssld246cf:30401891
vscop804cf:30404767

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe a duplicate of #106583

**Comment by 4n41yz3r** [comment]
> Maybe a duplicate of #106583

Yes, that's exactly what's happening. Quite an annoying bug, but thankfully there is a workaround. Thanks for pointing me in the right direction.
