### ISSUE TITLE
Non-distraction mode 

### ISSUE THREAD

**Issue by danjoa** [Microsoft/vscode#13776]
Feature Request

Brackets had a toggle non-distraction mode / hotkey: Quickly show/hide all side and bottom panels. Not a big thing but pretty useful.

**Comment by rebornix** [comment]
This is sometimes named as Zen mode.

@isidorn while implementing feature, will we expose any API for directly show/hide sidebar/panel? Currently we only have `toggle` stuff which doesn't indicate the status of them.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12940
