### ISSUE TITLE
New version 1.62.3-1637137107_amd64.deb setup error

### ISSUE THREAD

**Issue by GabrielLins64** [microsoft/vscode#137754]
Does this issue occur when all extensions are disabled?: Yes

It is only a warn, but when i've installed the new version, got the following log:

```
:~/Downloads$ sudo dpkg -i code_1.62.3-1637137107_amd64.deb 
(Reading database ... 532321 files and directories currently installed.)
Preparing to unpack code_1.62.3-1637137107_amd64.deb ...
Unpacking code (1.62.3-1637137107) over (1.62.3-1637137107) ...
Setting up code (1.62.3-1637137107) ...
Error in file "/usr/share/applications/org.kde.kdeconnect_open.desktop": "*/*" is an invalid MIME type ("*" is an unregistered media type)
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for shared-mime-info (1.15-1) ...
```

- VS Code Version: 1.62.3
- OS Version: Ubuntu 20.04.3 LTS x86_64

Steps to Reproduce:

1. Downloaded new version .deb
2. Installed via `$ sudo dpkg -i code_1.62.3-1637137107_amd64.deb`

**Comment by Tyriar** [comment]
This is unrelated to vscode, we trigger `update-desktop-database` to update the desktop icons and there's an error in `org.kde.kdeconnect_open.desktop`
