### ISSUE TITLE
Test: Finalization of `QuickInputItem` inline actions API

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#137741]
Refs: #88716

- [x] anyOS @sbatten
- [x] anyOS @aeschli

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23137741%0A%0A&assignees=TylerLeonhardt)

---

This iteration, we introduced a new proposed quick pick API... Buttons on QuickPick Items!
![image](https://user-images.githubusercontent.com/2644648/130532299-960fdb49-a0f6-47b8-83d9-2ba5fc74e493.png)

definition:
```ts
        // extends what is in vscode.d.ts
	export interface QuickPickItem {
		buttons?: QuickInputButton[];
	}
        // extends what is in vscode.d.ts
	export interface QuickPick<T extends QuickPickItem> extends QuickInput {
		readonly onDidTriggerItemButton: Event<QuickPickItemButtonEvent<T>>;
	}
	export interface QuickPickItemButtonEvent<T extends QuickPickItem> {
		button: QuickInputButton;
		item: T;
	}
```

Please play around with this API addition and let me know what you think. Keep in mind, you may see this issue: https://github.com/microsoft/vscode/issues/109969
Use `keepScrollPosition` property on the QuickPick to help with this.

Full steps if you need them:
* create an extension https://code.visualstudio.com/api/get-started/your-first-extension
* then run `npx vscode-dts main` in the root of the extension repo to get the latest vscode.d.ts API typings
* look at quick pick examples here: https://github.com/microsoft/vscode-extension-samples/blob/main/quickinput-sample/src/quickOpen.ts#L53

these buttons are only supported on the `window.createQuickPick` object and not on the simpler `showQuickPick`

### Useful stuff

* [Create an extension guide](https://code.visualstudio.com/api/get-started/your-first-extension)
* [Extensions samples repo](https://github.com/Microsoft/vscode-extension-samples)
* Add a finalized API: `npx vscode-dts main`
* Add a proposed API:
  * First add the proposed API to the `package.json` (see below)
  * Then run `npx vscode-dts dev` to get the typings
```json
	"enabledApiProposals": [
		"quickPickSeparators"
	],
```
> Note the name of the proposed API is gathered from the [file name in the vscode-dts folder](https://github.com/microsoft/vscode/tree/main/src/vscode-dts)

**Comment by aeschli** [comment]
All works nicely! Looks like this is now already in vscode.d.ts, so I guess  "enabledApiProposals": [: [ "quickPickSeparators" ] ` is not necessary.
