### ISSUE TITLE
Unicode messes up syntax hilighting

### ISSUE THREAD

**Issue by p-i-** [microsoft/vscode#137786]
Issue Type: <b>Bug</b>

Finally figured this out after months.

If I have 𐌎 in my .py file, sometimes the syntax hilighting messes up.

Guessing it's something about unicode characters comprising > 2 bytes.

Check the screenshot.

Note: introducing the character doesn't immediately cause the error. But after a few minutes working on the file, I get the random character hilighting.

And I wasn't getting this with files that don't involve fancy unicode characters.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id 208511c2-dba0-4576-b4d0-606dd0e49428|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
rtf|ale|2.4.0
bracket-pair-colorizer-2|Coe|0.2.1
dart-code|Dar|3.28.0
flutter|Dar|3.28.0
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.7.0
php-debug|fel|1.22.0
go|gol|0.29.0
lldb-vscode|lan|0.2.3
vscode-docker|ms-|1.18.0
vscode-kubernetes-tools|ms-|1.3.4
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
terraform-advanced-syntax-highlighting|pjm|1.4.0
java|red|1.0.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.1
LiveServer|rit|5.6.1
cmake|twx|0.0.17
vscode-lldb|vad|1.6.10
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.33.0
debug|web|0.25.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30402085
vsaa593:30376534
vssld246:30401890
vscop804:30404766

```

</details>

**Comment by p-i-** [comment]
![Screenshot 2021-11-24 at 16 49 57](https://user-images.githubusercontent.com/693495/143215523-9ed41629-07c3-42d3-be70-b15869b36329.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with `bracket-pair-colorizer-2` extension disabled and without enabling built-in one (`"editor.bracketPairColorization.enabled": false`)?
