### ISSUE TITLE
Need a shortcut for toggle the docstring when the mouse is inside the function call brackets

### ISSUE THREAD

**Issue by Raibows** [microsoft/vscode#137793]
Hi:
I use vscode with python official extension. When you call a function call, that will be a docstring toggled above, which helps you type the following params. But there doesn't exist a shortcut for **manually toggle the docstring again when the cursor(mouse) inside the function call brackets()**.  The shortcut for "show Hover" only works **when you move your mouse to the function name**, that's very inconvenient.
You are typing your params and you want to toggle or hide the docstring mannually but not moving your mouse to the function name then show up it. 
![image](https://user-images.githubusercontent.com/37944786/143245687-371083f1-c0d1-4146-8eb5-2a248b792d02.png)

Any help would be much appreciated! Thank you!

**Comment by yotam180** [comment]
It's <kbd>Ctrl</kbd> + <kbd>K</kbd> <kbd>Ctrl</kbd> + <kbd>I</kbd>

**Comment by Raibows** [comment]
> 

Hi! Thanks for your comment. The``ctrl+k plus ctrl+I`` is a default key binding for "show hover" and as I mentioned it will not work when your mouse is inside a function call brackets.

**Comment by jrieken** [comment]
The command is called `editor.action.triggerParameterHints` and its default keybinding is `shift+cmd+space`
