### ISSUE TITLE
Provide a restart workbench command

### ISSUE THREAD

**Issue by trajano** [Microsoft/vscode#13770]
- VSCode Version: 1.6.1
- OS Version: Windows 10

Steps to Reproduce:
1. Ctrl-Shift-P
2. Type in "Restart"

Was expecting something that looked like "Restart workbench"

**Comment by isidorn** [comment]
We call it 'reload window'
Assigning to @bpasero to consider adding one more command which maps to the same thing 'restart window'

**Comment by trajano** [comment]
Thanks, just wondering was there a way of adding new menu items (I was thinking of adding it to the File menu)

**Comment by bpasero** [comment]
Well one could argue that restart should do a full restart so the command could be different in the end.

Today you cannot change any menu items in the top level menu.

**Comment by trajano** [comment]
So is "Reload Window" right now is basically what gets called when we do an update of plugin or VSCode?

**Comment by isidorn** [comment]
@trajano yes

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
