### ISSUE TITLE
Select the just renamed file for edition

### ISSUE THREAD

**Issue by tipy01** [microsoft/vscode#137715]
Hi,

I often copy/paste **2** files as starting point for new code module.

Then I rename **1** file.

Then I start editing the renamed file.

Then I realize that I am editing one of the copied file instead of the renamed one, which is not good, finally I have to swap files content before going on. 

So it should be better if the just renamed file is the one ready to be edited.

**Comment by JacksonKearl** [comment]
\gifPlease

**Comment by tipy01** [comment]
Hello,
I made a gif, I hope this will help you to understand.
![recording](https://user-images.githubusercontent.com/71043641/144429407-40efc18d-0b4e-400a-a9f3-38eb34a2b6f2.gif)

**Comment by tipy01** [comment]
An other gif, this time with renaming:
![recording(1)](https://user-images.githubusercontent.com/71043641/144431257-9ac8b0e7-3fc8-436d-9082-44344975f4a3.gif)

**Comment by JacksonKearl** [comment]
Ah, I see. It is intentional that editing the name of a file does not open it. Opening a file can be a heavy weight operation (think massive model files on a network drive), so it's desirable to be able to edit them without needing to load them.
