### ISSUE TITLE
Dirty editors and Unsaved editors error.

### ISSUE THREAD

**Issue by MasterKavi-24** [microsoft/vscode#137720]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

![VSCodeIssue](https://user-images.githubusercontent.com/68172796/143052216-e737f2c6-b9cc-44c6-882d-4beee3e68ea4.png)

Hi Team VSCode,

   Thanks for VSCode, first of all, for such a nice editor. Now, the issue is when I create a new file, a small box named Untitled-1 comes up (that's OK). I have Auto-Save option on. But after I save the file, I still see in the Open Editors section that my current (auto-saved) file is still mentioned as Unsaved. You can see that near my file name, there is no circle (circle meaning that the file isn't saved yet) only a 'x' mark (x meaning the file is saved). Hope the attached picture gives the required info. Feel free to contact.

Thanking you,

Yours sincerely,
#VSCodeLover

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by MasterKavi-24** [comment]
Thanks for your response but this doesn't occur often, just like once in 10
times. So, IDK if that same error will pop up again or not, but your reply
means a lot to me.

Thanking you,

Yours sincerely,
#VSCodeLover

**Comment by bpasero** [comment]
OK

**Comment by MasterKavi-24** [comment]
[image: image.png]
Hi, Mr. Benjamin. Why do I get this type of error ?

**Comment by bpasero** [comment]
I cannot tell yet.

**Comment by MasterKavi-24** [comment]
Hi, Mr. Benjamin. There is this issue (maybe related to this) wherein if I
edit a new file without saving and close the editor, the window closes
without prompting anything like "Do You Want To Save ?" or something like
that.
1) Is this some kind of bug or is it not meant to pop up the save message ?
2) The next time I open the window, the old file + another new (empty) file
pops up. What causes this ?

**Comment by MasterKavi-24** [comment]
[image: image.png]Pic related to the previous error message.
