### ISSUE TITLE
Wrong Chinese translation

### ISSUE THREAD

**Issue by wll8** [microsoft/vscode#137776]
Issue Type: <b>Bug</b>
The sentences about recovery time obviously do not have the correct word order.

It's almost hard to understand.

![image](https://user-images.githubusercontent.com/28223260/143181477-0271c849-ab5b-4137-a343-5f4cfa1065cb.png)

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.86GB free)|
|Process Argv|--crash-reporter-id 050ffd85-02ce-440b-bbd9-b5f5a434d8b3|
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
All-Autocomplete|Ati|0.0.23
githistory|don|0.6.19
gitlens|eam|11.7.0
prettier-vscode|esb|9.0.0
leek-fund|gis|2.0.1
markdown-image|han|1.1.14
rest-client|hum|0.24.5
dupchecker|jia|0.1.7
git-tree-compare|let|1.13.2
vscode-language-pack-zh-hans|MS-|1.62.4
remote-wsl|ms-|0.58.5
live-server|ms-|0.2.9
vetur|oct|0.35.0
change-case|wma|1.0.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593cf:30376535
vssld246:30401890
vscop804cf:30404767
vs360cf:30404996

```

</details>

**Comment by danyeh** [comment]
Translation changed to '在 {1} 时从 {0} 还原的会话内容'. will reflect in next version.

**Comment by aeschli** [comment]
Veified in 版本: 1.63.0-insider (user setup)
提交: 68a1e2f872f8869b004eec284917782474730e0b
日期: 2021-12-02T05:15:40.605Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

![image](https://user-images.githubusercontent.com/6461412/144461946-c8aa4680-4823-485a-9122-30bd24d03e15.png)
