### ISSUE TITLE
Compact Line Numbers: Combine breakpoints with linenumbers

### ISSUE THREAD

**Issue by nathanKramer** [microsoft/vscode#137769]
# Compact Line Numbers

Combine the breakpoint column and linenumber column in a tasteful way, leave the code folding column as a natural space between the line numbers and the code.

## Context

Currently there is three columns on the left handside of a code pane.

![image](https://user-images.githubusercontent.com/4732403/143154147-fd5bb4cb-1ad9-4985-9eb7-c02b2de0ac08.png)

These columns show three pieces of information:

1. Breakpoints (maybe more?)
2. Line numbers
3. Code folding

Splitting these into 3 columns makes sense as a default,
but it uses a lot of screen real-estate, especially when using split panes.

### Relevant Existing Settings / Workarounds

These allow for more compact line numbers and are useful to know about,
however they require the compromise of removing information.

```
"editor.lineNumbers": "on", // or "off"
"editor.lineDecorationsWidth": 0, // undocumented. 0 is too small, but just to show what is possible.
"editor.glyphMargin": false,
"editor.folding": false,
```

## Best Hope

To be able to see breakpoints, linenumbers, and code-folding indicators,
but in a compact way that is economical with screen real-estate

## Idea for implementation

It might be possible to combine the three columns into a single "compact line numbers" column.

Breakpoints and code-folding are less constant, and I think they could be expressed by variations of the line number cell.

Examples of what I mean:

- A breakpoint could be a red line number. OR
- A breakpoint could have a red circle behind the line number.
- Code folding could be done underneath the line number (imagine the linenumber cell becomes a vertical stack with the line number and then the code fold, either sharing space equally, or with some tasteful difference in size)
- Only combine the breakpoint and line numbers, and leave the code folding as a separate column (as it works quite nicely as a natural space between the code and the line numbers, which is probably desirable.)

**Comment by misolori** [comment]
@isidorn do we already have an issue for this? I can't seem to find it

**Comment by weinand** [comment]
I'm not aware of an existing issue and we have no intention or cycles to change this.
