### ISSUE TITLE
node module fails to load in remote connection in the ms-vscode.js-debug extension

### ISSUE THREAD

**Issue by mikkelhegn** [microsoft/vscode#137794]
Issue Type: <b>Bug</b>

Running 'npm' in a dev.container, fails with the following command:

$ npm
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/home/node/.vscode-server/data/User/workspaceStorage/7bdf84952a5fcab126d4d451217c0221/ms-vscode.js-debug/bootloader.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1276:12)
    at loadPreloadModules (node:internal/bootstrap/pre_execution:484:5)
    at prepareMainThreadExecution (node:internal/bootstrap/pre_execution:78:3)
    at node:internal/main/run_main_module:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
} 

Running 'npm' on my host, does not render the same issue.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:14:33.711Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No
Remote OS version: Linux arm64 5.10.47-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 10, 8|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|. --crash-reporter-id 0689de63-b69a-48fb-86ff-684b5b8dd22d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js|
|OS|Linux arm64 5.10.47-linuxkit|
|CPUs|unknown (2 x 0)|
|Memory (System)|3.83GB (0.18GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
bracket-pair-colorizer|Coe|1.0.61
codespaces|Git|1.4.1
vue|jcb|0.1.5
vscode-azurevirtualmachines|ms-|0.4.1
vscode-dapr|ms-|0.5.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.205.2
material-icon-theme|PKi|4.10.0
vscode-icons|vsc|11.7.0
JavaScriptSnippets|xab|1.8.0
vscode-eslint|dba|2.2.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593cf:30376535
vssld246:30401890
vscexrecpromptc:30404946
vscop804:30404766
vs360cf:30404996

```

</details>

**Comment by connor4312** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/5516

You can "Toggle Auto Attach" to disabled and then back to enabled/smart to fix this
