### ISSUE TITLE
Error log content not useful / extension update download

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/vscode#137782]
Issue Type: <b>Bug</b>

At times, extension (update) download fails, and it fails with an error message which lacks any clarity _why_ it fails:

```
[2021-11-24 09:56:28.792] [renderer2] [error] XHR failed: Error: XHR failed
    at XMLHttpRequest.b.onerror (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:24141)
[2021-11-24 09:56:48.436] [renderer2] [error] XHR failed: Error: XHR failed
    at XMLHttpRequest.b.onerror (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:24141)
[2021-11-24 09:56:50.258] [renderer2] [error] ["Error: XHR failed","    at XMLHttpRequest.b.onerror (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:24141)"]
[2021-11-24 09:56:50.323] [renderer2] [error] XHR failed: Error: XHR failed
    at XMLHttpRequest.b.onerror (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:24141)
```

Right now, I am sitting in a very peculiar networking environment where Visual Studio Code emits the above error, and I'd like to discover what _exactly_ failed.

I'd then (probably) be enabled to get that peculiar networking environment fixed.

Alas, the above error log content is not suitable for diagnostics; there is no specific data, no pointing to additional log files, nothing. It just says "network no good" (sort of), which can be anything.

FWIW, I do know that this is a network environment problem, because this is Visual Studio Code running inside a virtual machine; when the VM host is connected to different network environments, all is good. Personally, I suspect some kind of DNS or IPv6 configuration problem on the network environment, but with Visual Studio Code not telling me what it is doing...

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.14.18-200.fc34.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|31.31GB (26.38GB free)|
|Process Argv|--unity-launch --crash-reporter-id 80e0ae97-0bc4-4a76-8337-f435f2ec1554|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|/usr/share/xsessions/plasmax11|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.5.0
xml|Dot|2.5.1
gitlens|eam|11.7.0
rest-client|hum|0.24.5
Ionide-fsharp|Ion|5.10.1
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.16
vscode-dotnet-pack|ms-|1.0.4
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
vscode-xml|red|0.18.1
vscode-yaml|red|1.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30402085
vsaa593:30376534
vssld246:30401890
vscexrecpromptt1:30404947
vscop804cf:30404767
vs360:30404995

```

</details>

**Comment by sandy081** [comment]
Logs are showing whatever network stack (request) is providing. @deepak1556 is it possible to get more information?

@shoffmeister You can also diagnose network requests as follows:

- Open Shared process using the command from command pallette `Developer: Toggle Shared Process`
- Go to network/console tab and see the failing requests

**Comment by deepak1556** [comment]
@shoffmeister if you can launch with `--log-net-log=<path>/netlog.json` where `<path>` some absolute path on your system. Once the network issue happens, you can quit the application and view the log file from the above path under https://netlog-viewer.appspot.com/#import for additional information on what failed in the network stack.
