### ISSUE TITLE
Syntax highlight of Ruby is broken on percent notations

### ISSUE THREAD

**Issue by takaram** [microsoft/vscode#137713]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3, 1.63.0-insider
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create .rb file
2. Input code like below
```rb
puts %(() parentheses)
puts %<{} braces>
puts %Q{[] brackets}
puts %r[[^a-z]]
puts %(
  def foo()
    puts 123
  rescue
    nil
  end
)
puts %x(echo '() parentheses')
```

Expected:
The literal is recognized as strings (or regexp) until the closing bracket.
Specification of Ruby percent notations: http://www.chrisrolle.com/en/blog/ruby-percentage-notations

Actual:
![image](https://user-images.githubusercontent.com/18339861/143017064-81773f53-2e74-4a69-af96-99dff642bed6.png)

**Comment by alexr00** [comment]
Moved to the repository that we get our ruby syntax highlighting grammar from: https://github.com/textmate/ruby.tmbundle/issues/140
