### ISSUE TITLE
Built-in TS/JS features extension crashes

### ISSUE THREAD

**Issue by tomasjiricek** [microsoft/vscode#137787]
Issue Type: <b>Bug</b>

Can't share steps to reproduce as I haven't found any pattern in reproducing the issue. "TypeScript and JavaScript Language Features" extension is often crashing and I get a pop-up to report it. Message is: "The TypeScript language service died unexpectedly 5 times in the last 5 minutes".
See the screenshot:
![image](https://user-images.githubusercontent.com/8479520/143224241-3258f150-28b7-4ba6-98aa-2df55f7fdc90.png)

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.72GB (22.16GB free)|
|Process Argv|--crash-reporter-id 5c9ae5a7-aa5e-4e7e-93c8-25e79140c6d7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.13.0
turbo-console-log|Cha|2.1.7
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.5.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
gitlens|eam|11.7.0
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
restore-terminals|Eth|1.1.6
graphql-for-vscode|kum|1.15.3
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
debugger-for-chrome|msj|4.13.0
markdown-preview-enhanced|shd|0.6.1
teams-dyson|tea|0.0.2021042802
alphabetical-sorter|ue|2.0.1

</details>

**Comment by mjbvz** [comment]
We need steps to reproduce or a crash log to investigate 

First, does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
