### ISSUE TITLE
Colors in Go broken when multi dimensional arrays are declared

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#13777]
_From @sdwarwick on October 14, 2016 14:40_

var e [][]*aType       // ( bug in vscode highligher?)

The double slash and everything after should be highlighted in green (comment), but is showing as white, but is working code.

_Copied from original issue: Microsoft/vscode-go#531_

**Comment by ramya-rao-a** [comment]
Thanks for reporting this @sdwarwick! 
This is a bug. 
Single dimensional array declarations are fine as long as the array size is not defined. 

![image](https://cloud.githubusercontent.com/assets/16890566/19396740/60d058ee-91f9-11e6-9067-ba5e28371eb2.png)


Since the colorization for `.go` files is defined in VS Code itself at https://github.com/Microsoft/vscode/tree/master/extensions/go, will move this to VS Code repo

**Comment by aeschli** [comment]
This issue was moved to atom/language-go#98
