### ISSUE TITLE
Integrated terminal does not appear to access the updated path environmental variable?

### ISSUE THREAD

**Issue by sciguyryan** [microsoft/vscode#137736]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- OS Version: Windows 10, 64-bit.

Steps to Reproduce:

1. Modify the path environmental variable.
2. Execute $Env:Path inside VS Code (closing and reloading it does not change this).
3. Load a PowerShell console window, execute the same command.
4. The two will produce different results, specifically the one in VS Code will not reflect any changes made to the path variable.

Here, for example, is the output within VSCode:

C:\Program Files\Microsoft\jdk-17.0.1.12-hotspot\bin;C:\Program Files\Python310\Scripts\;C:\Program Files\Python310\;C:\Program Files\ImageMagick-7.1.0-Q16-HDRI;C:\Program Files\Python\Python39\Scripts\;C:\Program Files\Python\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Users\Ryan\.cargo\bin;C:\Users\Ryan\AppData\Local\Microsoft\WindowsApps;C:\Users\Ryan\AppData\Local\GitHubDesktop\bin;C:\Users\Ryan\AppData\Local\Programs\MiKTeX\miktex\bin\x64\

While here is the correct output from a PowerShell console:

C:\Program Files\Microsoft\jdk-17.0.1.12-hotspot\bin;C:\Program Files\Python310\Scripts\;C:\Program Files\Python310\;C:\Program Files\ImageMagick-7.1.0-Q16-HDRI;C:\Program Files\Python\Python39\Scripts\;C:\Program Files\Python\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\dotnet\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\pkg-config-lite-0.28-1\bin;C:\gnome\bin;C:\gnome\lib\pkgconfig;C:\Users\Ryan\.cargo\bin;C:\Users\Ryan\AppData\Local\Microsoft\WindowsApps;C:\Users\Ryan\AppData\Local\GitHubDesktop\bin;C:\Users\Ryan\AppData\Local\Programs\MiKTeX\miktex\bin\x64\;C:\Users\Ryan\.dotnet\tools;C:\Users\Ryan\AppData\Roaming\Python\Python310\Scripts;C:\pkg-config-lite-0.28-1\bin;C:\gnome\bin;C:\gnome\lib\pkgconfig;

There should be no reason why these two would be different, and this issue is preventing me building with GTK from within VS Code on Windows.

I would like to know how this can be fixed, or how I can work around it until such time that it has been fixed.

Thanks.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by sciguyryan** [comment]
> I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

I have just checked the insider build and it does appear to be fixed. I was actually able to build the Rust project, which was not possible in the release build.

I also checked to confirm that the arguments are correctly displayed (just to be through), and everything appears to be fine.

**Comment by tonyqus** [comment]
@sciguyryan  I fixed the same issue by deleting the Powershell terminal after restarting the VSCode. Looks if the original Powershell terminal is open after VSCode restart, it's referencing the same instance of the last Powershell. 

I'm using VSCode 1.62.3 on Windows 10
