### ISSUE TITLE
Test: Finalized `silent` property on `getSession`

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#137743]
Refs: https://github.com/microsoft/vscode/issues/136300

- [ ] anyOS @IanMatthewHuff
- [x] anyOS @hediet

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23137743%0A%0A&assignees=TylerLeonhardt)

---

We added another property to the options in `vscode.authentication.getSession` it allows you to get a session if one is available for your extension without showing any prompt to the user. This is great for situations when you want to see if a user is logged in, but don't want to annoy the user with any prompt at all.

To test this, make a new extension and play with the API here:
https://github.com/microsoft/vscode/blob/1b40be33779bec0c3d64e14ab98902a04dfd9252/src/vscode-dts/vscode.d.ts#L13932-L13942

### Things to verify:
* When you are not logged in, `getSession` returns `undefined` and no visual indication is shown to the user that the extension was checking auth
* When you _are_ logged in to this particular extension,`getSession` returns the session and no visual indication is shown to the user that the extension was checking auth
* Error handling with all of the other properties on getSession

> NOTE: I've had to call this out a few times... so I'll do so here as well... `getSession` will _only_ return a session if an extension has been explicitly granted permission to do so. This API _does not_ enable an extension to get a session without the user agreeing.

### Some examples
```ts
const thisIsUndefined = await vscode.authentication.getSession('github', ['repo'], { silent: true });
// This shouldn't show anything to the user. No badge. No modal
```

```ts
// This SHOULD show a modal
const originalSession = await vscode.authentication.getSession('github', ['repo'], { createIfNone: true });
// This SHOULD NOT show anything. No badge. No modal
const sameAsOriginalSession = await vscode.authentication.getSession('github', ['repo'], { silent: true });
```
### Useful stuff

* [Create an extension guide](https://code.visualstudio.com/api/get-started/your-first-extension)
* [Extensions samples repo](https://github.com/Microsoft/vscode-extension-samples)
* Add a finalized API: `npx vscode-dts main`
* Add a proposed API:
  * First add the proposed API to the `package.json` (see below)
  * Then run `npx vscode-dts dev` to get the typings
```json
	"enabledApiProposals": [
		"quickPickSeparators"
	],
```
> Note the name of the proposed API is gathered from the [file name in the vscode-dts folder](https://github.com/microsoft/vscode/tree/main/src/vscode-dts)

**Comment by IanMatthewHuff** [comment]
Apologies, was out of the office Monday / Tuesday. Will hit this today.

**Comment by IanMatthewHuff** [comment]
Looks great to me. Also checked the error for specifying silent + createIfNone and it had a reasonable and clear error for that scenario.
