### ISSUE TITLE
Menus Are Unclosable

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#137789]
It is really difficult to close any context menu. I cannot click on anything else to close it and escape also does not do anything.

This happens for the context menu and the quick fix menu.

![recording](https://user-images.githubusercontent.com/2931520/143229486-7024cc4f-b77b-4086-952a-9a45bee7ca38.gif)

**Comment by jrieken** [comment]
This must have regressed with our change here https://github.com/microsoft/vscode/commit/9bd899fabad214ad2385cc2a252a5deb581049e3

I can reproduce with the following steps

* microsoft/vscode in env with custom menus, like web bits or windows
* open src/vs/base/common/arrays.ts
* right-click the arrays.ts in the explorer, select "Select for Compare"
* right-click into the editor
* click into the editor area
* 🐛 the editor context menu stays, the explorer gained focus

I don't know what's going on but I cannot reproduce when I revert the changes to the focus tracker

**Comment by prryplatypus** [comment]
This was reported in #137785. There's a workaround there too.
