### ISSUE TITLE
Improvement suggestions on the behavior of auto closing issues of github-actions

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [microsoft/vscode#137701]
If an issue whose content is "We have written the needed data into your clipboard. Please paste." is commented by the author, github-actions should NOT close this issue, because the comment may contain the needed data(even if the comment is not in the expected template, it may at least have the possibility to be solved), otherwise this issue will NEVER be solved.

**Comment by JacksonKearl** [comment]
This was discussed elsewhere but I don't have a link at the moment. Anyways, the current behavior is as-designed, the bot's comment contains clear steps for how to proceed, if the user ignores those steps that's out of our control.
