### ISSUE TITLE
fold  

### ISSUE THREAD

**Issue by wangweiguo520** [microsoft/vscode#137718]
Issue Type: <b>Feature Request</b>

<view>.....</view>  fold  == yes
<view>.....     fold  == yes

<view>.....      fold  ==no  
</view>

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

**Comment by wangweiguo520** [comment]
fold

**Comment by CodeCrazy-ywt** [comment]
> Issue Type: <b>Feature Request</b>
> 
> <view>.....</view>  fold  == yes
> <view>.....     fold  == yes
> 
> <view>.....      fold  ==no  
> </view>
> 
> 
> VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
> OS version: Windows_NT x64 10.0.17763
> Restricted Mode: No
> 
> 
> 

What do you mean?
