### ISSUE TITLE
Ctrl+Shift+E no longer toggles explorer

### ISSUE THREAD

**Issue by andyboyne** [microsoft/vscode#137781]
Issue Type: <b>Bug</b>

Press ctrl+shift+e

Expectation: Explorer panel is toggled
Actual: Nothing happens.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
AFAIK Ctrl+Shift+E has never **toggled** Explorer view, in the sense of pressing the keycombo once to show it and a second time to hide it. Rather, Ctrl+Shift+E should **show** Explorer view if a different view is currently shown, or if the Sidebar is hidden.

If that isn't happening for you, please opne the Keyboard Shortcuts editor and search for 'ctrl shift e' to see if there are any nonstandard bindings (look for 'Source' column containing something other than 'Default').

The Windows keycombo to **toggle** the Sidebar (regardless of which view it is showing) is Ctrl+B

**Comment by andyboyne** [comment]
It toggles focus which is very important. See the "official" keyboard shortcuts here: https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

The shortcut is showing as registered in settings but does not work.

**Comment by gjsjohnmurray** [comment]
Focus toggling works for me:
```
Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

Did you try the Extension Bisect?

**Comment by andyboyne** [comment]
This is great, Extension Bisect did indeed identify the issue so many thanks for pointing that out 🙇 . Turns out extension jshinonome.vscode-q was causing the issue.
