### ISSUE TITLE
Updated HTML coloring has issue with separator comments

### ISSUE THREAD

**Issue by FremyCompany** [Microsoft/vscode#13778]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14942
- Extensions: 

Steps to Reproduce:

1. Create an html document with the following content:
```html
<!-------------------------------------------->
<h2>I am not a comment</h2>
    <p>Me neither
    <!-------------------------------------------->
    <h3>Me neither
    <p>Me neither
<!-------------------------------------------->
<h2>I am not a comment</h2>
    <p>Me neither
    <!-------------------------------------------->
    <h3>Me neither
    <p>Me neither
```
2. See that the coloring is wrong in this case

**Comment by aeschli** [comment]
If I understand https://www.w3.org/TR/html5/syntax.html#comments correctly, your comment is invalid. <text must not ... contain two consecutive U+002D HYPHEN-MINUS characters (--), nor end with a U+002D HYPHEN-MINUS character (-) >
That's why the comment content is rendered red ('invalid')
