### ISSUE TITLE
java encoding euc-kr

### ISSUE THREAD

**Issue by masque79** [microsoft/vscode#137708]
![java encodig](https://user-images.githubusercontent.com/12206943/143002958-75e6bb84-34c5-4be9-a283-845adcbf5806.png)

Issue Type: <b>Feature Request</b>

I'd like to change "DefaultCharset" to "euc-kr".

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by CodeCrazy-ywt** [comment]
Wasn't this user clear enough? This user wants to change `Charset.defaultCharset()` to `euc-kr`.

**Comment by bpasero** [comment]
How about asking over at https://stackoverflow.com/questions/tagged/java
