### ISSUE TITLE
Clearer distinction between remote hosts/os

### ISSUE THREAD

**Issue by kfsone** [microsoft/vscode#137751]
Mechanisms for distinguishing remote windows:

You're working on the same code base across Win/Wsl/Lin/Mac so you have 2-4 windows open at any moment with ... the same code. If you jump the right hoops, you can tell from path names whether it's win vs wsl/lin/mac, but not much more.

Being able to specify some display properties per remote OS would be really helpful,
Being able to specify host-specific properties,

At the very least, having the remote host display in more pronounced fashion

I realize that the host name is displayed in a couple of places, but the screen is a busy place and neither of those are places that are intuitive to look at based on standard VScode usage.

Consider:

![image](https://user-images.githubusercontent.com/323009/143102114-8506adb5-2b6a-4029-973d-fc0e0ba0f8c3.png)
vs
![image](https://user-images.githubusercontent.com/323009/143102185-56a1b845-b3ce-448b-80e6-d0f25d2adb4e.png)

(yes, the machine is called 'mac' but it's running windows, and no, it actually wasn't just someone being difficult)

**Comment by egamma** [comment]
You can try the [peacock extension](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) it enables to color different remotes differently.

**Comment by misolori** [comment]
In addition to the peacock extension, you can use the remote machine settings as a place to better differentiate them from other windows:

![CleanShot 2021-12-06 at 14 08 47@2x](https://user-images.githubusercontent.com/35271042/144930676-aa24caa9-ea84-4194-a9d1-2d73e4172132.png)

and do something like:

```json
    "window.title": "🍊 ${activeEditorShort}${separator}${rootName}",
    "workbench.colorCustomizations": {
        "titleBar.activeBackground": "#ff88002d"
    }
```
And as you do this for your different hosts, you'll be able to see the difference:

<img width="1090" alt="CleanShot 2021-12-06 at 14 13 06@2x" src="https://user-images.githubusercontent.com/35271042/144931192-b28666d2-9e2b-40a1-a9cc-6b5e7b551aed.png">

You can do this either by the hosts or per repo (if they are on the same machine). Hope that helps!
