### ISSUE TITLE
VSCode terminal execute alt+forward delete doesnt work

### ISSUE THREAD

**Issue by jkryanchou** [microsoft/vscode#137783]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.2
- OS Version:macOS 12.0.1 (21A559) Monterery

Steps to Reproduce:

1. I switch to the terminal and try to delete word forward as before by typing `fn + alt + delete`. while it output `[3;3~` symbol:
   
    ![image](https://user-images.githubusercontent.com/1206342/143209639-14b09db1-9138-4424-8e43-d8c30f9f3322.png)

**Comment by jkryanchou** [comment]
Hi @meganrogge Have you met the issue？

**Comment by jkryanchou** [comment]
@meganrogge Have you confirmed this issue?

**Comment by jkryanchou** [comment]
@meganrogge No one to reply to this issue?

**Comment by jkryanchou** [comment]
@meganrogge `alt + delete` in terminal window by fish shell

**Comment by meganrogge** [comment]
works for me. I recommend running the keyboard shortcuts troubleshooting to see what might be causing this

 ![recording (11)](https://user-images.githubusercontent.com/29464607/146049736-3b838802-41db-4885-8c90-f1f57ba3e348.gif)

**Comment by jkryanchou** [comment]
@meganrogge Thanks. I got it. It's my mistake. I have forgot the keyboard settings has been set.
