### ISSUE TITLE
Task status restarts when another task status changes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#137723]
In the below gif I have a watch task (tsc) which is changing a bunch of files over a period of time, for every file changed the webpack task starts and finishes almost immediately.

![recording (2)](https://user-images.githubusercontent.com/2193314/143055735-74160f43-6ce0-4ec4-b490-156038147633.gif)

We should look into not re-rendering the status icon if it hasn't changed

**Comment by meganrogge** [comment]
IMO, this is by design - I use the status indicators to tell me if my changes are being evaluated
