### ISSUE TITLE
Inline Completion Provider Sample Needs Update

### ISSUE THREAD

**Issue by GusSand** [microsoft/vscode#137888]
/cc @hediet ⬆️

_Originally posted by @jrieken in https://github.com/microsoft/vscode/issues/131165#issuecomment-978939021_

There's a bunch of things that seem to need to change in the samples that reference the new API:
- Documentation
- package.json - how to modify it to add the proposed API
- post install script - needs to be updated to download the correct file. 

thanks!

**Comment by hediet** [comment]
*From @CodeCasterNL:*
documentation like [Inline Completions Sample](https://github.com/microsoft/vscode-extension-samples/tree/main/inline-completions) still links to the old file locations (https://github.com/microsoft/vscode/commit/a4d426a1c2ece4222f1343459d31fe948098b2f6).

**Comment by CodeCasterNL** [comment]
Perhaps a relevant search: https://github.com/search?q=org%3Amicrosoft+vscode.d.ts&type=code

**Comment by Anishashaik** [comment]
Hi
