### ISSUE TITLE
Notebooks: breakpoints unexpectedly moved when splitting cells

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode#137833]
Version: 1.63.0-insider (user setup)
Commit: ed3018f4310e906daa0a9119d997e75b8a38b879
Date: 2021-11-23T05:33:39.595Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

1. open an ipynb file
2. set a breakpoint in the middle of a notebooks cell, e.g.
![image](https://user-images.githubusercontent.com/26419852/143326357-c55602e7-7632-4797-8f8a-5cc82eb1f9b2.png)

3. move cursor to a different location in the cell (e.g. line 3 in this example) and split cell from there.

Expected:
The breakpoint remains in the same location

Actual:
The breakpoint was moved to a different line (should have stayed on line 6 in the second cell but it's on line 4 in the first cell)
![image](https://user-images.githubusercontent.com/26419852/143326414-b7707d02-d617-4d11-8cde-ef826166a160.png)

After an undo, the breakpoint moved to line 16, which again isn't its original location
![image](https://user-images.githubusercontent.com/26419852/143326462-0113fb90-2142-42f9-824c-8a521ba2e908.png)

**Comment by DonJayamanne** [comment]
Given that no one else has reported this issue and we've had debugging and this issue open for over 3 years now, I'm closing this as not planned.
