### ISSUE TITLE
Can't Copy from Cell Output (Still)

### ISSUE THREAD

**Issue by AaronBeaudoin** [microsoft/vscode#137816]
I couldn't reopen microsoft/vscode-jupyter#7575, and the last comment said that if the issue still occurs to reopen it. So here's a new issue.

The problem is the same. When I select text in the **output** of a cell and `Command+C`, my clipboard gets the text content of the _cell itself_, not the output of the cell.

If I follow [this](https://github.com/microsoft/vscode-jupyter/issues/7575#issuecomment-922279393) "solution", which is to click the "Terminal" pane to move the cursor there, then copy from the cell output, my clipboard is correctly set to what I selected in the output of the cell.

## Environment data

-   VS Code version: 1.62.3
-   Jupyter Extension version: 2021.10.1101450599
-   Python Extension version: 2021.11.1422169775
-   OS and version: macOS 12.0.1
-   Python version: 3.9.0 64-bit
-   Type of virtual environment used: None
-   Jupyter server running: Remote

## Expected behaviour

I hit `Command+C` and the text I've selected in the output of the cell is copied to my clipboard.

## Actual behaviour

I hit `Command+C` and the text content of the cell itself is copied to my clipboard.

## Steps to reproduce:

1. Open a notebook.
2. Create and run a cell.
3. Try copying the output and pasting it somewhere.

**Comment by rebornix** [comment]
@AaronBeaudoin can you please run "Toggle Notebook Clipboard Troubleshooting" from Command Palette, reproduce the bug and then share the log with us?
