### ISSUE TITLE
Current Working Directory in "terminal.integrated.Cwd" Win 11 Ubunutu 20.04 WSL does not work

### ISSUE THREAD

**Issue by Dawoodshah100** [microsoft/vscode#137844]
I have been trying to set "terminal.integrated.Cwd" to all possible paths, in WSL (Ubuntu 20.04) in Win 11 however none works and the current shell directory in vs code is always as "/mnt/c/Users/My User Name/AppData/Local/Programs/Microsoft VS Code"

These all were set to "terminal.integrated.Cwd" but didn't work.
${cwd}
${cwdFolder}:
${workspaceFolder}:
${local}:

Please guid as how to start vs code (in WSL) terminal in current folder in which it is opened

**Comment by meganrogge** [comment]
this might help you
https://stackoverflow.com/questions/52397075/setting-wsl-to-cwd-in-vscode-terminal
