### ISSUE TITLE
Editor: Linked Editing Error

### ISSUE THREAD

**Issue by NazmusSayad** [microsoft/vscode#137837]
![image](https://user-images.githubusercontent.com/87106526/143329348-5be48054-d01d-47d9-8664-cd02ae6570ee.png)
# Editor LInk editing not working when multiple items are selected and working with multiple items.

**Comment by egamma** [comment]
/needsMoreInfo please describe the behaviour your are expecting in detail and then describe what is the behaviour that you would have expected.

**Comment by NazmusSayad** [comment]
When I am working with HTML.
And I want to change more than one tag at a time. I use multi-cursor mode, and i change the tag. Then the closing tags aren't renamed.
As there are 2 h1 tags, and I want to change them to h3. I select two h1 starting to tag, and I type h3, then just the two starting tags are changed, the closing tags aren't changed.

**Comment by egamma** [comment]
Thanks for the additional information, but please be more specific. I suggest to use the format:

1. do x
2. do y
3. expect z

We do not want to speculate when we reproduce the issue.
