### ISSUE TITLE
Chinese characters are not correctly encoded while debugging Python in VS Code

### ISSUE THREAD

**Issue by shixuexeon** [Microsoft/vscode#13789]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: donjayamanne.python-0.4.2, dvdbrink.vscode-sql-connect-0.2.1

Steps to Reproduce:
代码为：
print('我的代码')
输出显示为：
�ҵĴ���

**Comment by rebornix** [comment]
Steps to Reproduce:

The code is  `print('我的代码')`
The out put is `�ҵĴ���`

@shixuexeon , can you try to run this piece of code in your terminal and provide the output?

**Comment by DonJayamanne** [comment]
Closed, moved to https://github.com/DonJayamanne/pythonVSCode/issues/431
