### ISSUE TITLE
ja: Translation suggestions

### ISSUE THREAD

**Issue by takayo2020** [microsoft/vscode#137829]
"'ファイル コピー' 参加者を実行しています..." -> "ファイルをコピーしています..."
"'ファイルの作成' の参加者を実行しています..." -> "ファイルを作成しています..."
ファイルの削除' の参加者を実行しています..." -> "ファイルを削除しています..."
"'ファイル名の変更' の参加者を実行しています..." -> "ファイル名を変更しています..."
https://github.com/microsoft/vscode-loc/blob/aba1483c988f8c59237b7f49caa682dfab05a8f7/i18n/vscode-language-pack-ja/translations/main.i18n.json#L2409-L2413

**Comment by TylerLeonhardt** [comment]
@jrieken - the ask is to simplify the English in 
https://github.com/microsoft/vscode/blob/19dca64e3882a0a6db43580750bd76bcf7c45324/src/vs/workbench/api/browser/mainThreadFileSystemEventService.ts#L180-L187

so that translations are also simpler.

**Comment by jrieken** [comment]
What's the suggestion? How should it be simplified?

**Comment by cristianosuzuki77** [comment]
See the feedback for the first case above mentioned by @takayo2020


IE, instead of "Running 'File Create' participants...", simply have "Creating files".
Same rationale for the other strings.

**Comment by jrieken** [comment]
> instead of "Running 'File Create' participants...", simply have "Creating files"

But this notification isn't shown because files are created etc but because extensions do extra _before_ a file is created. You would usually not see this notification, only when having certain extensions installed
