### ISSUE TITLE
Add "open containing folder" in the context menu for files shown in the Source Control panel

### ISSUE THREAD

**Issue by scaomath** [microsoft/vscode#137828]
## Current behavior
Suppose we want to go to Finder/Nautilus to locate a changed file, currently the workflow goes like `Right click the file->Reveal in Sidebar->Open containing folder`.

## Proposed feature
Since "open containing folder" is already in the context menu in the file browser, why not just add it to the source control as well.

**Comment by scaomath** [comment]
@lszomoru I doubt this feature request will get 20 upvotes in a 60 days span... 😂 can I submit a PR?

**Comment by lszomoru** [comment]
@scaomath, sure.

**Comment by lszomoru** [comment]
No need to close the issue. Submit a PR and link it to the issue. Thanks!
