### ISSUE TITLE
Generic LSP client

### ISSUE THREAD

**Issue by ruilvo** [microsoft/vscode#137885]
While VSCode has amazing LSP features, it lacks an important (in my opinion) basic functionality: 

### A bundled generic LSP. 

_But why?_

Well, in VSCode, LSP clients are typically provided by the respective extensions. The [official clangd extension](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd) is an example of this. 

However, it sometimes happens that testing new LSPs, or using LSPs without any extension support is desired. Examples of this can be the [cmake-language-server](https://github.com/regen100/cmake-language-server) or the upcoming [QML language server](https://bugreports.qt.io/browse/QTBUG-68406).

This makes adding/using these new engines to/on VSCode "boilerplaty" and I dare even say out of reach for the user that wants to test something and doesn't know TS/JS.

_But what about the extension market?_

A small [GLSPC extension](https://marketplace.visualstudio.com/items?itemName=torokati44.glspc) was previously developed. It has apparently since been abandoned. I've forked it myself to try and fix some things for my own testing, and even tried to PR the changed upstream, which have since been ignored.  

_Is there precedent for such functionality?_ 

In the [cmake-language-server](https://github.com/regen100/cmake-language-server) page, we found a chapter about [using said extension with generic client providers](https://github.com/regen100/cmake-language-server#tested-clients). 

So I'd like to argue this is something that should be provided. A generic client. In my vision, per-language settings already built in into vscode could be used to configure it. Basically point to the server address, and maybe a JSON with the client settings?

If MS doesn't want to pick up on this, I invite the community to do so!

**Comment by dbaeumer** [comment]
As you pointed out this is a perfect extension opportunity. IMO we should not add such support out of the box to VS Code. I am happy to assist with such a extension but I don't have the bandwidth right now to develop one.
