### ISSUE TITLE
Source Control activity hinders Bleutooth audio 

### ISSUE THREAD

**Issue by MarcelHeek** [microsoft/vscode#137869]
Issue Type: <b>Bug</b>

Whenever I am working in VSCode and there is activity regarding the source control the bluetooth audio connection is malfunctioning or faltering. This is also happening when in meeting in MS Teams. This is very annoying as you sometimes cannot make up a full sentence the other meetingmember is saying. 

It appears to be that all of the sudden VSCode is exclusively claiming CPU priority to do its source control tasks. My system is beefy enough to handle all the task and processes running, but whenever VSCode source control triggers it affects audio/bluetooth.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.22504
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2286M  CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (7.49GB free)|
|Process Argv|--crash-reporter-id d9de75d6-89e7-4d50-a08c-488fc8b5921d|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
azps-tools|azp|0.1.0
azurepolicyextension|Azu|0.2.2
file-templates|brp|1.2.0
bracket-pair-colorizer-2|Coe|0.2.1
vscode-svgviewer|css|2.0.0
gitlens|eam|11.7.0
copilot|Git|1.7.3952
remotehub|Git|0.18.0
vscode-pull-request-github|Git|0.32.0
gc-excelviewer|Gra|3.0.44
todo-tree|Gru|0.0.214
sentinel|has|0.0.3
terraform|has|2.16.0
regexp-preview|Lou|0.1.5
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
vscode-docker|ms-|1.18.0
vscode-dotnet-runtime|ms-|1.5.0
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.11
powershell|ms-|2021.10.2
azurerm-vscode-tools|msa|0.15.5
printcode|nob|3.0.0
indent-rainbow|ode|8.2.2
pdf|tom|1.1.0
vscode-icons|vsc|11.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593cf:30376535
vssld246:30401890
vscop804:30404766

```

</details>

**Comment by MarcelHeek** [comment]
On top of that intellisense in VSCode is slow. Typing is very laggy, mouse movements are laggy. All when the source control activity is happening and the small progress bar is the source control pane is moving from left to right.

**Comment by lszomoru** [comment]
Thanks for the report @MarcelHeek. 
Just to get a sense, how many repositories do you have open in VS Code?
Also what version of "Git for Windows" are you using? Have you updated recently?

**Comment by MarcelHeek** [comment]
Hi, thanks for reaching out.

Only one repository is opened in VSCode.
Git version  : git version 2.32.0.windows.2

So not updated recently, will do so to check the effect.

Met vriendelijke groet,

Marcel Heek | Automation / Cloud Specialist
+31 65022 5038 | ***@***.***

[VolkerWessels Infra ICT]<https://www.vwinfraict.nl/>
[website]<https://www.vwinfraict.nl/>
[Linkedin]<https://nl.linkedin.com/company/volkerwesselsinfraict>
[line]<https://www.facebook.com/VolkerWesselsInfraICT/>

VolkerWessels Infra ICT
Lange Dreef 7, 4131 NJ Vianen
KvK 61503258

[VolkerWessels Infra ICT]<https://www.volkerwessels.nl/>

**Comment by MarcelHeek** [comment]
Better to reply via web instead of via email as it is messy in the issue thread......

Ok, after updating to the latest Git version (git version 2.34.1.windows.1) VSCode is still laggy/slow as soon as I add something to code source control is triggered and makes it unpleasant to work with.

**Comment by lszomoru** [comment]
Thanks for updating the Git version. Are you able to reproduce the same behaviour with all the extensions disabled? Thanks!

**Comment by MarcelHeek** [comment]
No, if I start code with --disable-extension the IDE is not lagging anymore. Although good to know that it is extension related btw. 
Before you ask. I have no idea what the latest extension was I installed and/or if the issues started after installing a new extension or update of an existing extension.

**Comment by lszomoru** [comment]
Great! You can use [the extension bisect tool](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) that is included in VS Code to track down the culprit extension. Let me know how it goes.

**Comment by MarcelHeek** [comment]
I will close the issue as (in the end) it appeared to be an issue on my system. After updating to the latest Windows 11 insider preview it appears to be gone for no apparent obvious reason.
