### ISSUE TITLE
Fine in Selected is issue in this version  

### ISSUE THREAD

**Issue by absolinsoft** [microsoft/vscode#137848]
Issue Type: <b>Bug</b>

In this Update When We press the  ( Ctrl + F ) Find in selected  is automatically turning on

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.47GB free)|
|Process Argv|--folder-uri file:///d%3A/Aditya/Projects/Wheelsmart/Wheelsmart-Server --crash-reporter-id 1e3e0200-722f-4ed2-b5af-4cf5395593a5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.1
ccs-flutter-color|cir|1.0.1
dart-code|Dar|3.28.0
flutter|Dar|3.28.0
gitlens|eam|11.7.0
copilot|Git|1.7.3952
git-graph|mhu|1.30.0
vscode-docker|ms-|1.18.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
errorlens|use|3.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593:30376534
vssld246:30401890
vscexrecpromptc:30404946
vscop804cf:30404767
vscop341:30404997

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Have you changed setting `editor.find.autoFindInSelection`?
