### ISSUE TITLE
Sometimes RegEx search only works in currently opened files

### ISSUE THREAD

**Issue by 4310V343k** [microsoft/vscode#137899]
Issue Type: <b>Bug</b>

I have a GIF that showcases the problem:
https://i.imgur.com/S716KNp.gif

[Repository](https://github.com/Terrania/Baystation12/tree/ef02820a21cdd098cd0ba7e7cdc7440638d7bfe3) from the GIF
RegEx i used: `(\(|\s)(splittext)([^\S\n]*)\(`

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (18.26GB free)|
|Process Argv|--crash-reporter-id 977e55b8-89e5-4642-b0b4-ffe243493d75|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-zipfs|arc|2.3.0
procfile|ben|1.1.7
npm-intellisense|chr|1.4.0
gitignore|cod|0.7.0
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.2.2
vscode-deno|den|3.9.2
gitlens|eam|11.7.0
prettier-vscode|esb|9.0.0
code-runner|for|0.11.6
kotlin|fwc|0.2.23
byond-dm-language-support|gba|1.0.1
vscode-pull-request-github|Git|0.32.0
discord-vscode|icr|5.7.0
vsc-python-indent|Kev|1.14.2
languague-renpy|Luq|2.0.4
Kotlin|mat|1.7.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.18.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
powershell-preview|ms-|2021.11.1
vscode-typescript-tslint-plugin|ms-|1.3.3
sqltools|mtx|0.23.0
sqltools-driver-mysql|mtx|0.2.0
gradle-language|nac|0.2.3
material-icon-theme|PKi|4.10.0
heroku-command|pko|0.0.8
dm-langclient|pla|0.2.1
typescript-hero|rbb|3.0.0
LiveServer|rit|5.6.1
sharecode|Rol|0.4.1
kotlin-on-vscode|set|0.0.1
markdown-preview-enhanced|shd|0.6.1
vscode-spotify|shy|3.2.1
byond|ss1|1.1.0
auto-comment-blocks|sty|1.1.1
errorlens|use|3.4.1
vscodeintellicode|Vis|1.2.14
vscode-gradle|vsc|3.8.4
vscode-icons|vsc|11.7.0
gistfs|vsl|0.3.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30402085
vsaa593:30376534
vssld246:30401890
vscexrecpromptt2:30404948
vscop804:30404766
vscop341:30404997

```

</details>

**Comment by 4310V343k** [comment]
Update: if you remove the `\n` part of the regex, it works normally and as expected

Because of that more simpler regex (`splittext[^\S\n]*`) also fails, while `splittext[^\S]*` works fine

**Comment by thebinarysearchtree** [comment]
Your regular expression is wrong. That ```^``` also applies to ```\n```.
