### ISSUE TITLE
Using `silent` property on `getSession` for provider that supports multiple accounts could be more silent

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#137819]
Testing #137743

I am using an AuthenticationProvider that gets registered with `{ "supportsMultipleAccounts": true }`

1. Call vscode.authentication.getSession(providerId, ["A"], { createIfNone: true }) User gets asked to permit the calling extension to use the authprovider. If they consent,  provider's createSession is called and does its interaction with the user 👍 
2. Call again, this time with scopes=["B"]. Same happens 👍 
3. Now call with scopes=["A"] and { silent: true }. The provider's getSessions correctly returns only one scope-matching session. But this session is not returned silently to the caller, because their most recent session (aka sessionPreference) was for a different scope, so didn't appear in the getSessions response. The silent getSession returns undefined. :-1:

By contrast, if this third call had been for scopes=["B"] the session previously returned in step 2 (after user interaction) would be silently returned.

I think that step 3 should instead silently return the single scope-matched session (which was only created after user interaction in step 1).

Before step 3, the Accounts icon correctly shows two entries for the two logins. So it feels unexpected that the user gets re-prompted for approval when the calling extension asks for the not-most-recent session.

/assign @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
@gjsjohnmurray I feel as is `silent` & `"default" (aka silent & createIfNone false)` should return the same way. In other words, go through these exact steps but this time without the `{ silent: true }` in the 3rd step. Instead just use the default behavior.

Currently, this will prompt you and return undefined in the same manor that you've pointed out... I wonder if instead, you should get a session back in the default case as well.

**Comment by TylerLeonhardt** [comment]
There are also 2 routes to take with respect to multi-account Auth Providers:
* return undefined if there are 2 or more sessions that meet the requirements
* return a random one if there are 2 or more sessions that meet the requirements

**Comment by rchiodo** [comment]
/verified

Silent call returned the first session
