### ISSUE TITLE
Remote: Allow to open the file (e.g. `*.xlsx`) in the server with the local application (e.g. Excel)

### ISSUE THREAD

**Issue by IsaraAomi** [microsoft/vscode#137878]
- The environment:
  - I use Windows 10 in my local PC.
  - I develop softwares in the linux server (Ubuntu-18.04) with Remote-SSH extension.
  - Sometimes, I want to open `*.xlsx` files.

- In this case, I want to open the `*.xlsx` files with local application (Excel) by mouse clicks only.
- I think we can do this if VSCode call external editors or tools.

Thank you.

**Comment by bpasero** [comment]
I don't understand. You want to open a remote file in excel locally?

**Comment by IsaraAomi** [comment]
Thank you for your comment.

> You want to open a remote file in excel locally?

- Yes.
- Now we are thinking of a situation where a `*.xlsx` file is on a remote server and we are connecting to the remote server with Remote-SSH in VSCode.
- Then, you will see the `*.xlsx` file on the VSCode's explorer. 
- Normally this is a binary file, so we cannot view it as is in VSCode. 
- In such a case, for example, I want to right-click on the `*.xlsx` file and open it in the local Excel application from the menu.
  - To generalize, is it possible to use VSCode to open a specific file in a remote location with a local application? This is what I mean.
