### ISSUE TITLE
Duplicate selected text or area

### ISSUE THREAD

**Issue by miladghiravani** [Microsoft/vscode#13780]
- VSCode Version: 1.6.1
- OS Version: Windows 8.1 Enterprise 64-bit

Steps to Reproduce:
Hi,
This feature is best to speed up programming. (Please see below gif)
![milad](https://cloud.githubusercontent.com/assets/5067331/19399412/40a69d3e-925e-11e6-81be-4971a2f78d75.gif)

in vs code we can only duplicate lines by `Shift` + `Alt` + `Arrow up Or down`. But on this feature you can duplicate all things (selected characters, text , lines and ...)

**What's benefits?**
1. Do not use clipboard and you can save other things on clipboard and duplicate selected text or area.
2. Speed up programming.
3. Many developers previously worked with `notepad++` and now use `VS Code`. This feature is on `notepad++` and good to add this on vs code.

**Comment by miladghiravani** [comment]
@isidorn Please see this. Thank you

**Comment by mjbvz** [comment]
Closing as extension candidate. Please checkout these extensions already in the marketplace: https://marketplace.visualstudio.com/search?term=duplicate&target=VSCode&category=All%20categories&sortBy=Relevance
