### ISSUE TITLE
Every time you open vscode is a new interface

### ISSUE THREAD

**Issue by LLLLEN** [microsoft/vscode#137871]
Issue Type: <b>Bug</b>

I have been using vscode for a long time, but there has been no problem before. Suddenly tonight, vscode took up the entire computer screen, and then I closed vscode directly, but when I reopened vscode, I found that I was before The workspace file is gone, and then I will import the file again. When I open vscode again later, vscode still does not have my previous workspace file, and I have to import the file again. I need to re-import the file every time, but I don’t need this before. It will save my last time. The file on exit.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (3.49GB free)|
|Process Argv|--crash-reporter-id d2c43468-fb4d-422a-b3d1-fd5bc18f59c5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.1
phpserver|bra|3.0.2
php-debug|fel|1.22.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
code-runner|for|0.11.6
fortran|Gim|0.2.0
path-autocomplete|ion|1.17.1
language-julia|jul|1.5.6
vscode-language-pack-zh-hans|MS-|1.62.4
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
material-theme|zhu|3.13.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593:30376534
vssld246cf:30401891
pythonvs932:30404739
vscop804:30404766
vscop940:30404999

```

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com).

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
