### ISSUE TITLE
change occurrences is not working properly

### ISSUE THREAD

**Issue by joecheriross** [microsoft/vscode#137859]
Issue Type: <b>Bug</b>

when I do change occurrences (renaming variable), the occurrences are not getting changed properly. It is adding random characters and deleting unwanted characters surrounding the variable occurrences.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.31.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 3aff0e29-a6ae-4827-89dd-19bad08b9f51 --crash-reporter-id 3aff0e29-a6ae-4827-89dd-19bad08b9f51|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: jross-ld2.linkedin.biz|
|OS|Linux x64 3.10.0-1160.31.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz (8 x 2095)|
|Memory (System)|31.26GB (5.83GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
pdl-schema-vscode|mic|0.0.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
scala|sca|0.5.5
vscode-icons|vsc|11.7.0
vscode-todo-highlight|way|1.0.5
cornflakes-linter|kev|0.5.1
java|red|1.0.0
scala|sca|0.5.5
metals|sca|1.10.15
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.33.0
vscode-maven|vsc|0.34.1

</details>

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command to see if any of your extensions are causing this.

**Comment by joecheriross** [comment]
Yes, even with Bisect on, I am getting this issue
Here, I am trying to change the occurrences of hrsCountMap --> hoursCountMap
[image: image.png]

This is happening when I do that

[image: image.png]

**Comment by jrieken** [comment]
@joecheriross How about adding some information that allows us to reproduce this. Write step by step what you are doing, what you are seeing and what you are expecting. Also, add the language for which this happens, extensions you are using, and the code sample

**Comment by gjsjohnmurray** [comment]
@joecheriross also please note that images in email responses to GH issues don't get through. Instead, go to the issue in your browser (kink at the foot of the notification email) and follow the instruction at the foot of the comment box. 🔽
