### ISSUE TITLE
`onPtyHostResponsive` fired too often 

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#137893]
* run `resources/server/bin-dev/server.sh`
* open in your favorite browser
* add a breakpoint at https://github.com/microsoft/vscode/blob/7b3474abff37d9ebbe11e48ed8aa38bd077bdf2e/src/vs/workbench/contrib/terminal/browser/remoteTerminalBackend.ts#L146
* notice how the breakpoint is hit every few seconds
* this ends up transmitting data from the server to the client

**Comment by Tyriar** [comment]
A heartbeat fires every 5 seconds so we can detect when the pty host becomes unresponsive:

https://github.com/microsoft/vscode/blob/fba2cda1fa71bfee723cfc8876609a15be48e65c/src/vs/platform/terminal/node/heartbeatService.ts#L17-L19

Open to ideas on how to improve this but it's working as designed right now.

**Comment by alexdima** [comment]
Idea:
- determine if the pty host is responsive or not on the server process
- only communicate the status of the pty host from the server to the connected renderers when the responsiveness of the pty host changes.

**Comment by Tyriar** [comment]
That should work, we only care about the event when it's going from unresponsive->responsive anyway.
