### ISSUE TITLE
Support to hide the editor title bar 

### ISSUE THREAD

**Issue by NazmusSayad** [microsoft/vscode#137891]
When 
"workbench.editor.showTabs": false
then please add a feature 
![image](https://user-images.githubusercontent.com/87106526/143479394-574f5fff-b5d3-4b98-b3ba-192f84e92b11.png)
to remove this tab bar please.

**Comment by egamma** [comment]
/needsMoreInfo it is not clear from the screenshot what you want to have removed

The feature behaves as expected.

showTabs: true
![image](https://user-images.githubusercontent.com/172399/143547527-291b2b24-fc69-4ba6-a7b0-5eea376d2389.png)

showTabs: false
![image](https://user-images.githubusercontent.com/172399/143547592-edd994e0-efff-43aa-89b7-4686529e0b76.png)

**Comment by NazmusSayad** [comment]
![image](https://user-images.githubusercontent.com/87106526/143578682-caf9cb77-c1d7-4731-8e90-915abee098e2.png)
Remove the area when, showTabs: false
