### ISSUE TITLE
Debug View BooleanRegex is incorrect

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode#137818]
https://github.com/microsoft/vscode/blob/57ca9b99d5b6a59f2d2e0f082ae186559f45f1d8/src/vs/workbench/contrib/debug/browser/baseDebugView.ts#L25

This should be `/^(true|false)$/i` if the intent is to match explicitly on "true" and "false". 

The existing regex will match on items with extra content before false.
![image](https://user-images.githubusercontent.com/15258962/143304206-de971315-bf4a-4d8c-860a-1361d9644cd5.png)
![image](https://user-images.githubusercontent.com/15258962/143306463-094ff0c4-a8ab-459f-b530-bf04563e555f.png)

**Comment by weinand** [comment]
@JustinGrote thanks for spotting this!

**Comment by rchiodo** [comment]
Does anybody have any verification steps?

**Comment by JustinGrote** [comment]
@roblourens they display as $true instead of 'true' for things like variable watch and variable set, but their type is set to 'boolean' with the latest PS preview extension which is what should truly matter, not the content of the value.

it's sort of two separate issues as described in https://github.com/PowerShell/vscode-powershell/issues/3703#issuecomment-978161754, this fix is one part that was discovered while fixing the other.

**Comment by roblourens** [comment]
Yeah I see that there is a `type` on Variable, and the regex is just a fallback.
