### ISSUE TITLE
Markdown editor keeps scrolling up and down on itself

### ISSUE THREAD

**Issue by Sco768** [microsoft/vscode#137882]
Issue Type: <b>Bug</b>

1) I'm editing a markdown with a preview on the right.
2) The file is long enough for a preview to have a scrollbar
3) I'm adding text to the end of the source

expected:
4) The source pane on the left is just reflecting what I'm typing

actual:
4) The source pane scrolls to the top, then back to the line I'm editing

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 4.15.0-162-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|15.50GB (0.70GB free)|
|Process Argv|--unity-launch --crash-reporter-id fa91e1bb-4fb3-428e-ae14-52837a931f20|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|unity|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|unity|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
perl-html-template|bia|1.1.7
vscode-perl|cfg|1.18.0
copy-path|Eti|0.0.1
copy-filename|jac|2.3.2
mysql-syntax|jak|1.3.1
vscode-edit-csv|jan|0.6.4
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
copy-file-name|nem|1.2.0
gremlins|nho|0.26.0
java|red|1.0.0
trailing-spaces|sha|0.3.1
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.7
vscode-java-test|vsc|0.33.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
