### ISSUE TITLE
[Inline Suggestion] Update suggestion after rendering

### ISSUE THREAD

**Issue by felixhao28** [microsoft/vscode#137843]
I would like to continuously append content to an already rendered inline suggestion. For now, I am using the "hide and trigger again" strategy, but this introduces unbearable flickering.

```ts
        await vscode.commands.executeCommand("editor.action.inlineSuggest.hide");
        await vscode.commands.executeCommand("editor.action.inlineSuggest.trigger");
```

The delay between each "hide and trigger" is 200ms in this video. My question is, can we have a way to append content without flickering?

https://user-images.githubusercontent.com/2417391/143376847-b6ef7a97-72cd-4d9c-9013-67e9515e8a17.mp4

**Comment by hediet** [comment]
> I would like to continuously append content to an already rendered inline suggestion.

What do you mean with that? What is your use-case?

**Comment by felixhao28** [comment]
For example, if the server takes 100ms to generate every word, to generate a 10-words suggestion, it will take 1000ms. With the existing method, the suggestion can only be rendered as a whole, so it will take at least 1000ms for the user to actually see any suggestion. This could be unbearable to the user because of the high latency. So I would like to show the first word as the suggestion after 100ms, then two words after 200ms, then three after 300ms, ... So the user can read the suggestion while the server is generating it.

**Comment by hediet** [comment]
Now I understand, you basically want to stream in the inline suggestion? That is not a scenario which is supported currently.
