### ISSUE TITLE
High CPU utilization and disconnects from remote SSH when current directory in integrated terminal contains many files.

### ISSUE THREAD

**Issue by dobos** [microsoft/vscode#137826]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.3 (system setup)
- OS Version: Windows_NT x64 10.0.19043 (on the client)

I'm seeing a weird issue when using vscode to access a remote linux server via ssh from a windows client (although I don't think the issue is specific to the client OS). When I open two terminals (either side by side or on separate tabs) and I cd into a directory on the remote machine which contains lots of files (250k+), the cpu utilization on the server goes up to about 250-300% (multi-core) and the ssh connection breaks due to a time-out. When I check the remote server from a different terminal not running under vscode, I can still see a node js process spinning on the cpus. The problems remains when I start with `vscode --disable-extensions`. Note, that the large directory is not under the project folder, nor it is referenced in any way from the project (i.e. symlink) - it's on a network-mounted zfs volume and I simply cd into it from the terminal. It appears that the integrated terminal launches some operation in the background to discover the contents of the cwd.

Steps to Reproduce:

1. Open vscode and load a project from a Linux server.
2. Open a bash terminal then split the terminal to have two side by side.
3. In one of the terminals, cd into a directory that contains lots of files.

**Comment by dobos** [comment]
I'm trying to track down the issue myself as well. The problem can be reproduced by simply cd'ing into a large directory and than copying the full path of the directory from the command line prompt. I've also attached the node profiler to the server side vscode process and the function `readdir` is consuming much of the cpu time so I guess the integrated terminal is trying to be smart here. I can't find which feature is causing this issue and how to disable it, at least temporarily, so I can proceed with my work.

Please find the profiler output attached.

[vscode-profile-2021-11-25-02-38-34.zip](https://github.com/microsoft/vscode/files/7601075/vscode-profile-2021-11-25-02-38-34.zip)

**Comment by dobos** [comment]
Alright, the workaround is to add

```
"terminal.integrated.enableFileLinks": false,
```

to `settings.json`. I think it would be worth adding some time-out for any link processing running in the background so that the UI or the remote process remains responsive even when large directories are accessed from the terminal.

**Comment by Tyriar** [comment]
This has been reported before which was why we added that setting. This should also be a bit better in the upcoming version as file stat results will get cached for 10 seconds: https://github.com/microsoft/vscode/issues/138904

**Comment by Tyriar** [comment]
Tracking a similar issue in https://github.com/microsoft/vscode/issues/139593
