### ISSUE TITLE
No SCM is populating

### ISSUE THREAD

**Issue by BorususriHarshavardhan** [microsoft/vscode#137860]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by BorususriHarshavardhan** [comment]
Issue Type: <b>Bug</b>

I am inside my git project which has .git folder in it, but it's not showing anything ( branch, commits)

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.18.0-305.7.1.el8_4.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (6.74GB free)|
|Process Argv|--crash-reporter-id 995a05ce-93db-4fea-becc-20cea947f7e3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.54.8.251|
|OS|Linux x64 4.18.0-305.7.1.el8_4.x86_64|
|CPUs|Intel Xeon E312xx (Sandy Bridge, IBRS update) (4 x 1995)|
|Memory (System)|9.56GB (1.30GB free)|
|VM|0%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.2
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
notepadplusplus-keybindings|ms-|1.0.7
material-icon-theme|PKi|4.10.0
python-template-snippets|Ric|1.2.0
jinjahtml|sam|0.16.0
jenkinsfile-support|sec|0.1.0
vscode-icons|vsc|11.7.0
jinja2-snippet-kit|Wya|2.0.0
material-theme|zhu|3.13.3
terraform|4op|0.2.2
json-yaml-schema-selector|74t|1.1.0
golangwithdidi|ald|0.0.1
vscode-markdownlint|Dav|0.45.0
docs-yaml|doc|0.2.7
githistory|don|0.6.19
gitlens|eam|11.7.0
code-runner|for|0.11.6
shell-format|fox|7.2.2
go|gol|0.29.0
terraform|has|2.16.0
yaml-plus-json|hil|1.9.2
githd|hui|2.2.4
jenkins-pipeline-linter-connector|jan|1.2.0
auto-comment-blocks|kev|1.0.1
start-git-bash|McC|1.2.1
json|Mee|0.0.1
prettify-json|moh|0.0.3
vscode-docker|ms-|1.18.0
vscode-kubernetes-tools|ms-|1.3.4
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
notepadplusplus-keybindings|ms-|1.0.7
gremlins|nho|0.26.0
material-icon-theme|PKi|4.10.0
gotestexplorer|pre|0.1.13
quicktype|qui|12.0.46
vscode-thunder-client|ran|1.9.1
java|red|1.0.0
vscode-yaml|red|1.2.1
jenkinsfile-support|sec|0.1.0
python|tht|0.2.3
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.7
vscode-java-test|vsc|0.33.0
vscode-maven|vsc|0.34.1
vscode-icons|vsc|11.7.0
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2
material-theme|zhu|3.13.3
vscode-proto3|zxh|0.5.5

(12 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593cf:30376535
vssld246:30401890
vscexrecpromptc:30404946
vscop804:30404766
vscop453:30404998

```

</details>

**Comment by CodeCrazy-ywt** [comment]
A big 👎🏻 to github-actions.
