### ISSUE TITLE
Signing in with Microsoft to sync settings doesn't load the signing page in the browser

### ISSUE THREAD

**Issue by mystiquewolf** [microsoft/vscode#137894]
Issue Type: <b>Bug</b>

I've installed the snap VS Code and it tries to load localhost:43305/signin?nonce=CFWr0x34yMcDMM9kvTm5Mg== but it doesn't load. I've installed apache and it loads on localhost.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.15.2-zen1-1-zen snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 3070)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.64GB (0.59GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id a554318b-95b7-49db-b2e6-57987d696a90|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasmawayland|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593cf:30376535
vssld246:30401890
vscexrecpromptt1:30404947
vscop804:30404766
vscop341:30404997

```

</details>

**Comment by mystiquewolf** [comment]
For what it's worth i've removed the snap VS code and installed the [AUR one](https://aur.archlinux.org/packages/visual-studio-code-bin/) - still can't login with it too.

**Comment by TylerLeonhardt** [comment]
What browser are you using? Can you try setting your default browser to something else and seeing if it works then?

**Comment by mystiquewolf** [comment]
I am using Firefox. Today i tried and it did load the page, i was able to sign-in successfully. Not sure what was the issue. It loads now with both Firefox and Google Chrome.

**Comment by TylerLeonhardt** [comment]
Hmm ok well if you repro this again, don't hesitate to reach out!
