### ISSUE TITLE
alt click will jump to path like "\x\y\z" in remote ssh workspace terminal

### ISSUE THREAD

**Issue by liuhuiping2013** [microsoft/vscode#137864]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.3
- OS Version: win10

Steps to Reproduce:

1. in remote ssh terminal
`
echo /aaa/bbb/ccc
`

2. Alt + Click the output
3. pop window: "\aaa\bbb\ccc"

**Comment by duanju** [comment]
I face the same issue in vscode with wsl. The file path in terminal window is right, but it is incorrectly changed to the windows style path before nevigatted to.

**Comment by duanju** [comment]
@Tyriar Do you have any idea on this bug? Thanks
