### ISSUE TITLE
SCM - dirty diff decorator shows progress in SCM viewlet on every keystroke

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#137870]
Does this issue occur when all extensions are disabled?: Yes/No

Steps to Reproduce:

1. Open a folder that has a git repository, and open the SCM viewlet. 
2. Open a file and start typing. 

Notice a very brief progress indicator in the SCM viewlet for every keystroke.
This is a regression that was introduced in https://github.com/microsoft/vscode/pull/136969

//cc @gjsjohnmurray

**Comment by lszomoru** [comment]
As a tactical fix, I have added a 250ms delay to the progress indicator. Though since the long running operation is related to a decorator that appears in the editor, I wonder whether the progress indicator should be better placed in the editor area rather than the SCM viewlet. @gjsjohnmurray, let me know what you think.

**Comment by gjsjohnmurray** [comment]
@lszomoru thanks for adding the delay.

I chose to use an SCM viewlet because the scenario which gave rise to the change is that the user opens a file they know they've changed, but they don't immediately see the changebar decorators because it's taking a while to fetch the pre-change version from source control (e.g. slow FileSystemProvider) and then compute the diff decorations. The user is likely to be thinking "where are the SCM-supplied diff decorators?" rather than "where is my file?" (which they can already see).

**Comment by lszomoru** [comment]
Wouldn't a progress indicator in the SCM viewlet or on the SCM activity bar item indicate to the user that something is happening in that particular viewlet and there will be a change in the viewlet when the operation completes? While I do understand that SCM is the one that does the work to provide the information for the diff decorators, the decorators themselves appear in the editor area. The editor progress does not necessarily mean that the file is not there. There are other actions in the editor "Go to References" which if its long running it will show a progress indicator in the editor.

**Comment by gjsjohnmurray** [comment]
Fair points. I suggest you make the change.

**Comment by lszomoru** [comment]
Editor progress can only be shown from an editor contribution and not from a workbench contribution so this turned out to be more complex than I have anticipated. I will take a look at this next milestone and will update the issue with my findings.

**Comment by gjsjohnmurray** [comment]
> Editor progress can only be shown from an editor contribution and not from a workbench contribution

Related: #114672 seems to be a request for extension authors to be able to do this.
