### ISSUE TITLE
Let extensions force change language mode for a file

### ISSUE THREAD

**Issue by PranayAgarwal** [Microsoft/vscode#13782]
I'm writing a new extension providing Hack language support. Hack files still have a .php extension, but start with ```<?hh``` instead of ```<?php```. 

I added the following in the "hack" entry in the language contributes section in package.json:
```json
    "extensions": [ ".php" ],
    "firstLine": "^<\\?hh\\b.*$"
```

However, all .php files in the workspace are still auto-detected as PHP, and the extension providers (registered with ```const HACK_MODE: vscode.DocumentFilter = { language: 'hack', scheme: 'file' };```) aren't triggered unless the file mode is manually changed from PHP to Hack.

I'm not sure if I'm doing something wrong, or if PHP is still getting a higher precedence. Is there any way for an extension to force this change?

**Comment by bpasero** [comment]
We might not support this ATM. PR/help welcome if someone wants to look into this.

**Comment by bpasero** [comment]
This actually is https://github.com/Microsoft/vscode/issues/10915
