### ISSUE TITLE
debugServer property should be under configurations

### ISSUE THREAD

**Issue by xanathar** [Microsoft/vscode#13783]
Currently the ``debugServer`` property in launch.json is at the same level of ``version`` - that is, it's global.
In my opinion it would make more sense for it to be under the specific configurations; the benefits would be:

* the extensions can fill launch.json appropriately (as far as I can see extensions can easily provide configurations when they are first clicked in the debug gear dropdown, but not global properties to launch.json)
* debug extensions using programs and ones using debugServer properties could be mixed-up in the same project 

Of course there is a high change that I'm missing something big - documentation about ``debugServer`` is hard to find and sparse, that being the case, sorry in advance :)

**Comment by isidorn** [comment]
+1 for this
The downside is that we would break existing launch.json that have debugServer on top. Though most of them just have it for development of debug adapters so IMHO this might be fine

@weinand opinion?

**Comment by weinand** [comment]
@isidorn agreed, having `debugServer` per launch configuration makes sense (and becomes even more important if we start to support multiple sessions).
I suggest that we start to support this and keep the global `debugServer` as well (but deprecate it).

**Comment by isidorn** [comment]
@weinand the only way to depricate the debugServer is via documentation since it is currently hidden in the launch.json inteli-sense.
I also propose to support top level debug server for one sprint and then depricate it

**Comment by weinand** [comment]
We should document both `debugServer` attributes in intellisense.

**Comment by isidorn** [comment]
But I top level I would document it with a deprecation message.
And it can get a proper message inside the configuration

**Comment by daviwil** [comment]
I just started using the `debugServer` property in the PowerShell extension and I agree, it'd be great to have it on a per-configuration basis!
