### ISSUE TITLE
scanner library in java

### ISSUE THREAD

**Issue by ankeshjaiswal996** [microsoft/vscode#137813]
Issue Type: <b>Feature Request</b>

warning while using object of scanner. It is compiled and run successfully but there is a resource leak.
It can be solved by using obj.close(), but in some program where we have implement scanner object multiple time it shows error.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by egamma** [comment]
Thanks for the feature request, but there is nothing in the VS Code project we can do to address this request.
