### ISSUE TITLE
[Feature Request] Improve automation of MSVC DevEnv

### ISSUE THREAD

**Issue by BinToss** [microsoft/vscode#137858]
See https://code.visualstudio.com/docs/cpp/config-msvc#_run-vs-code-outside-the-developer-command-prompt

# Problems
`C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools/VsDevCmd.bat`
- static path. Contributors may install their tools to a custom path.
- Locked to Visual Studio. Contributors may prefer the standalone MSBuild SDK.
- Locked to one year or major version. Contributors may be on 2017, 2019, 2022, or others.
- Locked to one distribution branch. Contributors may use Community, Professional, *or* Enterprise.

```json
  "windows": {
    "options": {
      "shell": {
        "executable": "cmd.exe",
```
- Assumes the host is a Windows OS. VS2022 supports OSX.
- Does not take advantage of Windows Powershell or Powershell Core with Microsoft/VSSetup.Powershell to locate the current project's required workloads/components.
- Does not alternatively leverage vswhere to locate toolset dirs

# Solution(s)

## Locate the latest version of the Visual Studio that contains the specified workloads/components

```powershell
# Import-Module VSSetup

$VsReqs = "Microsoft.Component.VC.Runtime.UCRTSDK", "Microsoft.VisualStudio.Workload.NativeDesktop", "Microsoft.VisualStudio.Component.WinXP";

try {
    $MatchedVsInstallDir = (
        Get-VSSetupInstance -All -Prerelease | Select-VSSetupInstance -Latest -Require ($VsReqs)
    ).InstallationPath
    Write-Verbose $MatchedVsInstallDir
}
catch {
    $errMsg = "Failed to find a Visual Studio or MSBuild Tools install containing the following:`n";
    $VsReqs | ForEach-Object {
        $errMsg = $errMsg + "`t" + $_ + "`n";
    };

    Write-Error -Message $errMsg
}
```

## Get Visual Studio's PowerShell module for Enter-DevEnv
```powershell
Import-Module '../deps/Posh.Get-VSInstallDir/src/Get-VSInstallDir.psm1'

function Enter-VSDevEnv {
    [CmdletBinding()] param (
        [Parameter()] [bool] $Prerelease = $true,
    )

    $vsInstallDir = Get-VSInstallDir; # TODO: REPLACE

    Import-Module "$vsInstallDir/Common7/Tools/Microsoft.VisualStudio.DevShell.dll";
    Enter-VsDevShell -VsInstallDir $vsInstallDir -SkipAutomaticLocation;
}
```

**Comment by gjsjohnmurray** [comment]
How does this relate to Visual Studio **Code**, for which this is the GH repo, and which is a different product?

**Comment by egamma** [comment]
This issue refers to Visual Studio, this repository is for Visual Studio Code as @gjsjohnmurray observes.

**Comment by BinToss** [comment]
This issue applies to the documentation and automated tasks of Visual
Studio *Code* and how Visual Studio *Code* interacts with the MSVC build
tools.

I did not submit this issue to Visual Studio IDE, MSBuild, or their related
software because this issue does not request changes to them.
This issue suggests utilizing existing features of those software to solve
a hassle present in Visual Studio *Code*'s integration with them.

**Comment by egamma** [comment]
/extC++

@BinToss I'm sorry I've overlooked the link to the C++ documentation in VS Code. Please report the issue against the C++ extension.

**Comment by BinToss** [comment]
You're right. I should have submitted this issue to the C/C++ extension's
issue tracker.
