### ISSUE TITLE
There should be a "workspace manager" window

### ISSUE THREAD

**Issue by bediu** [microsoft/vscode#137804]
I've been using vscode for a very long time now. Before, I've used visual studio and other ides such as netbeans. There's nothing that the current vscode can't do better than all the other ides of my time, except in one thing it has been lacking badly, and I've been waiting very patiently thinking it'll come soon enough.

It has started to feel like a very dull chore having to open my workspaces with `ctrl + k + o` through a file open dialog after years of using vscode. Thus I propose we have some sort of "workspace manager" window which we open with a keyboard shortcut. 

This window will have the following features at a minimum:
* Latest workspaces (expandable)
* Pinned/favorite workspaces
* Icon coded (the icon is set by the project's main programming language)

The reason why we need this is that we don't have to deal with the limits of the whichever file open dialog we happen to be using. For example in my linux distro, it does support marking certain directories as favorite but my file open dialog is not limited to vscode only. I have other favorite directories which I would like to open with another software, so the UX takes a hit. 

Note: by workspace I mean a working directory

All the best

**Comment by egamma** [comment]
@bediu have you tried the project manager extension https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager?

**Comment by bediu** [comment]
@egamma I haven't and I didn't look for one either - but it seems I should have! The sidebar menu + tagging feature just sold it for me! Got all my projects nicely organized in 5min. Thanks for that suggestion!

I can leave the issue open since it's also nice to discuss a native solution as well. Given 2million extension downloads seems like it's worth looking into.
