### ISSUE TITLE
Auto-reconnect for remote debuggers

### ISSUE THREAD

**Issue by robertaistleitner** [microsoft/vscode#137852]
When using a remote debugger like Python it would be awesome to have an auto-reconnect feature with a configurable timeout.

Using the debugger is pretty uncomfortable to use if you have some kind of code auto-reloading feature in place which in causes the debugger connection to get lost for a short period of time because of reloading/restarting.

I guess this would need to be implemented in here and not in the https://github.com/microsoft/vscode-python project, right?

**Comment by weinand** [comment]
@robertaistleitner no, this functionality must come from the debugger extension, in your case Python.

**Comment by robertaistleitner** [comment]
Thanks for pointing out @weinand, I've opened an issue here: https://github.com/microsoft/vscode-python/issues/18079
