### ISSUE TITLE
workbench.colorCustomizations not working after the latest update

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#137867]
Issue Type: <b>Bug</b>

workbench.colorCustomizations stopped working after the latest update.

VS Code version: Code - Insiders 1.63.0-insider (1e473b624f088fc05269891170a8ffa1c84a35a6, 2021-11-25T09:04:34.615Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (4.12GB free)|
|Process Argv|--crash-reporter-id f5a247d1-3472-440d-8ba1-1c2f1706a088|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|13.0.0
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
output-colorizer|IBM|0.1.2
vscode-typescript-next|ms-|4.6.20211124
angular-console|nrw|17.12.4
vscode-xml|red|0.18.1
vscode-yaml|red|1.2.1
sonarlint-vscode|Son|3.1.0
code-spell-checker|str|2.0.13
vscode-stylelint|sty|1.2.1
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593cf:30376535
vsc1dst:30396469
pythonvs932:30404738
vscexrecpromptt2:30397559
vscop804cf:30404767
vs360cf:30404996

```

</details>

**Comment by sanket-bhalerao** [comment]
<img width="958" alt="issue" src="https://user-images.githubusercontent.com/9264813/143429869-db950d1b-218c-4a08-8a12-b58d31245369.png">
these are the custom colors i have set in the settings. after updating the vscode-insiders to latest version it stopped working
Version: 1.63.0-insider (user setup)
Commit: 1e473b624f088fc05269891170a8ffa1c84a35a6
Date: 2021-11-25T09:04:34.615Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by pingshunhuangalex** [comment]
+1
https://github.com/material-theme/vsc-community-material-theme/issues/24
