### ISSUE TITLE
Configure JS / TS Project via package.json

### ISSUE THREAD

**Issue by tivac** [Microsoft/vscode#13786]
I don't love needing to add yet another metadata file to my projects. But I love the improved `vscode` intellisense from adding a `jsconfig.json` file to my projects.

Has there been any discussion of allowing `vscode` configuration via `package.json`, much like [ESLint](eslint.org/docs/user-guide/configuring#configuring-eslint)?

Something like this:

``` js
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "...",
  "license": "MIT",
  "dependencies": {
    // ...
  },
  "vscodeConfig": {
    "compilerOptions": {
      "target": "ES6",
      "module": "commonjs"
    }
  }
}
```

That way no extra editor-specific file is required to be added to every single project that you want the benefits of configuring `vscode`.

**Comment by waderyan** [comment]
@tivac thank you for opening this issue. We are evaluating this experience right now and appreciate your insight! Stay tuned.

**Comment by waderyan** [comment]
@bowdenk7 I'm thinking this feature request might more sense in TS repo. What are your thoughts? Is this something on your radar? I searched TS issues and couldn't find it.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#13800
