### ISSUE TITLE
Show suggestion when I press any kind on key. Like [$,  !, %, ... or anything]

### ISSUE THREAD

**Issue by NazmusSayad** [microsoft/vscode#137825]
Please add a new feature that will show the suggestion whenever I press any key. It does not matter which key to press but show the suggestion widget.
Such as when press $, this will suggest to input template literals or any snippets.

**Comment by egamma** [comment]
/needsMoreInfo pls describe the feature in more detail and explain the benefits of this new feature over the existing support.
