### ISSUE TITLE
Types in object properties are highlighted incorrectly

### ISSUE THREAD

**Issue by richardsimko** [microsoft/vscode#137805]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.62.3
- OS Version: macOS 12.0.1 (21A559)

Steps to Reproduce:

Example file:

```js
function test() {
    
}

const asd = { a: test };
```

I expect `test` on the last line to be highlighted in the same color as `test` in the function definition. This used to be the case but since a few versions back this is no longer the case.

Using "Inspect Tokens & Scopes" it shows `foreground | variable` but for the function definition it shows `foreground | entity.name.function`.

**Comment by IllusionMH** [comment]
Works in TS files (VS Code Insiders), for JS I think you need to have `"checkJS": true` in `tsconfig.json`/`jsconfig.json` to have it highlighted same as TS.

**Comment by richardsimko** [comment]
It does not work in Typescript files on VS Code Insiders for me. But the fact that it works for you indicates that it is indeed some setting on my end. Any idea which setting it might be? Here is an example of a completely new file, no project or anything, just created a new file and set the type to TypeScript.

![image](https://user-images.githubusercontent.com/1245031/143451864-4fa6cb14-67c8-469a-9cc9-6322c7b5413c.png)

**Comment by richardsimko** [comment]
In Insiders it works for me in both JS and TS but in VS Code it does not work in either. Perhaps the bug is fixed or is there a setting that would disable this for TS as well?

Insiders in the foreground "regular" VS Code without plugins in the background:

![image](https://user-images.githubusercontent.com/1245031/143452408-801fb193-ef76-48b7-af42-2ffbd0fa2c62.png)

**Comment by richardsimko** [comment]
`"typescript.tsserver.useSyntaxServer": "always",`

This seems to have been the culprit. Removing that brought back proper syntax highlights!

**Comment by IllusionMH** [comment]
Great find!
