### ISSUE TITLE
Notebooks: No visual indication that cells are pending on a cell in "Run by line" status

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode#137834]
Version: 1.63.0-insider (user setup)
Commit: ed3018f4310e906daa0a9119d997e75b8a38b879
Date: 2021-11-23T05:33:39.595Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

1. open an ipynb file
2. start "Run by line" in any of the cells
3. wait until "Run by line" finishes starting, i.e. cursor stops at the first line in the cell
4. perform "Run All" 

Actual:
No cells are running because execution is pending on the cell in the "run by line" status, however there's no visual indication telling users that. It could be confusing as to why nothing is running.

**Comment by roblourens** [comment]
I think that https://github.com/microsoft/vscode/issues/130611#issuecomment-919582034 will be the best solution to this
