### ISSUE TITLE
Feature Request: Make it possible to switch focus between multiple cursors

### ISSUE THREAD

**Issue by ChrisWeit** [microsoft/vscode#137873]
It is already possible, if you use snippets, to jump between multiple positions, with tab. 

Now it would be useful, if you had multiple cursors active, that you could
1. focus on one of them 
2. and be able to switch in between them,

through the use of a shortcut.

This would simplify the implementation of, for example, multiple methods, with a simple shortcut.

Thanks.

**Comment by DMfTom** [comment]
Yeah, that would be really helpful and make programming a lot easier.

**Comment by alexdima** [comment]
Let's track in #135460
