### ISSUE TITLE
can't input chinese in editor

### ISSUE THREAD

**Issue by sheyong** [microsoft/vscode#137876]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T07:59:13.865Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 17.7.0

Steps to Reproduce:

1.open vscode editor
2.change input method app to chinese。
![image](https://user-images.githubusercontent.com/1137538/143439912-c10e3bc1-3ee0-470a-b67b-7aac2a9f0019.png)

There was no problem before I updated vscode。

**Comment by alexdima** [comment]
@sheyong Which input method are you using and what keys are you pressing?  Please explain in the greatest possible detail what steps I should take to reproduce the problem. Here is an example of the kind of steps I am looking for --> https://github.com/microsoft/vscode/wiki/IME-Test#windowsmac-japanese
