### ISSUE TITLE
Markdown string in the test message is not unescaped

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#137851]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.63.0-insider (user setup)
Commit: c1f2f40bcd81380bf2e286af64becddada57db88
Date: 2021-11-24T05:33:22.438Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Append a test message with a markdown string to an test item.
```ts
const md = new MarkdownString();
md.appendText('  at a.b.Class.java:123');
const mdMessage = new vscode.TestMessage(md);
...
```
2. Click the `Open in Editor` button at the right top corner of the test message
3. The displayed text is escaped format

![image](https://user-images.githubusercontent.com/6193897/143397691-32bc4cf2-f6bd-44d1-8906-3d24b635c0ea.png)

![image](https://user-images.githubusercontent.com/6193897/143397647-a070c118-8226-4b01-b1d6-0406ef36b6b5.png)

**Comment by connor4312** [comment]
This is intentional -- when opening in the editor we show the exact source of the failure message (or expected or actual results).
