### ISSUE TITLE
Diff view: output metadata change UX is confusing

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode#137836]
Version: 1.63.0-insider (user setup)
Commit: ed3018f4310e906daa0a9119d997e75b8a38b879
Date: 2021-11-23T05:33:39.595Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:
1. open this notebook in VS Code https://github.com/claudiaregio/data-science/blob/main/Titanic.ipynb
2. "Run All" cells
3. switch to the diff view for the notebooks file
4. scroll down to this cell
![image](https://user-images.githubusercontent.com/26419852/143326886-98a88815-116c-4813-800e-1b8ee881af76.png)

It's confusing that the two tables are highlighted in red and green colors, even though their content is identical. Also, the "Switch output rendering" button is hard to discover as it's on the far-right side.

**Comment by minsa110** [comment]
Related: https://github.com/microsoft/vscode/issues/135820

**Comment by greazer** [comment]
I knew I saw this before. Closing #135820 in lieu of this one. I think Claudia may have run into this too.

**Comment by greazer** [comment]
Actually closing this one instead. #135820 is the original and contains much more detail.
