### ISSUE TITLE
Tasks: Find the command a task will execute.

### ISSUE THREAD

**Issue by svanimpe** [microsoft/vscode#137895]
- VS Code Version: 1.62.3
- OS Version: macOS 11.6

When I create a `Task` with the following `ShellExecution`:

`new vscode.ShellExecution(command, args)`

I'd like to find out what command the `Task` will actually execute (after quoting it appropriately), so that I can display that to the user *before* they execute it. However, I can't find an API to request this command. Is there one? If not, where in the source code is this command calculated?

Thanks!

**Comment by alexr00** [comment]
@svanimpe are you looking for the exact command line that will be run? If yes, that's not accessible through the extension API, and we have no plans to add it. The command line is computed here: 

https://github.com/Microsoft/vscode/blob/b1dc0b0ebf7d4f4c20464601878fb8e2c2549b32/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1339-L1340

I wouldn't recommend recomputing this value as it is probably more information that the user wants instead, the value of your `command` that you pass into `new ShellExecution` is probably more valuable.
