### ISSUE TITLE
VSCODE wont show french accents properly (they dont even appear) even on UTF-8

### ISSUE THREAD

**Issue by WildFearless** [microsoft/vscode#137989]
Does this issue occur when all extensions are disabled?: Yes/No
IDK since i need to be able to compile a java file

- VS Code Version: 1.62.3
- OS Version:  10.0.19044 Build 19044

Steps to Reproduce:

I type chcp, it shows 65001 since it is the one for windows cmd to show accents. My vscode shows utf-8 in the bottom right. It wont show the accents at all, it just removes it from displaying the string. The only way to "fix it" is to do chcp 1252 which now fixes it. It used to work just fine yesterday and in the last 2 months but since i had issues with windows language keyboards it started happening.... My windows is set to accept UTF-8 worldwide language support....
   
Idk what to do to permanently fix it like it used to be.... The only fix I could think of is forcing chcp 1252 when I run any java files but idk what to do anymore....

I tried changing dectect locale to on/off/auto and it doesnt work either. I tried integrated or external terminal and it doesnt seem to want to force it to my CMD (I tried running a test java to see if it works on CMD and it does)

PS C:\Users\Alex\Documents\Java>  & 'C:\Program Files\Semeru\jdk-11.0.12.7-openj9\bin\java.exe' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:51701' '-cp' 'C:\Users\Alex\AppData\Roaming\Code\User\workspaceStorage\546c1e2d180863c743a32792d9653675\redhat.java\jdt_ws\Java_57fe1ceb\bin' 'BIGBOSS.conceptPOO.Exercices.cours2.AlexandreP_ex04'

**Comment by WildFearless** [comment]
Earlier today, I found a fix with someone else on reddit and a bunch of testing. I created a .ps1 profile for powershell in ~\Documents\WindowsPowerShell and added "chcp 1252 | out-null" in the profile to force it everytime my vscode opens. It feels a little bit like a jank solution but hey, if it works then it works uh...

**Comment by Tyriar** [comment]
I think we're behaving correctly here and difficulties setting the default codepage is a problem with Windows https://superuser.com/q/269818/205226. cc @TylerLeonhardt in case you have experience in this area with codepage in pwsh.
