### ISSUE TITLE
Initial authorisation for Publish or Clone on Windows does not correctly authorise git-credential-manager

### ISSUE THREAD

**Issue by physcrowley** [microsoft/vscode#137936]
Issue Type: <b>Bug</b>

This error only occurs when a Windows computer has not been previously authorised on GitHub. This happened with Git for Windows version 2.32.1.windows.1 and 2.33.1.windows.1

Any attempt to Publish a new repo or Clone an existing repo would seemingly go through the normal authorisation process (ask to Allow authorisation with GitHub -> open a browser tab to enter credentials and an alert to allow VS Code to open the resulting link). A copy of the repo would be created (on GitHub for a Publish attempt or locally for the Clone attempt), but none of the files would be transfered and the process would hang.

We would have to manually open Task Manager and kill the git processes as well as the git-credential-manager processes, then  delete the half-created repo.

#### One solution

The solution that we found was to run a `git clone` from the command line and authenticate via the Browser. Instead of the authorisation page that would appear from the VS Code interactions, the authorisation page was specifically for Git Credential Manager. Once that was authorised, the clone would complete successfully and there were no more issues with git actions (clone / publish / push / pull) in VS Code.

#### VS Code solution?

Is there a way to get the VS Code flows properly authorising Git Credential Manager?

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (1.95GB free)|
|Process Argv|--crash-reporter-id 62f030fd-d897-4cb3-88da-2525bc9a780b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
vscode-pull-request-github|Git|0.32.0
processing-vscode|Luk|2.4.0
vscode-language-pack-fr|MS-|1.62.4
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
remote-wsl|ms-|0.58.5
java|red|1.0.0
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.7
vscode-java-test|vsc|0.33.0
vscode-maven|vsc|0.34.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593cf:30376535
vssld246:30401890
vscop804cf:30404767
vscop341:30404997

```

</details>

**Comment by lszomoru** [comment]
@physcrowley, apologies for not getting back to you on this issue until now. To better understand the way VS Code integrates into the git authentication pipeline, I would suggest that you read this comment - https://github.com/microsoft/vscode/issues/144420#issuecomment-1096643247. In case you are still able to reproduce this problem there are ways that we can collect additional information but based on your description it seems to me that for some reason GCM is not being invoked during the initial authorisation request, since the authorisation requests "reaches" VS Code.
