### ISSUE TITLE
【git】 vscode should add a `fetch` to the ... menu 

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#137916]
because user will disable the auto fetch. or the interval is long

vscode adds `pull`, `push`, `clone` and `check out`， I believe `fetch` is the necessary command for user. If disable the auto fetch or we user just want to know is there any commit from remote before `commit and push`, we have to execute the `fetch` immediately.

![image](https://user-images.githubusercontent.com/1876302/143535829-c6702add-1f77-4f73-bcd9-527ff4a3c19e.png)

**Comment by lszomoru** [comment]
Merged pull request https://github.com/microsoft/vscode/pull/137940

**Comment by lszomoru** [comment]
Verification steps:
- Open VS Code Insiders, and open a folder/workspace with a git repository
- Switch to the "Source Control" viewlet
- Click on the `...` menu and click on the "Fetch" menu item
- Switch to the Git output using the "Git: Show Git Output" command
  - Confirm that you see a `git fetch` command that was executed
