### ISSUE TITLE
Unicode highlight styling can't be customised

### ISSUE THREAD

**Issue by pingshunhuangalex** [microsoft/vscode#137961]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.0-insider
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Type a full-width Unicode character like `：`
2. Check the colour of the border got highlighted

![image](https://user-images.githubusercontent.com/17170199/143663419-ab6caa13-6512-489c-aae7-0ffe2bbebda4.png)

The colour of the highlighted border for the Unicode highlight option is not controlled by any of the `xxxHighlightBorder` Theme Color properties. Therefore the style of the highlight can't be overridden (foreground, background, border, etc.)

**Comment by usernamehw** [comment]
```js
"workbench.colorCustomizations": {
	"editorUnicodeHighlight.border": "#0000ff",
},
```

**Comment by pingshunhuangalex** [comment]
Works like a charm. Thanks.

Double-checked it in https://code.visualstudio.com/api/references/theme-color, but still can't find this property. It'll be nice if the doc can stay up to date.

Also keen to know if there are other properties that are not yet documented.

Please feel free to close the issue if it's no longer relevant. Thanks.

**Comment by hediet** [comment]
This feature is still under development and will be released in about two weeks, we will update the docs then.

What is your experience so far with this feature? Does the warning make sense in your screenshot?
Why do you want to tweak the colors? (Is red to offensive?)
We are still discussing if the default color should be a different one (e.g. blue).

**Comment by pingshunhuangalex** [comment]
- Personally, I think it should be part of the warning family so I expect it to be consistent with other warning styles (a yellow squiggle in my own case).

- Red strike me as an error and the box style border also amplifies it, so yes it's a bit too strong to my taste. And I need to tweak it to fit my own theme colour palette and styles. Blue could be a better candidate indicating `info`

- I like the message the new warnings deliver, but if it can take the context of the file/section into consideration, it'll even be better. For example, the warning shouldn't show up in the comment section when the language used is not English (could be a toggle in the setting). Or maybe take a step further, having a quick fix button below the message to ignore/fix the issue.

Just my 2 cents with quickly trying things out. Really appreciate the team making VS Code better and more powerful day by day. Please keep up the awesome work.

**Comment by hediet** [comment]
Thanks for your feedback!

> For example, the warning shouldn't show up in the comment section when the language used is not English (could be a toggle in the setting).

This should already be the case: These boxes should not be shown in comments.

**Comment by thernstig** [comment]
@hediet Will the background color also be customizable in some way, or would that be weird?

**Comment by hediet** [comment]
Sounds like a reasonable request! Please create a separate feature request for that. If you like, you can also come up with a PR.
