### ISSUE TITLE
binary or uses an unsupported text encoding

### ISSUE THREAD

**Issue by prathameshpawar17** [microsoft/vscode#137911]
the terminal can't run the code, thay can run the code but the terminal con't axcept input. in the screan thay show the file is not displayed in the editor in the editor becouse it is either binary or uses an unsupported text encodind.

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" terminal
