### ISSUE TITLE
Show the extension/source overriding the default value of a setting in settings editor

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#137943]
With https://github.com/microsoft/vscode/issues/46851, an extension can override default values of a setting by contributing defaults to `contributeDefaults` contribution point. Eg:

```json
"configurationDefaults": {
      "workbench.colorTheme": "Monokai"
    }
```

It would be nice if settings editor can display the source of the default value

![image](https://user-images.githubusercontent.com/10746682/143592748-e872559f-9a42-49d6-91af-f8b126a7e509.png)

CC: @misolori

**Comment by sandy081** [comment]
@rzhao271 Configuration registry provides you with the source of the default value - 

https://github.com/microsoft/vscode/blob/212deea1ccf107e9e1a167b7b26ceac6f270f448/src/vs/platform/configuration/common/configurationRegistry.ts#L205

**Comment by misolori** [comment]
I think appending to the end could be a good start:

`Monokai        default(Extension Name)`

**Comment by rzhao271** [comment]
An issue in this case is that when the extension name is long, there is not enough room to show the source on the right side of that enum option.

Another possible option is to add a codicon next to the setting at the top, where hovering over it would show the extension that overrides the default:
![settings-space](https://user-images.githubusercontent.com/7199958/148608541-f7a8bfab-7160-4695-b07a-507cee53561f.PNG)

**Comment by misolori** [comment]
I think where the "Sync: Ignored" would also be a good option since that is additional meta data. You could do something like:

<img width="420" alt="image" src="https://user-images.githubusercontent.com/35271042/148811503-92edc564-85ef-4f76-988b-72fe47c920fb.png">
