### ISSUE TITLE
double-click to open the file error

### ISSUE THREAD

**Issue by waka3** [microsoft/vscode#137906]
Issue Type: <b>Bug</b>

Double-click to open the selected file, expecting to open the selected file, but actually opened the currently selected file and the last file of the currently selected file, and the work window shows the last file

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.81GB free)|
|Process Argv|--crash-reporter-id 01a8e23e-0c67-4df5-a1ed-4da32b5be8b7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
iconify|ant|0.2.2
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.5.0
cssrem|cip|2.6.0
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.28.0
flutter|Dar|3.28.0
vscode-html2pug|dba|4.0.0
FreeMarker|dco|0.0.9
githistory|don|0.6.19
jquerysnippets|don|0.0.1
vscode-style-formatter|dwe|1.0.0
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.23
pug2html|gin|0.0.5
autofilename|Jer|0.1.3
i18n-ally|lok|2.8.1
dotenv|mik|1.0.1
easy-less|mrc|1.7.3
vscode-jade-snippets|mrm|1.0.1
vscode-less|mrm|0.6.3
vscode-pugbeautify|mrm|1.0.2
vscode-docker|ms-|1.18.0
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
remote-wsl|ms-|0.58.5
debugger-for-chrome|msj|4.13.0
JavaScriptSnippets|nat|0.2.0
vetur|oct|0.35.0
view-in-browser|qin|0.0.5
vscode-sorting-attrs|rba|1.0.6
code-settings-sync|Sha|3.4.3
autoimport|ste|1.5.4
vscode-stylelint|sty|1.2.1
language-stylus|sys|1.14.1
vscode-import-cost|wix|2.15.0
ReactSnippets|xab|2.4.0
five-server|yan|0.1.1
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30402085
vsaa593cf:30376535
vssld246:30401890
vscexrecpromptt2:30404948
vscop804:30404766
vscop341:30404997

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command to check whether any of your extensions are causing this.

**Comment by JacksonKearl** [comment]
\gifPlease
