### ISSUE TITLE
[Window not Responsive ]

### ISSUE THREAD

**Issue by soljohnston777** [microsoft/vscode#137910]
[After the last couple updates Visual studio code keeps freezing if I leave it alone for a 30 minutes or more. It's like there is a memory hole.  It never used to do this.  

I have a computer with 40GB ram and lots of space on my hard drive.   
I am a computer tech and I know I don't have any malware or spyware.  None of my other programs are doing weird things. 

I only use 2 or 3 tabs at a time. I am using your stable build and this never used to happen, even if I put my computer in hibernate in the past. ]

**Comment by egamma** [comment]
/needsMoreInfo please provide more information about your setup when this happens, what extensions, what kind of workspace. One way to do so is to add the info that gets added when you create an issue from inside VS Code using Help>Report Issue.
