### ISSUE TITLE
Unable to open PHP files directly 

### ISSUE THREAD

**Issue by rudrakshpathak** [Microsoft/vscode#13798]
In 1.5.3 build I can open the PHP files by directly clicking the file icon. But in 1.6.* I'm unable to open them directly. A blank VS code window appears every time. But if I try to open it by selecting open with option, works fine. 
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: robertohuertasm.vscode-icons-3.0.4

**Comment by bpasero** [comment]
@rudrakshpathak can you share how this looks like when it does NOT open the file you want to open?

**Comment by bpasero** [comment]
![editors](https://cloud.githubusercontent.com/assets/900690/19412127/223606f8-930f-11e6-885f-52a234dd8cb1.gif)

Works for me as you can see.

**Comment by rudrakshpathak** [comment]
![vs code issue](https://cloud.githubusercontent.com/assets/8897522/19412310/c9bb5718-9330-11e6-915b-6f92026aa734.gif)

Hi @bpasero please see this. I'm still having this issue.

**Comment by bpasero** [comment]
@rudrakshpathak can you open settings and add this:

```
// Place your settings in this file to overwrite the default settings
{
    "telemetry.experiments.showDefaultViewlet": false,
    "telemetry.experiments.showCommandsWatermark": false,
    "telemetry.experiments.openUntitledFile": true
}
```

Then close all instances and try again?

**Comment by rudrakshpathak** [comment]
I did. Now its opening a new untitled file. I tried removing the last line of setting - 
> "telemetry.experiments.openUntitledFile": true
but didn't work.
![vs code issue 1](https://cloud.githubusercontent.com/assets/8897522/19415959/3e5d9ffe-939f-11e6-9a5a-2b8a0eefaff0.gif)

**Comment by bpasero** [comment]
@rudrakshpathak ok so it is unrelated to these settings, I was just suspecting something there. 

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by rudrakshpathak** [comment]
Sure :)

**Comment by bpasero** [comment]
@rudrakshpathak does it reproduce?

**Comment by rudrakshpathak** [comment]
I installed the insider version but the issue remains. One thing i would like to mention that the build 1.6.* is working fine on my other Windows machine.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by rudrakshpathak** [comment]
I uninstalled the extensions but that didn't work. Only PHP files are not opening rest everythig is fine with v1.6.*

**Comment by bpasero** [comment]
I wonder if this is related to the "Open in VS Code" registry thing. @joaomoreno does this ring any bell? Given it works on another machine, maybe its something written wrong to the registry that exhibits this.

**Comment by joaomoreno** [comment]
None. Did you install any extensions in the Insider version @rudrakshpathak?

**Comment by joaomoreno** [comment]
Uhoh: #13919
