### ISSUE TITLE
When you open Visual Studio Code you get a black screen and cant see anything

### ISSUE THREAD

**Issue by rahdev** [Microsoft/vscode#13799]
- VSCode Version: Latest Stable Release from download
- OS Version:Ubuntu 64 bit running in Virtual Box VM

Steps to Reproduce:

1. Log into Virtual Box Ubuntu VM
2. Download and install VSC .deb
3. Start Application from Developer folder
4. You get a black screen and cant see anything.

**Comment by amritanshu-pandey** [comment]
![visual-studio-code-bug](https://cloud.githubusercontent.com/assets/5570314/19414562/534fa716-939c-11e6-88f3-ab37d5b81c8d.png)
I am also facing the same issue. In the screen shot, the window appears to be white, but actually its black.

**Comment by tomcumming** [comment]
can reproduce on ubuntu 16.04 running on virtualbox latest stable

**Comment by isidorn** [comment]
Dup of some issue opened 7 days ago - please search our github issues for details.
In short: an electron rendering problem in the meantime please start with the flag you already found

**Comment by MehmetKaplan** [comment]
As a workaround, I have edited file /usr/share/applications/code.desktop

Replacing 
`Exec=/usr/share/code/code --unity-launch %U`
with
`Exec=/usr/share/code/code --disable-gpu --unity-launch %U`
solved my problem of launching code through launcher.

Just in case one may need...

**Comment by jradxl** [comment]
Indeed I did, Thankyou!

**Comment by jgeorgeson** [comment]
The `--disable-gpu` option isn't working for me, though it's just the application text that isn't displayed for me (file contents are displayed. . Maybe just missing some fonts?

![vscode-no-content](https://cloud.githubusercontent.com/assets/10238523/24405932/30cd7072-138c-11e7-8fae-338a96a7d593.png)

Version info:
```
Version 1.10.2
Commit 8076a19fdcab7e1fc1707952d652f0bb6c6db331
Date 2017-03-08T14:00:46.854Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```

Running on CentOS 7.3 in Xfce4 under vnc4xserver, connected via TightVNC Viewer.

**Comment by ArtStepanyuk** [comment]
code --disable-gpu Workaround works just fine for me

**Comment by jgeorgeson** [comment]
@ArtStepanyuk thanks for commenting as I couldn't find this issue again to follow-up! In my case it's a matter of unmet dependencies rather than the GPU rendering. I'm running on an AWS EC2 instance of the official Centos 7.x AMI, and had only installed the xfce4 group and vnc4xserver. Once I also installed the "_Server with GUI_" group then the application text started rendering. So there's a runtime dependency that's not declared in the RPM.

**Comment by nighto** [comment]
On Windows 10, after last update (Help > About says version 1.16.1) when I open Code the screen goes totally black, as if I have powered my monitor off (if that was possible on a notebook). Running with `--disable-gpu` fixes the problem.

**Comment by nicolasayotte** [comment]
For me, Zen Mode renders correctly even with this bug (CTRL-K, Z) if that can give a clue to the devs.
