### ISSUE TITLE
Wrong Output

### ISSUE THREAD

**Issue by SoumiK-777** [microsoft/vscode#137998]
Issue Type: <b>Bug</b>

#include <iostream>
#include<cmath>
using namespace std;

int main(){
    int n;
    cout<<"Taking Input"<<endl;
    cin>>n;
    int c=0;
    int m=n;
    while(m>0){
        c++;
        m/=10;
    }
    m=0;
    cout<<n<<endl;
    while(n>0){
        int p=(pow(10.0,(c-1)));
        m=m+(n%10)*p;
        n/=10;
        c--;
    }
    cout<<"Reverse is:"<<m<<endl;
    return 0;
}

Above is the code to reverse a number, the logic is perfectly alright but vs code is returning wrong output, i tried the same code on other ide, it is giving the desired output.
Input-123
Output-318
Expected output-321

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:07:04.152Z)
OS version: Windows_NT ia32 10.0.17134
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.96GB free)|
|Process Argv|--crash-reporter-id 298e4607-f6de-4d43-9f23-a631be87b934|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.6
cpptools|ms-|1.7.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30402085
vsaa593:30376534
vssld246:30401890
vscexrecpromptt1:30404947
vscop804cf:30404767
vscop341:30404997

```

</details>

**Comment by timmermansjoy** [comment]
you said other IDE. Maybe it uses a different compiler than the one you use with vscode wich could give different outcomes?
