### ISSUE TITLE
Is there any plan to support official project manager tools like Kanban or Trello?

### ISSUE THREAD

**Issue by SilenceHe** [microsoft/vscode#137965]
I really want to manage project schedule or sprint schedule or time schedule in VSCode, and want to keep it anywhere any devices with my hotmail account, is there any plan to support official project manager extension like Kanban or Trello tools?

**Comment by egamma** [comment]
This is an extension opportunity and there are already several extensions in the Marketplace that integrate a project manager /kanban tool, pls see https://marketplace.visualstudio.com/search?term=kanban&target=VSCode&category=All%20categories&sortBy=Relevance and https://marketplace.visualstudio.com/search?term=trello&target=VSCode&category=All%20categories&sortBy=Relevance.
