### ISSUE TITLE
Need launch.json template for Node-Red node (Rpi + win + iOS)

### ISSUE THREAD

**Issue by PizzaProgram** [microsoft/vscode#137979]
# Please provide templates for Node-Red
https://nodered.org/docs/creating-nodes/first-node

It is a Node.js based app, but usually we do not want to debug the whole Node.js or `red.js` itself, only 1 node running inside it.
Different OSs have different path systems storing NR + it's nodes in different places.
VSCode 1.61.1 can not handle that properly:
`/usr/bin/node --preserve-symlinks --experimental-modules ./../../../usr/lib/node_modules/node-red/red.js`

# Why?
- Node-Red is one (if not the most) famous IoT app for automatisation.
- But it is very hard to develop new nodes for it without debugging.
- The current available simple Node.js template can not handle Node-Red path system correctly.
- It does not STOP at any breakpoint.

**Comment by PizzaProgram** [comment]
It would be also helpful if VSCode would check, if `settings.js` file has a line: `debugger` in it, otherwise it won't stop at any breakpoint.
Should notify the user about it if hitting F5.

**Comment by PizzaProgram** [comment]
Here are some trials and setups for iOS + Windows:
https://discourse.nodered.org/t/how-to-proper-debug-custom-node/9308/12

**Comment by PizzaProgram** [comment]
I'm trying to make it work under Raspberry Pi, but it does not bound any break points.
Here is the `launch.json` file including 2 different approaches:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "name": "Run Script: debug MCP3",
            "program": "/usr/lib/node_modules/node-red/red.js",
            "mode": "debug",
            "cwd": "/home/pi/.node-red/",
            "skipFiles": [
                "<node_internals>/**"
            ],
            //"runtimeExecutable": "npm",
            "runtimeArgs": ["--preserve-symlinks", "--experimental-modules"],
            "request": "launch"
            //"command": "npm run debug",
        },
        {
            "type": "node",
            "request": "launch",
            "mode": "debug",
            "name": "Launch via NPM",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "--preserve-symlinks", "--experimental-modules",
                "run-script",
                "inspect"
            ],
            "program": "/usr/lib/node_modules/node-red/red.js",
            "stopOnEntry": true,
//            "cwd": "/home/pi/.node-red/",
            "port": 9229,
            "skipFiles": [
              "<node_internals>/**"
            ]
          }        
    ]
}
```

And in the `package.json`:
```
...
  "scripts": {
    "inspect": "node --inspect /usr/lib/node_modules/node-red/red.js --userDir /home/pi/.node-red/node_modules/mcp-pfc-aio",
    "start": "node node_modules/node-red/red.js -v -u . -s settings.js",
    "debug": "node --nolazy --inspect-brk=9229 node_modules/node-red/red.js -v -u . -s settings.js"
  },
```

**Comment by connor4312** [comment]
I would welcome a PR to the [vscode-recipes repo](https://github.com/microsoft/vscode-recipes) repo.

**Comment by PizzaProgram** [comment]
> I would welcome a PR

Sorry, I can not even find the problem, why it does not stop at the debug points, not to mention writing code directly into VSC.
That's why I've opened this ticket.
