### ISSUE TITLE
Issue Bot too aggressively flagged an issue as invalid?

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#137970]
pls see #137944

**Comment by usernamehw** [comment]
There are multiple issues:

1. https://github.com/microsoft/vscode/issues/117657 Issue reporter automatically creates an issue not letting the user preview it, like it worked before
2. People receiving `invalid` lavel often don't read the issue message to create a new issue and either edit the issue or add a comment.

In that issue bot worked as expected by closing an issue with the content:

```
We have written the needed data into your clipboard because it was too large to send. Please paste.
```

**Comment by JacksonKearl** [comment]
IMO this is working as-designed. The original issue body was indeed the raw text:
```
We have written the needed data into your clipboard because it was too large to send. Please paste.
```
and the bot responded by closing the issue, marking it invalid, and telling the author to open a new issue; the author ignored the bot and instead edited the issue body. 

It'd be theoretically possible to run the bot every time an issue is edited but I don't think the effort or runtime is worth it - the authors have already disregarded the bot's clear instructions so I don't think we're likely to get high quality issue out of them (as the linked issue demonstrates)
