### ISSUE TITLE
Importing from wrong location

### ISSUE THREAD

**Issue by b-novikov-ipersonality** [microsoft/vscode#137985]
<details>
<summary>Code version and OS</summary>

![image](https://user-images.githubusercontent.com/89237497/143687859-93df3521-9716-49a2-8785-24a9c44e02b5.png)
</details>

Steps to Reproduce:

1. Bootstrap a new react application `yarn create react-app`
2. Install chakra-ui `yarn add @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^4`
2. Change `App.js` content to this:
<details>
<summary>App.js content</summary>  

```javascript
import logo from './logo.svg';
import './App.css';
import { ChakraProvider } from '@chakra-ui/react';

function App() {
  return (
    <ChakraProvider>
      <Box>
        <Heading />
        <RadioGroup>

        </RadioGroup>
      </Box>
    </ChakraProvider>
  );
}

export default App;
```
</details>

5. Try to auto import (`ctrl`+`space` or `ctrl` + `.` on linux)   
5. See that corresponding components either **not imported** OR imported from "wrong" package (`import { Box, Heading } from "@chakra-ui/layout"` for example, should be imported from `@chakra-ui/react` package)

Here's a sandbox of correct import behavior: https://codesandbox.io/s/cranky-breeze-ixn86?file=/src/Damn.tsx  

**upd 28.11**: rolled back to VSCode 1.56.2, import works perfectly
**upd 2**: on 1.56.2 import works correctly when there's already import from correct package (`import { Component } from '@chakra-ui/react'`), otherwise it imports from other packages (`import { Component } from '@chakra-ui/layout'` for example)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by b-novikov-ipersonality** [comment]
@mjbvz the issue is gone in the latest version. It was really annoying. Thanks for fixing it
