### ISSUE TITLE
Copy path from navigation bar

### ISSUE THREAD

**Issue by devklick** [microsoft/vscode#137937]
Being able to copy the path (either relative or full) from the navigation bar at the top of the editor would be pretty useful. For example, right-click on the file or folder name and select `Copy Path` or `Copy Relative Path`, much like the options that are available when right-clicking on a file or folder in the explorer pane. 

Here's an extremely professional mockup in paint
![image](https://user-images.githubusercontent.com/58235000/143584147-067da641-2cc1-416c-8ccd-0f2875f05169.png)

An example scenario where I'd find this useful is running commands against against a specific file, for example, running a single test suite from the command line. 
![image](https://user-images.githubusercontent.com/58235000/143584752-b0363553-6512-410b-8db5-ce3c5f4e7692.png)
Rather than having to type the path to the file (or having to expand the side-bar which, I tend to have closed when working with split editor), it would be quite useful just to click the file from the navigation bar and select `Copy Relative Path` and paste it into the terminal.

**Comment by JacksonKearl** [comment]
You can do this with the context menu of the editor's tab:
![image](https://user-images.githubusercontent.com/8586769/144333451-34997b45-2819-4907-8dea-dca0ca6abcee.png)
