### ISSUE TITLE
VSCode caching files from old branch in file explorer, restarting or refreshing doesn't remove them 

### ISSUE THREAD

**Issue by jtkaufman737** [microsoft/vscode#137947]
Nature of issue: if new files/folder are created on a feature branch and committed, and I then switch back to a main branch without those files the folder/files still show up in file explorer. Quitting VSCode completely and restarting with extensions disabled doesn't change this.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2
- OS Version: MacOS Big Sur 11.6

Steps to Reproduce:

1. On feature branch, create new directory/files and commit 
2. Check out main branch without those files 
3. Quit VSCode, and reopen with extensions disabled 
4. Look for dir/files in file explorer 
5. Hit "refresh" file explorer to see if they go away 

Its clear that the editor knows the files aren't there on one level, if any are open in the buffer I will get banner messages "file not found". I don't know why they still show up in the file editor. Refreshing it doesn't remove them, nor does quitting VSCode altogether and restarting. Have ruled out the obvious like that files were actually committed in the wrong branch, basic sanity check stuff

**Comment by JacksonKearl** [comment]
I am not able to reproduce this, does it reproduce consistently for you? Can you include a sample repository or a screen recording?

/gifPlease
