### ISSUE TITLE
Debugging does not run

### ISSUE THREAD

**Issue by HiroyukiFukatsu** [microsoft/vscode#137996]
I was able to debug until yesterday, but when I try to work today it doesn't debug at all. If you select Execute, you will be able to select "Stop Debugging" or "Restart Debugging", but no error message will be displayed. I tried uninstalling, adding extensions, checking the JDK, checking the command prompt, updating the OS, restarting, etc., but it didn't improve.

**Comment by gjsjohnmurray** [comment]
All debugging is implemented by extensions. Your mention of JDK leads me to assume you are coding in Java.

/extJava
