### ISSUE TITLE
Git: jumping to file no longer reveals file

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#137974]
I am used to jumping to the file from the changes view, while selection is preserved. This seems to have regressed in latest insiders:
![recording](https://user-images.githubusercontent.com/900690/143678538-0fb8a423-f188-4fd6-98c1-7eb65b47dafc.gif)

**Comment by lszomoru** [comment]
I am not aware of any code changes in this area. @lramos15 anything that comes to mind?

**Comment by lramos15** [comment]
@bpasero Is this similar to #135692. @lszomoru there was a recent change in this area to fix #135422. That commit is https://github.com/microsoft/vscode/commit/514ad0acf04fba53550d0351df9e19928045bc5d

**Comment by bpasero** [comment]
Yeah sounds similar.

**Comment by lramos15** [comment]
![recording](https://user-images.githubusercontent.com/4544166/144077989-8a404121-14ff-4567-a1b2-1e1c9639d4dd.gif)
Having trouble reproducing. Does it happen to every file for you?

**Comment by bpasero** [comment]
🤷

**Comment by lramos15** [comment]
If you are able to reproduce often I would be happy to debug it with you but I've tried a couple of times with different files and workspaces with no luck.

**Comment by bpasero** [comment]
@lramos15 this somehow seems to be related to how many changes are in a file. Steps to reproduce:
* replace the contents of `test/automation/src/application.ts` with the contents below
* diff it
* select `checkWindowReady`
* select "Go to file"
* => 🐛  location is not revealed

[application.ts.zip](https://github.com/microsoft/vscode/files/7635307/application.ts.zip)
![recording (1)](https://user-images.githubusercontent.com/900690/144267161-bc3668cc-95db-41d2-83c2-0ef84ab26149.gif)

Maybe this is actually an editor issue? @hediet fyi

**Comment by lramos15** [comment]
Thanks for the repo.

Here's what I found when debugging:

We do select the range correctly but `editor.visibleRanges` returns the wrong value in the case of the diff. This causes us to scroll the document to the wrong position. If you scroll down you will see that the correct selection is preserved. This sounds like a core bug though since that's a value returned by the API

**Comment by hediet** [comment]
Is this a regression? `editor.visibleRanges` definitely has some problems, though I don't know if they apply here.

**Comment by bpasero** [comment]
Yeah regression!

**Comment by lramos15** [comment]
It was actually my regression. Darn you references changing 🤦
