### ISSUE TITLE
source.organizeImports get error in react file

### ISSUE THREAD

**Issue by YangChen00** [microsoft/vscode#137930]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.3 (Universal)
- OS Version: Mac OS Monterey 12.0.1

Steps to Reproduce:

1.set this in vscode settings.json
```js
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.codeActionsOnSave": ["source.organizeImports", "source.fixAll"],
```
2. save index.tsx file like this
```jsx
import '@/l10n/extension';
import { locale } from '@/locales';
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter as Router, useHistory } from 'react-router-dom';

const App = () => {
  return (
    <div>
      123
    </div>
  );
};

ReactDOM.render(
  <React.StrictMode>
      <Router>
        <App />
      </Router>
  </React.StrictMode>,
  document.getElementById('root'),
);
```
3. you got this
![image](https://user-images.githubusercontent.com/94821645/143566167-111a65a6-82db-4dba-b660-7ef52d59d019.png)

the seq is wrong

**Comment by mjbvz** [comment]
This is caused by eslint. VS Code's built-in organize import function doesn't know anything about your eslint rules
