### ISSUE TITLE
A shortcut to disable/enable all installed extensions (Your bug issues request as much-- but it's very tedious with 50+ extensions installed)

### ISSUE THREAD

**Issue by pmeaney** [microsoft/vscode#137957]
In the issue reports here in VS Code repo, I am expected to disable all extensions before making an issue report.  Well, I have 57 extensions.  And what I've noticed is that in the Extensions > Installed section, there's no "disable/enable all" toggle.  How about we add that, so when devs send issue reports to the VS Code, we don't have to go through all 57-bazillion extensions to disable them all, in order to trouble shoot a bug for ya. 

So, please add a Disable All/Enable all toggle feature to the "Installed Extensions" section.

Thanks!

**Comment by gjsjohnmurray** [comment]
At least two options already exist as commands you run from Command Palette:

1. `Help: Start Extension Bisect` - see https://code.visualstudio.com/blogs/2021/02/16/extension-bisect
2. `Developer: Reload With Extensions Disabled`

I recommend the first one, which is also mentioned in the New Bug Report template along with a CLI argument to launch with all extensions disabled:

![image](https://user-images.githubusercontent.com/6726799/143661396-4b469d40-06af-4da6-adcf-344727c68969.png)

**Comment by pmeaney** [comment]
Fantastic, thank you!

**Comment by egamma** [comment]
@gjsjohnmurray great answer, thank you.
