### ISSUE TITLE
Authentication API: `onDidChangeSessions` event provides insufficient information to handle user-initiated sign-out

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#137931]
Issue Type: <b>Feature Request</b>

At the moment an extension which uses an AuthenticationProvider via the [`vscode.authentication` API](https://code.visualstudio.com/api/references/vscode-api#authentication) can be notified when a user signs out off the Accounts icon's menu, but cannot discover which session(s) this action affected. Consequently it cannot perform cleanup such as creating session cookies maintained by a REST interface.

In particular, when the AP supports multiple accounts it may not be viable as a workaround to treat all occurrences of that event for the relevant AP as signalling a sign-out.

Interestingly, the AP itself can use its `onDidChangeSessions` event to get [detailed notification](https://code.visualstudio.com/api/references/vscode-api#AuthenticationProviderAuthenticationSessionsChangeEvent) of adds, changes and deletes of its sessions. This seems to  be partly intended for making it able to sync session changes between multiple VS Code windows.

VS Code version: Code - Insiders 1.63.0-insider (1e473b624f088fc05269891170a8ffa1c84a35a6, 2021-11-25T09:04:34.615Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by TylerLeonhardt** [comment]
I think the model that we were going for initially is that you would receive an event that "sessions changed" and if you cared about that provider, you would get rid of the session you have cached and re-request your session.

Now that we have `silent: true` this is even nicer and won't annoy the user.

Does that make sense?

**Comment by TylerLeonhardt** [comment]
Gonna close this but feel free to respond.

**Comment by gjsjohnmurray** [comment]
@TylerLeonhardt sorry for not responding sooner.

So, silently re-request each of my cached sessions, then discard any for which the silent re-request fails (because the user has logged this one out)?

**Comment by TylerLeonhardt** [comment]
Yes that's what I'm thinking. How many sessions are you holding on to? For most examples I've seen that number is like....... 2 or 3 tops.
