### ISSUE TITLE
Disable Unicode Highlighting By Default For Julia (and other languages)

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#137924]
Is there a way to turn this off by default depending on the source language. In julia source files, unicode variable names are very common and they now all have ugly red boxes around them by default:

![Screenshot from 2021-11-25 22-50-13](https://user-images.githubusercontent.com/1291671/143524383-5c645188-54d5-401f-8bbf-da47daf0bc37.png)

I understand that it's possible to turn this off manually, but this makes the first-use experience much worse for users opening julia source files.

_Originally posted by @Keno in https://github.com/microsoft/vscode/issues/137508#issuecomment-979677873_

**Comment by hediet** [comment]
We anticipated that this is going to be a problem for some languages (including Lean - FYI @gebner). Also, no worries, we won't enable this feature by default for stable unless we find a solution we are all happy with.

We implemented this feature to protect against recent [homoglyph](https://www.trojansource.codes/) and [invisible character](https://certitude.consulting/blog/en/invisible-backdoor/) attacks.

The unicode specification recommends checking for "confusable" characters to detect possible spoofing attempts in source code.
Unfortunately, the unicode specification defines `α` and `a` to be [confusable](http://www.unicode.org/Public/security/8.0.0/confusables.txt).
They define many more such confusable character pairs and it is difficult for us to decide which of those pairs are reasonable and which not, especially as this also depends on regional culture.

I think it is reasonable to have a mechanism for extensions to exclude some ambiguous characters from being highlighted for certain languages (such as Julia or Lean).
As long as these characters are commonly used in such a language and users are already aware that `α` is distinct from `a`, I think there are no security implications of allowing extensions to exclude such characters.

What are your thoughts on homoglyph attacks in languages that make extensive use of non-ascii characters?

**Comment by gebner** [comment]
Thanks for pinging me!

> What are your thoughts on homoglyph attacks in languages that make extensive use of non-ascii characters?

At least in Lean, we make heavy use of homoglyphs to disambiguate concepts (such as → for function types and ⟶  for morphisms in category theory, or | in pattern matches and ∣ for divisibility, or Σ for dependent products and ∑ for summation, or ... the list goes on).

> We implemented this feature to protect against recent homoglyph and invisible character attacks.

For Lean, it doesn't make sense to highlight homoglyphs.  But I think it would be useful to highlight invisible characters (which nobody uses, I hope).

**Comment by hediet** [comment]
> For Lean, it doesn't make sense to highlight homoglyphs.

As of today, extensions can already contribute default settings that only apply for specific languages:

```json5
"contributes": {
    ...
    "configurationDefaults": {
        "[lean]": {
            "editor.unicodeHighlight.ambiguousCharacters": false
        }
    },
    ...
}
```

Be aware that this also disables highlighting of confusables that look exactly the same, such as the latin `a` and the cyrillic `а`!

**Comment by Keno** [comment]
Julia has a canonical list of unicode characters that are common in julia source code: https://github.com/JuliaLang/julia/blob/master/stdlib/REPL/src/latex_symbols.jl. These should not be error highlighted. Our general approach to homoglyphs is to either complain to the font author if we think they are actually different (so should look visually different) or otherwise, we might actually normalize them on parse: https://github.com/JuliaLang/julia/blob/master/src/flisp/julia_charmap.h. Where we normalize, it certainly makes sense to highlight the non-canonical variant in the source and offer an automatic replacement by the canonical variant.

**Comment by Keno** [comment]
> Where we normalize, it certainly makes sense to highlight the non-canonical variant in the source and offer an automatic replacement by the canonical variant.

Or maybe just canonicalize on save or entry. The issue here is that sometimes users have keyboards that natively enter the non-canonical characters, so it would be annoying for them to get an ugly highlight.

**Comment by gebner** [comment]
> Julia has a canonical list of unicode characters that are common in julia source code: https://github.com/JuliaLang/julia/blob/master/stdlib/REPL/src/latex_symbols.jl. These should not be error highlighted.

We have a similar list for Lean in the vscode extension: https://github.com/leanprover/vscode-lean4/blob/master/vscode-lean4/src/abbreviation/abbreviations.json

I think it would be reasonable to highlight ambiguous characters that you cannot input this way.  Users can also add custom abbreviations in the settings, these should not be highlighted either.

**Comment by hediet** [comment]
We have not decided yet on a mechanism on how language extensions can exclude certain characters from being highlighted (we would like to avoid language extensions listing thousands of characters).

For now, languages that make extensive use of ambiguous characters (in particular in their standard library) should just deactivate the feature (as described [here](https://github.com/microsoft/vscode/issues/137924#issuecomment-979855421)).

**Comment by hediet** [comment]
Extensions can do this:

```json
"contributes": {
    ...
    "configurationDefaults": {
        "[lean]": {
            "editor.unicodeHighlight.allowedCharacters": {
                "α": true,
                ...
            },
        }
    },
    ...
}    
```

However, we didn't design that property to exclude thousands of unicode characters (which could have UX/performance issues).

If there are too many characters that would need to be allowed, we recommend to turn off highlighting ambigious characters, like this:
```json
"contributes": {
    ...
    "configurationDefaults": {
        "[lean]": {
            "editor.unicodeHighlight.ambiguousCharacters": false
        }
    },
    ...
}
```
