### ISSUE TITLE
Read first line of file and use as filename when saving

### ISSUE THREAD

**Issue by rui-ktei** [Microsoft/vscode#1379]
If you open a new tab in VS Code and type, say, `test.js`, then you press CTRL + S and dialog pops up:
<img width="735" alt="capture" src="https://cloud.githubusercontent.com/assets/12144265/11841720/4c76fffe-a453-11e5-8c07-a80fcb48a8d5.PNG">

Notice that it's not aware of the `test.js` we just typed. In sublime, if you do this, it will be smart enough to pick up *.js as file type and use `test` as the file name, which is quite handy. I'm not saying you should 100% copycat sublime however in terms of saving a new file, sublime gives a much better developer experience.

**Comment by dbaeumer** [comment]
@bpasero fyi.

**Comment by bpasero** [comment]
I think sublime will just name your untitled file whatever you put into the first line of the file. Not sure I like that in all cases.

**Comment by rui-infotrack** [comment]
@bpasero True, I totally agree with you and that's why I said "not saying to copycat sublime 100%", but I still think currently there is no easy to to save a file in a convenient way. See, the first file type is *.txt but most developers won't write .txt files too often.

**Comment by bpasero** [comment]
@rui-infotrack this actually changes in our next release, i have taken out the dropdown with file extensions because it caused other issues. However, if you change the language mode of an untitled file, I will propose the correct extension for this mode so that you dont have to type it again.

**Comment by rui-infotrack** [comment]
@bpasero thank you for taking that into consideration

**Comment by bgse** [comment]
@rui-infotrack If using keyboard instead of file navigation dialogs works for you, maybe open an issue here and describe your use-case, sounds like it would fit in:

https://github.com/bgse/vsc-addfileextension

**Comment by DerTolleEmil** [comment]
Will this also fix the editor ignoring quotes and adding another extension? Today I was working on a new batch file and habit always makes put the filename in quotes when saving, ie: `"convert.bat"`. However, the file will still get saved as convert.bat.txt which is a bit annoying; And also completely different to all other save dialogs I know (working with the Windows version).

**Comment by bpasero** [comment]
@DerTolleEmil yes I think so, you can switch to the insiders channel to try it out: https://code.visualstudio.com/Docs/supporting/FAQ#_why-does-visual-studio-code-have-a-different-license-than-the-vscode-github-repository

**Comment by egamma** [comment]
@DerTolleEmil the link is off by one, pls see: https://code.visualstudio.com/Docs/supporting/FAQ#_how-can-i-test-prerelease-versions-of-vs-code

**Comment by bpasero** [comment]
Ah sorry :)

**Comment by DerTolleEmil** [comment]
No worries :) It's working as expected in 0.10.4, thank you!

**Comment by bpasero** [comment]
:+1:

**Comment by mals14** [comment]
This would be a good feature for many a text / markdown files created in VS Code. Is it possible to achieve via any available extension? I could not find one... 

Thank you!

**Comment by sbusch** [comment]
In addition, Sublime updates the name of the unsaved buffer (= tab title) is updated while editing the first line.

**Comment by isidorn** [comment]
I see the user saying this works so no clue why is this still open -> closing

**Comment by sbusch** [comment]
IMO this is primarily a feature-request which is still valid and shouldn't be closed.
