### ISSUE TITLE
Recent unicode character highlighting change has broken output window

### ISSUE THREAD

**Issue by smcenlly** [microsoft/vscode#137907]
Version: 1.63.0-insider (Universal)
Commit: 1e473b624f088fc05269891170a8ffa1c84a35a6
Date: 2021-11-25T07:59:08.754Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0

Steps to Reproduce:

1. Install Quokka Extension
2. Start Quokka

Output window appears as shown below:

![image](https://user-images.githubusercontent.com/2074089/143520658-ca0071fe-7dac-4642-895f-d0a2437a39be.png)

---

To achieve code highlighting and maintain text positions, Quokka uses some invisible characters in it's language grammar for code highlighting.

Recent changes (November 19) by @hediet to implement highlight of unicode characters https://github.com/microsoft/vscode/pull/137508 has broken this in our extensions. 

Ideally I think that the output window's "editor instance", and perhaps all read-only editor instances should be excluded from such highlighting to limit unnecessary processing.

**Comment by ArtemGovorov** [comment]
We get the same issue for our Wallaby.js output and Test Story read-only view (powered by `vscode.workspace.registerTextDocumentContentProvider`) (both read-only):

<img width="1214" alt="Screen Shot 2021-11-29 at 8 45 45 pm" src="https://user-images.githubusercontent.com/979966/143854503-cffc1361-6b7f-4d8c-8b71-6c74e6bef1e8.png">

**Comment by hediet** [comment]
> vscode.workspace.registerTextDocumentContentProvider

Afaik Wallaby already registers a custom language for the Test Story view. I think the way to fix the highlighting in the editor would be to disable all `editor.unicodeHighlight.*` features for that specific languages. Wallaby could contribute a default value like this:

```
"configurationDefaults": {
    "[wallaby-test-story-lang]": {
        "editor.unicodeHighlight.ambiguousCharacters": false,
        // ...
    }
}
```

I would like to stay away from completely disabling unicode highlighting by default for read only text editors, as you could happen to review code from a readonly file system provider.

The feature should be disabled for the output pane though.

**Comment by hediet** [comment]
Please let me know of remaining issues not covered by the fix.

The fix just disables unicode highlighting in the output pane.

**Comment by smcenlly** [comment]
Thanks, it's working for us now, and we have applied the configuration defaults for our text document content provider (which is also working).

**Comment by smcenlly** [comment]
Really appreciate the fast turnaround on this! 🥳

**Comment by IanMatthewHuff** [comment]
LGTM using the Quokka demo file:
![image](https://user-images.githubusercontent.com/812783/144497026-4933c1f6-1f06-4c76-b307-78c53de30f9c.png)

Verified
