### ISSUE TITLE
Find in Files does not work if the workspace project names are different to the one in the file system

### ISSUE THREAD

**Issue by juergenbosch** [microsoft/vscode#137914]
Issue Type: <b>Bug</b>

I try to find only things in one project folder therefore i use the "Find in Folder..." function on the context menu of a project folder.

I have multiple projects in my workspace but the name of the project are different to the one in the filesystem.

vs code workspace example:

```
{
  "folders": [
    {
      "path": "ehs.fnd.lib.reuse.pcs1",
      "name": "FND [F3209]: PSS Reuse Library",
      "position": 0
    },
    {
      "path": "ehs.dg.reuselibs1",
      "name": "DG: Reuse Component [F3570]",
      "position": 10
    },
    {
      "path": "ehs.dg.unpackagedproduct.worklists1",
      "name": "DG: Classify UP - Worklist [F3643]",
      "position": 20
    },...
```

On search the following filter is used:
files to include: ./DG: Reuse Component [F3570]

The search result does not search only in the selected project!!!

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (14.93GB free)|
|Process Argv|C:\\SAPDevelop\\dev\\git\\pss\\dev\\pss-3-dg.code-workspace --crash-reporter-id edee1393-7cdb-4f57-aca6-37facf09e432|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-coverage-highlighter|bra|1.0.3
turbo-console-log|Cha|2.1.7
regex|chr|0.4.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
gitlens-insiders|eam|2021.10.2305
vscode-npm-script|eg2|0.3.23
vscode-pull-request-github|Git|0.32.0
vscode-commandbar|gsp|0.3.1
compareit|in4|0.0.2
tablegenerator|Jay|1.0.4
jbockle-format-files|jbo|3.4.0
vscode-abap|lar|0.5.6
git-graph|mhu|1.30.0
vscode-docker|ms-|1.18.0
remote-containers|ms-|0.202.5
remote-wsl|ms-|0.58.5
debugger-for-chrome|msj|4.13.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.1
vscode-yaml|red|1.2.1
yeoman-ui|SAP|1.7.3
xml-toolkit|SAP|1.1.0
sap-ux-annotation-modeler-extension|SAP|1.4.3
sap-ux-application-modeler-extension|SAP|1.4.3
sap-ux-fiori-tools-extension-pack|SAP|1.4.3
sap-ux-help-extension|SAP|1.4.3
sap-ux-service-modeler-extension|SAP|1.4.3
vscode-sql-beautify|sen|0.0.4
open-in-browser|tec|2.0.0
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by gjsjohnmurray** [comment]
/confirm

Problem seems to be here:

https://github.com/microsoft/vscode/blob/eca6f7ed24af32f3759cf3d4743291f7a503bbc9/src/vs/workbench/contrib/search/common/queryBuilder.ts#L596-L611

I will prepare a PR

**Comment by roblourens** [comment]
Thanks, but that isn't it, it uses the custom workspace folder name by design. It has something to do with the `[]` in the name, this works without those.

**Comment by rabbagliettiandrea** [comment]
+1

**Comment by juergenbosch** [comment]
Without the brackets in the name it worked for me.

**Comment by gjsjohnmurray** [comment]
@roblourens you may still want to reopen this and fix it.

**Comment by RB-Lab** [comment]
This, indeed, most likely caused by square brackets. Because I have a project with SvelteKit, and in has folder structure where you have [dynamic parameters](https://kit.svelte.dev/docs/routing#pages) set as e.g. `/path/segment/[param]/page`. And search can't find anything in these folders. 

**VSCode version:** 1.69.1

**Comment by benringrose** [comment]
I can confirm that this is still an issue when searching for files to include if I use ./resources/[jobs]/ with square brackets it doesnt work, however, going from another post I have found if I change it to ./resources/[[]jobs[]]/ it then searches within the folder

**VSCode version:** 1.72.2

**Comment by roblourens** [comment]
I think this is the same as https://github.com/microsoft/vscode/issues/82415, which has an open PR
