### ISSUE TITLE
undo doesn't trigger onWillRenameFiles event

### ISSUE THREAD

**Issue by saltylassi** [microsoft/vscode#137922]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.3
- OS Version: Windows 10, 64bit

Steps to Reproduce:

1. make a simple extension

```
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
  vscode.workspace.onDidRenameFiles((event) => {
    console.log('rename');
    vscode.window.showInformationMessage('rename');
  });
  vscode.workspace.onWillRenameFiles((event) => {
    console.log('willRename');
    vscode.window.showInformationMessage('willRename');
  });
}
```

2. when extension activate, rename file or move file

3. undo(in my case, press ctrl+z)

4. onWillRenameFiles event missing, only onDidRenameFiles is triggered

**Images here about this report**

case 1. rename file

![image](https://user-images.githubusercontent.com/77769802/143546432-867892ab-15b1-47b0-a742-a5609500c13f.png)

onWillRenameFiles triggered.

case 2. undo file

![image](https://user-images.githubusercontent.com/77769802/143546689-6c5afcba-ce80-49e6-a191-8ce2d8a8414b.png)

onWillRenameFiles event missing, only onDidRenameFiles triggered.

**Comment by egamma** [comment]
// CC @isidorn for additional insights on the current implementation.

**Comment by isidorn** [comment]
Rename is implemented [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/files/browser/fileActions.ts#L881)
I am not sure how the `bulkEditService` converts the ResourceFileEdit into `renameFile` events. @jrieken might know more
Though let's first see if @JacksonKearl can repro and if he needs help.

**Comment by jrieken** [comment]
We have done this on purpose, undo events are [ignore](https://github.com/microsoft/vscode/blob/19dca64e3882a0a6db43580750bd76bcf7c45324/src/vs/workbench/api/browser/mainThreadFileSystemEventService.ts#L79). The reasoning is that undo is a strong signal that the user wants to restore the previous state and doesn't want extension participation. 

@saltylassi What's your use-case for participation while undo?

**Comment by saltylassi** [comment]
> We have done this on purpose, undo events are [ignored](https://github.com/microsoft/vscode/blob/19dca64e3882a0a6db43580750bd76bcf7c45324/src/vs/workbench/api/browser/mainThreadFileSystemEventService.ts#L79). The reasoning is that undo is a strong signal that the user wants to restore the previous state and doesn't want extension participation.
> 
> @saltylassi What's your use-case for participation while undo?


thanks for reply :)

in my case, i've to know deleted thing is file or folder cuz logic is different, so i use isDirectory method(in nodeJS path module)

but after delete target, file doesn't exist, and i can't figure out target is a file or folder(with file doesn't exist error).


if this situation is by design, there is any proper apy in my usecase?

**Comment by saltylassi** [comment]
@jrieken 

unfortunately, maybe i can't use fileSystemWatcher cuz my extension is made for vscode and theia.

i reported something on theia's issue, and they fixed that yesterday. that is not validated well, i can't use. sry

**Comment by jrieken** [comment]
> in my case, i've to know deleted thing is file or folder cuz logic is different, so i use isDirectory method(in nodeJS path module)

You are saying that a file has been created and that undo is deleting it so you don't get an event for that?

**Comment by saltylassi** [comment]
> > in my case, i've to know deleted thing is file or folder cuz logic is different, so i use isDirectory method(in nodeJS path module)
> 
> You are saying that a file has been created, undo is deleting it, and don't get an event for that?


oh... my english is mess, sry about that. i'm not good at wrtie something with english. :) 


no. when i press ctrl+z, file has been changed, and i've to know that file's old Uri before file has gone.

**Comment by jrieken** [comment]
Ok, I believe I start to understand. While rename happens you check if the file being renamed is a directory or not. I am still unsure if you need further participate in the rename, like do you also [`waitUntil(...)`](https://github.com/microsoft/vscode/blob/297c52bd80d8dbd18c1bf1900fee25aa8b7a5044/src/vscode-dts/vscode.d.ts#L10632) with an edit or not? 

Iff not, why don't you use [`onDidRenameFiles`](https://github.com/microsoft/vscode/blob/297c52bd80d8dbd18c1bf1900fee25aa8b7a5044/src/vscode-dts/vscode.d.ts#L11162)? Sure, the `oldUri` is gone but the `newUri` will have the same file type, e.g renaming a directory doesn't turn it into a file

**Comment by saltylassi** [comment]
@jrieken 

ah, this is my mistake i missed i can use new Uri's type. if oldUri type is same as new Uri, i can do this

:) thanks for my mess english.
