### ISSUE TITLE
Launch VS Code from Address Bar in Windows Explorer

### ISSUE THREAD

**Issue by nahomebssa** [microsoft/vscode#137904]
To enhance developer productivity, VS Code could support launching from the address bar in Windows Explorer. This includes passing in arguments as in the cli.

https://user-images.githubusercontent.com/45636260/143507597-af1b39f7-cd69-4438-9944-ebf008d8b3c8.mp4

**Comment by joaomoreno** [comment]
@sbatten Is this standard?

@nahomebssa Can you provide examples of other applications which support this, including with arguments?

**Comment by yume-chan** [comment]
The address bar is basically a run prompt, so `code.cmd .` already works. But since it's not an `exe` the `.cmd` suffix is required.

I remember Windows Terminal recommended running `wt -d .` from address bar somewhere.
