### ISSUE TITLE
Output copied from terminal shouldn't have extra 'end of line' char

### ISSUE THREAD

**Issue by greams** [Microsoft/vscode#13797]
- VSCode Version: 1.6.1
- OS Version: Windows 10 v1607 (build 14393.321) / OS X 10.11.6

Steps to Reproduce:

1. Get long single-line output that will take few lines to display
2. Copied result will have extra 'end of line' char for each line from terminal

How it looks now:
![demo-bad](https://cloud.githubusercontent.com/assets/4791989/19409412/e2a3852a-92db-11e6-9c40-17fe327a9440.gif)

How it should be:
![demo-good](https://cloud.githubusercontent.com/assets/4791989/19409425/1662c3b2-92dc-11e6-831f-6f104bc67ce9.gif)

**Comment by Tyriar** [comment]
This is an upstream issue and is a design decision that needs to be made over there https://github.com/sourcelair/xterm.js/issues/103
