### ISSUE TITLE
Rename `resolveShellEnv` to `getResolvedShellEnv`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#137923]
When I investigated for #137900, I stumbled across https://github.com/microsoft/vscode/blob/main/src/vs/platform/request/node/requestService.ts#L70.

I worried that `resolveShellEnv` would resolve the env on every request.  But in fact `resolveShellEnv` uses a cached promise so all good.

To reflect that I suggest to rename `resolveShellEnv` to `getResolvedShellEnv`

**Comment by bpasero** [comment]
I renamed it. Note that if the promise is rejected, request service and pty service will log an error to the log file on each time the method is used.

//cc @chrmarti @Tyriar
