### ISSUE TITLE
"for" don't work

### ISSUE THREAD

**Issue by sdfcx** [microsoft/vscode#137983]
Issue Type: <b>Performance Issue</b>

When I try to ejecutate a program, the program wont do the "for", it just jump through the for. This is the program:

#include<stdio.h>
#define MAX 5
int matriz (int n, int mat[][MAX]){
    int i=0, j=1, aux1=0, aux2=0;
    for(i;i>n;i++){
        for(j;j>n;j++){
            if(mat[i][j]>aux1)
                aux1=mat[i][j];
            else if(mat[i][j]==aux1)
                aux1=aux1+mat[i][j];
        }
        j++;
    }
    i=n;
    j=n-1;
    for(i;i<0;i--){
        for(j;j<0;j--){
            if(mat[i][j]>aux2)
                aux2=mat[i][j];
            else if(mat[i][j]==aux2)
                aux2=aux2+mat[i][j];
        }
        j--;
    }
    return aux1+aux2;
}

int main(){
    int mat[5][5],n=5,sumatotal=0;
    mat[0][0]=1; 
    mat[0][1]=2;
    mat[0][2]=2;
    mat[0][3]=2;
    mat[0][4]=2;
    mat[1][0]=3;
    mat[1][1]=4;
    mat[1][2]=4;
    mat[1][3]=4;
    mat[1][4]=4; 
    mat[2][0]=5;
    mat[2][1]=6;
    mat[2][2]=6;
    mat[2][3]=6;
    mat[2][4]=6; 
    mat[3][0]=7; 
    mat[3][1]=8;
    mat[3][2]=8;
    mat[3][3]=8;
    mat[3][4]=8; 
    mat[4][0]=9; 
    mat[4][1]=10;
    mat[4][2]=10;
    mat[4][3]=10;
    mat[4][4]=10;
    sumatotal=matriz(n,mat);
    printf("%d",sumatotal);
}

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (3.58GB free)|
|Process Argv|--crash-reporter-id 532e5c66-1b28-454f-9816-2ab83a8d8980|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    87	 11428	code main
    0	   169	  2352	   window (entrevistatecnica.c - pp - Visual Studio Code)
    0	    98	  9876	     extensionHost
    0	    77	 13968	     watcherServiceNSFW
    0	    42	  9012	   utility
    0	    92	  9956	   shared-process
    0	    79	 14176	     ptyHost
    0	     7	  2176	       console-window-host (Windows internal process)
    0	    70	  8868	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	   108	 11400	   gpu-process
    0	    26	 12052	   crashpad-handler
    0	    83	 13456	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (entrevistatecnica.c - pp - Visual Studio Code)
|    Folder (pp): 257 files
|      File types: c(132) exe(112) json(3)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: cppdbg;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593cf:30376535
vssld246:30401890
pythonvs932:30404739
vscexrecpromptc:30404946
vscop804cf:30404767
vscop940:30404999

```

</details>

**Comment by egamma** [comment]
This looks like an issue with your C program. There is nothing VS Code can do to address this problem.

**Comment by sdfcx** [comment]
yeah it was something I did wrong in the program, thanks!
