### ISSUE TITLE
just updated to macos Monterey and vscode is not working when i run the code and it give me with "The terminal process failed to launch: Path to shell executable "/bin/shell" does not exist."

### ISSUE THREAD

**Issue by realammar** [microsoft/vscode#137995]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.3 (Universal)
- OS Version: 12.0.1

Steps to Reproduce:

1. 
2.

**Comment by timmermansjoy** [comment]
you should look at your settings for what terminal you are using with viscose to see if there is something not right. it prob cant find zsh or bash so it cant execute the command in the terminal. you probably cant open the terminal in vsCode?

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
