### ISSUE TITLE
Terminal uses builtin python instead of conda;s python

### ISSUE THREAD

**Issue by Okroshiashvili** [microsoft/vscode#137951]
Issue Type: <b>Bug</b>

I installed miniconda and vscode. Then created virtual environment in conda and when opened Vscode it is able to see where conda and conda environments are located. When I start Vscode terminal it automatically activate conda environment. However, when I type "python" in terminal it shows that termianl uses builtin 2.7 version of Python insted of python from conda environment.

VS Code version: Code 1.62.3 (Universal) (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id e624df91-0d34-47c5-b59a-e76e0ce4b343|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
LinkCheckMD|bla|0.3.1
path-intellisense|chr|2.5.0
vscode-database-client2|cwe|4.2.3
vscode-markdownlint|Dav|0.45.0
githistory|don|0.6.19
vscode-jupytext|don|0.1.0
gitlens|eam|11.7.0
copilot|Git|1.7.3952
remotehub|Git|0.18.0
vscode-pull-request-github|Git|0.32.0
mdmath|goe|2.7.4
gc-excelviewer|Gra|3.0.44
todo-tree|Gru|0.0.214
vscode-drawio|hed|1.6.3
latex-workshop|Jam|8.22.0
vscode-random|jre|1.11.0
restructuredtext|lex|167.0.0
markdown-shortcuts|mdi|0.12.0
git-graph|mhu|1.30.0
mongodb-vscode|mon|0.6.14
vscode-docker|ms-|1.18.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
live-server|ms-|0.2.9
vscode-json-editor|nic|0.3.0
autodocstring|njp|0.5.4
material-icon-theme|PKi|4.11.0
vscode-thunder-client|ran|1.9.1
vscode-yaml|red|1.2.1
vscode-fileutils|sle|3.4.5
code-spell-checker|str|2.0.13
luna-paint|Tyr|0.11.0
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.7.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30402085
vsaa593cf:30376535
vssld246:30401890
vscop804cf:30404767
vscop453:30404998

```

</details>

**Comment by Okroshiashvili** [comment]
I found the fix for this issue. Just I was trying some random checking/unchecking stuffs and when I unchecked the setting `Terminal Integrated Inherit Env` then Vscode terminal started to use Python from conda environment rather then builtin Python.

**Comment by meganrogge** [comment]
@karthiknadig is this a known/tracked issue?

**Comment by karthiknadig** [comment]
Yes, https://github.com/microsoft/vscode-python/issues/14464 is the tracking generic issue for this issue. We are re-evaluating how we do terminal support for activated environments, and this is part of addressing that.
