### ISSUE TITLE
refactor feature like webstorm

### ISSUE THREAD

**Issue by stekovinbranturry** [microsoft/vscode#137915]
![image](https://user-images.githubusercontent.com/33021960/143533257-29f3d1d8-0608-41e8-914f-31c5b33ea0f3.png)

Webstorm's refator feature is pretty awesome. It really helps a lot when I refactor project structure, such as move files, rename files. Webstorm will auto change all the relative paths. But the refactor feature of VS Code is not that powerful. Really hope it can do those things webstorm can do. Thanks!

**Comment by gjsjohnmurray** [comment]
@stekovinbranturry as a Webstorm user you are probably well placed to do a detailed gap analysis comparing its refactoring features with those of VS Code.

**Comment by mjbvz** [comment]
Please open specific feature requests for individual features
