### ISSUE TITLE
Sync Extensions

### ISSUE THREAD

**Issue by davidahern** [microsoft/vscode#137986]
Issue Type: <b>Feature Request</b>

hi, please sync VS Code Extensions either through Windows Store or other method

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
How does your request differ from the existing Settings Sync feature?

https://code.visualstudio.com/docs/editor/settings-sync

**Comment by davidahern** [comment]
Wasn't aware of this... I did Google extension sync and found third party extensions for this... So just assumed it didn't exist natively... Will close the ticket
