### ISSUE TITLE
Workspace-specific settings stored in user settings

### ISSUE THREAD

**Issue by devklick** [microsoft/vscode#137935]
Settings that are specific to a workspace but are stored in user settings. 

I frequently have multiple VSCode windows open, and I like to make slight customisations to each one so it's easy to differentiate them from. I tend to do this in the workspace settings (extensions such as [Window Colors](https://marketplace.visualstudio.com/items?itemName=stuart.unique-window-colors) are great for this).

However, my team believes that workspace settings should be stored in source control, but disagree with me customising the editor for different projects. I would generally just edit the workspace settings.json to apply some customisations, such as change the tile bar color, but they do not want this, so I cannot use the workspace settings to customise the editor. 

I would find it really helpful if there was the option to store workspace configurations in the user settings so they were specific to only me and do not need to be shared with others working on the code base. This would allow me to configure my editor per-workspace without my team being affected by my sometimes-questionable preferences).

**Comment by gjsjohnmurray** [comment]
You can already do this.

1. Open the folder XYZ (which I assume is what you are referring to as your workspace).
2. Use "Save Workspace As..." from the File menu to create a locally-stored XYZ.code-workspace file which is your own personal property.
3. Now in the Settings Editor there will be three subtabs, "USER", "Workspace" and "XYZ Folder".
4. Use the "Workspace" tab to define settings which get stored in JSON in your XYZ.code-workspace file and thus are personal ones.

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/40233
