### ISSUE TITLE
when input chinese the input frame not init at correct place

### ISSUE THREAD

**Issue by baofengyv** [Microsoft/vscode#13793]
- VSCode Version: 1.5.3 (1.5.3)
- OS Version:10.11.6

Steps to Reproduce:
1. type anyone key.
2. ![2016-10-15 12 53 33](https://cloud.githubusercontent.com/assets/5669938/19407510/ec9dc356-92d6-11e6-8745-a12446cfa774.png)

**Comment by alexandrudima** [comment]
Let's track in #356
