### ISSUE TITLE
Вопрос о xamarin 

### ISSUE THREAD

**Issue by LevCoding** [microsoft/vscode#137982]
Issue Type: <b>Feature Request</b>

**Здраствуйте.** Можно ли разрабатывать в _Visual studio code_ приложения на Xamarin**?**

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

**Comment by sryze** [comment]
Зачем, если есть просто Visual Studio?
