### ISSUE TITLE
Display all definitions/implementations and references in a multi-root workspace.

### ISSUE THREAD

**Issue by LangLangBart** [microsoft/vscode#137993]
My **javascript** multi-root project has two folders, folder B uses functions defined in folder A. Using definitions/implementations and references does not return results when looking it up.

The [documentation](https://github.com/microsoft/vscode-docs/blob/ca316dd114ba5ce8a60893b727fb4823bf21f5b8/docs/editor/workspaces.md) about multi-root workspaces doesn't answer how to do that. So I assumed it is a **missing feature**.

![Screenshot 2021-11-26 at 23 19 38](https://user-images.githubusercontent.com/92653266/143663139-b879db4c-233d-4d2d-b375-43d94efb0c83.jpg)

Related issues:
- https://github.com/microsoft/vscode-cpptools/issues/1230

PS: Very good code editor.

**Comment by mjbvz** [comment]
Do you have jsconfig for each project? Have you tried using project references? https://www.typescriptlang.org/docs/handbook/project-references.html
