### ISSUE TITLE
Staging a change doesn't use correct file encoding

### ISSUE THREAD

**Issue by izacsc** [microsoft/vscode#137958]
Issue Type: <b>Bug</b>

1. Open a file with a non UTF-8 encoding ( e.g. windows 1252 ) in a git repository.
2. Make changes in the file. 
3. Select the "Stage change" option from the hover menu. 
4. The file will be staged with the wrong encoding.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.96GB free)|
|Process Argv|--crash-reporter-id 894f54ae-c2f3-4c75-bfc8-7f4ac5dc9e16|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
protheusdoc-vscode|Ale|0.9.0
xml|Dot|2.5.1
gitlens|eam|11.7.0
vscode-engpro-extension|eng|1.2.0
advpl-unit-test|Kil|0.1.0
advpl-vscode|Kil|0.14.11
live-server|ms-|0.2.9
test-adapter-converter|ms-|0.1.4
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.1
code-spell-checker|str|2.0.13
code-spell-checker-portuguese-brazilian|str|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593:30376534
vssld246:30401890
pythonvs932cf:30404740
vscexrecpromptt1:30404947
vscop804cf:30404767
vscop453:30404998

```

</details>

**Comment by Lemmingh** [comment]
#111915

**Comment by lszomoru** [comment]
Closing this issue in favour of the duplicate - #111915
