### ISSUE TITLE
Wrap Text

### ISSUE THREAD

**Issue by Assafkalfa** [microsoft/vscode#137997]
Issue Type: <b>Feature Request</b>

Hi

Can you please add an ICON to wrap/unwrap text (view, not change the source)
Yes, I know Ctrl Shift P shortcut, but icon will be more useful (as we not always remember this shortcut, etc.)

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by timmermansjoy** [comment]
You can also use `F1` key

**Comment by egamma** [comment]
There is already a menu entry for 'Word wrap' pls try 'View>Word Wrap' does this cover your needs?

**Comment by gjsjohnmurray** [comment]
> There is already a menu entry for 'Word wrap' pls try 'View>Word Wrap' does this cover your needs?

And its Windows shortcut is <kbd>Alt</kbd>+<kbd>Z</kbd> which I remember because the letter Z somewhat resembles a long line being wrapped.

**Comment by egamma** [comment]
@gjsjohnmurray good point. I'll close the issue.
