### ISSUE TITLE
open folder in a wrong window

### ISSUE THREAD

**Issue by golang101** [Microsoft/vscode#13790]
- VSCode Version: 1.5.3
- OS Version: Debian 8

Steps to Reproduce:
1. Press ALT
2. Select File
3. Select Open New Window
4. In the new window, select Open Folder ...
5. the new folder is opened in the old window, the old folder opened in the old window is closed. 

Not 100% reproduced. About 5% I think.

**Comment by bpasero** [comment]
Could be a focus issue, maybe the old window still has focus when this happens?

**Comment by golang101** [comment]
@bpasero, 
> maybe the old window still has focus when this happens?

The possibility is low. The dialog was poped up by selecting the menitems in the new window,

**Comment by bpasero** [comment]
@golang101 does it reproduce with VS Code 1.6.x?

**Comment by golang101** [comment]
@bpasero, 
ok, I just installed vsc 1.6.1.

This problem is rare. 5% is some exaggerated. In my impression, it is about once per two weeks.
