### ISSUE TITLE
way to index all my existing workspaces (so that they appear on "open recent")

### ISSUE THREAD

**Issue by Lycopode** [microsoft/vscode#137912]
I reinstalled vscode, I have a lot of projects / workspaces on my computer and I want to index all my projects on vscode so that they can all be found when I go to "open recent" (shortcut on mac : CMD + R).

Currently the only solution I have found is to do it manually, by opening each project with "open", then it will get indexed by vscode. Is there a way to do it automatically? Can't find any cli option.

**Comment by egamma** [comment]
/needsMoreInfo
I suggest that you try to use the popular Project Manager extension https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager. Does this cover your needs?

**Comment by Lycopode** [comment]
@egamma why you need more info? No, I don't want to use an extension for a simple use case which is to open my projects on vscode. 

My question is simple : I want to batch-add all my projects from my computer to the list of projects that appears when you go to "open recent" / when you use the `CMD + R` shortcut.

**Comment by Lycopode** [comment]
up

**Comment by egamma** [comment]
>@egamma why you need more info? No, I don't want to use an extension for a simple use case which is to open my projects on vscode.

@egamma sry if I was not clear, I wanted to get your feedback whether this extension covers your needs. For this reason I've added the `needsMoreInfo` label.

>No, I don't want to use an extension for a simple use case which is to open my projects on vscode.

This answer is clear, thank you.

**Comment by Lycopode** [comment]
So this feature doesn't exist yet in vscode? I guess a good way to add this feature could be to add a cli option to to index a project to the "open recent" without actually opening it when you do `code myproject`
