### ISSUE TITLE
White Screen Flashes While Loading

### ISSUE THREAD

**Issue by foreachthing** [microsoft/vscode#137981]
Issue Type: <b>Bug</b>

Get adjusted to dark area, with nightlight on and some-what tired eys.
Then start VS-Code .... _I'm blind!!_
The screen, the whole screen, flashes bright white even though I set the app to darkmode. This white flash is hard on the eyes....

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (14.22GB free)|
|Process Argv|--crash-reporter-id 79c5aa2f-60e7-4835-81f4-36a77a0911a3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.2.2
project-manager|ale|12.4.0
vscode-django|bat|1.6.0
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|9.0.0
auto-rename-tag|for|0.1.9
code-runner|for|0.11.6
beautify|Hoo|1.5.0
latex-workshop|Jam|8.22.0
csharpextensions|jch|1.3.1
vsc-python-indent|Kev|1.14.2
vscode-smart-column-indenter|lmc|0.0.13
MagicPython|mag|1.1.0
csharp|ms-|1.23.16
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
cpptools|ms-|1.7.1
powershell|ms-|2021.10.2
update-python-packages-and-requirements-txt|niz|1.1.4
autodocstring|njp|0.5.4
material-icon-theme|PKi|4.11.0
vscode-qt-for-python|sea|1.1.4
code-spell-checker|str|2.0.13
python|tht|0.2.3
latex-support|tor|3.10.0
python-extended-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.7.0
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30402085
vsaa593cf:30376535
vssld246cf:30401891
vscexrecpromptc:30404946
vscop804cf:30404767
vscop453:30404998

```

</details>

**Comment by egamma** [comment]
/needsMoreInfo pls provide details steps for how we can reproduce the problem, what settings do you have enabled, at which point does the screen flash, what do you exactly mean by 'nightlight on'

**Comment by foreachthing** [comment]
Please watch this video: https://youtu.be/eQo7rUMVpHw.
You can see, around 4 seconds, the screen flashes white. At first startup it's longer.

Even without Wallpaper Engine, the screen flashes white.

"Nightlight" Microsoft's Windows Night light (see System -> Display -> Night light)
Not sure if it matters, but it still hurts my eyes...

**Comment by yume-chan** [comment]
Duplicate of #132339

**Comment by foreachthing** [comment]
Dup.
