### ISSUE TITLE
Menus not responsive on Windows 10

### ISSUE THREAD

**Issue by douglasstarnes** [Microsoft/vscode#138]
So I created a fresh Windows 10 VM today to try out the Beta.  However, the application is sluggish to open which isn't a big deal but I never noticed it before.  The problem is that the menus are not working.  They will appear on clicking on the menu bar, but selecting a menu item does nothing.  If I try to open a project folder from the explorer VSCode opens but the folder does not.  I have restarted and reinstalled with a fresh download of the installer.  Am I the only one who is seeing this?

**Comment by douglasstarnes** [comment]
So I fixed the problem.  Installing the Windows 10 November update was the solution.  However, I also tried installing on an existing VM that does not have the November update installed so I'll leave it up to the MS folks to leave this issue open or close it.

**Comment by bpasero** [comment]
Ok thanks for the update, will close for now.
