### ISSUE TITLE
Visual Studio validating JavaScript files as Typescript

### ISSUE THREAD

**Issue by bryanrasmussen** [microsoft/vscode#138043]
A site with mixed JS and TS is suddenly getting all JS validated as TS, now probably someone has added something somewhere in site that is causing this but I submit there should be no possible addition that should be able to cause this given the following conditions: 

The file extension is .js
The language mode at the bottom of the editor says JavaScript
I have turned off the Typescript validate enable in the settings

The only way that I found whereby I can turn off TS errors showing up in the JavaScript files is if I turn off JavaScript validate Enable. Which is of course problematic because it should not be that one should have to do without normal syntax checking etc. just because you are not willing to use typescript on this file, people have things to get done and cannot migrate the language of a project because the editor suddenly is unusable otherwise. 

I am not running any extensions with @builtin typescript. 

I have not set the tsdk (a suggestion I have read as a possible cause of this) - but even if you had set the tsdk what possible reason could it have to be validating JS. 

Frankly I have read A LOT of suggested ways that this scenario could exist, so I ask again WHY and state emphatically IT SHOULD NOT! There should not be any way that typescript starts validating all your JavaScript errors leading to the oft seen suggestion to turn off JavaScript validation, that it does is a bug, if it is a bug that will not be fixed because working as intended then I guess I would have to say that intention seems unethical and dangerous to me. 

VS code info 
Version: 1.62.3 (Universal)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T07:59:13.865Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

**Comment by IllusionMH** [comment]
/needsMoreInfo

If you have mixed JS and TS files - please provide `tsconfig.json` content? Do you have `"allowJS": true` and/or `"checkJS": true` in configuration?
Do you have in User or Workspace setting "JS/TS › Implicit Project Config: Check JS" enabled (`"js/ts.implicitProjectConfig.checkJs": true`)?

Do you see same errors if you run `tsc` on this project?
