### ISSUE TITLE
Issues with waking up when chrome using nvidia video card.

### ISSUE THREAD

**Issue by sillyotter** [Microsoft/vscode#13805]
My computer has a intel and nvidia card in it (Intel HD 530, Nvidia gforce 940MX).  For some reason I configured the system to use the nvidia card to handle chrome.

When in this configuration, and I run vscode, and let the display go to sleep, upon wake up code is displaying its window, but not its title bar or borders, and all the rest of the os desktop and all other apps are black with no display.  I have to power cycle the machine to fix.

Once I adjusted the settings so that chrome was using the intel card, the problem goes away.

Also, chrome itself does not exhibit this behavior, just vscode.  I dont have any other electron apps to test it with.
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: donjayamanne.githistory-0.1.0, donjayamanne.python-0.4.2, DotJoshJohnson.xml-1.6.0, DougFinke.vscode-pandoc-0.0.8, dracula-theme.theme-dracula-1.2.5, Ionide.Ionide-FAKE-1.1.0, Ionide.Ionide-fsharp-2.6.11, Ionide.Ionide-Paket-1.2.2, lukehoban.Go-0.6.44, mjmcloug.vscode-elixir-0.0.8, ms-vscode.csharp-1.4.1, ms-vscode.PowerShell-0.7.2, msjsdiag.debugger-for-chrome-1.2.0, pgourlain.erlang-0.0.9, robertohuertasm.vscode-icons-3.0.4, samverschueren.yo-0.8.5, sandy081.todotasks-0.4.0, saviorisdead.RustyCode-0.19.1, sbrink.elm-0.8.3

Steps to Reproduce:
1.  Configure chrome to use nvidia card in nvidia control panel
2.  Let screen go to sleep
3.  Wake up

**Comment by bpasero** [comment]
Marking as upstream because this sounds like an issue with Electron or Chrome. Please try if possible to reproduce with Electron or Atom.

**Comment by sillyotter** [comment]
I installed atom and tested.  It DOES NOT happen with atom, nor with chrome by itself.  Just with Code.

**Comment by bpasero** [comment]
@sillyotter make sure to try with Atom Beta as they use a comparable Electron version as we do (not Atom stable).

**Comment by sillyotter** [comment]
The problem also happens with Atom 1.12.0-beta2 so its definitely electron.

**Comment by bpasero** [comment]
That is what I expected, thanks 👍

**Comment by bpasero** [comment]
@sillyotter  we just updated Electron again, was wondering if that helps you: http://code.visualstudio.com/Download#insiders

**Comment by sillyotter** [comment]
Based on the hand full of tests I've run with no problem, I'd say electron has fixed this issue.  Everything seems to be fine now.

**Comment by bpasero** [comment]
Nice, thanks 👍
