### ISSUE TITLE
'#' at the end of heading disappeared in outline for markdown files

### ISSUE THREAD

**Issue by yamasix** [microsoft/vscode#138027]
Issue Type: <b>Bug</b>

If the heading is [something]#, # is disappeared in outline.

![sharp is disappeared](https://user-images.githubusercontent.com/12419113/143813498-8d8eb886-46fd-4d11-bc29-f9536b28ea6c.png)

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by mjbvz** [comment]
This is by-design as Markdown rendering also strips out any trailing `#` in the header

**Comment by yamasix** [comment]
OK, but # is rendered in markdown preview.

![md_preview](https://user-images.githubusercontent.com/12419113/144939140-d83fc10e-d564-40ff-87ab-d472dfbe4c56.png)
