### ISSUE TITLE
Test $id in json schemas

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#138098]
Refs:  #92042

- [x] anyOs @DonJayamanne

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23138098%0A%0A&assignees=aeschli)

---

We now support that relative $ids can be referenced by $ref in schemas

- In a schema file
`bar.schema.json`:
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "bar": {
            "$ref": "#foo"
        },
        "foo": {
            "$id": "#foo",
            "type": "string",
            "enum": [
                "foo1",
                "foo2"
            ]
        }
    }
}
````
- bar.json
```
{
    "$schema": "./zoo.schema.json",
    "bar":
}

```

- verify that code completion after `bar` shows `foo1` and `foo2`

**Comment by DonJayamanne** [comment]
Verified
