### ISSUE TITLE
Git integration fails if code is launched from command-line with non-matching folder case

### ISSUE THREAD

**Issue by reed-lawrence** [microsoft/vscode#138090]
- VS Code Version: 1.62.3 (Universal)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T07:59:13.865Z (1 wk ago)
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.1.0

- OS Version: MacOS Monterey 12.0.1

Steps to Reproduce:

Given a folder/repo is titled `My-Repo`

1. In a command line `code my-repo` or `code MY-REPO`
2. VS Code opens as expected, but git output contains many failures such as: `Opening repository for path='/Users/admin/source/repos/MY-REPO/package.json' failed; ex=RangeError [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 1`
3. VS Code git integration is largely broken, requiring manual detection of changes within the Git SCM extension. All gutter change flagging is broken as well. The Git extension itself still works. With full push/pull/fetch/etc functionality. Only the editor/explorer integration breaks.
4. From command line `code My-Repo` works as expected with full Git functionality

**Comment by lszomoru** [comment]
2) These were harmless exceptions but have been addressed with commit 47de42baa91f4f401f3bf51eaf545e0239522f02

> VS Code git integration is largely broken, requiring manual detection of changes within the Git SCM extension.

Could you please expand on what you mean by the git integration is largely broken? Thanks!

> All gutter change flagging is broken as well.

Could you please provide more details so that I can reproduce the issue and address it? Thanks!

**Comment by reed-lawrence** [comment]
In these two examples I have the git repo named `angular-docker` in the first expected example, I open the repo with the command `code angular-docker` and demonstrate how the VS Code integration behaves as expected when I make changes to a file. 

In the second example, I open the same repo with the command `code ANGULAR-DOCKER`. Same repo - but different casing of the repo name. I then demonstrate how VS Code fails to recognize changes to the same file. 

Expected:

https://user-images.githubusercontent.com/30061591/145588835-e10d3ebd-af80-4385-a76e-24a3b295ff52.mov



Actual:


https://user-images.githubusercontent.com/30061591/145588963-e7d9e3c0-9c70-43e0-9730-110ed4a155b2.mov

**Comment by lszomoru** [comment]
@reed-lawrence, thank you very much for the recording. I will look into this early next week.

**Comment by lszomoru** [comment]
Dirty diff decorator has been fixed in commit https://github.com/microsoft/vscode/commit/c3bd29b3d09e29b49f8050a5b55106960a671e3b.

**Comment by lszomoru** [comment]
@reed-lawrence, the latest Insiders release contains fixes that address both issues that were outlined in this issue. I will go ahed and close the issue but in case you experience any other git problems when using non-bathing folder case please feel free to reopen the issue. Thanks!
