### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by SamAmin2** [microsoft/vscode#138039]
- Issue Type: `Bug`
- Extension Name: `microsoft-authentication`
- Extension Version: `0.0.1`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.62.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 44,
		"activateCallTime": 1,
		"activateResolvedTime": 471,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "vscode.microsoft-authentication",
				"_lower": "vscode.microsoft-authentication"
			},
			"activationEvent": "onAuthenticationRequest:microsoft"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

This occurred while trying to save an xml file.
It's been happening frequently recently

**Comment by SamAmin2** [comment]
![image](https://user-images.githubusercontent.com/38502944/143854405-299c00da-7f36-4f33-9552-ca03d53ecd8a.png)

**Comment by TylerLeonhardt** [comment]
Can you provide the contents of the Microsoft Authentication output pane:
![image](https://user-images.githubusercontent.com/2644648/128087382-c706864f-7005-4a2e-878b-662c69c4457e.png)

And also anything that shows up in Dev Tools:

* ctrl + shift + P
* "Dev Tools"
