### ISSUE TITLE
Test the markdown preview custom editor

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#138040]
Test for #84520

- [x] Any @sandy081
- [x] Any @rchiodo

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23138040%0A%0A&assignees=mjbvz)

---

This is an exploratory test plan item for the markdown preview custom editor. This allows you to use `reopen with` to reopen the current document as a markdown preview instead of as a normal text editor . 

For this test plan item, please try using the new preview editor and seeing what doesn't work as expected. Some specific things to try:

- Try using `reopen with` to switch a text document to a markdown preview

- Try configuring `workbench.editorAssociations` to use the preview by default: 

    ```
    "workbench.editorAssociations": {
      "*.md": "vscode.markdown.preview.editor"
    }
    ```

- Make sure clicking on links works as expected using the new markdown preview. 

    Try using the vscode-docs repo since it has lots of links between files (images will not load since they use git LFS)

- Make sure scroll positions are restored properly when reloading a window or switching away from an editor and back

- Make sure scroll sync is disabled for preview based custom editors

**Comment by rchiodo** [comment]
> Make sure scroll sync is disabled for preview based custom editors

This seems to be sync'd so I'm also not sure what this means. Do you mean between 'Open Preview' and the editor we're testing?
