### ISSUE TITLE
Flaky test: FileSearchEngine Files: *.* include with unicode

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#138069]
This test failed 8 times over the past 30 days. I notice the suite is using `flakySuite` as well, we should consider figuring out the root cause of the flakiness as flaky tests will always have a chance to fail multiple times.

![image](https://user-images.githubusercontent.com/2193314/143910511-0f586179-7a2c-46f3-8552-91396a3361d8.png)

Failed run: https://monacotools.visualstudio.com/Monaco/_build/results?buildId=144087&view=results

Failure:

```
Error: ENOENT: no such file or directory, scandir '/Users/runner/work/1/s/out-build/vs/workbench/services/search/test/node/fixtures\üm laut汉语'
    at readdirSync (fs.js:1021:3)
    at e.readdirSync (electron/js2c/asar_bundle.js:5:10478)
    at Context.<anonymous> (file:///Users/runner/work/1/s/out-build/vs/workbench/services/search/test/node/search.integrationTest.js:433:34)
```

**Comment by Tyriar** [comment]
These tests also flaked:

- `FileSearchEngine Files: *.* exclude with unicode`
- `FileSearchEngine Files: Unicode and Spaces`

**Comment by eleanorjboyd** [comment]
I am going to guess this test is no longer being flaky if it is no longer being placed on the milestone for the past 2 years? @roblourens
