### ISSUE TITLE
Language switch on Tab key didn't work while using Pinyin as the input method.

### ISSUE THREAD

**Issue by ipaddicting** [microsoft/vscode#138028]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.62.3
- OS Version: macOS Monterey 12.0.1

Steps to Reproduce:

1. Change the Pinyin as the input method;
2. Open the terminal in VS Code;
3. Press 'Tab' to switch from Chinese to English;
4. All words typed in the terminal will be capitalized only(Intellij IDEA or iTerm2 won't have this issue).

**Comment by yume-chan** [comment]
I don't think "Tab" key switches between Chinese and English. If you are referring the Capslock key, then duplicate of xtermjs/xterm.js#2457

**Comment by ipaddicting** [comment]
> I don't think "Tab" key switches between Chinese and English. If you are referring the Capslock key, then duplicate of [xtermjs/xterm.js#2457](https://github.com/xtermjs/xterm.js/issues/2457)

Yes, my mistake. It related to Capslock key. Thanks
