### ISSUE TITLE
Feature request: dock integrated terminal into dedicated tab

### ISSUE THREAD

**Issue by anthony-y** [Microsoft/vscode#13806]
Currently, the integrated terminal just sort of floats over top of code tabs; wouldn't it be a good idea to allow you to dock it into it's own dedicated tab, like you can when viewing the details of an extension?

It would look something like this:

![wow](https://i.imgur.com/tHb71WA.png)

It's a little crude, I threw it together in 5 minutes in GIMP :stuck_out_tongue:

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/2806

**Comment by anthony-y** [comment]
Ah sorry, I tried to see if there were any others before I posted but I guess I didn't look hard enough.

**Comment by isidorn** [comment]
No worries
