### ISSUE TITLE
Test replace Output channel API

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#138077]
Ref #132183

- [x] Mac @tanhakabir
- [x] Win @rchiodo
- [x] Linux @joaomoreno

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23138077%0A%0A&assignees=sandy081)

---

We added `replace` api to OutputChannel that will replace the existing content of the channel. Please test if The API is working as expected and also validate the doc.

```ts
/**
		 * Replaces all output from the channel with the given value.
		 *
		 * @param value A string, falsy values will not be printed.
		 */
		replace(value: string): void;
```

A sample extension that creates an output channel and uses replace api

```ts
import * as vscode from 'vscode';

export async function activate(context: vscode.ExtensionContext) {
	const channel = vscode.window.createOutputChannel('test channel');
	channel.appendLine('Append content');
	channel.appendLine('Append content');
	channel.appendLine('Append content');
	channel.appendLine('Append content');
	channel.replace('Content to be replace');
}

// this method is called when your extension is deactivated
export function deactivate() { }

```

**Comment by joaomoreno** [comment]
The proposal mechanism transition makes testing this hard, since:

1. This is not in the new proposal format
2. It is no longer in the vscode.proposed.d.ts file

So, to test it properly, add the following `vscode.proposed.d.ts` file to your extension sources:

```ts
declare module 'vscode' {
	export interface OutputChannel {
		/*
		 * Replaces the existing contents of the channel with the given value.
		 */
		replace(value: string): void;
	}
}
```

**Comment by sandy081** [comment]
@joaomoreno This is finalized api, so it shall be available in `vscode.d.ts`. Not sure why this has to be added to the proposed api?

**Comment by joaomoreno** [comment]
If you start with `yo code`, you won't get that definition by default.

**Comment by rchiodo** [comment]
@sandy081 where are the docs? Are you talking about the comments in the vscode.d.ts? I thought it might be here too?
https://raw.githubusercontent.com/microsoft/vscode-docs/vnext/api/references/vscode-api.md

**Comment by sandy081** [comment]
> If you start with yo code, you won't get that definition by default.

I see.

@rchiodo By docs, I mean the comments in the vscode.d.ts file. Sorry for being ambiguous
