### ISSUE TITLE
files.exclude has different behavior based on matching specific file names or patterns

### ISSUE THREAD

**Issue by MarkKahn** [microsoft/vscode#138009]
Issue Type: <b>Bug</b>

For sanity purposes all my config files are symlinked in `./config` and hidden from the root dir in vscode.

My `settings.json` file includes:

```json
"files.exclude": {
  "*.json": true,

  "config/**/*": false
}
```

which hides `package.json`, etc in the root and shows it in config.  This works fine.  I'm trying to do the same on nested projects, however, and I noticed something weird.  If I change the settings to:

```json
"files.exclude": {
  "**/package.json": true,

  "config/**/*": false
}
```

now `package.json` no longer appears in `./config`.  Also if I remove the leading wildcard, `"package.json"` does show in `./config`

VS Code version: Code 1.62.3 (Universal) (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-77-generic

**Comment by IllusionMH** [comment]
`false` in `files.exclude` does not turn it into "include" - just doesn't mark it excluded. Therefore `"config/**/*": false` doesn't affect `package.json` excluded/hidden at any nesting level (`**`).

You need to all more exclude patterns for all other folders except `config`. 

Negations for `files.exclude` tracked on #869
