### ISSUE TITLE
Cannot open VS Code on Windows 10

### ISSUE THREAD

**Issue by Elsewhere42** [microsoft/vscode#138094]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: x64-1.62.3
- OS Version: Windows 10 v1909

This is a new Windows 10 laptop at work that I am setting up for the first time.  VS Code is one of the first applications I'm trying to install.

Steps to Reproduce:

1. Download VSCodeUserSetup-x64-1.62.3.exe
2. Execute VSCodeUserSetup-x64-1.62.3.exe to install.
    Note:  I also tried to install VSCodeSetup-x64-1.62.3.exe
3. When install is complete, click on VS Code icon in start window.
4. Observe empty/unresponsive ghost window outline.
5. After a short while error window appears asking if I want to close unresponsive program.

Here are the verbose logs:

C:\WINDOWS\system32>code --verbose --disable-gpu --disable-extensions

[main 2021-11-29T20:45:24.032Z] Starting VS Code
[main 2021-11-29T20:45:24.036Z] from: c:\Users\[username]\AppData\Local\Programs\Microsoft VS Code\resources\app
[main 2021-11-29T20:45:24.036Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': true,
  'disable-gpu': true,
  'ms-enable-electron-run-as-node': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': '75e9a086-8682-407c-8cf4-e285fe7a21a3',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: 'C:\\Users\\[username]\\AppData\\Roaming\\Code\\logs\\20211129T144523'
}
[main 2021-11-29T20:45:24.039Z] Resolving machine identifier...
[main 2021-11-29T20:45:24.039Z] Resolved machine identifier: 60c996423c869f575fa4dd8886b167f8e6525788fbf5d7c1ffba8b0a0d0ed9ce
[main 2021-11-29T20:45:24.040Z] Main->SharedProcess#connect
[main 2021-11-29T20:45:24.106Z] StorageMainService: creating global storage
[main 2021-11-29T20:45:24.107Z] lifecycle (main): phase changed (value: 2)
[main 2021-11-29T20:45:24.113Z] windowsManager#open
[main 2021-11-29T20:45:24.113Z] windowsManager#open pathsToOpen [
  {
    backupPath: 'C:\\Users\\[username]\\AppData\\Roaming\\Code\\Backups\\1638217560946',
    remoteAuthority: undefined
  }
]
[main 2021-11-29T20:45:24.117Z] IPC Object URL: Registered new channel vscode:449ae74a-ffe3-4591-96f1-556ffeca49c6.
[main 2021-11-29T20:45:24.118Z] window#validateWindowState: validating window state on 2 display(s) { mode: 1, x: 256, y: 48, width: 1024, height: 768 }
[main 2021-11-29T20:45:24.120Z] window#validateWindowState: multi-monitor working area { x: 0, y: 0, width: 1536, height: 824 }
[main 2021-11-29T20:45:24.120Z] window#ctor: using window state { mode: 1, x: 256, y: 48, width: 1024, height: 768 }
[main 2021-11-29T20:45:24.264Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 1, emptyToOpen: 0)
[main 2021-11-29T20:45:24.265Z] lifecycle (main): phase changed (value: 3)
[main 2021-11-29T20:45:24.290Z] update#setState idle
[main 2021-11-29T20:45:24.291Z] resolveShellEnv(): skipped (Windows)
[main 2021-11-29T20:45:24.651Z] [File Watcher (node.js)] [CHANGED] c:\Users\[username]\AppData\Roaming\Code\User\globalStorage
[main 2021-11-29T20:45:24.656Z] [File Watcher (node.js)] [CHANGED] c:\Users\[username]\AppData\Roaming\Code\User\globalStorage
[main 2021-11-29T20:45:24.858Z] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\[username]\AppData\Roaming\Code\User\globalStorage
[main 2021-11-29T20:45:25.665Z] resolveShellEnv(): skipped (Windows)
[main 2021-11-29T20:45:54.291Z] update#checkForUpdates, state =  idle
[main 2021-11-29T20:45:54.291Z] update#setState checking for updates
[main 2021-11-29T20:45:54.291Z] RequestService#request https://update.code.visualstudio.com/api/update/win32-x64-user/stable/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
[main 2021-11-29T20:45:54.291Z] resolveShellEnv(): skipped (Windows)
[main 2021-11-29T20:46:07.948Z] update#setState idle
[main 2021-11-29T20:50:41.596Z] CodeWindow: detected unresponsive
[main 2021-11-29T20:51:07.912Z] IPC Object URL: Removed channel vscode:449ae74a-ffe3-4591-96f1-556ffeca49c6.
[main 2021-11-29T20:51:07.912Z] Lifecycle#window.on('closed') - window ID 1
[main 2021-11-29T20:51:07.912Z] Lifecycle#onWillShutdown.fire()
[main 2021-11-29T20:51:07.914Z] Lifecycle#app.on(window-all-closed)
[main 2021-11-29T20:51:07.915Z] Lifecycle#app.on(before-quit)
[main 2021-11-29T20:51:07.915Z] Lifecycle#onBeforeShutdown.fire()
[main 2021-11-29T20:51:07.915Z] [WindowsStateHandler] onBeforeShutdown {
  lastActiveWindow: {
    workspaceIdentifier: undefined,
    folder: undefined,
    backupPath: 'C:\\Users\\[username]\\AppData\\Roaming\\Code\\Backups\\1638217560946',
    remoteAuthority: undefined,
    uiState: [Object: null prototype] {
      mode: 1,
      x: 256,
      y: 48,
      width: 1024,
      height: 768
    }
  },
  lastPluginDevelopmentHostWindow: undefined,
  openedWindows: []
}
[main 2021-11-29T20:51:07.916Z] Lifecycle#app.on(will-quit)
[main 2021-11-29T20:51:07.951Z] StorageMainService: closed global storage

C:\WINDOWS\system32>

[Window Title]
Visual Studio Code

[Main Instruction]
The window is not responding

[Content]
You can reopen or close the window or keep waiting.

[Reopen] [Keep Waiting] [Close]

**Comment by Elsewhere42** [comment]
Are there any updates on this?  VS Code is completely unusable right now.

**Comment by adicirstei** [comment]
Same here with the latest vscode version 1.63.1 64 bit.

I managed to run the insider version below:
Version: 1.64.0-insider
Commit: 886fd126446cd4b8b03f2b32f09c173dec541e6d
Date: 2021-12-14T16:25:19.507Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by deepak1556** [comment]
Unable to repro the issue with latest stable `1.73` on Windows 10
