### ISSUE TITLE
Issue with HTML comments

### ISSUE THREAD

**Issue by Nic787** [Microsoft/vscode#13801]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: None

Problem : HTML comments tags not working.

Steps to Reproduce:

1. Add  Will not work. Everything bellow is commented...

![comment](https://cloud.githubusercontent.com/assets/11185348/19411145/839fc8b6-92c9-11e6-854f-13ee0d6eb8df.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/11081
