### ISSUE TITLE
Formatting on save not working

### ISSUE THREAD

**Issue by asalcedo29** [microsoft/vscode#138074]
Up to last week the feature was working correctly...now code isn't automatically formatted when I save. I'm working with Python and autopep-8 formatter. Settings below:
{
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "jupyter.interactiveWindowMode": "perFile",
    "jupyter.sendSelectionToInteractiveWindow": true,
    "editor.wordWrap": "on",
    "window.restoreWindows": "all",
    "editor.wordWrapColumn": 120,
    "tabnine.experimentalAutoImports": true,
    "window.zoomLevel": 0,
    "tab-groups.groups": "W3sibmFtZSI6IkJyYW5jaDogYW5zYWxjZWQvbGF5b3V0LWNoYW5nZXMiLCJsaXN0IjpbXX0seyJuYW1lIjoiQnJhbmNoOiBtYXN0ZXIiLCJsaXN0IjpbXX0seyJuYW1lIjoiQnJhbmNoOiBhbnNhbGNlZC9zZW1hbnRpYy1zZWFyY2giLCJsaXN0IjpbeyJkb2N1bWVudCI6eyJ1cmkiOnsiJG1pZCI6MSwiZnNQYXRoIjoiZDpcXHNvdXJjZVxccmVwb3NcXFByb1NBVERhc2hib2FyZFxcRmVlZGJhY2tfQW5hbHlzaXNfRGFzaGJvYXJkXFxsYXlvdXQucHkiLCJfc2VwIjoxLCJleHRlcm5hbCI6ImZpbGU6Ly8vZCUzQS9zb3VyY2UvcmVwb3MvUHJvU0FURGFzaGJvYXJkL0ZlZWRiYWNrX0FuYWx5c2lzX0Rhc2hib2FyZC9sYXlvdXQucHkiLCJwYXRoIjoiL0Q6L3NvdXJjZS9yZXBvcy9Qcm9TQVREYXNoYm9hcmQvRmVlZGJhY2tfQW5hbHlzaXNfRGFzaGJvYXJkL2xheW91dC5weSIsInNjaGVtZSI6ImZpbGUifSwiZmlsZU5hbWUiOiJkOlxcc291cmNlXFxyZXBvc1xcUHJvU0FURGFzaGJvYXJkXFxGZWVkYmFja19BbmFseXNpc19EYXNoYm9hcmRcXGxheW91dC5weSIsImlzVW50aXRsZWQiOmZhbHNlLCJsYW5ndWFnZUlkIjoicHl0aG9uIiwidmVyc2lvbiI6MjI5LCJpc0Nsb3NlZCI6dHJ1ZSwiaXNEaXJ0eSI6ZmFsc2UsImVvbCI6MiwibGluZUNvdW50Ijo3NzN9LCJ2aWV3Q29sdW1uIjoxLCJmb2N1c3NlZCI6dHJ1ZX0seyJkb2N1bWVudCI6eyJ1cmkiOnsiJG1pZCI6MSwiZnNQYXRoIjoiZDpcXHNvdXJjZVxccmVwb3NcXFByb1NBVERhc2hib2FyZFxcRmVlZGJhY2tfQW5hbHlzaXNfRGFzaGJvYXJkXFxjYWxsYmFja3MucHkiLCJfc2VwIjoxLCJleHRlcm5hbCI6ImZpbGU6Ly8vZCUzQS9zb3VyY2UvcmVwb3MvUHJvU0FURGFzaGJvYXJkL0ZlZWRiYWNrX0FuYWx5c2lzX0Rhc2hib2FyZC9jYWxsYmFja3MucHkiLCJwYXRoIjoiL0Q6L3NvdXJjZS9yZXBvcy9Qcm9TQVREYXNoYm9hcmQvRmVlZGJhY2tfQW5hbHlzaXNfRGFzaGJvYXJkL2NhbGxiYWNrcy5weSIsInNjaGVtZSI6ImZpbGUifSwiZmlsZU5hbWUiOiJkOlxcc291cmNlXFxyZXBvc1xcUHJvU0FURGFzaGJvYXJkXFxGZWVkYmFja19BbmFseXNpc19EYXNoYm9hcmRcXGNhbGxiYWNrcy5weSIsImlzVW50aXRsZWQiOmZhbHNlLCJsYW5ndWFnZUlkIjoicHl0aG9uIiwidmVyc2lvbiI6Njk4LCJpc0Nsb3NlZCI6dHJ1ZSwiaXNEaXJ0eSI6ZmFsc2UsImVvbCI6MiwibGluZUNvdW50IjoyMDM1fSwidmlld0NvbHVtbiI6MiwiZm9jdXNzZWQiOmZhbHNlfSx7ImRvY3VtZW50Ijp7InVyaSI6eyIkbWlkIjoxLCJmc1BhdGgiOiJkOlxcc291cmNlXFxyZXBvc1xcUHJvU0FURFNcXFN1cnZleXNBbmRTaWduYWxzXFxDb25zaXN0ZW50UXVlc3Rpb25BbmFseXNpc1xcQW5hbHlzaXNcXFBsYXRmb3JtSW1wcmVzc2lvbnMucHkiLCJfc2VwIjoxLCJleHRlcm5hbCI6ImZpbGU6Ly8vZCUzQS9zb3VyY2UvcmVwb3MvUHJvU0FURFMvU3VydmV5c0FuZFNpZ25hbHMvQ29uc2lzdGVudFF1ZXN0aW9uQW5hbHlzaXMvQW5hbHlzaXMvUGxhdGZvcm1JbXByZXNzaW9ucy5weSIsInBhdGgiOiIvRDovc291cmNlL3JlcG9zL1Byb1NBVERTL1N1cnZleXNBbmRTaWduYWxzL0NvbnNpc3RlbnRRdWVzdGlvbkFuYWx5c2lzL0FuYWx5c2lzL1BsYXRmb3JtSW1wcmVzc2lvbnMucHkiLCJzY2hlbWUiOiJmaWxlIn0sImZpbGVOYW1lIjoiZDpcXHNvdXJjZVxccmVwb3NcXFByb1NBVERTXFxTdXJ2ZXlzQW5kU2lnbmFsc1xcQ29uc2lzdGVudFF1ZXN0aW9uQW5hbHlzaXNcXEFuYWx5c2lzXFxQbGF0Zm9ybUltcHJlc3Npb25zLnB5IiwiaXNVbnRpdGxlZCI6ZmFsc2UsImxhbmd1YWdlSWQiOiJweXRob24iLCJ2ZXJzaW9uIjoxLCJpc0Nsb3NlZCI6dHJ1ZSwiaXNEaXJ0eSI6ZmFsc2UsImVvbCI6MiwibGluZUNvdW50IjoyODh9LCJ2aWV3Q29sdW1uIjoyLCJmb2N1c3NlZCI6ZmFsc2V9XX0seyJuYW1lIjoiQnJhbmNoOiBhbnNhbGNlZC9maWx0ZXJlZC10YWJsZS1hZGp1c3RtZW50IiwibGlzdCI6W119LHsibmFtZSI6IkJyYW5jaDogYW5zYWxjZWQvc2VsZWN0ZWRjbHVzdGVyLXRhYmxlLWFkanVzdG1lbnQiLCJsaXN0IjpbeyJkb2N1bWVudCI6eyJ1cmkiOnsiJG1pZCI6MSwiZnNQYXRoIjoiZDpcXHNvdXJjZVxccmVwb3NcXFByb1NBVERhc2hib2FyZFxcRmVlZGJhY2tfQW5hbHlzaXNfRGFzaGJvYXJkXFxsYXlvdXQucHkiLCJfc2VwIjoxLCJleHRlcm5hbCI6ImZpbGU6Ly8vZCUzQS9zb3VyY2UvcmVwb3MvUHJvU0FURGFzaGJvYXJkL0ZlZWRiYWNrX0FuYWx5c2lzX0Rhc2hib2FyZC9sYXlvdXQucHkiLCJwYXRoIjoiL0Q6L3NvdXJjZS9yZXBvcy9Qcm9TQVREYXNoYm9hcmQvRmVlZGJhY2tfQW5hbHlzaXNfRGFzaGJvYXJkL2xheW91dC5weSIsInNjaGVtZSI6ImZpbGUifSwiZmlsZU5hbWUiOiJkOlxcc291cmNlXFxyZXBvc1xcUHJvU0FURGFzaGJvYXJkXFxGZWVkYmFja19BbmFseXNpc19EYXNoYm9hcmRcXGxheW91dC5weSIsImlzVW50aXRsZWQiOmZhbHNlLCJsYW5ndWFnZUlkIjoicHl0aG9uIiwidmVyc2lvbiI6MiwiaXNDbG9zZWQiOmZhbHNlLCJpc0RpcnR5IjpmYWxzZSwiZW9sIjoyLCJsaW5lQ291bnQiOjc3Nn0sInZpZXdDb2x1bW4iOjEsImZvY3Vzc2VkIjpmYWxzZX0seyJkb2N1bWVudCI6eyJ1cmkiOnsiJG1pZCI6MSwiZnNQYXRoIjoiZDpcXHNvdXJjZVxccmVwb3NcXFByb1NBVERhc2hib2FyZFxcRmVlZGJhY2tfQW5hbHlzaXNfRGFzaGJvYXJkXFxjYWxsYmFja3MucHkiLCJfc2VwIjoxLCJleHRlcm5hbCI6ImZpbGU6Ly8vZCUzQS9zb3VyY2UvcmVwb3MvUHJvU0FURGFzaGJvYXJkL0ZlZWRiYWNrX0FuYWx5c2lzX0Rhc2hib2FyZC9jYWxsYmFja3MucHkiLCJwYXRoIjoiL0Q6L3NvdXJjZS9yZXBvcy9Qcm9TQVREYXNoYm9hcmQvRmVlZGJhY2tfQW5hbHlzaXNfRGFzaGJvYXJkL2NhbGxiYWNrcy5weSIsInNjaGVtZSI6ImZpbGUifSwiZmlsZU5hbWUiOiJkOlxcc291cmNlXFxyZXBvc1xcUHJvU0FURGFzaGJvYXJkXFxGZWVkYmFja19BbmFseXNpc19EYXNoYm9hcmRcXGNhbGxiYWNrcy5weSIsImlzVW50aXRsZWQiOmZhbHNlLCJsYW5ndWFnZUlkIjoicHl0aG9uIiwidmVyc2lvbiI6MTEsImlzQ2xvc2VkIjpmYWxzZSwiaXNEaXJ0eSI6ZmFsc2UsImVvbCI6MiwibGluZUNvdW50IjoyMDUyfSwidmlld0NvbHVtbiI6MiwiZm9jdXNzZWQiOmZhbHNlfV19LHsibmFtZSI6IkJyYW5jaDogYW5zYWxjZWQvaW50ZWxsaWdlbnQtdG9waWNzIiwibGlzdCI6W3siZG9jdW1lbnQiOnsidXJpIjp7IiRtaWQiOjEsImZzUGF0aCI6ImM6XFxVc2Vyc1xcYW5zYWxjZWRcXE9uZURyaXZlIC0gTWljcm9zb2Z0XFxBTVBMSUZZXFxQcm9qZWN0c1xcU2lnbmFsc0FuZFN1cnZleXNcXFRhc2tQYW5lU3VydmV5QW5hbHlzaXNcXE1MQW5hbHlzaXNFeGNlbC5weSIsIl9zZXAiOjEsImV4dGVybmFsIjoiZmlsZTovLy9jJTNBL1VzZXJzL2Fuc2FsY2VkL09uZURyaXZlJTIwLSUyME1pY3Jvc29mdC9BTVBMSUZZL1Byb2plY3RzL1NpZ25hbHNBbmRTdXJ2ZXlzL1Rhc2tQYW5lU3VydmV5QW5hbHlzaXMvTUxBbmFseXNpc0V4Y2VsLnB5IiwicGF0aCI6Ii9jOi9Vc2Vycy9hbnNhbGNlZC9PbmVEcml2ZSAtIE1pY3Jvc29mdC9BTVBMSUZZL1Byb2plY3RzL1NpZ25hbHNBbmRTdXJ2ZXlzL1Rhc2tQYW5lU3VydmV5QW5hbHlzaXMvTUxBbmFseXNpc0V4Y2VsLnB5Iiwic2NoZW1lIjoiZmlsZSJ9LCJmaWxlTmFtZSI6ImM6XFxVc2Vyc1xcYW5zYWxjZWRcXE9uZURyaXZlIC0gTWljcm9zb2Z0XFxBTVBMSUZZXFxQcm9qZWN0c1xcU2lnbmFsc0FuZFN1cnZleXNcXFRhc2tQYW5lU3VydmV5QW5hbHlzaXNcXE1MQW5hbHlzaXNFeGNlbC5weSIsImlzVW50aXRsZWQiOmZhbHNlLCJsYW5ndWFnZUlkIjoicHl0aG9uIiwidmVyc2lvbiI6NTIxMSwiaXNDbG9zZWQiOnRydWUsImlzRGlydHkiOmZhbHNlLCJlb2wiOjIsImxpbmVDb3VudCI6NDE3fSwidmlld0NvbHVtbiI6MSwiZm9jdXNzZWQiOmZhbHNlLCJwaW5uZWQiOmZhbHNlfV19LHsibmFtZSI6IkJyYW5jaDogYW5zYWxjZWQvY29tYmluZWQtdGVtcCIsImxpc3QiOlt7ImRvY3VtZW50Ijp7InVyaSI6eyIkbWlkIjoxLCJmc1BhdGgiOiJjOlxcVXNlcnNcXGFuc2FsY2VkXFxPbmVEcml2ZSAtIE1pY3Jvc29mdFxcQU1QTElGWVxcUHJvamVjdHNcXFNpZ25hbHNBbmRTdXJ2ZXlzXFxUYXNrUGFuZVN1cnZleUFuYWx5c2lzXFxkZWJpYXNlZE1MLnB5IiwiX3NlcCI6MSwiZXh0ZXJuYWwiOiJmaWxlOi8vL2MlM0EvVXNlcnMvYW5zYWxjZWQvT25lRHJpdmUlMjAtJTIwTWljcm9zb2Z0L0FNUExJRlkvUHJvamVjdHMvU2lnbmFsc0FuZFN1cnZleXMvVGFza1BhbmVTdXJ2ZXlBbmFseXNpcy9kZWJpYXNlZE1MLnB5IiwicGF0aCI6Ii9jOi9Vc2Vycy9hbnNhbGNlZC9PbmVEcml2ZSAtIE1pY3Jvc29mdC9BTVBMSUZZL1Byb2plY3RzL1NpZ25hbHNBbmRTdXJ2ZXlzL1Rhc2tQYW5lU3VydmV5QW5hbHlzaXMvZGViaWFzZWRNTC5weSIsInNjaGVtZSI6ImZpbGUifSwiZmlsZU5hbWUiOiJjOlxcVXNlcnNcXGFuc2FsY2VkXFxPbmVEcml2ZSAtIE1pY3Jvc29mdFxcQU1QTElGWVxcUHJvamVjdHNcXFNpZ25hbHNBbmRTdXJ2ZXlzXFxUYXNrUGFuZVN1cnZleUFuYWx5c2lzXFxkZWJpYXNlZE1MLnB5IiwiaXNVbnRpdGxlZCI6ZmFsc2UsImxhbmd1YWdlSWQiOiJweXRob24iLCJ2ZXJzaW9uIjo0MTgsImlzQ2xvc2VkIjp0cnVlLCJpc0RpcnR5IjpmYWxzZSwiZW9sIjoyLCJsaW5lQ291bnQiOjE4OX0sInZpZXdDb2x1bW4iOjEsImZvY3Vzc2VkIjpmYWxzZSwicGlubmVkIjpmYWxzZX0seyJkb2N1bWVudCI6eyJ1cmkiOnsiJG1pZCI6MSwiZnNQYXRoIjoiYzpcXFVzZXJzXFxhbnNhbGNlZFxcT25lRHJpdmUgLSBNaWNyb3NvZnRcXEFNUExJRllcXFByb2plY3RzXFxTaWduYWxzQW5kU3VydmV5c1xcVGFza1BhbmVTdXJ2ZXlBbmFseXNpc1xcYW5hbHlzaXNBcHBzLnB5IiwiX3NlcCI6MSwiZXh0ZXJuYWwiOiJmaWxlOi8vL2MlM0EvVXNlcnMvYW5zYWxjZWQvT25lRHJpdmUlMjAtJTIwTWljcm9zb2Z0L0FNUExJRlkvUHJvamVjdHMvU2lnbmFsc0FuZFN1cnZleXMvVGFza1BhbmVTdXJ2ZXlBbmFseXNpcy9hbmFseXNpc0FwcHMucHkiLCJwYXRoIjoiL2M6L1VzZXJzL2Fuc2FsY2VkL09uZURyaXZlIC0gTWljcm9zb2Z0L0FNUExJRlkvUHJvamVjdHMvU2lnbmFsc0FuZFN1cnZleXMvVGFza1BhbmVTdXJ2ZXlBbmFseXNpcy9hbmFseXNpc0FwcHMucHkiLCJzY2hlbWUiOiJmaWxlIn0sImZpbGVOYW1lIjoiYzpcXFVzZXJzXFxhbnNhbGNlZFxcT25lRHJpdmUgLSBNaWNyb3NvZnRcXEFNUExJRllcXFByb2plY3RzXFxTaWduYWxzQW5kU3VydmV5c1xcVGFza1BhbmVTdXJ2ZXlBbmFseXNpc1xcYW5hbHlzaXNBcHBzLnB5IiwiaXNVbnRpdGxlZCI6ZmFsc2UsImxhbmd1YWdlSWQiOiJweXRob24iLCJ2ZXJzaW9uIjo3MjQsImlzQ2xvc2VkIjp0cnVlLCJpc0RpcnR5IjpmYWxzZSwiZW9sIjoyLCJsaW5lQ291bnQiOjI5Mn0sInZpZXdDb2x1bW4iOjEsImZvY3Vzc2VkIjp0cnVlLCJwaW5uZWQiOmZhbHNlfSx7ImRvY3VtZW50Ijp7InVyaSI6eyIkbWlkIjoxLCJmc1BhdGgiOiJjOlxcVXNlcnNcXGFuc2FsY2VkXFxPbmVEcml2ZSAtIE1pY3Jvc29mdFxcQU1QTElGWVxcUHJvamVjdHNcXFNpZ25hbHNBbmRTdXJ2ZXlzXFxUYXNrUGFuZVN1cnZleUFuYWx5c2lzXFxTY3Jld0RyaXZlci5weSIsIl9zZXAiOjEsImV4dGVybmFsIjoiZmlsZTovLy9jJTNBL1VzZXJzL2Fuc2FsY2VkL09uZURyaXZlJTIwLSUyME1pY3Jvc29mdC9BTVBMSUZZL1Byb2plY3RzL1NpZ25hbHNBbmRTdXJ2ZXlzL1Rhc2tQYW5lU3VydmV5QW5hbHlzaXMvU2NyZXdEcml2ZXIucHkiLCJwYXRoIjoiL2M6L1VzZXJzL2Fuc2FsY2VkL09uZURyaXZlIC0gTWljcm9zb2Z0L0FNUExJRlkvUHJvamVjdHMvU2lnbmFsc0FuZFN1cnZleXMvVGFza1BhbmVTdXJ2ZXlBbmFseXNpcy9TY3Jld0RyaXZlci5weSIsInNjaGVtZSI6ImZpbGUifSwiZmlsZU5hbWUiOiJjOlxcVXNlcnNcXGFuc2FsY2VkXFxPbmVEcml2ZSAtIE1pY3Jvc29mdFxcQU1QTElGWVxcUHJvamVjdHNcXFNpZ25hbHNBbmRTdXJ2ZXlzXFxUYXNrUGFuZVN1cnZleUFuYWx5c2lzXFxTY3Jld0RyaXZlci5weSIsImlzVW50aXRsZWQiOmZhbHNlLCJsYW5ndWFnZUlkIjoicHl0aG9uIiwidmVyc2lvbiI6MSwiaXNDbG9zZWQiOnRydWUsImlzRGlydHkiOmZhbHNlLCJlb2wiOjIsImxpbmVDb3VudCI6MjIxfSwidmlld0NvbHVtbiI6MSwiZm9jdXNzZWQiOmZhbHNlLCJwaW5uZWQiOmZhbHNlfSx7ImRvY3VtZW50Ijp7InVyaSI6eyIkbWlkIjoxLCJmc1BhdGgiOiJjOlxcVXNlcnNcXGFuc2FsY2VkXFxPbmVEcml2ZSAtIE1pY3Jvc29mdFxcQU1QTElGWVxcUHJvamVjdHNcXFNpZ25hbHNBbmRTdXJ2ZXlzXFxUYXNrUGFuZVN1cnZleUFuYWx5c2lzXFxmdW5jdGlvbnMucHkiLCJfc2VwIjoxLCJleHRlcm5hbCI6ImZpbGU6Ly8vYyUzQS9Vc2Vycy9hbnNhbGNlZC9PbmVEcml2ZSUyMC0lMjBNaWNyb3NvZnQvQU1QTElGWS9Qcm9qZWN0cy9TaWduYWxzQW5kU3VydmV5cy9UYXNrUGFuZVN1cnZleUFuYWx5c2lzL2Z1bmN0aW9ucy5weSIsInBhdGgiOiIvYzovVXNlcnMvYW5zYWxjZWQvT25lRHJpdmUgLSBNaWNyb3NvZnQvQU1QTElGWS9Qcm9qZWN0cy9TaWduYWxzQW5kU3VydmV5cy9UYXNrUGFuZVN1cnZleUFuYWx5c2lzL2Z1bmN0aW9ucy5weSIsInNjaGVtZSI6ImZpbGUifSwiZmlsZU5hbWUiOiJjOlxcVXNlcnNcXGFuc2FsY2VkXFxPbmVEcml2ZSAtIE1pY3Jvc29mdFxcQU1QTElGWVxcUHJvamVjdHNcXFNpZ25hbHNBbmRTdXJ2ZXlzXFxUYXNrUGFuZVN1cnZleUFuYWx5c2lzXFxmdW5jdGlvbnMucHkiLCJpc1VudGl0bGVkIjpmYWxzZSwibGFuZ3VhZ2VJZCI6InB5dGhvbiIsInZlcnNpb24iOjYzMywiaXNDbG9zZWQiOnRydWUsImlzRGlydHkiOmZhbHNlLCJlb2wiOjIsImxpbmVDb3VudCI6NDMzfSwidmlld0NvbHVtbiI6MSwiZm9jdXNzZWQiOmZhbHNlLCJwaW5uZWQiOmZhbHNlfV19XQ==",
    "python.languageServer": "Pylance",
    "python.formatting.autopep8Args": [
        "--max-line-length",
        "120"
    ],
    "settingsSync.ignoredSettings": [],
    "jupyter.textOutputLimit": 0,
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook"
    },
    "notebook.cellToolbarLocation": {
        "default": "right",
        "jupyter-notebook": "left"
    },
    "workbench.statusBar.visible": false,
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "himanoa.Python-autopep8",
}

**Comment by jrieken** [comment]
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |
