### ISSUE TITLE
Themes config in personnal JSON settings are not loaded on startup

### ISSUE THREAD

**Issue by Llacoste2000** [microsoft/vscode#138044]
Issue Type: <b>Bug</b>

I have modified my theme on my settings (JSON) file, VSCode is not loading my theme settings on startup.

Reproduce :
1 - install a theme + edit it with settings in personnal JSON settings file (key "workbench.colorCustomizations" in the settings)
2 - restart vscode, new theme customizations will not be loaded

awsome job <3

VS Code version: Code - Insiders 1.63.0-insider (1e473b624f088fc05269891170a8ffa1c84a35a6, 2021-11-25T07:59:54.812Z)
OS version: Linux x64 5.10.79-1-MANJARO snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|15.48GB (5.09GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 1d1b99cd-c37f-44b2-bf61-8142b1a63249|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (79)</summary>

Extension|Author (truncated)|Version
---|---|---
alpine-js-intellisense|adr|1.2.0
TabOut|alb|0.2.1
flutter-snippets|ale|3.0.0
laravel-extra-intellisense|ami|0.6.1
vscode-color|ans|0.4.5
swagger-viewer|Arj|3.1.2
vscode-styled-jsx|bla|2.1.1
vscode-intelephense-client|bme|1.7.1
git-exclude|bou|0.2.1
vscode-tailwindcss|bra|0.7.2
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.5.0
regex|chr|0.4.0
vscode-css-modules|cli|0.4.0
gitignore|cod|0.7.0
bracket-pair-colorizer-2|Coe|0.2.1
vscode-svgviewer|css|2.0.0
dart-code|Dar|3.28.0
flutter|Dar|3.28.0
vscode-eslint|dba|2.2.2
vscode-styled-jsx-languageserver|Div|1.3.0
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
php-debug|fel|1.22.0
auto-rename-tag|for|0.1.9
vscode-mysql|for|0.4.1
vscode-pull-request-github|Git|0.32.0
todo-tree|Gru|0.0.214
ftp-simple|hum|0.7.6
search-node-modules|jas|1.3.0
vue|jcb|0.1.5
svg|joc|1.4.14
node-module-intellisense|lei|1.5.0
MagicPython|mag|1.1.0
php-constructor|Meh|0.1.2
php-namespace-resolver|Meh|1.1.8
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.18.0
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.206.0
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.63.2
vscode-typescript-next|ms-|4.6.20211126
vsliveshare|ms-|1.0.5090
vsliveshare-audio|ms-|0.1.91
sqltools|mtx|0.23.0
awesome-flutter-snippets|Nas|3.0.2
php-docblocker|nei|2.6.1
vetur|oct|0.35.0
laravel-blade|one|1.28.0
vscode-php-getters-setters|php|1.2.3
material-icon-theme|PKi|4.11.0
nextjs-snippets|Pul|0.0.5
vscode-thunder-client|ran|1.9.1
vscode-yaml|red|1.2.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
color-manager|roy|0.6.3
code-settings-sync|Sha|3.4.3
vscode-hexdump|sle|1.8.1
sass-indented|syl|1.8.18
es6-string-html|Tob|2.12.0
vscodeintellicode|Vis|1.2.14
gistfs|vsl|0.3.0
nodejs-extension-pack|wad|0.1.9
vscode-todo-highlight|way|1.0.5
twig|wha|1.0.2
glean|wix|5.2.2
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0
local-history|xyz|1.8.1
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythontb:30258533
vsc_aacf:30263846
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593cf:30376535
vsc1dst:30396469
pythonvs932:30404738
vscexrecpromptt2:30397559
vscop804cf:30404767
vscop940:30404999

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

> in personnal JSON settings file

Do you mean in main (User) `settings.json` and not in `.vscode/settings.json` in a workspace?

Do you see any errors/problems reported when you open this JSON file? (View > Problems should show all errors for opened file)
Are other settings from this file applied as expected?

Please also provide example of color customization code - I was unable to reproduce this problem except case when I have duplicate entries of `workbench.colorCustomizations`

Also you can check if it is reproducible with all extensions disabled. You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`
