### ISSUE TITLE
Syntax Coloring C - Variable recognition problem

### ISSUE THREAD

**Issue by MoonChasing** [microsoft/vscode#138026]
After a new upgrade, the variable could not be recognized. In the developer tools, it changed from the original `mtk3` to `mtk1`. This causes the color of my code variable to fail to render.

For example, before this upgrade, the color of variable is as same as user_data in this code, but now ,its' color is white because `mtk1` class.
![image](https://user-images.githubusercontent.com/27677938/143808569-6d854635-06ba-4a0e-8e32-e509baf15d21.png)
![image](https://user-images.githubusercontent.com/27677938/143808877-5eb63d6c-fecf-40ea-a011-569231f6ce67.png)
![image](https://user-images.githubusercontent.com/27677938/143808886-194829d3-83a0-4cd6-914f-2d0a9ffb4bc0.png)

**Comment by alexr00** [comment]
@MoonChasing can you please provide a copy/pastable sample that I can reproduce the issue with?

**Comment by MoonChasing** [comment]
> @MoonChasing can you please provide a copy/pastable sample that I can reproduce the issue with?

The example in my picture comes from [https://github.com/sogou/workflow/blob/master/tutorial/tutorial-11-graph_task.cc](https://github.com/sogou/workflow/blob/master/tutorial/tutorial-11-graph_task.cc).

 But in any code, the variables I define cannot be recognized normally.  For example:
```C
int main()
{
    int a;
    return 0;
}
```
The variable `a` cannot be recognized. But the members of the structure can be recognized.

![image](https://user-images.githubusercontent.com/27677938/143845490-eb6c5f4f-a0a5-4a1d-b9cf-79fb67e1a706.png)

**Comment by alexr00** [comment]
I went back to version 1.60.2, and I didn't see any difference in that sample. The issue is likely due to a change in the C/C++ extension or the theme you're using.

**Comment by MoonChasing** [comment]
OK, thanks.  Let me see what makes `mtk3` become `mtk1`.

**Comment by MoonChasing** [comment]
Sorry for taking up your time, it is a change of the theme I use.

**Comment by MoonChasing** [comment]
> I went back to version 1.60.2, and I didn't see any difference in that sample. The issue is likely due to a change in the C/C++ extension or the theme you're using.

Sorry for taking up your time. It was caused by a change in the theme I used.
