### ISSUE TITLE
cap_net_bind_service and vscode debugger

### ISSUE THREAD

**Issue by dleeq8** [microsoft/vscode#138064]
- VS Code Version: (vscodium)
- Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-09T15:54:41.116Z
Electron: 12.0.4
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.11.0-38-generic snap
- OS Version: ubuntu 20.04

**when using this command to let me use port 80 without root**
```sudo setcap 'cap_net_bind_service=+ep' `which node` ```
**will cause debugger and logs stop working**

**and when reset cap_net_bind_service**
```sudo setcap 'cap_net_bind_service=-ep' `which node` ```
**everything work fine ..**

not sure if this count as "bug" or not.. but showing warnings about "cap_net_bind_service" settings will help

**Comment by connor4312** [comment]
See https://github.com/nodejs/node/issues/37588

Duplicates https://github.com/microsoft/vscode-js-debug/issues/852
