### ISSUE TITLE
Terminal: "after all" hook in "Terminal"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138049]
```
VSCode Smoke Tests (Web)
       Terminal
         "after all" hook in "Terminal":
     Error: Smoke test exit call did not terminate process after 20s, giving up
      at D:\a\1\s\test\automation\out\code.js:110:32

```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=144638&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=9302e8c4-de85-5274-34fa-935ce79d4e8d&l=118

**Comment by Tyriar** [comment]
@bpasero is this not just https://github.com/microsoft/vscode/issues/137725 after your refactors?

**Comment by bpasero** [comment]
I wanted to file this issue as separate issue because it hints into a direction where we fail to terminate the server (we use `tree-kill` to kill hits entire hierarchy). I am not sure though there is a clear correlation...

**Comment by Tyriar** [comment]
Log in https://dev.azure.com/monacotools/Monaco/_build/results?buildId=145526&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=9302e8c4-de85-5274-34fa-935ce79d4e8d shows:

```
Stopping playwright trace took >5seconds
      1) "after all" hook in "Terminal"
```

**Comment by bpasero** [comment]
Hm yeah I added that kind of logging recently. If we figure out that there is a correlation to the terminal issue here, I am fine changing the tracing to give up after 10s or so, but I wonder what that means...

**Comment by bpasero** [comment]
Work in https://github.com/microsoft/vscode/tree/ben/pw-trace-per-test happens to:
* trace per test and not suite (noticed how terminal tests seem to be one big suite, so tracing might end up very time intense)
* do not store trace to disk when test succeeded

**Comment by Tyriar** [comment]
Nothing useful in the CI logs, I would have expected the playwright trace to contain console messages but it's empty.

New theory: disposing the terminals at the end of each test is triggered async on the remote side but we don't await it. I'll try listen for confirmation from remote that the process has been killed before resolving the "kill all" command.

**Comment by Tyriar** [comment]
Pushed that change 🤞

**Comment by bpasero** [comment]
I have not seen this issue yesterday. 🤞

**Comment by Tyriar** [comment]
I think we can safely call this fixed 🎉 

![image](https://user-images.githubusercontent.com/2193314/145595638-c843ad33-3cf4-4f07-b75c-434b9cc7fdb1.png)

Let's reopen if we see it again on the main branch.
