### ISSUE TITLE
Impossible to tell local and remote copies of recent project when connected to remote

### ISSUE THREAD

**Issue by jordan-schneider** [microsoft/vscode#138099]
When connected to a remote computer, recent projects on both the current remote computer and on your local machine don't have a connection suffix (e.g. "[SSH: hostname]"), making it sometimes impossible to tell which you are about to open. Either projects on the remote server should continue to have the connection suffix, or projects on your local machine should have a suffix indicating e.g. [localhost]

- VSCode Version: 1.62.2
- Local OS Version: Ubuntu 20.04.3
- Remote OS Version: Ubuntu 18.04.5
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Have a workspace in the same location on your local and remote computer
2. Open the workspace locally
3. Connect to the remote computer
4. Open the workspace on the remote computer
5. Close the workspace
5. Open the File -> Open Recent menu

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by aeschli** [comment]
I can't reproduce in the latest build
