### ISSUE TITLE
Can't type anything on coding window

### ISSUE THREAD

**Issue by jerryben** [microsoft/vscode#138034]
Issue Type: <b>Bug</b>

I am using linux mint and before now everything was fine until i did an upgrade, with every subsequent upgrade the problem persisted. In the coding window i have a blinking cursor but it doesn't allow me type anything. can't just enter any code, no keystroke registers on my coding window.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.4.0-90-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|7.66GB (2.19GB free)|
|Process Argv|--verion --crash-reporter-id a880b9f9-708f-4d11-9ff9-bfd821c6d00c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
project-manager|ale|12.4.0
solidity-extended|bea|3.0.2
vscode-node-readme|ben|3.0.2
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.5.0
js-codeformer|cms|2.6.1
jsrefactor|cms|3.0.1
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.2.2
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.7.0
vscode-npm-script|eg2|0.3.23
react-native-react-redux|EQu|2.0.6
defi-ls|eri|0.0.5
prettier-vscode|esb|9.0.0
auto-close-tag|for|0.5.13
rest-client|hum|0.24.5
plantuml|jeb|2.16.1
solidity|Jua|0.0.136
vscode-language-babel|mgm|0.0.35
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
debugger-for-chrome|msj|4.13.0
polacode|pnp|0.3.4
vscode-css-peek|pra|4.2.0
quicktype|qui|12.0.46
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
open-in-browser|tec|2.0.0
graphviz-interactive-preview|tin|0.0.12
solidity-visual-auditor|tin|0.1.0
vscode-ethover|tin|0.0.7
vscode-inline-bookmarks|tin|0.0.25
vscode-solidity-flattener|tin|0.0.10
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.7.0
vim|vsc|1.21.10
quokka-vscode|Wal|1.0.427
vscode-import-cost|wix|2.15.0
JasmineSnippets|xab|1.0.1
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.13.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593cf:30376535
vssld246:30401890
vscexrecpromptt2:30404948
vscop804cf:30404767
vs360cf:30404996

```

</details>

**Comment by gjsjohnmurray** [comment]
Please run the `Start Extension Bisect` command from Command Palette to check whether one of your extensions is causing this.

**Comment by jerryben** [comment]
After i ran the start extension bisect VIM was actually identified as the cause of the problem am experiencing, thanks. below is the attached details.

Issue Type: <b>Bug</b>

After a start extension bisect, vim was identified as the extention causing the problem, it doesn't permit any keystroke to be registered on my code windows each time the appliacation is started.

Extension version: 1.21.10
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.4.0-90-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2815)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.66GB (5.32GB free)|
|Process Argv|--unity-launch --crash-reporter-id a880b9f9-708f-4d11-9ff9-bfd821c6d00c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593cf:30376535
vssld246:30401890
vscexrecpromptt2:30404948
vscop804cf:30404767
vs360cf:30404996

```

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Please report this to the extension author. One way to do that is by picking the correct dropdown item in the Report Issue dialog launched from the Help menu.
