### ISSUE TITLE
Cannot create new file using remote cli

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#138089]
- VS Code Version: insiders and from sources

Steps to Reproduce:

1. run vscode server
2. open terminal and type `code new_file` to open a new file
3. :bug: nothing happens

Seems a regression from this PR https://github.com/microsoft/vscode/pull/136359
cc @bpasero

**Comment by lszomoru** [comment]
Duplicate of #137409. This should be fixed in today's Insider release.
