### ISSUE TITLE
QuickPick : Ordered Selection

### ISSUE THREAD

**Issue by DTHaydon** [microsoft/vscode#138073]
There are currently two modes of operation for QuickPick: Single selection and Multiple selection.
With multiple selection, the returned selected items are in the order in which they are listed in the dropdown menu.
In some cases, the order in which the selected items are used is also important and I see no mechanism for the user to specify this information.

Allowing ordered selection actually introduces two new modes of operation for QuickPick :

1. All the items must be used and can be ordered as the user wishes
2. Any number of items can be selected and these selected items can be ordered as the user wishes

A click and drag mechanism for ordering the items would be the most user friendly; however, I imagine that this is incompatible with the current selection menu code.

For the first of the two new modes of operation, I cannot see any other method in which the user could provide information about the order.

However, for the second of the two new modes of operation, the most straightforward approach would be to keep track of the order in which the items are selected. 
Prefixing the label with a number would indicate the order in which it would be used.

**Comment by TylerLeonhardt** [comment]
@DTHaydon this would need an API addition which we usually only do if there's a large demand for it. Did you have a specific scenario in mind that you wanted to make but couldn't because this API doesn't exist?

**Comment by DTHaydon** [comment]
@TylerLeonhardt 
Of the two new selection modes I mentioned:
- the first (use all items but can reorder) I have not encountered a need for and would probably require an API addition.
- the second (select and order) I have wanted to use (and have been able to implement in some form)

For my original implementation of the ordered selection, I tracked the order in which items were selected.
However, this was inconvenient if an item was forgotten and where a click and drag feature would have been helpful.
With release 1.63 (individual QuickPickItem buttons) and the API Proposals: `quickPickSeparators` and `quickPickSortByLabel` it is possible to implement something more user friendly:

https://user-images.githubusercontent.com/15086793/145851629-c332b03e-447c-481d-b398-fb271b452591.mov

**Comment by image72** [comment]
quick pick list chaos sort
![image](https://user-images.githubusercontent.com/243154/146528975-48623597-df3d-4a5e-8083-1d863971fdd0.png)
