### ISSUE TITLE
Per window Zoom In/Out 

### ISSUE THREAD

**Issue by OmgImAlexis** [microsoft/vscode#138041]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.3
- OS Version: Linux x64 15.5-arch1-1

Steps to Reproduce:
  1. Open two instances (Windows) of VSCode
  2. In each instance, browse to some different code
  3. In one instance use the Ctrl-+ or Ctrl-- (View:Zoom In or View:Zoom Out)
  4. Notice that the Zoom level changes not only in the open window, but also in all the other VSCode instances
  
Same issue as https://github.com/Microsoft/vscode/issues/35913 which was closed "as-designed". It's been 4 years since this was closed, is there any chance this could be reconsidered? Currently this forces me to change zoom every time I switch between monitors as I have my main at 4k and my secondary at 1440x900

**Comment by bpasero** [comment]
Workspace setting maybe?

**Comment by OmgImAlexis** [comment]
@bpasero you mean to enable per window zoom?

**Comment by bpasero** [comment]
Yeah the `window.zoomLevel` setting can be configured per workspace, i.e. different per different workspace windows.
