### ISSUE TITLE
VSCode Smoke Tests (Electron)        Data Migration (stable -> insiders)          verifies that 'hot exit' works for dirty files

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#138055]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=144657&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=0699ae84-7245-5a45-5eee-80b086af2725

**Comment by bpasero** [comment]
Yup, on it via some logging...
