### ISSUE TITLE
Can't preview icon themes from marketplace based on gifs

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#138082]
- open the `Preferences: File Icon Themes` command and select `Browse Additional Color Themes`
- use the cursors to go through the themes. Note that some themes do not seem to load
- The dev tools console says: `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`

SVGs from the unpackage service are blocked for security reasons.

**Comment by isidorn** [comment]
If we can not fix this should we fine tune the place holder text such that it does not say "Use up/down to preview" since we know it does not work for icon themes.
I could not get any icon theme to properly preview.

**Comment by aeschli** [comment]
We have removed `Browse Additional Color Themes` from the File Icon theme picker as we can't work around the SVG limitation and most icon themes use SVG
