### ISSUE TITLE
Feature: Import module using alias as path if there is one

### ISSUE THREAD

**Issue by lucasbasquerotto** [microsoft/vscode#138067]
I want to request the option to auto-import typescript files in vscode using the **alias** as specified at `paths` in `tsconfig.json`, otherwise use a **relative path**. The related setting is `typescript.preferences.importModuleSpecifier`.

None of the options works this way. The closest is `project-relative`, but it only works if all aliases are outside the project. I want that all paths that satisfy an alias to use the alias, but without having to use absolute imports for other paths (those should be relative). The preferred way would be **alias followed by relative**.

Thanks.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

**Comment by lucasbasquerotto** [comment]
@mjbvz I created the related issue https://github.com/microsoft/TypeScript/issues/47053.
