### ISSUE TITLE
Test pre-release extensions as an end user

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#138086]
Ref #15756

- [x] Mac @tanhakabir
- [x] Win @jrieken
- [x] Linux @karthiknadig

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23138086%0A%0A&assignees=sandy081)

---

As a user, you can choose to install pre-release version of an extension.

Please read following before starting testing

**Note 1:** Pre-release versions are shown only if they are newer than the newest released version. 
**Note 2:** Use internal setting `_extensions.preferPreReleases` to disable VS Code insiders preferring pre-release versions  - Reload window required for the change to take affect
**Note 3:** Use `sandy081.998-test-code` or `github.vscode-pull-request-github` extensions for testing

Please test following:

Test browsing and installing extensions with pre-release versions 

- Test the representation of these extension in the extension view, hover and extension editor. Pre-release bookmark, badge & indicator are used to represent that extension has a pre-release or is pre-release.
- Test that the primary action to install the extension is to install the pre-release and the secondary action is to install the release version. Test these actions are working as expected.
- Disable `_extensions.preferPreReleases` setting (reload window) and test that primary action is to install the release version and secondary action is to install the pre-release version.
- Test that you can switch between release and pre-release versions using the actions `Switch to....` action that is available in the extension editor and extension context menu in extensions view.
- Test uninstalling and installing the extension works as expected.
- Test that you can browse and install previous versions of the extension using `Install Another Version...` action

Test Settings Sync:

- Open two VS Code Insiders instances using two different user data directories and extensions directories. Use `--user-data-dir` and `--extensions-dir` from command line.
- Enable settings sync on both instances
- Make sure installing pre-release/released version on one instance, installs the same pre-release/released version on another instance

Test Auto Migration

- Uninstall GitHub Pull Requests & Issues extension 
- Quit VS Code Insiders
- Download the old [GitHub Pull Requests & Issues nightly](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders) extension VSIX  from the Marketplace - Use the Download link in the resources section
- Install the above downloaded VSIX from the command line - `code-insiders --install-extension <vsix_path>`
- Open VS Code Insiders
- Make sure that GitHub Pull Requests & Issues nightly extension is uninstalled and main GitHub Pull Requests & Issues is installed - Reloading the window will enable the main extension

**Comment by karthiknadig** [comment]
I ran into #138130 as well. This seems to occur when several extension editor tabs get opened (like when you click show recommended). Manually re-opening it seems to fix it for me.

Other than that, it works well. Thanks for the feature.
