### ISSUE TITLE
hover over bracket in terminal does not attempt to match corresponding closing bracket

### ISSUE THREAD

**Issue by gilescope** [microsoft/vscode#138003]
It would be super helpful and cool and you only have to do processing if your hovering over a bracket of some sort.... just find the corresponding bracket just based on brackets of that type.

**Comment by gilescope** [comment]
it currently detects links that are hovered over, so this is not that big a leap.

**Comment by gilescope** [comment]
So wait, the only way to make vscode better is to continually monitor for
new issues and upvote them? This seems really helpful but just has no
publicity. Did a dev read it?

**Comment by Tyriar** [comment]
@gilescope yes multiple people on the team read it. Keep in mind that this is one request out of thousands, consider where this is positions in the list of all requests sorted by upvotes (ie. _the_ community signal for priority).
