### ISSUE TITLE
"Run Tests in Current File" only runs the first test in the file (for C++ tests)

### ISSUE THREAD

**Issue by stefanhaller** [microsoft/vscode#138007]
- VS Code Version: 1.62.3

With the C++ TestMate extension, for a source file with multiple test cases, running the command "Run Tests in Current File" only runs the first test in the file, not all of them.

It's easy to see why this happens: the [`ExecuteTestsInCurrentFile.run()`](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/testing/browser/testExplorerActions.ts#L812) method looks for tests matching the URI, and as soon as it finds one, it runs it and returns.

I suppose this is done with the assumption that there will always be a TestItem for the entire file (with sub items for the individual tests); this is not the case for the C++ TestMate extension.

Would it be a problem to run _all_ tests matching the URI, making it the extension's responsibility to deduplicate as necessary? From the discussion in #133519 I get the feeling that extensions have to do this deduplication already, anyway.

I tried the following simple patch, and it fixes the problem for the C++ extension; and for the Python extension it still works with this patch (it worked before too, because the Python extension does add a test node for the entire file).

```diff
diff --git a/src/vs/workbench/contrib/testing/browser/testExplorerActions.ts b/src/vs/workbench/contrib/testing/browser/testExplorerActions.ts
index c49e2511ded..baad17fd4e4 100644
--- a/src/vs/workbench/contrib/testing/browser/testExplorerActions.ts
+++ b/src/vs/workbench/contrib/testing/browser/testExplorerActions.ts
@@ -851,16 +851,12 @@ abstract class ExecuteTestsInCurrentFile extends Action2 {
 		const testService = accessor.get(ITestService);
 
 		const demandedUri = model.uri.toString();
-		for (const test of testService.collection.all) {
-			if (test.item.uri?.toString() === demandedUri) {
-				return testService.runTests({
-					tests: [test],
-					group: this.group,
-				});
-			}
-		}
-
-		return undefined;
+		const tests = Array.from(testService.collection.all).filter(
+			t => t.item.uri?.toString() === demandedUri);
+		return testService.runTests({
+			tests: tests,
+			group: this.group,
+		});
 	}
 }
 
```

Ping @connor4312

**Comment by rchiodo** [comment]
I can't repro this in stable so not sure what the steps are to cause the issue.

Perhaps @stefanhaller can verify? Please add a 'verified' label if you can verify this is fixed in the latest insiders. Thanks.

**Comment by stefanhaller** [comment]
> I can't repro this in stable so not sure what the steps are to cause the issue.

@rchiodo It is not as easy to reproduce in stable any more as it used to be back then, because there's now a workaround in the C++ TestMate extension. To reproduce it, you need a test executable with more than one .cpp file, and then test it in the second of those.

But yes, I can confirm that it's fixed in the current insiders.
