### ISSUE TITLE
How to change VS Code skin?

### ISSUE THREAD

**Issue by Natanael1234** [Microsoft/vscode#13804]
How could I change the theme of VC Code? 

By theme I mean the skin of the whole application, not just the editor colors.

**Comment by isidorn** [comment]
F1 > theme > choose your theme
or
Preferences > color theme

**Comment by Semmu** [comment]
Why did you close this question? It is clearly not answered.
(He asks about theming the **whole editor**, not just about changing the file icons or font colors, as you "answered".)

**Comment by isidorn** [comment]
That is currently not supported - you can file a feature request for that.

Thank you

**Comment by Natanael1234** [comment]
Semmu, in fact the answer is partially right.  F1 > theme > choose your theme allows to choose themes which can choose almost the whole interface. Fox example, "Light (Visual Studio)" theme changes the most of the ui while "Material Neutral" changes only the editor.


Anyway, my question could be better formulated.

My questions now are:

- where are stored the themes;
- How to create my own theme;
- How to change the styles of the letf side vertical menu bar?
- How to change the styles of the top menu bar?

**Comment by gregvanl** [comment]
@Natanael1234 Please see https://github.com/Microsoft/vscode/issues/3112 and have a look at the 1.11 release Insiders build https://code.visualstudio.com/insiders. The upcoming release allows much more customization of the workbench theming.
