### ISSUE TITLE
Exception: Unknown webview handle when closing custom editor

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#138060]
Repro:

1. Open a custom webview editor
2. Do some stuff (not sure what triggers exactly)
3. Close it

This seems like it's expected so should be silent?

![image](https://user-images.githubusercontent.com/2193314/143889312-822d22ea-05af-49eb-957a-7c85b5e3be56.png)

**Comment by mjbvz** [comment]
The error indicates that the webview is trying to post a message to a webview that has been destroyed.

I'm assuming this is your custom editor so can you look at your extension code to avoid doing that?

**Comment by Tyriar** [comment]
Thanks, figured it wasn't me since the trace only shows workbench code. I guess I need to catch and swallow the errors or track which webviews should be gone.
