### ISSUE TITLE
win + alt + r in full screen causes glitches

### ISSUE THREAD

**Issue by MedicalJewel105** [microsoft/vscode#138015]
If you open vs code in full screen (f11) and start to record (default win10 recorder, win + alt + r), it will cause glitches.

https://user-images.githubusercontent.com/87320205/143783686-423137d1-300e-4486-bdfd-e86fa660e5f5.mp4

**Comment by egamma** [comment]
/needsMoreInfo

Can you pls clarify what you consider glichtes? 

These are controls from the screen recording tool and have nothing to do with VS Code.
