### ISSUE TITLE
\{left\{ ... \right. is not colorized even if registered as colorized bracket pair

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#138058]
> Can you provide a screenshot?

The screenshot in the last post is the actual status after applying the patch of the LaTeX workshop. 

> Is this registered as bracket pair?

Yes. `\left\{...\right.` is registered as a bracket pair [here](https://github.com/James-Yu/LaTeX-Workshop/blob/02dcacc2638962c1feb6206f7b8b277c95e6de25/syntax/latex-language-configuration.json#L18). The frame shown on them also indicate they're matched. What actually goes wrong is the colorization system.

_Originally posted by @ZhangSongyi in https://github.com/microsoft/vscode/issues/137774#issuecomment-981561248_

To verify:
```json5
"[typescript]": {
    "editor.language.colorizedBracketPairs": [
        //["{", "}"],
        ["a{", "}b"], // does not work
    ],
    "editor.bracketPairColorization.enabled": true,
},
```

**Comment by hediet** [comment]
This is out of scope, as a reasonable constraint for brackets is that they are made up from tokens that have the same metadata. In `a{` for typescript, `a` has different metadata than `{`.

**Comment by ZhangSongyi** [comment]
As a related suggestion, when an item is registered in `editor.language.colorizedBracketPairs` but spans multiple different tokens,  it should be marked as warning status to indicate that it may not work properly.
(Perhaps further discussion should be transported into a new issue)
