### ISSUE TITLE
Bug when creating folder

### ISSUE THREAD

**Issue by cl0v** [microsoft/vscode#138010]
Issue Type: <b>Bug</b>

I was trying to create a file, but i miss the /, so i pressed ented and created a file without .ext(encion), than i pressed the button to try to create again, so i type screen/xxx.xxx bug i was not able to do that, cause i already have a "file" named screen

VS Code version: Code 1.62.3 (Universal) (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (1.33GB free)|
|Process Argv|. --crash-reporter-id d495c87c-2892-4823-b58e-d6afe0b7164c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
TabOut|alb|0.2.1
dart-data-class-generator|Ben|0.5.1
format-json|Cle|1.0.2
dart-code|Dar|3.28.0
flutter|Dar|3.28.0
vscode-new-file|dku|4.0.2
vs-code-xml-format|fab|0.1.5
copilot|Git|1.7.3952
pubspec-assist|jer|2.3.2
regexp-preview|Lou|0.1.5
dart-barrel-file-generator|miq|1.3.1
awesome-flutter-snippets|Nas|3.0.2
vscode-groovy-lint|Nic|1.6.0
fix-json|oli|0.1.2
java|red|1.1.0
vscode-xml|red|0.18.1
vscode-yaml|red|1.2.1
synthwave-vscode|Rob|0.1.10
vscode-fileutils|sle|3.4.5
json-utils|ted|1.0.8
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.7
vscode-java-test|vsc|0.33.0
vscode-maven|vsc|0.34.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593:30376534
vssld246cf:30401891
vscexrecpromptc:30404946
vscop804:30404766
vs360cf:30404996

```

</details>

**Comment by Boatik** [comment]
it is not possible to create file and folder (directory) with the same name in one folder.

correct me if I wrong with the "bug" steps we should take to reproduce.
1) open some folder in vscode
2) create file with name xxx in it
3) try to create another file with name (name-path) 'xxx/xxx.yyy'
if steps are ok, there is no bug in here. folder('xxx') cannot be created if file('xxx') exists in the filepath you're in.

**Comment by JacksonKearl** [comment]
It's not clear to me what the bug is here. Please include detailed reproduction steps or a screen recording.

/gifPlease
