### ISSUE TITLE
Make ambiguous character outline yellow, not red

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#138059]
Hit on the weekend and the red is too much imo since it's actually a warning, not an error:

![image](https://user-images.githubusercontent.com/2193314/143889067-3d1cfe84-6b17-4754-b153-235f1dc89b5b.png)

**Comment by hediet** [comment]
What about this:

![image](https://user-images.githubusercontent.com/2931520/144066421-ddd2f1dc-dae5-478c-90de-fde64593e1db.png)

![image](https://user-images.githubusercontent.com/2931520/144066453-962f517f-56c3-4615-8fd4-e58a5ad8ea94.png)

![image](https://user-images.githubusercontent.com/2931520/144066627-a80d14fb-7cd4-4b6d-a41a-a524b25f855b.png)


However, it does not jump into the eye anymore and it might me overlooked easily.

**Comment by Tyriar** [comment]
Looks good to me.

> However, it does not jump into the eye anymore and it might me overlooked easily.

It's still just as obvious imo, but it's signaling correctly that it's a warning not an error as ambiguous characters are perfectly fine to use.

**Comment by Tyriar** [comment]
Can you change this to use the theme's warning color? Otherwise it won't be using the right yellow in non Dark+/Light+ themes.

**Comment by Tyriar** [comment]
Moved question to https://github.com/microsoft/vscode/issues/138518
