### ISSUE TITLE
mongoDb shell and integrated terminal

### ISSUE THREAD

**Issue by volkancakil** [Microsoft/vscode#13809]
when i try to  use mongoDb shell in the integrated terminal, it is not possible to write brackets and curly brackets. in fact that key combinations with ALT-GR doesnt work.
- VSCode Version: 1.6.1
- OS Version: Win 8.1 x64

**Comment by Tyriar** [comment]
Likely related to https://github.com/Microsoft/vscode/issues/10163

**Comment by Tyriar** [comment]
Duplicate #14613

**Comment by Tyriar** [comment]
This should hopefully be fixed in tomorrow's Insiders build (via https://github.com/Microsoft/vscode/commit/63f1fa66800bf641de5e36027610503ba75085b5). Please let me know if it still reproduces.

See https://github.com/Microsoft/vscode/issues/13625 for more information.
