### ISSUE TITLE
Container build log doesn't open as editor terminal

### ISSUE THREAD

**Issue by dmartin** [microsoft/vscode#138061]
- VSCode Version: 1.62.3 Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
- Local OS Version: macOS 12.0.1 (21A559)
- Remote OS Version: N/A
- Remote Extension/Connection Type: Docker
- Logs: N/A

Steps to Reproduce:

1. Set `"terminal.integrated.defaultLocation": "editor"`
2. Start/rebuild a dev container
3. Click "Starting Dev Container (show log)" link in popup
4. Observe that log editor pane will not be displayed until container has started

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by danielbisar** [comment]
Same issue here. At least it helped me to understand why the log is not opening and settings the setting back to the default value helped (after restarting vscode). But still this is not a good solution.

**Comment by dmartin** [comment]
This seems to be resolved as of at least VSCode 1.80.1 (not sure of the exact version that included a fix)
