### ISSUE TITLE
C# (csharp) regions indentation formatting option

### ISSUE THREAD

**Issue by 66somedeveloper99** [microsoft/vscode#138013]
C# regions indentations is not currently an option. so when we write 
![image](https://user-images.githubusercontent.com/72737724/143780664-24ae6333-22a8-47df-84a4-4d0e366f0ebc.png)

it'll be like this after reformatting :
![image](https://user-images.githubusercontent.com/72737724/143780677-616ab3e3-cc49-43f9-b6f9-5f7c955db5b0.png)

the formatter gives the regions the same indentation as other lines. which is maybe wrong, or maybe a matter of preference. so it'll be nice to have it as a choice :D

thanks for this amazing beast of tool!

**Comment by 66somedeveloper99** [comment]
oh github didn't keep the formatting...

**Comment by 66somedeveloper99** [comment]
![image](https://user-images.githubusercontent.com/72737724/143780539-94eb5472-e96f-488d-95d6-047aa0d94722.png)
that is before formatting
![image](https://user-images.githubusercontent.com/72737724/143780578-b1a139c2-3f91-48ee-8f35-275943b3c60a.png)
and that is after formatting

**Comment by aeschli** [comment]
I need to file this against the extension that provides the formatter. Is it maybe the C# extension? (https://github.com/OmniSharp/omnisharp-vscode)
