### ISSUE TITLE
Test Unicode Highlighting

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#138071]
Test for #136437

- [x] Any @rebornix
- [x] Any @joaomoreno

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23138071%0A%0A&assignees=hediet)

---

This is an exploratory test plan item for the unicode highlight feature.

## Objectives
* When opening an untrusted workspace and no unicode highlights are being shown, [no unicode spoofing](https://www.trojansource.codes/) [attack](https://certitude.consulting/blog/en/invisible-backdoor/) is possible (with default *user* settings).
* When opening a trusted workspace and no unicode highlights are being shown, *some* known unicode spoofing attacks are detected (there is no guarantee that unknown spoofing attacks are detected).
* When opening a trusted workspace, this feature is not annoying.
* Nothing unexpected™ happens.

## New Settings To Play With
(`deriveFromWorkspaceTrust` is standard)
```json5
"editor.unicodeHighlight.invisibleCharacters": boolean | 'deriveFromWorkspaceTrust',
"editor.unicodeHighlight.ambiguousCharacters": boolean | 'deriveFromWorkspaceTrust',
"editor.unicodeHighlight.nonBasicASCII": boolean | 'deriveFromWorkspaceTrust',
"editor.unicodeHighlight.includeComments": boolean | 'deriveFromWorkspaceTrust',
"editor.unicodeHighlight.allowedCharacters": string,
```

## Test-Instructions
* Play with this feature and the new settings
* Make sure the objectives are met
* Make sure that in trusted workspaces no character in comments is highlighted (default settings)
* Make sure that a banner is being shown when a file with too many highlighted characters is opened

**Comment by joaomoreno** [comment]
A great way to play around with this is to open this repo: https://github.com/nickboucher/trojan-source/

**Comment by rebornix** [comment]
@joaomoreno thanks for the vscode dev link, it saves a huge ton of time to just get started.

In overall the highlight looks decent, great work.

**Comment by aminomancer** [comment]
I have a question about `editor.unicodeHighlight.includeComments`

![image](https://user-images.githubusercontent.com/33384265/145914947-1e4441ff-6f43-4409-adb2-a5822b936738.png)
![image](https://user-images.githubusercontent.com/33384265/145915003-bc171d33-6af3-4096-bb34-fe3948aaec58.png)

This styling in the top screenshot is from extension [Userscript](https://marketplace.visualstudio.com/items?itemName=adpyke.vscode-userscript). I guess whatever it's doing causes VS code to not perceive text in the userscript block as comments. Is there some way to circumvent this? I'd like to keep unicode highlighting of ambiguous characters enabled, but it's annoying in this particular case. I guess it would bother me less if the highlighting appearance was better. The highlight borders look kind of janky, but I don't think there's a theme property for setting a highlight background.

**Comment by hediet** [comment]
@aminomancer thanks for reaching out! Please create new issues for your feature requests.
Unfortunately, we don't know that structured comments are comments.
