### ISSUE TITLE
Explorer: Move File Up Or Down

### ISSUE THREAD

**Issue by daneb** [Microsoft/vscode#13800]
- VSCode Version: 1.6.0
- OS Version: 10.11.6

Steps to Reproduce:

1. mkdir ScratchPad
2. cd ScratchPad
3. dotnet new -l f#    // add other ceremonial issues dotnet restore etc.
4. Add File Domain.fs 
5. Add File Operations.fs

![image](https://cloud.githubusercontent.com/assets/1150821/19410866/8bac4110-92f6-11e6-9c19-f6946f77b5cf.png)

6. Add Files to Project.json

![image](https://cloud.githubusercontent.com/assets/1150821/19410869/9e591b94-92f6-11e6-9fd6-72cbd15f2a63.png)

7. Open terminal
8. dotnet build  
Produces error -
/Users/xxx/Documents/Github/xx/xx/ScratchPad/Program.fs(2,1): error FS0222: Files in libraries or multiple-file applications must begin with a namespace or module declaration, e.g. 'namespace SomeNamespace.SubNamespace' or 'module SomeNamespace.SomeModule'. Only the last source file of an application may omit such a declaration.

The Main (< EntryPoint >) for F# projects I believe need to be the last file in the Project.
http://putridparrot.com/blog/entrypoint-into-f/
http://stackoverflow.com/questions/10181118/fs-hello-world-with-2-fs-files

Unfortunately I cannot move files up or down in Explorer to solve the compiler requirement as with Visual Studio 2015. ~~I tried re-arranging the files in package.json.~~

**It would be nice to have the functionality built into VsCode that allowed**:
(a) Re-arranging of files (moving up and down in explorer)
(b) That would then feed into the compilation process to apply order.

**Comment by daneb** [comment]
Re: Setting the order in the project.json does the trick.
So having functionality that arranges files in Explorer and then sets their order in package.json is the **Feature Request** here.

**Comment by bpasero** [comment]
Sorry, but the file explorer should not care about order of files, it is a sorted view of the file system and has no knowledge about package.json. 

This seems more like a feature request around F# to make the editing easier so I suggest to file this against F#.
