### ISSUE TITLE
Using picked in a QuickPickItem does not pre-select item in QuickPick

### ISSUE THREAD

**Issue by DTHaydon** [microsoft/vscode#138070]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- OS Version: macOS 12.0.1

Steps to Reproduce:

```
const quickpick = vscode.window.createQuickPick();
quickpick.canSelectMany = true;

const items: vscode.QuickPickItem[] = [
         { label: 'Item 1', picked: false },
         { label: 'Item 2', picked: true },
        ];

quickpick.items = items;
quickpick.show()
```

QuickPickItems that have `picked: true` are not pre-selected.

This issue was raised already here https://github.com/microsoft/vscode/issues/103084 but no solution was given for those who need to use `vscode.window.createQuickPick()` instead of `vscode.window.showQuickPick()`.

**Comment by TylerLeonhardt** [comment]
Yes this is because you can simply do:

```ts
                const qp = vscode.window.createQuickPick();
		const items: vscode.QuickPickItem[] = [
			{ label: 'Item 1', picked: false },
			{ label: 'Item 2', picked: true },
		];
		const itemsThatYouWantPickedAlready = items.filter(item => item.picked);
		qp.items = items;
		qp.selectedItems = itemsThatYouWantPickedAlready;
```

we didn't want two ways to do the same thing in this case.

With that said, we should improve our docs for this case.

**Comment by DTHaydon** [comment]
The reason behind this issue is connected to https://github.com/microsoft/vscode/issues/138073#issuecomment-992673269

I found that since I needed to update `(vscode.QuickPick).items` with a reordered/modified item list it was also necessary to update `(vscode.QuickPick).selectedItems`, which triggered `onDidChangeSelection` again.

I thought `(vscode.QuickPickItem).picked` might have been a means of keeping items selected without triggering `onDidChangeSelection`.
