### ISSUE TITLE
Test configuration default overrides

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#138075]
Ref #46851

- [x] Mac @kieferrm
- [x] Win @rebornix
- [x] Linux @chrmarti

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23138075%0A%0A&assignees=sandy081)

---

You can now contribute and override defaults of configurations using `configurationDefaults` contribution point.

- Create a simple extension - https://code.visualstudio.com/api/get-started/your-first-extension
- Open package.json and customize defaults using `configurationDefaults` contribution point. Eg:
```json
"contributes": {
		"configurationDefaults": {
			"workbench.sideBar.location": "left"
		}
	}
```
Above contribution point will change the default value of `workbench.sideBar.location` setting to `right`.
- Run the extension and test that defaults are overriden.
- Test overriding defaults of various other settings
- Test IntelliSense in the `configurationDefaults` object
- Make sure that application/machine scoped settings cannot be overriden. Eg: `update.mode`
- Explore any other possible scenarios and test

**Comment by chrmarti** [comment]
@sandy081 Can `machine-overridable` settings' defaults be overridden?

**Comment by sandy081** [comment]
Yes they can be overridden
