### ISSUE TITLE
Sync not applying correct theme when detecting OS color scheme

### ISSUE THREAD

**Issue by TheCrether** [microsoft/vscode#138051]
Issue Type: <b>Bug</b>

When enabling the "Window: Auto Detect Color Scheme" feature and using Settings Sync between mutliple computers, it will detect the correct theme at first, but Settings Sync overwrites the theme after syncing.
My Laptop and PC both automatically switch to the **OS** light theme during daytime and to **OS** dark theme during the night (to reproduce, just have one device in **OS** dark mode and the other in **OS** light mode).

I often open VS Code on my PC and close it when the **OS** dark theme is enabled (and VS Code having the dark theme as the current theme). Then I open my laptop the next morning and it automatically switches to the **OS** light theme. Then, after opening VS Code, it first detects the correct theme (light in this case) and then applies the theme it gets from syncing the settings from my PC.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.90GB (0.90GB free)|
|Process Argv|--crash-reporter-id 8b29dd1c-56fb-4600-838e-b560915d4e33|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
xd|ado|1.2.3
vscode-javascript-snippet-pack|aka|0.1.6
markdown-emoji|bie|0.2.1
vscode-intelephense-client|bme|1.7.1
vscode-css-modules|cli|0.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|3.1.1
graphviz-preview|EFa|1.5.0
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.0.0
vs-code-xml-format|fab|0.1.5
shell-format|fox|7.2.2
remotehub|Git|0.18.0
go|gol|0.29.0
todo-tree|Gru|0.0.214
discord-vscode|icr|5.7.0
vscode-react-typescript|inf|1.3.1
vscode-graphviz|joa|0.0.6
mongodb-vscode|mon|0.6.14
vscode-scss|mrm|0.10.0
csharp|ms-|1.23.16
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
hexeditor|ms-|1.8.2
vsliveshare|ms-|1.0.5090
material-icon-theme|PKi|4.11.0
ruby|reb|0.28.1
code-stats-vscode|riu|1.0.18
vscode-autohotkey|sle|0.2.2
ayu|tea|1.0.5
pdf|tom|1.1.0
vim|vsc|1.21.10
vscode-wakatime|Wak|17.1.0
vscode-ruby|win|0.28.0
markdown-all-in-one|yzh|3.4.0

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30402085
vsaa593:30376534
vssld246:30401890
vscexrecpromptt1:30404947
vscop804:30404766
vscop453:30404998

```

</details>

**Comment by diogoleitao** [comment]
I have a similar issue (VS code theme not applying correctly based on OS theme), but Settings Sync doesn't overwrite any value. I've set `window.autoDetectColorScheme` to `true` and also the preferred theme for light and dark. To overcome this, sometimes I need to set the theme manually and then remove the configuration to force VS Code to check which theme should be applied or change back and forth any of the settings previously mentioned.

Relevant information:
- Version: 1.62.3
- Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
- Date: 2021-11-17T07:59:13.865Z
- Electron: 13.5.2
- Chrome: 91.0.4472.164
- Node.js: 14.16.0
- V8: 9.1.269.39-electron.0
- OS: Darwin x64 21.1.0

**Comment by sandy081** [comment]
It seems the auto detect color scheme feature is updating the `workbench.colorTheme` setting value. Settings Sync just synchronizes the settings file as is across machines. When the auto detect color scheme feature changes theme on one machine, settings sync synchronizes that setting to other machines. I am not sure how the auto detect color scheme feature is reacting to these changes. Hence assigning to @aeschli

**Comment by TheCrether** [comment]
I have found a "solution" to this problem, which is to make Settings Sync ignore the `workbench.colorTheme` property when syncing, which then only gets changed by the automatic theme detection.
