### ISSUE TITLE
Commenting is flawed in the new version

### ISSUE THREAD

**Issue by karteek-paruchuri** [Microsoft/vscode#13803]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: abusaidm.html-snippets-0.0.17, donjayamanne.python-0.4.2, georgewfraser.vscode-javac-0.0.23, zhuangtongfa.Material-theme-1.0.3, Zignd.html-css-class-completion-1.0.3

Steps to Reproduce:

1. Open a html page/ js file is VS code
2. select 3-4 lines of javascript 
3. Press Ctrl + / 
4. The js are not properly commented. They get considered to be HTML and gets commented in that way. 

This issue didn't exist before in old versions.

**Comment by mrmlnc** [comment]
See `HTML` section in 1.6.1 release notes (https://code.visualstudio.com/updates/v1_6)

![image](https://cloud.githubusercontent.com/assets/7034281/19411243/965f8f3a-9306-11e6-9093-abfb0d27a886.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/11081
