### ISSUE TITLE
Test pre-release extensions as an Extension author

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#138068]
Ref #15756

- [x] Mac @JacksonKearl
- [x] Win @weinand
- [x] Linux @roblourens

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23138068%0A%0A&assignees=sandy081)

---

As an extension author you can support pre releases for your extension. 

[Extension authoring guide](https://code.visualstudio.com/api/get-started/your-first-extension)

Please read following before starting testing

**Note 1:** You can only use `major.minor.patch` for extension version. `pre-release tags` are not supported.
**Note 2:** Recommended to use `major.EVEN_NUMBER.patch` for release versions and `major.ODD_NUMBER.patch` for pre-release versions. Eg: `0.2.*` for release and `0.3.*` for pre-release.
**Note 3:** Please wait at least for ~10 minutes after publishing your extension for VS Code to pick it.
**Note 4:** Pre-release versions are given preference only if they are newer than the newest released version. So, please make sure to have a pre-release version newer than newest released version for testing pre-release versions.

Please test following:

- Using latest `vsce` you can publish a pre-release version using `--pre-release` flag. Eg: `vsce publish --pre-release`
- Pre-release extension version is supported only when `vscode.engine` value in `package.json` is  >= 1.63.0.
- Publish some release versions and some pre-release versions.
 
- Open VS Code insiders and browse for your extension 
  - Test the representation of your extension in extension view, hover and extension editor. Pre-release bookmark, badge & indicator are used to represent that extension has a pre-release or is pre-release.
  - Test that the primary action to install your extension is to install the pre-release and the secondary action is to install the release version. Test these actions are working as expected.

- Test Updating
  - Publish a newer version of release/pre-release version of your extension
  - If you had installed pre-release version before, VS Code updates to the newest version (can be release/pre-release)
  - If you had installed release version, VS Code updates to the newest release version.

- Make sure that pre-release versions cannot be installed in current VS Code stable

**Comment by isidorn** [comment]
@JacksonKearl @alexdima @roblourens if you have any questions or if something is not clear from the test plan item please reach out to me. Thanks.

**Comment by JacksonKearl** [comment]
The linked Extension Authoring Guide doesn't seem to include information on pre-release publishing, is that documented somewhere?

**Comment by roblourens** [comment]
Awesome, can't wait to adopt it for SSH

**Comment by sandy081** [comment]
@JacksonKearl Documentation of the feature is pending yet, we will add all information once testing is done.

**Comment by weinand** [comment]
Very cool feature!

Now we can support a pre-release version of Mock Debug (which uses a pre-release version of the Debug Adapter Protocol): 

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/1898161/144229402-250b534a-6259-460d-b618-f23905d1900c.png">

**Comment by isidorn** [comment]
Great use case!

**Comment by isidorn** [comment]
I wrote a first version of the docs for extension authors 
https://github.com/microsoft/vscode-docs/blob/vnext/api/working-with-extensions/publishing-extension.md#pre-release-extensions
Feedback welcome. Especially interested in parts that might have been confusing for extension authors.
