### ISSUE TITLE
Multiple scroll bars in process explorer

### ISSUE THREAD

**Issue by dacapoday** [microsoft/vscode#138020]
Issue Type: <b>Bug</b>

open process exporer will reproduce it.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No
Remote OS version: Linux x64 5.11.0-38-generic
![Snipaste_2021-11-29_09-47-40](https://user-images.githubusercontent.com/9378047/143796871-1dcca223-da1b-422a-9e76-7240e7c16dbb.png)

**Comment by Tyriar** [comment]
Let's track this in https://github.com/microsoft/vscode/issues/83571 which is also related to the scroll bars.
