### ISSUE TITLE
VScode crashing in debug mode when CPU reaches 100%

### ISSUE THREAD

**Issue by thalia2809** [microsoft/vscode#138065]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.3 & 1.61.2
- OS Version: Linux 3.10.0 (KDE 4.14.8) & Ubuntu 20.10

Hello, I love the VS debugger but I cannot make it to work with large files. I am using Perl Language Server as the only extension and although it works fine with small files as soon as I open a large file or the code needs to copy a large file VScode crashes with no error report whatsoever. Perl also gives no error message. 
I noticed the crash will happen as soon as ANY CPU will reach 100% usage. I tried installing and launching it on a workstation with tens of CPUs and 45GB free mem and it still happens (!) 

Any advice would be much appreciated as I am stuck and the debugger is really helpful 
Thank you in advance

Steps to Reproduce:

1. Start VScode debugger on a perl script (Extension Perl Language Server Enabled)
2. VScode will crash and exit with no error as soon as ANY CPU usage reaches 100%

**Comment by weinand** [comment]
Please file this against the Perl extension (since VS Code out-of-the-box only contains a JavaScript debugger).
