### ISSUE TITLE
Attempt to override application setting disables all overrides

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#138149]
Testing #138075

```json
		"configurationDefaults": {
			"[javascript]": {
				"editor.lineNumbers": "off"
			},
			"workbench.sideBar.location": "right",
			"remote.containers.dockerPath": "foobar"
		}
```

`remote.containers.dockerPath` is an application setting, I see an expected warning for that. What's unexpected is that the other overrides stop working.

Maybe a corner case, but might be relevant when someone narrows the scope of a setting to `application` when that setting is already used in other extensions' overrides.

**Comment by sandy081** [comment]
Fixed by 7549d51a10e3b8deb6969c5952268eefdbccdb50
