### ISSUE TITLE
Testing markdown preview editor : Invalid link closes preview editor

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#138195]
Testing #138040

Repro steps:

1. Open vscode-docs\docs\getstarted\tips-and-tricks.md
2. Click on the 'Download' link at the top (looks invalid to me)

Expected result:
Error about link not existing comes up

Actual result:
Error comes up but original file closes too.

**Comment by mjbvz** [comment]
I just tested this again and now see this warning when clicking on a link to a file that does not exist:

![Screen Shot 2022-02-22 at 5 06 42 PM](https://user-images.githubusercontent.com/12821956/155245991-bae95348-8d2a-4ec2-8f91-58a2a4183a90.png)


I think this is the expected experience. If you still see some case not working well, please share steps to reproduce and I will investigate further
