### ISSUE TITLE
insert snippet picker list show where the snippet from

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#138105]
Snippets may from extension or builtin, it would be helpful if display where the snippet from.

![image](https://user-images.githubusercontent.com/41773861/143976200-b65c3752-7b1d-4450-bc79-448bbba6cbac.png)

**Comment by wengj9** [comment]
@jrieken Hi, a partner (@DavidJRWang) and I are interested in taking on this issue, could this be reassigned to us? Thanks!

**Comment by jrieken** [comment]
> ...this issue, could this be reassigned to us?

We can only assign issues to team members but you now have your stick in the ground for this one

**Comment by tjx666** [comment]
This extension maybe be help https://github.com/robole/vscode-snippets-ranger @jrieken  @wengj9

**Comment by Pines408** [comment]
i tried

**Comment by wengj9** [comment]
This is an early preview of what the snippet picker would look like:
<img width="604" alt="Screen Shot 2021-12-08 at 16 03 07" src="https://user-images.githubusercontent.com/12522122/145284281-5ff294d5-4c79-4caa-b402-84cd8810de52.png">

Would you prefer any changes to the current look/feel of it?

**Comment by tjx666** [comment]
The message should be shorter, for example: `extension: C/C++ Language Basics` be enough, if is built in extension, should be `builtin extension: C/C++ Language Basics`? @wengj9

**Comment by jrieken** [comment]
Also using the group label on the right for each and every entry seems a bit heavy. Today it's "User Snippets", "Workspace Snippets", and "Extension Snippets". I would suggest to remove the last group and have than one group per extension, not per snippet

**Comment by misolori** [comment]
+1 to only having a single category/group at the end as we do the same thing in the remote picker:

<img width="652" alt="CleanShot 2021-12-09 at 13 11 42@2x" src="https://user-images.githubusercontent.com/35271042/145476406-b6655317-7807-49b8-b102-c9e6230939e1.png">

**Comment by wengj9** [comment]
We've made the requested changes and here's what the snippet picker looks like now: 
<img width="604" alt="Screen Shot 2021-12-10 at 14 13 35" src="https://user-images.githubusercontent.com/12522122/145631175-581ab4f9-fd6e-4ea8-a46c-cae82e204d02.png">.

We also changed the sorting of the snippets to group extensions together to minimize the category/groups in the picker.

**Comment by misolori** [comment]
Do we really need to add the version info? I think having it as `Angular Snippets (Extension)` or even `Angular Snippets` would be a cleaner look

**Comment by DavidJRWang** [comment]
Right, the version number seems to be part of the extension name so I'm not sure there's much we can easily do about it right now. So you're suggesting, for example in the screenshot, instead of "Extension: Angular Snippets..." for it to just say "Angular Snippets"?

**Comment by misolori** [comment]
Yes just to simplify it as many snippet extension names are long:

<img width="647" alt="CleanShot 2021-12-10 at 14 11 28@2x" src="https://user-images.githubusercontent.com/35271042/145647945-aaee98dc-aa8d-4e97-b99a-f42a9ad9cf74.png">

<img width="651" alt="CleanShot 2021-12-10 at 14 10 49@2x" src="https://user-images.githubusercontent.com/35271042/145647874-3c024364-a0e3-4614-8c77-6a93ed28ae39.png">

<img width="626" alt="CleanShot 2021-12-10 at 14 11 00@2x" src="https://user-images.githubusercontent.com/35271042/145647896-458ff2e4-9130-49b2-ae63-0e16129ba22d.png">

**Comment by wengj9** [comment]
I omitted the "Extension: " and here's what it looks like now: 

![image](https://user-images.githubusercontent.com/12522122/145685485-7dec0ef7-bfe2-4d28-b50b-957d31447391.png)

Are there any other changes you'd like to the picker?

**Comment by misolori** [comment]
Looks good to me, thanks for taking the feedback!

**Comment by jrieken** [comment]
PR merged. Thanks everyone!

**Comment by tjx666** [comment]
@wengj9 @jrieken @misolori

![image](https://user-images.githubusercontent.com/41773861/146028802-88463175-fb8d-4be7-a54b-1044ebbabc0b.png)

The workspace snippets should be front of user snippets.

**Comment by wengj9** [comment]
The VSCode snippet picker in the current stable version also lists user snippets before workspace snippets:
![image](https://user-images.githubusercontent.com/12522122/146035165-411acb35-7246-4055-9cfa-936fc04fa914.png)

Not sure if you mean to open another issue about this?

**Comment by tjx666** [comment]
maybe it should be another issue. @wengj9

**Comment by tjx666** [comment]
I have create another issue: https://github.com/microsoft/vscode/issues/139103

**Comment by TylerLeonhardt** [comment]
<img width="768" alt="image" src="https://user-images.githubusercontent.com/2644648/151621341-d3b38e6c-80ee-49e6-8ebe-3c358c1cacde.png">

looks good!
