### ISSUE TITLE
space and ctrl + space key not honouring editor.quickSuggestions and editor.quickSuggestionsDelay settings

### ISSUE THREAD

**Issue by ajaygera** [microsoft/vscode#138112]
Does this issue occur when all extensions are disabled?: Yes/No Yes

- VS Code Version:1.51.1
- OS Version:Windows 10 Pro

To support intellisense/suggestion in our VSCode extension, I have implemented vscode.CompletionItemProvider interface and call to provideCompletionItems() returns the list of vscode.CompletionList.

If I type any charcter say - 'e' then I get a call  to provideCompletionItems method with the delay as specified in editor.quickSuggestionsDelay
But on pressing space and ctrl +space, i get call to provideCompletionItems immediately basically these keys are not honouring editor.quickSuggestionsDelay setting.
Also on pressing space and ctrl + space ,  I get call to provideCompletionItem even if editor.quickSuggestions set to false.
Please let me know what i need to do so that pressing space and ctrl + space key also honour these settings.
Pleas note, i have specified space as my trigger character because if i do not specify that as trigger chacter then provideCompletionItems does not get called for space key.

Thanks & Regards,
Ajay Gera

**Comment by jrieken** [comment]
The `editor.quickSuggestions` setting in only honored for "completions as you type". Manually invoking completions, with Ctrl+Space, or trigger-character based completions aren't delayed and directly dispatched.

**Comment by ajaygera** [comment]
Is it possible to to invoke provideCompletionItems() for space key  without specifying that as trigger character?

**Comment by ajaygera** [comment]
Another question-  how to identify or specify ctrl +space as trigger character ?
Basically I need to know that  user has specified ctrl + space key

**Comment by jrieken** [comment]
> Is it possible to to invoke provideCompletionItems() for space key without specifying that as trigger character?

No, that's not possible.

> Basically I need to know that user has specified ctrl + space key

There is now way to know that and there is also different ways how completions are requested. A context object is being passed to the provide-function and that has some data about the invocation. 

> VS Code Version:1.51.1

FYI - that version of VS Code is s u p e r old and should update to latest (1.62.x).
