### ISSUE TITLE
Versions 1.56+ breaks auto attach for custom interpreter

### ISSUE THREAD

**Issue by ngzaharias** [microsoft/vscode#138166]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56+
- OS Version:

Steps to Reproduce:

Before version 1.56 I was able to have a launch configuration with the following settings.
`		
{
	"type": "khonsu",
	"request": "launch",
	"name": "Launch Khonsu",
	"interpreter": "C:/Khonsu.exe",
	"args": [
		"--debug",
		"${file}"
	]
},
`

If I then loaded the script file and use "Run and Debug" with the above configuration, the Khonsu.exe would be launched and VSCode would be attached to it for debugging.

This is no longer working and instead requires that the "Run and Debug" be launched twice, the first time to start the process and the second time to attach to it.

**Comment by weinand** [comment]
VS Code has no built-in debugger "khonsu".
Please file this issue against the "khonsu" debugger extension.

**Comment by ngzaharias** [comment]
I'm not saying that this "Khonsu.exe" is a part of the debugger, but that VSCode no longer auto attaches to the process that was launched by it.

**Comment by weinand** [comment]
@ngzaharias the `"type": "khonsu"` determines which debugger extension is used to interpret the other properties of the launch config. The property `"interpreter"` is nothing that VS Code understand, so it must be something understood by the debugger extension that define the debug type `"khonsu"`.
