### ISSUE TITLE
Option 'disableExtensions' is deprecated, please use 'disable-extensions' instead

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138122]
```
~/Development/Microsoft/monaco> code-insiders --user-data-dir /Users/bpasero/Desktop/nov-ws --extensions-dir /Users/bpasero/Desktop/nov-ext
Option 'disableExtensions' is deprecated, please use 'disable-extensions' instead
```

![image](https://user-images.githubusercontent.com/900690/144013962-e05790f1-d5fe-4f0b-8f62-4a5ce8dcef69.png)

**Comment by vidhanio** [comment]
Can confirm this is happening to me on insiders on macOS Monterey. Code launches as expected, but still shows this error when opening it through the `code-insiders` command.

**Comment by aeschli** [comment]
@vidhanio On what VS Code version is that?

**Comment by vidhanio** [comment]
> @vidhanio On what VS Code version is that?

currently away from computer, but it was the latest insiders version at the time of my comment.
