### ISSUE TITLE
Unicode warning decoration still renders after exclusion

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#138185]
Testing #138071

* Open https://insiders.vscode.dev/github/nickboucher/trojan-source/ and open `C/commenting-out.c`.
* Hover on `[U+2066]`, adjust setting and exclude
* 🐛  The unicode warning decoration is still there though hover is gone.
* 🐛 Close the editor and open again, the warning is still there.

**Comment by hediet** [comment]
The actual issue is that the hover was shown in the first place.

These red character-replacement-boxes are a different feature (render control characters) and have nothing to do with unicode highlighting.
