### ISSUE TITLE
`_removePropertiesWithPossibleUserInfo` is ~10% of the cost of loading a renderer

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#138153]
* have a VS Code window
* start CPU Profiler
* select reload window
* stop profiling, show by "Heavy (Bottom Up)"
* 🐌 there is a single regex which costs ~150ms, ~3-4% of all JavaScript execution, ~10% of the overall renderer startup time

[CPU-20211130T143002.cpuprofile.txt](https://github.com/microsoft/vscode/files/7626049/CPU-20211130T143002.cpuprofile.txt)

<img width="748" alt="Screen Shot 2021-11-30 at 14 30 32" src="https://user-images.githubusercontent.com/1794099/144056228-3c797587-ff62-4067-a7fa-2273cd497907.png">

**Comment by jrieken** [comment]
I understand that clean telemetry data is of highest importance but I also believe the actual sending is done a the shared process. So, that dedicated process would be a really good place for costly operations like this

**Comment by bpasero** [comment]
I do not think we should wait another milestone to ship a fix for this, I am happy to help out.

**Comment by jrieken** [comment]
Agreed. I think we have these options

* move all cleansing into the shared process, right before handing data over to AI
* remove this particular regex
* improve this particular regex, it seems particular expensive, likely because it matches unbound numbers of non-whitespace characters at its end (`/\S*(key|token|sig|password|passwd|pwd)[="':\s]+\S*/`)

**Comment by lramos15** [comment]
@sbatten and I are working on a fix for this milestone.

**Comment by lramos15** [comment]
<img width="750" alt="Screen Shot 2021-12-01 at 1 43 25 PM" src="https://user-images.githubusercontent.com/4544166/144294676-a178da1f-a746-4dc5-8a72-5d41dded21cd.png">
Speed 🚗 🔥

**Comment by jrieken** [comment]
created https://github.com/microsoft/vscode/issues/138323 as follow-up item
