### ISSUE TITLE
Not able to insert different/new text on selecting completion item from the suggestion list.

### ISSUE THREAD

**Issue by ajaygera** [microsoft/vscode#138119]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.51.1
- OS Version:Windows 10 Pro

If I  select vscode.CompletionItem from the suggestion list then I need to display data, which I need to fetch from database.
Basically I want to put different data in insertText property of selected vscode.CompletionItem.
I have tried to do this processing in resolveCompletionItem() method.  
I have tried to change insertText property of vscode.CompletionItem but sometimes text gets inserted as specified in insertText property but sometimes it does not work.
Please let me know how to fix this issue?
I have tried to modify additionalTextEdits but it does not overrides existing text in insert Text property and also there is no way to specify position for additionalTextEdits  where text needs to be inserted because resolveCompletionItem() does not have position argument.
Thanks & Regards,
Ajay

**Comment by jrieken** [comment]
You cannot change the insert text after the fact, you can use additionaltextEdits but it may not overlap with the primary edit, see more here:

https://github.com/microsoft/vscode/blob/297c52bd80d8dbd18c1bf1900fee25aa8b7a5044/src/vscode-dts/vscode.d.ts#L4308-L4327

You should make sure to have all data ready when returning from `provideCompletionItems`. If that's only possible for a subset you can use incomplete results, see [here](https://github.com/microsoft/vscode/blob/297c52bd80d8dbd18c1bf1900fee25aa8b7a5044/src/vscode-dts/vscode.d.ts#L4226)
