### ISSUE TITLE
Wrong scroll appears when clicking on `Help` menu

### ISSUE THREAD

**Issue by microhobby** [microsoft/vscode#138110]
Issue Type: <b>Bug</b>

An unnecessary scroll element appears when clicking on `Help` menu the first time:

![image](https://user-images.githubusercontent.com/2633321/143990292-3f26bcb7-443a-4806-9f40-a27d955bf6a6.png)

If you close and open it again the scroll is not there anymore.

> ⚠️ very low priority issue, doesn't hurt, but reporting anyway

VS Code version: Code - Insiders 1.63.0-insider (8c56f0cae849839138fbd83fe4d5c7219c7ff806, 2021-11-29T18:01:13.184Z)
OS version: Windows_NT x64 10.0.22504
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2894)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.37GB (10.99GB free)|
|Process Argv|-n --crash-reporter-id 3d9c88e4-3dfe-4b4c-a1ea-3126556e988c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (79)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
better-comments|aar|2.1.0
icons-carbon|ant|0.2.4
QML|bbe|1.0.0
vscode-icontheme-nomo-dark|be5|1.3.6
markdown-checkbox|bie|0.3.2
bracket-pair-colorizer-2|Coe|0.2.1
doxdocgen|csc|1.3.2
arm|dan|1.5.2
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
vscode-wasm|dts|1.3.1
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
el-vsc-product-icon-theme|ElA|0.1.8
vscode-reveal|evi|4.0.3
vscode-vibrancy|eyh|1.0.16
vscode-pull-request-github|Git|0.32.0
vbnet|gor|1.0.2
output-colorizer|IBM|0.1.2
checkpatch|ida|0.0.8
better-cpp-syntax|jef|1.15.10
bats|jet|0.1.7
vscode-icon-theme|jtl|1.6.6
fluent-ui-vscode|lea|0.3.12
bash-ide-vscode|mad|1.11.0
git-graph|mhu|1.30.0
linuxkerneldev|mic|0.4.9
fluent-icons|mig|0.0.14
theme-monokai-pro-vscode|mon|1.1.19
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.17
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.11.1001515174
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.207.0
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.63.3
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
hexeditor|ms-|1.8.2
powershell|ms-|2021.10.2
debugger-for-chrome|msj|4.13.0
material-product-icons|PKi|1.1.1
vscode-thunder-client|ran|1.9.1
java|red|1.1.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.1
avr-support|roc|0.0.1
taskrunnercode|San|0.3.0
vscode-autohotkey|sle|0.2.2
vscode-il|sol|0.0.1
code-spell-checker|str|2.0.13
code-spell-checker-portuguese|str|0.1.9
code-spell-checker-portuguese-brazilian|str|2.0.2
ayu|tea|1.0.5
vt100-syntax-highlighting|Tob|1.0.1
qtvsctools|ton|0.10.1
torizon-early-access|Tor|1.4.266
android-xml-editor|Tot|0.0.1
vscode-totalcross|Tot|0.0.15
gnu-mapfiles|tro|1.1.0
cmake|twx|0.0.17
errorlens|use|3.4.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.7
vscode-java-test|vsc|0.33.0
vscode-maven|vsc|0.34.1
vscode-icons|vsc|11.7.0
windows-nt-vscode-theme|was|0.0.9
vscode-cil-complete|wk-|0.0.5
markdown-editor|zaa|0.1.10
material-theme|zhu|3.13.5

(14 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593cf:30376535
vsc1dst:30396469
pythonvs932:30404738
vscexrecpromptc:30397557
vscop804:30404766
vs360:30404995

```

</details>

**Comment by sbatten** [comment]
@microhobby thanks for reporting and the screenshot... sadly I cannot reproduce. are you able to do this 100% of the time or was this one and done?

**Comment by microhobby** [comment]
@sbatten I can reproduce this on my env 100%, in the first instance opened of the VS Code insiders:

![image](https://user-images.githubusercontent.com/2633321/144650415-81d68436-a02e-4bbb-9bd3-37ae58a9cafe.png)

After reproduce if I opened again or open another menu there is no issue. But if I close all instances and open a new VS Code instance the issue occurs again:

![image](https://user-images.githubusercontent.com/2633321/144650673-efd0c73a-5b3d-4b20-a316-2db2de090079.png)

**Comment by Lemmingh** [comment]
I can also reproduce it when clicking the menu **immediately** after a **fresh** start of VS Code Insiders `1.63`.

```yaml
Version: 1.63.0-insider (system setup)
Commit: d09289a2b6dd0e56b2a264a8e9380685498e10d6
Date: 2021-12-04T02:05:02.410Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

**Comment by alexr00** [comment]
It's 100% repro for me.

**Comment by sbatten** [comment]
@alexr00 can you confirm the bisect commit from @deepak1556 in the other issue? I still cannot repro

**Comment by Lemmingh** [comment]
This is related to Display Scaling.

On my Surface Book, I can reproduce it with the built-in display (200%), but not an external one (100%).

**Comment by sbatten** [comment]
Still not getting a repro no matter my scaling options... charging a different machine

**Comment by Lemmingh** [comment]
I'm sorry. The actual factor seems to be the effective window height.

https://user-images.githubusercontent.com/43396014/145284070-488e9747-fa7a-404d-8668-d30df75f8ba4.mp4

**Comment by sbatten** [comment]
after a lengthy bisect process, I've got the culprit commit https://github.com/microsoft/vscode/commit/24ba24e3298baf980cd6f9ea68b29353f7a45aa9 ... cc @alexdima 

I'll look into a fix tomorrow.
