### ISSUE TITLE
`Unable to resolve your shell environment notification` after VS Code restored during MacOS restart 2

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode#138182]
This is a reopening of #113869 which was erroneously closed. Perhaps it was a little unclear, so here is my attempt:

If you restart your Mac and ask it to reopen all windows at login, then when it reopens VSCode all of the windows (and future opened windows) will display the [`Unable to resolve your shell environment in a reasonable time`](https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fails) warning.

This is **NOT** because the shell takes longer than 10 seconds to start. If you read all of the comments in the original issue it is full of people with shells that start in under a second.

Also if you quit and restart VSCode then the error goes away.

This may be because when MacOS restarts all apps during a login the system grinds to a halt and then it really does take 10 seconds, but that doesn't explain why opening subsequent windows shows the same warning. Unless it just sets a "it's slow" flag and then keeps tediously warning you.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- OS Version: MacOS 11.6

Steps to Reproduce:

1. Open VSCode
2. Restart your Mac, with the open "Open windows after restart" enabled.

**Comment by joaomoreno** [comment]
@bpasero Should we just make this 10 second value configurable and be done with this?

**Comment by Timmmm** [comment]
> This may be because when MacOS restarts all apps during a login the system grinds to a halt and then it really does take 10 seconds, but that doesn't explain why opening subsequent windows shows the same warning. Unless it just sets a "it's slow" flag and then keeps tediously warning you.

Upon further investigation I think I'm right about this. It does take more than 10 seconds, because it's starting about 10 apps at the same time, and then once started it never tries to resolve your shell again and warns you on every window.

Assuming this is only used for the integrated terminal, it feels like the absolute rock solid way to solve this would be to show a `Resolving user shell environment... [cancel and use system environment]` type progress spinner UI thingy in the place of the terminal when you open it, in case it still hasn't resolved by the time you get to that point.

Ton of UI work though. I'd settle for making the delay configurable, or disabling it for the very first startup after a reboot.

**Comment by bpasero** [comment]
This is more about the fact that we popup the notification over and over for each new window we open.

/duplicate https://github.com/microsoft/vscode/issues/136272
