### ISSUE TITLE
jsonValidation feature after  package  is not work

### ISSUE THREAD

**Issue by xiaobindebingo** [microsoft/vscode#138144]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.62.3
- OS Version: macOS 11.1

Steps to Reproduce:

1.  when I debugger the vscode extension, the json validate feature is work successfully; But when I packaged it into  **vsix** file,and use the local load by VSIX； it does not work normally;
the github of this program is [extension code repository](https://github.com/xiaobindebingo/tuyamini-vscode)
```json
 "jsonValidation": [
      {
        "fileMatch": "pages/**/*.json",
        "url": "./src/json/page.json"
      },
      {
        "fileMatch": "manifest.json",
        "url": "./src/json/manifest.json"
      }
    ],
```

**Comment by IllusionMH** [comment]
Repo is private and cannot be accessed.

Are you sure that path `./src/json/page.json` is actually available in packed extension and `src` folder is not excluded because compiled code is in `dist` folder?

**Comment by aeschli** [comment]
Is this still an issue? I see you made a change to the location where you have your schema,

**Comment by xiaobindebingo** [comment]
> Is this still an issue? I see you made a change to the location where you have your schema,

thanks, it had soloved
