### ISSUE TITLE
Found multiple lock-files confusion

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#138174]
* open a folder with multiple package.json lock files
* a notification shows that there are multiple lock files
* be confused and say don't show again 🤣 

I don't understand what this message is good for because it has unclear FYI character, no ask to do something, no information if this is an issue or not

<img width="532" alt="Screen Shot 2021-10-06 at 16 22 40" src="https://user-images.githubusercontent.com/1794099/144084965-bb20163b-6955-45b3-acbc-13272f085291.png">

**Comment by alexr00** [comment]
This info message shows when you have `"npm.packageManager": "auto"`. We use the lock file to help determine which package manager the built in npm extension should use. To improve this I can:
1. Remove the notification or
2. Add something to it about `"npm.packageManager": "auto"`.

Do you have a preference?

**Comment by jrieken** [comment]
+1 to clarify what this issue/resolution is

**Comment by alexr00** [comment]
With more details:

![image](https://user-images.githubusercontent.com/38270282/145219054-007c5a43-9610-40bc-bf3e-cd05924bc5d6.png)

**Comment by jrieken** [comment]
@alexr00 Did something else change? I am not able to see any notification anymore but I believe there should be one, just more verbose?

**Comment by alexr00** [comment]
Yes, the notification should still be there and be very verbose. Did you maybe "Do not show again" the notification?

**Comment by jrieken** [comment]
I verified the message in source... I did try the same repo again and started with fresh user-data but didn't see the message tho, maybe the repo itself has changed

**Comment by alexr00** [comment]
Checked that repo, and the message shouldn't show for it unless you've done both a npm install and yarn for it.
