### ISSUE TITLE
Feat.Req.: API: showInputBox() user input validation and feedback

### ISSUE THREAD

**Issue by bgse** [Microsoft/vscode#1381]
It would be nice if we could validate user input before they dismiss with "ok", i.e. show the user they write something we won't accept before they dismiss the inputbox.

This could be a red outline around the inputbox if value doesnt pass validation, ideally would have a message shown underneath telling them what we expect.

A regex and (optional?) default message could work for many cases, ideally a custom validator that allows us to accept/reject (with optional message?) on user input change.

Possible duplicate of this, but this even goes a little further I think:

https://github.com/Microsoft/vscode/issues/426

**Comment by jrieken** [comment]
related to #540. 

We could extend the `InputBoxOptions` to allow to provide a validator

**Comment by jrieken** [comment]
this will be handled by #1795
