### ISSUE TITLE
Copilot causes vscode scaling to change

### ISSUE THREAD

**Issue by zhang-hongwei** [microsoft/vscode#138190]
Issue Type: <b>Bug</b>

Just click the code prompt of copilot, and the zoom of vscode will change

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by isidorn** [comment]
@zhang-hongwei I can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

fyi @hediet
