### ISSUE TITLE
Can't drag certain views into the side panel

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#138178]
Testing #138101

I tried dragging the Run and Debug view into the side panel (and terminal-area panel), and was confused as to why that doesn't seem to be supported. Same goes for Remote Explorer. I would expect the side panel to behave like the side bar in this regard... Could we consider either enabling that or providing a tooltip to explain why that's not allowed?

**Comment by sbatten** [comment]
This is by-design because the remote explorer and the run and debug view containers are special and have UX specific to the side bar. assigning others to re-consider if these views can be moveable.

**Comment by joyceerhl** [comment]
Someone else had the same question https://github.com/microsoft/vscode/issues/132893#issuecomment-950728209

**Comment by roblourens** [comment]
Is this the problem? 
![image](https://user-images.githubusercontent.com/323878/144139376-acde4d81-c3ec-49c2-9199-64d1d4c6dd55.png)

**Comment by joyceerhl** [comment]
Yeah it's probably the dropdown at the top, the Remote Explorer also has one. This makes sense now but was very confusing for me before given my expectation that the side panel works like the side bar.

**Comment by sbatten** [comment]
@roblourens i think that and probably the debug actions when debugging for docked mode

**Comment by roblourens** [comment]
Seems like it would work to put it in the title area of the panel, some panel viewlets customize that area

![image](https://user-images.githubusercontent.com/323878/144148556-c609152d-ee19-4934-b826-92c43a6895cd.png)

**Comment by alexr00** [comment]
This is as designed for Remote Explorer. No plans to change this.

**Comment by gjsjohnmurray** [comment]
For the record, Run & Debug can now live in Panel.

**Comment by roblourens** [comment]
And remote explorer :)
