### ISSUE TITLE
Opening vscode from terminal does not work WSL1 - Option 'disableExtensions' is deprecated, please use 'disable-extensions' instead

### ISSUE THREAD

**Issue by AH-Merii** [microsoft/vscode#138180]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: x64-1.63.0-insider
- OS Version: Windows 10 Enterprise 1909 - WSL 1 -> Ubuntu-20.04

Steps to Reproduce:

`code-insiders --verbose`
```
Option 'disableExtensions' is deprecated, please use 'disable-extensions' instead
Invoking: cd "/mnt/c/Users/a.hami-merii/AppData/Local/Programs/Microsoft VS Code Insiders" && ELECTRON_RUN_AS_NODE=1 "/mnt/c/Users/a.hami-merii/AppData/Local/Programs/Microsoft VS Code Insiders/Code - Insiders.exe" "resources/app/out/cli.js" "--ms-enable-electron-run-as-node" "--verbose" "--remote=wsl+Ubuntu-20.04"
```

1. Using WSL 1 Open Vscode using the `code-insiders` command
2. The following message pops up and vscode does not open -> Option 'disableExtensions' is deprecated, please use 'disable-extensions' instead

**Note**: 
- vscode opens when trying to run the same command from powershell. (The message is displayed, but vscode still opens)
- vscode opens when using the `--disable-extensions` flag

**Comment by Tyriar** [comment]
Happens on mac too:
<img width="591" alt="Screen Shot 2021-11-30 at 10 16 53 am" src="https://user-images.githubusercontent.com/2193314/144105187-2a3831ca-bcf8-48f3-ad3a-99e8aa089c25.png">

**Comment by conradwt** [comment]
I'm also seeing this issue on macOS 11.6.1 and it started happening today.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/138122
