### ISSUE TITLE
Weird intellisense behavior

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#13813]
- VSCode Version: Code - Insiders 1.7.0-insider (bbda59212ba3c603addfaa4854b35801fe04d92e, 2016-10-14T06:05:04.017Z)
- OS Version: Darwin x64 16.0.0

Steps to Reproduce:

1. No idea how to recreate. Happened twice in TypeScript

![cucgtozhvj](https://cloud.githubusercontent.com/assets/1723815/19414212/954dc078-9313-11e6-9f6d-a7ece08eeb1c.gif)

![image](https://cloud.githubusercontent.com/assets/1723815/19414210/90fb008a-9313-11e6-8968-4f3bf0510c7d.png)

**Comment by joaomoreno** [comment]
Screen cheese. Been trying to catch this since a while now.

**Comment by joaomoreno** [comment]
GOT IT! 🎆 

Repro steps: just hit <kbd>Escape</kbd> after using the mouse for scrolling.
