### ISSUE TITLE
Better warning message for uncommon characters

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#138188]
Testing #138071

`The character U+041d "Н" could be confused with the character U+0048 "H", which is more common in source code. Adjust settings`

Maybe we can mention that `U+0048` is ASCII otherwise it might be confusing as it's hard to tell the difference between two Unicode code points.

**Comment by hediet** [comment]
Suggestion:
Show "... could be confused with the ASCII character U+0048 "H", ..." when U+0048 (or whatever the codepoint is) is in the ASCII range.
