### ISSUE TITLE
Enter key does not expand/collapse in peek view

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#138143]
Does this issue occur when all extensions are disabled?: Yes

版本: 1.63.0-insider (system setup)
提交: b9cf83f70bb6b4697b544a97c7056dfd28fccc5f
日期: 2021-11-30T05:16:32.084Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.14393

Steps to Reproduce:
1. hit <kbd>shift+f12</kbd>
2. the reference show
3. use up/down to skip to next file(now the focus  is `MCU.pln` and it is fold )
![image](https://user-images.githubusercontent.com/1876302/144042778-ac64df33-f85b-4f0a-bf23-d21703be8d3d.png)
4. hit enter key the `mcu.pln` can not be unfold

but in reference view, we can use enter key to unfold
![image](https://user-images.githubusercontent.com/1876302/144043241-bc0dbcff-41ae-4258-ad6a-8cc4a12cf815.png)

**Comment by gjsjohnmurray** [comment]
For me, right-arrow expands it and left-arrow collapses it.

**Comment by heartacker** [comment]
> For me, right-arrow expands it and left-arrow collapses it.
> 

Thanks and I had never known that we could use left or right
and maybe we should make it a unified experience. What about binding the enter key for switching-expand?

**Comment by jrieken** [comment]
> What about binding the enter key for switching-expand?

On macOS enter is the default gesture for rename, e.g in the explorer. I do believe we have reasonable, popular defaults with the arrow keys and peek's tree doesn't change any default (from our default widget). Forwarding to @joaomoreno and @alexr00 to see if enter can also be a default

**Comment by alexr00** [comment]
This appears to be the keybinding that's causing enter to work for expanding in extension tree views:

https://github.com/Microsoft/vscode/blob/b2185337aa31a2c426bdaaacfe0e3962bc478890/src/vs/workbench/browser/actions/listCommands.ts#L434-L446

It doesn't appear to fire for peek trees.

**Comment by heartacker** [comment]
hi all, I am coding within my windows pc. and I test other list view like vscode-explorer tree and other collapsible tree node. the `enter` and `space` is being used to expanding/collapses(of course left and right arrow work too). maybe `enter` key is a windows style gesture. And I believe that we should add `enter` key for peek references view.

![image](https://user-images.githubusercontent.com/1876302/144071731-dd9e948d-786c-4b0d-81be-05964573d6d5.png)

![image](https://user-images.githubusercontent.com/1876302/144071892-bebb6982-69fc-4109-806e-41cf4e3d7079.png)

**Comment by joaomoreno** [comment]
This happens because [the `revealReference` eats up the <kbd>Enter</kbd> key](https://github.com/microsoft/vscode/blob/7b6c1065c76708d146844154c8a33906f06dce0b/src/vs/editor/contrib/gotoSymbol/peek/referencesController.ts/#L375-L392).

Caused by https://github.com/microsoft/vscode/commit/144f90443a8a82af28b6155236137d3e994c3f10
