### ISSUE TITLE
Selection of commands in layout control seems random

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#138135]
Testing #138100

The closest existing menu that we already have is the "Appearances" menu but the layout control seems to be a random subset. It has all show-commands except for "Show Editor Area". Similar it has "Move Sidebar" but not "Move Panel...". This repeats with picking "Centered Layout" but not Full Screen or Zen Mode. What determines this selection

<img width="269" alt="Screen Shot 2021-11-30 at 11 30 13" src="https://user-images.githubusercontent.com/1794099/144030960-8ba1b862-9653-4621-9cdb-bb3c31329687.png">

<img width="631" alt="Screen Shot 2021-11-30 at 11 30 04" src="https://user-images.githubusercontent.com/1794099/144030969-90f349f4-81c1-4ce8-a908-4a6c973c19b7.png">

**Comment by sbatten** [comment]
Show Editor Area was removed per @isidorn suggestion because doing so forces a maximized terminal and might be startling to the user. 

Full Screen and Zen Mode are removed because these cause the title bar to be hidden and are therefore hard to undo.

Move Panel... commands are removed as there is some discussion about whether these should exist going forward with the side panel so in order to avoid increased usage, they are removed from the prominent menu item.

**Comment by sbatten** [comment]
I will close this as-designed but happy to continue discussion if these reasonings don't make sense.

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/138135#issuecomment-982889561 is a pretty good summary of why I say "random". Looks like anyone can express a wish and the menu is updated accordingly. Shouldn't we have guiding principles instead?

**Comment by sbatten** [comment]
> Looks like anyone can express a wish and the menu is updated accordingly. 

That only accounts for one of the entries that is "missing'

Full Screen/Zen Mode are based on the principle that this menu is intended for improving discoverability of layout commands while making it easy for users to experiment. We don't want the user to trigger a command that they cannot undo.

Move Panel commands are an exception as we decide how to handle the side panel with left/right panels. They are either temporarily not present or will be removed as commands altogether.

**Comment by jrieken** [comment]
Sounds like there is at least agreements about "Show Editor Area"

**Comment by sbatten** [comment]
We greatly reduced this menu in favor of the Customize Layout command. This issue is out of date.
