### ISSUE TITLE
More specific language identifier should have precedence

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#138152]
Testing #138076

Have the following `settings.json`
```
"[cpp][c]":{
    "editor.lineNumbers": "on"
},
"[cpp][c][markdown]":{
    "editor.lineNumbers": "off"
}
```

Open a `c` file -> line number are not shown 🐛 

I would always expect the more specific identifier to have priority. More specific means less languages specified in it.

**Comment by sandy081** [comment]
At present, I treat a langue overrides more specific if they are defined for only one language otherwise they will be merged. This is also mentioned in the feature and test plan item. Hence closing this as designed.
