### ISSUE TITLE
Confusing unicode highlight option quick pick options

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#138184]
Testing #138071

<img width="616" alt="image" src="https://user-images.githubusercontent.com/876920/144100596-c29b39aa-4941-47a7-bef0-d6eae9f95e05.png">

The two quotes in `Exclude U+2066 ""` look weird/confusing even though after a second thought, it makes sense as the character is invisible. Maybe we can render something like "Exclude U+2066 (invisible character)"?

**Comment by hediet** [comment]
That's how it is now:
![image](https://user-images.githubusercontent.com/2931520/144220383-edd85f09-f3b9-435a-ab33-c2b0a571a57f.png)
