### ISSUE TITLE
provide setting to config which place the snippets can show 

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#138106]
like:

```javascript
"editor.quickSuggestions": {
    "strings": false,
    "comments": false,
    "other": true
  },
```

Add an option:

```
"editor.suggest.place": {
    "strings": false,
    "comments": false,
    "other": true
  },
```

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"snippets"
