### ISSUE TITLE
Feature Request: When Dragging A View, It Should Be Focused

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#138139]
Testing #138102

I think the SCM view should be focused (rather than the files view) at the end of the drag operation.
Otherwise it is hard to track what happened.

![recording](https://user-images.githubusercontent.com/2931520/144033774-731af1c3-caee-4fa6-8752-667aa4f64bf8.gif)

I think this should also happen when view are moved inside the main side panel.

**Comment by sbatten** [comment]
This is by-design, a decision made when we introduced dragging and dropping. This is to avoid UI churn when moving views around and allow chains of move out of the same view (e.g. moving outline and timeline out into their own activity bar entries)
