### ISSUE TITLE
crash when restart debug node.js app

### ISSUE THREAD

**Issue by oldguan** [Microsoft/vscode#13819]
when i debug the node.js app and restart debug it ,all of the application is crash 
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:28:55.412Z)
- OS Version: Darwin x64 16.0.0
- Extensions: donjayamanne.python-0.4.2, felixfbecker.php-debug-1.9.7, ms-vscode.Theme-TomorrowKit-0.1.3, ms-vscode.csharp-1.4.1, robertohuertasm.vscode-icons-3.0.5, spywhere.guides-0.5.1

**Comment by isidorn** [comment]
I can not reproduce this behavior.

Can you also reproduce this when you run vscode with `--disable-extensions`?
If not then one of the extensions is probably to blame.
Do you see this for any node workspace you use?

**Comment by oldguan** [comment]
when i run vscode with --disable-extensions and debug node app, and restart it, all application is crash include Finder. how did i get more info about crash?

**Comment by isidorn** [comment]
Can you please attach a short video / gif that captures this problem?
Do you see some errors in F1 > Toggle Developer Console?

When you say restart you mean restart the debugged node app?

**Comment by oldguan** [comment]
There is a video about this problem at https://youtu.be/LBUzm-0Jp4Y

**Comment by isidorn** [comment]
I do not really see the application crashing in the video - or am I missing something?
Do you see some errors in F1 > Toggle Developer Console?

**Comment by oldguan** [comment]
Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError

**Comment by oldguan** [comment]
end of the video, background become black that is Finder crash and Screen recording crash

**Comment by isidorn** [comment]
@bpasero please advise

**Comment by bpasero** [comment]
That developer console error is unrelated to any crash.

**Comment by isidorn** [comment]
@oldguan 
Here is a **checklist** to find out more about the freeze/slow/crash
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] there is no suspicious output when running from the command line (`code --verbose`)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line)
- [ ] it reproduces after deleting `<appdata>/User/keybindings.json` and `<appdata>/User/settings.json` (backup first! see below for paths)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`

**Comment by oldguan** [comment]
Thanks all, i will check the list and install code on another mac to test that.
thanks a lot.

**Comment by isidorn** [comment]
Closing until more data is provided

**Comment by oldguan** [comment]
it won't crash when upgrade to 1.9.0
Thanks!
