### ISSUE TITLE
documentation suggestion

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#138194]
Testing #137668

I noticed that when the title of the configuration object is the name of the extension, the settings will be top level (before other configurations)

```
{
				"type": "object",
				"title": "Z extension",
				"properties": {
					"J setting": {
						"type": "string"
					},
					"K setting": {
						"type": "string"
					},
					"L setting": {
						"type": "string"
					}
				}
			}
```
which I only realized by changing the title of the above to "Z extensions" which moved it to below A, B, and C configurations

**Comment by rzhao271** [comment]
I'll also update the docs in vnext.
