### ISSUE TITLE
setting.json 

### ISSUE THREAD

**Issue by Zorro58** [microsoft/vscode#138147]
Issue Type: <b>Bug</b>

il me refuse de changer la configuartion de la couleur de mon vscode et je n'arrive pas à le supprimer ce setting.json

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A4-6300 APU with Radeon(tm) HD Graphics     (2 x 3700)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.19GB (1.99GB free)|
|Process Argv|--crash-reporter-id 97ec7930-6eb2-4335-bc4c-1f59e38220e3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.4.0
standard-process-extension-pack|are|0.1.0
react-toolkit|Cod|1.3.10
gitignore|cod|0.7.0
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|3.1.1
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.16.4
git-project-manager|fel|1.8.2
package-plus-plus|jun|0.0.1
tailwindcss-intellisense-twin|lig|0.12.1
vscode-dapr|ms-|0.5.0
vscode-language-pack-fr|MS-|1.62.4
vs-keybindings|ms-|0.2.1
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.8.0
vscode-tailwindcss|sid|0.1.0
perforce|sle|3.2.0
pulsar-vsc-extension|Sup|1.6.6
tabnine-vscode|Tab|3.5.1
quokka-vscode|Wal|1.0.429
vscode-todo-highlight|way|1.0.5
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593:30376534
vssld246cf:30401891
vscop804cf:30404767
vs360cf:30404996

```

</details>

**Comment by rzhao271** [comment]
Are you trying to change the theme colour?
https://code.visualstudio.com/docs/getstarted/themes#_selecting-the-color-theme
