### ISSUE TITLE
'add markdown cell' button goes away when shrinking

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#138176]
Testing #138103

* set "notebook.globalToolbarShowLabel": "dynamic"
* Install Jupyter Extension https://github.com/microsoft/vscode-jupyter/suites/4497016960/artifacts/119963878
* Create a `ipynb` file or use menu File -> New File... and choose Jupyter Notebook
* Wait for the Jupyter extension to be activated after opening the ipynb file, then shrink the editor group

all buttons stay, but not the 'add markdown cell' button

![recording (2)](https://user-images.githubusercontent.com/6461412/144090353-30a174ef-4eb0-4ebe-ae2a-b310532b1632.gif)

**Comment by rebornix** [comment]
@aeschli thanks for the feedback. It's currently as designed as the Insert Code and Insert Markdown are using the same `+` icon, showing both would be confusing. We have some ideas of how to improve this, listed in https://github.com/microsoft/vscode/issues/129728

**Comment by aeschli** [comment]
I suggest to closing it as dup of #129728 then. Thanks!
