### ISSUE TITLE
Cannot clone or push or pull to Azure DevOps repos

### ISSUE THREAD

**Issue by gbrac** [microsoft/vscode#138199]
Issue Type: <b>Bug</b>

fatal: Unable to persist credentials with the 'wincredman' credential store

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (18.34GB free)|
|Process Argv|--crash-reporter-id 6548d6f2-1339-4415-9604-638c759dab50|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.28.0
flutter|Dar|3.28.0
csharp|ms-|1.23.16
azure-account|ms-|0.9.11
powershell|ms-|2021.10.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593cf:30376535
vssld246cf:30401891
vscexrecpromptt2:30404948
vscop804cf:30404767
vscop453:30404998

```

</details>

**Comment by TylerLeonhardt** [comment]
Are you pushing using VS Code's UI or using the git CLI in the terminal?

**Comment by gbrac** [comment]
I have tried both, but mainly the VS Code UI

**Comment by lszomoru** [comment]
@gbrac, could you please provide the exact steps that you are doing, and error(s) that you are getting? Thank you!

**Comment by gbrac** [comment]
Log into Azure DevOps web site, go to existing repo not already on my
machine, click Clone in VS Code button.  VS Code prompt to Allow extension
to open this URI.  Click Open and file dialog appears for where to clone
repo to locally.  Choose new folder under my profile on the hard drive,
Click Select Repository Location button.  VS Code shows error Failed to
Authenticate to Git Remote.  This is log:

Validating found git in: C:\Program Files\Git\cmd\git.exe
Using git 2.34.1.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --git-dir
Open repository: c:\Users\gregory.w.bracey\code\EndpointPrivilegeManagement
> git status -z -u
> git symbolic-ref --short HEAD
> git check-ignore -v -z --stdin
> git for-each-ref
--format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)
refs/heads/main refs/remotes/main
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
%(*objectname)
> git remote --verbose
> git config --get commit.template
> git clone
***@***.***/afs-it/Infrastructure%20Engineering/_git/EndpointPrivilegeManagement
c:\Users\gregory.w.bracey\code\test\EndpointPrivilegeManagement --progress
Cloning into
'c:\Users\gregory.w.bracey\code\test\EndpointPrivilegeManagement'...
fatal: Unable to persist credentials with the 'wincredman' credential store.
See https://aka.ms/gcmcore-credstores for more information.
Missing or invalid credentials.
Wrong number of arguments
fatal: Unable to persist credentials with the 'wincredman' credential store.
See https://aka.ms/gcmcore-credstores for more information.
fatal: Authentication failed for '
https://dev.azure.com/afs-it/Infrastructure%20Engineering/_git/EndpointPrivilegeManagement/
'

**Comment by gbrac** [comment]
Please close this issue.  We believe we have located the root cause.  It
appears due to BeyondTrust endpoint privilege management software recently
deployed.  It is breaking the authentication flow/access to stored
credentials.
