### ISSUE TITLE
Settings ask me to restart while sync is initializing

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#138131]
* have a setting that requires a restart
* use settings sync
* add another device
* 🤔 while sync'ing for the first time there, I am asked to restart and I don't know how well that ends

<img width="1066" alt="Screen Shot 2021-11-30 at 11 02 29" src="https://user-images.githubusercontent.com/1794099/144026723-912c53a8-e0b1-4252-8d32-4e78f1988916.png">

**Comment by sandy081** [comment]
It seems you have a setting that needs VS Code restart is updated. Choosing to Restart will ask you to cancel / continue the settings sync.

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/122132
