### ISSUE TITLE
Browse additional color themes not discoverable enough

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#138146]
Testing #138084

The `Browse Additional Color themes` is a very cool feature, I am just worried that it is not discoverable enough. It is just one item in the large quick pick list which can easily be missed.

An alternative idea:
When we show all the themes, at the bottom after a separator just stream more themes from the marketplace. That way I believe more users will find this feature.

I know @misolori had some concerns about this approach, so I would also like to hear his thoughts.

**Comment by aeschli** [comment]
> I am just worried that it is not discoverable enough.

It's the top item, so often it is visible. Also it is never filtered.

We can also look into a + button in the quick pick title.

**Comment by isidorn** [comment]
Yeah adding a button might help.
Once released we could measure telemetry: what's the percentage of users that opens the theme quick pick and clicks on this new button

**Comment by texastoland** [comment]
@aeschli I'm hesitant to open a separate ticket. Could it also use the default extension sort? Alphabetical ordering really limits the utility of searching for a theme.

**Comment by aeschli** [comment]
No action planed
