### ISSUE TITLE
Alignment settings are not useful for panels moved to the right

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#138172]
Testing #138101

If panels are moved to the right, the panel alignment options are not really useful...

**Comment by sbatten** [comment]
@weinand I am not sure what this means exactly, could you please share more?

**Comment by weinand** [comment]
@sbatten sorry, I forgot to include the screenshot:

<img width="1567" alt="CleanShot 2021-11-30 at 17 04 42@2x" src="https://user-images.githubusercontent.com/1898161/144130352-2e39c733-f131-404d-b2c7-708f4a945f01.png">

Here I have moved the panels (terminal etc.) from the bottom to the right of the editors. In this location none of the alignment options make any sense. So changing the alignment settings has no effect.

I wonder whether different alignments options would be possible for this location, e.g. "top", "bottom"...?

**Comment by sbatten** [comment]
thanks for the added info. there are some considerations going on with the panel position (left/right) and the new side panel. I think moving the panel left/right was long-lasting temporary solution for the inability to move views to a side(bar/panel). With the new side panel. for now, I think I can mention that this setting depends the panel being in the default position.
