### ISSUE TITLE
Ambiguous deriveFromWorkspaceTrust

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#138191]
Testing #138071

`deriveFromWorkspaceTrust` can represent different values (true or false) in unicode highlight settings and currently it's not clear what `deriveFromWorkspaceTrust` represents in each setting though. Maybe we can update the setting description to describe what's the behavior when it's set to `deriveFromWorkspaceTrust` for each setting.

**Comment by hediet** [comment]
What about `trueIfUntrusted`?

**Comment by hediet** [comment]
Fixed in 4da629d0.
