### ISSUE TITLE
`_extensions.preferPreReleases` doesn't seem to be working

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#138193]
Testing #138086

I toggled `_extensions.preferPreReleases` from true and false in my setting and this page doesn't seem to be changing at all. 

I see the following while it's set to `false`:
![image](https://user-images.githubusercontent.com/12758612/144105497-78729bf3-335d-492a-98f4-4c2e83ebe519.png)
![image](https://user-images.githubusercontent.com/12758612/144105589-42d01e2f-1471-43c8-8e42-2b50e675a19d.png)

**Comment by sandy081** [comment]
Have you reload the window after changing the setting?

**Comment by tanhakabir** [comment]
oh you're right I forgot to reload
