### ISSUE TITLE
Tasks with type `process` and a missing `command` fail too early to emit the right events

### ISSUE THREAD

**Issue by mkhl** [microsoft/vscode#138104]
Issue Type: <b>Bug</b>

See the [reproduction repo](https://github.com/mkhl/issue-process-task-for-missing-executable-drops-events), which provides two tasks `shell` and `process` and a README with these steps.

### Actual behavior

1. Run the task `process`
1. Run the task `process` again.
1. Note that each failed in its own terminal, despite what the message in the terminal said.
1. Focus the terminal and press a key to close it.
1. Run the task `shell`.
1. Run the task `shell` again.
1. Note that both failed in the same terminal, again not shared with the `process` task.
1. Without closing the terminal, run the task `process` again.
1. Note that the task reuses the terminal now, but doesn't fail. Instead it just produces no output at all, and doesn't seem to signal that it's finished.

### Expected behavior

The `process` task doesn't hang, it just fails.
Its terminal gets reused like the one from `shell`.
Ideally both tasks would emit the exact same sequence events, including both `onDidEndTask` and `onDidEndTaskProcess` so the listener can determine that the task failed.

VS Code version: Code - Insiders 1.63.0-insider (c42793d0357ff9c6589cce79a847177fd42852ee, 2021-11-29T08:08:44.056Z)
OS version: Linux x64 5.15.4-201.fc35.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1567)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|23.24GB (2.03GB free)|
|Process Argv|--disable-extensions .|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593:30376534
vsc1dst:30396469
pythonvs932:30404738
vscexrecpromptt2:30397559
vscop804cf:30404767
vs360:30404995

```

</details>

**Comment by alexr00** [comment]
@Tyriar or @meganrogge I think the cause of the problem is that `ITerminalChildProcess` `onProcessExit` doesn't fire when a process task exits with an error like this.

https://github.com/microsoft/vscode/blob/8d1b714a230dfeedb22f7d16bf55e4cc0c257ebf/src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts#L308-L309

I don't think there's anything suspicious in the shell launch configs:
![image](https://user-images.githubusercontent.com/38270282/144085627-d3a11cc4-3c3c-470b-bbaa-00baf163df37.png)

Would you expect `onProcessExit` to fire if the process errors out early like this (the command to run doesn't exist)?

**Comment by Tyriar** [comment]
When the call to create/start the process fails, like when `executable` doesn't exist, it should fire the `onProcessExit` event here:

https://github.com/microsoft/vscode/blob/f86e5d14afe60ceddb339ebc73bbd501f5029312/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1147-L1151

**Comment by alexr00** [comment]
It does do that, but it seems that something is still not cleaned up somewhere as process tasks run in a re-used terminal don't output the message at all.

**Comment by Tyriar** [comment]
If you have this repro set up could you also log these?

https://github.com/microsoft/vscode/blob/f86e5d14afe60ceddb339ebc73bbd501f5029312/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1193-L1194

This is where the output happens:

https://github.com/microsoft/vscode/blob/f86e5d14afe60ceddb339ebc73bbd501f5029312/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1202-L1207

**Comment by alexr00** [comment]
In a non-reused terminal:
- `this._exitCode` is set to undefined there.
- `exitMessage` is set to the expected message.
- `this._xtermReadyPromise.then` gets run and `xterm.raw.writeln` gets hit.

In a re-used terminal:
- None of those lines are hit.
- When I kill the terminal manually they are all hit, but all those values are undefined.

**Comment by alexr00** [comment]
@Tyriar is there a way I can tell on the tasks side if a terminal is being disposed vs. just had the above situation happen? I'd like to reuse it if it's not being disposed so that the user experience is consistent. Just iterate though the `instances` `ITerminalService` and see if the instance with the same ID is still there?

**Comment by Tyriar** [comment]
Internally we use `ITerminalLaunchError` to differentiate these:

https://github.com/microsoft/vscode/blob/695cbce42797381dee60be571b311095eebe9b14/src/vs/platform/terminal/common/terminal.ts#L540-L543

I guess we could just expose that as a type in `onExit` too, looks like tasks is still the only consumer that uses the value on the event I believe. If you want to try this, change this line:

https://github.com/microsoft/vscode/blob/33dc88051116ceceea42bdb7027a8989d3eeb763/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1412

To this or similar:

```
this._onExit.fire(exitCodeOrError)
```

**Comment by alexr00** [comment]
👍 I'll make the tasks changes in February: https://github.com/microsoft/vscode/issues/141728
