### ISSUE TITLE
Initially installing the release version of an extension that has a pre-release doesn't fully update extension editor content

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#138181]
Testing #138086

![junk](https://user-images.githubusercontent.com/6726799/144096044-2c57b24a-1b0b-4d92-a3d4-f2e9115d338b.gif)

1. Find a not-yet-installed extension for which a pre-release exists.
2. Choose to install the Release version.
3. The extra line in the header about there being a pre-release is missing until you close and reopen extension editor.

Also, when the extra line appears and you click on its link, the description correctly changes to that of the pre-release. But I see two problems:

- No visual indicator that I'm now reading pre-release info.
- No obvious way to go back to the release version's info.

**Comment by gjsjohnmurray** [comment]
> Also, when the extra line appears

@JacksonKearl has created #138233 for this aspect.

**Comment by sandy081** [comment]
I will take care of the second aspect in the issue #138233

**Comment by sandy081** [comment]
Fixed by 112ca126f6f86387f6054e8d55544d97f72f34ef
