### ISSUE TITLE
Test: Layout Control Experiment

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#138100]
Refs: #137633
- [x] macOS @jrieken
- [x] windows @misolori
- [x] web @brettcannon

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23138100%0A%0A&assignees=sbatten)

---

This milestone, we added a new ux surface for configuring the layout of VS Code. It exists in the title bar on macOS, Windows, and web when the custom titlebar is visible. Your icon may differ.
![image](https://user-images.githubusercontent.com/6561887/143954155-d1ac95be-710d-47ac-a3de-097c32f19351.png)

We intend to experiment with this surface in stable this milestone. Please verify the following:

1) `workbench.experimental.layoutControl.enabled` exists as a setting.
2) For desktop clients, verify whether or not you are in the experiment via the Issue Reporter. If the first part ends with `t` you are in the experiment. If it ends with `c` you are not.
![image](https://user-images.githubusercontent.com/6561887/143954791-ffcaa487-10f4-4d83-9e20-c405e0c32ad1.png)
3) Confirm the default value of the setting above matches your experiment value `t` => enabled `c` => disabled.
4) If necessary, enable the setting to continue testing.
5) Verify all of the actions in the menu work and reflect the workbench layout state.

As usual, provide any feedback on the experience you like or don't like.

**Comment by brettcannon** [comment]
For insiders.vscode.dev, I might not be seeing what I'm supposed to see (the sample screenshot doesn't point at exactly what I'm supposed to be looking for and there's stuff there like a triple dot menu, a puzzle piece and an icon I don't have in my editor):

![image](https://user-images.githubusercontent.com/54418/144319041-30de7bbf-2e2c-4840-9351-1caad45fb3ed.png)

Or maybe I do have it and you mean I should see the following even though it isn't the same as anything in the screenshot?:

![image](https://user-images.githubusercontent.com/54418/144319154-da98a74b-daf0-4a23-96ac-a232e42ccb14.png)

I'm going to assume the latter is what you're after, in which case it all works!
