### ISSUE TITLE
Testing markdown preview editor : Links don't seem to work? 

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#138196]
Testing #138040

Opening this file here:
vscode-docs\docs\getstarted\tips-and-tricks.md

And clicking on any of the links doesn't seem to work? Maybe the path is invalid though. Not sure. 

Example:

```
[Running VS Code on Linux](/docs/setup/linux.md)
```
Fails.

If I change it to this, it works:

```
[Running VS Code on Linux](..\\setup\\linux.md)
```

**Comment by sanathusk** [comment]
I see the same behavior in my case.Clicking on link that points to md file within the project don't open the  file.Links to website opens up.
