### ISSUE TITLE
values of "workbench.experimental.panel.alignment" setting have inconsistent grammatical forms 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#138164]
Testing #138101

"justified" has a different grammatical form than the other three: 
<img width="225" alt="CleanShot 2021-11-30 at 16 03 02@2x" src="https://user-images.githubusercontent.com/1898161/144071990-d7cba444-80d5-4c2d-ad1a-051972704d17.png">

**Comment by sbatten** [comment]
will switch to "justify"
