### ISSUE TITLE
Extensions viewlet and views cannot be dragged into panel or side panel

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138123]
Not sure why?

**Comment by sandy081** [comment]
It is designed. These views are tightly coupled with the viewlet toolbar (search & filters). Hence I chose not to move these views across. It only makes sense if you move complete viewlet rather than individual views here.

**Comment by bpasero** [comment]
Yeah I wasn't able to move the entire extensions viewlet either.
