### ISSUE TITLE
Confusing unicode exclusion option for U+202e

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#138187]
Testing #138071

<img width="753" alt="image" src="https://user-images.githubusercontent.com/876920/144101403-80f0d5cd-b9be-46dd-9426-79f06512153a.png">

U+202E is RIGHT-TO-LEFT OVERRIDE but not sure what "dethgilhgih ..." means ...

**Comment by hediet** [comment]
It is reversed :D
Nice catch of that unicode injection attack.

**Comment by hediet** [comment]
Because all such control characters are invisible, the fix for #138184 also fixes this:

![image](https://user-images.githubusercontent.com/2931520/144234184-6a00eec5-696a-475d-9f69-46e97cecdfaf.png)
