### ISSUE TITLE
File order in explorer not alphabetical if hexadecimal

### ISSUE THREAD

**Issue by brezeeger** [microsoft/vscode#138183]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Create a directory with filenames that start as hexadecimal.

If the file name starts with a number, it is sorting by the number until the first non-numerical character, and then alphabetically sorting after that. It seems to be assuming the entire string is a number. I presume this is to make sure it goes in order on [1.png, 2.png, ... 9.png, 10.png, 10updated.png, 11.png, ...].

The order of my (truncated) autogenerated files are:

1c67...py (1...c6)
1c97...py (1...c9)
01df...py (1...df)
1ef4...py (1...ef)
2a18...py (2)
5a40...py (5...a)
5d7a...py (5...d)
6b8f...py (6)
7fb3...py (7)
15c3...py (15)
19c9...py (19)
20b4...py (20)
26b0...py (26)
34b8...py (34)
...
93e9...py (93)
200d...py (200)
831d...py (831)
7637031a...py (7,637,031)
94425022c...py (94,425,022)

Alphabetical from this point forward
a656...py
a910...py

I think it could just use a little extra logic to decide whether the alphabetical sort or numerical sort takes hold. It might even be worth doing a base 16 sort instead of a base 10 sort at the start instead. No idea what's actually best, but it is super annoying to open a specific file when it starts with a 2 but is actually near the bottom of a long list. At least now I know the pattern it's using to sort, whereas beforehand it just seemed mostly correct with weird errors.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.57GB free)|
|Process Argv|--crash-reporter-id 0da48b81-247b-401a-83a6-ca57dafe498c|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593:30376534
vssld246cf:30401891
pythonvs932cf:30404740
vscexrecpromptt1:30404947
vscop804cf:30404767
vs360:30404995

```

</details>

**Comment by JacksonKearl** [comment]
`"explorer.sortOrderLexicographicOptions": "unicode"` should do what you want
