### ISSUE TITLE
SCM View Looks Different Right/Left

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#138136]
Testing #138102

Is it by design that the SCM looks slightly different?

* Right:

![image](https://user-images.githubusercontent.com/2931520/144033306-14996a0d-3f98-4014-a4eb-0c479774ef23.png)

* Left:

![image](https://user-images.githubusercontent.com/2931520/144033371-b7d70d08-a36c-40a1-89cb-89fc089f6896.png)

**Comment by IllusionMH** [comment]
Maybe related to #136803 where Tree View in References had different background
