### ISSUE TITLE
Delta extensions related exceptions when untrusting or trusting a workspace

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#138192]
Repros:

Trust a workspace:

<img width="582" alt="Screen Shot 2021-11-30 at 10 18 43 am" src="https://user-images.githubusercontent.com/2193314/144105326-e5221fd9-b311-4002-9d29-8c61337bfb87.png">

Untrust a workspace:

<img width="561" alt="Screen Shot 2021-11-30 at 10 22 47 am" src="https://user-images.githubusercontent.com/2193314/144105569-cb0ba883-395b-48ab-97fe-efea55a781a3.png">

**Comment by sandy081** [comment]
I cannot repro the first error but can repro the second. Fixed it.
