### ISSUE TITLE
Certificate expired errors

### ISSUE THREAD

**Issue by mcrobbj-abrdn** [microsoft/vscode#138132]
Getting certificate expired errors. with no details which certificates VSC is using so I can investigate.
Happens in two plugins thunderclient ( they dont know the default certs  and openapi security check.

**Comment by mcrobbj-abrdn** [comment]
![image](https://user-images.githubusercontent.com/93191982/144199223-f77c4f06-7e26-45c3-8398-de8f95b4fb18.png)
Not sure it helps this is for thunderclient and the message for open api is:
Unexpected error when trying to request token: RequestError: certificate has expired

So its obviously a shared cert that VSC uses, all I need to know is which one so I can look to update.

**Comment by hb20007** [comment]
It is probably related to https://github.com/microsoft/vscode/issues/136787
If so, https://github.com/microsoft/vscode/issues/136787#issuecomment-969065291 worked for me.

**Comment by TylerLeonhardt** [comment]
What do you think @deepak1556 ?

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/136787

Please use `http.systemCertificates: false` as a workaround.
