### ISSUE TITLE
Extensions editor content overlaps header

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#138130]
Testing #138086

* open extensions editor for "GitHub.vscode-pull-request-github"
* the body overlaps the header

<img width="790" alt="Screen Shot 2021-11-30 at 10 53 13" src="https://user-images.githubusercontent.com/1794099/144024983-dd1a559e-fa97-4f20-9f4d-c2d90a1dfbe3.png">

**Comment by joaomoreno** [comment]
Even though I can't repro on demand, I have seen this in real life. It's a missing call for the webview iframe.
