### ISSUE TITLE
Cannot turn off matching brackets

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#138134]
Version: 1.63.0-insider
Commit: b9cf83f70bb6b4697b544a97c7056dfd28fccc5f
Date: 2021-11-30T05:13:11.628Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Not that I want to, but `"editor.matchBrackets": "never"` does not work.

**Comment by hediet** [comment]
I cannot reproduce this:

![recording](https://user-images.githubusercontent.com/2931520/144059583-7d2257b1-b32f-4540-96c8-f334e75fc51b.gif)

**Comment by chrmarti** [comment]
Mistook it for `"editor.bracketPairColorization.enabled"`, closing. :)
