### ISSUE TITLE
react-native launch fail after changing app name

### ISSUE THREAD

**Issue by atlanteh** [Microsoft/vscode#13811]
- VSCode Version: 1.6.1
- OS Version: mac 10.11.6

Steps to Reproduce:

1. Create new react-native app
2. Build it with vscode
3. Change the app name via Xcode
4. Try building with vscode
5. build succeed.
6. launch fail
I get error:

Touch Build/Products/Debug-iphonesimulator/NewMyApp.app
    cd /Users/myUser/git/myApp/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /usr/bin/touch -c /Users/myUser/git/myApp/ios/Build/Products/Debug-iphonesimulator/NewMyApp.app
** BUILD SUCCEEDED **

// vscode is trying to install my old app name -->
**Installing build/Build/Products/Debug-iphonesimulator/OldMyApp.app**
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/OldMyApp.app/Info.plist

**Comment by isidorn** [comment]
Please file this against the vscode react extension here https://github.com/Microsoft/vscode-react-native

Thanks
