### ISSUE TITLE
Please rename "TypeScript React" to "TypeScript JSX", and "JavaScript React" to "JavaScript JSX"

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#138285]
The name "TypeScript React" nowadays is non-inclusive of all the libraries/frameworks out there that are built on JSX, but that are not React.

React is not the only lib/framework that has JSX syntax!

Let's make the field a fair play ground for all JSX libs.

This is what I'm referring to:

![Screenshot from 2021-12-01 09-18-16](https://user-images.githubusercontent.com/297678/144282085-ed5abc2b-4c8b-4bb6-a9c1-b833f1f1f585.png)

(it even shows React's logo)

I'm writing an app with [Solid.js](https://solidjs.com), for example. I'm not using React, and "TypeScript React" has no meaning in the context of a Solid app.

**Comment by trusktr** [comment]
Other libs/frameworks include [Surplus](https://github.com/adamhaile/surplus), [Preact](https://preactjs.com/), [Stenciljs](https://stenciljs.com/), etc.

**Comment by mjbvz** [comment]
Changing the display name is easy but we can't change the identifier. Also any new name should still mention react for the sake of all the documentation/tutorials out there that  talk about `TypeScript React`. For example: `TypeScript JSX (React)`

**Comment by trusktr** [comment]
`TypeScript JSX (React)` has the same issue. If I am in a Solid.js project, it has nothing to do with React.

Can there be a deprecated alias instead?

**Comment by rauchg** [comment]
`TypeScript JSX / React` could be another friendlier option to alternatives.

**Comment by Shinigami92** [comment]
I don't understand the association with `React`?
Why not `TypeScript JSX / Preact / React / Solid / Stenciljs / Surplus / Svelte / Vue` :roll_eyes: 
And I'm sure I missed some...

**Comment by mallardduck** [comment]
If there is a concern of keeping the UI consistent with existing (recent) content written about VS code, then why not treat the change as a depreciation of sorts?

First change it to:
Typescript JSX (previously Typescript React)

Then with time docs can be updated to use the correct "Typescript JSX" and any community made docs/blogs could update as well.

Then finally just remove the parentheses part completely when first party Docs are all confirmed updated to refer to it as "Typescript JSX".

Even if it's not as direct of a fix, this still allows the root concern to be addressed and gives a nice path for it to happen.

**Comment by numToStr** [comment]
I just wana say that the title is the best candidate for the change but not the identifier i.e `typescriptreact`. If you change that the whole community would break.

**Comment by Shinigami92** [comment]
Just introduce an alias and deprecate it slowly in a 2-year frame or somewhat

**Comment by mallardduck** [comment]
Couldn't the identifier either: a) change over time the same I suggested the title, and/or b) have the old one kept as an alias?

**Comment by numToStr** [comment]
Nope, identifier shouldn't have to change. You are talking about the decade old tooling and others century old editors (i.e vim/neovim) that depends on the identifier to detect/set the file type.

**Comment by kaleidawave** [comment]
How about a new language type with identifier `typescript-jsx` and display name "TypeScript JSX" with the ts logo and clone of the existing `typescriptreact` grammar definitions. Set it's precedence in the list higher than `typescriptreact`. Then `typescriptreact` can be deprecated and eventually removed at some later date.
