### ISSUE TITLE
open from recent list does not open local window

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#138282]
- install the remote repositories extension and a remote extension (e.g. wsl)
- open a remote repository
- open remote window
- use command `File: Open Recent...' and pick the remote repository
you end up in wsl window showing a remote repo

Its a bug with the  `File: Open Recent...' picker, works with the recent menu in the menu toolbar

**Comment by aeschli** [comment]
fixed by 38043d00949164b7eb5f14dbaa9b6680b5ac26be

**Comment by joyceerhl** [comment]
Works great now, thank you @aeschli!
