### ISSUE TITLE
Quick pick error decoration makes picker grow

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138247]
![recording](https://user-images.githubusercontent.com/900690/144210596-622fd891-82d8-4b51-985c-c671fff93646.gif)

//cc @chrmarti

**Comment by bpasero** [comment]
tbh it looks to me as if the picker is too small initially:

![image](https://user-images.githubusercontent.com/900690/144210732-f44ff5fc-da21-4716-a3ac-154c759508ad.png)

**Comment by TylerLeonhardt** [comment]
verification:

find the input box @bpasero used
or
add this code to an extension:
```ts
await window.showInputBox({
		prompt: 'Enter something from the alphabet',
		ignoreFocusOut: true,
		placeHolder: 'a letter',
		validateInput(value) {
			return isNaN(parseInt(value)) ? undefined : 'That is not in the alphabet!';
		}
	});
```

then cause the the error message to show up and ensure that the quick pick doesn't grow at all and that when there is no error the picker looks better than @bpasero's 2nd screenshot.

**Comment by bpasero** [comment]
The error box now jumps out of quick pick widget:

![image](https://user-images.githubusercontent.com/900690/151117527-9d11f05e-ed07-4b2c-a79d-043b38129c3c.png)

But the original issue is solved.
