### ISSUE TITLE
`code` command not working if the file not exist

### ISSUE THREAD

**Issue by TTTPOB** [microsoft/vscode#138295]
- VSCode Version: 1.62.3
- Local OS Version: windows 19043.1348
- Remote OS Version: `CentOS Linux 7 (Core) x86_64; kernel: 3.10.0-1062.9.1.el7.x86_64`
- Remote Extension/Connection Type: SSH
- Logs: not applicable I think, but attached here
[logs.txt](https://github.com/microsoft/vscode-remote-release/files/7634122/logs.txt)

Steps to Reproduce:

1. connect to remote host using ssh-remote plugin, version `0.66.1`
2. hit below command in the integrated terminal `code a_file_not_exsist`

Expected Behavior:
a file opened in vscode with the name `a_file_not_exsist`, as this is the behavior about 1 month ago;
from some day the behavior changes, I dont remember the date.

Behavior:
nothing happened, the command just did nothing
if I `touch a_file_not_exsist; code a_file_not_exsist`, it worked however

Does this issue occur when you try this locally?: no, on native windows, it works fine, on wsl2 it do not work like microsoft/vscode-remote-release#5885 
Does this issue occur when you try this locally and all extensions are disabled?: no

**Comment by bpasero** [comment]
This is becoming the most annoying issue....

**Comment by bpasero** [comment]
Sounds a bit like the regression Lad fixed, though this is not insiders but stable.

**Comment by aeschli** [comment]
Sounds like a dup of https://github.com/microsoft/vscode/issues/137409

I tested the given steps in the latest insiders build ( 1.63.0-insider, 68a1e2f872f8869b004eec284917782474730e0b, Date: 2021-12-02T05:15:40.605Z) and it seems to work also on SSH.

@TTTPOB Can you give it a try there to verify: https://builds.code.visualstudio.com/builds/insider

**Comment by TTTPOB** [comment]
> Sounds like a dup of #137409
> 
> I tested the given steps in the latest insiders build ( 1.63.0-insider, [68a1e2f](https://github.com/microsoft/vscode/commit/68a1e2f872f8869b004eec284917782474730e0b), Date: 2021-12-02T05:15:40.605Z) and it seems to work also on SSH.
> 
> @TTTPOB Can you give it a try there to verify: https://builds.code.visualstudio.com/builds/insider

hmmm but I cannot access this resource but download vscode insider build from the https://code.visualstudio.com/insiders/ did help me. it worked so I think I can expect this to be fixed on next release

**Comment by aeschli** [comment]
@TTTPOB Thanks for trying it out!
