### ISSUE TITLE
Starting vscode via "Start-Process code -credential ..." result in a startup crash

### ISSUE THREAD

**Issue by roy-t** [microsoft/vscode#138243]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- OS Version: 19042.1348 (Windows 10 Enterprise)
- Powershell version: 5.1.19041.1320

Steps to Reproduce:

I'm usually running powershell as an administrator due to corporate policies. However running vscode as administrator has some quircks so I'd rather run vscode as a regular user. Therefor I would like to start vscode like this:

```ps1
 start -FilePath code -NoNewWindow -credential "LOCAL\myuser"
 ```

If I do this vscode immediately crashes, while if I remove the -credential option everything works great. I've also tried this with notepad and there it seems to work perfectly. I've tried the following to get closer to identifying the problem:

Running with the extra arguments  `-PassThru -Wait -ArgumentList "--disable-extensions"`, no effect and I see that the exit code is a `1` so that doesn't help much. 

Running with `-PassThru -Wait -ArgumentList "--crash-reporter-directory C:\somepath"`, but that didn't result in any *.dmp files.

I'm at a complete loss at what would cause this problem as I guess it should be transparant to vscode how it is launched.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by roy-t** [comment]
Hey @bpasero, I've already followed those steps, hence why I ran it with the --crash-reporter-directory arguments. Are there any other steps you would like me to try? Could you reproduce the issue?

**Comment by bpasero** [comment]
Yeah, attach the crash dump file if any.

**Comment by roy-t** [comment]
As was already in the text...  "but that didn't result in any *.dmp files." :-)

**Comment by deepak1556** [comment]
Thanks for the repro steps, I am unable to repro the crash with a system installation flavor of either stable or insiders version on `Windows 11 Pro 21H2 22000.348`

@roy-t just to confirm are you attempting the launch with a `system setup` or `user setup` installation of vscode ?

**Comment by roy-t** [comment]
I've now tried on a different computer and there it all works as expected.  In both cases its a user installation. Looks like there might be something else wrong with my work laptop that makes this crash. I'll keep digging to see if I can find useful info. But I'll close this for now until I know more.

Thanks for checking!
