### ISSUE TITLE
Screen cheese when expanding collapsing notebook cells

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#138218]
Does this issue occur when all extensions are disabled?: N/A

Version: 1.63.0-insider (user setup)
Commit: 827f76521d33a61c19e92160649a0a6af8bad132
Date: 2021-11-30T11:58:52.241Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Create two cells, one markdown & one code cell
2. Use the commands to toggle collapse state of the input cells

See recording
![recording (1)](https://user-images.githubusercontent.com/1948812/144143490-50cd9d5f-777c-4c36-8c5e-93418759f738.gif)

**Comment by rebornix** [comment]
This is caused by moving collapse state out of metadata.

**Comment by joyceerhl** [comment]
Verified in Code-OSS running out of sources
