### ISSUE TITLE
Notebook toolbar flashes when toggling label visibility from "never" to "dynamic"

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#138207]
Testing #138103

Steps:
1. Install the Jupyter Extension at https://github.com/microsoft/vscode-jupyter/suites/4497016960/artifacts/119963878
2. Open a notebook, wait for the extension to be activated
3. Resize the window (or open a split view) so that some of the labels will have to be hidden if the "Dynamic" option is picked
3. Toggle the `notebook.globalToolbarShowLabel` setting from Always to Never to Dynamic, notice that the toolbar flashes before updating the labels:

https://user-images.githubusercontent.com/51720070/144119505-11403f75-ade4-4f40-a839-2e4354e56b9f.mp4

**Comment by rebornix** [comment]
let's track it with other global toolbar button width calculation issues like https://github.com/microsoft/vscode/issues/135886
