### ISSUE TITLE
"Install Another Version" shows incorrect timestamps

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#138234]
Testing #138068

I have an extension which I published 0.0.1, 0.0.2, then after a while 0.0.4, then 0.0.3, all using the odd/even : release/pre-release convention. When I go to "Install another version", the picker incorrectly shows 

![image](https://user-images.githubusercontent.com/8586769/144173462-50e31f63-b8e6-4abc-86d0-666a0b61238a.png)

It treats all but 0.0.1 as "just now" even though 0.0.2 was around the same time as 0.0.1, and even the others were >10 minutes ago.

**Comment by sandy081** [comment]
Can you please share me the extension to try and repro?

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/144308830-fbea1dc8-3854-495a-9eea-89003335d061.png)

They're now showing up as all "1 hour ago", when in fact it's more like 12 hours ago

https://marketplace.visualstudio.com/items?itemName=jaaxxx.pre-release-test.

**Comment by joyceerhl** [comment]
It's hard to tell whether this is working correctly now 
![image](https://user-images.githubusercontent.com/30305945/144512615-4d14c311-1115-4a1b-b506-f02f066b5144.png)

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/144519226-f7aedd59-3a15-4261-931f-65a21ff0be5b.png)
looks good
