### ISSUE TITLE
Kotlin support in VS code

### ISSUE THREAD

**Issue by srinikesh2929** [microsoft/vscode#138270]
I'd like to have Kotlin support for VS code (at least IntelliSense)

**Comment by lramos15** [comment]
There are a few extensions
https://marketplace.visualstudio.com/items?itemName=fwcd.kotlin
https://marketplace.visualstudio.com/items?itemName=mathiasfrohlich.Kotlin

**Comment by srinikesh2929** [comment]
> There are a few extensions https://marketplace.visualstudio.com/items?itemName=fwcd.kotlin https://marketplace.visualstudio.com/items?itemName=mathiasfrohlich.Kotlin

The Language Server is not running. It always shows Internal error

**Comment by lramos15** [comment]
That would be a bug to file on the extension. VS Code is built to be extensible via the extension API and therefore language support is added by external parties who are more versed in these languages than we are.
