### ISSUE TITLE
Google utils error on stdout redirect within vscode terminal only

### ISSUE THREAD

**Issue by jimsnab** [microsoft/vscode#138265]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:00:36.721Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-40-generic snap

Steps to Reproduce:

1. Run `gsutil ls -b gs://my-bucket > /tmp/x.txt` in terminal
(edit bucket url to something you can access)

Result:

```
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
PermissionError: [Errno 13] Permission denied
```
If this same command is run in a bash terminal outside of vscode, it works fine.

Also, strangely, I am able to redirect output of other things like `echo` or `kubectl`. I'm only having this problem with `gsutil` and `gcloud` utils.

**Comment by Tyriar** [comment]
Does this happen when you install the deb or rpm? I suspect it's related to the snap package.
