### ISSUE TITLE
"This extension has a Pre-Release version available" link is confusing

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#138233]
Testing #138068
![recording (4)](https://user-images.githubusercontent.com/8586769/144172269-c35463fe-0b0a-479f-b8ec-01f3bb4ae1a1.gif)

When I click this it triggers a reload of the lower half of the extension details page (I presume if there were a difference there in the pre-release version it'd show up here), but things like the version number don't change, and the link doesn't go away. I get that in some cases the README for the pre-release version might have relevant info, but I feel like in many cases this will cause more confusion than benefit.

**Comment by gjsjohnmurray** [comment]
Also, no obvious way to get back to seeing the information for the Release version.

**Comment by sandy081** [comment]
@gjsjohnmurray There is an action in the dropdown of gear icon to Show the Pre-Release version.

**Comment by sandy081** [comment]
I like the idea from @weinand  in #138264 - This needs some UX exploration and study. Hence postponed that to next release. 

For this release, I fixed the current flow

- Removed the **Pre-Release version** link in favor of **Show Pre-Release / Release version** actions in gear icon.
- Fixed extension editor to show the asked version

<img width="890" alt="image" src="https://user-images.githubusercontent.com/10746682/144317668-4124a251-c35e-4599-90e5-b549372076c0.png">
