### ISSUE TITLE
Moving a file to a folder, incorrectly duplicated and then deleted entire file

### ISSUE THREAD

**Issue by NathanBlaise** [microsoft/vscode#138225]
Issue Type: <b>Bug</b>

I had created a file (.py - Python Script) in a folder and finished editing it. I then saved it, in addition to having the auto-save feature on. I wanted to add this to an additional subfolder, so I created a new folder within the containing folder and dragged the file into the newly created folder. After doing this, on my file explorer view in VS Code it appeared the file had duplicated - it was both in the new folder and the original folder. I dragged the file that was outside of the newly created folder into it again, and was prompted with 'This file already exists in this folder. Do you want to replace it?' (not verbatim) to which I clicked yes. After doing this I was then met with an error from VSCode stating that the file in that path could not be found. I then saw no copies of the original file in either folder, nor in my system's Recycle Bin, or anywhere on my system's file directory.

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (1.72GB free)|
|Process Argv|--crash-reporter-id 868299c9-c8c4-44d1-a54b-f546f6fa2da8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
LinkCheckMD|bla|0.3.1
npm-intellisense|chr|1.4.0
vscode-markdownlint|Dav|0.45.0
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
powershell|ms-|2021.10.2
vscode-typescript-tslint-plugin|ms-|1.3.3
azurerm-vscode-tools|msa|0.15.5
code-spell-checker|str|2.0.13
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593cf:30376535
vssld246:30386377
vscexrecpromptt2:30400062

```

</details>

**Comment by JacksonKearl** [comment]
I am sorry to hear that you lost data, that should not happen. Are you able to reproduce this issue? I have not heard of any other cases of this and I can't reproduce it myself so I'm not sure exactly whats going on here.
