### ISSUE TITLE
VS Code doesn't recognize an imported VSIX to be pre-release

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#138271]
Testing #138068

After a installing a downloaded VSIX of pre-release Mock Debug 1.47.1 into VS Code,
VS Code still offered to "Switch to the Pre-Release" version (and it did not noticed that a version 1.47.2 was already available).

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/1898161/144260654-d18b0472-22b9-482b-b742-e325fc02d182.png">

Could it be that VS Code doesn't know whether a VSIX is pre-release or stable?

**Comment by sandy081** [comment]
Great catch
