### ISSUE TITLE
Native TODO highlighting in comments

### ISSUE THREAD

**Issue by lanehogan1** [microsoft/vscode#138267]
A feature that adds highlighting or underlining for TODO tags in comments (also FIXME, NOTE, etc.) like some extensions on the marketplace. With this, having a tab in the bottom terminal pane to search through TODOs would be useful for productivity.

**Comment by tjx666** [comment]
recommend https://github.com/Gruntfuggly/todo-tree, that extension still under maintain.But another extension about color https://github.com/KamiKillertO/vscode-colorize seems not maintained.

**Comment by HaraldKi** [comment]
If someone is anyway using ESlint, this comes close: https://eslint.org/docs/rules/no-warning-comments .
