### ISSUE TITLE
Rust Grammar has little control over keyword theming

### ISSUE THREAD

**Issue by pouyakary** [microsoft/vscode#138280]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- OS Version: macOS 12.0.1 (21A559)

It is very hard to add keyword customizations to the Rust language for the Visual Studio Code as you can see they are all generally marked:

<img width="635" src="https://user-images.githubusercontent.com/2157285/144276200-4ea1d639-f130-4482-a68f-9f8001f7ef12.png">

Here for example, it is expected to be `keyword.other.in.rust`

<img width="612" src="https://user-images.githubusercontent.com/2157285/144276208-f67a48b5-bb57-42cf-ad37-8204751af8db.png">

**Comment by aeschli** [comment]
Needs to be improved in https://github.com/dustypomerleau/rust-syntax. Please file an issue there.

**Comment by pouyakary** [comment]
@aeschli sure 👍🏻
