### ISSUE TITLE
Show Line Number Configuration in Search Settings is Invalid

### ISSUE THREAD

**Issue by caibingcheng** [microsoft/vscode#138255]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.62.2
- OS Version: Linux x64 5.4.0-90-generic

Steps to Reproduce:

1. Uncheck Show Line Numbers
2. Search a file, but line numbers show still

**Comment by IllusionMH** [comment]
Are you using Find in Files view or Search Editor (do not confuse with Find widget for current editor)?

If former: Are you performing new search in Find in Files or just look at previous results in Find in Files view?
If you already have results you need to perform new search, as results won't be re-rendered on settings change.

If later: see #92698

**Comment by caibingcheng** [comment]
Thanks, I using Find in Search Editor.

Disable line numbers will help check log in search editor, as I can sort the searched logs(from different log file) by timestamp, otherwise, they will sort by line number.
So, disable selection/display of line numbers by config may be better?

**Comment by JacksonKearl** [comment]
It's not very clear to me what you want here. Could you give an example screenshot of the UI you don't like and a description of what you'd like changed? Also what steps you have tried to fix it already.

**Comment by caibingcheng** [comment]
I have not fix it. I mean that I know it's able to disable show line number in Files view but not able to in Search Editor.

In [#92698](https://github.com/microsoft/vscode/issues/92698#issuecomment-599277484)  you said "In fact the line number is the means by which we link lines to their locations in the source text, so it must be present."  But there are some issue when search and sort in log directories, for example:

Search error log:
![Screenshot from 2021-12-22 14-17-32](https://user-images.githubusercontent.com/15170019/147045205-7afbe744-2b3e-48aa-ae92-014c1bc49c42.png)

Select all and sort:
![Screenshot from 2021-12-22 14-18-27](https://user-images.githubusercontent.com/15170019/147045223-e7359e4e-a472-4b9b-8e42-e87e3e891a19.png)

The results are **sorted by line number strings but not timestamp in log**:
![Screenshot from 2021-12-22 14-18-37](https://user-images.githubusercontent.com/15170019/147045239-93a03e00-3af2-44dd-8227-4512d54fa740.png)

In this case, hide the line number in display (they are exist in memory still) or disable selection may be helpful.

**Comment by JacksonKearl** [comment]
Hm, I see your point. It's difficult to synchronize in-memory data structures with the contents of the editor, but we could theoretically provide a way to write the raw contents to clipboard or something? Would that work for your use cases?

**Comment by caibingcheng** [comment]
> Hm, I see your point. It's difficult to synchronize in-memory data structures with the contents of the editor, but we could theoretically provide a way to write the raw contents to clipboard or something? Would that work for your use cases?

Thanks! Write the raw contents without line numbers to clipboard may be helpful to my usecase.
