### ISSUE TITLE
Wrong error message when no release extension is available

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#138215]
Testing #138068

- Publish a pre-release extension, and no "release" version
- Click to install the "release" version
- Get a misleading error message:

![image](https://user-images.githubusercontent.com/323878/144138838-7676c9d4-4be0-47d9-80d4-c33b01f89398.png)

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/138231

Install Release Version action is not shown if there is no release version
