### ISSUE TITLE
IndexedDB: "before each" hook for "runInTransaction"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138272]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=145059&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=0130b579-6834-5f43-f91f-f53497a6d032&l=8962

Maybe CI not healthy, not sure:

```
2) IndexedDB
       "before each" hook for "runInTransaction":

      Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      + expected - actual


  

  3) IndexedDB
       "after each" hook for "runInTransaction":

      TypeError: Cannot read property 'close' of undefined
      + expected - actual


      at Context.<anonymous> (file:///Users/runner/work/1/s/out-build/vs/base/test/browser/indexedDB.test.js:11:23)

```

**Comment by sandy081** [comment]
Cant repro locally and not seeing the failure in the builds, may be issue with that specific CI instance. Will keep 👀

**Comment by Tyriar** [comment]
It happened again, please action it even though you can't repro locally:

Test has flaked 3 times in last 30 days:

![image](https://user-images.githubusercontent.com/2193314/145075562-899ae088-0bd8-41a9-bedd-015f06dca54c.png)

after each also fails

```
  1) IndexedDB
       "before each" hook for "runInTransaction":

      Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      + expected - actual


  

  2) IndexedDB
       "after each" hook for "runInTransaction":

      TypeError: Cannot read property 'close' of undefined
      + expected - actual
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=145777&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=0130b579-6834-5f43-f91f-f53497a6d032&l=9061

**Comment by sandy081** [comment]
Seems IndexedDB is not getting opened by the browser and I do not know why. Since it is browser released, marked it flaky.
