### ISSUE TITLE
Add support proper syntax highlighting and support for indented sass(NOT scss)

### ISSUE THREAD

**Issue by kprem193** [Microsoft/vscode#13820]
- VSCode Version: 1.6.1
- OS Version:Win 10

Steps to Reproduce:

1. 
2. 

the intellisense is not working for indented sass originally
then i used a marketplace extension sass(by Robin Bentley) which gives some syntax highlighting but not all.

![1](https://cloud.githubusercontent.com/assets/22637351/19415233/8e688a58-9387-11e6-969b-f68161986147.jpg)
![2](https://cloud.githubusercontent.com/assets/22637351/19415234/8e6a4d52-9387-11e6-8e8c-8cfb18537349.jpg)

first one is for css
second is for indented sass

you can see the diffrence

**Comment by aeschli** [comment]
There are extensions for indented SASS. Please try these and help improving there.
