### ISSUE TITLE
Source Control not working

### ISSUE THREAD

**Issue by Esger** [microsoft/vscode#138278]
Issue Type: <b>Bug</b>

Trying to view the Source Control tab (on the left) in a freshly cloned repo with .git directory in place (or even a new clean repo with git inited) vsCode only offers a button with 'Initialize Repository'

When I push that button, it says 'Git: spawn usr/local/bin/git ENOENT' and buttons 'cancel' and 'Open Git Log'.

Open Git log says (in terminal) 
Validating found git in: usr/local/bin/git
Using git 2.23.0 from usr/local/bin/git
Opening repository for path='/Users/esgerjellema/Workspace/frontend-aurelia' failed; ex=spawn usr/local/bin/git ENOENT {
  "gitErrorCode": "NotAGitRepository"
} .. and more of such.

I tried many things like disabling extensions, reinstalling xcode command-line-tools, accept licence, many other solutions I could find on the web, but to no avail.

VS Code version: Code 1.62.3 (Universal) (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 3|
|Memory (System)|16.00GB (0.85GB free)|
|Process Argv|--crash-reporter-id 2d6f446a-c6c8-4899-a3d5-4999669b5c7c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aga|0.5.0
atlascode|atl|2.10.0
aurelia|Aur|2.0.7
vscode-style-formatter|dwe|1.0.0
gitlens|eam|11.7.0
prettier-vscode|esb|9.0.0
auto-rename-tag|for|0.1.9
beautify|Hoo|1.5.0
git-graph|mhu|1.30.0
vscode-autoprefixer|mrm|3.0.1
es6-css-minify|olb|3.3.2
vscode-yaml|red|1.2.2
vscode-sort-json|ric|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
vscexrecpromptt2:30404948
vscop804cf:30404767
vs360cf:30404996
vsrem710cf:30405999

```

</details>

**Comment by lszomoru** [comment]
@Esger, sorry for not getting back to you on this until now.
Can you please confirm that you are unable to initialise a repository using the following steps: 
- Create a new folder `foo`
- In terminal navigate inside the `foo` folder and type `code-insiders .`
- Open the SCM viewlet and click on the "Initialize Repository" button.
- If it fails, can you please share the contents of the git output?

In the terminal could you also please run `whereis git` and send me the output.

**Comment by Esger** [comment]
Hi, thank you for reaching out.

I tried what you suggested and I get this error message when I type
code-insiders . :

zsh: command not found: code-insiders

With bash shell I get the same error.

So I install code-insiders first and open the foo folder from within
code-insiders - started manually (not from terminal)
Then I could press Initialize Repository and that works.
Not sure about the git output you ask for, but I included the zipped .git
folder here.

Should I use code-insiders i.s.o. vsCode then?


Kind regards,

Esger Jellema


Voermanhaven 19
9742 VR  Groningen
M 06 49 68 68 93

<http://nl.linkedin.com/in/esgerjellema>*Profiel van Esger Jellema
weergeven <http://www.linkedin.com/in/esgerjellema>*


Op vr 10 dec. 2021 om 11:29 schreef Ladislau Szomoru <
***@***.***>:

**Comment by lszomoru** [comment]
Are you saying that everything is working as expected in VS Insiders? 
What about if you upgrade to the latest version of VS Code (`1.63` which was released this week)?

**Comment by Esger** [comment]
I already had the newest version of VS Code

Version: 1.63.0 (Universal)

Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e

Date: 2021-12-07T05:15:48.091Z (3 days ago)

Electron: 13.5.2

Chromium: 91.0.4472.164

Node.js: 14.16.0

V8: 9.1.269.39-electron.0

OS: Darwin x64 21.1.0


Which is not working as aspected... it's not recognizing the git repo.
VS Insiders is indeed working as expected.. source control, git-lens
extension and others all fine.


Kind regards,

Esger Jellema


Voermanhaven 19
9742 VR  Groningen
M 06 49 68 68 93

<http://nl.linkedin.com/in/esgerjellema>*Profiel van Esger Jellema
weergeven <http://www.linkedin.com/in/esgerjellema>*


Op vr 10 dec. 2021 om 13:19 schreef Ladislau Szomoru <
***@***.***>:

**Comment by lszomoru** [comment]
While its great that things are working in Insiders I really want to get to the bottom of why things are broken in Stable.
1. Could you start VS Code Stable using `code --disable-extensions` and see if that resolves the problem?
2. Could you start VS Code Stable using `code` and see if invoking the `Git: Show Git Output` from the command palette resolves the issue?

**Comment by Esger** [comment]
Hi, good morning,

When I tried disabling extensions (manually) before, it did not work. Now
with the terminal (code --disable-extensions) command source control seems
to work fine in VS Code Stable.
Strangely with terminal (code) command it seems to work as well. I'm
riddled here. Git output:
Validating found git in: usr/local/bin/git
Validating found git in: /usr/local/bin/git
Using git 2.23.0 from /usr/local/bin/git
> git rev-parse --git-dir
Open repository: /Users/esgerjellema/Workspace/frontend-aurelia
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref
--format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)
refs/heads/develop refs/remotes/develop
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
%(*objectname)
> git remote --verbose
> git config --get commit.template
> git check-ignore -v -z --stdin
> git show --textconv :src/slides/slide-edit-settings.html
> git ls-files --stage --
/Users/esgerjellema/Workspace/frontend-aurelia/src/slides/slide-edit-settings.html
> git show --textconv :src/resources/bnc-base/bnc-form.less
> git ls-files --stage --
/Users/esgerjellema/Workspace/frontend-aurelia/src/resources/bnc-base/bnc-form.less
> git cat-file -s 4397d6978a63c1e499f89747bf1276b211418019
> git cat-file -s ed8866e0e61eebfbad167fbcbbf14e620c645835
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref
--format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)
refs/heads/develop refs/remotes/develop
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
%(*objectname)
> git remote --verbose
> git config --get commit.template
> git ls-files --stage --
/Users/esgerjellema/Workspace/frontend-aurelia/src/slides/slide-edit-settings.html
> git ls-files --stage --
/Users/esgerjellema/Workspace/frontend-aurelia/src/resources/bnc-base/bnc-form.less
> git cat-file -s 4397d6978a63c1e499f89747bf1276b211418019
> git cat-file -s ed8866e0e61eebfbad167fbcbbf14e620c645835
> git show --textconv :src/slides/slide-edit-settings.html
> git show --textconv :src/resources/bnc-base/bnc-form.less


Then when quitting VS Code and starting it from the dock it doesn't work
anymore and gives this output:

Validating found git in: usr/local/bin/git
Using git 2.23.0 from usr/local/bin/git
Opening repository for
path='/Users/esgerjellema/Workspace/frontend-aurelia' failed; ex=spawn
usr/local/bin/git ENOENT {
"gitErrorCode": "NotAGitRepository"
}Error: spawn usr/local/bin/git ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
at onErrorNT (internal/child_process.js:465:16)
at processTicksAndRejections (internal/process/task_queues.js:80:21)

Quitting and starting it from terminal with code command it works again.

So that's what I can do for now, start code from the terminal.


Kind regards,

Esger Jellema


Voermanhaven 19
9742 VR  Groningen
M 06 49 68 68 93

<http://nl.linkedin.com/in/esgerjellema>*Profiel van Esger Jellema
weergeven <http://www.linkedin.com/in/esgerjellema>*


Op vr 10 dec. 2021 om 20:26 schreef Ladislau Szomoru <
***@***.***>:

**Comment by Esger** [comment]
whereis git says:

***@***.*** foo % whereis git

/usr/bin/git


Met vriendelijke groet,

Esger Jellema


Voermanhaven 19
9742 VR  Groningen
M 06 49 68 68 93

<http://nl.linkedin.com/in/esgerjellema>*Profiel van Esger Jellema
weergeven <http://www.linkedin.com/in/esgerjellema>*


Op vr 10 dec. 2021 om 11:29 schreef Ladislau Szomoru <
***@***.***>:

**Comment by TrevorKarjanis** [comment]
I was experiencing the same problem with 1.64.0-insider (Universal). Running from the command line, with and without `--disable-extensions` resolved the issue. Executing the `Git: Show Git Output` command also resolved the issue. Other related issues seem to be [138862](https://github.com/microsoft/vscode/issues/138862) and [138754](https://github.com/microsoft/vscode/issues/138754).

By disabling and enabling my extensions, I narrowed the suspect extension to [Azure Repos](https://marketplace.visualstudio.com/items?itemName=ms-vsts.team). This extension is [deprecated](https://github.com/microsoft/azure-repos-vscode/blob/master/DEPRECATED.md), and disabling or removing it resolved the issue.

**Comment by lszomoru** [comment]
@TrevorKarjanis thanks for sharing. Will be closing the issue for now. Please reopen if the issue reoccurs.
