### ISSUE TITLE
FormatOnSave distorts the HTML file.

### ISSUE THREAD

**Issue by AkashGutha** [Microsoft/vscode#13823]
- VSCode Version: 1.6.1
- OS Version: Windows 10 14393.321

Steps to Reproduce:

1.  Open a html file . make sure 'editor.formatOnSave' is set to true.
2.  make some changes and save the file.
3. the line gaps increase exponentially with each save.
![vscode](https://cloud.githubusercontent.com/assets/10159531/19415993/0e97349a-93a1-11e6-8a71-558e161b594d.gif)

**Comment by AkashGutha** [comment]
facing same problem with json files too,.

**Comment by AnWeber** [comment]
I have got the same problem. I disabled the autoformat option in the extension HookyQR.beautify. After that the formatting is valid.

**Comment by jrieken** [comment]
So, this is either the beautify extension or our built in formatter

**Comment by AkashGutha** [comment]
it's not from the extension i guess. the"Format On Save" is a new option included in vscode 1.6

**Comment by jrieken** [comment]
@AkashGutha "Format On Save" just calls whatever formatter is contributed by whatever extension. It doesn't actually implement a formatter, it's just a calling strategy

**Comment by AkashGutha** [comment]
Oh ! i didn't know that . i tested it and you were right. 
then i think this thread should be closed here and opened at that repo.

**Comment by AkashGutha** [comment]
The problem is not related to VSCode . it is caused due to an extension call Beutify by HOOKYQR.
