### ISSUE TITLE
Spourious test failures in ExtHostLanguageFeatureCommands 

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#1382]
Both
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build#favDefinitionId=37&_a=summary&buildId=19168
and
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build#favDefinitionId=37&_a=summary&buildId=19193

fail with
 6 failing
1) ExtHostLanguageFeatureCommands WorkspaceSymbols, ⇔ back and forth:
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
2) ExtHostLanguageFeatureCommands Definition, ⇔ back and forth:
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
3) ExtHostLanguageFeatureCommands Outline, back and forth:
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
4) ExtHostLanguageFeatureCommands Suggest, back and forth:
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
5) ExtHostLanguageFeatureCommands QuickFix, back and forth:
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
6) ExtHostLanguageFeatureCommands CodeLens, back and forth:
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

Looks like a timing issue, the tests pass in the next build

**Comment by bpasero** [comment]
Also seeing this.

**Comment by jrieken** [comment]
@bpasero You should let people know you comment out tests.

**Comment by aeschli** [comment]
Not sure how to verify. But I'm not aware of such test failures anymore. @joaomoreno Joao, agree?
