### ISSUE TITLE
Avoid duplicate low level `editorGroupModel` events

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#138200]
Right now we have `onDidGroupChange` and #137388 seeks to add `onDidModelChange`. However, the model is less informed than the view at the moments.

To clean up this debt we should
- Enrich the model to know about all view changes and act as the "source of truth"
- Have `onDidModelChange` replace `onDidGroupChange` so we don't have two listeners doing similar things. We can then rename `onDidModelChange` to `onDidGroupChange` as it is a better name.

**Comment by bpasero** [comment]
If you want to make an attempt via a new PR now that the other PR is merged, I am happy to review 👍

**Comment by lramos15** [comment]
Actually I'm not sure we want to do this. The first part yes we should figure out where active is being set and where it isn't. The second part we won't be able to replace all events because there's on will and on did close for example which is based on when the UI updates. The model already considers the editor closed.
