### ISSUE TITLE
Insiders: rejected promise not handled within 1 second

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138269]
Running insiders with the insiders extension looking at devtools I see:

```
Extension Host] rejected promise not handled within 1 second: undefined (at console.c.<computed> [as warn] (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-2021.10.19265/dist/extension.js:1047:115204))
```

Version: `v2021.10.19265`

**Comment by alexr00** [comment]
Discussed a bit with @bpasero, and adding a "Canceled" reason is what is done in other places like this. @mjbvz I've confirmed that with with "Canceled" reason it no longer gets logged to the console and I've opened a PR for this.
