### ISSUE TITLE
Local echo settings are marked experimental

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#138224]
Are all these settings still "experimental"? This seems like a mature feature

![image](https://user-images.githubusercontent.com/323878/144157696-030c296b-818b-4a2f-8d03-5d3e8e26d753.png)

**Comment by meganrogge** [comment]
This is a good point. I believe the `experimental` wording is used to indicate the functionality has some quirks. We will see if @Tyriar thinks it's fine to remove it.

**Comment by Tyriar** [comment]
Yep let's do it, I think we just didn't remember to remove
