### ISSUE TITLE
Settings TOC - all children get selected when expanding item

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#138253]
Testing #137668

Repro steps:
* Click on the item in the Settings TOC
* Click on the twistie to expand the item in the Settings TOC
* All children are being selected

<img width="249" alt="image" src="https://user-images.githubusercontent.com/3372902/144223071-9b335cd9-54ac-4dc2-b3fa-924e62a27b13.png">

**Comment by rzhao271** [comment]
Unable to repro on Insiders on macOS and Windows.

![Recording showing repro fail](https://user-images.githubusercontent.com/7199958/144278945-a35f2388-382e-401a-8807-be2e48877819.gif)

**Comment by lszomoru** [comment]
![recording](https://user-images.githubusercontent.com/3372902/144414510-b8b10770-06bf-4418-8ad9-90f9bace2a38.gif)

**Comment by rzhao271** [comment]
I can repro if I press the space key to expand the list

**Comment by rzhao271** [comment]
The example needs `id` fields for each category, which is what css-language-features currently has: https://github.com/microsoft/vscode/blob/main/extensions/css-language-features/package.json#L39
CC @eamodio because GitLens currently has the same issue.

@joaomoreno I'm guessing it is by design that the subcategories need `id` fields, otherwise I notice they get highlighted along with the parent such as in https://github.com/microsoft/vscode/issues/138253#issuecomment-984545422.

**Comment by joaomoreno** [comment]
@roblourens might be able to answer that.

**Comment by roblourens** [comment]
I'm not sure what the id is doing here but I can help you debug whatever you're seeing @rzhao271

**Comment by rzhao271** [comment]
TIL there's an `issue.copyGithubPermalink` command.

It looks like the `id` field is used to disambiguate elements to focus during `onDidModelSplice` calls in the `Trait` class.

The identity provider field:
https://github.com/microsoft/vscode/blob/902c672b2ece3e48c64d22424614c1c00ea09ffe/src/vs/base/browser/ui/list/listWidget.ts#L922

The way we're setting that field for the ToC relies on the `id` field:
https://github.com/microsoft/vscode/blob/3dea704a78daae380ccf29386aa2257aa55fcd75/src/vs/workbench/contrib/preferences/browser/settingsTree.ts#L2313

An example of where the ToC tree (which implements AbstractTree) uses that field:
https://github.com/microsoft/vscode/blob/cfebd1d0be3c1c56812d6843a124407d424a33d5/src/vs/base/browser/ui/tree/abstractTree.ts#L1339

An example of where `onDidModelSplice` uses the identity provider:
https://github.com/microsoft/vscode/blob/cfebd1d0be3c1c56812d6843a124407d424a33d5/src/vs/base/browser/ui/tree/abstractTree.ts#L1067

**Comment by rzhao271** [comment]
If an id field isn't given, we now use the category title to disambiguate the categories.

Verification:
1. Clone https://github.com/rzhao271/settings-editor-tocsort
2. Run the extension (I intentionally haven't updated it with `id` fields in the categories)`
3. Use the spacebar to open and close the Z extension part of the Settings editor table of contents
4. You shouldn't see the child entries highlighted. https://github.com/microsoft/vscode/issues/138253#issue-1068265483 shows what we _don't_ want.
