### ISSUE TITLE
[themes] No message when browsing for themes with no internet connection

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#138202]
Testing #138084

When browsing themes while offline, I didn't get any message that I could not connect to the marketplace and/or could not retrieve themes, with the only visible feedback being that the theme search would instantly return with an empty quickpick.

It would be nice if this information could be surfaced somehow.

**Comment by dbaeumer** [comment]
Verified:


![Image](https://user-images.githubusercontent.com/1931590/214815207-42ccc427-6943-4b41-a66e-5b742e6387e3.png)
