### ISSUE TITLE
Pre-Release only extensions show up in Stable search results

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#138231]
I created a new test-Stable build off of the same commit as todays Insiders to help test #138068: https://az764295.vo.msecnd.net/insider/4ee3ed1ff239dd9b51cd07ed8a35e29ca9d441c2/VSCode-darwin.zip

In it I see that the extension which I've only published a pre-release version of shows up in the search results, even though trying to install it gives the same issue as reported in #138215. 

IMO in this case it either shouldn't show up at all, or at least should say "Install Pre-Release" instead of "Install" (and "Install Pre-Release" should work to correctly install the pre-release)

![image](https://user-images.githubusercontent.com/8586769/144168899-dedb3d6b-5544-4c99-a376-687b71be97f2.png)

**Comment by sandy081** [comment]
This is a known limitation and we are building this feature based on properties we define and not on semver which is not yet supported by Marketplace. Hence, not showing an extension which does not have pre-release is not possible.

Once Marketplace supports Semver then it can enhance the Query API to provide pre-release filters. For eg., then we can add a filter that client does not prefer pre-releases and the query can return results accordingly.

But, I can try if I can show Install Pre-release action as default action in this case.

CC @isidorn - lets have a note of this we MP supports Semver.

**Comment by isidorn** [comment]
This will not happen in practice, no extensions will only have the Pre-Release version - this defeats the purpose.
Showing the correct action label is a good enough fix for this imho
