### ISSUE TITLE
yaml editor: text after "someKey: |" is colorized differently if a leading newline exists.

### ISSUE THREAD

**Issue by ghuser** [microsoft/vscode#138244]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: `1.62.3`
- OS Version: `Ubuntu 18.04.6 LTS`

Steps to Reproduce:

1. `code --disable-extensions`
2. create the following `.yml` file

```yml
someKey: |

  *Some description*
  which is multiline
```

3. Observe that "Some" word has another color (issue)
4. Now remove the leading newline
5. Observe that the whole string has the same color (expected behavior)

**Comment by alexr00** [comment]
Moved to the repo that we pull our yaml syntax highlighting grammar from: https://github.com/textmate/yaml.tmbundle/issues/38
