### ISSUE TITLE
Sidebar always comes back in empty workspaces

### ISSUE THREAD

**Issue by TheIndifferent** [Microsoft/vscode#13825]
- VSCode Version: 1.6.1
- OS Version: macOS Sierra 10.12

Often using VSC to do something real quick, like change arguments in URL or catch the terminal output, would be helpful to start with hidden side bar.

**Comment by garfieldbanks** [comment]
Yeah I hate this.

**Comment by isidorn** [comment]
If you hide the sidebar the next time you open vscode it would have the sidebar hidden.
Though adding an explicit option is a feature request thus assigning to @bpasero

**Comment by garfieldbanks** [comment]
@isidorn Uhh. That does not work.

**Comment by bpasero** [comment]
@garfieldbanks @TheIndifferent are you opening a folder with VS Code or opening empty/single file? Do you see the sidebar when opening a folder or with VSCode opening empty/single file?

I suspect this could be the experiments for these people to cause the sidebar to always show when opening single file / empty workspace.

**Comment by garfieldbanks** [comment]
OK I just tested opening code from the terminal like this:

`code .`

And this DOES preserve the sidebar being hidden (like @isidorn said) the after I close the window and reopen it with:

`code .`

However I never actually open vscode like this. I have it set to never reopen any folders. Maybe that will help isolate the problem.

**Comment by TheIndifferent** [comment]
My usecase is much simpler:

1. put an icon to the Dock.
2. need to edit a small piece of text real quick - click an icon, VSC starts with sidebar visible, press CMD+B to hide the sidebar, press CMD+N and paste text there.
3. after you're done - press CMD+Q to quit the VSC.
4. need to edit another piece of text - click an icon, VSC starts with sidebar visible again.

**Comment by garfieldbanks** [comment]
I can verify this in Windows 10 as well.

Place a simple shortcut to vscode on the desktop (without any command line parameters).

Open vscode using desktop shortcut.

Press Ctrl+B to close the sidebar.

Press Ctrl+Shift+W to close vscode.

Reopen vscode using desktop shortcut.

Verify that sidebar has been reset to visible.

**Comment by bpasero** [comment]
@garfieldbanks @TheIndifferent can you please upload a screenshot for when VS Code shows the sidebar when you do NOT expect it.

**Comment by garfieldbanks** [comment]
![image](https://cloud.githubusercontent.com/assets/12904270/19435957/bb10301c-942a-11e6-87cf-fe30e1bc524d.png)

**Comment by garfieldbanks** [comment]
![hellogoodbye](https://cloud.githubusercontent.com/assets/12904270/19436186/ee1ec864-942b-11e6-827d-b6a3292b8d55.png)

**Comment by garfieldbanks** [comment]
It just keeps coming back to say hello.

**Comment by bpasero** [comment]
@garfieldbanks @TheIndifferent can you try setting this in settings:

`"telemetry.experiments.showDefaultViewlet": false`

**Comment by garfieldbanks** [comment]
Yup. That fixes it.

**Comment by bpasero** [comment]
We need to disable these experiments as they cause unexpected and indeterministic behaviour. 

Unless objections, I will revert them ( @egamma @seanmcbreen @chrmarti fyi).

**Comment by bpasero** [comment]
I deleted all experiments besides the watermark experiment. Though I argue it should just be enabled by default.

**Comment by egamma** [comment]
CC @kieferrm

**Comment by kieferrm** [comment]
@bpasero disabling the experiments is not quite the right solution to the issue @TheIndifferent  and @garfieldbanks are seeing. It would make it impossible for us to improve our understanding how to better help first time users. 

The issue comes to light because we don't remember the state for the sidebar if the user does not have an open workspace. I.e. when in an older version you make the sidebar visible without opening a folder and restart code you will not get your sidebar back. 

Since we are not interested in changing the behavior for returning users, I'll attach a PR that filters based on first time usage.

**Comment by bpasero** [comment]
@kieferrm sounds good, I have opened https://github.com/Microsoft/vscode/issues/14009

As far as this issue goes, it is resolved by setting `"telemetry.experiments.showDefaultViewlet": false` for now.
