### ISSUE TITLE
Source Control / Pending Changes: Filter by Type

### ISSUE THREAD

**Issue by jgritten** [microsoft/vscode#138288]
Within the Source control tab, viewing the file list of pending changes, I would like to filter this list by type. More specifically, I would like to see the files I have modified(M) only, and not added(U). 

Reasoning: I have recently inherited a project which required a few local package updates and with that, nuget has decided to Add over 150+ files. Now my resulting work has been limited to modifying only 5 of those files, however I feel it would be easier to review those changes if I could filter down by type.

Thanks

**Comment by lszomoru** [comment]
@jgritten, have you tried the "Sort by Status" option available in the SCM viewlet?
<img width="616" alt="image" src="https://user-images.githubusercontent.com/3372902/144395604-edb58f88-a012-4031-8e3f-b95b768e3728.png">

**Comment by lszomoru** [comment]
@jgritten, please reopen the issue if the "Sort by Status" does not address the issue. Thanks!
