### ISSUE TITLE
join terminals shows empty quickpick

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#138210]
- create split terminals
- run join terminals
- none are listed

**Comment by meganrogge** [comment]
added a smoke test for a few more cases
https://github.com/microsoft/vscode/blob/7b3078d9318848abe8b42bc7bdd3df1fa22ef94f/test/smoke/src/areas/terminal/terminal-tabs.test.ts#L90-L108

**Comment by rzhao271** [comment]
I got confused because I tried joining terminals when there was only one terminal group. Is there a way to notify the user or to disable the command for that case?

**Comment by meganrogge** [comment]
yes, we should probably not show that command unless there are at least 2 un-joined terminals.
