### ISSUE TITLE
Persist selected file icon theme to user config (`settings.json`)

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#13824]
- VSCode Version: 1.6.1
- OS Version: OS X El Capitan

Steps to Reproduce:

1. Select a file icon theme
2. Open settings JSON

Expected:

The file icon theme should appear in the settings JSON.

Actual:

The file icon theme doesn't appear in the settings JSON.

**Comment by aeschli** [comment]
duplicate of #7358
