### ISSUE TITLE
"before all" hook for "reflects working tree changes"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138274]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=145032&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=6a86faf8-ed15-56db-877e-46756fb8e8fa&l=957

```
1) git smoke test
       "before all" hook for "reflects working tree changes":
     Error: Command failed: git branch -m main
error: Unable to create 'C:/Users/VssAdministrator/AppData/Local/Temp/git-1733/.git/HEAD.lock': Permission denied
error: HEAD of working tree C:/Users/VssAdministrator/AppData/Local/Temp/git-1733 is not updated
fatal: Branch renamed to main, but HEAD is not updated!

      at checkExecSyncError (child_process.js:616:11)
      at Object.execSync (child_process.js:652:15)
      at Context.<anonymous> (D:\a\1\s\extensions\git\src\test\smoke.test.ts:51:6)
      at processImmediate (internal/timers.js:461:21)

```

**Comment by joaomoreno** [comment]
Oh wow, never saw this.

**Comment by joaomoreno** [comment]
Very strange, just look at its occurrence rate in the last 30 days:

![image](https://user-images.githubusercontent.com/22350/144407333-c9b61141-6a12-489c-826c-3ecd801e7c14.png)

**Comment by joaomoreno** [comment]
Oh all those a few weeks ago are timeouts, they are not the same test failure.

**Comment by joaomoreno** [comment]
@rzhao271 Introduced [this branch renaming](https://github.com/microsoft/vscode/blob/7b6c1065c76708d146844154c8a33906f06dce0b/extensions/git/src/test/smoke.test.ts/#L51) which happens to be where this flakiness happened:

```
Command failed: git branch -m main error: Unable to create 'C:/Users/VssAdministrator/AppData/Local/Temp/git-1733/.git/HEAD.lock': Permission denied error: HEAD of working tree C:/Users/VssAdministrator/AppData/Local/Temp/git-1733 is not updated fatal: Branch renamed to main, but HEAD is not updated!
```

**Comment by joaomoreno** [comment]
🤷 I could only find this mitigation: https://github.com/microsoft/vscode/commit/1af9ac1b8f7882dc5690edd67a34b5bb47c8ca58
