### ISSUE TITLE
Support sippets in inline completions

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#138260]
The replacement string can currently only be a string. Would be cool to support snippets as well.

**Comment by hediet** [comment]
In the toy inline completion provider, line 30 indicates that line 31 should be replaced with the specified snippet.
This is the outcome:

![recording](https://user-images.githubusercontent.com/2931520/156384420-eb736c01-3531-4b42-9980-7e0871d7e134.gif)

**Comment by hediet** [comment]
@dbaeumer I tested this feature thoroughly. There are some things that don't work as expected though (such as whitespace-adjusting or resolving certain variables).
These things are not very useful for dynamic snippets anyway.

I'd be interested in your feedback for how this new feature helps your use-case!
