### ISSUE TITLE
Default product icon preview doesn't work

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#138201]
Testing #138084

Steps:
1. Have the [Fluent Icons theme](https://marketplace.visualstudio.com/items?itemName=miguelsolorio.fluent-icons) installed and enabled, and only that product icon theme
2. Use the `Preferences: Product Icon Theme` command to open the product icon theme quickpick
3. Swap between the Default and Fluent Icons themes, notice no icon change:

https://user-images.githubusercontent.com/51720070/144110211-efef60d1-cfb9-49d5-8c36-2f64d05f74b6.mp4

**Comment by IanMatthewHuff** [comment]
LGTM now
![FluentIcons](https://user-images.githubusercontent.com/812783/144495656-67d122a9-0512-4a31-85f6-a81a483c4061.gif)
.
