### ISSUE TITLE
Don't show tab modified indicator if file isn't different than what's on disk (even if changes were made)

### ISSUE THREAD

**Issue by rightaway** [Microsoft/vscode#13829]
- VSCode Version: 1.6.1
- OS Version: Linux

If I make a change to a file, the tab shows the modified indicator as expected. If I undo the change with Ctrl Z, the modified indicator goes away as expected.

But if I make a change like adding a character and then I delete the character, the tab shows the modified indicator which isn't expected. Even though a change was technically made, the file currently is no different than what's on disk, so it shouldn't appear as modified.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/919
