### ISSUE TITLE
icon of path suggest not match files.associations when using glob

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#138250]
Version info:

```
Version: 1.63.0-insider (Universal)
Commit: 0cc0904c565399781defa830facf43141db8b6f3
Date: 2021-12-01T05:13:44.911Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```

Steps to Reproduce:

1. toggle icon theme to builtin `Seti`
2. add following settings:

   ```json
   {
     "files.associations": {
       "**/src/utils/**/*.jsx": "javascript"
     }
   }
   ```

3. add `import './'` and trigger suggestion

![image](https://user-images.githubusercontent.com/41773861/144217184-6e37e905-8e45-4417-b186-3e6d361656ad.png)

You can see the file icon in explore is render right, but in suggestion list is not. If I using following setting, every thing work nice.

```json
{
  "files.associations": {
    "*.jsx": "javascript"
  }
}
```

![image](https://user-images.githubusercontent.com/41773861/144217084-074f6f05-6f21-4e23-8989-a1f18ac1b1fb.png)

**Comment by tjx666** [comment]
@jrieken

**Comment by jrieken** [comment]
That's because there is actually no path to be matched against. The completion only contains `a.jsx`, not the full path, and therefore glob matching doesn't work

**Comment by jrieken** [comment]
Open for suggestions here but I don't think we can do anything

**Comment by tjx666** [comment]
relatied issue https://github.com/ionutvmi/path-autocomplete/issues/100#event-5697553681

**Comment by jrieken** [comment]
This is the logic that computes the icon path. We use the label and description of the item, so if you use the actual filepath it should work

**Comment by tjx666** [comment]
@jrieken 
So, how I make that extension work? the label is used to be describe the suggestion item, no place to set the filepath. If I set label to filepath, it's not readable to users.

![image](https://user-images.githubusercontent.com/41773861/144470219-d0da48e7-e428-44f5-bdc2-2adb0e86a1ff.png)


![image](https://user-images.githubusercontent.com/41773861/144470138-5e3c1c28-654a-411a-b5de-a2423b4c43c1.png)

**Comment by jrieken** [comment]
did you try descriptions?

**Comment by tjx666** [comment]
> did you try descriptions?

After I set detail to real full fs path, it wroks.

![image](https://user-images.githubusercontent.com/41773861/144903196-99f9ef01-5a24-407f-88db-0c2a11ae2450.png)

**Comment by jrieken** [comment]
Ok, closing as question. Thanks for getting back to me so quickly

**Comment by tjx666** [comment]
So, module name in import statement should also be fixed by this way? @jrieken 
For now, that autocomplete is implement by vscode team?
