### ISSUE TITLE
Pre-release extensions: confusing experience on older versions of VS Code

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#138261]
Testing #138068

I had VS Code 1.62.0 installed on my Windows 11 VM.

Searching for Mock Debug showed the pre-release version 1.47.1 but without any visual indication:

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/1898161/144247236-a635182d-6e73-4703-ab21-a7941998fd9f.png">

Installing the extension resulted in version 1.46.11 being installed (without any warning): 

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/1898161/144249537-caa8b850-a420-4ab0-96b5-6237829750a2.png">

I understand that older versions of VS Code don't have the code "to do the right thing". 
But I was always under the impression that queries on the Marketplace only show "compatible" versions of an extension, but here I'm offered a Mock Debug that requires VS Code 1.63 (when I have VS Code 1.62).

**Comment by sandy081** [comment]
>But I was always under the impression that queries on the Marketplace only show "compatible" versions of an extension,

This is not true. VS Code always shows the latest version and installs the compatible version. Marketplace do not understand the semantics of vscode engine compatibility.

CC @isidorn

**Comment by isidorn** [comment]
Yeah this is an unfortunate limitation. It would be great if we were rendering the correct extension description, however I do understand how this would require additional MP calls which might overcomplicate things.
