### ISSUE TITLE
Show "Install-Pre Release" button if I have the stable version of an extension 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#138266]
Testing #138068

When I have "Mock Debug" (stable) installed, and search for Mock Debug  I see this:

<img width="576" alt="image" src="https://user-images.githubusercontent.com/1898161/144254806-f656bcbf-6850-4696-83b9-cbf27729087c.png">

If I don't have "Mock Debug" installed, and search for Mock Debug I see this:

<img width="590" alt="image" src="https://user-images.githubusercontent.com/1898161/144255207-f0c7604e-310b-4a3a-8258-f55d3d36c0b8.png">

I wonder why is there no prominent "Install-Pre Release" button in the first case?

**Comment by sandy081** [comment]
We wanted to be as less noisy as possible here. Hence, we used the bookmark/badge on the top left corner to indicate that extension has pre-release version. Showing the action might be too aggressive if users do not want to install pre-release. We show this button explicitly when you open in the extension editor and also available in the context  menu / gear dropdown.

CC @isidorn @misolori

**Comment by weinand** [comment]
Why are we agressive with new users, but not with existing users?
IMO that's backwards.

**Comment by sandy081** [comment]
Showing this when not installed fits well with the install flow, but showing this when release version is already installed makes my installed section view overloaded with these buttons which I cannot get rid off. For eg:

<img width="493" alt="image" src="https://user-images.githubusercontent.com/10746682/144372733-8575afbc-7985-4ee8-9aa0-33e41dc373bc.png">

I think the main intention for existing users is to provide a way for them to discover that there is a pre-release available for an extension.
