### ISSUE TITLE
Hover for completions in the interactive window don't follow when the window resizes

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#138299]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.0-insiders
- OS Version: macOS Monterey

Steps to Reproduce:

1. In the input box of the interactive window type something like `import sys` and `sys.` to bring up the completion hover
2. Then shrink down the size of the interactive window, the hover will not move with it
![HoverIssues](https://user-images.githubusercontent.com/812783/144327916-11d40d86-a412-42ab-90f6-7d9f23632ccb.gif)
.

**Comment by eleanorjboyd** [comment]
What was the fix here? I seem to just be no longer to adjust the interactive window height but it could also be because my interactive window is still not fully working.

**Comment by rebornix** [comment]
@eleanorjboyd the interactive window height can be adjusted by open and hide the panel.

Verifier: please test that when open/hide the panel through keybindings, the suggest widget is dismissed.

**Comment by roblourens** [comment]
This mostly works, except for this issue when I show the hover using the keyboard

![Recording 2023-01-26 at 11 43 18](https://user-images.githubusercontent.com/323878/214909798-84e1d632-7d2f-4d51-9e8b-318dc9b48e55.gif)

I'll still call it verified, this is an unusual case, @rebornix lmk if I should open an issue for this.
