### ISSUE TITLE
Source control (git) intermittently reports diverging branches

### ISSUE THREAD

**Issue by nicka101** [microsoft/vscode#138219]
Issue Type: <b>Bug</b>

I am unaware of exactly how to reproduce this issue, but VS Code specifically seems to have intermittent issues with incorrectly identifying a commit as divergent from its branch.

This manifests in the form of me pulling (either from vscode or from command line) and being told the repo and branch are up to date. I then commit the changes in my working set using vscode and attempt to push them. Vscode refuses to push the changes, claiming that my commit diverges from the branch.

Attempting to push the same commit, unmodified, from command line (or any other git client for that matter) succeeds without issue

VS Code version: Code - OSS 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-07T19:37:13.664Z)
OS version: Linux x64 5.10.79-1-MANJARO
Restricted Mode: No

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.1
vscode-docker|ms-|1.18.0
python|ms-|2021.11.1422169775
jupyter|ms-|2021.10.100
ansible|red|0.7.1
vscode-yaml|red|1.2.2
jinjahtml|sam|0.16.0

</details>

**Comment by lszomoru** [comment]
@nicka101, in case this happens in the future, can you please send us the contents of [the git output window](https://code.visualstudio.com/docs/editor/versioncontrol#_git-output-window). Thank you!
