### ISSUE TITLE
Comment and uncomment multiple lines in .env file

### ISSUE THREAD

**Issue by RaviPabari** [microsoft/vscode#138241]
- pressing ```ctrl + /``` should comment and uncomment multiple env variables

But currently I have to select using ```ctrl + shift + up/down``` to achive this and this takes so much time. 

If something like this is already there please help me how to do it. Thanks

**Comment by yume-chan** [comment]
You can try the [ENV](https://marketplace.visualstudio.com/items?itemName=IronGeek.vscode-env) extension.

Maybe vscode can have a built-in extension for `.env` files, or just add `.env` extension to Shell Script Language Basics built-in extension.

**Comment by RaviPabari** [comment]
> You can try the [ENV](https://marketplace.visualstudio.com/items?itemName=IronGeek.vscode-env) extension.
> 
> Maybe vscode can have a built-in extension for `.env` files, or just add `.env` file suffix to Shell Script Language Basics built-in extension.

thanks for mentioning that extension it came handy and also found another to switch between different env [.env switcher](https://marketplace.visualstudio.com/items?itemName=EcksDy.env-switcher&ssr=false#review-details) 

This solved my current problem.
