### ISSUE TITLE
Allow to to hide folder arrows in explorer and padding tweaks

### ISSUE THREAD

**Issue by NIPanag** [Microsoft/vscode#13828]
Hello,
As the title suggests, it would be a nice little UI improvement if we were able to disable the folder arrows in the explorer when an icon theme is in use.

As you can see in the screenshots below, some icon themes differentiate between open and closed state, thus making the arrows unneeded.
![](http://i.imgur.com/7Mlv9w7.png)
![](http://i.imgur.com/6xxCidT.png)

Furthermore, being able to reduce the left padding on the explorer items (as in for example, some sublime themes allow through a `sidebar-small`-like option) would be equally welcome.

I realize that these tweaks might appear minor but when working on smaller screens, every pixel counts.

**Comment by bpasero** [comment]
Dupe: https://github.com/Microsoft/vscode/issues/25655
