### ISSUE TITLE
Typescript and javascript failed multiple time in ideal mode

### ISSUE THREAD

**Issue by praveeenpatel** [microsoft/vscode#138235]
Issue Type: <b>Bug</b>

Typescript and javascript engine failed multiple time in ideal mode

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.11.0-38-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.37GB (8.01GB free)|
|Process Argv|--unity-launch --crash-reporter-id d806dc80-d6cc-4e89-8d96-ab24406ff80c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-node-readme|ben|3.0.2
vscode-mysql-client2|cwe|4.3.0
githistory|don|0.6.19
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
code-runner|for|0.11.6
c-cpp-runner|fra|2.0.5
html-snippets|gey|0.2.3
copilot|Git|1.7.4016
vscode-picture|Jak|1.0.0
tag-inserter|l7s|1.4.0
quickstart|lol|0.1.0
vscode-docker|ms-|1.18.0
remote-containers|ms-|0.205.2
cpptools|ms-|1.7.1
markdown-preview-enhanced|shd|0.6.1
html5-boilerplate|sid|1.1.1
ejs-snippets|Tao|0.1.0
vscode-lldb|vad|1.6.10
gitblame|wad|8.1.0
HTML5-extension-pack|wal|1.0.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932cf:30405812
vscexrecpromptc:30404946
vscop804:30404766
vscop940:30404999

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please specify what "Typescript and javascript engine failed" means and what is "ideal mode".

Code to reproduce problem and link to project would be helpful.

**Comment by praveeenpatel** [comment]
It is related to extension  `typescript`
it is crashed when vscode is running and the system is ideal for a while.
Then came back to the chair and see this error.

**Comment by IllusionMH** [comment]
> this error

What is exact error?
Do you see any stack trace or prompt to enable detailed logs?
