### ISSUE TITLE
since have updated Vs code-insiders yesterday, I could't run it and it seems to make memory almost full all the time

### ISSUE THREAD

**Issue by youfang11523868** [microsoft/vscode#138227]
- VS Code Version: Code - Insiders 1.63.0-insider (827f76521d33a61c19e92160649a0a6af8bad132, 2021-11-30T11:58:52.241Z)
-Remote: SSH: a certain cloud server
-OS Version:  Linux x64 4.15.0-117-generic

for you: please see some information about Vs code -insiders int the pictures below, is there something which needs to be deleted?
I am certainly confused about it.

Steps to Reproduce:
1. could't open it or open it  then run for a while then closed suddenly
![2021-12-01_105036](https://user-images.githubusercontent.com/71740544/144163184-7682acb9-14a1-4f62-a961-3e8bd32d2f83.jpg)
![2021-12-01_105100](https://user-images.githubusercontent.com/71740544/144163239-d81e87fc-c63a-465a-9c94-6ebd4da8cda3.jpg)
![Inked2021-12-01_103149_LI](https://user-images.githubusercontent.com/71740544/144162057-0296a233-d9aa-4796-8f50-4c0976b2f5ce.jpg)

**Comment by youfang11523868** [comment]
what's the command called "node"?

**Comment by deepak1556** [comment]
The executable is responsible for the server process, can you provide the output of `ps -ww -fp <PID-of-node>`

Does this issue happen with latest insiders ?
