### ISSUE TITLE
Terminal automation profiles: paths array ignores configuration

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#138290]
Testing #138078

> A single path to a shell executable or an array of paths that will be used as fallbacks when one fails.

Have the following configuration:

```json
  "terminal.integrated.automationProfile.osx": {
    "path": [
      "/bin/bash",
      "/opt/homebrew/bin/zsh"
      ],
    "overrideName": false,
    "icon": "zap",
    "color": "terminal.ansiRed"
  },
```

And when running tasks the default is shown

<img width="183" alt="CleanShot 2021-12-01 at 11 09 01@2x" src="https://user-images.githubusercontent.com/35271042/144298023-0f9222c9-a867-4797-aebe-0ea272787886.png">

If I change the path to a single then it appears to work:

<img width="171" alt="CleanShot 2021-12-01 at 11 09 43@2x" src="https://user-images.githubusercontent.com/35271042/144298131-a007e716-c955-40f6-aacb-baf9b1e2247a.png">

**Comment by alexr00** [comment]
Removed arrays from the schema.
