### ISSUE TITLE
Can a pre-release be manually uploaded to Marketplace?

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#138286]
Testing #138068

https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publish-an-extension describes how a manual upload of a VSIX created by `vsce package` is an alternative to uploading it through the `vsce publish` command.

As I understand #138068, the flag specified on `vsce publish` is what makes the VSIX a pre-release:

`vsce publish --pre-release`

Can I use the manual upload route to get a pre-release VSIX into Marketplace? If so, how?

Perhaps related to #138271 from @weinand

**Comment by sandy081** [comment]
Yes, you can create a pre-release package using vsce by passing `--pre-release` flag 

```
vsce package --pre-release
```

and upload the generated vsix to Marketplace. Pre-release properties are part of the extension vsix manifest which gets uploaded to Marketplace. Hence VS Code will identify that as a pre-release version.

CC @isidorn

**Comment by gjsjohnmurray** [comment]
@isidorn please add this information to https://github.com/microsoft/vscode-docs/blob/vnext/api/working-with-extensions/publishing-extension.md#pre-release-extensions

**Comment by isidorn** [comment]
Good point. I have updated the docs.
