### ISSUE TITLE
Should Configure Layout dropdown remain open until user presses Escape or changes focus?

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#138209]
Testing #138102

It would be nice to be able to check and uncheck multiple options in the Configure Layout dropdown.

Right now the dropdown disappears once you check a single item.

**Comment by sbatten** [comment]
This matches feedback from @JacksonKearl though I don't think he ever filed an issue.

**Comment by sbatten** [comment]
cc @misolori for ideas on what the control should look like to avoid introducing too many custom controls

**Comment by sbatten** [comment]
this is done
