### ISSUE TITLE
Stable extension should be the default to install

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#138220]
Testing #138068

- Search for the Github Pull Request extension
- Click the big green button
- Now you have the pre-release version

![image](https://user-images.githubusercontent.com/323878/144149290-44420f7c-6201-41c2-b345-70abf68c134b.png)

I think that we should be encouraging most people to install the stable version of the extension, and the pre-release version should be something that you have to opt into or look for.

**Comment by roblourens** [comment]
And even if this only shows up when the pre-release has the newest version, that will usually be the case.

One idea is to prefer pre-release in Insiders, but prefer the stable release in vscode Stable

**Comment by JacksonKearl** [comment]
> One idea is to prefer pre-release in Insiders, but prefer the stable release in vscode Stable

Based on https://github.com/microsoft/vscode/blob/80fdee58a72707131b7573eb9cb21aefcd1efb67/src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts#L606 I believe this is the case already.

**Comment by sandy081** [comment]
Yes, Default in insiders is to prefer pre-release where as in stable it is released version.

**Comment by roblourens** [comment]
Oh ok cool
