### ISSUE TITLE
Investigate progress bar in editors not hiding when changing editors

### ISSUE THREAD

**Issue by jhoneill** [microsoft/vscode#138331]
Does this issue occur when all extensions are disabled?: Yes/No {not tested}

- VS Code Version:  1.62.3
- OS Version:  Multiple. Present machine is  Windows  10 20H2 10.0.19042.1348

Steps to Reproduce: 
Cannot repro on demand, it appears to be triggered by folding code , sometimes I can go for hours without it happening sometimes it happens a few times in the space of a few minutes PowerShell and XML both do it so I don't think it is in a language extension. 

![image](https://user-images.githubusercontent.com/16209593/144398922-ef5e60ed-c964-4d21-8122-6cb91dbaf553.png)
The circled bit of blue which indicates "something is happening" starts moving left to right and  never stops, I have found if the edit area is split it only applies to one pane so I can split and  move all my tabs to it to get rid of the pane with the activity... 
I have what I'd class as an accessibility / vision / usability problem with things in motion on the screen - before ad-blockers I could only read some web sites by covering up part of the screen, and when this happens I can't make my eye stay in whatever I'm editing, and I _need_ to make it go away.  

Is there an option to stop these things appearing AT ALL ? I can't find one.  

Maybe others who have noticed this could help by saying what seems to trigger it, because I understand this is not the most helpful bug report I've ever written. A search didn't find prior reports of it, but that maybe my failure too,

**Comment by aeschli** [comment]
@bpasero Sorry, I'm not familiar with that indicator. When is it active?

**Comment by bpasero** [comment]
We have https://github.com/microsoft/vscode/issues/128595 as general feature request to reduce motion. 

Without knowing the clear action that is triggering this progress, it will be hard to learn more. Can you distill steps?

**Comment by ssigwart** [comment]
I've had the same issue.  I can trigger it by opening the search editor and search for `*` as a regular expression.  It says `Invalid regular expression: /*/: Nothing to repeat`.  After that, only a window reload seems to stop the progress bar.  I think I have a fix.

**Comment by roblourens** [comment]
I can't repro the issue with those steps @ssigwart, and looking at your PR, I don't get to that line of code in this scenario. The invalid regex is supposed to be handled somewhere upstream.

**Comment by ssigwart** [comment]
@roblourens, I have `search.mode` set to `newEditor`.  I'm guessing that's the difference.  With that setting, it hits the code in the PR.

**Comment by bpasero** [comment]
I can reproduce and think there are 2 issues here:
* search editor showing progress when you search for a `*` regex
* the editor area not hiding this progress when you open another editor

@jhoneill did you use search editors as @ssigwart suggests?

**Comment by jhoneill** [comment]
I definitely have the search editor open a lot, and I do use regex searches - sometimes quite complicated ones but I didn't think search was the trigger. I can't rule it out, because I'm not sufficiently sure what the trigger is.

**Comment by roblourens** [comment]
I was using the search editor @ssigwart, I still don't get to that line. We can continue discussing in the PR, but I still don't think that is a needed fix.

**Comment by bpasero** [comment]
Progress bar now hides when changing editors. The search issue has been extracted to https://github.com/microsoft/vscode/issues/139054

**Comment by JacksonKearl** [comment]
Verified progress bar hiding when changing editors.
