### ISSUE TITLE
Make VS Code Restartable on Windows

### ISSUE THREAD

**Issue by victoralvesp** [microsoft/vscode#138346]
I've searched but did not find any feature request for this so I'm submitting a new one. 
Since Windows 10, windows apps may be restarted on successful Login when the option **Accounts > Sign-in option > Restart apps** is turned **On** . This request is for VS Code on Windows to restart when this option is On. Other chromium projects like [Edge](https://www.microsoft.com/en-us/edge) have this feature.

Thanks a lot
> Side note: I absolutely LOVE VS Code! Thanks to all contributors :)

**Comment by bpasero** [comment]
I am not sure what specifically an application has to do to support this, isn't it just a matter of running `Code.exe` on startup? What do we have to provide more for Windows to support this?

**Comment by yume-chan** [comment]
> ## What’s new in Build 18965
>
> ### Control over restarting apps at sign-in
>
> As some of you already know, apps have the ability to [register for restart](https://docs.microsoft.com/en-us/windows/win32/recovery/registering-for-application-restart), which helps in a few situations, including enabling you to get back to what you were doing if you need to restart your PC. Previously this option was tied to the “Use my sign-in info to automatically finish setting up my device” option under Sign-in options in accounts settings. We’ve heard feedback that some of you would prefer more explicit control over when Windows automatically restarts apps that were open when you restart your PC, and with 20H1 we’re bringing that option to you.
>
> _https://blogs.windows.com/windows-insider/2019/08/21/announcing-windows-10-insider-preview-build-18965/_

The "Restart apps" option integrates with Windows' built-in crash recovery mechanism, it allows the application to specify the command line arguments when being restarted (so it can recover previously opened documents).

Generally it's a good idea to support that, but from my experience Code never fully crashes, sometimes a window may be unresponsive or crash, so it may not be useful for Code (so the only use is supporting restart after signing in).

**Comment by hello-smile6** [comment]
@webdev03 Upvote this please!
