### ISSUE TITLE
Make the behaviors of active indent guide scope consistent in both colored & non-colored cases, thus the non-colored case get improved :)

### ISSUE THREAD

**Issue by cateyes99** [microsoft/vscode#138373]
Previously I raised #108848 (_Active indent guide scope improvement_), and it was turned down eventually. Now since **VSCode** introduced this [**Bracket pair guides**](https://code.visualstudio.com/updates/v1_61#_bracket-pair-guides) in version **1.61** for the colored case, in which the behavior of the active indent guide scope is (almost) the same as what has been discussed/proposed in #108848. I think it might be good time to make the non-colored case behave in the same way. It'd be great, and both cases are consistent.

Current colored case:
<img src="https://user-images.githubusercontent.com/19678455/144508554-e7d15b95-5e5d-4dbd-bee6-35ef36a7f8d5.gif" alt= "ActiveIndentGuideScope_Colored" width="70%" height="70%">
Current non-colored case:
<img src="https://user-images.githubusercontent.com/19678455/144508628-f9e8894a-0c5b-4e33-a0c0-d35732b5364d.gif" alt="ActiveIndentGuideScope_NonColored" width="70%" height="70%">

I don't have permission to add new comments in #108848, so open this new one.

**Comment by hediet** [comment]
These are two distinct features.

* Indent guides: Guides based on indentation
* Bracket pair guides: Guides based on bracket pairs

you can tweak the colors to make the bracket pair guides look like the indent guides.

**Comment by cateyes99** [comment]
@hediet thank u. understand they are two different features. Maybe it'd be better to just call it `active scope`. So `active scope` here refers to the **highlighted vertical guide line**, no need to include the **horizontal line** part which *bracket pair guides* have but _indent guides_ don't.

Note in the 2 screenshots, when moving the cursor, how highlighting vertical guide lines changes. When the cursor is placed inside the `"bash": {...}` block (_from `{` to `}`_), both guides (_indent_ or _bracket pair_) highlight the `bash` block's vertical guide line. But when moving the cursor away from `{` towards the left on the line of `"bash": {`, **bracket pair guide** highlights `bash`'s **parent**, i.e., the `terminal.integrated.profiles.linux` block's vertical guide line, but **indent guide** still highlights the `bash` block's vertical guide line! So what we want here is to make **indent guide** behave the same way as **bracket pair guide** does, in terms how to highlight vertical guide lines, which is much better & useful as I explained in #108848.

**Comment by cateyes99** [comment]
> you can tweak the colors to make the bracket pair guides look like the indent guides.
BTW, how to do so?

**Comment by Kevin-Hamilton** [comment]
> > you can tweak the colors to make the bracket pair guides look like the indent guides.
> 
> BTW, how to do so?

editorBracketPairGuide.background{1,...,6} and editorBracketPairGuide.activeBackground{1,...,6}
As mentioned here: https://code.visualstudio.com/updates/v1_62 although I really had to search for it and wish it existed somewhere here: https://code.visualstudio.com/docs/editor/editingevolved#_bracket-pair-colorization
