### ISSUE TITLE
Enable text selection in the line-diff modal (see attached gif)

### ISSUE THREAD

**Issue by Avivhdr** [microsoft/vscode#138320]
Hello VSCode team, 

Sometimes I need to access a part of the code I recently changed.
I have the option to go to the source control tab, click on the file name, see the diffs and then copy the part that I want.
But there is an easier way to see changes you recently did in a file, and that is by clicking the vertical yellow line on the right of the row number: (line 36)
![image](https://user-images.githubusercontent.com/23265867/144377838-1dbe5f94-3018-4333-b215-b1b3af0c543f.png)
Clicking on this line will open a small window with changes between the old version and the new version.
For some reason, you can only select the new text but not the old text.

![select old text](https://user-images.githubusercontent.com/23265867/144378304-1e3f0e4f-b91b-4733-979b-456f997bf8ef.gif)

It would be nice to allow users to select the old text as well.

The reason that this feature is important is that you don't always just want to revert your changes, in this case, I wanted to copy the name of the type, to use it somewhere else in the file.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/8226
