### ISSUE TITLE
Also maintain selected item in quick pick when updating items

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#138355]
Testing #137740

Similarly to `keepScrollPosition`, it would be useful to have a flag to maintain the selected item. There is no ID on items but you could maintain it by index or by just comparing the properties of QuickPickItems to find the one which matches the previously selected item.

**Comment by TylerLeonhardt** [comment]
As you've pointed out, we don't have a good way to say for sure that yes that item is same as that one after setting `.items`. However, the API already lets you set `qp.activeItems` so you can just do either something like:

```ts
const previouslySelected = qp.activeItems;
qp.items = newListWithSameObjReferences;
qp.activeItems = previouslySelected;
```

or something like:

```ts
const indexesOfPreviouslySelected = qp.activeItems.map(item => qp.items.indexOf(item));
qp.items = newListWithDifferentObjReferences;
qp.activeItems = indexesOfPreviouslySelected.map(i => qp.items[i])
```

or if they use an id:

```ts
const idsOfPrevious = qp.activeItems.map(item => item.id);
qp.items = newListWithDifferentObjReferences;
qp.activeItems = idsOfPrevious.map(id => qp.items.find(item => item === id));
```

I don't think it's worth having QP logic to attempt to best effort these cases...

**Comment by TylerLeonhardt** [comment]
cc @bpasero and @chrmarti if they wanna join the discussion.

**Comment by roblourens** [comment]
Oh, I missed that the extension can set that. That is probably the right solution then.

**Comment by TylerLeonhardt** [comment]
I'll close this but feel free to reopen if you wanna have a discussion
