### ISSUE TITLE
"Add cursor below" has the same keyboard shortcut as changing the orientation of the screen in windows 10.

### ISSUE THREAD

**Issue by Lioncat6** [microsoft/vscode#138378]
Issue Type: <b>Bug</b>

"Add cursor below" has the same keyboard shortcut as changing the orientation of the screen in windows 10. To reproduce simply press "ctrl+alt+DownArrow. Expected results: A curser gets added to the line below, Actual results: your screen flips upside-down.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4150T CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.78GB free)|
|Process Argv|C:\\Users\\bwhou\\AppData\\Local\\Packages\\Microsoft.MinecraftUWP_8wekyb3d8bbwe\\LocalState\\games\\com.mojang\\resource_packs\\MinecraftJ\\subpacks\\all-3\\sounds\\music_definitions.json --crash-reporter-id 2f432922-e5e6-4c5e-a2cc-1f2083a0d31d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-bedrock-definitions|des|2.0.2
cpptools|ms-|1.7.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30405811
vscexrecpromptt1:30404947
vscop804cf:30404767
vscop341:30404997
vsrem710:30405998

```

</details>

**Comment by yume-chan** [comment]
AFAIK, only Intel graphic driver uses <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>DownArrow</kbd> to rotate the screen. You can disable it in Intel Graphics Control Panel.

**Comment by alexdima** [comment]
Yes, <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>DownArrow</kbd> is sometimes "stolen" at a system level by the Intel Graphics Driver. As @yume-chan mentions, you can disable the keybinding in the Intel Graphics Control Panel, or otherwise you can bind "Add cursor below" to another keybinding using the keybindings editor `cmd+k cmd+s`.
