### ISSUE TITLE
v1.6.1 can't recognize script code in vue file. This feature can work on 1.5 version.

### ISSUE THREAD

**Issue by Richard20160601** [Microsoft/vscode#13830]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: alechp.react-toolbox-snippets-0.12.0, EditorConfig.EditorConfig-0.3.3, glen-84.sass-lint-0.0.2, jameshrisho.redux-snippets-0.0.1, jaylinwang.weex-0.4.0, liuji-jim.vue-0.1.3, michelemelluso.code-beautifier-1.4.1, robinbentley.sass-indented-1.1.0, seanwash.vue-0.4.0, timothymclane.react-redux-es6-snippets-1.0.4, TwentyChung.jsx-0.0.1, xabikos.ReactSnippets-1.2.0

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
Please add a code example.
