### ISSUE TITLE
Search still improperly matches files inside .git

### ISSUE THREAD

**Issue by ajdavis** [microsoft/vscode#138376]
Does this issue occur when all extensions are disabled?: Yes/No
Not relevant.

- VS Code Version: 1.62.3
- OS Version: macOS 11.6

Steps to Reproduce:

1. Open VS Code with a project root that includes a .git directory
2. Activate "Search: Find in Files"
3. Search for something

Expected: matches are ignored if they're in files in .git/
Actual: matches in .git/rr-cache/ are displayed

![image](https://user-images.githubusercontent.com/84101/144513365-14915fac-a0bb-48c7-9283-265ff381523d.png)

I'm using the default exclude rules, which include `**/.git`, so I don't expect to see results in `.git/rr-cache/`, but I do.

Seems like "Search improperly matches files inside .git #62409" isn't fixed.

Note, this is a remote directory via ssh.

**Comment by gjsjohnmurray** [comment]
Is this significant?

![image](https://user-images.githubusercontent.com/6726799/144518042-c84072e6-c70b-4d97-8451-27edd5347d3e.png)

**Comment by ajdavis** [comment]
OMG, sorry.
