### ISSUE TITLE
Getting Started image only loads after switching to another window and back

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#138368]
Testing https://github.com/microsoft/vscode/issues/125400

The preview only seems to show up after navigating away to another window and back again.
![recording (7)](https://user-images.githubusercontent.com/7199958/144502270-9786e844-04ac-4022-aafe-1c58eb8ac9d9.gif)

**Comment by JacksonKearl** [comment]
Agree that it's slower than I'd like, but I do see it loading after a small wait. Could this be related to #138409?

**Comment by rzhao271** [comment]
I just tried it again, and yep I think it's a duplicate.
