### ISSUE TITLE
Files Associations are not working when opening a folder which is not trusted yet

### ISSUE THREAD

**Issue by LambdaAlpha** [microsoft/vscode#138390]
Issue Type: <b>Bug</b>

- add some file association rules like `'logcat_*' -> log`
- make a folder at somewhere untrusted.
- add some files matching the files association rules to the created folder, like `logcat_1.txt`
- open the folder in vscode
- trust this folder and enable all functionality
- the file association rules are not working

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.15.4-arch1-1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.51GB (1.40GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id cc788319-af4b-4646-95a9-0fb7e560ab2a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.9.0
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
code-runner|for|0.11.6
path-autocomplete|ion|1.17.1
batch-rename-extension|Jan|0.0.4
intellij-idea-keybindings|k--|1.5.0
vscode-language-pack-zh-hans|MS-|1.62.4
hexeditor|ms-|1.8.2
unicode-latex|oij|1.1.2
text-power-tools|qcz|1.30.0
text-marker|ryu|1.11.0
vscode-fileutils|sle|3.4.5
search|use|0.0.1
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.7.0
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2

</details>

**Comment by sbatten** [comment]
After testing, I can repro and the steps are precise in that before trust is given, the file association is working properly. Trusting the workspace triggers the bug for the current session.

**Comment by sbatten** [comment]
Can someone who owns the file association setting tell us what they are seeing from their side during the transition since other settings don't seem to have issues during transition?

**Comment by bpasero** [comment]
cc @alexdima, I think that happens here:

https://github.com/microsoft/vscode/blob/11862795ea2dc6491018addf3696ef0c0b440aee/src/vs/workbench/services/mode/common/workbenchModeService.ts#L166-L171

**Comment by alexdima** [comment]
@bpasero I think that code came in via https://github.com/microsoft/vscode/commit/4d9afc662400600d6e70841f7148b905c34f3264#diff-1f75d2d733bc7da5eb2d5915793fcdc327433d4eb46c6d146c1af29e4d1b2683R569-R579

**Comment by bpasero** [comment]
I do not see an issue:

![image](https://user-images.githubusercontent.com/900690/144901622-6bb0a66a-f8ea-435d-ab4d-7f4c00bd8136.png)

**Comment by bpasero** [comment]
Oh I see, it switches back to "Plain Text" when trust is given. Sorry, I have no clue what I have to search for that could trigger such a behaviour.

**Comment by sbatten** [comment]
from our side, in this path (untrusted to trusted) not a lot, additional extensions get activated and the configuration service gets a signal which may cause some onconfiguration changed events to fire for workspace related settings.

**Comment by alexdima** [comment]
@bpasero I could not reproduce. What are the precise steps? Here is what I tried:
* created two files `logcat_1.txt`, `logcat_2.txt`
* edited the folder settings:
```
"files.associations": {
	"logcat_*": "log"
},
```
* made the folder untrusted
* reloaded window
* opened file `logcat_1.txt`. It is recognized as Log
* made the folder trusted while file `logcat_1.txt` is open
* the file `logcat_1.txt` remains Log, opening the file `logcat_2.txt` opens it as Log

https://user-images.githubusercontent.com/5047891/145056768-5468d29e-6200-4fc0-9bf9-441732e07c7c.mp4

**Comment by bpasero** [comment]
I think when I tried the file was not the active tab and when I clicked it to make it active it showed as "Plain Text".

**Comment by LambdaAlpha** [comment]
@alexdima I think closing all vscode instances and opening the folder in vscode from file manager or from terminal would help to reproduce it.

**Comment by kanlukasz** [comment]
Related maybe --> https://github.com/microsoft/vscode/issues/138664

**Comment by bpasero** [comment]
@alexdima here are detailed steps:

* Configure as a setting
```
	"files.associations": {
	    "logcat_*": "log"
	}
```
* Open a folder with 1 file `logcat_1.txt`
* Do not trust the folder
* Close all opened editors, reload window
* Open `logcat_1.txt` and notice log mode, close editor
* Trust folder
* Open `logcat_1.txt` again and notice plain text mode

Debugging this, it looks like only the `workbenchLanguageService` is registering user configured associations here:

https://github.com/microsoft/vscode/blob/c71424a61de500cda911c0948e2e6c3140b2b3e6/src/vs/workbench/services/mode/common/workbenchLanguageService.ts#L165-L172

But transitioning into trust seems to call `clearTextMimes` here:

https://github.com/microsoft/vscode/blob/cb3bc8a60e6fec5db31620ca6ad879d2346e6161/src/vs/editor/common/services/languagesRegistry.ts#L112

Without adding back the user configured associations.

A regression from https://github.com/microsoft/vscode/commit/11862795ea2dc6491018addf3696ef0c0b440aee#diff-6a1dacad467735e2e56f8e155192689703247a0d4d3f9dcbe696344fe0c64be1R112
