### ISSUE TITLE
Loading never end

### ISSUE THREAD

**Issue by kwdaisuke** [microsoft/vscode#138381]
I am updating readme file through vscode. Now file tab shows clock logo and loading all files indefinitely.
It seems drag and drop zip file(955.5 MB on disk) caused this behavior, as way over the limit.

Tried
1. Reload
2. Open new tab

So far, no workaround found

Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36
Embedder: github.dev

**Comment by kwdaisuke** [comment]
<img width="817" alt="loading" src="https://user-images.githubusercontent.com/54173850/144536189-d1e7e62d-c7bd-415b-b579-6bfa8045faec.png">

**Comment by gjsjohnmurray** [comment]
Similar to #138331

**Comment by kwdaisuke** [comment]
recreated the repository for now
