### ISSUE TITLE
HTML fast typing (with TAB) stopped working, instead hinting useless [abc] thing

### ISSUE THREAD

**Issue by animanoir** [Microsoft/vscode#13839]
- VSCode Version: 1.6.1
- OS Version: W10

Steps to Reproduce:

1. Create HTML document
2. Type div or something like that, it should appear then the tooltip.

Everything was working quite well before the last update. I'm using the extension _HTML Snippets (0.0.17)_ , but now it doesn't puts first the tooltip to just press tap; now I need to scroll down to find it and press tab to get it close automatically.

It is pissing me off.

**Comment by animanoir** [comment]
Btw, I've been using the same extensions (HTML Snippets and others similar) and everything worked fine, until the last update.

**Comment by NiekPas** [comment]
Can confirm on my machine; word completion appears to take precedence over snippets.

![vscode-issue](https://cloud.githubusercontent.com/assets/11707054/19439762/9f8eaecc-947f-11e6-95a6-a36ababea7a8.png)

VSCode Version: 1.6.1
OS Version: Windows 10

**Comment by jrieken** [comment]
We change the default sorting on purpose. See https://github.com/Microsoft/vscode/issues/10467 and provide feedback there so we have it collected at one place

**Comment by animanoir** [comment]
And why in the f. world did you do that? How can I make VSCode useful again?
