### ISSUE TITLE
Tests for Emmet actions on html tags: update image css with multiple cursors in css file

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138314]
```
1 failing
  1) Tests for Emmet actions on html tags
       update image css with multiple cursors in css file:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode/vscode/extensions/emmet/out/test/updateImageSize.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=145119&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=c55167a9-8752-5898-67fa-9d7c918c61b3&l=1128

and

https://github.com/microsoft/vscode/runs/4387301168?check_suite_focus=true#step:17:1129

**Comment by rzhao271** [comment]
Merging with https://github.com/microsoft/vscode/issues/138499, since that one has more info.
