### ISSUE TITLE
Increase the default size of the Peek box for test results

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#138347]
The default size of the peek test output box is very short at only 5 lines of text. This came up before in #130786 but the resolution was to make it possible to open the full output in a whole new window. While that's great for large output, it's overkill for if you just want to review 10-15 lines.

There's a comment on the original issue:

> @connor4312 mentioned to me 1:1 that there is a feature to adjust height of peek based on the size of the message, but that that's only implemented for diffs, rather than the standard messages

It would be nice if this could be applied here, but if not, I think a slightly taller window (10 lines?) would go a long way.

**Comment by HerrNiklasRaab** [comment]
> It would be nice if this could be applied here, but if not, I think a slightly taller window (10 lines?) would go a long way.

I think making peek height (for tests?) a setting is necessary anyways.

**Comment by HerrNiklasRaab** [comment]
@connor4312  Why not make it a setting, or let it remember the size, after resizing?

**Comment by connor4312** [comment]
Reviewing our other peek usage in VS Code, we don't have size settings for those. But I think remembering the size makes sense, I'll add that too.

**Comment by HerrNiklasRaab** [comment]
Awesome! I know I demand a lot, but please also remember the size of the left and right panel 😊💪
