### ISSUE TITLE
there is no formatter for 'json' files installed

### ISSUE THREAD

**Issue by Xinchengzelin** [microsoft/vscode#138307]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.3
- OS Version: windows10

Steps to Reproduce:

1. json file not too large, about 4000KB, shift+alt+F couldn't work,  a dialoge appear " there is no formatter for 'json' files installed"
2. I tried the measures in [#46897](https://github.com/Microsoft/vscode/issues/46897), 
3. the measure "jarrettv commented on 17 Jul 2018" works:

- Open large file (vscode disables language features)
- Close large file.
- Open small file (vscode formatting won't respond).
- Restart vscode.
- Open small file again (vscode formatting working again).

**Comment by aeschli** [comment]
Sounds like https://github.com/microsoft/vscode/issues/105986.

**Comment by jrieken** [comment]
> a dialoge appear " there is no formatter for 'json' files installed"

A you really sure that you have a formatter installed and activated? This is what I am seeing for a very large file. 👇 

<img width="911" alt="Screen Shot 2021-12-02 at 10 51 39" src="https://user-images.githubusercontent.com/1794099/144398622-cd0cba83-78a5-42eb-bf3b-29430b6cd8b3.png">

**Comment by Xinchengzelin** [comment]
> > a dialoge appear " there is no formatter for 'json' files installed"
> 
> A you really sure that you have a formatter installed and activated? This is what I am seeing for a very large file. 👇
> 
> <img alt="Screen Shot 2021-12-02 at 10 51 39" width="911" src="https://user-images.githubusercontent.com/1794099/144398622-cd0cba83-78a5-42eb-bf3b-29430b6cd8b3.png">


It should be that, I have been used VSCode since last year, the format function( shift+alt+F) for json file is OK. And I'm sure the error was not like that in the picture, it was a dialog.

I don't know why the format function didn't work suddenly and since when it didn't work. Then I search the solution online,  and find the solution in #46897 and create this issue.
When I was finding the solution, I check the disabled extensions, no json realated extention was found.   Unfortunately, I didn't check the installed json related extentions at that time. Now I find there is  “JSON formatter” is in installed extensions, I couldn't remember I installed it manually.

**Comment by jrieken** [comment]
>  Now I find there is “JSON formatter” is in installed extensions, I couldn't remember I installed it manually. Is there a way to check when I installed the extension?

I don't think that's possible. I quite don't understand your comment. Are you saying the problem is now gone or was caused by that one extension?

**Comment by Xinchengzelin** [comment]
> 


> > Now I find there is “JSON formatter” is in installed extensions, I couldn't remember I installed it manually. Is there a way to check when I installed the extension?
> 
> I don't think that's possible. I quite don't understand your comment. Are you saying the problem is now gone or was caused by that one extension?

Yes，the problem is now gone, and it had been OK several months ago.  Unfortunately, I didn't check the installed extensions(if "JSON formatter" was OK) when the problem happened. Maybe it was caused by the extension.  I just don't know why this function didn't work suddenly.
