### ISSUE TITLE
Support Webview2

### ISSUE THREAD

**Issue by blogcraft** [microsoft/vscode#138343]
Just like MS Teams is transitioning from electron to Webview2, is it possible to do the same with VS Code?

**Comment by anobongjimwel** [comment]
Hey I think it's time to give this reconsideration

**Comment by censujiang** [comment]
They have changed Electron into Microsoft's own shape, guess why they dare not change it🤣

**Comment by danfratamico** [comment]
The new Teams 2.1, released yesterday, now uses Edge WebView2 on both Windows and macOS. I hope they will start replacing Electron on their other apps shortly...

**Comment by TomMalitz** [comment]
I would love to see discussion around this pickup some steam. If the performance gains seen in the new Teams 2.1 version are as claimed, this has huge potential for a major VSCode upgrade. I'm sure the work involved would be massive but ultimately might be worth it.

**Comment by jbaenaxd** [comment]
I hope they introduce it soon. Webview2 works nicely in the new Teams. I'm working on my Mac Mini with only 8GB and VS Code consumes too much RAM. This improvement would be make my workflow much better, I can barely open the browser if VS Code is open.

**Comment by codeofdusk** [comment]
Any updates on this issue?
