### ISSUE TITLE
editor.actions.findWithArgs should use "query" and "replace" args

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#138366]
Does this issue occur when all extensions are disabled?: Yes

`editor.actions.findWithArgs` uses these args: `searchString` and `replaceString`

`workbench.action.findInFiles` uses these args: `query` and `replace`

`search.action.openEditor` uses `query` (replace is not relevant for this command)

It seems odd to me that the new `editor.actions.findWithArgs` does not remain consistent with the similar functionality of the other two pre-existing find/search commands.

----------------
Version: 1.63.0-insider (user setup)
Commit: 68a1e2f872f8869b004eec284917782474730e0b
Date: 2021-12-02T05:15:40.605Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by ArturoDent** [comment]
Related: https://github.com/microsoft/vscode/issues/138365

**Comment by roblourens** [comment]
@rebornix did you assign me because I should change the search action?

**Comment by amunger** [comment]
the inconsistency is strange, but we can't change it at this point without breaking a lot of configurations that users have set
