### ISSUE TITLE
Layout control and window controls sizing

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#138350]
Testing #138100

I think this is a known issue but am documenting that the window controls have different dimensions than the windows layout action:

![image](https://user-images.githubusercontent.com/35271042/144465490-5a08e07b-d796-4f10-ba0e-70a8cc8bc3ce.png)

![image](https://user-images.githubusercontent.com/35271042/144465526-92532c65-6c04-488e-9d8b-b819765de516.png)

Version: 1.63.0-insider (user setup)
Commit: 68a1e2f872f8869b004eec284917782474730e0b
Date: 2021-12-02T05:15:40.605Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22489

**Comment by sbatten** [comment]
Fixed by making alotted space for the button the same width as the window controls, however the hover feedback is still our standard size and shape. I don't think we want this button to look like its a native window control.

**Comment by misolori** [comment]
The extra spacing definitely helps make the icon feel separate from the windows controls 👍
