### ISSUE TITLE
Jump to def on references of a given symbol whose def we are in doesn't jump you to def

### ISSUE THREAD

**Issue by uforic** [Microsoft/vscode#13837]
- VSCode Version: Version 1.6.1 (1.6.1)
- OS Version: OSX 10.11.6 (15G31)

Steps to Reproduce:

1. Create a file called "foo.js" with this code inside it:
```
function foo() {
  foo();
}
```
2. Right click on `foo()`, and select "Go To Definition"
3. The editor's cursor is not moved to the line "function foo()," but instead remains on the line with `foo()` . If the foo() call were in another function called bar, it would be.
4. Some digging into the internals reveals that this is because the definition range for foo contains the line we are currently on, and in this case the cursor is left as is and not moved to `function foo()`

5. Why is this a bug, and not desired behavior? Imagine foo had 1000 lines, and we were looking at a call to foo on line 999. The expected behavior here seems like it would be to jump to the first line of the foo definition, not to have a no-op (current behavior).

gif: https://cl.ly/0c3s2d0d3K0b

**Comment by waderyan** [comment]
@uforic thank you for opening this issue. I hear you and see the merit in what you propose. This behavior is defined in the JavaScript language service. I am going to migrate the issue to the JavaScript language service repo to get their feedback. We should consider your approach.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11823
