### ISSUE TITLE
Auto-update often breaks my installation

### ISSUE THREAD

**Issue by fandecheng** [microsoft/vscode#138392]
Issue Type: <b>Bug</b>

Before today, I have always kept Visual Studio Code automatically updated. However, during recent three years of use, the auto-update has broken my VSCode installation at least three times, forcing me to download the newest version and to install by myself.

Behavior 1: broken when relaunching after auto-update. In that case, VSCode prompts me to update it. I let it update. Then it closes all VSCode windows. After updating, it tries to re-open the windows, but important program files (e.g. some JS files of VSCode) are not found, causing it failing to launch.

Behavior 2: auto-update without my permission, breaking running instances. In this case, the auto-update runs silently, without asking me for confirmation. It breaks running instances of VSCode, making them inoperable, e.g. unable to use "search in files" feature, due to missing important VSCode program files.

I hope this auto-update mechanism can be made more stable, and always ask me for confirmation. Otherwise I'd rather choose to opt out of auto-update.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (14.83GB free)|
|Process Argv|--crash-reporter-id bd3cf343-bd3a-446e-a16b-cfa04b943e64|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vshan820:30294714
vscod805:30301674
vsccppwt:30393681
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vscop804cf:30404767
vscop453:30404998

```

</details>

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
