### ISSUE TITLE
suggestions inside console.log for javascript not working

### ISSUE THREAD

**Issue by apicgg** [microsoft/vscode#138398]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. The auto suggestion is not working (like for variables) inside the console.log(var_name).
2. This issue seems to be on the first attempt of writting console.log(). After moving the cursor, the auto suggestion is working again. 

Check the below gif for better understanding. 

![console_log](https://user-images.githubusercontent.com/78271602/144590848-37495855-96d7-42c0-8ace-ec4ca90cd98a.gif)

**Comment by ArturoDent** [comment]
I can't reproduce this in Stable or Insiders in a `js` file on W11.  Did you try it with all extensions disabled?

**Comment by apicgg** [comment]
> I can't reproduce this in Stable or Insiders in a `js` file on W11. Did you try it with all extensions disabled?

Yes, tried with all extentions disabled. But this is still there, also tried in Linux as well. It's same there as well.

**Comment by mjbvz** [comment]
The suggestions are likely working, they are just not shown automatically because the snippet surpasses them. Set `"editor.suggest.snippetsPreventQuickSuggestions": false` to disable this behavior

/cc @jrieken I see this issue reported once or twice a month. Could we revisit this setting's default value or provide some kind of UI hint when quick suggestions are suppressed?

**Comment by apicgg** [comment]
> The suggestions are likely working, they are just not shown automatically because the snippet surpasses them. Set `"editor.suggest.snippetsPreventQuickSuggestions": false` to disable this behavior
> 
> /cc @jrieken I see this issue reported once or twice a month. Could we revisit this setting's default value or provide some kind of UI hint when quick suggestions are suppressed?

Thanks lot for the help.
