### ISSUE TITLE
Outdent-line command (cmd + [) is not responding

### ISSUE THREAD

**Issue by yu-smc** [microsoft/vscode#138384]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3 / 1.63.0-insider
- OS Version: mac OS Monterey 12.0.1
- (PC: iMac 2021 (M1))
- (Keyboard: Apple US keyboard)
Steps to Reproduce:
 
I have found same issues (already closed) but they do not seem to be solved, and the latest version of VS code, VS code insiders with the latest mac OS still have the problem. This issue may be related to M1 Mac / US keyboard. 

1. Just installed the latest vs c()ode
2. the indent command works fine but the outdent command (cmd + [) is not responding
3. I have tried the shortcut-panel, and found that I couldn't set only cmd + [ to any shortcut command
4. It is clear that the keyboard itself does not have any problem.
5. Rebooting vs code and PC itself did not solved the problem.
6. All extensions are disabled and shortcut settings are all default

Thank you for your research.

**Comment by gjsjohnmurray** [comment]
Also #114075 and #115651

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `cmd+[`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by yu-smc** [comment]
@alexdima 

Thank you for help! I tried the above and the results are following:

```
[2021-12-06 11:59:52.536] [renderer4] [info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: MetaLeft, keyCode: 91, key: Meta
[2021-12-06 11:59:52.536] [renderer4] [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: MetaLeft, keyCode: 57 ('Meta')
[2021-12-06 11:59:52.536] [renderer4] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2021-12-06 11:59:52.938] [renderer4] [info] [KeybindingService]: + Storing single modifier for possible chord meta.
[2021-12-06 11:59:53.244] [renderer4] [info] [KeybindingService]: + Clearing single modifier due to 300ms elapsed.
```

Maybe the unexpected keycode 57('Meta') is detected?

**Comment by alexdima** [comment]
@yu-smc It looks like VS Code is not receiving the keybinding `cmd + [` from the OS on your machine. Here is how it looks like for me:
```
/ Received  keydown event - modifiers: [meta], code: MetaLeft, keyCode: 91, key: Meta
| Converted keydown event - modifiers: [meta], code: MetaLeft, keyCode: 57 ('Meta')
\ Keyboard event cannot be dispatched in keydown phase.
/ Received  keydown event - modifiers: [meta], code: BracketLeft, keyCode: 219, key: [
| Converted keydown event - modifiers: [meta], code: BracketLeft, keyCode: 87 ('[')
| Resolving meta+[BracketLeft]
\ From 1 keybinding entries, no when clauses matched the context.
+ Storing single modifier for possible chord meta.
+ Clearing single modifier due to 300ms elapsed.
```

There is nothing that can be done on our side if the OS does not dispatch the keybinding to VS Code. I hear about problems similar to this one all the time. All the time this is caused either by an OS configuration where an OS shortcut is bound to this keybinding or by some other application that "steals" the keybinding from all other applications on the machine.
