### ISSUE TITLE
How to change keywords's fontsize?

### ISSUE THREAD

**Issue by lichangwei123** [microsoft/vscode#138382]
How to change keywords's fontsize?

For Example

![image](https://user-images.githubusercontent.com/46671582/144537615-f7995150-ee90-454a-858a-41c3e98c2d55.png)
![image](https://user-images.githubusercontent.com/46671582/144537674-28e014ee-75b9-4d78-858b-c56632fc0de8.png)

How can I use extensions API to realize？

**Comment by rebornix** [comment]
We currently don't support changing font size of specific tokens.
