### ISSUE TITLE
terminalShellType for workbench.action.terminal.sendSequence & Escape Sequences

### ISSUE THREAD

**Issue by Zernoxi** [microsoft/vscode#138388]
Does this issue occur when all extensions are disabled?: Yes

- Issue Type: Bug
- VS Code Version: Code 1.62.3 ([ccbaa2d](https://github.com/microsoft/vscode/commit/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247), 2021-11-17T08:11:14.551Z)
- OS Version: Windows_NT x64 10.0.19042
- Restricted Mode: No

`terminalShellType` does not track current `terminalFocus`.
Escape sequences are also not fully implemented. Is that intentional?

<details>
<summary>Steps to Reproduce terminalShellType:</summary>
<br>
In default keyboard shortcuts, `ctrl+backspace` is mapped to two different actions.

```json
{ "key": "ctrl+backspace",        "command": "workbench.action.terminal.sendSequence",
                                     "when": "terminalFocus",
                                     "args": {"text":"\u0017"} },
{ "key": "ctrl+backspace",        "command": "workbench.action.terminal.sendSequence",
                                     "when": "terminalFocus && terminalShellType == 'cmd'",
                                     "args": {"text":"\b"} },
```
But since the one with `"args": {"text":"\u0017"}` is above `"args": {"text":"\b"}`, the latter action is never checked.

Also if I manually create a user keyboard shortcut, it will still default to `"args": {"text":"\u0017"}`.
</details>

<details>
<summary>Steps to Reproduce escape sequence:</summary>
<br>
In default keyboard shortcuts, `ctrl+backspace` is mapped to two different actions.

```json
{ "key": "ctrl+backspace",        "command": "workbench.action.terminal.sendSequence",
                                     "when": "terminalFocus && terminalShellType == 'cmd'",
                                     "args": {"text":"\001b[1;D\001b[K"} },
```
The argument `\001b[K` does not work and will only move to the start of the current word. It does not delete the word.
</details>

**Comment by roblourens** [comment]
I can't verify this, my command with `"when": "terminalShellType == 'zsh'"` in my zsh terminal is never run

**Comment by meganrogge** [comment]
do you have shell integration enabled @roblourens ? there are issues with that and zsh at the moment

**Comment by meganrogge** [comment]
something has regressed since this fix happened - `TerminalProcess onDidChangeProperty` is not firing with type `ProcessPropertyType.ShellType` anymore.

**Comment by meganrogge** [comment]
oh wait, actually just realized this is related to windows. should be verifiable there.

**Comment by meganrogge** [comment]
to verify, on windows, set a keybinding using `terminalShellType` for a when clause as is described by the OP. verify that it works

**Comment by Tyriar** [comment]
FYI `terminalShellType` doesn't get filled in on anything but Windows currently, this should have had the windows label earlier sorry.

**Comment by rzhao271** [comment]
Verified by creating a new custom keyboard shortcut and testing with pwsh and cmd.

```json
{
	"key": "ctrl+backspace",
	"command": "workbench.action.terminal.sendSequence",
	"when": "terminalFocus && terminalShellType == 'cmd'",
	"args": {
		"text": "test here"
	}
}
```
