### ISSUE TITLE
Any plans to integrate inline suggestions into regular API?

### ISSUE THREAD

**Issue by junghon3709** [microsoft/vscode#138383]
Are there any plans to integrate the inline suggestions proposed API into the current VScode APi? The inline suggestions API was proposed in [v1.5.8](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_58.md#inline-suggestions) but reading recent issues on github, there doesn't seem to be any move to make it into the regular API.

**Comment by hediet** [comment]
This is planned, however we don't think it is ready to go yet.
