### ISSUE TITLE
Built-in terminal runs with wrong LANG variable (leads to missing power line symbols in the prompt)

### ISSUE THREAD

**Issue by geggo98** [Microsoft/vscode#13834]
- VSCode Version: 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e)
- OS Version: Mac OS X El Capitan 10.11.6

Steps to Reproduce:
1. Start up the built in terminal
2. Check the variable LANG: echo $LANG. Value shown (wrong): "de.UTF-8". Correct would be: "de_DE.UTF-8"

This wrong environment variable leads to power line symbols in the fish status line ([example](https://github.com/oh-my-fish/theme-bobthefish)) shown as "?".

With the following configuration, the terminal works fine

``` javascript
    "terminal.integrated.shell.osx": "/usr/bin/env",
    "terminal.integrated.shellArgs.osx": [
        "LANG=de_DE.UTF-8",
        "fish",
        "-li"
    ],
```
# Examples
## Example: Defect power line prompt

<img width="976" alt="capturfiles-201610290_211060" src="https://cloud.githubusercontent.com/assets/54929/19420315/3655c486-93e9-11e6-9795-6c54554d8a2c.png">
## Example: Correct power line prompt (with configuration as shown above)

<img width="977" alt="capturfiles-201610290_211067" src="https://cloud.githubusercontent.com/assets/54929/19420324/6c121f70-93e9-11e6-9741-8f07bfd6dada.png">

**Comment by Tyriar** [comment]
@geggo98 does setting `terminal.integrated.setLocaleVariables` to false fix the issue?

**Comment by geggo98** [comment]
@Tyriar Toggling "terminal.integrated.setLocaleVariables" doesn't fix the behavior. Only setting the environment explicitly (e.g. with "env") fixes the problem.

**Comment by simonnagl** [comment]
VSCode Version: 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281)
macOS: 10.12.3 (16D32)

Without changing settings:
```
> echo $LANG
de.UTF-8
```
terminal.integrated.setLocaleVariables:
```
> echo $LANG

```
@Tyriar Thank you for the workaround! You helped me out!

**Comment by Tyriar** [comment]
The reason it's failing is because `platform.locale` is in an unexpected format:

- Australian English: `en-gb`
- German: `de`
- Korean: `ko`

**Comment by Tyriar** [comment]
It's actually sourced from `$VSCODE_NLS_CONFIG`, not node as was expected:

```
❯ echo $VSCODE_NLS_CONFIG
{"locale":"en-gb","availableLanguages":{}}
```

```
❯ echo $VSCODE_NLS_CONFIG
{"locale":"ko","availableLanguages":{}}
```

**Comment by Tyriar** [comment]
`defaults read -g AppleLocale` gets the correct format, maybe it should be a Mac-specific setting? @dbaeumer do you think we should amend `$VSCODE_NLS_CONFIG` to be the correct format for the `$LANG` attribute or pull it directly from the OS?

Pulling it from the OS could lead to inconsistencies with terminal and vscode locale, but it would also enable greater language support because we only support 7 or 8 languages in VS Code?

**Comment by dbaeumer** [comment]
The value of VSCODE_NLS_CONFIG is compute using electron API here https://github.com/Microsoft/vscode/blob/master/src/main.js#L47. The electron API used is app.getLocale(). Looks like that one is not returning the value you expect.  I have no problem adding an additional value however I would first like to understand if appgetLocale should be fixed.

**Comment by simonnagl** [comment]
> Pulling it from the OS could lead to inconsistencies with terminal and vscode locale, but it would also enable greater language support because we only support 7 or 8 languages in VS Code?

It also would set LANG to a value expected by common command line applications. I think this is the biggest pro.

**Comment by Tyriar** [comment]
@simonnagl that's the end goal, just depends on how we get there.

@dbaeumer Thanks for the link, here's some more info on the API https://github.com/electron/electron/blob/686a26d948d35bee2474fddf287ad6ebf8aa59b7/docs/api/locales.md#L3

> Electron uses Chromium's l10n_util library to fetch the locale.

Given this I think I'll just create a default/fallback locale region in case only the language comes back from `getLocale`. So if `en` is returned it will append `-US`, for `de` append `-DE`, etc.

**Comment by Tyriar** [comment]
Verification steps:

1. Set Mac system language to German
2. Restart machine
3. Launch VS Code
4. Open terminal
5. Run `echo $LANG`
6. The output should be `de_DE.UTF-8`

**Comment by aeschli** [comment]
Verified as instructed.
