### ISSUE TITLE
Opening a file from WSL appears empty but it is not. Then prompts to save empty file when closing.

### ISSUE THREAD

**Issue by b-hayes** [microsoft/vscode#138387]
Issue Type: <b>Bug</b>

I type:
`code ~/.bashrc`
VScode opens and shows the file is empty.

in wsl I type:
`cat ~/.bashrc`
I can see the file is clearly full of code.

VSCode pompts to save the empty file when I attempt to close it.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (7.81GB free)|
|Process Argv|--crash-reporter-id 338533ef-2682-4010-981c-5e8b23071f25|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
intellij-idea-keybindings|k--|1.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
vscop804:30404766
vs360:30404995
vsrem710cf:30405999

```

</details>

**Comment by aeschli** [comment]
Can you add a screenshot?
In VS Code is the full path that is shown in the editor tab correct?
In the integrated terminal, can you access the file? Is it maybe a permission problem?

**Comment by b-hayes** [comment]
The problem is fixed after installing the remote interpreter plugin.

Before that it was happening every single time I tried to open anything from ~ from in wsl terminal.

So I guess without the remote interpreter plugin, it must be assuming ~ to be the windows home path instead of the Linux one?

**Comment by aeschli** [comment]
Ok, good to hear. If you see it again, you can also run `code ~/.bashrc` to get more information how the path is resolved.
