### ISSUE TITLE
Chrome Debug Extension killing browser

### ISSUE THREAD

**Issue by vancourse** [Microsoft/vscode#13838]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 15.0.0
- Extensions: msjsdiag.debugger-for-chrome-1.2.1

Steps to Reproduce:

1. Launch Chrome against localhost, with sourcemaps
2. After Chrome browser launches, try opening the developer tools.

**Comment by roblourens** [comment]
This is expected - when the debug adapter connection is kicked out by Chrome, its process is killed, and Chrome is killed too. If you have to switch back and forth I suggest using an 'attach' config.

**Comment by vancourse** [comment]
Thank you for the quick turnaround.
