### ISSUE TITLE
Apply format.space setting to more languages

### ISSUE THREAD

**Issue by Ludonope** [Microsoft/vscode#13836]
I don't thinks it's a bug, but it would be really awesome if we could chose, or extend on which language this setting (format.space) apply.

I was trying to create a custom ident style for C++, but it only seems to apply on:
- php
- javascript
- java
- css

I have to say I'm really sad it doesn't work for C++, because that was exactly what I wanted, and it already work for some others language.

Currently, I can change the editor language to one of those listed, but this is really frustrating, especially for such a "small feature".

Thank you.

**Comment by jrieken** [comment]
Please file this issue against the formatter extensions you are using.
