### ISSUE TITLE
Git: Add remote feature not found in my VS Code command pallete

### ISSUE THREAD

**Issue by maxkumar93** [microsoft/vscode#138344]
Issue Type: <b>Feature Request</b>

Git: Add remote feature not found in my VS Code command pallete

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

**Comment by gjsjohnmurray** [comment]
Please update your VS Code. The current version is 1.62.3
