### ISSUE TITLE
After installing pre-release, context menu still says switch to pre-release 

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#138356]
Testing #138086

![image](https://user-images.githubusercontent.com/3840081/144482735-311b24d0-24b4-495f-9b57-6739d603788f.png)

**Comment by sandy081** [comment]
@karthiknadig I cant repro it

Can you please give me steps?

**Comment by karthiknadig** [comment]
Sorry, after updating to the latest insiders. I am not able to repro this.
