### ISSUE TITLE
High CPU from window showing progress bar for a long time

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode#138396]
- VSCode Version:
- Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:00:36.721Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-90-generic
- Local OS Version: Ubuntu 20/04
- Remote OS Version: CentOS 7.6
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Say you just restarted your computer so the previous docker containers you develop in haven' t been started.
2. Open VSCode, which opens more than 10 windows that opens projects in that container that haven' t been started yet. 
3. Click start container in one of the windows. Since usually you don' t work at all of the projects, just several of them are relevant for one work session.
4. You leave several background windows waiting for that container start, displaying that animation that scrolls horizontally in that window.
5. You see high CPU usage of your VSCode GPU process.
6. If you open all those waiting windows one by one and click "Start Container". After a while your CPU usage drops and temperature drops from 80 C to 40 C.

**Comment by bpasero** [comment]
@chrmarti is there a reason the operation is taking long enough? What specifically is blocking the workbench from opening, is there user action required?

**Comment by chrmarti** [comment]
@bpasero The resolver asks the user for confirmation to start a manually  (or otherwise) stopped container, so there is a modal dialog on which the resolver is waiting.

**Comment by bpasero** [comment]
Maybe when a dialog opens we could stop any progress from showing until the dialog closes again. I just verified that we continue to show progress even when dialogs are opened and they consume CPU.

**Comment by misolori** [comment]
Someone did update our regular spin animation that throttles the animation (steps), do you mind trying this out to see if it persists?

https://github.com/microsoft/vscode/blob/fb0128c7ec4e35055ebb387dcc3bb2d373394437/src/vs/base/browser/ui/codicons/codicon/codicon-animations.css#L12-L15

**Comment by bpasero** [comment]
@misolori we actually got a similar issue for the progress bar in notifications last year that made me push this change, but only for notifications (that have a chance to show more often):

https://github.com/microsoft/vscode/blob/3c3ed7fb583f27453d92d4a82d1118e7878fc05b/src/vs/workbench/browser/parts/notifications/media/notificationsList.css#L138-L148

As you can see the throttling depends on the screen resolution because I felt that using `steps` makes the progress bit stutter. Maybe for Codicons this is less noticable because the animation area is small, but for the progress bit it might be more obvious.

Ideally we had a butter smooth animation that does not spin CPU high... maybe we do a tactical fix and use `steps` only after like 30s consistently?

**Comment by bpasero** [comment]
I pushed a change to automatically reduce the animation to `steps(100)` after 10s of running (via https://github.com/microsoft/vscode/commit/204d4b4a47079e56042ec2dfc9c522a7aebbf087). Anything below that looks quite bad on my screen.

@misolori if you want to see long running progress in action (given bug https://github.com/microsoft/vscode/issues/139054) you can do:
* open search viewlet
* search for `*`
* click "open in search editor"
* click RegEx search

After 10s you should notice how the progress bit becomes less fluent.
![recording](https://user-images.githubusercontent.com/900690/145957927-36dae280-9088-4a8a-90b0-47d2fc355d4c.gif)

**Comment by bpasero** [comment]
I have pushed 2 changes now:
* flip to `steps(100)` after `10s` of animation
* hide the animation when a modal dialog is visible

Specifically the latter thing should help for the case of a modal dialog asking for input while something is loading. 

**Verification:**
* after 10s GPU usage drops (this is probably hard to measure and might depend on the setup, but would be good to measure anyway)
* while a progress animation is running, open a dialog and verify the animation stops for the duration of the dialog being visible but recovers

**Comment by misolori** [comment]
Really digging the progressive degradation here in the name of using less resource 👍

**Comment by bpasero** [comment]
Yeah unfortunately even with `steps(100)` I cannot get the GPU usage flat. Tried a couple of things also as suggested in our standup:
* `contain: strict`
* no `scaleX` during the animation (the progress bit shrinks and grows while moving)
