### ISSUE TITLE
IntelliSense for packages in package.json show the suggestions several times

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode#13835]
- VSCode Version: 1.6.1 + 1.7.0-insiders
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Write `"{__}"` when `{__}` cursor position.
2. Start typing `mi` then press <kbd>Ctrl+Space</kbd>.
3. Continue to typing `romatch`.
4. `micromatch` package show several times.

![2016-10-17_01-07-35](https://cloud.githubusercontent.com/assets/7034281/19421328/daf5e800-9406-11e6-83e3-e4e73492cbaf.gif)

This is not reproduce if start write without quotes.

**Comment by aeschli** [comment]
I can reproduce with 'micromatch'.
I added a 'console.log(items.filter(r => r.label === 'micromatch').length);' to https://github.com/Microsoft/vscode/blob/master/extensions/javascript/src/features/jsonContributions.ts#L137 to verify that the provider doesn't return duplicate proposals.
So it must be the suggestion widget that creates these. Likely this has to do with the fact that the provider always returns incomplete proposals

**Comment by jrieken** [comment]
Interesting - we should remove all items that came from an incomplete result set...

**Comment by roblourens** [comment]
![oct-27-2016 18-18-49](https://cloud.githubusercontent.com/assets/323878/19790973/e8d7b584-9c71-11e6-9025-5f2fedb43af7.gif)

@jrieken I don't see the duplicates in Insiders, but I see this new problem. If I type 'mic', show and hide the intellisense window, then type the rest quickly, the intellisense window opens up again but doesn't update, so once i've typed 'micromatch', it still shows matches for 'mic'. If I do it differently at all, it looks correct.

**Comment by jrieken** [comment]
hm... I'll reopen in investigate in November

**Comment by jrieken** [comment]
I am actually not able to repo with all kinds of typing speeds or pasting, then typing etc. @roblourens If you continue to see this, please file a separate issue with reproducible steps - pls not just an animation.

**Comment by roblourens** [comment]
Original bug is verified, I'll open a new one.
