### ISSUE TITLE
closing Visual Studio Code, but the server won't shut down.

### ISSUE THREAD

**Issue by imRonakGiri** [microsoft/vscode#138310]
Issue Type: <b>Bug</b>

When we run an express server using nodemon in visual studio code,
Then turn off the Visual Studio code, the server is still running, and when we open the Visual Studio code again we run the server and change the code and terminate the server, the server will shut down, so this is the problem.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.14.0-kali4-amd64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.65GB (2.53GB free)|
|Process Argv|. --crash-reporter-id e0cb8485-6411-4604-aa5e-16d93ab7a2e8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|lightdm-xsession|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.0
doxdocgen|csc|1.3.2
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
gitlens|eam|11.7.0
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
file-icons|fil|1.0.29
go|gol|0.29.0
better-cpp-syntax|jef|1.15.10
vscode-language-babel|mgm|0.0.35
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
vscexrecpromptt2:30404948
vscop804cf:30404767
vs360cf:30404996
vsrem710cf:30405999

```

</details>

**Comment by weinand** [comment]
@imRonakGiri how are you starting the express server?

**Comment by imRonakGiri** [comment]
npm  start

**Comment by imRonakGiri** [comment]
Screenshots of a running server...
https://photos.app.goo.gl/nUbKskMW96s2P3G36

**Comment by imRonakGiri** [comment]
Sorry
@weinand 

Now I think this is not a problem of Visual Studio Code.

The problem comes when I run nodemon...

**Comment by weinand** [comment]
@imRonakGiri I cannot reproduce your problem.

If I launch the following simple server.js from VS Code's builtin terminal via `nodemon server.js` and then shutdown VS Code, then nodemon and the server are terminated.
```ts
setInterval(() => {
	console.log("hello")
}, 1000);
```

**Comment by imRonakGiri** [comment]
i also saw
But this problem is still running on nodemon as you mentioned.

**Comment by imRonakGiri** [comment]
as you mentioned, code is note Working on any [ PORT ].

**So there is no problem**

**Comment by weinand** [comment]
@imRonakGiri great, thanks!
