### ISSUE TITLE
Notebook revert changes action

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#138360]
It would be great if I could undo all changes to a notebook cell just like how you can do that for segments of code in the editor. If this is already possible, I haven't been able to figure out how / it's not discoverable. 

![recording - 2021-12-02T111748 917](https://user-images.githubusercontent.com/29464607/144488297-cc47a706-37fa-4228-a6a1-e01bd414bc07.gif)

**Comment by rebornix** [comment]
We don't have SCM/changes support yet in the normal notebook editor. Will revisit when we start exploration for it.
