### ISSUE TITLE
Support isolated "environment"

### ISSUE THREAD

**Issue by refcell** [microsoft/vscode#138306]
I have 56 plugins installed to cope with multilingual development, and managing a large number of plugins has always given me a headache.

I've always wanted vscode to come up with a feature to switch "environment", so that each environment corresponds to a set of settings and plugins, and different settings, plugins, accounts, preferences can be switched by switching between environments instead of workspaces.

Just like logging into different accounts in an operating system, different accounts are isolated from each other.

When I enter a new environment, it's like entering a brand new vscode where I can set up settings, plugins, accounts, preferences, and these settings, plugins, accounts, preferences are brand new and not shared with other environments.

I can switch to an environment and open a project without adding the project to a special workspace.

vscode provides a "default environment" by default, just as it does now.

I think this solution makes it easier to cope with multilingual development and to manage a large number of plugins.

I hope the official can consider this suggestion.

**Comment by yume-chan** [comment]
Looks like #116740

**Comment by refcell** [comment]
> Looks like #116740

Different, what I want is complete isolation of settings, plugins, accounts, and preferences, so that breaking one environment does not affect the others, equivalent to installing multiple vscode on one machine.

**Comment by gjsjohnmurray** [comment]
https://code.visualstudio.com/docs/editor/command-line#_advanced-cli-options

Try using extensions-dir and user-data-dir
