### ISSUE TITLE
terminal blank

### ISSUE THREAD

**Issue by monkeycc** [microsoft/vscode#138456]
1.  win10
2. VSCodeUserSetup-x64-1.62.3.exe

<img width="653" alt="微信截图_20211205115840" src="https://user-images.githubusercontent.com/6490927/144733236-b64f23d3-eafc-461a-a02c-f01b57fc90cf.png">

terminal blank

**Comment by meganrogge** [comment]
what version of vscode are you using?

try setting `terminal.integrated.useWslProfiles` to false

**Comment by Siva-Leo** [comment]
@meganrogge its working.....Thank You
