### ISSUE TITLE
Script Producing Different Results

### ISSUE THREAD

**Issue by COD-Team** [microsoft/vscode#138474]
Issue Type: <b>Bug</b>

Different Results between ISE and VSCode

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-build|mar|2.1.35
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.12.0
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
cpptools|ms-|1.7.1
powershell|ms-|2021.10.2
platformio-ide|pla|2.4.0
[Potential Bug Powershell 1.docx](https://github.com/microsoft/vscode/files/7656914/Potential.Bug.Powershell.1.docx)

</details>

**Comment by COD-Team** [comment]
New to submitting, was the word doc attached reviewed? What additional information is required?

**Comment by gjsjohnmurray** [comment]
I don't see any Word doc.

Please describe step by step how to reproduce the problem as simply as you can. Include script text that can be copied.

**Comment by COD-Team** [comment]
Potential Bug Powershell 1.docx is in the initial post at the bottom of the grid, will open and post here in a min

**Comment by COD-Team** [comment]
[Potential.Bug.Powershell.1.docx](https://github.com/microsoft/vscode/files/7656978/Potential.Bug.Powershell.1.docx)

See if you can access....

**Comment by COD-Team** [comment]
Script
$DomainComputers = Get-ADComputer -Filter {OperatingSystem -like "Windows*"} -Properties Name | Select-Object -ExpandProperty Name
$results = Invoke-Command -ComputerName $DomainComputers -ErrorAction SilentlyContinue -ScriptBlock {Get-NetFirewallProfile}
$results | out-file -Append C:\COD-Logs\Firewall.txt

Mixed Results
Execute inside of ISE
Execute inside of VSCode

ISE provides clean information, VSCode provides numbers in place of the string value. The Values as an example for NotConfigured differ. Clean table in the word doc in this tread.

**Comment by Tyriar** [comment]
Can you please attach a screenshot or something that shows the difference? I don't want to open a foreign word document on my machine/account.
