### ISSUE TITLE
Suggestion: show some suggestions whilst waiting for auto import suggestions

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#138449]
I work on a large TypeScript codebase and I've noticed that suggestions in VS Code have gradually felt slower as the codebase has grown in size.

I recently discovered that suggestions appear significantly faster when we disable TypeScript's auto import suggestions (`"typescript.suggest.autoImports": false`).

As an example, here is a quick test where I type `window` in an empty file (which is part of a large TypeScript project).

### Before (`"typescript.suggest.autoImports": true` aka the default):

https://user-images.githubusercontent.com/921609/144722257-5fe818bb-5223-47fe-8da3-c85fdde2fea2.mov

(The second time I type `window` it's _slightly_ faster because the auto import suggestions are cached, but still nowhere as fast as I would like it to be.)

### After (`"typescript.suggest.autoImports": false`):

https://user-images.githubusercontent.com/921609/144722285-38de1c30-068a-4c29-a790-04046543f49d.mov

In many cases, I don't want auto import suggestions, I just want suggestions for something that's already in scope such as `window` or a variable that's currently in scope. It seems silly that I have to wait for TypeScript to calculate auto imports before I can use any of the other suggestions.

I could just disable auto import suggestions but they are still useful in some cases. For this reason I would like to make a suggestion: VS Code should show suggestions immediately, whilst it waits for the auto import suggestions to arrive—rather than the current behaviour which is to show 0 suggestions until the auto import suggestions have arrived, which makes users wait longer for suggestions which in many cases they won't need.

I'm sure there are UX concerns here which I haven't fully thought through, but hopefully they can be solved!

**Comment by mjbvz** [comment]
Our current suggestion UI needs to know all possible suggestions before it displays. Otherwise the suggestion list could reorder itself while you are browsing through it, which would be a very bad user experience 

Can you please open an issue against TypeScript so we can investigate why computing auto imports is taking a long time in the first place?

**Comment by OliverJAsh** [comment]
> Otherwise the suggestion list could reorder itself while you are browsing through it, which would be a very bad user experience

Would it be acceptable to just append the new suggestions at the end of the list when they arrive? So trading off sorting for speed.

> Can you please open an issue against TypeScript so we can investigate why computing auto imports is taking a long time in the first place?

I already did that in https://github.com/microsoft/TypeScript/issues/44826. Some improvements were made but the issue of slow auto imports still remains. 

Even if TypeScript was able to reduce the computing time for auto imports, say from 1 second to 500 milliseconds, I think my suggestion in the original post above remains: I want to see suggestions *immediately*. Even a couple of hundred milliseconds is noticeable lag when I'm in the flow of writing code.

**Comment by OliverJAsh** [comment]
Here's a related TypeScript issue which details the performance problem: https://github.com/microsoft/TypeScript/issues/32174.

So far there is no obvious performance optimisation so I think we should reconsider my suggestion above?
