### ISSUE TITLE
Allow Jump to Any Line (up and down) while debugging

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#138410]
While debugging, sometimes you need to _go back_ to previous lines instead of running again the whole debugging, or  _go forward_ to further lines, ignoring some lines of code.

I use VS Code on a daily basis, for C#, TypeScript, JavaScript and Go, and from time to time I miss this feature. I came from Delphi, which calls this feature `New EIP` (https://docwiki.embarcadero.com/RADStudio/Sydney/en/Disassembly_Pane). Just recently I started using Jetbrains Rider too, and it also has a similar feature, called `Jump to Any Line`/`Drag to Skip Code` (https://blog.jetbrains.com/idea/2020/08/jump-to-any-line-while-debugging/).

I didn't find this feature in VS Code, but I'm not entirely sure this is something that depends only on VS Code, or if does need some improvements in Debug Adapter Protocol as well. Looking at their documentation, I didn't find anything about it.

Thank you

**Comment by weinand** [comment]
VS Code's generic debugger UI supports "Restart Frame", "Run to Cursor", "Jump to Cursor", and "Back in time debugging". Most likely you are looking for the "Jump to Cursor" (which is called "Set Next Statement" in VS). If you really want to step backwards (in time), then you are looking for "Back in time debugging".

But please note, all these features are only visible in the UI if a debugger extension implements them (via DAP).

**Comment by alefragnani** [comment]
@weinand , thanks for the detailed information!

I’ll follow your instructions and look closer on each debugger. If TS and C# has, I’ll be really happy 😄 .

Thank you
