### ISSUE TITLE
Highlighting in HTML breaks with extra " (double quotes)

### ISSUE THREAD

**Issue by alljamin** [Microsoft/vscode#13843]
- VSCode Version: 1.6.1
- Colour theme: Light+ (default light)
- OS Version: macOS Sierra 10.12

Steps to Reproduce:

1. Create HTML file with any reference to link e.g. `<link rel="stylesheet" href="main.css">`
2. Add an extra double quote e.g. `<link rel="stylesheet"" href="main.css">`
3. Add some placeholder HTML after this line.
4. See that all the highlighting messes (reverts?) up after the line with extra ".

![vscode](https://cloud.githubusercontent.com/assets/10956179/19426759/cee4b75a-9486-11e6-845b-4b3d78918447.gif)

No changes in `settings.json` content

**Comment by aeschli** [comment]
A extra quote will cause some syntax highlighting strangeness, that's to be expected and IMO not a bug.
You can file improvement requests for the html grammar to https://github.com/textmate/html.tmbundle
