### ISSUE TITLE
Folder creating

### ISSUE THREAD

**Issue by Den0702** [microsoft/vscode#138405]
Issue Type: <b>Bug</b>

Hello, 

If I'm not wrong, here seems to be a bug:

When attempting to create a folder to be a sibling relating to other folders within workspase it lands to .vscode folder inspite of  the fact that previously I removed a focus from ./vscode directory. Here is the  [screencast](https://1drv.ms/u/s!AuGXFEbvzmTCkQ-z7FjwB0zFazY1?e=V0bRQZ)

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
vscode-firefox-debug|fir|2.9.5
auto-close-tag|for|0.5.13
debugger-for-chrome|msj|4.13.0
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.6.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
vscexrecpromptt2:30404948
vscop804:30404766
vscop341:30404997
vsrem710cf:30405999

```

</details>

**Comment by imRonakGiri** [comment]
please update visual studio code...

**Comment by JacksonKearl** [comment]
Hm, I'm a bit confused as to your workspace setup here, you're in a multi-root workspace configuration, and it looks like you've added a `.vscode` folder as a root to that workspace? So when you create a folder with nothing selected, it defaults to putting it in that first root. 

Are you trying to maybe add an entirely new root folder to the multi-root workspace? In that case use the `Workspaces: Add folder to Workspace" command. I see how this is a but confusing, but the explorer's new folder action is not intended for modifying workspaces.
