### ISSUE TITLE
PLEASE make the tooltip of  git menu shown the origin git command

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#138460]
for a cjk language user, it is really really hard to understand the localization string. especially people who are used to git cli command or learn git from git cli

![image](https://user-images.githubusercontent.com/1876302/144741149-78d5b1df-55c4-4b78-bceb-d6ef3df2896f.png)

for English user, it is easy to understand .
abort rebase is easier to be recognized as `git rebase --abort`. 

Also that will be great to show the cli command for all language user

![image](https://user-images.githubusercontent.com/1876302/144741242-47eeeaf6-3853-4f62-8207-14ddeab02376.png)

similar to https://github.com/microsoft/vscode/issues/104999

please. that will be great for those people who are used to git cli

**Comment by Fuahi** [comment]
really want this
非常需要这个

**Comment by heartacker** [comment]
哑巴吃黄连,有苦说不出
我虽不是哑巴,但谁理解哑巴.

**Comment by heartacker** [comment]
close because of this, https://github.com/microsoft/vscode/issues/138653
of course, few people want this maybe and few people voted.
