### ISSUE TITLE
终端

### ISSUE THREAD

**Issue by yanhaocheng666** [microsoft/vscode#138494]
终端中切换分支时有冲突的，使用快捷键cmd + 左键想跳转到选中的文件，可是一点击就跳转到一个新的vscode中

**Comment by CodeCrazy-ywt** [comment]
# Terminal

Conflicts might happen when switching branches. I wanna go to selected file using ctrl + left mouse button, but every time I use this shortcut it opens a new window.

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
