### ISSUE TITLE
VSCode is undefined in debug console when debug extension

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#138444]
Version info:

```
Version: 1.63.0-insider (Universal)
Commit: d09289a2b6dd0e56b2a264a8e9380685498e10d6
Date: 2021-12-04T02:02:08.723Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
ms-vscode.js-debug-nightly: v2021.11.1217
```

Steps to Reproduce:

1. clone repository: https://github.com/tjx666/path-autocomplete
2. add breakpoint in following screenshot position
3. input `vs` in debug console

![image](https://user-images.githubusercontent.com/41773861/144714439-d65f91ac-b94d-446d-ab6a-4795d35cb4ef.png)

@weinand

**Comment by connor4312** [comment]
TypeScript needs to implement `names` mapping for imports in order to fix this: https://github.com/microsoft/TypeScript/issues/9627

**Comment by pflannery** [comment]
I had the same issue for imports with vscode too.
Shame Typescript doesn't translate esm named imports to a equivalent left-hand destructor in cjs. 

Instead it translates  

```js
// esm
import { workspace } from 'vscode'`
const codeLensEnabled = vscode.workspace.getConfiguration().get('editor.codeLens')
``` 
into 
```js
// cjs debug evaluate fails :'(
const vscode_1 = require("vscode");
const codeLensEnabled = vscode_1.workspace.getConfiguration().get('editor.codeLens')
```

A workaround I found is to trick the compiler by using `import * as vscode from 'vscode'`

```js
// esm
import * as vscode from 'vscode'
const codeLensEnabled = vscode.workspace.getConfiguration().get('editor.codeLens');
```
translates into 
```js
// cjs debug evaluate works!
const vscode = require("vscode");
const codeLensEnabled = vscode.workspace.getConfiguration().get('editor.codeLens');
```
