### ISSUE TITLE
Relative unstable SSH leads to loss of data

### ISSUE THREAD

**Issue by davide-f** [microsoft/vscode#138468]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.0-insider
- OS Version: 21H2 build 19044.1348

Steps to Reproduce:

1. Connect to SSH
2. Work on it
3. After a while it is impossible to interact with the remote session and all changes are lost

I have been using VSCode with a remote connection through VPN + SSH for developing code in a remote unit.
To be clear, when I experienced this issue, I was connected through hotspot from my mobile with 4G yet with low signal; the VPN never lost connection or highlighted problems but probably there may be delays or other issues that lead VSCode to get disconnected without having notifications.

While developing simple notebooks <= 5MB total size including outputs of script, sometimes VSCode starts to be unable to save the changes in the remote element and cannot recover.
When that occurs, changes are lost and I don't have a way to save and restore the changes later. This is really annoying and made me lose 4+ hours of work several time.

This can prevent me from work properly and I highly recommend to provide features to overcome this issue.
Thank you

**Comment by roblourens** [comment]
Merging this into https://github.com/microsoft/vscode/issues/138784
