### ISSUE TITLE
High CPU consumption when disconnected to network

### ISSUE THREAD

**Issue by Kerr19** [microsoft/vscode#138493]
Issue Type: <b>Performance Issue</b>

High CPU consumption when disconnected to network

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 7, 6|
|Memory (System)|16.00GB (1.58GB free)|
|Process Argv|--crash-reporter-id 218af0f1-121a-4ce8-99db-bbbc5545d321|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   32	   147	  7737	code main
    0	    49	  7740	   gpu-process
    0	    33	  7742	   utility
   13	   279	  7744	   window (test.py — pytorch)
  111	   180	  7770	     extensionHost
    0	   131	  7888	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) --ms-enable-electron-run-as-node /Users/genius/.vscode/extensions/ms-python.vscode-pylance-2021.11.2/dist/server.bundle.js --cancellationReceive=file:7aad134930513d4ed3f921bb05f41275fc8ff827bd --node-ipc --clientProcessId=7770
    0	    33	  7771	     watcherServiceNSFW
   13	   213	  7745	   window (开始)
  111	   147	  7769	     extensionHost
    0	   131	  7768	   shared-process
    0	    49	  7772	     ptyHost
    0	     0	  7908	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    66	  7906	   window (问题报告程序)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (test.py — pytorch)
|    Folder (pytorch): 20 files
|      File types: py(3) DS_Store(1) gitattributes(1) gitignore(1) md(1)
|                  meta(1) html(1) gz(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
anes|gam|0.0.2
leek-fund|gis|2.0.1
vscode-leetcode|Lee|0.18.0
vscode-language-pack-zh-hans|MS-|1.62.4
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
cpptools|ms-|1.7.1
veriloghdl|msh|1.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593cf:30376535
vssld246cf:30401891
vscop804:30404766
vscop453:30404998

```

</details>

**Comment by CodeCrazy-ywt** [comment]
# High CPU consumption when disconnected to network

When disconnected to network, vscode may comsume cpu very heavily, after a while cpu consumption returns normal.

**Comment by heartacker** [comment]
same problem。
vscode crash even at launch
![image](https://user-images.githubusercontent.com/1876302/144822096-8c026f72-8c15-40fc-ba92-53c2a4486103.png)

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
