### ISSUE TITLE
Hello teacher! After verifying that still missing items 1 and 2 in this iteration not solved it

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#138457]
Hello teacher!
After verifying that still missing items 1 and 2 in this iteration not solved it

Um! Teacher, your idea is great! Great! But I don’t know if your idea can solve this problem: [https://github.com//issues/134326], if it can be solved directly in the next milestone, then thank you very much, teacher, You are really very, very great, very, very awesome 👍👍👍😜!

It may be that what I described earlier is not clear enough or detailed enough. . . Here again, the detailed explanation is as follows: Hello, teacher! It is recommended that the font foreground color of the widget needs to be changed. I used red numbers and green arrows to make detailed marking instructions. I also used the green box to mark the range of the font foreground color that needs to be changed. Please see the picture below:
![140309160-5988199c-0cd3-46f9-ac96-f59d76e114a7](https://user-images.githubusercontent.com/54253524/144733582-fecde42f-ac72-4521-8eb4-1234964a160d.png)
Hello, teacher!
If you confirm my needs, please reply, thank you very much!
https://github.com/microsoft/vscode/issues/134326

**Comment by gjsjohnmurray** [comment]
Doesn't https://github.com/microsoft/vscode/issues/134326#issuecomment-933315205 work for you?

**Comment by zhouxinghong** [comment]
> Doesn't [#134326 (comment)](https://github.com/microsoft/vscode/issues/134326#issuecomment-933315205) work for you?

Dear Teacher!
Hello!
https://github.com/microsoft/vscode/issues/134326
I just solved the foreground color of the area marked with number 3, but I did not solve the foreground color of the area marked with red numbers and yellow oval background color and the area marked with number 1 and number 2 with green boxes. Thank you very much for your help!😜

**Comment by zhouxinghong** [comment]
Hello, teacher!
The new year has come, I wish the teachers a happy new year! ! !
In the new year, I hope that the teacher can help solve this problem in time, thank you very much!👍👍👍👍👍👍😜😜

**Comment by zhouxinghong** [comment]
Hello, teacher!
        VSCode is a great project that gives users the greatest autonomy from the very beginning, allowing users to personalize configurations according to their own habits, so it can fully surpass the long-born jetbrion series in just 5 years. The most important reason is that VSCode's open source thinking and allowing users to customize and configure VSCode development methods to the greatest extent can achieve today's achievements. I hope VSCode can continue to develop this way of thinking and development, focusing on every reasonable request of users and need. Thank you here!
                                                             vscode contributors
                                                             20220126

**Comment by zhouxinghong** [comment]
> Doesn't [#134326 (comment)](https://github.com/microsoft/vscode/issues/134326#issuecomment-933315205) work for you?

Hello, teacher!
        VSCode is a great project that gives users the greatest autonomy from the very beginning, allowing users to personalize configurations according to their own habits, so it can fully surpass the long-born jetbrion series in just 5 years. The most important reason is that VSCode's open source thinking and allowing users to customize and configure VSCode development methods to the greatest extent can achieve today's achievements. I hope VSCode can continue to develop this way of thinking and development, focusing on every reasonable request of users and need. Thank you here!
                                                             vscode contributors
                                                             20220126
