### ISSUE TITLE
Unable to define custom integrated terminal profile

### ISSUE THREAD

**Issue by Merith-TK** [microsoft/vscode#138451]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.2
- OS Version: Windows 11, 21H2 (build 22000.348)

Steps to Reproduce:

1. settings.json
2. attempt to define custom workspace profile
```json
{

	//"terminal.integrated.shell.windows": "C:\\Users\\zachd\\scoop\\shims\\ssh.exe",
	//"terminal.integrated.shellArgs.windows": "pi@192.168.0.111",

	"terminal.integrated.profiles.windows": {
		"pizero": {
			"path": "C:\\ProgramData\\scoop\\shims\\ssh.exe",
			"args": ["pi@192.168.0.111"]
		}
	},
	"terminal.integrated.defaultProfile.windows": "pizero",
	"Lua.diagnostics.globals": [
		"parallel",
		"keys",
		"shell",
		"periphery"
	]
}
```

VSCode only allows the default shells and nothing else
![image](https://user-images.githubusercontent.com/10422110/144725236-d427a116-5c57-47e9-bcc5-39ca7832b413.png)

ssh is infact located at that path
![image](https://user-images.githubusercontent.com/10422110/144725228-c85f0b56-712c-4611-a9f5-5eada2f50410.png)

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by clitetailor** [comment]
For me it the same, it does not work on both VSCode 1.63.0 and 1.64.0-insider versions.
![image](https://user-images.githubusercontent.com/16368559/145624542-c209a673-96ed-411c-934e-190075ffef37.png)
![image](https://user-images.githubusercontent.com/16368559/145624601-c92ee718-1e49-41dd-b550-b1512a7a80ac.png)

**Comment by LaurentLesle** [comment]
I have a similar issue with version 1.63.1 on macos M1.

If I open vscode with source code from local folder, I expect the user settings to be processed first then the workspace in the .vscode subfolder

Neither if I set my profile in user or workspace the shell appears.

![image](https://user-images.githubusercontent.com/4702224/149146218-02ae32cd-4f0b-4a33-be1b-0619b1d79746.png)

![image](https://user-images.githubusercontent.com/4702224/149146308-555fe029-ec5f-4df0-85e8-5c9a084d874b.png)

![image](https://user-images.githubusercontent.com/4702224/149146368-32d853dc-1609-4644-9de4-f43ad3dceaf0.png)

I also tried to create a custom workspace

![image](https://user-images.githubusercontent.com/4702224/149146768-6b233e8b-3b42-4004-95ec-fe1f09a906e5.png)

reopened vscode from that workspace but still no terminals.

![image](https://user-images.githubusercontent.com/4702224/149146878-238e8116-9d1b-4624-8b8b-8edb08b556d0.png)

It is only when I open my source code in a remote containter (devcontainer or remote ssh host) that I get the workspace profiles processed correctly (with a caveat as I would expect the Remote settings to overwrite the workspace settings to be more specific to the remote environment(documentation does not mention the Remote in the inheritance process, will open another issue - https://code.visualstudio.com/docs/getstarted/settings#_settings-precedence)

![image](https://user-images.githubusercontent.com/4702224/149147461-f21db268-be86-4cda-b346-f9133444e016.png)

**Comment by meganrogge** [comment]
Can you enable trace logging and toggle the shared process and attach the logs when you launch/save the profile?

**Comment by LaurentLesle** [comment]
is that what you are looking for? This is what I get when I open the code-workspace. I tried to update the profile but the log (Shared) is not showing any activity

![image](https://user-images.githubusercontent.com/4702224/149612959-37f3abb9-fe0b-4a51-aa9d-d1884be13e37.png)


![image](https://user-images.githubusercontent.com/4702224/149612799-d7d5b9f2-cde5-4e23-9c64-500f2365cb4b.png)

**Comment by meganrogge** [comment]
Open the command palette (ctrl or cmd shift p) toggle shared process. Then, command palette set log level trace.

**Comment by meganrogge** [comment]
open the command palette ctrl or cmd shift p
toggle shared process
command palette set log level - trace
do something or reload the window
share the logs
