### ISSUE TITLE
'files.associations' doesn't work

### ISSUE THREAD

**Issue by CarterLi** [Microsoft/vscode#13840]
- VSCode Version: 1.6.1 & earlier
- OS Version: macOS 10.12 & earlier

Steps to Reproduce:

1. Edit user settings:
```json
{
  "files.associations": {
    "*.vue": "HTML"
  }
}
```

2. Open a `.vue` file

Result: The file is opened as plain text file with no syntax highlighting
Expected: The file is recognised as HTML files

**Comment by bpasero** [comment]
```
"files.associations": {
	"*.vue": "html"
}
```
