### ISSUE TITLE
 Cannot read property 'symbols' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#13849]
Issue Id: <b>95a8fd68-a1e5-c106-9f72-02d444277430</b><br /><br />*Versions* <br />- 1.6.1<br />-  e52fb0bc87e6f5c8f144e172639891d8d8c9aa55<br />*Stack* <br />TypeError: Cannot read property 'symbols' of undefined<br />[/vs/workbench/api/node/extHostLanguageFeatures.ts#L75:72 (symbols)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L75:72 (symbols))<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />[/vs/workbench/api/node/extHostLanguageFeatures.ts#L75:50 (then)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L75:50 (then))<br />[/vs/workbench/api/node/extHostLanguageFeatures.ts#L719:71 (provideCodeLenses)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L719:71 (provideCodeLenses))<br />[/vs/workbench/api/node/extHostLanguageFeatures.ts#L693:9 (callback)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L693:9 (callback))<br />[/vs/workbench/api/node/extHostLanguageFeatures.ts#L719:14 (_withAdapter)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L719:14 (_withAdapter))<br />[/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply))<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L269:39 (handle)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/platform/extensions/common/ipcRemoteCom.ts#L269:39 (handle))<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L226:25 (invokeHandler)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/platform/extensions/common/ipcRemoteCom.ts#L226:25 (invokeHandler))<br />    at _combinedTickCallback (internal/process/next_tick.js:67:7) <no sourcemaps><br />    at process._tickCallback (internal/process/next_tick.js:98:9) <no sourcemaps><br />

**Comment by jrieken** [comment]
Obsolete - code as been removed
