### ISSUE TITLE
ColorPicker bug

### ISSUE THREAD

**Issue by KA-Mirza** [microsoft/vscode#138448]
![VSCode_issue_01](https://user-images.githubusercontent.com/95545487/144722288-3d1e4103-d55d-4e6c-8a9e-b0d0b80d3b8e.png)
![VSCode_issue_02](https://user-images.githubusercontent.com/95545487/144722289-a59374be-58e7-483e-a270-b435bf4f7b7e.png)
Issue Type: <b>Bug</b>

There is a problem with ColorPicker. Tool normally pop ups on color hover, but color value (alphanumeric string) does not appear in caption, until caption been clicked or value changed using controls.
The problem has been observed for several months in a row on different computers, including clean install: no extensions, no previous installation. OS - win10x64 21H1(AMD platform), 21H2(Intel platform).

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.1

</details>

**Comment by ssigwart** [comment]
This looks like a duplicate of #136224.  I think a fix for this is in the next VS Code version.

**Comment by KA-Mirza** [comment]
Thank you for reply.
Excuse me, but it is not the [#136224](https://github.com/microsoft/vscode/issues/136224) issue. In my case - _initial_ value of color does not appear. 
This issue exists since 1.60.X version (August 2021) at least. But works properly in 1.48 (July 2020).

**Comment by yume-chan** [comment]
The screenshot looks same as in https://github.com/microsoft/vscode/issues/83589#issuecomment-944765950, #136224 fixed that.

**Comment by KA-Mirza** [comment]
I really did not find how [#136224](https://github.com/microsoft/vscode/issues/136224) fixed that. Topic just contains video with properly working tool. Neither clue, nor steps how to fix it

**Comment by KA-Mirza** [comment]
Problem was fixed by Microsoft in VSCode 1.63.0 (November 2021). Thank you!
Also thanks a lot for all participator
![VSCode_fixed_01](https://user-images.githubusercontent.com/95545487/145822543-e31923e0-b4d6-418f-ba1f-3eb0d3e98cfc.png)
s
