### ISSUE TITLE
How to remove this extra spaces from VS Code Editor?

### ISSUE THREAD

**Issue by kunaltyagi9** [microsoft/vscode#138416]
I was working on VS Code Editor and suddenly I pressed some key which created this space around window

![Screenshot (115)_LI](https://user-images.githubusercontent.com/43796571/144645126-09ba41fd-becf-4abc-918e-88b2c77bbc97.jpg)

How can I remove this space?

**Comment by alexdima** [comment]
I think that might be the zen mode.

**Comment by JacksonKearl** [comment]
Looks like it, the "Toggle Zen Mode" command should work.

**Comment by ArturoDent** [comment]
`View/Appearance/Centered Layout` uncheck it if it is enabled.

**Comment by kunaltyagi9** [comment]
View/Appearance/Centered Layout it was enables, I disable it and it got fixed. Thankyou
