### ISSUE TITLE
Terminal process stat failed

### ISSUE THREAD

**Issue by Force1ess** [microsoft/vscode#138489]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.62.3
- OS Version:Win11 10.0.22000

Steps to Reproduce:

1.open integrated terminal
2.start failed and report error
`error code is 15700`
And I searched it, here it is
[Error code 15700](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--12000-15999-#:~:text=APPMODEL_ERROR_NO_PACKAGE-,15700%20(0x3D54),-The%20process%20has)
I tried to change my default terminal to "Windows Terminal" and roll back, doesn't works
<img width="349" alt="image" src="https://user-images.githubusercontent.com/72636351/144801731-a556370c-7695-4828-98fd-5f0b166b4882.png">

**Comment by meganrogge** [comment]
Do you have anti-virus software that could be blocking the terminal? If so try following the instructions in https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch
/label "needs more info" terminal

**Comment by Force1ess** [comment]
@meganrogge 
Hi, I don't have any anti-virus software and windows defend was also disabled
Can't get any useful info from this help doc
Any more info if you need please tell me and I'll reply soonly

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by Force1ess** [comment]
What hell, I uninstalled Power Shell, and everything became fine.
This might be caused by PowerShell Not Windows Power Shell
I don't understand that PowerShell was not my default terminal.
