### ISSUE TITLE
Emmet autocomplete inside a pair of [ ] in a React file is wrong

### ISSUE THREAD

**Issue by aindriu80** [microsoft/vscode#138461]
Does this issue occur when all extensions are disabled?: Yes (disabling Emmet)

- VS Code Version: - 1.62.3
- OS Version: - Ubuntu 21.10 

Steps to Reproduce:

1. Open a .js file which is denoted a React file by VSCode 
2. As part of the coding implement state for a counter with the following simple line: `const [state, setState] = useState`
3. After getting as far as typing `setState` I wish to just exit the square brackets however Emmet takes the first position 
4. Pressing tab results in an HTML string appearing, see pictures

Question: How do I move Emmet down the list of suggestions in Autocomplete for a React file, I am using other extensions like TabOut (to get out of the square brackets without any autocomplete) which would be more appropriate.

![2021-12-05_10-39](https://user-images.githubusercontent.com/8885837/144743395-8c7958a3-7350-4d0a-b2e4-72b6f8fbefa8.png)
![2021-12-05_10-40](https://user-images.githubusercontent.com/8885837/144743397-e7b789e2-8b75-45e3-8801-5a80b611e895.png)
![2021-12-05_10-40_1](https://user-images.githubusercontent.com/8885837/144743399-14e6ae2f-be6f-4dcf-a94e-31b6a8c02e74.png)
![2021-12-05_10-41](https://user-images.githubusercontent.com/8885837/144743406-f83dc9aa-c2da-4cb8-b8e4-32f7cb88e2ca.png)

**Comment by tjx666** [comment]
This issue heavily affect the react users.

**Comment by rzhao271** [comment]
Verification steps:
1. Create a JSX file.
2. Type `const [count, setCount]`.
3. There should not be an Emmet suggestion.
