### ISSUE TITLE
Terminal can't close

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#138443]
Version info:

```
Version: 1.63.0-insider (Universal)
Commit: d09289a2b6dd0e56b2a264a8e9380685498e10d6
Date: 2021-12-04T02:02:08.723Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```

Steps to Reproduce:

1.clone repository https://github.com/tjx666/vscode-fe-helper
2.using command `yarn` to install dependencies
3.ensure there had been an terminal you open in normal way, for example `cmd + j`
3.startup debug with config `Run Extension`, will open another terminal run background task
4.click stop debug button to stop debug
5.close the first terminal
6.try to close the terminal startup by debug, can't close it

@Tyriar

**Comment by weinand** [comment]
@tjx666 I cannot reproduce your problem:

/Users/weinand/Library/Application Support/CleanShot/media/media_72g5oM6YBe/CleanShot 2022-01-11 at 11.43.47-converted.mp4

**Comment by tjx666** [comment]
Seems had been fixed.
