### ISSUE TITLE
where are the scrollbar buttons?

### ISSUE THREAD

**Issue by jasonzuvela-wywm** [microsoft/vscode#138484]
Issue Type: <b>Feature Request</b>

how to enable scrollbar buttons?

cant just use the mousewheel, because i want to scroll individual lines.

![image](https://user-images.githubusercontent.com/88409869/144793758-ffb0a088-99be-47f8-9527-afe22fd1d803.png)

other hand is busy typing/copy/pasting

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

**Comment by gjsjohnmurray** [comment]
See my comment at https://github.com/microsoft/vscode/issues/130616#issuecomment-897178161

**Comment by alexdima** [comment]
Let's track in #130616
