### ISSUE TITLE
Menubar is very chatty to persist `lastKnownMenubarData`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138491]
Looking into a recent issue with `IStateMainService` and how we store some data in `storage.json` (instead of our SQLite DB) I noticed how there is a constant stream of JSON data being pushed to the main side (from the window) to persist `lastKnownMenubarData` almost on every action I do (even just clicking into the editor).

Some thoughts:
* Is this really necessary and what is the purpose of that data
* Can we change to persist it only on shutdown
* Can we send it less often to the main side

I see around 22k of JSON data being pumped through the IPC connection for the menu bar data. That is a lot more than e.g. saving typical source code files :O

**Comment by sbatten** [comment]
this data is sent over frequently to deal with `when` and `precondition` clauses

**Comment by bpasero** [comment]
The reason I bring this up is https://github.com/microsoft/vscode/issues/138072. Since the data goes into a file on disk (and not a DB), frequent writes have a risk of corrupting the file in case VSCode crashes, because each write is a truncate first.

**Comment by bpasero** [comment]
Workspace history is no longer stored in this file, if you don't plan to revisit this feel free to close.

**Comment by sbatten** [comment]
thanks for the update
