### ISSUE TITLE
getting 10,000+ matching instances in "Find in Files" results on vscode.dev

### ISSUE THREAD

**Issue by YaStone0** [microsoft/vscode#138431]
When I try to get all instances matching a regex pattern from the "Find in Files" results where there are 20,000+ matching instances,
1) if I choose "Copy All", what I get is just the initial 10,000 instances.
2) if I choose "Open in editor", I can get all lines, but each line is limited to the initial 1,000 characters.

So it seems I can't obtain all matching instances.

I'd like to have an option in the settings where we can select the maximum number of
1) instances in the "Copy All" function beyond 10,000, and
2) characters in each line in the "Open in editor" function beyond 1,000.

Thanks.

**Comment by ArturoDent** [comment]
Does the setting `Search: Max Results` have any effect?

**Comment by YaStone0** [comment]
Thanks for your suggestion, @ArturoDent.
But that setting is related to how many results can be obtained.
I'd already changed this setting to null, so I can get all, more than 20,000, results for my regex search.

What I want to do is to retrieve all the matching parts in the results.
In other words, I want to copy all, not just the initial 10,000 instances, of the matching instances displayed on the lower left side of the screen after the search.

**Comment by roblourens** [comment]
Are you saying that when you set the Max Results setting, then use Copy All, you don't copy all the results that are displayed?

**Comment by YaStone0** [comment]
@roblourens Yes, that's what I mean.
I face the same problem both on the stable version and on the insider version of vscode.dev.

**Comment by YaStone0** [comment]
Thanks for your fixing.
