### ISSUE TITLE
Extension Readme Loading Time Regression

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#138409]
(observed for installed extensions, but I think it is slower for all extensions)

Insiders:
![recording](https://user-images.githubusercontent.com/2931520/144629368-440159a9-3fc9-482f-aa5c-19a7a48f1be6.gif)

Stable:
![recording](https://user-images.githubusercontent.com/2931520/144629230-80700000-06d0-48b2-aba4-460ec6a2cd6b.gif)

**Comment by joaomoreno** [comment]
cc @sandy081

**Comment by JacksonKearl** [comment]
Seeing similar slowness in Getting Started, cc @mjbvz is it maybe a general markdown issue?

**Comment by sandy081** [comment]
Yes, I can confirm that markdown rendering has slowed down. Hence assigning back to @mjbvz

**Comment by mjbvz** [comment]
Doesn't seem to happen for the markdown preview which suggests to me something in core with markdown rendering. Let me know if you notice this for any other webviews

**Comment by mjbvz** [comment]
I have a potential fix but don't yet understand why it works

To summarize: when loading webviews, we load a file called `fake.html` from the disk. This file is very small and should be loaded almost instantly. And it is for normal webviews

However for the extension editor, the network request for this file is in the `stalled` state for almost a full second. I've confirmed that our code to serve this file runs very quickly (however it is only hit after the stall) so the stall must be happening somewhere else: https://github.com/microsoft/vscode/blob/03a2bf8dd74aa4a2c3ba5d857bce753741829c9a/src/vs/platform/webview/electron-main/webviewProtocolProvider.ts#L29

Unlike other webviews, the extension editors all share a single internal webview identifier. This means that the requests look like:

```
vscode-webview://extensioneditor/fake.html?id=3202b879-1c32-41c4-80f8-c353cc5f9ae4 
```

However if I change the extension editors to also have unique ids for the requests, the stall disappears

```
vscode-webview://UUID/fake.html?id=3202b879-1c32-41c4-80f8-c353cc5f9ae4 
```

My best guess right now is there's a cache lookup or something that causes the stall (I thought it could be the service worker, but both cases have the service worker enabled)

**Comment by joaomoreno** [comment]
cc @deepak1556 @bpasero

**Comment by mjbvz** [comment]
Also porting fix to November release

**Comment by deepak1556** [comment]
There is a limit on the number of socket connections per host, currently it is set to 6 in all chromium based browsers https://source.chromium.org/chromium/chromium/src/+/main:net/socket/client_socket_pool_manager.cc;l=43-54,  it is very likely possible that we hit this when using the same origin for extension editors. I can confirm if this is the case by taking a net log with `--log-net-log`.
