### ISSUE TITLE
`resolveMarketplaceHeaders` is running too early

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138492]
The call to:

https://github.com/microsoft/vscode/blob/5b805e41413463215a5016459afca19f4fe0fce2/src/vs/platform/windows/electron-main/window.ts#L307-L310

Runs very early on startup even before a window opens. We pass a stub of the `IStorageMainService` into that method and that seems to be used to resolve a "service machine identifier". However, at the time the storage service is used, it will operate in-memory because it is only initialized when the window opens to reduce startup pressure.

Q: do we really need to resolve this so early? When I see usages, it seems to only being used here:

https://github.com/microsoft/vscode/blob/5b805e41413463215a5016459afca19f4fe0fce2/src/vs/platform/windows/electron-main/window.ts#L544-L548

But these requests are likely only being made when the user opens the extensions viewlet, no? I would suggest to push the resolving of market place headers to a later point after the storage service has been initialized. I can expose a method to wait on that.

**Comment by bpasero** [comment]
Fyi I have [pushed](https://github.com/microsoft/vscode/commit/11d343aef8d5d93562ba8ec208cc33caa7828c7c) `storageMainService.globalStorage.whenInit` support.

**Comment by sandy081** [comment]
I can also make this promise/request created on demand.
