### ISSUE TITLE
 Cannot read property 'disposables' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#13848]
Issue Id: <b>90f81f4f-c0d0-c2b9-140c-47e2d3759c34</b><br /><br />*Versions* <br />- 1.6.1<br />-  e52fb0bc87e6f5c8f144e172639891d8d8c9aa55<br />*Stack* <br />TypeError: Cannot read property 'disposables' of undefined<br />[/vs/workbench/api/node/extHostLanguageFeatures.ts#L108:51 (disposables)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L108:51 (disposables))<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />[/vs/workbench/api/node/extHostLanguageFeatures.ts#L108:15 (then)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L108:15 (then))<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />[/vs/workbench/api/node/extHostLanguageFeatures.ts#L105:54 (then)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L105:54 (then))<br />[/vs/workbench/api/node/extHostLanguageFeatures.ts#L719:71 (provideCodeLenses)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L719:71 (provideCodeLenses))<br />[/vs/workbench/api/node/extHostLanguageFeatures.ts#L693:9 (callback)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L693:9 (callback))<br />[/vs/workbench/api/node/extHostLanguageFeatures.ts#L719:14 (_withAdapter)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L719:14 (_withAdapter))<br />[/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply))<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L269:39 (handle)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/platform/extensions/common/ipcRemoteCom.ts#L269:39 (handle))<br />

**Comment by jrieken** [comment]
code has been removed
