### ISSUE TITLE
Allow creation of new folder (especially remote)

### ISSUE THREAD

**Issue by Apreche** [microsoft/vscode#138411]
Imagine a user opening VSCode. They want to start coding a brand new project from scratch. A directory for this project doesn't even exist yet. How can they create it? Obviously they could create the directory very easily using many tools that are external to VSCode, such as explorer or a shell. But how can they create that new directory within VSCode?

One way is to make a new file first. Then when the user saves that file using the save as dialog box (which is just explorer), they can create a new directory from there. After they save the file in that directory, they must still take the extra step of opening that directory.

Now imagine they are using a remote VSCode window, for instance using wsl. The save as option no longer uses explorer. The prompt that is offered only permits the user to enter a path that already exists. The easiest way they have to create this initial project directory is to go into the wsl terminal, which is still technically external to vscode. Again, they must then take the additional step of opening the directory.

Another idea might be to create a Git repository that is blank and then clone it to start the project. That would work, but there's no way to create a new Git repository from within VSCode. The user has to create that Git repository externally and then clone it. Even the Github extension offers no way to create a new repository, only clone an existing one.

VSCode seems to simply lack the concept of "new project." It expects that, at bare minimum, a blank directory for the project already exists to be opened and then worked on. 

I am requesting an option be added to the File menu and command palette called `New Folder`. This command should require that the user provides the path to this new folder to be created. Assuming the path is valid, VSCode should create the folder as an empty directory, and then immediately open the folder. It would be a nice bonus if it would `git init` inside that folder. Importantly, this functionality should still work if there is a remote connection that supports it, such as wsl.

**Comment by JacksonKearl** [comment]
A "Create Folder" welcome view item in the explorer could be helpful.

**Comment by gjsjohnmurray** [comment]
See also #71425

**Comment by JacksonKearl** [comment]
@gjsjohnmurray thanks, I knew I remembered something along those lines but I couldn't find it. I'll close this in favor of that one.
