### ISSUE TITLE
Ubuntu Repository for Edge seems to be broken

### ISSUE THREAD

**Issue by aaron-kunde** [microsoft/vscode#138412]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Hello, out pipeline build fails, since we install edge on ubuntu for integration tests, like:

      sudo apt-get install software-properties-common apt-transport-https wget
      wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
      sudo apt-get install microsoft-edge-beta

**Comment by Tyriar** [comment]
edge != vscode
