### ISSUE TITLE
HTML: Add select to input list

### ISSUE THREAD

**Issue by richarddunnebsc** [microsoft/vscode#138401]
When using HTML, users can create a select list by typing "sel" then return.  As select is a form input type, it would make sense that it would also appear in the input type list after typing "in", wouldn't it?

**Comment by aeschli** [comment]
You are talking about emmet completion in HTML, correct?
![image](https://user-images.githubusercontent.com/6461412/144610811-fc9b68c2-12ff-4e9c-a437-0d6bdfa0b4f0.png)

**Comment by richarddunnebsc** [comment]
Correct.  Although the only existing approach for select is faster, a lot of developers may find this approach just as useful, as an alternative.  It seems common sense that select would be in the list of input types anyway.

**Comment by richarddunnebsc** [comment]
Can I track the vote count?
