### ISSUE TITLE
Code.exe deleted after upgrade

### ISSUE THREAD

**Issue by jorticus-msft** [microsoft/vscode#138478]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.62.3 ??
- OS Version: Windows 11

Steps to Reproduce:
Unknown, possibly due to failed upgrade.

---

Not sure how this happened, but somehow VSCode deleted itself during an upgrade.

The main shortcut no longer points to a valid executable, and further investigation reveals that the entire contents of `C:\Program Files\Microsoft VS Code\bin` is **empty**!!

There does seem to exist a Code.exe under `C:\Program Files\Microsoft VS Code\_` but at this stage I'm not sure how to recover, except for wiping and re-installing.

Seems there is a severe bug in the upgrade process.

**Comment by deepak1556** [comment]
Can you attach the updater log files `vscode-inno-updater-*` from `%LOCALAPPDATA%\Temp\`, thanks!

**Comment by calscot** [comment]
Just happened to me too
[vscode-inno-updater-1638810921.log](https://github.com/microsoft/vscode/files/7662441/vscode-inno-updater-1638810921.log)
.

**Comment by deepak1556** [comment]
Thanks for the log! Updater failed with the following error

```
Dec 06 17:15:53.543 ERRO Failed to mark file for deletion: Access is denied.
```

Looping in @joaomoreno for the inno-updater, looks like the updater process aborted after https://github.com/microsoft/inno-updater/blob/c69dd8dc599607fcd56ee0b2e8f47f0edc15a034/src/main.rs#L167 failed. Can we add some more logging around https://github.com/microsoft/inno-updater/blob/c69dd8dc599607fcd56ee0b2e8f47f0edc15a034/src/handle.rs#L68 to find out on which file the operation failed.

**Comment by jorticus-msft** [comment]
> Can you attach the updater log files `vscode-inno-updater-*` from `%LOCALAPPDATA%\Temp\`, thanks!

These logs seem to have disappeared for me. 

Fortunately after re-installing, everything is back to normal (extensions and settings have not been lost)

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
