### ISSUE TITLE
Mancato calcolo variabili

### ISSUE THREAD

**Issue by Wallaby90** [microsoft/vscode#138446]
Issue Type: <b>Bug</b>

const arr = [1, 2, 3, 4, 5];

let sum = 0;
for (let num of arr) {
  sum += num;
}

console.log('somma = ${sum}');

Quando vado ad effettuare il console.log tramite il terminale del programma, non effettua il calcolo ma bensì appare solamente ciò che c'è all'interno delle parentesi, ossia:
somma = ${sum}

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Genuine Intel(R) CPU             575  @ 2.00GHz (1 x 1995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.93GB (1.32GB free)|
|Process Argv|--crash-reporter-id 1009615e-609b-443c-8b13-a3dd6f697c0b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.5.0
vscode-language-pack-it|MS-|1.62.4
remote-wsl|ms-|0.58.5
powershell|ms-|2021.10.2
vscode-typescript-next|ms-|4.6.20211203
tsimporter|pmn|2.0.1
typescript-hero|rbb|3.0.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30405811
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30405999

```

</details>

**Comment by albertosantini** [comment]
Hello @Wallaby90. I think this is not related to VSCode. Need to use backquote, not single quote.
