### ISSUE TITLE
Folding is not working continuously

### ISSUE THREAD

**Issue by byterocker** [microsoft/vscode#138400]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.62.3
- OS Version: 10.0.19042

Steps to Reproduce:
The folding feature is one time working with "(defun" and sometimes not
Code:
(defun ctx:dyn:setprop ( blk prp val )
    (setq prp (strcase prp))
    (vl-some
       '(lambda ( x )
            (if (= prp (strcase (vla-get-propertyname x)))
                (progn
                    (vla-put-value x (vlax-make-variant val (vlax-variant-type (vla-get-value x))))
                    (cond (val) (t))
                )
            )
        )
        (vlax-invoke blk 'getdynamicblockproperties)
    )
)
(defun ctx:dyn:setprops ( blk prps  ) ; properties als cons Liste
(mapcar (lambda ( y )
    (vl-some
       '(lambda ( x )
            (if (= (strcase (car y)) (strcase (vla-get-propertyname x)))
                (progn
                    (vla-put-value x (vlax-make-variant (cdr y) (vlax-variant-type (vla-get-value x))))
                    (cond ((cdr y)) (t))
                )
            )
        )
        (vlax-invoke blk 'getdynamicblockproperties)
    )
    )prps)
)
![image](https://user-images.githubusercontent.com/95368231/144599788-2f4c1a02-69f1-4970-a437-501e1bafd71e.png)

**Comment by aeschli** [comment]
It looks like indentation based folding is used here.
Indentation base folding is the default for all languages that don't provide a language specific folding provider.
With Indentation base folding, a folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To be smarter and to, for example, understand lisp syntax, we will have to install an extension.
Just quickly browsing the VS Code marketplace, https://marketplace.visualstudio.com/items?itemName=ailisp.commonlisp-vscode could be a good fit.
