### ISSUE TITLE
 Cannot read property 'heightInLines' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#13844]
Issue Id: <b>18a86ff0-6fcd-f79c-ad6a-1fba3e35a348</b><br /><br />*Versions* <br />- 1.6.1<br />*Stack* <br />TypeError: Cannot read property 'heightInLines' of null<br />[/vs/editor/contrib/zoneWidget/browser/zoneWidget.ts#L298:21 (heightInLines)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/contrib/zoneWidget/browser/zoneWidget.ts#L298:21 (heightInLines))<br />[/vs/editor/contrib/gotoError/browser/gotoError.ts#L440:17 (call)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/contrib/gotoError/browser/gotoError.ts#L440:17 (call))<br />[/vs/editor/contrib/gotoError/browser/gotoError.ts#L400:51 (_relayout)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/contrib/gotoError/browser/gotoError.ts#L400:51 (_relayout))<br />[/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />[/vs/editor/contrib/gotoError/browser/gotoError.ts#L400:35 (then)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/contrib/gotoError/browser/gotoError.ts#L400:35 (then))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L117:26 (call)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/common/event.ts#L117:26 (call))<br />[/vs/editor/contrib/gotoError/browser/gotoError.ts#L130:31 (fire)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/contrib/gotoError/browser/gotoError.ts#L130:31 (fire))<br />[/vs/editor/contrib/gotoError/browser/gotoError.ts#L138:7 (move)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/contrib/gotoError/browser/gotoError.ts#L138:7 (move))<br />[/vs/editor/contrib/gotoError/browser/gotoError.ts#L471:10 (next)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/contrib/gotoError/browser/gotoError.ts#L471:10 (next))<br />

**Comment by jrieken** [comment]
obsolete - code has been removed

**Comment by mattgodbolt** [comment]
I'm seeing this when expanding annotations (with F8) the first time in my custom monaco editor-based website. Any ideas what might be causing it?

**Comment by mattgodbolt** [comment]
This is easy to reproduce in e.g. https://microsoft.github.io/monaco-editor/
