### ISSUE TITLE
Add a obvious icon of searching in explorer.

### ISSUE THREAD

**Issue by futurehome** [microsoft/vscode#138486]
Please make search in explorer more obvious, like add search icon, and can search even when the folders are collapsed.

**Comment by gjsjohnmurray** [comment]
#66971 is about adding a way to resolve all subfolders.

**Comment by JacksonKearl** [comment]
#66971 tracks searching in model rather than view, we aren't likely to change the UI here as it is used in many places and extra indications would be noisy. 

I recommend Ctrl/Cmd+P for file searching.
