### ISSUE TITLE
auto align colons in object literals, variables, and equals like WebStorm

### ISSUE THREAD

**Issue by kinergy** [Microsoft/vscode#13841]
- VSCode Version: 1.6.1
- OS Version: macOS 10.12

Using Format Code on a js file:
```
var abcde = 'abcde',
    def   = {
      a : 'aaa',
      bb: 'b'
    };
```
turns into:
```
var abcde = 'abcde',
  def = {
    a: 'aaa',
    bb: 'b'
  };
```

It would be really nice to have a setting to align the beginning of var names, align the equals, and align the colons in object literals like WebStorm. I tried looking for an extension, but wasn't able to identify one.

**Comment by waderyan** [comment]
@kinergy thank you for opening this issue. 

@jrieken is this issue related to the formatting stab you are doing?

**Comment by jrieken** [comment]
Nah, the actual formatting smarts must come from an extension - TypeScript/JavaScript in this case. What we do it just calling into those formatters and apply their results

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11865
