### ISSUE TITLE
cannot close dirty file after join / split in group action

### ISSUE THREAD

**Issue by xiaoas** [microsoft/vscode#138442]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version:1.62.3, both stable & insider
- OS Version: Windows 11 21H2

Steps to Reproduce:

1.  open a file, make it dirty
2. split right
3. right click the left tab & select split in group
4. try to close the right tab, I'm prompted to save or discard the content

Desired behavior:

The editor should not prompt me just like the one mentioned in #8983

Another Steps to Reproduce:

1. open a file, make it dirty
2. open untracked diff view in source control -> click file name
3. close either tab, I'm not allowed to.

**Comment by bpasero** [comment]
Nice catch.
