### ISSUE TITLE
`providerLabel` not used with `git.api.getRemoteSources`

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#138407]
I was verifying https://github.com/microsoft/vscode/issues/111658, when I saw that my `providerLabel` is not being used now.

Snippet:
```ts
    const results = await vscode.commands.executeCommand('git.api.getRemoteSources', {
        providerLabel: (provider: any) => `Testing the branch picker of ${provider.name}`,
        urlLabel: `URL`,
        branch: true
	});
```

In stable:
![image](https://user-images.githubusercontent.com/38270282/144623074-ae97db0a-ab5d-4d7a-ac14-74b86e14be87.png)

In insiders:
![image](https://user-images.githubusercontent.com/38270282/144623149-3f9d2b5b-9274-4a93-81fa-50da18753630.png)

**Comment by lszomoru** [comment]
@alexr00, is this still an issue. Cannot reproduce this issue in the latest Insiders release.

<img width="748" alt="image" src="https://user-images.githubusercontent.com/3372902/151351343-dcb2ce87-10a1-4aa3-9b40-1b0886e46068.png">

**Comment by alexr00** [comment]
I also cannot repro anymore.
