### ISSUE TITLE
Markdown: outline view is blank

### ISSUE THREAD

**Issue by amitbha** [microsoft/vscode#138435]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- OS Version: Linux x64 5.10.79-1-MANJARO

Steps to Reproduce:

1. open a markdown file
2. open the outline view, but it's blank

![1204-1235-27](https://user-images.githubusercontent.com/4060625/144697146-21ed6e73-388e-48c5-8d2f-49761974ae8c.jpg)

Errors displayed in the Dev Tools Console:

~~~
workbench.desktop.main.js:602  INFO Starting extension host with pid 3590503.
workbench.desktop.main.js:602  INFO [LocalProcessExtensionHost]: IExtensionHostStarter.start() took 63 ms.
workbench.desktop.main.js:602   ERR [Extension Host] (node:3590503) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
workbench.desktop.main.js:77 [Extension Host] (node:3590503) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `code --trace-deprecation ...` to show where the warning was created)
E @ workbench.desktop.main.js:77
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout
~~~

**Comment by mjbvz** [comment]
Please share the text of the markdown file that causes this

/needsMoreInfo

**Comment by amitbha** [comment]
@mjbvz Any of markdown files.

[Send-Email-From-The-Linux-Command-Line.md](https://github.com/microsoft/vscode/files/7667488/Send-Email-From-The-Linux-Command-Line.md)
![1207-1818-37](https://user-images.githubusercontent.com/4060625/145011107-a9335852-03bb-4298-b651-ba14bd90c4dc.jpg)

The log from the Dev Tools Console (all extensions are disabled):
[vscode-app-1638872376434.log](https://github.com/microsoft/vscode/files/7667511/vscode-app-1638872376434.log)

**Comment by mjbvz** [comment]
Thanks. Works fine for me though 

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
