### ISSUE TITLE
Windows CaseSensitive file system support

### ISSUE THREAD

**Issue by Yurunsoft** [microsoft/vscode#138455]
Issue Type: <b>Feature Request</b>

run: `fsutil file setCaseSensitiveInfo "D:\myproject" enable`

then:

![image](https://user-images.githubusercontent.com/20104656/144733177-16962d51-f704-4fdd-9c05-9c1c50c0b72b.png)

VSCode does not support case sensitivity of file names under windows now

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/94307#issuecomment-704529221

Even though the title of that issue only mentions macOS other issues asking for the the same for Windows have been closed by team members as duplicates of it.
