### ISSUE TITLE
Editor in new folder is opened with wrong theme

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#138422]
- Open a new folder
- Trust the workspace
- Some of the colors in the window become wrong
- An editor has the wrong background color
- Opening the theme picker fixes it

![Dec-03-2021 10-43-36](https://user-images.githubusercontent.com/323878/144656274-606a7801-1717-478e-a13f-b3f8c3b172ac.gif)

**Comment by misolori** [comment]
I originally filed https://github.com/microsoft/vscode/issues/138349 because I encountered this during Settings Sync but think it's not related as I also saw this when opening files:

![image](https://user-images.githubusercontent.com/35271042/144670813-6c29035b-1373-4457-a92d-14f3f2d7ac3b.png)

**Comment by aeschli** [comment]
Step to verify
- connect to settings sync
- install and set the Dracula theme (`dracula-theme.theme-dracula`)
- notice that the remote indicator is violet
- open a new folder that is not yet trusted
- the trust dialog shows up, approve
- verify that the remote indicator is still violet, not blue
