### ISSUE TITLE
Change kernel gear icon does nothing

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#138554]
## Environment data

-   VS Code version: 1.63.0-insiders
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001532801
-   Python Extension version (available under the Extensions sidebar): v2021.12.1522449417-dev
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: N/A
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: N/A

## Expected behaviour

When I change my kernel and click on the gear icon, I expect some options to show up, such as setting that kernel to be the default one.

## Actual behaviour

When I change my kernel and click on the gear icon, nothing happens.

**Comment by rebornix** [comment]
@rzhao271 can you provide more details like your setup, or maybe a screen recording?

**Comment by rzhao271** [comment]
![Demo](https://user-images.githubusercontent.com/7199958/146286266-ad010b4d-7908-480f-bff4-32dbb33a3c44.gif)
