### ISSUE TITLE
Unable to `yarn install` with VS2022 build tools

### ISSUE THREAD

**Issue by JJRcop** [microsoft/vscode#138572]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: main @ 470cee7f66e0284846ae902308cc35ef69ab7d59
- OS Version:  Windows 10 Home 21H1 19043.1348 Windows Feature Experience Pack 120.2212.3920.0

Steps to Reproduce:

1. Don't have Visual Studio 2019 installed anywhere
2. Install prerequisites including Node.js but don't install native c++ build tools
3. Install Visual Studio Build Tools 2022 separately
4. Attempt to run `yarn install`

Result:

Receive error from `build\npm\preinstall.js`:

    Invalid C/C++ Compiler Toolchain. Please check https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites.

This is because Visual Studio Build Tools 2022 installs to `C:\Program Files (x86)\Microsoft Visual Studio\2022`, but `build\npm\preinstall.js` does not consider 2022 to be a supported version, only 2019 and 2017.

https://github.com/microsoft/vscode/blob/5f63d720d583f476a4c3a807774a674b622fcd2e/build/npm/preinstall.js#L48

I would prefer to save disk space and avoid installing Visual Studio Build Tools 2019 when I already have 2022 installed.

**Comment by joaomoreno** [comment]
Forwarding it to @deepak1556 in case he'd like to update our docs to include 2022 as well. Otherwise, we close it.

**Comment by deepak1556** [comment]
I haven't tested with 2022 yet, @JJRcop is rest of the yarn step successful after bypassing the preinstall step ?

**Comment by JJRcop** [comment]
Adding `'2022'` to the `supportedVersions` array works with node-gyp version v8.4.0 or later. When I made this issue, I was on v8.3.9, where it didn't work.

Upgrading node-gyp to v8.4.1 fixed install, and `yarn install` works without issue on VS2022.

https://github.com/nodejs/node-gyp/releases/tag/v8.4.0

**Comment by deepak1556** [comment]
Thanks for testing, given that this requires node-gyp `>=8.4.0` which also brings in https://github.com/nodejs/node-gyp/commit/a27dc08696911c6d81e76cc228697243069103c1, it won't build the native modules on the main branch correctly due to older electron version. We can add `2022` to the list once https://github.com/microsoft/vscode/pull/137241 lands.

**Comment by deepak1556** [comment]
@JJRcop `main` branch is now updated to Electron 16, do you want to send a PR to add `2022` to the supported list ? Thanks!
