### ISSUE TITLE
 Cannot read property 'cancel' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#13857]
Issue Id: <b>2eeaaa69-bb6f-674a-54aa-b9877b5a96d0</b><br /><br />_Versions_ <br />\- 1.6.1<br />\-  e52fb0bc87e6f5c8f144e172639891d8d8c9aa55<br />_Stack_ <br />TypeError: Cannot read property 'cancel' of null<br />[/vs/base/parts/ipc/node/ipc.cp.ts#L82:22 (cancel)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/parts/ipc/node/ipc.cp.ts#L82:22 %28cancel%29)<br />[/vs/base/parts/ipc/node/ipc.cp.ts#L77:38 (request)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/parts/ipc/node/ipc.cp.ts#L77:38 %28request%29)<br />[/vs/platform/telemetry/common/telemetryIpc.ts#L37:22 (call)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/platform/telemetry/common/telemetryIpc.ts#L37:22 %28call%29)<br />[/vs/platform/telemetry/common/telemetryService.ts#L119:18 (log)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/platform/telemetry/common/telemetryService.ts#L119:18 %28log%29)<br />[/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/common/winjs.base.raw.js#L1566:0 %28onComplete%29)<br />[/vs/platform/telemetry/common/telemetryService.ts#L107:32 (then)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/platform/telemetry/common/telemetryService.ts#L107:32 %28then%29)<br />[/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L164:34 (publicLog)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L164:34 %28publicLog%29)<br />[/vs/base/common/winjs.base.raw.js#L1209:0 (onError)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/common/winjs.base.raw.js#L1209:0 %28onError%29)<br />[/vs/base/common/winjs.base.raw.js#L901:0 (_notify)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/common/winjs.base.raw.js#L901:0 %28_notify%29)<br />[/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/common/winjs.base.raw.js#L1068:0 %28enter%29)<br />

**Comment by ramya-rao-a** [comment]
@isidorn am not sure why this got assigned to me ....

**Comment by isidorn** [comment]
@ramya-rao-a by accident, sorry.
