### ISSUE TITLE
Status Bar's "Editor End of Line" Option is Missing

### ISSUE THREAD

**Issue by dylan-k** [microsoft/vscode#138531]
Issue Type: <b>Bug</b>

I've seen in documentation that the statusbar shows a description of the EOL characters in use within the currently open file. It does not appear for me. If I right click on the statusbar, there's no option to enable the "editor end of line" feature.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10600 CPU @ 3.30GHz (12 x 3312)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|39.85GB (24.33GB free)|
|Process Argv|H:\\Notes\\.obsidian\\snippets\\worknotes-custom-styles.css --crash-reporter-id c4bca9c7-81c1-452a-b161-91313632a280|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icalendar|af4|1.0.1
vscode-m3u|af4|1.0.0
set-syntax|ahg|0.0.3
typewriterscrollmode|and|0.1.1
theme-verdandi|be5|2.0.1
markdown-checkbox|bie|0.3.2
vscode-intelephense-client|bme|1.8.0
findallinfile|bna|1.1.6
htmltagwrap|bra|0.0.7
language-hugo-vscode|bud|1.3.1
gitignore|cod|0.7.0
vscode-markdownlint|Dav|0.45.0
xml|Dot|2.5.1
settings-on-fire|edb|1.0.3
vale-server|err|0.14.2
vscode-todo-plus|fab|4.18.4
auto-rename-tag|for|0.1.9
vdf|GEE|0.0.7
giflens|gif|2.0.0
timing|Haa|2.6.0
vscode-pigments|jas|2.0.0
dupchecker|jia|0.1.7
vscode-go-template|jin|0.2.1
read-time|joh|1.0.0
vscode-insertdatestring|jsy|2.3.0
l13-projects|L13|1.1.0
markdown-shortcuts|mdi|0.12.0
rainbow-csv|mec|1.10.1
lipsum-generator|MrA|1.2.3
vscode-docker|ms-|1.18.0
remote-containers|ms-|0.205.2
remote-wsl|ms-|0.58.5
powershell|ms-|2021.10.2
sublime-keybindings|ms-|4.0.10
language-liquid|nei|0.1.1
linux-desktop-file|nic|0.0.18
subtitles-editor|pep|1.1.6
betterfountain|pie|1.8.10
vscode-yaml|red|1.2.2
datetime|rid|2.1.1
snippets-ranger|rob|0.20.2
wikitext|Row|3.6.1
vscode-scss-formatter|sib|2.3.2
shopify-liquid|sis|2.3.0
vscode-fileutils|sle|3.4.5
vscode-autohotkey|sle|0.2.2
rewrap|stk|1.15.4
markdown-kit|svs|1.2.0
vscode-markdown-paste-image|tel|0.13.8
new-blog-post|tim|0.0.6
html-validate-vscode|Tob|0.2.0
sort-lines|Tyr|1.9.0
remove-empty-lines|use|0.0.8
gistfs|vsl|0.3.0
todoist|way|0.1.1
twig|wha|1.0.2
city-lights-icon-vsc|Yum|1.1.3
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
vscop804cf:30404767
vscop940:30404999
vsrem710:30405998
vscexrecpromp3t1:30407762

```

</details>

**Comment by ArturoDent** [comment]
What kind of file is this occurring in?  All files or only certain types?

A jpg of the status bar might be helpful.  And did you try reloading with all extensions disabled?

**Comment by dylan-k** [comment]
This is happening to me in a text file, `.md` extension. I'll take a screenshot tomorrow.

**Comment by dylan-k** [comment]
After uninstalling a lot of old extensions I don't use anymore I can't duplicate this. Closing now. Sorry for the trouble.
