### ISSUE TITLE
Open JSON schemas in editor (vscode.dev)

### ISSUE THREAD

**Issue by lychung7** [microsoft/vscode#138543]
For vscode.dev, should JSON schemas be opened in a new editor tab rather than a new browser tab? It could be consistent with how they open up in the editor for desktop.

**Comment by aeschli** [comment]
Also for the desktop they don't open in an editor, but an external browser.

**Comment by lydiayschung** [comment]
Hmm, this is what I see on my end. 


https://user-images.githubusercontent.com/60596156/145069387-de99f3ee-62eb-43e8-a9d5-a132b61f0199.mov


https://user-images.githubusercontent.com/60596156/145069434-d99ce690-b001-475a-910d-f7649272c6bb.mov

**Comment by aeschli** [comment]
Ah, I see, thanks. On the desktop it's a `file` resource that is opened in an editor. On the web, it's a 'http' resource, typically opened in a browser.

**Comment by lydiayschung** [comment]
Oh gotcha, thanks for clarifying!
