### ISSUE TITLE
New empty file line keeps jumping while one types

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#138541]
I'm on the latest Insiders on macOS.
In a new empty file, when I try typing, a `...` appears on top of the first line, and then disappears as the file is being saved.

When there is IME input, the output looks even more glitchy:
![recording](https://user-images.githubusercontent.com/7199958/144904809-bcd71b26-9f2e-4d25-bc27-58fc92f7af88.gif)

The first line is by typing rkr, pausing, and then typing rkr again using the 2-set Korean keyboard. The second line is by typing test and then pressing 1 with the Sogou keyboard, and then I switch to the usual US layout and type test again.

**Comment by alexdima** [comment]
@rzhao271 This doesn't reproduce for me. Does this reproduce when disabling all extensions?

https://user-images.githubusercontent.com/5047891/144991684-ae04e187-ada4-47dc-b68b-368a6374e5b4.mp4

**Comment by eamodio** [comment]
@rzhao271 While GitLens is adding (and ultimately removing) the CodeLens when it is computing a possible Git CodeLens, from your video there seems to be another VS Code issue going on, where the CodeLens line and the editor line are combined for some reason.

**Comment by alexdima** [comment]
@eamodio :+1: Yes, that is the `<textarea>` used for input which is revealed when doing IME. When IME begins, it used to be that we would record the `(top;left)` coords where the cursor was and we would always render the textarea at those coordinates for the duration of the composition. https://github.com/microsoft/vscode/pull/139394 improves that and we now record the logical `(lineNumber,distanceToLineStart,distanceToLineEnd)` so the textarea would now (with the latest Insiders) reposition itself in cases like this .
