### ISSUE TITLE
Allow blacklisting paths in auto import suggestions

### ISSUE THREAD

**Issue by skog-newglue** [microsoft/vscode#138579]
In certain scenarios, such as when using a monorepo with Angular and Nx, you will have an `index.ts` file for your libraries which acts as the entry point. This creates huge issues when using `project-relative` imports, as it suggests the `index.ts` file instead of the actual file. Using the `index.ts` file will cause any app consuming the library to crash.

Here I expect to get `../../helpers/global/is-external-url` instead of `../../../index`:

<img width="783" alt="Screenshot 2021-12-07 at 11 08 30" src="https://user-images.githubusercontent.com/83581833/145010011-6824765f-2322-4085-a89c-c8311df374de.png">

There are two possible solutions here as I see it:

1. Allow blacklisting paths for auto imports
2. Suggest all possible paths and let the developer choose which path is correct

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
