### ISSUE TITLE
Extension shows no status

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#138527]
Testing #138075

I created an extension that solely consist of the `package.json` file:
```json
{
    "name": "settings-override",
      "displayName": "settings-override",
      "description": "testing settings overrides",
      "version": "0.0.1",
      "engines": {
          "vscode": "^1.63.0"
      },
      "contributes": {
          "configurationDefaults": {
              "[markdown]": {
                  "editor.wordWrap": "on"
              }
          }
      }
 }
```

When I install this extension as a `vsix` I get the following:

The extension entry in the extensions view is disabled, i.e. I don't know whether the extension is active or not: 
![image](https://user-images.githubusercontent.com/4674940/144765479-d87df0e1-5951-467b-a072-a1408744a7dc.png)

**Comment by sandy081** [comment]
It seems the extension has not defined the publisher id in which case the extension view and extension host are using different extension id. Fixed it by changing it to use same extension id.

**Comment by hediet** [comment]
> When I install this extension as a vsix I get the following:

When I try to package the single file as vsix, it already says

> ERROR  Missing publisher name. Learn more: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publishing-extensions

Thus, unclear how to test the actual issue.

**Comment by sandy081** [comment]
You can always go to the extension installation folder location and edit the package.json and remove the publisher id there and try
