### ISSUE TITLE
Smoke test flake: VSCode Smoke Tests (Electron) Launch verifies that application launches when user data directory has non-ascii characters

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#138551]
This test failed 3 times in the last 30 days:

![image](https://user-images.githubusercontent.com/2193314/144920602-67487cd1-35be-47ed-a6d4-da264f42f28c.png)

https://monacotools.visualstudio.com/Monaco/_build/results?buildId=145504&view=results

```
Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/1/s/test/smoke/out/main.js)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

Looks like it was reported flaky earlier in the year: https://github.com/microsoft/vscode/issues/119816

**Comment by dbaeumer** [comment]
@bpasero assigning to you. The issue @Tyriar mentioned was about localization.

**Comment by bpasero** [comment]
I wonder if we can convert this test into a integration test.

**Comment by bpasero** [comment]
Same answer as https://github.com/microsoft/vscode/issues/138614#issuecomment-988954352
