### ISSUE TITLE
Always access to the file-path of the text editor

### ISSUE THREAD

**Issue by mtirionMSFT** [microsoft/vscode#138523]
I'm creating a VSCode Notebook extension. The notebook is about parsing Liquid (a templating language). Besides the liquid template fragments you type in code blocks it can also use the users data-files and Liquid templates on disk. That's all handled by a parser I include in the extension. To have a configuration per notebook, I've added a 'Settings' language to my notebook where you can do something like:

```yaml
DATA .\Data
TEMPLATES .\Templates
```

The provided paths can be absolute, but also relative. My idea is that relative paths are resolved from the location of the notebook in the editor. Currently the way to get the file-path of the open text editor in code is through this piece of code:

```Typescript
vscode.window.activeTextEditor?.document.uri.fsPath
```

The problem is that if the file gets larger than 50 MB, `activeTextEditor` returns `undefined` (because of memory saving. See https://github.com/Microsoft/vscode/issues/32118). I understand that this is done for the contents of the file, but now it's a bit weird behavior now when the `activeTextEditor` is set or `undefined`. I have a notebook currently 8 KB in size (so, very small) and in one run of the code `activeTextEditor` is set, a few milliseconds later it's undefined. 

Request: I would like to have a standard way to obtain the path of the file in the text editor at all times, even if it's larger then 50MB.

**Comment by jrieken** [comment]
There are no plans to have an editor without a documents. There are plans to expose editor tabs (see https://github.com/microsoft/vscode/issues/133532) independent of the actual editor.

Forwarding to Alex for the actual limit of 50MB but I don't believe there are plans to change that.

**Comment by mtirionMSFT** [comment]
To better clarify the question: In a Notebook extension I only want to know the path of the file being edited. I don't care for contents of the file through the ActiveEditor. Someone pointed to the new 'tabs-functionality' that might be a solution. As long as I know the path of the current file through that api, that it would be okay. But if there are exceptions there too when data is available, then it's not an option for me.

**Comment by jrieken** [comment]
> I don't care for contents of the file through the ActiveEditor. 

The API doesn't know the concept of an editor without document. They are strictly coupled and therefore too large documents never have an editor. This will be different for tabs (see linked proposal above)
