### ISSUE TITLE
The wrong languageId for eslintignore file 

### ISSUE THREAD

**Issue by AkatQuas** [microsoft/vscode#138578]
Does this issue occur when all extensions are disabled?: Yes 

- VS Code Version: 1.62.3
- OS Version: Darwin x64 19.6.0

![image](https://user-images.githubusercontent.com/24731539/144998333-89713b72-c8fd-4df8-9f33-7fa0a0a87f88.png)

Steps to Reproduce:

1. Open an `.eslintignore` file in any editor.
2. Check out the `Output` channel, `css-language-feature` extension has started.

https://user-images.githubusercontent.com/24731539/144999516-7ca5b9fd-088d-42fe-ac9f-98bf08ad1f4c.mov

**Comment by aeschli** [comment]
I can reproduce with the `.eslintignore` from the vscode repo and all extensions disabled.

It's the language detector that identifies the file as `CSS`. 

The correct guess would be the `ignore` language, defined by the git extension. The association to this language happens in the `eslint` extension, which needs to be installed first.

Several approaches here:
- improve the language detection for `ignore` type files (@TylerLeonhardt)
- move the language association from eslint to git. We didn't do that so far as we thought the eslint extension is the better place as it knows about all eslint related files.

Moving to @TylerLeonhardt first. The file doesn't resembles css much, except from the comments :-)

**Comment by roshal** [comment]
can not reproduce

**Comment by TylerLeonhardt** [comment]
Moving this into the mega thread of samples that don't work for follow up there https://github.com/microsoft/vscode/issues/131450
