### ISSUE TITLE
When hovering mouse on function or something another, it shows ...loading forever

### ISSUE THREAD

**Issue by sverlubeton** [microsoft/vscode#138577]
![Untitled](https://user-images.githubusercontent.com/55356905/144997456-cc2b79a2-278e-44e8-a458-3f4ec49e9ce0.png)

**Comment by sverlubeton** [comment]
In case if I have many folders and files, a lot of code it shows ...loading forever. It happened two days ago probably, before it worked okay

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including platform, version, and whether the Start Extension Bisect command identifies an extension causing the problem.

**Comment by sverlubeton** [comment]
Version: 1.63.0-insider
Platform: Windows 11
I executed Start Extension Bisect command and it didn't identify problems

**Comment by heartacker** [comment]
same

**Comment by mjbvz** [comment]
@sverlubeton Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
