### ISSUE TITLE
Quick Outline uses a not ideal sorting

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#138502]
* create an extension in `$HOME/.vscode-oss-dev/extensions`:
* `package.json`:
```json
{
    "name": "m2517",
    "publisher": "alex",
    "version": "0.0.1",
    "engines": {
        "vscode": "^1.22.0"
    },
    "activationEvents": ["*"],
    "main": "main.js"
}
```
* `main.js`:
```js
const vscode = require('vscode');

exports.activate = function() {

    const symbols = [
        { name: "containers", range: { startLineNumber: 1, startColumn: 1, endLineNumber: 4, endColumn: 26 } },
        { name: "container 0", range: { startLineNumber: 2, startColumn: 5, endLineNumber: 5, endColumn: 1 } },
        { name: "name", range: { startLineNumber: 2, startColumn: 5, endLineNumber: 2, endColumn: 16 } },
        { name: "ports", range: { startLineNumber: 3, startColumn: 5, endLineNumber: 5, endColumn: 1 } },
        { name: "ports 0", range: { startLineNumber: 4, startColumn: 9, endLineNumber: 4, endColumn: 26 } },
        { name: "containerPort", range: { startLineNumber: 4, startColumn: 9, endLineNumber: 4, endColumn: 26 } }
    ];

    vscode.languages.registerDocumentSymbolProvider({ language: 'plaintext' }, {
        provideDocumentSymbols: (doc, token) => {
            return symbols.map(s => {
                return new vscode.SymbolInformation(
                    s.name,
                    vscode.SymbolKind.Object,
                    new vscode.Range(s.range.startLineNumber - 1, s.range.startColumn - 1, s.range.endLineNumber - 1, s.range.endColumn - 1)
                );
            });
        }
    })
    console.log(`I am alive!`);
}
```
* open a file in vscode `example.txt`:
```
containers:
  - name: nginx
    ports:
      - containerPort: 80
```
* Show outline (using `F1`, followed by `@`)

![image](https://user-images.githubusercontent.com/5047891/144836488-9da39750-aabe-4c02-888e-a8f566f9765a.png)

Notice how `name` is showing before `container 0`:
* `name` has the range [1,4,1,15]
* `container 0` has the range [1,4,4,0]
* it would be expected that `container 0` shows before `name` (because `name` is contained inside `container 0`).
* we believe this is happening because of [this](https://github.com/microsoft/vscode/blob/11d343aef8d5d93562ba8ec208cc33caa7828c7c/src/vs/editor/contrib/documentSymbols/outlineModel.ts#L463) usage and think that maybe a custom comparator should be written here instead of using `Range.compareRangesUsingStarts`.

**Comment by jrieken** [comment]
> we believe this is happening because of this usage and think that maybe a custom comparator should be written here instead of using Range.compareRangesUsingStarts.

Yeah, with equal starts we should look at ends as well. Tho, when flatten'ing the array parents should become before children and sort should later be stable... This is maybe specific to quick outline resorting again

**Comment by jrieken** [comment]
> Tho, when flatten'ing the array parents should become before children and sort should later be stable... This is maybe specific to quick outline resorting again

Nvm - there is no parent child-relation, it's all flat

**Comment by jrieken** [comment]
Oh, wow I completely forget/ignored that `Range.compareRangesUsingStarts` also looks at ends
