### ISSUE TITLE
Windows PowerShell should be in a "detected" section?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#138559]
I think we used to have a "detected" section when creating a terminal using a profile:

![image](https://user-images.githubusercontent.com/2193314/144928498-62c08f29-21c3-46a8-8fe5-2bb72a6cf85e.png)

Without a separate section, you don't know which are your actual profiles and which are the other less important ones.

**Comment by meganrogge** [comment]
explanation here

https://github.com/microsoft/vscode/issues/138558#issuecomment-988454665

**Comment by meganrogge** [comment]
I think we need to clarify the concept of `autoDetected`. there are these that are autoDetected, but those are often part of the config. (powershell for instance)

https://github.com/microsoft/vscode/blob/5248915eadd04a8723f7d15789e61e0ea49d2f3a/src/vs/platform/terminal/node/terminalProfiles.ts#L92-L119

maybe `available` would be better? or `outside of configured`?
