### ISSUE TITLE
Search button changed into Source control button

### ISSUE THREAD

**Issue by cpd55** [microsoft/vscode#138573]
Issue Type: <b>Bug</b>

So there are 2 Source controll buttons: 
- one leads to search (the tool tip says: Source control(cntr+shift+f) and the title of the search tool turned into "Source control". Othervise it is the search.
- the other leads to Source control

Don't know how it happened. I might moved around stuff. Also I did a re-install but the thing didn't changed back. (That is true that I didn't uninstall before the re-install.)

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (1.42GB free)|
|Process Argv|--crash-reporter-id 5f9da9ca-171d-4367-8f9f-10bf1c924e49|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
output-link-to-file|93a|0.0.17
Bookmarks|ale|13.2.2
vscode-django|bat|1.8.0
vagrant|bbe|0.5.0
vscode-markdownlint|Dav|0.45.0
py-pack|dav|1.2.0
python-preview|don|0.0.4
githistory|don|0.6.19
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
gitlens|eam|11.7.0
code-runner|for|0.11.6
gc-excelviewer|Gra|4.0.45
vscode-test-explorer|hbe|2.21.1
format-python-docstrings|ian|1.2.1
output-colorizer|IBM|0.1.2
python-coding-conventions|igr|0.0.4
vscode-edit-csv|jan|0.6.4
bracket-peek|jom|1.4.2
vsc-python-indent|Kev|1.14.2
vscode-python-test-adapter|lit|0.7.0
MagicPython|mag|1.1.0
code-groovy|mar|0.1.2
rainbow-csv|mec|1.10.1
vscode-docker|ms-|1.18.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.12.0
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-wsl|ms-|0.58.5
test-adapter-converter|ms-|0.1.4
gradle-language|nac|0.2.3
autodocstring|njp|0.5.4
oracledevtools|Ora|21.3.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.1
vscode-yaml|red|1.2.2
trailing-spaces|sha|0.3.1
mdx|sil|0.1.0
vscode-taskexplorer|spm|2.5.7
code-spell-checker|str|2.0.13
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.19.0
vscode-maven|vsc|0.34.1
jinja|who|0.0.8
bracket-lens|wra|1.5.1
vscode-mdx-preview|xyc|0.3.3
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
vsena315:30406435
vscop804:30404766
vscop940:30404999
vsrem710cf:30405999
vscexrecpromp3c:30407761

```

</details>

**Comment by joaomoreno** [comment]
Can you share a screenshot?

**Comment by sbatten** [comment]
to get to a clean state, you can run `Ctrl+Shift+P` > `View: Reset View Locations`... let me know if this helps

**Comment by cpd55** [comment]
Thanks for the reply the `Ctrl+Shift+P` > `View: Reset View Locations` solved the issue. For the records I am including here the screen-shot about how it looked like.

![image](https://user-images.githubusercontent.com/7595522/148220492-d942dd39-fd92-480a-963a-d74f017ac972.png)
