### ISSUE TITLE
cant load new file with same filename

### ISSUE THREAD

**Issue by Kurt-Shiwz** [microsoft/vscode#138555]
## Environment data
-   VS Code version: 1.62.3 (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
-   OS (Windows | Mac | Linux distro) and version: mac os 12.0.1 
-   Jupyter server running: Local

when i open a file `a.ipynb` and close the `a.ipynb` and remove `a.ipynb`. 
then make a copy of `b.ipynb` rename to `a.ipynb`, open it and i find the `file content` is `old a.ipynb` not the copy of `b.ipynb`.
i think vscode-jupyter load the `delete one` not the `new one`

**Comment by toshafaye** [comment]
*Tosha Wade*


*On Mon, Dec 6, 2021, 4:26 PM kurt ***@***.***
***@***.***>> wrote:*

**Comment by toshafaye** [comment]
Tosha Wade

**Comment by rebornix** [comment]
We have updated our file watcher recently and I'm not able to reproduce this issue anymore on latest Insiders on macOS. @ Kurt-Shiwz can you help verify?

**Comment by Kurt-Shiwz** [comment]
> We have updated our file watcher recently and I'm not able to reproduce this issue anymore on latest Insiders on macOS. @Kurt-Shiwz can you help verify?

not work, always show line through  on the tab, cant open the "new file"

![image](https://user-images.githubusercontent.com/7554917/152969883-85738bf9-309f-429a-8a00-b084cfd9105d.png)

vscode:1.64.0
mac:12.1

**Comment by rebornix** [comment]
@Kurt-Shiwz sorry for coming back to you late. Are you still seeing this issue? I'm a bit confused of what you are seeing (the strikethrough on the file name).
