### ISSUE TITLE
Settings Sync: `generateSyncPreview` takes > 1s on web

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#138511]
On https://insiders.vscode.dev, after having enabled Settings Sync once, I often see the workbench hang for a second at a time. After profiling I found out this is the culprit:

![image](https://user-images.githubusercontent.com/22350/144858776-f146e83b-df18-4cd9-a506-0f5bb24b7cd7.png)

**Comment by joaomoreno** [comment]
Actually, it reproduces in desktop, but the workbench doesn't get slow since that runs in the shared process:

![image](https://user-images.githubusercontent.com/22350/144859667-5a3c7b29-5340-4b4d-99d0-3cb007c3847c.png)

**Comment by sandy081** [comment]
Used `JSON.stringify` formatter instead of the formatter in the core. This takes down the amount of time from 1.26s to ~2ms. Also did some improvements to check if remote has changed when local resource has changed.

@aeschli - Please let me know if you want me to create an issue for the slowness while using the formatter + applyEdits in your json formatter?

**Comment by aeschli** [comment]
@sandy081 Your change makes sense. There's no point of first creating a string without whitespaces and then let the format add all the whitespaces again through edits.
I see there are more similar use cases of `format`. I can add a utility if that helps. The only think the utility would do is to make sure that we use tabs/spaces and eol as configured.

**Comment by joaomoreno** [comment]
> I see there are more similar use cases of `format`. I can add a utility if that helps. The only thing the utility would do is to make sure that we use tabs/spaces and eol as configured.

Also I guess preserving comments?

**Comment by aeschli** [comment]
> Also I guess preserving comments?

No, the utility would just cover this use case:
```
	const content = JSON.stringify(globalState);
	const edits = format(content, undefined, {});
	return applyEdits(content, edits);
```
Formatted JSON from an object.

**Comment by aeschli** [comment]
I added `toFormattedString` to stringify and format am object. Right now, it doesn't do much more than `JSON.stringify`, but if we add new formatting options it would cover these.
I updated the other users of `format` that didn't really care about the edits.
@sandy081 Feel free to switch to `toFormattedString`, if you are interested in formatting with options (eol, spaces...).

**Comment by sandy081** [comment]
Great, will use it. Thanks.
