### ISSUE TITLE
Git changes action always visible

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#138510]
When running with GIT enabled every editor gets a disabled "Open Changes" action. The command is enabled when the file in question has changes. This comes with a few concerns

* We usually don't show disabled commands in prominent locations (editor context, title etc) because space is constrained
* In past we only used to show the command for files with changes
* The command shows for files that aren't under source control, like files that are explicitly git-ignored or files from my download-folder, etc

<img width="515" alt="Screen Shot 2021-12-06 at 14 43 37" src="https://user-images.githubusercontent.com/1794099/144856650-ce8321e1-46ac-4844-adea-f220f2480332.png">

**Comment by lszomoru** [comment]
Fixed. Now, we should only show the action if the active file has changes.
