### ISSUE TITLE
VS Code Explorer window's Outline is blank "No symbols found in document"

### ISSUE THREAD

**Issue by WilliamDAssafMSFT** [microsoft/vscode#138562]
Issue Type: <b>Bug</b>

1. Open markdown for https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/create-locate-anchors-swift in VSCode.
2. Open Outline view under Explorer. The outline says "No Symbols found in document 'create-locate-anchors-swift.md'
3. Delete lines 194 and until the end of file. An outline immediately appears in the Outlline view. Must be something about this file's length or code samples? Is there a max number of "[!INCLUDE" statements we're hitting here?

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (11.28GB free)|
|Process Argv|--crash-reporter-id a45ec549-74b9-4b55-a90f-63ff9d102f0e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.2.0
Bookmarks|ale|13.2.2
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.45.0
docs-article-templates|doc|0.2.11
docs-authoring-pack|doc|0.1.15
docs-build|doc|0.3.8
docs-images|doc|0.0.9
docs-linting|doc|0.0.8
docs-markdown|doc|0.2.100
docs-metadata|doc|1.0.7
docs-preview|doc|0.3.57
docs-scaffolding|doc|0.0.12
docs-visual-areas|doc|0.2.1
docs-yaml|doc|0.2.7
remote-wsl|ms-|0.58.5
powershell|ms-|2021.10.2
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.2
code-spell-checker|str|2.0.13

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vshan820:30294714
vscod805cf:30301675
vsccppwt:30393681
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vscop804cf:30404767
vscop453:30404998

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
