### ISSUE TITLE
Password shows letters being entered in terminal while on SSH

### ISSUE THREAD

**Issue by danielfoster15** [microsoft/vscode#138595]
Issue Type: <b>Bug</b>

Sometimes (seemingly related to the connection?) my vscode shows my password while I enter it to do a push in git. The password appears letter by letter in light grey. This occurs when I am connected to remote via SSH, but not always. 

Not great while on zoom calls with screenshare etc. 

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.11.0-41-generic snap
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1062.9.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor (16 x 3044)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|31.30GB (23.50GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id e146c1c2-a2ae-4e8e-83e3-37ec96d0d19b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: tkw12|
|OS|Linux x64 3.10.0-1062.9.1.el7.x86_64|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3631)|
|Memory (System)|19.34GB (0.83GB free)|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
vscode-icons|vsc|11.8.0
perl-toolbox|d97|1.4.0
gitlens|eam|11.7.0
vscode-edit-csv|jan|0.6.4
plantuml|jeb|2.16.1
vscode-peacock|joh|4.0.0
chat|kar|0.35.0
rainbow-csv|mec|1.10.1
vscode-docker|ms-|1.18.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.12.0
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
vsliveshare|ms-|1.0.5090
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
java|red|1.1.0
bash-debug|rog|0.3.9
markdown-preview-enhanced|shd|0.6.1
html-preview-vscode|tht|0.2.5
terminal-zoom|try|1.7.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.19.0
vscode-java-test|vsc|0.33.0
vscode-maven|vsc|0.34.1
docker|vsc|1.0.0
yaml|vsc|1.0.0
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30408636
vscop804cf:30404767
vscop341:30404997
vsrem710:30405998
vscexrecpromp3t2:30407763

```

</details>

**Comment by gjsjohnmurray** [comment]
See #136063 and #130821
