### ISSUE TITLE
Can't view Notebook git diffs

### ISSUE THREAD

**Issue by RyanCantab** [microsoft/vscode#138567]
## Environment data

-   VS Code version: 1.62.3
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
-   Python Extension version (available under the Extensions sidebar): v2022.0.1547158216-dev
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Python 3.7 conda 4.10.3
-   Type of virtual environment used: conda
-   Jupyter server running: Local

## Expected behaviour

According to several sources, e.g.
https://code.visualstudio.com/docs/datascience/jupyter-notebooks
I should be able to view easily understandable diffs between notebooks.

## Actual behaviour

The diff viewer only shows the diff of the raw file.
Adding "notebook.diff.enablePreview": true to settings.json does not fix the issue.

## Steps to reproduce:

Make a notebook. Commit it. Change the notebook. Commit it. Go to Git Graph. Find the notebook file in the commit and select "View Diff".

**Comment by rebornix** [comment]
> Go to Git Graph

@RyanCantab is this view contributed by an extension?
