### ISSUE TITLE
Can't set breakpoint in vscode extension: unbound breakpoint

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#138534]
Version:

```
Version: 1.63.0-insider (Universal)
Commit: d09289a2b6dd0e56b2a264a8e9380685498e10d6
Date: 2021-12-04T02:02:08.723Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
ms-vscode.js-debug-nightly: v2021.11.1217
```

Steps to Reproduce:

1. git clone: https://github.com/tjx666/view-github-repository
2. install dependencies with `yarn`
3. debug with `Run Extension`
4. open `src/util.ts`, try to set breakpoint

![image](https://user-images.githubusercontent.com/41773861/144898242-e1acd6e7-4ee3-4826-b0f8-3ab62a106dba.png)

@connor4312

**Comment by weinand** [comment]
@tjx666 as long as your extension is not activated and the code in util.ts is not loaded, it is expected that newly created breakpoints are not validated.
Did you try to activate the extension?

**Comment by connor4312** [comment]
You also do not have `sourceMap: true` in your tsconfig. You'll need to add that for the compiler to emit sourcemaps, which are required in order to figure out how to set breakpoints in compiled code. Let us know if you have any more issues.
