### ISSUE TITLE
Use theme's warning color for ambiguous character outline

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#138518]
Forked off from https://github.com/microsoft/vscode/issues/138059#issuecomment-986844575

> Can you change this to use the theme's warning color? Otherwise it won't be using the right yellow in non Dark+/Light+ themes.

**Comment by hediet** [comment]
As a default? Sounds like a good idea.
Do you think this is a candidate?

**Comment by Tyriar** [comment]
I wouldn't make this a candidate at this point
