### ISSUE TITLE
VSCode memleaks. Hard.

### ISSUE THREAD

**Issue by nocturn9x** [microsoft/vscode#138549]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.0 and above
- OS Version: Artix Linux 20210726 (plasma-openrc) [x86_64] Kernel 5.15.5-artix1-1

Steps to Reproduce:

1. Open VSCode
2. RAM usage grows indefinitely until the system is brought to its knees (and I have 48 friggin GIGABYTES of RAM, just FYI)

It all happened after I updated vscode to 1.62.2 today. Tried downgrading it back to 1.62.0 to no avail. It's absurd: this tool is supposed to help developers get work done and it's making it impossible for me to use it.

__Note__: Don't even try to close this issue as "out of scope". I __will__ come for your head. With torches _and_ a pitchfork. Jokes aside though: this has to be fixed

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by nocturn9x** [comment]
Hi, thanks for the swift reply. I'll update this issue ASAP with the requested profiler information, although I'd like to reiterate that VSCode memleaks even with all extensions disabled and after a cold reboot (I haven't checked CPU usage, but my fan spin up real hard so I'll have to inspect that too)

**Comment by jrieken** [comment]
@nocturn9x ping for actionable info

**Comment by nocturn9x** [comment]
> @nocturn9x ping for actionable info

I have switched to using an older version of VSCode for now, as I need to get work done. I'll try to submit logs/dumps by the end of the week, sorry for the wait

**Comment by nocturn9x** [comment]
Apparently, uninstalling and reinstalling vscode entirely fixed the issue. No idea what caused it, probably a bad global config carried over from a previous version. Closing
