### ISSUE TITLE
TerminalConfigHelper - isMonospace sans-serif

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138584]
```
1) Workbench - TerminalConfigHelper
       TerminalConfigHelper - isMonospace sans-serif:

      Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      + expected - actual
```

https://github.com/microsoft/vscode/runs/4442518754?check_suite_focus=true#step:13:9041

**Comment by Tyriar** [comment]
Weird, the only async part of that test is `setUserConfiguration`:

https://github.com/microsoft/vscode/blob/8b2ddf274c7134312d79c14de92f9eb7c54e8360/src/vs/workbench/contrib/terminal/test/browser/terminalConfigHelper.test.ts#L175-L185

Which just returns `Promise.resolve(undefined)`:

https://github.com/microsoft/vscode/blob/4eb6b3832de7c5b44d3e5176735c58402fcdb697/src/vs/platform/configuration/test/common/testConfigurationService.ts#L49-L59
