### ISSUE TITLE
scss grammar: Meta property value was not fully recognized

### ISSUE THREAD

**Issue by edumqssan** [microsoft/vscode#138536]
Does this issue occur when all extensions are disabled?: Yes, after all the extensions were disabled the bug still appeared.

- VS Code Version: Version: 1.62.3 (user setup, appears with the insider version)
- OS Version:  Windows_NT x64 10.0.19043

### Describe the bug:

Part of syntax highlighting of meta.property-value mistaken as support.constant.mathematical-symbols

### Steps to Reproduce:

1. Create a file *.scss, (example: index.scss)
2. Add a style with the following code `font-family: source-code-pro, Menlo, Monaco, Consolas, 'Courier New',
    monospace;`
3. Now you should see the minus symbol in **source-code-pro** aren't recognized as a meta.property-value as it does in a *.css file

### Expected Behavior:

When add the source-code-pro without quotation in .css, the editor recognizes the symbol as part of meta.property-value

```css
code {
  font-family: source-code-pro, Menlo, Monaco, Consolas, 'Courier New',
    monospace;
}
```

### Screenshots:

The SCSS file showing meta property value was not fully recognized:
![Capture1](https://user-images.githubusercontent.com/56772885/144899081-e59079ee-0f8b-47bf-a4dc-b0a8fd651625.JPG)

CSS file showing meta property value being fully recognized:
![Capture2](https://user-images.githubusercontent.com/56772885/144899100-bf949d2a-e6fb-4fe4-8e94-1347bdcf576d.JPG)

**Comment by alexr00** [comment]
Thanks for the detailed issue! I have moved it to the repo that we pull our scss syntax highlighting grammar from: https://github.com/atom/language-sass/issues/287
