### ISSUE TITLE
GitHub

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode#138574]
Issue Type: <b>Bug</b>

I'm using VSCode GitHub/GitHub Lense extensions on a Ubuntu VM. I installed the snap version.
Everytime when I start VSCode I get request for allowing permissions to GitHub. On Mac I do not have this issue.

For some reason the GitHub extension/integration does not remember my settings.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.4.0-91-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2194)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 1, 0|
|Memory (System)|7.78GB (4.65GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 93018483-6c68-4874-a08d-8844484af4bf|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
doxdocgen|csc|1.3.2
gitlens|eam|11.7.0
vscode-pull-request-github|Git|0.32.0
vscode-test-explorer|hbe|2.21.1
plantuml|jeb|2.16.1
better-cpp-syntax|jef|1.15.10
vscode-catch2-test-adapter|mat|4.0.10
git-graph|mhu|1.30.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.12.0
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
test-adapter-converter|ms-|0.1.4
vsonline|ms-|1.0.3076
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30408636
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30405999
vscexrecpromp3t2:30407763

```

</details>

**Comment by alexr00** [comment]
Sounds like this is caused by the Git Lens extension.
