### ISSUE TITLE
Language status indicator - separate parent/child hover background color

### ISSUE THREAD

**Issue by lychung7** [microsoft/vscode#138540]
<img width="364" alt="Screen Shot 2021-12-06 at 9 37 40 AM" src="https://user-images.githubusercontent.com/60596156/144902623-0fd3b291-ed90-4a57-8ff7-b734b40f5045.png">

I noticed that the hover background color is the same for {} and JSON even though they have two separate dialogs that show up on hover. I didn't realize I needed to specifically hover each for the different dialogs. 

Can we have different hover background colors like below to distinguish between the two? 

<img width="399" alt="Screen Shot 2021-12-06 at 9 38 21 AM" src="https://user-images.githubusercontent.com/60596156/144902830-b9c75f39-08d4-48b4-9382-c104940ed529.png">

**Comment by bpasero** [comment]
I think I wasn't able to find a working color that was distinguishable enough to make a difference given all the colors we already use in the status bar. And I personally don't mind the way it is now, not sure we got any feedback from users?

**Comment by misolori** [comment]
I think it's not immediately obvious that there are two hovers because there is no direct feedback that it's there, which may be why we haven't seen any feedback. I think starting with a similar hover interaction that we have with the split run button would be a good start:

<img width="94" alt="CleanShot 2021-12-15 at 07 29 26@2x" src="https://user-images.githubusercontent.com/35271042/146215401-d4041503-7d21-44d1-9d87-88fd007a7ae7.png">

<img width="279" alt="CleanShot 2021-12-15 at 07 31 58@2x" src="https://user-images.githubusercontent.com/35271042/146215774-b814eae3-fa0c-4d56-b561-bfb8276fca97.png">

<img width="207" alt="CleanShot 2021-12-15 at 07 33 06@2x" src="https://user-images.githubusercontent.com/35271042/146215949-778df883-c468-4c41-9d0e-2c42f5e2131b.png">

**Comment by bpasero** [comment]
I had to pull quite some tricks to get the same background color appear when you hover over the one or the other item, are you saying we go back to only showing hover background where you hover over?

**Comment by misolori** [comment]
I think the preferred style is to use the dual hover feedback (what was originally proposed), I think we can use a mixture of opacity to make that happen. I also just opened https://github.com/microsoft/vscode/issues/139213 to make split hovers to be consistent so it would make sense that the language status indicator have similar hover feedback, like:

<img width="272" alt="CleanShot 2021-12-15 at 08 26 46@2x" src="https://user-images.githubusercontent.com/35271042/146225224-3ca7599b-76c8-412d-abde-32d1c809673e.png">

**Comment by bpasero** [comment]
@misolori I think we will end up with padding/margin issues when you move the mouse between the two because there is no real padding in between. If you can figure out the sizing and proof that in a video that shows the interaction between two, I can take a look.

**Comment by misolori** [comment]
Alright let me see what I can do

**Comment by misolori** [comment]
You can check out the [`misolori/language-status-hover`](https://github.com/microsoft/vscode/commit/7334d0f1b737970390d7d52b8a8fe1cb6dd7465b) branch for a sample, had to introduce a new color token with a slight higher opacity for the active item:

https://user-images.githubusercontent.com/35271042/146249235-ff895690-cc89-4eeb-9c71-8a5c5914a6c5.mp4

**Comment by bpasero** [comment]
@misolori thank you, works quite well. as I had indicated the padding is a little bit inconsistent between the one and the other item then:
![recording](https://user-images.githubusercontent.com/900690/146330599-23f98ceb-69cf-459d-86f5-1449ce0ef813.gif)

But I don't mind merging your change in if you want.

**Comment by misolori** [comment]
I think the inconsistent padding is ok otherwise the two items will appear farther away from each other and be a bit inconsistent with how we represent them in regular status bar items.

I'll merge in my changes then!

**Comment by misolori** [comment]
For verification, find a language status indicator by either opening a JSON or Typescript file (you'll see the `{ }` next to the language status bar item) and verify that each item has separate hover states. Also verify that you can theme `statusBarItem.compactHoverBackground`.
