### ISSUE TITLE
Windows PowerShell should use powershell icon

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#138558]
![image](https://user-images.githubusercontent.com/2193314/144928498-62c08f29-21c3-46a8-8fe5-2bb72a6cf85e.png)

**Comment by meganrogge** [comment]
this should already be happening https://github.com/microsoft/vscode/blob/5248915eadd04a8723f7d15789e61e0ea49d2f3a/src/vs/platform/terminal/node/terminalProfiles.ts#L97-L101

I guess it's getting set to undefined somewhere and thus uses the fallback?

**Comment by meganrogge** [comment]
Interestingly, I have windows powershell at the expected location for detection, but it's not picked up on.

![windows](https://user-images.githubusercontent.com/29464607/145100816-4f1e8a7f-5594-4e74-b37b-fcd9f11d145b.PNG)

**Comment by meganrogge** [comment]
Windows powershell isn't getting detected for me even though it exists at the expected path and i've added it to my system env vars.

**Comment by Tyriar** [comment]
Yeah, I saw that code too but wasn't on Windows to investigate further. At some point we merge the actual profiles with the `isAutoDetected` ones, we might be losing the icon and detected status (https://github.com/microsoft/vscode/issues/138559) there.

**Comment by meganrogge** [comment]
even when I add this directly to my settings, it doesn't show up (it used to)

```
"windows powershell": {
		"path": "${env:windir}\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
		"icon": "save"
	}
```

**Comment by Tyriar** [comment]
That works here:

![image](https://user-images.githubusercontent.com/2193314/145104087-e8d395b4-a5a0-4452-9ae3-5a798f218fef.png)

**Comment by meganrogge** [comment]
for me, it was stored at `C:\\Windows\\WindowsPowerShell\\v1.0\\powershell.exe` wonder if we should be checking there too

**Comment by Tyriar** [comment]
@TylerLeonhardt have you ever seen Windows PowerShell not under System32? That seems to be why it's not auto detected for @meganrogge 😕 

https://github.com/microsoft/vscode/blob/494cbbd02d67e87727ec885f98d19551aa33aad1/src/vs/base/node/powershell.ts#L230-L237

**Comment by meganrogge** [comment]
I moved it to the expected location and it's still not getting detected. What you see first in this gif is what happens when I provide the path directly. Then I remove that, and it doesn't get detected.
![recording - 2021-12-07T130610 997](https://user-images.githubusercontent.com/29464607/145106189-5b00f985-b0c9-4fa2-8df2-73788c7c4047.gif)

**Comment by TylerLeonhardt** [comment]
I have only ever seen Windows PowerShell under:
* System32 (normal)
* SysNative (64bit Windows PowerShell in 32bit VS Code on 64bit Windows)
* SysWOW64 (32bit Windows PowerShell in 64bit VS Code on 64bit Windows)

**Comment by meganrogge** [comment]
Windows PowerShell wasn't showing up for me because we don't pass in `includeDetectedProfiles` here so that's false. 

https://github.com/microsoft/vscode/blob/730e0da4ea122b04524f3cb99b3c790e3db22e61/src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts#L107

after passing true in there, 
![recording - 2021-12-07T190413 418](https://user-images.githubusercontent.com/29464607/145141172-8a68638e-39e6-450c-bfd5-b063c927d70c.gif)

**Comment by meganrogge** [comment]
I propose we don't include the detected profiles in the profile dropdown, but do include them in the quick pick for the `select default profile` and `create new with profile` actions

**Comment by meganrogge** [comment]
as you can see, the icon is correct with that adjustment

**Comment by meganrogge** [comment]
it does now in the quick pick in https://github.com/microsoft/vscode/pull/138628, but when the terminal gets created, it uses the default icon incorrectly

**Comment by meganrogge** [comment]
this is coming back as undefined

https://github.com/microsoft/vscode/blob/c55fd10ad867049438824985a6a9e82b897cf94b/src/vs/workbench/contrib/terminal/browser/terminalProfileResolverService.ts#L231

**Comment by meganrogge** [comment]
perhaps as a result of the platform config not getting updated due to the recent recursion fix?

**Comment by meganrogge** [comment]
confirmed that on my branch, the icon is always wrong for the default profile. works if you choose any other profile.

**Comment by meganrogge** [comment]
icon is only working for profiles with source because

https://github.com/microsoft/vscode/blob/338f69409bca5138f4ef51bc1a10bc2ce793f806/src/vs/platform/terminal/node/terminalProfiles.ts#L159-L171
