### ISSUE TITLE
My visual studio code closes frequently without any error message.

### ISSUE THREAD

**Issue by mdshabbir** [microsoft/vscode#138590]
<b>Performance Issue</b>

When I start my visual studio code after 1 min it will close automatically. I didn't understand why this is happening.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.74GB free)|
|Process Argv|--crash-reporter-id 0d443d1e-1aa9-475c-9238-72dd0a5c2839|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    82	  2028	code main
    0	    80	  5208	   shared-process
    0	    67	  6612	     ptyHost
    1	   122	  7212	   gpu-process
    0	   143	 10180	   window (method2.java - Untitled (Workspace) - Visual Studio Code)
    0	    69	  1036	     watcherServiceNSFW
    0	   257	  5524	     extensionHost
    0	    11	  9772	       c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-1.7.1\bin\cpptools.exe
    0	    10	 14952	         console-window-host (Windows internal process)
    0	   230	 12624	       "C:\Program Files\Java\jdk-17.0.1\bin\java" --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Djava.import.generatesMetadataFilesAtProjectRoot=false -Dfile.encoding=utf8 -DwatchParentProcess=false -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=c:\Users\Administrator\AppData\Roaming\Code\User\workspaceStorage\ab3123934cf75bfff9d5098746c2e116\redhat.java -jar c:\Users\Administrator\.vscode\extensions\redhat.java-1.1.0\server\plugins\org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar -configuration c:\Users\Administrator\AppData\Roaming\Code\User\globalStorage\redhat.java\1.1.0\config_win -data c:\Users\Administrator\AppData\Roaming\Code\User\workspaceStorage\ab3123934cf75bfff9d5098746c2e116\redhat.java\jdt_ws
    0	    11	  9376	         console-window-host (Windows internal process)
    0	    69	 13640	       "C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=5524
    0	     0	 11528	         
    0	    25	 10588	   crashpad-handler
    0	    38	 10828	   utility
    1	    78	 12392	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (method2.java - Untitled (Workspace) - Visual Studio Code)
|    Folder (My work space): 201 files
|      File types: jpg(53) java(29) class(29) html(18) css(15) pdf(9) png(5)
|                  js(4) json(3) jfif(3)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: java cppvsdbg;
```

</details>
<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
vscode-html-css|ecm|1.10.2
auto-close-tag|for|0.5.13
code-runner|for|0.11.6
better-cpp-syntax|jef|1.15.10
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5090
vsliveshare-audio|ms-|0.1.91
java|red|1.1.0
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.19.0
vscode-java-test|vsc|0.33.0
vscode-maven|vsc|0.34.1
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932cf:30408637
vscop804cf:30404767
vs360:30404995
vsrem710:30405998
vscexrecpromp3t2:30407763

```

</details>

**Comment by mjbvz** [comment]
Closing as more info needed to investigate
