### ISSUE TITLE
Intellisense suggestions/ auto imports do not work inside jsx tags

### ISSUE THREAD

**Issue by DenysPavlenko** [microsoft/vscode#138522]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- OS Version: Win10

Steps to Reproduce:

1. TabButton is imported, just want to autocomplete it. It works inside of the function:
![image](https://user-images.githubusercontent.com/37882647/144875951-6d26379e-5577-4308-9e04-6ce8ddb893b9.png)

2. The same procedure doesn't work inside the html tag or other component (Page in the example below)
![image](https://user-images.githubusercontent.com/37882647/144876146-3bf5c601-94f8-44b3-8ae2-addb286ae69f.png)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If so please share a minimal example that demonstrates the issue (as text, not screenshots)

**Comment by DenysPavlenko** [comment]
Yes, the issue is present in the latest VS Code insiders build
Here is an example. I am using react. As you can see I've imported ContentBox component for example. When I try to add it between <Page></Page> the intellisense or autocomplete doesn't work at all. I type Content.... and nothing happens accept for the popup appears with "Properties and Attributes" icon (You can see it on the screenshot from my fist message). 

import { useState } from 'react';
import { Page } from 'layouts';
import { ContentBox } from 'components/ContentBox';

const tabs = [
  { label: 'Add lp', value: 'add-lg' },
  { label: 'Stake EST', value: 'stake-est' },
];

export const SomePage = () => {
  const [tab, setTab] = useState(tabs[0].value);

  return (
    <Page>
      Content...
    </Page>
  );
};

**Comment by mjbvz** [comment]
@DenysPavlenko You need to write `<` inside of JSX to signal that you are starting a tag. Otherwise the content is treated a text and showing auto imports for it would be unexpected
