### ISSUE TITLE
Terminal - New Terminal or View - Terminal crashes all IDE.

### ISSUE THREAD

**Issue by OsvaldoFerrero** [microsoft/vscode#138547]
Issue Type: <b>Bug</b>

Goog morning,
Everytime I View Terminal or make New Terminal, the complete IDE freezes and restart it.
At the second attempt, It runs well, until I opens VSCode again.
I uninstalled all plugins and erase and install a clean copy of IDE, but still the issue,
Greetings from Argentina.

VS Code version: Code 1.62.3 (Universal) (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|4.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 94de364b-b839-406f-92af-b9ea99c14a82|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
vsena315cf:30406436
vscop804cf:30404767
vscop453:30404998
vsrem710:30405998
vscexrecpromp3t2:30407763

```

</details>

**Comment by deepak1556** [comment]
Can you follow the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues and attach the crash logs, thanks!
