### ISSUE TITLE
 this.text.substring is not a function

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#13850]
Issue Id: <b>320568e1-03ae-bee3-a437-9b40eb0ddc6f</b><br /><br />_Versions_ <br />\- 1.6.1<br />\-  e52fb0bc87e6f5c8f144e172639891d8d8c9aa55<br />_Stack_ <br />TypeError: this.text.substring is not a function<br />[/vs/base/browser/ui/highlightedlabel/highlightedLabel.ts#L79:52 (substring)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/browser/ui/highlightedlabel/highlightedLabel.ts#L79:52 %28substring%29)<br />[/vs/base/browser/ui/highlightedlabel/highlightedLabel.ts#L50:7 (render)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/browser/ui/highlightedlabel/highlightedLabel.ts#L50:7 %28render%29)<br />[/vs/workbench/parts/markers/browser/markersTreeViewer.ts#L143:27 (set)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/parts/markers/browser/markersTreeViewer.ts#L143:27 %28set%29)<br />[/vs/workbench/parts/markers/browser/markersTreeViewer.ts#L130:16 (renderMarkerElement)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/parts/markers/browser/markersTreeViewer.ts#L130:16 %28renderMarkerElement%29)<br />[/vs/base/parts/tree/browser/treeView.ts#L286:25 (renderElement)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/parts/tree/browser/treeView.ts#L286:25 %28renderElement%29)<br />[/vs/base/parts/tree/browser/treeView.ts#L1097:7 (render)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/parts/tree/browser/treeView.ts#L1097:7 %28render%29)<br />[/vs/base/parts/tree/browser/treeView.ts#L1082:7 (refreshViewItem)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/parts/tree/browser/treeView.ts#L1082:7 %28refreshViewItem%29)<br />[/vs/base/parts/tree/browser/treeViewModel.ts#L163:8 (onRefreshItem)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/parts/tree/browser/treeViewModel.ts#L163:8 %28onRefreshItem%29)<br />[/vs/base/parts/tree/browser/treeViewModel.ts#L138:7 (onRefreshItems)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/parts/tree/browser/treeViewModel.ts#L138:7 %28onRefreshItems%29)<br />[/vs/base/parts/tree/browser/treeView.ts#L947:7 (onRefreshItemSet)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/parts/tree/browser/treeView.ts#L947:7 %28onRefreshItemSet%29)<br />

**Comment by sandy081** [comment]
Looks like [Marker.message](https://github.com/microsoft/vscode/blob/master/src/vs/platform/markers/common/markers.ts#L54) is returning something which is not `string`. 

@jrieken I am not sure how this is happening, may be it is coming from the extension writers passing an object instead of string for message? If so, we might need a guard in the API?

**Comment by jrieken** [comment]
Hm... Unsure, we have a check for markers with a [message](https://github.com/Microsoft/vscode/blame/master/src/vs/platform/markers/common/markerService.ts#L185) and we [ignore](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/markers/common/markerService.ts#L172) them.

**Comment by jrieken** [comment]
Closing this as I am unsure about the timings - when we added the check, when these error occurred.
