### ISSUE TITLE
TypeScript Language Server not reporting errors (Insiders)

### ISSUE THREAD

**Issue by MikeMatusz** [microsoft/vscode#138528]
Issue Type: <b>Bug</b>

The TypeScript language server does not seem to be detecting/displaying any inline errors at all, and also seems not to be following imports for typing.  The same project does report errors in non-insiders VSCode.  No errors in the Output window, TS Server appears to start normally.  

VS Code version: Code - Insiders 1.63.0-insider (d09289a2b6dd0e56b2a264a8e9380685498e10d6, 2021-12-04T02:05:02.410Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (12.86GB free)|
|Process Argv|--crash-reporter-id 650c7985-3402-40af-bef4-fdd41b619439|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|13.0.0
multi-cursor-case-preserve|Car|1.0.5
vscode-eslint|dba|2.2.2
gitlens-insiders|eam|2021.12.504
prettier-vscode|esb|9.0.0
remotehub-insiders|Git|2021.12.30104
vscode-pull-request-github|Git|0.32.0
vscode-guid|hea|1.4.20
Angular2|joh|12.0.0
vscode-codemetrics|kis|1.24.0
git-graph|mhu|1.30.0
remote-containers|ms-|0.209.1
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.63.4
vscode-remote-extensionpack|ms-|0.21.0
vsliveshare|ms-|1.0.5090
vscodeintellicode|Vis|1.2.14
codetour|vsl|0.0.58

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
vsc_aa:30263845
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593:30376534
vsc1dst:30396469
pythonvs932:30404738
vscop804cf:30404767
vscop453:30404998
vsclayoutctrc:30405799
py55gd98:30408621
vscexrecpromp3t3:30407760

```

</details>

**Comment by MikeMatusz** [comment]
Here's an example of errors not being reported.

VSCode (errors underlined):
![image](https://user-images.githubusercontent.com/9934982/144889271-c187ca18-6e73-4c20-99f4-debfc64893ba.png)

VSCode Insiders (no errors):
![image](https://user-images.githubusercontent.com/9934982/144889301-b01ba195-412a-4f7d-aedd-a6b9cdb59b84.png)

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? 

Have you also checked your user settings?

**Comment by MikeMatusz** [comment]
Apologies for wasting anyone's time on this, someone committed the `typescript.validate.enable` setting set to false in the `.vscode/settings.json` file, and apparently I was the only one who had pulled latest, and also the only one using Insiders, leading to my confusion.  Thanks for pointing me in the right direction, and I'll make sure to check more thoroughly before posting next time.
