### ISSUE TITLE
Setting color not displayed in editor in VS code

### ISSUE THREAD

**Issue by moyscode** [microsoft/vscode#138569]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- OS Version: Windows 10

Steps to Reproduce: I have done anything special. I just used  'npx create-react-app my-app --template typescript' to create the react app. Then the issue is there.

Issue:-
I am trying to customize the color of HTML tags in react (.tsx files). So, I included the code below in `settings.json` file.

```
"editor.tokenColorCustomizations": {    
    "textMateRules": [
      // TextMate grammars tokenization settings
      {
        "name": "JSX tags",
        "scope": [
          "entity.name.tag", // HTML tags (in JSX)
          "entity.name.tag.html", // JSX Component tags
          "meta.tag",
          "meta.jsx"
        ],
        "settings": {
          "foreground": "#18da32"
        }
      }
    ]
  },

```
However, even after the settings is applied, the color does not change (the color should be like so 
![image](https://user-images.githubusercontent.com/92194668/144962330-2bcaab54-a5bd-40c3-8b2e-43c2c1c9c9fa.png)
)

What is being displayed is a below 
![image](https://user-images.githubusercontent.com/92194668/144962376-fe262a0d-d947-448c-ad69-73e5cddd0086.png)

However, when I use the developer tools it shows the right Hex code but the color displayed is wrong!
![image](https://user-images.githubusercontent.com/92194668/144962442-f22d5462-83d0-473a-9f79-b529e0142839.png)

The other tag is displayed correctly (the dark orange color)
![image](https://user-images.githubusercontent.com/92194668/144962508-67f25fdd-cc44-44ea-8eb4-8b9a07e5d7ba.png)

**Comment by Dromantor** [comment]
I have a similar issue. I've customized syntax highlighting to easily distinguish between local and global vars, struct members, etc.
This doesn't work anymore. "textMateRules" is completely ignored as it seems. Simple rules (like "comments", "variables" besides "textMateRules") still work.

**Comment by aeschli** [comment]
In the first screenshot, the cursor is after `App` and the token happens to be a whitespace character after the token. The title of the hover shows that: `.  1 char`. Because its a whitespace no color is seen.
If you set the cursor on `App` you see the scopes and you see on the last line that there's a coloring rule for `support.class` that wins.
![image](https://user-images.githubusercontent.com/6461412/146543898-02160764-3fa4-42f1-b709-6faf3d1e1a14.png)

A solution would be to add a coloring rule for match `support.class` after `entity.name.tag`: `entity.name.tag support.class`
```
  "editor.tokenColorCustomizations": {    
    "textMateRules": [
      // TextMate grammars tokenization settings
      {
        "name": "JSX tags",
        "scope": [
          "entity.name.tag", // HTML tags (in JSX)
          "entity.name.tag support.class", // HTML tags (in JSX)
          "entity.name.tag.html", // JSX Component tags
          "meta.tag",
          "meta.jsx"
        ],
        "settings": {
          "foreground": "#18da32"
        }
      }
    ]
  },
```
![image](https://user-images.githubusercontent.com/6461412/146544897-fa157d66-79db-42a9-a7c8-b2bb8a3ab7eb.png)

**Comment by aeschli** [comment]
@Dromantor If you use the `Developer: Inspect editor tokens and scopes` you can see where the color comes from. I suspect it's from the semantic highlighting which goes on top of syntax highlighting.
If that doesn't explain what you are seeing, can you file a new issue that contains the sample code?

**Comment by moyscode** [comment]
@aeschli Thanks for the solution. It worked (i have put `support.class.component` instead of just `support.class`). When I checked with developer tools, I was selecting ass the letter ('App') and thought that was the the right selection. I now know that I have to put the cursor in the middle of the tag to get the correct reference. Thanks again.
