### ISSUE TITLE
The menu disappears after flashing when right click on jupyter markdown cell. 

### ISSUE THREAD

**Issue by wingforth** [microsoft/vscode#138671]
Issue Type: <b>Bug</b>

The jupyter extension is installed when installing python. 
When the Jupyter Markdown cell is in the editing state, click the right mouse button, and the pop-up menu will automatically disappear immediately. When stop editing cell, it works fine. 

Extension version: 2021.10.1101450599
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.64GB free)|
|Process Argv|--crash-reporter-id ff469fb9-9934-440a-8b27-17b057d8e8d1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30408636
vscop804:30404766
vscop453:30404998
vsrem710:30405998

```

</details>

**Comment by rchiodo** [comment]
This repros for me too. Context menu in edit mode for a markdown cell doesn't stay open.

**Comment by wingforth** [comment]
This seems to be a common situation at present. Will it be regarded as a bug and fixed in the future? As sometimes this situation confuses me.
