### ISSUE TITLE
Command links in notebook output not working

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#138666]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63-insider
- OS Version: Edge on Windows (vscode.dev)

Steps to Reproduce:

1. Open a github issues notebook
2. Don't sign in and run a relatively complex query, get the message about needing to sign in due to the api rate limit
3. 🐛 clicking on the link to sign in does nothing
![image](https://user-images.githubusercontent.com/30305945/145263246-c891f5fb-f9f2-4695-b973-9ffdb931bae8.png)

fyi @jrieken since this impacts the getting started experience with GitHub Issues notebooks--could the extension request authentication with `createIfNone` when we hit this case?

**Comment by jrieken** [comment]
> could the extension request authentication with createIfNone when we hit this case?

I believe the extension cannot know that we hit this case. I believe it's a bug that command links don't work, waiting for @rebornix to confirm tho

**Comment by mjbvz** [comment]
@rebornix  Was this fixed by your commit? Should we only enable command links in trusted workspaces?
