### ISSUE TITLE
`const { xor } = require("cypress/types/lodash");` added to top of file randomly

### ISSUE THREAD

**Issue by ab-gord** [microsoft/vscode#138624]
- Issue Type: `Bug`
- Extension Name: `typescript-language-features`
- Extension Version: `1.0.0`
- OS Version: `Darwin x64 19.6.0`
- VS Code version: `1.62.3`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 42,
		"activateCallTime": 48,
		"activateResolvedTime": 109,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "vscode.typescript-language-features",
				"_lower": "vscode.typescript-language-features"
			},
			"activationEvent": "onLanguage:javascript"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

Hi there. Once about every 100 file saves, VSCode will write

const { xor } = require("cypress/types/lodash");

To the top of a JS file when I save it.

Here are my running extensions. This was happening before I installed Prettier. 

![Screen Shot 2021-12-07 at 3 52 09 PM](https://user-images.githubusercontent.com/87447820/145123747-2e67b1fa-8e3e-443f-be5a-43b1c4324431.png)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
