### ISSUE TITLE
Consider moving quickinput & custom hover into `vs/platform`

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#138617]
I'm finding myself getting burned by the quickinput code being in `vs/base` because things like the custom hover service and widget are not in `vs/base` but in `vs/workbench` and I can't access them. I need to access these so I can render icons in the tooltips correctly.

I talked to @jrieken and he feels like `vs/base` isn't the right place for quickinput and the custom hover and that `vs/editor` would be better for these.

Thoughts?

**Comment by Tyriar** [comment]
Do you mean moving vs/workbench into vs/editor? Moving vs/base into vs/editor would just make the hover more restrictive.

**Comment by TylerLeonhardt** [comment]
@Tyriar yeah move what's in `vs/workbench` into `vs/editor` and then I would move quickpick from `vs/base` into `vs/editor` so a mix of making quick pick more restrictive and making hover less restrictive.

**Comment by Tyriar** [comment]
@TylerLeonhardt can you inject hover service delegates here?

https://github.com/microsoft/vscode/blob/e29e1f908a435cc8acf2563c10b24dbc20f83b98/src/vs/workbench/services/quickinput/browser/quickInputService.ts#L42-L47

**Comment by TylerLeonhardt** [comment]
@Tyriar right I can do that but then Monaco wouldn't get this feature.

Is there a reason why the custom hover can't be in Monaco?

**Comment by Tyriar** [comment]
A separate hover implementation exists for monaco (editor/contrib/hover) which depends upon base. What do you mean monaco wouldn't get the feature as you would be passing whatever you need to that controller?

**Comment by TylerLeonhardt** [comment]
Ah. I guess then I would expose the hover delegate there and here:
https://github.com/microsoft/vscode/blob/2fc1dac22902923e6b97f43694a8aa4e0db3fcce/src/vs/editor/standalone/browser/quickInput/standaloneQuickInputServiceImpl.ts#L54

for Monaco and then use monaco's hover instead of vscode's hover.

What's the reason behind having 2 hovers instead of one that exists in `vs/editor`?

**Comment by Tyriar** [comment]
The editor one is heavily tied to displaying language data, the workbench one is generalized.

I see the workbench hover doesn't depend on anything in workbench, so as long as it can use IConfigurationService from platform which it will probably depend on soon I don't have an issue with moving it into the editor layer. I haven't really worked there so don't know the layering rules though, I believe I got an issue before saying avoid depending on editor from the terminal though.

**Comment by Tyriar** [comment]
Maybe moving HoverService to platform is the way to go. Not sure you should be moving the base quickInput into editor or platform though as base is just meant to contain simple base widgets and be built upon in other layers.

**Comment by TylerLeonhardt** [comment]
Maybe we need @alexdima to chime in here.

**Comment by Tyriar** [comment]
@TylerLeonhardt I think moving HoverService to platform should work since editor can depend on platform, feel free to work on this and send me a PR if it looks like it solves the problem.

**Comment by alexdima** [comment]
:+1: sorry I forgot to answer here. I also don't have any concerns with moving things around.

**Comment by TylerLeonhardt** [comment]
quick input is in platform now... so I don't think we need this anymore
