### ISSUE TITLE
The VS Code is not showing existing files opened in editor

### ISSUE THREAD

**Issue by nirmalsinghoo7** [microsoft/vscode#138663]
Issue Type: <b>Bug</b>

On Windows, When I close the VS Code, it closed without any warning for unsaved files.
But on Mac, it warned for unsaved files and never open recently opened files.

VS Code version: Code 1.62.2 (Universal) (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.68GB free)|
|Process Argv|--crash-reporter-id 5d0a7784-545f-404e-a53d-5d90d6896190|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.7.2
indented-block-highlighting|byi|1.0.7
bracket-pair-colorizer|Coe|1.0.61
macos-modern-theme|dav|2.1.9
es7-react-js-snippets|dsz|3.1.1
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
vscode-firefox-debug|fir|2.9.5
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
vscode-gutter-preview|kis|0.29.0
kite|kit|0.147.0
code-beautifier|mic|2.3.3
python|ms-|2021.11.1422169775
cpptools|ms-|1.7.1
color-highlight|nau|2.5.0
format-html-in-php|rif|1.7.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
code-spell-checker|str|2.0.13
highlight-matching-tag|vin|0.10.1
vscode-icons|vsc|11.8.0
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
vsena315cf:30406436
pythonvs932cf:30408637
vscop804cf:30404767
vs360:30404995
vsrem710cf:30405999
vscexrecpromp3t2:30407763

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

What is your value for `files.hotExit` setting?
Afaik there is difference in default behavior between OSes.
You can try different values depending on what is expected result, as from report it's unclear which one is desired.

**Comment by nirmalsinghoo7** [comment]
> /needsMoreInfo
> 
> What is your value for `files.hotExit` setting? Afaik there is difference in default behavior between OSes. You can try different values depending on what is expected result, as from report it's unclear which one is desired.

It's onExit - https://prnt.sc/22eico2

How to edit settings.json? I can't find the file path on Mac
