### ISSUE TITLE
Handle links with `href=blob:` in WebView

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode#138604]
Is there a way to handle links with `href=blob:...` in WebView, e.g. from a WebView created from https://github.com/REditorSupport/vscode-R/issues/904 where plotly widget create a blob url to download a file.

https://github.com/microsoft/vscode/issues/98101 and https://github.com/microsoft/vscode/pull/98690 seem to support it, but I don't find a public API or documentation about how a general WebView could be enabled to handle it.

**Comment by tamuratak** [comment]
When we execute the following snippet in WebView,  a file download dialog pops up:

```ts
    const blob = new Blob(['abc'], { type: 'text/plain'});
    const url = URL.createObjectURL(blob);
    const dom = document.createElement('a');
    dom.href = url;
    dom.download = 't.txt';
    dom.click();
```

![2021-12-09 7 29 41](https://user-images.githubusercontent.com/10665499/145301144-7c42a3ad-b30b-4b39-a992-8542c4ec1c8d.png)

- https://github.com/tamuratak/vscode-extension-samples/tree/webview_blob/webview-sample

@mjbvz  is this an intended behavior? Or is it bypassing some restrictions unintentionally?
