### ISSUE TITLE
Disable mouse interaction in terminal

### ISSUE THREAD

**Issue by OldStarchy** [microsoft/vscode#138627]
Please add an option to disable passing mouse events through to terminal programs.

This has been bothering me for a while now; I'm used to being able to select things in the terminal with left-click and copy them with right-click.

Currently _sometimes_ when I'm editing a file with vim in the terminal the mouse clicks are passed through to vim. This means that

* when I try to select text it puts vim into visual mode and moves the cursor around
* when I right-click to copy, weird stuff happens. I honestly don't know what it's doing (I'm not an expert in vim but it looks like it's pasting from some unknown buffer (it's not the default vim buffer that I can use with `yy` or `dd`))

I'm sure that in some situations having the mouse events go through the terminal to whatever end program is useful but unfortunately it's just getting in my way.

I've searched the vscode docs and the issue tracker to see if there's a way to prevent mouse events from going into the terminal but I haven't found anything.

From testing, the scenario this happens is only when I've got a workspace open in WSL, open a terminal and SSH into a remote host, then `docker exec -it container bash`, then `vim some-file`. It doesn't happen for vim running on the remote host (outside the container) or my local WSL vim, so its probably some vim setting that's different in the container, but I'd like to disable it across the board as I'm not always going to be able to modify remote host settings.

**Comment by Tyriar** [comment]
We respect vim's request when it asks for mouse events, you should disable mouse support in vim if it bothers you. It probably doesn't happen in your remote because vim doesn't have mouse events enabled. Additionally, you can still use native terminal selection by holding shift (linux and windows) or alt (on mac if `terminal.integrated.macOptionClickForcesSelection` is enabled).
