### ISSUE TITLE
Bad view of code when new file is created

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#138681]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:
When creating new file in Nawigator by contex menu, eg. new.py and adding code by ctr+v then code is "faken" around indentation. The indentation is narrow like no indentation and other issues are around.
After close tab with new.py and reopen then view is ok.
I reported this error more like 2 years ago and still exist, not sure where.. PTV, debugpy, notebook, jupyter.. 
And I'm surprised that this still exist.

**Comment by Lemmingh** [comment]
/gifPlease

A screen recording would be helpful.

---

> 2 years ago

Out of curiosity, which issue?

<https://github.com/microsoft/vscode/issues?q=is%3Aissue+author%3AManPython>

**Comment by Lemmingh** [comment]
There might be something bizarre with your indentation settings `editor.detectIndentation` and `editor.tabSize`.

**Comment by ManPython** [comment]
> There might be something bizarre with your indentation settings `editor.detectIndentation` and `editor.tabSize`.

Well, when change this to false, the opened file looks like 1st image.
`"editor.detectIndentation": true`
Turning true like 2nd. But steps to reproduce showing that this settings is not stable.

**Comment by ManPython** [comment]
Insert space is true, and tab size 1.
Don't know where is problem.

**Comment by Lemmingh** [comment]
So, you have

```json
{
    "editor.tabSize": 1,
    "editor.insertSpaces": true,
    "editor.detectIndentation": true
}
```

The descriptions of these settings can answer your question.

When you open an empty editor (empty file in your case), `tabSize` and `insertSpaces` are used.

When you open a file with content, `detectIndentation` asks the editor to check the file content to overwrite them.

**Comment by ManPython** [comment]
So what setting should be to be compatible here? I think that I never changed here nothing from ears when I start to use VSC.

**Comment by Lemmingh** [comment]
I'm afraid I don't understand you. Things work as expected, from what I can tell. Perhaps you changed your settings accidentally.

<https://code.visualstudio.com/docs/editor/codebasics#_indentation>
