### ISSUE TITLE
View: focus left editor group command does not work for Jupyter notebooks

### ISSUE THREAD

**Issue by natwille1** [microsoft/vscode#138661]
## Environment data

-   VS Code version: 1.62.3
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Anaconda3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

Command for view: focus left editor should switch from a group of editors open on the right of a split screen to the left of the split screen

## Actual behaviour

Command does nothing

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open VSCode and 2 jupyter notebooks
2. Split screen so there are two groups of editors 
3. Command to switch from the editor group on the left to the right works
4. Command for the opposite direction does nothing 

Command definition:
Switch to Left group
{
  "key": "ctrl+h",
  "command": "workbench.action.focusLeftGroup",
  "when": "editorTextFocus && vim.active && vim.mode != 'Insert'"
}
Switch to Right group
{
  "key": "ctrl+l",
  "command": "workbench.action.focusRightGroup",
  "when": "editorTextFocus && vim.active && vim.mode != 'Insert'"
}

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by mjbvz** [comment]
I just tested this. I believe the commands work, however the example keybindings are setup to only be enabled when a text editor is focused (`editorTextFocus`). For notebooks, this means the commands will only be enabled when you are editing a code cell. If you clear the focus to instead have the notebook document focused, then `editorTextFocus` is no longer true so the keybindings never apply

I suggest tweaking the keybindings to also be enabled when `notebookEditorFocused` is true

Let me know if this analysis seems incorrect

**Comment by mjbvz** [comment]
Have you tried without vim? I tested using the keybindings without any `when` clause and they worked fine

**Comment by natwille1** [comment]
Hey sorry for late response, yea removing the "when" clause worked actually. However, now I'm not able to switch focus to the File Explorer when pressing "ctrl+h" from the editor next to the File Explorer..
