### ISSUE TITLE
SCM input history needs better storage management

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#138605]
Currently:

- Empty history is stored to storage anyway
- Repositories are saved forever and ever

**Comment by joaomoreno** [comment]
Resolution:

- If history is just `['']`, we shouldn't store it at all
- Entries are now saved with a timestamp, and garbage collected after 30 days
- Entries are migrated on the first time an SCMInput is instantiated

cc @sandy081 @meganrogge

**Comment by joaomoreno** [comment]
Best verification would be a code review.

**Comment by joaomoreno** [comment]
Pushing one more commit, from standup feedback:

- Change storage target to `MACHINE`, making sure this state is not synced at all
- Make sure to skip writing to storage if history doesn't change at all

**Comment by lszomoru** [comment]
Reviewed the code, added the tag.
