### ISSUE TITLE
editor suggestions interface, variables, and properties are mixed up

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#138677]
Does this issue occur when all extensions are disabled? Yes

- VS Code Version: 1.62.3 (Insiders 1.63.0)
- OS Version: macOS Monterey 12.0.1

Steps to Reproduce:

1. Copy this code into your editor:
```
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>

<body>
	<button type="button" onclick="">Button</button>
</body>

</html>
```
2. Set `"editor.suggest.showInterfaces": false`
3. Open the suggestions on the `onclick=""` and notice the interfaces still show up
<img width="1792" alt="Screen Shot 2021-12-08 at 21 47 29" src="https://user-images.githubusercontent.com/22457463/145289740-a9ceb30e-aeac-406d-b6b3-d75c3c29f9a2.png">

4. Set `"editor.suggest.showInterfaces": true` and `"editor.suggest.showVariables": false`
5. Open the suggestions on the `onclick=""` and notice the interfaces are now gone
<img width="1792" alt="Screen Shot 2021-12-08 at 21 48 20" src="https://user-images.githubusercontent.com/22457463/145289888-32df9905-10f7-48f0-9cb0-5c7feb4f7a02.png">

Also note:
- Variables are shown/hidden with the `editor.suggest.showProperties` instead of the `editor.suggest.showVariables`
<img width="1792" alt="Screen Shot 2021-12-08 at 21 56 09" src="https://user-images.githubusercontent.com/22457463/145291259-4d428dc5-db4a-44d8-b057-d99be5a85db8.png">
- The `$` and the `name` variables are always suggested, even if they aren't part of the document

**Comment by jrieken** [comment]
It depends on the extension generating the suggestion (JS/TS or HTML, I am unsure)Then there is also some TS specifics to be considered, the AbortController is typed with an interface and ctor-variable-function.

**Comment by aeschli** [comment]
The TypeScript service reports the `AbortController` as a variable. That's related to how the typing were designed
```
declare var AbortController: {
    prototype: AbortController;
    new(): AbortController;
};

```

**Comment by aeschli** [comment]
> Variables are shown/hidden with the editor.suggest.showProperties instead of the editor.suggest.showVariables

I fixed that with 2858dd87e7d400cdefeb470073e0ec66f39d28b2

For the `AbortController` I suggest we file an issue against TypeScript.

**Comment by andrecasal** [comment]
Thanks @aeschli! 🙌

If you point me in the TypeScript repo's direction, I'll file the issue. Is it [this one](https://github.com/microsoft/vscode-typescript-next)?

**Comment by aeschli** [comment]
Thanks that would be great: It's https://github.com/microsoft/TypeScript/issues

**Comment by andrecasal** [comment]
For the TS service, anything in the global scope, including web api functions like AbortController() are considered variables, so they [closed](https://github.com/microsoft/TypeScript/issues/47086#issuecomment-991960975) the issue.

Should VS Code be responsible for correctly annotating Web API functions or should the TS service?
