### ISSUE TITLE
VS Code confuses parameter type as parameter identifier in certain scenarios.

### ISSUE THREAD

**Issue by sbeve72** [microsoft/vscode#138695]
Issue Type: <b>Bug</b>

This is a very annoying issue with VSC that I found out even Vim gets right. In VSC, when I have a function declaration like
```c
double atof2(const char[]);
```
VSC assumes that `char` is the paramter's identifier instead of the type. This shouldn't be very hard for VSC since it char is not a valid idenitifer anyway since it's a keyword but for some reason VSC is unable to understand that.

Vim gets this right, Discord's markdown feature gets this right and CLion gets this right and I'd really like if VSC did too.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:16:45.441Z)
OS version: Linux x64 5.11.0-41-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8300 CPU @ 3.70GHz (4 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.50GB (5.29GB free)|
|Process Argv|--crash-reporter-id e295b45c-908c-41c9-a5f0-92489d35bfb2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.0.0
better-cpp-syntax|jef|1.15.10
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cmake|twx|0.0.17
vim|vsc|1.21.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30408636
vscop804:30404766
vs360cf:30404996
vsrem710:30405998
vscexrecpromp3t3:30407764

```

</details>

**Comment by sbeve72** [comment]
same happens with
```c
void somefun(unsigned int);
```

where `unsigned int` is the type of the parameter but VSC thinks `int` is the indentifier and highlights it with light blue (as opposed to dark blue for keywords)

**Comment by sbeve72** [comment]
@mjbvz The issue persists even after disabling the extension or completely uninstalling it. I don't know why it would be the cause of the problem.

**Comment by yume-chan** [comment]
Looks very similar to jeff-hykin/better-cpp-syntax#200.

https://github.com/jeff-hykin/better-cpp-syntax/commit/ad31cfa8d06699226827ae126f2366e08e88be26 only fixed its cpp grammar, and indeed the issue doesn't happen when set to cpp mode.

![image](https://user-images.githubusercontent.com/1330321/145438839-d3f576af-818d-41e2-8cac-bf0e41f11853.png)
(c)

![image](https://user-images.githubusercontent.com/1330321/145438881-eaab1861-d893-4b25-91a2-fa4f9ed131b6.png)
(cpp)

**Comment by sbeve72** [comment]
Can you reproduce the problem without the extensions installed? The maintainer above said that this issue is caused by the extension but I don't believe so since the issue persists even with the extensions disabled/uninstalled.

**Comment by yume-chan** [comment]
The issue is not from the C/C++ extension, but the built-in C/C++ Language Basics extension, which uses TextMate grammar from https://github.com/jeff-hykin/better-cpp-syntax. It's not in Visual Studio Code's scope anyway.

**Comment by sbeve72** [comment]
> The issue is not from the C/C++ extension, but the built-in C/C++ Language Basics extension, which uses TextMate grammar from https://github.com/jeff-hykin/better-cpp-syntax. It's not in Visual Studio Code's scope anyway.
@yume-chan 

Sorry I don't understand, do you mean to say that VSC internally uses that extension (better cpp syntax) for syntax highlighting?

**Comment by yume-chan** [comment]
Yes
