### ISSUE TITLE
remove menu tooltip

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#138653]
hi, how can we extension developers make contribution to custom menu of tool tip
eg: change the tool tip to other string
![image](https://user-images.githubusercontent.com/1876302/145230422-eb2c5689-1790-4333-891e-8a03e38c73ba.png)

**Comment by sbatten** [comment]
I did not realize that the tooltip was even showing for some actions. Native menus do not do this, so I would think this is a bug that should be fixed by removing tooltips from custom menus altogether.

**Comment by heartacker** [comment]
you mean that vscode should delete this tooltip?
NO, That is a useful and it could make the short menu better when hover providing supplementary instruction;

GREAT contribute-point rather than deleting them

**Comment by sbatten** [comment]
sorry @heartacker we attempt to function like native menus since we use those across platforms, for that reason, no tooltips in custom menus

**Comment by heartacker** [comment]
https://github.com/microsoft/vscode/issues/138460 lack
