### ISSUE TITLE
No definition found

### ISSUE THREAD

**Issue by AlexiaAlarza** [microsoft/vscode#138639]
Issue Type: <b>Bug</b>

Bonjour,

je suis sous mac et j'utilise VSC. Depuis quelques semaines je n'arrive plus à naviguer entre les composants il m'indique "no definition found". Sauriez-vous d'où cela pourrait venir ? 

Merci par avance,
Alexia

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv|--crash-reporter-id 8430c310-d58b-455d-8f0f-01b6281a4a0e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
ng-template|Ang|13.0.0
path-intellisense|chr|2.6.0
bracket-pair-colorizer-2|Coe|0.2.1
angular-schematics|cyr|5.1.1
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
auto-rename-tag|for|0.1.9
angular-essentials|joh|12.0.0
Angular2|joh|12.0.0
vscode-peacock|joh|4.0.0
lucca-lokalise|luc|0.0.2
Angular-BeastCode|Mik|10.0.3
vscode-language-pack-fr|MS-|1.62.4
csharp|ms-|1.23.17
vsliveshare|ms-|1.0.5196
debugger-for-edge|msj|1.0.15
gremlins|nho|0.26.0
angular-console|nrw|17.12.4
material-icon-theme|PKi|4.11.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
vsena315cf:30406436
pythonvs932:30408636
vscop804cf:30404767
vscop940:30404999
vsrem710:30405998
vscexrecpromp3t2:30407763

```

</details>

**Comment by IllusionMH** [comment]
Please provide problem description in English and code samples/repo that reproduce problem.

**Comment by AlexiaAlarza** [comment]
Hi, since some days i can't jump between components by using cmd+click, just on some project not all. 
I think this bug is due to the extension Angular language Service because if disabled experimental-ivy it works but with some errors on pipes.
<img width="1036" alt="Capture d’écran 2021-12-09 à 10 44 31" src="https://user-images.githubusercontent.com/77682210/145372578-c05dd987-cfe0-4b1b-85e3-db1d48c70774.png">

**Comment by mjbvz** [comment]
Please file this against the angular extension
