### ISSUE TITLE
Background color is wrong when terminals are created in editor area via command

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#138601]
Repro is to run create new terminal in editor area command:

![image](https://user-images.githubusercontent.com/2193314/145053160-4c613c8a-cb06-42b9-ba58-3561a13dc16f.png)

**Comment by Tyriar** [comment]
Reverted in 8605d7aeff46622320a70e577d0eba5c9b6557d9

**Comment by meganrogge** [comment]
to verify, install the [sapphire theme](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiEqYmQ7OP0AhXKQc0KHelEAbQQFnoECAUQAQ&url=https%3A%2F%2Fmarketplace.visualstudio.com%2Fitems%3FitemName%3DTyriar.theme-sapphire&usg=AOvVaw3L2tA0zyy3dsDCZW0_Nown) (it shows in that one specifically).
run create new terminal in the editor area command. it should not look like the above.

**Comment by meganrogge** [comment]
merged into the release branch
