### ISSUE TITLE
After renaming file, getting error on compare

### ISSUE THREAD

**Issue by dfdumaresq** [microsoft/vscode#138618]
Issue Type: <b>Bug</b>

1. Open two files in the editor (FileA, FileB)
2. Rename FileA to FileA1
3. Compare FileA1 with FileB
4. Note error: 
Unable to open 'CMTN_UPDATE-AB-2560.sql ↔ COTR_UPDATE-2560.sql': Unable to read file '/scripts/CMTN_UPDATE-AB-2560.sql' (Error: Unable to resolve nonexistent file '/scripts/CMTN_UPDATE-AB-2560.sql').

VS Code version: Code 1.62.3 (Universal) (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id 161e5da9-f592-4143-baa2-0a9d01a1bfab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
redis|Dun|1.4.0
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
LogFileHighlighter|emi|2.13.0
vscode-nupkg|eri|1.0.1
prettier-vscode|esb|9.0.0
vscode-firefox-debug|fir|2.9.5
text-transform|flo|0.1.0
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
docker-explorer|for|0.1.7
openssl-configuration-file|gee|0.0.1
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.5.0
vscode-nuget-package-manager|jmr|1.1.6
intellij-idea-keybindings|k--|1.5.0
dotnet-core-essentials|Kis|0.0.8
git-graph|mhu|1.30.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.17
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.11
js-debug-nightly|ms-|2021.11.1217
sublime-keybindings|ms-|4.0.10
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.13.0
vsnotes|pat|0.7.1
material-icon-theme|PKi|4.11.0
qub-xml-vscode|qub|1.2.8
java|red|1.1.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.2
vs-code-prettier-eslint|rve|3.0.4
preview-vscode|sea|2.2.5
vscode-workspace-explorer|tom|1.5.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.37.0
vscode-java-pack|vsc|0.19.0
vscode-maven|vsc|0.34.1
gitblame|wad|8.1.0
ReactSnippets|xab|2.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30408636
vscop804:30404766
vscop940:30404999
vsrem710:30405998
vscexrecpromp3t3:30407764

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by JacksonKearl** [comment]
I can't reproduce this myself, does it reproduce all of the time for your or only sporadically? It'd help if you could include a screen recording of the isssue.

\gifPlease
