### ISSUE TITLE
macOS: code command line generates icon in "recently opened" section of dock 

### ISSUE THREAD

**Issue by ChaseMalik** [microsoft/vscode#138691]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.0
- OS Version: macOS Monterey 12.0.1

Steps to Reproduce:

1. Open vscode from command line - `code`
2. Run `code` from command line again

Actual: After the first execution of `code` the existing vscode icon in the dock is 'active' (bounces and has dot beneath it) After second execution, a new vscode icon is added to the 'Recently opened' section of the dock. It bounces, but the dot indicating it is currently open goes away (and remains with the icon from part 1).

Expected: Calls to code while vscode is already open should not create a new icon in the recently opened section.

A very similar bug was previously tracked as #60579 and closed by #131213, but the issue still partially repros. (Only one icon is ever added to the 'recently opened' section now)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/132569

Underlying issue is related to the specific usage of `open` command and macOS behavior related to it.
