### ISSUE TITLE
[0.10.4] editor.insertSpaces "auto" not being detected

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#1386]
I have my setting set to `auto` which worked in `0.10.3`. After I upgraded to the insider release, it's not being detected automatically, it always inserts spaces.

**Comment by SamVerschueren** [comment]
Tagging some people as I guess it should be fixed before final december release.

// @bpasero @jrieken

**Comment by bpasero** [comment]
@SamVerschueren I think we changed the defaults (see https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/latest.md#changed-defaults-and-key-bindings) and so unless you explicitly configured it, it would change.

@alexandrudima fyi

**Comment by SamVerschueren** [comment]
I configured it to `auto`, but the it does not work, it keeps inserting spaces unless I explicitly set it to `false`.

**Comment by SamVerschueren** [comment]
Did a screencapture.

My `gulpfile.js` uses tabs, so with `editor.insertSpaces` set to `auto`, it should insert tabs instead of spaces. As you can see in the screencapture, when I change the setting from `false` to `auto`, it is not detected.

![spaces](https://cloud.githubusercontent.com/assets/1913805/11864301/af428714-a49b-11e5-97c0-f928e587684b.gif)

**Comment by egamma** [comment]
Changed milestone to Dec and we will discuss in our bug review today.

**Comment by SamVerschueren** [comment]
Thanks for the quick response!

**Comment by alexandrudima** [comment]
@SamVerschueren Since "auto" looks at the file to detect the setting, can you please also share the file with us (if the file is too short or has too few hints we fall back to insertSpaces: true).

**Comment by SamVerschueren** [comment]
@alexandrudima 

```js
'use strict';

/**
 * Tasks that will zip all the files so that the zip file can be deployed to
 * AWS Lambda.
 *
 * @author Sam Verschueren      <sam.verschueren@gmail.com>
 * @since  02 Sep. 2015
 */

// module dependencies
var fs = require('fs');
var path = require('path');
var gulp = require('gulp');
var install = require('gulp-install');
var zip = require('gulp-zip');
var strip = require('gulp-strip-comments');
var removeEmptyLines = require('gulp-remove-empty-lines');
var del = require('del');
var pkg = require('./package.json');

gulp.task('clean', ['zip'], function () {
	return del('.temp');
});

gulp.task('rmaws', ['copyAndInstall'], function () {
	return del('.temp/node_modules/aws-sdk');
});

gulp.task('copyAndInstall', function () {
	var files = ['package.json'].concat(pkg.files);

	if (pkg.files === undefined) {
		files = ['./**', '!./**/*.md', '!gulpfile.js', '!./{dist,dist/**}', '!./{test,test/**}', '!./{node_modules,node_modules/**}'];
	} else {
		files = files.map(function (file) {
			try {
				if (fs.statSync(path.join(__dirname, file)).isDirectory()) {
					return path.join(file, '**/*');
				}
			} catch (err) {
				// do nothing
			}

			return file;
		});
	}

	return gulp.src(files, {base: '.'})
		.pipe(strip())
		.pipe(removeEmptyLines())
		.pipe(gulp.dest('.temp'))
		.pipe(install({production: true}));
});

gulp.task('zip', ['copyAndInstall', 'rmaws'], function () {
	return gulp.src('.temp/**')
		.pipe(zip('build.zip'))
		.pipe(gulp.dest('dist'));
});

gulp.task('build', ['copyAndInstall', 'rmaws', 'zip', 'clean']);
gulp.task('default', ['build']);
```

> Note: It are all tabs, GitHub just renders them as spaces.

**Comment by alexandrudima** [comment]
@SamVerschueren Thank you for finding this!! :love:

It was a nasty regression introduced with d60cc73d82e803184c996da11bbd54d8f4eddb57 where the guessing code was always guessing it should `insertSpaces`

**Comment by SamVerschueren** [comment]
Thanks for expressing your love to me :).

On a more serious note, thanks for fixing it before the final release!
