### ISSUE TITLE
unhide task bar

### ISSUE THREAD

**Issue by menatara** [microsoft/vscode#138697]
Issue Type: <b>Performance Issue</b>

unable to unhide task bar

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (7.39GB free)|
|Process Argv|--crash-reporter-id 159cfd27-40a7-4b7f-9256-cfaabce70413|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   102	 15656	code main
    0	    26	  6028	   crashpad-handler
    1	    82	  7360	   issue-reporter
    0	    91	 13280	   shared-process
    0	    68	 22696	     ptyHost
    0	   154	 20848	   extensionHost
    0	    73	 22108	     "C:\Users\menatara\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\menatara\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=20848
    0	   141	 24516	   gpu-process
    0	    41	 30372	   utility-network-service
    0	   167	 30712	   window (Settings - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.0
bracket-pair-colorizer|Coe|1.0.61
codespaces|Git|1.4.1
vscode-pull-request-github|Git|0.32.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.12.0
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.3
remote-ssh|ms-|0.68.0
remote-ssh-edit|ms-|0.68.0
remote-wsl|ms-|0.63.4
vscode-remote-extensionpack|ms-|0.21.0
vetur|oct|0.35.0

</details>

**Comment by sbatten** [comment]
Can you explain what you mean by task bar?
