### ISSUE TITLE
`authentication.getSession` with `forceNewSession` has `Promise<AuthenticationSession | undefined>` return type

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#138684]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63
- OS Version: Windows 11

Steps to Reproduce:

1. Have an extension which calls `getSession` passing the newly finalized `forceNewSession` option
2. 🐛 TypeScript says the return type is potentially `undefined`.  Previously (prior to finalization) it said that the return type was `Promise<AuthenticationSession>`

I think the intent of the forceNewSession option is to ensure that getSession always returns an AuthenticationSession, but because forceNewSession has been added to AuthenticationGetSessionOptions as part of api finalization, it now falls into this case
```ts
        export function getSession(providerId: string, scopes: readonly string[], options?: AuthenticationGetSessionOptions): Thenable<AuthenticationSession | undefined>;
```
rather than this case
```ts
        export function getSession(providerId: string, scopes: readonly string[], options: AuthenticationGetSessionOptions & { forceNewSession: true | { detail: string } }): Thenable<AuthenticationSession>;
```

Is this something we can get fixed in the published types? I think if you switch their order, that would be enough (at least that seems to work locally). In the meantime I have worked around it by downloading the .d.ts off the main branch, switching their order in that copy, and deleting the conflicting copy of @types/vscode from node_modules.

**Comment by deepak1556** [comment]
Candidate pushed via https://github.com/microsoft/vscode/pull/138782

**Comment by TylerLeonhardt** [comment]
Verification steps:

In an extension, grab the `vscode.d.ts` from the release branch and replace the `node_modules/@types/vscode/vscode.d.ts` file with it.

put this in your extension's code:

```ts
vscode.authentication.getSession('github', ['repo'], { forceNewSession: true });
```

The return type of that call should be `Promise<vscode.AuthenticationSession>` NOT `Promise<vscode.AuthenticationSession | undefined>`
