### ISSUE TITLE
Alt + UpArrow

### ISSUE THREAD

**Issue by vwjh37** [microsoft/vscode#138636]
From Selection menu, shortcut 'Alt + UpArrow' should move line up, but it doesn't work. Instead that shortcut conduct a behavior like 'Ctrl + Alt + UpArrow'. Same as 'Alt + DownArrow'.

**Comment by Lemmingh** [comment]
https://code.visualstudio.com/docs/getstarted/keybindings#_detecting-keybinding-conflicts
