### ISSUE TITLE
Yet more 100% capture of CPU by VSCode on Mac

### ISSUE THREAD

**Issue by mormegil27** [microsoft/vscode#138611]
I came here because I found this thread, which describes my *problem* but not solution:

https://github.com/microsoft/vscode/issues/101555

Essentially, VSCode randomly captures 100% of my CPU using the "Code Helper" process.  In my case there were 2 offending processes with the same name.  The processes remain even after closing VSCode and must be directly killed.  My versions:

VSCode: 1.62.3 (Universal)
macOS Catalina: 10.15.7

However, the thread (above) targets the ESLint extension as the problem, but I do not have that extension installed.  My extensions:

Jupyter
Jupyter Keymap
Jupyter Notebook
Pylance
Python

I'm using VSCode solely for editing Python code.  What else might cause this problem?  The CPU capture occurred after I left the system idle for a while.

Thanks!

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code-insiders --status`
