### ISSUE TITLE
Allow configuring CompletionItem dropdown suggestions list order, or partial disabling of language server altogether

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode#138665]
It would be nice if we could give preference to our language's `CompletionItem`s in the suggestions dropdown list.

We made our language very similar to JavaScript, by design, so that it's more familiar to new developers.

So, it's nice when VSCode auto-detects our source files as JavaScript, because then we get nice things like syntax highlighting and variable renaming.

What isn't ideal, however, is that when developers type lines of code into a source file in our programming language, all the **JavaScript** suggestions appear first, and _then_ our language's keywords appear in the suggestions dropdown list, near the bottom.

It would be awesome if we could give preference to **our** language's keywords, or just disable JavaScript's `CompletionItem`s suggestions dropdown list altogether, i.e., pick-and-choose which parts of the JavaScript language server we want to enable, so that the `CompletionItem` suggestions dropdown list only shows our **own** keywords.

Or, it would also be very helpful if we could at least tell Visual Studio Code that we want JavaScript's `CompletionItem`s to appear lower down in the suggestions dropdown list, i.e., let us be able to tell Visual Studio Code which precedence to give different language servers' `CompletionItem`s in the suggestions dropdown list, if we can't disable a language's `CompletionItem`s altogether, so that our language's keywords aren't appearing dead-last when developers write in our programming language.

We don't want to straight-up remove _all_ of the functionality that JavaScript's language server provides, because like I said earlier, we get nice functionality like syntax highlighting and variable renaming by letting Visual Studio Code auto-detect our sources files as JavaScript. It would just be nice if we could pick-and-choose which parts of the JavaScript language server we want, or to at least give precedence to our language's keywords in the `CompletionItem` dropdown suggestions list.

[I looked into implementing this in our programming language's language server, but Dirk recommended I open an issue here, since this is not under the control of the LSP library.](https://github.com/microsoft/vscode-languageserver-node/issues/868)

https://user-images.githubusercontent.com/43425812/145081425-e2573b7e-4638-4977-b090-0a85ec481aba.mov

**Comment by yume-chan** [comment]
>  i.e., pick-and-choose which parts of the JavaScript language server we want to enable

I think you need to create your own language server. You can forward some requests (like semantic highlighting) to Typescript (not that TypeScript server doesn't use LSP, the TypeScript extension bridges TypeScript server protocol to Code extension APIs directly, but you can still use some of its code), and do others (like suggestions) yourself. Code also [recommends this pattern](https://code.visualstudio.com/api/language-extensions/embedded-languages).

It's also possible by creating a [TypeScript server plugin](https://code.visualstudio.com/api/references/contribution-points#contributes.typescriptServerPlugins). Technically you can adjust every part of TypeScript server, but it's very poorly documented and heavily relies on internal parts of TypeScript which can change between versions.

**Comment by jrieken** [comment]
Extensions are all equal and cannot suppress each other. On the other hand there is also no logic to sort completions from one extension higher up than those of other extension. It is all based on the `range` and `sortText` of completion items - so that might be something that you can tweak. Also, as suggested by @yume-chan you should look into tsserver plugins.

**Comment by hamirmahal** [comment]
[I did try setting `item.sortText = 'A';` for our language's `CompletionItem`s in `connection.onCompletionResolve( (item: CompletionItem): CompletionItem => {`](https://github.com/microsoft/vscode-languageserver-node/issues/868#issue-1071720084), but I believe that only affected the order of `CompletionItem`s within our own language server.

This didn't allow any of our language's `CompletionItem`s to "jump ahead" of `CompletionItem`s from Visual Studio Code's built-in JavaScript language server.

**Comment by jrieken** [comment]
The `sortText` property is applied globally. To inspect further, you can use the explain mode: trigger suggest, make sure suggest details show, and hit `cmd+/`. That will change the details window into explain mode, showing sort text, ranges, scores etc. Like so

<img width="764" alt="Screen Shot 2021-12-16 at 09 28 39" src="https://user-images.githubusercontent.com/1794099/146335520-9f3309c6-9411-43af-a0cf-11b488f194f7.png">

**Comment by hamirmahal** [comment]
Whoa! I did not know we could do that. Thank you for showing me that.

So, our language's keywords show up with `score: -100`, by default, and keywords from Visual Studio Code's built-in ~~JavaScript~~ TypeScript language server have `score: 2`.

https://user-images.githubusercontent.com/43425812/146430414-12770aa7-1428-426c-81f3-7b84ee54fbe5.mov

If I do `item.sortText = 'A';`, `score: -100` still, for our language's keywords, and keywords from the ~~JavaScript~~ TypeScript language server still have `score: 2`.

https://user-images.githubusercontent.com/43425812/146432660-eabd847f-eb3f-4f6b-94f8-d28c0b30c383.mov

For what it's worth, even if I change the language to `'plaintext'` instead of `'javascript'` for these `CompletionItem`s, and look at the `score` in `plaintext` files, they still have `score: -100`.

https://user-images.githubusercontent.com/43425812/146431062-d970df96-d995-458a-a70d-6ce2760187e1.mov

It would be amazing if we could manually edit these `score`s to give them a `score` of, for example, `3`, to let our language's suggestions show up, first.

Or, if we could remove JavaScript keyword suggestions from ~~JavaScript's~~ TypeScript's language server altogether, that would be nice, since we could use the features of the ~~JavaScript~~ TypeScript language server that we want, like 'jump to definition', and smart 'variable renaming', while still having our language's keywords show up at the top of a `CompletionItem` suggestions dropdown list.

Also, for fun, I tried `item.sortText = '0';`, but the `score`s of our language's `CompletionItem`s are still `score: -100`.

https://user-images.githubusercontent.com/43425812/146433315-25eb363e-29d6-47d6-b526-13232f0b1806.mov

**Comment by hamirmahal** [comment]
@jrieken, do you have any additional thoughts on this? I think we'll go with having our own, separate language server, instead of relying on the JavaScript one, so our language's keywords aren't appearing last in the suggestions dropdown list.
