### ISSUE TITLE
shell command path not showing in VS code

### ISSUE THREAD

**Issue by SkiSherpa** [microsoft/vscode#138616]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by SkiSherpa** [comment]
The "shell command" path is not showing up in the search in the VS code app. I've uninstalled, reinstalled the app, restarted my computer. VS code is in my applications folder. 

<img width="650" alt="Screen Shot 2021-12-07 at 10 08 47 AM" src="https://user-images.githubusercontent.com/87342782/145088216-f881db21-9b71-46ee-8859-eec7d66f0833.png">
.

**Comment by kyr0** [comment]
@SkiSherpa What exactly are you trying to accomplish?  If you want to run shell commands, open View -> Terminal. This will open the system shell. To see the current path, run `pwd` on macOS/Linux or `echo %cd%` on Windows

**Comment by SkiSherpa** [comment]
My goal is to open all the files with in a directory from the terminal. Sometimes there are many, and I want to use `code . ` The command always worked before, but today it didn't. When I run it `code .` I get `-bash: code: command not found`.

Based on what you said, the terminal in VS code says the interactive shell is zsh, I'm currently running bash. Is that an issue? However, in the top right corner of the terminal in VS code it says bash.

 I mainly run it due to courses that I'm in. I'm still new to the coding scene. Is the terminal in VS code different than the one on my macbook?

**Comment by SkiSherpa** [comment]
I found my issue. It was very simple. I used the incorrect shortcut to find the search. I was using command+up+P, instead of command+shift+P.

Thank you for your help.
