### ISSUE TITLE
Markdown preview relative links sometimes don't work

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#138629]
- VS Code Version: 1.63.0 Insiders
- OS Version: Windows 11

Noticed while reviewing vscode-docs release notes highlight links.

Steps to Reproduce:

1.Open v1_61.md.
2. Ctrl+V to get the Markdown preview. The highlight links work.
3. Open v1_59.md.
4. Select the open Markdown preview. The highlight links for v1_59.md don't work.
5. Go back to v1_61.md.
6. Go back to open Markdown preview. Now the highlight links for v1_61.md don't work as well.

Not sure if this is related to the recent work to support incremental Markdown Preview refresh. Does not repro on 1.62.

**Comment by mjbvz** [comment]
@gregvanl Can you please test this again in the latest insiders? If you still don't see it working, can you add some detail on which links you are clicking on? I just tested but could not reproduce this

**Comment by gregvanl** [comment]
@mjbvz Yep, appears to be working now on 1.64 Insiders.
