### ISSUE TITLE
Issue Reported took forever to popup

### ISSUE THREAD

**Issue by Ma-XX-oN** [microsoft/vscode#138696]
Issue Type: <b>Bug</b>

I was about to report on an issue and the issue reporter window wouldn't pop up.  I tried to open it up several times (10?). Finally, I issued the Developer: Reload Window command and it still wouldn't pop up (tried another 10 times).  Then I tried to close and reopen VSCode and it still didn't pop up till about the 5th try.

Not sure if it's related, but before I had done this, I had just ran a regex that wouldn't end (endless loop) and the IDE just froze.  I get a message from Windows asking if I want to Restart or do two other things.  I said restart and that's when I found I couldn't bring up the Issue Reporter window.  (Going to post a separate issue regarding this problem).

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.38GB (0.87GB free)|
|Process Argv|--crash-reporter-id ff847a9c-5b94-44a0-b759-b62cfb7fa79c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
overtype|DrM|0.4.0
vscode-powertools|ego|0.67.1
vscode-pull-request-github|Git|0.32.0
better-cpp-syntax|jef|1.15.10
cortex-debug|mar|0.4.10
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.12.0
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.3
remote-ssh|ms-|0.68.0
remote-ssh-edit|ms-|0.68.0
remote-wsl|ms-|0.63.4
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.0-insiders2
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5196
vsliveshare-audio|ms-|0.1.91
comment-wrap|nex|0.0.2
select-by|rio|1.9.0
code-spell-checker|str|2.0.13
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30408636
vscop804cf:30404767
vscop341:30404997
vsrem710:30405998
vscexrecpromp3t2:30407763

```

</details>

 too large to send. Please paste.

**Comment by TylerLeonhardt** [comment]
I wonder if we are trying to prefill some data that blocks the UI from showing.

If you open the Issue Reporter and just wait a while, does it eventually show up (even after ... 1min...5min)?
