### ISSUE TITLE
Send command to terminal even if nothing is selected.

### ISSUE THREAD

**Issue by anishmittal2020** [microsoft/vscode#138647]
- My `keybindings.json`

```json
    {
        "key": "alt+l",
        "command": "workbench.action.terminal.sendSequence",
        "args": { "text": "\u000AMdLink \"${file}\" \"${selectedText}\" \u000A" },
        "when": "!editorReadonly"
        //"when": "!editorReadonly && editorLangId == 'markdown'"
    }
```

It executes a bash script called MdLink with arguments path of the file and the selected text.

This script should do something special when a text is selected. And when nothing is selected, then I want the script to do something general. I know that I can create another keybinding without `selectedText` variable but its not elegant.

But the shortcut fails if no text is selected. May be its useful to still run the command even if no text is selected.

**Comment by ArturoDent** [comment]
> But the shortcut fails if no text is selected.

Are you saying the command doesn't run at all if there is  no `selectedText`?  The `selectedText` should just resolve to the empty string if there is no `selectedText`.

Do you want to run a different script if there is no `selectedText`?

---------------

You can also use these `when` clauses:

` "when": "editorHasSelection"`

 and

` "when": "!editorHasSelection"`       // note the negation

**Comment by anishmittal2020** [comment]
> Are you saying the command doesn't run at all if there is no selectedText?

Yes

> Do you want to run a different script if there is no selectedText?

No. The script internally counts number of arguments and does work accordingly. 

I want the command to be passed to terminal irrespective of a string being selected or not.
