### ISSUE TITLE
Git commit also sync

### ISSUE THREAD

**Issue by MalcolmMielle** [microsoft/vscode#138648]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- OS Version: Fedora 35

Steps to Reproduce:

1. Create a GitLab repo
2. Clone locally
3. Modify the repo
4. In the version control tab, stage changes and add commit message.
5. Click on "commit" check mark. 
6. The repo is sync automatically after the commit

I expect the repo to not sync automatically.

I am not sure if anything changed recently, but I'm observing this behavior on multiple repos.

**Comment by gjsjohnmurray** [comment]
What is your `git.postCommitCommand` setting?

**Comment by MalcolmMielle** [comment]
It says "none".
