### ISSUE TITLE
Failed to download VS Code Server HTTP 500 - Internal Server Error

### ISSUE THREAD

**Issue by jmorris-dev** [microsoft/vscode#138660]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.3
- OS Version: Windows 10 19042.1348

Steps to Reproduce:

1. Install Remote - Containers
2. Attempt to build docker dev environment.

![Screenshot (546)](https://user-images.githubusercontent.com/25271173/145247927-9d621e53-f6d8-4cf3-ad5f-daaf06b30f0c.png)

**Comment by georgebv** [comment]
Same issue here. Getting 500 error when checking for updates. Looks like the server is down.

**Comment by jmorris-dev** [comment]
> Same issue here. Getting 500 error when checking for updates. Looks like the server is down.

Yes, its been down since at least yesterday afternoon EST when I first saw this error.

**Comment by Sam948-byte** [comment]
Good to know it's not just me.

**Comment by rangelfinal** [comment]
It's not possible to use the "Remote - WSL" extension as well
```
Installing VS Code Server for x64 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247)
Downloading: 100%
Failed
--2021-12-08 14:00:10--  https://update.code.visualstudio.com/commit:ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/server-linux-x64/stable
Resolving update.code.visualstudio.com (update.code.visualstudio.com)... 51.144.164.215
Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|51.144.164.215|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2021-12-08 14:00:15 ERROR 500: Internal Server Error.

ERROR: Failed to download https://update.code.visualstudio.com/commit:ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/server-linux-x64/stable to /home/rangel/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247-1638982806.tar.gz  
```

It seems to have happened before  #74732

**Comment by Sam948-byte** [comment]
I think it might be back up, it's letting me install an update now.

**Comment by jmorris-dev** [comment]
I can confirm I was also able to install now, seems fixed.
