### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'getLineLastNonWhitespaceColumn' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#13868]
Issue Id: <b>a7cb80c1-76af-90d9-6c0e-b4703c3b697c</b><br /><br />*Versions* <br />- 1.6.1<br />-  e52fb0bc87e6f5c8f144e172639891d8d8c9aa55<br />*Stack* <br />TypeError: Cannot read property 'getLineLastNonWhitespaceColumn' of null<br />[/vs/editor/browser/widget/diffEditorWidget.ts#L1606:36 (getLineLastNonWhitespaceColumn)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/widget/diffEditorWidget.ts#L1606:36 (getLineLastNonWhitespaceColumn))<br />[/vs/editor/browser/widget/diffEditorWidget.ts#L1124:33 (_getModifiedEditorDecorations)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/widget/diffEditorWidget.ts#L1124:33 (_getModifiedEditorDecorations))<br />[/vs/editor/browser/widget/diffEditorWidget.ts#L835:39 (getEditorsDiffDecorations)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/widget/diffEditorWidget.ts#L835:39 (getEditorsDiffDecorations))<br />[/vs/editor/browser/widget/diffEditorWidget.ts#L242:66 (_updateDecorations)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/widget/diffEditorWidget.ts#L242:66 (_updateDecorations))<br />[/vs/base/common/async.ts#L597:8 (runner)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/common/async.ts#L597:8 (runner))<br />

**Comment by alexandrudima** [comment]
Fixed with bdd1a312855ef9ca1bc221fb5fb611421b0766ae
