### ISSUE TITLE
Keyboard not working (some keys)

### ISSUE THREAD

**Issue by r3soares** [microsoft/vscode#138668]
Issue Type: <b>Bug</b>

Sometimes the keyboard stops working (some keys). The error has happened to me when developing flutter for windows, with debug mode disabled (CTRL+F5). The problem occurs when there are errors in the design of widgets, for example: when I don't define their size and flutter doesn't know how to display them on the screen. I notice that when errors are displayed, the pc becomes slow and then the keyboard stops working. Just returning when closing and reopening vscode.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.28GB free)|
|Process Argv|--folder-uri file:///d%3A/Projetos/AgendamentoVTR/agendamentoVTR/src/agendamento_vtr --crash-reporter-id f1b9a160-ce2a-440c-9a78-3415df3883d6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.4.0
dart-code|Dar|3.29.0
flutter|Dar|3.29.0
xml|Dot|2.5.1
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
vscode-rojo|eva|1.13.3
code-runner|for|0.11.6
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-docker|ms-|1.18.0
vscode-language-pack-pt-BR|MS-|1.62.4
csharp|ms-|1.23.17
remote-containers|ms-|0.205.2
remote-wsl|ms-|0.58.5
robloxlsp|Nig|1.5.5
material-icon-theme|PKi|4.11.0
gruvbox-material|sai|6.4.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
vsena315cf:30406436
pythonvs932:30408636
vscop804cf:30404767
vscop341:30404997
vsrem710cf:30405999

```

</details>

**Comment by alexdima** [comment]
When you have a problem with a specific keybinding, please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `F1 > Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
