### ISSUE TITLE
Multiple "Fetching search index..." notifications in github.dev

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#138670]
In my case I have switched to Insiders version of github.dev and as well as enabled search index couple of weeks ago.

When I opened github.dev again today I had Find in Files view active and started to type. Not sure if there were 3 notifications when page started loading, but when I finished I saw 3 similar notifications.
(I think there were two at some point and third appeared when I finished, but can't tell for sure as there were other notification for some time)

![image](https://user-images.githubusercontent.com/1312662/145270716-2c06bb8e-0127-41ff-87ad-b0928a93b636.png)

Version: 1.63.0-insider
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4714.0 Safari/537.36 Edg/98.0.1089.1
Embedder: github.dev

**Comment by jrieken** [comment]
Also saw this. Maybe related to anycode also triggering an index fetch?

**Comment by JacksonKearl** [comment]
Logic has since been updated quite a lot, this should not longer occur.
