### ISSUE TITLE
TerminalCommandTracker - before each" hook for "should scroll to the next and previous commands

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138609]
```
  1) Workbench - TerminalCommandTracker
       Commands
         "before each" hook for "should scroll to the next and previous commands":

      Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      + expected - actual
```

https://github.com/microsoft/vscode/runs/4445847188?check_suite_focus=true#step:13:9039

**Comment by bpasero** [comment]
Time to disable this test?

**Comment by bpasero** [comment]
Also https://github.com/microsoft/vscode/runs/4445036589?check_suite_focus=true#step:13:9039

**Comment by Tyriar** [comment]
Disabled, will either fix or remove it this iteration.

**Comment by Tyriar** [comment]
Interestingly TerminalCommandTracker only fails on GH actions, not ADO

**Comment by Tyriar** [comment]
Let's track in https://github.com/microsoft/vscode/issues/138273
