### ISSUE TITLE
Weird scrollbar on first menu opening

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#138637]
![image](https://user-images.githubusercontent.com/38270282/145187345-be124222-2ca9-45c3-a4ab-c5bb4bcfa4e0.png)

Found while sanity testing the 1.63 stable build (Windows 64).

1. Reload or open VS Code. 
2. Do nothing for ~5 seconds
3. Click on a menu to open it.

Repros 100% of the time for me and with extensions disabled.

**Comment by deepak1556** [comment]
Can also confirm on my setup `Windows_NT arm64 10.0.22000`, issue is not present in `1.62.3` stable and bisect shows issue was first introduced in Version: 1.63.0-insider, Commit: 4e303fcc52269ab578affa6cb1eb455eacab445f

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/138110 

@deepak1556 thanks for bisecting as I could not repro
