### ISSUE TITLE
Tests stop to work at random

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138632]
I feel that over the past weeks our test runner has gotten a lot more unstable again, often requiring me to reload the window before I can run a test again. This is always with unit tests from us.

Check recording:
![recording](https://user-images.githubusercontent.com/900690/145162023-69d5449b-7887-407f-8172-00602fd14b1d.gif)

There is no hanging Code OSS process.

**Comment by bpasero** [comment]
I think this happens when I add a new test to a suite.

**Comment by connor4312** [comment]
This is slippery but I think I know what's going on. Please let me know if you continue to see this.
