### ISSUE TITLE
Terminal Stopped Launching a Shell

### ISSUE THREAD

**Issue by hpinsley** [microsoft/vscode#138676]
Issue Type: <b>Bug</b>

The terminal window no longer launches any shell and you cannot type in the terminal window.  The drop down to the right simply says:

Configure terminal settings and
Select Default Profile

I've been using VSCode for some time and this is the first time I've had this issue.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.73GB (26.07GB free)|
|Process Argv|--crash-reporter-id f55e2ec5-13b4-443e-9bf7-3f1ace27d869|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.15.1
cypress-snippets|and|1.2.0
xml|Dot|2.5.1
gitlens|eam|11.7.0
prettier-vscode|esb|9.0.0
vscode-mysql|for|0.4.1
gc-excelviewer|Gra|4.0.45
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.24.6
nbpreviewer|jit|1.2.2
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.17
data-workspace-vscode|ms-|0.1.0
mssql|ms-|1.11.1
sql-database-projects-vscode|ms-|0.13.1
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.12.0
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.205.2
remote-wsl|ms-|0.58.5
powershell|ms-|2021.10.2
test-adapter-converter|ms-|0.1.4
debugger-for-chrome|msj|4.13.0
csharp2ts|raf|0.0.26
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.2
elm|sbr|0.26.0
vscode-scss-formatter|sib|2.3.3
vscode-behave-test-adapter|You|0.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30408636
vscop804cf:30404767
vscop940:30404999
vsrem710:30405998
vscexrecpromp3t3:30407764

```

</details>

**Comment by meganrogge** [comment]
Set terminal,integrated,useWslProfiles to false
