### ISSUE TITLE
Hide extension update notifications

### ISSUE THREAD

**Issue by KarlRhodes** [microsoft/vscode#138641]
I work with Microsoft Business Central and develop against multiple versions using their AL language, which requires that I use the "AL Language" extension, and must have specific versions of the extension installed to work with different versions of Business Central.

When using an earlier version of the "AL Language" extension while developing against an earlier version of Business Central, I am constantly notified that a new version exists that I simply cannot use it.

Can we add the ability to hide notifications for new versions of extensions?

Perhaps a boolean option "extensions.hideUpdateNotifications"

**Comment by gjsjohnmurray** [comment]
How about the existing setting `"extensions.autoCheckUpdates": false`

**Comment by KarlRhodes** [comment]
> How about the existing setting `"extensions.autoCheckUpdates": false`

Thanks for your reply John..
Unfortunately, I already have this set, and its made no difference. The notification is still there.

**Comment by KarlRhodes** [comment]
Screenshot for reference...
![image](https://user-images.githubusercontent.com/33315989/145219062-266ac002-93a8-4b48-8ba2-cb0faa12ec0b.png)
