### ISSUE TITLE
Access to Proposed APIs setting no longer persisted with version 1.63

### ISSUE THREAD

**Issue by wilhem-meignan** [microsoft/vscode#138736]
The Code Together extension is asking for access to VS Code Proposed APIs on startup.

![image](https://user-images.githubusercontent.com/47667558/145379267-5457579d-3d40-42ef-bdf5-8cc5479c1851.png)

After clicking "Enable", a restart is required:

![image](https://user-images.githubusercontent.com/47667558/145379619-4291e15b-f63c-4619-97dd-b5043ee352d4.png)

But on restart the same notifications are displayed again.

This issue started with the update to VS Code 1.63.

Version: 1.63.0 (user setup)
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T06:26:56.179Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

Name: CodeTogether
Id: genuitecllc.codetogether
Description: Add CodeTogether to VS Code to live share your IDE and coding sessions. Cross-IDE support for VS Code, IntelliJ and Eclipse. Free plan always available!
Version: 5.0.1
Publisher: Genuitec
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=genuitecllc.codetogether

**Comment by gjsjohnmurray** [comment]
/causedByExtension

The extension author needs to adopt the new rules. See https://code.visualstudio.com/updates/v1_63#_updated-api-proposal-structure

**Comment by wilhem-meignan** [comment]
Thank you for the quick feedback. I have opened an issue there.

https://github.com/Genuitec/CodeTogether/issues/352
