### ISSUE TITLE
Plot in Julia always open in the first group

### ISSUE THREAD

**Issue by sheevy** [microsoft/vscode#138738]
Does this issue occur when all extensions are disabled?: Cannot tell because Julia extension is required to reproduce.

- VS Code Version: 1.63
- OS Version: Windows 10 Pro

After migration to 1.63: when plotting (in Julia) the prot always open in the first group. Previously, it would open in the group which have plot pane already opened.

Steps to Reproduce:

1. Install Julia + Julia mode for VS Code + Plots.jl
2. Make a plot.
3. Split the screen in VS Code and move the Plot pane there.
4. Make another plot.

What happens: plot gets shown in the first group
What should happen: plot gets shown in the second group, where the previous plot is.

**Comment by Talmanes** [comment]
I do not think it is an extension issue.  I'm getting the same problem with **REST Client** extension.  First request splits out the **Response** to the right.  If I run it again, it moves that **Response** split window back to the first grouping.  So I have to click back into my script.

**Comment by sheevy** [comment]
https://github.com/julia-vscode/julia-vscode/issues/2618

**Comment by sheevy** [comment]
#julia-vscode/julia-vscode/issues/2618
