### ISSUE TITLE
Extension fails while Debugging when in Monorepo

### ISSUE THREAD

**Issue by inferrinizzard** [microsoft/vscode#138773]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- OS Version: Win 10

## Context

I have a formatting VSCode extension for one of my npm packages that I recently consumed as a subrepo but now I am having issues with Debugging it vs. the original repo. \
Debugging works correctly in the standalone repo but running the same command with the subrepo folder open causes issues - the Debugging Extension Host starts correctly and I believe the extension does launch correctly (section appears in settings) but the Formatter does not get properly registered.

Similar to: #108000

### Steps to Reproduce:

1. Open subrepo folder with VSCode
2. Launch Extension Host via F5 or Debug menu
3. Check list of formatters for SQL files / attempt to format SQL files.

### Materials
File Hierarchy:
![image](https://user-images.githubusercontent.com/10782902/145442072-b0291740-1808-40a1-a102-de5a3c85c038.png)

launch.json:
![image](https://user-images.githubusercontent.com/10782902/145442237-d2a51ca6-6bd4-4f27-9b6f-4a300b4f762a.png)

tasks.json (`watch` is `tsc --watch`):
![image](https://user-images.githubusercontent.com/10782902/145442314-52009083-9c63-4fbc-8e7f-7eded16f7cf5.png)

Error Message and list of formatters:
![image](https://user-images.githubusercontent.com/10782902/145442905-e4bead5c-236f-418e-b3be-d459110143b0.png)
![image](https://user-images.githubusercontent.com/10782902/145443000-b85016de-ad27-4de3-8e7d-3df67c8c936f.png)

Expected output (run with standalone repo):
![image](https://user-images.githubusercontent.com/10782902/145443231-cb3ff42d-3911-4c3c-a7a0-2ce34786a403.png)

**Comment by inferrinizzard** [comment]
Yes, the directory looks exactly the same as before, it is simply contained within another folder as a monorepo.
When I open the subfolder in VSCode, it has exactly the same contents as the standalone repo, the Debugger is launched from the same folder, all other components are the same.

**Comment by inferrinizzard** [comment]
@weinand Any help ?

**Comment by weinand** [comment]
@inferrinizzard where do your generated *.js files live? I cannot find them in the "File Hierarchy" screenshot from above.

**Comment by inferrinizzard** [comment]
the `out` directory is on the same level as `src`:
![image](https://user-images.githubusercontent.com/10782902/146396048-fe16a930-bc39-4bc3-a3bd-71f50d632114.png)

**Comment by weinand** [comment]
If you set a breakpoint in the extension's `activate` method, is it being hit if you activate the extension?

**Comment by inferrinizzard** [comment]
Yes, the breakpoint is set as an unbound breakpoint and does trigger when the extension first loads but is unable to trigger within the formatProvider since it is unable to be called. (when run with the subrepo)

However - when I add a breakpoint to the standalone repo - it does _not_ trigger on extension load but triggers normally when formatting, which feels like intended behaviour.

**Comment by inferrinizzard** [comment]
I got it to work by replaying all my changes on a fresh `yo code` starter, content looks about the same as before - may have been a missing `vscode install` cmd when changing directories

**Comment by weinand** [comment]
@inferrinizzard great to hear that you could solve your problem.
