### ISSUE TITLE
Git operations frequently freeze (please add better git logging)

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode#138743]
Does this issue occur when all extensions are disabled?: Yes (need remote extension though)

- VS Code Version: 1.62.3
- OS Version: Mac 11.6

Steps to Reproduce:

1. Connect to a remote server in my company (ok this is not really reproducible)
2. Do a load of git operations

After a while performance will start degrading and git operations (e.g. opening file changes) take several seconds, sometimes minutes. Reloading the window gets back to normal performance.

The filesystem is a heavily loaded NFS mount, and while git operations in the integrated terminal can be slow, they're never *that* slow. When it freezes I can go to the git Output pane and copy/paste the commands into a terminal and they run instantly.

Since this is pretty hard to reproduce I'd really just like to know if there is any way to get more debugging information from the git process. The git Output just shows which commands are run, but not how long they took, what the UI is waiting for, etc.

Is there any way to get that information? As I understand it I can't rebuild VSCode myself to add it because of the licensing of the remote development extension. It only works with official builds.

**Comment by gjsjohnmurray** [comment]
related - #138168

**Comment by Timmmm** [comment]
Ah nice. That's what I call service! I'll close this an reopen it if the new logging fails to elucidate.
