### ISSUE TITLE
CANNOT use API proposal: quickPickSeparators. Its package.json#enabledApiProposals-property declares: [] but NOT quickPickSeparators.

### ISSUE THREAD

**Issue by kbysiec** [microsoft/vscode#138745]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.63.0 (Universal)
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T05:15:48.091Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.1.0

After update to version 1.63.0 my extension [vscode-search-everywhere](https://marketplace.visualstudio.com/items?itemName=kbysiec.vscode-search-everywhere) has stopped working. In version 1.62.3 everything was working, there were no updates on extension side. It doesn't use any proposal API so the error is weird.

The received error:
![image](https://user-images.githubusercontent.com/26285420/145389242-96258820-d2b8-4870-b7e5-8859ef52f914.png)

In [package.json](https://github.com/kbysiec/vscode-search-everywhere/blob/master/package.json) there isn't property enabledApiProposals.

**Comment by gjsjohnmurray** [comment]
Your extension extension extends the `vscode.QuickPickItem` interface, adding a `kind` property:

![image](https://user-images.githubusercontent.com/6726799/145394314-07200cd4-62fa-4213-9f6e-e20903087cb8.png)

This coincides with the new property added in the proposed API mentioned in the error message.

I think you need to rename your property.

**Comment by jrieken** [comment]
That's really unfortunate. We are working on a new property that allows to classify quick pick items. This is [the proposal](https://github.com/microsoft/vscode/blob/b256d9bc74e56e315fa2ce858f68500b65869198/src/vscode-dts/vscode.proposed.quickPickSeparators.d.ts#L15-L16) and it is enforced [here](https://github.com/microsoft/vscode/blob/b256d9bc74e56e315fa2ce858f68500b65869198/src/vs/workbench/api/common/extHostQuickOpen.ts#L541). It seems that your extension is already using this property inside the [`createQuickPickItem`](https://github.com/kbysiec/vscode-search-everywhere/blob/1ee0462200e6830419e061f2088b8bd70414d8bf/src/dataConverter.ts#L143)-function. This is unhappy but can happen as we extend/broaden the API. You can unblock yourself by picking a different name for "your" kind-property

**Comment by kbysiec** [comment]
@gjsjohnmurray, @jrieken 

Thanks Guys for clarification and quick support. After renaming the property, everything is working as expected.

Cheers!
Kamil

**Comment by tyglander** [comment]
You have the same issue with: Extension '**ms-dotnettools.csharp**' CANNOT use API proposal: quickPickSeparators. Its package.json#enabledApiProposals-property declares: [] but NOT quickPickSeparators. The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-dotnettools.csharp

I would have thought introducing a breaking change would be less than ideal.
