### ISSUE TITLE
Cannot debug mocha/es6 tests

### ISSUE THREAD

**Issue by ales004** [Microsoft/vscode#13876]
- VSCode Version: 1.6.1
- OS Version: Windows 10

Steps to Reproduce:
1. Open the attached project [BugExample.zip](https://github.com/Microsoft/vscode/files/532832/BugExample.zip)
2. Run  npm install
3. Open the project in VS Code
4. Put a breakpoint in L8 or L16 of ActionTest.test.js
5. Debug the test using the Launch configuration

The problem is that the test is run but the breakpoint is not hit. I think that this is related to the fact that the source maps are not loaded correctly but I don't undertand how to solve the problem.

Thank you for your help
Alessandro

**Comment by weinand** [comment]
works fine now.
