### ISSUE TITLE
Your Release Notes are terrible

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#138720]
Issue Type: <b>Bug</b>

It's impossible to properly read through the material with all the blinking GIF animations in your face constantly. This is terribly distracting and frustrating.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3598)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (42.13GB free)|
|Process Argv|--crash-reporter-id f825acfe-92fa-4526-a38a-f8815cf9f7ea|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (45.27GB free)|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.5.0
javascript-ejs-support|Dig|1.3.1
eslint-disable-snippets|drK|1.3.0
output-colorizer|IBM|0.1.2
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.209.3
remote-ssh|ms-|0.68.0
remote-ssh-edit|ms-|0.68.0
remote-wsl|ms-|0.63.4
vscode-remote-extensionpack|ms-|0.21.0
vscode-icons|vsc|11.8.0
tsl-problem-matcher|amo|0.5.0
vscode-zipfs|arc|2.3.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.2.2
javascript-ejs-support|Dig|1.3.1
xml|Dot|2.5.1
eslint-disable-snippets|drK|1.3.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
vs-code-xml-format|fab|0.1.5
generateuuid|Fir|0.0.5
shell-format|fox|7.2.2
vscode-graphql|Gra|0.3.41
yarn2-dependency-explorer|hah|0.0.1
terraform|has|2.17.0
vscode-test-explorer|hbe|2.21.1
vscode-esformatter|how|1.6.0
output-colorizer|IBM|0.1.2
innosetup|idl|1.6.1
vscode-random|jre|1.11.0
template-string-converter|meg|0.5.5
code-beautifier|mic|2.3.3
vscode-docker|ms-|1.18.0
vscode-kubernetes-tools|ms-|1.3.4
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.12.0
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
test-adapter-converter|ms-|0.1.4
vscode-js-profile-flame|ms-|0.0.21
vscode-paste-image|mus|1.0.4
monolit|Oli|0.0.33
vscode-yaml|red|1.2.2
vscode-icons|vsc|11.8.0
docker|vsc|1.0.0
yaml|vsc|1.0.0

(2 theme extensions excluded)

</details>

**Comment by Lemmingh** [comment]
#134514

**Comment by gjsjohnmurray** [comment]
> I'd also be fine with reading the release notes in Markdown

https://raw.githubusercontent.com/microsoft/vscode-docs/main/release-notes/v1_63.md

**Comment by mjbvz** [comment]
> Your Release Notes are terrible

Terrible issue title ;) In the future, lay off the hyperbole and instead summarize the issue @oliversalzburg

**Comment by ArturoDent** [comment]
I do think sometimes the gifs are a little "fast" which makes them more difficult to follow.  The creators could slow the sequences a little (just by pausing occasionally or using a higher frame capture rate) and they would be less "flashy".
