### ISSUE TITLE
No Results in Search Editor

### ISSUE THREAD

**Issue by bphunter1972** [microsoft/vscode#138785]
Issue Type: <b>Bug</b>

The screenshot shows how a search finds results when performed in the Search window of the sidebar, but no results when performed in the "Search: Find in Files" or "Search in Editor: New Search Editor"

I have pored over the settings, but haven't found anything that would cause the results to not appear in the search editor window.

VS Code version: Code 1.63.0 (Universal) (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1062.1.2.el7.x86_64
Remote OS version: Linux x64 3.10.0-1062.1.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id ed8eb4ec-682d-46cd-9f6c-960816ecada1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: scv-bphunter01.csg.apple.com|
|OS|Linux x64 3.10.0-1062.1.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz (2 x 2992)|
|Memory (System)|7.64GB (1.47GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: scv-bphunter01.csg.apple.com|
|OS|Linux x64 3.10.0-1062.1.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz (2 x 2992)|
|Memory (System)|7.64GB (1.47GB free)|
|VM|100%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-peacock|joh|4.0.0
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.68.0
sublime-keybindings|ms-|4.0.10
vs-qalc|nor|0.1.7
material-icon-theme|PKi|4.11.0
rewrap|stk|1.15.4
jinja|who|0.0.8
increment-selection|alb|0.2.0
clock|ang|1.0.1
toml|be5|0.6.0
systemverilog|eir|0.11.3
vscode-select-by-indent|hab|0.1.2
vscode-test-explorer|hbe|2.21.1
search-editor-apply-changes|jak|0.1.1
align-by-regex|jan|1.0.4
vscode-python-test-adapter|lit|0.7.0
mypy|mat|0.2.1
git-graph|mhu|1.30.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.12.0
test-adapter-converter|ms-|0.1.4
vscode-text-tables|Rom|0.1.5
vscode-paste-and-indent|Rub|0.0.8
todotasks|san|0.5.0
sort-lines|Tyr|1.9.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.4.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
vsena315:30406435
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710:30405998
vscexrecpromp3c:30407761

```

</details>

**Comment by bphunter1972** [comment]
<img width="676" alt="Screen Shot 2021-12-09 at 11 35 13" src="https://user-images.githubusercontent.com/5446342/145465068-d2a44dc4-c01d-4936-98dd-98979fa1708e.png">

**Comment by pascaloliv** [comment]
Hello - exact same issue for me with this configuration :

```
Version: 1.63.0 (Universal)
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T05:15:48.091Z (3 days ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0
```

But it seems fixed in 
```
Version: 1.64.0-insider (Universal)
Commit: 065b450db9f555f177161748e8f2911ebb5677f9
Date: 2021-12-10T05:13:44.798Z (4 hrs ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0
```

**Comment by JacksonKearl** [comment]
> but no results when performed in the "Search: Find in Files"

`Find in Files` usually opens that same sidebar, do you have `search.mode` configured? And are you able to reproduce in Insiders?

If you can share a repo where this happens I might be able to better understand the issue.

**Comment by bphunter1972** [comment]
I agree that it has been fixed in the insiders version. However some testing around this area probably needs updating.

**Comment by JacksonKearl** [comment]
There haven't been any changes to search editor logic in quite some time so it's unclear what would cause the difference here. These are also the only two reports of this I've seen, so there may be something specific to your setups that is causing the problem. It'd help me to diagnose this if you could try running with a fresh install (for example: `code --user-data-dir ~/Desktop/tmp --extensions-dir ~/Desktop/tmp`) and seeing if the problem reproduces there in some public repository.
