### ISSUE TITLE
 the SVN plug-in cannot be used。

### ISSUE THREAD

**Issue by mumu-baba** [microsoft/vscode#138706]
Issue Type: <b>Bug</b>

Missing dependency: jschardet

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (0.51GB free)|
|Process Argv|--crash-reporter-id 8e6645b7-6dcd-4afb-90ae-11dc9fcc0979|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.29.0
flutter|Dar|3.29.0
es7-react-js-snippets|dsz|3.1.1
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
auto-close-tag|for|0.5.13
anes|gam|0.0.2
codespaces|Git|1.4.1
vue|jcb|0.1.5
svn-scm|joh|2.15.0
compare-folders|mos|0.22.2
vscode-docker|ms-|1.18.0
vscode-language-pack-zh-hans|MS-|1.63.2
remote-containers|ms-|0.209.3
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.8.1
awesome-flutter-snippets|Nas|3.0.2
vetur|oct|0.35.0
LiveServer|rit|5.6.1
altitude-script-language|uca|0.0.3
highlight-matching-tag|vin|0.10.1
vscode-icons|vsc|11.8.0
material-theme|zhu|3.13.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932cf:30408637
vscop804:30404766
vs360:30404995
vsrem710cf:30405999

```

</details>

**Comment by Jomsanchez-gmv** [comment]
Same problem here:

After vscode update to v1.63.0 (this morning in EU) I have "Missing dependency: jschardet" issue linked to SVN (https://marketplace.visualstudio.com/items?itemName=johnstoncode.svn-scm) extension.

**Comment by guypes** [comment]
Same problem. Please it's urgent, all our work is based on SVN so we are locked.
It's possible to lock temporary the update of vscode or to manual load the missing module?

**Comment by Josemi-SW** [comment]
> 

I have downgraded manually to previous version: https://code.visualstudio.com/updates/v1_62

**Comment by Josemi-SW** [comment]
Update: SVN extension has been updated few minutes ago. Now everything works with new VSCode release.
