### ISSUE TITLE
Calling a Native Node.js Add-On API In an Extension Launches New Dock Icon for Extension Host Process in macOS

### ISSUE THREAD

**Issue by ericdrobinson** [microsoft/vscode#138712]
Issue Type: <b>Bug</b>

I'm working on an extension for VS Code and have found that in 1.63 when I launch the debugger or issue a command from the Command Palette, a new VS Code icon appears in the macOS 10.14.6 Dock. It bounces for quite a while and only ever shows "Force Quit" when right-clicked.

![image](https://user-images.githubusercontent.com/9142587/145357155-bec9c51f-69ed-4efd-8ac9-b1511b663d63.png)

If you _do_ "Force Quit" the icon, an error message pops up in the VS Code Window that issued the command that reads "Extension host terminated unexpectedly." It provides two options:

1. Open Developer Tools
2. Restart Extension Host

Restarting the Extension Host works just fine. To be clear, the extension appears to work as expected as well (until the new Dock icon is force-quit, of course).

I just did a bunch of work on the extension build process for the extension I'm working on, so I _thought_ the issue was on my end. However, I tested the same build of my extension in VS Code **1.62** and it did **not** exhibit this odd functionality. I also tested the older version of the extension I'm working on and it caused the same issue. Seems to repro 100% of the time for me.

I searched around the issues but wasn't able to find anything. Any insights as to what's going on (or if this is simply just a VS Code bug) would be greatly appreciated.

**VS Code version:** Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
**OS version:** Darwin x64 18.7.0
**Restricted Mode:** No
**Remote OS version:** Linux x64 5.10.47-linuxkit
**Remote OS version:** Linux x64 5.10.47-linuxkit

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
extendscript-debug|Ado|2.0.0-beta0
githistory|don|0.6.19
vscode-diff|fab|1.4.2
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932cf:30408637
vscop804:30404766
vscop940:30404999
vsrem710cf:30405999
vscexrecpromp3t3:30407764

```

</details>

**Comment by ericdrobinson** [comment]
It gets worse: it spawns a VS Code icon in the Dock for window within which the command was triggered. See:

![image](https://user-images.githubusercontent.com/9142587/145359680-351245de-9ee0-4bae-81ae-f4b6a2cd132d.png)

That's after triggering the command in three separate VS Code windows...

**Comment by weinand** [comment]
@ericdrobinson do you see this problem even when debugging an unmodified "Hello World" extension (created via `yo code`)?

**Comment by oaarn** [comment]
I'm having the same issue after updating to VS Code 1.63.0. I'm running on MacOS Big Sur 11.6.1 (Darwin x64 20.6.0)

**Comment by ericdrobinson** [comment]
And I just updated VSCodium to 1.63 and started the extension via the debugger. Received the same issue:

![image](https://user-images.githubusercontent.com/9142587/145459905-92deac9b-3846-4157-a767-93917a5978e8.png)

**Comment by ericdrobinson** [comment]
Okay, I just ran through the extension with the debugger. The extra Dock icon is spawned when the first **API call into the native node framework** is triggered. When I stepped over that call, the Dock icon appeared and started its merry jig.

**Comment by oaarn** [comment]
@ericdrobinson I'm not 100% sure whether native code is being used. But it does appear to be loading a debugger into the extension host. I've narrowed down the problem plugin for me to the [Adobe ExtendScript Debugger](https://marketplace.visualstudio.com/items?itemName=Adobe.extendscript-debug) extension. 
The second dock icon appears when it is loaded, the line from the extension host log looks like such:
`[2021-12-09 15:37:21.207] [exthost] [info] ExtensionService#_doActivateExtension Adobe.extendscript-debug, startup: false, activationEvent: 'onLanguage:javascript'`

**Comment by ericdrobinson** [comment]
@oaarn Heh. The debugger you're referring to there is the V1 version of the debugger that I'm actually working on (creating V2).

It is exceedingly likely that the source of the issue is the same - that when the ExtendScript core library (a native lib) is first called into, the Extension Host's process somehow spawns a Dock icon...

**Comment by ericdrobinson** [comment]
While I don't have permission to provide public access to the V2 beta package for the ExtendScript Debugger, it seems that the V1 package (which is available on the Marketplace) triggers the same issue.

@weinand @deepak1556 This very likely will reproduce for you if you install the [ExtendScript Debugger](https://marketplace.visualstudio.com/items?itemName=Adobe.extendscript-debug) extension from the marketplace and activateit.

**Comment by deepak1556** [comment]
Thanks for narrowing down the issue, I can confirm the issue on my end with the extension installed.

**Comment by weinand** [comment]
@ericdrobinson  please note that native Node.js extension (aka "native modules") are compiled against a specific version of node.js which most likely is not the same as the node.js version VS Code uses to run extensions. So we do not recommend this.
If you really need native code, you are better off running your debug adapter as a separate process where you have control over the node.js runtime.

**Comment by ericdrobinson** [comment]
@weinand I appreciate the warning. We are currently only targeting NodeJS's N-API which, since version 8.12.0, has been [guaranteed to be forward compatible](https://nodejs.org/en/docs/guides/abi-stability/):

> A given version _n_ of N-API will be available in the major version of Node.js in which it was published, and in all subsequent versions of Node.js, including subsequent major versions.

Indeed, this is confirmed in their [Version Matrix documentation](https://nodejs.org/api/n-api.html#node-api-version-matrix).

We also haven't run into any issues for over two years of advancements. The latest version available on the marketplace was built in July, 2019, back in the VSCode 1.36/1.37 days. It was built against a version of Node.js@10. It still works just fine. The N-API forward compatibility promise seems to hold.

Is there something else that you're referring to here?

**Comment by Jordan-Eckowitz** [comment]
> I'm having the same issue after updating to VS Code 1.63.0. I'm running on MacOS Big Sur 11.6.1 (Darwin x64 20.6.0)

Same same (versions and OS)

**Comment by ericdrobinson** [comment]
> Same same (versions and OS)

@Jordan-Eckowitz Which extension are you using that causes this?

**Comment by philsherry** [comment]
I've currently got 5 VS Code projects open and this is what my Dock looks like. Full-length image to show the context menu, but also the dividing line in the Dock—of which they’re on the running apps side, not the recently run side (as I saw mentioned elsewhere in some closed Issues).

![dock-github](https://user-images.githubusercontent.com/272769/146175375-99a66504-758b-4366-b171-c0084c415645.jpg)

Right-clicking any of those shows “Application not responding” between Options and the list of recent Project folders. I do not get this behaviour with the latest version of Insiders. 

I'm running macOS 12.1 (21C52) and these are my VS Code details:
```log
Version: 1.63.1
Commit: fe719cd3e5825bf14e14182fddeb88ee8daf044f
Date: 2021-12-14T02:13:13.580Z (1 day ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0
```

This is causing mayhem in my neurodivergent brain.  🔥🧠🔥

**Comment by Jordan-Eckowitz** [comment]
> > Same same (versions and OS)
> 
> @Jordan-Eckowitz Which extension are you using that causes this?

@ericdrobinson I'm not sure how to tell which extensions are causing this - I can export my full extension list for you if you'd like

**Comment by jaydenwindle** [comment]
After running into this issue, I was able to determine which extension was causing the extra dock icons by doing the following:

1. Disable all extensions and reload VSCode
2. Enable extensions one-by-one, reloading if required
3. Immediately after enabling the extension causing this issue, the extra dock icons will appear

In my case, [Spell Right](https://marketplace.visualstudio.com/items?itemName=ban.spellright) was the culprit. After uninstalling the extension and reloading VSCode, the extra dock icons were gone.

**Comment by philsherry** [comment]
@jaydenwindle 💪 Solid investigative work there. That fixed the issue for me, too. Seems there are multiple issues about it over on that repo. 

https://github.com/bartosz-antosik/vscode-spellright/issues/465

**Comment by NorthboundTrain** [comment]
Is this SpellRight's issue to fix or a base VS Code bug, or perhaps it's not yet known?

**Comment by ericdrobinson** [comment]
> Is this SpellRight's issue to fix or a base VS Code bug, or perhaps it's not yet known?

It's a VS Code bug. As I understand the problem, this would only become a SpellRight (among other extensions) issue if the VS Code team decided that the extension system no longer supported N-API altogether.

**Comment by rben01** [comment]
> After running into this issue, I was able to determine which extension was causing the extra dock icons by doing the following:
> 
> 1. Disable all extensions and reload VSCode
> 2. Enable extensions one-by-one, reloading if required
> 3. Immediately after enabling the extension causing this issue, the extra dock icons will appear
> 
> In my case, [Spell Right](https://marketplace.visualstudio.com/items?itemName=ban.spellright) was the culprit. After uninstalling the extension and reloading VSCode, the extra dock icons were gone.

You can shorten this process from O(n) to O(log(n)) by *bisecting* your extensions; the command is "start extension bisect"

**Comment by hazarek** [comment]
all plugins are disabled and still the new icon is bouncing when open a file with terminal in same workspace.

**Comment by hazarek** [comment]
> After running into this issue, I was able to determine which extension was causing the extra dock icons by doing the following:
> 
> 1. Disable all extensions and reload VSCode
> 2. Enable extensions one-by-one, reloading if required
> 3. Immediately after enabling the extension causing this issue, the extra dock icons will appear
> 
> In my case, [Spell Right](https://marketplace.visualstudio.com/items?itemName=ban.spellright) was the culprit. After uninstalling the extension and reloading VSCode, the extra dock icons were gone.

All extensions are disabled and the new icon is still bouncing when a file is opened with the terminal in the same workspace. disappears in a few seconds

**Comment by temocj** [comment]
Is this the same issue that's causing multiple icons to appear in the "recent apps" section for me?

<img width="233" alt="Screenshot 2022-03-11 at 18 21 32" src="https://user-images.githubusercontent.com/68073709/157927676-aed49062-4cfa-4d9f-9419-8824206c0335.png">

This happens every time I run `code some-folder` from Terminal and I have tried disabling all extensions. The extension bisect feature doesn't actually exhibit the issue for me.

macOS 12.2.1 and VS Code v1.65.2

**Comment by TylerADavis** [comment]
I just began seeing these same symptoms the last few weeks, though I am not sure of the source. The issue persists even if I do `code --disable-extensions .`

**Comment by deepak1556** [comment]
We have changed the architecture of extension host since the issue was created, refs https://code.visualstudio.com/updates/v1_75#_utility-process-for-extension-host.
