### ISSUE TITLE
Terminal: backslash sometimes blocks input

### ISSUE THREAD

**Issue by Urkallinger** [microsoft/vscode#138726]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
1.63.0

- OS Version:
Windows 10 (21H1, Build 19043.1348)

Steps to Reproduce:
* start vs code
* open terminal (cmd.exe)
* enter backslash
* press backspace
* Expectation: Backslash will be deleted
* Actual: backslash is not deleted. only after another press of backspace the backslash is deleted

* The same problem occurs when using the arrow keys.

https://user-images.githubusercontent.com/20026149/145375171-09b30daa-5e55-4fa5-916d-5eb91ec58879.mp4

**Comment by TTSPhilipp** [comment]
The same problem occurs when using a ~ character.
