### ISSUE TITLE
How to install extensions in visual studio code either from command or extension api

### ISSUE THREAD

**Issue by shanalikhan1** [Microsoft/vscode#1387]
Hi
How to install visual studio code extension from command prompt if i have ID or complete accurate name or any other identifier. or how i can install extension from vscode API.

**Comment by joaomoreno** [comment]
Neither of those are possible for now.

**Comment by shanalikhan1** [comment]
Is this in your roadmap ? it would be good to add as im making extension for sync settings and only extension sync is remaining.

**Comment by joaomoreno** [comment]
ping @chrisdias

**Comment by chrisdias** [comment]
@joaomoreno can we make this issue a feature request and put on the backlog?  the scenario is that i want to create a service which roams my extensions across machines.  I need a way to install the set of extensions outside of VS Code, or within VS Code but by calling some sort of API.

**Comment by shanalikhan1** [comment]
@chrisdias i have found a way check out extension named at visual studio code settings sync.
But it would be a good rather then all the things im doing manually externally the api should do the only input i should be providing some unique name or ID

**Comment by chrisdias** [comment]
exactly, you should not have to recreate what the tool does when installing and uninstalling an extension.
