### ISSUE TITLE
Code CLI open file somewhat slow

### ISSUE THREAD

**Issue by meandmymind** [microsoft/vscode#138747]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.62.3
- OS Version: MacOS Monterey 12.0.1
- Macbook pro 2019 6 i7
- zsh (also reproduced with bash)

Steps to Reproduce:

1. open terminal (external or integrated)
2. code file.txt
3. it takes 2-3 seconds to focus on vscode file editor view

**Comment by bpasero** [comment]
Is VSCode already running or not?

**Comment by meandmymind** [comment]
@bpasero yes

**Comment by bpasero** [comment]
> it takes 2-3 seconds to focus on vscode file editor view

Can you setup VSCode to be visible on the screen at the same time as the terminal and measure if the actual editor opening is 2-3s slow or the window getting focus.

**Comment by meandmymind** [comment]
> at the same time as the terminal 

It is reproducible both in external terminal and integrated terminal. here is vid

https://user-images.githubusercontent.com/24773652/146206167-83720feb-38eb-4f59-928b-6003193c79d6.mp4

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by meandmymind** [comment]
It's still reproducible

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
