### ISSUE TITLE
macOS: Multiple icons vscode / monterey when switching applications with cmd-tab

### ISSUE THREAD

**Issue by pgundlach** [microsoft/vscode#138722]
Does this issue occur when all extensions are disabled?: No

When I deactivate the extension `ban.spellright` everything seems to work as normal.

```
Version: 1.63.0
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T05:15:48.091Z (2 days ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```

- OS Version: 12.0.1 (21A559)

Steps to Reproduce:

1. Open code on the command line by typing in  `code` or by starting it from the Gui
2. Enable the extension `ban.spellright` (Spell right)
2. Open another window
3. Multiple icons appear when pressing cmd-tab to change applications. One for each open window, so it seems.

<img width="1087" alt="tabicons" src="https://user-images.githubusercontent.com/209434/145369469-bd594c5b-f959-43aa-8666-46973c76847e.png">

**Comment by weyert** [comment]
Yes, I am having the same issue. Shows multiple icons in the Dock or `cmd-tab` when having one window but multiple tabs

**Comment by grahamannett** [comment]
Yeah I was trying to figure this out today as well.  Seems like it is extension related based on doing a clean install but besides going through and checking each I am not sure how to diagnose which one.

**Comment by 6twenty** [comment]
In my case the other icons are also showing in the dock, as well as in the app switcher, and save for the "main" one, the others show as not responding.

<img width="681" alt="image" src="https://user-images.githubusercontent.com/169607/145498234-ae3e0992-197f-47e3-b41a-598768372909.png">

**Comment by pgundlach** [comment]
> Yeah I was trying to figure this out today as well. Seems like it is extension related based on doing a clean install but besides going through and checking each I am not sure how to diagnose which one.

@grahamannett  There is the command 'Help: start extension bisect' which would help you in this case.

**Comment by dskecse** [comment]
By running the "Help: start extension bisect" command I've managed to figure out the extension that's causing the problem was [`ban.spellright`](https://github.com/bartosz-antosik/vscode-spellright/issues/465) indeed and I've already reported the issue there

![Screenshot 2021-12-10 at 16 00 59](https://user-images.githubusercontent.com/1451690/145578856-7f2e2de8-12e3-471d-a917-d420ae6f2637.png)

**Comment by younho9** [comment]
This issue is also reproduced in Big Sur. I uninstalled `ban.spellright` and it was solved.

**Comment by carlosfrodriguez** [comment]
+
