### ISSUE TITLE
Attached file won't open in vscode

### ISSUE THREAD

**Issue by ulvtro** [Microsoft/vscode#13870]
[Vinduer.zip](https://github.com/Microsoft/vscode/files/532576/Vinduer.zip)

- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: donjayamanne.python-0.3.24, robertohuertasm.vscode-icons-3.0.0, Tyriar.sort-lines-1.1.0, wmaurer.change-case-0.4.1

Steps to Reproduce:

1. Open the attached file in vscode
2. Message: "The file will not be displayed in the editor...". It works fine in Sublime and TextPad.

**Comment by bpasero** [comment]
@ulvtro the file seems to be encoded with UTF-16 but not using a BOM. We can only show UTF-16 if the file is saved with a BOM. See http://unicode.org/faq/utf_bom.html
