### ISSUE TITLE
Setting "Editor › Unicode Highlight: Ambiguous Characters" doesn't work as advertised

### ISSUE THREAD

**Issue by emptyVoid** [microsoft/vscode#138767]
Issue Type: <b>Bug</b>

1. Create a C++ source file in utf-8 encoding.
2. Add a cyrillic string literal.

Actual results:
VSCode highlights every latin-looking cyrillic character.

Expected results:
Cyrillic characters should not be highlighted.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

Here's the setting's description:
![image](https://user-images.githubusercontent.com/13639229/145428054-d8270d93-4986-468f-9364-94d21a9deb60.png)

Here's my locale:
![image](https://user-images.githubusercontent.com/13639229/145428184-57b55a32-088b-4fc9-9ffc-6653ed2958b0.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz (16 x 2998)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (16.99GB free)|
|Process Argv|--crash-reporter-id 6348721a-3924-4e1c-9ad8-0a5c0f7d4f8a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
systemd-unit-file|coo|1.0.6
gitlens|eam|11.7.0
openssl-configuration-file|gee|0.0.1
doxygen-previewer|hak|0.2.3
saltstack|kor|0.0.9
vscode-cudacpp|kri|0.1.1
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.12.0
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.3
remote-ssh|ms-|0.68.0
remote-ssh-edit|ms-|0.68.0
remote-wsl|ms-|0.63.4
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
powershell|ms-|2021.10.2
vscode-typescript-tslint-plugin|ms-|1.3.3
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.10
code-spell-checker|str|2.0.13
code-spell-checker-russian|str|2.0.1
cmake|twx|0.0.17
sort-lines|Tyr|1.9.0
markdown-all-in-one|yzh|3.4.0
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932cf:30408637
vscop804:30404766
vs360:30404995
vsrem710:30405998
vscexrecpromp3t3:30407764

```

</details>

**Comment by hediet** [comment]
@emptyVoid thanks for reaching out!
What is your current VS Code display language?

![image](https://user-images.githubusercontent.com/2931520/145544102-493fac95-55cf-4484-81dd-9e3c8815b814.png)

Also, can you share some code examples?

**Comment by emptyVoid** [comment]
It's English.
![image](https://user-images.githubusercontent.com/13639229/145545210-cfda5fdd-bf4b-4528-9c32-5ba33f8dfcf5.png)

Here's a code sample:
```c++
#include <cstdlib>

auto some_cyrillic_text = "просто текст кириллицей";

int main() { return EXIT_SUCCESS; }
```

**Comment by hediet** [comment]
Thanks!

It should work when you install a russian VS Code language pack and select it as display language for VS Code.

Probably the unicode highlighting locale should be overridable, independent of the VS Code locale.
Alternatively, the unicode highlighting locale should be derived from the OS, not from the language selected in VS Code.

**Comment by emptyVoid** [comment]
> It should work when you install a russian VS Code language pack and select it as display language for VS Code.

I've guessed as much.

> Probably the unicode highlighting locale should be overridable, independent of the VS Code locale.

I think it would be great to be able to add character sets to the ignore list. (e.g. entire Greek and entire Cyrillic alphabet).

> Alternatively, the unicode highlighting locale should be derived from the OS, not from the language selected in VS Code.

IMO this should be the default.

**Comment by hediet** [comment]
VS Code insiders now allows to configure a list of locales. Common characters used by that locale are not highlighted. By default, the OS and VS Code locale are included in that list. `"editor.unicodeHighlight.allowedLocales"` can be used to override this list:
```json
"editor.unicodeHighlight.allowedLocales": {
    "_os": true,
    "_vscode": true
},
```

Also, when clicking on "adjust settings" when hovering on a highlighted character, there is new an option to include the relevant language in `allowedLocales`:
![image](https://user-images.githubusercontent.com/2931520/149798944-bc07db24-a9b9-412c-bcc1-b2be37e1602a.png)

**Comment by yyjdelete** [comment]
> VS Code 内部人员现在允许配置区域设置列表。在任何这些区域设置中常见的字符都不会突出显示。默认情况下，OS 和 VS Code 区域设置包含在该列表中。 可用于覆盖此列表：`"editor.unicodeHighlight.allowedLocales"`
> 
> ```json
> "editor.unicodeHighlight.allowedLocales": {
>     "_os": true,
>     "_vscode": true
> },
> ```
> 
> 此外，当将鼠标悬停在突出显示的字符上时单击"调整设置"时，有一个新的选项可以包含以下语言：`allowedLocales` ![图像](https://user-images.githubusercontent.com/2931520/149798944-bc07db24-a9b9-412c-bcc1-b2be37e1602a.png)
> 
> 请注意，这仅适用于[vscode-loc](https://github.com/microsoft/vscode-loc)中的语言。

But since there is another setting `editor.unicodeHighlight.nonBasicASCII`, which is `inUntrustedWorkspace` by default, it still highlight everything in user locale for untrusted workspace. And make it strange for people which vscode just as an text editor.

**Comment by hediet** [comment]
> it still highlight everything in user locale for untrusted workspace.

This is by design to provide a safe environment for code review. You can disable that feature though.

**Comment by yyjdelete** [comment]
It just make every people disable it.

**Comment by johnk005297** [comment]
> 

Did you figure out how to fix this issue ? I have the same, and it's really innoying.

**Comment by johnk005297** [comment]
@hediet disabled Unicode Highlight: Ambiguous characters. Worked for me.
