### ISSUE TITLE
Broken "Open With Code" Shell Extension

### ISSUE THREAD

**Issue by christopherecusack** [microsoft/vscode#138739]
Since the last update, I have experienced this issue. Reinstall did not fix the problem. Note the VSCode icon no longer displays in the context menu...

![vscode-err1](https://user-images.githubusercontent.com/74408884/145382185-c86f7e3d-f773-465f-8426-cb356b868cf2.png)

![vscode-err2](https://user-images.githubusercontent.com/74408884/145382203-c4054c28-e162-46d2-a470-5b00cf5196af.png)

**Comment by gjsjohnmurray** [comment]
When you reinstalled did you set the checkbox(es) to get VS Code shortcuts added to your context menu?

**Comment by christopherecusack** [comment]
Hello John. Thanks for replying. When re-installing the options were checked and the options still were not there but the latest update I ran seems to have fixed my issue. All good on my end. Thank you.
