### ISSUE TITLE
Terminate batch jobs (Y/N) hangs VS Code tests

### ISSUE THREAD

**Issue by abahocodes** [microsoft/vscode#138791]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.0
- OS Version: Windows 10 MMS-2019

Steps to Reproduce

This issue must be executed via `vscode-test` and the steps to reproduce are in the [linked issue](https://github.com/microsoft/vscode-test/issues/111) in `microsoft/vscode-test`. The main reason this issue is duplicated here is that the aforementioned issue is only present with VS Code Version 1.63.0 on Windows.

**Comment by connor4312** [comment]
Tracking on https://github.com/microsoft/vscode-test/issues/111
