### ISSUE TITLE
Switching between terminal tabs always requires double-click (even if single click is configured)

### ISSUE THREAD

**Issue by vasilev-alex** [microsoft/vscode#138716]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.0
- OS Version: macOS Monterey 12.0.1

Steps to Reproduce:

1. Open 2 Terminal tabs
2. Single click on a tab doesn't bring you to the selected terminal when `Terminal > Integrated > Tabs: Focus Mode` is `singleClick`

This issue has already been raised #128254 but was tagged as not reproducible despite multiple people experience the same problem.

https://user-images.githubusercontent.com/4973437/145361690-e342b2ad-433e-4095-8bd6-4a7bbc6e2d84.mov

**Comment by Tyriar** [comment]
Can't repro on Windows.

**Comment by meganrogge** [comment]
Can't repro on macOS Monterey. what are your other settings and have you tried disabling all extensions?
![recording (21)](https://user-images.githubusercontent.com/29464607/146405180-859054f0-e680-45a5-b7cd-7161ec7a3eb6.gif)

**Comment by Tyriar** [comment]
@vasilev-alex can you share your full settings.json file? Maybe there's a conflict with some other setting we've not using

**Comment by vasilev-alex** [comment]
@Tyriar you're right. It's because of

```
"workbench.list.openMode": "doubleClick"
```

I toggle folders in the Explorer with a `double` click and looks like these two settings conflict with each other. Does it look like a bug?

**Comment by Tyriar** [comment]
@vasilev-alex perfect! Looks like we can handle this properly by ignoring that setting and forcing "single click opening" all the time for the terminal as that's what it's meant to do.
