### ISSUE TITLE
Since last update all tags in html appear in red

### ISSUE THREAD

**Issue by solondon** [Microsoft/vscode#13873]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: abusaidm.html-snippets-0.0.17, anseki.vscode-color-0.1.11, dbaeumer.jshint-0.10.15, donjayamanne.githistory-0.1.0, donjayamanne.python-0.4.2, DotJoshJohnson.xml-1.6.0, HookyQR.beautify-0.4.1, lonefy.vscode-JS-CSS-HTML-formatter-0.2.1, ms-vscode.csharp-1.4.1, ms-vscode.Theme-TomorrowKit-0.1.3, msjsdiag.debugger-for-chrome-1.2.1, robertohuertasm.vscode-icons-3.0.5, Zignd.html-css-class-completion-1.0.3

Steps to Reproduce:

1. Open any html document
2.

**Comment by aeschli** [comment]
@solondon What color theme are you using?

**Comment by solondon** [comment]
Tommorow night Bright. I have replicated setup on another pc same files and addons and they work, I cant work out what the difference is. Thanks for the response

**Comment by aeschli** [comment]
The underlying grammar has changed that creates the syntax highlighting tokens. We are now using standard text mate grammar, generated scopes should be similar, but changes can occur. Looks like the Tommorow night Bright color theme is sensitive to these change.
Nothing I can do from our side, we are not authoring neither the grammar not the color theme.

**Comment by solondon** [comment]
thanks for taking the time to look and reply, that does appear to be the issue. Cant work out why its ok on the other machine, but at least I have  a workaround now. Many thanks
