### ISSUE TITLE
Custom configuration with extension testing

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#13871]
- VSCode Version: 1.6.1
- OS Version: macOS Sierra

From https://github.com/SamVerschueren/vscode-final-newline/issues/12#issuecomment-254127218

I want to test my extension. The extension only activates when the setting `files.insertFinalNewline` is set to `true`. But how can I do this while testing the extension? It doesn't seem you can launch the Extension Host with preconfigured custom settings. Also their doesn't seem to be an utility function to do this.

**Comment by bpasero** [comment]
You can open the extension host on a folder that contains a .vscode folder with a settings.json file that contains this setting. Otherwise you could have another extension that writes to the setting with the new config update API we provide.

**Comment by SamVerschueren** [comment]
> writes to the setting with the new config update API we provide.

That's what I needed! Thanks for elaborating. I want to easily test with multiple configurations without having the need to create multiple fixtures.
