### ISSUE TITLE
Breakpoint decorations sometimes don't disappear

### ISSUE THREAD

**Issue by kycutler** [microsoft/vscode#138789]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.0
- OS Version: Windows 11

Steps to Reproduce:

1. Open a file where breakpoints can be set
2. Hover around the edge of the editor, in and out of the margin until the breakpoint stays even though the mouse is outside of the editor (see GIF below).

![monacodecorationbug](https://user-images.githubusercontent.com/67761731/145471307-fe865982-412d-4440-aa7a-baf8c180120b.gif)

This is important to me because I am using margin decorations in Monaco and running into the same issue there.

Internally the `onMouseLeave` event isn't triggered, so the decorations aren't removed. It seems to be specific to decorations in the glyph margin, as without these (e.g. line decorations) it doesn't seem to reproduce.

**Comment by alexdima** [comment]
I can reproduce when moving the mouse quickly. I find it interesting that also the scrollbars suffer form the same problem (the scrollbars listen independently to `mouseout`). I've also tried locally to replace `mouseout` with the somewhat more modern `mouseleave` and I could still reproduce. Basically the browser simply forgets soemtiems to send us a `mouseleave` or a `mouseout` event:

<img width="538" alt="image" src="https://user-images.githubusercontent.com/5047891/175542116-2d21e31b-d82a-489e-8da4-0b94b1eebce8.png">
