### ISSUE TITLE
Argument hints should show all the time inside parens, not only when first opening them

### ISSUE THREAD

**Issue by intellix** [microsoft/vscode#138755]
When in TypeScript if you open parens, you’re shown the arguments and which position you’re on. If you click away and click back into those parens… or just go to any other method to start adding arguments, you’re never shown the same tooltip for which arguments a method takes, ever again. This leads me to just starting again, so I can see that tooltip again:

**Upon opening parens:**
<img width="701" alt="Screenshot 2021-12-09 at 12 06 49" src="https://user-images.githubusercontent.com/1162531/145401214-51ea31a1-20cf-485e-bab9-a72e67220093.png">

**After clicking away, and going back into the parens.... or if I just open a new file and click into them to edit them:**
<img width="1004" alt="Screenshot 2021-12-09 at 12 07 00" src="https://user-images.githubusercontent.com/1162531/145401289-de969e7e-095a-444d-9b45-16c01c3e737b.png">

**Comment by mjbvz** [comment]
You can use use the `trigger parameter hints` command to manually show these hints again. The default Mac keybinding is shift+cmd+space

**Comment by intellix** [comment]
ahah, i did not know that existed at all. Is there any reason it's not just the default and provided by CTRL+Space suggestions? The suggestions in the screenshot are useless and can't think of any reason to use that here
