### ISSUE TITLE
Publish fails with a cryptic error message

### ISSUE THREAD

**Issue by yecril71pl** [microsoft/vscode#138742]
Issue Type: <b>Bug</b>

When no git repo is configured, the command GitHub Publish fails with a cryptic error message: "State not found in accepted state. Skipping this execution..."

Extension version: 0.32.0
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.15.5-1-default
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz (4 x 2393)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|5.66GB (0.17GB free)|
|Process Argv|--unity-launch --crash-reporter-id 2a03cb52-9f4b-48bf-93d3-5c0537d534ee|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma5|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
vscop804cf:30404767
vscop940:30404999
vsrem710:30405998

```

</details>

**Comment by lszomoru** [comment]
Seems to be the GitHub Authentication extensions. @TylerLeonhardt, could you please take a look? Thanks!

**Comment by yecril71pl** [comment]
This happens in a fresh unauthenticated **Code** environment when the current folder is not associated with [GitHub](https://github.com/) either.  Once you have authenticated, the problem goes away.  The problem also goes away when you are in a folder already linked to [GitHub](https://github.com/); **Code** detects you are a nobody and correctly instructs you to authenticate; this authentication persists forever afterwards.

**GitHub Publish** should enter the same authentication dance when invoked with no context.  Currently it fails miserably, leaving an unintelligible message in an output section that is hard to find (does not pop up).

**Comment by TylerLeonhardt** [comment]
Unfortunately, I can't seem to repro what you're seeing :(

https://user-images.githubusercontent.com/2644648/148827630-dfb0fbde-8ca8-43ae-8851-6916efce7d6b.mp4

**Comment by yecril71pl** [comment]
I do not know how to reproduce it now because I already have the token.

**Comment by TylerLeonhardt** [comment]
you can sign out again from the Account menu in the bottom left:
![image](https://user-images.githubusercontent.com/2644648/148844814-f9bf6e4b-bb9f-4a24-9252-44afdd02d9c5.png)

**Comment by yecril71pl** [comment]
I confirm the intended behaviour after logging out.  I still think that the state after logging out is different from the state before logging in for the first time.

**Comment by TylerLeonhardt** [comment]
I've tried this a few time in fresh containers and haven't seen it.

Let me know if you see this again and we can try to debug further.
