### ISSUE TITLE
Merge conflict comments does not appear

### ISSUE THREAD

**Issue by booster085** [microsoft/vscode#138753]
For already 2 months, I can't resolve conflicts in vs code because the merge editor does not appear at all. Vs code merges the files partially by its own in some way and I can only see the red exclamation mark for conflict in the file. And few more colleagues have the same issue.

**Comment by booster085** [comment]
![Inked13123131_LI](https://user-images.githubusercontent.com/10547232/145398815-ff372927-7556-4d1c-a2ee-b2874e412fca.jpg)

**Comment by chrmarti** [comment]
There should be textual markers from Git for the merge conflicts. Could you try closing all files and then opening the package.json from the Explorer viewlet?
