### ISSUE TITLE
Styling loss of entire file

### ISSUE THREAD

**Issue by akash-kony** [Microsoft/vscode#13874]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: gerane.Theme-ChromeDevTools-0.0.2, gerane.Theme-Github-0.0.2, gerane.Theme-Xcodedefault-0.0.2, HookyQR.beautify-0.2.1, saviorisdead.Theme-GitHubCleanWhite-0.0.3, SintrumIT.theme-oceanic-next-italic-1.1.14, ullissescastro.theme-bracketslight-1.0.2, zhuangtongfa.Material-theme-0.0.1

Steps to Reproduce:

1. Create javascript file
2. Write code in the following way - 
```javascript
var i = 0;
for(; i<selectedindex.length -1; i++) {
  data = data[selectedindex[i]].children;
}
```
Note that selectedindex, data are defined in my code.
3. After this syntax all code following it will be single color.

**Comment by waderyan** [comment]
@akash-kony thank you for opening this issue. Your code as an unintentional syntax error. 

If you add a greater than symbol `>` then the syntax highlighting will behave properly. 

```
var i = 0;
for(; i<selectedindex.length > -1; i++) {
  data = data[selectedindex[i]].children;
}
```

Possibly you were aware of this. VS Code did not handle the error case very well. @aeschli do you have any thoughts here? Is this an issue for the new grammar? I checked this with the old and the new grammar and the behavior was similar.

**Comment by akash-kony** [comment]
Hi waderyan,
It is a valid js code, with no syntax errors (chrome) - and does work as well.
Intention was to run the loop from 0 to length - 1
Even if the space after .length is removed - theme works.

```javascript
//GOOD
var i = 0;
for(; i<selectedindex.length-1; i++) {
  data = data[selectedindex[i]].children;
}

//BAD
var i = 0;
for(; i<selectedindex.length -1; i++) {
  data = data[selectedindex[i]].children;
}
````

Appreciate your work, great product.

Thanks,
Akash

**Comment by waderyan** [comment]
Whoops. Misread the code. Thank you for the clarification.

**Comment by waderyan** [comment]
This is definitely a grammar issue then. Migrating to that repo.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#319
