### ISSUE TITLE
Terminal is not openning

### ISSUE THREAD

**Issue by NeilSayok** [microsoft/vscode#138774]
Issue Type: <b>Bug</b>

Terminal is not openning 

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (3.31GB free)|
|Process Argv|--crash-reporter-id 451565f9-f3cb-483b-b6cc-6efe3be85373|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-database-client2|cwe|4.3.3
githistory|don|0.6.19
es7-react-js-snippets|dsz|3.1.1
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|9.0.0
code-runner|for|0.11.6
copilot|Git|1.7.4016
ftp-simple|hum|0.7.6
intellij-idea-keybindings|k--|1.5.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.12.0
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-wsl|ms-|0.58.5
cpptools|ms-|1.7.1
material-icon-theme|PKi|4.11.0
vscode-thunder-client|ran|1.9.1
java|red|1.1.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.19.0
vscode-java-test|vsc|0.33.0
vscode-maven|vsc|0.34.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932cf:30408637
vscop804cf:30404767
vs360cf:30404996
vsrem710:30405998
vscexrecpromp3c:30407761

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" terminal

**Comment by NeilSayok** [comment]
Issue fixed on reinstalling vs code
