### ISSUE TITLE
Why I was locked as spam, even though my bug was legitimate?

### ISSUE THREAD

**Issue by JakubDrozd** [microsoft/vscode#138775]
#136510 HI, I was locked as spam by microsoft, even though my issue was legitimate. Sorry for the insistence to fix the issue quickly. I apologize for the comments, and please, Microsoft, unlock the conversation. I will be very grateful.

**Comment by IllusionMH** [comment]
You weren't locked as spam, only comments that request things and doesn't provide useful information to help fix issue were marked as spam. Issue is locked as it contains all necessary info to implement it.

Is there any additional info that can help resolve that issue?

**Comment by Tyriar** [comment]
Every comment triggers a notification to whoever has interacted with the issue as well as anyone watching the repository:
![image](https://user-images.githubusercontent.com/2193314/145466667-e6275808-9391-444b-975b-2c5f23644ce4.png)

You were commenting too much about things that didn't matter, like how we label issues. It's now unlocked, but please avoid commenting unless there is something that would help solve the issue. Also avoid asking why this isn't fixed or bumping the issue, this is one minor issue in a minor feature among over 5000 tracked in the repo.

**Comment by JakubDrozd** [comment]
But I already apologised!
