### ISSUE TITLE
"Settings Sync: Select Service" not present in Insiders command pallet

### ISSUE THREAD

**Issue by samjewell** [microsoft/vscode#138772]
Issue Type: <b>Bug</b>

I want to sync my settings from Insiders to VSCode, and I found this section of the docs:

https://code.visualstudio.com/docs/editor/settings-sync#_syncing-stable-versus-insiders

They refer to a "Settings Sync: Select Service" option. I searched for this option in the command pallet, but couldn't find it - it seems to be missing to me.

Thanks

VS Code version: Code - Insiders 1.64.0-insider (68976705968229accd11fdfe1cba36a908208dc9, 2021-12-09T05:14:18.136Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id d6b55923-ea5b-4116-93ff-b1744deac02c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.0.0
codespaces|Git|1.4.1
copilot|Git|1.7.4016
go|gol|0.29.0
terraform|has|2.17.0
jsonnet-language|lia|1.0.0
rainbow-csv|mec|1.10.1
vscode-docker|ms-|1.18.0
remote-containers|ms-|0.209.3
remote-ssh|ms-|0.68.0
remote-ssh-edit|ms-|0.68.0
remote-wsl|ms-|0.63.4
vscode-remote-extensionpack|ms-|0.21.0
sublime-keybindings|ms-|4.0.10
vsliveshare|ms-|1.0.5196
vscode-commons|red|0.0.6
python|tht|0.2.3
markdown-all-in-one|yzh|3.4.0
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedc:30350118
pythonvspyt187:30365360
vsaa593cf:30376535
vsc1dst:30396469
pythonvs932:30404738
vscop804:30404766
vs360cf:30404996
vsclayoutctrt:30405800
py55gd98:30408621
vscexrecpromp3t1:30407758
azactmsal:30409287

```

</details>

**Comment by sandy081** [comment]
You can select service only while turning on settings sync, as written in the doc

```
You can sync your Insiders with Stable by selecting the Stable sync service while turning on Settings Sync. This option is only available in VS Code Insiders.
```

So, please turn off and turn on sync again.

**Comment by samjewell** [comment]
@sandy081 ok thanks, you are right, that was written in the text of that help article - many thanks for your help.

I wonder if the docs could be improved with more imagery, or more context on the image which is already included, in order to make it clearer that you can't simply change that setting directly via the command pallet.

In combination with another issue which I reported on Zendesk: https://support.github.com/ticket/1421927 this problem caused me a lot of pain and time wasted.

**Comment by sandy081** [comment]
Thanks for the feedback.

Definitely, I will wait until I listen more feedback before doing any changes.
