### ISSUE TITLE
Fullwidth characters are not highlighted as ambiguous (confusable) characters

### ISSUE THREAD

**Issue by mandel59** [microsoft/vscode#138746]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.0
- OS Version: macOS Monterey 12.0.1
- Locale: `en` and `ja`

Steps to Reproduce:

1. Input the following code:

```javascript
`
！＂＃＄％＆＇（）＊＋，－．／
０１２３４５６７８９：；＜＝＞？
＠ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯ
ＰＱＲＳＴＵＶＷＸＹＺ［＼］＾＿
｀ａｂｃｄｅｆｇｈｉｊｋｌｍｎｏ
ｐｑｒｓｔｕｖｗｘｙｚ｛｜｝～
`
```
2. Change language mode to JavaScript.

Expected result:
- All fullwidth characters are highlighted.
- A tooltip shows its counterpart character.

Actual result:
- Some characters are not highlighted.

<img width="245" alt="スクリーンショット 2021-12-09 20 32 10" src="https://user-images.githubusercontent.com/1079715/145388936-6e9c2c19-9954-45a3-baa9-c5b8fbff711d.png">

- Some tooltips show characters not so similar.
    - > The character U+ff3b "［" could be confused with the character U+0028 "(", which is more common in source code.
    - > The character U+ff3d "］" could be confused with the character U+0029 ")", which is more common in source code.

<img width="536" alt="スクリーンショット 2021-12-09 20 33 42" src="https://user-images.githubusercontent.com/1079715/145389172-6e101d08-5e8e-4317-932b-5c0874c6dffc.png">

**Comment by ArturoDent** [comment]
I think your example is covered by the setting below and not the ambiguous setting:

`Editor > Unicode Highlight: Non Basic ASCII`

When I have that set to `false` or `inUntrustedWorkspace` (the default) I get your result.

If I set that to `true` I get

![unicode full width](https://user-images.githubusercontent.com/31813701/145479179-eb69dd58-9910-4ff8-906d-2efceb9d23d1.jpg)

**Comment by hediet** [comment]
Thanks for reporting your finding!

We used the data from the unicode specification ([confusables.txt](https://www.unicode.org/Public/security/14.0.0/confusables.txt)) to compute the ambiguous characters.

Interestingly, that file declares U+FF21 Fullwidth Latin Capital Letter A to be confusable with the ASCII A, but it does not declare U+FF26 Fullwidth Latin Capital Letter F to be confusable with the ASCII F.
This is unfortunate and makes me question the reliability of the unicode data.

---

> Editor > Unicode Highlight: Non Basic ASCII

This is the last resort, that we introduced exactly for cases like this.
It just highlights every non (basic) ASCII character, whether it can be confused with an ASCII character or not.

**Comment by IanMatthewHuff** [comment]
Looks good here, but there is the one backtick character before the 'a' that wasn't getting flagged:
![image](https://user-images.githubusercontent.com/812783/151270002-5bb90c25-ea96-46da-bb55-b761afc2acb9.png)
Took a quick peek at the confusables list and it looks like it has an entry there:
`FF40 ;	0027 ;	MA	#* ( ｀ → ' ) FULLWIDTH GRAVE ACCENT → APOSTROPHE	# →‘→`

**Comment by IanMatthewHuff** [comment]
@hediet I only had time for a quick peek at the code, but I see what looks like the correct fullwidth grave accent in confusable-overrides.json. However in the ambigious-formatted.json file it looks like the entry was removed and I don't see it added back in.

**Comment by hediet** [comment]
That was a bug in the tool that generated that data. Thanks! It works now.

![image](https://user-images.githubusercontent.com/2931520/151345329-0c17459b-ea98-47a2-95df-23e3c767207d.png)
