### ISSUE TITLE
Integration test failure: Tabs - Ensure tabs getter is correct

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#138788]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=146269&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=c55167a9-8752-5898-67fa-9d7c918c61b3&l=459

```
  1 failing
  1) vscode API - window
       Tabs - Ensure tabs getter is correct:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\extensions\vscode-api-tests\out\singlefolder-tests\window.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

[Wiki: Dealing with Test Flakiness](https://github.com/microsoft/vscode/wiki/Dealing-with-Test-Flakiness)

**Comment by lramos15** [comment]
Seems to be due to notebook webview not resolving. Added retry and reduced timeout to 10seconds as this should be a quick test 
https://github.com/microsoft/vscode/commit/9ce72d28b6fc53c3c6419ea37774cf2d0e17fd76
