### ISSUE TITLE
Preserve past output after running Ctrl-L in terminal

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#13872]
- VSCode Version: 1.7 Insider
- OS: macOS 10.11.6

Currently Ctrl-L clears all output from terminal. You can't scroll up to find past output.
iTerm and gnome-terminal all handle Ctrl-L by clearing the screen while preserving output, so later you can still scroll up to find it.

**Comment by jhasse** [comment]
Works for me with VSCode 1.6.1 on Linux.

**Comment by octref** [comment]
@jhasse Thanks for letting me know! Marking this as a bug for Mac.

**Comment by Tyriar** [comment]
Discussion on what clear should do is located at https://github.com/sourcelair/xterm.js/issues/106
