### ISSUE TITLE
Grabbing sash corner moves the wrong sashes

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#138771]
Steps:
1. Open VS Code with all 3 panels/bars visible
2. Toggle side bar location twice
🐛 => drag sash corner of panel/sidebar
![recording (13)](https://user-images.githubusercontent.com/6561887/145441300-a036595c-076b-4545-a4aa-a26cbda5cc25.gif)

**Comment by joaomoreno** [comment]
Regressed due to https://github.com/microsoft/vscode/pull/137009

**Comment by joaomoreno** [comment]
Simpler repro steps:

1. Open workbench, corner sash between panel and sidebar works
2. Toggle sidebar position, 🐛 corner sash no longer works

**Comment by joaomoreno** [comment]
![image](https://user-images.githubusercontent.com/22350/145588809-bed07d97-c082-425f-b0b2-146cd923001e.png)

I knew I should never have exposed this method. 😃

**Comment by joaomoreno** [comment]
Yup, [this `+1`](https://github.com/microsoft/vscode/pull/137009/files#diff-46e51ed1ac7d85ccbcf5bb4fd6e196840a71cc267e33415121ea6e84856a4f36R243) makes it possible for `validateIndex` to return `numChildren` as the index to use, but [most](https://github.com/microsoft/vscode/pull/137009/files#diff-46e51ed1ac7d85ccbcf5bb4fd6e196840a71cc267e33415121ea6e84856a4f36L514) [grid](https://github.com/microsoft/vscode/pull/137009/files#diff-46e51ed1ac7d85ccbcf5bb4fd6e196840a71cc267e33415121ea6e84856a4f36L550) [operations](https://github.com/microsoft/vscode/pull/137009/files#diff-46e51ed1ac7d85ccbcf5bb4fd6e196840a71cc267e33415121ea6e84856a4f36L573) [can't](https://github.com/microsoft/vscode/pull/137009/files#diff-46e51ed1ac7d85ccbcf5bb4fd6e196840a71cc267e33415121ea6e84856a4f36L592) [handle](https://github.com/microsoft/vscode/pull/137009/files#diff-46e51ed1ac7d85ccbcf5bb4fd6e196840a71cc267e33415121ea6e84856a4f36L612) [that](https://github.com/microsoft/vscode/pull/137009/files#diff-46e51ed1ac7d85ccbcf5bb4fd6e196840a71cc267e33415121ea6e84856a4f36L620).

I'll leave it up to you what to do here. My suggestion would be to revert the gridview changes of https://github.com/microsoft/vscode/pull/137009, and go with my [suggestion instead](https://github.com/microsoft/vscode/pull/137009#issuecomment-967147824). We would even be able to delete the hacky `moveViewTo` method, which is only exposed for this purpose.

**Comment by sbatten** [comment]
thanks for the investigation, will think on a fix

**Comment by joaomoreno** [comment]
Maybe something like `grid.restructure(structure descriptor)` would be cool.

**Comment by benibenj** [comment]
Seems to have been fixed. Unable to repro
