### ISSUE TITLE
When focus shifts to the bug when runnig and debugging code, do not close the file that I started running the code from.

### ISSUE THREAD

**Issue by ollie-iterators** [microsoft/vscode#138779]
When I am running and debugging the code, and an error shows up on the code, the focus goes to the area with the error, and the file that I was on is closed, so I have to search for the file I was using before the error showed up to start running it again. I would like it to happen that when the focus shifts to another file based on an error, that the original file that I was on does not go away from being able to be interacted with.

**Comment by IllusionMH** [comment]
Are files that are closed have filename in italics and do you have **Workbench › Editor: Enable Preview** enabled? (`"workbench.editor.enablePreview": true`)?
