### ISSUE TITLE
Snippet suggestions are too eager

### ISSUE THREAD

**Issue by shenghui0779** [microsoft/vscode#138707]
see comment

**Comment by shenghui0779** [comment]
- `settings.json`

![image](https://user-images.githubusercontent.com/67535398/145368075-540da76d-333d-40d8-8f7f-aaf1426c0d1b.png)

- `editor`

![image](https://user-images.githubusercontent.com/67535398/145368961-66287442-188d-4dc9-9cd1-0721eee497d8.png)

There is `omitempty` in the context, but when I input `omit`, there is no suggestion in the list. It's OK on old version.

- `env`

1. windows 11
2. macOS Monterey

**Comment by max-mykhailenko** [comment]
Yea, same for me. Suggestions based on the last character, but not for the full word. It's a really big problem for me. Look at screenshot. It's just long variable name

<img width="701" alt="image" src="https://user-images.githubusercontent.com/1213198/145689176-23351744-23f8-4c90-aeca-caf711340cad.png">

**Comment by jmayoralas** [comment]
Exactly the same for me. It's like snippetSuggestions setting is ignored and only shows snippets suggestions:
![imagen](https://user-images.githubusercontent.com/20075656/145712364-0a8abd67-5671-4a5f-a369-e5fcd550f21f.png)

**Comment by jrieken** [comment]
@tomasklaen - tomorrows (14.12) insiders should have a fix for the foobar vs async case

**Comment by jrieken** [comment]
To _verify_

* make sure have snippet suggestions enabled (`editor.suggest.showSnippets: true`)
* open `src/vs/base/common/actions.ts`
* on line 26 trigger suggestion after the second `i` of `IAction`
* make sure no snippets (like `if, ifelse, import, ...`) are suggested

(it doesn't have to be that exact word/location, the gist is that snippets should only show inside words when the current prefix matches)
