### ISSUE TITLE
Source Control ignores files changed to links

### ISSUE THREAD

**Issue by elnicoCZ** [microsoft/vscode#138714]
Issue Type: <b>Bug</b>

When a file (say old_name) is renamed (say new_name), and a symbolic link with the original name (old_name) is created to link to the new file name (new_name), the Source Control does not reflect the change and only reports a new untracked file (new_name).

1. `mv old_name new_name`
2. `ln -s new_name old_name`

Correct behaviour is to show a new untracked file (new_name) and a changed file with file type changed. After staging both files, the rename should be detected.

The issue propagates to Git Graph, which does not show the new link and the renamed file is presented as Added.

![image](https://user-images.githubusercontent.com/3861622/145359720-9204c81b-c334-4aba-99ca-6aaf751420d9.png)

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.10.0-9-amd64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.24GB (7.47GB free)|
|Process Argv|--unity-launch --crash-reporter-id 78a351ea-fb78-4ef6-8f9a-f37bcbff986a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
vscode-sccconfig|be5|0.3.2
systemd-unit-file|coo|1.0.6
vscode-markdownlint|Dav|0.45.0
overtype|DrM|0.4.0
gitlens|eam|11.7.0
bitbake|Eug|1.1.2
todo-tree|Gru|0.0.214
customize-ui|ioc|0.1.55
monkey-patch|ioc|0.1.15
kconfig|luv|1.0.3
camelcasenavigation|map|1.1.3
git-graph|mhu|1.30.0
vscode-docker|ms-|1.18.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.68.0
cpptools|ms-|1.7.1
devicetree|plo|0.1.1
partial-diff|ryu|1.4.3
shellcheck|tim|0.18.2
markdown-all-in-one|yzh|3.4.0

</details>

**Comment by intonet** [comment]
Hi, I have the same issue on macbook.
Reporoduce by create two files:
```

└> touch file1   
└> touch file2
└> echo "file1" > file1
└> echo "file2" > file2
└> git add . 
└> git commit -m "created files"          
[master (root-commit) d528bfa] created files
 2 files changed, 2 insertions(+)
 create mode 100644 file1
 create mode 100644 file2
└> rm file1    
└> ln -s file2 file1               
└> git status                   
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        typechange: file1

no changes added to commit (use "git add" and/or "git commit -a")
```
Git status show changes but Code Control do not.
![Screenshot 2022-08-04 at 08 50 20](https://user-images.githubusercontent.com/35962194/182782575-80bc27f3-f65e-494e-8740-3343d0b5c647.png)

**Comment by lszomoru** [comment]
The work to add Git support for repositories/configuration that have a symbolic link on their path is tracked here: https://github.com/microsoft/vscode/issues/5970.
I would suggest that you subscribe to the linked issue to get notification when the work is scheduled.
