### ISSUE TITLE
Settings should be kept configured for all scopes (user, workspace) unless explicitly reset by user in Settings editor

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#138856]
_Disclaimer: I understand that having over 5k open issues, it won't be very important issue, but maybe it's worth standardizing._

**Detail:**
From what I can see, the settings that I put via `settings.json` stay there forever, no matter what value I set or change via the GUI.
The `diffEditor.renderSideBySide` setting works differently because it is removed from `settings,json` when i change its value with the `Inline View` button 

This creates a bit of a mess as I have my own ordering convention in `settings.json`
(I prefer to keep the native VsCode settings first in the file)

If it describes it too chaotically, below is a gif of an example:
![999](https://user-images.githubusercontent.com/30685349/145597098-d24c5467-5bcd-4f15-920f-f4fc570b1a56.gif)

**Comment by rzhao271** [comment]
I think the issue in this case is more how settings that get reset to their default value should be handled.

**Comment by kanlukasz** [comment]
> Or, do you just want the setting to not disappear no matter which settings.json file you're editing?

Yes. I think that would be the best option. Whether it's a user setting, wsl setting, or a global setting, it should always stay there when added

**Comment by rzhao271** [comment]
I added a PR to #58038 that should help with your feature request for workspace scopes. I changed the title of this issue so that it's more generic, and placed the feature on the backlog candidates milestone.

**Comment by rzhao271** [comment]
I'll merge this issue into #58038.
