### ISSUE TITLE
There is a problem with Japanese input in Japanese input IME (ATOK).

### ISSUE THREAD

**Issue by sora2h** [microsoft/vscode#138896]
VSCode1.63.0 update made ATOK Japanese conversion strange
input1 : "あいうえお"
decision : あいうえお
input2 : あいうえお"かきくけこ"
translation : あいうえおあいうえお ←!?
decision : あいうえおカキクケコ

**Comment by Lemmingh** [comment]
#138704

**Comment by sewege11** [comment]
I mentioned the same issue with short-movie at #138704 .
(Posted https://github.com/microsoft/vscode/issues/138704#issuecomment-995462569)

**Comment by jrieken** [comment]
Closing based on the previous comment
