### ISSUE TITLE
Simple browser opened in another group when reload vscode

### ISSUE THREAD

**Issue by fifv** [microsoft/vscode#138849]
Issue Type: <b>Bug</b>

1. open simple browser in one of some groups
2. focus on another group
3. use command : `reload window`, or, close and open vscode manually
4. simple browser will open at the focused group instead of where it was

I have tried extension bisect and it also happens with all extensions disabled.

I have tried insider version(1.64.0), and it still happens.

Both opened by command palette, or use the **`executeCommand`** api `"simpleBrowser.api.open"`,can cause the problem.

In previous version and before(1.62 or maybe earlier), the simple browser just disappeared after reload window.

![vscodesimplebrowser](https://user-images.githubusercontent.com/75289510/145579003-f2ba1885-5a5d-4556-ad1e-ddd5a5621d4e.gif)

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (2.68GB free)|
|Process Argv|--crash-reporter-id 18367ca6-ae75-472c-b379-58589707c3fc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-m3u|af4|1.0.0
depot|aft|1.6.1
increment-selection|alb|0.2.0
react-pure-to-class-vscode|ang|1.1.8
vscode-subtitles|ast|0.4.0
replacerules|bhu|0.4.1
exe-runner|bra|0.2.1
path-intellisense|chr|2.6.0
sqlnotebook|cmo|0.1.1
epub-reader|cwe|1.0.0
vscode-eslint|dba|2.2.2
typescript-notebook|don|2.0.6
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
vscode-command-runner|edo|0.0.120
apacheconf-snippets|eim|1.3.0
php-debug|fel|1.22.0
file-icons|fil|1.0.29
auto-rename-tag|for|0.1.9
go|gol|0.29.0
gc-excelviewer|Gra|4.0.45
beautify|Hoo|1.5.0
reg|ion|1.0.3
latex-workshop|Jam|8.22.0
moonscript|Lyn|1.1.9
rainbow-csv|mec|1.10.1
formate|Mik|1.2.1
ecdc|mit|1.4.0
vscode-uuid-generator|mot|0.3.0
vscode-apache|mrm|1.2.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
cpptools|ms-|1.7.1
hexeditor|ms-|1.8.2
live-server|ms-|0.2.11
vscode-markdown-notebook|ms-|0.0.26
vscode-typescript-next|ms-|4.6.20211209
vscode-json-editor|nic|0.3.0
fix-json|oli|0.1.2
convert-css-in-js|pau|1.1.3
subtitles-editor|pep|1.1.6
vscode-css-peek|pra|4.2.0
vscode-thunder-client|ran|1.9.1
vscode-yaml|red|1.2.2
html-to-jsx|ria|0.0.1
multi-command|ryu|1.5.1
react-proptypes-generate|sum|1.7.6
lua|sum|2.5.3
even-better-toml|tam|0.14.2
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.14
quokka-vscode|Wal|1.0.431
save-and-run|wk-|0.0.22
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
vscode-caddyfile-syntax|zam|1.0.4
material-theme|zhu|3.13.6
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30405998
vscexrecpromp3c:30407761

```

</details>

**Comment by gjsjohnmurray** [comment]
related to #119057
