### ISSUE TITLE
Not Displaying text Properly on terminal window

### ISSUE THREAD

**Issue by manish-adh** [microsoft/vscode#138810]
Issue Type: <b>Bug</b>

on the terminal window,the text automatically dissapears when the window is dragged to enlarge sidewise for few time. some part of the text from right hand side will not display. the text is missing.
please fix it. thank you

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.17134
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.71GB (3.21GB free)|
|Process Argv|--crash-reporter-id 0e2c9033-e3b7-47cc-9885-eaf19f04d6bf|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" terminal
