### ISSUE TITLE
No syntax highlight for the D programming language in Markdown's fenced code blocks

### ISSUE THREAD

**Issue by robertkovacs** [microsoft/vscode#138855]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.63.0
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T05:15:48.091Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
- OS Version: macOS Monterey 12.0.1

Steps to Reproduce:

The easiest to demonstrate the issue is opening the attached markdown file (test.md). When open in VSCode, there is syntax highlight available for the c++ code block, but no syntax highlight for the 'd' code block. 

Opening the Markdown preview by clicking the 'Open Preview to the Side' icon in the tab bar gives a preview with both fenced code blocks syntax-highlighted properly - see the attached screenshot for an illustration.

Expected behavior: the fenced code block containing 'D' code should have proper syntax highlight in the raw markdown source view as well, not only in the preview.

[test.md](https://github.com/microsoft/vscode/files/7693559/test.md)

<img width="1440" alt="Screen Shot 2021-12-10 at 16 01 50" src="https://user-images.githubusercontent.com/32719856/145594804-80e2af49-d718-4a08-96f1-b5bd3cadc775.png">

**Comment by mjbvz** [comment]
Highlighting in the preview uses highlight.js

However VS Code does not include D syntax highlighting out of the box so we can't highlight it in the source file. That's up to a D extension to contribute
