### ISSUE TITLE
Search and find feature not working.

### ISSUE THREAD

**Issue by Edison-Samuel** [microsoft/vscode#138852]
Issue Type: <b>Bug</b>

Hi Team,

I have updated vscode recently to below specified version after that I am not able to **search files** and **find files** features. I am  just able to see only recently opened files. Could you please help on this?

Thanks.

Version: 1.63.0 (user setup)
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T06:26:56.179Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Did you click this button down by mistake?

![image](https://user-images.githubusercontent.com/6726799/145606057-ac231368-aea9-4c53-813f-c48e0113c2d3.png)

**Comment by eaylward8** [comment]
I was experiencing this same issue and it was resolved after restarting my computer. Granted, I'm on macOS.

Version: 1.63.0
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T05:15:18.361Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.1.0

**Comment by Edison-Samuel** [comment]
> Did you click this button down by mistake?
> 
> ![image](https://user-images.githubusercontent.com/6726799/145606057-ac231368-aea9-4c53-813f-c48e0113c2d3.png)

No.

**Comment by Edison-Samuel** [comment]
> I was experiencing this same issue and it was resolved after restarting my computer. Granted, I'm on macOS.
> 
> Version: 1.63.0 Commit: [7db1a2b](https://github.com/microsoft/vscode/commit/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e) Date: 2021-12-07T05:15:18.361Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Darwin arm64 21.1.0

Thanks for you adding this, I tried but still seeing same

**Comment by Edison-Samuel** [comment]
This issue got resolved after switching workspace. Thanks everyone for stepping up and helping.
