### ISSUE TITLE
Windows: Warn users when opening a folder inside VS Code's installation directory

### ISSUE THREAD

**Issue by KnightBea** [microsoft/vscode#138815]
Issue Type: <b>Bug</b>

I was doing some projects on my and had saved them properly , but now none of them are there and everything has been erased. In VScode it shows it had opened them early but nothing is there now, everything has been erased including alot of hardwork i had put on those projects.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (3.84GB free)|
|Process Argv|--crash-reporter-id b519655f-0e31-4412-b139-3fb603b4c088|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
java|red|1.1.0
vscode-java-debug|vsc|0.37.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30405999
vscexrecpromp3t2:30407763

```

</details>

**Comment by bpasero** [comment]
Sorry to hear that, can you clarify exactly what happened so we can help?

**Comment by KnightBea** [comment]
I might have found the issue 🥲.
When I had installed VSCode it created it's folder called Microsoft Visual
Studio , and I had created a folder called programs in it and had saved all
my files in it.
This Morning VSCode auto updated itself , maybe this is the reason my files
went missing as it cleared it during the update process.

**Comment by joaomoreno** [comment]
The general recommendation for all applications is to never put your data inside the folder of the application. VS Code happens to clear all files from that directory in order to update itself.

Unfortunately, if you had no backups or source control, those files are gone. Sorry about that.

I'll keep this issue open so we notify when people open folders within VS Code's installation directory.

**Comment by gjsjohnmurray** [comment]
> When I had installed VSCode it created it's folder called Microsoft Visual Studio , and I had created a folder called programs in it and had saved all my files in it.

@KnightBea yes, that will be the reason. Maybe in future VS Code could give a big warning if a user saves a file within the installation folder tree.

**Comment by KnightBea** [comment]
Awesome, thanks! And specially thanks for responding this fast , truly this
is amazing.😊

**Comment by gjsjohnmurray** [comment]
@joaomoreno can I help with this?

Maybe add a suitable warning when save is creating a new file within the install tree? I found this code which seems to handle a similar situation where user is asked to confirm before overwriting an existing file I could be wrong though, as so far I have only been code-reading.

https://github.com/microsoft/vscode/blob/63ea7eae19563c97935527c22771d6559816bd5a/src/vs/workbench/services/textfile/browser/textFileService.ts#L497-L506

Wherever the check happens, questions I have:

- Warn on file save or on folder open? Or both?
- Allow user to ignore and mute the message?
- Notification in bottom right? Modal? Or banner-style message like is used for some other editor-related ones?
- Only needed on Windows? If so, is `process.platform === 'win32'` the correct test?
- How to determine install folder, and how best to detect that a uri lies within this tree?

**Comment by joaomoreno** [comment]
> @joaomoreno can I help with this?

That would be lovely, thanks!



> I found this code which seems to handle a similar situation where user is asked to confirm before overwriting an existing file I could be wrong though, as so far I have only been code-reading.

I think a cleaner way would be to have a brand new workbench contribution (search for `IWorkbenchContribution`) which, when detecting open folders or open/save operations in files within the installation folder, notifies the user accordingly.

> Wherever the check happens, questions I have:

- I would make it both. I actually would only do it at open time, both files and folders. We can assume the user knows what they are doing when saving.
- Yes, absolutely still allow the user to ignore the message.
- I would use a bottom right notification.
- I would make it general. Should work on all platforms.
- I would poke around the environment service for a good indication of where Code is installed. The Windows update service might use it in a way which hints in the right direction. Once you have that location, a URI, you can use certain utils from `resources.ts` to figure out whether any given URI is a descendant or equal to another URI.

**Comment by joaomoreno** [comment]
**Verification:**

1. Open a file within VS Code's installation directory

There should be a warning.

**Comment by joaomoreno** [comment]
@bpasero @gjsjohnmurray I'm missing context here, what happened?

**Comment by gjsjohnmurray** [comment]
@joaomoreno see https://github.com/microsoft/vscode/issues/156370

**Comment by bpasero** [comment]
**Verification**
* open install dir and verify a banner warning about doing so at the top
* open a folder within the install dir and verify the same

**Comment by gjsjohnmurray** [comment]
@bpasero I was unsuccessful when trying to verify this using the most recent Insiders:

```
Version: 1.72.0-insider (user setup)
Commit: b9f7f85e90b4d51b38fcbf4232801ab04bd659cb
Date: 2022-09-23T08:10:29.337Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes
```
Based on the commit shown above, it should include this, but when I open my appRoot folder or a subfolder of it I don't get the banner.

I am on Windows, and my appRoot is `C:\Users\JohnM\AppData\Local\Programs\Microsoft VS Code Insiders`

**Comment by bpasero** [comment]
Thanks, I had forgotton that `appRoot` is not the same as install dir: https://github.com/microsoft/vscode/pull/161613

**Comment by bpasero** [comment]
I actually noticed that the path was still using the wrong `appRoot`, will push a fix:

![image](https://user-images.githubusercontent.com/900690/192571542-249cfd8a-9a64-44d7-86f2-65fadb703885.png)
