### ISSUE TITLE
Cannot see more than one terminal per editor group

### ISSUE THREAD

**Issue by dowel** [microsoft/vscode#138870]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.64.0-insider (Universal)
Commit: 065b450db9f555f177161748e8f2911ebb5677f9
Date: 2021-12-10T05:13:44.798Z (11 hrs ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
or
Version: 1.63.0 (Universal)
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T05:15:48.091Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

- OS Version: macOS Big Sur 11.6.1
- Remote OS Version: Ubuntu 20.04.3 

Steps to Reproduce:

1. Connect to remote machine. 
2. Open terminal in editor area. Open another editor in editor area. Switch between terminals.

I've seen this problem happening on a local window. I think it starts happening in local windows as soon as you open one remote. 

Not sure if its related, but I am using fish shell on both local and remote machines. Attaching reproduction gif. 

![out](https://user-images.githubusercontent.com/417396/145618023-2a0852ba-0504-4b24-9082-af2cb85e431e.gif)

**Comment by meganrogge** [comment]
likely a /duplicate https://github.com/microsoft/vscode/issues/138770

**Comment by meganrogge** [comment]
Just saw this happen - occurs after dragging and dropping them in the editor area/rearranging

**Comment by rzhao271** [comment]
I'm not sure whether I'm repro'ing the original issue correctly.
What are some confirmation/verification steps for this issue?

**Comment by meganrogge** [comment]
Just following the op's steps were enough. They were really broken.

**Comment by Tyriar** [comment]
@rzhao271 try on a remote machine:

1. Create terminal in editor area command
2. Run a command
3. Create terminal in editor area command
2. Switch between them

Also:

1. Create in terminal panel
2. Drag to editor area
3. Run a command
4. Create in terminal panel
5. Drag to editor area
6. Switch between them
