### ISSUE TITLE
Terminal font rendering is distorted after changing to a larger text size in Win10 and then back to default.

### ISSUE THREAD

**Issue by visusys** [microsoft/vscode#138848]
Does this issue occur when all extensions are disabled?: Yes/No

**Yes.**

- VS Code Version: 1.63.0
- OS Version: Win10 Pro Version 21H1 (OS Build 19043.1348)

Steps to Reproduce:

1. Open the "[Ease of Access](https://i.imgur.com/6XsMd5K.png)" settings in Windows 10 
2. Make the text bigger by an arbitrary amount, press Apply, and wait for the setting to change.
3. Change the text back to 100% (All the way to the left), press Apply, and then wait for it to update again.
4. Go to the "Make text size bigger" window (Just search for 'Bigger' in the windows start menu.
5. Under "Make everything bigger", change the size from 100% to 125%/150%
6. Change it back to 100%.
7. Finally, look in VS Code and notice that text in the terminal looks awful. 

How it looks after performing the above steps:
![Code_C3zCWYmOvV](https://user-images.githubusercontent.com/33441569/145576067-ba3ff801-0ea7-4bd1-b2fa-b650e51b7d32.png)

How it should look:
![pwsh_to9L7kGAd7](https://user-images.githubusercontent.com/33441569/145575988-077b80d3-4aff-4355-b828-627e319400a8.png)

**A big clue** about what's going on is that if I set `Terminal › Integrated: Gpu Acceleration` to OFF, the problem goes away and everything looks normal again. So I'm not sure why that setting is fixing it. I rather enjoy GPU Acceleration, so I'd prefer to find a fix than settle with this workaround.

I really want my old terminal back. :( 

Any help or guidance would be greatly appreciated.

**Comment by visusys** [comment]
Just wanted to add an update. I uninstalled VSCode and deleted all remnants of the program from disk. I then performed a clean install, and the problem still persists. However, another additional clue: If I set `Terminal › Integrated: Letter Spacing` to 1 instead of 0, it looks a LOT better.

**Comment by Tyriar** [comment]
We looked into this and it appears the main complaint is the terminal is missing "sub-pixel anti-aliasing", this is likely an issue in Electron since it ends up working when hosting VS Code in the web. I expect the font rendering to get better when we update Electron which will use a newer browser engine.
