### ISSUE TITLE
Opening large binary files reads full contents

### ISSUE THREAD

**Issue by kaala** [microsoft/vscode#138805]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.63.0 (Universal)
OS: Darwin x64 20.6.0

Steps to Reproduce:

1. open a folder contains some very large zip files
2. select the zip files
3. edit pane become unresponsive
4. after a long time, edit pane display message: The file is not displayed in the editor because it is either binary or uses an unsupported text encoding

I don't want to open zip file in vscode, but there are some time I select the file by mistake. and then vscode freeze for a long time. 
This happens both in vscode and vscode remote ssh.
I need a file extension blacklist, or make the binary detect fast.

**Comment by j824h** [comment]
Related to #132771.
When I've made the same mistakes, I don't usually felt that encoding detection is so slow.
Does it work differently in macOS from in Windows or GNU/Linux?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
Nevermind, great catch. We indeed seem to read the entire file and try to decode it even though we could bail out earlier given we only accept text.

This does not seem like a regression though, I can reproduce slowness also in previous stable.

**Comment by kaala** [comment]
The problem also exist in insider build
You are correct about decode
![图片](https://user-images.githubusercontent.com/246542/145533395-60d5276a-18b7-4593-b140-f01abdaa9a58.png)

**Comment by bpasero** [comment]
A fix for this will be available in our insiders build on Monday, would be good to verify then. I also tried to tackle https://github.com/microsoft/vscode/issues/132771 so that the reading of large files really stops on the remote end as well.

You can give our preview releases a try from: https://code.visualstudio.com/insiders/
