### ISSUE TITLE
Markdown Preview checkboxes

### ISSUE THREAD

**Issue by ConduciveMammal** [microsoft/vscode#138845]
I've recently started using markdown to keep track of dev notes and in the markdown preview, I noticed that checkboxes aren't supported.
There exists [this extension](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox) but it seems a bit odd that something like this wouldn't be baked right in. Could it be added?

**Example:**
- [x] Remove icons and green text below from nutritional info.
- [ ] Pre-select the 10kg (is also recommended).
- [ ] Remove top pack shot
- [ ] Hide previous dogs carousel selectors

![image](https://user-images.githubusercontent.com/18140157/145565077-cbbc90c6-6d8f-4de9-948c-2eb32179ddf7.png)

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/129473#issuecomment-888814652 for response to a previous request for this.
