### ISSUE TITLE
--extensionHomePath seems broken and contradictary on Windows

### ISSUE THREAD

**Issue by joewood** [Microsoft/vscode#13887]
- VSCode Version: 1.5.2
- OS Version: Windows 7 64bit

Steps to Reproduce:

1. Move extensions to temporary directory (from `%HOME%\.vscode\extensions` to `c:\temp\extensions`)
2. Run `code --listExtensions --extensionHomePath c:\temp\extensions` - verify list of extensions (that works)
3. Run `code --extensionHomePath c:\temp\extensions` - Code runs but no extensions are loaded. Contradicts last command.

Related issue: #9520

**Comment by bpasero** [comment]
@joewood did you try with our latest 1.6.x release?

**Comment by bpasero** [comment]
Please reopen if this reproduces in 1.6 still.
