### ISSUE TITLE
Go to next problem should not move the content if error is already visible

### ISSUE THREAD

**Issue by MartinWallgren** [microsoft/vscode#138827]
Issue Type: <b>Bug</b>

It's really disorienting when the viewer/editor jumps around when activating the action "Go to next problem (Error, Warning, Info)" for errors that are already visible.

See the video linked below were I have the cursor on a line containing next error and active "Go to next error" with a keyboard shortcut. Even though the cursor is already in the same line, the view jumps making hard to orient your self.

https://user-images.githubusercontent.com/924858/145539691-eba4f600-5d52-44c6-9943-4b433c5a49a8.mp4

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 4.19.0-18-amd64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 4600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|31.33GB (2.16GB free)|
|Process Argv|--unity-launch --crash-reporter-id 4744407d-4929-4a0a-b56b-dc9f087c4021|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by sandy081** [comment]
Go to Error command always (consistent) reveals the squiggle in the editor near to the top of the view port. https://github.com/microsoft/vscode/issues/90068

I can understand that if your cursor is already on the line, then adjusting the view port is not ideal. May be we can treat this as special case and do not adjust the position if the cursor is already on the line of the squiggle?

CC @misolori

**Comment by misolori** [comment]
If we can get the peek window to not move (if it fits on the screen size) when the squiggle is within view then I am all in favor of that 👍

**Comment by MartinWallgren** [comment]
I don't think it should be for just when the error is on the same line as the cursor. As soon as the error information can be revealed without adjusting the view port the view port should remain still.
