### ISSUE TITLE
how to set the current folder for visual studio code from vscode API

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#1388]
Hi , 
how to set the current folder for workspace in visual studio code from vscode API

**Comment by jrieken** [comment]
@shanalikhan1 You cannot do that, it's seen as starting a new instance

**Comment by shanalikhan1** [comment]
Yes i know it will open new instance. but is it possible to open new folder from API and open new instance ?

**Comment by jrieken** [comment]
@shanalikhan1 You cannot do that

**Comment by shanalikhan1** [comment]
this is the good feature. i hope it will be in your roadmap

**Comment by bpasero** [comment]
#58
