### ISSUE TITLE
Can't open an HTML file on Mac

### ISSUE THREAD

**Issue by TysonMN** [microsoft/vscode#138806]
Issue Type: <b>Bug</b>

I tried to open [this HTML file](https://github.com/ploeh/ploeh.github.com/blob/master/_posts/2021-12-06-the-liskov-substitution-principle-as-a-profunctor.html) on my Mac.  Visual Studio Code opens, but the file does not open.

VS Code version: Code 1.63.0 (Universal) (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 3c85375f-3a4a-499c-88c9-6964efa29d0a|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vs360cf:30404996
vsrem710:30405998
vscexrecpromp3c:30407761

```

</details>

**Comment by TysonMN** [comment]
https://user-images.githubusercontent.com/34664007/145519510-f5a515d3-586d-4baa-b3b8-a742b42b34e1.mov

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by TysonMN** [comment]
Sorry for the delay in replying.

Good news though is that the behavior is now correct.  Great work everyone! :)
