### ISSUE TITLE
Review usage of string to represent icons

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#138830]
Extracted from https://github.com/microsoft/vscode/pull/138662#issuecomment-989648402

https://github.com/microsoft/vscode/blob/bbef3ab9bb24a08e9540b84083cf27fc25fc9f83/src/vs/platform/terminal/common/terminal.ts#L698 uses a string to represent an icon.
We normally represent icons as `ThemeIcon`. `string` is used in some contribution points and uses the `$(iconId)` notation. Ideally, convert it to ThemeIcon as quickly as possible, to avoid confusion. (`ThemeIcon.fromString`).
The current code seems to accept various formats.

**Comment by Tyriar** [comment]
@aeschli FYI the URI ones are because extensions can set the icon:

https://github.com/microsoft/vscode/blob/ab80daed7409a4ec2c6c86be1f850600931c9177/src/vscode-dts/vscode.d.ts#L9737

**Comment by aeschli** [comment]
Yes, no problem with the URI, just the string. 
For example here https://github.com/microsoft/vscode/blob/main/src\vs\workbench\contrib\terminal\browser\terminalProfileQuickpick.ts#L147 
it shows the string can be both `$(iconName)` as `iconName`

**Comment by Tyriar** [comment]
I think that was because icons in settings can be `$(icon)` or `icon`, but yeah converting to `ThemeIcon` ASAP sounds like a good idea.

**Comment by Tyriar** [comment]
I looked into doing this and am a little worried about introducing regressions for a refactor that doesn't change the product. Also, our contribution point supports both `"$(icon)"` and `"icon"` formats which it looks like `ThemeIcon.fromString` does not (would be a breaking change to switch this). We do end up converting them to theme icons, the interfaces closer to dealing with the extension contribution point and across IPC are dealt as strings is all.
