### ISSUE TITLE
Snippets in 'launch.json'

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#13886]
I would like to be able to contribute snippets for a 'launch.json' file from a debug extension. 
These snippets should only be available in 'launch.json' and not in any other .json file.

Currently each debug extension contributes a json schema which specifies what fields are required, the default values and so on.. Maybe this could somehow be used for the snippet support.

What would be the recommended way to get the snippet suport in 'launch.json'?

fyi @weinand @egamma

**Comment by aeschli** [comment]
@isidorn Did you check out the 'defaultSnippets' in the schema?

**Comment by isidorn** [comment]
This is done via a0450b3
