### ISSUE TITLE
tasks.json to execute Python script failing

### ISSUE THREAD

**Issue by Piranha688** [microsoft/vscode#138825]
I created a Python script that takes in parameters that I want to execute locally. Unfortunately, I'm running into an issue where certain Python libraries aren't imported correctly. The error message I'm getting is the following:

`ImportError: DLL load failed: The specified module could not be found.`

I have created a simple test.py that illustrates the problem:

```
import sys, os 
import pandas as pd
import numpy as np 

print("Anaconda env is ", sys.exec_prefix.split(os.sep)[-1] )
print("cwd is ", os.getcwd())
print(sys.exec_prefix)

from azureml.pipeline.core import PublishedPipeline # this is where it breaks when running through "Run Build Tasks"

print("done")
```

As you can see from this script, I'm using an Anaconda environment and I check that it's using the correct one which seems to be the case. The working directory also seems to be picked up correctly, so it's not an issue with not finding the correct script. As indicated by the comment, running this script through a tasks.json via the default "Ctrl + Shift + B" shortcut for "Tasks: Run Build Task" runs into above import problem. The tasks.json looks like this:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Run Python with parameters",
            "type": "shell",
            "command": "${command:python.interpreterPath}",
            "args": ["src\\test.py"],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

My settings.json includes the following lines as I want VSCode to use Command Prompt by default (rather than Powershell):

```
"terminal.integrated.automationShell.windows": "C:\\WINDOWS\\system32\\cmd.exe",
"terminal.integrated.defaultProfile.windows": "Command Prompt",
```

I experienced similar import problems before when Powershell turned into the default Terminal. So was wondering if maybe the Build Task doesn't run in Command Prompt, despite it being set to the default shell?

Interestingly, running the exact same test.py by execution from Command Prompt runs through the whole script successfully. No import error at all.

I have a workaround now, where I created a .cmd file to run my (original) predict script with parameters. It's still a little annoying though, as I thought "Tasks: Run Build Task" is meant for exactly this purpose. 

Any advice on what I'm doing wrong or help on fixing this would be appreciated!

**Comment by alexr00** [comment]
What version of VS Code are you using?

**Comment by Piranha688** [comment]
It's Version 1.63.0

**Comment by alexr00** [comment]
First, let's make sure that cmd is correctly being used since you suspect that's an issue. Can you add the following task to your tasks.json then run it:
```json
        {
            "label": "Do an 'ls'",
            "type": "shell",
            "command": "ls",
            "problemMatcher": []
        }
```
If the `ls` works, then powershell is being incorrectly used. If the `ls` fails then cmd is correctly being used. I tried this out, and it worked correctly with cmd being used (`ls` failed).

Next, let's check that `${command:python.interpreterPath}` is resolving to the value you expect. Can you add the following task to your tasks.json then run it:
```json
        {
            "label": "Echo interpreter path",
            "type": "shell",
            "command": "echo ${command:python.interpreterPath}",
            "problemMatcher": []
        }
```
Is the echoed path the same one you were using when you ran the script by hand?

**Comment by Piranha688** [comment]
Hi, 
I tested both of the above tasks you suggested. The first one came back with 

```
Executing task: ls <

'ls' is not recognized as an internal or external command,
operable program or batch file.
The terminal process "C:\WINDOWS\system32\cmd.exe /d /c ls" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```

which I understand is expected if my settings are correctly specified.

The second task also came back as expected:

```
> Executing task: echo C:\Users\hasemjan\Anaconda3\envs\AML\python.exe <

C:\Users\hasemjan\Anaconda3\envs\AML\python.exe

Terminal will be reused by tasks, press any key to close it.

```

**Comment by alexr00** [comment]
Thanks for trying those out. Since they both had the expected results it sounds like there could be some other environment values that are missing. 

Does your task work properly if you modify it like this?
```json
		{
            "label": "Run Python with parameters",
            "type": "shell",
            "command": "${command:python.interpreterPath}",
            "args": ["src\\test.py"],
            "group": {
                "kind": "build",
                "isDefault": true
            },
			"options": {
				"shell": {
					"args": [
						"/c"
					]
				}
			}
        },
```
What that's doing is removing the `/d` from the task that is run (https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmd#remarks if you want to know more about that).
