### ISSUE TITLE
Clojure character literals `\{`, `\[`, and `\(` wrongly rainbow colorized 

### ISSUE THREAD

**Issue by PEZ** [microsoft/vscode#138868]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: VS Code Insiders, 1.64.0-insider
- OS Version: MacOS 12.0.1

Steps to Reproduce:

1. Open a new file and paste this text:

```clojure
(defn auto-complete [open [c & r]]
  (if (empty? r)
    open
    (cond (#{\{ \[ \(}) c
          (recur (conj open c))
          
          )
    )
  )
``` 

(Set the language to Clojure if it doesn't happen automatically.)

Expected. The character literals `\{`, `\[`, and `\(` should not be rainbow colorized, and they should not mess up the colorization of ”real” brackets.

Actual: They are colorized and mess up the colorization of real brackets:

<img width="297" alt="image" src="https://user-images.githubusercontent.com/30010/145617662-e238cccf-5a9b-4f1e-86ef-18106f285135.png">

**Comment by PEZ** [comment]
Thanks. I'll check what happens if we mark these as strings for now. I can file a PR if that seems to work OK. I'm unsure since they aren't strings, but we'll see.

**Comment by hediet** [comment]
> I'll check what happens if we mark these as strings for now. 

Note that this changes syntax highlighting!
