### ISSUE TITLE
Support for 'type' in SetVariableResponse

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#13881]
_From @actboy168 on September 29, 2016 16:21_

Now I can't change the variable's type in SetVariable.
![11](https://cloud.githubusercontent.com/assets/1836844/18962500/afecbd52-86a3-11e6-8d66-dc7572a18aef.gif)

_Copied from original issue: Microsoft/vscode-debugadapter-node#66_

**Comment by weinand** [comment]
@actboy168 please elaborate what exactly you are asking for.

**Comment by weinand** [comment]
_From @actboy168 on October 17, 2016 11:48_

My extension will be change the variable's type in SetVariable request,e.g. from string to integer.But,vscode GUI has not changed.

**Comment by weinand** [comment]
You mean the type that is shown when hovering over the value does not change?

**Comment by weinand** [comment]
_From @actboy168 on October 17, 2016 12:5_

Yes.

**Comment by weinand** [comment]
Since this is a bug in the UI I will move this issue over to VS Code and create a new protocol extension request for the missing "type" attribute.

**Comment by weinand** [comment]
@isidorn with https://github.com/Microsoft/vscode-debugadapter-node/issues/66 the SetVariablesRequest can optionally return a new type (which gets shown in the hover).

**Comment by aeschli** [comment]
@isidorn How can I verify that?

**Comment by isidorn** [comment]
@weinand not so easy, you need a debug adapter that supports types and setting variables. Not sure one exists. Maybe @weinand can help
After all this is not a bug, but a new feature

**Comment by weinand** [comment]
@aeschli I will verify this!

**Comment by weinand** [comment]
Verified by adding a type to Variables return from node-debug.
