### ISSUE TITLE
Allow vscode.dev to load and save text from URLs

### ISSUE THREAD

**Issue by markrendle** [microsoft/vscode#138847]
It would be cool if I could open vscode.dev with loadUrl and saveUrl query parameters, and it could use them to load and save text.

Example:

I have a website at example.com, and I have implemented endpoints to load and save over Azure Storage blobs.

- https://example.com/files/load/foo.json
- https://example.com/files/save/foo.json

I could create links on a page to open foo.json in vscode.dev like so:

```
<a href="https://vscode.dev?loadUrl=https%3A%2F%2Fexample.com%2Ffiles%2Fload%2Ffoo.json&saveUrl=https%3A%2F%2Fexample.com%2Ffiles%2Fsave%2Ffoo.json">Edit foo.json</a>
```

vscode.dev would call the load endpoint which returns `text/text`, and then when the user saves, it would POST to the save endpoint.

**Comment by joaomoreno** [comment]
This can be achieved by an extension which would implement a file system provider and call those endpoints accordingly.
