### ISSUE TITLE
Need to be able to reliably uninstall VSCode on macOS

### ISSUE THREAD

**Issue by aprknight** [microsoft/vscode#138867]
Simply deleting the application is insufficient as there are multiple dependencies that remain (unnecessarily) in situ.
Can a formal uninstaller be provided for VSCode on macOS to ensure that not only the application but all of its dependencies are removed?

**Comment by joaomoreno** [comment]
You can just delete the app itself and then the following two folders: https://code.visualstudio.com/docs/setup/setup-overview#_how-can-i-do-a-clean-uninstall-of-vs-code
