### ISSUE TITLE
Request: Outline view

### ISSUE THREAD

**Issue by jeansantos** [Microsoft/vscode#13889]
- VSCode Version: 1.5.2
- OS Version: Windows 7 Professional (7601)

It would be great to have an Outline view, similar to Eclipse PHP where it is also possible navigate through methods even when in different files. In my point of view this is the only feature missing on this editor.

Take a look : http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Fconcepts%2Fcoutline.htm

Thank you.

**Comment by roblourens** [comment]
Yeah we've been talking about it, covered by #5605
