### ISSUE TITLE
Menu bar mnemonics don't work with version 1.63.0

### ISSUE THREAD

**Issue by bsv-hub** [microsoft/vscode#138851]
I usually press Alt+F to open file menu and it stopped working with version 1.63.0. Seems like other Alt key mnemonics doesn't work as well. I rolled back on version 1.62.3 (snap installation) and it works again.
  

- VS Code Version: 1.63.0
- OS Version: Ubuntu 20.04.2

Steps to Reproduce:
1. Press Alt+F

Expecting to see:
* File menu.

**Comment by sbatten** [comment]
I am not able to reproduce this, @deepak1556 any known issues on electron side?

**Comment by bsv-hub** [comment]
I installed 1.63.0 again to check Dev Tools Console output and provide more details and Alt key mnemonics are working again.
Seems like my previous 1.63 installation was corrupt.
Sorry and thanks for your work 👍
