### ISSUE TITLE
Make "Open with Code" part of the Win11 main context menu

### ISSUE THREAD

**Issue by fpintos** [microsoft/vscode#138814]
Issue Type: <b>Feature Request</b>

Windows 11 File Explorer introduced a 2-level context menu on items and folders.

The primary level is supposed to be "important" stuff, and the second level is the usual context menu with all options we used to have before.

To me, the primary level is pretty much useless, since most of the time I'm looking for the "Open with Code" option, which is relegated to the secondary level; apparently there is a way for applications to register their verbs so they get picked up by the primary level so maybe vscode should work with that.

(see https://blogs.windows.com/windowsdeveloper/2021/07/19/extending-the-context-menu-and-share-dialog-in-windows-11/)

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by joaomoreno** [comment]
#127365

**Comment by EnesToptas** [comment]
> #127365

> October Milestone
> November Milestone
> December Milestone

And it's a product of Microsoft itself. :D
