### ISSUE TITLE
Unicode Highlight: Ambiguous Characters - make it contextual

### ISSUE THREAD

**Issue by notaprofi** [microsoft/vscode#138898]
I really love the new "Unicode Highlight: Ambiguous Characters" feature, since cyrillic 'a' and 'c' invade my variables names from time to time. The problem is, that my code have a lot of cyrillic strings as well, and those get all highlighted and distract a lot. So I basically have no choice but to turn this feature off.

But what if we can take this feature one step further and **highlight "Ambiguous Characters" only when they seem to be a part of variable name**? when they are next to Latin characters? May be there are other conditions I'm missing.
If this is too complex, then make a simple fix for strings only: do not highlight Ambiguous Characters, which are surrounded by non ASCII characters, or space character, or quotes.

If I've missed some of the customization options for that feature, please let me know.

Thank you for your time!

**Comment by Morion-Self** [comment]
I agree, they are very annoying.

Sometimes it is difficult to read what is written in the text at all. For example

![2021-12-11_23-49](https://user-images.githubusercontent.com/1108000/145688175-162c89a2-24be-4ba2-b5e8-f8a24bd82c2c.png)

**Comment by pavlos256** [comment]
Yes, we need an option to ignore strings.

**Comment by hediet** [comment]
> do not highlight Ambiguous Characters, which are surrounded by non ASCII characters, or space character, or quotes.

I think it is reasonable to have an option to allow such characters in strings (as defined by the textmate grammar), similar to how we currently allow it in comments.

While this feature (for trusted workspaces) already does not guarantee to detect all possible unicode spoofing attacks, allowing ambiguous characters in strings makes you vulnerable to some known attacks.

Especially if you do something like this (note that `𝗎𝗌𝖾𝗋` != `user` and that the first one does not use any ASCII characters):
```
if (user.kind === '𝗎𝗌𝖾𝗋') {
    // The user does not have priviliges to access the resource
    return;
}
// The user is admin, grant access
```

We could have an option `allowAmbigiousCharactersInStrings` (similar to the existing option to allow any unicode character in comments) that is disabled by default. The "adjust settings" dialog could offer you to allow such characters in strings.

**Comment by notaprofi** [comment]
> We could have an option

sure. People will use this feature for different purposes. Some to counter hackers, some to avoid invisible characters, and some to avoid typos during wrong keyboard layout. Thereby several settings like this would fit perfectly.

Just a note to take into account - strings are defined differently in different languages. They are not always surrounded by quotes, for example in html files.

**Comment by hediet** [comment]
This feature is available in todays insider build. When you hover on a unicode highlight in a string and click on "adjust settings", there will be an option to exclude highlights in strings.
