### ISSUE TITLE
关闭未保存文件选项卡VSCODE闪退

### ISSUE THREAD

**Issue by China-Uncle** [microsoft/vscode#138899]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:
1.安装了 VSCodeUserSetup-x64-1.62.3 和 VSCodeUserSetup-x64-1.57.1
2.win10 19043.928
问题：
1.关闭未保存文件，无任何提示，VScode闪退
2.菜单栏about闪退。

1. Installed VSCodeUserSetup-x64-1.62.3 and VSCodeUserSetup-x64-1.57.1
2.win10 19043.928
problem:
1. Close the unsaved file without any prompt, VScode crashes
2. The menu bar about flashes back.

**Comment by China-Uncle** [comment]
I didn't find a solution, and I couldn't find the error log.
I reinstalled the operating system and the problem was solved.

**Comment by deepak1556** [comment]
Can you please follow the steps provided here https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and attach the crash logs, thanks!
