### ISSUE TITLE
"Git: Open changes" button always grayed out (#131739 contd)

### ISSUE THREAD

**Issue by CComparon** [microsoft/vscode#138879]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.0
- OS Version: Win10 21H2 19044.1387
- WSL2

**Steps to Reproduce:**

1. On a git-managed repo, open a file that has local changes (compared to local HEAD)
2. Used to have the "Git: Open changes" action available and the corresponding menu button, but now it's grayed out:
![image](https://user-images.githubusercontent.com/12992190/145627589-cfc70ce8-1a65-4fc8-97b7-d200130ab80e.png)

**Long story:**

I reported a similar bug in https://github.com/microsoft/vscode/issues/131739 and thanks to @lszomoru I ended up being able to patch my ~/.vscode-server/bin/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/extensions/git/package.json as he did with [this revert commit](https://github.com/microsoft/vscode/commit/4297ff8195cfabb0f96aefd122a6e88cb6a080bb#). I had to do it at every minor vscode version update, but at least I was able to fix the problem. To my knowledge, this patch was never part of an official release. Today, I upgraded to 1.63.0 and the patch won't apply any more due non-trivial changes to that file. The "Open change" command is now available :tada: but the corresponding menu shortcut button remains grayed out. I found the following patch (works fine except that the shortcut button is always enabled even when file has no changes).
in "contributes"."menus"."editor/title" :
![image](https://user-images.githubusercontent.com/12992190/145629984-47149c49-77d1-481d-baea-084d1e0d483e.png)

Many thanks
Cyril

**Comment by lszomoru** [comment]
Sorry about that. I will take another look at this next week.

**Comment by lszomoru** [comment]
@CComparon, apologies for the delay on getting back to you on this one. The latest Insiders release should contain a fix for this issue that is specific to WSL. The "Open Changes" editor action will only be shown for items that have pending changes. Let me know if you are seeing any issues. Thanks!

**Comment by lszomoru** [comment]
Closing this issue. @CComparon, please feel free to reopen in case you are still seeing any issues with the action. Thanks!
