### ISSUE TITLE
Issue running Bash Shell in terminal

### ISSUE THREAD

**Issue by CubanFireball81** [microsoft/vscode#138894]
Issue Type: <b>Bug</b>

Hello,
I am running a Lenovo Legion 5I Pro with Windows 11 Home Insider Preview OS (Build 22518.rs_prerelease.211203-1458). Today there was a "Windows Update" that seems to have done something to my VSCode's ability to connect with Bash in the terminal. Prior to today, I have not had any issues with opening a terminal and Bash running. After the update, when I try to open the Terminal it stalls for about 1-2 mins then loads Powershell. I do get some sort of red error message but it quickly goes away and I am unable to read it. 

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.22518
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (8.73GB free)|
|Process Argv|--crash-reporter-id cc2fe618-1764-4cd8-8042-764635eafe3c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
html-snippets|abu|0.2.1
project-manager|ale|12.4.0
gitignore|cod|0.7.0
bracket-pair-colorizer-2|Coe|0.2.1
githistory|don|0.6.19
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
RunOnSave|eme|0.2.0
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|9.0.0
code-runner|for|0.11.6
go|gol|0.29.0
vscode-test-explorer|hbe|2.21.1
vscode-test-explorer-liveshare|hbe|1.0.5
live-html-previewer|hdg|0.3.0
MagicPython|mag|1.1.0
vscode-language-babel|mgm|0.0.35
python|ms-|2021.12.1559732655
jupyter|ms-|2021.11.1001550889
powershell|ms-|2021.10.2
test-adapter-converter|ms-|0.1.4
vsliveshare|ms-|1.0.5196
vsliveshare-pack|ms-|0.4.0
prettier-standard-vscode|num|0.9.2
vetur|oct|0.35.0
indent-rainbow|ode|8.2.2
java|red|1.1.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
sonarlint-vscode|Son|3.1.0
guides|spy|0.9.3
code-spell-checker|str|2.0.13
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.19.0
vscode-java-test|vsc|0.33.0
vscode-maven|vsc|0.34.1
vscode-ruby|win|0.28.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.13.6
html-css-class-completion|Zig|1.20.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710:30405998
vscexrecpromp3t1:30407762

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" terminal
