### ISSUE TITLE
menu of  ”copy“，”cut“，“paste” do not work

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#138892]
Does this issue occur when all extensions are disabled?: Yes/No

Steps to Reproduce:

1. open c/++ externsion page
2. selecte some text and click copy with mouse

![image](https://user-images.githubusercontent.com/1876302/145658665-c2d2c790-71fb-4d2e-8acf-e6ae5d2fe225.png)

3. open git graph,
4. select commit message object
5. click copy
![image](https://user-images.githubusercontent.com/1876302/145658692-6f85ba76-0d70-437b-8359-caafcdacad32.png)

we could copy nothing

**Comment by aleshh** [comment]
I am having this problem also with .png files. Code can preview them, and right-click gets me the same Cut/Copy/Paste menu. Not sure what Cut and Paste would do, but I would expect Copy to copy the image to the clipboard, which it does not do

**Comment by mjbvz** [comment]
@aleshh Please open a separate feature request for that

`copy` in the context menu copies selected text. This is what I see happening with GitGraph. If you instead want to be able to copy objects in GitGraph, please file a feature request against that extension

**Comment by heartacker** [comment]
@mjbvz how about extension view?
![image](https://user-images.githubusercontent.com/1876302/150047302-d37704c3-4827-4233-b11d-5fbbd31dfde2.png)
