### ISSUE TITLE
Bug in autoformatting while saving code 

### ISSUE THREAD

**Issue by thelyinglama** [microsoft/vscode#138897]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- OS Version:
-Version: 1.63.0 (user setup)
-Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
-Date: 2021-12-07T06:26:56.179Z
-Electron: 13.5.2
-Chromium: 91.0.4472.164
-Node.js: 14.16.0
-V8: 9.1.269.39-electron.0
-OS: Windows_NT x64 10.0.19042
Steps to Reproduce:

1.  Create a c++ file.
2. Define a vector of vectors. eg:   vector<vector<int> > v;
3.  Try to save the code. VSC autoformats it and the spacing between "vector<vector<int> > v;" is formatted to "vector<vector<int>> v;"
4. Try o compile the code. The compiler will throw an error " '>>' should be '> >' within a nested template argument list
     vector<vector<int>> v;
                                    ^

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

I think that C++ formatter is provided with corresponding extension so should be reported in extension's repo.
