### ISSUE TITLE
Changes to JSON schema are not reflected

### ISSUE THREAD

**Issue by heaths** [Microsoft/vscode#13897]
- VSCode Version: 1.6.1
- OS Version: 10.0.14393.321

Steps to Reproduce:

1. Open folder with JSON schema and JSON instance document (document references schema by local path, e.g. file:///Users/name/Source/schema.json)
2. Modify schema
3. Switch back to instance document

Validation nor IntelliSense is affected. This was supposedly fixed with bug #6976 last spring but seems to have been regressed.

**Comment by aeschli** [comment]
@heaths Is the schema file in the folder opened by VSCode? We only track changes to files in the open folder.

**Comment by heaths** [comment]
Yes. I ran "code ." in the current directory which contains both my schema and an example instance document, which referenced the schema by path (like in the example above). Could there be a disconnect there, when referring to the document by a full path? I wasn't able to use a relative path (e.g. "schema.json") as Code kept trying to connect to localhost then. That syntax was the only syntax I could get working at all.

**Comment by aeschli** [comment]
For a relative path use './schema.json'.
But also "$schema": "file:///Users/name/Source/schema.json" should work. I tried it in my workspace and it worked. Not sure how we can find the issue...

**Comment by aeschli** [comment]
On Windows, don't forget to add the Drive letter.
I tested with a test file foo.json next to foo.schema.json with the following contents:
{
    "$schema": "file:///c:/Users/aeschli/Setup-Engine/schema/foo.schema.json",
    "foo": ""
}
 
-          Hover over ‘foo’ shows the description from the schema -> schema is used
-          Making a change to the over ‘branch’ description in foo.schema.json, save foo.schema.json
-          Hover over ‘foo’ shows the modified description
 
For a relative path, try this:
{
    "$schema": "./foo.schema.json",
    "branch": ""
}
