### ISSUE TITLE
Warning on vscode.dev startup on Windows

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#138991]
![image](https://user-images.githubusercontent.com/22350/145822514-388b30e0-a0a2-45ca-865a-e8489081f563.png)

Caused by: https://github.com/microsoft/vscode/commit/f17b1ec6386e9dbef4cbcd26915188a18c3d55d5

**Comment by isidorn** [comment]
Alex just notified me "I added the warning because for example AltGr+S was not distinguishable from  Ctrl+Alt+S , so if there was a language which needed AltGr+S to type { or some other symbol, we would be blocking that out-of-the-box."

**Comment by isidorn** [comment]
@joaomoreno pushed a fix. Can you please verify on Windows, since I could not easily build there. I verified on macOS web the chords work nicely.
