### ISSUE TITLE
Remote SSH Connection: editing php files give me non-existing syntax errors

### ISSUE THREAD

**Issue by FxOmar** [microsoft/vscode#138989]
Issue Type: <b>Bug</b>

I was able to connect to my ``Vagrant-homestead `` from VSCode, but if I edit php files VSCode keep giving me non-existing syntax errors
<img width="1470" alt="Screen Shot 2021-12-13 at 1 27 51 PM" src="https://user-images.githubusercontent.com/18153283/145812329-c6d088f8-bb1a-402f-87a9-8a45af637065.png">

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-91-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (8.09GB free)|
|Process Argv|Homestead.yaml --crash-reporter-id 42a90ced-432a-41cf-bdd4-cd7b5ad80bb1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: laravel|
|OS|Linux x64 5.4.0-91-generic|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (1 x 2591)|
|Memory (System)|1.94GB (0.78GB free)|
|VM|100%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
bracket-pair-colorizer-2|Coe|0.2.1
postcss|css|1.0.9
es7-react-js-snippets|dsz|3.1.1
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
vscode-firefox-debug|fir|2.9.5
vue-snippets|hol|1.0.4
better-cpp-syntax|jef|1.15.10
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.209.5
remote-ssh|ms-|0.68.0
remote-ssh-edit|ms-|0.68.0
remote-wsl|ms-|0.63.5
sublime-keybindings|ms-|4.0.10
php-docblocker|nei|2.6.1
deepdark-material|Nim|3.3.0
env-cmd-file-syntax|Nix|0.3.0
laravel5-snippets|one|1.13.0
material-icon-theme|PKi|4.11.0
laravel-helpers|raf|0.2.2
js-jsx-snippets|sky|11.0.0
bootstrap4-vscode|the|6.1.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.13.6
vetur|oct|0.35.0

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30405999
vscexrecpromp3t2:30407763

```

</details>

**Comment by roblourens** [comment]
It looks like you aren't using a PHP extension, so this is coming from the builtin PHP support? Can you share the file and your PHP version?

**Comment by FxOmar** [comment]
I'm using PHP 7.3.33 in the case of the file I can't share it, but I can assure you that the problem is coming from VSCode because I opened the same project on my local machine, and it's working just fine, but when I open it using remote ssh error shows up again, and it's effecting my project too
<img width="1434" alt="Screen Shot 2021-12-13 at 6 13 07 PM" src="https://user-images.githubusercontent.com/18153283/145857565-0526255e-2dac-40c7-a87b-621c66147927.png">
 to fix it I open vim editor and open the infected file and hit save again and it fixed but once I open it with VSCode error show up

VSCode extensions that I'm using and I tried to disable them and nothing change same error
<img width="401" alt="Screen Shot 2021-12-13 at 6 02 51 PM" src="https://user-images.githubusercontent.com/18153283/145856540-d03db684-58b4-43f6-a063-03fb5a679a93.png">

**Comment by roblourens** [comment]
What is the new screenshot from? 

Are you saying that there is actually something wrong with the file? 

> to fix it I open vim editor and open the infected file and hit save again and it fixed

The file contents change when you do this?

**Comment by FxOmar** [comment]
Open this video link in Firefox to watch the reproduce of bug
https://res.cloudinary.com/di8rsna4o/video/upload/v1639481911/Screen_Recording_2021-12-14_at_12.15.28_PM_lccji3.mov

**Comment by roblourens** [comment]
Weird bug, thanks for the video. If php (in your vagrant app) is giving the error, then clearly there is a real error. Is there something else changing the file when you save, like maybe you have an extension autoformatting the file on save, and it messed up the file?

There must be a difference in the file's content when it's working vs not working, you could save a copy of the file and diff the good and bad states

**Comment by FxOmar** [comment]
I think there's no difference because as you saw in the video when I open the file using vim everything goes back to normal

> There must be a difference in the file's content when it's working vs not working, you could save a copy of the file and diff the good and bad states

I disabled all the extensions that I have nothing change same error
> maybe you have an extension autoformatting the file on save

The thing is in my local everything is working fine, but when I use remote ssh it keep giving me that error

**Comment by roblourens** [comment]
If you load the website and php complains about that error, then clearly there is some problem with the actual contents of the file external to vscode.
