### ISSUE TITLE
Too much Loading!!!!!!!!

### ISSUE THREAD

**Issue by ravi1452** [microsoft/vscode#138906]
Issue Type: <b>Bug</b>

I need quick response to solve this bug.
My laptop will take load some time,
When i start server,Litrelly much much more time to take load.
Need Solution!

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.49GB free)|
|Process Argv|--crash-reporter-id f198afd2-98ba-4ee4-9ef2-be4aaa59185b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.5
es7-react-js-snippets|dsz|3.1.1
sublime-keybindings|ms-|4.0.10
material-icon-theme|PKi|4.11.0
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30405999
vscexrecpromp3c:30407761

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

> When i start server,Litrelly much much more time to take load.

Which server? If you are launching using LiveServer extension - you should report this issue there (with more details) or look for alternatives (as LiveServer hasn't been updated in 2 years). Maybe https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server#features


If you are using Run/Debug - you need to provide more details and your report has no info that would help to reproduce issue.
