### ISSUE TITLE
Accounts activity icon just disappears

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#138902]
On https://insiders.vscode.dev.

This is a strange one.

I've seen the Accounts activity icon disappear a few times. When I right clicked the activity bar, the Accounts entry is there **with** the checkbox, as if it was visible. When I click that, the Accounts entry comes back, and a right click on the activity bar would show an unchecked Accounts entry. Very confusing.

I can't seem to reproduce it on demand. It just happened to me after returning to a vscode.dev instance after 7 days; Sync reported that it couldn't login, so I logged in using the Accounts icon. As soon as the login was successful, the Accounts icon just disappeared.

I know @bpasero has seen this. Sorry if I assigned this incorrectly.

**Comment by bpasero** [comment]
👍 , didn't you also see this with a view once?

**Comment by sbatten** [comment]
@joaomoreno do you use a product icon extension? i.e. is it likely this happened when syncing a change in product icon theme?

**Comment by bpasero** [comment]
I am not and I saw it too.

**Comment by joaomoreno** [comment]
I do have @misolori's cool icons.
