### ISSUE TITLE
More customization to the Unicode Highlight feature.

### ISSUE THREAD

**Issue by Teltta** [microsoft/vscode#138938]
Add an option to enable/disable the Unicode highlighting in the minimap, scroll bar, and the text editor.
![image](https://user-images.githubusercontent.com/92880720/145712664-44c1eb9c-4d7f-4f81-ad81-22c48bcbfe21.png)
![image](https://user-images.githubusercontent.com/92880720/145712682-d0d6623c-3ec2-45c7-b304-985049ffe870.png)

**Comment by ArturoDent** [comment]
In the meantime, see
```jsonc
{
  "workbench.colorCustomizations": {

    "editorUnicodeHighlight.border": "#0000",                // setting to transparent
    "minimap.unicodeHighlight": "#0000",
    "editorOverviewRuler.unicodeForeground": "#0000"
}
```
