### ISSUE TITLE
Why native formatter doesn't work?

### ISSUE THREAD

**Issue by CookieJack** [microsoft/vscode#138971]
something must be going wrong i think, the formatter was good last week until today i was clicking the right-mouse button and select format incase to format the .vue document, but i got nothing response.  i thought was my fault to setup the wrong step first, but then when my colleague told me the same problem was show up, and he didn't change any thing

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version, platform, and whether the Start Extension Bisect command points to any of your extensions being the cause of the issue.
