### ISSUE TITLE
Terminal letter problem

### ISSUE THREAD

**Issue by Sujal1717** [microsoft/vscode#138912]
Issue Type: <b>Bug</b>

How do i rest my terminal it to normal.Its to big idk how i got that problem but hoow can i fix my terminal letter

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.94GB (1.37GB free)|
|Process Argv|--crash-reporter-id ad0f9d3f-f867-4892-8131-d1ba04b8c606|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.3.2
prettier-vscode|esb|9.0.0
code-runner|for|0.11.6
vscode-pull-request-github|Git|0.34.0
better-cpp-syntax|jef|1.15.10
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.5
remote-ssh|ms-|0.68.0
remote-ssh-edit|ms-|0.68.0
remote-wsl|ms-|0.63.5
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
powershell|ms-|2021.10.2
vsliveshare|ms-|1.0.5196
vsliveshare-audio|ms-|0.1.91
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.11.0
text-power-tools|qcz|1.30.0
LiveServer|rit|5.6.1
cmake|twx|0.0.17
terminal-tabs|Tyr|0.2.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30405999
vscexrecpromp3t3:30407764

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe you have set a large value for `terminal.integrated.fontSize`
