### ISSUE TITLE
Unicode Highlight showing in Overview Ruler even when turned off.

### ISSUE THREAD

**Issue by chharvey** [microsoft/vscode#138920]
Issue Type: <b>Bug</b>

When Unicode Highlight is turned off for comments,
```json
"editor.unicodeHighlight.includeComments": false
```
the highlighting in the Editor and Minimap is hidden as expected, but is still shown in the Overview Ruler (scrollbar). It should also be hidden from the Overview Ruler.

<img width="901" alt="Screenshot showing incorrect highlighting in Overview Ruler." src="https://user-images.githubusercontent.com/1362083/145686720-9d289104-581c-49ee-a98a-2edb58682913.png">

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.44GB free)|
|Process Argv|--crash-reporter-id 54cd22d4-e2ee-4f22-b559-5f15af22da1c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-wasm|dts|1.3.1
vs-code-xml-format|fab|0.1.5
vscode-ebnf|igo|1.0.3
indenticator|Sir|0.7.0
counterpoint-lang|N/A|1.0.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
vsena315cf:30406436
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710:30405998
vscexrecpromp3t3:30407764

```

</details>

**Comment by pilatte** [comment]
I can confirm that this bug is still present in the latest version. And I see it has been tagged as `feature-request`, I don't know if the problem has been well understood.

**Comment by hediet** [comment]
The overview ruler no longer shows unicode highlights (see #141152 for the rationale).

Thus, this issue no longer applies.
