### ISSUE TITLE
Untitled via `vscode.open` loose associated resource

### ISSUE THREAD

**Issue by mkhl** [microsoft/vscode#138925]
Issue Type: <b>Bug</b>

Creating an untitled document
(from a file URI amended with the `untitled` scheme)
results in different states depending on whether the document is created
with the `vscode.open` command or the `openTextDocument` function.

I tried to reduce the problem to a failing test case and failed,
but maybe [the tests in the reproduction repo](https://github.com/mkhl/issue-vscode-open-untitled) can still be useful for debugging.

## Reproduction

- Create an untitled URI for a new file (`vscode.Uri.file(path).with({scheme:'untitled'})`)
- Open an editor for that URI with `openTextDocument`/`showTextDocument`
- Type some text
- Save the file
- Notice that the save dialog starts with the `path` we had provided

- Create a new untitled URI for a new file
- Open an editor for that URI with `vscode.commands.executeCommand('vscode.open', uri)`
- Type some text
- Save the file

## Expected behavior

The save dialog starts with the `path` we had provided,
just like with the other method.

## Actual behavior

The save dialog starts with the text we typed instead of the `path` we had provided.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:16:45.441Z)
OS version: Linux x64 5.15.6-200.fc35.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|23.24GB (1.14GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-unfancy-file-icons|ale|3.15.0
icons-carbon|ant|0.2.4
chalice-icon-theme|art|1.2.16
awk-ide-vscode|bea|0.6.2
vscode-fish|bma|1.0.24
init-script|bod|0.1.3
make-task-provider|car|2.1.1
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.6.0
vscode-eslint|dba|2.2.2
EditorConfig|Edi|0.16.4
gtk-dark-titlebar|fkr|1.2.3
vscode-pull-request-github|Git|0.34.0
go|gol|0.29.0
terraform|has|2.17.0
nix-ide|jno|0.1.18
language-julia|jul|1.5.6
rust-analyzer|mat|0.2.842
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.15
direnv|mkh|0.3.0
vscode-docker|ms-|1.18.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.5
remote-ssh|ms-|0.68.0
remote-ssh-edit|ms-|0.68.0
vsliveshare|ms-|1.0.5196
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.2
edit-with-shell|ryu|1.3.0
lua|sum|2.5.3
even-better-toml|tam|0.14.2
shellcheck|tim|0.18.2
redo|zom|0.1.0

(6 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Looks like when you call `openTextDocument` we treat the URI as the associated resource:

https://github.com/microsoft/vscode/blob/4ed0329e9c5e12e2c7c59697facc96020b0768ab/src/vs/workbench/api/browser/mainThreadDocuments.ts#L276

But we do not do the same from `vscode.open`

**Comment by TylerLeonhardt** [comment]
I tried this with the following code:
```
import * as vscode from 'vscode';

export async function activate(context: vscode.ExtensionContext) {
	let a = false;
	context.subscriptions.push(vscode.commands.registerCommand('open.helloWorld', async () => {
		if(!a) {
			a = true;
			await vscode.workspace.openTextDocument(vscode.Uri.file('/path/to/a/path1').with({ scheme: 'untitled' }));
			return;
		}

		await vscode.commands.executeCommand('vscode.open', vscode.Uri.file('/path/to/a/path2').with({scheme:'untitled'}));
	}));
}
```

and both files saved to the correct paths... but I wasn't prompted at all by a file dialog. Is that expected?

**Comment by bpasero** [comment]
> Is that expected?

Yes. Untitled with associated path don't ask for a file name, that is the whole idea of "untitled with associated resource" vs. "untitled without associated resource".
