### ISSUE TITLE
emmet.extensionsPath can not be applied in this window

### ISSUE THREAD

**Issue by SuperstringDev** [microsoft/vscode#138967]
Issue Type: <b>Bug</b>

In working with Quokka I'd like to make a Emmet snippet for the /*?*/ feature under the WSL2 side. 

For this I'm just following the Egghead video below but the path to the Emmet snippets.json file does not seem to work for me. Maybe the Egghead video was using WSL1 not WSL2?

https://egghead.io/lessons/egghead-create-custom-emmet-snippets-in-vs-code

I have the .emmet dir with the snippets.son file in it at the same Linux home location as the Egghead video and my VSCode settings.json looks like this.

    "emmet.extensionsPath": [
        "~/.emmet"
    ],

I have also tried /home/user/.emmet for the path without success.

The green text is a different color than the other settings have and when I hover over the green key name for this property VSCode tells me this.

"This setting cannot be applied in this window. It will be applied when you open a local window."

I am not sure what that means so getting this path working remains essentially the last thing that is not yet running smoothly under WSL2.

I've looked for solutions but found none. How can I resolve this path issue? 

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.74.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (1.02GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/star/pack/vite-lit --remote=wsl+Ubuntu --crash-reporter-id 38670415-f434-4b9d-b76a-082ef6e73e15|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.74.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz (8 x 1497)|
|Memory (System)|3.63GB (1.14GB free)|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.2.2
theme-verdandi|be5|2.0.1
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
remote-wsl|ms-|0.63.5
open-in-browser|tec|2.0.0
vscode-icons|vsc|11.8.0
JavaScriptSnippets|xab|1.8.0
vscode-tailwindcss|bra|0.7.4
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.6.0
vscode-eslint|dba|2.2.2
vscode-new-file|dku|4.0.2
rxjs-cheatsheet|dzh|1.1.1
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
code-runner|for|0.11.6
search-node-modules|jas|1.3.0
fix-json|oli|0.1.2
vscode-css-peek|pra|4.2.0
lit-plugin|run|1.2.1
vsc-quokka-statusbar|ske|1.3.6
vscode-stylelint|sty|1.2.1
tabnine-vscode|Tab|3.5.5
pdf|tom|1.1.0
nodejs-extension-pack|wad|0.1.9
dingo-vscode|Wal|1.0.9
quokka-vscode|Wal|1.0.432
better-align|wwm|1.1.6

(20 theme extensions excluded)

</details>

**Comment by yume-chan** [comment]
I believe in the video he is using macOS and a pretty old version of Code

![image](https://user-images.githubusercontent.com/1330321/145773943-89de5de5-c947-4c44-904c-a8d7e8af7467.png)

Make sure you select the "Remote [WSL: XXX]" tab, not "User" tab.

Or you can open your setting.json with "Preferences: Open Remote Settings (JSON) (WSL: XXX)" command.

![image](https://user-images.githubusercontent.com/1330321/145774117-a72c6788-acdd-4e0e-a539-a834d81f2a1a.png)

**Comment by SuperstringDev** [comment]
Think I found the right settings.json at 

/home/star/.vscode-server/data/Machine/settings.json

Below is what I put in it and it no longer appears to be disabled.

{
  "emmet.extensionsPath": ["/home/star/.emmet"]
}

Here is what I have in my /home/star/.emmet/snippets.json 

{
    "html": {
        "snippets": {
            "q": "{/*?*/}"
        }
    }
}

I'm not sure why its still not working? Does it look right?

**Comment by rzhao271** [comment]
I'm unable to reproduce the issue. Could it be that Emmet didn't activate on time? Do other abbreviations like `ul>li` work?

**Comment by SuperstringDev** [comment]
Emmet works fine with it's own snippets. When I tested this to verify I also changed the name of my snippet and now it works. I changed it back to a single letter name and that works as well.

I've been trying out different extensions so that may be an issue or else Emmet may not have fully loaded?

Thanks for your help.
