### ISSUE TITLE
Replace all option when copying files

### ISSUE THREAD

**Issue by xencodes** [microsoft/vscode#138928]
I just tried to copy bunch of files from one folder to another folder, I wanted to update my existing project with the one I've worked one, but when I tried to copy files from their I had to press "Replace" button for every single file.

Isn't it a better idea to add a replace all button that will replace each every file.
Thanks

**Comment by JacksonKearl** [comment]
Could you explain exactly what you're doing here? When I try this I see the files get renamed with "copy" appended.
![recording (7)](https://user-images.githubusercontent.com/8586769/145897467-c5db6f14-1b99-410f-b403-e7c975e6f927.gif)

\gifPlease
