### ISSUE TITLE
函数之间的调用关系支持

### ISSUE THREAD

**Issue by jinxiangwzh** [microsoft/vscode#138952]
生成函数调用关系流程图

**Comment by hamirmahal** [comment]
Title: 函数之间的调用关系支持
Translation (via Google Translate): Calling relationship between functions support

Description: 生成函数调用关系流程图
Translation (via Google Translate): Generate function call relationship flowchart

Source: https://translate.google.com/?sl=auto&tl=en&text=函数之间的调用关系支持%20%23138952%0A%0A生成函数调用关系流程图%0A&op=translate

**Comment by yume-chan** [comment]
> In our experience, automatic translation services are not able to handle the technical language needed to effectively communicate about software issues

@hamirmahal Hi, although this one translation if OK-ish, please don't translate issues with Google. Our Chinese community members will handle them.

**Comment by CodeCrazy-ywt** [comment]
Human translation:
(Feature Request) Showing a figure of the calling/invokation hierarchy of functions.
I think this should be implemented by extensions, not vscode itself.

**Comment by JacksonKearl** [comment]
It sounds like this is asking for call graphs, which vs code does now support on a per-extension basis, see https://github.com/microsoft/vscode/issues/16110

I recommend searching for "Call Hierarchy" in the extension for the language you are using, or filing an issue on that extension if one does not exist.
