### ISSUE TITLE
Jumping into wrong place in settings.json。

### ISSUE THREAD

**Issue by joyous-coder** [microsoft/vscode#138977]
Does this issue occur when all extensions are disabled?: Yes

I remember when I clicked the link "Edit in settings.json" in the past ,   it would lead me to the right place I need to make some modifications or create a node I didn't create before. But now the cursor run into random places I don't expect to.

- VS Code Version: 1.63.0（user setup）
- OS Version: Windows_NT x64 10.0.19044

**Comment by rzhao271** [comment]
Is this a duplicate of https://github.com/microsoft/vscode/issues/134908?

**Comment by joyous-coder** [comment]
> Is this a duplicate of #134908?

Yeah，I think so
