### ISSUE TITLE
Quick Suggestion is Too Slow on Different Part of the Workspace

### ISSUE THREAD

**Issue by YosepRA** [microsoft/vscode#138987]
Issue Type: <b>Performance Issue</b>

Okay, let's start with my project's structure.

```
root
|-- api
|-- ui
```

### Preface

- Each folder (root, api, ui) has their own ESLint configs. 
- API folder is built using Express and other packages which I don't think affect my issue.
- UI is built using Vite with React template.

### Main Issue

"Quick suggestion is painfully slow when a file belonging to API folder is open"

### Case-by-case scenario:

1. **Only UI file is open**
File currently open: "ui/src/App.jsx"
Status: Okay ✅
Info: Quick suggestion is working as per configuration (10 ms). Perfectly fine.

2. **Only API file is open**
File currently open: "api/app.js"
Status: Failed ❌
Info: Quick suggestion seems to have a "fixed delay" of about 5 seconds. I thought it's only a first-load problem where it will ease up as I write. But the problem persists. On each key stroke, quick suggestion panel will highlight the typed letter _only after 5 seconds_ as it being typed.

3. **Files from API and UI are open**
File currently open: "api/app.js", "ui/src/App.jsx"
Status: Failed ❌
Info: Exactly the same as case number 2. But now, it also affects the `App.jsx` file too. The previously fine `App.jsx` also have the slow suggestions just the same as `app.js` file from API folder.

That's it for my issue. Feel free to ask for any additional details as I don't know which part are actually causing my issue. Thank you in advance for working with my issue. Have a good day!

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 460  @ 2.53GHz (4 x 2527)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.86GB free)|
|Process Argv|--crash-reporter-id 408a9cca-ea4b-43a2-a380-be29de69cade|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    92	  4100	code main
    0	    80	  4296	   shared-process
    0	    45	 10072	     ptyHost
    0	     5	  2680	       "C:\Program Files\Git\bin\bash.exe" --login
    0	     8	  8960	         "C:\Program Files\Git\bin\..\usr\bin\bash.exe" --login
    0	     5	  8324	       "C:\Program Files\Git\bin\bash.exe" --login
    0	     8	  6196	         "C:\Program Files\Git\bin\..\usr\bin\bash.exe" --login
    0	     6	  8424	       console-window-host (Windows internal process)
    0	     7	  9924	       console-window-host (Windows internal process)
    1	    86	  6092	   window (Issue Reporter)
    0	   195	  8532	   window (Home.jsx - crustecan-warrior-app - Visual Studio Code [Administrator])
    0	    80	  1316	     watcherServiceNSFW
    0	   124	  8416	     extensionHost
    0	   117	  1896	       "C:\Users\YosepRA\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\YosepRA\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName C:\Users\YosepRA\AppData\Local\Temp\vscode-typescript\4b0f062476be69b8e9bf\tscancellation-08f5e3b0d9d93af824d6.tmp* --globalPlugins typescript-vscode-sh-plugin --pluginProbeLocations "c:\Users\YosepRA\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features" --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
    0	   226	  3244	       "C:\Users\YosepRA\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\YosepRA\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\YosepRA\AppData\Local\Temp\vscode-typescript\4b0f062476be69b8e9bf\tscancellation-dc2ebf7432235d3a582b.tmp* --globalPlugins typescript-vscode-sh-plugin --pluginProbeLocations "c:\Users\YosepRA\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features" --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
    0	    95	  7376	         "C:\Users\YosepRA\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:/Users/YosepRA/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/YosepRA/AppData/Local/Microsoft/TypeScript/4.4 --enableTelemetry --typesMapLocation "c:/Users/YosepRA/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typesMap.json" --validateDefaultNpmLocation
    0	    40	  9500	   utility
    0	    24	  9640	   crashpad-handler
    0	    57	 10068	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Home.jsx - crustecan-warrior-app - Visual Studio Code [Administrator])
|    Folder (crustecan-warrior-app): 72 files
|      File types: js(20) jsx(10) json(9) md(6) gitignore(2) svg(2) css(2)
|                  env(1) html(1)
|      Conf files: package.json(3);
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
vsena315:30406435
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710:30405998
py55gd98cf:30411515
vscexrecpromp3t3:30407764

```

</details>

**Comment by jrieken** [comment]
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by YosepRA** [comment]
I forgot to mention that I've tried disabling all the extensions, but the problem remains.

**Comment by Lineez** [comment]
+1
i have problem too. In last version when my remote folder open Quick Suggestion is very slow. Close folder - fix problem. And simple search like "alt+shift+f" not end, i think he search in remote folder now.

**Comment by mjbvz** [comment]
Please share a minimal project that demonstrates this issue so we can investigate

**Comment by YosepRA** [comment]
Following the project structure of the example app, here is the repositories:

root
|-- api: https://github.com/YosepRA/crustecan-warrior-api
|-- ui: https://github.com/YosepRA/crustecan-warrior-ui

The workspace root doesn't have a remote repository, but it has a few npm packages installed in it.

Root `package.json` gist: https://gist.github.com/YosepRA/60c7c4d3d10f7b40e8cb9c70c29e8bce

**Comment by YosepRA** [comment]
I will close this issue as I found many unhelpful inconsistencies between different project with many different file structure. Quick suggestions in some of them are fast, and a few others are a bit slow (but still bearable). The Crustecan Warrior application has been particularly the slowest of them all.

Therefore, I will conclude this problem might be caused by my old 4GB laptop's performance. Thank you for the help so far. Good day.
