### ISSUE TITLE
Support virtual desktops on windows

### ISSUE THREAD

**Issue by proimage** [microsoft/vscode#138936]
Issue Type: <b>Bug</b>

I'm running Windows 11, and have multiple virtual desktops configured. On many of them, I have both VS Code and Google Chrome windows open. When I restart the computer, I exit out of both programs manually first (in VSC, via File -> Exit, and in Chrome, via the hamburger menu -> Exit). Exiting in this manner (instead of using the Close / X button in the top-right corner) closes all the windows of each program together, and allows the session to continue where it left off after reboot (VSC has the same Workspaces and tabs open, Chrome has the same windows and tabs open).

When I relaunch each of these programs, Chrome restores each window to the virtual desktop it had been on before the restart, whereas VSC restores all the workspaces/windows to the _current_ desktop.

I'd love it if VSC could behave like Chrome, and restore each workspace/window to the virtual desktop it was on initially.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Fetching remote diagnostics for 'wsl+ubuntu' timed out.
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (10.95GB free)|
|Process Argv|--crash-reporter-id cf829538-9b7f-4bbd-892b-dfe6bf5e9a2a|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'wsl+ubuntu' timed out.

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|Memory (System)|4.82GB (0.14GB free)|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
vscode-gitignore-syntax|dun|0.1.2
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
vscode-liquid-snippets|kil|2.0.3
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
remote-containers|ms-|0.209.4
remote-ssh|ms-|0.68.0
remote-ssh-edit|ms-|0.68.0
remote-wsl|ms-|0.63.4
vscode-remote-extensionpack|ms-|0.21.0
sublime-keybindings|ms-|4.0.10
language-liquid|nei|0.1.1
material-icon-theme|PKi|4.11.0
bbcode|ric|0.0.2
twig-for-craft-2|sel|0.5.0
open-in-browser|tec|2.0.0
hosts|tom|1.2.0
gitlens|eam|11.7.0
prettier-vscode|esb|9.0.0
asciidecorator|hel|0.2.0
svg|joc|1.4.14
twig-language-2|mbl|0.9.2
vscode-duplicate|mrm|1.2.1
vetur|oct|0.35.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.2
sublime-commands|Zar|0.1.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710:30405998
vscexrecpromp3t1:30407762

```

</details>

**Comment by yume-chan** [comment]
Related to #111376 and #116358. Looks like we will have the third try.

Also related to #123517 though that one is for macOS. But we need Electron support anyway.

**Comment by hello-smile6** [comment]
@webdev03 Could you upvote? It's ridiculous to mark a bug fix as a feature request.

**Comment by proimage** [comment]
Bah... it's a bugfix FFS, not a feature request.
