### ISSUE TITLE
Text in Jupyter notebook markup is hard to read because it is gray and incorrectly anti-aliased

### ISSUE THREAD

**Issue by oscarrutt** [microsoft/vscode#138947]
Issue Type: <b>Performance Issue</b>

Text in Jupyter notebook markup cells is hard to read because it uses a grey font color. This problem is exacerbated because, at least on macOS, incorrect font anti-aliasing is used instead of the system-native subpixel rendering. This is weird because text in code cells uses subpixel anti-aliasing. There appears no way to change the markup text color, in spite of the addition in 1.63 of the ability to change markup font size.

Gray fonts appear throughout VSC including in the preferences (settings) file and in web-style pages describing extensions. It's in this window as I type this note in VSC. Let's put an end to this awful, evil, bad, horrible UX fad. Leave it to Apple ad copy.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 15.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|4, 5, 5|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	    98	 95563	code main
    0	    74	 95566	   gpu-process
    0	    16	 95568	   utility-network-service
    0	    74	 95601	   shared-process
    0	    25	 95602	     ptyHost
    0	    25	  1598	       /Applications/Julia-App-Current/Contents/Resources/julia/bin/julia -i --banner=no --project=/Users/me/.julia/environments/v1.6 /Users/me/.vscode/extensions/julialang.language-julia-1.5.6/scripts/terminalserver/terminalserver.jl /var/folders/5r/0qcw1v_r8xjdqm00r6by9zy00000gn/T/vsc-jl-repl-de05ae92-3a75-4894-932c-6fa46d106be6 /var/folders/5r/0qcw1v_r8xjdqm00r6by9zy00000gn/T/vsc-jl-cr-0fd0ac43-98b5-4e0e-bb9f-8823bfe952eb USE_REVISE=true USE_PLOTPANE=true USE_PROGRESS=true DEBUG_MODE=false
    0	    25	  1599	       /Applications/Julia-App-Current/Contents/Resources/julia/bin/julia -i --banner=no --project=/Users/me/.julia/environments/v1.6 /Users/me/.vscode/extensions/julialang.language-julia-1.5.5/scripts/terminalserver/terminalserver.jl /var/folders/5r/0qcw1v_r8xjdqm00r6by9zy00000gn/T/vsc-jl-repl-dbaf777b-bcb7-4633-ac0c-07252fc16bfd /var/folders/5r/0qcw1v_r8xjdqm00r6by9zy00000gn/T/vsc-jl-cr-dc8c927f-7b09-4a30-8ff6-31b614788005 USE_REVISE=true USE_PLOTPANE=true USE_PROGRESS=true DEBUG_MODE=false
    0	    16	 95677	     watcherServiceParcelSharedProcess
    0	   147	 95675	   window (Antennas.adb — Ada (Workspace))
    0	    41	 95676	   extensionHost
    0	     8	 95684	     /Users/me/.vscode/extensions/adacore.ada-23.0.1/darwin/ada_language_server
    0	    25	 96116	     /Apps/Text_Editors/VSC/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Apps/Text_Editors/VSC/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=95676
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Antenna Pattern Modulation Projection.ipynb — Julia (Workspace))
|  Window (Antennas.adb — Ada (Workspace))
|    Folder (Code): 103 files
|      File types: ipynb(68) DS_Store(8) jl(7) webloc(6) pdf(2)
|                  profile link(1) png(1)
|      Conf files:
|    Folder (Code): more than 20163 files
|      File types: svn-base(3247) adb(1905) c(1394) ali(1374) ads(1088)
|                  py(768) o(757) out(648) gpr(619) h(501)
|      Conf files: cmake(191) makefile(67) launch.json(1) tasks.json(1)
|      Launch Configs: gdb;
```

</details>
<details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.52.0
ada|Ada|23.0.1
Bookmarks|ale|13.2.2
pascal|ale|9.4.0
pascal-formatter|ale|2.6.0
project-manager|ale|12.4.0
rtf|ale|2.4.0
octave-hacking|apj|0.2.12
vscode-svgviewer|css|2.0.0
vscode-mac-color-picker|dae|1.0.2
textpad-icon-theme|dam|1.19.21
vscode-markdownlint|Dav|0.45.0
vscode-great-icons|emm|2.1.79
ada-snippets|Ent|0.3.0
vscode-faust|gle|1.1.0
gc-excelviewer|Gra|4.0.45
vscode-lyx|gyt|0.0.4
fortran-ls|han|0.6.2
latex-workshop|Jam|8.22.0
svn-scm|joh|2.15.2
language-julia|jul|1.5.6
keen-neutral-icon-theme|kee|1.0.8
linter-gfortran|krv|2.6.2
octave|lea|0.1.1
eps-preview|mkv|0.3.0
python|ms-|2021.12.1559732655
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
postscript|mxs|1.0.1
vscode-json-editor|nic|0.3.0
vsc-octave-debugger|pau|0.4.23
bib|phr|0.3.0
seti-icons|qin|0.1.3
ipf|qms|1.0.1
vscode-data-preview|Ran|2.3.0
lualint|sat|0.0.5
bash-beautify|sha|0.1.1
markdown-preview-enhanced|shd|0.6.1
html-preview-vscode|tht|0.2.5
octave|toa|0.0.3
pdf|tom|1.1.0
vscode-lua|tri|0.12.4
vscode-icons|vsc|11.8.0
vscode-icons-mac|way|7.25.3
debug|web|0.25.1
txt-syntax|xsh|0.2.0
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710cf:30405999
py55gd98:30411514
vscexrecpromp3t1:30407762

```

</details>

**Comment by mjbvz** [comment]
What color theme are you using?

**Comment by oscarrutt** [comment]
Any of the "light" themes that come installed with VSC have this problem. These include Light (Visual Studio - C/C++), Light (Visual Studio), Light+ (default), Quiet Light, and Solarized Light.

I should add that the pesky gray font color also appears in _textual output_ in notebooks with these themes, also with incorrect antialiasing. So I suppose that if settings were to be added, it would require two different ones.

**Comment by mjbvz** [comment]
This is what I see:

![Screen Shot 2021-12-13 at 8 30 51 PM](https://user-images.githubusercontent.com/12821956/145933518-ee0177b9-7b9d-44a5-a4e3-e714e3566c56.png)

As you note, this slightly lighter black is used throughout the editor. We have not seen other reports of it being too low contrast

You can override the default color using the `foreground` color theme key:

```json
	"workbench.colorCustomizations": {
		"foreground": "#000"
	}
```
