### ISSUE TITLE
Getting the error "This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'", when using type modifiers on import names

### ISSUE THREAD

**Issue by Pika-Pool** [microsoft/vscode#138995]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.0
- OS Version: Windows 10

Steps to Reproduce:

1. Add `"importsNotUsedAsValues": "error"` to `compilerOptions` in `tsconfig`
2. import a type into a ts file:
```ts
import { type ReactNode } from 'react';
```

This throws an error: `This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.`

**Comment by mjbvz** [comment]
This is coming from your linter, likely eslint

**Comment by Pika-Pool** [comment]
This is a typescript bug. Documented at: https://github.com/microsoft/TypeScript/issues/47118
