### ISSUE TITLE
viewColumn parameter in WebviewPanel.reveal() does not work in VS Code 1.63

### ISSUE THREAD

**Issue by formulahendry** [microsoft/vscode#138914]
Issue Type: <b>Bug</b>

Run below code in VS Code extension:
`this.panel.reveal(vscode.ViewColumn.Two, true);`

**Expect:**
Panel reveal in ViewColumn.Two

**Actual:**
Panel reveal in ViewColumn.One

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (14.21GB free)|
|Process Argv|--crash-reporter-id 4c77ebb2-870b-4ced-b137-79272fb437b3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
armview|ben|0.4.5
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
955-wlb|for|0.0.1
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
code-runner|for|0.11.6
code-runner-for-web|for|0.1.4
remotehub|Git|0.19.0
vscode-pull-request-github|Git|0.34.0
vscode-drawio|hed|1.6.3
csharp|ms-|1.23.17
vscode-dotnet-runtime|ms-|1.5.0
azure-account|ms-|0.9.11
vscode-typescript-tslint-plugin|ms-|1.3.3
azurerm-vscode-tools|msa|0.15.5
material-icon-theme|PKi|4.11.0
ms-teams-vscode-extension|Tea|3.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710:30405998
py55gd98cf:30411515
vscexrecpromp3t3:30407764

```

</details>

**Comment by JarrettSpiker** [comment]
I am also seeing this with `window.createWebviewPanel` specifying `ViewColumn.Beside`. The webview panel appears to get created beside the active editor, but then moves almost immediately to `ViewColumn.One`

**Comment by IanMatthewHuff** [comment]
![CodingCats](https://user-images.githubusercontent.com/812783/151622776-ff229d36-9cc2-41e3-a019-d688f8eda64a.gif)
Looks good with a tweak to CodingCats sample to increment on each show.

As a slight side note with regards to the API, I was a bit unsure if calling reveal with a ViewColumn past what was available in the editor was exactly what I would have expected. In the code looks like it defaults to SIDE_GROUP. So if I have editor groups 1, 2, 3. And if I request ViewColumn.Eight when editor 1 is active it reveals in editor 2's group. I think that I would expect a new group 4 to be created with just my webview in it in this situation. Though that might just be personal preference / expectation.
