### ISSUE TITLE
Excessive stack depth comparing types TS:2321 After VSCode Update

### ISSUE THREAD

**Issue by mrfambo** [microsoft/vscode#138927]
Issue Type: <b>Bug</b>

Right after updating to VSCode Latest update of November 2021, all of these typescript errors emerged!

VS Code version: Code 1.63.0 (Universal) (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|40.00GB (18.63GB free)|
|Process Argv|--crash-reporter-id 5d97b757-aa14-424e-9dd2-7d7d2a6d0889|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.0.0
copilot|Git|1.7.4016
beautify|Hoo|1.5.0
code-beautifier|mic|2.3.3
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.19
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.18.0
cpptools|ms-|1.7.1
react-proptypes-intellisense|OfH|1.0.3
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.2
vscode-scss-formatter|sib|2.3.3
sass-indented|syl|1.8.18
vscode-counter|uct|2.3.0
vscode-conventional-commits|viv|1.23.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710cf:30405999
vscexrecpromp3t3:30407764

```

</details>

**Comment by mrfambo** [comment]
The issue is by default, VSCode is using its own version of 4.5.2 instead of respecting the version of workspace.

Fixed it by going back to Workspace Version of Typescript 4.2.4, instead of 4.5.2 version of VSCode.

P.S: I don't know if the behaviour of `{} Typescript` icon on the bottom bar was the same or not but it is confusing now. I had to hover on the icon to get a popup menu to change the version!

**Comment by mjbvz** [comment]
Please share some code that demonstrates this issue

**Comment by mrfambo** [comment]
What do you define as some code? I believe it is irrelevant to the code rather more on the side of project structure and Typescript setup isn’t it? Should i provide you the project structure and typescript setup to regenerate the issue?

**Comment by mjbvz** [comment]
Share steps (plus the reliance source code) so we can try to reproduce the issue on our side
