### ISSUE TITLE
Unergonomic keybind for Create New Terminal

### ISSUE THREAD

**Issue by snctfd** [microsoft/vscode#138994]
The default keybind on US keyboards for "Create New Terminal" is currently assigned to `Ctrl` + `Shift` + `` ` `` by default. I would argue that this is a highly unergonomic keybind, as it (at least in my personal experience) requires complicated acrobatics with the right hand to pull off - the fact that I have fairly large hands certainly doesn't help. I could also see this causing issues for users with motor disabilities. 

I suggest `Ctrl` + `Alt` + `T`, which as far as I can tell is not bound to anything by default.

**Comment by Tyriar** [comment]
We try not to bind alt by default on Windows/Linux and the reason it's ctrl+shift+` is because it's essentially an augmented ctrl+`. I'd recommend just creating a custom keybinding for your case:

```
{ "key": "ctrl+alt+t", "command": "workbench.action.terminal.new" }
```

FWIW I actually have more difficulty with ctrl+alt+t 🤷
