### ISSUE TITLE
Allow custom, contributed languages more customizability, including custom language icons and user-facing name

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode#138949]
It'd be nice if, when I contribute a language in `package.json`, I could

1. Add an icon for that language

![image](https://user-images.githubusercontent.com/43425812/145730888-3ddc5a0e-c4f3-4ad1-8a3d-332d489afff6.png)

2. Add a custom user-facing, display name for that language

![image](https://user-images.githubusercontent.com/43425812/145730956-141c8657-5284-4349-882a-6f64ba6cd383.png)

The current `contributes` option in `package.json` doesn't give me that level of control, since I believe the `"id"` and `"language"` properties for contributed languages has to match, since if I update one and not the other, I get an `Unknown language in contributes.grammars.language. Provided value: My Language` error when launching the extension.

I also believe there is no option to add a custom icon for `myLanguage`.

```json
        "languages": [
            {
                "id": "myLanguage",
                "extensions": [
                    ".placeholder"
                ]
            }
        ],
        "grammars": [
            {
                "language": "My Language", // does not work; "id" and "language" properties must match
                "scopeName": "source.placeholder",
                "path": "./syntaxes/placeholder.tmLanguage"
            }
        ]
```

What are your thoughts on this?

**Comment by yume-chan** [comment]
> You can contribute a human-readable using the aliases field. The first item in the list will be used as the human-readable label.
>
> _https://code.visualstudio.com/api/references/contribution-points#contributes.languages_

The icon is generally provided by icon themes. I don't know the language extension can provide a fallback.

**Comment by aeschli** [comment]
See #118846 as a solution to this.
