### ISSUE TITLE
When debugging is started, the debug console does not work properly.

### ISSUE THREAD

**Issue by BUBear** [microsoft/vscode#138963]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63
- OS Version: Windows 10

When debugging is started, the debug console does not work properly.

In the video, when debugging is started in version 1.59, a record appears in the debug console, but only loading appears in version 1.63, and nothing is done.

However, once you click on the call stack, it works normally, or when the brake point works, it works normally like version 1.59.

Even if you erase all VS codes and reinstall them, the problem is the same.

This problem has appeared since version 1.60, but I don't know if it's a bug. Is there a solution?

https://user-images.githubusercontent.com/46530081/145752094-2c771dc0-d89f-4f9a-bdb1-90a4cdbf1b6c.mp4

https://user-images.githubusercontent.com/46530081/145752097-810b719c-66e1-4541-8d98-d5ffaff1e6ca.mp4

**Comment by connor4312** [comment]
This seems to be an issue with compact mode --  the compacted parent is receiving the request, rather than the child. Clicking on the session in the Call Stack view fixes it.

**Comment by roblourens** [comment]
This is from https://github.com/microsoft/vscode/issues/128132. 

> So in theory now when a user starts a js-debug session which does not hit any breakpoints the parent session will remain focused until the child gets stopped. I think this makes sense in general.

https://github.com/microsoft/vscode/issues/89669 was the same issue as this. It seems like we still would want to focus the child session when it is added, but maybe the logic should be to focus the child session if it is compact?
