### ISSUE TITLE
No error message on failed plugin update in 1.5.1

### ISSUE THREAD

**Issue by gabejohnson** [Microsoft/vscode#13891]
- VSCode Version: 1.5.1
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Install ESLint plugin https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint (1.0.8 specified as latest version).
2. Note ESLint version at 1.0.7 and there's an update badge and update button for ESLint.
3. Update ESLint plugin and restart.
4. Version of ESLint plugin still at 1.0.7

I would expect VSCode to show a message specifying the min version the plugin supports or at least an error/warning message that the update failed.

After updating to 1.6.1 the plugin updates correctly.

**Comment by roblourens** [comment]
I think that showing available updates for extensions with an unsupported vscode version might have been fixed for 1.6 but I can't find the bug. Joao?

**Comment by joaomoreno** [comment]
#11573
