### ISSUE TITLE
Unit tests fail: WorkspaceConfigurationService - Folder

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#138972]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=146530&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=2d4939b1-2b74-59b7-3eb2-605f0910a1a9

Linux and Windows ia32 failed here:

```
  1) WorkspaceConfigurationService - Folder
       change event when there are global tasks:

      Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      + expected - actual
```

**Comment by sandy081** [comment]
This seems to start randomly failing from Saturday ie., 2021-12-11 and never failed before. I have not changed anything here.

@bpasero does any thing changed here with file service ?

**Comment by bpasero** [comment]
I just checked and it looks like the test failed before my commits on Saturday already: https://github.com/microsoft/vscode/runs/4490521985?check_suite_focus=true

**Comment by sandy081** [comment]
This test depends on browser specific runWhenIdle operation. This could have caused the flakiness. 

Added a change to explicitly reload user configuration.

**Comment by bpasero** [comment]
In my experience, none of `runWhenIdle`, `setTimeout` etc. were any reliable in testing, at least when this hits Firefox for example in browser unit tests.
