### ISSUE TITLE
Request: Search for text in strings/literals

### ISSUE THREAD

**Issue by johann-lau** [microsoft/vscode#138973]
# Search only in strings or literals
A great feature that could be added to Visual Studio Code is the ability to look for text only within literals (or the reverse, i.e. all matches outside literals).
For instance, if I want to look for the literal string "button" in an HTML document, chances are, I will have to go over tens or even thousands of results because I have a lot of `<button>` tags. On the other hand, if such a feature could be implemented, I can easily narrow down the matches to get exactly what I want.
## Implementation
Personally, I think this part would not be too difficult. If you can syntax-highlight strings, it means that you can identify strings and this feature would not be too far away.

**Comment by gjsjohnmurray** [comment]
Previous response from @roblourens https://github.com/microsoft/vscode/issues/72912#issuecomment-487075936

You can probably use a regex search to narrow down your matches.

**Comment by roblourens** [comment]
Language-specific search features are not practical for us to implement right now

**Comment by micah-redwood** [comment]
Just wanted to +1 this. It's one of the few features of the Webstorm/PHPStorm ecosystem that I miss now that I've been working in VSCode for the past year. Totally get that it would not be an easy feature to build, maybe best left for a plugin. But would be very useful.
