### ISSUE TITLE
${fileBasename} with extension, any variable without extension?

### ISSUE THREAD

**Issue by delmyers** [Microsoft/vscode#13895]
_From @bayesrule on October 17, 2016 1:39_

- VSCode Version: 1.6.1
- OS Version: Window 7

Hi,

When using cl.exe in VS Code for C++, without other specification the output program is automatically named as {fileNameWithoutExt}.exe. In current VS Code, we already have ${fileBasename} with extension and ${fileExtname} (the extension). Is it possible to add another variable without the extension?

Below is an example in my launch.json file.

```json

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch (Windows)",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceRoot}/${fileBasename}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": false
        },
        {
            "name": "C++ Attach (Windows)",
            "type": "cppvsdbg",
            "request": "attach",
            "processId": "${command.pickProcess}"
        }
    ]
}

```
It doesn't work since the "program" property will end up with foo.cpp.exe

Many thanks!

_Copied from original issue: Microsoft/vscode-cpptools#289_

**Comment by isidorn** [comment]
Will not add this unless we get more feature requests of the kind

**Comment by bayesrule** [comment]
There is at least another similar request #1104 , posted one year ago. Ended up as an entry to Backlog as well...

@isidorn @roblourens

**Comment by isidorn** [comment]
Thanks for the pointer, closign this one as a dup of #1104
