### ISSUE TITLE
expected/actual editor for failing tests has display issues when in inline mode

### ISSUE THREAD

**Issue by baincd** [microsoft/vscode#138915]
Does this issue occur when all extensions are disabled?: Yes (except for necessary extensions to run Java tests)

- VS Code Version: 1.62.3
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. With the Java extension pack installed, write a unit test with a failing assertion
2. Click the Open in Editor button to open the comparison 
![image](https://user-images.githubusercontent.com/5075659/145684641-a6dbd214-69a9-4bf2-9c91-1e178328eaae.png)

When the comparison editor is in side-by-side mode, it looks OK
![image](https://user-images.githubusercontent.com/5075659/145684601-9c76ded5-d51b-4312-a923-df53866585e6.png)

But in inline mode, the "Expected" and "Actual" hints are overlapped with the text, making it hard to read
![image](https://user-images.githubusercontent.com/5075659/145684690-8393a007-e153-4bd3-9e16-c81bf66077b0.png)

**Comment by gjsjohnmurray** [comment]
Maybe a general problem with CodeLens rendering when diff is displaying in inline mode?

**Comment by baincd** [comment]
> Maybe a general problem with CodeLens rendering when diff is displaying in inline mode?

Yes - that may actually be the issue!

Using the GitLens code lens, and setting `"diffEditor.codeLens": true,`, the code lens looks OK in the side-by-side diff editor
![image](https://user-images.githubusercontent.com/5075659/145714036-7f598982-0182-469b-8ade-8f3c3d93559f.png)

But not in inline mode
![image](https://user-images.githubusercontent.com/5075659/145714061-bcb26125-54cd-4583-8fd6-a3556b06aa70.png)

Interestingly, the issue seems to only occur if the code lens is immediately above a removed line.  If it is above or within an added line, the code lens displays OK in inline mode
![image](https://user-images.githubusercontent.com/5075659/145714342-0a88783b-5922-4dc9-892f-2bbd0c1cb4bc.png)
