### ISSUE TITLE
Some hebrew letters are selected constantly

### ISSUE THREAD

**Issue by roylaza** [microsoft/vscode#138937]
Issue Type: <b>Bug</b>

Since the lastest version, some hebrew letters in my HTML files have a yellow border around them and the line they are on appear as selected (orange) in the code mini map

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.72GB free)|
|Process Argv|--crash-reporter-id a5784d35-abd4-4084-a6a8-3361ad0d6e08|
|Screen Reader|no|
|VM|50%|
</details>

**Comment by itispey** [comment]
I have same problem with Persian words.
![image](https://user-images.githubusercontent.com/60852968/145718964-307d1207-3d02-4aeb-8e22-6fdc07c93021.png)
