### ISSUE TITLE
Keep terminal running when reloading, optionally

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode#138996]
My workflow often is:

1. Run an npm script do build and serve my node/javascript app with a watcher
2. Open another terminal in vs code to perform basic tasks
3. Make changes to the code
4. See the changes in the browser

This workflow is great, except when I have to reload the vs code instance due to a new extension update or some other change. When this happens, my terminal processes are lost too.

What I’d like is an option to have the terminal processes restart or keep running when the instance reloads.

My workaround today is to restart them manually or to use an external terminal.

**Comment by meganrogge** [comment]
/duplicate https://github.com/microsoft/vscode/issues/117408 you can also configure tasks to run when opening a folder
