### ISSUE TITLE
No hisotry records in SEARCH View

### ISSUE THREAD

**Issue by jiqiubo2019** [microsoft/vscode#138954]
Issue Type: <b>Feature Request</b>

Why provides history records in the Serach view?

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Please explain what you mean. Maybe paste screenshots.

/gifPlease

**Comment by roblourens** [comment]
You can see history in input boxes with the up/down arrow keys

**Comment by jiqiubo2019** [comment]
> Issue Type: Feature Request
> 
> Why **NOT** provides history records in the Serach view?
> 
> VS Code version: Code 1.63.0 ([7db1a2b](https://github.com/microsoft/vscode/commit/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e), 2021-12-07T06:26:56.179Z) OS version: Windows_NT x64 10.0.19042 Restricted Mode: No

**Comment by jiqiubo2019** [comment]
> You can see history in input boxes with the up/down arrow keys

Thanks. I try to press Up/Down arrow keys, Yes, I can get history records. 
It would be better if the Search View could display the history through dropdown control or other methods.

**Comment by jiqiubo2019** [comment]
> It would be better if the Search View could display the history through dropdown control or other methods.

It would be better if the Search View could display the history through dropdown control or other methods.

**Comment by jiqiubo2019** [comment]
> Why provides history records in the Serach view?

Why NOT provides history records in the Serach view?

**Comment by roblourens** [comment]
Tracking that request in https://github.com/microsoft/vscode/issues/23099
