### ISSUE TITLE
Terminal stats the terminal prompt

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#138904]
Logging errors from the file service I notice that the terminal seems to stat the terminal prompt multiple times:

![recording](https://user-images.githubusercontent.com/900690/145671871-0eccb3af-032f-4976-a264-339b282b923d.gif)

Notice the `>` at the end of the file path.

**Comment by Tyriar** [comment]
When you hover a line in the terminal links are resolved, one of the link providers gets confirmation on whether it's a file or directory and gives a high confidence link (underline shows when you hover without cmd) and on macOS we treat `>` as a valid path character. This is how it's always worked. but we could cache this stat result with a TTL (10s?) so it doesn't spam so many stat calls and will be able to return the link faster on successive hovers.
