### ISSUE TITLE
outlining doesn't work for non-standard file extension

### ISSUE THREAD

**Issue by amigo421** [Microsoft/vscode#13899]
- VSCode Version: 1.6.1
- OS Version: Win10

Steps to Reproduce:

1.  have a files (c++ syntax but non-standard extension, c++ scripting for specific system)
2. user settings contains (probably incorrect??)

`
"files.associations" : {  "*.aaa" : "cpp"  }
`

outlining (Ctrl+Shift+O) doesn't work ("no symbols.." message), 
in case of I rename the file with usual extension: .cpp, all works okay then

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-cpptools#291
