### ISSUE TITLE
QuickPick sporadically closes when user has not interacted with it

### ISSUE THREAD

**Issue by alanthai** [microsoft/vscode#138948]
Issue Type: <b>Bug</b>

I'm creating a vscode extension that sequentially opens new QuickPicks dialogs (folder navigation). After a while, they will spontaneously close out without user input.

My project:
https://github.com/alanthai/vscode-quick-explore.

Screenshot of issue:
https://screenshot.click/12-36-7owcu-yzpm8.mp4

To reproduce, download my extension, and debug it. Try navigating by moving through folders. Eventually, the QuickPick will close out unexpectedly.

VS Code version: Code 1.63.0 (Universal) (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.83GB free)|
|Process Argv|--crash-reporter-id 4141acca-2e89-4d77-ac70-a3e5528e5b55|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.19.9
vscode-neovim|asv|0.0.83
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
auto-rename-tag|for|0.1.9
go|gol|0.29.0
vscode-graphql|Gra|0.3.41
search-node-modules|jas|1.3.0
remote-ssh|ms-|0.68.0
remote-ssh-edit|ms-|0.68.0
vsliveshare|ms-|1.0.5196
mdx|sil|0.1.0
vscode-stylelint|sty|1.2.1
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
vsena315:30406435
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30405998
vscexrecpromp3c:30407761

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by alanthai** [comment]
I ran it with all extensions disabled. It seems to now take much longer before the bug appears. However, it's still sporadic. I've had a spontaneous close as early as 4 consecutive quickpicks deep, but as long as >40.

**Comment by TylerLeonhardt** [comment]
Most quick picks in VS Code will hide when it loses focus. I wonder if that's what is happening here...

**Comment by TylerLeonhardt** [comment]
So at the end of your video, that QuickPick closed because of something random happening that you don't know? Also, does this happen with any quick pick like even the Command Palette or just this particular QuickPick?

**Comment by alanthai** [comment]
It would be nice if the quick pick had an argument that was an enum of the reason it closed. I don't see evidence of something random happening that's taking focus away, although I could be wrong.

Does the Command Palette have more than 1 level deep of quick pick? Mine has theoretically infinite levels since they're moving across directories. If it were to die after 30 levels, that would be fine. But, it's very common to want to navigate 4+ levels deep, and it often does.

I do believe something's taking its focus away, but I don't feel like there's a good way to investigate. Another nice feature would be if there was a place that logs all actions taken in VSCode.

**Comment by TylerLeonhardt** [comment]
@alanthai does your quick pick set the `ignoreFocusOut` property? I'm wondering what happens if you set that (if you don't have it set already).

**Comment by alanthai** [comment]
Thanks, with that I was able to find the root cause of my issue. It turns out, I had a previous step that focuses on the Explorer on this command

```tsx
          await vscode.commands.executeCommand(
            'revealInExplorer',
            vscode.Uri.parse(nextPath)
          );
```

Adding the `await` resolved the issue!
