### ISSUE TITLE
terminal to one side

### ISSUE THREAD

**Issue by Distortions81** [microsoft/vscode#138956]
Would love for the problems/output/debug/terminal window to be docked to one side, so it doesn't take up the entire bottom.
This is a bit of a waste of screen space, the width is just not needed.

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/145774260-766f5435-f708-43eb-b9ef-bf1436914825.png)

`View: Move Panel Left` or `View: Move Panel Right`
