### ISSUE TITLE
long time running cause compute running slow

### ISSUE THREAD

**Issue by ben620** [microsoft/vscode#138955]
Issue Type: <b>Performance Issue</b>

Open a slightly large scale c++ project via remote ssh, and everything works well as  it should be. Keep the computer open without any operation for a day or two, then the you get a feel that the computer is not respond to you willingly. it slows down.

computer works fine without vs code.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (10.68GB free)|
|Process Argv|--crash-reporter-id f0a07140-375e-43f7-bc80-f9007004eef0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    92	  2248	code main
    0	   102	  2668	   shared-process
    0	    69	 11464	     ptyHost
    0	    25	  5416	   crashpad-handler
    5	   144	  5748	   window (Get Started - Visual Studio Code)
    0	   146	  1904	     extensionHost
    1	    80	 13436	   window (Issue Reporter)
    0	    37	 15160	   utility
    1	    95	 15336	   gpu-process
    0	    11	 15804	   C:\Users\benyuan\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e.exe /verysilent /update="C:\Users\benyuan\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0	    39	 15932	     "C:\Users\benyuan\AppData\Local\Temp\is-HMK7T.tmp\CodeSetup-stable-7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e.tmp" /SL5="$20514,78862383,828416,C:\Users\benyuan\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e.exe" /verysilent /update="C:\Users\benyuan\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
lua-debug|act|1.52.0
arepl|alm|2.0.3
vscode-intelephense-client|bme|1.8.0
doxdocgen|csc|1.3.2
githistory|don|0.6.19
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
vscode-html-css|ecm|1.10.2
php-intellisense|fel|2.3.14
gc-excelviewer|Gra|4.0.45
compareit|in4|0.0.2
vue|jcb|0.1.5
better-cpp-syntax|jef|1.15.10
vsc-python-indent|Kev|1.14.2
Lua|key|0.0.9
MagicPython|mag|1.1.0
Kotlin|mat|1.7.1
vscode-docker|ms-|1.18.0
vscode-language-pack-zh-hans|MS-|1.62.4
csharp|ms-|1.23.17
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.68.0
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.0-insiders2
cpptools-extension-pack|ms-|1.1.0
hexeditor|ms-|1.8.2
autodocstring|njp|0.5.4
vetur|oct|0.35.0
java|red|1.1.0
vscode-hexdump|sle|1.8.1
emmylua|tan|0.3.49
python|tht|0.2.3
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.19.0
vscode-java-test|vsc|0.33.0
vscode-maven|vsc|0.34.1
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.20.0
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710:30405998
vscexrecpromp3t1:30407762

```

</details>

**Comment by roblourens** [comment]
Can you give some more details about what is slow? If you check the task manager, is there a process using high cpu or memory?
