### ISSUE TITLE
[TestExplorer] newly added test item not showing gutter icon

### ISSUE THREAD

**Issue by connectdotz** [microsoft/vscode#138922]
Issue Type: <b>Bug</b>

After adding a new test, the item shows up correctly in the TestExplorer view, but no gutter icon is shown, even though the item does have the correct location (range).

![Dec-11-2021 15-43-18](https://user-images.githubusercontent.com/891093/145691348-16c20d8f-4f08-4f32-9e84-9153eea3703d.gif)

This might help narrow down the issue: the test item was first created without range but updated afterward. Maybe the update failed to notify the gutter update for some reason?

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (5.71GB free)|
|Process Argv|--crash-reporter-id 438d80c7-05fc-418f-b140-e69581260943|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-color-pick|ada|0.6.2
spellright|ban|3.0.60
emojisense|bie|0.9.0
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
gitlens|eam|11.7.0
prettier-vscode|esb|9.0.0
vscode-commands|fab|1.4.3
flow-for-vscode|flo|1.9.2
shell-format|fox|7.2.2
vscode-pull-request-github|Git|0.34.0
go|gol|0.29.0
vscode-insertdatestring|jsy|2.3.0
vscode-colorize|kam|0.11.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.18.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.8.1
vscode-jest|Ort|4.2.1
material-icon-theme|PKi|4.11.0
java|red|1.1.0
markdown-preview-enhanced|shd|0.6.1
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.19.0
vscode-java-test|vsc|0.33.0
vscode-maven|vsc|0.34.1
vim|vsc|1.21.10
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
I'm having trouble reproducing this either in vscode-jest or the test provider, but I think I might know what's going on here. I'll put a fix in, please let me know if it solves the issue for you.

**Comment by connectdotz** [comment]
/verified

yup, this is fixed, @connor4312 thanks!
