### ISSUE TITLE
VSCode adds a second bouncing icon to the dock on MacOS 

### ISSUE THREAD

**Issue by EllipticEllipsis** [microsoft/vscode#138918]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.63.0
- OS Version: MacOS 12.0.1

Steps to Reproduce:

1. Open VSCode.
2. Second bouncing icon appears. Sometimes it stops bouncing, sometimes it doesn't, but it never goes away.

I opened it using `code .` in a terminal window once and now it does it every time. This is extremely annoying, and there don't seem to be any instructions on how to fix it.

Edited to add: Restarting the Extension Host adds *another* icon!

Edit 2: Disabling and reenabling extensions and reloading *seems* to fix it, but this obviously doesn't solve the initial problem, whatever it is.

**Comment by tjx666** [comment]
often see extra icon bounce too on macOS...

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/138838#issuecomment-991354259

**Comment by hesselmonk** [comment]
The other issue is closed, but I'd like to argue that extensions should not be able to add additional icons to the dock?

**Comment by jomach** [comment]
same here
