### ISSUE TITLE
Console should not say 'no suggestions' if the debug adapter doesn't support completions

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#13893]
If `supportsCompletionsRequest` is not returned from initializeRequest, it might look better if the 'no completions' popup is not shown when the user presses ctrl+space. It looks like the debug adapter is trying to show completions and failing.

**Comment by isidorn** [comment]
This is what we do in the editor when no completions are available.
I do not want to treat the repl editor as a special editor and display it differntly

Thus closing as will not fix / as designed
