### ISSUE TITLE
Split view, Split Working file

### ISSUE THREAD

**Issue by puneethrai** [Microsoft/vscode#1389]
For easy working with multiple files and multiple view. it is good if working file list has split based on files located in each view

**Comment by Codemaverick** [comment]
Complained about this very issue [here](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/9009457-list-move-files-per-editor-window).

If the team is still using the uservoice, maybe also add votes there?

**Comment by csinco** [comment]
Cool idea. @bgashler1 and @stevencl maybe something to explore soon?

**Comment by puneethrai** [comment]
@Codemaverick Voted there as well.

**Comment by bpasero** [comment]
This is planned for June.
