### ISSUE TITLE
 I've disabled all online features could find, but VSCode still try to connect to internet

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#138913]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.63
- OS Version:Win10

#133582 still .

Do not ask for IPs . Just install and test VSC, with monitoring the network .

**Comment by joaomoreno** [comment]
> Do not ask for IPs

Unfortunately I'm not going to follow your suggestion. I will ask. What traffic are you observing exactly?

**Comment by irvnriir** [comment]
TCP to IPs of Microsoft and Microsoft Azure .

Specific output, like targeted addresses, is a personal information .

**Comment by joaomoreno** [comment]
If VS Code reaches out to those addresses, I can guarantee they are not personal information.

If you can't provide them, I can't look into the issue. Let me know how you want to proceed.

**Comment by irvnriir** [comment]
I don't have computer in country which is far enough, to check whether they are personal info or not . And this issue should've not happen in the 1st place .

Definitely there is people in the Microsoft's 3rd of Redmond city who know how to monitor network .
