### ISSUE TITLE
Default shortcut doesn't work

### ISSUE THREAD

**Issue by madallday** [microsoft/vscode#138916]
Issue Type: <b>Bug</b>

The default shortcut for 'Reveal in File Explorer" is Shift+Alt+R.
Attempting to use that shortcut does not work, and instead it drops down the 'Run' menu.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by sbatten** [comment]
This isn't a result of mnemonic conflict. The command has a when condition that is false when the editor is focused. Disabling the menu doesn't have any impact on this keybinding working. Therefore assigning to @bpasero and @alexdima

**Comment by bpasero** [comment]
Pretty much the same as https://github.com/microsoft/vscode/issues/137216 I would argue.
