### ISSUE TITLE
Missing onDidOpenTextDocument/onDidCloseTextDocument events for documents opened with openTextDocument

### ISSUE THREAD

**Issue by mkhl** [microsoft/vscode#138924]
Issue Type: <b>Bug</b>

During extension development I noticed that
opening files with `openTextDocument`
didn't always fire the `didOpenTextDocument` events I was expecting.

This test suite is there to explore and reproduce the problem.

## Reproduction

In the [reproduction repo](https://github.com/mkhl/issue-ondidopentextdocument-events):

- `npm ci`
- `npm test`

## Expected results

All tests in the suite succeed.

## Actual results

The test for events fired by `openTextDocument`
followed by `showTextDocument`
for an existing file fails.

It seems like closing the editor with the text document
doesn't actually close the document
(and doesn't fire `onDidCloseTextDocument`),
so subsequent attempts to open the document
don't fire `onDidOpenTextDocument`.

The same sequence of events works for nonexistent files
(with the `untitled` uri scheme),
as does opening the file with the `vscode.open` command.

Other commands for closing editors (like `workbench.action.closeAllEditors`)
don't improve the situation,
and the API doesn't seem to provide any other method to close documents.

For more details, see the test suite in `src/test/suite/extension.test.ts`.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:16:45.441Z)
OS version: Linux x64 5.15.6-200.fc35.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2997)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|23.24GB (0.83GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-unfancy-file-icons|ale|3.15.0
icons-carbon|ant|0.2.4
chalice-icon-theme|art|1.2.16
awk-ide-vscode|bea|0.6.2
vscode-fish|bma|1.0.24
init-script|bod|0.1.3
make-task-provider|car|2.1.1
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.6.0
vscode-eslint|dba|2.2.2
EditorConfig|Edi|0.16.4
gtk-dark-titlebar|fkr|1.2.3
vscode-pull-request-github|Git|0.34.0
go|gol|0.29.0
terraform|has|2.17.0
nix-ide|jno|0.1.18
language-julia|jul|1.5.6
rust-analyzer|mat|0.2.842
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.15
direnv|mkh|0.3.0
vscode-docker|ms-|1.18.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.5
remote-ssh|ms-|0.68.0
remote-ssh-edit|ms-|0.68.0
vsliveshare|ms-|1.0.5196
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.2
edit-with-shell|ryu|1.3.0
lua|sum|2.5.3
even-better-toml|tam|0.14.2
shellcheck|tim|0.18.2
redo|zom|0.1.0

(6 theme extensions excluded)

</details>

**Comment by ArturoDent** [comment]
https://github.com/microsoft/vscode/issues/114005 and similar might help for background information.

**Comment by mkhl** [comment]
Ah, so `openTextDocument` is behaving as intended and `vscode.open` is an outlier I shouldn't rely upon?
