### ISSUE TITLE
LightBulb on top of line numbers when glyph margin disabled

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#13890]
1. "editor.glyphMargin": false
2. Have a error that produces a quick fix
3. Notice the light bulb goes on top of editor line numbers
4. If I have glyphMargin disabled I would expect to never show the light bulb. Same as how we do not show breakpoints if a user has disabled the glyph margin

![screen shot 2016-10-17 at 16 48 53](https://cloud.githubusercontent.com/assets/1926584/19442566/fd80d8b6-9489-11e6-8bec-38c02c9d2ee3.png)

**Comment by jrieken** [comment]
Agree - didn't even know that you can turn that off...

**Comment by isidorn** [comment]
I actually fixed that this sprint since there was an option but we never respected it due to debug decorations. Now we respect it since users requested it
