### ISSUE TITLE
Crush if dragging a large file to open

### ISSUE THREAD

**Issue by LoveJenny** [Microsoft/vscode#139]
![image](https://cloud.githubusercontent.com/assets/1896620/11261236/87592644-8ead-11e5-9c29-246b3d7aa922.png)

**Comment by meritozh** [comment]
Now, it can't support large file. I suggest you use st or vim to open it.

**Comment by bpasero** [comment]
@LoveJenny can you attach it (possibly as a zip if it is so large).

**Comment by msallin** [comment]
I also have this issue with an XML file. The size of the file is about 80 MB.
I can not provide you with the original one but you can reproduce it easy by creating a own file.

I was able to reproduce the crash with an XML file which is about 66 MB in size.
Use the following C# Code to generate the file:

```
XDocument xdoc = new XDocument(new XElement("root"));
for (int i = 0; i < Math.Pow(10, 6) * 2; i++)
{
	xdoc.Root.Add(new XElement("Child" + 1, new XAttribute("attr" + i, i)));
}

xdoc.Save(@"C:\temp\file.xml");

```

**Comment by alexandrudima** [comment]
Generated file using:
```javascript
var fs = require('fs');

var text = [];
text.push('<xml>');
for (var i = 0, len = Math.pow(10, 6) * 2; i < len; i++) {
	text.push('<Child1 attr'+i+'="'+i+'" />');
}
text.push('</xml>');

fs.writeFileSync('large_files/large.xml', text.join('\n'));
```

Made a change that files above 5MB don't are "hidden" from the extension host.

After b57564d and b255288 the generated file (2M lines, 63MB) opens.
