### ISSUE TITLE
 Hangul is entered twice in ubuntu

### ISSUE THREAD

**Issue by danaisboss** [microsoft/vscode#139066]
We have written the needed data into your clipboard because it was too large to send. Please paste.ubutntu 20.04.3 LTS 환경에서 사용중입니다.
다른 터미널에선 안그러는데, vsc의 터미널 내에서만 한글이 두번씩 입력됩니다.
버그인가요?

----
in ubutntu 20.04.3 LTS 
in vsc terminal korean is entered twice. is it error? 
![image](https://user-images.githubusercontent.com/46172219/145976634-3429d681-f70b-429f-8515-3f845b197c85.png)

like this... i just want "한글이 두번씩" but in vsc termianl "한한글글이이 두두번번씩"

**Comment by CHOONGHOJO** [comment]
저도 같은 문제로 해결점을 찾고 있습니다만, 아직 해결하지 못했습니다.

**Comment by chunje99** [comment]
저도 같은 증상이 있습니다.
5.11.0-37-generic #41~20.04.2-Ubuntu
vscode 터미널에서 한글쓸일이 많지 않아서 그냥 쓰곤 있지만 불편하네요.
![스크린샷, 2021-12-22 13-01-35](https://user-images.githubusercontent.com/17687912/147033830-80ae7891-a450-4270-ae01-9d4eac6a4a69.png)

**Comment by kiminseob** [comment]
저도 동일한 증상이 발생하고 있습니다.
5.11.0-43-generic #47~20.04.2-Ubuntu
vscode: 1.63.2

**Comment by danaisboss** [comment]
아니 저 스레드도 해결 제대로 안됐는데 왜 닫어

**Comment by aveyuan** [comment]
> 아니 저 스레드도 해결 제대로 안됐는데 왜 닫어 I don't think that thread is solved yet. Why are you closing it? @meganrogge

Hi，This issue has been resolved in Vsocde 1.64.0. You can try. it.

**Comment by chunje99** [comment]
oh~~ thank you. The issue has been resolved in Vscode 1.64.0 ^^
@meganrogge  버전업 하고 해보세요. 저는 해결된걸로 보이네요.
