### ISSUE TITLE
Parent indirection in launch configs cwd results in poor source maps

### ISSUE THREAD

**Issue by ccarcaci** [microsoft/vscode#139086]
Does this issue occur when all extensions are disabled?: Yes

When using the "double-dot parent folder indirection" in launch configuration (see image) the debugger stops working properly with typescript and source maps.

![Screenshot from 2021-12-14 13-50-58](https://user-images.githubusercontent.com/7973726/146001732-4502004e-c7a1-4c88-9e96-93f717ac5960.png)

- VS Code Version:
```
1.63.0
7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
x64
```
- OS Version:
Ubuntu Linux `Linux ccarcaci-N56JN 5.11.0-41-generic #45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
I have the same problem also on OSX on a different machine.

Steps to Reproduce.

Working case:
1. Checkout this repo https://github.com/ccarcaci/parent-cwd-issue
2. Select menu entry File > Open workspace from file...
3. Select the workspace.code-workspace from `parent-cwd-issue/single-folder`.
4. Run `npm build` pointing your console to `parent-cwd-issue/single-folder`.
5. Set a breakpoint in the index.ts file.
6. Open Run&Debug tab.
7. Launch "single folder" runnable configuration.
8. Debugger stops correctly on the breakpoint (see image).
![Screenshot from 2021-12-14 13-55-03](https://user-images.githubusercontent.com/7973726/146002264-804620ba-5a3f-4013-8fce-f7f24797eda2.png)

Broken case:
1. Checkout this repo https://github.com/ccarcaci/parent-cwd-issue
2. Select menu entry File > Open workspace from file...
3. Select the workspace.code-workspace from `parent-cwd-issue/multi-folder/workspace-launch`.
4. Run `npm build` pointing your console to `parent-cwd-issue/multi-folder/service-code`.
5. Set a breakpoint in the index.ts file.
6. Open Run&Debug tab.
7. Launch "multi folder" runnable configuration.
8. Debugger is not stopping correctly at the breakpoint.
9. Open the file `parent-cwd-issue/multi-folder/service-code/build/src/index.js`.
10. Set a breakpoint.
11. Open Run&Debug tab.
11. Launch "multi folder" runnable configuration.
12. Debugger works correctly on compiled code (see image).
![Screenshot from 2021-12-14 14-00-54](https://user-images.githubusercontent.com/7973726/146003109-a7b7cab3-66a4-41ec-a907-818e82ad0ce9.png)

What's the difference?
The single-folder package has [a launch configuration](https://github.com/ccarcaci/parent-cwd-issue/blob/main/single-folder/.vscode/launch.json) which uses the `cwd` default value (I've tried using a path without parent indirection and it works either).

The multi-folder package has [a launch configuration](https://github.com/ccarcaci/parent-cwd-issue/blob/main/multi-folder/workspace-launch/.vscode/launch.json#L14) which specifies a parent indirection in the `cwd` setting.

**Comment by connor4312** [comment]
You'll want to [configure your outFiles too](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-map-discovery) by adding:

```
      "outFiles": [
        "${workspaceFolder}/../service-code/**/*.js",
        "!**/node_modules/**"
      ],
```

By default, VS Code will only scan the workspace folder for sourcemaps, and this adjusts that. We actually have logic to do this automatically, but it was only activated if a `program` was set, which is not the case for you.

You also most likely want to remove the `disableOptimisticBPs`.

**Comment by connor4312** [comment]
This will be fixed in the next [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension)

**Comment by ccarcaci** [comment]
TY @connor4312

**Comment by rchiodo** [comment]
/verified

![image](https://user-images.githubusercontent.com/19672699/151460917-73d28bb2-c992-4b25-9e06-60952497708d.png)
