### ISSUE TITLE
Allow for triggering breakpoints when a watch condition is met

### ISSUE THREAD

**Issue by nholthaus** [Microsoft/vscode#13904]
Allowing for expressions in the `watch` block of the code debugger is really helpful! But it would be even better if it was possible to trigger a breakpoint automatically if the expression or evaluates to `true` (or changes, whatever is easier).

[Visual Studio has a similar feature](https://msdn.microsoft.com/en-us/library/aa295838%28v=vs.60%29.aspx#_core_setting_a_breakpoint_when_an_expression_is_true) for reference.

**Comment by roblourens** [comment]
We do actually have this - set a breakpoint then right click on it and select 'Edit breakpoint' to set a condition.

**Comment by nholthaus** [comment]
I guess that's sort of the opposite of what I'm asking for.

You're saying that you can break at a known location, if a given condition is met.

I'd like to break at whichever location causes the condition to be met.

**Comment by roblourens** [comment]
Oh, I see

**Comment by weinand** [comment]
@nholthaus we only add feature like this to the generic VS Code debugger UI if there is actually a chance that a debug extension will be able to implement this. Node.js does not support this and we've got no requests from the C++ or C# teams. Do you have examples for runtimes that would support that feature?

**Comment by nholthaus** [comment]
I was hoping for c++ support, which I think would also involve changing the c++ extension. Visual Studio C++ has the equivalent feature so it's not impossible to implement.

**Comment by weinand** [comment]
@nholthaus moving to the C++ extension.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#294
