### ISSUE TITLE
VS Users UI

### ISSUE THREAD

**Issue by Prateek-Singh1** [microsoft/vscode#139094]
There are some white patches are formed on VS Software when I am working on it. After moving my cursor to those patches its disappears after few seconds again it comes back to VS Code. 
i do have Screen Shots.
Please let me know if you have any solution.
Thank you

**Comment by Prateek-Singh1** [comment]
![recording](https://user-images.githubusercontent.com/90711854/146022065-c431bcae-6bea-4183-ba18-7c93ce76425f.gif)
![Screenshot (205)](https://user-images.githubusercontent.com/90711854/146022103-0cd7676b-cb0a-4d54-aba7-0396dd8ba821.png)

**Comment by gjsjohnmurray** [comment]
Please launch VS Code from a Windows command prompt like this:
```
code --disable-gpu
```

Do you still get the problem? If so, please confirm your version information by picking About from the Help menu, then using the Copy button to put them on the clipboard. Finally, paste them here.

**Comment by gjsjohnmurray** [comment]
I suggest you check that your display hardware drivers are up to date. If they are then I think you will have to continue using the --disable-gpu switch.

**Comment by Prateek-Singh1** [comment]
Thanks, I'll check it out.

**Comment by IllusionMH** [comment]
In this comment update of nvidia settings helped https://github.com/microsoft/vscode/issues/115189#issuecomment-768239687

Also, there is more permanent way than always passing `--disable-gpu` flag. See https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by Prateek-Singh1** [comment]
That Permanent way works fine now..
Thank you
@IllusionMH

**Comment by bpasero** [comment]
You can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart
