### ISSUE TITLE
Shortcut cw

### ISSUE THREAD

**Issue by Kiev-Junta** [Microsoft/vscode#13903]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:43:46.054Z)
- OS Version: Linux x64 4.4.0-31-generic
- Extensions: ms-vscode.csharp-1.4.1, robertohuertasm.vscode-icons-3.0.5

Steps to Reproduce:

"cw - tab tab" generates System.Console.WriteLine() instead of Console.WriteLine(). (using System exists, namespace name is different)

**Comment by roblourens** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#828
