### ISSUE TITLE
vscode crash oom

### ISSUE THREAD

**Issue by mozhuanzuojing** [microsoft/vscode#139096]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:1.63
- OS Version:windows 10 21H1

As long as you open git comparison frequently, more than 100 consecutive times will cause `OOM`. i think git does not release memory

**Comment by gjsjohnmurray** [comment]
> worenwi is a git plugin that does not release memory

By "plugin" do you mean "extension"?

Please use the `Start Extension Bisect` command to check whether one of your extensions is causing the issue.

**Comment by mozhuanzuojing** [comment]
@gjsjohnmurray Unable to locate the problem, do not know how to set the maximum memory of vscode

**Comment by lszomoru** [comment]
@mozhuanzuojing, are you able to reproduce the same type of memory consumption when you start code using `code --disable-extensions`?

**Comment by mozhuanzuojing** [comment]
@lszomoru Thanks. I will close this question. Because I cannot reproduce stably. And it rarely appears.
