### ISSUE TITLE
Something in webview makes browser tests flaky unless we have a released build

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139085]
We had a lot of red builds in CI until we released a new insiders (it seems). So I conclude that something in the unit tests depends on a build being released, I suspect something around webviews being published to some remote endpoint so that web tests can run. 

I think we need to remove this source of failure as it will happen again in the future.

//cc @Tyriar

**Comment by Tyriar** [comment]
This test flaked the other day which complained about a webview endpoint being accessed https://dev.azure.com/monacotools/Monaco/_build/results?buildId=146269&view=results

**Comment by bpasero** [comment]
👎
