### ISSUE TITLE
Unable to select brackets for link title in markdown

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [microsoft/vscode#139051]
This problem still occurs even if you disable all extensions.

# Unable to select brackets for `[link title]` in markdown

When creating a link, the brackets surrounding a link title do not seem to be recognized well.
Similarly, the same symptom occurs when pasting an image.

I often use `editor.action.selectToBracket` to select inside brackets, but currently I can't select inside brackets surrounding link title with this command.

```markdown
[Example Domain](http://example.com/)
```

This behavior is the same when a link is created as follows:

```markdown
[Example Domain][link]

[link]: http://example.com/
```

Example of running:
I want to select the link title `Example Domain`, but the URL is selected.
Changing the link title is a bit annoying because I can't select contents of the brackets.

![Animation](https://user-images.githubusercontent.com/75878492/145832721-0e8b96e8-366d-434c-9f9e-ef93d4139813.gif)

Also, `"editor.bracketPairColorization.enabled": true` is set, but brackets surrounding link title are not highlighted.

Sample image:

![link-syntax](https://user-images.githubusercontent.com/75878492/145832741-3a606815-7f6e-495a-8df8-670635ed2502.png)

----------

I reported this issue to [Markdown All in One](https://github.com/yzhang-gh/vscode-markdown) as an extension problem, but it was pointed out that it may be a problem in VS Code, so I reported it here.

> https://github.com/yzhang-gh/vscode-markdown/issues/1063

## Version

| OS               | Windows10 x64 21H1                       |
| :--------------- | :--------------------------------------- |
| VS Code version  | 1.62.1                                   |

<details>
<summary>Installed extensions version</summary>
<div>

| Extension                               | Version |
| :-------------------------------------- | :------ |
| alefragnani.project-manager             | 12.4.0  |
| BriteSnow.vscode-toggle-quotes          | 0.3.5   |
| James-Yu.latex-workshop                 | 8.22.0  |
| MS-CEINTL.vscode-language-pack-ja       | 1.62.4  |
| ms-vscode.cpptools                      | 1.7.1   |
| oderwat.indent-rainbow                  | 8.2.2   |
| patricklee.vsnotes                      | 0.7.1   |
| **shd101wyy.markdown-preview-enhanced** | 0.6.1   |
| **TakumiI.markdowntable**               | 0.7.2   |
| tamasfe.even-better-toml                | 0.14.2  |
| yzhang.dictionary-completion            | 1.1.2   |
| **yzhang.markdown-all-in-one**          | 3.4.0   |
| zokugun.explicit-folding                | 0.20.0  |

</div></details>

**Comment by Binly42** [comment]
Not sure whether related.

Currently, the command `editor.action.jumpToBracket` not work for Markdown link nor wikilink. 

I am not insider. Would the latest version cover this problem?

## repro
Given Markdown like:
```Markdown
aaa [bbb] ccc
[[foobar]]
xxx [yyy] zzz
```
- if cursor is before the `]]`, the command would pin the cursor at the center of `]]`.
- if cursor is after the `]]`, the command would do nothing.
- if removed `[[foobar]]`, the command would do nothing.

<details>
<summary>version info</summary>
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
</details>

Tested when all extensions disabled.

Tested the setting `editor.language.brackets` for any of following:
- ```json
    "[md]": { "editor.language.brackets": [ ["[",   "]"],               ], },
    ```
- ```json
    "[md]": { "editor.language.brackets": [ ["[[", "]]"],               ], },
    ```
- ```json
    "[md]": { "editor.language.brackets": [ ["[[", "]]"], ["[",   "]"], ], },
    ```
- without this setting
