### ISSUE TITLE
searchModel can throw

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139054]
Even though this method returns a promise, any error that is thrown before the promise is created will be an exception that upstream clients are probably not expecting to handle:

https://github.com/microsoft/vscode/blob/4ed0329e9c5e12e2c7c59697facc96020b0768ab/src/vs/workbench/contrib/search/common/searchModel.ts#L1050

Error is thrown here:

https://github.com/microsoft/vscode/blob/4ed0329e9c5e12e2c7c59697facc96020b0768ab/src/vs/workbench/contrib/search/common/searchModel.ts#L1061

And upstream handles only `finally`:

https://github.com/microsoft/vscode/blob/2fc1dac22902923e6b97f43694a8aa4e0db3fcce/src/vs/workbench/contrib/searchEditor/browser/searchEditor.ts#L533-L538

So we end up with a progress operation that never finishes.

This would not be happening if `SearchModel.search` was using `async` btw.

Related PR: https://github.com/microsoft/vscode/pull/138430

**Comment by ssigwart** [comment]
> This would not be happening if `SearchModel.search` was using `async` btw.

@bpasero, do you want me to make any changes to #138430 given this comment?
