### ISSUE TITLE
Typescript file resolving issue

### ISSUE THREAD

**Issue by Strate** [Microsoft/vscode#1390]
Hi!

I am using typescript together with webpack and ts-loader. My code compiles successfully via webpack, but in VS Code I get some kind of errors:

![image](https://cloud.githubusercontent.com/assets/392644/11849024/c5161278-a436-11e5-94de-6ba92ae911b4.png)

In my project this file located at `src/lib/utils/storage.ts` and `src/lib/entities/index.ts`. Is there any way to tell VSCode to search that files there?

**Comment by dbaeumer** [comment]
All I can think off is to make the imports relative (eg. ../../). If this doesn't help please open a issue against TypeScript here https://github.com/Microsoft/TypeScript since VSCode uses the tsserver provided by the TS team.
