### ISSUE TITLE
C++ symbol search and other features not working on Linux install

### ISSUE THREAD

**Issue by ericgrossNI** [Microsoft/vscode#13900]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:43:46.054Z)
- OS Version: Linux x64 3.10.0-327.36.1.el7.x86_64 (Scientific Linux 7)
- Extensions: ms-vscode.cpptools-0.9.2

I have used Visual Studio code for quite a few versions on both Windows and Linux. For some reason, none of the symbol database features seem to work on my Linux install. Right-clicking on any symbol or include file only shows "Change all Occurrences", and not peek/go to definition. This works great on Windows. I haven't seen anything in the documentation  that says this feature is Windows-only. Am I missing something?

Steps to Reproduce:

1. Go to any C++ source file.
2. Right click on C++ symbol.
3. Note missing options in right-click menu related to symbol

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-cpptools#292
