### ISSUE TITLE
Scroll bar of test message view is not adaptive when the view height changes

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#139061]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.64.0-insider (user setup)
Commit: 065b450db9f555f177161748e8f2911ebb5677f9
Date: 2021-12-10T05:14:44.789Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Generate a Markdown test message with html support enabled

```ts
const mdString: vscode.MarkdownString = new vscode.MarkdownString();
mdString.supportHtml = true;
for (let i = 0; i < 20; i++) {
    mdString.appendText('hello, world!');
    mdString.appendMarkdown('<br/>');
}
const mdMessage = new vscode.TestMessage(mdString);
```

2. The scroll bar cannot be adaptive when the view height changes (not expand when view size changes and cannot scroll to bottom)

https://user-images.githubusercontent.com/6193897/145951228-368b9855-6c7d-4708-be27-785a39ba448b.mp4

**Comment by rchiodo** [comment]
/verified

Scrollbar now changes size as peek area is expanded.
