### ISSUE TITLE
Extending commit characters for all supported languages

### ISSUE THREAD

**Issue by MK-HDev** [microsoft/vscode#139033]
Its a good job to extending _'**acceptSuggestionOnCommitCharacter**'_ feature to non-ts/js files. either through implementing a general setting or an api for plugin-dependent setting of any specific language plugins.

**Comment by mjbvz** [comment]
This feature is language agnostics

https://github.com/microsoft/vscode/blob/8541d5b225cf6847dd2cf45a43778e1047766702/src/vscode-dts/vscode.d.ts#L4173

If it isn't supported in a given language, please file an issue against them
