### ISSUE TITLE
[vscode.dev] "New File" shortcut shown in menu is incorrect

### ISSUE THREAD

**Issue by tsekityam** [microsoft/vscode#139048]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.0
- OS Version: Microsoft Edge 94.0.992.50 on Windows 10 Enterprise 1909

Steps to Reproduce:

1. Go to https://vscode.dev
2. Press "ctrl + alt + N"
![Screenshot 2021-12-14 at 11 22 29 AM](https://user-images.githubusercontent.com/3814422/145927797-40607810-9472-49c5-a9d7-94c05be2d059.png)

What did I expect:
A new file tab is opened

What did I see:
A new browser tab is opened

What went wrong:
The correct shortcut to create a new file tab is "ctrl + alt + win + N". If I use these combo, then a new file tab is opened corrcetly.
![Screenshot 2021-12-14 at 11 22 35 AM](https://user-images.githubusercontent.com/3814422/145927932-981e46f7-4717-49aa-a7cd-c1c07e174e4a.png)

**Comment by bpasero** [comment]
From https://github.com/microsoft/vscode/commit/f17b1ec6386e9dbef4cbcd26915188a18c3d55d5

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/138991
