### ISSUE TITLE
code.exe won't deal with command-line arguments?

### ISSUE THREAD

**Issue by syehoonkim** [microsoft/vscode#139087]
Dear Mr./Ms.,
Hello.
Recently, I have found that in the latest stable VS Code, inverse search from external PDF Viewer to TeX file doesn't work.
It seems due to that code.exe seems not to deal with command line arguments like -h, -v, etc.
(Please refer to https://github.com/jlelong/LaTeX-Workshop-wiki/issues/89 and https://forum.sumatrapdfreader.org/t/inverse-search-not-performed-for-vs-code-exe/4486)
This can be resolved by using code.cmd instead of code(.exe) file.
But, this solution raises a cmd.exe prompt window.
I know the window disappears quickly, but it bothers some.
So, I wonder if you are planning to make code.exe work with command-line interface.
Thank you.

**Comment by IllusionMH** [comment]
There are no plans to completely replace `code.cmd` to `Code.exe` https://github.com/microsoft/vscode/issues/126149

As for handling CLI arguments - I think you still need that `cli.js` that can be executed with `Code.exe`. Maybe @joaomoreno can provide more insights here.

/assign @joaomoreno

**Comment by syehoonkim** [comment]
@IllusionMH 
Thank you. It seems code.exe dosen't support cli.js by just giving the cli.js path as an argument. Were there any changes on it in the recent update? I heard that additional argument with it at this post: https://forum.sumatrapdfreader.org/t/inverse-search-not-performed-for-vs-code-exe/4486/20
Thank you for answer.

**Comment by syehoonkim** [comment]
Oh, at the latest reply on the article, I found this: https://github.com/microsoft/vscode/issues/136988
You don't have to mind me. Thank you!

**Comment by IllusionMH** [comment]
I think you should follow how it's called in `code.cmd`:
```
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --ms-enable-electron-run-as-node "$@"
```

`ELECTRON_RUN_AS_NODE=1` is required env variable at this moment (see #137510) and pass `--ms-enable-electron-run-as-node` as well.
