### ISSUE TITLE
Terminal Input Auto replies should automatically reply to a custom entry

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139076]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=146748&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=87fb4592-a208-5e50-19ed-a089f1b91f06&l=98

```
1) VSCode Smoke Tests (Web)
       Terminal
         Terminal Input
           Auto replies
             should automatically reply to a custom entry:
     Error: Timeout: get terminal buffer '#terminal .terminal-wrapper' after 20 seconds.
      at poll (/__w/1/s/test/automation/out/code.js:65:19)
      at async Code.waitForTerminalBuffer (/__w/1/s/test/automation/out/code.js:204:9)
      at async Terminal.waitForTerminalText (/__w/1/s/test/automation/out/terminal.js:186:13)
      at async Context.<anonymous> (out/areas/terminal/terminal-input.test.js:33:17)

```

**Comment by Tyriar** [comment]
Added a `itSkipOnFail` util so it will continue to run but only log on a failure

**Comment by bpasero** [comment]
Failed again:

```
1) VSCode Smoke Tests (Web)
       Terminal
         Terminal Input
           Auto replies
             should automatically reply to default "Terminate batch job (Y/N)":
     Error: Timeout: get terminal buffer '#terminal .terminal-wrapper' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:65:19)
      at async Code.waitForTerminalBuffer (D:\a\1\s\test\automation\out\code.js:200:9)
      at async Terminal.waitForTerminalText (D:\a\1\s\test\automation\out\terminal.js:194:13)
      at async Context.<anonymous> (out\areas\terminal\terminal-input.test.js:27:17)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=147484&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=10e09c22-9c76-5ab5-51c4-3709b1557991&l=97

I am running repeated sets of integration + smoke tests in https://github.com/microsoft/vscode/tree/ben/ci-tests-loop to find flaky tests and this one appeared there but only once. I will continue these runs over the weekend and disable tests as I see them fail.

In general I suggest before enabling a test to give it a few runs on a branch to keep `main` stable.

**Comment by Tyriar** [comment]
The trace seems corrupt, the screenshots are out of sync with the actions, and the actions are missing the start of the test

**Comment by bpasero** [comment]
One consequence of running multiple tests one after the other is that the trace is only from the last run, so it may not be matching.

**Comment by Tyriar** [comment]
My guess is this is conpty shenanigans ordering the output wrong or adding cursor move sequences in between, if that happens it's expected to fail though I haven't seen it happen in practice. Will add retries explicitly on Windows for both tests, the other one doesn't appear flaky right now as it only prints "foo", meaning there's a much smaller change for conpty to do weird things.

**Comment by Tyriar** [comment]
Didn't take 😭 

https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=150244
