### ISSUE TITLE
vsdbg always shows exit code 0

### ISSUE THREAD

**Issue by yecril71pl** [microsoft/vscode#139009]
Issue Type: <b>Bug</b>

```C#
return 0XF;
```

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:16:45.441Z)
OS version: Linux x64 5.15.6-1-default
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 9, 9|
|Memory (System)|5.66GB (0.20GB free)|
|Process Argv|--unity-launch --crash-reporter-id 2a03cb52-9f4b-48bf-93d3-5c0537d534ee|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma5|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
vscode-resx-editor|Dom|0.0.5
vscode-pull-request-github|Git|0.34.0
Ionide-fsharp|Ion|5.10.2
better-cpp-syntax|jef|1.15.10
vscode-language-pack-pl|MS-|1.63.2
csharp|ms-|1.23.17
dotnet-interactive-vscode|ms-|1.0.2606010
vscode-dotnet-pack|ms-|1.0.4
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.5
remote-ssh|ms-|0.68.0
remote-ssh-edit|ms-|0.68.0
remote-wsl|ms-|0.63.5
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
vscode-markdown-notebook|ms-|0.0.26
vsliveshare|ms-|1.0.5196
vsliveshare-audio|ms-|0.1.91
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710:30405998

```

</details>

**Comment by Tyriar** [comment]
Sounds like a C++/C# extension problem?

**Comment by yecril71pl** [comment]
https://github.com/OmniSharp/omnisharp-vscode/issues/3084
