### ISSUE TITLE
Files not loading in Ctrl+P search for VSCode since upgrade to 1.63.0

### ISSUE THREAD

**Issue by syed-shahjahan** [microsoft/vscode#139056]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.0
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Open any project
2. Enter ctrl+p then type the filename
3. Files list will keep loading instead of showing result files.
4. Below is the resulting image
![image](https://user-images.githubusercontent.com/42941326/145946623-52544870-5b95-49e7-80a9-a54a8b349cba.png)

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by eaylward8** [comment]
I'm also experiencing this. In addition, VS Code source control is not recognizing that my project is a git repo. These issues were present for me the other day and were resolved after restarting my computer. However, they've come back and this time restarting did not make any difference.

I used Start Extension Bisect and the issues were still present when all extensions were disabled.

Version: 1.63.1
Commit: fe719cd3e5825bf14e14182fddeb88ee8daf044f
Date: 2021-12-14T02:13:46.212Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.1.0

**Comment by roblourens** [comment]
Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages or any error messages in the "Log (Window)" and "Log (Extension Host)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by syed-shahjahan** [comment]
I ran the commands you gave above but I don't really find any issues in Logs. Below are my observations experienced on different versoins,

- VS Code Version: 1.63.0: Didn't work
- VS Code Version: 1.63.1: **Worked**
- VS Code Version: 1.63.2: Didn't work

**Comment by syed-shahjahan** [comment]
Attaching the log files "`Log Window, Log Extension Host`"here,

[Log-Extension Host.txt](https://github.com/microsoft/vscode/files/7760400/Log-Extension.Host.txt)
[Log-Window.txt](https://github.com/microsoft/vscode/files/7760401/Log-Window.txt)

**Comment by roblourens** [comment]
It doesn't look like these are logs from "trace"

> Run the command "Set log level" and change it to "Trace"

**Comment by syed-shahjahan** [comment]
Facing a problem when having multiple workspaces on the Explorer.

Started working when `"extension.prophet.sandbox.filesystem.enabled": false,` line is removed from settings.json file which was working before.

Hope this issue will be taken care of on later release.

**Comment by SqrTT** [comment]
this is not cased by extension. the issue is the same as was before https://github.com/microsoft/vscode/issues/94928

(waits for SerchResult infinitely)

**Comment by gjsjohnmurray** [comment]
Probably #140737
