### ISSUE TITLE
Workspace file not opening with vscode.openFolder() 

### ISSUE THREAD

**Issue by ratkinson-prh** [microsoft/vscode#139010]
Issue Type: <b>Bug</b>

I have a number of extensions installed that use vscode.openFolder() - see https://github.com/auchenberg/vscode-open-file-folder as a very simple example.

According to the documentation, VS Code should open the folder as a workspace if one exists, but it doesn't (there is no 'Workspace' tag in the Explorer tree).

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (7.36GB free)|
|Process Argv|--crash-reporter-id 03e7ca5b-1570-4b62-9db2-6eb210844ee9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-open-file-folder|auc|0.0.4
gitlens|eam|11.7.0
powershell|ms-|2021.10.2
favorites|ole|1.5.7
code-spell-checker|str|2.0.13
shell-launcher|Tyr|0.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30405999
vscexrecpromp3t3:30407764

```

</details>

**Comment by ratkinson-prh** [comment]
Hi @bpasero - can you point me in the right direction as to what additional information you need?   I've had a quick read through the guidelines, but I can't see anything too obvious that I've missed.

Thanks, Rob

**Comment by bpasero** [comment]
Maybe start with a minimal reproducible extension sample code to show the issue by pasting the code here.

**Comment by ratkinson-prh** [comment]
This is the smallest piece of code I can get down to Banjamin :-

```
import * as vscode from 'vscode';
import * as os from 'os';
import * as path from 'path';
import * as fs from 'fs';
import { Uri, commands } from 'vscode';
. . . . .
let workspace_file = Uri.file(workspace)
commands.executeCommand('vscode.open', workspace_file, newWindow)
```

I've run it in debug mode, and the value of workspace is 'u:\\WindowsPowerShell\\Powershell Projects\\Scratch Area\\Scratch Area.code-workspace'

workspace_file come back from Uri.file as....

{
  scheme: "file",
  authority: "",
  path: "/u:/WindowsPowerShell/Powershell Projects/Scratch Area/Scratch Area.code-workspace",
  query: "",
  fragment: "",
  _formatted: null,
  _fsPath: null,
}

VS Code re-opens the GUI with the workspace, but it appears to open it as a folder and NOT the workspace.

The code in vscode.Open() is compressed, so difficult for me to step through to see what exact methods are being called, and how it differs from the 'Open workspace from file....' option in the File menu.

Thanks, Rob.

**Comment by bpasero** [comment]
I cannot reproduce, here is my code:

```ts
const uri = vscode.Uri.file('/Users/bpasero/Documents/playground.code-workspace');
vscode.commands.executeCommand('vscode.openFolder', uri);
```

**Comment by ratkinson-prh** [comment]
Thanks Benjamin. I've been working with the author of Favorites.vscode as well, and he's sent me logging output that shows he's using exactly the same calls to openFolder() as I am but also doesn't see the same problem.

Clearly this is an environmental problem I'm experiencing, I'm guessing either virus scanner or Windows UAC.

I appreciate the time you've taken to help me get this far, and happy for you to close the issue.

Thanks, Rob.
