### ISSUE TITLE
Inlined variable values affect cursor position at debug mode

### ISSUE THREAD

**Issue by agusakow** [microsoft/vscode#139023]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.63.0
- OS Version: macOS Big Sur 11.4

Steps to Reproduce:

1. Open Settings > Features > Debug
2. Set **Inline Values** : true
3. create js file with any variable assignments, for example: 
```javascript
var arr = [1, 2, 3, 4, 5]
print(arr)
```
4. **Run and Debug** this code
5. Paste cursor at the first column second line, press left

Expected cursor position:
```javascript
var arr = [1, 2, 3, 4, 5]| /*variable value*/
print(arr)
```
Actual cursor position:
```javascript
var arr = [1, 2, 3, 4, 5] /*variable value*/|
print(arr)
```
Also inlined values affect text selection.

![](https://camo.githubusercontent.com/72ceb8b2cee2c00fb4f8b793e132767924ddefe2a02cd2af1060d6c79e737957/68747470733a2f2f692e696d6775722e636f6d2f4374716c4269362e676966)

**Comment by weinand** [comment]
@agusakow thanks for reporting this. 
I could easily reproduce this in Mock Debug.

@hediet this seems to be a regression in the interaction between selection handling and text's inline feature.

In the 1.62 October release this worked fine:
![CleanShot 2021-12-13 at 22 18 35](https://user-images.githubusercontent.com/1898161/145890469-2b3bf2aa-c7ab-41ba-a259-ebddfe3305a1.gif)

In November (1.63) this is broken:
![CleanShot 2021-12-13 at 22 22 54](https://user-images.githubusercontent.com/1898161/145890992-03e0501a-343b-499f-8aec-d0b09e0d02bd.gif)

**Comment by weinand** [comment]
@hediet this is still an issue in the latest Insiders.

**Comment by weinand** [comment]
@hediet your fix addresses only a part of the problem: now it is no longer possible to set the caret at the right end of the inline value. But it is still possible to set the caret on the left end.
The correct behavior would only allow to set the caret at right end of the last character of the regular text.

**Comment by hediet** [comment]
> But it is still possible to set the caret on the left beginning of the inline value (this is not correct).

I think this is a duplicate of https://github.com/microsoft/vscode/issues/135955.
