### ISSUE TITLE
vscode 1.63.0 broke `runTests` of `@vscode/test-web` with `extensionPaths`

### ISSUE THREAD

**Issue by stevenguh** [microsoft/vscode#139053]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.0
- OS Version: Darwin x64 20.6.0

Steps to Reproduce:

1. `git clone https://github.com/VSpaceCode/VSpaceCode.git`
2. `cd VSpaceCode && npm install && npm run compile && npm run test-web`

ACTUAL: The output indicated the additional extension (dependent extension) provided failed to load which caused the extension being tested failed to activate.
```
Ignoring following additional builtin extensions as there is an error while fetching them from gallery [ null ] Cannot read properties of undefined (reading 'toLowerCase')
```
EXPECTED: 
The additional extensions provided loads correctly.

---

Verified that this behavior doesn't exist in vscode 1.62.3.

Steps:
1. `git clone https://github.com/VSpaceCode/VSpaceCode.git`
2.  Change `version: 'stable',` to `version: 'sources',/` of [runTest-web.ts](https://github.com/VSpaceCode/VSpaceCode/blob/master/src/test/runTest-web.ts#L109)
3. `git clone https://github.com/microsoft/vscode.git`
4. `cd vscode && git checkout 1.62.3 && yarn && yarn compile && yarn web`
5. `cd ../VSpaceCode && npm install && npm run compile && npm run test-web`

**Comment by aeschli** [comment]
@sandy081 The problem is with the isUri test:


![image](https://user-images.githubusercontent.com/6461412/146259449-9497adde-2d85-4a4a-977c-0e9a4cae062e.png)
