### ISSUE TITLE
Terminal auto replies smoke tests are flaky

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139083]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=146764&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=87fb4592-a208-5e50-19ed-a089f1b91f06&l=98

```
1) VSCode Smoke Tests (Web)
       Terminal
         Terminal Input
           Auto replies
             should automatically reply to default "Terminate batch job (Y/N)":
     Error: Timeout: get terminal buffer '#terminal .terminal-wrapper' after 20 seconds.
      at poll (/__w/1/s/test/automation/out/code.js:65:19)
      at async Code.waitForTerminalBuffer (/__w/1/s/test/automation/out/code.js:204:9)
      at async Terminal.waitForTerminalText (/__w/1/s/test/automation/out/terminal.js:186:13)
      at async Context.<anonymous> (out/areas/terminal/terminal-input.test.js:27:17)

  2) VSCode Smoke Tests (Web)
       Terminal
         Terminal Input
           Auto replies
             should automatically reply to a custom entry:
     Error: Timeout: get terminal buffer '#terminal .terminal-wrapper' after 20 seconds.
      at poll (/__w/1/s/test/automation/out/code.js:65:19)
      at async Code.waitForTerminalBuffer (/__w/1/s/test/automation/out/code.js:204:9)
      at async Terminal.waitForTerminalText (/__w/1/s/test/automation/out/terminal.js:186:13)
      at async Context.<anonymous> (out/areas/terminal/terminal-input.test.js:33:17)
```

**Comment by Tyriar** [comment]
These are currently skipping on fail.

**Comment by Tyriar** [comment]
Interesting, the terminal really never gets any content:

![image](https://user-images.githubusercontent.com/2193314/146391359-c420a5c9-09e2-4fa2-b2e9-eb44efaa0ff5.png)

**Comment by Tyriar** [comment]
To make sure nothing weird is going on with the webgl renderer and to help diagnose future problems, I'm going to switch the default to DOM for the smoke tests.

**Comment by bpasero** [comment]
I think we might also be running with `--disable-gpu` in CI runs.

**Comment by Tyriar** [comment]
@bpasero that's fine, that means it would fallback to the canvas renderer and use software rendering. I've noticed the trace viewer only shows screenshots in the top part, the main preview shows nothing for those textures. This change will just make sure the terminal buffer shows up in both the screenshots and the main preview.

**Comment by Tyriar** [comment]
Re-enabling these tests without skip so I get pinged on the next failure, should be more actionable with the DOM renderer.

**Comment by Tyriar** [comment]
New failed run with trace: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=147273&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=500500fc-d3cc-5138-3a2a-6935e05fea33&l=97

**Comment by Tyriar** [comment]
Interesting...

![image](https://user-images.githubusercontent.com/2193314/146585474-9b11226f-d307-4f68-823b-3ac4b9aef0f9.png)

This is either a bug with sh or local echo causing this unexpected order. Will make the test handle this as the order isn't important to the feature.
