### ISSUE TITLE
Problem matcher not work or I doing something wrong

### ISSUE THREAD

**Issue by GSoftwareDevelopment** [microsoft/vscode#139007]
I have created a task to compile a program written in MAD Pascal (a kind of Pascal for the 6502 processor)
I wanted any problems occurring during the compilation process to be shown in the "Problems" window.
The following fragment of the `tasks.jso` file
~~~json
{
	"label": "Compile source",
	"type": "shell",
	"command": "~/Atari/MadPascal/mp ${fileBasename} -o",
	"presentation": {
		"echo": false,
		"reveal": "silent",
		"focus": false,
		"panel": "shared",
		"showReuseMessage": false,
		"clear": true
	},
	"problemMatcher": {
		"fileLocation": ["relative", "${workspaceFolder}"],
		"pattern": [
			{
				"regexp": "/^(.+)\\s\\((\\d+),(\\d+)\\):\\s(\\w+):(.+)$",
				"file": 1,
				"line": 2,
				"column": 3,
				"severity": 4,
				"message": 5
			}
		]
	}
}
~~~
I checked the regular expression and it seems to correctly extract information from the result in the console ( [regexp in regex101](https://regex101.com/r/U9KA5Q/1) )
However, it does not work. I don't get any messages in the "Problems" window

What am I doing wrong, or what do I not understand about setting up a Problem Matcher for tasks?

**Comment by GSoftwareDevelopment** [comment]
I managed to find a solution - it was my mistake in writing the regular expression (one colon too many :) )

However, there was another problem.
It looks like ProblemMatcher accumulates errors. More precisely, it doesn't always remove the previous ones. It's hard to replicate, because sometimes it deletes, and sometimes it just adds new errors. I need to see if there is a similar error reported.

**Comment by alexr00** [comment]
The errors accumulating can occur when you're modifying the task (each time you change it, we see it as a different task, and don't delete the previous errors). Once you're done editing your task you should see the errors correctly be removed.

**Comment by GSoftwareDevelopment** [comment]
This would explain, difficult to reproduce, the process of presenting the problem :)
Thanks.

For my side, I consider the problem closed
