### ISSUE TITLE
`FileUserDataProvider` is a bit weird

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139060]
Maybe the `FileUserDataProvider` can become obsolete once [atomic reads](https://github.com/microsoft/vscode/issues/139058) land but still wanted to report it:

https://github.com/microsoft/vscode/blob/1944e5d1335c5f298df5330371df1f7a7cd085d4/src/vs/workbench/services/userData/common/fileUserDataProvider.ts#L15

seems to wrap around a disk file system provider, but does some weird things:
* why does it have to probe on the capabilities of the provider that is passed in, can we not declare the right set of interfaces from the passed in provider and be good with it?
* why do we need to wrap around the disk provider at all, the risk here is that adding new capabilities to the disk provider (such as atomic read support) would need to be adopted also in the user data provider

**Comment by sandy081** [comment]
This will be cleaned along with https://github.com/microsoft/vscode/issues/126376
