### ISSUE TITLE
Minimize number of extension query requests to Marketplace

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#139015]
Minimize number of extension query requests to Marketplace

- At present, one request is made per each installed extension when the latest version of that extension in the marketplace is not compatible. Change it to one request for all such extensions.

- At present, an additional request is made to know if there is a release version or not even when requested for pre-release version. This is to support the feature - not to show install release version button or not to show switch to release version button - https://github.com/microsoft/vscode/issues/138231. Since this adds additional overhead on MP, lets unsupport this feature and support it when MP moves to SemVer with proper efficient query API.

**Comment by sandy081** [comment]
Improvements:

- Refactored `ExtensionsGalleryService` to funnel all workbench Marketplace queries into single `queryGalleryExtensions` method which can serve all purposes (compatible, target platform, version, pre-release...)
- let workbench make single request (max 2 queries) to query all latest compatible installed extensions while checking for updates. Before there can be more requests if the latest versions are not compatible.

**Comment by sandy081** [comment]
cc @SaiKanth007

**Comment by SaiKanth007** [comment]
I also remember we discussed that having two instances of VSCode editors open will make two different update calls to marketplace, even that is optimized as part of this ?

**Comment by sandy081** [comment]
> I also remember we discussed that having two instances of VSCode editors open will make two different update calls to marketplace, even that is optimized as part of this ?

No, that needs considerable design changes and felt not worth the change. Current optimizations listed above are already good enough.
