### ISSUE TITLE
Middle mouse click on taskbar icon doesn't open a new window

### ISSUE THREAD

**Issue by cozzbp** [Microsoft/vscode#13905]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: abotteram.typescript-react-snippets-0.1.9, hars.CppSnippets-0.0.5, lukehoban.Go-0.6.44, ms-vscode.cpptools-0.9.2

Steps to Reproduce:
1. Middle click on running VS Code icon on the taskbar, it doesn't open a new window like many programs
2.  You can open a new window by right clicking the icon and choosing "New Window"

**Comment by jhasse** [comment]
Related: When working with multiple workspaces, clicking on VS Code in the taskbar on a workspace where it hasn't been started yet switches to a running instance on another workspace instead of starting a new one.

**Comment by peredin** [comment]
This has to be fixed, very annoying now that Windows finally has multiple virtual desktops natively.

VS Code should automatically open a new window upon execution. This way, Windows will take care of activating an existing window unless shift is held while clicking the button, or, opening a new VS Code window.

**Comment by cozzbp** [comment]
It may actually be a problem with electron apps in general.  Postman also exhibits this behavior.

**Comment by the-ress** [comment]
I think it should be done by setting [System.AppUserModel.RelaunchCommand](https://msdn.microsoft.com/en-us/library/windows/desktop/dd391571.aspx) with `-n` argument.

It will need to be implemented in Electron (like e.g. jump lists).

**Comment by bpasero** [comment]
Depends on https://github.com/Microsoft/vscode/pull/23800

**Comment by chrmarti** [comment]
- VSCode Version: Code - Insiders 1.12.0-insider (d8a1d8b8a7c886547ba6bc0d81fc2ff639d4c9f5, 2017-04-27T06:12:15.095Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none

'New Window' works, but middle click and Shift + left click still don't.

**Comment by the-ress** [comment]
I've just finished some investigation into this. It works when launch VSCode using `scripts\code.bat`, but not when I build `VSCodeSetup.exe` and install it.

The shortcut in start menu (which has the same AppUserModelID as the window) seems to take priority over the `RelaunchCommand` value. (I couldn't find any way to override this.)

AppUserModelID of the shortcut and the window needs to match so they share one MFU list and jump list.

Only solution I can think of is to add the `-n` argument to the start menu shortcut too.

**Comment by bpasero** [comment]
I am a bit confused, I could swear I tested this. But probably only from a local built VS Code, never when going through the setup. Too bad...

**Comment by todorm85** [comment]
Had similar issue with sublime, managed to get it working by adding the -noframemerging switch to the target of the shortcut. Right click on shortcut to vscode, go to shortcut tab and in target add -noframemerging after the path to the executable (should be outside the quotes).

**Comment by dmrickey** [comment]
How is this still a thing?

**Comment by bpasero** [comment]
@the-ress I cannot really explain it but with our current insiders release, middle-click on the taskbar opens a new window for me (stable does not work).

Can others try to reproduce this with our insiders: https://code.visualstudio.com/insiders/

I am very confused what change could have an impact :-/

**Comment by bpasero** [comment]
Wow, now I am back to having it NOT working in insiders, this is very weird....

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/45322
