### ISSUE TITLE
Params in snippets not working if put after double backslash

### ISSUE THREAD

**Issue by deitry** [microsoft/vscode#139062]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62, 1.63.0
- OS Version: Windows 10 21H1

Steps to Reproduce:

1. Call "Configure User Snippets" command and create new snippets file with
```json
{
	"test_snippet": {
		"body": "windows\\path\\${1:param}",
	}
}
```
2. Go to any file and insert new snippet.

Expected:
```
windows\path\param
```
Actual:
```
windows\path${1:param}
```

**Comment by jrieken** [comment]
The `\\$` escapes the `$` sign. Use `windows\\path\\\\${1:param}`

**Comment by deitry** [comment]
So, this double-double backslash escapes backslash itself. Thanks, that worked.
