### ISSUE TITLE
1.6+ Version has problem hitting breakpoints on transpiled code (ES6/Babel)

### ISSUE THREAD

**Issue by jeromu** [Microsoft/vscode#13907]
- VSCode Version: 1.6 (1.6.1 as well) - Using the new '**outFiles**' option (instead of the deprecated 'outDir')
- OS Version: windows

Steps to Reproduce:
1. Using a ES6/Babel project, transpile, and use source maps in debug configuration
2. Add breakpoint
3. Try to hit breakpoint

Observed:
-Hit breakpoint, but on the wrong line.  (used to work fine in previous versions of VSCode < 1.6)

Note: using '**outDir**' never hits any breakpoints.

**Comment by roblourens** [comment]
Does it work if you use `"type": "node2"`? Just curious because this is our new experimental Node debugger.

**Comment by jeromu** [comment]
Using "type": "node2".... The debugger doesn't start, I get the following in the Debug output:
node --inspect=7599 --debug-brk --nolazy server\bin\server.js 
node: bad option: --inspect=7599

**Comment by roblourens** [comment]
Thanks for trying it but it only works for newer versions of Node, which I should have mentioned.

**Comment by jeromu** [comment]
Small test project that can hit breakpoints in 1.5.3 but cannot in 1.6.x:
[vscode_es6.zip](https://github.com/Microsoft/vscode/files/535078/vscode_es6.zip)

> npm install
> npm run build    /// to transpile and generate source maps

-Set breakpoints in src/server.js
-Start the 'Launch' launch config.

**Comment by roblourens** [comment]
This works fine now (1.5 years later)
