### ISSUE TITLE
Hyphen in snippet prefix de-indents snippet

### ISSUE THREAD

**Issue by kierang12** [microsoft/vscode#139016]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.0
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Configure VSCode to use the attached snippets file
2. Indent some spaces
3. Insert the "Foo- Bar" snippet by typing "bar" \<TAB\>

The snippet is inserted with one space fewer indentation than the current indent level.

If the snippet is inserted by typing "foo" - the snippet inserts normally.

Seems to be to do with a hyphen being in the snippet prefix, followed by a space.

Behaviour not present in 1.62.3

![recording(2)](https://user-images.githubusercontent.com/96078447/145867249-092d14ae-2997-4d66-b9ee-a86939ceb851.gif)

[test_snippets.zip](https://github.com/microsoft/vscode/files/7705977/test_snippets.zip)

**Comment by jrieken** [comment]
Can you try this with [VS Code Insiders](https://code.visualstudio.com/insiders/)?

**Comment by kierang12** [comment]
Thanks, not sure if I'm missing something with installing Insiders. Downloaded from the link provided, but the build seems 4 days old, and the commit that solves #138707 is after the commit referenced in the Help > About box. 

Help > Check for updates tells me there are currently no updates available

Version: 1.64.0-insider
Commit: 065b450db9f555f177161748e8f2911ebb5677f9
Date: 2021-12-10T05:14:44.789Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

For what it's worth, behaviour still present here.

**Comment by jrieken** [comment]
Latest insiders is on `745ef8b8264e12b2a704f6b2b60a2ce2cabfcda3 `

**Comment by kierang12** [comment]
Updated insiders to 745ef8b8264e12b2a704f6b2b60a2ce2cabfcda3

Behaviour still exists.


Snippet here, for ease:
```json
{
    "FooBar": {
        "prefix": "Foo- Bar",
        "body": [
            "Foo",
        ],
    }
}
```

**Comment by jrieken** [comment]
I do reproduce. Thanks for clarifying so quickly

**Comment by jrieken** [comment]
The root cause is the (still good) fix for https://github.com/microsoft/vscode/issues/123860. To fix the aforementioned issue we changed that snippet prefix matching isn't "locked" to word starts anymore. In this case it means the `Foo- Bar` snippet is freely aligned with ` bar` (e.g the `bar`-word plus its leading whitespace)

**Comment by kierang12** [comment]
There seems to be some related fun here with camelCase here too:
```json
{
	"FooBar": {
		"prefix": "FooBar Baz",
		"body": [
			"Foo",
		],
	}
}
```

Calling this snippet with `bar` casuses the 1 space de-indent
