### ISSUE TITLE
Can't save and next stop running

### ISSUE THREAD

**Issue by lilonghe** [Microsoft/vscode#13913]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: formulahendry.auto-rename-tag-0.0.7, robertohuertasm.vscode-icons-3.0.5

![2016-10-18_094845](https://cloud.githubusercontent.com/assets/12867278/19461559/292207fe-9518-11e6-8f6f-916ac4235892.png)

**Comment by roblourens** [comment]
I'm not sure what the problem is. Could you please explain the problem a little more?

**Comment by weinand** [comment]
closing issue since there was no response after 7 days
