### ISSUE TITLE
ms-toolsai.jupyter cannot use proposed api

### ISSUE THREAD

**Issue by serbInit** [microsoft/vscode#139138]
Does this issue occur when all extensions are disabled?: No

Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-07T19:37:13.664Z
Electron: 13.6.3
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.15.6-2-MANJARO

Steps to Reproduce:

1. Install ms-toolsai.jupyter
2. try to activate it

Error : Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-toolsai.jupyter

**Comment by mjbvz** [comment]
Does it work if you update to the latest VS Code version: 1.63.1?

**Comment by jrieken** [comment]
what version of jupyter do you use?
