### ISSUE TITLE
Interactive python Cell no longer collapsing by default

### ISSUE THREAD

**Issue by lyndond** [microsoft/vscode#139147]
Issue Type: <b>Bug</b>

Running a Cell (delineated by #%% ). Input code in the Interactive pane always is showing despite having Collapse set to default in the settings.

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:13.580Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.96.1.fi

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (40.12GB free)|
|Process Argv|--crash-reporter-id e994e0e5-e06c-471a-b489-a9ce30009c61|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: rusty1|
|OS|Linux x64 5.4.96.1.fi|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (56 x 1203)|
|Memory (System)|503.82GB (441.28GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.15.10
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.11
vim|vsc|1.21.10
gitignore|cod|0.7.0
gitlens|eam|11.7.0
vscode-pull-request-github|Git|0.34.1
intellij-idea-keybindings|k--|1.5.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
vscodeintellicode|Vis|1.2.15

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
javagetstartedt:30391933
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30405999
vscexrecpromp3t2:30407763
vscop841cf:30413486
vscop927cf:30413487
vscop436cf:30413488

```

</details>

**Comment by rebornix** [comment]
Thanks for reporting, this will be fixed in next recovery build (coming tomorrow)
