### ISSUE TITLE
Can't delete row from setting

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#139175]
1. Search for `terminal auto` in settings
2. Try removing the only row on that table by clicking the `X`

![image](https://user-images.githubusercontent.com/22350/146147222-0c2ac5a0-5f82-42d4-a14b-e343d7620d56.png)

cc @Tyriar

**Comment by vaindil** [comment]
Just a note if it helps or matters somehow: Manually setting `"terminal.integrated.autoReplies": {}` does not disable the feature, I restarted VS Code completely to verify that the setting took and it still sends Y.

**Comment by rzhao271** [comment]
Verification:
1. https://github.com/microsoft/vscode/issues/139175#issue-1080705720 should be resolved. The settings JSON file should display `{}` as the value.
2. Reset that auto replies setting, and then add another row to the value. The original default value should not disappear, and it should also show up in the settings JSON.

**Comment by rzhao271** [comment]
The fix breaks https://github.com/microsoft/vscode/issues/142820 and causes more confusion for extension authors and anyone who knows that the settings follow a merging strategy rather than an override strategy. I'll revert the commit above.

**Comment by rzhao271** [comment]
Verification steps:
1. Clone and run the extension https://github.com/rzhao271/vsc-objs-with-defaults.
2. Navigate to the Settings editor.
3. Search for the setting `vsc-obj-with-defaults.exampleObjectSetting`.
4. Verify that the key1 row cannot be deleted, but that its value can be modified and then reset.

**Comment by joaomoreno** [comment]
Now I can't ever delete the first row, even if I have two rows:

![image](https://user-images.githubusercontent.com/22350/176456438-31d96b96-6b67-4cc9-af00-c9a34424dbab.png)

It's not obvious to me why is it that I can't simply delete that row:

![image](https://user-images.githubusercontent.com/22350/176456546-a1251014-2c67-4973-bdae-b8a1abc3f5d0.png)

It seems that the only valid states from the UI are:

- { key1: string }
- { key1: string, key2: string }

But from the config declaration, it seems the following two states should also be possible:

- {}
- { key2: string }

**Comment by rzhao271** [comment]
If `{}` is possible, how do we display default object values to the user? Object setting values work by doing something like `finalObjSettingValue = {...defaultValue, ...userValue, ...workspaceValue}`. If the user deletes key1, they might think they have unset key1, but they haven't. The Settings editor doesn't support that yet. Also see https://github.com/microsoft/vscode/issues/142820
