### ISSUE TITLE
LiveShare: Unable to join in vscode.dev

### ISSUE THREAD

**Issue by jonny-sloan-abzu** [microsoft/vscode#139186]
Hi,

When trying to join a liveshare session via browser I get redirected from a url like `https://prod.liveshare.vsengsaas.visualstudio.com/join?{hash}` to `https://vscode.dev/liveshare/{hash}`, and then the error message `Joining collaboration session: Direct connection not supported on the browser.` when trying to join as an anonymous user.

This functionality worked fine about a week ago.

The browser I'm using is the user agent metadata below:

Version: 1.63.1
Commit: fe719cd3e5825bf14e14182fddeb88ee8daf044f
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0
Embedder: vscode.dev

Thanks

**Comment by LeCoupa** [comment]
I am also getting this issue

**Comment by huydhoang** [comment]
Having the same issue. Any workaround?

**Comment by LeCoupa** [comment]
@huydhoang, you can use live share on the app for the time being. Works fine over there.

**Comment by huydhoang** [comment]
> @huydhoang, you can use live share on the app for the time being. Works fine over there.

Thanks, that seems to be the best alternative for now. Hopefully this will get fixed soon.

**Comment by ja-ro-pe** [comment]
Glad to see this isn't just me. But would like to know what the fix is???

**Comment by Fi1osof** [comment]
Me too

**Comment by joaomoreno** [comment]
@jramsay @lostintangent Are you aware of this? Is there any issue tracker we can move this issue to?

**Comment by jramsay** [comment]
@jonny-sloan-abzu: thanks for creating this issue! We've released a fix to the VS Code Marketplace (Live Share 1.0.5201)
