### ISSUE TITLE
Occasional prompts to switch display language

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#139151]
Issue Type: <b>Bug</b>

(sorry, these are not good steps because I can't figure out exactly what triggers this)

1. Have a language pack installed (I have the german pack)
1. Open a new workspace or reload VS Code

**Bug**
Sometimes I get a prompt to switch display languages. I select no but the prompt will come back again later

I see this maybe once or twice a day and haven't figured out exactly what is causing it

VS Code version: Code - Insiders 1.64.0-insider (Universal) (886fd126446cd4b8b03f2b32f09c173dec541e6d, 2021-12-14T13:26:59.630Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
salesforce-soql-editor|all|1.8.0
tsl-problem-matcher|amo|0.5.0
comment-tagged-templates|bie|0.3.1
docs-view|bie|0.0.9
emojisense|bie|0.9.0
folder-source-actions|bie|0.2.1
jsdoc-markdown-highlighting|bie|0.0.1
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-yaml-preamble|bie|0.1.0
test-ext|bie|0.0.1
vscode-eslint|dba|2.2.2
dendron|den|0.73.0
dendron-paste-image|den|1.1.0
typescript-notebook|don|2.0.6
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
codespaces|Git|1.4.2
copilot|Git|1.7.4273
remotehub|Git|0.20.0
vscode-pull-request-github|Git|0.35.2021121409
vscode-drawio|hed|1.6.3
vscode-postfix-ts|ipa|1.9.4
latex-workshop|Jam|8.22.0
vscode-platform-specific-sample|joa|1.15.0
vscode-platform-specific-sample|joa|1.5.0
vscode-memfs|jri|0.0.3
template-string-converter|meg|0.5.5
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.18.0
vscode-language-pack-de|MS-|1.63.3
python|ms-|2022.0.1578295602-dev
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2022.1.1001576989
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
azure-account|ms-|0.9.11
hexeditor|ms-|1.8.2
js-debug-nightly|ms-|2021.11.1217
live-server|ms-|0.2.11
vscode-github-issue-notebooks|ms-|0.0.113
vsliveshare|ms-|1.0.5196
debugger-for-chrome|msj|4.13.0
vetur|oct|0.35.0
code-spell-checker|str|2.0.13
rest-book|tan|5.0.1
ayu|tea|1.0.5
luna-paint|Tyr|0.11.0
sort-lines|Tyr|1.9.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
javagetstartedt:30350119
vsaa593cf:30376535
vsc1dst:30396469
pythonvs932:30404738
vscop804:30404766
vscop453:30404998
vsclayoutctrt:30405800
py55gd98cf:30408622
vscexrecpromp3t3:30407760
azactmsalcf:30409288

```

</details>

**Comment by dbaeumer** [comment]
@TylerLeonhardt please ping if you need help with this.

**Comment by mjbvz** [comment]
Here's the code that seems to trigger this: https://github.com/microsoft/vscode/blob/4df57580d323ab2bb9dfaaafb347d24be018a49a/src/vs/workbench/contrib/localizations/browser/localizations.contribution.ts#L54

Would extension updates also trigger this?

**Comment by TylerLeonhardt** [comment]
@rzhao271 and I looked into this with https://github.com/microsoft/vscode/pull/171121 and we were shocked to see that background updating of an extension had an InstallOperation of "Install" and not "Update"

https://github.com/microsoft/vscode/blob/82cc78f9ec75c80ecd4ff1d03992de2ad6f72e68/src/vs/workbench/contrib/localization/electron-sandbox/localization.contribution.ts#L60

Is this correct @sandy081?

Easy repro steps:

* Using OSS with the marketplace
* Place a breakpoint on the line linked above ^ (or just at the top of `onDidInstallExtensions`)
* Install an old version of a language pack
* No longer "Ingore Updates"
* Reload the window

Your breakpoint will hit when the language pack updates to the latest version again and you'll notice the `operation` is set to `Install` (aka 2) instead of `Update`.

**Comment by sandy081** [comment]
Yeah, it's a bug on my side that I am not propagating the operation properly. Sorry about that. Fixed.

**Comment by bhavyaus** [comment]
I did a lang pack install and used it for half a day and didn't seen any prompts to switch display language. Is there anything other way to verify this?

**Comment by rzhao271** [comment]
I have the German language pack installed but haven't been using it. I haven't seen any prompts to switch to German recently so :+1:
