### ISSUE TITLE
iframe within a webview does not allow you to use drag and drop

### ISSUE THREAD

**Issue by estruyf** [microsoft/vscode#139111]
Issue Type: <b>Bug</b>

Following the sample on the docs to open an iframe within a webview: https://code.visualstudio.com/api/advanced-topics/remote-extensions#option-1-use-asexternaluri - I noticed that drag&drop functionality is not working on the iframe its content.

On the webview, it all works fine, but inside the iframe its contents it's not working. It seems that events are just ignored or not correctly bubble down to the iframe.

When loading the same site/page from outside VS Code, within an iframe, it works fine. So it seems to be the communication from the webview in VS Code to the iframe.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:18.361Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|/Users/eliostruyf/nodejs/vscode/vscode-front-matter/ --crash-reporter-id 9cbfe442-202a-4d78-939e-58df82641e13|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
quitcontrol-vscode|art|4.0.0
vscode-tailwindcss|bra|0.7.4
language-hugo-vscode|bud|1.3.1
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.6.0
language-postcss|cpy|1.1.0
vscode-svgviewer|css|2.0.0
postcss|css|1.0.9
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
spfx-snippets|eli|1.11.1
vscode-extension-panel|eli|0.0.2
vscode-front-matter-beta|eli|5.7.1548668
vscode-hide-comments|eli|1.5.0
vscode-hugo-themer|eli|0.0.2
vscode-msgraph-autocomplete|eli|1.2.0
vscode-msgraph-essentials|eli|0.0.5
vscode-remote-control|eli|1.0.0
vscode-typescript-exportallmodules|eli|2.2.0
prettier-vscode|esb|9.0.0
copilot|Git|1.7.4273
vscode-guid|hea|1.4.20
beautify|Hoo|1.5.0
vscode-react-typescript|inf|1.3.1
vscode-peacock|joh|4.0.0
json-to-ts|Mar|1.7.5
vscode-github-actions|me-|3.0.1
fluent-icons|mig|0.0.15
azure-pipelines|ms-|1.195.0
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
azure-account|ms-|0.9.11
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-edge|msj|1.0.15
material-icon-theme|PKi|4.11.0
vscode-thunder-client|ran|1.9.1
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.2
autoimport|ste|1.5.4
errorlens|use|3.4.1
vscodeintellicode|Vis|1.2.15
vscode-icons|vsc|11.8.0
vscode-todo-highlight|way|1.0.5
fig|wit|0.0.5
vscode-import-cost|wix|2.15.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710:30405998
vscexrecpromp3t3:30407764

```

</details>

**Comment by mjbvz** [comment]
Can you avoid using an iframe? They generally don't play nicely with VS Code without extra work

**Comment by estruyf** [comment]
Unfortunately not. There are indeed some pitfalls of using the iframe approach, but they also provide major benefits to the development process. 

I can overcome the pitfalls by creating a good communication strategy between vscode -> webview -> iframe. Currently, the only blocking factor is the drag&drop.

**Comment by estruyf** [comment]
Going to take a different approach, so will close the issue for now.
