### ISSUE TITLE
Close terminal should have visual indication

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#13910]
- VSCode Version: 1.7
- OS Version: Mac

Steps to Reproduce:
1. Open terminal 1, 2, 3
2. Switch to terminal 2
3. Close 2 by clicking the garbage can icon

Terminal 3 get renamed to terminal 2. In cases where both have same name and output, there is no indication that the closing action happened.

**Comment by octref** [comment]
Just linking #10546 since this can be solved by Tabs in terminal.

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/Microsoft/vscode/issues/10546
