### ISSUE TITLE
Webviews loading resources off `localhost` failing

### ISSUE THREAD

**Issue by sourishkrout** [microsoft/vscode#139161]
It appears that https://github.com/microsoft/vscode/pull/138811 (authored & merged by @mjbvz) introduced an edge case where initialization isn't ready and both try/catch appear to run into the same problem ultimately throwing an irrecoverable error. The problem does *not* occur if resources are being loaded of a non-localhost host.

```
ERR Cannot access 'se' before initialization: ReferenceError: Cannot access 'se' before initialization
    at MessagePort.re.onmessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1284:13768)
```

As a result, the network tab for the respective webview will show failed requests after a longish timeout:

```
main.js:826 GET http://localhost:3000/static/js/bundle.js net::ERR_FAILED
(anonymous) @ main.js:826
setTimeout (async)
v @ main.js:824
(anonymous) @ main.js:855
main.js:826 GET http://localhost:3000/static/js/main.chunk.js net::ERR_FAILED
(anonymous) @ main.js:826
setTimeout (async)
v @ main.js:824
(anonymous) @ main.js:855
main.js:826 GET http://localhost:3000/static/js/vendors~main.chunk.js net::ERR_FAILED
(anonymous) @ main.js:826
setTimeout (async)
v @ main.js:824 (anonymous) @ main.js:855
```

Steps to repro:
1. Create a webview inside of extension
2. Reference resources served of http://localhost:[port]
3. Load build in Insiders

Reproduced in:
```
Version: 1.64.0-insider
Commit: 886fd126446cd4b8b03f2b32f09c173dec541e6d
Date: 2021-12-14T13:26:59.630Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

I believe the following code is what triggers the issue. It appears it is special cased for loading resources from localhost. I don't know the code well enough to understand why, however, figured it might help to have a pointer:
https://github.com/microsoft/vscode/blob/b823936907f86ded04a152a4af202d0fc8423522/src/vs/workbench/contrib/webview/browser/webviewElement.ts#L356-L361

Happy to provide more information if required.

**Comment by mjbvz** [comment]
Thanks for catching this!

**Comment by sourishkrout** [comment]
Of course. Thank you for the quick fix, @mjbvz.

**Comment by sourishkrout** [comment]
/verified

works now! thanks again 👍
