### ISSUE TITLE
Wiki: Broken `OS test availability` link

### ISSUE THREAD

**Issue by erikvimz** [microsoft/vscode#139188]
Branch: main
Last commit: #139183

On wiki page [Running the Endgame](https://github.com/microsoft/vscode/wiki/Running-the-Endgame), section [`OS Test Availability`](https://github.com/microsoft/vscode/wiki/Running-the-Endgame#os-test-availability) there is a broken [link](https://github.com/Microsoft/vscode-tools#updating-testers), resulting in 404 Not Found.

**Comment by IllusionMH** [comment]
Most likely it's just private repo (usual GH behavior) as "Running the Endgame" is devs only activity.

**Comment by erikvimz** [comment]
Ahh, didn't even think about that. And this is usual behaviour? Well... thanks for clarifying.
