### ISSUE TITLE
Abnormally high CPU usage

### ISSUE THREAD

**Issue by vaibhavgarg1982** [microsoft/vscode#139164]
Issue Type: <b>Bug</b>

The CPU usage is extraordinarily high, one core is permamently at 100%. This is even with no projects/files/folders open. 

The CPU fan runs at full speed. Below is the screenshot from process explorer. 

The path/ cmd line for the offending process is:

 `"C:\Users\11019\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --inspect-port=0 "c:\Users\11019\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork" --type=extensionHost --skipWorkspaceStorageLock
`
![image](https://user-images.githubusercontent.com/7822698/146131594-a7fa792d-1571-4e5e-bc24-c4b0f9abff40.png)

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:54.292Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (8.08GB free)|
|Process Argv|--crash-reporter-id 9cb752a7-8ccf-491b-ad23-e9b3fdbfb155|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.7.4273
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
vscodeintellicode|Vis|1.2.15

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710:30405998
vscexrecpromp3c:30407761
vscop841cf:30413486
vscop927cf:30413487
vscop436cf:30413488

```

</details>

**Comment by cpp233** [comment]
I have the same problem, and 1.63.0 also has this problem, older versions do not

**Comment by metab0t** [comment]
Same problem for VS code 1.63.1 on Windows.
The builtin process explorer indicates that extension host process causes CPU usage.

**Comment by jsjain** [comment]
Having similar issue with 1.63.1 on Mac OSX (Intel), i can see 1 electron process consuming 100% CPU usage even for mege small code base of ~20 files.

**Comment by jsltrifork** [comment]
Same issue on MacOS with VS Code version 1.63.1. There's 1 process named "Electron" consuming 100% CPU making VS Code very slow.

Version data:
Version: 1.63.1
Commit: fe719cd3e5825bf14e14182fddeb88ee8daf044f
Date: 2021-12-14T02:13:13.580Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

**Comment by tanhakabir** [comment]
@vaibhavgarg1982 thanks for creating the issue!

It looks like the extension host is causing the the spike in usage since the path you found to be the offender contains `--type=extensionHost`. This means it's most likely an extension causing this.

To verify it's one of your installed extensions, do you still see the same CPU usage if you start vscode with extensions disabled? You can use `code --disable-extensions` to launch VS Code without extensions.

If you do still see the spike could you please run through Extension Bisect to find the offending extension? You can use `Help: Start Extension Bisect' from Command Palette to find the specific extension.

**Comment by br14n-sol** [comment]
Same problem, high cpu usage starts from last 2 updates
Run `Help: Start Extension Bisect` with no results

---

VSCode version: 1.63.1
OS: Windows 10 Pro v20H2
CPU: Intel i3-3240
RAM: 6 GB

<details>
<summary>Extensions (15)</summary>

| Extension | Author | Version |
| --- | --- | --- |
| Github Copilot | Github | 1.7.4273 |
| Dobri Next - Themes and Icons | dobbbri | 1.1.6 |
| ENV | Jakka Prihatna | 0.1.0 |
| env-autocomplete | jpruliere | 1.2.0 |
| Error Lens | Alexander | 3.4.1 |
| ESLint | Microsoft | 2.2.2 |
| GitLens — Git supercharged | GitKraken | 11.7.0 |
| Import Cost | Wix | 2.15.0 |
| indent-rainbow | oderwat | 8.2.2 |
| PostCSS Language Support | csstools | 1.0.9 |
| PowerShell | Microsoft | 2021.10.2 |
| Prettier-Standard - JavaScript formatter | numso | 0.9.2 |
| Sundial – Automatic night mode and settings switch | Marvin Heilemann | 2.6.2 |
| Tailwind CSS IntelliSense | Tailwind Labs | 0.7.4 |
| vscode-icons | VSCode Icons Team | 11.8.0 |

</details>

Note: I doubt that it is a matter of extensions, I have been using vscode for 1 - 2 years, sometimes with more or less extensions than the ones I currently have and I have never had this problem.

**Comment by tanhakabir** [comment]
@br14n-sol hm I see. And to verify you've tried this as well?

> To verify it's one of your installed extensions, do you still see the same CPU usage if you start vscode with extensions disabled? You can use code --disable-extensions to launch VS Code without extensions.

**Comment by br14n-sol** [comment]
I've been looking for and removed some extensions that I didn't use much:
<details>
<summary>Show</summary>

| Extension |
| --- |
| Dobri Next - Themes and Icons |
| ENV |
| GitLens — Git supercharged |
| indent-rainbow |
| PowerShell |

</details>

---

> @br14n-sol hm I see. And to verify you've tried this as well?
> 
> > To verify it's one of your installed extensions, do you still see the same CPU usage if you start vscode with extensions disabled? You can use code --disable-extensions to launch VS Code without extensions.

@tanhakabir I did a little comparison, having all 10 active extensions:
- Just opening vscode for the first time while everything is loading it hits ~84% CPU usage then stabilizes at ~10%
- Opening a single project file in this case .jsx, it peaks at ~76% before stabilizing at ~23%
- Repeatedly switching between files, it peaks at ~84% until stabilizing at ~58%
- Having two or more files open it stays constant at ~90%

---

Without any active extension (--disable-extensions):
- Just opening vscode for the first time while everything is loading it hits ~80% CPU usage then stabilizes at ~6%
- Opening a single project file in this case .jsx, it peaks at ~48% before stabilizing at ~8%
- Repeatedly switching between files, it peaks at ~75% until stabilizing at ~37%
- Having two or more files open it stays constant at ~20%

**Comment by br14n-sol** [comment]
I still think the high CPU usage is strange, I usually use two instances of vscode at the same time, one for backend and one for frontend and I have never had any problems until now 🤔

**Comment by vaibhavgarg1982** [comment]
@tanhakabir 
I can confirm that loading code without extensions does not cause the "high CPU usage" issue. So it seems to be the extension host process as you suggested.

Let me revert with the results of Extension Bisect.

**Comment by vaibhavgarg1982** [comment]
@tanhakabir 
Extension bisect says that "no extension was identified; this may be a problem with code".
I don't have many extensions installed anyway.

**Comment by August-Rushme** [comment]
I have the same situation. I used Extension Bisect to eliminate the problem. Finally, I found that **GitHub pilot** extension caused excessive CPU utilization. If I disable it, there will be no excessive CPU utilization.

**Comment by tanhakabir** [comment]
@vaibhavgarg1982 good to know. Can you confirm you still see the CPU issue if you disable GitHub copilot?

**Comment by tanhakabir** [comment]
@br14n-sol  the initial spike then tapering off seems like a slightly different issue. Would you mind creating another issue with the information you provided me?

**Comment by vaibhavgarg1982** [comment]
> @vaibhavgarg1982 good to know. Can you confirm you still see the CPU issue if you disable GitHub copilot?

Seems to be the case. The CPU usage is close to 0 after disabling CoPilot.

**Comment by vaibhavgarg1982** [comment]
> I have the same situation. I used Extension Bisect to eliminate the problem. Finally, I found that **GitHub copilot(v1.7.4273)** extension caused excessive CPU utilization. If I disable it, there will be no excessive CPU utilization.Or go back to the previous version to solve the problem.

Thanks a lot. How do you roll back to previous version of the extension? Couldn't find a way to do it!

**Comment by vaibhavgarg1982** [comment]
I rolled it back to the point release 1.7.3862. So far, the CPU is quiet.

**Comment by spa5k** [comment]
Visual Studio IntelliCode - is the extension that i found out resulting in lots of cpu usage, that too after disabling all extensions and removing settings, then enabling them one by one.

If this extension is not enabled, the usage stays around 2-4% but after it is enabled, the usage reaches - 15-25%

**Comment by jsltrifork** [comment]
Unfortunately I wasn't able to find the extension causing the issue with the bisect function, but I downgraded to version 1.62.3 and that seemed to fix the problem.

**Comment by tanhakabir** [comment]
For the original issue posted by @vaibhavgarg1982, it looks like a GitHub copilot issue. The GitHub copliot team is already aware of this issue and is working on it here: https://github.com/github/feedback/discussions/8861

@spa5k could you create an issue for what you saw here? https://github.com/MicrosoftDocs/intellicode/issues

For @br14n-sol, and @jsltrifork both of your issues seem different and could have very different causes. If you guys don't mind, could you all create another issue on this repo with all the information you have available?

Closing this issue now!
