### ISSUE TITLE
addMissingImports code action doesn't prompt for ambiguous imports

### ISSUE THREAD

**Issue by rothfels** [microsoft/vscode#139131]
Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: 1.63.0
- OS Version: macOS 114

(I think this is a bug as I remember this behavior existing in the past...but I could be wrong and it's a feature request)

**Steps to Reproduce:**

1. Add to `settings.json`

```json
"editor.codeActionsOnSave": {
    "source.addMissingImports": true,
}
```

2. Save a file with ambiguous imports, e.g

```ts
function myFunction(id: ID) {
  
}
```

Where `ID` hasn't been imported. Make sure you have a local file with an export like 

```ts
export type ID = string
```

and also some dependency like `aws-sdk` which also exports `ID`.

**Expected:**

The auto-import action detects multiple options for `ID`and prompts the user to select which value to import, similar to the tooltip prompt:

![image](https://user-images.githubusercontent.com/1095573/146071781-5cf14069-c537-44fa-83ba-2f2cab5b4052.png)

It would do this once for each ambiguous import.

**Actual:**

The auto-import action imports the first possible match, which often is not the desired import.

**Comment by mjbvz** [comment]
This is by-design as we don't want our source actions to (sometimes) prompt for user interaction. Doing so would be especially weird on save

Instead `source.addMissingImports` is designed to only add imports it is confident in. More complex cases require manual review by the developer

**Comment by rothfels** [comment]
@mjbvz thanks, that makes sense.

> Instead source.addMissingImports is designed to only add imports it is confident in

In that case, isn't it weird that the auto-importer would always choose the first when there are multiple import options? That's what feels like the bug to me -- in the case where there's ambiguous imports, I would rather vscode import none of the options than the current behavior of choosing the wrong one.
