### ISSUE TITLE
License agreement contains a broken link to telemetry settings

### ISSUE THREAD

**Issue by lfmcmillan** [microsoft/vscode#139144]
The License agreement contains a hyperlink to a page about the telemetry settings: "You may opt-out of many of these scenarios, but not all, as described in the product documentation located at https://code.visualstudio.com/docs/supporting/faq#_how-to-disable-telemetry-reporting." That link works.

However, when I click on the link from within the license agreement dialog, and it opens in Firefox, it tries to open the following page:

https://code.visualstudio.com/docs/supporting/faq%23_how-to-disable-telemetry-reporting

which doesn't exist.

**Comment by lfmcmillan** [comment]
thanks for the prompt response and confirmation

**Comment by lramos15** [comment]
@joaomoreno Seems the issue is that it attempts to uri encode the `#` character which creates an invalid link. I'm not sure what the guidelines are here but maybe an `aka.ms/code-disable-telemetry` link or something similar would prevent having to worry about this

**Comment by gregvanl** [comment]
There looks to be a problem with the link. On Insiders I see:

![image](https://user-images.githubusercontent.com/12818376/149275721-fc1f93f1-1b81-4021-a257-474adfd9f915.png)

and the link resolves to 'https://code.visualstudio.com/docs/supporting/faq#_how-to-disable-telemetry-reporting.There'

with an extra '.There' and does not go to the How to disable telemetry reporting section.

**Comment by joaomoreno** [comment]
Very strange, since Word shows this:

![image](https://user-images.githubusercontent.com/22350/149499581-409d77a1-4359-4b22-9575-929786f0e653.png)

**Comment by lfmcmillan** [comment]
I can clearly see in the Word screenshot that there is no space between "reporting." and "There", so the blue and underline in the Word screenshot may be misleading about what is being treated as the link. I don't think this problem has been fully fixed yet.

**Comment by gregvanl** [comment]
Looks like the next link for the privacy statement might have the same problem. It doesn't look like there is a space between ".You"

**Comment by joaomoreno** [comment]
I did fix the first one: 

![image](https://user-images.githubusercontent.com/22350/149729151-2bbb21b6-6605-4a29-991e-f159bd3e5193.png)

But I missed that the second link had the same issue. Pushing a new fix.
