### ISSUE TITLE
editorSuggestWidget.foreground ignored

### ISSUE THREAD

**Issue by trkoch** [microsoft/vscode#139196]
Issue Type: <b>Bug</b>

Customizing `editorSuggestWidget.foreground` as [documented](https://code.visualstudio.com/api/references/theme-color#editor-widget-colors) has no effect.

**Given**

``"editorSuggestWidget.foreground": "#ff0000",``

**Expected**

Foreground color of suggest widget (i.e., text color) is red.

**Actual**

Foreground color of suggest widget (i.e., text color) is default foreground color. Status bar color is red.

**Screenshot**

![image](https://user-images.githubusercontent.com/73974/146191341-4ba72a86-2992-4123-a7ea-696bbd39f39c.png)

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:13.580Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv|--crash-reporter-id 0404a371-ca9b-4f3c-9e1f-dfea7ff85d7c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
alpine-js-intellisense|adr|1.2.0
Bookmarks|ale|13.2.2
ng-template|Ang|13.1.0
asciidoctor-vscode|asc|2.8.10
toml|be5|0.6.0
lit-html|bie|1.11.1
markdown-emoji|bie|0.2.1
markdown-preview-github-styles|bie|0.2.0
clj-kondo|bor|2021.12.1
vscode-tailwindcss|bra|0.7.4
vscode-toggle-quotes|Bri|0.3.5
vscode-standardjs-snippets|cap|0.8.15
solargraph|cas|0.23.0
postcss|css|1.0.9
transformer|dak|1.12.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.0.0
vscode-commands|fab|1.4.3
vscode-sql-tagged-template-literals|fri|0.0.18
vscode-sql-tagged-template-literals-syntax-only|fri|0.0.19
go|gol|0.29.0
vscode-graphql|Gra|0.3.41
todo-tree|Gru|0.0.214
elixir-ls|Jak|0.9.0
vsc-space-block-jumper|jmf|1.2.2
asciidoctor-vscode|joa|2.8.0
vscode-styled-components|jpo|1.7.0
center-editor-window|kai|2.3.0
endwise|kai|1.5.1
restructuredtext|lex|167.0.0
rainbow-csv|mec|1.10.1
prettify-json|moh|0.0.3
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.18.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
vscode-typescript-tslint-plugin|ms-|1.3.3
neos-fusion|net|1.0.6
vetur|oct|0.35.0
phoenix|pho|0.1.1
prisma|Pri|3.6.0
ruby|reb|0.28.1
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.2
vscode-sort-json|ric|1.20.0
multi-command|ryu|1.5.1
jinjahtml|sam|0.16.0
vscode-nginx|sha|0.6.0
vscode-fileutils|sle|3.4.5
vscode-multiclip|sle|0.1.5
rewrap|stk|1.15.4
ayu|tea|1.0.5
vscode-status-bar-format-toggle|tom|3.0.0
simple-rst|tro|1.5.1
non-breaking-space-highlighter|vik|0.0.3
vscode-todo-highlight|way|1.0.5
vscode-ruby|win|0.28.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes516:30244333
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710cf:30405999
py55gd98cf:30411515
vscexrecpromp3t1:30407762
vscop841cf:30413486
vscop927cf:30413487
vscop436cf:30413488

```

</details>

**Comment by trkoch** [comment]
This seems to be a regression. I noticed my Insiders build (which was not updated at the time) respected the setting. After updating my Insiders build, this is no longer the case.

**Comment by trkoch** [comment]
If I had to guess, this https://github.com/microsoft/vscode/commit/d5c42c8c3e6f58a3eafef9a05197698027f30ba8 looks like a possible culprit (this commit touched quite a few lines and timing seems right, since my previous Insiders build was from October).

**Comment by ArturoDent** [comment]
I note that the `details` text in a `suggestWidget` is being properly colored by the setting.  Just not the various completionItems.

**Comment by trkoch** [comment]
I wonder if the actual suggestions are marked up as `<a>` elements, which receive another color? I cannot figure out how to inspect with the web developer console (suggestions disappear once I try to select it).
