### ISSUE TITLE
Add option to auto save when running tests

### ISSUE THREAD

**Issue by kjohnsen** [microsoft/vscode#139125]
I have autosave enabled for changing focus. When I use the new testing framework, whether with the shortcuts (like `ctrl+;+t`) or the buttons in the testing panel, the focus doesn't change and thus tests are run on the old, undesired code. An option to autosave whenever running a testing command would be nice.

**Comment by connor4312** [comment]
Good idea, contributions welcome.

Code pointer: https://github.com/microsoft/vscode/blob/913639f42aaf268f6b2acc6cbe5701eee3720d7b/src/vs/workbench/contrib/testing/common/testServiceImpl.ts#L167

**Comment by slidoooor** [comment]
@connor4312 hi, I found that the auto-save function is encapsulated inside editor, and he triggers his own save method by listening to focus change or windows change, we have no condition to trigger save when we execution test method, can we only add a processing option to autoeditor's auto-save and in editor deal this case?

**Comment by connor4312** [comment]
`IEditorService`, which can be injected into the TestServiceImpl, contains a `saveAll()` method.

**Comment by slidoooor** [comment]
> `IEditorService`, which can be injected into the TestServiceImpl, contains a `saveAll()` method.

Hi I submitted a revision for this case and did some testing~

**Comment by slidoooor** [comment]
> vscode/src/vs/workbench/contrib/testing/common/testServiceImpl.ts

Hi I submitted a change for this case, did some testing, hope my changes are right
