### ISSUE TITLE
Can't add new terminal and empty list shell

### ISSUE THREAD

**Issue by UnknownFX02** [microsoft/vscode#139156]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
```
Version: 1.62.1 (system setup)
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-05T10:57:55.946Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
```
- OS Version:
```
Edition	Windows 11 Enterprise
Version	21H2
Installed on	‎7/‎14/‎2021
OS build	22000.348
Experience	Windows Feature Experience Pack 1000.22000.348.0
```
Launch with `code --disable-extensions` to check. Yes

Steps to Reproduce:

1. Open new vsccode or workspace
2. Terminals not available (Both add new and select shell like powershell). See image
![image](https://user-images.githubusercontent.com/32718930/146114426-c99f2fe8-3061-460c-893d-8ca6b4e2cded.png)
3. Terminal config
![image](https://user-images.githubusercontent.com/32718930/146114624-b365669c-36c8-4608-9c4a-2b5c5963cd26.png)

Note: I was updating Windows terminals and set its default. That's all I change before this issue

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by meganrogge** [comment]
if you'd rather not use insider's, set `terminal.integrated.useWslProfiles` to false
