### ISSUE TITLE
cmd-shift-num to change editor tab

### ISSUE THREAD

**Issue by nocksock** [Microsoft/vscode#13911]
It'd be great if one could hit eg. cmd-shift-1 to switch to the first tab of the current editor. Or configure it as such so that cmd-shift-1 would select the first editor group. I struggle a lot with not being able to intuitively change tabs with cmd-[num].

**Comment by roblourens** [comment]
This should work with ctrl+1, ctrl+2, etc. You can change it if you want, the command name is "workbench.action.openEditorAtIndex1"

**Comment by nocksock** [comment]
Ah nice!

For anyone curious I added this to my keyboard shortcus:

        { "key": "cmd+1",                "command": "workbench.action.openEditorAtIndex1" },
        { "key": "cmd+2",                "command": "workbench.action.openEditorAtIndex2" },
        { "key": "cmd+3",                "command": "workbench.action.openEditorAtIndex3" },
        { "key": "cmd+4",                "command": "workbench.action.openEditorAtIndex4" },
        { "key": "cmd+5",                "command": "workbench.action.openEditorAtIndex5" },
        { "key": "cmd+6",                "command": "workbench.action.openEditorAtIndex6" },
        { "key": "cmd+7",                "command": "workbench.action.openEditorAtIndex7" },
        { "key": "cmd+8",                "command": "workbench.action.openEditorAtIndex8" },
        { "key": "cmd+9",                "command": "workbench.action.openEditorAtIndex9" },
        { "key": "cmd+,",                "command": "workbench.action.openGlobalSettings" },
        { "key": "ctrl+w h",             "command": "workbench.action.previousEditor" },
        { "key": "ctrl+w l",             "command": "workbench.action.nextEditor" },
        { "key": "ctrl+1",               "command": "workbench.action.focusFirstEditorGroup" },
        { "key": "ctrl+2",               "command": "workbench.action.focusSecondEditorGroup" },
        { "key": "ctrl+3",               "command": "workbench.action.focusThirdEditorGroup" }
