### ISSUE TITLE
EPERM: operation not permitted

### ISSUE THREAD

**Issue by azizsaboor** [Microsoft/vscode#13914]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 14.5.0

I am working on a folder with permissions 755 with user 'root' and group 'admin' respectively. I am (the current user) part of the 'admin' group. But, when I open this folder in code... and try to save something twice in a row, I get the following error.

A system error occured (EPERM: operation not permitted, utime '/Library/WebServer/Documents/...

I don't have this issue when working on the same folder from another editor like sublime. I have tried to run code as 'admin' and seem to solve the problem... however, I am greeted with a warning message that says it is not recommended to run code as admin. So what do I do?

**Comment by roblourens** [comment]
This looks the same as #13920, so let's merge them
