### ISSUE TITLE
Shift-Tap markiert nicht.

### ISSUE THREAD

**Issue by honsberg** [microsoft/vscode#139178]
wenn ich die Shift-Taste gedrückt halte und in den Editor tippe (Touchscreen) erwarte ich, dass der Text zwischen aktueller Cursorposition und dem Tap markiert wird. (wie bei einem click)

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:54.292Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (6.07GB free)|
|Process Argv|C:\\Users\\jan\\AppData\\Local\\Temp\\_tcx\\3\\1\\cosmic\\box\\box_a_regel_edit.php --crash-reporter-id bee6aa95-c798-4b54-9f17-32b0a3d625d3|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
vscode-intelephense-client|bme|1.8.0
php-debug|fel|1.22.0
php-pack|fel|1.0.2
ftp-sync|luk|0.3.9
vscode-language-pack-de|MS-|1.63.3
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
kb-macro|tsh|0.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710:30405998
vscop841cf:30413486
vscop927cf:30413487
vscop436cf:30413488

```

</details>

**Comment by alexdima** [comment]
Let's track in #47770
