### ISSUE TITLE
cannot disable editor.formatOnSave

### ISSUE THREAD

**Issue by ufolux** [Microsoft/vscode#13916]
- VSCode Version: 1.6.1
- OS Version: macOS 10.12

Steps to Reproduce:

1. set "editor.formatOnSave": false
2. when I save file, formatter will still format my code

**Comment by roblourens** [comment]
What language? Do you have any extensions installed? Some extensions will do this for you. Does it happen if you launch with `code --disable-extensions`?

**Comment by ufolux** [comment]
oh, I find it is caused by JS-CSS-HTML Formatter extension. It's not a bug. Thanks @roblourens
