### ISSUE TITLE
Evaluate terminal auto replies setting

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#139102]
By endgame we should:

- Decide whether this should be a general setting or specific to the Windows batch case
- Disable by default, adding an enabled setting if it's going to remain general

**Comment by vaindil** [comment]
Not sure if this is the correct place for this, I don't know if this is a bug or intended behavior.

I love this functionality, but I already use Cmder/Clink as my terminal within VS Code, and it handles this for me. I don't mind it defaulting on, but the "Terminate batch job (Y/N)" prompt cannot currently be removed from the VS Code setting. Both VS Code and Cmder are now trying to reply to it, which ends up with a duplicate "Y" sent. Clicking the X in the VS Code settings editor for the entry has no effect, and editing the existing one so it would no longer match just creates a new entry with the edited text, so I cannot prevent VS Code from handling it for me. This is frustrating, as I can't tell Cmder/Clink to not handle it specifically for VS Code.

**Comment by Tyriar** [comment]
@vaindil thanks for the feedback! That issue where you can't delete the setting is tracked in https://github.com/microsoft/vscode/issues/139175. Note that by the time this goes to stable we'll switch the default to off. In the meantime you can add this setting to your settings.json file which should disable the feature:

```
"terminal.integrated.autoReplies": {}
```

**Comment by vaindil** [comment]
Ah, sorry, guess I didn't search hard enough. Thank you!

**Comment by Tyriar** [comment]
@vaindil I have trouble finding stuff too 😅

**Comment by Tyriar** [comment]
I haven't heard any complaints of the default apart from the above, let's keep it as the default since the settings row delete bug is fixed as well.

**Comment by hello-smile6** [comment]
@Tyriar Could you add the following entry to prevent accidentally doing `rm -r /`?
```
"rm: descend into directory '/'?": "n\r"
```

**Comment by Tyriar** [comment]
@hello-smile6 you could add that entry if you really wanted to, it shouldn't be a default though.

**Comment by hello-smile6** [comment]
> @hello-smile6 you could add that entry if you really wanted to, it shouldn't be a default though.

Here's an example with v86.
https://copy.sh/v86/?profile=archlinux&c=mkdir%20t%3Bcd%20t%3Bmodprobe%20ne2k-pci%3Bdate%20--set%3D%27%60hwclock%60%27%3Bdhcpcd%20-w4%20eth0%3Bgit%20clone%20https%3A%2F%2Fgithub.com%2Fhello-smile6%2Fempty-repository%3Bcd%20..%3Brm%20-ri%20t%20%2F%3B
The user could accidentally add a space and `/` after a directory using `rm -ri`. By adding that entry, the user would hopefully avoid deleting everything.
