### ISSUE TITLE
Can not create new Terminal

### ISSUE THREAD

**Issue by HadesD** [microsoft/vscode#139135]
Issue Type: <b>Bug</b>

When I press new terminal, it do not create any terminal, just a blank page with cursor
I have to open Split to exists terminal, then un-split it

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:54.292Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.01GB free)|
|Process Argv|--crash-reporter-id 6416353b-4fa5-4bb1-9ee4-02e8c90fe481|
|Screen Reader|no|
|VM|14%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor (16 x 3792)|
|Memory (System)|15.60GB (8.37GB free)|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
systemd-unit-file|coo|1.0.6
auto-close-tag|for|0.5.13
vue-snippets|hol|1.0.4
better-cpp-syntax|jef|1.15.10
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.11
vim|vsc|1.21.10
vscode-intelephense-client|bme|1.8.0
doxdocgen|csc|1.3.2
vscode-react-proptypes-intellisense|cun|0.0.4
vue-peek|dar|1.0.2
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
php-intellisense|fel|2.3.14
better-cpp-syntax|jef|1.15.10
vscode-clang|mit|0.2.4
vscode-docker|ms-|1.18.0
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
vetur|oct|0.35.0
react-proptypes-intellisense|OfH|1.0.3
laravel-blade|one|1.28.0
vscode-blade-formatter|shu|0.8.5
cmake|twx|0.0.17

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
javagetstartedt:30391933
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710:30405998
vscexrecpromp3t2:30407763

```

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" terminal

**Comment by lucyholic** [comment]
Hi I'm having the same issue on remote WSL Ubuntu 20.04. 
The log says `No terminal backend registered for remote authority 'wsl+ubuntu-20.04'` 
I removed settings.json, but it didn't solve the problem.

**Comment by HadesD** [comment]
@Tyriar 
I 've delete workspace and create new workspace, it fixed.
