### ISSUE TITLE
Complex scss syntax highlight anomalies

### ISSUE THREAD

**Issue by gadfly3173** [microsoft/vscode#139170]
Issue Type: <b>Bug</b>

render result: 
![image](https://user-images.githubusercontent.com/28685179/146143201-a193ae01-624b-4e23-a970-f8c554248032.png)

```scss
:deep(.el-scrollbar) {
  .reserve-drawer {
    padding: 0 20px;
    .create-btn {
      margin-bottom: 10px;
    }
  }
}
.reserve-edit-form {
  :deep(.el-form-item__content) {
    .el-input-number--mini {
      width: 80px;
    }
  }
}
```

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (13.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nginx-conf|ahm|0.1.3
vscode-subtitles|ast|0.4.0
vscode-database|baj|2.2.3
vscode-importmagic|bra|0.2.5
zh-hans-tt-hant-vscode|cip|1.0.0
native-ascii-converter|cwa|1.0.9
vscode-mysql-client2|cwe|4.3.5
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
javascript-ejs-support|Dig|1.3.1
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.23
vscode-mysql|for|0.4.1
copilot|Git|1.7.4273
gc-excelviewer|Gra|4.0.45
todo-tree|Gru|0.0.214
vue-snippets|hol|1.0.4
vscode-wordcount-cjk|hol|1.3.1
mysql-syntax|jak|1.3.1
fontawesome-autocomplete|Jan|1.1.2
cfg-games-support|joe|0.1.2
volar|joh|0.29.8
vscode-typescript-vue-plugin|joh|0.29.8
materialdesignicons-intellisense|luk|4.0.0
eslint-rules-zh-plugin|mag|0.1.0
workspace-cacheclean|Mam|0.0.2
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-uni-app-snippets|Mod|0.6.2
vscode-docker|ms-|1.18.0
vscode-language-pack-zh-hans|MS-|1.63.3
data-workspace-vscode|ms-|0.1.0
mssql|ms-|1.11.1
sql-database-projects-vscode|ms-|0.13.1
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1001414422
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.11
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.7.1
hexeditor|ms-|1.8.2
sftp|Nat|1.15.10
material-icon-theme|PKi|4.11.0
java|red|1.1.0
vs-code-prettier-eslint|rve|3.0.4
markdown-preview-enhanced|shd|0.6.1
autoimport|ste|1.5.4
sass-indented|syl|1.8.18
language-stylus|sys|1.14.1
tabnine-vscode|Tab|3.5.5
stylus-supremacy|thi|2.16.0
git-commit-lint-vscode|UvD|1.3.0
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.19.0
vscode-java-test|vsc|0.33.0
vscode-maven|vsc|0.34.1
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
Moved to the repository that we get our scss grammar from: https://github.com/atom/language-sass/issues/288
