### ISSUE TITLE
Close the specified editor by file name

### ISSUE THREAD

**Issue by guoshilin1314** [microsoft/vscode#139195]
Now only the active text editor can be closed. Can you provide a command to close the specified text editor (inactive)

**Comment by roblourens** [comment]
Can you tell us more about what you want to use it for?

**Comment by guoshilin1314** [comment]
I want to close the corresponding text editor according to the file path, instead of closing the active editor or closing the editor of the specified group and editorindex




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月16日(星期四) 上午9:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode] Close the specified editor (Issue #139195)





 
Can you tell us more about what you want to use it for?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bpasero** [comment]
You mean a command you can use from an extension?

**Comment by guoshilin1314** [comment]
Yes, I want to use the command in the extension




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月16日(星期四) 下午2:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode] Close the specified editor (Issue #139195)





 
You mean a command you can use from an extension?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
