### ISSUE TITLE
What is the logic for multiple suggestion api? (multiple autocomplete extensions)

### ISSUE THREAD

**Issue by softmarshmallow** [microsoft/vscode#139193]
I'm planning to develop a suggestion extension something like github copilot, but more focused on front-end code.

What happens if user has multiple extensions doing the suggestion? can i force vscode to suggest my code first? 
What is the priority and how is it handled?

**Comment by jrieken** [comment]
see https://github.com/microsoft/vscode/blob/ab80daed7409a4ec2c6c86be1f850600931c9177/src/vscode-dts/vscode.d.ts#L11436-L11441

**Comment by jrieken** [comment]
and https://github.com/microsoft/vscode/blob/ab80daed7409a4ec2c6c86be1f850600931c9177/src/vscode-dts/vscode.d.ts#L4117-L4129
