### ISSUE TITLE
Error comes up in wrong window

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#139181]
1. Enable settings sync
2. Open two windows
3. Edit user settings JSON on one window, make a syntax error, make sure settings.json is not opened in another window

🐛 Notification about the syntax error comes up in the other window

![image](https://user-images.githubusercontent.com/22350/146161306-db947009-c16b-420a-8330-d5c6b4150eba.png)

**Comment by sandy081** [comment]
It is designed to show the dialog only when the settings file is not opened, when opened user is aware of errors and it is a noise to show the prompt. I think the bug is that show the prompt only in the active window.

Fixed.
