### ISSUE TITLE
VS Code listing problems for files that don't exist. Not even in trash.

### ISSUE THREAD

**Issue by undeadindustries** [microsoft/vscode#139110]
Issue Type: <b>Bug</b>

I have a simple 4 file go source. There used to be more files. I recently deleted some files and some folders. Now when I open Code, I see problems referencing those old files and problems for code that's not on this computer.

It's like there's a cache that is corrupted or something.

I've cleared editor history etc. I've uninstalled code, rebooted and installed nightly. I've copied the files into a new folder. Nothing seems to work.

LiteIDE works with these files fine. 

Thanks!

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700G with Radeon Graphics          (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.39GB (53.24GB free)|
|Process Argv|--crash-reporter-id 40295e11-c43f-4153-9f69-9193002d2311|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
go-nightly|gol|2021.12.1321
workspace-cacheclean|Mam|0.0.2
vscode-docker|ms-|1.18.0
remote-containers|ms-|0.209.6
remote-wsl|ms-|0.63.5
powershell|ms-|2021.10.2
go-doc|msy|1.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710:30405998
vscexrecpromp3t2:30407763

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`
