### ISSUE TITLE
Enable starting extension host with --expose-gc

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#139139]
The Jupyter extension runs memory usage tests, but they don't provide useful results unless they can force a GC. Starting a node process with `--expose-gc` enables the api `global.gc()` to do this.

Can we enable spawning the extension host with this flag? Or is there some creative backdoor way that an extension can do this already? https://github.com/microsoft/vscode/blob/648e355c05fe2b0cfd38379fea30f08d19114fc0/src/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.ts#L250

We could always set it when running extension tests. Or, add a flag/environment variable that vscode can be started with to enable this. `NODE_OPTIONS` apparently can't be used for `--expose-gc`

cc 
@rchiodo

**Comment by alexdima** [comment]
> We could always set it when running extension tests

:+1: PR welcome.
