### ISSUE TITLE
Vscode is showing warning for display:grid

### ISSUE THREAD

**Issue by irf4nmohd** [microsoft/vscode#139191]
Issue Type: <b>Bug</b>

'display: grid' is not supported by Internet Explorer. Add 'display: -ms-grid' to support Internet Explorer 10+.Microsoft Edge Toolscompat-api/css.

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:54.292Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (2.25GB free)|
|Process Argv|--crash-reporter-id 11b7bf9e-9ecf-4369-aea7-52b2e223203a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-sqlite|ale|0.14.0
vscode-custom-css|be5|6.0.2
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.6.0
emoji-snippets|dev|1.5.3
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.7.0
prettier-vscode|esb|9.0.0
vscode-firefox-debug|fir|2.9.5
auto-rename-tag|for|0.1.9
copilot|Git|1.7.4273
gc-excelviewer|Gra|4.0.45
rest-client|hum|0.24.6
vscode-styled-components|jpo|1.7.0
regexp-preview|Lou|0.1.5
vscode-language-babel|mgm|0.0.35
dotenv|mik|1.0.1
vscode-docker|ms-|1.18.0
vscode-edge-devtools|ms-|1.4.2
remote-containers|ms-|0.209.6
indent-rainbow|ode|8.2.2
material-icon-theme|PKi|4.11.0
material-product-icons|PKi|1.1.1
polacode|pnp|0.3.4
vscode-css-peek|pra|4.2.0
vscode-thunder-client|ran|1.9.1
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.10
vscodeintellicode|Vis|1.2.15
quokka-vscode|Wal|1.0.432
html-css-class-completion|Zig|1.20.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710:30405998
py55gd98:30411514
vscexrecpromp3c:30407761
vscop841cf:30413486
vscop927cf:30413487
vscop436cf:30413488

```

</details>

**Comment by ArturoDent** [comment]
As the problem indicates, that is being produced by the extension `Microsoft Edge Tools for VSCode`.  Disable that and the error goes away.

**Comment by aeschli** [comment]
Thanks @ArturoDent for the answer!
