### ISSUE TITLE
When replacing folders, offer an option to merge the files

### ISSUE THREAD

**Issue by tazejin** [Microsoft/vscode#1391]
When you have in root folder named "images" for example and in lets say folder "secret" you have another "images folder" and you move the images from secret to root, it ask you to replace files but it does not replace them, it deletes whole folder and copy new one rather than replacing only existing files.

**Comment by dbaeumer** [comment]
@bpasero fyi.

**Comment by bpasero** [comment]
:+1: but I really think this is just another operation and should not be "Replace", instead it should be an option from the dialog to say "Merge" folders.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
