### ISSUE TITLE
Git default clone directory does not automatically clone

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#139117]
I always expected that setting `git.defaultCloneDirectory` would automatically select that directory when cloning and not prompt me every time (save a step). The description even says `The default location to clone a git repository.` so the fact that I still have to select/confirm the folder feels like the setting isn't properly described or not working as expected.

I would like to be able to use the "Git: Clone" command and have it auto-clone into the directory I set it for and automatically open (I also have "Open After Clone" set to "Always").

**Comment by lszomoru** [comment]
Looking at the code, the `git.defaultCloneDirectory` settings describes the folder that is used when initialising the open file dialog.
