### ISSUE TITLE
word wrap not working on mac

### ISSUE THREAD

**Issue by mdemonahmed** [microsoft/vscode#139114]
Issue Type: <b>Bug</b>

hi on my mac word wrap not working. i tried several ways but it's not working. even i edit settings.json file. 

VS Code version: Code 1.63.0 (Universal) (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 9, 8|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id b764b140-d182-423b-8fbc-392b56b77d7c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-intelephense-client|bme|1.8.0
bracket-pair-colorizer|Coe|1.0.62
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.7.0
prettier-vscode|esb|9.0.0
php-debug|fel|1.22.0
auto-rename-tag|for|0.1.9
vscode-wordpress-hooks|joh|0.6.0
vscode-docker|ms-|1.18.0
sqltools|mtx|0.23.0
LiveServer|rit|5.6.1
wordpress-toolbox|wor|1.3.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710cf:30405999
vscexrecpromp3t2:30407763

```

</details>

**Comment by alexdima** [comment]
@mdemonahmed Word wrapping works for me. Can you please try the following:
* Run `File > New Window` (`shift+cmd+N`)
* Run `File > New File` (`cmd+N`)
* copy paste `thisisalongtextthisisalongtextthisisalongtextthisisalongtextthisisalongtextthisisalongtextthisisalongtextthisisalongtextthisisalongtextthisisalongtextthisisalongtextthisisalongtextthisisalongtextthisisalongtextthisisalongtextthisisalongtext`
* Run `View > Word Wrap` (`opt+Z`)

Do the contents wrap for you?
![image](https://user-images.githubusercontent.com/5047891/146416702-3e50d02a-80e4-40b8-b330-6d113841e416.png)
