### ISSUE TITLE
当我第一次打开vscode的标题栏的时候，会有一个滚动条

### ISSUE THREAD

**Issue by zhxde** [microsoft/vscode#139182]
Issue Type: <b>Bug</b>

无用且再次打开就正常了

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:54.292Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.87GB (3.96GB free)|
|Process Argv|--crash-reporter-id cf9053ce-3a57-4c85-86ce-a0d3cbf89fd2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
vscode-language-pack-zh-hans|MS-|1.63.3
vetur|oct|0.35.0
vscode-boot-dev-pack|Piv|0.1.0
vscode-spring-boot|Piv|1.29.0
material-icon-theme|PKi|4.11.0
fabric8-analytics|red|0.3.5
java|red|1.1.0
vscode-commons|red|0.0.6
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.6.1
open-in-browser|tec|2.0.0
vscode-gradle|vsc|3.8.4
vscode-java-debug|vsc|0.37.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
javagetstartedt:30391933
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710:30405998
vscop841cf:30413486
vscop927cf:30413487
vscop436cf:30413488

```

</details>

**Comment by yume-chan** [comment]
Translation:

> ## When I open vscode's title bar the first time, there is a scroll bar
>
> Unless and doesn't happen when open again

I don't know how to open "vscode's title bar", but this is what the reporter says.

**Comment by heartacker** [comment]
fixed ： https://github.com/microsoft/vscode/issues/138110
