### ISSUE TITLE
dragging a terminal from the editor area to the first slot in the panel detaches xterm element

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#139222]
I do not see the notification toast when I select "New Terminal" from command palette.

But I see this issue that the OP reported I think:

![image](https://user-images.githubusercontent.com/900690/146227824-36b6ca4a-3102-4dbd-8286-c8cd5d55be40.png)
![recording](https://user-images.githubusercontent.com/900690/146227864-16807e86-4059-47eb-b948-31484582a86f.gif)

_Originally posted by @bpasero in https://github.com/microsoft/vscode/issues/138770#issuecomment-994967889_

**Comment by keiranmraine** [comment]
I see this problem:

* Start a new terminal - full screen
* Drag to bottom or right = non-functional

If you split the panel right, it is fine

**Comment by meganrogge** [comment]
Reproes only when you have more than one terminal in the editor area

**Comment by keiranmraine** [comment]
Can do it with a single terminal, clean open of VSCode (mac), no other windows.

```
Version: 1.63.1
Commit: fe719cd3e5825bf14e14182fddeb88ee8daf044f
Date: 2021-12-14T02:13:13.580Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0
```
![terminal_loose_prompt](https://user-images.githubusercontent.com/3740323/146409156-72a4068c-8638-46fd-ae2d-ce8806e129f6.gif)

**Comment by meganrogge** [comment]
Thanks, I specifically meant when dragging and dropping into the panel.

**Comment by rchiodo** [comment]
/verified second terminal is no longer blank
