### ISSUE TITLE
Adjust the order of files in working directory.

### ISSUE THREAD

**Issue by krishna116** [microsoft/vscode#139277]
Issue Type: <b>Feature Request</b>

If I have two file: "file5.lex" and "file5.1.lex", the order of the two file in working directory is:
"file5.1.lex"
"file5.lex"
But I want the file order is:
"file5.lex"
"file5.1.lex"

If I have two file: "file.lex" and "file-2.lex", I also want the order is:
file.lex
file-2.lex

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:54.292Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by JacksonKearl** [comment]
Duplicate #27286
