### ISSUE TITLE
Signature helper(parameter hints) not being triggered in js/jsx files

### ISSUE THREAD

**Issue by gcazaciuc** [Microsoft/vscode#13924]
- VSCode Version:
1.6.1
- OS Version:
Ubuntu 16

Steps to Reproduce:
I'm writing a VSCode extension and I'm trying to make the signature helper(parameter hints) kick in. I followed the docs and took inspiration also from 'vscode-golang' on how this should be implemented but this feature is still not triggered even when explicitly triggering it with 'ctrl+shift+space'
1. I have the provider registered as:

```js
 vscode.languages.registerSignatureHelpProvider({ language: lang, scheme:" file" }, 
            new SignatureProvider(), '(', ','));
```

Where lang is 'javascript' and 'javascriptreact'(iregistration happens in a loop).

2. I have the provider implemented as:
```js
import * as vscode from 'vscode';
export default class SignatureProvider implements vscode.SignatureHelpProvider {
    public provideSignatureHelp(
        document: vscode.TextDocument,
        position: vscode.Position,
        token: vscode.CancellationToken
    ):any {
            const signatureHelp = new vscode.SignatureHelp(); // This line is never reached 
            console.log('Signature helper kicked in');
            signatureHelp.activeParameter = 0;
            signatureHelp.activeSignature = 0;
            const sig = new vscode.SignatureInformation('param', 'great param');
            sig.parameters = [new vscode.ParameterInformation('x', 'docs')];
            signatureHelp.signatures = [sig];
            return signatureHelp;
    }
}
```

No matter what i do, press 'ctrl+shift+space' or type in a method call the provider isn't triggered.

All of my other providers are triggered just fine as expected: hover provider, autocomplete provider .

**Comment by jrieken** [comment]
That most likely because we blindly pick the first one we have in that is likely the default JavaScript/TypeScript provider. I'll change the logic to keep asking the providers (in order) until some has a rest.

**Comment by jrieken** [comment]
stretch for october

**Comment by gcazaciuc** [comment]
One thing to note after further investigation:

If the registration of the provider is done async, like in a small timeout or as a result of triggering a command the hints are being triggered.
So it seems to be some kind of a race condition that it's happening at the editor level.
On a related note i haven't been able to get the active signature to highlight but i don't know if it's related in any kind with this issue.

You can also see the timeout hack that makes signature provider to work in action here: https://github.com/gcazaciuc/vscode-flow-ide (in extension.ts):

```js
 setTimeout(() => {
        context.subscriptions.push(
            vscode.languages.registerSignatureHelpProvider('javascriptreact', new SignatureProvider(), '(', '.')
        );
        context.subscriptions.push(
            vscode.languages.registerSignatureHelpProvider('javascript', new SignatureProvider(), '(', '.')
        );
    }, 1000);
```

**Comment by jrieken** [comment]
It is not a race condition its the conflict resolution: When two [*equal well matching*](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3919) providers are available we take the one that came last.

**Comment by jrieken** [comment]
@gcazaciuc I have fixed this by continuing asking provider until a valid result is returned. That means if TypeScript/JavaScript comes first *and* returns a result you won't be asked, otherwise you will. There is no notion of *merging* two or more signature help objects and show a combined view in the UI. Please let me know if you desire that. 

Last, minor nitpick - When calling register you can pass an array of document selectors, like so `vscode.languages.registerSignatureHelpProvider(['javascript', 'javascriptreact'], new SignatureProvider(), ',', '(')`

**Comment by jrieken** [comment]
Can by verified by writing an extension or by looking at [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/test/node/api/extHostLanguageFeatures.test.ts#L748) test

**Comment by aeschli** [comment]
Verified with 
```
export function activate(context: vscode.ExtensionContext) {
    context.subscriptions.push( vscode.languages.registerSignatureHelpProvider({ language: 'typescript' }, new SignatureProvider(), '(', ','));;
}
```
and the provider above.
Verified that the provided signature help provider is used if there is none from typescript
