### ISSUE TITLE
Terminal tabs are not restored after closing vs code and opening the project again

### ISSUE THREAD

**Issue by vasilev-alex** [microsoft/vscode#139276]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.1 
- OS Version: macOS Monterey

Open terminal tabs (renamed/colored) are not restored after closing the window.

Steps to Reproduce:

1. Open Terminal, create a new tab (optionally, rename and change the color)
2. Close vsCode
3. After reopening the project all Terminal tabs are gone.

**Comment by Tyriar** [comment]
The terminals are now only restored if you have typed into them, we can change this to also cover renaming and coloring 👍
