### ISSUE TITLE
Error Plotting on VSCode

### ISSUE THREAD

**Issue by cokeverdejo** [microsoft/vscode#139200]
Issue Type: <b>Bug</b>

I can't plot any graph on Python, i had problem using Normal  VSCode, now i'm using the Insider Version and I have new problems

VS Code version: Code - Insiders 1.64.0-insider (b823936907f86ded04a152a4af202d0fc8423522, 2021-12-15T05:14:42.036Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.10GB free)|
|Process Argv|--crash-reporter-id 93c950c8-8ecd-47ed-9cce-96d10a95716d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.7.4273
mdmath|goe|2.7.4
r|Iku|2.3.4
rainbow-csv|mec|1.10.1
vscode-language-pack-es|MS-|1.63.3
python|ms-|2022.0.1578295602-dev
vscode-pylance|ms-|2021.12.3-pre.1
jupyter|ms-|2022.1.1001581935
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
cpptools|ms-|1.7.1
material-icon-theme|PKi|4.11.0
math-snippets|tho|0.1.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30396469
pythonvs932:30404738
vscop804cf:30404767
vscop341:30404997
vsclayoutctrt:30405800
py55gd98:30408621
azactmsalcf:30409288
vscop841cf:30413486
vscop927cf:30413487
vscop436cf:30413488

```

</details>

**Comment by cokeverdejo** [comment]
![image](https://user-images.githubusercontent.com/76455458/146191130-00f72975-9b75-4858-b399-cb8a267ebf4a.png)

**Comment by cokeverdejo** [comment]
> ![image](https://user-images.githubusercontent.com/76455458/146191130-00f72975-9b75-4858-b399-cb8a267ebf4a.png)

```
Error loading preloads:
Failed to fetch dynamically imported module: https://file+.vscode-resource.vscode-webview.net/c%3A/Users/Coke/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.4/out/client_renderer/renderers.js
```

**Comment by mjbvz** [comment]
Please start by filing this against the python extension 

/extPython

**Comment by AlFontal** [comment]
I'm facing the same issue. Did you find a way to fix this?

**Comment by luabud** [comment]
this actually seems to be an issue with the Jupyter extension, I have just bumped into it but it's not reproducible 100% of the time for me. Closing the notebook and reopening it fixed it for me.

**Comment by AlFontal** [comment]
Yes @luabud, I ended up concluding the same. In fact, it does not only happen with figures/plots, but also with error messages.

**Comment by cokeverdejo** [comment]
> I'm facing the same issue. Did you find a way to fix this?

Just like @luabud says, the only solution is to close the app and re open it. 
Now I'm not seeing errors and graphs.
Apparently is a Jupyter Notebook Renders error.

**Comment by luabud** [comment]
It seems it's this same issue that was reported to the Jupyter extension: https://github.com/microsoft/vscode-jupyter/issues/8596

**Comment by kevingoh** [comment]
have the same issue, following

**Comment by kevingoh** [comment]
I just found the culprit. Seems like the culprit is Jupyter Notebook Renderers extension v 1.0.4.....rolling back v 1.0.3 solves the issue
<img width="383" alt="Screenshot 2021-12-22 at 20 13 11" src="https://user-images.githubusercontent.com/4591380/147143767-2be713db-766c-4a00-b8aa-3e2b371fa10a.png">
