### ISSUE TITLE
VS Code update fails

### ISSUE THREAD

**Issue by velhari** [microsoft/vscode#139261]
We have written
Issue Type: <b>Bug</b>

Whenever the new Update comes, it fails on every updates. I have to uninstall the app and download from online to install as fresh then only able to start work on the VSCode application. For the past couple of months only experiencing these kind of issues. 

Error is happening on not able to rename the Code.exe.

Hope it will be fixed soon. 

Thanks

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:54.292Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (9.11GB free)|
|Process Argv|--crash-reporter-id 26985157-0925-45e6-b402-150197f20e3a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-zipfs|arc|2.3.0
atlascode|atl|2.10.0
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
prettier-vscode|esb|9.0.0
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.8.1
vscode-yaml|red|1.2.2
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710:30405998
vscexrecpromp3t3:30407764
vscop841cf:30413486
vscop927cf:30413487
vscop436cf:30413488

```

</details>

 the needed data into your clipboard because it was too large to send. Please paste.

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
