### ISSUE TITLE
Color incorrect

### ISSUE THREAD

**Issue by CeruttiMaicon** [microsoft/vscode#139204]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.1
- OS Version: Linux Ubuntu

Steps to Reproduce:

1. 
![image](https://user-images.githubusercontent.com/25940408/146200121-9912d097-8416-4cf2-973c-377acc097eff.png)

2.
![image](https://user-images.githubusercontent.com/25940408/146200166-dbb341bb-fc07-40df-aa1f-7259dc2dcd92.png)

**Comment by hediet** [comment]
Can you describe what the actual and expected behaviors are?

**Comment by Tyriar** [comment]
The "blue" is more purple because of your theme, it defines the color.
