### ISSUE TITLE
Can someone please add the search input bar for QuickOpen views (`workbench.action.quickOpenView`) ?

### ISSUE THREAD

**Issue by akharrou** [microsoft/vscode#139260]
All QuickOpen commands normally come with a search input bar with focus so that we can quickly search, find and accept something from the results list... except the one for views, there's no search input bar ?

Can we please have that added ? It's super useful to quickly navigate log files, terminals and other things.

Thank you

**Comment by yume-chan** [comment]
`workbench.action.quickOpenView` is designed to use with keyboard shortcut (confirm when modifier key released).

For normal usage with search, use `workbench.action.openView`

**Comment by akharrou** [comment]
> `workbench.action.quickOpenView` is designed to use with keyboard shortcut (confirm when modifier key released).
> 
> For normal usage with search, use `workbench.action.openView`

Hey thanks man, that's what I was looking for. Also quick other side question, do you know if there is a command for quick opening symbols categorized by type, i.e quick open with `@:` as base search input ?

**Comment by yume-chan** [comment]
> quick open with @: as base search input ?

Looks like there is none. You may open a new issue requesting for that.

**Comment by akharrou** [comment]
> > quick open with @: as base search input ?
> 
> Looks like there is none. You may open a new issue requesting for that.

Done: https://github.com/microsoft/vscode/issues/139264#issuecomment-995498737

```json
{ "key": "cmd+p", "command": "workbench.action.quickOpen", "args": "@: " },
```
