### ISSUE TITLE
Invoke an extension defined in tasks.json? How / Documentation

### ISSUE THREAD

**Issue by bdcoder2** [microsoft/vscode#139259]
Futher to the following question:
[https://stackoverflow.com/questions/70371978/visual-studio-code-tasks-json-how-to-execute-an-extension-with-arguments](https://stackoverflow.com/questions/70371978/visual-studio-code-tasks-json-how-to-execute-an-extension-with-arguments), is there any way to invoke an extension defined in tasks.json ?

Example:

```
{
   "version": "2.0.0",
   "tasks": [
      {
         "label": "Minify Javascript File",
         "command": "olback.es6-css-minify.minifyExplorer",
         "args": [ "${cwd}\\some_file.js"]
       }
   ]
}
```

In the above "tasks.json" file, I want to minify a Javascript file using the olback.es6-css-minify extension (Minify) -- but am unable to find any documentation or examples of any syntax that illustrates how this can be accomplished.

If not possible, can it be?, I would suggest adding a "extension": property that when present is given the extension ID and method along with any arguments required to invoke the extension, ie:

```
{
   "version": "2.0.0",
   "tasks": [
      {
         "label": "Minify Javascript File",
         "extension": "olback.es6-css-minify.minifyExplorer",
         "args": [ "${cwd}\\some_file.js"]
       }
   ]
}
```

Would be most useful.

Thanks in advance.

**Comment by alexr00** [comment]
You can invoke commands from tasks.json tasks so long as the command returns a string value: https://code.visualstudio.com/docs/editor/variables-reference#_command-variables
