### ISSUE TITLE
Single terminal tab isn't respecting icon

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#139297]
Noticed this just now:

![image](https://user-images.githubusercontent.com/2193314/146395950-9c52ea9a-1a37-499f-80b9-73bf450e35d6.png)

This is the setting I'm using:

```json
"terminal.integrated.automationProfile.windows": {
  "path": "cmd.exe",
  "icon": "zap",
  "color": "terminal.ansiBlue"
},
```

Strangely it only seems to affect the task terminals:
![recording (5)](https://user-images.githubusercontent.com/2193314/146396137-b10c5dcb-0f68-497c-bcd8-f7b1f615033d.gif)

**Comment by meganrogge** [comment]
wonder if we could add a smoke test for this since we could check that it's not the default icon?
