### ISSUE TITLE
my vscode crashed ,agian.

### ISSUE THREAD

**Issue by 7NZ** [Microsoft/vscode#13928]
- VSCode Version:
1.5.3.
Language:
Chinese .
OS:
Windows 10.

- i was edit the code in a floder,then it crashed. it wasn't the first time.

**Comment by roblourens** [comment]
Have you tried the latest version, 1.6? Do you have any extensions installed? Does this happen randomly, or when you do something in particular?

**Comment by 7NZ** [comment]
Thanks for the reply. i have installled the latest version 1.6.1,and i have 6 extentions,and it happend randomly when i was edit the code in my working floder.

**Comment by roblourens** [comment]
It sounds like it hasn't crashed in 1.6 yet? If it does, can you try running without extensions (launch with `--disable-extensions` from the command line) to see if it still reproes)

**Comment by 7NZ** [comment]
actually,it has crashed once in 1.6. so i uninstall  the all extensions,and the situation hasn't happend yet.

**Comment by roblourens** [comment]
Please update if it is crashing again
