### ISSUE TITLE
add js/css/html/any code minifier

### ISSUE THREAD

**Issue by nityanand86876** [microsoft/vscode#139293]
Add a code minifier which can minify any code and can lesser the size of that process.
This will be very useful for website developer to minify the code that can be easily interpreted by the computer and can be resolved by the computer in less time.
This will increase the productivity of that site.
It will be slightly difficult but i am sure you will acheive it.
It will be the opposite of code formatter .
Do write back,
😊😊😊

**Comment by IllusionMH** [comment]
There are ton of different minifiers and configurations for them.

You can check extensions that will provide necessary minifications and configuration.
https://marketplace.visualstudio.com/search?term=minify&target=VSCode&category=All%20categories&sortBy=Relevance
