### ISSUE TITLE
Misleading invisible character warning on warning emoji

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#139201]
![image](https://user-images.githubusercontent.com/22350/146191252-8e25e4bf-9b84-4b2e-b940-fd6dbd58864d.png)

**Comment by hediet** [comment]
Just out of curiosity: Where do you use that emoji?

**Comment by joaomoreno** [comment]
README files

**Comment by hediet** [comment]
Do you think it might make sense to disable highlighting of invisible characters in markdown and text files? Non-breaking whitespace might actually make sense in those files.

**Comment by joaomoreno** [comment]
It's worth discussing. My intuition tells me it's OK.

**Comment by hediet** [comment]
I also think it is okay. Confusables are already disabled for text and markdown documents.
You can still override the default in your user settings.

Allowing variation selectors (which is used in the warning emoji) in arbitrary source code is dangerous. We could allow it just for text/markdown documents. But then I think we can just allow all invisible characters for text/markdown documents by default.
