### ISSUE TITLE
vscode API - workspace - Should send a single FileWillRenameEvent instead of separate events when moving multiple files at once 

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139217]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=147024&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=0a31a1a1-76c6-5f31-444a-2b6049ed7294&l=436

```
  1 failing
  1) vscode API - workspace
       Should send a single FileWillRenameEvent instead of separate events when moving multiple files at once#111867:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/1/s/extensions/vscode-api-tests/out/singlefolder-tests/workspace.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

A few lines above:

```
Unable to move/copy when source 'fake-fs:/' is parent of target 'fake-fs:/ellvsq'.
IGNORING workspace edit {}
```

Maybe another instance of a random file name clash?

**Comment by jrieken** [comment]
> Maybe another instance of a random file name clash?

My theory is that the `rndName` function returns an empty string, https://github.com/microsoft/vscode/blob/ab8e74352064fb4485ab8f9773f1554552165860/extensions/vscode-api-tests/src/utils.ts#L10-L12

It can happen that `Math.random().toString(36)` is just numbers which than all get replaced with `''`. I will come up with a new name generator and see how that goes

**Comment by jrieken** [comment]
Pushed better logic for `rndName`, calling `Math.random().toString(36).replace(/[^a-z]+/g, '').substr(0, 10)` in a loop until it hits `''` takes surprisingly little time

**Comment by bpasero** [comment]
Oh interesting, will check all the other usages we have of `Math.random` for file names, looks like there are more, even outside of tests.
