### ISSUE TITLE
A system error occured (EPERM: operation not permitted, utime

### ISSUE THREAD

**Issue by pptyasar** [Microsoft/vscode#13920]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:30:01.819Z)
- OS Version: Linux x64 3.13.0-92-generic
- Extensions: Tyriar.lorem-ipsum-1.0.0, medzhidov.font-awesome-codes-html-0.0.3

Steps to Reproduce:

When saving showing this

A system error occured (EPERM: operation not permitted, utime
2.

**Comment by roblourens** [comment]
This happened when you saved a file? Do you see it every time? Do you see it for every file?

**Comment by joshvoll** [comment]
I see this issue everytime on macOS i need to fix this issue can some one help me

**Comment by avsazonov** [comment]
This happens while file saving (in my case on debian linux). The system user Visual Studio Code launched is the same as owner of the file.

![screenshot from 2016-10-18 21 25 00](https://cloud.githubusercontent.com/assets/2930065/19481774/48a0067e-9579-11e6-826a-79ccd155a482.png)

**Comment by sero323** [comment]
Having the same issue. Cannot save the file.

**Comment by azizsaboor** [comment]
I was having the same issue, so I tried running code from the terminal as admin... and it seemed to solve the problem. However, then I started to see the warning that it was not recommended to run code as admin. Eventually, I ended the problem by changing the folder permissions to me (as in the current $USER).

**Comment by avsazonov** [comment]
>  changing the folder ownership from root
that is my case, thanks for the guess

**Comment by bpasero** [comment]
@pptyasar @joshvoll @azizsaboor @avsazonov @sero323 can you try this:
* have a dirty file
* save it
=> you should not see the error

* have a non dirty file
* save it
=> you get the error?

**Comment by azizsaboor** [comment]
Like I said above... after my fix, I no longer see the error... even for a non-dirty file.

**Comment by bpasero** [comment]
To give some background: the error message talks about `utime` and there was a change in 1.6 that I added that would allow you to save a file even if it was not dirty. We would just increase the mtime of the file (aka touch it) so that you can trigger external file watchers (e.g. nodemon).

**Comment by sero323** [comment]
@bpasero You are correct. If the file has not been edited and you try to save, you get the error, but If you make changes to the file and save you will not get the error.

**Comment by bpasero** [comment]
Thanks for trying, working on a fix...

**Comment by bpasero** [comment]
Now ignoring any error bubbling up from the utimes call since this is just about supporting cases where you are using an external watcher. I am still not sure why writing to the file would work but changing the atime and mtime does not. If someone has an idea, the code starts from https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L327

**Comment by joaomoreno** [comment]
@bpasero Node's documentation says

> The value should be a Unix timestamp in seconds. For example, Date.now() returns milliseconds, so it should be divided by 1000 before passing it in.

You seem to [not be doing that](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L327), which could explain the `EPERM`.

Furthermore, [pfs.utimes](https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/pfs.ts#L104) parameters should be `number`, not `Date`.

**Comment by duttakapil** [comment]
I'm facing the same issue on Windows 10 Home, with the latest version of VS Code

**Comment by bpasero** [comment]
@duttakapil 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by duttakapil** [comment]
@bpasero just did that. Same issue.

**Comment by bpasero** [comment]
@duttakapil can you hover over the error message to see its full text. Is it talking about `utime` as well?

**Comment by duttakapil** [comment]
Here you go : 
![vscodebug](https://cloud.githubusercontent.com/assets/6577624/20300597/e80400ee-ab45-11e6-8d11-f355f63b2717.png)

**Comment by bpasero** [comment]
That is a different error that indicates you are missing permissions to save the file as the user you started Code with.

**Comment by raphaelkieling** [comment]
If your system os is Linux, jut try this in terminal.
sudo chmod 777 name_file

**Comment by Remijeous** [comment]
Just open the visual studio in Administrator mode

**Comment by yanxiaodi** [comment]
@Remijeous is right. Run vs code as administrator mode.
