### ISSUE TITLE
break无法跳出while循环

### ISSUE THREAD

**Issue by Python020703** [microsoft/vscode#139256]
#include<stdio.h>
#include<stdlib.h>
#include<time.h>
int add(int a,int b)
{
    int add;
    add=a+b;
    return add;
}
int sub(int a,int b)
{
    int sub;
    sub=a-b;
    return sub;
}
int mul(int a,int b)
{
    int mul;
    mul=a*b;
    return mul;
}
float di(int a,int b)
{
   float div;
   div=(float)a/(float)b;
   int m=(int)div;
   int n=(int)(div*10)%10;
   int p=(int)(div*100)%10;
   int q=(int)(div*1000)%10;
   if(q>=5) p++;
   float t=m+n*0.1+p*0.01;
   return t;
}
int main()
{
    int m,a,b,i;
    double x;
    char ch;
    FILE *fp;
    srand(time(NULL));
    fp=fopen("result.txt","w");
    if(fp==NULL)
    {
        puts("can`t open result.txt");
        exit(0);
    }
    printf("计算练习，电脑随机生成5道题目\n");
    printf("十以内加、减、乘、除（四舍五入保留2小数），请答题：\n");
    while(1)
    {   int corr=0;
        for(i=1;i<=5;i++)
        {
        a=1+rand()%10;
        b=1+rand()%10;
        m=1+rand()%4;
        if(m==1)
        {
            printf("%d+%d=",a,b);
            scanf("%lf",&x);
            fprintf(fp,"%d+%d=%lf",a,b,x);
            if(x==add(a,b)) corr++;
        }
        else if(m==2)
        {
            printf("%d-%d=",a,b);
            scanf("%lf",&x);
            fprintf(fp,"%d-%d=%lf",a,b,x);
            if(x==sub(a,b)) corr++;
        }
        else if(m==3)
        {
            printf("%d*%d=",a,b);
            scanf("%lf",&x);
            fprintf(fp,"%d*%d=%lf",a,b,x);
            if(x==mul(a,b)) corr++;
        }
        else if(m==4)
        {
            printf("%d/%d=",a,b);
            scanf("%lf",&x);
            fprintf(fp,"%d/%d=%lf",a,b,x);
            if(x==di(a,b)) corr++;
        }
        }
        printf("正确率为%d%%",corr*20);
        fprintf(fp,"正确率为%d%%",corr*20);
        printf("\n是否继续，如果是输入Y，否则输入N\n");
        ch=getchar();
        getchar();
        if(ch=='N'||ch=='n')
            break;
    }
    fclose(fp);
    return 0;
}

**Comment by Python020703** [comment]
一直跳不出while循环

**Comment by heartacker** [comment]
你这是代码问题，你应该问编程专家吧。哥哥
