### ISSUE TITLE
vsCode用github账号登录不了

### ISSUE THREAD

**Issue by studyforeverY** [microsoft/vscode#139275]
Issue Type: <b>Feature Request</b>

vsCode用github账号登录不了，提示undefind和timeout重试多次也一样

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

**Comment by CodeCrazy-ywt** [comment]
Cannot login via github. It says “undefined” and “timeout”. Have tried many times.
