### ISSUE TITLE
Enable ESLint rule to disallow variable declarations in case/default clauses 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#139236]
Variables declared in case/default clauses can be referenced throughout the switch block, but will throw a runtime error, like so: 

```ts
switch (someVar) {
    case 'bar':
         const a = 42;
         break;
    case 'baz':
        console.log(a); // Will throw "ReferenceError: Cannot access 'a' before initialization" at runtime
        break;
}

```

We can prevent these with https://eslint.org/docs/rules/no-case-declarations.

/cc @tyriar @mjbvz @digitarald

**Comment by mjbvz** [comment]
Good idea! Already started looking into this and should have a PR shortly
