### ISSUE TITLE
Settings sync across intel and arm Mac produces missing syntax highlighting/theme issues (arm side only).

### ISSUE THREAD

**Issue by jtkiley** [microsoft/vscode#139226]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.16.3 (Universal)
- OS Version: 11.6.1 (intel) 12.1 (arm)

Steps to Reproduce:

1. Remove install and `~/Library` items on arm Mac.
2. Install VS Code on arm Mac.
3. Verify that syntax highlighting and themes work normally.
4. Turn on Settings Sync.
5. Note missing syntax highlighting, dark text on dark background (in dark mode) in editor, terminal, and logs. In light mode, it's dark text on a light background, but still no syntax highlighting in the editor or color in the terminal (in text only; colors in my prompt symbols still work).

This started sometime in the last month or so, and it has persisted through a couple of updates. My settings aren't all that elaborate: auto-match system theme with Light+/Dark+), Source Code Pro and some turned up font sizes, python pointed to a conda environment.

I tried no extensions (no effect, either bisect or disable all) and a fresh setup (works until settings sync is turned on). At all times, the Intel Mac side of the sync works as expected.

In case it matters (e.g., something like an HDR screen bug in the past), the Intel Mac is a 2020 iMac and the arm Mac is a 14-inch MBP.

Any ideas?

**Comment by aeschli** [comment]
Can you add a screenshot?

This could be related to the Source Code Pro font. Check our https://github.com/microsoft/vscode/issues/110640

**Comment by jtkiley** [comment]
That fixed it, thanks! It looked just like the first image in #100840.

With VS Code closed, I ran:

```
brew uninstall --cask font-source-code-pro
brew install --cask font-source-code-pro
```

It did pull the Google Fonts version (a recipe change in the home-brew cask a few days after I installed it initially), and it seems fine now.
