### ISSUE TITLE
VS code Bad CPU type in executable

### ISSUE THREAD

**Issue by ShaniTiomkin** [microsoft/vscode#139246]
Hey,
I got the new MacBook Air with M1
Until now, I used the MacBook Air 2015
I tried to run the code on VS Code, and got the following error:
Bad CPU type in executable

Can you please assist me with this issue?

Thanks,
Shani

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/146282595-84239a85-9dcf-4213-ae9b-435b290e887f.png)
Have you downloaded the Universal build from this page?

**Comment by ShaniTiomkin** [comment]
Hey,
Thanks for reaching out 
We solved the issue

Thanks
