### ISSUE TITLE
VSCode Integrated Terminal ignores XTerm escape sequence for "set title"

### ISSUE THREAD

**Issue by ddurschlag** [microsoft/vscode#139288]
Issue Type: <b>Bug</b>

Send an XTerm set-title escape sequence (e.g. "\e]0;TITLE\a" typically seen in zero-width brackets as "\[\e]0;TITLE\a\]" ) in the integrated terminal (notably in PS1, where it is common) -- VSCode's title for that terminal does not change.

Expected behavior: VSCode's title for the terminal changes to match the contents of the escape.

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:02:02.183Z)
OS version: Linux x64 4.19.0-13-amd64
Restricted Mode: Yes

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
vscode-test-explorer|hbe|2.21.1
test-adapter-converter|ms-|0.1.5

</details>

**Comment by Tyriar** [comment]
You need to change the `title` setting to get the title sequence to show up in the UI, try:

```
"terminal.integrated.tabs.title": "${process}${separator}${sequence}",
```

![image](https://user-images.githubusercontent.com/2193314/146418676-59cdae97-3806-4621-9bc0-9690099f2fe9.png)
