### ISSUE TITLE
code from terminal not transferring focus to a vs code window on macOS

### ISSUE THREAD

**Issue by vdovhanych** [microsoft/vscode#139215]
When opening project from the macOS terminal with `code .` vs code opens in the background and focus in not transferred to that window. This also happens if you already have project open in and it wont bring focus to that window.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 
Version: 1.63.1 (Universal)
Commit: fe719cd3e5825bf14e14182fddeb88ee8daf044f
Date: 2021-12-14T02:13:13.580Z (1 day ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0
- OS Version:
macOS Version 12.1 (21C52)

Steps to Reproduce:

1. Open project from default macOS terminal with `code .` in the project directory. Focus stays on terminal and is not transfer to vscode window (opens in the background) 

https://user-images.githubusercontent.com/45185420/146221417-c3ea3a57-19c3-4200-aeae-0442bf0de136.mov

**Comment by bpasero** [comment]
Maybe related to the change we did to use `open` command.

**Comment by deepak1556** [comment]
I am unable to repro with the steps provided, what happens when you try the following 

```
> open -b com.microsoft.VSCode --args <abosolute-path-to-your-project>
```

**Comment by vdovhanych** [comment]
> I am unable to repro with the steps provided, what happens when you try the following
> 
> ```
> > open -b com.microsoft.VSCode --args <abosolute-path-to-your-project>
> ```

Still the same behaviour as was described in the original post. Attaching a video to demonstrate.

https://user-images.githubusercontent.com/45185420/146337625-a5a64f34-6240-4e85-a505-a68cf0a954cb.mov

If it helps to debug, this started happening to me after the latest vscode or macOS update, not sure what broke it because both were updated approx at the same time.

**Comment by vdovhanych** [comment]
I have resolved this issue. This is related to enabling `Secure keyboard entry` in the terminal options. If enabled, you can reproduce the described behaviour. (also affects github-cli with opening the browser)
![Screenshot 2021-12-16 at 11 05 36](https://user-images.githubusercontent.com/45185420/146351204-466373f6-8f47-4117-92d0-e068b6a69032.png)

**Comment by deepak1556** [comment]
Thanks for narrowing down the issue, there is not much we can do here as its a OS behavior, `Secure Keyboard Entry` uses secure input event feature https://developer.apple.com/library/archive/technotes/tn2150/_index.html which expects the process calling this method will have access to keyboard input and not other process intercepting it.

**Comment by deepak1556** [comment]
Usually an application has to use this feature fairly by using this feature when only when receiving secure inputs and then disable it after that so that access can be given to other applications, but not for entire lifetime of the application. Please check `Using Secure Event Input Fairly` in the above link

**Comment by vdovhanych** [comment]
This makes perfect sense that it would prevent this functionality. Thanks for the clarification and your help!

**Comment by kvz** [comment]
Same for iTerm2, this was enabled:


![image](https://github.com/microsoft/vscode/assets/26752/0f567fc9-d207-467e-88e3-91b4a7dc73cb)

Fixed by unchecking. Thanks I would have never known without this issue!
