### ISSUE TITLE
Traditional Chinese(New Phonetic IME) input bug on github.dev

### ISSUE THREAD

**Issue by nicehorse06** [microsoft/vscode#139257]
Traditional Chinese input method can not display correctly on github.dev.
This bug also happen in Ubuntu OS with other traditional Chinese input method.
I use New Phonetic IME
[Bug example video link](https://youtu.be/5iySMG2J7s4)

Version: 1.63.1
Commit: fe719cd3e5825bf14e14182fddeb88ee8daf044f
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36 Edg/96.0.1054.53
Embedder: github.dev

**Comment by yume-chan** [comment]
Should be related to #138704

**Comment by nicehorse06** [comment]
This bug only happen in browser like https://vscode.dev/
Downloaded version is work fine.

**Comment by alexdima** [comment]
@nicehorse06 You can use the insiders version at https://insiders.vscode.dev/

**Comment by nicehorse06** [comment]
/verified
My IME work fine at https://insiders.vscode.dev/, thank your help @alexdima.
