### ISSUE TITLE
Thunder Client

### ISSUE THREAD

**Issue by ruby-000** [microsoft/vscode#139203]
Issue Type: <b>Bug</b>

In extensions marketplace I could not find Thunder Client

VS Code version: Code - OSS 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-07T19:37:13.664Z)
OS version: Linux x64 5.13.19-2-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (3 x 2419)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 1, 1|
|Memory (System)|3.92GB (1.15GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
gitignore|cod|0.7.0
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|11.7.0
git-project-manager|fel|1.8.2
git-graph|mhu|1.30.0
git-extension-pack|pin|1.0.0
vscode-boot-dev-pack|Piv|0.1.0
vscode-spring-boot|Piv|1.29.0
fabric8-analytics|red|0.3.5
java|red|1.1.0
vscode-gitweblinks|red|2.6.0
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.19.0
vscode-java-test|vsc|0.33.0
vscode-maven|vsc|0.34.1
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.8.0
vscode-open-in-github|ziy|1.4.1

</details>

**Comment by gjsjohnmurray** [comment]
I think the Manjaro distribution of VS Code uses Open VSX instead of Marketplace.
