### ISSUE TITLE
Smoke: sometimes `enter` is not picking the result

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139230]
This happened in https://dev.azure.com/monacotools/Monaco/_build/results?buildId=146945&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=07088cf7-fede-5f74-0d50-155edd53af7d&l=76

```
[2021-12-15T04:59:57.757Z] setValue .quick-input-widget .quick-input-box input readme.md
[2021-12-15T04:59:57.768Z] getElements .quick-input-widget .quick-input-list .monaco-list-row .label-name
[2021-12-15T04:59:57.908Z] getElements .quick-input-widget .quick-input-list .monaco-list-row .label-name
[2021-12-15T04:59:58.117Z] getElements .quick-input-widget .quick-input-list .monaco-list-row .label-name
[2021-12-15T04:59:58.151Z] dispatchKeybinding enter
```
![verifies_that__hot_exit__works_for_dirty_files__without_delay_ (1)](https://user-images.githubusercontent.com/900690/146249322-3e56d545-a51d-4e0b-8b3f-8fc8ed9864fc.png)

We see `readme.md` as search result but dispatching `enter` does not open the editor.

//cc @Tyriar

**Comment by Tyriar** [comment]
My message from the linked issue:

> the above screenshot shows the quick access util to open a file is failing, any ideas how this could happen?
>
> https://github.com/microsoft/vscode/blob/224701f74d0f275bbe814f3689729ec323499478/test/automation/src/quickaccess.ts#L82-L88
>
> Enter might be getting triggered before the result is ready for the enter?

**Comment by roblourens** [comment]
Is it possible that the input box didn't have/lost output somehow? Looks similar to this https://github.com/microsoft/vscode/issues/139216#issuecomment-995307679

**Comment by bpasero** [comment]
This needs some investigation as soon as possible because many smoke tests rely on quick pick for opening files.

**Comment by TylerLeonhardt** [comment]
I can look into this today

**Comment by bpasero** [comment]
Looking into some changes to be more consistent what we do when picking an element, might help for this one: https://github.com/microsoft/vscode/pull/139368

**Comment by rebornix** [comment]
@bpasero the change for `openFile` looks great and inspiring, especially that it doesn't necessarily rely on element focus. I wonder if we can do the same for https://github.com/microsoft/vscode/blob/2d77c9e23ab39c3eb1ade77215af02359ef6b7ac/test/automation/src/quickaccess.ts#L154-L155

For example, in https://github.com/microsoft/vscode/issues/139216#issuecomment-997078687, we search for a command then want to run the command by pressing `enter`, however it's blocked by the notification sealing the focus. The focus stealing can happen anytime, by any component. If we can pick the first result and run, it would make the tests less flaky.

**Comment by bpasero** [comment]
@rebornix but a notification toast is never stealing keyboard focus, otherwise users would constantly complain that typing in the editor stops working once a toast shows up?

In https://github.com/microsoft/vscode/issues/139216#issuecomment-997078687, the picker would actually close if it had lost focus, so I doubt that this is the issue here.

The method `waitForQuickInputElementFocused` is mainly assuring that there is a result item selected in the picker as far as I can tell (I did not add that method).

I wonder what the test failure in https://github.com/microsoft/vscode/issues/139216#issuecomment-997078687 is specifically? Then we can look at the `smoke-test-runner.log`.

**Comment by bpasero** [comment]
I think this one is probably fine to close, the smoke tests had a lot of green runs lately...
