### ISSUE TITLE
Reopen closed tab

### ISSUE THREAD

**Issue by hassandraga** [microsoft/vscode#139233]
I suggest to add "_Reopen closed tab_" when the user click right on a tab, or by menu. I guess it's a nice feature to have.

**Comment by knmn2000** [comment]
Hey @hassandraga , you can reopen closed tabs by using the shortcut Ctrl+Shift+T.

**Comment by hassandraga** [comment]
> Hey @hassandraga , you can reopen closed tabs by using the shortcut Ctrl+Shift+T.

I know that, many editors and web browsers use `Ctrl + Shift + T`, but also they provide click menu and VS don't.
