### ISSUE TITLE
Inconsistent hovers for split actions

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#139213]
<img width="146" alt="CleanShot 2021-12-15 at 07 37 24@2x" src="https://user-images.githubusercontent.com/35271042/146216768-fe1c9a4f-2276-4ba2-8c38-4be5d66a65f6.png">

<img width="146" src="https://user-images.githubusercontent.com/35271042/146217064-e9eb25b9-6099-4fd4-8951-073520184460.png">

I think we originally talked about the split action having two hovers, like in the terminal, but not sure why that changed for the run button.

**Comment by Tyriar** [comment]
🤷 it's using the same widget afaik, the "shared hover" was meant to help indicate that they're linked.

**Comment by weinand** [comment]
No, they are not using the same widget because the run button's behavior was too different.
