### ISSUE TITLE
Refresh Code Lenses on document save

### ISSUE THREAD

**Issue by jonaskrask** [microsoft/vscode#139210]
I am working on an LSP implementation that provides code lenses for launching code. In our case, we can only provide sensible code lenses after the files have been saved. If the user does not modify the source file after the save or does not change focus, VS Code will not send a request for code lenses. 

We considered using the LSP request `workspace/codeLens/refresh` but the client replies back with 

```
ResponseError { 
  code: -32601, 
  message: "Unhandled method workspace/codeLens/refresh", 
  data: None 
}
```

Do you intend to implement the LSP request in the near future or do you have other suggestions for how to go about refreshing the code lenses after a document save?

**Comment by jrieken** [comment]
Unsure about the LSP specifics but in the vscode-API there is [`onDidChangeCodeLenses?: Event<void>;`](https://github.com/microsoft/vscode/blob/ab80daed7409a4ec2c6c86be1f850600931c9177/src/vscode-dts/vscode.d.ts#L2460) for cases like that. To answer the question: I don't think it makes sense to ask each and every code lens provider for an update on save, instead your provider should implement the specific event to tell us to update. If there are specific issues with LSP client lib around this feature than you should file an issue over there
