### ISSUE TITLE
VS Code does not use launch.json arguments when I press Debug Python File

### ISSUE THREAD

**Issue by ejkitchen** [microsoft/vscode#139251]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.1
- OS Version: macOS Monterey 12.0.1

Steps to Reproduce:

1. Open VS Code for Mac
2. Open a folder containing a python file (not a project, I don't want one)
3. Create a launch.json file with arguments
4. Click on python file (open it)
5. Press F5 or select Run\Debug and all parameters from launch.json are passed
6. BUT if I press the "Debug Python file" button to the right of the filename (see red circle in image), parameters are not passed
7. If I open the Run&Debug pane and then press on the button circled in green with the right profile, it works

What is really baffling to me is nowhere in the documentation does it state the Debug Python file button does not pass arguments. Is there a way to force that button to use my launch.json? I rarely have the Run&Debug pane open so I have to do 2 extra clicks to get to this and on a Mac with my Logitech keyboard, pressing F5 requires me to move my fingers way off the middle to do Fn-F5. I also don't want to create a keyboard shortcut for F5. Is there a way to simply get that button in red to do what I want it to do?

If not, the documentation should explicitly state that that button does not allow for the passing of command-line arguments. But then again I find it really strange that you would have different mechanisms for debugging with one not having support for arguments.

EJK

![VS Code buttons](https://user-images.githubusercontent.com/823511/146288165-c5b82f28-2465-4cf7-a35b-18ff7a81f8a5.png)

**Comment by weinand** [comment]
The Run/debug button is a contribution of the Python extension to simplify running/debugging single files. It is completely independent from VS Code's debug configuration mechanism (which relies on launch.json configuration files).

**Comment by ejkitchen** [comment]
Thank you for the quick responses! In the future, how can I determine where a button in the UI comes from? I have 20 extensions installed and I never clued in that this came from somewhere else. When I look at some of your docs, for example here: https://code.visualstudio.com/docs/python/debugging, that button shows up and it's not clear to me that this is from a plugin. Especially this image (https://code.visualstudio.com/assets/docs/python/debugging/debug-configurations.png) made me think that "Python File Debug the currently active Python file" was simply the command related to that button. 

BTW, love VS Code. You guys have done an amazing job with the product and the quick and constant releases are fantastic.
