### ISSUE TITLE
color theme

### ISSUE THREAD

**Issue by aileenaileen** [microsoft/vscode#139207]
Issue Type: <b>Bug</b>

for any color theme all of my files and icons have color except my .sol files

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:54.292Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<img width="917" alt="image" src="https://user-images.githubusercontent.com/74773459/146206604-2cb4f8db-d4c6-47a4-9f37-7bbb084ad38c.png">

**Comment by IllusionMH** [comment]
VS Code doesn't have support for this kind of files out of the box. Only icon mapping in default icon theme. Most likely you would see Plain Text in status bar when in this file.

You need to install extension that provides syntax highlight (and maybe other advanced features).

**Comment by aeschli** [comment]
Thanks @IllusionMH  for the explanation!
