### ISSUE TITLE
css selector specificity disable

### ISSUE THREAD

**Issue by lmace-eriks** [microsoft/vscode#139237]
Issue Type: <b>Feature Request</b>

Is there a way to disable the popup window for css selector specificity? Very annoying while coding. Constantly gets in the way of where I need to put my cursor. Thank you.

VS Code version: Code 1.63.0 (Universal) (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
![Screen Shot 2021-12-15 at 15 42 30](https://user-images.githubusercontent.com/95253580/146269475-526b6ee0-2a7f-49d0-bd3e-bbbaca7ddaef.png)

**Comment by aeschli** [comment]
There are already various hover settings, e.g. `"editor.hover.enabled": false`.
You can also set that only for by css
```
  "[css]": {
    "editor.hover.enabled": false
  }
```

Is that good enough?
