### ISSUE TITLE
Terminal Windows Synced across IDE Windows

### ISSUE THREAD

**Issue by craig-seeman** [microsoft/vscode#139211]
Issue Type: <b>Bug</b>

Not able to reproduce (yet)

Has anyone experienced this? 

I had multiple windows open, each with their own individual terminal, and today when I started VS Code, for some reason they were all synced to one and not individual (normally they're all under their own directory and not shared). 

To explain better: I was typing in one terminal window and it was being duplicated to all of the other windows.

When I closed VS code and re-opened this problem disappeared.

VS Code version: Code 1.63.1 (Universal) (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:13.580Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

**Comment by yume-chan** [comment]
I met this problem when this feature was first landed in insiders version. Have you updated vscode before it happened? Maybe it's not properly handed there?

**Comment by Tyriar** [comment]
Let us know if you can find more solid repro steps, not sure how this could happen but maybe something to do with multiple windows asking if a terminal process is an orphan and multiple "adopting" it.

**Comment by craig-seeman** [comment]
> Let us know if you can find more solid repro steps, not sure how this could happen but maybe something to do with multiple windows asking if a terminal process is an orphan and multiple "adopting" it.

Thanks! I will keep an eye out and see if I can get it to happen again. I agree it's very strange and might be some edge case bug. One thing I noted was VS code started VERY quickly when this happened - compared to it taking a few seconds to open windows etc etc.

**Comment by craig-seeman** [comment]
Closing issue - has not happened for quite some time now.
