### ISSUE TITLE
Visual Studio Code Locks Windows 10 System With Over 2000 "Git for Windows" Processes in Task Manager

### ISSUE THREAD

**Issue by fatdog1** [microsoft/vscode#139208]
Does this issue occur when all extensions are disabled?: Yes/No 
yes

- VS Code Version:  1.63
- OS Version:  Windows 10 21H1 (OS Build 19043.1387)

Steps to Reproduce:

1. Launch VS Code
2. Watch several thousand instances of "Git for Windows" processes in Task Manager lock the system with near 100% CPU and 100% memory. The "taskkill /im git.exe /t /f" fails to kill the processes in an elevated CMD. Clicking on the processes in Task Manager allows me to kill several of the Git for Windows processes long enough for me to restart the system before a total lockup. Restarting the system is the only way to use the system again.
3.  see attached
![Visual Studio Code Error](https://user-images.githubusercontent.com/19149155/146206753-2f8b057c-af03-4b61-98ec-ddddcec941ea.jpg)
![Git Error (1)](https://user-images.githubusercontent.com/19149155/146206889-7106896a-63e6-42ee-8355-3bc2d869f97a.jpg)

**Comment by fatdog1** [comment]
Update on this issue. VS Code is one program that launches Git.exe. I uninstalled Git.exe from C:\ProgramFiles\Git\unins001.exe and I was able to use VS Code with no issues. I have not reinstalled Git.exe yet.

**Comment by lszomoru** [comment]
@fatdog1, could you please try reinstalling Git for Windows `2.34.1` and see if you are still able to reproduce the issue? Thanks!

**Comment by fatdog1** [comment]
I did and it works fine now, thanks.

**Comment by lszomoru** [comment]
Closing the issue for now. Please reopen if the issue reoccurs.

**Comment by fatdog1** [comment]
Thanks!
