### ISSUE TITLE
auto completion css

### ISSUE THREAD

**Issue by wilfried8358** [microsoft/vscode#139232]
Nous avons écrit les données nécessaires dans votre presse-papiers, car elles étaient trop volumineuses à envoyer. Veuillez les coller.

avec visual studio code
css ne m'affiche plus les raccourci flexbox comme :
display flex
justify-content etc...

comment je peut faire ?

Translation:
with visual studio code
css no longer shows me flexbox shortcuts like:
flex display
justify-content etc...

how can I do this?

**Comment by aeschli** [comment]
Can you add a small code sample and steps that show the problem?
Is something not working as did before or do you ask for a new feature?

![image](https://user-images.githubusercontent.com/6461412/146334001-e9ebc0a9-9d71-4089-8c26-8e699731e056.png)
