### ISSUE TITLE
Is there, else can we have, a command for quick opening symbols categorized by type, i.e quickopen w/ `@:` as base search input ?

### ISSUE THREAD

**Issue by akharrou** [microsoft/vscode#139264]
Vscode has a feature that lets you search all symbols in a file/workspace (`workbench.action.gotoSymbol`). it's super useful and I use it all the time. By default, it seems to sort results by name. Vscode exposes this command as `workbench.action.gotoSymbol` and it is bindable ofc.

Vscode also allows searching all symbols in a file/workspace and sorting the results by category: with QuickOpen and a base search input of `@:`. the only problem is I can't seem to find the corresponding command for it, or at least the one that is bindable to a key.

Would it be possible to add it ? (e.g. ` workbench.action.gotoSymbolByCategory` and `workbench.action.showAllSymbolsByCategory`)

Thank you.

**Comment by bpasero** [comment]
The generic `workbench.action.quickOpen` can be passed the input in as argument.

**Comment by akharrou** [comment]
> The generic `workbench.action.quickOpen` can be passed the input in as argument.

Like with a keybinding ? Or how so ? the idea is that just like `workbench.action.gotoSymbol`, you wouldn't have to bring up quickOpen and type `@:`.

**Comment by akharrou** [comment]
Ah I see:

```json
{ "key": "cmd+p", "command": "workbench.action.quickOpen", "args": "@: " },
```

Thanks @bpasero !

---

Just a side question, how do you find out about the available arguments of commands ?

**Comment by TylerLeonhardt** [comment]
Some of them are documented here:
https://code.visualstudio.com/api/references/commands

Others you may have to look in the code for references as they were likely not documented because they aren't necessarily set in stone like the vscode API is.
