### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by EmericBayard** [microsoft/vscode#139280]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63
- OS Version: MacOS Darwin x64 20.6.0

Log : Extension host (LocalProcess) terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, vscode.configuration-editing, vscode.extension-editing, vscode.json-language-features, vscode.npm, eg2.vscode-npm-script, vscode.debug-auto-launch, vscode.git-base, cssho.vscode-svgviewer, donjayamanne.githistory, firsttris.vscode-jest-runner, formulahendry.auto-close-tag, formulahendry.auto-rename-tag, GitHub.vscode-pull-request-github, HookyQR.beautify, joelday.docthis, johnpapa.vscode-peacock, kiteco.kite, mblode.twig-language, ms-mssql.mssql, ritwickdey.LiveServer, zhuangtongfa.material-theme, msjsdiag.cordova-tools, vscode.git, ritwickdey.live-sass, vscode.github-authentication, ahmadawais.emoji-log-vscode, vscode.github, ms-mssql.data-workspace-vscode, ms-mssql.sql-database-projects-vscode, vscode.emmet, vscode.merge-conflict, alefragnani.Bookmarks, formulahendry.code-runner, ms-vscode-remote.remote-containers, PKief.material-icon-theme, waderyan.gitblame

**Comment by acermez** [comment]
@alexdima Thank you! I had the same issue described by OP, using the "Start Extension Bisect" command, I was able to locate the bad extension (Spell checking extension) and now everything is working fine. Thanks again!

**Comment by alexdima** [comment]
@acermez Great!

@EmericBayard Were you able to track down the problematic extension?

**Comment by namnh06** [comment]
> @alexdima Thank you! I had the same issue described by OP, using the "Start Extension Bisect" command, I was able to locate the bad extension (Spell checking extension) and now everything is working fine. Thanks again!

Yes, this one, https://marketplace.visualstudio.com/items?itemName=ban.spellright
I removed it, and everything is working well now.
