### ISSUE TITLE
Cannot have files of the same name but different extensions open at the same time. Linux, C++, foo.cpp foo.h

### ISSUE THREAD

**Issue by Hunanbean** [microsoft/vscode#139258]
Does this issue occur when all extensions are disabled?: Yes/No Yes

- VS Code Version: Version: 1.62.0
- OS Version:  Linux x64 5.10.83-1-MANJARO
Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-07T19:37:13.664Z
Electron: 13.6.3
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.10.83-1-MANJARO
Steps to Reproduce:

1. have a file named foo.cpp and a file named foo.h
2. notice they cannot be open at the same time

**Comment by chrmarti** [comment]
This works for me. Where do you open them from? Does one close when the other opens or does the second one not open at all? Could you attach a screenshot?

**Comment by Hunanbean** [comment]
> This works for me. Where do you open them from? Does one close when the other opens or does the second one not open at all? Could you attach a screenshot?

I have opened them from the built in 'Explorer' and also from my OS. The result is the same, one closes and the other opens.
an animated screenshot would take some time.
I suspect this may be a Manjaro specific issue.

Thank you

**Comment by bpasero** [comment]
Maybe follow our docs to resolve this: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

**Comment by Hunanbean** [comment]
> Maybe follow our docs to resolve this: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

That resolved the issue, but does not really explain why it only happened on files of the same name but different extensions.

Thank you
