### ISSUE TITLE
Document how to disable CSS linting

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#1392]
I'm working on an extension that supports CSSLint. While you can disable VSC's linting of JS files (https://code.visualstudio.com/docs/languages/javascript#_javascript-linters-eslint-jshint), you can't disable VSC's CSS linting.

**Comment by cfjedimaster** [comment]
Ok, it *is* supported, just not documented. :)

**Comment by egamma** [comment]
@cfjedimaster This is what I thought :smile: 

@aeschli can you look into updates in the doc.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-docs#86
