### ISSUE TITLE
`hasCustomMarkdownPreview` disables preview buttons in context menus as well

### ISSUE THREAD

**Issue by SeriousBug** [microsoft/vscode#139240]
`hasCustomMarkdownPreview` allows extensions to disable the "Open Preview" button in markdown files. This option should also disable the "Open Preview" button in the context menus.

![image](https://user-images.githubusercontent.com/19672699/144149137-8eb8c192-0b8a-4083-900a-f248ec43c945.png)

_Originally posted by @rchiodo in https://github.com/microsoft/vscode/issues/136388#issuecomment-983149447_

**Comment by rchiodo** [comment]
/verified

In stable:

![image](https://user-images.githubusercontent.com/19672699/151468757-68d51e48-1bc7-4291-a864-3eab8b72f74d.png)

In insiders:

![image](https://user-images.githubusercontent.com/19672699/151468793-6c7a25ac-da05-4947-aae3-dedf1ef298e0.png)
