### ISSUE TITLE
Decorations rendered incorrectly in scaled editor

### ISSUE THREAD

**Issue by somebee** [microsoft/vscode#139281]
Does this issue occur when all extensions are disabled?: Yes

When the editor element or a parent is transformed using css, the decorations, selections and caret is rendered incorrectly. This happens on every line that contains a foreign element (ie. a color preview thumbnail).
If the theme font is not considered to be monospaced the bug will affect all lines.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/8467/146354958-840f8951-f70e-4224-ba2e-00a298dfa2d5.png">

Steps to Reproduce:

1. Go to vscode.dev
2. Create a simple css file with the content `body { color: red; }`
3. Scale the document `document.body.style.transform = "scale(0.75)"`
4. Select the code and/or move caret around to see wrong positions and sizes

**Comment by IanMatthewHuff** [comment]
Verified. Looks good now. Also verified the old broken behavior on non-insiders.
