### ISSUE TITLE
Button to preview theme in theme details at marketplace

### ISSUE THREAD

**Issue by robson036** [microsoft/vscode#139343]
The latest update brought the theme search and preview from theme choosin modal, and it have been very useful.
I think would be great if possible place a button to preview theme also in marketplace item page.
The "Preview" button could be placed next to the "Install" button. By leaving the marketplace screen, could change to predefined theme.

**Comment by aeschli** [comment]
@sandy081 FYI there's already a command to preview a theme (see https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/themes/browser/themes.contribution.ts#L456), but I can also improve it to show a quick pick
