### ISSUE TITLE
User is no longer prompted with all build tasks when there are multiple default built tasks in a multi-root workspace

### ISSUE THREAD

**Issue by KaravolisL** [microsoft/vscode#139384]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:
1. Create a multi-root workspace like this:
```
{
    "folders": [
        {
            "path": "subworkspace1",
            "name": "subworkspace1"
        },
        {
            "path": "subworkspace2",
            "name": "subworkspace2"
        }
    ]
}
```
2. Within each folder, create .vscode/tasks.json files with the following content:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Subworkspace 1 build task",
            "type": "shell",
            "command": "echo Subworkspace1",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Subworkspace 2 build task",
            "type": "shell",
            "command": "echo Subworkspace2",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
3. Click ctrl+shift+p and select Tasks: Run Build Task
4. The build task for subworkspace 1 is run

I'm not sure what the expected behavior is in this case, but I've noticed it was changed between version 1.62 and 1.63. Previously, Tasks: Run Build Task would show all build tasks when there were multiple default ones, but now it runs the first default build task in the list of folders.

Let me know if any information is missing, or if this is actually expected behavior now

**Comment by alexr00** [comment]
We should still prompt here. Thanks for pointing this out!

**Comment by alexr00** [comment]
Looks like this is already fixed in insiders.

**Comment by IanMatthewHuff** [comment]
Looks good. I see the prompt now.
![image](https://user-images.githubusercontent.com/812783/151441875-3a607eea-90b8-4c69-b9ec-2425e197d202.png)
