### ISSUE TITLE
Hint drawing overflow

### ISSUE THREAD

**Issue by Sasha-P** [Microsoft/vscode#13934]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:43:46.054Z)
- OS Version: Linux x64 3.19.0-28-generic

![screenshot from 2016-10-18 14 28 15](https://cloud.githubusercontent.com/assets/3497621/19476352/646d18ca-9541-11e6-8d5c-5e6e81a1e660.png)

**Comment by joaomoreno** [comment]
#13636
