### ISSUE TITLE
Button to toggle Markdown code/preview mode

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#139332]
Now that there's a new "Reopen with" for Markdown that shows the tab in preview mode, it'd be nice to have a button in the corner to quickly do this. There's already a button "Open Preview to the Side." I'm just proposing another button, "Toggle Mode" that toggles between Preview or Edit modes.

**Comment by WebMechanic** [comment]
I second that, however I wouldn't want this to be mutually exclusive and I also **wouldn't want yet another button up** there wasting space and covering open tabs. 

I'd prefer if that would be supported by a modifier key, i.e. "Alt/Opt click" toggle preview, regular click open preview aside. And have a setting that defines which one's  the default behaviour.

There are also several "enhanced" MD previews available, stand-alone or as part of another extension (i.e. dendron). It'd be nice if one could specify which Preview should be the default (per workspace).
