### ISSUE TITLE
Unable to setup vscode locally

### ISSUE THREAD

**Issue by Sujay-shetty** [Microsoft/vscode#13932]
- VSCode Version: *
- OS Version: Windows

Hi,
I'm trying to setup vscode locally in windows 64 bit machine but facing following issue.
I followed the steps in the link https://github.com/Microsoft/vscode/wiki/How-to-Contribute#using-vscode
I can able to install the node modules and also if I run ".\scripts\npm run watch" it is successful without error. When I try to run ".\scripts\code --remote-debugging-port=9222" it is throwing following error.

```
[16:16:12] Using gulpfile E:\Projects\vscode-master\gulpfile.js
[16:16:12] Starting 'clean-electron'...
[16:16:12] Finished 'clean-electron' after 2.64 ms
[16:16:12] Starting 'electron'...
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:586:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
The system cannot find the path specified.
```
@bpasero , @joaomoreno

**Comment by roblourens** [comment]
Does it work if you run without the remote-debugging parameter? That's optional, you can also use the builtin chrome devtools to debug.

**Comment by Sujay-shetty** [comment]
tried without remote-debugging parameter command (.\scripts\code) but still getting the same error as above.

**Comment by roblourens** [comment]
Is there anything weird with your internet connection? A proxy or something? It looks like it's having an issue with downloading electron. You could also try deleting your node_modules folder and running ./scripts/npm install again.

**Comment by Sujay-shetty** [comment]
Setting up behind corporate proxy.
Tried deleting and installing node packages but did not helped.

**Comment by bpasero** [comment]
No clue, never saw this error.

**Comment by roblourens** [comment]
The corporate proxy has got to be the problem. You could check for existing issues at https://github.com/joaomoreno/gulp-atom-electron

**Comment by Sujay-shetty** [comment]
@roblourens
Tried the above process to package electron with gulp but still it cannot able to package.

**Comment by joaomoreno** [comment]
Try `set NODE_TLS_REJECT_UNAUTHORIZED="0"` before running `.\scripts\code`.

**Comment by Sujay-shetty** [comment]
@joaomoreno
No luck still stuck in setup.
It is not able to pull electron from git and build the same in corporate proxy.

**Comment by joaomoreno** [comment]
Create a folder `gulp-electron-cache` in your `%TEMP%`. Place inside [electron](https://github.com/electron/electron/releases/download/v1.3.7/electron-v1.3.7-win32-ia32.zip) and [ffmpeg](https://github.com/electron/electron/releases/download/v1.3.7/ffmpeg-v1.3.7-win32-ia32.zip) and try again.

**Comment by Sujay-shetty** [comment]
@joaomoreno
Above link for electron and ffmpeg are hosted on amazon aws servers which are blocked from corporate proxy :(

**Comment by joaomoreno** [comment]
We can't really fix your network proxy. :(
