### ISSUE TITLE
terminal unusable because of garbled text

### ISSUE THREAD

**Issue by tbela99** [microsoft/vscode#139338]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.63.1
- OS Version: Linux x64 5.10.74.3-microsoft-standard-WSL2

Steps to Reproduce:

1. open the terminal. the font is always garbled, no matter which font you use

this issue also exist in previous versions I have used

system info

```text
Version: 1.63.1
Commit: fe719cd3e5825bf14e14182fddeb88ee8daf044f
Date: 2021-12-14T02:02:02.183Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.10.74.3-microsoft-standard-WSL2
```
list of extensions
```text
| Extension | Author (truncated) | Version |
| ---------- | ------------------ | --------: |
| systemd-unit-file | coo | 1.0.6 |
| xml	| Dot	| 2.5.1 | 
| prettier-vscode | esb	| 9.0.0 | 
| easy-less | mrc	| 1.7.3 | 
| vscode-docker | ms-	| 1.18.0 | 
| remote-containers	| ms- | 0.209.6 | 
```

![image](https://user-images.githubusercontent.com/58517/146467099-36ba686a-5e69-433f-91cb-fb4463f2ad0c.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo
does it happen only with Monaco or other fonts as well? Especially if you comment out both font-family settings.


And do I understand correctly that VSCode is installed directly in WSL2 and not on Windows +Remote-WSL extension?

**Comment by tbela99** [comment]
Yes, and I just changed the font to Monaco to see if it works.

None of the fonts worked. It is in this state for months. I thought an
update will fix it but it didn't

**Comment by meganrogge** [comment]
does changing the `terminal.integrated.gpuAcceleration` help?

**Comment by tbela99** [comment]
disabling it solved the problem

![image](https://user-images.githubusercontent.com/58517/146487506-a108c8ba-0bc6-4f69-ac17-d1fddecf642d.png)

**Comment by tbela99** [comment]
disabling it solved the problem
![image](https://user-images.githubusercontent.com/58517/146487626-cb08bc86-2f5e-4045-9d37-badf3c66e6cf.png)

**Comment by Tyriar** [comment]
> OS Version: Linux x64 5.10.74.3-microsoft-standard-WSL2

I think you're seeing some weird gpu behavior due to WSLg, the workaround here is to disable gpuAcceleration as you've done. AFAIK we can't detect this case reliably, we already fallback gracefully if webgl is not supported but it says it's supported and proceeding to do the wrong thing.
