### ISSUE TITLE
share terminal backend code in the constructor

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#139325]
https://github.com/microsoft/vscode/blob/e42240c92de43ea593548f119dce26a9ff4a9a67/src/vs/platform/terminal/common/terminal.ts#L224-L231

with a shared `refreshEnvironment` (or something) function

https://github.com/microsoft/vscode/blob/e42240c92de43ea593548f119dce26a9ff4a9a67/src/vs/workbench/contrib/terminal/electron-sandbox/localTerminalBackend.ts#L275-L318

**Comment by Tyriar** [comment]
> with a shared refreshEnvironment (or something) function

Just `parseSerializedState` instead since the environment stuff would happen in the server process for remote.
