### ISSUE TITLE
After updating a pre-release extension to a newer pre-release, extension is no longer running as pre-release

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#139334]
Issue Type: <b>Bug</b>

1. Publish an extension.
2. Publish a pre-release with a higher minor version.
3. Switch to using the pre-release.
4. Build a new pre-release with a higher maintenance version.
5. Publish it.
6. In VS Code check for updates. See that a newer pre-release is offered.
![image](https://user-images.githubusercontent.com/6726799/146455655-cd9f474b-ebac-4122-a698-214b273afcfa.png)

7. Install it, then click the Reload button.
8. :bug: after reload you are no longer running the pre-release. You have to opt in to pre-release again.

VS Code version: Code - Insiders 1.64.0-insider (f67a8b753f55e452f38b61497662839c4691fb12, 2021-12-16T05:15:05.411Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by sandy081** [comment]
This seems to happen when auto updates are disabled.

**Comment by JacksonKearl** [comment]
Not sure why author verification bot didn't run here, but @gjsjohnmurray can you verify this?

**Comment by connor4312** [comment]
Verified by disabling updates, downgrading to an older prerelease, then upgrading and ensuring it remained as prerelease.
