### ISSUE TITLE
Support for Python PEP 677 in Python TextMate grammar

### ISSUE THREAD

**Issue by erictraut** [microsoft/vscode#139393]
VS Code includes a TextMate grammar for Python. Draft [PEP 677](https://www.python.org/dev/peps/pep-0677/) introduces a new syntax for annotating callable signatures. This PEP hasn't been ratified, but it's likely to be in the near future. I recently added support for this feature in pyright (and therefore, in pylance as well). The TextMate grammar will need to be updated to accommodate this new syntax. Currently, it causes VS Code to display the `->` token in red.

![0e3f81e5-ff24-4f85-81ca-f1519b11088b](https://user-images.githubusercontent.com/7040122/146594702-529223ac-336d-4e36-ba0a-8ba616aac847.jpg)

**Comment by alexr00** [comment]
Moved to https://github.com/MagicStack/MagicPython/issues/247, which is the repo we get our python grammar from.
