### ISSUE TITLE
A feature for auto updating Vscode

### ISSUE THREAD

**Issue by Hudson-AmalembaL** [microsoft/vscode#139360]
Hello, 
I have a suggestion about how the vscode updates work. 
Rather than each time  there's a new release, you have to go to the browser to download the update, uninstall the one you have and the reinstall the new downloaded version and repeat the same every other time a new version is available. 

If there could be a way, the updates happen in the background right from an opened vscode instance, then after a completed download in the background,  it should uninstall the current version and install the new downloaded and updated version.
Thank you.

**Comment by yume-chan** [comment]
Am I time travelled? What OS and installation method do you use?

**Comment by Hudson-AmalembaL** [comment]
I'm using Zorin, a linux distribution.

**Comment by Hudson-AmalembaL** [comment]
> Am I time travelled? What OS and installation method do you use?

What do you mean by "time travelled"?

**Comment by yume-chan** [comment]
> Zorin OS is a Linux distribution based on Ubuntu desktop linux. 
>
> _[Zorin OS - Wikipedia](https://en.wikipedia.org/wiki/Zorin_OS)_

---

> download the update, uninstall the one you have and the reinstall the new downloaded version

You mean you manually download the `deb` package and install it?

You can install [Code via Snap](https://snapcraft.io/code) which will look for updates automatically every day.

**Comment by yume-chan** [comment]
> What do you mean by "time travelled"?

I mean I don't know Code doesn't have auto updating on every platform.

**Comment by Hudson-AmalembaL** [comment]
> > Zorin OS is a Linux distribution based on Ubuntu desktop linux.
> > _[Zorin OS - Wikipedia](https://en.wikipedia.org/wiki/Zorin_OS)_
> 
> > download the update, uninstall the one you have and the reinstall the new downloaded version
> 
> You mean you manually download the `deb` package and install it?
> 
> You can install [Code via Snap](https://snapcraft.io/code) which will look for updates automatically every day.

Yeah. I've been downloading it every time. I'll check this out though. Thanks.
