### ISSUE TITLE
Update application in user-context when other code.exe is running

### ISSUE THREAD

**Issue by emipa606** [microsoft/vscode#139377]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.1
- OS Version: Windows Server 2016

Steps to Reproduce:

1. Applications needs to be restarted to apply an update
2. Closes the application
3. The update can not continue as there are other code.exe running (but not as my user)

It would be nice if the User-installed version of Code could autoupdate even when other users on the same computer are running their own installations of Code.

![image](https://user-images.githubusercontent.com/6932991/146548104-9d49666f-732d-4a0a-a388-672bf7179fa7.png)

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by emipa606** [comment]
I fail to see how a workaround for a unrelated issue should be a solution for this issue. 
The one you are referring to has the issue that System is locking the code.exe

This issue (that I thought was clearly specified) happens when a user on a server has its own code-installation active and another user tries to update their own. 
It happens even when installing, not just during autoupdate. 

Please open this issue again
