### ISSUE TITLE
Self-Hosted vscode.dev

### ISSUE THREAD

**Issue by Sebi2020** [microsoft/vscode#139335]
It would be nice if people could host the vscode.dev edition locallly. For example through a docker image. This would be especially interesting if you're working in a company, which do not want to expose source files to the internet.

Currently I cannot find any information on how to achieve that, about the technical differences between VSCode Desktop and vscode.dev (same or different source code?) and how to setup a self hosted instance of vscode.dev (if possible at all).

**Comment by IllusionMH** [comment]
Looks like duplicate of #135856

**Comment by Sebi2020** [comment]
> Looks like duplicate of #135856
It is, thank you for pointing this out.

**Comment by janus-reith** [comment]
No, this is actually a duplicate of #135733 which was closed.

**Comment by Sebi2020** [comment]
@janus-reith 
> No, this is actually a duplicate of #135733 which was closed.

Where do you see the difference between #135733 and #135856 ? For me it looks like MS is systematically closing issues requesting open source access to a self runnable web version of vscode.

**Comment by janus-reith** [comment]
@Sebi2020 I described the difference in #135856 - That one, which actually describes a different underlying technical set of features which is already available in other vscode-based solutions(server, GUI in the browser), is kept open for some reason.

As for the last part of what you wrote, unfortunately I have the same impression.
