### ISSUE TITLE
wsl terminal/bash shell - pressing up then down key displays additional character at front of cmd using unicode 

### ISSUE THREAD

**Issue by hkskoglund** [microsoft/vscode#139362]
Issue Type: <b>Bug</b>

I am trying to debug a printf issue with unicode 🌧.

printf "%-7sT" "🌧" | od -A n -t x1
f0 9f 8c a7 20 20 20 54 0a

1. Press up

printf "%-7sT\n" "🌧"| od -A n -t x1 
(space removed before |)

2. Press down
pprintf "%-7sT\n" "🌧"| od -A n -t x1

Additional p displayed, but not actually in the command line buffer, pressing Enter executes the command ok. Repeating steps 1 and 2  multiples times gives 
 
pppppppppppppppppppppprintf "%-7sT\n" "🌧"| od -A n -t x1

I tried to reboot vs code and start a new terminal, but it didnt fix the problem.

Maybe its related to the the readline library in the bash shell used in wsl?

echo $BASH_VERSION
5.0.17(1)-release

I am unable to reproduce the same issue  on fedora 35/bash 5.1.8(1)

[henning@satellite ~]$ printf "%-7s\n" "🌧" | od -A n -t x1
 f0 9f 8c a7 20 20 20 0a
[henning@satellite ~]$ uname -a
Linux satellite 5.14.18-300.fc35.x86_64 #1 SMP Fri Nov 12 16:43:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
[henning@satellite ~]$ echo $BASH_VERSION
5.1.8(1)-release

[https://tiswww.case.edu/php/chet/readline/rltop.html](url)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800U with Radeon Graphics          (16 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.86GB (4.74GB free)|
|Process Argv|--crash-reporter-id a447e73c-2032-4285-aa92-a2c03ddbc8dd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
vscode-eslint|dba|2.2.2
shell-format|fox|7.2.2
vscode-pull-request-github|Git|0.34.1
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5200
vsliveshare-audio|ms-|0.1.91
text-power-tools|qcz|1.30.0
java|red|1.2.0
shellcheck|tim|0.18.2
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.0
vscode-maven|vsc|0.34.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710cf:30405999
vscexrecpromp3t3:30407764

```

</details>

**Comment by Tyriar** [comment]
Initially I thought this was to do with the size we (vscode) thinks the emoji is (1) and the backend (conpty) thinks it's 2, but looking at the sequences we get shows that is false:

```
xterm.js:1 xterm.js: sending data "[A" (3) [27, 91, 65]
xterm.js:1 xterm.js: parsing data [?25l[7;52Hprintf "%-7sT" "🌧" | od -A n -t x1[1C[?25h
```

The `[7;52H` above is positioning the cursor absolutely at the wrong position. So, this is a conpty bug, and it reproduces in Windows Terminals as well:

![image](https://user-images.githubusercontent.com/2193314/146581933-0bbac656-586a-4b52-8786-71e21ec1830e.png)

FYI @zadjii-msft
