### ISSUE TITLE
Total Variants of VS Code

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#13935]
How many variant are available for vscode

I have less information about that and need to know to make my extension supports all variants.

As far i know there is Code , Code-Insiders so i had to manage to get the code settings either from /Code - Insiders'  or  '/Code'.

are there more variants of code ? and whats their extension and config folder structure name

**Comment by roblourens** [comment]
I wouldn't try to get settings from both places. Insiders and Stable can have their own sets of installed extensions. Someone could have different versions of your extension installed in each, with different settings. But those are the only two variants.

**Comment by shanalikhan** [comment]
is there any way that i insert the beta version of my extension only for insiders and let the stable version downloadable to stable version ?

**Comment by roblourens** [comment]
Yes, in package.json you can set

```json
"engines": {
    "vscode": "^1.7.0"
}
```

and it will only be downloadable in 1.7 (which is currently insiders).

**Comment by shanalikhan** [comment]
if i set it to 1.7 , will 1.6 users will be able to see the update ?

I faced recent scenario when i set 1.6 and user with 1.5 see update and try to update it and it doesnt install rather than it removes automatically and installs the older version and keep showing the update

**Comment by roblourens** [comment]
That was a bug in 1.5, but it should be fixed now for later versions.

**Comment by shanalikhan** [comment]
How this case will handled ?
For example i generate 2.0.0 for public release and than i release 2.0.1 for insiders - the public release users wont see any update- than i have to release 2.0.2 to make 2.0.1 that release for public so they get update ? they will jump direct from 2.0.0 to 2.0.2 ?

**Comment by joaomoreno** [comment]
Yes.
