### ISSUE TITLE
"VS Code setting - Search:Max Results" doesn't work

### ISSUE THREAD

**Issue by ShoulderHe** [microsoft/vscode#139345]
When "VS Code setting - Search:Max Results" is set to null (empty),  The max number of search results is not unlimited but 999.
VS Code version:
![image](https://user-images.githubusercontent.com/40564017/146492461-d570a9cf-7fd5-4e20-99ac-2aa423fee324.png)

**Comment by gjsjohnmurray** [comment]
Seems to work for me. This search for 'a' in the VS Code source eventually produced an option to close the app:

![image](https://user-images.githubusercontent.com/6726799/146536587-bf960cb2-a9aa-46b6-906d-f7a6fd91f099.png)

**Comment by ShoulderHe** [comment]
Here are my search results:
![image](https://user-images.githubusercontent.com/40564017/147429244-05aa874f-6c85-4399-b1bf-2695bc10f349.png)
![image](https://user-images.githubusercontent.com/40564017/147429266-10eb073d-1503-4a13-b443-518b56651d5c.png)

**Comment by rzhao271** [comment]
We pass in `undefined` for the `limitResultCount` parameter of `findMatches`:

https://github.com/microsoft/vscode/blob/c8e2fd7baeaa8cd9dc43d3051db66a7428309c97/src/vs/workbench/services/search/common/searchService.ts#L449

But it gets defaulted to 999:

https://github.com/microsoft/vscode/blob/973684056e67153952f495fce93bf50d0ec0b892/src/vs/editor/common/model/textModel.ts#L1169

CC @alexdima

**Comment by roblourens** [comment]
Sorry @rzhao271 dunno if you were working on this already
