### ISSUE TITLE
WSL terminal profiles should be "profiles" (not "detected")

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#139385]
This has been happening for a while now, WSL profiles haven't been showing up in the dropdown despite the useWslProfiles setting being true. But they are being detected, just not promoted to the real profiles section:

![image](https://user-images.githubusercontent.com/2193314/146581042-ff4e26c8-cc99-45f8-bec3-dc5d46e010da.png)

**Comment by meganrogge** [comment]
fixed with https://github.com/microsoft/vscode/commit/2c22ffe6ae0d8d7cf38a511c3375dd68fd151595
s/o to bracketed paste mode on bash for the typo
