### ISSUE TITLE
Github authentication error

### ISSUE THREAD

**Issue by rplotka** [microsoft/vscode#139386]
Issue Type: <b>Bug</b>

I edited my plist file so that I can open folders with VSCode on the mac.  Now when I try to login to github (or Microsoft) I am getting the following error...

Writing login information to the keychain failed with error 'invalid Info.plist (plist or signature have been modified)'.

How may I fix this error?  OR if I need to reinstall, how do I do so and then set the system to allow it to Folders -> Open With -> VS Code?

Thank you so much!

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id c425ebab-471c-4af2-894c-036f2049b874|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.2.3
vscode-intelephense-client|bme|1.8.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.6.0
dart-code|Dar|3.29.0
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
vscode-dash|dee|2.4.0
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
tslint|eg2|1.0.47
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
php-debug|fel|1.22.0
php-pack|fel|1.0.2
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
code-runner|for|0.11.6
docker-explorer|for|0.1.7
vscode-pull-request-github|Git|0.34.1
go|gol|0.30.0
cloudcode|goo|1.17.0
gc-excelviewer|Gra|4.0.45
beautify|Hoo|1.5.0
solidity-debugger|hos|0.2.1
r|Iku|2.3.4
c-cpp-flylint|jbe|1.11.0
solidity|Jua|0.0.136
rainbow-csv|mec|1.10.1
git-graph|mhu|1.30.0
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.18.0
vscode-kubernetes-tools|ms-|1.3.4
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
cpptools|ms-|1.7.1
live-server|ms-|0.2.11
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.5200
sqltools|mtx|0.23.0
material-icon-theme|PKi|4.11.0
heroku-command|pko|0.0.8
vscode-css-peek|pra|4.2.0
typescript-hero|rbb|3.0.0
vscode-yaml|red|1.2.2
r-lsp|REd|0.1.14
bash-debug|rog|0.3.9
django-intellisense|sha|0.0.2
code-settings-sync|Sha|3.4.3
vscode-nginx|sha|0.6.0
open-in-browser|tec|2.0.0
vscode-status-bar-format-toggle|tom|3.0.0
vscodeintellicode|Vis|1.2.15
vscode-icons|vsc|11.8.0
material-theme|zhu|3.13.7
html-css-class-completion|Zig|1.20.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710cf:30405999
vscexrecpromp3c:30407761

```

</details>

**Comment by TylerLeonhardt** [comment]
If you revert that change to the plist, does the error go away? I feel like there must be a better way allow opening folders in VS Code... like whats in this SO article: https://stackoverflow.com/questions/64040393/open-a-folder-in-vscode-through-finder-in-macos

**Comment by rplotka** [comment]
Actually after reboot - VScode would not run, so I reinstalled the app and all was fine, however I still cannot open a folder from the menu on Mac.  Very frustrating, especially since VSCode uses the folders as workspaces (which is great).  I created a workflow as in the above - but that is very Kludgy.  It should defintiely be something that is setup upon install from the app imho.  BBedit, etc do it.  I do not understand why Mac makes this so hard.  You can't even add it as a new 'open with option'. It has to be done upon install it seems
