### ISSUE TITLE
Shell integration: Setup mechanism for listening to shell integration sequences and light up capabilities

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#139396]
Parent issue https://github.com/microsoft/vscode/issues/133084

The shell integration script will emit sequences that we need to handle via an xterm.js sequence handler. We may want to only light up capabilities on the terminal process once we have verified that feature works?

We also need to handle partial capabilities: On Windows may not work 100% since for example it emits the sequences in the renderer, not in the actual order they happened (https://github.com/microsoft/terminal/issues/11220, https://github.com/microsoft/terminal/issues/8698). Should we wait for the sequence to come and if the positioning of the prompt looks off don't turn on a particular capability?

**Comment by meganrogge** [comment]
started on https://github.com/xtermjs/xterm.js/compare/master...meganrogge:shell-integration?expand=1

**Comment by meganrogge** [comment]
done here

https://github.com/microsoft/vscode/blob/9817557314f4aefe7a71a95e80b1b92aec81f37c/src/vs/workbench/contrib/terminal/browser/xterm/shellIntegrationAddon.ts#L86-L87

should this be closed?

**Comment by Tyriar** [comment]
This should be mostly done with https://github.com/microsoft/vscode/pull/140635
