### ISSUE TITLE
PHP syntax highlighting breaks when inserting a hash (#) char in a string

### ISSUE THREAD

**Issue by MioVisman** [microsoft/vscode#139390]
Does this issue occur when all extensions are disabled?: Yes (ms-ceintl.vscode-language-pack-ru - ON)

- VS Code Version: 1.63.2
- OS Version: Windows 7 x64

Steps to Reproduce:

PHP syntax highlighting breaks when inserting a hash (#) char in a string.
![hasherr](https://user-images.githubusercontent.com/5917956/146588919-a707db21-1c63-4597-8fbd-84f495e24190.png)

P.S. At the moment, these are the lines: 
`https://github.com/forkbb/forkbb/blob/master/app/Core/DB/Sqlite.php#L450`
`https://github.com/forkbb/forkbb/blob/master/app/Core/DB/Sqlite.php#L482`

**Comment by roblourens** [comment]
I think this is essentially the same as https://github.com/atom/language-php/issues/327 and https://github.com/atom/language-php/issues/418
