### ISSUE TITLE
live server 

### ISSUE THREAD

**Issue by Zorro58** [microsoft/vscode#139306]
Issue Type: <b>Feature Request</b>

probléme de port réseau

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:54.292Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by IllusionMH** [comment]
/needsMoreInfo

Are you using extension for Live Server? If yes you should report issue against extension.

If it's not about extension you should provide detailed steps on how to reproduce this issue.
