### ISSUE TITLE
Display whether current file is saved or not in zen mode

### ISSUE THREAD

**Issue by AryanBeezadhur** [microsoft/vscode#139303]
When a file is opened in zen mode (<kbd>Ctrl</kbd> + <kbd>K</kbd> <kbd>Z</kbd>), I cannot tell if the file is saved without exiting zen mode. It would be nice if VS Code would tell me whether the file is saved or not with a little dot or asterisk in the top bar when the file is not saved.

**Comment by JacksonKearl** [comment]
The x in top left turns to a dot when the file has edits. You can also unset `zenMode.hideTabs` to maintain the standard tab presentation in zen mode.
![image](https://user-images.githubusercontent.com/8586769/146432451-3995b344-0fa1-4071-88c7-3c76042cf7a9.png)
![image](https://user-images.githubusercontent.com/8586769/146432467-83bcdfa3-4ae1-428f-9a19-150272f41928.png)

**Comment by AryanBeezadhur** [comment]
@JacksonKearl I don't see any <kbd>x</kbd> or dot in the top in zen mode:

![image](https://user-images.githubusercontent.com/34424160/146456862-a557337f-328b-412d-825a-4c4a9a771c36.png)

![image](https://user-images.githubusercontent.com/34424160/146456870-241fe7e6-4baa-4388-87c7-73c0fa89b119.png)

**Comment by JacksonKearl** [comment]
My bad, looks like that icon is only rendered if tabs have been globally disabled.

**Comment by IanMatthewHuff** [comment]
Verified. Looks good to me.
![image](https://user-images.githubusercontent.com/812783/151260413-c72fbacb-11b7-4100-a585-c11fc5b0d0d9.png)
