### ISSUE TITLE
Code is not running properly.

### ISSUE THREAD

**Issue by Vishal973** [microsoft/vscode#139369]
Issue Type: <b>Performance Issue</b>

Code is started to run and it shows "Running", but it doesn't complete. I am facing this problem since today morning. Whenever I try to run code it only shows "Running".
Please help me to run my codes properly.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.73GB (5.82GB free)|
|Process Argv|--crash-reporter-id 6c762e54-8133-4012-846f-6ffd6cc54a7c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    87	 17272	code main
    0	    23	  3940	   utility-network-service
    0	   132	  7636	   window (Visual Studio Code - Visual Studio Code)
    0	   133	 11412	   gpu-process
    0	    13	 14168	   crashpad-handler
    0	    70	 17576	   extensionHost
    0	    29	 11328	     "C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=17576
    1	    54	 18408	   issue-reporter
    2	    83	 20044	   shared-process
    0	    34	 12632	     watcherServiceParcelSharedProcess
    0	    33	 18676	     ptyHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Visual Studio Code - Visual Studio Code)
|    Folder (Visual Studio Code): 57 files
|      File types: c(26) exe(25) json(2) py(1)
|      Conf files: settings.json(2);
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
code-runner|for|0.11.6
better-cpp-syntax|jef|1.15.10
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.0-insiders2
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710cf:30405999
vscexrecpromp3t1:30407762

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled or it depends on extension? Later means that most likely issue should be reported in extension's repo.
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Do you mean run code from "Run and Debug" view or some other way?
Please specify language (probably code sample) and exact steps how do you run code.
