### ISSUE TITLE
overlap on autocomplete

### ISSUE THREAD

**Issue by nicolasvahidzein** [microsoft/vscode#139358]
Hello @bpasero 

I found another bug

I am attaching screenshots.

When i am in the midde of a string of code and i change a portion with an autocomplete suggestion, it erases the portion beyond the . and onto the next part of the valid code.

![001](https://user-images.githubusercontent.com/29876108/146518188-ee939e0b-c5df-414c-a770-d0f5ff1426d6.JPG)
![002](https://user-images.githubusercontent.com/29876108/146518185-ad5c34d7-71a7-43ad-8a6a-0a32a9a063b1.jpg)
![003](https://user-images.githubusercontent.com/29876108/146518182-5c461b2d-78dd-47ca-a08b-ce9ce2cef1f0.JPG)

**Comment by yume-chan** [comment]
Did you set `"editor.suggest.insertMode": "replace"`? I think the suggestion provider gave incorrect text spans to be replaced.

**Comment by nicolasvahidzein** [comment]
Hello @yume-chan,

Nope i have no override setting in my JSON file and the setting in the default preference panel is indeed set to "insert".
