### ISSUE TITLE
Universal macOS Builds Lack Option to "Open using Rosetta"

### ISSUE THREAD

**Issue by ericdrobinson** [microsoft/vscode#139319]
## **Issue Type:** Bug

[Apple's documentation](https://support.apple.com/en-us/HT211861) suggests that:

> For universal apps only, the Info window includes the setting “Open using Rosetta.” This setting enables universal apps such as web browsers or email apps to use plug-ins, extensions, and other add-ons that haven't been updated to support Apple silicon. If a universal app doesn't recognize an add-on that you installed for the app, you can quit the app, select this setting, and try again.

This is exactly the feature I need for my development purposes. Unfortunately, Visual Studio Code's "Get Info" view does not offer this checkbox:

![image](https://user-images.githubusercontent.com/9142587/146430195-818f7036-21f9-4a7b-95c5-9eab4dc15086.png)

As I have a Universal version of VSCode installed, I would expect that this checkbox be available so that I may select to start the application using the architecture I desire.

For the record, I am certain that Rosetta 2 is installed as I have several applications up and running in "Intel" mode. Also, both **Google Chrome** and **Slack** (the latter being an example of a fellow Electron-based application) offer the option to "Open using Rosetta".

## Environment

**VS Code version:** Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
**OS version:** Darwin arm64 21.2.0
**Restricted Mode:** No
**Remote OS version:** Linux arm64 5.10.76-linuxkit
**Remote OS version:** Linux arm64 5.10.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|64.00GB (3.70GB free)|
|Process Argv|--crash-reporter-id f2ed6d4d-a63c-4f7b-b4e4-b849cfa2015e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: panel-frontend|
|OS|Linux arm64 5.10.76-linuxkit|
|CPUs|unknown (4 x 0)|
|Memory (System)|3.84GB (1.13GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: panel-server|
|OS|Linux arm64 5.10.76-linuxkit|
|CPUs|unknown (4 x 0)|
|Memory (System)|3.84GB (1.13GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
extendscript-debug|Ado|2.0.0-beta0.5
githistory|don|0.6.19
vscode-diff|fab|1.4.2
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710cf:30405999
vscexrecpromp3t3:30407764
vscop841cf:30413486
vscop927cf:30413487
vscop436cf:30413488

```

</details>

**Comment by deepak1556** [comment]
> This is exactly the feature I need for my development purposes

Are you referring to testing a vscode extension using native addon built for a particular architecture ? Can the native module not be built for universal instead ?

**Comment by ericdrobinson** [comment]
> Are you referring to testing a vscode extension using native addon built for a particular architecture ?

Yes.

> Can the native module not be built for universal instead ?

No. A framework the extension depends upon does not have a Universal build and there are apparently no plans to update it.

**Comment by ericdrobinson** [comment]
My specific use case doesn't really change the fact that there's something very strange about Visual Studio Code's "Universal" build that for some reason can't be set to "Open using Rosetta"...

**Comment by zhb94430** [comment]
I can confirm the same issue and was able to work around by forcing intel through command line:

arch -x86_64 /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron

**Comment by deepak1556** [comment]
Sorry missed this thread, yes this is because we build our universal application with https://developer.apple.com/documentation/bundleresources/information_property_list/lsrequiresnativeexecution

**Comment by ericdrobinson** [comment]
@deepak1556 Wait, but **_why_** do you build with that key? Is there a specific reason? What do you expect **doesn't** work when you run under Rosetta 2?

**Comment by deepak1556** [comment]
> What do you expect doesn't work when you run under Rosetta 2?

It is the other way, we don't have any component in core that needs the translation so this key is a good way to ensure that we don't use it and also, it gives a clear signal if anything breaks without translation.

**Comment by ericdrobinson** [comment]
> It is the other way, we don't have any component in core that needs the translation so this key is a good way to ensure that we don't use it and also, it gives a clear signal when something breaks without translation.

Wait, what? To my understanding that is exactly the **opposite** of the purpose of that flag. The fact that you don't have any component in core that needs the translation _**isn't the point of the option**_.

The documentation for that option has the following note:

> If your app’s binary supports only the Intel architecture and you link the app against the macOS 11 SDK or later, the inclusion of this key prevents your app from running on Apple silicon.

**That** seems like the point of the flag: do not allow the app to run under translation because _something is known not to work_. The flag is called "LS Requires Native Execution" and yet you have provided no specific reason that VS Code "**requires** native execution"; where VSCode is known to fail under translation.

It should be noted that this does not stop people from running VSCode with translation - it simply makes it much more painful. You either need to run from the [command line](https://github.com/microsoft/vscode/issues/139319#issuecomment-1010458337) or download the [Intel-only build](https://code.visualstudio.com/sha/download?build=stable&os=darwin-intel). With relation to this:

> it gives a clear signal when something breaks without translation.

I would think that your error reports would include the architecture used (Intel/Apple) and the architecture of the OS, which would give you a way to identify an application operating under translation.

# This Affects End Users!

To provide you with a very specific, **user facing** example of why this is harmful, I am working on an update to [an extension on the marketplace](https://marketplace.visualstudio.com/items?itemName=Adobe.extendscript-debug) that contains Intel-only binaries. _Currently_, there is **no way** to get those binaries rebuilt for Apple Silicon. Users of that extension on Apple Silicon devices, then, have to download the **Intel**-specific version of VSCode in order to successfully run that extension. This is an extra step that is **unnecessary** for them and **definitely non-standard in the macOS ecosystem**.

Please re-evaluate your usage of this flag as it appears misused and ends up unnecessarily affecting users in a negative way.

**Comment by Harbs** [comment]
Please enable the flag to let us choose to launch VS Code in Rosetta! An Application such as VS Code absolutely NEEDS an option to be able to be run in Rosetta. Specifically because VS Code is so extendable. It's not reasonable to assume that every extension is going to be ARM native. **Please** reverse the flag!

**Comment by Harbs** [comment]
> It is the other way, we don't have any component in core that needs the translation so this key is a good way to ensure that we don't use it and also, it gives a clear signal when something breaks without translation.

That seems like a reason to build **development** builds with that flag and **maybe** insider builds. That's not a reason to use the flag for **release** builds where it prevents end users from loading it in Rosetta.

**Comment by gilbertconsult** [comment]
Please enable the flag to let us choose to launch VS Code in Rosetta.

**Comment by ericdrobinson** [comment]
@deepak1556 Thank you very much for handling this. Looking forward to downloading the Universal build in the next release!
