### ISSUE TITLE
Please rename the "restart" parts in UI texts to "reload"

### ISSUE THREAD

**Issue by epicbugs** [Microsoft/vscode#13938]
As per #3592 and @bpasero, there currently is no restart command in VS Code that would do the full thing. 

What more, @bpasero argues that "Restart Now" does a window reload as a bug because if you have a second window open, you need to do the same action there too to benefit from the extension. I am not sure if it really is a bug, but nevertheless it would be a lot less confusing if the naming in that case would be more consistent.

Hence the request -- please rename the "Restart" parts in UI texts to "Reload". If no full restart is being done, then it makes no sense to name it as such.

Also, this proposed change would bring about another increase in consistency as there already is a "Reload Window" command which, at least on the surface, appears to do the very thing that is currently being disguised and labeled as a "Restart" in other parts of the UI.

**Comment by bpasero** [comment]
@sandy081 I am fine renaming the action to "Reload" instead of "Restart", though I leave this decision up to you and @joaomoreno. I do not have strong feelings the one or other way.

**Comment by sandy081** [comment]
Got renamed to 'Reload'. Hence closing.
