### ISSUE TITLE
when terminal default location is editor, terminals in the view have their background color set to that of the editor area

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#139389]
something might be wrong with the themes - this is how they looked in the editor area when the terminal target was undefined

![Screen Shot 2021-12-17 at 11 51 47 AM](https://user-images.githubusercontent.com/29464607/146587189-5a6cdab8-da86-43f4-9a09-fb72aff2d13f.png)

**Comment by Tyriar** [comment]
I believe this is fixed now, can't reproduce and the code that handles the the background color looks good:

https://github.com/Microsoft/vscode/blob/6685d794edfaffb3cc2e4cffba4f451c9e1b9635/src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts#L437-L442

Reopen if you still see it.

**Comment by meganrogge** [comment]
<img width="1112" alt="Screen Shot 2022-01-05 at 10 18 11 PM" src="https://user-images.githubusercontent.com/29464607/148327452-91201722-a607-40f1-a9f5-cf3a0b205ae8.png">

**Comment by Tyriar** [comment]
Maybe you should handle this one as I tried a bunch of different things to repro and couldn't.

**Comment by meganrogge** [comment]
`xterm-viewport` has a background-color set but `xterm-screen` does not.
![Screen Shot 2022-01-06 at 11 48 43 AM](https://user-images.githubusercontent.com/29464607/148427477-83598138-9f6c-4237-9ffa-b34d8bdfefd9.png)

Setting the background color of `xterm-screen` to that of `xterm-viewport` doesn't fix it.

**Comment by meganrogge** [comment]
no bug on stable and has the same dom structure/ element.style for each
![Screen Shot 2022-01-06 at 11 59 38 AM](https://user-images.githubusercontent.com/29464607/148428864-ab4073a1-25cb-4e8a-a731-01423ca7c5dd.png)

**Comment by meganrogge** [comment]
the background color of `xterm-viewport` is getting set to that of the editor area
![Screen Shot 2022-01-06 at 12 01 32 PM](https://user-images.githubusercontent.com/29464607/148429162-b7b7c4d5-49fd-42e6-bdaf-d04291e8cfdd.png)

**Comment by meganrogge** [comment]
I have `terminal.integrated.defaultLocation` set to editor. toggling that setting fixes the issue

**Comment by meganrogge** [comment]
not seeing this in oss 🤔

**Comment by Tyriar** [comment]
@meganrogge the background color on `xterm-viewport` should only influence the scroll bar's color on macOS

> not seeing this in oss 🤔

If you toggle off that color and it's the problem then this could be a problem with our custom Electron?

**Comment by meganrogge** [comment]
that color isn't the problem because it happens in stable too
for some reason, it's parent is .editor-instance
![Screen Shot 2022-01-06 at 6 31 29 PM](https://user-images.githubusercontent.com/29464607/148471784-4811c9c3-5a72-4e36-8d7d-cc9c20e51d81.png)

**Comment by meganrogge** [comment]
closing as I can't reproduce in oss 😢

**Comment by meganrogge** [comment]
I am pretty certain this is a symptom of some case when terminal target isn't set so gets set to defaultLocation (inappropriately for a terminal created in the panel) and thus gets editor styling

**Comment by cheymos** [comment]
I had the same problem. 
This setting helped to solve the problem: `"terminal.integrated.gpuAcceleration": "off"`

**Comment by meganrogge** [comment]
@Tyriar I think when this bug hits stable, we will see a bunch of reports because it's pretty ugly. Lmk if you have any thoughts

**Comment by meganrogge** [comment]
can no longer repro
