### ISSUE TITLE
terminal split button in the editor area doesn't work

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#139309]
a new terminal in the editor area isn't opened

**Comment by bpasero** [comment]
This is a consequence of:

https://github.com/microsoft/vscode/blob/6c89a38cfcc8d6ae4b4804302b709f5256e4a02b/src/vs/workbench/contrib/terminal/browser/terminalEditorInput.ts#L59

The `Singleton` capability signals the editor part that it cannot be split. Is that wrong and can the terminal be split in two?

**Comment by meganrogge** [comment]
We never want an exact duplicate of the terminal, so in that sense, it should be a singleton. 

In the panel, splitting is different from creating a new terminal in that it uses the shell type of the parent terminal instead of that of the default profile. I would think this should also be supported in the editor area for consistency. 

It seems we don't do this now though - when I have a terminal editor focused and run the split terminal command, it creates a new one using my default profile.

We should disallow running that command, remove the split button, and remove split from the context menu, or fix this to work as expected

@Tyriar thoughts?

**Comment by Tyriar** [comment]
I think last this was discussed we were going with the same model as how webviews that don't support splitting work which right now just opens a new group to the right. Both feel a little weird but at least it's consistent. I think it's more important for terminal editors to be consistent with webviews than with the panel since the model is a little different in the panel; a terminal editor is closer to a separate terminal _panel_ than a terminal _group_ imo.

**Comment by meganrogge** [comment]
the web view editor, when split, opens a new empty group to the side. is that what we expect? that's what's happening for terminals atm.

**Comment by Tyriar** [comment]
Not really sure what to expect when it's split, but it's as designed right now. Any changes should be applied to webviews too and I think the only options for singleton editors are:

- Open a group to the right (current)
- Move the editor to the right

Up to @bpasero to consider any changes in this area imo

**Comment by Tyriar** [comment]
+ @lramos15

**Comment by meganrogge** [comment]
I get the open a group to the right, but for terminal editors, wish that would mean a new terminal editor instead of an empty group. to me, that feels like a bug, esp because in the panel, split means create a new one to the side.

**Comment by bpasero** [comment]
I see a lot of prior issues on this matter, specifically https://github.com/microsoft/vscode/issues/117541#issuecomment-815142513 that indicates this was brought up and discussed in the UX call. 

Similar: https://github.com/microsoft/vscode/issues/117580, https://github.com/microsoft/vscode/issues/119666, https://github.com/microsoft/vscode/issues/122362

**Comment by bpasero** [comment]
I noticed that it was still possible to create a duplicate of a terminal via drag+drop+copy operation. Opened https://github.com/microsoft/vscode/issues/139356 for that.
