### ISSUE TITLE
Error on service worker extension editor details don't load on vscode server

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#139346]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: from sources

Steps to Reproduce:

1. run server
2. open vscode on browser
3. go to extensions view and click on a extension
4. click con details tab, then changelog, then details again 
5. :bug: extension details doesn't load and this error shows in console

```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Client': Port at index 0 is already neutered.
```

**Comment by jeanp413** [comment]
Created a PR fixing this https://github.com/microsoft/vscode/pull/139347
cc @mjbvz

**Comment by mjbvz** [comment]
Can you share some details about your setup? The current code works for me with both yarn web and on vscode-dev in my testing

**Comment by jeanp413** [comment]
@mjbvz I just tested it on vscode dev insiders and the issue happens

**Comment by jeanp413** [comment]
![webview-port-neutered](https://user-images.githubusercontent.com/25115070/146618611-6d625fcf-d292-4a03-b7a0-e2405458dc98.gif)

**Comment by mjbvz** [comment]
Thanks! I confirmed this happens after visiting the second extension page

The PR should work but I am going to fix this in a different way as I think this identified another bug
