### ISSUE TITLE
Confirmation of Clear Recent projects

### ISSUE THREAD

**Issue by ConduciveMammal** [microsoft/vscode#139392]
Issue Type: <b>Feature Request</b>

Can you please add a confirmation dialog to Clear Recently Opened? I perpetually use this to quickly access all my work projects and clicking this by mistake means I have to re-populate it each time.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Previously requested on #134356 and before than on #125727, but neither received enough upvotes to reach the Backlog.

**Comment by bpasero** [comment]
Pushed confirm dialogs for the following commands:
* Clear Recently Opened
* Clear Editor History
* Clear Commands History

I think this is good practice, given there is no way to undo this operation.

**Comment by amunger** [comment]
whoops, author requested

**Comment by bpasero** [comment]
That is fine, anyone can verify!

**Comment by ConduciveMammal** [comment]
Sorry guys, I'm not on Insiders so can't confirm.

But thanks for knocking this one out! 👍🏻

**Comment by andrewshymanel** [comment]
Is there a setting to disable it and clear recent projects w/o confirmation?
