### ISSUE TITLE
Syntax highlighting for batch is broken.

### ISSUE THREAD

**Issue by TechTony2016** [Microsoft/vscode#1393]
A common way to strip double-quotes from a variable in Windows Batch Language:
set my_var=%my_var:"=%

But, VS code syntax highlighter thinks that the double-quote in the line above is starting a string, and so, it highlights all code in the file beyond that double-quote until it finds another double-quote in the file, as if it were part of a string, which is isn't.

**Comment by aeschli** [comment]
duplicate of #487
