### ISSUE TITLE
Integration test failure: Notebook Editor Active/Visible Editor 

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#139300]
This specific test fails reliably on windows in `electron-16.x.y` branch

Steps to repro:

* From `electron-16.x.y` branch, `./scripts/test-integration.bat`

Refs https://monacotools.visualstudio.com/Monaco/_build/results?buildId=147165&view=results

**Comment by bpasero** [comment]
I can reproduce when I run the tests out of sources on Windows, and what is suspicious is that right before the test fails, a terminal seems to open (labeled `npm`). When I just run the notebook test suite this does not reproduce. I feel that we need to first fix https://github.com/microsoft/vscode/issues/138792 and ensure no external terminal pops up.

**Comment by bpasero** [comment]
![recording](https://user-images.githubusercontent.com/900690/146645412-ac8fa63f-903e-4147-80a1-30162da90d19.gif)

This is probably a consequence of activating the TS/JS extension.
