### ISSUE TITLE
Unit test failure: "TerminalConfigHelper - isMonospace sans-serif"

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#139307]
Please see https://github.com/microsoft/vscode/runs/4550161254?check_suite_focus=true#step:13:9003

```
  7456 passing (2m)
  46 pending
  1 failing

  1) Workbench - TerminalConfigHelper
       TerminalConfigHelper - isMonospace sans-serif:

      Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      + expected - actual
```

**Comment by Tyriar** [comment]
I do not understand this, the test is not async and its `setup` is sync as well in the commit that was built.

**Comment by Tyriar** [comment]
Looks like this failure never happens in ADO, only GH actions.

**Comment by Tyriar** [comment]
Made them retry with a lengthy comment to justify
