### ISSUE TITLE
New quick picks API breaks Java refactoring support

### ISSUE THREAD

**Issue by dmchurch** [microsoft/vscode#139333]
Issue Type: <b>Bug</b>

The implementation of the quickPickSeparators proposal check here:

https://github.com/microsoft/vscode/blob/53f4cbddb72bb519dcb3439f4bcb2c6e5e225bae/src/vs/workbench/api/common/extHost.api.impl.ts#L602

creates a false positive when an extension has _any_ `kind` property on a quick pick item, not just one of the QuickPickItemKind magic values. Given that the `window.showQuickPick` method returns the original object, it's entirely reasonable for an extension to have extra data on it, including (conceivably) a `kind` property.

STR:

1. open a Java source file with inner classes
2. with the cursor on an inner class name, press control-. (command: Quick Fix)
3. choose the first option, "Move 'classname'"
4. observe the error notification that pops up

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (17.26GB free)|
|Process Argv|--crash-reporter-id ac355797-2567-4ffb-9b4c-ea2f04db70d0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (70)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
vscode-sqlite|ale|0.14.0
tsl-problem-matcher|amo|0.5.0
jest-snippets|and|1.8.0
vsc-prolog|art|0.8.23
tcl|bit|0.4.0
sleighighlight|Car|0.0.3
save-editors-layout|ctf|0.2.2
yash|dao|0.2.8
midl-webidl-syntax|dav|0.0.1
mustache|daw|1.1.1
debian-vscode|daw|0.1.2
vscode-eslint|dba|2.2.2
java-decompiler|dgi|0.0.2
remove-multi-cursors|dmc|0.0.1
xml|Dot|2.5.1
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
vscode-jest-runner|fir|0.4.47
vdf|GEE|0.0.7
remotehub|Git|0.20.0
smartmulticursor|ida|0.0.3
latex-workshop|Jam|8.22.0
svg|joc|1.4.14
local-code|loc|0.0.3
smalise|Loy|0.0.12
AWK|lug|0.0.2
autoconf|mae|0.1.0
Lisp|mat|0.1.11
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.17
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
hexeditor|ms-|1.8.2
powershell|ms-|2021.10.2
cordova-tools|msj|2.4.0
debugger-for-chrome|msj|4.13.0
resxpress|Pra|4.3.0
java|red|1.2.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.2
vscode-qt-for-python|sea|1.1.5
vscode-il|sol|0.0.1
functional-cursors|spo|0.0.8
regexworkbench|ste|2.0.5
lua|sum|2.5.3
ninja|sur|0.0.1
rst-vscode|tht|3.0.1
tmlanguage|Tog|0.10.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.19.0
vscode-java-test|vsc|0.33.0
vscode-maven|vsc|0.34.1
wallaby-vscode|Wal|1.0.322
save-and-run|wk-|0.0.22
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30414009
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710cf:30405999
vscexrecpromp3t3:30407764

```

</details>

**Comment by TylerLeonhardt** [comment]
Thanks for this! I have addressed this in:
https://github.com/microsoft/vscode/commit/c02a8deaa11125fcdbcb3031f2b0d0ea17a88090

This does two things:
* Uses a "less likely used by existing extensions" value for `QuickPickItemKind.Separator`: `-1`
* Checks for that value and if that value is seen, then it checks Proposed API

**Comment by TylerLeonhardt** [comment]
verification steps:
* Check that QuickPickItemKind.Separator has the value of `-1` in the latest typings
* Ensure that you, as an extension author, can set kind to a random other value `2`, `'foo'` and you don't get yelled at for proposed API

> NOTE: you may wanna build a VSIX for bullet point 2 to truly verify this

**Comment by dmchurch** [comment]
Thank you so much for the quick response and mitigation! Just out of curiosity, why is the API using integers rather than strings for the `kind` property? Is it for smaller message sizes, or is it an API coding standard, or a protocol limitation, or what? Just wondering what goes into that kind (if you'll forgive the accidental pun) of decision 🙂

**Comment by dmchurch** [comment]
Oh, and, since I didn't see it mentioned over on the vscode-java issue - from the cursory inspection I made, it seems that the `kind` property is on the payload from the Java language server, when the vscode-java extension asks it for refactoring suggestions. The extension just reuses the property (after adding the human-readable label) when it forwards the QuickPick on to VS Code. Just in case you're curious!

**Comment by TylerLeonhardt** [comment]
> why is the API using integers rather than strings for the kind property?

You called it. An API coding standard. If you look at all `kind`s in the vscode API, they all use integer enums:
https://github.com/microsoft/vscode/wiki/Extension-API-guidelines#enums

> When API-work started only numeric-enums were supported, today TypeScript supports string-or-types and string-enums. Because fewer concepts are better, we stick to numeric-enums.

**Comment by dmchurch** [comment]
@TylerLeonhardt It's been over a month since I reported this, can we get a release or a hotfix or something with this fix in it? It ruins my flow when I have to quit VS Code every few days, open an external command line, and re-run it with the `--enable-proposed-api` option, to say nothing of when I switch computers and have to go into the extensions folder to re-edit the package.json.

**Comment by TylerLeonhardt** [comment]
@dmchurch are you running VS Code stable? If you switch over to VS Code Insiders you will be unblocked until our next release (which is in a week and a half)

http://code.visualstudio.com/insiders
