### ISSUE TITLE
WHY prompt EVERYTIME when startup ???

### ISSUE THREAD

**Issue by GQHero** [microsoft/vscode#139320]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

 
![image](https://user-images.githubusercontent.com/4112245/146430510-6855dfde-452d-4602-bcb6-371994fdc3c4.png)

**Comment by joaomoreno** [comment]
Can you repro if you disable all extensions? `--disable-extensions`
