### ISSUE TITLE
Editor becomes unresponsive after hover preview of very large variable

### ISSUE THREAD

**Issue by jhsware** [Microsoft/vscode#13937]
- VSCode Version: 1.5.3
- OS Version: MacOS 10.11.6

Steps to Reproduce:

1. assign a variable a large amount of binary data
2. hover over the variable to get the preview

VS Code gets unresponsive. Eventually it returns back to normal, but it takes a long time.

Would expect VS Code not to show a preview of variables containing a large amount of data.

**Comment by roblourens** [comment]
Is this when debugging Node? That's a known issue. If you are using a newer version of Node (6.3+) you could try using `"type": "node2"`, our new experimental debugger, which can handle large variables better.
