### ISSUE TITLE
Setting editor.autoSurround -> "never" is ignored

### ISSUE THREAD

**Issue by RealVidy** [microsoft/vscode#139382]
Issue Type: <b>Bug</b>

If I select some text and press a bracket key ('[' or ']'), it will surround my selection with brackets instead of overwritting the selection with the bracket I typed.

My settings include:

```
  "editor.autoClosingOvertype": "never",
  "editor.autoSurround": "never",
  "editor.autoClosingBrackets": "never"
```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.01GB free)|
|Process Argv|--crash-reporter-id 3ddfb1a2-3e84-485b-bab1-65e7e3974ca4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (75)</summary>

Extension|Author (truncated)|Version
---|---|---
blocksort|1nV|0.7.2
better-comments|aar|2.1.0
vscode-css-formatter|aes|1.0.2
Bookmarks|ale|13.2.2
tailwind-docs|aus|1.4.0
expect|bda|1.0.1
vscode-intelephense-client|bme|1.8.0
vscode-tailwindcss|bra|0.7.4
pgformatter|bra|1.17.0
better-toml|bun|0.3.2
indented-block-highlighting|byi|1.0.7
flip|Chr|0.0.3
transformer|dak|1.12.0
vscode-faker|dee|1.5.0
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
json-tools|eri|1.0.2
php-debug|fel|1.22.0
vscode-elixir-snippets|flo|0.2.39
todo-tree|Gru|0.0.214
elixirlinter|iam|0.4.1
smarty|imp|0.3.0
elixir-ls|Jak|0.9.0
svg|joc|1.4.14
break-from-comma|jza|1.1.6
vsc-python-indent|Kev|1.14.2
wrapSelection|kon|0.10.0
restructuredtext|lex|167.0.0
bash-ide-vscode|mad|1.11.0
MagicPython|mag|1.1.0
rainbow-csv|mec|1.10.1
vscode-language-babel|mgm|0.0.35
dotenv|mik|1.0.1
vscode-filesize|mkx|3.1.0
vscode-talonscript|mro|0.3.2
language-gettext|mro|0.2.0
vscode-docker|ms-|1.18.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
cpptools|ms-|1.7.1
surface|msa|0.7.0
color-highlight|nau|2.5.0
uuid-generator|net|0.0.4
autodocstring|njp|0.5.4
vetur|oct|0.35.0
erlang|pgo|0.8.2
phoenix|pho|0.1.1
remote-vscode|raf|1.1.0
vscode-sort-json|ric|1.20.0
keep-a-changelog|RLN|1.2.1
color-manager|roy|0.6.3
rust|rus|0.7.8
partial-diff|ryu|1.4.3
elixir-test|sam|1.7.1
swdc-vscode|sof|2.6.19
timestamp-converter|Sta|0.0.1
vscode-eex-snippets|ste|0.0.8
addDocComments|ste|0.0.8
insert-special-symbol|swi|1.3.0
pdf|tom|1.2.0
simple-rst|tro|1.5.1
sensitive-replace|vil|0.1.1
vscodeintellicode|Vis|1.2.15
jinja|who|0.0.8
fig|wit|0.0.4
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2
vscode-eex-beautify|zer|0.2.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30414009
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30405999
vscexrecpromp3t2:30407763

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command to check whether any of your extensions are causing this.

**Comment by RealVidy** [comment]
It was indeed an extension on my end called "wrapSelection" with an undocumented behavior. 
Thanks for letting me know about `Start Extension Bisect`, it's really nice!
