### ISSUE TITLE
Error TS2322 (Union type in function return values) not showing in VS Code

### ISSUE THREAD

**Issue by adripanico** [Microsoft/vscode#13930]
- VSCode Version: 1.6.1
- OS Version: Ubuntu 16.04.1 (Linux 4.4.0-42-generic)

Given the following code snippet:
```
let a: number | Date = 10;
let b: number;
b = a;
```

Running `tsc` will show the corresponding error `error TS2322: Type 'number | Date' is not assignable to type 'number'`, but VS Code is not showing anything at all.

**Comment by roblourens** [comment]
Is your global tsc version the same as the version being used in vscode? You can see the version number in the lower right corner. Do you see other errors?

**Comment by adripanico** [comment]
My bad, you are right.

As soon as both versions match, the error starts appearing. Thanks!
