### ISSUE TITLE
Cmd + Enter sometimes stages all and commit

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#13936]
I've noticed that VSCode sometimes stages all and commit them after pressing CMD + Enter in the git commit message input. It never happens the first time. Though sometimes the 2nd time. But give it enough time it will stage all.

1. Stage some files through the GIT tab.
2. Give a commit message.
3. Press CMD + Enter.
4. Voila VSCode stages all files and commit them.

I've gotten very frustrated sometime when it stages all. When in fact I only want the already staged files to be committed.

**Comment by joaomoreno** [comment]
This should not happen at all.

The behaviour [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/git/browser/gitActions.ts#L896) and [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/git/node/rawGitService.ts#L156) describes the following, when hitting <kbd>Cmd Enter</kbd>:

- If there are any staged changes, only those changes are committed.
- If there are no staged changes, all changes are staged and committed.

Try to get a reproducible case in which there are both staged and unstaged changes and Code commits all in one go.
