### ISSUE TITLE
Notebook API tests onDidChangeCellExecutionState is fired

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139350]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=147260&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=c55167a9-8752-5898-67fa-9d7c918c61b3&l=411

```
 1) Notebook API tests
       onDidChangeCellExecutionState is fired:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\extensions\vscode-api-tests\out\singlefolder-tests\notebook.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

**Comment by bpasero** [comment]
Skipped via https://github.com/microsoft/vscode/commit/ca17de5011403e977648e4527c85724ab31ceb43

**Comment by roblourens** [comment]
Same error as in https://github.com/microsoft/vscode/issues/126371#issuecomment-994185142

If these continue to be an issue we can disable the whole suite
