### ISSUE TITLE
Editor getting stuck during renaming

### ISSUE THREAD

**Issue by appdromeda** [microsoft/vscode#139326]
Issue Type: <b>Bug</b>

It happens when folder you want rename is open in windows explorer. When i closed window VS renamed all files and everything was ok.

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:54.292Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by JacksonKearl** [comment]
![recording (9)](https://user-images.githubusercontent.com/8586769/146465876-561d4064-2189-4897-b4de-a333fb1d0035.gif)
I am not able to reproduce this, can you include a screen recording of what exactly you are doing here?

\gifPlease

**Comment by appdromeda** [comment]
@JacksonKearl You are changing filename not folder. Watch this :)
![recording](https://user-images.githubusercontent.com/34538050/146492157-0df22986-0656-4e33-ab9c-4e2bb08e13b5.gif)

**Comment by JacksonKearl** [comment]
Unfortunately I don't think there's anything we can do about that -- if the OS is locking the file for whatever reason, we can't get around that.
