### ISSUE TITLE
Editor resolver disposes editor to open in some cases

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139355]
The editor resolver itself has logic to close an editor in case it is marked as `singlePerResource` via the `closeExistingEditorsForResource` method. Some editors, like file editor inputs, are shared across all resources. I.e. the same input is used for the same resource across all groups.

When the editor resolver resolves an editor it:
* converts the untyped editor to a typed one
* checks if the same resource is opened in another group
* closes the editor in that case

This will dispose the file editor and then it cannot be opened anymore because the same editor input that is already being used will be used in the resolver too. 

Steps to reproduce:
* set `singlePerResource: true` in [`registerDefaultEditor`](https://github.com/microsoft/vscode/blob/4ed0329e9c5e12e2c7c59697facc96020b0768ab/src/vs/workbench/services/textfile/common/textEditorService.ts#L68)
* open a file
* open an empty group to the side
* focus that empty group
* open quick open
* select the file

=> 🐛 all editors close

I am not sure what should happen here actually, but I believe we would have similar problems if the editor to close is actually dirty and would thus bring up a save dialog. Would a better model be to not close the editor but `move` it to the target group if possible?

**Comment by lramos15** [comment]
Why would an input that is shared across groups be marked as singlePerResource?

**Comment by bpasero** [comment]
I am not sure there is a correlation between setting `singlePerResource` and reusing the same input. I can imagine that we have a few editors where we could have both, e.g. think about the "Running Extensions" editor. That one:
* is single per resource
* could in theory have a single editor input that is always being used when opening, might even be created statically once

Checking what happens when an editor is closed, we do call `dispose`:

https://github.com/microsoft/vscode/blob/e7b3724e0cdc9095d73a06b47203baa2c1777ea8/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L605-L609

I guess my question is rather whether it would be more accurate to move the editor to the target group instead of closing and then opening it?

**Comment by lramos15** [comment]
This makes sense to me from just a performance perspective as well. If you can reuse an editor input then you should and this setting shouldn't restrict that. The only downside I can think of is that you cannot change the editor options when moving but can when you close and reopen just because we have the factories return and `IEditorInputWithOptions`. Hopefully this doesn't produce any new bugs but lets be vigilant of that as maybe we will need to revert as separating the options out would complicate the model

**Comment by bpasero** [comment]
Cool!
