### ISSUE TITLE
whenever Iam trying to change settings in userspace or theme it is giving me error "Can not add index to parent of type array"

### ISSUE THREAD

**Issue by VaibhavGupta0751** [microsoft/vscode#139375]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by VaibhavGupta0751** [comment]
No extension is disabled.

Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you see any errors/warnings if you open `settings.json` (<kbd>F1</kbd> `>Preferences: Open Settings (JSON)`)?

Is it reproducible if you force VS Code to open with specify some other folder with `code --user-data-dir=path/to/dir`?

**Comment by VaibhavGupta0751** [comment]
Let me describe my problem more clearly, this error is showing up with all settings which Iam trying to alter in preference ->settings in user settings.
see in below screenshots
![Screenshot (87)](https://user-images.githubusercontent.com/74704203/146641487-9f8c013d-89ae-4fea-b559-a73444b95148.png)
![Screenshot (88)](https://user-images.githubusercontent.com/74704203/146641497-0ba8b817-5bef-47d9-ba2d-310dce1b0e93.png)

**Comment by IllusionMH** [comment]
Therefore my question was specifically about `settings.json` file. Looks like you have errors in that file and it is impossible to save new values to invalid json

**Comment by VaibhavGupta0751** [comment]
Yes I made some changes in settings.json  in last 3 days which created this problem.

Just few minutes ago I solved this problem by deleting all content of settings.json which now set on default is working fine.
