### ISSUE TITLE
Tab key shifts focus with "Tab Moves Focus" mode turned off and tab keybinding removed

### ISSUE THREAD

**Issue by manuix** [microsoft/vscode#139339]
Issue Type: <b>Bug</b>

1. Remove "Tab" keybinding.
2. Press the Tab key with the focus on a text editor.
3. The focus will go out of the text editor.

Expected:
Nothing.

Results:
The focus is changed away from the text editor.

Comments:
I was able to reproduce this without any extensions and even in a clean install of vscode.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (5.28GB free)|
|Process Argv|--crash-reporter-id e0fff512-bbc7-40fb-8ec4-9b3f79dab239|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.15
vscode-subword-navigation|ow|1.2.0
block-travel|sas|0.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710:30405998
vscexrecpromp3t1:30407762

```

</details>

**Comment by alexdima** [comment]
@manuix This is expected. VS Code has a keyboard dispatching system. When VS Code handles a keydown, then we call `e.preventDefault()` on the keydown event. When preventing default, the browser (Chromium) will not do its default action. For <kbd>Tab</kbd>, the default action is to move focus to next focusable element. This is something that Chromium does by default and does not appear as a rule in our keybindings. If you wish for <kbd>Tab</kbd> to be a no-op, you can use the following in your `keybindings.json` file (`F1 > Preferences: Open Keyboard Shortcuts (JSON)`):
```
{ "key": "tab", "command": "noop" }
```

**Comment by manuix** [comment]
Ok, I tried that and it does in fact stop the tab key from doing it's default behavior. 
With the "noop" command attached to the tab key I see that no other command is executed though, and I was originally trying to have the tab button only trigger the "insertNextSuggestion" command. That's when and saw that with no command attached to the tab key the focus was still being shifted even though the "tab shift focus" mode was deactivated, which looked to me like a bug.

Is there a way to get VS Code to do what I originally wanted?

**Comment by alexdima** [comment]
@manuix Yes, all keybindings can be either removed or shadowed by user keybindings, so 100% customization is achievable. You can read more about the keybinding system [here](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-rules). The following will only keep <kbd>Tab</kbd> triggering the `insertNextSuggestion` command (I took this keybinding from the default keybindings JSON):
```
{ "key": "tab", "command": "noop" },
{ "key": "tab", "command": "insertNextSuggestion", "when": "hasOtherSuggestions && textInputFocus && !inSnippetMode && !suggestWidgetVisible && config.editor.tabCompletion == 'on'" },
```
