### ISSUE TITLE
Show image width and height in preview

### ISSUE THREAD

**Issue by kamil-kielczewski** [microsoft/vscode#139376]
When I click on image in vsc explorer I see the image which is nice - but when I want to use it during CSS creation I also want to know the size of the image. Currently I must open it in other tool to read such basic informations which is quite clumsy

![image](https://user-images.githubusercontent.com/15379981/146552670-f1dbabf2-87d0-4131-b486-3c4af1c0f436.png)

**Comment by mjbvz** [comment]
The image size is shown in the status bar:
![Screen Shot 2021-12-17 at 2 32 53 PM](https://user-images.githubusercontent.com/12821956/146615589-1a109bd1-5a44-4fcc-b6f7-a4486e4fd932.png)
