### ISSUE TITLE
TerminalCommandTracker

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139366]
https://github.com/microsoft/vscode/runs/4558931487?check_suite_focus=true#step:13:9002

```
1) Workbench - TerminalCommandTracker
       Commands
         "before each" hook for "should scroll to the next and previous commands":

      Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      + expected - actual
```

**Comment by bpasero** [comment]
Skipped via https://github.com/microsoft/vscode/commit/ffdd9b85e9ac3ad8d581ab712e0d21ac4ac0ebcd

**Comment by Tyriar** [comment]
I believe it was this specific test, not the suite that was flaky here, it is actually timing out due to container resources in GH actions for the same reasons as https://github.com/microsoft/vscode/issues/138273

**Comment by bpasero** [comment]
Still seeing this in https://github.com/microsoft/vscode/runs/5584050974?check_suite_focus=true#step:14:9369

**Comment by Tyriar** [comment]
Ended up removing the test today
