### ISSUE TITLE
Allow setting explicit title for unsaved files

### ISSUE THREAD

**Issue by Lezzess** [microsoft/vscode#139378]
I know there is a feature for the title of an unsaved tab being set to the first line of its content, but it would be nice to have an opportunity to set an explicit tab title (by double-clicking on the tab title or via the context menu) that will override the implicit one.
Reasons:
- Some of the file formats do not accept comments (e.g. json) and you cannot use them as the title (well, you can but then you have to see that red error highlighting). Also, I am pretty sure some formats require the first line to be some predefined construct, like imports, that is not readable as the title.
- I often use unsaved files as a copy-paste buffer and adding additional custom content to it disables the opportunity to copy everything via Ctrl+A, Ctrl+C. Instead, I have to either remove the first line and copy everything or select everything but the first line.

**Comment by WebMechanic** [comment]
> you cannot use them as the title

i.e. she-bang lines in shell scripts
