### ISSUE TITLE
Terminal duplication on remote host

### ISSUE THREAD

**Issue by darkfessing** [microsoft/vscode#139310]
- VSCode Version: 1.63.0
- Local OS Version: Windows 10 x64
- Remote OS Version: Ubuntu 18.04.5 LTS (or any else)
- Remote Extension/Connection Type: SSH

Problem appered after last update of VS code. Remote Terminals are DUPLICATED. When you open new terminals - old`ones looks exactly like the last one. My colleagues faced similar problem.

Steps to Reproduce:

1.
![2021-12-14_20-35-17](https://user-images.githubusercontent.com/78741712/146052713-aaf155f2-2976-4b8e-b371-13195a8d2193.png)

2.
![2021-12-14_20-35-51](https://user-images.githubusercontent.com/78741712/146052727-9c7cd6ed-94e3-4cd4-87fe-f714924eb1d9.png)

3.
![2021-12-14_20-36-06](https://user-images.githubusercontent.com/78741712/146052744-dbdf91d4-a82f-4925-b462-96c7f3f7747c.png)

4.
![2021-12-14_20-36-21](https://user-images.githubusercontent.com/78741712/146052750-d563a1ec-e3bd-4581-ae55-d54c5a0e714f.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No (only remote Terminals)

**Comment by meganrogge** [comment]
Can reproduce this - does not seem related to remote. Happens after rearranging terminals in the editor area.

**Comment by meganrogge** [comment]
same root cause and /duplicate #139222
