### ISSUE TITLE
error viewer and connection info in Interactive Window stop displaying

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#139330]
Issue Type: <b>Bug</b>

1. Run a cell to open an Interactive Window
2. Run a cell that will throw an error (print(a) where a is not defined)
3. switch which kernel is being used a couple times, run another cell
4. wait for 5-10 minutes
5. run another cell

Actual :
connection information disappears, but still takes up vertical space,
errors disappear and don't take up vertical space

this also repros with --disable-gpu flag

Extension version: 2022.1.1001586661
VS Code version: Code - Insiders 1.64.0-insider (f67a8b753f55e452f38b61497662839c4691fb12, 2021-12-16T05:15:05.411Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.92GB (20.58GB free)|
|Process Argv|--disable-gpu --crash-reporter-id ee1e8284-1ce1-46ae-b666-4982391b0a39|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
vscop804cf:30404767
vs360cf:30404996
vsclayoutctrt:30405800
py55gd98cf:30408622
vscexrecpromp3t2:30407759
azactmsal:30409287
vscop841cf:30413486
vscop927cf:30413487
vscop436cf:30413488

```

</details>

**Comment by rebornix** [comment]
@mjbvz can you help take a look why the modules can be loaded properly?

**Comment by amunger** [comment]
duplicate of #139609. Seems to be fixed with that change
