### ISSUE TITLE
`TextEditor.selections` now read-only

### ISSUE THREAD

**Issue by SNDST00M** [microsoft/vscode#139304]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.0
- OS Version: N/A

Steps to Reproduce:

1. Set up a extension with code like so:
```typescript
import * as vscode from 'vscode';
export function activate(context: vscode.ExtensionContext): void {
    const activeEditor = vscode.window.activeTextEditor;
    const startPosition = new vscode.Position(0, 0);
    const endPosition = new vscode.Position(1, 0);
    activeEditor.selection = activeEditor.selections[0] = new vscode.Selection(startPosition, endPosition);
}
```
2. The console reports that this selection property is readonly as of 1.63

**Comment by JacksonKearl** [comment]
Not sure where you're getting `vscode.window.activeEditor` from. That doesn't exist in the API as far as I'm aware. There's `vscode.window.activeTextEditor`, and the code type checks when I use that instead.

**Comment by SNDST00M** [comment]
Yeah that's the one I believe

**Comment by SNDST00M** [comment]
https://github.com/lramos15/DefinitelyTyped/blob/a4ff899/types/vscode/index.d.ts#L1121

**Comment by JacksonKearl** [comment]
From https://github.com/microsoft/vscode/commit/b911788593205a3aab733df8441dc24c6dd3b323

**Comment by SNDST00M** [comment]
Okay, can we be certain that setting `TextEditor.selection` updates `TextEditor.selections`?

**Comment by JacksonKearl** [comment]
Yes, the implementation is here: https://github.com/microsoft/vscode/blob/7fbe563c0a528e35d19c5cf9562b1bc2a38777d8/src/vs/workbench/api/common/extHostTextEditor.ts#L393-L399

**Comment by SNDST00M** [comment]
Dope, closing

**Comment by SNDST00M** [comment]
Someone on the extension dev Slack: "Assignment to both should work - that's the way to set the editor selection or multiple selections - and types should match this behavior."

**Comment by mjbvz** [comment]
Adding `readonly[]` makes it clearer that you can't update selections by manipulating the array (for example `selections.push()` or  `.selections[1] = ...`) instead you need to update the entire array
