### ISSUE TITLE
Shell integration: Implement enhanced cwd detection and working directory history

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#139407]
Parent issue #133084

Currently cwd tracking is done on macOS and Linux by running lsof or checking procos respectively, these mechanisms can be disabled if we get the cwd from shell integration as it will come in faster and without the need for additional polling. We also want to maintain a list of recent working dirs to support the go to recent directory feature https://github.com/microsoft/vscode/issues/139402 

This new cwd should work for relative links and the `splitCwd` setting.

**Comment by meganrogge** [comment]
this is complete IMO and we should create a new issue for the relative links and `splitCwd` setting

**Comment by Tyriar** [comment]
Let's do this before we close this off:

- [ ] Move to new capabilities system
- [ ] Make sure splitCwd and links use the new cwd is it's available, otherwise the old method
- [ ] Make sure cwd detection works for Windows if shell integration is enabled
- [ ] Update setting docs to call out shell integration
