### ISSUE TITLE
Vscode full CPU running

### ISSUE THREAD

**Issue by SilvaQ** [microsoft/vscode#139497]
typescript tagged bug for   [bug detail](https://github.com/syntax-tree/unist-util-visit/issues/33#issuecomment-997702812)

Excuse me, what is the current solution? I've looked at everything and I still can't find a solution.

I don't have a typescript project right now.
Pure JS projects do import `{visit} from "unist-util-visit"; ` the CPU immediately overloads and vscode doesn't work properly

![image](https://user-images.githubusercontent.com/46706370/146736603-c61006de-2624-41f6-b53c-5fbc2f7942be.png)

**Comment by SilvaQ** [comment]
Is there any progress? The whole business is on the verge of collapse, please tell me how to save this disaster!
@mjbvz

**Comment by SilvaQ** [comment]
I think this could be a temporary solution。
The idea is to solve the problem by switching versions of typescript。
Modify the default typescript mode of vscode as shown in the documentation below：
[using-the-workspace-version-of-typescript](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-the-workspace-version-of-typescript)

steps:
1. open vscode settings.json
2.  add typescript.tsdk filed
3. specify the typescript path you want to use

I installed the specified version of the current project：
```bash
yarn add typescript@4.4.4
```

Modified the vscode configuration file:
```json
       ... other fields here ....
"typescript.tsdk": "./node_modules/typescript/lib"
```
problem off for me now.

**Comment by mjbvz** [comment]
First, does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If it still does, please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Start by sharing the output of `code-insiders --status`
