### ISSUE TITLE
[folding] Highlighting active fold region in the gutter with a colored line

### ISSUE THREAD

**Issue by Ramzy1990** [microsoft/vscode#139425]
Hi,

I would like to request an option to highlight the active fold region (that is, the one with the caret) in the gutter with a colored line. It is also like highlighting the folding region or block in a different color from the main code. Such options are found in other editors (as pointed out previously by users of vscode).

![image](https://user-images.githubusercontent.com/30245545/146630712-c32b0acf-7d1b-45c2-a230-85a8c81b4765.png)

![image](https://user-images.githubusercontent.com/30245545/146630721-94a98f90-0574-4b88-92af-29b1cb9727af.png)

Now I understand there are a lot of previous topics (i.e., duplicates) requesting this same feature since 2016 (see, e.g., #4096, #19690, #25132, #37479, #73800). But they are closed, and I do not see this option added to vscode. I hope such an option is projected to be added because it is quite helpful.

I would also gladly try to add this feature if you can point me towards the place where one should start to adjust the folding behavior.

Thanks,

**Comment by aeschli** [comment]
I've reopened https://github.com/microsoft/vscode/issues/19690 and use that one for the request for folding lines.
I'll add a comment there for the request to highlight the active folding range differently.
