### ISSUE TITLE
WHERE THE FUCK IS PROJECT PROPERTIES!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by CCCCC7** [microsoft/vscode#139460]
I HAVE RIGHT FUCKING CLICKED IN THE EXPLORER ON THE FUCKING FOLDER ON THE FUCKING FILE IN THE FUCKING GOD DAMN SOLUTION EXPLORER I HAVE FUCKINGH DONE IT ALL THERE IS NO FUCKING BUTTON FOR PROPERTIES WHERE THE  FUCCKCDFKCCCKCDSG:LIGJSHNHDS IS ITTTTT!

**Comment by CCCCC7** [comment]
https://i.imgur.com/AqtmPAc.jpeg

**Comment by 4ingers** [comment]
u fool this is vs not vscode😭😭😭😭

**Comment by CCCCC7** [comment]
hahahahhahahha bro, I remember this. It was literally like looking in the fridge for food to not find food for like hours.....back forth back forth......opens vs, finds it np *slaps face, takes long break*
