### ISSUE TITLE
Consider `example.com` as sample domain

### ISSUE THREAD

**Issue by Lemmingh** [microsoft/vscode#139451]
## Problem

Many sample domains in VS Code's source code are **not** controlled by the VS Code team. For instance, in the `vscode.d.ts`,

<https://github.com/microsoft/vscode/blob/d12df34e31b4a018735d312a8947d79331132368/src/vscode-dts/vscode.d.ts#L1257>

```whois
Domain Name: MSFT.COM
Registry Domain ID: 704327_DOMAIN_COM-VRSN
Updated Date: 2021-08-30T17:14:38Z
Creation Date: 1997-10-28T05:00:00Z
Registrar Registration Expiration Date: 2025-10-27T04:00:00Z
Registrar: Network Solutions, LLC
Registrar IANA ID: 2
Registrant Name: NaturalProducts.com
Registrant Organization: NaturalProducts.com
```

[This can harm your reputation.](https://devblogs.microsoft.com/oldnewthing/20040713-00/?p=38463)

Note that the problem also exists in other repos, at least in [`vscode-uri`](https://github.com/microsoft/vscode-uri/blob/dd39d06d80c9f8d4b5ca6ab195219699b417a0b2/src/uri.ts#L117).

## Suggestions

Please switch to the [domains safely reserved by IANA](https://www.iana.org/domains/reserved), such as `example.com`.

**Comment by alexr00** [comment]
Also assigning to @isidorn since this isn't just in vscode.d.ts

**Comment by jrieken** [comment]
wow, I always assumed msft.com is us...

**Comment by alexr00** [comment]
Looks like `msft.com` isn't too pervasive. Outside of vscode.d.ts:

- vscode\src\vs\monaco.d.ts @alexdima 
- vscode\src\vs\base\common\uri.ts @jrieken 
- vscode\src\vs\base\test\common\uri.test.ts @jrieken 
- vscode\src\vs\workbench\contrib\debug\test\browser\debugSource.test.ts @weinand

**Comment by jrieken** [comment]
monaco.d.ts is derived from uri.ts, I will push a commit that removes all msft.com

**Comment by weinand** [comment]
I've fixed the debug tests.
