### ISSUE TITLE
[css] Long decimal alpha overflows color picker header

### ISSUE THREAD

**Issue by patorpey** [microsoft/vscode#139419]
Issue Type: <b>Bug</b>

<b>Steps to Reproduce</b>
1. Open a document with a language or schema that displays color swatches.
2. Enter a color value that would have a repeating decimal for an alpha value in rgba() or hsla() notation. For example, `#0007`.
3. Hover over the color swatch to display the color picker.

<b>Expected Result</b>
The color picker displays the color value in single line.

<b>Actual Result</b>
When the color is formatted as a short hex value in the document, the color picker displays the color in the header in rgba() by default instead of hex. In the case of `#0007`, it is displayed as `rgba(0, 0, 0, 0.4666666666666667)`. The long decimal value causes a line break in the value, which is then clipped by the header box and appears over the "half moon" contrast icon. Cycling through the color formats, the alpha value will then be truncated to three decimal places, causing the header to render as expected.

![color_picker_decimal_alpha](https://user-images.githubusercontent.com/11205356/146625107-81810642-966a-413d-98dd-43847fc99a46.JPG)

The header would need to be able to display the short hex initially or truncate the decimal value when the picker is first displayed.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

**Comment by rebornix** [comment]
The presentation is from the CSS extension.

@aeschli Chrome Dev Tools formats it to `0.467`.

**Comment by aiday-mar** [comment]
Hi @patorpey with the recent work done on the color picker, now the text renders on one line and if there is overflow, it is hidden. This issue will be closed.

![Uploading Screenshot 2023-12-05 at 13.00.25.png…]()
