### ISSUE TITLE
Replace toasts with a dedicated notification window.

### ISSUE THREAD

**Issue by warriorstar-orion** [microsoft/vscode#139440]
The ability to display toasts in VSCode is abused by VSCode itself and every extension. It is not uncommon for me to launch VSCode and see a half dozen toasts displayed. They show up at launch, they show up if an error occurs within an extension, they show up if VSCode tries to be helpful and recommend extensions, they show up if VSCode wants me to update itself. They are fundamentally obnoxious and I want all of them to go away forever.

Instead of allowing every extension author and VSCode feature to distract programmers with an animated user interface feature that can, at worst, take up 30% of the entire window, please create a dedicated pane where all notifications are redirected, and which does not interrupt the user, obscure the editing windows or rest of the interface, and to which a user can navigate to when they decide to take action on them.

To be clear, so this feature request does not get closed incorrectly, *this is not an extension-specific feature request*. I am not asking for extension authors to provide configuration settings to disable *their* toasts. I am asking for a core VSCode feature to disable all of them, forever, permanently, with no hope of ever showing up again, ever again, forever. I literally never want to see another toast in VSCode for as long as I live.

**Comment by perigoso** [comment]
I made a patch that disables all pop ups in the workbench CSS, because MS doesnt care, and the pop ups were p*ssing me off
it's for archlinux, but the patch can probably be used anywhere its just a regex
https://aur.archlinux.org/packages/code-hide-notifications/

**Comment by warriorstar-orion** [comment]
Well, the toasts have, nominally, useful information in them. Which is why this is a feature request: the information should be somewhere, dedicated, just like the countless other panels—Debug, Output, Problems, Console, et cetera—something which emphasizes the user's choice as to when to look at and act on the issues.

Right now the user has no choice, and a CSS workaround to hide them only hides the problem.

**Comment by perigoso** [comment]
Its actually a pretty good fix, you can click the bell icon and they are all still there, they just don't pop up, which they shouldn't to begin with imho
I only posted this here because i know for a fact this feature wont be implemented, like every other request related to this
![image](https://user-images.githubusercontent.com/39195157/146966956-865eb71d-c02f-404b-84d5-84260383c76e.png)

**Comment by warriorstar-orion** [comment]
In two years of using VSCode I've never even seen that interface before, which only reinforces that notifications should follow the same UI principles as everything else. If notifications are important enough to interrupt the user's workflow, they're important enough to have a dedicated panel.
