### ISSUE TITLE
My Intellisene stopped working unexpectedly. I've been trying to solve this for 6hrs and still I was unable to. This happened while working on my Nextjs project. It's not showing auto complete anymore. 

### ISSUE THREAD

**Issue by Tosinkoa** [microsoft/vscode#139447]

**Comment by gjsjohnmurray** [comment]
Does the `Start Extension Bisect` command identify a cause?

If not, please provide more information.

/needsMoreInfo

**Comment by Tosinkoa** [comment]
I use the extension bisect but the extensions were not the causes of the problem

**Comment by Tosinkoa** [comment]
When I cleanup my JSON settings to see if that could solve the problem, its showing a little 'abc'  in front of suggested word (auto complete) word. Anything I can do from here?

**Comment by mjbvz** [comment]
There is not enough information in this issue to know what the issue is or how we can investigate it

If you are still seeing it, please follow the linked issue reporting guidelines. Be sure to include a sample project and steps to reproduce the problem
