### ISSUE TITLE
Task arguments not clearly documented

### ISSUE THREAD

**Issue by KokoDoko** [Microsoft/vscode#13941]
Usage of arguments in tasks.json is not clearly documented. In the following example the same arguments are used in a terminal and in tasks.json. The latter is not working.

- VSCode Version: latest
- OS Version: mac os x

Steps to Reproduce:

1.  first try the following node-sass command directly in the terminal and see that it runs
`node-sass --output-style compressed resources/assets/sass/materialize.scss public/css/hr-materialize.css`

2. then create a vs code task with the same arguments and see it crash and burn
```
{
    "version": "0.1.0",
    "command": "node-sass",
    "isShellCommand": true,
    "args": ["--output-style compressed", "resources/assets/sass/materialize.scss", "public/css/hr-materialize.css"]
}
```

**Comment by roblourens** [comment]
You need to split output-style and its parameter into two array items, like `"args": ["--output-style", "compressed", ... `. Otherwise, it's read as `node-sass '--output-style compressed'`- one argument with an escaped space.

**Comment by roblourens** [comment]
I think this is the same way childProcess.spawn's args works, which is basically what it's doing.
