### ISSUE TITLE
加载 Web 视图时出错: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

### ISSUE THREAD

**Issue by airflycode** [microsoft/vscode#139481]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.63
- OS Version:win10 professional

Steps to Reproduce:

1.加载 Web 视图时出错: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
2.
![image](https://user-images.githubusercontent.com/71859391/146698091-bec2eaeb-cdbf-4d4f-a85d-b973385dd6fb.png)

**Comment by SINC-G** [comment]
可以参考[这里](https://stackoverflow.com/questions/67698176/error-loading-webview-error-could-not-register-service-workers-typeerror-fai)解决这个问题

**Comment by airflycode** [comment]
thanks SINC-G，I have solved this problem currently, I don't know whether it will occur in future.
