### ISSUE TITLE
No option to upload or check

### ISSUE THREAD

**Issue by nkuck** [microsoft/vscode#139478]
Issue Type: <b>Performance Issue</b>

Not sure if anything different than my running in the past. Been working on issues for new FW for a 3D printer. After loading a particular file, I no longer have the options along the bottom bar to load the file.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 6b225f4b-b891-4c11-b761-0f9174df73a0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   24	   180	 48253	code main
    0	    49	 48256	   gpu-process
    0	    33	 48258	   utility-network-service
    0	   377	 48260	   window (Configuration.h — Marlin-2.0-3.x)
    0	   262	 48276	   extensionHost
    0	    82	 48300	     /Users/noelkuck1/.vscode/extensions/ms-vscode.cpptools-1.7.1/bin/cpptools
    0	   115	 48347	       /Users/noelkuck1/.vscode/extensions/ms-vscode.cpptools-1.7.1/bin/cpptools-srv 48300 {42547AC3-5953-481C-9B19-12FF64AAF830}
    3	   180	 48277	   shared-process
    0	    49	 48278	     ptyHost
    0	    16	 48328	       /Users/noelkuck1/opt/miniconda3/bin/python3 /Users/noelkuck1/.vscode/extensions/chriswood.pico-go-1.4.3/terminalExec.py 2087
    0	    49	 48290	     watcherServiceParcelSharedProcess
    0	     0	 48366	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    4	    82	 48361	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Configuration.h — Marlin-2.0-3.x)
|    Folder (Marlin-2.0-3.x): 2770 files
|      File types: h(1254) cpp(793) ld(55) py(50) c(38) bmp(32) json(20)
|                  md(19) png(16) ini(16)
|      Conf files: github-actions(7) makefile(3) dockerfile(2) dropbox(1);
```

</details>
<details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-gcode-syntax|app|0.7.0
code-gnu-global|aus|0.2.2
vscode-django|bat|1.8.0
pico-go|Chr|1.4.3
doxdocgen|csc|1.3.2
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
gitlens|eam|11.7.0
vscode-pull-request-github|Git|0.34.1
better-cpp-syntax|jef|1.15.10
svn-scm|joh|2.15.2
vsc-python-indent|Kev|1.14.2
MagicPython|mag|1.1.0
auto-build|mar|2.1.35
vscode-docker|ms-|1.18.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5200
vsliveshare-audio|ms-|0.1.91
autodocstring|njp|0.5.4
platformio-ide|pla|2.4.0
python|tht|0.2.3
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.15
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30405999
vscexrecpromp3t3:30407764

```

</details>

**Comment by gjsjohnmurray** [comment]
Sounds like features added to the status bar by one or more of your installed extensions are no longer working.

Perhaps use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by nkuck** [comment]
Thanks, will have a look. I subsequently loaded another file and got it back.

NOEL KUCK

Live simply!

**Comment by nkuck** [comment]
> > Also, running the Start Extension Bisect command resulted in several messages about a certain number of extensions deleted, etc, but nothing seemed to change.

NOEL KUCK

Live simply!

**Comment by nkuck** [comment]
If you can possibly help me, I have disabled and re-enabled a number of extensions to no avail. Attached is a screen shot of what I am seeing/not seeing at the bottom of my screen. Thanks for your review and suggestions.

NOEL KUCK

Live simply!

**Comment by gjsjohnmurray** [comment]
Screenshots cannot be received into GitHub by email. You need to use the web interface, which is accessible from a link at the bottom of issue emails from GH.

**Comment by nkuck** [comment]
[
![4C62FDE7-FCE1-41A5-8ED5-827908C3BC7B](https://user-images.githubusercontent.com/10149362/146815244-6219961b-7464-4d50-93a1-7e244aa74fa8.png)
](url)

**Comment by nkuck** [comment]
Here is the screenshot

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Please contact the extension author for help.

**Comment by nkuck** [comment]
Sorry, but I don’t have the knowledge to follow through with your comment. How do I determine the extension culprit, just turn all extensions off and re-enable one by one?

NOEL KUCK

Live simply!

**Comment by gjsjohnmurray** [comment]
Which extension should be providing the status bar panel(s) that you no longer have?

Disable all other extensions, then restart VS Code. If the status bar panel(s) are still missing, contact the extension author for help,

**Comment by nkuck** [comment]
Thanks, will try to nose around.
