### ISSUE TITLE
A restored HTML tag (by undo) unnecessarily triggers auto close

### ISSUE THREAD

**Issue by cimpok** [microsoft/vscode#139467]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows  10  19044.1415

Steps to Reproduce:

1.    Make sure your're editing HTML with the auto close HTML tags feature on
2.    Delete a HTML tag by any method
3.    Undo the delete operation by CTRL-Z

You can observe the unnecessary extra closing tag entered after the undo operation which is surely not the intended result by the user.
My opinion is that any undo operation should exactly restore the previous state and avoid any side effects during this, in this case the auto close feature should be suppressed in the context of undo.

**Comment by aeschli** [comment]
There was a fix for this a while back. I tries a simple delete with the keyboard and it seems to work.
![recording (5)](https://user-images.githubusercontent.com/6461412/147831880-5d97ef50-759e-4369-ab1f-942d913419ed.gif)

Can you provide the exact steps and code sample? 
Make sure that you are in a HTML editor, are using the built-in auto close, and not the [Auto Close Extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag).

**Comment by cimpok** [comment]
I am sorry, the error only occurs when I am editing the html section of .vue files, with plain .html files it works ok. 
The bug is present with both extensions I tried for Vue: 'vetur' and 'volar'. This made me think that this auto-close functionality is using rather the built-in VS Code core somehow and is not rewritten in these extensions.
Sorry for the false alarm, and thank you for taking the time to look into it, I will address this issue to the above extensions' authors. I think you can close this issue here.

**Comment by aeschli** [comment]
Thanks @cimpok. If you can file an issue against vetur that would be great. They need to check for undo and redo as [done here](https://github.com/microsoft/vscode/blob/99305570d885bce929ba8f24d90f2c3ee54c5c2f/extensions/html-language-features/client/src/autoInsertion.ts#L46)
