### ISSUE TITLE
Move Cursor in Terminal with just a click

### ISSUE THREAD

**Issue by ParadaCarleton** [microsoft/vscode#139422]
I'd like to be able to use left-click in the terminal instead of having to do alt-click.

**Comment by meganrogge** [comment]
what are you trying to do that requires alt clicking?

**Comment by ParadaCarleton** [comment]
> what are you trying to do that requires alt clicking?

Trying to move the cursor in the VSCode terminal.

**Comment by Tyriar** [comment]
We definitely wouldn't change the default left click binding, but in the future you might be able to configure this yourself after https://github.com/microsoft/vscode/issues/3130 lands
