### ISSUE TITLE
Git - Unable to sync repository that was cloned empty

### ISSUE THREAD

**Issue by prryplatypus** [microsoft/vscode#139415]
Issue Type: <b>Bug</b>

**Steps to repro**
1. Create and clone an empty repository
2. Open its folder with VS Code
3. Create some files, add them and commit them

**Expected**
The settings button shows there's one commit to be pushed, and clicking it pushes the changes to remote.

**Actual**
The settings button doesn't display any pending commits to be pushed and you have to push manually from a console via `git push`.

VS Code version: Code - Insiders 1.64.0-insider (065b450db9f555f177161748e8f2911ebb5677f9, 2021-12-10T05:14:44.789Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 3900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (19.20GB free)|
|Process Argv|--crash-reporter-id b33d094e-4dc2-4789-85b6-6a67d398b837|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.0
copilot|Git|1.7.4406
discord-vscode|icr|5.7.0
python|ms-|2022.0.1589021501-dev
vscode-pylance|ms-|2021.12.3-pre.1
jupyter|ms-|2022.1.1001591438
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
hide-gitignored|npx|1.1.0
material-icon-theme|PKi|4.11.0
quicktype|qui|12.0.46
highlight-matching-tag|vin|0.10.1
vscodeintellicode|Vis|1.2.15

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593:30376534
vsc1dst:30396469
pythonvs932:30404738
vscop804:30404766
vscop453:30404998
vsclayoutctrt:30405800
py55gd98:30408621
vscexrecpromp3c:30407757
azactmsal:30409287

```

</details>

**Comment by prryplatypus** [comment]
Simply clone an empty repo, create a new file and commit it using VSCode. After committing no option to "push" shows up (possibly because no remote branch is set, even though VSCode does say it's on "main"?).

![uIkScalSYq](https://user-images.githubusercontent.com/25409753/148104538-bc3e16f6-7816-42ef-9422-6b96da58c4f8.gif)

**Comment by lszomoru** [comment]
Thanks @prryplatypus. For some reason the top of the screen in the recording is cut. Can you please try re-upload? Thanks!

**Comment by prryplatypus** [comment]
Updated my initial message with a full-screen GIF @lszomoru. Cheers!

**Comment by lszomoru** [comment]
Closing as duplicate of [#100725](https://github.com/microsoft/vscode/issues/100725)
