### ISSUE TITLE
The incorrect line number always be given for the search result in a folder on Visual Studio Code for Mac

### ISSUE THREAD

**Issue by lingyphone** [microsoft/vscode#139426]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
Version: 1.63.1 (Universal)
Commit: fe719cd3e5825bf14e14182fddeb88ee8daf044f
Date: 2021-12-14T02:13:13.580Z (1 day ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

- OS Version: MacOS Big Sur 11.6.1 (20G224)

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/70597724/146631476-7d535497-e7bb-414b-9cbd-811d3b5b05e6.png)

2.

**Comment by roblourens** [comment]
Is it possible that the file has some line endings that are lone CR characters, not CRLF or LF? Can you share the file?

**Comment by lingyphone** [comment]
Actually the lines ending by <CF><CF><LF> caused the mistake for mismatched search and editor 

In NotePad++ on windows
<img width="747" alt="image" src="https://user-images.githubusercontent.com/70597724/150044870-1a009bac-2919-48b9-ad65-094ed36326cb.png">

In TextMate++ on Mac
<img width="747" alt="image" src="https://user-images.githubusercontent.com/70597724/150045106-74ccda38-cf4f-45e9-8a13-194d8d993255.png">

In VSCode on Mac
<img width="747" alt="image" src="https://user-images.githubusercontent.com/70597724/150045193-fe6b4e22-d84f-4b4a-859f-958b25e03aaf.png">

The actual lines as below
```

function FindProxyForURL(url, host) {
    /* Define Private IP ranges */
    var privateIP = /^(0|10|127|192\.168|172\.1[6789]|172\.2[0-9]|172\.3[01]|169\.254|192\.88\.99)\.[0-9.]+$/;
    
    /* Find current local IP */
    var resolved_ip = dnsResolve(host);
    
    /* Find forwarding IP */

```

**Comment by roblourens** [comment]
Yes, bare CR characters like that cause issues.

https://github.com/microsoft/vscode/issues/35797
https://github.com/microsoft/vscode/issues/48063
