### ISSUE TITLE
Provide 'files.endWithNewline'

### ISSUE THREAD

**Issue by epicbugs** [Microsoft/vscode#13942]
This issue appears on VS Code `v1.6.1` and Windows 10 Professional `v1607`.

VS Code is running with `--disable-extensions`, in user settings `html.format.endWithNewline` and `html.format.preserveNewLines` are both set to `true`, yet not only is VS Code failing to generate ending newlines when I invoke "Format Code", the existing ending newlines are being actively purged.

Workspace settings are basically empty, nor are there any other formatting configurations present such as `.editorconfig` etc, user settings file is as follows:

```
{
    "files.eol": "\n",
    "files.autoSave": "onFocusChange",
    "editor.tabSize": 4,
    "editor.formatOnSave": false,
    "editor.trimAutoWhitespace": false,
    "files.trimTrailingWhitespace": false,
    "html.format.endWithNewline": true,
    "html.format.preserveNewLines": true
}
```

Yet, the ending newlines are being trimmed on format everywhere except for `.html` files.

**Comment by roblourens** [comment]
The 'html' settings will only apply to .html files. But I'm not sure whether ending newlines should be trimmed with those settings.

**Comment by epicbugs** [comment]
> The 'html' settings will only apply to .html files.  But I'm not sure whether ending newlines should be trimmed with those settings.

Yeah, neither am I but this is what VS Code `v1.6.1` appears to be doing. Have you guys managed to reproduce it?

**Comment by khyamay** [comment]
having similar issue where the whitespace are being trimmed when saving even with the     ```"files.trimTrailingWhitespace": false,```
using VS Code v1.6.1 as well and i am quite sure I didn't had this issue before.

**Comment by epicbugs** [comment]
> The 'html' settings will only apply to .html files. But I'm not sure whether ending newlines should be trimmed with those settings.

For some reason, the trimming behavior happens only for `.json` files.

**Comment by aeschli** [comment]
The `"html.format.endWithNewline": true` is used only by the HTML formatter and is about the new line at the end of the document.

Can you append a small html example and explain what you see and what you expect?

**Comment by epicbugs** [comment]
> The "html.format.endWithNewline": true is used only by the HTML formatter and is about the new line at the end of the document.
> Can you append a small html example and explain what you see and what you expect?

Yes, but I want a single and consistent last newline setting **for all file types**. With `.html` files it already seems to work, but I don't understand why should it be related to the file type. As a developer I just want the setting to work with all files as soon as its turned on.

`editor.trimAutoWhitespace` is already there, so why not add **`editor.endWithNewline`** also?

**Comment by aeschli** [comment]
Ok, then I'm renaming this issue to a feature request for a setting like `files.endWithNewline`.
That then would be only used on save.
But note that formatters, which can be contributed as extensions, have each their own set of settings. This is to make it easy to integrate existing formatters such as beautifyjs.

**Comment by bpasero** [comment]
-> https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

**Comment by bpasero** [comment]
Actually, no this is a duplicate of https://github.com/Microsoft/vscode/issues/1666
