### ISSUE TITLE
my vscode rebooted for new vision,but it needs a new reboot to update after i just updated it,it confused me.

### ISSUE THREAD

**Issue by airflycode** [microsoft/vscode#139450]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.63
- OS Version: Windows 10 professional 

Steps to Reproduce:

# 1.
![image](https://user-images.githubusercontent.com/71859391/146661832-467f87a6-6fbe-4086-8c10-a3b061fe7278.png)

# 2. i have rebooted my vscode from time to time these days, it makes me breakdown.
# 3. And my jupyter in vscode can't height the grammers, the right bottom of the Cell says "CVE", though I selected “python”
![image](https://user-images.githubusercontent.com/71859391/146661945-5a6b7bca-c1c7-4f42-b163-15661715c5c9.png)
# 4. I hope these issues can be worked out ,thanks!!!!
some details is located in #139518
my jupyter notebook has this but not python foe the current cell

![image](https://user-images.githubusercontent.com/71859391/146763445-b966452b-b9db-48c6-8b73-69f7b889c071.png)

**Comment by rebornix** [comment]
@airflycode can you share the notebook you use to help us troubleshoot?

**Comment by dacort** [comment]
I'm also experiencing a similar issue where I select Python as the language, but CVE ends up getting selected instead. 

This happens on a brand new document regardless of whether I select Python in the bottom right or the "Select a language" prompt. I'm going to try restarting to see if it helps.

My version info:

```
Version: 1.64.0
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:20:17.224Z (2 wks ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

**Comment by rebornix** [comment]
It's weird that we picked language cve other than python. I guess it's because that we didn't save language if a notebook has no picked kernel.

**Comment by dacort** [comment]
@rebornix I see this is now closed as a duplicate. Do you know which issue it's a duplicate of? 

Of note, I realize now this is happening on one computer and not the other. :\  After doing an "extension bisect" it seems this is due to the Red Hat Dependency Analytics extension and I filed an issue there: https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/567
