### ISSUE TITLE
How to uninstall VSCode installed by @vscode/test-electron

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#139468]
![image](https://user-images.githubusercontent.com/41773861/146670509-a217851d-c343-4fb6-b460-9b39854715c2.png)

@connor4312

**Comment by connor4312** [comment]
@bpasero is there a way to ask VS Code not to register file associations when it starts up?

**Comment by bpasero** [comment]
I am not aware. I think this is managed by macOS via the `Info.plist` we provide. Maybe @deepak1556 or @joaomoreno know more about it.

**Comment by tjx666** [comment]
@connor4312 @bpasero
