### ISSUE TITLE
VSCode live sharing doesn't connect reliably

### ISSUE THREAD

**Issue by dabrahams** [microsoft/vscode#139414]
Issue Type: <b>Bug</b>

Be my boss.  Try to connect to my live share session.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:38:17.605Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|64.00GB (35.33GB free)|
|Process Argv|--crash-reporter-id cb52c330-136e-4b7c-b471-bbd53ecb81e0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.7.0
vscode-clangd|llv|0.1.13
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
vsliveshare|ms-|1.0.5200
vscode-swift-development-environment|vkn|2.12.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710:30405998
py55gd98:30411514
vscexrecpromp3t3:30407764

```

</details>

**Comment by rzhao271** [comment]
For Live Share issues, you can file them at https://github.com/MicrosoftDocs/live-share/issues.
