### ISSUE TITLE
Shell integration: Create "Terminal: Go to Recent Directory" command

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#139402]
Parent issue https://github.com/microsoft/vscode/issues/133084

Blocked on:

- https://github.com/microsoft/vscode/issues/139407

Notes:

- This will present a quick pick of all recent terminal directories
- This should share code with the command history command as both will present a list and send text to the shell
- Should have smoke tests
- Considerations:
  - Do we have a maximum of entries we track?
  - Should this be sorted by recency of frequency?
  - Can we avoid settings for this feature?

**Comment by Tyriar** [comment]
We also want to check to see if there is currently a command being input and send ctrl+c if so (`Terminate batch job` might cause problems on Windows)

**Comment by Tyriar** [comment]
Something else to think about, pretty sure we want to persist this information, but should it be persisted globally or per workspace?

**Comment by meganrogge** [comment]
same question - should this be per terminal instance? it is right now

**Comment by Tyriar** [comment]
- We should not sync this
- Should this be per terminal instance? No
- We should persist similar to recent commands as well
- Should persisted entries work across different shells? Probably
- We should invalidate entries similar to commands
- Let's support removing entries, using a `x` icon that shows only on active and hovered item
- Let's not use the x for failed, we can improve visualizing errors later on
