### ISSUE TITLE
commandsToSkipShell not working for some commands with WSL2

### ISSUE THREAD

**Issue by Apreche** [microsoft/vscode#139479]
Issue Type: <b>Bug</b>

1. `workbench.action.togglePanel` is part of `commandsToSkipShell` by default, and is bound to `ctrl + j`.
2. Open a WSL bash terminal in the panel.
3. Focus on the WSL terminal.
4. Press `ctrl + j`.
5. The expectation is that this shortcut will skip the shell and be recognized by vscode and toggle the panel. It does not close. The `ctrl + j` is sent to the shell.
6. This still happens even if `workbench.action.togglePanel` is added to the setting manually.

Similarly,
1. `workbench.action.toggleSidebarVisibility` (`ctrl+b`) is not part of `commandsToSkipShell` by default.
2. Add it to `commandsToSkipShell` manually.
3. Focus on the WSL terminal panel
4. Press `ctrl + b`
5. Expectation is the sidebar will toggle. It does not. The shell is not skipped.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.73GB free)|
|Process Argv|--crash-reporter-id 4174560b-27b8-4da6-b6db-f7c4310938c1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3695)|
|Memory (System)|15.60GB (12.98GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remotehub|Git|0.20.0
remote-containers|ms-|0.209.6
remote-wsl|ms-|0.63.13
vim|vsc|1.21.10
vscode-pull-request-github|Git|0.34.1
vscode-docker|ms-|1.18.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2

</details>

**Comment by Tyriar** [comment]
I can't reproduce, could you try on the latest insiders version?

**Comment by Apreche** [comment]
I tried with insiders build and it still doesn't work. I can make a screen capture video for you if that will be helpful.

**Comment by Tyriar** [comment]
Hmm, could you share your keybindings.json, settings.json and also do a screen cap after doing the following:

- Setting log level to verbose (via command palette)
- Enabling escape sequence logging (via command palette), this should open the devtools console automatically to show the logs

**Comment by Apreche** [comment]
When I took a look at my settings to paste them here I noticed the problem. I had "terminal.integrated.sendKeybindingsToShell" set to true. So yeah, sorry. No bug here. 

I was under the impression that setting that to true would send all keybindings to terminal _except_ the ones that I had explicitly listed as skipping the shell. That is apparently not the case. I had to reread the documentation several times to get myself in order, but I think I've now figured it out. 

If anyone does a search and finds this, here is the relevant documentation: [https://code.visualstudio.com/docs/editor/integrated-terminal#_keybindings-and-the-shell](https://code.visualstudio.com/docs/editor/integrated-terminal#_keybindings-and-the-shell)

I think what would make this easier is if I could configure the skipping not in terms of commands, but in terms of bindings.

For example, my ideal setup is:

I would like all keyboard shortcuts to be handled by vscode unless the terminal is in focus. In that case, any of the following keypresses, regardless of what command they are bound to in vscode, should be sent to the shell. "ctrl+a, ctrl+e, ctrl+k, ctrl+c, ctrl+d, ctrl+l, ctrl+[, ctrl+z, ctrl+u, ctrl+r"

Thank you so much. Even though there is nothing to fix, if you hadn't responded to this I wouldn't have figured it out.

**Comment by Tyriar** [comment]
> I think what would make this easier is if I could configure the skipping not in terms of commands, but in terms of bindings.

This was considered as it makes more sense when thinking just about terminals, but it doesn't really play nicely with our keybindings system unfortunately and would lead to some inconsistencies in the product.

Glad to help!
