### ISSUE TITLE
Open the window with default dual columns

### ISSUE THREAD

**Issue by shaonianruntu** [microsoft/vscode#139484]
For now, VCS only supports one-column editing window and terminal window. If you need two columns, you need to manually click the column button to split the window.

![截屏2021-12-20 at 10 37 24](https://user-images.githubusercontent.com/16336682/146704300-b9b381c0-23dc-4cf1-b823-6c9b807b7bfb.png)

But I am accustomed to using dual columns. It is very inconvenient to manually split the editing window and terminal window every time. 

I hope to add the function of opening the editing window and terminal window with default split window.

![截屏2021-12-20 at 10 36 57](https://user-images.githubusercontent.com/16336682/146704429-f0538f3d-af75-4ea9-8458-dd674d3ac7fd.png)

Thanks
Nan

**Comment by shaonianruntu** [comment]
In addition, add a shortcut key to switch between different split windows.

**Comment by Tyriar** [comment]
You can use a keyboard shortcut to split the terminal, the default is ctrl+shift+5. Also, if you have typed into the terminal, it will be persisted across restarts unless you've changed the "persistent terminal" settings.

**Comment by Tyriar** [comment]
There are also builtin keybindings for moving between splits, it's alt on Windows for example - check the keybindings editor for the default on your platform.
