### ISSUE TITLE
Using mouse wheel scroll loses focus in main editor window

### ISSUE THREAD

**Issue by alainpannetier** [microsoft/vscode#139474]
Does this issue occur when all extensions are disabled?: Yes/No

YES

- VS Code Version:
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-91-generic

OS Version:
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20.2
DISTRIB_CODENAME=uma
DISTRIB_DESCRIPTION="Linux Mint 20.2 Uma"
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu Focal Fossa

Steps to Reproduce:

1.  Take any reasonably medium size file (500 lines are enough)
2.  Load that file in the editor (verified with css and simple text file)
3. Use mouse wheel to scroll up and down
      - Observe carret/cursor (I shaped) not on text
      - After less than 10 wheel scroll events carret disappears (focus lost)
      - Mouse wheel scroll inactive
      - Move mouse a bit (or click) to regain focus
      - Carret/cursor reappears
      - Mouse wheel scroll works again

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/133744
