### ISSUE TITLE
Shell integration: Create "Terminal: Run Recent Command" command

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#139401]
Parent issue https://github.com/microsoft/vscode/issues/133084

Blocked on:

- https://github.com/microsoft/vscode/issues/139406

Notes:

- This will present a quick pick with all recently run terminal commands, including command name, cwd, exit code
- When selected in the quick pick, the command will run in the active terminal
- Should have smoke tests
- Whatever tracks command history should have unit tests
- Considerations:
  - Do we have a maximum of entries we track?
  - Should this be sorted by recency of frequency?
  - Can we avoid settings for this feature?

**Comment by meganrogge** [comment]
maybe we can also have a commands view like ITerm 2 has?



![Command History](https://user-images.githubusercontent.com/29464607/147704917-bac30e2f-8cb8-4418-a5bd-17539a06faa2.png)

**Comment by meganrogge** [comment]
or actually, maybe better to use the quickpick to display them so it's accessible?

**Comment by Tyriar** [comment]
We also want to check to see if there is currently a command being input and send ctrl+c if so (`Terminate batch job` might cause problems on Windows)

**Comment by Tyriar** [comment]
Something else to think about, pretty sure we want to persist this information, but should it be persisted globally or per workspace?

**Comment by meganrogge** [comment]
I think per workspace since the commands one runs in different projects (esp if using different languages) are often very different.

**Comment by meganrogge** [comment]
I still wonder if commands should be saved per terminal instance.

**Comment by Tyriar** [comment]
@meganrogge I guess a combination is what would be best, a given terminal instance would have a series of commands with exit code, timestamp, maybe output, etc. But then we would have a deduped list of past commands that are persisted which don't store exit code/timestamp/etc., or at least if we did keep those it would only refer to the last time it was run.

**Comment by Tyriar** [comment]
- Should we share historical commands across shell types since zsh, bash, etc. are similar? Probably not since it's an edge case to commonly use multiple shells.
- What do we store in historical commands? Just last run time? Exit code is probably not useful, output isn't possible.
- For how long do we keep these records around? A month?
- We could sync historical commands across machines with the same shell type.
  - Should we share historical commands across OSs? Probably overcomplicating thing and there would be too many issues with path structures differing.
  - Should historical commands have a machine ID if we sync them?

**Comment by Tyriar** [comment]
More focused issue: https://github.com/microsoft/vscode/issues/141006, the command exists and works for commands in the current session.
