### ISSUE TITLE
Feature/Extension for Refactoring 

### ISSUE THREAD

**Issue by sandeepkokane97** [microsoft/vscode#139424]
Extension for refactoring:
Most vscode users are basically Javascript users, and all of them love vscode. But if vscode also could have a feature/extension which could help in refactoring code with various key-binding will be a very effective step in vscode and will save the enormous time of the developers and vscode experience will be grateful.
Thank you.

**Comment by IllusionMH** [comment]
/needsMoreInfo

VS Code has built-in code action for JS/TS. Rename, extract to method, implement interface etc. Check this page for details https://code.visualstudio.com/docs/languages/javascript#_refactoring

Do you have suggestions for specific refactorings?

**Comment by sandeepkokane97** [comment]
Can this refactoring be done in a quicker way like having key-bindings/ shortcuts? As the present feature is we should know the code is to be refactored. As IntelliJ IDEA provides the code can to refactor to a better extends and on Alt+Enter it provides solutions that all refactoring is possible.
If there were some highlights instead of selecting code and then clicking on the hint button and then knowing that the code can be refactored. It is not even known by many beginners.

**Comment by mjbvz** [comment]
@sandeepkokane97 See https://code.visualstudio.com/docs/editor/refactoring#_keybindings-for-code-actions
