### ISSUE TITLE
Two alert message boxes displaying and no alert commands in code

### ISSUE THREAD

**Issue by Josheir** [microsoft/vscode#139476]
My code is displaying two alert message boxes and there aren't any alert commands in the code there.  What can I do?  My Go version is 1.16.3. and 1.17.5.  I am using JavaScript.  Thank you!  Doesn't seem to be the cache either.

**Comment by Josheir** [comment]
I found the problem, an alert was in a function being called.  Thanks!

**Comment by gjsjohnmurray** [comment]
@Josheir please close your issue.
