### ISSUE TITLE
Debug Console doens't follow output when a command is entered while paused in debug mode

### ISSUE THREAD

**Issue by jpike88** [microsoft/vscode#139452]
Issue Type: <b>Bug</b>

- Pause a node process in debugger
- open Debug Console
- enter a command (can be anything)
- hit enter
- line just stays there and doesn't jump to bottom of the result

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

**Comment by jpike88** [comment]
see images:

before, I entered in some dummy lines to fill up the console window, then typed a real command and hit enter. as you can see it looks like nothings happened.
<img width="1025" alt="Screenshot 2021-12-19 at 12 38 34 PM" src="https://user-images.githubusercontent.com/9585787/146665253-0b14096a-a5b1-43ed-bd5d-bd3d4a42a736.png">

but if I scroll down...
<img width="1020" alt="Screenshot 2021-12-19 at 12 38 42 PM" src="https://user-images.githubusercontent.com/9585787/146665254-d9f0b16d-2f60-4d27-9fef-6f810e703256.png">

this is a frustrating function, I have scroll every time I enter something. really gets in the way

**Comment by roblourens** [comment]
I can't repro it and don't remember seeing this before. Does it happen 100% of the time?

**Comment by roblourens** [comment]
There was a fix that went in here some months ago, let me know if it still happens.
