### ISSUE TITLE
bootstrap-fork.js shown in every line of debug console

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode#139417]
Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: 1.61.2
- OS Version: macOS Big Sur

Steps to Reproduce:

1. Create a basic extension as described in https://code.visualstudio.com/api/get-started/your-first-extension
2. Launch its debug task
3. Open the debug console

In my case, the launch configuration is:

```json
		{
			"name": "Extension Tests",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--disable-extensions",
				"--extensionDevelopmentPath=${workspaceFolder}",
				"--extensionTestsPath=${workspaceFolder}/out/test/suite/index"
			],
			"outFiles": [
				"${workspaceFolder}/out/test/**/*.js"
			],
			"preLaunchTask": "${defaultBuildTask}",
		},
```

Then the debug console is cluttered with meaningless links to bootstrap-fork.js:

![image](https://user-images.githubusercontent.com/2845433/146618327-17fce6c9-3aa7-4258-8629-de532d5582e6.png)

**Comment by IllusionMH** [comment]
This is line where this message was logged to console. Like in the browser

**Comment by memeplex** [comment]
Yes, I understand that, but for spawned processes it's meaningless, a level up in the call chain may be useful, I don't know. This is not an artificial example. It's the recommended way to debug and test vscode extensions. Maybe some way of turning it off?

**Comment by memeplex** [comment]
> it's meaningless

I mean it's an implementation detail that's cluttering almost half of the console with long links to a minified and pretty obscure internal module.

**Comment by connor4312** [comment]
We should probably skipFile that automaticall in extension host configs

**Comment by memeplex** [comment]
Notice that since stdout/err are not forwarded to the debug console from the extension host (https://github.com/microsoft/vscode-test/issues/114, https://github.com/microsoft/vscode/issues/74173) there is another underlying issue that makes this worse: `console.log/error` are (ab)used as substitutes of stdout/err in order to send raw output. So even if you skip bootstrap-fork, its calling place won't be informative, probably a wrapper around `console.log/error`, and even the caller to this wrapper isn't that informative either since it's doing raw output that you usually don't want to associate with a "logging place" in the console. 

The chain is something like this:

- Not so interesting place: a testing framework writes "PASS test-one-equals-one" to stderr.
  - Even less interesting place: `process.stderr.write` was monkey patched to call `console.log`.
    - Uninteresting place: bootstrap-fork sends a log object to its parent process.

Regarding those stdout/err wrappers, I've seen many buggy implementations that simply take the input to stdout/err and forward it to `console.log/error`, hence adding "random" newlines here and there.

**Comment by connor4312** [comment]
This will be fixed in the next [nightly build](), though there are some issues with other extensions interfering with this:

- https://github.com/github/codespaces/issues/5622
- https://github.com/microsoft/vscode/issues/139895
- https://github.com/microsoft/vscode/issues/139894 
- https://github.com/microsoft/vscode-pull-request-github/issues/3213
- https://github.com/microsoft/vscode/issues/139896
