### ISSUE TITLE
Support format on paste

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#13945]
We should add support for format on paste. Idea is to simply invoke selection formatters when paste has happened.

**Comment by jrieken** [comment]
related to https://github.com/Microsoft/vscode/issues/4039

**Comment by coreh** [comment]
On OS X, could this be mapped to "Paste and Match Style"? ⌥⇧⌘V

**Comment by jrieken** [comment]
@rebornix Do you want me to get started on this? We already have the concept for formatting a range so, my plan is to do the following:

1) detect paste range
2) invoke range formatter

**Comment by rebornix** [comment]
@jrieken previously I implemented it in another way but we think that's not good, I'll follow your suggestions and do this again :)

**Comment by OliverJAsh** [comment]
Like @coreh I'm also interested to know whether this can be a command separate from paste so the user can choose which to use on demand (i.e. one keyboard shortcut for paste, one for paste + format)

**Comment by jakearchibald** [comment]
Firstly, thanks for adding this, it's been the *one* feature I really missed from Sublime Text.

Having a play around with it, it seems to create two entries into undo history per single paste. I can't decide if that's a bug or a feature.

**Comment by rebornix** [comment]
@jakearchibald It's not a bug but I can't say it's a feature :( The behavior is consistent with FormatOnType or Save as we hook the formatting handler to Type/Save/Paste event, which makes it two entries in undo/redo stack. cc @jrieken

**Comment by jakearchibald** [comment]
Another "is this a bug or not?"

If I paste:

```js
self.addEventListener('fetch', function(event) {
  event.respondWith(
    promiseAny([
      caches.match(event.request),
      fetch(event.request)
    ])
  );
});
```

It adds a space between `function` and `(event)`. I didn't expect it to do that.

**Comment by rebornix** [comment]
@mjbvz I suppose what @jakearchibald mentioned is actually TypeScript formatter's default behavior, right?

**Comment by mjbvz** [comment]
Yes, you can disable this formatting using `"javascript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false` or `"typescript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false`
