### ISSUE TITLE
Icons not showing up

### ISSUE THREAD

**Issue by briasativa** [microsoft/vscode#139480]
Issue Type: <b>Bug</b>

I added the VS icon extension and followed the directions. I watched the videos to make sure I installed it right. But alas, they don't show up anywhere. I am kinda new to this program. I searched the web and could not find the same issue. Thanks.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (2.72GB free)|
|Process Argv|--crash-reporter-id 515e9b05-ff93-430a-a4bc-49fe04d71574|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.45.0
eppz-code|epp|1.2.52
file-icons|fil|1.0.29
vscode-firefox-debug|fir|2.9.5
vscode-pull-request-github|Git|0.34.1
open-in-browser|igo|1.0.2
vscode-icons|vsc|11.8.0
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30405998
vscexrecpromp3t1:30407762

```

</details>

**Comment by joaomoreno** [comment]
Can you share a screenshot of what you mean?

**Comment by briasativa** [comment]
I got the extension for icons, enabled it, and activated it, but it doesn't
show up. I also tried the file-icons extension and no luck. I am including
a screenshot that shows the extension enabled (it shows how it should look
when icons are enabled) and the whole screen showing missing icons. If
there is something I'm missing, please let me know. Thanks!

Best wishes,
*Bria Sativa Aguayo*
www.briasflowers.com
Welder/Horticulturist
Designer/Photographer
404.909.7505

**Comment by joaomoreno** [comment]
It's best to include the screenshot in GitHub. If you send it by e-mail, it doesn't work.

**Comment by briasativa** [comment]
Here are the screenshots. I missed the previous message. :-/
![Screenshot 2021-12-31 100655](https://user-images.githubusercontent.com/90485908/148689065-dde4f509-944d-4024-8514-32e4b2e99fc0.jpg)
![Screenshot 2021-12-31 100557](https://user-images.githubusercontent.com/90485908/148689074-66b8a4a0-9fa8-46b7-b65b-0bc7cbd39470.jpg)

**Comment by joaomoreno** [comment]
In your second screenshot, there is an error in the bottom-right corner which has its information cut, is it relevant?

Anyway, if you press <kbd>F1</kbd>, type `Icon` and choose `Preferences: File Icon Theme`, you can switch between those themes.

**Comment by briasativa** [comment]
The error is not relevant. It's just having trouble connecting to GitHub
pull requests. The problem is that is relevant is that I can't access
icons. I have selected the File Icon Theme, and it doesn't do anything.
If you look at the attached screenshots (I realized the last ones weren't
very clear - my bad) the vs-code-icon-menu.jpg is the extension preview of
what the icon menu is supposed to look like. It also shows choosing an icon
(it's actually a GIF and shows how to choose an icon). The
vs-code-icon-menu-missing.jpg screenshot shows the icon menu is missing in
my actual VS-Code. This is the issue. I have no way of accessing the icons
without this menu. I've tried disabling and re-enabling the extension; I've
tried going between icon extensions; I've tried looking everywhere for a
hidden menu; I've tried uninstalling and reinstalling the extensions.
Nothing brings up the icon menu where I can select an icon. Therefore,
icons are unavailable. Can you help me with this? Thanks!

Best wishes,
*Bria Sativa Aguayo*
www.briasflowers.com
Welder/Horticulturist
Designer/Photographer
404.909.7505

**Comment by joaomoreno** [comment]
Unfortunately attaching screenshots via email doesn't work. Do you mind coming to GitHub and attach the new screenshots? Thanks.

**Comment by briasativa** [comment]
Whoops, I forgot. This is all pretty new to me. So the menu-missing JPG shows that there is no icon menu. There is no way to access icons, unless there is something I'm missing. In the menu-preview JPG it shows what the extension is supposed to look like with a drop-down menu to access icons. I already gave you details of what I have tried. Let me know if there is something I can do. Thanks!
![vs-code-icon-menu-missing](https://user-images.githubusercontent.com/90485908/149427738-e96da2e2-3efb-48a4-9d8c-990b9d11e236.jpg)
![VS-code-icon-menu-preview](https://user-images.githubusercontent.com/90485908/149427742-a38704ac-ec44-4aa3-be25-565b556e27ec.jpg)

**Comment by joaomoreno** [comment]
>  the menu-preview JPG it shows what the extension is supposed to look like with a drop-down menu to access icons.

No, that screenshot just shows an explorer panel with the title `VSCODE-ICONS`. The user who took that screenshot had a folder open, called `vscode-icons`, which contained several files with different extensions, which acted as a sample for that specific screenshot.

**Comment by briasativa** [comment]
So, how do I access icons? That's the issue. I have the extension and can't
figure out how to use icons in the html. Do I need to import icons or
something?
I couldn't find any instructions except the ones I already did, including
the ones you suggested.
I've been able to use other extensions but this one. I've started trying
out other text editors in case I can't use VS Code. Any other suggestions
would be appreciated. Thanks!

Best wishes,
Bria Sativa Aguayo
Horticulturist/Welder
Designer/Photographer
www.briasflowers.com
404-909-7505

**Comment by joaomoreno** [comment]
The extension contains icon for VS Code. These icons are not meant for you to use in your HTML projects.

**Comment by briasativa** [comment]
Or CSS? How do I use icons in HTML?

**Comment by joaomoreno** [comment]
Please ask your question on [StackOverflow](https://aka.ms/vscodestackoverflow).

Happy Coding!
