### ISSUE TITLE
erratic undo redo in vue single file component

### ISSUE THREAD

**Issue by mgiraldo** [microsoft/vscode#139448]
Issue Type: <b>Bug</b>

Redo stops working when text cursor gets “trapped” inside a HTML tag bracket. Attached is a GIF reproducing the issue. It is rather unpredictable so it is possible that the bracket is not the issue. I just got lucky that i was able to get it to appear consistently in this particular file.

![undo-redo](https://user-images.githubusercontent.com/133020/146657221-64c02470-2af7-4193-86ff-5fbc456b9849.gif)

VS Code version: Code 1.63.0 (Universal) (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 6, 5|
|Memory (System)|64.00GB (0.72GB free)|
|Process Argv|--crash-reporter-id 223afcc8-0da3-44a7-876a-618b32d5e4e8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.62
vue-peek|dar|1.0.2
vscode-eslint|dba|2.2.2
file-icons|fil|1.0.29
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
vscode-rufo|jnb|0.0.4
vscode-peacock|joh|4.0.0
volar|joh|0.26.16
haml|kar|1.3.1
expand-region|let|0.1.4
rainbow-csv|mec|1.10.1
vscode-scss|mrm|0.10.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
color-highlight|nau|2.5.0
ruby|reb|0.28.1
svelte-vscode|sve|105.8.0
simple-ruby-erb|vor|0.2.1
vscode-ruby|win|0.28.0
fig|wit|0.0.1

</details>

**Comment by mjbvz** [comment]
Please start by filing this against your Vue extension
