### ISSUE TITLE
Allow selective overriding of file explorer and workbench icon associations, instead of overriding all icons

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode#139477]
# Problem Statement

I'd like to, for example, create a new programming language.

I'd like to change the icon file association for my programming language, so that a logo for my programming language appears instead of the default icon.

For simplicity, let's say I'm creating a fictitious GitHub programming language that has files that end in `.gh` and my language makes use of a `github` script, for which I am also updating the icon.

If I just do

```
        "iconThemes": [
            {
              "id": "override",
              "label": "Only override a few icons",
              "path": "./override-icon-theme.json"
            }
        ],
```

in the `contributes` section of `package.json`, and `override-icon-theme.json` is

```
{
	"iconDefinitions": {
		"_github_logo": {
			"iconPath": "./GitHub-Mark-120px-plus.png"
		}
	},
	"fileExtensions": {
		"gh": "_github_logo"
	},
	"fileNames": {
		"github": "_github_logo"
	}
}
```

then I end up with

![Screen Shot 2021-12-19 at 12 11 50 PM](https://user-images.githubusercontent.com/43425812/146689369-32844624-3b38-44b6-96c8-046cf6a0d0b4.png)

Notice how _all_ icons are gone, except for the ones I specified.

How do I keep all icons, _except_ for the specific ones I want to override?

Even if I were to just copy-and-paste [`extensions/theme-seti/icons/vs-seti-icon-theme.json`](https://github.com/microsoft/vscode/blob/main/extensions/theme-seti/icons/vs-seti-icon-theme.json), and merge

```
{
	"iconDefinitions": {
		"_github_logo": {
			"iconPath": "./GitHub-Mark-120px-plus.png"
		}
	},
	"fileExtensions": {
		"gh": "_github_logo"
	},
	"fileNames": {
		"github": "_github_logo"
	}
}
```

with that, that would be a hindrance to developers who use, say, [`extensions/theme-defaults/fileicons/vs_minimal-icon-theme.json`](https://github.com/microsoft/vscode/blob/main/extensions/theme-defaults/fileicons/vs_minimal-icon-theme.json), since now they have to use [`extensions/theme-seti/icons/vs-seti-icon-theme.json`](https://github.com/microsoft/vscode/blob/main/extensions/theme-seti/icons/vs-seti-icon-theme.json) as their "fallback" icons to see updated icons for the fictitious "GitHub" programming language.

It would be really helpful if I could just selectively pick-and-choose which icon file associations to override, and let the remaining icon associations stay as-is, so as to not disturb developers' other icon preferences.

What are your thoughts on this?

**Comment by aeschli** [comment]
There's PR https://github.com/microsoft/vscode/pull/118846 in the works that allows languages extensions to define a default icon for their language.

Ok to close in favor of https://github.com/microsoft/vscode/pull/118846?

**Comment by hamirmahal** [comment]
Ah, I was not aware of this. That's fine with me. Thank you for the response!

Another issue I created, #138949, is also basically a duplicate of #118846.
