### ISSUE TITLE
Scroll bar sometimes won't respond to dragging

### ISSUE THREAD

**Issue by riksweeney** [microsoft/vscode#139433]
Issue Type: <b>Bug</b>

Sometimes the scrollbar will not respond to dragging. The editor window will move using the arrow keys or mouse wheel, but clicking and dragging the bar has no effect.

Opening a dialog window such as the Process Explorer or Issue Reporter and then closing it will fix the problem.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.4.0-91-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.69GB (0.74GB free)|
|Process Argv|--unity-launch --crash-reporter-id d148cfb9-67a7-4d91-8b0a-68f981b8eb7b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.15.10
cpptools|ms-|1.8.0-insiders2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710:30405998
vscexrecpromp3c:30407761

```

</details>

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/124895

**Comment by Drarig29** [comment]
@ricksentam thanks for the tip about opening a dialog window!
