### ISSUE TITLE
Issues loading php library

### ISSUE THREAD

**Issue by GodModus** [microsoft/vscode#139441]
Issue Type: <b>Bug</b>

I tried printing the module list with apachectl -f '/Library/Application Support/appsolute/MAMP PRO/conf/httpd.conf' -M             but I got an error (listed below). I tried resetting the httpd.conf but that didnt work. The files exist in the directory. What caught my eyes was 'dlopen' command which is not part of macos terminal. For the rest php seems to work just fine.

ERROR 
httpd: Syntax error on line 188 of /Library/Application Support/appsolute/MAMP PRO/conf/httpd.conf: Cannot load /Applications/MAMP/bin/php/php7.3.29/modules/libphp7.so into server: dlopen(/Applications/MAMP/bin/php/php7.3.29/modules/libphp7.so, 10): Library not loaded: @rpath/libzip.5.dylib\n  Referenced from: /Applications/MAMP/bin/php/php7.3.29/modules/libphp7.so\n  Reason: image not found

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (2.60GB free)|
|Process Argv|-psn_0_1794486 --crash-reporter-id 43285e02-fbd7-474b-8304-20d0141d4c56|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.22.0
php-pack|fel|1.0.2
php-debug|rob|1.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710:30405998
py55gd98:30411514
vscexrecpromp3t3:30407764

```

</details>

**Comment by roblourens** [comment]
Sorry I don't understand why this is a vscode issue, can you explain some more?

**Comment by GodModus** [comment]
The error log is generated by macOS whenever an app crashes. I noticed that some  big mkv files open just fine (but freeze the app for a few minutes), while other files simply cause crashes. These videos are ripped from encrypted 4K and blu-ray movies. I used rip tool makeMKV. Could the tool or the video source or file format have something do with it?

**Comment by roblourens** [comment]
I need exact steps for what you are doing and what happens. You are opening video files in vscode?
