### ISSUE TITLE
Add an option to not focus sidebar from Cmd-B

### ISSUE THREAD

**Issue by DonMartin76** [Microsoft/vscode#13943]
- VSCode Version: 1.6.1
- OS Version: macOS Sierra 10.12.0

Steps to Reproduce:
1. Open a code editor window
2. Mis-type Cmd-V (paste) and press Cmd-B (hide directory/file pane)
3. Press Cmd-B again to show the left pane again
4. Cuss and grab the mouse to click inside the editor because it has lost focus

Expected: Focus is still on editor window.

**Comment by roblourens** [comment]
I think this is by design... You should be able to refocus the editor with `cmd+1`.

**Comment by DonMartin76** [comment]
Thanks for the hint with Cmd-1. It's still annoying though, even if it's as designed. I do this all the time.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
