### ISSUE TITLE
words prohibition in writing any code 

### ISSUE THREAD

**Issue by amanjhaaa** [microsoft/vscode#139458]
We have written the neeI updated my vs code last night and after that they prohibited me to write some certain word in the code . 1>)I am unable to write "Node" in the c code 2.) I am unable to write "endl " in my c++ program . It is taking this words by copy paste , but for this too short word why i will use copy paste and waste my time . Kindly help me regarding this . I have reset my vs code , done restricted mode false , but no reponse . Same is happening .

Note :- I am using windows 11.ded data into your clipboard because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

Please also describe or show how VS Code "prohibits" you.

Also paste version info from the About dialog on the Help menu.

/needsMoreInfo

/gifPlease
