### ISSUE TITLE
Native Window Title Bar

### ISSUE THREAD

**Issue by demimurych** [microsoft/vscode#139438]
Issue Type: <b>Bug</b>

Невозможно включить системный title bar для окна.
Настройка игнорируется. Вместо нее показывается  title bar созданный средствами самой среды. 
Сброс настроек, чистая установка не решает проблемы.

Kubuntu 20.04 
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-91-lowlatency
OS Type: 64-bit
Processors: 4 × Intel® Core™ i7-3520M CPU @ 2.90GHz
Memory: 15,6 ГиБ

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.4.0-91-lowlatency
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 3184)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.58GB (10.15GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 9623192c-64d4-4d95-b38b-dd44bc495f7f --crash-reporter-id 9623192c-64d4-4d95-b38b-dd44bc495f7f --crash-reporter-id 9623192c-64d4-4d95-b38b-dd44bc495f7f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
overtype|ada|0.2.0
webassembly|trf|0.2.0
QML|bbe|1.0.0
vscode-wasm|dts|1.3.1
comment-anchors|Exo|1.9.1
vscode-projects-plus|fab|1.23.4
sftp|lix|1.12.9
git-graph|mhu|1.30.0
vscode-apache|mrm|1.2.0
vscode-language-pack-ru|MS-|1.63.3
murablock|dem|0.0.1
errorlens|use|3.4.1

(2 theme extensions excluded)

</details>

**Comment by CodeCrazy-ywt** [comment]
Google:
Unable to enable system title bar for window. Setting is ignored. Instead, the title bar is shown, created by means of the environment itself. Resetting the settings, a clean installation does not solve the problem.

**Comment by sbatten** [comment]
@demimurych do you still have this issue? if so, can you provide a screen recording of relevant settings and the experience you are seeing?
