### ISSUE TITLE
Decrease tooltip showing speed

### ISSUE THREAD

**Issue by EugeneQilo** [microsoft/vscode#139482]
Issue Type: <b>Feature Request</b>

There seems to be a recent update on Visual Studio Code to show the tooltip faster when hovering over objects and classes. I found this to be very annoying, often times you hover over some text to reach the line above but by then the tooltip of the line below has appeared and causes inconvience where you want to work

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by yume-chan** [comment]
It haven't been changed

https://github.com/microsoft/vscode/blame/36fdeed3b5b4136607e45e4b75334b23b517c313/src/vs/editor/common/config/editorOptions.ts#L1841

You can change that with `"editor.hover.delay": 2000`

**Comment by jespertheend** [comment]
> It haven't been changed

I think it might have been though. If I set hover delay to 10 seconds, the hovers appear in 5 seconds.

**Comment by jespertheend** [comment]
Seems this regressed in https://github.com/microsoft/vscode/commit/ade68869b89b9fee7ea20d22af6546fb2a4f7cc1

**Comment by jespertheend** [comment]
Also see https://github.com/microsoft/vscode/issues/139818
