### ISSUE TITLE
Fix css imports to use standardized assert: {type: 'css' }

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/vscode#139416]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. see: https://github.com/microsoft/vscode/blob/edbf56a72a0630649effa940940d0800d42753e2/src/vs/editor/standalone/browser/accessibilityHelp/accessibilityHelp.ts#L6
2. the css import should use 
https://web.dev/css-module-scripts/

**Comment by hediet** [comment]
Let's track [here](https://github.com/microsoft/monaco-editor/issues/2839).

This is an issue of bundling.
