### ISSUE TITLE
Jupyter notebook: idea for easier cell merge and bug in "undo cell merge"  

### ISSUE THREAD

**Issue by kolibril13** [microsoft/vscode#139473]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.63.2
- OS Version: Mac OS 12.0.1 (21A559)

**Idea:** When multiple cells are selected, it should be possible to merge only the selected cells.
 Currently, it is only possible to merge all selected + previous or all selected + next cell.

**Bug:** When one uses the "Undo" button, the cell with the merged code keeps all the code, see screen recording.
However, this merging process should be reversed. 

Steps to Reproduce:

https://user-images.githubusercontent.com/44469195/146681380-9a7df938-3c80-4dd5-95da-986345280205.mov

**Comment by rebornix** [comment]
@kolibril13 thanks for your feedback. Note that Join Cells with Previous/Next are different from Merge Cells (which we don't support yet in VS Code but can be a good extension candidate). With that being said, it's a valid bug that undo doesn't revert.

**Comment by rebornix** [comment]
Should be fixed now.
