### ISSUE TITLE
Multiple application instances opening, freezing

### ISSUE THREAD

**Issue by cooper-joe** [microsoft/vscode#139496]
Issue Type: <b>Bug</b>

## Description
Multiple instances of VSCode open when launching. The _duplicate_ instances seem to be frozen ("Application not responding" shown when right-clicking in the dock). macOS Activity Monitor shows 3 _Code_ processes running. Attempting to quit any of them closes the original and its duplicates.

Previously, only a single duplicate instance was opening. Today it is 2 duplicates. I deleted and reinstalled VSCode, but it still happens.

## Screenshots

![image](https://user-images.githubusercontent.com/33054985/146730128-23097615-f728-464c-8f8f-f5c72a641857.png)

![image](https://user-images.githubusercontent.com/33054985/146730137-900fd484-4860-4182-94f9-e3ce54c1e126.png)

![image](https://user-images.githubusercontent.com/33054985/146730201-94df12a8-b78a-4118-9edf-00d097e4099e.png)

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.54GB free)|
|Process Argv|--crash-reporter-id dc433d48-0208-4b80-9bdc-f5522283d8f6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgo|ajh|0.1.0
cucumberautocomplete|ale|2.15.1
html-end-tag-labels|ant|0.8.0
vs-code-css-comments|ash|1.0.5
spellright|ban|3.0.60
markdown-preview-github-styles|bie|0.2.0
theme-clear|dan|2.0.4
vscode-eslint|dba|2.2.2
binary-plist|dni|0.8.0
vale-server|err|0.14.2
prettier-vscode|esb|9.0.0
change-string-case|max|1.1.2
vscode-typescript-tslint-plugin|ms-|1.3.3
vscode-react-native|msj|1.8.1
color-highlight|nau|2.5.0
text-power-tools|qcz|1.30.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.6.1

(4 theme extensions excluded)

</details>

**Comment by joaoponceleao** [comment]
I can confirm this with the latest insiders

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/138712
