### ISSUE TITLE
Browser: serving whole of vscode on a webserver

### ISSUE THREAD

**Issue by mbana** [Microsoft/vscode#13947]
Are there any plans to allow serving the whole of the app using a webserver.

There are several projects that get around this, so I makes me think, it's better if this becomes part of vscode itself. Examples:
- https://github.com/sourcegraph/sourcegraph-go
- https://github.com/spiffcode/ghedit

If you have a rough idea on how to go about implementing it, I'll also take a look.

If you're wondering why I'm wanting to do this; the [monaco-editor](https://github.com/Microsoft/monaco-editor) module doesn't contain as much features as `vscode` and, I think, it also falls behind a bit?

**Comment by alexandrudima** [comment]
@mbana regarding the monaco-editor: it contains only the text editor that is used in vscode. it is shipped in a monthly rhythm (same as vscode). For the other question, I will ask @egamma to chime in.

**Comment by mbana** [comment]
@alexandrudima and @egamma, hi, to the both of you,

I have a rough idea on how to go about doing this. It requires a lot of work though. From my limited experience in browsing the code, here what's I noticed:

* `vscode` should perhaps be an interface.
* `vscode.native` should be what the native version uses.
* `vscode.browser` would be a one that folks wanting to use a browser-based emulation would import, say.

*I think* Eclipse did something similar?

We've, [Synthace Limited](https://github.com/Synthace) been trying to get Monaco to talk to a languageserver via WebSockets, so that we can reuse the functionality done in [vscode-languageserver-node](https://github.com/Microsoft/vscode-languageserver-node) to manage all the models etc. This requires a bit of work so it's still WIP.

What I've noticed is the modules could benefit from this layer of abstraction.

There are projects that already bring a vscode-like experience to the browser, pls see https://github.com/Microsoft/vscode/issues/446. However, I feel they complicate things and are not generic enough for wild-scale use. Feels hacky, no ill intention meant here.

**Summary:**

Enhancing <https://github.com/mbana/vscode-languageserver-node> to support WebSocket as a transport instead of just tcp and stdio. This requires a fair bit if refactoring.

We are using <https://github.com/mbana/go-langserver> as the languageserver.

The folks at sourcegraph seem to be in agreement with the WebSocket approach, pls see https://github.com/sourcegraph/go-langserver/pull/13. Ccin @sqs and @keegancsmith.

I guess something ideal would be:

* [vscode-languageclient](https://github.com/Microsoft/vscode-languageserver-node/tree/master/client) would have two+ implementations; vscode-languageclient-native, vscode-languageclient-browser etc.
* [vscode-languageclient](https://github.com/Microsoft/vscode-languageserver-node/tree/master/jsonrpc) likewise.
* and the rest of the modules that have hard dependencies on native `vscode`.

---

Feedback most welcome!!!

**Comment by egamma** [comment]
@mbana 

> Are there any plans to allow serving the whole of the app using a webserver.

This is appealing, but our current priority is the desktop application, sorry. 

BTW, you have built something similar in the past it was called 'Visual Studio Online Monaco' https://channel9.msdn.com/Series/Visual-Studio-Online-Monaco.

**Comment by MGazi42** [comment]
Is there any update about this issue?

**Comment by MGazi42** [comment]
I want this feature very much. Could you add it to the road map?
