### ISSUE TITLE
IntelliSense not working until target file is opened.

### ISSUE THREAD

**Issue by murrellr** [microsoft/vscode#139579]
I've created a Visual Studio Code project from an existing website and I can't get IntelliSense to work properly. This is a pure HTML5/JavaScript ES5 website. I want to use VSCode to edit and debug under Chrome browser. This is our existing directory structure:

```
web/
   Product1/
      index.html
      main.js
      ui.js
   Product2/
      index.html
      main.js
      ui.js
   lang/
      lang_en.js
      (other language files)
   lib/
      (third party js files)
   shared/
      shared1.js
      shared2.js
      (other shared js files)
```

We use a javascript compiler to render each product to an index.html.gz file and embed that file into our products to be served by our internal web server.

I installed VSCode and created a workspace file in web/. I also created jsconfig.json in web/Product1/. This is the content of the jsconfig.json:

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6"
    },
    "include": [
        "../images/*",
        "../lang/*",
        "../lib/*",
        "../shared/*"
    ]
}

```
I open shared1.js in the editor and right-click on an object that is defined in shared2.js and select "Go to definition", I get "No definition found for 'object'". If I open shared2.js VSCode "Go to definition" will work between those files. If I exit VSCode and reopen the workspace, it can't find the object until I repeat this sequence.

**Comment by IllusionMH** [comment]
> I want to use VSCode to edit and debug under Chrome browser. 

Are you using web version (vscode.dev or github.dev)?

Web version currently has limitation that works only with open files, as it's not trivial task to effectively launch TS server and works with all files.

**Comment by murrellr** [comment]
> Are you using web version (vscode.dev or github.dev)?

I don't know what this means.  I have Windows 10 and installed VSCode with VSCodeUserSetup-x64-1.63.1.exe.

**Comment by mjbvz** [comment]
If it still isn't working after creating a jsconfig, please share a minimal example project that demonstrates this issue so we can investigate

**Comment by murrellr** [comment]
I have reduced our environment to the simplest form that reproduces the problem:

1. Unzip the attached folder.
2. Open folder 'test/' in VSCODE.  If any editor tabs are open, close the tabs, close the workspace, and reopen the workspace.
3. Select Explorer in the Activities bar.
4. Open shared/shared1.js from the explorer side panel.
5. Right-click over 'SHARED2.show()' on line 13 of shared1.js.  Select "Go to definition".  The editor will show "No definition found for 'show'"
6. Open shared/shared2.js from the explorer side panel.
7. Select the shared1.js editor tab.  Right-click over 'SHARED2.show()' on line 13 of shared1.js.  Select "Go to definition".  Focus will change to shared2.js editor tab, line 6.
8. Close all open editor tabs and close VSCODE.
9. Repeat from step 2 and step 5 will show "No definition found for 'show'".

[test.zip](https://github.com/microsoft/vscode/files/7810125/test.zip)

**Comment by murrellr** [comment]
I've found that you do not have to exit VSCODE.  Close the shared2.js editor tab and retry step 5, and it will fail.

**Comment by mjbvz** [comment]
Since you are using globals without explicit file references, you need to create a jsconfig if you want unopened files jS to be included in the project: https://code.visualstudio.com/docs/languages/jsconfig

**Comment by murrellr** [comment]
There is a jsconfig.json in Project1 folder:
`
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6"
    },
    "include": [
        "../shared/*"
    ]
}
`
