### ISSUE TITLE
Add "Copy As" button to context menu

### ISSUE THREAD

**Issue by abousselmi** [microsoft/vscode#139576]
{is:issue is:open copy as context menu } = {}

Hi,

I suggest that we have a new button `Copy As` in the context menu of the `Explorer` next to `Cut` and `Copy`, that will copy the selected file in the same location and opens its name for editing. It's like a `Copy` and `Rename` in one click.

Thank you.

**Comment by JacksonKearl** [comment]
I recommend finding or creating an extension for this. The extension would contribute a command to the explorer's context menu which would open a quick input for the name of the new file. Let me know if you need any pointers on how to build something like this.
