### ISSUE TITLE
[json] schema association not working for external file and multi-root workspace

### ISSUE THREAD

**Issue by johnspurlock** [microsoft/vscode#139584]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: macOS Monterey 12.1 (21C52)

Steps to Reproduce:

1.  Create a jsonc file with trailing commas
2. Note that vscode problems view hates them
3. Read issue #102061
4. Put the following in vscode settings
```
    "json.schemas": [{
      "fileMatch": ["*.jsonc"],
      "schema": {
        "allowTrailingCommas": true
      }
    }]
```
5. Problems view still hates them, it seems to have no effect.

Did something change since then?  Is there another way to get VSCode to ignore trailing commas as a problem in the problems view?

**Comment by aeschli** [comment]
I tried
```
  "json.schemas": [
    {
      "fileMatch": ["*.jsonc"],
      "schema": {
        "allowTrailingCommas": true
      }
    }
  ],
  ``` 
and it still works for me.

**Comment by johnspurlock** [comment]
Hmm, what am I doing wrong?

~/Library/Application Support/Code/User/settings.json
```json
{
    "editor.minimap.enabled": false,
    "security.workspace.trust.untrustedFiles": "open",
    "explorer.confirmDelete": false,
    "terminal.integrated.defaultProfile.osx": "bash",
    "telemetry.telemetryLevel": "off",
    "editor.fontSize": 11,
    "json.schemas": [{
      "fileMatch": ["*.jsonc"],
      "schema": {
        "allowTrailingCommas": true
      }
    }]
}
```
![trailing-commas](https://user-images.githubusercontent.com/528937/147833491-4a56eeec-0738-4e2b-9d08-8628d2a95767.png)

**Comment by aeschli** [comment]
Is this in a multi-root workspace?

**Comment by johnspurlock** [comment]
No, actually I see now that it seems to only reproduce on jsonc files opened that reside outside of the workspace.

If it's in the user-level setting, I would have guessed that it should apply to any opened file, no?

**Comment by aeschli** [comment]
It's with multi-folder workspaces and an external file

**Comment by johnspurlock** [comment]
Thank you!

This will be in next month's 1.76, right?  i.e not the version released today: https://code.visualstudio.com/updates/v1_75

**Comment by aeschli** [comment]
Yes 1.76
