### ISSUE TITLE
Incorrect bracket colors in Vue HTML

### ISSUE THREAD

**Issue by voidMike** [microsoft/vscode#139512]
Issue Type: <b>Bug</b>

Object props with nested objects have incorrect brace colors if the closing braces of the two objects are touching. The issue continues with further nesting, with weirder results when the nesting depth is even.
```
<template>
	<test :some-value="{param1: 2, object: {}}"/>
</template>
```

![image](https://user-images.githubusercontent.com/12560261/146752487-0610b83f-f0b4-41e8-a92d-ce87315bcad4.png)
![image](https://user-images.githubusercontent.com/12560261/146755644-db34816d-648c-4fb5-a038-67a8ddcdfd54.png)

VS Code version: Code - Insiders 1.64.0-insider (807bf598bea406dcb272a9fced54697986e87768, 2021-12-20T07:18:13.749Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vetur|oct|0.35.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
vscop804cf:30404767
vs360:30404995
vsclayoutctrt:30405800
py55gd98cf:30408622
vscexrecpromp3t3:30407760
azactmsal:30409287

```

</details>

**Comment by voidMike** [comment]
Token inspector says that they are `Other`
![image](https://user-images.githubusercontent.com/12560261/146763193-20224d7b-68e0-46d3-a060-b162dd129ddf.png)

**Comment by hediet** [comment]
Can you check the language of each bracket token? Matching brackets must have the same language.

**Comment by voidMike** [comment]
Everything has `vue-html` as the language.
Matching brackets have the same textmate scopes. The same color ones that shouldn't match have differing textmate scopes.

**Comment by hediet** [comment]
This is the issue:
https://github.com/vuejs/vetur/blob/5651cd5ff61a81a1f85b557eba052dc84602c8c0/languages/vue-html-language-configuration.json#L13

vue-html configures `}}` to be a bracket pair. The parsing algorithm matches longest bracket pairs first (otherwise they would never be matched).

Please file an issue in the vue extension.
