### ISSUE TITLE
Open file column lock feature

### ISSUE THREAD

**Issue by moon-ANVVIL** [microsoft/vscode#139548]
When opening a new current file, the file always opens in the column to which the currently focused file belongs.

There is no problem in general use, but it becomes complicated when using by opening and closing multiple files editing, multiple columns.

If the new file can be fixed to open from the right or left, it will increase ease.

**Comment by bpasero** [comment]
> If the new file can be fixed to open from the right or left, it will increase ease.

Can you clarify how exactly this would work?

**Comment by moon-ANVVIL** [comment]
현재 작동 방식입니다.

![vscode_group_openfile](https://user-images.githubusercontent.com/1875278/147029775-7ebc4634-610a-40e8-a7cd-21a9bd69865a.gif)
It works in a group when you openfile.(current)

When users use multiple groups and open multiple files to edit, it is difficult to immediately know which files are open to which group.

My suggestion is to fix it so that it opens in the right column (up row when it's vertical) when opening a new file. (left,down, toggle fuction...whatever)

The benefits of this are that even if you open multiple files, you will not find which group you are in, know the location, and get the desired group configuration and placement.

I'm not an English speaker.
This article used a translator.
I don't think the translation will be smooth.
Thank you for your consider.

**Comment by bpasero** [comment]
It sounds to me that locked editor groups could be helpful here: https://code.visualstudio.com/updates/v1_60#_locked-editor-groups

One thing to note though is that we decided to only allow you to lock a group when more than one group is opened. I.e. you cannot lock the primary group.

**Comment by moon-ANVVIL** [comment]
It was confirmed that the function mentioned was working.

![open_in_webview](https://user-images.githubusercontent.com/1875278/147311846-00c29876-2e66-4bc5-a92b-0301a1643eea.gif)

This is the extension I use.(markdown preview enhanced)

This extension allows you to view the markdown preview in vcode as a web view and supports file links.
When reviewing the plug-in's code, it simply requests to open the file. However, in this case, when a file is opened in vcode, the file is opened in the group where the current preview is located, ignoring the group lock.

**Comment by bpasero** [comment]
@moon-ANVVIL thats a great bug you found, tracking in: https://github.com/microsoft/vscode/issues/139713

When that issue is fixed, you should be fine so I will go ahead and close this issue.

**Comment by moon-ANVVIL** [comment]
good news. thank for your response :)
