### ISSUE TITLE
Format code is not working for XML.

### ISSUE THREAD

**Issue by xucaen** [Microsoft/vscode#13954]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 6.1.7601

Format code is not working for XML. Shouldn't it work?

Steps to Reproduce:

1. enter xml code with no line breaks
2. press ALT+Shift+B

**Comment by roblourens** [comment]
We don't support this out of the box, but I see extensions for formatting XML.

**Comment by xucaen** [comment]
I tried the #1 extension for formatting xml and it didn't work,  so
something in VSCode prevents xml from being formatted by extensions.

**Comment by roblourens** [comment]
I doubt it's an issue on vscode's end if that's the case, maybe file a bug on them?
