### ISSUE TITLE
[themes] "textMateRules" section in workspace settings completely overrides same section in user settings 

### ISSUE THREAD

**Issue by Dromantor** [microsoft/vscode#139503]
Issue Type: <b>Bug</b>

Having a `"editor.tokenColorCustomizations" > "textMateRules"` section in workspace settings fully overrides any settings made in user settings. Just having an empty textMateRules sections clears all customizations from the user settings.

Examples:
- no workspace override = all fine
![wo_workspace_setting](https://user-images.githubusercontent.com/1822013/146743443-5f7cbb8f-0611-4a67-b2c1-3f9117fa287f.png)
- override a single scope = all user settings gone
![with_workspace_setting](https://user-images.githubusercontent.com/1822013/146743452-cca84c1f-968d-4e15-8e2f-d8c666d9b24d.png)

For the reason why one would even want to override styles for a single workspace: I'm working on a microcontroller project and I'm using a custom formatted printing function with { } placeholders to write internal values to debug serial. And every instance where a % sign occurs is highlighted red because code thinks it's an illegal printf placeholder. So I just set the highlighting for those placeholders to the same color as the strings. (Is there maybe a better way to just disable the detection of those placeholders?)

As a workaround I currently just apply those rules without a "[Default Dark+]" theme section which seems to work.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.07GB free)|
|Process Argv|--crash-reporter-id f88d64be-4345-4275-b2bd-d984644ea1a3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.8.0-insiders2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710cf:30416617
vscexrecpromp3t2:30407763

```

</details>

**Comment by aeschli** [comment]
It's the same with all settings that are not maps. Only maps are merged across the the scope hierarchy. The `textMateRules` setting is an array. So the folder setting overrides the user settings. That's all done by the configuration store and as a consumer of the configuration store we don't need to know about the hierarchy. I fact the hierarchy has several levels: folder > workspace > machine > user > default, sometimes also language, so it's better not to implement a custom lookup.

There are currently no plans to change that.
