### ISSUE TITLE
Delete key in notebooks deletes selected cell

### ISSUE THREAD

**Issue by oscarrutt** [microsoft/vscode#139507]
Issue Type: <b>Feature Request</b>

In ipynb notebooks, when a cell is selected, hitting Delete should delete the cell.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 15.6.0
Restricted Mode: No

**Comment by rebornix** [comment]
To avoid deleting cells unexpectedly, we didn't bind Delete key to cell deletion command, instead we bind `Cmd+Backspace` to it. However you can still add following rule to your keybindings file to bind Delete

```
	{
		"key": "delete",
		"command": "notebook.cell.delete",
		"when": "notebookEditable && notebookEditorFocused && !inputFocus"
	}
```
