### ISSUE TITLE
File python deleted suddenly on Visual studio code

### ISSUE THREAD

**Issue by Sirjoe8** [microsoft/vscode#139577]
I was running a file python while suddenly its paths did not existed anymore.
After Visual studio code did not work anymore on the wsl i used for the execution of the python interpreter.

Later on VSC provided me the link for the update of the wsl that effectively got this problem, but the file is still missing.

Could you please give me some help to recover this file?

**Comment by Tyriar** [comment]
We have a hot exit feature that backs up files with changes only, you can see where we store backups if that's the case here: https://code.visualstudio.com/docs/editor/codebasics#_hot-exit

Other than that, you would need to deal with backups yourself either with some extension or by using an SCM like git.
