### ISSUE TITLE
Customized macro

### ISSUE THREAD

**Issue by Leon-Zhang** [microsoft/vscode#139504]
Hello, is it possible to make a macro that runs cmake.build command first and start debugging right after cmake.build finished? Thanks.

**Comment by IllusionMH** [comment]
Have you checked available params in docs https://code.visualstudio.com/Docs/editor/debugging#_launchjson-attributes ?

Looks like `preLaunchTask` is what you are looking for (when you add that script to tasks).

**Comment by weinand** [comment]
In your launch configuration (in `launch.json`) you can add the "cmake.build command" as a `preLaunchTask`.
Search for `preLaunchTask` in this section of VS Code's debugger documentation: https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes

**Comment by Leon-Zhang** [comment]
@IllusionMH @weinand Thanks for your answers.

But what I need is another customized command which able to lunch from F1 key dropdown list, just like cmake.build.
I don't need to run cmake.build every time I debug the program, so need to separate this customize command from debugging command.

**Comment by weinand** [comment]
you can use a macro extension, e.g.  https://marketplace.visualstudio.com/items?itemName=jeff-hykin.macro-commander
