### ISSUE TITLE
Tool-tip box with function information clips off the top sof characters

### ISSUE THREAD

**Issue by oscarrutt** [microsoft/vscode#139508]
Issue Type: <b>Bug</b>

When editing text and hovering the cursor over a function name, a pop-up box, like a tooltip, appears with helpful information about the function.

In normal text editors (not notebooks), the box touches the tops of the characters of text in the same line as the function name. In ipynb notebooks, it clips off the tops of the characters. In both cases, the text is hard to read while the box is open.

In either normal editors or notebooks, if the function name line is near the top of the screen, the box appears below the line of text and leaves a small space between the box and the bottom of the line of text, leaving the text easy to read.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 15.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 3, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
ada|Ada|23.0.1
Bookmarks|ale|13.2.2
pascal|ale|9.4.0
pascal-formatter|ale|2.6.0
project-manager|ale|12.4.0
octave-hacking|apj|0.2.12
vscode-svgviewer|css|2.0.0
vscode-mac-color-picker|dae|1.0.2
textpad-icon-theme|dam|1.19.21
vscode-markdownlint|Dav|0.45.0
ada-snippets|Ent|0.3.0
gc-excelviewer|Gra|4.0.45
vscode-lyx|gyt|0.0.4
latex-workshop|Jam|8.22.0
svn-scm|joh|2.15.2
language-julia|jul|1.5.6
keen-neutral-icon-theme|kee|1.0.8
octave|lea|0.1.1
eps-preview|mkv|0.3.0
python|ms-|2021.12.1559732655
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
postscript|mxs|1.0.1
vscode-json-editor|nic|0.3.0
vsc-octave-debugger|pau|0.4.23
bib|phr|0.3.0
ipf|qms|1.0.1
vscode-data-preview|Ran|2.3.0
markdown-preview-enhanced|shd|0.6.1
octave|toa|0.0.3
pdf|tom|1.2.0
debug|web|0.25.1
txt-syntax|xsh|0.2.0
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710cf:30405999
py55gd98:30411514
vscexrecpromp3t1:30407762

```

</details>

**Comment by rebornix** [comment]
@oscarrutt can you please share a screenshot or recording of what you are seeing? I think I know what's the issue you ran into but wanna confirm where it happens.

**Comment by oscarrutt** [comment]
Sorry for the delay. I hope this post re-opens the issue. Screen shots attached from both normal editor and ipynb cell editor. I would like to amend my original post because the clipping happens on both types of editors but perhaps not identically. Note also that the languages used here are different for each editor
[Screen shots for #139508.pdf](https://github.com/microsoft/vscode/files/7797303/Screen.shots.for.139508.pdf)
.
