### ISSUE TITLE
"Comments not permitted in JSON" with devcontainer.json

### ISSUE THREAD

**Issue by jkopczyn** [microsoft/vscode#139599]
The precreated `devcontainer.json` does not raise errors for containing comments, but creating any other file with the same structure does. E.G. storing multiple versions of the file in the tree (`./.devcontainer/devcontainer.json`, but also `./.devcontainer/alternate-specs/devcontainer.json` and/or `./.devcontainer/devcontainer.v1.json`, `./.devcontainer/devcontainer.v2.json`), so that it can be customized for later users, every comment line is marked as a problem.

Maybe there is a setting to disable this, but I cannot find it, so in that case I suggest making it more prominent in the documentation.

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
User Agent: Chrome/96.0.4664.110 (AppleWebKit/537.36 (KHTML, like Gecko) may also be relevant)
Embedder: codespaces

**Comment by aeschli** [comment]
Currently, we associate the filename `.devcontainer.json` and the file name pattern `"**/.devcontainer/devcontainer.json` to JSONC. If other names are common too, we can add these too. @chrmarti For you to decide.

Users can extend that list in the settings, e.g.
```json
  "files.associations": {
    "devcontainer*.json": "jsonc"
  },
```

**Comment by chrmarti** [comment]
We are doing this only for the supported filenames at the moment. I suggest to add the above config to your user settings.

**Comment by jkopczyn** [comment]
As I said originally, this needs to be much more visible in documentation.

**Comment by jkopczyn** [comment]
> We are doing this only for the supported filenames at the moment. I suggest to add the above config to your user settings.

@chrmarti, that's missing the point. As I said originally, this needs to be much more visible in documentation; there isn't anywhere in the docs that even mentions `"files.associations"` is an option. Something that only affects myself is _not a fix_.

**Comment by aeschli** [comment]
https://code.visualstudio.com/docs/languages/identifiers is the doc for `files.associations`.
https://code.visualstudio.com/docs/languages/json#_json-with-comments explains how to set JSONC for a file that isn't.
I'll add a sentence that links to the first one.
