### ISSUE TITLE
Cannot load iframe in Get Started page

### ISSUE THREAD

**Issue by zWingz** [microsoft/vscode#139500]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: https://github.com/microsoft/vscode/commit/7bd1a636f44c9f8199b1df2c09db8640b43b5aef

Steps to Reproduce:

1. clone vscode
2. run vscode server
3. open get started
4. change step

![image](https://user-images.githubusercontent.com/13031838/146739414-0883884d-eeec-4060-833a-f174825dd214.png)

![image](https://user-images.githubusercontent.com/13031838/146739335-f6d75b76-17ae-4cfb-93c0-cf486086191c.png)

[vscode.dev](https://vscode.dev/)
![image](https://user-images.githubusercontent.com/13031838/146739864-50f1a216-6877-404a-a8cb-79eed0547c63.png)

**Comment by JacksonKearl** [comment]
@mjbvz any idea what the error message there means? "port is already neutered"

**Comment by mjbvz** [comment]
@zWingz  Are you still seeing this in the latest code from main?
