### ISSUE TITLE
${workspaceFolder} not work as well

### ISSUE THREAD

**Issue by PowerDi** [microsoft/vscode#139561]
Does this issue occur when all extensions are disabled?: Yes/No
yes

- VS Code Version: 1.62.3
- OS Version: windows but remote coding is ubuntu16.04

The include file shows can not find. My c_cpp_properties.json is
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/modules/"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
``` 
That Vscode can find the include.h, however, Vscode can not find the include.h if I set
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/modules/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
``` 
This is abnormal, because when I use  ${workspaceFolder}/** want to include all the header file in the path. The Vscode shows many cant find problem. I am using Remote ssh on Ubuntu16.04.

BTW, there is another issue when the remote path is under symbolic link:
1.
```c++
ln -s myproject linkProject
\\open linkProject in Remote SSH
\\color parse error
```
2.
```c++
\\open myproject in Remote SSH
\\color parse right
```
[https://github.com/microsoft/vscode-cpptools/issues/8431#issuecomment-977165233](url)
Steps to Reproduce:

1.
2.

**Comment by sandy081** [comment]
Seems to be c++ extension related, please file the issue against that extension.
