### ISSUE TITLE
git Source Controll not working

### ISSUE THREAD

**Issue by sgMaddog** [microsoft/vscode#139598]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Running windows 11, (logged in and working or browsing, or just being logged in)
Wait until windows 11 logs you out, even with all the settings off.
then log back in.
open te source controll in vis code 
and read the god dam text "the folder currently open doesnt have a git repository. bla bla bla

tried re installing everything (even a clean windows install)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 3893)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (21.03GB free)|
|Process Argv|--crash-reporter-id 3d183588-a38b-41d1-b674-d674df552c62|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|13.1.0
npm-intellisense|chr|1.4.0
vscode-eslint|dba|2.2.2
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
vscode-jest-runner|fir|0.4.47
output-colorizer|IBM|0.1.2
git-graph|mhu|1.30.0
angular-console|nrw|17.13.4
vscode-versionlens|pfl|1.0.9
vscode-icons|vsc|11.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710cf:30416617
vscexrecpromp3t1:30407762

```

</details>

![Naamloos](https://user-images.githubusercontent.com/96444298/146997201-09cd0a71-e28c-47e4-bea3-42b24ae831cc.png)

**Comment by berezovskyi** [comment]
I am having the same issue. On a large folder with many repositories I get the same view as @sgMaddog. If I open a subfolder of that folder in VS Code, I see multiple repos. I just updated to the recent version. Is it possible there was some "efficiency" tweak made for larger folders that now disables git repo scanning? If so, how do I undo that flag?

**Comment by jameswilddev** [comment]
No less than ten minutes after pushing some commits I realized that VS Code lost the ability to interact with Git.  Using the built-in Git Clone functionality presents the error:

"Command 'Git: Clone' resulted in an error (command 'git.clone' not found)."

I have confirmed that I can `git status` within VS Code's own terminal, so something's definitely broken for me here.

```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z (1 wk ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```

**Comment by jameswilddev** [comment]
No less than ten minutes after pushing some commits I realized that VS Code lost the ability to interact with Git.  Using the built-in Git Clone functionality presents the error:

"Command 'Git: Clone' resulted in an error (command 'git.clone' not found)."

I have confirmed that I can `git status` within VS Code's own terminal, so something's definitely broken for me here.

```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z (1 wk ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```

**Comment by lszomoru** [comment]
@sgMaddog, @berezovskyi, are you able to reproduce the problem in the latest insiders release? Could you please open the repository in VS Code, then invoke the `Git:  Show Git Output...` command from the command palette and share the output. Could you also please share the folder structure of the workspace that you are opening related to the `.git` folder?

**Comment by lszomoru** [comment]
@jameswilddev, that seems unrelated to this issue. Do you mind opening a separate issue to track that? Thanks!

**Comment by michmerr** [comment]
Just updated from 1.62.something to 1.63.2, and several of my folders can no longer find their git repositories.

In each window I use open folder, and open each folder has the .git directory at the folder root. The most basic cloned repository there is. No nested projects or repos, just one repo under the root.

Any folder that did not have pending changes before the update does not detect the Git repository.

Any folder that had any changed files was still detecting the git repository after the update, but if I reverted the files or added them to the .gitignore, the SCM view would change to no-repo-detected mode. Making a change to a file did not cause the repo to be detected again, nor did reloading the folder. Once it stopped detecting the repository, that was it.

**Comment by michmerr** [comment]
I installed a Git extension to see if could add something that would raise an activation event for vscode.git. This seems to have worked, with vscode.git starting at the very end, listing the extension as the source of the event.

So it might be worth looking at the chain of activation events and root causes. In the logs from before I updated to 1.63, vscode.git was showing activationEvent: '*' and root cause: vscode.github, so perhaps something has changed with vscode.github.

**Comment by berezovskyi** [comment]
For the record: I have removed the following directories under `~/Library/ApplicationSupport/Code` and the Git repo discovery in a multi-repo project folder seems to work back again on the latest VS Code and no change in enabled extensions: 

- `Cache`
- `CachedDate`
- `CachedExtensions`
- `Code Cache`

**Comment by mediantiba** [comment]
I have the same issue. The only way to make it work is to use the `Git: Show Git Output...` command.

![Animation](https://user-images.githubusercontent.com/11060031/153481866-facbfc2b-5796-433e-93d3-3e8fda71d6e6.gif)

**Comment by lszomoru** [comment]
We have recently tracked down a bug in the extension activation log that has been fixed today - https://github.com/microsoft/vscode/issues/144518. Tomorrow's (2022-03-11) Insiders release should contain the fix. When it's released, could you please update to the latest Insiders release and see if you are still able to reproduce the problem? Thank you!
