### ISSUE TITLE
stuck on Administrator

### ISSUE THREAD

**Issue by PaiKai-Lee** [microsoft/vscode#139565]
Issue Type: <b>Bug</b>

My vscode always run as Adminstrator if even I didn't choose run as Adminstrator. And white bar on top.
How can I solve it.

![image](https://user-images.githubusercontent.com/76577188/146906165-e9ca256c-f6e5-48a7-adcc-3adeb9b10472.png)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by roblourens** [comment]
Is this the User or System vscode install?

Also you can change the titlebar style with this setting `window.titleBarStyle`

**Comment by PaiKai-Lee** [comment]
Thanks!! I remove the white bar style.

**Comment by roblourens** [comment]
What is the install location? What if you try uninstall and reinstalling?
