### ISSUE TITLE
Update extension hangs

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#1395]
1. Create a new extension with yo code (just a TypeScript basic extension.
2. Publish to the gallery
3. Install on VS Code
4. Update the extension version and republish to the gallery
5. Extensions: Show Outdated Extensions
6. You see that a new version of the extension is available.  Click Update extension.
The dropdown stays open with the Update extension button swirling.  It never stops.
If you change focus, the dropdown goes away but no Restart message comes up.
If you look under .vscode/extensions, the extension folder is still there containing just the node-modules folder and the .vsixmanifest files.

**Comment by gregvanl** [comment]
If you restart VS Code, the extension is not shown as installed.  
If you try to install the extension (new version) from the gallery, this also hangs and the extension is not installed.
It appears that the extension directory can't be removed and this blocks update and installation.

**Comment by gregvanl** [comment]
This issue repro's on both 0.10.3 and 0.10.4 releases.

**Comment by gregvanl** [comment]
The workaround is to uninstall the extension first (succeeds) then install the update.

**Comment by egamma** [comment]
This is a good test case for the update extensions improvements that will go into 0.10.5

**Comment by gregvanl** [comment]
This reproduces for simple extensions as well such as a theme with no code nor npm modules.  The .vsixmanifest file is the only thing left in the extension folder.

**Comment by egamma** [comment]
Reproduced on 0.10.4 and I can no longer reproduce this on 0.10.5.

**Comment by egamma** [comment]
Duplicate of #1111
