### ISSUE TITLE
Hover links no longer have pointer hand icon when hovering (back to default cursor)

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#139535]
In the current Insiders, the links within a hover no longer have the correct `cursor` style when hovering over them. Can't capture the mouse:

![image](https://user-images.githubusercontent.com/641685/146815757-7a3dd412-2f75-49ec-9e1f-cdb54603c9d7.png)

/cc @Tyriar @alexdima

**Comment by Tyriar** [comment]
Reproduces with regular links in symbol docs too

**Comment by Tyriar** [comment]
+ in custom workbench hover
