### ISSUE TITLE
git graph often crash when using vscode-insiders

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#139526]
Does this issue occur when all extensions are disabled?: Yes/No

版本: 1.64.0-insider (system setup)
提交: 807bf598bea406dcb272a9fced54697986e87768
日期: 2021-12-20T07:18:13.749Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22523

名称: Git Graph
ID: mhutchie.git-graph
说明: View a Git Graph of your repository, and perform Git actions from the graph.
版本: 1.30.0
发布者: mhutchie
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph

Steps to Reproduce:
1. open git graph
2. I don't know but It often crash

![image](https://user-images.githubusercontent.com/1876302/146796299-1ef238d0-b02b-468b-aa47-53368ada08fa.png)

**Comment by heartacker** [comment]
vscode stable works fine

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Please report to extension author in the first instance. If they think it is a 1.64 issue they should open an issue here with technical details.
