### ISSUE TITLE
webviews using hard-coded old style vscode-resource uri should work

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139572]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=147696&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=354d3e13-3534-5793-0b68-b00f8c1d36f3&l=607

1) vscode API - webview
       webviews using hard-coded old style vscode-resource uri should work:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\extensions\vscode-api-tests\out\singlefolder-tests\webview.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

**Comment by mjbvz** [comment]
Removed for now with #157155
