### ISSUE TITLE
I want to print the file  to my printer, will you help me?

### ISSUE THREAD

**Issue by afsoe** [microsoft/vscode#139546]
Issue Type: <b>Feature Request</b>

I want to print the file  to my printer (hard ware), will you help me? will you add a button???

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/5953
