### ISSUE TITLE
Have to type enter twice on terminal after punctuation and other special characters

### ISSUE THREAD

**Issue by fneto** [microsoft/vscode#139585]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows 10 21H1

Everytime a terminal command ends with punctuation or special characters like ? or ~ I have to hit enter twice, this happens on any terminal, like PowerShell or bash and zsh if I'm connected to my remote Ubuntu machine.

I trying experimenting with the settings but nothing I found fixed this.

**Comment by meganrogge** [comment]
does this also happen for you in external terminals? 

what are your settings? 

can you include a gif with screen capture toggled on?

**Comment by fneto** [comment]
This only happens with VScode terminal. The only setting I'm using for the terminal is this: "terminal.integrated.copyOnSelection": true, but I alteready tried without it and got the same problem.

Also, a coworker just tested it on his pc, and the same thing happens.

I'm sending a gif showing the behaviour on vscode (remote connected to ubuntu and locally using powershell), on Windows Powershell, and on another terminal(conemu running GitBash) I use with ssh. As you can see, this only happens on VSCode
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/401385/147250557-2b189761-6780-4b84-9809-8caff65e9945.gif)
.

**Comment by meganrogge** [comment]
thanks for that info. can you please turn on escape sequence logging and provide the logs when you see this issue?

**Comment by fneto** [comment]
I'm attaching the log file.

What I noticed is that when I type ENTER for the first time, it does not
log anything, only the second one that works.

-- 
Felício Moysés Neto


Em qua., 29 de dez. de 2021 às 00:11, Megan Rogge ***@***.***>
escreveu:
