### ISSUE TITLE
No way to skip debug breakpoint hit by extension (not launch by click debug button)

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#139501]
Version info:

I use https://marketplace.visualstudio.com/items?itemName=Adobe.extendscript-debug to debug ExtendScript. This debug extension will hit the breakpoint when run js function [app.scheduleTask()](https://github.com/bbb999/Types-for-Adobe/blob/master/AfterEffects/18.0/index.d.ts#L824) like following screenshot. 

If I launch debug by click debug button with launch.json, I can config skipFiles option. But this breakpoint is hit by extension, I have no way to skip for it.

I would like there is a setting like: 'debug.skipFiles` in settings.json.

![image](https://user-images.githubusercontent.com/41773861/146742262-44496545-35be-4a8e-ba8a-523ceffd56bd.png)

```
Version: 1.64.0-insider (Universal)
Commit: d12df34e31b4a018735d312a8947d79331132368
Date: 2021-12-17T05:14:21.805Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0
```

**Comment by tjx666** [comment]
@connor4312

**Comment by weinand** [comment]
Please file this against the "extendScript" extension
