### ISSUE TITLE
X shouldn't overlay text in intellisense completion widget

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#139580]
Maybe this has always been the case, but in my opinion it looks bad and initially I thought it was some rendering bug. I would expect that area to be reserved and then you scroll to reveal text from under it
<img width="333" alt="Screen Shot 2021-12-21 at 10 19 26 AM" src="https://user-images.githubusercontent.com/4544166/146954833-f464371b-5ac7-413d-9741-0da870011a2c.png">
.

**Comment by slidoooor** [comment]
@lramos15 hi, Which version are you using?

**Comment by jrieken** [comment]
@lramos15 Can you add some steps/details? With my testing I cannot reproduce this... According to the implementation there should be a padding and wrapping so that the x stays by itself

<img width="652" alt="Screen Shot 2021-12-23 at 16 16 06" src="https://user-images.githubusercontent.com/1794099/147259602-203a75ff-c7fb-42bd-809a-b9e6064206f6.png">

**Comment by lramos15** [comment]
Sorry for not providing enough details. I saw this when using the C# extension with Octokit. I am running the latest insiders. I haven't seen this with other extensions but I wouldn't expect this to be an extension issue as the widget should handle it.

<img width="830" alt="Screen Shot 2021-12-23 at 10 20 13 AM" src="https://user-images.githubusercontent.com/4544166/147260224-4ffeb07b-564c-419f-ba9e-1876195524c7.png">

**Comment by jrieken** [comment]
Thanks @lramos15. This happens when a completion item lacks detail but has a documentation property with a "header line"  atop

**Comment by lramos15** [comment]
<img width="870" alt="Screen Shot 2022-01-26 at 1 44 15 PM" src="https://user-images.githubusercontent.com/4544166/151226647-3b16fbe1-2311-4bc1-ab0d-0e29180a80f8.png">
It doesn't have the same rendering bug but the downside is that with overflow hidden you can't see the rest of the header so the templated string is cut off

**Comment by jrieken** [comment]
Yeah, but it was always cut off and you can resize that details pane.

**Comment by lramos15** [comment]
Well I used to be able to scroll using the horizontal scrollbar. I don't know if we want to do `overflow: scroll` instead or just leave it to resizing
