### ISSUE TITLE
Debug Console Fontsize

### ISSUE THREAD

**Issue by capegreg** [microsoft/vscode#139583]
Issue Type: <b>Bug</b>

Fontsize is very small at 14 (or 14.0). But at 14.1, fontsize is too big, nearly 2x larger. 

settings
"debug.console.fontSize": 14

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

![image](https://user-images.githubusercontent.com/1051118/146959377-112bfb0f-a11a-4680-a98b-e746d1bbeffb.png)

![image](https://user-images.githubusercontent.com/1051118/146959574-1ab17fd7-c5be-4b82-a327-11bb5c2ecf1e.png)

**Comment by roblourens** [comment]
What is the value you've set in User settings? I suspect you are modifying it from a smaller size than 14, up to 14.1.
