### ISSUE TITLE
Command 'Files: Save All' is not enabled in the current context.

### ISSUE THREAD

**Issue by danvk** [Microsoft/vscode#13955]
- VSCode Version: 1.6.1
- OS Version: Mac OS X 10.11.4

Steps to Reproduce:

1. Do something that modifies a bunch of files, e.g. renaming an exported variable.
2. Hit Cmd-P then do "Files: Save All"

This produces the error `Command 'Files: Save All' is not enabled in the current context.`.

I'm not sure if this has anything to do with the rename, but I would like to save all the modified files. If nothing else, the error is cryptic. (What's the "current context"?)

**Comment by roblourens** [comment]
Do you have autosave enabled? You would see that if no files were actually dirty

**Comment by danvk** [comment]
Nope, no autosave. There were 4-5 dirty files after I renamed my exported TypeScript symbol.

**Comment by roblourens** [comment]
Does the 'save all' icon work? In the sidebar, by "Open editors"

**Comment by danvk** [comment]
It does. And oddly, the command does now, too. So I'm unable to reproduce. I'll close out for now. I'll report back if I run into this again.

Thanks for the help!
