### ISSUE TITLE
TypeScript Language Service continously dies

### ISSUE THREAD

**Issue by omirobarcelo** [microsoft/vscode#139590]
Issue Type: <b>Bug</b>

When opening an Nx Angular/Nest project, the TypeScript Language Service continuously dies. 
Before this was an annoyance, but the IDE still worked more or less as intended.
Since the Windows 10 system updates for 2021-12-18/19 and the VS Code update for 2021-12-20, the intellisense is not working anymore.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.59GB (0.60GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/dev/repos/Electry/Talentfinder --remote=wsl+Ubuntu-20.04 --crash-reporter-id d1f6337d-894e-4765-91e8-fc35f1ead06e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|12.16GB (5.15GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
remote-wsl|ms-|0.63.13
material-icon-theme|PKi|4.11.0
ng-template|Ang|13.1.0
angular-schematics|cyr|5.1.1
gitlens|eam|11.7.0
prettier-vscode|esb|9.0.0
vscode-jest-runner|fir|0.4.47
vscode-docker|ms-|1.18.0
vscode-typescript-tslint-plugin|ms-|1.3.3
angular-console|nrw|17.13.4
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.2
git-merger|sha|0.4.1
autoimport|ste|1.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30414009
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710:30416614
vscexrecpromp3c:30407761

```

</details>

**Comment by preIdiot** [comment]
I am having this issue too.
 `The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.`

**Comment by cameliaben** [comment]
I am having the same issues and could not figure out a way yet to bring Vs Code Intellisense back to life. VS Code version: Code 1.63.2 , System: macS Big Sure v11.6.2.

**Comment by cameliaben** [comment]
I was finally able to get Intellisense back while using the Vs Code Insiders version - https://code.visualstudio.com/insiders/ .

**Comment by mjbvz** [comment]
@omirobarcelo Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
