### ISSUE TITLE
"disabled" key in json textmate language does not work

### ISSUE THREAD

**Issue by RedCMD** [microsoft/vscode#139510]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows 10

`"disabled": 1` key does not work

Steps to Reproduce:

1. Create a TextMate Language based syntax highlighting extension
2. Try to disable a rule by adding the key '"disabled": 1' to it
notice how the rule is still enabled

If this key is deprecated, then a bug report should be made to https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json as it still supports the "disabled" key

![image](https://user-images.githubusercontent.com/33529441/146751588-91264ae2-f085-4056-afec-ee56a4a764d3.png)

**Comment by aeschli** [comment]
[vscode-textmate](https://github.com/Microsoft/vscode-textmate) implementation does not support the `disabled` property. Maybe other textmate engines do. I don't know the history of it. Do you know more?

Either way the issue should be filed against https://github.com/martinring/tmlanguage or https://github.com/Microsoft/vscode-textmate
