### ISSUE TITLE
Start tsserver with noEmit

### ISSUE THREAD

**Issue by xymopen** [microsoft/vscode#139505]
Issue Type: <b>Bug</b>

There is a similar issue #70014 but feel like it is necessary to reopen it

Steps to Reproduce:

1. Create an empty folder and open it with VSCode
2. Create `tsconfig.json`

  ```json
  {
  	"compilerOptions": {
  		"allowJs": true,
  	},
  	"include": [
  		"./main.js",
  	]
  }
```
3. Create empty `main.js`

VScode would show an error in `tsconfig.json` saying`Cannot write file 'path/to/main.js' because it would overwrite input file` . Following #70014 and adding `outDir: path/to/out ` or  `noEmit: true` could shutdown that error. However, this doesn't make sense to me because:

1. `--outDir` could be add to `tsc` build script
2. If a bundler such as `webpack` is used, it would take care how emitted content should be processed

In neither cases should it prevent VSCode from linting JS files.

IMO, as linting itself doesn't actually emit files, we could start `tsserver` with `noEmit: ture` to solve this issue.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700G with Radeon Graphics          (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|59.88GB (34.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
scriptbox|cub|2.0.1
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
copilot|Git|1.7.4421
gitlab-workflow|Git|3.40.0
rest-client|hum|0.24.6
svg|joc|1.4.14
vscode-codemetrics|kis|1.24.0
vscode-language-pack-zh-hans|MS-|1.63.3
anycode|ms-|0.0.53
github-issues-prs|ms-|0.9.3
hexeditor|ms-|1.8.2
live-server|ms-|0.2.11
powershell|ms-|2021.10.2
vscode-github-issue-notebooks|ms-|0.0.113
vscode-js-profile-flame|ms-|0.0.21
vscode-markdown-notebook|ms-|0.0.26
vscode-sanddance|msr|3.3.0
vetur|oct|0.35.0
rust|rus|0.7.8
vscode-stylelint|sty|1.2.1
vscodeintellicode|Vis|1.2.15
vscode-todo-highlight|way|1.0.5
browserslist|web|1.1.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a bug upstream](https://github.com/microsoft/TypeScript/issues)

**Comment by mjbvz** [comment]
Although this is likely by-deign now that I think about it a bit more. TS Server has no way of knowing you will use `--noEmit` so it shows an error assuming you will just run `tsc` directly. This is correct in the majority of use cases

Just add `"noEmit": true` in the tsconifig to suppress this

**Comment by xymopen** [comment]
Does Typescript team also maintain the [typescript-language-features](https://github.com/microsoft/vscode/tree/main/extensions/typescript-language-features) plugin? It seems to me that the plugin could override these `tsconfig` settings when starting `tsserver`.

would like to dig it deep if have some time.

Thanks in advance.
