### ISSUE TITLE
AutoSave

### ISSUE THREAD

**Issue by moshodi** [microsoft/vscode#139569]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. When I have my autosave feature on and I tried to copy and paste some JavaScript code. The code automatically scattered and was not the same format that I copy and pasted it in. When I turned the autosave off, I was able to copy and paste the code in the same format as I pulled it from the Internet
2.

**Comment by jrieken** [comment]
Do you use format on save?
