### ISSUE TITLE
Mouse wheel events ignored moving mouse

### ISSUE THREAD

**Issue by BttCld** [microsoft/vscode#139525]
Issue Type: <b>Bug</b>

Move the mouse horizontally or vertically and at the same time turn the wheel. I guess the wheel events are ignored as the page doesn't scroll.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.4.0-91-generic
Restricted Mode: No

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/84136
