### ISSUE TITLE
JSX syntax highlighting is broken after stacking destructured constants in component.

### ISSUE THREAD

**Issue by mndewitt** [Microsoft/vscode#13956]
- VSCode Version: 1.6.1
- OS Version:  OSX El Capitan (10.11.6)

Steps to Reproduce:

1. Stack a destructured object at the top of the `render()` method in a React component.
2. Write some JSX in the `return()` block of the render method.  The JSX will be mostly orange, as opposed to having a distinction between elements and attributes like one would expect:

![badhighlighting](https://cloud.githubusercontent.com/assets/7085141/19491351/3d3fad66-9538-11e6-8c2c-a1db81f4103e.png)

Sample code to reproduce:

```javascript
export class Test extends Component {
  render () {
    const {
      test,
      test2,
      test3 } = this.props

    return (
      <div className={test}>
      </div>
    )
  }
}
```

**Comment by aeschli** [comment]
This seems to be fixed with the new JavaScript grammar.
![image](https://cloud.githubusercontent.com/assets/6461412/19508985/795ab850-95dc-11e6-8090-96d2342e6216.png)
