### ISSUE TITLE
status bar

### ISSUE THREAD

**Issue by Yitshak770** [microsoft/vscode#139516]
Issue Type: <b>Feature Request</b>

most informations doesn't appear in status bar

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
![image](https://user-images.githubusercontent.com/96015515/146762082-d8cb2e67-7b35-44a8-bb41-b6f06d7f8f4f.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide information about what information is expected but not available there.
Also have you tried to do right click on status bar and see if that items are just hidden.

**Comment by Yitshak770** [comment]
> /needsMoreInfo
> 
> Please provide information about what information is expected but not available there. Also have you tried to do right click on status bar and see if that items are just hidden.

added

**Comment by IllusionMH** [comment]
Do you have workspace(folder) opened? Is it trusted workspace?

For this one - do you have Git repo initialized in folder that is opened?

I see similar picture when I open new window with no workspace selected.

**Comment by Yitshak770** [comment]
Git clone was not initialized in this folder - thanks for the help
