### ISSUE TITLE
VSCode is using a lot of the CPU on this Mac with the CPP extension

### ISSUE THREAD

**Issue by brennanMKE** [Microsoft/vscode#13958]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 15.6.0
- Extensions: Kasik96.swift-0.0.2, Orta.vscode-ios-common-files-1.0.2, TimonVS.ReactSnippetsStandard-1.0.3, TwentyChung.jsx-0.0.1, alechp.react-toolbox-snippets-0.12.0, cdsama.shell-snippets-0.1.2, dbaeumer.vscode-eslint-1.0.8, donjayamanne.githistory-0.1.0, dzannotti.vscode-babel-coloring-0.0.4, eg2.tslint-0.5.39, flowtype.flow-for-vscode-0.3.3, gllwy.theme-dusk-0.0.7, groksrc.ruby-0.0.6, kube.ClangComplete-0.0.4, mitaki28.vscode-clang-0.2.1, ms-vscode.cpptools-0.9.2, ornithologist.ios-snippets-0.0.15, rebornix.Ruby-0.9.0, redhat.java-0.0.5, robertohuertasm.vscode-icons-3.0.5, rtorr.vscode-flow-276.3.0, vsmobile.vscode-react-native-0.2.0, waderyan.babelrc-1.0.0, xabikos.ReactSnippets-1.2.0

It appears to be related to `Microsoft.VSCode.CPP.Extension.darwin` and `parentalcontrolsd`. When I run VSCode the CPU is used heavily and the fan makes a lot of noise. This is happening just recently when I started using VSCode with C code. Specifically I am viewing code for the `pjsim` project on GitHub. Perhaps loading up that project on a Mac (El Capitan) with VSCode will be a way to reproduce the problem.

Steps to Reproduce:

1. Clone `pjsim` project from GitHub https://github.com/chakrit/pjsip
2. Open that folder with VSCode
3. Install the recommended plugins for C/C++
4. Restart VSCode
5. Wait for the CPP plugins to wreak havoc on all that is good and holy

It appears to not cause any trouble without the recommended CPP plugins. The Microsoft CPP and Clang plugins for C/C++ have been downloaded a lot and have high ratings so I expected them to be alright.

One potentially important detail is that I am running a beta release of Xcode (8.1 beta 3) and have that path selected with `Xcode-select`. If that is somehow the cause for this trouble it would be best to resolve it before the final 8.1 release is out.

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-cpptools#297
