### ISSUE TITLE
Background artifacts in VS 1.6.1 and OS X Sierra

### ISSUE THREAD

**Issue by connor4312** [Microsoft/vscode#13959]
- VSCode Version: 1.6.1
- OS Version: OS X 10.12 Sierra

Steps to Reproduce:

1. Open a file in VS code with the [Earthsong Theme](https://peet.io/i/Earthsong.tmTheme)
2. View [background artifacts](https://peet.io/i/16-10-rgmq4262qvsqlhiw4x0i6lblq0ll0j.mp4)

Note:

This did not occur prior to my rebooting for the Sierra upgrade, which allowed vscode to upgrade when the app was restarted. Probable cause is something in 1.6.0 -> 1.6.1 or Sierra itself.

**Comment by roblourens** [comment]
This is an issue with electron that we're tracking - #12473
