### ISSUE TITLE
Terminal On Windows - Resizing Issues

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#139509]
I think @Tyriar already mentioned that resizing the Terminal on windows causes problems, but I still wanted to report any weird behavior for the sake of completeness.

As you can see, characters disappear when you resize the terminal. Since the terminal resizes when the VS Code window resizes, this actually happens quite often.

![recording](https://user-images.githubusercontent.com/2931520/146750956-17861fb4-1569-4ff5-9092-dcc297cd1cb1.gif)

**Comment by Tyriar** [comment]
I haven't seen this particular behavior, could you enable escape sequence logging via command palette next time you see it and paste in the output when resizing? Also, could you provide Windows version details?

**Comment by hediet** [comment]
I was on vacation. Happy new year ;)
