### ISSUE TITLE
Large json import in .js file causes 100% CPU + autocomplete stops working

### ISSUE THREAD

**Issue by jfrancos** [microsoft/vscode#139532]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: macOS 11.6.2

Steps to Reproduce:

1. Put a large json file in a directory, e.g. `data.json` (mine is 2 MB)
2. Edit a file in the same directory, e.g. `index.js`
3. Add `import data from './data.json'` to the top of the file
4. CPU jumps to 100% (but VS Code is mostly still usable)

If I comment the `import` and then reload the window, CPU goes back to normal

Some other stuff that coincides with this:
If I reload the window with the `import` *uncommented*:
1. CPU goes up right away
2. Semantic styling is slightly off e.g. unused variables are not darkened
3. After about a minute, semantic styling corrects itself, and at the same time all autocomplete suggestions stop working.

(Autocomplete not working is the main thing making life difficult)

Some stuff I've tried, but did not help:
```
{
  "files.watcherExclude": {
    "**/*.json": true,
    "**/src/data/**": true
  },
  "search.exclude": {
    "**/src/data/**": true,
    "**/data/**": true
  },
  "npm.exclude": "**/src/data/**",
  "timeline.excludeSources": ["**/src/data/**"],
  "editor.unicodeHighlight.ambiguousCharacters": false,
  "json.maxItemsComputed": 50,
  "workbench.settings.enableNaturalLanguageSearch": false,
  "editor.wordBasedSuggestions": false
}
```

Happy to provide any other info.

**Comment by jfrancos** [comment]
Hi,

I added the following to a jsconfig.json at the root of my project, and that fixed it:
```
{
  "exclude": ["**/src/data/**"]
}
```

Maybe there's a useful place to document this?  (I only figured it out with some help on [reddit](https://www.reddit.com/r/vscode/comments/rkr7n5/large_es6_import_causes_100_cpu_and_autocomplete/hpborjg/?utm_source=reddit&utm_medium=web2x&context=3)).  Otherwise feel free to close this.

**Comment by mjbvz** [comment]
Can you please share a minimal example project that demonstrates this issue so we can investigate?
