### ISSUE TITLE
Signed out every day from Setttings Sync (Microsoft)

### ISSUE THREAD

**Issue by IT-CASADO** [microsoft/vscode#139563]
Does this issue occur when all extensions are disabled?: Cannot answer this, because I cannot work without extension a full work day.

- VS Code Version: 1.63.2
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Sign in to Sync Settings and Live-Share (both with Microsoft)
2. Use VS Code as normal
3. Go to bed and sleep
2. On next day open again VS Code -> you have again to sign-in to enable settings sync (and Live-Share)

In the past I had much trouble with Settings Sync. E.g. I noticed this #133201 the last month nearly every day.
I didn't notice that the last 2 or 3 weeks. 

But now I'm logged off every day or so and need to sign-in again:

<img width="339" alt="image" src="https://user-images.githubusercontent.com/2911693/146894473-44be1ce2-7ffc-46bb-87e3-b8256fbc4c29.png">

In output of **Microsoft Authentication** the following is reported:

[Info  - 07:48:57.918] Reading sessions from keychain...
[Error  - 07:48:59.309] Getting token failed: Error: Decryption failed
[Info  - 07:48:59.320] No stored sessions found.
[Info  - 07:48:59.398] Getting sessions for openid,profile,email,offline_access...
[Info  - 07:48:59.398] Got 0 sessions for email,offline_access,openid,profile...
[Info  - 07:49:03.528] Getting sessions for 0ced2f92-e1f8-45a1-a53a-0198e83410c2/all,email,offline_access,openid...
[Info  - 07:49:03.528] Got 0 sessions for 0ced2f92-e1f8-45a1-a53a-0198e83410c2/all,email,offline_access,openid...

**Comment by IT-CASADO** [comment]
signed-in this morning and 12 hours later I'm yet again signed-out from settings sync - but not from Live-share.

<img width="359" alt="image" src="https://user-images.githubusercontent.com/2911693/146995683-bf110cbb-e667-45e7-97f5-dc8c235460f5.png">

In output of Microsoft Authentication the following is reported (1 error):

[Info  - 20:37:48.212] Reading sessions from keychain...
[Info  - 20:37:49.602] Got stored sessions!
[Trace  - 20:37:49.602] Read the following session from the keychain with the following scopes: 0ced2f92-e1f8-45a1-a53a-0198e83410c2/all email offline_access openid
[Info  - 20:37:49.602] Refreshing token for scopes: 0ced2f92-e1f8-45a1-a53a-0198e83410c2/all email offline_access openid
[Trace  - 20:37:49.602] Read the following session from the keychain with the following scopes: email offline_access openid profile
[Info  - 20:37:49.602] Refreshing token for scopes: email offline_access openid profile
[Info  - 20:37:50.126] Setting token for scopes: email offline_access openid profile
[Trace  - 20:37:50.126] storing data into keychain...
[Info  - 20:37:50.141] Token refresh success for scopes: email offline_access openid profile
[Error  - 20:37:50.217] Unexpected token  in JSON at position 0
[Info  - 20:37:50.217] Failed to fetch token claims from access_token. Attempting to parse id_token instead
[Info  - 20:37:50.217] Setting token for scopes: 0ced2f92-e1f8-45a1-a53a-0198e83410c2/all email offline_access openid
[Trace  - 20:37:50.217] storing data into keychain...
[Info  - 20:37:52.170] Token refresh success for scopes: 0ced2f92-e1f8-45a1-a53a-0198e83410c2/all email offline_access openid
[Info  - 20:37:55.336] Getting sessions for openid,profile,email,offline_access...
[Info  - 20:37:55.336] Got 1 sessions for email,offline_access,openid,profile...
[Info  - 20:37:55.336] Token available from cache (for scopes email offline_access openid profile), expires in 5046790 milliseconds
[Info  - 20:37:55.832] Getting sessions for 0ced2f92-e1f8-45a1-a53a-0198e83410c2/all,email,offline_access,openid...
[Info  - 20:37:55.832] Got 1 sessions for 0ced2f92-e1f8-45a1-a53a-0198e83410c2/all,email,offline_access,openid...
[Info  - 20:37:55.832] Token available from cache (for scopes 0ced2f92-e1f8-45a1-a53a-0198e83410c2/all email offline_access openid), expires in 4562385 milliseconds
[Info  - 20:37:59.787] Getting sessions for all scopes...
[Info  - 20:37:59.787] Got 2 sessions for all scopes...
[Info  - 20:38:03.376] Getting sessions for all scopes...
[Info  - 20:38:03.376] Got 2 sessions for all scopes...
[Info  - 20:40:02.556] Getting sessions for all scopes...
[Info  - 20:40:02.556] Got 2 sessions for all scopes...
[Info  - 20:40:54.755] Getting sessions for all scopes...
[Info  - 20:40:54.755] Got 2 sessions for all scopes...
[Info  - 20:41:20.232] Getting sessions for all scopes...
[Info  - 20:41:20.232] Got 2 sessions for all scopes...

**Comment by jimcroft** [comment]
I'm having the exact same issue (including logs about failed token decryption and bad character in json), and have done since 1.63.0. Running Windows 11 Pro x64 (10.0.22000)

**Comment by jonathan-kostet** [comment]
I also have this issue on Windows 10. AFAIK the issue does not appear when using my GitHub account.

**Comment by TylerLeonhardt** [comment]
Are any of you switching between WSL and Windows?

I'm suspicious of https://github.com/microsoft/vscode/issues/135934

**Comment by TylerLeonhardt** [comment]
Also can you all share the logs of Settings Sync as well? You'll see it in the Output drop down.

**Comment by IT-CASADO** [comment]
No

**Comment by jonathan-kostet** [comment]
I do use WSL for some things, and I also have two Microsoft accounts logged into Windows.

**Comment by jonathan-kostet** [comment]
And I either get a `Getting token failed: Error: Decryption failed` or `Unexpected token � in JSON at position 0` every time I open a new vscode window.

**Comment by IT-CASADO** [comment]
Yesterday signed in, this morning signed out. I restartet my laptop over night, so VS Code was not running....

**Output for "Microsoft Authentication"**
[Info  - 07:07:33.571] Reading sessions from keychain...
[Error  - 07:07:34.863] Getting token failed: Error: Decryption failed
[Info  - 07:07:34.882] No stored sessions found.
[Info  - 07:07:34.955] Getting sessions for openid,profile,email,offline_access...
[Info  - 07:07:34.955] Got 0 sessions for email,offline_access,openid,profile...
[Info  - 07:15:28.931] Getting sessions for all scopes...
[Info  - 07:15:28.931] Got 0 sessions for all scopes...
[Info  - 07:15:32.922] Getting sessions for all scopes...
[Info  - 07:15:32.922] Got 0 sessions for all scopes...

Output for "Log(Settings Sync)"
[2022-01-20 08:07:32.074] [settingssync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2022-01-20 08:07:32.074] [settingssync] [info] Auto Sync is enabled.
[2022-01-20 08:07:32.074] [settingssync] [info] Auto Sync: Suspended until auth token is available.


PS: Output info is from the same time! It seems that first one is in local time and the latter in UTC...

**Comment by TylerLeonhardt** [comment]
@IT-CASADO can you share what extensions you have installed?

**Comment by IT-CASADO** [comment]
Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.3
ng-template|Ang|13.2.2
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.2.0
angular-essentials|joh|12.0.0
Angular2|joh|12.0.0
vscode-peacock|joh|4.0.0
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.19.0
csharp|ms-|1.24.0
remote-containers|ms-|0.217.1
powershell|ms-|2021.12.0
test-adapter-converter|ms-|0.1.5
vsliveshare|ms-|1.0.5330
angular2-inline|nat|0.0.17
angular-console|nrw|17.14.1
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.12.1
vscode-sort-json|ric|1.20.0
sonarlint-vscode|Son|3.2.0
errorlens|use|3.4.1
vscodeintellicode|Vis|1.2.17
vscode-conventional-commits|viv|1.24.0
wallaby-vscode|Wal|1.0.325
JavaScriptSnippets|xab|1.8.0

**Comment by IT-CASADO** [comment]
BTW: I don't seeing automatic sign-outs in the last days (this week). I will watching this....

**Comment by TylerLeonhardt** [comment]
Glad to hear it @IT-CASADO! If you getthe latest insider build of VS Code: http://code.visualstudio.com/insiders that has even more of my auth fixes which won't ship until next month.

I'm going to close this since we're in a "wait and see" but if you see the issue again, don't hesitate to comment here or open a new issue.
