### ISSUE TITLE
Opt in to pre-release versions when installing an extension with `installPreReleaseVersion` flag

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#139528]
When installing an extension using the command `workbench.extensions.installExtension` by passing the `installPreReleaseVersion` flag should opt into pre-release even if the latest version of the extension is not a pre-release. 

`vscode.commands.executeCommand("workbench.extensions.installExtension", "github.vscode-pull-request-github", { installPreReleaseVersion: true });`

**Comment by isidorn** [comment]
fyi @Colengms so you get pinged when we tackle this. Thanks

**Comment by rchiodo** [comment]
Adding myself so I get pinged when this is fixed too.

**Comment by Colengms** [comment]
@sandy081 Could you confirm that users will also be opted in to pre-release versions when a prerelease VSIX is manually installed?

**Comment by sandy081** [comment]
Yes, but only if the version of the VSIX is a pre-release version and the user has to be connected to the internet while VSIX is being installed - because while installing VS Code queries Marketplace to get this information.
