### ISSUE TITLE
auto completion of braces in typescript files

### ISSUE THREAD

**Issue by Martin-Andersen** [Microsoft/vscode#13952]
- VSCode Version: 1.6
- OS Version: macOS sierra

Love VSCode but I am missing some intellisense from R#
When I type myClass. I get list of members. when I choose one and tab it would be nice if VSCode could add braces.

Behaviour today: myClass.showNextPage
desired behaviour: myClass.showNextPage();
If there are parameters place the cursor between the braces. else at the end of the line

**Comment by roblourens** [comment]
Personally, I like the current behavior because I am sometimes not calling a function, but passing it to another function or something else. But worth thinking about.

**Comment by mjbvz** [comment]
For TypeScript, try adding `"typescript.useCodeSnippetsOnMethodSuggest": true ` to your settings. I believe this will enable the behavior you asking for:

![dec-01-2016 17-30-10](https://cloud.githubusercontent.com/assets/12821956/20819830/d2fde7b6-b7eb-11e6-84bc-3273ecfe96d2.gif)


There seems to be a bug that prevents this setting from working with JavaScript files. I'll sent out a PR to fix this shortly.
