### ISSUE TITLE
Environment Issue

### ISSUE THREAD

**Issue by DevBhargav9669** [microsoft/vscode#139558]
Issue Type: <b>Feature Request</b>

I am a trainee. I started learning blockchain developer course through cognitive classes collaborated by IBM and following their tutorials I tried downloading and start the embedded instance of Hyper ledger Fabric, but it shows that the environment failed to become available and notified me to check the docker container logs for more details. But I couldn't find any such. Please guide me on this issue.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by weinand** [comment]
This is not a VS Code issue. Please ask the authors of "Hyper ledger Fabric" or the "blockchain developer course" for help.
