### ISSUE TITLE
reveal file on sidebar with absolute path 

### ISSUE THREAD

**Issue by MiniSoda** [microsoft/vscode#139562]
Issue Type: <b>Bug</b>

I’m experiencing some confusion with the absolute/relative path here.

I’m working with windows visual studio code +  ssh remote(to Debian server) + clangd.
My build system is CMake + ninja for C++.

The compile_commands.json is something like:
{
  "directory": "/home/jiazhe/sandbox/workplace/build/target",
  "command": “it’s too long and irrelevant”,
  "file": "/home/jiazhe/sandbox/workplace/source/applications/board/src/board.cpp"
}
My _workspaceFolder_ , in this case, is /home/jiazhe/sandbox/workplace
When go-to definition, clangd is behaving right to retrieve absolution path,
But if I want to reveal file in a side bar, it is required to use a relative path like:
source/applications/board/src/board.cpp

How can I mitigate this problem?

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 4.19.0-10-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.03GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bbei01/home/jiazhe/sandbox/workplace --crash-reporter-id 50dc03af-3229-4cc3-9f1a-ac25a9698291|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: bei01|
|OS|Linux x64 4.19.0-10-amd64|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (16 x 2095)|
|Memory (System)|31.41GB (4.13GB free)|
|VM|100%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
thrift|cdu|0.0.1
arm|dan|1.5.2
LogFileHighlighter|emi|2.13.0
better-cpp-syntax|jef|1.15.10
vscode-valgrind|kro|0.0.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
ninja|sur|0.0.1
Bookmarks|ale|13.2.2
json-tree-view|Cha|2.6.0
gitlens|eam|11.7.0
svn-scm|joh|2.15.2
vscode-clangd|llv|0.1.13
mongodb-vscode|mon|0.7.0
vscode-docker|ms-|1.18.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
cpptools|ms-|1.7.1
text-power-tools|qcz|1.30.0
partial-diff|ryu|1.4.3
cmake|twx|0.0.17
docker|vsc|1.0.0
yaml|vsc|1.0.0
clang-format|xav|1.9.0

</details>

**Comment by JacksonKearl** [comment]
> But if I want to reveal file in a side bar, it is required to use a relative path like:
source/applications/board/src/board.cpp

Could you expand on what you mean by this? It may be helpful to provide a screen recording of the issue.

\gifPlease
