### ISSUE TITLE
Refactoring pane: wierd selection box focus behaviour

### ISSUE THREAD

**Issue by Dromantor** [microsoft/vscode#139519]
Only cpp extension active which is needed for refactoring.

Steps to Reproduce:
1. Refactor any (c? didn't test other languages) code that brings up said pane and tick some boxes.

Result:
- Look at that focus box around the selection boxes.
![wierd_behaviour](https://user-images.githubusercontent.com/1822013/146762074-f863baf4-4bb4-4c3a-b2e4-901158349b3d.gif)

- VS Code Version: 1.63.2
- OS Version: Win10 21H1 19043.1415

**Comment by misolori** [comment]
@jrieken I think this follows the same pattern in the the breakpoints view, though it also appears to react differently in the settings gui:

https://user-images.githubusercontent.com/35271042/148124743-6e7d1c82-a2f8-4d0d-b0d5-9c75f136641c.mp4

**Comment by joaomoreno** [comment]
We could do a better job at reusing templates for renders.

**Comment by joaomoreno** [comment]
**Verification**

1. Open Debug view
2. Click the `Caught Exceptions` breakpoint checkbox

🐛 The `Uncaught Exceptions` breakpoint checkbox is now focused. It shouldn't be.

![Recording 2022-01-24 at 16 00 58 (1)](https://user-images.githubusercontent.com/22350/150807373-becd673f-b3b3-4e97-adf4-76a9d5c424ae.gif)
