### ISSUE TITLE
Github authentication getting forbidden

### ISSUE THREAD

**Issue by abhijeet-1110** [microsoft/vscode#139566]
Hi Team,

I am unable to authorize the GitHub authentication.It is getting 403 forbidden after clicking the authorize button.

![Screenshot from 2021-12-21 15-40-50](https://user-images.githubusercontent.com/69045486/146912904-2a9dcc89-2008-41f8-ac75-95da13fdb8ab.png)
![Screenshot from 2021-12-21 15-41-34](https://user-images.githubusercontent.com/69045486/146912900-32b320bd-a774-4378-ad15-c171d4f7b073.png)
![Screenshot from 2021-12-21 15-41-42](https://user-images.githubusercontent.com/69045486/146912897-69ca5a8d-a41f-4d29-8a7a-f99919d3a908.png)

**Comment by TylerLeonhardt** [comment]
I notice that you're connecting to an instance of VS Code running on 0.0.0.0.

This is why it doesn't work. 

The good news is, I just fixed this so it will work in the next stable build of VS Code. It already works in the current insiders version of VS Code.

Of course with all that said, I have one more question. How did you get vscode running on 0.0.0.0?

**Comment by abhijeet-1110** [comment]
using docker i am running on 0.0.0.0

**Comment by TylerLeonhardt** [comment]
Can you share the Dockerfile? I see you're running VS Code server out of sources. If you run with the latest source, you should get a different auth flow.

**Comment by filiptronicek** [comment]
@TylerLeonhardt the one @abhijeet-1110 is using is most likely this one: https://github.com/gitpod-io/openvscode-releases/blob/main/Dockerfile (they reported the issue to us first) and a couple of minutes ago I released the new [insiders Docker image](https://hub.docker.com/r/gitpod/openvscode-server/tags?page=1&name=insiders), so this should be fixed. 

@abhijeet-1110 could you please confirm this is no longer an issue?

**Comment by abhijeet-1110** [comment]
Yes @filiptronicek we are using gitpod docker file

**Comment by TylerLeonhardt** [comment]
I'll go ahead and close this since it's already addressed
