### ISSUE TITLE
Terminal: Underline on Hover Is Inconsistent & Column/Line are not considered when jumping to source

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#139513]
When hovering on path, the path is underlined.
However, when hovering on the path extension, only the line number is underlined.
When hovering on the line number, the column number is underlined:

![recording](https://user-images.githubusercontent.com/2931520/146755798-db07c89b-0856-4af6-9351-d3facd9850d7.gif)

Also, when clicking on the path, the column/line numbers are not taken into account. The file is opened in the editor, but the cursor does not jump to the specified column/line number.

**Comment by Tyriar** [comment]
That is a supported format so need to investigate (path)(line,col): https://github.com/microsoft/vscode/blob/f880c417dad6ef7571bfbc80e3d4c746a6478b07/src/vs/workbench/contrib/terminal/browser/links/terminalValidatedLocalLinkProvider.ts#L41

I can also reproduce the weird offset thing going on.

**Comment by Tyriar** [comment]
Actually, the link requires ctrl meaning the regex isn't working and it's falling back to "word" links, so the offset is probably specific to word links.

**Comment by Tyriar** [comment]
Validated links regressed in https://github.com/microsoft/vscode/pull/139136, the offset problem applies to validated links and word links.

**Comment by Tyriar** [comment]
Offset problem was caused by how we changed padding handling recently: https://github.com/xtermjs/xterm.js/issues/3579
