### ISSUE TITLE
Ctrl+C in command line closes VS Code

### ISSUE THREAD

**Issue by aldonunez** [microsoft/vscode#139605]
Issue Type: <b>Bug</b>

I can still repro this bug that I originally reported in https://github.com/microsoft/vscode/issues/126101, which was closed automatically, despite providing all of the requested information.

Steps:

1. Run cmd
2. In cmd, run code
3. In the same instance of cmd, press Ctrl+C.

It doesn't matter whether you press Ctrl+C right away, or after running an internal command like dir, or even inside another program running in cmd like python. Nor does it matter whether you run cmd inside Powershell.

This problem also happens directly in Powershell. But in this case, it happens only while Powershell executes a command. For example, when you press Ctrl+C during `dir -re C:\Windows`

More information:
I didn't change any key bindings. I can reproduce this from three machines that I had recently installed VS Code on. The path to `code` is `C:\Users\Aldo\AppData\Local\Programs\Microsoft VS Code\Code.exe`

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (17.70GB free)|
|Process Argv|--crash-reporter-id 82ea55cd-129d-454d-b53c-333ece78a72e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30416617
vscexrecpromp3t1:30407762

```

</details>

**Comment by ilangleben19** [comment]
Bump, still seems to happen to me

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/66750
