### ISSUE TITLE
terminal crashes

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode#139641]
Issue Type: <b>Bug</b>

When I try to open the terminal window, it crashes right away with the error

> The terminal process failed to launch: A native exception occurred during launch (Cannot launch conpty).

I ran with trace enabled and got this:

```
[2021-12-22 17:59:15.613] [renderer1] [trace] KeybindingService#dispatch Ctrl+` workbench.action.terminal.toggleTerminal
[2021-12-22 17:59:15.614] [renderer1] [trace] CommandService#executeCommand workbench.action.terminal.toggleTerminal
[2021-12-22 17:59:15.635] [renderer1] [trace] terminalInstance#ctor (instanceId: 2) {}
[2021-12-22 17:59:15.805] [renderer1] [debug] Terminal process exit (instanceId: 2) with code undefined
[2021-12-22 17:59:15.806] [renderer1] [debug] Terminal process exit (instanceId: 2) state 2
[2021-12-22 17:59:15.807] [renderer1] [trace] terminalInstance#dispose (instanceId: 2)
```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.83GB free)|
|Process Argv|--crash-reporter-id 973f8da1-2b44-4d5d-97c1-7b905258c359|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30416617
py55gd98:30411514
vscexrecpromp3t1:30407762

```

</details>

**Comment by meganrogge** [comment]
This means your terminal failed during launch - likely due to incorrect shell/shell args. please share your settings.json file

**Comment by BMBurstein** [comment]
My settings.json files are empty (user and worksapce).
I had been trying to add a new terminal type (msys2) and then this happened, so I undid my changes to settings.json, and the problem still occurs. I didn't try opening a terminal before I made the changes to the settings (this is a new install of vscode, and the first thing I did was try to add msys2), so I don't know if it worked before.

**Comment by BMBurstein** [comment]
After some investigation, it looks like the problem may be that when I open the terminal pane, vscode runs
```
C:\WINDOWS\system32\cmd.exe /d /s /c "wsl.exe -l -q"
```

I don't have wsl.exe, and so this command fails. I think this may be causing the prolem. I don't know what this `wsl.exe` is or why it is trying to run it

**Comment by meganrogge** [comment]
you're on an old version in which there was an issue with `terminal.integrated.useWslProfiles` either update vscode or set that to false.

**Comment by meganrogge** [comment]
the reason that runs is we try to detect the shells available to you - including any wsl distros

**Comment by BMBurstein** [comment]
@meganrogge I am on version 1.63.2, which is the latest. I tried setting it to false, and it didn't solve the issue.

**Comment by meganrogge** [comment]
Exiting with code undefined indicates the shell or shell args you're using are invalid.
