### ISSUE TITLE
Code installs older version of extension with pre-release version available

### ISSUE THREAD

**Issue by lnicola** [microsoft/vscode#139628]
- VS Code Version: 1.63.2
- OS Version: Arch Linux

Steps to Reproduce:

1. Open https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer. Notice how the latest versions are 0.3.872 (pre-release) and 0.2.867 (stable). 0.2.853 is the previous stable version.
2. Search for the extension in Code. Notice how you get 0.2.853 instead of 0.2.867
3. Install the pre-release version
4. Switch to stable
5. You now have 0.2.867 (which you couldn't install before)

There might be something wrong with our packaging process, but this all seems quite confusing to me. The only case where I've seen older versions show up in Code is when they depend on a newer `engine`, but I'm running the latest version.

**Comment by sandy081** [comment]
I cant repro this on VS Code 1.63.2 - When I switch to released version it always installs 0.2.853. Can you please try again?

**Comment by lnicola** [comment]
@sandy081 still happens to me (I tested earlier today).

But the issue is not that switching to pre-release and back installs 0.2.889. The issue is that the first install gets you 0.2.853 instead of the latest version.

**Comment by sandy081** [comment]
Yeah I can repro it. It seems this extension has both pre-releases and platform specific.

**Comment by lnicola** [comment]
This. This started happening after uploading the first pre-release builds. Platform-specific versions work fine.

**Comment by lnicola** [comment]
It might also be related to the `engine` upgrade to `^1.63.0` (needed for the pre-release version support, according to the docs). I noticed before that Code shows older versions of extensions requiring a newer version of it.

But there was a `@types/vscode 1.63.0`, so I'm not sure what's wrong.

**Comment by sandy081** [comment]
Reopening for candidate discussion

**Comment by lnicola** [comment]
This seems fixed in Code Insiders, but is it supposed to recommend the pre-release version by default?

![image](https://user-images.githubusercontent.com/308347/148770528-f14de35d-3a74-41ba-bcaf-a4ce2038e37e.png)

**Comment by sandy081** [comment]
>  but is it supposed to recommend the pre-release version by default?

Yes, VS Code Insiders recommend to install pre-release version by default. Are you seeing other way?

**Comment by lnicola** [comment]
It works as expected, then.
