### ISSUE TITLE
integrated terminal tabs on the top or bottom

### ISSUE THREAD

**Issue by ibukanov** [microsoft/vscode#139661]
The current setting `terminal.integrated.tabs.location` supports only two values, `left` and `right`. When using terminal in the panel which is shown on left or right or in the sidebar, when terminal is tall and relatively narrow, this waists space as most of the tall tab column is empty while the terminal itself becomes narrower.

It will be nice if the setting will support also `top` and `bottom` values to optimize screen estate usage.

**Comment by ehaynes99** [comment]
There is this setting, which essentially reverts to the old behavior of a dropdown rather than tabs. Not as good as tabs on top/bottom, but better than eating up 10% of the screen IMO

```
"terminal.integrated.tabs.enabled": false
```

**Comment by amangoel185** [comment]
Can this issue be re-opened for another round of voting or be opened as a new issue?
