### ISSUE TITLE
animateTransform tag is not highlighted in HTML

### ISSUE THREAD

**Issue by cyberalien** [microsoft/vscode#139698]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.0-insider
- OS Version: macOS 12.1

Steps to Reproduce:

1. Create file `test.html` with this content:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <svg
      width="120"
      height="120"
      viewBox="0 0 120 120"
      xmlns="http://www.w3.org/2000/svg"
    >
      <polygon points="60,30 90,90 30,90">
        <animateTransform
          attributeName="transform"
          attributeType="XML"
          type="rotate"
          from="0 60 70"
          to="360 60 70"
          dur="10s"
          repeatCount="indefinite"
        />
      </polygon>
    </svg>
  </body>
</html>
```
Tag `animateTransform` is marked red:
![Screenshot 2021-12-23 at 21 35 19](https://user-images.githubusercontent.com/822287/147285003-839ce9ca-10d4-4f24-bb79-1d0eed177352.png)

It is a valid SVG element, sample code copied directly from MDN: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateTransform

**Comment by alexr00** [comment]
@cyberalien it looks like `animateTransform` is getting that color because it is deprecated. We get our syntax highlighting grammar for html from https://github.com/textmate/html.tmbundle. If you think that it shouldn't be marked as deprecated in our syntax highlighting grammar you can file an issue over there.

**Comment by cyberalien** [comment]
> @cyberalien it looks like `animateTransform` is getting that color because it is deprecated.

That is incorrect. `animateTransform` is part of SVG 2 spec, it is not deprecated.

> We get our syntax highlighting grammar for html from https://github.com/textmate/html.tmbundle. If you think that it shouldn't be marked as deprecated in our syntax highlighting grammar you can file an issue over there.

Sure.
