### ISSUE TITLE
better triaging of terminal launch failures

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#139669]
I see at least a few terminal launch failure issues each week. 

I propose when a terminal process exits during launch (likely due to bad shell/shell args), we show a notification with a link to docs that might help. 

Even if it just points to docs that say: "in your issue, include your settings.json file", it would save time and point users in the right direction.

**Comment by Tyriar** [comment]
We already do this for the most part:

![image](https://user-images.githubusercontent.com/2193314/148116039-f2879920-3d17-48eb-89d0-df9f9d325f45.png)

That points to https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch, do you want to link that somewhere to https://github.com/microsoft/vscode/wiki/Terminal-Issues?

**Comment by meganrogge** [comment]
I don't remember the use case for this. I'll reopen it if I see them again. I think it might be good to say in the docs if this still doesn't work, create an issue with your settings.json and a trace log file.
