### ISSUE TITLE
live server not showing favicon

### ISSUE THREAD

**Issue by Patrick2812** [microsoft/vscode#139622]
Issue Type: <b>Bug</b>

The problem is occuring only for this file 
i have added a link to my favicon when i open with live server it wont show me the favicon whereas it shows the favicon when i open without vs code 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (2.85GB free)|
|Process Argv|C:\\Users\\prati\\OneDrive\\Desktop\\Newsletter Subscription web app --crash-reporter-id e136686f-2f9e-4538-b0bf-99b7610a0507|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.6.0
doxdocgen|csc|1.3.2
gitlens|eam|11.7.0
prettier-vscode|esb|9.0.0
macros|ged|1.2.1
vscode-pull-request-github|Git|0.34.2
better-cpp-syntax|jef|1.15.10
csharp|ms-|1.23.17
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5200
vsliveshare-audio|ms-|0.1.91
material-icon-theme|PKi|4.11.0
LiveServer|rit|5.6.1
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614
vscexrecpromp3t2:30407763

```

</details>

**Comment by deepak1556** [comment]
This sounds like an issue with the Live Server extension (rather than an issue with VS Code). Please file an issue for that extension.

If you can pinpoint your problem to a bug in VS Code, please create a new issue.

Thanks!
