### ISSUE TITLE
VSCode is not taking new gradle version installed after restart

### ISSUE THREAD

**Issue by daskabe** [microsoft/vscode#139606]
Does this issue occur when all extensions are disabled?: Yes/No. Yes

- VS Code Version: 1.62.2
- OS Version: BigSur v11.6

Steps to Reproduce:

1. installed gradle version 5.6.1 using sdkman
2. ```sdk install gradle 5.6.1```
3. ```sdk default gradle 5.6.1```
4. restarted VSCode and closed all terminal.
5. VSCode does not want to use the new installed gradle version.
6. in Bash the new installed gradle has taken effect.
<img width="1161" alt="Screen Shot 2021-12-21 at 4 39 45 PM" src="https://user-images.githubusercontent.com/94478096/147007462-6f41cd95-2b03-49a1-818a-d19e9219789e.png">

**Comment by meganrogge** [comment]
have you tried closing the vscode application entirely? that's necessary to refresh the environment

**Comment by daskabe** [comment]
> 4.restarted VSCode and closed all terminal.

**Comment by Tyriar** [comment]
@daskabe can you run `which gradle` and `echo $PATH`? The problem might be on your end and depend on your shell launch scripts
