### ISSUE TITLE
Support Per-Workspace Environment Variable Settings and Path Specifications

### ISSUE THREAD

**Issue by matttproud** [Microsoft/vscode#13965]
- VSCode Version: 1.6.1 (1.6.1)
- OS Version: Mac OS X 10.11.6 (15G1004)

User story: As a developer, I would like VS Code to offer a per-workspace setting that lets me replace (or augment) VS Code's environment variables with my own dictionary of key-value pairs.

User story: As a developer, I would like VS Code to offer the ability to reference pre-existing variables in my definition and apply expansion to them.

``` javascript
{
// Editor

  // Controls the environment variables.
  "editor.environment": {
    "GOPATH": "./pkg",
    "PATH": "${HOME}/bin:./pkg/bin:${PATH}"    
  }
}
```

Before you write this issue off as absurd, consider Mac OS X as a platform.  Propagating environment variables to non-command line applications is especially problematic and breaks between major operating system releases:
- http://stackoverflow.com/questions/30118993/how-to-set-environment-variables-in-yosemite
- http://stackoverflow.com/questions/25385934/setting-environment-variables-via-launchd-conf-no-longer-works-in-os-x-yosemite

The motivating discovery behind filing this is the [Go Programming Language](http://www.golang.org)'s reliance on environment variables for controlling its execution environment, package search path, runtime, build tools, etc:
- https://golang.org/doc/code.html#GOPATH
- https://golang.org/cmd/go/

The issue transcends the [popular Go plugin](https://github.com/Microsoft/vscode-go).

**Comment by roblourens** [comment]
There is a setting for the gopath - I have `"go.gopath": "/Users/roblou/code/go"`, in case you didn't see it. Might make sense to have a general solution though.

**Comment by matttproud** [comment]
Yep, a general solution is what I am aiming for.  I do a fair bit of hacking on the core Go distribution itself, including building binaries that use the [Cgo bridge](https://blog.golang.org/c-go-cgo).  All of these exercises have environmental variable needs that go way beyond just the usual`GOPATH` — e.g., [integrating with `pkg-config`](https://golang.org/cmd/cgo/)  :-(

**Comment by joaomoreno** [comment]
#6333
