### ISSUE TITLE
[Bug] Markdown Preview does not load/render external JavaScript files with totally allowed content and script executions

### ISSUE THREAD

**Issue by gusbemacbe** [microsoft/vscode#139684]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders .164
- OS Version: Endeavour OS (derived from Arch Linux)

Steps to Reproduce:

1. Create a vanilla JavaScrip file called `vanilla.js` in a new folder `js` in your project with files written in Markdown. Write like:

   ```js
    const x = "Hello World!";
    document.getElementById("demo").innerText = x
   ```

2. Write `<script type="module" src="js/vanilla.js"></script>` on the Markdown file.
3. Write the element with a JavaScript identifier – `<span id="demo"></span>` on the Markdown file. 
4. Click the Open Preview to Side and you will figure out it does not load or render the `demo` element.

You can compare the HTML and Markdown previews at VSCode:

![Markdown file at Markdown Preview on VSCode](https://user-images.githubusercontent.com/2257024/147232611-737b3e63-4362-4d13-8ff8-9467551767b8.png)

![HTML file at HTML Preview on VSCode](https://user-images.githubusercontent.com/2257024/147232756-9694edca-9274-4d0c-b415-2d1556782d33.png)

In the Markdown file, at the preview, the tables are not rendered/loaded. In the HTML file, at the previw, they are rendered/loaded.

I'll provide you a compressed file, so you can test, replicate and find easily the bug.

[example.zip](https://github.com/microsoft/vscode/files/7768975/example.zip)

**Comment by Lemmingh** [comment]
I believe it's a bug of your own code.

`yaml.js` uses sync XHR, which is not allowed.

Please turn to `fetch`.

---

Proof:

```javascript
"use strict";

// Fetch is modern and easy to use.
(async () => {
    const response = await fetch("assets/yaml/letter.yaml");
    console.log("Fetch:", (await response.text()).slice(0, 51));
})();

// Asynchronous XHR is awkward.
(() => {
    const xhr = new XMLHttpRequest();
    xhr.onload = function () {
        console.log("A XHR:", this.responseText.slice(0, 51));
    };
    xhr.open("GET", "assets/yaml/letter.yaml");
    xhr.send();
})();

// Synchronous XHR causes error.
(() => {
    const xhr = new XMLHttpRequest();
    xhr.onload = function () {
        console.log("S XHR:", this.responseText.slice(0, 51));
    };
    xhr.open("GET", "assets/yaml/letter.yaml", false);
    xhr.send();
})();
```

**Comment by gusbemacbe** [comment]
> I believe it's a bug of your own code.
> 
> `yaml.js` uses sync XHR, which is not allowed.
> 
> Please turn to `fetch`.
> 
> Proof:

Markdown Preview

![image](https://user-images.githubusercontent.com/2257024/147296712-7016cf5a-07db-49b2-89f4-5b94408bfe01.png)

HTML preview

![image](https://user-images.githubusercontent.com/2257024/147296496-84fe354d-1950-4b78-811e-7d22b1f4c99b.png)

**Comment by Lemmingh** [comment]
In my environment, sync XHR leads to `net::ERR_NAME_NOT_RESOLVED` or `net::ERR_CONNECTION_CLOSED`, indicating that it's rejected. Fetch and async XHR work fine.

Besides, if I understand `<iframe>` attributes correctly, sync XHR is not enabled in VS Code webview.

---

What's your code behind the scene? Why did your logs all come from `prevel.js:496` or `__vscode_liveprevie...injected_script:131`?

**Comment by gusbemacbe** [comment]
> What's your code behind the scene? Why did your logs all come from `prevel.js:496` or `__vscode_liveprevie...injected_script:131`?

The same code in JavaScript, I just copied and pasted your XHR code to show you the results. 

`prevel.js:496` turned to be Mate Translate extension, but I disabled it and the log appeared different with the other extensions. 

`__vscode_liveprevie...injected_script:131` comes from Microsoft's [Livre Preview](https://github.com/microsoft/vscode-livepreview). I open the HTML page with "Open in Browser" from this extension.

**Comment by mjbvz** [comment]
Please share a minimal example workspace for this issue (the current `example.zip` is rather complex)

**Comment by gusbemacbe** [comment]
Ok, I am going to use the non-insider version of VSCode to install few Markdown extensions and create a simple and minimal workspace with the name of `SImple Markdown.code-workspace`. 

I'll share only the workspace settings file for you. I will not share the user configs file because no Markdown settings are not included. They are included only in the workspace settings called `Simple Markdown.code-worskapce`. I also will include the recommended extensions to the workspace settings to ease your analysis and investigation. 

I'll provide you the zipped file: [simple-small-minimal-basic-markdown-project.zip](https://github.com/microsoft/vscode/files/7804991/simple-small-minimal-basic-markdown-project.zip)


I'll show two images, one within a workspace and without a workspace. I will make a very simple and small Markdown project. 

# Project

1. I created only a basic Markdown file. 
2. I created two folders – `js` and `yaml` inside the folder `assets`
3. I will not create the root ptoject settings (`.vscode/settings.json`).

## JavaScript

I include three files:

1. `yaml` is a pure JavaScript file that converts from YAML to JSON. Reference: [yamljs](https://www.npmjs.com/package/yamljs);
2. `json2html` is a pure JavaScript file that converts from JSON converted from YAML to HTML lists or tables. Reference: [json2html](http://www.json2html.com/);
3. `global` is an user global JavaScript file. The word `global` means to apply for all the pages. If I name it `index`, it applies only for the page `index.html` or `index.md`. 

## YAML

It will be a very simple and small YAML file to ease your understanding. 

# Without workspace

The project comes without workspace settings. No problems. OK, I disabled all restrictions.

1. I created a file called `index.md`. How is the Markdown file like? Here is:

   ![image](https://user-images.githubusercontent.com/2257024/147999171-9828b529-135e-4f5f-8674-b3c76778d4be.png)

2. Firstly, let's create a simple YAML file called `yaml.yml`:

    ![image](https://user-images.githubusercontent.com/2257024/148000513-3894e209-6415-4202-b987-227d4edb0cb2.png)

3. OK, let's write the code in the file `global.js`. 

    a. Firstly, we need to load a YAML file, using `yaml.js` that will convert it to JSON;

    ```js
    const yaml = YAML.load("assets/yaml/yaml.yml");
    ```

    Too simple, isn't it?

    b. Based on `json2html`s [tutorial of example 2 – "Short Hand Notation"](http://www.json2html.com/examples/). I'll copy only the template part and change the values to `fruit` and `price` as we could see from the YAML file:
    
    ```js
    let template = {'<>':'div','text':'${fruit} (${price})'};
    ```

    c. Let's write to trigger and render new HTML code in the Markdown file:
    
    ```js
    document.getElementById("list-of-fruits").innerHTML = json2html.render(yaml, template);
    ```

    Ready!

    Here is like:
    
    ![image](https://user-images.githubusercontent.com/2257024/147999284-71ef0004-0dcc-4b66-83a9-b30b7adc9ebf.png)

Here is the result... Where is the list of fruits?!

![image](https://user-images.githubusercontent.com/2257024/147999340-5e7f3100-1779-420d-b42b-2e6e9059240c.png)

Let me generate it to HTML, using @yzhang-gh's [Markdown All in One](https://github.com/yzhang-gh/vscode-markdown)... On a HTML file, yeah, the list appears:

![image](https://user-images.githubusercontent.com/2257024/148000587-ae248958-c08d-4307-9a8a-47ea2c79cc3e.png)

# With workspace

The project comes with workspace settings. All restrictions were already disabled. Let's create and save as a file with `SImple Markdown.code-workspace`:

![image](https://user-images.githubusercontent.com/2257024/147999733-41e1d7c4-f8f8-4cb1-ab79-0722e5d75bf1.png)

Here is the workspace settings:

```json
{
	"folders": 
	[
		{
			"path": "../Testes/Basic Markdown"
		}
	],
	"settings": 
	{
		"livePreview.portNumber": 1984,
		"livePreview.showStatusBarItem": true,

		// MARKDOWN ALL IN ONE
		"markdown.extension.print.absoluteImgPath": false,
		"markdown.extension.print.imgToBase64": true,
		"markdown.extension.print.includeVscodeStylesheets": false,
		"markdown.extension.print.onFileSave": false,
		"markdown.extension.toc.plaintext": false,
		"markdown.extension.toc.updateOnSave": false,

		// MAKRODWN PASTE 
		"MarkdownPaste.rules": 
		[
			{
				"regex": "^(?:https?://)?(?:(?:(?:www\\.?)?youtube\\.com(?:/(?:(?:watch\\?.*?v=([^&\\s]+).*)|))?))",
				"options": "g",
				"replace": "[![](https://img.youtube.com/vi/$1/0.jpg)](https://www.youtube.com/watch?v=$1)"
			},
			{
				"regex": "^(https?://.*)",
				"options": "ig",
				"replace": "[]($1)"
			}
		],
		"MarkdownPaste.enableImgTag": true,

		// MAKRODWN PREVIEW ENHANCED
		"markdown.preview.markEditorSelection": false,
		"markdown-preview-enhanced.automaticallyShowPreviewOfMarkdownBeingEdited": false,
		"markdown-preview-enhanced.codeBlockTheme": "one-dark.css",
		"markdown-preview-enhanced.enableCriticMarkupSyntax": true,
		"markdown-preview-enhanced.enableEmojiSyntax": true,
		"markdown-preview-enhanced.enableExtendedTableSyntax": true,
		"markdown-preview-enhanced.enableHTML5Embed": true,
		"markdown-preview-enhanced.enableScriptExecution": true,
		"markdown-preview-enhanced.frontMatterRenderingOption": "table",
		"markdown-preview-enhanced.HTML5EmbedIsAllowedHttp": true,
		"markdown-preview-enhanced.HTML5EmbedUseImageSyntax": true,
		"markdown-preview-enhanced.HTML5EmbedUseLinkSyntax": true,
		"markdown-preview-enhanced.liveUpdate": true,
		"markdown-preview-enhanced.previewTheme": "github-dark.css",
		"markdown-preview-enhanced.mermaidTheme": "dark",

		// MICROSOFT MARKDOWN LANGUAGE FEATURES
		"markdown.preview.breaks": true,
		"markdown.preview.fontFamily": "'Red Hat Display', sans-serif",
	},
	"extensions": 
	{
		"recommendations": 
		[
			"bierner.github-markdown-preview",
			"bierner.markdown-emoji",
			"bierner.markdown-footnotes",
			"bierner.markdown-preview-github-styles",
			"jebbs.markdown-extended",
			"jjaakko.markdown-kbd",
			"mathpix.vscode-mathpix-markdown",
			"ms-vscode.live-server",
			"pkief.markdown-checkbox",
			"rsolano.pandoc-markdown",
			"shd101wyy.markdown-preview-enhanced",
			"telesoho.vscode-markdown-paste-image",
			"yzhang.markdown-all-in-one"
		]
	}
}
```

The result is the same as that without workspace. Ready.

Satisfied?

**Comment by mjbvz** [comment]
Thanks. The root cause is that the library you are using to loa the yaml seems to make a synchronous XMLHttpRequest to load a workspace resources

VS Code uses service workers to support loading workspace resources and in Chrome, service workers do not support sync XMLHttpRequests: https://stackoverflow.com/questions/35879844/can-service-workers-respond-to-synchronous-xhr-requests. As using sync XMLHttpRequests is strongly discouraged, I don't see this being fixed and there's nothing VS Code can do to work around this


I suggest switching to use the `fetch` api to load the file instead
