### ISSUE TITLE
Settings Sync won't turn on

### ISSUE THREAD

**Issue by TurnipGuy30** [microsoft/vscode#139603]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: `1.63.2 (user setup)`
- OS Version: `Windows_NT x64 10.0.19042`

Steps to Reproduce:

1. `Accounts` > `Turn on Settings Sync...` > `Sign in & Turn on` > `TurnipGuy30 (GitHub)`
2. Notification: `Error while turning on Settings Sync. Please check [logs](command:workbench.userDataSync.actions.showLog) for more details.`
3. `Log (Settings Sync)` returns the following:
```
[2021-12-22 06:20:28.049] [settingssync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2021-12-22 06:20:28.049] [settingssync] [info] Auto Sync is disabled.
[2021-12-22 06:46:15.511] [settingssync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/manifest
```

**Comment by sandy081** [comment]
It seems the request `Request failed https://vscode-sync.trafficmanager.net/v1/manifest` has failed. Can you please do following to get more Information about the error:

- Open Shared Process (F1 > Toggle Shared Process) and let us know the error for above request

**Comment by TurnipGuy30** [comment]
I believe this is what you're talking about:
```
request.ts:42 GET https://vscode-sync.trafficmanager.net/v1/manifest net::ERR_CERT_WEAK_SIGNATURE_ALGORITHM
```

**Comment by sandy081** [comment]
Yes, it seems you have network connection issues, please fix them and try again.

**Comment by TurnipGuy30** [comment]
It's probably related to me using a school computer. Thanks for the help.
