### ISSUE TITLE
Open the default keybinding file without creating a new group

### ISSUE THREAD

**Issue by septsea** [microsoft/vscode#139659]
As of VSC 1.61, the default setting file is opened *in group* if `"workbench.settings.editor"` is set to be `"json"` and `"workbench.settings.openDefaultSettings"` is set to be `true`. However, the default keybinding file is still opened in another group. To be specific, if `"workbench.settings.openDefaultKeybindings"` is set to `true` and one opens "Preferences: Open Keyboard Shortcuts (JSON)" via the command palette, they will find that the default keybinding file is opened in the last active group and that the user keybinding setting file is opened in a new group. The inconsistency is somehow unpleasing.

Therefore, I suggest that the default keybinding file should be opened without creating a new group.

Please do not hesitate to raise a question if I did not make myself understood.

**Comment by Yash621** [comment]
@sandy081 can I work on this ?

**Comment by LaurMerl** [comment]
Hello @sandy081, @Yash621 I have also seen this issue while working on VScode and proposed a simple fix here https://github.com/microsoft/vscode/pull/141989
Steps to reproduce the current behavior are well described in the first comment.

Please, do not hesitate to reach me for further explanations/details.
