### ISSUE TITLE
Git Explorer Color Highlight on git diffs does not "refresh" on changes, only highlights on start / restart

### ISSUE THREAD

**Issue by kamok** [microsoft/vscode#139656]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z (1 wk ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```
- OS Version: MacOS Big Sur 11.6

Steps to Reproduce:

1. Make a change in on any files that is inside a Git Repository
2. I don't see the yellow M, or highlight on the Explorer
3. If I reload VSCode, I now do see the yellow M
![image](https://user-images.githubusercontent.com/9758567/147158043-f392bef4-3d3b-4e21-88c6-84925e73a6f0.png)
4. Similarly, if I delete the change I just made, the yellow M remains, indicating a diff in git (but there isn't)
5. If I reload VSCode, it goes away.

Seems like refresh on Explorer is broken, not the Git Diff part, since this feature (the blue bar indicating change in line in file) works perfectly
![image](https://user-images.githubusercontent.com/9758567/147158216-ab5b0490-7d90-4f4e-ad24-dfb448e328a4.png)

**Comment by kamok** [comment]
Let me know if I can help with anything. This feature is very useful for when doing tedious tasks like updating something in 20 files, and saves me from staring at 20 lines of `git diff` in the command line to figure out if I missed any file.

**Comment by lszomoru** [comment]
@kamok, sorry for not getting back to you on this until now. I was wondering if you could record a gif (you can use https://gifcap.dev/ for example) of you reproducing the issue as that recording would allow me to learn more about your setup in an attempt to try to reproduce the issue locally in order to get to the bottom of this.

**Comment by timonschoenfeld** [comment]
Hey, I'm running into the same issue. Here is a video.
I'm using VS Code 1.64.2 on a MacBook Pro (2021, M1 Pro) and macOS Monterey 12.2.

![Recording 2022-02-25 at 13 56 21](https://user-images.githubusercontent.com/8083819/155719110-ac58fae9-445d-486e-8e45-668fba8ad3fc.gif)

**Comment by kamok** [comment]
Sorry @lszomoru, I missed this email completely. I also took some time to make a gif.
![Recording 2022-03-02 at 16 03 12](https://user-images.githubusercontent.com/9758567/156449416-97f4e1c7-9391-40bf-88ef-fd047078d4ad.gif)

**Comment by kamok** [comment]
I realized I demoed with extensions on, but I did this before and it functions (incorrectly) the same without any extensions.

**Comment by cesarmesones** [comment]
Also have this issue on `1.64.x`, reverting to `1.63.2` fixes it for me.

**Comment by kamok** [comment]
Well, given that I reported the issue when it was at `16.3.2`, I don't think it works for me.

**Comment by kukdh1** [comment]
I also have this issue on Windows, version `1.65.2`.
Reverting to `1.63.2` on Windows solves this issue.

I performed a set of git commands and recorded on both `1.65.2` and `1.63.2`.

My environment:
```
OS: Windows 10 [10.0.19044.1586]
Git: 2.35.1.windows.2
```
Please note that I disabled all extensions and I'm using `Git Bash` as a default terminal.

### On VSCode `1.63.2`
```
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z (3 mos ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

![1 63 2](https://user-images.githubusercontent.com/6904750/159363294-e557acfb-021d-4de5-8917-e8dfe3705e66.gif)
1. Create new file named `README.md`
2. Type, Save, Stage and commit
3. Type again, Note that a **blue bar appeared** before saving document.
4. Save, Note that the blue bar disappeared and a **green bar appeared**.
5. Stage, Note that the **green bar disappeared**.
6. Commit.

### On VSCode `1.65.2`
```
Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z (1 wk ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

![1 65 2](https://user-images.githubusercontent.com/6904750/159366255-a95ad3fb-0eb8-4dbe-993f-ac1e595046f8.gif)
1. Create new file named `README.md`
2. Type, Save, Stage and commit
3. Type again, Note that the **blue bar does not appeared**.
4. Save, Note that the **green bar does not appeared**.
5. If I reopen the file (`Ctrl + W` and `Ctrl + Shift + T`), the **green bar appeared**.
6. Stage, Note that the **green bar does not disappeared**.
7. Reopen the file, the **green bar disappeared**.
8. Commit.

Similarly, git diff window also not updated immediately, as shown in below (`1.65.2`):
![diff_1 65 2](https://user-images.githubusercontent.com/6904750/159367341-bbf226ce-a959-401e-beea-63ed147260a8.gif)

**Comment by lszomoru** [comment]
@kukdh1, thank you very much for the additional information. I have tried to reproduce the issue without much luck so I was wondering if I could ask you to try couple of things so that we track down the root cause of the issue that you are seeing.
 - Could you please check if you are able to reproduce the issue in `1.64`. Download link are at the top of [the release page](https://code.visualstudio.com/updates/v1_64).
 - We have made some changes related to file watching so I was wondering if you could collect [the file watching logs](https://github.com/microsoft/vscode/wiki/File-Watcher-Issues) while you are able to reproduce the problem.

**Comment by kukdh1** [comment]
@lszomoru Interestingly, _some_ issues are solved after I removed the VSCode (deleting `<HOME>/AppData/Local/Programs/Microsoft VS Code` using uninstaller) and installed again.
So, I ran same tests, with uninstalling the VSCode everytime I change the version.

As shown in below (VSCode `1.64.2` and `1.65.2`), change bars (blue and green) are appeared correctly as I edit the file.
![Recording 2022-03-25 at 03 34 46](https://user-images.githubusercontent.com/6904750/159986858-d4c8259e-3702-4ad9-95d6-715cdd033486.gif)

But still, green bar does not disappear after staging/committing the file (both `1.64.2` and `1.65.2`).
![Recording 2022-03-25 at 03 37 12](https://user-images.githubusercontent.com/6904750/159987247-c5efa4d1-b075-4ecf-8aef-40ef5bdacd34.gif)

When I tested on `1.63.2`, log says `onWillActivateByEvent:  onFileSystem:git` when I staged/committed.
Maybe this event is related to updating git diff?

Below log is collected on `1.63.2`:
```
**** log.ts:289 TRACE CommandService#executeCommand git.stage
log.ts:289 TRACE CommandService#executeCommand setContext
log.ts:289 TRACE CommandService#executeCommand setContext
log.ts:289 TRACE [text file model] resolve() - enter git:/d:/git/test/README.md.git?{"path":"d:\\git\\test\\README.md","ref":""}
log.ts:289 TRACE [text file model] resolveFromFile() git:/d:/git/test/README.md.git?{"path":"d:\\git\\test\\README.md","ref":""}
++++ log.ts:289 TRACE onWillActivateByEvent:  onFileSystem:git
++++ log.ts:289 TRACE onWillActivateByEvent:  onFileSystem:git
log.ts:289 TRACE [text file model] resolveFromContent() - enter git:/d:/git/test/README.md.git?{"path":"d:\\git\\test\\README.md","ref":""}
log.ts:289 TRACE [text file model] doUpdateTextModel() git:/d:/git/test/README.md.git?{"path":"d:\\git\\test\\README.md","ref":""}
log.ts:289 TRACE [text file model] onModelContentChanged() - enter git:/d:/git/test/README.md.git?{"path":"d:\\git\\test\\README.md","ref":""}
log.ts:289 TRACE [text file model] onModelContentChanged() - new versionId 3 git:/d:/git/test/README.md.git?{"path":"d:\\git\\test\\README.md","ref":""}
log.ts:289 TRACE CommandService#executeCommand setContext

**** log.ts:289 TRACE CommandService#executeCommand git.commitStaged
log.ts:289 TRACE CommandService#executeCommand setContext
log.ts:289 TRACE KeybindingService#dispatch . undefined
log.ts:289 TRACE CommandService#executeCommand setContext
log.ts:289 TRACE CommandService#executeCommand setContext
log.ts:289 TRACE [text file model] resolve() - enter git:/d:/git/test/README.md.git?{"path":"d:\\git\\test\\README.md","ref":""}
log.ts:289 TRACE [text file model] resolveFromFile() git:/d:/git/test/README.md.git?{"path":"d:\\git\\test\\README.md","ref":""}
++++ log.ts:289 TRACE onWillActivateByEvent:  onFileSystem:git
++++ log.ts:289 TRACE onWillActivateByEvent:  onFileSystem:git
log.ts:289 TRACE [text file model] resolveFromContent() - enter git:/d:/git/test/README.md.git?{"path":"d:\\git\\test\\README.md","ref":""}
log.ts:289 TRACE [text file model] doUpdateTextModel() git:/d:/git/test/README.md.git?{"path":"d:\\git\\test\\README.md","ref":""}
log.ts:289 TRACE CommandService#executeCommand setContext
```

Please check below log too, which was collected on `1.64.2`:
(This log **does not** contains `onWillActivateByEvent`)
```
**** log.ts:289 TRACE CommandService#executeCommand git.stage
log.ts:289 TRACE CommandService#executeCommand setContext
TRACE [text file model] resolve() - enter file:///d:/git/test/README.md
log.ts:289 TRACE [text file model] resolveFromFile() file:///d:/git/test/README.md
log.ts:289 TRACE KeybindingService#dispatch . undefined
log.ts:289 TRACE [File Watcher (node.js)] [raw] ["change"] globalStorage
log.ts:289 TRACE [File Watcher (node.js)] [CHANGED] c:\Users\kukdh1\AppData\Roaming\Code\User\globalStorage
log.ts:289 TRACE [File Watcher (node.js)] [raw] ["change"] globalStorage
log.ts:289 TRACE [File Watcher (node.js)] [CHANGED] c:\Users\kukdh1\AppData\Roaming\Code\User\globalStorage

**** log.ts:289 TRACE KeybindingService#dispatch Ctrl+Enter scm.acceptInput
log.ts:289 TRACE CommandService#executeCommand scm.acceptInput
log.ts:289 TRACE CommandService#executeCommand _vscode_delegate_cmd_l15cf7oh
log.ts:289 TRACE [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\kukdh1\AppData\Roaming\Code\User\globalStorage
log.ts:295 DEBUG User data changed
log.ts:289 TRACE CommandService#executeCommand setContext
```

**Comment by lszomoru** [comment]
@kukdh1, thank you very much for sharing all these details. The git decorators are being updated through various events, one being the file system events scoped to the `.git` folder of the folder/workspace. I have just got to the bottom of a similar issue so I was wondering if you could try the following:
1. Could you please check your user/workspace setting and share the values of the `files.watcherExclude`.
2. Could you please invoke the `Git: Set Log Level...` command to set the log level to `Trace`
3. Reproduce the remaining issue, and send me the contents of the Git output channel which you can access by invoking the `Git: Show Output Log...` command

**Comment by kukdh1** [comment]
> 1. Could you please check your user/workspace setting and share the values of the `files.watcherExclude`.

Here is my user settings of `files.watcherExclude`:
![image](https://user-images.githubusercontent.com/6904750/160197942-c0091207-b9c2-42e3-96e7-d3fa77fea0ea.png)
JSON version was little different with the screenshot:
```json
"files.watcherExclude": {
  "*.synctex.*": true,
  "**/__pycache__/**": true,
  "**/.ammonite": true,
  "**/.bloop": true,
  "**/.git/**": true,
  "**/.git/objects/**": false,
  "**/.git/subtree-cache/**": false,
  "**/.metals": true,
  "**/bazel-*/**": true,
  "**/node_modules/**": true,
  "**/node_modules/*/**": false,
  "**/vivado_project/**": true
}
```

Here is my workspace settings of `files.watcherExclude` (not changed though).
```
"files.watcherExclude": {
  "**/.git/objects/**": true,
  "**/.git/subtree-cache/**": true,
  "**/node_modules/*/**": true,
  "**/.hg/store/**": true
}
```

> Git output log

- Logs printed after I saved the file.
```
[2022-03-25T20:30:57.172Z] [debug] [wt] Change: d:\git\test\README.md
[2022-03-25T20:30:57.233Z] [debug] [wt] Change: d:\git\test\README.md
[2022-03-25T20:30:58.300Z] > git symbolic-ref --short HEAD [23ms]
[2022-03-25T20:30:58.331Z] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/master refs/remotes/master [29ms]
[2022-03-25T20:30:58.361Z] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [28ms]
[2022-03-25T20:30:58.362Z] > git remote --verbose [27ms]
[2022-03-25T20:30:58.390Z] > git config --get commit.template [25ms]
```

- Logs printed after I staged the file.
```
[2022-03-25T20:32:14.650Z] git.stage 1
[2022-03-25T20:32:14.650Z] git.stage.scmResources 1
[2022-03-25T20:32:14.679Z] > git add -A -- D:\git\test\README.md [27ms]
[2022-03-25T20:32:14.738Z] > git symbolic-ref --short HEAD [25ms]
[2022-03-25T20:32:14.770Z] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/master refs/remotes/master [30ms]
[2022-03-25T20:32:14.801Z] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [29ms]
[2022-03-25T20:32:14.801Z] > git remote --verbose [27ms]
[2022-03-25T20:32:14.830Z] > git config --get commit.template [26ms]
```

- Logs printed after I re-opened the file (to update diff highlights)
![Recording 2022-03-26 at 05 36 24](https://user-images.githubusercontent.com/6904750/160197380-28f18f30-0cd9-4760-82fe-bc5d6678fd29.gif)
```
[2022-03-25T20:33:37.740Z] > git ls-files --stage -- D:\git\test\README.md [24ms]
[2022-03-25T20:33:37.767Z] > git cat-file -s 3b95c160030f12fd6dfc138e9e1dff143fa1a357 [26ms]
```

**Comment by kukdh1** [comment]
@lszomoru As I noticed that the `files.watcherExclude` includes whole git directory, I tried with default one by clicking `Reset Setting` in Settings window:
```json
"files.watcherExclude": {
  "**/.git/objects/**": true,
  "**/.git/subtree-cache/**": true,
  "**/node_modules/*/**": true,
  "**/.hg/store/**": true
}
```

And I validated that the git highlights are updated correctly (as shown in below, on `1.65.2`):
![Recording 2022-03-26 at 05 46 54](https://user-images.githubusercontent.com/6904750/160198681-d57c46ab-b727-4fc5-85ae-43f7fedddf93.gif)
Also, `Stage Selected Ranges` works well:
![Recording 2022-03-26 at 05 50 46](https://user-images.githubusercontent.com/6904750/160199090-79dc3cce-cf98-4538-aceb-bfdd6c3b0161.gif)

Here is the git logs after stage, and last two lines are added:
```
[2022-03-25T20:54:52.496Z] git.stage 1
[2022-03-25T20:54:52.496Z] git.stage.scmResources 1
[2022-03-25T20:54:52.526Z] > git add -A -- D:\git\test\README.md [25ms]
[2022-03-25T20:54:52.585Z] > git symbolic-ref --short HEAD [24ms]
[2022-03-25T20:54:52.589Z] [debug] [.git] Change: d:\git\test\.git\index
[2022-03-25T20:54:52.615Z] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/master refs/remotes/master [28ms]
[2022-03-25T20:54:52.642Z] > git remote --verbose [24ms]
[2022-03-25T20:54:52.642Z] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [26ms]
[2022-03-25T20:54:52.669Z] > git config --get commit.template [24ms]
++++ [2022-03-25T20:54:53.737Z] > git ls-files --stage -- D:\git\test\README.md [25ms]
++++ [2022-03-25T20:54:53.762Z] > git cat-file -s 3b95c160030f12fd6dfc138e9e1dff143fa1a357 [23ms]
```

**Comment by kukdh1** [comment]
I think you can close the issue (I cannot do that as I'm not an author of this issue).
Thank you very much for your help.

For anybody who has same issues:
1. Try to reinstall VSCode (to remove potential garbage files caused by update).
2. Reset `files.watcherExclude` setting to the default.

**Comment by kamok** [comment]
> @kukdh1, thank you very much for sharing all these details. The git decorators are being updated through various events, one being the file system events scoped to the `.git` folder of the folder/workspace. I have just got to the bottom of a similar issue so I was wondering if you could try the following:
> 
> 1. Could you please check your user/workspace setting and share the values of the `files.watcherExclude`.
> 2. Could you please invoke the `Git: Set Log Level...` command to set the log level to `Trace`
> 3. Reproduce the remaining issue, and send me the contents of the Git output channel which you can access by invoking the `Git: Show Output Log...` command

I can happily confirm that I had this in my settings.json for some god awful reason.

```
    "files.watcherExclude": {
        "**": true
    }
```

Really not sure where it came from, maybe an extension in the past messed it up(?) Does running VSCode without extensions not reset settings.json(?). But after removing it, the feature works as expected (as it always have for years).

I am closing the issue.
