### ISSUE TITLE
向右拆分编辑页后，在主页进行编辑时跳转焦点问题。

### ISSUE THREAD

**Issue by mrlitong** [microsoft/vscode#139679]
Issue Type: <b>Feature Request</b>

场景：我打开了编辑页A，然后点击右上角「向右拆分编辑页」后，屏幕分屏，左边为编辑页A，右边为编辑页A1。（此时A和A1一模一样对吧。）随后我在A1页找到一个代码片段并保持停留，鼠标焦点切换回A页面进行代码开发。在A页面我想查看一个函数的定义，此时我跳转到了编辑页B，查看完以后我通过回退功能返回编辑页A继续进行开发。但是在这一步出现了问题，**预期应该从B页面回跳回A页面，但是vscode跳转到了A1页面**；

Just same with this:https://github.com/microsoft/vscode/issues/9526#issuecomment-713871869

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

**Comment by mrlitong** [comment]
Let me know if you need a english issue version.

**Comment by Lemmingh** [comment]
#9526

**Comment by NLCharles** [comment]
As is suggested, this issue is a duplicate of https://github.com/microsoft/vscode/issues/9526. Thanks for the navigation.

> #9526
