### ISSUE TITLE
"stick" checkbox on color theme picker

### ISSUE THREAD

**Issue by wmertens** [Microsoft/vscode#13964]
- VSCode Version: 1.5.3
- OS Version: 10.11.6

When you open the color theme picker, you can only select one theme before it closes. It would be nice to have a way to keep the picker open so you can try several themes before picking a winner.

**Comment by roblourens** [comment]
If you use the arrow keys to scroll up and down, you can preview all the themes before selecting one.

**Comment by wmertens** [comment]
![facepalm](https://s-media-cache-ak0.pinimg.com/originals/cf/05/af/cf05af3f2188da8c80516a6456441040.gif)

Thanks and sorry for the noise :)
