### ISSUE TITLE
Sidebar webview view sometimes doesn't show the html that is set

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#139638]
I was investigating https://github.com/microsoft/vscode-pull-request-github/issues/3199, and it looks like a VS Code issue, not an extension issue. The steps in that issue repro ~30% of the time for me.

Code wise, here's what's happening in the extension:
1. The extension's `resolveWebviewView` gets called
2. We set the `html` of the `Webview`
3. At this point, the webview is somehow empty.

I added a log point in `$setHtml` in `MainThreadWebviews`, and I've confirmed that the html is at least making it that far. When I inspect the element using the devtools, the html is not there:

![image](https://user-images.githubusercontent.com/38270282/147114386-e83464a3-8d0e-49a2-b563-0a3af47a25f8.png)

Any ideas about what might be going on here? It looks like the iframe is just missing entirely.

**Comment by mjbvz** [comment]
Are there any other logs/errors in the dev tools when this happens?

**Comment by alexr00** [comment]
No, nothing in the dev tools.

**Comment by mjbvz** [comment]
Are you still seeing this issue in current insiders builds?

**Comment by alexr00** [comment]
No, it seems to be fixed. Thank you!
