### ISSUE TITLE
The preview of Markdown desyncs from the file when folding

### ISSUE THREAD

**Issue by caramat** [microsoft/vscode#139636]
Issue Type: <b>Bug</b>

When editing a Markdown file and seeing the preview, VS Code tries to maintain the editor and preview synced to see the same lines related in both. When the folding feature is used in the editor (e.g. folding a code block), the syncing between the editor and the preview is lost.

I've seen #115998, but this issue may be slightly different. The syncing between the editor and the preview may be done first independently, but I leave it to your criteria

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.11.0-43-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 3784)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 2, 2|
|Memory (System)|15.51GB (1.45GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id f163163c-c82d-4195-ab56-5514460c8cd5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.10.1
vscode-intelephense-client|bme|1.8.0
indent4to2|Com|0.1.2
gitlens|eam|11.7.0
vscode-phpmd|eco|1.3.0
php-debug|fel|1.22.0
vscode-php-cs-fixer|fte|0.4.0
todo-tree|Gru|0.0.214
phpcs|ika|1.0.5
dupchecker|jia|0.1.7
vscode-php-refactoring|mar|1.2.1
vscode-docker|ms-|1.18.0
vscode-language-pack-es|MS-|1.63.3
remote-containers|ms-|0.209.6
php-docblocker|nei|2.6.1
vscode-php-getters-setters|php|1.2.3
php-create-method|pkb|0.0.6
vscode-yaml|red|1.2.2
tabnine-vscode|Tab|3.5.11
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vs360cf:30404996
vsrem710:30416614

```

</details>

**Comment by mjbvz** [comment]
Can you share more info about what isn't working as expected?

When I tested this, when the preview scrolls to a folded section, VS Code will simply pause at the folded editor section before continuing on once you have scrolled past that section. This seems like the correct behavior
