### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Sonu07op** [microsoft/vscode#139650]
Issue Type: <b>Feature Request</b>

i can't see what problem i have done in my code when i write it since the problem section in terminal is always saying no problem

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
