### ISSUE TITLE
IntelliSense for react/react-native not working

### ISSUE THREAD

**Issue by Mirodil** [Microsoft/vscode#13966]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 14.5.0
- Extensions: EditorConfig.EditorConfig-0.3.3, dbaeumer.vscode-eslint-1.0.8, donjayamanne.python-0.4.2, johnpapa.Angular2-1.0.2, ms-vscode.csharp-1.4.1, msjsdiag.debugger-for-chrome-1.2.2, vsmobile.vscode-react-native-0.2.0, xabikos.JavaScriptSnippets-1.2.0

Steps to Reproduce:
Intelligent for react even with typings not working
1. create project with this tool https://github.com/infinitered/ignite
2. and open vscode install typings

**Comment by roblourens** [comment]
Where are you missing intellisense? Can you give a code example?

**Comment by roblourens** [comment]
Are you using the react native extension? Is it a bug on their end? I think they try to get typings automatically somehow.

**Comment by Mirodil** [comment]
I checked again in freshly created sources as described above. if you open any file inside app folder, for instance `app/components/AlertMessage.js` and try to get IntelliSense for react.

**Comment by roblourens** [comment]
I don't think intellisense is supposed to work out of the box in vscode for JS so I'm moving this to react-native.

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-react-native#322
