### ISSUE TITLE
Set default location for "Open Folder..."

### ISSUE THREAD

**Issue by igordreher** [microsoft/vscode#139635]
Issue Type: <b>Feature Request</b>

It would be a nice addition to provide a way of configuring a default path for the command "Open Folder...", so I won't need to click around the file explorer every time I launch the editor.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:51:30.084Z)
OS version: Linux x64 5.13.19-2-MANJARO
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
/duplicate see https://github.com/microsoft/vscode/issues/115730#issuecomment-991705914
