### ISSUE TITLE
Path Problem with Compiler

### ISSUE THREAD

**Issue by David-AOMS** [microsoft/vscode#139601]
Issue Type: <b>Bug</b>

When my path has a space in it such as:

G:\My Drive\Projects\CREED

The compiler always fails. It uses the path "G:\My" only.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by weinand** [comment]
What compiler are you using?

**Comment by David-AOMS** [comment]
It's a setup for "Particle" devices.

I believe this is it:

"C:\Users\David\.particle\toolchains\gcc-arm\9.2.1\bin\arm-none-eabi-gcc.exe"



*David Burlington, BSc.*

Director of Engineering

AOMS Technologies
301-155 Gordon Baker Rd
Toronto, ON M2H 3N5
Canada

Office:  +1 (647) 812-2747 x 31
Mobile: +1 (416) 458-8535
Email:   ***@***.***

www.aoms-tech.com

**Comment by weinand** [comment]
Why is this a VS Code problem?
