### ISSUE TITLE
Hide explorer by default

### ISSUE THREAD

**Issue by regs01** [Microsoft/vscode#13962]
- VSCode Version: 1.6.1
- OS Version: Windows 10 1607

How do we make explorer not to forcibly show when opening a file? It's wasting space. Can't find anything related with hide explorer, show explorer, hide sidebar, show sidebar with in:title. There is some "explorer.autoReveal" in settings, but setting it to false doesn't seem to do anything.

**Comment by roblourens** [comment]
Are you saying that when you open a new vscode window, the sidebar is always visible, even if it was closed last time? This is probably #13825. You can set `"telemetry.experiments.showDefaultViewlet": false` as a workaround.
