### ISSUE TITLE
Unwanted angle bracket autocompletion in TypeScript

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#13963]
- VSCode Version: 1.6
- OS Version: Windows 10

When writing code in TypeScript, I often go to fix an expression by changing the comparison operator. I'll highlight the operator, such as the `>=` in `if(a >= b) { ...`, then type the correct operator, such as `<`. In VS Code 1.6, I've noticed that it is treating angle brackets in the same way as other types of brackets when applied to a selection, presumably for the purposes of improved editing of casting syntax and generic type arguments. In my example above, this means that rather than replacing my selection with the correct operator, it changes `>=` into `<>=>`, which is obviously not what was desired.

I want autocompletion in general, but I'd like to turn it off for angle brackets in TypeScript, as I find it more of a hindrance than a help. Is there an option for this, and if not, could it be added in a future version of VS Code? Note that turning it off should be a language-specific feature, as it would be undesirable to also turn it off for tsx, jsx, xml and html.

**Comment by roblourens** [comment]
Huh, I see this too, only when highlighting a `<` or `>`. Not when highlighting something else.

**Comment by waderyan** [comment]
This is very strange. Confirmed with latest Insider bits. @dbaeumer can you confirm that this is a JavaScript language service issue?

**Comment by dbaeumer** [comment]
@waderyan it is not a language server issue. This is in the TS extension language configuration (vscode\extensions\typescript\language-configuration.json). And we added with for cast and generic types. Unfortunately this can not be disabled separately. Would be a feature request.

**Comment by axefrog** [comment]
Would it be possible to perform a quick contextual check before applying brackets around the selection? Specifically, if there are no alphanumeric characters in the selection, then it shouldn't be applied. This would cover casting and generic types, as both would have alphanumeric characters within the selection. If the selection does not have any alphanumeric characters, then it's very probably not going to be a case where the user is trying to wrap a selection for casting or as a generic type.

**Comment by waderyan** [comment]
@axefrog thank you for your feedback. This is a good suggestion. 

@dbaeumer just to confirm I understand correctly - this issue should stay in VS Code and not be migrated to TypeScript? In other words who owns the TS extension language configuration (vscode\extensions\typescript\language-configuration.json)?

**Comment by dbaeumer** [comment]
We :-)

**Comment by mjbvz** [comment]
I'm unable to repo in current insiders builds. I believe this was fixed by c5251468766314f6ed634303adc3a765cf621966

Please let me know if you still see the problem.

Thanks
