### ISSUE TITLE
Find action name by its keyboard shortcut

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#139699]
Issue Type: <b>Feature Request</b>

I just pressed Ctrl-E by accident and want to know what it's doing. I can't find it in the menus. I'd like to be able to know what a keyboard shortcut does by pressing it in a similar context to that input thing for when you set one.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting

**Comment by sdegutis** [comment]
That's a lot harder to use.

**Comment by gjsjohnmurray** [comment]
What about running the command to toggle screencast mode?

**Comment by sdegutis** [comment]
That just shows me I pressed Ctrl-E which I already know. I want to know what Ctrl-E is doing.

**Comment by ArturoDent** [comment]
Did you try the "Record Keys" functionality in the Keyboard Shortcuts page?  Click the keybiard icon and type Ctrl+E.

**Comment by sdegutis** [comment]
That kinda works.

1. It shows this shortcut along with several others, so I have to scan it
2. I have to type out the whole thing instead of just pressing it

But just letting me press the shortcut in a box and tell me its title/info would be easier.

**Comment by ArturoDent** [comment]
You can just press Ctrl+E - that is what I meant sorry.

**Comment by sdegutis** [comment]
Pressing it in that window didn't work. It just ran its command.

**Comment by ArturoDent** [comment]
You didn't click the little keyboard icon to the right.

**Comment by gjsjohnmurray** [comment]
> What about running the command to toggle screencast mode?

Looks like only some keycombos manage to display the command name in screencast mode. For example, Ctrl+Shift+P and Ctrl+Shift+E and Ctrl+Shift+X do but Ctrl+Shift+F doesn't.
