### ISSUE TITLE
Wrong value show for `this` on hover in es6 arrow syntax

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#13967]
_From @ventsislav-georgiev on October 18, 2016 13:25_

The **ES6** `arrow syntax` preserves `this` to be the parent scope. However, in VSCode node debugging the on hover provider shows the `bind`-ed value of `this`, which is really confusing while debugging.

![image](https://cloud.githubusercontent.com/assets/5616486/19479439/69c70a20-954f-11e6-9df3-351e68782a54.png)

> Note: that evaluation or `console.log` in the debug console shows the correct value of `this`.

**VSCode version:**
1.6.1

**Node Debug version:**
1.6.10

**Code to reproduce**

``` js
(function() { 
    console.log(`parentScope: ${this.fake}`);

    (() => { 
        console.log(`childScope: ${this.fake}`);
        debugger;
    }).call({ innerFake: "innerFakeValue" }); 

}).call({ fake: "fakeValue" });
```

_Copied from original issue: Microsoft/vscode-node-debug#103_

**Comment by adelphes** [comment]
As a workaround, adding **this** as an explicit watch value appears to show the correct value. Still, having the hover and variable windows showing the wrong value is incredibly confusing during debugging.

**Comment by isidorn** [comment]
This is the current limitation of the debug hover. Namely it searches through the variables to find the matching hovered one. If you look in the variables list you will find exactly the value that the hover shows.

Evaluate produces a different result, and each debug adapter can choose if it wants to instead evaluate on hover. Node debug is not doing that.

Thus assigning this to @roblourens to consider changing this in the future

**Comment by roblourens** [comment]
This is coming from the runtime and reproes in Chrome DevTools. I filed https://bugs.chromium.org/p/chromium/issues/detail?id=660951

**Comment by roblourens** [comment]
Chrome status from a few weeks back:

> Fix should be available in one of the next Canary this week.

I can confirm fixed in Canary today.
