### ISSUE TITLE
[FEATURE] Disable Keyboard Shortcut

### ISSUE THREAD

**Issue by Yash-Singh1** [microsoft/vscode#139655]
Currently, when I want to make a keyboard shortcut not work or disable it temporarily, either I have to disable it or set it to something like `editorReadonly && !editorReadonly`. Maybe there could be a when expression like `never` or there could be an option to disable keyboard shortcuts temporarily so I can reenable it later.

**Comment by IllusionMH** [comment]
You can delete shortcut in Shortcuts editor, it would jusd add `- command.id` for that shortcut. Or do that manually.
You can always remove that object from `keybindings.json` at any time to restore.
