### ISSUE TITLE
word not italic when typing in comment

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#139662]
Version:

```
Version: 1.64.0-insider (Universal)
Commit: 7b9e5c32a053669d4e72f998e4fa217090c32f59
Date: 2021-12-22T05:14:43.841Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0
```

Steps to Reproduce:

1. copy `// 注释文` to a ts file
2. toggle Chinese Input
2. press `zi`

![image](https://user-images.githubusercontent.com/41773861/147180104-c6e1d179-1915-4b6a-9a7e-acc99bb83519.png)

**Comment by tjx666** [comment]
@jrieken

**Comment by hediet** [comment]
I think this is a technical limitation of how support for IME is implemented. This is very complex and I don't think there is a solution to that.

**Comment by alexdima** [comment]
Currently, when made visible, the `<textarea>` uses the default foreground color and the default font style, it is not set to the color / font style of the text it renders on top. It is possible that sometimes it renders over multiple tokens which would have distinct styles.
