### ISSUE TITLE
Cannot see more than one terminal per editor group, re-open #138870

### ISSUE THREAD

**Issue by dowel** [microsoft/vscode#139653]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: macOS Big Sur 11.6.1
- Remote OS: Ubuntu 20.04.3

Steps to Reproduce:
![out](https://user-images.githubusercontent.com/417396/147152042-f22c8d4b-4b2e-4096-be68-a17cd9ce76e0.gif)

**Comment by hilaolu** [comment]
Same problem. I also am on 1.63.2.
https://github.com/microsoft/vscode/issues/139677

**Comment by Tyriar** [comment]
Fixed the milestone in the linked https://github.com/microsoft/vscode/issues/139222, this is fixed in the upcoming version.

**Comment by dowel** [comment]
I confirm that it works with latest insiders build. Thank you @Tyriar .
