### ISSUE TITLE
Documentation for browser loading grammars and `vscode-oniguruma` library

### ISSUE THREAD

**Issue by SNDST00M** [microsoft/vscode#139683]
There is a serious dearth of documentation on how I'm meant to loadWasm (Oniguruma) and loadGrammar (Textmate) on the browser.
The `vscode-textmate` module has the working Node.js logic for this but not the browser side.

I.e. I want to load:

- raw grammar files from extension
- files like ./language-configuration.json relative to `extensionPath`
- onig.wasm in `vscode-oniguruma` as array buffer

**Comment by SNDST00M** [comment]
Right Web is Joyce yet TM is Alex D and Ben 🤔 Help! 😃

**Comment by alexdima** [comment]
@SNDST00M This is mentioned briefly [here](https://github.com/microsoft/monaco-editor#faq). Please see https://github.com/bolinfest/monaco-tm for a community written project showing how `vsode-textmate` and `vscode-oniguruma` can be loaded in a browser.

Regarding reading grammar files and language-configuration files, this all depends on where you're running, if you are writing a vscode web extension, then the only available thing is `fetch`.

**Comment by SNDST00M** [comment]
Okay I figured out the URL for reading grammar files, it's `Uri.joinPath(vscode.extensions.getExtension('<ID>').extensionUri.toString(), '<PATH>')`.

Can't I just use the `vscode-textmate` and `vscode-oniguruma` that ship with VS Code for the Web though?
All I'd need is the azureedge URL that the vscode web app actually ships with
