### ISSUE TITLE
[bug] can't open file with no extension name in a folder which name cotain space character

### ISSUE THREAD

**Issue by DirtyBat** [microsoft/vscode#139694]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.63.2
- OS Version: windows 11 21H2

Steps to Reproduce:

1.Create an folder anywhere which name contain a space (e.g. folder name "a test folder with space")
2.Create an text file in the folder we create in step one, then delete the file extension name (e.g. create a file named test.txt, and then delete .txt)
3.Open the file we create in step two by vscode, then we got:
![image](https://user-images.githubusercontent.com/17296733/147265035-c42b6c3f-87b5-44af-a121-34f19129be80.png)

There is some issue happen with the path, the tab name "a" in the pic above, is actually the folder name before the first space.

**Comment by JacksonKearl** [comment]
I haven't been able to reproduce this, could you include a screen recording and sample workspace? 
![image](https://user-images.githubusercontent.com/8586769/147973076-9b8edb29-eb61-48ec-bdcd-0db3dcfa4e8f.png)

\gifPlease

**Comment by DirtyBat** [comment]
> 

https://user-images.githubusercontent.com/17296733/148249423-2b61b555-c510-492d-afb4-7bab17b7de6b.mp4

**Comment by DirtyBat** [comment]
https://user-images.githubusercontent.com/17296733/148249692-36bc9258-e065-4c42-9740-4eef50423881.mp4

**Comment by DirtyBat** [comment]
> I haven't been able to reproduce this, could you include a screen recording and sample workspace? ![image](https://user-images.githubusercontent.com/8586769/147973076-9b8edb29-eb61-48ec-bdcd-0db3dcfa4e8f.png)
> 
> \gifPlease

I upvote an vedio above

**Comment by JacksonKearl** [comment]
I've tried a couple times and have never been able to reproduce this. I'm going to close it as not-reproducible, but if you feel passionate about this I will consider PR's or reopening it.
