### ISSUE TITLE
Go To File Not Working

### ISSUE THREAD

**Issue by jmatos** [microsoft/vscode#139642]
Issue Type: <b>Bug</b>

When I press CMD+P and type a file name, I only see "recent files" show up and not other files that I know exist in my workspace.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.19GB free)|
|Process Argv|--crash-reporter-id bfd065a4-8e1c-44d6-8a81-fce638c657a3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
sync-scroll|dqi|1.3.0
gitlens|eam|11.7.0
vscode-pull-request-github|Git|0.34.2
vscode-graphql|Gra|0.3.41
plantuml|jeb|2.17.0
rainbow-csv|mec|1.10.1
prophet|Sqr|1.4.25
code-navigation|vik|0.2.0
vscode-icons|vsc|11.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710cf:30416617
vscexrecpromp3t3:30407764

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe #139056 or #139172

**Comment by jmatos** [comment]
@gjsjohnmurray I looked at those issues and yes, the issues are similar to what I'm seeing.  Is there any way to download a prior version of vs code?

**Comment by IllusionMH** [comment]
Some options available at updates pages (e.g. there is no zip download)
https://code.visualstudio.com/updates/v1_62
Do not forget to set `"update.mode": "none"`

**Comment by jmatos** [comment]
I installed prior versions with no luck - same issue - went back as far as June 2021 (version 1.58).
Any other ideas?

**Comment by jmatos** [comment]
I renamed/deleted my vscode workspace file and just opened the folder that had my files in it and CMD+P started working again with the latest version of vscode.

**Comment by gjsjohnmurray** [comment]
> I renamed/deleted my vscode workspace file and just opened the folder that had my files in it and CMD+P started working again with the latest version of vscode.

Sounds similar to https://github.com/microsoft/vscode/issues/139172#issuecomment-996928435

**Comment by jmatos** [comment]
Yes it does sound similar but in the other issue, deleting the workspace did not work for him - I'm glad this worked for me because I did not relish the idea of having to switch to a new IDE!

**Comment by TylerLeonhardt** [comment]
Hmm I'd like to understand this issue more but it sounds like you managed to unblock yourself. If you happen to see this more frequently, we can dig in deeper.
