### ISSUE TITLE
Disable formatter for some part of code

### ISSUE THREAD

**Issue by caiqichang** [microsoft/vscode#139617]
like formatter markers in comments

In Java:
```java
// @formatter:off
code in this block will not be formatted
// @formatter:on
```

In Html:
```html
<!-- @formatter:off -->

<!-- @formatter:on -->
```

**Comment by aeschli** [comment]
Every formatter has a different implementation. That means we need separate feature requests per language.

For the built-in HTML formatter this already is possible with the setting `html.format.unformattedContentDelimiter`.
You can define a keyword of your choice:
```json
"html.format.unformattedContentDelimiter": "<!--noformat-->",
```

And use it like that:
```html
<body>
	<!--noformat-->
	<div       id="container"         style="width:800px;height:600px;border:1px solid #ccc"></div>
	<!--noformat-->
</body>
```
The built-in HTML formatter is based on jsbeautify. Additional feature requests or bug reports around that setting need to be filed there: https://github.com/beautify-web/js-beautify/issues

Assigning to @mjbvz for the built-in TypeScript/Java Script

**Comment by mjbvz** [comment]
We already have an upstream issue tracking this for JS/TS https://github.com/microsoft/TypeScript/issues/18261

**Comment by Moyura2017** [comment]
// prettier-ignore
matrix(
  1, 0, 0,
  0, 1, 0,
  0, 0, 1
)
//https://prettier.io/docs/en/ignore.html
