### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by nelrafa103** [microsoft/vscode#139637]
- Issue Type: `Bug`
- Extension Name: `microsoft-authentication`
- Extension Version: `0.0.1`
- OS Version: `Linux x64 5.15.8-76051508-generic`
- VS Code version: `1.60.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 274,
		"activateCallTime": 3,
		"activateResolvedTime": 3852,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "vscode.microsoft-authentication",
				"_lower": "vscode.microsoft-authentication"
			},
			"activationEvent": "onAuthenticationRequest:microsoft"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by IllusionMH** [comment]
> VS Code version: 1.60.1

Please update to latest version which is 1.63.2 and check again.
