### ISSUE TITLE
Allow close on popup message

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/vscode#139734]
Issue Type: <b>Bug</b>

See image, there is currently no way for me to close this message?

I really don't need to restart in this case as I am only reading text.

![snap-20211224-01](https://user-images.githubusercontent.com/439226/147369799-a43e9fa9-1fb6-4993-9c08-ccbea5f6bf2b.png)

VS Code version: Code - Insiders 1.62.0-insider (0f7f6e338a4e86306474d4d01bdea9b8fe798017, 2021-10-27T05:16:22.862Z)
OS version: Linux x64 5.15.8-1-default
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 4199)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|62.71GB (54.52GB free)|
|Process Argv|/home/yadav/dev/docs/guides --crash-reporter-id 210d9130-10f4-4cf9-ad76-187d60112fd6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma5|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (71)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.2
vscode-base64|ada|0.1.0
vscode-tomcat|ada|0.12.1
markdown-navigation|Ala|1.0.3
Bookmarks|ale|13.2.2
aws-toolkit-vscode|ama|1.34.0
ng-template|Ang|13.1.0
vscode-apollo|apo|1.19.9
vscode-browser-preview|auc|0.7.2
vscode-tailwindcss|bra|0.7.4
dep|car|0.1.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.6.0
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
java-decompiler|dgi|0.0.2
java-debug|DSn|0.0.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
vscode-lombok|Gab|1.0.1
terraform|has|2.17.0
haskell|has|1.8.0
markdown-preview-bitbucket|hbr|1.0.0
java-properties|ith|0.0.2
vscode-peacock|joh|4.0.0
solidity|Jua|0.0.136
language-haskell|jus|3.4.0
sort-typescript-imports|mic|1.4.1
vscode-docker|ms-|1.18.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
cpptools|ms-|1.7.1
vscode-typescript-tslint-plugin|ms-|1.3.3
angular2-inline|nat|0.0.17
vetur|oct|0.35.0
vscode-boot-dev-pack|Piv|0.1.0
vscode-manifest-yaml|Piv|1.29.0
vscode-spring-boot|Piv|1.29.0
platformio-ide|pla|2.4.0
java-ide-pack|pve|1.2.1
vscode-thunder-client|ran|1.9.1
fabric8-analytics|red|0.3.5
java|red|1.2.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.2
vscode-yaml|red|1.2.2
vue-vscode-snippets|sdr|2.2.1
markdown-preview-enhanced|shd|0.6.1
vscode-checkstyle|she|1.4.1
java-generate-setters-getters|soh|7.4.0
sonarlint-vscode|Son|3.1.0
sass-indented|syl|1.8.18
language-stylus|sys|1.15.0
serverless-ide-vscode|Thr|0.5.32
find-then-jump|tra|2.0.5
sort-lines|Tyr|1.9.1
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.0
vscode-maven|vsc|0.34.2
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.8.0
better-align|wwm|1.1.6
vscode-java-saber|You|0.1.2
markdown-pdf|yza|1.4.4
vscode-aspell|zap|0.1.4

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
vsc_aa:30263845
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
vscop804:30404766
vscop341:30404997
vsclayoutctrt:30405800
py55gd98cf:30408622
vscexrecpromp3c:30407757
azactmsal:30409287

```

</details>

**Comment by tanhakabir** [comment]
This pop up is created by the platformio-ide extension so they decide what options to display in their notifications. I'd suggest creating an issue here for them to modify their notifcations: https://github.com/platformio/platformio-vscode-ide
