### ISSUE TITLE
Is there a way to select the item by default when using "window.createQuickpick"?

### ISSUE THREAD

**Issue by taronlee** [microsoft/vscode#139789]
in QuickPickItem in your documents,
>/**
         * Optional flag indicating if this item is picked initially.
         * (Only honored when the picker allows multiple selections.)
         *
         * @see {@link QuickPickOptions.canPickMany}
         */
        picked?: boolean;

When using `window.createQuickpick`, picked property doesn't work you said.

Is there a way to select the item by default?

**Comment by TylerLeonhardt** [comment]
You can set `selectedItems` on the quick pick to the items you want to be selected.
