### ISSUE TITLE
VS Code is not responding

### ISSUE THREAD

**Issue by Khaan25** [microsoft/vscode#139759]
Issue Type: <b>Bug</b>

Please Help me out!
I opened vs code to work but 7 to 8 times, it got unresponsive and CCPU usage was 50%, tried using it with disabled extensions but same issue.
I think it is maybe vs code?

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (9.20GB free)|
|Process Argv|--crash-reporter-id 6ef4d349-a7da-4aba-8ea6-e872c88d9f96|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vscode-css-formatter|aes|1.0.2
node-snippets|chr|1.3.3
bracket-pair-colorizer|Coe|1.0.62
vscode-html-css|ecm|1.10.2
vsc-material-theme|Equ|33.2.2
vscode-pull-request-github|Git|0.34.2
scss-allman-formatter|Gra|1.0.2
vscode-gutter-preview|kis|0.29.0
vscode-autoprefixer|mrm|3.0.1
html-fmt-vscode|Nik|0.7.2
material-icon-theme|PKi|4.11.0
vscode-css-peek|pra|4.2.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
px-to-rem|sai|1.3.1
eta-vscode|sha|1.0.0
svg-preview|Sim|2.8.3
html-to-css-autocompletion|sol|1.1.2
JavaScriptSnippets|xab|1.8.0
One-dark-pro|zhu|3.11.3
html-css-class-completion|Zig|1.20.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710cf:30416617
vscexrecpromp3t1:30407762

```

</details>

**Comment by tanhakabir** [comment]
Hm do you have more details of the exact processes from VS Code running when you see such a huge CPU usage?

**Comment by Khaan25** [comment]
Now it happens sometimes... when it lags, it takes about 30 seconds or more then become normal

**Comment by tanhakabir** [comment]
Could you share the paths for the processes causing the spike?
