### ISSUE TITLE
HTML menu

### ISSUE THREAD

**Issue by KekOnTheWorld** [microsoft/vscode#139715]
The file edit selection view go run terminal and help menu as a themed menu in html not a native menu

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo what version and platform are you using?

Also, what is your `window.titleBarStyle` setting?

**Comment by KekOnTheWorld** [comment]
Im using pop os 21.10 but does this matter? All i wanted to say was that it'd be cool if vscode had the ability to transform its native menu to an html themed menu. maybe even a frameless window

**Comment by sbatten** [comment]
Since you are on linux, the default is the native menu (since we cannot compensate in html for the many stylings of linux desktop window managers). However, if you are happier with Windows-styles html menus, you can enable these with `window.titleBarStyle` => `custom`
