### ISSUE TITLE
Running Infinite Loop

### ISSUE THREAD

**Issue by RajnishPuri** [microsoft/vscode#139771]
Issue Type: <b>Bug</b>

I am working on DSA and I'm doing my simple code of traversal but It returns me an Infinite loop instead of finite values. I checked the same code on an online compiler like chef code IDE It gives me finite values.
My code is :-
#include<stdio.h>
#include<stdlib.h>
struct node{
    int data;
    struct node *next;
};
void display(struct node *head){
    int i=1;
    while (head!=NULL)
    {
        printf("Element %d is : %d\n", i, head->data);
        head=head->next;
        i++;
    }
    
}
int main()
{
    struct node *prev, *p, *head;
    int count;
    printf("Enter the total number of element : ");
    scanf("%d", &count);

    head=NULL;
    for (int i = 0; i < count; i++)
    {
        p=(struct node*)malloc(sizeof(struct node));

        printf("Enter the %d Element : ", i+1);
        scanf("%d", &p->data);
        if (head==NULL)
        {
            head=p;
        }
        else{
            prev->next=p;
        }
        prev=p;
    }

    display(head);
    
    return 0;
}

My Input is:-
5
1
2
3
4
5
Expected Output:-
1
2
3
4
5
But it gives me an Infinite loop

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.67GB free)|
|Process Argv|--crash-reporter-id c7b3ce3f-cd80-40e7-9c6d-9ca77d8d9fd9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
competitive-programming-helper|Div|5.8.7
vscode-html-css|ecm|1.10.2
code-runner|for|0.11.6
better-cpp-syntax|jef|1.15.10
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
cpptools|ms-|1.8.0-insiders2
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710:30416614
py55gd98:30411514
vscexrecpromp3t1:30407762

```

</details>

**Comment by heartacker** [comment]
That is your code problem.

**Comment by RajnishPuri** [comment]
sir but the same code is running on other IDE.

**Comment by heartacker** [comment]
1. **VSCODE is NOT IDE**.
2. The problem is related to c compiler
3. have a try
```c
#include <stdio.h>
#include <stdlib.h>
struct node
{
    int data;
    struct node *next;
};
void display(struct node *head)
{
    int i = 1;
    while (head != NULL)
    {
        printf("Element %d is : %d\n", i, head->data);
        head = head->next;
        i++;
    }
}
int main()
{
    struct node *prev, *p, *head;
    int count;
    printf("Enter the total number of element : ");
    scanf("%d", &count);

    head = NULL;
    for (int i = 0; i < count; i++)
    {
        p = (struct node *)malloc(sizeof(struct node));

        printf("Enter the %d Element : ", i + 1);
        scanf("%d", &p->data);
        if (head == NULL)
        {
            head = p;
        }
        else
        {
            prev->next = p;
        }
        prev = p;
        // try this
        prev->next = NULL;
    }

    display(head);

    return 0;
}

```
