### ISSUE TITLE
Weird gradient on context menu on wayland

### ISSUE THREAD

**Issue by 3nt3** [microsoft/vscode#139751]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3)
- OS Version: NixOS 22.05 unstable, kernel version 5.10.87

![2021-12-25T20:55:22+01:00_cropped](https://user-images.githubusercontent.com/39235738/147392701-82a5fa40-097b-4eb0-89fd-7ec5b39b7046.png)

Steps to Reproduce:

1. start code with 
```sh
code --enable-features=UseOzonePlatform --ozone-platform=wayland
```
2. the context menu is weird.

**Comment by mawoka-myblock** [comment]
Having the same problem, but some options are completely invisible

**Comment by xsrvmy** [comment]
Same issue here. It's only a problem if you use native title bar. Another similar issue is that tooltips are broken.
This is possibly related: #136390

**Comment by xsrvmy** [comment]
Update:
I have two monitors: build in at 2x scale and external at 1x scale. The bug only occurs with both monitors connected, so I suspect the scale is not being detected correctly. Note sure if this is a vscode or an electron bug.

There is a workaround if you only use vscode on one screen: add --force-device-scale-factor=2 (or whatever scale you use) to the argument list.

**Comment by xsrvmy** [comment]
Update:
I have two monitors: build in at 2x scale and external at 1x scale. The bug only occurs with both monitors connected, so I suspect the scale is not being detected correctly. Note sure if this is a vscode or an electron bug.
The opposite happens on KDE: native menus always take 2x scale space, meaning on the 1x screen black boxes appear.

There is a workaround if you only use vscode on one screen: add --force-device-scale-factor=2 (or whatever scale you use) to the argument list.

**Comment by KucharczykL** [comment]
Can confirm that with two monitors connected and one set to 2x scaling on KDE Plasma causes the menus to be cropped. Using the `--force-device-scale-factor=2` fixes that issue for the monitor scaled to 2x (dragging the window to a 1x scale screen makes everything scaled 4x I believe).

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/136390
