### ISSUE TITLE
GitHub

### ISSUE THREAD

**Issue by PyAndrey** [microsoft/vscode#139700]
Issue Type: <b>Bug</b>

I want to send the changes to GitHub, but an error pops up "Git: git@github.com: Permission denied (pubblickey)". The repository is synchronized by SSH key.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz (2 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|5.89GB (1.83GB free)|
|Process Argv|--crash-reporter-id 84abf8f0-dc5d-4885-80d8-aee19d0500a3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
vscode-sqlite|ale|0.14.0
All-Autocomplete|Ati|0.0.23
color-info|bie|0.7.0
bracket-pair-colorizer|Coe|1.0.62
auto-close-tag|for|0.5.13
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.9
vscode-pull-request-github|Git|0.34.2
fluent-icons|mig|0.0.15
vscode-language-pack-ru|MS-|1.63.3
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
material-icon-theme|PKi|4.11.0
synthwave-vscode|Rob|0.1.10
vscodeintellicode|Vis|1.2.15

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710cf:30416617

```

</details>

**Comment by lszomoru** [comment]
@PyAndrey, are you still able to reproduce this issue. VS Code `1.72` added support for [SSH keys with a passphrase](https://code.visualstudio.com/updates/v1_72#_add-support-for-ssh-keys-with-a-passphrase). 
I will optimistically close this issue but in case you are still experiencing any issues please feel free to re-open it. Thanks!
