### ISSUE TITLE
VSCode randomly deleting whole cells from jupyter notebook

### ISSUE THREAD

**Issue by Gonxolo** [microsoft/vscode#139794]
Issue Type: <b>Bug</b>

start a jupyter notebook and suddenly you will see some cells disappear

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.98GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Tacho%20Producciones/Documents/Practica%20I/algorithm --crash-reporter-id 5ec24c3a-257c-4d0c-a09c-6d79159bca4f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
vscode-sqlite|ale|0.14.0
doxdocgen|csc|1.3.2
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.0.0
latex-workshop|Jam|8.22.0
better-cpp-syntax|jef|1.15.10
csharp|ms-|1.23.17
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
material-icon-theme|PKi|4.11.0
ruby|reb|0.28.1
java|red|1.2.0
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2
vscode-icons|vsc|11.8.0
vscode-ruby|win|0.28.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710cf:30416617
py55gd98:30411514
vscexrecpromp3c:30407761

```

</details>

**Comment by rebornix** [comment]
@Gonxolo can you share a bit more about what you were seeing? Are they markdown cells or code cells? Do they come back when you reopen the file?
