### ISSUE TITLE
Extension 'vscode.git' CANNOT use API proposal: scmValidation

### ISSUE THREAD

**Issue by Vulxan** [microsoft/vscode#139705]
Issue Type: <b>Bug</b>

- VS Code Version: 1.63.2
- OS Version: macOS Monterey 12.1

Steps to Reproduce:

1. Open a Git repo
2. Open OUTPUT

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 8, 8|
|Memory (System)|32.00GB (2.82GB free)|
|Process Argv|people-design --crash-reporter-id 2133163b-be35-40cf-8cb7-cb4a3d4a9511|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.7.4
fe-vscode-plugin|byt|0.0.15
authenticator|byt|0.2.22
cloud-toolkit|byt|0.3.0
gallery|byt|0.4.10
bytesec-vscode|byt|1.0.52
v2ex-playground|cha|1.4.5
path-intellisense|chr|2.6.0
vscode-eslint|dba|2.2.2
docs-markdown|doc|0.2.100
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.7.0
prettier-vscode|esb|9.0.0
vscode-styled-components|jpo|1.7.0
lynx-studio|lyn|1.3.1
git-graph|mhu|1.30.0
vscode-language-pack-zh-hans|MS-|1.63.3
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-typescript-next|ms-|4.6.20211223
vscode-zhihu|niu|0.5.0
vetur|oct|0.35.0
material-icon-theme|PKi|4.11.0
svg-preview|Sim|2.8.3
vscode-styled-components|sty|1.7.2
git|vsc|1.62.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710cf:30416617
vscexrecpromp3t2:30407763

```

</details>

**Comment by Vulxan** [comment]
![CleanShot 2021-12-24 at 10 44 48@2x](https://user-images.githubusercontent.com/32930147/147309938-88f840c8-c1f3-4a03-91b2-7115c63506c4.png)

**Comment by Semperia** [comment]
Hi~ It appears to be a malformed vscode.git extension installed from [OpenVSX registry](https://open-vsx.org/extension/vscode/git), uninstalling it should solve this problem

**Comment by Vulxan** [comment]
@Semperia Thank you for your reply. I'm sure this is a built-in git extension, and I can't find a way to uninstall it.

**Comment by Mrzzchao** [comment]
+1

**Comment by Mrzzchao** [comment]
> 

do you resolve this issue?

**Comment by Vulxan** [comment]
@Mrzzchao Nope. My colleague also had this situation.😂

**Comment by gjsjohnmurray** [comment]
@Vulxan the 1.62.3 version number alongside the git extension entry in the table in the original report looks odd to me. Here's a screenshot from my 1.62.3 (Windows) after running the command to reload with all extensions disabled.

![image](https://user-images.githubusercontent.com/6726799/147342049-c64ab8d8-2635-466e-b34b-ad282021dd1d.png)

It shows version number as 1.0.0

Same result even without running that command first.

`Show Running Extensions` also shows 1.0.0 for the Git one.

**Comment by gjsjohnmurray** [comment]
@Semperia's theory looks good:

![image](https://user-images.githubusercontent.com/6726799/147342431-9f7b72e2-be68-485a-83d9-eceeb0e2b2bb.png)

**Comment by Mrzzchao** [comment]
![image](https://user-images.githubusercontent.com/13391134/147342796-d52ab52a-c0a1-4abc-b2b6-d4625b834b9c.png)
@gjsjohnmurray no the git scm

**Comment by Vulxan** [comment]
@Semperia  @gjsjohnmurray Thank you for your help.
Finally I found the cause of the error. An extension of our team installed the git extension from OpenVSX by itself.

**Comment by gjsjohnmurray** [comment]
@sandy081 is it wise that VS Code allows a built-in extension to be overloaded by installing a VSIX file?

**Comment by Mrzzchao** [comment]
can you tell me the extension that the error?

**Comment by zhanzizhen** [comment]
+1 for me. 
didn't solve problem though i disable all extension except git scm

**Comment by gjsjohnmurray** [comment]
When you filter your Extensions viwe with `@builtin @id:vscode.git` does this appear?

![image](https://user-images.githubusercontent.com/6726799/147344845-edb99b92-8e53-48ad-8df6-0ece3d9a3da9.png)

If not, what does the filter `@installed @id:vscode.git` show?

If an extension lists there, uninstall it.

**Comment by Mrzzchao** [comment]
![image](https://user-images.githubusercontent.com/13391134/147345074-25abbfbc-a683-4210-9f91-39eb0681d94a.png)

**Comment by Mrzzchao** [comment]
i install the 1.62.3 version

**Comment by Vulxan** [comment]
@Mrzzchao @zhanzizhen  You can try to uninstall the Git extension, and then you may find that a certain extension installs the git extension from openVSX by itself

**Comment by zhanzizhen** [comment]
> When you filter your Extensions viwe with `@builtin @id:vscode.git` does this appear?
> 
> ![image](https://user-images.githubusercontent.com/6726799/147344845-edb99b92-8e53-48ad-8df6-0ece3d9a3da9.png)
> 
> If not, what does the filter `@installed @id:vscode.git` show?
> 
> If an extension lists there, uninstall it.

it work for me after unisntall Git(built-in). thanks a lot

**Comment by Mrzzchao** [comment]
yeh i resolve it with it. thanks u

**Comment by mumu1993** [comment]
> ![image](https://user-images.githubusercontent.com/13391134/147345074-25abbfbc-a683-4210-9f91-39eb0681d94a.png)

works for me thx

**Comment by lszomoru** [comment]
> @sandy081 is it wise that VS Code allows a built-in extension to be overloaded by installing a VSIX file?

I want to make sure that you do not lose track of this question. @sandy081, is this expected or a bug? Thanks!

**Comment by sandy081** [comment]
This is useful in some cases where users want to override some builtin extensions which has newer versions available in the Marketplace. Some debugger extensions are following this before and also for some builtin extensions in web.

**Comment by lsongseven** [comment]
I have the same issue (with v1.62.3) and it works when I uninstall it. 

Does it mean that v1.62.3 has a bug?

**Comment by gjsjohnmurray** [comment]
> I have the same issue (with v1.62.3) and it works when I uninstall it.

@lsongseven no, you simply shouldn't be installing that VSIX. The `vscode.git` extension is a built-in one.

**Comment by lsongseven** [comment]
> > I have the same issue (with v1.62.3) and it works when I uninstall it.
> 
> @lsongseven no, you simply shouldn't be installing that VSIX. The `vscode.git` extension is a built-in one.

@gjsjohnmurray but from @sandy081, installing a VSIX vscode.git seems to be an expected approach.


> This is useful in some cases where users want to override some builtin extensions which has newer versions available in the Marketplace. Some debugger extensions are following this before and also for some builtin extensions in web.

**Comment by Semperia** [comment]
> This is useful in some cases where users want to override some builtin extensions which has newer versions available in the Marketplace. Some debugger extensions are following this before and also for some builtin extensions in web.

But it seems the installed extensions that tries to override built-in ones are not able to use proposed apis, is this our misuse?

**Comment by sandy081** [comment]
Yes, overriding the builtin extension makes it user extension and they cannot use proposed apis by default.
