### ISSUE TITLE
File watch failed on linux

### ISSUE THREAD

**Issue by kekeliu-whu** [microsoft/vscode#139709]
Issue Type: <b>Bug</b>

The bug is easy to reproduce:  
`sudo mkdir -p /FOLDER/tmp /folder && code /FOLDER/tmp`  
Type the command above in **an path-case-sensitvie system, for example Linux**, you can see the notification:  
```bash
File changes watcher stopped unexpectedly. A reload of the window may enable the watcher again unless the workspace cannot be watched for file changes.
```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.11.0-43-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|19.39GB (0.25GB free)|
|Process Argv|--unity-launch --crash-reporter-id b60b612e-16a8-49da-889c-b292f55684de|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>

<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30414010
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614
py55gd98:30411514
vscexrecpromp3c:30407761

```

</details>

**Comment by kekeliu-whu** [comment]
[](url
![Screenshot from 2021-12-24 14-35-23-2](https://user-images.githubusercontent.com/19950321/147326242-108e03d1-3a36-4505-9d83-b3ee6dfeeb02.png)
)

Screenshoot is shown above.

**Comment by kekeliu-whu** [comment]
Here is the screenshoot:
![Screenshot from 2021-12-24 14-35-23-2](https://user-images.githubusercontent.com/19950321/147326338-4b8dd32b-ea4d-4836-bbaa-1411433d0253.png)

**Comment by bpasero** [comment]
What a great bug 👏 . Turns out, on Linux we never wanted to cal `realPathSync`, it was an oversight when I added the parcel watcher.
