### ISSUE TITLE
JS: element innerText property doesn't pop in member list if select by class

### ISSUE THREAD

**Issue by JustinWebDev** [microsoft/vscode#139735]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.63.2
- OS Version:  W10 v21H1 x64

Steps to Reproduce:
For the below code, start typing "inner" for the "x." element -> only "InnerHTML" shows, but for the "z." element both "innerText" and "innerHTML" show in the member list.

```
<html>
<button class="copyLink">copy this link</button>
<script>
let z = document.querySelector('button'); z.
let x = document.querySelector('.copyLink'); x.
</script>
</html>
```

**Comment by mjbvz** [comment]
Hover over the types for `z` and `x`. VS Code can infer that `z` is a `HTMLButtonElement` but does not know the more specific element type of `x` so it is just `Element`. Not every type of element returned by that querySelector would have an `innerText` property

If you know the types of the elements you are retrieving though, just add a cast:

```js
/** @type {HTMLElement} */ let x = document.querySelector('.copyLink')
```

**Comment by JustinWebDev** [comment]
So, VSC doesn't know how to understand the code for a class identifier in the querySelector method, but it does for an element?  How does VSC know that x even has an "InnerHTML" property if it doesn't know exactly what kind of element is it?  This is why I reported it has a bug.  I'd expect both to properly understand the element type.

Thanks, @mjbvz  for the detailed explanation.
