### ISSUE TITLE
since November 2021 update getting strange marks on hebrew text

### ISSUE THREAD

**Issue by felix007** [microsoft/vscode#139775]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.
![issue](https://user-images.githubusercontent.com/1016496/147416462-23cc26ef-a845-406a-923d-843055e12263.png)
since November 2021 update getting strange marks on hebrew text
Disabled all extensions with no success.
Don't know how to disable those markers.
rolled back to  October 2021 (version 1.62) and no markers
![22](https://user-images.githubusercontent.com/1016496/147416553-c97f7f58-10ab-4331-a953-224adb79924a.png)

**Comment by IllusionMH** [comment]
Looks like this is part of https://code.visualstudio.com/updates/v1_63#_unicode-highlighting because letters might be ambiguous characters. See post provided settings on how to disable these warnings.

Also see #138767 that should track OS locale and not warn.
/duplicate
