### ISSUE TITLE
code hanging updating plugin

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#13973]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:43:46.054Z)
- OS Version: Linux x64 4.4.0-43-generic
- Extensions: DavidAnson.vscode-markdownlint-0.5.0, EditorConfig.EditorConfig-0.3.3, ajhyndman.jslint-1.2.1, dbaeumer.jshint-0.10.15, dbaeumer.vscode-eslint-1.0.8, eg2.tslint-0.5.39, jakethashi.vscode-angular2-emmet-1.0.9, ms-vscode.cpptools-0.9.2, msjsdiag.debugger-for-chrome-1.2.2, vscodevim.vim-0.3.8

Steps to Reproduce:
1. install vccodevim
2. hangs during update, need to kill vscode

I tired it with markdownlint, it takes a long time but eventually come around.

**Comment by rajinder-yadav** [comment]
Also when the plugin is finally installed, I am unable to click on the blue "enable" button and vscode hangs.

vscode just timed out after I updated another plugin, and needed to be closed.

**Comment by joaomoreno** [comment]
During the _hang_, can you click around, select text, etc? Can you screencast the _hang_?

**Comment by rajinder-yadav** [comment]
The hang seems to have gone away in the latest update, closing this issue.
