### ISSUE TITLE
Open integrated terminal in directory of current file

### ISSUE THREAD

**Issue by sdwarwick** [Microsoft/vscode#13974]
- VSCode Version: 1.6.1
- OS Version: windows

ctrl ` to open terminal window opens in  top level directory where .vscode is stored.  how about allowing the option to open in the directory of the file in the current active window?

**Comment by Tyriar** [comment]
You can currently do this using the following extension: https://marketplace.visualstudio.com/items?itemName=Tyriar.vscode-terminal-here
