### ISSUE TITLE
Non-Standard Operation of CTRL-C

### ISSUE THREAD

**Issue by OneMonkeyArmy** [microsoft/vscode#139755]
Issue Type: <b>Bug</b>

It has been more than 30 years, that CTRL-C ann CTRL-V works the same way... Once something has been copied into CTRL-C, even if you hit CTRL-C again, while nothing is selected, it keeps it's previous copied data, but your editor does something so anoying, it deletes the content... I hope you gonna correct it ASAP, because I am about to throw the keyboard by the window... !

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.95GB (38.81GB free)|
|Process Argv|--crash-reporter-id 8fdf969f-c808-4164-bb3a-57ae5c4e14cd|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by yume-chan** [comment]
This is how many other code editors work.

You can change by setting `"editor.emptySelectionClipboard": false`

**Comment by OneMonkeyArmy** [comment]
Thank you very much!
