### ISSUE TITLE
Integrated Terminal doesn't clean properly when using bash on Windows

### ISSUE THREAD

**Issue by ahlechandre** [Microsoft/vscode#13975]
- VSCode Version: 1.6.1
- OS Version: Microsoft Windows [10.0.14393]
- GNU bash: 4.3.42(5)-release

Steps to Reproduce:
1. Define the shell as bash by using: `"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"`.
2. Open terminal with `CTRL + '` or **View > Integrated Terminal**.
3. Run commands and try to clear with `clear` command or `CTRL + L` shortcut.

![image](https://cloud.githubusercontent.com/assets/7119058/19506231/86c147fe-95a8-11e6-80e9-a95695e389fd.png)

> Actually, this occurs only with bash (no problems with default `cmd.exe` running `cls`).

**Comment by willi84** [comment]
it also not clear the input correctly when u want to change a command and using the arrow-keys

**Comment by Tyriar** [comment]
Seems to work now
