### ISSUE TITLE
Cannot set "sideBySideEditor.<horizontal/vertical>Border.width"

### ISSUE THREAD

**Issue by ROBCON-Software** [microsoft/vscode#139795]
Issue Type: <b>Bug</b>

when used custom color for sideBySideEditor.horizontalBorder and tab.activeBorderTop - these are not visible because of null width of borders between splitted editor windows.

![2021-12-27_11-14-59_Code](https://user-images.githubusercontent.com/92823350/147463311-606ed750-7b7d-467c-9117-b8421557fdb7.jpg)

and the "scrollbars" arrows still works... but they cannot be modified ? (size)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.45GB (5.40GB free)|
|Process Argv|--crash-reporter-id 3b9681cd-15f0-4f8b-bbe9-d60f9ba7298c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.1.0
overtype|ada|0.2.0
project-manager|ale|12.4.0
gitignore|cod|0.7.0
bracket-pair-colorizer-2|Coe|0.2.2
dart-code|Dar|3.31.20211214
flutter|Dar|3.31.20211214
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|11.7.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
indent-rainbow|ode|8.2.2
material-icon-theme|PKi|4.11.0
local-history|xyz|1.8.1
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614
vscexrecpromp3t3:30407764

```

</details>

**Comment by alexdima** [comment]
`editor.scrollbar.verticalHasArrows` and `editor.scrollbar.horizontalHasArrows` are greyed out because they are not supported. That is why they look so unpolished, etc. There are no plans to invest in the way they look because they are not supported. However, a PR to improve them is welcome.

Regarding `activeBorderTop`, this might be caused by the recent vertical arrangement work, or it might be a long-standing issue with the grid, I'm not sure.

**Comment by bpasero** [comment]
I cannot reproduce:

![image](https://user-images.githubusercontent.com/900690/148893097-420efc67-2643-45f3-bab6-e7e741ccfa17.png)

Configured:

```json
"sideBySideEditor.horizontalBorder": "#ff0000",
"tab.activeBorderTop": "#ff0000"
```

**Comment by bpasero** [comment]
@alexdima 

> this might be caused by the recent vertical arrangement work

What is that?

**Comment by alexdima** [comment]
I was thinking about the split vertical editors, but it looks like the border renders fine between those.

But @bpasero , looking at your screenshot, isn't the problem that the lower tab is missing the red top border:

<img width="764" alt="Screen Shot 2022-01-13 at 22 11 22" src="https://user-images.githubusercontent.com/5047891/149409856-bd7263c0-0671-426a-ac03-251daca15e45.png">

**Comment by bpasero** [comment]
Oh yeah! Addressed via https://github.com/microsoft/vscode/issues/140685

My complicated `z-index` explainer just become more complex:

https://github.com/microsoft/vscode/blob/b61f91f54a081567fd9faf501c520172d046e99a/src/vs/workbench/browser/parts/editor/media/tabstitlecontrol.css#L7-L39

**Comment by ROBCON-Software** [comment]
please distinguish between "splitted screen" and "splitted in group" = 2 diff. things.

> I cannot reproduce:
> 
> ![image](https://user-images.githubusercontent.com/900690/148893097-420efc67-2643-45f3-bab6-e7e741ccfa17.png)
> 
> Configured:
> 
> ```json
> "sideBySideEditor.horizontalBorder": "#ff0000",
> "tab.activeBorderTop": "#ff0000"
> ```

![obrázok](https://user-images.githubusercontent.com/92823350/149507661-4e97b5fc-5494-4a71-804e-72bbfa1cb629.png)

**Comment by bpasero** [comment]
@ROBCON-Software the issue https://github.com/microsoft/vscode/issues/140685 fixes is number 2, the top color above tabs not appearing.

I did not encounter any other issue but maybe you can share your color settings with me.

**Comment by ROBCON-Software** [comment]
which of them please ? and from which files ? settings.json and/or other ?

**Comment by bpasero** [comment]
Just your configured settings for `workbench.colorCustomizations` that showcase the issues you face.

**Comment by ROBCON-Software** [comment]
"workbench.colorCustomizations": {
        "tab.activeBorder": "#ffff00",
        "tab.activeBorderTop": "#ffff00",
        "tab.activeBackground": "#ffff0030",
        "tab.unfocusedActiveBorder": "#ffff0030",
        "tab.unfocusedActiveBorderTop": "#ffff0030",
        "tab.unfocusedActiveBackground": "#ffff0018",
        "tab.unfocusedInactiveBackground": "#2d2d2d",
        // border between windows,
        "sideBySideEditor.horizontalBorder": "#ff0000",
        "sideBySideEditor.verticalBorder": "#ff0000",
        // indentation lines
        "editorIndentGuide.background": "#fff0"
    },

but perhaps I see where the problem of colors is.

I'm asking about border between file windows - but the red color is for this - in group split...

![obrázok](https://user-images.githubusercontent.com/92823350/149552323-d1beec68-1c76-4f74-b125-02617e12a213.png)

and second - I'm asking about file windows border color - and this is nowhere in settings... but when there are arrows (already unsupported) why there is not file window border color like when You hower over that place and it turns nice blue and You can resize windows of files self...

![obrázok](https://user-images.githubusercontent.com/92823350/149552920-e68e4313-b78d-453f-b0b1-b1b6bf340562.png)

and when the width is as is, You cannot see upper "tab.activeBorderTop" also if I'm usig it as marker for changed files I'm lost...

![obrázok](https://user-images.githubusercontent.com/92823350/149554867-8915c430-a929-4130-b76c-18c7fa49558c.png)

versus

![obrázok](https://user-images.githubusercontent.com/92823350/149555007-7e18a04d-c4c8-40c4-ab7f-3a87e786df9d.png)

**Comment by ROBCON-Software** [comment]
yes, "editorGroup.border" is OK. for color. Thank You.

but still missing (is hidden behind) the in lower active window the "tab.activeBorderTop"

![obrázok](https://user-images.githubusercontent.com/92823350/149556663-be050ca2-02e4-4e3d-8168-50d1c42f9d8f.png)

**Comment by bpasero** [comment]
Yeah that is the same issue I had fixed. Proof:

![image](https://user-images.githubusercontent.com/900690/149557104-41258719-1c19-4612-a7cf-a5910170113b.png)

**Comment by ROBCON-Software** [comment]
thak You for Your effort, but this is not working here :-(

![obrázok](https://user-images.githubusercontent.com/92823350/149557466-2f9adcbd-1eb2-4b58-af9f-75fffb6b2a7e.png)

perhaps missing some Z-index value ?

**Comment by bpasero** [comment]
Yeah sure, the fix was actually to increase `z-index`, but the fix is not deployed yet. It will be available on Monday in our insiders build.

You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by ROBCON-Software** [comment]
thank You very much all mates ! will wait for better version :-) going to learn some code :-D bye.
