### ISSUE TITLE
vscode cant open anypath withing /home/users

### ISSUE THREAD

**Issue by goldcoders** [microsoft/vscode#139791]
I followed installation also got the remote extension plugin
Im using the stable version of vscode

if i do try to use it to open files on windows path
/mnt/c/Users/username

vscode will launch it when typing `code .`

unfortunately i have projects i wanna launch from terminal using code inside /home/user folder

this is the debug output

```
❮ VSCODE_WSL_DEBUG_INFO=true code .
+ COMMIT=899d46d82c4c95423fb7e10e68eba52050e30ba3
+ APP_NAME=code
+ QUALITY=stable
+ NAME=Code
+ DATAFOLDER=.vscode
+ realpath /mnt/c/Users/uriah/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/uriah/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/uriah/AppData/Local/Programs/Microsoft VS Code/bin
+ VSCODE_PATH=/mnt/c/Users/uriah/AppData/Local/Programs/Microsoft VS Code
+ ELECTRON=/mnt/c/Users/uriah/AppData/Local/Programs/Microsoft VS Code/Code.exe
+ IN_WSL=false
+ [ -n Ubuntu ]
+ IN_WSL=true
+ [ true = true ]
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID
+ wslpath -m /mnt/c/Users/uriah/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ CLI=C:/Users/uriah/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ WSL_EXT_ID=ms-vscode-remote.remote-wsl
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/uriah/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/uriah/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --ms-enable-electron-run-as-node --locate-extension ms-vscode-remote.remote-wsl
```

it wont exit i have to press ctrl + C to quit the app

anyone knows why is this happening?

**Comment by aeschli** [comment]
Opening from `/home/user` should work too. 
What Windows build are you on?
Can you see if manually running
`ELECTRON_RUN_AS_NODE=1 "/mnt/c/Users/uriah/AppData/Local/Programs/Microsoft VS Code/Code.exe" "C:/Users/uriah/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js" --ms-enable-electron-run-as-node --locate-extension ms-vscode-remote.remote-wsl`
also does not do anything?

**Comment by aeschli** [comment]
Closing due to lack of additional information
