### ISSUE TITLE
VS Code shows squiggly line under custom file import

### ISSUE THREAD

**Issue by data-bits** [microsoft/vscode#139701]
Issue Type: <b>Feature Request</b>

Let's say I create a file called classes.py and in there I have a class called Player. In the main.py file when I import this file/class VS Code keeps showing a squiggly line and a warning that cannot be resolved.  The code runs fine, but the IDE keeps throwing warnings... Can you fix this issue please? VS Code should know that there's a file with that name there and I'm importing a class from there. Thanks!

<b>Example code:</b>
from classes import Player

<b>Example warning:</b>
[{
	"resource": "/app/main.py",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "reportMissingImports",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules",
			"path": "/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "diagnostic-severity-rules"
		}
	},
	"severity": 4,
	"message": "Import \"classes\" could not be resolved",
	"source": "Pylance",
	"startLineNumber": 3,
	"startColumn": 6,
	"endLineNumber": 3,
	"endColumn": 13
}]

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

**Comment by IllusionMH** [comment]
/causedByExtension

As you can see in example - Pylance extension is source of this issue.
Please report it in extension's repo with information about relevant configurations and file structure.
