### ISSUE TITLE
Cannot open Visual Studio Code

### ISSUE THREAD

**Issue by mtebele** [Microsoft/vscode#13971]
- VSCode Version: 1.6.1
- OS Version: macOS Sierra 10.12

Steps to Reproduce:

1. Open Visual Studio Code

When I launch it, the app icon appears in the dock and it closes when I click it.
Tried with `code --disable-extensions` and the same.

If I type `code --list-extensions` on console it logs the following:

![image](https://cloud.githubusercontent.com/assets/4268555/19499720/57ee27ec-956e-11e6-93c9-f7cf6207b341.png)

I have tried removing app data, uninstalling and installing again, deleting cache, and always the same result.

VSCode Insiders works well.

**Comment by mtebele** [comment]
By the way, I have installed the following extension that I suspect it is causing problems: https://marketplace.visualstudio.com/items?itemName=gyuha.format-on-save

**Comment by joaomoreno** [comment]
@bpasero Looks like the configuration service needs some sanity checking.

@mtebele Please check your user settings file. It might be broken (not valid JSON).

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13606
