### ISSUE TITLE
Electron events "maximize", "unmaximize" and "enter-full-screen" don't get emitted in Linux

### ISSUE THREAD

**Issue by N1kO23** [microsoft/vscode#139719]
On linux the electron events "maximize" and "unmaximize" don't get emitted, instead electron emits the event "leave-full-screen" (This event also gets emitted when the focus is returned). Because of this, 'browser-window-maximize' and 'browser-window-unmaximize' never gets called and for example the maximize/unmaximize icon on custom title bar style doesn't update.

![demo](https://user-images.githubusercontent.com/59277828/147374488-f624598a-3031-4fc6-9e06-12e8af737c3a.gif)

This bug was tested also using the latest insider build with no extensions and it was there as well. Originally thought the issue was with outdated version of electron, but that turned out to not be the case.

**Does this issue occur when all extensions are disabled?:** Yes

- **VS Code Version:** 1.63.2
- **OS Version:** EndeavourOS Linux x86_64
- **Kernel:** 5.15.11-zen1-1-zen
- **Desktop Enviroment:** Plasma 5.23.4
- **Window manager:** KWin

**Steps to Reproduce:**

1. Set window title bar style to custom (Settings -> Window -> Title Bar Style)
2. Restart VSCode for the change to take effect
3. Maximize/Unmaximize window either by snapping window to top, double clicking title bar or by pressing maximize/unmaximize button 
-> The button style won't update

**Comment by Geoxor** [comment]
indeed when toggling between maximize and unmaximize the icon doesn't update

![image](https://user-images.githubusercontent.com/34042825/147374475-82e9dc0c-0aa7-45ed-9453-a81d9c151655.png)
![image](https://user-images.githubusercontent.com/34042825/147374480-116074b8-17ca-4ebc-b373-5b18bf0a7463.png)

**Comment by qexat** [comment]
I also experience the same issue
- **VS Code Version:** 1.62.0
- **OS version:** identical to @N1kO23
- **Kernel:** 5.15.11-arch2-1
- **DE:** identical as well
- **Window manager:** X11

**Comment by N1kO23** [comment]
After digging a bit more into the issue I discovered that the event `'enter-full-screen'` also never gets emitted when entering fullscreen, thus `this._win.isFullScreen()` always returns false, because its value never gets updated to true.

**Comment by N1kO23** [comment]
This issue is no longer relevant as the bug has disappeared, not fully sure if it was from DE or Electron, either way it no longer exists :tada:

**Comment by qexat** [comment]
> This issue is no longer relevant as the bug has disappeared, not fully sure if it was from DE or Electron, either way it no longer exists :tada: 

The new update now uses Electron 17, which fixes the bug.
