### ISSUE TITLE
Auto-completing not working if typing fast

### ISSUE THREAD

**Issue by longrunsoul** [microsoft/vscode#139708]
Issue Type: <b>Bug</b>

1. Install Rust: https://www.rust-lang.org/learn/get-started
2. Install vscode extension ```rust-analyzer```  
3. Create a rust project with the command: ```cargo new my-gtk-app```  
4. Add crate gtk4 to section ```dependencies``` of Cargo.toml file:
![image](https://user-images.githubusercontent.com/76798273/147323127-a81fbd72-4288-403c-8cad-735d9591174f.png)

5. Edit file main.rs to have the following code:  
```rust
use gtk4::{prelude::*, Application, ApplicationWindow, Button};

fn main() {
    let app = Application::builder()
        .application_id("org.gtk-rs.example")
        .build();

    app.connect_activate(build_ui);

    app.run();
}

fn build_ui(app: &Application) {
    let button = Button::builder()
        .label("Press me!")
        .margin_top(12)
        .margin_bottom(12)
        .margin_start(12)
        .margin_end(12)
        .build();

    button.connect_clicked(move |button| button.set_label("Hello World!"));

    let window = ApplicationWindow::builder()
        .application(app)
        .title("My GTK App")
        .child(&button)
        .build();

    window.present();
}
```

6. Wait rust-analyzer to finish its preparation  
7. Test autocompleting as the following gif shows:
![vscode-not-autocompleting](https://user-images.githubusercontent.com/76798273/147323182-e7ff72ac-c177-4ed2-bffc-f2761c318785.gif)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.4.164-1-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2962)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|31.27GB (2.05GB free)|
|Process Argv|/vault/code/rust/my-gtk-app --crash-reporter-id 4f9aedb1-3e5e-4327-8aae-d4ed0dfa3da4|
|Screen Reader|no|
|VM|67%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
dart-code|Dar|3.29.0
flutter|Dar|3.29.0
vscode-eslint|dba|2.2.2
vscode-npm-script|eg2|0.3.23
go|gol|0.30.0
better-cpp-syntax|jef|1.15.10
rust-analyzer|mat|0.2.867
git-graph|mhu|1.30.0
csharp|ms-|1.23.17
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17
vscode-lldb|vad|1.6.10

(1 theme extensions excluded)

</details>

**Comment by hediet** [comment]
I am pretty sure that this is an issue of the rust language server. Please create an issue in the repository of the extension you use for rust support.

**Comment by longrunsoul** [comment]
OK. I will do that later. Thank you for your time.
