### ISSUE TITLE
ctrl+left click not work suddenly

### ISSUE THREAD

**Issue by TonyZhang94** [microsoft/vscode#139712]
My project is written in typescript. Reopen vscode, restart machine, reinstall vscode, disable/enable all extension can't solve this issue.

More context (copy form vscode issue reporter)
![image](https://user-images.githubusercontent.com/13308803/147330686-97913d29-2fa4-41ba-8664-7a35da2648b2.png)

1. my system information
<html>
<body>

CPUs | Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (8 x 3600)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 31.68GB (17.26GB free)
Process Argv | --crash-reporter-id ae045f5f-44d1-4955-bac2-4553574c476c
Screen Reader | no
VM | 0%

</body>
</html>

<html>
<body>

2. my enabled extension
Extension | Author (truncated) | Version
-- | -- | --
vscode-eslint | dba | 2.2.2
prettier-vscode | esb | 9.0.0
tsimporter | pmn | 2.0.1
typescript-hero | rbb | 3.0.0
vscode-commons | red | 0.0.6
vscode-xml | red | 0.18.2

</body>
</html>

3. A/B experiment info
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710:30416614
py55gd98:30411514
vscexrecpromp3t2:30407763

**Comment by TonyZhang94** [comment]
any update here?

**Comment by mjbvz** [comment]
Please share steps and example code to reproduce the problem
