### ISSUE TITLE
Built-in color picker stops working on large css files

### ISSUE THREAD

**Issue by RenuzitV** [microsoft/vscode#139743]
The built-in color picker of VS Code stops working after around 4000 lines of css code.

- VS Code Version: 1.63.2
- OS Version: Windows 11 Home, 10.0.22000 Build 22000

Steps to Reproduce: 
Any css file with a large amount of elements will eventually make color picker stop working.
If you paste a piece of code (rgb() or #FFF) right before where color picker stops working, the code that got pushed down will automatically have its color picker removed for the new code, so I believe this issue does not came from the code that I'm using.

**Comment by Xyenia** [comment]
I can confirm this. At first I thought it was a colorizing extension, so I disabled it. My CSS file has over 4000 lines of code.
At a specific point in the file, the color picker stops. If I grab one color attribute and move it a line above, color picker works on it and the attribute under now doesn't.

So, I started counting backwards through all my color instances (Hex & RGB).

Guess what? I came to 500.

So I created a blank stylesheet and populated it with 520 incrementing classes with a single color.

Guess what? - Color picker shops after the 500th instance of a color attribute. Color picker does not work on the 501st instant of a color attribute.

Can this 500 limit be increased?
.


![image](https://user-images.githubusercontent.com/68520136/152692231-8b25f231-ce5f-4732-ae41-a824d605fb8d.png)

.

**Comment by eguiadaniel** [comment]
Same here. After lines 500 it does not preview anymore colors.
I would like to know if there is any way I can increase this limit.
<img width="577" alt="Captura" src="https://user-images.githubusercontent.com/40235952/187624934-0704b4de-0f35-4d50-ba20-067dd71289bf.PNG">

**Comment by davidlinhares** [comment]
I experienced the same thing, where in a large CSS file it would only show the color picker for the first 500 color codes.

**Comment by rebornix** [comment]
We do have a limit for the colors (500) for performance considerations. We could consider adding a setting to allow increasing it per need.

**Comment by a-hulman** [comment]
> We do have a limit for the colors (500) for performance considerations. We could consider adding a setting to allow increasing it per need.

Yes, definitely, a simple setting or even better a message/alert that for performance reasons, the highlighting was disabled, setting can be adjusted in .....

**Comment by davidlinhares** [comment]
> We do have a limit for the colors (500) for performance considerations. We could consider adding a setting to allow increasing it per need.



> > We do have a limit for the colors (500) for performance considerations. We could consider adding a setting to allow increasing it per need.
> 
> Yes, definitely, a simple setting or even better a message/alert that for performance reasons, the highlighting was disabled, setting can be adjusted in .....

+ 1 for the setting.
