### ISSUE TITLE
Consider unify the refresh action for test explorer

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#139737]
> API Proposal: https://github.com/microsoft/vscode/issues/139737#issuecomment-1002662337

Currently since the test explorer does not have `refresh` action by default. Extensions might contribute their own implementation for `refresh`, and thus, cause some UX conflicts. For example:

![WeChat Screenshot_20211225105654](https://user-images.githubusercontent.com/6193897/147376440-ed8a55af-9ae0-469b-8f13-218f6c785137.png)

If user installed both `Java` and `Python` extension, the user will see two refresh button in the test explorer:

- The one in the navigation bar is contributed by Python
- The one in the overflow button is contributed by Java

And if Python extension is not activated, click on the navigation bar refresh button will cause an error.

This issue can be resolved if VS Code can unify the refresh action from the platform level

See: https://github.com/microsoft/vscode-java-test/issues/1348

**Comment by nickzhums** [comment]
@luabud for awareness, this seems to be affecting users who install both Java and Python extension

**Comment by connor4312** [comment]
Yep, agreed. I suggest an API such as this:

```ts
	export interface TestRunProfile {
		/**
		 * If this method is present, a refresh button will be present in the
		 * UI, and this method will be invoked when it's clicked. When called,
		 * the extension should scan the workspace for any new, changed, or
		 * removed tests.
		 *
		 * It's recommended that extensions try to update tests in realtime, using
		 * a {@link FileWatcher} for example, and use this method as a fallback.
		 *
		 * @returns A thenable that resolves when tests have been refreshed.
		 */
		refreshHandler: (() => Thenable<void> | void) | undefined;
	}
```

**Comment by luabud** [comment]
cc @karthiknadig

**Comment by connor4312** [comment]
The API is shipping in tomorrow's Insiders. Please give it a shot! 

Example of adopting it in the sample: https://github.com/microsoft/vscode-extension-samples/commit/2f1d70f74e489ccdcc9e0b221de130ecc1585b0a

**Comment by karthiknadig** [comment]
@connor4312 Can this API and the UI support cancellation? Currently we show `beaker-stop` codicon when refreshing. We hide the refresh icon and show `beaker-stop` when triggered it cancels the refresh.

**Comment by connor4312** [comment]
@karthiknadig added

**Comment by karthiknadig** [comment]
@connor4312 Should this API be updated to take in cancellation token as well? https://github.com/microsoft/vscode/blob/fe0e9a96d35f19129892827b45168916c560af84/src/vscode-dts/vscode.proposed.testRefresh.d.ts#L35

the API implementation here seems to be taking it: https://github.com/microsoft/vscode/blob/fe0e9a96d35f19129892827b45168916c560af84/src/vs/workbench/api/common/extHost.api.impl.ts#L357

**Comment by connor4312** [comment]
Oops, added that too
