### ISSUE TITLE
Find in Selection in any selection, not just by lines

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#13972]
In VS Code, Find in Selection only works by lines, if you have a multiline selection. In other editors, I can select any fragment and search within it. If anyone uses this, I think it would be more useful to match this. Especially for minified files with very large lines. And after https://github.com/Microsoft/vscode/commit/79bc7a814603d541502a604e0f984aee7abba90f, it makes more sense. Since before, if you accidentally selected two characters, you'd be stuck searching in there.

**Comment by rebornix** [comment]
Right now you can have Find in Selection in a single line selection.

**Comment by roblourens** [comment]
So this was fixed before 1.12 some time? Works as I expect now at least.
