### ISSUE TITLE
While writing code for node js app, pc uses too much cpu.

### ISSUE THREAD

**Issue by harunfr** [microsoft/vscode#139750]
Issue Type: <b>Performance Issue</b>

Whenever I hit any key, it uses much cpu for at leat 5 seconds. It happens mostly on node js apps. When writing code for front end apps, it doesn't happen.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.11.0-43-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.75GB (0.51GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id c8151a66-7104-4ac5-9fde-5722325c35e5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   135	 23708	code main
    0	    40	 23710	   zygote
    1	    95	 23737	     gpu-process
    0	    40	 23711	   zygote
    2	    87	 24141	     issue-reporter
    0	    56	 23751	   utility-network-service
    0	   222	 23763	   window (products.js - store-api - Visual Studio Code)
    0	   167	 23996	   extensionHost
    0	   119	 24058	     /snap/code/85/usr/share/code/code --ms-enable-electron-run-as-node --max-old-space-size=3072 /snap/code/85/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /tmp/vscode-typescript1000/0017bd2f1149b6400e5b/tscancellation-497efd66044d0b3efb1c.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
    0	   135	 24004	   shared-process
    0	    63	 24025	     ptyHost
    0	    63	 24044	     watcherServiceParcelSharedProcess
    0	     0	 24155	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 24156	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (products.js - store-api - Visual Studio Code)
|      Error: Unable to collect workspace stats for folder /home/harun/Desktop/All-About-FullStack/store-api (TypeError: t is not iterable);
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.0.0
LiveServer|rit|5.6.1
learn-vim|vin|0.0.27

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710:30416614
vscexrecpromp3t1:30407762

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
