### ISSUE TITLE
sidebar drag bug

### ISSUE THREAD

**Issue by 18392152392** [microsoft/vscode#139799]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. when I install an extension from vsix, if I drag the area left and right, it is always in active state, it is a serious bug, can you help to fix?
![1640604944(1)](https://user-images.githubusercontent.com/52459655/147468143-cc430233-cb90-475b-b847-2b83fe53df56.jpg)
 
2.

**Comment by joaomoreno** [comment]
What do you mean by _always in active state_? Why is that a serious bug?

Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by 18392152392** [comment]
ok，Thanks for your reply


this video is the problem, I think it is a serious bug, can you help to fix? thank you !




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月5日(星期三) 下午4:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode] sidebar drag bug (Issue #139799)





 
What do you mean by always in active state? Why is that a serious bug?
 
Can you please provide a screen recording?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by 18392152392** [comment]
hello
&nbsp;I have already provide you a screen recording





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月10日(星期一) 晚上9:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode] sidebar drag bug (Issue #139799)





 
Can you please provide a screen recording?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 18392152392** [comment]
hello,
&nbsp;this is the screen recording, I think it is a serious bug, can you help to fix?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月10日(星期一) 晚上9:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode] sidebar drag bug (Issue #139799)





 
Can you please provide a screen recording?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by joaomoreno** [comment]
Please come to GitHub and attach the screen recording. Sending it via e-mail doesn't work.
