### ISSUE TITLE
html only autocomplete </div>

### ISSUE THREAD

**Issue by Cheesing-Jade** [microsoft/vscode#139748]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest
- OS Version: Arch Linux (mr)

Steps to Reproduce:

1. type </ while editing html and it will automatically and only insert </div> without me pressing tab
[Youtube Video](https://youtu.be/4z7NvyXuCR8)

**Comment by aeschli** [comment]
What you see is the html auto close feature.
You can disable it with `"html.autoClosingTags": false,`
