### ISSUE TITLE
VS Code for Apple Silicon at 200+ power impact

### ISSUE THREAD

**Issue by deoradh** [microsoft/vscode#139754]
Issue Type: <b>Performance Issue</b>

1. Start up Code
2. Browse extensions, edit text file, check git repos.  Compilation not required.
3. Let it be over 12 hours while doing other things in Safari, Mail, etc.
4. Eventually open Activity Monitor, look at Energy tab and 12-hour impact.

There's no good reason why editing text or doing the occasional git status should cause Code to cause that much impact (50x the impact of an active Telegram chat???).  If I were doing compilations, sure, but even then only while actively compiling.   

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:38:17.605Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 5|
|Memory (System)|64.00GB (4.85GB free)|
|Process Argv|--crash-reporter-id c0b1f744-191d-4a2e-8579-42550a1d92a6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   17	   197	 76025	code main
    0	    66	 76028	   gpu-process
    0	    66	 76029	   utility-network-service
   27	   262	 76031	   window (Visual Studio Code)
    0	   197	 76049	   shared-process
    0	    66	 76051	     ptyHost
    0	     0	 76093	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   197	 76050	   extensionHost
    0	    66	 76082	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=76050
    0	    66	 76089	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.45.0
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|11.7.0
git-project-manager|fel|1.8.2
remotehub|Git|0.20.0
mdmath|goe|2.7.4
vscode-test-explorer|hbe|2.21.1
Ionide-fsharp|Ion|5.10.2
crates-completer|jed|1.2.1
language-julia|jul|1.5.8
nim|kos|0.6.6
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.17
dotnet-interactive-vscode|ms-|1.0.2606010
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.7.1
powershell|ms-|2021.12.0
test-adapter-converter|ms-|0.1.5
vsliveshare|ms-|1.0.5200
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
cargo|pan|0.2.3
material-icon-theme|PKi|4.11.0
vscode-xml|red|0.18.2
rust|rus|0.7.8
crates|ser|0.5.10
vscode-rust-test-adapter|Swe|0.11.0
vscode-lldb|vad|1.6.10
vscode-icons|vsc|11.8.0
rust-extension-pack|wol|0.1.1
pestfile|xor|0.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30414010
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710:30416614
vscexrecpromp3t1:30407762

```

</details>

**Comment by deoradh** [comment]
See also https://github.com/microsoft/vscode/issues/131923

**Comment by jbg** [comment]
It's almost certainly one or more of your extensions. In particular try disabling the Rust-related extensions. VSCode, open and idle, has 0 energy impact on my M1 — I can use it all day on battery. If I install the rust-analyzer extension it goes to over 200 and my battery drains in a few hours.
