### ISSUE TITLE
Question: is it possible to test userinteraction?

### ISSUE THREAD

**Issue by buehler** [Microsoft/vscode#13977]
When an extension developer is writing some tests (hopefully).
Is there any possibility to test for user interaction?

E.g.

The code shows an input box where the user has to input a filename for example. Now my unit test would insert "foobar" there and hit enter. The main reason would be to test some features and functions that depend on a users input.

I've not found any documentation on this matter.

Cheers

**Comment by bpasero** [comment]
No, currently not. Best you can do is try to perform actions by exercising the extension API (e.g. trigger commands).
