### ISSUE TITLE
Subpixel Font Rendering is Broken in the Integrated Terminal, Resulting in Blurry Text

### ISSUE THREAD

**Issue by nicebyte** [microsoft/vscode#139739]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version:  1.63
- OS Version: Windows 10 Home 21H2 (build 19044.1415)

Steps to Reproduce:

1. Open the integrated terminal.

Details:

In the screenshot below, the top part is displaying text in the code window, while the bottom part is displaying text in the integrated terminal (please click on the image to view at full resolution because image rescaling interferes with important details):

![image](https://user-images.githubusercontent.com/12521759/147378588-f92ae8ff-5f9d-41da-9dda-cf31ba89044a.png)

Both the code window and the integrated terminal use the same font, at the same size and are at the same zoom level.

Observe that the text in the code window has colored fringes. This is normal, and is expected when using [subpixel rendering](https://en.wikipedia.org/wiki/Subpixel_rendering). However, the text in the terminal only has shades of gray. This is undesirable, because shades of gray light up all _three_ of the rgb subpixels. Effectively, the horizontal resolution is not increased, and the text appears blobby and blurred.

The effect is quite apparent to the naked eye when using the default fonts. However, it is even more apparent when using a bitmap font (in this case `PxPlus IBM VGA8`):

![image](https://user-images.githubusercontent.com/12521759/147378749-d8516899-02bb-4bf2-b606-e72873f1d827.png)

For reference, the same text with the same font in the code window:

![image](https://user-images.githubusercontent.com/12521759/147378766-7887ef95-ad01-42e1-a345-fe3425e21b2a.png)

**Comment by nicebyte** [comment]
this looks like it might be an issue with xterm.js. at least they had a similar problem in the past (https://github.com/xtermjs/xterm.js/commit/c6d66d7b0d774e260025df23c1578db7c567d546) - but that commit is over 3 years old.

**Comment by meganrogge** [comment]
thanks for the info, did this start happening recently?

**Comment by nicebyte** [comment]
I am not sure. I installed vscode for the first time in a while and noticed it immediately.

**Comment by Tyriar** [comment]
We investigated this earlier and believe it's an issue with our version of Electron. We're currently updating to v16 so stay tuned
