### ISSUE TITLE
it is not possible to write the '@'-sign anymore

### ISSUE THREAD

**Issue by todaelapps** [microsoft/vscode#139798]
Visual Studio Code 
after update it is not possible to write the '@'-sign anymore
Error Message: command 'codemap.reveal' not found.
I'm using mac mini with magic keyboard.
How can I solve that problem, eg. what settings maybe are wrong?

**Comment by alexdima** [comment]
@todaelapps It looks like you have installed an extension that maps a keybinding to the keys you use to type `@`. You can:
- disable the problematic extension
- uninstall the problematic extension
- (or) remove the offending keybinding

**Comment by todaelapps** [comment]
Thank you very much @alexdima !
I found and removed the binding and it worked perfectly!
