### ISSUE TITLE
<center>tag turns red when it shouldn't be.

### ISSUE THREAD

**Issue by Winstonjames2** [microsoft/vscode#139707]
error type =bug
system = Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by aeschli** [comment]
Is this for syntax highlighting in HTML? 

Note that the center tag should no longer be used and might not be supported by browsers in the feature:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center

**Comment by aeschli** [comment]
For HTML syntax highlighting we use the grammar at https://github.com/textmate/html.tmbundle/issues
If you think the `center` tag should be support even it is deprecated, please file an issue there.
