### ISSUE TITLE
`window.tabs` after `vscode.open` command is not up to date

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139786]
I just [pushed a test](https://github.com/microsoft/vscode/commit/7e55d4b8fbbda54f03e760aced9cefa7a4cee53a) for asserting `vscode.open` command properly applies the `ViewColumn` argument and my initial idea was to use the `window.tabs` API for that purpose, but as it turns out, awaiting `executeCommand` and then calling `window.tabs` does not work, maybe (?) because of the [micro queue](https://github.com/microsoft/vscode/blob/0cc783e8450299c0cef5f55258f1f40d6b58b354/src/vs/workbench/services/editor/browser/editorService.ts#L50) that puts the events at the end?

Using `window.activeTextEditor.viewColumn` however seems to work, and I wonder if we need to make `window.tabs` also work so that extensions see a consistent picture.

If we don't want to drop the micro task then maybe those commands that leverage editors need to await the tabs model being synced back to the extension host?

//cc @jrieken

**Comment by lramos15** [comment]
This is interesting as I feel like the tab tests do something similar but they use open and show text document for the most part. 

For example we use execute command to get a diff here and then check windows.tab

https://github.com/microsoft/vscode/blob/9ce72d28b6fc53c3c6419ea37774cf2d0e17fd76/extensions/vscode-api-tests/src/singlefolder-tests/window.test.ts#L394-L397

**Comment by bpasero** [comment]
@lramos15 but you are not testing for `activeTab`, just add this and it fails after line 397:

```
assert.strictEqual(window.activeTab?.viewColumn, ViewColumn.Three);
```

**Comment by lramos15** [comment]
@bpasero I just tested this again now that we removed microtask and it's still incorrect. Will have to dig deeper but that doesn't seem like it was it.

**Comment by bpasero** [comment]
Is it possible that the `executeCommand` simply returns to the extension host before you were pushing the updated tabs model to the extension host? Maybe there is a missing `await` in `vscode.open` that does not exist in the other ways for opening.

**Comment by lramos15** [comment]
I thin I must've messed up testing / fixed it with my `if (!editorIndex)` fix. Seems to work now and I added a test. Don't know if you want to update your `vscode.open` tests as well

**Comment by bpasero** [comment]
verified via https://github.com/microsoft/vscode/commit/6dee30baa85e99e245f6b7c940c7ad13f3a3199a
