### ISSUE TITLE
"Not enough storage is available to process this command" in Terminal Panel.

### ISSUE THREAD

**Issue by redstrike** [Microsoft/vscode#13978]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 2gua.rainbow-brackets-0.0.6, christian-kohler.npm-intellisense-0.1.4, christian-kohler.path-intellisense-1.1.0, dkundel.vscode-npm-source-0.0.3, donjayamanne.githistory-0.1.0, donjayamanne.jquerysnippets-0.0.1, EditorConfig.EditorConfig-0.3.3, eg2.tslint-0.5.39, emilast.LogFileHighlighter-1.0.0, fknop.vscode-npm-3.3.0, formulahendry.auto-rename-tag-0.0.7, HookyQR.beautify-0.4.1, lukehoban.Go-0.6.45, ms-vscode.typescript-javascript-grammar-0.0.5, msjsdiag.debugger-for-chrome-1.2.2, qinjia.seti-icons-0.1.2, robertohuertasm.vscode-icons-3.0.5, ronnidc.nunjucks-0.2.3, SirTori.indenticator-0.2.1

Steps to Reproduce:

1. Open the VS Code.
2. Open the Terminal.

![image](https://cloud.githubusercontent.com/assets/2168227/19508707/d3151642-9604-11e6-91e5-9cb909596cd6.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/12260
