### ISSUE TITLE
Allowing more than one extension dir

### ISSUE THREAD

**Issue by pasqui23** [microsoft/vscode#139742]
I would like if `VSCODE_EXTENSIONS` would take more than one directory, separated by `:`, like `PATH`.

**Comment by IllusionMH** [comment]
What are use casses for this feature? Probably there are other requests that might achieve same end goal without this env var

**Comment by pasqui23** [comment]
Allowing things like having a `./local-code` with a few project-specific extensions, and even having such extra extensions be built locally to the project. Having to install an extension in the home dir could be problematic.

This also allow using different versions of the same extension with different invocation of vscode with `VSCODE_EXTENSIONS`

**Comment by sandy081** [comment]
> Allowing things like having a ./local-code with a few project-specific extensions, and even having such extra extensions be built locally to the project. Having to install an extension in the home dir could be problematic.

There is a feature request for this specific request already.

> This also allow using different versions of the same extension with different invocation of vscode with VSCODE_EXTENSIONS

Not sure what you mean by this
