### ISSUE TITLE
Possibility to use the simple file dialog instead of the system file dialog

### ISSUE THREAD

**Issue by ThomasLamalle** [microsoft/vscode#139757]
Issue #135904 is related but did not solved the request of this feature.
I'm working on an extension that would search for a file at some point.
I would like to use the simple file dialog that we get when we use the command "Go to File...", which is really neat and can easily filter files instead of the outdated system file, that we get when using vscode.window.showOpenDialog.

**Comment by alexr00** [comment]
Please see the full response at https://github.com/microsoft/vscode/issues/135904#issuecomment-958741687
