### ISSUE TITLE
Very Slow VSCode, Lags

### ISSUE THREAD

**Issue by justinbarak** [microsoft/vscode#139731]
Issue Type: <b>Performance Issue</b>

Running 64bit Raspberry Pi OS on 4GB Raspberry Pi. It looks like I am seeing a 5-10 second delay after every action in vscode. Every other app responds instantly, just vscode is super slow. Scrolling down through small 100 line python scripts is a nightmare, with the same lag. This makes fixing typos madness. Updating and rebooting does not fix the problem.Typing this up took 10 minutes and still some of the typos just weren't worth the effort of fixing.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:55.286Z)
OS version: Linux arm64 5.10.63-v8+
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|unknown (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|3.71GB (1.00GB free)|
|Process Argv|--crash-reporter-id cb557db1-d84e-418b-b3c5-c41cfe835447|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|LXDE-pi|
|XDG_CURRENT_DESKTOP|LXDE|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   148	254563	code main
    0	    38	254566	   zygote
    2	   140	254595	     gpu-process
    0	    23	254615	       broker
    0	    38	254567	   zygote
    0	     8	254569	     zygote
    3	    83	383866	       issue-reporter
    0	    53	254606	   utility-network-service
    0	   129	254640	   shared-process
    0	    65	254674	     ptyHost
    0	     4	255020	       /usr/bin/bash
    0	    61	254824	     watcherServiceParcelSharedProcess
    0	     0	383883	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	383884	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   224	254778	   window (scrape_antenna.py - Botcheck - Visual Studio Code)
    0	   190	254808	   extensionHost
    0	   186	254903	     /usr/share/code/code --ms-enable-electron-run-as-node /home/pi/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist/server.bundle.js --cancellationReceive=file:57d94d1a20eb7c72c90fff98c487ba2c9c3751c4ff --node-ipc --clientProcessId=254808
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (scrape_antenna.py - Botcheck - Visual Studio Code)
|      Error: Unable to collect workspace stats for folder /home/pi/projects/Botcheck (TypeError: t is not iterable);
```

</details>
<details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.7.0
code-runner|for|0.11.6
pythonsnippets|frh|1.0.2
copilot|Git|1.7.4421
vscode-pull-request-github|Git|0.34.2
gc-excelviewer|Gra|4.0.45
terraform|has|2.17.0
latex-workshop|Jam|8.22.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.18.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-wsl|ms-|0.63.13
cpptools|ms-|1.7.1
vscode-yaml|red|1.2.2
python-template-snippets|Ric|1.2.0
jinjahtml|sam|0.16.0
ayu|tea|1.0.5
vsfire|tob|1.4.1
pdf|tom|1.2.0
vscodeintellicode|Vis|1.2.15
snippet|vsc|0.8.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710:30416614
py55gd98:30411514
vscexrecpromp3c:30407761

```

</details>

**Comment by rebornix** [comment]
@justinbarak can you try running VS Code with GPU disabled? `code --disable-gpu` and see if you can reproduce?

**Comment by ondruska** [comment]
I do confirm this is more of an Electron issue and a workaround is to disable using acceleration, for instructions see https://ratticon.com/how-to-fix-slow-visual-studio-code-on-raspberry-pi-4/

I would be great this is addressed in https://code.visualstudio.com/docs/setup/raspberry-pi (I will try to do so)

**Comment by ondruska** [comment]
https://github.com/microsoft/vscode-docs/pull/5085

**Comment by ItalyPaleAle** [comment]
In your RPi, how much memory do you have dedicated to the GPU? (For reference: https://peppe8o.com/manage-raspberry-pi-gpu-memory-split/ )

**Comment by ondruska** [comment]
mine was at 64 and changing to maximum of 256 made no difference

**Comment by justinbarak** [comment]
@rebornix Running --disable-gpu did help. I eventually implemented the fixes linked by @ondruska and it works great now. Thanks so much!!
@ItalyPaleAle I can confirm, changing from 64 to maximum 256 made no difference.
