### ISSUE TITLE
Grey color in syntax highlighting for launch.json

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#13979]
- VSCode Version: Code - Insiders 1.7.0-insider (27d17e3ebfeae2b0252949534c5c5d67eb7fdb1b, 2016-10-18T06:05:15.056Z)
- OS Version: Darwin x64 15.6.0
- Extensions: christian-kohler.path-intellisense-1.1.0, dbaeumer.vscode-eslint-1.0.8, eg2.tslint-0.5.39, ms-vscode.Theme-TomorrowKit-0.1.3, ms-vscode.js-atom-grammar-0.1.10, msjsdiag.debugger-for-chrome-1.2.2, vscodevim.vim-0.3.8

The file is launch.json for VSCode.
Is the grey intended or broken?

![image](https://cloud.githubusercontent.com/assets/4033249/19510172/e2146c24-9596-11e6-9803-a92fc18ab9bc.png)

**Comment by octref** [comment]
@roblourens Is this intended for launch.json? This doesn't look good.

**Comment by roblourens** [comment]
Yeah that's on purpose, from https://github.com/Microsoft/vscode/issues/13353. The idea is that the less important attributes are deemphasized, so the ones that a user needs to configure stand out more, to make the whole thing slightly less overwhelming.

**Comment by aeschli** [comment]
@isidorn Isi, FYI.

**Comment by chrmarti** [comment]
Looked like a bug to me too:
![screen shot 2016-12-08 at 9 08 05 am](https://cloud.githubusercontent.com/assets/9205389/21019573/e084863a-bd25-11e6-9b4e-edb9a6662129.png)

What about using the same kind of coloring, but greyed-out - instead of just grey? /cc @bgashler1

**Comment by isidorn** [comment]
The decoaritions are currently not allowing us to use transparency.
So the decorations styling support is currently limited to be too creative here unfortunetly

**Comment by bgashler1** [comment]
I love that we're trying to make `launch.json` less complex-looking, but I also find the gray colorization kind of confusing.  I've looked at the discussion in #13353, and it appears I'm not the only one.  Have we considered making use of comments and negative space to make it more clear what's important?
