### ISSUE TITLE
Plot Navigator For Julia Not Showing Any Plots 

### ISSUE THREAD

**Issue by AI-economist** [microsoft/vscode#139733]
Issue Type: <b>Bug</b>

I ran this code: 

import Pkg; Pkg.add("Plots")
begin
    using Plots 
    plotly()
end

using LinearAlgebra
using RowEchelon

#Let's create a scatter plot
begin
    scatter([1.5,2,-1],[1,5,-2], title="Points", label="Points")
end

using Plots
x=1:10
y = rand(10)
#These are the plotting Data
plot(x,y, label="my label")

But I can't see any plots anywhere. The "Plot Navigator" just shows plots numbers but no plots. 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.60GB free)|
|Process Argv|--crash-reporter-id c2a680cf-8001-4c61-ad2b-6001ae9171a3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
language-julia|jul|1.5.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710:30416614
py55gd98:30411514
vscexrecpromp3t1:30407762

```

</details>

**Comment by AI-economist** [comment]
Hi. Is there been any update ?

**Comment by artkuo** [comment]
I have the same problem, and workaround was to revert to Julia language extension 1.5.6, which restores plot plane. The pane appears in the main editor group though, which I believe has already been reported elsewhere and perhaps fixed.
