### ISSUE TITLE
Slow compiling

### ISSUE THREAD

**Issue by Priyanshuwork** [microsoft/vscode#139732]
Issue Type: <b>Performance Issue</b>

Whenever I try to compile my C/C++ codes it is too slow that i get irritate. Please fix this issue.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (6.35GB free)|
|Process Argv|--crash-reporter-id 73bfd10e-64a2-4e9f-b003-54992550e76e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   124	 59080	code main
    0	    24	 23204	   crashpad-handler
    0	     6	 56052	   "C:\Program Files\Google\Drive File Stream\53.0.8.0\crashpad_handler.exe" --database=C:\Users\KIIT\AppData\Local\Google\DriveFS\Crashpad --url=https://clients2.google.com/cr/report --annotation=application=Code.exe --annotation=prod=DriveFS --annotation=ver=53.0.8.0 --initial-client-data=0x1694,0x13d0,0x16a8,0x16b8,0x15c8,0x7ffd01021930,0x7ffd01021940,0x7ffd01021950
    0	    41	 58884	   utility-network-service
    0	   138	 61276	   gpu-process
    0	    93	 64788	   shared-process
    0	    86	 42696	     ptyHost
    0	    77	 56632	     watcherServiceParcelSharedProcess
    0	   148	 66212	   window (Untitled (Workspace) - Visual Studio Code)
    0	    87	 68576	   issue-reporter
    0	   270	 68924	   extensionHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Untitled (Workspace) - Visual Studio Code)
|    Folder (VS): 200 files
|      File types: exe(76) cpp(66) c(41) json(5) lnk(1) dat(1) c++(1) cPP(1)
|      Conf files: launch.json(2) settings.json(2)
|      Launch Configs: cppvsdbg;
```

</details>
<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
vscode-html-css|ecm|1.10.2
code-runner|for|0.11.6
better-cpp-syntax|jef|1.15.10
vscode-JS-CSS-HTML-formatter|lon|0.2.3
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5200
vsliveshare-audio|ms-|0.1.91
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.1.1
swdc-vscode|sof|2.6.21
cmake|twx|0.0.17
vscode-lldb|vad|1.6.10
vscode-icons|vsc|11.8.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710:30416614
py55gd98:30411514
vscexrecpromp3c:30407761

```

</details>

**Comment by tanhakabir** [comment]
Hello! Sorry about that! Unfortunately VS Code itself doesn't handle compiling you C/C++ code. The issue is most likely in the compiler you have installed on your machine or the cpptools extension. 

I'm going to move this issue to their repo to see if they have any suggestions!
