### ISSUE TITLE
Global snippets: group multiple file types, snippet inheritance

### ISSUE THREAD

**Issue by brandon942** [microsoft/vscode#139876]
Grouping global snippets by file type in the same way settings can be grouped.
```jsonc
"[js][ts]":{
	.... snippets
}
```
And/Or better (method 2):
```jsonc
// typescript.json  (the current snippet file)
"inherit": ["javascript"]   // <- this is the key line
.... snippets
```
The "scope" field can be useful in certain special cases but usually snippets come in groups, so that is not enough.  
Currently if you have 100 `js` snippets and want them in `ts` files you'd have to edit the "scope" field of each one of them. Then you're trying React - do it again.... And so on.  

The 2 methods are similar and can complement each other but the advantage of method 2 is that a more specialized version of a language can add additional snippets and override inherited snippets, eg `for(var i: number; ...` overrides `for(var i; ...` if the `for` snippet is redefined, but doesn't have to.  
While we're at it, the `typescript.json` file can contain a `"exclude javascript": [...snippet ids]` field naming inherited snippets that you do not want in a `ts` file.

**Comment by tjx666** [comment]
Current VSCode snippet configuration is not flex enough, so many snippet extension programmatically to generator snippets. Like https://github.com/dsznajder/vscode-react-javascript-snippets and https://github.com/johnpapa/vscode-angular-snippets which user ammount is vary large.
