### ISSUE TITLE
Bracket pair color is not working correctly

### ISSUE THREAD

**Issue by piavgh** [microsoft/vscode#139823]
Issue Type: <b>Bug</b>

Steps to produce:

1. Add these 2 lines in settings.json:

```
{
    "editor.bracketPairColorization.enabled": true,
    "editor.guides.bracketPairs":"active"
}
```

2. Open a React.js component
3. Choose a JSX element that is not the outermost element
4. See the issue => The bracket pair is not highlighted at all

![Screenshot at Dec 28 10-05-51 AM](https://user-images.githubusercontent.com/4060207/147524183-cbb21cd8-c333-4159-abf9-1256a98f64fb.png)

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.53GB free)|
|Process Argv|--crash-reporter-id 52ec3cd5-fac4-4905-850d-49c46048dfb4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.6.0
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
vscode-great-icons|emm|2.1.79
prettier-vscode|esb|9.0.0
vscode-pull-request-github|Git|0.34.2
go|gol|0.30.0
solidity-debugger|hos|0.2.1
svg|joc|1.4.15
vscode-styled-components|jpo|1.7.0
solidity|Jua|0.0.136
rust-analyzer|mat|0.2.867
git-graph|mhu|1.30.0
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.17
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
remote-containers|ms-|0.209.6
cadence|onf|0.6.3
vscode-yaml|red|1.2.2
vscode-vyper|tin|0.0.10
learn-vim|vin|0.0.27
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710cf:30416617
vscexrecpromp3t2:30407763

```

</details>

**Comment by IllusionMH** [comment]
There are no bugs on screenshot:
1) It's bracket pairs highlight, not a tags pairs highlight so line that arrow points to in not supposed to be highlighted by this feature. You should check for existing requests for this kind of feature and create feature request if there are no existing requests.

2) `<`/`>` were intentionally excluded from highlight as they caused problems(check closed issues) and in JSX its always same color: ach tag has open and close pair of `<`/`>` so there is no color change for nested tags.

In your case active pair would've been pair of `<`/`>` in just `<PageWrapper>`.

**Comment by piavgh** [comment]
@IllusionMH : please check the screenshot below. It's the default setting, there is actually a highlight on the ruler of <PageWrapper> tag

1.
<img width="790" alt="Screenshot at Dec 28 10-06-37 PM" src="https://user-images.githubusercontent.com/4060207/147579735-b5bbde25-2d7b-4cdc-bcbd-95c2a353e53e.png">

The same highlight exists with Bracket Pair Colorizer:

2.
<img width="798" alt="Screenshot at Dec 28 10-09-43 PM" src="https://user-images.githubusercontent.com/4060207/147579971-c0cb0f00-30f1-470b-9968-a55462986aec.png">

So with 1, I think it's a bug

With 2, I think it's a feature that should be included (Bracket Pair Colorizer maintainer said that he will no longer support the extension because VSCode has it built-in)

**Comment by IllusionMH** [comment]
OK, with other screenshots for comparison it looks more clear now.

So to clarify: you expect to see colored (pink) line for `return`'s pair of `(`/`)` and regular (white) highlight for indentation guide (not tags pair) in JSX? At least this is what you see in BPC2, there is no special support for JSX, it's just white indentation line.

From first message it looked like you want JSX elements to have own colored lines for tags pair.

**Comment by piavgh** [comment]
@IllusionMH : 

"you expect to see colored (pink) line for return's pair of (/) and regular (white) highlight for indentation guide (not tags pair) in JSX" => yes, I just need it exactly like BPC2.

Because at the moment, I can not see which block of JSX tag that I'm selecting
