### ISSUE TITLE
Excluding the intellisens for a node package 

### ISSUE THREAD

**Issue by BLITzStudio** [microsoft/vscode#139893]
### 

> Example: I start working with mongoose and the code complition becomes lagy (it needs 3 to 4 seconds to show me some relevant stuf ) , this shoud allow me to exclude that node package .
>I looked up this issue online but iI didnt find something that can help solve this. I jump on the settings.json to see if i can find a parameter that have somehow a connection with code coplition, intellisens or even with npm, but unfortunately i didnt manage to find something relevant. Vscode performate its really bad when using Mongoose(the last version of it).
Sorry for the english,i am tring my best.

**Comment by BLITzStudio** [comment]
I looked up this issue online but iI didnt  find something that can help solve this. I jump on the settings.json to see if i can find a parameter that have somehow a connection with code coplition, intellisens or even with npm, but unfortunately i didnt manage to find something relevant. Vscode performate its really bad when using Mongoose(the last version of it).
Sorry for the english,i am tring my best.

**Comment by mjbvz** [comment]
Please provide a motivating use case for this (ideally with a small sample project) and describe the expected behavior of the new setting

/needsMoreInfo
