### ISSUE TITLE
Custom URLs for non-theme extensions

### ISSUE THREAD

**Issue by lewisl9029** [microsoft/vscode#139839]
Hi VSCode team!

[Custom URLs](https://code.visualstudio.com/docs/editor/vscode-web#_more-custom-urls) is one of the killer features for vscode.dev in my humble opinion. 

Among other things, it opens up the possibility for extension authors to provide awesome onboarding experiences where users can just click a link to a playground repo with their extensions pre-installed, with a codebase specifically designed to showcase various use cases for the extension. This dramatically reduces the risk/friction to trying out new extensions, and allows for a much more streamlined onboarding/learning experience.

Today, this possibility seems to be limited to a few microsoft first-party extensions (github and azure repos) and themes. Do you have plans to open up custom url integration for more third party extensions? Perhaps through a vscode.dev/extensions/extension-id url scheme, analogous to the one for themes?

If so, I'd love to test it out as soon as it's available! If you have reservations on opening custom urls to non-theme extensions, I'd love to hear them, and maybe we can try to work out solutions with the community.

Thanks!

One last thought: This could also be a very effective way to encourage more extension authors to make their extensions web-compatible! It saddens me to see only about 1/3 of my desktop extensions available on vscode.dev, even though there's no real technical blockers for most of them to be migrated.

**Comment by joaomoreno** [comment]
> Today, this possibility seems to be limited to a few microsoft first-party extensions (github and azure repos) and themes. Do you have plans to open up custom url integration for more third party extensions? Perhaps through a vscode.dev/extensions/extension-id url scheme, analogous to the one for themes?

We are definitely considering it. Stay tuned!

> One last thought: This could also be a very effective way to encourage more extension authors to make their extensions web-compatible! It saddens me to see only about 1/3 of my desktop extensions available on vscode.dev, even though there's no real technical blockers for most of them to be migrated.

100% agree!
