### ISSUE TITLE
Can not sign in to sync

### ISSUE THREAD

**Issue by kaijCH** [microsoft/vscode#139843]
Issue Type: <b>Bug</b>

The button for sing in account and sync was not responding

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.10.0-1052-oem
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 3191)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.35GB (8.62GB free)|
|Process Argv|--unity-launch --crash-reporter-id 9cb81f8e-c27e-4a9d-a78b-e7d3cb6b8d61|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by sandy081** [comment]
Can you please provide a video/gif of what happening?

**Comment by kaijCH** [comment]
Sorry I did not have a follow up and close such thread, the issue happened when I updated and did not reboot machine. Button of login was disappearing from both sidebar, and functionality can not be reach from anywhere in setting, wherever I access regarding account sync just no responding. Though I understand that after update rebooting is required, but the missing issue is still a little bit confusing

**Comment by sandy081** [comment]
I see, not sure if I can be helpful without able to repro it. I would close it for now and recommend to reopen it with a gif or video or steps to repro.
