### ISSUE TITLE
Crash while using GUI menus with X11 forwarding

### ISSUE THREAD

**Issue by HenriHakonen** [microsoft/vscode#139857]
Issue Type: <b>Bug</b>

1 (in client). Open gnome-terminal in Ubuntu 20.04.
2. ssh -X myname@myserver.com
3 (in server). code-insiders --disable-extensions --crash-reporter-directory ~/crash-report
4. VSCode window appears in client screen.
5 Click menus (File, Edit, Selection, etc.) multiple times in some order. GUI will respond slower and slower. After 10 or 20 clicks VSCode crashes.

System info is from server. Server's /var/log/syslog has rows
Dec 28 20:58:08 dt kernel: [ 2955.176412] code-insiders[5504]: segfault at ffffd5f3598ae11d ip 00005651dcaaea88 sp 00007ffdabfda4e0 error 5 in code-insiders[5651da7fe000+5ee0000]
Dec 28 20:58:08 dt kernel: [ 2955.176446] Code: e8 4d 76 b8 ff eb ce cc cc cc cc cc cc cc cc cc cc cc 55 48 89 e5 48 8d 05 2c 3d 1a fd 5d c3 cc cc cc 55 48 89 e5 48 8b 7f 08 <48> 8b 07 5d ff 60 18 cc 55 48 89 e5 41 57 41 56 41 54 53 49 89 f6
Dec 28 20:58:12 dt kernel: [ 2959.444982] code-insiders[5661]: segfault at 0 ip 00007f673d801b24 sp 00007fff89eef5b0 error 4 in watcher.node[7f673d7df000+4a000]
Dec 28 20:58:12 dt kernel: [ 2959.445009] Code: f9 01 77 0a 49 8d 74 24 ff 4c 21 f6 eb 15 4d 39 e6 73 05 4c 89 f6 eb 0b 4c 89 f0 31 d2 49 f7 f4 48 89 d6 48 8b 05 ec c8 02 00 <48> 8b 04 f0 48 85 c0 0f 84 4c 01 00 00 44 0f b6 2b 41 f6 c5 01 74

VS Code version: Code - Insiders 1.64.0-insider (7b9e5c32a053669d4e72f998e4fa217090c32f59, 2021-12-22T05:15:27.690Z)
OS version: Linux x64 5.11.0-43-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel Xeon Processor (Skylake, IBRS) (4 x 2099)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|15.26GB (11.20GB free)|
|Process Argv|--crash-reporter-id 99f45915-7302-4428-8444-7dea4adba0da|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
better-cpp-syntax|jef|1.15.10
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.0-insiders2
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
vscop804cf:30404767
vscop453:30404998
vsclayoutctrc:30405799
py55gd98:30408621
vscexrecpromp3t1:30407758
azactmsal:30409287

```

</details>

[crash-report.zip](https://github.com/microsoft/vscode/files/7786110/crash-report.zip)

**Comment by deepak1556** [comment]
Please try remote ssh extension https://code.visualstudio.com/docs/remote/ssh instead of X11 forwarding.
