### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by WoogonShim** [microsoft/vscode#139821]
Does this issue occur when all extensions are disabled?: Yes (_I tried to disable all extensions to `disable(workspace)`_)

- VS Code Version: 1.63.2
- OS Version: WindowsNT x64 10.0.19043

![![image](https://user-images.githubusercontent.com/582071/147521315-459f9bd7-7189-476e-912d-f9193df33fec.png)](https://user-images.githubusercontent.com/582071/147521125-5d1163bf-ec5e-4432-9ea3-4728dc5f5750.png)

```
Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```

Steps to Reproduce:

1. start vscode and wait a moment.
2. select the `Source Control` icon on the left.
3. _(additionally)_ error popups from extensions related to git appear.

--------
vscode couldn't recognize git repository even though I opened git repository path.
![image](https://user-images.githubusercontent.com/582071/147521341-b8aa2856-6c0c-446f-a79e-0d7937db6315.png)

Also, I got the below message from the `GitLens` extension after starting vscode:
![image](https://user-images.githubusercontent.com/582071/147521297-aeed7e46-1612-48a3-b2aa-59e4118df982.png)

And message from the 'Git Graph' extension:
![image](https://user-images.githubusercontent.com/582071/147526140-17b733a7-22c9-446a-9100-40aadf1e3724.png)

It's really weird. I have already installed the latest version of Git for Windows.
![image](https://user-images.githubusercontent.com/582071/147521315-459f9bd7-7189-476e-912d-f9193df33fec.png)
![image](https://user-images.githubusercontent.com/582071/147521323-14609b79-5a73-4e29-b899-12c4826e70b9.png)

And I specified git.path as follow:
![image](https://user-images.githubusercontent.com/582071/147521331-2a2b9893-c759-43c3-89f8-22b2037131b8.png)

The result of `git rev-parse --git-dir` is as follow:
![image](https://user-images.githubusercontent.com/582071/147521538-371c47bc-d65f-408a-b1dc-f9d400e1ff7f.png)

What makes me crazy is that the git commands correctly work inside the command line prompt in vscode.
_with powershell_
![image](https://user-images.githubusercontent.com/582071/147521390-0d8378fb-c2a1-4ac2-9f4f-298107778553.png)

with _git bash_ actually **I used zsh instead of bash**
![image](https://user-images.githubusercontent.com/582071/147521398-a5e6a0d0-76d7-435f-9946-5a3dde1bf3ea.png)

and **`Output (Git)`** is as follows:
```
Validating found git in: C:\Program Files\Git\cmd\git.exe
Using git  from C:\Program Files\Git\cmd\git.exe
> git rev-parse --git-dir
fatal: not a git repository (or any of the parent directories): .git
Opening repository for path='d:\@DevDocs\lab_weekly_meeting' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any of the parent directories): .git\n"
}
> git rev-parse --git-dir
fatal: not a git repository (or any of the parent directories): .git
Opening repository for path='d:\@DevDocs\lab_weekly_meeting\.vscode' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any of the parent directories): .git\n"
}
> git rev-parse --git-dir
fatal: not a git repository (or any of the parent directories): .git
Opening repository for path='d:\@DevDocs\lab_weekly_meeting\2018' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any of the parent directories): .git\n"
}
> git rev-parse --git-dir
fatal: not a git repository (or any of the parent directories): .git
Opening repository for path='d:\@DevDocs\lab_weekly_meeting\2019' failed; ex=Failed to execute gitWhat: 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any of the parent directories): .git\n"
}
> git rev-parse --git-dir
fatal: not a git repository (or any of the parent directories): .git
Opening repository for path='d:\@DevDocs\lab_weekly_meeting\2020' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any of the parent directories): .git\n"
}
Opening repository for path='d:\@DevDocs\lab_weekly_meeting\2021-07-13 H&A센터장 세미나.md' failed; ex=spawn C:\Program Files\Git\cmd\git.exe ENOENT {
  "gitErrorCode": "NotAGitRepository"
}Error: spawn C:\Program Files\Git\cmd\git.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Opening repository for path='d:\@DevDocs\lab_weekly_meeting\20210114-SEL-주간보고.md' failed; ex=spawn C:\Program Files\Git\cmd\git.exe ENOENT {
  "gitErrorCode": "NotAGitRepository"
}Error: spawn C:\Program Files\Git\cmd\git.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
..... (ommitted) .....
```

I thought that special character `@` might cause this situation, So I tried to re-clone in another path string without any special characters, `d:\lab_weekly_meeting`. The result is the same.

**What should I do?**

--------
*Add*

In another machine, vscode recognizes this git repository and works nicely. What's wrong with it?
**I integrated my github account on vscode to sync extensions and settings.**

```
Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by lszomoru** [comment]
Based on the information that you have provided the issue seems to be machine specific so we should try to track down the difference between the two machines. Could you please try the following on both machines and share the contents of the Git output?
1. Download [VS Code Insiders](https://code.visualstudio.com/insiders/) to make sure that you have the latest code
2. Start VS Code insiders using `code-insiders --disable-extensions` to make sure that all extension are disabled
3. Open the repository in VS Code insiders and share the contents of the Git Output. 

Thanks!

**Comment by WoogonShim** [comment]
I'm so sorry. I missed your comment, @lszomoru!

As you suggested, I run VS Code Insiders with all extensions that are disabled and open the same repository.
The result is below:

```
[2022-01-19T05:21:30.652Z] Validating found git in: C:\Program Files\Git\cmd\git.exe
[2022-01-19T05:21:30.804Z] Using git  from C:\Program Files\Git\cmd\git.exe
[2022-01-19T05:21:31.169Z] > git rev-parse --git-dir [169ms]
[2022-01-19T05:21:31.170Z] fatal: not a git repository (or any of the parent directories): .git
[2022-01-19T05:21:31.465Z] > git rev-parse --git-dir [119ms]
[2022-01-19T05:21:31.465Z] fatal: not a git repository (or any of the parent directories): .git
[2022-01-19T05:21:31.674Z] > git rev-parse --git-dir [91ms]
[2022-01-19T05:21:31.674Z] fatal: not a git repository (or any of the parent directories): .git
[2022-01-19T05:21:31.900Z] > git rev-parse --git-dir [109ms]
[2022-01-19T05:21:31.900Z] fatal: not a git repository (or any of the parent directories): .git
[2022-01-19T05:21:32.122Z] > git rev-parse --git-dir [104ms]
[2022-01-19T05:21:32.122Z] fatal: not a git repository (or any of the parent directories): .git
[2022-01-19T05:21:33.116Z] > git rev-parse --git-dir [87ms]
[2022-01-19T05:21:33.116Z] fatal: not a git repository (or any of the parent directories): .git
[2022-01-19T05:21:36.952Z] > git rev-parse --git-dir [149ms]
[2022-01-19T05:21:36.952Z] fatal: not a git repository (or any of the parent directories): .git
[2022-01-19T05:21:37.337Z] > git rev-parse --git-dir [119ms]
[2022-01-19T05:21:37.337Z] fatal: not a git repository (or any of the parent directories): .git
```

**Comment by WoogonShim** [comment]
This problem was resolved.
The root cause is the conflicts between git in VS Code and the security monitoring tool which our company insists to install.
After removing and applying the newest patch, git correctly works now.

**Comment by lszomoru** [comment]
@WoogonShim, thank you very much for the update. Happy to hear that you were able to track down the root cause of the issue. Would you be able to share the name of the security monitoring tool so that we have it on file in case any other user runs into the same issue? Thank you!

**Comment by WoogonShim** [comment]
Thank you for your kindness.

The name of security program is "WaterWall". It's a kind of DLP(Data Loss Prevention) system.
https://wwsystems.co.kr/
