### ISSUE TITLE
Annoying highlight after using suggestions

### ISSUE THREAD

**Issue by Rc85** [microsoft/vscode#139890]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: Windows_NT x64 10.0.19042
- Language Mode: Typescript React

Steps to Reproduce:

1. Use a suggested autocomplete shown in the screenshot below

![image](https://user-images.githubusercontent.com/22307591/147695027-6d12f21e-886b-4da4-a78b-3eb97c1047e5.png)

2. The value field has this annoying highlight, similar to using a snippet where you define $1, $2 to tab your cursors to.

![image](https://user-images.githubusercontent.com/22307591/147695205-0aa4dde4-75c8-4ebf-9e22-a62d221264e6.png)

Why is this annoying? Because the code you type into the highlight area does not provide suggestions and autocompletes. May not be a bug and if there is a way to disable it, please advise.

**Comment by mjbvz** [comment]
Set `"editor.suggest.snippetsPreventQuickSuggestions": false` to enable suggestions when typing inside snippets

/cc @jrieken

**Comment by Rc85** [comment]
Didn't work

#### Current behavior:

![image](https://user-images.githubusercontent.com/22307591/147985703-43841ba2-2b3b-48ac-b572-9f5c8797990c.png)

Press tab after suggesting `justify`
![image](https://user-images.githubusercontent.com/22307591/147985953-e9446cc4-0976-40d2-8724-8b1b255776fe.png)

Suggestions not showing
![image](https://user-images.githubusercontent.com/22307591/147985830-e389e255-b1f4-4d31-a115-40f3a27e142c.png)

#### Expected behavior:

Instead of pressing tab to select `justify` I typed the `justify=''`. Suggest popped up.
![image](https://user-images.githubusercontent.com/22307591/147985892-e3dca5d6-4266-4893-8360-b5158b7373d3.png)

**Comment by mjbvz** [comment]
Quick suggestions also are disabled inside strings. If you are already in a string (such as after accepting the suggestion with tab), you can manually trigger suggestions again using ctrl+space

**Comment by Rc85** [comment]
Is there a way to disable that highlight after selecting a suggestion? I remember it was never like this in older version of vscode. I would, say, tab on `justify` and the cursor would just move between the single quotes and I would type as normal.

**Comment by Rc85** [comment]
After fiddling with the settings and added `"editor.quickSuggestions": true`, suggestions are showing up when cursor is in the highlighted area.
