### ISSUE TITLE
word wrap not saved between restarts

### ISSUE THREAD

**Issue by alex-jitbit** [microsoft/vscode#139869]
Issue Type: <b>Bug</b>

select "View - Word Wrap", restart VS

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (21.98GB free)|
|Process Argv|--crash-reporter-id 1302d358-09bd-43ec-99f2-e1b1afeb467a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.13
eml|lei|0.4.0
csharp|ms-|1.23.17
remote-wsl|ms-|0.63.13
powershell|ms-|2021.12.0
code-spell-checker|str|2.0.14

</details>

**Comment by gjsjohnmurray** [comment]
See #103199

**Comment by alex-jitbit** [comment]
@gjsjohnmurray the issue you linked talks about "open documents".

1. This setting should be global (not "per document"). Just like it is _in all other text editors on this planet_ literally (including the "full" Visual Studio). Don't break our habits.

2. This setting should be preserved between restarts.

**Comment by gjsjohnmurray** [comment]
Did you try using the `editor.wordWrap` setting?

**Comment by alex-jitbit** [comment]
> Did you try using the `editor.wordWrap` setting?

@gjsjohnmurray I did not, thanks for guiding me, but isn't it the same as the mentioned menu toggle?
