### ISSUE TITLE
Types replaced by a character in Javascript Parameter Hints

### ISSUE THREAD

**Issue by ahlechandre** [Microsoft/vscode#13983]
- VSCode Version: 1.6.1
- OS Version: Microsoft Windows [10.0.14393]

Steps to Reproduce:

1.  Type `reduce` method from array
2.  Navigate with **Up** or **Down**
3.  `previousValue` from `callbackfn`, `callbackfn`, `initialValue` and function return type changes to `U`

### Step 1
![reduce](https://cloud.githubusercontent.com/assets/7119058/19511046/5f31e254-95c4-11e6-8a23-6c0450b306f1.jpg)

### Step 2
![reduce2](https://cloud.githubusercontent.com/assets/7119058/19511097/8e20ba2c-95c4-11e6-9023-28ede1c3567f.jpg)

**Comment by roblourens** [comment]
I think this is right - the type definitions are written in TS and you have 2 there - one where everything is `any`, and one with a generic type parameter `U`.
