### ISSUE TITLE
Support `javascript.preferences.quoteStyle` as a language specific setting

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#139864]
From this thread:
https://twitter.com/mannieschumpert/status/1475927885156343820

and these docs: https://code.visualstudio.com/updates/v1_63#_jsx-attribute-completions

My best guess is that for the video in the docs, `"javascript.preferences.quoteStyle"` is set to `"single"` or it is set to `"auto"` and there is an `import` or `require` statement that we can't see that uses single quotes.  

The ask from this twitter thread is support different quote styles for JavaScript and JavaScript React file types.  However, the quoteStyle setting is not supported for per language configurations:

![image](https://user-images.githubusercontent.com/1487073/147617127-225ded5c-1107-4b95-a083-a29bcc733365.png)

**Comment by mannieschumpert** [comment]
For some clarification of the problem that led to this issue:
It is not actually not just language-specific, but style specific. I would guess that the example in the video is using Airbnb JSX style conventions, as described here: https://airbnb.io/javascript/react/#quotes
In this particular, but very popular, style convention, single quotes are used everywhere in any JSX or TSX file, _except_ for when declaring JSX component attributes.

**Comment by yuval-gilboa** [comment]
I'd like to echo @mannieschumpert  comments.

When choosing JSX attribute completion style = `auto`, i get single quotes despite the fact that the tooltip explicitly says i should get double quotes:

![image](https://user-images.githubusercontent.com/4710322/148304235-44e35cfa-7bb0-4189-a8cc-f9ac9b76dc3f.png)

I guess this has to do with the fact that the general quotes style is set to `auto (single)`:

![image](https://user-images.githubusercontent.com/4710322/148304310-fe92b07f-036f-4125-8c0f-c19f99d5f091.png)

Somehow the two settings need to be combined with a new option to enable using single quotes in the general case, but double quotes in the specific case of JSX attribute completion (as well as any other inline markup fragments such as HTML/XML).

CC: @mjbvz

**Comment by mjbvz** [comment]
@mannieschumpert  Can you please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md) for that

I only fixed what the original issue here described

**Comment by joyceerhl** [comment]
Verified that in Insiders:
- I can now customize the quote style for the `javascriptreact` language
- Configuring a preference for 'single' will autocomplete attributes with single quotes even if there are double quotes elsewhere in the file
- Configuring a preference for 'double' will autocomplete attributes with double quotes even if there are single quotes elsewhere in the file
- Configuring a preference for 'auto' will match inferred preference from elsewhere in the file
