### ISSUE TITLE
colorless .js file text

### ISSUE THREAD

**Issue by Bhikkanmiya** [microsoft/vscode#139809]
We have writin my vs code when is create the index.js file or any file name with .js extension  the code or the content whatever i am writing in .js file it will displaying in colorless text and also when i create html and css files it shows in colors.
as well as when i comment the js file it comes @rem.ten the needed data into your clipboard because it was too large to send. Please paste.

**Comment by aeschli** [comment]
What is the editor mode showing in the status bar? JavaScript or TypeScript?
