### ISSUE TITLE
Extension markdown internal links do not always work

### ISSUE THREAD

**Issue by sophodoros** [microsoft/vscode#139852]
Issue Type: <b>Bug</b>

There is a problem with resolving internal links when a VS Code extension's README.md file is displayed in the extension's "Details" tab. Consider the following markdown:

~~~~~~~~~~~~~~~~~

  - [Align: Columns](#align-columns)
  - [Align: Equals](#align-on-equals)
  - [Align: Text](#align-text)

Ipsum lorem    
Ipsum lorem    
Ipsum lorem    
Ipsum lorem    
Ipsum lorem    
Ipsum lorem    
Ipsum lorem    
Ipsum lorem    
Ipsum lorem    
Ipsum lorem    
Ipsum lorem    
Ipsum lorem    

---------------
### <a name="align-columns"></a>__Align: Columns__

Ipsum lorem    
Ipsum lorem    
Ipsum lorem    
Ipsum lorem    
Ipsum lorem    

---------------
### <a name="align-on-equals"></a>__Align: Equals__

Ipsum lorem    
Ipsum lorem    
Ipsum lorem    
Ipsum lorem    
Ipsum lorem    

---------------
### <a name="align-text"></a>__Align: Text__

Ipsum lorem    
Ipsum lorem    
Ipsum lorem    
Ipsum lorem    
Ipsum lorem    

~~~~~~~~~~~~~~~~~

When this README.md file is included in my extension, the 1st and 3rd links in the list work, but the 2nd ("align-on-equals") does not.  Here are the steps I'm using to test this:

1. Save the README changes for the extension
2. In the VS Code Terminal, run the "vsce package" command to generate a .vsix extension file.
3. In the VS Code Extensions section, click on the 3-dot menu and select  "Install from VSIX" and select the new .vsix. Say "Yes" to "Reload now".
5. In the VS Code Extensions section, test each of the links in the extension's "Details" tab. If the problem exists, clicking the 2nd link will have no effect.

If the string "align-on-equals" is changed to "align-equals" and the steps are repeated, the link DOES work. However, this only happens in the test README.md shown above. My extension's real README.md (which is considerably more detailed than the test sample here) uses the string  "align-on-equals" for a link, and changing it to "align-equals" does not fix it. In the real README.md, changing link names sometimes works, and sometimes does not. 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (8.08GB free)|
|Process Argv|--crash-reporter-id 06ad3d1a-923e-44a5-b0eb-bbb1e100d442|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.19
xml|Dot|2.5.1
copy-markdown-as-html|jer|1.1.0
csharp|ms-|1.23.17
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
hexeditor|ms-|1.8.2
codevalet-vscode|Sop|1.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30414010
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710:30416614
vscexrecpromp3c:30407761

```

</details>

**Comment by sophodoros** [comment]
**Update**: To verify that this issue wasn't somehow related to other features or settings in my extension, I performed a test using the configuration-sample extension from the [VS Code extension samples](https://github.com/microsoft/vscode-extension-samples). (I picked configuration-sample because the main project folder indicated it had been updated within the last month, while most of the other samples had not been updated in 3 months or more.)

In order to create a .vsix package using configuration-sample, I first had to modify its package.json file to set engines.vscode to "^1.40.0". I also had to set "publisher" to a valid publisher. 

Once that was done, I replaced the contents of the extension's README.md file with the README text from my original post. Then, I ran "vsce package" to generate the .vsix file. Finally, I installed the .vsix file in VS Code.

When viewed on the extension's "Details" screen, only the 1st link worked -- the 2nd and 3rd did not. I then changed the "align-on-equals" to "align-equals" and rebuilt the .vsix, and the 2nd link then worked. The 3rd link still did not work.

**Comment by mjbvz** [comment]
Thanks for the detailed writeup!

For reference, do all of these links work on the extension marketplace website? https://marketplace.visualstudio.com/vscode

**Comment by sophodoros** [comment]
Hi Matt,
Well, actually I’m a bit embarrassed to say that most of the links in Code Valet’s <https://marketplace.visualstudio.com/items?itemName=SophodorosLLC.codevalet-vscode> (my published extension) README are broken when viewed in the extension's Details page in VS Code, and have been that way for over a year. I just found out recently that the reason they didn’t work was that markdown link names had to be all lower case; my link names used camelCase. I mistakenly thought they didn’t work because VS Code’s rendering of the Details page just didn’t allow markdown links.

I discovered the problem reported in the bug report after I converted my camelCase link names to lowercase snake-case. Since many of the links still didn’t work after I “fixed” them, I haven’t published those changes. If it would help your analysis of the problem, I could publish an update to Code Valet with those changes -- let me know if you want me to do that.

Regards,
Art Walker
Sophodoros LLC

**Comment by mjbvz** [comment]
Thanks. I think you are describing: https://github.com/microsoft/vscode/issues/126082 Do the links all work if the case of the link exactly matches the case  of the id/name?

**Comment by mjbvz** [comment]
Also for the original example, I believe the links will work if you use `id` instead of `name`. Not super familiar with `name` outside of forms but I think `id` is the more standard approach  for links

**Comment by sophodoros** [comment]
DOH! After changing the `a` element `name` refs to `id`, all of the links do indeed work.

I'm not sure how we wound up using `name` instead of `id` -- HTML isn't one of my strengths, so I rely on the kindness of strangers for guidance. Regardless, it looks like a cockpit error was responsible for the problem, so as far as I'm concerned you can consider this issue closed.

Many thanks for your help!

**Comment by mjbvz** [comment]
Glad this worked. Closing this issue for now then since it sounds like this has been resolved
