### ISSUE TITLE
snippet stop working after extension:Python installed

### ISSUE THREAD

**Issue by hanbaobao2005** [Microsoft/vscode#13980]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393, windows 10 Pro 1607 x64
- Extensions: donjayamanne.python-0.4.2, magicstack.MagicPython-0.5.17, ms-vscode.PowerShell-0.7.2, tht13.python-0.2.3, tushortz.python-extended-snippets-0.0.1

Steps to Reproduce:
1. Install VS code on D: drive which is not OS drive
2. snippet works before I install the extension: python-0.4.2
3. my python path is D:/Program Files (x86)/python3.5/python.exe, and I configured setting item:
"python.pythonPath": "\"D:/Program Files (x86)/python3.5/python.exe\""
4. Snippet stops to work after I install the extension: python-0.4.2 : the snippet doesn't pop up anymore.

Expectation:
Snippet should works after I install the extension: python-0.4.2.

More info:
I installed the extension/VSCode on a server which OS is windows 2008 R2 and python path is 'C:/Python34/python.exe', snippet works well.

I have opened an [issue](https://github.com/DonJayamanne/pythonVSCode/issues/397#issuecomment-254736290) for Python extension, the author doubt that this is a VSCode issue, I would like to provide more info to locate the root cause.

Thanks,

**Comment by roblourens** [comment]
Could it be related to the tushortz.python-extended-snippets-0.0.1 extension? Does it work if you uninstall that extension?

**Comment by hanbaobao2005** [comment]
@roblourens snippet works after I uninstalled the extension.

**Comment by roblourens** [comment]
'the extension' meaning the snippet one that I mentioned? Please file an issue on them.

**Comment by hanbaobao2005** [comment]
@roblourens Thanks, 
I have reported [an issue](https://github.com/DonJayamanne/pythonVSCode/issues/397) on the extension. The author @DonJayamanne doubts this is an issue of VSCode.
Where I can find the log about snippet？
Thanks,

**Comment by roblourens** [comment]
I see you edited your comment, so it works if you uninstall Don's Python extension? Can you post the snippet?

**Comment by hanbaobao2005** [comment]
snippet stops working totally, it doesn't not pop up anymore.
I'll confirm with @DonJayamanne  to see if autocomplete function of the extension: Python affected snippet.

**Comment by DonJayamanne** [comment]
@hanbaobao2005 , please could you confirm that auto complete doesn't work for JavaScript, HTML and TypeScript. You mentioned (https://github.com/DonJayamanne/pythonVSCode/issues/397#issuecomment-254740368) that this was the case. 
Meaning, this is not an issue with an extension, but a VS Code issue.

**Comment by hanbaobao2005** [comment]
I did the testing again (Extension version is 0.5.0), and now I agree with @roblourens that this is should an issue of the extension.
I captured a gif about the issue:
![test](https://cloud.githubusercontent.com/assets/1937472/19547296/5579f8ea-96c9-11e6-8d0a-1924ae7c9f39.gif)
1. New a file and set the language mode to javascript
or
open a .js file, snippet works well

2. New a file and set the language mode to html
or
open a .html file, snippet works well
Note: Sorry about #1 and #2, the result is a different one, I'm not sure if I entered the right keywords to trigger snippet.

3. Open a Py file, the snippet doesn't work
4. New a file and set the language mode to Python, snippet works well.

**Comment by DonJayamanne** [comment]
@hanbaobao2005 please confirm that snippets work for other os. You mentioned this was the case on the other thread. 

Also for the snippet to work toy need to enter another space after selecting the snippet. 

Could you try the other short, ```for/else```?

**Comment by hanbaobao2005** [comment]
@DonJayamanne snippets works on my win2008R2 x64 Enterprise edition, attached the gif
BTW, I would say that snippet should works in real time, extra space is not needed:
OS: win2008R2 x64
![test](https://cloud.githubusercontent.com/assets/1937472/19549967/b2c369d6-96d9-11e6-9175-027bee61779e.gif)

try/finally still doesn't work on my win10, attached gif:
![test1](https://cloud.githubusercontent.com/assets/1937472/19550140/aecabcc0-96da-11e6-9278-10fabeff60cc.gif)
Thanks,

**Comment by DonJayamanne** [comment]
@hanbaobao2005 , you are not selecting the snippet.
In the above screen, you are selecting the auto complete.
The icons for auto complete is different from the snippet.
The icon for snippets is a simple square. The ones for an autocomplete is one with multiple lines.
I.e. this isn't an issue. You're selecting auto complete, and not the snippet.

Have a look below. Basically you're selecting the wrong item.
Once again, if it is a snippet you can see the title under the item (see below).
![snippet](https://cloud.githubusercontent.com/assets/1948812/19550343/bc64c60e-96f4-11e6-9f3f-6c97724c19a1.gif)

**Comment by hanbaobao2005** [comment]
@DonJayamanne my issue is not about item selection, but when a opened a .py file, **the snippet doesn't pop up**.

**Comment by DonJayamanne** [comment]
@hanbaobao2005 apologies for not understanding the issue.
It leads me to believe that the extension may not have been installed correctly.
You've mentioned that it works on one os (win2008R2 x64 Enterprise edition) and not the other. 

Please try uninstalling the Python extension and trying again. There's nothing OS specific with snippets.

>OS Version: Windows_NT ia32 10.0.14393

Is this Windows 7 , 8 or 2000? Thanks

**Comment by hanbaobao2005** [comment]
@DonJayamanne,
I tried to uninstall/install the extension several times, it doesn't help.
My OS is windows 10 Pro 1607 x64, I could provide a remote access by team viewer for debugging.
Really appreciate your patient.
Thanks,

**Comment by DonJayamanne** [comment]
Will do, Let's close this issue and reopen the one on the vs code python repo.

**Comment by DonJayamanne** [comment]
@roblourens 
FYI - Problem was settings.json was configured incorrectly and caused extension not to load correctly.

**Comment by roblourens** [comment]
Thanks Don!
