### ISSUE TITLE
Spawning new terminal does not work for workspace with folders and "terminal.integrated.cwd": "${workspaceFolder}"

### ISSUE THREAD

**Issue by drweb86** [microsoft/vscode#139842]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.64.0-insider (user setup)
Commit: 7b9e5c32a053669d4e72f998e4fa217090c32f59
Date: 2021-12-22T05:15:28.225Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Create workspace file
```
{
    "folders": [
        {
            "name": "scripts",
            "path": "."
        },
        {
            "name": "other",
            "path": ".//other"
        },
    ],
    "settings": {
        "terminal.integrated.cwd": "${workspaceFolder}",
    }
}
```
Create the other folder.
2. Open it in Visual Studio Code on Windows
3. Terminal \ New Terminal, select 'scripts'
4. Observe error:
The terminal process failed to launch: Starting directory (cwd) "\D:\sources\app" does not exist.
5. Terminal \ New Terminal, select 'other'
6. Observe error
The terminal process failed to launch: Starting directory (cwd) "\D:\sources\app" does not exist.

Actual behavior: spawning of terminal does not work for workspaces with folders. Relative paths support became broken.
Expected behavior: terminal opens normally with proper folder.

Relative paths support became broken is a regression caused by PR that fixed issue
https://github.com/microsoft/vscode/issues/136099

**Comment by JesusDR01** [comment]
It's a little tricky.
You must delete your 
 `"terminal.integrated.cwd": "${workspaceFolder}"` 

Then add:
```
    "terminal.integrated.profiles.windows": {
        "My PowerShell": {
            "source": "PowerShell",
            "args": ["-noexit", "cd","${fileDirname}"]
        }
    },
    "terminal.integrated.defaultProfile.windows": "My PowerShell"
```
