### ISSUE TITLE
Add the view-filtered item in the right click menu on a project dir

### ISSUE THREAD

**Issue by yordan-georgiev-valuemotive** [microsoft/vscode#139883]
According to the following scenario: 
Prerequisites: 
- The User has opened a dir in his/her workspace
Steps: 
- The User right clicks any dir/folder from his project
- The System presents the "view filtered" item ( could be another name too ) in the right click menu
- The User clicks on the "view filtered" item
- The System presents a dialog asking for the file glob pattern ( why not regex too )  to use to filter the files in the directory
- The User types the regex ( could be something like `*.yaml`
- The System presents ONLY the files in the folder mathing the file glob / regex filter specified by the User
- The System indicates with a color that this folder is filtered and does not remove the filter unless explicitly requested to

aka something like

```bash
vim -o `find src -name *.yaml`

**Comment by JacksonKearl** [comment]
It's an interesting idea, but probably something I'd leave for an extension to contribute. The extension would contribute a command to the explorer's context menu that prompts for a glob, then writes that glob to the `files.exclude` setting for the workspace. A status bar entry could allow removing the glob.
