### ISSUE TITLE
Mac Electron process uses 10% CPU for large projects attempting to use VS Code as Finder

### ISSUE THREAD

**Issue by valhuber** [microsoft/vscode#139856]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.64.0-insider (Universal)
Commit: 7b9e5c32a053669d4e72f998e4fa217090c32f59

- OS Version: Monterey

Steps to Reproduce:

1. Open a large folder (e.g., home folder)
2. Check Activity Monitor

As noted in title, I am trying to use VS Code as my Finder, but it basically eats one cpu (2019 MBP).

<img width="1188" alt="electron" src="https://user-images.githubusercontent.com/5579631/147598594-30a315ec-741f-4033-9fb7-61ae307f3560.png">

**Comment by deepak1556** [comment]
Can you check if the issue persists with latest stable `1.73` ? If it does, please provide the full command line of the high CPU process.

**Comment by valhuber** [comment]
I repeated the large-home-folder test on Insiders (1.75), I saw a momentary spike which quickly cleared.

Fixed from my perspective... thanks!

**Comment by deepak1556** [comment]
Thanks for confirming.
