### ISSUE TITLE
VSCode start very slow, and use nearly 100% of CPU

### ISSUE THREAD

**Issue by platonev** [Microsoft/vscode#13981]
- VSCode Version: 1.6
- OS Version: Windows Server 2008(64bit)
- CPU: Intel Xeon CPU E5-26xx v3 2.39GHz
- RAM: 1G

**Comment by nigelr0** [comment]
Same/similar problem.

After a recent update opening Code (even on an empty folder) pegs the CPU at 90%+.

Left it for several minutes, but no change.

![image](https://cloud.githubusercontent.com/assets/12252186/19520117/f3c52772-9606-11e6-9d27-81d3ba222cc3.png)

![image](https://cloud.githubusercontent.com/assets/12252186/19520160/27379874-9607-11e6-85f4-5a0667a7eb3b.png)

**Comment by bpasero** [comment]
Are you running VSCode inside a VM?

**Comment by nigelr0** [comment]
Yes, I am 

    On Wednesday, 19 October 2016, 16:19, Benjamin Pasero <notifications@github.com> wrote:
 

 Are you running VSCode inside a VM?—

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13882
