### ISSUE TITLE
Consider to set `EditorInputCapabilities.Singleton`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139837]
The `EditorInputCapabilities.Singleton` editor capability marks an editor as not being able to show more than once. Going through some of our existing editors that I felt might want to consider using this capability:
* [x] [`WalkThroughInput`](https://github.com/microsoft/vscode/blob/a91a307436c31831705a19a7c862a367145b1e11/src/vs/workbench/contrib/welcome/walkThrough/browser/walkThroughInput.ts#L52) @JacksonKearl 
* [x] [`GettingStartedInput`](https://github.com/microsoft/vscode/blob/999f172e9cbd8f3cc12cf4d4ecdbf252fe9ee47f/src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStartedInput.ts#L15) @JacksonKearl 
* [x] [`DisassemblyViewInput`](https://github.com/microsoft/vscode/blob/636b70da227750d1905f76b46a500e0dd6c2c0ce/src/vs/workbench/contrib/debug/common/disassemblyViewInput.ts#L9) @weinand 

Feel free to unassign in case it does not apply.

**Comment by JacksonKearl** [comment]
Adopted for walkthrough as I encountered issues when splitting the playground, leaving getting started alone as we generally do support splits.

**Comment by weinand** [comment]
Since the disassembly view seems to support splits, I don't think that the `DisassemblyViewInput` needs to return the `EditorInputCapabilities.Singleton` editor capability.

@roblourens @yuehuang010 @xisui-MSFT please speak up if you disagree.
