### ISSUE TITLE
Live Share Extension: Provide ability to save/export comments from a session

### ISSUE THREAD

**Issue by ScriptAutomate** [microsoft/vscode#139891]
When using [Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare), comments can be made and read during a session, but are [transient and disappear](https://twitter.com/ScriptAutomate/status/1462851858112794626) once live share is stopped. It would be awesome if these could be exported in some way, and allow for the ability to still see or make use of comments in the VS Code editor when offline.

I'm opening this in the VS Code repository as I can't seem to find whether this extension has a repository elsewhere, as I can only seem to find the [docs repo for Live Share](https://github.com/MicrosoftDocs/live-share).

**Comment by alexr00** [comment]
The "Issues" link in the marketplace for Live Share points to https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare. Moving the issue there.

**Comment by alexr00** [comment]
Moved to https://github.com/MicrosoftDocs/live-share/issues/4552
