### ISSUE TITLE
All Extensions Got Uninstalled 

### ISSUE THREAD

**Issue by coder-teamie** [microsoft/vscode#139828]
- VS Code Version: 1.63.2
- OS Version: Windows 10

All my installed extensions suddenly got uninstalled upon starting the app today. I still made use of the app last night and everything still worked fine.
![Screenshot 2021-12-28 143213](https://user-images.githubusercontent.com/79058304/147536029-36266a38-e46a-4c18-8004-7edb2fbf06d0.png)

**Comment by sandy081** [comment]
It seems you have settings sync is enabled, can you please check what settings sync log has?

> F1 > Open View.. > Log (Settings Sync)

You can also check which machine of yours has pushed the state that uninstalled extensions on this machine - https://code.visualstudio.com/docs/editor/settings-sync#_restoring-data

From this view, you can find the history of machines syncing extensions.
