### ISSUE TITLE
git login panel vanishes when minimised.

### ISSUE THREAD

**Issue by furkankatman** [Microsoft/vscode#13984]
- VSCode Version:0.10.11
- OS Version:windows8

Steps to Reproduce:
1. Open a git repository
2. Then try to commit and you will be redirected to git login screen. when you minimise that login panel it will vanish forever .And You cannot get it back . and git symbol on the bottom left side will look as processing  (the circle arrows ).

**Comment by joaomoreno** [comment]
No longer.
