### ISSUE TITLE
Microsoft authentication extension should not wrap `console` methods

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#139894]
**Describe the bug**

When developing or testing extensions, it's common for developers to log data from their extensions. However, because the Microsoft auth extension wraps console methods, the lines reported to the developer are incorrect.

**To Reproduce**
1. Create a hello world extension https://code.visualstudio.com/api/get-started/your-first-extension
2. In the launch.json, add the following lines (this will be unnecessary in the next release):
 	```
	"skipFiles": [
		"<node_internals>/**",
		"**/bootstrap-fork.js"
	],
	```
3. Add a `console.log("hello")` to the command in `src/extension.ts`
4. F5, and run the hello world command

Note: you may need to disable codespaces and the github auth plugin to see this, because they do the same thing https://github.com/github/codespaces/issues/5622 https://github.com/microsoft/vscode/issues/139895

**Expected behavior**

The line in the console points to the source line in the user's code where the log message appeared.

**Actual behavior**

It's the Microsoft auth extension where it wraps the global console methods. It should _not_ wrap these methods.

**Screenshots**

See the source in the lower right corner points to a place where the extension wraps the global console methods.

![image](https://user-images.githubusercontent.com/2230985/147700444-ca22b7e7-83f7-4f29-9e0e-1b1858582e4f.png)

**Comment by TylerLeonhardt** [comment]
I'm confused by this... AFAIK we don't do anything like that... maybe it's a bundling issue?

We use this:
https://github.com/microsoft/vscode/blob/main/extensions/microsoft-authentication/src/logger.ts
ok there's a single console.error here I should probably fix:
https://github.com/microsoft/vscode/blob/main/extensions/microsoft-authentication/src/authServer.ts#L66

but that's it.

**Comment by alexr00** [comment]
My investigation for the GHPRI version of this issue pointed to https://github.com/microsoft/vscode-extension-telemetry/issues/88
