### ISSUE TITLE
Implement "Suggestion Mode" from Visual Studio

### ISSUE THREAD

**Issue by macintacos** [microsoft/vscode#139825]
In Visual Studio, [there is a mode called "Suggestion Mode" that is described here in MS's documentation](https://docs.microsoft.com/en-us/visualstudio/ide/using-intellisense?view=vs-2022#:~:text=You%20can%20also,Toggle%20Completion%20Mode.). This functionality is more succinctly described in [this blog post](https://docs.microsoft.com/en-us/archive/blogs/zainnab/intellisense-suggestion-mode). Basically, I would like for suggestions to be shown, but none "selected" until I actually wish to use them.

This has been brought up in several issues (at the very least #85768, #67698, #33725). I wanted to open a new issue to have the VSCode potentially reconsider this, since after reading one of the VSCode bot's links, it appears that older issues are unsubscribed by the team - it would be great to have this implemented.

Editing with some minor clarifications I provided [in my comment below](https://github.com/microsoft/vscode/issues/139825#issuecomment-1092354299):

> The ideal scenario that I personally am trying to have in VSCode is:
> 
> 1. I type something into an editor and I get suggestions.
> 2. As I get those suggestions, none are "selected" until I hit "tab" or arrow-down the list of suggestions (I personally use "tab" to go through the suggestion list, but the point is that it should be an intentional choice for me to navigate through the list).
> 3. At this point, I decide what I want to do. If I intentionally navigate into the suggestion list and I have decided on an item I want to insert, I hit "enter" and VSCode completes the selection into the editor. If I don't navigate into this list, "enter" will just insert a line break.
>

**Comment by Imericxu** [comment]
I’d like to add that from working in Neovim, I found it very intuitive to explicitly select and cycle through auto-completion suggestions with `Ctrl + n` and `Ctrl + p` or tabbing then accept with `Enter`. Currently, I’m resorting to accepting with the `Tab` key alongside the Vim extension.

**Comment by haoadoresorange** [comment]
does `editor.acceptSuggestionOnEnter` solve the problem ?

**Comment by BIKA-C** [comment]
> @macintacos does `editor.acceptSuggestionOnEnter` solve the problem ?

No, it is still selected

**Comment by haoadoresorange** [comment]
I mean it's still selected but enter make a new line, so shouldn't that be good ?

**Comment by macintacos** [comment]
@haoadoresorange no. I still want "enter" to be how completion items are chosen after navigating to them in the list. I just don't want anything in the quick suggestion list selected _until I navigate into the list._

The ideal scenario that I personally am trying to have in VSCode is:

1. I type something into an editor and I get suggestions.
2. As I get those suggestions, none are "selected" until I hit "tab" or arrow-down the list of suggestions (I personally use "tab" to go through the suggestion list, but the point is that it should be an _intentional choice_ for me to navigate through the list). 
3. At this point, I decide what I want to do. If I intentionally navigate into the suggestion list and I have decided on an item I want to insert, I hit "enter" and VSCode completes the selection into the editor. If I don't navigate into this list, "enter" will just insert a line break.

Hopefully that adds some clarity to this feature request.

**Comment by haoadoresorange** [comment]
@macintacos I see, maybe add this to the original post above ?

**Comment by macintacos** [comment]
Sure, I've updated it.

**Comment by user72356** [comment]
Isn't that exactly how Visual Studio (the original) works? At least that's what I remember from my VS days. My muscle memory tells me so.

**Comment by Imericxu** [comment]
@user72356 VS and VSCode are two different programs.

**Comment by user72356** [comment]
> @user72356 VS and VSCode are two different programs.

So what? You expect people not to compare feature sets when they know something that works better elsewhere? Especially another MS product.

**Comment by Imericxu** [comment]
My bad, I misunderstood it as you saying the current functionality is expected, especially since you have a random username.

**Comment by jrieken** [comment]
This actually started with https://github.com/microsoft/vscode/issues/151336

**Comment by macintacos** [comment]
Never thought I'd see the day - this seems to work pretty much exactly the way that I want it to, this is great!

For those who can't be bothered to open that issue, the setting is:

```
  "editor.suggest.selectQuickSuggestions": false,
```

It'll present as "disabled", but that appears to be on purpose. It still works.

**Comment by macintacos** [comment]
Actually... not quite. Thought it was working, but it doesn't seem to work the way I have selections set up with my keybindings.

Currently, as stated in the description, I use `tab`/`shift+tab` to navigate the suggestion list. This is set up like this:

```
  {
    "key": "tab",
    "command": "selectNextSuggestion",
    "when": "editorTextFocus && suggestWidgetMultipleSuggestions && suggestWidgetVisible"
  },
  {
    "key": "shift+tab",
    "command": "selectPrevSuggestion",
    "when": "editorTextFocus && suggestWidgetMultipleSuggestions && suggestWidgetVisible"
  }
```

With `"editor.suggest.selectQuickSuggestions": false`, the suggestion list isn't selected (great!) but `tab` doesn't seem to select the first item. Am I just missing a keybind/when-clause/command combination now?

**Comment by jrieken** [comment]
Yeah, there is a new `focusSuggestion` command which puts focus into the list first. By default it is bound to the trigger keybindings, e.g `cmd+space` etc. You should be able to configure it. 

https://github.com/microsoft/vscode/blob/6e2ee35d1630b4bb916f35fdbd678848d129547c/src/vs/editor/contrib/suggest/browser/suggestController.ts#L884-L895

**Comment by macintacos** [comment]
@jrieken thanks! I'll look into that.

Yeah I'll share what I come up with - I just noticed that it's because it wasn't working when only one item was shown in the suggestion list, because then technically the `suggestWidgetMultipleSuggestions` would be false in that case (which was causing the default behavior - inserting a tab instead of navigating into the list). Trying to figure it out.

**Comment by macintacos** [comment]
Okay yeah adding this seems to make things work the way I expect:

```
  {
    "key": "tab",
    "command": "focusSuggestion",
    "when": "editorFocus && suggestWidgetVisible"
  },
```

**Comment by tristone13th** [comment]
> Never thought I'd see the day - this seems to work pretty much exactly the way that I want it to, this is great!
> 
> For those who can't be bothered to open that issue, the setting is:
> 
> ```
>   "editor.suggest.selectQuickSuggestions": false,
> ```
> 
> It'll present as "disabled", but that appears to be on purpose. It still works.

Worked for me, thanks!

**Comment by jrieken** [comment]
👋 Attention: for next Insiders (which will be released after the break) I have renamed the setting to `editor.suggest.selectionMode`. Also, it is no longer a boolean anymore but allows for more fine grained control when it comes to auto suggest triggered by typing (aka quick suggest) or by trigger-characters.  

https://user-images.githubusercontent.com/1794099/209361942-55a68f8b-9fc7-45b2-981c-cf859c46cb72.mov

**Comment by jrieken** [comment]
Closing - remaining work should be tackled as separate bugs or polish issues
