### ISSUE TITLE
Breakpoints unbound when debugging Chrome, using JavaScript Debugger Nightly

### ISSUE THREAD

**Issue by bkindzierski** [microsoft/vscode#139808]

**Comment by bkindzierski** [comment]
I have another project using Angular 11 and  I recently updated to Angular 13 and using the same launch file I get unbound breakpoints. This works with Angular 11
here is my launch.json file:
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}",
            
        }
    ]
}

**Comment by bkindzierski** [comment]
Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:53:24.645Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT ia32 6.3.9600

**Comment by bkindzierski** [comment]
[
[vscode-debugadapter-a6857e42.json.gz](https://github.com/microsoft/vscode/files/7781408/vscode-debugadapter-a6857e42.json.gz)
](url)

**Comment by bkindzierski** [comment]
Angular CLI: 13.1.2
Node: 14.15.4
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 13.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
rxjs                            6.6.7
typescript                      4.5.4

**Comment by bkindzierski** [comment]
Do you need anything further from me to help this issue?

**Comment by connor4312** [comment]
It looks like your Angular build is not set up to generate sourcemaps. This documentation may be helpful: https://angular.io/guide/workspace-config#source-map-configuration
