### ISSUE TITLE
Debug: being asked to save a file on F5

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139880]
* Do normal extension development
* Step into code from extension host (i.e. not the extension)
* Stop debugging
* While code from extension host is visible, press F5

=> 🐛 you are being asked to save the file

**Comment by bpasero** [comment]
![recording](https://user-images.githubusercontent.com/900690/147669939-ab32125b-4697-4ce5-9d89-e140c909b7c8.gif)

**Comment by connor4312** [comment]
This actually looks intentional:

https://github.com/microsoft/vscode/blob/7d10ad3e294c05103bb5be31a11ee0f9ca9590cf/src/vs/workbench/contrib/debug/browser/debug.contribution.ts#L519-L529

But regardless of the active group configuration, we already call saveAll() which excludes untitled configurations, so this is kind of confusing...

https://github.com/microsoft/vscode/blob/e7b3724e0cdc9095d73a06b47203baa2c1777ea8/src/vs/workbench/contrib/debug/common/debugUtils.ts#L312-L325

I think `nonUntitledEditorsInActiveGroup` should be the default. This default is rather annoying imo, I use untitled editors as scratch buffers frequently.

cc @isidorn

**Comment by roblourens** [comment]
So that file that came from the DA is an "untitled" file?

**Comment by roblourens** [comment]
Same issue: https://github.com/microsoft/vscode/issues/117949
and original discussion in https://github.com/microsoft/vscode/issues/114890

I think maybe there are people writing some code in an untitled editor, then starting a launch config that references `${file}` and we can help them by making them save the file. We can probably distinguish between files that are actually `Untitled-1` vs these files with names right?

**Comment by connor4312** [comment]
Yea, that's a refinement. But I'm curious how often it helps with correctly saving an untitled file versus the false-positive rate we get when prompting.

**Comment by roblourens** [comment]
> I'm curious how often it helps with correctly saving an untitled file

I bet it's not uncommon especially in JS and Python

**Comment by bpasero** [comment]
So the culprit is this line:

https://github.com/microsoft/vscode/blob/e7b3724e0cdc9095d73a06b47203baa2c1777ea8/src/vs/workbench/contrib/debug/common/debugUtils.ts#L319-L320

If you want to special case only untitled editors, you would have to probe the resource of the active editor (via `EditorResourceAccessor`) to be `untitled` scheme.

**Comment by connor4312** [comment]
> I bet it's not uncommon especially in JS and Python

Could we only do this if `${file}` is present in any of the unresolved launch configuration properties?

**Comment by roblourens** [comment]
What other scenarios did you have in mind @isidorn?

**Comment by isidorn** [comment]
@roblourens no other scenarios then what the comment mentions - make sure to save the untitled file. As @bpasero suggests we could look at the active file to check if it is untitled - that sounds reasonable.

The whole point of that change is for beginner users when they just press start coding in an untitled file and press F5 that we prompt them to save the file, thus enabling debugging once there is an extension.

**Comment by roblourens** [comment]
I prefer the solution of checking the scheme and only saving untitled files. These other files from the debugger have the scheme `debug:`
