### ISSUE TITLE
Unable to open the pop-up box for the selected folder

### ISSUE THREAD

**Issue by donotloveshampo** [microsoft/vscode#139822]
After opening vscode for a long time, the pop-up box of the selected folder cannot be opened. You must restart vscode before it can be used normally  
system:  Apple M1 Pro

**Comment by JacksonKearl** [comment]
I'm not sure what you mean by "the pop-up box of the selected folder cannot be opened", could you show an example of what this looks like? ("pop-up box of the selected folder")
