### ISSUE TITLE
VS Code doesn't restore terminal names after restart

### ISSUE THREAD

**Issue by toolbox-design** [microsoft/vscode#139868]
Issue Type: <b>Feature Request</b>

Hello! I run many powershell terminals using VS Code, often I rename them. After reopening VS Code all terminals appear but they have standart names, such as 'powershell'.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Maybe 139276

Are you able to test with Insiders?

**Comment by meganrogge** [comment]
I can't reproduce this in insider's.
![Screen Shot 2021-12-30 at 11 31 52 AM](https://user-images.githubusercontent.com/29464607/147774859-4870934c-1ac3-4974-a805-f304ca78056a.png)

**Comment by toolbox-design** [comment]
After update to 1.63.2 problem disapperared. Thanks for helping!
