### ISSUE TITLE
Flutter | New Package not being Recognized

### ISSUE THREAD

**Issue by cacothi** [microsoft/vscode#139865]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Every new module added to Flutter project the VS Code do not recognize it. I do need to Close the VS Code and re open it again.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:38:17.605Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (2.17GB free)|
|Process Argv|--crash-reporter-id 64bc242c-9968-4327-8bca-9e2e35b5775b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
todo-pusher|Ale|0.0.2
dart-code|Dar|3.29.0
flutter|Dar|3.29.0
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
todo-tree|Gru|0.0.214
Angular2|joh|12.0.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-dotnet-runtime|ms-|1.5.0
vscode-typescript-tslint-plugin|ms-|1.3.3
awesome-flutter-snippets|Nas|3.0.2
java|red|1.2.0
vscode-scss-formatter|sib|2.3.3
vscode-stripe|str|2.0.10
generate-translation|thi|0.0.10
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2
vscode-icons|vsc|11.8.0
gitblame|wad|8.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710cf:30416617
vscexrecpromp3c:30407761

```

</details>

**Comment by tanhakabir** [comment]
Hm this is most likely an issue of the Flutter extension. I'd recommend filing your issue here: https://github.com/Dart-Code/Flutter
