### ISSUE TITLE
console.log adds additional blank lines

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode#139888]
As in microsoft/vscode-test#114, but now `run` does:

```ts
  return new Promise((resolve, reject) => {
    for (let i = 0; i < 200; i++) {
      console.log("x");
      console.log("y");
    }
    resolve();
  }
```

This is part of the output:

```
x

y

x

y

x

y

x

y

x

y
x

y
x

y

x
y
x
y

x

y
x

y
x
y
x
y
x

y

x
y

x

y

x

y
x
y
x
y
x
y
x
y
x
y

x

y

x

y
```

The blank lines appear at random places. I believe `console.log` is sending messages to the parent process, I don't know who is sending the additional blank lines.

**Comment by connor4312** [comment]
@deepak1556 it seems like this is logging extra lines. Removing the line gets rid of all logging, and adding `console.log('hi')` generates logs that include extra lines. It seems like something in Electron's console log implementation is going wrong

https://github.com/microsoft/vscode/blob/a1de3ce2a5c029b6bc68cd0f1cf1403023e5b269/src/vs/platform/log/common/logIpc.ts#L94

**Comment by connor4312** [comment]
Oh, nevermind, this is just in vscode-test as the reporter pointed out in a different issue
