### ISSUE TITLE
Azure extensions not showing subscriptions from 2FA tenants

### ISSUE THREAD

**Issue by danmana** [microsoft/vscode#139850]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:
Prerequisites: have access to 2 Azure tenants, one with 2FA enabled one without.

1. Install Azure Tools extension pack
2. Sign in Azure
3. Check App Service subscriptions in VSCode (or any of the Azure extension sections, Functions, Storage etc)
4. Only Subscriptions from tenants without 2-factor enabled are visible
Subscriptions from the 2FA tenant are missing.

If we set in Settings > Azure configuration > Azure tenant - the tenant with 2FA, then we can see the 2FA subscriptions, and they work as expected, but we can't see the ones from the other tenant.

There doesn't seem to be any way to show both 2FA and non-2FA tenant subscriptions.

**Comment by sandy081** [comment]
Please file the issue against the azure tools extension pack extension
