### ISSUE TITLE
Dissasembly view has non localized strings

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#139836]
Found this, maybe there are more:

https://github.com/microsoft/vscode/blob/4ed0329e9c5e12e2c7c59697facc96020b0768ab/src/vs/workbench/contrib/debug/browser/disassemblyView.ts#L717

**Comment by weinand** [comment]
@xisui-MSFT @yuehuang010 I've localized two strings, please verify my commit

**Comment by connor4312** [comment]
Verified via code review
