### ISSUE TITLE
My programmes are not running.

### ISSUE THREAD

**Issue by Vishal973** [microsoft/vscode#139851]
Issue Type: <b>Performance Issue</b>

When I tried to run the programmes on VS code it only shows that it is running, but it never completes (I never get any output from that). Some programmes (smaller ones) run and are completed, but some other programmes (bigger ones) run and never complete (I never get any output from that).

This has been happening since last 10 to 15 days.
 
**1.**  #include<stdio.h>

      int main(){
           int a = 70;
           printf("Your output is: %c", a);
           return 0;
        }

**2.**  #include<stdio.h>

     int main()
     {
     int a=1, n;
     printf("Enter your number \n");
     scanf("%d", &n);

     while((a+1)<n)
     {a++;
      n%a;
      if(n%a==0){printf("Given number is not a prime number"); break;}
       }
       if((a+1)==n){printf("Given number is a prime number");}
       if(n<=1){printf("Given number is not a prime number");}
       return 0;    
        }

The above programme-1 (in C language) runs properly, but programme-2 doesn't give me any output (it only shows 'Running').

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.73GB (4.94GB free)|
|Process Argv|--crash-reporter-id 6c762e54-8133-4012-846f-6ffd6cc54a7c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    79	  6572	code main
    0	    55	  4488	   extensionHost
    0	    18	 15868	     c:\Users\Admin\.vscode\extensions\ms-vscode.cpptools-1.8.0-insiders2\bin\cpptools.exe
    0	     5	   416	       console-window-host (Windows internal process)
    0	    14	 15280	       c:\Users\Admin\.vscode\extensions\ms-vscode.cpptools-1.8.0-insiders2/bin/cpptools-srv.exe 15868 {343210E5-5578-47C6-BC8C-6AE4231D032F}
    0	    11	 17676	       c:\Users\Admin\.vscode\extensions\ms-vscode.cpptools-1.8.0-insiders2/bin/cpptools-srv.exe 15868 {165C4255-1F18-4DAA-9E26-FC8099B9BD7D}
    0	    22	 19124	     "C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=4488
    0	    15	 12620	   crashpad-handler
    0	    76	 14588	   shared-process
    0	    25	 14536	     watcherServiceParcelSharedProcess
    0	    25	 18508	     ptyHost
    0	   129	 15376	   gpu-process
    0	    20	 16976	   utility-network-service
    0	   154	 19320	   window (Rough_Work.c - Visual Studio Code - Visual Studio Code)
    0	    53	 21384	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Rough_Work.c - Visual Studio Code - Visual Studio Code)
|    Folder (Visual Studio Code): 57 files
|      File types: c(26) exe(25) json(2) py(1)
|      Conf files: settings.json(2);
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
code-runner|for|0.11.6
better-cpp-syntax|jef|1.15.10
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.0-insiders2
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710cf:30416617
vscexrecpromp3t1:30407762

```

</details>

**Comment by Vishal973** [comment]
I couldn’t understand that how should I file the report on C++ extension on GitHub.And the version (that you asked in previous mail)  of C++ extensions are:Name: Better C++ SyntaxId: jeff-hykin.better-cpp-syntaxDescription: The bleeding edge of the C++ syntaxVersion: 1.15.10Publisher: Jeff HykinVS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax Name: C/C++Id: ms-vscode.cpptoolsDescription: C/C++ IntelliSense, debugging, and code browsing.Version: 1.8.0-insiders2Publisher: MicrosoftVS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools Name: C/C++ Extension PackId: ms-vscode.cpptools-extension-packDescription: Popular extensions for C++ development in Visual Studio Code.Version: 1.1.0Publisher: MicrosoftVS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-extension-pack Name: C/C++ ThemesId: ms-vscode.cpptools-themesDescription: UI Themes for C/C++ extension.Version: 1.0.0Publisher: MicrosoftVS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-themes I tried to get rid from this issue, so I installed the latest version of gcc compiler and I also reinstalled the VS Code. But no avail.Please solve my issue in a easy way.  Sent from Mail for Windows From: Andre WeinandSent: 29 December 2021 01:45To: microsoft/vscodeCc: Vishal973; AuthorSubject: Re: [microsoft/vscode] My programmes are not running. (Issue #139851) /extCpp—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by weinand** [comment]
VS Code has no built-in C/C++ support, so the VS Code team cannot help. 
Please file the a bug or question here: https://github.com/microsoft/vscode-cpptools/issues/new/choose
