### ISSUE TITLE
window.withProgress() doesn't update progress synchronously

### ISSUE THREAD

**Issue by adriancuadrado** [microsoft/vscode#139855]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create an extension with this code:
  ```ts
  import * as vscode from 'vscode';
  
  export function activate(context: vscode.ExtensionContext) {
      context.subscriptions.push(vscode.commands.registerCommand('helloworld.helloworld', () => {
          vscode.window.withProgress(
              {
                  location: vscode.ProgressLocation.Notification,
                  title: "Hello world!"
              },
              async progress => {
                  for (let i = 0; i < 10; ++i) {
                      debugger;
                      progress.report({ increment: 10 });
                  }
              });
      }));
  }
  ```
2. Execute the extension and see how the progress bar isn't updated each time the breakpoint is hit.

In my use case scenario, I originally had a really long loop that took some time to execute instead of the breakpoint. Apparently, for some reason the progress bar is only updated (but not always, just sometimes) when I put this code next to the breakpoint:
`await new Promise<void>(r => setTimeout(r, 0));`

**Comment by jrieken** [comment]
> In my use case scenario, I originally had a really long loop that took some time to execute instead of the breakpoint. 

I guess that long loop does execute inside the extension host process? Iff so it might saturate the process and the message to update the progress (in the renderer process) can never be send. Can you yield from within your operation from time to time?

**Comment by adriancuadrado** [comment]
What do you mean by "yield"? Do you mean using the "yield" operator that is used inside generic functions? My loop is not in a generic function, so I don't really understand what you mean.

**Comment by jrieken** [comment]
In JavaScript there is a single threaded event loop that continuously executes all code. You can block a single iteration of that loop by synchronously computing something for a long time (like parsing documents or so). When happens no other code will run, e.g the code that updates the progress has no chance of running. I suspect that's what's happening because pausing at a breakpoint has the same effect. Yielding is often used to say "do work for a short time and continue the rest with a setTimeout-callback"

**Comment by adriancuadrado** [comment]
"Can you yield your operation from time to time?"
After reading your comment and doing some research, I came to the conclusion that you are basically asking me to execute `await new Promise<void>(r => setTimeout(r, 0));` from time to time. Yes, I can do that, I just wasn't aware that this is fundamentally how nodejs works.
