### ISSUE TITLE
Missing menu or button to execute git rebase --continue

### ISSUE THREAD

**Issue by DerAndere1** [microsoft/vscode#139879]
I am missing a menu or button to execute `git rebase --continue`. At the moment I have to go to the terminal within VSCode (which is running PowerShell) and execute the following command: 
```
git rebase --continue
``` 
When rebasing a feature branch with multiple new, conflicting commits onto the main branch, I want to follow these steps:
- use the GUI to start the rebase
- resolve conflicts within VSCode
- save the changed file
- close the changed file
- stage the changed file using the GUI of VSCode+GitLens to add them to the index
- click a menu entry or button to continue the rebasing

As a bonus, the GUI elements for staging and for continuing or aborting the rebase should show up next to each other in a well suited place after starting the rebase. The GUI element for `continue`ing should be grayed out (inactive) as long as there are unstaged files.

Benefits: Grapical user interface elements visualize existing options. This helps users that have little experience with git rebasing.

**Comment by DerAndere1** [comment]
This seems to be implemented since version 1.26.1 according to https://github.com/microsoft/vscode/issues/6614#issuecomment-426163072: 

> As of 1.26.0 or 1.26.1, clicking commit will do a rebase --continue if a rebase is underway.

Maybe it is better to focus on another related issue: https://github.com/microsoft/vscode/issues/60149.

**Comment by lszomoru** [comment]
Closing this issue for now.
