### ISSUE TITLE
Unable to resolve your shell environment - Fish Shell

### ISSUE THREAD

**Issue by jshwrner** [microsoft/vscode#139867]
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.63.2 (Universal)
- Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
- Date: 2021-12-15T09:37:28.172Z
- Electron: 13.5.2
- Chromium: 91.0.4472.164
- Node.js: 14.16.0
- V8: 9.1.269.39-electron.0
- OS: Darwin x64 17.7.0

Steps to Reproduce:

1. Open VSCode
2. Error occurs on startup

![vscode_error](https://user-images.githubusercontent.com/22651504/147626054-744e8f59-f6b1-4ed4-8593-b4ce10f7ef00.png)

Everytime VSCode opens, I get the following error: "Unable to resolve your shell environment: A system error occurred (spawn /bin/fish ENOENT). I installed Fish shell via Homebrew and it installed it to `/usr/local/bin/fish`. `/bin` includes other shells like bash, zsh, etc but Fish is not listed here. Here are my settings: 

```
	"terminal.integrated.profiles.osx": {
		"Fish": {
			"path": "/usr/local/bin/fish"
		}
	},
	"terminal.integrated.defaultProfile.osx": "Fish",
```

For some reason, VSCode seems to still be looking at `/bin/fish` instead of the location defined in settings. This continues to happen when I change the default terminal to something else as well.

**Comment by meganrogge** [comment]
if you change the name of the profile to "fish2" does it work? and what do you see when you run `select default profile`?

**Comment by jshwrner** [comment]
Thanks for the response. No, changing the profile name to `fish2` does not help and changing the default profile doesn't help either. This only happens on start up though. If I change the default profile to bash, the terminal pops up fine, but if I close and reopen VSCode, I get the same error regardless of which profile is default.

**Comment by meganrogge** [comment]
ok I just tried what you have for the path and it works - I think you need the `-l` args

```
"fish": {
			"path": "/usr/local/bin/fish",
			"args": [
				"-l"
			],
		},
```

**Comment by meganrogge** [comment]
pls lmk if that does not fix your issue

**Comment by jshwrner** [comment]
Still seems to crash on startup

![Screen Shot 2022-01-03 at 4 55 04 PM](https://user-images.githubusercontent.com/22651504/147989276-d63ba2b1-5439-40b4-9c15-d1cf3fb8a0d1.png)

**Comment by meganrogge** [comment]
does that path exist on your computer?

**Comment by jshwrner** [comment]
![Screen Shot 2022-01-04 at 8 35 57 AM](https://user-images.githubusercontent.com/22651504/148075002-6d60885d-6d2c-400c-a91b-22a660e6107b.png)

Yeah, it also looks like that's a shortcut pointing to `/usr/local/Cellar/fish/2.7.1/bin/fish`. I also tried using this explicit path and I get the same error. `/bin/fish` does not exist though because it was installed via Homebrew

**Comment by Tyriar** [comment]
We use the `$SHELL` environment variable which it appears you have set to /bin/fish, or homebrew did 🤷 

Look into changing it (via the `chsh` command?).

**Comment by jshwrner** [comment]
I was able to update this on my Mac by updating `Users & Groups -> (right click user) Advanced Options... -> Login Shell` and now my terminal reflects changes to `$SHELL`; however, VSCode still isn't noticing those changes. Is there somewhere in VSCode that's setting or caching this path that I could update? 

![shell](https://user-images.githubusercontent.com/22651504/148314309-a04fee1f-c885-472e-bf50-c25240479a08.png)

**Comment by jshwrner** [comment]
> We use the `$SHELL` environment variable which it appears you have set to /bin/fish, or homebrew did 🤷
> 
> Look into changing it (via the `chsh` command?).

Thanks for the insight, this was super helpful! I was able to run `sudo chsh -s /usr/local/bin/fish ` in my VSCode terminal and after I logged out and back in again, the error was gone and `echo $SHELL` reflected the proper path. Thanks for your help!
