### ISSUE TITLE
Use Material Icon Theme as default icon theme

### ISSUE THREAD

**Issue by joeljose350** [microsoft/vscode#139838]
The current file icon themes included with VS Code (Minimal and Seti) look dated and have fewer icons than [Material Icon Theme](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme). Including Material Icon Theme with VS Code and maybe even using it as the default File Icon Theme would be a good idea imo.

**Comment by drweb86** [comment]
I vote for that too. But I think - better to install automatically most downloaded file icon theme plugin upon installing VS code

**Comment by aeschli** [comment]
Sorry , we have no plans for that. It's easy for users to install the material icon theme if they prefer it over the seti theme.
