### ISSUE TITLE
[question] Clarify how test output is supposed to be sent

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode#139887]
I've filed issues microsoft/vscode-test#114 and microsoft/vscode-test#115. The underlying reason for both is the same. I'm trying to run some jest tests and there is no reasonable way to show the output of those tests in the console.

1. The test runner writes to stdout/stderr, but these streams are not forwarded to the console at all (#114).

2. If I replace stdout/err write function with a console equivalent, as in the code snippet below, the output is interspersed with blank lines all over the place (#115). Notice that I consider the "write rewriting" hack even worse than the blank lines.

```ts
  let remaining = '';
  process.stderr.write = (buffer: string) => {
    let lines = (remaining + buffer).split('\n');
    remaining = lines.pop();
    lines.forEach((l) => console.log(l));
    return true;
  };
```

I'm surely missing something here, I refuse to believe this jumping through hoops is actually required.

---

Also, notice that in runTest.ts you have this code:

```ts
	return new Promise<number>((resolve, reject) => {
...
		cmd.stdout.on('data', function (data) {
			console.log(data.toString());
		});

...
```

I know there are similar examples in node's `child_process` documentation, but I believe this code is wrong, `console.log` will add newlines to each `data`, but `data` is something originally passed to `write`, so newlines were explicitly added, there is a mismatch from a buffer oriented interface to a line oriented one, that's the reason why I had to write my code above as I did. Now, I don't know about all the IPC plumbing going on here, but this may have something to do with the extra blank lines.

**Comment by connor4312** [comment]
Re the recommendation: in response to the linked issue, there's now support for process.stdout/stderr writing in the _Node.js_ extension host. It comes with two caveats:

1. Data written is only logged once a new line `\n` is written. Our log architecture is built around messages and doesn't support arbitrary streams, and I don't believe it's in-scope to change that for just this use case.
2. This is only supported in the Node.js extension host. It won't work in web extensions / in [`@vscode/test-web`](https://github.com/microsoft/vscode-test-web). The `console` methods are the only isomorphic methods that are available between these platforms, so they should be generally preferred.
