### ISSUE TITLE
Features like go to and definition searching unresponsive

### ISSUE THREAD

**Issue by aljazvetrih** [microsoft/vscode#139844]
Issue Type: <b>Bug</b>

When clicking on go to definition, it is loading, and it doesn't load or go to it. It is the same with CTRL+click feature.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.94GB (5.41GB free)|
|Process Argv|--crash-reporter-id 16cef231-2077-47c0-81c3-00be962e2b98|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-wsl|ms-|0.63.13
cpptools|ms-|1.7.1
c-cpp-flag-debugging|uts|0.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710cf:30416617
vscexrecpromp3t1:30407762

```

</details>

**Comment by joaomoreno** [comment]
In which programming language?

**Comment by aljazvetrih** [comment]
JavaScript, React native.

V V pet., 31. dec. 2021 ob 13:34 je oseba João Moreno <
***@***.***> napisala:

**Comment by mjbvz** [comment]
Please provide steps the reproduce the issue
