### ISSUE TITLE
Cannot type single quote in editor

### ISSUE THREAD

**Issue by SidusCaelum** [microsoft/vscode#139826]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: November 2021 (version 1.63)
- OS Version: Windows 10

Steps to Reproduce:

1. install vscode
2. attempt to type single quote in editor
3. get prompted in status bar with (') was press. Waiting for second key of chord.

There does not seem to be an easy direct way to disable this functionality or a reasonable situation for it to be setup as a default behavior. 

**Keyboard Language**
US English

**Current list of plugins**
Go
HashiCorp Terraform
Rust
Vue Language Features (Volar)
Vim
Community Material Theme
Material Icon Theme

**settings.json**
```
{
    "workbench.colorTheme": "Community Material Theme Palenight",
    "editor.fontFamily": "'Fira Code', Consolas, 'Courier New', monospace",
    "editor.fontLigatures": true,
    "editor.fontWeight": "bold",
    "vim.insertModeKeyBindings": [
        {
            "before": [
                "f",
                "d"
            ],
            "after": [
                "<Esc>"
            ]
        }
    ],
    "workbench.iconTheme": "material-icon-theme",
    "editor.fontSize": 16,
    "editor.minimap.enabled": false,
    "editor.minimap.maxColumn": 80,
    // "typescript.updateImportsOnFileMove.enabled": "always",
    // "[vue]": {
    //     "editor.defaultFormatter": "johnsoncodehk.volar"
    // },
    // "typescript.preferences.quoteStyle": "single",
    // "javascript.preferences.quoteStyle": "single",
}
```

**Comment by SidusCaelum** [comment]
This issue seems to be fixed in the latest insider's edition.

**Comment by gjsjohnmurray** [comment]
Sounds like in your non-Insiders instance you have a multi-key binding (aka chord) which begins with the single-quote key.

First use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

If it isn't, see https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization for how to open your keybindings.json file. If you can't find the problem binding there and delete it, post the file contents here.

**Comment by alexdima** [comment]
Also please check your `keybindings.json` file.

**Comment by SidusCaelum** [comment]
@alexdima turns out it was a misconfigured keybinding. A stray ' was hanging around. Thanks for all the help!
