### ISSUE TITLE
Make Context Menu shortcut programmable in all settings

### ISSUE THREAD

**Issue by azaslavsky** [microsoft/vscode#139817]
For certain cases (like when the sidebar has focus, eg the file explorer), the only way to "right click" on a highlighted element via the keyboard is via the default `shift` + `f10` binding, as described in https://github.com/microsoft/vscode/issues/123534.  It would be nice to be able to set overwrite this keybinding in keybindings.json, and more generally, to be able set the "open context menu" shortcut for all areas of focus (today, only `editor.action.showContextMenu` is possible).

**Comment by alexdima** [comment]
Each component that shows a context menu would need to create a specific command and then that command could be bound via keybindings. #123534 mentions the explorer, so we could start there.
