### ISSUE TITLE
Scrollable doesn't support decimal values

### ISSUE THREAD

**Issue by ZhangSongyi** [microsoft/vscode#139877]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. have this setting `"window.zoomLevel": 0.8,`
1. open a markdown file containing a long title (see below)
2. shrink the window until the breadcrumbs cannot fully shown.
3. drag the scroll bar of the breadcrumbs to the right side.
4. click anywhere inside the panel.
5. the breadcrumbs start wriggling to the right🐛

```md

# A Looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong title

Lorem markdownum, onerosus, rebellant pectore divum; in quid iactantem levatae
distulit. Genitor nescio nox Argolicas in natis Interea Iovis mihi lynca,
capillis. Comitante conpulit negat quibus. Fuit minuuntur auctoris ramos suaque
disiectisque vestis.

```

![GIF 2021-12-29 20-55-04](https://user-images.githubusercontent.com/12276998/147664679-92f7c5e5-2d3d-436d-a11c-727655c2b904.gif)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22523
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (2.18GB free)|
|Process Argv|C:\\Users\\zhang\\Documents\\TMP\\test.md --crash-reporter-id 99c26a9b-0c96-47a2-825a-93f72f42c876|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710cf:30416617
vscexrecpromp3t3:30407764

```

</details>

**Comment by cas--** [comment]
Caused by attempting to fix #135721

**Comment by jrieken** [comment]
Doesn't reproduce for me. Anything special in your setup? Special zoom level?

**Comment by cas--** [comment]
@jrieken I am not sure why my comment has been marked off-topic. I am seeing the exact same issue as reported here which I highlighted in the original issue:

> I tested with newly released version 1.62 and it's actually worse since the breadcrumb bar now slowly scrolls to the start of the with every cursor movement then jumps back to the end when typing. Could this regression be a result of this commit e764729

**Comment by jrieken** [comment]
> @jrieken I am not sure why my comment has been marked off-topic. 

It's off-topic because you linked to an unrelated commit. Please help me reproduce by answering questions that are asked in this issue

**Comment by cas--** [comment]
It can be reproduced as explained by both myself in #135721 and the OP but also make sure to set a custom window zoom level e.g. 0.8

**Comment by jrieken** [comment]
> but also make sure to set a custom window zoom level e.g. 0.8

That's the missing piece

**Comment by jrieken** [comment]
This is an issue with our scrollable element and it always cutting off fractional values. I have pushed a workaround in breadcrumbs so that this doesn't so prominently anymore but the underlaying issue still exists. 

Forwarding to @alexdima to look into the scroll bar
