### ISSUE TITLE
Show error in Explorer tree file icon

### ISSUE THREAD

**Issue by echo-sean** [Microsoft/vscode#13985]
This is a request for visual feedback of errors.

If I am working on a file and make a change that causes errors in other files I would like to be able to glance over to the Explorer tree and see where the errors are.

Possibly add a red x (or circle) on the file (or parent folder) icon that has the error.

I know I can have a look at "Problems" - but that involves looking down and clicking. 
I use "Problems" if there is a large amount of issues or I want to see details.

I'm currently using VSCode 1.6.1.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/782
