### ISSUE TITLE
Many console errors when starting VSC

### ISSUE THREAD

**Issue by sylvain-priser** [microsoft/vscode#139889]
Issue Type: <b>Bug</b>

When launching VSC, I get many errors (58) in the dev console. I noticed that while trying to undestand why my salesforce SFDX extension was not working properly (cannot see the Deploy source to Org in contextual menu).

Could you help me fixing issues below :

marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_CONNECTION_RESET
workbench.desktop.main.js:77 [Extension Host] (node:6764) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code --trace-deprecation ...` to show where the warning was created)
I @ workbench.desktop.main.js:77
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_CONNECTION_RESET
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_CONNECTION_RESET
workbench.desktop.main.js:77 [Extension Host] Cannot find fr, defaulting to en
workbench.desktop.main.js:77 [Extension Host] (node:6764) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
workbench.desktop.main.js:77 [Extension Host] (node:6764) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
workbench.desktop.main.js:77 [Extension Host] (node:6764) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
workbench.desktop.main.js:77 [Extension Host] (node:6764) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
workbench.desktop.main.js:77 [Extension Host] (node:6764) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
workbench.desktop.main.js:77 [Extension Host] (node:6764) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
workbench.desktop.main.js:77 [Extension Host] (node:6764) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
workbench.desktop.main.js:77 [Extension Host] (node:6764) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
workbench.desktop.main.js:77 [Extension Host] (node:6764) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
workbench.desktop.main.js:77 [Extension Host] (node:6764) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
workbench.desktop.main.js:77 [Extension Host] (node:6764) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
. . .
workbench.desktop.main.js:77 [Extension Host]% {message: "Git error", stdout: "", stderr: "fatal: c:\\Users\\SylvainPriser\\Documents\\sfdx\\crg\\c…crg\\chr\\sfdx-project.json' is outside repository\n", exitCode: 128}exitCode: 128message: "Git error"stderr: "fatal: c:\\Users\\SylvainPriser\\Documents\\sfdx\\crg\\chr\\sfdx-project.json: 'c:\\Users\\SylvainPriser\\Documents\\sfdx\\crg\\chr\\sfdx-project.json' is outside repository\n"stdout: ""__proto__: Object
vscodeexperiments.azureedge.net/experiments/vscode-experiments.json:1 Failed to load resource: net::ERR_CONNECTION_RESET
workbench.desktop.main.js:77 [Extension Host] Error: read ECONNRESET	at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (1.27GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/SylvainPriser/Documents/sfdx/crg/chr --crash-reporter-id 9548980c-5638-4e18-90b4-f37a89c5791c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
lana|Fin|1.3.5
vscode-drawio|hed|1.6.3
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
powershell|ms-|2021.10.2
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode|sal|53.8.0
salesforcedx-vscode-apex|sal|53.8.0
salesforcedx-vscode-apex-debugger|sal|53.8.0
salesforcedx-vscode-apex-replay-debugger|sal|53.8.0
salesforcedx-vscode-core|sal|53.8.0
salesforcedx-vscode-lightning|sal|53.8.0
salesforcedx-vscode-lwc|sal|53.8.0
salesforcedx-vscode-soql|sal|53.8.0
salesforcedx-vscode-visualforce|sal|53.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710cf:30416617
vscexrecpromp3t1:30407762

```

</details>

**Comment by deepak1556** [comment]
Does the issue happen with latest stable `1.66.2` ?
