### ISSUE TITLE
supportUntrustedWorkspaces override is ignored for source control providers

### ISSUE THREAD

**Issue by joepie91** [microsoft/vscode#139803]
Issue Type: <b>Bug</b>

1. Open untrusted workspace
2. See an error in the source control pane: "None of the registered source control providers work in Restricted Mode"
3. Observe that `vscode.git` has been disabled in untrusted workspaces in a [recent update](https://github.com/microsoft/vscode/issues/139124)
4. Attempt to re-enable it by adding an override for it to `extensions.supportUntrustedWorkspaces` in `settings.json`
5. Observe that, after a reload, the extension is indeed re-enabled under the built-in extensions, but...
6. ... the source control pane still shows the same error, instead of the actual Git integration

From a glance at the implementation for this error condition, [the error seems to be *always* shown](https://github.com/microsoft/vscode/blob/67d6356a25661ecd2bdaf13a3fc8c9d14ee5161f/src/vs/workbench/contrib/scm/browser/scm.contribution.ts#L66) when the editor is in Restricted Mode, regardless of whether any source control providers have *actually* indicated support for this mode.

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:02:02.183Z)
OS version: Linux x64 5.14.21
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|62.76GB (2.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma5|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|plasma5|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
Nix|bbe|1.0.1
language-postcss|cpy|1.1.0
flow-for-vscode|flo|1.9.2
beautify|Hoo|1.5.0
l13-diff|L13|1.0.3
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
vscode-quick-open-create|noc|0.6.0
mdx|sil|0.1.0
rewrap|stk|1.15.4
debug|web|0.25.1

(9 theme extensions excluded)

</details>

**Comment by lszomoru** [comment]
To verify:
1. Add the following into your `settings.json`:
  ```json
      "extensions.supportUntrustedWorkspaces": {
          "vscode.git": {
              "supported": true
          }
      },
  ```
2. Open a workspace containing a git repository and choose to stay in restricted.
3. Confirm that the SCM viewlet is rendered as expected and no welcome messages are shown
