### ISSUE TITLE
multi-cursor doesn't respect line wrapping

### ISSUE THREAD

**Issue by soanvig** [microsoft/vscode#139847]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.2
- OS Version: Windows 10 64 bit

Steps to Reproduce:

1. Enter lines which are wrapped
2. Try to select first and second physical line with multi-cursor (keyboard) - see GIF below

![line-break-bug](https://user-images.githubusercontent.com/7525286/147570625-d16657da-b707-4470-a30b-ffffbd8112a0.gif)

multi-cursor should actually select only physical lines, not wrapped ones.
Also as visible on GIF: going back to beginning of the line fixes multi-cursor

**Comment by alexdima** [comment]
Please update vscode. This has been changed via https://github.com/microsoft/vscode/issues/26393
