### ISSUE TITLE
[JS] IntelliSense doesn't detect function properties defined outside an object literal initialisation

### ISSUE THREAD

**Issue by NickMackz** [Microsoft/vscode#13988]
- VSCode Version: 1.6.1
- OS Version: Fedora 21

If an object is initialised using the literal notation (object = {}) and a function property is added to the object outside the initialisation, IntelliSense doesn't detect it for code completion.

Steps to Reproduce:
![intellisense example](https://cloud.githubusercontent.com/assets/5260674/19513070/8b847ade-95e6-11e6-8d70-c3d724f6ff31.png)

**Comment by roblourens** [comment]
That's just how typescript infers the types (TS language server is used for JS intellisense). You could hover over 'example' to see the type. If you ask on StackOverflow or a TS forum someone might be able to tell you if there's a setting to make this scenario work better for you.

**Comment by NickMackz** [comment]
Thanks for the response, but I think you might have misunderstood the issue. I would expect code completion to suggest both the 'internal' function, like it does, and also the 'external' function, which it doesn't.

This is particularly an issue for node modules that are written in this style:
```
var user = {};
module.exports = user;

user.getUsername = function(req) {
   var username = "";
   ...
   return username;
}

user.getAccessLevel = function(req, domain) {
   var level = "guest";
   ...
   return level;
}
```

When this module is required in another module, VSCode won't offer code completions for any of it's functions.

**Comment by roblourens** [comment]
I understand, I just think that's expected. Here's a portion of the docs that explain more - https://github.com/Microsoft/TypeScript/wiki/Salsa#intellisense-based-on-type-inference

**Comment by NickMackz** [comment]
Oh I see. Fair enough then. Thanks for linking the docs.
