### ISSUE TITLE
omnisharp server is not running

### ISSUE THREAD

**Issue by st4nthe** [microsoft/vscode#139813]
when i try to press run tests in context it doesnt do anything all it does is say "failed to run test because omnisharp servers is not running" and i have tries numerous things. if someone could get back to me with advice it would be greatly appreciated

**Comment by tanhakabir** [comment]
Hello! Sorry about that! Unfortunately that seems like an omnisharp specific error from the omnisharp extension and not VS Code, you can ask your question here to get more help https://github.com/OmniSharp/omnisharp-vscode.
