### ISSUE TITLE
Underscored methods and properties should go last 

### ISSUE THREAD

**Issue by Noriller** [microsoft/vscode#139816]
I believe most languages have the underscore prefix as a convention to naming private components.
But I realized that underscored components are actually appearing first on IntelliSense (even with no extensions enabled).

Best case scenario, it should be able to know if it's being called from the scope or from outside of it.
Inside, it should probably order the list ignoring the first prefix underscore.
And then, since those shouldn't be used outside their scope, outside the scope underscored components should be ordered after all other components with double (or more) underscored components coming after that, in order of how many underscores they have first.

At least, it should order underscored methods and properties after all the others.

**Comment by Noriller** [comment]
For example:

```js
class MyExampleClass {
  _privateStuff = 'private';

  constructor() {
    this.name = 'My Example Class';
  }

  publicMethod() {
    return "I'm public";
  }

  _privateMethod() {
    return "I'm private";
  }
}
```
This is kind of ok I guess... maybe it should sort while ignoring the underscore.
![image](https://user-images.githubusercontent.com/54413263/148095965-2d0938ab-67fd-4a8a-b16c-3bfbd8e1faaf.png)

Then you have this:
![image](https://user-images.githubusercontent.com/54413263/148096145-4140a878-2b97-4d8a-b1fd-4fa65532a5f1.png)
The private methods should come last.

The leading underscore is a convention. So when you have a true private available:
```js
class MyExampleClass {
  #privateStuff = 'private';

  constructor() {
    this.name = 'My Example Class';
  }

  publicMethod() {
    return "I'm public";
  }

  #privateMethod() {
    return "I'm private";
  }
}
```
![image](https://user-images.githubusercontent.com/54413263/148096708-0bc50f44-33a6-4670-b0b0-2ad302411f7f.png)
It works as intended and completely hides it.
Unless you're inside it:
![image](https://user-images.githubusercontent.com/54413263/148097368-b5979f78-2d07-4359-b392-3463473464e8.png)


So the suggestion is, instead of it appearing like this:
![image](https://user-images.githubusercontent.com/54413263/148096906-58c1033f-6c3f-41ce-a6da-5abe4b7565ca.png)
It would appear in this order:

- name
- publicMethod
- _privateMethod
- _privateStuff

This, could be a flag where you select to sort the methods and properties to go last.
Since depending on the language you might want or not to access/see the "private" methods, maybe it could have an additional flag to hide or not them (as if they were a "true" private).

All examples made on VSCode restarted with extensions disabled.

**Comment by jrieken** [comment]
TypeScript could set the initial order when sending items via the `sortText` but I'd call it stretch
