### ISSUE TITLE
Visual Studio Code text turning white

### ISSUE THREAD

**Issue by mynameish4r01d** [microsoft/vscode#139827]
Issue Type: <b>Bug</b>

for some reason when i open a different window on my computer the VSC software text turns white and is really starting to bug me is there a fix for it???

here a screen shot
![Screenshot (32)](https://user-images.githubusercontent.com/96763884/147546792-e0f14852-9f73-44dd-a39d-a750c126a4b9.png)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.75GB (17.35GB free)|
|Process Argv|--crash-reporter-id 144e1a16-90e4-4836-83a0-f433cbcce81e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30416617
vscexrecpromp3t2:30407763

```

</details>

**Comment by mynameish4r01d** [comment]
> Thanks for reporting this issue! Unfortunately, it's hard for us to understand what issue you're seeing. Please help us out by providing a screen recording showing exactly what isn't working as expected. While we can work with most standard formats, `.gif` files are preferred as they are displayed inline on GitHub. You may find https://gifcap.dev helpful as a browser-based gif recording tool.
> 
> If the issue depends on keyboard input, you can help us by enabling screencast mode for the recording (`Developer: Toggle Screencast Mode` in the command palette).
> 
> Happy coding!

i just added a image showing how it looks and it gets a little bit worse from there is there a fix???

**Comment by mynameish4r01d** [comment]
> i just added a image showing how it looks and it gets a little bit worse from there is there a fix???

i just added a image showing how it looks and it gets a little bit worse from there is there a fix???

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by yan-iso** [comment]
> Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`
> 
> If that helps, you can permanently configure this option via:
> 
> * Command Palette search for "Configure Runtime Arguments"
> * Set `disable-hardware-acceleration: true`
> * Restart
thank you it works

**Comment by yan-iso** [comment]
> Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`
> 
> If that helps, you can permanently configure this option via:
> 
> * Command Palette search for "Configure Runtime Arguments"
> * Set `disable-hardware-acceleration: true`
> * Restart


thank you it worked
