### ISSUE TITLE
How to disable right click context menu in custom editor extension (copy/paste/cut)?

### ISSUE THREAD

**Issue by Codes-Breaker** [microsoft/vscode#139824]
How to disable right click context menu in custom editor (copy/paste/cut)?
is it even possible to hide it in custom editor extension?
![image](https://user-images.githubusercontent.com/10660055/147524173-5277e3fc-57c0-47ea-88ba-b37b28c50451.png)

**Comment by mjbvz** [comment]
Try adding your own listener to the `'contextmenu'` event and preventing VS Code's default behavior with `stopImmediatePropagation`:

```js
window.addEventListener('contextmenu', e => {
    e.stopImmediatePropagation()
}, true);
```
