### ISSUE TITLE
JSX auto-import broken

### ISSUE THREAD

**Issue by ehsanghorbani190** [microsoft/vscode#139810]
JSX auto-import is broken. also , vscode is super slow while working with multiple files or even a single file within a react project.
Issue Type: <b>Bug</b>

1. Open your vscode in some react project with some components inside a folder (e.g. Components) inside src folder.
2. try to use that component inside App.js render function , it would'nt suggest it and even if you type it your self , it doesn't recognize it and won't import it. You can see in the image below that i have a component named Section and it wouldn't recognize it at all.
![Screenshot_2021-12-27_22-46-35](https://user-images.githubusercontent.com/35449522/147500853-c31b68ca-6252-4701-a606-5163da93ae39.png)

However it detects it after some time and opening the file many times but even after that this problem accrues sometimes.

VS Code version: Code - OSS 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-07T19:37:13.664Z)
OS version: Linux x64 5.15.7-1-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2455)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.58GB (7.23GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
simple-react-snippets|bur|1.2.5
path-intellisense|chr|2.5.0
vscode-eslint|dba|2.2.2
file-icons|fil|1.0.29
mayukaithemevsc|Gul|3.1.0
vscode-styled-components|jpo|1.7.0
code-spell-checker|str|2.0.14
vscode-import-cost|wix|2.15.0

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by ehsanghorbani190** [comment]
@gjsjohnmurray 
just tested extension bisect and problem still exists even with all extensions disabled

**Comment by mjbvz** [comment]
Please provide steps to reproduce the problem

**Comment by ehsanghorbani190** [comment]
@mjbvz 
there's 2 steps in the main issue :D 
So i don't know why but i created a `jsconfig.json` file in the root folder with this content : 

`{
    "compilerOptions": {
      "baseUrl": "./src",
      "checkJs": true,
      "jsx": "react",
      "alwaysStrict": true
    }
  }`
I don't know why but this helps alot and makes problem almost gone , but the bug accrues sometimes.

**Comment by mjbvz** [comment]
Please provide specific steps to reproduce the problem
