### ISSUE TITLE
Comments not working in Script tag

### ISSUE THREAD

**Issue by pratham-ops** [microsoft/vscode#139801]
Issue Type: <b>Performance Issue</b>

1- Create a html file
2- In html file use scipt tag with type="text/javascript"
3- With some js written in it , commenting out doesnt works with <-- this, 
instead we have to manually use // on each line to comment it out

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.92GB (0.49GB free)|
|Process Argv|--crash-reporter-id 2c91b828-0f9c-477a-a72e-8e857d62bfd4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    94	  6968	code main
    1	    84	  3936	   issue-reporter
    1	   120	  4908	   gpu-process
    0	   380	  5352	   extensionHost
    0	    25	  5608	     c:\Users\ppmk6\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\3.1.19\dotnet.exe c:\Users\ppmk6\.vscode\extensions\visualstudioexptteam.vscodeintellicode-insiders-1.1.5\dist\Prose\ProseServer.dll
    0	    10	  4896	       console-window-host (Windows internal process)
    0	    20	  7212	     c:\Users\ppmk6\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\4.0.37\x86_64-pc-windows-gnu\TabNine.exe --client=vscode --no-lsp=true --client-metadata clientVersion=1.63.2 pluginVersion=3.5.11 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 "vscode-theme-name=One Dark Pro Flat" vscode-theme-kind=Dark vscode-machine-id=5f3af79e63968d882e5d756cbc22024853f7fa698a53dbb851ba3cda46bb7c7e vscode-is-new-app-install=false vscode-session-id=609977f5-90f4-4a5c-8763-abf1ac5ede591640606465797 vscode-language=en "vscode-app-name=Visual Studio Code" vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=0
    0	    10	  4140	       console-window-host (Windows internal process)
    0	    20	 10836	       "C:\Users\ppmk6\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\4.0.37\x86_64-pc-windows-gnu\WD-TabNine.exe" --client vscode --client-metadata clientVersion=1.63.2 pluginVersion=3.5.11 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 "vscode-theme-name=One Dark Pro Flat" vscode-theme-kind=Dark vscode-machine-id=5f3af79e63968d882e5d756cbc22024853f7fa698a53dbb851ba3cda46bb7c7e vscode-is-new-app-install=false vscode-session-id=609977f5-90f4-4a5c-8763-abf1ac5ede591640606465797 vscode-language=en "vscode-app-name=Visual Studio Code" vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=0
    0	   108	 15196	       "c:\Users\ppmk6\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\4.0.37\x86_64-pc-windows-gnu\TabNine.exe" --client=vscode --no-lsp=true --client-metadata clientVersion=1.63.2 pluginVersion=3.5.11 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 "vscode-theme-name=One Dark Pro Flat" vscode-theme-kind=Dark vscode-machine-id=5f3af79e63968d882e5d756cbc22024853f7fa698a53dbb851ba3cda46bb7c7e vscode-is-new-app-install=false vscode-session-id=609977f5-90f4-4a5c-8763-abf1ac5ede591640606465797 vscode-language=en "vscode-app-name=Visual Studio Code" vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=0 --no_bootstrap
    0	   561	  6164	         "c:\Users\ppmk6\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\4.0.37\x86_64-pc-windows-gnu\TabNine-deep-local.exe" --settings C:\Users\ppmk6\AppData\Roaming\TabNine\local.settingsSmall --settings-version 1 --client vscode --client-metadata clientVersion=1.63.2 pluginVersion=3.5.11 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 "vscode-theme-name=One Dark Pro Flat" vscode-theme-kind=Dark vscode-machine-id=5f3af79e63968d882e5d756cbc22024853f7fa698a53dbb851ba3cda46bb7c7e vscode-is-new-app-install=false vscode-session-id=609977f5-90f4-4a5c-8763-abf1ac5ede591640606465797 vscode-language=en "vscode-app-name=Visual Studio Code" vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=0
    0	    58	 14472	     "E:\PROGRAMME FILES\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\ppmk6\.vscode\extensions\mkaufman.htmlhint-0.10.0\node_modules\vscode-languageclient\lib\utils\electronForkStart c:\Users\ppmk6\.vscode\extensions\mkaufman.htmlhint-0.10.0\server\server.js --node-ipc --clientProcessId=5352
    0	    94	 14944	     "E:\PROGRAMME FILES\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "e:\PROGRAMME FILES\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=5352
    0	    63	 16660	     "E:\PROGRAMME FILES\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "e:\PROGRAMME FILES\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=5352
    0	    47	 16696	     "E:\PROGRAMME FILES\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\ppmk6\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js --node-ipc --clientProcessId=5352
    0	   200	  6148	   window (● js(assingment).html - Untitled (Workspace) - Visual Studio Code [Administrator])
    0	    25	  9508	   crashpad-handler
    0	    38	 15308	   utility-network-service
    5	   102	 15412	   shared-process
    0	    79	  2684	     watcherServiceParcelSharedProcess
    0	    67	 16472	     ptyHost
    0	    74	  2408	       "C:\Program Files\PowerShell\7\pwsh.exe"
    0	     6	 10436	       console-window-host (Windows internal process)
    0	     6	 14280	       console-window-host (Windows internal process)
    0	    74	 15240	       "C:\Program Files\PowerShell\7\pwsh.exe"
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● js(assingment).html - Untitled (Workspace) - Visual Studio Code [Administrator])
|    Folder (Web Scrapping): 11 files
|      File types: pdf(4) cpp(2) exe(2) py(1) txt(1)
|      Conf files:
|    Folder (Machine Learning): 26 files
|      File types: ipynb(9) csv(5) xml(4) gitignore(1) iml(1) pkl(1)
|      Conf files:
|    Folder (GIT): 107 files
|      File types: py(43) png(14) pdf(11) svg(10) tex(4) yaml(2) gitignore(2)
|                  txt(2) html(1) cfg(1)
|      Conf files: makefile(3)
|    Folder (HTML & CSS): 42 files
|      File types: html(9) js(7) pdf(3) css(3) png(2) txt(1) jpg(1) mp4(1)
|      Conf files:
|    Folder (Data Structure & Algorithms): 111 files
|      File types: cpp(58) pdf(14) exe(12) png(6) zip(2)
|      Conf files:
|    Folder (Full Stack Developement): 79 files
|      File types: html(37) css(11) jpg(7) zip(3) js(1) png(1)
|      Conf files:
|    Folder (C++): 224 files
|      File types: cpp(150) exe(37) json(8) txt(3) py(1)
|      Conf files: launch.json(2) settings.json(2) tasks.json(1)
|      Launch Configs: cppvsdbg
|    Folder (Python): 7328 files
|      File types: py(2979) pyc(2450) pyd(167) mat(109) txt(99) gz(83) sav(47)
|                  pxd(46) exe(42) c(40)
|      Conf files: launch.json(1) settings.json(1) makefile(1);
```

</details>
<details><summary>Extensions (82)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.2
cpp-helper|ami|0.3.0
html-class-suggestions|And|1.1.1
vs-code-css-comments|ash|1.0.5
code-gnu-global|aus|0.2.2
vscode-database|baj|2.2.3
vscode-django|bat|1.8.0
vscode-custom-css|be5|6.0.2
pythoncpp-debug|ben|0.2.15
vscode-pytest|Cam|0.1.1
emmet-jss|car|1.0.0
doxdocgen|csc|1.3.2
vscode-database-client2|cwe|4.3.6
c-cpp-compile-run|dan|1.0.15
vscode-markdownlint|Dav|0.45.0
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|9.0.0
code-runner|for|0.11.6
c-cpp-runner|fra|2.1.1
pythonsnippets|frh|1.0.2
html-snippets|gey|0.2.3
vscode-pull-request-github|Git|0.34.2
CppSnippets|har|0.0.15
live-html-previewer|hdg|0.3.0
path-autocomplete|ion|1.18.0
css-snippets|joy|1.0.2
vsc-python-indent|Kev|1.14.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
MagicPython|mag|1.1.0
css-inline-comment|Mat|1.0.3
python-path|mge|0.0.11
formate|Mik|1.2.1
HTMLHint|mka|0.10.0
vscode-html-format|moh|0.0.4
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.17
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2021.12.1559732655
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
cpptools|ms-|1.8.0-insiders2
cpptools-extension-pack|ms-|1.1.0
powershell|ms-|2021.12.0
vsliveshare|ms-|1.0.5200
vsliveshare-audio|ms-|0.1.91
sqltools|mtx|0.23.0
doma-sql-formatter|nag|0.0.13
live-server-preview|neg|0.1.4
vscode-css-peek|pra|4.2.0
csssnippet|Pri|1.0.4
java|red|1.2.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.6.1
py-snippets|RTG|1.0.1
html5-boilerplate|sid|1.1.1
vscode-hexdump|sle|1.8.1
css-auto-prefix|spo|0.1.7
tabnine-vscode|Tab|3.5.11
html-preview-vscode|tht|0.2.5
python|tht|0.2.3
pygame-snippets|tus|0.0.1
vscode-lldb|vad|1.6.10
highlight-matching-tag|vin|0.10.1
intellicode-api-usage-examples|Vis|0.0.6
vscodeintellicode|Vis|1.2.15
vscodeintellicode-insiders|Vis|1.1.5
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0
js-runner|Zol|3.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710cf:30416617
vscexrecpromp3t3:30407764

```

</details>

**Comment by gjsjohnmurray** [comment]
Surely within Javascript you should be using /* to start a multiline comment block and */ to end it, no?

**Comment by pratham-ops** [comment]
> Surely within Javascript you should be using /* to start a multiline comment block and */ to end it, no?

Is there any way to use Keyboard shortcut , since every time i uses ctrl+/ it automatically wraps text to <-- and not // . This happens in script tag only , whereas there is no such issue when using external .js file

**Comment by ArturoDent** [comment]
This should work ou tof the box, but is frequently reported that extensions mess it up: see https://stackoverflow.com/questions/44858100/visual-studio-code-html-wrong-comment-type/59131077#59131077

Did you try it with all extensions disabled?

**Comment by pratham-ops** [comment]
> This should work out of the box, but is frequently reported that extensions mess it up: see https://stackoverflow.com/questions/44858100/visual-studio-code-html-wrong-comment-type/59131077#59131077
> 
> Did you try it with all extensions disabled?

Thank you Sir , got it maybe it was because of some faulty extension
