### ISSUE TITLE
Issue with Run Selection (F8)

### ISSUE THREAD

**Issue by hhazeley** [microsoft/vscode#139977]
Issue Type: <b>Bug</b>

If i use the Run Selection button or F8 system get a weird behavior, seems to but the break before the command is ran rather than after.  This issue only happening on Insider version of VS Code.

The 'Run Selected Text' works fine. Not sure if it is system or application configuration issue, moving to regular VS Code as this is critical feature.

https://ufile.io/f70wyxyh

VS Code version: Code - Insiders 1.64.0-insider (7b9e5c32a053669d4e72f998e4fa217090c32f59, 2021-12-22T05:15:28.225Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (1.61GB free)|
|Process Argv|--crash-reporter-id 99fbcfbe-38f1-4f32-ab6d-15aaf52f2ecc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.60
armview|ben|0.4.5
terminal|for|0.0.10
azure-pipelines|ms-|1.195.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2022.1.1001614873
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-wsl|ms-|0.63.13
azure-account|ms-|0.9.11
powershell-preview|ms-|2021.12.0
spellchecker|swy|1.3.0
armviz|yte|0.0.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
vscop804:30404766
vscop453:30404998
vsclayoutctrc:30405799
py55gd98:30408621
vscexrecpromp3t1:30407758
azactmsalcf:30409288

```

</details>

**Comment by weinand** [comment]
What language are you trying to run?

**Comment by hhazeley** [comment]
Language is Powershell
