### ISSUE TITLE
freeze on scrolling a lot of tests

### ISSUE THREAD

**Issue by zztalker** [microsoft/vscode#139952]
VSCode freeze on mouse wheel scrolling with lot of tests:

```python
import pytest


@pytest.mark.parametrize("a", [1, 2])
@pytest.mark.parametrize("b", [1, 2, 3])
@pytest.mark.parametrize("c", ["a", "b"])
@pytest.mark.parametrize("d", [True, False])
@pytest.mark.parametrize("e", [True, False])
@pytest.mark.parametrize("f", [True, False])
@pytest.mark.parametrize("g", [True, False])
@pytest.mark.parametrize("h", ["A", "B"])
def test_create_commands(a, b, c, d, e, f, g, h):
    pass
```
open test explorer, 
![image](https://user-images.githubusercontent.com/1027857/147802427-b0b68194-6b8d-4a13-88ee-2fc742f3311b.png)

right-click on the test button
scroll tests with mouse wheel at least twice

[Performance profile](https://drive.google.com/file/d/1e3suweaSS5x4tKAMxKjotTymqkUZqvmf/view?usp=sharing)

VS Code version: Code - Insiders 1.64.0-insider (7b9e5c32a053669d4e72f998e4fa217090c32f59, 2021-12-22T05:15:27.690Z)
OS version: Linux x64 5.4.0-92-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2405)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|11.58GB (0.79GB free)|
|Process Argv|--unity-launch --crash-reporter-id d1dc4fc0-87bd-4ba9-b632-a18a280ca837|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
gitlens-insiders|eam|2021.12.2804
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
themeswitch|Foo|1.0.5
rpm-spec|Lau|0.3.2
vscode-docker|ms-|1.18.0
python|ms-|2022.0.1612153341-dev
vscode-pylance|ms-|2021.12.3-pre.1
jupyter|ms-|2022.1.1001614873
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
code-stats-vscode|riu|1.0.18
code-spell-checker|str|2.0.14
code-spell-checker-russian|str|2.0.2
cron-explained|tum|1.3.1
material-theme|zhu|3.13.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstes627:30244334
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
vscop804:30404766
vs360cf:30404996
vsclayoutctrt:30405800
py55gd98cf:30408622
vscexrecpromp3t2:30407759
azactmsal:30409287

```

</details>

**Comment by zztalker** [comment]
Looks like [#136237](https://github.com/microsoft/vscode/issues/136237) doesn't help.

**Comment by connor4312** [comment]
Thanks (again) for the issue!
