### ISSUE TITLE
Space in search matches erroneous characters

### ISSUE THREAD

**Issue by alanondra** [microsoft/vscode#139973]
Issue Type: <b>Bug</b>

**Steps to reproduce:**
1. Use the Search feature on any directory with files with indented text (for example, the config directory of a Laravel project)
2. In the Search field, press Ctrl + Enter to enter a newline
3. Follow it with a space character

**Expected results:**
Match only literal newlines and a single space after them.

**Actual results:**
Matches newlines and random chunks of other characters
In this [screenshot](https://i.imgur.com/z3lLLtX.png) I'm searching for newline + space, and replacing with newline + space. It should be evident something is wrong

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.95GB (26.80GB free)|
|Process Argv|C:\\Users\\alan\\Workspace\\PHP\\DRP --crash-reporter-id 80e6fae8-24ee-431f-a928-19dd3aa07694|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (80)</summary>

Extension|Author (truncated)|Version
---|---|---
monogame-pipeline-vscode|abc|0.0.3
doge|Ado|1.2.1
vscode-nginx-conf|ahm|0.1.3
laravel-blade-vscode|ami|2.0.3
ng-template|Ang|13.1.0
vscode-twig-pack|baj|1.1.0
vscode-intelephense-client|bme|1.8.0
vscode-tailwindcss|bra|0.7.4
gitignore|cod|0.7.0
doxdocgen|csc|1.3.2
vscode-mysql-client2|cwe|4.4.0
vscode-eslint|dba|2.2.2
conan|dis|0.7.1
vscode-html-css|ecm|1.10.2
php-debug|fel|1.22.0
conan-tools|Fir|0.1.1
auto-rename-tag|for|0.1.9
vscode-pull-request-github|Git|0.34.2
better-cpp-syntax|jef|1.15.10
vscode-nuget-package-manager|jmr|1.1.6
php-cs-fixer|jun|0.2.10
docomment|k--|0.1.30
edge|luo|0.3.2
zscript|mek|1.0.5
dotenv|mik|1.0.1
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.17
data-workspace-vscode|ms-|0.1.0
mssql|ms-|1.12.0
sql-database-projects-vscode|ms-|0.14.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
github-browser|ms-|0.0.15
hexeditor|ms-|1.8.2
mono-debug|ms-|0.16.2
powershell|ms-|2021.12.0
vscode-github-issue-notebooks|ms-|0.0.113
vscode-typescript-next|ms-|4.6.20211230
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.5200
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
php-docblocker|nei|2.6.1
vetur|oct|0.35.0
vscode-versionlens|pfl|1.0.9
vscode-spring-boot|Piv|1.29.0
java|red|1.2.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.2
vscode-yaml|red|1.2.2
adonis-js-goto-controller|ste|0.0.5
adonis-js-goto-view|ste|0.0.2
vscode-make|tec|1.0.2
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.8.0
vscode-icons|vsc|11.8.0
twig|wha|1.0.2
eno|Wsc|2.3.53
markdown-all-in-one|yzh|3.4.0
makefile-creator|zen|0.0.3
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30416617
vscexrecpromp3c:30407761

```

</details>

**Comment by roblourens** [comment]
I can repro (in our repo, shows up in the file `src/vs/base/common/marked/marked.js` and others).

I am pretty sure it shares a root cause with https://github.com/microsoft/vscode/issues/131507 which has the upstream issue https://github.com/BurntSushi/ripgrep/issues/1983. Since I haven't heard a response upstream, I will try to work around it on our end. Closing as dupe of #131507
