### ISSUE TITLE
please add fetures typescript types in vscode extension, like in monacoEditor

### ISSUE THREAD

**Issue by xiaobindebingo** [microsoft/vscode#139923]
please Add typescript types lib for code hint in vscode extension, I hope to invoke **addExtraLib**  method  in vscode extension;   like monaco editor: 
```
monaco.languages.typescript.typescriptDefaults.addExtraLib()
```
detail: https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults

**Comment by xiaobindebingo** [comment]
I have add more info in this issue，please help me

**Comment by xiaobindebingo** [comment]
I want to give a .js file with d.ts file accroding to vscode extension

**Comment by mjbvz** [comment]
What is the use case for this though? Please explain what you are trying to achieve first

**Comment by xiaobindebingo** [comment]
when the user use my extension;  he can get  **code hint** by  **.d.ts file** which is in the extension

**Comment by mjbvz** [comment]
Please describe the use case in more detail. For example, what is the d.ts file for?

**Comment by xiaobindebingo** [comment]
![image](https://user-images.githubusercontent.com/33923136/148478484-8386a387-29f8-408b-808e-86b9dcfd2c41.png)  目的
monaco editor has  api **addExtraLib** to achieve the objective， but I cannot found in vscode

**Comment by mjbvz** [comment]
You're jumping right to a solution. First, what is the problem?  Once we understand that, we can see if which  solution make sense

**Comment by xiaobindebingo** [comment]
> You're jumping right to a solution. First, what is the problem? Once we understand that, we can see if which solution make sense

![image](https://user-images.githubusercontent.com/33923136/148479125-f1aa2dcb-987e-4594-8e3b-ab6c06223f90.png)
For Example like above picture,  the .js file only have **wx.**code; it can get a code hint according .d.ts; how can I get this  performance in vscode

**Comment by mjbvz** [comment]
For what purpose though? Please describe the end to end experience you are trying to create, what doesn't work today, and what alternatives you have considered

**Comment by xiaobindebingo** [comment]
I have consider use `/// <reference path="node_modules/name.d.ts" /> `; but
 I think it is not good experience
