### ISSUE TITLE
When a breakpoint is hit, the caret (cursor) should move to that line

### ISSUE THREAD

**Issue by pisoni-onshape** [microsoft/vscode#139950]
Issue Type: <b>Bug</b>

Currently, there is a minor problem with at least Javascript/Typescript debugging in VS Code on macOS. When you hit a breakpoint while running the web application, the caret (cursor) doesn't move to that line automatically like it does in Visual Studio (the bigger cousin). In fact, it's seen nowhere in the Editor Window, and trying to move with arrow keys won't work. I'm not even sure if the Editor Window is in focus at that point at all or not. We have to click on the line to focus on the line with the breakpoint. One problem with not doing it for example is if we want to quickly disable or delete that breakpoint with the keyboard (in case it's hitting too frequently), it won't work as the cursor is not on the line at that point. 

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|32.00GB (10.21GB free)|
|Process Argv|--crash-reporter-id 71ea9e01-a319-4ace-a2ba-6f58c4d27d45|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-select|chu|2.0.2
glsl-canvas|cir|0.2.14
vscode-mac-color-picker|dae|1.0.2
vscode-quick-select|dba|0.2.9
gitlens|eam|11.7.0
clipboard-manager|Edg|1.4.2
glsl-snippets|j0h|0.0.1
tws|jki|1.0.1
render-crlf|med|1.5.21
jscs-formatter|moo|0.1.1
vscode-glsl-linter|mrj|1.2.0
cpptools|ms-|1.7.1
vscode-typescript-next|ms-|4.6.20211229
vetur|oct|0.35.0
shader|sle|1.1.5
vscode-lldb|vad|1.6.10
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-maven|vsc|0.34.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710:30416614
vscexrecpromp3t1:30407762

```

</details>

**Comment by weinand** [comment]
@roblourens it seems that the editor does not get focus when hitting a breakpoint.

**Comment by roblourens** [comment]
We don't move DOM focus or the cursor when hitting a breakpoint. I have also been annoyed by this and want to implement it with a setting, but I'm not sure what the default should be. I'd be worried about messing up workflows where people are editing or doing other things at the same time as debugging.

I guess currently we open the file and reveal the debug viewlet, so that's sort of disruptive already, it seems fine to also focus the editor and move the cursor, with a setting to disable.

**Comment by weinand** [comment]
@roblourens Yes, I agree with your assessment: focus the editor and move the cursor should be the default.

For the setting I suggest to expand the existing setting "Debug: Focus Window on Break" instead of introducing a new setting:
<img width="592" alt="CleanShot 2022-01-04 at 11 23 44@2x" src="https://user-images.githubusercontent.com/1898161/148044921-682fb6ab-c97f-4e9f-9135-e9847e65cd1f.png">

"Debug: Focus On Break Behavior"
- Focus Window
- Focus Editor
- Focus Editor and Move Cursor (default)

**Comment by JeroenBos** [comment]
I think this is a regression compared to 1.62. After reinstalling 1.62.2 and hitting a breakpoint, the editor has focus, and arrow keys work, whereas on 1.63 they do not.

**Comment by roblourens** [comment]
Are you sure? I don't see that behavior and don't see how it would have worked before

**Comment by JeroenBos** [comment]
@roblourens  I investigated a bit more. I realize I did not fully describe in my previous comment what I did. Now I noticed I mindlessly threw in an <kbd>Esc</kbd> press without noticing.

There is definitely _some_ regression from 1.62 to 1.63, although it's hard for me to pinpoint what exactly. 
I see behavioral differences if the following sequence is executed:
- hit a breakpoint
- press <kbd>Esc</kbd>. 
- press <kbd>Right Arrow</kbd> key. 

I both 1.62 and 1.63 I see the caret appear at the beginning of the line after pressing <kbd>Esc</kbd>, however, in 1.62 the caret responds to <kbd>Right Arrow</kbd> whereas in 1.63 it does not.

Some notes:
- I debug in Python, but I suspect that it's regardless of in which language the breakpoint is hit
- I have no User keybindings associated with the <kbd>Esc</kbd> or <kbd>Right Arrow</kbd>; only the default.
- I now realize that this is not exactly the same issue as described by OP, although related. Sorry for confounding.

### Workaround
I can mention a workaround, though:
After hitting a breakpoint, press <kbd>Esc</kbd> to move the caret to that line.

**Comment by roblourens** [comment]
I'm not sure what Esc is doing here - it probably depends on where focus started, or some other condition. In any case I plan to fix it by forcing focus to go to the right place

**Comment by roblourens** [comment]
Adding this with a new setting. Not building on the "focus window" setting because I think this is totally independent from focusing the window. I would have options for "focus window but not editor" and "focus editor but not window" and the other combinations.

**Comment by weinand** [comment]
@roblourens yeah, having a new settings seems to be more appropriate.

**Comment by rzhao271** [comment]
I'm currently seeing the opposite problem on Windows 10 where even with the new setting set to false, I get the following behaviour:

1. Start debugging a single JS file with many breakpoints.
2. The debugger should hit the first endpoint.
3. Navigate to another editor.
4. Press the play button to continue debugging the program.
5. :bug: The focus switches back to the next breakpoint even though I set `debug.focusEditorOnBreak` to be false.

**Comment by roblourens** [comment]
We have always revealed the editor where you paused. But previously we didn't focus the editor. I don't plan to change revealing the editor, I think that makes sense, you should know that you paused.

**Comment by rzhao271** [comment]
I see the difference now. LGTM!
