### ISSUE TITLE
.vscode-server-insiders/bin/*/extensions/ms-vscode.js-debug/src/chromehash_bg.wasm have mtime 1985-10-26 04:15:00

### ISSUE THREAD

**Issue by ShadSterling** [microsoft/vscode#139949]
Sorry if this is not the right place to report this, it wasn't clear to me where to report problems with remote or insiders, much less both

Does this issue occur when all extensions are disabled?: Yes/No

This occurs when extensions are installed on the remote server (at least when it's OpenSuse Linux) when using the Remote - SSH extension in Code - Insiders

- VS Code Version: 1.63.0-insider
- OS Version: macOS 11.6
- Remote Host OS: OpenSuse Tumbleweed 20211228

Steps to Reproduce:

1. Have an idiosyncratic maintenance script that warns about absurdly old files in your home directory (on or sync'd with the remote host)
2. Get warnings about .vscode-server-insiders/bin/*/extensions/ms-vscode.js-debug/src/chromehash_bg.wasm having mtime 1985-10-26 04:15:00

**Comment by ShadSterling** [comment]
How does bumping the version of [@c4312/chromehash](https://github.com/connor4312/chromehash) address this?

**Comment by connor4312** [comment]
That's where `chromehash_bg.wasm` comes from

**Comment by ShadSterling** [comment]
Sure, I'm just not seeing a change there that looks relevant to this
