### ISSUE TITLE
[TS] coloring broken

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#13991]
![image](https://cloud.githubusercontent.com/assets/900690/19515067/474223e8-95f6-11e6-9eaa-c5caf4b2b8e5.png)

Starting from https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/openEditorsView.ts#L170

**Comment by aeschli** [comment]
This seems to be fixed with the latest update (also in 1.7)
