### ISSUE TITLE
Despite disabling JSDoc autocompletion, VSCode still completes doc comments.

### ISSUE THREAD

**Issue by JetForMe** [microsoft/vscode#139983]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: macOS 12.1

Steps to Reproduce:

I've looked at https://github.com/Microsoft/vscode/issues/23642

I've disabled all the autocomplete and JSDoc features I could find, particularly `JavaScript > Suggest: Complete JSDocs` in all Settings scopes, and re-launched VSCode, but it still inserts the closing `*/` and prefixes each line with an asterisk whenever I type `/**`. Note that it does not pop up a menu of possible completions, it just immediately inserts the closing delimiter when I type the second asterisk.

*Edit:* I was able to turn off an Auto Closing Brackets, and that seemed to fix the automatic close, but it still adds a leading `*` on every new line inside a doc comment block.

**Comment by Lemmingh** [comment]
The behavior you described is declared in the language configuration.

https://github.com/microsoft/vscode/blob/7b9e5c32a053669d4e72f998e4fa217090c32f59/extensions/javascript/javascript-language-configuration.json#L19

https://github.com/microsoft/vscode/blob/7b9e5c32a053669d4e72f998e4fa217090c32f59/extensions/typescript-language-features/src/languageFeatures/languageConfiguration.ts#L23-L38

**Comment by JetForMe** [comment]
I'm not sure I understand. I can see that you show me where the actions are defined, but how do I disable the action? Do I have to try to edit those files? How would I even do that? Where do they live? Is their mere presence or absence the only way to enable or disable this behavior?

**Comment by mjbvz** [comment]
That setting only controls filling in JSDoc templates (i.e. `@param ...`)

As @Lemmingh notes, closing comments is controlled by the on enter rules defined for a language. As far as I know you can't disable these with a setting, but @rebornix  can confirm that
