### ISSUE TITLE
vscode icon in windows 11 taskbar does not show correctly

### ISSUE THREAD

**Issue by sinapis** [microsoft/vscode#139957]
Issue Type: <b>Bug</b>

Icon in taskbar is gone. it reverted to default windows icon shorty after installation. here is a screenshot:
![image](https://user-images.githubusercontent.com/15230040/147807756-200d78b3-a646-40a2-b34c-1fdf53496d80.png)

this happened across multiple of my windows machines. including a brand new machine that i installed from scratch.
i followed each of the answers in this thread: https://stackoverflow.com/questions/63087606/vscode-icon-in-task-bar-is-blank

none of them worked for me except the accepted answer, and even that only for a few hours until the issue came back.

i also tried running vscode without extensions: code --disable-extensions
it didn't help either.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900K (24 x 3187)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.78GB (49.61GB free)|
|Process Argv|--crash-reporter-id 271396ae-2a55-47b7-ace0-ae533958d642|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
TabOut|alb|0.2.1
better-toml|bun|0.3.2
path-intellisense|chr|2.6.0
githistory|don|0.6.19
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
vscode-vibrancy|eyh|1.0.16
vscode-pull-request-github|Git|0.34.2
vscode-test-explorer|hbe|2.21.1
debug-visualizer|hed|2.2.4
rest-client|hum|0.24.6
output-colorizer|IBM|0.1.2
git-graph|mhu|1.30.0
azure-pipelines|ms-|1.195.0
vscode-docker|ms-|1.18.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.11
hexeditor|ms-|1.8.2
powershell|ms-|2021.12.0
test-adapter-converter|ms-|0.1.5
vsliveshare|ms-|1.0.5200
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
docthis|oou|0.8.2
vscode-css-peek|pra|4.2.0
prisma|Pri|3.7.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.2
vscode-coverage-gutters|rya|2.8.2
fish-vscode|sky|0.2.1
code-spell-checker|str|2.0.14
svelte-vscode|sve|105.8.0
highlight-matching-tag|vin|0.10.1
vscodeintellicode|Vis|1.2.15
vscode-icons|vsc|11.8.0
vscode-import-cost|wix|2.15.0
material-theme|zhu|3.13.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710:30416614
vscexrecpromp3c:30407761

```

</details>

**Comment by joaomoreno** [comment]
This is a Windows issue, not VS Code, unfortunately.

**Comment by sinapis** [comment]
@joaomoreno can you please provide me with more info about this windows issue? Is it a known issue? Can I follow it somewhere like I follow issues in vscode via github? Are there workarounds?

**Comment by sinapis** [comment]
Are you sure this is a Windows issue? I don’t see it happening to other programs. Only vscode.

**Comment by joaomoreno** [comment]
Unfortunately I don't know more than what I read in that StackOverflow post.

Have you tried both setups (system and user)? What path exactly does the shortcut point to? Does that location have an icon?

**Comment by sinapis** [comment]
icon points here
C:\Users\user\AppData\Local\Programs\Microsoft VS Code\Code.exe

seems like it has an icon. is this the way to test it?
![image](https://user-images.githubusercontent.com/15230040/148044261-1a648f71-380e-4a24-942f-a459ec1a9010.png)


I didn't try both setups
