### ISSUE TITLE
Pinned files should remain open.

### ISSUE THREAD

**Issue by AdhTri001** [microsoft/vscode#139912]
I would love to have a feature where we pinned a document and it should remain opened even if it's deleted or go corrupted (Maybe showing cached version or a message "The view will be refreshed as file reappears."?) Like currently I use **vscode-pdf** extension with **texlab** extension to make documents. When I hit save, latexmk rebuilds the file, and I usually have the pdf view open in left. Whenever there is an error, The pdf gets deleted in some cases and I have to relocate the file. If I could pin it and be relaxed about not relocating and reopening the pdf viewer again and again? I know about about Latex-Workshop though I am happy with what texlab and vscode-pdf provides me.

![image](https://user-images.githubusercontent.com/84070263/147739292-49c0395c-d028-49ed-ac0c-d0873375f2d8.png)

Here is my setup for latex if I wasn't clear with my explination.

If this feature can't be possible, its totally understandable. Thanks vsc-team!

**Comment by bpasero** [comment]
We keep text editors open even when the editor gets deleted and it was opened before, but this seems to be about custom editors, is that true?

**Comment by AdhTri001** [comment]
Yeah files does remain open, this issue should rather be transferred to the vscode-pdf extension repository because it doesn't work with pdf view. Sorry I didn't know that this was already a feature. Thanks again!

If authorities would like to, they can close this issue :)
