### ISSUE TITLE
VSCode is slow AF

### ISSUE THREAD

**Issue by DivyanshIsSoCoolDude** [microsoft/vscode#139999]
Ok, this thing is SLOW, I can't do a single thing with it
Someone pls help
Clearing Cache didn't help
PC Specs
i3, 4GB RAM, 1TB HDD
It should work but it isn't
HELP

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

Also see https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by tanhakabir** [comment]
Thanks @gjsjohnmurray! Yes we need much more information the figure out what the issue is
