### ISSUE TITLE
Meaning of green warning in settings.json is not discoverable

### ISSUE THREAD

**Issue by richardcox13** [Microsoft/vscode#13995]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: alefragnani.Bookmarks-0.9.2, ms-vscode.csharp-1.4.1, ms-vscode.PowerShell-0.7.2

Steps to Reproduce:
1. Create settings as shown below
2. Wonder what the green underlining means

Once spotted (its a duplicate) it is obvious, but until then nothing indicates its meaning.

Suggest: tooltip when hovering over marked setting should also state the reason for the warning.

![untitled](https://cloud.githubusercontent.com/assets/4578827/19518285/32d9fc7a-95fe-11e6-9030-471b590858d4.png)

**Comment by roblourens** [comment]
If you hover over it, there should be a message about it being a duplicate. Do you not see that?

**Comment by richardcox13** [comment]
No I didn't.

But checking on another install…

**Comment by roblourens** [comment]
Gotcha, I see it just as the first item in the list, not a 'title' so much.

**Comment by bgashler1** [comment]
I wonder if we should be hi-lighting both when there is a duplicate?  I also agree that there needs to be a tooltip explaining why there is a problem.

Also, it would be nice to have more lightbulb actions that can propose fixes to situations like this "Remove this duplicate instance" or "Highlight all duplicates."

**Comment by richardcox13** [comment]
@bgashler1 : Should get a +1 for each of those ideas.

**Comment by bgashler1** [comment]
@jrieken not sure if this is your territory, but it seemed you were working on lightbulbs perviously.

**Comment by aeschli** [comment]
@bgashler1 Good suggestions. Please file separate issues... 
Closing this one as there is a hover explaining the error. 
![image](https://cloud.githubusercontent.com/assets/6461412/21742632/4ea60156-d4c9-11e6-9f10-dcebe5a3d0e9.png)

To me, the hover is clear and not sure what to improve. If your scenario shows a confusing hover, please attach the screenshot.
