### ISSUE TITLE
Support context menu on breadcrumb items.

### ISSUE THREAD

**Issue by sandipchitale** [microsoft/vscode#139975]
I love the breadcrumbs feature. The breadcrumbs is a great hierarchical context. It will be great to have a context menu on breadcrumb items. The commands should get the full breadcrumbs items and the contextual breadcrumb item passed in.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"breadcrumbs"
