### ISSUE TITLE
Scope inspector bug when extending C++ syntax highlighting through Textmate grammar

### ISSUE THREAD

**Issue by felipejinli** [microsoft/vscode#139996]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: Darwin x64 21.1.0
repo: https://github.com/felipejinli/vscode-hide-logs
Steps to Reproduce:

1. created a vscode extension
2. contributed to C++ grammar by writing the following Textmate grammar file (see snippet 1) and setting the extension's `package.json` to contribute correctly (see snippet 2)
3. built the extension and ran it on Extension Development Mode
4. used Inspect Editor Scopes tool to check a token that matches to a custom defined Regex within my extended Textmate grammar file
5. PROBLEM: inspector doesn't show my custom textmate scope 

Snippet 1) 
```
{
	"scopeName": "source.cpp.debug",
	"fileTypes": [
		"cpp",
		"c++",
		"c"
	],
	"patterns": [
		{
			"include": "#expression"
		}
	],
	"repository": {
		"expression": {
			"patterns": [
				{
					"include": "#clog-db"
				},
				{
					"include": "#indent-DB"
				},
				{
					"include": "#array-db"
				},
				{
					"include": "#sample"
				}
			]
		},
		"clog-db": {
			"begin": "^\\s*clog",
			"end": "<<[^;]+;",
			"name": "cpdebug.clog"
		},
		"indent-DB": {
			"match": "^\\s*DB\\(\\);",
			"name": "cpdebug.indentdb"
		},
		"array-db": {
			"match": "^\\s*dba(2)?\\([^;]+\\);",
			"name": "cpdebug.arraydb"
		},
		"sample": {
			"match": "clog",
			"name": "cpdebug.sample"
		}
	}
}
```
Snippet 2:
```
	"contributes": {
			"grammars": [
				{
					"scopeName": "source.cpp.debug",
					"path": "./syntaxes/cpp.tmGrammar.json",
					"injectTo": [
						"source.cpp"
					]
				}
			]
		},
```

![image](https://user-images.githubusercontent.com/42386776/147862739-5ef8d900-8db7-4c9d-9e8f-988ced840165.png)

**Comment by aeschli** [comment]
My guess is that you are missing the `injectionSelector`.
See the [injection grammars doc](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#injection-grammars) for an example.
