### ISSUE TITLE
Incorrect Errors raised in scripts when using "Replace in Files" or Ctrl+Shift+H

### ISSUE THREAD

**Issue by Cyb3r4rch3r** [microsoft/vscode#139930]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.63.2
- OS Version: Windows_NT x64 10.0.22000
- Installed Extensions: 
                 Jupyter
                 Jupyter Keymap
                 Jupyter Notebook Renderers
                 PowerShell
                 Pylance
                 Python

Steps to Reproduce:

1. Replace string in multiple files (I replaced a string in 86 scripts)
2. Open any script and the Problems tab highlights non-existent errors (eg "Unexpected token" at a line that has no tokens, and simply performing a cut and paste of the same exact line resolves it). Errors found in lines that do not exist (see image).

Currently, completely exiting the application and ending the task will resolve the issue until a replace is performed again.

![VSCode Error](https://user-images.githubusercontent.com/6243762/147763504-013d0832-a915-4bf0-ad05-32ef14763c63.png)

**Comment by roblourens** [comment]
This would probably be an issue with the powershell extension
