### ISSUE TITLE
Respect the `editor.scrollbar` options in all areas of the workbench

### ISSUE THREAD

**Issue by yecril71pl** [microsoft/vscode#139922]
Issue Type: <b>Bug</b>

Button 1 press in the scroll bar results in the window pane scrolling to the absolute position of the pointer.  This makes it very hard to scroll to the right place when the window is short and the content is long, such as when viewing a debug log.
Filtering in the debug log is not a workaround because it does not show the context of an event; in order to see the context, you have to remove the filter, but then the interesting event disappears.
Not to mention the absence of scroll buttons, a nightmare feature devised by UX people to show us that we are stupid and they are smart and that everybody should just use the wheel.  *censored*

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.15.8-1-default
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 3, 3|
|Memory (System)|5.66GB (0.16GB free)|
|Process Argv|--unity-launch --crash-reporter-id 2a03cb52-9f4b-48bf-93d3-5c0537d534ee|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma5|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
vscode-resx-editor|Dom|0.0.5
vscode-pull-request-github|Git|0.34.2
Ionide-fsharp|Ion|5.10.2
better-cpp-syntax|jef|1.15.10
vscode-language-pack-pl|MS-|1.63.3
csharp|ms-|1.23.17
dotnet-interactive-vscode|ms-|1.0.2606010
vscode-dotnet-pack|ms-|1.0.4
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
powershell|ms-|2021.12.0
vscode-markdown-notebook|ms-|0.0.26
vsliveshare|ms-|1.0.5200
vsliveshare-audio|ms-|0.1.91
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710:30416614

```

</details>

**Comment by alexdima** [comment]
You can configure `"editor.scrollbar.scrollByPage": true`.

**Comment by yecril71pl** [comment]
> You can configure `"editor.scrollbar.scrollByPage": true`.

It does not affect scrolling in the log page at all.

**Comment by yecril71pl** [comment]
If this setting is meant to be universal, it should be taken out of the `editor` context.

**Comment by yecril71pl** [comment]
@alexdima it is not a feature request, it is a UX bug.

**Comment by gjsjohnmurray** [comment]
@yecril71pl are you watching #145788?
