### ISSUE TITLE
Output tab does not show cyrrilic symbols

### ISSUE THREAD

**Issue by tvardero** [microsoft/vscode#139985]
Issue Type: <b>Bug</b>

The only enabled extension is C# extension for VSCode.
System language is ru-RU.
VSCode interface language was both english and russian (russian language extension pack), issue happened on both.
Dotnet --version returns 6.0.101 .

Steps to reproduce:
1. Make any change in project to make omnisharp asking executing "dotnet restore" command. Deleting /obj folder and restarting omnisharp server might do the job.
2. Accept executing "dotnet restore" command from omnisharp pop-up.
3. In Output tab any cyrillic symbol is replaced with rombus with "?" symbol on it.

Other than output tab, everything is normal and shown correctly (in debug console tab, in problems, in integrated terminal).

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.50GB free)|
|Process Argv|--crash-reporter-id de6d76a4-5091-497f-b5c6-b5d71a3bc989|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710cf:30416617
vscexrecpromp3t1:30407762

```

</details>

**Comment by tvardero** [comment]
![image](https://user-images.githubusercontent.com/45442278/147853368-4484a36c-ba4f-46d5-a719-49bce2c7ae1f.png)

**Comment by sandy081** [comment]
It seems this output channel is owned by csharp extension, can you please first reach out to csharp extension and let them investigate first to see if they are doing something different. Otherwise, It would be great if you can provide a sample extension with source code to reproduce this. Thanks
