### ISSUE TITLE
Terminal compiling log text

### ISSUE THREAD

**Issue by OneMonkeyArmy** [microsoft/vscode#139993]
Issue Type: <b>Bug</b>

When resizing the main window of vscode while compiling, and returning to full screen when compiling is done, the terminal log text is unreadable, part are missing...

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.95GB (37.18GB free)|
|Process Argv|--crash-reporter-id 531d2115-ceaf-4549-94bd-16d079019a04|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by meganrogge** [comment]
pls attach a gif

**Comment by OneMonkeyArmy** [comment]
Since this, I  have updated my Windows 10 to the latest Windows 11, and this problem no longer exist.
