### ISSUE TITLE
无法通过ctrl+鼠标左键跳转到定义、无法语法报错

### ISSUE THREAD

**Issue by shawnzheng777** [microsoft/vscode#139901]
Issue Type: <b>Bug</b>

1、无法通过ctrl+鼠标左键跳转到函数定义或引入定义
2、未使用变量无报错

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:53:24.645Z)
OS version: Windows_NT ia32 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.72GB free)|
|Process Argv|--crash-reporter-id 9cf7328e-986a-4ba4-8fc3-6b19021cacb5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
cssrem|cip|2.6.0
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|3.1.1
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
vscode-language-pack-zh-hans|MS-|1.63.3
view-in-browser|qin|0.0.5
classlens|rex|0.7.1
px-to-rem|sai|1.3.1
open-in-browser|tec|2.0.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30416617

```

</details>

**Comment by smallp** [comment]
1、Cannot jump to definition through ctrl+clicking.
2、No warning for unused variable.

这种问题一般重启就能解决，没有错误信息很难排查。
