### ISSUE TITLE
Close other only editors

### ISSUE THREAD

**Issue by flippidippi** [microsoft/vscode#139948]
Currently `@command:workbench.action.closeOtherEditors` closes all editors AND terminals. It would be nice to either change `closeOtherEditors` to not close terminals or add a new command to only close editors.

**Comment by bpasero** [comment]
cc @Tyriar @meganrogge

**Comment by Tyriar** [comment]
If we decided to go this route I think it would need to be in editor land, for example an arg you could hook up to a keybinding to ignore certain editor types.

**Comment by Tyriar** [comment]
It's worth mentioning that once the tab model api ships https://github.com/microsoft/vscode/issues/133532 an extension would be able to make a command to do this pretty easily.
