### ISSUE TITLE
Cannot execute CodeLens command using the "Show CodeLens Commands For Current Line" command: "actual command NOT FOUND"

### ISSUE THREAD

**Issue by gnailuy** [microsoft/vscode#139910]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2 and 1.64.0-insider
- OS Version: Windows 10 Enterprise 21H2 Build 19044.1415

Initially I found this issue on the [Azure Stream Analytics extension](https://marketplace.visualstudio.com/items?itemName=ms-bigdatatools.vscode-asa), but I can also reproduce it on the [CodeLens Sample extension](https://github.com/microsoft/vscode-extension-samples/tree/main/codelens-sample) which I think should provide a simpler environment to debug.

Steps to Reproduce (Using the CodeLens Sample extension):

1. Clone the project source: https://github.com/microsoft/vscode-extension-samples
2. `cd` to the `codelens-sample` directory;
3. `npm install` then `vsce package`;
4. Install the generated extension package `codelens-sample-0.0.1.vsix`;
5. Open any file, the above extension provides CodeLens command "Codelens provided by sample extension" on every line;
6. On any line, use Ctrl+Shift+P, then "Show CodeLens Commands For Current Line";
7. Choose the CodeLens command then hit `Enter`;
8. VSCode will show the below pop-up windows on the left-bottom corner;

![image](https://user-images.githubusercontent.com/1468648/147735371-48f7c302-71e4-4b4b-a63c-bb27f1115176.png)

9. **If we try step 6 and 7 a few more times, it will work eventually**.

I see @jrieken resolved an issue #84153 which reported the same error message. So I also tried to debug this issue in the Developer Container. This issue is also related to the `CodeLensCache`, the cache key doesn't exist in the CodeLens cache. I'm not familiar with how the CodeLens cache works so the debug stuck here. Could you please help take a look? Thanks a lot. 

![image](https://user-images.githubusercontent.com/1468648/147735734-a3af6a9a-5711-49be-b9bb-eb3cc14c40b1.png)

**Comment by jrieken** [comment]
I can reproduce in insiders but not when running out of dev. This error happens when code lens results are being disposed and that usually happens after a model or config change (anything that re-requests code lenses).

**Comment by gnailuy** [comment]
Thank you so much for the quick fix. I've verified it works well in VSCode Insiders.
