### ISSUE TITLE
Meaning of Notebook > Markup: Font Size

### ISSUE THREAD

**Issue by DavidP2Z** [microsoft/vscode#139935]
Issue Type: <b>Bug</b>

I find it difficult to understand the meaning of the Notebook > Markup: Font Size setting. It's not clear how the sizing scheme works from the description. I read that 0 corresponds to 120% of the editor font size - but beyond that do the numbers mean point size? If so, what's the scheme for relative scaling of markdown headings etc.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (8.42GB free)|
|Process Argv|--crash-reporter-id a9c98a1c-f474-4ebb-9a4d-d2a82c17d6b6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
essential-data-science-pack|ana|1.0.2
preview-html|ana|1.0.0
preview-jp2|ana|0.0.4
preview-mp4|ana|0.0.1
preview-pdf|ana|1.0.0
preview-tiff|ana|1.0.1
snippets-geojson|ana|1.0.0
snippets-plotly|ana|1.0.3
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
vscode-azurevirtualmachines|ms-|0.4.1
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
azure-account|ms-|0.9.11
azurerm-vscode-tools|msa|0.15.5
vscode-sanddance|msr|3.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710cf:30416617
py55gd98cf:30411515
vscexrecpromp3c:30407761

```

</details>

**Comment by dimitry-ishenko** [comment]
@DavidP2Z see #141310 for headings
