### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by baraaalsharif** [microsoft/vscode#139995]
Issue Type: <b>Bug</b>

Aborting installation.
Unexpected error. Please report it as a bug:
Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:403:11)
    at Object.spawn (child_process.js:553:9)
    at spawn (C:\Users\baraa\AppData\Roaming\npm\node_modules\create-react-app\node_modules\cross-spawn\index.js:12:24)
    at C:\Users\baraa\AppData\Roaming\npm\node_modules\create-react-app\createReactApp.js:390:19
    at new Promise (<anonymous>)
    at install (C:\Users\baraa\AppData\Roaming\npm\node_modules\create-react-app\createReactApp.js:341:10)
    at C:\Users\baraa\AppData\Roaming\npm\node_modules\create-react-app\createReactApp.js:468:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}

Deleting generated file... package.json
Deleting my-app/ from C:\Users\baraa\OneDrive\Skrivbord\New folder
Done.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (3.90GB free)|
|Process Argv|--crash-reporter-id 9318559d-a497-43c9-bfd0-de07880bf7bf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
npm-intellisense|chr|1.4.0
githistory|don|0.6.19
es7-react-js-snippets|dsz|3.1.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.23
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
vscode-pull-request-github|Git|0.34.2
go|gol|0.30.0
iceworks-style-helper|ice|1.1.0
icon-fonts|idl|2.5.3
vscode-styled-components|jpo|1.6.6
vscode-github|Kni|0.30.7
auto-save|mcr|1.0.3
vscode-filesize|mkx|3.1.0
mongodb-vscode|mon|0.7.0
debugger-for-chrome|msj|4.13.0
indent-rainbow|ode|8.2.2
vscode-janus-debug|otr|1.5.8
advanced-new-file|pat|1.2.2
vscode-spring-boot|Piv|1.29.0
vscode-css-peek|pra|4.2.0
view-in-browser|qin|0.0.5
java|red|1.2.0
LiveServer|rit|5.6.1
code-spell-checker|str|2.0.14
pdf|tak|0.6.1
open-in-browser|tec|2.0.0
vscode-java-debug|vsc|0.37.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-icons|vsc|11.8.0
vscode-todo-highlight|way|1.0.5
save-and-run|wk-|0.0.22
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.13.8
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710cf:30416617
vscexrecpromp3t1:30407762

```

</details>

**Comment by Tyriar** [comment]
VS Code doesn't touch create-react-app, this looks like an issue on your end. If you think otherwise, please provide some more context on where you saw this error.
