### ISSUE TITLE
Out of Box C++ compiler

### ISSUE THREAD

**Issue by AGoh2019** [microsoft/vscode#139929]
Issue Type: <b>Feature Request</b>

I have MingGW-64 installed, but am unable to configure the JSON file to run the C++ source.  Do you have a out of box solution.  

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by Igorgro** [comment]
Vscode is not an IDE, it's a powerful text editor. You need install C++ extension https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools to integrate compiler
