### ISSUE TITLE
File extensions are truncated when using 'import'

### ISSUE THREAD

**Issue by gebbber** [microsoft/vscode#139976]
Issue Type: <b>Bug</b>

1. Add `"type": "module"` to `package.json`
2. Create file `app.js`; leave it empty to start.
3. Create file `tool.js`; add a named non-default export, and save the file:
```javascript
export function abcdefg() {
}
```
4. In `app.js`, begin to type the name of function, in order to call it: `abcdefg();`
5. As you type, VS Code should suggest importing it from `./tool` (note the lack of `.js` extension)
6. Accept the suggestion to automatically import the file
7. Import is added: `import { abcdefg } from './tool'`, with no `.js` extension
8. `app.js` won't run &mdash; ES6 import syntax requires the complete filename, including extension.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.0.0
rest-client|hum|0.24.6
vscode-docker|ms-|1.18.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
hosts|tom|1.2.0

(1 theme extensions excluded)

</details>

**Comment by albertosantini** [comment]
See https://github.com/Microsoft/TypeScript/issues/16577#issuecomment-754941937

**Comment by IllusionMH** [comment]
/question

This auto imports behavior requires separate configuration depending on your setup.
In your case you should add to Workspace (or User) `settings.json` `"javascript.preferences.importModuleSpecifierEnding": "js"` (`"typescript.preferences.importModuleSpecifierEnding": "js"` if needed).


@albertosantini this question is about code generated with auto imports, linked issue is about different "problem" - updates of import paths during compiling JS/TS files.
