### ISSUE TITLE
VSCode opens files weirdly

### ISSUE THREAD

**Issue by DRYN07** [microsoft/vscode#139990]
Issue Type: <b>Bug</b>

If I drag a file to the editor, it opens nicely. However if I click on a file (txt for example), it makes new empty files from every word in the filename. I try to illustrate:

"this is a new document.txt"

If I click that document, my editor is going to look like this:
"this" > these are new empty files
"is"
"a"
"new"
"document"

I tried this with a newly downloaded clean vscode as well.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by IllusionMH** [comment]
/needsMoreInfo

Where do you click on this file Windows Explorer or where? Do you see same behavior if you use Open With... ?

**Comment by DRYN07** [comment]
> /needsMoreInfo
> 
> Where do you click on this file Windows Explorer or where? Do you see same behavior if you use Open With... ?

From windows explorer or I tried just from desktop, it does (did) the same thing. Now I did a clean install again and it works, however it would be good to find a solution for this because I tried to solve this issue since version 1.63.2 was released. I tried a clean install, clean portable, go through all the settings and nothing helped. Honestly I don't know why it is working now.

Here is a picture about the issue: [https://ibb.co/FJx73tB](url)

**Comment by IllusionMH** [comment]
Not sure how you set VS Code to open `.txt` files by default, but looks like previously it was `code this is a new document.txt` which will treat each part separated by space as file name to open from tht folder instead of `code 'this is a new document.txt'` which will correctly pass name as single string and VS Code can open file that exists on disk.

**Comment by DRYN07** [comment]
I set it up using windows's default window for it (right click on file > Properties > set as default for .txt | sorry i don't really know, my OS is not english)

**Comment by joaomoreno** [comment]
> If I drag a file to the editor, it opens nicely. However if I click on a file (txt for example), it makes new empty files from every word in the filename. I try to illustrate:

Can you show me a screen recording of the bug in action?

**Comment by DRYN07** [comment]
> Can you show me a screen recording of the bug in action?

https://drive.google.com/file/d/1jBm0us-R-tBAEGTaZXNs6rCyhxkatFtM/view?usp=sharing

**Comment by joaomoreno** [comment]
Does the issue reproduce if you reinstall VS Code?

**Comment by DRYN07** [comment]
> Does the issue reproduce if you reinstall VS Code?

Yes I tried to reinstall it more times and also tried a clean portable version. After weeks of tying now the reinstall somehow worked, however it would be good to know what was this issue if it happens again

**Comment by joaomoreno** [comment]
Very strange. I have never seen it happen before. Let's keep an eye on it and do let us know if it comes back.

**Comment by DRYN07** [comment]
> Very strange. I have never seen it happen before. Let's keep an eye on it and do let us know if it comes back.

Okay so the problem is here again :/ On one of my PC it works now, on the other one it does not. Even on a clean install. Are there any settings that can possibly cause this? I don't have any idea I can try.

**Comment by Tyriar** [comment]
Could be related to how the CLI is hooked up to the default OS action?
