### ISSUE TITLE
There is a problem with the title display

### ISSUE THREAD

**Issue by LwyNamaste** [microsoft/vscode#139916]
Issue Type: <b>Bug</b>

In the secondary menu of the pull and push menu of branch management, there is a [Pull from] and [Push to] that are not displayed completely, and the mouse and hover are still displayed with ellipsis

VS Code version: Code - Insiders 1.64.0-insider (d12df34e31b4a018735d312a8947d79331132368, 2021-12-17T05:14:38.692Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (2.19GB free)|
|Process Argv|--crash-reporter-id a0740c50-e6fc-4754-a5f9-c5a62f95937c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.6.0
bracket-pair-colorizer|Coe|1.0.62
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
vscode-escape-entities|dja|0.1.0
gitlens|eam|11.7.0
prettier-vscode|esb|9.0.0
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
vscode-language-pack-zh-hans|MS-|1.64.1
color-highlight|nau|2.5.0
indent-rainbow|ode|8.2.2
material-icon-theme|PKi|4.11.0
vs-code-prettier-eslint|rve|3.0.4
code-spell-checker|str|2.0.14
open-in-browser|tec|2.0.0
vscode-js-console-utils|vsc|1.1.2
vscode-js-console-utils|wht|0.7.0
vscode-import-cost|wix|2.15.0
ReactSnippets|xab|2.4.0
material-theme|zhu|3.13.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
vscop804:30404766
vs360cf:30404996
vsclayoutctrt:30405800
py55gd98cf:30408622
azactmsalcf:30409288

```

</details>

**Comment by joaomoreno** [comment]
Can you share a screenshot?
