### ISSUE TITLE
electron downloaded by gulp-atom-electron have something wrong

### ISSUE THREAD

**Issue by nabychan** [microsoft/vscode#139994]
Issue Type: <b>Bug</b>

ffmpegdl in node_modules\electron\dist is bigger than the in .build\electron. The second one just plays video with sound control grey, but the first one is good. So why use gulp-atom-electron to download a new one, just use the one in node package is well. By the way, the released version cannot play video sound too.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by deepak1556** [comment]
ffmpeg from `gulp-atom-electron` does not support proprietary codecs hence the size difference. The only supported codecs are 

* opus
* webm (encoded with opus codec, the default encoding with vorbis codec is not supported)
* flac
