### ISSUE TITLE
Search for specific node_module

### ISSUE THREAD

**Issue by nicoabie** [microsoft/vscode#139928]
It would be really cool to add in the contextual menu of the node_module folder an item call search module to quickly get to its folder.

**Comment by roblourens** [comment]
Sorry I don't understand the request, can you explain some more?

**Comment by IllusionMH** [comment]
Just expand `node_modules` dir and start typing module name. This will trigger search on type. Use arrows to navigate between matches (fuzzy matches).

**Comment by nicoabie** [comment]
Thanks @IllusionMH, closing this issue
