### ISSUE TITLE
Sync outline with code

### ISSUE THREAD

**Issue by wxzhuhua** [microsoft/vscode#139959]
Issue Type: <b>Feature Request</b>

In outline window, follow and highlight the items that the location of cursor is inside code window

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

**Comment by wxzhuhua** [comment]
I realized that there's already a "follow cursor" option, though, it don't work for constants.
So, it can be improved by following all items.

**Comment by wxzhuhua** [comment]
I realized that there's already a "follow cursor" option, though, it don't work for constants.

So, it can be improved by following all items, and display a skeleton row above the highlighted item to show the total belong-to structure.

**Comment by jrieken** [comment]
> I realized that there's already a "follow cursor" option, though, it don't work for constants.

What language and what language extension do you refer to?

**Comment by wxzhuhua** [comment]
@jrieken I was using C, file with .c extension
