### ISSUE TITLE
Support @augments when a template is used.

### ISSUE THREAD

**Issue by akwotom** [microsoft/vscode#139925]
Seems like, till now, VS code doesn't provide any auto complete when faced with such a documentation:

```js

/**
    @class
    @template ArrayType
    @augments ArrayType - Instead of @augments String or Number, we are augmenting the very template parameter that's being passed in.
*/
class CustomArray{

}

```

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
