### ISSUE TITLE
Pinch to zoom support

### ISSUE THREAD

**Issue by Filyus** [microsoft/vscode#139989]
I would very much like to see support for the interface and editor zoom using multi-touch.

**Comment by rzhao271** [comment]
Also, I'm wondering which OS or device you're requesting the feature for?

**Comment by Filyus** [comment]
I have a touch screen and Windows 10. But it seems to me that it does not depend on the operating system. Chromium supports Touch events.

Ideally, it would be great to have two fingers pan and zoom (like in the browser).

At the moment, there are not so many developers who have a touch screen, but I am sure that the situation will gradually change in the future.

I am ready to write the code myself.

This functionality shouldn't have a performance impact.
