### ISSUE TITLE
entering a comma shows unwanted documentation window

### ISSUE THREAD

**Issue by Velok** [Microsoft/vscode#13998]
- VSCode Version: 1.6.1
- OS Version: macOS 10.12

Steps to Reproduce:

1. open an angular2 component file (typescript)
2. delete and reenter a comma at the end of a property in the Component Decorator

![image](https://cloud.githubusercontent.com/assets/6967752/19518902/c6bf63ca-9609-11e6-8ada-8ca5dad646b2.png)

**Comment by roblourens** [comment]
By design, you can also show it by pressing cmd+shift+space
