### ISSUE TITLE
SOURCE CONTROL REPO: 

### ISSUE THREAD

**Issue by kuperxu** [microsoft/vscode#139902]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/10049446/147717333-09d2947d-b799-4071-b099-307a507c38c6.png)

2.
```
git worktree list 
~/workspace/ark_template/ArkTemplate  77637c8 [master]
```

**Comment by kuperxu** [comment]
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z (2 wks ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

**Comment by lszomoru** [comment]
@kuperxu, could you please share any additional information which would allow me to reproduce this and debug it? Are you opening a workspace that has multiple repositories, or it one repository that somehow results in duplicate nodes in the `Source Control Repositories` view? Thank you!

**Comment by kuperxu** [comment]
-
