### ISSUE TITLE
--enable-logging not work

### ISSUE THREAD

**Issue by nabychan** [microsoft/vscode#139961]
i want to see chromium level log，after i looked for a while , i get a --enable-logging which can be used in electron, but not work for vs code.

**Comment by deepak1556** [comment]
What chromium level logs are you interested in tracking ?

**Comment by nabychan** [comment]
Accoding to https://www.electronjs.org/zh/docs/latest/api/command-line-switches
There three switchs:
--enable-logging[=file]
--log-level=N             //works with --enable-logging
--v=N                        //works with --enable-logging
--vmodule=N            //works with --enable-logging
I test --enable-logging --log-level with vs code，no logs show。
I just test it with electron，no logs too，
But --enable-logging --v works well，
Maybe this a electron problem，or I need more test to explorer it。
Thanks!

**Comment by nabychan** [comment]
I will close this issue, this is not a problem of vs code.
