### ISSUE TITLE
Jump along indent

### ISSUE THREAD

**Issue by batamire** [Microsoft/vscode#13996]
I'd like to be able to quickly jump along the same indentation, as in: https://packagecontrol.io/packages/Jump%20Along%20Indent

I also like keybindings in this extension, very useful.
It conflicts with current move lines up/down keybindings (alt + up/down) but that functionality could be improved: https://github.com/Microsoft/vscode/issues/12718#issuecomment-254792297

**Comment by roblourens** [comment]
I'd like that too, but it should be doable by an extension. Want to take a shot at it? :) https://code.visualstudio.com/docs/extensions/overview

**Comment by kaiwood** [comment]
It is doable by an extension, I'm using a rough implementation of this for myself for the past three weeks. Didn't know there is a Sublime plugin that mimics this behaviour (it originally came from TextMate, where it's built in). 

If I find the time over the weekend, I'll polish it a bit and release it in the marketplace.

**Comment by kaiwood** [comment]
Alright, extension can be found here: https://marketplace.visualstudio.com/items?itemName=kaiwood.indentation-level-movement

It currently works for basic movements up and down. There are still a couple of bullet points on my todo for this (jump+selection, scrolling the viewport on long jumps, jumping with multiple cursors…), but it shouldn't take too long for a proper 1.0 release ;)
