### ISSUE TITLE
JSX language support - more than colors

### ISSUE THREAD

**Issue by OshotOkill** [Microsoft/vscode#140]
I know VSCode has not support JSX yet but it didn't appear so much error highlights in the last version, even I had already changed my language mode into `Plain Text`.
![2](https://cloud.githubusercontent.com/assets/6079112/11261584/f5e2e9d0-8eb0-11e5-8388-e6711dc718f9.PNG)

**Comment by leafduo** [comment]
Seems that changing language only affect highlighting?

**Comment by OshotOkill** [comment]
@leafduo So it does, and I must change file extension into .jsx to get rid of these warnings.

**Comment by leafduo** [comment]
@OshotOkill It's annoying. And jsx and js files have different highlighting. That's annoying too.

**Comment by daiheitan** [comment]
http://stackoverflow.com/questions/32832264/change-language-to-jsx-on-visual-studio-code

Found this but it is not working for the latest VS Code build

**Comment by OshotOkill** [comment]
@leafduo That's OK for me, especially colors and highlightings are the same as .tsx files in this version (kinda like C#).

**Comment by OshotOkill** [comment]
@daiheitan It's a hack lol and could lead to some side effects...

BTW #81 also mentioned these problems.

**Comment by anibali** [comment]
Same problem here, none of the hacky "fixes" I've found around the internet seem to help either. Is renaming our files to use the IDE properly really our only option at the moment?

**Comment by OshotOkill** [comment]
@anibali AFAIK It is...

Once upon a time I replied them on twitter for asking jsx support, and they said they were working on getting it better just a start.

**Comment by daiheitan** [comment]
@OshitOkill
VS Code does have jsx support now. It just could not parse JSX syntax in plain js files.
This is assigned to a developer now, so I guess let's just wait.

**Comment by admmasters** [comment]
I think one of the issues seems to be that jsx is seen as different to normal js, which seems to work pretty well with autocompletion (intellisense) etc. JSX and other variants of JS should still be able to support all the same functionality as the basic JS syntax if those features are available and there should be the ability for VS Code dialects to act as extenders as oppose to completely separate languages if that makes any sense...

**Comment by jrieken** [comment]
Appart form syntax highlights there is no real support for JSX yet, but it is on its way. Stay tuned.

**Comment by jpierson** [comment]
What is the motivation for JSX syntax in .js files? I don't understand what using the .js file extension buys you other  than possible tooling compatabilty. I don't doubt that there are valid reasons but they should be presented when making feature requests.

**Comment by gpbl** [comment]
@jpierson For an editor, it's like having JS code in an HTML page. Also, from a developer point of view, JSX is Javascript with a different syntax.

**Comment by anibali** [comment]
@jpierson Using a new IDE should not force you to rename a bunch of files IMO.

**Comment by alexisbg** [comment]
There is workaround by using ESLint: have a look to "JavaScript Linters (ESLint, JSHint)" heading at:
https://code.visualstudio.com/docs/languages/javascript

Very efficient !

**Comment by jpierson** [comment]
Ok so what I can gather from @anibali and @gpbl is that jsx syntax inside .js files is useful for designers and there must be other editors that have set this precident and thus would make VSCode difficult to switch to for projects that have been taking advantage of this feature. Does that sound right?

Personally I would be more in favor of a feature that allows a global setting that makes all .js files be able to default to reactjs JSX syntax. This should be similar to the jsconfig files that are already used on a directory level to specify between es5 and es6. Any arguments against using that as a solution? My concerns about supporting any super set of JavaScript in .js files is that it could potentially make the code for standard JS parsing more complex, slow, and hard to maintain. Are these concerns valid?

**Comment by jpierson** [comment]
See #334 for more details on another option for treating JavaScript as JSX.

**Comment by anibali** [comment]
@jpierson I don't expect any superset of JS to be automatically supported. Either of your proposed solutions would work fine for me.

**Comment by anibali** [comment]
FWIW the ESLint workaround proposed by @alexisbg is good for my needs.

**Comment by OshotOkill** [comment]
@jpierson My opinion is similar that they should make an optional choice in user settings to config all .js files support JSX syntax or, to say the least, provide this option in jsconfig.json.

**Comment by OshotOkill** [comment]
@alexisbg lOl I totally forget we could open ESlint in editor other than the default and extension now make it more convenient. Thanks.

But I am also looking forward to another way of setting this in global rather download ESlint from npm every time.

**Comment by jwulf** [comment]
Does the eslint workaround work when the file is named `*.jsx`? I have an `app.jsx` file, and `"eslint.enable:true`, and I get syntax highlighting and no spurious errors - but I don't think I'm getting eslinting.

**Comment by fhelwanger** [comment]
If I use the eslint workaround, can I still get intellisense to work?

**Comment by alexisbg** [comment]
@fhelwanger Intellisense seems to work but it is not always relevant.

**Comment by dlong500** [comment]
eslint is a decent workaround at the moment but it would still make a lot of sense to fully support JSX syntax in `*.js` files.  After all JSX syntax is specifically meant to be used within/along side JavaScript, so it doesn't make sense to separate the two.  All that should be needed is an extension to the standard JavaScript syntax.  I think it would make sense to have a setting option to recognize JSX within `*.js` files so it can enabled or disabled per user preference.

**Comment by egamma** [comment]
We plan to improve this by integrating the Salsa work from the TypeScript team: Microsoft/TypeScript#4789

**Comment by OshotOkill** [comment]
@jwulf Yes it does and .jsx files now support the basic function -- autocomplete brackets...

If you try to return two nodes in `render() {}` function you will get a `parsing error`, so I think the linting is working.

**Comment by egamma** [comment]
Not fix, but here is a **workaround** for using VS Code with JSX:

* Install the [vscode-eslint extension](https://marketplace.visualstudio.com/items/dbaeumer.vscode-eslint) and [configure eslint](http://eslint.org/docs/user-guide/configuring.html) for JSX.
``` 
{
    "ecmaFeatures": {
        "jsx": true,
        ...
    }
    ...
}

```
* If you are using React constructs inside .js files then the built-in JavaScript validation can be disabled using the setting `"javascript.validate.enable": false` or 
* You can install the `js-is-jsx` [extension](https://marketplace.visualstudio.com/items/eg2.js-is-jsx) which changes the file mapping so that .js files are treated like .jsx files. **Notice** when installing this extension then you loose the existing language support for .js files.

**Comment by albertogasparin** [comment]
[js-is-jsx extension](https://marketplace.visualstudio.com/items/eg2.js-is-jsx) + [eslint extension](https://marketplace.visualstudio.com/items/dbaeumer.vscode-eslint) looks like the best combo for now, as you will get both syntax highlight and hinting.

**Comment by egamma** [comment]
Yes makes sense, thanks (updated my comment above).

**Comment by prashaantt** [comment]
That's really a huge tradeoff between form (highlighting) and function (intellisense), which IMO is the distinguishing feature of Code. Sublime Text otherwise has an excellent highlighting support for JSX already.

Here's my +1 to full native JSX support in Code.

**Comment by justsayno** [comment]
I +1 as well. I have just started using WebStorm instead... Which I don't like nearly as much.

**Comment by egamma** [comment]
@justsayno @prashaantt  the other work around you can try is to disable the built in JS validation. Then you will still get some intellisense in JS but still no support for JSX intellisense. To disable the built-in JS validation add the following setting to your user or workspace settings:

```json
{
    "javascript.validate.enable": false
}
```

Please let me know what you think works better, than we can adjust the work around recommendation.

**Comment by aravantv** [comment]
@jwulf I have the same issue: I use the workaround with eslint + the corresponding vscode extension but the linting simply does not appear in vscode when I edit my .jsx files. However:
* running eslint in command-line does show that there are some problems
* and linting does display when Iedit *.js* files in vscode

**Comment by mheiber** [comment]
+1

**Comment by fhelwanger** [comment]
@mheiber I think that Salsa already does that.

Check https://code.visualstudio.com/Updates#_javascript-salsa-preview

**Comment by egamma** [comment]
Closing - Salsa will be the default for the February update and supports JSX.

**Comment by mheiber** [comment]
Thanks! I'll switch over to Salsa, looking forward to trying it out. Love
the work you guys are doing with Code.

**Comment by shprink** [comment]
js-is-jsx is gone (　ﾟдﾟ)

![image](https://cloud.githubusercontent.com/assets/1388706/15882988/0dfb315e-2d7f-11e6-8d02-6962e31f95ca.png)

**Comment by prashaantt** [comment]
I think this is now easily fixed with the setting:

```json
"files.associations": {
    "*.js": "javascriptreact"
}
```
