### ISSUE TITLE
press "L" key continuously bug

### ISSUE THREAD

**Issue by zhangbowei** [Microsoft/vscode#14000]
![snip20161019_2](https://cloud.githubusercontent.com/assets/14348480/19521298/ac9efcd0-9645-11e6-92fb-6411e1f5e598.png)
![snip20161019_3](https://cloud.githubusercontent.com/assets/14348480/19521299/aca4ddda-9645-11e6-9e2b-4117407dbb23.png)

what's this when I press "L" key all the time?

**Comment by tremblaye** [comment]
It seems you are on a mac and that this is default OS behaviour. It's not that you are pressing L all the time, it's that you are holding it down for a while.

If you do the same thing with the letter "e", you get more options (accented characters).

**Comment by roblourens** [comment]
That's right, thanks @tremblaye. It is possible to disable this in OSX if you search around.

**Comment by zhangbowei** [comment]
Thanks.
Solved by this method.

1. iterm
2. Input "defaults write -g ApplePressAndHoldEnabled -bool false"
