### ISSUE TITLE
Intellisense not respecting jsdoc parameter type for typescript

### ISSUE THREAD

**Issue by timty** [Microsoft/vscode#14008]
Intellisense works great for my postgress Pool type when explicitly declared:

![screen shot 2016-10-19 at 10 16 03 am](https://cloud.githubusercontent.com/assets/113954/19529521/15dfb24a-95e5-11e6-8c86-8a9f2e4c0e5a.png)

However when passed as a parameter to a function and described through a JSDoc parameter intellisense fails:

![screen shot 2016-10-19 at 10 14 57 am](https://cloud.githubusercontent.com/assets/113954/19529486/ec2f52ca-95e4-11e6-9748-f1ff9e3f6905.png)

- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 15.6.0
- Extensions: Unity.unity-debug-1.0.1, benjaminromano.typings-installer-0.2.0, dbaeumer.vscode-eslint-1.0.7, dkundel.vscode-npm-source-0.0.3, joelday.docthis-0.3.4, mohsen1.prettify-json-0.0.3, ms-vscode.omnisharp-0.3.3, rafaelmaiolla.diff-0.0.1, stevencl.addDocComments-0.0.8, xabikos.JavaScriptSnippets-1.1.0, xabikos.ReactSnippets-1.1.1

**Comment by waderyan** [comment]
@timty thank you for opening this issue. I have confirmed this with the latest bits and no extensions. Migrating to JavaScript language service. 

Code to copy and paste. 

```typescript
class Foo {

    bar() {}
}

var f = new Foo();
// IntelliSense works correctly
// f. 


/**
 * @param {Foo} x
 */
function zoo(x) {
    // IntelliSense is not being given
    x.
}
```

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11825
