### ISSUE TITLE
setting envirment variables for tsserver in vscode 

### ISSUE THREAD

**Issue by craigphicks** [microsoft/vscode#140064]
My environment requires the bash environment variable setting `NODE_PATH=$(npm root -g)` in order that `tsc` can find the global `node_modules` folder.  So I set it in `~/.profile` and `~/.bashrc`.  No problem.

However, in **vscode** the `tsserver` apparently doesn't have access to the `NODE_PATH` setting, so it reports an error when global imports are declared, e.g., 

```
import npm from 'npm' // Cannot find module 'npm' or its corresponding type declarations.ts(2307)
```

However, by ignoring the error 
```
/* @ts-ignore */
import npm from 'npm' // No error now.
```
the compilation will succeed because `tsc` knows about `NODE_PATH`.

I cannot see any  vscode/typescript setting for setting environment variables for **tsserver**, let alone a setting that requires executing a program.  

Either such a feature is missing or it is not well documented (or I haven't found it). 

Any info about a workaround would be greatly appreciated in the meantime.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

**Comment by mjbvz** [comment]
I'm not aware of any workaround for this issue, but someone on the TS team may have suggestions
