### ISSUE TITLE
wsl terminal - ansi escape background color styling not terminated  on window resize

### ISSUE THREAD

**Issue by hkskoglund** [microsoft/vscode#140086]
Issue Type: <b>Bug</b>

Resizing visual studio code window adds a full line of background color in wsl terminal

Steps to reproduce:
 
1. printf "\e[48;5;2mTEST\e[0m\n" 
2. resize window
3. notice a complete full line of green background

Not able to reproduce in fedora/gnome terminal.

Expecting ansiescape \e[0m to end styling even on window resize. Same problem observed in Windows Terminal.

<img width="877" alt="image" src="https://user-images.githubusercontent.com/3141603/148062319-4c803569-3211-4939-962f-6d18bb14f8c4.png">

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800U with Radeon Graphics          (16 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.86GB (5.48GB free)|
|Process Argv|--crash-reporter-id a447e73c-2032-4285-aa92-a2c03ddbc8dd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
vscode-eslint|dba|2.2.2
shell-format|fox|7.2.2
vscode-pull-request-github|Git|0.34.2
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5200
vsliveshare-audio|ms-|0.1.91
text-power-tools|qcz|1.30.0
geo-data-viewer|Ran|2.5.0
java|red|1.2.0
shellcheck|tim|0.18.3
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710cf:30416617
vscexrecpromp3t3:30407764

```

</details>

**Comment by meganrogge** [comment]
>Same problem observed in Windows Terminal.

This is likely a conpty problem because of what you stated above
