### ISSUE TITLE
Files cannot be dragged and dropped into Electron launched using vscode's built-in powershell

### ISSUE THREAD

**Issue by fullmooooon** [microsoft/vscode#140009]
Issue Type: <b>Bug</b>

Reproduction step:

Create a new directory in vscode
run
```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
npm start
```
Drag a png picture into the window. 
What appears is cursor css: not-allowed.And in fact, the drop event cannot be triggered

Win + R      open   powershell
```
npm start
```
The cursor displayed indicates that you can drop.
It's the same powershell that runs the npm command, but there's a problem running from vscode, so I guess it's vscode's bug.

https://user-images.githubusercontent.com/43309591/147879078-6d01ea28-7080-4dd8-9cf0-6eb43f2509d3.mp4

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.10GB free)|
|Process Argv|--crash-reporter-id 9bb126fd-b7eb-45eb-8df0-f0167b8c17ac|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.6
electron-snippets|ant|1.0.3
vscode-standardjs-snippets|cap|0.8.15
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.6.0
EnglishChineseDictionary|Cod|1.1.0
bracket-pair-colorizer-2|Coe|0.2.2
vbscript|Dar|1.0.4
vscode-eslint|dba|2.2.2
javascript-ejs-support|Dig|1.3.1
jquerysnippets|don|0.0.1
xml|Dot|2.5.1
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
php-debug|fel|1.22.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
code-runner|for|0.11.6
kotlin|fwc|0.2.23
vscode-atom-javascript-snippet|glu|0.2.1
vue-pack|hol|1.0.0
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
vue|jcb|0.1.5
svg|joc|1.4.15
jsdoc|lll|1.0.3
Kotlin|mat|1.7.1
vscode-docker|ms-|1.18.0
vscode-language-pack-zh-hans|MS-|1.63.3
remote-containers|ms-|0.209.6
debugger-for-edge|msj|1.0.15
gradle-language|nac|0.2.3
JavaScriptSnippets|nat|0.2.0
vetur|oct|0.35.0
indent-rainbow|ode|8.2.2
vuehelper|oys|0.1.0
material-icon-theme|PKi|4.11.0
vscode-jsp|pth|0.0.3
view-in-browser|qin|0.0.5
java|red|1.2.0
vue-vscode-snippets|sdr|2.2.1
kotlin-on-vscode|set|0.0.1
background|sha|1.1.30
element-ui-snippets|SS|0.7.2
language-stylus|sys|1.15.0
stylus-supremacy|thi|2.16.0
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2
JavaScriptSnippets|xab|1.8.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vs360cf:30404996
vsrem710:30416614

```

</details>

**Comment by deepak1556** [comment]
Unable to repro with latest stable `1.74`
