### ISSUE TITLE
Support opening files with an external application

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/vscode#140004]
In Visual Studio, you could open a file directly within another application whereas Visual Studio Code only lets you open with editors within the application. Sometimes you may want to open a file with another application and there's no way to do it with Visual Studio Code without opening the folder in File Explorer and using the "open with" option there.

Visual Studio displays external applications as well designers/editors within the IDE.
![image](https://user-images.githubusercontent.com/45227503/147874916-f4c3b5f8-f914-44d6-895c-564919fb8018.png)

Visual Studio Code doesn't.
![image](https://user-images.githubusercontent.com/45227503/147874947-82dc19c3-643e-458e-9bb2-e4ce75204711.png)

**Comment by sandipchitale** [comment]
This extension does it: https://marketplace.visualstudio.com/items?itemName=sandipchitale.vscode-open-with

The key is to launch child process with:

```
rundll32.exe shell32,OpenAs_RunDLL <path to file>
```

![image](https://user-images.githubusercontent.com/3310939/148841274-7ca1c9de-ab49-4259-b1fa-f0290e9b57a6.png)

**Comment by lramos15** [comment]
Oh if an extension already does it that's great and I would recommend installing that extension 👍

**Comment by sandipchitale** [comment]
I tried to create a PR but ran into layering issues in VS Code. Any guidance where I can implement the Menu registration, command registration and the above snippet I can submit the PR.

**Comment by sandipchitale** [comment]
@iramos15 Can I get some guidance on where in the vscode this should be implemented. I have implemented - 

```
export function showOpenWithDialog(fsPath: string): Promise<string> {
	return new Promise((resolve, reject) => {
		if (fsPath) {
			let stdout = '';
			const child = cp.spawn('rundll32.exe',
				[
					'shell32,OpenAs_RunDLL',
					fsPath
				],
				{
					cwd: fs.dirname(fsPath)
				});
			if (child.pid) {
				child.stdout.on('data', (data: Buffer) => {
					stdout += data.toString();
				});
			}
			child.on('error', err => {
				reject(err);
			});
			child.on('close', code => {
				resolve(stdout);
			});
		}
	});
}
```
```
MenuRegistry.appendMenuItem(MenuId.ExplorerContext, {
	group: 'navigation',
	order: 20,
	command: {
		id: OPEN_WITH_DIALOG_COMMAND_ID,
		title: nls.localize('explorerOpenWithDialog', "Open With Dialog..."),
	},
	when: ContextKeyExpr.and(ExplorerFolderContext.toNegated(), ResourceContextKey.HasResource),
});
```
```
CommandsRegistry.registerCommand({
	id: OPEN_WITH_DIALOG_COMMAND_ID,
	handler: async (accessor, resource: URI | object) => {
		const uri = getResourceForCommand(resource, accessor.get(IListService), accessor.get(IEditorService));
		if (uri) {
			showOpenWithDialog(uri.fsPath);
		}
	}
});
```
I ran into issues related to layering of vscode.

**Comment by lramos15** [comment]
The layering is there to prevent code from being executed in the wrong place. I think this is best to leave to an extension as it is specific to windows and VS Code is cross platform + on web

**Comment by sandipchitale** [comment]
Thanks!
