### ISSUE TITLE
.properties file not syntax highlighed properly

### ISSUE THREAD

**Issue by MCEmperor** [microsoft/vscode#140083]
Issue Type: <b>Bug</b>

When there is an apostrophe in a value in a .properties file, it is syntax highlighted all the way to the end of the file, or until another apostrophe is found. The same behaviour is observed when double quotes (") are used instead of apostrophes.

This is incorrect behaviour. Apostrophes nor double quotes are string delimiters in a .properties file. Instead, the value of a property starts immediately behind the first = or :, unless they are escaped with a backslash.

**Steps to reproduce:**

1. Open a new file ("File » New File" or Ctrl+N)
2. Change the language mode to "Properties (properties)"
3. Insert the following text into the file:

    ```
    greeting=hello world
    somevalue=h@*(')what
    suddenly=itisred
    ```

**Actual output:**

![actual](https://user-images.githubusercontent.com/5734897/148055686-20b98320-cb06-48b1-8005-b3d79decda75.png)

**Expected output:**

![expected](https://user-images.githubusercontent.com/5734897/148055781-5dde62fa-7237-4a6b-a804-3f8ff1ac5826.png)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by alexr00** [comment]
We get our .properties syntax highlighting grammar from https://github.com/textmate/ini.tmbundle/. Upstream issue: https://github.com/textmate/ini.tmbundle/issues/3

**Comment by MCEmperor** [comment]
Note that the upstream repository is not updated for a while (last updated 9 years ago). It may be desirable to pick a different source for highlighting .ini and .properties files.

**Comment by alexr00** [comment]
@MCEmperor I'm open to community suggestions for a new grammar! I don't see bugs filed very often for the ini grammar, but if a better, community-maintained, ini grammar is suggested I am happy to work with the owner of the grammar to understand if we will be better off if we adopt it.
