### ISSUE TITLE
VS Code core should not contain click here links

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#140059]
While testing https://github.com/microsoft/vscode/issues/107791, I noticed that some setting descriptions such as `file.exclude` have links where the text is just "here". Screenreaders would just say the link is "here", which slows down screenreader users, because they'll then have to hover around the link to figure out what the rest of the text is.

**Comment by meganrogge** [comment]
@rzhao271 how can I verify?

**Comment by rzhao271** [comment]
1. In the VS Code repo, search `[here]` with files to exclude set to `*.test.ts`
2. No results should show up.

Though I just realized two results showed up. Reopening.
