### ISSUE TITLE
Strange and useless autosuggestion #region/#endregion PHP

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#140039]
**Does this issue occur when all extensions are disabled?:**
In this ticket, I test with extension, but it also happens without extensions, for example here -> https://github.com/microsoft/vscode/issues/139559

```
Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

**Additional info:**
I've seen `#region`, `#endregion` autosuggestions very often in my PHP projects for some time. It wasn't there before.
This auto-suggestion shows up in a lot of unnecessary situations, causing confusion when writing code.
Eg.:
![vs2](https://user-images.githubusercontent.com/30685349/147945343-a0fbfcb7-816c-42c4-b216-2a441fe12c72.gif)

**It may be related to the one mentioned above:**
https://github.com/microsoft/vscode/issues/139559

**Steps to Reproduce:**
![vs1](https://user-images.githubusercontent.com/30685349/147944848-3e86df89-7adc-4149-8117-63d5ea62b4a3.gif)

**Comment by mattiasljungstrom** [comment]
I see the same in C++/C code.

**Comment by xetosu** [comment]
I had the same situation so I had to remove auto-suggestion within [settings.json] file, because it was so annoying. I'm willing to contribute to this and get rid of it.

**Comment by roblourens** [comment]
I see this with snippets that start with `#` and I don't see it in an older build.

@TylerLeonhardt did you change something with the filtering logic and special characters for quick open that might have impacted this? cc @jrieken

**Comment by jrieken** [comment]
Yeah, I have made changes and they need further polish it seems...

**Comment by ycyc202020** [comment]
111

**Comment by jrieken** [comment]
@kanlukasz From what extension do the `#region` snippets come from? Out of the box I am not seeing them

<img width="733" alt="Screen Shot 2022-01-18 at 09 12 48" src="https://user-images.githubusercontent.com/1794099/149896938-31bfb2d7-5844-47cd-ae32-65971b2c0be8.png">

**Comment by kanlukasz** [comment]
I am afraid the extensions are not involved as now i am testing it on the new portable VSCode version without any extensions and the situation is the same

### Steps to Reproduce:

1. Download fresh VSCode portable from official [source](https://code.visualstudio.com/docs/?dv=winzip)

2. Unpack, create empty `data` directory inside, run

3. Set VSCode Settings:
```
{
    "editor.quickSuggestions": {
        "other": true,
        "comments": true,
        "strings": true
    },
    "editor.wordBasedSuggestionsMode": "allDocuments"
}
```

4. Open empty project folder

6. Create file - `index.php`

7. The contents of the `index.php` file:
```
<?php

getName('');
```

8. Now try type `B` or `Bart` inside `getName('')`

---

Above I have written everything in the form of text and sources, but for the sake of clarity, I am attaching a short GIF with the result of these actions again:
![vsvsvs2233](https://user-images.githubusercontent.com/30685349/149899838-2642485d-5559-4cdf-ac27-44649269fed8.gif)

**Comment by mattiasljungstrom** [comment]
with C++ extension on, I see it when I create a new file and type this and then hit ctrl+space. (It shows up as suggestions all the time in my code, but this was the most simple example I could replicate.)

<img width="710" alt="end_region_cpp" src="https://user-images.githubusercontent.com/411202/149899699-38b8a195-1220-4fc3-ac20-c167456af1fe.png">

**Comment by jrieken** [comment]
Yeah, with C++ I am seeing this using `function abc($|)` which is unwanted (not that `|` is the cursor). I am pushing a change for that. 

@mattiasljungstrom your sample (https://github.com/microsoft/vscode/issues/140039#issuecomment-1015180383) is how it is because the `#`-prerix matches the snippet prefix and because snippets work without context

I try again with php but one important difference to CPP (and likely others) is that `$` is part of a word in CPP but not in PHP. So, for the PHP we aren't aiming for "overlap" because we are not at a word end

**Comment by kanlukasz** [comment]
Sorry, I'm not sure what you mean by overlap. Does this apply to my example above?
So it will be fixed for php too or not?

**Comment by mattiasljungstrom** [comment]
@jrieken ok thanks! just to be clear, it happens in lots of scenarios, not only after '$'. another example without typing '#':
<img width="718" alt="end_region_bug3" src="https://user-images.githubusercontent.com/411202/149905172-62a1dd5e-dd3c-4838-90e9-6571e8821353.png">
:

**Comment by kanlukasz** [comment]
> it happens in lots of scenarios,

Same with PHP (i have only shown one example which is the easiest to reproduce)

**Comment by jrieken** [comment]
@mattiasljungstrom Yeah, that should be fixed now. The `$` or `t` bit will be identified as "word" and when at word ends the prefix must overlap (now)

**Comment by jrieken** [comment]
@kanlukasz re https://github.com/microsoft/vscode/issues/140039#issuecomment-1015179712 - that's using stable, not insiders, right? please use insiders because that already has some fixes

**Comment by kanlukasz** [comment]
@jrieken - I did some quick tests and it looks like it works fine now 🎉
