### ISSUE TITLE
Error while fetching extensions. XHR failed

### ISSUE THREAD

**Issue by sylvain-priser** [microsoft/vscode#140026]
Issue Type: <b>Bug</b>

type in any search term in the Extension manager search (I'm typing "git") and I get this message "Error while fetching extensions. XHR failed"

I also get many errors in my console when loading VSC as stated and this issue : https://github.com/microsoft/vscode/issues/139889

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (1.21GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/SylvainPriser/Documents/sfdx/crg/chr --crash-reporter-id 9548980c-5638-4e18-90b4-f37a89c5791c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
powershell|ms-|2021.12.0
salesforcedx-vscode|sal|53.8.1
salesforcedx-vscode-apex|sal|53.8.1
salesforcedx-vscode-core|sal|53.8.1
salesforcedx-vscode-soql|sal|53.8.1
salesforcedx-vscode-visualforce|sal|53.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710cf:30416617
vscexrecpromp3t1:30407762

```

</details>

**Comment by sandy081** [comment]
Can you please provide following?

> F1 > Toggle Developer Tools
> Please provide us the screenshot of errors in the console

**Comment by sylvain-priser** [comment]
Hi Sandeep, 

here it is :
![Capture d’écran 2022-01-05 160036](https://user-images.githubusercontent.com/54172581/148239185-41d206f8-4f49-4de7-9035-5afd338edad5.png)

**Comment by sylvain-priser** [comment]
and this is another screenshot from another computer with a fresh VSC install (and also fresh Win10 install) .. but same microsoft account

![Annotation 2022-01-05 160257](https://user-images.githubusercontent.com/54172581/148239954-b942d73a-e1a6-4c48-b5d0-a7d0b98aff46.png)

**Comment by sandy081** [comment]
Seems like you have network connection issues - it could be proxy related or network admin related.

For more trouble shooting passing on to @deepak1556 and @chrmarti

**Comment by chrmarti** [comment]
Could you start VS Code with `--log-net-log=netlog.json`, retry to trigger the error and then post the created netlog.json here?

**Comment by sylvain-priser** [comment]
Hi Christof,

To add to Sandeep comment, I have no proxy neither at home office nor at company office.

here is the dos command output :
![Capture d’écran 2022-01-06 084903](https://user-images.githubusercontent.com/54172581/148347948-22fec375-517d-4e2c-97a7-b7d1117c7440.png)

.. and the zipped netlog.json :
[netlog.zip](https://github.com/microsoft/vscode/files/7820267/netlog.zip)

Sylvain

**Comment by chrmarti** [comment]
Only the requests to marketplace.visualstudio.com fail, others seem to work as expected.

@sylvain-priser Are you using a VPN? Did this work before?

**Comment by sylvain-priser** [comment]
Quite strange indeed, no I don't use a VPN except sometimes when working for a specific customer. Could that have an effect ? 

I just relaunched my vscode with VPN connection enabled, but it seems to give the same result. Is there anything I can do to make it work ?

![Capture d’écran 2022-01-06 095441](https://user-images.githubusercontent.com/54172581/148356471-db1717b9-2f72-44b1-9b74-0d6f4f9c958f.png)

[netlog.zip](https://github.com/microsoft/vscode/files/7820573/netlog.zip)

**Comment by sylvain-priser** [comment]
Something related to wifi network apparently, it seems to work fine from another home computer wired directly to the router. So the issues occurs when connected through both company and home wifi. Any idea of what kind of support I should contact for such a case ?

![Capture d’écran 2022-01-06 103145](https://user-images.githubusercontent.com/54172581/148361838-0184c10f-4fdf-4eff-b4bd-2ca9cf7109da.jpg)

**Comment by chrmarti** [comment]
Maybe verify it works when you wire the machine to the router. Also check with your company's network admins if there is some special network setup on your machine.
