### ISSUE TITLE
[api] finalize `icon` property of the language contribution point

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#140047]
As implemented by #14662 and #118846 (PR)

Language contributors can define an icon for the language.
```jsonc
{
  "contributes": {
    "languages": [
      {
        "id": "latex",
        // ...
        "icon": {
          "light": "./icons/latex-light.png",
          "dark": "./icons/latex-dark.png"
        }
      }
  ]
```
The icon is used by file icon themes as fallback if they don't have an icon for the language.
- the file icon theme defines at least one file icon (not just a generic icon for all files such as the `Minimal` theme)
   -> default language icons do not show in file icon themes like `Minimal` or `None`
- the file icon theme does not define a specific icon for the language
- icons defined for file extensions or file names always win against the language icon (no change)
- file icon themes can override this default behavior by defining `showLanguageModeIcons: true|false` in the theme file.
   - `showLanguageModeIcons: true` shows the default language icons even if the theme does not specify a file icon
   - `showLanguageModeIcons: false` prevents that default language icons are used.

**Comment by LadyCailin** [comment]
My language supports multiple types of file extensions, and it would be nice to have a different icon for each. Is that possible?

**Comment by aeschli** [comment]
@LadyCailin No, we just allow to set a single language icon.
