### ISSUE TITLE
git.clone not found - SourceControl/SCM does not work

### ISSUE THREAD

**Issue by rbaumgar** [microsoft/vscode#140092]
Issue Type: <b>Bug</b>

```
[2022-01-04 15:20:55.050] [renderer21] [error] command 'git.clone' not found: Error: command 'git.clone' not found
    at y._tryExecuteCommand (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1482:3364)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1482:3245
[2022-01-04 15:21:04.589] [renderer21] [error] Error received from starting extension host (kind: LocalProcess)
[2022-01-04 15:21:04.589] [renderer21] [error] The local extension host took longer than 60s to connect.
[2022-01-04 15:21:09.591] [renderer21] [error] undefined
[2022-01-04 15:21:09.591] [renderer21] [warning] Settings Sync: Accounts are not initialized

$ git version
git version 2.27.0
$ which git
/usr/bin/git
$ ls -l /usr/bin/git
-rwxr-xr-x. 1 root root 3206088 15. Jun 2020  /usr/bin/git
 
```
SCM/Git does not work in new/cloned directory. Old dirctories work.
Git version > 2.0

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 4.18.0-348.2.1.el8_5.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.00GB (8.11GB free)|
|Process Argv|. --crash-reporter-id 5a57cda8-c6e3-418d-bc86-25900f90213f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
karavan|cam|0.0.9
vscode-extension-kogito-bundle|kie|0.15.0
vscode-kubernetes-tools|ms-|1.3.4
vscode-boot-dev-pack|Piv|0.1.0
vscode-concourse|Piv|1.29.0
vscode-manifest-yaml|Piv|1.29.0
vscode-spring-boot|Piv|1.29.0
apache-camel-extension-pack|red|0.0.11
atlasmap-viewer|red|0.1.2
fabric8-analytics|red|0.3.5
java|red|1.2.0
project-initializer|red|0.2.1
vscode-apache-camel|red|0.1.4
vscode-camelk|red|0.0.28
vscode-commons|red|0.0.6
vscode-didact|red|0.4.0
vscode-extension-bpmn-editor|red|0.15.0
vscode-extension-dmn-editor|red|0.15.0
vscode-extension-pmml-editor|red|0.15.0
vscode-knative|red|0.9.4
vscode-openshift-connector|red|0.2.12
vscode-openshift-extension-pack|red|0.0.2
vscode-openshift-java-pack|red|0.0.2
vscode-rsp-ui|red|0.23.11
vscode-server-connector|red|0.25.2
vscode-tekton-pipelines|red|1.0.1
vscode-wsdl2rest|red|0.0.15
vscode-xml|red|0.18.2
vscode-yaml|red|1.2.2
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710cf:30416617
vscexrecpromp3t1:30407762

```

</details>

We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by rbaumgar** [comment]
looks like a duplicate with #139598

**Comment by lszomoru** [comment]
@rbaumgar, could you please share the exact steps that you have performed to get the error?
Also can you please invoke the `Git: Show Git Output...` command from the command palette and share the output?

**Comment by rbaumgar** [comment]
@lszomoru 
git clone https://github.com/rbaumgar/otelcol-demo-app
cd otelcol-demo-app
code .

![image](https://user-images.githubusercontent.com/19689547/148080989-8fdbc923-15f2-45ed-a5ae-117c978b73d8.png)

**Comment by lszomoru** [comment]
@rbaumgar, if you open the `Extensions` viewlet, and search for `@builtin Git`, do you see the Git extension? Is it enabled?

**Comment by rbaumgar** [comment]
![image](https://user-images.githubusercontent.com/19689547/148083092-c538d174-2f37-47ae-9047-7c95425fc97e.png)

**Comment by lszomoru** [comment]
Are you able to reproduce the problem if you start code using `code --disable-extensions`?
I am suspecting that you have an extension that calls `git.clone` before the extension is activated.

**Comment by rbaumgar** [comment]
you are right.

Validating found git in: git
Using git 2.27.0 from git
> git rev-parse --git-dir
Open repository: /home/rbaumgar/demo/jaeger/otelcol-demo-app
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/main refs/remotes/main
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/main refs/remotes/main
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git show --textconv :README.md
> git ls-files --stage -- /home/rbaumgar/demo/jaeger/otelcol-demo-app/README.md
> git cat-file -s 606a48e4caaacd54dd0c6ce45996655c901b11c0
> git check-ignore -v -z --stdin
> git ls-files --stage -- /home/rbaumgar/demo/jaeger/otelcol-demo-app/README.md
> git cat-file -s 606a48e4caaacd54dd0c6ce45996655c901b11c0
> git show --textconv :README.md
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/main refs/remotes/main
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z -n21 -- /home/rbaumgar/demo/jaeger/otelcol-demo-app/README.md
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/main refs/remotes/main
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/main refs/remotes/main
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template

**Comment by rbaumgar** [comment]
now after restart WITHOUT disable all extensions, everything is working!

**Comment by lszomoru** [comment]
@rbaumgar, while that is great, I am sorry that we do lost the consistent repro so that we can track down the culprit extension. In case this issue reoccurs in the future I would like to suggest that you use [the extension bisect tool](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to track down the extension.
