### ISSUE TITLE
expand/collapse button doesn't work on mobile device

### ISSUE THREAD

**Issue by Buntu0001** [microsoft/vscode#140048]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2 (vscode.dev)
- OS Version: iPadOS 15.2
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15

Steps to Reproduce:

1. enter to vscode.dev
2. click or touch expand/collapse button

https://user-images.githubusercontent.com/57615703/147962302-788977dc-f239-4781-945a-148e312cf439.MOV

**Comment by sbatten** [comment]
@TylerLeonhardt I might need some help verifying this one

**Comment by TylerLeonhardt** [comment]
This is working but on iPad the trackpad had some clicks that weren’t registering. Touch seems to work fine though so that’s good.

**Comment by Buntu0001** [comment]
problem solved. thank you

**Comment by sbatten** [comment]
closing issue as per OP
