### ISSUE TITLE
Cursor goes back to starting location in "Default Settings" window

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/vscode#14006]
- VSCode Version: 1.6.1
- OS Version: Windows 10 Version 1607 OS Build: 14393.321

Steps to Reproduce:

1. Open "Default Settings" window by going to "File" menu > "Preferences" > "User Settings"
2. Drag the "settings.json" to the workspace where "Default Settings" window is present
3. Scroll down in "Default Settings" window
4. Go to another window
5. Come back to "Default Settings" window. We see the cursor at the starting location.
Snapshot is attached as reference
![1](https://cloud.githubusercontent.com/assets/16834561/19529513/d4a55b4a-964d-11e6-9099-b7cd51ae6f2f.png)

**Comment by roblourens** [comment]
I'm not following. Are you saying that the cursor position changes when you switch to another window, then switch back? How are you switching? By clicking in the window, alt+tab, ? Is this only for the Default Settings editor or any file? I don't think there's anything special about it that would affect this. Do you have any extensions installed?

**Comment by ranjan-ranjan** [comment]
> Are you saying that the cursor position changes when you switch to another window, then switch back?

Yes

> How are you switching? By clicking in the window, alt+tab, ? 

Yes

>  Is this only for the Default Settings editor or any file? 

I found it only for "Default Settings" editor. It may be for windows also.

> Do you have any extensions installed?

No

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

I think that's what he's trying to say. See the Gif.

![gif](https://cloud.githubusercontent.com/assets/19866231/19560398/20bf4288-96b3-11e6-8adb-12bf43ca7e09.gif)

**Comment by roblourens** [comment]
Oh, I see this too.

**Comment by ranjan-ranjan** [comment]
@Tekbr yes. i wasn't able to create gif in two websites that's why i wrote in text form.

**Comment by bpasero** [comment]
Landed with Sandeeps work 👍
