### ISSUE TITLE
Add a Debug action "Terminate"

### ISSUE THREAD

**Issue by yecril71pl** [microsoft/vscode#140065]
The Debug action **Stop** does not allow the application being debugged to gracefully terminate.  Please add a **Terminate** action to allow that.  The current workaround is to tell the **Process Manager** to terminate the process being debugged&mdash;but it is cumbersome when you do not know the process ID.

**Comment by weinand** [comment]
VS Code's "Stop" command supports the terminate functionality you are asking for via the Debug Adapter Protocol: If a debug extension supports "Terminate", the "Stop" command will use this in order to gracefully terminate the debuggee.
What debug extension are you using?

**Comment by yecril71pl** [comment]
I use **Microsoft .NET Core Debugger (vsdbg)**.  When the debugger stops the application, [ApplicationStopping](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostapplicationlifetime.applicationstopping#Microsoft_Extensions_Hosting_IHostApplicationLifetime_ApplicationStopping) does not fire.
