### ISSUE TITLE
Theme type:light is ignored, wrongly detected as dark theme

### ISSUE THREAD

**Issue by phil294** [microsoft/vscode#140006]
Does this issue occur when all **other** extensions are disabled?: Yes

- VS Code Version: 1.63.1
- OS Version: Manjaro 21.2.0, 5.4.164-1

Steps to Reproduce:

[This extension](https://marketplace.visualstudio.com/items?itemName=wassimdev.windows-nt-vscode-theme) has `"type": "light"` [set in its -color-theme.json](https://github.com/manekinekko/windows-nt-vscode-theme/blob/main/themes/windows-nt-color-theme.json#L3), but VSCode ignores that and still shows it listed under `dark themes` regardless and applies `.vs-dark` to the monaco-workbench div. This results in bad contrasts, some wrong colors etc. I checked, the the GitHub json is not different from the one contained in the extension.

Maybe the author applied some ambiguous colors or misconfigured something, but with type:light set, this must never happen and is surely a bug.

**Comment by usernamehw** [comment]
Maybe value in `package.json` is overriding it?

https://github.com/manekinekko/windows-nt-vscode-theme/blob/5c0e241c2c3497299ba7d43ee1db0512eb963b97/package.json#L48

**Comment by aeschli** [comment]
What matters is the value in the package.json. The color-theme file format does not really have a type attribute.
