### ISSUE TITLE
I hope to invoke addExtraLib method in vscode extension

### ISSUE THREAD

**Issue by xiaobindebingo** [microsoft/vscode#140070]
please Add typescript types lib for code hint in vscode extension, I hope to invoke addExtraLib method in vscode extension; like monaco editor:

```
monaco.languages.typescript.typescriptDefaults.addExtraLib()
```
detail: [https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults)

**Comment by mjbvz** [comment]
Duplicate of #139923 

Please follow up on the original issue instead of posting a duplicate
