### ISSUE TITLE
Line endings aren't copy/pasted correctly from VS Code

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#1400]
When I copy / paste a JSON file with LF or CRLF line endings, and paste it into PowerPoint 2016 for Mac, the line endings aren't maintained.

Using the [Atom Editor](http://atom.io), when I use CRLF line endings, the same content pasted into PowerPoint for Mac 2016 properly maintains the line endings.

What could cause this behavior to occur? Is there something I should be doing differently? Screenshots included below.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

<img width="520" alt="screen shot 2015-12-16 at 8 49 10 pm" src="https://cloud.githubusercontent.com/assets/466713/11860834/7d3514ea-a436-11e5-8ce3-d5426456a958.png">

<img width="1060" alt="screen shot 2015-12-16 at 8 49 45 pm" src="https://cloud.githubusercontent.com/assets/466713/11860849/9590f7ca-a436-11e5-82cd-cdca2fac8c3e.png">

**Comment by alexandrudima** [comment]
Indeed, this is a bug, on Mac the clipboard always gets LF as a separator in https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/controller/keyboardHandler.ts#L656

**Comment by pcgeek86** [comment]
@alexandrudima Thank you for confirming that it's a bug. I wasn't really sure how to dig into this further, so I appreciate your help in identifying the root cause.

Cheers,
Trevor Sullivan

**Comment by pcgeek86** [comment]
@alexandrudima Thanks for fixing this.

Ciao,
Trevor Sullivan
