### ISSUE TITLE
Output panel shows old log after "Restart ESLint Server"

### ISSUE THREAD

**Issue by zen0wu** [microsoft/vscode#140029]
Cannot see the logs anymore, so I'm not too sure whether the server is still running or not (I think it is), but it would be great to have the logs

**Comment by dbaeumer** [comment]
Steps to reproduce:

- Use ESLint extension
- open a file that is linted
- Open Output > ESLint
- Execute command `ESLint: Restart ESLint Server`

Observe:

- the combo box shows a different output panel. I my case `Tasks` which is empty
- the view content is still from the ESLint Server, but the old log content
- if you select ESLint again you see the new content

When restarting a ESLint server the ESLint output channel is disposed and re-created.

**Comment by dbaeumer** [comment]
![cast](https://user-images.githubusercontent.com/1931590/147923005-1ad83130-2e31-4d09-b580-fa98975e19d3.gif)

**Comment by sandy081** [comment]
@dbaeumer Output channel is switched because the current visible channel is disposed/removed. It is not switched back if it is created/added again. May I know why are you disposing the channel?

**Comment by sandy081** [comment]
Fixed that disposing the channel switches to the first channel and content also gets updated correctly. 

@dbaeumer I am still not sure why you are disposing the channel.

**Comment by dbaeumer** [comment]
I will look into not doing it. Might be to start fresh since I have a fresh server.

**Comment by sandy081** [comment]
You can clear the output channel if you want to start fresh.
