### ISSUE TITLE
failed to save Index.html unable to write file f:/geoserver/webapps/appliation error unnwon 

### ISSUE THREAD

**Issue by Narendra97gisDEV** [microsoft/vscode#140025]
I have GeoServer installed on Windows 10 as part of the Openlayer . It's working well and I have just started creating my own app using it.

I have created an html file in \WebAppslapps and can view it via localhost:8080. My problem is that once I have viewed the file in a browser it becomes locked and I can't save over it. In any editor such as VISUAL STUDIO, atom, notepad etc.

Is there a fix?

**Comment by JacksonKearl** [comment]
As you noted, this isn't specific to VS Code. Perhaps ask the maintainer of the web server you're using?
