### ISSUE TITLE
when clause for view/item/context not automatically reevaluated

### ISSUE THREAD

**Issue by yuyichao** [microsoft/vscode#140010]
Does this issue occur when all extensions are disabled?: Yes and No (because an extension is required to construct the situation.)

- VS Code Version: 1.62.0 and source build from latest main branch.
- OS Version: Linux (also web version)

Steps to Reproduce:

1. Create a contribution to the `view/item/context` menu with a custom condition, e.g. `"when": "view == myextension.view && myextension.should_show"`. (I've only tested the inline group)
2. After the view is shown, change the value of `myextension.should_show` in the extension.
3. The visibility of the button does not change.

For a contributed view from the same extension, this can be worked around by triggering a refresh of the whole view (by firing `onDidChangeTreeData`) but there doesn't seem to be a way to do this if the view is from somewhere else... The automatic update works in most other places I've tried...

**Comment by jrieken** [comment]
Please attach a small/minimal sample extension that reproduces this

**Comment by yuyichao** [comment]
Please find the extension at https://github.com/yuyichao/test-ext

The extension has one custom context: `test-ext.running`, two commands `test-ext.start` and `test-ext.pause` that sets the running context to true and false respectively.

The two commands are added as menu items to the editor context and the tree view item context with the same conditions (the tree view one has additional check for view id) that the play button is visible when running is false and the pause button is visible when running is true.

Clicking the play button causes the editor context one to change to the pause button as expected but the tree view one does not change. If you set the global flag in `extension.js` to `true`, however, this will fire the onDidChangeTreeData event for the tree data provider everytime the context value is change which fixes this issue.

**Comment by yuyichao** [comment]
I assume the needs-more-info label can at least be removed? Or is there any other information needed?

**Comment by alexr00** [comment]
No further information, I just hadn't tried out your sample yet. Thank you for the easy repro!

**Comment by alexr00** [comment]
After investigating, this is as-designed. Re-rendering each extension provided tree each time one of the contexts that it's actions depend on change could be expensive and leak menus.

**Comment by yuyichao** [comment]
> Re-rendering each extension provided tree each time one of the contexts that it's actions depend on change could be expensive and leak menus.

Also, regarding this, two questions,

1. If a context is changed, why would the the user/developer **NOT** want the item that depends on it to be reevaluated?
2. Having to redraw the whole tree "each time one of the contexts that it's actions depend on change" is actually the current behavior, not the expected behavior. The expected behavior is exactly to avoid having to do this expensive action.

To be clear, I'm not, in my original report, suggesting that doing the equivalent of firing `onDidChangeTreeData` is the correct fix. That's merely a workaround, and it only works for view from the same extension. I am suggesting, however, that when the context value have changed, the buttons, and only the buttons should be redrawn, without redrawing the whole tree view or calling any methods from the tree item provider. I don't see how this can cause a leak in the menus.

**Comment by alexr00** [comment]
I also did not like my previous answer. Still investigating...

**Comment by rchiodo** [comment]
/verified

Using @yuyichao's test extension. In insiders it will switch buttons just by clicking the button:

![image](https://user-images.githubusercontent.com/19672699/155626341-11828156-d349-4806-ac1f-f8fbe5eea965.png)
