### ISSUE TITLE
A couple of minor issues when running from WSL

### ISSUE THREAD

**Issue by SteveALee** [microsoft/vscode#140087]
Issue Type: <b>Bug</b>

I'm excited to find when I run `code .` in WSL on Windows 11 it runs code in WSL and not WIndows with remote debugging. However a few of points

- default integrated shell is Powershell not WSL Ubuntu (say) and I can't see how to change for WSL on windows (not Linux)
- Updates to the view like type script errors seem to take a long time

Thanks for all the excellent work.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (4.97GB free)|
|Process Argv|. --crash-reporter-id d4f7b7d4-f906-432a-a781-81f25dff1b73|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
astro-vscode|ast|0.8.5
vscode-markdownlint|Dav|0.45.0
vscode-versionlens|pfl|1.0.9
svelte-vscode|sve|105.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710cf:30416617
py55gd98:30411514
vscexrecpromp3t1:30407762

```

</details>

**Comment by aeschli** [comment]
> default integrated shell is Powershell not WSL Ubuntu

This depends on the type of window. In a WSL window (as seen in the lower left corner) you get a Linux terminal.
In a local window, it's Powershell by default.

The idea is that when working in WSL, you open a WSL window, with terminal and the all extensions running in Linux.

> Updates to the view like type script errors seem to take a long time

Please add more details and steps to reproduce, e.g. a screencast. Are you working on a `/mnt/...` drive?

**Comment by SteveALee** [comment]
@aeschli Thanks, I think my expectations may be wrong and I;m not sure how to check which version of code is running. Basically I very confused about what context code is running in.

- Open WSL in terminal 
- go to to a WSL folder - eg ~/project
- run `code .`

The VS code i get was running a clean new config (eg no extensions as set in the Pre Windows 11 launched WSL version using code .) As this is WSLg on windows 11 I assumed the code was now running using WSL context and X11 windows (or whatever Linux uses these days and is now supported for WSL GUI apps) and not the WIn64 (?) version.

However it use powershell as the default I hit a number of problems including those mentioned and any attempt to delete files tries to save to recycle which fails and it offers to permanently delete.

To add to the confusion I tried and the remote WSL extension as I had to used before windows 11 upgrade  and all the problems went away.

All very confusing to be honest.

Do we run the windows version of code or WSLg now?

**Comment by aeschli** [comment]
Ah, I see. You don't have the `Remote-WSL` extension installed. In your setup all tools run on the Windows side, just using the WSL file system.
Remote WSL is very likley what you want: https://code.visualstudio.com/docs/remote/wsl

You should have gotten a recommendation for the extension. Maybe you clicked it away?
