### ISSUE TITLE
Screen reader reads extension's <publisher>.<name> at top of extension settings page

### ISSUE THREAD

**Issue by tgriff** [microsoft/vscode#140045]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Win11 22000.376

Steps to Reproduce:

1. Open VSCode.
2. Open the Settings page and expand the "Extensions" item.
3. Turn on your screen reader (I'm using Windows Narrator).
4. Select an extension from the tree.
5. Hit tab to move focus to the extension's settings page.
6. Focus will move to a top-level element (which isn't really visible). Note that this is distinct from name of the extension at the top of the settings page.
7. Narrator will announce the extension's "<publisher>.<name>".

Expected result:
I think ultimately the element shouldn't be focusable as it causes the screen reader to announce some text that isn't actually there.

![settings_header_repro](https://user-images.githubusercontent.com/34492055/147957701-970d0abd-557c-425d-a50f-5cc2b56781f3.gif)

**Comment by Shivamd1** [comment]
GithubTags:#A11yMAS;#a11y-partner;
