### ISSUE TITLE
Typescript "as type" annotation causes a parsing error

### ISSUE THREAD

**Issue by danielo515** [microsoft/vscode#140058]
Issue Type: <b>Bug</b>

Acan see on the screenshot, VSCode complaints about an object property being annotated.
TSC works well, this only happens within VSCode.

![image](https://user-images.githubusercontent.com/2270425/147971954-8ceb2925-200a-44b6-9cb4-2514cd52f52a.png)

Of course the file is set as typescript, using workspace typescript.
Here is the tsconfig if it helps:

```jsonc
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig.json to read more about this file */
    "target": "ESNext" /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */,
    "module": "commonjs" /* Specify what module code is generated. */,
    "lib": [
      "ESNext",
      "DOM"
    ] /* Specify a set of bundled library declaration files that describe the target runtime environment. */,
    "jsx": "react" /* Specify what JSX code is generated. */,

    /* Modules */
    // "rootDir": "./",                                  /* Specify the root folder within your source files. */
    // "moduleResolution": "node",                       /* Specify how TypeScript looks up a file from a given module specifier. */
    "baseUrl": "./src",
    "paths": {
      "rootReducer": ["common/rootReducer"],
      "@common/*": ["common/*"],
      "formatters": ["formatters"],
      "@types": ["types"]
    } /* Specify a set of entries that re-map imports to additional lookup locations. */,
    "types": ["vite/client"],
    "resolveJsonModule": true /* Enable importing .json files */,

    /* Emit */
    "noEmit": true /* Disable emitting files from a compilation. */,
    /* Interop Constraints */
    "esModuleInterop": true /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables `allowSyntheticDefaultImports` for type compatibility. */,
    "forceConsistentCasingInFileNames": true /* Ensure that casing is correct in imports. */,

    /* Type Checking */
    "strict": true /* Enable all strict type-checking options. */,
    "noImplicitAny": false /* Enable error reporting for expressions and declarations with an implied `any` type.. */,
    // "strictNullChecks": true,                         /* When type checking, take into account `null` and `undefined`. */
    // "strictFunctionTypes": true,                      /* When assigning functions, check to ensure parameters and the return values are subtype-compatible. */
    // "strictBindCallApply": true,                      /* Check that the arguments for `bind`, `call`, and `apply` methods match the original function. */
    // "strictPropertyInitialization": true,             /* Check for class properties that are declared but not set in the constructor. */
    // "noImplicitThis": true,                           /* Enable error reporting when `this` is given the type `any`. */
    // "useUnknownInCatchVariables": true,               /* Type catch clause variables as 'unknown' instead of 'any'. */
    // "alwaysStrict": true,                             /* Ensure 'use strict' is always emitted. */
    // "noUnusedLocals": true,                           /* Enable error reporting when a local variables aren't read. */
    // "noUnusedParameters": true,                       /* Raise an error when a function parameter isn't read */
    // "exactOptionalPropertyTypes": true,               /* Interpret optional property types as written, rather than adding 'undefined'. */
    // "noImplicitReturns": true,                        /* Enable error reporting for codepaths that do not explicitly return in a function. */
    // "noFallthroughCasesInSwitch": true,               /* Enable error reporting for fallthrough cases in switch statements. */
    // "noUncheckedIndexedAccess": true,                 /* Include 'undefined' in index signature results */
    // "noImplicitOverride": true,                       /* Ensure overriding members in derived classes are marked with an override modifier. */
    // "noPropertyAccessFromIndexSignature": true,       /* Enforces using indexed accessors for keys declared using an indexed type */
    // "allowUnusedLabels": true,                        /* Disable error reporting for unused labels. */
    // "allowUnreachableCode": true,                     /* Disable error reporting for unreachable code. */

    /* Completeness */
    // "skipDefaultLibCheck": true,                      /* Skip type checking .d.ts files that are included with TypeScript. */
    "skipLibCheck": true /* Skip type checking all .d.ts files. */
  }
}

```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.39GB free)|
|Process Argv|. --crash-reporter-id 3bf10e6d-54c9-4df4-8aaa-781f2b9fc1b9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (112)</summary>

Extension|Author (truncated)|Version
---|---|---
yaml2json|ahe|0.0.3
project-manager|ale|12.4.0
auto-add-brackets|ali|0.12.0
jest-snippets|and|1.8.0
vscode-apollo|apo|1.19.9
gitstash|art|5.1.0
find-and-transform|Art|0.9.81
material-ui|Aru|1.0.0
vscode-django|bat|1.8.0
unique-lines|bib|1.0.0
file-browser|bod|0.2.10
better-toml|bun|0.3.2
rescript-vscode|che|1.1.3
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.6.0
keymapceditor-vsc|Cia|0.7.7
vscode-devtools-for-chrome|cod|0.0.7
systemd-unit-file|coo|1.0.6
doxdocgen|csc|1.3.2
vscode-svgviewer|css|2.0.0
python-snippets|cst|0.1.1
danielo-node-snippets|dan|1.8.13
danielo-vsc-tools|dan|1.0.3
vscode-eslint|dba|2.2.2
javascript-ejs-support|Dig|1.3.1
vs-code-snippet-generator|dku|1.1.0
githistory|don|0.6.19
python-extension-pack|don|1.7.0
jest-test-language-support|dpl|1.30.2
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
vscode-powertools|ego|0.64.0
prettier-vscode|esb|9.1.0
esy-vscode|esy|0.0.2
vscode-search-open-all-results|fab|1.0.3
vimL|fal|0.0.3
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.9
reasonml|fre|1.0.38
vscode-extension-react-ts-snippets|fun|1.2.0
monkey-c|ghi|0.4.0
lintlens|ghm|3.0.0
copilot|Git|1.7.4421
vscode-pull-request-github|Git|0.34.2
go|gol|0.30.0
vscode-graphql|Gra|0.3.41
align-mode|Gru|0.0.21
ansible|haa|0.2.8
vscode-nginx-conf-hint|han|0.3.0
githd|hui|2.2.4
customize-ui|ioc|0.1.55
monkey-patch|ioc|0.1.16
fuzzy-search|jac|0.0.3
search-editor-apply-changes|jak|0.1.1
better-cpp-syntax|jef|1.15.10
svg|joc|1.4.15
styled-components-snippets|jon|0.10.0
open-in-vim|jon|0.6.0
tw5-syntax|jos|1.0.4
vscode-styled-components|jpo|1.6.6
magit|kah|0.6.24
vscode-home-assistant|kee|1.22.0
vsc-python-indent|Kev|1.14.2
vscode-wrap-console-log|mid|1.7.2
dotenv|mik|1.0.1
vscode-docker|ms-|1.18.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
cpptools-extension-pack|ms-|1.1.0
vscode-typescript-next|ms-|4.6.20220102
debugger-for-chrome|msj|4.13.0
vscode-purty|mva|0.6.0
autodocstring|njp|0.5.4
indent-rainbow|ode|8.2.2
docthis|oou|0.8.2
python-string-sql|ptw|1.1.0
geo-data-viewer|Ran|2.5.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.2
partial-diff|ryu|1.4.3
jinjahtml|sam|0.16.0
vscode-javascript-booster|sbu|14.0.1
bash-beautify|sha|0.1.1
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.4.5
code-spell-checker|str|2.0.14
code-spell-checker-spanish|str|2.0.4
vscode-stylelint|sty|1.2.1
control-snippets|svi|1.9.1
open-spec-file|the|0.0.6
errorlens|use|3.4.1
highlight-matching-tag|vin|0.10.1
template-strings|vit|0.0.6
vscode-icons|vsc|11.8.0
material-ui-snippets|vsc|3.3.8
vim|vsc|1.21.10
vspacecode|VSp|0.10.5
whichkey|VSp|0.11.3
literally-html|web|0.1.3
vscode-file-extra|wil|3.1.0
fig|wit|0.0.5
glean|wix|5.2.2
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.4.0
vscode-open-in-github|ziy|1.3.6
es6-string-javascript|zjc|1.0.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710:30416614
py55gd98cf:30411515
vscexrecpromp3t2:30407763

```

</details>

**Comment by orta** [comment]
This is likely from one of your extensions trying to read the file as a .js file and not recognizing typescript syntax.

**Comment by danielo515** [comment]
Is there any way to know from wich extension is this error originating?

**Comment by danielo515** [comment]
Yes, it seems to be eslint extension who complains
