### ISSUE TITLE
Add selection to next find match always adds left-to-right selection

### ISSUE THREAD

**Issue by kretes** [microsoft/vscode#140078]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-43-generic snap
```
- OS Version: ubuntu 20.04

Steps to Reproduce:

1. Select a bunch of text `from right to left` e.g. by using shift+home
2. Run `add selection to next find match` (`ctrl+g` in my case)
3. observe the cursor in the expanded selection is at the end of the text not at the begining
4. If I now run e.g. `delete line` I end up with cursors in different parts of the respective lines.
See video in which I do just these actions:

![vscode_issue](https://user-images.githubusercontent.com/1224887/148033756-ab43e9e6-cf1b-44b9-8596-7f7a42122020.gif)

**Comment by alexdima** [comment]
If you are interested in contributing a PR for this, the relevant code is at https://github.com/microsoft/vscode/blob/e7b03fb2ee2a459f93154b5d61102bc5e8aa597a/src/vs/editor/contrib/multicursor/multicursor.ts#L387
