### ISSUE TITLE
Extension search by file extension (ext:) also matches against tags

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#140050]
Spin-off from https://github.com/microsoft/vscode/issues/139321#issuecomment-1004225117.

> `ext:production` is converted this following tags filters: `__ext_production`, `__ext_.production`, `production`. MP is returning all extensions that contain at least one of these tags.

I suggest to audit if broadening the _extension_ query to _tags_ is more helpful (extensions that have defined the relevant tags but not file extension) or counter-productive (extensions are shown that have nothing to do with the searched file extension).

In case of the linked issue, I see it as more harmful. If there is no common cases where it helps to find the right extensions, I would recommend to make the query less broad by not including tags.

**Comment by sandy081** [comment]
I would appreciate if there are any constructive recommendations or suggestions.

**Comment by isidorn** [comment]
@digitarald do you have some suggestions on how to improve this? I do not unfortunetly.
We can also keep the discussion in #139321

**Comment by digitarald** [comment]
> @digitarald do you have some suggestions on how to improve this? I do not unfortunetly.

My recommendation would be to just search in the extension fields, but not including the _tag_ in the search, so resolving `ext:example` is resolved into `__ext_example`, `__ext_.example`, but not adding ~`example`~ (using the format from the original comment https://github.com/microsoft/vscode/issues/139321#issuecomment-1004225117).

As I am not 100% familiar with the format of the marketplace search, did I capture the idea in a sensible format, @sandy081?

**Comment by sandy081** [comment]
I am not sure what will we miss if `example` tag is excluded in this case. Will there be an extension with this tag that supports this language? Actually I do not know why this was like this as it was there from beginning even before I took over. It seems we need to study what happens if we avoid this tag

**Comment by isidorn** [comment]
No action items I see from this item thus closing.
We can reopen in the future if we figure out what to do here
