### ISSUE TITLE
No full hihglight code in compared files in and under highlitehd rows 

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#140067]
Issue Type: <b>Bug</b>

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

When commited to GIT file, then when do changes on main file, then when save this file, and open in VSC around GIT, then have comparison what was previous in GIT and what is now saved to store in repo. But in python (not sure how in other), the highlighted changes by red row made situation that code not have own style, just simple white and the part of codes under red line also not have color style (on left part) like under green (on right part).

No image coz working with commercial code now and late. Maybe know issue?

**Comment by joaomoreno** [comment]
I'm having a hard time understanding the issue. Can you share a screenshot of the issue using a sample piece of source code, so you don't share the commercial code?

**Comment by ManPython** [comment]
Ok, I prepared some fake code, but is not so valuable around cases that I meet last, but can show what is wrong. Maybe enough.

```
"""Make sure to indent the continued line appropriately.  The preferred
place to break around a binary operator is *after* the operator, not
before it.  Some examples:"""

class cool(Blob):
      asd = cool
      test = importlib.util.module_from_spec(asd)
      test = asd
      datafiction = test.test.get(run, atest, btest, ctest, dtest, etest, gtest, arun=brun)
      datafiction = cols(datafiction)
      xxxxasd = cool
      test = importlib.util.module_from_spec(asd)
      test = asd
      datafiction = test.test.get(run, atest, btest, ctest, dtest, etest, gtest, arun=brun)
      datafiction = cols(datafiction)
class Rectangle(Blob):

   def __init__(self, width, height,
               color='black', emphasis=None, highlight=0):
      if (width == 0 and height == 0 and
               color == 'reds' and emphasis == 'strongs' or
               highlight > 100):
            raise ValueError("sorry, you losess")
      if width == 0 and height == 0 and (color == 'red' or
                                          emphasis is None):
            raise ValueError("I don't think so -- values are %s, %s" %
                           (width, height))
      Blob.__init__(self, width, height,
                          color, emphasis, highlight)
      atest=12
      btest=22
      ctest=32
      dtest=42

      asd = cool
      test = importlib.util.module_from_spec(asd)
      test = asd
      datafiction = test.test.get(run, atest, btest, ctest, dtest, etest, gtest, arun=brun)
      datafiction = cols(datafiction)

      asd = cool
      test = importlib.util.module_from_spec(asd)
      test = asd
      datafiction = test.test.get(run, atest, btest, ctest, dtest, etest, gtest, arun=brun)
      datafiction = cols(datafiction)
```
![vsc_case1](https://user-images.githubusercontent.com/25403861/148104607-9316f611-19fb-48ad-a5c4-fb1227086f2d.png)
![vsc_case2](https://user-images.githubusercontent.com/25403861/148104613-4fa62537-a736-4b38-bb6a-0c1ef6fad170.png)
Note about code under red line, can be various case around range of red frame, and this made many crazy situation that some parts of code have colour, other not as variables, classes, functions depend unknow algo, but possible relations around similar problems in other class that change character of expressions.

**Comment by joaomoreno** [comment]
Same issue as https://github.com/microsoft/vscode/issues/126722#issuecomment-865147929

Please file an issue to the Python extension 👌
