### ISSUE TITLE
Recently Opened files list is broken and doesn't show recently opened files

### ISSUE THREAD

**Issue by ttodua** [microsoft/vscode#140076]
It's a bit astounding for me, that this obvious misbehavior and annoying issue has never been reported and requested by mass of users. The only topic I find is dated 3 years ago ( https://github.com/microsoft/vscode/issues/49629 ) and was right away closed, without leaving us a room to 'upvote' for Feature request.

The problem is that VSCODE never ever really shows recently opened files in `Open Recent` files list. It's straightforward to reproduce it - just open any other file in VSCode and close it - you will not find out that in `Open Recent` and moreover, it's quite strange from where those useless list of "recent files" come from. The idea of "recent files" is to show recently closed files, like it is perfectly working in `Notepad ++` and everybody who has used N++ knows this.

(I know the imperative approach of software vendors, so I don't say this should be changed directly, but at least, give us an option to show 'really recently closed files' instead of current behavior of VScode)

**Comment by bpasero** [comment]
This list is filled only with files that are opened via specific UI points:
* file dialogs
* drag and drop files that are outside of the workbench

It is not a list of every editor you open and close, for that there is a editor history: `Cmd+O`

**Comment by ttodua** [comment]
at first, I assume with `cmd+o` you might meant for Mac users (sorry, i've not mentioned, I am Windows user), and I can't reproduce what you say with any combination on Windows. (neither found how to open "editor history" from google, however, found an unassigned one in "keyboard shortcuts" named "Quick open pervious editor from History", which seems to achieve that ).
second, as I said, it would be good if there was option to override "Open recent" behavior or even, you added "Open History" after "Open recent". 
thanks

**Comment by bpasero** [comment]
`Ctrl+O`?

**Comment by bpasero** [comment]
Ah yeah it is `Ctrl+E` by default on Windows.
