### ISSUE TITLE
Weird `import vs/platform/workspace/common/workspaceTrust`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#140043]
There is a import that does not have `registerSingleton`:

https://github.com/microsoft/vscode/blob/e8838f10628a63ca0c9d73fbedabfd35d6abf2cb/src/vs/workbench/workbench.common.main.ts#L54

This import only seems to contain types. Why was it added then?

**Comment by sbatten** [comment]
at the time of committing that line, there was a `registerSingleton` call in the file. It has since been removed and this line can be safely removed.

**Comment by lszomoru** [comment]
Sorry about that. Removed the import in 25553c854db21b3ca9a0cabf1ba88e86076c7919
