### ISSUE TITLE
Add an undo/redo stop at end of snippet

### ISSUE THREAD

**Issue by ShafinKhadem** [microsoft/vscode#140094]
Curently there's no undo/redo stop at end of snippet (when the snippet reaches its last placeholder). In my opinion, having an undo/redo stop at end of snippet is better. See the following comparison.

**Current:**
![before](https://user-images.githubusercontent.com/26321479/148076790-7228485f-89bd-445c-a57c-548e71bc6717.gif)

**Expected:**
![after](https://user-images.githubusercontent.com/26321479/148076895-2e2fb601-e408-4f76-bb7d-699ddb4ad1e1.gif)

**Comment by jrieken** [comment]
This is already handled on a per-case basis: https://github.com/microsoft/vscode/blob/973684056e67153952f495fce93bf50d0ec0b892/src/vs/editor/contrib/snippet/snippetController2.ts#L127

**Comment by ShafinKhadem** [comment]
@jrieken if I understand correctly, the line that you linked inserts a stop just after inserting a snippet. I am talking about adding a stop when the snippet reaches its end / last placeholder.

**Comment by jrieken** [comment]
Understood. Thanks for helping me. Sounds reasonable tho needs a little thinking if this affects some use-case.
