### ISSUE TITLE
can't use keyboard when debug progam

### ISSUE THREAD

**Issue by LawsonAbs** [microsoft/vscode#140005]
Issue Type: <b>Bug</b>

I can't use some key when I debug my program, my vscode version is 1.63.2. What should I do?

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.15.0-163-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.26GB free)|
|Process Argv|--crash-reporter-id d13afac7-296a-4abb-ab5f-2f4dfd220064|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: bleu|
|OS|Linux x64 4.15.0-163-generic|
|CPUs|AMD EPYC 7502 32-Core Processor (128 x 1498)|
|Memory (System)|503.82GB (51.48GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-rename-tag|for|0.1.9
vscode-language-pack-zh-hans|MS-|1.63.3
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
open-in-browser|tec|2.0.0
vscode-todo-highlight|way|1.0.5
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
color-highlight|nau|2.5.0
markdown-preview-enhanced|shd|0.6.1
markdown-pdf|yza|1.4.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710:30416614

```

</details>

**Comment by LawsonAbs** [comment]
for example, I can't use the key "Backspace" when I debug the program.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

People use VS Code to code and debug programs in may languages. Please provide more information.

**Comment by LawsonAbs** [comment]
> /needsMoreInfo
> 
> People use VS Code to code and debug programs in may languages. Please provide more information.

The language is Chinese, thanks

**Comment by gjsjohnmurray** [comment]
> The language is Chinese, thanks

Coding language, not spoken language.
