### ISSUE TITLE
Workspace .env file setting is not respected after loosing the remote ssh connection

### ISSUE THREAD

**Issue by pmercatoris** [microsoft/vscode#140075]
Issue Type: <b>Bug</b>

I have an environemnt file (Python: Env File) that I set in the settings as ${workspaceFolder}/.myenv 

However, when loosing my ssh remote connection (when computer sleeps), the environment defaults to another environment file (.env in the same folder). The only way I can fix this, is by reopening that remote VSC window.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1058-gcp

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 6, 6|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: do_etls|
|OS|Linux x64 5.4.0-1058-gcp|
|CPUs|Intel(R) Xeon(R) CPU @ 2.20GHz (8 x 2200)|
|Memory (System)|31.36GB (23.52GB free)|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
file-browser|bod|0.2.10
remotehub|Git|0.20.0
fuzzy-search|jac|0.0.3
codeacejumper|luc|3.3.2
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
vim|vsc|1.21.10
vspacecode|VSp|0.10.5
whichkey|VSp|0.11.3
file-browser|bod|0.2.10
githistory|don|0.6.19
fuzzy-search|jac|0.0.3
magit|kah|0.6.24
codeacejumper|luc|3.3.2
vscode-docker|ms-|1.18.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
vspacecode|VSp|0.10.5
whichkey|VSp|0.11.3

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@pmercatoris I believe this issue should be discussed in the python extension repository. https://github.com/Microsoft/vscode-python
