### ISSUE TITLE
Embedded terminal scroll reset

### ISSUE THREAD

**Issue by TPdiegolopez** [microsoft/vscode#140061]
Issue Type: <b>Bug</b>

Very often the terminal ouput state (scroll) gets reset after a little stuck. I usually use terminal to run a sort of maven commands which produces a lot of  output lines and when I focuse the terminal again, it gets stuck for a moment and then the scroll position gets reset at the beggining of the output (but was at the end).

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz (2 x 2295)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|12.00GB (3.98GB free)|
|Process Argv|C:\\TripServices\\reservation-domain-payment-1p --crash-reporter-id 70108000-701a-4d33-abe6-351ff1fe3961|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
clipboard-history|Anj|1.0.7
http-status-codes|bea|1.0.2
vscode-simpler-icons|dav|1.6.5
macos-modern-theme|dav|2.1.9
vscode-dash|dee|2.4.0
java-decompiler|dgi|0.0.2
gitlens|eam|11.7.0
eppz-code|epp|1.2.52
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
vscode-firefox-debug|fir|2.9.6
todo-tree|Gru|0.0.214
helium-icon-theme|hel|1.0.0
theme-monokai-pro-vscode|mon|1.1.19
csharp|ms-|1.23.17
live-server|ms-|0.2.11
sqltools|mtx|0.23.0
sqltools-driver-mysql|mtx|0.2.0
gradle-language|nac|0.2.3
vscode-boot-dev-pack|Piv|0.1.0
vscode-spring-boot|Piv|1.29.0
material-icon-theme|PKi|4.11.0
fabric8-analytics|red|0.3.5
java|red|1.2.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.2
vscode-gradle-extension-pack|ric|0.0.4
synthwave-vscode|Rob|0.1.10
gruvbox-material|sai|6.5.0
jshelleasy|Sen|1.0.1
java-generate-setters-getters|soh|7.4.0
sonarlint-vscode|Son|3.1.0
vscodeintellicode|Vis|1.2.15
vscode-gradle|vsc|3.9.0
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.8.0
vscode-icons|vsc|11.8.0
vscode-icons-mac|way|7.25.3
change-case|wma|1.0.0
local-history|xyz|1.8.1
material-theme|zhu|3.13.9

(21 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710cf:30416617
vscexrecpromp3t2:30407763

```

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
