### ISSUE TITLE
Shift + Enter ignores editor setting editor.acceptSuggestionOnEnter and always accepts autocomplete suggestions

### ISSUE THREAD

**Issue by FOMX** [microsoft/vscode#140063]
## Environment data

-   VS Code version: 1.63.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Pro
-   Python and/or Anaconda version: Python 3.10.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

With the setting "editor.acceptSuggestionOnEnter" set to OFF 
and a code completion suggestion available
Shift+Enter should run the current cell and NOT accept the autocomplete suggestion. 

More generally all variations of "Enter", (Enter, Ctrl+Enter, Alt+Enter, Shift+Enter) should not accept the autocomplete suggestion.

## Actual behaviour

With the setting "editor.acceptSuggestionOnEnter" set to OFF 
and a code completion suggestion available
Shift+Enter accepts the autocomplete suggestion and does not run the current cell.

The other variations of Enter (Alt+Enter, Enter, and Ctrl+Enter) all ignore the autocomplete suggestion and perform their respective functions. 

This is the same issue from /issues/2578 which, according to the ticket was planned to be included in the new notebook UI. @IanMatthewHuff mentioned back in October 2020 that it was working in the preview at the time, but it seems that "Shift+Enter" has slipped through at some point. 

![ezgif-7-169de0c50b](https://user-images.githubusercontent.com/20251588/147926321-04878d9c-ad22-49b9-af66-320e5c6b9cc8.gif)

## Steps to reproduce:

1. Set the setting "editor.acceptSuggestionOnEnter" to OFF.
2. Type code in a cell to get a code completion suggestion available.
3. Press Shift+Enter to accept the autocomplete suggestion.

## Logs
N/A no output

**Comment by greazer** [comment]
Autocomplete behavior is pure vscode.

**Comment by FOMX** [comment]
Installing another extension Jupyter Keymap Extension v1.0.0 seems to overwrite the base Jupyter-notebook extension hotkey and create the expected behaviour for "Shift +Enter". [https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter-keymap](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter-keymap) 
![jupyter keymap extension](https://user-images.githubusercontent.com/20251588/150049620-8c984fca-c269-438c-89bb-77170687170c.gif)

**Comment by FOMX** [comment]
the extension seems to just add some simple keybindings. 
https://github.com/microsoft/vscode-jupyter-keymap/blob/main/package.json
```json
{
    "key": "shift+enter",
    "when": "editorTextFocus && inputFocus && notebookEditorFocused || notebookCellListFocused && notebookCellType == 'code'",
    "command": "notebook.cell. "
}
```

**Comment by DonJayamanne** [comment]
@rebornix assigning to you as this was assigned to me when this was transferred.

**Comment by rebornix** [comment]
I'm no longer reproducing this issue in latest build, closing for now but we can reopen if you are still seeing it.
