### ISSUE TITLE
Odd spacing with SCM action button

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#140027]
See attached screen capture. The action button seems to be intended by some margin and that look odd

<img width="441" alt="Screen Shot 2022-01-03 at 10 19 04" src="https://user-images.githubusercontent.com/1794099/147915440-e2ad49f0-2954-4b7a-82fa-18bad94bf38b.png">

**Comment by lszomoru** [comment]
@jrieken do you still have a repro of this one? I cannot seem to be able to reproduce it.

**Comment by jrieken** [comment]
Yeah, I still see this... Maybe because I only have single view in the viewlet? Or because some SCM settings? I have these

```
"scm.defaultViewMode": "list",
"scm.alwaysShowRepositories": false,
"scm.showActionButton": true,
```

**Comment by jrieken** [comment]
This is the full picture

<img width="569" alt="Screen Shot 2022-01-06 at 16 33 29" src="https://user-images.githubusercontent.com/1794099/148407842-98461d02-562a-4d97-957a-8a35664e1e8d.png">
