### ISSUE TITLE
TSServer has no memory pressure resolution

### ISSUE THREAD

**Issue by clshortfuse** [microsoft/vscode#140090]
Issue Type: <b>Performance Issue</b>

Currently, TSServer is reliant on just Node's `max-old-space-size` command line to manage memory usage on a machine. It's currently defaulting to 3072MB of RAM, but there's no real code to manage the memory consumption of the element while in use. Most documentation I've found mostly relates to increasing this value for large projects, but there isn't a mechanism to manage or limit the memory consumption while it's in use. 

It seems heavily related to an issue many of us users are having with using remote SSH on our server deployments that don't have much memory available. Already, it's a bad idea to use a 3GB limit on a system with less than that. When TSServer starts consuming more memory than available on the system, the entire host will lock up. The "solution" is to set a limit to `typescript.tsserver.maxTsServerMemory` and just let the extension crash when it approaches that limit. It makes for a rather poor experience, but at least won't flat out crash our server instances. Also, values that are too low don't allow TSServer to even start properly so there is some sort of minimum memory requirement. The stated `128MB` is not enough.

I had personally taken a look a what may be consuming all that memory, but I wasn't able to really track down due to lack of understanding of the code structure. It seems there are lot of hard references and while the `CachedResponse` paradigm does collect items, it has no real strategy to release them or reduce when memory is pressured. I have tried `WeakRef` which is supported by the Node environment VSCode is running, but I didn't have much success. `WeakRef` probably isn't smart enough to just throw chunks out. There probably has to be some manual tooling required here to, perhaps, release based on recency of access. I would think when `.getHeapStatistics()` reports 90% of memory utilization some sort of clean up should happen.

References:

https://github.com/microsoft/vscode-remote-release/issues/2692

https://github.com/microsoft/vscode/blob/e802791cf1df891aa81c7f57dc4ca57d54c0282a/extensions/typescript-language-features/src/utils/configuration.ts#L195-L201

https://github.com/microsoft/vscode/blob/53350bc6661449bc097496b04a1d8712474bd301/extensions/typescript-language-features/src/tsServer/serverProcess.electron.ts#L184-L185

https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes

https://nodejs.org/docs/latest-v14.x/api/v8.html#v8_v8_getheapspacestatistics

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

**Comment by mjbvz** [comment]
I don't think there's anything actionable here. We don't see many crashes due to memory usage. It happens of course, but typically for projects that are exceedingly large (the VS Code codebase for example is large but still well under default the 3GB memory usage)

If you're seeing performance issues with js/ts, see this guide: https://code.visualstudio.com/docs/typescript/typescript-compiling#_working-with-large-projects

**Comment by clshortfuse** [comment]
>I don't think there's anything actionable here

That really reads pretty dismissive like you didn't read any of the comment. I already stated different strategies. At the bare minimum you shouldn't target more memory than the system is capable of using. You'll crash the system. Here's a Chrome V8 developer explaining the same:

>If heap memory consumption (i.e. live objects that the GC cannot free) exceeds the limit, V8 will crash your process (for lack of alternative), so you don't want to set it too low. Of course, if you set it too high, then the additional heap usage that V8 will allow might cause your overall system to run out of memory (and either swap or kill random processes, for lack of alternative).

>In summary, on a machine with 2GB of memory I would probably set --max-old-space-size to about 1.5GB to leave some memory for other uses and avoid swapping.

https://stackoverflow.com/questions/48387040/how-do-i-determine-the-correct-max-old-space-size-for-node-js/48392705#48392705

Why is VSCode forcefully targeting 3GB with no regards to the actual memory available on the system?

**Comment by mjbvz** [comment]
If people are seeing issues in real world use cases, we will take a look (but again, our telemetry does not suggest this is happens)

Right now however you have not provided evidence of an actual problem, just concerns. Sorry to be blunt but that's not helpful

**Comment by clshortfuse** [comment]
>If people are seeing issues in real world use cases, we will take a look (but again, our telemetry does not suggest this is happening)

>Right now however you have not provided evidence of an actual problem, just concerns. Sorry to be blunt but that's not helpful

Except that's not true at all. Again, I suggest you read my initial comment, but just in case, again:

>It seems heavily related to an issue many of us users are having with using remote SSH on our server deployments that don't have much memory available.

Here's the GitHub issue link detailing the issue:

https://github.com/microsoft/vscode-remote-release/issues/2692

Here's a collection of comments detailing it from that thread:

>I've been attempting to use the new remote VSCode feature to work with a project stored on an AWS EC2 instance. Each time I use it, it works fine for a few hours. Eventually, the whole instance stops responding. AWS indicates that the instance is unresponsive in the control panel, and I have to force-stop it. The screenshot/log feature on AWS doesn't show anything. Once I boot the instance back up, there's nothing in the logs--they just cut off at the time the instance stopped responding. I wish I had more information to give you, but I'm at a loss of how to troubleshoot this.

----

>@roblourens , its crashing on me with fresh install of vscode server on EC2. so all the extensions on the server as basically the ones that there by default. No other extension added. Funny thing is, if I go to extensions, or try to play around, the whole EC2 crashes, like there is nothing I can do to restore/access it. I have to restart the server.
One more information, although just going to extensions page makes things slow and at the verge of crashing them, I managed to get TS/JS plugin disabled, that has improved things a bit.

----

>OK I did a small test by re-typing an existing function under three
conditions for five minutes each:

>1. vscode.typescript-language-features disabled. No freezing within 5
minutes.

>2.  vscode.typescript-language-features *enabled*. Freezes within 5 minutes.
![image](https://user-images.githubusercontent.com/135116/93006864-8dd47300-f52f-11ea-9319-d710a8f10db6.png)


>3. vscode.typescript-language-features *enabled *with
typescript.disableAutomaticTypeAcquisition *disabled* (per
https://stackoverflow.com/questions/52935211/disable-tsserver-for-visual-studio-code/52936301).
Freezes within 5 minutes.
![image](https://user-images.githubusercontent.com/135116/93006859-80b78400-f52f-11ea-938e-e8f3b6b4534b.png)

----

>Is anybody having these issues with Azure? I only use EC2 and it's pretty much a guaranteed way to crash the VM. I use the Amazon Linux v1 and v2 and both have had issues.

---

>I'm pretty sure it's RAM. Opening up a project it balloons from up to 750M/979M of RAM. Closing VSCode drops it down to 164M/979M.

>I opened up VSCode again and it's ballooned to 754M again. The biggest culprit is extensions/node_modules/lib/tsserver.js. I don't think the issue is so much the TS server itself at is is the lack of memory limit whatsoever. It'll consume memory as it sees fit until it halts the system. At this point, just opening a project leaves me ~170M to work with.

----

>I am experiencing the same issue with SSH Remote plugin when connecting to my AWS Lightsail instances.

>My main instance (3GB RAM) stalls and becomes unresponsive within a few minutes after connection has been established. Command “htop” shows about a dozen or so identical vs-code-server processes that gradually fill up the RAM usage bar until all 3GB are used up and the instance becomes unresponsive.

---

>Unfortunately that's not much of a solution for those of us working in typescript/javascript

>That said, the typescript server has been a scourge on my existence for a while. My old macbook air with 8gb of ram couldn't really handle a large react project due to the typescript engine hogging all the resources. I'm still pretty green in the industry so forgive me if this is a silly question, but is it possible that vscode's implementation of the server is bugged, watching directories outside the project root, or something similar?

---

>I hate to "me too" but I must add that this exact same behavior is hitting us in GCP. It mirrors everything described above.

---

>Can confirm has been happening to my team for months on a variety of EC2s running Ubuntu (at different versions and on different instance sizes).

---

>Hey everyone. Thanks for all the comments and help. I finally could fix the problem, at least from my side.

>I had the very same problem with VSCode connecting to my EC2 instance. However, this wasn't the first time that I had VSCode running with an EC2, and the other server that I had, was running smoothly. What was the difference between my old server (that is actually still running) and the new one? That in the old one, I was running an Apache server with only PHP code, so basically, I was only using VSCode for setting files and PHP.

>I created a new server, started writing PHP again and everything was going fine. The problem came when I started writing JS code in a Node.js, and suddenly became very slow and began crashing, just with the same symptoms described above.

>So, it looks like VSCode has an extension built-in in a release called "TypeScript and JavaScript Language Features" but you can find it easily by looking at the extensions box and writing: "@Builtin typescript". Find it and disable it and you'll be just fine.

----

>Yeah, I think we'd pretty much established that the problem was from the TS and JS features hogging too much memory, but unfortunately, disabling that makes for a pretty lousy development experience. It would be much more ideal if the problem itself could be remedied instead of sacrificing the quality of the experience.

----

>I had this same issue. The way to solve it is to disable the built-in javascript/typescript extensions which max out the CPU and cause AWS to stall the server.

>In the extensions tab, I searched for '@Builtin' and disabled everything to do with typescript or javascript. After reconnecting, my CPU usage stayed at around 2-3% instead of spiking to 99% after a couple minutes.

**Comment by rhyek** [comment]
@mjbvz in the section https://code.visualstudio.com/docs/typescript/typescript-compiling#_make-sure-your-tsconfig-only-includes-files-you-care-about, could you clarify if that is talking about the root tsconfig.json only, or in cases of larger projects (monorepos, for example) where you can have multiple nested tsconfig files (possibly referencing the root one) are those also used?

In my case, whenever I want to rename a class or other symbol through refactor, it will take some time for vscode to find all references first. It files like there is no indexing going on before-hand.

**Comment by clshortfuse** [comment]
@mjbvz Please respond. You asked for evidence:

>Right now however you have not provided evidence of an actual problem, just concerns.

And I have provided it last week. If after this, the team is not still willing to help work out issues, at least say so, so we can move on to finding our own solution.
