### ISSUE TITLE
API to get `viewColumn` for a notebook

### ISSUE THREAD

**Issue by pokey** [microsoft/vscode#140097]
For any editor that represents a cell in a notebook, I'd like to be able to determine the view column of the containing notebook.  Today, calling `editor.viewColumn` on the editor for the given cell just returns `undefined`, exactly as described in the docs, but it would be useful if I could say eg `notebook.viewColumn`.  I need this feature so that I can focus the notebook using eg `workbench.action.focusFirstEditorGroup`

**Comment by pokey** [comment]
Are you open to a pull request?

**Comment by mjbvz** [comment]
Yes you can use `NotebookEditor.viewColumn` for this

If you're starting with a `NotebookDocument`,  first iterate through `visibleNotebookEditors` to find the editor for the current document (if one exists)
