### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by venkatapidikiti** [Microsoft/vscode#14004]
- VSCode Version:1.6.1
- OS Version: Windows 8.1

Steps to Reproduce:
Pre-requistes : Admin access to install VS 2015 ,CODE
1. Install VS2015 community edition with default settings at C drive
2. Install VS Code at E drive
3. Now trying to install NET Core 1.0.1 - VS 2015 Tooling Preview 2 

![microsoft netcore1 0 1error](https://cloud.githubusercontent.com/assets/11817148/19526981/f31244ee-9643-11e6-86f2-304f0e3280a1.jpg)

**Comment by roblourens** [comment]
This site is for Visual Studio Code which is a different product than Visual Studio. Please find support at https://www.visualstudio.com/support/.

**Comment by venkatapidikiti** [comment]
Dear Rob,

I’d like to thank you for response. I have mentioned issue for “Microsoft Visual Studio Code” as I am unable to install “Microsoft Visual Studio Code Preview tools”.

Venkatta

**Comment by roblourens** [comment]
It looks like you're unable to install ".NET Core VS 2015 Tooling Preview" which is for VS, not VS Code. The steps did say you installed VS Code, but it shouldn't affect installing VS.
