### ISSUE TITLE
Small problems with terminal icons showing up

### ISSUE THREAD

**Issue by RobFosterNYC** [microsoft/vscode#140020]
Can someone please explain to me, why icons are broken in VS-Code terminal using powershell in the terminal,
But when using Powershell on windows itself, everything is fine and all the icons works ??

**Here is how it should look as an Example**:

![Screenshot_83](https://user-images.githubusercontent.com/18384135/147891123-ada6398b-4e21-4589-b380-c5ab6b96446f.jpg)

But in VS-Code this is how the terminal looks.

![Screenshot_84B](https://user-images.githubusercontent.com/18384135/147891153-4717e539-6c1f-467a-bd92-e073b4fca0f4.jpg)

I am using the latest Nerd Fonts.
https://github.com/ryanoasis/nerd-fonts 

as well as th latest of Oh-My-Posh
https://github.com/JanDeDobbeleer/oh-my-posh2

as well as the latest of Terminal Icons
https://github.com/devblackops/Terminal-Icons

And I tried using the latest from microsoft font itself 
https://github.com/microsoft/cascadia-code/releases/tag/v2111.01

Someone please explain to me what am I missing here??
Thanks.

**Comment by Tyriar** [comment]
Did you configure vscode to use your font? https://code.visualstudio.com/docs/editor/integrated-terminal#_can-i-use-powerline-fonts-in-the-integrated-terminal

Also I see there's a guide at https://github.com/devblackops/Terminal-Icons#tips to look investigate this.

**Comment by RobFosterNYC** [comment]
Aaah ok,   so icons that dont show and look broken is normal behavior.  Ok got it.
I didn't know that its normal behavior.  No problem thank you.
