### ISSUE TITLE
Split editor icon

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#14002]
I have concerns about the current horizontal split editor icon

1. Looks 3D
2. Looks much fuller / thicker compared to the vertical one
3. it should be like the vertical one rotated by 90 degrees (with the title staying on top)

FYI @bpasero

**Comment by bpasero** [comment]
@bgashler1 also see my notes on Slack that I reported yesterday.

**Comment by bgashler1** [comment]
Have no fear.  I and the icon team agreed as well.  Posting an updated icon here.
[HorizontalSplitIcons.zip](https://github.com/Microsoft/vscode/files/539686/HorizontalSplitIcons.zip)

It's exactly the same weight now as the previous one.
![horizontal-split-02_with-icons](https://cloud.githubusercontent.com/assets/11839736/19528931/cdbdfee2-95e2-11e6-9656-9f8fb5d8c02b.png)

Previously the icon was trying to convey that there would be literally 2 title bars, but it ended up making it look too heavy.

**Comment by bgashler1** [comment]
Assigning to Ben to put in the product.

**Comment by bpasero** [comment]
Thanks, pushed 👍
