### ISSUE TITLE
Rename input box should adjust width according to input

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14007]
- VSCode Version: 1.7
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Rename something
2. Enter something long

![image](https://cloud.githubusercontent.com/assets/4033249/19529141/9bb8a540-95e3-11e6-9ee0-e9c5719231cf.png)

**Comment by jrieken** [comment]
It does but it has a lower limit of 20 characters to allow you to type a *longer* name then you currently have without the need to scroll. Also, the box has a frame, some padding etc which means perfect alignment without a tiny font inside (or h-scrolling) isn't possible. 

Closing as-designed
