### ISSUE TITLE
lowest option in context menu gets auto clicked when clicking on a "merged" view of a nested folders

### ISSUE THREAD

**Issue by imbdb** [microsoft/vscode#140012]
Issue Type: <b>Bug</b>

1. Create a folder `parent`
2. Create a folder `child` inside the first folder
_Now VS code will show these folders in same level with slash like `parent/child`_
3. Now hover pointer on the `child` folder and right click

Most of the time the position of right click and lowest option in menu matches and the lowest option gets auto clicked, in my case that is `Delete` which leads to serious issues

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.11.0-40-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.36GB (4.89GB free)|
|Process Argv|--unity-launch --crash-reporter-id c38b8178-c90d-4cf9-9b8d-538c75917dea|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by gjsjohnmurray** [comment]
Maybe a duplicate of #113175

**Comment by imbdb** [comment]
Closing this as people are already discussing on #113175 which is the same issue but at a different area.
This Issue is on file explorer/file list view and that issue is on file content view.
