### ISSUE TITLE
Regex search with negative lookahead alway case sensitive

### ISSUE THREAD

**Issue by usama8800** [microsoft/vscode#140000]
Issue Type: <b>Bug</b>

I have a file with a line `5 Bolts` and when I search using the sidebar with `"bolts(?!Icon|[_"])"` with match case off and regex on, nothing comes up but when I change it to `"Bolts(?!Icon|[_"])"`, it comes up. The only thing I am changing is b => B.

VS Code version: Code - Insiders 1.64.0-insider (7b9e5c32a053669d4e72f998e4fa217090c32f59, 2021-12-22T05:15:28.225Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (6.06GB free)|
|Process Argv|--crash-reporter-id c6c05c99-b628-4afc-9b44-6ec6732178f0|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
vscop804:30404766
vscop341:30404997
vsclayoutctrt:30405800
py55gd98cf:30408622
vscexrecpromp3t1:30407758
azactmsalcf:30409288

```

</details>

**Comment by ArturoDent** [comment]
I can't reproduce this in W11 and the Insiders' Build:

Version: 1.64.0-insider (user setup)
Commit: 7b9e5c32a053669d4e72f998e4fa217090c32f59
Date: 2021-12-22T05:15:28.225Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Perhaps show a gif of this not working?

**Comment by usama8800** [comment]
![Code_-_Insiders_Sr19031vdH](https://user-images.githubusercontent.com/3450518/148950100-e4934d99-a144-49d3-a878-216ce920f622.gif)

First I search with a lowercase c then with an uppercase c `Clin(?![^"]*[iI]con|[_"])`

**Comment by roblourens** [comment]
Thanks for the gif, I still can't repro though. Can you share one of the files so I can test with the exact file?

I assume that if you toggle "match case" on and off, it doesn't make a difference?
