### ISSUE TITLE
If there is a suggestions widget driven inline completion along with brackets and the user accepts it by hitting Tab, only the suggestions widget selection is accepted and the inline completion disappears

### ISSUE THREAD

**Issue by juihanamshet1** [microsoft/vscode#140176]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.64.0-insider (user setup)
Commit: 99305570d885bce929ba8f24d90f2c3ee54c5c2f
Date: 2022-01-03T12:05:41.799Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:
[pandas_sample.txt](https://github.com/microsoft/vscode/files/7816967/pandas_sample.txt)

1. Convert the .txt file attached to a .py file
2. Before
![image](https://user-images.githubusercontent.com/86270736/148269808-40ab52a7-80d1-4031-a7b6-64cce7ef5b47.png)
3. After I hit Tab, `notnull` would be accepted and the `(x)` would disappear. 

I suspect this has something to do with how the diff is calculated when brackets are present/autoclosed. 

In Python, when the inline completion contains a paren and when the paren is autoclosed by VS Code, this is the behavior. Notice that first the brackets get matched with the inline completion and THEN the inline completion disappears. 

![image1](https://user-images.githubusercontent.com/86270736/148270057-71f1009e-f5ae-429e-af99-1be1af58bf72.gif)

If I delete the closing paren, the inline completion stays and works as expected including the Tab Tab behavior. 
![image2](https://user-images.githubusercontent.com/86270736/148270070-b0a54f90-2e04-4b8c-af39-b3dd30329a45.gif)

However, I don't see the same issue in TypeScript always, for example
The prediction stays even if the bracket is autoclosed by VS Code. What's different here is that there is a semi-colon at the end of the prediction so there is text after the closing bracket. 
![image3](https://user-images.githubusercontent.com/86270736/148270075-4f131ae9-a00e-4a33-b6f0-5e03dad2fa25.gif)

**Comment by juihanamshet1** [comment]
cc @hediet

**Comment by hediet** [comment]
Thanks for reporting this!

> Notice that first the brackets get matched with the inline completion and THEN the inline completion disappears.

Can you log the requests to your inline completion provider and what it sends back?
Are you sure that when your provider is asked at `languages.apply(|)` (with `position` being at `|`), that the model returns the correct inline suggestion (with correct ranges)?

> Steps to Reproduce:

With the intellicode extension (is it already available?) or the copilot extension?

**Comment by juihanamshet1** [comment]
Hi Henning, 

I've included the text and range for each of the scenarios below. Scenario 1 and 3 are the same except 1 is in Python and 3 is in Typescript; 1 doesn't work correctly but 3 does. Do these text and range look right to you? 

This is with IntelliCode extension. 

Scenario 1
In Python, when the inline completion contains a paren and when the paren is autoclosed by VS Code, this is the behavior. Notice that first the brackets get matched with the inline completion and THEN the inline completion disappears.
Cursor position: `notNull = languages.apply(|)`
Prediction Text: `lambda x: x.notnull())`
Prediction Range: `char 34 - char 56` i.e. `()`

![image](https://user-images.githubusercontent.com/86270736/148840324-5516d8cd-6b36-44ae-97b0-8149a82f57f3.png)

Scenario 2
If I delete the closing paren, the inline completion stays and works as expected including the Tab Tab behavior.
Cursor position: `notNull = languages.apply(|`
Prediction Text: `languages.apply(lambda x: x.notnull())`
Prediction Range: `char 18 - char 56` i.e. `languages.apply(`

![image](https://user-images.githubusercontent.com/86270736/148840348-ccbe25ab-4b68-49d7-8b9a-8b2eec0cab5e.png)

Scenario 3
However, I don't see the same issue in TypeScript always, for example
The prediction stays even if the bracket is autoclosed by VS Code. What's different here is that there is a semi-colon at the end of the prediction so there is text after the closing bracket.
Cursor position: 
Prediction Text:  `"");`
Prediction Range: `char 12 - char 16` i.e. `()`

![image](https://user-images.githubusercontent.com/86270736/148840359-ddb6c568-6a6c-4391-9c2a-dfa9463e19bb.png)

**Comment by hediet** [comment]
> Prediction Range: char 34 - char 56 i.e. ()

This I don't full understand. With prediction range you mean the range that is to be replaced?  In that example, you are replacing 22 characters (56 - 34), but `()` are only two.

I think due to the complexity of this, I can help you better in a quick meeting.

**Comment by juihanamshet1** [comment]
Adding discussions from our meeting here so this issue is reopened by the bot. 

The current line is `notNull = languages.apply(|)`, the prediction is `lambda x: x.notnull())`. The cursor position is Column 35 which translates to position.character=34 I believe.

If the range to replace is set to char 34 - char 35, then the prediction does not show in grey text.

If the range to replace is set to char 34 - char 34, then the prediction shows up but the brackets don't match notNull = languages.apply(_lambda x: x.notnull())_)` where the grey text is italicized.

**Comment by juihanamshet1** [comment]
Sounds good!
