### ISSUE TITLE
Get Started - New File not working

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#140112]
Issue Type: <b>Bug</b>

When trying on `Get Started - New File` tab create file, after type name file and enter, nothings is done.
The shortcut ctr+n wokring normaly.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

**Comment by JacksonKearl** [comment]
Are you referring to this picker?
![image](https://user-images.githubusercontent.com/8586769/148105460-e35e3aa2-07d6-4bbd-b321-9e31d5cbe811.png)

**Comment by ManPython** [comment]
Yes, for me on this version not working.

**Comment by JacksonKearl** [comment]
Could you include a recording of what is happening? The expectation is that you'd click "Text File" in that picker then get an empty buffer as usual.

\gifPlease

**Comment by ManPython** [comment]
Dam... I try do record, and was sure that when have input I should type file name and extension no just push enter, the enter creating file. Also working, just wrong intuition here for me. Issue can be close or the feature here can be as enhancement to offer in input create file name and extension to change this in next steps on tab or when saving tab/file maybe.
