### ISSUE TITLE
Highlight selected indent guides

### ISSUE THREAD

**Issue by shauntrennery** [Microsoft/vscode#14017]
Enable selection of indent guides to aid navigation of long blocks of code. Color of selected indent guides to made configurable.

Example below:

<img width="600" alt="screen shot 2016-10-19 at 20 53 50" src="https://cloud.githubusercontent.com/assets/98803/19533027/6bc139d2-963e-11e6-94f8-38c184defbef.png">

**Comment by ZodmanPerth** [comment]
It would be awesome to style the guide lines as well.  Personally I prefer dotted lines to a solid line (such as the Visual Studio extension "Indent Guides").

**Comment by connor4312** [comment]
Also: allow an option to only show the indent guideline on the current block. I'm unsure how feasible that is with editor mechanics, but it would be a nice to have 😄

**Comment by rfgamaral** [comment]
I agree with both comments above. IMO, it's the tiny details like these that make for a great editor.

**Comment by jamesfancy** [comment]
I follow @ZodmanPerth and hope can custom guide color.

**Comment by freMea** [comment]
In fact here is an illustration of the issue title:

![Highlight current scope](https://camo.githubusercontent.com/bd2c08f385b598228efcd10077a7159b074dde98/68747470733a2f2f692e6769746875622d63616d6f2e636f6d2f383366333865663135643066393031323066656334666332316661623138666333616330656666632f363837343734373037333361326632663732363137373265363736393734363837353632373537333635373236333666366537343635366537343265363336663664326636383631373236313639326636393665363436353665373432643637373536393634363532643639366437303732366637363635363432663664363137333734363537323266363436663633326636343635366436663265363736393636)

In Sublime, it could be customized in the .tmTheme files like this:
```
<key>guide</key>
<string>#ffffff25</string>
<key>activeGuide</key>
<string>#DAAD59</string>
```

Pretty useful feature when you tasted it.

**Comment by neekibo** [comment]
Have a look at https://marketplace.visualstudio.com/items?itemName=SirTori.indenticator

**Comment by selrond** [comment]
I recommend [Guides](https://marketplace.visualstudio.com/items?itemName=spywhere.guides) plugin, really customizable, working as expected.
