### ISSUE TITLE
Outputting large images in cells while using the Remote SSH extension puts VS Code into an unresponsive state

### ISSUE THREAD

**Issue by simondemeule** [microsoft/vscode#140116]
When using the Remote SSH extension to connect to a machine running a local Jupyter server, outputting large images (around 1024x1024 and up) puts VS Code into an unresponsive state, either permanently or for a very long duration.

## Troubleshooting Process

I encountered this issue while working on image processing code. I tested a few things to converge on the issue:
- Slimmed down my problematic notebook to what caused the issue; image display.
- Attempted to reproduce without using the Remote SSH extension, directly on my notebook. The issue does not occur; therefore it seems this is related to how the Remote SSH extension interacts with the Jupyter extension.
- Attempted to reproduce using different image resolutions. The issue does not occur at 128x128, 512x512, but does at 1024x1024 and 2048x2048.

## Environment data

-   VS Code version: 1.63.2 (Universal)
-   Jupyter Extension version: v2021.11.1001550889
-   Python Extension version: v2021.12.1559732655
-   Remote SSH Extension version: v0.70.0
-   OS and version: macOS Catalina 10.15.7 (19H15) (client) / Ubuntu 20.04.3 LTS (GNU/Linux 5.11.0-43-generic x86_64) (server)
-   Python and/or Anaconda version: Python 3.8.10
-   Type of virtual environment used: venv
-   Jupyter server running: Local 

## Expected behaviour

Once a large-image-producing cell has been executed once:
- All cells may be executed immediately.
- The Kernel may be restarted.
- The notebook may be saved.

## Actual behaviour

Once a large-image-producing cell has been executed once:
- No cell can be executed subsequently.
- The Kernel cannot be restarted.
- The notebook cannot be saved.

These issues seem to either persist indefinitely (until VS Code is restarted), or dissipate after a long wait (30 seconds to more than a minute). Larger images tend to push things to the worse side of things. Clearing the cell output does not prevent the issue from arising.

## Steps to reproduce:

Create a virtual environment; install an appropriate Jupyter kernel along with Pillow. Grab a moderately-high-resolution PNG image (1024x1024 seems to do it reliably for me), and display it:

```
from PIL import Image
from IPython.display import display

display(Image.open("test.png"))
```

Running this cell will put VS Code into the broken state described here. 

## Logs

Here is an example where a 1024x1024 image caused a ~20 second hang. A second cell execution was requested immediately when the first one completed (timestamped `17:20:29`); Jupyter only reports receiving this request 19 seconds later (timestamped `17:20:48`). During this hang, VS Code is unresponsive, and the cell is not reported as currently executing.

```
Jupyter Extension Version: 2021.11.1001550889.
Python Extension Verison: 2021.12.1559732655.
Info 17:20:21: Experimentation service retrieved: [object Object]
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 17:20:21: ZMQ install verified.
Info 17:20:21: Freferred kernel connection found in cache .jvsc74a57bd0bb8c0256f6cd245c5b727ef2ef8d49f712fe7481b9680663e8403409cddf867f./home/simon/Unfurl/env/python./home/simon/Unfurl/env/python.-m#ipykernel_launcher
Info 17:20:21: PreferredConnection: .jvsc74a57bd0bb8c0256f6cd245c5b727ef2ef8d49f712fe7481b9680663e8403409cddf867f./home/simon/Unfurl/env/python./home/simon/Unfurl/env/python.-m#ipykernel_launcher found for NotebookDocument: ~/Unfurl/Test.ipynb
Info 17:20:21: Early registration of controller for Kernel connection .jvsc74a57bd0bb8c0256f6cd245c5b727ef2ef8d49f712fe7481b9680663e8403409cddf867f./home/simon/Unfurl/env/python./home/simon/Unfurl/env/python.-m#ipykernel_launcher
Info 17:20:21: TargetController found ID: .jvsc74a57bd0bb8c0256f6cd245c5b727ef2ef8d49f712fe7481b9680663e8403409cddf867f./home/simon/Unfurl/env/python./home/simon/Unfurl/env/python.-m#ipykernel_launcher for document ~/Unfurl/Test.ipynb
Info 17:20:21: Setting controller affinity for ~/Unfurl/Test.ipynb .jvsc74a57bd0bb8c0256f6cd245c5b727ef2ef8d49f712fe7481b9680663e8403409cddf867f./home/simon/Unfurl/env/python./home/simon/Unfurl/env/python.-m#ipykernel_launcher
Info 17:20:22: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 17:20:22: Creating controller for jupyter-notebook with interpreter ~/Unfurl/env/bin/python
Info 17:20:22: Setting setActiveController for ~/Unfurl/Test.ipynb
Info 17:20:22: KernelProvider switched kernel to id = .jvsc74a57bd0bb8c0256f6cd245c5b727ef2ef8d49f712fe7481b9680663e8403409cddf867f./home/simon/Unfurl/env/python./home/simon/Unfurl/env/python.-m#ipykernel_launcher
Info 17:20:22: Starting Notebook in kernel.ts id = .jvsc74a57bd0bb8c0256f6cd245c5b727ef2ef8d49f712fe7481b9680663e8403409cddf867f./home/simon/Unfurl/env/python./home/simon/Unfurl/env/python.-m#ipykernel_launcher
Info 17:20:22: Creating raw notebook for ~/Unfurl/Test.ipynb
Info 17:20:22: Getting preferred kernel for ~/Unfurl/Test.ipynb
Info 17:20:22: Computing working directory ~/Unfurl/Test.ipynb
Info 17:20:22: Process Execution: > ~/Unfurl/env/bin/python -m pip list
> ~/Unfurl/env/bin/python -m pip list
Info 17:20:22: Starting raw kernel env (Python 3.8.10)
Info 17:20:22: installMissingDependencies ~/Unfurl/env/bin/python
Info 17:20:22: IPykernel found previously in this enviornment ~/Unfurl/env/bin/python
Info 17:20:22: Kernel launching with ports 9005,9006,9007,9008,9009. Start port is 9000
Info 17:20:22: Launching kernel daemon for Python 3.8.10 64-bit ('env': venv) # ~/Unfurl/env/bin/python
Info 17:20:22: No custom variables for Kernel as interpreter is not conda, but is Venv
Info 17:20:22: Creating daemon process for ~/Unfurl/env/bin/python with env variables count 42
Info 17:20:22: Process Execution: > ~/Unfurl/env/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/Unfurl/env/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 17:20:22: Starting kernel from scratch
Info 17:20:22: Registering dummy command feature
Warn 17:20:22: StdErr from Kernel Process /home/simon/Unfurl/env/lib/python3.8/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.

Warn 17:20:22: StdErr from Kernel Process   warn(

Warn 17:20:22: StdErr from Kernel Process /home/simon/Unfurl/env/lib/python3.8/site-packages/traitlets/traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'c41cbe20-8918-4748-97d5-e8fd451cf817' instead of 'b"c41cbe20-8918-4748-97d5-e8fd451cf817"'.

Warn 17:20:22: StdErr from Kernel Process   warn(

Info 17:20:22: Raw session started and connected
Started kernel env (Python 3.8.10)
Info 17:20:22: Finished connecting 11681de4-e2bd-40f1-a2bf-621b28dd4b4d
Info 17:20:22: UpdateWorkingDirectoryAndPath in Kernel
Info 17:20:22: Process Execution: > /usr/bin/python3 -m pip list
> /usr/bin/python3 -m pip list
Info 17:20:22: changeDirectoryIfPossible
Info 17:20:22: Executing (status idle) silently Code = import os\nimport sys\n%cd "/home/simon/Unfurl"\nif os.getcwd() not in sys.path:\nsys.path.insert(0,
Info 17:20:22: Executing silently Code (completed) = import os\nimport sys\n%cd "/home/simon/Unfurl"\nif os.getcwd() not in sys.path:\nsys.path.insert(0,
Info 17:20:22: Executing (status idle) silently Code = %config Completer.use_jedi = False
Info 17:20:22: Executing silently Code (completed) = %config Completer.use_jedi = False
Info 17:20:22: Executing (status idle) silently Code = %config InlineBackend.figure_formats = ['png']
Info 17:20:22: Executing silently Code (completed) = %config InlineBackend.figure_formats = ['png']
Info 17:20:22: Executing (status idle) silently Code = import sys\nprint(sys.executable)
Info 17:20:22: Executing silently Code (completed) = import sys\nprint(sys.executable)
Info 17:20:22: Waiting for idle on (kernel): 732610a0-5de0-4ee6-91a6-39a8c75406df -> idle
Info 17:20:22: Finished waiting for idle on (kernel): 732610a0-5de0-4ee6-91a6-39a8c75406df -> idle
Info 17:20:22: IPyWidgetScriptSource.initialize
Info 17:20:29: Execute Cells request 0
Info 17:20:29: Execute Cell 0 ~/Unfurl/Test.ipynb
Info 17:20:29: Cell 0 executed with state Success
Info 17:20:48: Execute Cells request 0
Info 17:20:48: Execute Cell 0 ~/Unfurl/Test.ipynb
Info 17:20:50: Cell 0 executed with state Success
```

**Comment by kwikwag** [comment]
In microsoft/vscode-jupyter#8660 I mention that the reason is that a lot of data is getting sent back to the server.

**Comment by simondemeule** [comment]
Adding onto this: over LAN, things seem to work fine. This issue only seems to occur for me over WAN. This likely has to do with the quality of the connection. What is strange is how the issue locks in after the data is fully loaded on the client.

**Comment by kwikwag** [comment]
I think this is definitely limited by upload speeds. However I imagine that also via LAN you will be able to observe large amounts of data being sent *to* the server, which is something that's not supposed to happen or is supposed to be minimal when *receiving* output *from* the server.

This is becoming near-prohibitive for working with images over Jupyter in SSH, which I suppose is quite common, and is becoming more so due to working remotely becoming more popular in the Corona age. I suggest testing with one of the [tools to simulate slow connections available freely](https://stackoverflow.com/questions/3536249/simulating-slow-internet-connection).

If it can help, please let me know and I will check the content of the payload being sent back to the server, perhaps using a network monitor such as Wireshark, so that we can take a guess at who's sending data back to the server, and why.

**Comment by kwikwag** [comment]
BTW do you know if this is a regression bug? I didn't notice this behavior on pervious versions of VS Code, but I cannot swear to it.

**Comment by simondemeule** [comment]
@kwikwag absolutely agree on this being a major problem for writing image-processing software using Jupyter. I've completely abandoned it; I just write things to disk to check them afterwards. It's really clunky.

I've only been using this setup since a short period of time so I can't say if it's a regression.

I'll try and investigate bandwidth issues sometime this week.

**Comment by xl0** [comment]
I don't think this has anything to do with the connection.

I'm directly connected to the machine with a 1Gbs cable and still seeing the issue. Moreover, the slowdown happens _after_ the image is sent and displayed (note cell execution times):

![image](https://user-images.githubusercontent.com/439415/198494439-3eaf462c-add8-4bc7-9e7b-60fa12568874.png)

Here is the minimal code to reproduce without relying on PIL:
```python
class ShowPng():
    def __init__(self, img): self.img = img
    def _repr_png_(self): return open(self.img, "rb").read()

ShowPng("../output.png")
```

**Comment by roblourens** [comment]
Merging this into https://github.com/microsoft/vscode/issues/138784
