### ISSUE TITLE
Getting a "Cannot read property 'sideBar' of undefined" when I toggle the side bar

### ISSUE THREAD

**Issue by ryan-efendy** [microsoft/vscode#140174]
Issue Type: <b>Bug</b>

toggle side bar and you will get a notification/warning: "Cannot read property 'sideBar' of undefined"

VS Code version: Code - Insiders 1.64.0-insider (f0054e049cd286ff317c738efe0fd8810b48ae98, 2022-01-05T05:24:27.310Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|32.00GB (3.00GB free)|
|Process Argv|--crash-reporter-id 26c16dff-0d3a-4429-a92d-6ddd94bd74c9 --crash-reporter-id 26c16dff-0d3a-4429-a92d-6ddd94bd74c9|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.6.0
vscode-eslint|dba|2.2.2
gitlens-insiders|eam|2022.1.504
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.1.0
vscode-jest-runner|fir|0.4.47
copilot-nightly|Git|1.7.4459
remotehub|Git|0.21.2021121709
vscode-pull-request-github|Git|0.34.2
rest-client|hum|0.24.6
customize-ui|ioc|0.1.55
monkey-patch|ioc|0.1.16
vscode-peacock|joh|4.0.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.18.0
vscode-kubernetes-tools|ms-|1.3.4
js-debug-nightly|ms-|2022.1.417
vscode-typescript-next|ms-|4.6.20220104
refactor|p42|1.66.0
material-icon-theme|PKi|4.11.0
material-product-icons|PKi|1.1.1
vscode-yaml|red|1.2.2
vscode-javascript-booster|sbu|14.0.1
autoimport|ste|1.5.4
code-spell-checker|str|2.0.14
tabnine-vscode|Tab|3.5.13
errorlens|use|3.4.1
intellicode-api-usage-examples|Vis|0.0.6
vscodeintellicode|Vis|1.2.15
gistfs|vsl|0.3.0
fig|wit|0.0.5

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@ryan-efendy i cannot reproduce however there were some changes to the layout state code in the latest build. can you verify that this still occurs with extensions disabled? i notice you have the monkeypatch extension, is it possible you have some custom code that is no longer working here?

**Comment by ryan-efendy** [comment]
@sbatten yea disabling the monkeypatch extension did not throw that error. Will close this and open a new issue in https://github.com/iocave/monkey-patch.
