### ISSUE TITLE
poor remote session vim and emacs behavior since 1.64.0-insider 2022-01-05T05:15:20.239Z (now on 1.64 official)

### ISSUE THREAD

**Issue by giromide** [microsoft/vscode#140187]
- VS Code Version:
Version: 1.64.0-insider (user setup)
Commit: f0054e049cd286ff317c738efe0fd8810b48ae98
Date: 2022-01-05T05:15:20.239Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
- OS Version:
OS: Windows_NT x64 10.0.19043
- Remote OS Version:
RHEL 7.7
- Remote OS env:
`TERM=xterm-256color`

Problem:

Since the Insider release as of 2022-01-05, I have noticed problems with both `vim` and `emacs` on remote sessions. In the case of `vim`, text from terminal is rendered in the buffer, which is usually resolved by adjusting the pane. In the case of `emacs`, the buffer will not load. This behavior is not presented on the same remote session in use with standard `vscode` 1.63.0 release.

Steps to Reproduce:

1. In most recent 1.64.0-insiders release, initiate remote session to RHEL 7.7 or SELinux system. (I have not had opportunity to test on other Linux distros.)
2. Open existing files with either `vim` or `emacs`, preferably some python scripts with enough lines to require scrolling.

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" terminal

Also if the buffer doesn't load it would be helpful to log escape sequences when you load emacs: https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging

**Comment by giromide** [comment]
I'm encountering this on work equipment, so I'll see what I can provide.

**Comment by giromide** [comment]
I have enabled escape sequence logging with the dev terminal open. First thing I noticed upon creating a new terminal is this:
```
your 131072x1 screen size is bogus. expect trouble
```

Looking around for this, I found the below SHA (which appears to be from a fork) which I found from a different rendering issue back in 2017. https://github.com/microsoft/vscode/commit/0932e58743ac5cf75a6a90500c9261bd26c56440

**Comment by giromide** [comment]
I am unable to paste a screenshot of the bottom of my remote terminal that has loaded a vim of a new file, so I will type it out here:

```
"some_file.txt" [New File]ite-lisp/site-start.d/systemtap-init.el (source)... done
```

Typing "hello world" yielded

```
hellomworld
```

with a blue m between the words was rendered instead of a space. Upon saving and running `cat` on the file, it's just `hello world`

**Comment by giromide** [comment]
Still trying to obtain a gif of a recording that I can share without sensitive information.

With regards to `emacs`, I do not use it very often, but something I noticed is that in current Insiders terminal, upon loading a pre-existing file, the status bar at the bottom remains in `(List Interaction)` and never proceeds to `(Fundamental)`.

**Comment by Tyriar** [comment]
> with a blue m between the words was rendered instead of a space

Something odd is going on but this in particular sounds like it might be an issue with whatever you're remoting to. If you can repro that with escape sequence logging on, chances are it'll say parsing data "hello<esc>[34mm<esc>[0mworld`, meaning your remote pty told us to write the m in blue and vscode's terminal is just doing what it's told.

I can't really action this yet unfortunately.

**Comment by giromide** [comment]
![issue-140187-gif](https://user-images.githubusercontent.com/1554254/149245075-fb8a1519-89d9-4096-b803-82835bb0386b.gif)

I am unable to upload the source .CAST file for the above .GIF.

Unfortunately, this .GIF is not rendered to demonstrate an “n” displayed between “hello” and “world” in the first vim session; however, this does demonstrate that the emacs session is unable to display or load the file.

**Comment by modkaffes** [comment]
I’m encountering the same issue after the latest update (v1.64.1). Emacs opens in scratch mode in the vscode integrated terminal, whereas it opens in edit mode in iTerm.
![Recording 2022-02-09 at 02 53 50](https://user-images.githubusercontent.com/1829897/153101190-225c3fdf-a23e-42ab-aa93-4d4451d2c1ee.gif)

**Comment by giromide** [comment]
Closing as problems have been resolved.
