### ISSUE TITLE
Test: contribute to editor title context menu

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14014]
Test for https://github.com/Microsoft/vscode/issues/11942

- [x] anyOS @sandy081 
- [x] anyOS @ramya-rao-a 

Verify you can write an extension that adds menu entries to the editor tab context menu that can do something with the resource that is being shown. This context menu also shows up when tabs are disabled and you right click on the editor title.

The related menu key for package.json is `editor/title/context`, e.g.:

```json
"commands": [{
    "command": "doSomething",
    "title": "Do Something"
}],
"menus": {
    "editor/title/context": [
        {
            "command": "doSomething"
        }
    ]
}
```

**Comment by stef-levesque** [comment]
Any chance we will see the same feature for files in the `open editors` section ?
(see https://github.com/stef-levesque/vscode-hexdump/issues/10)

**Comment by bpasero** [comment]
@stef-levesque we should have it, can you file a new issue on this topic?
