### ISSUE TITLE
Extension ID case not preserved in web extension context

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#140120]
Originally created by @joyceerhl 

1. Go to insiders.vscode.dev
2. Open sources
3. Search for remotehub extension bundle
4. Pretty print the file
5. Set a breakpoint on line 40222
6. Reload the page
7. 🐛 See that `context.extension.id === 'GitHub.remotehub-insiders'` evaluates to `false` because `context.extension.id` is 'github.remotehub-insiders`. This is only the case on web insiders and stable--on desktop insiders and stable, case is preserved

![image](https://user-images.githubusercontent.com/30305945/144872506-9e7fcdd2-6808-49e9-bfbd-658815e76119.png)

I believe this behavior changed at least two releases ago, because RemoteHub uses this check to determine whether to enable an experimental setting--but it's possible that this has always been the case in web. I can look into running web out of sources to check if/when this changed.

IMO this is a surprising behavior discrepancy between web and desktop that may cause certain functionality to silently break in web. As an example, in web if you install RemoteHub stable and RemoteHub insiders together, you don't get the extension's warning since it's gated on a check for 'GitHub.remotehub-insiders'
![image](https://user-images.githubusercontent.com/30305945/144872191-a068ce99-7ea4-4536-96fb-cdeaec031624.png)

**Comment by rchiodo** [comment]
/verified

![image](https://user-images.githubusercontent.com/19672699/151597408-28a6762f-74fa-490d-beee-8eecaa048dd2.png)
