### ISSUE TITLE
Undo delete of a folder in explorer only restores folder, not files

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#140100]
Steps to Reproduce:

1. have 1 folder with 1 file
2. right click -> delete the folder
3. hit undo

=> 🐛  only the folder is restored, not the file

//cc @isidorn @jrieken

**Comment by isidorn** [comment]
I think this was a known limitation, and there might already be an issue for this.

**Comment by JacksonKearl** [comment]
duplicate of #111022
