### ISSUE TITLE
Titlebar does not respond properly to fullscreen changes

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#140164]
![image](https://user-images.githubusercontent.com/900690/148243162-a107bbf0-3eb3-467d-ac37-3861f112dc0e.png)

Maybe related to the layout changes?

**Comment by bpasero** [comment]
Hm, things are really weird. When I go fullscreen, the custom title does not hide anymore.

**Comment by bpasero** [comment]
So the first issue reproduces when you:
* go fullscreen
* quit
* start again
* leave fullscreen

**Comment by gjsjohnmurray** [comment]
> When I go fullscreen, the custom title does not hide anymore.

See also #140156

**Comment by sbatten** [comment]
thanks all, I can repro, working on a fix

**Comment by bpasero** [comment]
I think there are more regressions, like my sidebar size is not remembered anymore.

**Comment by sbatten** [comment]
@bpasero please create a separate issue so I can track these fixes individually.
