### ISSUE TITLE
Inlay hints not visible in right hand side of diff editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#140199]
Noticed that a diff shows on in lay hints on the right hand side, tried with a TS file.

**Comment by jrieken** [comment]
I see inlay hints with compare files

<img width="904" alt="Screen Shot 2022-01-06 at 08 26 22" src="https://user-images.githubusercontent.com/1794099/148345142-c63e7814-6034-4f5f-9383-06276ce7e9e4.png">

**Comment by bpasero** [comment]
![Recording 2022-01-06 at 08 39 28](https://user-images.githubusercontent.com/900690/148346662-8feb1483-8b17-48fd-a422-48f73187e27a.gif)

(this is todays insider build)

**Comment by jrieken** [comment]
Same build, same file, same change and I am not seeing this... Is there anything on the console?

**Comment by bpasero** [comment]
Fine now.
