### ISSUE TITLE
Explorer scroll bar pointer isn't captured when it enters a webview

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140101]
Repro:

1. Open a webview
2. Drag explorer scroll bar into webview, it ignores the events

Possible fix is to set/release pointer capture. Might be an issue in webviews?

![recording (11)](https://user-images.githubusercontent.com/2193314/148090087-4294aae6-f070-4e63-9b4e-14e16b42fc4e.gif)

**Comment by joaomoreno** [comment]
Precedence: https://github.com/microsoft/vscode/issues/94055, with fix https://github.com/microsoft/vscode/commit/18b8ef01b85d867d74f7314637c3de89e46227d8

@rebornix Was your fix intended to fix this problem for all webviews?

**Comment by Tyriar** [comment]
@rebornix the pointer capture thing is how I solve this to allow continued listening to pointer events from within the webview even when the pointer is outside, so if that works it'll probably be more reliable than a cover element approach.

**Comment by mjbvz** [comment]
@Tyriar I haven't used the pointer capture api but on this case, we would want to set pointer capture on the scrollbar element, right? 

/cc @alexdima Since I believe you implemented scrolling

**Comment by alexdima** [comment]
@Tyriar What exact DOM API are you using? At https://mdn.github.io/dom-examples/pointer-lock/ I get three undesirable behaviors:
* My mouse cursor becomes invisible
* A browser message shows up saying I can press Escape to exit this mode
* Escape is not dispatched to the DOM but is eaten up to exit this mode

**Comment by Tyriar** [comment]
@mjbvz yes.

@alexdima oh, I didn't know it would be ambiguous, here's what I do:

```ts
addDisposableDomListener(container, 'pointerdown', e => {
  container.setPointerCapture(e.pointerId);
});
addDisposableDomListener(container, 'pointerup', e => {
  container.releasePointerCapture(e.pointerId);
});
```

**Comment by mjbvz** [comment]
@alexdima I believe you were looking at the pointer-lock api which is different than the pointer capture api that @Tyriar was proposing: https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture
