### ISSUE TITLE
can not search in open editors and the prompt is not helpful

### ISSUE THREAD

**Issue by alan-gu** [microsoft/vscode#140198]
Issue Type: <b>Bug</b>

I'm not sure about the steps to reproduce.
I've certainly used search in open editors feature before and it worked well.
This time when I try to search "ops" in opend editors, the search frame becomes red and there is this prompt if I left click on it.
![image](https://user-images.githubusercontent.com/13609895/148339494-1a2472f7-2f07-4560-84ca-98d381d4ab0d.png)
Normal search(in whole workspace) in OK.
And none of my files is named starting with a slash.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-186-generic
Remote OS version: Linux x64 4.4.0-210-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.72GB free)|
|Process Argv|--crash-reporter-id 3f050556-49ec-422b-ba00-0fe51e830e09|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.198.39.42|
|OS|Linux x64 4.4.0-186-generic|
|CPUs|Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz (32 x 2992)|
|Memory (System)|251.92GB (23.80GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: 10.198.39.41|
|OS|Linux x64 4.4.0-210-generic|
|CPUs|Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz (48 x 2992)|
|Memory (System)|251.91GB (88.19GB free)|
|VM|100%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-drawio|hed|1.6.2
better-cpp-syntax|jef|1.15.10
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
vscode-remote-extensionpack|ms-|0.21.0
devicetree|plo|0.1.1
vim|vsc|1.21.7
hidl-syntax|yrp|0.0.2
gitlens|eam|11.7.0
cpptools|ms-|1.7.1
highlight-words|rsb|0.1.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710:30416614
vscexrecpromp3t3:30407764

```

</details>

**Comment by alan-gu** [comment]
It seams "ops" is irrelavant.
Searching any characters in open editors produces the message.
Meanwhile other windows are working.

**Comment by gjsjohnmurray** [comment]
What kind of URIs do your open files have? Hovering the mouse over each tab may reveal this information.

**Comment by roblourens** [comment]
Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" and "Log (Extension Host)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by alan-gu** [comment]
@gjsjohnmurray I think they are just normal URls. I'm not sure if I can show the whole name so I'll just give an example with only some of the names changed.
/home/alan/code/platform/vendor/somecompany/a/b/c/d/e/f.cpp
actually it happens even when I have no file open.

**Comment by alan-gu** [comment]
@roblourens I haven't been able to reproduce this bug. I'll update the log when I have it.

**Comment by alan-gu** [comment]
@roblourens 
I have the log you need.

> [2022-01-12 15:32:46.638] [renderer2] [trace] KeybindingService#dispatch Enter undefined
[2022-01-12 15:32:47.057] [renderer2] [trace] KeybindingService#dispatch Enter undefined
[2022-01-12 15:32:47.244] [renderer2] [trace] KeybindingService#dispatch Enter undefined
[2022-01-12 15:32:59.979] [renderer2] [trace] KeybindingService#dispatch Backspace undefined
[2022-01-12 15:33:06.067] [renderer2] [trace] KeybindingService#dispatch O undefined
[2022-01-12 15:33:06.374] [renderer2] [trace] KeybindingService#dispatch P undefined
[2022-01-12 15:33:06.584] [renderer2] [trace] KeybindingService#dispatch S undefined
**[2022-01-12 15:33:22.278] [renderer2] [trace] SearchService#search {"_reason":"searchView","folderQueries":[{"folder":{"$mid":1,"fsPath":"\\________________________","_sep":1,"external":"vscode-remote://ssh-remote%2B10.198.39.42/home/_____________x","path":"/home/_____________x","scheme":"vscode-remote","authority":"ssh-remote+10.198.39.42"},"folderName":"_______","fileEncoding":"utf8","disregardIgnoreFiles":true,"disregardGlobalIgnoreFiles":false,"ignoreSymlinks":false},{"folder":{"$mid":1,"fsPath":"\\home\\____________","_sep":1,"external":"vscode-remote://ssh-remote%2B10.198.39.42/home/_______________","path":"/home/_________________","scheme":"vscode-remote","authority":"ssh-remote+10.198.39.42"},"folderName":"chi-cdk","fileEncoding":"utf8","disregardIgnoreFiles":true,"disregardGlobalIgnoreFiles":false,"ignoreSymlinks":false},{"folder":{"$mid":1,"fsPath":"\\home\\_________________________","_sep":1,"external":"vscode-remote://ssh-remote%2B10.198.39.42/home/_____________________","path":"/home/________________________","scheme":"vscode-remote","authority":"ssh-remote+10.198.39.42"},"folderName":"qcom","fileEncoding":"utf8","disregardIgnoreFiles":true,"disregardGlobalIgnoreFiles":false,"ignoreSymlinks":false},{"folder":{"$mid":1,"fsPath":"\\home\\_________________","_sep":1,"external":"vscode-remote://ssh-remote%2B10.198.39.42/home/____________________","path":"/home/__________________","scheme":"vscode-remote","authority":"ssh-remote+10.198.39.42"},"folderName":"camera","fileEncoding":"utf8","disregardIgnoreFiles":true,"disregardGlobalIgnoreFiles":false,"ignoreSymlinks":false}],"usingSearchPaths":false,"extraFileResources":[{"$mid":1,"fsPath":"\\home\\_____________________","_sep":1,"external":"vscode-remote://ssh-remote%2B10.198.39.42/home/__________________","path":"/home/_______________","scheme":"vscode-remote","authority":"ssh-remote+10.198.39.42"}],"onlyOpenEditors":false,"maxResults":20000,"type":2,"contentPattern":{"pattern":"ops","isRegExp":false,"isCaseSensitive":false,"isWordMatch":false,"wordSeparators":"`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"},"previewOptions":{"matchLines":1,"charsPerLine":1000},"usePCRE2":false,"userDisabledExcludesAndIgnoreFiles":true}**
[2022-01-12 15:33:23.431] [renderer2] [trace] SearchService#search: 1139ms
[2022-01-12 15:33:39.707] [renderer2] [trace] KeybindingService#dispatch Enter undefined

The bold line is one successful search when I unset the "Search in Open Editors" option. I edited some of the detailed path info. Hope it won't affect your debugging.
The last line is after I set the option and hit enter.
It seems when I set the "Search in Open Editors" option, vscode treats my input in search frame as some keybinding.

**Comment by roblourens** [comment]
I didn't realize that this was only with "Search in Open Editors" selected. The log shows that the error doesn't come from the actual search code. Any idea @JacksonKearl? I don't see anything unusual with the URIs. The fsPath has weird backslashes but I see the same using SSH from Win->Linux, and don't repro the issue.

**Comment by JacksonKearl** [comment]
Tried a few different variations on this and was not able to reproduce. Does this happen every time you search, regardless of opened editors? Also is it only one remote, or have you seen it without remotes or on a different remote at all?

**Comment by JacksonKearl** [comment]
The next insiders will have improved logging of open editors queries, if you run into this again it'd be a big help for us if you could include the log from a new Insiders (also in `trace` mode)

**Comment by alan-gu** [comment]
> Tried a few different variations on this and was not able to reproduce. Does this happen every time you search, regardless of opened editors? Also is it only one remote, or have you seen it without remotes or on a different remote at all?

Sorry I was off work for a few days. I only work with one remote so it only occured on that remote. I have not seen the issue in a local window. It took me a few days to reproduce this myself. I don't know the steps to reproduce it.

> The next insiders will have improved logging of open editors queries, if you run into this again it'd be a big help for us if you could include the log from a new Insiders (also in `trace` mode)

I have updated my vscode. I'll update the log if I run into the issue again.
Thanks.
