### ISSUE TITLE
Centered Layout is Broken

### ISSUE THREAD

**Issue by ivme83** [microsoft/vscode#140189]
Issue Type: <b>Bug</b>

Open a file to edit
Toggle Centered Layout
Layout does not toggle to Centered Layout

VS Code version: Code - Insiders 1.64.0-insider (f0054e049cd286ff317c738efe0fd8810b48ae98, 2022-01-05T05:15:20.239Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.76GB (47.66GB free)|
|Process Argv|C:\\Users\\Roland\\Desktop\\shortcuts\\SpyFu_Frontend.code-workspace --crash-reporter-id 44922a6d-9ffe-4bed-8330-2b75c78031a8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
htmltagwrap|bra|0.0.7
vscode-toggle-quotes|Bri|0.3.6
path-intellisense|chr|2.6.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
scriptcsRunner|fil|0.1.0
kotlin|fwc|0.2.23
copilot|Git|1.7.4421
vscode-pull-request-github|Git|0.34.2
output-colorizer|IBM|0.1.2
vscode-edit-csv|jan|0.6.4
rainbow-csv|mec|2.0.0
csharp|ms-|1.23.17
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
powershell-preview|ms-|2021.12.0
test-adapter-converter|ms-|0.1.5
vsliveshare|ms-|1.0.5201
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vetur|oct|0.35.0
indent-rainbow|ode|8.2.2
vscode-jest|Ort|4.2.1
material-icon-theme|PKi|4.11.0
material-product-icons|PKi|1.1.1
vscode-commons|red|0.0.6
elastic|ria|0.13.3
vscode-stylelint|sty|0.87.6
vscodeintellicode|Vis|1.2.15
vscode-icons|vsc|11.8.0
vscode-js-console-utils|wht|0.7.0
ws-rainmeter|wil|0.2.7
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
vscop804cf:30404767
vs360cf:30404996
vsclayoutctrc:30405799
py55gd98cf:30408622
vscexrecpromp3t1:30407758
azactmsal:30409287

```

</details>

**Comment by gjsjohnmurray** [comment]
/confirm

Version: 1.64.0-insider (user setup)
Commit: 9afbea7caab9dd06592ddd98aa4161b43b126d3f
Date: 2022-01-06T05:15:07.481Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by bpasero** [comment]
@sbatten
