### ISSUE TITLE
Lines or static covers the screen when use external monitor

### ISSUE THREAD

**Issue by maxineliu** [microsoft/vscode#140135]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2 (Universal)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0
- OS Version: macOS Monterey 12.1
- chip Apple M1 pro

Steps to Reproduce:

1. Display VS code at the external monitor with a refresh rate of 120 Hertz.
2. Lines or static covers the screen, especially the edges (see image).
![IMG_5685](https://user-images.githubusercontent.com/56008870/148148874-83545292-a6f9-40fa-89c7-e3dc8d8e68c7.jpg)
3. The problem may not occur at first, but will always happen as time goes by or when you change the size of windows or split the screen with VScode and other apps.

I am pretty sure that VScode causes this problem because it won't happen when I use other apps like chrome or ms office.

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/139827#issuecomment-1001943302 suggests steps that may help you investigate the problem.

**Comment by MaxineLiu** [comment]
> [#139827 (comment)](https://github.com/microsoft/vscode/issues/139827#issuecomment-1001943302) suggests steps that may help you investigate the problem.

Thx so much! Lines no more occur after GPU disable! Awesome~
