### ISSUE TITLE
Error in the SASS/LESS -> CSS guide

### ISSUE THREAD

**Issue by malisbad** [Microsoft/vscode#1401]
There is an error in your SCSS/LESS - > CSS guide. The task shouldn't have the ">" in the task runner (anymore?). If you follow the guide, it writes the compiled .css to the ">". If you remove it, it writes to "styles.css" correctly.

**Comment by dbaeumer** [comment]
@aeschli not sure if this is you

**Comment by aeschli** [comment]
This is about the 'Transpiling Sass and Less into CSS' section in https://github.com/Microsoft/vscode-docs/blob/master/docs/languages/css.md
Not sure who authored that, @gregvanl ?

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-docs#85
