### ISSUE TITLE
Slow Search

### ISSUE THREAD

**Issue by una** [Microsoft/vscode#14012]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:28:55.412Z)
- OS Version: Darwin x64 15.4.0
- Extensions: HookyQR.beautify-0.4.1, anseki.vscode-color-0.1.11, christian-kohler.path-intellisense-1.1.0, dbaeumer.vscode-eslint-1.0.8, donjayamanne.githistory-0.1.0, ms-vscode.js-atom-grammar-0.1.10, robertohuertasm.vscode-icons-3.0.5, seanmcbreen.Spell-0.8.6, streetsidesoftware.code-spell-checker-0.10.13, zhuangtongfa.Material-theme-1.0.3

Steps to Reproduce:
1. Open a large file system
2. Search across the system

I love this product, but the only downside of it (which can be prohibitive when doing certain types of work) is how slow the search is when searching across the file system. Not sure if its a plugin I have installed, but searching in Sublime Text is relatively speedy (for comparison), while searching through VS Code seems to take a long time and never complete the search.

**Comment by roblourens** [comment]
To be clear, do you mean text search like with cmd+shift+f, or opening a file by name with cmd+p? Could you check if it's any faster without extensions, by launching with `--disable-extensions` from the command line?

**Comment by roblourens** [comment]
And roughly how large is the folder that you open?

**Comment by una** [comment]
cmd+shift+f ! Thanks for clarifying

**Comment by una** [comment]
Maybe it was a plugin, it does seem to go faster without extensions and with a system refresh. It was pretty painful before

**Comment by andreiropotica** [comment]
Same problem here, very slow search... I have several plugins but that shuldn't afect the search...

- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: cmstead.jsrefactor-0.5.3, dbaeumer.jshint-0.10.15, dbalage.vscode-stylesheet-formatter-0.2.0, donjayamanne.githistory-0.1.0, donjayamanne.jquerysnippets-0.0.1, HookyQR.JSDocTagComplete-0.0.2, mohsen1.prettify-json-0.0.3, ms-vscode.jscs-0.1.9, msjsdiag.debugger-for-chrome-1.2.2, shinnn.stylelint-0.17.3, stevencl.addDocComments-0.0.8, Tyriar.sort-lines-1.1.0, waderyan.gitblame-1.3.0, wcwhitehead.bootstrap-3-snippets-0.0.7

**Comment by roblourens** [comment]
This should be faster in VS Code 1.8, from work in https://github.com/Microsoft/vscode/issues/15384 - try it out and let me know!

**Comment by una** [comment]
It's not much faster for me, just so you know :/

**Comment by roblourens** [comment]
Hm, roughly how large is the folder that you're searching in? And how long does it take?

**Comment by una** [comment]
its really not that big -- 132 files, 578 KB, and takes over 10 seconds on average

**Comment by roblourens** [comment]
Yeah, I would expect that to be searched nearly instantaneously in Code at this point too. Can you check whether other folders are faster, or whether there's something about this particular folder?

**Comment by junestone** [comment]
In this case, a cache is needed.
Use a datastructure or database to include all text content to speedup text search is possible. Searching file by file is a horrible idea.
I think u can ask Visual Studio team for help.
