### ISSUE TITLE
ctrl+0 shortcut doesn't focus when no files opened

### ISSUE THREAD

**Issue by ceyhunkerti** [Microsoft/vscode#14018]
- VSCode Version: 16.1
- OS Version: ubuntu 16.04

Steps to Reproduce:
1. open a fresh folder with no open editor tabs
2. press ctrl+0 to focus file explorer

**Comment by Tyriar** [comment]
This is as designed imo since there is a focus explorer action (ctrl+shift+e) which is meant to focus the explorer, not a file within it. I opened https://github.com/Microsoft/vscode/issues/14020 which is related to the latter though.

**Comment by ceyhunkerti** [comment]
thanks, i'll close this one then.
