### ISSUE TITLE
Web: 1.5MB SVG is too big

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#140159]
We currently ship `/out/vs/workbench/contrib/welcome/gettingStarted/common/media/learn.svg`, **a 2 MB SVG file**, in our web package:

![image](https://user-images.githubusercontent.com/22350/148224509-ac1d3b0e-19c1-41d2-8a30-4a098ce27bfc.png)

This is beyond reasonable.

I would even argue that we should minify all SVG we currently have in sources. Even smaller ones, like `debug.svg`, weigh 64 KB and could easily be reduced by around 22% with plain SVG minification.

**Comment by misolori** [comment]
SVG is now 40kb, stripped out some shadows and images that were taking up a lot of space. We'll make sure and ensure our svgs are optimized as much as possible and stay under 1mb.

**Comment by misolori** [comment]
@joaomoreno can we setup a gulp task to auto-minify all svg assets?

**Comment by joaomoreno** [comment]
You mean like this? https://github.com/microsoft/vscode/commit/35c70dc0a26c557d909529fb6f5ac5544e59877e 💪

Minification helps reducing 1.6MB down to 1.2MB, not bad.

![image](https://user-images.githubusercontent.com/22350/148555809-c63b9927-1ed0-4d77-8d35-272a34cfe5c4.png)

**Comment by joaomoreno** [comment]
Marking it as bug, to go through verification:

1. Download a ZIP archive of VS Code
2. All SVGs should be minified (no new lines)
3. `out/vs/workbench/contrib/welcome/gettingStarted/common/media/learn.svg` should be ~40kb
