### ISSUE TITLE
Sidebar width not memorized

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#140154]
Does this issue occur when all extensions are disabled?: Yes/No

Version:

```
Version: 1.64.0-insider (Universal)
Commit: f0054e049cd286ff317c738efe0fd8810b48ae98
Date: 2022-01-05T05:14:16.471Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0
```

Steps to Reproduce:

1. drag the sidebar width
2. `cmd + q` to quit vscode
3. open vscode, the width of vscode will not be the same when it closed

**Comment by gjsjohnmurray** [comment]
Looks like this got fixed by @sbatten on #140175

/duplicate
