### ISSUE TITLE
VsCode Window randomly disappear on Ubuntu os

### ISSUE THREAD

**Issue by RodolpheGohard** [microsoft/vscode#140167]
Issue Type: <b>Bug</b>

I am using Ubuntu with Cinnamon,

Sometimes, seamingly at random, my vscode window vanishes.
It happens when I'm actively using it but also when it's in the background.

I have found that the codium processes continue to exist, and I have to kill them manually because the cumulation of them end up eating a lot of RAM.

The bug happens with VsCodium as well, and even with no extensions installed.
I looked through the various log files but could not find anything relevant.

I have another machine (laptop) with Ubuntu and Cinamon as well but the issue doesn't happen there.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.11.0-44-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 4180)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|31.26GB (8.91GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 5dfe1fdb-bb99-4123-be84-37294483bfd8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.7.0
vscode-json5|mrm|1.0.0
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.17
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
remote-containers|ms-|0.209.6
vsliveshare-pack|ms-|0.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30414009
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710:30416614
vscexrecpromp3t3:30407764
vscop841:30415853

```

</details>

**Comment by tanhakabir** [comment]
Hm do you have more details about the memory intensive processes?

Also does you other working laptop see the same emory intensive issues?

**Comment by RodolpheGohard** [comment]
It's not particularily intensive, it's just that the codium processes stay even though the window closes:

![vscodium eluding itsef](https://user-images.githubusercontent.com/294167/148674726-3a252ea7-02b7-43e0-a115-53b5975c1e94.png)

**Comment by tanhakabir** [comment]
I see. How long after closing do you still see the processes?

**Comment by RodolpheGohard** [comment]
I do not close, the vscode windows disappear by themselves.
These processes stay as long as I don't kill them.

It looks like vs code is still running fine, but somehow it's just the window which is lost. Maybe something to do with the window or desktop manager ?

**Comment by RodolpheGohard** [comment]
I uninstalled the snap version and try with the .deb version and the problem does'nt seem to happen.

version that works:

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-44-generic

Maybe it's a problem with the snap package / environment ?

**Comment by tanhakabir** [comment]
Hm I'm not familiar with how Codium bundles their packages so I'm sorry we can't help you here. You could check in with them for what might be the issue.
