### ISSUE TITLE
Extension host sometimes doesn't start up when switching folders

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#140114]
On the latest exploration build
1. Open the program
2. Open a fresh folder containing files such as json or TS files. VS Code asks you to trust the folder. Trust it.
3. :bug: Notice that the file icon theme isn't loaded, and there's no syntax highlighting
4. :bug: When running the `workbench.action.showRuntimeExtensions` command, no extensions show up

The bug is flaky, though. I don't get it happening consistently.

**Comment by bpasero** [comment]
Please next time in devtools try this:

```
setImmediate(()=>{
   console.log("immediate")
})
process.nextTick(()=>{
   console.log("nextTick")
})
```

**Comment by rzhao271** [comment]
I repro'd the issue, pasted the code above in the devtools, and noticed that both of those messages are logged. 
I however notice that there's another warning in the devtools that appeared before I pasted the code above in: "The customer named _initialize has been holding onto the lock for 30s. This might be a problem."

**Comment by bpasero** [comment]
Is this still happening?

**Comment by rzhao271** [comment]
I tried a few more times to repro it but wasn't able to. Closing.
