### ISSUE TITLE
Test Explorer: test items added aren't properly refreshed in the editor gutter

### ISSUE THREAD

**Issue by fabioz** [microsoft/vscode#140166]
Does this issue occur when all extensions are disabled?: No (extension is needed to reproduce issue with test explorer)

Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Create extension that uses the new test explorer
2. Use `Copy Line Down` to copy the contents of a test
3. Editor gutter is no longer properly refreshed with the contents of the test explorer

I'm attaching a gif showing the issue.

The gif shows first adding a new item by typing a new test (where it works) and then just typing it out (where the editor gutter becomes confused) and then closing/reopening (where it updates again).

![vscode_test_explorer_items](https://user-images.githubusercontent.com/117621/148244891-df33e353-65f1-43b4-a356-09545c8951d7.gif)

Some notes:

- The tree seems to be correct while the editor becomes confused.

- If the test item is removed and then an `await sleep(500)` is done to then re-add the child items (such that there's a flicker where the items are removed), the gutter is updated correctly. 

- Closing and reopening the editor does make the items in the editor gutter appear properly.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/138835, fixed already on Insiders :)

**Comment by fabioz** [comment]
Thanks ;)
