### ISSUE TITLE
VSCode previous open workspaces not in sync with right click menu on taskbar

### ISSUE THREAD

**Issue by ricardosantos9521** [microsoft/vscode#140181]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64 - insiders
- OS Version: Windows 11

Steps to Reproduce:

1. Remove a recent folder from the right click menu from the taskbar 
![image](https://user-images.githubusercontent.com/20097801/148281396-bac33120-da37-4d67-89b6-7dcfefde5c90.png)
2. does not update the Backups/workspaces.json

Some context:
- previously Powertoys Run plugin VSCode Workspaces used AppData/Roaming/Code - Insiders/settings.json to get all the previous opened workspaces for vscode insiders in this case
- because of a recent change in code insiders i was trying to use AppData/Roaming/Code - Insiders/Backups/workspaces.json instead, but vscode insiders sometimes cleans all the folderWorkspaceInfos from that json

We don't the best way of getting the previously open workspaces in sync with what is showed in right click menu showed above.

Can anyone take a look at this?

**Comment by bpasero** [comment]
With https://github.com/microsoft/vscode/issues/138072, the list of opened workspaces moved into our SQLite DB and out of that JSON file. This is intentional.
