### ISSUE TITLE
Double clicking on settings.json file results in new tabs each time 

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#140129]
![settings-multiple-tabs](https://user-images.githubusercontent.com/641685/148135817-17574702-c73c-45d6-9d8c-5f26dcd31d96.gif)

I haven't noticed this before, but not sure if it is new or not.

I would guess it is related to my settings to use the split json editor.
```json
  "workbench.settings.editor": "json",
  "workbench.settings.useSplitJSON": true,
```

I also have `revealIfOpen` enabled too
```json
"workbench.editor.revealIfOpen": true,
```

/cc @roblourens

**Comment by rzhao271** [comment]
Just the `"workbench.settings.useSplitJSON": true` setting is enough to cause the issue, and I confirmed that the bug has been there since 1.61.
