### ISSUE TITLE
Theme Color Switching Randomly

### ISSUE THREAD

**Issue by osvaldorivera** [microsoft/vscode#140139]
Issue Type: <b>Bug</b>

Title speaks for itself, it seems the devs have not properly fixed the issue referenced here https://developercommunity.visualstudio.com/t/back-and-forth-theme-switching/954569

It's only a bit annoying to me because I am looking at plots in python notebooks and having the color switch like that interrupts my visualizations.

VS Code version: Code 1.63.0 (Universal) (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
The link you posted is about Visual Studio, which is not the same product as VS Code.

**Comment by aeschli** [comment]
Closing the issue. If the problem is indeed with VS Code, please provide steps to reproduce.

**Comment by osvaldorivera** [comment]
OK,. sorry for posting a link to Visual Studio, however the problem is indeed in the VS Code. I went through the "Report Issue" link of the tool. The issue report linked me then to create this GitHub issue, that is why you see the system information automatically appended to the bottom. Don't be so quick to dismiss...

Steps to reproduce:
- open file in VS code.. (currently in dark mode)
- select default white theme
- wait a few seconds (or a minute) for it to randomly turn back to original dark theme.

VS code initially defaulted to the high contrast theme.

**Comment by aeschli** [comment]
I'm not able to reproduce.
- Does it reproduce when running with extension disabled? There are some extensions that manage theme based on daylight. To test this, use the command `Developer: Reload with Extensions Disabled`
- Do you have settings sync enabled?

**Comment by aeschli** [comment]
I'm not able to reproduce.
Does it reproduce when running with extension disabled? 
 (there are some extensions that manage theme based on daylight)

**Comment by osvaldorivera** [comment]
I did reproduce a few times and stopped using VS code for a while. Looking into it again today, it seems to have stopped doing it. Not sure why because I haven't updated to newest macOS yet. It's fine, thanks for looking into it.
