### ISSUE TITLE
Copying content in problem hover is extremely painful

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#140172]
I was trying to copying a new setting in the problems hover and it was extremely painful to do so:

https://user-images.githubusercontent.com/35271042/148260276-749293ec-9c9b-461b-8875-1fbaf3733c67.mp4

**Comment by sandy081** [comment]
This is editor hover and hence assigning to @alexdima

**Comment by Tyriar** [comment]
FWIW this works fine for me on Windows.
