### ISSUE TITLE
Auto Add List Items

### ISSUE THREAD

**Issue by TwisterMc** [Microsoft/vscode#14010]
- VSCode Version: Version 1.6.1 (1.6.1)
- OS Version: 10.12

_Feature Request_
When working in markdown files, it'd be great if after I start a list, each time I hit enter it would add another list item. That'd make working with Markdown much more efficient. 

Hitting enter twice would then break out of the list.

**Comment by roblourens** [comment]
Probably could be done by an extension

**Comment by dptr** [comment]
does any one known any extension? I came accross the same problem.

**Comment by auchenberg** [comment]
The extension "Markdown all in one" implements this https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one

**Comment by mjbvz** [comment]
Closing as extension candidate
