### ISSUE TITLE
Screen readers don't read the source of autocomplete suggestions for imports

### ISSUE THREAD

**Issue by Neurrone** [microsoft/vscode#140138]
/CC @isidorn 

Issue Type: <b>Bug</b>

When I type a symbol like `DocumentClient`, several suggestions appear for possible matches. However, the source of where the import comes from does not get read out automatically with NVDA.

For example, I expect "DocumentClient, aws-sdk/clients/dynamodb" to be read. But only "DocumentClient" is read. This makes it difficult to select an appropriate suggestion to accept when there are multiple matches that have the same name.

VS Code version: Code - Insiders 1.64.0-insider (990ad4044032b05c0ebf0f67f800c5845baad4c7, 2022-01-04T05:18:15.830Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1697)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.23GB (15.96GB free)|
|Process Argv|--crash-reporter-id 1304d64e-abdb-456c-beb6-72c33120f731|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1696)|
|Memory (System)|24.45GB (19.00GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.210.0
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
vscode-eslint|dba|2.2.2
dendron|den|0.76.0
dendron-markdown-links|den|0.6.20
dendron-markdown-preview-enhanced|den|0.10.57
dendron-markdown-shortcuts|den|0.12.1
dendron-paste-image|den|1.1.0
dendron-snippet-maker|den|0.1.6
gitlens|eam|11.7.0
prettier-vscode|esb|9.1.0
copilot|Git|1.7.4421
rest-client|hum|0.24.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
vscop804cf:30404767
vs360cf:30404996
vsclayoutctrc:30405799
py55gd98cf:30408622
vscexrecpromp3t1:30407758
azactmsalcf:30409288

```

</details>

**Comment by Neurrone** [comment]
Perhaps a more accurate way of stating this is the right hand side of the list that has additional info for that suggestion isn't read.

**Comment by isidorn** [comment]
@Neurrone sorry for the slow response. I can repro.
As a workaround if you press `ctrl + space` while the suggestion are shown it should work. We use `ctrl + space` to trigger an additional suggest window that has the additional info.

@jrieken the bug seems to be that if the additional suggest window is not shown the additional info is not part of the aria label of each suggest item.

**Comment by jrieken** [comment]
> the bug seems to be that if the additional suggest window is not shown the additional info is not part of the aria label of each suggest item.

I don't believe it's about the additional window but about the complex label which consists of label, detail, and description

**Comment by Neurrone** [comment]
This seems to have regressed recently, it was working a while ago. I'm on this version:

```
Version: 1.64.0-insider (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
```

**Comment by Neurrone** [comment]
Weird, this seemed to be ok now, the only difference was the file that I was trying to edit couldn't be saved because a newer version of it existed. After I resolved that problem, autocompletes are reading properly again. Maybe it was just a fluke.
