### ISSUE TITLE
Provide a simple and easy way to insert escaped or special characters in HTML

### ISSUE THREAD

**Issue by henrychea** [microsoft/vscode#140161]
A simple snippet or extension that would suggest special characters like `&nbsp;` or `&#39;` when the keyword `&;` is typed in HTML text

**Comment by aeschli** [comment]
The HTML language mode already provides code completion on `&` (Ctrl+Space after &)
![image](https://user-images.githubusercontent.com/6461412/148248085-a4e9831b-9f58-4b77-9f92-e4659b49c6a0.png)

Additionally, you can define user snippets for your commonly used entity characters.

Lety me know what you are missing.

**Comment by SNDST00M** [comment]
Do you mean mapping characters like `-` to their respective escape sequences?

**Comment by aeschli** [comment]
Still waiting for more information from @henrychea ...

**Comment by henrychea** [comment]
Hi sorry for the inconvenience. This issue has been resolved. Thank you for the aid and patience.

**Comment by SNDST00M** [comment]
Cool. What was the solution?
