### ISSUE TITLE
Extend the directory depth of `git.autoRepositoryDetection`

### ISSUE THREAD

**Issue by mozhuanzuojing** [microsoft/vscode#140134]
`git.autoRepositoryDetection`  At present, the maximum directory depth scanned by this parameter is the lower level of the currently opened folder. But the projects I encountered are all in the lower level of the current open folder, that is, the third-level directory is the code warehouse. I hope to be able to add parameters to automatically detect the subordinates of the subordinates of the currently opened folder.

> samples:

+OpenFloder
+------------- otherConfig
+------------- subprojects
+-------------------------- git-project1
+-------------------------- git-project2
+-------------------------- git-project3

**Comment by lszomoru** [comment]
The solution here would be to have a setting that one can set to control the depth of the repository discovery. That feature is currently tracked with https://github.com/microsoft/vscode/issues/87888 so I will go ahead and close this issue as duplicate. I will try to look at that feature request this milestone.

**Comment by mozhuanzuojing** [comment]
@lszomoru Thank you for your detailed reply and work！

This feature is related to the convenience of using git in vscode. If the development is completed, it will make it easier for users to use git in vscode. Otherwise, it is easy to leave users with the impression that the git function of vscode is not easy to use.

**Comment by lszomoru** [comment]
The latest version of insiders contains a new setting `git.repositoryScanMaxDepth` that you can use to control the folder depth when we are scanning for repositories. You can set that setting either in your user settings, on in the workspace settings based on your folder structure.

**Comment by mozhuanzuojing** [comment]
@lszomoru OK. I saw. Thank you very much for your great contribution.it works very well.

**Comment by lszomoru** [comment]
Verification steps:
1. Set up folder structure with git repositories similar to this one:
    ```
    +OpenFloder
    +------------- otherConfig
    +------------- subprojects
    +-------------------------- git-project1
    +-------------------------- git-project2
    +-------------------------- git-project3
    ```
2. Open `OpenFolder` in VS Code Insiders, switch to the SCM viewlet and confirm that the git repositories are not discovered.
3. Open settings, and set the `git.repositoryScanMaxDepth` setting to 2 either in your user settings of in the workspace setting. 
4. Reload the window 
    - Use the SCM viewlet to confirm that the git repositories are being discovered

**Comment by mozhuanzuojing** [comment]
@lszomoru i test it.

> result ： scan out all git repository. but, when project has an oversized directory `node_modules`, the scanning time takes more than three minutes.

![image](https://user-images.githubusercontent.com/63572041/150893711-0e66a7a6-220c-4817-af8c-729e660ed4a9.png)

> this is my project structure

![image](https://user-images.githubusercontent.com/63572041/150894427-38177f06-259d-4e65-9ff1-c9db4c5ff0c9.png)

**Comment by lszomoru** [comment]
@mozhuanzuojing, thank you very much for testing the new setting. Tomorrow's Insiders release contains a new setting (`git.repositoryScanIgnoredFolders`) that you can use to specify the names of the folders that you want repository scan to ignore. For the time being it only contains `node_modules` but you can add your own as you wish.

**Comment by mozhuanzuojing** [comment]
@lszomoru @rchiodo Thanks a lot for your improvements and testing. I went home for the Chinese Spring Festival a few days ago and didn't see the reply in time.

**Comment by MingHuiLiu** [comment]
want to be able to ignore folders and files that have been tracked by git

**Comment by lszomoru** [comment]
@MingHuiLiu, could you please elaborate on that? There is a setting `git.repositoryScanIgnoredFolders` that can be used to specify directories that should be ignored while scanning for repositories.
