### ISSUE TITLE
make link providers generic to allow extensions to contribute

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#140182]
Can we make this:

```ts
getLinks(providersIds: string[], y: number): Promise<IDetectedLinks | undefined>
```

That way we can avoid extra work and ensure the links are detected as fast as possible, the validated local link provider for example needs to go to disk which could be particularly slow in remote.

Going more generic would be best as then we can support extensions and other link types easily in the future, perhaps this should just be:

```ts
getLinks(providersId: string, y: number): Promise<ILinks[] | undefined>
```

And then it's up to the quick pick to fetch the right ones, something along the lines of this?

```ts
const links: Map<string, ILinks[]> = Map();

await Promise.all([...providerIds.map(e => {
  getLinks(e, y).then(typeLinks => {
    links.set(e, typeLinks);
  })
]);
```

Can defer making this more generic until extension link providers get done.

_Originally posted by @Tyriar in https://github.com/microsoft/vscode/pull/140121#discussion_r778441492_

**Comment by meganrogge** [comment]
https://github.com/microsoft/vscode/pull/140121#discussion_r779125430

**Comment by FranklinYu** [comment]
I’m interested in the possibility of “extension registering link providers” for terminal. Would that be covered in this issue, or am I supposed to create a stand-alone feature request?

**Comment by Tyriar** [comment]
I can't remember the context of this issue, we have link providers as stable API now which I guess happened after this?
