### ISSUE TITLE
M1 Universal Build Hangs on workspace search over multiple directories

### ISSUE THREAD

**Issue by wsbastian** [microsoft/vscode#140173]
# Overview
When working in a workspace comprised of many explicitly added directories, VSCode hangs and takes a long time to complete the search.

This behavior is not evident when adding a single directory with the same/many subdirectories and doing the same search

# Steps to reproduce
* Use the latest VScode universal build on M1/Monterey
*  Build a workspace comprised of many folders, which each folder being relatively complex
*  Conduct a global search
*  Observe VSCode hang, and lock up other windows
*  (At this point opening unopened files in the workspace will hang, the file will open when the search is complete)

(The above steps can be done without issue, delay and/or hanging) when opening the folders' parent directory and doing a global search

## Sytem Information
CPUs | Apple M1 Pro (10 x 24)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 4, 7, 7
Memory (System) | 32.00GB (0.55GB free)
Process Argv | --crash-reporter-id f3e48c32-d2eb-4266-b34b-e2a73f5d3a4d
Screen Reader | no
VM | 0%

## Extensions
Extensions: none

## A/B Experiment Info
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710:30416614
vscexrecpromp3t3:30407764

## Performance Profile Attachment
This captures:
1. Conducting a global workspace search (takes a long time to complete)
2. Then, opening a file from the workspace (hangs)
3. Finally, search completes (>40s later), and the file opens.

[multi-directory-workspace-search.json.zip](https://github.com/microsoft/vscode/files/7816680/multi-directory-workspace-search.json.zip)

**Comment by roblourens** [comment]
I probably just need to limit the number of simultaneous searches. Thanks for the profile, but it's not obvious what caused a hang. When you say "hang", do you mean that if you clicked in the window it would not respond?

**Comment by wsbastian** [comment]
@roblourens that's correct - VSCode along with other (all? - feels like it, but that's a broad statement) apps become unresponsive. Chrome for instance will report a page has stopped responding if attempts to reload it happen during this time.

Once the search completes, everything bounces back.

For reference, doing the global search over a single folder with many subdirectories is sub 1s.
The same search over each subdirectory added to the workspace is > 40s.

Happy to provide any other insights from my local if it's helpful.

Cheers.

**Comment by wsbastian** [comment]
Adding some additional anecdotal information - 

1. The number of directories that result in VSCode becoming unresponsive appears to be somewhat(?) nondeterministic. For instance, adding directories (0..n) will not result in the behavior. Adding directory n+1 will result in the global search making vs code unresponsive. Removing directory n+1 does not return to an immediate search returning.
2. Testing the above with combinations of different directories provides consistent behavior: variable thresholds for global search locking VSCode, seemingly not directly related to the number of directories, nor the directories themselves.
3. That is, the trigger point for global search locking up VSCode seems to be somewhat dynamic, and not immediately reversible.
4. The one constant is that inevitably through adding addition directories to the workspace, eventually global search will cause the app to hang.

**Comment by wsbastian** [comment]
Is there any other info I can provide on this or otherwise contribute to move this forward? Would love to do what I can.

**Comment by wsbastian** [comment]
This issue has been remedied by a recent VScode build; multi-root workspaces are no longer locking up during global-search.

**Comment by roblourens** [comment]
Thanks for following up!
