### ISSUE TITLE
Opening `edt active ` when ctrl+tab without editors feels wrong

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140102]
Repro:

1. Close all tabs
2. Ctrl+tab

I'd expect it to simply do nothing, not open and leave focus in the quick pick

![image](https://user-images.githubusercontent.com/2193314/148090512-20a32cde-599c-47f9-9c35-260d10f1e835.png)

**Comment by bpasero** [comment]
Arguably those commands probably shouldn't even be enabled when no editor is opened?

**Comment by bpasero** [comment]
Up for grab, the action seems to be the subclasses of [`AbstractQuickAccessEditorAction`](https://github.com/microsoft/vscode/blob/a7d6b0fc328e5768a50129d6400f0eaef42be5d3/src/vs/workbench/browser/parts/editor/editorActions.ts#L1412)

**Comment by Tyriar** [comment]
Thanks!
