### ISSUE TITLE
New integrated terminals are never GPU-accelerated

### ISSUE THREAD

**Issue by jaminthorns** [microsoft/vscode#140128]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: macOS 11.6.1

Even if `terminal.integrated.gpuAcceleration` is set to `on` or `auto`, newly opened integrated terminals will never be GPU-accelerated. Whenever the `terminal.integrated.gpuAcceleration` setting is changed while an integrated terminal is open, the behavior is corrected.

To be a little clearer, for newly opened integrated terminals, when the `terminal.integrated.gpuAcceleration` setting is:

- `off` or `canvas`, terminal behaves as expected.
- `on` or `canvas`, terminal scrolls slowly as if it's not being GPU-accelerated (seems to behave like `canvas`).

After changing from one setting to another, unexpected behavior in open integrated terminals is corrected. Terminals opened after the change will exhibit the unexpected behavior again.

Here's a video to demonstrate the issue:

https://user-images.githubusercontent.com/6618434/148135080-c905eb32-b6f8-4b6c-af71-49fe48143f00.mov

**Comment by Tyriar** [comment]
Can you enable trace logging and paste in the output? We log when falling back to other renderers so maybe that will give us the answer https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by meganrogge** [comment]
can reproduce the problem

**Comment by jaminthorns** [comment]
@Tyriar Here's another video of me reproducing the issue:

https://user-images.githubusercontent.com/6618434/148271626-dcc8afe8-f01a-4cef-87fa-bf854e01e951.mov

And here's the log file that was generated from that reproduction: https://pastebin.com/QM4Rm3C1

Looks like @meganrogge already fixed the issue, though. Thank you! 😁

**Comment by alexr00** [comment]
I don't think I can repro this in stable. What is the best way to repro + verify this?

**Comment by Tyriar** [comment]
To verify:

1. Enable trace logging
2. Open a terminal, ensure `Webgl was loaded` shows in logs
3. DOM inspect the terminal, there should be 3 canvases (webgl renderer), not 4 (canvas renderer)
