### ISSUE TITLE
All extensions are gone

### ISSUE THREAD

**Issue by Sid110307** [microsoft/vscode#140141]
Does this issue occur when all extensions are disabled?: Yes, it occurs irrespective of whether they are disabled.

I opened VS Code today, and found that all of my extensions were gone. I had signed in with GitHub with settings sync. I don't know how this happened. Usually, I have extensions like Atom Material Theme, GitLens, GH Copilot, etc., but today, all of them were somehow gone.

- VS Code Version: `1.63.2`
- OS Version: `Linux x64 5.10.0-9-amd64`

**Comment by sandy081** [comment]
Sorry about that. Let's see what would have cause it. Can you please share following logs?

- F1 > Open View... > Log (Settings Sync)

If you are syncing, then you can restore your extensions by following this - https://code.visualstudio.com/docs/editor/settings-sync#_restoring-data

In that view where you can restore data, you can also see which machine of yours has actually removed your extensions.

**Comment by sandy081** [comment]
I do not see any removal of extensions in this session. Mostly the extensions are removed in previous session. You can get logs of previous session using trouble shooting view

<img width="462" alt="image" src="https://user-images.githubusercontent.com/10746682/148231975-7c6e050b-42ac-402e-a98f-087112a629eb.png">

Can you please figure out which machine of yours has removed the extensions from the Sync Activity (Remote) view

**Comment by Sid110307** [comment]
![image](https://user-images.githubusercontent.com/67900745/148331903-199596b7-2ed3-48c0-b040-3edc3dccb30d.png)
![image](https://user-images.githubusercontent.com/67900745/148331957-7b225c86-787a-416b-ba91-797202ece41f.png)
![image](https://user-images.githubusercontent.com/67900745/148331997-a4fa8a00-52a2-4273-847f-6ede06fe1009.png)

This is what I get. Nothing about extensions.

I just had to reinstall whatever extensions I remember I had manually.

Troubleshoot view:

![image](https://user-images.githubusercontent.com/67900745/148332158-5157a82d-6905-43ed-850f-0a479e81a3ab.png)
![image](https://user-images.githubusercontent.com/67900745/148332225-57603f3b-03bd-4bbc-8302-df9cb0ae34b8.png)
![image](https://user-images.githubusercontent.com/67900745/148332254-0c99aa11-83eb-4f79-aef8-ca08d82aa1d8.png)

**Comment by sandy081** [comment]
Have you disabled syncing extensions? Can you please check your settings sync configuration options?

**Comment by Sid110307** [comment]
Yes, I disabled it after all extensions went because I'm currently using [this](shanalikhan/code-settings-sync).

**Comment by sandy081** [comment]
We are very sorry about this - But we have some good news for you. You can restore all your data from the cloud. Please see this doc - https://code.visualstudio.com/docs/editor/settings-sync#_restoring-data

Coming back to the issue - lets see why the settings sync has not synced properly. Can you please share the logs during which you the sync went wrong? You can find the history of settings sync logs from following location: `F1 > Settings Sync: Show Synced Data > F1 > Open View... > Troubleshoot (under Settings Sync Section) > Logs`

You can also check which system of yours has synced and pushed wrong data into the cloud from the following view: `F1 > Settings Sync: Show Synced Data  > Sync Activity (Remote) view`

Please share us with this information to know what has gone wrong.

Thanks
