### ISSUE TITLE
vscode fails to open last project after update and defaults to last opened file in dssktop files list

### ISSUE THREAD

**Issue by drankinatty** [microsoft/vscode#140144]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0

- OS Version:
OS: Linux x64 4.12.14-lp150.12.82-default- 

Steps to Reproduce:

1.  Close vscode normally prior to update an Linux. Do some other work that manipulates files. Now update to latest version of vscode.
2. Vscode now opens with the last file used (a LibreOffice writer `.odt` file that had been exported to `.pdf` in this case) instead of opening the last project open in vscode before update.

This appears to be something in the last couple of updates. Originally vscode did not have this problem and would consistently open the last active project across updates. The past two (maybe three) updates are no longer consistent. Further, while the only editing done in vscode is C/C++ (1.7.1 extension). Now it opens documents that have no relations to programming at all. 

Where vscode should have opened the last open project with config in `~/dev/src-c/tmp`, instead after update it opened with `~/Documents/law/XXXXX_XXXXX/pld/filed/` (client name redacted) where there was no `.vscode/` config at all. Opening two `.pdf` files, specifically

```none
002_answer-1st-amended-cc-jury.pdf
002_answer-1st-amended-cc-jury_file-stamped.pdf
```

I don't know where vscode went wrong, but it appears it is attempting to read from the XDG `recently-used.xbel` file in `~/.local/share`. That makes no sense at all.

Thought I would pass this along so whatever is causing the loss of last project directory across updates can be fixed.

This also seems to be related to the last document handled (downloaded) by Firefox (the file-stamped version of the pleading retrieved from the court after filing). The apparent entry that was used by vscode was:

```none
  <bookmark href="file:///home/david/Documents/law/XXXXX_XXXXX/pld/filed/002_answer-1st-amended-cc-jury_file-stamped.pdf" added="2022-01-04T21:32:41Z" modified="2022-01-04T21:32:41Z" visited="2022-01-04T21:32:41Z">
    <info>
      <metadata owner="http://freedesktop.org">
        <mime:mime-type type="application/pdf"/>
        <bookmark:applications>
          <bookmark:application name="Firefox" exec="&apos;firefox %u&apos;" modified="2022-01-04T21:32:41Z" count="2"/>
        </bookmark:applications>
      </metadata>
    </info>
  </bookmark>
```
Let me know if there is anything else I can provide.

**Comment by bpasero** [comment]
A list of exact steps how to reproduce step by step from a fresh workspace start (i.e. `code-insiders --user-data-dir <some empty folder>`).
