### ISSUE TITLE
Starting a editor tab drag operation is taking a long time

### ISSUE THREAD

**Issue by k3179** [microsoft/vscode#140188]
Issue Type: <b>Bug</b>

Switching to different file tabs takes average of 2 sec to open the file

when i click "Release Notes:xxx" tab , it's very quick , and no performance bug. but when i start to click a local file , it takes 2 or 3 second until the tab changed to dragable mode. dual the stuck times , cpu use from 5% to 25% and get back 5% when it's changed to dragable mode.

code --disable-extensions , still happens

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 6.2.9200
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (11.29GB free)|
|Process Argv|--crash-reporter-id b7e7c0bf-917b-4c7a-be4d-8a59d99cf89b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.0
php-debug|fel|1.22.0
anes|gam|0.0.2
vscode-language-pack-zh-hans|MS-|1.63.3
sftp|Nat|1.15.10
laravel-blade|one|1.29.0

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by k3179** [comment]
it's same as vscode none insider version.

VS Code version: Code - Insiders 1.64.0-insider (9afbea7caab9dd06592ddd98aa4161b43b126d3f, 2022-01-06T05:15:07.481Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.23GB free)|
|Process Argv|--crash-reporter-id a1b4e353-f028-4d61-a79d-c442dadc1669|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
vscop804cf:30404767
vscop940:30404999
vsclayoutctrc:30405799
py55gd98:30408621
vscexrecpromp3t1:30407758
azactmsalcf:30409288

```

</details>

**Comment by k3179** [comment]
![Recording 2022-01-07 at 15 15 10](https://user-images.githubusercontent.com/7879755/148506457-cbb8f172-5816-4f24-9bf9-3f063b220779.gif)

**Comment by bpasero** [comment]
Wait, that is a drag and drop operation? That does not look like "switching file tabs"?

**Comment by k3179** [comment]
![Recording 2022-01-07 at 15 18 18](https://user-images.githubusercontent.com/7879755/148506780-c105638e-acd4-4f3d-8fb1-44c76ffd6c6c.gif)

**Comment by k3179** [comment]
yes, it's drag and drop operation , sorry for my english

**Comment by bpasero** [comment]
Are you running with special user rights? Maybe as admin?

**Comment by k3179** [comment]
"net localgroup Administrator returns" include my user name  , seem like i have admin permission , but not the Administrator

**Comment by bpasero** [comment]
Can you reproduce with a different user that does not have admin?

**Comment by k3179** [comment]
i'm sorry , i have no permission to create a new user to my pc , maybi'm sorry , i have no permission to create a new user to my pc , maybe i can try at home later.e i can try at home later.

**Comment by bpasero** [comment]
👍

**Comment by k3179** [comment]
there's no problem except my office pc...
