### ISSUE TITLE
speaker as output not recognized

### ISSUE THREAD

**Issue by mynameish4r01d** [microsoft/vscode#140137]
Issue Type: <b>Bug</b>

Dear VSCODE developers,

I was just wondering if it's possible to change speaker output? so instead of using my laptop speaker and laptop mic, I want to use different output and input devices. I already tried changing it in settings and it still does not work but when I open other apps such as Audacity it recognizes the speaker and mic, so what gives???

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|23.75GB (16.30GB free)|
|Process Argv|--disable-gpu|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-jetbrains-keybindings|isu|0.1.9
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30416617
vscexrecpromp3t2:30407763

```

</details>

**Comment by joaomoreno** [comment]
What sounds exactly does VS Code emit?

**Comment by mynameish4r01d** [comment]
> What sounds exactly does VS Code emit?
> 
> Can you share a screenshot of the feature?

i am using a text to speech

**Comment by joaomoreno** [comment]
So, is this an error with the _text to speech_ app you are using?

**Comment by mynameish4r01d** [comment]
> So, is this an error with the _text to speech_ app you are using?

I just thought it might be visual studio and if there is anyway to change the audio output

**Comment by joaomoreno** [comment]
No, that sounds like a setting of the text to speech app you are using.
