### ISSUE TITLE
`Open Recent` files/folders disappear when using external storage

### ISSUE THREAD

**Issue by traviswimer** [microsoft/vscode#140266]
Issue Type: <b>Bug</b>

**To reproduce:**

1. Open folder on external storage device (e.g. external SSD, etc).
2. Close VS Code.
3. Disconnect external storage device.
4. Open VS Code.
5. Reconnect external storage device.
6. Click `File --> Open Recent`

**Actual result:**

The folder that was opened from the external device will not be an option in the displayed list.

**Expected Result:**

Files/Folders in the `open recent` list should remain even if they have temporarily disappeared.

My guess would be that this behavior is intentional, with the purpose of removing deleted directories from the list. Although that makes sense, I imagine my use-case of using external storage is also fairly common.

So, I'm not sure if this functionality should be changed by default, but it would be very helpful if there was a setting to allow the full list of recently opened files/folders to be retained regardless of whether they no longer exist.

---------

**VS Code Data**

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (4.08GB free)|
|Process Argv|--crash-reporter-id e7dd9b71-99a9-498f-ae5a-aef921789915|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.32.0
flutter|Dar|3.32.0
vscode-eslint|dba|2.2.2
javascript-ejs-support|Dig|1.3.1
gitlens|eam|11.7.0
prettier-vscode|esb|9.1.0
vscode-flow-ide|gca|1.2.0
vscode-graphql|Gra|0.3.41
vscode-styled-components|jpo|1.7.0
stretchy-spaces|kyl|0.1.0
vscode-format-context-menu|lac|1.0.4
vscode-ios-common-files|Ort|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710cf:30416617
py55gd98:30419165
vscexrecpromp3t3:30407764

```

</details>

**Comment by bpasero** [comment]
Prior art: https://github.com/microsoft/vscode/issues/128107

**Comment by traviswimer** [comment]
How are there not more people bothered by this bug? I have to deal with annoyance at least once every day.

**Comment by traviswimer** [comment]
Well, apparently they fixed this anyway. 🎊🎉
