### ISSUE TITLE
Feature Request: Toggle "Find in Files" search hits can ignore marked out values.

### ISSUE THREAD

**Issue by brettvatech** [microsoft/vscode#140294]
Hello all.  Longtime listener, first-time caller.  As the subject implies, it would be pretty nifty to allow Find in Files to ignore marked out terms when searching for a word/string.  I apologize if similar is already possible today.

**Comment by gjsjohnmurray** [comment]
What do you mean by "marked out"?

**Comment by brettvatech** [comment]
Commented out / remarked, like the script itself won't execute the line.

**Comment by ArturoDent** [comment]
If you mean don't search in comments, probably a dup of https://github.com/microsoft/vscode/issues/11688.

**Comment by brettvatech** [comment]
Not necessarily just commented things, but say we used to use a variable of
$var1 in like a PowerShell script, and along the way moved to $var2 and
left the $var1 there for historical reference.  Now, in most of my
searches for $var1, I'd want to see where the variable was period, but then
in certain search cases, I might only want to see where it's still in use;
i.e., not commented out.

**Comment by brettvatech** [comment]
This has nothing to do with just comments, why did you close it?

**Comment by roblourens** [comment]
Language-specific smarts in search is probably out of scope, just given the way search works. You might be looking more for something like "find all references" or another language feature.
