### ISSUE TITLE
Workbench › Panel: Default Location setting doesn't work in Insiders

### ISSUE THREAD

**Issue by samestep** [microsoft/vscode#140287]
As of Wednesday 2022-01-05, the Insiders build does not respect the **Workbench › Panel: Default Location** setting, and instead always puts the panel on the bottom. This issue does not occur in Stable, and if I remember correctly, it also didn't occur in the Insiders build on Tuesday 2022-01-04.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.0-Insider (Universal); Commit: 419e16a49c7bffc23b8e5f0f9f35ee34167f20e1
- OS Version: macOS Big Sur Version 11.6.2

Steps to Reproduce:

1. Open Visual Studio Code: Insiders.
2. Disable all extensions.
3. Set **Workbench › Panel: Default Location** to "left".
4. Reload the window.
5. Open the terminal.
6. Observe that it is on the bottom of the window rather than the left.

<img width="1173" alt="Screen Shot 2022-01-07 at 11 47 10 AM" src="https://user-images.githubusercontent.com/8246041/148577469-298786e9-50ab-4be8-814a-81f8a04c4c18.png">

**Comment by bpasero** [comment]
@sbatten

**Comment by samestep** [comment]
This morning I was able to reproduce the same bug on two other operating systems:

- VS Code Version: 1.64.0-Insider (Universal); Commit: 419e16a49c7bffc23b8e5f0f9f35ee34167f20e1
- OS Version:
  - Windows 10
  - Ubuntu 20.04.3 LTS

I also did a bisect (on Ubuntu) and found the following:

- 419e16a49c7bffc23b8e5f0f9f35ee34167f20e1 bug
- 7e4ed924c107fcf0eb5da96d57c3e90760d919db bug
- 6ce37ef7a2ad0d093edc5d5ae38d8f3acd9ed8c7 bug
- ed86704006ff38f456b27ed6476f1e78d0ea5e89 bug
- a3482c39bc57ebab1318db3708a777753f956248 bug
- 02d46ca95c7af2d87bb49a8e4974655df7f917f9 bug
- f0e8c022f961a59b2fbbb391e61d09c2f3a1ab64 no bug
- f0cc5604d7fd0739bc10c0cc5e956699dc4fbbde no bug
- d7074440efac022d92f099a30bb72a5cbee7ca0f no bug

So this bug seems to have been introduced by 02d46ca95c7af2d87bb49a8e4974655df7f917f9 (#139043).

**Comment by sbatten** [comment]
actually due to this long time confusion, I'm taking the opportunity to update the behavior of the setting to function like other workbench parts https://github.com/microsoft/vscode/issues/67639... changing the location setting, will update the position automatically without a reload

**Comment by IanMatthewHuff** [comment]
@sbatten Is this just the verification? The commits linked look like the setting was removed:
![image](https://user-images.githubusercontent.com/812783/151268475-7db3a48e-c967-43f9-a93b-c9b0d8fbb1ef.png)

**Comment by samestep** [comment]
@IanMatthewHuff See the discussion here: https://github.com/microsoft/vscode/pull/140742
