### ISSUE TITLE
breakpoints unbound sourceMaps available

### ISSUE THREAD

**Issue by nileio** [microsoft/vscode#140273]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.55.2
- OS Version: MacOS

Steps to Reproduce:

1.generate sourcemaps, enable sourcemaps `sourceMaps: true`
2.no breakpoints are hit

this is Chrome debugger. The client-side Javascript loaded in the browser as `.html` files. This is the way [Node-RED](https://github.com/node-red/node-red) loads client-side javascript. it uses `eval` statements, extracts `script` tags , etc.
I had this working successfully in earlier versions of VSCode. 
My sourceMap is created successfully, and have the correct `file`,`sourceRoot`, `sources` entries.
Example SourceMap content
```
"version":3,
"sources":["/src/example_node/node.html"],
"names":["code","code"],
"mappings":["blabla","blabla"],
"file": "/src/example_node/node.html"
"sourceRoot": "/Full/Path/to/Source/Root/"
```
the script is loaded and I can see it in VSCode.
Now I tried alot of things to get the sourceMap be used.
Example
`outFiles`,
`pathMappings` -> this should be needed to map `/src/` to workspace `src` directory.

I ran out of all possibilities, and tried to use the trace file (which seem to have changed alot from previous versions) - could not figure out how to fix this for days.

Any pointers, ideas please?

Note: without any config I could get IDEA to recognise and use the sourceMap, but it is frustrating because I only use it for that. I want to continue using VSCode

**Comment by nileio** [comment]
I created those trace logs and checked the information in the website. I can't see errors or issues there.
what should I be looking for ?
Note: the older version of VSCode log files were much more better and readable, and in fact pointed out issues. No idea why things change so often.

**Comment by connor4312** [comment]
Please share the log files so I can diagnose your issue.

**Comment by nileio** [comment]
@connor4312 just emailed it

**Comment by connor4312** [comment]
Thanks for the logs. The first thing I notice is that `/src/cryptobot/nodes.html` declares its sourceMapURL as `/src/cryptobot/nodes.html.map`, but the server 404's when hitting `http://localhost:1880/src/cryptobot/nodes.html.map`, so that's something in your setup you will want to address. Note that you can also set the `sourceMapURL` to be a file URI to have js-debug read the sourcemap from disk rather than from the server, if desired.

Also, I noticed you're on debugger version 1.55.2, which is going on a year old at this point. You may want to update that to get the latest fixes, improvements, and features.

**Comment by nileio** [comment]
@connor4312 how to update the debugger ? my VSCode is up to date.

In terms of 404 issue.. My understanding was `pathMappings` keys should successfully resolve it to the file on disk. I had it working successfully in previous VSCode versions with this setup
my `pathMappings` looked like
```
"/src/" : "${workspacefolder}/src/"
```
am I doing something wrong here?
I dont want to expose any `.map` on any route on the server side..

**Comment by connor4312** [comment]
Currently `pathMapping` only affects the resolution of source files and doesn't participate in the [resolution of sourceMapURLs](https://github.com/microsoft/vscode-js-debug/blob/83c459400f16f0056897f2e50d2109e40d02eb28/src/common/sourceMaps/sourceMapFactory.ts#L114-L131).

**Comment by nileio** [comment]
@connor4312 hmmm this is news to me! This does not follow the specs for `sourceMapURL` in my view.
check https://sourcemaps.info/spec.html
```
Regardless of the method used to retrieve the source mapping URL the same process is used to resolve it, which is as follows:
When the source mapping URL is not absolute, then it is relative to the generated code’s “source origin”. The source origin is determined by one of the following cases:


If the generated source is not associated with a script element that has a “src” attribute and there exists a //# sourceURL comment in the generated code, that comment should be used to determine the source origin. Note: Previously, this was “//@ sourceURL”, as with “//@ sourceMappingURL”, it is reasonable to accept both but //# is preferred.
If the generated code is associated with a script element and the script element has a “src” attribute, the “src” attribute of the script element will be the source origin.
If the generated code is associated with a script element and the script element does not have a “src” attribute, then the source origin will be the page’s origin.
If the generated code is being evaluated as a string with the eval() function or via new Function(), then the source origin will be the page’s origin.
```
I have `sourceURL` in the generated code comments too

**Comment by connor4312** [comment]
We are following that specification. The `sourceURL` is `/src/cryptobot/nodes.html` (at least according to what Chrome says). This is an absolute path but not a complete URI, so the origin is the same and it resolves as `http://localhost:1880/src/cryptobot/nodes.html`. Then, the sourceMappingURL from that is another path, so it stays on the same origin.

`pathMapping` is a concept exclusive to VS Code, and we just don't apply it before trying to load the sourceMappingURL.

**Comment by nileio** [comment]
@connor4312 I tried with an absoulte path, both with `file:///` and without it. so in this example the comments as
```
//# sourceURL=/complete/path/to/source.html
//# sourceMappingURL=/complete/path/to/source.html.map
```
also tried
```
//# sourceURL=file:////complete/path/to/source.html
//# sourceMappingURL=file:////complete/path/to/source.html.map

```
still no change.
I removed `pathMapping` and removed `outFiles` tested without them and with them..
I am not sure how VSCode debugger actually works to resolve the source maps. It is also confusing because a year ago version of VSCode worked fine. IDEA works fine using the same comments too

**Comment by nileio** [comment]
I finally got it to work but changing to absolute path in the sourceMap itself
both `sources`, `file` and `sourceRoot` in the sourceMap is now absolute path. This is Ok since I dont ship the `.map` file with my code.
However, I also needed to have an absolute path for `sourceMappingURL` . the comments now look like
```
//# sourceURL=/relative/path/to/source.html
//# sourceMappingURL=/complete/path/to/source.html.map
```
I like to avoid having an absoulte path for `sourceMappingURL` because those comments are usually left behind there - or I may need to clean those up as I dont wish to show full path of dev machine in a distribution code, however, this maybe minor thing and perhaps even recommended. 
Anyway I am glad it is working now. Thanks for ideas @connor4312 
Not sure if there is any enhancements that can be derived from this in the way sourceMaps are being resolved by VSCode given my setup was working out of the box with IDEA for example. 
I recommend using `pathMapping` key or another similar key that we can use to map to physical locations

**Comment by nileio** [comment]
@connor4312 Ok I see.. 
I am sure my original launch configuration was working fine in an older version of VSCode which I suppose was using the old Chrome Debugger.

I am not sure how IDEA does it but I now have all paths as absolute paths and removed `sourceRoot` from source map, that is , set to empty string.
in IDEA there is a configuration where you "map" local folder to a url .. I suppose this was the reason it worked. So my suggestion here is having "pathMappings" in launch configuration working for source maps too..
