### ISSUE TITLE
Pixeled mouse cursor on tab bar next to tabs

### ISSUE THREAD

**Issue by VOOM108** [microsoft/vscode#140289]
Issue Type: <b>Bug</b>

The cursor shown on the tab bar, where a double click opens a new tab, is a "hand touch" cursor which cannot be changed in windows settings and for one makes no sense (should be simple pointer) and also is pixeled grocely. (Note: this is not the hand pointer for links!) See attached image taken without any extensions active. My screens are UHD scaled to 150% - all other cursors display fine. 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (43.38GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 89fc7b7f-a14e-42c2-a456-7da04cf6efee|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

![pixeled-cursor](https://user-images.githubusercontent.com/16562946/148580697-f9db0765-799c-4dfc-9fb0-143474b43cdc.png)

**Comment by gjsjohnmurray** [comment]
I think it's a hand because you can drag this area. For example, try this:

1. Open a file.
2. Split Editor Right using the button on the upper right of the window.
3. Double-click in the are to the right of the file's tab in the right-hand split. This creates an untitled file.
4. Repeat step 3 to create a second untitled file.
5. Close the right-hand group's copy of your original file.
6. Now drag the pixelated hand from the right group and drop it onto the left group. This transfers the two untitled files onto the left group and closes the right group.

**Comment by VOOM108** [comment]
It also appears when there is no target area to drag the tabs to, which I find irritating. And it is really ugly... ;) Of course it is a Windows-issue that this cursor is nowhere to be changed and has never been updated to HighDPI apparently, but maybe there is another way to achieve this within VS Code? I have never seen this cursor in any other app ever....

**Comment by VOOM108** [comment]
I checked the behavior once more; when there is no split view, the active tab can be dragged and shows a pointer-hand (like over URLs), while dragging from the empty space in the bar also drags the active tab, now showing the (ugly) touch-hand, though. This is also inconsistent. The easiest fix would probably be to always use the pointer-hand.

**Comment by bpasero** [comment]
As it was pointed out, this works as designed, the editor group is draggable, i.e. you can move all tabs at once.

The fact that the cursor looks bad is something I reported a while ago, but Chrome does not seem to have any interest in fixing it: https://bugs.chromium.org/p/chromium/issues/detail?id=1035285&q=&can=4
