### ISSUE TITLE
Access is denied error when installing visual studio code

### ISSUE THREAD

**Issue by rajeevgoyal22** [microsoft/vscode#140244]
![image](https://user-images.githubusercontent.com/97211089/148330211-6c893ad0-411b-4d64-a75f-d85d90539c15.png)

"Access is denied" error when installing visual studio code
No other information. After clicking OK it rollbacks installation
Is there a way to check log files somewhere to get specific information?
I am running on my personal laptop (Windows 10) and have admin privileges.

**Comment by joaomoreno** [comment]
Strange. Can you install using the System Install package?

**Comment by rajeevgoyal22** [comment]
Thanks for your response. This issue has been resolved. My user profile had some issues, so I renamed the .vscode folder in c:\users\rgoya (rgoya is my user name) . Re-installed and it worked perfectly. I had been having some trouble with my user profile, and had similar issue with some other software packages. After renaming them, they all are working fine.
