### ISSUE TITLE
Progress bar status bug

### ISSUE THREAD

**Issue by ELHoussineT** [microsoft/vscode#140269]
Issue Type: <b>Bug</b>

In a notebook, the progress bar status at the top keeps indicating that the cell is running but it is not.
![image](https://user-images.githubusercontent.com/20634657/148536192-41183916-8cf4-4972-b77b-1097da6e631c.png)

VS Code version: Code - Insiders 1.64.0-insider (Universal) (99305570d885bce929ba8f24d90f2c3ee54c5c2f, 2022-01-03T05:15:53.904Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (12.13GB free)|
|Process Argv|--crash-reporter-id 6a5f1067-1364-4707-a779-b0b66087d6de|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.7.0
copilot|Git|1.7.4421
vscode-pull-request-github|Git|0.35.2021120909
git-graph|mhu|1.30.0
python|ms-|2022.0.1664492081-dev
vscode-pylance|ms-|2022.1.1-pre.1
jupyter|ms-|2022.1.1001614873
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
vsc_aa:30263845
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
vscop804:30404766
vscop940:30404999
vsclayoutctrt:30405800
py55gd98cf:30408622
vscexrecpromp3t2:30407759
azactmsal:30409287

```

</details>

**Comment by roblourens** [comment]
Might have been fixed in the past week, but do you have steps to reproduce this?

**Comment by ELHoussineT** [comment]
I cannot reproduce the issue anymore, seems to be fixed.

**Comment by roblourens** [comment]
Thanks, I am still making changes in this area so let me know if you see it again.
