### ISSUE TITLE
Debug "out of sync" for web extensions using `pwa-extensionhost` approach

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#140218]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: macOS Big Sur 11.6.1

Steps to Reproduce:

1. Create a brand new web-extension, using `yo code`
2. Open in VS Code
3. Add a breakpoint on any line of code
4. Build and Start Debugging (which means the `pwa-extensionhost` approach)
5. Try to run the `Hello World` command
6. You will notice the breakpoints are out of sync

![Kapture WebExtension Debug Out of Sync - Short](https://user-images.githubusercontent.com/3781424/148399448-527abb6d-9918-470d-b9ff-55ae130efa92.gif)

I'm trying to update my extensions to be web ready, but even being _apparently_ able to produce the web-ready portion of an extension, the debugging process is not working correctly (and I really like to debug stuff on each scenario). 

I tried to _skip_ the debugging process and test the extension using the Sideload approach explained in the documentation, but had no success either, as commented here https://github.com/microsoft/vscode/issues/138623#issuecomment-1003183147. In this case, I'm not sure it is an issue in the tooling or my machine. 

Thank you

**Comment by weinand** [comment]
I can reproduce this.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/136242
