### ISSUE TITLE
Allow spin animation for vscode.TreeItem icons when using custom SVG

### ISSUE THREAD

**Issue by zaycev** [microsoft/vscode#140237]
Hi, when constructing `vscode.TreeItem` and providing `vscode.ThemeIcon` it is possible to set spin animation by adding `~spin` to the icon name property.

How can we have the same functionality for icons that are custom SVGs represented as `vscode.Uri`?

Thank you

**Comment by alexr00** [comment]
I expect that you can animate the svg yourself: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animate
