### ISSUE TITLE
Loader produces (seemingly) invalid SVGs when inlining them

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#140281]
I noticed this while running the minification step locally:

```
[14:38:20] gulp-postcss: vs\workbench\workbench.desktop.main.css
cssnano: C:\Users\jomo\Work\vscode\out-vscode\vs\workbench\workbench.desktop.main.css:10023:2: Error in parsing SVG: Non-whitespace before first tag.
Line: 0
Column: 1
Char: %
cssnano: C:\Users\jomo\Work\vscode\out-vscode\vs\workbench\workbench.desktop.main.css:10493:2: Error in parsing SVG: Non-whitespace before first tag.
Line: 0
Column: 1
Char: %
``` 

These refer to the SVGs referenced in, which were inlined into the CSS:

- https://github.com/microsoft/vscode/blob/112ca126f6f86387f6054e8d55544d97f72f34ef/src/vs/workbench/contrib/extensions/browser/media/extensionEditor.css#L354
- https://github.com/microsoft/vscode/blob/1ddaeae9bedb1d5d084b0142dcc9e799d4540568/src/vs/workbench/contrib/extensions/browser/media/extensionsViewlet.css#L96

I'm not sure why the `postcss` tool complains, if the browsers handle these SVGs just fine... but it might be worth a peek?

Also found in build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=148932&view=logs&j=bd1e231b-cef9-51a2-e461-b67194c0a817&t=9cc46b07-0f4a-51e5-598b-b142e2b8a72a&l=132

**Comment by joaomoreno** [comment]
Oh nice, there was something there after all! ❤️ thanks!

**Comment by alexdima** [comment]
Yes, thanks for spotting! :)
