### ISSUE TITLE
Hover delay time is half what `editor.hover.delay` specifies

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#140212]
Issue Type: <b>Bug</b>

1. Set `editor.hover.delay` to 2000
2. Hover, and observe that the hover appears after 1 second rather than 2 :bug:
3. Set `editor.hover.delay` to 10000 which is the undocumented clamped maximum for this setting.
4. Hover, and observe that the hover appears after 5 seconds rather than 10  :bug:

VS Code version: Code - Insiders 1.64.0-insider (9afbea7caab9dd06592ddd98aa4161b43b126d3f, 2022-01-06T05:15:07.481Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by trevyn** [comment]
Bisected commit mentioned here: https://github.com/microsoft/vscode/issues/139818#issuecomment-1003228021

**Comment by alexdima** [comment]
Duplicate of #139818
