### ISSUE TITLE
Incorrect selection change event kind when clicking on any text

### ISSUE THREAD

**Issue by langmf** [microsoft/vscode#140288]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.63.2 (user setup)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 6.1.7601

### Steps to Reproduce:
Create an extension to log selection change events:

```
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext): void {
    context.subscriptions.push(
        vscode.window.onDidChangeTextEditorSelection(function(e) {
            console.log('Selection changed:', e.kind);
        })
    );
}
```
Click with the mouse in any position, and then click somewhere in another position. The selection change event that gets logged is of kind 3 (Command), but I would expect it to be of kind 2 (Mouse). 

See screencast:
![kind](https://user-images.githubusercontent.com/12271618/148579379-fb409794-cc43-444f-935d-65f38db48107.gif)

**Comment by rebornix** [comment]
I'm not seeing this in latest Insiders, can you confirm if you can reproduce with all other extensions disabled?

**Comment by langmf** [comment]
I created a new extension, and only it is included.
I attach it here
[test.zip](https://github.com/microsoft/vscode/files/7876526/test.zip)
.

**Comment by langmf** [comment]
In version 1.65, added new bug **e.kind** may be undefined when toggle tabs with files.
