### ISSUE TITLE
zsh unable to run OSS prelaunch task

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#140236]
1. Try to debug OSS on macOS. I'm using the exploration build, but I can repro the problem in Insiders.
2. :bug: Get the following error: `The terminal process "zsh '-c', 'node build/lib/preLaunch.js'" terminated with exit code: 127.`

None of my settings are modified. I notice that if I remove the comma in between, then I can run the command from the integrated terminal just fine.

**Comment by alexr00** [comment]
@rzhao271 can you share any `terminal` settings you have changed? I asked someone with macOS to try this out, and it worked as expected for them.

**Comment by rzhao271** [comment]
Unable to repro on the latest Insiders.
