### ISSUE TITLE
Network mapped drive folder very slow - does not work

### ISSUE THREAD

**Issue by carlhua** [Microsoft/vscode#14026]
VSCode Version: 1.6.0
OS Version: Windows 10
Steps to Reproduce:

open any folder that is a network mapped drive
go to def on any item, takes extremely long time.
search - takes extremely long time
language doesn't matter, so its not a language service issue.

**Comment by roblourens** [comment]
Is it slower than another editor? I would expect it to be slower than a local folder.

**Comment by carlhua** [comment]
Yes. not usable. go to def pretty much does not work.

**Comment by roblourens** [comment]
If you do go to def twice on the same thing, is it just as slow the second time?

**Comment by carlhua** [comment]
Yes. Could take minutes.

**Comment by dbaeumer** [comment]
@carlhua is the TypeScript or JavaScript ?

**Comment by carlhua** [comment]
C files

**Comment by dbaeumer** [comment]
Do you have a C extension installed? If so I would recommend opening an issue with the extension. 

When you refer to search you are referring to textual search inside VS Code.

**Comment by carlhua** [comment]
Any files. Not just c. So it's not an extension issue

**Comment by carlhua** [comment]
It is not an extension issue. And it is a vscode issue because any file mounted remotely won't work.

**Comment by dbaeumer** [comment]
@carlhua it is a VS Code issue and a extension issue. This is why I didn't close this issue. However something like goto definition in a C file requires the C extension to make this fast. VS Code doesn't have the logic for this. However textual search is VS Code core code and if that is slow we need to look into this in the VS Code base. So I still think that you need to open issues against the C extension regarding slowness of language features (code complete, goto definition, find references, ...).

**Comment by dbaeumer** [comment]
@chrmarti assigning to you since the VS Code part is mostly about search performance.

**Comment by chrmarti** [comment]
Is this still an issue? We are using ripgrep now for searching both text and files.

We are tracking an issue with sshfs in https://github.com/Microsoft/vscode/issues/37013.
