### ISSUE TITLE
Support Electron 15.0.0+

### ISSUE THREAD

**Issue by rbrisita** [microsoft/vscode#140249]
Electron 15+ uses the latest LTS Node.js v16+ which contains a lot of desired features for extensions: AbortController and abort-able promises and timers. Is there a time frame in the road map for this?

**Comment by gjsjohnmurray** [comment]
See #137241

**Comment by gjsjohnmurray** [comment]
Also this filter for the open issues

https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aelectron-16-update

**Comment by rbrisita** [comment]
Most excellent! Thank you!

**Comment by deepak1556** [comment]
Thanks @gjsjohnmurray , please follow the PR for updates.
