### ISSUE TITLE
Terminal in Editor area blanks when dragged between panes

### ISSUE THREAD

**Issue by ucirello** [microsoft/vscode#140240]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:38:17.605Z (3 wks ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0

- OS Version: Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64

![image](https://user-images.githubusercontent.com/138827/148460305-73ffb0cb-bb49-475b-b7cb-de38ac13706f.png)

Steps to Reproduce:

1. Invoke "Terminal: Create New Terminal in Editor Area"
2. Split the view into two panes
3. Drag'n'Drop the terminal from one pane into another
4. You get running yet blank terminal

https://user-images.githubusercontent.com/138827/148460420-32d7dc1f-9f2f-458a-9bd2-cefe02618d46.mov

**Comment by AlaaMouch** [comment]
I'm also experiencing this issue on VSCode 1.63.2; you can check the diagnosis info of my system in the duplicate issue up above.

My current workaround, when the editor group is locked and the newly created terminal goes to another editor group (related: https://github.com/microsoft/vscode/issues/135022), is to unlock the former, create the terminal, and re-lock it. It is not unbearable, but it definitely is a productivity disruption.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by AlaaMouch** [comment]
Can confirm that it is fixed in the Insiders build :partying_face:

When will we able to see this fix released? Early february, right?

**Comment by meganrogge** [comment]
yes 👍🏼  /duplicate of #138870 and #139222

**Comment by AlaaMouch** [comment]
Many thanks! Keep up the amazing work! :)
