### ISSUE TITLE
Incorrect inclusion of @types in a TypeScript project

### ISSUE THREAD

**Issue by TomMarius** [Microsoft/vscode#14025]
According to https://www.typescriptlang.org/docs/handbook/tsconfig-json.html, if `"compilerOptions"`.`"types"` is specified, only the types you specify will be included in compilation. VS Code weirdly and unpredictably ignores this - in my case, it uses typings from `@types/node` instead of the one I specified (webpack-env). Compilation itself passes with no errors.

- VSCode Version: 1.6.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. create a Typescript project, install `@types/node` and `@types/webpack-env`
2. specify `"compilerOptions"`.`"types"` (e.g. `[ "webpack-env" ]`)
3. watch how your `require.ensure(...)` gets underlined

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11826
