### ISSUE TITLE
Notebook cell toolbar edit/stop edit button switches position

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#140255]
![jumpy](https://user-images.githubusercontent.com/641685/148496227-cf685013-8c6a-4833-b9b0-09e328b4e76a.gif)

I keep trying to toggle that on and off, and I keep ending up splitting the cell because the button changes position

/cc @rebornix @misolori

**Comment by misolori** [comment]
Given that the split cell is already on a different position that should stay the same which will allow the edit/done button to stay in the same spot.
