### ISSUE TITLE
Support theming of additional integrated terminal colors (for base16 shell)

### ISSUE THREAD

**Issue by chtenb** [microsoft/vscode#140235]
Currently it is possible to theme the 16 ansi colors of the integrated terminal. I would like to request that we can theme at least four more colors (nr 17 to 21) such that we can fully theme a [base16 shell](https://github.com/chriskempson/base16-shell).

**Comment by chtenb** [comment]
Perhaps it is desirable to be able to theme any of the 256 colors, such that all possible ANSI extensions in the 256 color space are covered.

**Comment by Tyriar** [comment]
We'd need a new API in xterm.js for this: https://github.com/xtermjs/xterm.js/issues/3601
