### ISSUE TITLE
Search Editor - Peek Definition displays confusing results

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#140280]
Issue Type: <b>Bug</b>

1. Open a folder (I used the vscode-mock-debug example extension)
2. Search for a word (I used 'provide')
3. Click the "Open in editor" link
4. Double-click the underlined name of a file in which matches were found (I used CHANGELOG.md). Or alternatively use its context menu to choose Peek > Peek Definition.
5. Try to understand what gets shown in the peek area.

![image](https://user-images.githubusercontent.com/6726799/148553292-4202c42c-5756-4627-aa67-c8f748e5484d.png)

When no context lines are being shown in the Search Editor, see how the Peek reports 6 definitions, whereas the search panel (and the editor text behind the peek) shows 3 matches for the search string.

See how the three lines containing the search term are each shown twice in the right-hand panel of the peek, and the matching word is not what is highlighted.

Repeat the peek after enabling context lines:

![image](https://user-images.githubusercontent.com/6726799/148553855-e5e88328-dad0-4eb3-856b-79570f5152a1.png)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by JacksonKearl** [comment]
Good catch, thanks. The peek's count will now match the number of result lines shown. There is still a corner case of having multiple results on the same line which is not accurately handled, unless the results are far enough apart to get a `⟪ ([0-9]+) characters skipped ⟫` added.
