### ISSUE TITLE
make shell integration commands context aware

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#140247]
don't show shell integration commands in quick pick if shell integration isn't enabled

IE if `commandTrackerAddon instanceof NaiveCommandTrackerAddon` or something similar

**Comment by Tyriar** [comment]
What would happen if some terminals have shell integration enabled, just not the active one?

Perhaps we should always show them and treat it as an entry point for the feature and point to docs on how to set it up?

**Comment by Tyriar** [comment]
Tracking in https://github.com/microsoft/vscode/issues/141504
