### ISSUE TITLE
Notebook rendering issues

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#140254]
I'm using @joyceerhl's [GitHub GraphQL notebook extension](https://github.com/joyceerhl/vscode-github-graphql-notebooks/) and have been running into a few odd rendering issues.

First, if I reload a window with a notebook open -- nothing renders (just a blank tab), unless I resize the editor, change tabs, or something.

Second, sometime markdown cells won't get rendered at all:

![markdown](https://user-images.githubusercontent.com/641685/148495544-00375e47-1184-4dfc-8900-058b5c0d27b8.gif)

And other times they get rendered as plain text:

![image](https://user-images.githubusercontent.com/641685/148495878-9760477e-2bd4-4dba-b1d9-ab54c2de831e.png)

And if I split the plain text ones, it shows

![image](https://user-images.githubusercontent.com/641685/148495918-22e0d4bc-c894-4b41-b0b7-077cf7163463.png)

/cc @rebornix

**Comment by joyceerhl** [comment]
I believe this happens when creating `NotebookCellData` where `kind` is `NotebookCellKind.Markup` and `languageId` is not `markdown`--fixed that in my extension with https://github.com/joyceerhl/vscode-github-graphql-notebooks/commit/f91a294bd178ed79152982d962af1756f9e885a8. Is that valid usage of the API / should that throw an error?

**Comment by rebornix** [comment]
@joyceerhl thanks for the reproduce steps.

**Comment by mjbvz** [comment]
@joyceerhl Does your extension register a notebook renderer for `graphql`? In markup mode, the cell is always rendered with a contributed renderer

**Comment by mjbvz** [comment]
@joyceerhl Yes you'll need to contribute a renderer in this case. The idea is that markup cells are always displayed as rendered, while code cells show their source plus output. 

Right now Markup is only used for markdown, but in the future we want to support other types of markup too: #126417

**Comment by joyceerhl** [comment]
If an extension which contributes a serializer wants to benefit from the builtin markdown renderer, do we say it has `NotebookCellKind.Markup` and language 'markdown', or should we say it has `NotebookCellKind.Code` and language 'markdown'? The former seems to work at the moment.

**Comment by DonJayamanne** [comment]
Yes it should be the former, that's what we do as well.
From what I can remember, `markdown` language in cells don't work well. In fact if you try to change the language to `markdown` the cell changes to a non-code cell. At least thats how it used to work.

**Comment by mjbvz** [comment]
I believe this has either been worked around on the extension side or fixed on the VS Code side

@joyceerhl Let me know if if there's still something you think VS Code should do better for this case
