### ISSUE TITLE
code already running 

### ISSUE THREAD

**Issue by madforcs** [microsoft/vscode#140209]
Issue Type: <b>Bug</b>

i cant stop the code 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.49GB free)|
|Process Argv|--crash-reporter-id b77dee95-91de-469b-94b8-4686bfa37f8a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
prettier-vscode|esb|9.1.0
code-runner|for|0.11.6
vscode-pull-request-github|Git|0.34.2
beautify|Hoo|1.5.0
kite|kit|0.147.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.0
jupyter|ms-|2021.11.1001550889
cpptools|ms-|1.7.1
notepadplusplus-keybindings|ms-|1.0.7
debugger-for-chrome|msj|4.13.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.2
LiveServer|rit|5.6.1
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode|sal|53.12.0
salesforcedx-vscode-apex|sal|53.12.0
salesforcedx-vscode-apex-debugger|sal|53.12.0
salesforcedx-vscode-apex-replay-debugger|sal|53.12.0
salesforcedx-vscode-core|sal|53.12.0
salesforcedx-vscode-lightning|sal|53.12.0
salesforcedx-vscode-lwc|sal|53.12.0
salesforcedx-vscode-soql|sal|53.12.0
salesforcedx-vscode-visualforce|sal|53.12.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vs360cf:30404996
vsrem710:30416614
vscexrecpromp3t2:30407763

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

You forgot to describe steps to reproduce this problem.
