### ISSUE TITLE
Macos Monterey12.1 Can not use code in terminal.

### ISSUE THREAD

**Issue by endingman** [microsoft/vscode#140279]
![image](https://user-images.githubusercontent.com/16915802/148549559-d4ad1a51-2a3b-428d-944e-fe83ee2c9ce8.png)

**Comment by meganrogge** [comment]
have you tried running `workbench.action.installCommandLine` IE `Shell Command: Install 'code' command in PATH`?

**Comment by endingman** [comment]
> have you tried running `workbench.action.installCommandLine` IE `Shell Command: Install 'code' command in PATH`?

yes.And I try reinstall few times.

**Comment by meganrogge** [comment]
I think you have an alias set for `c` maybe?

**Comment by Tyriar** [comment]
Can you try running `which code` and `pwd` in the directory this happens and paste in the output?

I don't see any usages of `cd` in our shell script:

https://github.com/microsoft/vscode/blob/e08e4d3fe1079f6ccb1b781f6089d9e573b81ca6/resources/darwin/bin/code.sh#L12

Also I'm not sure why `/var/www` would be getting accessed, is that the working directory?

**Comment by endingman** [comment]
I have a alias on `code`，sorry.
