### ISSUE TITLE
Drag/drop to window border shows "copy" icon, does nothing, suppresses default title bar behaviour

### ISSUE THREAD

**Issue by rlipscombe** [microsoft/vscode#140282]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-91-generic

- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:

1. With at least two monitors, open VS Code maximized in one of them
2. From the other monitor, drag a tab from Firefox or Chrome to the very top of the first monitor.
3. Observe that the cursor changes to a copy ("+") icon, but dropping the tab does nothing.
4. If, instead, you drag over the VS Code title bar (but not the very top row of pixels), observe that the cursor does _not_ display the "+", and dropping the tab results in it being torn off the original browser and opened in a new window.

The same behaviour can be seen if you drag, e.g., a file from "Files" -- the very top row of pixels behave differently from the rest of the title bar/caption.

This behaviour does _not_ occur on VS Code (same version) on Windows 11: the title bar extends to the very edge of the screen.

Why is this annoying?

Because when I want to pull a tab from one browser window into its own window, I can't take advantage of Fitts' law, but instead have to be very careful about where I'm dragging the tab.

**Comment by sbatten** [comment]
@rlipscombe can you share a screen recording of the behaviour on Linux? I'd like to understand the state of the vs code window during the repro.
