### ISSUE TITLE
[BUG] Drag & Drop not working on VSCode as admin 

### ISSUE THREAD

**Issue by angelhdzmultimedia** [microsoft/vscode#140202]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows 11 Home 10.0.22000 Build 22000

Steps to Reproduce:

1. Dragging any file into VSCode is disabled when VSCode is run as admin, even when File Explorer is also run as admin.

Please fix, because there are many terminal commands that require admin privileges and if we have to open the Windows Terminal, what's the purpose of having an integrated terminal in VSCode?

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" terminal

**Comment by angelhdzmultimedia** [comment]
> Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues. /label "needs more info" terminal

Sure I can provide a screenshot, video, GIF. But I'm curious why would you need that if I was very clearn in the explanation of the issue?

Maybe you failed to understand it?

Then I will rephrase it:

_Files can not be dragged into the explorer or the editor of VSCode when VSCode is run in admin mode (as admin).  A block icon will appear in the cursor, disabling the drop functionality. Opening VSCode in normal mode, then allows files to be dragged and dropped in it.

**Comment by bpasero** [comment]
This may be non-fixable: https://github.com/microsoft/vscode/issues/38999#issuecomment-790146428

**Comment by deepak1556** [comment]
Closing as this is a limitation in the runtime.
