### ISSUE TITLE
Problem with the terminal showing french accents (chcp active code page issue)

### ISSUE THREAD

**Issue by WildFearless** [microsoft/vscode#140217]
Does this issue occur when all extensions are disabled?: Yes/No
Yes, its hard to test because I need the terminal to test my java program

- VS Code Version: 1.63.2
- OS Version: WINDOWS_NET x64 10.0.19044

Steps to Reproduce:
For java coding
1. chcp 1252 to change active code page to that, it will show É È À just fine from my println 
2. It wont show any accents for txt files that I load into my program so it shows as a string in the terminal 
3. https://i.gyazo.com/d218824fc9e932d0a8cdfccf0f0c83aa.png
4. Here's what im supposed to see https://i.gyazo.com/dba8471779ffcbd9ab219f7e4aebccc2.png
4. Changing chcp to 65001 will fix the accents for the txt file I load in so it shows accent properly, but now it literally deletes any accents in my println
5. Here's what I see when i do 65001 and what im supposed to see from my own print ln
6. https://i.gyazo.com/ac3ce48194e5cfa17cf0ae5b468ad201.png
7. Here's what im supposed to see https://i.gyazo.com/be05803f618169c3aadc89dc6176fcc0.png

Im at a lost, idk what to do. I had the issue before so I set my active code page to 1252 but now that ive started using exterior text files to use as strings, nothing works properly and I really want to use vscode and not the other IDEA

**Comment by meganrogge** [comment]
possibly related https://github.com/xtermjs/xterm.js/issues/2479

**Comment by WildFearless** [comment]
Forgot to mention im french canadian so I use the qwerty layout, my windows is in english but my projects at school are in french

**Comment by WildFearless** [comment]
> possibly related [xtermjs/xterm.js#2479](https://github.com/xtermjs/xterm.js/issues/2479)

Anything new? Ive noticed that for active code page 65001, accents works perfectly from prints and file loading in python. So I think the issue might be with java extensions but i dont know how to prove or test this

**Comment by WildFearless** [comment]
THIS https://github.com/microsoft/vscode-java-debug/issues/1090#issuecomment-1020739900 Fixed it. For anyone having problems with french accents
