### ISSUE TITLE
1.999.0 is still in the repo

### ISSUE THREAD

**Issue by zobo** [microsoft/vscode#140207]
Hi. Referencing #75639 and #74915. The tag is back again and automated system like this keep offering the upgrade. I started writing exclude rules to prevent it, but it'd be great if this could be stopped with some git hook...
![image](https://user-images.githubusercontent.com/2456026/148369336-da5d4b79-85c7-46b8-883d-211e9dee9cc9.png)

**Comment by connor4312** [comment]
I deleted the tag. Unfortunately there's no way to enforce that someone does not accidentally push it back up again (https://github.com/github/feedback/discussions/5529), but I have advised our team to delete it locally. If it is a persistent problem we could probably have a bot to delete the tag, but hopefully the advisory solves the issue 🙂
