### ISSUE TITLE
Notebook cell toolbar doesn't change focus to the notebook, so some commands fail

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#140253]
![image](https://user-images.githubusercontent.com/641685/148495054-c9dad8a6-c6a5-4514-b9af-13a742669921.png)

Certain cell commands don't work unless the notebook currently has focus.

To reproduce:
- Open a notebook (I'm using @joyceerhl's awesome [GitHub GraphQL notebook extension](https://github.com/joyceerhl/vscode-github-graphql-notebooks/) if it matters
- Create a markdown cell
- Change focus to another tab (in a side-by-side layout)
- Try to click the Stop editing button -- :bug: it won't do anything

The same happens for delete and others. I didn't test them all, but some work and some don;t.

/cc @rebornix

**Comment by roblourens** [comment]
I can't repro this and don't have a theory. This is Insiders, Windows?

**Comment by eamodio** [comment]
I can't reproduce this anymore
