### ISSUE TITLE
 your file folder path

### ISSUE THREAD

**Issue by GERMANDAN** [microsoft/vscode#140233]
Issue Type: <b>Feature Request</b>

 change the default path to your file folder path

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by JacksonKearl** [comment]
I'm not sure what you mean by this.
