### ISSUE TITLE
Disable inlay hint project config again

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140225]
I have `"editor.inlayHints.enabled": false` set:

<img width="384" alt="Screen Shot 2022-01-06 at 8 03 46 am" src="https://user-images.githubusercontent.com/2193314/148412406-28fdfd21-3fe5-41bd-bd02-9e5e35cd0eb2.png">

Version: 1.64.0-insider
Commit: 9afbea7caab9dd06592ddd98aa4161b43b126d3f
Date: 2022-01-06T05:15:20.409Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

**Comment by hediet** [comment]
> "editor.inlayHints.enabled": false

Did you configure it globally? Afaik Joh enabled inlay hints for the vscode repo as workspace setting.

**Comment by Tyriar** [comment]
Yes I configured it in my user settings, I guess this becomes an ask to remove `editor.inlayHints.enabled` from our settings.json then because I generally don't like anything that shifts my code around (which is why I'd like https://github.com/microsoft/vscode/issues/128162)

**Comment by jrieken** [comment]
I definitely will remove it again but for this iteration I want to make sure our team selfhost on it and files issues. Like you do. So, thanks so far, keep enduring, and don't forget to file issues
