### ISSUE TITLE
I cannot start debug Angular

### ISSUE THREAD

**Issue by ThuanNP** [microsoft/vscode#140204]
Issue Type: <b>Bug</b>

I cannot start debug Angular CLI project. Although, I have installed debugger for Chrome, Microsoft Edge, Firefox, the editor cannot recognize 'pwa-chrome' or 'pwa-msedge.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 7ab256d8-c593-4135-803f-31cd95026b26|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.2.2
ng-template|Ang|13.1.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.6.0
vscode-eslint|dba|2.2.2
vscode-faker|dee|1.5.0
githistory|don|0.6.19
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.1.0
vscode-firefox-debug|fir|2.9.6
auto-close-tag|for|0.5.13
rest-client|hum|0.24.6
icon-fonts|idl|2.5.3
angular-essentials|joh|12.0.0
Angular2|joh|12.0.0
vscode-peacock|joh|4.0.0
vscode-github|Kni|0.30.7
mssql|ms-|1.12.0
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vsliveshare|ms-|1.0.5201
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
color-highlight|nau|2.5.0
angular-console|nrw|17.13.6
material-icon-theme|PKi|4.11.0
polacode|pnp|0.3.4
vscode-css-peek|pra|4.2.0
vscode-yaml|red|1.2.2
code-settings-sync|Sha|3.4.3
html5-boilerplate|sid|1.1.1
vscode-fileutils|sle|3.4.5
autoimport|ste|1.5.4
code-spell-checker|str|2.0.14
bootstrap4-vscode|the|6.1.0
vscode-solidity-language|tin|0.0.6
vscode-icons|vsc|11.8.0
quokka-vscode|Wal|1.0.435
vscode-todo-highlight|way|1.0.5
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710:30416614
vscexrecpromp3t1:30407762

```

</details>

![Screen Shot 2022-01-06 at 15 25 15](https://user-images.githubusercontent.com/15880525/148352975-50bc99ab-a0f0-43cf-a818-fbf9e8ee89ee.png)
![Screen Shot 2022-01-06 at 15 24 23](https://user-images.githubusercontent.com/15880525/148352990-eeea2f31-4eb9-40d5-afa3-97f49bf385fd.png)

**Comment by connor4312** [comment]
Please make sure, by searching for `@disabled`, that you didn't accidentally disable the JavaScript debugger.
