### ISSUE TITLE
cpptools do not find definition of local variables

### ISSUE THREAD

**Issue by jeybrahms** [Microsoft/vscode#14029]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:43:46.054Z)
- OS Version: Linux x64 4.4.0-43-generic
- Extensions: donjayamanne.python-0.4.2, ms-vscode.cpptools-0.9.2

Steps to Reproduce:

1. Create a bug.cpp file and put this code inside
void f() {
    int nodeffound = 1;

    int b = nodeffound + 1;
}

2. right-click on the second reference to 'nodeffound' and choose PeekDefinition. No definition will be displayed.

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-cpptools#301
