### ISSUE TITLE
shadowed box in panel

### ISSUE THREAD

**Issue by fillharris** [microsoft/vscode#140297]
Issue Type: <b>Bug</b>

I dont know how to reproduce it  is in vscode itself. I can only show a screen shot.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HS with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.41GB (10.14GB free)|
|Process Argv|--crash-reporter-id 5e50b501-b193-4023-8563-8d0489e70775|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.6.0
gitlens|eam|11.7.0
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.1.0
go|gol|0.30.0
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30414009
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30416617
vscexrecpromp3t3:30407764

```

</details>

**Comment by ArturoDent** [comment]
You didn't add your screenshot.

**Comment by fillharris** [comment]
![vscodesnip](https://user-images.githubusercontent.com/93097873/148592765-23c1468f-d71a-4b29-a709-634692c7b277.jpg)
sorry

**Comment by fillharris** [comment]
When I hover over it in a file I get a spinning cursor. It is in every panel when I open a file.

**Comment by JacksonKearl** [comment]
@fillharris does this also occur when you are in a text editor? (versus just the welcome page)

Is there any operating system setting that might be affecting this? For instance a zoom mode.

**Comment by fillharris** [comment]
It was a windows issue. I rebooted and it went away 🤷‍♂️
