### ISSUE TITLE
filter out high code point symbols/emoji from terminal word link results

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#140230]
> Perhaps filtering out these high code point symbols/emoji only is the way to go?

Sounds like a good approach to me.

_Originally posted by @isidorn in https://github.com/microsoft/vscode/issues/95570#issuecomment-1006680055_

**Comment by meganrogge** [comment]
once we have shell integration, we will know the prompt and thus any of the symbols /icons in it and can filter them out. I think that's the better fix

**Comment by Tyriar** [comment]
@meganrogge we still want to detect the cwd in the prompt as a link though imo

**Comment by Tyriar** [comment]
To verify:

1. Open a terminal
2. Write some single character words, for example: `echo a b c` (enter)
3. Run the Open Detected Link command
4. Ensure a b c (from step 2) don't show up

**Comment by IanMatthewHuff** [comment]
Looks good. Don't see the single letters in the list anywhere.
![image](https://user-images.githubusercontent.com/812783/151231404-91b1b91b-d8e3-4d6c-a3e8-06fa72a805d8.png)
