### ISSUE TITLE
debug.copyStackTrace doesn't work when called outside the callstack context menu

### ISSUE THREAD

**Issue by ivanhernandez13** [microsoft/vscode#140239]
Issue Type: <b>Bug</b>

I wanted to be able to copy the call stack through a keyboard shortcut so I created a binding for `debug.copyStackTrace` but found that it doesn't do anything. I tried different combinations of `when` clauses and ensured that my keystroke was not being captured by something else but still no luck.

Invoking the command directly in my extension like so `vscode.commands.executeCommand('debug.copyStackTrace')` also did not work and the thenable resolved to `undefined`.

The comment [here](github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugCommands.ts) and post [here](https://github.com/microsoft/vscode/issues/106696#issuecomment-693250913) imply this should work outside of the callstack context so I've filed this as a bug as opposed to a feature request for a keyboard shortcut to copy the call stack.

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 10, 13|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|/Volumes/google/src/cloud/ivanhernandez/small-projects/google3/googlemac/nextcode/vetting/Buttons/Buttons.code-workspace --crash-reporter-id b5a447da-2982-4269-91cd-d8398f01fd39|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-bazel|Baz|0.5.0
arm|dan|1.5.2
vscode-diff|fab|1.4.2
fig|Goo|0.10.1
misc-additions|iva|1.0.2
lldb-vscode|llv|0.1.0
jupyter|ms-|2021.11.1001550889
remote-ssh|ms-|0.68.0
remote-ssh-edit|ms-|0.68.0
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.7.1
errorlens|use|3.4.1
vim|vsc|1.21.10
clang-format|xav|1.9.0
material-theme|zhu|3.13.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710cf:30416617
vscexrecpromp3t1:30407762

```

</details>

**Comment by roblourens** [comment]
The comment in code applies to the commands in general but that particular command can't be called globally currently. It copies a callstack from one thread and there can be multiple callstacks available so one has to selected to copy.

Do you want the keybinding to work on the focused thread, or does that not help?

**Comment by ivanhernandez13** [comment]
Yes, defaulting to the focused thread was my expectation.
