### ISSUE TITLE
Intellisense, Organize imports etc... not working

### ISSUE THREAD

**Issue by mujtabaraza** [microsoft/vscode#140256]
Steps to Reproduce:

1.  Update to 1.63.2
2. Organize imports stopped working in React js
3. Any intellisense such as npm modules import or paths, hover over to method info are not working anymore
![image](https://user-images.githubusercontent.com/62982499/148498110-37050eb3-060a-47a9-9255-8bec58f08fe8.png)

it happened to my teammates as well

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo

**Comment by mujtabaraza** [comment]
@mjbvz yes it's reproducible with all extensions disabled on v1.63.2

**Comment by mjbvz** [comment]
Please test using the Insiders build too, VS Code 1.64

**Comment by mujtabaraza** [comment]
alright

**Comment by mujtabaraza** [comment]
worked with that thanks 💯

**Comment by mujtabaraza** [comment]
issue persists with enabled extension

**Comment by mjbvz** [comment]
If that's the case, then one of your extensions is causing this. See https://code.visualstudio.com/blogs/2021/02/16/extension-bisect for help tracking down which one is causing this

**Comment by mujtabaraza** [comment]
https://stackoverflow.com/a/39751676 this resolved my issue
