### ISSUE TITLE
"Install another version" picker gets very full of pre-release versions

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#140262]
For the GitHub Pull Requests and Issues extension, the pre-release version is published ~4 times per week. Since the pre-release versions are also showing in the "Install another version" picker, it gets very full.

![image](https://user-images.githubusercontent.com/38270282/148516731-ea569b3a-cc81-41ff-aa5c-73cd988385c4.png)

When a user is using the stable/release version, the pre-release versions could be filtered out since they probably don't care about them.

**Comment by sandy081** [comment]
@TylerLeonhardt Can I have a check box in the input box row with a label **pre-release** ? So that user can filter pre-release extensions?

**Comment by TylerLeonhardt** [comment]
This would be a new feature ask for a generalized solution for filters. It's gotta be something we think through so it won't happen in January (or Feb at this point). Instead, can you use what we already have available:
* A title bar button - could be used as a toggle to toggle between showing pre-release and not (might need @misolori for icons for that)
* An item button that does ^
* Have the first QPI in the list act as filter toggle that says something like "Hide pre-release versions..."

**Comment by misolori** [comment]
I think when the extension is already in pre-release mode you can filter out the non-stable ones and when using the stable version you filter out the pre-release. So it should only scope it for the version that the user is in, if they want to use a stable version then they can switch to it and then choose another.

**Comment by sandy081** [comment]
@alexr00 Can you please verify this
