### ISSUE TITLE
Add `increaseIndentToken` to `indentationRules` 

### ISSUE THREAD

**Issue by sumneko** [microsoft/vscode#140259]
This is the current `indentationRules` of Lua:

```json
"indentationRules": {
  "increaseIndentPattern": "^((?!(\\-\\-)).)*((\\b(else|function|then|do|repeat)\\b((?!\\b(end|until)\\b).)*)|(\\{\\s*))$",
  "decreaseIndentPattern": "^\\s*((\\b(elseif|else|end|until)\\b)|(\\})|(\\)))"
}
```

It can work normally in most cases, but sometimes it can cause problems, such as:
![indentationRules](https://user-images.githubusercontent.com/5213431/148503783-292ce328-a5a3-4002-8c27-ebd2dee0c1d0.gif)

Since regular expressions are currently used to determine whether indentation is required, and the rules for strings are usually very complicated, it is difficult to solve this problem with the current designs.

Then I found that `tokenTypes` can mark a syntax token as `other`, `string` or `comment`.
Therefore, we may be able to achieve indentation through a similar method, which can ensure the correctness of the indentation, for example:

```json
"indentationRules": {
    "increaseIndentToken": ["keyword.control.increase.lua", "brackets.left.lua"],
    "decreaseIndentToken": ["keyword.control.decrease.lua", "brackets.right.lua"],
}
```

**Comment by rebornix** [comment]
@sumneko thanks for your suggestion, this is an interesting idea. The regex based solution is never good enough and taking the token info into account can help with some cases but I'm not sure how it would work with multi-line scenarios.

**Comment by sumneko** [comment]
> @sumneko thanks for your suggestion, this is an interesting idea. The regex based solution is never good enough and taking the token info into account can help with some cases but I'm not sure how it would work with multi-line scenarios. With that being said, it's a good start and we can continue brainstorm how to make it work properly.

```lua
local t = [[multi-line $ string]]
```
If I use then token `string.lua` as `increaseIndentToken`, and press Enter at `$`, this solution cannot resolve this case.
Is this what you mean of `how it would work with multi-line scenarios` ?

I will consider this situation carefully.

**Comment by rebornix** [comment]
@sumneko right, we kind of need to differentiate whether the cursor is in the first line of the multi-line string or the second or next lines. This might require knowledge of the context (other tokens in the line) so knowing the token type around the cursor is not sufficient.

However I wonder if this can be solved by the tokenizer generating more token types.

**Comment by sumneko** [comment]
> However I wonder if this can be solved by the tokenizer generating more token types.

I agree.
Since this feature will not cause any incompatibility, people who want to use this feature can solve the multi-line problem by generating more token types.

But there is also a potential problem, the user may have installed third-party tokenizer plugins, and these plugins may not provide these tokens.
A fallback solution may be required, for example we allow `increaseIndentPattern` to exist at the same time as `increaseIndentToken`, but if it is not possible to provide the required token in the current tokenizer (I'm not sure if this is possible), use `increaseIndentPattern`, otherwise use `increaseIndentToken`.
