### ISSUE TITLE
How to get custom sort order for CompletionItem list

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#1403]
I'm working on the PowerShellEditorServices support and right now the ordering for cmdlet parameters is alphabetical.  In PowerShell this is typically not what you want as there are a dozen or so "common" parameters that automatically show up on every cmdlet i.e. PowerShell provides them for all cmdlets.  

So in editors like PowerShell ISE it is common to list the cmdlet-specific parameters first followed by the common parameters.  I thought I could use CompletionItem.SortText to get a custom sort order but it doesn't seem to be working.  Here's a log of the messages returned to VSCode for this list:
```json
{
    "label": "-FileVersionInfo",
    "kind": 10,
    "detail": null,
    "documentation": null,
    "sortText": "007-FileVersionInfo",
    "filterText": "Regular Parameter",
    "insertText": null,
    "textEdit": {
    "range": {
        "start": {
        "line": 49,
        "character": 12
        },
        "end": {
        "line": 49,
        "character": 13
        }
    },
    "newText": "-FileVersionInfo"
    },
    "data": null
},
{
    "label": "-ErrorAction",
    "kind": 10,
    "detail": null,
    "documentation": null,
    "sortText": "008-ErrorAction",
    "filterText": "Common Parameter",
    "insertText": null,
    "textEdit": {
    "range": {
        "start": {
        "line": 49,
        "character": 12
        },
        "end": {
        "line": 49,
        "character": 13
        }
    },
    "newText": "-ErrorAction"
    },
    "data": null
},
```
Kind should be CompletionItemKind.Variable.  I was experimenting with other kinds to see if they worked any better - no joy so far.

Also it is not clear from the documentation how you use FilterText and what it looks like in the UI.

**Comment by jrieken** [comment]
The `sortText` should do what you want. I will have investigate...

**Comment by jrieken** [comment]
The sorter we use don't honour the sortText-property...

**Comment by rkeithhill** [comment]
This fix apparently didn't make the December (0.10.6 update).  Hopefully it will make the next update?

**Comment by egamma** [comment]
>This fix apparently didn't make the December (0.10.6 update). Hopefully it will make the next update?

Correct, pls check the milestone assigned to the issue.

**Comment by rkeithhill** [comment]
@egamma Thanks for that teaching moment.  :-)  I'm still learning my way around GitHub and tips like that really do help.

**Comment by aeschli** [comment]
Verified that the sort text is used.
