### ISSUE TITLE
file created in remote wsl not showing is vscode through terminal

### ISSUE THREAD

**Issue by Rohitrana124** [microsoft/vscode#140364]
Issue Type: <b>Bug</b>

i created file in window platform it shows in vscode but in wsl remote it's not showing when i create

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22523
Restricted Mode: No
Remote OS version: Linux x64 5.10.74.3-microsoft-standard-WSL2

**Comment by aeschli** [comment]
Is it a refreshing issue in the explorer? There's a well-known issue in WSL2 that file watching on `/mnt/...` is not reliable.
See https://github.com/microsoft/vscode-remote-release/issues/5000.

Is that the issue that you are seeing?

**Comment by Rohitrana124** [comment]
i solve this by moving my files in linux subsytem
