### ISSUE TITLE
Customize code folding for .js and .jsx files to achieve folding of className='...'

### ISSUE THREAD

**Issue by maplesyrupman** [microsoft/vscode#140303]
I am looking to fold the className attribute in my react app, as I am using tailwindcss and thus the classNames get quite long, cluttering my files. I've come across code folding based on start and end identifiers using regex, but am unsure as to how I go about editing the ```javascript-language.configuration.json``` file. 

I'm thinking of setting the start identifier to ```className='``` and the end identifier to ```'```

How do I open this file, and is it even possible to code fold within a single line?

for example, I would like to convert the following:
```
   <div className='some-superlong list-of-tailwind utility-classes that clutter-up this-file'>
      <p className='some-more utility-classes that-need to get-folded'>
   </div>
```
into something like this:
```
   <div className...>
      <p className...>
   </div>
```

**Comment by nrjdalal** [comment]
I can totally agree, was just googling this today, if there’s a solution or something. You beat me to it by 2 days. Thanks for raising the concern though.

**Comment by aeschli** [comment]
Sorry, but VS Code currently doesn't support folding inside a line, only full lines..

**Comment by aeschli** [comment]
Closing as blocked by https://github.com/microsoft/vscode/issues/50840 for which we currently hve no plans to implement.
