### ISSUE TITLE
Как мне запускать консоль Java? 

### ISSUE THREAD

**Issue by kalisto74** [Microsoft/vscode#14039]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: abusaidm.html-snippets-0.0.17, akamud.vscode-caniuse-0.5.3, akamud.vscode-javascript-snippet-pack-0.1.5, anseki.vscode-color-0.1.11, bajdzis.vscode-refresh-html-0.0.2, chenxsan.vscode-standard-format-0.0.12, chenxsan.vscode-standardjs-1.0.1, DavidAnson.vscode-markdownlint-0.5.0, dbaeumer.vscode-eslint-1.0.8, donjayamanne.javadebugger-0.0.2, DSnake.java-debug-0.0.2, eg2.vscode-css-properties-0.0.10, georgewfraser.vscode-javac-0.0.23, HookyQR.beautify-0.4.1, ithildir.java-properties-0.0.1, Kasik96.format-indent-1.3.0, michelemelluso.code-beautifier-1.4.1, mkaufman.HTMLHint-0.0.3, ms-vscode.js-atom-grammar-0.1.10, ms-vscode.PowerShell-0.7.2, ms-vscode.Theme-MarkdownKit-0.1.1, msjsdiag.debugger-for-chrome-0.3.1, qinjia.view-in-browser-0.0.3, redhat.java-0.0.5, seanmcbreen.Spell-0.8.6, Shan.code-settings-sync-2.3.3, tushortz.java-imports-snippets-0.0.1, tushortz.java-snippets-0.0.1, xabikos.JavaScriptSnippets-1.2.0, zhuangtongfa.Material-theme-1.0.3, Zignd.html-css-class-completion-1.0.3

Steps to Reproduce:

1. Все расширения настроила, path добавила путь к папке C:\Program Files\Java\jdk1.8.0_111
JAVA_HOME, JRE_HOME. пути добавила 
2. Выдает ошибку Error:spawn jdb ENOENT  http://skrinshoter.ru/s/201016/VahiTE

**Comment by roblourens** [comment]
Hi, Google Translate is not working very well here. It looks like you are trying to run this Java code, but seeing an error. Could you file this bug in the repo for the extension that you're using to run the Java code?

**Comment by egamma** [comment]
@mrmlnc may you can help, but this also looks like an issue against the Java extension and they should be filed against: https://github.com/redhat-developer/vscode-java/issues

**Comment by kalisto74** [comment]
Thank you.

**Comment by mrmlnc** [comment]
Привет, @kalisto74,

Во-первых, ещё раз проверьте настройки JDK:

  * `java.home` в настройках редактора 
  * `JDK_HOME` и `JAVA_HOME` в системных переменных
  * Путь до директории `JAVA_DIRECTORY/bin` в `PATH`.

![image](https://cloud.githubusercontent.com/assets/7034281/19552326/06443b3e-96b8-11e6-8eda-6caea0a76cdd.png)

Во-вторых, используя `Java Debugger` расширение, необходимо создать задать `jdkPath` (`JAVA_DIRECTORY/bin`` в `.vscode/launch.json`. Скорее всего ошибка из-за него. Обратите внимание, что нужно указывать путь именно до директории `/bin`.

![image](https://cloud.githubusercontent.com/assets/7034281/19552206/8ee1a8e2-96b7-11e6-9920-9c5a98f73a39.png)

После всех манипуляций должен пойти процесс отладки:

![image](https://cloud.githubusercontent.com/assets/7034281/19552265/cf3dba52-96b7-11e6-9588-f55ddeff66f7.png)

---

@egamma, done 🐼

**Comment by egamma** [comment]
@mrmlnc great thank you. Even I can understand the screenshots 🌷
