### ISSUE TITLE
Shell integration: Explore decorations in xterm.js

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140308]
This would let us show decorations in the buffer, now that we understand more about it https://github.com/xtermjs/xterm.js/issues/1852

**Comment by pitust** [comment]
Can i say i hate this feature? I really do, it covers up the prompt and doesn't add anything of value (i can select things myself, thank you very much)

**Comment by Tyriar** [comment]
@pitust it's off by default, don't turn it on if you don't like it

**Comment by Tyriar** [comment]
@pitust shell integration is off by default, but if you have that turned on the decorations will appear. It shouldn't be covering up the prompt, that would be a bug. It's been under heavy development the last 2 weeks and has been in a not so great state because of that.

You can turn off the decorations currently by setting this:

```
  "terminal.integrated.shellIntegration.commandIconDefault": "",
  "terminal.integrated.shellIntegration.commandIconError": "",
  "terminal.integrated.shellIntegration.commandIcon": "",
```

This will likely change though as that's not that easy to figure out.

**Comment by Tyriar** [comment]
Created https://github.com/microsoft/vscode/issues/143737 to follow this up
