### ISSUE TITLE
Inefficient file watching

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#140398]
Came across this code:

https://github.com/microsoft/vscode/blob/1944e5d1335c5f298df5330371df1f7a7cd085d4/src/vs/platform/extensionManagement/node/extensionsWatcher.ts#L47-L69

I think it can be improved:
* do the cheap checks first (i.e. the change type check)
* do not do a manual check for parent via `dirname`, there is `isEqualOrParent`

**Comment by sandy081** [comment]
> do not do a manual check for parent via dirname, there is isEqualOrParent

I want to check if the resource is an immediate child of another resource, for that, `isEqualOrParent` is not enough, I have to do `isEqual` check too. Instead I am just checking if parent of the resource is equal to the target resource. I think both shall be equally optimistic.
