### ISSUE TITLE
createOutputChannel -> append

### ISSUE THREAD

**Issue by amatilda** [microsoft/vscode#140382]
Issue Type: <b>Bug</b>

В версии 1.63.2 по сравнению с 1.61.2 по-другому работать стала функция append.
Раньше она выводила сразу строку, а теперь начала буферизовать, что не очень удобно.
Не знаю это так задумывалась или нет… Но если так задумывалось, то может было бы хорошо если бы появилась функция flush или что то подобное, что бы выводить сразу?

In version 1.63.2, the append function works differently compared to 1.61.2.
Previously, it immediately output a line, but now it started buffering, which is not very convenient.
I don’t know if it was so conceived or not ... But if it was so conceived, then it might be good if the flush function or something like that appeared to display it right away? 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3492)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.44GB free)|
|Process Argv|--file-uri file:///c%3A/Users/hapr-/OneDrive/Work/VSCode/Z-Uno-VSCode-Plugin.code-workspace --crash-reporter-id f0d1d8b6-d8f3-4212-a85b-f020ae3b0f18|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-fasm|ama|0.0.3
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.3.2
arm|dan|1.7.1
vscode-pull-request-github|Git|0.34.3
better-cpp-syntax|jef|1.15.10
vscode-language-pack-ru|MS-|1.63.3
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.0
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5242
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
linkerscript|Zix|1.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710cf:30416617
py55gd98:30419165

```

</details>

video, as it used to be, but how is it now:
[2022-01-10 04-42-36.zip](https://github.com/microsoft/vscode/files/7836446/2022-01-10.04-42-36.zip)

**Comment by sandy081** [comment]
We immediately flush the content if the channel is visible? Are you seeing other way? If so can you please provide a sample to repro and also a gif explaining the delay. Thanks.

**Comment by amatilda** [comment]
Сначала “show” а потом “append”.

Вот ссылка на пример [Plugin](https://github.com/Z-Wave-Me/Z-Uno-VSCode-Plugin)

Я прикрепил видео в первом сообщении или именно gif нужен?

По сути код там простой через “spawn” запускается программа, которая выводит в канал через “append”. Раньше выводило сразу – не тормозя как сейчас.



First "show" and then "append".

Here is a link to an example [Plugin](https://github.com/Z-Wave-Me/Z-Uno-VSCode-Plugin)

Did I attach the video in the first post or is it the gif you need?

In fact, the code there is simple through “spawn” a program is launched that outputs to the channel through “append”. Previously, it outputted immediately - without slowing down as it is now. 

Simple code example:

`
const Output= {
	channel: VsCode.window.createOutputChannel("Z-Uno"),
	data: function(data)
	{
		_this.channel.append(data.toString());
	},
	show: function()
	{
		_this.channel.show();
	}
}
const ChildProcess = require("child_process");
const Run= {
	spawn: function(cmd, stdout = false, stderr = false, args = [], options = {})
	{
		return (new Promise((resolve, reject) => {
			const child = ChildProcess.spawn(cmd, args, options);
			child.on("error", (err) => {
				resolve(false);
			});
			child.on("exit", (code) => {
				resolve(code);
			});
			if (stdout != false)
			{
				child.stdout.on("data", (data) => {stdout(data, resolve);});
			}
			if (stderr != false)
			{
				child.stderr.on("data", (data) => {stderr(data, resolve);});
			}
		}));
	}
}

Output.show();
.......
await Run.spawn('program', Output.data, Output.data, 'arg');
`

**Comment by sandy081** [comment]
I tested this without creating a process and output is getting updated immediately. We flush and update the channel if it is shown. I clearly cannot say why there is a delay between these two versions. Can you please provide a simple sample ie., without using a child process so that I can try the same and repro?
