### ISSUE TITLE
VScode cursor will switch styles when using pinyin input method

### ISSUE THREAD

**Issue by Pathsis** [microsoft/vscode#140386]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.1.63.2
2.macOS 12.1

VScode cursor will switch styles when using Pinyin Input Method, how to adjust? Refer to iA Writer. The cursor style is unchanged.There is no style switching in English in VScode.

https://user-images.githubusercontent.com/72077265/148716148-5f051622-2089-4277-8202-eb6608172902.mp4

**Comment by alexdima** [comment]
When doing composition, we reveal the native `<textarea>` that we use for input. The native `<textarea>` only allows to customize the caret color (not its shape or its blinking style). So we can align the color, but that's about it.

**Comment by Tuneabq** [comment]
✅👍💯

**Comment by Pathsis** [comment]
@alexdima This does not solve the problem of frequently switching cursor styles in the input method state. I now request vscode to provide the system default cursor style options to avoid this problem.
