### ISSUE TITLE
git status block "master" block "find result" window. 

### ISSUE THREAD

**Issue by arthas-cui** [Microsoft/vscode#14036]
- VSCode Version:1.3.1
- OS Version: mac os 10.12

Steps to Reproduce:
git status block "master" block "find result" window. 
1. in a git folder, search, get very very much result(scroll bar is visible)
2. check it.

**Comment by roblourens** [comment]
Sorry, I don't understand. Can you show a screenshot or give some more details?

**Comment by weinand** [comment]
@joaomoreno no answer after 5 days but you might know what the problem is anyway...

**Comment by joaomoreno** [comment]
Please provide more details and/or a screenshot.
