### ISSUE TITLE
Code Lens has wrong spacing with default editor.codeLensFontSize value

### ISSUE THREAD

**Issue by chupans** [microsoft/vscode#140331]
Issue Type: <b>Bug</b>

1. Default value for editor.codeLensFontSize uses slightly bigger spacing:
![изображение](https://user-images.githubusercontent.com/1556712/148647035-a6e69f9c-83a5-4569-9ca2-25d07503c8b0.png)

2. Change editor.codeLensFontSize to value equal to editor.fontSize. The font in Code Lens will be bigger but the spacing will stay the same
![изображение](https://user-images.githubusercontent.com/1556712/148647041-80588732-b3c1-4067-9b3a-16077ec72a02.png)

3. Change the editor.codeLensFontSize to 0.9 * editor.fontSize. The spacing will  be smaller
![изображение](https://user-images.githubusercontent.com/1556712/148647048-10e19dda-50fe-4ae1-81f7-ec036d370cce.png)

Expected behavior:
Default value of 0 for editor.codeLensFontSize uses sets proper spacing

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.17
unity-debug|Uni|3.0.2

</details>

**Comment by jrieken** [comment]
Not really sure what those arrows point at. Do you mean the "line height" of the code lenses?

**Comment by chupans** [comment]
Yeah, line height of code lenses. You can also check the line numbers, for font size 12 it fits from line 6 to 14, while in other cases it's only from 6 to 13

**Comment by jrieken** [comment]
> for font size 12 it fits from line 6 to 14, while in other cases it's only from 6 to 13

That can happen, the line code lens height does depends on its font height. However, when using default (90% of the editor font) it uses 100% of the editor's line height...

**Comment by jrieken** [comment]
Code pointer in case someone wants to pick this up: https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/editor/contrib/codelens/browser/codelensController.ts#L89-L100

**Comment by aeschli** [comment]
Tried various font sizes and it look good to me.
