### ISSUE TITLE
XML Code Colouring breaks when comment contains '--'

### ISSUE THREAD

**Issue by TomByrne** [microsoft/vscode#140388]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create XML doc with XML content below 
2. All content after the comment is coloured as if it is a comment, even after the comment is closed

XML content (Markdown does it right)
```xml
<?xml version="1.0" encoding="utf-8"?>
<project>

	<!-- <haxeflag name="--connect" value="6001" if="debug"/> -->

    <not-in-comment/>

</project>
```

Screenshot:
![image](https://user-images.githubusercontent.com/274228/148719375-9bce4d8a-ba25-497e-8423-370cf02f25b6.png)

**Comment by alexr00** [comment]
@TomByrne thank you for the snippet and the screenshot! My understanding is that this correct according to the spec: https://www.w3.org/TR/REC-xml/#sec-comments
