### ISSUE TITLE
PowerShell parameter color values are not unique for prescribed values

### ISSUE THREAD

**Issue by JustinWebDev** [microsoft/vscode#140372]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.63.2
- OS Version:  Win10 V21H2 x64

Steps to Reproduce:
1.  start a new PS file
2.  type a cmd string that has a prescribed parameter value pair - observe the value color is the same as the parameter
e.g., `new-item -path $myfolder -itemtype Directory`
"Directory" color is not different than the param; compare to a PS CLI.
![VSC_colors_off](https://user-images.githubusercontent.com/40804543/148698013-761cba8c-42b1-43c4-b8b0-9d655b66d421.png)
![PScli_colors](https://user-images.githubusercontent.com/40804543/148698015-5d43021f-28b6-4dcc-b0a8-237933b3a71c.PNG)

**Comment by alexr00** [comment]
The PowerShell syntax highlighting grammar we use doesn't handle this case. However, the [PowerShell extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell) does do a nice job of this.
