### ISSUE TITLE
CodeLens - Bloating screen too much

### ISSUE THREAD

**Issue by PavelCibulka** [microsoft/vscode#140357]
Can CodeLens  be displayed on the same line (not as extra line). It has been already nicely designed at https://github.com/Microsoft/vscode/issues/23652 

Issue has been closed because of wrong assumption that only problem is UI jumps. I don't mind jumping. They take to much screen space. So I've to turn them off.

Images from 23652:
![8134f5cc-1534-11e7-9fcd-5d45b4796376](https://user-images.githubusercontent.com/4307038/148673969-ab65201a-6c4c-4951-af05-955d7d8cb81f.png)

**Comment by kklocker** [comment]
Related: #138324
