### ISSUE TITLE
Main window extended across multiple screens does not restore position when re-opening

### ISSUE THREAD

**Issue by jayhaast** [microsoft/vscode#140305]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2 and 1.64.0-insider
- OS Version: Windows 11 Home Version 21H2 OS build 22000.376

Steps to Reproduce:

1. Extend main VS Code window across multiple monitors 
2. Close
3. Reopen

More info:
- I have a laptop set as my secondary monitor and an external primary monitor, which are different resolutions/aspect ratios.
- When I resize VS Code to completely fill my main monitor and extend across most of my laptop screen (can't extend across entirely due to different resolutions/aspect ratios), then close, then reopen, it always reopens on my primary monitor only.
- When I resize to mostly fill my laptop screen and extend slightly across my primary monitor, then close, then reopen, it sometimes remembers the position exactly but more often opens across both monitors but the position has changed.
- This is the only program on my computer that does this - all others that I've tested correctly remember position across both screens on reopening.
-  Note this is different from issue #56999, which referred only to restoring position on a single screen in a multi-monitor setup rather than extending across multiple screens.

**Comment by bpasero** [comment]
This is very likely https://github.com/microsoft/vscode/issues/115768. Does it reproduce if both monitors have the exact same resolution and DPI?

**Comment by jayhaast** [comment]
Hi and thanks for the quick reply. I've changed the resolution and scaling
to be the same, Windows 11 now thinks the screens are identical (see
screenshot) although the physical size of them is actually still different.
So not sure if that counts as "exact same resolution and DPI" but I think
it's the closest I can get with my setup. With these changes the issue
still reproduces.


[image: image.png]

**Comment by bpasero** [comment]
We print some information around the display sizes and how we attempt to restore when verbose logging is enabled.

Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by bpasero** [comment]
Using my windows machine I was able to reproduce, with a laptop monitor and an external display, both having same resolutions and zooming, the window is not sized properly after restart when extended on the second monitor.

My setup:
* monitor extended
* VSCode is not maximized, but made large enough that it overlaps both monitors horizontally
* I close VSCode and start it again
* 🐛 the width is not the same

Running with `--verbose` and monitoring the window bounds I get back from Electron, I verified that I restore the exact width I get from Electron, so there is nothing I can fix on VSCode end.

**Comment by bpasero** [comment]
@gjsjohnmurray fix seems to fix this too: https://github.com/microsoft/vscode/pull/155589

**Comment by alexr00** [comment]
I tried to verify this, but I see a different issue.
In stable, the window is restored small and only on one monitor.
In insiders, the window is restored across both monitors, but it's way wider than it was originally and a large portion of it is off screen as a result.

**Comment by bpasero** [comment]
How did you configure the 2 displays?

**Comment by alexr00** [comment]
External monitor with scale at 100%, laptop monitor with scale at 250%.

**Comment by bpasero** [comment]
I tried that setup, with the laptop being primary monitor, making the window cross the display bounds and reopening the app restored it correctly:

Setup is like this:

![image](https://user-images.githubusercontent.com/900690/186914304-ec66314a-ccf6-4059-9fd9-46df3407d792.png)

(laptop is to the right physically, but consider it to the left)

**Comment by alexr00** [comment]
I have found how to repro my issue reliably, which means the original issue is verified. I will open a new issue.
