### ISSUE TITLE
Provide support for "Debug: Stop All" as a configurable hotkey and Debug Toolbar button.

### ISSUE THREAD

**Issue by kon14** [microsoft/vscode#140333]
Please consider providing support for killing all debug processes at once using a "Debug: Stop All" feature.
This should be a configurable hotkey just like "Debug: Stop", only it would kill all running debug processes at once.

This is a really important feature for anyone building microservices or otherwise working with multiple processes running at the same time.

Ideally this behaviour should also be exposed through the Debug Toolbar.
I can think of two different approaches to this with different pros and cons.

1) Show an additional square _"Stop All"_ icon whenever debugging more than a single process.
![vscode_stop_all_debug_toolbar](https://user-images.githubusercontent.com/1786609/148647781-a50f7c23-18c0-43db-953a-829982ce52a6.png)
The icon could probably use a glyph to help differentiate it further from _"Stop"_ at first glance without the need to hover over them for clarification.
This has the benefit of not affecting anyone that's only debugging a single process, while also not particularly affecting people working with a couple processes that might not normally mind an extra click or two. 

2) When debugging multiple processes, clicking the _"Stop"_ icon could show a dropdown, similar to what IntelliJ IDEs do:
![webstorm_stop_dropdown](https://user-images.githubusercontent.com/1786609/148648134-f4ea68a6-523b-48e3-af82-87ee0e592fe2.png)
This approach would also only affect anyone debugging multiple processes at the same time, but it would require a couple of additional mouse clicks to terminate one or all of the processes.
It's still no worse than the current behaviour where developers need to select a process from the existing dropdown before clicking on the _Stop_ button anyway.
I think the only actual negative of this is how the toolbar would end up with an additional dropdown.
This approach could however be extended so that process groups are capable of being defined in _launch.json_, thus making it easy for dev to kill processes in groups, but that's somewhat overkill for most people.

**Comment by roblourens** [comment]
If you are working with a compound launch configuration, you can set `"stopAll": true` so that all will be stopped when you stop one - that might be what you are looking for.

**Comment by kon14** [comment]
> If you are working with a compound launch configuration, you can set `"stopAll": true` so that all will be stopped when you stop one - that might be what you are looking for.

But then you can't stop processes individually anymore, which in contrast to having to kill them individually, isn't just frustrating and tiresome, but also pretty disruptive when it comes to debugging intorcommunicating services.

**Comment by roblourens** [comment]
Just curious and trying to understand your usage pattern - do you start several launch configs individually, and you want to sometimes stop them individually and sometimes stop all of them? Or, do you currently use a compound launch config?

**Comment by kon14** [comment]
> do you start several launch configs individually, and you want to sometimes stop them individually and sometimes stop all of them?

Exactly
