### ISSUE TITLE
Alt key stops toggling menuBarVisibility after git uses VSCode as editor

### ISSUE THREAD

**Issue by hexpunk** [microsoft/vscode#140356]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Set `window.menuBarVisibility` setting to `toggle`.
2. Use VSCode as your default editor for git by setting your `~/.gitconfig` file to include the following:
```
[core]
  editor = code --wait
```
3. Check that using the Alt key is properly toggling the menu bar.
4. Cause git to open a file for editing in VSCode, for example by running `git rebase -h HEAD~2`
5. See that the `git-rebase-todo` file has been opened in VSCode.
6. Try using the Alt key to toggle the menu bar and see that it no longer works until you restart VSCode

Here's my full system info if it helps:
```
$ inxi -F
System:    Host: lemur Kernel: 5.15.8-76051508-generic x86_64 bits: 64 Desktop: Unity Distro: Pop!_OS 21.10 
Machine:   Type: Laptop System: System76 product: Lemur Pro v: lemp9 serial: <superuser required> 
           Mobo: System76 model: Lemur Pro v: lemp9 serial: <superuser required> UEFI: coreboot v: 2021-07-20_93c2809 
           date: 07/20/2021 
Battery:   ID-1: BAT0 charge: 67.3 Wh (97.1%) condition: 69.3/73.9 Wh (93.7%) 
CPU:       Info: Quad Core model: Intel Core i7-10510U bits: 64 type: MT MCP cache: L2: 8 MiB 
           Speed: 900 MHz min/max: 400/4900 MHz Core speeds (MHz): 1: 900 2: 900 3: 900 4: 901 5: 900 6: 899 7: 955 8: 2635 
Graphics:  Device-1: Intel CometLake-U GT2 [UHD Graphics] driver: i915 v: kernel 
           Device-2: Chicony Chicony USB2.0 Camera type: USB driver: uvcvideo 
           Display: x11 server: X.Org 1.20.13 driver: loaded: modesetting unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel UHD Graphics (CML GT2) v: 4.6 Mesa 21.2.2 
Audio:     Device-1: Intel Comet Lake PCH-LP cAVS driver: snd_hda_intel 
           Sound Server-1: ALSA v: k5.15.8-76051508-generic running: yes 
           Sound Server-2: PulseAudio v: 15.0 running: yes 
           Sound Server-3: PipeWire v: 0.3.32 running: yes 
Network:   Device-1: Intel Comet Lake PCH-LP CNVi WiFi driver: iwlwifi 
           IF: wlp0s20f3 state: up mac: 74:d8:3e:89:ba:b6 
Bluetooth: Device-1: Intel Bluetooth 9460/9560 Jefferson Peak (JfP) type: USB driver: btusb 
           Report: hciconfig ID: hci0 rfk-id: 0 state: down bt-service: enabled,running rfk-block: hardware: no software: yes 
           address: 74:D8:3E:89:BA:BA 
Drives:    Local Storage: total: 465.76 GiB used: 14.92 GiB (3.2%) 
           ID-1: /dev/nvme0n1 vendor: Western Digital model: WDS500G2B0C-00PXH0 size: 465.76 GiB 
Partition: ID-1: / size: 449.02 GiB used: 11.78 GiB (2.6%) fs: ext4 dev: /dev/nvme0n1p3 
           ID-2: /boot/efi size: 497 MiB used: 252.2 MiB (50.7%) fs: vfat dev: /dev/nvme0n1p1 
Swap:      ID-1: swap-1 type: partition size: 4 GiB used: 0 KiB (0.0%) dev: /dev/dm-0 
Sensors:   System Temperatures: cpu: 46.0 C mobo: 42.0 C 
           Fan Speeds (RPM): cpu: 0 
Info:      Processes: 267 Uptime: 16m Memory: 15.5 GiB used: 2.75 GiB (17.8%) Shell: Bash inxi: 3.3.06 
```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.15.8-76051508-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.50GB (11.58GB free)|
|Process Argv|--unity-launch --crash-reporter-id 2355595a-58c1-4fb1-84c2-f211c65848cb --crash-reporter-id 2355595a-58c1-4fb1-84c2-f211c65848cb --crash-reporter-id 2355595a-58c1-4fb1-84c2-f211c65848cb --crash-reporter-id 2355595a-58c1-4fb1-84c2-f211c65848cb|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.0
gitignore|cod|0.7.0
doxdocgen|csc|1.3.2
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
permute-lines|ear|1.1.0
simple-alignment|ear|1.0.1
sort-lines-by-selection|ear|1.0.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.23
theme-karyfoundation-themes|kar|25.2.3
cpptools|ms-|1.7.1
test-adapter-converter|ms-|0.1.5
vscode-versionlens|pfl|1.0.9
shellcheck|tim|0.18.3
sort-lines|Tyr|1.9.1

</details>

**Comment by sbatten** [comment]
This is linux and therefore the alt-trigger is controlled by electron

**Comment by deepak1556** [comment]
Unable to repro with latest stable `1.74`
