### ISSUE TITLE
Code [filename] does not work

### ISSUE THREAD

**Issue by galileogenerobin** [microsoft/vscode#140399]
The command code [filename] does not work in the CS50 VS Code cloud environment. I am in the correct directory where the file I'm trying to open is saved. I get the message "/opt/cs50/bin/code: line 52: ./bin/code: No such file or directory.

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
Embedder: codespaces

<!-- generated by web issue reporter --
![Screenshot 2022-01-10 175821](https://user-images.githubusercontent.com/61642869/148747434-58c87d4b-f505-4df0-82f4-cbd7e3fb864c.png)
>

**Comment by aeschli** [comment]
I'm not familiar with the 'CS50 VS Code cloud environment'. Is this based on Cloudspaces? Should the issue be filed there?
Can you add more steps and screenshot? Are you in an integrated terminal?

**Comment by twistedmacaroni** [comment]
> I'm not familiar with the 'CS50 VS Code cloud environment'. Is this based on Cloudspaces? Should the issue be filed there? Can you add more steps and screenshot? Are you in an integrated terminal?

Hi,
I'm having the same issue. Yes, CS50 is using Github Codespaces as a cloud environment and a Linux integrated terminal. When creating a new file with code [filename], it gives an error. The file is created nevertheless but it does not start editing the file right away. I've attached a screenshot of the said error. 

P.S. - I'm using Codespaces in the VS Code Application, not the web app.

Thanks.

![image](https://user-images.githubusercontent.com/93189292/152720142-f238dd95-b5c7-48eb-aa94-e00ff02b22f7.png)

**Comment by aeschli** [comment]
Does this happen all the time? Or occasionally?
I quickly tried if I can reproduce from the desktop against a freshly started codespace but it worked.


See https://github.community/t/submitting-feedback-to-github-updated/10207 on how to file an issue against Github Codespaces.

**Comment by twistedmacaroni** [comment]
> Does this happen all the time? Or occasionally? I quickly tried if I can reproduce from the desktop against a freshly started codespace but it worked.
> 
> See https://github.community/t/submitting-feedback-to-github-updated/10207 on how to file an issue against Github Codespaces.

It seemed to fix itself automatically after i deleted all the files from the workspace and started fresh. Thanks anyways.
