### ISSUE TITLE
feature request: different vscode logo colors per workspace

### ISSUE THREAD

**Issue by synaption** [microsoft/vscode#140379]
I use vscode remote a lot, and I often have so many different workspaces open that it becomes hard to tell them apart.  I noticed vs code stable and vs code insiders have slightly different colored logos and I was wondering if the same thing could be done with different workspaces, possibly automatically.  If it is easy for somebody to add this feature or make a plugin that would be great.  If not, maybe someone can point me in the right direction and I can tackle this myself.  Thanks.

**Comment by misolori** [comment]
You can use workspace settings to set a custom styling or use the peacock extension that does this automatically for you https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock
