### ISSUE TITLE
Right click context menu position when no room to go above or below cursor

### ISSUE THREAD

**Issue by crankywilson** [microsoft/vscode#140346]
Issue Type: <b>Bug</b>

This may be specific to my Linux Mint OS with customized font settings? 

On my system, when I right click, and there is no room to fit the context menu fully above the (mouse) cursor or below (because there are too many entries and the cursor is towards the center of the display), the default position of the menu ends up being such that the cursor is inside the menu area.

This is bad, because I'm used to right clicking (with a mouse button up) to bring up the menu, and then clicking again when I find the item I want.

However in this situation (which is frequent in my Python environment) the result is that a random item will get selected immediately and I don't know what the result is as the menu will immediately disappear.

What I think the proper behavior should be is that if the menu can't fit entirely above or below the cursor, it should be shifted a bit to the right or left so that if the mouse button is released (which I think is the usual way people use context menus) a menu item is not immediately chosen.

I'll be happy to give a demo if needed - send a message to bw620@outlook.com 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.4.0-74-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 3033)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.57GB (0.27GB free)|
|Process Argv|--unity-launch --crash-reporter-id 1a54e333-2f5a-407a-9cb2-b4cb2ffe56b2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.17
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.0
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
sort-lines|Tyr|1.9.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710cf:30416617
vscexrecpromp3t2:30407763

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/113175#issuecomment-960634448
