### ISSUE TITLE
Start debug session from command line

### ISSUE THREAD

**Issue by weiguozhi** [microsoft/vscode#140354]
When debug a binary with gdb we can use
```
gdb --args ./my_binary ...
```

I hope vscode has similar capability, so we can directly start a debug session from command line like
```
code -debug --args ./my_binary ...
```

**Comment by codingatmorning** [comment]
You can open a terminal in vscode and run gdb, I don't remember but I'm pretty sure vscode detects line references and allows you to automatically jump to lines. What you are asking is for someone to actually create a good debugger for binary files.

**Comment by weiguozhi** [comment]
I didn't mean a new debugger.

I'm using vscode to debug a binary built outside of vscode. My current workflow needs to create a new configuration, fill in parameters, then start debugging. Usually I run the binary from command line, and the command line changes frequently. So each time I want to debug the code with vscode, I need to create a new configuration and fill in different parameters. I don't feel it's convenient. Instead I just prepend "gdb --args " to my command line and start debugging. So I hope vscode has similar command line to start a debug session (skip the configuration setup).

An example is KDevelop. I can use following command line to start a debug session
```
kdevelop -d gdb ./my_binary ...
```

**Comment by weinand** [comment]
[Mentioned](https://github.com/microsoft/vscode/issues/10979#issuecomment-434541942) in issue #10979 is this extension:
Please use this extension  https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-debug-launcher
