### ISSUE TITLE
`executeCommand('setContext'` doesn't work in when clause when object values are functions

### ISSUE THREAD

**Issue by verhovsky** [microsoft/vscode#140359]
Steps to Reproduce:

1. Create a new extension with `yo code`
2. Make your command 
3. Add a [when clause](https://code.visualstudio.com/api/references/when-clause-contexts) to your sample command that depends on a [custom context](https://code.visualstudio.com/api/references/when-clause-contexts#add-a-custom-when-clause-context), e.g.
```json
  "contributes": {
    "menus": {
      "editor/context": [
        {
          "command": "myExtension.helloWorld",
          "title": "Hello world",
          "group": "9_cutcopypaste@5",
          "when": "editorLangId in myExtension.supportedLanguages"
        }
      ]
    }
  },
```
4. Set the custom context variable in your extension to an object where the values are functions, e.g. a function that just returns `true`, like this: 
```js
const converters = {
  'python': () => true,
}
vscode.commands.executeCommand('setContext', 'myExtension.supportedLanguages', converters);
```

Expected behavior:

The extension command appears in the right click context menu under "Paste" for files that have their language set to Python, because "[the value doesn't matter](https://code.visualstudio.com/api/references/when-clause-contexts#in-conditional-operator)".

Actual behavior:

The extension command never appears for any file.

Setting the value to some more basic value like a boolean or a string, or getting just the keys works:

```js
vscode.commands.executeCommand('setContext', 'myExtension.supportedLanguages', {'python': true});
vscode.commands.executeCommand('setContext', 'myExtension.supportedLanguages', Object.keys({'python': () => true}));
```

**Comment by jrieken** [comment]
Context key evaluation only works with simple types, not with functions
