### ISSUE TITLE
Create new file, save and close, file is not in recents list to be reopened

### ISSUE THREAD

**Issue by coinzdude** [microsoft/vscode#140310]
Issue Type: <b>Bug</b>

1. Open VS Code, 
2. create a new file, add some content, 
3. save and close this file. 
4. The file is not shown then in the recents file list to be reopened, from the File, Open Recents menu, list.

Expected results: 
At step 4 above, I expected this most recently created and closed file to be available from the recents menu. 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.91GB (24.88GB free)|
|Process Argv|--crash-reporter-id acff8a88-5a78-4ede-98d6-442e7df7ae01|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-css-formatter|aes|1.0.2
better-toml|bun|0.3.2
svg-gallery|dev|2.1.0
mhtml2md|dev|1.0.2
xml|Dot|2.5.1
LogFileHighlighter|emi|2.13.0
vscode-edit-csv|jan|0.6.4
vscode-nuget-package-manager|jmr|1.1.6
svg|joc|1.4.15
vscode-svg-dev|kon|0.8.16
Lisp|mat|0.1.12
ecdc|mit|1.4.0
mongodb-vscode|mon|0.7.0
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.17
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.0
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-wsl|ms-|0.63.13
powershell-preview|ms-|2021.12.0
vetur|oct|0.35.0
vscode-auto-scroll|pej|1.0.4
java|red|1.2.0
Unotes|rya|1.3.1
vscode-qt-for-python|sea|1.1.7
prettier-vscode|Sim|2.0.7
svg-preview|Sim|2.8.3
snooty|sno|0.9.8
html-preview-vscode|tht|0.2.5
simple-rst|tro|1.5.1
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710:30416614
vscexrecpromp3c:30407761

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/140076#issuecomment-1004625625

**Comment by coinzdude** [comment]
I got beat by 4 days!  lol  Thanks for closing!
