### ISSUE TITLE
Missing Sublime command - Increase / Decrease font size

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#14031]
While building this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings) I found that VS Code is missing feature parity with Sublime Text. The feature is increasing and decreasing font size. 

This is what I see in Sublime Text. 

![increase_decrease_font_size](https://cloud.githubusercontent.com/assets/2449568/19541790/f511dc08-961d-11e6-96e8-c1b35c751a2d.gif)

The keyboard shortcut for this in Sublime Text is <kbd>ctrl++</kbd> and <kbd>ctrl+-</kbd> on Windows / Linux. The shortcut on Mac is <kbd>cmd++</kbd> and <kbd>cmd+=</kbd> to increase font and <kbd>cmd+-<kbd> to decrease font. 

Note that this feature is closely related to, but not quite the same as zooming in and out.

**Comment by usernamehw** [comment]
* `editor.action.fontZoomIn`
* `editor.action.fontZoomOut`
* `editor.action.fontZoomReset`
