### ISSUE TITLE
Enter and Backbutton stop working on vscode instance.

### ISSUE THREAD

**Issue by williamowen65** [microsoft/vscode#140387]
Issue Type: <b>Bug</b>

**vscode is tweaking**  
Loses the ability to press enter to go to next line, and backspace to delete.

I was taking notes in markdown and bug appears. I am in the middle of a live course right now where we use VS Live Share often. But I only have had this today, and had no VS Live Share today.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (6.67GB free)|
|Process Argv|--crash-reporter-id c28b6632-6189-4c00-8528-14ce599b5870|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.0
simple-react-snippets|bur|1.2.5
path-intellisense|chr|2.6.0
bracket-pair-colorizer-2|Coe|0.2.2
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
svg-gallery|dev|2.1.0
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|3.1.1
prettier-vscode|esb|9.1.0
auto-rename-tag|for|0.1.9
vscode-es6-string-html|hjb|1.1.1
vscode-env|Iro|0.1.0
vscode-mdx|Jou|0.2.3
markdown-shortcuts|mdi|0.12.0
prettify-json|moh|0.0.3
mongodb-vscode|mon|0.7.0
csharp|ms-|1.23.17
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
vsliveshare|ms-|1.0.5242
vetur|oct|0.35.0
prettier-now|rem|1.4.9
LiveServer|rit|5.6.1
svg-snippets|sid|1.0.1
vsc-quokka-statusbar|ske|1.3.6
code-spell-checker|str|2.0.14
spellchecker|swy|1.3.0
sass-indented|syl|1.8.18
vsfire|tob|1.4.1
pdf|tom|1.2.0
quokka-vscode|Wal|1.0.435
auto-markdown-toc|xav|2.1.4
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30416617
vscexrecpromp3t2:30407763

```

</details>

**Comment by alexdima** [comment]
@williamowen65 Extensions have the ability to override keybindings or "steal" typing in the editor. When this reproduces, could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
