### ISSUE TITLE
Create Project Option

### ISSUE THREAD

**Issue by githubazure** [microsoft/vscode#140301]
Issue Type: <b>Feature Request</b>

Hi Team,

Please make the create project option available as earlier version of VS code.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
What do you mean by "project"?
