### ISSUE TITLE
command palette focus isn't respected when standing on PR-page

### ISSUE THREAD

**Issue by joelmagner** [microsoft/vscode#140304]
- Extension version: 0.27.1
- VSCode Version: 1.57.1
- OS: Mac OS

Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z (1 wk ago)
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Be on PR page, focus commentbox.
2. Cmd + p, type something, then cmd + v and it will paste in commentbox instead of in command palette.
![Untitled](https://user-images.githubusercontent.com/20977161/123960063-28af1880-d9af-11eb-8a28-632da5bd749e.gif)

**Comment by mjbvz** [comment]
This seems to be fixed in my testing

@joelmagner Can you give this a quick test in the latest VS Code insiders build and let me know if you still see the problem
