### ISSUE TITLE
Docked Debug Toolbar should not entirely replace the 'launch config' dropdown.

### ISSUE THREAD

**Issue by kon14** [microsoft/vscode#140335]
This is how the Run and Debug Toolbar area looks like with no processes being debugged:
![docked_debug_toolbar_no_process](https://user-images.githubusercontent.com/1786609/148648873-f9f00a18-796a-431f-a5f5-5f1cb41a4956.png)
At this point, users can conveniently start debugging using any _launch config_ they wish.

Here's how it looks like while a process is already being debugged with the debug toolbar in docked mode:
![docked_debug_toolbar_process_runinng](https://user-images.githubusercontent.com/1786609/148648875-fe7672a0-a18e-4564-95e3-06dd15c7faea.png)
In order for users to debug an additional process, they need to click on the _dots_ icon, then on the "Start additional session" option, then select their target launch configuration.
This can get tiresome pretty fast for anyone debugging multiple processes.

I understand this was most likely necessary to prevent the side bar from taking up too much horizontal space, but couldn't the launch configuration dropdown simply be moved below the debug toolbar area whenever actively debugging instead of being entirely removed?
That additional vertical ui "line" could be configured to only show up, or do so only when there's more than a single launch option in the project's _launch.json_ file.
Here's a rough mockup for an open drop down element (using the existing "Start Additional Session" option):

![docked_debug_toolbar_debug_additional_process](https://user-images.githubusercontent.com/1786609/148649662-2c4de984-4df8-481a-ab8e-dd974b5bdf07.png)

**Comment by roblourens** [comment]
It might make sense to have the toolbar below the start debugging dropdown. FWIW, this is only an issue when the user has set `debug.toolBarLocation` and isn't the default
