### ISSUE TITLE
add `code --list-versions`

### ISSUE THREAD

**Issue by ctaggart** [Microsoft/vscode#14035]
Along with #14034, I want to be able to list the available versions for an extension by doing something like:

```
code --list-versions Ionide.Ionide-fsharp
```

I did some digging and it looks like you already have the code to get all of the versions for an extension here: https://github.com/Microsoft/vscode/blob/master/build/lib/extensions.ts

Example request:
![image](https://cloud.githubusercontent.com/assets/80104/19543326/86a0d216-962b-11e6-9f90-7ed2b09e678a.png)

And corresponding response:
![image](https://cloud.githubusercontent.com/assets/80104/19543348/a150d35e-962b-11e6-8f01-adf3f3ee5568.png)

**Comment by ctaggart** [comment]
Related, I figured out how to do it via curl & jq:
```
$ curl -s -H "Content-Type: application/json" -H "Accept: application/json;api-version=3.0-preview.1" -X POST -d '{"filters":[{"criteria":[{"filterType":8,"value":"Microsoft.VisualStudio.Code"},{"filterType":7,"value":"Ionide.Ionide-fsharp"}],"pageNumber":1,"pageSize":1,"sortBy":0,"sortOrder":0}],"assetTypes":["Microsoft.VisualStudio.Services.VSIXPackage"],"flags":131}' https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery  | jq -r .results[0].extensions[0].versions[].version
2.7.1
2.7.0
2.6.14
2.6.13
2.6.12
2.6.11
```
I truncated the full list of versions, but it had them all. jq is easy to install with something like `apt-get install jq` or `brew install jq` depending on your OS.

**Comment by joaomoreno** [comment]
Let's not put this in the product. I don't think there is really a use case. I'm glad you found an ad-hoc way to do it, though. 👍

**Comment by ctaggart** [comment]
@joaomoreno The use case is pretty clear. When you are troubleshooting an extension or there is a problem with the new version, it is useful to install an older version of the extension. To install an older extension, you need to know what the older version numbers are.

**Comment by joaomoreno** [comment]
Yup that makes some sense. Although you can't install an old version from within the product. We encourage staying on the latest, which forces communication between the extension users and its developers. Instead of installing an older version, it's more beneficial to everyone to communicate the issue to the extension developer in order to get a new version out which fixes the issue.
