### ISSUE TITLE
Hover overlaps anchor

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#140339]
Does this issue occur when all extensions are disabled?: Yes/No

Yes.

Versions:

```
Version: 1.64.0-insider (Universal)
Commit: 419e16a49c7bffc23b8e5f0f9f35ee34167f20e1
Date: 2022-01-07T09:53:34.504Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0
```

Steps to Reproduce:

1. copy following code to a ts file
2. hover cursor to variable `ts`
3. you can see that hover hide the variable `ts`

![image](https://user-images.githubusercontent.com/41773861/148654439-9bd38e5d-592d-4f6b-9bad-072c5a393f2e.png)

**Comment by tjx666** [comment]
@jrieken

![image](https://user-images.githubusercontent.com/41773861/148713290-5c0cb060-26e9-4225-bb0d-1ab6ac117e6f.png)

**Comment by hediet** [comment]
I can reproduce:

![recording](https://user-images.githubusercontent.com/2931520/148779662-b21c9655-5813-4430-a3fe-793c28b10073.gif)

**Comment by alexdima** [comment]
The first bad commit is 93f987a8a2978533843e8a7585d5eebd63d58980

**Comment by alexdima** [comment]
Easy repro case. Hover over `x` in TS:
```ts
const x = { bar: 3 };
```
