### ISSUE TITLE
EMMET

### ISSUE THREAD

**Issue by Wakodono** [microsoft/vscode#140371]
Issue Type: <b>Performance Issue</b>

Tried creating a div with a unique class name

For example:

 .navbar 

Then noticed that no suggestions work even for regular html tags like h1

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  N3520  @ 2.16GHz (4 x 2167)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.46GB free)|
|Process Argv|C:\\Users\\David\\Documents\\GitHub\\STRIVE EXTRA\\wako-solo-capstone --crash-reporter-id 755a00f8-aaa8-499b-890e-e74e7901159b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.7
path-intellisense|chr|2.6.0
bracket-pair-colorizer|Coe|1.0.62
es7-react-js-snippets|dsz|3.1.1
prettier-vscode|esb|9.1.0
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
copilot|Git|1.7.4421
vsliveshare|ms-|1.0.5242
debugger-for-chrome|msj|4.13.0
quokka-vscode|Wal|1.0.435

</details>

**Comment by rzhao271** [comment]
What type of file are you editing in, and what is your `emmet.includeLanguages` setting currently set to?
Also, do you have an example code snippet that you can paste, where the abbreviation doesn't expand? See for example https://github.com/microsoft/vscode/issues/61474

**Comment by Wakodono** [comment]
![image](https://user-images.githubusercontent.com/53127265/148817995-b61c8a43-c836-4b21-99ae-df22707ed012.png)

**Comment by rzhao271** [comment]
Does adding the following key-value pair to the `emmet.includeLanguages` setting in the Settings editor solve the issue?
`"javascript": "javascriptreact"`

![A screenshot showing the value set in the UI Settings editor](https://user-images.githubusercontent.com/7199958/148819188-d7d6b7e8-d140-4bf9-975b-b96fa93075df.PNG)

**Comment by Wakodono** [comment]
Yes, it did. Which is weird cos it worked earlier this morning for no reason. Nice
