### ISSUE TITLE
Testing: remember collapsed state of test items across reloads

### ISSUE THREAD

**Issue by stefanhaller** [microsoft/vscode#140332]
It would be great if VS Code could remember the collapsed/expanded state of test items across reloads. Since it can already remember the success/failure state, it feels like this shouldn't be too hard to add?

Cc @connor4312

**Comment by stefanhaller** [comment]
This is great, thanks. It works well with the python extension.

However, it doesn't work with the C++ TestMate extension, and I'm a bit at a loss with debugging why. With that extension, all tests are always expanded after (re-)discovery. Any idea what an extension can possibly do wrong to prevent this from working?

**Comment by connor4312** [comment]
Thanks, fixed

**Comment by stefanhaller** [comment]
This is better, but it still doesn't always work. It now works when reloading the window, but it doesn't when tests are rediscovered for a different reason. An easy way to reproduce it is with "Test: Reload tests by C++ TestMate" from the command palette.

Let me know if you need a more precise repro scenario.

**Comment by stefanhaller** [comment]
@connor4312 Is there anything I can do to help with this? It would be super nice if this worked better.

**Comment by connor4312** [comment]
Looking at this tomorrow

**Comment by connor4312** [comment]
@stefanhaller could you let me know if this is working better for you?

**Comment by stefanhaller** [comment]
I'm sorry to say this, but no, it isn't working any better. For the python extension, the [comment above](https://github.com/microsoft/vscode/issues/140332#issuecomment-1010823082) still applies, unchanged.

For the C++ TestMate extension it even got a little worse: when using the "Reload tests by C++ TestMate" command, some of the test executables now lose their children (not all of them do, and I haven't been able to see a pattern yet). I have to invoke the command a second time, this fixes it, but the collapsed state then is the one from the last window reload, not the one from right before the first "Reload tests" command.

(Of course, the executables loosing their children might be a problem with the extension; not sure. Cc @matepek.)

I can try to come up with an exact reproduction recipe if this is helpful.

**Comment by stefanhaller** [comment]
Is there a way to delete the saved state? This would sometimes be useful for testing.

**Comment by matepek** [comment]
> "Reload tests by C++ TestMate"

I have seen that. There is a race condition which I don't know how to solve with low effort now.
(And TBH I'm not sure I remember correctly..)

So the reload flow is something like this in the extension side:

1. Removing all existing items: This is a recursive task which start with the leaf nodes and if the parent became leaf it removes that too. (This feature is there for custom grouping.)
2. Reloads the tests from executable and adds them to the tree.

If I put a delay between the two stages it seems working.
My assumption is that the stage 1 is lazy in vscode side and stage 2 is happening before stage 1 is executed on vscode side.

**Comment by stefanhaller** [comment]
Interesting. Do you think it would make a difference if you switched to https://github.com/microsoft/vscode/issues/139737#issuecomment-1002662337?

**Comment by matepek** [comment]
I don't think so. But that's a nice initiative. +1

I would also mention another feature request of my users: retired test state (which is orthogonal to the existing state) :)

**Comment by connor4312** [comment]
Modification to tests are (all) lazy but should all eventually be sequentially applied in VS Code.

> There is a race condition which I don't know how to solve with low effort now.

To clarify -- do you suspect a race in VS Code, or in the Testmate extension?

**Comment by matepek** [comment]
I think it's in vscode or the way how my extension uses vscode api.. Not sure but I didn't see any restriction in the documentation..

Now I spent some time and I can reproduce it. 

Long story short:

1. I remove elements
2. I add new elements (they are usually with the same id because I just re-enumerate the executables)
This happens in a short interval and some of the tests are missing.

If I add a delay between the two steps, everything seems fine. <-- !!

Repro (short version):
- Set up my extension: See CONTRIBUTING.md
- create dir `mkdir -p ./out/cpp; cd ./out/cpp; cmake ../../test/cpp; make`
- Remove line from `workspaceManager.ts`: `await new Promise<void>(r => setTimeout(r, 500));`
- Debug "Manual cpp"
- Change settings.json to: `"testMate.cpp.test.executables": "suite{1,2}*.exe"`
- Open test view
- Execute "Reload tests by C++ TestMate"

**Comment by connor4312** [comment]
@matepek that is captured in https://github.com/microsoft/vscode/issues/142966

**Comment by JDaance** [comment]
I also have the issue with test tree collapsing state being somewhat random on restart. Sometimes when I start/reload vscode it remembers some collapsed state which I don't know from when it is. It is not how it was before window reload/restart. On reloading all tests it remembers the collapsed state well for me so far.

In general I'm a bit annoyed by the explorer remembering stuff on restart/window reload. I would be happy with it being a completely blank slate. Like remembering all tests being green is not useful to me, I may have checked out another branch altogether and it slightly confuses me how the tests are already good.

**Comment by stefanhaller** [comment]
@connor4312 I would like to come back to [this comment above](https://github.com/microsoft/vscode/issues/140332#issuecomment-1010823082), which is still not addressed.

Now that the TestMate C++ extension supports the refresh button, it's very easy to repro: with a C++ executable showing in the test browser, expand some nodes, then hit refresh: the collapsed state is back to what it was when initially loading the tests.

The same thing happens with the python extension, which leads me to believe that it's not the extension's fault.

The state is correctly saved and restored when reloading the window, which is nice; but since refreshing tests is an operation that I do very often, this bug is quite annoying.

**Comment by stefanhaller** [comment]
Ping @connor4312: do you think there's something that can be done about this? My last comment right above this one is still valid.

**Comment by connor4312** [comment]
I have this slated for debt week (next week)

**Comment by stefanhaller** [comment]
@connor4312 Any news on this?

**Comment by connor4312** [comment]
news: it's done 🙂

**Comment by stefanhaller** [comment]
Awesome, thanks. Works well so far. Big improvement!
