### ISSUE TITLE
Tabs vs. Spaces

### ISSUE THREAD

**Issue by KidSysco** [microsoft/vscode#140373]
VS Code is always changing my tabs to spaces and spaces to tabs. Constantly, it never stops no matter how I setup the app. On every computer it always does the opposite of what I want. I really dont care what we decide to use, but we need to pick one. Either tabs, or spaces.

**Comment by KidSysco** [comment]
I think I have discovered what is really bothering me. It is when I paste. If I paste code that uses tabs, it does not matter what my local setting is. I get tabs. Same way vice, versa. I think what I am really looking for is to have paste respect my choice of tabs vs. spaces.

**Comment by alexdima** [comment]
@KidSysco You can use the following settings: `"editor.formatOnPaste": true` or `"editor.autoIndent": "full"`.
