### ISSUE TITLE
Command "workbench.action.exitZenMode" would turn on ZenMode when not in ZenMode

### ISSUE THREAD

**Issue by Binly42** [microsoft/vscode#140392]
Issue Type: <b>Bug</b>

1. Add a shortcut like
  ```json
    {
        "key": "alt+e alt+w",
        "command": "workbench.action.exitZenMode",
    },
  ```
2. ensure not in ZenMode
3. fire the shortcut "alt+e alt+w"
4. the ZenMode would be turned on

i.e. `exitZenMode` behaves just like `toggleZenMode` ...

---

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (0.73GB free)|
|Process Argv|--crash-reporter-id aef19635-1b79-4f09-9c0d-1ff29d49308d|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
dendron|den|0.76.0
dendron-paste-image|den|1.1.0
githistory|don|0.6.19
todo-tree|Gru|0.0.214
vscode-wordcount-cjk|hol|1.3.1
vscode-settings-cycler|hoo|1.0.1
path-autocomplete|ion|1.18.0
python|ms-|2021.12.1559732655
wordcount|ms-|0.1.0
markdown-checkbox|PKi|1.7.2
vscode-yaml|red|1.2.2
multi-command|ryu|1.5.1
cjk-word-handler|Sha|0.1.1
pdf|tom|1.2.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.13.10
writing-extension-pack-for-binly|N/A|0.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710cf:30416617
py55gd98cf:30419166
vscexrecpromp3t1:30407762

```

</details>

---

usage scenario:
Since the config setting `zenMode.hideTabs` (after toggled) would not be effective until re-enter the ZenMode (if already in ZenMode), and I only need `hideTabs==true` for few scenario, the command `exitZenMode` would help for command macros.

workaround:
define multiple shortcuts depending on the when clause "inZenMode" and "!inZenMode", which may be very troublesome when combined with another when clauses ... (especially without paranthesis... https://github.com/microsoft/vscode/issues/91473

**Comment by chenjefferson** [comment]
Hello! Can I take a look at this issue? Thanks!

**Comment by JacksonKearl** [comment]
@chenjefferson sure! let me know if you need a pointer. Searching the codebase for 'exitZenMode' should get you started.

**Comment by chenjefferson** [comment]
Thanks! Searching for `exitZenMode` did the trick. Fix for the issue above, although no worries if it's in your backlog!

@Binly42 In the interim, you could use `"when": "inZenMode"` for the keyboard shortcut.

```json
{
      "key": "alt+e alt+w",
      "command": "workbench.action.exitZenMode",
      "when": "inZenMode",
},
```

**Comment by kkakroo** [comment]
@JacksonKearl , Can I please have a look at this if this has not been fixed yet? 
@chenjefferson , hope it's fine with you, please let me know.
