### ISSUE TITLE
Support installing specific versions of extensions

### ISSUE THREAD

**Issue by ctaggart** [Microsoft/vscode#14034]
I would like to be able to easily install previous versions of extensions. For example, I want to be able to do this:

```
code --install-extension Ionide.Ionide-fsharp --version 2.7.0
```

I just reported a https://github.com/ionide/ionide-vscode-fsharp/issues/217 and I want to be able to troubleshoot by easily rolling back to the previous versions of the extension.

Today, it is possible to manually download and install as explained here:
https://code.visualstudio.com/Docs/editor/extension-gallery

**Comment by roblourens** [comment]
Sounds like something we could enable, I don't know if there's an existing issue. Maybe syntax like `--install-extension Publisher.Extension@2.7.0`

**Comment by ctaggart** [comment]
`@2.7.0` syntax would work too. :-)

**Comment by joaomoreno** [comment]
Fixed by #13131

**Comment by ctaggart** [comment]
@joaomoreno #13131 doesn't looks like it fixes this.

**Comment by roblourens** [comment]
I think that's for showing versions, not installing a particular version.

**Comment by ADmad** [comment]
Would be really nice to have this feature. Would really help rolling back to an older version if new version of a plugin causes problem, especially now that there's extension auto updating feature.

**Comment by mzvast** [comment]
Any progress on this topic?

**Comment by mungojam** [comment]
It seems the API may have a way to get it, see this example for the link to an old version of the python extension:

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2018.4.0/vspackage

**Comment by sandy081** [comment]
This request is also covered along with https://github.com/Microsoft/vscode/issues/12764

Hence closing this as duplicate
