### ISSUE TITLE
Creating a new file/folder

### ISSUE THREAD

**Issue by shreedharhegde99** [microsoft/vscode#140321]
### Creating New File/Folder
1.It would be nice to have an option to ```create/modify ```  file /folder when we hover over any folder.
right now the available option is that we have to hover over root file or right click in explorer menu to create a new file/folder

2.It would be more easier, while using the shortcut key ``` Ctrl+N```  if it would have asked for the ``` file name ``` and ```language``` ,rather than only ```language```.

for example  ```foo.html``` , ```bar.js```

![Screenshot from 2022-01-08 14-00-11](https://user-images.githubusercontent.com/90758718/148638774-1d54a7de-67bc-4db4-80e3-b327204bfc50.png)

![Screenshot from 2022-01-08 14-00-28](https://user-images.githubusercontent.com/90758718/148638801-578690af-7fb5-4b3a-abe7-83f5c4a89b9a.png)

**Comment by JacksonKearl** [comment]
I'm not sure exactly what you're asking for here. We do have the new file/folder buttons at the top of the explorer, which will create a new file or folder under or adjacent to the currently selected resource. You can assign a keybinding to that button with the keybindings editor (look for `explorer.newFile`):
![image](https://user-images.githubusercontent.com/8586769/149008752-35e533f6-733a-4db2-b901-5fb08dff8408.png)

**Comment by shreedharhegde99** [comment]
> I'm not sure exactly what you're asking for here. We do have the new file/folder buttons at the top of the explorer, which will create a new file or folder under or adjacent to the currently selected resource. You can assign a keybinding to that button with the keybindings editor (look for `explorer.newFile`): ![image](https://user-images.githubusercontent.com/8586769/149008752-35e533f6-733a-4db2-b901-5fb08dff8408.png)

That solves my issue. 
Thanks.
