### ISSUE TITLE
Missing semicolon

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#140391]
I noticed there is a missing semicolon [here](https://github.com/microsoft/vscode/blob/b07d7df0c35fe36caa434263f9f398d95515f7e9/src/vs/editor/browser/editorBrowser.ts#L839).

I think we used to have an eslint rule for missing semicolons, not sure if that was removed intentionally.

**Comment by jrieken** [comment]
> I think we used to have an eslint rule for missing semicolons, not sure if that was removed intentionally.

I believe that not working for interfaces, neither in TS nor in ESLint. So selfhost with format on type and this code action save config: `	"editor.codeActionsOnSave": {"source.fixAll.eslint": true},`. When writing expressions I happily see semicolons being auto-inserted. Adding @dbaeumer for the ESlint part of this

**Comment by dbaeumer** [comment]
The reason for ESLint not detecting this is that we need to turn the ESLint semi rule off and use the TS semi rule. Something like

```
        "semi": "off",
        "@typescript-eslint/semi": "error",
```

I will look into chancing this for VS Code.

**Comment by dbaeumer** [comment]
Actually we have the right settings in the eslintrc file

```
		"semi": "off",
		"@typescript-eslint/semi": "warn",
```

**Comment by jrieken** [comment]
Yeah, semi colons in interfaces and inline types are considered optional and eslint doesn't seem to auto insert them. I now use the ts formatter setting (as user setting)

**Comment by dbaeumer** [comment]
There is a special rule in TS ESLint for member delimiter. Let me look if we can use that one:

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/member-delimiter-style.md

**Comment by dbaeumer** [comment]
I needed to revert this. It caused hundreds of warnings in out code base :-(.

**Comment by dbaeumer** [comment]
The question is: do we want to enforce this. If yes, we would need to adopt?

**Comment by dbaeumer** [comment]
We would also need to decide what happens with single line

```ts
context?: { cell: DiffElementViewModelBase; }
```

I am in favor of forcing a semicolon there as well (e.g. after `DiffElementViewModelBase`)

**Comment by jrieken** [comment]
Let's make this a team decision

**Comment by dbaeumer** [comment]
I did some additional testing with the ESLint rule and it affects only interface and type literals. Object literals are still separated using ','. Here are examples what the rule will enforce:


```typescript
interface X {
    foo: number; // <== enforces a semicolon here
}
```

```typescript
type X = {
   foo: number;  // <== enforces a semicolon here.
}
```

As said above by default the ESLint rule enforces no semicolon if the type literal is written on one line. So this is correct

```typescript
type X = { foo: number }  // <== no semicolon
```

and this would be an error

```typescript
type X = { foo: number; }  // <== no semicolon allowed
```

But we can customize ESLint that even on single line we enforce a semicolon. Since it is a type definition and not an object literal I would actual opt to enforce it.

**Comment by jrieken** [comment]
/cc @microsoft/vscode 

Please raise concerns and leave feedback - this is about semicolons in a few more places (see comment above)

**Comment by jrieken** [comment]
This is now done

**Comment by Tyriar** [comment]
I'm a bit late, but my personal preference is to use a command on single line definitions as semi colons look a little off to me when single line interfaces are inlined into other statements:

```json
    "@typescript-eslint/member-delimiter-style": [
      "warn",
      {
        "multiline": {
          "delimiter": "semi",
          "requireLast": true
        },
        "singleline": {
          "delimiter": "comma",
          "requireLast": false
        }
      }
    ],
```

As long as we're consistent it doesn't bother me too much though.

**Comment by dbaeumer** [comment]
I prefer semicolon for all type literals and comma for object literals.
