### ISSUE TITLE
Feature Reqest for Emmet - ability to customize validation for abbreviations

### ISSUE THREAD

**Issue by elYanuki** [microsoft/vscode#140407]
I would love to be able to use emmet, for example, in an empty CSS file so that i can make a custom snippet simmilar to the ! in html, right now as far as i know you can only use emmet inside a selector which isnt what im looking for. It would be nice to have a setting where you could add to the validation or deactivate it entirely for certain languages. ^^

**Comment by rzhao271** [comment]
Wait. Do VS Code snippets cover that use case for you?
https://code.visualstudio.com/docs/editor/userdefinedsnippets
