### ISSUE TITLE
Bad visual feedback when using ctrl+click the remove from the selection in the explorer

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140421]
Repro:

- Select multiple item in explorer
- Ctrl+click one of them

In the below screenshot `multiroot` is not selected (but it is focused):

![image](https://user-images.githubusercontent.com/2193314/148786155-445adfd2-5a1c-477b-b511-5d1681372f46.png)

I expect the background to go in that case but to keep the outline, like how Windows Explorer does it:

![image](https://user-images.githubusercontent.com/2193314/148786536-08c16515-76b2-428b-816f-83406bf86f64.png)

**Comment by JacksonKearl** [comment]
Styling issue? This is "list.focusBackground"/"list.inactiveFocusBackground"/"list.activeSelectionBackground"/"list.inactiveSelectionBackground"

I have it configured to do what you expect:
![image](https://user-images.githubusercontent.com/8586769/148839846-90a7c4d5-14ef-4319-9274-088ee422727a.png)


cc @misolori

**Comment by misolori** [comment]
This does appear to be a styling issue as in the default theme, ctrl + clicking de-selects the item. Below I de-selected `grooming-delta`:

<img width="294" alt="image" src="https://user-images.githubusercontent.com/35271042/148843010-40af4d17-473f-4815-9c14-12c40cd3314a.png">

and in other themes I'm seeing that style appear differently:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/35271042/148843101-722d9bb9-4355-4fc0-9a6c-71478d05806c.png">

**Comment by Tyriar** [comment]
Thanks, this is on my theme's end then

**Comment by Tyriar** [comment]
Actually, is our default for `list.inactiveFocusBackground` bad? It's null in my theme so the default should be transparent imo.

**Comment by misolori** [comment]
`list.focusBackground` is the key for this

**Comment by Tyriar** [comment]
Thanks, yep this is all on my end:

https://github.com/Tyriar/vscode-theme-generator/blob/67ecacc199e13ac4c59486b45d378ecaddbbcf3d/src/vscodeThemeGenerator.ts#L114-L115
