### ISSUE TITLE
JavaScript & TypeScript formatting

### ISSUE THREAD

**Issue by SeanHub** [Microsoft/vscode#14045]
- VSCode Version: 1.6.1
- OS Version: Windows 10 Pro (10586.494)

Steps to Reproduce:

1. Create a new JavaScript file (same problem with a TypeScript file)
2. Add a function
3. Pressing Alt + Shift + F does nothing (nor does clicking on the right click menu shortcut)

Example code:

`function test(arg) {console.log(arg);};`

I would expected the code above to have been formatted like so:

```
function test(arg) {
    console.log(arg);
};
```

**Comment by roblourens** [comment]
Works for me, do you have any extensions installed?

**Comment by SeanHub** [comment]
Nope no extensions (I've removed them all). Very odd if formatting works for you because its happening to another member of our development team at work. It might be worth knowing that I'm running TypeScript 1.6.2, VSCode asked me if I wanted to update the version to 2 but I declined.

**Comment by roblourens** [comment]
Oh actually, it works in the Insider's build, but not stable. So it must be fixed by taking a new version of the TS language service, which we did recently. You can try it out here if you like - http://code.visualstudio.com/insiders

**Comment by SeanHub** [comment]
Hi, I've tried the insider build and both formatting and intellisense isn't working. I know this issue is regarding the formatting but both these issues occurring at the same time is surely related. I'm still running TypeScript 1.6.2 (not that it should make a difference to JavaScript formatting).

**Comment by SeanHub** [comment]
There was a setting in the settings.json file with the key "typescript.check.workspaceVersion" which was pointing to a TypeScript build (1.6.2) in my node_modules folder. For some reason VSCode would not work properly with this version (Formatting and Intellisense disabled). I have since removed this setting and opted to use the inbuilt version of TypeScript when prompted to do so by VSCode. Formatting and Intellisense now works. This may be of help to others who experience this issue.
