### ISSUE TITLE
Switching from edit mode to command mode with Enter button changes the view

### ISSUE THREAD

**Issue by Seenaam** [microsoft/vscode#140454]
Issue Type: <b>Bug</b>

If a part of a cell is not being showed on the screen and you are in the cmmand mode, switching to edit mode with the Enter key changes the view (like it jumps).

Extension version: 2021.11.1001550889
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.36GB free)|
|Process Argv|I:\\Torrent dl\\TensorFlow Developer Certificate in 2021 Zero to Mastery\\TensorFlow Developer Certificate in 2021 Zero to Mastery\\01. my codes on this pc\\3-linear regression.ipynb --crash-reporter-id 7410a323-d8bb-4598-bd3f-514b152808e2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710:30416614
py55gd98:30419165
vscexrecpromp3t2:30407763
vscop841:30415853

```

</details>

**Comment by greazer** [comment]
Handling keyboard and scrolling behavior is a vscode core issue.

**Comment by rebornix** [comment]
@Seenaam can you please share a screen recording to help understand what's going on?

**Comment by Seenaam** [comment]
> @Seenaam can you please share a screen recording to help understand what's going on?

Of course. I hope [this](https://imgur.com/OrRPWMJ) is helpful.

**Comment by rebornix** [comment]
@Seenaam the gif explains the bug perfectly, thanks for your help!

**Comment by Seenaam** [comment]
> @Seenaam the gif explains the bug perfectly, thanks for your help!

My pleasure. Your consideration means a lot, thank you.

**Comment by rebornix** [comment]
We have recently updated our cell focus logic and I don't reproduce this bug any more in latest Insiders. Feel free to reopen if you are still seeing this.
