### ISSUE TITLE
[Bug] Unintentional Horizontal Scroll occurs in Diff Editor on clicking near the right end of the modified editor instance

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/vscode#140410]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.63.2 
- OS Version: Mac OS - Big Sur 11.6

### Steps to Reproduce:

1. Select any file in the Diff Editor Mode from the source control tab
2. Click on the right end of the modified editor instance
3. The content is getting selected automatically and editor is scrolling unintentionally

### Video explaining the issue

_This video is recorded in VS Code Desktop Application with all the extensions disabled as mentioned in the comment_ 

https://user-images.githubusercontent.com/29809906/148763270-2b0657fd-c61a-4ebd-aadb-49a336360315.mov

### Additional Info

This issue occurs only when there is a click happening very close to the right end of the editor, But I'm not sure about the exact distance from the right side

This issue is reproducible in monaco editor playground also

**Comment by alexdima** [comment]
This reproduces in any editor (not just in a diff editor) and it also reproduces when clicking near the bottom of the viewport.

**Comment by Pranomvignesh** [comment]
@alexdima Thanks for fixing the issue
