### ISSUE TITLE
"workbench.action.toggleSplitEditorInGroupLayout" would influence all split-ed-in-group editors in all groups

### ISSUE THREAD

**Issue by Binly42** [microsoft/vscode#140406]
Issue Type: <b>Bug</b>

The same as the `Toggle Layout` button in right top corner of the editor.

**Reproduce**:
1. open two or more editors in different groups
2. run command `workbench.action.splitEditorInGroup` on all of them (or click through right-click context)
3. run command `workbench.action.toggleSplitEditorInGroupLayout` on one of them (or click the `Toggle Layout` button)
4. layouts of all split-ed-in-group editors would be toggled simultaneously

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (0.78GB free)|
|Process Argv|--crash-reporter-id aef19635-1b79-4f09-9c0d-1ff29d49308d|
|Screen Reader|no|
|VM|50%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710cf:30416617
py55gd98cf:30419166
vscexrecpromp3t1:30407762

```

</details>

**Comment by bpasero** [comment]
This ends up changing a setting in settings and cannot be changed on a per-editor basis.

**Comment by Binly42** [comment]
Got it. (a little pity...

It would be great to support per-editor split-in-group layout, so as to make better use of the grid view, just like:
![图片](https://user-images.githubusercontent.com/15514941/148907984-78448d47-48e4-4eed-9177-1698e0bec2f0.png)
(the code example is casually picked from the commits, the lines of which are fairly short already)
