### ISSUE TITLE
Unexpected connection attempts to applicationinsights service from Remote workspace despite telemetryLevel off

### ISSUE THREAD

**Issue by natevw** [microsoft/vscode#140458]
Despite my setting of `"telemetry.telemetryLevel": "off"`, after adding an extension (e.g. "Docker" or "Hex Editor") to a Remote workspace, I begin to see connection attempts to `eus012-breeziest-in.cloudapp.net` domains whose servers present an `in.applicationinsights.azure.com` certificate.

I initially reported this as https://github.com/microsoft/vscode-docker/issues/3372 thinking it was a bug in one particular extension I happened to be using, but after further troubleshooting it appears this is likely coming from VS Code itself.

Here's what I'm seeing:

1. I have `"telemetry.telemetryLevel": "off"` in my local workstation's User settings
2. Installed the Remote SSH extension on that local workstation
3. Used the Remote SSH extension to connect to a VM (which installed vscode-server on the VM)

At this point, I do **not** see connection attempts to the apparent telemetry service domains.

However as soon as I install an extension (e.g. `ms-vscode.hexeditor` or `ms-azuretools.vscode-docker`) in the remote workspace, the VM hosting that remote workspace starts trying to connect to domains which my firewall identifies as e.g. `eus012-breeziest-in.cloudapp.net` or similar subdomains, and which appear to be associated with a `in.applicationinsights.azure.com` service.

My understanding is that "Application Insights" is a user tracking/analytics service and so I would not expect any such connections to be attempted with my `telemetryLevel` set to `off`. The connection attempts also seem to happen at various times e.g. not just when I open the workspace but also right when I interact with the extension (e.g. after I click the "Docker" sidebar item an attempt is made) — which also leads me to suspect the connections might be for an analytics/telemetry purpose.

Why does my VM attempt such connections after I have installed extensions in a Remote workspace, if I have opted out of all telemetry in the VS Code app?

**Comment by natevw** [comment]
If it helps track down the source I found via an older and otherwise related issue (https://github.com/microsoft/vscode/issues/29489) a similar file `/tmp/appInsights-nodeAIF-444c3af9-redacted/164redacted.ai.json` on my own VM with contents roughly:

```
{"ver":1,"sampleRate":100,"tags":{"ai.application.ver":"1.61.2","ai.device.id":"","ai.cloud.roleInstance":"my-vm-hostname","ai.device.osVersion":"Linux 5.10.0-10-arm64","ai.cloud.role":"Web","ai.device.osArchitecture":"arm64","ai.device.osPlatform":"linux","ai.internal.sdkVersion":"node:1.0.8"},"data":{"baseType":"EventData","baseData":{"ver":2,"properties":{"common.machineId":" - identifier - ","sessionID":" - other uuid - ","commitHash":"6cba118ac49a1b88332f312a8f67186f7f3c1643","version":"1.61.2-remote","common.platformVersion":"5.10.0","common.platform":"Linux","common.nodePlatform":"linux","common.nodeArch":"arm64","common.product":"remoteAgent","timestamp":"2022-01-10T21:56:59.696Z"},"measurements":{"optIn":1,"common.timesincesessionstart":17,"common.sequence":0},"name":"monacoworkbench/optInStatus"}},"iKey":" - redacted - ","name":"Microsoft.ApplicationInsights.AIF444c3af98e694462a-redacted.Event","time":"2022-01-10T21:56:59.752Z"}
{"ver":1,"sampleRate":100,"tags":{"ai.application.ver":"1.61.2","ai.device.id":"","ai.cloud.roleInstance":"my-vm-hostname","ai.device.osVersion":"Linux 5.10.0-10-arm64","ai.cloud.role":"Web","ai.device.osArchitecture":"arm64","ai.device.osPlatform":"linux","ai.internal.sdkVersion":"node:1.0.8"},"data":{"baseType":"EventData","baseData":{"ver":2,"properties":{"common.machineId":" - identifier - ","sessionID":" - other uuid - ","commitHash":"6cba118ac49a1b88332f312a8f67186f7f3c1643","version":"1.61.2-remote","common.platformVersion":"5.10.0","common.platform":"Linux","common.nodePlatform":"linux","common.nodeArch":"arm64","common.product":"remoteAgent","timestamp":"2022-01-10T21:56:59.749Z"},"measurements":{"startTime":37.325926999999865,"startedTime":44.636412999999266,"codeLoadedTime":108.70524699999987,"readyTime":125.68321500000002,"common.timesincesessionstart":70,"common.sequence":1},"name":"monacoworkbench/serverStart"}},"iKey":" - redacted - ","name":"Microsoft.ApplicationInsights.AIF444c3af98e694462a-redacted.Event","time":"2022-01-10T21:56:59.752Z"}
{"ver":1,"sampleRate":100,"tags":{"ai.application.ver":"1.61.2","ai.device.id":"","ai.cloud.roleInstance":"my-vm-hostname","ai.device.osVersion":"Linux 5.10.0-10-arm64","ai.cloud.role":"Web","ai.device.osArchitecture":"arm64","ai.device.osPlatform":"linux","ai.internal.sdkVersion":"node:1.0.8"},"data":{"baseType":"EventData","baseData":{"ver":2,"properties":{"common.machineId":" - identifier - ","sessionID":" - other uuid - ","commitHash":"6cba118ac49a1b88332f312a8f67186f7f3c1643","version":"1.61.2-remote","common.platformVersion":"5.10.0","common.platform":"Linux","common.nodePlatform":"linux","common.nodeArch":"arm64","common.product":"remoteAgent","timestamp":"2022-01-10T21:56:59.752Z"},"measurements":{"usingFallbackGuid":0,"common.timesincesessionstart":73,"common.sequence":2},"name":"monacoworkbench/machineIdFallback"}},"iKey":" - redacted - ","name":"Microsoft.ApplicationInsights.AIF444c3af98e694462a-redacted.Event","time":"2022-01-10T21:56:59.752Z"}
```

**Comment by lramos15** [comment]
Thank you for the detailed report. This of course should not be happening and sounds like a bug in https://github.com/microsoft/vscode-extension-telemetry. I will get right on this 👍

**Comment by natevw** [comment]
Thanks for the quick turnaround! Looks like this is currently tagged as "unreleased" so I won't retest just yet.

**Comment by roblourens** [comment]
Not clear how I can verify this @lramos15

**Comment by lramos15** [comment]
@roblourens Please just review the commit https://github.com/microsoft/vscode/pull/140651.

The way I went about verifying this was patching OSS to send telemetry and setting breakpoints within the telemetry code to ensure it was never sending anything. I believe the author has some sort of network watcher on the VM hosting the server which is also possible but a bit more involved
