### ISSUE TITLE
"Hybrid Extensions" for Web and Desktop VSCode versions

### ISSUE THREAD

**Issue by Gamadril** [microsoft/vscode#140402]
I have an extension for "VSCode for Desktop" which adds language support, compiler and uploader. Upload to embedded device is implemented using serial port NodeJS library. Because of the upload feature the extension cannot work in "VSCode for Web". However in theory it should be possible to modify the extension to use Web Serial API for code upload and make it work also in the online version - at least inside Chrome based browsers.
So it should be possible to write "hybrid" extensions which would use NodeJs modules for "VSCode for Desktop" and extended Web APIs (like Web USB, Web Serial, Web bluetooth and others) for "VSCode for Web".

**Comment by joaomoreno** [comment]
Given that web extensions have a [separate `"browser"` entry-point](https://code.visualstudio.com/api/extension-guides/web-extensions#web-extension-anatomy), this is already supported today.

cc @aeschli
