### ISSUE TITLE
Dates on extension page use American format regardless of display language

### ISSUE THREAD

**Issue by hickford** [microsoft/vscode#140434]
The 'Last updated' and 'released on' dates on the extension page use the American format. This is confusing to many people.

> Last updated 12/3/2021

![image](https://user-images.githubusercontent.com/105314/147394673-159f7479-cbe2-4b34-8859-e3d781b93090.png)

I tried [changing the display language](https://code.visualstudio.com/docs/getstarted/locales) to Spanish and German, but the problem remains:

![image](https://user-images.githubusercontent.com/105314/147394710-8cc408f9-8f68-4e06-96a7-8c1e270c7692.png)

![image](https://user-images.githubusercontent.com/105314/147394748-54f27c37-3264-422c-98f0-7b3c5039f5fe.png)

Consider using a unambiguous date format such as yyyy-mm-dd (ISO 8601)

**Comment by TylerLeonhardt** [comment]
@sandy081 I think using the unambiguous date format is a good way forward. However, we could do something where en-US is displayed one way and...well... everything else is displayed the other way... but I don't think that is 100% accurate.

**Comment by Yash621** [comment]
@hickford can I work on this ?

**Comment by armgp** [comment]
is this issue closed? or still needs help?

**Comment by sandy081** [comment]
Its still open and there is a PR which has to be reviewed.

**Comment by hannahcoles** [comment]
@sandy081 Hello, is this issue still open? I am new to contributing to GitHub projects and this seems like a good first issue for me. Is there a way to claim this issue?

If I am able to work on this, do you have any advice for me in contributing for the first time?

**Comment by sandy081** [comment]
@hannahcoles  Thanks for your interest. This is already being worked on. Please look for another good first and help wanted issues. Thanks/

**Comment by icepaq** [comment]
I know people often scour these issues for something to work on.

While this comment is in the thread (not deleted), anyone can feel free to take this issue over.

cc @armgp @hannahcoles @cristianosuzuki77
