### ISSUE TITLE
Run vscode on Linux by decompressing and installing

### ISSUE THREAD

**Issue by liergou99** [microsoft/vscode#140470]
os：centos7
user：test
download vscode
`     wget   https://az764295.vo.msecnd.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/code-stable-arm64-1639561407.tar.gz`

decompress & run
`     tar -zxvf code-stable-x64-1639562789.tar.gz`
`   ./VSCode-linux-x64/bin/code`
Vscode did not run successfully

When I use sudo when unzipping, there is no such problem
`     sudo tar -zxvf code-stable-x64-1639562789.tar.gz `
`   ./VSCode-linux-x64/bin/code`

 Must sudo be used for decompression ？
How to install using a user without sudo permission？

**Comment by deepak1556** [comment]
Can you provide the output of `./VSCode-linux-x64/bin/code --verbose` when run without sudo. Thanks!

**Comment by liergou99** [comment]
[test@localhost pack]$ ./VSCode-linux-x64/bin/code --verbose
[20868:0112/195247.460148:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/test/pack/VSCode-linux-x64/chrome-sandbox is owned by root and has mode 4755.

**Comment by liergou99** [comment]
It also doesn't boot properly when I use test user on Ubuntu system. Using root and ubuntu user can start successfully .

test@ubuntu:~/vscode$ ./VSCode-linux-x64/bin/code  --verbose
No protocol specified
[6456:0113/014704.031687:ERROR:browser_main_loop.cc(1402)] Unable to open X display.
The futex facility returned an unexpected error code.

**Comment by deepak1556** [comment]
Thanks for the logs, when running from archive you have to manually fix the permissions of the SUID helper binary https://code.visualstudio.com/updates/v1_59#_progress-for-electron-sandbox-support.

```
sudo chown root <path-to-vscode>/chrome-sandbox
sudo chmod 4755 <path-to-vscode>/chrome-sandbox
```
