### ISSUE TITLE
Nested Extension Packs fail to install correctly

### ISSUE THREAD

**Issue by craigleonard** [microsoft/vscode#140412]
Version of VS Code: 1.63.x and above
Your operating system: Windows 11

---

When an extension pack contains another extension pack, the extensions in the nested pack are not installed when installing top level pack.

This is exemplified by the `ms-python.python` extension pack. It has the following hierarchy (using `*` to denote an extension pack here):

```
ms-python.python *
 - ms-python.vscode-pylance
 - ms-toolai.jupyter *
   - ms-toolai.jupyter-keymap
   - ms-toolai.jupyter-renderers
```

In 1.62.2, installing `ms-python.python` would result in all 5 extensions being installed. In 1.63.0 and above, only 3 extensions are installed,  with `mstoolsai.jupyter-keymap` and `mstoolsai.jupyter-renderers` being excluded. This is also the case in the insider 1.64.0 build.

**1.62.2**

![1 62 2](https://user-images.githubusercontent.com/2349129/148772102-74fd8752-d43e-4d0a-8da4-f85c9d668898.png)

**1.63.2**

![1 62 3](https://user-images.githubusercontent.com/2349129/148772112-d805b0b4-3ea0-4f70-b6dc-5a7e4418a7dd.png)

To replicate:
1. From the Extension Marketplace view, search for and install the `ms-python.python` extension.
2. Display the installed list of extensions by searching for `@installed`.

**Other cases**

Another example of this behaviour is exhibited when installing `donjayamanne.python-extension-pack`, which includes `ms-python.python`. None of the extensions under `ms-python.python` (Pylance and Jupyter) get installed in this scenario.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/139134
