### ISSUE TITLE
Event broker for cross-extension message passing

### ISSUE THREAD

**Issue by xsznix** [microsoft/vscode#140442]
Has there been any thought to adding an event broker API to make pub/sub across extensions easier to implement? We are writing an extension that holds state that other extensions subscribe to, and we need the cross-extension subscriptions to work across extension hosts because we are using Remote Development. This rules out relying solely on exporting APIs from the publisher extension's `activate(...)` function because extensions cannot access these APIs across extension hosts.

The architecture looks something like:

- User is using Remote Development
- 1 workspace extension manages and publishes shared state
- 1 or more workspace extensions subscribe to the shared state – this can be done today by exporting an API from `activate(...)`, e.g. using an event emitter or RxJS
- 1 or more UI extensions subscribe to the shared state – we are looking for a solution for this case

I see that there is an event broker in Eclipse, but the same concept does not appear in VS Code's extension API: https://javadoc.scijava.org/Eclipse/org/eclipse/e4/core/services/events/IEventBroker.html

Would this be a reasonable feature to have? Or are there better existing ways to implement cross-extension pub/sub in VS Code today?

**Comment by roblourens** [comment]
Unfortunately the only tool we have for calling between extension hosts currently is the `executeCommand` API. You may be able to get the same effect with that but I understand it's suboptimal.

We previously investigated enabling extensions to export async-only API that could be called between extension host processes, but it's a tough problem.

**Comment by solomatov** [comment]
@roblourens Thanks for your quick answer.

Are you open to an implementation of a proposed api by us in a PR? Having such an API will help us solve important problems, and it will be possible to use it as the base for other features. For example, the cross ext. host RPC could be implemented through this API.

**Comment by roblourens** [comment]
An API for this would take a significant amount of investigation and discussion and I don't think we'd be open to a PR yet.

cc. @alexdima @jrieken
