### ISSUE TITLE
Live Server Issue

### ISSUE THREAD

**Issue by Vishanth2202** [microsoft/vscode#140484]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.While loading live server the the page shown in the screenshot opens not the page what i want to load
2.How to get the file what actually want to open 
![Capture](https://user-images.githubusercontent.com/84909882/148920234-40e288a8-4791-4a43-9df7-24ee4f05c40e.JPG)

**Comment by lszomoru** [comment]
@Vishanth2202, are you using the [Live Server extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) or [the Live Preview extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server)?
