### ISSUE TITLE
Pressing Tab doesn't indent, but moves to next window panel (terminal)

### ISSUE THREAD

**Issue by cobrapitz** [microsoft/vscode#140432]
Issue Type: <b>Bug</b>

Pressing Tab doesn't indent, but moves to next window panel (terminal)

I have no clue on which condition this happens, maybe app focus.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (20.33GB free)|
|Process Argv|--crash-reporter-id e7476ea4-6eb9-4982-a547-686161d0dc08|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
gitlens|eam|11.7.0
godot-tools|gee|1.1.2
vscode-pull-request-github|Git|0.34.3
latex-workshop|Jam|8.23.0
vscode-edit-csv|jan|0.6.4
better-cpp-syntax|jef|1.15.10
vscode-gutter-preview|kis|0.29.0
restructuredtext|lex|167.0.0
rainbow-csv|mec|2.0.0
git-graph|mhu|1.30.0
compare-folders|mos|0.22.2
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.0
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.0-insiders2
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5242
vsliveshare-audio|ms-|0.1.91
vscode-yaml|red|1.2.2
glassit|s-n|0.2.4
vscode-workspace-explorer|tom|1.5.0
cmake|twx|0.0.17
gitblame|wad|8.1.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710cf:30416617
py55gd98:30419165
vscexrecpromp3c:30407761

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you see "Tab Moves Focus" in status bar? Can be toggled with <kbd>Ctrl</kbd>+<kbd>M</kbd>

**Comment by cobrapitz** [comment]
I'll check and report back the next time I get it,

**Comment by meganrogge** [comment]
ok create a new issue with repro steps if you see it again
