### ISSUE TITLE
Unable to scroll line with ctrl+up and ctrl+down when editing a cell

### ISSUE THREAD

**Issue by Takkoona** [microsoft/vscode#140452]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I wanted to scroll line using `ctrl+up` and `ctrl+down` like I can with other file (so I can adjust the position of the line I'm editing on the screen). I tried disabling all other notebook-related `ctrl+up` and `ctrl+down` keybindings. This only allows me to scroll with the two keybindings in commond mode. So I modified the `when` expression for `scrollLineDown` and `scrollLineUp` but still failed in edit mode. The following is my current keybindings.json file.

```json
// Place your key bindings in this file to override the defaultsauto[]
[
    {
        "key": "ctrl+up",
        "command": "-notebook.cell.focusOutOutput",
        "when": "notebookEditorFocused"
    },
    {
        "key": "ctrl+down",
        "command": "-notebook.cell.focusInOutput",
        "when": "notebookCellHasOutputs && notebookEditorFocused"
    },
    {
        "key": "ctrl+down",
        "command": "-notebook.focusNextEditor",
        "when": "notebookEditorFocused && notebookOutputFocused"
    },
    {
        "key": "ctrl+down",
        "command": "scrollLineDown",
        "when": "textInputFocus || editorTextFocus && inputFocus && notebookEditorFocused"
    },
    {
        "key": "ctrl+down",
        "command": "-scrollLineDown",
        "when": "textInputFocus"
    },
    {
        "key": "ctrl+up",
        "command": "scrollLineUp",
        "when": "textInputFocus || editorTextFocus && inputFocus && notebookEditorFocused"
    },
    {
        "key": "ctrl+up",
        "command": "-scrollLineUp",
        "when": "textInputFocus"
    }
]
```

### VS Code Version

Version: 1.63.2 (user setup) Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3 Date: 2021-12-15T09:40:02.816Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.19044

### Jupyter Extension Version

Jupyter Extension Version: 2021.11.1001550889

### Coding Language and Runtime Version

Python v3.9.7

### Language Extension Version (if applicable)

Python Extension Verison: 2021.12.1559732655

### Anaconda Version (if applicable)

Miniconda v4.11.0

### Running Jupyter locally or remotely?

Local

**Comment by greazer** [comment]
These commands are handled by core vscode notebook support.

**Comment by DonJayamanne** [comment]
@rebornix assigning to you as this was assigned to me when this was transferred.
