### ISSUE TITLE
When to support javascript and typescript intellisense in .vue file?

### ISSUE THREAD

**Issue by yeluoqiuzhi** [Microsoft/vscode#14047]
When to support javascript and typescript intellisense in .vue file?
There are so many web developer write vue with vscode.

**Comment by roblourens** [comment]
Is a .vue file just a javascript file? Does this setting fix it for you?
```
"files.associations": {
        "*.vue": "javascript"
    }
```

**Comment by yeluoqiuzhi** [comment]
No. .vue is just a html file, but there is no intellisense in  embed <style> and <script> tag

**Comment by roblourens** [comment]
Ok, I think that won't work anyway because of #8928, regardless of file extension.
