### ISSUE TITLE
Testing: fuzzy matching in the Testing Explorer is less useful than substring matching

### ISSUE THREAD

**Issue by stefanhaller** [microsoft/vscode#140405]
In #137811, filtering in the Testing Explorer was changed to fuzzy matching. This is definitely a regression for me, I'd propose to revert this change, or introduce an option to control it.

In some test frameworks, test names can be very long. For example, in the catch2 C++ framework, test names are allowed to be entire sentences. This is useful to make test names really descriptive.

In such an environment, filtering for a short word of three or four characters almost always matches a large number of tests, because the single letters of the word appear in many test names. This is not useful.

(Alternatively, it might be an improvement to change fuzzyContains to only return results where each sub-match is more than one character. But since this would affect other features of VS Code, that's maybe not an option.)

Cc @connor4312 @ashgti

**Comment by connor4312** [comment]
I've run into this a bit as well. I'm leaning towards reverting to the old behavior as well.

**Comment by ashgti** [comment]
When dealing with very large suites I thought it was pretty useful, plus most of the other UI components fuzzy match (like the tree view filters, quick pick and command palette).

The following gif was made using the self hosted tests in VS Code searching for `getRela` > `getRelat` > `getRelative`, you can see that it does find the specific test, plus some extras but it will filter down to a specific enough value with a specific enough pattern.

![fuzzy-filtering](https://user-images.githubusercontent.com/22535/148863817-8a7bcc4d-2a55-46e2-b9a2-0c15ca57ea53.gif)
 
Could we have an option to fuzzy match vs substring match in the filter options?

<img width="210" alt="Screen Shot 2022-01-10 at 5 13 32 PM" src="https://user-images.githubusercontent.com/22535/148863981-629e6d99-b63d-4088-886e-3b5d5226824c.png">

**Comment by stefanhaller** [comment]
Frankly, I don't want to have to type so many characters. If I have a test name "Ask user for login credentials", then I want to type "ask" to show that test, and maybe a handful others that also ask users for things. But right now it shows me every test that happens to have the letters "a", "s", and "k" in their name, which is more or less _every_ test. This makes quick filtering useless for me.

An option sounds fine to me though.

**Comment by connor4312** [comment]
![image](https://user-images.githubusercontent.com/2230985/161116821-7aefe4ee-7fb4-4691-82ba-839785c24e8f.png)

**Comment by stefanhaller** [comment]
Works well in the latest insider, thanks. Also, thanks for making it default to "off". 😄
