### ISSUE TITLE
Vscode cannot remember the order of the outline.

### ISSUE THREAD

**Issue by huye** [microsoft/vscode#140495]
Issue Type: <b>Bug</b>

Every time I set it to sort by type, but after a while, it becomes sorted by name again.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.4.0-90-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (8 x 2275)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|14.65GB (2.06GB free)|
|Process Argv|--unity-launch --crash-reporter-id 14391a16-897d-41f8-af87-c27038b34956|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.0
vscode-test-explorer|hbe|2.21.1
php-cs-fixer|jun|0.2.10
vscode-language-pack-zh-hans|MS-|1.63.3
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
test-adapter-converter|ms-|0.1.5
vsliveshare|ms-|1.0.5242
code-settings-sync|Sha|3.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710cf:30416617
vscop841:30415853

```

</details>

**Comment by huye** [comment]
What else should I say? The only problem is that the sorting of the outline cannot be retained. I don't know when it will return to the default sorting.

**Comment by jrieken** [comment]
Idk either, the code is pretty simple ⬇️ Unless there is an issue with settings sync (cc @sandy081) or storage there is little that explains this. It will be help to know when/how the happens, esp because "name" isn't default sort. That would be position - so if data is corrupt or lost than it should default to that

 https://github.com/microsoft/vscode/blob/d66db5cc754dc760ffb0a69049e5127fb78d723f/src/vs/workbench/contrib/outline/browser/outlineViewState.ts#L71

**Comment by sandy081** [comment]
Settings Sync do not sync workspace state

**Comment by jrieken** [comment]
Oh, yeah. That could explain this. @huye do you see this inside one workspace or across multiple?

**Comment by huye** [comment]
> Oh, yeah. That could explain this. @huye do you see this inside one workspace or across multiple?

I don't quite remember why. If this problem happens again in the future, I will pay more attention to it myself. If it's not because I remember wrong, I'll give you feedback again.
