### ISSUE TITLE
Duplicate vscode icons in macOS dock

### ISSUE THREAD

**Issue by leira** [microsoft/vscode#140472]
Issue Type: <b>Bug</b>

### Steps to reproduce:

1. launch vscode through Spotlight or Dock.
2. open a project with Open Folder....

### Expected behavior:

Vscode launched. There is only one icon in Dock. There is a small dot under the icon.

Besides the icon already in Dock, a new vscode icon shows up in the recent applications area and starts to dance. Eventually it stops dance. There is no dot under this duplicated icon.

-----------

This issue is similar to #60579. But #60579 is triggered through `code` command. In my case, it can be reproduced without command line.

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|--crash-reporter-id 2a3bf93f-336a-4391-bbe0-1141c28d10e2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
command-alias|Art|0.5.5
spellright|ban|3.0.60
foam-vscode|foa|0.17.2
dance|gre|0.5.8
nix-ide|jno|0.1.19
vscode-paste-image|mus|1.0.4
rewrap|stk|1.15.4
ayu|tea|1.0.5
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30421291
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710cf:30416617

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by leira** [comment]
Thanks, @gjsjohnmurray! It is really helpful. "Start Extension Bisect" identified spellright is the reason. Following up with bartosz-antosik/vscode-spellright#465, close this one.
