### ISSUE TITLE
Search and compare missing in source control

### ISSUE THREAD

**Issue by tanmay6anand** [microsoft/vscode#140481]
Issue Type: <b>Feature Request</b>

I can't find search and compare in source fix it asap..!!!!

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by lszomoru** [comment]
@tanmay6anand, could you please provide repro steps of the issue that you are experiencing?
