### ISSUE TITLE
Syntax error highlights

### ISSUE THREAD

**Issue by pointer2null** [microsoft/vscode#140411]
Issue Type: <b>Feature Request</b>

At the moment a syntax error is flagged by the first character being underlined. I find this can be hard to spot so could we have the option to underline the whole line or better still make the line number red for example.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.1.16-200.fc29.x86_64

**Comment by meganrogge** [comment]
what language are you using? can you please attach a gif or screenshot?

**Comment by pointer2null** [comment]
Language in this case is 'go'. Here are two examples, a mssing param to a
function and a typo - missing comma

**Comment by mjbvz** [comment]
Please file this issue against the Go Extension
