### ISSUE TITLE
problem with renderWhitespace option

### ISSUE THREAD

**Issue by TrafalgarRicardoLu** [microsoft/vscode#140469]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: November 2021 (version 1.63)
- OS Version: MacOS Monterey 12.1

Steps to Reproduce:

1. in setting, set 'renderWhitespace' to 'all'
2.in big project, both reading new file and scroll up&down become very slow. But write remain fast.

**Comment by alexdima** [comment]
I think this is a duplicate of #111816 . @TrafalgarRicardoLu Could you please follow the steps at https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process and attach a renderer JavaScript CPU profile?
