### ISSUE TITLE
Update-Help

### ISSUE THREAD

**Issue by Get-SPO** [microsoft/vscode#140422]
Issue Type: <b>Bug</b>
The error code tells you to run the same command that was just run.
Without "-UICulture en-US" it picks up GB setting and errors.

RUN:
PS C:\> Update-Help -UICulture en-US
RESULT:
Update-Help: Failed to update Help for the module(s) 'PSReadline, WindowsUpdateProvider' with UI culture(s) {en-US} : 
One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
gitlens|eam|11.7.0
spfx-debug|eli|0.0.3
spfx-snippets|eli|1.11.1
vscode-spfx-localization|eli|1.7.0
vscode-spfx-remove-components|eli|1.0.0
vscode-spfx-task-runner|eli|1.2.4
prettier-vscode|esb|9.1.0
vscode-edit-csv|jan|0.6.4
vscode-azureappservice|ms-|0.23.0
vscode-azureresourcegroups|ms-|0.4.0
csharp|ms-|1.23.17
azure-account|ms-|0.9.11
azurecli|ms-|0.5.0
powershell|ms-|2021.12.0
debugger-for-chrome|msj|4.13.0
</details>

**Comment by IllusionMH** [comment]
Could you please clarify how this is related to VS Code editor itself?
Are you able to run this command in PS directly but not in the integrated terminal?

**Comment by Get-SPO** [comment]
Apologies, this is a PS error not VS Code.

Peter Sherlock
Flex Tech Services
(613) 355-5205
________________________________
