### ISSUE TITLE
VSCode Using Terminal -> New Terminal menu causes terminal crash

### ISSUE THREAD

**Issue by brws70** [microsoft/vscode#140431]
Issue Type: <b>Bug</b>

Expected operation is that a new powershell Terminal window opens within VSCode.

Actual result is an error 'The terminal process "C:\Program Files\PowerShell\7\pwsh.exe" terminated with exit code : 3221225794"

Select Menu -> Terminal -> New Terminal
Focus changes to Terminal tab followed by the error.
Happens 100% of time 
![VSCodeTerminalIssue](https://user-images.githubusercontent.com/76622705/148810883-4e98cc54-0270-42e4-9057-e2525ce51f35.png)

On Microsoft Windows [Version 10.0.19042.1415]

Relevant output from the log file generated from "code --log trace"

```
[2022-01-10 17:20:22.836] [renderer1] [trace] CommandService#executeCommand workbench.action.terminal.new
[2022-01-10 17:20:22.836] [renderer1] [trace] terminalInstance#ctor (instanceId: 6) {"executable":"C:\\Program Files\\PowerShell\\7\\pwsh.exe","icon":{"id":"terminal-powershell"}}
[2022-01-10 17:20:23.085] [renderer1] [debug] Terminal process ready (shellProcessId: 12132)
[2022-01-10 17:20:24.350] [renderer1] [debug] Terminal process exit (instanceId: 6) with code undefined
[2022-01-10 17:20:24.351] [renderer1] [debug] Terminal process exit (instanceId: 6) state 6
[2022-01-10 17:20:24.351] [renderer1] [trace] terminalInstance#dispose (instanceId: 6)
```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz (6 x 2195)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|20.86GB (10.84GB free)|
|Process Argv|--log trace ./ --crash-reporter-id d6d72c9f-6b8b-4cc9-afd8-951c77dc73fb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.17
code-spell-checker|str|2.0.14
pdf|tom|1.2.0

</details>

**Comment by joeljose350** [comment]
> Select Menu -> Terminal -> New Terminal

This works just fine on my Windows 11 machine.

```
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
```

**Comment by brws70** [comment]
If I change VSCode preferences Terminal > Integrated > Default profile: Windows from "PowerShell" to "Command Prompt" or "Git Bash" I get the same issue, so is likely related to VSCode and its ability to execute an external process??

![VSCodeTerminalIssue-Bash](https://user-images.githubusercontent.com/76622705/148825366-18617dd5-be19-4fff-a390-cbee9cddeb3c.png)

This in a corporate environment so possibly something is interfering with the ability of VSCode to execute commands?

How could I verify that?

**Comment by meganrogge** [comment]
Do you have anti-virus software that could be blocking the terminal? If so try following the instructions in https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch
/label "needs more info" terminal
