### ISSUE TITLE
Uri handler is no longer hit when debugging an extension

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#140468]
I'm working on an authentication provider and in the stable edition of VS Code I can debug it and redirects to the `vscode://<extension-id>`  work just fine, but in the current insiders edition, the uri handler never gets called (nor does the allow dialog get shown). Although the VS Code window does come to the foreground -- just not the right one, the debugger window comes to front rather than the debuggee.

/cc @joaomoreno

**Comment by roblourens** [comment]
The uri-handler-sample extension works fine for me in insiders, does that work for you?

Do you own this api now @TylerLeonhardt?

**Comment by TylerLeonhardt** [comment]
I don't, I just added the sample.

**Comment by eamodio** [comment]
@roblourens I think the issue was/is that if the focus isn't on the extension host window, it doesn't get routed properly. Though now when I try it, I see the "Allow this url dialog", on which ever window had focus last.

**Comment by roblourens** [comment]
I suppose the extension is installed and active in both windows, is that causing an issue?

**Comment by eamodio** [comment]
@roblourens Ah, yeah. So if the extension is not enabled in the debugger window, but it has focus, it looks like the url handling is just dropped, but if it is enabled in both windows, then it just gets routed to the wrong one.
