### ISSUE TITLE
Clicking in explorer when focus is outside vscode will drop the selected item and focus the outer explorer element

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140418]
This behavior has been pretty frustrating to deal with when doing a lot of work between windows recently where I want to create a new file 

![Recording 2022-01-10 at 06 49 13](https://user-images.githubusercontent.com/2193314/148785553-d5452503-c697-4cae-a85c-661075071385.gif)

It also seems to sometimes not drop the selection, having multiple selections seems to increase the chance of the selection being kept 🤷 

Version: 1.64.0-insider (user setup)
Commit: a06afb22ce06dbd4f01d3bb5bf946e08bff55180
Date: 2022-01-10T05:16:12.944Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by bpasero** [comment]
I think I see this very often in web, not so much desktop.

**Comment by JacksonKearl** [comment]
Can you try setting `skipRefreshExplorerOnWindowFocus` to `true` (hidden) and see if this reproduces in next insiders? The mouse events get mangled in OSS.

**Comment by Tyriar** [comment]
I don't think this reproduces anymore
