### ISSUE TITLE
GitHub Authentication won't load properly in the webworker extension host

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#140459]
I'm trying to debug GitLens in the webworker extension host (to simulate a web environment -- since the debug experience is far better than the other options). And I've forced both RemoteHub and GitHub auth into the webworker host via:

```json
  "remote.extensionKind": {
    "GitHub.remotehub": ["web", "ui"],
    "vscode.github-authentication": ["web", "ui"]
  }
```

And when I do, it fails to activate:

![image](https://user-images.githubusercontent.com/641685/148850530-e921d62d-fa65-4205-92c4-efddea84c845.png)

There is no output channel and the console doesn't show anything other than the error notification above.

/cc @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
I think for this scenario we just need to fallback to PAT. I think that's the best we can do considering we're stuck with CORS issues.

**Comment by TylerLeonhardt** [comment]
This probably works a lot better now. Optimistically closing.
