### ISSUE TITLE
Improve lua grammar

### ISSUE THREAD

**Issue by sumneko** [microsoft/vscode#140489]
The current lua grammar is a little poor, such as:

1. Many tokens are not catched:
![no-token](https://user-images.githubusercontent.com/5213431/148939488-433fa1eb-c6dd-4111-9ec2-24fc05397aa6.png)

2. Dose not support tokens after Lua 5.2
![old-token](https://user-images.githubusercontent.com/5213431/148939725-00512f0b-0168-442e-8cf7-a18ad6ecb2cd.png)
 
3. Dose not support `EmmyLua`, whitch is a type annotation system that has become the de facto standard
![no-luadoc](https://user-images.githubusercontent.com/5213431/148940304-845b5efe-0fd8-4d8b-99f7-5a06d711bf88.png)

Since the [source project](https://github.com/textmate/lua.tmbundle) is no longer active (I have created a [PR](https://github.com/textmate/lua.tmbundle/pull/13) there 3 years ago), I created a new project to provide the grammar file: https://github.com/sumneko/lua.tmbundle/blob/master/Syntaxes/Lua.plist

The effect of the above code after using this grammar file is:
![new-syntax](https://user-images.githubusercontent.com/5213431/148940898-f2620460-e655-44ba-a292-5381615c0513.png)

The grammar file has been in [my extension](https://marketplace.visualstudio.com/items?itemName=sumneko.lua) for several years and it works fine.
I hope that it can be set as the default lua grammar file of VSCode, so that theme developers can better optimize the color matching for it.

**Comment by alexr00** [comment]
Thanks for reaching out @sumneko. I looked for Lua.plist in https://github.com/sumneko/lua-language-server, but I wasn't able to find it. Can you point me to where in your extension you use the grammar file? Does your extension depend on https://github.com/sumneko/lua.tmbundle? 

When adopting a new grammar file in VS Code we want to make sure we're moving to a better supported grammar then the old one. I can see that your extension has regular releases, which is great. I want to understand how the new grammar repo fits into the extension, and whether you'll continue to make fixes for the grammar.

**Comment by sumneko** [comment]
> Does your extension depend on https://github.com/sumneko/lua.tmbundle?

Yes, the Lua.plist is https://github.com/sumneko/lua.tmbundle/blob/master/Syntaxes/Lua.plist .
I used it in my extension at https://github.com/sumneko/vscode-lua/blob/master/syntaxes/lua.tmLanguage.json

> I want to understand how the new grammar repo fits into the extension, and whether you'll continue to make fixes for the grammar.

In fact I maintain the grammar file by manually modifying the json file, and I used a script in the above project to convert json to plist.

I will countinue make fixes for the grammar, it has been part of my extension before.
After VSCode uses it, I will remove it from my extension and maintain the `lua.tmbundle` project instead.

**Comment by alexr00** [comment]
That all sounds great, thanks for the answers. We don't require a plist file, a tmLanguage.json file is also good, so no need to maintain a plist if that isn't your preference. 

Let's try using https://github.com/sumneko/lua.tmbundle in VS Code at the beginning of our February iteration. That way, the changes will have the entirety of the February iteration to be used by VS Code insiders users before being released.

**Comment by SNDST00M** [comment]
Is EmmyLua already the standard? I've been using LDoc for a long time so will that be supported?

**Comment by sumneko** [comment]
> Is EmmyLua already the standard? I've been stuck with LDoc for a long time so will that be supported? It'd be a matter of supporting `--` prefix for doc comment and injecting into `--[[` Lua block comments too.

Since I don't use LDoc, I don't support it, but PRs are welcome.
`EmmyLua` should be the only type annotation system for original Lua, and as far as I know LDoc cannot create or mark types.

**Comment by SNDST00M** [comment]
`@type` means a OOP class and `@class` means data type, for backwards compatibility with LuaDoc.
My main concern is that tags have to be reimplemented as repository rules injected in multiple contexts.

**Comment by ChrisKader** [comment]
Thank you @sumneko

**Comment by alexr00** [comment]
Reopening for visibility.

**Comment by SNDST00M** [comment]
@sumneko I was not able to genericise the Lua documentation tags between block and inline comments, so I think I'll open a request on the bundle repo

**Comment by sumneko** [comment]
Sorry I just found that the issues function is disabled in https://github.com/sumneko/lua.tmbundle .
I have enabled it and any issues are welcome!

**Comment by alexr00** [comment]
I have not seen an increase in issues for lua syntax highlighting since switching to the new grammar. Closing as fixed! Thank you @sumneko.
