### ISSUE TITLE
No formatter option for space between colon and type in TypeScript

### ISSUE THREAD

**Issue by M-Pixel** [Microsoft/vscode#14041]
- VSCode Version: 1.6.1
- OS Version: Win 10

Steps to Reproduce:
1. Write a TypeScript interface definition omitting space between colon and type (e.g. `name:string`)
2. Autoformat
3. Note that a space was inserted between ":" and "string"
4. Open user preferences in order to change this behavior
5. Note that among the many `typescript.format.insertSpaceAfter*` options, none address this area of syntax.

I prefer to omit this conventional space in order to differentiate `{key: val}` from `{name:Type}`. It would be nice to have the option to autoformat without having to forgo this convention.

**Comment by kcbleeker** [comment]
Yes please

**Comment by roblourens** [comment]
I think we only get the formatting options that the TS service exposes.

**Comment by kcbleeker** [comment]
That's a little frustrating in a VSCode versus IntelliJ battle.

**Comment by roblourens** [comment]
tslint autofix might do this.

**Comment by waderyan** [comment]
@M-Pixel thank you for opening this issue. We are looking at ways to improve this experience and will consider your specific use case. Are there are formatting options you would like to see?

Ping @jrieken as this might be relevant for your formatting work.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#12365
