### ISSUE TITLE
javaScript code fold bug;

### ISSUE THREAD

**Issue by baofengyv** [Microsoft/vscode#14042]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 15.6.0
- Extensions: Zignd.html-css-class-completion-1.0.3, abusaidm.html-snippets-0.0.17, donjayamanne.githistory-0.1.0, xabikos.JavaScriptSnippets-1.2.0

Steps to Reproduce:

 ##fold javaScript code bug;

1. before fold
![2016-10-20 2 32 30](https://cloud.githubusercontent.com/assets/5669938/19548692/9723dc58-96d2-11e6-9924-6c23506db257.png)
 
2. after fold
![2016-10-20 2 32 47](https://cloud.githubusercontent.com/assets/5669938/19548695/9f8e30f0-96d2-11e6-908f-6d8874303726.png)

**Comment by roblourens** [comment]
Folding is just based on indentation, not language structures, so this is expected.

**Comment by baofengyv** [comment]
I think ,that's may be good but not perfect :)
