### ISSUE TITLE
Navigating via require statements in JavaScript

### ISSUE THREAD

**Issue by plaanupam** [Microsoft/vscode#14049]
- VSCode Version: 1.6
- OS Version: Ubuntu 16.04
- Language: JavaScript
I am able to navigate through require statements in JavaScript. It directs me to the file, when I press ctrl+click on a required file.

My friend is also using VSC and getting intellisense, but he is not able to jump through files via require statement.

I am unable to find a setting which is different in our VSC. 
jsconfig.js file is the same in both our projects and I am unable to find a setting that controls this behavior. 
I may be missing something trivial here, but how can I enable this feature everywhere.

Thanks

**Comment by waderyan** [comment]
@plaanupam thank you for opening this issue. This is a known bug. 

@bowdenk7 can you help me find where we are tracking this issue in TypeScript repo? I can't find it.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11923
