### ISSUE TITLE
Getting started: Misleading checkbox UX

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#140403]
🐛 The mouse cursor shows a pointer when hovering over the checkbox label, but clicking it makes no change to the checkbox. Clicking the label should toggle the checkbox.

![image](https://user-images.githubusercontent.com/22350/148751615-94b2010e-f0ad-4920-9f83-12e4db7851a9.png)

**Comment by JacksonKearl** [comment]
Nice catch, thanks
