### ISSUE TITLE
Incorrect warning about "vscode" property in package.json file

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#14040]
- VSCode Version: 1.7.0-insiders
- OS Version: MacOS

Steps to Reproduce:

1.  open an empty workspace
2. create a `package.json` file
3. add `name` and` version` property
4. add an empty `engines` property

<img width="356" alt="warning" src="https://cloud.githubusercontent.com/assets/4674940/19546138/d1413b06-9641-11e6-9ebf-e74afa2bc10d.png">

Nothing in this workspace is supposed to refer to vscode.

**Comment by aeschli** [comment]
fixed with 7970218
