### ISSUE TITLE
can not use VS Code after used MS-remote desktop 

### ISSUE THREAD

**Issue by MC-Guan** [microsoft/vscode#140467]
Issue Type: <b>Bug</b>

Whenever I use MS-remote desktop, the VS Code stops responding, I have to close and re-open to use it. 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.56GB free)|
|Process Argv|--crash-reporter-id 77fce59d-f8da-4c38-98c2-0a5fbe124378|
|Screen Reader|no|
|VM|44%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
icons-carbon|ant|0.2.4
vscode-JS-CSS-HTML-formatter|lon|0.2.3
rainbow-csv|mec|2.0.0
fluent-icons|mig|0.0.15
vscode-language-pack-zh-hans|MS-|1.63.3
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.0
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-wsl|ms-|0.63.13
material-product-icons|PKi|1.1.1
python|tht|0.2.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614

```

</details>

**Comment by rzhao271** [comment]
Are you using VS Code on remote desktop, or do you just have the two programs open at the same time locally?
If it is the first case, are you able to use remote development extensions like remote-SSH instead?

**Comment by MC-Guan** [comment]
> Are you using VS Code on remote desktop, or do you just have the two programs open at the same time locally? If it is the first case, are you able to use remote development extensions like remote-SSH instead?

Thank you for your reply. I can use remote-SSH in first case.  I do some tests, there may be something wrong with my office PC,  the problem only occurs when i use remote desktop to connect my office PC, i think i will figure it out. Thanks again.
