### ISSUE TITLE
Fabric Environment

### ISSUE THREAD

**Issue by depederj1** [microsoft/vscode#140465]
"Smart Contract" and "Channels" do not appears under my Fabric Environments in VS Code after packaging my first smart contract and starting/connecting to my local fabric environment (I am very new to this space and trying to learn). This means I cannot install or instantiate a smart contract on my program. See attachment. 
![image](https://user-images.githubusercontent.com/97486805/148861452-71545e01-7220-415b-a150-ee144c5bc139.png)

Thanks!

**Comment by alexdima** [comment]
@depederj1 It looks like you might have a question or a problem with a VS Code Extension. Please try finding the repository for the VS Code Extension you are using and ask for help / report a problem there.
