### ISSUE TITLE
"Go to" commands broken in insider

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#140483]
For inlay hint I have tweak the "go to"-commands so that they can invoked with a location (https://github.com/microsoft/vscode/commit/120718992a05ccf3cf4b90237128e7c561086997). However, it seems that editor actions are always invoked with an empty arguments object...

**Comment by hediet** [comment]
Verification steps?

**Comment by jrieken** [comment]
To verify Invoke "go to definition" on a symbol with a definition

**Comment by hediet** [comment]
Works 👍
