### ISSUE TITLE
RPM repo source is too slow in China

### ISSUE THREAD

**Issue by rim99** [microsoft/vscode#140494]
I'm using Fedora for development.

When I execute `sudo dnf update`, it could take more than 4 minutes to sync with `Visual Studio Code` repo. (For other repos, it only takes several seconds)

I was wondering if it is prossible for MS:
1. to setup a host in China.
2. Or, somehow, to reduce the size of data for syncing

Thanks

**Comment by Tyriar** [comment]
Thanks, I passed this onto the repo admins
