### ISSUE TITLE
JS/TS Inlay hints settings should be scoped to resource

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#140414]
I use a multi-root workspace:

```json
{
	"folders": [
		{
			"path": "monaco"
		},
		{
			"path": "vscode-docs"
		}
	],
	"settings": {
		"files.associations": {
			"cglicenses.json": "jsonc"
		},
		"typescript.tsdk": "monaco/node_modules/typescript/lib",
		"emmet.excludeLanguages": [],
		"git.ignoreLimitWarning": true,
		"remote.extensionKind": {
			"msjsdiag.debugger-for-chrome": "workspace"
		},
		"typescript.tsc.autoDetect": "off"
	}
}
```

I do not see inlay hints in vscode (`monaco` is the `vscode` repo) even though they are enabled in workspace settings for `vscode`.

**Comment by jrieken** [comment]
@bpasero I cannot reproduce this... I have a dummy workspace that contains `vscode`, `monaco-editor`, and another folder and all works as expected, e.g by default inlays show everywhere, when disabling inlay per user-settings the vscode-folder still shows them. Anything else would also be surprising as there is no special workspace logic for inlay hints. 

Do you still see this? Iff so, can you set a breakpoints here: https://github.com/microsoft/vscode/blob/1498d0f34053f854e75e1364adaca6f99e43de08/src/vs/editor/contrib/inlayHints/browser/inlayHintsController.ts#L128

**Comment by bpasero** [comment]
Yeah, it goes past that breakpoint, it's something else. This is quite bizarre, I am able to reproduce with a fresh user data dir and fresh extensions dir on insiders even with just 1 folder (called `monaco` our repo) transitioning into multi root workspace:

![Recording 2022-01-24 at 16 46 26](https://user-images.githubusercontent.com/900690/150815759-6e31b11a-2da3-4276-9600-77bbd080eff1.gif)

When writing the workspace file we do migrate all workspace settings over into the multi root file, not sure that is relevant?

The full file ends up being:

```json
{
	"folders": [
		{
			"path": "../Development/Microsoft/monaco"
		}
	],
	"settings": {
		"files.associations": {
			"cglicenses.json": "jsonc"
		},
		"typescript.tsdk": "node_modules/typescript/lib",
		"git.ignoreLimitWarning": true,
		"remote.extensionKind": {
			"msjsdiag.debugger-for-chrome": "workspace"
		},
		"typescript.tsc.autoDetect": "off",
		"testing.autoRun.mode": "rerun",
		"explorer.experimental.fileNesting.patterns": {
			"*.js": "$(capture).*.js",
			"bootstrap.js": "bootstrap-*.js"
		}
	}
}

```

**Comment by bpasero** [comment]
Btw this reproduces from then on also after a window reload, so it is not related to entering the workspace. Maybe we can debug on my machine.

**Comment by bpasero** [comment]
@mjbvz it looks like typescript is not passing in the resource scope when resolving the configuration here:

https://github.com/microsoft/vscode/blob/8ef8933a1af8bc3613dcc375d7483c2fd6da6add/extensions/typescript-language-features/src/languageFeatures/inlayHints.ts#L100

Even though it is marked as resource setting:

https://github.com/microsoft/vscode/blob/e15397d2bb4625eb8ab18e69760b8b05e9c4abe7/extensions/typescript-language-features/package.json#L320

Not sure there are other settings that have this problem?

**Comment by mjbvz** [comment]
No this should be a unique case
