### ISSUE TITLE
Slow file loading

### ISSUE THREAD

**Issue by ilovecoding69420** [microsoft/vscode#140447]
Issue Type: <b>Slow performance while opening .txt utf-8 files</b>

When I load a file with drag n drop, or with open tab it loads in 5s. But when I load the file from opened folder everything is ok and the load time is almost instant.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by rzhao271** [comment]
\gifplease

**Comment by ilovecoding69420** [comment]
Drag n drop:
![Recording 2022-01-10 at 23 36 02](https://user-images.githubusercontent.com/97043299/148850372-e30a8215-360b-4ff7-9eff-9ef601eebda7.gif)
From folder:
![Recording 2022-01-10 at 23 40 28](https://user-images.githubusercontent.com/97043299/148850412-126833b7-1a36-4b6f-be63-99dac1cf7dbc.gif)

**Comment by bpasero** [comment]
Do you run as admin?

**Comment by ilovecoding69420** [comment]
> Do you run as admin?
Yes, i have an admin account.

**Comment by bpasero** [comment]
Does it reproduce with a non-admin user.

**Comment by DotWong** [comment]
I have the same problem. After opening the file about 200 times or more with drag n drop, it will start to slow down.

**Comment by bpasero** [comment]
Does it reproduce with a non-admin user.

**Comment by DotWong** [comment]
Yes

**Comment by DotWong** [comment]
Downgrade to 1.62.3 and then upgrade to 1.63.2. Opening files is very fast.
![Recording 2022-01-20 at 23 20 28](https://user-images.githubusercontent.com/7877560/150371468-c66a678b-e789-4265-a20f-b303a93c8bc5.gif)

Starts to slow down after opening a lot of files.
![Recording 2022-01-20 at 23 31 38](https://user-images.githubusercontent.com/7877560/150371819-2abe5b62-46b2-4594-b283-afe4106673d4.gif)

Open 1KB txt.
![Recording 2022-01-20 at 23 33 57](https://user-images.githubusercontent.com/7877560/150372087-20a83ab6-8984-4ecb-a966-358b5fe0e10d.gif)

**Comment by bpasero** [comment]
Indeed. 

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
In other words, this insider version improves the situation for you?

Back to the stable version, can you disable all extensions and try again.

From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by DotWong** [comment]
Yes, insider version improves the situation for me.

I tried `code --disable-extensions`. After opening many files, the file loading speed also slows down.

**Comment by bpasero** [comment]
@ilovecoding69420 can you also try with insiders?
