### ISSUE TITLE
Avoid showing a user notification for missing menu contributions

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#140463]
I'm deep in the process of adding virtual repository support to GitLens (for vscode.dev / github.dev) and because the Git extension doesn't exist on the web, VS Code shows this notification to users:

![image](https://user-images.githubusercontent.com/641685/148852003-dd30653f-6c94-457e-926f-0ab5dcb75d6a.png)

GitLens adds a command to that Git sub-menu and even if that menu item has a `when` clause that disables it, it still errors. 

This will only get worse as I add more functionality to virtual workspaces, since there will be menu's that only exist in one environment and not the other.

Can this notification be suppressed?

/cc @jrieken @joaomoreno

**Comment by IllusionMH** [comment]
Looks a bit similar to #136222, but that one at least doesn't popup in notifications.
Maybe it's possible to add something like `extensions:name` check in `when` clause or as separate key to mark these contributions optional unless user has required extension.

**Comment by joaomoreno** [comment]
Wait, so there is a notification? In #136222 it was just about devtools printing out stuff. But I did get the feeling that people might be seeing something more, since @alexr00 keeps getting dupes for this.

**Comment by jrieken** [comment]
I am pretty sure this surfaces as notification in extension development mode only. When running "for real" it's just log messages

**Comment by jrieken** [comment]
This uses the default collector infrastructure from @alexdima 

https://github.com/microsoft/vscode/blob/112709a721bdad02bf4a658f686be3bb5af4e8c6/src/vs/workbench/api/common/menusExtensionPoint.ts#L748

**Comment by joaomoreno** [comment]
>  I am pretty sure this surfaces as notification in extension development mode only. When running "for real" it's just log messages

Yeah. @eamodio, considering this, I would argue once again not to do anything. It's a good warning to see when you're developing an extension. But it doesn't show up to any user.

**Comment by alexr00** [comment]
My understanding is that the notification shows when doing extension debugging.

It also shows in the "Show Running Extensions View" always (no debugging required). This is the place that I keep getting bugs filed from.

**Comment by eamodio** [comment]
Even if it is only on when debugging -- imo it is pretty annoying and only going to get more so when trying to run in different environments. Personally, a console warning (only when debugging) feels like enough.

And as @alexr00 mentioned even not debugging it shows up at the _Running Extension_ page
![image](https://user-images.githubusercontent.com/641685/148992696-20981564-33d5-4d3e-9e75-503516e1f2f3.png)

And it shows up in the console
![image](https://user-images.githubusercontent.com/641685/148992635-c7d893d8-e68b-4de5-a09b-d1e6c745a7dd.png)

IMO, when not debugging, it shouldn't show up in either place.

**Comment by alexdima** [comment]
I have taken a quick look at what most usages of `collector.warn` complain about and I think most of them should remain, just like they are today, a notification when doing extension development.

Here is what I would like to suggest: If we know there are certain valid product configurations where certain menus will be missing (e.g. like web serverless where the `git.commit` menu contributed by the `git` extension does not exist), then I think this specific warning could be converted to a `collector.info` call. What do you think @jrieken ?

**Comment by eamodio** [comment]
@alexdima would it be really possible to know that? It doesn't feel like it -- unless the whole class of submenu warnings are converted to infos, since submenus are "dynamic".

Here's another scenario, let's say the GHPR (or whatever) extension contributes a submenu called `pr.actions`, and GitLens (or any other extension) wants to add to that menu (when its available). That wouldn't be something VS Code could tell would or would not be a problem.

Also, another case against the notifications, won't notifications pop up for everyone when debugging? Meaning, if GitLens has an "issue" with a menu, and someone else is debugging their own extension with GitLens installed, won't they end up getting GitLens warning notifications?

**Comment by jrieken** [comment]
We don't know much, only that there is contribution to a menu that's unknown. It could be a typo of a menu identifier that exists (like `editor/tilte` instead of `editor/title`) or it could be the correct name of a submenu that isn't available (because the corresponding extension isn't there). If we turn this into an info-message it might be less annoying but it will also not help to detect real issues anymore.

**Comment by jrieken** [comment]
Discussed this with @alexdima and came to the following conclusion. With the introduction of submenus we allow extension A to contribute to the menu of extension B. This means statically we cannot know all menu ids any more, also dynamically we can only know them when the right set of extensions is installed. Given this we think we shouldn't warn/complain about contributing to an unknown menu anymore at all (because it couples extensions tighter). We will print a simple information message is surfaced less dramatic. That allows to do optional menu contributions but comes at the cost of not being notified when misspelling the name of a well-known menu identifier.

**Comment by jrieken** [comment]
fyi @joaomoreno on ⬆️

**Comment by joaomoreno** [comment]
Thanks for this!
