### ISSUE TITLE
vscode code base - migrate to consuming typings from npm as supported by TS 2.0

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#14043]
The code base still includes a [typings folder](https://github.com/Microsoft/vscode/tree/master/src/typings).

Now, that we are on 2.0 we should consider migrating to consume typings through npm.

**Comment by dbaeumer** [comment]
Blocked by https://github.com/jrieken/gulp-tsb/issues/51

**Comment by dbaeumer** [comment]
Did not make it for November.

**Comment by dbaeumer** [comment]
Some improvements happened but we still have quite some code referring to d.ts files in the typings folder.

**Comment by gulshan** [comment]
Is it still relevant?

**Comment by dbaeumer** [comment]
Yes, there is still a typings folder mainly because we customize some of the typings. Need to investigate which once we need to keep.

**Comment by dbaeumer** [comment]
I am closing the issue. I looked over the typings folder and there are now quite some new typings because we forked existing npm modules. For the once were it looked reasonable we have them in the package.json now (see https://github.com/Microsoft/vscode/blob/master/package.json#L62)
