### ISSUE TITLE
Home key navigates behind indetation

### ISSUE THREAD

**Issue by TobiaszCudnik** [microsoft/vscode#140488]
- VS Code Version: v1.63.0
- OS Version: 5.15.5-arch1-1

Steps to Reproduce:

1. Use this JS (^ is the cursor position)
```
function foo() {
    console.log(1)^
}
```
2. Press the Home key

Expected:
```
function foo() {
    ^console.log(1)
}
```

Current:
```
function foo() {
^    console.log(1)
}
```

Second time Home is pressed, it should go pass the indentation. Thx.

**Comment by alexdima** [comment]
@TobiaszCudnik Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `Home`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by TobiaszCudnik** [comment]
```
[2022-01-14 12:18:04.468] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: Home, keyCode: 36, key: Home
[2022-01-14 12:18:04.469] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: Home, keyCode: 14 ('Home')
[2022-01-14 12:18:04.470] [renderer1] [info] [KeybindingService]: | Resolving [Home]
[2022-01-14 12:18:04.470] [renderer1] [info] [KeybindingService]: \ From 6 keybinding entries, matched cursorLineStart, when: textInputFocus, source: user.
```

**Comment by alexdima** [comment]
> `From 6 keybinding entries, matched cursorLineStart, when: textInputFocus, source: user.`

@TobiaszCudnik The default for `Home` would be the command `cursorHome`. It looks like you have defined a keybinding which executes `cursorLineStart` when pressing `Home` in your personal `keybindings.json`. If this is undesired I suggest that you edit your `keybindings.json` and remove the keybinding using `F1` > `Open Keyboard Shortcuts (JSON)`.
