### ISSUE TITLE
`Install Another Version...` takes a really long time for the C# extension only

### ISSUE THREAD

**Issue by cateyes99** [microsoft/vscode#140525]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: **_1.63.2_**
- OS Version: **_Windows 10 Enterprise, Version 20H2, OS Build 19042.1415_**

I raised [an issue](https://github.com/OmniSharp/omnisharp-vscode/issues/4973) regarding this in **OmniSharp-VSCode**'s repo, but they suggested that the issue should be raised here.

Steps to Reproduce:

For weeks, i've noticed that among the all extensions i've installed, the C# one is the only one has this issue. Go to the Extensions view. Click `Install Another Version...` on the menu for the **C#** extension. Observe that after hanging for a **_long_** time (it took me **56** seconds), the expected list of versions finally shows up.
![VSCodeCSharpExtensionInstallAnotherVer](https://user-images.githubusercontent.com/19678455/147300602-5ef4f46a-4b36-4a9d-972f-e3c56efefb3b.gif)

**Comment by MrPointer** [comment]
Getting the same behavior with the **Gitlab Workflow** extension, also takes forever but eventually loads.  
Seems it happens with extensions that have many versions -> long list to produce

**Comment by cateyes99** [comment]
@sandy081 could you please mention which one this duplicates?

**Comment by sandy081** [comment]
There is a PR - https://github.com/microsoft/vscode/pull/136992 for this and not an issue tracking it. I will use this issue for tracking that PR
