### ISSUE TITLE
Vs code android

### ISSUE THREAD

**Issue by Ninjacoderhsi** [microsoft/vscode#140507]
![Screenshot_۲۰۲۲۰۱۱۱-۲۰۰۷۰۲_vs code mobile](https://user-images.githubusercontent.com/89408667/148988367-8ee29c45-2689-4484-b6dd-ec7583929324.jpg)
![Screenshot_۲۰۲۲۰۱۱۱-۱۵۵۹۱۷_vs code mobile](https://user-images.githubusercontent.com/89408667/148988375-b94164c2-c1d2-48da-ba0a-238934bbab4f.jpg)

Hello, I am an Android developer and I want to publish the vs code program for Android. Do you grant the necessary permissions?

**Comment by luisdavim** [comment]
I think an official android version of vscode on the play store would be awesome, especially with tablets and Samsung  Dex becoming more powerful and popular.

**Comment by chrisdias** [comment]
dupe of #126147

**Comment by Ninjacoderhsi** [comment]
> 

Yes, I created a version but it is not very powerful. I am updating this program. I update about 5 times a month.
