### ISSUE TITLE
Hot Exit: properly deal with backups to files that got deleted

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14054]
Today a workspace path is the identifier for a backup but you need to consider the case of a folder getting deleted and recreated with the same name. For that, each `IWorkspace` object carries an identifier (this is actually the `ctime`). You need to take this into account when finding backups and you need to discard backups if you detect that a workspace with same path but different ID is opened.

**Comment by Tyriar** [comment]
But then someone's unsaved work could go missing? Let me see if I understand:

1. Clone vscode to `/dev/vscode`
2. Open `/dev/vscode` in VS Code
3. Dirty `/dev/vscode/gulpfile.js`
3. Dirty an untitled file
4. Exit VS Code
5. Delete `/dev/vscode`
6. Clone vscode to `/dev/vscode`
7. Open `/dev/vscode` in VS Code

At this point `/dev/vscode` would use a different identifier but I would still expect both text and untitled backups to be restored, regardless of whether `/dev/vscode/gulpfile.js` exists anymore or not. Better safe than sorry, people will be trusting vscode to not randomly delete the files.

**Comment by bpasero** [comment]
@Tyriar good point. however then please make sure your restore logic can deal with the fact that a file might not be on disk anymore. In other words: A backup to a file that does not exist on disk should be converted to an untitled file to restore with the path of the file. Only that ensures you do not see crashes on the way to restoring it :)

**Comment by bpasero** [comment]
@Tyriar I have updated the summary, actually this issue applies no matter what happens to the workspace. You can always close Code, delete a file that is still somewhere known as backup. Upon restoring you need to check if the file exists or not and do the right thing.

**Comment by Tyriar** [comment]
Currently same situation as https://github.com/Microsoft/vscode/issues/14063#issuecomment-255316576

![image](https://cloud.githubusercontent.com/assets/2193314/19590743/3c954744-9728-11e6-891a-858bd942581b.png)

**Comment by bpasero** [comment]
@Tyriar ok I think both cases are somewhat related, I expect:

* if the file is deleted on disk but the workspace still exists, the window with the workspace is opened and an untitled file created using the same path as the file that is now deleted

* if the workspace is deleted but the file still exists I expect to see an empty window with that file visible as untitled file with associated path

If you wonder what an "untitled file with associated path" is, just start code from command line with a file name that does not exist. It will open as untitled file with that path associated and when you save it saves to that provided path.

**Comment by Tyriar** [comment]
I no longer consider this a blocker for the initial merge as the current behavior is that the file is simply not restored currently (no message to create because the part service is not yet ready [here](https://github.com/Microsoft/vscode/blob/1437e44ce4658f07fe16cf270b4109eadf9a90d9/src/vs/workbench/browser/parts/editor/editorPart.ts#L439)).

@bpasero if I understood correctly I need to handle the error that is being bubbled up from `TextFileEditorModel` and transform the input into an `UntitledEditorInput`, have any tips at what level this should be handled as I don't see anything similar happening? It could also be done by forcing the createMissingFile prompt when there is a backup present?

**Comment by bpasero** [comment]
I would not assume that this error handling happens inside the renderer but instead on the main side where you decide which files to open and which untitled files to open you have to check if the file exists and if not do the right thing so that it ends up to be an untitled file that gets restored. Anything else is messy...

**Comment by Tyriar** [comment]
Yeah it was looking messy, main side will be much better thanks.

**Comment by bpasero** [comment]
I think we need to handle this from the renderer: upon startup when we restore backups we should check if the file exists and if not, open an untitled file with the associated path and backup.

**Comment by bpasero** [comment]
One idea would be to do this from the workbench contribution that restores backups: It has to check for each backup of a workspace if the file still exists and if not, do the right dance of opening an untitled file with the associated file path.

**Comment by bpasero** [comment]
Marking as important because this means potential data loss. Here is what happens:
- make a file dirty
- quit
- delete it
- reopen
=> file is not restored
=> data loss

**Comment by bpasero** [comment]
✊ this one is tricky ✊

**Comment by Tyriar** [comment]
As you mentioned, during launch on the main process you could check to make sure all backed up text files have their original sources still, if not move them to `../untitled/` as untitled files now keep metadata too.

**Comment by bpasero** [comment]
It is pragmatic but means ugly startup slowdown if there are many files :-|

**Comment by bpasero** [comment]
I found a nice solution without doing any more fs calls on the main side: When a file loads on startup (e.g. due to the backup restorer doing its work), I detect the case of a FILE_NOT_FOUND error and in  that case check for a backup being present. If so, I ignore the error and just create the file with the backup content. The file model can deal with the fact that a file does not exist anymore on disk because this can also happen without backups (e.g. you have a dirty file and delete it from disk, the dirty file is still opened in the editor).
