### ISSUE TITLE
Angular, wrong import added

### ISSUE THREAD

**Issue by perl80903** [microsoft/vscode#140582]
Issue Type: <b>Bug</b>

Not sure if this is an add-on or VS Code proper responsible for this.

I am fairly new to both Angular and VS Code (though not VS), and I've been following some corporate training via pluralsight.com. 

Whenever I reference a new component in an Angular module's code section, VS Code helpfully adds the required import declaration automatically at the top of the module, however occasionally it's not the right one. 

For example today when I needed to use EventEmitter, VS Code added 

import { EventEmitter } from 'protractor'

where what I really needed was

import { EventEmitter } from '@angular/core'

Since the import section wasn't even on screen at the time when this was happening, I failed to notice and it took me quite a while to track down what was causing all those obscure compilation errors that npm start emitted. VS Code itself showed no issues.

Could VS Code perhaps detect when multiple declarations of the same component exists and not do the automatic import declaration in that case?

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|13.1.0
better-cpp-syntax|jef|1.15.10
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
angular-component-extension|oni|0.0.14

(1 theme extensions excluded)

</details>
Please paste.

**Comment by IllusionMH** [comment]
VS Code should show all suggestions that match criteria and only add imports after you accept one. So you should be able to pick which one you need. Do you see suggestions box?

If not - check if you see this behavior in regular TS files with extensions disabled.
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`
