### ISSUE TITLE
How to show delete confirmation window in custom treeview (VSCode Extension)

### ISSUE THREAD

**Issue by Codes-Breaker** [microsoft/vscode#140543]
I would like to have a popup window like this in my custom treeviewprovider. Is there any api I could use?
![image](https://user-images.githubusercontent.com/10660055/149053242-4c3087e9-b2b2-4fbb-820c-5aae23528810.png)

**Comment by yume-chan** [comment]
`vscode.window.showInformationMessage('Hello', { modal: true }, { title: 'OK' });`

![image](https://user-images.githubusercontent.com/1330321/149056189-ea124296-9653-4f1d-bba3-cefa9a12b70e.png)

**Comment by Codes-Breaker** [comment]
> `vscode.window.showInformationMessage('Hello', { modal: true }, { title: 'OK' });`
> 
> ![image](https://user-images.githubusercontent.com/1330321/149056189-ea124296-9653-4f1d-bba3-cefa9a12b70e.png)

Is it possible for this dialog to show in the center of editor?

**Comment by yume-chan** [comment]
It's showing in the center. Try it yourself.

**Comment by Codes-Breaker** [comment]
> vscode.window.showInformationMessage('Hello', { modal: true }, { title: 'OK' });

Thanks for the help. How can I achieve the style like the one you posted? Mine seems really ugly..
![image](https://user-images.githubusercontent.com/10660055/149076679-382de453-a308-4088-a4e1-db866b8df9e3.png)

**Comment by yume-chan** [comment]
I have the `"window.dialogStyle": "custom"` setting. You can't change this only for your dialogs.

**Comment by Codes-Breaker** [comment]
> "window.dialogStyle": "custom"

Can I write this in my extension settings.json?

**Comment by yume-chan** [comment]
Yes, although not recommended.

For example

```ts
    const configuration = vscode.workspace.getConfiguration('window');
    let oldValue = configuration.get('dialogStyle');
    if (oldValue !== 'custom') {
      await configuration.update('dialogStyle', 'custom', vscode.ConfigurationTarget.Global);
    }
    await vscode.window.showInformationMessage('Hello', { modal: true }, { title: 'OK' });
    if (oldValue !== 'custom') {
      await configuration.update('dialogStyle', oldValue, vscode.ConfigurationTarget.Global);
    }
```

**Comment by alexr00** [comment]
All the suggestions above are good (including that it's not recommended to overwrite user settings unexpectedly), thanks @yume-chan!
