### ISSUE TITLE
Disable default typescript libraries

### ISSUE THREAD

**Issue by OldStarchy** [microsoft/vscode#140537]
I often will write up some notes in the form of some typescript interfaces, especially when scoping some new features.

I run into problems with naming conflicts with the default libs, eg. "Duplicate identifier 'Image'" when penciling in an image class.

For code in a project, I can use a tsconfig.json like so

```json
{
    "compilerOptions": {
        "lib": []
    }
}
```

however I don't often save these files to disk, rather they remain as unsaved editors in a non-workspace window until I eventually post it to the team in Jira or slack.

Perhaps a more common example is when I'm writing short scripts to test/calculate something, and I can run the script using the Code Runner extension, it makes no sense to have the DOM types, I'd rather set it to use node types instead.

**Comment by yume-chan** [comment]
Currently there are

* `js/ts.implicitProjectConfig.checkJs`
* `js/ts.implicitProjectConfig.experimentalDecorators`
* `js/ts.implicitProjectConfig.strictFunctionTypes`
* `js/ts.implicitProjectConfig.strictNullChecks`

I propose a `js/ts.implicitProjectConfig` setting that accepts the same object format as `tsconfig.json` (or just the `compilerOptions` section)
