### ISSUE TITLE
Remote smoke tests on Linux can stall when restarting VS Code

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140571]
Linux smoke tests (remote) window stuck on checking the status bar while connecting to remote. https://dev.azure.com/monacotools/Monaco/_build/results?buildId=149407&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=87fb4592-a208-5e50-19ed-a089f1b91f06

```
  3 failing

  1) VSCode Smoke Tests (Electron)
       Data Loss (insiders -> insiders)
         verifies that "hot exit" works for dirty files (without delay):
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/1/s/test/smoke/out/main.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  2) VSCode Smoke Tests (Electron)
       Data Loss (insiders -> insiders)
         "after each" hook for "verifies that "hot exit" works for dirty files (without delay)":
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/1/s/test/smoke/out/main.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  3) VSCode Smoke Tests (Electron)
       Data Loss (insiders -> insiders)
         "after all" hook for "verifies that auto save triggers on shutdown":
     Error: Smoke test exit call did not terminate process after 20s, giving up
      at /__w/1/s/test/automation/out/code.js:152:32
```

Smoke runner log:

```
[2022-01-11T12:01:29.508Z] getElements .monaco-workbench .statusbar-item[id="status.host"]
[2022-01-11T12:01:29.590Z] [electron] stdout: [90m[main 2022-01-11T12:01:29.590Z][0m [driver] getWindowDriver(1)

[2022-01-11T12:01:48.822Z] stopTracing checkWindowReady_instance_3
[2022-01-11T12:02:27.749Z] 
[2022-01-11T12:02:27.749Z] >>> !!! FAILURE !!! Test end: 'verifies that "hot exit" works for dirty files (without delay)' !!! FAILURE !!! <<<
```

https://github.com/microsoft/vscode/blob/9c0cce1dae7e2cc028564a50861d4c22673f2bcc/test/automation/src/application.ts#L143-L158

**Comment by Tyriar** [comment]
Think this is the same issue, stuck on status.host: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=150177&view=artifacts&pathAsName=false&type=publishedArtifacts

```
[2022-01-14T10:55:51.524Z] [electron] stdout: [90m[main 2022-01-14T10:55:51.523Z][0m [driver] getWindowDriver(1)

[2022-01-14T10:55:51.541Z] getElements .monaco-workbench .statusbar-item[id="status.host"]
[2022-01-14T10:56:10.793Z] stopTracing checkWindowReady_instance_8
[2022-01-14T10:56:49.783Z] exitApplication
```

**Comment by bpasero** [comment]
I think this one here is another incarnation of an unhealthy driver connection: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=151088

**Comment by Tyriar** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=151786&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=968972e0-8dc3-5713-9454-eac40de9dc16

**Comment by JacksonKearl** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=155837&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=79e950e2-ae58-5fea-a241-0229f56d23a3

**Comment by bpasero** [comment]
This is becoming one of the main flaky reasons for smoke tests.

**Comment by Tyriar** [comment]
I definitely won't have time this week or next for this

**Comment by bpasero** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=156114&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=79e950e2-ae58-5fea-a241-0229f56d23a3&l=68

**Comment by joaomoreno** [comment]
Having clicked all build failures linked above, common traits are:

- Always Linux x64
- Always remote smoke tests
- Always in tests in which Code needs to be restarted

So, my back of the envelope estimation: there's something in the implementation of `app.restart()` which makes Code/driver/smoke suite hang. This has nothing to do with status bar entries.

**Comment by joaomoreno** [comment]
1 month later, @Tyriar have you seen this since?

**Comment by bpasero** [comment]
I did not.
