### ISSUE TITLE
[Typescript]: Editor should convert imports to type imports on save

### ISSUE THREAD

**Issue by Nokel81** [microsoft/vscode#140520]
There is a TS refactoring called "convert to type-only import", it would be highly useful if this could be run `onSave` like some other refactorings.

**Comment by vuki656** [comment]
For those using eslint + typescript, there is an auto fixable rule for that https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-imports.md

**Comment by Nokel81** [comment]
Yes I see, however it splits the imports which isn't necessary anymore

**Comment by mjbvz** [comment]
Since this is more or less a style preference, it is a better fit for a linter instead of something in core VS Code

You can file feature request against ESLint if it currently doesn't behave as you expect
