### ISSUE TITLE
Maximum call stack size exceeded in bracket matching

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#140534]
![image](https://user-images.githubusercontent.com/323878/149046019-555ece32-6a99-47b7-8818-6f31cb8a348c.png)

I was making some edits in a notebook cell, and have this text (just deleting the try:). I put my cursor on line 2 and press tab, and get the error popup

```
for i in range(20):
            
        print(i)
        time.sleep(1)
    except KeyboardInterrupt:
        print("Stopping...")
        break
```

**Comment by hediet** [comment]
Unfortunately, I cannot reproduce this.
What are the exact reproduction steps?

**Comment by roblourens** [comment]
I was having issues last night but I can't get it to happen today. I'll let you know if I manage to repro it

**Comment by hediet** [comment]
Notice that for reproduction, all the edits since you open the document matter.
