### ISSUE TITLE
`code` launch script no longer works (from wsl)

### ISSUE THREAD

**Issue by crispinb** [microsoft/vscode#140542]
Issue Type: <b>Bug</b>

- launch Windows Terminal (wsl / Ubuntu 20.04)
- enter `code` (or `code .` if in relevant dir)

Expected: VSCode launches (in workspace if folder supplied)
Actual:  command hangs (is interruptible with ctrl-c)

Same result with Insiders build, and `code --disable-exensions`
`code.cmd` works find in cmd & powershell.

`code` worked until a day or two ago - the one thing I know I've changed was my wslg version (upgraded from 1.0.26 to 1.0.29 via the Microsoft Store), but I'm not entirely sure about the order of events.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Fetching remote diagnostics for 'WSL: Ubuntu-20.04' failed: Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (18.52GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu-20.04/home/crispinb/src/crispinb/wengrow_data_structures/elixir --crash-reporter-id 1a377100-8204-4312-96a3-11731d34e89a|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu-20.04' failed: Canceled
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.1
vscode-terminal-themes|ctf|0.1.1
gitlens|eam|11.7.0
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
filter-line|eve|2.0.1
vscode-test-explorer|hbe|2.21.1
elixir-ls|Jak|0.9.0
reflow-markdown|mar|2.1.0
markdown-formatter|mer|0.9.7
metago|met|4.2.0
MetaJump|met|1.4.0
MetaWord|met|1.3.0
vscode-docker|ms-|1.18.0
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
live-server|ms-|0.2.12
test-adapter-converter|ms-|0.1.5
phoenix|pho|0.1.1
markdown-checkbox|PKi|1.7.2
java|red|1.2.0
elixir-jump-to-test|sam|0.2.0
vscode-autohotkey|sle|0.2.2
zig|tie|0.2.5
beamdasm|Val|1.1.5
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2
quokka-vscode|Wal|1.0.435
recenter-top-bottom|yea|0.1.2
vscode-eex-beautify|zer|0.2.2
material-theme|zhu|3.13.10

(11 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710cf:30416617
vsccppwtstudy:30421978

```

</details>

**Comment by crispinb** [comment]
I just found that if the workspace in `code <workspace>` is on the windows filesystem, it works fine. Also `ssh` isn't working. So this is a distro/network issue - nothing to do with VS Code after all. I'll therefore close this issue.

**Comment by JacobDeuchert** [comment]
Did you solve the problem? 

With the latest Insider Build i have the same problem. When starting VS Code from the Teriminal with `code` it works in windows but when used inside WSL i get the following error:

`/mnt/c/Users/j.deuchert/.vscode-insiders/extensions/ms-vscode-remote.remote-wsl-0.63.13/scripts/wslCode.sh: 69: /home/jdeuchert/.vscode-server-insiders/bin/753319a08f8e74700b1dba3a29bf0a6af7c2953f/bin/code-insiders: not found`

What i tried so far:

- Deleting .vscode-server-insiders and let it reinstall
- Rebooting WSL with `wsl --shutdown`
- Rebooting Windows
- Reinstalling WSL Extension
`

**Comment by JacobDeuchert** [comment]
@aeschli 
Just tested it, works again. Thanks a lot for the fix.
