### ISSUE TITLE
No code hints

### ISSUE THREAD

**Issue by 819049639** [microsoft/vscode#140556]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2 (Universal)
- OS Version: macOS Monterey 12.0.1

Steps to Reproduce:

1. No code hints;
2. No JS or TS code prompts for reinstalling software or reconfiguring settings.json files;

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo
