### ISSUE TITLE
window.withProgress: using location: { viewId: ..} shows invalid progress

### ISSUE THREAD

**Issue by MikeSchulze** [microsoft/vscode#140576]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: MacOS Big Sur 11.3

Steps to Reproduce:

1. Create a new extension and put the code in
```
export function activate(context: vscode.ExtensionContext) {
	testProgressBar();
}

function testProgressBar() {
	vscode.window.withProgress({
		location: { viewId: 'TestInspector'}
		//location: vscode.ProgressLocation.Notification
	}, (progress, token) => {
		let counter = 0;
		let interval: NodeJS.Timeout;
		return new Promise((resolve, reject) => {
			interval = setInterval(() => {
				progress.report({ message: `Run test ${counter}:100`, increment: 1});
				counter++;
				if (counter === 100) {
					clearInterval(interval);
					resolve("100");
				}
			}, 100);
		});
	});
}

```
package.json
```
"contributes": {
		"viewsContainers": {
			"activitybar": [
				{
					"id": "inspector-view",
					"title": "Progress Test",
					"icon": "resources/test.svg"
				}
			]
		},
		"views": {
			"nspector-view": [
				{
					"id": "TestInspector",
					"name": "Test Inspector"
				},
			]
		},
```

It shows a invalid progress (only a small line is sliding from left to right)
![image](https://user-images.githubusercontent.com/347037/149176032-c71cfd03-befb-469d-9200-397c6cb75b30.png)

When i use `location: vscode.ProgressLocation.Notification` instead the progress bar is shown as.
![image](https://user-images.githubusercontent.com/347037/149175072-537fc410-ee71-4b64-ad9e-f2944b87e1f2.png)

**Comment by bpasero** [comment]
Hm, this never worked. Exits early here:

https://github.com/microsoft/vscode/blob/fe227dacb71c40c38e91a5f59a407f6c37def728/src/vs/workbench/services/progress/browser/progressService.ts#L473-L475

**Comment by MikeSchulze** [comment]
thanks, that was fast +1

**Comment by bpasero** [comment]
Yup, we do not support this in that location. I think we document that in the API too.
