### ISSUE TITLE
VSCode 1.63.2 Install Plugins

### ISSUE THREAD

**Issue by ITCTOM** [microsoft/vscode#140558]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: Windows Server Standard 2019 Version	10.0.17763 Build 17763

Steps to Reproduce:

1. Start VSCode
2. Install PlugIns
3. in Shared Process i got the Error "DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/899d46d82c4c95423fb7e10e68eba52050e30ba3/node_modules/applicationinsights/out/Library/EnvelopeFactory.js.map: Certificate error: net::ERR_CERT_AUTHORITY_INVALID"

Regards

  Thomas

**Comment by lramos15** [comment]
Do you mind providing information about what extensions you installed? I have plenty of extensions installed and don't see this
