### ISSUE TITLE
vscode window becomes intermitently unscrollable when working on Jupyter Notebooks

### ISSUE THREAD

**Issue by atticusmatticus** [microsoft/vscode#140504]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Open a large enough notebook that it can be scrolled and scroll down. The page stops and cannot be scrolled down intermitently. Scrolling up still works but continuing down will not work at all until you wait for a few seconds. Issue repeats all the time.

VS Code version: Code - Insiders 1.64.0-insider (00f1ca47ada2fda8ee1437e17b27af5b4002cecb, 2022-01-11T09:14:06.453Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.0-10-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (24.78GB free)|
|Process Argv|--crash-reporter-id 5d6ed546-7e98-45e4-83fc-3dfcdb8502ec --crash-reporter-id 5d6ed546-7e98-45e4-83fc-3dfcdb8502ec|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vaderl|
|OS|Linux x64 5.10.0-10-amd64|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3591)|
|Memory (System)|31.18GB (23.40GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.211.0
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
vim|vsc|1.21.10
viml|Xad|1.0.1
python|ms-|2022.0.1679807046-dev
vscode-pylance|ms-|2022.1.1-pre.1
jupyter|ms-|2022.1.1001614873
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
synthwave-vscode|Rob|0.1.10

(4 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@atticusmatticus can you please share the notebook to help troubleshoot?

**Comment by atticusmatticus** [comment]
Sure, it's happening on this notebook among others: https://github.com/fastai/fastbook/blob/master/10_nlp.ipynb
My local copy of this notebook should be identical but here it is just incase it isn't:
[10_nlp.ipynb.zip](https://github.com/microsoft/vscode/files/7865823/10_nlp.ipynb.zip)

**Comment by rebornix** [comment]
@atticusmatticus thanks for your help, this is a really good catch.
