### ISSUE TITLE
Hot Exit: promise handling is often bad

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14052]
I found many places where a method is called that actually returns a `promise`. Without adding a `done` handler you swallow possible errors and also make it very hard to understand that a method call is a long running operation.

A typical pattern we use is `method().done(null, errors.onUnhandledException)`. 

Examples: `untitledEditorModel`

**Comment by bpasero** [comment]
@Tyriar fyi only found [some](https://github.com/Microsoft/vscode/commit/683673394adbe8fba803c21b47736132a6333e4a) in `backupModelTracker.ts`.

**Comment by Tyriar** [comment]
Thanks, I had a look at this but wasn't sure which were relevant now. I reviewed the commit for future reference :smile:
