### ISSUE TITLE
Inlay hints can cause scrolling to jitter

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#140527]
1. Have word wrap and inlay hints on
2. Have a file where the addition of an inlay hint causes a line to wrap
3. Scroll around slowly using the mousewheel and notice you get jitter.
3. Scroll just right and you get infinite jitter.

![](https://memes.peet.io/img/22-01-31a3354b-223f-4096-afc5-258db702adb7.gif)

**Comment by jrieken** [comment]
@connor4312 We cannot reproduce this. Can you share more details? What's the exact view port when this happens? Can you do breakpoints [here](https://github.com/microsoft/vscode/blob/ec78252383bb7733ef0bb11bc00132d0161f8444/src/vs/editor/contrib/inlayHints/inlayHintsController.ts#L413)

**Comment by jrieken** [comment]
ping @connor4312

**Comment by connor4312** [comment]
I'm not seeing this today, where previously I saw it happen trivially in any large file. Closing unless it comes up again...
