### ISSUE TITLE
Secondary panel (terminal, outline) doesnt remeber position and opened tab

### ISSUE THREAD

**Issue by impnet** [microsoft/vscode#140552]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.0-insider (system setup) 2022-01-07T09:50:37.680Z
- OS Version: Windows 10 PRO 64-bit 21H2 19044.1466

Steps to Reproduce:
1. Open VS code
2. Shortcut Ctrl+J
3. Panel with terminal open on the bottom instead of right position

This happen after last update.

JSON settings:
```json
{
    "workbench.startupEditor": "none",
    "workbench.colorTheme": "Default Light+",
    "workbench.panel.defaultLocation": "right",
    "editor.tabSize": 2,
    "editor.folding": false,
    "editor.renderIndentGuides": false,
    "window.autoDetectHighContrast": false,
    "files.trimTrailingWhitespace": true,
    "editor.fontSize": 15,
    "files.maxMemoryForLargeFilesMB": 8192,
    "php.memoryLimit": "14336M",
    "explorer.confirmDelete": false,
    "editor.minimap.enabled": false,
    "C_Cpp.updateChannel": "Insiders",
    "diffEditor.ignoreTrimWhitespace": false,
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "window.restoreWindows": "none",
    "security.workspace.trust.untrustedFiles": "open",
    "timeline.excludeSources": [],
    "security.workspace.trust.enabled": false,
    "php.validate.executablePath": "C:\\Program Files\\PHP\\php-7.4.20-nts-Win32-vc15-x64\\php.exe",
    "editor.largeFileOptimizations": false,
    "git.enabled": false,
    "workbench.statusBar.visible": false,
    "workbench.experimental.panel.alignment": "right",
    "workbench.panel.opensMaximized": "always",
}
```
**What i need as default positions:**
- Left panel with files
- Right panel with functions
![what i need](https://user-images.githubusercontent.com/46919973/149086453-4ae1a08b-ea0d-42fe-b764-7ca62573bb15.png)

When opened any single file i get this:
-Panel with outline not visible
![open file](https://user-images.githubusercontent.com/46919973/149086461-46c6662f-ad3a-475e-8dbc-f42aaccd6bc3.png)

When press Ctrl+J i get this:
-Open everytime at bottom and cover the whole editor
-Open everytime Terminal tab instead Outline
![open panel](https://user-images.githubusercontent.com/46919973/149086468-8e20a618-38f8-4ab4-a234-e1916381a192.png)

**What i need for opening single file:**
- Left panel with files
- Right panel with functions
![wha i need for single file](https://user-images.githubusercontent.com/46919973/149086880-35ddbb14-5e58-424a-932f-903198e5b890.png)

**Comment by impnet** [comment]
Remember position panels after update solved.

**Comment by impnet** [comment]
Can i make "Outline" tab as default for "Ctrl+J" panel?

**Comment by sbatten** [comment]
You can bind the command `outline.focus` to Ctrl+J to always open outline view

**Comment by impnet** [comment]
@sbatten thank you ver much =)
