### ISSUE TITLE
Styling of links is wrong within the banner

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode#140579]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.0-dev
- OS Version: Mac OS 12.1

Steps to Reproduce:

1. Create a banner which uses a link. 

```ts
    this.bannerService.show({
      id: 'test_id',
      icon: CodiconUtil.bellDot,
      message: new MarkdownString('**Test Message** [link](http://test/)'),
    });
```

![image](https://user-images.githubusercontent.com/150152/149171047-f6761bea-b1bd-435f-b74b-c33207863cfa.png)

Even though BannerService accepts a `MarkdownString`, the styling of links does not work as expected.

Note, this does not effect links provided within actions, just links defined within the markdown.

**Comment by JacksonKearl** [comment]
<img width="266" alt="image" src="https://user-images.githubusercontent.com/8586769/165817385-9f6a77fa-36be-4122-9b09-b7b1e53424c7.png">
codicon color could be tweaked but overall 👍
