### ISSUE TITLE
Notebook on reload renders incorrectly 

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#140515]
Just restarted VScode to install insider update. This notebook was already opened and reopened in this state.

Python: v2022.0.1668608660-dev
Jupyter-renderer: v1.0.4 - prerelease
Jupyter: v2022.1.1001681627 - prerelease

vscode: 1.64.0 - insider

<img width="496" alt="Screenshot 2022-01-11 143506" src="https://user-images.githubusercontent.com/10987493/149010091-7f1b2b0d-84f0-461a-a575-0d2fe826fa41.png">

_Originally posted by @matrix303 in https://github.com/microsoft/vscode/issues/139609#issuecomment-1010300546_

**Comment by matrix303** [comment]
Also occurring on simply opening files. eg. just opened a file not used. 

<img width="392" alt="image" src="https://user-images.githubusercontent.com/10987493/149010747-0a59a877-1289-46a0-b328-7072c9adf7a3.png">

**Comment by rebornix** [comment]
I couldn't reproduce but it looks like a race condition of folding and markdown rendering.

**Comment by mjbvz** [comment]
Please give the next insiders build a test  and let me know if you can still reproduce this. If you can, please share an example  notebook and specific steps I can follow to try reproducing myself

**Comment by matrix303** [comment]
So far have not experienced this issue, looking resolved. Thanks all

**Comment by rzhao271** [comment]
Marking as verified based on https://github.com/microsoft/vscode/issues/140515#issuecomment-1041596824
