### ISSUE TITLE
Wrap links in flame graph info box

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#140528]
Version: 1.64.0-insider
Commit: 419e16a49c7bffc23b8e5f0f9f35ee34167f20e1
Date: 2022-01-07T09:53:34.504Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

Steps to Reproduce:

1. Launch the debug profile and flame graph, click on a process
2. The info box with all the times and links appears. Resize the VS Code window and notice the links in the box spill out past the box instead of wrapping

https://user-images.githubusercontent.com/9721254/149039740-fe7506eb-14e6-4499-aaf3-3ebdf41c5c86.mov

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode-js-profile-visualizer/commit/286cce1ee57ecfea44c94f78a66ef41b343db433
