### ISSUE TITLE
Terminal open new line while typing

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14050]
- VSCode Version: 1.7
- OS Version: OS X 10.11.6

![term](https://cloud.githubusercontent.com/assets/4033249/19551476/2c6a64bc-9660-11e6-9e91-f332541baddf.gif)

Happens erratically. Don't know  how to repro yet.

**Comment by zxdong262** [comment]
I have two ubuntu 16.04.1x64, all latest vscode release, one have this problem, one not have. the only possible diff is that in the one not working properly, I installed some terminal extension and uninstalled. reinstall did not help.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/13554
