### ISSUE TITLE
Change Language prompts on new windows

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#140553]
Version: 1.64.0-insider (Universal)
Commit: 00f1ca47ada2fda8ee1437e17b27af5b4002cecb
Date: 2022-01-11T09:14:08.981Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

On every new window I see the following prompts appear:
![image](https://user-images.githubusercontent.com/12758612/149088208-1c5f4d82-9f85-4589-a9d5-f2e1819fc0be.png)

**Comment by rzhao271** [comment]
Assigning to Sandeep for now judging by file blame on https://github.com/microsoft/vscode/blob/4df57580d323ab2bb9dfaaafb347d24be018a49a/src/vs/workbench/contrib/localizations/browser/localizations.contribution.ts#L62

**Comment by sandy081** [comment]
Assigning to @TylerLeonhardt as he owns localizations support now.
