### ISSUE TITLE
Vertical scroll bar for opened files is not usable

### ISSUE THREAD

**Issue by koniecdev** [microsoft/vscode#140584]
![obraz](https://user-images.githubusercontent.com/89053753/149193145-4101baff-c229-4aeb-8968-dbc6674c7cf8.png)
This scroll bar is like 1px height, clicking on it with high mouse DPI is literally impossible. I just keep dragging my opened tabs.

**Comment by gjsjohnmurray** [comment]
Please try setting `"workbench.editor.titleScrollbarSizing": "large"`
