### ISSUE TITLE
Hot Exit: avoid direct calls to fs.readdir()/fs.readdirSync()

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14055]
I noticed you are calling `fs.readdir()/fs.readdirSync()`. These methods cannot be used standalone, instead please use `pfs.readdir()/pfs.readdirSync()`. These use `extfs` to deal with some exotic corner cases of unicode normalization in paths.

**Comment by Tyriar** [comment]
I believe `fs` is only called in the sync functions (excluding tests) as there are no sync functions on `pfs` (including `pfs.readdirSync`).

**Comment by bpasero** [comment]
@Tyriar yes, you would need to add a sync extfs.readdir(). just copy what we do for the async case and add it 👍
