### ISSUE TITLE
Hot Exit: backup workspace handling should all happen on main side

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14056]
I find it weird that the main side adds a workspace to the backup service but the renderer removes it again on close. I think the window should not deal with this matter and instead let the main side deal with backup workspace management. 

For that I suggest to split the backup service into two pieces: one that deals with backup workspace management only from the main side and then a backup-file-service that deals with all the backup methods that the workbench needs (even fine by me to move this into the workbench services part).

The backup workspace service in `electron-main` listens to lifecycle and window events to manage backup workspaces. Each window object has an associated workspace path so you can use that. It:
- adds a workspace to the backup on open
- removes a workspace from backup on close if there are no backups anymore
- same for exit

**Comment by Tyriar** [comment]
Yes this would be good now as pretty much nothing is shared anymore.

**Comment by Tyriar** [comment]
See https://github.com/Microsoft/vscode/issues/14153, this is causing unwanted restores at start as workspaces are not removed from workspaces.json due to multiple processes accessing the same file.
