### ISSUE TITLE
TypeScript directive `@show-types`

### ISSUE THREAD

**Issue by AkatQuas** [microsoft/vscode#140567]
I come across to this directive `@show-types` for Typescript and wonder if it is necessary to add it.

Should I make some modifications to the file `extensions/typescript-language-features/src/languageFeatures/directiveCommentCompletions.ts` ?

**Comment by mjbvz** [comment]
Can you link to where this is documented?

**Comment by AkatQuas** [comment]
I picked it up when practising type-challenge, [playground](https://www.typescriptlang.org/play?#code/PQKgUABBCM0GwQLQQEoFMAOAbAhgYzUiURNKICMBPCAQQDsAXACwHs7qAxAVwgAoABHIwBmXAJQQAxAFs0AEwCWXaVIZpp2HGsRYFagE44sRIpLMQAilzQBnBgrYmoASQ1Z1aRhAAG6TQQAeAGUAGggOfRZpMIAVFgA+bwgAdyYFPCYIfUxcAghmNAg7fQU6AHMfCKik5L1M7ziktjzS-KZCsoUAN08ihhLynyDvAFgiMagOFn0INAAPHDc0CYgV73WGGxWGSgxC7P95CABeVBz8NACAch29mwgcbIhROgBCK7Crl4+IK5xk2xRNBXeIQYDAWZzPZ4NRyfIsCDkQo3Xa2B5Pf6A2TvNbrJwQUEANQUaGSEDYEAA4noABJccgALggTAYDAwNgZ4M2GQAdAArGw86ZlYCwOBgEDAMDS0AQAD6CsVSsVEAAmiwuDMAMIsOSFGloJ7K40KiCS6W3Qp+XKXIKQtR0OT3YqlMphKoqeYOp19AZuiBxe2eH0u8qg05CSjSsCyk3GgO2BgQLU4GxouPKs1ShQaaZJgDeEAAogBHLhGMJFqFoGEQAC+z0iKiu-EtiAyRnc5VswC49iwNiuYzGlogeFTaNOAG0VlXoQwAqXy1gAtaLtdhCwWORHj8rjv9HvNywQZ9j8eQfEQrPqzDF2WjKvzoEvluDwe9x+z1vT79z2-d3iK8b3ne9lyfQ4NwA-Qv1+I8fyvP9oI-IDryIOcawXJdHzXF9j3fXdPnIQx4JPRDX23R4UOA9Dbywh8V1wy4rj3VjyMvNCAF0xmjWMMxVbh9AKGYgjUdl5X401zVAIhQSCJhHkKSgNRmGwWCwPsHDoDlmVZdlOWAbkmH5QVhVFeBgCEGwAX0WSIGJUkinUzS2B0lk2Q5LkbF5AUhX0EUxWANSNPsVy7IAWWmQotQUrAuzKWwmXc-SvJ80z-IlKUwCAA).  


![image](https://user-images.githubusercontent.com/24731539/150076080-1f7a71fc-8c9a-4048-95e3-0079a2dfeeba.png)

Is it a hidden one?

**Comment by mjbvz** [comment]
Thanks. I think that's specific to the TS playground and not supported by TS out of the box
