### ISSUE TITLE
Debugging: Run to Completion and Restart

### ISSUE THREAD

**Issue by jSadoski** [microsoft/vscode#140580]
Among the Debug actions in the Debug Toolbar (`Pause`/`Continue`, `Step Over`, `Step Into`, `Step Out`, `Restart`, `Stop`), it would be useful to have a button that is similar to `Restart`, but will continue the code to its exit (error or otherwise), then start it again.

This would be very useful when, for example, debugging an E2E test from the Python Test Extension which has a fixture that requires cleanup. Right now, if you were to Restart an test in progress, it would skip the cleanup/teardown steps of that fixture. A `Finish & Restart` button would allow for teardown to occur before restarting the test. Of course, this would make code changes faster to debug in these scenarios.

Optionally, I think it would make sense to allow this feature to skip breakpoints (or a certain level of breakpoints) until the current run exits.

Apologies if this has already been requested. I did some searching, but this isn't an easy concept to specify in search.

**Comment by weinand** [comment]
@connor4312 what do you think?

**Comment by connor4312** [comment]
The test case would be partially covered by https://github.com/microsoft/vscode/issues/134941. Though we don't have any plan/feature right to "disable breakpoints for the current test run and continue". I would probably backlog-candidate this feature request.
