### ISSUE TITLE
Terminal's Maximize Panel Size and Restore Panel Size button shows up/down arrows when the panel is located on a side

### ISSUE THREAD

**Issue by alimxk** [microsoft/vscode#140519]
When the terminal panel is moved to the right or left side, the `Maximize Panel Size / Restore Panel Size` button still shows Up and Down arrows. 

It would be more intuitive for the arrows to point at the direction which the panel expands and collapses to, just like it does when the terminal panel is at the bottom.
![image](https://user-images.githubusercontent.com/5487760/149021554-b7aef790-3a8c-44e7-b8ee-129bc5beb19f.png)

**Comment by sbatten** [comment]
@alimxk thanks for reporting, as discussed the old panel will no  longer be moveable in favor of the moving views to the side panel. in that case this issue is no longer present.
