### ISSUE TITLE
Watermark commands not lined up

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14058]
- VSCode Version: 1.7
- OS Version: OS X 10.11.6

![image](https://cloud.githubusercontent.com/assets/4033249/19552016/db9cdf9e-9662-11e6-8652-d095e76e7663.png)

The up and down arrow are off.

Because the arrow key falls through all provided fonts and get rendered in Arial.

![image](https://cloud.githubusercontent.com/assets/4033249/19552102/42a5dc4a-9663-11e6-880c-e424d8c89697.png)

I suggest adding Lucida Grande to the font-family, for `.shortcut` in macOS's watermark.

**Comment by bgashler1** [comment]
@octref I actually didn't had a problem with this on my Mac for some reason.  Even without the previous commit you added, my glyphs for the symbols like arrows and stuff were being rendered via Lucida Grande, whereas the rest of the glyphs were rendered with San Fransisco.

![screen shot 2016-10-20 at 10 25 54 am](https://cloud.githubusercontent.com/assets/11839736/19570609/993671cc-96af-11e6-95f9-e33e13a83509.png)

![screen shot 2016-10-20 at 10 29 35 am](https://cloud.githubusercontent.com/assets/11839736/19570749/20bf2fc6-96b0-11e6-821c-b14630f5e475.png)

![screen shot 2016-10-20 at 10 28 35 am](https://cloud.githubusercontent.com/assets/11839736/19570707/023720c2-96b0-11e6-9b76-64a4d29e018f.png)

**Comment by bgashler1** [comment]
Closing for now, but just wanted to let you know what was going on on my machine.

**Comment by octref** [comment]
@bgashler1 What's your macOS version?

**Comment by bgashler1** [comment]
macOS 10.12 Sierra
VS Code Insiders c613e1bddce6a544fdf7fcfe2fc0a59626d8195d

**Comment by octref** [comment]
Sierra has SF for `-apple-system`.
I still think we should make the shortcuts rendered in the same font, and Lucida Grande is a safe choice.
