### ISSUE TITLE
Error received from starting extension host (kind: Remote)

### ISSUE THREAD

**Issue by kuntiik** [microsoft/vscode#140566]
![Screenshot from 2022-01-12 14-45-23](https://user-images.githubusercontent.com/43137698/149153576-ce33ccee-699b-4709-8301-3492c73ab1e2.png)
Issue Type: <b>Bug</b>

I am running visual studio code on a linux server . Once my connection went down Iand had to kill the vscode server using SIGTERM.  Now when I run the visual studio code server, the extension host is not starting. I tried to reinstall the whole visual studio server, even removed .vscode_server folder (from the server) and installed it again, but the problem remains the same.  (Visual Studio on my desktop is working as expected)

I will be happy to provide any additional information to resolve this problem.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.11.0-46-generic
Restricted Mode: No
Remote OS version: Linux x64 4.9.0-6-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700G with Radeon Graphics (16 x 1400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|30.66GB (19.32GB free)|
|Process Argv|--unity-launch --crash-reporter-id ba07563b-2834-4b9b-ae78-ee73e83b2285|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: halmos|
|OS|Linux x64 4.9.0-6-amd64|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz (32 x 2400)|
|Memory (System)|125.80GB (19.72GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
material-icon-theme|PKi|4.11.0
prolog|reb|0.0.4
vim|vsc|1.21.10
material-theme|zhu|3.13.10
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.0
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
advanced-new-file|pat|1.2.2

(1 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
@kuntiik Could you please attach all available logs at `View > Output > Log` e.g. `Log (Window)`, `Log (Remote Server)` and `Log (Remote Extension Host)`.
