### ISSUE TITLE
Tab & shift+tab keys appear random in Source Control window, no functionality to go up/down in repo message boxes

### ISSUE THREAD

**Issue by RobbyCBennett** [microsoft/vscode#140513]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: Windows_NT x64 10.0.19042

This functionality is important for pushing changes to multiple repositories. It could be implemented with commands such as "scm.nextMessage" and "scm.previousMessage".

Steps to Reproduce:

1. Open multiple repositories in the same window, preferably at least 3.
2. Open the source control window.
3. Click on a message box.
4. Hit tab.
5. The order appears random. It does not go immediately down, and shift+tab does not go immediately up. It is also inconsistent. Sometimes, the focus goes straight to the first editor tab title.

**Comment by RobbyCBennett** [comment]
I'm testing this again right now and I can't replicate the issue anymore.

**Comment by lszomoru** [comment]
@RobbyCBennett, that you very much for following up on this issue. The latest VS Code Insiders release, contains a recent fix that should address the tab order in the source control view.
