### ISSUE TITLE
Bracket Pair Colorization for YAML is not working properly

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [microsoft/vscode#140505]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows 10 21H2 19044.1415

Steps to Reproduce:

1. Turn on Bracket Pair Colorization
2. Open a YAML file with regular expressions

The colorization will appear for a very short time then be covered by YAML syntax highlight color

Reproduce Video:
https://youtu.be/9T6oyRgLFrw

**Comment by hediet** [comment]
This is by design. Brackets in strings are not highlighted.
