### ISSUE TITLE
Support custom icons for a view

### ISSUE THREAD

**Issue by chairy** [microsoft/vscode#140533]
When I tear out a view (out of many that come from the same extension) and put that in the activity bar, I see multiple identical icons, which makes it very difficult to tell them apart. Example:

If I tear out storage and databases out to their own icons,
![image](https://user-images.githubusercontent.com/4393177/149045715-7c5b8ebc-7373-49d7-a607-1acb10283140.png)

then I get this:
![image](https://user-images.githubusercontent.com/4393177/149045756-3201039a-9c9e-480b-948e-3b22aed7c791.png)

It would be great if VS Code enables extensions to specify a custom icon and tooltip to a view, so that iff it is teared out to exist as a separate container, it can be distinguishable.

**Comment by alexr00** [comment]
VS Code already supports this: https://code.visualstudio.com/api/references/contribution-points#contributes.views (see the `icon` property).

I recommend you open an issue on the extension that contributes that view!
