### ISSUE TITLE
RESET

### ISSUE THREAD

**Issue by bmw628de** [microsoft/vscode#140526]
Issue Type: <b>Bug</b>

Hello World

I want to Use this editor to easy Kombile files.
But like a Stupid mistake i Type some wrong word into a File.
I save and closed VS Studio.
Now i think uninstall this with the 2 Aplications.
Platform IO ; Auto Bild Marlin.

Nothing all old save are in VScode after reinstall

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-build|mar|2.1.36
vscode-language-pack-de|MS-|1.63.3
cpptools|ms-|1.8.0-insiders2
platformio-ide|pla|2.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710:30416614

```

</details>

**Comment by weinand** [comment]
@bmw628de
Bitte beschreibe dein Problem etwas besser in Deutsch. Vielleicht kann ich dann helfen.

**Comment by bmw628de** [comment]
@weinand 
Danke für die schnelle Antwort.
Versuche mich seit tagen an VScode & PlatformIO & Marlin Auto Builder.
Im Prinzip ganz einfach Ich Deinstalliere die APPs Deinstalliere VS code, Lösche PC Tempdaten.
Allso ist der gedanke das ich bei einer "Neu Installation " alles neu installieren muss, endlich mal gewollt.
Aber Vscode hat sofort alle alten daten wieder nach der Neuinstallation ?????
Wie kann man das unterbinden.
Deinstallieren sollte alles Entfernen 
Neu Installieren, heißt doch neu.
Nur platformio zeigt das Programm sofort an & den Marlin Auto Builder auch .
Habe auch einige AppData Dateien gefunden zum löschen aber naja, macht trozdem wieder nur unfug das VScode

**Comment by weinand** [comment]
@bmw628de zu PlatformIO & Marlin Auto Builder kann ich nichts sagen, da das "third party" Extensions sind die ausserhalb unserer Kontrolle bzw. Kenntnis liegen.
Deinstallation der VS Code Applikation bzw. der Extensions ist eigentlich nie nötig, da diese keinerlei Daten "in sich selbst" speichern, also selbst "stateless" sind. Ob allerdings "PlatformIO & Marlin Auto Builder" das auch so handhaben weiss ich nicht.
VS Code merkt sich allerdings bestimmte Daten für einen Workspace (= "Ordner"). Öffnet man diesen Ordner erneut, so wird VS Code die alten Daten wieder finden. Öffnet man hingegen einen neuen Ordner, so werden keine alten Daten gefunden.
Will man die gemerkten Daten ganz löschen, so sollte man auf Windows den Ordner "%APPDATA%\Code\User\workspaceStorage" löschen können (Ich kann das im Moment nicht verifizieren, da ich nur macOS benutze). Hier die Quelle für die Info: https://stackoverflow.com/questions/61056128/clear-workspacestorage-folder-for-visual-studio-code?rq=1
