### ISSUE TITLE
error handling/ notification when shell integration fails

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#140586]
we should discuss what should happen when process start results in an error when there are shellIntegrationArgs provided

- restart the process without those args?
- inform the user and suggest they disable shell integration?
- disable shell integration?
https://github.com/microsoft/vscode/blob/63e4626c5a9c87972a7fd098c047faf5a3d49457/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1279-L1289

**Comment by Tyriar** [comment]
We want to make sure that failures that happen shortly after the process is created are handled, where the process state is `ProcessState.Launching`, which would be a special case for this case:

https://github.com/microsoft/vscode/blob/28497c879865b47de63690a19b372ad8f78dd898/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L2300-L2305

**Comment by Tyriar** [comment]
Let's start with just a message similar to above but that points to the shell integration setting as well. Note that the failure still might not be caused by shell integration.
