### ISSUE TITLE
NodeJs Debug console "require is not defined"

### ISSUE THREAD

**Issue by veedeo** [microsoft/vscode#140569]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: Darwin x64 21.2.0

```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0
```

Steps to Reproduce:

1. Stop on Breakpoint
2. fs = require('fs');
Uncaught ReferenceError: require is not defined

**Comment by connor4312** [comment]
`require` is only available in the current context if it's used inside the file, or sometimes in the current scope. This is a V8 optimization -- identifiers not used in the current scope are often not accessible.
