### ISSUE TITLE
Make `LanguageFeatureRequestDelays` easier to use and adopt in more places

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#140557]
We have adaptive debouncing logic implemented in `LanguageFeatureRequestDelays`. We should make this so that it can be used in more places easier. Identified the following pieces

- [x] a better sliding window average instead of "forever move average"
- [x] in all providers, to save on bandwidth, if a request is canceled, throw canceled instead of returning results
- [x] adopt [`ILanguageFeatureDebounceService#for`](https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/editor/common/services/languageFeatureDebounce.ts#L22) in more providers e.g. 
  - [x] semantic tokens, 
  - [x] folding
  - [x] colors @aeschli 
  - [x] linked editing @aeschli 
  - [x] document links @alexdima 
  - [x] debug inline values @weinand 
  - [x] inline completions @hediet

**Comment by jrieken** [comment]
@alexdima @aeschli Please adopt the `ILanguageFeatureDebounceService` in your "ambient editor" features, like folding ranges and semantic tokens. The service allows you get debounce information (some dynamic average) for a feature registry, see inlay hints [here](https://github.com/microsoft/vscode/blob/ec78252383bb7733ef0bb11bc00132d0161f8444/src/vs/editor/contrib/inlayHints/inlayHintsController.ts#L91)

**Comment by jrieken** [comment]
@aeschli created PR https://github.com/microsoft/vscode/pull/141162 which adopts this for folding

**Comment by jrieken** [comment]
Moving this to February for more cancellation token adoption

**Comment by jrieken** [comment]
fyi @aeschli readded you for more ambient editor features: colors, linked editing

**Comment by hediet** [comment]
I think some documentation of that service wouldn't hurt.
Why does adoption make sense? (After I talked to you I now know why)

**Comment by jrieken** [comment]
Thanks everyone!
