### ISSUE TITLE
Perhaps, as maintainers of VS Code, you could quarantine the plug-ins that are submitted, and reduce the number of incompatibilities between the plug-ins JetBrains Fleet IDE

### ISSUE THREAD

**Issue by AGoh2019** [microsoft/vscode#140530]
Issue Type: <b>Feature Request</b>

I believe JetBrains Fleet IDE is a potential replacement for VS Code, since it makes programming a out of the box experience without having the need to download a variety of language extensions and plug-ins.  As of now, its language support covers what I am currently learning, and also what I will be doing in the future. I am excited about Fleet.  The other IDE that is being developed is Theia. 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by bpasero** [comment]
So what is the feature request here?

**Comment by AGoh2019** [comment]
That you fix users troubles with the Java extension.  The issue also happens with C++.
--- Andrew Goh
 

    On Wednesday, 12 January 2022, 03:25:45 pm SGT, Benjamin Pasero ***@***.***> wrote:  
 
 


So what is the feature request here?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bpasero** [comment]
> That you fix users troubles with the Java extension.  The issue also happens with C++

Maybe it would help if you indicated what troubles you.

**Comment by AGoh2019** [comment]
Hi Benjamin,
Well, I removed all of VS Code, and did a re-installation. And then I added the minimum number of plugins for the languages I am going to code in for the next few years.  And I am more careful if plugins have conflicts or fail to function. I would then remove it. 
So far, I have just installed the Extension Packs for ten languages including HTML5 and CSS3, and few other utilities. And re-run the Java code, and it ran well without crashing.  
Perhaps, as maintainers of VS Code, you could quarantine the plug-ins that are submitted, and reduce the number of incompatibilities between the plug-ins.
Happy Coding,
--- Andrew Goh
 

    On Wednesday, 12 January 2022, 07:50:41 pm SGT, Benjamin Pasero ***@***.***> wrote:  
 
 



That you fix users troubles with the Java extension. The issue also happens with C++


Maybe it would help if you indicated what troubles you.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AGoh2019** [comment]
Hi Triage team,
I have a problem using C++ on VS Code. The compiler tells me 'g++' is not recognized as an internal or external command.  I have MinGW-w64 installed at C:\ root. What configuration file must I edit, and I do try to follow instructions from the plug-ins?

--- Andrew Goh
 

    On Wednesday, 12 January 2022, 08:19:29 pm SGT, VS Code Issue Triage Bot ***@***.***> wrote:  
 
 


This feature request is now a candidate for our backlog. The community has 60 days to upvote the issue. If it receives 20 upvotes we will move it to our backlog. If not, we will close it. To learn more about how we handle feature requests, please see our documentation.

Happy Coding!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
