### ISSUE TITLE
Narrow Debug Console search bar hides other tabs

### ISSUE THREAD

**Issue by kilbouri** [microsoft/vscode#140540]
Issue Type: <b>Bug</b>

1. Move the integrated console viewlets to a vertical layout
2. Make the viewlet narrow

When wide enough:
![image](https://user-images.githubusercontent.com/52428953/149051013-9c3fb17b-febd-4411-8dc0-eecaa94f43f4.png)

Once narrowed:
![image](https://user-images.githubusercontent.com/52428953/149051027-a3e87eca-6ea3-47ab-92a6-0c8f5233eeef.png)

Expected result: Debug Console search bar shrinks/hides itself in order to show other tabs first (like in the first screenshot). The 3 dots "works", but is, at least in my opinion, more annoying than not being able to search in the Debug Console when the viewlet is narrow.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.75GB free)|
|Process Argv|--crash-reporter-id a67afd80-6294-4ad2-b3ee-2184c6ffa8b8|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
The min width is 300, I think that can be narrower. The problems view filter input goes into the body when the view is too narrow, which is sorta cool

https://github.com/microsoft/vscode/blob/0ed1c9c5356d643d47a1ab72ca5ea8ee2381de2a/src/vs/workbench/browser/parts/views/viewPane.ts#L684

<img width="571" alt="image" src="https://user-images.githubusercontent.com/323878/207989120-0b0a331f-11ab-43b8-8b24-b17712b29251.png">

but I won't implement that right now

**Comment by roblourens** [comment]
Actually it was easy to opt into that. I tweaked the min widths and also when the pane is narrow, the filter box will move down into the body

**Comment by kilbouri** [comment]
Holy, I forgot about this issue! 

Love the idea of copying the behaviour of the Problems tab! Excited to try it on Insiders :) Thanks @roblourens !
