### ISSUE TITLE
Hot Exit: how do you deal with the same file opened twice in multiple windows?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14057]
It is possible to open the same file in multiple windows even if those windows have workspaces associated. You can just File > Open and pick any file on disk.

How is this handled today? Isn't it weird to associate a backup to a file that is outside of the workspace to the backup story of a specific workspace?

**Comment by Tyriar** [comment]
It's only as weird as the user opening the file in that workspace in the first place. It would be far more weird imo to open some file that is not a descendant of the workspace directory in some workspace and have it be restored in a new workspace, not the one the user associated it with originally.

**Comment by bpasero** [comment]
@Tyriar right, I was actually more asking what happens if you do that and both are dirty? Are you dealing with this currently because hot exit is just disabled when using multiple windows?

**Comment by Tyriar** [comment]
From my early testing of multiple workspaces it seemed to work just fine. The main work there is to ensure that we're only retaining the workspaces when `app.on('before-quit')` is triggered. I cut off that use case to reduce the scope of the original PR.
