### ISSUE TITLE
Syntax highlighting does not work

### ISSUE THREAD

**Issue by allwell997** [microsoft/vscode#140531]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:   1.63.2 (user setup)
- OS Version:   Windows_NT x64 10.0.19042

Steps to Reproduce:

1.  Syntax highlighting does not work when I use a set_tocken('xxxxxxxx') program line. 
2.  Syntax highlighting is ok before the program line , it dose not work after the line.

**Comment by alexr00** [comment]
@allwell997 what programming language is this occurring with? Can you share a complete snippet with a few lines before and after the issue in a copy/pastable format that I can try to reproduce the issue with? And finally, can you please include a screen shot that shows the issue?
