### ISSUE TITLE
Problem with the VS Code Stop Debugging API 

### ISSUE THREAD

**Issue by SuseeJeeva** [microsoft/vscode#140560]
Hi all,

My objective is to create a VS Code Extension which can ATTACH debugger to a running .NET Console Application

I have a .NET Console Application running parallelly (The Console Application was not attached to the Visual Studio Debugger)

And I have created a VS Code Extension. (Used the default "Hello World" Extension)

In the Extension, I had the below code:

```
// Attach the debugger --- This is working as per the expectation
vscode.debug.startDebugging(undefined, {
		name: ".NET Core Attach",
		type: "coreclr",
		request: "attach", // Please note that the request is ATTACH
		processId: "18876" // Manually configured the Console Application's process ID
}, undefined);


// This is a dummy timer which waits for 5 secs
setTimeout(() => {
	//This piece of code is stopping the debugger BUT ALSO TERMINATE MY CONSOLE APPLICATION which is not expected
	vscode.debug.stopDebugging();

	//I have tried the below code as well, but no luck
	//vscode.debug.stopDebugging(vscode.debug.activeDebugSession);

}, 5000)
```

I am not sure why the vscode.debug.stopDebugging() API terminates the Console Application (Since the Debug Configuration request is ATTACH (but not LAUNCH)

Please help me understand what I am doing wrong here.

Thanks in Advance,
Susee

**Comment by weinand** [comment]
@SuseeJeeva the comment of `debug.stopDebugging` explains the behavior you are seeing:
> Stop the given debug session or stop all debug sessions if session is omitted.

Since you are omitting a debug session argument, all debug sessions are terminated.

If you want to make sure that the correct session gets stopped, I suggest that you you register an event handler `onDidStartDebugSession` and remember the session inside the handler after verifying it.
Relying on `debug.activeDebugSession` is tricky because you never know what debug session is active.

```ts
var myDebugSession: vscode.DebugSession | undefined;
vscode.debug.onDidStartDebugSession(session => {
    if (session.configuration.name === '.NET Core Attach') {
       myDebugSession = session;
    }
});
setTimeout(() => {
   if (myDebugSession) {
      vscode.debug.stopDebugging(myDebugSession);
   }
}, 5000);
```

**Comment by SuseeJeeva** [comment]
@weinand , thank you for your comments.

I am still facing the same issue even if I follow the steps you suggested.

My requirement is, I wanted to achieve the below operation:

- **Attach** the debugger to the existing .NET Console application (This I am able to achieve with the startDebugging API
- **Disconnect** the debugger from the existing .NET Console application. (This is not working as expected because the stopDebugging API is **Stopping** (Terminating) the process. But my requirement is to just **Disconnect** it (Without impacting the actual process's state.

However, If I click on the "Disconnect" Icon manually in the "Extension Development Host", it is properly getting disconnected.

Attaching the image for your reference.

![image](https://user-images.githubusercontent.com/95345113/149154985-dd5c1f0b-4cc7-424d-bd03-a1c84b0b265a.png)

**Comment by weinand** [comment]
@SuseeJeeva I've fixed the issue - please try tomorrow's Insiders.

**Comment by SuseeJeeva** [comment]
@weinand Thank you for the quick support. Sure, I shall try with the Insiders

**Comment by SuseeJeeva** [comment]
@weinand , the issue is resolved in the Insiders version. 

Thanks,
Susee

**Comment by weinand** [comment]
@weinand great, thanks for verifying my fix!
