### ISSUE TITLE
Auto Closing Brackets not working for log file even set it to always

### ISSUE THREAD

**Issue by Zhou-Yucheng** [microsoft/vscode#140506]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: macOS Monterey 12.1 and Windows 10 20H2 (both has this issue)

Steps to Reproduce:

1. open a log file
2. type a opening bracket (
3. expected result ()
4. actually getting ( only
5. bracket is not auto closing

Note that even I set "Auto Closing Brackets" to "always" in settings, this issue still exists.  

I'm not sure it is a bug or feature, but I really need Auto Closing Brackets for log file. Hope it can be fixed, or, is there any way to enable Auto Closing Brackets for a log file?

**Comment by alexdima** [comment]
This is because brackets are defined via language configuration and the log file does not define a language configuration which would configure `()`, `[]` to be brackets. I think we already have a feature request somewhere which asks for such language brackets to be definable via user settings, otherwise in the meantime we might consider defining a language configuration file for log files.

**Comment by Zhou-Yucheng** [comment]
Thank you for your reply. I think defining a configuration for log files is great because log files are very common and most users want this feature enabled by default :)

**Comment by hediet** [comment]
> I think we already have a feature request somewhere which asks for such language brackets to be definable via user settings

You can do that already:
```json
 "[log]": {
        "editor.language.brackets": [
            ["{", "}"]
        ],
    },
```

**Comment by Zhou-Yucheng** [comment]
> > I think we already have a feature request somewhere which asks for such language brackets to be definable via user settings
> 
> You can do that already:
> 
> ```json
>  "[log]": {
>         "editor.language.brackets": [
>             ["{", "}"],
>             ["(", ")"]
>         ],
>     },
> ```

Unfortunately, adding this to my user settings (json) has no effect, the issue still exists. Have you tested it in your vscode?

**Comment by hediet** [comment]
![recording](https://user-images.githubusercontent.com/2931520/151364329-2331176f-aa82-4ee8-92af-2f5a65819d91.gif)

**Comment by Zhou-Yucheng** [comment]
Thank you for your quick reply.  
That's weird, I have added this settings to both user settings and project-specific settings (in .vscode folder), but it still has no effect. All extensions are also disabled.
![ezgif-5-387adfd3ff](https://user-images.githubusercontent.com/36097684/151390898-bdde58da-2d1d-4a17-b2c2-789f44e2d5dd.gif)

**Comment by hediet** [comment]
Can you install VS Code insiders and try it there?

**Comment by Zhou-Yucheng** [comment]
Oh, it works for me! Here is the information.

Version: 1.64.0-insider (Universal)
Commit: 3dda6ea7acb66ea8693032fe9631ccac629da770
Date: 2022-01-27T08:39:44.269Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0

Note that before that I'm using vscode version: 1.63.2.
