### ISSUE TITLE
Docs on how to embed into a site

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#140546]
I have a [new web framework](https://github.com/PurityLib/Purity) where everything, including data, views, helpers, route handlers, literally everything, is stored in the DB, which is just a JSON array, using the vm module and the sucrase lib to compile TypeScript functions. It's intended to be so dynamic that I never have to touch local dev tools again on my machine to edit my site, even if I want to change the admin panel.

So far, it's working well. I am using Monaco editor to edit things DB objects in my primitive admin panel. But I want to take this a step further and use the full VS Code experience in my admin panel. I want something very similar to vscode.dev or github.dev but customized to my framework.

There are no docs anywhere on how to embed VS Code like those two sites have. Is it even possible for us non-Microsoft-employees to do? I know Sandbox.io did this a few years ago, but probably in a different way than vscode.dev does. Is this mechanism officially supported by VS Code, or something we have to manually hack at to accomplish what you did in vscode.dev and github.dev? If it is possible, this issue is to request docs. (In any case, this issue is secondarily also to ask personally how to do this, trying to avoid a SO roundtrip.)

**Comment by leukipp** [comment]
See feature-request #135856.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"triage-needed"
