### ISSUE TITLE
Unable to resolve your shell environment: Unexpected exit code from spawned shell (code 9, signal null)

### ISSUE THREAD

**Issue by dillonkrug** [microsoft/vscode#140591]
Issue Type: <b>Bug</b>

1) add `export NODE_OPTIONS=--openssl-legacy-provider` to .zshrc
2) start VSCode (not via cli)

Removing "--openssl-legacy-provider" solves the problem -- I'm mostly creating this issue so others can google it.

That said, if VSCode's notification had the text from the error, this would have taken seconds to figure out instead of ~45 minutes.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:38:17.605Z)
OS version: Darwin arm64 21.0.1
Restricted Mode: No

**Comment by joaomoreno** [comment]
> if VSCode's notification had the text from the error

Where did you find the text from the error, then?

**Comment by dillonkrug** [comment]
I dug through the source [here](https://github.com/microsoft/vscode/blob/1ab07c536abfb7ac05e57728ab1fb1e1d40190e8/src/vs/platform/environment/node/shellEnv.ts#L136) and figured the command being executed was something like this:
```
$> /bin/zsh -ilc "'/Applications/Visual Studio Code.app/Contents/MacOS/Electron' -p '\"asdf\" + JSON.stringify(process.env) + \"asdf\"'"
```
```
[81020:0115/165803.557060:ERROR:node_bindings.cc(287)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
Warning: 'p' is not in the list of known options, but still passed to Electron/Chromium.
```

I also did this:
```
$> npm i -g electron
...
$> electron -p "whatever"
```
```
electron: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

**Comment by joaomoreno** [comment]
Thanks! I think this is fine to close. I don't think it'll be benefitial to show the stderr on the UI. [We do show it](https://github.com/microsoft/vscode/blob/1ab07c536abfb7ac05e57728ab1fb1e1d40190e8/src/vs/platform/environment/node/shellEnv.ts#L176) in the logs if you were to switch to a trace logging level, which I think is enough for this case.
