### ISSUE TITLE
Notebook smoke tests fail fail during before all/after all hooks

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140575]
I'm skipping the suite as well since all tests are already skipped yet it's still breaking the build sometimes:

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=149637&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=87fb4592-a208-5e50-19ed-a089f1b91f06

**Comment by bpasero** [comment]
What's the plan here?

**Comment by roblourens** [comment]
@rebornix did you say you looked at this last week? I never understood why before/after would fail here

**Comment by roblourens** [comment]
Can merge into https://github.com/microsoft/vscode/issues/139672
