### ISSUE TITLE
Format html code TypeError

### ISSUE THREAD

**Issue by mancereus** [Microsoft/vscode#1405]
code version 0.10.4

When i try to format a html file i get the following error:
TypeError: Cannot read property 'startLineNumber' of null

![image](https://cloud.githubusercontent.com/assets/174948/11864429/add40410-a49c-11e5-813c-9115dc2c5119.png)

**Comment by edotassi** [comment]
Duplicate of #1321

**Comment by egamma** [comment]
@edotassi thanks, closing as a duplicate of #1321
