### ISSUE TITLE
Breakpoint doesn't work well with typescript + mocha

### ISSUE THREAD

**Issue by leinlee** [Microsoft/vscode#14069]
I'm working on a typescript project, using mocha as unit-test.
The debug mode worked fine on vscode v1.5.3.
After upgrading to 1.6.0 and later versions, it suspends at the first breakpoint, then auto-resume after like 1 sec, and skips all other breakpoints till done.
Another strange thing is "mocha --debug-brk" service with be terminated after that.

It works again after downgrade to v1.5.3.
- VSCode Version: 1.6.0
- OS Version: Windows 10

Steps to Reproduce:
1. Start a typescript project.
2. Write some test case using mocha.
3. Setup launch config with sourceMaps=true.
4. Run mocha --debug-brk.
5. Add some breakpoints in testcase.
6. Debug run.

**Comment by leinlee** [comment]
sure
[launch.zip](https://github.com/Microsoft/vscode/files/543842/launch.zip)

**Comment by leinlee** [comment]
You're right. I just found it's not necessary to run "mocha --debug-brk" alone.
However, it doesn't fix the issue. Without a standalone mocha debug service, it won't even suspend for any second. It just skips all breakpoints.
Here is a full case.

[mochaDebugTest.zip](https://github.com/Microsoft/vscode/files/545571/mochaDebugTest.zip)

Steps:
1. unpack
2. npm install
3. typings install
4. tsc --sourcemap
5. [in vscode] add a breakpoint in sample.test.ts
6. [in vscode] debug run
PS: It's fine on v 1.5.3

**Comment by roblourens** [comment]
Yeah the 'port' parameter is the problem. If you specify that, it assumes that you provided the `--debug-brk` parameter elsewhere.
