### ISSUE TITLE
Commit from source control in vscode doesn't verify commits

### ISSUE THREAD

**Issue by m-naeem66622** [microsoft/vscode#140699]
- VS Code Version: 1.63.2 (user setup)
- OS Version: 21H1 (OS Build 19043.1415)

Commit from source control given in vscode doesn't verify my commits Can anybody help me. How it can be verified
Here is the pic of the issue
![Untitled](https://user-images.githubusercontent.com/89637035/149502101-431507d0-1e16-4a9f-87ca-5aa5863d248c.png)

**Comment by lszomoru** [comment]
@m-naeem66622, does verification work when you commit from the terminal?
Could you please share the documentation that you have follow in order to set up commit signing on your machine?
