### ISSUE TITLE
`Launch VSCode` target launches multiple window

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14060]
- VSCode Version: master
- OS Version: OS X 10.11.6

I was rebasing my PR against master, but this happens:

When I do `npm run watch` + `F5`

- First time, one window open for project A.
- Cmd+o, open another project B that's not opened in any windows
- Close all windows and restart the instance again, VSCode still launches two windows, one for A and one for B.

Now I've used my build to open a few more projects...And I have 4 windows open....
Here is a gif of me adding yet another one

![multiple](https://cloud.githubusercontent.com/assets/4033249/19552829/66d6374c-9666-11e6-8085-7ef331068555.gif)

I guess it's related to hot exit.

/cc @bpasero @Tyriar

**Comment by bpasero** [comment]
@octref if this does not reproduce in stable, it is likely the hot-exit work, so I move this to @Tyriar.

**Comment by octref** [comment]
This isn't reproducible when I was rebasing 2 days ago against master. So it's likely hot-exit.

**Comment by Tyriar** [comment]
I think the fix here is to not attempt backups at all while debugging extensions.
