### ISSUE TITLE
CompletionItems are  not getting listed as per sortText property in completionItem

### ISSUE THREAD

**Issue by ajaygera** [microsoft/vscode#140623]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.51.1
- OS Version: Windows 10 Pro

Steps to Reproduce:
On pressing space key, I am returning completion items but completion items are not getting listed per sortText priority.
I have specified 10 different priority order by setting sortText to value as shown below
1)space
2) !
3)  "
4)  #
5) $
6) % 
7) &
8) 0
9) 1
10) 2

I want to display items with sortText 'space' on top , followed by items with sortText '!' , followed by " so on
1) I have observed that upto 7 different priority can be displayed but this is not very consistent ? Is their any such limitation or it depends upon completion item kind as well.
In the completion list, I have items with different kind like struct , keyword , method , class , enum.
2) I also observed another issue that completion item with label '%' gets listed somewhere in between completion items with sort text of 'space'. I did not set sort text to completion item with label '%' i.e. it is null and kind is keyword. so this should get listed after above 10 priority items are displayed

Thanks & Regards,
Ajay

**Comment by jrieken** [comment]
Please provide more clarifying information and a full sample but note that sortText is only effective when no prefix is selected (as defined by the range property). See here: https://github.com/microsoft/vscode/blob/f5ad06212dad13272d0de2451b803b30bb5ef831/src/vscode-dts/vscode.d.ts#L4140
