### ISSUE TITLE
Allow extensions to customize and/or opt-out of the built-in issue reporter

### ISSUE THREAD

**Issue by jblievremont** [microsoft/vscode#140630]
Everything is pretty much in the title: it would be great for extensions to either tell the issue reporter where/how to post a report, or to disable error reporting altogether.

Rationale behind this is:
* Not all extensions have their source code hosted on GitHub
* Extensions that have their source code on GitHub might not have "Issues" enabled on their repo, nor want end-users to open issues there
* Extensions might have their own system to gather user feedback (e.g: JIRA, Discourse, Slack...)

For instance, on the SonarLint extension, we got reports on our community forum from users who tried to use the error reporter, and who received a 404 because "Issues" are disabled on our repo.

Suggested implementations could be:
* Rely on the `qna` or `bugs` field from the extension manifest to redirect users
* Define a new field in the extension manifest, and maybe an API for the extension to register a custom error reporter

**Comment by TylerLeonhardt** [comment]
Reasonable request, although you _could_ have a GitHub repo specifically for issues from the issue reporter and than handle them accordingly (GitHub Actions could then push them to whatever issue tracker you use)

So I don't think anyone is blocked on this at the moment... but I'll put it on backlog-candidate to gauge interest.
