### ISSUE TITLE
initializing JS/TS language hangs

### ISSUE THREAD

**Issue by rustamsmax** [microsoft/vscode#140638]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I don't remember what was my latest changes

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin arm64 21.0.1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 7, 5|
|Memory (System)|16.00GB (1.16GB free)|
|Process Argv|--crash-reporter-id 40a8f3f0-9f32-4a9a-86b3-29d5dd04d460|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-typescript-next|ms-|4.6.20220112

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30422343
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30421291
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710:30416614
vsccppwtstudy:30421978

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by rustamsmax** [comment]
![image](https://user-images.githubusercontent.com/36570577/149414620-28f7948f-bfa7-4981-b3cb-5cd2624859ea.png)

Version: 1.64.0-insider
Commit: 753319a08f8e74700b1dba3a29bf0a6af7c2953f
Date: 2022-01-12T05:27:22.016Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.0.1

Yes still exists

**Comment by rustamsmax** [comment]
https://gist.github.com/rustamsmax/f807e0f81e9ce59145383bdfd009e24f

this is my package.json content

**Comment by rustamsmax** [comment]
and tsconfig.json
https://gist.github.com/rustamsmax/c3917ac6c0423f0c045226621ce06c82

**Comment by rustamsmax** [comment]
I found the issue. I've been testing hls format audios (ts files) locally. The files were in project folder. I moved them to outer folder and issue was resolved

![telegram-cloud-photo-size-2-5408917878431922342-x](https://user-images.githubusercontent.com/36570577/149520566-97f71a15-89f2-4fcb-a315-099ebdbe31e8.jpg)

**Comment by mjbvz** [comment]
Thanks for investigating this! 

This is a know issue and currently tracked upstream by https://github.com/microsoft/TypeScript/issues/21136
