### ISSUE TITLE
VS Code exits without disposing all pushed items to subscription

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode#140697]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows 10

We are tracking a Windows-specific issue (https://github.com/REditorSupport/vscode-R/pull/941) where we can't `taskkill` the spawned processes on vscode exits.

Basically, we define the following:

```typescript

/**
 * As Disposable.
 *
 * Create a dispose method for any given object, and push it to the
 * extension subscriptions array
 *
 * @param {T} toDispose - the object to add dispose to
 * @param {Function} disposeFunction - the method called when the object is disposed
 * @returns returned object is considered types T and vscode.Disposable
 */
export function asDisposable<T>(toDispose: T, disposeFunction: (...args: unknown[]) => unknown): T & vscode.Disposable {
    type disposeType = T & vscode.Disposable;
    (toDispose as disposeType).dispose = () => disposeFunction();
    extensionContext.subscriptions.push(toDispose as disposeType);
    return toDispose as disposeType;
}

export type DisposableProcess = cp.ChildProcessWithoutNullStreams & vscode.Disposable;
export function exec(command: string, args?: ReadonlyArray<string>, options?: cp.CommonOptions, onDisposed?: () => unknown): DisposableProcess {
    const logger = fs.createWriteStream(path.join(homeExtDir(), 'diagnostics.log'), { flags: 'a' });
    const proc = cp.spawn(command, args, options);
    logger.write(`Process [${command}] (${proc.pid}) spawned\n`);
    let running = true;
    const exitHandler = () => {
        running = false;
        logger.write(`Process [${command}] (${proc.pid}) exited\n`);
    };
    proc.on('exit', exitHandler);
    proc.on('error', exitHandler);
    const disposable = asDisposable(proc, () => {
        logger.write(`Process [${command}] (${proc.pid}) disposing, connected: ${String(proc.connected)}, exitCode: ${proc.exitCode}, signalCode: ${proc.signalCode}, killed: ${String(proc.killed)}, running: ${String(running)}\n`);
        if (running) {
            logger.write(`Process [${command}] (${proc.pid}) terminating\n`);
            if (process.platform === 'win32') {
                const taskkill = cp.spawn('taskkill', ['/pid', proc.pid.toString(), '/f', '/t']);
                taskkill.stdout.on('data', (data: Buffer) => {
                    logger.write(data.toString());
                });
                taskkill.stderr.on('data', (data: Buffer) => {
                    logger.write(data.toString());
                });
            } else {
                proc.kill('SIGKILL');
            }
        }
        logger.write(`Process [${command}] (${proc.pid}) disposed, connected: ${String(proc.connected)}, exitCode: ${proc.exitCode}, signalCode: ${proc.signalCode}, killed: ${String(proc.killed)}, running: ${String(running)}\n`);
        logger.end();
        if (onDisposed) {
            onDisposed();
        }
    });
    return disposable;
}
```

The `exec` method is a bit messy as we put some logging code into it to see what happens on dispose, especially when vscode exits. However, some user observes that the spawned processes are left orphan, while my test goes like most of the time the spawned processes could be terminated in an azure Windows 10 environment, but the log looks quite weird.

It looks like my `dispose` never completes.

```
Process [C:\Program Files\R\R-4.1.2\bin\R.exe] (10340) spawned
Process [C:\Program Files\R\R-4.1.2\bin\R.exe] (11000) spawned
Process [C:\Program Files\R\R-4.1.2\bin\R.exe] (10340) disposing, connected: false, exitCode: null, signalCode: null, killed: false, running: true
Process [C:\Program Files\R\R-4.1.2\bin\R.exe] (11000) disposing, connected: false, exitCode: null, signalCode: null, killed: false, running: true
```

while @albertosantini's test looks like `dispose` is called on some spawned processes but not all of them, but `taskkill` does not seem to work at all. After vscode exits, they become orphan processes.

```
Process [C:\woot\opt\r\bin\R.exe] (10760) spawned
Process [C:\woot\opt\r\bin\R.exe] (15664) spawned
Process [C:\woot\opt\r\bin\R.exe] (10760) disposing, connected: false, exitCode: null, signalCode: null, killed: false, running: true
Process [C:\woot\opt\r\bin\R.exe] (15664) disposing, connected: false, exitCode: null, signalCode: null, killed: false, running: true
Process [C:\woot\opt\r\bin\R.exe] (15664) terminating
Process [C:\woot\opt\r\bin\R.exe] (15664) disposed, connected: false, exitCode: null, signalCode: null, killed: false, running: true
```

We don't use `proc.kill()` because it does not seem to work. Any clue on what's happening in the `dispose()` mechanism?

**Comment by albertosantini** [comment]
Resolved. 
Eventually in our use case (taskkill) the fix was using `spawnSync` or, generally speaking, using an external library with `await`.

I learned you need to use a **sync** approach in the disposable subscriptions; otherwise, when vscode quits or the extension is deactivated, the subsciptions have no time to complete the task.

I was wondering if vscode compells some pattern for the subscriptions or in the docs there is some note, because it is a quite common approach executing async disposable functions (removing temporary files, killing processes, etc.). I am sure vscode team noticed it and they gave an answer in terms of pattern, policy, note in the doc or something else.

**Comment by albertosantini** [comment]
It seems there is a sort of sync-aware.

Not the same context of this issue, but it gives the idea how Disposables subscriptions are tricky and the solution is adding an `await`.

- https://github.com/microsoft/vscode/issues/127250
- https://github.com/microsoft/vscode/issues/92868

**Comment by alexdima** [comment]
You're right. Disposables are synchronous, we do not support that a disposable returns a `Promise`. Despite the fact that [the return type is `any`](https://github.com/microsoft/vscode/blob/432098a88dcc861554f6d2d19632ef023817e92c/src/vscode-dts/vscode.d.ts#L6274-L6278), we actually do not await a disposable that returns a `Promise`. (cc @jrieken , do you think we should better document this?)

So `ctx.subscriptions` cannot be used as a mechanism to register a async disposables.

However, we do support that the `deactivate` function that the extension module exports can return a `Promise`. So it is possible to avoid using `spawnSync` as long as the process you spawn is wrapped into a `Promise` and then this promise is returned from `deactivate`.

In pseudo-code:
```
exports.deactivate = function() {
  return new Promise((resolve, reject) => {
    const child = cp.spawn(/*...*/);
    child.on('exit', resolve);
  });
};
```

**Comment by albertosantini** [comment]
@alexdima Thanks for the details. That is the way I was not able to find.
@renkun-ken You may close the issue, if you agree. Thanks for highlighting this point.

**Comment by renkun-ken** [comment]
@alexdima Thanks for the details! It would be nice if this could be documented somewhere.

**Comment by jrieken** [comment]
Pushed a doc-change to `vscode.d.ts` that points out that async-dispose isn't awaited
