### ISSUE TITLE
`setTimeout().unref()` is not a function

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#140624]
Seeing in shared process:

```
bootstrap-window.js:253 TypeError: setTimeout(...).unref is not a function
    at IncomingMessage.<anonymous> (Sender.ts:138)
    at IncomingMessage.emit (events.js:327)
    at endReadableNT (internal/streams/readable.js:1327)
    at processTicksAndRejections (internal/process/task_queues.js:80)
```

Originates from `Sender.ts` of app insights it seems.

![image](https://user-images.githubusercontent.com/900690/149332827-891bd1c3-7aeb-4aae-b535-53723e860100.png)

https://ticino.blob.core.windows.net/sourcemaps/753319a08f8e74700b1dba3a29bf0a6af7c2953f/node_modules/applicationinsights/Library/Sender.ts

**Comment by lramos15** [comment]
Hmmm, `unref` has been around in node for awhile. Are you doing anything special? It seems like a lot of the errors with unref happen when you accidentally execute in a browser based context rather than node.

**Comment by bpasero** [comment]
Nothing special afaik, just show the shared process window via F1:

![image](https://user-images.githubusercontent.com/900690/149613283-df3333c3-6565-41e5-9afb-5859dd70f69c.png)

Keep in mind that the shared process is a browser window, so `setTimeout` does not return a function but a number!

![image](https://user-images.githubusercontent.com/900690/149613314-2394a924-4204-4791-a6b5-f49e6c25aba9.png)

**Comment by bpasero** [comment]
I still see this in exploration builds but not insiders 🤷

**Comment by lramos15** [comment]
Is there something special about exploration builds? I just added a try catch

**Comment by bpasero** [comment]
@lramos15 yeah maybe how uncaught exceptions are handled and reported. This one you cannot really catch as it happens from an event handler:

![image](https://user-images.githubusercontent.com/900690/151115091-60a6f129-58e1-4f2d-a76d-a9f1947f7f8a.png)

**Comment by lramos15** [comment]
Yeah like I said not sure what we should do here as one module expects node and another module expects window and the shared process is a bit in between

**Comment by bpasero** [comment]
This is still happening.

Btw found https://github.com/microsoft/ApplicationInsights-node.js/issues/367. Maybe we need to contribute a PR.

**Comment by lramos15** [comment]
Is the issue saying we're trying to use the node SDK in the electron renderer?

**Comment by bpasero** [comment]
Yeah in the renderer we get the `setTimeout` variant from `DOM` and not `node.js`. I was actually looking into whether we could simply shim the `unref()` method, but it didn't seem to easy, unless we would overwrite the entire `setTimeout` method for everyone.

**Comment by lramos15** [comment]
Maybe we should be using the web SDK in the renderer then? We use the web telemetry reporter in the `/browser/` telemetryService so I'm surprised that we're using the node one in the renderer.

**Comment by bpasero** [comment]
Yeah that sounds reasonable. Though the fact that the shared process is a browser window is a bit of a debt issue, eventually we probably want to go away from running it as hidden window and use a pure node.js process once https://github.com/microsoft/vscode/issues/131798 landed.

Given that, maybe we should just ignore the issue for now until we get to a real node.js process.

**Comment by lramos15** [comment]
Going to reopen this since it hasn't really been fixed and Daniel is seeing the issue as well. We are working on switching modules so maybe that will help but still want to keep this as a tracking issue.

**Comment by lramos15** [comment]
Closing this as we have switched modules
