### ISSUE TITLE
Terminal has weird letter spacing after updating editor font style

### ISSUE THREAD

**Issue by lewallen** [microsoft/vscode#140678]
Does this issue occur when all extensions are disabled?: Yes (it derives from settings.json).

- VS Code Version: 1.63.2
- OS Version: macOS 12.1

Steps to Reproduce:

1. Change editor font via the editor.fontFamily setting to a non-monospaced font.
2. Use the terminal.

I'm not sure whether this is a bug or the intended behavior, but I wanted to post something in case it can save anyone else the day I lost trying to diagnose the problem.

What seems to be happening is that the terminal is inheriting its font from the editor.fontFamily setting. The issue can easily be solved without resetting editor.fontFamily, simply by setting terminal.integrated.fontFamily explicitly to 'monospace' (or another desired font family).

There is actually a warning message about the terminal which comes up when changing editor.fontFamily, however if a user doesn't read the message carefully and has the terminal closed at the time they change the editor font, then when they use the terminal a while later they may have a hard time tracking down the cause of the strange spacing. That's what happened to me, anyway.

I find it unintuitive that editor.fontFamily should effect the terminal at all, but again, that may be the intended behavior. Also, there are several past issues reporting weird spacing in the terminal and I'm not sure whether those have the same cause; some were solved simply by resizing the terminal, which isn't the case here.

**Comment by meganrogge** [comment]
Hi and thanks for the issue. This is the expected behavior and is also indicated in the `terminal.fontFamily` setting description.

![Screen Shot 2022-01-18 at 9 31 25 AM](https://user-images.githubusercontent.com/29464607/149967537-fa7fd211-37f0-441f-ab3d-b86a97e5b12b.png)
