### ISSUE TITLE
MarkdownString Broken After Or In HTML

### ISSUE THREAD

**Issue by rbrisita** [microsoft/vscode#140686]
Issue Type: <b>Bug</b>

## Steps to Reproduce:

1. Create a multiline Markdown string with a `<br/>` in the middle.
1. Set to a MarkdownString in the constructor or value property.
1. Any Markdown below or in an HTML tag does not render.

## Example
```
const hoverUI = `
# One
## Two
### Three
<br/>
#### Four
##### Five
###### Six
`;
const md = new MarkdownString(ui, true);
md.isTrusted = true;
md.supportHtml = true;
statusBar.tooltip = md;

```
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:18:59.299Z)
OS version: Linux arm64 5.15.7-1-MANJARO-ARM
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|unknown (6 x 1416)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|3.77GB (0.09GB free)|
|Process Argv|. --crash-reporter-id 2a85f066-a8e2-4971-b1ff-37959f57a0f0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
vscode-drawio|hed|1.6.4
vsliveshare|ms-|1.0.5242

</details>

**Comment by mjbvz** [comment]
I don't think that that markdown will do what you want. It seems like `<br/>` causes everything after it to be treated as part of an html tag:

https://spec.commonmark.org/dingus/?text=%23%20One%0A%23%23%20Two%0A%23%23%23%20Three%0A%3Cbr%2F%3E%0A%23%23%23%23%20Four%0A%23%23%23%23%23%20Five%0A%23%23%23%23%23%23%20Six

In our case, I think we then strip this out but I don't think this is worth looking into since even if we fixed our rendering, it still would not render as expected

**Comment by rbrisita** [comment]
Thanks for the link, it gives more insight into AST output. It seems it has to do with a newline character. To be clear, it is any HTML tag; if there isn't a newline after it, it will not render Markdown correctly. Meaning this:

```
# 1
<hr/ >

## 2
```

Renders differently than the first example. In AST the two different outputs:

```
  <heading level="1">
    <text>One</text>
  </heading>
  <html_block>&lt;hr/&gt;</html_block>
  <heading level="2">
    <text>Two</text>
  </heading>
```

vs

```
  <heading level="1">
    <text>One</text>
  </heading>
  <html_block>&lt;hr/&gt;
## Two</html_block>
```
