### ISSUE TITLE
fs.readFile actually returns a Buffer, not a Uint8Array

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140632]
Maybe this is by design/can't change, but fs.readFile doesn't actually return a Uint8Array object:

https://github.com/microsoft/vscode/blob/f7ed5376eb0f72cb7a5c25d476dd6311000c265b/src/vscode-dts/vscode.d.ts#L7567-L7573

This is causing the lib I'm using to decode the Uint8Array fail because it's not the expected type.

![image](https://user-images.githubusercontent.com/2193314/149349830-ae1990f1-befa-497f-b962-d3a96ab5a5d7.png)
![image](https://user-images.githubusercontent.com/2193314/149349842-a93597ea-2720-44d5-9152-43bf6d659c3c.png)

The specific reason it's failing is because I use readFile().buffer to get the Uint8Array's backing buffer, but that ends up transforming the data:

![image](https://user-images.githubusercontent.com/2193314/149349928-b2fe66fc-9bc4-4257-bfe6-b37d6d1a5702.png)

**Comment by jrieken** [comment]
> because I use readFile().buffer to get the Uint8Array's backing buffer, but that ends up transforming the data:

I don't really know what that means. Anyways, the `Buffer` type is a subclass of `Unit8Array` (see https://nodejs.org/api/buffer.html#buffers-and-typedarrays) and therefore shouldn't cause issues, right? 

Also looping in Alex because what readFile is returning is VSBuffer.buffer (which is adaptive the respective platforms)

**Comment by Tyriar** [comment]
I investigated this more and it is actually an error due to me not knowing about [`byteOffset`](https://nodejs.org/api/buffer.html#bufbuffer) and byteLength.

The `buffer.buffer` points at a sub-portion of the backing ArrayBuffer because `byteOffset` is 22:

![image](https://user-images.githubusercontent.com/2193314/149525096-acdf4b88-ae73-4723-b33a-e337281b6ee8.png)
![image](https://user-images.githubusercontent.com/2193314/149525151-f0a0743b-bc0c-47f1-85f4-2bec1ec6ee28.png)

So I need to add support for this to my library. Not sure what the header of the backing ArrayBuffer is but it's probably to avoid recreating a new ArrayBuffer.

Sorry about the hassle, very good to know though! Will share in standup.

**Comment by Tyriar** [comment]
Proper fix on my end for anyone else who hits this:

```ts
new DataView(buffer.buffer, buffer.byteOffset, buffer.byteLength)
```

**Comment by jrieken** [comment]
Yeah, I also had to learn about `byteOffset` and `byteLength` and hard way

**Comment by alexdima** [comment]
Also be aware that nodejs uses a `Buffer` pool which means that not all buffers are transferable --> https://github.com/microsoft/vscode/pull/139145#issuecomment-994860119

**Comment by jrieken** [comment]
Talking about mean things: the `slice` functions behave different, so make sure to use `subarray`
