### ISSUE TITLE
Turn on auto-save problem feedback

### ISSUE THREAD

**Issue by bmqy** [microsoft/vscode#140679]
Issue Type: <b>Bug</b>

After the auto-save function is enabled, the save file event of ctrl+s will not be triggered when saving a file, so that extensions such as eslint cannot automatically format the code

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (7.94GB free)|
|Process Argv|--crash-reporter-id 3a8eea86-2195-4ed9-945e-46806ed52246|
|Screen Reader|no|
|VM|0%|
</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30416617
vsccppwtstudy:30421978

```

</details>

**Comment by bpasero** [comment]
I cannot reproduce, for me a explicit `Cmd+S` always formts.
