### ISSUE TITLE
I CANT SYC MY VSCODE WITH GITHUB

### ISSUE THREAD

**Issue by CSituma** [microsoft/vscode#140696]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by CSituma** [comment]
![github isue](https://user-images.githubusercontent.com/35976894/149494908-0fdd6103-8234-4d57-86d4-f1727d83f32c.PNG)

**Comment by lszomoru** [comment]
@TylerLeonhardt, this looks like an issue with the GitHub authentication.

**Comment by CSituma** [comment]
It was An authentication issue....

How i fixed it:
Connected using the terminal- Set Global Username ,email and Set Password to Personal Access Token

**Comment by CSituma** [comment]
It was An authentication issue....

How i fixed it:
Connected using the terminal- Set Global Username ,email and Set Password to Personal Access Token
