### ISSUE TITLE
Enable path IntelliSense in markdown 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#140602]
Tracks enabling simple path intellisense inside of markdown files, specifically when completing links

### Goals
- Support path suggestions to other files
- Support suggestions to header sections in the current file
- Support completions for `[](path)` style links as well as reference links: `[][ref]`
- Support relative links (`path/to/file` or `./path/to/file`) and absolute links (`/path/to/file`)
- Setting to easily disable this feature

### Out of scope
- Suggestions for shorthand reference links such as `[bla]` (could be added in the future)
- Path intellisense for html inside markdown 
- `file://` uris

**Comment by ArturoDent** [comment]
Is this in the Insiders Build yet?  I don't see the setting.

Version: 1.64.0-insider (user setup)
Commit: 753319a08f8e74700b1dba3a29bf0a6af7c2953f
Date: 2022-01-12T05:16:42.486Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by karlhorky** [comment]
@mjbvz this is amazing, thanks!! 🙌

What would be necessary to enable this also for MDX files? This is something that a few people have been asking for, for a while now:

- https://github.com/silvenon/vscode-mdx/issues/8
- https://github.com/mdx-js/vscode-mdx/issues/165

**Comment by karlhorky** [comment]
Oh, one other thing: now that there's IntelliSense in Markdown files, is it possible to also have this in attributes for HTML in those files?

Eg. in the `src` here?

<img width="342" alt="Screen Shot 2022-02-04 at 19 36 24" src="https://user-images.githubusercontent.com/1935696/152584516-719b4093-845b-43cb-a1e7-ea68ad57eba2.png">

Would also open another issue for this, if it's a valid request.
