### ISSUE TITLE
Design Systems Patterns

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#140601]
## Summary

This design exploration aims to look at how we can make the product more consistent from a design system perspective. Parts of the products use certain patterns while others don't, so we will explore what this could look like. The list below will grow and evolve as we discover more patterns:

- [x] Overflow
- [x] View and action management
- [x] Contextual windows (notification center, feedback)
- [x] Drag and drop
- [x] Filtering

### Overflow and view management

Below is video walkthrough of the current proposal for how we could apply our overflow and view management patterns to other areas like toolbar actions, status bar items, etc.

#### Related issues

- #46403
- #35744
- #9285

[<img width="740" alt="image" src="https://user-images.githubusercontent.com/35271042/149241062-e5c36f54-ba8e-46c6-a27f-e07ed7bd5090.png">](https://www.loom.com/share/0db793c008e54429a0fb9e5582caaea4)

https://user-images.githubusercontent.com/35271042/149242157-a3c023fa-ffc3-4e9d-a9f6-cfdd77a23adc.mp4

### Contextual windows

In the status bar, we utilize contextual windows to display content close to the user's click target. Using the same spirit, this concept looks at using a "mini quick pick" for items that derive from the status bar. Because the quick pick can filter out results based on the input field, we inverted the orientation to keep the position of the input consistent.

https://user-images.githubusercontent.com/35271042/153288462-8365654b-daae-4110-a22d-62e3bc4e1258.mp4

### Drag and drop

We currently allow users to move around views in the Activity Bar, Sidebars, and Panels. This explorer aims to see how we can extend this to the editor area and allow you to move files that are inside of views (Problems, References, Diff, etc.) and other views into the editor area. We also looked at how we can extend the drag and drop functionality for inserting paths/links in markdown/typescript files.

### Related issues

- #5240
- #133018
- #111260

[<img width="903" alt="CleanShot 2022-03-08 at 10 27 43@2x" src="https://user-images.githubusercontent.com/35271042/157302207-c323ce71-6a95-4ef1-8eaf-666111991b6c.png">
](https://www.loom.com/share/a7cdac3520e945adad7faf87a812ea10)

### Filtering

We have a, hard to discover, feature in tree views that allow the user to [filter the list view on type](https://code.visualstudio.com/updates/v1_31#_new-tree-widget). This exploration looks at making that a little more discoverable by adding an entry point in the list header. This is also looks at consolidating the search filters & queries from the problems/settings/extensions views for a consistent experience.

#### Related issues

- #70646

[<img width="1478" alt="CleanShot 2022-03-17 at 15 31 13@2x" src="https://user-images.githubusercontent.com/35271042/158905077-cce70bf8-5d0f-4dd6-b59e-df532bbeb1f2.png">
](https://www.loom.com/share/2bf76214202345ae979b06c69e45302a)

**Comment by heartacker** [comment]
:question

**Comment by misolori** [comment]
@heartacker what's your question?

**Comment by cognominal** [comment]
disclaimer: I am new to vscode internal
