### ISSUE TITLE
Can't close file in editor

### ISSUE THREAD

**Issue by fabiocapsouza** [microsoft/vscode#140667]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Linux x64 5.8.0-7642-generic

Problem:

I was editing a Jupyter notebook in VS Code and I moved the file to another folder. After I closed and reopened the VSCode window, the editor for that file became stuck in a state where the editor tab fails to load (`The editor could not be opened due to an unexpected error. Try again`) and also fails to close. When I try to close it, an error pop up appears with the message "`Unable to open 'my_notebook.ipynb': No file system provider found for resource vscode-notebook:/path/to/my_notebook.ipynb'.`".

I am stuck with this tab open for 2 months now.

Is there a way to force it to close?

Steps to Reproduce:

I can't reproduce this behaviour with other files.

**Comment by greazer** [comment]
Looks like a dupe of #138700? Perhaps this is the repro we need?

**Comment by fabiocapsouza** [comment]
By the way, I managed to close the notebook editor by accident a week after posting here. With the editor split in two columns, I dragged it from one column to the other and it disappeared. I updated vscode a few days prior to this event, and the bug was still there.

**Comment by rebornix** [comment]
I didn't reproduce this issue, I wonder if it's related to how the underlining working copy service didn't handle this properly. Will keep this open and see if anyone else ran into the same.

**Comment by zcernigoj** [comment]
I have the same issue. It reopens if I select `Don't save`. It also reopens if I click `Save` and then do a `git restore <file_name>` to revert the changes.

VS Code's `about` page:
```
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:29.527Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-30-generic snap
```
(Ubuntu 20.04 LTS)

**Comment by rebornix** [comment]
> I have the same issue. It reopens if I select Don't save when closing the file. It also reopens if I click Save and then do a git restore <file_name> to revert the changes in the terminal inside of VS Code / with the source control part of the VS Code GUI.

Looks like related to file watcher.

**Comment by bpasero** [comment]
🤷 , needs detailed step by step how to reproduce, otherwise I cannot help.

**Comment by ndgayan** [comment]
Same issue. Can't close the IPYNB file. It is always in the editor. When I try to save it, I'm getting the below message. 

![Tmp1](https://user-images.githubusercontent.com/1891059/161796508-d34cc816-fc33-4624-8973-0b933adac17a.jpg)

**Comment by bpasero** [comment]
🤷

**Comment by bpasero** [comment]
Sounds like https://github.com/microsoft/vscode/issues/146940. I would need exact steps for how to reproduce, preferably with a fresh `--user-data-dir` and fresh `--extensions-dir` to start from zero. These steps should include which extension to install and which file to create and then possibly delete?

**Comment by zcernigoj** [comment]
> Thanks for reporting this issue! Unfortunately, it's hard for us to understand what issue you're seeing. Please help us out by providing a screen recording showing exactly what isn't working as expected. While we can work with most standard formats, `.gif` files are preferred as they are displayed inline on GitHub. You may find https://gifcap.dev helpful as a browser-based gif recording tool.
> 
> If the issue depends on keyboard input, you can help us by enabling screencast mode for the recording (`Developer: Toggle Screencast Mode` in the command palette).
> 
> Happy coding!

Thanks for all the support. I will provide gif, just need to take some time for it.
