### ISSUE TITLE
JavaScript code coloring bug when comma separated var

### ISSUE THREAD

**Issue by mfazer** [Microsoft/vscode#14061]
Please notice that "watch" variable has no color here:

![image](https://cloud.githubusercontent.com/assets/17722512/19553042/d0ab7f28-96b2-11e6-9057-a3c17ea37ef8.png)

- VSCode Version: 1.6.1
- OS Version: Win 8.1

Steps to Reproduce:
```
// code coloring: with BUG:
var gulp = require('gulp'),
    watch = require('gulp-watch');

// code coloring - OK:
var less = require('gulp-less');
var path = require('path');
```

**Comment by waderyan** [comment]
We have put a lot of work into fixing this. Can you install this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) to see if it solves your issue? 

The extension is in beta and we are gathering feedback to decide to bring it into product or not.

**Comment by mfazer** [comment]
Works perfect,
Thanks
![image](https://cloud.githubusercontent.com/assets/17722512/19687353/5b5bd88c-9ac5-11e6-850c-bac370ddd108.png)
