### ISSUE TITLE
Zen Mode improvement: Toggle full screen for 1 editor group

### ISSUE THREAD

**Issue by duckimann** [microsoft/vscode#140662]
Sometimes my vscode in zen mode looks like this

![image](https://user-images.githubusercontent.com/46382253/149397594-4c1f3c98-da4b-4046-94f4-394a32dd56ec.png)

and I want to view the left group only, like... make the left group go full screen instead of all the groups.

The feature I'm trying to describe is: In zen mode, we can make a specific editor group go full screen and go back to normal zen mode (view multiple editor groups)

**Comment by JacksonKearl** [comment]
Do I understand correctly that you want to temporarily hide all editor groups besides the active one? This isn't specific to Zen mode, correct?

**Comment by duckimann** [comment]
Yeah, that's correct.
