### ISSUE TITLE
Error message appears in every cell

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode#140669]
## Environment data

-   VS Code version: 1.63.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: Python 3.9.9 / Conda 4.11.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

Error message should show wherever is only relevant.

## Actual behaviour

https://user-images.githubusercontent.com/10833267/149374282-d5e7759d-9e56-43c0-bbeb-9ca2c8ca655a.mp4

## Steps to reproduce:

1. Using the [Titanic Notebook](https://github.com/claudiaregio/data-science/blob/main/Titanic.ipynb) repo, move a cell that uses a variable (ex: "X") above where that variable is defined.
2. Error message for X not being defined shows up in every cell (doesn't show at first, possibly a perf issue, but could also just be my machine...)
3. Clicking on a cell gets rid of that error message from that cell

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment]
@rebornix I'm assuming you're not looking at this. The video shows diagnostics showing up in every cell instead of just the cell where the diagnostic message is.

**Comment by rchiodo** [comment]
That error is actually shown by this extension here:

https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens

This issue should be logged on that extension. It's the one not updating correctly.
