### ISSUE TITLE
Adding python function snippets in class changes the indent

### ISSUE THREAD

**Issue by XuShenLZ** [microsoft/vscode#140614]
Issue Type: <b>Bug</b>

This issue is too bizarre for me to believe that it can actually happen in VS code. I have been using it for a year and it only happens recently. No luck with rebooting. 

1. Open a python file
2. Start writing a class manually or with code snippets autocomplete
3. Start writing "def..." to invoke a autocomplete. Choose any one of them in the list to add a code snippet for function
4. You will see the inserted snippet reduced indentation by 1 or 2

Not all snippets has this issue. Like in the gif below, `for` loop is doing ok.

![indent](https://user-images.githubusercontent.com/31999415/149286571-9529499c-a9fe-4906-9c64-05c5ea5a8e88.gif)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.62GB free)|
|Process Argv|--crash-reporter-id 426bf50b-4335-4c6a-96dd-3bf82c502c87|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|7.70GB (6.59GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.15.10
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
sublime-keybindings|ms-|4.0.10
material-theme|zhu|3.13.10
better-cpp-syntax|jef|1.15.10
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30422343
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30416617
vsccppwtstudy:30421978

```

</details>

**Comment by jrieken** [comment]
Please attach the source, the snippets, and the exact steps that you are trying this with

**Comment by XuShenLZ** [comment]
@jrieken There is no source and the snippets are all built-in python autocomplete suggestions to create function and `for` loop.

1. Just create a blank, new python file. 
2. Create class 
3. Start creating a function with the built-in snippets `def(class method)` or `def(static class method)`
4. Then `def(class method)` will decrease indentation by 1 space and `def(static class method)` will decrease by 2.

The gif above shows very clearly what is going on. I have attached this test file [here](https://drive.google.com/file/d/1PsX9f2vg-TNjlPgbPKYZ0NP4PrJTUivB/view?usp=sharing), but I don't think it has any complex things in it.

**Comment by jrieken** [comment]
VS Code itself doesn't come with any built-in python snippets. What extension do have you have installed? It's likely that those contribute the snippet

**Comment by XuShenLZ** [comment]
Then it will be the [official python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python)... Do I need to submit this Issue there?

**Comment by jrieken** [comment]
I don't see any snippets in the official python extension. The suggest details window for a snippet will print the name of the source of the snippet. So, please check again

<img width="892" alt="Screen Shot 2022-01-24 at 16 23 19" src="https://user-images.githubusercontent.com/1794099/150811558-c68b11f9-537a-4e07-8e99-643ed3690a15.png">
