### ISSUE TITLE
After changing context lines to 0, increasing the context lines have no effect in search editor

### ISSUE THREAD

**Issue by 95th** [microsoft/vscode#140612]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
```
$ code --version
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64
```
- OS Version:
```
$ uname -a
Darwin My-MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
```
Steps to Reproduce:

1. Go to search tab. Click "Open new search editor"
2. Search some text.
3. Increase context lines to 2. It takes effect.
4. Decrease context lines to 0. It take effect.
5. Increase context lines to 2. It doesn't take effect.

**Comment by ArturoDent** [comment]
I can see this too (in Insiders).  It is as if decrease the context lines value to 0 toggles **off** the context lines for some reason.

**Comment by quanzhuo** [comment]
When the context line number decrease to zero, toggle button is unchecked. However if you increase the number again, the toggle button is not checked automatically which result in this issue.
