### ISSUE TITLE
Use zsh as the default command prompt on Mac

### ISSUE THREAD

**Issue by Louise1987** [microsoft/vscode#140690]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Update Mac book Pro to MacOS Monterey version 12.1. 
2. Open Visual Studio Code and start writing PHP. Errors will show everywhere but the code still run and works.
3. Open terminal.
4. Open terminal settings.
5. Click Generally.
6. Click Open command interpreters.
7. Click command (full path) and write in /bin/zsh and close settings.
8. Relaunch VS Code. 
9. Error still there. 
<img width="1680" alt="Skärmavbild 2022-01-14 kl  09 37 08" src="https://user-images.githubusercontent.com/31926492/149480538-dddda825-253e-4bb9-85f1-0b9bd48e239d.png">
<img width="1680" alt="Skärmavbild 2022-01-14 kl  09 38 57" src="https://user-images.githubusercontent.com/31926492/149481459-e6c58144-fc1d-4517-88d6-cf2ce012efa3.png">

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you please specify how errors that coming from PHP Intelephense are related to setting up default terminal in OS? And how both of the, are related to VS Code editor itself?

For errors that are provided by extension please see extension docs for proper configuration or raise issue in extension's repo.

For configuring VS Code integrated terminal to use different profile - check docs on this topic https://code.visualstudio.com/docs/editor/integrated-terminal#_terminal-profiles

**Comment by Louise1987** [comment]
<img width="1680" alt="Skärmavbild 2022-01-16 kl  21 59 24" src="https://user-images.githubusercontent.com/31926492/149677867-a85831a2-3480-4d3d-9de0-b595d05af340.png">

I cant add more information to this issue for i dont know what to write about it. But I try to find the php executable to fix the issue. See image to understand my problem.

**Comment by Louise1987** [comment]
<img width="1680" alt="Skärmavbild 2022-01-16 kl  22 06 12" src="https://user-images.githubusercontent.com/31926492/149678095-eb1ad56d-9b40-4fd4-851c-6e3bb4f4a7d4.png">

This is a better image showing the settings.

**Comment by Louise1987** [comment]
The information I can give is that I have my php with Mamp and now I have installed zsh to read the shell.

**Comment by meganrogge** [comment]
the source of the error is the PHP Language Features Extension. Please create an issue in that repo.
