### ISSUE TITLE
终端不能定位当前项目目录

### ISSUE THREAD

**Issue by sdutlyb** [microsoft/vscode#140603]
Issue Type: <b>Bug</b>

近期更新后，打开项目，很长时间自带的控制台终端都定位不到当前项目目录下

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

**Comment by Troubledesigner** [comment]
Translate for the question:

Issue Type: Bug

After a recent update, when I opened a project, the self-contained console can't locate the current directory for a long time.

VS Code version: Code 1.63.2 (Universal) (899d46d, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No
