### ISSUE TITLE
(Part 2) Extension host did not start in 10 seconds, it might be stopped on the first line and needs a debugger to continue.

### ISSUE THREAD

**Issue by lhton74** [microsoft/vscode#140672]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Linux x64 4.18.0-348.2.1.el8_5.x86_64

Steps to Reproduce:

1. Follow "yo code" to set up vanilla Typescript extension (https://code.visualstudio.com/api/get-started/your-first-extension).
2. Run Extension (F5)

This is a followup task to #140536, which was closed after a fix was implemented. Please see that ticket for background information. After that fix, the extension host debug issue was not resolved.

The debugger still failed to connect to the extension host. Once again, I generated the debug log file:

vscode-debugadapter-f7ae5530.json.gz

and analyzed it using https://microsoft.github.io/vscode-pwa-analyzer/index.html. It appears that ECONNREFUSED status code 503 has gone away, suggesting that your recent fix got us a bit further. However, the "cdp.send attachToTarget" message never gets a reply. I compared this with the working test case running on my local MacOS, and in that case the "cdp.send attachToTarget" message gets an immediate "cdp.receive" reply with a valid "sessionId".

Do you have any idea why this attach mechanism is still not working? How should I debug this issue further?

Here's the result of the vscode-pwa-analyzer from the failing case (running local on my Linux VM):

![image](https://user-images.githubusercontent.com/73308552/149415530-958d0fe4-ef31-4f71-be13-f25b42fd6dce.png)

**Comment by lhton74** [comment]
My specific question is: what underlying mechanism is "cdp.send/cdp.receive" using? Maybe some networking config is misconfigured on my Linux VM that prevents this handshaking from succeeding.

**Comment by connor4312** [comment]
I put in another fix for js-debug and tried to simulate your scenario the best I could on my home server, in spite of not hitting the exact same IPv6 behavior... Please try it again in on the next js-debug nightly in a couple hours. Thanks!

**Comment by lhton74** [comment]
It works!!!

I am now able to debug both the vanilla yo extension as well as my custom extension on my Linux Centos8 VM.

Thank you so much for you time and effort here. It is greatly appreciated!!

**Comment by connor4312** [comment]
Awesome, thank you for confirming the fix!
