### ISSUE TITLE
Hot Exit: push renderer backup logic into new backup service

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14065]
I notice that many backup related tasks are spread and tightly coupled in many places of untitled world and files world. This is a larger issue where I think the theme should be to LOOSEN the tight coupling of backup to the rest by leveraging more events and services. I am not a big fan of adding all backup matters into the pieces we have today. Instead this should be an optional service that is plugged in from the outside as much as that is possible.

I suggest to introduce a new service for backup handling from the renderer that deals with all these matters. 

It should contain all the methods of `IFileService` for backup related work and just use the IFileService where appropriate. 

It should listen to dirty events from the untitled and text file land and start the business of doing a backup (after a delay - for that take a look into `async.ts/RunOnceScheduler`) as well as cleaning up backups when a file is no longer dirty or the model gets disposed. This also makes it possible to reuse the same code between backing up untitled and text files.

It should answer to the question if hot exist is enabled or not for the workspace. 

It should participate in the shutdown lifecycle and do the things that `ITextFileServices` today does. I do not expect to see any backup related code in `ITextFileServices`, the only thing it should do is check for the hot exit flag to ask for confirmation or not.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/pull/14115
