### ISSUE TITLE
Hot Exit: backupService saves and loads a LOT

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14064]
I do not understand why the `backupService.ts `needs to sync save and load on basically every method invocation. We already ensure that at any time only one main process can be running so I think also only one process ever writes to `workspaces.json` in the backups folder.

I suggest to look at `storage.ts` in `electron-main` as an example and just keep the workspaces in memory and not load/save every time.

**Comment by Tyriar** [comment]
All processes currently write to the file as both workspaces (main) and files (renderer) are written. As such I think it's required unless the files portion are split out into their own files. So this:

```js
// Backups/workspaces.json
{
  "folderWorkspaces": {
    "/foo": [ "/foo/bar" ]
  }
}
```

Becomes 2 files:

```js
// Backups/workspaces.json
{
  "folderWorkspaces": [
    "/foo"
  ]
}

// Backups/<hash("/foo")>/workspace.json
{
  "files": [
    "/foo/bar"
  ]
}
```

That way saving is only necessary when adding or removing workspaces and files respectively.

**Comment by bpasero** [comment]
@Tyriar I totally like that 👍 . Backups/workspaces.json is for the main side and the other for the renderer. That way you are safe to assume that only 1 process at any time writes to these files (UNTIL we allow multiple windows on the same workspace though.......). 

This also plays nicely with the other request to split up backup service into two: main side for workspace management and renderer side for backup file management.

But I think for now the assumption is good and I think with that you could avoid a lot of the instant write/read calls and maybe buffer them in a more efficient way.

**Comment by Tyriar** [comment]
I ended up splitting it out and then removing workspace.json completely since it was only being used to restore textfiles which are now checked in the model when launching :tada:
