### ISSUE TITLE
Hot Exit: deal with backup workspaces that do not exist anymore

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14063]
On startup you add workspaces to open that have backups. What if this workspace meanwhile got deleted? You should check this on startup and remove the backup workspace from `workspaces.json` if you detect it does not exist anymore.

**Comment by Tyriar** [comment]
:-1: to removing backups unannounced under any circumstances. I would expect the folder to be opened like it currently is, ideally with a dialog asking if the user wants to restore backups on a deleted workspace..

**Comment by bpasero** [comment]
@Tyriar agree, but we are currently not able to open the folder if it does not exist so best you could do is to open a bunch of untitled files that point to the folder. I will update the title of this issue.

**Comment by bpasero** [comment]
Actually the title of this issue is still good, but the fix for this issue is more complicated to prevent loosing user data.

**Comment by Tyriar** [comment]
This is what happens right now.

1. ![image](https://cloud.githubusercontent.com/assets/2193314/19590654/d621ef58-9727-11e6-9959-0e0549d6476e.png)
2. `rm ../temp-workspace`
3. ![image](https://cloud.githubusercontent.com/assets/2193314/19590667/e84e8920-9727-11e6-9013-51b12ce6d4d4.png)

**Comment by bpasero** [comment]
@Tyriar it seems to me the file that was previously "test file" is now called "temp-workspace"? path issues?

**Comment by Tyriar** [comment]
@bpasero in the example temp-workspace was the original workspace, after being deleted it tried to open it as a file. I'm assuming this happened:

- Open `temp-workspace` in code
- Close code
- Delete `temp-workspace`
- Open `temp-workspace` in code
- Attempt to restore `temp-workspace` (throws an exception(
- Assume `temp-workspace` is a file as it wasn't a directory and try open i.

**Comment by Tyriar** [comment]
I disabled restore for now, the backups are kept around though. Moving the notification to https://github.com/Microsoft/vscode/issues/14705
