### ISSUE TITLE
editer focus bug after close quick open picker

### ISSUE THREAD

**Issue by BTBMan** [microsoft/vscode#140615]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.63.2
- OS Version:Darwin x64 20.6.0

Steps to Reproduce:

1. tap `cmd + p`, and then tap `esc` to close picker
2. tap `ctrl + tab`, and then tap `esc` while still hold `ctrl` key to close picker

after that, it's not focus on active editer group and don't know where foucs on

**Comment by TylerLeonhardt** [comment]
Interestingly, without step one, this doesn't repro. I wonder if focus is somehow held on by the quick pick.

**Comment by bpasero** [comment]
I cannot reproduce even with both steps applied 🤔

**Comment by TylerLeonhardt** [comment]
Yeah I can't repro either... @BTBMan do you still repro?

**Comment by BTBMan** [comment]
I can't repro now, probably fixed? 😂
