### ISSUE TITLE
Hooks to improve the debugger for compile-to-js languages?

### ISSUE THREAD

**Issue by evanw** [Microsoft/vscode#1406]
I'm working on a compile-to-js language called [Skew](http://www.skew-lang.org/). Visual Studio Code's language services API has been really awesome so far and I'm impressed how easy it was to hook up my compiler to provide standard features like tooltips and diagnostics and so on. I tried to do the same thing in Atom and ended up needing to implement tooltips and squiggly underlines and stuff which was a bummer. So great job on the API!

Right now the primary target language for the Skew compiler is JavaScript, so it makes sense to run Skew code with the node debugger target. I recently discovered that the debugger supports source maps so I'd like to focus on making Visual Studio Code the primary IDE for Skew. However, Skew is different enough from JavaScript that the values in the debugger panel don't make sense sometimes and the value tooltips often don't work. Some examples: the object context is called "self" instead of "this", enums show up as numbers instead of their textual names, function names in the call stack use their rewritten names instead of their original names.

Is there a way to hook into the view layer of the debugger to provide better names, tooltips, and value visualizations for languages that compile to JavaScript? The debugger API seems to be at the wrong level. I want to leverage the existing node debugger, just change the view layer when the current file is Skew code. Doing this customization in the view layer also seems like the right place to me because it means debugging a project that uses multiple compile-to-js languages would be able to work. Other languages could benefit too. For example, tooltips currently don't work when debugging CoffeeScript for variables that use the "@" prefix to access instance variables.

**Comment by weinand** [comment]
@evanw it is not yet possible to hook into the view layer of the debugger. But it is planned to open this up, e.g. for tooltips. But even if we would introduce hooks in the variables view, it will be difficult for you to do correct name substitution. The reason for this is that the VSCode debugger is language agnostic. It does not understand in any way what is displayed in the variables view. It is just a tree of name/value pairs. There is no type information available. The debug adapter prepares (formats) the strings, the UI renders them without further interpretation. Just blindly replacing numbers by enum values would not work. But let's continue the discussion!
(adding @isidorn)

**Comment by evanw** [comment]
I was imagining that visualizing enums correctly could be accomplished by having the compiler emit custom metadata into the generated source maps which is then retrieved by the view layer. I looked more into this last night and it looks like the tooltip lookup request starts [here](
https://github.com/Microsoft/vscode/blob/f21fd8f/src/vs/workbench/parts/debug/browser/debugHoverWidget.ts#L55), but it's based on string splitting using "." which means it's not that robust. For example, tooltips work for "this.foo" but not for "(this).foo" when debugging JavaScript. Maybe it would make sense to pass that range down to the debugger and ask it what the value at that position is? That way the lookup could potentially use the actual syntax tree for better accuracy. Also, if that range could be mapped through a source map, that might be a good way to automatically make tooltips work a lot better for compile-to-js languages (CoffeeScript's "@" variables might just work, for example).
