### ISSUE TITLE
Explore an view that provides shortcut for all programming languages

### ISSUE THREAD

**Issue by nickzhums** [microsoft/vscode#140634]
Hi VS Code folks,
This is obviously long-term discussion but we have received feedback like this in our VS Code Java user survey:

“as we all know java is a verbose language why don't you guys add a seprate section to show shortcuts of every language this will make programmer's life easy  “ 

This leads us to think of an view that will display a shortcut for all available programming languages

thanks!
Nick

**Comment by digitarald** [comment]
Keyboard shortcuts solve this but please re-open if not. I might be lacking context on what it means to show "keyboard shortcuts for a language"
