### ISSUE TITLE
Add thorough unit tests for CommandDetection capability

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140668]
This is blocked on the CommandDetection capability implementation being added https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/terminal/common/capabilities/commandDetectionCapability.ts

Good candidate for unit tests as this code would be very fragile without it, currently at:

https://github.com/Microsoft/vscode/blob/36a768abef01532fc1517b176bfbfbf0ae39cfab/src/vs/workbench/contrib/terminal/browser/xterm/cognisantCommandTrackerAddon.ts#L49

Should also tidy up the code as part of this, removing `!`, reviewing logic around building the command object, etc.

**Comment by meganrogge** [comment]
remember to add a suite for cognisantCommandTracker

**Comment by Tyriar** [comment]
Closing as tests exist and are fairly easy to add, can add more as required by other items.
