### ISSUE TITLE
"Find and replace all in selection" don't work

### ISSUE THREAD

**Issue by ItShallBeDone** [microsoft/vscode#140687]
Issue Type: <b>Bug</b>

1. Press Ctrl+H
2. Imput value to find
3. Input replace value 
4. Press "Find in selection" button
5. Select part of text with multiply occurence of text to find
6. Press "Replace all" button
Result : nothing replaced

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (17.50GB free)|
|Process Argv|--crash-reporter-id 0b9b0c12-ef2e-449e-a456-b103a68d16fb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
bracket-pair-colorizer|Coe|1.0.62
emulate|Die|1.6.0
xml|Dot|2.5.1
vscode-nuget-package-manager|jmr|1.1.6
data-workspace-vscode|ms-|0.1.0
mssql|ms-|1.12.0
sql-database-projects-vscode|ms-|0.14.1
partial-diff|ryu|1.4.3

</details>

**Comment by rebornix** [comment]
@ItShallBeDone the way find in selection works is 

* select a range of text
* click find in selection, the current selection now becomes the search scope
* now find and replace will work in the scope
