### ISSUE TITLE
input by IME in search box of terimal doesn't work correctly in Japanese

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#140611]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.15.13-arch1-1

IME:
fcitx: 4.2.9.8-1
fcitx-mozc: 2.26.4360.102.gca82d39-1

Steps to Reproduce:

1.  show search box in terminal
2. input words as usual by IME

https://user-images.githubusercontent.com/52106048/149277290-5572979f-be40-4f54-b2b6-70c3f948c8ab.mp4

works correctly in editor's search box.

https://user-images.githubusercontent.com/52106048/149277311-65e95ce2-5587-4263-95c1-dcce06e1ad92.mp4

**Comment by Tyriar** [comment]
Can reproduce:

![Image](https://user-images.githubusercontent.com/2193314/206801222-32d5ce53-5672-459b-b448-5f532202d56b.gif)

It should read こんいちは！！

**Comment by Tyriar** [comment]
Same problem but for Korean: https://github.com/microsoft/vscode/issues/142639, let's track separately to make sure both cases work.

**Comment by Tyriar** [comment]
This should be fixed now
