### ISSUE TITLE
Deleted a folder permanently

### ISSUE THREAD

**Issue by Khimoiddin** [microsoft/vscode#140655]
I have deleted a folder runoff.c on vscode permanently accidentally, now I am trying to reinstall the folder from the assignment page, but it won't let me. I do not know how to work and submit the assignment. Can anyone give me an advice on how to solve the problem? Thank you in advance.

**Comment by JacksonKearl** [comment]
I'm not sure what you mean by "I am trying to reinstall the folder from the assignment page, but it won't let me". Could you include a screen recording of the exact behaviour you're seeing?

\gifPlease

**Comment by Khimoiddin** [comment]
Good evening,
Thank you for reaching out to help. I fixed by turning the power off and on.
