### ISSUE TITLE
Explorer menu contribution shows hover with identical text when hovered

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140631]
![image](https://user-images.githubusercontent.com/2193314/149349580-e58aad49-d612-41cb-949f-4cbc4ee89d49.png)

Command:

```
{ "command": "luna.file.inspectImageFile", "title": "File > Inspect Image File", "category": "Luna", "shortTitle": "Inspect Image File" },
```

Menu contribution:

```
"explorer/context": [
	{
		"command": "luna.file.inspectImageFile",
		"when": "resourceExtname =~ /\\.png$/"
	}
]
```

**Comment by JacksonKearl** [comment]
What would you expect to happen here? cc @sbatten for custom menus.

**Comment by JacksonKearl** [comment]
Seems to be the same across all extension contributions to custom menus. 
<img width="1440" alt="Screen Shot 2022-01-13 at 3 58 49 PM" src="https://user-images.githubusercontent.com/8586769/149427644-4ea6d274-0e2f-4675-b298-aa0e8ce65543.png">

**Comment by sbatten** [comment]
same as bug noticed with https://github.com/microsoft/vscode/issues/138653
