### ISSUE TITLE
Disable underlining for clickable URLs

### ISSUE THREAD

**Issue by tfiers** [microsoft/vscode#140657]
It would be nice to have the option to not underline URLs in source code -- but still make them ctrl-clickable.

`"editor.links": false` disables the underline but also makes them unclickable.

A lighter shade and thinner line might also work.
Currently, URLs are visually quite heavy with respect to surrounding text, while they're usually not the most important thing.

The [current workaround](https://stackoverflow.com/a/69555779/2611913) is not so stable.

**Comment by CodingMarkus** [comment]
This 20 upvote policy is stupid. I bet there are several hundred people in the world who don't want their links underline but they will not permanently monitor all issues of this GitHub repo, so they can jump in when someone requests for something they may want as well.
