### ISSUE TITLE
when i start vscode stops working properly after few seconds from launch

### ISSUE THREAD

**Issue by medtahabakri** [microsoft/vscode#140637]
Issue Type: <b>Bug</b>

i just launch vs code after few seconds features like intellisense and language formatter also edit file name and file copy and many other functionalities stop working it maybe because of an extension or something but i dont know whats the problem

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.4.0-91-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3175)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.52GB (4.29GB free)|
|Process Argv|. --crash-reporter-id 1818c0a4-d5dc-421e-8d11-000a17d70ab2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify-blade|api|1.0.1
vscode-intelephense-client|bme|1.8.0
tpl|cdp|1.0.1
npm-intellisense|chr|1.4.0
vscode-sql-beautify|cla|0.2.8
bracket-pair-colorizer|Coe|1.0.62
doxdocgen|csc|1.3.2
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
react-native-react-redux|EQu|2.0.6
beautify|Hoo|1.5.0
better-cpp-syntax|jef|1.15.10
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.1
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5242
vscode-react-native|msj|1.8.1
vetur|oct|0.35.0
es6-css-minify|olb|3.3.2
laravel-blade|one|1.29.0
java|red|1.2.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.6.1
vue-vscode-snippets|sdr|2.2.1
vscode-blade-formatter|shu|0.10.2
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2
vuetify-vscode|vue|0.2.0
html-snippets|wsc|1.0.6
search|Wsc|1.0.37
vue|Wsc|1.0.26
vue-extensionpack|Wsc|0.0.6
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
pythonvspyl392:30422343
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710:30416614
vsccppwtstudy:30421978

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo


You should check if it reproducible with all extensions disabled.
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Also if there are errors in developers tools(check Help menu) if issues are still there with all extensions disabled.
