### ISSUE TITLE
Screen Corruption Windows 11

### ISSUE THREAD

**Issue by NaHyeongJin** [microsoft/vscode#140675]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2 (user setup)
- VS Code Insider Version: 1.64.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:

Just turning on VSCode/VSCode Insiders leads to visible screen corruption making usage impossible
Problem persisted on fresh install, even when I had manually erased the entire extensions folder.

![unknown](https://user-images.githubusercontent.com/56540533/149430179-3e0733fa-4c73-4b38-8279-68a13a1fc5c1.png)
![image](https://user-images.githubusercontent.com/56540533/149430237-83798adf-0477-4369-8e53-ac54f9d9f05c.png)
![image](https://user-images.githubusercontent.com/56540533/149430278-16d00fd6-4031-40e1-a15e-eb9a78be989c.png)

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/139827#issuecomment-1001943302 suggests steps that may help you investigate the problem.

**Comment by NaHyeongJin** [comment]
> [#139827 (comment)](https://github.com/microsoft/vscode/issues/139827#issuecomment-1001943302) suggests steps that may help you investigate the problem.

The steps detailed in this link fixed my problems.
Should I close this issue?

**Comment by gjsjohnmurray** [comment]
Good. Yes I suggest you close this one and subscribe to the other one.

**Comment by NaHyeongJin** [comment]
> Good. Yes I suggest you close this one and subscribe to the other one.

Thank you.
