### ISSUE TITLE
Remote support for shell integration

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140663]
Main thing here is ensuring the shell scripts exist on the remote side and their paths are resolved correctly.

**Comment by Tyriar** [comment]
This is how we add the scripts to the bundle:

https://github.com/microsoft/vscode/blob/fdb52b8b3ad62d97af6bfcc32eaa4a0c08b261ad/build/gulpfile.vscode.js#L72-L73

Need to make sure the path is correct in remote workspaces as well.

**Comment by meganrogge** [comment]
Works in the test resolver and using SSH

![Screen Shot 2022-01-19 at 12 04 41 PM](https://user-images.githubusercontent.com/29464607/150188350-5d8bb970-f307-4eaf-9a22-e1d8a3da1fd0.png)
