### ISSUE TITLE
How can I remove the select code snippet shadow

### ISSUE THREAD

**Issue by wnz27** [microsoft/vscode#140764]
when I USE , the vscode show:
<img width="788" alt="截屏2022-01-15 14 52 05" src="https://user-images.githubusercontent.com/12094918/149612632-9b1836b6-2fe5-499e-933c-bf256366c58f.png">
the shadow cover all functions snippet, what config I change can remove this。

**Comment by jrieken** [comment]
Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

**Comment by wnz27** [comment]
> Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks.
> 
> <img alt="screen shot 2018-05-09 at 08 45 10" width="577" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

I need some extensions, I don't know what extention cause this problem

**Comment by wnz27** [comment]
> Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks.
> 
> <img alt="screen shot 2018-05-09 at 08 45 10" width="577" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

disabled and enabled config have some change。。。。my god 。。。。。。

**Comment by jrieken** [comment]
I am sorry but I cannot follow

**Comment by wnz27** [comment]
> I am sorry but I cannot follow

never mind, it doesn't matter, I think I need more explore and attempt.
