### ISSUE TITLE
'Find next' in a notebook should continue from cursor, not from top!

### ISSUE THREAD

**Issue by Ozziko** [microsoft/vscode#140743]
Issue Type: <b>Bug</b>

'Find next' in a notebook should continue from cursor position and on, not start from the top of the notebook! 'Find next' in scripts works intuitively - from curson on, not the top...

Extension version: 2021.11.1001550889
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710:30416614
vsccppwtstudy:30421978

```

</details>

**Comment by greazer** [comment]
We have recently made changes to how find works in notebooks. The latest behavior can be experimented with in the Insiders build of VS Code. 

Closing this assuming the request here has been granted. :)
