### ISSUE TITLE
"Build Task" terminal window inconsistent scrolling behavior

### ISSUE THREAD

**Issue by kice** [microsoft/vscode#140788]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Win 10

Steps to Reproduce:

1. Set `terminal.integrated.mouseWheelScrollSensitivity` very small
2. Run any build task
3. Scroll the `Build task` output window, and it will scroll way to many lines

The build task window scroll differently than other terminal window, in my case it was too fast, even if set `terminal.integrated.mouseWheelScrollSensitivity` to `0` or a small non-zero value.

And sometime, after losing the focus, then scroll the `Build task` output window, it **might** scroll like other terminal windows, such as the Powershell terminal window.

**Comment by kice** [comment]
> > 1. Set terminal.integrated.mouseWheelScrollSensitivity very small
> 
> What value are you using for this setting? I tried with .1, and I do not see the issue.

From 0.1 to 0.001 to 0.0. Maybe because I am using a high DPI monitor or scaling is not 100%.

**Comment by alexr00** [comment]
@Tyriar do you know why this might happen? I'm not able to reproduce the issue and I don't have access to a high DPI monitor to test at the moment.

**Comment by Tyriar** [comment]
Can repro and figured out the issue. It's not related to tasks, just the fact that you created the tasks terminal and not the others after changing the options. We initialize it with the wrong value:

https://github.com/microsoft/vscode/blob/c389cbe3e4622e73a980372add84233ca278f637/src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts#L120-L121
