### ISSUE TITLE
Insiders not automatically getting the pre-release version of GHPR extension

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#140706]
I don't think I switched to the release version, but it doesn't update to the latest pre-release:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/9205389/149522091-b2adb68d-54e6-413d-8b96-195d87fa2a27.png">

The pre-release versions have higher version numbers:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/9205389/149522172-cd7e97c2-047b-4640-84cb-ca98d5be4513.png">

/cc @alexr00

**Comment by sandy081** [comment]
It seems you didn't opted into the pre-release version first of all, are you sure? Switch to pre-release and you shall be on latest version always.

**Comment by chrmarti** [comment]
Same with Remote-Containers. I think it just doesn't automatically go from non-pre-release to pre-release when the first pre-release version is published. I just did that for Remote-Containers:
- Install latest non-pre-release extension version when no pre-release version is published yet.
- Publish first pre-release version.
- No automatic update in VS Code Insiders to pre-release version of extension. 🐛 

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/9205389/149540502-39f531a3-f9b8-4e5d-a252-f38fcd9c46f3.png">

**Comment by sandy081** [comment]
Yes, that's expected. There is no opt into pre-release if there is no latest pre-release. This is bit weird for user to do so as the user is not seeing any pre-release. Once user installs the pre-release updates make sure user always gets latest version.

**Comment by chrmarti** [comment]
@sandy081 I have so far used the `"engines"` property in the `package.json` to make sure VS Code Insiders users get the in-development version of Remote-Containers. If they now do not automatically get the pre-release version, the number of pre-release users basically resets to 0.

For VS Code Insiders, it would make sense to make 'pre-release' the default, not only in the UI, but also when the release version of an extension is already installed at the time the first pre-release version becomes available.

/cc @isidorn

**Comment by chrmarti** [comment]
This would also make sense for extensions not having used the `"engines"` property to have in-development versions because VS Code Insiders users having installed an extension before it released its first pre-release version, did not "opt-out", they were just not given the default "opt-in" UI.

**Comment by isidorn** [comment]
@chrmarti it seems like you were using the same flow as the Jupyter extension - using `engines` to control if pre-release or not. So in order to have a smooth transition I would recommend the same as I did to the jupyter extension:

1. For your current in-development version of your extension do the following
2. Show a persistent notification to the user, or a modal dialog "bla bla we moved to pre-release - click here to be migrated"
3. Once user clicks -> execute 
```
vscode.commands.executeCommand("workbench.extensions.installExtension", "ms-vscode-remote.remote-containers", { installPreReleaseVersion: true });
```

**Comment by chrmarti** [comment]
@isidorn Every extension publishing their first pre-release version when there already is a substantial number of VS Code Insiders users using the extension's stable release is going to add such a modal dialog. Wouldn't it be easier to upgrade VS Code Insiders users automatically to the first pre-release version?

**Comment by isidorn** [comment]
@chrmarti in practice there are only two extension which are using this mechanism: the remote containers and jupyter. All other extensions have a separate insiders extension for which we support transition from the VS Code side. So I suggest that each of these two extensions does the dialog approach.
Hope this makes sense.

**Comment by chrmarti** [comment]
@isidorn I'm also thinking about extensions that did not use `"engines"` or a separate insiders extension. They would also benefit from VS Code Insiders users automatically moving on to their first pre-release version when they publish it.

**Comment by isidorn** [comment]
@chrmarti that is correct, but we had quite some discussions in the standup if the VS Code Insiders users should automatically start using pre-release extensions. And there were a lot of pros and cons to this approach. In the end we decided on a diplomatic solution: that for insiders we just offer by default the pre-release extension version and we would not automatically install pre-release extensions.
While your suggesting makes sense to me, I think it would cross this fine diplomatic line which we have achieved in the past.

**Comment by sandy081** [comment]
I see your issue about updating from previous insiders version to new pre-release version automatically. We have a migration strategy for other use cases but not for this. Let me know if there is any way for the workbench to know so that it can auto update the extension to latest pre-release version.

Regarding auto installing pre-release in insiders, I agree with @isidorn and the current UI has the right balance for supporting pre-releases in insiders.

**Comment by chrmarti** [comment]
Ok, will add that to the adoption. Note that I originally filed this for the GHPR extension. Good to close this issue if that is working as designed too.

**Comment by chrmarti** [comment]
I probably didn't have GHPR nightly installed. So not getting the pre-release seems expected. Closing.

**Comment by chrmarti** [comment]
Thinking about this some more, I realize this will loose many in-development users of Remote-Containers. Users never had to think about whether they want to follow the development version of Remote-Containers before, but they opted-in implicitly by installing VS Code Insiders. Presenting them with a modal dialog (followed by a second modal dialog asking if they want to sync the extension) will make many opt-out. That's a much different flow from the UX presented to users when they install the extension for the first time and just have to click the default 'install pre-release' button.

There are probably two kinds of pre-releases: those going through smoke-testing and sanity-checking and those releasing automatically once a day. I release Remote-Containers maybe once a week and want as many "insiders" testing the in-development version as possible because that is expected to have high quality and if there is a regression I quickly fix it in a new version. Extensions doing nightly pre-releases on the other hand are tested more carefully only before their stable release and nightly releases are more often used for early verification of fixes and considered more on the bleeding edge.

Can I get a command to switch the extension to use pre-release versions without any prompts? (The sync flag would be preserved.)

**Comment by sandy081** [comment]
Lets sync on this tomorrow
