### ISSUE TITLE
Debug console doesn't show line number when using console.log

### ISSUE THREAD

**Issue by mozeryansky** [microsoft/vscode#140785]
Issue Type: <b>Bug</b>

I am using NextJS and I have the output to the Debug Console. The line numbers appear on the right for all the uses of console.log except when I include a variable.

console.log("hello") <<-- Works

console.log("x =", x) <<-- prints value but no file/line number 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<img width="964" alt="Screen Shot 2022-01-15 at 3 21 19 PM" src="https://user-images.githubusercontent.com/3287719/149638107-78889c22-dda0-4ddd-8908-251b893bcdb5.png">
<details>

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 8, 6|
|Memory (System)|16.00GB (0.63GB free)|
|Process Argv|--crash-reporter-id d4de4934-b068-4ba8-88d7-18fa765609dd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-opennewinstance|chr|0.0.12
npm-intellisense|chr|1.4.0
postcss|css|1.0.9
vscode-eslint|dba|2.2.2
vscode-npm-script|eg2|0.3.23
rainbow-csv|mec|2.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710cf:30416617
vsccppwtstudy:30421978

```

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/137100
