### ISSUE TITLE
Make ctrl+` keybinding useful when terminal is in the sidebar

### ISSUE THREAD

**Issue by szhu** [microsoft/vscode#140760]
## Background

Originally:
- Terminals could only appear in the panel.
- The <code>ctrl+&#96;</code> keybinding would run `workbench.action.terminal.toggleTerminal`, which would behave as follows:
  1. If the terminal viewlet in the panel is not showing, show it.
  2. If it is showing but not focused, focus it.
  3. If it is focused, hide the panel.

Then two features were released:
- Terminals could appear in the sidebar.
- Terminals could appear in the editor.

## The issue

These new features are amazing! However, the <code>ctrl+&#96;</code> keybinding doesn't play well with terminal in the sidebar:
- If a terminal in the sidebar is focused, the keybinding doesn't do anything. To be consistent with behavior 3. above, I think it should hide the sidebar.
- If the terminal viewlet in the sidebar is focused but contains no terminals, the keybinding doesn't do anything. This case doesn't have a precedent in the panel, since closing the last terminal in the panel hides the panel. For the sidebar case, I think it's acceptable for the keybinding to either create a new terminal or hide the sidebar.

Here's a screencast showing this -- you can see that <code>ctrl+&#96;</code> toggles the terminal in the panel but not the terminal in the sidebar:

![Screen Recording 2022-01-14 at 11 23 33 PM](https://user-images.githubusercontent.com/1570168/149609441-2c12c8db-5b07-4ed4-89c1-f6571968b736.gif)

## Workaround

This is a set of keybindings that implements the missing behavior above:

<details><summary><code>keybindings.json</code></summary>

```jsonc
[
  // Disable the default keybinding.
  {
    "key": "ctrl+`",
    "command": "-workbench.action.terminal.toggleTerminal",
    "when": "terminal.active"
  },

  // For the keybindings below, we want to ignore any opened terminals in the
  // editor, because toggling doesn't apply to them. So instead of
  // `terminalFocus`, we use `(terminalFocus && !terminalEditorFocus)`.

  // When the terminal is not focused, show it using `terminal.toggleTerminal.`
  {
    "key": "ctrl+`",
    "command": "workbench.action.terminal.toggleTerminal",
    "when": "terminal.active && !(terminalFocus && !terminalEditorFocus) && activeViewlet != 'terminal'"
  },

  // Edge case: When the terminal viewlet is visible in the sidebar, but all
  // terminals have been closed, the terminal is not considered focused, and
  // `toggleTerminal` does nothing. In this case, we create a new terminal using
  // `terminal.new`.
  {
    "key": "ctrl+`",
    "command": "workbench.action.terminal.new",
    // Alternatively, maybe the right action is to hide the sidebar:
    // "command": "workbench.action.toggleSidebarVisibility",
    "when": "terminal.active && !(terminalFocus && !terminalEditorFocus) && activeViewlet == 'terminal'"
  },

  // If the terminal is focused and is in the sidebar, hide it using using
  // `toggleSidebarVisibility`.
  {
    "key": "ctrl+`",
    "command": "workbench.action.toggleSidebarVisibility",
    "when": "terminal.active && terminalFocus && !terminalEditorFocus && sideBarFocus"
  },

  // If the terminal is focused and is in the panel, hide it using
  // `terminal.toggleTerminal`.
  {
    "key": "ctrl+`",
    "command": "workbench.action.terminal.toggleTerminal",
    "when": "terminal.active && terminalFocus && !terminalEditorFocus && panelFocus"
  },
]
```

</details>

Here's a screencast showing that things work correctly after applying these keybindings:

![Screen Recording 2022-01-14 at 11 25 08 PM](https://user-images.githubusercontent.com/1570168/149609449-b9c0e7bc-33d5-4481-a60d-330a075a67a3.gif)

## Proposed solution

- The behavior described by the keybindings above should be the default.
- `workbench.action.terminal.toggleTerminal` should do something meaningful when the sidebar is showing the terminal viewlet, including the edge case where no terminal is open.
- Similar to `terminalEditorFocus`, `terminalPanelFocus` and `terminalSideBarFocus` should be available to use in the `when` clause.

**Comment by sbatten** [comment]
@sandy081 it looks like we just have hardcoded behaviour to only focus in the sidebar. was this because there might be multiple views in the side bar and we thought hiding would be strange? I think we could easily change this here https://github.com/microsoft/vscode/blob/3febecac20f00eedbbcc13348ea27146f4d60eeb/src/vs/workbench/browser/parts/views/viewsService.ts#L433-L441

**Comment by sandy081** [comment]
> was this because there might be multiple views in the side bar and we thought hiding would be strange? 

No. I think, it is the intentional/legacy design of Side bar and Panel ie., Side bar view commands switch focus between the editor and the side bar whereas panels view commands are designed to be 3-state toggle (focus, hide, show).

Here are some old issues discussing about this behaviour

https://github.com/microsoft/vscode/issues/7540
https://github.com/microsoft/vscode/issues/19400

**Comment by szhu** [comment]
Hi, I just tried out the Insiders build. I see that the behavior is now for <code>Ctrl-`</code> to toggle terminal focus, if the terminal is the sidebar.

I created this issue primarily to suggest making the shortcut to toggle the terminal also toggle sidebar visibility. Can you clarify what the verdict is on that -- is this something that will not be supported? If not, is there a way to make improvements to keyboard shortcut handling so that it's easier for users to add that functionality?

I can also create a new issue for this. Let me know if that's the recommended way forward.

**Comment by sbatten** [comment]
Hi @szhu, sorry about the confusion. There were a lot of historical discussions that determined that the side bar and panels should function differently with respect to toggle behavior. The determination is as follows:

**For Side Bar**
The keybinding toggles through 2 states: Focus View and Focus Editor

**For Panel/Side Panel**
The keybinding toggles through 3 states: Open View and Focus, Focus View if not Focused, Close View if Focused

You can get the behavior you want with the following keybinding:

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/6561887/151217818-dd20c641-9f7f-4d59-ba35-b052e7f351fa.png">
