### ISSUE TITLE
Having a setting to remove "information" from "problems" tab. 

### ISSUE THREAD

**Issue by Ierezell** [microsoft/vscode#140795]
Having a way (config, json setting, checkbox...) to remove the "information" problems from the problem type count. 

I like to have my files checked but I overrode some checks as information because they're not really problems. 
(e.g pylance `reportUnusedCallResult` or `reportPrivateUsage` or some fancy like `reportUnusedFunction` because decorated and used in another factory function etc....)

However, those "informations" are still showing in the problems tab count and I find it weird to have hundreds of "problems" that are not. 

The quick fix is to put those checks as "none" (which totally removes them). However, I would still like to see them somewhere. 

Maybe removing them from the little count bubble if they're unchecked ? 
Like showing the X instead of Y in the problem  tooltip from the `showing X of Y` in the filter. 

Thanks in advance, 
Have a great day !

**Comment by Ierezell** [comment]
I found that `"python.analysis.logLevel"` may be the thing I need, however, when setting it to all the possible values I still have information showing.

**Comment by ArturoDent** [comment]
Does the filter in the Problems view `Show Infos` disable work for you?   

![FilterInfos](https://user-images.githubusercontent.com/31813701/149704587-05067627-ae50-4626-a101-2377af624bbb.gif)

**Comment by Ierezell** [comment]
Hello @ArturoDent, thanks for your time. 

Yes, it does work, however, the tooltip still shows `problems (123)` 

If a new error appears then it will be `problems (124)` and I have no way to know if I have 124 errors, warnings, or just information.

**Comment by sandy081** [comment]
Yes, tool tip informs about all errors and filtering is done only in Problems UI.
