### ISSUE TITLE
Add Keymap & Video Help Menu Items

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#14071]
Hi,

We are going to create a single page cheat sheet for keybindings.  This should be linked from the help menu.  We have a different link for each OS.

The item should be `Keymap Reference`.

* MacOS: `https://go.microsoft.com/fwlink/?linkid=832143`
* Linux: `https://go.microsoft.com/fwlink/?linkid=832144`
* Windows: `https://go.microsoft.com/fwlink/?linkid=832145`

Currently the links point to the webpage on the website - but by the time we ship stable we will have the nice PDF versions.

We should also include a link for `Introductory Videos` which will use the single fwd link of:
* `https://go.microsoft.com/fwlink/?linkid=832146`

This is inspired by what WebStorm does.

![image](https://cloud.githubusercontent.com/assets/1051190/19554585/9732d1d6-96b9-11e6-9213-91564fd45941.png)

cc @gregvanl , @waderyan

**Comment by isidorn** [comment]
@seanmcbreen What are the titles you want to go for?
`'Keymap Cheatsheet'`
'`Introductory Videos`'

**Comment by gregvanl** [comment]
I suggest:
'Keyboard Shortcuts Reference'
'Introductory Videos'
Using 'Keyboard Shortcuts' matches what we already have in the product File > Preferences > Keyboard Shortcuts and the 'Default Keyboard Shortcuts' readonly page.

**Comment by gregvanl** [comment]
Updated fwlinks to point to code.visualstudio.com/shortcuts/keyboard-shortcuts-(platform).pdf
