### ISSUE TITLE
Partial suggestion acceptance - Github Copilot 

### ISSUE THREAD

**Issue by SmallLemur** [microsoft/vscode#140708]
When using Copilot, users would like to be able to only partially accept suggestion instead of the whole suggestion at once.
The users demand either word by word or line by line completion.

Desired behaviour:
Press a predefined key and accept the whole suggestion.
Use a predefined combination of 2 keys to accept the top line of the suggestion. (eg: For a suggestion of 3 lines, the user would need to press the combination 3 times to accept the whole suggestion). The prompt would not show the line already accepted.

**Comment by hediet** [comment]
Technically, I think this would be rather easy to implement. I'd love to hear some more UX discussion before we implement this thought.
What key-binding do you have in mind?

**Comment by isidorn** [comment]
@SmallLemur do you have some UX designers on the team that would like to help here? Once we have some good ux proposal we can bring it in our UX weekly sync on Wednesday to start the discussion.

**Comment by SmallLemur** [comment]
@isidorn No I dont have a UX designer in my team. I ll see how i can come up with a suggestion and get back to you

**Comment by YitziG** [comment]
This is similar to https://github.com/zsh-users/zsh-autosuggestions/issues/265. Solution for me was 'CMD + ->' to accept a word at a time.

Something similar here would be great.

**Comment by alloy** [comment]
Fish shell allows word-by-word completion using the <kbd>Alt</kbd> + <kbd>&#8594;</kbd> key-combo, which—_at least on macOS_—is used system-wide for navigating text word-by-word. I notice that I keep trying to automatically use this key-combo, so big +1 from me.

(This should perhaps be a feature that would need to get generic support from VS code?)

![](https://user-images.githubusercontent.com/772937/86824811-7e264300-c043-11ea-9d66-af36ca7db681.gif)

**Comment by isidorn** [comment]
@alloy awesome idea.
@hediet since you said this is low hanging maybe we assign to July for the initial investigation? What do you think?

**Comment by martinmr** [comment]
This would be great. I am loving copilot so far, but this is my biggest UX gripe. Copilot's first suggestions in a new piece of code tend to only be accurate for the first few words. It tends to get much better only after more context is added. Not a blocker, but it'd make it much easier to get started.

**Comment by isidorn** [comment]
We did an initial investigation and this is not low hanging as I have initially commented above. Also, this milestone we have been mostly focusing on improving the merge editor. So this one will have to continue in September.

**Comment by isidorn** [comment]
Had a sync with the VS folk and here's some very early thinking:
* When partial completion is accepted the ghost text should not change - we should use the cache. VS did multiple user studies and users always get shocked when the ghost text changes beneath them
* Undo is the user gesture to undo the last partial acceptance (this should work out of the box for us).
* Simple keybindings like word next navigation, and navigate to end of line should be used for partial word acceptance, and whole line acceptance. So same keybindnigs as `cursorWordEndRight` and `cursorEnd` commands.

Open questions (probably not for first version):
* How to make this keybindings discoverable
* Should we support the mouse? For example alt + mouse click to accept until the mouse click

**Comment by senorflor** [comment]
Hi! A use case for per-word completion: comment/natural language completion. I want this almost every time that copilot gives me a comment suggestion.

To make sure I understand the shape of the discussion, I think three issues are separable here:

1) whether to offer partial completion;
2) at what granularities (here the use case and example-based analysis is most relevant, and feed back into question 1);
3) if doing it, what default keybindings at these levels to provide so as not to hijack muscle memory (but possibly still utilize it in a parallel modifier key universe)?

Is that right, and if so at what stage does the team currently see the conversation?

For 3), in Lisp-y language tools, Paredit's keybindings might be a decent template too: in some sense what we are doing here is structurally selecting part of what is an `expr -> token` (falling back on a `line -> token` as above) structure before "acceptance" (which is already well-understood as a result of `Tab` by default keybinding users). That would be a more elaborate form of the partial acceptance, though, requiring a language-sensitive parse, so definitely not low hanging fruit.

**Comment by comp-nect** [comment]
It's a marketing problem, they market the code you accept as efficiency. If they would also add the 97% of the code you have to remove carefully again it wouldn't be that a nice metric.

I believe we need to adapt the plugins on our own or write a plugin watchdog, something that monitors completions, immediately removes them and offers a word-by-word insert of the code.

**Comment by hediet** [comment]
A use case from @jrieken: He wants to accept the first couple of words here (but not the entire completion):

![image](https://user-images.githubusercontent.com/2931520/196967857-b5a12364-f8ea-4fc2-a874-86a1289d4fed.png)

... `Fibon|acci numbers to` ~`ensure that we get a good distribution of`~ `have a performance benchmark that`

**Comment by cmp-nct** [comment]
@hediet
For jetbrains IDE's you can use my plugin (https://github.com/cmp-nct/Stewardess)
You press CTRL+ALT+D and it will complete the sentence word by word.

**Comment by VictorDuranEM** [comment]
I love this suggestion. I encounter the scenario of wanting to only accept a suggestion partially a lot.

**Comment by hediet** [comment]
@VictorDuranEM would you prefer word-by-word partial acceptance or line-by-line?

**Comment by VictorDuranEM** [comment]
> @VictorDuranEM would you prefer word-by-word partial acceptance or line-by-line?

It would be awesome to be able to do both, but if only one of the two is possible, then I would prefer word-by-word.

**Comment by cmp-nct** [comment]
There is no reason why only one would be doable.
A line based completion is a couple of lines of code.
Word based completion is half a page if you want to do the word separation smart, or an abstract if it's dumb.

**Comment by hediet** [comment]
First iteration has been implemented in #166956
