### ISSUE TITLE
FileChooser and sub-menus not using dark theme when elementary OS set to dark mode

### ISSUE THREAD

**Issue by joeljose350** [microsoft/vscode#140786]
Does this issue occur when all extensions are disabled?: Yes

VS Code information:

```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-46-generic
```

OS: elementary OS 6.1 (Jólnir)

Steps to Reproduce:

1. Set OS to dark mode in System Settings.
2. Open VS Code.
3. Press Ctrl + O to open the FileChooser or open any of the sub-menus.
4. Observe that the FileChooser and the sub-menus are using a light theme.

![Screenshot from 2022-01-16 03-22-01](https://user-images.githubusercontent.com/53969297/149639101-57d9e187-a3e0-4a09-bb4c-9c1fcc7397f7.png)

Note: VS Code FileChooser and sub-menus do use the dark theme in Pop!_OS 21.10

![Screenshot from 2022-01-16 03-13-19](https://user-images.githubusercontent.com/53969297/149639124-a6c03f0f-9eac-4f7e-9a26-f6d8f9f3b3aa.png)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/50386
