### ISSUE TITLE
Source control panel - sync changes button when syncing is not in loading state

### ISSUE THREAD

**Issue by matystu** [microsoft/vscode#140731]
![image](https://user-images.githubusercontent.com/68393567/149564615-4881ca1e-d525-4a4e-8576-4182a2d63377.png)
This button that you can see in my attached image, is in source control panel when you have changes to sync. But when you start syncing changes, the round icon is not loading as it's loading in bottom bar. I think it should be in loading state.

**Comment by lszomoru** [comment]
@misolori when icon animation was implemented for the status bar, have we considered doing the same for the Button widget?

**Comment by misolori** [comment]
@lszomoru I don't think we ever did consider it but can be possible via `$(icon~spin)` or by using the class `codicon-modifier-spin`:

https://user-images.githubusercontent.com/35271042/150069438-84e3d600-cc1f-472f-abe3-15384fe95bf5.mp4

**Comment by lszomoru** [comment]
@misolori, it looks good to me. Is this something that we should bring up in the weekly UX meeting?

**Comment by misolori** [comment]
@lszomoru we can post about it in the ux sync but don't expect this to be controversial. We also show the animating sync button in the multi-repo view as well:

<img width="317" alt="CleanShot 2022-01-19 at 15 24 33@2x" src="https://user-images.githubusercontent.com/35271042/150234476-3f8fa245-2df4-450d-be01-2794a722e8e6.png">
