### ISSUE TITLE
Markdown Render VSCode Command Link

### ISSUE THREAD

**Issue by rbrisita** [microsoft/vscode#140733]
Issue Type: <b>Bug</b>

Hello,

Regarding the `MarkdownString`, in Markdown this:

`[Name](link)`

Renders a link. In a VS Code Extension, this is also possible:

`[Run It](command:pkg.command)`

Creating a link to run a command.

One would think creating an actual anchor link like this:

`<a href="command:pkg.command">Run It</a>`

Would work but the click does not execute the command.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:18:59.299Z)
OS version: Linux arm64 5.15.7-1-MANJARO-ARM
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|unknown (6 x 1416)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 2|
|Memory (System)|3.77GB (0.02GB free)|
|Process Argv|. --crash-reporter-id 2a85f066-a8e2-4971-b1ff-37959f57a0f0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
vscode-drawio|hed|1.6.4
vsliveshare|ms-|1.0.5242

</details>

**Comment by WaqasAliAbbasi** [comment]
can i take this?

**Comment by rbrisita** [comment]
I think they'd be happy if you created a PR.

For completeness: `data-href` works:

`<a data-href="command:pkg.command">Run It</a>`

 but the cursor does not change to a hand icon like if `href` was populated.

**Comment by WaqasAliAbbasi** [comment]
> I think they'd be happy if you created a PR.
> 
> For completeness: `data-href` works:
> 
> `<a data-href="command:pkg.command">Run It</a>`
> 
> but the cursor does not change to a hand icon like if `href` was populated.

Thanks, will take a look

**Comment by WaqasAliAbbasi** [comment]
This is what I found. In markdown links are detected at two places:
  - [extensions\markdown-language-features\src\features\documentLinkProvider.ts](https://github.com/microsoft/vscode/blob/main/src/vs/editor/common/languages/linkComputer.ts) detects anything starting with http:// or https:// or file:// 
  - [extensions\markdown-language-features\src\features\documentLinkProvider.ts](https://github.com/microsoft/vscode/blob/main/extensions/markdown-language-features/src/features/documentLinkProvider.ts) checks for `[]()` and returns anything inside () as URI

That's why [Run It](command:pkg.command) is detected as a link but `<a href="command:pkg.command">Run It</a>` isn't. 

I couldn't get `<a data-href="command:pkg.command">Run It</a>` to work. I tried holding ctrl while clicking it and tried in preview as well. Can you tell me how to reproduce it?

**Comment by rbrisita** [comment]
You'll need to [register a command](https://code.visualstudio.com/api/extension-guides/command#creating-new-commands) for it to take an action. The example in the link is probably the easiest. After registration create a MarkdownString containing the registered command. In regards to the linked example:

`<a data-href="command:myExtension.sayHello">Say Hello</a>`

You should be able to click on it and see the console log. Note that the cursor doesn't change to a hand icon.

**Comment by HadesArchitect** [comment]
@rbrisita Have you found any solution? For me even `data-href` doesn't work :(

**Comment by rbrisita** [comment]
The way I implemented Markdown and executing a registered command (through package.json) was by adding a [`MarkdownString`](https://code.visualstudio.com/api/references/vscode-api#MarkdownString) (mds) to the tooltip of a [`StatusBarItem`](https://code.visualstudio.com/api/references/vscode-api#StatusBarItem). The structure is very particular because it is an implementation of the [CommonMark Spec ](https://spec.commonmark.org/0.30) and is something like this:

```typescript
const stop = '# [$(debug-stop)](command:my_ext.stop)';
const table = `
<table>
<tbody>
<tr>
<td align="center">

${stop}

</td>
</tr>
</tbody>
</table>
`;
mds.value = table;
statusBar.tooltip = mds;
```

Make sure you are using the correct VS Code version too.

**Comment by mjbvz** [comment]
Command links in `MarkdownString` should now also work for normal `<a>` elements included in the markdown (you have to set `isTrusted` and `supportHtml` on the `MarkdownString` to enable this)

**Comment by TylerLeonhardt** [comment]
@mjbvz where should links work? I tried this in a completion item `MarkdownString` and neither link syntaxes work:
```
snippetCompletion.documentation = new vscode.MarkdownString("Inserts a snippet that lets you select the _appropriate_ part of the day for your greeting.[run it](command:workbench.action.reloadWindow) <a href='command:workbench.action.reloadWindow'>Run It</a>");
```
![Screen Shot 2022-06-02 at 11 31 31 AM](https://user-images.githubusercontent.com/2644648/171701392-d79ed57a-e5b4-45bd-b8d2-9f8f0b0df630.png)

**Comment by mjbvz** [comment]
@TylerLeonhardt Sorry for not adding verification details. The markdown string needs to both trusted and have html enabled:

```
const docs = new vscode.MarkdownString(`<a href="command:workbench.action.toggleSidebarVisibility">Run It</a>.`);
docs.isTrusted = true;
docs.supportHtml = true;
```
