### ISSUE TITLE
Git: support not passing -u to git status for large repositories

### ISSUE THREAD

**Issue by brianduff** [microsoft/vscode#140755]
For very large git repositories, the `-u` option (an alias for `-uall`) can sometimes make `git status` take a large amount of time and CPU.

Would like to have an option (off by default) to ignore individual files in untracked directories, which is the default behavior of `git status` with no arguments (equivalent to `-unormal`).

**Comment by lszomoru** [comment]
Fixed with https://github.com/microsoft/vscode/commit/29f9e514449e6332432fd96c1b8d8ea92c7c5ca9.
Though for the record, I am also looking at this pull request - https://github.com/microsoft/vscode/pull/136698

**Comment by lszomoru** [comment]
Verification steps:
- Launch VS Code, and open a folder/workspace that contains a git repository
- Open the Git output using the `Git: Show Git Output` command
- Switch to the "Source Control" viewlet, and press the action to "Refresh" the list of changes
- Look at the Git output and confirm that you see a `git status -z -uall` command being executed
- Open Settings and set the `git.untrackedChanges` setting to `hidden`
- Switch to the "Source Control" viewlet, and press the action to "Refresh" the list of changes
- Look at the Git output and confirm that you see a `git status -z -uno` command being executed
