### ISSUE TITLE
Hot Exit: Careful when you veto the shutdown from failing backups

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14074]
I notice that you seem to veto the shutdown if backups are failing, but you are not showing anything to the user. That is very tough to understand for a user why he cannot exit or close a window.

Suggest to add a message here or some handling from the backup service that should handle the shutdown phase.

**Comment by Tyriar** [comment]
It's currently the same as when saving regular files https://github.com/Microsoft/vscode/blob/4dc59b7e2a9c003e17d154023d47bd94a972694b/src/vs/workbench/services/textfile/browser/textFileService.ts#L172

It says this if there are no write permissions:

![image](https://cloud.githubusercontent.com/assets/2193314/19581475/16f9e74c-96e2-11e6-8de5-2afba6829343.png)

Considering how infrequent of an occurrence this would be I think the message is fine. VSCode probably wouldn't launch if the user data dir didn't have write access and disks don't fill up much. Am I missing some other big case where this could fail?

**Comment by bpasero** [comment]
@Tyriar my concern was more how discoverable this error message is for a user. I think the backup service (on the renderer side) should catch errors that happen and instead of bubbling the native error from the file service wrap it around some nicer wording so that as a user you understand that the backup is failing. This gives us also a better way to track bugs when people report this.

**Comment by Tyriar** [comment]
![image](https://cloud.githubusercontent.com/assets/2193314/19590071/c7e65184-9724-11e6-9886-425b85d1d4b0.png)

https://github.com/Microsoft/vscode/commit/a33a4baf5bc2b3f91509558439e77624a400a088

**Comment by bpasero** [comment]
Yup, better.
