### ISSUE TITLE
The `Refresh` button doesn't refresh on the **Extension View**

### ISSUE THREAD

**Issue by cateyes99** [microsoft/vscode#140794]
Does this issue occur when all extensions are disabled?: **_N/A_**

- VS Code Version: _**1.63.2** portable zip version_
- OS Version: _**Windows 10 Enterprise**, Version 20H2, OS Build 19042.1415_

Steps to Reproduce:
1. When you have **VSCode** opened already. Say there are **8** extensions having new updates.
<img src="https://user-images.githubusercontent.com/19678455/149642044-b8dd38bf-47cb-4e89-98ff-2b64ae6f0e4b.png" alt= "RefreshExtensions" width="60%" height="60%">

2. After that, if there is another extension having a new update becoming available, you open another **VSCode**, you notice that the number of extensions having updates available becomes **9** which is good.
<img src="https://user-images.githubusercontent.com/19678455/149642070-d37120c4-7ba4-4b43-ac57-bfb89b97060c.png" alt= "RefreshExtensions" width="60%" height="60%">

3. But on the 1st **VSCode** you opened earlier, mentioned in Step `1.`, you go to the `View: Show Extensions` by click <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>X</kbd>, it's still  **8**. Now click the Refresh button, notice that it **doesn't** refresh the extensions after it looks like doing some sort of refreshing, and the update available number is still **8** not **9**. No matter how many times to refresh the extensions, still nothing changes.
<img src="https://user-images.githubusercontent.com/19678455/149642111-cf71ae3f-d8f9-4caf-aab8-964e974759c3.png" alt= "RefreshExtensions" width="60%" height="60%">

I've observed this issue for months.

**Comment by hediet** [comment]
Are there easy reproduction steps without relaying on someone publishing an update?

**Comment by sandy081** [comment]
You can always go to the extension installation folder location and change the version attribute in the package.json to see the update.
