### ISSUE TITLE
taking size of array from user in c programming language

### ISSUE THREAD

**Issue by ROSHTU** [microsoft/vscode#140705]
Issue Type: <b>Bug</b>

int x;
    printf("Enter the size : ");
    scanf("%d",&x);
    // the below error is a bug in vs code it does not harm the functioning of the program
    bd b[x];

on writing the above given code i found out that a red line appears on x inbd b[x]; which denotes an error but on running the program it does not disrupts the functoning of the program

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (23.66GB free)|
|Process Argv|--crash-reporter-id 53e61994-1cd4-451a-a4ff-08743a6389ee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.2.2
code-runner|for|0.11.6
c-snippets|Har|1.3.1
better-cpp-syntax|jef|1.15.10
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.0-insiders2
cpptools-extension-pack|ms-|1.1.0
material-icon-theme|PKi|4.11.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710:30416614
vsccppwtstudy:30421978

```

</details>

**Comment by joyceerhl** [comment]
If you disable all extensions, do you still get the red line? If that causes the red line to disappear, please use the Help: Start Extension Bisect command to identify the extension that is flagging an error, and report this issue on that extension's issue tracker.

**Comment by ROSHTU** [comment]
> If you disable all extensions, do you still get the red line? If that causes the red line to disappear, please use the Help: Start Extension Bisect command to identify the extension that is flagging an error, and report this issue on that extension's issue tracker.

yes just found out an extension was causing this error , have reported the issue thanks
