### ISSUE TITLE
Support to fully exclude folder/project in multiple project workspace.

### ISSUE THREAD

**Issue by harpalsingh1993** [microsoft/vscode#140779]
When I open multiple(many) projects in the workspace, I don't work frequently on all of them. I can exclude those folders/projects in  Explorer(using settings/some extensions). And also I can exclude from search. But in SCM(I use git default) I can only disable those temporary when I restart VSCode it loads all projects in SCM.

It would be helpful if we have Folder/Project excluded from explorer, it also excludes the same from search and SCM. Or at least persists the SCM.

**Comment by gjsjohnmurray** [comment]
Closed repository state not being recorded and reloaded is mentioned in https://github.com/microsoft/vscode/issues/104151#issuecomment-672001440

/assign @lszomoru
