### ISSUE TITLE
Unable to customize Bracket Pair Colors

### ISSUE THREAD

**Issue by deepindersinghbti** [microsoft/vscode#140766]
I am using VS Code, version 1.63.2. I have built-in Bracket Pair Colorization enabled. I open settings.json, and I am trying to customize my colors for Bracket Pair Colorization.

  "workbench.colorCustomizations": {
    "editorBracketHighlight.foreground1": "#ff0000"
  },

The moment I make my changes and save the file, my customizations are automatically removed and the code changes to:

  "workbench.colorCustomizations": {},

(Which is the default setting).

Due to this, I am unable to customize my bracket pair colors. Please share some solution!

**Comment by IllusionMH** [comment]
/needsMoreInfo

It should not reset to empty object.
Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`
