### ISSUE TITLE
Show "Reopen closed tab" command in tabs context menu

### ISSUE THREAD

**Issue by rhalaly** [microsoft/vscode#140716]
It can be useful to open the latest closed file tab in the Explorer view.

**Comment by JacksonKearl** [comment]
Could you explain what you want in greater detail? We do provide the `View: Reopen closed Editor` command to reopen the latest closed editor.

**Comment by rhalaly** [comment]
Ah, I didn't know that this command exists. I was looking for it in the tabs context menu (as the browsers have). If it can be also there it will be awesome...

<img width="380" alt="image" src="https://user-images.githubusercontent.com/8597700/149565618-5e4773a2-83e8-4a65-ab64-84808cabd2f3.png">
