### ISSUE TITLE
shell integration does not work - zsh

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#140784]
but does on bash
![Screen Shot 2022-01-15 at 1 35 12 PM](https://user-images.githubusercontent.com/29464607/149635519-ea6d4112-f41b-4fad-b607-519490f728f3.png)

**Comment by rzhao271** [comment]
Now, shell integration gets activated for zsh on macOS, but I'm unable to run commands such as "Run recent command"

**Comment by meganrogge** [comment]
@rzhao271 have you updated to the latest? 

![Screen Shot 2022-01-27 at 1 22 49 PM](https://user-images.githubusercontent.com/29464607/151429098-90c2e037-f625-46bf-9a0d-453c07977668.png)

can you attach a gif? any warnings in the console?

**Comment by meganrogge** [comment]
@rzhao271 and I debugged this and found that `precmd` does not run. Running the script via `source script` in the terminal results in it working as expected.

**Comment by meganrogge** [comment]
He has zsh installed at `bin/zsh` whereas I have it installed at `/usr/local/bin/zsh`

**Comment by Tyriar** [comment]
It's a shame but let's defer, we can call out that there's a known issue with zsh in the release notes.

Also this is related to https://github.com/microsoft/vscode/issues/141620

**Comment by Tyriar** [comment]
Actually let's track this zsh problem in #141620, this original issue was about not wrapping the shell script in quotes which is definitely fixed.
