### ISSUE TITLE
Notebook editor progress bar disappears after switching editors

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#140753]
- Open a notebook
- Execute a cell and scroll it out of view so the editor progress bar appears
- Switch to another editor in the same group
- Switch back to the notebook
- The editor progress bar is gone

**Comment by roblourens** [comment]
@bpasero I think after https://github.com/microsoft/vscode/commit/51354ad23cbbd10d364ab031aba646a43c09be6c, I have to make the editor progress bar show up again after switching back to the notebook editor. Is that right? It's fine but wasn't what I expected.

**Comment by bpasero** [comment]
Yes, editors never supported progress to return when you return to the editor. So before this was broken in a way that progress would just continue to show for "wrong" editors and now it actually reflects the real way it is.
