### ISSUE TITLE
No origin info for completion and hover provider

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode#140774]
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Not sure if this is a bug or a missing feature:

I have implemented a completion provider in my extension.
Completions generally work and do show up like here (addStandardHeader):

![Bildschirmfoto 2022-01-15 um 14 58 10](https://user-images.githubusercontent.com/3081973/149624325-39d6a344-6dc6-47d8-928b-60152c0b9296.jpg)

E.g. for 'addAbortSignal', which is from some other extension, the source 'stream' can be seen.
For my extension it is missing. I would expect that the extension name is shown here.

Very similar is the behavior for my hover provider:

![Bildschirmfoto 2022-01-15 um 14 59 59](https://user-images.githubusercontent.com/3081973/149624378-17413256-a391-492c-a3c4-8eb395f6531f.jpg)

It shows the hover, but the title is 'any'. 
Here as well I would expect the extension name.

**Comment by jrieken** [comment]
The extension name rarely/never shows in the UI. For suggest, you can use the [CompletionItemLabel](https://github.com/microsoft/vscode/blob/f5ad06212dad13272d0de2451b803b30bb5ef831/src/vscode-dts/vscode.d.ts#L4016)-type, for hover it's just the returned MD string

**Comment by jrieken** [comment]
> OK, but where does the 'stream' or 'process' come from in the completion list:

It's the `CompletionItemLabel` that I have mention. 

> And how to get rid of the 'any' in the hover:

I don't know how puts that there and you have not provided enough information for me to know. Maybe your extension's HoverProvider or another extension that you have installed

**Comment by maziac** [comment]
>It's the CompletionItemLabel that I have mention.

Ah, OK. It's the 'detail' field. I have overlooked that.

For the hover:
You are right: I de-installed my extension and the 'any' is still there.
I misinterpreted before: I thought it was some kind of title.
Is there a way to tell which extension is responsible for the hover rather than disabling all?

**Comment by gjsjohnmurray** [comment]
> Is there a way to tell which extension is responsible for the hover rather than disabling all?

I recommend that you use the Start Extension Bisect command.
