### ISSUE TITLE
Git doesn't watch the correct remote path when using worktrees

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#140787]
When using Git worktrees, the `.git` folder is split over two different paths. The main repository's `.git` folder becomes the "common" Git directory (were all the "git" stuff continues to live), and a new "tracking" `.git` folder for the worktree lives in the main repository's `.git/worktrees/<worktree-name>`

These paths can be returned by running `git rev-parse --git-dir --git-common-dir`.

I will open a PR to fix this.

/cc @lszomoru

**Comment by joaomoreno** [comment]
Note that we never fully committed to supporting worktree: https://github.com/microsoft/vscode/issues/68038

**Comment by eamodio** [comment]
While worktrees expose this bug, it isn't a worktree specific thing. There are other ways to have a different git common dir and git dir. So this fix just accounts for that case. Again worktrees just exposes this issue, but the bug nor the fix are worktree related.

**Comment by lszomoru** [comment]
> There are other ways to have a different git common dir and git dir.

Could you also please illustrate other scenarios in which this can happen?
Any additional scenarios would be valuable data for us to prioritise this bug against other bugs in the git area. Thanks!

**Comment by eamodio** [comment]
Other than worktree's I'm not really sure of the use-case, but Git allows you to control the `$GIT_COMMON_DIR` environment var (https://git-scm.com/docs/git#Documentation/git.txt-codeGITCOMMONDIRcode) which will controls that behavior. So there may be other cases of value that I'm not aware of.

**Comment by eamodio** [comment]
I was just working on worktrees in GitLens last night and verified that this works in VS Code.

/verified
