### ISSUE TITLE
Allow for double equal signs to ==highlight text== in Markdown

### ISSUE THREAD

**Issue by aleksey-rowan** [microsoft/vscode#140732]
Allow for double equal signs to [==highlight text==](https://www.markdownguide.org/extended-syntax#highlight) in editor and preview views.

CommonMark standard doesn't include support for highlight, but some popular markdown editors are using double equal signs to show highlighting: [Typora](https://support.typora.io/Markdown-Reference/#highlight), [Obsidian](https://help.obsidian.md/How+to/Format+your+notes#Highlighting), [Quilt](http://tmthydvnprt.com/quilt/news/markdown_syntax.html), [Joplin](https://joplinapp.org/markdown/#plugins) and [iA Writer](https://ia.net/writer/support/general/markdown-guide).

```md
==highlight==
```

Roam also supports highlighting, but uses double carets instead of equals: `^^highlight^^`.

**Comment by mjbvz** [comment]
Our built-in markdown support targets [CommonMark](https://commonmark.org)

Highlighting with `==` looks like an extension to markdown so it's not something we would ship built-in. However support for this can be added by a vscode markdown extension: https://code.visualstudio.com/api/extension-guides/markdown-extension
