### ISSUE TITLE
Hot Exit: textFileServices.ts feedback

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14079]
Besides other feedback mentioned already (move backup logic into new backup service), there are some issues I noticed:

There is a public `backup()` method that does not seem to be used anywhere. 

doBackupAll() seems to be very complicated and possibly copied from another method. Do you need the source/target information really?

I do not understand this comment: `// Only remove the workspace from the backup service if it's not the last one or it's not dirty` 
Do we prevent hot exit for multiple windows with this check?

**Comment by Tyriar** [comment]
- [x] Remove public https://github.com/Microsoft/vscode/pull/14115
- [ ] Simplify `doBackupAll`

RE: the comments, yes it's disabled until https://github.com/Microsoft/vscode/issues/13305 is done

**Comment by bpasero** [comment]
Ok maybe update the comment and point to the issue, it is very hard to understand whats going on from just reading it.

**Comment by bpasero** [comment]
I think this is much better now?
