### ISSUE TITLE
Menu paramètre

### ISSUE THREAD

**Issue by Spiti-gaming** [microsoft/vscode#140791]
Issue Type: <b>Bug</b>

Erreur lors du changement de catégorie du menu paramètre : 
Cannot read property 'lastIndexOf" of undefined

VS Code version: Code - Insiders 1.64.0-insider (c6e58d126f6b5676242e32b34180b2a595f29b51, 2022-01-14T05:19:33.429Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.95GB (6.58GB free)|
|Process Argv|--crash-reporter-id d8dc8ac2-9b7e-458c-a883-eec9eaa6fb1c|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|12.4.0
vscode-django|bat|1.8.0
gitignore|cod|0.7.0
git-extension-pack|don|0.1.3
githistory|don|0.6.19
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
vscode-great-icons|emm|2.1.79
discord-vscode|icr|5.7.0
vsc-python-indent|Kev|1.14.2
MagicPython|mag|1.1.0
git-graph|mhu|1.30.0
theme-monokai-pro-vscode|mon|1.1.19
vscode-language-pack-fr|MS-|1.64.3
csharp|ms-|1.23.17
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.1
jupyter|ms-|2022.1.1001614873
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
cpptools|ms-|1.7.1
vsliveshare|ms-|1.0.5242
autodocstring|njp|0.5.4
python|tht|0.2.3
vscode-decompiler|tin|0.0.8
vscodeintellicode|Vis|1.2.15
vscode-icons|vsc|11.8.0
jinja|who|0.0.8
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30421239
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30421357
vscop804cf:30404767
vs360:30404995
vsclayoutctrt:30405800
azactmsal:30409287
vsccppwtstudy:30421978

```

</details>

**Comment by sbatten** [comment]
@Spiti-gaming can you share a screen recording of your issue?

**Comment by Spiti-gaming** [comment]
Sorry for the time to respond, after an update that issue was resolved.
