### ISSUE TITLE
Writing login information to the keychain failed with error 'The specified item could not be found in the keychain.'.

### ISSUE THREAD

**Issue by philipbeber** [microsoft/vscode#140721]
Does this issue occur when all extensions are disabled?: Don't know

- VS Code Version: Version: 1.63.2 (Universal)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0

- OS Version: macOS Monterey 12.1

Steps to Reproduce:

About once a week when I unlock my computer in the morning VS code is unusable.
1. It continually pops up a toast with the error message in the title
2. Files can be edited but not saved (nothing happens when pressing save)
3. "Report an issue" does not work (just shows a gray screen)
4. Exiting does nothing, I have to Force Quit VS Code
5. Of course, any unsaved changes are then lost
6. All VS Code windows are affected

It's hard to reproduce since it only happens after the computer has been idle overnight, so I'm not sure if it's caused by an extension.

Thanks!

**Comment by TylerLeonhardt** [comment]
Sorry to hear that! This doesn't seem to be scoped to auth but all of vscode seems to go sideways.

I noticed you're using the Universal macOS app. Although they _should_ be the same, I wonder if you get the same behavior with the regular install?

**Comment by b0s0z0ku** [comment]
Hi!
Same error for me on Kali Linux 2021.4 with VScode v1.63.2 when using GitHub authentication for syncing.

Linux kali 5.15.0-kali2-amd64 #1 SMP Debian 5.15.5-2kali2 (2021-12-22) x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/78355570/151429094-07ca7cc8-eead-4092-bd1a-8ba226440438.png)

**Comment by TylerLeonhardt** [comment]
@b0s0z0ku that's a different error and that one usually means you need `gnome-keyring`. I'm not sure what the steps are to setting up `gnome-keyring` properly on Kali since I don't have a lot of experience with that distro, but installing it and setting it to unlock the Login key ring when you unlock your machine should be the way to go to get this working.
