### ISSUE TITLE
terminal link path separator should use backend os

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#140748]
Guess this was an existing bug, but this needs to be the backend's OS, not the frontend

_Originally posted by @Tyriar in https://github.com/microsoft/vscode/pull/140676#r785024730_

**Comment by Tyriar** [comment]
Bad link but it was this comment:

![image](https://user-images.githubusercontent.com/2193314/207706684-2c5f292e-c824-4401-bc4f-6e5bf9322541.png)

I don't see references to `isWindows` in the links folder anymore so closing off.
