### ISSUE TITLE
Assign shortcuts from the command pallete

### ISSUE THREAD

**Issue by batsking** [microsoft/vscode#140783]
Jetbrains IDEs have this neat feature - 
When you are searching for a command in the command pallete, you can press alt+enter to instantly assign it to a keyboard shortcut. 

<img width="512" alt="image" src="https://user-images.githubusercontent.com/97805786/149635034-b6d3b347-5864-4cfc-888c-85c475fd80e5.png">

I think it would be very useful in vs code.

**Comment by ArturoDent** [comment]
When you hover a command in the Command Palette click on the Gear Icon that appears to the right.  That will take you to the command in the Keyboard Shortcuts editor with only that command.  Then click on the `+` sign to its left and you can enter a keybinding into the input box that appears.
