### ISSUE TITLE
MenuBar impossible to launch with Alt key on Ubuntu

### ISSUE THREAD

**Issue by brzuchal** [Microsoft/vscode#14077]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:43:46.054Z)
- OS Version: Linux x64 4.4.0-42-generic, Ubuntu 16.04
- Extensions: alefragnani.Bookmarks-0.9.2, alefragnani.numbered-bookmarks-0.5.0, donjayamanne.githistory-0.1.0, ms-vscode.cpptools-0.9.2, waderyan.gitblame-1.3.0

Steps to Reproduce:

1. Install on Ubuntu
2. Enter the `Alt` key which opens system menu bar

Since Ubuntu has integrated global menu there is natural that `Alt` keybinding opens search bar to find and execute commands. VSCode has own menu bar which I cannot launch using `Alt` keybinding and am unable to chenge that keybinding.

**Comment by roblourens** [comment]
I see that 'alt' isn't configurable

**Comment by bpasero** [comment]
@brzuchal if it reproduces with the Atom editor then it seems like an Electron issue that should be reported to https://github.com/atom/electron

**Comment by brzuchal** [comment]
@bpasero I don't know and don't have Atom

**Comment by bpasero** [comment]
@brzuchal you could download it from https://atom.io/

**Comment by brzuchal** [comment]
What for?

**Comment by bpasero** [comment]
@brzuchal to find out if this issue is caused by Electron (the framework that Atom and VS Code are using). I find it unlikely that this is something we can control. So if it reproduces with Atom you should report this against Electron itself.

**Comment by brzuchal** [comment]
@bpasero AFAIK Electron is a framework to create such apps, that would require from me to prepare whole app in this framework. I'm using VSCode co reporting an issue where it stands on. I don't care what internally is used in VSCode, that should not be in my interest to do the job instead of authors of VSCode.

**Comment by bpasero** [comment]
I cannot reproduce with Ubuntu 15:

![editors](https://cloud.githubusercontent.com/assets/900690/19620342/c26006e4-987b-11e6-8845-31dd663347b2.gif)

**Comment by brzuchal** [comment]
@bpasero You've missunderstood the problem, system menu bar in Ubuntu isn't a problem. The problem is with MenuBar (the option Toggle MenuBar in global menu) it opens MenuBar and says that it's always accessible with an `Alt` keybinding, but on Ubuntu actually is not because `Alt` is binded with global menu and there is no way to redefine this keybinding (That from Toggle MenuBar)

**Comment by brzuchal** [comment]
Whait a moment I was thinking this is the menu bar where can write commands like bookmark etc.

**Comment by brzuchal** [comment]
Ahhhhh sorry I was thinking this is an activator for *Command pallette...*
