### ISSUE TITLE
Can't close a file without saving changes

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#1407]
How to reproduce:

1 .open a file
2. modify it (don't save your modifications)
3. right-click on the file and select "Close File"
4. choose "Don't Save" in the dialog that appears

The file won't be closed.

Worse: you cannot exit Code or open a new folder if you have unsaved modifications.

If you do that, the same dialog asking weather you want to save your changes, if you choose "Don't Save", nothing happens, and Code won't open the new folder.

This happens with Code 0.10.4 on Win 10 (x64).

**Comment by stkb** [comment]
Can't find the original issue now but this has already been fixed in master. The actions of the ```Don't Save``` and ```Cancel``` were accidently switched. For now, you have to click "Cancel" instead :)

**Comment by warpdesign** [comment]
I see, thanks! I guess this will make it into final 0.10.4 ?

**Comment by dbaeumer** [comment]
@bpasero another dup :-)

**Comment by bpasero** [comment]
True...
