### ISSUE TITLE
vscode freezes when left unattended for a period of time

### ISSUE THREAD

**Issue by TribalCoder** [microsoft/vscode#140754]
Issue Type: <b>Bug</b>

Window workstation was locked.

After leaving vscode for a period of time (approximately 1.4 hour), I come back to vscode it is frozen (unresponsive). I've seen this happen for the terminal and for scrolling a code window (markdown, at the time).

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (13.24GB free)|
|Process Argv|--crash-reporter-id 7cd011b7-6da3-4a74-b15e-ac634b1b8451|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.0
dart-code|Dar|3.32.0
flutter|Dar|3.32.0
vscode-eslint|dba|2.2.2
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
vscode-wasm|dts|1.3.1
prettier-vscode|esb|9.1.0
vscode-jest-runner|fir|0.4.47
kotlin|fwc|0.2.23
copilot|Git|1.7.4608
go|gol|0.30.0
terraform|has|2.18.0
vsc-python-indent|Kev|1.14.2
MagicPython|mag|1.1.0
Kotlin|mat|1.7.1
vscode-docker|ms-|1.18.0
csharp|ms-|1.23.17
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
hexeditor|ms-|1.9.3
powershell|ms-|2021.12.0
vsliveshare|ms-|1.0.5242
autodocstring|njp|0.5.4
rust|rus|0.7.8
code-spell-checker|str|2.1.4
cmake|twx|0.0.17
shell-launcher|Tyr|0.4.1
jinja|who|0.0.8
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710:30416614
vsccppwtstudy:30421978

```

</details>

**Comment by TribalCoder** [comment]
Yes. Vscode starts working again after restarting. Sent from Mail for Windows From: Iswar MondalSent: Friday, January 14, 2022 7:29 PMTo: microsoft/vscodeCc: TribalCoder; AuthorSubject: Re: [microsoft/vscode] vscode freezes when left unattended for a period of time (Issue #140754) Does it becomes functional after restarting the IDE?—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by iswarmondal** [comment]
I'm not sure why this is happening, maybe the moderators can help. 
Hey, @deepak1556 I would be very happy to work on it, can we discuss why this might be happening

**Comment by deepak1556** [comment]
@TribalCoder when the unresponsiveness happens, can you able tab into other open applications and tab back to vscode instance and see if the problem continues. Thanks!

**Comment by TribalCoder** [comment]
Not sure. I’ll keep an eye out if/when it happens again. Sent from Mail for Windows From: RoboSent: Tuesday, February 1, 2022 8:31 AMTo: microsoft/vscodeCc: TribalCoder; MentionSubject: Re: [microsoft/vscode] vscode freezes when left unattended for a period of time (Issue ***@***.*** when the unresponsiveness happens, can you able tab into other open applications and tab back to vscode instance and see if the problem continues. Thanks!—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by TribalCoder** [comment]
Hi, I just had vscode freeze up. And I tabbed away and tabbed back and vscode freed up (became responsive again). Best,Martin Sent from Mail for Windows From: RoboSent: Tuesday, February 1, 2022 8:31 AMTo: microsoft/vscodeCc: TribalCoder; MentionSubject: Re: [microsoft/vscode] vscode freezes when left unattended for a period of time (Issue ***@***.*** when the unresponsiveness happens, can you able tab into other open applications and tab back to vscode instance and see if the problem continues. Thanks!—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by deepak1556** [comment]
Side effect of the occlusion tracker

Merging to https://github.com/microsoft/vscode/issues/123257

**Comment by lorand-horvath** [comment]
@deepak1556 I confirm this issue, but in my case, the VSCode terminal freezes and/or text inside it disappears, if computer left unattended for a while. Noticed this in 1.66.x, so it might be related to aggressive occlusion tracker in Electron/Chromium, as you said https://github.com/microsoft/vscode/issues/146737#issuecomment-1111839499
