### ISSUE TITLE
Connected my Github to my VS Code in Ubuntu, and now Python won't debug.

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#140759]
The problem is the same as here https://github.com/microsoft/vscode/issues/123881 but you marked it as solved. Shutting down conversations about problems might make you feel like you are being more productive, but you aren't. 

"That one should be fixed in insiders and should be available in the next stable in 1 month" isn't a solution, especially when you don't leave the conversation open to discussion for when the update happens. What do you gain by making me have to resubmit a problem that someone else has already expressed? This kind of practice makes me want to use Notepad++.

VSCode was working fine, Ctrl + F5 would debug and run my script, I connect Github repo and loaded my script (same one I just ran locally), and now I get an error.

![image](https://user-images.githubusercontent.com/94647125/149608315-0bfacd74-721a-4318-aca9-3d7ff286050f.png)

"You don't have an extension to run Python. Should we find a Python extension in the Marketplace?" I click the "Find Python extension" button, and the extension is installed with an caution error icon that states "Only partial intelliSense supported".

![image](https://user-images.githubusercontent.com/94647125/149608649-d1eb89dc-1ab8-444a-b594-1d9746fcbfb0.png)

Websearch found this documentation that states possible causes, but no solution https://github.com/microsoft/vscode-python/wiki/Partial-mode .

I've uninstalled/reinstalled the extension, and tried a system reboot. Github has obviously changed a setting someplace when I granted it access, as it never installed/uninstalled anything to my knowledge. 

I've been coding for years, used to use Visual Studios. Really trying to give VS Code and Github a chance, but you make me want to uninstall and go back to a simple text editor and CLI.

Treating forums like tickets, and shutting down the conversation whenever you like, is counter-productive and not beneficial. I just can't understand why people don't see the problem with this, it's a waste of everyone's time and contribution, segmenting important information to solve common problems into hundreds of tickets with the same keywords and redundancies. Search engines ignores these multiple search results, only populating a handful in favor of advertisements, blogs, news, and any number of other things.

Using Ubuntu 20.04 LTS, downloaded VS Code from the Ubuntu Software Store.

![image](https://user-images.githubusercontent.com/94647125/149609436-38997de7-db21-40a8-837c-6eec3ab9dcd8.png)

Update: Reinstalling VS Code did nothing, going to uninstall and try to delete user config files, and reinstall, but I doubt it will fix it.

**Comment by PrivacyAddress** [comment]
Uninstalled, ran `cd .vscode/`, than `sudo rm -fr extensions/` and `sudo rm -fr argv.json`, and reinstalled, did nothing.

**Comment by weinand** [comment]
@PrivacyAddress What do you mean by "I connect Github repo"?
Please provide reproducible steps.

**Comment by PrivacyAddress** [comment]
"You can find more information about how to submit good bug reports in the VS Code wiki: https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions"

What is my time worth? I am taking my time to write you in regard to a problem with your application, and you are unhappy with my formatting? You are getting free troubleshooting help, be grateful. Their was a time when you corporations had to pay people to do this testing.

Why shouldn't I just uninstall and use PyCharm? Wanting me to spend my time helping you fix your application, for free...

I installed one of these

![image](https://user-images.githubusercontent.com/94647125/149639663-0c6d3b4e-352a-4c33-a98d-da44fc491b6f.png)

I think it was this one

![image](https://user-images.githubusercontent.com/94647125/149639713-e2777916-49c0-4a17-a35b-4d9fabfc5e67.png)

and it asked me to grant it permission by logging in, I did, and it stopped working.

I can't recreate it, as the prompt to grant access was automated, and I don't know how to trigger it.

You aren't the only one that needs more information, your application sucks, and doesn't provide any additional information.

I don't know why I expected anything else from Microsoft.

Your application has a bug, and you are welcome for me taking my time to write you. 

Look at how many tickets end this way "NeEd MoRe InFoMaTiOn". I won't be replying.
