### ISSUE TITLE
Jump to line+column in terminal links (format `<path> l:c`)

### ISSUE THREAD

**Issue by strarsis** [microsoft/vscode#140780]
It is possible with VSCode to follow a path printed in the terminal.

When that path also contains the line and column number in the format `<path> l:c` (`l` ≙ line number; `c` ≙ column number),
VSCode currently doesn't interpret it completely and therefore doesn't also jump to the line/column in the opened file.

Example:
````
resources/styles/blocks/cover/rhombus.scss 49:46
````
This path format indicates the path to the file but also the line (49) and column (46) number.

Ctrl + clicking this path currently in VSCode will open the file but not jump to the line or the column.

As this format is used by many linters and compilers (e.g. SASS), it would be a very useful and time-saving feature.

**Comment by Tyriar** [comment]
Code link:

https://github.com/microsoft/vscode/blob/95a0e2b859aff1f5f3e6300a8d70aa813608da64/src/vs/workbench/contrib/terminal/browser/links/terminalValidatedLocalLinkProvider.ts#L35-L44

I think here we'd want to require the exact (num)(colon)(num) to prevent problems with (link) (number) (text)

**Comment by tjx666** [comment]
nice feature for many front end build tools.

**Comment by ssigwart** [comment]
I added PR #153957 for this.
