### ISSUE TITLE
Our `vscode.d.ts` does not enforce `class` types

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#140771]
I know this train has possibly left the station but anyway: I was caught by surprise that given an API such as:

```ts
getCells(range?: NotebookRange): NotebookCell[];

export class NotebookRange {
...
}
```

An extension can do this:

```ts
vscode.workspace.notebookDocuments[0].getCells({ end: 4, isEmpty: false, start: 3, with: undefined! });
```

I.e. the type that is passed into `getCells` is actually not a `class`. But when implementing the API, we might do `instanceof` checks that are then invalid because the thing passed in is an object and not a `class`.

Given we can probably not change this for backwards compatibility, I think we somehow need tooling that ensures every `class` thing that enters the system from am extension is being converted to be a real `class` and not used as is.

**Comment by jrieken** [comment]
That's how TypeScript works, I am not happy with it and didn't manage to convince them (years, years back)

**Comment by jrieken** [comment]
See https://github.com/microsoft/TypeScript/issues/8168
