### ISSUE TITLE
Directly creating a terminal in a group editor

### ISSUE THREAD

**Issue by cognominal** [microsoft/vscode#140712]
Directly creating a terminal in a group editor.
Creating it in the terminal panel, moving it, then closing the terminal 
panel is too indirect.

**Comment by IllusionMH** [comment]
There are existing commands in Command palette(<kbd>F1</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>): `>Terminal: Create New Terminal In Editor area` and `>Terminal: Create New Terminal In Editor area to the Side`

You can assign key bindings for them as well.

**Comment by IllusionMH** [comment]
@Tyriar maybe it make sense to add Create New Terminal In Editor area to the Terminal section of Main menu?

**Comment by Tyriar** [comment]
@IllusionMH the thinking was if someone wants to use editor terminals a lot they would set `"terminal.integrated.defaultLocation": "editor"`

**Comment by cognominal** [comment]
I missed the obvious. 
But the discussion was enlightening.
I should have said I am trying to do everything from the keyboard, so I don't use the main menu even if on my Mac I could access it with shift cmd /
So IllusionMH suggestion may be very good but is irrelevant to me.
But the setting proposed by Tyriar seems promising.
Thanks everyone.
