### ISSUE TITLE
GlobPattern#from is spec'd wrong

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#140707]
The [`GlobPattern#from`](https://github.com/microsoft/vscode/blob/e3cf7e5e1bc93824ed84bb960c3f86f89450ab36/src/vs/workbench/api/common/extHostTypeConverters.ts#L1386) is slightly bogous because its return type is also an API type, instead it should return 'IRelativePattern' or, if needed, a specific DTO-type. Also, recent changes to `RelativePattern` (getter) cause it to not serialise correctly anymore

**Comment by jrieken** [comment]
pushed https://github.com/microsoft/vscode/commit/fde8aca38e189e56d30984a4798a04f3966dbb42 as a workaround

**Comment by bpasero** [comment]
@jrieken yeah total mess. https://github.com/microsoft/vscode/pull/140689 should fix it, also the questionable handling of notebooks. Only the language selector was doing fine because it does not rely on the URI it seems.
