### ISSUE TITLE
"Go To File" doesn't work when there's a custom file scheme in the workspace

### ISSUE THREAD

**Issue by shati-patel** [microsoft/vscode#140737]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2 (commit 899d46d82c4c95423fb7e10e68eba52050e30ba3) 
  - Also checked on 1.64.0-insider (commit 753319a08f8e74700b1dba3a29bf0a6af7c2953f)
- OS Version: Windows_NT x64 10.0.19042

### Summary

👋🏽  I'm a maintainer of the [CodeQL extension](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-codeql). We implement a custom file system provider for the `codeql-zip-archive` scheme: https://github.com/github/vscode-codeql/blob/0e6d85374f31cddf33ed2ab9049168e8b47edf7c/extensions/ql-vscode/src/archive-filesystem-provider.ts#L293

Recently, users have reported that whenever there's a `codeql-zip-archive` in the workspace, the "Go To File" `Ctrl`/`Cmd`+`P` search no longer works. Removing the `codeql-zip-archive` fixes the search:

![040CDF41-F7A6-4F0B-BA93-292E7D205686](https://user-images.githubusercontent.com/42641846/149416154-f92dce9e-17f1-4b34-bc69-4fe7389276e2.GIF)

### Steps to reproduce

These are the steps to reproduce in the CodeQL case (though I suspect the problem exists for other custom file schemes too): 
1. Install the [CodeQL extension](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-codeql) and run command "CodeQL: Download Database from LGTM"
2. Enter a valid URL/slug (e.g. "`g/github/codeql`")
3. Once the database is downloaded and added to the workspace, `Ctrl`/`Cmd`+`P` should hang
4. Remove the database (i.e. the `codeql-zip-archive`) from the workspace to fix

Some users have had similar problems with "Search in Files" `Ctrl`+`Shift`+`P` search. I haven't been able to reproduce this consistently, but expect it would be related 🙂

### Debugging ideas

_Originally from https://github.com/github/vscode-codeql/issues/1068#issuecomment-1006152670:_

In the case where there's a `codeql-zip-archive` in the workspace, the VS Code console (in Developer Tools) emits the warning
```
No search provider registered for scheme: codeql-zip-archive, waiting
```

That message is logged [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/search/common/searchService.ts#L212), where it looks like VS Code dispatches the file search to separate providers for each scheme. It won't return results until all providers give back a response, even if there's no search provider registered for a scheme.

Manually inserting a dummy provider in the context of that function (in the Console) with
```js
this.registerSearchResultProvider("codeql-zip-archive", 0, {
  textSearch: function(q, o, t) { return null; },
  fileSearch: function(q, t) { return null; },
  clearCache: function(s) { return null; }
})
```
fixes the issue temporarily. Screenshot for clarification:

![image](https://user-images.githubusercontent.com/42641846/149552840-b883d990-7297-4364-967d-f74c570be2d0.png)

We currently don't have a way to fix this in our extension code, so I wonder if this is a bug in VS Code itself?

There's a proposed [`fileSearchProvider`](https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.fileSearchProvider.d.ts) API which might let us add such a dummy provider ourselves, but we wouldn't be able to publish our extension using a proposed API.

Please let me know if I can provide more information! 😊

**Comment by gjsjohnmurray** [comment]
@roblourens commented on a similar issue at https://github.com/microsoft/vscode/issues/139172#issuecomment-1002276280

**Comment by gjsjohnmurray** [comment]
Looks like a 1.63 regression from 5993f56abe1701d6cc0f71520a93fe5951383c32

**Comment by roblourens** [comment]
Thanks @gjsjohnmurray. Let me take a look at https://github.com/microsoft/vscode/issues/139172
