### ISSUE TITLE
I can't cancel column select mode. I tried restarting vscode, restarting my pc, even re-installing vscode, but it still in column select mode.  The vscode version is 1.63.0. Is there anyone who can help me to solve this problem

### ISSUE THREAD

**Issue by Kestcon** [microsoft/vscode#140758]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.63.0 & 1.62.3
- OS Version: win 7

Steps to Reproduce:

1.
2.

**Comment by abhijitchikane** [comment]
Click on the 'selection' menu on the top bar
then click on the 'column selection mode'

**Comment by abhijitchikane** [comment]
Click on the 'selection' menu on the top bar
then click on the 'column selection mode'

**Comment by Kestcon** [comment]
> Click on the 'selection' menu on the top bar then click on the 'column selection mode' ![image](https://user-images.githubusercontent.com/50770619/149632872-426fd62d-8058-4aee-b6bc-cd9c8fcf1898.png)

Thanks, i'm a new user of vscode.
