### ISSUE TITLE
Python Function collapse not functioning as intended.

### ISSUE THREAD

**Issue by marckeelingiv** [microsoft/vscode#140741]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.63.2
- OS Version: Windows_NTx64 10.0.19044

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/32782256/149587920-74c0d452-e6d4-4cb4-b68a-2a56e7ffa20d.png)

**Comment by aeschli** [comment]
This issue needs to be filed against 
https://github.com/Microsoft/vscode-python/issues
Would you mind filing the issue there?
