### ISSUE TITLE
Active indicator is misaligned on Windows in maximized mode

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#140723]
Related to #140647

![image](https://user-images.githubusercontent.com/35271042/149555507-7a29180a-3638-49a6-9689-dcefc8c7c8b6.png)

![image](https://user-images.githubusercontent.com/35271042/149555519-88f4db36-0710-4290-a685-67a259828ea9.png)

(screenshots are hard to see but there is a gap between the active indicator in the explorer)

When in maximized mode on Windows, the windowless px is gone and the indicator gets mis-aligned. We need a way to not let the indicator misalign in maximized mode so we'll look at toggling a class when in maximized mode.

cc @sbatten

**Comment by sbatten** [comment]
added class with https://github.com/microsoft/vscode/commit/050dd097021d4ab9ab6e294922702b62a8005ecd

**Comment by misolori** [comment]
For verification: verify that there is no gap between the active indicator in the activity bar while in maximized mode
