### ISSUE TITLE
No syntax highlighting after CData? (screenshot)

### ISSUE THREAD

**Issue by alnorris** [Microsoft/vscode#14072]
- VSCode Version: 1.6.1 (1.6.1)
- OS Version: OSX 10.11.6 (El Capitan)

Steps to Reproduce:

See screenshot
[
<img width="868" alt="screen shot 2016-10-20 at 10 41 17" src="https://cloud.githubusercontent.com/assets/882627/19554778/01f016a8-96b2-11e6-8dc1-cde2150c5b8c.png">
](url)

**Comment by waderyan** [comment]
@alnorris thank you for opening this issue. We have put a lot of work to improve the JS / TS grammar. Can you install this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar)? This is in beta right now and we are gathering feedback. Once it is stable we will ship with it in product.

**Comment by mjbvz** [comment]
Please try out VSCode 1.7+ which includes the new TS/JS grammar:

![screen shot 2016-11-18 at 3 44 18 pm](https://cloud.githubusercontent.com/assets/12821956/20450481/ced20d20-ada5-11e6-9964-e907a760a3f0.png)

If you still see this issue, please let me know and we will investigate further. Thanks.
