### ISSUE TITLE
Window hang when stopping test run

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#140745]
- Run "Debug all tests"
- Click stop halfway through
- Window stops responding for awhile

![image](https://user-images.githubusercontent.com/323878/149595782-75fc29ee-e697-403c-ac59-b41f0bf6c3a5.png)
[profile.json.txt.zip](https://github.com/microsoft/vscode/files/7873682/profile.json.txt.zip)

**Comment by connor4312** [comment]
Owch

**Comment by connor4312** [comment]
I wasn't able to hit a case quite this pathological with a 50 second pause, but I optimized away what was eating up lots of time in the profile (and about 500ms locally) so it should be a lot better.
