### ISSUE TITLE
Visibility property when set to hidden for the tree view is not working.

### ISSUE THREAD

**Issue by sreeharshakakani** [microsoft/vscode#140725]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.63.2
- OS Version: MacOS Big Sur Version: 11.5.2

Steps to Reproduce:

1. Cloned the tree-view-sample vscode extension repo : [tree-view-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/tree-view-sample) 
2. Added visibility property as hidden here in the view  : [https://github.com/microsoft/vscode-extension-samples/blob/main/tree-view-sample/package.json#L50](view) and in here in the explorer : [explorer](https://github.com/microsoft/vscode-extension-samples/blob/main/tree-view-sample/package.json#L61)
2. Run these commands : npm install
3. npm run watch
4. F5 to start debugging

The view is not getting hidden upon adding the visibility property for both view and in the explorer. Added the screen gif for the validation below.

https://user-images.githubusercontent.com/96312934/149557071-cf2802e6-ebbb-4b31-b896-67ac64b4057c.mov

**Comment by vickyvishal** [comment]
Also happens the same when `visibility: collapsed ` in contribution -> views

**Comment by sreeharshakakani** [comment]
> Also happens the same when `visibility: collapsed ` in contribution -> views

yeah, It's happening the same with all the properties of visibility.

**Comment by alexr00** [comment]
The `visibility` property only applies if the user hasn't taken any collapse/expand/hide action on the view already. This is intentional, as we never want to mess with user choices for the view.
