### ISSUE TITLE
File nesting increases time to render directories with many nests

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#140883]
#6328

https://github.com/JacksonKearl/explorer-nesting-stress-test

`xl/nested` takes much longer to render with file nesting enabled. Impact is lessened by disabling file nest auto-expansions. 

`xl/flat` is not significantly slower to render with nesting, though I have not collected proper numbers yet.

**Comment by JacksonKearl** [comment]
\closedWith 563785ea74c34a1370147f673c2ffa6a85fcf86c

**Comment by joyceerhl** [comment]
`xl/nested` takes a comparable amount of time to render with file nesting enabled, though there is a perceptible delay for both. However, I do also notice that the window becomes intermittently unresponsive after expanding `xl/nested`. Is this known?

**Comment by JacksonKearl** [comment]
Yeah, same thing happens with nesting disabled. There's an open issue somewhere for ways to reduce that (like streaming the dir contents).
