### ISSUE TITLE
Unable to drop dirty untitled editor to target window if untitled exists

### ISSUE THREAD

**Issue by hrayr1996** [microsoft/vscode#140898]
We have written the needed 
Issue Type: <b>Bug</b>

Opened two windows of VS Code. One window has 7 tabs and the other only one(unsaved) tab. Try to move a tab from the only tab window to the window with many tabs.

Expected: Tab moved to the other window and window left with no tab is closed or remain with no tabs.
Actual result: Moves first tab of window with many tabs to the place I made a drop and the main tab stood where it was.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
Environment: Windows 11 Home 21H2 build 22000.434 
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (1.07GB free)|
|Process Argv|--crash-reporter-id ca386ca7-fc1c-4fe5-894a-e21ef0178ac4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
remotehub|Git|0.20.0
vscode-sshfs|Kel|1.24.1
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-sftp|sun|1.1.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710:30416614
vsccppwtstudy:30421978

```

</details>

**Comment by bpasero** [comment]
This could be a setting but we cannot really change this, given most users probably by now expect the current behaviour?

**Comment by hrayr1996** [comment]
https://user-images.githubusercontent.com/55699544/150083855-02501f51-ff98-4984-a2ec-59d4b8cb0037.mp4

**Comment by hrayr1996** [comment]
Opened new window using `CTRL+SHIFT+N`.
Opened new tabs using `CTRL+N`.

**Comment by bpasero** [comment]
Ok, this seems to be limited to when the target window already has the untitled file opened (i.e. moving `Untitled-1` to a window that has `Untitled-1` as well).

**Comment by bpasero** [comment]
Dragging a untitled editor with contents to another window will now ensure that the resource URI is not being transferred, rather a new untitled file is enforced and that will ensure that the contents restore too.

**Comment by rchiodo** [comment]
/verified

Dragging tab keeps contents
