### ISSUE TITLE
Output in the terminal is not shown correctly

### ISSUE THREAD

**Issue by niwram5** [microsoft/vscode#140815]
Issue Type: <b>Bug</b>

I've created a non-project file called "test123.java" and I've written the following code:

public class test123 {
    public static void main(String[] args) {
        Test1 eins = new Test1();
        Test1 zwei = new Test1();
        Test1 drei = new Test1();
        System.out.println(eins);
        System.out.println(zwei);
        System.out.println(drei);
    }
}

class Test1 {

}

Now I run the code a few times and I get the following output in the terminal:

Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Lernen Sie das neue plattformübergreifende PowerShell kennen – https://aka.ms/pscore6
st123'
Test1@4617c264
Test1@36baf30c
st123'
Test1@4617c264
Test1@36baf30c
Test1@7a81197d
PS C:\Users\Marwin>  & 'C:\Program Files\Java\jdk-17.0.1\bin\java.exe' '--enable-preview' '-XX:+ShowCodeDetailsInExceptionMessages' '-cp' 'C:\Users\Marwin\AppData\Local\Temp\vscodesws_9a9ac\jdt_ws\jdt.ls-java-project\bin' 'test123'
Test1@4617c264
Test1@36baf30c
Test1@7a81197d
PS C:\Users\Marwin>  & 'C:\Program Files\Java\jdk-17.0.1\bin\java.exe' '--enable-preview' '-XX:+ShowCodeDetailsInExceptionMessages' '-cp' 'C:\Users\Marwin\AppData\Local\Temp\vscodesws_9a9ac\jdt_ws\jdt.ls-java-project\bin' 'test123'
Test1@4617c264
Test1@36baf30c
Test1@7a81197d
PS C:\Users\Marwin>

So what you see is that the newest outputs are correct. But the older outputs (I had to scroll up to see them again) are not correct anymore. Why is that? Could that be a bug?

Kind regards

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1400 Quad-Core Processor            (8 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (10.41GB free)|
|Process Argv|--crash-reporter-id ca72abcd-b4ed-4fee-b969-c540046011d7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-de|MS-|1.63.3
java|red|1.2.0
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30421290
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710cf:30416617
vsccppwtstudy:30421978

```

</details>

**Comment by meganrogge** [comment]
What do you mean by "not correct"?

**Comment by niwram5** [comment]
Thank you for the question. You can see in my code that I wrote three times "System.out.println();". So when I run the code, normally I should get three different Strings. In the newest runs of the code there is shown:

Test1@4617c264
Test1@36baf30c
Test1@7a81197d

=> everything is correct

But in the oldest run of the code there is shown:

Test1@4617c264
Test1@36baf30c

=> that's not correct

So, you can see that I always run the same code but the output in the oldest one is shown differently.

**Comment by meganrogge** [comment]
does resizing the terminal fix it?

**Comment by niwram5** [comment]
No, unfortunately that doesn't fix it.

**Comment by meganrogge** [comment]
Please provide a gif of this as I can't reproduce
