### ISSUE TITLE
output Error

### ISSUE THREAD

**Issue by vinnywalker** [microsoft/vscode#140818]
Issue Type: <b>Bug</b>

Not able to type anything

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.11.0-46-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A4-9125 RADEON R3, 4 COMPUTE CORES 2C+2G (2 x 2492)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 3, 3|
|Memory (System)|3.71GB (0.12GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 3831243b-eb4a-47d5-9f3d-7116ac1ade94|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.0
jshint|dba|0.11.0
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
vscode-firefox-debug|fir|2.9.6
vscode-pull-request-github|Git|0.34.3
beautify|Hoo|1.5.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.1
jupyter|ms-|2021.11.1001550889
ruby|reb|0.28.1
vim|vsc|1.21.10
vscode-ruby|win|0.28.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30416617
vsccppwtstudy:30421978

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by sergiojunene** [comment]
It’s happening to me only with files. md, I don’t think it’s an extension because I uninstalled most of them, what’s going on?
![Captura de pantalla 2022-01-16 a las 23 56 46](https://user-images.githubusercontent.com/22520811/149681633-9ad0ca98-7e88-4814-bc45-c7a86cb97496.png)

**Comment by rebornix** [comment]
@sergiojurcas can you please try run VS Code with extension disabled `code --disable-extensions`?
