### ISSUE TITLE
希望终端可以单独移动到左侧下方（I hope the terminal can move to the lower left side alone）

### ISSUE THREAD

**Issue by wuwenliangx** [microsoft/vscode#140894]
![image](https://user-images.githubusercontent.com/37337778/149913067-011b657e-5779-47c5-80f1-f80acf6507d3.png)

**Comment by liuyji** [comment]
现在就是支持的, 你拖着终端这两个字, 拖到你说的那个地方就可以了. vscode 在这一点上很灵活.

**Comment by meganrogge** [comment]
Doesn't putting it in the activity bar like this accomplish that?

![Screen Shot 2022-01-19 at 12 30 22 PM](https://user-images.githubusercontent.com/29464607/150192256-86115b29-1004-44ba-9ea7-34a635e7d59a.png)

**Comment by meganrogge** [comment]
or dragging and dropping whatever you want on the right side of the panel accomplishes that a different way
![Screen Shot 2022-01-19 at 12 31 07 PM](https://user-images.githubusercontent.com/29464607/150192367-2ba9ac47-43a3-4992-8f8c-b5428817a5dc.png)

**Comment by Tyriar** [comment]
Yeah you can do this sort of thing in various ways:

- Move into a "view container" on the side by dragging
- Multiple side-by-side views in the bottom panel
- Change "panel alignment" coming in 1.64

**Comment by chenbimo** [comment]
> 

what time the 1.64 release?

**Comment by Tyriar** [comment]
Probably tomorrow

**Comment by wuwenliangx** [comment]
Thank you very much. I dragged the blank area before. I didn't drag it. It's OK to drag the panel text.
![image](https://user-images.githubusercontent.com/37337778/152714432-2f8eae0e-0417-4ee3-acca-97d109f66087.png)
