### ISSUE TITLE
[Bug] When profile button is clicked, a menu opens which is stuck on loading

### ISSUE THREAD

**Issue by Rubix982** [microsoft/vscode#140841]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: `1.62.0`, `b3318bc0524af3d74034b8bb8a64df0ccf35549a`, `x64`
- OS Version: `Linux saif-latitude 5.16.0-zen1-1-zen #1 ZEN SMP PREEMPT Mon, 10 Jan 2022 20:12:01 +0000 x86_64 GNU/Linux`, 

Steps to Reproduce:

1. Fresh installation of `vscode` on a `arch linux` based distro (currently using `garuda linux`) with `sudo pacman -S code`
2. Click on the `profile button` at the bottom left to get this menu as shown in the screenshot attached.

![image](https://user-images.githubusercontent.com/41635766/149728423-8b9f479b-9786-4256-b41f-87535a0d1f32.png)

**Comment by Rubix982** [comment]
Also, is there anyway I can access the "Turn On Setting Sync" option in there through the Command Platte?

**Comment by TylerLeonhardt** [comment]
I don't think that's the right package. I think you want this one:

https://aur.archlinux.org/packages/visual-studio-code-bin/?O=10&PP=10
