### ISSUE TITLE
Custom Code Actions Menu Style

### ISSUE THREAD

**Issue by talks2much** [microsoft/vscode#140809]
There is `window.dialogStyle` which is handy for me since `custom` variant doesn't have annoying and really long opening animation.
I want the same setting for the Code Actions menu as it has ~200 ms latency after selecting variant on macOS which is incredibly annoying for me.

The same also applies for all types of native context menus. I wonder is it possible to disable it on system level?

The only advantage of native menus is selecting elements with keyboard much easier.

**Comment by tanhakabir** [comment]
@sbatten seeing git blame for `window.dialogStyle` here: https://github.com/microsoft/vscode/blob/9291d82351cb36c832d5aef2620d3bd6c08f3eae/src/vs/workbench/electron-sandbox/desktop.contribution.ts#L192 with your name.

Let me know if I assigned incorrectly!

**Comment by sbatten** [comment]
@talks2much we currently don't support the custom menus on macos. I would believe if all native context menus behave this way, there should be an OS-level setting to configure but I am not aware. If there is specifically extra latency with the code actions menu, @mjbvz might be able to help

**Comment by mjbvz** [comment]
Closing this at it sounds like a general MacOS context menu behavior and not something VS Code can override/customize

**Comment by talks2much** [comment]
> we currently don't support the custom menus on macos

@sbatten I see, thats why I am asking for this feature to be added.
@mjbvz I don't really understand what you mean, I suppose you just misread the issue? VSCode can override dialog style, why can't it override menu style?

All in all the menu style is already implemented for windows platform, why don't give a setting to enable them on macOS as well? Or am I missing something?

**Comment by talks2much** [comment]
Again, I want this menu to be available on macOS as it doesn't have *general MacOS context menu behavior* problem

<details>
<summary>Screenshot</summary>

![Screenshot 2022-01-19 020215](https://user-images.githubusercontent.com/78976241/150032784-37d6ed49-2923-4e40-933c-e116a384b4c4.png)

</details>

**Comment by zardoy** [comment]
Hey, @mjbvz I think the talk here is about having custom UI style for codeactions. If its possible to implement should the issue be reopened? I’d like get a chance to dig into it.
