### ISSUE TITLE
Layer breaker in  browser/contextScopedHistoryWidget.ts#L14

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#140856]
The following import added with a59631868afa579b4ef500f15c484514fecb2943 adds a layer breaker from `platform` to `editor`
https://github.com/microsoft/vscode/blob/347f954c2960610cba11a9d25638b9395ff35d19/src/vs/platform/browser/contextScopedHistoryWidget.ts#L14

**Comment by alexdima** [comment]
This is now also flagged by our eslint rules. (https://github.com/microsoft/vscode/issues/140984)
