### ISSUE TITLE
Ctrl+y busted

### ISSUE THREAD

**Issue by TheREK3R** [microsoft/vscode#140810]
Issue Type: <b>Bug</b>

I think autosave is busting my REDO. I often ctrl+z to get to a past state, copy, and ctrl+y to get back. Now it is locking state so I cant redo which is very annoying.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614
vsccppwtstudy:30421978

```

</details>

**Comment by alexdima** [comment]
@TheREK3R What are the precise steps where `Ctrl+Y` no longer works?
