### ISSUE TITLE
I can't login to https://github.dev/

### ISSUE THREAD

**Issue by DeFaLT-dj** [microsoft/vscode#140863]
I can't login to https://github.dev/ with my Microsoft account. It shows this error when trying to login. 

![image](https://user-images.githubusercontent.com/64617514/149796192-6bbbe049-4a7a-4d3c-b24e-6b32a6e30f0c.png)

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 Edg/97.0.1072.62
Embedder: github.dev

**Comment by TylerLeonhardt** [comment]
Interestingly, I can't repro this in vscode.dev or VS Code desktop.

**Comment by jkeech** [comment]
github.dev currently only supports using your GitHub account for Settings Sync. The github.dev session should be pre-authenticated with your GitHub account, although you might have to enable Settings Sync manually the first time.

**Comment by DeFaLT-dj** [comment]
> github.dev currently only supports using your GitHub account for Settings Sync. The github.dev session should be pre-authenticated with your GitHub account, although you might have to enable Settings Sync manually the first time.

Oh, I see, thanks for letting me know. Hope it will support MS accounts in the future versions.
