### ISSUE TITLE
My vscode disappeared when screenshot

### ISSUE THREAD

**Issue by fjboy** [microsoft/vscode#140879]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: win10

The vscode ui interface disappears when I try to take a screenshot using the PrtSc key. And the same goes for taking screenshots with the third-party screenshot tool Snipaste. 

Steps to Reproduce:

1. Open vscode
2. Press the PrintSc key

**Comment by deepak1556** [comment]
Unable to repro the issue, please try with latest stable `1.73`. Can reopen if the issue is still present, please provide additional info on the screenshot tool used.
