### ISSUE TITLE
To group buttons of extensions in left bar

### ISSUE THREAD

**Issue by vieiraes** [microsoft/vscode#140875]
Issue Type: <b>Feature Request</b>

Sometimes, a group os extensions has similiriarity and Idlike to group by subject. ( Like DOcker and Docker compose extensions, should be grouped in a single button "Docker", and expanded as I wish)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.13.0-25-generic snap
Restricted Mode: No

**Comment by sandy081** [comment]
You can always merge these views by drag n drop.
