### ISSUE TITLE
VSCode jumps to testing view

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [microsoft/vscode#140869]
Issue Type: <b>Bug</b>

After some action VSCode switches to the Testing panel. Happens sometimes on saving, deleting, searching and so  on.

VS Code version: Code - Insiders 1.64.0-insider (6612ae0f8b5d9c0d86518ebbd153c724a7cbcf73, 2022-01-17T05:16:09.172Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (6.49GB free)|
|Process Argv|--crash-reporter-id 5f9e326c-2a01-458b-95a4-f411641d6f56|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
jest-snippets|and|1.8.0
browse-lite|ant|0.2.16
icons-carbon|ant|0.2.4
vscode-apollo|apo|1.19.9
atlascode|atl|2.10.3
turbo-console-log|Cha|2.1.7
path-intellisense|chr|2.6.1
vscode-svgviewer|css|2.0.0
vue-peek|dar|1.0.2
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.79
prettier-vscode|esb|9.1.0
vscode-firefox-debug|fir|2.9.6
auto-rename-tag|for|0.1.9
gitlab-workflow|Git|3.40.1
vscode-graphql|Gra|0.3.41
dance|gre|0.5.8
vue-snippets|hol|1.0.4
output-colorizer|IBM|0.1.2
prettier-sql-vscode|inf|0.2.0
vscode-postfix-ts|ipa|1.9.4
vscode-peacock|joh|4.0.0
volar|joh|0.30.5
vscode-typescript-vue-plugin|joh|0.30.5
jq-syntax-highlighting|jq-|0.0.2
vscode-dependency-cruiser|jua|0.0.1
vscode-lua-format|Koi|1.3.8
i18n-ally|lok|2.8.1
vue-discovery|maa|1.4.0
fluent-icons|mig|0.0.16
dotenv|mik|1.0.1
vscode-scss|mrm|0.10.0
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.0
vsliveshare|ms-|1.0.5242
vsliveshare-audio|ms-|0.1.91
angular-console|nrw|17.13.7
oracledevtools|Ora|21.3.0
vscode-jest|Ort|4.2.1
refactor|p42|1.68.2
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.11.0
polacode|pnp|0.3.4
inline-sql-syntax|quf|2.5.0
vscode-yaml|red|1.3.0
mdx|sil|0.1.0
sonarlint-vscode|Son|3.1.0
sass-indented|syl|1.8.18
intellicode-api-usage-examples|Vis|0.0.8
vscodeintellicode|Vis|1.2.15
vscode-conventional-commits|viv|1.24.0
vscode-icons|vsc|11.8.0
change-case|wma|1.0.0
luahelper|yin|0.2.10
sort-js-object-keys|zen|1.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30421239
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30421357
vscop804:30404766
vs360cf:30404996
vsclayoutctrc:30405799
azactmsalcf:30409288
vsccppwtstudy:30421978

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate this.

**Comment by sschneider-ihre-pvs** [comment]
Wow, I didn't know that there is something like git bisect now for extensions, really great!

**Comment by sschneider-ihre-pvs** [comment]
https://github.com/jest-community/vscode-jest/issues/829
