### ISSUE TITLE
Delete option on right click of mouse 

### ISSUE THREAD

**Issue by suneelkumar7** [microsoft/vscode#140843]
Issue Type: <b>Feature Request</b>

after selecting the text if i click on mouse's right click button than there should be a delete option available so that i could delete selected text easily, and it helps in productivity.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by hediet** [comment]
You can use `cut` and the text gets deleted!
