### ISSUE TITLE
Missing Sublime Text command - Expand selection to brackets

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#14089]
While building this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings) to map Sublime Text default keyboard shortcuts to VS Code, I found that this feature is missing. 

The feature is expand to brackets. 

**Default Sublime Text keybindings**
Windows / Linux: <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>m</kbd>
Mac: <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>m</kbd>

![expand_selection_by_brackets](https://cloud.githubusercontent.com/assets/2449568/19564915/f31df09a-9699-11e6-9a6c-65b481c2f80d.gif)

Today an [extension](https://marketplace.visualstudio.com/items?itemName=guosong.bracketselection) exists with this functionality. I believe we should bring this feature into the product.

**Comment by neolwc** [comment]
<kbd>⌃</kbd>+<kbd>⇧</kbd>+<kbd>⌘</kbd>+<kbd>→</kbd>
<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>cmd</kbd>+<kbd>→</kbd>

**Comment by waderyan** [comment]
@neolwc unfortunately that functionality is not exactly the same. It will work in some cases but not all.

**Comment by Egorvoz** [comment]
@waderyan yep. VS code needs this feature.

**Comment by bigfanjs** [comment]
I just switched to VS code and unfortunately I did not find that feature when I mapped the Sublime text default keyboard shortcuts to VS code. I badly need it!

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/9768, let's track it there. It's on our deck now.
