### ISSUE TITLE
vscode on Chromebook using networkshare not working

### ISSUE THREAD

**Issue by kbfifi** [microsoft/vscode#140824]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: ChromeOS 97.0.4692.77

Steps to Reproduce:

1. start vscode on Chromebook
2. open network share folder, via file->open folder
3. issue1: Side bar shows network folder but no files are shown 
4. open file via  file->open file
5. change file and save
6. issue2: "Failed to save ... ENOTSUP, operation not supported on socket

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by kbfifi** [comment]
Thanks for your quick response!
Here's the requested log
[vscode_verbose.log](https://github.com/microsoft/vscode/files/7880247/vscode_verbose.log)

**Comment by bpasero** [comment]
@kbfifi thanks, this seems the issue:

```
Error: EINVAL: invalid argument, scandir '/mnt/chromeos/SMB/752b96118bc7a5f3490e9f951ce445989cc55c52051bd95bb40d92315effac35'
```

Can we conduct an experiment? Can you install node.js (14.x to match VSCode version), run `node` from the command line and run the following code:

```js
fs.readdirSync('/mnt/chromeos/SMB/752b96118bc7a5f3490e9f951ce445989cc55c52051bd95bb40d92315effac35')
```

And see if you get any output?

**Comment by kbfifi** [comment]
Yes saw that too, but doesn make sense to me. Here's the result of your request:
kurt@penguin:~$ node -v
v14.18.3
kurt@penguin:~$ node
Welcome to Node.js v14.18.3.
Type ".help" for more information.
> fs.readdirSync('/mnt/chromeos/SMB/752b96118bc7a5f3490e9f951ce445989cc55c52051bd95bb40d92315effac35')
Uncaught:
Error: EINVAL: invalid argument, scandir '/mnt/chromeos/SMB/752b96118bc7a5f3490e9f951ce445989cc55c52051bd95bb40d92315effac35'
    at Object.readdirSync (fs.js:1047:3) {
  errno: -22,
  syscall: 'scandir',
  code: 'EINVAL',
  path: '/mnt/chromeos/SMB/752b96118bc7a5f3490e9f951ce445989cc55c52051bd95bb40d92315effac35'
}

**Comment by bpasero** [comment]
Without the ability to read a folder, VS Code cannot show the contents. I suspect this is an issue with the file system driver.
