### ISSUE TITLE
Vscode tooltips colors syntax of documentation rendering instead of the monotonous white syntactic

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#140872]
I'm looking for a Vscode extension or native way where we can add better colors syntax for rendering documentation instead of the monotonous white syntactic ! Has anyone already found this and could share a link with me?

Actually on my side the documentation render in full white ! Am look for something like seconde frame ! [Photoshoped]

![image](https://user-images.githubusercontent.com/24865815/149834919-c5c9c9a1-e31b-4f92-b08e-4fa7154de4ff.png)

thanks
I also add a post on stackoverflow
https://stackoverflow.com/questions/70747273/vscode-colors-syntax-of-rendering-documentation-instead-of-the-monotonous-white

**Comment by mjbvz** [comment]
This is not possible for an extension to add. Marking as a feature request
