### ISSUE TITLE
Error in searching/fetching extensions

### ISSUE THREAD

**Issue by kavyahalani** [microsoft/vscode#140844]
Issue Type: <b>Bug</b>

Trying to search any extension in the extensions:marketplace panel and it gives me: Error while fetching extensions. XHR timeout: undefinedms

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 16190dcc-2b5e-46d7-add2-ff7ee2afce6b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
ng-template|Ang|11.2.9
htmltagwrap|bra|0.0.7
gulp-lattice|chr|0.2.0
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
angular-schematics|cyr|4.13.0
vscode-markdownlint|Dav|0.40.3
vscode-eslint|dba|2.1.19
vscode-faker|dee|1.5.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|11.3.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.19
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|6.3.2
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.3
rest-client|hum|0.24.5
angular-essentials|joh|11.0.0
Angular2|joh|11.0.0
vscode-peacock|joh|3.9.1
vscode-gutter-preview|kis|0.27.1
vscode-language-babel|mgm|0.0.31
code-beautifier|mic|2.3.3
dotenv|mik|1.0.1
vscode-typescript-next|ms-|4.3.20210405
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
material-icon-theme|PKi|4.6.0
pluralsight|Plu|0.4.1
tsimporter|pmn|2.0.1
vscode-css-peek|pra|4.1.3
quicktype|qui|12.0.46
typescript-hero|rbb|3.0.0
code-settings-sync|Sha|3.4.3
vscode-scss-formatter|sib|2.1.0
html5-boilerplate|sid|1.1.1
swdc-vscode|sof|2.5.11
autoimport|ste|1.5.3
code-spell-checker|str|1.10.2
errorlens|use|3.2.5
remove-empty-lines|use|0.0.6
highlight-matching-tag|vin|0.10.0
vscode-icons|vsc|11.4.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30283811
wslfolderdoc:30282074
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071

```

</details>

**Comment by sandy081** [comment]
Can you please check if there are any errors in the console while you are searching extensions? You can get to the console by following these steps:

- F1 > Developer: Toggle Developer Tools
