### ISSUE TITLE
 My vscode is starting in the background without me touching anything

### ISSUE THREAD

**Issue by procopio-marker** [microsoft/vscode#140823]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2 
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by procopio-marker** [comment]
My vscode is starting in the background without me touching anything

**Comment by rzhao271** [comment]
Which OS are you on? Is VS Code in the list of programs that run on startup?
