### ISSUE TITLE
MDN Hover effect

### ISSUE THREAD

**Issue by jeetbhalani15** [microsoft/vscode#140864]
Issue Type: <b>Feature Request</b>

guys plz change this effect all the time I tryna click any element MDN refer is opened whenever I click it mistakenly. use some another effect yeah it's useful to we want it too but it's annoying many  a times

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Try editing the `edit.hover.delay` setting, but be aware that a recent regression means you need to double your value, until the fix arrives next month.
