### ISSUE TITLE
Unable to resolve your shell environment: Unexpected token b in JSON at position 35

### ISSUE THREAD

**Issue by CaledoniaProject** [microsoft/vscode#140888]
Every time I start vscode this dialog would popup:

![screenshot 2022-01-18 at 3 39 53 PM](https://user-images.githubusercontent.com/1357701/149892025-118a0465-3e81-43d1-a3f1-4ee573e19f7a.jpg)

And there's no way to determine which JSON file is broken. The "Learn More" button does not provide anything useful, please help me figure out what's wrong?

**Comment by CaledoniaProject** [comment]
@meganrogge 

1. Tried stackoverflow already, no one answers for 2 months
2. It's a bug and a feature request. The error dialog is useless and need to be improved, aka provide detailed error information

Please reopen it and improve the dialog.

**Comment by Tyriar** [comment]
@CaledoniaProject when VS Code launches, we source a "dev environment" by running your default shell. When this fails we show the error message that your shell returned. Bottom line is you have some issue in your shell init files that's causing that error, you need to investigate on your end as it's a problem with your environment, not with VS Code.

See here for what we do before showing this error:

https://github.com/microsoft/vscode/blob/87b365f433427f0b936b02382b177abebc7c6369/src/vs/platform/environment/node/shellEnv.ts#L126-L151

**Comment by CaledoniaProject** [comment]
Thanks, I did more debugging:

1.  This pops the error dialog: `VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args "$@"`
2. This works fine: /usr/local/homebrew/bin/code "$@"

Is there any difference?
