### ISSUE TITLE
Slow loading in VS Code

### ISSUE THREAD

**Issue by MoNarchEnterprises** [microsoft/vscode#140803]
- Extension Name: debug-auto-launch
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.19043
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 56870,
		"activateCallTime": 40,
		"activateResolvedTime": 18011,
		"activationEvent": "onLanguage:python"
	}
}
```

**Comment by connor4312** [comment]
debug-auto-launch doesn't listen for that activation event. Can you provide more info about what you're seeing?
