### ISSUE TITLE
Insider: Unable to reassign F1 as keybinding for Show All Commands

### ISSUE THREAD

**Issue by JacobDeuchert** [microsoft/vscode#140884]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
  ```
  1.64.0-insider
  7ae7f9d40b82a0f1a49d8ad180d27e16812ad95e 
  x64
  ```
- OS Version:
`Windows 10 21H1`

Steps to Reproduce:

1. Remove default keybinding F1 for Show All Commands 
2. Add new Keybinding for Show All Commands and try to assign F1 to it.

When trying to add F1 as a new keybinding for Show All Commands it just does nothing. You can assign other shortcuts like "ctrl+F1".
The only way to get F1 back is by removing all keybindings for "Show All Commands" and then reset the keybinding.
![vscode-keybinding](https://user-images.githubusercontent.com/43518397/149884986-30dd8766-ed94-4539-becf-67fb58c7d891.gif)

Keybindings for other commands can be assigned with F1.

I tried it with the stable VS Code and there it works just fine.

**Comment by alexdima** [comment]
I can reproduce and confirm that this is a bug. As a workaround, you can open your `keybindings.json` file using `Ctrl+Shift+P > Preferences: Open Keyboard Shortcuts (JSON)` and remove the following rule:
```
  {
    "key": "f1",
    "command": "-workbench.action.showCommands"
  },
```
