### ISSUE TITLE
Can't open latest insider version

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#140839]
![image](https://user-images.githubusercontent.com/41773861/149722962-df8de4f4-83f4-4869-ad4d-7d666e13beda.png)

**Comment by tjx666** [comment]
After I upgrade latest insider second minutes ago...

**Comment by tjx666** [comment]
After I restart my computer, It still can't open. I had reinstalled latest insider version, it can normally open now.

**Comment by joaomoreno** [comment]
>  it can normally open now

Good to know, let us know if it comes back.
