### ISSUE TITLE
What can i do for err : self signed certificate 

### ISSUE THREAD

**Issue by william54wp** [Microsoft/vscode#14080]
when I open VScode  offline, I got an error : self signed certificate . what can i do for it ? 

- VSCode Version: 1.6.1
- OS Version: Win7x64

**Comment by joaomoreno** [comment]
Set the `http.proxyStrictSSL` setting to `false`.

**Comment by william54wp** [comment]
3Q ,It's worked, but i got another error: Server returned 400
