### ISSUE TITLE
Auto Sync stop automatic

### ISSUE THREAD

**Issue by mohamedsaqer** [microsoft/vscode#140842]
Issue Type: <b>Bug</b>

every time I had a window opened and I open a new window the app ask me to sign in to sync my settings 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:38:17.605Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (0.91GB free)|
|Process Argv|--crash-reporter-id 0ee627cf-e4d9-4f4e-b8d2-b8c6ff2d7a6a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|3.1.1
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|9.1.0
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
copilot|Git|1.7.4608
remotehub|Git|0.20.0
vscode-gutter-preview|kis|0.29.0
vscode-language-babel|mgm|0.0.35
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
vsliveshare|ms-|1.0.5242
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vscode-react-native|msj|1.8.1
color-highlight|nau|2.5.0
indent-rainbow|ode|8.2.2
material-icon-theme|PKi|4.11.0
LiveServer|rit|5.6.1
code-spell-checker|str|2.1.4
highlight-matching-tag|vin|0.10.1
JavaScriptSnippets|xab|1.8.0
zeplin|Zep|2.2.0
material-theme|zhu|3.13.11

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30422344
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30421291
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710:30416614
vsccppwtstudy:30421978

```

</details>

**Comment by mohamedsaqer** [comment]
![Recording 2022-01-25 at 13 47 25](https://user-images.githubusercontent.com/9972973/150971534-000db10c-7868-4978-9ebb-cdb5d6f7369e.gif)

**Comment by mohamedsaqer** [comment]
@TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
Can you follow these steps so that we can get more information on what's going on?

* Open the Command Palette
* Run the `Developer: Set Log Level...` command
* Choose `Trace`
* _Wait for the issue to happen..._
* Open the Output pane (ctrl+shift+u I think on Windows)
* drop in this issue he contents of the following:
  * `Microsoft Authentication` Output channel or `GitHub Authentication` Output channel (depending on the account you're using
  * `Log (Settings Sync)` Output channel
  * `Log (Window)` Output channel

**Comment by mohamedsaqer** [comment]
[log.txt](https://github.com/microsoft/vscode/files/7968187/log.txt)

**Comment by TylerLeonhardt** [comment]
@mohamedsaqer thanks for that. I appreciate you providing both Microsoft & GitHub output but which one do you actually use with Settings Sync?

**Comment by mohamedsaqer** [comment]
I use both but the main is Microsoft

**Comment by TylerLeonhardt** [comment]
I have a possible fix for this that will come in VS Code Insiders starting either Thursday or Friday. Fixed in https://github.com/microsoft/vscode/commit/f498b374c03be09cf664a7fefa1c1c95a0c7216d

**Comment by mohamedsaqer** [comment]
Awesome

**Comment by TylerLeonhardt** [comment]
@mohamedsaqer can you try out the latest insider build of VS Code: http://code.visualstudio.com/insiders

**Comment by RahmanKeong** [comment]
Masalah kode authentikator Google

**Comment by TylerLeonhardt** [comment]
@mohamedsaqer have you had a chance to give this a go? I specifically would like to know how Microsoft Auth goes.

**Comment by mohamedsaqer** [comment]
the issue still exists @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
I'm closing this since there has been a lot of work in this space. Please give Insiders a try or wait until the Stable release which will be next Thursday which will have my fixes.
