### ISSUE TITLE
VSCode ignoring tsconfig.json

### ISSUE THREAD

**Issue by devmanbr** [microsoft/vscode#140830]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows 10 20H2

Steps to Reproduce:

VSCode (apparently) completely ignores the tsconfig.json file, for some reason. As a result, the "paths" defined in the TypeScript settings file at the root of the project are not resolved, and errors are generated (specifically, TS:2307).

Initially I thought it might be related to #21473, but I realized the problem was occurring because the VSCode is installed on one disk (C:/), and the project is on another (H:/). To reach this conclusion, I made tests by copying the project to the C:/ disk, with exactly the same structure, and the problem no longer exists.

The obvious solution that many can point me to is to simply create the projects on the C:/ disk. However, for reasons of free disk space, I have no way to do that (that's exactly why I installed the new disk).

I tried multiple solutions (even modifying the NPM directory), and none worked.

Any light?

**Comment by mjbvz** [comment]
Please share a small project that demonstrates the issue and share steps to reproduce this issue using it
