### ISSUE TITLE
VScode using local electron's resources which in my project's node_modules directory.

### ISSUE THREAD

**Issue by xckai** [microsoft/vscode#140881]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: Win11 Windows_NT x64 10.0.22000

Steps to Reproduce:

1.  open a javascript project, install electron dependency。 
2.  reopen vscode with this project.
3.  install  another dependency by npm :  npm i electron-tabs , then you got an error: xxx.file is locked;
4. open window resource monitor search this file, you will see VScode using this file in it's process.

 EBUSY: resource busy or locked, rename 'C:\Users\xckai\Desktop\projects\Test\encoo-browser\node_modules\_electron@16.0.7@electron\dist\resources\default_app.asar' -> 'C:\Users\xckai\Desktop\projects\Test\encoo-browser\node_modules\._electron@16.0.7@electron-mrqNG047\dist\resources\default_app.asar'
 
![image](https://user-images.githubusercontent.com/5928422/149866852-067e3f57-7d73-4bd7-bab4-1c56c42eb02d.png)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by xckai** [comment]
> I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

yes, it works, thanks.
