### ISSUE TITLE
Localization starts with "DE" locale and verifies title and viewlets text is in German

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#140838]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=150432&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=aaa04083-6c0b-5a33-e907-3d845b07f0b5&l=71

```
1) VSCode Smoke Tests (Electron)
       Localization
         starts with "DE" locale and verifies title and viewlets text is in German:
     Error: Timeout: get element 'div.extensions-viewlet[id="workbench.view.extensions"] .monaco-list-row[data-extension-id="ms-ceintl.vscode-language-pack-de"]' after 20 seconds.
      at poll (/__w/1/s/test/automation/src/code.ts:109:10)
      at Code.waitForElement (/__w/1/s/test/automation/src/code.ts:263:10)
      at Extensions.searchForExtension (/__w/1/s/test/automation/src/extensions.ts:36:3)
      at Extensions.installExtension (/__w/1/s/test/automation/src/extensions.ts:49:3)
      at Context.<anonymous> (src/areas/workbench/localization.test.ts:19:4)
```

![starts_with__DE__locale_and_verifies_title_and_viewlets_text_is_in_German](https://user-images.githubusercontent.com/900690/149722152-09025f84-171d-4941-ac57-27ce420926b1.png)

**Comment by sandy081** [comment]
@bpasero It seems like the machine has network issues connecting to the Marketplace. So not sure if anything can be done.

**Comment by bpasero** [comment]
Should this request be retried in case of an XHR failure unless the user is offline?

**Comment by sandy081** [comment]
I would not do that in prod, it means we have to have this retry code for all requests which does not makes sense. But retry can be done in smoke tests just like how user retries ?

**Comment by bpasero** [comment]
Yeah that is a good idea, try to find that message specifically and re-try the operation only in smoke tests.

**Comment by bpasero** [comment]
Thanks for the prompt resolution!
