### ISSUE TITLE
Editor doesn't insert white spaces when formatting html files.

### ISSUE THREAD

**Issue by nikolafon** [Microsoft/vscode#14081]
- VSCode Version: 1.6.1
- OS Version: macOS Sierra 10.12

Steps to Reproduce:
1. 
Make sure that you set 
"editor.insertSpaces": true
in your workspace settings
2.
Make sure you are using indentation with spaces and indentation size 2 in my case.
3. 
Try to format html file

Expected result:
Editor should preserve white spaces as tabs.

Result:
Editor converts spaces to tabs. It should not.

Additional comment:
It works fine when saving typescript file for example.
The white spaces are preserved correctly.

**Comment by roblourens** [comment]
Are you formatting with an extension, or the built-in vscode format?

**Comment by nikolafon** [comment]
Build in VS Code formatter.

**Comment by roblourens** [comment]
This is #13563
