### ISSUE TITLE
Some Feature Request's

### ISSUE THREAD

**Issue by Samyak-Bumb** [microsoft/vscode#140855]
1. Please add **Smooth Animation / Transition** while _Opening_ & _Closing_ Items (Also Add Setting to **Turn off a Particular Transition / Animation**)
2. Add **Border Radius** to Dropdown, Buttons, _**Scrollbar**_ etc.
3. Add a Feature **Toggle Title Bar** Hide / Show.
4. Add a Feature to **Change Emmet Extension Output**.
### **Important**:
5. Add a **Default Formatter** for all **Coding Languages 🌍** (Fully Customizable)
6. Add a Feature to **Get List of Remaining Keyboard Shortcuts**
7. Add a Documentation to How to Write _**When**_ in Keyboard Shortcuts?

## Thanks for Reading 🙂😀
**Please Add This Features in Future** 👍

**Comment by IllusionMH** [comment]
It's a bad practice to dump list of requests in one issue as it makes hard for devs to track issue.
Moreover - one line description is not enough to weight on request. Please filter list (especially check docs existing docs on site) and create reasonable separate feature requests according to template.

1. Motivation required, especially "Turn off a Particular Transition / Animation". Are there examples with this much configuration in any app?
4. No info how/why?
5. Already exists as global setting, have UI + can be overridden for each language using exsting mechanisms.
6. What does it mean? There is existing command <kbd>F1</kbd> `>Preferences: Open Keyboard Shortcuts` to see Keyboard Shortcuts editor. Unbound commands are available there as well. Check https://code.visualstudio.com/docs/getstarted/keybindings for details
7. Already documented. See https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts and then link in https://code.visualstudio.com/docs/getstarted/keybindings#_available-contexts section

**Comment by weinand** [comment]
@IllusionMH thanks a lot for providing guidelines to @Samyak-Bumb

In addition we have a [Wiki](https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) that explains how to write Good Bug Reports and Feature Requests.

@Samyak-Bumb I'm closing this issue now because we cannot handle kitchen-sink feature requests.

**Comment by Samyak-Bumb** [comment]
@IllusionMH Sorry for that 😭😥
