### ISSUE TITLE
Missing Sublime Text Command - Split selection into lines

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#14088]
While building this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings) to map Sublime Text default keyboard shortcuts to VS Code, I found that this feature is missing. 

The feature is split selection into lines. 

**Default Sublime Text keybindings**
Windows / Linux: <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>l</kbd>
Mac: <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>l</kbd>

![split_selection_into_lines](https://cloud.githubusercontent.com/assets/2449568/19564761/74df606a-9699-11e6-85b7-ccfe36283612.gif)

Today an [extension](https://marketplace.visualstudio.com/items?itemName=JulioGold.vscode-smart-split-into-lines) exists that provides this feature. I believe we should bring this into the product.

**Comment by waderyan** [comment]
Looks like this already exists for the command - `editor.action.insertCursorAtEndOfEachLineSelected`

**Comment by dyyylan** [comment]
For anyone else that stumbles upon this from Google, this is the whole line you can copy/paste this into keybindings.json to get this feature working with the same shortcut as sublime/atom:

`{ "key": "ctrl+shift+l", "command": "editor.action.insertCursorAtEndOfEachLineSelected", "when": "editorTextFocus "}`

**Comment by wdews** [comment]
Currently VS Code allows you to make a selection and use the "Selection" alt menu, then choose "Add Cursors to Line Ends". On Mac, the keyboard shortcut is Option+Shift+I (the letter "i").
