### ISSUE TITLE
it's very sluggish!

### ISSUE THREAD

**Issue by francorop** [microsoft/vscode#140847]
Issue Type: <b>Bug</b>

after update windows to 21h1

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (0.38GB free)|
|Process Argv|--crash-reporter-id 5c621e3f-6477-4241-bf5c-c7def8adb26a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-html-css|ecm|1.10.2
php-debug|fel|1.22.0
php-pack|fel|1.0.2
Angular2|joh|12.0.0
Angular-BeastCode|Mik|10.0.3
vscode-docker|ms-|1.18.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
notepadplusplus-keybindings|ms-|1.0.7
sftp|Nat|1.15.10
regexr-vscode|Ora|1.0.0
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-maven|vsc|0.34.2
bootstrap-v4-snippets|Zac|1.1.3
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30421290
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710:30416614
vsccppwtstudy:30421978

```

</details>

<!-- generated by issue reporter --
[Profile-20220117T111439.zip](https://github.com/microsoft/vscode/files/7881018/Profile-20220117T111439.zip)
>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

https://github.com/microsoft/vscode/wiki/Performance-Issues
