### ISSUE TITLE
Ctrl + ` not bring up the terminal

### ISSUE THREAD

**Issue by Fitmavincent** [microsoft/vscode#140811]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. When I use keybindings Ctrl+`, no bottom panel (terminal) comes up.
2.  Test with several keyboards, wired and wireless, same results.

**Comment by gjsjohnmurray** [comment]
Please use the advice at https://github.com/microsoft/vscode/wiki/Keybinding-Issues to investigate.
