### ISSUE TITLE
Flaky integration test 'vscode API - languages - link detector'

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#140878]
Failed twice in a row today

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=150523&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=6a86faf8-ed15-56db-877e-46756fb8e8fa

https://github.com/microsoft/vscode/runs/4847136200?check_suite_focus=true

I've skipped this test

**Comment by Tyriar** [comment]
This failed a lot, I'm not sure it was flaky? Please check it one out during this milestone to verify it's not important.

**Comment by aeschli** [comment]
I'm not able to reproduce locally, so I guess it's flaky. I added more debug output and enabled it again.
