### ISSUE TITLE
right click issue

### ISSUE THREAD

**Issue by AbdoZaghlool** [microsoft/vscode#140887]
Issue Type: <b>Bug</b>

when trying to right click any where my code the arrow is by default clicking the alignment option

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.11.0-46-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|9.62GB (0.54GB free)|
|Process Argv|--unity-launch --crash-reporter-id 85f3d514-829f-43e5-becf-dd78837e50ad|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
alpine-js-intellisense|adr|1.2.0
laravel-model-snippets|ahi|2.0.0
project-manager|ale|12.4.0
laravel-extra-intellisense|ami|0.6.1
vscode-intelephense-client|bme|1.8.0
htmltagwrap|bra|0.0.7
vscode-tailwindcss|bra|0.7.6
livewire-vscode|cie|0.2.8
laravel-blade|cjh|1.1.2
gitignore|cod|0.7.0
laravel-goto-view|cod|1.3.7
bracket-pair-colorizer-2|Coe|0.2.2
tighten-lint|d97|0.1.0
vscode-eslint|dba|2.2.2
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
php-debug|fel|1.22.0
copilot|Git|1.7.4608
laravel-create-view|gli|0.0.6
vue|jcb|0.1.5
php-cs-fixer|jun|0.2.10
laravel-snippets|ken|1.2.1
dotenv|mik|1.0.1
laravel-intellisense|moh|0.2.0
vscode-docker|ms-|1.18.0
php-docblocker|nei|2.6.1
vetur|oct|0.35.0
indent-rainbow|ode|8.2.2
laravel-blade|one|1.29.0
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.13.0
advanced-new-file|pat|1.2.2
material-icon-theme|PKi|4.11.0
try-material-icon-theme|raf|3.9.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
laravel-artisan|rya|0.0.28
vscode-blade-formatter|shu|0.10.3
prettify-symbols-mode|sie|0.4.2
vscode-fileutils|sle|3.4.6
sonarlint-vscode|Son|3.1.0
laravel-goto-controller|ste|0.0.15
city-lights-icon-vsc|Yum|1.1.3
vscode-open-in-github|ziy|1.3.6

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30421290
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710:30416614
vsccppwtstudy:30421978

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the description in #140346 match your case?
