### ISSUE TITLE
Impossible de lancer correctement Visual studio code pour exécuter un code .html. Message "l'hôte d'extension s'est arrêté de manière inattendue", 

### ISSUE THREAD

**Issue by sergaey** [microsoft/vscode#140877]
Issue Type: <b>Feature Request</b>

Bonjour,
Ci-dessous le message d'erreur que j'ai eu en lançant le logiciel:

Message "l'hôte d'extension s'est arrêté de manière inattendue",
Ouvrir les outils de développement ou Rédémarer l'hôte d'extension

Serait-il possible que vous puissiez m'aider, je n'arrive pas à trouver ce qui ne fonctionne pas. Je vous remercie par avance de votre retour.

Bien cordialement

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by sbatten** [comment]
Translated
>Below is the error message I got when launching the app
>
>Message "Extension host terminated unexpectedly"
>Open Developer Tools or Restart the Extension Host‎
>
>Would you be able to help me? I can't find what isn't working. Thanks in advance for your reply.‎

When issues like this occur, we have some tools to help investigate. Please look at this previous issue with guidance to understand which extension you have installed that might be the problem. https://github.com/microsoft/vscode/issues/139280
