### ISSUE TITLE
Terminal resizing does not take position into account

### ISSUE THREAD

**Issue by jmg-duarte** [microsoft/vscode#140873]
As the title states, the resize action does not take into account the position of the terminal.

If the terminal is on the left, I would expect the `resizePaneLeft` action to enlarge the terminal, etc.

Example:
![2022-01-17 20-41-20](https://user-images.githubusercontent.com/15343819/149835035-6363c762-0224-4378-8815-aec766a28a57.gif)

https://github.com/microsoft/vscode/blob/00b535ca43cc93f43b9599cd5f6e62a20569af0e/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L331-L370

I did a quick dive into the code and think that it could be easily added if the terminal position is available in the snippet above.

**Comment by jmg-duarte** [comment]
I had submitted this for so long I even forgot about it! Glad to see the VSCode team doing backlog. Great job! ❤️

**Comment by Tyriar** [comment]
Thanks for the report, we get pretty behind on issues sometimes 😅
