### ISSUE TITLE
git.autoRepositoryDetection setting seems to have no effect

### ISSUE THREAD

**Issue by ak5k** [microsoft/vscode#140800]
Issue Type: <b>Bug</b>

Setting `git.autoRepositoryDetection` to true, false, subFolders or openEditors seems to have no effect. 

After setting git.autoRepositoryDetection to false (for both user and workspace) and then opening a workspace, Visual Studio Code still detects Git repositories from current, parent or subfolders.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (8 x 3792)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (24.82GB free)|
crash-reporter-id a836ae33-3ec4-4cfd-b783-0e44ad433173|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
armview|ben|0.4.5
doxdocgen|csc|1.3.2
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.1.0
better-cpp-syntax|jef|1.15.10
azure-pipelines|ms-|1.195.0
vscode-azureappservice|ms-|0.23.0
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
vscode-azurevirtualmachines|ms-|0.4.1
vscode-bicep|ms-|0.4.1124
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.18.0
vscode-dotnet-runtime|ms-|1.5.0
vscode-edge-devtools|ms-|1.4.2
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.63.13
azure-account|ms-|0.9.11
azurecli|ms-|0.5.0
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
vscode-node-azure-pack|ms-|0.2.1
azurerm-vscode-tools|msa|0.15.5
cmake|twx|0.0.17
vim|vsc|1.21.10

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710cf:30416617
vsccppwtstudy:30421978

```

</details>

**Comment by lszomoru** [comment]
@ak5k, thanks for filing the issue. As of right now, the setting controls scanning repositories that are not in the root workspace folder which is being opened in VS Code. We could probably improve on the documentation but we are also opened to behaviour change. Could you please share your scenario in which you would like to disable repository detection completely? Thank you!

**Comment by ak5k** [comment]
Hi! In my scenario workspace root (CMake project) is a Git repository, and it has submodules (which in turn have submodules etc). It seems no matter what combination I set for repository and submodule or modification detection, the root repository and its submodules and their modifications are always detected. If it's meant to work this way when workspace root is a Git repository, then it isn't really a problem. But if behaviour is to change, I would like the possibility to ignore submodules and/or their modifications and/or the entire root repository itself, even when the VSCode workspace root is also a Git repository.

**Comment by lszomoru** [comment]
Thanks for the additional context. I will factor that in, when discussing whether we want to adjust the behaviour.

**Comment by davidstone** [comment]
Ran into the same issue and was super confused why repositories I didn't want kept being reopened. `git.repositoryScanIgnoredFolders` also didn't seem to do anything.

My use case is a top-level repository that contains a `dependencies` directory that is filled with git submodules. Some of these are truly third-party code that I am unlikely to modify, so I don't want those cluttering my source control view. Some of them are other libraries that I maintain -- it's reasonable for me to develop code in there and push it up. `openEditors` seemed like the right setting, because once I opened up a file I can do any git commands I need and I won't "forget" that I edited something, so I was disappointed to find that it doesn't do what I expected.

**Comment by janakg** [comment]
Facing the same issue for a similar use case

**Comment by adab4d** [comment]
@neg2led 

>The inability to prevent the git extension from automatically recursing through every repository in a workspace is utterly infuriating

Thanks for putting in prose my frustration.

**Comment by anddam** [comment]
@neg2led 

>The inability to prevent the git extension from automatically recursing through every repository in a workspace is utterly infuriating

Thanks for putting in prose my frustration.

**Comment by dprandle** [comment]
> either of these would make dealing with these nightmarishly huge metarepositories (like Zephyr and, well, Android/AOSP) so very very much nicer...

Or any git based workspace with any submodules - as reloading vscode happens pretty regularly for various reasons..

The biggest problem for me isn't the clutter - its needing to select the repo target for stage/commit actions every single stage/commit

**Comment by maerroc** [comment]
@neggles

> or conversely, explicitly specify which git repos to open automatically in a folder (whitelist as opposed to blacklist)

What I do is to add a .gitmodules file to the root project stating which subrepos I want VS Code to list:

```
[submodule "vendor/vendor1/module1"]
path = vendor/vendor1/module1
url = mandatory_dummy_string

[submodule "vendor/vendor1/module2"]
path = vendor/vendor1/module2
url = mandatory_dummy_string

[submodule "vendor/vendor2/module"]
path = vendor/vendor2/module
url = mandatory_dummy_string
```

**Comment by lszomoru** [comment]
@NiceneNerd, you can try disabling submodule detection using the `git.detectSubmodules` setting.

One should be able to ignore both repositories as well as submodules using the `git.ignoredRepositories` setting. You can either specify the absolute path of the repository/submodule or the path of the repository/submodule relative to a workspace folder. 

Starting with today's Insiders (2023-10-12) we have also made the following improvements related to "Close Repository":
1. Closed repositories do not get automatically reopened when opening a file from the repository
2. Closed repositories will be remembers per workspace
3. Added a new command, `Reopen Closed Repositories...` to the command palette to reopen a repository that has been closed

**Comment by juliuscrn** [comment]
I wish there was an option to have Atom-style toggling between repositories. In Atom git pane displays only the project that was last active (i.e. you had it open in the editor). VS Code source control pane is incredibly cluttered and frustrating to work with. I do not need to see all these projects, but I also don't want to remove them from my workspace.

**Comment by lszomoru** [comment]
@contang0, please feel free to file a feature request as your request is outside the scope of this issue. Thank you!
