### ISSUE TITLE
Can't create tasks.json when a user-wide tasks.json already exists

### ISSUE THREAD

**Issue by raulsntos** [microsoft/vscode#140867]
Issue Type: <b>Bug</b>

In a workspace without a `tasks.json` file the option `Create tasks.json file from template` does not appear if a `tasks.json` file already exists in the user directory `$HOME/.config/Code/User/tasks.json` so I can't create a `tasks.json` file for the current workspace.

Probably due to 18e70eb636e20d51ae0f183d600662ead015427a that only checks when a non-contributed task exists regardless of whether it comes from the user or the workspace.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.15.11-76051511-generic
Restricted Mode: No

**Comment by alexr00** [comment]
@raulsntos which command are you running?

**Comment by alexr00** [comment]
To verify:
1. Open a folder that doesn't have a tasks.json file
2. Create a user task if you don't have one already ("Tasks: Open User Tasks")
3. "Tasks: Configure Task"
4. Verify that you see your user task in the "configure" picker. Verify that you also see an option to create a tasks.json from a template. Verify that the create-from-template options creates a folder tasks.json.

**Comment by raulsntos** [comment]
Tested in `1.64.0-insider` in a folder without a `tasks.json` file and with user tasks, but I still don't see the `Create tasks.json file from template` option.

![image](https://user-images.githubusercontent.com/3903059/150825335-a1b8fb2a-2c3c-4c0f-a026-32bb3bf45453.png)

Version: 1.64.0-insider
Commit: 2c967bf892d52550fabae08347faae57a4539b03
Date: 2022-01-24T05:15:08.896Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.15.15-76051515-generic
