### ISSUE TITLE
Incorrect result of the input

### ISSUE THREAD

**Issue by ash-khola** [microsoft/vscode#140850]
Issue Type: <b>Bug</b>

I have written a simple programm to calculate the cube of 5 and acoording to human brain the expected output is "125" but the vs code is giving the output as "124" which is not the correct answer from any logic.
It should be corrected asap to avoid further possible isuues, in the programm.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.86GB (0.43GB free)|
|Process Argv|--crash-reporter-id aa268803-6c4c-4644-838d-a59c7d37fa3c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
code-runner|for|0.11.6
vscode-pull-request-github|Git|0.34.3
better-cpp-syntax|jef|1.15.10
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.0-insiders2
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5242
vsliveshare-audio|ms-|0.1.91
material-icon-theme|PKi|4.11.0
cmake|twx|0.0.17

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710cf:30416617
vsccppwtstudy:30421978

```

</details>

![VS_Code_bug_report](https://user-images.githubusercontent.com/97885856/149759255-6a6823d8-0362-4aff-b89f-dffc2eec0386.png)

**Comment by weinand** [comment]
VS Code does not have built-in functionality to compile and run C programs. 
So the erroneous result you are seeing is not produced by VS Code but by some of the extensions you are using.
You might want to file the issue against the C/C++ extension.
