### ISSUE TITLE
The 'x' icon on the tab should be moved to the Left (from right)

### ISSUE THREAD

**Issue by Scoodood** [Microsoft/vscode#14085]
- VSCode Version: 1.6.1
- OS Version: OSX 10.10.5

**Feature Suggestion**
1. The 'x' icon on the tab should be moved to the left (from right) so that its position is fixed relatively to the tab's origin (upper left corner), allowing users to close multiple tabs very quickly when the tab width are different.

**How to Replicate the Issue**
1. Create 8 dummy files with the file name length of 10, 15, 20, 25, 30, 35, 40, 45 characters.
2. Open and view them all with VSCode, you should now have 8 tabs opened horizontally side by side with different tab width.
3. Now starting from the left most tab, close each tab one by one VERY QUICKLY by clicking the 'x' icon on each tab.
4. You will find that you have to reposition your mouse cursor on each tab in order to hit the 'x' icon, which is tedious. This is because the 'x' position is not fixed with relative to the tab origin (upper left corner).

**Resolution**
1. By relocating the 'x' to the left of the tab, the 'x' position is now fixed relative to the tab origin. You can close all tabs very quickly without having to reposition your mouse cursor when the tab width are different.
2. UI mockup
![screen shot 2016-10-24 at 5 17 39 pm](https://cloud.githubusercontent.com/assets/15989924/19668646/0450edd2-9a0e-11e6-825e-f7c5e04ecbfe.png)
3. You can also try this out on Safari browser (x on the left) vs Chrome browser (x on the right).

**Comment by roblourens** [comment]
`cmd+w`? :) Currently the file icon is on the left.

**Comment by bpasero** [comment]
I disagree that we need to move the X to the left to allow for smooth closing. I think we can achieve smooth closing by leaving it on the right and making the sizing on close smarter so that the X always stays under the mouse.

**Comment by bpasero** [comment]
We ship a new setting to control the location of the close button (including left, right and off).
