### ISSUE TITLE
Please help me with Python Debugger

### ISSUE THREAD

**Issue by MrGoldSky** [microsoft/vscode#140917]
I am unable to run the debugger in python. As soon as I click debug, the debug window opens and after a couple of seconds it closes itself. I found the answer on google, it says to click on Set as Startup File. However, I don't understand where I can find it.

Link on YouTube https://youtu.be/3nL5tVByV_k

**Comment by weinand** [comment]
Maybe your program just runs to completion without producing any output?
Please set a breakpoint in your code so that the debugger can stop and you can single step from there.

**Comment by MrGoldSky** [comment]
> 

Yes, I can put a breakpoint, but then the whole code with all the loops is executed and I have no control over it. I used to be able to run the program line by line

**Comment by weinand** [comment]
If you set a breakpoint then debugging should stop there.
Then you can run your program line by line with the "Step Over" button (or F10)
