### ISSUE TITLE
make top most Workspace Folder sticky (in File Explorer)

### ISSUE THREAD

**Issue by sillyslux** [microsoft/vscode#140971]
In a scrolled File Explorer with multiple Workspace Folders, it would be nice to see which root folder the top most files belong to.
The 3rd option shows what it could look like, if #140007 was applied as well.

![150142256-94c65e55-893f-4866-ac81-ff50a5199faf](https://user-images.githubusercontent.com/10578906/151675485-8a11f3d1-4734-42fd-ab05-71a55586d531.png)

**Comment by OnkelTem** [comment]
I recorded a little demonstration to clarify the request:

https://github.com/microsoft/vscode/issues/140971

**Comment by JacksonKearl** [comment]
This is a fair feature request that has come up in some form or another a few times before, including the general case of having every parent folder appear as a breadcrumb when they're out of scroll view (not just the root workspace folder). 

cc @joaomoreno do you have an idea of how big of a change to the tree widget it would be to support something like this?

**Comment by joaomoreno** [comment]
Might not be too hard to get something going, but the edge cases will be brutal. Namely, what happpens with keyboard/mouse selection, drag and drop, etc.

**Comment by sillyslux** [comment]
I'd make it so that the sticky element isn't part of the file explorer. I'd just make it hover there for informative purposes. Only the arrow button would interest me, to fold the tree.
If you try to drop something on it, the explorer below starts scrolling anyway. My instinct tells me to wait for the scroll to end before dropping. Drop targets are highlighted, i wait for the highlighting to appear. That means, i'd wait for the real element to appear and drop on that. Drop actions on the sticky element, can be discarded.
I would also ignore drag and click actions, you could scroll up on click, instantly to the point where the sticky element is replaced by the real element, although, i don't see the benefits.
