### ISSUE TITLE
Missing Sublime Text command - Go to symbol in project

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#14091]
While building this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings) to map Sublime Text default keyboard shortcuts to VS Code, I found that this feature is missing. 

The feature is go to symbol in project.

**Default Sublime Text keybindings**
Windows / Linux: <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>r</kbd>
Mac: <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>r</kbd>

![goto_symbol_in_project](https://cloud.githubusercontent.com/assets/2449568/19565274/20862f7e-969b-11e6-98ea-d035b9c00e54.png)

**Comment by bpasero** [comment]
@waderyan whats wrong with `workbench.action.gotoSymbol` ?

**Comment by waderyan** [comment]
@bpasero good question. Sublime Text supports this operation **workspace wide**. As far as I can tell we only support this for the open file.

**Comment by bpasero** [comment]
@waderyan right, I mixed up the command id: `workbench.action.gotoSymbol` is for the current file and `workbench.action.showAllSymbols` for any file in the workspace.

**Comment by waderyan** [comment]
Awesome! Added to the extension.

**Comment by kentor** [comment]
Isn't the behavior different? In sublime's cmd+shift+r we can fuzzy search for any symbol in the project. In vscode, this only searches for symbols in files that are opened (under "Open Editors").

Is symbol search over project files, even if they are not opened, not currently possible?

**Comment by waderyan** [comment]
@kentor thank you for your message. Is what you are looking for captured in this open issue? https://github.com/Microsoft/TypeScript/issues/9737

**Comment by kentor** [comment]
I don't think so? My project is full of CommonJS modules and symbol search works, but again only on files that are open. Sublime's would work on files in the project that were never opened.
