### ISSUE TITLE
Missing Sublime Text command - select open editor by index

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#14095]
While building this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings) to map Sublime Text default keyboard shortcuts to VS Code, I found that this feature is missing. 

The feature is selecting an open editor by index. 

**Default Sublime Text keybindings**

| Windows / Linux | Mac | Editor Index | 
| ----------------- | ----- | ----------- | 
| <kbd>alt</kbd>+<kbd>1</kbd> | <kbd>cmd</kbd>+<kbd>1</kbd> |  0 | 
| <kbd>alt</kbd>+<kbd>2</kbd> | <kbd>cmd</kbd>+<kbd>2</kbd> | 1 | 
| <kbd>alt</kbd>+<kbd>3</kbd> | <kbd>cmd</kbd>+<kbd>3</kbd> | 2 |
| <kbd>alt</kbd>+<kbd>4</kbd> | <kbd>cmd</kbd>+<kbd>4</kbd> | 3 |
| <kbd>alt</kbd>+<kbd>5</kbd> | <kbd>cmd</kbd>+<kbd>5</kbd> | 4 |
| <kbd>alt</kbd>+<kbd>6</kbd> | <kbd>cmd</kbd>+<kbd>6</kbd> | 5 |
| <kbd>alt</kbd>+<kbd>7</kbd> | <kbd>cmd</kbd>+<kbd>7</kbd> | 6 |
| <kbd>alt</kbd>+<kbd>8</kbd> | <kbd>cmd</kbd>+<kbd>8</kbd> |  7 |
| <kbd>alt</kbd>+<kbd>9</kbd> | <kbd>cmd</kbd>+<kbd>9</kbd> |  8 |
| <kbd>alt</kbd>+<kbd>0</kbd> | <kbd>cmd</kbd>+<kbd>0</kbd> |  9 |

![select_editor_by_index](https://cloud.githubusercontent.com/assets/2449568/19565543/082bc2bc-969c-11e6-8fc6-16728efcbe36.gif)

**Comment by bpasero** [comment]
@waderyan nope, we have it: `workbench.action.openEditorAtIndex1-9`

**Comment by waderyan** [comment]
@bpasero excellent great!
