### ISSUE TITLE
WSL2: Terminal does not open in working directory - open again

### ISSUE THREAD

**Issue by ctellechea2001** [microsoft/vscode#140909]
Could you please inform how can resolve this issue? 

Opening the terminal for a WSL2 instance (Ubuntu 20.04 in this case: **code .**) defaults to the path mounted at /mnt/c/users/carlos/AppData/Local/Programs/Microsoft VS Code instead of the working directory.

Related unresolved issue: https://github.com/microsoft/vscode/issues/116135

**Comment by ctellechea2001** [comment]
![imagen](https://user-images.githubusercontent.com/45426180/149973217-6904fa5c-86e6-45fe-bda3-4f8e70b29b9d.png)

**Comment by ctellechea2001** [comment]
@mojodna @meganrogge @doudou @threeve

**Comment by meganrogge** [comment]
can you share your settings.json?

**Comment by ctellechea2001** [comment]
{
    "workbench.colorTheme": "Default Dark+",
    "scm.alwaysShowActions": true,
    "scm.alwaysShowRepositories": true,
    "editor.inlineSuggest.enabled": true,
    "github.copilot.enable": {
        "*": true,
        "yaml": true,
        "plaintext": false,
        "markdown": false
    },
}

![imagen](https://user-images.githubusercontent.com/45426180/149974747-68852fa4-579f-4085-b069-6c0745ba2a1b.png)

**Comment by meganrogge** [comment]
and what happens if you set `terminal.integrated.cwd` explicitly?

**Comment by ctellechea2001** [comment]
I set that and nothing is happens. I tried with 

terminal.integrated.cwd= "."
terminal.integrated.cwd= "${workspaceFolder}"

and the settings is ignored!.

**Comment by Tyriar** [comment]
Can you share a screenshot of the whole window, including the explorer sidebar?

**Comment by ctellechea2001** [comment]
![imagen](https://user-images.githubusercontent.com/45426180/149996413-e918cf8e-6ae5-4b60-b3c6-db3118d57981.png)

**Comment by ctellechea2001** [comment]
@Tyriar 

if i put a wrong folder I am checking that the terminal is not opening but the path is correct. I think that the path is changed after terminal in vscode is executed.

![imagen](https://user-images.githubusercontent.com/45426180/149999495-f3f4c7be-905f-4409-a998-2434a8dddfd6.png)


![imagen](https://user-images.githubusercontent.com/45426180/149999459-18d792be-c700-4406-a6d5-ed0e1a4371b5.png)

**Comment by ctellechea2001** [comment]
Another information

![imagen](https://user-images.githubusercontent.com/45426180/150002085-c1a66c68-4e2d-489b-a334-459178128a7c.png)

**Comment by ctellechea2001** [comment]
@mojodna @meganrogge @doudou @threeve @Tyriar

**Comment by mojodna** [comment]
@ctellechea2001 please stop tagging arbitrary people. That I’ve had a single PR accepted in this project (a typo fix!) does not mean I can help you.

**Comment by ctellechea2001** [comment]
sorry for that! Could you help me?

**Comment by ffyuanda** [comment]
same issue here

**Comment by Tyriar** [comment]
Remove the terminal.integrated.cwd setting, that's meant to be an absolute or relative path.
