### ISSUE TITLE
Missing Sublime Text command - Break / wrap line

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#14093]
While building this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings) to map Sublime Text default keyboard shortcuts to VS Code, I found that this feature is missing. 

The feature is break / wrap line. 

**Default Sublime Text keybindings**
Windows / Linux: <kbd>alt</kbd>+<kbd>q</kbd>
Mac: <kbd>cmd</kbd>+<kbd>alt</kbd>+<kbd>q</kbd>

![break_line](https://cloud.githubusercontent.com/assets/2449568/19565360/62677af6-969b-11e6-9196-fa59593d4be9.gif)

**Comment by madig** [comment]
This would be very useful to have! Atom has Alt+Q which breaks lines and even correctly handles comments in source code. I currently have to break comments up manually :( There's the "Reflow Markdown" extension, but that breaks in source code.
