### ISSUE TITLE
Missing Sublime Text command - Change case of selection

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#14096]
While building this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings) to map Sublime Text default keyboard shortcuts to VS Code, I found that this feature is missing. 

The feature is changing the case of the selection to upper and lower case. 

**Default Sublime Text keybindings**

| Case change | Windows / Linux | Mac |
| --- | --- | --- |
| Upper case | <kbd>ctrl</kbd>+<kbd>k</kbd> <kbd>ctrl</kbd>+<kbd>u</kbd> | <kbd>cmd</kbd>+<kbd>k</kbd> <kbd>cmd</kbd>+<kbd>u</kbd> |
| Lower case | <kbd>ctrl</kbd>+<kbd>k</kbd> <kbd>ctrl</kbd>+<kbd>l</kbd> | <kbd>cmd</kbd>+<kbd>k</kbd> <kbd>cmd</kbd>+<kbd>l</kbd> |

![upper_lower_case](https://cloud.githubusercontent.com/assets/2449568/19565852/3481b5b4-969d-11e6-8458-42da4bdbbb63.gif)

Today an [extension exists](https://marketplace.visualstudio.com/items?itemName=wmaurer.change-case) with this functionality. I think this is a good feature to bring into the core of the product.

**Comment by gandhis1** [comment]
As there are extensions to do this (https://github.com/wmaurer/vscode-change-case), I think there's sufficient demand for this feature, and reason to include it for all users. Definitely essential for any text-editor.

**Comment by waderyan** [comment]
@gandhis1 thank you for your feedback. I opened this issue so I agree with you. I've been trying to come up with specific use cases where this is helpful. Can you help me by adding a couple others?

**Use Cases:**
1. Constants are often all caps. While refactoring you may want to change a variable to use all caps. 
2. Inverse of 1.

**Comment by gandhis1** [comment]
I mostly use it to correct improperly formatted SQL queries (keywords should be capitalized, and names lowercase).

**Comment by tangmi** [comment]
This feature composes especially well with multi-cursor selection--e.g. if one has the identifiers `foo`, `bar`, and `baz`, and wants to make `getFoo() { }` and so on, they can simply select the first letters of each of the identifiers, uppercase, and prepend with `get`.

**Comment by lipis** [comment]
When pasting multiple things from variables/enums.. then you can multi select the first letters and transform them into capital letters if you want to use them as labels :)
