### ISSUE TITLE
File not marked as resolved after using command palette to stage file

### ISSUE THREAD

**Issue by Nokel81** [microsoft/vscode#140981]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Start a git action that causes file X to have conflicts
2. Resolve the conflicts
3. Use the command palette to do the `git.stage` command
4. Observe that the file is still displayed as having conflicts.

**Comment by lszomoru** [comment]
@Nokel81, apologies for not getting back to you on this until now. I was wondering if you are still able to reproduce this issue? Thanks!

**Comment by Nokel81** [comment]
I haven't noticed exactly the same bug I have noticed that I cannot mark files that I delete during a merge as "resolved" if they initially had some git conflicts. I have to fallback to use the `git` CLI.

**Comment by lszomoru** [comment]
@Nokel81, would you be able to provide a recording (https://gifcap.dev) so that I can further investigate the issue? Thanks!

**Comment by lszomoru** [comment]
Closing the issue as I was never able to reproduce this and investigate further.
