### ISSUE TITLE
Incorrectly scaled window menu on 2nd monitor

### ISSUE THREAD

**Issue by gplumb** [microsoft/vscode#140931]
Issue Type: <b>Bug</b>

1. Run Windows 11 on a dual monitor setup (Laptop + external monitor at lower resolution / DPI than the Laptop)
2. Run VS Code and drag to 2nd monitor
3. Right-click on title bar to reveal system shell menu

You will notice that if the scaling for the system menu is incorrect (It's sized for the primary monitor's scaling, not the secondary's):

![DpiQuirk](https://user-images.githubusercontent.com/741350/149997306-66c41550-1216-49ed-b1c6-e8dcf0a21039.png)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.77GB free)|
|Process Argv|--crash-reporter-id 7aeeeb56-39f3-4c9e-af30-8a9b39f7885d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.19.0
remote-containers|ms-|0.209.6

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/85898
