### ISSUE TITLE
Add support for slurm node debugging

### ISSUE THREAD

**Issue by gonidelis** [microsoft/vscode#140925]
VS Code currently does not support a debugging session for a slurm node (interactive session using srun). Adding srun as the main program and giving the executable as argument would not work as srun will run to completion even if the executable throws a segfault.

Following are the ways I've tried to run a debugging session:
1. Provide the whole srun command to the program name in **launch.json**: `srun -p <node_name> -N 1 --pty <executable_name>`
2. Provide srun as program name and executable in the **args** section along with executable's arguments
3. Try running vs code directly in an interactive session  (the node doesn't support it)

**Comment by connor4312** [comment]
I'm not at all familiar with slurm. PR's welcome.
