### ISSUE TITLE
very long delayed in code run in c language 

### ISSUE THREAD

**Issue by prathammalviya1** [microsoft/vscode#140903]
very long delayed in code run in c language . supposed if i run at that time then it takes 2-5 min to execute in terminal and some time it will not executed and someting it  more than 5 min also even in simple printf satement if i executed that that takes some much time to execute in terminal. i have also reinatalled the vs code and MYSYS2 minGW 64 bit from vs code website.
kindly providing me help, it is very distrubed me during coding please help me.

**Comment by meganrogge** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
