### ISSUE TITLE
Introduce a command to open the most recent link of a particular type

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140923]
Also can think about idea for maintaining history of the link that was clicked (invalidate on LF in terminal?) https://github.com/microsoft/vscode/issues/95570#issuecomment-1013666771

**Comment by alexr00** [comment]
I tried the following:
1. Start the VS Cod build task.
2. Generate some build errors.
3. Focus on the build terminal with the errors
4. "Terminal: Open Most Recent File Link"
5. Nothing happens.

Am I doing something wrong?

**Comment by Tyriar** [comment]
Sorry this is actually captured in a test plan (#141342).
