### ISSUE TITLE
Layer breaker in `quickinput.test.ts`

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#140983]
Code from `vs/base` should not import code from `vs/platform`. Please move the test to `vs/platform` or remove the import and use `IListOptions<T>` instead of `IWorkbenchListOptions<T>` in the test:

https://github.com/microsoft/vscode/blob/6997390c367a5aa05285473e0a6409a3e74691cc/src/vs/base/parts/quickinput/test/browser/quickinput.test.ts#L11-L14

This import came in via https://github.com/microsoft/vscode/commit/358b28f3932cf67b898b536016c7334e0a7eed7a

(ref #140857 #140874)

**Comment by TylerLeonhardt** [comment]
How did I mess this up without breaking CI? 🤔

**Comment by alexdima** [comment]
Our layering rules were incomplete. This is now flagged by the eslint rule (since https://github.com/microsoft/vscode/commit/62b0d5cb815aa8161ffdb6550ed1787e4bffdd17)
