### ISSUE TITLE
Search workspace bar, alt + arrow key doesn't jump words

### ISSUE THREAD

**Issue by tallalnparis4ev** [microsoft/vscode#140937]
When editing files in VSCode (Mac) I always use alt + left/right arrow key to jump between words, like so:
![vscodeissue](https://user-images.githubusercontent.com/47358379/150020076-75abf905-e5d3-4551-8b82-5fa1c3cc2372.gif)

However, in the search workspace bar, here:
![image](https://user-images.githubusercontent.com/47358379/150020139-8d49118d-fdc3-4cee-bca9-aa257b6e945a.png)
I cannot use the alt + left/right arrow keys to jump between words.

Is there some way such that I can enable the alt + left/right arrow keys to jump between words in the search bar? Or is this a desirable feature, if so I would quite enjoy looking at implementing it.

**Comment by roblourens** [comment]
It works for me and should work as far as I know. Is it possible that you have another keybinding registered which intercepts it? It may also come from an extension.
