### ISSUE TITLE
github workflow and local actions

### ISSUE THREAD

**Issue by cmeissner** [microsoft/vscode#140913]
Issue Type: <b>Bug</b>

Currently I'm working on a custom javascript action. That action supports input parameters. To test the action a also created a workflow which uses the action locally `./`.
Unfortunately the editor reports all parameters in `with` dict as unsupported. But this isn't correct. 
If I change the value of `uses` to the latest tag `<org>/<action>@<tag>` no errors will be reported.

This is not a fuctional issue but I is a bit confusing for anybody who started to work on actions or with workflows which uses local actions. 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.11.0-46-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2300)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.33GB (0.61GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 6ab71b07-2363-4dca-8a92-05ebf94ccfea|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.4.0
better-toml|bun|0.3.2
gitignore|cod|0.7.0
vscode-github-actions|csc|0.21.3
vscode-markdownlint|Dav|0.45.0
jekyll-run|Ded|1.7.0
githistory|don|0.6.19
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
ginfuru-vscode-jekyll-syntax|gin|0.1.1
vscode-jekyll-snippets|gin|0.9.3
copilot|Git|1.7.4608
remotehub|Git|0.20.0
vscode-pull-request-github|Git|0.34.3
vscode-test-explorer|hbe|2.21.1
restructuredtext|lex|168.0.0
ruby-rubocop|mis|0.8.6
vscode-docker|ms-|1.18.0
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
test-adapter-converter|ms-|0.1.5
autodocstring|njp|0.5.4
ruby|reb|0.28.1
vscode-commons|red|0.0.6
vscode-yaml|red|1.3.0
jinjahtml|sam|0.16.0
html-preview-vscode|tht|0.2.5
python|tht|0.2.3
simple-rst|tro|1.5.1
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-maven|vsc|0.34.2
vscode-icons|vsc|11.8.0
gitblame|wad|8.1.0
vscode-ruby|win|0.28.0
ansible-vault-inline|wol|0.4.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30421291
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710cf:30416617
vsccppwtstudy:30421978

```

</details>

**Comment by mjbvz** [comment]
Without an example otherwise, this sounds like an issue with the GitHub actions tooling and not with VS Code itself. Please start by filing the issue against them
