### ISSUE TITLE
splitting a terminal via the tab dropdown menu does not inherit cwd

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#140941]
also suspect the context menu split won't work either

https://github.com/microsoft/vscode/blob/212a8ca457177c1b41fd839a1977ba0cd2dabc1a/src/vs/workbench/contrib/terminal/browser/terminalMenus.ts#L739-L784

_Originally posted by @meganrogge in https://github.com/microsoft/vscode/issues/140939#issuecomment-1015933001_

**Comment by meganrogge** [comment]
oh, can't because that is async?

**Comment by ChaseKnowlden** [comment]
No, it is not async.

**Comment by meganrogge** [comment]
Hey @ChaseKnowlden thanks for the PR. this is the issue i'm talking about here related to the code above that I referenced. Your change has to do with the terminal location
![Recording 2022-01-18 at 20 49 40](https://user-images.githubusercontent.com/29464607/150054624-3783d314-0b1e-4455-b1cb-7002617ecc45.gif)
