### ISSUE TITLE
Disabling CSS Hover documentation in VUE files is ignored `css.hover.documentation`

### ISSUE THREAD

**Issue by katerlouis** [microsoft/vscode#140963]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: macOS 12.0.1

Steps to Reproduce:

1. Disable `css.hover.documentation`, `css.hover.references`, `scss.hover.documentation` and `scss.hover.references`
2. Edit a `*.vue` file with the following structure:

```vue
<template>
  <div>I'm a happy component</div>
</template>

<style lang="scss" scoped>
div {
  background: blue; // hover this line to still see a MDN reference tooltip
}
</style>
```

3. Hover a css property

What I expect:
No tooltip at all.

:(

**Comment by aeschli** [comment]
You need to file this against the vue extension: https://github.com/vuejs/vetur/issues
