### ISSUE TITLE
Missing Sublime Text command - repeat

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#14097]
While building this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings) to map Sublime Text default keyboard shortcuts to VS Code, I found that this feature is missing. 

The feature is repeating last keyboard action. 

**Default Sublime Text keybindings**
Windows / Linux: <kbd>ctrl</kbd>+<kbd>y</kbd>
Mac: <kbd>ctrl</kbd>+<kbd>y</kbd>

![repeat_last](https://cloud.githubusercontent.com/assets/2449568/19565959/8c85e30c-969d-11e6-999a-af766a3aa876.gif)

**Comment by nox** [comment]
`ctrl+y` yanks text in Sublime on OS X, it doesn't repeat as your screenshot shows. I could not reproduce this behaviour.

**Comment by nox** [comment]
This is `cmd+y` on OS X.
