### ISSUE TITLE
Allow 3rd party extensions to the telemetry settings

### ISSUE THREAD

**Issue by fbricon** [microsoft/vscode#140972]
Red Hat published extensions expose a telemetry setting like:
```json
"redhat.telemetry.enabled": {
          "type": "boolean",
          "default": null,
          "markdownDescription": "Enable usage data and errors to be sent to Red Hat servers. Read our [privacy statement](https://developers.redhat.com/article/tool-data-collection).",
          "scope": "window"
        },
```

When opening the Telemetry settings menu, the settings UI filters on `@tag:telemetry`, but only shows the built-in Telemetry settings:

<img width="1246" alt="Screenshot 2022-01-19 at 14 57 44" src="https://user-images.githubusercontent.com/148698/150145202-336875e1-8807-46ef-8185-6eeb40b3af93.png">

You need to remove the `@tag:` prefix to be able to see our setting:
<img width="1267" alt="Screenshot 2022-01-19 at 14 58 25" src="https://user-images.githubusercontent.com/148698/150145208-6b109edf-4c88-4beb-8619-fe29220ef68a.png">

We'd like to be able to see telemetry settings contributed by 3rd party extensions, in that `@tag:telemetry` subset.
A "telemetry":boolean property could be added to configuration properties, or something more generic, like a "tags":array(strings).

**Comment by lramos15** [comment]
There's an interesting UX problem here as well. These settings fall under the application tab which is reserved for core VS Code settings. All extension settings have always fallen under the extensions group so we don't have a concept of a mixed group.

cc @rzhao271 for thoughts

**Comment by fbricon** [comment]
@lramos15 thanks it works. I actually tried it before I opened this ticket, but I somehow managed to do it wrong.
