### ISSUE TITLE
Idea: Don't highlight ambiguous/invisible characters when they are surrounded by non-latin-looking characters

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#140960]
Given this screenshot:
![image](https://user-images.githubusercontent.com/1473102/148699342-b06b33c9-07fc-4f1d-971a-e27bd17a65cc.png)

The highlight's don't make sense, as the surrounding characters clearly indicate that this character is to be expected.

Related: #140376

**Comment by justanotheranonymoususer** [comment]
This doesn't look like a good and secure implementation to me.
Consider the following code:
```
if (variable_א || variable_ב || vаriable_ג) {
    admin = true;
}
```
As far as I understand, nothing will be highlighted after the change. But paste the code to an editor before the change and you'll see why it's bad.

I think it should only skip the highlighting if the word contains only characters from a single language.

Also, there must be a way to disable this word-based highlighting exclusion.

**Comment by hediet** [comment]
Thanks for your input!

> As far as I understand, nothing will be highlighted after the change.

This is correct.

> This doesn't look like a good and secure implementation to me.

To be secure, we recommand configuring `"editor.unicodeHighlight.nonBasicASCII": true`. We don't guarantee security with the other settings, just heuristic protection against common unicode spoofing attacks.

Also, if you use non-basic ascii characters for identifiers, you are making yourself much more vulnerable for such attack.

> I think it should only skip the highlighting if the word contains only characters from a single language.

Might be worth to consider.

The rule would be:
* Highlight characters that look like ASCII or that are invisible
* ... unless this character is in a word where at least one character cannot be confused with an ASCII character **and all characters in that word have the same script**

(bold is new)
