### ISSUE TITLE
IntelliSense tips rendering on top of others and with wrong height

### ISSUE THREAD

**Issue by adamabernathy** [Microsoft/vscode#14092]
In some cases you can get into a mess where the IntelliSense tips render on top of another and where they do not scale to the amount of text provided.

- VSCode Version: 1.6.1
- OS Version: OSX 10.11.6 (15G1004)

Steps to Reproduce:

1. Included photos on how to reproduce this. For this example I just have a Python script with a few commands.

Case No. 1
<img width="1028" alt="screen shot 2016-10-20 at 8 55 57 am" src="https://cloud.githubusercontent.com/assets/5117513/19565230/60d5ad22-96a3-11e6-9f7a-4ffdef3ea9ed.png">

---

Case No. 2
<img width="1031" alt="screen shot 2016-10-20 at 8 57 59 am" src="https://cloud.githubusercontent.com/assets/5117513/19565237/642e48ee-96a3-11e6-814d-e1cffb811cca.png">

**Comment by DonJayamanne** [comment]
@adamabernathy this is an issue (https://github.com/DonJayamanne/pythonVSCode/issues/368) with the [Python extension](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python).
The issue has been resolved and fix will be in the next release.

**Comment by alexandrudima** [comment]
fyi @joaomoreno
