### ISSUE TITLE
[HTML] Emmet not formatting multiple elements (nav>a*6)

### ISSUE THREAD

**Issue by tuttifrutti19** [microsoft/vscode#140922]
nav.nav>a*6
It places all inline `<nav class="nav"><a href=""></a><a href=""></a><a href=""></a><a href=""></a><a href=""></a></nav>`
instead of line breaks
Does anyone know what's the matter?

**Comment by ArturoDent** [comment]
You need this:

```jsonc
"emmet.preferences": {
  "output.inlineBreak": 1,
},
```

**Comment by tuttifrutti19** [comment]
> You need this since all those `a` elements are inline elements:
> 
> ```js
> "emmet.preferences": {
>   "output.inlineBreak": 1,
> },
> ```
> 
> See, e.g. https://stackoverflow.com/a/66296921/836330,

super, it worked! thank u ❤
