### ISSUE TITLE
VScode update fails

### ISSUE THREAD

**Issue by FenryrMKIII** [microsoft/vscode#140958]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.57.0 (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

I am trying to update VScode. I receive an error message. Looking at the logs, I see VScode can't find a specific directory, namely : 
`Jan 19 08:31:41.955 INFO Reading directory: "C:\\Users\\XXXXX\\AppData\\Local\\Programs\\Microsoft VS Code\\gne\\CreateSimulationBucketFunction\\build_artifacts\\CreateSimulationBucketFunction\\build_artifacts\\CreateSimulationBucketFunction\\build_artifacts\\CreateSimulationBucketFunction\\build_artifacts\\CreateSimulationBucketFunction`

This seems to be related to some work I did at some point. But I don't understand why VScode needs that. And I certainly don't know how to resolve this error.

Any support would be appreciated. Thank you !

**Comment by pra15mesh** [comment]
Does Restarting the Desktop/Laptop and then trying to Update VScode worked?

**Comment by FenryrMKIII** [comment]
No, no change

**Comment by pra15mesh** [comment]
Ohk, try reinstalling the VSCode i know it's difficult or Wait for the
Expert to Provide Solution.

**Comment by joaomoreno** [comment]
@FenryrMKIII Is `CreateSimulationBucketFunction` your code? I highly recommend not placing your code inside VS Code's installation folder.

**Comment by FenryrMKIII** [comment]
It should be my code. But I don't think I ever touched VS code installation folder myself. And I don't see anything in VScode allowing me to understand how to remove this "dependency"

**Comment by joaomoreno** [comment]
Can you uninstall and reinstall VS Code?
