### ISSUE TITLE
split cwd not inherited when created via alt click of new with profile action

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#140942]
same with the create with profile quickpick

https://github.com/microsoft/vscode/blob/b560f60f6bbc57ff71bf45e56ebf436882e61230/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L220-L228

_Originally posted by @meganrogge in https://github.com/microsoft/vscode/issues/140939#issuecomment-1015933320_

**Comment by rzhao271** [comment]
What are some verification steps for this issue?

**Comment by meganrogge** [comment]
- have an active terminal in a directory `a`
- have `terminal.integrated.splitCwd: inherit`
- run `Terminal: create new with profile`
- while clicking one in the quick pick, press alt
- it should split the terminal and the cwd in that terminal should be `a`
