### ISSUE TITLE
Can't open or show commands

### ISSUE THREAD

**Issue by Zingo21** [microsoft/vscode#140910]
Issue Type: <b>Bug</b>

1. Open the command palette 
2. Type show all commands and try to click. 

I was expecting to see all the commands and also being able to change some commands.

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 6, 16|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 32038472-23da-4d4c-ab49-4e25654c066a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (73)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
namespace|adr|1.1.2
TabOut|alb|0.2.1
shaderlabvscodefree|aml|1.2.8
icons-carbon|ant|0.2.4
git-urgent|ara|1.0.0
unity-code-snippets-improved|ble|1.4.1
vscode-intelephense-client|bme|1.8.0
unity-code-snippets|cem|0.1.0
bracket-pair-colorizer-2|Coe|0.2.2
dart-code|Dar|3.32.0
flutter|Dar|3.32.0
vscode-markdownlint|Dav|0.45.0
dendron|den|0.77.1
dendron-markdown-shortcuts|den|0.12.1
dendron-paste-image|den|1.1.0
xml|Dot|2.5.1
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
unity-dev-pack|fab|2.4.1
fauna|fau|1.8.1
php-debug|fel|1.22.0
vscode-solution-explorer|fer|0.4.5
auto-using|Fud|0.7.15
remotehub|Git|0.20.0
vscode-pull-request-github|Git|0.35.2022011809
vscode-git-add-and-commit|iva|2.1.1
docomment|k--|0.1.30
intellij-idea-keybindings|k--|1.5.0
swift|Kas|0.2.0
unity-code-snippets|kle|1.3.0
git-tree-compare|let|1.13.2
google-fonts|lio|0.0.1
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.16
csharp|ms-|1.23.17
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
brackets-keybindings|ms-|0.1.1
brackets-pack|ms-|0.1.1
live-server|ms-|0.2.12
powershell|ms-|2021.12.0
vs-keybindings|ms-|0.2.1
vsliveshare|ms-|1.0.5242
debugger-for-chrome|msj|4.13.0
unity-toolbox|pix|1.0.6
material-icon-theme|PKi|4.11.0
vscode-css-peek|pra|4.2.0
java|red|1.2.0
vscode-yaml|red|1.3.0
explorer-exclude-vscode-extension|Red|1.2.0
c-sharp-utilities|rev|0.3.2
LiveServer|rit|5.6.1
csharp-helper|roa|0.0.14
shader|sle|1.1.5
code-spell-checker|str|2.1.4
teamhub|Tea|14.0.8
html-preview-vscode|tht|0.2.5
unity-tools|Tob|1.2.12
luna-paint|Tyr|0.12.0
unity-debug|Uni|3.0.2
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2
change-case|wma|1.0.0
unity-snippets|Ycl|0.1.2
html-css-class-completion|Zig|1.20.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710:30416614
vsccppwtstudy:30421978

```

</details>

**Comment by gjsjohnmurray** [comment]
> I was expecting to see all the commands and also being able to change some commands.

What happens for you?

Does the behavior change after you run the `Start Extension Bisect` command?

/gifPlease

**Comment by Zingo21** [comment]
![Recording 2022-01-18 at 18 26 17](https://user-images.githubusercontent.com/82944718/149987606-fe100648-97a3-4bcb-be1d-32eb32f18b7e.gif)

For me nothing happens! I don't know how to use the extension bisect command yet 😅

**Comment by TylerLeonhardt** [comment]
Show All Commands opens the Command Palette. It's doing "nothing" because the Command Palette is already open. What did you expect to happen? Maybe you're looking for something else

**Comment by Zingo21** [comment]
> Show All Commands opens the Command Palette. It's doing "nothing" because the Command Palette is already open. What did you expect to happen? Maybe you're looking for something else

I was expecting to come to a page with all the commands for VS Code there I could also change some of the commands. I think now that i'm out at the wrong place. 🤔

**Comment by TylerLeonhardt** [comment]
You can't change the commands at this time, that would be https://github.com/microsoft/vscode/issues/50836

You can change the keybindings that are tied to any command if you want. To get there you can do: `CMD+K CMD+S`

If you wanna get more commands, you'd need to install an extension.

I think vscode is behaving as expected so I'm gonna close this.
