### ISSUE TITLE
bottom bar (showing errors, spaces, encoding etc) loses functionality after a certain size.

### ISSUE THREAD

**Issue by DevOps-DoDo** [microsoft/vscode#140906]
We have written the needed data into your clipboard because it was too large to send. Please paste
Issue Type: <b>Bug</b>

I've just noticed that the bottom bar on Code doesn't respond when the app is full screen.

![Screen recording 2022-01-18 14 01 49](https://user-images.githubusercontent.com/5068651/149953731-15181f0b-cc29-4fc8-b9a9-ecfc631d1fb2.gif)

I was trying to click the bell icon at the bottom right of the screen to see the notifications and it wouldn't select it, it just kept bring up the "Select Language Mode" prompt. Originally I thought it was my extended screen as it's old, but when I transferred the app to the main screen on my Chromebook, the same thing happened.
Stranger still, when I resize the window, the functionality returned; the smaller the window, the further right I could click.

I'm not sure what I've done to make this happen but it appears to be a dead zone in a box format from the bottom right corner and grows the larger the screen gets.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.10.90-13883-gc2edb212fd80
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (2 x 1607)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|6.48GB (6.45GB free)|
|Process Argv|--unity-launch --crash-reporter-id 8b1923db-b110-4b57-b9f7-954b8ee65223|
|Screen Reader|no|
|VM|60%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|9.1.0
auto-rename-tag|for|0.1.9
todo-tree|Gru|0.0.215
MagicPython|mag|1.1.0
git-graph|mhu|1.30.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
indent-rainbow|ode|8.2.2
material-icon-theme|PKi|4.11.0
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.15

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30421291
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710cf:30416617
vsccppwtstudy:30421978

```

</details>

**Comment by bpasero** [comment]
What Linux distribution / window manager is this?

**Comment by TarunavBA** [comment]
@bpasero its a ChromeOS

**Comment by bpasero** [comment]
Maybe @deepak1556 you heard about this issue before? Not sure if ChromeOS is officially supported by VSCode? I am not finding it here: https://code.visualstudio.com/docs/supporting/requirements

**Comment by TarunavBA** [comment]
@bpasero maybe it's a lack of requirements issue. We can close it I think.

**Comment by bpasero** [comment]
Let's see.

**Comment by DevOps-DoDo** [comment]
> What Linux distribution / window manager is this?

It's using the Debian Linux shell inside ChromeOS, so should work on as if on Linux. Used to work fine, but now this issue has popped up.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by DevOps-DoDo** [comment]
I'll try that tomorrow, thank you

Dominic Ross
07738382996
***@***.***
DevOps_DoDo

**Comment by bpasero** [comment]
Any update?

**Comment by DevOps-DoDo** [comment]
I've just tried again, and it seemed to work with no issue. Must have been
an odd glitch with my laptop.

Sorry

Dominic Ross
07738382996
***@***.***
DevOps_DoDo

**Comment by NBS-LLC** [comment]
I can reproduce this issue on both the stable (1.65.2) and nightly (1.66.0) builds. I'm on a Chromebook using the default Linux container. I think I've isolated the issue to the fact that I have external monitor that is configured in portrait mode. Keep in mind that VSCode is not being displayed on this monitor. 

If I unplug the monitor, restart the Linux container then VSCode no longer exhibits a dead zone.
If I plug in the monitor, restart the Linux container then VSCode shows the dead zone issue.

BTW, I'm always running VSCode on another external monitor, always configured in landscape (normal) mode.

Let me know what other details I can provide :)

**Comment by DevOps-DoDo** [comment]
That mirrors my set up! Nicely done!

Dominic Ross
07738382996
***@***.***
DevOps_DoDo
