### ISSUE TITLE
typescript missing import  should trigger when only prefix match suggestion item

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#140918]
![image](https://user-images.githubusercontent.com/41773861/149972981-6a2461cd-7244-42f1-8a06-18956e66da78.png)

When I press dot `.`, VSCode auto complete:

![image](https://user-images.githubusercontent.com/41773861/149973096-64bd699b-3537-429a-a5d4-2f9bfac184ba.png)

test when all extension disable?

yes.

Version:

```
Version: 1.64.0-insider (Universal)
Commit: 23aa7ad51c95d90d48b1d352a316d7f0c2c4310d
Date: 2022-01-18T09:44:03.147Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0
```

@mattbierner

my settings: https://gist.github.com/tjx666/5256af269f9a3bb5784c5fa7789a58a8

**Comment by mjbvz** [comment]
This is by-design. If you don't want trigger characters like `.` to accept completions, set:

```json
"editor.suggestOnTriggerCharacters": false
```

**Comment by tjx666** [comment]
```
"editor.suggestOnTriggerCharacters": false
```
That setting disable properties suggest totally, but I just want not auto accept sueestion when only prefix match.

**Comment by mjbvz** [comment]
Sorry, should be `"editor.acceptSuggestionOnCommitCharacter": false`
