### ISSUE TITLE
Background colour of active file tab

### ISSUE THREAD

**Issue by prodv** [microsoft/vscode#140904]
Hi

The background colour of active file tab should be different so that it will be easier to recognoze.

**Comment by gjsjohnmurray** [comment]
I think you can [customize](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme) the `tab.activeBackground` color.

**Comment by sbatten** [comment]
@gjsjohnmurray is correct, thanks

**Comment by prodv** [comment]
Awesome!!

It works.
