### ISSUE TITLE
Terminal fechando sozinho / Terminal closing by himself

### ISSUE THREAD

**Issue by HandsonMatheus** [microsoft/vscode#140946]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows 10 Home 20H2 - 19042.1466

<html>
<body>

CPUs | Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 7.90GB (2.32GB free)
Process Argv | --crash-reporter-id 464d713c-e743-455b-99f2-2fd3979b7963
Screen Reader | no
VM | 0%

</body>
</html>

<html>
<body>
<div class="block block-extensions" style="box-sizing: border-box; font-size: 12px; color: rgb(204, 204, 204); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="block-info" id="systemInfo" style="box-sizing: border-box; background-color: rgb(60, 60, 60); color: rgb(204, 204, 204); width: 581.391px; font-size: 12px; overflow: auto; overflow-wrap: break-word; margin: 5px 5px 1.5em; padding: 10px;">

Extension | Author (truncated) | Version
-- | -- | --
bracket-pair-colorizer | Coe | 1.0.62
rails-snippets | Hri | 1.0.8
vscode-language-pack-pt-BR | MS- | 1.63.3
remote-wsl | ms- | 0.63.13
vscode-icons | vsc | 11.8.0
vscode-ruby | win | 0.28.0
beautify | Hoo | 1.5.0
ruby | reb | 0.28.1
vscodeintellicode | Vis | 1.2.15
vscode-ruby | win | 0.28.0

(1 theme extensions excluded)</div></div><br class="Apple-interchange-newline">
</body>
</html>

My vscode terminal close right away after try to open.
Doesn't matter if I'm using the shortcut or using the menu, the effect is the same.

I recorded a short video: https://i.imgur.com/9OIGmU3.mp4

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by HandsonMatheus** [comment]
Hey, @meganrogge, thanks for replying me!

I solved my problem just cleaning up the mess that I made on my `settings.json` and now everything's working fine.

Unfortunately I don't know what exactly I did to solve it, but the problem was definitively solved while I was working on it.
