### ISSUE TITLE
Add access to electron clipboard.readHTML() API for Extensions

### ISSUE THREAD

**Issue by fabiomanz** [microsoft/vscode#140976]
Hi,
in the Electron sandbox, you currently support the clipboard readText() and writeText() functions. I would like to use the clipboard.readHTML() function. More Information can be found [here](https://www.electronjs.org/docs/latest/api/clipboard).
Is there the ability, that you add this functionality to the vscode API? The other implementations are found [here](https://github.com/microsoft/vscode/blob/3774c64ce2161e0c95ebcb04d1f3ccffdc321af2/src/vs/platform/native/electron-main/nativeHostMainService.ts#L618).

**Comment by jrieken** [comment]
This isn't widely supported in browsers yet, so it likely won't happen soon
