### ISSUE TITLE
Consider moving tests from `vs/workbench/contrib/notebook/browser/contrib/*/test/`

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#140992]
`vs/workbench/contrib/notebook` is one of only 2 (the other being `welcome`) workbench contributions that is not flat. That is to say that it contains tests which are not located at `vs/workbench/contrib/notebook/test/LAYER/**`. Each notebook contribution has its tests next to its code, but this breaks a pattern that we follow throughout our sources where tests are placed in `contrib/*/test/LAYER` folders which are sibling to `contrib/*/LAYER` folders.

Please consider moving tests out of the `vs/workbench/contrib/notebook/browser/contrib/*/test/` folders and maybe into `vs/workbench/contrib/notebook/test/browser/contrib/*`. This would align with the other 59 workbench contributions and could lead to a simplification of our layering rules, where we now [need a special case for these notebook contributions tests](https://github.com/microsoft/vscode/blob/6ffa1d3786912241860dd3847655bc8fc8b571bb/.eslintrc.json#L275-L291).

(ref #140857 #140874)

**Comment by bpasero** [comment]
👍

**Comment by rebornix** [comment]
Thanks @alexdima , I like it more having test files in the same folder `/test/`

**Comment by alexdima** [comment]
Nice! Thank you! :heart:
