### ISSUE TITLE
SCM viewlet needing frequent manual updates

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#140955]
Found myself today several times needing to manually refresh the SCM viewlet before it'd let me commit (it thought the working directory was empty). I haven't seen this before so just heads up

**Comment by bpasero** [comment]
This could be a regression from adopting the file watching support: https://github.com/microsoft/vscode/commit/044092db5597de273b8fe7030332ec3454043102

However, this is not such a big change as it may seem, in the end we still use `fs.watch` on the provided path, though our watcher covers a lot more corner cases and is more complex:

https://github.com/microsoft/vscode/blob/b03fe7a97c06ae1906efd62e616d383704ee95e7/src/vs/platform/files/node/watcher/nodejs/nodejsWatcherLib.ts#L20

Some questions:
* do you have reliable repros?
* do you maybe open VSCode with the wrong path casing (i.e. the path you open is not the same as it is on disk)?

**Comment by bpasero** [comment]
@eamodio I think in a different issue you outlined what `GitLens` is doing to detect changes and it seems the patterns were a lot more complex. Have you noticed any regressions with using that watcher pattern over the past months? I wonder whether the Git extension should use the same patterns as you do to detect changes.

**Comment by JacksonKearl** [comment]
I haven't seen this since so no reliable repro, but I don't have `files.watcherExclude` configured. I'll keep an eye on possible casing issues.

**Comment by eamodio** [comment]
@bpasero I haven't noticed any issues so far. Ultimately, I think it would be great for the Git extension to get closer to the patterns that GitLens has, so that it can provide more granular repository change events.

**Comment by bpasero** [comment]
@eamodio just to clarify, do you think that the Git extension watching only top level files in `.git` means some events are missed? Why does GitLens watch a lot more compared to the Git extension?

**Comment by eamodio** [comment]
@bpasero Looking at what I have in GitLens, I don't really think the Git extension is missing anything. The things that I'm watching for outside of the top level, are rebase specific changes and I also listen for all changes in `/refs/**` (since I show all the branches/tags/etc), where as the Git extension sets up a specific watcher for the upstream of the current ref. 

Technically though without watching for any of the `/ref/**` changes, other users of the Git extension's `onDidChange` event could be missing something they might care about. But it doesn't affect the current needs of the Git extension itself.

**Comment by bpasero** [comment]
Thanks!

**Comment by bpasero** [comment]
Will watch for more issues like this but currently I am not sure whether this is actionable or not. If `fs.watch` was catching file events that `@parcel/watcher` is not, it would be good to learn how we can possibly fix this. 

If not possible, we could bring back support for `fs.watch` even if the folder is within the workspace but that comes at the risk of sending duplicate events (once from `@parcel/watcher` and once from `fs.watch`). We can maybe prevent duplicates by adding another delayed filter around all events (from `fs.watch` and `@parcel/watcher`) but there is no guarantee about the timing (the one could fire first and the other with a delay later).
