### ISSUE TITLE
VS Code - and Electron Apps generally - don't show Windows 11 SnapAssist on hover of Max

### ISSUE THREAD

**Issue by shanselman** [microsoft/vscode#140932]
in Win 11 when you hover over the Maximize button you should see
<img width="260" alt="image" src="https://user-images.githubusercontent.com/2892/150004353-31ffa775-024c-48df-80d9-6ecd12f9c522.png">

This doesn't fire in VS Code, Teams (electron apps) or Windows Terminal (custom owner draw title bar)

The Electron Core (whomever is responsible for the Maximize button) needs to implement WM_NCHITTEST and reply with HTMAXBUTTON when the hit test is over top of the max button. That will tell Windows it's a Max button which helps Accessibility AND fires SnapAssist.

<img width="441" alt="image" src="https://user-images.githubusercontent.com/2892/150004613-5b43dc98-bd7b-48fd-9e35-68b13d4ecab5.png">

**Comment by DHowett** [comment]
This is mentioned tangentially in https://github.com/electron/electron/issues/32360 as well.

**Comment by shanselman** [comment]
@chrisdias looks like @mlaurencin is deep into it from the Electron side but it'd be nice to figure out "who owns" since it's starting at Chromium and working it's way up...but it's still not quite there https://bugs.chromium.org/p/chromium/issues/detail?id=1218921#c21 Maybe someone on your team can chat with her?

**Comment by emhuang-msft** [comment]
here's the guidance I've been given to have Electron applications support the Snap Layout Menu:
[Window Controls Overlay for Customized Title Bars.pdf](https://github.com/microsoft/vscode/files/8044779/Window.Controls.Overlay.for.Customized.Title.Bars.pdf)

**Comment by deepak1556** [comment]
I kept it separate to track the upstream issue related to hover effect for WCO https://github.com/microsoft/vscode/issues/140932#issuecomment-1015781799

Can be merged to https://github.com/microsoft/vscode/issues/127449 as the relevant fixes are available with insiders.
