### ISSUE TITLE
Missing Sublime Text command - Switch to single column view

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#14094]
While building this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings) to map Sublime Text default keyboard shortcuts to VS Code, I found that this feature is missing. 

The feature is switch to single column view. 

**Default Sublime Text keybindings**
Windows / Linux: <kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>1</kbd>
Mac: <kbd>alt</kbd>+<kbd>cmd</kbd>+<kbd>1</kbd>

The feature allows you to easily switch from split editor mode to a single editor. 

Before switching:

<img width="909" alt="sublime_two_columns" src="https://cloud.githubusercontent.com/assets/2449568/19565452/be2b0d58-969b-11e6-9da1-fbe424c602e9.png">

After switching:

<img width="912" alt="sublime_single_column" src="https://cloud.githubusercontent.com/assets/2449568/19565461/c4079534-969b-11e6-8611-0ad11dc03ace.png">

**Comment by bpasero** [comment]
There is more to this command, it actually takes the editors from other groups and moves them to the single group. We have to decide if we want to go with the full sublime editor layout model. I think one requirement for it is to support empty groups.

**Comment by AndreasBackx** [comment]
@bpasero I would love for the "Split editor" command to behave differently. Currently it splits the current editor, but it opens a copy of the same file. Most of the time you do not want a copy of the same file in the new editor. What you end up doing every single time is splitting the editor 3 times for example, open 2 new files in the 2 new editors, and then closing the original file that was opened in each editor.

Could we also have more than 3 editors open at the same time? Is there any reason to limit this? I prefer to have 4 editors open most of the time when writing Python or Go, but VSCode stops me from doing that unfortunately.

Lastly is there perhaps another issue revolving around the way VSCode handles multiple editor windows?
