### ISSUE TITLE
Consider moving api tests from `vs/workbench/test/LAYER/api` to `vs/workbench/api/test/LAYER`

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#140993]
This would better align the tests and place them near the code which they target and it would also allow to remove [two exceptions that we need to maintain in our layering rules](https://github.com/microsoft/vscode/blob/6ffa1d3786912241860dd3847655bc8fc8b571bb/.eslintrc.json#L235-L236)

(ref #140857 #140874)

**Comment by bpasero** [comment]
I like 👍 .

**Comment by bpasero** [comment]
PR https://github.com/microsoft/vscode/pull/141056
