### ISSUE TITLE
Missing Sublime Text command - expand selection to scope

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#14099]
While building this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings) to map Sublime Text default keyboard shortcuts to VS Code, I found that this feature is missing. 

The feature is split selection into lines. 

**Default Sublime Text keybindings**
Windows / Linux: <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>space</kbd>
Mac: <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>space</kbd>

![expand_selection_by_scope](https://cloud.githubusercontent.com/assets/2449568/19566165/22e0b55c-969e-11e6-83ec-2ee96c932345.gif)

Today an [extension](https://marketplace.visualstudio.com/items?itemName=letrieu.expand-region) exists that provides this feature. I believe we should bring this into the product.

**Comment by ristomatti** [comment]
@waderyan There already is similar command. It's called **smart select**. But unfortunately  I've found it to not be as fine grained as I'd wish.
```json
{ "key": "shift+alt+right",       "command": "editor.action.smartSelect.grow",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+left",        "command": "editor.action.smartSelect.shrink",
                                     "when": "editorTextFocus" },
```

 **Luckily @windwp has created a great extension called [expand-region](https://marketplace.visualstudio.com/items?itemName=letrieu.expand-region)** which does this quite well.

![image](https://cloud.githubusercontent.com/assets/9029939/23115810/f273afec-f74f-11e6-9475-a670f1d4f59c.png)

**Comment by Bigous** [comment]
Hi, I've found the [Expand Selection To Scope](https://marketplace.visualstudio.com/items?itemName=vittorioromeo.expand-selection-to-scope) extension and it works very much like the SublimeText feature.

Very good.

**Comment by maranomynet** [comment]
I'm using VSCode 1.18.1 and the build in

`Selection -> Expand selection  (Ctrl + Shift + Cmd + RightArrow)`

and

`Selection -> Shrink selection  (Ctrl + Shift + Cmd + LeftArrow)`

seem to cover this extremely well.

**Comment by amiiit** [comment]
@roblourens it seems that can be closed as it's obviously already implemented.
