### ISSUE TITLE
Simple image dialog should remember file name when switching folders

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140912]
I often write the file name and then realize I'm in the wrong folder and switching clears what I wrote.
![Recording 2022-01-15 at 08 53 34](https://user-images.githubusercontent.com/2193314/149964512-005fe424-c727-47d5-bcf6-5aa47e0ce45e.gif)

**Comment by alexr00** [comment]
It's very hard to tell if the last path segment that a user types here is intended to be the filename or a folder. We would need a multistep input to handle this properly.

**Comment by Tyriar** [comment]
@alexr00 assuming it's a file if it has an extension seems like a safe approach?

**Comment by alexr00** [comment]
I can try that. It won't work in every case since not all files have extension, but it might be an improvement.

**Comment by Tyriar** [comment]
Thanks, should cover the only cases I would hit the problem
