### ISSUE TITLE
Error in npm intall after cloneing

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#1409]
I am getting this error on npm install after cloning.

C:\Users\skhan\Dropbox\vscode\vscode\node_modules\windows-mutex\build\CreateMut
ex.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default
.props" was not found. Confirm that the path in the <Import> declaration is cor
rect, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
 "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\b
in\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\skhan\Dropbox\vscode\vscode\node_modules\windows-mutex
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing windows-mutex@0.2.0
\
> alexandrudima-oniguruma@6.0.1 install C:\Users\skhan\Dropbox\vscode\vscode\nod
e_modules\vscode-textmate\node_modules\alexandrudima-oniguruma
> node-gyp rebuild
C:\Users\skhan\Dropbox\vscode\vscode\node_modules\vscode-textmate\node_modules\a
lexandrudima-oniguruma>if not defined npm_config_node_gyp (node "C:\Program File
s\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node
-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Users\skhan\Dropbox\vscode\vscode\node_modules\vscode-textmate\node_modules\
alexandrudima-oniguruma\build\oniguruma.vcxproj(20,3): error MSB4019: The impor
ted project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the pa
th in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\skhan\Dropbox\vscode\vscode\node_modules\vscode-textmate\n
ode_modules\alexandrudima-oniguruma
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! native-keymap@0.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the native-keymap@0.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the native-keymap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls native-keymap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\skhan\Dropbox\vscode\vscode\npm-debug.log

**Comment by Nosherwan** [comment]
+1
I am getting the same error on ubuntu. I am using node 5.3.0.

**Comment by shanalikhan1** [comment]
u found any solution to this problem ?

**Comment by joaomoreno** [comment]
Please make sure you have all the [build prerequisites](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source) installed. I cannot reproduce this.

@Nosherwan for sure you are seeing a different error, since @shanalikhan1's error is very specific to Windows (`The imported project "C:\Microsoft.Cpp.Default.props" was not found.`). If you see an error, please create a separate issue.

**Comment by m3talsmith** [comment]
I found a solution for Ubuntu: make sure that the x11 dev dependencies are installed - https://github.com/Microsoft/node-native-keymap#installing
