### ISSUE TITLE
Consider moving `src/vs/server/cli.js` and `src/vs/server/main.js` to `src/`

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#140997]
ref https://github.com/microsoft/vscode/issues/140874

`src/vs/server/cli.js` and `src/vs/server/main.js` are entry points to `vscode-server`. We added them in the `src/vs/server` folder because that made it easier to have the server sources not be open source. 

We could consider moving them to `src/server-cli.js` and `src/server-main.js`, which would better align with how the source is structured for vscode.

Thoughts or concerns @bpasero @aeschli ?

**Comment by bpasero** [comment]
Yes, 👍

**Comment by aeschli** [comment]
Makes sense!
