### ISSUE TITLE
Can VS code will support more theme or theme package?

### ISSUE THREAD

**Issue by zhuangtongfa** [Microsoft/vscode#141]
Can VS code will support more theme or theme package?Now it looks ugly!

**Comment by meritozh** [comment]
yes, it support .tmTheme file which is TextMate themes file. You can also create your own theme by  yo code extension generator. Here is doc: https://code.visualstudio.com/docs/customization/themes

**Comment by bpasero** [comment]
Closing, we have theme support and language coloring support via extensions.
