### ISSUE TITLE
Allow write Markdown in py-file when I type #%%md

### ISSUE THREAD

**Issue by yongleya** [microsoft/vscode#141040]
When I use VSCode to edit Python files, I will enter “#%%” to open interactive programming like jupyter notebook, but in VSCode, this way cannot enter code blocks in Markdown format, so I suggest that when we enter ‘#%%md’, you can enter text in Markdown format in this code block, just like pycharm.

**Comment by rchiodo** [comment]
Markdown is actually already supported. It's a different marker for a markdown cell.

Like so:

```
# %% [markdown]
# # Header Is here
```

The markdown is all commented in the python file, but then regular markdown formatting applies after the comment.

That example generates markdown like so:

![image](https://user-images.githubusercontent.com/19672699/150390937-2bb515e0-67b6-4e39-ba9e-ca56aff5ef3f.png)

**Comment by rchiodo** [comment]
You can change the regex we use to find markdown cells with this setting here:

![image](https://user-images.githubusercontent.com/19672699/150391033-7478e2b7-41f5-46d6-974c-7af94a6698b2.png)

**Comment by rchiodo** [comment]
There's some more examples here:
https://github.com/microsoft/vscode-jupyter/blob/169de00f61433bae6fc6f68fff4f0b9e8bcd62be/src/test/datascience/manualTestFiles/manualTestFile.py#L36
