### ISSUE TITLE
VSCode cannot find module with yarn berry's pnp and typescript on WSL2

### ISSUE THREAD

**Issue by Phryxia** [microsoft/vscode#141043]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2 (also tested with 1.64.0-insider)
- OS Version: Win10 (10.0.19043) **with WSL2**

Steps to Reproduce:

1. Make a project using yarn berry's pnp feature on. (To be simple, clone this project: https://github.com/Phryxia/auto-proof) 
2. Execute `yarn` (Need to enable corepack - https://yarnpkg.com/getting-started/install)
3. Open any `ts`/`tsx` file
4. Open `tsconfig.json`
5. Wait until seeing this message

```
File '//wsl$/Ubuntu-20.04/home/sekyukwon/dev/my/auto-proof/.yarn/cache/typescript-patch-0b90225f97-2e488dde7d.zip/node_modules/typescript/lib/lib.dom.d.ts' not found.
  The file is in the program because:
    Library 'lib.dom.d.ts' specified in compilerOptions

Cannot find module 'react-dom' or its corresponding type declarations.
Cannot find module 'react/jsx-runtime' or its corresponding type declarations.
Cannot find name 'document'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
```

I'm not sure this is yarn's problem or vscode's problem... so feel free to close this if it's not related to vscode.

Also I did these things:

- Executed `yarn dlx @yarnpkg/sdks vscode` and check `typescript.tsdk` in `.vscode/settings.json`
- Use typescript with workspace version
- Installed ZipFs extension, enabled it or disabled it.
- Note that `typescript-patch-0b90225f97-2e488dde7d.zip` file does exists.

For your interests, see this `tsconfig.json`

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "es6",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "paths": {
      "@src/*": ["./src/*"]
    }
  },
  "include": ["src/**/*"]
}
```

**Comment by mjbvz** [comment]
I believe yarn adds its own typescript server extension to support zip files. Please start by filing an issue against them
