### ISSUE TITLE
Consider deleting `vs/editor/test/common/model/benchmark/bootstrap.js`

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#141005]
ref #140874

@rebornix Do you still run this? I haven't executed this in years. I suggest to delete it.

**Comment by rebornix** [comment]
@alexdima yep, the code is being there for more than four years and we rarely made any change and also no obvious performance issue. Let's remove it.

**Comment by alexdima** [comment]
Nice! Thank you!
