### ISSUE TITLE
Terminal in editor area turns blank when moved to another panel

### ISSUE THREAD

**Issue by t0mm4rx** [microsoft/vscode#141074]
Issue Type: <b>Bug</b>

Hello,
I have a very annoying bug with the terminal in the editor area. When I summon a new terminal directly in the editor area (with a custom keybinding, or directly with the command panel) it shows my usual shell. When I move this terminal to another panel (like pinning the terminal in the right side of the editor area) it turns blank.

Tested with all extensions turned off, different themes, with latest. VSCode version and macOS 11.6.

To reproduce:
1. Open two terminal tabs in the editor area with the command palette
2. Drag one of the two terminal tabs to one of the side (splitting your editor area in multiple panels)
3. The moved terminal is now blank (no text, no interactivity)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:38:17.605Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 9e1da458-5c32-4242-bc5f-fccbc4603e5f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
touch-bar-display|bla|1.5.0
vscode-eslint|dba|2.2.2
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
solidity|Jua|0.0.136
prettify-json|moh|0.0.3
vscode-docker|ms-|1.19.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
cpptools|ms-|1.7.1
vetur|oct|0.35.0
java|red|1.2.0
LiveServer|rit|5.7.2
prettier-plus|svi|4.2.2
latex-support|tor|3.10.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30424895
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30416617
vsbas813:30426126

```

</details>

**Comment by t0mm4rx** [comment]
Here is a demo of the issue: https://www.loom.com/share/4d6bb7ccc6df4a15b4cd38882d7c3159
No error in the JS console.

**Comment by gjsjohnmurray** [comment]
Are you able to re-test using Insiders?

**Comment by xinstein** [comment]
When will it roll out to stable channel?

**Comment by gjsjohnmurray** [comment]
The next release is scheduled to be out before the end of next week.
