### ISSUE TITLE
Horizontal Layout Workspace Setting

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#14105]
When you have a `workspace` setting for laying out the editors e.g. 
`"workbench.editor.sideBySideLayout": "horizontal"`

The toggle options (which are user settings) do nothing e.g. clicking on:
![image](https://cloud.githubusercontent.com/assets/1051190/19566721/a28f8222-96eb-11e6-99ae-ed5ec74897eb.png)

It could be worth testing to see if a workspace setting exists.  If it does then tell the user that the toggle will not override this setting.  As a result it will do nothing.

The same is true for this menu option - it does nothing as the workspace setting overrides it:
![image](https://cloud.githubusercontent.com/assets/1051190/19566819/e9f16252-96eb-11e6-8a62-4218ede5f6e6.png)

In this case I'm already in horizontal layout so we probably need an additional check to validate the workspace setting mode before rendering the item.

**Comment by bpasero** [comment]
@seanmcbreen well that is actually a good point, would you expect the toggle to then write to your workspace settings file if we find the setting there?

**Comment by bpasero** [comment]
I decided to go with an approach where the toggles are not writing to settings. You can still configure this manually though.
