### ISSUE TITLE
add split cwd smoketest

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#141090]
with inherited as the splitCwd setting, try to split in various ways and verify that the cwd of the new terminal is the same as the parent after changing the parent's directory

**Comment by meganrogge** [comment]
do we just want to do this for the NaiveCwdDetection for now? if not, might be involved to get the shell integration script to work in smoke tests

**Comment by Tyriar** [comment]
👍 we can defer shell integration to https://github.com/microsoft/vscode/issues/141479
