### ISSUE TITLE
"Open Folder" is mapped to "Add folder to workspace" in web

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141045]
This getting started entry needs better context keys:

https://github.com/microsoft/vscode/blob/87ea829ceffa8bfbe3ce69f5314b5e33a364615e/src/vs/workbench/contrib/welcome/gettingStarted/common/gettingStartedContent.ts#L111-L121

Because you can be:
* in a serverful web environment (e.g. Codespace)
* having a multi-root workspace opened
* clicking on "Open Folder" from getting started
* assuming this would allow the user to open a folder

But instead it adds a folder.

Since I recently added the "Open Folder" entry to the main menu, I suggest to copy the context keys I used there: https://github.com/microsoft/vscode/commit/12f9c5fc6d5329bfb0c4402b9fbc6013ed9be0da

**Comment by JacksonKearl** [comment]
cc @digitarald
