### ISSUE TITLE
Git should adopt `RelativePattern` in places where events should be scoped

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141048]
Instead of doing `isDescendant` checks on its own.

https://github.com/microsoft/vscode/blob/c047af40b27be89e456b8703526adc1a138d563d/extensions/git/src/repository.ts#L864

//cc @joaomoreno 

---

@joaomoreno rewrite:

What this means is that we should continue where https://github.com/microsoft/vscode/pull/140695 left off, adopt the new file watching API to scope watching to arbitrary folders. Doing that means that we have to use `RelativePattern` and we can afford to drop `isDescendant`.

**Comment by joaomoreno** [comment]
This whole issue title and description confused me. This is about https://github.com/microsoft/vscode/pull/140695 not being 100% complete. There are a total of 3 calls to `createFileSystemWatcher` in `extensions/git` and that PR only touched one of them. This issue is about the other two supposedly.

**Comment by bpasero** [comment]
I think there are in total 2 work areas:
* drop any `fs.watch` (I think that one is done)
* review every use of `createFileSystemWatcher` to see whether `RelativePattern` to scope watcher to a specific path

**Comment by joaomoreno** [comment]
Thanks!

Plan of action:

- Nothing to do for [`Model`](https://github.com/microsoft/vscode/blob/c047af40b27be89e456b8703526adc1a138d563d/extensions/git/src/model.ts#L117)
- Adopt [`RelativePattern` in `Repository`](https://github.com/microsoft/vscode/blob/c3bd29b3d09e29b49f8050a5b55106960a671e3b/extensions/git/src/repository.ts#L860-L864), @eamodio started that in https://github.com/microsoft/vscode/pull/140792/files
    - Propagate that watcher to [`DotGitWatcher`](https://github.com/microsoft/vscode/blob/c3bd29b3d09e29b49f8050a5b55106960a671e3b/extensions/git/src/repository.ts#L870), so we can remove both [`watch`](https://github.com/microsoft/vscode/blob/c3bd29b3d09e29b49f8050a5b55106960a671e3b/extensions/git/src/repository.ts#L543) [calls](https://github.com/microsoft/vscode/blob/c3bd29b3d09e29b49f8050a5b55106960a671e3b/extensions/git/src/repository.ts#L566)
    - Delete the [`watch` util](https://github.com/microsoft/vscode/blob/044092db5597de273b8fe7030332ec3454043102/extensions/git/src/watch.ts#L13)

**Comment by bpasero** [comment]
Ping. With https://github.com/microsoft/vscode/issues/146066 being fixed now, there should really be no need for node.js watching anymore nor not using relative patterns.

Can we move on here?

**Comment by lszomoru** [comment]
Updated plan based on this morning's conversation: 
- Merge https://github.com/microsoft/vscode/pull/140792
- Reducing number of watchers used by the git extension is blocked by work that has to happen for the Parcel watcher (support glob based exclusion) as well as VS Code extension API changes to support setting up a watcher using an include/exclude list

**Comment by bpasero** [comment]
Related watcher issues:
* https://github.com/microsoft/vscode/issues/137872
* https://github.com/parcel-bundler/watcher/issues/64

I can see whether watchers can become isolate, at least when created from the extension host so that the watcher created by one extension would not trigger events everywhere.

**Comment by lszomoru** [comment]
Pushed aa0cc063771f3f5ba4878f844e94b6b386f29b87 that adopts `RelativePattern` for the repository watcher.
