### ISSUE TITLE
I would like to reset

### ISSUE THREAD

**Issue by HiCONSUMPTION** [microsoft/vscode#141000]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Performance Issue</b>

How do you completely delete, I have uninstall extension but there are still errors not allowing me to run a simply hello world in c++

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 1dff9dd1-2203-46af-a66e-3ddd45e96235|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   19	    98	 34467	code main
    0	    33	 34481	   gpu-process
    0	    16	 34484	   utility-network-service
    0	    66	 34509	   shared-process
    0	    16	 34517	     ptyHost
    0	     0	 35300	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   123	 35278	   window (Get Started)
    0	    66	 35279	   extensionHost
    0	    74	 35289	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-csv|mec|2.0.0
cpptools|ms-|1.7.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30424896
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614

```

</details>

**Comment by rzhao271** [comment]
Have you checked out https://code.visualstudio.com/docs/languages/cpp?
Do you have example error messages or screenshots for how your application isn't working?
