### ISSUE TITLE
problemMatcher can not find the file

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#141038]
https://github.com/microsoft/vscode-cpptools/issues/8693

Bug type: General

**Describe the bug**
版本: 1.64.0-insider (system setup)
提交: 16856037e075275f53b25b7e2dec2303e8e25728
日期: 2022-01-19T05:15:25.456Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.14393
c/c++: 1.8.0

**To Reproduce**
*Please include code sample and `task.json` files.*
1. build task
2. switch to problem panel
3. click problem
4. can not find the file

            "problemMatcher": [
                "$msCompile"
            ],

```json
        {
            "label": "makebat",
            "type": "shell",
            "runOptions": {},
            "command": "${workspaceFolder}/makefile.bat",
            // "dependsOn": "VS2022 Env",
            "problemMatcher": [
                "$msCompile"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
```
**Expected behavior**
goto file

**Screenshots**
![image](https://user-images.githubusercontent.com/1876302/150247260-d02c0fc2-8b87-43c6-9cb7-37f84479735e.png)

![image](https://user-images.githubusercontent.com/1876302/150247266-476e808e-62e5-41fd-b278-8731950e0872.png)

**Additional context**
```json
	"folders": [
		{
			"path": "."              // there is the folder of task.json
		},
		{
			"path": "C:\\CRAFT\\include"
		},
		{
			"path": "C:\\CRAFT\\doc"
		}
	],
```

**Comment by alexr00** [comment]
The `$msCompile` problem matcher expects absolute file paths. Your build output looks like it uses relative file paths. See https://stackoverflow.com/questions/49466043/vs-code-mscompile-problemmatcher-doesnt-work-with-relative-file-path for more info!
