### ISSUE TITLE
Missing Sublime Text command - close HTML tag

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#14104]
While building this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings) to map Sublime Text default keyboard shortcuts to VS Code, I found that this feature is missing. 

The feature is close HTML tag. 

**Default Sublime Text keybindings**
Windows / Linux: <kbd>alt</kbd>+<kbd>.</kbd>
Mac: <kbd>cmd</kbd>+<kbd>alt</kbd>+<kbd>.</kbd>

![close_html_tag](https://cloud.githubusercontent.com/assets/2449568/19566803/6f8e46f6-96a0-11e6-923e-796c4600c987.gif)

Today an [extension](https://marketplace.visualstudio.com/items?itemName=Compulim.compulim-vscode-closetag) exists that provides this feature. I believe we should bring this into the product.

**Comment by rebornix** [comment]
That's all about finding previous unclosed tag :)
