### ISSUE TITLE
orca doesn't say tab names when switching by ctrl+tab

### ISSUE THREAD

**Issue by alex19EP** [microsoft/vscode#141061]
Issue Type: <b>Bug</b>

when pressing ctrl+tab and switching tabs with tab orca says nothing.

orca version: 41.1.r53.g6580a8928-1

VS Code version: Code - Insiders 1.64.0-insider (0c6d1e9f7ef648cfa50733abb62388bc0791856a, 2022-01-20T06:29:50.054Z)
OS version: Linux x64 5.16.1-zen1-1-zen
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.49GB (0.17GB free)|
|Process Argv|--crash-reporter-id 49edb027-d44c-4fb4-befd-53de5d4dd885|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
meson|asa|1.3.0
github-markdown-preview|bie|0.1.0
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
better-toml|bun|0.3.2
vscode-astyle|chi|0.9.0
systemd-unit-file|coo|1.0.6
vscode-github-actions|csc|0.21.3
vscode-markdownlint|Dav|0.45.0
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
git-project-manager|fel|1.8.2
remotehub|Git|0.20.0
remotehub-insiders|Git|2022.1.140934
vscode-pull-request-github|Git|0.35.2022012009
gitlab-workflow|Git|3.40.2
markdown-extended|jeb|1.1.1
better-cpp-syntax|jef|1.15.10
restructuredtext|lex|168.0.0
kconfig|luv|1.0.3
rust-analyzer|mat|0.2.908
vscode-github-actions|me-|3.0.1
language-gettext|mro|0.2.0
vscode-docker|ms-|1.19.0
vscode-language-pack-ru|MS-|1.64.3
python|ms-|2022.0.1716474472-dev
vscode-pylance|ms-|2022.1.2-pre.1
jupyter|ms-|2022.1.1001614873
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.213.0
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.1
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.0-insiders2
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5273
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vsonline|ms-|1.0.3076
awk-vscode|pet|0.1.1
trusty-rusty-snippets|pol|0.0.5
java|red|1.2.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.3.0
platform-settings|run|1.0.0
just|ske|2.0.0
rewrap|stk|1.16.0
code-spell-checker|str|2.1.4
code-spell-checker-russian|str|2.0.2
even-better-toml|tam|0.14.2
cmake|twx|0.0.17
vscode-lldb|vad|1.6.10
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstartedc:30421358
vscop804cf:30404767
vscop341:30404997
vsclayoutctrt:30405800
azactmsalcf:30409288

```

</details>

**Comment by alex19EP** [comment]
CC: @isidorn

**Comment by isidorn** [comment]
Jose already reported this and we are discussing in https://github.com/microsoft/vscode/issues/140861#issuecomment-1014791394
So closing as duplicate and I plan to comment on the other issue soon
