### ISSUE TITLE
vscode web build documentation

### ISSUE THREAD

**Issue by ashwin31** [microsoft/vscode#141093]
In reference with https://github.com/microsoft/vscode/issues/136959

There is no mention of build command or script in the wiki/documentation.

Can you please piont me to the right one if it is listed out there or anhance documentation to build vscode web.

**Comment by bpasero** [comment]
> There is no mention of build command or script in the wiki/documentation.

Where do you mean? And what kind of docs do you expect?

**Comment by ashwin31** [comment]
@bpasero I am able to run vscode web but I couldn't find documentation or command or script to build it for web. to load in browser like vscode.dev

**Comment by bpasero** [comment]
/duplicate https://github.com/microsoft/vscode/issues/104968

cc @egamma

**Comment by ashwin31** [comment]
@bpasero the other ticket you mentioned is closed without a solution #104968

**Comment by bpasero** [comment]
Well, https://github.com/microsoft/vscode/issues/104968#issuecomment-707626698 was the last word on it, I have pinged Erich to comment if this has changed in the meantime.

**Comment by ashwin31** [comment]
Thank you @bpasero Let's see what @egamma says and if this has changed over time.

**Comment by ashwin31** [comment]
Hi @egamma can you share build command to build this repo for web.
