### ISSUE TITLE
Shell integration: Frequency sorting of recent directories may be broken on Windows

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#141008]
https://github.com/microsoft/vscode/issues/139402#issuecomment-1012387929

**Comment by meganrogge** [comment]
I believe this was broken at one point, but is now working correctly.

![Screen Shot 2022-01-19 at 5 11 06 PM](https://user-images.githubusercontent.com/29464607/150233181-2176aed3-8a6c-4313-b6bf-dc023be618ac.png)

**Comment by Tyriar** [comment]
Still seems broken for me on Windows, I'll look into it for https://github.com/microsoft/vscode/pull/141083

**Comment by meganrogge** [comment]
verify that the cwds are sorted in terms of the frequency that you've cd'd into them

**Comment by rzhao271** [comment]
For me, the sorting seems to be by most recent first.
I ran `cd <absolute path to vscode repo dir>` multiple times.

![Demo](https://user-images.githubusercontent.com/7199958/151632400-ab25abc1-0499-4d46-9fc7-572525a07a81.PNG)

**Comment by Tyriar** [comment]
The "current session" section is now in last accessed order just like the new "previous session" section
