### ISSUE TITLE
Missing Sublime Text command - select down to next auto complete suggestion

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#14101]
While building this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings) to map Sublime Text default keyboard shortcuts to VS Code, I found that this feature is missing. 

The feature is select down to next auto complete suggestion. 

**Default Sublime Text keybindings**
Windows / Linux: <kbd>ctrl</kbd>+<kbd>space</kbd>
Mac: <kbd>ctrl</kbd>+<kbd>space</kbd>

![next_suggestion](https://cloud.githubusercontent.com/assets/2449568/19566545/923397a2-969f-11e6-8120-132dab82ccd1.gif)

**Comment by shanalikhan** [comment]
+1
