### ISSUE TITLE
cant find \r in regex mode

### ISSUE THREAD

**Issue by andre-ss6** [microsoft/vscode#141087]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows 10 21H1

Steps to Reproduce:

select CRLF for line end sequence
write some lines
abc`\r\n`
def

ctrl + f to open search
select regex mode (.*)
try `\n`: new lines are selected
try `\r`: no results

Also, if you try replacing `\n` with `\r\n`, `\r` is written literally instead.

I'm reopening [this issue](https://github.com/microsoft/vscode/issues/31449) from five years ago.

There is also [this StackOverflow question](https://stackoverflow.com/questions/62192933/find-n-and-replace-with-r-n-in-vs-code) from almost two years ago about this same issue.

**Comment by rafrafek** [comment]
Is it possible to search for files with `\r\n` ending?

**Comment by amunger** [comment]
as noted in the linked issue, this is by design. `workbench.action.editor.changeEOL` can be used to change line endings.
