### ISSUE TITLE
Render issue of multiple pandas dataframes

### ISSUE THREAD

**Issue by kuelumbus** [microsoft/vscode#141022]
## Environment data

Version: 1.64.0-insider
Commit: 16856037e075275f53b25b7e2dec2303e8e25728
Date: 2022-01-19T06:30:32.860Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.163-17372-g914fa8228dda

-   Jupyter Extension version (available under the Extensions sidebar): 2022.1.1001614873
-   Python Extension version (available under the Extensions sidebar): 2022.0.1712827410-dev
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): poetry
-   Jupyter server running: Remote

## Actual behaviour

https://user-images.githubusercontent.com/44866753/150205499-c32831b0-d5f1-4c50-b6a1-a004cccb5cd7.mp4

## Steps to reproduce:

Open notebook and run
```python
import pandas as pd

for i in range(500):
    display(pd.DataFrame({"A": [1, 2, 3]}))
```

Run the cell again

**Comment by amunger** [comment]
we wait to update height now, so it might take the renderer a while to update with all that output (https://github.com/microsoft/vscode-jupyter/issues/11636), it won't put a cell editor right in the middle like that anymore
