### ISSUE TITLE
not run project

### ISSUE THREAD

**Issue by mhamad1400** [microsoft/vscode#141085]
![Capture](https://user-images.githubusercontent.com/98103726/150384566-77906b69-0739-440f-9839-1867b3e27404.JPG)
Hi my dear  .
I have  a problem in vscode . when i want run project of flutter . it say build errors project exsist on your project . 
even when i want to create your  project teamplate, it just says . 
please help me .

**Comment by weinand** [comment]
If you press the "Show Errors" butt on what do you see?

**Comment by mhamad1400** [comment]
`
![Uploading Capture123.JPG…]()

**Comment by weinand** [comment]
@mhamad1400 the uploaded picture doesn't work.

**Comment by mhamad1400** [comment]
sorry this 
![Capture123](https://user-images.githubusercontent.com/98103726/150392219-329227ac-1ad9-4620-b0a3-d74522fc9dca.JPG)
