### ISSUE TITLE
`scripts/code-web.sh` prints errors for extensions

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141066]
Trying out the new `scripts/code-web.sh` support, it looks like there are some errors about extensions that cannot be found:

![image](https://user-images.githubusercontent.com/900690/150344867-6d95798f-8523-402a-882f-f100394754c8.png)

```
INFO Request to 'http://localhost:8080/static/extensions/0/vscode-web-playground/package.nls.json' failed with status code 404
```

![image](https://user-images.githubusercontent.com/900690/150345000-d3494c98-1ffa-4262-bc78-2c3eaee5fb48.png)

**Comment by aeschli** [comment]
Did you run `yarn watch-web` ?

**Comment by bpasero** [comment]
@aeschli good point, works better after I did that.

Still seeing this though, but maybe that is fine:

```
INFO Request to 'http://localhost:8080/static/extensions/0/vscode-web-playground/package.nls.json' failed with status code 404
```

**Comment by aeschli** [comment]
I will add a console message if I see that the browser main file is missing.

The 404 for `package.nls.json` is normal. Our code tries to download `package.nls.json` for every extension. It could become smarter to only do that if there's a translation placeholder in the `package.json`
