### ISSUE TITLE
"Variable ${selectedText} can not be resolved" when run command `search.action.openNewEditor` from diff editor

### ISSUE THREAD

**Issue by Binly42** [microsoft/vscode#141051]
Issue Type: <b>Bug</b>

The full detail error/warning message is: `Variable ${selectedText} can not be resolved. Make sure to have some text selected in the active editor.`
And finally not open a new search editor yet.

## repro

1. add a keybinding like:
  
  ```json
    {
        "key": "ctrl+e ctrl+f",
        "command": "search.action.openNewEditor",
        "args": {
            "query": "${selectedText}",
        },
    },
  ```
2. in a normal editor, select some text, emit the shorcut, the command works fine
3. in a diff editor, select some text, emit the shorcut, the result said top above appears
    - no matter select in left side or right side, or even both ...

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (0.62GB free)|
|Process Argv|--crash-reporter-id aef19635-1b79-4f09-9c0d-1ff29d49308d|
|Screen Reader|yes|
|VM|50%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30424896
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710cf:30416617
vsbas813:30426126

```

</details>

**Comment by Binly42** [comment]
Another point might not related. 

From https://github.com/microsoft/vscode/issues/95582#issuecomment-625555653 , I got that `${selectedText}` would throw if there's no selected text.
As a result, currently it is not able to open a search editor, which should be with a complex query based on selectedText (like `"query": "foobar${selectedText}",`), when not selected anything.

Maybe it is not simple to make the query arg support full-feature snippet.
But it would be great to support when not selected anyting...

IMO it would be more great to support the `$0`, with that we could easily edit the text to be search when not selected text (by using something like `${0:${selectedText}}`)

**Comment by mjbvz** [comment]
@JacksonKearl This works for me when I select text in a normal editor or on the right hand side of a diff view, but not when my selection is on the left hand side (to repro, make sure nothing is selected on the right)
