### ISSUE TITLE
open my project use Multi-root Workspaces  debug app get the error

### ISSUE THREAD

**Issue by KingJch** [microsoft/vscode#141069]
when i use Multi-root Workspaces and debug my app，i got  that error：
`
zsh:1: command not found: yarn
The terminal process "zsh '-c', 'yarn run web:watch'" failed to launch
`

but when i use single Workspaces it work well

**Comment by weinand** [comment]
Could you share the debug launch configuration with us?

**Comment by KingJch** [comment]
> Could you share the debug launch configuration with us?

```json
// A launch configuration that compiles the extension and then opens it inside a new window
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
{
	"version": "0.2.0",
  "compounds": [
    {
      "name": "Debug webview-jupiter",
      "configurations": [
        "Run Extension",
        "Run Webview"
      ],
      "presentation": {
        "order": 0
      }
    }
  ],
	"configurations": [
		{
			"name": "Run Extension",
			"type": "extensionHost",
			"request": "launch",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}"
			],
			"outFiles": [
				"${workspaceFolder}/dist/**/*.js"
			],
			"preLaunchTask": "templates:webview build"
		},
    {
      "name": "Run Webview",
      "request": "attach",
      "type": "node",
      "preLaunchTask": "npm: web:watch"
    },
		{
			"name": "Extension Tests",
			"type": "extensionHost",
			"request": "launch",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}",
				"--extensionTestsPath=${workspaceFolder}/out/test/suite/index"
			],
			"outFiles": [
				"${workspaceFolder}/out/**/*.js",
				"${workspaceFolder}/dist/**/*.js"
			],
			"preLaunchTask": "tasks: watch-tests"
		}
	]
}

```

**Comment by weinand** [comment]
@alexr00 the error message originates from the `prelaunchTask`

**Comment by alexr00** [comment]
@KingJch can you share your `tasks.json` file?

**Comment by KingJch** [comment]
@alexr00 

// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format
{
	"version": "2.0.0",
	"tasks": [
		{
      "label": "templates:webview build",
			"type": "npm",
			"script": "extension:watch",
			"problemMatcher": [
				"$ts-webpack-watch",
				"$tslint-webpack-watch"
			],
			"isBackground": true,
			"presentation": {
				"reveal": "never",
				"group": "watchers"
			},
			"group": "build"
		},
		{
			"type": "npm",
			"script": "watch-tests",
			"problemMatcher": "$tsc-watch",
			"isBackground": true,
			"presentation": {
				"reveal": "never",
				"group": "watchers"
			},
			"group": "build"
		},
		{
			"label": "tasks: watch-tests",
			"dependsOn": [
				"npm: watch",
				"npm: watch-tests"
			],
			"problemMatcher": []
		}
	]
}

**Comment by alexr00** [comment]
Thank you! @KingJch if you run `yarn run web:watch` from the VS Code integrated terminal manually does it work?

**Comment by KingJch** [comment]
@alexr00 it work

**Comment by alexr00** [comment]
I'm not able to reproduce the issue. My steps:
1. Make a multiroot workspace
2. Make sure one of the folders in the workspace has a launch.json file with a launch config with a prelaunch yarn/npm task.
3. Select that launch config and debug.

@KingJch can you provide a few more details please:
- What operating system are you using?
- How did you launch VS Code?
