### ISSUE TITLE
What did you do to the integrated terminal in the latest version if Insiders

### ISSUE THREAD

**Issue by happyteque** [microsoft/vscode#141016]
1. How do I get the Terminal in a vertical column on the right, between the side panel and the editor?

**Comment by meganrogge** [comment]
>How do I get the Terminal in a vertical column on the right, between the side panel and the editor?
![Recording 2022-01-19 at 14 02 28](https://user-images.githubusercontent.com/29464607/150205169-afa20a3b-d935-4006-a178-0aee91de2434.gif)

**Comment by Tyriar** [comment]
Please keep things respectful.

**Comment by Tyriar** [comment]
Also it sounds like you're on insiders, so you opted into the less stable experience where new stuff that isn't necessarily done is pushed. You might enjoy stable more.

**Comment by happyteque** [comment]
OK thanks. It wasn't like in the gif you posted, it looked like there was a whole new thing going on with panels and views which I didn't understand. But turns out restarting the app fixed the issue. Apologies.

**Comment by sbatten** [comment]
please see the comments here about the new experience https://github.com/microsoft/vscode/pull/140742#issuecomment-1016750965
