### ISSUE TITLE
Scrolling is not smooth in insiders 

### ISSUE THREAD

**Issue by RGBYCP** [microsoft/vscode#141058]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.0-insider
- OS Version: Catalina

Steps to Reproduce:

1. Install VSC Code insiders. 
Version: 1.64.0-insider (Universal)
Commit: 16856037e075275f53b25b7e2dec2303e8e25728
Date: 2022-01-19T05:14:31.474Z (1 day ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0
2. Jupyter v2022.1.1001717102 pre-release
3. Work in the .ipynb with a conda kernel. Scrolling is not smooth. It stops from time to time.

**Comment by rebornix** [comment]
@RGBYCP can you please share the notebook you were using?
