### ISSUE TITLE
When hot exit restores neither files or untitled files from backup, no files that were open but not dirty are being restored

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14100]

**Comment by Tyriar** [comment]
This is happening because `EditorPart.restoreEditors()` is only called when `resolveEditorsToOpen` returns with `[]`.

**Comment by Tyriar** [comment]
Perhaps `editorStacks.model` could be leveraged here such that filesToRestore does not need to be tracked at all and the regular workspace restore code is relied upon? /cc @bpasero

**Comment by Tyriar** [comment]
I went ahead and pushed this instead of doing a PR as other things will depend on it and it's significantly better this way.

**Comment by bpasero** [comment]
@Tyriar see https://github.com/Microsoft/vscode/issues/14131
