### ISSUE TITLE
Color Theme doesn´t works

### ISSUE THREAD

**Issue by GabVlado** [microsoft/vscode#141027]
Issue Type: <b>Bug</b>

I work on Ruby  language while i have two windows open, one with TS and other with Ruby . 

I set the colors with textMateRules and works on Ruby but in TS no more, and  Developer Spector Scope  doesnt work too, the error is "No grammar provided for <source.ts>

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.87GB (5.44GB free)|
|Process Argv|--crash-reporter-id e4129787-89e3-467f-b4cb-ade114b858bc|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|Memory (System)|9.23GB (8.40GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
jest-snippets|and|1.8.0
vscode-styled-jsx|bla|2.1.1
bracket-pair-colorizer|Coe|1.0.62
es7-react-js-snippets|dsz|4.0.4
styled-snippets|fer|1.0.3
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
reactnextjssnippets|iJS|1.6.0
better-cpp-syntax|jef|1.15.10
styled-components-snippets|jon|0.10.0
theme-monokai-pro-vscode|mon|1.1.20
vscode-language-pack-es|MS-|1.63.3
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
awesome-flutter-snippets|Nas|3.0.2
material-icon-theme|PKi|4.11.0
nextjs-snippets|Pul|0.0.5
JavaScriptSnippets|xab|1.8.0
git-graph|mhu|1.30.0
vscode-typescript-next|ms-|4.6.20220118
vscodeintellicode|Vis|1.2.15

(17 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30424895
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710:30416614

```

</details>

**Comment by aeschli** [comment]
Does this reproduce without the `textMateRules` set?
Can you provide the setting you have?
