### ISSUE TITLE
`code-insiders --status` no longer works

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141053]
Steps to Reproduce:

1. run an instance of `code-insiders`
2. run `code-insiders --status`
3. => 🐛 no output

I traced this down to the watch task getting cancelled here:

https://github.com/microsoft/vscode/blob/b03fe7a97c06ae1906efd62e616d383704ee95e7/src/vs/code/node/cli.ts#L404

I did push some larger refactorings around [`watchFileContents`](https://github.com/microsoft/vscode/blob/ca8d9d1542431fa4ff8271accefc58abf9a537e6/src/vs/platform/files/node/watcher/nodejs/nodejsWatcherLib.ts#L468) earlier this milestone so maybe that triggered it. I still though believe that the watcher does the right thing of returning immediately when it is being cancelled.

**Comment by rzhao271** [comment]
Added a `setTimeout` for now.
The main issue is we want the watcher to quit once it has nothing left to read, but the current implementation gives the decision-making to whoever holds the cancellation token instead. Therefore, the CLI script must decide when to stop the watcher, when in this case we want the watcher to decide for itself.

**Comment by rzhao271** [comment]
Closing for verification.

**Comment by bpasero** [comment]
> The main issue is we want the watcher to quit once it has nothing left to read, but the current implementation gives the decision-making to whoever holds the cancellation token instead. Therefore, the CLI script must decide when to stop the watcher, when in this case we want the watcher to decide for itself.

How could the file watcher know when to stop watching the file for changes? There is no signal the file watcher could use to know that the file is no longer updated, no?

The `200ms` seems quite random and fragile to me.

**Comment by deepak1556** [comment]
When the main process exits there are no other process that will be writing to the watched file, it is incorrect to expect the file watcher to stop based on a particular signal, rather we should just flush the remaining contents of the file that have not been read before closing the cli process.
