### ISSUE TITLE
High CPU usage every saving file

### ISSUE THREAD

**Issue by wqyfavor** [microsoft/vscode#141041]
Issue Type: <b>Performance Issue</b>

Cmd + Save on Mac

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|46, 34, 20|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id d8923b90-4d96-41da-b479-93bd28f894da|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   24	   164	  1541	code main
    3	    66	  1544	   gpu-process
    0	    16	  1546	   utility-network-service
    0	   541	  1549	   window (dart_spy_runtime.cc — dart)
   24	   115	  1563	   shared-process
    0	    16	  1566	     ptyHost
    0	    16	  1582	     watcherServiceParcelSharedProcess
    0	     0	 13779	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   623	  2107	   extensionHost
    0	   131	  2122	     /Users/bytedance/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/12.0.0/clangd_12.0.0/bin/clangd
    0	    82	  2132	     /Users/bytedance/Desktop/Dev/Flutter2/flutter/bin/cache/dart-sdk/bin/dart language-server --client-id=VS-Code --client-version=3.32.0
    0	    66	  2184	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Users/bytedance/.vscode/extensions/byted-sec.bytesec-vscode-1.0.52/server/dist/index.js --pipe=/var/folders/hf/_cmmd4212kv26dtflszl5mym0000gp/T/vscode-3647147595ac55ca5db712d9e084c9603d47e682cd.sock --clientProcessId=2107
    0	   246	  2185	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Users/bytedance/.vscode/extensions/streetsidesoftware.code-spell-checker-2.1.4/packages/_server/dist/main.js --node-ipc --clientProcessId=2107
    0	    16	  2193	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=2107
    3	    66	 13776	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (dart_spy_runtime.cc — dart)
|    Folder (dart): more than 22648 files
|      File types: expect(10160) dart(7474) yaml(457) md(148) java(103)
|                  options(97) json(76) crash_dart(54) gni(26)
|                  status(24)
|      Conf files: makefile(2) cmake(2);
```

</details>
<details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.5.0
authenticator|byt|0.2.23
cloud-toolkit|byt|0.3.5
gallery|byt|0.4.11
bytesec-vscode|byt|1.0.52
doxdocgen|csc|1.3.2
dart-code|Dar|3.32.0
flutter|Dar|3.32.0
vscode-eslint|dba|2.2.2
vscode-pull-request-github|Git|0.34.3
vscode-test-explorer|hbe|2.21.1
better-cpp-syntax|jef|1.15.10
vscode-clangd|llv|0.1.13
vscode-catch2-test-adapter|mat|4.0.22
cpplint|min|0.1.3
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
test-adapter-converter|ms-|0.1.5
vscode-typescript-next|ms-|4.6.20220119
vsliveshare|ms-|1.0.5273
vsliveshare-audio|ms-|0.1.91
vscode-gn|npc|1.1.0
vscode-gnformat|per|0.0.3
java|red|1.2.0
code-spell-checker|str|2.1.4
shellcheck|tim|0.18.4
cmake|twx|0.0.17
vscode-lldb|vad|1.6.10
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2
git|vsc|1.62.3
clang-format|xav|1.9.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30424895
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710cf:30416617
vsbas813:30425875

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by weinand** [comment]
@wqyfavor are you seeing a high CPU usage on save for every file type or only for specific files?
