### ISSUE TITLE
[javascript] support color decorators in strings assigned to donNode.style

### ISSUE THREAD

**Issue by Stroichik** [microsoft/vscode#141088]
Issue Type: <b>Bug</b>

I`m taking first steps to learn a bit of coding, specifically JS. Doing exercises for JS lessons i was coding some style.border colors into HTML file, but VSCode's built-in color picker doesnt show me color preview, or opens up on hover. I dont know why. I tried disabling every extensions - still nothing.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (19.83GB free)|
|Process Argv|--crash-reporter-id 34c729dd-bd61-466a-adc9-cc292c71d79b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.11.0
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.1.0
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
vscode-pull-request-github|Git|0.34.3
scoper|Gru|0.0.13
beautify|Hoo|1.5.0
vscode-language-pack-ru|MS-|1.63.3
color-highlight|nau|2.5.0
fabric8-analytics|red|0.3.5
java|red|1.2.0
vscode-xml|red|0.18.2
open-in-browser|tec|2.0.0
highlight-matching-tag|vin|0.10.1
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30424896
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614
vscop841cf:30424584
vsbas813:30426126

```

</details>

![image](https://user-images.githubusercontent.com/12185977/150388806-358b59dc-1214-4d1d-be06-d53060cdc6a2.png)

Thats how code looks like for me without any extension running. From what i`ve seen on videos, there should be a color square before color description, and color picker should open when u hover(or click on it, probably, dunno since it  doesn't work for me).

**Comment by Stroichik** [comment]
While tinkering in HTML file i found that if i place anything color related into a <style> section of document - color picker starts to work in that section, but only there. Not rendering color preview ore editor in any other part of HTML. I dont know if its working as it should. But can it be forced to work in whole document?

**Comment by aeschli** [comment]
We currently only support color decorators inside CSS and JSON (when the JSON uses a color format annotation).

Your example is for JavaScript where a string literal is assigned to a `item.style`.
We would have to understand the format of `style.border`. Right now we only know it's a string.
We don't want to blindly add a color decorator behind every occurrence of a color name such as `blue`. 

Closing as 'won't implement'.

**Comment by Stroichik** [comment]
So there is no way to force it across whole window, rather than only certain parts of it?
