### ISSUE TITLE
Quick find next (Ctrl + F3) - Document loses focus

### ISSUE THREAD

**Issue by MohammadYounes** [Microsoft/vscode#1410]
Hi,

When making a quick find next, by highlighting some text then pressing <kbd>Ctrl</kbd>+<kbd>F3</kbd>, the search box receives focus making it hard to do quick changes to the found matches. 

The same thing happens when having a previous search then pressing <kbd>F3</kbd>.

I'm forced to click the document to be able to work with next matches.

Thanks!

**Comment by abierbaum** [comment]
Agreed.  This is very annoying.  Would be nice if find next just went to the next location and let you keep typing in the editor.

**Comment by alexandrudima** [comment]
Ok, I see, this happens in the case the find widget is hidden.

If focus is in the editor and the find widget is hidden and <kbd>F3</kbd> is pressed, focus moves to the now revealed find widget.

If focus is in the editor and the find widget is shown and <kbd>F3</kbd> is pressed, focus stays in the editor.

**Comment by alexandrudima** [comment]
@MohammadYounes 

Added two new actions for <kbd>Ctrl</kbd>+<kbd>F3</kbd> and <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F3</kbd>: "Sets the search pattern to the selected text, then search in the direction specified". These actions do not move focus into the find widget.

**Comment by MohammadYounes** [comment]
@alexandrudima  Awesome! Thanks :+1:
