### ISSUE TITLE
editor.formatOnType does not respect editor.insertSpaces setting

### ISSUE THREAD

**Issue by j-h-a** [Microsoft/vscode#14108]
- VSCode Version:
1.6.1
- OS Version:
OSX (10.11.6)

### Searchable description

VS Code keeps changing some lines to have spaces instead of tabs in the leading whitespace.

### Steps to Reproduce:

Use these settings:
	"editor.tabSize": 4,
	"editor.insertSpaces": false,
	"editor.detectIndentation": false,
	"editor.formatOnType": true,

Type some code that triggers formatOnType to activate a format change.

### Expected behaviour:
Line is formatted using tabs for leading whitespace, because of the insertSpaces setting.

### Actual behaviour:
Line is formatted with spaces instead of tabs for the leading whitespace.

**Comment by roblourens** [comment]
Is this in an html file? Could be #13563

**Comment by j-h-a** [comment]
No, this is while editing C#

**Comment by roblourens** [comment]
Related @aeschli?

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#834
