### ISSUE TITLE
My program is taking more time to execute than usual

### ISSUE THREAD

**Issue by Pratik-geek** [microsoft/vscode#141072]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

program in vs code is taking more time to execute than it generally takes

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics          (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.37GB (2.60GB free)|
|Process Argv|--crash-reporter-id cd08e690-cddd-41f8-b866-5270e2c51d23|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    96	  9012	code main
    0	    84	  2856	   issue-reporter
    0	    24	  5648	   crashpad-handler
    0	   178	  9920	   window (2.cpp - Udemy cpp - Visual Studio Code)
    1	    97	 12164	   shared-process
    0	    77	  8456	     watcherServiceParcelSharedProcess
    0	    85	 13196	     ptyHost
    0	    70	  4016	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     4	  8936	       C:\Windows\System32\cmd.exe
    0	     6	 15348	       console-window-host (Windows internal process)
    0	     6	 19700	       console-window-host (Windows internal process)
    0	   133	 12844	   extensionHost
    0	    29	 13344	     c:\Users\jadha\.vscode\extensions\ms-vscode.cpptools-1.7.1\bin\cpptools.exe
    0	    11	  7992	       console-window-host (Windows internal process)
    0	    19	  7996	       c:\Users\jadha\.vscode\extensions\ms-vscode.cpptools-1.7.1/bin/cpptools-srv.exe 13344 {396BE3E1-A97C-433E-B4A2-56299C442CF7}
    0	    37	 20076	   utility-network-service
    0	   158	 20744	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (2.cpp - Udemy cpp - Visual Studio Code)
|    Folder (Udemy cpp): 565 files
|      File types: cpp(164) exe(62) txt(58) mk(54) project(51) h(47) db(10)
|                  json(6) session(5) tags(5)
|      Conf files: makefile(5) launch.json(2) tasks.json(2) settings.json(1)
|      Launch Configs: cppdbg;
```

</details>
<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
gitlens|eam|11.7.0
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
code-runner|for|0.11.6
kotlin|fwc|0.2.23
better-cpp-syntax|jef|1.15.10
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
material-icon-theme|PKi|4.11.0
java|red|1.2.0
open-in-browser|tec|2.0.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2
material-theme|zhu|3.13.16

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30424895
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710:30416614
vscop841cf:30424584
vsbas813:30426126

```

</details>

**Comment by weinand** [comment]
What program is that?
How do you run the program in VS Code? (please provide steps)

Use the "Start Extension Bisect" command to investigate whether the problem is being caused by one of your installed extensions.

**Comment by TarunavBA** [comment]
@Pratik-geek Disable all the extensions and try again. If the problem persists then use the `Start extension bisect` as suggested by @weinand above.

**Comment by weinand** [comment]
no response - closing.
