### ISSUE TITLE
Task "detail" field is not rendered in the task list

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#141063]
In the API docs for `Task`, there's a `detail` field that reads:

> A human-readable string which is rendered less prominently on a separate line in places where the task's name is displayed. Supports rendering of theme icons via the `$(<name>)`-syntax.

However it doesn't appear to be displayed in the main task picker (under the "Run Task") command:

```ts
const task = new vs.Task(
	{ type: this.type, cwd: fsPath(projectFolder), command, args } as DartTaskDefinition,
	workspaceFolder,
	[command, ...args].join(" "),
	this.type,
	undefined,
	undefined
);
task.name = "NAME HERE!";
task.detail = "DETAIL HERE"; // SET HERE
return task;
```

![Screenshot 2022-01-20 at 12 21 40](https://user-images.githubusercontent.com/1078012/150338090-7464dd58-883c-41d8-9efe-19e9b0ff1d1d.png)

I'm trying to use this for tasks where they may be multiple instances available within a single workspace folder. For example if you open a monorepo that has 5 projects, I would like to display 5 "dart: pub get" tasks, similar to how you would see multiple if they were their own workspace folders:

![Screenshot 2022-01-20 at 12 25 39](https://user-images.githubusercontent.com/1078012/150338348-47bdad72-18d4-47e4-8163-79f85a741398.png)

**Comment by alexr00** [comment]
@DanTup when we fetch the detail can be a bit complicated:
- If the task is in your recently used tasks we don't go to the extension for the task at the time that it's displayed and instead use the cached task value for display. The task is fetched from the extension when it's selected from the quick pick. We do this to improve the performance of the task picker.
- If the task is in your tasks.json we do the same thing.
- Only if you've selected a task "folder" or are showing all tasks have we gone to the extension for the task.
- For recently used tasks, once the task has been fetched from the extension with it's new detail value once (i.e., by running) the new detail should show in the task picker.

Is your situation explained by one of the above points?

**Comment by DanTup** [comment]
@alexr00 sorry, this was completely user error. In my `resolve` method I create a _new_ `Task` (as advised [here](https://github.com/microsoft/vscode/issues/58836#issuecomment-696620105)) and I wasn't copying the `detail` over from the stub I'd previously created. I should've debugged that better, sorry for the bother!
