### ISSUE TITLE
Consider moving `resolveMarketplaceHeaders` to `vs/platform/windows/`

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#141010]
ref #140874

spotted in:

<img src="https://user-images.githubusercontent.com/1507221/149838351-a6acd63e-1e13-4903-a1a9-58607cc8c90e.png" alt="large tangle diagram" />

It looks like this dependency causes some entanglement in our services. It might be good to extract `resolveMarketplaceHeaders` to another location or simply move it to `vs/platform/windows/**` which appears to be a more "base" service.

cc @bpasero

**Comment by sandy081** [comment]
Is it enough if I move this to following file or it has to be moved out of `extensionManagement` layer completely?

https://github.com/microsoft/vscode/blob/8df0645d3c414083b8ea72464c3ff69b9e1e755b/src/vs/platform/extensionManagement/common/extensionManagement.ts#L6

**Comment by alexdima** [comment]
You could also move `resolveMarketplaceHeaders` to another more "basic" service maybe inside `/request/`. That would untangle `platform/extensionManagement` and `platform/windows`.

**Comment by sandy081** [comment]
Moved to `platform/externalServices/common` (which is renamed from `platform/serviceMachineId/common`)
