### ISSUE TITLE
Move accept/discard button of refactor preview into panel

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#141065]
The buttons to accept/discard refactorings aren't easy to discover. 

@lychung7 proposed to move them into the view (similar to the ports view) and I think we should explore that. 

![buttons fixed to bottom of panel](https://user-images.githubusercontent.com/1794099/150343277-2efe56dc-a8b4-446b-a3d4-4fc0c8ff7648.png)

**Comment by jrieken** [comment]
Alternative idea: use the existing buttons location but make the rendering much more prominent, e.g so

![buttons fixed to bottom of panel](https://user-images.githubusercontent.com/1794099/150741145-26d277ce-d398-44fb-a437-f02b76b7ad5e.png)

**Comment by isidorn** [comment]
I agree that currently the Apply and Discard buttons are not discoverable.
I prefer the first proposed solution - to show the buttons in the view (below the tree). We already have some pattern where we render buttons below the tree - Call Stack view for "Load more stack frames".
We do not have any patterns where we render buttons like that in the title area, so I am against that. Also I think it would be less discoverable.

**Comment by jrieken** [comment]
Pushed a first version of this. @misolori I was trying to use the "secondary button" style [here](https://github.com/microsoft/vscode/blob/ad2b76daee0ef0445ccc9501ccdd952dabacb806/src/vs/workbench/contrib/bulkEdit/browser/preview/bulkEditPane.ts#L160) but than the "discard" button with have no styles (transparent background). Is there another color or property that I should be using?

<img width="591" alt="Screen Shot 2022-02-05 at 15 43 04" src="https://user-images.githubusercontent.com/1794099/152646541-39d4875e-6709-418f-a9f3-55826a4be32e.png">

**Comment by misolori** [comment]
Not sure, I know when I tested the secondary buttons in the notification center, the `secondary: true` worked fine:

https://github.com/microsoft/vscode/blob/e46d9fe322ca374b3a803622f5b21dedf7443c0d/src/vs/workbench/browser/parts/notifications/notificationsViewer.ts#L469

<img width="487" alt="CleanShot 2022-02-07 at 12 14 22@2x" src="https://user-images.githubusercontent.com/35271042/152864448-2bef0370-08ba-4890-99e0-982dbc79afae.png">

**Comment by isidorn** [comment]
@jrieken can we not use the checkmark before the "Apply"? 
Before the Discard there is no icon so it is a bit inconsistent. Also we do not use Icon + text in a lot of places?

**Comment by jrieken** [comment]
> @jrieken can we not use the checkmark before the "Apply"?

✔️

**Comment by jrieken** [comment]
Closing and tracking color tweaks as bug

**Comment by jrieken** [comment]
To verify

* in TS rename a symbol with preview
* make sure the refactor preview window shows prominent accept/discard buttons

**Comment by isidorn** [comment]
Works great -> verified
I filled a follow up issue https://github.com/microsoft/vscode/issues/143736
