### ISSUE TITLE
[Bug: VS Code Snippets] When inserting a snippet, Pressing TAB inserts a Tab Space instead of moving the Focus to next Edit Position in snippet

### ISSUE THREAD

**Issue by ashuvssut** [microsoft/vscode#141004]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows 10 21H2

## ISSUE
**Suppose I inserted a snippet**
![image](https://user-images.githubusercontent.com/60546840/150183858-cb6d15df-cbd4-4c5d-9bcb-4d889145f45a.png)

Now my focus is on `Position 1`.

When I press `Tab`, instead of Moving my focus to `Position 2`, the editor inserts a Tab Space in `Position 1`
**Whats Expected?** Instead of inserting a Tab Space in `Position 1`, move the focus of the cursor to `Position 2`

----------------------------------------------
I have found a work around. when entering snippet, explicitly turn on `Tab Moves Focus` mode by pressing `Ctrl + M`.
But I think VS Code should automatically enter into `Tab Moves Focus` mode when inserting snippets and automatically turn off `Tab Moves Focus` mode  when editing the snippet is over

**Comment by jrieken** [comment]
Please share the snippet and make your `keybindings.json` file. It's likely that you or an extension have reconfigured what `Tab` does. Best is to start so: `code --user-data-dir ~/Desktop/test1-data --extensions-dir ~/Desktop/test1-ext`

**Comment by ashuvssut** [comment]
Thankyou @jrieken  for the hint. ISSUE SOLVED!

in `keybindings.json` there was keybinding that I once created to use with VS Code Vim,
`{ "key": "tab", "command": "tab", "when": "editorTextFocus && !editorTabMovesFocus" },`
I guess I have to think of an alternative to this😅
