### ISSUE TITLE
Feature: Make CTRL-C in terminal copy if text is selected like Windows Terminal

### ISSUE THREAD

**Issue by MartinEmrich** [microsoft/vscode#141073]
Is it possible to make the vscode terminal on Windows behave like Windows Terminal? Having to press CTRL+SHIFT+C/V to copy/paste just makes my mind spin, as it is CTRL+C/V everywhere else... Just when it catches on... try pressing CTRL+SHIFT+C in Edge/Chrome... A short time later back to vscode, I cancel my process instead of copying...

The new(ish) Windows Terminal seem smart: If text is selected, CTRL-C copies it. If no text is selected, it sends CTRL+C to the terminal just as expected. CTRL+V always pastes text. The CTRL-SHIFT-Variants are there, too.

On searching for similar issues, I just found #84080, who (to me surprisingly) claims the opposite... But everyone is different.

I don't see how to put different behaviours depending on "selection status" in the keybinding customizations... Am I missing something?

/label windows
/label terminal

**Comment by meganrogge** [comment]
Your settings or keybindings are causing the issue here as it works correctly - cannot reproduce the issue.

For instance, `terminal.integrated.sendKeybindingsToShell` and also consider running `Developer: Toggle Keyboard Shortcuts Troubleshooting`

**Comment by MartinEmrich** [comment]
@meganrogge thanks, removing the check on `terminal.integrated.sendKeybindingsToShell` made it behave exacly as expected :)
