### ISSUE TITLE
VSCode Insiders 1.64.0(2022-01-17 version). Issue with 'createFileSystemWatcher' and in-memory file system

### ISSUE THREAD

**Issue by jna119** [microsoft/vscode#141011]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.0-insider (16856037e075275f53b25b7e2dec2303e8e25728, 2022-01-19T05:15:25.456Z)
- OS Version: Windows and MacOS

Currently issue is reproducible in VSCode Insiders 1.64.0 only, but it is not reproducible in VSCode 1.63.2.
In result we are not sure if we need adapt our code with different solution or it is regression in upcoming version.

Issue is related to `in-memory file system`. VSCode example of it available in - [fsprovider](https://github.com/microsoft/vscode-extension-samples/tree/main/fsprovider-sample)
Problem happens when we are trying to use `createFileSystemWatcher` and listen to in-memory file changes.
In VSCode 1.63.2. that solution works, but we noticed that listeners are not called in VSCode Insiders 1.64.0.

Steps to Reproduce(we prepared slim extension based on [fsprovider](https://github.com/microsoft/vscode-extension-samples/tree/main/fsprovider-sample) VSCode example):
1. Take extension source. Extension source - https://github.com/jna119/virtualFileWatchIssue
2. Install this extension - `npm i`;
3. Run extension - press F5 key;
4. In new opened VSCode window - open any folder of existing workspace(issue is not reproducible if there no workspace opened);
5. Execute command `Create Virtual File and Open`("memfs.init"). Command does following:
5.1. Command creates virtual file based on opened folder path by appending `dummy/subfolder/test.txt`.
5.2. Command opens VSCode `TextEditor` for created virtual file .
6. In opened VSCode `TextEditor` - manually change content of `test.txt` file and save;

Problem, created watchers do not catch changes for virtual files and VSCode Info Message does not appear.

Watchers registered using `createFileSystemWatcher` - https://github.com/jna119/virtualFileWatchIssue/blob/main/src/extension.ts#L70-L81
If you run same using VSCode 1.63.2(or older versions), then such issue does not occur.

We can create workaround by listening each change using `onDidChangeFile` - [onDidChangeFile](https://github.com/jna119/virtualFileWatchIssue/blob/main/src/fileSystemProvider.ts#L213) and then manually filtering changed files.

Could you please check if it is a bug in VSCode Insiders 1.64.0 or we need adapt our code for upcoming VSCode release?

**Comment by bpasero** [comment]
Yes, see https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_64.md#vscodeworkspacecreatefilesystemwatcher-supports-any-path-now

One soft-breaking change is that `createFileSystemWatcher` with just a glob pattern will no longer report events for a file that is considered outside of the workspace. Not sure that is happening here though.

Can you check if that is the case?

**Comment by jna119** [comment]
> Yes, see https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_64.md#vscodeworkspacecreatefilesystemwatcher-supports-any-path-now
> 
> One soft-breaking change is that `createFileSystemWatcher` with just a glob pattern will no longer report events for a file that is considered outside of the workspace. Not sure that is happening here though.
> 
> Can you check if that is the case?

yes, it looks and works like that. If I use `RelativePattern` for `createFileSystemWatcher`, then I am able to create watcher for files which are in `in-memory file system` and is not in workspace. I think we can close issue, thanks

**Comment by bpasero** [comment]
I still want to check though why it wouldn't just work. My understanding is that you create a file inside the workspace and not outside?

**Comment by jna119** [comment]
@bpasero 

1. In my case file is in 'memFs'([memFs](https://github.com/jna119/virtualFileWatchIssue/blob/main/src/fileSystemProvider.ts#L51))
2. I am creating 'memFs' file using (writeFile)[https://github.com/jna119/virtualFileWatchIssue/blob/main/src/extension.ts#L64]
3. In result file is in memory and it is not added to workspace(at least that's how I understand that)

If I add `memFs` structure to `workspace` then approach with `vscode.workspace.createFileSystemWatcher('**/*.txt')` works ok.

For example working case(when `memFs` file is in workspace) - it can be reproduced as:
1. Example extension - https://github.com/jna119/virtualFileWatchIssue
2. Open extension, but there should not be any workspace or folder opened in new VSCode window;
3. Execute command `Setup Workspace` - workspace with `memFs` files is created;
4. Execute command `Create Virtual File and Open`
5. In opened VSCode `TextEditor` - manually change content of test.txt file and save;

In such case - watcher would be triggered.

Real extension's scenario is that 'memFs' files are not added to workspace

**Comment by bpasero** [comment]
This seems to me an issue with how the patterns are setup:

```ts
// Try to add watchers
const sourceFileWatch = vscode.workspace.createFileSystemWatcher('**' + fileUri.path);
sourceFileWatch.onDidChange(() => {
	vscode.window.showInformationMessage('File changed');
});
```

--> You are not supposed to add file paths to a glob pattern like that, for this reason we added `vscode.RelativePattern`.

```ts
const sourceFileWatch2 = vscode.workspace.createFileSystemWatcher(fileUri.path);
sourceFileWatch2.onDidChange(() => {
	vscode.window.showInformationMessage('File changed 2');
});
```

--> You are not supposed to use file paths as a glob pattern like that, for this reason we added `vscode.RelativePattern`.

```ts
const sourceFileWatch3 = vscode.workspace.createFileSystemWatcher('**/*.txt');
sourceFileWatch3.onDidChange(() => {
	vscode.window.showInformationMessage('File changed 3');
});
```

Valid use!
