### ISSUE TITLE
Implement a preferences UI editor smoke test for `Preferences turns off editor line numbers and verifies the live change`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141054]
**Update**

This was originally a test failure, but my suggestion in the end would be to come up with a settings smoke test that leverages the settings UI editor if possible.

**Original:**

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=151025&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=0699ae84-7245-5a45-5eee-80b086af2725&l=71

```
1) VSCode Smoke Tests (Electron)
       Preferences
         turns off editor line numbers and verifies the live change:
     Error: Timeout: get elements '.line-numbers' after 20 seconds.
      at poll (D:\a\1\s\test\automation\src\code.ts:109:10)
      at Code.waitForElements (D:\a\1\s\test\automation\src\code.ts:258:10)
      at Context.<anonymous> (src\areas\preferences\preferences.test.ts:23:4)

```

//cc @sandy081

**Comment by isidorn** [comment]
Also hit this https://dev.azure.com/monacotools/Monaco/_build/results?buildId=151056&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=0699ae84-7245-5a45-5eee-80b086af2725

**Comment by bpasero** [comment]
I yield because I think this is somewhere in preferences/configuration land.

Analyzing what goes on, evidence by the screenshot is that line numbers are indeed not off:

![turns_off_editor_line_numbers_and_verifies_the_live_change](https://user-images.githubusercontent.com/900690/150371347-12b8719b-9b94-4c64-8fc8-11688624ca4b.png)

As such, this is a correct test failure.

However, the smoke-test-runner.log shows that the steps for writing to the settings file have been followed:

```
[2022-01-20T08:56:13.715Z] dispatchKeybinding ctrl+shift+p
[2022-01-20T08:56:13.821Z] isActiveElement .quick-input-widget .quick-input-box input
[2022-01-20T08:56:13.828Z] setValue .quick-input-widget .quick-input-box input >workbench.action.openSettingsJson
[2022-01-20T08:56:13.980Z] getElements .quick-input-widget .quick-input-list .monaco-list-row.focused .monaco-highlighted-label
[2022-01-20T08:56:14.029Z] isActiveElement .quick-input-widget .quick-input-box input
[2022-01-20T08:56:14.069Z] dispatchKeybinding enter
[2022-01-20T08:56:14.176Z] getElements .quick-input-widget
[2022-01-20T08:56:14.198Z] click  .monaco-editor[data-uri$="settings.json"] .view-lines > .view-line:nth-child(1)
[2022-01-20T08:56:14.501Z] isActiveElement  .monaco-editor[data-uri$="settings.json"] textarea
[2022-01-20T08:56:14.544Z] dispatchKeybinding right
[2022-01-20T08:56:14.650Z] getElements  .monaco-editor[data-uri$="settings.json"]
[2022-01-20T08:56:14.674Z] isActiveElement  .monaco-editor[data-uri$="settings.json"] textarea
[2022-01-20T08:56:14.686Z] typeInEditor  .monaco-editor[data-uri$="settings.json"] textarea "editor.lineNumbers": "off",
[2022-01-20T08:56:14.743Z] getElements  .monaco-editor[data-uri$="settings.json"] .view-lines
[2022-01-20T08:56:14.771Z] dispatchKeybinding ctrl+s
```

So I end up being puzzled how this change could have not traveled to the editor. Is this depending on file events?

**Comment by bpasero** [comment]
I pushed a change to skip this test for now as it failed more in the past 24h.

**Comment by bpasero** [comment]
Oh, I had to skip the entire suite because I think the second test depends on the first (?)

**Comment by sandy081** [comment]
@bpasero I cant repro it and I cannot speculate what would have gone wrong. I can see that setting was changed and got updated but editor did not pick it. There could be many reasons like change events or could be editor issue. May I know what is recommended for such scenarios?

**Comment by bpasero** [comment]
How about some temporary logging only for this case? We could also temporarily expose a method on the `window.driver` that you can call to collect some more info, like e.g. the state of configuration at the time.

**Comment by sandy081** [comment]
I can add more logs for sure, but I do not know how the `window.driver` thingy works. 

Can I enable these tests again and I will have this issue open to add more logs? Since we rely on automated smoke tests and it would be important to have as less skipped tests as possible during the release so that we don't miss some real obvious bugs?

**Comment by bpasero** [comment]
> but I do not know how the window.driver thingy works

If you search for `capturePage` you can see an end to end of a method that is accessible from the smoke tests all the way into the running VSCode app where the method is implemented. Methods exposed from `driver.ts` can be used from smoke tests via the driver's IPC channel. 

> Can I enable these tests again

Yes, please do.

**Comment by bpasero** [comment]
Failed in https://dev.azure.com/monacotools/Monaco/_build/results?buildId=152826&view=results

**Comment by sandy081** [comment]
I can reproduce it locally but not consistently. Here is the screenshot.

![image](https://user-images.githubusercontent.com/10746682/151776743-81a122f7-e254-4ede-a9bf-6558109cd7ad.png)

It seems, settings got saved but the editor has not picked up the setting. Looks like the editor has missed the event. @bpasero Is there any logging in the workbench editor while listening and updating the settings?

**Comment by bpasero** [comment]
@sandy081 no logging at the moment, the code is here:

https://github.com/microsoft/vscode/blob/c8e2fd7baeaa8cd9dc43d3051db66a7428309c97/src/vs/workbench/browser/parts/editor/textEditor.ts#L67-L72

We rely on a `onDidChangeConfiguration` event being fired when settings change.

**Comment by sandy081** [comment]
@bpasero Is it possible to get the recorded screenshots for this test from the build? I remember we used to have this before?

**Comment by sandy081** [comment]
I can confirm that when this test is failing, the configuration service is triggering the change event and the line numbers settings is off - I added a log statement in the location @bpasero pointed

![image](https://user-images.githubusercontent.com/10746682/151812027-2ee20672-648a-4b37-b695-f00d4da8639d.png)

TBH, I do not understand the consistency of this failure. One thing I observed is that, it is failing when I am switching focus from the editor. I am also not sure exactly at which point of time the focus has to be switched. 

It seems `handleConfigurationChangeEvent` is not updating the change immediately if the editor is not visible. 

https://github.com/microsoft/vscode/blob/c8e2fd7baeaa8cd9dc43d3051db66a7428309c97/src/vs/workbench/browser/parts/editor/textEditor.ts#L84-L90

This seems to be causing it too

**Comment by bpasero** [comment]
@sandy081 

> Is it possible to get the recorded screenshots for this test from the build?

Only from the web smoke tests that use Playwright unfortunately.

> This seems to be causing it too

Can you send me over the steps you use to reproduce locally?

**Comment by sandy081** [comment]
As said, it was non trivial to repro this consistently. I have to say I am lucky to repro it locally after many trials and playing around with switching the focus, I could repro it and confirm that change event is being triggered. (I logged the configuration object during these trials). I will probably do more trials to understand more. I mentioned it here so that you might get a hunch of what is happening in editor land.

**Comment by bpasero** [comment]
Yeah please continue to log if you have a repro, the idea of the `isVisible` check was to buffer the setting change events if the editor is not visible and then only apply them once the editor becomes visible.

I wonder if we switch to the editor too soon after the configuration change has happened and then fail to apply it?

But I wonder: isn't the setting applied to the opened settings file as well? Why do we open another editor? Can we not just drop that part?

**Comment by sandy081** [comment]
> But I wonder: isn't the setting applied to the opened settings file as well? Why do we open another editor? Can we not just drop that part?

Thats right and I have done the same in my testing.

**Comment by bpasero** [comment]
I pushed a change to not open any random file, the entire test can be done just by checking the settings file. There is nothing involved around editor being visible or not, I would argue.

**Comment by bpasero** [comment]
This is as simple as it gets:

https://github.com/microsoft/vscode/blob/12c5c57e46e06e314bc5d29409d78a51c4c3d7bd/test/smoke/src/areas/preferences/preferences.test.ts#L15-L23

Line numbers are turned off and we await the line numbers disappearing. 

Are we sure the config change event is fired? Or does that rely only on file events? I wonder if file events are to blame here?

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/blob/fb8316c8f45d55b2bcdfaf4437f800b78139bf79/test/automation/src/settings.ts#L21-L22

This indicates to me that we rely on file events because we are not going through the UI settings editor.

**Comment by sandy081** [comment]
Simplification of the test makes sense to me.

> Are we sure the config change event is fired? Or does that rely only on file events? I wonder if file events are to blame here?

Yes, we rely on file events as we update the settings file. There was no UI editor when we have these smoke tests. I also think updating through settings editor might not be trivial in smoke tests.

I do not think file events is the issue here because, as I said, I can see the change triggered by the config service which implies it received the file change event

**Comment by bpasero** [comment]
Pushed a change to log the options we apply to see if we reach it:

https://github.com/microsoft/vscode/blob/23fa6aad5be2c359d6485c191e50c5828a3f0181/src/vs/workbench/browser/parts/editor/textEditor.ts#L266-L268

**Comment by sandy081** [comment]
My hunch is that this **will not fail** in the build anymore given that we changed validating the line numbers in the settings file which is already opened. Before, we were switching tabs after setting is saved. I am guessing that the config change event is triggered while tabs are being switched and there could be some race condition in the editor that has random file opened. This random file was hidden before and made visible with switching tabs. During this transition the editor might have missed updating the configuration. With the changes we made, this will no longer happen. It means this failure could have encountered a real bug?

**Comment by bpasero** [comment]
It is still failing, almost every run.

**Comment by bpasero** [comment]
I have added sufficient logging now that I understand what is going on: this test relies 100% on file events working at the time the change is made to the settings file. But that is fragile because file watching moved out of the renderer into the shared process. We start shared process delayed, and there is no guarantee that file events will work right on startup. We do not block the startup of the workbench waiting for the file events to work so that startup is as fast as possible.

I also think that testing the raw settings editor (JSON file) is not telling the truth: if we want to test settings, imho we should test through the settings UI editor. I verified that line numbers disappear when changing them via UI editor even when file events are disabled:

![image](https://user-images.githubusercontent.com/900690/152189313-faad413d-056f-4131-a831-c7f721fd6ab7.png)

I suggest to either drop this test entirely or find a way to make a change to the settings that works without having to rely on file events.

**Comment by sandy081** [comment]
@rzhao271 I think it would be a good smoke test for settings editor. We have similar test for keybindings editor.

**Comment by bpasero** [comment]
After a bit of discussion with Sandeep, we came to the conclusion that a change from me probably is the underlying reason for the recent flakiness in the test. Specifically, file watching is more delayed on startup ever since it moved to the shared process and if a component or test relies on file events alone, there is a higher chance of failure. 

I have opened https://github.com/microsoft/vscode/issues/142027 for me to revisit this and I can bring back this test in its old form when that happened.

Nevertheless, I still think the idea of changing this test to a UI settings editor smoke test would be desired.

**Comment by JacksonKearl** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=154454&view=logs&j=306b2268-2a17-5e97-ab97-f41a26dc5206&t=ac333dbf-2cf5-57c7-3dca-c00ab22505d6

Again in the release build:
```
  1) VSCode Smoke Tests (Electron)
       Preferences
         turns off editor line numbers and verifies the live change:
     Error: Timeout: get elements '.line-numbers' after 20 seconds.
```

**Comment by bpasero** [comment]
That cannot be from `main`, the test is skipped:

https://github.com/microsoft/vscode/blob/0d741957d9b88df9a3826a54568677423e01f1a8/test/smoke/src/areas/preferences/preferences.test.ts#L15

**Comment by bpasero** [comment]
Yeah, above is from the release 1.64 branch...

**Comment by sandy081** [comment]
Enabled the preferences smoke test after adopting to file operations event. Adopting to settings UI editor is still a value added smoke test for settings editor. So keeping this open.

**Comment by bpasero** [comment]
👏

**Comment by JacksonKearl** [comment]
This continues to bite the release build: 
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=155207&view=logs&s=27eddb93-7805-576c-c80f-37b2176e40f7&j=672276a2-8d3a-5fab-615d-090c51352f92
```
  1) VSCode Smoke Tests (Electron)
       Preferences
         turns off editor line numbers and verifies the live change:
     Error: Timeout: get elements '.line-numbers' after 20 seconds.
      at poll (D:\a\1\s\test\automation\src\code.ts:109:10)
      at Code.waitForElements (D:\a\1\s\test\automation\src\code.ts:258:10)
      at Context.<anonymous> (src\areas\preferences\preferences.test.ts:23:4)
```

**Comment by bpasero** [comment]
If it helps, we can disable it in the release branch?
