### ISSUE TITLE
VS Code is resetting a valid PYTHONPATH from env to null

### ISSUE THREAD

**Issue by MAFulator** [microsoft/vscode#141114]
Issue Type: <b>Bug</b>

# Behaviour

A valid value for the PYTHONPATH env variable (inherited from the shell from which vscode is launched) is reset to null in vscode. As a result pylance cannot find imports, and run/debug of the application does not receive the valid PYTHONPATH from the parent environment.

Same result on MacOS and linux.
vscode 1.49 + ms-python v2020.6.91350  worked as expected: PYTHONPATH was inherited normally from the parent shell.

## Expected vs. Actual Behaviour

The core property of environment variables is that they are inherited from the parent process. Therefore, in the most natural and basic case, e.g. PYTHONPATH should be setup in the shell (or other parent process) before launching vscode, and then a python application can be run/debugged with no additional setup in vscode.
This allows devops tools to manage the environment for a complex collection of packages/projects, and seamlessly launch vscode in a proper context and it just works without any manual configuration on the part of the developer.
Manually managing PYTHONPATH with vscode settings for each workspace is not workable solution for enterprise development.

It is of course helpful for vscode to provide settings to manually manage environment variables e.g. if vscode is being launched directly from a desktop menu, but the default settings should not arbitrarily overwrite the inherited environment, or at minimum there should be a setting to preserve the inherited environment. Otherwise vscode becomes cumbersome in an enterprise context.

## Steps to reproduce:

From bash on linux/macos:
```
export PYTHONPATH="/tmp/myproject/pylib"
code /tmp/myproject

```
Within vscode, run/debug the following:

```
import os

def main():
    vars = [ 'PATH', 'PYTHONPATH']
    for v in vars:
        val = os.environ[v] if v in os.environ else ''
        print(f"{v} == {val}")

main()

```
The result should include the line:
`PYTHONPATH == /tmp/myproject/pylib`

but instead is:

`PYTHONPATH ==` 

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.1
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: false
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "autopep8"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: false
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: false
• optInto: []
• optOutFrom: []

insidersChannel: "off"

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2021.12.1559732655
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.15.14-200.fc35.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (2 x 2294)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|1.89GB (0.12GB free)|
|Process Argv|--extensions-dir /sw/vscode~1.63/extensions /home/mikef/sw/test-simple~dev/..code-workspace /home/mikef/sw/test-simple~dev/..code-workspace|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|openbox|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|openbox|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by bpasero** [comment]
@JacksonKearl fyi it looks like transferred issues are not picked up by triage bot

**Comment by bpasero** [comment]
Oh, this issue was assigned to @karthiknadig up until 8h ago, maybe the bot has not picked it up.

**Comment by alexdima** [comment]
@MAFulator @karthiknadig I cannot reproduce that this is a problem with VS Code itself. Here is what I do:

* close all VS Code instances
* in a macos terminal run `export PYTHONPATH="/tmp/myproject/pylib"`
* in a macos terminal run `code .`
* in the vscode instance that comes up I open an integrated terminal and run `echo $PYTHONPATH`
* this works as expected

<img width="770" alt="image" src="https://user-images.githubusercontent.com/5047891/153892502-2341a724-abc6-4ddd-bca9-ec788b776e4a.png">


I also could not find `PYTHONPATH` in the vscode sources.

**Comment by MAFulator** [comment]
argh! There was a wrapper around `code` that was trashing the env, which I just discovered when returning to this issue after upgrade to vscode 1.73
Thanks to all for help, and sincere apologies for the wasted time.
