### ISSUE TITLE
Hard to compare two files of the same name

### ISSUE THREAD

**Issue by Bmandk** [microsoft/vscode#141132]
When comparing two files of the same name, it is next to impossible to figure out which file is which if the files are quite similar in structure. The path is not shown in the filenames above. The problem is showcased here: https://i.imgur.com/tK3Q8PD.png

Ideally, I would like to have the full path shown at the top of the file, like in this mockup: https://i.imgur.com/3nVELHx.png

**Comment by bpasero** [comment]
Good catch, this was only happening if one of the 2 files was in the root folder. It will now show up as this:

![image](https://user-images.githubusercontent.com/900690/150627961-fc3eccd0-a263-4dd3-91fe-e3361d47387d.png)
