### ISSUE TITLE
Test: Finalized API for `QuickPickItem` separators

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#141193]
Refs: #74967

- [x] anyOS @mjbvz
- [x] anyOS @joyceerhl

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23141193%0A%0A&assignees=TylerLeonhardt)

---

In this milestone, we've introduced the highly anticipated QuickPick Separators into the API.

API definition:
https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.d.ts#L1641-L1672

When you set the `kind` to `Separator` on a QuickPickItem, that QPI will be treated like a separator. Here's an example:

```ts
	const result = await window.showQuickPick([
		{
			label: 'APIs',
			kind: QuickPickItemKind.Separator
		},
		{
			label: 'showQuickPick',
		},
		{
			label: 'showInputBox',
		},
		{
			label: 'createQuickPick',
		},
		{
			label: 'createInputBox',
		},
		{
			label: 'Types',
			kind: QuickPickItemKind.Separator
		},
		{
			label: 'QuickPickItemKind',
		},
		{
			label: 'QuickInputButton',
		},
		{
			label: 'QuickQuick',
		},
		{
			label: 'InputBox',
		},
	]);

	window.showInformationMessage(`You selected: ${result?.label ?? 'nothing'}`);
```
or the long form:
```ts
	const qp = window.createQuickPick();
	qp.items = sameItemsAsAbove;

	qp.onDidAccept(() => {
		qp.dispose();
		window.showInformationMessage(`You selected: ${qp.selectedItems[0]?.label ?? 'nothing'}`);
	});

	qp.show();
```
gets you:
![image](https://user-images.githubusercontent.com/2644648/143090429-6235bf24-6184-477a-8019-0a78e1d6a2e0.png)

### Things to test

* Play around with setting the `kind` property
* Keep in mind that the only property that matters when setting `kind` to `Separator` is `label` all others will be ignored (test this)
* Ensure you can set `label` to empty string to add a blank separator
* in the long form, ensure you are also able to add buttons to the QPI and they are rendered properly (they'll be ignored if you add them to the separator QPIs)

### Useful stuff

* [Create an extension guide](https://code.visualstudio.com/api/get-started/your-first-extension)
* [Extensions samples repo](https://github.com/Microsoft/vscode-extension-samples)
* Add a finalized API: `npx vscode-dts main`

**Comment by ArturoDent** [comment]
I did notice that you cannot have 2 separators back-to-back - only the second one is rendered.  If this isn't allowed LMK and I can file an issue.  

Like this:

```jsonc
....... more
{
	label: 'Types',
	kind: vscode.QuickPickItemKind.Separator     // not rendered
},
{
	label: 'Types 2',
	kind: vscode.QuickPickItemKind.Separator   // rendered
},
...... more
```

Same result if you have:

```jsonc
const fileSeparator = {
	label: 'Files',
	kind: vscode.QuickPickItemKind.Separator,    // not rendered, makes sense
	kind: vscode.QuickPickItemKind.Default        // rendered
};
```

**Comment by mjbvz** [comment]
Looks good in my testing. Also confirmed that weird values of `kind` don't seem to cause issues

**Comment by joyceerhl** [comment]
Looks good. Adopted in RemoteHub:

![image](https://user-images.githubusercontent.com/30305945/151069807-50ab3a62-a799-44f8-9421-9eda0f10336a.png)
