### ISSUE TITLE
selectHighlights shortcut not working when search is enabled (Mac)

### ISSUE THREAD

**Issue by probaton** [microsoft/vscode#141184]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

I have `editor.action.selectHighlights` mapped to `cmd+shift+L`, which does exactly what it should most of the time, except when the in-editor/local/top-right-corner search bar is enabled. To be clear, I have a section of text in the _editor_ selected. The search bar is open, but does _not_ have focus. When the search bar is open the keybind will select all occurrences of the text _in the search bar_ instead of the text that is highlighted in the editor.

Reproduction: 
- Open an empty file
- Set file contents to "highlightText highlightText searchText searchText"
- Enable the search bar (e.g. `cmd+f`)
- Set the search bar field to "searchText" 
- Select "highlightText" in the editor window
- Trigger `editor.action.selectHighlight`

The editor will select both instances of "searchText" instead of "highlightText".

Steps taken to fix the issue:
- Remove all other functions bound to `cmd+shift+L`
- Restart VS Code

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|. --crash-reporter-id 37aaa0e8-992d-4fe0-9244-c4b3695d2b50|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
javascript-ejs-support|Dig|1.3.1
vue|jcb|0.1.5
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
vetur|oct|0.35.0
ruby|reb|0.28.1
java|red|1.2.0
synthwave-vscode|Rob|0.1.10
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30424896
pythonvs932:30410667
wslgetstarted:30426333
vscop804:30404766
vs360cf:30404996
vsclayoutctrc:30425945
vsrem710cf:30416617
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by alexdima** [comment]
@probaton I have tried with the latest VS Code and could not reproduce. I am following your steps precisely, but I am not changing any keybindings, as `Cmd+Shift+L` is bound by default to `editor.action.selectHighlights`.

Could you please try disabling your extensions and commenting out your `keybindings.json`?

https://user-images.githubusercontent.com/5047891/155592978-43ea57ef-c02a-4916-997e-0f3b7fc894ea.mp4
