### ISSUE TITLE
Semantic highlight not activating (insiders regression)

### ISSUE THREAD

**Issue by Elringus** [microsoft/vscode#141171]
Issue Type: <b>Bug</b>

In the latest insiders build semantic highlighting is no longer automatically activating when extension is activated.

Can be reproduced by installing [the extension](https://marketplace.visualstudio.com/items?itemName=Elringus.naninovel) and opening a folder with `test.nani` file with the following content:

```
; comment
```

In the stable VS Code 1.63.2 the highlighting is automatically activated and the comment line becomes colored, while in the latest insider it's not.

Notes:
 - In insiders build, if an output window with any log category is opened, the highlighting is activated.
 - When a file with a built-in highlighting is opened (eg, settings JSON), the semantic highlighting provided by the extension is activated.
 - Adding `"editor.semanticHighlighting.enabled": true` to either extension's `configurationDefaults` or to the settings doesn't help, hence it's probably not related with #118639
 - Nothing noteworthy is detected in the logs or the developer console.

-----

VS Code version: Code - Insiders 1.64.0-insider (23664355e61f3fb614932a5cb16613b4d987cfb7, 2022-01-21T13:25:29.978Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (16 x 3198)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (45.82GB free)|
|Process Argv|--crash-reporter-id c51fceed-1f91-41d7-8869-11b3f687573c|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
naninovel|Elr|1.6.3
vscode-dotnet-runtime|ms-|1.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30421357
vscop804:30404766
vscop940:30404999
vsclayoutctrt:30405800
azactmsal:30409287
pythonvspyt640:30426300
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by alexdima** [comment]
cc527241377edbf2674b672261a57ee487c677cf is the first bad commit
