### ISSUE TITLE
Assembly has the same disassembly view as C/C++

### ISSUE THREAD

**Issue by hongshui3000** [microsoft/vscode#141127]
Assembly has the same disassembly view as C/C++. Currently only c/c++ code can open disassembly, and general embedded projects will have assembly code (such as interrupt and initialization code), and assembly compilation will also add some optimizations, So I would also like to be able to open the disassembly view in assembly.

**Comment by weinand** [comment]
@hongshui3000 I do not fully understand your request.
Is "Assembly" another debug extension?
If you want to open the disassembly view from "Assembly" I suggest that you check out and analyse "Mock Debug" in order to learn how to support the disassembly view.

**Comment by hongshui3000** [comment]
![image](https://user-images.githubusercontent.com/25566498/150912981-5fbc914f-0c04-4f3d-96be-a06294d07e81.png)

**Comment by weinand** [comment]
@hongshui3000 VS Code shows the "Open Disassembly View" menu command if the current stack frame has a `instructionPointerReference` property (https://microsoft.github.io/debug-adapter-protocol/specification#Types_StackFrame).
Mock Debug sets this property here: https://github.com/microsoft/vscode-mock-debug/blob/7147a68373309fc9789e99a629a13d1a27222d30/src/mockDebug.ts#L365

**Comment by hongshui3000** [comment]
> "Open Disassembly View" menu

"Open Disassembly View" menu doesn't seem to be related to plugins

**Comment by weinand** [comment]
@hongshui3000 I don't understand what you mean.
I was never mentioning "plugins". Do you mean Extensions?

"Open Disassembly View" only appears if a debug extension supports DAP's `disassembly` request.

**Comment by hongshui3000** [comment]
> @hongshui3000 I don't understand what you mean. I was never mentioning "plugins". Do you mean Extensions?
> 
> "Open Disassembly View" only appears if a debug extension supports DAP's `disassembly` request.


Any file vscode will query whether the debug extension supports disassembly, it does not distinguish between file types such as assembly or c files
do you mean this?

**Comment by weinand** [comment]
@hongshui3000 VS Code does not care about file types for the "Open Disassembly View" command.
It only looks at the currently selected stackframe that is shown in the editor. If the frame has a `instructionPointerReference` property, then the "Open Disassembly View" command is shown in the editor's context menu.

**Comment by hongshui3000** [comment]
> @hongshui3000 VS Code does not care about file types for the "Open Disassembly View" command. It only looks at the currently selected stackframe that is shown in the editor. If the frame has a `instructionPointerReference` property, then the "Open Disassembly View" command is shown in the editor's context menu. Since the stackframe is provided by the debug extension, it is ultimately the debug extension that determines whether "Open Disassembly View" is available or not.

I probably already understand the process, thanks

**Comment by weinand** [comment]
@hongshui3000 great, thanks. Closing.
