### ISSUE TITLE
Incorrect `extends` resolving for tsconfig

### ISSUE THREAD

**Issue by zardoy** [microsoft/vscode#141112]
Currectly, tsconfig `extends` links are hardcoded and don't resolve to correct path comparing to TS behavior. TypeScript algorithm reference: https://github.com/microsoft/TypeScript/blob/febfd442cdba343771f478cf433b0892f213ad2f/src/compiler/commandLineParser.ts#L3005.

I checked it with `ts --showConfig` command.

**Comment by roblourens** [comment]
What exactly didn't work before?

One thing I notice is that the hover used to say "Follow link", now it says "Execute command" which is not as helpful

<img width="230" alt="image" src="https://user-images.githubusercontent.com/323878/155599284-486c9711-5332-415d-95b0-71b382f8bd0a.png">

<img width="272" alt="image" src="https://user-images.githubusercontent.com/323878/155599326-2afd4408-e939-4626-afcf-3b8dbff02027.png">

**Comment by zardoy** [comment]
@mjbvz asked me to open this issue for some reason, which is essentially a duplicate of https://github.com/microsoft/vscode/issues/131643.

See issue above for details. Also does the message really matter? What is not helpful here?

By the way you can look into linked PR. Original implementation didn't have this `Execute command` message.

**Comment by mjbvz** [comment]
We should restore the message. `Execute command` is the default message but is not meaningful to users in this case 

@zardoy For testing, please share an simple example of a tsconfig that didn't have a link before (or had an incorrect link) and now works

**Comment by zardoy** [comment]
File from issue above:
```json
{
	"extends": "@sindresorhus/tsconfig"
}
```
You also need to install `@sindresorhus/tsconfig` as local dependency.

Edge case that isn't in issue above, but now resolves correctly:
```json
{
	"extends": "./fileWithoutJson"
}
```

```jsonc
//@filename fileWithoutJson
{
	"compilerOptions": {
        "allowJs": false
    }
}
```

**Comment by roblourens** [comment]
Thanks, looks great
