### ISSUE TITLE
.NET Core Attach doesn't work

### ISSUE THREAD

**Issue by dil-rfuszenecker** [microsoft/vscode#141150]
Issue Type: <b>Bug</b>

1. Create a new project.
2. Add launch.json.
3. Try to attach a process.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (8.06GB free)|
|Process Argv|--crash-reporter-id dcd5baea-a99e-4f16-ba96-55124806ff29|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.0
ng-template|Ang|13.1.1
vscode-postgres|cko|1.4.0
dart-code|Dar|3.32.0
flutter|Dar|3.32.0
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.1.0
copilot|Git|1.7.4688
rest-client|hum|0.24.6
Ionide-fsharp|Ion|5.10.2
angular-essentials|joh|12.0.0
Angular2|joh|12.0.0
vscode-peacock|joh|4.0.0
roslynator|jos|4.0.0
vscode-docker|ms-|1.19.0
blazorwasm-companion|ms-|1.1.0
csharp|ms-|1.24.0
dotnet-interactive-vscode|ms-|1.0.2606010
vscode-dotnet-pack|ms-|1.0.5
vscode-dotnet-runtime|ms-|1.5.0
vscode-kubernetes-tools|ms-|1.3.6
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
powershell|ms-|2021.12.0
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
angular-console|nrw|17.13.7
material-icon-theme|PKi|4.11.0
prisma|Pri|3.8.1
quicktype|qui|12.0.46
vscode-yaml|red|1.3.0
markdown-all-in-one|yzh|3.4.0
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30424895
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710:30416614
vscop841:30424583
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by fuszenecker** [comment]
```
mkdir __x
cd __x
dotnet new webapi
code .
dotnet run --urls=http://127.0.0.1:9876
```

launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            // Use IntelliSense to find out which attributes exist for C# debugging
            // Use hover for the description of the existing attributes
            // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/bin/Debug/net6.0/__x.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            // Enable launching a web browser when ASP.NET Core starts. For more information: https://aka.ms/VSCode-CS-LaunchJson-WebBrowser
            "serverReadyAction": {
                "action": "openExternally",
                "pattern": "\\bNow listening on:\\s+(https?://\\S+)"
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach"
        }
    ]
}
```
