### ISSUE TITLE
Keyboard shortcut Alt-Shift-ArrowDown Alt-Shift-ArrowUp do not work.

### ISSUE THREAD

**Issue by inkoff** [microsoft/vscode#141107]
Issue Type: <b>Bug</b>

Do not work that Keyboard shortcut. OS elementary 6.1

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.13.0-27-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3225 CPU @ 3.30GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.57GB (10.89GB free)|
|Process Argv|/home/ink/.bash_aliases --crash-reporter-id 02481cf3-042c-468b-a838-1c5ff5144bc9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pantheon|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pantheon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.0
npm-intellisense|chr|1.4.0
es7-react-js-snippets|dsz|4.1.0
code-runner|for|0.11.6
live-html-previewer|hdg|0.3.0
smarty|imp|0.3.0
fluent-icons|mig|0.0.16
vscode-docker|ms-|1.19.0
vscode-language-pack-ru|MS-|1.63.3
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.63.13
sqltools|mtx|0.23.0
sqltools-driver-sqlite|mtx|0.2.0
LiveServer|rit|5.7.2
control-snippets|svi|1.9.1
pdf|tom|1.2.0
vscode-icons|vsc|11.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30424895
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710cf:30416617
vsbas813:30425875

```

</details>

**Comment by inkoff** [comment]
Done

**Comment by joyceerhl** [comment]
Thanks! Have you customized either Alt+Shift+ArrowDown or Alt+Shift+ArrowUp? Which commands do they map to? If you've customized those shortcuts, can you please run this command 'Open Keyboard Shortcuts (JSON)' and share the contents of your keyboard shortcuts json file: 
![image](https://user-images.githubusercontent.com/30305945/150588165-a5f22cf3-8d7d-49e7-9762-9be695a7c442.png)
