### ISSUE TITLE
support bash login args with shell integration

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#141199]
https://github.com/microsoft/vscode/blob/71ad170dc0ae4fc692f5b00e79686bc9edbadcec/src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts#L445-L450

**Comment by meganrogge** [comment]
instead of overriding, we should pass it in (if possible)

**Comment by Tyriar** [comment]
We could support a `-l` in our shell integration script, which when present will source the same files as `bash -l` does. From https://linux.die.net/man/1/bash

> When bash is invoked as an interactive login shell, or as a non-interactive shell with the --login option, it first reads and executes commands from the file /etc/profile, if that file exists. After reading that file, it looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and executes commands from the first one that exists and is readable. The --noprofile option may be used when the shell is started to inhibit this behavior.

**Comment by meganrogge** [comment]
- check if bash_profile or bash_rc runs first in a bash -l terminal
 - imitate what -l does
