### ISSUE TITLE
Filter Extension Search Results by Most Recently Updated

### ISSUE THREAD

**Issue by W3Dojo** [microsoft/vscode#141196]
# Filter Extension Search Results by Most Recently Updated
 
#### Below is an image that I will use as a reference point for describing the pre-existing feature that I propose an addition feature be added to.

---

![Feature-Request-VSCode 2022-01-21_PST](https://user-images.githubusercontent.com/82741003/150604027-7f58c67e-07eb-4b9f-bd4d-3ef749b8cf85.png)

### TL;DR

- > ###### _"For the sake of clarity, I have included a thorough description of the pre-existing feature that I am proposing an addition for. Most will not need to read this, and can just skip it all-together, however, if there is any confusion over the proposal, referring to this section may prove useful."_

When your looking at the image below, you are looking at V.S. Code's **"Extension: Marketplace"** view. In the view, their is a menu that is dropped open, that menu is the **"Filter-extensions Widget Menu"**. The Extension:Marketplace's **"Filter-widget"** is used by the user to configure their extension search (or query). Obviously, the user configures it in such a way where the search returns the most meaningful results. There are sort options too, which sorts the results returned by the search, so that the most relevant extensions are near the top, and the least relevant are placed near the bottom (or that is the goal anyways). 

---

#### Currently the Filter-widget Menu allows you to select a few options, which includes, but is not limited too.

- installed
- rating
- name
- publish date

<br>

##### It is important to note that using the menu is not the only means for configuring the query made to the Extension:Marketplace's DB, there is a custom syntax that can also be used. Here are some example of the syntax.

- @popular 
- @featured 
- @recommended 
- @sort:publishedDate
- @sort:rating
- @sort:name
- @sort:installs

##### In some cases you can mix & match syntax to try and get more organized helpful results.

<br>

## THE PROPOSAL

I Propose that a_ "Recently Updated"_ search option be added to the Extension:Marketplace's search feature.

### Semantics

The overall general semantics for the feature might look something like **_"recentlyUpdated"_**, which would result in a menu option using the name **_"Recently Updated"_** same name, and a syntax, used for custom queries, that looks like this: **_`@sort:recentlyUpdated`_**. 

### The Problems that are Solved by this Proposal

This proposal may not look like a big deal at first, but I would argue that it is not so much a nice feature to have, as much as it is necessary. There are currently two problems that are incurred, and this feature helps to solve both of them.

###### _"The first solution solves a problem that is incurred by those who frequent the extension marketplace often. I will explain from my perspective, as I feel a firsthand account is helpful."_

I often frequent the marketplace looking for new extension's. I am, of course, not interested in every new extension. Sometimes there are some really good extensions, but if they are not relevant to the software I develop, or a language I write, I could care less about them, consequently; I use the filter widget to filter out what I consider to be the junk extensions. Often times what is left are extensions I have already installed, and a bunch of low quality extensions. I generally consider the low quality extensions, as being low quality because they solve problems that another extension already does a better job at solving, they attempts to solve a problem, but that fail to solve it at the level I require, or it has a good solution to a problem, but the extensions interface was poorly developed.  

Often times extensions are published in a state that is considered by most to be low quality, but sometimes developers continue to improve there extension, and this often times creates an extension that is a hidden gem. Being able to search for extension that have been recently updated would help users to find these extensions.

#### The Second Problem Solved

The second problem that gets solved is closely related to the first, but is incurred from those sitting the opposite side of the table. I have began playing around with developing my own extensions, and recently I developed and published a theme. I have done a lot of work on the theme since its development, and I have committed that work to the themes repository, created a newly versioned VISX file, and published the theme under a new version. The theme got a some downloads, but never got supper popular because I really never finished. Recently I spent a lot of time on it, and it is actually a very nice theme. I know there are a lot of themes out there, so the competition is real when It comes to themes, but I am telling you, this is a gem. And here is where the problem is incurred, I really love my theme, and want to share it with the world, if I publish it under the same name, its unlikely many people will find it. So I will probably delete the old version, and republish so it pops up under the Recently published list, where I know some people will take a peek at it. If there was a recently updated search feature, every time I update it, it would get pushed to the top of that list. 

I didn't think about it until just now, but that actually creates an incentive for developers to update there themes regularly.

---

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/53405
