### ISSUE TITLE
Cannot unset args in osx profiles

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#141188]
It's unexpected that args is still `-l`

<img width="512" alt="Screen Shot 2022-01-21 at 1 47 23 pm" src="https://user-images.githubusercontent.com/2193314/150604568-19904e14-d069-45da-add4-d61d36cfa6a0.png">

It works with `args: []`

**Comment by Tyriar** [comment]
Code pointer:

https://github.com/microsoft/vscode/blob/6ef041e33856f453b5afb49746a7304124776704/src/vs/platform/terminal/node/terminalProfiles.ts#L26

**Comment by weartist** [comment]
It appears to be because the default configuration comes with ‘-l’ arg, when our arg is not have ‘-l’, It will be retained ‘-l’ after the merge.
So we need to add a configuration to determine if it is supported ‘-l’ by default?

**Comment by weartist** [comment]
> Code pointer:
> 
> https://github.com/microsoft/vscode/blob/6ef041e33856f453b5afb49746a7304124776704/src/vs/platform/terminal/node/terminalProfiles.ts#L26

It appears to be because the default configuration comes with ‘-l’ arg, when our arg is not have ‘-l’, It will be retained ‘-l’ after the merge.
So we need to add a configuration to determine if it is supported ‘-l’ by default?

**Comment by Tyriar** [comment]
@sandy081 is there a way to turn off this config merging at a certain level? We want full profiles to be merged, but not profile specifics

**Comment by Tyriar** [comment]
@weartist yeah we do need the merging at the first level as that's very important is all. It would be a shame to need to enumerate all profiles whenever you just want to tweak one of them.

**Comment by sandy081** [comment]
@Tyriar Unfortunately not.

**Comment by Tyriar** [comment]
Closing as no one has hit this afaik, I just noticed it, plus it can be worked around. @sandy081 we'd like that feature in config if there are other problems is causes, probably not worth adding just for this singular case.
