### ISSUE TITLE
Smoke test runner fails or hangs without error

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#141148]
The smoke test runner tends to fail or hangs without error. This is very time costly if you are only do this occasionally.

- run the smoke test on a recently cleaned vs code repo without Electron in `.build/electron`. `yarn smoketest` exits with `exit code 0`, no explanation
https://github.com/microsoft/vscode/blob/e7e89e4098985bfee0c9b382b944c8a1c50cbc24/test/smoke/src/main.ts#L107
`fail` should not only log to the logger, but also the console.

- run the web smoke test (`yarn smoketest --web`) when the port 9000 is already taken
The tests hangs in `waitForEndpoint`

In the meantime I learned that running with `verbose` helps getting useful information, such as the server log location.
It would already be helpful to print that information in the beginning.

**Comment by bpasero** [comment]
The first issue was a regression I introduced that is fixed meanwhile. Everything is now logged into a `smoke-test-runner.log` file so that we can diagnose further in the CI build machine but I forgot that some of these log messages should be printed to the console even when `--verbose` is not provided.

The second issue is something I never saw but can see how to improve it.

**Comment by bpasero** [comment]
Please try again with my changes.

**Comment by rchiodo** [comment]
Maybe @aeschli would be better to look at this, but the second part doesn't seem to be working?

I get this when running ```yarn smoketest --web``` (and creating a node app to take up port 9000)

1) VSCode Smoke Tests (Web)
       Search
         "before all" hook for "has a tooltp with a keybinding":
     Error: [10:48:21] Error: listen EADDRINUSE: address already in use 127.0.0.1:9000
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1503:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:8) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 9000
}

      at Socket.<anonymous> (D:\Source\vscode\test\automation\src\playwrightDriver.ts:339:12)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

  2) VSCode Smoke Tests (Web)
       Quick Open
         "before all" hook for "quick open search produces correct result":
     Error: [10:48:23] Error: listen EADDRINUSE: address already in use 127.0.0.1:9001
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1503:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:8) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 9001
}

**Comment by rchiodo** [comment]
Here's the code I used to occupy port 9000 (node app):

```javascript
var http = require('http');
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.write('Hello World!');
  res.end();
}).listen(9000);
```

**Comment by bpasero** [comment]
Yes that is a good result when the port is occupied, my intended fix was not to use a different port but to indicate this error to you instantly and not just hang.

**Comment by bpasero** [comment]
Given your comment I actually think this is verified. Martin can confirm.

**Comment by aeschli** [comment]
Looks good now, thanks!
