### ISSUE TITLE
onDidCloseTextEditor triggering on preview pane that is still open

### ISSUE THREAD

**Issue by anthonydresser** [Microsoft/vscode#14118]
- VSCode Version: 1.6.1
- OS Version: OSX

Related to #13623 . From that I learned that preview panes (virtual documents) have a 3 minute timer that clean ups unused virtual files. However, it appears as though this is attempting to clean up documents that are not closed, but simply not currently visible.

[Open preview panes](http://imgur.com/MnaR597)

[onDidCloseTextEditor triggering for a preview pane I have open](http://imgur.com/ZYhPbfW)

This is a problem because this means we can not trust this onDidCloseTextDocument event in order to know when to clean up data, meaning we have to hold on to data forever. Is this expected behavior? Is there a `vscode.window.visibleTextEditors` but for all open files so we can check to see if a html pane has actually been closed?

Steps to Reproduce:

1. Open two html preview panes
2. Wait for the three minute clean up to trigger and on did close document will trigger for a document you already have open but not visible.

**Comment by jrieken** [comment]
Yeah - open is defined as *visible in an editor/pane* and not as visible as tab. The latter is just a UI gesture to quickly open/restore a document (the obvious case is after a refresh, when tabs are restored but not documents). Likewise a tab that you never come back to is like a closed editor. Whatever dispose strategy one implements it's a tradeoff. 

Tho, it doesn't mean that you cannot trust the `onDidCloseTextDocument` event because that is never fired for a document currently showing (contents) and if fired on subsequent views we will ask to create the same document again.

**Comment by anthonydresser** [comment]
The problem is I need a way to know when the pane is _actually_ closed so that I can properly clean up data that is no longer needed. Currently I have two options, just never clean up the data (which could have some pretty obvious performance problems);

Or clean up the data on this current close request and have to go through and re create the data when I get the open request from vscode again, which would be a bad user experience and could have undesired side effects for the user.

**Comment by rebornix** [comment]
Run into the same issue as @anthonydresser with Vim.

> open is defined as visible in an editor/pane and not as visible as tab.

Previous I didn't know that we define `open` in above way so we clear our internal cache for buffer each time a text document is closed. It works perfectly while just opening files but it started to fail if you work on a project with language service enabled, for example, a valid TypeScript project. Each time when we switch tabs, the text document is closed and then definitely we'll clear all internal cache (like marks, macros, etc) and reinitialize it when we switch to the tab again.

**Comment by xconverge** [comment]
I was under the impression that onDidTextDocumentClose meant the tab was closed...not just switched away from...
