### ISSUE TITLE
Allow hold-down select to scroll terminal

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14114]
- VSCode Version: 1.7
- OS Version: OS X 10.11.6

![termscroll](https://cloud.githubusercontent.com/assets/4033249/19570354/7322a1be-96ae-11e6-879e-bb0404753bf9.gif)

**Comment by Tyriar** [comment]
Tracking this one in the xterm.js repo https://github.com/sourcelair/xterm.js/issues/69
