### ISSUE TITLE
Git slow in intergrated terminal

### ISSUE THREAD

**Issue by davidjhole** [microsoft/vscode#141156]
Issue Type: <b>Bug</b>

Hello, using either git in the integrated terminal or the sync function in the UI is very slow, in the example below 5 minutes in code and 20 seconds directly in PowerShell. I originally thought it was related to my company proxy but now i'm not so sure.

![image](https://user-images.githubusercontent.com/44851206/150546193-7d89459d-1da8-4c09-9259-cf404caec1dd.png)

git version 2.33.1.windows.1
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.72GB free)|
|Process Argv|--crash-reporter-id f94abdf9-0216-41b8-98b9-3edbad5e3fe1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.7.0
azure-pipelines|ms-|1.195.0
vscode-bicep|ms-|0.4.1124
vscode-dotnet-runtime|ms-|1.5.0
azure-account|ms-|0.9.11
powershell|ms-|2021.12.0
code-spell-checker|str|2.1.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30424895
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30416617
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by meganrogge** [comment]
does this happen when you disable all of your extensions?

**Comment by davidjhole** [comment]
yes still happens with all extensions disabled

**Comment by Tyriar** [comment]
Two thoughts of what this could be:

- Your pull involved way more pulling in the vscode one?
- Anti-virus or company lock down is throttling the named pipes we use to connect with the process, can you chat with your IT support to ensure all .node, .dll and .exe files within your the `<Microsoft VS Code Path>\resources\app\node_modules.asar.unpacked\node-pty\build\Release` folder and allowed?

**Comment by davidjhole** [comment]
Thanks I have opened a ticket with IT, is there an easy way to prove that it could be throttling named pipes?

**Comment by davidjhole** [comment]
this was indeed caused by IT restrictions, the issue is now resolved.
