### ISSUE TITLE
Support Tasking compiler errors in the terminal links

### ISSUE THREAD

**Issue by grumlu** [microsoft/vscode#141109]
Hi,

Tasking compiler issue messages like this ones:
ctc W593: ["C:\JWD\wks\project\software\swc\_CDD\MotCtrl\motor_app_type.h" 614/15] typedef Control_Mode_T redefined
0 errors, 5 warnings
However, the terminal is unable to detect the line and column of the error.

**Comment by Tyriar** [comment]
Right now we wouldn't want to accept this as it's a bit of an obscure format and the regex would run on every line on every terminal but get very few actual hits. Created #141305 to explore a refactor that would make that performance concern go away.
