### ISSUE TITLE
Provide a theme key for unicode highlighting

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#141153]
Unicode highlighting is currently the warning color, which is a good default, but I'd like to reduce the opacity so the text is more readable/subtle since the rectangles are there permanently.

I image if I could read Greek, the highlights would make this much harder to read:

![image](https://user-images.githubusercontent.com/2193314/150543708-eb25bb3c-8652-4d7d-a8e8-a7c3030687fd.png)

**Comment by hediet** [comment]
Such a theme key already exists: `editorUnicodeHighlight.border`.
