### ISSUE TITLE
Test ctrl/cmd+clicking of inline hints

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#141166]
Refs: https://github.com/microsoft/vscode/issues/129528

- [x] anyOS @kimadeline
- [x] anyOS @hediet

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23141166%0A%0A&assignees=jrieken)

---

For inline hints we added the ability to have them be composed out of different parts and for those parts to be interactive, e.g they can be link and can have a context menu. 

This test plan item requires to author an extension and this sample should help you get started: https://github.com/jrieken/test-inlayhints. For markdown files, this sample puts `foo` in front of "bar" and puts `bar` after "foo". It also finds all "definitions" of the foo-word. 

<img width="268" alt="Screen Shot 2022-01-21 at 18 04 39" src="https://user-images.githubusercontent.com/1794099/150569250-d83136e6-7d8a-404b-9e68-5c194c7c3eff.png">

---

* make yourself familiar with the sample 
* make your self familiar with the inlay hint API proposal, esp with [`InlayHintLabelPart`](https://github.com/microsoft/vscode/blob/516bef8deca4a3dc8544de536eb16d5e88ad8a83/src/vscode-dts/vscode.proposed.inlayHints.d.ts#L40)
* tweak the sample, e.g by adding a command to a label part, add tooltips to label parts, etc
* test that tooltips for inlay hints and label parts show (both can have tooltips)
* test that hints with an attached source location invoke go to definition as link (ctrl/cmd+click)
* test that hints with an attached source location have a context menu
* test that hints with an attached source location show the language specific hover for the location
* test that hints with an attached command have a link gesture
* test that hints with an attached command _and_ source location behave properly

**Comment by kimadeline** [comment]
I feel that I'm doing something wrong, because I can't get commands to appear on in lay hints.

I used the sample above, and added the Hello World command from the [Hello World sample](https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-sample) where the `InlayHintLabelPart` is created.

Command definition:

```ts
export function activate(context: vscode.ExtensionContext) {
  const disposable = vscode.commands.registerCommand(
    "extension.helloWorld",
    () => {
      vscode.window.showInformationMessage("Hello World!");
    }
  );

  context.subscriptions.push(disposable);

  vscode.languages.registerInlayHintsProvider(
....
```

Command usage:

```ts
          if (fooIdx < 0 || (barIdx >= 0 && barIdx < fooIdx)) {
            const helloWorld: vscode.Command = {
              title: "Hello World",
              command: "extension.HelloWorld",
              tooltip: "something hello world",
            };
            // before BAR
            const before = document.positionAt(barIdx);
            const part = new vscode.InlayHintLabelPart("potato");
            part.command = helloWorld;

            const firstFooIdx = text.indexOf("foo");
            if (firstFooIdx >= 0) {
              part.location = new vscode.Location(
                document.uri,
                document.positionAt(firstFooIdx)
              );
            }
```

> test that hints with an attached command have a link gesture
> test that hints with an attached command and source location behave properly

I understood the comments in the proposal as needing both a command and a location for the command to work properly?

https://github.com/microsoft/vscode/blob/516bef8deca4a3dc8544de536eb16d5e88ad8a83/src/vscode-dts/vscode.proposed.inlayHints.d.ts#L69-L70

What's the label of an `InlayHint` for?

https://github.com/microsoft/vscode/blob/516bef8deca4a3dc8544de536eb16d5e88ad8a83/src/vscode-dts/vscode.proposed.inlayHints.d.ts#L87-L95

**Comment by jrieken** [comment]
> I understood the comments in the proposal as needing both a command and a location for the command to work properly?

All combinations should be supported, just a command, just a location, and both. When have one (command or location) than the link gesture is the corresponding thing. Tho, the link gesture only appears when cmd/alt (depends on platform and config) hovering the link. What gesture did you try?

**Comment by hediet** [comment]
Worked for me, I used a built-in command.

Just discovered the glitch as discussed on slack, though I was not able to reliably reproduce it (after trying for at least 20 mins)... Maybe some user will find those.

**Comment by kimadeline** [comment]
Ok, turns out it was user error, I mistyped the command name (wrong casing) 🙃  Works for me!

**Comment by jrieken** [comment]
@kimadeline I am accepting a bug of not showing an error when the underlying command goes south
