### ISSUE TITLE
Local Visual Studio Code thinks that it's Online Visual Studio Code

### ISSUE THREAD

**Issue by mdwalters** [microsoft/vscode#141151]
Does this issue occur when all extensions are disabled?: Yes/No

No, I don't think so.

- VS Code Version: 1.63.2

- OS Version: Linux x64 5.4.157-17191-g6575d22de694 (running in a sandbox)

Steps to Reproduce:

1. Go to the run and debug menu
2. It will say that I need a local Visual Studio Code to use it, when I am using a local Visual Studio Code

**Comment by TarunavBA** [comment]
Hey @Mwalters75 try removing the `.vscode` folder and uninstall vscode. And install it again.

**Comment by hello-smile6** [comment]
> Does this issue occur when all extensions are disabled?: Yes/No
> 
> No, I don't think so.
> 
> * VS Code Version: 1.63.2
> * OS Version: Linux x64 5.4.157-17191-g6575d22de694 (running in a sandbox)
> 
> Steps to Reproduce:
> 
> 1. Go to the run and debug menu
> 2. It will say that I need a local Visual Studio Code to use it, when I am using a local Visual Studio Code

Sounds like an identity issue.

**Comment by weinand** [comment]
@Mwalters75
What status item do you see in bottom left corner?

![image](https://user-images.githubusercontent.com/1898161/150686763-3dd68ef1-d570-4075-b4af-eacb2ba017a8.png)

If it is green (like in my screenshot) then you are running in remote mode.
