### ISSUE TITLE
Assistance in typing function signatures

### ISSUE THREAD

**Issue by moniuch** [microsoft/vscode#141183]
Not sure where this feature belongs - more VSCode or TypeScript language service itself...

When you care about typing your code but some of the libraries are too complex, and the typing popup don't really help...

![image](https://user-images.githubusercontent.com/681956/150600952-28ab598d-281b-4ce1-a1b5-d97acc75470c.png)

You would still want to receive some help with this.
Why don't we have a contextual menu (cmd-.) that does that for ya?

**Comment by mjbvz** [comment]
Please provide a minimal example (as text) and describe the expected behavior 

/needsMoreInfo

**Comment by moniuch** [comment]
In the screenshot attached in OP, the function does not have a return type. As a dev you want to provide an explicit one though.
The language service is able to infer it, therefore it should be a Quick Fix available whenever the caret is over a function/method without a return type.

**Comment by mjbvz** [comment]
There's already a `infer function return type` quick fix that can be triggered on the function name:
![Screen Shot 2022-01-24 at 6 10 03 PM](https://user-images.githubusercontent.com/12821956/150897781-83d3d695-c2e3-47c0-a587-f52192ca8c6c.png)

If you don't see this working as expected, please open some issue with some example code
