### ISSUE TITLE
[less] Bad highlighting for first parentheses in id-mixins

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode#14119]
- VSCode Version: 1.6.1 + 1.7.0
- OS Version: Windows 10

``` less
#f(@hm: "broken highlighting in VS Code") {
    content: "";
}
```

![image](https://cloud.githubusercontent.com/assets/7034281/19576010/0f2a4682-971a-11e6-8b33-862362425cb3.png)

Proof: [less2css](http://less2css.org/#%7B%22less%22%3A%22%23f%28%40hm%3A%20%5C%22broken%20highlighting%20in%20VS%20Code%5C%22%29%20%7B%5Cn%20%20%20%20content%3A%20%40hm%3B%5Cn%7D%5Cn%5Cn%2F%2F%20Selector%20interpolation%20only%20works%20in%201.3.1%2B.%20Try%20it!%5Cn%40theGoodThings%3A%20~%5C%22.food%2C%20.beer%2C%20.sleep%2C%20.javascript%5C%22%3B%5Cn%5Cn%40%7BtheGoodThings%7D%20%7B%5Cn%20%20%23f%28123%29%3B%5Cn%7D%22%7D)

**Comment by mrmlnc** [comment]
As far as I can see, the repository [textmate/less.tmbundle](https://github.com/textmate/less.tmbundle) is dead.

May be use [`atom/language-less`](https://github.com/atom/language-less)?

**Comment by aeschli** [comment]
I update the less gramma to use atom/language-less. This fixed the issue.

**Comment by mrmlnc** [comment]
Thanks, @aeschli! I’m really grateful to you 🐼
