### ISSUE TITLE
Releasing Alt sometimes inserts characters

### ISSUE THREAD

**Issue by dmchurch** [microsoft/vscode#141175]
Issue Type: <b>Bug</b>

I don't have a reliable STR, unfortunately, but I've been having an intermittent issue for quite a while which manifests as follows:

1. Hold the Alt key. (Left Alt, if you're curious.)
2. Press Up/Down to move the current line/selection up or down
3. Release the Alt key.

The editor then acts as if I'd typed a character; sometimes `R`, or `X`, or sometimes an undisplayable Unicode character, among others. This means it gets inserted at the cursor point, or if I had a selection, it replaces the selection.

Of course, now that I'm trying to reproduce it, it doesn't happen, so I don't expect anyone else can track it down for me; for all I know it may be some weird interaction with OS-level software. What I want to know is, does VSC have some sort of internal logging where I can see what actions it has performed recently, and why? If I could narrow down what it _thought_ it was doing, I could maybe figure out _why_ it was doing it.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (18.28GB free)|
|Process Argv|--enable-proposed-api redhat.java --crash-reporter-id ac355797-2567-4ffb-9b4c-ea2f04db70d0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
java-decompiler|Ben|0.0.3
save-editors-layout|ctf|0.2.2
remove-multi-cursors|dmc|0.0.1
gitlens|eam|11.7.0
remotehub|Git|0.22.0
latex-workshop|Jam|8.23.0
local-code|loc|0.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
hexeditor|ms-|1.9.3
gradle-language|nac|0.2.3
java|red|1.2.0
functional-cursors|spo|0.0.8
vscodeintellicode|Vis|1.2.15
vscode-gradle|vsc|3.9.0
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30424895
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710cf:30416617
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by alexdima** [comment]
@dmchurch What kind of keyboard are you on? Are perhaps the arrow keys sometimes acting as a numpad? The only special kind of input on Windows that I'm aware of that sounds similar would be the `Alt+Numpad Keys` special character insertion. [Here's a site](https://www.irongeek.com/alt-numpad-ascii-key-combos-and-chart.html#:~:text=Alt%2BNumpad%3A%20A%20method%20of,In%20Windows%3A&text=Alt%2B%2C%20where,generates%20an%20OEM%2Dencoded%20character.) that explains this.

`ALT+082` would create an `R` (maybe up arrow (8), down arrow (2) )
Also `ALT+088` would create an `X` (maybe up arrow (8), up arrow (8) )

**Comment by dmchurch** [comment]
@alexdima !!!!!!!! omg you're absolutely right, that's totally what it is. Wow, I haven't thought about Alt keycodes in like two decades! And I absolutely do use the numpad on my laptop keyboard for navigation, since it doesn't have independent home/end/etc keys. (I end up switching numlock a _lot_ when I'm on this laptop.)

Y'know, I'd thought that Windows only did Alt+numpad insertions when numlock was _on_, but clearly that's not the case. At least I have a workaround, though - using the dedicated arrow keys for alt+up/down!

It does bring up a question, though: is there any way to tell Windows not to process that key combination as part of an alt code if VSCode is handling it as an event?

**Comment by alexdima** [comment]
I'm glad that was the root cause. We can continue tracking in https://github.com/microsoft/vscode/issues/22364 , but it doesn't seem likely that things will improve, I remember reporting this upstream, but nothing happening.
