### ISSUE TITLE
Testing: no progress bar when rediscovering tests

### ISSUE THREAD

**Issue by stefanhaller** [microsoft/vscode#141182]
- VS Code Version: 1.64.0-insider (23664355e6)

When opening the test browser for the first time, an indeterminate progress bar is shown while tests are being discovered. This is very useful to know when discovery is done.

However, when re-discovering tests while the browser is already open, no progress bar shows. This can be tested by pressing the "Refresh Tests" button of the python extension, or by using the "Reload Tests by C++ TestMate" command from the command palette for the C++ TestMate extension.

**Comment by connor4312** [comment]
This is technically an extension issue, but they'll get progress for free when extensions move to https://github.com/microsoft/vscode/issues/139737
