### ISSUE TITLE
VSCode Insider goes corrupt after autoupdate

### ISSUE THREAD

**Issue by Raydir** [microsoft/vscode#141149]
Issue Type: <b>Bug</b>

Version: Insyder 1.64.0

since several days the insider Version of vscode goes corrupt and  cant be started anymore when autoupdate hits in (on close of application).

I tried the following things:
- re-install over existing
- Deinstall / re-install the complete vs code insider
- switch to system setup

Any advise?

VS Code version: Code - Insiders 1.64.0-insider (be7ec0fed2492d17984ab4e3764fe3f685e6ddc4, 2022-01-21T05:16:11.878Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (18.75GB free)|
|Process Argv|--crash-reporter-id 7225540c-8dfb-4d99-8bb4-c4faee480e6c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
Bookmarks|ale|13.2.2
vdf|ali|0.3.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
vscode-npm-script|eg2|0.3.24
windows-explorer-context-menu|ele|2.3.0
vscode-npm|fkn|3.3.0
gc-excelviewer|Gra|4.0.50
todo-tree|Gru|0.0.215
ilspy-vscode|ics|0.13.1
easy-icons|jam|0.3.1
vscode-language-pack-de|MS-|1.64.3
vscode-dotnet-runtime|ms-|1.5.0
cpptools|ms-|1.7.1
opacciconbar|Opa|0.0.1
f-script|Opa|17.0.1
opacc-fscript-debug|Opa|16.20.1
webapplicationservices-language-server|Opa|6.13.2
jsdoc-live-preview|Per|2.0.0
qub-msbuild|qub|0.6.3
snippets-viewer|Ran|1.9.0
testcafe-test-runner|rom|2.1.1
testlatte|ssh|2.1.1
msbuild-tools|ste|0.0.12
addDocComments|ste|0.0.8
msbuild-project-tools|tin|0.4.3
snippets-view|use|0.2.10
cursorCharCode|zei|0.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstartedc:30421358
vscop804cf:30404767
vscop341:30404997
vsclayoutctrc:30405799
azactmsalcf:30409288
pythonvspyt640:30426300
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by joaomoreno** [comment]
> goes corrupt

How so? Do you have any error to share?

**Comment by Raydir** [comment]
@joaomoreno  Problem is just, that the "update" seems to delete the executables and doesnt reinstall them:

![image](https://user-images.githubusercontent.com/17499573/150774251-f5ca8fe0-5cc6-4219-a4d1-30dab8bbd9a8.png)

**Comment by joaomoreno** [comment]
OK. Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`. For that, completely reinstall VS Code and set that setting. Let me know if the issue resurfaces.

**Comment by Raydir** [comment]
yep, that did the trick! Thanx :)
