### ISSUE TITLE
Optimization to reduce recalculations on scrollbar scrolling 

### ISSUE THREAD

**Issue by Bistard** [microsoft/vscode#141191]
In the file `scr/vs/base/browser/ui/scrollbar/scrollbarState.ts`, calling `setScrollPosition()` will always recalculate all the computed values.

I think when changing the scroll position these recalculations are redundant except `this._computedSliderPosition`.

If I am correct about this one, I may create a simple pr to fix this one 😃 .

**Comment by Bistard** [comment]
It seems like the pr cannot be merged into the master and it says branch blocked. 

This is my first pr, if I did something please let me know :)

**Comment by hello-smile6** [comment]
> It seems like the pr cannot be merged into the master and it says branch blocked.
> 
> This is my first pr, if I did something please let me know :)

It is restricted. In other words, only specific Microsoft employees can merge to `main`.

**Comment by Bistard** [comment]
> > It seems like the pr cannot be merged into the master and it says branch blocked.
> > This is my first pr, if I did something please let me know :)
> 
> It is restricted. In other words, only specific Microsoft employees can merge to `main`.

Thank you for replying! Are there other available branches that most people would be merging into?

**Comment by hello-smile6** [comment]
> > > It seems like the pr cannot be merged into the master and it says branch blocked.
> > > This is my first pr, if I did something please let me know :)
> > 
> > 
> > It is restricted. In other words, only specific Microsoft employees can merge to `main`.
> 
> Thank you for replying! Are there other available branches that most people would be merging into?

I don't think so. But then, considering that you're neither a member of the @microsoft org nor a user with the ability to merge into `main`, it shouldn't really matter, since you couldn't merge into a different branch anyway.

**Comment by Bistard** [comment]
> > > > It seems like the pr cannot be merged into the master and it says branch blocked.
> > > > This is my first pr, if I did something please let me know :)
> > > 
> > > 
> > > It is restricted. In other words, only specific Microsoft employees can merge to `main`.
> > 
> > 
> > Thank you for replying! Are there other available branches that most people would be merging into?
> 
> I don't think so. But then, considering that you're neither a member of the @microsoft org nor a user with the ability to merge into `main`, it shouldn't really matter, since you couldn't merge into a different branch anyway.

I see. How do other people around the world submit their discovery and request a change to the repository? Are we only available to submit a new general feature or a bug and the actual Microsoft team will do the implementation?

**Comment by hello-smile6** [comment]
> > > > > It seems like the pr cannot be merged into the master and it says branch blocked.
> > > > > This is my first pr, if I did something please let me know :)
> > > > 
> > > > 
> > > > It is restricted. In other words, only specific Microsoft employees can merge to `main`.
> > > 
> > > 
> > > Thank you for replying! Are there other available branches that most people would be merging into?
> > 
> > 
> > I don't think so. But then, considering that you're neither a member of the @microsoft org nor a user with the ability to merge into `main`, it shouldn't really matter, since you couldn't merge into a different branch anyway.
> 
> I see. How do other people around the world submit their discovery and request a change to the repository? Are we only available to submit a new general feature or a bug and the actual Microsoft team will do the implementation?

No, anyone can create a PR, only Microsoft can merge.

**Comment by Bistard** [comment]
> > > > > > It seems like the pr cannot be merged into the master and it says branch blocked.
> > > > > > This is my first pr, if I did something please let me know :)
> > > > > 
> > > > > 
> > > > > It is restricted. In other words, only specific Microsoft employees can merge to `main`.
> > > > 
> > > > 
> > > > Thank you for replying! Are there other available branches that most people would be merging into?
> > > 
> > > 
> > > I don't think so. But then, considering that you're neither a member of the @microsoft org nor a user with the ability to merge into `main`, it shouldn't really matter, since you couldn't merge into a different branch anyway.
> > 
> > 
> > I see. How do other people around the world submit their discovery and request a change to the repository? Are we only available to submit a new general feature or a bug and the actual Microsoft team will do the implementation?
> 
> No, anyone can create a PR, only Microsoft can merge.

I think get the idea now, thank you so much for replying!

**Comment by hello-smile6** [comment]
> > > > > > > It seems like the pr cannot be merged into the master and it says branch blocked.
> > > > > > > This is my first pr, if I did something please let me know :)
> > > > > > 
> > > > > > 
> > > > > > It is restricted. In other words, only specific Microsoft employees can merge to `main`.
> > > > > 
> > > > > 
> > > > > Thank you for replying! Are there other available branches that most people would be merging into?
> > > > 
> > > > 
> > > > I don't think so. But then, considering that you're neither a member of the @microsoft org nor a user with the ability to merge into `main`, it shouldn't really matter, since you couldn't merge into a different branch anyway.
> > > 
> > > 
> > > I see. How do other people around the world submit their discovery and request a change to the repository? Are we only available to submit a new general feature or a bug and the actual Microsoft team will do the implementation?
> > 
> > 
> > No, anyone can create a PR, only Microsoft can merge.
> 
> I think get the idea now, thank you so much for replying!

You're welcome.
![picture](https://assets.scratch.mit.edu/045e55e80b60ddd40d5a1a2a1bb3403a.png)

**Comment by alexdima** [comment]
I have profiled scrolling and this code path is not expensive and is therefore IMHO not worth it to micro-optimize it.
