### ISSUE TITLE
Consider removing the unicode highlight scroll bar decoration

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#141152]
The main place I encounter the highlights currently are in test files where it's expected:

![image](https://user-images.githubusercontent.com/2193314/150543515-88de8122-f489-48b0-b852-31a2652dc30f.png)

I find myself often getting distracted by the scroll bar and minimap decorations, thinking I have real warnings in the file. I'd argue these warnings are mainly useful when you're actually looking at the code so am proposing not adding the decorations to the side for unicode highlighting.

If this happens, I'm also not sure whether there would need to be a setting for this. A less loud appearance seems like it would be better and sufficient.

**Comment by Tyriar** [comment]
Another case where it would be great to get rid of the scroll bar/minimap decoration:

![image](https://user-images.githubusercontent.com/2193314/151197811-1a21041e-5c9e-4641-8b9f-fb88782401dc.png)

The inline warning is nice here (after the theme color was toned down), but I don't care unless I'm looking at the code in this case.

**Comment by hediet** [comment]
I agree.

The unicode highlight feature is not about spotting weird characters in a file that you don't know the content of, but to point out that what you are currently reviewing might not be what you think.

Thus, showing the highlights in the minimap or the ruler does not make much sense.
I disabled that for good.

**Comment by rzhao271** [comment]
Got it. Considering I was in a trusted workspace, I had to adjust `editor.unicodeHighlight.nonBasicASCII`.
