### ISSUE TITLE
Clicking "README" on an installed extension prompts to install it again

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode#1411]
1. Execute the command ```Extensions: Show Installed Extensions```
2. Click on the small ```README``` button for an extension in the list
3. The readme opens in a browser as expected, but additionally the install prompt comes up:

    Info | Would you like to install *extensionName*? | Install Now | Cancel

**Comment by onionhammer** [comment]
:+1:  Just witnessed this as well.
