### ISSUE TITLE
No LSP support for TS on web (vscode.dev)

### ISSUE THREAD

**Issue by xnkevinnguyen** [microsoft/vscode#141108]
Does this issue occur when all extensions are disabled?: **Yes**/No

- VS Code Version: 1.63.2
- OS Version: Windows 11/ Edge Browser

The web version of vscode is lacking some LSP features for Typescript such as rename, Go to implementations, etc. It should be supported by web the same way it is supported by the vscode desktop client. The python extension team has the lsp features for the web extension. 

Steps to Reproduce:

1. Open a typescript project
2. Do a language service action

Expected Result: Same as desktop experience 

![image](https://user-images.githubusercontent.com/23067852/150430561-1932cff0-c145-40af-a803-ffecfa45ced7.png)

Actual Result: The code actions are not available.
![image](https://user-images.githubusercontent.com/23067852/150430612-48bdd941-de81-4f06-ad34-c315e1903cbd.png)

**Comment by mjbvz** [comment]
Please open individual issues for any features you want supported. `rename` for example is intentionally not enabled because on web we don't have access to the entire project (so a rename may unexpectedly end up breaking the project)
