### ISSUE TITLE
commit after rebasing takes forever

### ISSUE THREAD

**Issue by afdallah** [microsoft/vscode#141126]
Issue Type: <b>Bug</b>

After I run git pull branch-name -r . I fixed all the conflict but then after that when I tried to commit with the vscode git menu it keeps loading.

To solve this I need to use commind line to manually call git rebase --continue, then refresh the vscode git menu.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:38:17.605Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 3|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv|. --crash-reporter-id b2c40d9e-b06a-465d-89bf-7dec0a411048|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.8.1
alpine-js-intellisense|adr|1.2.0
vscode-caniuse|aka|0.5.4
project-manager|ale|12.4.0
react-component-generator|And|1.0.5
vscode-intelephense-client|bme|1.8.0
vscode-tailwindcss|bra|0.7.6
path-intellisense|chr|2.6.1
postcss|css|1.0.9
vscode-faker|dee|1.5.0
es7-react-js-snippets|dsz|4.1.0
gitlens|eam|11.7.0
vsc-material-theme|Equ|33.2.2
prettier-vscode|esb|9.1.0
gitpod-desktop|git|0.0.28
vscode-power-mode|hoo|2.2.0
hubl|Hub|0.15.0
eml|lei|0.4.0
google-fonts|lio|0.0.1
regexp-preview|Lou|0.1.5
dotenv|mik|1.0.1
mongodb-vscode|mon|0.8.0
vscode-docker|ms-|1.19.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
live-server|ms-|0.2.12
vsliveshare|ms-|1.0.5273
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
prettier-standard-vscode|num|0.9.2
advanced-new-file|pat|1.2.2
material-icon-theme|PKi|4.11.0
vscode-thunder-client|ran|1.10.0
vscode-yaml|red|1.3.0
LiveServer|rit|5.7.2
synthwave-vscode|Rob|0.1.10
gruvbox-material|sai|6.5.0
code-settings-sync|Sha|3.4.3
vscode-scss-formatter|sib|2.3.3
vscode-fileutils|sle|3.5.0
vscode-standard|sta|2.0.1
vscode-styled-components|sty|1.7.2
ayu|tea|1.0.5
email-viewer|Tom|5.0.0
vscode-pets|ton|1.9.3
vscodeintellicode|Vis|1.2.15
vim|vsc|1.21.10
quokka-vscode|Wal|1.0.439
codesandbox|yes|0.0.8

(12 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30424895
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30416617
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by lszomoru** [comment]
Related to https://github.com/microsoft/vscode/issues/114461. 
This issue has been fixed in today's Insiders release (2022-07-21) or later.
Please give it a try and let me know if you are still experiencing this issue. Thank you!
