### ISSUE TITLE
only the first created terminal has capabilities enabled on create

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#141160]
![Recording 2022-01-21 at 09 12 24](https://user-images.githubusercontent.com/29464607/150551263-7ea2225b-2e48-440b-865d-b721d1dc7add.gif)

**Comment by meganrogge** [comment]
other info:
- changing the directory in the 2nd terminal will result in the cwdDetection capability getting added
- maybe this is by design? If so, should be consistent with terminal 1, 2, 3 etc

**Comment by Tyriar** [comment]
Think this might actually be an issue with filling the hover, I haven't seen the list for a while at least on windows.

**Comment by Tyriar** [comment]
This doesn't happen because we don't listen to capability change events and refresh the tabs.

**Comment by Tyriar** [comment]
Fixed part of this but not the listener yet.
