### ISSUE TITLE
SemanticTokensModifier provided by language server are not interpreted correctly

### ISSUE THREAD

**Issue by moosq** [microsoft/vscode#141131]
SemanticTokensModifier are defined as bitset where each set bit represents a chosen modifier. Instead the provided value is taken as direct index into the legend provided during initialisation.
Legend:

``   
    "legend": {
                "tokenTypes": [
                    "namespace",
                    "type",
                    "class",
                    "enum",
                    "interface",
                    "struct",
                    "typeParameter",
                    "parameter",
                    "variable",
                    "property",
                    "enumMember",
                    "event",
                    "function",
                    "method",
                    "macro",
                    "keyword",
                    "modifier",
                    "comment",
                    "string",
                    "number",
                    "regexp",
                    "operator"
                ],
                "tokenModifiers": [
                    "declaration",
                    "definition",
                    "readonly",
                    "static",
                    "deprecated",
                    "abstract",
                    "async",
                    "modification",
                    "documentation",
                    "defaultLibrary"
                ]
            },
  ``

For following modifiers declaration(Bit 0) and readonly(Bit 2) the value `1*2^0+1*2^2 = 1+4=5`

I got this result:
![image](https://user-images.githubusercontent.com/53606936/150368431-66f99ca5-5b77-4423-a76d-226cdda6e8d3.png)

abstract which is obviously at Bit position 5 but should be represented by a value of `1*2^5 = 32`

vscode version: 
Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by dbaeumer** [comment]
@alexdima can you please check. I pass these values one to one to the API and according to VS Code modifiers are a bit mask.

**Comment by moosq** [comment]
I have to apologize. Everything seems to be ok. It was my fault as the language server itself transmitted the wrong value
