### ISSUE TITLE
Clicking F11 while not in debug mode turns on debug instead of going full screen

### ISSUE THREAD

**Issue by RadhiRasho** [microsoft/vscode#141157]
Have a few configurations (mine were javascript client/server attach) for the debugging and click F11, while not in debug mode, and have `Auto Attach` turned on with `With Flag` as the option.

Once clicking F11, it tries to turn on debugging for a few seconds, and then stops: 

This is the Output from the Log (Window) error that appears: 
![image](https://user-images.githubusercontent.com/54078496/150546585-a3173af6-63cc-4ee0-95be-1a56274514fb.png)

**Comment by mjs510** [comment]
It seems these are both the defaults in 1.66.2.

```
{
  "key": "f11",
  "command": "extension.node-debug.startWithStopOnEntry",
  "when": "!inDebugMode && debugConfigurationType == 'node' || !inDebugMode && debugConfigurationType == 'pwa-extensionHost' || !inDebugMode && debugConfigurationType == 'pwa-node'"
}
```

```
{
  "key": "f11",
  "command": "workbench.action.toggleFullScreen",
  "when": "!isIOS"
}
```

So, for example, F11 starts debugging in a Node project but toggles full screen in other projects.

**Comment by weinand** [comment]
@mjs510 the keybindings work as designed.

**Comment by RadhiRasho** [comment]
Is there no way of having it go into "Start Debugging" mode when a specific condition is met? Something like `when: isDebugOn`?
I typically have the auto attach feature set to `With Flag` so that when I run an npm script with `--inspect` it automatically activates debug mode. 

Another option is to have F11 start debugging if the user is in the Debug tab of the sidebar. Just ideas, not something that is really needed, sense it isn't causing any urgent issues.

**Comment by connor4312** [comment]
Ultimately this will still cause a conflict for users who both want to toggle fullscreen and do use debugging. So we should relocate or specify one keybinding or the other...

**Comment by connor4312** [comment]
Reviewing this, looks like we have both "F10" and "F11" as keybindings. Unfortunately we don't have a way to differentiate which keybinding triggered entering debug mode in our telemetry, and a sizable number of users (>10K) have used one of these keybindings recently, so I don't just want to boot one of those off.

I like the compromise of only running the command on F11 when the debug view is the active viewlet.

**Comment by aeschli** [comment]
Verified that F11 only starts debugging if the debug view is visible (also if not active)
