### ISSUE TITLE
Rust - inconsistently incorrect syntax highlighting for "weak keyword" `union`

### ISSUE THREAD

**Issue by cyqsimon** [microsoft/vscode#141141]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: `1.62.0 b3318bc0524af3d74034b8bb8a64df0ccf35549a x64` (Code OSS)
- OS Version: `Linux 5.4.169-1-MANJARO x86_64`

## Steps to Reproduce

1. In VSCode, create a new file and paste in the following code. Set the language to Rust if necessary. It is not necessary to install any extensions.
```rust
use std::collections::HashSet;

fn main() {
    let set_a = HashSet::from([0, 1]);
    let set_b = HashSet::from([2, 3]);

    let set_c: HashSet<_> = set_a.union(&set_b).collect();
    dbg!(set_c);

    let set_d: HashSet<_> = [set_a, set_b]
        .into_iter()
        .reduce(|acc, set| acc.union(&set).cloned().collect())
        .unwrap();
    dbg!(set_d);
}
```
2. Observe that the two calls to `HashSet::union` are highlighted differently
- The first call is highlighted with the same styles as other method calls, which is the expected behaviour
- The second call is highlighted with the same style as other keywords, which is incorrect in this context

![shot-20220121-195731](https://user-images.githubusercontent.com/28627918/150523447-d8e29f6f-919c-47b7-86d6-d3ed2e33e633.png)

## What I guess is happening
`union` in Rust is a "weak keyword" (see [here](https://doc.rust-lang.org/reference/keywords.html#weak-keywords)), and the syntax highlighter currently has some kind of special handling for the case when `union` is not used as a keyword. However in some cases the special handler is not invoked when it should have been, leading to this inconsistent behaviour.

**Comment by RedCMD** [comment]
FYI; I have no expirence in Rust

Problem is `"keywords"` and `"functions"` is applied in the wrong order underneath `"functions"`
![image](https://user-images.githubusercontent.com/33529441/150634308-224e3ada-97f9-4a7d-b1c9-0d5056e58d28.png)
Moving `"keywords"` underneath `"functions"` fixes this issue

This however, create issues with every single `"keywords"` keyword now being marked as a function; Including operators
Tho this may be a non-issue depending on what has higher priority in Rust
![image](https://user-images.githubusercontent.com/33529441/150634291-ad2dfb73-c189-4dd3-a746-66ad7a62689f.png)

**Comment by cyqsimon** [comment]
Oof. First of all thanks for tackling this. However I've got a strong feeling that this kind of "swap them and hope it works" solution is quite dubious and may cause unexpected side-effects, either right now or down the line.

Now I am the exact opposite to you - I am decently competent in Rust but have no experience in the inner workings of VSCode, so my following suggestion may be impractical to implement:

It is possible to create "weak keywords" as its own category of pattern, then handle them separately? To my Rust-oriented brain, it feels much better to enumerate all the different categories of lexical tokens explicitly and handle each one of them, than to rely on some shaky ordering in logic to implicitly handle "a category within a category".

Not sure if what I wrote is any understandable - feel free to question me if not.

**Comment by RedCMD** [comment]
Are all the keywords in the list in that picture above 'weak'?

Looking the top of the file, the order of includes is differenet and has `"#functions"` above `"#keywords"`
![image](https://user-images.githubusercontent.com/33529441/150651935-edd63bf5-eda5-4b48-8820-efcf63e5dbe4.png)

Managing the order of patterns in textmate is very common
especially when you have an explicit pattern like `"keywords"` that only matches certain words
and a more general pattern like `"functions"` that just matches any word available

**Comment by cyqsimon** [comment]
Okay thank you. I will open an issue there as suggested.

**Comment by alexr00** [comment]
Thank you for opening the issue in https://github.com/dustypomerleau/rust-syntax!
