### ISSUE TITLE
Connection Error while running code

### ISSUE THREAD

**Issue by Adity03** [microsoft/vscode#141128]
We have written the needed data into your clipboar
Issue Type: <b>Bug</b>

**Urgent**Getting the following error when i run code on VS code. Work is blocked currently.
ClientRequestError: Error occurred in request., ConnectionError: HTTPSConnectionPool(host='eastus.api.azureml.ms', port=443): Max retries exceeded with url: /pipelines/v1.0/subscriptions/0413db21-0acb-497a-abed-5a42f700a527/resourceGroups/sm-infra-stable-rg/providers/Microsoft.MachineLearningServices/workspaces/autotrain/DataTypes (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000248EADA9CC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (4 x 2112)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (1.13GB free)|
|Process Argv|--crash-reporter-id be9caebd-28f9-4003-a0d9-2af4c9b5cc15|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.34.3
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30422344
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30424896
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30416617

```

</details>

d because it was too large to send. Please paste.

**Comment by JacksonKearl** [comment]
@Adity03 this seems to be an issue with the code you are running rather than VS Code core. Could you provide screenshots of where you see this happening? Also, try running with extensions disabled to see if one of them is causing the problem. As far as I know VS Code core doesn't call out to any `azureml` domains.
