### ISSUE TITLE
Needed validation in `contributes.keybindings` for extension manifest

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#14111]
While building a keymap extension I ran into an issue. 

I created a keybinding contribution as seen below:

``` json
{
  "mac": "ctrl+shift+pageup",
  "win": "alt+shift+pageup",
  "linux": "alt+shift+pageup",
  "command": "cursorColumnSelectPageUp",
  "when": "editorTextFocus" 
}
```

What is wrong with the above? 

Once I debugged the extension I found the issue. 

![image](https://cloud.githubusercontent.com/assets/2449568/19569406/77f42bee-96aa-11e6-937b-9c9cc4eaf2bb.png)

Two things could be fixed here:

1 - The error message is too large and so I cannot see what is going on. I did figure out that I can see the same error in the debug console. It would be better if there was a way to see the complete message in the error box. (ping @bgashler1 @stevencl on this one)
2 - I would've expected to have caught this with the JSON validation of the file. We should introduce a squiggle line indicating that the keybinding object is missing a required `"key"` property. 
3 - The error message should indicate the line number where the issue exists. See the debug console error message below does not give me an indication where the problem is. 

![image](https://cloud.githubusercontent.com/assets/2449568/19569706/9e057a44-96ab-11e6-80c3-6ba0e21e314e.png)

To fix this today, I simply need to add the `key` property. 

``` json
{
  "mac": "cmd+shift+l",
  "win": "ctrl+shift+l",
  "linux": "ctrl+shift+l",
  "key": "ctrl+shift+l",
  "command": "editor.action.insertCursorAtEndOfEachLineSelected",
  "when": "editorTextFocus"
}
```

As an aside, I created https://github.com/Microsoft/vscode/issues/14112 to address the necessity of the `"key"` property.

**Comment by bgashler1** [comment]
Related to #1135

**Comment by isidorn** [comment]
Closing as dup of https://github.com/Microsoft/vscode/issues/1135
