### ISSUE TITLE
Batch-close all tabs of a similar type/plugin

### ISSUE THREAD

**Issue by moniuch** [microsoft/vscode#141173]
After reviewing Git changes, I usually end up with a lot of Working Tree tabs open.

![image 2022-01-21 19-23-21](https://user-images.githubusercontent.com/681956/150580573-0e0fa442-e6a1-4fa3-b7eb-3b485da01162.png)

I would like to be able to close all of them in one go.
(I now right-clicked over such a tab to double-check if there is a help but apparently there is not.)

So my request would be to add such a context menu command, to either close all Git windows, or - maybe make it more universal - close all tabs belonging to a given type/plugin.

**Comment by lszomoru** [comment]
All diff editors can be closed using the "Git: Clone All Diff Editors" command from the command palette.
