### ISSUE TITLE
How can I change the color of commands in vs code terminal?

### ISSUE THREAD

**Issue by ayushiamazing** [microsoft/vscode#141155]
![image](https://user-images.githubusercontent.com/90521537/150545054-0cbb917b-dd87-4640-a5bf-0fb7cf5e1504.png)
Sir, I want to ask that why the color of the command in the first terminal (which is git bash) is not changed as the one in the second terminal (which is powershell) and also tell how can I fix it.

**Comment by meganrogge** [comment]
It looks like you're using the Java extension contributed terminal. I cannot reproduce the problem in plain pwsh terminals in vscode, so create an issue for them or tweak your settings.
![Screen Shot 2022-01-21 at 9 19 07 AM](https://user-images.githubusercontent.com/29464607/150552178-592d8022-0350-4af0-b21f-6a14004f0e11.png)

**Comment by ayushiamazing** [comment]
![image](https://user-images.githubusercontent.com/90521537/150555763-799ffa88-b4aa-4f17-ab6d-36716607f0ca.png)
![image](https://user-images.githubusercontent.com/90521537/150555990-7fadad00-080c-47bb-a1f8-01aade3dacbb.png)
Sir, the same issue is not only happening with Java but with Python too. Is it too caused by the extension?

**Comment by meganrogge** [comment]
yes
