### ISSUE TITLE
File not saving - no content showing in saved files

### ISSUE THREAD

**Issue by MJDQ** [microsoft/vscode#141118]
ADD ISSUE DESCRIPTION HERE

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14324.62.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.77 Safari/537.36
Embedder: vscode.dev

**Comment by gjsjohnmurray** [comment]
> ADD ISSUE DESCRIPTION HERE

/needsMoreInfo
