### ISSUE TITLE
vscode.open does not differentiate between single and double clicking

### ISSUE THREAD

**Issue by HannaSwidaPieces** [microsoft/vscode#141145]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2 
- OS Version: 12.0.1 macOS monterey

Steps to Reproduce:

1. Use the vscode.open like in the example below on command upon clicking a treeview Item (Virtual Document):
```
         const doc = await vscode.workspace.openTextDocument(uri);
        await vscode.commands.executeCommand("vscode.open", vscode.Uri.parse("snippetPreview:" + label));
        vscode.commands.executeCommand("workbench.list.openMode")
        vscode.languages.setTextDocumentLanguage(doc,extToString[language].toLowerCase())
```
2. After extension compilation double click on the item that calls the function. The file opens in italics, but double clicking does not pin it. Double clicking its name on the tab does pin it, though.

**Comment by aeschli** [comment]
Not sure if our treeItem API allows to add a different command for double click.

**Comment by alexr00** [comment]
@HannaSwidaPieces if you want to take advantage of VS Code file opening conventions then you need to use the `vscode.open` command directly as the tree item's `command` without calling `executeCommand`:

https://github.com/microsoft/vscode/blob/77ee9ba8795ca057f1260d0d3a9dbf5ac77bdaf3/src/vscode-dts/vscode.d.ts#L9616-L9623
