### ISSUE TITLE
Search in files (Ctrl+Shift+F) with UTF-16 LE encoding does not work

### ISSUE THREAD

**Issue by kohlmayer** [microsoft/vscode#141164]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open directory with UTF-16 LE encoded text files in visual studio code
2. Search (Ctrl+Shift+F) in this directory (not in open editors) and no search results will appear if search string is found in UTF-16 LE encoded files.

Thanks!

**Comment by roblourens** [comment]
You need to set `files.encoding` - encoding autodetection doesn't work in workspace search
