### ISSUE TITLE
A lot of eslint warnings due to relative imports now being banned

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#141165]
Might have been done by accident, but there are a bunch of failures.

![image](https://user-images.githubusercontent.com/2193314/150566046-b0aabfa8-f6e4-4adc-b152-6337361ee0f8.png)

Search:

```
^import.+'\.
```

In:

```
./src/**/*.ts
```

Most of these are eslint warnings, which makes merging from origin/main sometimes a confusing experience as precommit hooks run on merge.

![image](https://user-images.githubusercontent.com/2193314/150566012-5da24396-2906-4659-997f-f51336e4aca5.png)

Assigning to @alexdima since you have touched eslint rules a lot recently.

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/vscode/commit/54b242dcd74e16ad6bf4e7f0ab5c8292479e6805
