### ISSUE TITLE
[Test view] [UX]: layout shift when starting tests for the first time.

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/vscode#141181]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: all
- OS Version: all

This is a minor UX annoyance. When running tests for the first time, the entire test tree shifts under the mouse cursor because of the `1/10 tests passed` label inserted above the test tree.

**Comment by pavelfeldman** [comment]
@connor4312 ^^

**Comment by JDaance** [comment]
It also shifts again during run when the label gets longer then the width of the panel and wraps

![image](https://user-images.githubusercontent.com/1148112/154287239-9e9a7d66-ff68-49fc-a9ab-8d070b3f0cdc.png)

![image](https://user-images.githubusercontent.com/1148112/154287351-d29545cb-ce0b-45e2-84f3-748e677c7726.png)
