### ISSUE TITLE
Tangle in `/platform/`

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#141154]
ref #140874

![image](https://user-images.githubusercontent.com/5047891/150544465-61a769b4-2ce0-4d85-b98b-a913f206ff7e.png)

**Comment by alexdima** [comment]
Reduced to:

![image](https://user-images.githubusercontent.com/5047891/150546429-93e2b67c-2120-4264-b075-63a2ee8770eb.png)

**Comment by alexdima** [comment]
Reduced to:

![image](https://user-images.githubusercontent.com/5047891/150552914-e8e515f2-232e-40be-9260-9a8878ff550b.png)

**Comment by alexdima** [comment]
Reduced to:

![image](https://user-images.githubusercontent.com/5047891/150560964-cbb84959-971f-4c0b-af4b-75653bfbcc83.png)

**Comment by bpasero** [comment]
Thanks to Jo, I am now also setup and can contribute.

**Comment by bpasero** [comment]
There is no more `workspace` dependency to `workspaces`:

![image](https://user-images.githubusercontent.com/900690/152835858-d56a06bc-8604-4131-b111-945f5f130f33.png)

**Comment by bpasero** [comment]
This is now down to just 3 small ones, I am not sure what the idea is how far we want to go:

![image](https://user-images.githubusercontent.com/900690/153819891-9e3e6e4a-6bfc-495b-985f-f31862b16a1b.png)

I am not sure how to solve that other than merging `workspaces` and `windows` into one.

![image](https://user-images.githubusercontent.com/900690/153820015-e5a3e93f-ef59-4845-8293-8af8d3e4c15b.png)

Similar, hard to break up: file service needs log service and some of the log service implementations need file service.

![image](https://user-images.githubusercontent.com/900690/153820036-df889143-8fa2-4c30-be98-930ffc4c8f96.png)

The tangle of 4 is somewhat ugly: `actions` should not depend on `storage` but it includes some kind of widgets that have storage service dependencies (`DropdownWithDefaultActionViewItem`). `window` depends on a very generic interface from `actions` for its touch bar support. I feel if we wanted to further clean this up, `actions` needs to split into 2 components.

**Comment by bpasero** [comment]
I got rid of the 4er tangle by introducing `vs/platform/action` alongside `vs/platform/actions`. I feel we could rename `vs/platform/actions` to `vs/platform/menus` because most of it is about menus, but then I noticed there is also `IAction2` inside...

**Comment by alexdima** [comment]
👏  NICE !
