### ISSUE TITLE
Support references links when no [] exists

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#141285]
I see we support linking to the source for `[ref][ref]` and `[ref][]` formats, but not `[ref]`.

![image](https://user-images.githubusercontent.com/2193314/150805346-638c1d8c-9292-4bbd-ab59-e3f21032b2e7.png)
![image](https://user-images.githubusercontent.com/2193314/150805356-c4af5725-429f-4894-983b-6394b3dfe4e2.png)
![image](https://user-images.githubusercontent.com/2193314/150805372-5bdcb7bd-42e6-40ab-a818-301e069e880a.png)

I see it's not mentioned as much in "specs" but in my experience it has always worked. Would be handy to see the underline to quickly see what references are declared below.

**Comment by BamBamboozled** [comment]
Taking a look at this, if that's okay! If I don't respond in 1 day, can go back to up for grabs.

**Comment by BamBamboozled** [comment]
Should be ready for review!
