### ISSUE TITLE
Open code with minimal/no extensions loaded

### ISSUE THREAD

**Issue by kilasuit** [microsoft/vscode#141248]
Issue Type: <b>Feature Request</b>

I have a number of extensions that are installed in Code (stable and insiders) and I would like to the ablity to be able to open code with either a default set of extensions loaded as well the option to do so with no extensions at all.

This request is inspired by [PowerShell's Profile system](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.2) and `-noprofile` switch on the execuatble

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by alefragnani** [comment]
@kilasuit ,

You could try the Command Line options:

* `—disable-extensions`: _Disable all installed extensions. Extensions will still be visible in the Disabled section of the Extensions view but they will never be activated._
* `—extensions-dir`: _Set the root path for extensions. Has no effect in Portable Mode_

With `—extensions-dir` you could create _profiles_ for each set of extensions you want

More info here https://code.visualstudio.com/docs/editor/command-line

Hope this helps

**Comment by kilasuit** [comment]
@alefragnani that seems to do exactly what I want and I could manage very easily with a custom code function in PowerShell.
