### ISSUE TITLE
[typescript] VS Code won't use lib ES2015 type definitions

### ISSUE THREAD

**Issue by ricokahler** [Microsoft/vscode#14123]
I'm trying to use some ES2015 features (specifically `Object.assign`).

Since typescript 2, [there is built in type definitions for ES2015 using the `--lib` option](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#including-built-in-type-declarations-with---lib) and similarly, there is a `lib` `compilerOptions` key in the `tsconfig.json` file.

I have the `lib` option changed to contain `es2015`. My project compiles fine with from `tsc` with no errors but VS Code yells at me for using `Object.assign` and other ES2015 features.

I see that VS Code actually contains the type definitions in `Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\lib.es2015.d.ts`.

**Is there a way to get vs code to use those type definitions? Is this a bug and should this already happen?**

I already have webpack including the respective polyfills but I can't seem to get the type definitions working in vs code. Any ideas?

Thanks!

- VSCode Version:
1.6.1
- OS Version:
Windows 10
Steps to Reproduce:

1. Use vs code to open a typescript project with es2015 types with an es5 target.
2. Observe that vs code yells at you
![image](https://cloud.githubusercontent.com/assets/10551026/19578450/af229184-96e9-11e6-947f-6ec9b04da7e5.png)

**Comment by roblourens** [comment]
This works for me. What if you restart vs code?

**Comment by ricokahler** [comment]
I restarted VS Code and tried it on another windows 7 installation. I still have the same problem. I can provide the whole project folder or any other resources if that helps identify anything.

**Comment by ricokahler** [comment]
Just to clarify, vs code is suppose to use the es2015 type definitions if i include the `es2015` string in the `lib` `compilerOptions`, correct? Is this seemingly a bug or is it my fault?

**Comment by roblourens** [comment]
Yeah, for me, it works like you expect.

**Comment by ricokahler** [comment]
I created a brand new typescript project with `"lib": ["es2015", "dom"]` and `Object.assign` is working like expected. But my existing typescript project doesn't work and I have the same compiler options for this project. **It seems like I'm doing something wrong here or this is some weird edge case.**

I've cloned the same project and tested it on three windows machines (one with a brand new vs code installation) and i'm getting the same error. The [project is available here](https://github.com/ricokahler/harmony/tree/42655bc3fdadd67c0f37d6e0372336b966510fed) (ignore the contents).

Steps to reproduce (if you're so willing):
1. Clone [this](https://github.com/ricokahler/harmony/tree/42655bc3fdadd67c0f37d6e0372336b966510fed)
2. Open folder with code
3. Navigate to `src/example.ts`
4. Observe the errors from `Object.assign`
![image](https://cloud.githubusercontent.com/assets/10551026/19588910/d8d3fdcc-9736-11e6-92a9-9fdcc6fc772f.png)

**Comment by ricokahler** [comment]
It did not work for me right away in vscode insiders. I had to use the version of typescript (2.0.6) bundled with insiders and then it works. Using the bundled version changes `"typescript.check.workspaceVersion"` to `false` in `.vscode/settings.json`.

Works for me in vs code stable if I `npm install typescript@next` (which is currently `typescript@2.1.0-dev.20161021`) and then add change `"typescript.tsdk"` to `"./node_modules/typescript/lib"` in `.vscode/settings.json`.

Anyway I'm just the bug is already fixed. Just gotta wait till a new version of typescript to be released
