### ISSUE TITLE
explorer shows nothing after downgrade from 1.63.2 to 1.46.1

### ISSUE THREAD

**Issue by liesauer** [microsoft/vscode#141204]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.46.1
- OS Version: win10

Steps to Reproduce:

1. upgrade to version `1.63.2`
2. downgrade to version `1.46.1`

![image](https://user-images.githubusercontent.com/8676741/150631158-bd85cb79-aaea-4e15-bcc4-62b3b04248f7.png)

**Comment by JacksonKearl** [comment]
Could you try opening vscode with a different user data directory? i.e. `code --user-data-dir ./tmp`

**Comment by liesauer** [comment]
> Could you try opening vscode with a different user data directory? i.e. `code --user-data-dir ./tmp`

this solution works. but i resolve this by removing `%appdata%\Code` folder.
