### ISSUE TITLE
Regex can't support Zero-Length Assertions

### ISSUE THREAD

**Issue by STayinloves** [Microsoft/vscode#14129]
- VSCode Version:1.6.1
- OS Version:win10 1607

Steps to Reproduce:
1. toggle search palette
2. input expression like`/(?<=\w)\w/`
3. it will show that "Invalid regular expression"

If it possible to add this property to vscode, or if I miss some settings to open this feature.

**Comment by roblourens** [comment]
This is not (yet?) supported by Node, but is by Chrome for some reason. If it ends up working in Node, it will work for single file search. But it will likely never be supported by ripgrep, the full text search provider.
