### ISSUE TITLE
Image preview transparency background is affected by scaling

### ISSUE THREAD

**Issue by haykam821** [microsoft/vscode#141292]
Most bitmap image editors, such as [Paintbrush](https://paintbrush.sourceforge.io/), use a checkered grid for transparency that matches the image size regardless of zoom:

![Paintbrush transparent image](https://user-images.githubusercontent.com/24855774/150813128-e57dfea1-da4a-4c3c-bb28-7ba96f53cabf.png)

However, when zooming in on VS Code, the grid changes:

![VS Code transparent image](https://user-images.githubusercontent.com/24855774/150813343-6f1e5120-73ed-47df-b393-8995c15e00f0.png)

![VS Code transparent image zoomed](https://user-images.githubusercontent.com/24855774/150813425-6066f59e-87fc-4ac0-9941-96c92550ff5e.png)

Ideally, the grid would align with the image's pixels and remain the same size when zooming in.

**Comment by haykam821** [comment]
[This demo](https://jsfiddle.net/9o3gdvcr/3/) replicates Paintbrush's grid by using `transform: scale()` rather than adjusting the `width` attribute here:

https://github.com/microsoft/vscode/blob/319ee9a6af7c7b3fcb5e5877e896ed78a7052c8f/extensions/image-preview/media/main.js#L104-L105

Would VS Code match this square size or use some other size?

**Comment by roblourens** [comment]
Looks nice!
