### ISSUE TITLE
Test Marketplace interactions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#141276]
Refs: https://github.com/microsoft/vscode/issues/139015

- [x] anyOS: @isidorn 
- [ ] anyOS @karrtikr

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23141276%0A%0A&assignees=sandy081)

---

In this milestone I have refactored and optimized the gallery service that talks to the Marketplace so that the number of query requests to the Marketplace are minimized. So please play around with extension view and make sure the interactions are not broken.

- Try querying for extensions using different filters, like free text or pre-defined filters available in the viewlet
- Try installing extensions, pre-release versions or release versions is working as expected
- Make sure updates are shown and updating extensions are working as expected. (You can trigger an auto update by going to the extension installed location using command `Open Extensions Folder` and change the version of the extension in its package.json.
- Also try installing extension from command line eg., `code-insiders --install-extension <pub.id>`

**Comment by isidorn** [comment]
All seems to work well, nice job 👏

**Comment by karrtikr** [comment]
Works nicely 👍
