### ISSUE TITLE
The folding region snippet doesn't work well

### ISSUE THREAD

**Issue by torn4dom4n** [microsoft/vscode#141260]
- VS Code Version: 1.63.2
- OS Version: Windows 10 or Windows 11

Transfer problem from https://github.com/AREA44/vscode-LaTeX-support/issues/20

Step to Reproduce:
1. Type:
```cpp
#include<iostream>

using namespace std;

int main() {
	cout << "Hello World";
	return 0;
}
```

2. Moving cursor to `;` and typing something.
![image](https://user-images.githubusercontent.com/27698189/150729114-36ceb003-01b6-4c40-a9f0-10ea4a3d2e2e.png)

**Comment by aeschli** [comment]
The `#region` and `#endregion` proposals are snippets for the c and c++ . For me they only show up when I type `#`.
Do you have any snippet related settings set?

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"snippets"

**Comment by torn4dom4n** [comment]
@jrieken I can only find https://github.com/microsoft/vscode/issues/139943

**Comment by torn4dom4n** [comment]
> The `#region` and `#endregion` proposals are snippets for the c and c++ . For me they only show up when I type `#`. Do you have any snippet related settings set?

I didn't change anything in settings. It maybe a bug like this https://github.com/microsoft/vscode/issues/139943
