### ISSUE TITLE
Watches pane - "Rename expression" -> "Edit expression"

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14127]
'Rename' doesn't feel right here. I was going to make the change but don't know whether the localize ID, action name, and everything else should change to be consistent.

**Comment by isidorn** [comment]
+1 for the change.
Yeah everything should change except the ID if it is exposed in the keybindings.json. I believe this one is not so feel free to change everything.
Good old full text search should do the trick here :)
