### ISSUE TITLE
VSCode UI issues when working with Remote Desktop

### ISSUE THREAD

**Issue by kuhlaid** [microsoft/vscode#141221]
This might be more a problem with remote desktop for Window, but here goes. I am accessing a Window 10 computer via Remote Desktop. The remote machine is running VSCode with a NodeJs project. If I start the node dev server and then exit out of the Remote Desktop connection (leaving the remote machine running), when I log back into the Remote Desktop connection to go back into VSCode, I can't work with the UI. UI refresh/redraw is completely out of whack and I have to go into the Windows task bar or task manager to close VSCode because the minimize and close buttons at the top right of VSCode stop functioning.

Below is a screen cast of VSCode before I disconnect from Remote Desktop.

https://user-images.githubusercontent.com/41551429/150649892-09b83bd7-c672-480b-8491-de744b998170.mp4

When I reconnect to Remote Desktop this is a screen cast of how the UI is broken. The main menus seem to stick to the window when selecting them (sometimes worse than others), when scrolling the code window the right portion of the window scrolls but leaves the code lines on the left in place and you can see the visible break in the code window as I scroll.

https://user-images.githubusercontent.com/41551429/150650152-3968e952-a8b8-4831-9c7b-4de124b406e1.mp4

----
**Also I using the 'Report Issue' from the 'Help' menu in VS Code but when I submitted the issue I get taken to 
https://github.com/microsoft/vscode/issues/141220 with a Page Not Found message.**

![image](https://user-images.githubusercontent.com/41551429/150650141-bba96927-f88f-405a-9ab2-58a88d62a430.png)

Does this issue occur when all extensions are disabled?: Don't know

**Where is the `Command Palette`? There is no mention of it at https://code.visualstudio.com/docs/getstarted/userinterface**

Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by TheBrenny** [comment]
I'm tempted to say that this is an issue because of the resources on your destination computer. Maybe the RDP server isn't able to keep up and send all the data, or maybe it's optimization technique makes it not send parts of the screen which "haven't updated". Yes, you're updating the screen, but I'd put my bets on RDP not seeing it. Remember that there's a NodeJS server running as well, which is probably taking plenty of resources.

> Where is the Command Palette? There is no mention of it at https://code.visualstudio.com/docs/getstarted/userinterface
![image](https://user-images.githubusercontent.com/1498923/154825560-8caa77a6-1c8b-4173-996a-da343a3462ec.png)

**Comment by kuhlaid** [comment]
I'm thinking this is an app 'resizing' issue when the remote desktop connection is closed and restarted. I hadn't noticed it before but the text in VS Code 'shrinks' when I close and restart the remote desktop connection. I can correct the issue by simply clicking the app icon in the taskbar to minimize the VS Code (since the minimize button on the app is not functional at this point) and then click the taskbar icon again to show the app and the UI issues correct themselves. I am going to close this issue unless someone else sees a reason to open it.
