### ISSUE TITLE
"terminal.explorerKind": "external" setting not working on macOS

### ISSUE THREAD

**Issue by dsimanis** [microsoft/vscode#141294]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.63.2 (Universal)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0

- OS Version: macOS 12.1 Monterey

Steps to Reproduce:

1. Close  integrated terminal. 
2. Add following to User settings.json:
    "terminal.explorerKind": "external",
    "terminal.external.osxExec": "iTerm.app",
3. Restart VsCode
4. Launch terminal: Menu > Terminal > New Terminal
5. Regular integrated terminal is launched below the editor window.

**Comment by meganrogge** [comment]
> Launch terminal: Menu > Terminal > New Terminal

this will not work because always launches the integrated terminal. the explorerKind setting applies to where the terminal will launch when a file is right clicked on in the explorer -> Open in terminal.

**Comment by meganrogge** [comment]
![Uploading Recording 2022-01-26 at 17.26.03.gif…]()

**Comment by meganrogge** [comment]
This setting description could use more details
![Screen Shot 2022-01-26 at 5 26 57 PM](https://user-images.githubusercontent.com/29464607/151264075-26ec119a-8b10-498f-89e4-5643b5c6e3a5.png)
