### ISSUE TITLE
Toggle specific terminal

### ISSUE THREAD

**Issue by allefeld** [microsoft/vscode#141233]
My extension has both a dedicated terminal for its output and a status bar item. I would like clicking on the status bar item to result in a toggling of the dedicated terminal:

- If the dedicated terminal is visible, close the panel.
- If the dedicated terminal is not visible, make it visible.

The dedicated terminal being "visible" means:
- The panel is open,
- within it, the "Terminal"  tab is selected, and
- within that, the dedicated terminal is selected.

The `Terminal` object has methods `show` and `hide`, which correspond to the two things to do if the dedicated terminal is visible or is not visible. However, it does not seem to be possible to determine whether a specific terminal is visible or not.

I looked into `window.activeTerminal` and `window.onDidChangeActiveTerminal`, but apparently a terminal being "active" only means that it is selected among several terminals; it does not reflect whether the panel is open or the "Terminal" tab is selected.

My feature request is to implement a `Terminal` method `isVisible` which indicates visibility as explained above.

**Comment by meganrogge** [comment]
what's your use case?

**Comment by Tyriar** [comment]
It's not perfect, but you can mostly accomplish this right now by doing something like:

```ts
if (window.activeTerminal === myTerminal) {
  executeCommand('workbench.action.terminal.toggleTerminal');
} else {
  myTerminal.show();
}
```

**Comment by allefeld** [comment]
@Tyriar, thanks, that makes sense.

However, I don't seem to be able to make it work. I created a function with your code, registered a command for it, and attached that command to the status bar item. Switching to my terminal when something else is open works (`myTerminal.show`). But, when the if condition is true and `executeCommand` is run, nothing happens.

I thought I might have made a typo, but then I copied the command name from a custom keybinding I have (which does work), so that can't be it.

I appended `.then((value) => console.log(value))`, which prints `undefined` – I don't know if this is the expected return value?

I also attached `workbench.action.terminal.toggleTerminal` directly to the status bar item:

	status = vscode.window.createStatusBarItem();
	status.text = `$(whitespace)`; // I use this icon to identify my extension
	status.command = 'workbench.action.terminal.toggleTerminal';
	status.show();

Then nothing happens when I click the status bar item.

I have no idea what the problem might be. Do you?

**Comment by allefeld** [comment]
When I execute my registered command from the command palette, it works ... most of the time.
But never when executed from the status bar item.

**Comment by Tyriar** [comment]
Oh, this is because `toggleTerminal` changed a while back to focus instead of toggle if the panel isn't focused. You could experiment with using `workbench.action.togglePanel` instead which will always show/hide it regardless of where focus is. Maybe this?

```
if (window.activeTerminal === myTerminal) {
  executeCommand('workbench.action.togglePanel');
} else {
  myTerminal.show();
}
```

This would fall apart if the terminal moves to another view though (eg. drag to the right side panel).

**Comment by allefeld** [comment]
Thanks, but I'm afraid not. It works as long as the terminal is already selected in the panel. But if the panel shows e.g. "Output" but the panel is hidden, this just shows the panel but stays on "Output".

My impression is there simply isn't enough in the API to make this happen.

Unless there were another way to work around the focus issue. If I understand correctly, the problem is that activating the command palette takes the focus away, but clicking on the status bar item does not? Is there a way to take the focus away in the second case, too?
