### ISSUE TITLE
Terminal View Has Poor Visual Feedback To Indicate That It Has Focus

### ISSUE THREAD

**Issue by oscarrutt** [microsoft/vscode#141226]
Issue Type: <b>Feature Request</b>

The visual feedback of whether the terminal view has focus is poor. The only indication is if the cursor is blinking (if one has chosen a blinking cursor) and if the cursor happens to be visible. One often thinks he or she is typing in the code pane when the typing is actually in the terminal pane and vice versa. The terminal pane should have some easily noticeable visual feedback when it has focus such as a colored bounding rectangle.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 15.6.0
Restricted Mode: No

**Comment by meganrogge** [comment]
you can set your theme to high contrast and then it does
![Recording 2022-01-26 at 16 20 18](https://user-images.githubusercontent.com/29464607/151256728-71a4aedf-6def-4f15-9328-3fac12b183a0.gif)

**Comment by oscarrutt** [comment]
meganrogge, I'm sorry but I don't see from your screen shot what features besides a blinking cursor make indicate that the terminal pane has focus. The terminal has a box drawn around it but the box does not change appearance when the terminal has or does not have focus. And changing the theme to solve the problem probably won't change this behavior and in any case is impractical.

**Comment by meganrogge** [comment]
there's an orange border around the active terminal as you can see in my gif.

**Comment by oscarrutt** [comment]
Hmmm.... There is no decoration like this on my computer. Is there a setting for this to make it more visible?

**Comment by meganrogge** [comment]
you could also set 	`"workbench.colorCustomizations": {"terminalCursor.foreground": "#ff0000"}` to make the cursor more noticeable

**Comment by meganrogge** [comment]
> Hmmm.... There is no decoration like this on my computer. Is there a setting for this to make it more visible?

All I did was change the theme to High Contrast

**Comment by meganrogge** [comment]
I'm trying to find the color customization key for that border now so that you could keep whatever theme you have and use that

**Comment by oscarrutt** [comment]
Thank you. High contrast theme hurts my soul.

**Comment by meganrogge** [comment]
It doesn't look like there's a way to set that

**Comment by oscarrutt** [comment]
> I'm trying to find the color customization key for that border now so that you could keep whatever theme you have and use that

I tried terminal.tab.activeBorder but it didn't seem to have any effect.

**Comment by oscarrutt** [comment]
> This feature request is now a candidate for our backlog.

Since it is now a feature request, I will mention that the orange border that appears in the High Contrast theme, despite its orangeness, is a little subtle. Perhaps a thicker line or a box that extends around the pane would be better.

**Comment by meganrogge** [comment]
>I tried terminal.tab.activeBorder but it didn't seem to have any effect.

![Screen Shot 2022-01-26 at 5 21 57 PM](https://user-images.githubusercontent.com/29464607/151263603-9c58e315-25be-4ec6-b403-7ab77b06c5ee.png)

**Comment by oscarrutt** [comment]
Oh.
