### ISSUE TITLE
toggleMaximizedPanel eats part of the first line of integrated terminal

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#14122]
- VSCode Version: 1.7-Insiders
- OS Version: macOS

Steps to Reproduce:
1. Toggle Integrated Terminal
2. Toggle Maximized Panel multiple times

![screen shot 2016-10-20 at 2 20 50 pm](https://cloud.githubusercontent.com/assets/876920/19578425/6e2059aa-96d0-11e6-9a38-d787c30f7944.png)

**Comment by Tyriar** [comment]
Should be fixed with https://github.com/Microsoft/vscode/issues/14479
