### ISSUE TITLE
Laggy scrolling

### ISSUE THREAD

**Issue by guillaumepaulhe** [microsoft/vscode#141244]
Issue Type: <b>Performance Issue</b>

When toggling "Background Application Max Frame Rate" in the NVIDIA control pannel the scrolling in VSCode becomes laggy.

In order to fix it I need to set a program setting for VScode in the NVIDIA control pannel and disable "Background Application Max Frame Rate" only for VSCode

(Windows 11 build 22000.438)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 4092)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.96GB free)|
|Process Argv|--crash-reporter-id 32729dc5-d93d-4e30-ad4a-8a777345e47d|
|Screen Reader|no|
|VM|29%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    88	 12344	code main
    0	   143	  6676	   window (● New Text Document.txt - Visual Studio Code)
    0	    89	  8484	   shared-process
    0	    68	 11892	     ptyHost
    0	   127	  9044	   extensionHost
    0	    37	 12960	   utility-network-service
    0	    80	 18008	   issue-reporter
    0	    94	 18332	   gpu-process
    0	    26	 19072	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.0
doxdocgen|csc|1.3.2
prettier-vscode|esb|9.1.0
vscode-pull-request-github|Git|0.34.3
better-cpp-syntax|jef|1.15.10
vscode-docker|ms-|1.19.0
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
LiveServer|rit|5.7.3
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30424895
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710cf:30416617
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by deepak1556** [comment]
Closing as issue is in runtime and hard to repro without specific hardware setup.
