### ISSUE TITLE
Test syncing user tasks

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#141275]
Refs: https://github.com/microsoft/vscode/issues/91011

- [x] anyOS @alexr00 
- [x] anyOS @bamurtaugh

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23141275%0A%0A&assignees=sandy081)

---

You can now sync user tasks using settings sync. Please test this feature.

- Create user tasks from one machine and make sure that these tasks are synced on other machines
- Test turning on settings sync on a fresh device and make sure tasks are synced
- Try to introduce conflicts in user tasks between two machines and resolve them during sync. 
  - To introduce conflicts you can turn off sync on one machine and change the tasks in both machines with different content.
  - Turn off sync on the machine and you shall the conflicts
- Open Sync Activity (Remote) view using the command `Settings Sync: Show Synced Data` and test the tasks sync activity.
- Try out and test any other scenarios you think of

**Comment by alexr00** [comment]
Blocked on https://github.com/microsoft/vscode/issues/141393

**Comment by bamurtaugh** [comment]
Got to step 3 where I tried introducing a conflict and merging changes, but cannot see if it worked since I'm also now blocked by https://github.com/microsoft/vscode/issues/141393.

**Comment by alexr00** [comment]
Works well!
