### ISSUE TITLE
Feature Request: Drag and drop Watch variables 

### ISSUE THREAD

**Issue by salfej** [Microsoft/vscode#14125]
I'm getting used to the debugger and it's been really helpful, but it can be difficult to manage at times. I thought giving users the ability to re-order watch items would be nice. 

![image](https://cloud.githubusercontent.com/assets/10404888/19580432/cc0385a4-96eb-11e6-98ba-edfe358b5dd0.png)

Sometimes I'm watching variables that have similar names but are from different files. It can get a little confusing when there's several watch variables from different locations. I'll put dummy variables between them as dividers to remind me which file they came from.

![image](https://cloud.githubusercontent.com/assets/10404888/19580577/cd12d232-96ec-11e6-9d23-13e361719451.png)

Being able to do these sorts of things quickly would be awesome. Currently I have to delete and rebuild the entire watch list if I feel the need to re-order or add something in an ordered fashion.

**Comment by roblourens** [comment]
Drag to reorder would be pretty easy. Surprisingly you can't even do that in chrome devtools.

I'm not sure about dividers. Seems very specific to a certain workflow. It would be interesting if the watches that have values, ie don't throw ReferenceError, were sorted to the top, as an alternative to a user-ordered list.

**Comment by isidorn** [comment]
I like the drag to reorder idea, assigning to November to investigate
