### ISSUE TITLE
Following links: alt-click ❌ ctrl-click ✔️

### ISSUE THREAD

**Issue by woctezuma** [microsoft/vscode#141238]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows_NT x64 10.0.19044
```
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```
Steps to Reproduce:

1. `<Ctrl+N>` to have a "New File".
2. Write a URL, e.g. `https://www.google.com`.
3. Try `alt-click` to follow the link.

![Alt click](https://i.ibb.co/3kLQwNH/2022-01-23-12-44-54.png)

4. ❌ The window is resized instead of opening the web-browser.

![Resized window](https://i.ibb.co/1ZRJzyB/2022-01-23-12-46-07.png)

5. Switch the setting in `Selection > Switch to Alt+Click for Multi-Cursor`.

![Setting](https://i.ibb.co/cXJcf8B/2022-01-23-12-46-36.png)

6. Try `ctrl-click` to follow the link.

![Ctrl Click](https://i.ibb.co/sF9mQFs/2022-01-23-12-48-12.png)

7. ✔️ The web browser is opened as expected.

8. Switch the setting in `Selection > Switch to Ctrl+Click for Multi-Cursor`.

![Setting bis](https://i.ibb.co/kXMRDPV/2022-01-23-12-51-42.png)

9. The issue described at steps 3 and 4 is still present.

Loosely related issues:
- https://github.com/Microsoft/vscode/issues/36683

**Comment by alexdima** [comment]
> ❌ The window is resized instead of opening the web-browser.

I cannot reproduce this on Windows. It looks to me that you might have installed a lot of software that customizes how Windows behaves. Is perhaps some of the software you installed interfering with `alt + click` ? i.e. Are you able to use `alt + click` in other applications on this computer?

**Comment by woctezuma** [comment]
Sorry, you are right! The culprit was [`AltDrag`](https://github.com/stefansundin/altdrag)!
