### ISSUE TITLE
v 1.63 com bug

### ISSUE THREAD

**Issue by dmoraes1986** [microsoft/vscode#141277]
Prezados, eu e meus amigos de empresa temos problemas com a versão 1.63 do VS Code, quando clonamos uma pasta git para nossa máquina e iniciamos o terraform, dá tela azul e reinicia o pc. Isso vem acontecendo sistematicamente com pelo menos 10 pessoas e estamos utilizando uma versão mais antiga para conseguir trabalhar.

**Comment by joaomoreno** [comment]
> e iniciamos o terraform

Será mais um problema com Terraform, dado que o crash acontece apenas quando inicia o terraform?

**Comment by dmoraes1986** [comment]
João,  Se fosse um problema do Terraform teria que ocorrer em qualquer uma versão do VS, acredito eu. Enviado do Email para Windows De: João MorenoEnviado:segunda-feira, 24 de janeiro de 2022 10:59Para: microsoft/vscodeCc:dmoraes1986; AuthorAssunto: Re: [microsoft/vscode] v 1.63 com bug (Issue #141277) e iniciamos o terraformSerá mais um problema com Terraform, dado que o crash acontece apenas quando inicia o terraform?—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***> 
Esta mensagem pode conter informação confidencial ou privilegiada, sendo seu sigilo protegido por lei. Se você não for o destinatário ou a pessoa autorizada a receber esta mensagem, não pode usar, copiar ou divulgar as informações nela contidas ou tomar qualquer ação baseada nessas informações. Se você recebeu esta mensagem por engano, por favor, avise imediatamente ao remetente, respondendo o e-mail e em seguida apague-a. Agradecemos sua cooperação.

**Comment by joaomoreno** [comment]
Pode enviar uma gravação para eu ver melhor?
