### ISSUE TITLE
Change branch for multiple repositories in workspace not finding common branches.

### ISSUE THREAD

**Issue by tacosontitan** [microsoft/vscode#141243]
### Version Information:
![image](https://user-images.githubusercontent.com/65432314/150689094-2cdbb13a-bf21-4e7e-a6df-998c4d890b0d.png)

### Steps to Reproduce:
I have a workspace containing about 8 different repositories that I actively work in on a daily basis. Recently I decided to investigate the other areas in the source control tab and as I was investigating the "branches" area, I noticed the "switch to another branch" button:

[![enter image description here][3]][3]

This was in the area that typically works across all repositories in the workspace, so I got really excited because I loathe changing and creating branches one at a time. I clicked it and was presented with a drop-down of repositories containing checkboxes next to them:

[![enter image description here][4]][4]

<sub>I'm unable to take a screenshot of the full drop-down due to highly specific project names.</sub>

[![enter image description here][5]][5]

So I chose some repositories and clicked okay to be presented with a list of no branches:

[![enter image description here][6]][6]

However, I know for a fact all of my repositories have about 5 branches in common. Moreover, the create branch button doesn't have those checkboxes, so I wonder if this is a bug, or if I just don't know how to use it yet, and I'm having trouble finding documentation on it.

  [1]: https://i.stack.imgur.com/40OLA.png
  [2]: https://i.stack.imgur.com/eKW2C.png
  [3]: https://i.stack.imgur.com/HMBkF.png
  [4]: https://i.stack.imgur.com/IA1cb.png
  [5]: https://i.stack.imgur.com/zU4sZ.png
  [6]: https://i.stack.imgur.com/APSpv.png

**Comment by gjsjohnmurray** [comment]
Those features come from an extension, not from the core product. Maybe GitLens?

Please report the issue to the extension developer.

/causedByExtension
