### ISSUE TITLE
Test new cell fold/collapse features

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#141222]
Refs: #132690

- [x] macOS @kieferrm
- [x] linux @rzhao271
- [x] windows @joaomoreno

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23141222%0A%0A&assignees=roblourens)

---

Open any notebook using any notebook provider. For example, install the "Github Issue Notebooks" extension and open one of the *.github-issues files in the vscode repo.

- Make sure you have `"notebook.cellFocusIndicator": "gutter"` (the default)
- You should now be able to click the blue bar to collapse the cell input or output
- The collapsing feature existed before via double-clicking or the context menu, the blue bar behavior is new
- When the cell has output, the blue bar is split and clicking the top half should just collapse the input, the bottom half should just collapse the output
- Try different notebook layout settings and make sure that the bar still appears and works correctly
- It also works to collapse markdown cells and doesn't appear split

---

- When you fold a markdown cell (by clicking the chevron), text like "X cells hidden..." appears
- Try with different notebook layout settings and make sure that the layout appears correct, e.g. that text is not overflowing onto the next cell

Note that "collapsing" in the first item is different from "folding" in the second. Code and Markdown cells can be collapsed, and this just reduces their height to about one line. Folding folds hierarchical groups of markdown cells.

Known issues
- Fold/unfolding a markdown cell can sometimes produce flickering in markdown cells below
- The `...` will become clickable to expand the folded region

**Comment by joaomoreno** [comment]
All I got is nitpicking.

It's hard to click the indicator, especially if the only open file is the notebook itself: the indicator is right next to the window's resizeable border.

---

I found the style of a collapsed Markdown cell very confusing: it just looks like an uncolored version of a Markdown cell in edit mode... but double clicking it does nothing.

![image](https://user-images.githubusercontent.com/22350/150983401-8be088ee-14bc-40e1-b483-b5fe7244593b.png)

![image](https://user-images.githubusercontent.com/22350/150983421-d294c5dd-55cb-4b5c-ab2d-5a00b4eeec8f.png)

---

I find the `1 cell hidden...` indicator strange. I'm not sure the `...` is conveying anything there. At best, let's use an ellipsis `…`.

![image](https://user-images.githubusercontent.com/22350/150983000-03dffcb2-bc08-470b-b564-0b2df103f3e4.png)
