### ISSUE TITLE
 VS Code Server for WSL closed unexpectedly.

### ISSUE THREAD

**Issue by prakashsellathurai** [microsoft/vscode#141211]
Issue Type: <b>Bug</b>

i tried to access a folder inside wsl via vscode, it crashes

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Fetching remote diagnostics for 'WSL: Ubuntu' failed: VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.37GB free)|
|Process Argv|--crash-reporter-id 956c2bb8-6d46-4698-9eb4-a9fdd55f51a5|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu' failed: VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30424895
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710:30416614
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by fujinjun** [comment]
solved by update the remote extension version of vscode in windows

**Comment by aeschli** [comment]
@prakashsellathurai Do you still see the issue with the latest version of VS Code and Remote-WSL?

**Comment by prakashsellathurai** [comment]
The issue was resolved by restarting vscode in windows and updating the extension.
