### ISSUE TITLE
[less] Errors with multiple @import modes 

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode#14121]
- VSCode Version: 1.6.1 + 1.7.0
- OS Version: Windows 10

``` less
@import (optional, reference) "test.less";
```

![image](https://cloud.githubusercontent.com/assets/7034281/19576930/ae8032a2-971d-11e6-8d13-13189cced9b0.png)

Proof: [less2css](http://less2css.org/#%7B%22less%22%3A%22%40import%20%28optional%2C%20reference%29%20%5C%22test.less%5C%22%3B%5Cn%22%7D)

**Comment by Z3roCoder** [comment]
@aeschli As the change seems fixed, and you closed my issue due to a duplicate, when might it get rolled out?

**Comment by aeschli** [comment]
It's part of the [November iteration](https://github.com/Microsoft/vscode/issues/15099).
You try the fix already in the [insider build](https://vscode-builds.azurewebsites.net/insider).

**Comment by mrmlnc** [comment]
@aeschli, It seems like something went wrong :octocat: 

![image](https://cloud.githubusercontent.com/assets/7034281/20574099/fb21035a-b1c3-11e6-9d02-9ab763700c62.png)

**Comment by aeschli** [comment]
@mrmlnc Thanks, the VSCode didn't use the latest css language service. Now it's in, please try again tomorrow.
