### ISSUE TITLE
VS Code Terminal Won't Map Option Key to Meta on OS X

### ISSUE THREAD

**Issue by currenthandle** [microsoft/vscode#141250]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: OS X 10.15.7
- iTerm2: Build 3.4.12
- Terminal: Version 2.10 (433)

Steps to Reproduce:

The `"terminal.integrated.macOptionIsMeta": true`setting is not working on my system (https://code.visualstudio.com/updates/v1_20#_option-as-meta-on-macos).

I made this same change to my system Terminal app and iTerm2. iTerm is the only one that works. In iTerm the option key is mapped to Meta but not in the VS Code terminal or Terminal.

`settings.json`
```
{
  "editor.tabSize": 2,
  "window.zoomLevel": 1,
  "code-runner.preserveFocus": false,
  "code-runner.showExecutionMessage": false,
  "code-runner.saveAllFilesBeforeRun": true,
  "code-runner.runInTerminal": true,
  "editor.formatOnPaste": true,
  "editor.formatOnSave": true,
  "js/ts.implicitProjectConfig.experimentalDecorators": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[prisma]": {
    "editor.defaultFormatter": "Prisma.prisma"
  },
  "javascript.updateImportsOnFileMove.enabled": "always",
  "workbench.iconTheme": "vscode-icons",
  "vim.easymotion": true,
  "vim.incsearch": true,
  "vim.useSystemClipboard": true,
  "vim.useCtrlKeys": true,
  "vim.hlsearch": true,
  "vim.insertModeKeyBindings": [
    {
      "before": ["j", "j"],
      "after": ["<Esc>"]
    }
  ],
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["<leader>", "d"],
      "after": ["d", "d"]
    },
    {
      "before": ["<C-n>"],
      "commands": [":nohl"]
    }
  ],
  "vim.leader": "<space>",
  "vim.handleKeys": {
    "<C-a>": false,
    "<C-f>": false
  },
  "terminal.integrated.macOptionIsMeta": true
}

```

VS Code
![Screen Shot 2022-01-23 at 2 02 08 PM](https://user-images.githubusercontent.com/10948068/150701129-8b60ddd4-cc19-4a11-a287-3fe3fbe9fdab.png)
![Screen Shot 2022-01-23 at 2 01 58 PM](https://user-images.githubusercontent.com/10948068/150701131-b27d0ec8-fbd2-44ec-9143-56201e8e7067.png)

iTerm2
![Screen Shot 2022-01-23 at 2 01 44 PM](https://user-images.githubusercontent.com/10948068/150701132-80c5b01e-1225-4a51-bd05-be2279b623ce.png)

Terminal
![Screen Shot 2022-01-23 at 2 01 20 PM](https://user-images.githubusercontent.com/10948068/150701134-0c781325-3acd-45fa-abd3-23eb5c1327c5.png)

**Comment by currenthandle** [comment]
Closing. This appears to be an issue with OS X, not VS Code.

The relationship between Option/Alt and Esc/Meta does not work well. Specifically, Option will work as Meta in an `Option+j` scenario but will not work in an `Option+Left` scenario. When using the arrow keys you must use Esc as Meta.

**Comment by micimize** [comment]
For me `terminal.integrated.macOptionIsMeta` didn't work until I switched from `ABC - Extended` to `U.S.` keyboard layout
