### ISSUE TITLE
code bug

### ISSUE THREAD

**Issue by 1bule** [microsoft/vscode#141231]
Issue Type: <b>Bug</b>

the code is not displayed during debugging

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.75GB free)|
|Process Argv|--crash-reporter-id fa62a192-1ce6-4f56-9136-b65e9d915ba9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.63.3
open-in-browser|tec|2.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30424896
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710cf:30416617
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by 1bule** [comment]
Add  some  CSS styles  to  html tags ,  which  are not  displayed  in document.

**Comment by 1bule** [comment]
sometimes  the   added  html  tags  will  not  be  displayed  in the document.  I  can be  sure  that  these  tags  and  styles  are correct  .

**Comment by weinand** [comment]
@1bule please provide reproducible steps and a screenshot where the "html tags" are missing.

**Comment by 1bule** [comment]
![Recording 2022-01-24 at 17 51 36 (1)](https://user-images.githubusercontent.com/90629588/150760784-086d5b85-e9e6-4257-b3ef-55a2788ff53f.gif)

**Comment by 1bule** [comment]
![Recording 2022-01-24 at 18 30 51](https://user-images.githubusercontent.com/90629588/150766898-b10ffae4-b1d1-4a62-9fdd-f33208623325.gif)

**Comment by 1bule** [comment]
thank you for your help

**Comment by aeschli** [comment]
@1bule For us to help, please provide a small HTML file with some code (link to it, or paste here), provide the exact steps (where do you set the breakpoint, what launch command to you invoke), and tell us what you see and what you expect.

Note that we only support debugging in the embedded JavaScript code.

**Comment by 1bule** [comment]
thank you  very much . I've solved it.
