### ISSUE TITLE
Testing Allowed Locales: unicode highlighting 

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#141228]
Does this issue occur when all extensions are disabled?: Yes/No

@hediet

I am testing the setting: `Editor > Unicode Highlight: Allowed Locales`  

I installed the [Portugese (Brazil) Language Pack](https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-pt-BR).

![ptLanguagePack](https://user-images.githubusercontent.com/31813701/150659100-e2943515-23f2-4479-9c02-1afbf374a694.jpg)

It is on the [Visual Studio Code Language Packs](https://github.com/microsoft/vscode-loc) list.

With this text in an editor:

`Português Brasileiro` the `ê` is highlighted:

![ptUnicodeHighlighting](https://user-images.githubusercontent.com/31813701/150659094-0c7e39a4-3e96-42c0-976e-3cd3b8429ac3.jpg)

But I have this setting:

![ptLocale](https://user-images.githubusercontent.com/31813701/150659105-fed2a5cd-d8c2-4f74-9ea9-22a18ff3fbc9.jpg)

But the character is still unicode highlighted.  Am I not using the setting correctly?

`en` is set as the display language.  `pt-br` is given as an option to the `Configure Display Language` command.  

[The `Adjust setting` hover command does work as expected.  Perhaps `Add character to \'Allowed Characters\' or just 'Allow Character' is a better command name.]

----------

Version: 1.64.0-insider (user setup)
Commit: 23664355e61f3fb614932a5cb16613b4d987cfb7
Date: 2022-01-21T13:25:29.978Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by hediet** [comment]
I cannot reproduce:

![image](https://user-images.githubusercontent.com/2931520/151179888-9a9120b8-79c6-46e6-a4d4-7cd49e203634.png)

Did you open an untrusted workspace? For those, by default, all non-basic-ASCII characters are highlighted, regardless of any locale settings.

**Comment by ArturoDent** [comment]
I see you have the Portugese language set as your display language.  Is that required?  I was under the impression that setting installing another locale and updating the `Allowed Locales` setting would be sufficient to eliminate unicode highlighting of those locales.

The file is in a trusted folder (named `trustedFolder`):
![trustedFolderEditor](https://user-images.githubusercontent.com/31813701/151623472-b2921001-e781-43a6-ac4e-1202cb0f11ba.jpg)

Not sure why the bottom two folders are not in bold text like the first two?

**Comment by hediet** [comment]
> Not sure why the bottom two folders are not in bold text like the first two?

I don't know either - if you like, you can open an issue for that.

>  I was under the impression that setting installing another locale and updating the Allowed Locales setting would be sufficient to eliminate unicode highlighting of those locales.

This is correct.

What does the hover show? What options do you get when clicking on "Adjust settings"?

`ê` does not seem to be a confusable character at all.
Can you try with default settings?

**Comment by ArturoDent** [comment]
On hover:

![unicodeHover](https://user-images.githubusercontent.com/31813701/152094461-85f543d5-1557-4ed3-bf38-6bc7fb82562e.gif)
![unicodePortugeseCharacterSetting](https://user-images.githubusercontent.com/31813701/152094489-e58bd631-588f-4ff0-b6ac-d1a475f12642.jpg)

The `Adjust settings` link works as expected.  BTW I got the character from this extension's README: https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-pt-BR

**Comment by ArturoDent** [comment]
" (unless you explicitly set editor.unicodeHighlight.nonBasicASCII to true" 

 I do have it set to **true**.  But setting it to false or the default will not highlight any `nonBasicASCII` characters - not just those in Portugese Brazilian.  I am not sure that is the desired behaviour in general.

But feel free to close this if that is the expected behaviour.

**Comment by hediet** [comment]
> I do have it set to true. 

Then this explains it.

> But setting it to false or the default will not highlight any nonBasicASCII characters

Please check your other settings. It should highlight for example `α`.
