### ISSUE TITLE
Test new cell execution UI hints

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#141223]
Refs: #130611

- [x] macOS @kimadeline
- [x] linux @JacksonKearl
- [x] windows @chrmarti

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23141223%0A%0A&assignees=roblourens)

---

This feature was 3 changes:

- When no executing cell is scrolled into view, the editor-level progress bar will be visible
- A "Go To Executing Cell" button has been added to the notebook toolbar, when the cell is executing
- When a cell is executing, it gets an animated 🔄 icon where it appears in the breadcrumbs and outline (enable `notebook.outline.showCodeCells` to see this)

---

- Test that these all work as expected
- The editor progress bar is hidden and shown when clicking from the notebook to another editor, back to the notebook, while a cell is still executing
- The animations never get stuck showing when a cell is not actually executing
- For 🌟 _bonus points_ 🌟 , test this with Jupyter debugging. Setup steps [here](https://github.com/microsoft/vscode/issues/131469). The animations should not animate when a cell is paused in the debugger.

**Comment by JacksonKearl** [comment]
Works well! Noticed some weird things with multiple cells running at once, I didn't realize Jupyter doesn't actually support that. But it'd be nice to have for Handy.

**Comment by kimadeline** [comment]
Looks good to me! Only noticed a couple of small details, sadly I couldn't get the debugging to work 😔
