### ISSUE TITLE
Feature Request: Make package.json "scripts" click-to-run

### ISSUE THREAD

**Issue by cdaringe** [Microsoft/vscode#14126]
feature request!

fulfill the following workflow:
- open package.json
- adjacent to anything in `scripts: { ... }`, add a little icon that I can click to run it!
- additionally, alternatively, parse the `scripts: { ... }` and add them to the launch configuration menu automatically

frequently I find myself re-creating those scripts in my launch.json... but it seems like an easy win to just make them runable by default!

**Comment by roblourens** [comment]
When you first create a launch config, we parse package.json to extract the 'main' field, and add that to a launch config. It would be interesting to try to parse the scripts fields too.

**Comment by isidorn** [comment]
We are already parsing the scripts - however we are probably not covering your corner case.
Here is a code pointer, PRs are welcome to improve this
https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension.ts#L197

**Comment by weinand** [comment]
@isidorn this is unrelated to 'debug'. I think it is more 'task' functionality.

**Comment by isidorn** [comment]
@weinand agree I misread the initial comment
fyi @dbaeumer

**Comment by koddsson** [comment]
@isidorn I was maybe going to take a crack at this and I'm trying to navigate the code. I can't find `node.ts` in the project I cloned:

![image](https://cloud.githubusercontent.com/assets/318208/26372560/48dd5cea-3ff6-11e7-9adf-041741cbbfe9.png)

Has is moved since that comment was made or do I need to clone the `vscode-node-debug` extension separately?

**Comment by isidorn** [comment]
@koddsson you need to clone the `vscode-node-debug` extension seperately. However I would check with @weinand for PR ideas as he is the owner of that repository. And he is on vacation this week so expect a slow response.

In my opinion we can always improve how we guess the `program` from the `package.json` and that code lives [here](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension.ts#L336)

**Comment by mjbvz** [comment]
We now automatically create [tasks](https://code.visualstudio.com/Docs/editor/tasks) for npm scripts. An extension would also be able to add the inline decorators described in this issue
