### ISSUE TITLE
Diagnostic hovers adding indentation with \n

### ISSUE THREAD

**Issue by joshbw** [Microsoft/vscode#14128]
- VSCode Version: 1.6.1
- OS Version: Win10 w/ anniversary update

Steps to Reproduce:
1. create a diagnostic with the message property set to text that contains newlines (\n).  For example:
   diagnostic.message = "\nSeverity: Critical\nHere are details about the Error";
2. hover over whatever code is tied to the diagnostic to show the message.  Prior to 1.6 this would appear as:

[Source]
Severity: Critical
Here are details about the error

As one would expect.  However, in 1.6 and above both Severity and "Here are the details..." will also start with a heavy indentation, as if there are a number of tabs inserted

**Comment by roblourens** [comment]
Can you share a screenshot?

**Comment by joshbw** [comment]
![devskim screenshot](https://cloud.githubusercontent.com/assets/12884476/19603906/c600b466-9767-11e6-9644-f06e1effdcf6.png)
Attached - prior to 1.6 everything was aligned in the hover.  In 1.6 the first line after each \n is heavily indented as you can see

**Comment by joshbw** [comment]
Wising up, I launched the Dev tools to capture the hover element in 1.3 (the only other install I could find that I hadn't launched in a while) and 1.6.  

In 1.3 this is the HTML for the hover:

`<div class="monaco-tokenized-source"><span class="token">[Devskim:Banned C function detected (strncpy)] </span><br><span class="token">Severity: [Imp]</span><br><span class="token"></span><br><span class="token">strncpy is dangerous, as if the source contains n or more characters, it will not null terminate destination.</span><br><span class="token"></span><br><span class="token">Fix Guidance: Use strcpy_s or strlcpy if possible. If no safe function is viable, strcpy/strncpy should be proceeded by conditional checks to verify tha that the source string will fit in the destination with a null termnator.</span></div>`

And in 1.6, with the same extension code, this is the html:

`<div class="monaco-tokenized-source"><span class="token">[Devskim:Banned C function detected (strncpy)] </span><br><span class="token">                                               Severity: [Imp]</span><br><span class="token"></span><br><span class="token">                                               strncpy is dangerous, as if the source contains n or more characters, it will not null terminate destination.</span><br><span class="token"></span><br><span class="token">                                               Fix Guidance: Use strcpy_s or strlcpy if possible. If no safe function is viable, strcpy/strncpy should be proceeded by conditional checks to verify tha that the source string will fit in the destination with a null termnator.</span></div>`

As you can see, for some reason in 1.6 the markup is adding a whole lot of spaces at the start of each span following a <br>  (also, that I apparently have a ton of typos in my text)

**Comment by joaomoreno** [comment]
Can you share a code snippet of what your extension is doing exactly?

**Comment by joshbw** [comment]
Sent you an email

**Comment by joaomoreno** [comment]
Can you just provide a link to the github repo or similar?

**Comment by joaomoreno** [comment]
Oh nevermind, just got the email.
