### ISSUE TITLE
workbench.editorAssociations  "*.{oneext}" doesn't work

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#141286]
Moving over from https://github.com/lunapaint/vscode-luna-paint/issues/129

> Thanks for the fast response. I happened to have a conflicting entry in my user settings, which for some reason won't get replaced if I use the `*.{png}` pattern in my workspace settings:
> 
> User `settings.json`:
> 
> ```json
> "workbench.editorAssociations": {
>     "*.png": "imagePreview.previewEditor"
> }
> ```
> 
> Workspace `.vscode/settings.json` which does not work:
> 
> ```json
> "workbench.editorAssociations": {
>     "*.{png}": "luna.editor"
> }
> ```
> 
> Workspace `.vscode/settings.json` which does work:
> 
> ```json
> "workbench.editorAssociations": {
>     "*.png": "luna.editor"
> }
> ```
> 
> Could you check if you can replicate this issue by adding a corresponding entry in your user (not workspace) settings? I am not sure why the culy bracket glob pattern does not work. I removed `workbench.editorAssociations` from both (user + workspace) settings and it now works without specifying any associations explicitly.

**Comment by lramos15** [comment]
It's a bit interesting what is happening here. So in the case of `*.{png}` in workbench settings and `*.png` in user settings it just picks the first one read in which is user settings. In the case of `*.png` in both settings what happens is it reads in the user setting and then the workbench setting the keys being equivalent cause the workbench setting to persist. 

My prosed solution is 
Read in workbench setting first and then user setting but don't merge user setting keys as duplicate keys should still choose workbench settings. I'll hold until after endgame to try this

**Comment by lramos15** [comment]
@carstenschwede I have fixed this. It should be in the insiders build in about a week, thanks for reporting 👍
