### ISSUE TITLE
Disable grouping of messages in Debug Console

### ISSUE THREAD

**Issue by WhiteBlackGoose** [microsoft/vscode#141218]
As far as I could find, there's no way to disable grouping by messages, what I mean is:

<img src="https://user-images.githubusercontent.com/31178401/150649591-73678c5d-9607-44a0-aac7-83397a40fc89.png" width="500">

The behaviour is observed in **C#** and **F#**, but **not in Node.Js** which also uses Debug Console.

<img src="https://user-images.githubusercontent.com/31178401/150649728-7a263323-7044-4c26-9bc3-f20aa7f3b191.png" width="300">

1) Is this the right repo to open an issue against?
2) If so, is there a way to disable it?
3) If not, I suggest a setting :)

**Comment by gjsjohnmurray** [comment]
`debug.console.collapseIdenticalLines`

**Comment by weinand** [comment]
yes, `debug.console.collapseIdenticalLines` which shows up like this in the settings UI:
<img width="799" alt="CleanShot 2022-01-22 at 22 22 56@2x" src="https://user-images.githubusercontent.com/1898161/150655909-7320fa9e-e3ab-43d6-8329-82ff823e8bfa.png">

**Comment by WhiteBlackGoose** [comment]
Thanks!

**Comment by tebeco** [comment]
thx a lot @gjsjohnmurray and @weinand 

how do you explain the fact that C++/Node were not affected for example 
but C# and F# were
* same computer
* same vscode
* same settings
* even the same folder opened with `code .` so it's not even a possibly local `.vscode/settings.json`


I mean I'm happy to have a possible idea what to look for, but the current install of vscode did not had that in user settings or local and behave differently for 2 lang on the same folder

it's disturbing a bit

**Comment by weinand** [comment]
If console output provides source information (in the following screenshot on the right hand side), then lines are only collapsed if their source is identical.  @isidorn is this correct?

<img width="969" alt="CleanShot 2022-01-23 at 17 12 03@2x" src="https://user-images.githubusercontent.com/1898161/150687518-e628c0b0-c8e9-4bc7-bee8-a3e931b077e3.png">

If a debug extension does not provide source information, then identical are always collapsed. This seems to be the case for C# and F#.

**Comment by isidorn** [comment]
@weinand that is correct, lines are only collapsed if the sources are identical. Code pointer https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/common/replModel.ts#L243
