### ISSUE TITLE
Test: vscode.dev PWA

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#141296]
Refs: https://github.com/microsoft/vscode/issues/135553

- [x] web @kimadeline
- [x] web @isidorn

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23141296%0A%0A&assignees=joaomoreno)

---

We have enabled offline access in https://insiders.vscode.dev/, which is a core part of [PWAs](https://web.dev/what-are-pwas/). Test that:

- After using https://insiders.vscode.dev/ for a minute or so, you can go offline, open https://insiders.vscode.dev/ again and basic functionality should still work, especially local file editing. Core, built-in, extensions should work. Marketplace extensions don't.
- When offline, the status bar should turn a red color and there should be a status bar item on the left indicating the offline status.

**Comment by hello-smile6** [comment]
@joaomoreno It works, at least partially. Here are some screenshots from VSCode Web on the Windows build of https://crrev.com/962708 . I used a temporary profile. If you'd like, I can provide data from the profile.
![Recording 2022-01-24 at 15 43 17](https://user-images.githubusercontent.com/73048226/150884469-141374e8-23e9-4007-97da-b81a45304129.gif)
![Recording 2022-01-24 at 15 50 47](https://user-images.githubusercontent.com/73048226/150884752-054f80e3-99c0-45ad-b578-9170fd678030.gif)

**Comment by isidorn** [comment]
@joaomoreno I have done some very basic PWA testing since this is complexity 3 and because it seems like that some features are expectedly still not working. Please let me know if you would like me to give this a more thorough test pass and I can.

**Comment by kimadeline** [comment]
Local file editing seems to be working reasonably well. At some point I managed to get in an in-between state when getting back online, with the "offline" status disappearing but the status bar still being red, and I could search for extensions in the marketplace. Sadly I haven't been able to repro it 😔
