### ISSUE TITLE
Inconsistency in showing hover panels in a notebook cell verses in a normal editor

### ISSUE THREAD

**Issue by njpipeorgan** [microsoft/vscode#141261]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.63
- OS Version: Windows 10

Steps to Reproduce:

1. Open a Python document and hover over `list` function.
2. Open a Python notebook and hover over `list` function in a code cell.
3. There is a difference that the text overflows in the notebook but it wraps in a normal editor.

No line wrap in the notebook seems to be a bug.

**In the editor:**
![image](https://user-images.githubusercontent.com/12444637/150669359-f1567ae0-a0ec-47f7-93b8-90d4f62a80cc.png)

**In the notebook:**
![image](https://user-images.githubusercontent.com/12444637/150669348-b2610512-4a6e-49e9-b92b-b01231992e0c.png)

[related](https://github.com/njpipeorgan/wolfram-language-notebook/issues/13)

**Comment by rebornix** [comment]
It's possible that the code editor in notebook thinks there is no enough space for the hover widget, I'll dig into this, thanks for your report.

**Comment by xxchan** [comment]
Hi @rebornix any updates? This problem makes hover panels in the notebook basically unreadable. 😞
