### ISSUE TITLE
`code-insiders --wait nonexistentfile` hangs after abandoning the edit (i.e. close editor without saving)

### ISSUE THREAD

**Issue by ackalker** [microsoft/vscode#141237]
Issue Type: <b>Bug</b>

Steps to reproduce:

- Start Visual Code Insiders
- From a terminal (whether inside or outside of VSCode), run the command `code-insiders --wait nonexistentfile`
- In VSCode, close the newly opened editor without inserting any text
- In the popup "Do you want to save any changes to nonexistentfile?", click "Don't Save"
- Examine the output in the terminal in which you ran `code-insiders --wait nonexistentfile`

Expected results:

- The command should finish after closing the editor, whether changes were made and saved or not

Actual results:

- After closing the editor, the command appears to hang. Pressing `Ctrl-C` returns control back to the shell.

VS Code version: Code - Insiders 1.64.0-insider (23664355e61f3fb614932a5cb16613b4d987cfb7, 2022-01-21T13:26:52.572Z)
OS version: Linux x64 5.15.16_1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3534)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.71GB (1.73GB free)|
|Process Argv|--unity-launch --crash-reporter-id 83fc0498-ebc2-45fe-b20d-f031c0c5251e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
go|gol|0.30.0
better-cpp-syntax|jef|1.15.10
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.3
jupyter|ms-|2022.1.1001614873
remote-containers|ms-|0.214.0
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.64.1
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
ruby|reb|0.28.1
cmake|twx|0.0.17
vscode-ruby|win|0.28.0

(1 theme extensions excluded)

</details>

**Comment by ackalker** [comment]
As an aside, I don't think VSCode should prompt me whether to save changes for an editor without any changes in it.

**Comment by bpasero** [comment]
Pushed a fix for this (which hopefully doesn't break other `--wait` scenarios).

> As an aside, I don't think VSCode should prompt me whether to save changes for an editor without any changes in it.

We don't, unless the editor is an "untitled editor with associated resource" as in this case.
