### ISSUE TITLE
Smoke test reading and writing user settings file

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#141274]
Refs: https://github.com/microsoft/vscode/issues/126376

- [x] mac @mjbvz 
- [x] windows @alexr00
- [x] linux @TylerLeonhardt

Complexity: 3

Authors: @bpasero @sandy081 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23141274%0A%0A&assignees=sandy081,bpasero)

---

In this milestone, we have moved all user data (settings, keybindings) read/write transactions to main process. So please test updating settings, keybindings from multiple windows and make sure they are getting updated properly.

Write a sample extension that gets activated on start up and updates a setting on activation. Install this extension (using vsix) and open multiple windows. Make sure the setting that is written is updated properly. 

Quit and reopen VS Code so that all windows open up at the same time and the extension from all windows update settings. Make sure the setting got update correctly.

**Comment by TylerLeonhardt-alt** [comment]
Things looked good!
