### ISSUE TITLE
Uploaded images for smoke-test-remote on Linux are 0kb

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#141290]
Every time I've tried to download this image on various builds it's 0kb.

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=151786&view=artifacts&pathAsName=false&type=publishedArtifacts

![image](https://user-images.githubusercontent.com/2193314/150809185-a6e889f7-1240-4daa-ab02-fa87dd50d6b2.png)

**Comment by bpasero** [comment]
@Tyriar I think the images work but at the point in time they are created, the instance is somewhat dead. For example, we see this when we probe on an element and that just hangs for 2 minutes for no real reason. I believe this is more of an issue of when the images are being created (i.e. in this broken state), vs. in general. If you can find another case on Linux that is not in this area, then it sounds like something is broken.

**Comment by Tyriar** [comment]
Can we check the image size is > 0 bytes before uploading?

**Comment by Tyriar** [comment]
Oh I see, feel free to close if it's not actionable then

**Comment by bpasero** [comment]
I verified they work for a normal run: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=152045&view=artifacts&pathAsName=false&type=publishedArtifacts
