### ISSUE TITLE
Cannot copy/paste "when" expression in keyboard shortcut editor

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#141299]
### Issue Type: <b>Bug</b>

When editing keyboard shortcuts, you cannot copy existing `when` expressions for pasting them into other keyboard shortcuts.

There's no IntelliSense, either, so you have to type the same `when` expressions over and over again.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-de|MS-|1.63.3

</details>

**Comment by sandy081** [comment]
You can edit the when column using the context menu and select and copy/paste the text now.
