### ISSUE TITLE
Find widget match status doesn't update

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#141382]
Testing #141346

* open notebook
* search for something that has matches
* erase what you typed
* widget still shows match status (? of 1 match)

https://user-images.githubusercontent.com/1794099/150958999-56663997-a1b5-4166-acf2-bd60b100e553.mov

**Comment by devinvalenciano** [comment]
I also experienced this issue on Windows - 
<img width="285" alt="image" src="https://user-images.githubusercontent.com/1389808/151091256-c83b2493-7f36-4b92-aad8-0616c501be4b.png">

**Comment by rebornix** [comment]
Fixed via 9aaf5bbe82fe263bae8ce46cdc2adc618d827cb9
