### ISSUE TITLE
Cannot set colors for side panel

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141397]
Testing #141357

I would expected themable colors for anything in the side panel but only found "sidebar" related colors.

**Comment by symmetriq** [comment]
This is a problem, because I keep my terminal on the right, and it now has to be the same color as the sidebar, and I like my terminals with a pretty dark background. I just made them both dark for now, but don't like Explorer having a dark background.

**Comment by tamuratak** [comment]
You can customize the background color with:

```json
"workbench.colorCustomizations": {
      "terminal.background": "#000000"
}
```

See:

- https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme

**Comment by symmetriq** [comment]
Perfect. Thanks @tamuratak!

**Comment by benibenj** [comment]
Closing as there has not been any ask from the community to have different colours for secondary side bar
