### ISSUE TITLE
Test: JS debug excluded callers

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#141348]
Refs: #127775

- [x] anyOS @weinand 
- [x] anyOS @hediet 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23141348%0A%0A&assignees=connor4312)

---

I added the ability to js-debug that can exclude a caller from stopping at the current call frame.

1. Have a JavaScript program that pauses in any location for any person -- on a debugger statement, breakpoint, exception, etc. Ideally a location that is called from multiple locations.
2. Once paused, right click on a stackframe in the Debug viewlet. There should be an "Exclude Caller" option in the resulting context menu.
3. Continue debugging the program. The debugger should never pause at that location when the excluded caller is anywhere in (the 50 first frames) of the stack.

Also, do some verification on the tree view:

- An "excluded callers" tree view should be displayed in the debug viewlet if there's at least one excluded callers.
- Excluded `(caller, target)` pairs should be displayed in the tree view. Inline actions allow going to the caller and target location, and removing the exclusion.
- A clear button in the view title removes excluded callers.

Known issues:

- Locations hit _very_ early in the program might still pause. This is because the excluded caller info is sent over `onDidStartDebugSession`, which fires immediately after configuration is done and when the program starts running.

**Comment by weinand** [comment]
@connor4312 I have a hard time to get this feature to work, but may be I'm missing something.

Here is a recording:

![CleanShot 2022-01-25 at 18 10 43](https://user-images.githubusercontent.com/1898161/151025626-a05b65c7-070d-4729-bf72-b0034bc01fcb.gif)

I want to exclude the breakpoint in "hello" when called from "foo".

**Comment by connor4312** [comment]
It looks like I broke this during a refactoring -- callers were only getting assigned when sessions start, not during a session. This will be fixed in the next Insiders build, please try tomorrow.

**Comment by weinand** [comment]
This still does not work in the latest Insiders (45060913204279d4ecfe0575ca69d68211fb3798) and js-debug nightly (v2022.1.2517).

**Comment by connor4312** [comment]
@weinand the nightly is working for me, however I forgot to push the version bump to the product.json which includes the fix. Can you double check that you were in fact using the nightly version, and if you so grab a `trace: true` log of a failure?

**Comment by weinand** [comment]
@connor4312 I cannot get it to work with the latest Insiders (3dda6ea7acb66ea8693032fe9631ccac629da770).
I tried on Windows and here is the trace: 
[vscode-debugadapter-8c8ba31f.json.gz](https://github.com/microsoft/vscode/files/7949654/vscode-debugadapter-8c8ba31f.json.gz)

**Comment by hediet** [comment]
I also don't get it to work (on windows):

![image](https://user-images.githubusercontent.com/2931520/151346437-072e763f-00be-4241-9920-b91762b9df12.png)

I would have expected that I wouldn't stop at this breakpoint with this callstack again.

**Comment by connor4312** [comment]
[Found the issue](https://github.com/microsoft/vscode-js-debug/commit/ffcc52591cd4c7a3a490bf7b529a99bb2659c241), it was something I happened to not hit in the files I was testing with 🤦 thanks for your patience in getting this tested. Here's a nightly vsix if you're still up and want to test this before the next Insiders/nightly: https://memes.peet.io/img/js-debug-nightly-excluded-callers.vsix

**Comment by weinand** [comment]
bingo, _what a difference a ~~day~~ word makes_ ;-)

**Comment by hediet** [comment]
Works really really nicely! Thanks!

This is one of my favorite features this month ;)
