### ISSUE TITLE
cannot load environment variable from workspace settings.json

### ISSUE THREAD

**Issue by luyu12** [microsoft/vscode#141330]
- VS Code Version:1.63.2
- OS Version:12.0.1

Steps to Reproduce:
I have the following define in the workspace settings.json
` "extensions.directory": "${env:HOME}/.vscode-extensions",`

But I'm not able to read the variable 'extesions.directory' from the other files, the error is 
`Could not create directory ${env:HOME}/.vscode-extensions`

**Comment by sandy081** [comment]
settings does not support resolving env variables

**Comment by luyu12** [comment]
Thanks! Is there any way to work around this?

**Comment by sandy081** [comment]
I assume no.
