### ISSUE TITLE
Template literal and Bracket Pair Colorizer

### ISSUE THREAD

**Issue by syzgod** [microsoft/vscode#141321]
Hello everyone!

Is it maybe possible to leave the template literal${} out of the color matching and leave them as it is. Using Monokai Pro theme and it has a nice red color for the dollar sign and the curly braces also but the Bracket Pair Colorization makes it totally indistinguishable in the code most of the cases.

Regards

**Comment by syzgod** [comment]
Can I promote this or bump it or should I just leave it  be?

**Comment by hediet** [comment]
This seems like a very narrow edge case.
Even if `${` ... `}` is not registered as pair, it would detect `{` ... `}` as pair.

So far, I have no good idea how to support your scenario, so it is unlikely this is going to happen.

**Comment by syzgod** [comment]
> This seems like a very narrow edge case. Even if `${` ... `}` is not registered as pair, it would detect `{` ... `}` as pair.
> 
> So far, I have no good idea how to support your scenario, so it is unlikely this is going to happen.

Will find a piece of JS and show the images before and after pair colorizer.
It actually needs to detect that the curly braces with the dollar sign in front means using a template literal ergo leave it untouched if they are already colorized by a theme in my case.

When I write appendHTML = `text ${...} other text ` - the backticks should be red so as the dollar sign and the curly braces as well coming from the theme. Instead with the pair colorizer the backticks are red and the dollar sign + curly braces turn to yellow(or other hard to read color) so they totally blend in with the text.
