### ISSUE TITLE
"vscode-proxy-agent" failed

### ISSUE THREAD

**Issue by assoft** [microsoft/vscode#141358]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
  - Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
  - Date: 2021-12-15T09:38:17.605Z (1 mo ago)
  - Electron: 13.5.2
  - Chromium: 91.0.4472.164
  - Node.js: 14.16.0
  - V8: 9.1.269.39-electron.0
  - OS: Darwin arm64 21.2.0
- OS Version: MacOS Monterey 12.1 - M1

Everything was normal before, but suddenly these problems appeared. And my plugins stopped working. 

Please help me!

![1](https://user-images.githubusercontent.com/835239/150916216-e943b5cc-bf1d-4989-8f69-43c9da65fc69.jpg)
![2](https://user-images.githubusercontent.com/835239/150916228-d078830d-1662-4566-a5be-ec81d829d8dd.jpg)

**Comment by assoft** [comment]
No, there is absolutely no extra command line argument!

I can't get rid of these problems even though I did a clean install.

"clean install steps":
1. ~/.vscode `removed`
2. ~/Library/Application Support/Code `removed`
3. Download VSCode Apple Silicon from https://code.visualstudio.com/download

*Despite all this, nothing has changed*

**Comment by chrmarti** [comment]
Could you unfold the first error in the log (clicking on its triangle)? We seem to be missing something. If that doesn't reveal anything new, maybe compare with the Insiders version (can be installed alongside stable): https://code.visualstudio.com/insiders/

**Comment by assoft** [comment]
I scanned almost all directories and deleted traces of vscode. I've tried Insiders, both universal and arm... but I can't seem to get rid of these errors at all.

Thank you for your attention @chrmarti!

These two screenshots were taken at your request.

![2](https://user-images.githubusercontent.com/835239/151081672-aa224a94-a5e4-46df-ae30-42f410c8942e.jpg)
![1](https://user-images.githubusercontent.com/835239/151081678-1c66464a-3e82-461f-9e5c-fcd3f9ffb8bd.jpg)

**Comment by assoft** [comment]
If I run the code from the command line with the following argument, everything returns to normal and the plugins continue to work, despite some errors;

```bash
code --trace-deprecation
```

I don't think there has been a change in my development environment. But on the other hand, if I go back to the previous versions of the code, I see that nothing has changed.

![1](https://user-images.githubusercontent.com/835239/151170473-c7602c8c-c054-4c8c-9b7d-568254fd72b7.jpg)

**Comment by chrmarti** [comment]
It looks as if the extension host was started with `--throw-deprecation`. Not sure where that might come in. Maybe check your launch.json (for extension development) and `F1` > `Preferences: Configure Runtime Arguments`.
