### ISSUE TITLE
PWA: Search not working when offline

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#141396]
Testing #141296

Search is not working in PWA, when offline

<img width="302" alt="Screenshot 2022-01-25 at 11 57 59" src="https://user-images.githubusercontent.com/1926584/150964412-5dcdf84c-bd8c-49b2-941b-50940afae2db.png">

**Comment by joaomoreno** [comment]
@isidorn Is this a GH repo?

I can't reproduce. My steps:

1. Open https://insiders.vscode.dev
2. Go offline
3. Open folder
4. Search for something. It works.

**Comment by isidorn** [comment]
Seems to work fine now, I can no longer repro. Feel free to close.
Maybe a clue why this was happening is the error "Unable to search with Web Worker text searcher"
