### ISSUE TITLE
Cannot open file in VS Code if it's already opened

### ISSUE THREAD

**Issue by andreiropotica** [Microsoft/vscode#14138]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: cmstead.jsrefactor-0.5.3, dbaeumer.jshint-0.10.15, dbalage.vscode-stylesheet-formatter-0.2.0, donjayamanne.githistory-0.1.0, donjayamanne.jquerysnippets-0.0.1, HookyQR.JSDocTagComplete-0.0.2, mohsen1.prettify-json-0.0.3, ms-vscode.jscs-0.1.9, msjsdiag.debugger-for-chrome-1.2.2, shinnn.stylelint-0.17.3, stevencl.addDocComments-0.0.8, Tyriar.sort-lines-1.1.0, waderyan.gitblame-1.3.0, wcwhitehead.bootstrap-3-snippets-0.0.7

Steps to Reproduce:

0. Have default editor for js files VS Code
1. Open a project in VS Code
2. Double click a JS file 

It won't open in VS Code, even if it's in the project that's opened.

A few versions ago it worked ok. It's usefull from source control to open a specific file.

**Comment by joaomoreno** [comment]
This was broken with a recent Windows update. Please set Visual Studio Code as the default editor for JS files again.
