### ISSUE TITLE
"Align Panel" is not in panel right click menu

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141378]
Testing #141357

Shouldn't it be there?

![image](https://user-images.githubusercontent.com/900690/150958608-393ba4a7-41b6-4052-bf10-26c7ae006e0a.png)

**Comment by sbatten** [comment]
to verify:

right click the panel title area and look for:



![Image](https://user-images.githubusercontent.com/6561887/214193336-7b95f9e0-846d-458d-9a22-7b22d399879c.png)

Test changing the values with the menu and also try the panel position menu as well.
