### ISSUE TITLE
Glitches in VSCode

### ISSUE THREAD

**Issue by sushantabrin** [microsoft/vscode#141363]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 97.0.1072.69
- OS Version: Windows 11

Steps to Reproduce:
![Screenshot 2022-01-25 142748](https://user-images.githubusercontent.com/97043022/150945128-6044ca06-0574-43c7-bd56-f3de930cf1ee.png)

1.  When I write something and switch to other apps, the interface of the vscode becomes **glitchy** as you can see in the image.
2. I don't know if that problem is specifically with VSCode or other Microsoft apps too in Windows 11.
3. Windows 10 runs it smooth and without any issues/ glitches.
4. I tried uninstalling and reinstalling it again, but seems the problem persists.

**Comment by IllusionMH** [comment]
That's problem with GPU accelerated rendeing.

In this comment update of nvidia settings helped https://github.com/microsoft/vscode/issues/115189#issuecomment-768239687

Should be also gone if you pass `--disable-gpu` CLI flag or as permanent launch setting https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by sushantabrin** [comment]
Thanks a lot, Sir. After I restored the default NVIDIA settings, the problem is now solved.
