### ISSUE TITLE
Test Unicode Highlighting - Allowed Locales

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#141338]
Refs: #138767

- [x] anyOS @deepak1556
- [x] anyOS @joaomoreno (windows)

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23141338%0A%0A&assignees=hediet)

---

## Locale Override
* Ensure neither your OS locale nor VS Code locale is Russian
* Paste the cyrillic `А` into a JS document (not in a comment)
* Observe that it gets highlighted
* Hover on it, click on adjust settings and allow common characters from the locale "ru"
* Observe that no cyrillic characters (e.g. `Х`) are highlighted anymore

## Automatic OS Locale Detection
* Remove the property `"editor.unicodeHighlight.allowedLocales"` from your settings.
* Set your OS language to Russian
* Observe that no cyrillic characters in JS documents are highlighted
 
 ## Automatic VS Code Locale Detection
* Remove the property `"editor.unicodeHighlight.allowedLocales"` from your settings.
* Ensure your OS locale is not Russian (e.g. English)
* Install the russian language pack in VS Code
* Observe that no cyrillic characters in JS documents are highlighted

**Comment by joaomoreno** [comment]
The hard part was finding my way back to setting the OS language back to English. Good job! 👏

**Comment by mihailstefanov** [comment]
'ru' is not the only Cyrillic language.
