### ISSUE TITLE
"Network status appears to be offline..." -> "Network appears to be offline..."

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#141392]
Testing #141296
"Network status appears to be offline" -> "Network appears to be offline"
"status" not needed here imho

<img width="557" alt="Screenshot 2022-01-25 at 11 46 28" src="https://user-images.githubusercontent.com/1926584/150962824-817810dd-df69-4917-8173-d6fd056e3730.png">

**Comment by joaomoreno** [comment]
![easy](https://media.giphy.com/media/NaboQwhxK3gMU/giphy.gif)

**Comment by isidorn** [comment]
exactly :D
