### ISSUE TITLE
Shell integration activated prompt shouldn't show up on reconnect

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#141345]
<img width="721" alt="Screen Shot 2022-01-24 at 4 17 03 pm" src="https://user-images.githubusercontent.com/2193314/150886899-82f5482d-3870-4e87-9c03-086ec4e6344f.png">

**Comment by hello-smile6** [comment]
@Tyriar Is one of these related?
https://github.com/microsoft/vscode/blob/b60a25439bd4dc94a014b7674732137691f290fc/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh#L83
https://github.com/microsoft/vscode/blob/f6956110f9e79d65b9616171656b13bd7f51b492/src/vs/workbench/contrib/terminal/browser/terminal.ts#L831

**Comment by Tyriar** [comment]
Opps this was a revive not a reconnect, this is as expected.

@hello-smile6 yep but it's fine, sorry 🙂
