### ISSUE TITLE
Test auto insert quote

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#141334]
Testing #18071

- [x] anyOS @paulacamargo25
- [x] anyOS @joaomoreno

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23141334%0A%0A&assignees=aeschli)

---

The auto insert quote feature adds quotes after a `=` when entering HTML properties.

Test
- that this works in editor that are in HTML language mode
- that the quick insertion only happens after a property name
- that the cursor is put between the quotes and that pressing tab brings you after the quotes
- that based on the setting `html.completion.attributeDefaultValue` single, doublequotes or no quotes are inserted
- that the feature can be turned off with `html.autoCreateQuotes`
- test that quotes are not auto inserted after undo and redo

**Comment by joaomoreno** [comment]
Lovely 👏

**Comment by paulacamargo25** [comment]
Nice feature! 👍
