### ISSUE TITLE
Test markdown path IntelliSense

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#141327]
Test for #140602

- [x] Mac @IanMatthewHuff
- [x] Linux @brettcannon
- [x] Windows @hediet

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23141327%0A%0A&assignees=mjbvz)

---

## Overview
#140602 adds IntelliSense when completing markdown paths. This includes support for:

- Completions for other sections (headers) of the current file using `#` : `[text](#header-id)`
- Completions for files and directories: `[text](./path/to/file)`
- Completions for link declarations: 

```md
[text][link]

[link]: ./path/to/file
```

## Testing
Test out the different forms of of links and make sure the completions work as expected. Cases the check

- Test the different forms of links listed above
- Test both replacement and insertion completions (use setting or hold shift to change modes)
- Test in untitled files and loose files 
- For path completions, make sure the `/` references the root of the workspace while `path` or `./path` start from the file's current directory 

Note that because quick suggestions are disabled by default in markdown, suggestions will not automatically trigger when you type `a-z` (but should trigger when you type `.` or `/`). You can always trigger suggestions using ctrl+space

**Comment by hediet** [comment]
Even this works nicely (and actually works in the preview):

![image](https://user-images.githubusercontent.com/2931520/151164151-9c6a2acc-e512-41cc-8969-610367607b4e.png)

Well done!

**Comment by IanMatthewHuff** [comment]
Sorry for the late start. I was OOF Monday / Tuesday. Jumping on this now.

**Comment by IanMatthewHuff** [comment]
Awesome, all looked good to me. I filed one issue regarding link behavior not scrolling the correct header onto screen, but I don't think that's related to this change.

**Comment by brettcannon** [comment]
Opened https://github.com/microsoft/vscode/issues/141610 for file completions including unrelated options like headings. Otherwise works great!
