### ISSUE TITLE
Pre-release labels on extensions are inconsistent 

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#141331]
## Hovers

<img width="600" src="https://user-images.githubusercontent.com/35271042/150870574-c28cc49f-ea90-4962-b9d5-a2bebb8dfe46.png">

<img width="600" src="https://user-images.githubusercontent.com/35271042/150870537-e7a932fe-0ebd-4742-a1dd-9181d2364ac5.png">

## Detail

<img width="600" src="https://user-images.githubusercontent.com/35271042/150870741-f0269517-0046-4442-93c1-507a1fbd2e1c.png">

<img width="600" src="https://user-images.githubusercontent.com/35271042/150870769-e6d51c25-19b6-48c1-8c8d-950057111265.png">

## Proposal

IMO the labels should be consistent and we should use the icon + label as much as possible:

![image](https://user-images.githubusercontent.com/35271042/150871873-a50e9b76-b83b-4930-9ac0-18476f456dca.png)

**Comment by sandy081** [comment]
@misolori I like your idea of showing the icon + label. But would like to show it next to the version as they are coupled. Also showing an addition line for a pre-release extension in the hover seems redundant to me. 

So, I just added icon to the existing label and this is how it looks:

![image](https://user-images.githubusercontent.com/10746682/151403098-8b68f827-7380-4480-97c4-5e573f9f3461.png)

![image](https://user-images.githubusercontent.com/10746682/151403394-ad8c6944-7166-4a99-a7dd-aca41b0ed3f4.png)
