### ISSUE TITLE
Test: File Nesting

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#141354]
Refs: #6328

- [x] anyOS @aeschli
- [ ] anyOS @sbatten

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23141354%0A%0A&assignees=JacksonKearl)

---

This iteration we added (experimental) support for file nesting. There are several settings to try out:

- `explorer.experimental.fileNesting.enabled`, main switch for nesting. Verify that the explorer enables/disables nesting live when toggled.
- `explorer.experimental.fileNesting.expand`, controls whether file nests get expanded by default upon expanding a folder's contents. (Note that expansion state is stored, so reopening a folder after toggling this has no effect)
- `explorer.experimental.fileNesting.patterns`, central configuration for the whole operation. Some things to verify:
  - The vscode repo has a local configuration for this, verify that works and inheritance behaves in a way you expect
  - The prebuilt patterns work as expected (for instance`*.ts => $(capture).js, $(capture).d.ts`)
  - The `addedExtension` pattern works: `* => $(capture).*`
  - `pathSegment` patterns work: `*.js => $(capture).*.js`
  - Suffix/prefix/substring patterns work, for instance: `foo-*.js => $(capture).js`, `*.js => foo-$(capture).js`, `*-foo.js => $(capture).js`, `*.js => $(capture)-foo.js`, `foo-*-bar.js => $(capture).js`, `*.js => foo-$(capture)-bar.js`, etc.
  - Anything else you can think of!

Ref https://docs.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2022 for how VS does this. Generally speaking we should be able to support anything VS does, with the exception of the generic `pathSegment` operator (`".*": {}` in VS), which we only support on a per-file extension basis: *.js => $(capture).*.js`

**Comment by marsen** [comment]
- [x] MacOS

Sorry, I don't get it,
I add these settings in settings.json(User/MyName/Library/Application Support/Code/User/settings.json), 
but it's not working, should install a special version of VSCode, or do I use the wrong setting file?
![pic](https://user-images.githubusercontent.com/4269720/150915492-8ee95e92-a017-4a7f-befe-c7f2779a159c.png)

**Comment by JacksonKearl** [comment]
@marsen this feature is only available in the Insiders release of VS Code, at https://code.visualstudio.com/insiders/

Also, `testplan-item`'s are assigned to vscode team members per policy, but that doesn't mean you can't file issues as well!

**Comment by sbatten** [comment]
I shared some feedback with @JacksonKearl offline around ideas of supporting multiple capture groups, wildcard not allowing `*` to remove ambiguity, supporting virtual folders via nesting, and removing duplicated prefixes.

**Comment by Hextar** [comment]
@JacksonKearl works as a charm on Ubuntu 21.10.

If that could help I've tested it for vue+typescript file nesting with test, snap, and stories with the following command.

```
key: *.vue
value: $(capture).test.ts, $(capture).test.ts.snap, $(capture).stories.ts
```

**Comment by marsen** [comment]
Maybe this is a different issue, but when I set Display Language as `zh-tw`
The Settings display like this, some text covered others
![截圖 2022-01-26 下午5 04 20](https://user-images.githubusercontent.com/4269720/151134681-b8ae2aa0-5561-4391-b291-c334cca078c2.png)
And I tried with `zh-cn`, it seems regular
![截圖 2022-01-26 下午5 08 00](https://user-images.githubusercontent.com/4269720/151134975-0467fe59-f985-486b-8dfa-a2659e5e955a.png)

If this is another issue, where should I report it?
