### ISSUE TITLE
Match extension icon colors to base colors

### ISSUE THREAD

**Issue by xsrvmy** [microsoft/vscode#141344]
Currently icons from extensions are displayed as a background svg file, and as a result their colors do not match with the icon's included in vscode. It would be nice to allow a way for the icons to match. There are two possible implementations that I can think of:
- Inlining the contents of the svg, so that a CSS variable can be used.
- Using the css filter property. This would require the user to specify the start and end colors so that vscode can calculate a suitable filter to use. This doesn't require extensions to change their code. However, it would have to be done per-extension.

**Comment by aeschli** [comment]
The colors of the file icons are chosen by the current file icon theme. We currently don't know what a matching color would be.
We could pick the default text color, but also that might not match the file icon theme.

I think it's up to the languages to pick a light and dark icon that is unobtrusive and goes well with most themes. Also, the idea hope that that file icon themes that will continue to adopt more and more languages. We want user to continue to file issues against file con themes if an icon doesn't look good.
File icon themes that don't want default icons to show, can turn them off in their file icon theme definition file using `showLanguageModeIcons`.

**Comment by xsrvmy** [comment]
I am refering to the editor action icons (eg. from gitlens), not file icons.

**Comment by aeschli** [comment]
Icons can also be defined in icon fonts and then the icon will get the color of the label.
That's what Gitlens does:

Usage of an icon:
https://github.com/gitkraken/vscode-gitlens/blob/972cff4ac668a6af794995436e70d55454c5f855/package.json#L6644

Definition of the icon.
https://github.com/gitkraken/vscode-gitlens/blob/972cff4ac668a6af794995436e70d55454c5f855/package.json#L6725

That solves the problem. no?
