### ISSUE TITLE
Resources lost their authority part

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#141328]
Ubuntu 21.01

- Run the code server, open the web UI and open a folder with a `package.json`
- open the `package.json` in the editor
- in the integrated terminal add a new dependency with `yarn add -D @vscode/web-custom-data`
- the command runs successfully, but the editor does not update
- Switch editors back and forth to see the change
- Set the log level to trace and observe the remote server log: the file watcher reports the content change

**Comment by bpasero** [comment]
In my testing I see the editor resource no longer having the `localhost:...` part but the file events do contain the `localhost:` part and thus we fail to compare the URIs.

**Comment by alexdima** [comment]
We think this might be caused by the `folder` query parameter simplification.

**Comment by bpasero** [comment]
👏  for finding this.
