### ISSUE TITLE
Settings editor update flaw

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#141301]
### Issue Type: <b>Bug</b>

Some of the input elements in the visual Settings editor don't update their values as expected:

![Settings drop-down box flaw](https://user-images.githubusercontent.com/9283914/150825899-6d943f2e-9be1-4bcd-846c-9feb55c98550.gif)

<br/>

![Settings editor flaw](https://user-images.githubusercontent.com/9283914/150831311-9d2df8d6-0a92-4c42-a3ed-82bd36d88b2b.gif)

<br/>

![Settings editor flaw - 2](https://user-images.githubusercontent.com/9283914/150846792-20861d68-fc16-4c03-b335-0d50f81b2e82.gif)

### Current Behavior

When selecting a value using a drop-down box in the visual Settings editor, the selected value isn't used by Visual Studio Code. (Probably it's being used, but the GUI doesn't reflect that.) However, when editing another setting, the previously neglected change will be processed.

When clicking a checkbox, the value isn't updated if the checkbox doesn't already have focus.

### Expected Behavior

When selecting a value using an input element in the visual Settings editor, the new value should be used and displayed immediately.

---
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-de|MS-|1.63.3

</details>

**Comment by r3m0t** [comment]
This doesn't reproduce any more. @rzhao271
