### ISSUE TITLE
Test: Terminal auto replies

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#141341]
Refs: #133524

- [x] macOS @deepak1556 
- [x] linux @gregvanl
- [x] Windows @bamurtaugh

Complexity: 2

Authors: @Tyriar, @meganrogge 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23141341%0A%0A&assignees=Tyriar,meganrogge)

---

The terminal has a new feature called auto replies that will reply automatically when a particular sequence of characters is encountered in succession. The main use case for this feature is Windows batch scripts and their annoying `Terminate batch job (Y/N)?` question they ask, despite the backing process already being killed. The reply is throttled just in case something goes wrong.

The default for the setting is:

```
  "terminal.integrated.autoReplies": {
    "Terminate batch job (Y/N)": "Y\r"
  }
```

Do some exploratory testing, try to break it, etc. Whoever is on Windows make sure to test the primary use case of ctrl+c in a batch script, also make sure you can remove the default from the setting to disable it.

**Comment by hello-smile6** [comment]
@Tyriar Just wondering, will it be possible to disable that? It could potentially have issues. For example, sending "y" in response would potentially send non-HTTP data to an HTTP server if the user was downloading a file via `telnet` and that line was at the end of the response.

**Comment by Tyriar** [comment]
@hello-smile6 you can delete the default item from the setting pretty easily to disable it completely. Maybe I'm misunderstanding but I don't think it would cause issues in the case you're talking about since `Terminate batch job (Y/N)` would have to happen first.

**Comment by hello-smile6** [comment]
> @hello-smile6 you can delete the default item from the setting pretty easily to disable it completely. Maybe I'm misunderstanding but I don't think it would cause issues in the case you're talking about since `Terminate batch job (Y/N)` would have to happen first.

Here's an example with v86.
https://copy.sh/v86/?profile=archlinux&c=mkdir%20t%3Bcd%20t%3Bmodprobe%20ne2k-pci%3Bdate%20--set%3D%27%60hwclock%60%27%3Bdhcpcd%20-w4%20eth0%3Bgit%20clone%20https%3A%2F%2Fgithub.com%2Fhello-smile6%2Fempty-repository%3Bcd%20..%3Brm%20-ri%20t%20%2F%3B
The user could accidentally add a space and `/` after a directory using `rm -ri`. By adding that entry, the user would hopefully avoid deleting everything.

**Comment by Tyriar** [comment]
@hello-smile6 this feature isn't meant to be a stop the user from deleting `/` protection, but a convenience thing to workaround a UX issue on Windows. It's just generalized so you can use it elsewhere if you want to.

**Comment by hello-smile6** [comment]
> @hello-smile6 this feature isn't meant to be a stop the user from deleting `/` protection, but a convenience thing to workaround a UX issue on Windows. It's just generalized so you can use it elsewhere if you want to.

Okay.
