### ISSUE TITLE
Offline status bar only shown in PWA not in web

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#141390]
Testing #141296

https://vscode.dev/

Turn off internet
Status bar does not show you are offline, even though you can still do quite some functionality.
The offline status bar only works in PWA. I think it should also work on the web page.

**Comment by joaomoreno** [comment]
@isidorn Make sure you're testing https://insiders.vscode.dev, not stable.

**Comment by isidorn** [comment]
Sorry about that. Now it seems to work, maybe I accidentally opened vscode.dev
