### ISSUE TITLE
A few error messages in my ts file

### ISSUE THREAD

**Issue by zh-wowtv** [Microsoft/vscode#14130]
- VSCode Version: 1.6.1
- OS Version: 10.11.6

Steps to Reproduce:

1. `git clone https://github.com/bsliran/angular2-meteor-base.git demo`
2. Open `app.component.ts`

<img width="361" alt="2016-10-21 12 22 44" src="https://cloud.githubusercontent.com/assets/18462946/19586596/1cf8c1c0-9789-11e6-91a4-98eb9d9a2d96.png">

The first error is: ` [ts] Cannot find module './app.component.html'.`

The second error is: `[ts] Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.`

After I insert to .vscode/settings.json:

```
{
  "typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib"  
}

```

The problem exists.

My tsconfig.json:

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "es6",
      "dom"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "sourceMap": true
  },
  "exclude": [
    "node_modules"
  ],
  "files": [
    "typings.d.ts"
  ],
  "compileOnSave": false,
  "angularCompilerOptions": {
    "genDir": "aot",
    "skipMetadataEmit": true
  }
}

```

I think the code itself has no problem because I can run the app without problem. But it shows the error message.

What should I do? Thanks.

**Comment by roblourens** [comment]
The tsconfig file isn't being applied to that file, because of the files entry. That's a list of the files you want to include, and it doesn't include any others, so app.component.ts is excluded. It works if I remove that.

**Comment by zh-wowtv** [comment]
@roblourens Yes, removing `files` in tsconfig.json will remove the error messages. But it causes the following error message when I run the application:

> While processing files with barbatus:typescript (for target web.browser):
>    packages/barbatus:typescript-compiler/typescript-compiler.js:254:13: Format
>    of the tsconfig is invalid: SyntaxError: Unexpected token /
>    at TypeScriptCompiler.parseConfig
>    (packages/barbatus:typescript-compiler/typescript-compiler.js:254:13)
>    at TypeScriptCompiler.processConfig
>    (packages/barbatus:typescript-compiler/typescript-compiler.js:228:32)
>    at TypeScriptCompiler.processFilesForTarget
>    (packages/barbatus:typescript-compiler/typescript-compiler.js:41:10)
>    
>    While processing files with barbatus:typescript (for target os.osx.x86_64):
>    packages/barbatus:typescript-compiler/typescript-compiler.js:254:13: Format
>    of the tsconfig is invalid: SyntaxError: Unexpected token /
>    at TypeScriptCompiler.parseConfig
>    (packages/barbatus:typescript-compiler/typescript-compiler.js:254:13)
>    at TypeScriptCompiler.processConfig
>    (packages/barbatus:typescript-compiler/typescript-compiler.js:228:32)
>    at TypeScriptCompiler.processFilesForTarget
>    (packages/barbatus:typescript-compiler/typescript-compiler.js:41:10)

**Comment by roblourens** [comment]
Did you comment out the line? Comments usually aren't allowed in JSON, and whatever tool you're using can't parse it.

**Comment by zh-wowtv** [comment]
@roblourens Yeah. That's right. It solves my issues. Thanks.
