### ISSUE TITLE
Panel arrow does not change after maximized

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141399]
Testing #141357

It stays the same:
![Recording 2022-01-25 at 12 00 52](https://user-images.githubusercontent.com/900690/150964851-7767f85f-b745-4bdd-9545-2c1ee74a3a6d.gif)

**Comment by sbatten** [comment]
also can't repro this one :(

**Comment by sbatten** [comment]
same here, the issue repros when the panel is empty (or when there is no active panel)

**Comment by sbatten** [comment]
this one is strange. the icon is controlled by a context key which is correctly updated. the same key controls the tooltip which correctly displays "Restore Panel Size". somehow the icon is disconnected but only sometimes.
