### ISSUE TITLE
Can not run decorator sample anymore

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#1413]
Windows, VS Code 0.10.4

- git clone https://github.com/Microsoft/vscode-extension-samples
- cd vscode-extension-samples
- npm run install-all
- open folder `vscode-extension-samples` in code
- run debugger (F5)
- second windows opens, but does not get any syntax coloring. After 10 seconds it shows the warning
`Plugin host did not start in 10 seconds`

This worked in 0.10.3

Note: vscode-extension-samples has a special launch.json with
`--extensionDevelopmentPath=${workspaceRoot}/decorator-sample`

**Comment by aeschli** [comment]
Same problem on Linux

**Comment by weinand** [comment]
@isidorn I've debugged this on my side and I found out that you are not sending me an attach-request. When debugging your code it looks like you are not receiving an event from @bpasero. I think this is a must fix.
