### ISSUE TITLE
Inconsistent font rendering of markdown headers in notebooks

### ISSUE THREAD

**Issue by dimitry-ishenko** [microsoft/vscode#141310]
Issue Type: <b>Bug</b>

1. Create new Jupyter notebook
2. Create Markdown cell
3. Enter in the cell:

```
This is default Markdown text.
#### Heading 4
### Heading 3
## Heading 2
# Heading 1
```

4. Observe ginormous headings.

![Screenshot from 2022-01-17 18-40-44](https://user-images.githubusercontent.com/2858291/150572482-c93314af-bfe4-4af6-b961-15273dbc5e57.png)

Extension version: 2022.1.1001614873
VS Code version: Code - Insiders 1.64.0-insider (23664355e61f3fb614932a5cb16613b4d987cfb7, 2022-01-21T13:26:52.572Z)
OS version: Linux x64 5.13.0-25-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.22GB (0.95GB free)|
|Process Argv|--unity-launch --crash-reporter-id 2273c5d1-5f55-44d1-afd8-13c81c1bf0ca|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by greazer** [comment]
This is technically a core VS Code change, so moving to that repo.

**Comment by dimitry-ishenko** [comment]
@mjbvz I am curious why you've changed this to feature request, when it's clearly a bug...

**Comment by mjbvz** [comment]
This is mostly subjective. We originally increased the header size based on user feedback and would like more feedback before making another change to it

**Comment by dimitry-ishenko** [comment]
@mjbvz so there was an issue with notebook fonts being too small. It was covered in #126294.

In Oct of 2021 @greazer had submitted PR #134550 referencing the above issue, which bumped header sizes.

Then, in Nov you had bumped them even more with commit d1f2d0a7296a4747fe1ba4c3b01633e78392b15e, while addressing a dis-related issue #105900.

And a few days later, you've increased overall font size in notebooks with commit a4ad395f23ab80d535730574c3ac82b84c779d72 which was the correct overall handling, but it had further increased the size of the headers. That commit should have also reverted the earlier ones.

So, this PR basically complements your last commit and re-balance sizes of headers relative to normal text.

**Comment by dimitry-ishenko** [comment]
Once again, to illustrate the issue:

Here are header sizes in the Markdown Preview extension compared to normal text. Notice how Heading 4 is nearly the same size as normal text.
![Screenshot from 2022-01-26 12-23-28](https://user-images.githubusercontent.com/2858291/151214768-02d65bba-71f2-4f5f-8074-41c763b5580c.png)

---

Same for Google Colab.
![Screenshot from 2022-01-26 12-27-56](https://user-images.githubusercontent.com/2858291/151215078-437bc283-a21f-4ab6-85c2-1629f53cfea3.png)

---

Same for GitHub.

This is default Markdown text.
#### Heading 4
### Heading 3
## Heading 2
# Heading 1

---

As for Notebooks, Heading 4 is quite a bit larger than normal text:

![Screenshot from 2022-01-26 12-29-28](https://user-images.githubusercontent.com/2858291/151215511-009b8366-7725-4225-933a-2c1a85f6f242.png)

**Comment by dimitry-ishenko** [comment]
@mjbvz ☝🏻

**Comment by mjbvz** [comment]
@dimitry-ishenko  Please don't ping me to get attention. As I said, we're waiting for more feedback from users

**Comment by dimitry-ishenko** [comment]
@mjbvz you didn't like me pinging you, but have you actually looked through my comments? It's been a week I have not heard back from you. If you are too busy, please reassign this issue to someone who can read through my findings and determine whether this is a feature or a bug.

**Comment by mjbvz** [comment]
Yes and as I’ve said multiple times now, we will wait for additional user feedback before changing the defaults for everyone. See https://aka.ms/vscode-issue-lifecycle
