### ISSUE TITLE
Strange behavior when opening shortcuts in Windows

### ISSUE THREAD

**Issue by EFanZh** [Microsoft/vscode#14137]
- VSCode Version: 1.6.1
- OS Version: Windows 7 32-bit (and at least partially in Windows 10 64-bit)

Steps to Reproduce:
1. Create two empty text documents (call them _A_ and _B_);
2. Create two shortcuts (call them _C_ which links to _A_, and _D_ which links to _B_);
3. Select _A_ and _B_, right click on _A_ or _B_, then select “Open with Code”;
4. _A_ and _B_ are opened normally. This is expected.
5. Select _C_ and _D_, right click on _C_ or _D_, then select “Open with Code”;
6. **Only one of _A_ and _B_ is opened while both of them should be opened.**
7. Select _A_ and _C_, right click on _A_, then select “Open with Code”;
8. **_A_ and _C_ are opened, while only _A_ should be opened since they are the same file.**
9. Select _A_ and _C_, right click on _C_, then select “Open with Code”;
10. _A_ is opened. This is expected.
11. Select _A_ and _D_, right click on _A_, then select “Open with Code”;
12. **_A_ and _D_ are opened, while both _A_ and _B_ should be opened.**
13. Select _A_ and _D_, right click on _D_, then select “Open with Code”;
14. **Only _B_ is opened, while both _A_ and _B_ should be opened.**

**Comment by bpasero** [comment]
@EFanZh still happens?

**Comment by EFanZh** [comment]
@bpasero Yes, that still happens.

**Comment by bpasero** [comment]
I do not think this is a bug in VSCode but rather how Windows decides to pass the arguments over to the launching process. For example, when I see the command line after doing "Open with Code" on the 2 shortcuts, I only see one file being passed over to VSCode.

**Comment by EFanZh** [comment]
@bpasero Besides that, sometimes VS Code opens the shortcut its self instead of the file it links to. Can this situation be solved?

![image](https://user-images.githubusercontent.com/2160692/39925792-a35f0cc0-555f-11e8-8117-2b550744f4a4.png)

**Comment by bpasero** [comment]
Unfortunately that is not possible for the same reason as https://github.com/Microsoft/vscode/issues/35085#issuecomment-332452409

**Comment by xeor** [comment]
This is quite anoying.. Is there any way this can be handled in vscode (instead of giving up on the issue).
`lnk` is in theory just a file, but maybe vscode can resolve it before it hits nodejs? So everything node cares about is the actuall file...

Creating symlinks in windows is possible, but require additional permissions, so it's not an easy workaround for keeping your files structured...
