### ISSUE TITLE
file nesting: impossible to discover nested files if icon theme hides folder arrows

### ISSUE THREAD

**Issue by yume-chan** [microsoft/vscode#141359]
Issue Type: <b>Bug</b>

Testing #141354

After setting `"explorer.experimental.fileNesting.enabled": true` and `"explorer.experimental.fileNesting.expand": false`, my nested files are completely hidden, and requires double-clicking the item to expand/collapse.

![image](https://user-images.githubusercontent.com/1330321/150925985-3d8d07a3-0c17-48e9-9c41-e8f5c36a2473.png)
(`stream.js` also has nested `stream.js.map`)

This is because icon themes can hide the arrow next to folders in explorer ([doc](https://code.visualstudio.com/api/extension-guides/file-icon-theme#folder-icons-in-file-icon-themes)), one example is the [vscode-icons](https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons) icon theme I'm using, which has a `vsicons.presets.hideExplorerArrows` option (and `Icons: Toggle Explorer Folder Arrows Visibility (User Level)` command).

VS Code version: Code - Insiders 1.64.0-insider (2c967bf892d52550fabae08347faae57a4539b03, 2022-01-24T05:14:33.015Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 8, 7|
|Memory (System)|32.00GB (0.40GB free)|
|Process Argv|--crash-reporter-id 4fd680f3-dbd8-413a-8c27-d5306e62c299|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-repl|ach|0.7.3
Bookmarks|ale|13.2.2
toml|be5|0.6.0
gitlens|eam|11.7.0
prettier-vscode|esb|9.1.0
copilot-nightly|Git|1.7.4731
remotehub|Git|0.22.0
rest-client|hum|0.24.6
monkey-patch|ioc|0.1.16
vscode-env|Iro|0.1.0
search-node-modules|jas|1.3.0
rust-analyzer|mat|0.3.917
csharp|ms-|1.24.0
remote-containers|ms-|0.214.0
remote-ssh|ms-|0.71.2021121615
remote-ssh-edit|ms-|0.71.2021121615
remote-wsl|ms-|0.64.2
hexeditor|ms-|1.9.3
js-debug-nightly|ms-|2022.1.2317
vscode-typescript-next|ms-|4.6.20220124
vsliveshare|ms-|1.0.5273
vscode-yaml|red|1.3.0
reveal|smu|1.2.7
workspace-config-plus|Swe|0.2.2
luna-paint|Tyr|0.12.0
vscode-icons|vsc|11.8.0
cloudmusic|YXL|9.8.1
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.13.16

</details>

**Comment by JacksonKearl** [comment]
@misolori any ideas here? I was considering some thing like using the description to show a message:
![image](https://user-images.githubusercontent.com/8586769/152604993-0839c136-9206-4b41-b509-974eb821a522.png)

Or just an icon of some sort:
![image](https://user-images.githubusercontent.com/8586769/152605089-256baf5f-1159-4254-9f14-e58416b52b29.png)


We could perhaps provide a default "nest parent" file icon and let themes customize it.

**Comment by misolori** [comment]
I think in the case where the theme has chosen to hide the chevron, that is on the theme because that is what denotes a "folder". So creating a "nested parent" option would only help in this case as i wouldn't add additional meta data on the list item.

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/152714322-832fc55a-c28d-45c1-a4f3-c1eb5becc118.png)

How about let Code place a little folder icon at bottom right of the original file icon?

Maybe file icon theme authors need to create extra simplified folder icons, or maybe it's completely impossible because they will be too small.

**Comment by zzjin** [comment]
Sub little icon sounds great! Or maybe using plus(➕) to make a difference?

**Comment by JacksonKearl** [comment]
Nest parents will now display a chevron even if folders do not.
