### ISSUE TITLE
debugging seesion being disappear in 1 second

### ISSUE THREAD

**Issue by hanzala2626** [microsoft/vscode#141361]
Issue Type: <b>Feature Request</b>

when i start to debug my code . it started processing and when it start it disapperar in a second .
i try it many time to uninstall and reinstall again and restar computer and  restart vs code too unable to solve this problem

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
What language are you coding in?

How are you launching your code?

Maybe capture a screen recording and paste it here.

/gifPlease
