### ISSUE TITLE
Editor - Bring back getModeAtPosition() semantics

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#14136]
Since we extracted HTML into an extension, getModeAtPosition always returns the top-level mode/language and not the nested one. 

TODO:
- [x] determine language based on top level scopes for each token
- [x] generate modeTransitions based on the token's language transition
- [x] somehow load embedded languages configurations
- [ ] ~~write test plan item~~

**Comment by aeschli** [comment]
Once fixed, I guess https://github.com/Microsoft/vscode/issues/11081 can be closed

**Comment by alexandrudima** [comment]
Test coverage will be done through verification of issue #11081 and all linked issues from there.
