### ISSUE TITLE
"Show Panel" misses checkbox

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141387]
Testing #141357
![Recording 2022-01-25 at 11 42 57](https://user-images.githubusercontent.com/900690/150962121-c0aa29e0-beee-457d-8c48-66aed45b3b04.gif)

**Comment by sbatten** [comment]
anything additional in terms of repro steps? does not repro for me :/

**Comment by bpasero** [comment]
I had 2 windows open at the same time side by side, maybe the one impacted the other?

**Comment by sbatten** [comment]
it seems to be caused by not having an active panel (outline is not activated). repro is easy if panel is empty
