### ISSUE TITLE
Notebook find widget shows 6 of 5

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#141368]
Testing #141346

(see attached recording)

* open my-endgame notebook
* search for your user name
* run the "Issues filed by me" query
* search in output too, go through all matches
* replace your own username with its upper case variant
* the number of matches is bogous

https://user-images.githubusercontent.com/1794099/150954536-4ae6d959-591e-4dc2-a187-3317d1c47be4.mp4

<img width="442" alt="Screen Shot 2022-01-25 at 10 51 39" src="https://user-images.githubusercontent.com/1794099/150953747-e905ef3b-cc95-431f-bf15-75fa66907b33.png">

**Comment by rebornix** [comment]
Verifier:

Follow the steps above. When searching in output is enabled and there are search results in outputs, the replace all button is disabled. The replace one button is enabled only when the current find match is a model match, you need to navigate to that match to test replacement.
