### ISSUE TITLE
Dragging a view into side panel does not open it

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141384]
Testing #141357
![Recording 2022-01-25 at 11 27 44](https://user-images.githubusercontent.com/900690/150959715-7bd8ca18-9458-4d79-8827-12ace3f24a09.gif)

**Comment by bpasero** [comment]
Same for panel actually!

**Comment by bpasero** [comment]
Is it expected that the view remains inactive when dropped?
![Recording 2022-01-26 at 08 05 58](https://user-images.githubusercontent.com/900690/151118275-bd1dd574-9c83-493f-b018-1ae07a18dc79.gif)

**Comment by sbatten** [comment]
@bpasero yes, this is allow multiple moves with minimal UI churn
