### ISSUE TITLE
Nervous progress bar atop find widget

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#141377]
Testing #141346

* open notebook
* find something
* notice a flickery progress bar atop the find widget

https://user-images.githubusercontent.com/1794099/150958404-57f6e703-d0aa-450b-8df5-d201f5e73f44.mov

**Comment by rebornix** [comment]
We should have some more timeouts for the progress bar.

**Comment by rebornix** [comment]
Added a 200 ms delay.
