### ISSUE TITLE
Hot Exit: restoring file model issues

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14132]
Feedback for https://github.com/Microsoft/vscode/commit/b23229f65dd68c594915650e0e2aed722cdaa401

The `textFileEditorModel` is now restoring the backup in its `load` method as suggested. However you are passing in the `etag` and the encoding of the file model into the `resolveContent` method of the backup. This is problematic for two reasons:
- the `etag` is used to find out if the file has been modified since but you take the wrong `etag` (from the file, not the backup)
- the encoding of the file model can be UTF-16 but I think all backups are stored as UTF-8?

**Comment by Tyriar** [comment]
@bpasero it should backup with the same encoding right? Is it fine to assume this.preferredEncoding (of the original file) is good to restore with if that's what it was backed up with, or does it need to be persisted to disk?

**Comment by bpasero** [comment]
@Tyriar I would probably not store backups with user defined encoding, but always store them in UTF-8. I am not seeing any value in retaining the picked encoding in the backup world. Since backups are 100% under our control we should pick the best encoding and that is UTF-8.

**Comment by Tyriar** [comment]
Some questions:

1. Isn't it correct that we take the `etag` from the actual file and not the backup? The backup is just a temporary buffer that is persisted to disk, we don't want to tell other classes that the model is newer than the actual file do we?
2. So I'll keep everything UTF-8 like it currently is?

**Comment by bpasero** [comment]
Yes, the `etag` must come from the file on disk and always using UTF-8 for backups should be good 👍

**Comment by bpasero** [comment]
When loading the backup, I would not even send any etag. We only use that to make sure we do not load the content again if we already have it in memory for files.
