### ISSUE TITLE
Test: New Layout State

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#141357]
Refs: #132893

- [x] anyOS @bpasero
- [x] anyOS @rchiodo

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23141357%0A%0A&assignees=sbatten)

---

This milestone, we modified how layout state is managed and stored. This should majorly be a no-op, but we want to verify there are no surprises.

Some context on the changes: We are moving away from settings to store the visual state (e.g. is the side bar visible?) Currently the now legacy setting and local storage are sync'd with each other.

Please test these 3 facets of layout state:

1) Migration: Using an old insiders build (linked below) please set up some layout state in a fresh user data directory, then try to launch the latest insiders with this build. Verify that things don't break and things are migrated.
2) Layout manipulation: The easiest way to play with the layout state in the latest build is with the new `Customize Layout...` command. Try as many combinations of changes including reloads as you can think of.
3) Multi-window: Mess with layout across multiple windows and ensure things are reasonable.

**Additional Note**
What is layout state? What should I manipulate to test for migration? Layout state is historically stored in many forms including settings and local storage. It includes many settings under `workbench` regarding part (side bar, status bar, menu bar etc) visibility, position, and size. It also cares about fullscreen, zen mode, centered layout. All these are great combos to test.

**1.63.0-insider builds**
winx64:
    win32-x64: https://az764295.vo.msecnd.net/insider/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/VSCodeSetup-x64-1.63.0-insider.exe
    win32-x64-archive: https://az764295.vo.msecnd.net/insider/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/VSCode-win32-x64-1.63.0-insider.zip
    win32-x64-user: https://az764295.vo.msecnd.net/insider/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/VSCodeUserSetup-x64-1.63.0-insider.exe
winia32:
    win32: https://az764295.vo.msecnd.net/insider/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/VSCodeSetup-ia32-1.63.0-insider.exe
    win32-archive: https://az764295.vo.msecnd.net/insider/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/VSCode-win32-ia32-1.63.0-insider.zip
    win32-user: https://az764295.vo.msecnd.net/insider/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/VSCodeUserSetup-ia32-1.63.0-insider.exe
winarm64:
    win32-arm64: https://az764295.vo.msecnd.net/insider/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/VSCodeSetup-arm64-1.63.0-insider.exe
    win32-arm64-archive: https://az764295.vo.msecnd.net/insider/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/VSCode-win32-arm64-1.63.0-insider.zip
    win32-arm64-user: https://az764295.vo.msecnd.net/insider/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/VSCodeUserSetup-arm64-1.63.0-insider.exe
macOS x64: https://az764295.vo.msecnd.net/insider/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/VSCode-darwin.zip
macOS arm64: https://az764295.vo.msecnd.net/insider/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/VSCode-darwin-arm64.zip
macOS Universal: https://az764295.vo.msecnd.net/insider/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/VSCode-darwin-universal.zip
Linux 64:
    linux-x64: https://az764295.vo.msecnd.net/insider/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/code-insider-x64-1638829168.tar.gz
    linux-deb-x64: https://az764295.vo.msecnd.net/insider/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/code-insiders_1.63.0-1638828867_amd64.deb
    linux-rpm-x64: https://az764295.vo.msecnd.net/insider/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/code-insiders-1.63.0-1638828957.el7.x86_64.rpm
    linux-snap-x64: https://az764295.vo.msecnd.net/insider/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/code-insider-x64-1638829424.snap

**Comment by bpasero** [comment]
As for migration wouldn't it make more sense to ask to use a stable VSCode and then run latest insiders over it? Wouldn't that cover what we actually want to test?

**Comment by bpasero** [comment]
Took me a bit to get used to the fact that the "Panel" can no longer move to the side and that the "Side Panel" is the replacement for that. Now I really like this model and think it is a lot easier to understand for new users, though maybe might confuse existing users. 

Anyway, good job with these layouts, I filed many issues but I think nothing critical.

**Comment by rchiodo** [comment]
Looks good to me too. The only issue that might need to be fixed (that I logged) is #141471
