### ISSUE TITLE
Notebook cell toolbar overlapping menu

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#141314]
![image](https://user-images.githubusercontent.com/641685/150847252-6473dd92-f403-4157-965d-d7020722bfb9.png)

I clicked on the `...` and the menu appeared, but as I hovered over the menu (near the cell toolbar), the cell toolbar below it would appear on top of the menu.

/cc @roblourens @rebornix

**Comment by rebornix** [comment]
@eamodio what's the `notebook.cellToolbarVisibility` setting you are using? I didn't reproduce this as I can't have two cell toolbars visible at the same time

**Comment by rebornix** [comment]
nvm, I can reproduce on Windows with it set to `hover`

**Comment by rebornix** [comment]
@sbatten we render the dropdown as child, but when the dropdown is open, and we move our hover to another cell, the toolbar on that cell will be rendered on top of the dropdown, even when they have the same zindex. Any ideas?

**Comment by sbatten** [comment]
@rebornix i assume all toolbars live on the same z-index so this means that the later one in the dom will always beat out the visible one. arguably the hover interactions shouldn't work though with the menu open. similar to what we do with the context menu (native mac behaviour)

**Comment by rebornix** [comment]
The fix here is increasing the zindex of  the toolbar with dropdown visible.

**Comment by kimadeline** [comment]
Is this Windows-specific? I cannot reproduce this issue on Mac, but my cell toolbars don't look like that.

**Comment by sbatten** [comment]
@kimadeline yes, the menu is specific to windows (or web on mac)
