### ISSUE TITLE
PWA: quick pick not finding files 

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#141394]
Testing #141296

On vscode.dev quick pick properly finds files.
If I open the same workspace in PWA quick pick does not find any files

<img width="660" alt="Screenshot 2022-01-25 at 11 54 38" src="https://user-images.githubusercontent.com/1926584/150964091-d18017f4-d5c3-4431-80db-42aaa78b14c8.png">

**Comment by joaomoreno** [comment]
Merging with https://github.com/microsoft/vscode/issues/141396
