### ISSUE TITLE
Revisit names of filter commands

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#141371]
Testing #141346

<img width="415" alt="Screen Shot 2022-01-25 at 11 11 46" src="https://user-images.githubusercontent.com/1794099/150957281-9b14e5ee-9bf7-4cf0-9ccc-7c6924fcc2f8.png">

The names seem a bit overly specific, like "Code Cell Outputs" could just be "Cell Outputs" (as in the output switcher) or "Outputs". Also "outputs" is plural while others are singular

**Comment by rebornix** [comment]
Good suggestion, `Cell Output` is a good candidate.

**Comment by rebornix** [comment]
I wonder if we should also change `Code Cell Source` to `Code Source` to align with `Markdown Source` but not sure if that would be too ambiguous.
