### ISSUE TITLE
Test: New move to side panel behavior

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#141356]
Refs: #132893

- [x] anyOS @lszomoru
- [x] anyOS @stevencl

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23141356%0A%0A&assignees=sbatten)

---

This milestone, we will enable the side panel for stable users. This comes with quite a few changes to create a coherent experience. This item is focused on the deprecation of the old "move panel to left/right" behavior. With the new side panel, from a UX perspective, the old move panel behavior is redundant and confusing. Try out the new commands, the old commands, and review the messaging.

Test:
1) The old commands `Move Panel Left|Right|Bottom`. Bind these to a shortcut to mimic an existing user of the commands.
2) The new commands `Move Views from Panel To Side Panel` and `Move Views from Side Panel to Panel`.
3) Review the notifications from the old commands.
4) In your `settings.json`, add 	`"workbench.panel.defaultLocation": "left"` and review the deprecation messaging.

**Comment by lszomoru** [comment]
@sbatten, for step 4) I have added the setting but I am not seeing any deprecation message. Am I missing something or this is a bug? If it's a bug, I will file an issue for it. Thanks!

![image](https://user-images.githubusercontent.com/3372902/150987585-8acc49d6-212e-4604-b401-14fe79d3774a.png)

**Comment by sbatten** [comment]
@lszomoru it renders in the settings editor

@roblourens do we not render deprecation in the json view?

**Comment by stevencl** [comment]
I can see the deprecation message in the json view:

![image](https://user-images.githubusercontent.com/1704059/151162098-dda193f3-86d8-493a-b0f7-5adc832385de.png)

**Comment by lszomoru** [comment]
In today's build I am also seeing the deprecation. It was not there in yesterday's build 🤷🏻‍♂️
