### ISSUE TITLE
Broken highlights in `go` files when using `raw string literal` in some cases

### ISSUE THREAD

**Issue by DimaGashko** [microsoft/vscode#141360]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.0 + https://vscode.dev as well

- OS Version: Arch Linux

Steps to Reproduce:

1. Open an empty `Go` file
2. Paste this code:
```go
package main

import (
	"fmt"
)

func main() {
	var a interface{} = []byte(`{"a": "When only 1 line it's ok."}`)
	fmt.Println(a)
	var b interface{} = []byte(`{
		"b": "But when multiple lines highlighting is broken."
	}`)
	fmt.Println(b)
	// And only one more ` will stop it...
}
```
Github highlights it correctly but here's how VS Code does it:

![image](https://user-images.githubusercontent.com/20650419/150927008-75f7bdce-27d8-4d10-a55b-1c47e78d86e9.png)

**Comment by alexr00** [comment]
Moved to the upstream repo that we get our go syntax highlighting grammar from: https://github.com/jeff-hykin/better-go-syntax/issues/33
