### ISSUE TITLE
"Rendered Markdown" disabled "Markdown Source"

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#141375]
Testing #141346

* open notebook
* find widget filters
* check "Rendered Markdown"
* :bug: the "Markdown Source" button is disabled (no matter if it was checked/unchecked before)

<img width="404" alt="Screen Shot 2022-01-25 at 11 14 45" src="https://user-images.githubusercontent.com/1794099/150957955-5b089e49-5c57-4cf3-b399-68fe072ecbae.png">
<img width="333" alt="Screen Shot 2022-01-25 at 11 14 54" src="https://user-images.githubusercontent.com/1794099/150957957-67f1a2c1-62c1-4fa0-a903-4920b488410a.png">

**Comment by rebornix** [comment]
This is intentional as we don't have a UX yet for matching both the source and the preview as we can't render both at the same time. An alternative is when clicking on "rendered markdown", we uncheck "markdown source".

**Comment by jrieken** [comment]
> matching both the source and the preview as we can't render both at the same time.

I understand that for a single cell but I can have one markdown cell in preview and another in source, right?
