### ISSUE TITLE
Tree Data Provider: Tree item actions are not screen reader compatible

### ISSUE THREAD

**Issue by mliao95** [microsoft/vscode#141329]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: Win11

Steps to Reproduce:
1. Launch a debug session in VSCode
2. Turn on Narrator
3. Use keyboard and navigate focus to the debug target
![image](https://user-images.githubusercontent.com/14304598/150866437-f59a5cf3-3436-4c17-86a0-cb48b84ae052.png)

Expected Result:
Narrator should announce all context, including action items associated with the treeitem

Actual Result:
Narrator announces just the tree item text and associated action buttons

**Comment by roblourens** [comment]
You should be able to tab to these items, and they will be announced. Does that do it for you? I don't think we normally read all the context items on each list row. That would be a lot of extra reading here.
