### ISSUE TITLE
Stuck "Turning on Setting Sync..."

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#141393]
Testing #141275

1. Setting is turned off
2. I have an missing comma in my keybindings.json
3. From the Account icon, turn on setting sync
4. Go through the sign in flow and turn on setting sync
5. An error message shows, so I looked at the logs and fixed the missing comma in keybindings.json
6. 🐛 How can I complete turning on settings sync now? I don't see a command or other way to do so:
![image](https://user-images.githubusercontent.com/38270282/150963329-40e09011-3c85-41f4-9ab7-f226b1a80555.png)

**Comment by sandy081** [comment]
Did you reloading the window?

**Comment by bamurtaugh** [comment]
I also got into this state (testing on Windows).

- Turn off Settings Sync on one machine
- Change tasks.json on both machines to introduce a conflict 
- Turn Settings Sync back on, resolve the merge conflict manually by selecting to accept remote
- Change doesn't take effect, check gear and notice I'm also stuck "Turning on Settings Sync...". I reloaded the window, but it's still in this state

![image](https://user-images.githubusercontent.com/25310137/151027687-56323ba1-9ad6-4a11-a228-a418c972d8fe.png)

**Comment by alexr00** [comment]
I also tried reloading the window, but the problem persisted.

**Comment by sandy081** [comment]
I can reproduce what @alexr00 has reported and fixed it.

@bamurtaugh I am not able to reproduce the issue you reported. Can you please file a separate issue and may be share the video with steps?

**Comment by bamurtaugh** [comment]
@sandy081 When I tested the TPI again today, I didn't end up stuck in this state, so perhaps it was a fleeting issue? If I encounter it again, I'll be sure to file an issue.
