### ISSUE TITLE
Test language default icon

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#141335]
Testing #14662

- [x] anyOS @JacksonKearl
- [x] anyOS @bpasero

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23141335%0A%0A&assignees=aeschli)

---
Language contributors can now define an icon for the language.
```jsonc
{
  "contributes": {
    "languages": [
      {
        "id": "latex",
        // ...
        "icon": {
          "light": "./icons/latex-light.png",
          "dark": "./icons/latex-dark.png"
        }
      }
  ]
```

The icon is used by file icon themes as fallback if they don't have an icon for the language. The rules are:
- the file icon theme defines at least one file icon (not just a generic icon for all files such as the `Minimal` theme)
   -> default language icons do not show in file icon themes like `Minimal` or `None`
- the file icon theme does not define a specific icon for the language
- icons defined for file extensions or file names always win against the language icon (no change)
- file icon themes can override this default behavior by defining `showLanguageModeIcons: true|false` in the theme file.
   - `showLanguageModeIcons: true` shows the default language icons even if the theme does not specify specific file icons (like the Minimal theme)
   - `showLanguageModeIcons: false` prevents that default language icons are used.

Test
- create an extension that creates a new language with an icon
- test that the built-ion set theme shows the icon, but not the `Minimal` or `None` theme
- test some other file icon themes from the Marketplace. They should show the icon unless they are simple themes like the Minimal theme
- create a file icon theme (eg. modify/copy the [Seti theme](https://github.com/microsoft/vscode/tree/main/extensions/theme-seti))
  - add `showLanguageModeIcons: false`: The default language icon should not be shown
  - define an icon for the language in the theme. That icon from the theme should show instead of the default language icon

https://code.visualstudio.com/api/extension-guides/file-icon-theme has more information on file icon themes

**Comment by bpasero** [comment]
I am not sure I was able to test the `showLanguageModeIcons` thing.

**Comment by JacksonKearl** [comment]
Very cool! 
![image](https://user-images.githubusercontent.com/8586769/151083583-dd13fc4f-b569-453b-ace3-4cb44ce8c6d9.png)

re `showLanguageModeIcons` , I found that if it's unset or false in `ayu-icons.json`, my language extension's icon gets used. If its false, then the icon theme's icon gets used. I think this is the expected behaviour.
