### ISSUE TITLE
Can not install offcial Python Extension into a container (but can install other extensions)

### ISSUE THREAD

**Issue by BIAOXYZ** [microsoft/vscode#141373]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
```console
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.5.0
```
- OS Version:

This is the OS version of the container in remote machine.
```console
root@592bb763c392:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

This is for the remote machine.
```console
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

This is local machine (A Mac where Vscode software installed)
```console
macOS Catalina
10.15.5
```

Steps to Reproduce:

0. I start a new container as usual, and first use remote ssh to connect to remote machine, then from remote machine connect to the new container.

1. I first saw this prompt message, so of course I go to the extension bar and try to install Python.
![image](https://user-images.githubusercontent.com/6740021/150955583-d5ac6f0f-95e4-40ec-ad5e-39265f5be7f4.png)

2. But it is always in `installing` state.
![image](https://user-images.githubusercontent.com/6740021/150957313-e99cf91b-36ab-41b0-96c5-cba2664f4adf.png)
The logs is like:
![image](https://user-images.githubusercontent.com/6740021/150961663-d847e9ae-5bb3-49df-a2dd-7b58a2ff8245.png)

3. I can install any other extension (compared to the above pic,  extension `Python for VSCode` has been successfully installed, but `Python` is still `installing`. because this, I believe this weird phenomenon is not due to my network...)
![image](https://user-images.githubusercontent.com/6740021/150957460-9571227b-a4d7-4ee7-b37b-8edbf6b6b876.png)

**Supplementary material**:
Is it possible due to my container name (very simple, just two numbers `22`)? But this name works before...
![image](https://user-images.githubusercontent.com/6740021/150960133-8019fded-380d-44b9-83d7-cf9040471574.png)

**Comment by sandy081** [comment]
What's happening when you click on `Install in Container buildim...` button? If it is not installing, can you please share following logs?

> F1 > Open View... > Log (Window)
> F1 > Open View... > Log (Remote)

**Comment by BIAOXYZ** [comment]
Hi @sandy081 , after I restart/reset all three (my Mac, my remote Debian, delete and re-run a new container on that Debian), now `Python` extension can be successfully installed —— and unfortunately, the bug (only `Python` extension cannot be installed but all other extensions can) cannot be reproduced at present 😅.
