### ISSUE TITLE
Markdown cells not rendered

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#141369]
Testing #141346

Sorry, no steps but it seems that a random subsection of markdown wasn't renderered. This happened after reload. I was recording with [RetroClip](https://apps.apple.com/us/app/retroclip/id1332064978?mt=12) so here is a "dump" of what happened

https://user-images.githubusercontent.com/1794099/150955246-afe92717-e215-41d9-8257-2c3ebabd242a.mp4

**Comment by mjbvz** [comment]
@jrieken Have you seen this recently? I just tried testing a few window reloads and was not able to reproduce the problem

**Comment by jrieken** [comment]
No, haven't see this lately
