### ISSUE TITLE
Notebook find filter (menu) doesn't work on Safari

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#141367]
Testing #141346

* safari
* open a notebook
* open find widget
* select the filter button
* 🐛 nothing happens

https://user-images.githubusercontent.com/1794099/150952778-2507eb04-abb6-4eea-b769-620fde901efb.mov

**Comment by rebornix** [comment]
Thanks for the testing on Safari. Didn't really see this on Desktop.

My fix for it was disabling rendering context menu as child but I'm not sure why it fails this way in Safari, cc @sbatten .

**Comment by jrieken** [comment]
I now see a menu in Safari but the commands don't really work. Like find in rendered output doesn't seem to work in Safari
