### ISSUE TITLE
Restore/View previous configuration user settings.json  (not sync related)

### ISSUE THREAD

**Issue by jhirn** [microsoft/vscode#141325]
Hello. I searched for this all over but couldn't find an existing feature or open issue. Please inform if this does exist. There are times when I like to test a new setting or group of settings and discover later they aren't preferable for a number of reasons. If I've closed or restarted my editor in that time, I do not know what the previous version of my settings were to go back to the last known working state. Normally I'd manage this by having my configuration under source control and waiting a few days to add/commit or revert things that weren't validated yet but with the way VSCode handle settings, this is a bit prohibitive (maybe not I have not actually tried. 

Is there a way to see or revert to the previous versions of settings.json? This is not relevant to sync as I'd do use that feature but still want history without the sync enabled. That said, if there's a way to accomplish this with sync history that may be enough to get me by. 

Thank you!

**Comment by sandy081** [comment]
This is enabled only with Sync - please use sync feature to restore.

**Comment by jhirn** [comment]
Ty @sandy081. I wasn't aware of this history with settings sync. It's satisfies my need in a slightly different way, but it works.
