### ISSUE TITLE
DiffEditor cannot be closed using close()

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#141326]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:
1. Create a new extension that uses the tabs proposed api
2. Open couple of files, and couple of diff editors
3. Create a command that executes `await window.tabs[0].close();`

**Expected:** Invoking the command would close each tab one by one
**Actual:** Tabs contains files get closed, but diff editors do not

**Comment by lramos15** [comment]
I was trying to support non text diffs which was messing up matches. @mattbierner or @bpasero Do you know if we have any example of non text diffs that I can use for testing?

**Comment by bpasero** [comment]
Compare 2 notebooks?

**Comment by bpasero** [comment]
Or 2 binary files / images.
