### ISSUE TITLE
Fine tune when shell integration activation message is shown

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#141483]
This will be particularly important when we enable this by default

One option:
- only show it in the first x terminals created of a particular shell

**Comment by Tyriar** [comment]
Good topic for UX sync, some other ideas:

- Dismiss by hovering the message
- Status bar entry calling out shell integration

**Comment by Tyriar** [comment]
The message is still there but is now a link to the docs with an action to flip a setting:
<img width="343" alt="Screen Shot 2022-02-04 at 2 40 21 pm" src="https://user-images.githubusercontent.com/2193314/152612822-1420ac35-d17d-428e-9716-4d5e55e650b2.png">

**Comment by Tyriar** [comment]
To verify make sure the link's hover and its links work, even when the link wraps the line in a really narrow terminal.
