### ISSUE TITLE
File nesting: Simplify the setting syntax

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#141437]
Testing #141354

I find the file nesting setting syntax not very intuitive.

- the `$(capture)` uses round brackets. We use curly brackets in placeholder in settings, launch and task configurations
- from what I understand it is always `capture`. That's quite verbose and forces the user to type a lot.

What about using `$0` and `$1` like in regular expression instead?

![image](https://user-images.githubusercontent.com/6461412/151001094-a6b26348-72ff-4a5b-980f-66ce1abf26b4.png)

**Comment by JacksonKearl** [comment]
`$0` makes good sense. The capture logic doesn't support multiple capture groups as it introduces ambiguity, so I've also considered just `$`. What do you think?

**Comment by aeschli** [comment]
You are right, `$` would be even simpler. But it would be something new.

I suggest bringing it up in slack or even a API call, maybe there are other ideas.
It would be nice to get consistency across settings.

What's the ambiguity when allowing multiple capture group?

**Comment by JacksonKearl** [comment]
Parsing `a.b.c` would be ambiguous with a `*.*` pattern, is it `(a.b).(c)` or `(a).(b.c)`. In talking with @sbatten about this we considered maybe having a capturing token that does not capture `.`, which would help to remove the ambiguity. 

One nice thing with `$(capture)` is that it ties in with our existing `$(basename)` syntax, so we could in theory support something like `*`: `$(basename).*.$(extname)`, though that's not possible at the moment.

I'll bring it up in an API call

**Comment by aeschli** [comment]
ok, I see. Wasn't aware (anymore) of the $(basename)

**Comment by adam-coster** [comment]
I'm in agreement that this is less about simplification than about simplicity related to expressiveness. With the current functionality having such limited expressiveness, a syntax change to something like `$`, as suggested, would be nice.

This feature can become increasingly valuable as the pattern becomes more expressive, so keeping `$(capture)` to leave room for extended functionality is my preference. Even the simple pattern `$(basename).*.$(extname)` that @JacksonKearl mentioned would make the file-nesting feature much more powerful for my own use cases.

This is related to the fact that the current behavior favors the *least specific* match patterns, while some use cases (like mine) prefer biasing towards the *most specific* patterns, e.g. in issues https://github.com/microsoft/vscode/issues/144814 and https://github.com/microsoft/vscode/issues/144867

**Comment by JacksonKearl** [comment]
Added `$(basename)` and `$(extname)` matching, making the use of `$(capture)` more sensible.
