### ISSUE TITLE
A11y_VisualStudioCodeLiveShare-Sep2020_Nocollaboration_SessionDetails_Keyboard: The tool tip for buttons "join and start collaboration " are not hoverable 

### ISSUE THREAD

**Issue by bbarik06** [microsoft/vscode#141401]
**GitHubTags**:#A11y_Visual Studio Code Client;#A11ySev2;#A11yTCS;#A11yMAS;#DesktopApp;#Visual Studio Code Client;#WCAG1.4.13;#MAC;#BM-VisualStudioCodeClient-MAC-Aug2021;#A11yWCAG2.1;#Keyboard;

## Environment Details:​
Application Name: Visual Studio Code

## Repro Steps:

1. Launch VS Code
2. Navigate to the “sign-in” button using tab .
3. Tab to share button and use enter key.
4. Tan to Session Details dropdown
5. Hover over the buttons "join and start collaboration"

## Actual:
On hovering over the buttons "join and start collaboration" the tooltip get displayed but on moving the pointer to the tooltip they get dismissed.

## Expected:
The pointer should move to the tooltip without the tooltip getting dismissed.

## User Impact:
Keyboard users that zoom the screen to view data will not get a chance to view the tooltip information if it dismisses before moving to it 
## Attachment
![Presentation1](https://user-images.githubusercontent.com/98393966/150969238-dd2f9762-340a-4e13-9145-25078365db66.gif)

**Comment by Tyriar** [comment]
It's a native OS hover, you're not meant to be able to hover it? @isidorn thoughts?

**Comment by isidorn** [comment]
This is just how native hovers behave. So this would need to be addressed by Edge and Chrome first. I suggest to file this issue against Microsoft Edge first. Once the browsers fix this we will also benefit.

No plans to tackle this on the VS Code side. Thus closing
For the custom hover we have a separate issue https://github.com/microsoft/vscode/issues/115034

**Comment by isidorn** [comment]
Let's reopen for `a11ymas` tracking.
We can close as duplicate in the future. Accessibility team has to improve their platform flow.
