### ISSUE TITLE
Methond explanation

### ISSUE THREAD

**Issue by Dr033** [microsoft/vscode#141457]
Issue Type: <b>Bug</b>

Hello. I'm doing training and I noticed that my trainer receives details of a method after writing it, but in my vs code it doesn't show up.
The trainer said that this feature already comes with vs code but I couldn't activate it.

My trainer:
![Screenshot_4](https://user-images.githubusercontent.com/35387000/151023074-4d472cb7-1bc9-4d68-ade8-17de096119a2.png)

Me:
![image](https://user-images.githubusercontent.com/35387000/151023227-3e1e6ce3-cb3d-4769-a3c1-244237bea105.png)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (16.46GB free)|
|Process Argv|--crash-reporter-id d9c3fdca-1753-4821-888f-575c9685f6c3|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
emulate|Die|1.6.0
es7-react-js-snippets|dsz|4.1.0
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.1.0
auto-rename-tag|for|0.1.9
code-runner|for|0.11.6
beautify|Hoo|1.5.0
vscode-pylance|ms-|2022.1.3
remote-wsl|ms-|0.63.13
material-icon-theme|PKi|4.12.1
live-sass|rit|3.0.0
LiveServer|rit|5.7.4
vscode-javascript-booster|sbu|14.0.1
tabnine-vscode|Tab|3.5.17
quokka-vscode|Wal|1.0.440
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30424896
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710:30416614
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command to investigate whether any of your extensions are preventing that feature from working.

**Comment by Dr033** [comment]
Still not  working.

**Comment by gjsjohnmurray** [comment]
Does the status bar language indicator show the correct coding language?

Your trainer's screenshot shows `fs.readFile()` and yours shows `fa.readFile()` so maybe your editor doesn't know what type `fa` is.

**Comment by Dr033** [comment]
> Does the status bar language indicator show the correct coding language?
> 
> Your trainer's screenshot shows `fs.readFile()` and yours shows `fa.readFile()` so maybe your editor doesn't know what type `fa` is.

Yes JavaScript.
I correct it after it but still not working.
