### ISSUE TITLE
Command output should be read-only, not untitled

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#141496]
Testing #141339

I feel like I would mostly open output as a "one-off" editor to inspect test failures, for example. Having the prompt whenever I want to close the editor, since it's marked as untitled, is annoying. Instead, should it be opened as an ordinary read-only file which allows the user to `Save As` if they want to keep it?

**Comment by Tyriar** [comment]
@connor4312 do you know how to do this in core? I also want to know how to do it in extensions for a similar problem in luna paint.

**Comment by connor4312** [comment]
You can register an `ITextModelContentProvider`, I do that for test output:

https://github.com/microsoft/vscode/blob/891164f3e2686c92e8c857de044807ecbf84fa66/src/vs/workbench/contrib/testing/common/testingContentProvider.ts#L20

**Comment by Tyriar** [comment]
Thanks, I'm a little surprised there's no `readonly: true` option for extensions in `openTextDocument` as it seems like a common thing people would want to do.
