### ISSUE TITLE
There is no confirmation window while drag-dropping project files in the "Explore" panel.

### ISSUE THREAD

**Issue by Egorrr** [Microsoft/vscode#1414]
Without confirmation window on drag-dropping files in the Explore panel there is a chance to accidentally move project files to another directory.

**Comment by dbaeumer** [comment]
@bpasero IMO not asking for confirmation is what I expect. Normal OS explorers behave the same. However they allow me to undo such changes. So I would expect undo in VSCode as well.

**Comment by bpasero** [comment]
:+1:

**Comment by Egorrr** [comment]
I'm not sure is its correct comparison, but for example in Jetbrains Webstorm when I drag-drop files there I see a confirmation window, which protects from accidentally moving some files from one directory to another. Otherwise, you can somehow drag files with your mouse and not even notice that.

**Comment by Matthijs-Wessels** [comment]
I have had this problem many times and even had a plugin in Visual Studio .NET that did this for me: Here's a user-voice post for this same feature: https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/11312763-ask-before-moving-files-in-solution-explorer-tree

**Comment by gaguirre** [comment]
Hi @dbaeumer, I think could be (and perhaps _should be_) different features:  
- Showing a confirmation window (with _do not ask me anymore_ option maybe)
- Undo changes in the Explore panel

Recently I had to look at "git status" and figure out which file I moved accidentally, and it's really a pain.

**Comment by jamietre** [comment]
+1, I just did this and had a [Visual Studio PTSD](https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/2206847-ask-before-moving-files-in-solution-explorer-tree) response.

**Comment by bpasero** [comment]
Fyi for July (or insiders) https://github.com/Microsoft/vscode/issues/4842 is pushed and allows to disable DND in the explorer.

**Comment by bpasero** [comment]
PR welcome.

**Comment by snhardin** [comment]
Hi! I'd like to work on this. This is something that's annoyed me for a while now.

**Comment by patwaswapnil** [comment]
Its very annoying when a folder goes (i dont even know where and what) by accident. Especially when using touchpad.

The worst thing is when working on others directory and dont know the actual structure.

**Comment by a-eid** [comment]
+1 
there should be either a confirmation dialog or an undo functionality

**Comment by KernelDeimos** [comment]
This just broke me

**Comment by andypotts** [comment]
+1

**Comment by BrennerSpear** [comment]
+1

Is there anything like cmd+Z for this?

**Comment by jfconde** [comment]
+1. It's specially painful to move node_modules, or accidentally moving your mouse and not even having an idea of what has been moved to where.

**Comment by bpasero** [comment]
I added a new setting `"explorer.confirmDragAndDrop": true` which is enabled by default and shows a confirm dialog that provides a checkbox to quickly change this setting to no longer show a confirmation:

![image](https://user-images.githubusercontent.com/900690/31277946-81f5e066-aaa3-11e7-8c8e-605a52929727.png)
