### ISSUE TITLE
runRecentCommand should deduplicate identical commands

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#141495]
Testing #141339

![image](https://user-images.githubusercontent.com/2230985/151067712-2e512041-4452-47a6-a514-5f74d6b6c7b4.png)

It's not useful to me to have the `echo` duplicated twice

**Comment by meganrogge** [comment]
We should hide duplicates when we make this change https://github.com/microsoft/vscode/issues/141006

**Comment by Tyriar** [comment]
The fact we have the output as well complicates this a little, but yeah we could just only present the output of the latest run command of any type conveniently. The older ones are still available you just need to navigate to them manually.

**Comment by Tyriar** [comment]
Let's merge the commands like `history` does in bash where there may be duplicates, but never consecutive.
