### ISSUE TITLE
Add setting to automatically close Working Tree tabs when window is closed or when commit has been made

### ISSUE THREAD

**Issue by Coteh** [microsoft/vscode#141475]
Although I use git command line for most things, I use the IDE when making commits, and I find that whenever I make a commit, close a project and reopen it at a later point, there are still a whole bunch of Working Tree tabs from before that I do not need to see anymore. I often have a tab for the file itself anyway, so when I reopen the IDE, I basically have two tabs for each file, one of them is the file itself and the other is the diff tab.

It would be nice if there was some sort of config option available to automatically close all these types of tabs whenever a commit has been made and/or when the window is closed. Would keep the IDE a bit tidier for me.

edit: `openDiffOnClick` does not work for me because I still like to see these diffs.

**Comment by bpasero** [comment]
Related/duplicate:
* https://github.com/microsoft/vscode/issues/18651
* https://github.com/microsoft/vscode/issues/135276

**Comment by omidantilong** [comment]
There are already 47 upvotes on one of the old threads for this - are those counted when deciding if something gets moved to the backlog or do people need to vote on _this_ specific issue?

**Comment by lszomoru** [comment]
Yes, this is something that I will be looking at this milestone.

**Comment by lszomoru** [comment]
Today's Insiders release (2022-02-10) contains a new setting (`git.closeDiffOnOperation`) that is meant to address the need to manually close the diff editors after certain git operations. If the setting is enabled, diff editors will automatically be closed when changes are committed, discarded, staged, unstaged. Try out the new setting and let me know your feedback.

**Comment by omidantilong** [comment]
I just gave it a go and it seems to work well so far. Initially it felt a bit eager, I thought it would close on _commit_, not when the file is staged. But I'll try to use it for some "real" work and see how it behaves. 

I do still think a manual "Close all tabs with (Working Tree) in the name" action in the command palette would be useful.

Thanks for the updates!

**Comment by lszomoru** [comment]
Today's Insiders release (2022-02-16) contains a new command `Git: Close All Diff Editors` to manually close the diff editors independent of the `git.closeDiffOnOperation` setting. Please give it a try and let me know if you experience any issues with the command.
