### ISSUE TITLE
Showing Panel does not translate to other open instances

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#141464]
Testing #141357

1. Open a window
2. Open a new window
3. Customize layout
4. Change Side bar location
5. It will switch with both windows
6. Change panel visibility

Expected:
Both windows show the panel

Actual:
Only the active window shows the panel.

Maybe this is be design but it's a little inconsistent.

**Comment by sbatten** [comment]
Panel, Side Bar, and Side Panel visibility are always per-window (workspace settings)... I'd like to move status bar and activity bar to follow suit for consistency but for the time being due to historical behavior, this remains different.
