### ISSUE TITLE
Notebook toolbar resizes when the "Go to running cell" button appears

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#141486]
Testing #141223

- Set `notebook.globalToolbarShowLabel` to `dynamic`
- Resize the window so that it's just big enough for the labels to appear
- Run a cell
- Notice that the labels in the toolbar disappeared

I don't know what the best solution for this would be, if there's any 😔  Since a new icon + label are added to the toolbar when running a cell, this issue is bound to happen for window dimensions that straddle the line between labels being displayed and hidden (and that's not even considering translations).

https://user-images.githubusercontent.com/51720070/151050813-a72c3701-dd98-4af1-a523-4bbf1d8cf76a.mp4

**Comment by roblourens** [comment]
Basically by design, a shorter label for "Go to Running Cell" would help. Would just "Go To" (with the full label in tooltip) and with the spinning icon be clear? Any other ideas to mitigate it @rebornix

**Comment by kimadeline** [comment]
I think the spinning icon is a good enough indicator. Even if we address the issue with "Go To", it might happen in languages with a longer translated label.

**Comment by roblourens** [comment]
Are you saying the button shouldn't have a label in the toolbar?

**Comment by kimadeline** [comment]
Oh no, I meant to say that the current solution is good enough.
