### ISSUE TITLE
Drag feedback for views that cannot move beyond their original panel/viewlet

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#141433]
Testing #141355

It is unclear which views can be moved to the Side Panel (e.g., Docker extension) and which can't (e.g., Remote-Explorer). A possible improvement could be to add drag feedback to indicate that the view cannot be dropped into, e.g., the Side Panel.

**Comment by sbatten** [comment]
we actually do this, but macOS does not display it
