### ISSUE TITLE
Can no longer open an editor

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#141471]
Testing #141357

Got into this state

![image](https://user-images.githubusercontent.com/19672699/151037836-b16d369d-3224-49e0-bf1d-7463fd6d5f3f.png)

Cannot seem to get an editor to appear anymore.

I did this by:
- Enable side panel
- Drag side bar until it covers editors
- Try to undrag

Can't seem to uncover the editors anymore

**Comment by rchiodo** [comment]
Changing to 'justify' layout seems to bring it back

![image](https://user-images.githubusercontent.com/19672699/151038470-de74c773-6961-46f1-b701-63a4c993061d.png)

**Comment by sbatten** [comment]
repro:
1. show side panel
2. align panel right
3. set side bar position to right
4. drag side bar to snap closed editor area

while its recoverable, its not obvious how
