### ISSUE TITLE
Side panel contents changes color of panels dragged into it

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#141468]
Testing #141357

Maybe this is on purpose but in stable when I move say the problems panel to the right, it maintains the same background color:

![image](https://user-images.githubusercontent.com/19672699/151037318-cc02bbac-8982-4010-b856-eb9f15377ac3.png)

In the new 'side panel' the background color is like the 'Side Bar'

![image](https://user-images.githubusercontent.com/19672699/151037418-be5d3453-a3e6-4b82-a715-cc0624fa0530.png)

**Comment by sbatten** [comment]
this is as designed but there is a separate issue about introducing additional theme tokens for the side panel... today, we use side bar theme keys
