### ISSUE TITLE
Tree drag and drop API proposal should support dragging into the editor

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#141418]
The tree drag and drop proposal allows extensions to provide data transfer items when a tree item is dragged, but the only way to drag into the editor is to attach a resource to the tree item.

Attaching a resource to a tree items means that the tree item will receive resource related display characteristics (decorations colors for example). This is not always desirable. 

In the existing `handleDrag` API proposal, we should allow extensions to provide a `resourceurls` mime type that the editor then knows how to handle when the tree item is dropped there. This `resourceurls` type is already used internally.

**Comment by alexr00** [comment]
Closed by https://github.com/microsoft/vscode/pull/140709

**Comment by rchiodo** [comment]
Whoops can't test yet. Well not on insiders.
