### ISSUE TITLE
PWA: anycode does not work since it can not connect to server

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#141400]
Testing #141296

Open vscode.dev in PWA and open a typescript file. Notice anycode error
fyi @jrieken 

<img width="462" alt="Screenshot 2022-01-25 at 12 01 29" src="https://user-images.githubusercontent.com/1926584/150965015-01966aaf-d8eb-4550-acac-c5ada3bb2513.png">

**Comment by joaomoreno** [comment]
Marketplace extensions are not yet functional.

**Comment by jrieken** [comment]
@joaomoreno Why is that marketplace related? The anycode extension seems installed but the message sounds more like an LSP setup issue, e.g the LSP server is likely meant but I need to drill into LSP bits to understand this further

**Comment by joaomoreno** [comment]
An extension to be "installed" on vscode.dev means nothing. Even on a subsequent reload, the extension will be fetched from vscode-unpkg. So... if there's any dynamic loading that the extension does (ie request additional files at runtime), it could be that @isidorn was in a state in which he has the extension activated before going offline, went offline and then opened a TS file which made the extension load additional resources.

Does anycode do any dynamic loading?

**Comment by jrieken** [comment]
> Does anycode do any dynamic loading?

Yes, it starts its LSP server which is implemented in a different file (which is loaded from the extension "folder"). Tho, that is done [immediately](https://github.com/microsoft/vscode-anycode/blob/b90f170a19fd6f869a463d30078315198b2b6492/client/src/main.ts#L18) during activate

**Comment by joaomoreno** [comment]
It can actually be something else: the mechanisms by which the entry point and the server are loaded are different. We currently do cache certain things from vscode-unpkg... but I believe that only covers the first mechanism.
