### ISSUE TITLE
Gutter indicators for running cells?

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#141481]
Testing #141223

Might be nice to have the location of the running cells marked in the guttter, iif you have a large notebook with many cells running it's annoying to need to scroll around to find the running cell. Could be somewhat alleviated by #141478, but it'd be nice to have both

**Comment by DonJayamanne** [comment]
Given this issue has been around for almost 3 years without any upvotes, I'm closing this issue as not planned.
