### ISSUE TITLE
Using vscode with Jupyter extension, how to find/replace text within a notebook cell

### ISSUE THREAD

**Issue by lgonzalezsa** [microsoft/vscode#141493]
In Jupyter Lab and Notebook web UI, it is possible to find and replace in the selected cell or entire notebook.

How to instruct vscode to replace only in the selected cell?

https://stackoverflow.com/questions/70043037/using-vscode-with-jupyter-extension-how-to-find-replace-text-within-a-notebook

**Comment by rebornix** [comment]
@lgonzalezsa thanks for your feedback, this can be a great addition to the new filter UX we introduced for the find widget 

![Uploading image.png…]()

**Comment by lgonzalezsa** [comment]
Awesome!

**Comment by 392781** [comment]
@rebornix Why not just make it so that you search within the current selection?  

If you're focusing a cell, you search the cell.  
If you're focusing the notebook, you search the notebook.

**Comment by rouzki** [comment]
Hi any update ?

**Comment by wandli** [comment]
Wanting update +1

**Comment by Greco1899** [comment]
+1. This would be really helpful!

**Comment by Chipmunk91** [comment]
This is going to be huge help!

**Comment by rouzki** [comment]
The solution that I am using :
 1. Select one occurrence of the text that you want to change.
 2. Press Ctrl+Shift+L, to select all occurrences of current selection.
 3. Then start editing all selection occurrences at the same time.

**Comment by luchungi** [comment]
> The solution that I am using :
> 
> 1. Select one occurrence of the text that you want to change.
> 2. Press Ctrl+Shift+L, to select all occurrences of current selection.
> 3. Then start editing all selection occurrences at the same time.

The other way is to use Alt+Click of the mouse on all areas you want to edit at the same time if Ctrl+Shift+L ends up selecting beyond parts which you wish to edit.

For the VS Code solution to this problem, I think we need the find/replace function to have the option of restricting it to the selected text instead of just confining it to the selected cell as the prior option can also easily achieve the selected cell option. Of course, having both options is even better.

**Comment by rouzki** [comment]
> 

If I want to restrict my selection I don't use the mouse (as it's not easy, and takes too much time), I simply select the occurrence then keep pressing Ctrl+D to select only the next occurrence.

**Comment by rouzki** [comment]
> > The solution that I am using :
> > 
> > 1. Select one occurrence of the text that you want to change.
> > 2. Press Ctrl+Shift+L, to select all occurrences of current selection.
> > 3. Then start editing all selection occurrences at the same time.
> 
> The other way is to use Alt+Click of the mouse on all areas you want to edit at the same time if Ctrl+Shift+L ends up selecting beyond parts which you wish to edit.
> 
> For the VS Code solution to this problem, I think we need the find/replace function to have the option of restricting it to the selected text instead of just confining it to the selected cell as the prior option can also easily achieve the selected cell option. Of course, having both options is even better.

If I want to restrict my selection I don't use the mouse (as it's not easy, and takes too much time), I simply select the occurrence then keep pressing Ctrl+D to select only the next occurrence.

**Comment by lgonzalezsa** [comment]
I learned from https://stackoverflow.com/a/73109147/1729896 that using `F3` enables the find and replace for the cell, just what I need, hope this helps others.
CTRL-D also is a nice feature. Closing for now.

**Comment by gjsjohnmurray** [comment]
See also #121218
