### ISSUE TITLE
Terminal auto replies: Differing default values

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#141456]
Testing #141341

I tried several different configurations of the setting; I outlined 3 different ones here.

- Config 1: Set:

```
"terminal.integrated.autoReplies": {
        "Terminate batch job (Y/N)": "Y\r"
      }
```

- Run a script, ctrl+c
- Batch job terminated without further user interaction, output is: `Terminate batch job (Y/N)? Y` and then returns
- Config 2: Change setting to empty: `"Terminate batch job (Y/N)": "" `, run and terminate script again
- Asked in terminal `Terminate batch job (Y/N)?`, need to manually type an answer
- Config 3: Comment out setting line: run and terminate script again

```
"terminal.integrated.autoReplies": {
        //"Terminate batch job (Y/N)": ""
      }
```

- ❓: Batch job terminated without further interaction, behaving the same way as `"Y\r"`

I thought config 2 and config 3 would behave the same: either both defaulting to `"Y\r"` behavior or both defaulting to requiring the user to manually enter `Y` or `N`. Is it expected they'd behave differently?

**Comment by Tyriar** [comment]
I expected this too, the defaults and user settings are probably being mixed in which I don't think it desirable here.

**Comment by rchiodo** [comment]
The setting seems to have no effect for me.

I've tried this:

```json
  "terminal.integrated.autoReplies": {
    "Terminate batch job (Y/N)": ""
  }

```
This
```json
  "terminal.integrated.autoReplies": {
    "Terminate batch jobsss (Y/N)": ""
  }

```
and this
```
```json
  "terminal.integrated.autoReplies": {
    "Terminate batch job (Y/N)": "Y\r"
  }

```
They all behave the same. It ALWAYS enters the ```Y``` for me.

**Comment by Tyriar** [comment]
In general this works for me, but rarely it doesn't so there's probably some race condition when passing the updates over to the pty host (this may only happen when multiple windows are opened?). Pushing to next iteration as it's low priority and restarting VS Code should always fix it up.

**Comment by Tyriar** [comment]
I couldn't reproduce the issue again, I called out that you may need to restart VS Code to apply new values
