### ISSUE TITLE
Make file explorer more readable: problem with distinguishing files and folders

### ISSUE THREAD

**Issue by OnkelTem** [microsoft/vscode#141406]
Currently, the file tree is rendered a way, which makes it difficult to distinguish folders from files: they're blending together into one list.

Let's have a look at the problem:

![image](https://user-images.githubusercontent.com/114060/151662073-f983b3c7-d738-4fcd-a145-e50af5a9347a.png)

Let's compare it with the same view in WebStorm:

![image](https://user-images.githubusercontent.com/114060/151662097-04121280-030c-420c-8e19-800114104700.png)

I guess it's more or less clear where folders end and files start, isn't it? There are two reasons for that:

1) Main: The folder's arrow expand sign ">" has a negative indent which clearly separates folders from files in the list.

2) Secondary: Folders are also prefixed with a well-known folder icon.

Initially I thought that utilizing color would help. But now I'm not sure, since color in the file tree is already used for encoding another type of information. But to not lose the initial idea, let's add it to the list as well.

*Proposition*

Make file tree more readable by:

1) Providing an optional negative indent for folders;

2) Adding "folder" icons to folders

3) Allowing to color folders and files separately (via masks?)

==== ORIGINAL POST ===

Currently there seem to be no way to set different colors for files and folders: 
https://code.visualstudio.com/api/references/theme-color#lists-and-trees

This is a big problem for me personally as folders and files look just the same way. I wonder why it was not added before. And I found no ticket on this. Hence, this request.

**Comment by OnkelTem** [comment]
Thanks, that's great. Now we can finally start thinking on different approaches to increase readability of the file tree.

**Comment by OnkelTem** [comment]
Thanks to the help of great VSCode community, I was recommended to try an extension called vscode-icons[https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons]. 

It's very popular among the community, and actually solves the main issue by adding a reasonable indent to files:

![image](https://user-images.githubusercontent.com/114060/151669391-62232ed5-f7a3-475d-8a04-915296bdab07.png)

Yet, I still incline to the thought that this feature (file indents or folder negative indents) should be provided out-of-the-box. As well as folders/files custom (and independent) coloring.

**Comment by JacksonKearl** [comment]
I don't understand the request here. The WebStorm photo you provided simply shows folder icons, we provide file icon themes out of the box that do the same: 
Minimal: <img width="483" alt="image" src="https://user-images.githubusercontent.com/8586769/155448240-839de258-79b7-4dde-9025-a73bfb093cb5.png">

And extensions can do whatever they want: 
Material Icon Theme: <img width="427" alt="image" src="https://user-images.githubusercontent.com/8586769/155448330-f935d7f9-6a9b-4ad3-ab42-c0f3fc258f9d.png">

**Comment by fwcd** [comment]
I think @OnkelTem's point (in https://github.com/microsoft/vscode/issues/141406#issuecomment-1024945727) is worth highlighting here: Treating files and folders inconsistently (as VSCode's default icon theme, Seti, does) makes it less readable than WebStorm and other themes, which align both files and folders by placing the arrows to the left of the whole column rather than making the arrow the folder icon.

I think the ideal default theme would be with the folders/alignment from the current 'minimal' theme:

![image](https://user-images.githubusercontent.com/30873659/160027872-73810bf9-a937-4009-bcf4-b0e8ebb95049.png)

...but with Seti's icons for files:

![image](https://user-images.githubusercontent.com/30873659/160027834-72edab5d-da80-409d-9bc7-35f42e2c8da8.png)

**Comment by fwcd** [comment]
Another reason to consider placing arrows consistently left of the icons would be that indentation becomes really messy once [file nesting](https://code.visualstudio.com/updates/v1_64#_explorer-file-nesting) gets involved:

![image](https://user-images.githubusercontent.com/30873659/160028168-16f4fc34-e3dc-4c43-9cda-a033f0c97278.png)

**Comment by JacksonKearl** [comment]
IMO the correct solution is already implemented: extensions can provide file icon themes with full control over file icons, folder icons, and explorer arrows. 

There's not much use arguing over the default, the current one is happily used by many millions of people -  changing it without a very solid reason is asking for trouble.
