### ISSUE TITLE
Does not update the code after compiling

### ISSUE THREAD

**Issue by Lailatorki** [microsoft/vscode#141446]
Issue Type: <b>Bug</b>

No step needed, just open terminal and you have twice this message : 
bash:  /etc/profile.d/codespaces.sh: line 15: syntax error near unexpected token `done'
bash:  /etc/profile.d/codespaces.sh: line 15: `done < /workspaces/.codespaces/shared/.env-secrets'

I don't know what it means nor how to fix it but the compiling doe not work since this.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1067-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (10.31GB free)|
|Process Argv|--crash-reporter-id 4cd55373-00ac-4875-a8fa-df27aa5bcf0e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1067-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (2 x 2593)|
|Memory (System)|3.84GB (0.40GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.9.6
codespaces|Git|1.5.0
cs50|CS5|0.0.1
ddb50|CS5|0.0.1
phpliteadmin|CS5|0.0.1
gitlens|eam|11.7.0
codespaces|Git|1.5.0
vscode-pull-request-github|Git|0.34.3
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.3
jupyter|ms-|2021.11.1001550889
cpptools|ms-|1.7.1
hexeditor|ms-|1.9.3
vsliveshare|ms-|1.0.5273
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
jinjahtml|sam|0.16.0
gitdoc|vsl|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30424896
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30416617
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by roblourens** [comment]
Is this an issue with Github Codespaces? If so please file at https://github.com/github/feedback/discussions/categories/codespaces-feedback
