### ISSUE TITLE
View dragged to the side panel not rendered initially

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#141427]
Testing #141356

1. Have the outline view in the panel at the bottom of the screen
    ![image](https://user-images.githubusercontent.com/3372902/150990595-e2e18b7a-7680-4f93-b1ad-fe8d30101c62.png)
2. Drag the outline view from the panel to the side panel on the right. Notice how the tab for the view is rendered, but the contents of the view itself are not.
    ![image](https://user-images.githubusercontent.com/3372902/150990689-46174f07-5b9c-4e03-9523-a9d6ac931984.png)
3. Click on the tab, will cause the view contents to be rendered

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/141384
