### ISSUE TITLE
Quick pick item separator label and buttons shift around on hover

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#141474]
Testing #141193

The separator label is always rendered for the first item in the list. If that item also has buttons contributed for it, this causes the separator label to shift around on hover:

![Recording 2022-01-25 at 10 54 05](https://user-images.githubusercontent.com/30305945/151040743-b9b9d714-f201-4343-90e2-b0cf60f6889e.gif)

**Comment by TylerLeonhardt** [comment]
I think this is really by design. Where else could it go? 🤔

Maybe it would make more sense if I fixed: #131398

**Comment by TylerLeonhardt** [comment]
Any thoughts, @misolori?

**Comment by misolori** [comment]
Not sure if we ever ran into this one before, but the action and label should aligned as that looks off and think being anchored to the top is fine.
