### ISSUE TITLE
Cannot "Hide Terminal"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141405]
Testing #141357

![image](https://user-images.githubusercontent.com/900690/150971167-ce26b496-b933-44f5-89d4-9f6800428959.png)

I had dragged the outline view into the side panel where terminal was and would have expected I can now "Hide Terminal".

**Comment by sbatten** [comment]
@Tyriar do you do something to prevent hiding in any case?

**Comment by Tyriar** [comment]
Not intentionally at least, no idea how I would communicate that to the layout code.

**Comment by Tyriar** [comment]
@sbatten the cause is here:

https://github.com/microsoft/vscode/blob/a30e4b2b7651ecce46e85f93a4207afd67cd1e20/src/vs/workbench/contrib/terminal/browser/terminalGroupService.ts#L79-L83

I don't remember adding that.

**Comment by sbatten** [comment]
@Tyriar thanks, i think we can remove the restriction on view container location, what do you think?

**Comment by Tyriar** [comment]
@sbatten actually that might not be the cause after thinking on it more, I think that drives ensuring the view doesn't get closed if you have a setup like problems next to terminal. Would be a pain to manually show it again?

This might be it?

https://github.com/Microsoft/vscode/blob/74e7864370241df106ff7a330a8aaf2a3b6735a5/src/vs/workbench/contrib/terminal/browser/terminal.contribution.ts#L110

**Comment by sbatten** [comment]
@Tyriar I actually thought the last comment was on a separate issue about deleting the last terminal... I still think that code is relevant for that fix. For this issue, the new code is likely it. I don't recall why this would be that way.

**Comment by sbatten** [comment]
looks like a mistake 
<img width="614" alt="image" src="https://user-images.githubusercontent.com/6561887/151032012-a58fa5d7-4366-4ebb-acd5-099ccde94a06.png">

**Comment by Tyriar** [comment]
@sbatten I just hid the terminal panel below and i don't think there's any way of bringing it back outside running a command/keybinding. Was it was added to protect against this case?

<img width="274" alt="Screen Shot 2022-01-25 at 9 56 14 am" src="https://user-images.githubusercontent.com/2193314/151032433-34676322-e8a6-4f07-8c72-445e39b65d99.png">

Hiding the panel/view works, it's just not when it's in a container view or whatever it's called.

**Comment by sbatten** [comment]
Ah, we don't surface the views on the panel's composite bar context menu so it gets lost unless there are multiple views. This is not a regression and all built-in panel's are not toggle-able at the moment, so I will punt this to february.

**Comment by benibenj** [comment]
@Tyriar  I suggest we just enable `canToggleVisibility` for terminal and some other views. There are enough ways to bring them back now. For example the Views submenu which @bpasero added or focus commands

<img width="537" alt="Image" src="https://github.com/user-attachments/assets/46154226-f23d-446a-8bc2-6cdcfaf87903" />
