### ISSUE TITLE
Animated icon in breadcrumbs still there when notebook.outline.showCodeCells is disabled

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#141491]
Testing #141223

Repro steps:
- Enable `notebook.outline.showCodeCells`
- Run a cell, verify that there's an animated icon in the breadcrumbs
- Disable `notebook.outline.showCodeCells`, whether by unticking it in the settings UI, or setting it to false in the json
- Run the same cell again, the animated icon is still here

![animated cell show code false](https://user-images.githubusercontent.com/51720070/151060238-e742e3e7-2981-45f9-a83b-6486bab43943.png)

**Comment by roblourens** [comment]
The outline and breadcrumbs have separate settings :)

**Comment by kimadeline** [comment]
🤦
