### ISSUE TITLE
Add "Open Terminal" command (internal)

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#141487]
![image](https://user-images.githubusercontent.com/8586769/151051118-a8df054b-272b-4868-9668-4209e1054f0f.png)

This would have be believe that the only Open Terminal I can do is external. 

We have these, but none seems to exactly match "Open Terminal":
![image](https://user-images.githubusercontent.com/8586769/151050978-9d767e59-d640-451d-a768-4bbc1f274ac7.png)

**Comment by Tyriar** [comment]
@TylerLeonhardt any idea if we can do synonyms for commands like this?

**Comment by JacksonKearl** [comment]
I guess the command I wanted was "Focus Terminal", but mentally Open made more sense.

**Comment by TylerLeonhardt** [comment]
@Tyriar not really... you'll need to just register an additional command.

There's also this issue #50836

**Comment by Tyriar** [comment]
@JacksonKearl this has come up before, but we can't really change the name and I don't want to create duplicate commands just for command palette discoverability.

/duplicate #50836
