### ISSUE TITLE
Quick Open widgets to open below tab/action bar

### ISSUE THREAD

**Issue by wprater** [Microsoft/vscode#14142]
- VSCode Version: 1.7

Has there been any meetings about the placement of the quick open widget?  with the new eager preview option, its kinda weird to not see which tabs are being switched around or opened in the background while the widget is not hidden.

**Comment by wprater** [comment]
I agree on it's positioning.  However, would it be OK to span centered across multiple editor groups?

**Comment by bpasero** [comment]
That seems very weird to me because the impression is that the quick open widget is anchored to the editor and not workbench imho.

**Comment by wprater** [comment]
> That seems very weird to me because the impression is that the quick open widget is anchored to the editor and not workbench imho.

yeah, let's pop it out centered below the editor group.
