### ISSUE TITLE
Sequential commands result in weird output in powershell

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#141497]
Testing #141339

1. In powershell, run `echo hi`
2. Then `echo bye`
3. View the command output of `echo bye`
4. This is the result:

![image](https://user-images.githubusercontent.com/2230985/151068403-8a9d9b9f-b12c-4845-8815-76952fc1385e.png)

It seems like the command is incomplete, and the output includes both the requested as well as the previous command

**Comment by connor4312** [comment]
Output detection in powershell is very inconsistent, I can provide more examples if needed but I'm guessing they're all from the same underlying issue(s)

**Comment by meganrogge** [comment]
Yes when we added the output feature, only zsh was working so this is not surprising.

**Comment by Tyriar** [comment]
The inconsistency is just on windows though. Can investigate improvements as part of this issue.

**Comment by meganrogge** [comment]
this might be fixed now by https://github.com/microsoft/vscode/pull/141601

**Comment by meganrogge** [comment]
can still reproduce

**Comment by Tyriar** [comment]
This works mostly fine for me, shell integration on Windows needs https://github.com/microsoft/vscode/issues/153476 to be fixed in order to be more reliable. Closing in favor of that issue
