### ISSUE TITLE
Hex Editor is not updated if bytes are updated outside of editor

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#141476]
Testing #141347

1. Open hex editor from variables view
2. Update bytes in debug console or by stepping through code

🐛 => hex editor remains unchanged

**Comment by connor4312** [comment]
I don't think we'll be able to detect byte updates via the debug console, but updates via stepping is covered by the 'known issue' in https://github.com/microsoft/debug-adapter-protocol/issues/238
