### ISSUE TITLE
Ambiguity in comments for createFileSystemWatcher 

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#141494]
Testing #140693

I found the language on this line ambiguous:
https://github.com/microsoft/vscode/blob/5d9d61821592ef998299d595f2107a1c149f8d9c/src/vscode-dts/vscode.d.ts#L11006

'This method' I believe is referring to passing a string or glob pattern. But the first time I read I thought it was referring to createFileSystemWatcher (which would contradict the previous bit of documentation).

Perhaps replace 'This method' with 'Using a string or a glob pattern'.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/blob/4454a14dd28cd93848b138a5da412d7442d04047/src/vscode-dts/vscode.d.ts#L11005-L11007
