### ISSUE TITLE
Make sure that "View Binary Data" is accessible

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#141442]
Testing #141347

I'm not sure how accessible the "inline on hover" action "View Binary Data" is:

![CleanShot 2022-01-25 at 16 35 15@2x](https://user-images.githubusercontent.com/1898161/151007904-4bc17fe3-2543-4ddd-b177-c0a6cdebf2ba.png)

@isidon what's your your POV?

It might be necessary to install the "View Binary Data" command as a context menu action on the variable.

**Comment by connor4312** [comment]
It's structured like other inline actions and is tab-accessible. Let me know if there's anything else to do here.

**Comment by weinand** [comment]
@isidorn please let us know whether the "inline on hover" action "View Binary Data" is accessible.

**Comment by isidorn** [comment]
@weinand yes, all inline actions are accessible. I just tried it out and my biggest concern is regarding the hex view which is not very accessible. For example `up/down` do not work in the hex value and I think we could use better aria labels.
@lramos15 have you been thinking about the hex view from the accessibility perspective?

**Comment by lramos15** [comment]
@isidorn The hex view attempts to do its best to be accessible. Arrow key navigation should work. @connor4312 Just rewrote it in React versus normal vanilla DOM APIs so some things may have been lost.
