### ISSUE TITLE
Explorer Enable Undo doesn't prompt

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#141465]
Testing #141351

On macOS

* Ensure the `explorer.enableUndo` setting is not modified (default to `warn`) 
* Create two folders `A` and `B`, create file `a.py` in `A`
* Drag it to `B`
* Undo

There isn't any prompt of warning

**Comment by rebornix** [comment]
Renaming a file and undo doesn't warn either.

**Comment by rebornix** [comment]
The way I interpreter `warn` is it will warn is it prompts and tells you what's going to happen when you undo/redo as the undo/redo is focus based and it's likely to mis-trigger. I don't necessarily want to disable this feature (as it's convinient) but I want to be aware of what's going to change. Undo the dnd is one of them as I might miss where the file will be moved into (especially when I'm traversing in the undo stack).

**Comment by JacksonKearl** [comment]
Changed the config around to better stratify this:

```
		'explorer.confirmUndo': {
			'type': 'string',
			'enum': [UndoConfirmLevel.Verbose, UndoConfirmLevel.Default, UndoConfirmLevel.Light],
			'description': nls.localize('confirmUndo', "Controls whether the explorer should ask for confirmation when undoing."),
			'default': UndoConfirmLevel.Default,
			'enumDescriptions': [
				nls.localize('enableUndo.verbose', 'Explorer will prompt before all undo operations.'),
				nls.localize('enableUndo.default', 'Explorer will prompt before destructive undo operations.'),
				nls.localize('enableUndo.light', 'Explorer will not prompt before undo operations when focused.'),
			],
```
