### ISSUE TITLE
consider to integrate HexEditor into debug viewlet

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#141440]
Testing #141347

Clicking on the "View binary Data" switches for the Debug viewlet to the HexEditor viewlet.
This is a drastic context switch for users. 

I suggest to install the Hex Editor in the debug viewlet because it makes more sense to keep its "Data Inspector" close to the Variables view.

**Comment by sbatten** [comment]
I actually moved it to the debug viewlet with drag and drop for this exact reason.

**Comment by weinand** [comment]
Yes, me too. But if we all have to do this, then this should be the default.

**Comment by connor4312** [comment]
@lramos15 mentioned wanting to get rid of it and integrate into the webview instead. I'm a bit in the same boat -- or perhaps putting it in the panel would work better.

I don't think the debug viewlet is the right place for it, since the hex editor also works for generic files on disk.

**Comment by lramos15** [comment]
> @lramos15 mentioned wanting to get rid of it and integrate into the webview instead. I'm a bit in the same boat -- or perhaps putting it in the panel would work better.

I'm sure users would want the option. I know some have discussed the dislike of the panel being confusing with multiple hex editors open

**Comment by weinand** [comment]
Something like the following would work for me:
If a debug sessions opens the "binary data view", the Hex Editor's Data Inspector should land in the debug viewlet (below the Variables view) and the Hex Editor could open in the splitted editor area.
The important thing is that there is no switch between the debug viewlet and a HexEditor viewlet.

If the HexEditor is used to open a binary file, then both the Data Inspector and the Hex Editor could continue to live in their own viewlet.

**Comment by weinand** [comment]
Another idea for the Data Inspector:

the data inspector is closely related to the selection in the Hex Editor but it lives far away from the Hex Editor.
In addition the Data Inspector is a bit bulky but at the same time all the various formats are only rarely used.

Would it be possible to fold/integrate the Data Inspector into the Hex Editor for example as something similar to a code assist overlay window? After selecting some bytes in the Hex Editor the data inspector would open adjacent to the selection with only those edit fields available that make sense for the selection size.

The advantage of this approach is that the Hex Editor would be self contained and that no separate data inspector would have to be managed.

**Comment by connor4312** [comment]
Yes, I like that idea

**Comment by connor4312** [comment]
There's now three modes, controllable by `hexEditor.inspectorType`

- `sidebar` shows the inspector in the sidebar, as it was previously
- `hover` shows the inspector only when hovering on a byte
- `aside` (default) show the inspector on the right side when there's approximate space for it, otherwise shows a hover in narrow editors
