### ISSUE TITLE
Quick fix lightbulb bleeds onto other editors

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#14141]
1. Get a quick fix lightbulb in the gutter
2. Quick open another file

The lightbulb will survive the switch.

![bug](https://cloud.githubusercontent.com/assets/22350/19592229/10d7dc0e-977b-11e6-9120-89f2272fbdbd.gif)

**Comment by octref** [comment]
![switch](https://cloud.githubusercontent.com/assets/4033249/19778896/9b3b9acc-9c33-11e6-9fad-e17b17d0be65.gif)

**Comment by jrieken** [comment]
to verify make sure to move from a CSS file to a CSS file (not change the mode)
