### ISSUE TITLE
File nesting: Improve file icon rendering for folder less themes

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#141428]
Testing #141354
- set `"explorer.experimental.fileNesting.enabled": true`
- open a folder with `foo.js` and `foo.ts`
- use the Seti file icon theme
![image](https://user-images.githubusercontent.com/6461412/150968856-1302b2a9-def5-408a-aa2f-38e9e241532b.png)

Theres a misalignment as the Seti theme doesn't expect that a file can be a root node.
We probably have to hide the icon of `foo.ts`

**Comment by JacksonKearl** [comment]
cc @misolori any ideas on how this could look? I like how the icon lets me know it's a file, but agree the alignment is weird.

**Comment by misolori** [comment]
I'd probably hide the file icon for the parent folder, even though it isn't ideal but you can't get alignment and folder icon unless we add a folder icon for seti icons:

<img width="273" alt="CleanShot 2022-01-25 at 20 39 51@2x" src="https://user-images.githubusercontent.com/35271042/151104956-7c55666f-6966-4ec0-b20c-050d882dc170.png">

**Comment by chrisdias** [comment]
with the minimal file icon theme everything lines up nicely, the nested files are indented nicely

![image](https://user-images.githubusercontent.com/1487073/151620948-542f8810-502e-4a93-9466-628ac13addfc.png)

As compared to seti...

![image](https://user-images.githubusercontent.com/1487073/151621008-8255a401-7cba-4929-9416-b2108dfbd815.png)

**Comment by JacksonKearl** [comment]
I'll try to find a way to make Seti work well next iteration, I'd rather not lose the quick identifiability the icons provide but agree the current alignment is very odd

**Comment by aeschli** [comment]
@JacksonKearl Happy to help and review.
`align-icons-and-twisties` is the css rule that is set when a file icon theme only defines file icons but no folder icons.

**Comment by aeschli** [comment]
There are also file icon themes that disable the twisties. Instead, they provide different folder icons for expanded and collapsed folders.
An example is the[Ayu](https://marketplace.visualstudio.com/items?itemName=teabyii.ayu) theme:
![image](https://user-images.githubusercontent.com/6461412/151774332-8473c9fe-bcb7-4fcb-b8a6-67667c831025.png)

Again such themes don't work well with file nesting
![Peek 2022-01-31 11-07](https://user-images.githubusercontent.com/6461412/151774604-1fbbb7b3-f748-4a4a-ba87-feaa605163db.gif)

I can open a different issue for that.

**Comment by yume-chan** [comment]
> There are also file icon themes that disable the twisties. Instead, they provide different folder icons for expanded and collapsed folders.

#141359

**Comment by misolori** [comment]
Another idea that came from the ux sync was aligning the other files to the same indentation in the case where there is no folder icon (like seti) and since they are not sibilings they should be on the same indentation:

<img width="300" src="https://user-images.githubusercontent.com/35271042/152203781-5ee2218f-f8c6-4ef2-8972-fd834ba84dbb.png">

**Comment by babakfp** [comment]
Hi @JacksonKearl
I see you are working on this feature. What do you think about a config (for each pattern) that disables the ability to hide the nested files (child files)? So they can always be visible and accessible. I see that it can be a useful feature to add. For example, this is what it is right now:
![Screenshot 2022-02-21 131244](https://user-images.githubusercontent.com/44144724/155026890-fe12ffe1-1e62-4caf-a639-c464f2efe0d4.png)
... and this is how I want it to be:
![Screenshot 2022-02-21 131207](https://user-images.githubusercontent.com/44144724/155026907-e8ceab04-1bde-4919-ae57-1905cc3419d2.png)

---

Also, an option for each pattern to hide the child file icon if its name was equal to the parent file name or something like that.

**Comment by JacksonKearl** [comment]
@babakfp by default all nests are shown expanded, I don't see why we'd want to remove the option of collapsing them?

**Comment by babakfp** [comment]
Hi
Thank you for your response

> by default all nests are shown expanded, I don't see why we'd want to remove the option of collapsing them?

It's because of this problem and reasons👇
https://github.com/microsoft/vscode/issues/141359
- So I can have peace of mind that there are no hidden files.
- Some people may disable the whole nesting feature because they don't want this problem #141359 to happen to them.

Thank you again. A saw a lot of issues assigned to you, here is a coffee🍵😅🌸

@JacksonKearl

**Comment by JacksonKearl** [comment]
#141359 is definitely a bug, but it only appears when the file icon theme has disabled folder chevrons. I will be fixing that this iteration by rendering nests with chevrons regardless of whether they're rendered with folders.

**Comment by JacksonKearl** [comment]
We now hide the icon of a nest parent if the folders do not have chevrons or icons

**Comment by babakfp** [comment]
> I will be fixing that this iteration by rendering nests with chevrons regardless of whether they're rendered with folders.

But it's not the same. There is an option to hide the 'angle down/arrow down' icon, so it means that there was/is a need for this option/this functionality. By doing what you said, you are destroying that functionality!

> We now hide the icon of a nest parent if the folders do not have chevrons or icons

What do you mean is that this (TS) icon is going to be hidden?:

![150968856-1302b2a9-def5-408a-aa2f-38e9e241532b](https://user-images.githubusercontent.com/44144724/157363046-7f4526bd-d29d-4aa0-a0c4-8014793d190f.png)

It's not a good thing to do if it's not optional for each nest. (Maybe I misunderstood what you meant)

@JacksonKearl

**Comment by JacksonKearl** [comment]
That is what I have now, though I can see the sense in doing [this](https://github.com/microsoft/vscode/issues/141428#issuecomment-1028166906) instead.

**Comment by babakfp** [comment]
> That is what I have now, though I can see the sense in doing https://github.com/microsoft/vscode/issues/141428#issuecomment-1028166906 instead.

Yeah, in my opinion, this one is better than removing the icon.

It's also useful to only group files together(for ordering porpuses) instead of nesting them under each other.
