### ISSUE TITLE
Seeing both editor and cell progress bars?

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#141477]
Testing #141223

Not sure if this is expected, 
![image](https://user-images.githubusercontent.com/8586769/151042244-17250a60-d6a6-45fd-96b3-c5421203d31b.png)

**Comment by JacksonKearl** [comment]
Also the "go to running cell" action is visible

**Comment by JacksonKearl** [comment]
This is an untitled handy dandy notebook, as created by

**Comment by JacksonKearl** [comment]
Side note, I tried again with more cells running and did see the expected "no editor progress bar when executing cell is in view" behaviour, but now I think I'd actually like the editor progress bar to be visible if there are cells besides the one in view running, it'd be a nice indication that there's something else going on in a potentially big multi-entrant notebook.

![image](https://user-images.githubusercontent.com/8586769/151045389-fdf43ba7-5662-426d-8fe9-8d19a15a5b5e.png)

**Comment by roblourens** [comment]
The first issue, can you trigger this consistently or was it a random occurrence? The second suggestion, good idea.

**Comment by JacksonKearl** [comment]
Reproduces reliable when I have only a single cell and it's executing. If I have multiple cells it doesn't reproduce.
