### ISSUE TITLE
More intuitive description for never/disable option for explorer.enableUndo

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#141469]
Testing #141351

It's not clear what `disable/never` means for `explorer.enableUndo`. `allow`/`warn` are talking about when the explorer will prompt to warn users but `never` disable this feature completely. I didn't get that when the first time read `does not anticipate in undo events`, maybe we make it clear that undo/redo will no longer work in explorer when disabled.

**Comment by JacksonKearl** [comment]
Moved to `Undo will be disabled in the explorer.`

**Comment by JacksonKearl** [comment]
Actually split this into two settings, so `explorer.enableUndo` is a boolean controlling whether the explorer does undo at all, then `explorer.confirmUndo` is an enum configuring how frequently to prompt.
