### ISSUE TITLE
Secondary panel icon shows options outside of window

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#141453]
Version: 1.64.0-insider
Commit: f93c69659de1a1466bd15e0f1c9f790e73be9208
Date: 2022-01-25T08:42:38.986Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

When you change the window size of the editor and click on the tile icon on the top right, the menu of options opens up outside of the window.

https://user-images.githubusercontent.com/9721254/151019193-6c307648-293a-4430-96b5-39dec928c8f0.mov

**Comment by sbatten** [comment]
duplicate
