### ISSUE TITLE
Side Panel: Too much space between SCM icon and its batch

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#141432]
Testing #141355

<img width="142" alt="image" src="https://user-images.githubusercontent.com/9205389/150998570-c270a9fc-a9e7-4f55-bccc-779c286113dc.png">

**Comment by sbatten** [comment]
independent of the linked issue, I think I can improve the badge situation

**Comment by sbatten** [comment]
This is only a simple fix for the release to reduce the spacing. Next milestone we can revisit better representations as mentioned in the linked issue.
