### ISSUE TITLE
Closing last terminal in panel closes panel, but not side panel

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141404]
Testing #141357

When you hit the trash icon on the last terminal in panel, the panel closes. But the same does not happen in side panel, leaving an empty terminal area around.

![image](https://user-images.githubusercontent.com/900690/150970874-d372e059-0821-4df6-8f73-9af0e2ffa88d.png)

//cc @Tyriar

**Comment by Tyriar** [comment]
This is what does this:

https://github.com/microsoft/vscode/blob/0e7b7662b176562d88a7d3ee6e12f7f7bd29c6da/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L180-L187

@sbatten do you think we should hide the side panel here just like the panel? Would be harder to bring back up without default keybindings.

**Comment by sbatten** [comment]
I think we should probably hide the same as the panel, for terminal especially, people typically know the keybinding

**Comment by Tyriar** [comment]
@sbatten I removed this if statement and closeView didn't seem to do anything:

https://github.com/microsoft/vscode/blob/a30e4b2b7651ecce46e85f93a4207afd67cd1e20/src/vs/workbench/contrib/terminal/browser/terminalGroupService.ts#L81

**Comment by Tyriar** [comment]
@sbatten I think this is on your end since I verified we call `IViewsService.closeView` and it doesn't close the side panel
