### ISSUE TITLE
"Go to running cell" indicator still spins when cell stopped in debug

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#141490]
Testing #141223

![image](https://user-images.githubusercontent.com/8586769/151057265-24800de9-b4ff-4c88-833a-2f2067d12467.png)

**Comment by roblourens** [comment]
Oh yes, it's actually not possible to change this without registering two separate actions, and I figured I'd wait to see if it's really annoying (do you think it's really annoying?)

**Comment by JacksonKearl** [comment]
I don't think it's terrible. My notebooks don't support debug so I wouldn't notice it anyways.
