### ISSUE TITLE
Make shell integration scripts idempotent

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#141458]
When called twice it should not for example wrap the prompt twice. This will be required for setting up manual shell integration (eg. for sub-shell support #141343).

**Comment by meganrogge** [comment]
we will want to make sure that `injectShellIntegrationArgs` is aware of its args, so doesn't warn if they're already set
![Screen Shot 2022-01-31 at 12 07 11 PM](https://user-images.githubusercontent.com/29464607/151850177-7b15aa39-71cf-4f70-8abe-cb191834bac7.png)

**Comment by Tyriar** [comment]
The warning is probably fine to keep, the user can just ignore it or set `enableShellIntegration` to `false` to suppress it in that case since they handle it manually.

**Comment by Tyriar** [comment]
I believe the scripts are already idempotent as they don't export environment variables. If there is an issue it can be handled in https://github.com/microsoft/vscode/issues/141343
