### ISSUE TITLE
"type" not suggested in contributes.configuration 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#141499]
Issue Type: <b>Bug</b>

1. Create a VS Code extension
1. In the package.json, try creating a new configuration section

```
"contributes": {
    "configuration": [
        {
            "title": "Settings Editor Widget Samples",
            "order": 2,
            "properties": {
                "conf.settingsEditor.boolObjectSetting": {
                    |
                }
            }
        }
    ]
}
```

3. Trigger suggestions at `|`

**Bug**
There aren't suggestions for keys such as `type`

<img width="854" alt="Screen Shot 2022-01-25 at 2 17 34 PM" src="https://user-images.githubusercontent.com/12821956/151069372-02b6d8c5-df37-4c0d-b98a-d73ffc5eef05.png">

VS Code version: Code - Insiders 1.64.0-insider (Universal) (f93c69659de1a1466bd15e0f1c9f790e73be9208, 2022-01-25T08:42:38.986Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
salesforce-soql-editor|all|1.8.0
tsl-problem-matcher|amo|0.5.0
comment-tagged-templates|bie|0.3.1
docs-view|bie|0.0.9
emojisense|bie|0.9.0
folder-source-actions|bie|0.2.1
github-markdown-preview|bie|0.1.0
jsdoc-markdown-highlighting|bie|0.0.1
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
test-ext|bie|0.0.1
vscode-eslint|dba|2.2.2
dendron|den|0.79.0
dendron-paste-image|den|1.1.0
typescript-notebook|don|2.0.6
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
codespaces|Git|1.5.0
copilot|Git|1.7.4688
remotehub|Git|0.22.0
vscode-pull-request-github|Git|0.35.2022012509
vscode-drawio|hed|1.6.4
vscode-postfix-ts|ipa|1.9.4
latex-workshop|Jam|8.23.0
vscode-platform-specific-sample|joa|1.15.0
vscode-platform-specific-sample|joa|1.5.0
vscode-memfs|jri|0.0.3
vscode-position|jtr|1.1.2
template-string-converter|meg|0.6.0
git-graph|mhu|1.30.0
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.19.0
vscode-language-pack-de|MS-|1.64.4
python|ms-|2022.0.1742983688-dev
vscode-pylance|ms-|2022.1.4-pre.1
jupyter|ms-|2022.1.1001614873
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.215.0
remote-ssh|ms-|0.71.2022012519
remote-ssh-edit|ms-|0.71.2022012519
azure-account|ms-|0.9.11
hexeditor|ms-|1.9.3
js-debug-nightly|ms-|2022.1.2317
live-server|ms-|0.2.12
vscode-github-issue-notebooks|ms-|0.0.113
vsliveshare|ms-|1.0.5273
debugger-for-chrome|msj|4.13.0
vetur|oct|0.35.0
code-spell-checker|str|2.1.4
rest-book|tan|5.0.1
ayu|tea|1.0.5
luna-paint|Tyr|0.12.0
sort-lines|Tyr|1.9.1

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
A few other missing fields off the top of my head: `description`, `default`, `enum`

**Comment by rzhao271** [comment]
Code pointer for myself: `src\vs\workbench\api\common\configurationExtensionPoint.ts`
Changing this to be a debt item.

**Comment by rzhao271** [comment]
I'm unable to repro the issue now.
I also noticed that `type` comes from IJSONSchema. I wonder if that means you have to wait for the json languages extension to finish loading, first?
