### ISSUE TITLE
File nesting: Some files show twisty but have no content

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#141430]
Testing #141354

Version: 1.64.0-insider
Commit: f93c69659de1a1466bd15e0f1c9f790e73be9208
Date: 2022-01-25T08:41:29.626Z
OS: Linux x64 5.13.0-27-generic

- set "explorer.experimental.fileNesting.enabled": true
- open the vscode repo
- expand the `build/darvin` node. The `.ts` files have a twisty, but when expanding nothing to show
- 
![image](https://user-images.githubusercontent.com/6461412/150996323-1b54e464-146f-4525-8230-6013707fb1dd.png)

The `.js` are filtered in the tree. It would be nicer to not show the twisty then.

**Comment by JacksonKearl** [comment]
I figured it was nice to have some indication that there are some other files, but they aren't being shown at the moment. Similar to how we can visually "open" a folder that only contains hidden files. Maybe a setting?
