### ISSUE TITLE
File nesting: setting hover swallows `$(capture)`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#141439]
Testing #141354

Open the hover in the JSON settings

![image](https://user-images.githubusercontent.com/6461412/151004787-d1da19b2-ed36-40ea-ac2c-452da22471f2.png)

Note the "``". It should say `$(capture)` which needs to be escaped as this is the syntax of codicons.

**Comment by JacksonKearl** [comment]
Do you know how I'd properly escape that? I tried `\\$(capture)` with no luck.
for now using zero width space:
```
`$\u200b(capture)`
```
but I don't like how this may end up copy/pasted
