### ISSUE TITLE
Reconsider "Most Recent" wording

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#141419]
Testing #141342

> Most Recent refers to the link closest to the cursor position.

No string feelings but the TPI itself made me file this issue. If above explanation is needed than that might be a since of bad naming? So how about "Open closest/nearest link" or "Open last link" (last allows for interpreting it as time/recency and proximity-value)

**Comment by Tyriar** [comment]
Open Last Link is nice and concise 👍
