### ISSUE TITLE
Order of views in different windows

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#141438]
Testing #141355

- 2 open windows.
- Moved "Docker: Images" to Side Panel in first window.
- Opened Side Panel in second window.
- Moved "Debug Console" to side panel in first window, taking the top half from "Docker: Images".
- Second window shows the reverse order: "Docker: Images" in top half, "Debug Console" in bottom half. 🐛 

Maybe triggered by the above: Reloading the first window does not remember the Side Panel was shown and flips the order of the views to the one of the second window.

**Comment by sbatten** [comment]
I think I've determined this is out of scope after investigating. We never sync view order across open windows and will try to reorder on restart. The second issue already has an open ticket.
