### ISSUE TITLE
Splitting terminal moves prompt up

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#141403]
Testing #141357
![Recording 2022-01-25 at 12 39 09](https://user-images.githubusercontent.com/900690/150970351-6848ef3e-8c7a-441e-88ed-6a9c7cc49720.gif)

**Comment by Tyriar** [comment]
We'll need to repro on mac and look at the sequences to verify whether this is an issue or we're going the right thing.

**Comment by Tyriar** [comment]
I think this is working as designed since it's just padding on the top, however we could check the location of the terminal view and if it's on either side, top align the terminal instead of bottom aligning it.
