### ISSUE TITLE
Running an empty command reports as the last command run

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#141498]
Testing #141339

1. Write `echo hi` in powershell
2. Hint enter several times
3. In recent commands, observe duplicates of the last command even though nothing was run

![image](https://user-images.githubusercontent.com/2230985/151069082-998a10bd-d859-4231-9f8c-be88dc10eb11.png)

**Comment by Tyriar** [comment]
This is https://github.com/microsoft/vscode/issues/141180
