### ISSUE TITLE
New move to side panel behavior - don't show again

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#141422]
Testing #141356

As of right now the deprecation warning appears every single time one of the old commands is being invoked. While I do understand that we try to get the deprecation message across, I am wondering if the dialog should have a button for "don't show this again".

**Comment by sbatten** [comment]
My hesitation is that someone hits don't show again and eventually these commands do nothing and they are more confused. They currently have a "Don't show again" option which is to use a different key binding.

**Comment by sbatten** [comment]
we reverted all of this
