### ISSUE TITLE
Debug freeze on large data set

### ISSUE THREAD

**Issue by T1KK3S** [Microsoft/vscode#14144]
While using VS Code Insiders, my debugger freezes when hitting a breakpoint.

Clicking on "**continue**" does not work anymore and I, then, have to either hit "**stop**" or close VS code altogether. Note that I am using the **insider** edition.
Is anyone having this issue too?

After some time (say 5 minutes) I get following error:
**Cannot read property onDidStop of null** (I do not have such a property in my code, it is the IDE)

and

**Debug adapter process has terminated unexpectedly**

Then, my debug session is stopped. 

**note**
I do not have this behaviour in the stable version (not insider)

See screen captures:
![vscfreezeoutput](https://cloud.githubusercontent.com/assets/20314637/19593060/f72f1dae-977e-11e6-8981-054219200e25.PNG)
![vscfreeze](https://cloud.githubusercontent.com/assets/20314637/19593059/f72cf04c-977e-11e6-8059-f790722abe22.PNG)

**Comment by T1KK3S** [comment]
consistently, that's why I was doubting it'd be my nodeJs version... Especially since the stable version does not show this behaviour at all

**Comment by roblourens** [comment]
Is this a project that you can share with us?

**Comment by T1KK3S** [comment]
I'm afraid not...

**Comment by roblourens** [comment]
Then it would be useful if you could create a repro that breaks insiders but not stable.
