### ISSUE TITLE
Git out of sync

### ISSUE THREAD

**Issue by roroland** [microsoft/vscode#141509]
Issue Type: <b>Bug</b>

I work on two machines (Windows 10 with WSL and Mac), when switch to my Windows pc any repository I download that I share with the Mac system is showing on VS code uncommited changes but in VS code terminal it says everything is up to date.
I asumed it was something with the convertion between LF and LCRF ending lines, but after change my settings and fix end lines the issue remains ( git add --renormalize .)

If I made a commit in VS code git UI the VS code terminal shows pending files. If I then add pending files via VS terminal then the UI show uncommited files.... everything is out of sync.

![sync1](https://user-images.githubusercontent.com/200220/151076764-536f5280-94dc-4392-b5a7-6e303dd8325c.PNG)

I've tried on several repositories wit hthe same issue, it doesn't happens when I work on VS code under Mac

Any idea how can I fix this ? Please I'm a bit desperate with this issue. Thanks

GIT CONFIG

[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
        ignorecase = true
        autocrlf = false
[remote "origin"]
        url = git@github.com:roroland/aes.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
        remote = origin
        merge = refs/heads/main

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (26.56GB free)|

|Process Argv|--crash-reporter-id 5a9bd907-41b7-457d-b58b-04c4d3fd5f0d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
scss-lint|ada|0.1.10
codesnap|adp|1.3.4
project-manager|ale|12.4.0
html-class-suggestions|And|1.1.1
vscode-color|ans|0.4.5
npm-intellisense|chr|1.4.0
vscode-svgviewer|css|2.0.0
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
jquerysnippets|don|0.0.1
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
vscode-optimize-images|fab|1.1.1
auto-rename-tag|for|0.1.9
ginfuru-vscode-jekyll-syntax|gin|0.1.1
vscode-jekyll-snippets|gin|0.9.3
vscode-auto-open-markdown-preview|hnw|0.0.4
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
latte|Kas|0.18.0
vscode-gist|ken|3.0.3
vscode-liquid-snippets|kil|2.0.3
vscode-autoprefixer|mrm|3.0.1
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.19.0
vscode-language-pack-es|MS-|1.63.3
vscode-edge-devtools|ms-|1.4.2
remote-wsl|ms-|0.63.13
atom-keybindings|ms-|3.0.9
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
language-liquid|nei|0.1.1
vetur|oct|0.35.0
css-grid-snippets|oha|0.0.5
vscode-html-scss|P-d|0.0.42
vscode-phpcbf|per|0.0.8
live-sass|rit|3.0.0
LiveServer|rit|5.7.4
nunjucks|ron|0.3.0
vue-vscode-snippets|sdr|2.2.1
autoimport|ste|1.5.4
material-theme|zhu|3.13.16
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30424895
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30416617
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by lszomoru** [comment]
@roroland, sorry for not getting back to you on this until now. You mention in your description that you are using Windows 10 with WSL, though as far as I can tell from your screenshot you are not connected to WSL. Is that correct? Are you able to reproduce the issue when you open the folder/workspace without WSL? 

The SCM viewlet renders the list of changes based on the output of `git status -u`.
Could you run that command in the terminal and share the output? Thank you!
