### ISSUE TITLE
Can't differentiate file specs for cell output when doing things like compare...

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#141590]
1. Open a notebook that uses pandas (pandas is not required, but is just what I used as part of this real-world scenario. I was trying to compare the differences between "help(df)" and "df?"
2. Run this code in a cell:
```python
import pandas as pd
df = pd.DataFrame()
```
3. Then run two additional cells:
```python
help(df)
``` 
and
```python
df?
```

4. Open each of the latter cell outputs as a separate text file using the "in a text editor" link, and ensure both are available as separate tabs.
5. Invoke the command "Compare Active File With..."

You'll see at least 3 copies of the ipynb file that you started with. Here's an example:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/11685408/151225434-fd63c903-3157-4f75-8899-e05265b96a1f.png">

While it's somewhat obvious which file is the real ipynb, the 2nd two are not as they have the exact same title. If possible it would be nice to be able to differentiate them somehow. Of course, I suppose that saving them as new files could be a workaround.

**Comment by rebornix** [comment]
It's quite challenging to tweak the name of the output files (as there isn't an easy to help identify a cell output), we will recommend to use scrollable output once it's well polished.

**Comment by rebornix** [comment]
It's quite challenging to tweak the name of the output files (as there isn't an easy to help identify a cell output), we will recommend to use scrollable output once it's well polished.
