### ISSUE TITLE
No error shown when inlay hint command from context menu doesn't work 

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#141588]
Testing #141166

Repro steps:
- Add a non-existent command to one of the `InlayHintLabelPart` objects in https://github.com/jrieken/test-inlayhints (or mistype the name of a command)
- Make sure the label part also has a source location
- Display the context menu for an inlay hint (on my mac it's ctrl + click), and click on the command
- Notice that there is no error prompt shown

Notes:
- The error is shown in the developer tools
- When the inlay hint only contains a command (no source location), an error message is shown

**Comment by hediet** [comment]
I'm not so sure if the commit fixes the described issue (and if the commit even has an effect).

Key of the descibed issue is:
> Make sure the label part also has a source location

But the code is still like this:
```ts
if (part.location) {
    // ...
} else if (languages.Command.is(part.command)) {
    // ...
}
```

Thus, if `location` is set, `command` is ignored.

The issue also describes, that even before the fix an error was shown when `location` was not set.

**Comment by jrieken** [comment]
When `location` is set then the `command` moves into the context menu and when invoking those no error handling was done.
