### ISSUE TITLE
Cannot sign in to sync setting

### ISSUE THREAD

**Issue by Kritiqual** [microsoft/vscode#141571]
## Step to reproduce:
1, Click on "Account" icon on the bottom-left of vscode
2, Click on "Turn on setting sync"
3, Choose "Sign in with Github"
4, Nothing happened

## Expected behaviour
Open browser to sign in

## Result behaviour
Nothing happened and after a while, the procedure is cancelled

## More information
OS: Arch Linux (5.16.2)
Vscode version: 1.63.2

**Comment by sandy081** [comment]
May I know What you mean by nothing happened? You are not able to sign in?

**Comment by Kritiqual** [comment]
Yes, normally when I choose "Sign in with Github", vscode will open browser for me to sign in but, now it's does nothing (it not open browser for me). I have tried other method (Sign in with Microsoft), but no result. Idk why but after a couple of system reboot, it normal again, pretty weird
