### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes. Please consider to open a bug report.

### ISSUE THREAD

**Issue by tonywaterman** [Microsoft/vscode#14159]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. When opening up VS code I get an error continuously appearing an disappearing in a dropdown. It appears for a second, disappears, then appears again. Like a blink tag. Very annoying.

[Window Title]
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes. Please consider to open a bug report.

[Main Instruction]
Happens with the last update. This appears to be a random issue

[Content]

Version 1.6.1
Commit 9e4e44c19e393803e2b05fe2323cf4ed7e36880e
Date 2016-10-13T16:21:53.542Z
Shell 1.3.7
Renderer 52.0.2743.82
Node 6.5.0
![image](https://cloud.githubusercontent.com/assets/6731450/19600439/103f889e-9773-11e6-88c0-5df69fa528e9.png)

[OK]

**Comment by waderyan** [comment]
@tonywaterman thank you for opening this issue. Can you look at this [issue](https://github.com/Microsoft/TypeScript/issues/10735) and comment there? We are seeing many of the same issues that you have observed. Any insights into tracking this down would be much appreciated.
