### ISSUE TITLE
Can not surround strings with backtick (`)

### ISSUE THREAD

**Issue by AshkanLaei** [microsoft/vscode#141543]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- OS Version: Linux x64 5.16.1-arch1-1

Steps to Reproduce:

1. Open a new `.js` file and type something
2. Try to make it a string by selecting it and pressing `"` (it works)
3. Now try to do the same by pressing <code>`</code> (doesn't work)

Template Literals are an important part of javascript programming language and enclosing strings with backticks is normal.

**Comment by gjsjohnmurray** [comment]
Works for me on current release (1.63.2), so maybe you should update your version:

![junk](https://user-images.githubusercontent.com/6726799/151154614-1bdad793-58ef-4068-afa8-b64195615316.gif)

Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by AshkanLaei** [comment]
I'm so sorry, I made a mistake.
It works in js files for me too, but **it doesn't work in HTML files (inside `script` tag)**.
How can I fix that?

**Comment by aeschli** [comment]
```
<head>
    <script>
        var x = text
    </script>
</head>
```
- select `text`, press backtick. Should surround the text with backticks.

https://github.com/microsoft/vscode/blob/8b5368ec42eff55b3c67decb15b39ff9fa46ef88/src/vs/editor/contrib/wordOperations/browser/wordOperations.ts#L344

could use the language at the position, not the model language.
