### ISSUE TITLE
vscode doesnt support c blah blah blah

### ISSUE THREAD

**Issue by GH0STH4CKER** [microsoft/vscode#141565]
VS Code doesn't ship support for C++ out of the box and it's provided by extensions and (supported) compiler of your choise.

Please see steps https://code.visualstudio.com/dges/cpp and https://code.visualstudio.com/docs/cpp/introvideos-cpp for setup steps and other information on how to use C++ in VS Code.

_Originally posted by @IllusionMH in https://github.com/microsoft/vscode/issues/134181#issuecomment-931162887_

**Comment by SteelBlueVision** [comment]
404 on first link!

**Comment by Tyriar** [comment]
I don't understand why you would create this issue to just restate what was told to you before. C++ is not supported out of the box in VS Code and I doubt will ever be. Any questions related to C++ should be routed to the C++ extension team https://github.com/microsoft/vscode-cpptools
