### ISSUE TITLE
Can't see that a code cell is collapsed

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#141579]
Testing #141222.

When a code cell as a first line that causes a horizontal scrollbar and you collapse the cell, there is no visual indication anymore that the cell is collapsed.

<img width="726" alt="image" src="https://user-images.githubusercontent.com/4674940/151217298-87d5f1d9-8a43-484f-96d8-e19306328fca.png">

**Comment by roblourens** [comment]
Isn't it enough that you don't have the editor border/background color? If you hover, you will get a tooltip hint to double click. What else do you want to see?

**Comment by roblourens** [comment]
For reference - narrower cells get the `...` button

![image](https://user-images.githubusercontent.com/323878/153314190-696dcfb0-e773-4d46-a53d-d95ddc66edca.png)

**Comment by roblourens** [comment]
We could

- Make sure the `...` is always visible - it would float to the right side
- Show some other decoration, icon, or color to indicate that a cell is collapsed

**Comment by roblourens** [comment]
Yeah, but the alternative is adding more space between cells which I also don't want to do
