### ISSUE TITLE
Blue line in the middle of the cell

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#141505]
Testing #141222

There seems to be a blue line appearing in the middle of Markdown cells after I click near the bottom edge of them:

![Screenshot](https://user-images.githubusercontent.com/7199958/151071410-972af876-1b01-4341-bc0d-6d28b54e0a96.PNG)

**Comment by roblourens** [comment]
Yeah, you focused the status bar. Doesn't look great but is by design basically.
