### ISSUE TITLE
Old auto replies included in new terminal

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#141530]
Testing #141341

After creating a new terminal (type doesn't matter), a previous setting value still is included.

![image](https://user-images.githubusercontent.com/12818376/151109580-4f1caa1f-a99b-42d1-b9bb-f157bc1162ae.png)

I had earlier had a setting value of:

```
    "terminal.integrated.autoReplies": {
        "Terminate batch job (Y/N)": "Y\r",
        "blah": "_blah_"
    }
```

The active terminal when the setting value was removed don't have the old value.

**Comment by Tyriar** [comment]
This seems to be working fine now after the `null` change was added.

**Comment by kimadeline** [comment]
Steps I took:
- added the following to my settings.json:
```json
    "terminal.integrated.autoReplies": {
        "blah": "_blah_"
    }
```
- Opened a terminal and verified that typing `blah` resulted in `blah_blah_`
- Changed the settings value to `"blah": "what is it"`
- Opened a new terminal and verified that typing `blah` resulted in `blahwhat is it`
