### ISSUE TITLE
LiveServer+DevTools

### ISSUE THREAD

**Issue by KimOleg** [microsoft/vscode#141554]
Issue Type: <b>Bug</b>

Good afternoon. Please tell me what can happen in the following situation: I open an HTML/CSS file in Visual Studio Code. I'm launching a Live Server. In the browser (Google Chrom), a screen opens that draws my file. I run DevTools there.I make changes to the code using VS Code and at the moment of saving the file, the screen in the browser flies off, the message "No Internet connection" appears, although it is there. What to do? Sincerely, Oleg

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by hediet** [comment]
This sounds like an issue with the Live Server extension (rather than an issue with VS Code). Please file an issue for that extension.

If you can pinpoint your problem to a bug in VS Code, please create an new issue.

Thanks!
