### ISSUE TITLE
[Settings Sync] Settings merge conflict with diff highlighting a change when nothing is different

### ISSUE THREAD

**Issue by MatthewCushing** [microsoft/vscode#141584]
Issue Type: <b>Bug</b>

1. On my personal Mac computer (14" M1 Max), I deleted the `editor.wordSeparators` setting.

2. On my other computer (Windows 10 Pro), I then received a notification in VSCode that there was a merge conflict

3. I decided to check what the merge conflict was and chose the option to open up the diff

4. I was presented with "Accept Remote" and "Accept Merges" for the diff and there was only a single line highlighted for the diff (nothing to do with the setting I actually changed)

5. This single highlighted line was no different on either side of the diff comparison.  It highlights the letters `lab` in the word `Scrollable`.  It is spelled identically on either side.  I have provided a screenshot to show what I mean.

*Not a big issue on my end.  However, if this is a bug where diffs are being calculated incorrectly, I figure it might help.*

![image](https://user-images.githubusercontent.com/10594068/151219399-acada61d-50d3-4628-9ce3-cbb337e32f2e.png)

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.96GB free)|
|Process Argv|--crash-reporter-id d7a3bc0c-a7d8-40bb-981e-4105b2c9687e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (82)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
android-dev-ext|ade|1.3.2
js-quick-console|Aha|0.0.3
spaces-inside-braces|Air|0.4.0
TabOut|alb|0.2.1
project-manager|ale|12.4.0
vscode-sqlite|ale|0.14.0
ng-template|Ang|13.1.1
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-intelephense-client|bme|1.8.0
npm-intellisense|chr|1.4.0
gitignore|cod|0.7.0
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
vscode-faker|dee|1.5.0
emulate|Die|1.6.0
es7-react-js-snippets|dsz|4.1.0
gitlens|eam|11.7.0
vscode-npm-script|eg2|0.3.24
vscode-great-icons|emm|2.1.82
eppz-code|epp|1.2.52
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.1.0
git-project-manager|fel|1.8.2
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
auto-using|Fud|0.7.15
kotlin|fwc|0.2.23
html-slim-scss-css-class-completion|gen|1.7.8
mayukaithemevsc|Gul|3.1.0
helium-icon-theme|hel|1.0.0
vscode-edit-csv|jan|0.6.4
csharpextensions|jch|1.3.1
vscode-nuget-package-manager|jmr|1.1.6
vscode-peacock|joh|4.0.0
vscode-styled-components|jpo|1.6.6
docomment|k--|0.1.30
comment|kar|7.0.7
theme-karyfoundation-themes|kar|25.2.3
pop-n-lock-theme-vscode|Lux|3.32.7
vscode-autohotkey-plus-plus|mar|2.8.1
rainbow-csv|mec|2.0.0
php-namespace-resolver|Meh|1.1.8
vscode-language-babel|mgm|0.0.35
fluent-icons|mig|0.0.16
react-native-styled-component-snippets|mil|1.0.1
theme-monokai-pro-vscode|mon|1.1.20
vscode-duplicate|mrm|1.2.1
vscode-scss|mrm|0.10.0
azure-pipelines|ms-|1.195.0
vscode-docker|ms-|1.19.0
csharp|ms-|1.24.0
azure-account|ms-|0.9.11
powershell|ms-|2021.12.0
vsliveshare|ms-|1.0.5273
one-dark-theme|msk|1.14.2
rose-pine|mvl|2.0.0
color-highlight|nau|2.5.0
vetur|oct|0.35.0
unity-toolbox|pix|1.0.6
material-icon-theme|PKi|4.12.1
polacode|pnp|0.3.4
vscode-commons|red|0.0.6
vscode-xml|red|0.18.2
LiveServer|rit|5.7.4
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.6.1
mdx|sil|0.1.0
shader|sle|1.1.5
code-spell-checker|str|2.1.4
ayu|tea|1.0.5
unity-tools|Tob|1.2.12
sort-lines|Tyr|1.9.1
unity-debug|Uni|3.0.2
vscodeintellicode|Vis|1.2.16
vscode-icons|vsc|11.8.0
vim|vsc|1.21.10
vscode-import-cost|wix|2.15.0
vscode-mdx-preview|xyc|0.3.3
markdown-pdf|yza|1.4.4
json|Zai|2.0.2

(15 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
I think it seems like the letter `W` in setting `cSpell.userWords` is not same character `W` and hence it is highlighted on right side but not on left side. Can you please check fixing the letter `W` there and see if the problem occurs?

**Comment by sandy081** [comment]
Closing this as there is no enough information. Please reopen if you are able to reproduce this and provide necessary infi
