### ISSUE TITLE
None of the extensions are working.

### ISSUE THREAD

**Issue by amanator** [microsoft/vscode#141541]
Issue Type: <b>Bug</b>

After new update VS Code ectensions are not working and showing the error "Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.."

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.43GB free)|
|Process Argv|E:\\Web Development\\React\\newsapp\\backend --crash-reporter-id 73c65371-ef24-4bb0-a9e4-cbd4b9c652e5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.8.0
doxdocgen|csc|1.3.2
es7-react-js-snippets|dsz|4.1.0
prettier-vscode|esb|9.1.0
code-runner|for|0.11.6
vscode-pull-request-github|Git|0.34.3
better-cpp-syntax|jef|1.15.10
python|ms-|2021.12.1559732655
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.0
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5273
vsliveshare-audio|ms-|0.1.91
material-icon-theme|PKi|4.12.1
vscode-thunder-client|ran|1.10.0
java|red|1.3.0
LiveServer|rit|5.7.4
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.16
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30424896
pythonvs932:30410667
wslgetstarted:30426333
vscop804:30404766
vscop341:30404997
vsclayoutctrt:30425946
vsrem710cf:30416617
vscop841:30424583
vsbas813:30426126

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command to investigate which extensions are causing this.
