### ISSUE TITLE
filenamePattern specific priority for custom editors

### ISSUE THREAD

**Issue by yuyichao** [microsoft/vscode#141562]
Right now, the priority seems to be a property of the editor as a whole rather than for different extensions. However, for my editor, we may want to use either a generic extension (json) or a more specific one (haven't decided on that yet actually). I'd like to set my editor as option for the generic extension (json) but the default for the more specific one so it would be nice to be able to set different priority for different patterns for the same editor.

**Comment by go-commit-code** [comment]
It doesn't look like this will get enough upvotes.

In case anyone is looking for a workaround,
you can do this by registering the same editor twice using different ID's, like so:

```json
"customEditors": [
	{
		"viewType": "my-extension.myCustomEditor",
		"displayName": "My Custom Editor",
		"selector": [
			{
				"filenamePattern": "*"
			}
		],
		"priority": "option"
	},
	{
		"viewType": "my-extension.myCustomEditorDefault",
		"displayName": "My Custom Editor",
		"selector": [
			{
				"filenamePattern": "*.something"
			}
		]
	}
]
```
```typescript
export function activate(context: ExtensionContext) {
	let disposable;

	disposable = window.registerCustomEditorProvider('my-extension.myCustomEditor', new MyCustomEditor(context));
	context.subscriptions.push(disposable);

	disposable = window.registerCustomEditorProvider('my-extension.myCustomEditorDefault', new MyCustomEditor(context));
	context.subscriptions.push(disposable);
}
```

Remember to include both editor ID's in activation events:
```json
"activationEvents": [
	"my-extension.myCustomEditor",
	"my-extension.myCustomEditorDefault"
]
```

And if you reference an editor ID in a `when` clause, you might want to include both ID's:
```json
"commandPalette": [
	{
		"command": "my-extension.myCommand",
		"when": "activeCustomEditorId == my-extension.myCustomEditor || activeCustomEditorId == my-extension.myCustomEditorDefault"
	}
]
```
