### ISSUE TITLE
Question: Notification channels for upcoming releases?

### ISSUE THREAD

**Issue by uberDoward** [microsoft/vscode#141559]
Is there a mailing list or any other communication channel where one could be notified of upcoming releases?

Currently, I'm checking in daily on the pinned issues.  Thought I'd ask if there's a communications mechanism I'm unaware of.

Thanks!

**Comment by TylerLeonhardt** [comment]
Unfortunately, we don't have a mailing list. That said...

You could watch for just releases so you get notifications when they occur:

https://www.jessesquires.com/blog/2020/07/30/github-tip-watching-releases/

You could join the vscode slack:

https://aka.ms/vscode-dev-community

Where someone else will almost certainly post about it.

You could write a tiny script that makes a request to GitHub's REST API for Releases and have it send you a toast in the machine you're on:

https://docs.github.com/en/rest/reference/releases#get-the-latest-release
