### ISSUE TITLE
Terminal shell integration doesn't work on remote windows

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#141599]
Does this issue occur when all extensions are disabled?: Yes/No

* Version: 1.64.0-insider (user setup)
* Commit: 45060913204279d4ecfe0575ca69d68211fb3798
* Date: 2022-01-26T05:17:50.284Z
* OS: Windows_NT x64 10.0.22000
* WSL2 (ubuntu, with zsh shell)

Follow up on https://github.com/microsoft/vscode/issues/141339#issuecomment-1022554046

**Comment by meganrogge** [comment]
Just to be sure, you changed the directory and also ran some commands, correct?

You also should've seen
![Screen Shot 2022-01-26 at 4 09 59 PM](https://user-images.githubusercontent.com/29464607/151255417-1c97a00f-0b7e-4462-96f0-31035b4dac1f.png)
in the terminal. Did you?

**Comment by Tyriar** [comment]
Can repro at least one issue here, we're injecting a Windows path:

![image](https://user-images.githubusercontent.com/2193314/151271102-4877ab6a-1b0d-4985-9cc5-729e4d5c5c94.png)

**Comment by Tyriar** [comment]
This is a bit of a risky change, I think we probably need to move the shell integration arg injecting over to the server so `execInstallFolder` uses the right OS. Or refactor how the function is organized to support pulling that path over from the other side if needed.

**Comment by Tyriar** [comment]
I think this breaks arg injection on all remotes, except for the test resolver which we tested against :trollface:

**Comment by meganrogge** [comment]
Also worked on ssh

**Comment by Tyriar** [comment]
@meganrogge oh shell integration does on ssh? Are you sshing into localhost as that should work?

**Comment by meganrogge** [comment]
Yes it does I'm ssh'ing into localhost
![Screen Shot 2022-01-27 at 1 30 28 PM](https://user-images.githubusercontent.com/29464607/151430192-f9e1695f-1891-4fcb-9a21-7989f9928a9f.png)

**Comment by theGirrafish** [comment]
I believe I'm getting a similar issue when enabling the new experimental shell integration setting.
It seems it's searching for a file local to my drive although I'm currently running the terminal in a remote SSH window.
Any new terminal I open is met with the following:

```
zsh:1: no such file or directory: /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-zsh.sh
```

**Comment by connor4312** [comment]
I still hit this. The host OS is a Windows system with Powershell 7, using remote SSH to connect to a Linux machine (that should use zsh). I just have `terminal.integrated.defaultProfile.windows: Powershell` in my settings.

**Comment by connor4312** [comment]
This seems to happen whenever I click the "+" button https://memes.peet.io/img/22-02-0f460379-9dfb-4c56-829f-78e33458ef05.mp4

**Comment by Tyriar** [comment]
Can repro, I wasn't seeing it because I had `"terminal.integrated.defaultProfile.linux": "bash"` set

**Comment by Tyriar** [comment]
I see this in the log which is wrong:

```
WARN Shell integration cannot be enabled when custom args undefined are provided for pwsh.exe.
```

Cause is related to this debt item: https://github.com/microsoft/vscode/issues/143965

**Comment by Tyriar** [comment]
That issue is caused because we currently only resolve backend OS/remote authority after the process is created.

**Comment by Tyriar** [comment]
I pushed a fix but could only test Windows -> Windows, make sure to verify on Windows -> non-Windows (eg. WSL) or the other way around.

**Comment by joyceerhl** [comment]
Shell integration works for me over Remote-SSH with the following setup:
- Host OS: Windows, Powershell 7
- Remote OS: Linux

![image](https://user-images.githubusercontent.com/30305945/156065305-ee4aa33d-4159-45e2-8cca-7eae329824e1.png)

**Comment by connor4312** [comment]
Verified it works here too 🎉

**Comment by joyceerhl** [comment]
I just noticed the following in the logs when using Remote-SSH with shell integration enabled 

```
 WARN Shell integration cannot be enabled when custom args -c,wget --version > /dev/null
if [ $? -eq 0 ]
then
	wget --connect-timeout=7 --tries=1 --dns-timeout=7 -q  -O - http://<redacted>/latest/meta-data/instance-id
else
	curl --version > /dev/null
	if [ $? -eq 0 ]
	then
		curl --connect-timeout 7 -s  http://<redacted>/latest/meta-data/instance-id
	fi
fi
exit 0 are provided for sh.
```

Is this known/expected @Tyriar?

**Comment by Tyriar** [comment]
@joyceerhl yes that's expected as a warning just to call out if someone is looking that shell integration couldn't be enabled. I just improved that warnings format in a pr I have out as well.
