### ISSUE TITLE
Explorer undo prompt should be Yes/No

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#141555]
Testing #141351

I think the dialog should have Yes/No instead of Yes/Cancel since the prompt is asking the user a Yes/No question.

![image](https://user-images.githubusercontent.com/1704059/151163968-6f9305b2-998f-4251-9861-ae0bc1c766d8.png)

cc: @misolori in case there are guidelines about how to label buttons like these.

**Comment by JacksonKearl** [comment]
cc @alexdima seems the relevant line is here: https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/undoRedo/common/undoRedoService.ts#L1108-L1118

what do you think?

**Comment by alexdima** [comment]
:+1: Good suggestion.
