### ISSUE TITLE
"input" variables prevent compound configuration from launching more than one session

### ISSUE THREAD

**Issue by philippjbauer** [microsoft/vscode#141514]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: macOS 12.1 (ARM64)

I can't get more than two launch configurations to run at the same time. I can run the rest of the configurations afterwards and everything works (debugging, etc.). StopAll will also only close the two configs that were successfully launched.

I haven't found any mention in the documentation that this is limited to two launch configurations. I've only seen that two are used in every explanation or tutorial about this feature.

Steps to Reproduce:

1. Add multiple launch configurations in multi-root workspace inside of project roots.
2. Add launch configurations to compounds in .code-workspace file
3. Start debugging
4. Only two of the many compound configurations will run

Examples:

tasks.json

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "dotnet: build bc1",
            "detail": "Build the Bounded Context 1 WebAPI Project",
            "type": "shell",
            "command": "dotnet build -p:Config=Debug ./src/Presentation/WebAPI",
            "problemMatcher": ["$msCompile"],
            "presentation": {
                "echo": true,
                "reveal": "silent",
                "focus": false,
                "panel": "dedicated",
                "showReuseMessage": true,
                "clear": true
            }
        }
    ]
}
```

launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch API (Debug)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "dotnet: build bc1",
            "program": "${workspaceFolder}/src/Presentation/WebAPI/bin/Debug/net6.0/BoundedContext1.dll",
            "args": [],
            "cwd": "${workspaceFolder}/src/Presentation/WebAPI",
            "stopAtEntry": false,
            "serverReadyAction": {
                "action": "openExternally",
                "pattern": "\\bNow listening on:\\s+https?://\\S+:(\\S+)",
                "uriFormat": "http://localhost:%s/swagger"
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Debug"
            }
        }
    ]
}
```

Root.code-workspace
```json
{
    "launch": {
        "version": "0.2.0",
        "compounds": [
            {
                "name": "Launch Full (with Docker)",
                "configurations": [
                    "Launch WebUI",
                    {
                        "folder": "Bounded Context 1",
                        "name": "Launch API (Debug)"
                    },
                    {
                        "folder": "Bounded Context 2",
                        "name": "Launch API (Debug)"
                    },
                    {
                        "folder": "Bounded Context 3",
                        "name": "Launch API (Debug)"
                    }
                ],
                "preLaunchTask": "docker: up db/mail",
                "stopAll": true
            }
        ]
    }
}
```

**Comment by weinand** [comment]
@philippjbauer VS Code imposes no limit on number of launch configurations in compound config.

I've verified this with this simple example project:
[multifolderdebug.zip](https://github.com/microsoft/vscode/files/7941132/multifolderdebug.zip)

- unpack zip file
- in VS Code use "Open Workspace from file" to open workspace file `multifolderdebug.code-workspace` inside `multifolderdebug` folder
- switch to debug viewlet
- in debug config dropdown select and run "4 Debug Session"

Observe:
4 debug sessions:

<img width="1384" alt="CleanShot 2022-01-26 at 11 45 23@2x" src="https://user-images.githubusercontent.com/1898161/151149560-d383194c-1bdb-4f30-92d1-9cc2c3be766a.png">

**Comment by philippjbauer** [comment]
Thank you for taking a look at this @weinand 

After inspecting your configuration and some research in my own project I was able to isolate the culprit.

The problem arises when you try to make us of inputs in the launch configuration.

I created a demo for download, the process is the same as you described above.

[webdebug.zip](https://github.com/microsoft/vscode/files/7943243/webdebug.zip)

**Comment by weinand** [comment]
@philippjbauer thanks for the additional info.

I was able to create an even smaller repro without a multi-folder workspaces. 
[compound.zip](https://github.com/microsoft/vscode/files/7943618/compound.zip)

- unpack zip file
- in VS Code open the "compound" folder
- switch to debug viewlet
- in debug config dropdown select and run "Compound"

Observe: only one debug session starts

**Comment by xisui-MSFT** [comment]
@weinand @roblourens Is it possible to implement the input that allows blocking another input request until the first input has completed?

**Comment by roblourens** [comment]
Do you own the configuration resolver @alexr00? Is my solution correct or should the service guarantee correct behavior when calling into it multiple times simultaneously?

**Comment by alexr00** [comment]
@roblourens your solution looks good. The configuration resolver service doesn't currently make any guarantees about what will happen if it's called into multiple time simultaneously. 

I would also be fine with the change being in the configuration resolver service though. We can change it's behavior so that it does make that guarantee.

**Comment by weinand** [comment]
Yes, making the fix in the configuration resolver service sounds better.

**Comment by xisui-MSFT** [comment]
@roblourens This fix doesn't fully cover our scenario (tested in latest insiders).

This fixes `promptString` case, and yet we also prompt for input or quick pick in `resolveDebugConfigurationWithSubstitutedVariables`, which is not covered in this PR.

Is it appropriate to wait for `resolveDebugConfigurationWithSubstitutedVariables` as well?

**Comment by roblourens** [comment]
Good point. Yeah, I think that makes sense.

**Comment by xisui-MSFT** [comment]
@roblourens I guess we'll need Queue's for https://github.com/microsoft/vscode/blob/0f2239fc7c2703312928b6f7ff9ce6642d2e3354/src/vs/workbench/contrib/debug/browser/debugService.ts#L451 and https://github.com/microsoft/vscode/blob/0f2239fc7c2703312928b6f7ff9ce6642d2e3354/src/vs/workbench/contrib/debug/browser/debugService.ts#L472

Would you like to make the changes, or should I work on this?

**Comment by roblourens** [comment]
I can take care of it

**Comment by roblourens** [comment]
This gets a bit weird. Since one launch config can be calling into the variable resolver (the first fix) while the second is calling the extension config provider, we also need a queue that orchestrates those two things. Easiest fix is to start launch configs one at a time instead of kicking them off in parallel: https://github.com/microsoft/vscode/blob/b811724c2856c1c950c32d88489c464d5ee611ba/src/vs/workbench/contrib/debug/browser/debugService.ts#L357

and I'm not sure what other impacts that could have. Perf to some extent, probably.

So @TylerLeonhardt, I wonder whether we would ever consider queueing calls into the quick pick control so that invoking the quick pick while it is already visible would wait instead of cancelling the first one as it does currently. Example of what I'm talking about (but in my real situation it's an extension competing with code in core):

```ts
vscode.window.showInputBox({ prompt: 'message 1' });
vscode.window.showInputBox({ prompt: 'message 2' });
```

This extension code only shows one input box, while we could have the second wait for the first to complete. 

This could possibly be a breaking change for some extensions though, so it could be enabled with a flag.

**Comment by roblourens** [comment]
As an easy workaround, I can put a queue around calling into the vscode variable resolver and calling an extension debug config provider. But, putting a queue around two unrelated pieces of code seems to say that I'm solving the problem at the wrong level.

**Comment by xisui-MSFT** [comment]
Or maybe make them the same level by moving the resolve queue to https://github.com/microsoft/vscode/blob/0f2239fc7c2703312928b6f7ff9ce6642d2e3354/src/vs/workbench/contrib/debug/browser/debugService.ts#L455?

**Comment by TylerLeonhardt** [comment]
> So @TylerLeonhardt, I wonder whether we would ever consider queueing calls into the quick pick control so that invoking the quick pick while it is already visible would wait instead of cancelling the first one as it does currently.

Just to be clear. The two callers of the `showInputBox()` are in two different places right (core and extension)?

**Comment by roblourens** [comment]
Right

**Comment by TylerLeonhardt** [comment]
Ok I've not heard of any feature request like this but feel free to open one... I wonder if maybe instead Core could have concept of "important" quick picks that can't be stomped over by extensions.

**Comment by roblourens** [comment]
It can also go the other way. The problem is just that there are two async processes that have to run and show a quick input, and we need both of them to complete and not to get canceled by the other. Filed https://github.com/microsoft/vscode/issues/158433

I'll go with a workaround for now, so I'm not blocked, just figured I'd start the discussion

**Comment by xisui-MSFT** [comment]
@roblourens Sorry for the late reply. I tested this today and it works for our scenario. Thanks for the quick fixes!
