### ISSUE TITLE
Hitting the cell focus indicator of a collapsed cell

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#141587]
Testing #141222

See screen recording at https://cln.sh/bnodFl.

When a cell is not collapsed the cursor around the cell focus indicator is a pointer/arrow. When the cell is collapsed the cursor is the hand (for grabbing and dragging the cell) and I need to move very much to the left to actually have the cell focus indicator react to my mouse. I missed many times.

**Comment by roblourens** [comment]
Weird, the cursor should always be the hand regardless of collapse status, and that is how it is for me. You always see an arrow when the markdown cell is not collapsed?

**Comment by IanMatthewHuff** [comment]
I don't see the screen recording any more, but with the new changes this hit target feels pretty reasonable. And side by side I can very much see the point issue and that the target use to be much smaller.
