### ISSUE TITLE
terminal doesnt work. 

### ISSUE THREAD

**Issue by sylvia0703** [microsoft/vscode#141547]
We have written the needed data into your clipboard because it was too large to send. Plea
Issue Type: <b>Performance Issue</b>

I am  new to this. Failed to connect to the remote extension host server (Error: No remote extension installed to resolve codespaces.) 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: Yes
Fetching remote diagnostics for 'vscode-remote' failed: No remote extension installed to resolve codespaces.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (3.26GB free)|
|Process Argv|--crash-reporter-id ac7c16e4-9b08-4e56-964b-1972cd3e6e56|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'vscode-remote' failed: No remote extension installed to resolve codespaces.
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    87	 11052	code main
    0	    80	  3096	   extensionHost
    0	    82	  8460	   shared-process
    0	    66	 11448	     ptyHost
    1	    80	  9624	   issue-reporter
    0	   145	 10920	   window (defaultSettings.json - 96442009 [vscode-remote] - Visual Studio Code)
    0	    24	 13512	   crashpad-handler
    1	   129	 15036	   gpu-process
    0	    37	 15952	   utility-network-service
Fetching remote diagnostics for 'vscode-remote' failed: No remote extension installed to resolve codespaces.
```

</details>
<details>
<summary>Workspace Info</summary>

```

Fetching remote diagnostics for 'vscode-remote' failed: No remote extension installed to resolve codespaces.;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30424896
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710:30416614
vsbas813:30426126

```

</details>

se paste.

**Comment by Tyriar** [comment]
> No remote extension installed to resolve codespaces

It sounds like you need to install the codespaces extension. If installing that doesn't work I'd ask report to GitHub.

If you're just trying to get out of that state, ctrl+shift+n will create a new _local_ window that doesn't need Codespaces.
