### ISSUE TITLE
Unicode highlighting does not seem to respect application locale

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#141507]
Testing #141338

```
Version: 1.64.0-insider (Universal)
Commit: f93c69659de1a1466bd15e0f1c9f790e73be9208
Date: 2022-01-25T08:42:38.986Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0
```

* Verifying `Automatic VS Code Locale Detection`
* OS locale set to `en`

<img width="1438" alt="Screen Shot 2022-01-26 at 8 14 28" src="https://user-images.githubusercontent.com/964386/151075718-d28f9205-6544-4c5e-8c75-276fbf1b89d5.png">

**Comment by hediet** [comment]
For untrusted workspaces, all non-basic ascii characters are highlighted by default for security reasons.

---

~Are you sure that you have the default settings?~

~I cannot reproduce this on Windows:~
![recording](https://user-images.githubusercontent.com/2931520/151175394-af337db8-6ff6-4e96-af3b-2016ac2e78ef.gif)
