### ISSUE TITLE
BracketPairColorization is working wrong.

### ISSUE THREAD

**Issue by mertcandav** [microsoft/vscode#141560]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.63.2
- OS Version: Windows_NT x64 10.0.19044

![image](https://user-images.githubusercontent.com/54983926/151166223-650be900-ab8b-4012-828c-8804a5abf337.png)

Seen at image above, bracket pair colorization is working wrong.
I've only seen this issue when working with cpp.
Bracket match system is working done, look at the `for` block brace and real end brace of block, these brackets are matched and highlighted. Pair colorization probably doesn't use same engine, brackets matching can sometimes be wrong.

I have a guess on this.
![image](https://user-images.githubusercontent.com/54983926/151168235-fb532176-77e4-4175-8488-9ca348405552.png)
Seen at image above, bracket matching still working done. But pair colorization is wrong, why last `>` is pink?
This is first colorization issue and after that all colorizations is wrong. The problem may be caused by `<` and `>` matchings.

**Comment by hediet** [comment]
You seem to use a cpp language that configures `<`...`>` as bracket pair.
However, that does not work for C++, as you are using `std::wcout << ...` which confuses everything.
Please bug the author of that language-configuration.json to remove `<`...`>` as bracket pair.
