### ISSUE TITLE
What's the behaviour for conflicting/overlapping inlay hints?

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#141511]
Testing #141166

Not an issue, more of a question 🙂 

When using the sample at https://github.com/jrieken/test-inlayhints and writing `foobar`, only the inlay hint that was defined last is going to be displayed (when I type `foobar` only the second `bar` hint shows up). Is it expected behaviour?

**Comment by jrieken** [comment]
Nice catch - inlay hints do support this but the sample extension wasn't doing this properly. Basically, when seeing `foo` or `bar` it would advance by 4 instead of 3 characters and therefore "touching" foos and bars wouldn't work. I have pushed a fix
