### ISSUE TITLE
Expose/Support when clause `*InputIsInLastPosition` for not only scmInput

### ISSUE THREAD

**Issue by Binly42** [microsoft/vscode#141527]
Currently, there are two when clause to detect the cursor position for scmInput:
- scmInputIsInFirstPosition
- scmInputIsInLastPosition

with them, we can define shortcuts like:
```json
    {
        "key": "down",
        "command": "list.focusDown",
        "when": "editorLangId == 'scminput' && scmInputIsInLastPosition && scmRepository && !suggestWidgetVisible",
    },
```

However, other input-box (like keybindings, find-widget, etc) do not support similar things.
It would be great to support them.

**Comment by Binly42** [comment]
I find that there currently is also no `editorLangId` attribute in ContextKeys of other input-box.
Maybe they are in different implement?

Or possibly because a bug of the `inspectContextKeys` (https://github.com/microsoft/vscode/issues/141236) ?

**Comment by sandy081** [comment]
Not all input boxes are same. SCM input box has editor embedded and hence it has editor contexts. It has editor embedded because it needs editor features, where as others do not need.
