### ISSUE TITLE
Add configurable delay between input and errors highlighting

### ISSUE THREAD

**Issue by nyan-cat** [microsoft/vscode#141549]
I'm not sure whether this feature request should be addressed to VS Code itself, or to particular syntax plugin authors. Anyway, this could be useful in general for all syntax plugins. Also I couldn't find if there is already a solution for this issue.

When I type some code (in my case I write Elm application), VS Code checks and validates syntax right away, after every character inputted, in a fraction of a second, and of course, the code is incorrect until I complete current statement. As a result - red underscore appears and disappears during input. Half screen flashes with red like a new year tree. That's annoying.

It would be nice to have some option to get some delay between last character inputted and error highlighting. Just a couple of seconds of delay would make life much comfortable.

Update: I think not just inputted character, but any key pressed should restart delay timer. Because, for example, you could press arrow keys to move caret around. In such case you're not inputting anything, but the delay timer should be restarted. Also I think syntax checking should be performed immediately after you do "Save" / "Save all".

**Comment by sandy081** [comment]
Diagnostics are generated by the extension and VS Code just displays them in the UI. I think this depends on the language smartness. So, please file the issue against the extension that is generating these.
