### ISSUE TITLE
listen to cwd capability events in TerminalLinkManager 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#141597]
then could remove this code from TerminalInstance

https://github.com/microsoft/vscode/blob/6b2e1e90eb42e30e6dd984fa63547271d2fed822/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1510-L1512

https://github.com/microsoft/vscode/blob/6b2e1e90eb42e30e6dd984fa63547271d2fed822/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L365-L367

**Comment by Tyriar** [comment]
Part of this is to fill in `NaiveCwdDetection` and leverage `onFirstListenerAdd`/`onLastListenerRemove` to avoid trigger `lsof` unless it's needed.

**Comment by Tyriar** [comment]
Reopened for this comment: https://github.com/microsoft/vscode/commit/5cb6ea993449cfc39202d37ebd9613c02530b7e1#r65724018

**Comment by Tyriar** [comment]
This is already done
