### ISSUE TITLE
CSS Formatter

### ISSUE THREAD

**Issue by Samyak-Bumb** [microsoft/vscode#141542]
Please create a **Built-In CSS Formatter**. I don't want to Download Extension Because Extension have many files, storage & takes tooo much time to load the extension.

Thank You

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode/issues/19166. See https://github.com/microsoft/vscode/issues/19166#issuecomment-409928738 for why we can't cover all functionality for all languages.
