### ISSUE TITLE
Overlapping text in notebook editor find bar

### ISSUE THREAD

**Issue by devinvalenciano** [microsoft/vscode#141515]
Testing #141346

Version: 1.64.0-insider (user setup)
Commit: f93c69659de1a1466bd15e0f1c9f790e73be9208
Date: 2022-01-25T08:42:41.055Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Open notebook in latest insiders
2. Search for text that exceeds default length of search bar
3. Input text overlaps the "Aa" icon

<img width="332" alt="image" src="https://user-images.githubusercontent.com/1389808/151092832-94e0603c-a8e4-4dd3-b73b-1e30313aaa22.png">

**Comment by rebornix** [comment]
We should expand the default width of the notebook find widget and consider supporting find widget expansion (https://github.com/microsoft/vscode/issues/141516) like the editor find widget.
