### ISSUE TITLE
Impossible to identify that a collapsed markdown cell was folded

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#141581]
Testing #141222

A collapsed, **unfolded** markdown cell:
<img width="695" alt="image" src="https://user-images.githubusercontent.com/4674940/151218210-8ee09c7b-d013-4748-8f16-d86c1826ccd4.png">

A collapsed, **folded** markdown cell:
<img width="695" alt="image" src="https://user-images.githubusercontent.com/4674940/151218252-641542bd-ad32-4c91-af67-1f98940895e5.png">

**Comment by roblourens** [comment]
Should we set `"notebook.showFoldingControls": "always"`? I have a strong preference for this
