### ISSUE TITLE
Unable to expand find menu in notebook editor

### ISSUE THREAD

**Issue by devinvalenciano** [microsoft/vscode#141516]
Version: 1.64.0-insider (user setup)
Commit: f93c69659de1a1466bd15e0f1c9f790e73be9208
Date: 2022-01-25T08:42:41.055Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Testing #141346

Steps to Reproduce:

1. Open notebook editor
2. Open find menu
3. Try to expand the size of the find menu - on my device, I'm unable to.  Also, if you look closely, there's a little grey line on the left side of the find menu on Stable that indicates you can drag - I don't see an equivalent on the find menu in the notebook editor.

![Recording 2022-01-25 at 18 23 40](https://user-images.githubusercontent.com/1389808/151093512-61ff0f1e-b100-4d14-a8d9-b1ad23cb6b98.gif)
Clip shows Stable first (grey theme), then Insiders (blue theme)

**Comment by roblourens** [comment]
@andreamah - didn't realize you had a PR already! I think that is a good start. Don't worry about just copying code from the editor's FindWidget, I think there may be some subtle differences and it's not complex enough to reuse an implementation. If you get stuck here, @rebornix can help
