### ISSUE TITLE
Adopt dnd API for references viewlet

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#141585]
Some work has already started but this needs to be finished and reach done, done

**Comment by jrieken** [comment]
To verify:

* populate the references view via "Find All References", "Find All Implementations", and "Show Call Hierarchy"
* from the tree drag any item onto the editor area and make sure the corresponding file and location opens, e.g a reference to a symbol on line 10 should reveal and select that line etc
* ensure you cannot drag/drop anything onto the references view

**Comment by tanhakabir** [comment]
I'm not seeing the proper line being selected from references:
![Recording 2022-02-23 at 10 01 25](https://user-images.githubusercontent.com/12758612/155379327-7bb5fe27-2d8d-4729-9430-de4211cded97.gif)

**Comment by jrieken** [comment]
@tanhakabir You are not dragging a reference but a file

**Comment by tanhakabir** [comment]
Oh whoops you're right! Working as expected
