### ISSUE TITLE
Double reply on Ubuntu bash

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#141528]
Testing #141341

On Ubuntu Linux I got into a state where I would see two replies. Screenshot has the setting as well as the terminal output.

![Screenshot from 2022-01-25 21-25-01](https://user-images.githubusercontent.com/12818376/151109085-be1fc969-6f22-46a3-a0f2-12068065376b.png)

**Comment by gregvanl** [comment]
This also repro on WSL with Ubuntu

**Comment by gregvanl** [comment]
One thing that is odd is that the first reply on the line disappears if you resize the terminal or window layout.

**Comment by Tyriar** [comment]
While a bit weird, this is actually working as designed since the shell echos any input during that state, then the shell prompt kicks in using the new cursor position. When resizing the terminal, the prompt redraws in the correct spot.
