### ISSUE TITLE
Restore minimized VS Code come back on wrong display when maximized

### ISSUE THREAD

**Issue by bradwilson** [microsoft/vscode#141521]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2 (user version)
- OS Version: Windows 11 (22000.434)

Steps to Reproduce:

1. Use a computer with at least two displays
1. Maximize VS Code
1. Send it to a secondary monitor (Windows + Shift + Left/Right)
1. Minimize VS Code
1. Restore VS Code (click on it on the taskbar, or Alt + Tab to it)
1. Window reappears on the primary monitor, not the secondary monitor where it was when minimized

This only happens when VS Code was maximized when minimized. If VS Code is not maximized, it restores to the correct location on the correct monitor.

**Comment by bradwilson** [comment]
People on Twitter are suggesting that this may be an Electron bug, as they can also reproduce it with other things like Slack or Teams.

**Comment by bpasero** [comment]
@bradwilson want to report it to Electron then? https://github.com/electron/electron

**Comment by bradwilson** [comment]
@bpasero I don't have the requisite knowledge to fill out their bug form, since I am not the direct consumer of Electron.

**Comment by bpasero** [comment]
I cannot reproduce this (anymore)?

**Comment by bradwilson** [comment]
@bpasero Possible that it was fixed in Electron. I also can't repro anymore so I'm closing this.
