### ISSUE TITLE
Settings Sync activity doesn't show specific User Tasks entry

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#141573]
Testing #141275

 - Open Sync Activity (Remote) view using the command `Settings Sync: Show Synced Data` 
 - Make a change in one machine's tasks.json, change takes effect a few seconds later in second machine's tasks.json
 - ❓ Expected to see `User Tasks` as one of the most recent entries, but only see `UI State` from today
      - I see `User Tasks` entries from sync testing yesterday, so thought I'd see it again today, especially as `UI State` doesn't mention tasks.json
      - Is it covered by `globalState.json`?

![image](https://user-images.githubusercontent.com/25310137/151209335-03054657-5962-4659-95e8-c1b1929947fd.png)

**Comment by bamurtaugh** [comment]
I refreshed the Sync Activity, and `User Tasks` appeared - is it expected for Sync Activity to automatically update (i.e. after 10 minutes, since the initial sync was 6 minutes ago, as shown below), or does the user need to refresh / run the command again?

![image](https://user-images.githubusercontent.com/25310137/151210086-70b0f64d-0ef7-42a5-81f3-50001432b004.png)

**Comment by sandy081** [comment]
It does not auto appear, you have to refresh manually. Since this is just for trouble shooting it is not aggressive to update.
