### ISSUE TITLE
Support inlay hint double click gesture

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#141576]
We should support the double click gesture on inlay hints and connect it with some "primary command". That would allow for nice interactions like making the corresponding code change when clicking etc

**Comment by jrieken** [comment]
This happened. With `vsocde.InlayHint.command` the default (dbl-click) gesture can be set

**Comment by jrieken** [comment]
To verify

* use the sample https://github.com/jrieken/test-inlayhints/
* run `npm i`
* press F5 to debug
* open a markdown file, type "foo" and "bar",  both words will be decorated with an inlay hints
* ensure you can dbl-click the hints and see a notification

**Comment by isidorn** [comment]
Works nicely -> verified. Filled follow up issue https://github.com/microsoft/vscode/issues/143740

**Comment by jrieken** [comment]
Re-opening after further discussion (https://github.com/microsoft/vscode/issues/143740 and related). The current API allows to give a command for the hint as well as for hint label parts. Tho, the former command is meant to be a "accept" command and we should model the API accordingly. That would allow us to show specific UI, like "double click to accpet"

**Comment by jrieken** [comment]
API idea

```ts
export class InlayHint {

  // optional edit that is performed when the default gesture is triggered
  edit?: TextEdit | WorkspaceEdit;
}
```
