### ISSUE TITLE
Need to guess if what I see is a collapsed markdown cell

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#141580]
Testing #141222

Same as https://github.com/microsoft/vscode/issues/141222#issuecomment-1021172492.

Other than by background color there is no way to quickly identify a collapsed markdown cell:

<img width="693" alt="image" src="https://user-images.githubusercontent.com/4674940/151217866-7416f213-00db-47e4-acfe-1621b810e685.png">

**Comment by roblourens** [comment]
You mean if it's markdown vs code?

**Comment by roblourens** [comment]
We could 

- Show a single line of rendered markdown
  - The first line might not be useful to show rendered - it could be a comment, a table header, etc. We could parse it enough to show the first non-comment line
- Add some label or icon like the markdown codicon
