### ISSUE TITLE
Alpine Linux: /bin/ps: unrecognized option: x

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#141545]
Alpine Linux' `ps` does not appear to have the `x` option:

```
[IPC Library: Pty Host] DEBUG ChildProcessMonitor: Fetching process tree failed Error: Command failed: /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
/bin/ps: unrecognized option: x
BusyBox v1.34.1 (2021-11-23 00:57:35 UTC) multi-call binary.

Usage: ps [-o COL1,COL2=HEADER] [-T]

Show list of processes

        -o COL1,COL2=HEADER     Select columns for display
        -T                      Show threads

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
```

Version: 1.64.0-insider
Commit: 45060913204279d4ecfe0575ca69d68211fb3798
Date: 2022-01-26T05:15:06.786Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Comment by Tyriar** [comment]
@meganrogge FYI Rachel wrote this code so I guess we own it now https://github.com/microsoft/vscode/blob/6358042bbcd72bca2c3c2a667b74fd3a8a7172a2/src/vs/base/node/ps.ts#L232

@chrmarti completely new to Alpine is there any easy way to test this?

**Comment by chrmarti** [comment]
The options are very limited:
```
BusyBox v1.34.1 (2021-11-23 00:57:35 UTC) multi-call binary.

Usage: ps [-o COL1,COL2=HEADER] [-T]

Show list of processes

        -o COL1,COL2=HEADER     Select columns for display
        -T                      Show threads
```

Header names are different/limited:
```
ps: bad -o argument 'pcpu', supported arguments: user,group,comm,args,pid,ppid,pgid,etime,nice,rgroup,ruser,time,tty,vsz,sid,stat,rss
```

And the only way to hide the header name is to use `-o` for each:
```
ps -o pid="" -o ppid="" -o comm=""
```

Remote-Containers reads `/proc` to avoid the need for `ps` which isn't necessarily installed, e.g., the Debian Docker image does not have it (https://hub.docker.com/_/debian).

**Comment by Tyriar** [comment]
@chrmarti fyi I've found reading /proc throws security related errors sometimes, that's why this throw exists:

https://github.com/microsoft/vscode/blob/7f2580fa2ee290d1a87bf8ec0789f1bc2b7990f2/src/vs/platform/terminal/node/terminalProcess.ts#L545-L549

Could you take this one as I don't have an Alpine setup? We could try use Alpine's limited args or it might be better to detect that and fallback to `ps.sh` like when `ps` doesn't exist?

https://github.com/microsoft/vscode/blob/6358042bbcd72bca2c3c2a667b74fd3a8a7172a2/src/vs/base/node/ps.ts#L220-L228

**Comment by chrmarti** [comment]
The implementation I'm using ignores when it can't read a /proc file. (There is known bug with env values including newlines.) I see `ps.sh` is using `awk`, I have so far avoided that, but can't currently find a distro not including it.

The easiest way to get Alpine for testing is maybe as a container (I don't have a full install of Alpine).

**Comment by Tyriar** [comment]
Both the terminal's child process monitor and the process explorer work when connected to an Alpine container so I guess this is fixed? Maybe only in newer versions of Alpine?
