### ISSUE TITLE
Markdown heading link doesn't seem to scroll the heading correctly on screen

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#141577]
Testing #141327

Create a simple notebook like the following:

Cell 1:
```
# Main Header
## Second Header
```

Cell 2:
`[Main Link](#main-header)`

Both cell are markdown cells. When clicking the Main Link it would scroll the Main Header cell off the screen which doesn't seem right for that action. Best illustrated with GIF below:

![HeaderLink](https://user-images.githubusercontent.com/812783/151213152-703b7226-0520-41e1-82a5-a4efa5276f3b.gif)

When I click Main Link my expectation would be that Main Header would end up onscreen, like when I click it from the outline. Instead the cell containing the link is scrolled to the top and the Main Header cell is pushed offscreen.

**Comment by greazer** [comment]
This works in Jupyter and was also recently run across by Rong. So adding nb-golden.
