### ISSUE TITLE
Inline Completion Bracket Matching Issues

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#141550]
This works:
![image](https://user-images.githubusercontent.com/2931520/151159452-3b9a6a02-0814-455e-90d2-b342e1e90657.png)

But this doesn't, but should:
![image](https://user-images.githubusercontent.com/2931520/151159538-0a63b68b-831d-4e9a-b61f-25a19348d7fc.png)

**Comment by juihanamshet1** [comment]
There was also this scenario in the original issue which I believe is related
Before: 
https://user-images.githubusercontent.com/86270736/148269808-40ab52a7-80d1-4031-a7b6-64cce7ef5b47.png

After: 
After I hit Tab, notnull would be accepted and the (x) would disappear.
