### ISSUE TITLE
Code - Insiders won't start if the "%APPDATA%\Code - Insiders\Backups\workspaces.json" contains an invalid path

### ISSUE THREAD

**Issue by ionut-botizan** [Microsoft/vscode#14151]
While I had a folder opened as a project in _Code - Insiders_, I renamed that folder to something else. Then, an update became available and it prompted me to install it. Code closed, the update went on, but Code never came back.
After investigating a bit, I realized the `workspaces.json` still pointed to the old folder name. After removing the `workspaces.json` file, Code started normally.
---
- VSCode Version: Code - Insiders 1.7.0-insider (4dc59b7e2a9c003e17d154023d47bd94a972694b, 2016-10-21T06:11:33.710Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

| Extension | Author | Version |
| --- | --- | --- |
| Bookmarks | alefragnani | 0.9.2 |
| vscode-svgviewer | cssho | 1.2.0 |
| xml | DotJoshJohnson | 1.6.0 |
| php-debug | felixfbecker | 1.9.7 |
| php-intellisense | felixfbecker | 0.0.9 |
| Theme-Daily-Grind | gerane | 0.0.2 |
| Theme-Twilight | gerane | 0.0.2 |
| vscode-todo-parser | minhthai | 1.8.3 |
| vscode-apache | mrmlnc | 1.1.0 |
| PowerShell | ms-vscode | 0.7.2 |
| vscode-nginx | shanoor | 0.3.0 |
| guides | spywhere | 0.5.1 |
| Align | steve8708 | 0.2.0 |
| change-case | wmaurer | 0.4.1 |
| theme-vsicons | ionut-botizan | 0.0.1 |
---

Steps to Reproduce:

**The hard way:**
1. Create a folder `abc`
2. Open that folder as a workspace in Code - Insiders
3. Rename the `abc` folder to something else, like `xyz`, while Code is still running
4. Use your favorite method to _crash_ Code in such a way that the `%APPDATA%\Code - Insiders\Backups\workspaces.json` file doesn't get updated; hard resetting your machine works best! :)
5. After your machine restarts, try to open Code
6. Nothing happens
7. Manually delete or edit the contents of `%APPDATA%\Code - Insiders\Backups\workspaces.json`
8. Code will start normally

**The easy way:**
1. Close all running instances of _Code - Insiders_
2. Edit the contents of the `workspaces.json` file to point to an inexistent directory, like:
`{"folderWorkspaces":{"c:\\foo\\bar\\baz":[]}}`
3. Try to open Code; it shouldn't start

**Comment by Tyriar** [comment]
I've reverted the changes responsible and will queue a new build. This will stay open until it's verified to be fixed on the feature branch.

**Comment by Tyriar** [comment]
The new builds will have to wait until this [DNS DDoS attack](arstechnica.com/security/2016/10/dos-attack-on-major-dns-provider-brings-internet-to-morning-crawl/) is over.

**Comment by Tyriar** [comment]
This should have been fixed by https://github.com/Microsoft/vscode/issues/14063
