### ISSUE TITLE
Cannot set breakpoint (unbound) in symlinked node_modules dependency

### ISSUE THREAD

**Issue by neo-ctataryn** [microsoft/vscode#141586]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: `1.63.2 (Universal)`
- OS Version: Mac OSX Monterey `12.0.1 (21A559)` `Darwin arm64 21.1.0`

**Problem:**

When setting a symlink to a library on my computer within a React app's `node_modules` I cannot set a breakpoint on:
1. Any line in my app that has a call to a function from the linked module
2. Any line of code within the linked module

The breakpoint always shows up as "unbound".

Steps to Reproduce:

1. Clone: https://github.com/apollographql/fullstack-tutorial
2. Follow the notes on how to build from its Readme
3. Start the `server` from that project's `final` folder
4. Open VSCode on the `client` folder from the `final` folder
5. Inspect the client's `package.json` file and find the `@apollo/client` version they are using
6. In a separate folder on your drive, clone the Apollo Client project (https://github.com/apollographql/apollo-client)
7. From the version you found in the `client`'s package.json, switch `apollo-client` to that version (e.g. `git checkout tags/v3.4.6 -b v3.4.6`)
8. Build the `apollo-client` project (https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#building)
9. In the `fullstack-tutorial`'s `client`'s `node_module` folder, follow the guide on how to symlink the `apollo-client` in (https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#wiring-a-checkout-into-an-application)
10. Pay special mind in the guide to wiring up the `react` and `react-dom` dependencies as well

Now, in VSCode in the `fullstack-tutorial`'s `final/client` folder do the following:

1. Add the snippet below to your `launch.json`
2. Start the app using the launch configuration
3. Ignore the browser it spawns (doesn't seem to attach to debugger) and instead open the VSCode command palette (Shift-Cmd-P) type "Open Link" and fill in the prompt with `http://localhost:3000`
4. in the `src/index.tsx` try placing a breakpoint on the line: `const { data } = useQuery(IS_LOGGED_IN);` but the breakpoint will be unbound
5. in the same file, try placing a breakpoint on the line below it `return data.isLoggedIn ? <Pages /> : <Login />;` and the breakpoint will be fine
6. Drill into the `userQuery` function (this is now code within `node_modules`) and then drill into `useBaseQuery`
7. Try setting a breakpoint anywhere within `useBaseQuery.ts` and it'll be unbound

`launch.json`
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-node",
            "name": "start",
            "request": "launch",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
              "run-script",
              "start",
              "--preserve-symlinks"
            ],
            "skipFiles": [
              "<node_internals>/**",
              "**/node_modules/**",
              "!**/node_modules/@apollo/**"
            ],
            "console":"integratedTerminal",
            "localRoot": "${workspaceFolder}",
            "resolveSourceMapLocations": [
              "!${workspaceFolder}/node_modules/**",
              "${workspaceFolder}/**",
              "${workspaceFolder}/node_modules/@apollo/client/**",
            ],
            "trace": true
          }
    ]
}
```

**Comment by connor4312** [comment]
Please grab a trace log:

/jsDebugLogs

**Comment by neo-ctataryn** [comment]
@connor4312 Here you are... I did things like try to set breakpoints in the project where I had described they were "unbound" above. 
[vscode-debugadapter-e4e29f91.json.gz](https://github.com/microsoft/vscode/files/7946363/vscode-debugadapter-e4e29f91.json.gz)

**Comment by connor4312** [comment]
Thanks for the log.

> in the src/index.tsx try placing a breakpoint on the line: const { data } = useQuery(IS_LOGGED_IN); but the breakpoint will be unbound

This is an issue with sourcemaps produced by TypeScript, but you can work around it by removing the destructuring assignment. There are quite a few known issues with targeting ES5, particularly debugging around async/await where it is downleveled into generators which have a different control flow. Unless you need to support Internet Explorer, it's quite safe to target ES2020 or newer. Your code will also perform better 🙂 

> Try setting a breakpoint anywhere within useBaseQuery.ts and it'll be unbound

I repro'd this on the stable debugger, but it looks like it's working in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension). Could you give that a spin and let me know if that fixes it for you as well? 

![image](https://user-images.githubusercontent.com/2230985/151269432-a9603882-fb8d-4add-bf5d-b6c278a360d0.png)

**Comment by neo-ctataryn** [comment]
@connor4312 Thank you! I'll be sure to try your suggestions and report back. I want to make sure it also works in a larger project where I first observed the issue too.

**Comment by neo-ctataryn** [comment]
@connor4312 it works! (enough to get me by!). It's still a bit janky, [I recorded a video just to demonstrate](https://youtu.be/Qdnyr4rLQzs).  The gist of it is that I can set breakpoints but they don't seem like they take. But then when I launch the debug browser it'll hit on one in `index.tsx` then I can step-debug into `userQuery` but the debugger kinda bounces my cursor around (I think because of what you described in how there are generator code in behind the scenes).

Note at the end how it complains about not being able to find `typescript.js.map` I think this is why I'm getting the red-squiggles in the @apollo/client files? I confirmed that no such file exists in my `node_modules/typescript/lib` folder, only `typescript.d.ts, typescript.js` are there which are named similarly.

I also attached the trace file for the session depicted in the video in case you wanted to check it out.

[vscode-debugadapter-219e09bf.json.gz](https://github.com/microsoft/vscode/files/7951632/vscode-debugadapter-219e09bf.json.gz)

P.S. On my larger project this didn't seem to work, in fact when I cmd-click into a function like `useQuery` it'd just bounce me to the `useQuery.d.ts` file, not the code. Do you know why that might be? In my larger project, I didn't symlink, but rather I copied the Apollo Client's dist folder directly into my `node_modules/@apollo/client` folder. Not sure why that'd be an issue, but I could retry by doing the symlink way...

**Comment by neo-ctataryn** [comment]
@connor4312 update: I re-synlink'd in `@apollo/client` to my larger project and I was able to step in to `userQuery` and it showed the code, yay!  Still have the red-squiggles though and pre-setting breakpoints in @apollo/client don't seem to work but if I step into that code and then set a breakpoint it does seem to take.

Anyway, like I said it's enough to allow me to go forward. Thank you for the help 🙏

**Comment by connor4312** [comment]
> Still have the red-squiggles though

This is on the TypeScript side. We open a `.ts` file, so that's what's used.

> pre-setting breakpoints in @apollo/client don't seem to work

This looks like an issue with the sourcemaps webpack generates. For me, for example, it creates an absolute file URI `"file:///Users/connor/src/react/hooks/utils/useBaseQuery.ts"`, where it should be `"file:///Users/connor/Downloads/apollo-client/src/react/hooks/utils/useBaseQuery.ts"`. The version of webpack in the example repo is also quite old, so updating it may fix things as well.
