### ISSUE TITLE
URL Protocol opens existing window instead of launching a new one

### ISSUE THREAD

**Issue by david-caetano** [microsoft/vscode#141548]
When we open vscode using the URL protocol (vscode://file/some-folder) it utilizes an existing window and overwrites it with the new folder. It was expected that a new window would be launched if the URL we are trying to open via vscode:// does not match any open window.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows 10

Steps to Reproduce:

1. Start a vscode instance in any folder e.g. D:/folder-a
2. Use the URL Protocol to open vscode on a second folder e.g. start vscode://file/D:/folder-b or using the explorer/browser URL input
3. Check that the vscode window that was open on the first folder D:/folder-a was overwritten with the new folder D:/folder-b

**Comment by bpasero** [comment]
I think changing this for everyone just now is a bad idea, and besides this is also a user setting to control this. But maybe there could be a parameter in the URL to control this.

**Comment by joaomoreno** [comment]
We now handle a `windowId=_blank` query param. If you set this in a URI and give it to be handled by Code, it will always do it in a brand new window.

**Comment by joaomoreno** [comment]
Reminder: release notes

**Comment by joaomoreno** [comment]
Oh wow good catch @joyceerhl! I can definitely repro, but not on URIs meant for extensions. There might be another code path I didn't see.

**Comment by joaomoreno** [comment]
Bad copy paste. This is already in `main` since yesterday: https://github.com/microsoft/vscode/commit/bcc2da636987ca8b173820b53c9a4a16b06064fa

**Comment by rebornix** [comment]
Works great. Adopted this in my logseq plugin, good timing :)
