### ISSUE TITLE
Make Node's `vm` module work with VS Code debugger

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#141551]
I'd like to call a function created by passing the content of a file in the current project tree to `vm.compileFunction` and be able to set a breakpoint inside file and have it work. I can't figure this out. Is this possible already? If not, how much work would it be to add it?

It already works with the `debugger` keyword. Presumably we just need to add like, some path logic in there or something, right? I am able to map the local filename from the file tree to this file if need be, passing it as the `filename` option to the aforementioned function. Will this help?

For context, I created [this issue in the nodejs project](https://github.com/nodejs/node/issues/41703) and they told me I need to ask you.

**Comment by connor4312** [comment]
It sounds like you want to add a comment like `//# sourceURL=<original file uri>`, where `<original file uri>` is in the form `file:///foo/bar.js`, to the end of the string you pass to `compileFunction`. This is a standard comment form which MDN has a brief section on: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Debug_eval_sources

**Comment by sdegutis** [comment]
In this format?

```js
vm.compileFunction(code + `\n//# sourceURL=${pathToFileURL(realPath).toString()}`)
```

Because it's not working. VS Code is not seeing the connection. It prints a valid file path, but in Windows format:

```
// ...
// ... js code here, last line below:
// ...

//# sourceURL=file:///c:/Users/myuser/Documents/projects/myapp/src/pages/home.tsx
```

Could that be why it's not working?

**Comment by sdegutis** [comment]
Oh wait, it's working. It's just I'm not giving a source map. Oops. Thanks @connor4312

**Comment by sdegutis** [comment]
@connor4312 Can we reopen this? Your suggestion isn't enough since it needs a whole source map, and I can't figure out how to give VS Code a source map that it understands. I've gotten pretty far but not knowing how to debug what VS Code is doing, and not knowing its internals, I've spent about an hour and gotten almost nowhere.

**Comment by sdegutis** [comment]
For context:

1. I'm creating a valid source map object
2. I'm encoding it correctly as a base64 URL
3. I'm correctly making it the last line of the compiled vm function source
4. I'm running my code inside VS Code's debugger
5. The `sources` key has a valid absolute file url to my file
6. VS Code can open that absolute file URL just fine on its own
7. I've tried passing several values to `filename` option of `vm.compileFunction`

Example source map:

```js
{
  version: 3,
  file: 'myfile.js',
  sources: [
    'file:///C:/Users/myuser/projects/myapp/src/some/myfile.tsx'    
  ],
  mappings: 'AAAA;[etc];AACA',
  names: []
}
```

**Comment by sdegutis** [comment]
More context:

1. When I put a `debugger` statement inside the file, VS Code stops execution right there as expected
2. It shows the compiled source, as expected, in a new tab
3. The name of this new file is exactly what I passed to `filename` option of `vm.compileFunction`
4. This new file has my source map at the bottom, in proper base64 format

Example base64-encoded URL at the bottom of my file (no newline at end, newline before it is `\n`):

```js

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoibWFpbi5qcyIsInNvdXJjZXMiOlsiZmlsZTovLy9jOi9Vc2Vycy93b3cveW91L2FjdHVhbGx5L2RlY29kZWQvdGhpcy9pbS9zdXJwcmlzZWQveW91L3dlbnQvdGhhdC9mYXIvYXBwL3NyYy9tYWluLnRzeCJdLCJtYXBwaW5ncyI6IkFBQUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSIsIm5hbWVzIjpbXX0
```

**Comment by sdegutis** [comment]
This is what the debugger shows:

![image](https://user-images.githubusercontent.com/4399718/151266114-750670c6-b751-4a0f-9f8a-a43b625c1017.png)

**Comment by sdegutis** [comment]
I wonder, is it related to the fact that it's showing `<node_internals>` before the file name I gave it? Like, maybe VS Code just needs me to convince Node.js that the function I created with `vm.createFunction` is not part of node_internals, or something?

**Comment by connor4312** [comment]
That sourcemap looks correct. Using an absolute file URI in `sources` is the simplest way to get it to work, though the example sourcemap you gave looks incomplete. You can use https://sokra.github.io/source-map-visualization/ if you need to debug sourcemaps themselves.

You may also need to pass `resolveSourceMapLocations: null` in your launch.json to instruct js debug to resolve sourcemaps seen anywhere. By default it'll try to only resolve sourcemaps for sources in your workspace folder and excluding node_modules.

**Comment by sdegutis** [comment]
I just added the default value for that (the one it filled in for me):

```json
      "resolveSourceMapLocations": [
        "${workspaceFolder}/**",
        "!**/node_modules/**"
      ],
```

*And it worked!*

This is so cool.

Thanks @connor4312

**Comment by sdegutis** [comment]
For future reference, the source map above is what worked. It is missing `sourceRoot` which is commonly empty string (`""`) but that doesn't matter since the sources are absolute file URLs. I found this out in the spec which is why I'm sure it's not fragile.

**Comment by sdegutis** [comment]
For reference, [Novo Cantico](https://www.novocantico.org/) is the new TypeScript framework which you all helped to make extremely easy to use with VS Code's debugger by helping me figure out how to make `vm`-compiled functions work with VS Code via source maps. Thanks, and I'd be glad to hear what you think of this framework if any of you have a minute to spare :)
