### ISSUE TITLE
something wrong when type Chinese character

### ISSUE THREAD

**Issue by Laily123** [Microsoft/vscode#14156]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 15.6.0
- Extensions: lukehoban.Go-0.6.45, vscodevim.vim-0.3.8

When I type Chinese character in vs code, the input method bar show everywhere instead of near my cursor.

**Comment by rebornix** [comment]
I can repro this issue in 1.7.0-Insiders with no extension enabled. My reproduce steps:

1. Open a file with 10 lines
2. Start to type with Chinese IME turned on at line 5
3. When you type the first char, the IME popup window is at the first line of the document
4. Afterwards the popup window is right below the cursor, which is correct.

**Comment by roblourens** [comment]
Maybe related to #13093

**Comment by Laily123** [comment]
@roblourens It doesn't word, my problem is the same with rebornix's post

**Comment by alexandrudima** [comment]
Maybe a dup of #356 ?

**Comment by Laily123** [comment]
@alexandrudima yeah, It is the same with #365, Thank you for reply 😬
