### ISSUE TITLE
Clicking into folded markdown cells

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#141582]
Testing #141222

See also https://github.com/microsoft/vscode/issues/141222#issuecomment-1021172492.

Clicking into a folded markdown cell or the hidden cell indicator does nothing. Double clicking enters edit mode of the markdown cell but I'd expect it to expand first.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/4674940/151218764-48056004-8edb-40d6-a81a-5de562e337c8.png">

**Comment by roblourens** [comment]
Going to make `...` clickable
