### ISSUE TITLE
VSCode/Win 11 Crashing/Freezing - requiring complete reboot

### ISSUE THREAD

**Issue by SteCCX** [microsoft/vscode#141540]
Issue Type: <b>Bug</b>

Hi, I am creating a PS script to connect to AzureAD and get data etc.
I am using Windows 11 and VSCode with the ISE and LiveShare extension, i keep getting interrupted because VSCode will freeze crash and often cause the whole OS will become unstable - Ctrl-alt-delete doesn't work so i have to  reboot laptop to restart work.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (23.07GB free)|
|Process Argv|--crash-reporter-id e4a350d3-a179-43dd-b4a3-0f57180e612b|
|Screen Reader|no|
|VM|15%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2021.12.0
vsliveshare|ms-|1.0.5273

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30424895
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsclayoutctrc:30425945
vsrem710:30416614
vsbas813:30426126

```

</details>

**Comment by alexdima** [comment]
@SteCCX Does the crash reproduce without using those extensions? If you are able to consistently reproduce, can you please follow the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues to create a `.dmp` file?

**Comment by SteCCX** [comment]
Hi, Thanks for the reply. I think the issue can be closed. I moved to ISE and the system was still freezing, leading me to think its more of a Windows 11 problem or perhaps MS ATP interfering (event viewer showed the service frequently needed restarting) as work have recently enabled this.
Anyway, the issue seems to have gone away since i joined the insider program and downloaded a cumulative win 11 update and the system is no longer locking up.
