### ISSUE TITLE
Allow global toggle for escape escape sequence logging

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#141568]
Currently escape sequences can only be enabled on terminals that exist, that makes it hard to diagnose issues like https://github.com/microsoft/vscode/issues/141510 without debugging in OSS. We should switch this command to enable it for all terminals that already exist and new ones that will be created.

**Comment by meganrogge** [comment]
Would hate to have to add `escapeSequenceLoggingEnabled` to shell launch config, as we already discussed that has too many things on it, but don't know of another way 🤔

**Comment by Tyriar** [comment]
@meganrogge It's not a shell setting but an xterm.js one (logLevel), so you check something inside `XtermTerminal` or `TerminalInstance` for this.

**Comment by meganrogge** [comment]
Maybe I misunderstood this, but was thinking we'd track the log level in terminal service and then pass that info to terminal instance service for terminal creation, which eventually gets to xterm terminal create.

**Comment by Tyriar** [comment]
I think you can set it in TerminalService, just via something like `TerminalInstance.setEscapeSequenceLogging()` right after it's been created? Just need to make sure it happens before the process/data is written to xterm.js which should happen in at least the next frame.

**Comment by meganrogge** [comment]
right, but then can't have a cyclic dependency, so will have to pass it in the shell launch config in order for it to reach the xtermTerminal constructor.

**Comment by Tyriar** [comment]
As in listen for ondidcreate from terminal instance service from within terminal service and set it like `instance.set...`. Dependencies should still be TerminalService->TerminalInstance->XtermTerminal.

Whenever the toggle action happens you can iterate over all instances from inside terminal service.
