### ISSUE TITLE
Build for an extension doesn't run unless opening the terminal window

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#141510]
Issue Type: <b>Bug</b>

1. Git clone  https://github.com/microsoft/vscode-extension-samples.git
2. Open the tree-view-sample
3. Hit F5

Debugger won't start until you open a terminal window

VS Code version: Code - OSS Dev 1.64.0 (Commit unknown, Date unknown)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (12.98GB free)|
|Process Argv|. --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-renderer-backgrounding --disable-sync --metrics-recording-only --no-first-run --no-default-browser-check --user-data-dir=D:\\Source\\vscode/.profile-oss --inspect=5875 --no-cached-data --disable-features=CalculateNativeWinOcclusion --remote-debugging-port=9222|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.0.1719302831-dev
jupyter|ms-|2022.1.1001711856
jupyter-renderers|ms-|1.0.4

</details>

**Comment by alexr00** [comment]
@Tyriar this sounds like a terminal issue.

**Comment by Tyriar** [comment]
I can reproduce, I think the problem matcher never matches the finish regex.

This is what the terminal looks like when expanded and scrolled up:

![image](https://user-images.githubusercontent.com/2193314/151186060-82d26158-e694-48d5-9cab-d0b784857c1b.png)

Resizing the terminal on Windows launches since the lines get rewritten. I'm guessing this only happens on Windows due to conpty being weird. Created https://github.com/microsoft/vscode/issues/141568 for better tools to diagnose this sort of thing.

**Comment by Tyriar** [comment]
This is because of the 2 width terminal and the windows wrapped line heuristic is treating it as a single wrapped line:

![image](https://user-images.githubusercontent.com/2193314/152565579-73f9606a-4b36-41df-bf1e-ce5c1e5ccb1f.png)

**Comment by Tyriar** [comment]
The process is created correctly with the fallback 80x30, xterm is created with 0x0 though.
