### ISSUE TITLE
"Show Command Output" includes the next prompt line

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#141616]
Testing #141339

Is this by design? I would expect to see just the first two lines.

![image](https://user-images.githubusercontent.com/323878/151278477-756930eb-eda6-4512-9b4a-15b94520d94e.png)

**Comment by meganrogge** [comment]
This is fixed now. Can't find the duplicate issue; should be verifiable in insider's tomorrow

**Comment by meganrogge** [comment]
Actually don't think there was an issue for this, but fixed it
