### ISSUE TITLE
Safari — SyntaxError: Activating extension 'vscode.markdown-language-features' failed

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#141689]
Issue Type: <b>Bug</b>

1. Build for macOS
1. `./scripts/code-web.sh`
1. Launch in safari 
1. Open markdown file

**Bug**

```
SyntaxError: Activating extension 'vscode.markdown-language-features' failed: Invalid regular expression: invalid group specifier name.
Function
(anonymous function)
asyncFunctionResume
(anonymous function)
promiseReactionJobWithoutPromise
promiseReactionJob
onDidChangeNotification — notificationsAlerts.ts:40
```

VS Code version: Code - Insiders 1.64.0-insider (Universal) (3dda6ea7acb66ea8693032fe9631ccac629da770, 2022-01-27T08:39:44.269Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|32.00GB (3.49GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Seems to have come in through a514979b022ef8926643f2109bf480019841f377

**Comment by mjbvz** [comment]
https://caniuse.com/js-regexp-lookbehind

**Comment by joyceerhl** [comment]
Hit this in insiders.vscode.dev on iOS yesterday. Verified that markdown features like preview work now--thanks for the quick fix!
