### ISSUE TITLE
Linting in copied files shows incorrect errors.

### ISSUE THREAD

**Issue by kawka-maciej** [microsoft/vscode#141637]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.63.2
- OS Version: macOS 10.15.7 (19H2)

Steps to Reproduce:

1. Create a sample TypeScript file and declare any variable there.
2. Copy and paste the file.
3. TypeScript reports an error `Cannot redeclare block-scoped variable 'test'.` although the variables are declared in two different files.

**Comment by IllusionMH** [comment]
/duplicate of #22436 and https://github.com/microsoft/TypeScript/issues/14279

Files without `import`/`export` statements are treated as in global scope and therefore it's not allowed to use same name. See linked issues for details.
