### ISSUE TITLE
Getting started errors after reload 

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#141603]
Testing microsoft/vscode-jupyter#8793

1. Follow the steps on the linked issue until you open "Get started with Jupyter Notebooks"
2. Reload the window
3. The "getting started" editor loads infinitely and this error is in the console:

![image](https://user-images.githubusercontent.com/2230985/151057118-76042593-1a25-4299-ab1a-cacd6086304f.png)

cc @JacksonKearl

**Comment by JacksonKearl** [comment]
Wasn't able to repro in the wild, but tested via debugging an extension that contributes a walkthrough, opening the walkthrough, deleting the steps from that walkthrough in the extension's `package.json`, then reloading.

**Comment by connor4312** [comment]
Seems fixed for me!
