### ISSUE TITLE
Keyboard Shortcuts: Change When Expression might actually remove keybinding in Insiders

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#141638]
Issue Type: <b>Bug</b>

I think this changed somwhere in January (I don't think I've noticed it in late December).

Steps to repoduce:
1. Open Keyboard Shortcuts editor
1. Find **shortcut without `when` expression** (e.g. `workbench.action.closeActiveEditor`)
1. Right click and select "Change When Expression"
1. Add `when` expression (e.g. `editorTextFocus`) and save it
1. Shortcut is removed from filtered results and doesn't work when cursor is in editor.

Root cause is that Change When Expression creates 2 records in `keybindings.json`:
```json
{
    "key": "ctrl+w",
    "command": "workbench.action.closeActiveEditor",
    "when": "editorTextFocus"
},
{
    "key": "ctrl+w",
    "command": "-workbench.action.closeActiveEditor"
}
```
and lately `"command": "-commandIdЭ` without `when` removes all keybindings without taking `when` into account.
Swithing order of these objects restores expected behavior.

Looks like this doesn't happen if keybinding already had `when` expression. For example next change displayed in list as expected
```json
{
    "key": "escape",
    "command": "editor.debug.action.closeExceptionWidget",
    "when": "exceptionWidgetVisible && editorTextFocus"
},
{
    "key": "escape",
    "command": "-editor.debug.action.closeExceptionWidget",
    "when": "exceptionWidgetVisible"
},
```

VS Code version: Code - Insiders 1.64.0-insider (3dda6ea7acb66ea8693032fe9631ccac629da770, 2022-01-27T05:15:00.564Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (20.14GB free)|
|Process Argv|--crash-reporter-id cf52dbde-2c94-45c3-9bf3-45d8b9966b04|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by joyceerhl** [comment]
Still seems to repro: 
![Recording 2022-01-28 at 12 07 45](https://user-images.githubusercontent.com/30305945/151614462-b119f688-b78e-49fb-b3d8-018dd4015d22.gif)

**Comment by IllusionMH** [comment]
Hmm... Strange. I cannot reproduce problem with steps from my initial report and I don't see difference with order of add/remove shortcut objects.

This order works fine in my case.
```js
{
    "key": "ctrl+w",
    "command": "workbench.action.closeActiveEditor",
    "when": "editorTextFocus"
},
{
    "key": "ctrl+w",
    "command": "-workbench.action.closeActiveEditor"
}
```

Version: 1.64.0-insider (user setup)
Commit: b8178e3e2f3f620ebdd31dfbfba937ff1b12ee04
Date: 2022-01-28T10:18:24.930Z
OS: Windows_NT x64 10.0.19041

**Comment by alexdima** [comment]
@joyceerhl I also tried again on Windows and I cannot reproduce what you are seeing? Are you on latest Insiders?

**Comment by joyceerhl** [comment]
Works now--I thought I updated this morning but needed another restart. Sorry about that!
