### ISSUE TITLE
Feature request: jump to relative line number

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#14162]
Now VSCode has the option to show relative line numbers, it would be great to have a command that allows a user to jump to a line number relative to the current cursor location.

**Comment by OliverJAsh** [comment]
Is this part of that issue? That sounds like a bug to do with rendering, this is a behavioural feature request.

**Comment by roblourens** [comment]
In the comment, Dirk suggested it as an option. And since I linked this issue, we'll know that it was also requested specifically.

**Comment by retepaskab** [comment]
Yes that would be great, it should also work with non-relative line number display.

**Comment by seanyu4296** [comment]
i seem to get this error when i try to install your extension @retepaskab 
```Unable to install because, the extension 'retepaskab.relativegoto' compatible with current version '1.19.2' of VS Code is not found.```

**Comment by retepaskab** [comment]
It's compatible with 1.21.1, try refreshing vscode. I will review and correct the package later.

**Comment by sergei-dyshel** [comment]
@retepaskab 
Would you mind publishing the source too?

**Comment by retepaskab** [comment]
@sergei-dyshel It should be in the folder .vscode\extensions\retepaskab.relativegoto-0.0.1\out
