### ISSUE TITLE
Terminal syncing up across windows/workspaces

### ISSUE THREAD

**Issue by simplyandyg** [microsoft/vscode#141656]
Issue Type: <b>Bug</b>

When working with multiple windows/workspaces open all of a sudden the terminal from window A will match window B. It will be an exact and reactive mirror. The terminal path also changes to what is in window B.

Type a command in the terminal in Window B, it shows up as you are typing, letter for letter in Window A. Send it, it shows in Window A. Etc. Seems like the terminal instances are somehow getting linked.

I have not been able to intentionally reproduce the issue, but have seen it happen 3 times today. If I can figure out the steps, I will post them on the GitHub issue.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:38:17.605Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 5|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 853d23cb-0bc6-4e44-ad68-a71a78fce5ff|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.0
vscode-sql-beautify|cla|0.2.8
beautify|Hoo|1.5.0
php-cs-fixer|jun|0.2.10
vscode-docker|ms-|1.19.0
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
color-highlight|nau|2.5.0
vetur|oct|0.35.0
LiveServer|rit|5.7.4
php-debug|xde|1.23.0
material-theme|zhu|3.13.16

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710:30416614
vsbas813:30426126

```

</details>

**Comment by meganrogge** [comment]
Yes, please add some steps to reproduce so we can investigate this. Thanks
