### ISSUE TITLE
error crashed code 5

### ISSUE THREAD

**Issue by likun7981** [microsoft/vscode#141629]
Does this issue occur when all extensions are disabled?: No

<img width="300" src="https://user-images.githubusercontent.com/13427467/151322387-e9e4ff5e-10ee-45bd-851c-ad64b251b2e3.png" />

- VS Code Version:
<img width="300" src="https://user-images.githubusercontent.com/13427467/151321868-4816f9ec-16b3-463f-baa1-5795537b38f5.png" />

- OS Version:
<img width="300" src="https://user-images.githubusercontent.com/13427467/151321968-8930c5b6-4b4c-49a6-b614-e38aa636906c.png" />

Steps to Reproduce: *.dmp file is here 

[vscode-crash.zip](https://github.com/microsoft/vscode/files/7948910/vscode-crash.zip)

**Comment by IllusionMH** [comment]
> Does this issue occur when all extensions are disabled?: No

If this not reproducible with all extensions are disabled that it's likely caused by an extension.
From command palette (<kbd>F1</kbd>) run `>Help: Start Extension Bisect` and follow steps.

See details: https://code.visualstudio.com/blogs/2021/02/16/extension-bisect

**Comment by likun7981** [comment]
I cannot reproduce errors when some extensions are disabled
