### ISSUE TITLE
Cannot switch languages in code server mode

### ISSUE THREAD

**Issue by chenxqiyu** [microsoft/vscode#141694]
Cannot switch languages in code server mode，Hope to adapt as soon as possible

**Comment by tanhakabir** [comment]
To clarify do you mean that you can't change the language of files or do you mean that you can't change VS Code the entire app to be a different language?

**Comment by chenxqiyu** [comment]
> 

can't change VS Code the entire app to be a different language

**Comment by tanhakabir** [comment]
Do you have the language pack of the language you're interested installed?
