### ISSUE TITLE
terminal bloqueado

### ISSUE THREAD

**Issue by Cleidianaa** [microsoft/vscode#141648]
Issue Type: <b>Feature Request</b>

terminal esta bloqueado, não consigo digitar. 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 6.2.9200
Restricted Mode: No

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/label "needs more info" terminal
