### ISSUE TITLE
Wrap content in variables and watch views

### ISSUE THREAD

**Issue by asaf400** [microsoft/vscode#141665]
#81275
Thanks @kgfly I'll try this one again..

> During debugging, my variable names are long and its content is long too. So Variables/Watch/CallStack/Breakpoints windows cannot show all contents.
> 
> Please support customized font setting for debugger windows. If possible, I want to use smaller font in these windows.
> 
> Another request: if the variable is a list and its content is long, current window just show "...". So can the windows "wrap" the text and show all the contents?

The previous issue was closed, but the issue is high-profile and still remains,
consider this watch list item:
`response.headers["set-cookie"].map(x => x.split(";")[0]).join("; ")`

that is a 71 character watch expression which is actually reasonable if a developer doesn't want to save the value in a variable.

the only way to see the value of the expression during a breakpoint is either to expand the sidebar to more then 50% of the screen space, 
or use the debug console directly, but then the watchlist just becomes useless..

I ask that you reconsider the previous conclusion.

**Comment by weinand** [comment]
You can just move the watch view to the bottom:

<img width="1277" alt="CleanShot 2022-01-27 at 22 11 22@2x" src="https://user-images.githubusercontent.com/1898161/151444315-4ab1d7ed-9419-4d6e-81bd-e1004b6e816a.png">
