### ISSUE TITLE
Hello, teacher! VSCode is a great project that gives users the greatest autonomy from the very beginning, allowing users to personalize configurations according to their own habits, so it can fully surpass the long-born jetbrion series in just 5 years. The most important reason is that VSCode's open source thinking and allowing users to customize and configure VSCode development methods to the greatest extent can achieve today's achievements. I hope VSCode can continue to develop this way of thinking and development, focusing on every reasonable request of users and need. Thank you here!  vscode contributors 20220126

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#141621]
- VS Code Version: 1.63
- OS Version: Windows 10

Steps to Reproduce:

Hello, teacher!
VSCode is a great project that gives users the greatest autonomy from the very beginning, allowing users to personalize configurations according to their own habits, so it can fully surpass the long-born jetbrion series in just 5 years. The most important reason is that VSCode's open source thinking and allowing users to customize and configure VSCode development methods to the greatest extent can achieve today's achievements. I hope VSCode can continue to develop this way of thinking and development, focusing on every reasonable request of users and need. Thank you here!
https://github.com/microsoft/vscode/issues/134326
https://github.com/microsoft/vscode/issues/138457
https://github.com/microsoft/vscode/issues/132756
Hope to fix them in the next milestone, thank you so much teachers!
vscode contributors
20220126

**Comment by Tyriar** [comment]
Those issues are already tracked, no need to create another one calling them out as that just wasted the teams time triaging.

**Comment by zhouxinghong** [comment]
> Those issues are already tracked, no need to create another one calling them out as that just wasted the teams time triaging.

The following issues are not necessarily tracked and have been unresolved for a long time without any changes. . .
https://github.com/microsoft/vscode/issues/138457
https://github.com/microsoft/vscode/issues/132756

**Comment by zhouxinghong** [comment]
> > Those issues are already tracked, no need to create another one calling them out as that just wasted the teams time triaging.
> 
> The following issues are not necessarily tracked and have been unresolved for a long time without any changes. . . #138457 #132756

Fix these issues and there are no UI issues behind. . . thanks!

**Comment by Tyriar** [comment]
@zhouxinghong they're 2 issues out of over 5000. Consider their place when you sort that list of issues by upvotes from the community. We only have so many people on our team to resolve these problems but I see https://github.com/microsoft/vscode/issues/132756 is marked with help wanted if you're really passionate about it.

**Comment by zhouxinghong** [comment]
> 



> @zhouxinghong they're 2 issues out of over 5000. Consider their place when you sort that list of issues by upvotes from the community. We only have so many people on our team to resolve these problems but I see #132756 is marked with help wanted if you're really passionate about it.

Teacher, please take a closer look at the following problems. This problem was solved by 30% last year, and the remaining part was originally scheduled to be solved in the December 2021 version, but it was cancelled again. I hope it can be solved this time:
https://github.com/microsoft/vscode/issues/138457 this issue
