### ISSUE TITLE
Support Rider's Resharper EditorConfig values

### ISSUE THREAD

**Issue by marcusjwhelan** [microsoft/vscode#141646]

**Comment by marcusjwhelan** [comment]
Rider creates its own editorconfig values prepended with `resharper` but add a lot of value to how code editing is done. I am having trouble with formatting inconsistencies between a developer working in Visual Studio Code and myself working in Jetbrains Rider. Since Rider has more granular support for formatting than Visual Studio Code it is an issue of inconsistent formatting

I assume I would request this feature in VSC rather than on the editorconfig github since VSC would have to implement those features. Is this a possibility?

**Comment by Tyriar** [comment]
Editorconfig in vscode is an extension as you mention, the request would need to go there first and then they could propose APIs for us to implement if there are gaps.
