### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by eMerzh** [microsoft/vscode#141670]
Issue Type: <b>Bug</b>

Typescript language seems to crash a lot lately ....

not sure what it is ....

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 5, 5|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|--crash-reporter-id 6e3d370d-944d-41d5-9a12-996aeaee1914|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icalendar|af4|1.0.1
Bookmarks|ale|13.2.2
better-toml|bun|0.3.2
npm-intellisense|chr|1.4.0
vscode-github-actions|csc|0.21.3
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.1.0
auto-rename-tag|for|0.1.9
kotlin|fwc|0.2.23
vscode-pull-request-github|Git|0.34.3
vscode-graphql|Gra|0.3.41
terraform|has|2.19.0
npm-dependency-links|her|1.2.0
vscode-styled-components|jpo|1.7.0
vscode-github|Kni|0.30.7
graphql-for-vscode|kum|1.15.3
eml|lei|0.4.0
rainbow-csv|mec|2.0.0
dotenv|mik|1.0.1
ecdc|mit|1.4.0
language-gettext|mro|0.2.0
vscode-docker|ms-|1.19.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.3
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
workspace-settings-json|Nat|0.0.10
color-highlight|nau|2.5.0
abracadabra|nic|6.10.0
vscode-data-preview|Ran|2.3.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.3.0
rust|rus|0.7.8
mdx|sil|0.1.0
sort-lines|Tyr|1.9.1
errorlens|use|3.4.1
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
glean|wix|5.2.2
vscode-import-cost|wix|2.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsclayoutctrc:30425945
vsrem710:30416614
vsbas813:30426126

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
