### ISSUE TITLE
PHP syntax highlighting without <?php

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#14166]
VS Code currently highlights something that has the language ID `php` only if it is wrapped in `<?php` tags, and everything outside like HTML. That is wrong in a few ways. The code outside of `<?php` is not "php" language, it is whatever output you are using. So for a CLI application, code outside would just get printed to STDOUT, while in a webserver it would get send to the client, which means the language is dependend on the `Content-Type` header (it does not have to be text/html). Only the code _inside_ `<?php` tags should be considered PHP, the outside can actually be any language, like `html` or `plaintext`. As this is not defined anywhere, VS Code should autodetect and fallback to HTML as that is most used. The inside is then "injected" as PHP like JavaScript in a `<script/>` tag or CSS in a `<style/>` tag. Also see #1751.

This causes many issues:
1. PHP in markdown blocks don't get highlighted if they use the ```php tag and do not contain `<?php`. If you switch to preview or view the file on GitHub or any other editor, everything works fine.  
   ![image](https://cloud.githubusercontent.com/assets/10532611/19602026/df226f72-97ab-11e6-83d8-8867cfe52089.png)
2. If you `eval()` to evaluate code (which does not require `<?php` tags) and the PHP debugger breaks inside that code, VS Code does a `sourceRequest`. The reported code does not get syntax highlighted. This means the PHP debugger [needs to dynamically add this tag](https://github.com/felixfbecker/vscode-php-debug/blob/master/src/phpDebug.ts#L589), which also means that every breakpoint request, every stackframe location [needs to be shifted one line down](https://github.com/felixfbecker/vscode-php-debug/blob/master/src/phpDebug.ts#L539).
3. Like many language servers, [the PHP LS includes a declaration line in the HoverResponse](https://github.com/felixfbecker/php-language-server/pull/50). This declaration line is only colored if a `<?php` is included, which I would like to remove because it doesn't make sense: I declared the language to be PHP, so it should be highlighted as PHP. Other clients like Eclipse behave correctly here. Issue: https://github.com/felixfbecker/php-language-server/issues/105  
   ![hover](https://cloud.githubusercontent.com/assets/10532611/19514022/5b6a20cc-95f2-11e6-8e32-0f22857b3def.png)

**Comment by felixfbecker** [comment]
I would like to remove the `<?php` in the next release of PHPLS because all other clients work correctly here. Is there an approximate ETA for a fix in VS Code? Is it worth to hold back so users don't use highlighting in VS Code?

**Comment by mousetraps** [comment]
@felixfbecker started looking into this. Quick question, regarding your second bullet point - just to confirm - are you actually getting syntax highlighting for php blocks in the markdown editor (not preview)? Because even when I add `<?php`, preview properly renders, but the editor does not. 

![image](https://cloud.githubusercontent.com/assets/762848/20092104/1e29b5c0-a54b-11e6-90a3-74cd3af8cfd2.png)

**Comment by felixfbecker** [comment]
@mousetraps Yes, correct. The markdown preview is not affected. Thanks for looking into this

**Comment by mjbvz** [comment]
@felixfbecker, @mousetraps There's another bug tracking php syntax highlighting not working at all in markdown files: #3746 

I do not know what is different about the php here. We do properly recognize the fenced code block as a php fenced code block, but the language highlighter never seems to kick in.

**Comment by joaomoreno** [comment]
@mousetraps Removing this from January.

**Comment by roblourens** [comment]
I understand the argument but I don't know that it's likely to change soon.

@aeschli can you help me decide whether this fits into any planned work we have?

**Comment by aeschli** [comment]
I also understand the argument. But it looks like markdown worked around this as I see this working. I think it's ok to close, unless there are other issues blocked by this.
