### ISSUE TITLE
Add command corresponding to what the "Enter" key do in picker

### ISSUE THREAD

**Issue by Binly42** [microsoft/vscode#141697]
Currently, we all use and only be able to use `Enter` to select a item in pickers (like FilePicker, CommandPicker).

It would be great to have a corresponding command, with which we can define a custom shortcut to "select".

Especially useful when only our left hand is on the keyboard. 
In this case, we can define `Ctrl+Space`(only for pickers) to mock `Enter`.

---
Tested the command `list.select` not work.

**Comment by Binly42** [comment]
a workaround via AutoHotkey.

Define a mouse button hotkey to turn on a tmp mode. And when that mode On, let `Ctrl+Space` send `Enter` ...

**Comment by ArturoDent** [comment]
Try using this command: `workbench.action.acceptSelectedQuickOpenItem`:

```jsonc
{
  "key": "ctrl+space",
  "command": "workbench.action.acceptSelectedQuickOpenItem",
  "when": "inQuickOpen"
}
```
