### ISSUE TITLE
Split terminals don't have labels applied?

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#141686]
On Insiders Windows 10, I navigated to the src/typings directory of the vscode repo, and then split the terminal.
I noticed the first terminal said `typings`, but the ones after didn't.
![Demo](https://user-images.githubusercontent.com/7199958/151467894-2514f2d5-dc5d-4e1d-ad1a-9de2268b5c66.PNG)

**Comment by meganrogge** [comment]
regression related to this change:

https://github.com/microsoft/vscode/commit/0e45c9f2a2e8bdf173c5f662db3f9c18474622f4

**Comment by meganrogge** [comment]
to be clear, right now on Insider's, this does not work for you @Tyriar ?
![Recording 2022-01-28 at 11 07 02](https://user-images.githubusercontent.com/29464607/151590694-8c9c783e-8d38-4ca0-9f74-148f8a2bbc56.gif)
