### ISSUE TITLE
Programmatically add expressions to the watch window

### ISSUE THREAD

**Issue by benmcmorran** [microsoft/vscode#141613]
This is already possible by calling [the undocumented `debug.addToWatchExpressions` command](https://github.com/microsoft/vscode/blob/fe0e9a96d35f19129892827b45168916c560af84/src/vs/workbench/contrib/debug/browser/variablesView.ts#L647-L654) with an appropriately shaped input. I propose adding a documented built-in command with similar functionality.

```typescript
await vscode.commands.executeCommand("debug.addToWatchExpressions", {
    variable: { evaluateName: 'my expression to evaluate' },
});
```

**Comment by weinand** [comment]
The existing command-based approach is good enough for this rarely requested API.
