### ISSUE TITLE
Typescript language

### ISSUE THREAD

**Issue by jkunsman76** [microsoft/vscode#141600]
Issue Type: <b>Bug</b>

randomly generated when idle or running for a few minutes. 
started after python, pipenv, and pylint were installed 

The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

source TypeScript Langauge Features (extension)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (11.81GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/home/jkuns76/workspace/python-projects/rare/rare-client-smoky-pythons --remote=wsl+Ubuntu-18.04 --crash-reporter-id a44ebd99-944f-4453-ab7a-190f08935412|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (4 x 2592)|
|Memory (System)|2.85GB (0.07GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (4 x 2592)|
|Memory (System)|2.85GB (0.07GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (4 x 2592)|
|Memory (System)|2.85GB (0.07GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (4 x 2592)|
|Memory (System)|2.85GB (0.07GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer|Coe|1.0.62
remote-wsl|ms-|0.63.13
jinja|who|0.0.8
material-theme|zhu|3.13.16
vscode-sqlite|ale|0.14.0
vscode-django|bat|1.8.0
multi-cursor-case-preserve|Car|1.0.5
vscode-faker|dee|1.5.0
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
gitlens|eam|11.7.0
vscode-test-explorer|hbe|2.21.1
vsc-python-indent|Kev|1.14.2
vscode-python-test-adapter|lit|0.7.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.3
jupyter|ms-|2021.11.1001550889
test-adapter-converter|ms-|0.1.5
sqltools|mtx|0.23.0
autodocstring|njp|0.5.4
code-spell-checker|str|2.1.4
tabnine-vscode|Tab|3.5.17
vscodeintellicode|Vis|1.2.16
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30424896
pythonvs932:30410667
vscop804cf:30404767
vs360cf:30404996
vsclayoutctrt:30425946
vsrem710cf:30416617
vsbas813:30426126

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by jkunsman76** [comment]
let me test it with the extensions disabled and ill get back to you

**Comment by mjbvz** [comment]
Closing as more info needed
