### ISSUE TITLE
Unable to resolve your shell environment: Unexpected exit code from spawned shell (code null, signal SIGABRT)

### ISSUE THREAD

**Issue by glennbach** [microsoft/vscode#141674]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: 11.6.2

Steps to Reproduce:

1. Run VSC on Mac (not from terminal)
2. Error pops up saying it couldn't resolve the shell environment due, not to excessive time, but an unexpected exit code. It receives a SIGABRT.

Doesn't give the error when `code` is run from a regular system terminal. This only started happening a couple months ago.

**Comment by joaomoreno** [comment]
If you run <kbd>F1</kbd>, `Developer: Toggle Developer Tools`, is ther anything interesting in the Console?

Otherwise, can you run it from a syterm terminal with `--force-user-env --log trace`, then open the Output view in VS Code, the `Log (Main)` log and search in there for `getUnixShellEnvironment`?

![image](https://user-images.githubusercontent.com/22350/151511674-e0c77bb7-5afe-4c2a-8649-6265d5eb51aa.png)

**Comment by glennbach** [comment]
From the former, I don’t see much:

notificationsAlerts.ts:42 Unable to resolve your shell environment: Unexpected exit code from spawned shell (code null, signal SIGABRT)
onDidChangeNotification @ notificationsAlerts.ts:42
log.ts:313   ERR [Extension Host] (node:10822) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Electron --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:10822) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Electron --trace-deprecation ...` to show where the warning was created)
I @ console.ts:137

From the latter I also see:

[2022-01-31 12:24:20.006] [main] [trace] getUnixShellEnvironment#stderr dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO

which is peculiar… 

This all worked fine a couple months ago, so I don’t know if the change was on my end or the code’s end.

Thanks,

Glenn

**Comment by joaomoreno** [comment]
You have to go dig into your `.bashrc` or `.zshrc` file and figure out what's inside that might cause that issue.

**Comment by glennbach** [comment]
It’s actually the Electron call that is failing:

[2022-02-02 15:56:14.530] [main] [trace] getUnixShellEnvironment#spawn ["-ilc"] '/Applications/Visual Studio Code.app/Contents/MacOS/Electron' --ms-enable-electron-run-as-node -p '"cfc5d3b9a1e9" + JSON.stringify(process.env) + "cfc5d3b9a1e9"'

My .bashrc file is essentially empty.

If I just try to run Electron from a terminal, I get the same error:

$ /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
Abort trap: 6


Glenn

**Comment by joaomoreno** [comment]
Oh! Interesting. @deepak1556 can you take it from here?

**Comment by deepak1556** [comment]
Looks like you have `DYLD_LIBRARY_PATH` setup somewhere in your shell profile, the libraries that are loaded mess up the with symbols required from the `Electron` binary, can you try unsetting it.

**Comment by glennbach** [comment]
Ah, it wasn't in my .bashrc, but in my .profile. Something must have recently changed in Electron that triggered this.

Thanks!
