### ISSUE TITLE
Imports are not updated if folder is moved (JavaScript project)

### ISSUE THREAD

**Issue by HolgerSeith** [microsoft/vscode#141626]
Issue Type: <b>Bug</b>

JavaScript imports are not updated if folder is moved inside project.

Steps to repro:
- Move folder (containing JavaScript files) to another parent via DnD
- See that references from outside to the (implicitly) moved files are not updated

Settings:
- "javascript.updateImportsOnFileMove.enabled": "always",

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.64GB (49.70GB free)|
|Process Argv|application --crash-reporter-id 40965713-e090-4791-a568-26f683c5c826|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
markdown-mermaid|bie|1.13.1
jsonviewer|cci|1.2.2
npm-intellisense|chr|1.4.0
js-codeformer|cms|2.6.1
jsrefactor|cms|3.0.1
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.1.0
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.1.0
vscode-mocha-test-adapter|hbe|2.13.0
vscode-test-explorer|hbe|2.21.1
vscode-drawio|hed|1.6.4
plantuml|jeb|2.17.2
vscode-styled-components|jpo|1.6.6
test-adapter-converter|ms-|0.1.5
vsliveshare|ms-|1.0.5273
abracadabra|nic|6.10.0
vscode-react-refactor|pla|1.1.3
psi-header|psi|1.17.0
java|red|1.3.0
vscode-coverage-gutters|rya|2.9.1
code-spell-checker|str|2.1.4
errorlens|use|3.4.1
vscodeintellicode|Vis|1.2.16
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0
vscode-icons|vsc|11.8.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30428979
pythonvs932:30410667
wslgetstarted:30426333
vscop804:30404766
vscop453:30404998
vsrem710:30416614
vsbas813:30426126

```

</details>

**Comment by sbmelvin** [comment]
They honestly just need to remove this feature entirely. It's been broken for years.

**Comment by mjbvz** [comment]
Please share a project that demonstrates this issue. I just tested this and it seems to work fine for me

I suspect that you may not have a JSConfig in place which would allow VS Code to understand the structure of your JS project

**Comment by mjbvz** [comment]
Also double check that you have saved the files. On move, VS Code will open all of the edited files but not actually save them. This makes it easy to overlook edits until you either save or try closing the files

**Comment by sbmelvin** [comment]
The feature works when moving individual files or directories. It does not work if you select multiple files and drag them into another folder. What happens is the first file that is being moved will be changed, but the others will not be. It's not just JS either, it was reported nearly [two years ago](https://github.com/microsoft/vscode/issues/105110) that it doesn't work with TS either.

**Comment by mjbvz** [comment]
Yes multiple folders is already being tracked by #105110 

I'm closing this due to lack of feedback on this issue
