### ISSUE TITLE
Add `source.removeUnused` action to `codeActionsOnSave`

### ISSUE THREAD

**Issue by benPesso** [microsoft/vscode#141671]
VS Code has a few useful `codeActionsOnSave` actions for code cleanup and organization, but it is missing a crucial option to only remove unused imports.

In Flutter, it is often common to separate "platform imports" (Flutter libraries, external packages, etc.) from local imports (app-specific classes and assets) with an empty line; sometimes even with 3 separate sections of imports, like so:

```dart
import 'dart:convert';
import 'dart:typed_data';

import 'package:app/core/utilities/image_tools.dart';
import 'package:app/users/user_model.dart';

import 'package:flutter/material.dart';
```
_** The second section above contains the app-specific imports._

Currently, running the `Organize Imports` command removes the unused imports, but also sorts the remaining ones, AND removes any empty lines in between. However, using the `Quick Fix` menu to remove unused imports from the file does exactly what you'd expect; removing the unused imports without touching the order or spacing of the remaining imports.

Ideally, I would expect the `source.organizeImports` action to: 1) retain the spacing (while removing duplicate empty lines), 2) sort each import-block separately, and 3) remove unused imports within each import-block.

Alternatively, as the title says, having a`source.removeUnused` action that **only** removes unused imports - without sorting or organizing - will also work, as it will at least allow users to maintain the existing formatting.

**Comment by mjbvz** [comment]
Additional source actions can be contributed by extensions. JS/TS for example already implements this as `source.removeUnused` (it removed all unused code in the current file)

Please file an issue against Flutter if you want to see a `source.removeUnused` supported there as well
