### ISSUE TITLE
`zh-tw` language breaks settings editor layout

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#141614]
Maybe this is a different issue, but when I set Display Language as `zh-tw`
The Settings display like this, some text covered others
![截圖 2022-01-26 下午5 04 20](https://user-images.githubusercontent.com/4269720/151134681-b8ae2aa0-5561-4391-b291-c334cca078c2.png)
And I tried with `zh-cn`, it seems regular
![截圖 2022-01-26 下午5 08 00](https://user-images.githubusercontent.com/4269720/151134975-0467fe59-f985-486b-8dfa-a2659e5e955a.png)

If this is another issue, where should I report it?

_Originally posted by @marsen in https://github.com/microsoft/vscode/issues/141354#issuecomment-1022006039_

**Comment by rzhao271** [comment]
1. Switch display language to French
2. Navigate to the Settings UI, and zoom out a bit
3. Search "nest"
4. :bug: Rendering glitch

**Comment by rzhao271** [comment]
Regression caused by https://github.com/microsoft/vscode/issues/135677.

**Comment by rzhao271** [comment]
Verification steps:
1. Switch to the French language pack.
2. In the Settings editor, search for `workbench.editor.pinnedTabSizing`.
3. Verify there is no error message saying something about how `lastIndexOf` cannot be applied to `undefined` in the console.
4. Navigate around the Settings editor, and confirm that the rendering is not glitched.
