### ISSUE TITLE
PWA: No error message when an image fails to load

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#141604]
Testing #141296

Repro steps:
- Open a remote repo that contains pngs in https://insiders.vscode.dev/, but do not open any of the images
- Go offline, wait for the red status bar + "offline" message to appear
- Try to open a file, see a "Failed to fetch" message appear
- Try to open an image, it is infinitely loading, while there is an error message in the dev tools: `Activating extension 'vscode.image-preview' failed: Failed to fetch.`

**Comment by joaomoreno** [comment]
This might be the image editor in VS Code which doesn't handle error situations that well.

**Comment by mjbvz** [comment]
I believe this is essentially #96407

Not sure why the error doesn't get surfaced here though
