### ISSUE TITLE
Debug Console Search Filter Should Clear on Re-Open

### ISSUE THREAD

**Issue by mrebe97** [microsoft/vscode#141682]
The search filter in the debug console should clear on closing/re-opening VSCode. I was trying to run a test and de-bug, and I was confused because logs were missing. In reality, they weren't showing up because the filter than had been in place earlier was filtering them out.

**Comment by roblourens** [comment]
I am actually not sure about this. I suspect it should be persisted like pretty much every other input box in vscode. I also checked with Chrome devtools and they persist the filter. Is the problem maybe more just that it wasn't obvious that there was a filter applied?

**Comment by haugerbr** [comment]
@roblourens yes I think the problem is more awareness that values are persisted from a previous session. I could see something like a banner at the top of the terminal saying something like "Filtering zto console output that matches the string 'inputstring'".
