### ISSUE TITLE
Unexpectedly closing the window.

### ISSUE THREAD

**Issue by Tharun-Jannu** [microsoft/vscode#141658]
Issue Type: <b>Performance Issue</b>

When i try to open the folder it unexpectedly closing the window.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.86GB free)|
|Process Argv|--crash-reporter-id 0ce1ee54-7c47-4ce2-b433-1f45c8c35e93|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    92	 14588	code main
    1	    54	  2668	   issue-reporter
    0	   192	  3452	   extensionHost
    0	    99	  5152	   window (Get Started - Visual Studio Code [Administrator])
    0	    66	 10868	   shared-process
    0	    33	 21596	     ptyHost
    0	    95	 12752	   gpu-process
    0	    14	 19232	   crashpad-handler
    0	    25	 20292	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.7.0
vscode-eslint|dba|2.2.2
vscode-npm-script|eg2|0.3.24
search-node-modules|jas|1.3.0
vscode-codemetrics|kis|1.24.0
node-module-intellisense|lei|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.3
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
azure-account|ms-|0.9.11
vsliveshare|ms-|1.0.5273
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.13.0
vscode-for-node-js-development-pack|nod|2.0.1
LiveServer|rit|5.7.4
code-settings-sync|Sha|3.4.3
open-in-browser|tec|2.0.0
nodejs-extension-pack|wad|0.1.9
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30428979
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710:30416614
vsbas813:30426126

```

</details>

**Comment by rzhao271** [comment]
Sounds like a crash. Are you able to get a crash dump?
https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
