### ISSUE TITLE
Distribute `typescript-language-features` as a standalone package

### ISSUE THREAD

**Issue by TonyPapousekLC** [microsoft/vscode#141690]
I prefer VSCode's built-in `.ts` language features. For cross-compatibility reasons, my team is stuck using [The Mangler](https://prettier.io/).

I'd love if VSCode's version could be installed as a Node package and used within CICD flows.

**Comment by mjbvz** [comment]
The built-in extension uses TypeScript for formatting. You can use typescript directly or tools like `tsfmt` to run the same formatter VS Code uses
