### ISSUE TITLE
Shell integration zsh hooks don't load on macOS/Linux sometimes

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#141620]
Testing #141339

I get this error in the terminal, on Linux using zsh

```
/snap/code-insiders/917/usr/share/code-insiders/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-zsh.sh: 50: /snap/code-insiders/917/usr/share/code-insiders/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-zsh.sh: Syntax error: word unexpected (expecting ")")
```

```
$ zsh --version
zsh --version
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
```

**Comment by Tyriar** [comment]
Can repro with plain zsh installed via apt

**Comment by Tyriar** [comment]
It's a shame but let's defer, we can call out that there's a known issue with zsh in the release notes.

**Comment by Tyriar** [comment]
There's also some issue @rzhao271 was hitting which seems related to using macOS' default zsh, not the homebrew install https://github.com/microsoft/vscode/issues/140784#issuecomment-1023558494

**Comment by gmessow-cxomni** [comment]
I had the same problem with under Linux (with oh-my-zsh, don't know if this relevant).

The following changes to the integration shell script helped:

Add as first line: #!/bin/zsh 

Added at line 49:
typeset -a precmd_functions preexec_functions

Change line 50 and 51 to:
precmd_functions+=(precmd)
preexec_functions+=(preexec)

**Comment by Tyriar** [comment]
@gmessow-cxomni thanks for the info, I'm relatively new to zsh scripting so this should be handy

**Comment by Tyriar** [comment]
Spent some time looking into this and here's my understanding of what's happening. We launch zsh with shell integration using:

```
zsh -c '"${execInstallFolder}/out/vs/workbench/contrib/terminal/browser/media/shellIntegration.zsh"; zsh -i'
```

Since `-c` is used, autoload, add-zsh-hook, etc. aren't available which is messing everything up. I don't know why results are inconsistent across machines but that's the theory, so the fix would be to move to something closer to what bash does where we source rc/profile within the shell integration script.

**Comment by roblourens** [comment]
Can't verify, due to https://github.com/microsoft/vscode/issues/143389

**Comment by Tyriar** [comment]
Added verification steps needed to deter people from trying until it's fixed (hopefully today or tomorrow: https://github.com/microsoft/vscode/issues/143629)

**Comment by Tyriar** [comment]
Ready to verify after today's insiders goes out
