### ISSUE TITLE
File path completion for Markdown triggers listing unrelated completions

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#141610]
Testing #141327

Trying to complete to file paths also listed things like headings for completions as we

![image](https://user-images.githubusercontent.com/54418/151267220-a0852f4b-e654-47b4-a687-cfce3c0a14e7.png)

This does not seem to happen for completions for link declarations.

**Comment by mjbvz** [comment]
I believe this is expected. The additional items (`bold`, `code`, ...) are snippet completions which VS Code provides automatically whenever completions are shown. I don't think there's a way to hide them (although users can disable them with `editor.snippetSuggestions` if they wish)
