### ISSUE TITLE
Attempting to open a file from the commandline (or via git editor) fails to open file

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#14164]
- VSCode Version: `Version 1.7.0-insider (1.7.0-insider)` 69fe34632fa4651e89db040fb205f0c739598197
- OS Version: `macOS Sierra 10.12 (16A323)`

Steps to Reproduce:

1. Try opening a file from the command line `code foobar.md`
2. Almost all of the time it will open code without any file at all (it worked once)

Or

1. Using code as your git editor have git open the editor (via commit or interactive rebase)
2. Almost all of the time code will open blank

This is a regression in 69fe34632fa4651e89db040fb205f0c739598197 as yesterday's build worked fine.

**Comment by eamodio** [comment]
@roblourens fyi -- I haven't yet seen the issue since upgrading to 788caba5a3ca1c2b137353f4384bb0e026db1a31

**Comment by joaomoreno** [comment]
These commits seem unrelated to the issue. But if it doesn't happen anymore, I'll just close it.

**Comment by eamodio** [comment]
@joaomoreno maybe it was related to hot exit as that was reverted in that time: https://github.com/Microsoft/vscode/commit/9d681961685b69cc0bd940f4d6a4dacf15386201

But I'll let you know if I see it again

**Comment by roblourens** [comment]
@joao It wasn't that commit, it was between that commit and the previous insider's build.

@eamodio This sounds familiar now... I think it was fixed
