### ISSUE TITLE
VS CODE SSH connection reconnect

### ISSUE THREAD

**Issue by zohimchandani** [microsoft/vscode#141608]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2 
- OS Version: Mac OS Big Sur 11.6 

Steps to Reproduce:

1. Prior to VS code, I would connect to my company VPN, set up port forwarding, connect via ssh to a GPU cluster, use `tmux` to keep the terminal alive and request for a jupyter notebook on a given port, open the kernel link on a browser and use the kernel to get a notebook running, disconnect VPN, log back in after some time, connect again and the notebook would still be running. 

2. Now I have set up VS code to connect via ssh to host and can run my `.ipynb` files on the server directly in VS code. However, when I close of my laptop and log back in, the kernel dies. I tried to use `tmux` to keep the terminal alive behind the scenes but not sure how to prevent the kernel from dying when I disconnect the VPN connection? 

Is there a way to get large jobs to run on VS code when connected to host via SSH, disconnect and come back later?

**Comment by roblourens** [comment]
See https://github.com/microsoft/vscode-jupyter/issues/3998 and https://github.com/microsoft/vscode-remote-release/issues/3096
