### ISSUE TITLE
Fails to render pointer icon underneath cursor in Editor while in debug mode.

### ISSUE THREAD

**Issue by henry-js** [microsoft/vscode#141631]
Issue Type: <b>Bug</b>

Unicode pointer arrow fails to render underneath cursor when in debug mode:
![vscode-fails-to-render-icon](https://user-images.githubusercontent.com/79054685/151329034-913545ad-c105-43c8-be22-0077018efb78.gif)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.88GB (4.14GB free)|
|Process Argv|--crash-reporter-id 60aad9c9-8c82-47be-85ae-8f34e579ffa3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.1
vscode-markdownlint|Dav|0.45.0
dendron|den|0.79.0
dendron-paste-image|den|1.1.0
vscode-peacock|joh|4.0.0
lorem-space|Man|0.1.3
rainbow-csv|mec|2.0.0
csharp|ms-|1.24.0
powershell|ms-|2021.12.0
material-icon-theme|PKi|4.12.1
vscode-thunder-client|ran|1.11.0
vscode-xml|red|0.18.2
vscode-sort-json|ric|1.20.0
swdc-vscode|sof|2.6.25
msbuild-project-tools|tin|0.4.3
learn-vim|vin|0.0.27
vim|vsc|1.21.10
markdown-all-in-one|yzh|3.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30428979
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710cf:30416617
vsbas813:30426126

```

</details>

**Comment by weinand** [comment]
@hediet is this something related to your unicode work?

**Comment by hediet** [comment]
> @hediet is this something related to your unicode work?

Not the unicode highlighting feature, but maybe injected text adoption, though unlikely.
