### ISSUE TITLE
ssh agent connectivity: "Error connecting to agent: No such file or directory"

### ISSUE THREAD

**Issue by glennbach** [microsoft/vscode#141678]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.63.2
- OS Version: 11.6.2

Steps to Reproduce:

1. Run VSC on Mac
2. run `ssh-add -k` from VSC terminal

Error: `Error connecting to agent: No such file or directory`

This breaks all my ssh connections.

It works fine from a regular Mac terminal.

**Comment by codeboten** [comment]
Can confirm I saw this also running 1.63.2 on MacOS 11.6.2.

I ended up removing VSCode, installing an older version and upgrading back to 1.63.2 and it's no longer exhibiting that behaviour.

**Comment by glennbach** [comment]
I removed it and installed 1.63.1, then let it update, updating to 1.64, and now the problem is gone.
