### ISSUE TITLE
handleUri(uri: vscode.Uri) function can't get access to the 'fragment' part of the URI 

### ISSUE THREAD

**Issue by aadarshp31** [microsoft/vscode#141640]
I am creating a Vs Code web extension with OAuth2 based authentication (similar to Github Authentication in VS Code), upon successful authentication, redirects to a specific URI like the one shown below. This URI, unfortunately, contains the auth credentials in the fragment part (i.e. starts with the "#" character). This "#" character and the credentials are added by the OAuth server.

Redirect URI from OAuth server:
https://vscode.dev/callback?vscode-reqid=1&vscode-scheme=vscode&vscode-authority=myPublisher.foo-web-extension&vscode-path=%2Fdid-authenticate#&access_token=XXXX&expires_in=XXXX&location=XXXX&api_domain=XXXX

I'm accessing this URI inside the extension's source using the below code:

```
context.subscriptions.push(vscode.window.registerUriHandler({
    handleUri(uri: vscode.Uri): vscode.ProviderResult<void> {
        console.log(uri);
    }
}));
// output: { "$mid": 1, "path": "/did-authenticate", "scheme": "vscode", "authority": "myPublisher.foo-web-extension" }

```
**_Note here that the 'fragment' part of the vscode.Uri instance is not present in the output_**
The URI object doesn't contain the fragment part (i.e. `#&access_token=XXXX&expires_in=XXXX&location=XXXX&api_domain=XXXX`) which is required to log the user in the extension.

### Questions:
1. I can't log the user in until I can access the OAuth credentials from this URI. Is there any way the handler function can get access to the fragment part of the URI? Any workaround?

2. I'm using vscode.env.openExternal to initiate the login process, which opens a new tab. Is there another option to open the same process in a popup window using VS Code's Extension API? Github Authentication uses a popup window for the same. I wasn't able to find the particular VS Code's Extension API.

### What I've tried?
* Removing the '#' part from the URI solves the issue as all the credential information gets included in the `uri.query` object. So, I've reached out to the OAuth provider for removing the "#" character and providing credentials in queryString only, but haven't got a solution from them as of now.

### Steps to Reproduce:
_Reproducing error during VS Code web extension development_
1. Create a URI for the VS Code's extension to listen for using the below code.
```
const redirectURI = (await vscode.env.asExternalUri(vscode.Uri.parse(vscode.env.uriScheme + '://myPublisher.foo-web-extension/did-authenticate'))).toString()
```
2. Attach this redirectURI to OAuth2 login URI for your provider and open the resultant loginURI using the `vscode.env.openExternal` method and perform authentication. The OAuth2 authentication provider I'm using redirects to a link containing credential details appended as fragment part. 
i.e. `https://vscode.dev/callback?vscode-reqid=1&vscode-scheme=vscode&vscode-authority=myPublisher.foo-web-extension&vscode-path=%2Fdid-authenticate#&access_token=XXXX&expires_in=XXXX&location=XXXX&api_domain=XXXX`
```
const loginUri = await getLoginUri(redirectURI);
await vscode.env.openExternal(loginUri);
```
3. Listen for the URI event and register a URI handler method to get and save auth credentials.
```
context.subscriptions.push(vscode.window.registerUriHandler({
    handleUri(uri: vscode.Uri): vscode.ProviderResult<void> {
        console.log(uri);
    }
}));
// output: { "$mid": 1, "path": "/did-authenticate", "scheme": "vscode", "authority": "myPublisher.foo-web-extension" }
```
4. As the credential details are present in the fragment part of the redirect URI, the resultant 'uri' I'm getting is having no credential details. We can get access to the credentials details only if we can get access to the fragment part of this 'uri'.

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
Embedder: vscode.dev

**Comment by joaomoreno** [comment]
> This URI, unfortunately, contains the auth credentials in the fragment part

That's essentially the problem here, unfortunately.

We actually merge in query params and ignore external fragments. The reason for that is that we might accidentally overwrite the initial fragment you might've put in the original URI. This works out usually pretty OK, since most OAuth implementations simply add additional query params. Your specific OAuth server decided to instead use the fragment portion of the URL.

If they would use the query params, the URL would look like this instead: `https://vscode.dev/callback?vscode-reqid=1&vscode-scheme=vscode&vscode-authority=myPublisher.foo-web-extension&vscode-path=%2Fdid-authenticate&access_token=XXXX&expires_in=XXXX&location=XXXX&api_domain=XXXX`, and we'd correctly translate it to `vscode://myPublisher.foo-web-extension/did-authenticate?access_token=XXXX&expires_in=XXXX&location=XXXX&api_domain=XXXX`.

Is there any chance you have control over the OAuth server and can change that implementation to not use the fragment part of the URI?>

**Comment by aadarshp31** [comment]
> Is there any chance you have control over the OAuth server and can change that implementation to not use the fragment part of the URI?

I don't have any control over the OAuth server or it's implementation. I was hoping if we can get an optional API to get fragments from the URI or any workaround for this issue. 

Google OAuth also uses fragment part to attach auth details in the redirect URI. So there will be a demand for such a solution soon (if not already). [learn more here](https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow#oauth-2.0-endpoints_2)



> 2\. I'm using vscode.env.openExternal to initiate the login process, which opens a new tab. Is there another option to open the same process in a popup window using VS Code's Extension API? Github Authentication uses a popup window for the same. I wasn't able to find the particular VS Code's Extension API.

I was also hoping to get a solution for this case as the popup window option is better for our use case while asking the user to authenticate instead of switching to a new tab.

**Comment by joaomoreno** [comment]
> I was also hoping to get a solution for this case as the popup window option is better for our use case while asking the user to authenticate instead of switching to a new tab.

Do you mind filling this a new separate issue, so we mark it a feature request?

**Comment by aadarshp31** [comment]
> 2\. I'm using vscode.env.openExternal to initiate the login process, which opens a new tab. Is there another option to open the same process in a popup window using VS Code's Extension API? Github Authentication uses a popup window for the same. I wasn't able to find the particular VS Code's Extension API.

For sure! Will create a new issue for `Question 2`

> I was hoping if we can get an optional API to get fragments from the URI or any workaround for this issue.

Can we do anything regards to this line?

**Comment by joaomoreno** [comment]
Yeah. I think the best behavior would be to overwrite the fragment, if the OAuth gives us one and the original URI also had one.

**Comment by aadarshp31** [comment]
Any timeline on this fix?

**Comment by joaomoreno** [comment]
Just fixed this in our vscode-dev sources. By tomorrow, insiders.vscode.dev should have the fix.

**Comment by aadarshp31** [comment]
Thanks, @joaomoreno, and every developer who worked on this feature update. I really needed this fix and your efforts mean a lot to my team and me. We are grateful.

**Comment by joaomoreno** [comment]
This bug has been fixed in to the latest release of VS Code Insiders for the Web!

@aadarshp31, you can help us out by confirming things are working as expected in the latest Insiders release. If things look good, please leave a comment with the text /verified to let us know.

Happy Coding!

**Comment by aadarshp31** [comment]
Hi, @joaomoreno I tested things out with my project and everything works as expected. /verified
Thanks again!
