### ISSUE TITLE
VSCode 1.63 making Gradle C++ Compilation Slow

### ISSUE THREAD

**Issue by jwsv61099** [microsoft/vscode#141606]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.63
- OS Version: RHEL 7.9

Steps to Reproduce:

1. Gradle 3.5
2. VSCode Version 1.63
3. Compile C++ project with gradle and ensure vscode is open
4. Compilation should be slow
5. Close vscode
6. Recompile C++ project with gradle, it should be faster

Hi there!

I work on an offline system, and we recently brought over VSCode 1.63.  We have a mature project which uses an old version of Gradle to build our C++ Code; we noticed our compilation has slowed down considerably since bringing over vscode 1.63.

After doing some digging we noticed when we have VSCode closed, compilation is what it was before. When vscode is open compilation is incredibly slow; one of my team members did some digging and he said it might have to do with how VSCode watches the files? One thing to note, we do not ever remember this issue happening with past versions of VSCode. We tested this issue by disabling the C++ Extension too and the same issue occurs.

Any ideas as to why this would be happening?

Getting any sort of logs will be really difficult to get since I work on an offline system, so if there are any ideas as to what's happening, I can see what I can do in terms of logs that could be used to sort this issue out.

Thanks!

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
