### ISSUE TITLE
Suggestions on solving the slow loading of code server network

### ISSUE THREAD

**Issue by chenxqiyu** [microsoft/vscode#141693]
\vscode\out\server-main.js

const server = http.createServer(async (req, res) => {
                    res.setHeader("Cache-Control","max-age=9999999999");

Because the code server is in use, there are too many files and the loading is very slow, up to 52mb. Adding cache control avoids repeated loading in the use of code server and speeds up the loading speed.
【res.setHeader("Cache-Control","max-age=9999999999");】

**Comment by alexdima** [comment]
Good idea! We have added `Cache-Control` to the requests which can be safely cached on the client-side and we implemented `Etag`/`If-None-Match` for the other requests. Which request in particular do you think can be safely cached clint-side?
