### ISSUE TITLE
operating system independent home folder variable

### ISSUE THREAD

**Issue by imthenachoman** [microsoft/vscode#141657]
- On Linux and macOS the user's home folder variable is `$HOME`.
- On Windows it is `%userprofile%`.

This means, if you need to reference something you have to specify it twice: once for Linux/macOS and once for Windows.

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "options": {
        "env": {
            "SOME_VAR": "${env:HOME}/path/to/file"
        }
    },
    "windows": {
        "options": {
            "env": {
                "SOME_VAR": "${env:userprofile}\\path\\to\\file",
            }
        }
    }
}
```

If VS Code had an environment variable (like https://code.visualstudio.com/docs/editor/variables-reference) that pointed to the running OS' home then it would simplify things in `tasks.json`.

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "options": {
        "env": {
            "SOME_VAR": "${userHome}{pathSeparator}path{pathSeparator}to{pathSeparator}file"
        }
    }
```

Pretty please? With sugar on top?

**Comment by Bruce-Hopkins** [comment]
Can I work on this issue?

**Comment by imthenachoman** [comment]
Happy to test if needed.

Another idea I had, if it is easier or makes more sense, is nested variables processed in order. For example, something like:

```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "variables": {
        "MY_HOME": "${env:HOME}",
        "windows": {
            "MY_HOME": "${env:userprofile}"
        },
    },
    // then we could use ${MY_HOME} anywhere else....
    // and this would need to be in tasks.json for collaborative development reasons
}
```

**Comment by alexr00** [comment]
@Bruce-Hopkins you are welcome to work on it!

First, let's make the first parameter of `recursiveResolve` here a new type which is `IProcessEnvironement & {userHome: URI}`. 
https://github.com/microsoft/vscode/blob/e7b3724e0cdc9095d73a06b47203baa2c1777ea8/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L124-L125

Then, you'll need to get the userhome value somewhere around here:
https://github.com/microsoft/vscode/blob/e7b3724e0cdc9095d73a06b47203baa2c1777ea8/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L95-L96

For an example of how to get userhome (you won't need the preferLocal options):
https://github.com/microsoft/vscode/blob/c8e2fd7baeaa8cd9dc43d3051db66a7428309c97/src/vs/workbench/services/dialogs/browser/simpleFileDialog.ts#L246-L249

Finally, the variable name will need to be added into this switch:
https://github.com/microsoft/vscode/blob/e7b3724e0cdc9095d73a06b47203baa2c1777ea8/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L224-L225

**Comment by Bruce-Hopkins** [comment]
@alexr00 thanks! I appreciate the detailed response. If you could help, I have a few questions.

1. I apologize, but I don't understand what needs to be changed here.
https://github.com/microsoft/vscode/blob/e7b3724e0cdc9095d73a06b47203baa2c1777ea8/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L95-L96

2. I'm trying to make a function to get the home path like the example:
https://github.com/microsoft/vscode/blob/c8e2fd7baeaa8cd9dc43d3051db66a7428309c97/src/vs/workbench/services/dialogs/browser/simpleFileDialog.ts#L246-L249

But in the constructor, we don't receive the ```IPathService``` interface. Do I add an optional parameter to this constructor or is there a better way?

https://github.com/microsoft/vscode/blob/e7b3724e0cdc9095d73a06b47203baa2c1777ea8/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L43-L44

**Comment by alexr00** [comment]
> 1. I apologize, but I don't understand what needs to be changed here.

Once you make the first change ("First, let's make the first parameter of recursiveResolve here a new type which is IProcessEnvironement & {userHome: URI}."), you'll need to update the first parameter on that line.

> But in the constructor, we don't receive the IPathService interface. Do I add an optional parameter to this constructor or is there a better way?

Yep, an optional parameter is the way to get `IPathService` here.

**Comment by Bruce-Hopkins** [comment]
Is this good? I made the param a union type. Will this prevent needing to make any changes to the `envVariablesPromises`

https://github.com/Bruce-Hopkins/vscode/blob/35db2798d860e63f2fcb0ddd45bff98b16e8a09d/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L128-L129

Also, I'm trying to find a way to use `pathService`, but I don't think I can return the result in the switch statement because the function is asynchronous.

https://github.com/Bruce-Hopkins/vscode/blob/35db2798d860e63f2fcb0ddd45bff98b16e8a09d/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L193-L196
