### ISSUE TITLE
Improve default settings formatting when folding is disabled

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#14169]
- VSCode Version: insiders
- OS Version: os x

Steps to Reproduce:
1.  set "editor.folding": false,
2. Open settings file -> notice how it is weirdly indented

Either force that file to always have folding no matter the setting or do not indent my settings when folding disabled.

**Comment by sandy081** [comment]
This indentation in settings is not new and was there from before. Agreed that when user disabled folding, we should take an alternate approach for displaying settings properly.

**Comment by bpasero** [comment]
I think this does not apply anymore.
