### ISSUE TITLE
The setting `editor.wordWrap`'s performance is very bad.

### ISSUE THREAD

**Issue by lolimay** [microsoft/vscode#141618]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: Darwin x64 20.6.0

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Steps to Reproduce:

1. Prepare a large file with long text per line (over 60K lines of text)
2. Open the setting `editor.wordWrap: on` in the `settings.json` 
3. You propably get a "The window is not responding" dialog 😕
4. Switch the setting to `editor.wordWrap: off`, you can open this file within 100ms (in my feel)

<img width="314" alt="image" src="https://user-images.githubusercontent.com/32427260/151285096-fb087ef6-0d08-4b2d-b727-26a981896356.png">

**Comment by alexdima** [comment]
@lolimay Have you configured the setting `"editor.wrappingStrategy"` to `"advanced"`?
```js
// Controls the algorithm that computes wrapping points.
//  - simple: Assumes that all characters are of the same width.
// This is a fast algorithm that works correctly for monospace 
// fonts and certain scripts (like Latin characters) where glyphs 
// are of equal width.
//  - advanced: Delegates wrapping points computation to the browser. 
// This is a slow algorithm, that might cause freezes for large files, 
// but it works correctly in all cases.
"editor.wrappingStrategy": "simple"
```

**Comment by lolimay** [comment]
> ```js
> ser. 
> // This is a slow algorithm, that might cause freezes for large 
> ```

Yes, I configured "editor.wrappingStrategy" to "advanced". Is there any config like `editor.maxWordWrapLines` to disable this feature for large files. I can bear the wordWrap disabled when opening large files (like `pacakge-lock.json`) but don't want it cause my editor to `The window is not responding`.

The worse thing is that even if you `Close` the editor and restart it, since the active file is still that one, the editor gets stuck again. I can't solve the problem and stuck in an endless loop.

**Comment by lolimay** [comment]
Revert to `"editor.wrappingStrategy": "simple"`, everything works fine now, thanks for your help!
