### ISSUE TITLE
Side Panel doesn't automatically show terminal view if it's the only one there

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#141695]
https://user-images.githubusercontent.com/2644648/151477812-fc992a39-6cb7-4ce3-bbf0-66bf7118b88e.mp4

Steps to Reproduce:

1. drag Terminal from Panel to Side Panel

Expect: the terminal to be selected on drop
Actual: still see message about "Drag a view into panel to display"

**Comment by sbatten** [comment]
I am not reproducing this on macOS or Windows in today's insiders, this is today's build?

**Comment by TylerLeonhardt** [comment]
Looks good today.
