### ISSUE TITLE
Context clause for active editor position in editor group

### ISSUE THREAD

**Issue by chaoz-dev** [microsoft/vscode#141625]
Currently, the following when context clauses exist:
`activeEditorGroupIndex`
`activeEditorGroupLast`

I'd like to request similar context clauses but for the currently active editor instead; ie.
`activeEditorFirstInEditorGroup` - Returns true if the active editor is the first editor in its current editor group.
`activeEditorIndexInEditorGroup` - Returns an int index of the active editor in its current editor group.
`activeEditorLastInEditorGroup` - Returns true if the active editor is the last editor in its current editor group.

Edit 2022/1/27: Updated request with more details for requested contexts.

**Comment by chaoz-dev** [comment]
Took a look at the list of feature request issues, but don't think I saw this requested yet...

**Comment by bpasero** [comment]
To clarify, a context that indicates whether the current active editor is first or last in a group and/or the index of that editor?

**Comment by chaoz-dev** [comment]
Ah yes, correct! I'll specify this in the original request as well. Although for index I was originally thinking of index in current editor group, but global index could be interesting as well...

**Comment by bpasero** [comment]
What is the use case?

**Comment by chaoz-dev** [comment]
The following is my use case (let me know if these are duplicated elsewhere):
- First/Last checks allow for overloading of keybindings for editor behavior depending on editor position in editor group. eg. If we have keybindings for moving an active editor to the left/right of an editor group, we can then check if its position is first/last in this editor group; if so, we can "overload" keybindings by disabling the original keybindings and re-use the same keybindings to enable moving this active editor into a new editor group.
- Indexing allows for better positioning info of active editor within editor group. Combined with editor group index, this would give the coordinates of the current active editor across all groups.

**Comment by bpasero** [comment]
There are 2 new context keys:
* `activeEditorIsFirstInGroup`
* `activeEditorIsLastInGroup`

I wonder whether we can close this issue then given you indicated there is no use case yet for the index.

**Comment by chaoz-dev** [comment]
Ah, this is perfect, thank you!! Yes, we can close this ticket now. Thanks again!

**Comment by bpasero** [comment]
@chaoz-dev can you check with insiders version if the context keys work as desired? Thanks!

You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
Explainer: https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_66.md#new-context-keys-for-editors

**Comment by chaoz-dev** [comment]
Just gave this a try -- it works exactly as expected! Thank you!
Now I'm able to detect when the active editor is the first/last in a group and enable/disable keybindings depending on this condition... I've been able to overload the keybinding as a result.

Thanks a bunch again for implementing this functionality!!
