### ISSUE TITLE
Codespaces tries to use backslashes when selecting terminal to open

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#141769]
Local: Windows 10 VS Code Insiders
Remote: Codespaces v1.5.1, Linux

I don't have a setting for terminal profiles on Linux.
My default profile on Linux is `null`.
When I press Ctrl+J, I get an error because it tries to open `\usr\bin\pwsh` which doesn't exist.

**Comment by meganrogge** [comment]
/duplicate and same root cause as #141753
