### ISSUE TITLE
A11y_VisualStudioCodeClient_Customizations and settings_Keyboard:Using keyboard tooltips are not appearing for "Record keys" and "Sort by Precedence" icons.

### ISSUE THREAD

**Issue by kupatkar99** [microsoft/vscode#141724]
### GitHubTags:
#A11yMAS; #A11yTCS; #A11ySev2; #DesktopApp; #Visual Studio Code Client; #BM-VisualStudioCode-Win32-Nov2021; #Win32; #Keyboard; #WCAG2.1.1; #AINotInScope; #FTP; #STP;

### Environment Details:
Application Name: Visual Studio Code Client
Windows Version: Windows 11

### Repro Steps:
1.Open Visual studio code editor.
2.Naviagte to setting icon
3)Select "Keyboard shortcuts options".
4)Verify whether the tooltip is appearing for the "Record keys" and "Sort by Precedence" icons using keyboard or not.

### Actual Result:
Using keyboard tooltips are not appearing for "Record keys" and "Sort by Precedence" icons.

### Expected Result:
Using keyboard tooltips should be appear for "Record keys" and "Sort by Precedence" icons.

### User Impact:
Keyboard Users will miss the additional information within tooltip for the control.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/132344
