### ISSUE TITLE
character overlay in settings menu

### ISSUE THREAD

**Issue by Elie77350** [microsoft/vscode#141772]
<img width="939" alt="Capture d’écran 2022-01-29 à 00 13 42" src="https://user-images.githubusercontent.com/75457081/151635011-f8a81524-480b-40de-8501-d329c8a31798.png">
Nous avons écrit les données nécessaires dans votre presse-papiers, car elles étaient trop volumineuses à envoyer. Veuillez les coller.

**Comment by Elie77350** [comment]
it's about VSCode Insiders version

**Comment by rzhao271** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/141614
