### ISSUE TITLE
Confusing UI extension enable/disable workspace (extension management)

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/vscode#141789]
Issue Type: <b>Bug</b>

The UI around extension enabling and disabling for workspaces keeps confusing me. My use case is having (too) many extensions installed for various separate concerns, and I'd rather have only a selection of those extensions active at any given time. Examples scenarios for me are, for instance, "Python only", "Java read-only legacy with AnyCode", "Java modern", "JavaScript", "Rust", mix-in of various doc and design tools (draw.io, plantuml), or file renderers (Swagger / OpenAPI etc).

So given

<img width="331" alt="image" src="https://user-images.githubusercontent.com/3868036/151658436-0899451c-8482-4f5c-ac44-244253e87e67.png">

the UI tells me "This extension is enabled for this workspace by the user." - and then shows an active button "Enable" immediately above that. I am just confused. (Of course I can work this out, but I'd rather not spend the _energy_ on that)

I believe the root cause of this is the UI trying to offer an approach to manage _global_ extension state from within a workspace, with exactly the same UI. I suspect that this collides with usability. Similarly, the semantics of installing an extension ("manage wombats") when inside a workspace vs when just using vscode (folder/file), are probably _predictable_ - _but not explainable_ with few words (AKA usability challenge) - will the new "wombats" extension interfere with by "capybara" workspace?

Perhaps trimming / simplifying helps in making this more approachable, by having exactly two modes of operation:
* workspace mode
* general _user_ mode (i.e. folders are open, or just a file)

Depending on the mode, the UI switches, too. In
* workspace mode, only offer options to enable and disable for the workspace; install still installs globally (but clarifies that this only _enabled_ for the current workspace), uninstall is acceptable but warns that this will have global effect
* general _user_ mode, installing an extension enables it in _user mode_ and a one-time-only confirms whether to enable it by default in all new (i.e. still-to-be-created) workspaces;  enabling and disabling an extension only has effect on _user_ mode.

Additionally, the "Installed" section on the Extensions panel would get a checkbox UI "add extension to new workspaces".

This implicitly switches the extension state system from what I sense to be "state inheritance" (all workspaces *inherit* _extension_ state from global) to "state replication at time of conception", which, to be honest, I consider to be more obvious, in particular in the presence of change. For managing existing workspaces, an extension could be created to handle those.

Now, extension _setting_ management is something funky ... I think extension _setting_ management could still benefit from inheritance - so different behaviour compared to extension _state_ management.

In case things already work out as sketched above - apologies, but ... I don't _see_ that in the UI ;)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.66GB (43.27GB free)|
|Process Argv|--crash-reporter-id 5ddcd13a-5853-4d88-9c59-31e3be66729a|
|Screen Reader|no|
|VM|44%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.8.2
gitlens|eam|11.7.0
vscode-drawio|hed|1.6.4
plantuml|jeb|2.17.2
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.3
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
anycode|ms-|0.0.53
hexeditor|ms-|1.9.3
vscode-xml|red|0.18.2
vscode-yaml|red|1.3.0
vscodeintellicode|Vis|1.2.16

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30429732
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
wslgetstarted:30426333
vscop804:30404766
vscop940:30404999
vsrem710:30416614

```

</details>

because it was too large to send. Please paste.

**Comment by sandy081** [comment]
Thanks for your detail feedback. May I know if your use case is to configure extensions enablement per workspace? Aldo have you tried clicking on the dropdown next to Enabled button and see if you can change enablement per workspace ?

**Comment by shoffmeister** [comment]
My use case is indeed managing the set of extensions that are enabled in any given scenario. My scenarios are too varied - or I am too keen on focusing my attention my slimming feature sets - that I'd want to have all installed extensions enabled all the time.

To get the elephant out of the room: I believe that, purely functionally, it is feasible to get the installed extensions into the enablement state per user, and per (saved) .workspace, that I want them to be in.

So (AFAICS for myself) we are only talking about usability of the enablement functionality - or simply the amount of brain gymnastics that I need to apply (mental model), and the extent of care I need to take, to get there. I have to _think_ too much when it comes to applying installation and enablement, to take the appropriate course of action. That's what I was trying to convey in my initial report.

As background, it may help to understand that my workspaces can be put into a number of distinct, non-overlapping categories, e.g. "Python", "Typescript" (or js/npm), "Java maven", "Java gradle spring boot", "anycode", "Rust", "C". Plus using vscode as a really nice totally generic editor (text, draw.io, plantuml), as a user.

My intent in managing extensions explicitly is to reduce my cognitive load while using vscode. I don't want to see the any icons on the left for, say, "docker", when I am in Python mode. And neither do I want to have the commands _discoverable_ (Ctrl+Shift+P). I have no idea, to be honest, whether my intent materializes into something, but ... hey :)

**Comment by shoffmeister** [comment]
I think I may have a presentation and user interaction that wouldn't totally confuse me.

In the same below, *all* UI elements would always be visible; only Install/Uninstall changes. The (wordy) tag line "This extension is ..." is removed; instead a set of two vertical radio buttons, each reflecting the current state for the user and the workspace, respectively, take over. Outside of a workspace, the second set of radio buttons remains visible, but is rendered in a disabled state (and no button selected). 

By selecting radio buttons, a user simply and immediately flips the state of the extension.

Basically this is UX based on directly applying the change, instead of "issuing a command to enact change".

This UI also mirrors the "Preferences (UI)" approach (consistency across the product) where users flip - except that there it is not feasible to show both user and workspace at once - and here we can beneficially afford to render the state of both at the same time for lack of space constraints.

```
Microsoft Open Enclave  v1.0.10
Develop, deploy, and debug your Microsoft Open Enclave

<< Install / Uninstall button with drop-down >> 

Extension state:      User             Workspace       
                       [] enabled       [] enabled
                       [] disabled      [] disabled


Details   Feature Contributions
-----------
```

**Comment by sandy081** [comment]
Thanks for taking time and explaining the UX in detail. 

Regarding the scenario of various projects with different languages, we already have a feature request to support configure enabling/disabling extensions as a set per workspace - https://github.com/microsoft/vscode/issues/40239

We also have a feature request to support installing an extension and enable it only in the workspace it is installed - https://github.com/microsoft/vscode/issues/85735

Please let us know irrespective of UX, above feature requests would serve your use case?

**Comment by shoffmeister** [comment]
* Feature work for installing globally + enabling only in the current workspace: This would be welcome.
* Defining sets of extensions and managing these sets: I do not see significant value for my current use cases, although I do see the point in general.

**Comment by sandy081** [comment]
> Defining sets of extensions and managing these sets: I do not see significant value for my current use cases, although I do see the point in general.

Can you please explain why not and what is the difference?
