### ISSUE TITLE
enableShellIntegration issue with custom PowerShell prompt

### ISSUE THREAD

**Issue by wsmelton** [microsoft/vscode#141764]
I have a profile for PowerShell using the `prompt{}` and once I enable the `terminal.integrated.enableShellIntegration` the prompt is no longer loading.

With it enabled I see this prompt:
![image](https://user-images.githubusercontent.com/11204251/151624251-c8e4afd8-7c93-42aa-b060-0299261f5a12.png)

When I disable I get my expected prompt:
![image](https://user-images.githubusercontent.com/11204251/151624334-231f744c-88e7-47d8-b3b4-6d8532b2b6f4.png)

My prompt function within my PowerShell profile:

```powershell
function Prompt {
    $major = $PSVersionTable.PSVersion.Major
    $minor = $PSVersionTable.PSVersion.Minor
    $patch = $PSVersionTable.PSVersion.Patch
    if ($major -lt 6) {
        Write-Host "[PS $($major).$($minor)] [" -NoNewline
    } else {
        $patch = $PSVersionTable.PSVersion.Patch
        Write-Host "[PS $($major).$($minor).$($patch)] [" -NoNewline
    }
    Write-Host (Get-Date -Format "HH:mm:ss") -ForegroundColor Gray -NoNewline

    try {
        $history = Get-History -ErrorAction Ignore -Count 1
        if ($history) {
            Write-Host "] " -NoNewline
            $ts = New-TimeSpan $history.StartExecutionTime $history.EndExecutionTime
            switch ($ts) {
                { $_.TotalMinutes -ge 1 } {
                    '[{0,5:f1} m ]' -f $_.TotalMinutes | Write-Host -ForegroundColor DarkRed -NoNewline
                }
                { $_.TotalMinutes -lt 1 -and $_.TotalSeconds -ge 1 } {
                    '[{0,5:f1} s ]' -f $_.TotalSeconds | Write-Host -ForegroundColor DarkYellow -NoNewline
                }
                default {
                    '[{0,5:f1}ms ]' -f $_.Milliseconds | Write-Host -ForegroundColor Cyan -NoNewline
                }
            }
        } else {
            Write-Host "] >" -ForegroundColor Gray -NoNewline
        }
    } catch { }
    if (Test-Path .git) {
        $branchName = git branch | ForEach-Object { if ( $_ -match "^\*(.*)" ) { $_ -replace "\* ", "" } }
        Write-Host "[ git:$branchName ]" -ForegroundColor Yellow -NoNewline
    }
    Write-Host " $($executionContext.SessionState.Path.CurrentLocation.ProviderPath)"
    "[$($MyInvocation.HistoryId)] > "
}
```

**Comment by LuanVSO** [comment]
this is happening because line https://github.com/microsoft/vscode/blob/61ff43bafe4b2e8cd69f18cfe4df691579970522/src/vs/workbench/contrib/terminal/browser/media/shellIntegration.ps1#L26
is throwing because there is no history in a newly created session

**Comment by Tyriar** [comment]
@LuanVSO champion 🥇, should be able to handle this early next week

**Comment by LuanVSO** [comment]
i could do a pr

**Comment by Tyriar** [comment]
@LuanVSO that would be awesome! I'm fairly new to pwsh so any comments on the rest of the script would be appreciated too 🙂

**Comment by Tyriar** [comment]
Under what cases would the file system not be available?

**Comment by LuanVSO** [comment]
the provider could something other than filesystem, like the registry, certificate or environment
you can see them if you run `get-psdrive`

**Comment by Tyriar** [comment]
@LuanVSO just tried `cd HKLM:`, neat 😛

**Comment by Tyriar** [comment]
We probably want to keep the CWD even on non-filesystem providers actually, just give it a different scheme or something in that case to let VS Code differentiate it from a regular path. That way we would still get the cwd folder showing up in the tab:

![image](https://user-images.githubusercontent.com/2193314/152570750-a1e3739a-e67d-4d26-9418-db79bb27ebd9.png)

**Comment by LuanVSO** [comment]
also, is it only supposed to support powershell 7 and not win PS?

**Comment by Tyriar** [comment]
Yep, no windows powershell

**Comment by LuanVSO** [comment]
does vscode also supports osc 9;9 for CWD Tracking?

**Comment by Tyriar** [comment]
@LuanVSO some discussion on the topic in https://github.com/microsoft/vscode/issues/140514, my plan is to move us over to using our own custom sequences to avoid shell integration getting confused and give us freedom to change what them as we please.

**Comment by Tyriar** [comment]
@LuanVSO let me know if I'm missing something though, I don't think running another terminal's shell integration script is particularly useful. Instead, you would use the arg injection or set it up manually (docs aren't written yet).

**Comment by Tyriar** [comment]
I see you have the sequences we support in your profile, these would break when we action #140514 as we'd probably move to use `OSC 633`

**Comment by LuanVSO** [comment]
yeah, I will probably remove them after the chages in #142217 and #142211 get into a release

**Comment by Tyriar** [comment]
Good to hear, let us know if you hit any other problems as I have a pretty simple pwsh setup

**Comment by wsmelton** [comment]
Can confirm latest build resolves this now on Inisiders:

![image](https://user-images.githubusercontent.com/11204251/152833496-4e738d19-931d-40f6-8add-dc577d159c17.png)
