### ISSUE TITLE
Predict variable names instead of "newLocal" when it's kind of obvious

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#141797]
If I'm extracting an expression "new FooBarQux" maybe it could suggest "fooBarQux" as the name?

**Comment by weinand** [comment]
What language are you using?

**Comment by sdegutis** [comment]
TypeScript

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

**Comment by sdegutis** [comment]
No
