### ISSUE TITLE
"Run Recent Command" doesn't show quickpick

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#141745]
"Run Recent Command" is broken now - it reveals the terminal but does not show the quickpick. Maybe a regression from one of the issues I filed?

**Comment by meganrogge** [comment]
if shell integration isn't enabled for your terminal, you won't see it. that was something @Tyriar fixed/added yesterday I think.

**Comment by meganrogge** [comment]
if there aren't any commands (or if shell integration isn't enabled/working), it doesn't show
https://github.com/microsoft/vscode/blob/22fc0438ffad90f2ee34d4b0c46df61d3222afe7/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L739

**Comment by roblourens** [comment]
I have shell integration enabled and have run commands

**Comment by meganrogge** [comment]
does it work if you try it in bash?

**Comment by roblourens** [comment]
Yes

**Comment by meganrogge** [comment]
Same cause as #141620 /duplicate
