### ISSUE TITLE
"Last Updated On" shows pre-release's timestamp

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#141766]
![image](https://user-images.githubusercontent.com/8586769/151626489-aa7d73de-a2ea-40de-9e72-2c6325122312.png)

As far as I can tell, the release of the stable extension was 22 days ago (https://github.com/microsoft/vscode-pull-request-github/releases/tag/v0.34.3), but the extension editor shows that it was updated yesterday. I imagine this is because there was a nightly release yesterday.

**Comment by sandy081** [comment]
It represents when was the last time this extension was published to the marketplace. Technically what you are seeing is correct as it does not mention about pre-release or released versions.

**Comment by gjsjohnmurray** [comment]
@sandy081 then maybe clarify this by changing the "More Info" header to become "Marketplace Info".

**Comment by sandy081** [comment]
Good idea!
