### ISSUE TITLE
VsCode's Task.json and Gulp doesn't pass arguments correctly

### ISSUE THREAD

**Issue by MrDesjardins** [Microsoft/vscode#14172]
**Versions**
- VSCode Version: 1.6.1
- OS Version: Windows 10

**Problem**
Passing values from VsCode, like the current file, is not possible when using Task.json and Gulpfile.js

**Why**
Task.js offers arguments, but in a not in the right order. For example:

```
{ 
 "command": "gulp"
  "args": ["myCommandArguments"],
  "tasks" : [ 
    { "taskName": "myTaskThatDoesSomethingForTheActiveFile",
      "args": ["myTaskArguments"],
      "suppressTaskName": false,
    }
  ]
}
```
This will end up doing : 
```
gulp myCommandArguments myTaskArguments myTaskThatDoesSomethingForTheActiveFile
```
As you can see the `myTashARguments` is not after the gulp task, hence cannot be read by gulp

**Other links that share the same issue:**
http://stackoverflow.com/questions/33348654/pass-arguments-to-gulpfile-task-from-tasks-json
http://stackoverflow.com/a/30419250/13913

**Comment by dbaeumer** [comment]
This works for me using the following example. 

```
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "echo",
	"isShellCommand": true,
	"args": ["commandArg"],
	"showOutput": "always",
	"echoCommand": true,
	"tasks": [
		{
			"taskName": "taskOne",
			"suppressTaskName": false,
			"args": [
				"taskArg"
			]
		}
	]
}
```

@MrDesjardins can you add the `"echoCommand": true` property to the tasks.json and provide me with the output. May be there is something strange with gulp.

**Comment by MrDesjardins** [comment]
Your example is not good. You invoke 'echo' that use the argument. I am invoking `gulp` that invoke a task that uses the parameter. You should do a test using `gulp` to see the actual problem instead of trying to do it with something else.  It worth the try since `gulp` is so popular.

I used the `echoCommand` as requested. Here is the task.json:

```
{
    "version": "0.1.0",
    "command": "gulp",
    "isShellCommand": true,
    "echoCommand": true,
    "tasks": [
        {
			"taskName": "myTaskThatDoesSomethingForTheActiveFile",
			"isBuildCommand": true,
			"showOutput": "always",
                        "args":  ["${file}", "${env.BUILDDIR}"],
		}
    ]
}
```
Here is the output when using in VSCode:
```
running command> gulp myTaskThatDoesSomethingForTheActiveFile c:\code\test.ts
[10:49:15] Using gulpfile c:\gulpfile.js
[10:49:15] Task 'c:\code\test.ts' is not in your gulpfile
```
As you can see, like the initial post, the task try to run the parameter (the typescript file) instead of the task name.

**Comment by dbaeumer** [comment]
The tasks.json executing engine doesn't know something about gulp. So we defined a general arg order like this: ${command} ${commandArg} ${taskName} ${taskArgs}. This is the same whether you execute echo, gulp, or msbuild. This is why I made the example in echo. But before closing it I wanted to make sure we don't have a bug. That is why I asked you to run with `"echoCommand": true`

If you want to define the position of your task name yourself you can suppress the task name and add the task name to the args.

```json
    "tasks": [
        {
            "taskName": "taskOne",
            "suppressTaskName": true,
            "args": [
                "taskArg", "taskOne"
            ]
        }
    ]

```

**Comment by MrDesjardins** [comment]
Hello, 
I understand perfectly that the engine doesn't know Gulp. My issue was with VsCode and Gulp, one of the most popular tool in the JavaScript ecosystem, hence assumed that it would be better to debug with that tool than another one . As I can see, it seems that it not the case, but would simplify the resolution. In all cases, thank you for your inputs, it helped me to find a solution.

That said, for everyone wondering how to make it works with **VsCode** and **Gulp** here is the solution.

When running a Task from VsCode for Gulp's task, the argument that Gulp will see is:
```
[0] node.exe path
[1] Gulp.js file
[2] First parameter
[3] Second parameter
[4] ...
```
That said, you cannot just use 

```
 "tasks": [
        {
            "taskName": "taskOne",
            "suppressTaskName": true,
            "args": [
                "taskArg", "taskOne", "param1", "param2"
            ]
        }
    ]
```
Because Gulp will think that param1 and param2 are **task name**. You need to use the syntax with the double hyphen. Here is an example of the syntax:
```
 "tasks": [
        {
            "taskName": "taskOne",
            "suppressTaskName": true,
            "args": [
                "taskArg", "taskOne", "--arg1", "value1", "--argxx2", "valuexx2"
            ]
        }
    ]
``` 
From the gulp tasks you can access the argument by index if desired:
```
process.argv[3] // Get value1
```
