### ISSUE TITLE
VSCode web icon doesn't fill area on Chrome OS

### ISSUE THREAD

**Issue by hello-smile6** [microsoft/vscode#141706]
The VSCode icon doesn't display well on Chrome OS. To fix it, you'd just have to add the `purpose: "any maskable"` property to each icon in the PWA manifest. Could you fix it?
Sorry if I'm doing something wrong, I don't know what to do.

**Comment by hello-smile6** [comment]
> /gifPlease

Would a screenshot work?

**Comment by bpasero** [comment]
Yes!

**Comment by hello-smile6** [comment]
> Yes!

Okay.
![image](https://user-images.githubusercontent.com/73048226/151501769-c0555c4a-69bb-41d7-a52f-1d2525dc309e.png)

If you look at the [blog post](https://code.visualstudio.com/blogs/2020/12/03/chromebook-get-started) for the native app, you'll notice that the icon fills the entire space. In order to get the same result on the PWA, you'd have to add the `purpose: "any maskable"` property for each image in the manifest.

**Comment by bpasero** [comment]
> ...  each icon in the PWA manifest...

Just to clarify, you are using `vscode.dev` as PWA?

**Comment by hello-smile6** [comment]
> > ...  each icon in the PWA manifest...
> 
> Just to clarify, you are using `vscode.dev` as PWA?

Yes. Here's what I'm saying.
```diff
{
	"name": "Visual Studio Code",
	"short_name": "Code",
	"start_url": "/",
	"lang": "en-US",
	"display": "standalone",
	"icons": [
- 		{ "src": "/static/stable/code-192.png", "type": "image/png", "sizes": "192x192" },
- 		{ "src": "/static/stable/code-512.png", "type": "image/png", "sizes": "512x512" },
+  		{ "src": "/static/stable/code-192.png", "type": "image/png", "sizes": "192x192", "purpose": "any maskable" },
+ 		{ "src": "/static/stable/code-512.png", "type": "image/png", "sizes": "512x512", "purpose": "any maskable" }
	]
}
```

I made an [example](https://vscode-icon-example.9pfs.repl.co/) of how the icon would look that way. Please note that you'd need to add more padding.

**Comment by rzhao271** [comment]
Hi @hello-smile6, has the issue been fixed on the latest Insiders?

**Comment by hello-smile6** [comment]
Checking @rzhao271

**Comment by hello-smile6** [comment]
@rzhao271 No.

**Comment by hello-smile6** [comment]
The Insiders icon is actually slightly smaller than the main one.

**Comment by misolori** [comment]
We are in the process of deploying the fix today so it's not yet available (don't think the bot can verify when it's been released since it's the web version).

**Comment by hello-smile6** [comment]
@misolori Okay, I'll reinstall the PWA a few times

**Comment by misolori** [comment]
Deployment is now complete, please try again using https://insiders.vscode.dev/ and remember to uninstall the app from `chrome://apps`

**Comment by hello-smile6** [comment]
It doesn't seem to work.

**Comment by misolori** [comment]
This is what i see when I try this out on a android emulator, the cropping isn't the best but it at least appears to be working:

![image](https://user-images.githubusercontent.com/35271042/156297380-cfbba61f-ab01-41ac-b205-5b4993922c78.png)

**Comment by hello-smile6** [comment]
> Ah, so we did change it so that the browser apps on Chrome/iOS use the white background and on desktop they use the transparent version so that looks as expected (for some reason it looks better on your screenshot than mine).

Oh, would it be possible to somehow have the transparent version?
