### ISSUE TITLE
Task running python script fails with : Cannot create process, error code: 193

### ISSUE THREAD

**Issue by Butanium** [microsoft/vscode#141751]
Issue Type: <b>Bug</b>

I have this task `decimate and plot csv` executing a python script plotting the csv I'm editing, and several others which executs cmd as `dune utop` : 
```json
{
			"label": "dune utop",
			"command": "external_tools/_run_config/dune_utop.cmd"
		},
		{
			"label": "decimate and plot csv",
			"command": "external_tools/show_data/show_task.py",
			"args": ["${relativeFile}","${input:decimateFactor}"]
		}

	],
	"inputs": [
		{
			"id": "decimateFactor",
			"description": "Decimate factor :",
			"default": "1000",
			"type": "promptString"
		}
	]
```
The dune task works well but the python one just doesn't : 
```
> Executing task in folder ocaml-tsp: C:\Users\Clement\Documents\prepa\tipe\ocaml-tsp\external_tools\show_data\show_task.py logs\MCTS-att48-7s-Random-Min_spanning_tree-Two_opt_optimization_200len_100iter_1s\all_scores.csv 1000 <

Échec du lancement du processus de terminal : A native exception occurred during launch (Cannot create process, error code: 193).

Le terminal sera réutilisé par les tâches, appuyez sur une touche pour le fermer.
```
However when I copy paste the task in a vscode cmd, it works well : 
```
Microsoft Windows [version 10.0.19043.1466]
(c) Microsoft Corporation. Tous droits réservés.

C:\Users\Clement\Documents\prepa\tipe\ocaml-tsp>C:\Users\Clement\Documents\prepa\tipe\ocaml-tsp\external_tools\show_data\show_task.py logs\MCTS-att48-7s-Random-Min_spanning_tree-Two_opt_optimization_200len_100iter_1s\all_scores.csv 1000
debugging...
file decimated
```
By the way this is the python script called : 
```py
from show_data import decimate
import matplotlib.pyplot as plt
import os
import sys

print("debugging...", flush=True)
os.chdir("C:/Users/Clement/Documents/prepa/tipe/ocaml-tsp/")
factor = 1000 if len(sys.argv) <= 2 else int(sys.argv[2])
result = decimate(sys.argv[1], factor)

plt.plot(result['timestamp'], result['length'])
plt.show()
```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (0.97GB free)|
|Process Argv|--crash-reporter-id 8a98e7f6-95cb-41bb-86c4-651ceca005df|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-fr|MS-|1.63.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710:30416614
vsbas813:30426126

```

</details>

**Comment by alexr00** [comment]
@Butanium can you share any `terminal` and `task` related settings you have set?

**Comment by Butanium** [comment]
@alexr00 
I can't remember which settings I changed, if any, can I send you my whole settings.json or screenshots of terminal and tasks settings ?

**Comment by alexr00** [comment]
Yes, the whole `settings.json` would be usefule.

**Comment by Butanium** [comment]
The one inside my .vscode project folder is just :
```json
{
    "ocaml.sandbox": {
        "kind": "global"
    },
    "python.formatting.provider": "black",
    "discord.enabled": true
}
```
The global one in `C:\Users\Clement\AppData\Roaming\Code\User\settings.json` : 
```json
{
    "workbench.colorTheme": "Default Dark+",
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "source": "Git Bash"
        },
        "ocaml_terminal": {
            "path": "C:\\WINDOWS\\System32\\cmd.exe",
            "args": []
        }
    },
    "files.autoSave": "onFocusChange",
    "files.autoGuessEncoding": true,
    "timeline.excludeSources": [],
    "git.confirmSync": false,
    "tabnine.experimentalAutoImports": true,
    "git.enableSmartCommit": true,
    "diffEditor.ignoreTrimWhitespace": false,
    "files.watcherExclude": {
        "**/_build/**": true,
        "**/archive/**": true,
        "**/puzzle_input/**": true
    },
    "search.exclude": {
        "**/_build/**": true,
        "**/archive/**": true,
        "**/logs/**": true
    },
    "files.eol": "\n",
    "gitlens.defaultTimeFormat": null,
    "gitlens.hovers.currentLine.over": "line",
    "update.mode": "manual"
}
```

Let me know if I can provide you more info

**Comment by alexr00** [comment]
It looks like when you run the script manually you're using cmd.exe. However, unless you specify a different shell, tasks will use your default shell (in this case powershell). Can you try adding this setting to change the shell that tasks uses?
```
	"terminal.integrated.automationProfile.windows": {
		"path": "cmd.exe",
	},
```

**Comment by Butanium** [comment]
I just tried to run in powershell and it works,
```ps
PS C:\Users\Clement\Documents\prepa\tipe\ocaml-tsp> external_tools/show_data/show_task.py 
logs\MCTS-att48-1800s-Random-Min_spanning_tree-Two_opt_optimization_200len_100iter_1s--1\all_scores.csv 1000
```
but opens an external python console 
![image](https://user-images.githubusercontent.com/55806347/153880821-564bd23a-db1c-4cac-98b0-2cc5068bc1ba.png)

I added the parameters you sent in both `settings.json` but it seems like the task still execute in a Powershell console : 
![image](https://user-images.githubusercontent.com/55806347/153881328-b63d1341-a9b4-415a-b323-a23fbe45d9c3.png)

I also tried to replace your path by `"path":"${env:windir}\\Sysnative\\cmd.exe"` and `"${env:windir}\\System32\\cmd.exe"` but got the same result

**Comment by alexr00** [comment]
Do you also have settings in a *.code-workspace file?

**Comment by Butanium** [comment]
![image](https://user-images.githubusercontent.com/55806347/153890221-5e86aeeb-5af4-4603-bba4-13b323a7ef99.png)
Opens this settings.json : 
```json
{
    "ocaml.sandbox": {
        "kind": "global"
    },
    "python.formatting.provider": "black",
    "discord.enabled": true
}
```
And I have no *.code-workspace file on my computer

**Comment by alexr00** [comment]
@Butanium it looks like you're running your tasks as a `process` task. Your task should work if you add the property `"type": "shell"` to it. I missed this in the original post.

**Comment by Butanium** [comment]
I don't have the error but it doesn't work : the command is entered like this :
`'{command}' `, and the `'` makes it says it doesn't recognize the command whatever it is

**Comment by Butanium** [comment]
I had to enter the entire path instead of the relative one but it works now. Thanks !
