### ISSUE TITLE
Electron process eating all CPU on MAC

### ISSUE THREAD

**Issue by Rodrigo-JM** [microsoft/vscode#141763]
Issue Type: <b>Performance Issue</b>

Just opening the editor causes the issue. Suddenly it started happening

On activity monitor it shows about +99% CPU usage on the electron process that is tied to VSCODE (that's my interpretations, since opening and closing the editor pops up the process)

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|16, 9, 4|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|cryptum-frontend-v2 --crash-reporter-id abca23f4-dbdf-400a-9d37-68a40e337bee|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Workspace Info</summary>

```
|  Window (Release Notes: 1.63.2 — cryptum-frontend-v2)
|    Folder (cryptum-frontend-v2): 180 files
|      File types: pack(40) js(27) tsx(15) ts(13) json(12) svg(6) DS_Store(4)
|                  xml(4) old(3) gitignore(2)
|      Conf files: package.json(1) tsconfig.json(1);
```

</details>
<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|8.2.0
ng-template|Ang|13.2.0
atlascode|atl|2.10.6
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|4.1.0
gitlens|eam|11.7.0
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.1.0
json2ts|Gre|0.0.6
rainbow-csv|mec|2.0.0
vscode-typescript-next|ms-|4.6.20220127
vscode-yaml|red|1.3.0
nextjs-vscode-snippets|ret|0.1.1
nestjs|rub|1.5.0
code-settings-sync|Sha|3.4.3
vscode-icons|vsc|11.8.0

(4 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Does this also happen if you launch it with the `--disable-extensions` switch?

**Comment by Tyriar** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
