### ISSUE TITLE
can't open the settings menu

### ISSUE THREAD

**Issue by Elie77350** [microsoft/vscode#141794]
Nous avons écrit les données nécessaires dans votre presse-papiers, car elles étaient trop volumineuses à envoyer. Veuillez les coller
<img width="1784" alt="Capture d’écran 2022-01-29 à 15 59 00" src="https://user-images.githubusercontent.com/75457081/151666043-a3369d9d-d6d0-43d3-80b1-c213a1fa4966.png">
<img width="1784" alt="Capture d’écran 2022-01-29 à 15 59 34" src="https://user-images.githubusercontent.com/75457081/151666057-0bbddad3-ffc7-414b-b634-d0f495dd9865.png">
.

**Comment by rzhao271** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/141614
