### ISSUE TITLE
Terminal links rarely work under FluxBox

### ISSUE THREAD

**Issue by vid512** [microsoft/vscode#141792]
Issue Type: <b>Bug</b>

When running on Debian with FluxBox as Desktop environment, the links in terminal only rarely work when I ctrl+click them. Only 1 in about 10 - 30 clicks actually works.

https://user-images.githubusercontent.com/34608784/151662697-2eb1bb4c-f710-4520-a90f-ed205ffb5d4e.mp4

After "unsuccessful" click, the cursor changes to text cursor, so I have to move it around a little bit to change back into clickable link cursor.

Under XFCE desktop environment on same system, with same vscode, terminal links work as expected.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.10.0-10-amd64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2820)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.58GB (7.73GB free)|
|Process Argv|. --crash-reporter-id 7c6178dd-b28d-4737-ab81-cc6eff37a263|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|fluxbox|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|fluxbox|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710cf:30416617

```

</details>

**Comment by Spongman** [comment]
I see the same thing connecting to a Windows-hosted docker instance using VNC Viewer 6.17.

**Comment by Tyriar** [comment]
@vid512 a lot of link improvements have happened over the past few months and the issue of clicking not working is one of those problems that was fixed. Can you try reproduce the problem on the Insiders build? https://code.visualstudio.com/insiders

**Comment by vid512** [comment]
The problem can be reproduced with code-insiders too, in exactly same way. Under bare FluxBox link only works rarely, under XFCE it works consistently.

Version: 1.66.0-insider
Commit: 45999664ef626d6d665cb585104efdcab383a3cd
Date: 2022-03-28T07:50:54.731Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.10.0-10-amd64

**Comment by Tyriar** [comment]
Oh I understand now. This is either an issue in Fluxbox or Chromium/Electron under Fluxbox.
