### ISSUE TITLE
Change format of cell uris so that it is harder to guess

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#141717]
Notebooks use the the [`CellUri`](https://github.com/microsoft/vscode/blob/76625c5207bbccc118ffca9d0516b3fee2a08d1f/src/vs/workbench/contrib/notebook/common/notebookCommon.ts#L507) to create a uri for a specific cell of a notebook. The rules are

* take notebook uri
* replace scheme with `vscode-notebook-cell`
* append a padded fragment of the cell handled (padded for lexical-sort of uris)
* append the notebook's scheme unless it's `file`

Samples:

Cell 1 of notebook `file:///some/notebook.ipynb` is `vscode-notebook-cell:///some/notebook.ipynb#ch0000001`
Cell 21 of notebook `memfs:///some/notebook.ipynb` is `vscode-notebook-cell:///some/notebook.ipynb#ch0000021memfs`

This format is an implementation details and the problem is that it is so obvious that folks starting to program against it (instead of using API, e.g for discovering a notebook for a cell etc). To prevent this we should make the format a little less obvious, e.g. by encoding the fragment a little.

**Comment by weinand** [comment]
@jrieken in the notebook debugging samples the debugging functionality did not make assumptions about cell uri format.

But since VS Code persists breakpoints independent from debuggers via their resource URI, it is possible that a persisted cell breakpoint "gets broken" when the cells of a notebook are rearranged and then the notebook cell URIs get new sequential numbers in their URI fragment. 

For this problem the notebook debugging samples tried to ["fix" the persisted breakpoints](https://github.com/microsoft/vscode-simple-jupyter-notebook/blob/77cd8b0f1695e2228756f9ace1d8e2b4d4d21c6c/src/debugging.ts#L70-L102) when they detected that cell rearrangements happened.

If cell URI would be robust, this ugly workaround would not be necessary.  

@roblourens is my assessment still true for the current notebook debugging approach?

**Comment by roblourens** [comment]
I can't think of anything in debugging that makes assumptions about the format. Changing the format will break anything that is stored by cellURI, like persisted breakpoints. So if we change it we might consider a simple one-time migrationwith the update

**Comment by jrieken** [comment]
> So if we change it we might consider a simple one-time migrationwith the update

I am not sure how `CellUri` is used but a relatively simple adoption would be to let `CellUri#parse` support the old and new variant for a while. @roblourens Can you check with your usage and see if that would work?

**Comment by jrieken** [comment]
> For this problem the notebook debugging samples tried to "fix" the persisted breakpoints when they detected that cell rearrangements happened.

I do understand the desire for stable URIs but this specific case is also a good sample for why the format should be obfuscated. This specific "[massage](https://github.com/microsoft/vscode-simple-jupyter-notebook/blob/77cd8b0f1695e2228756f9ace1d8e2b4d4d21c6c/src/debugging.ts#L77)" isn't working since roughly a year more (due to https://github.com/microsoft/vscode/commit/ce02917f666e1a72bdb6a60891e0616c821a0f53) and we don't want to invite people to make assumptions...

Stable cell uris/identity is likely another topic and while I believe this is coming (has come?) to jupyter it isn't defined for other notebooks. There is also a specific issue with displaying cell uris in the workbench: we don't have the concept for pluggable resource sorters and therefore cell uris are crafted so that they sort lexicographically well. This makes the problems and references view look nice...

**Comment by jrieken** [comment]
/cc @rchiodo I found something that looks like an assumption about the format of the fragment. What's that for and can that work without these assumptions? 

https://github.com/microsoft/vscode-jupyter/blob/62356af10732e2bbf1c520e9cea0ad8420ab3f27/src/client/datascience/notebook/intellisense/logReplayService.ts#L152

That was the only usage I could find but I am curious if you know about more such places?

**Comment by rchiodo** [comment]
Yes actually this is used here:
https://github.com/microsoft/lsp-notebook-concat/blob/d9fae2e518e2e32a8ebc97e723e2f3120161566a/src/notebookConcatDocument.ts#L231

We use this in pylance for computing where a notebook cell is in a document when it is created. I think @dbaeumer's new LSP messages will eliminate this need though (as the cells positions are contained in his new messages).

**Comment by rchiodo** [comment]
The first location you mentioned is a debug tool we use for replaying customer's logs. We'd need some way to pull apart the cell URI for that to continue to work because we don't have the actual notebook originally associated with the URI.

**Comment by jrieken** [comment]
> We'd need some way to pull apart the cell URI for that to continue to work

Can you explain what pulling apart uris means?

**Comment by rchiodo** [comment]
Take the cell index out of the fragment. We need that (during the log replay) to determine what cell a 'textDocument/didChange' event to apply an edit to.

The log replace service is used to try and repro intellisense problems. Customer sends a log of all the LSP requests and a notebook that they started with.

We open the notebook and for every `textDocument/didChange` event we figure out which cell the edit is for and reapply it. Since the notebook URI doesn't match what we have locally, we just scrape the fragment portion to compute the cell index. Seems like it should work to replace the path part of the URI with our local file and then just search on the cell that matches instead. But that would also presume that the rest of the URI would be consistent across machines.

**Comment by jrieken** [comment]
> Since the notebook URI doesn't match what we have locally, we just scrape the fragment portion to compute the cell index. Seems like it should work to replace the path part of the URI with our local file and then just search on the cell that matches instead. But that would also presume that the rest of the URI would be consistent across machines.

Ok, thanks for clarifying. I believe a better approach is checking for the `vscode-notebook-cell`-scheme and simply use the whole fragment without making assumptions about its form. Roughly like so

```
if(step.textDocument.uri.scheme === 'vscode-notebook-scheme') { // check fixed scheme
	const replaced =  this.activeNotebook
              .cellAt(0)
              .document.uri.with({ fragment: step.textDocument.uri.fragement }); // use with, no string-replace
	step.textDocument.uri = replaced
}
```

**Comment by jrieken** [comment]
> I think @dbaeumer's new LSP messages will eliminate this need though (as the cells positions are contained in his new messages).

Do you have an ETA for adopting that?

**Comment by rchiodo** [comment]
> Do you have an ETA for adopting that?

The pylance team would also need to switch to adopting it. Probably this month some time.

**Comment by dbaeumer** [comment]
@rchiodo has the new LSP messages makes it possible to not rely on the cell URL format.

**Comment by jrieken** [comment]
@rchiodo Did that [adoption](https://github.com/microsoft/vscode/issues/141717#issuecomment-1027135146) happen?

**Comment by rchiodo** [comment]
No it did not.

**Comment by rchiodo** [comment]
I believe @msfterictraut is in the process of making  an experimental version of pylance to adopt this new API.

**Comment by erictraut** [comment]
I'm not working on that. The pylance team might be.

**Comment by jrieken** [comment]
@rchiodo can you figure out who is working on that and that the timeline is. thanks

**Comment by rchiodo** [comment]
You could ask @heejaechang or @bschnurr.

**Comment by jrieken** [comment]
Thanks for the update @debonte. Please keep me in the loop once you have migrated so that we can the URI change happen

**Comment by dbaeumer** [comment]
I added Pylance to the proposed API exception list so that they can give it a try.

**Comment by jrieken** [comment]
@debonte How is the roll-out going? Can we make this change now?

**Comment by debonte** [comment]
@jrieken, no we haven't started the experiment yet. @dbaeumer had suggested that we split the code changes into two chunks -- first upgrade to the latest LSP, second add the LSP notebooks code as an experiment. And he recommended shipping the first part (LSP upgrade) to insiders first. The Python core extension has done this (their current insiders build is using LSP 3.17), but unfortunately Pylance doesn't have a real insiders build, so shipping the LSP upgrade to insiders requires us to make some build/publish infrastructure improvements.

Is there time pressure on this change for some reason? We could speed things up a bit by just shipping the LSP upgrade in our next stable build, bypassing the insiders step.

**Comment by jrieken** [comment]
> Is there time pressure on this change for some reason? We could speed things up a bit by just shipping the LSP upgrade in our next stable build, bypassing the insiders step.

No real pressure but it's just another ball I need to keep in the air. The work on my side is done and I keep snowplowing this item. It mostly about the overhead and chance of merge conflicts. If you can conformably speed it up, I'd be very thankful.

**Comment by jrieken** [comment]
@debonte Monthly ping

**Comment by debonte** [comment]
@jrieken The changes for the experiment were checked in today. Prerelease builds with experiment support will ship tomorrow. Current plan is to start the experiment on Monday.

**Comment by jrieken** [comment]
👯 Thanks for the update

**Comment by jrieken** [comment]
@debonte I wanna finally make this change happen in July? Any objections? @rchiodo Same question

**Comment by rchiodo** [comment]
Post that being fixed we'd still make assumptions about notebook URIs. We need this in order to determine if the TextDocument for the input box in the interactive window is tied to the notebook for the interactive window or not. @jrieken I'm not sure if you're changes will make this impossible or are they only dealing with the fragment portion?

**Comment by rchiodo** [comment]
The 'logReplayService' above isn't really necessary. It's just a debug tool.

**Comment by jrieken** [comment]
> or are they only dealing with the fragment portion?

@rchiodo Only the fragment portion. The new format is more obscure but has the same properties: sorts by cell orders and encodes the cell index. 


@debonte Assuming are going ahead with this change. What's the impact on your end? What will break and intermediate change can you make?

**Comment by debonte** [comment]
> @debonte Assuming we are going ahead with this change. What's the impact on your end? What will break and what intermediate change can you make?

Because we depend on the lsp-notebook-concat code that Rich [referenced above](https://github.com/microsoft/vscode/issues/141717#issuecomment-1027107693), I believe this would cause the ordering of cells to be wrong for anyone using Pylance's concat doc-based notebook support. Depending on how the cells are misordered, this could cause most language server features to misbehave. This would impact any user that is not in the LSP notebooks experiment treatment group or who is using Interactive Window.

The Jupyter team owns this code and would be best able to say how it might be adjusted to support both the old and new formats.

FYI, Rich is OOF this week.

**Comment by jrieken** [comment]
> I believe this would cause the ordering of cells to be wrong for anyone using Pylance's concat doc-based notebook support.

The new format makes the same ordering guarantees, e.g when sorting by the toString()'ed uri of the cell-documents you get the same order as before. It is just harder to extract the actual (numeric) value from the URI

**Comment by debonte** [comment]
The lsp-notebook-concat code we are currently using gets the cell fragment as a number like this: 

```javascript
parseInt(cellUri.fragment.substring(2) || '0')
```

My understanding is that this won't work properly with the new format. That was my point.

**Comment by jrieken** [comment]
Yeah, parsing the fragment into a number won't work anymore but looking at how the parse result is actually used gives me confidence. The value is kept in `NotebookSpan#fragment` and the only usage of the that field seems to be a [simple comparison](https://github.com/microsoft/lsp-notebook-concat/blob/joh/naval-lark/src/notebookConcatDocument.ts#L886).  That will continue to work with the fragment as-is (because cell-order is encoded in the fragment part)

**Comment by jrieken** [comment]
> Maybe it should be more explicit that it's a string compare (instead of using '<').

Unsure - the comparison operator might be best suited here because it faster and more narrow-spec'd than localeCompare (I believe). I also see this as a temporary fix, e.g using the LSP concat is the way to go but the question is what do you do assuming we make the fragment-change at the end of the week? 

The patch I have suggested is a good stepping-stone to prevent breakage but it isn't an alternative to LSP. It just less fragile: today we assume the fragment (1) parses to a number and (2) the numbers are comparable and with my patch we assume (1) the fragment is comparable. That's better but not the optimum, use LSP is the optimum but I haven't seen that happening  in the last months and I want to make progress

**Comment by jrieken** [comment]
>  Oh maybe it doesn't. Fragment today would compare the same I think.

Yes, the change can happen today because comparing the fragment is already behaving like that

**Comment by rchiodo** [comment]
Okay the fragment change made it through all the layers for jupyter. Our build tonight will have the new fragment change.
