### ISSUE TITLE
[GitHub issue] Can't verify fix

### ISSUE THREAD

**Issue by Elringus** [microsoft/vscode#141773]
I've got a request on an issue that I've previously created here (#138413) to comment if the fix is working (and it is indeed working), but the comments are restricted for collaborators, so I can't do this. @rchiodo 

![](https://i.gyazo.com/c660f9e720141d58c24dff2032ea3acf.png)

**Comment by jrieken** [comment]
Maybe a special case because this iteration was very long

**Comment by JacksonKearl** [comment]
Ah, so the bot wont lock the issue if there's a pending author verification requested, but in this case the issue was locked before the verification request label was added. Having the bot automatically unlock the issue when verification is requested is a fair feature request.

**Comment by lramos15** [comment]
Tried to verify with https://github.com/microsoft/vscode/issues/148267 but bot didn't even make the comment @JacksonKearl am I missing a step?
