### ISSUE TITLE
Debugger gives no error message when node isn't installed

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#1417]
- have linux with node
- have app.js
- launch debugging
- > nothing happens, no error message etc

**Comment by weinand** [comment]
We are showing this message now:

![2017-06-16_12-03-48](https://user-images.githubusercontent.com/1898161/27222286-f9bf9d46-528b-11e7-9ff0-a40ed4796922.png)

**Comment by michelkaporin** [comment]
Works if `legacy` or `inspector` protocol is specified. In case with `auto`, I am presented with the following notification:

![image](https://user-images.githubusercontent.com/2239563/27681520-de8cb7d2-5cbf-11e7-901a-043711d2c6fc.png)

**Comment by weinand** [comment]
This error no longer occurs.

@roblourens for "legacy" I show:

![2017-08-17_15-16-46](https://user-images.githubusercontent.com/1898161/29414169-2d7ccc54-835f-11e7-8931-0535886dac2d.png)

whereas you show:

![2017-08-17_15-18-08](https://user-images.githubusercontent.com/1898161/29414215-4a644cc0-835f-11e7-8f3e-f6f6e343e7b7.png)

**Comment by roblourens** [comment]
Updated the message
