### ISSUE TITLE
Open file in local workspace results in OS native file or folder selector

### ISSUE THREAD

**Issue by siddharthgpta** [microsoft/vscode#141784]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: MacOS 12.2

Steps to Reproduce:

1. Try to open file in local workspace (results in the OS open folder window pane to show up)
2. Try to open file in remote workspace (results in the vscode Open FIle or Folder prompt)

https://user-images.githubusercontent.com/11062831/151648945-60120fb3-9b76-44a0-9160-8efcd0bbde14.mov

**Comment by gjsjohnmurray** [comment]
I think this is as designed. How would the native OS dialog be able to browse the folders of the remote server?

**Comment by siddharthgpta** [comment]
> I think this is as designed. How would the native OS dialog be able to browse the folders of the remote server?

I have local repos that used to work the same way I believe. I can try going back to an older version and check.

For my work I admit all of it is on remote servers so this worked the same, but I have been tinkering on my personal laptop after some time and this behavior doesn't feel right.

**Comment by alexr00** [comment]
@siddharthgpta when your current workspace is local, we show the OS native file picker.

If you want to use the VS Code simple file picker (the one that shows when your current workspace is remote), then you can use the setting `"files.simpleDialog.enable": true`. 

If I'm misunderstanding your issue please let me know!

**Comment by siddharthgpta** [comment]
> @siddharthgpta when your current workspace is local, we show the OS native file picker.
> 
> If you want to use the VS Code simple file picker (the one that shows when your current workspace is remote), then you can use the setting `"files.simpleDialog.enable": true`.
> 
> If I'm misunderstanding your issue please let me know!

Thanks @alexr00! Yes this was the issue, I didn't realize this became an option.

I find the simple dialog faster than the OS native file picker. Curious how others feel about it :)
