### ISSUE TITLE
Clicking a link in an error opens two copies of the file

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#141757]
Run some code like so in the Interactive Window
```python
raise Exception('foo')
```
Click on the links

Another document opens.

I suspect this is because @rebornix fixed VS code to support the link clicking but we didn't remove our own handlers.

**Comment by rchiodo** [comment]
@rebornix can we disable the file link clicking for now? And work on making it open the same file/support line number?

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/commit/a853936292178200eb58c2a9904d7a7dcf98cce8.
