### ISSUE TITLE
`.razor` file should have default `Language Mode` of `razor`

### ISSUE THREAD

**Issue by TanayParikh** [microsoft/vscode#141756]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
- OS Version: Github codespaces

Steps to Reproduce:

1. Open a `.razor` file

Should utilize `razor` language syntax highlighting (Language Mode) by default without any other extensions installed given `razor` syntax is supported by default in VSCode. 

Note, `.cshtml` files already use `razor` syntax by default. This issue is to ensure `.razor` extension files also utilize `razor` syntax.

**Comment by IanMatthewHuff** [comment]
Verified. Insiders with extensions disabled. In a razor project both cshtml and razor files map to razor language and highlighting.
<img width="2374" alt="image" src="https://user-images.githubusercontent.com/812783/155387211-79d37445-6834-4162-8c0a-677fd59b4692.png">
