### ISSUE TITLE
more friendly error message(s) when offline

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#141762]
Testing #141296

When I am offline and search the marketplace, I get the message `Error while fetching extensions. XHR failed`.  We know we are offline, suggest to have a friendlier error message here.

`Unable to search the Marketplace when offline, please check your connection.` or something like that.

**Comment by sandy081** [comment]
@joaomoreno / @deepak1556 Is there an API to know if VS Code is offline? 

At present, the internal request service does not provide any info about this.

**Comment by deepak1556** [comment]
In the renderer process you can use the [navigator.onLine](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine) property and in the main process you can use [net.isOnline](https://github.com/electron/electron/blob/main/docs/api/net.md#netisonline) method.

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/151950963-07d13ac2-ed7c-4145-bf92-b743e14887f6.png)

**Comment by joyceerhl** [comment]
I see this in insiders.vscode.dev (PWA and web) still: 
![image](https://user-images.githubusercontent.com/30305945/155451255-74bf44bc-d705-4ddf-81a4-5a7d19f6f0ca.png)
![image](https://user-images.githubusercontent.com/30305945/155451234-1abe270b-d753-4f2e-9ad0-ad97e3759fc2.png)

**Comment by sandy081** [comment]
It works for me in insiders.vscode.dev - I turned off wifi for eg.,

![image](https://user-images.githubusercontent.com/10746682/155511682-2e7fad3c-636f-4d80-af52-99104ce40570.png)
