### ISSUE TITLE
! completion adding extra characters at end

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14177]
- VSCode Version: 1.7
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Open terminal
2. Type `git rebase --continue` and enter
3. `!git re<Tab>`
4. Expected `git rebase --continue` to show, but instead `git rebase --continue re` is shown.

**Comment by Tyriar** [comment]
I expect `!git rebase` to display, I'm assuming this is `zsh`?

Can you try repro on the [xterm.js demo](https://github.com/sourcelair/xterm.js) and report there if it repros?

**Comment by octref** [comment]
`!keyword` searches history backwards and find the last executed command which starts with `keyword`.

Yep, the demo has it after I run it using zsh:

![image](https://cloud.githubusercontent.com/assets/4033249/19622005/3c6993ce-9854-11e6-970a-a4b32a5ca752.png)

**Comment by Tyriar** [comment]
Please file there, thanks :)
