### ISSUE TITLE
Unable to log in Github

### ISSUE THREAD

**Issue by Arryboom** [microsoft/vscode#141750]
![image](https://user-images.githubusercontent.com/28295452/151605756-3b282487-2f31-4d7c-bd3f-531cc1a3e49c.png)

![image](https://user-images.githubusercontent.com/28295452/151605313-80dd0c26-74be-422f-a34b-659fdf983238.png)

check chrome console get

```
Refused to apply style from 'https://vscode-auth.github.com/css/fonts/roboto.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
vscode-auth.github.com/:1 Refused to apply style from 'https://vscode-auth.github.com/css/fonts/roboto.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```
tried firefox with the same authlink got similar error:
```
The resource from “https://vscode-auth.github.com/css/fonts/roboto.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

both tried private mode with the authlink ```https://vscode-auth.github.com/authorize/?callbackUri%20vscode://vscode.github-authentication/did-authenticate%253FwindowId%253D1```

vscode up to date
chrome up to date
firefox up to date

**Comment by Arryboom** [comment]
I think it could be related to the nosniff options added for security
![image](https://user-images.githubusercontent.com/28295452/151606523-76264b99-885a-42ed-a00a-dbfb7bd51a52.png)

**Comment by Arryboom** [comment]
VS Code Version: 1.63.2
OS Version: Win10 1905 X64

**Comment by Arryboom** [comment]
I'm still unable to login successfully,already tried some way as https://github.com/VSCodium/vscodium/issues/534 and https://github.com/microsoft/vscode-pull-request-github/issues/1221 provided,none of them working

**Comment by TylerLeonhardt** [comment]
I don't think it's that. A font loading shouldn't block the flow at all.

> both tried private mode with the authlink https://vscode-auth.github.com/authorize/?callbackUri%20vscode://vscode.github-authentication/did-authenticate%253FwindowId%253D1

was there anything else in the link? This only seems to have part of what I expected. It should contain a code query parameter among other things... You're using VS Code right? I have no idea if vscodium even supports auth so if that's what you're using, you'll have to discuss it with those folks.

If you are using VS Code, can you share a gif/video of you going through the flow? I wanna make sure each step is expected.

**Comment by Arryboom** [comment]
> /gifPlease

hi gif is too huge to upload I've been upload mp4 here:
https://public11temp.s3.us-west-1.amazonaws.com/2022-02-03-22-42-44.mp4

**Comment by TylerLeonhardt** [comment]
@Arryboom we just released a new version of VS Code (1.64). Can you please give that one a try and see if you still see this issue?

**Comment by Arryboom** [comment]
> @Arryboom we just released a new version of VS Code (1.64). Can you please give that one a try and see if you still see this issue?

no it didnt solve this issue,now version is 1.64.0,and still the same link

**Comment by Arryboom** [comment]
> @Arryboom we just released a new version of VS Code (1.64). Can you please give that one a try and see if you still see this issue?

Ok,i guess I know the problem,
you said  it's part of url before so I tried another computer and its full link was like ```https://vscode-auth.github.com/authorize/?callbackUri=vscode://vscode.github-authentication/did-authenticate%253FwindowId%253D1&scope=read:user&state=xxx&responseType=code&authServer=https://github.com```,it works fine.
Now back to this one(cannot login github),using sysinternal tools to check the start command line you can see the **:** in "read:user" was replaced with a space (split into two start command args into chrome)

**Comment by Arryboom** [comment]
update:
I've updated chrome to the lastest version,it now works as expected.
although Im still wonder why old version split the start command,and what's more weired is that even it's 2 seperated command args,the first url should stop at "read",not "253D1",and if it's ":" cause the issue,then why the first ":" in "vscode://" didnt split...

**Comment by TylerLeonhardt** [comment]
yeah that is veryyyyy strange. It's almost as if it saw that `&scope=read user` was not a valid query parameter and chopped that off and everything that came after it...

Not sure I understand why it behaved the way that you saw.. but I'm glad Chrome fixed it for you! :) 

I'll close this now since there's nothing I can really do here.

**Comment by Arryboom** [comment]
> yeah that is veryyyyy strange. It's almost as if it saw that `&scope=read user` was not a valid query parameter and chopped that off and everything that came after it...
> 
> Not sure I understand why it behaved the way that you saw.. but I'm glad Chrome fixed it for you! :)
> 
> I'll close this now since there's nothing I can really do here.

Thanks so much for help!:)
