### ISSUE TITLE
Feature: Add progress bar for downloads and updates

### ISSUE THREAD

**Issue by joeljose350** [microsoft/vscode#141729]
Add a progress bar that shows the progress of downloading extensions and updates to VS Code.

**Comment by joaomoreno** [comment]
As far as product updates go, we won't add a progress bar. Updates are meant to just happen in the background. If a progress bar is still intended, you can see one while you download the latest setup package from our webpage and then another one when you run it.

I'll forward to @sandy081 for extensions.

**Comment by sandy081** [comment]
The progress is shown in the Extensions View for the extension install & updates. Please check it.

**Comment by joeljose350** [comment]
I meant something that shows how far the download has progressed in percentage or megabytes. There is currently no way for users to know if the update is downloading or it has stalled due to a bad network connection or some other problem.

Replacing the loading animation at the top of the Extension Menu with a similar bar that shows the progress of downloading and installing extensions and extension updates would be a good feature, in my opinion.

I also think it would be a good idea to show the progress in percentage next to the "Downloading Update" text in the Settings sub-menu for VS Code.

My internet connection can be unreliable at times, so I have been in situations where I was expecting VS Code updates to install when they were waiting for my computer to reconnect to the Internet.
