### ISSUE TITLE
Managed to get duplicate build tasks running again

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#141774]
I hit ctrl+shift+b again when the fetching tasks status bar item was there, they were taking a very long time for some reason.

<img width="305" alt="Screen Shot 2022-01-28 at 3 51 41 pm" src="https://user-images.githubusercontent.com/2193314/151636759-5fbb58e4-f4c8-41e0-827c-e9587a2843ad.png">

The Tasks output channel is empty.

**Comment by Tyriar** [comment]
Version: 1.64.0-insider
Commit: b8178e3e2f3f620ebdd31dfbfba937ff1b12ee04
Date: 2022-01-28T10:16:18.006Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0

**Comment by Tyriar** [comment]
Looks like off is the default so I didn't have it on. Something weird was going on with my computer at the time, it seemed to be really slow overall at the OS level.

**Comment by joaomoreno** [comment]
For traceability, this is my old one: https://github.com/microsoft/vscode/issues/134430
