### ISSUE TITLE
Having shell integration enabled breaks terminal in remote windows

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#141748]
- Have shell integration enabled
- Use Remote-SSH from Mac -> Windows
- Open the terminal in this remote window
- Get this error notification

```
The terminal process failed to launch: Path to shell executable "\bin\zsh" does not exist.
```

I guess it's checking the local platform, not the remote platform

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/141599
