### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rezeqA** [microsoft/vscode#141787]
why when i pot any code i get an error ?!! when i wright a word like (node) its come with yellow color ?
node : The term 'node' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
At line:1 char:1
+ node -v
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (node:String) [], CommandNotFou
   ndException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by gjsjohnmurray** [comment]
/gifPlease

Please also post version info from Help\About.
