### ISSUE TITLE
Customize Layout picker - Menu Bar icon is confusing

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#141719]
Issue Type: <b>Bug</b>

The visual appearance of the icon alongside the Menu Bar item looks too much like the menu control ("hamburger") that appears at the top of the Activity Bar when the Menu Bar is hidden. This caused me to think at first that the visibility "eye" on the right of this selected or hovered row was reversed, since it was showing/tipping "hidden" when I could see the hamburger, and vice versa.

I think the confusion could be avoided by adding a thicker border at the top of the icon and moving the dropped-down lines away from the left edge so it becomes more representative of a bar across the top of the app with a menu descending from it.

/assign @misolori

VS Code version: Code - Insiders 1.64.0-insider (4af3e141defad7b6b96aa1e831f4b50f78abbe6d, 2022-01-28T05:15:27.497Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by misolori** [comment]
<img width="172" alt="CleanShot 2022-01-28 at 13 52 25@2x" src="https://user-images.githubusercontent.com/35271042/151626662-4d160e5e-b8bc-4132-a122-1e3f33d84cd6.png">

@gjsjohnmurray you're referring to this icon, correct? Would it help if the icon changed based on the toggle? Like if it's on, we show the menu and if it's off we show the title bar?

<img width="200" alt="CleanShot 2022-01-28 at 13 54 29@2x" src="https://user-images.githubusercontent.com/35271042/151626871-fc63af9b-ee34-4799-b4b1-5379b8818490.png">

**Comment by gjsjohnmurray** [comment]
Yes, that icon. I don't think it is necessary to switch between two icons as the user toggles the setting. None of the others in that section work that way do they? But I think the one icon you use for Menu Bar should have its 3-line representation of a dropped-down menu moved a bit to the right. Otherwise it looks a bit like the hamburger icon which appears at the top of the Activity Bar when the Menu Bar has been toggled off.

**Comment by misolori** [comment]
> None of the others in that section work that way do they

Yes, when the activity bar is switched to the right other icons adjust accordingly (like the sidebar)

> Otherwise it looks a bit like the hamburger icon which appears at the top of the Activity Bar when the Menu Bar has been toggled off

That actually is the intention, curious to know why you felt like this was wrong? The menu bar action toggles that menu

**Comment by sbatten** [comment]
I can echo some of the feelings of @gjsjohnmurray: we refer to the menu bar as being visible when it is in the title bar area and not visible after we've moved it to the activity bar. yet, the icon then represents the menu bar in its hidden state, or at least that is how it feels and no other visibility entry does this. as for the toggling back and forth, no other visibility entry changes its representation based on visibility.

**Comment by daviddossett** [comment]
What about something like this instead?

<img width="609" alt="CleanShot 2022-12-14 at 16 26 27@2x" src="https://user-images.githubusercontent.com/25163139/207744067-c2b91764-d035-49e2-a4c7-ed356497f838.png">

**Comment by sbatten** [comment]
@daviddossett I like the idea, but maybe making them less square (more rectangular like a word). Not sure if that means removing one of them for space

**Comment by daviddossett** [comment]
Good shout—how about:

<img width="647" alt="CleanShot 2022-12-14 at 16 54 39@2x" src="https://user-images.githubusercontent.com/25163139/207747045-088e89fa-76da-4e6c-9112-4466551eeb27.png">

**Comment by sbatten** [comment]
now i just need to test it out
