### ISSUE TITLE
Decouple tunnelFactory from RemoteAuthorityResolver

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#141737]
Some extensions may only provide an ability to tunnel ports (ex. my  [vscode-localtunnel](https://github.com/TylerLeonhardt/vscode-localtunnel) extension, or any other tunneling service).

It doesn't seem like I have the ability to specify that my extension should handle tunneling today - which would be ideal for having the ports that I tunnel be in the well known Ports view that you see with Codespaces.

@alexr00 pointed out to me that this is the API I would need to override in order to do this, but today, I don't have the ability to do so:
https://github.com/microsoft/vscode/blob/c393048b98a11880ccd54a8964a449a6cc6508bd/src/vscode-dts/vscode.proposed.resolvers.d.ts

**Comment by alexr00** [comment]
@TylerLeonhardt would your tunneling service provide features like changing who can access the forwarded port or changing whether it uses http or https?

**Comment by TylerLeonhardt** [comment]
Based on the [Localtunnel docs](https://github.com/localtunnel/localtunnel#options) it looks like I can specify a boolean to control whether or not it's an https server:

> local_https (boolean) Enable tunneling to local HTTPS server.

but I don't think I can control who has access to it. Localtunnel seems to be open to everyone.

**Comment by TylerLeonhardt** [comment]
Another example of a tunneling app is [ngrok](ngrok.com) and it looks like [they also support HTTPS](https://ngrok.com/docs#http-local-https) and [additionally support password protection](https://ngrok.com/docs#http-auth).

**Comment by alexr00** [comment]
👍 it sounds like we should ensure that we can support all the tunnel features that we let resolver tunnel providers support then.

**Comment by alexr00** [comment]
This has since been done! https://github.com/microsoft/vscode/pull/188270
