### ISSUE TITLE
Mssql query execution on tab change

### ISSUE THREAD

**Issue by Alex2jf** [microsoft/vscode#141713]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
- OS Version:
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Install SQL Server addon
2. Connect to database
3. Open and execute two sql queryes in different tabs, results must be in different tabs too
4. Results will refresh (query executed) every time when result tabs switched

**Comment by IllusionMH** [comment]
/causedByExtension

Looks like this behavior is caused by an extension and you should report this issue in extension's repo.
If this is webviews then it's possible that extensions doesn't enable persistence for webviews.
