### ISSUE TITLE
Task terminals with a failed `process` task aren't always reused properly

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#141728]
When the process task's process is never started (for example, when executable doesn't exist), that terminal won't be reused correctly. Full context at https://github.com/microsoft/vscode/issues/138104#issuecomment-1023405620

**Comment by rchiodo** [comment]
/verified

I created a task like so:

```json
,
        {
            "label": "Fail",
            "type":"process",
            "isBackground": true,
            "command": "foo.exe",
            "group": "build"
        }
```

In stable it constantly creates a new terminal
In insiders it reuses the one before it
