### ISSUE TITLE
Programmatically reveal a document in side bar by uri.

### ISSUE THREAD

**Issue by JiangJie** [microsoft/vscode#141705]
I use `QuickPick` to show some search files result.
And I want to reveal the selected item in side bar, but I have no idea how to do.
I found `File: Reveal Active File in Side Bar` command, it only support the active file, doesn't meet my needs.
So shall we add some apis or commands to support?
Thanks!

**Comment by ArturoDent** [comment]
Try this using the `revealInExplorer` command:

```js
// get path from the QuickPick and make it into a `Uri`
const fileURI = vscode.Uri.file('C:\\Users\\Mark\\OneDrive\\Test Bed\\zip\\gulpfile.js');  
await vscode.commands.executeCommand('revealInExplorer', fileURI);
```

**Comment by JacksonKearl** [comment]
Confirmed @ArturoDent's proposed solution works as expected. Thanks!

**Comment by JiangJie** [comment]
> Confirmed @ArturoDent's proposed solution works as expected. Thanks!

+1
Thanks!
