### ISSUE TITLE
macOS 12.3 `code` shell command doesn't work due to Python 2 being removed

### ISSUE THREAD

**Issue by fishcharlie** [microsoft/vscode#141738]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.63.2 (Universal)
- OS Version: macOS 12.3 Beta (21E5196i)

**Summary**

In macOS 12.3 beta Apple removed support for Python 2. Additionally Python 3 no longer comes bundled with macOS. This causes the `code` command to not work anymore.

- https://www.macrumors.com/2022/01/28/apple-removing-python-2-in-macos-12-3/
- https://www.idownloadblog.com/2022/01/28/python-macos-monterey-no-more/

The fact that VS Code is using Python 2 which hasn’t been officially supported since January 2020 is kinda crazy.

This should be fixed ASAP.

---

Steps to Reproduce:

1. Ensure you are running macOS 12.3 Beta (21E5196i)
2. `Shell command: Install 'code' command in path` in VS Code
3. Run `code` in Terminal

```
/usr/local/bin/code: line 6: python: command not found
/usr/local/bin/code: line 10: ./MacOS/Electron: No such file or directory
```

**Comment by fishcharlie** [comment]
Created a PR for this at #141749. Couple of questions included in there that might lead to more work tho. But figured it'd be a good start to get the ball rolling and try to get this done as quick as possible 😃.

**Comment by bpasero** [comment]
See https://github.com/microsoft/vscode/issues/134635 and https://github.com/microsoft/vscode/pull/138582

//cc @deepak1556 @joaomoreno

**Comment by makaracc** [comment]
I got mine working by:

1. cd /usr/local/bin
2. nano code
3. change python => python3 (on the line where it says "function realpath() { python -c ........" to "function realpath() { python3 -c ......"

And it's all set, hope it helps :) , and maybe there will be update to fix this idk

**Comment by xdarkroth** [comment]
This worked for me, thanks!

**Comment by MovingKyu** [comment]
I have fixed the issue with "code" not working on local computer after replacing "python" with "python3".

Does any of you have problem withe the command "code" on remote server? The "code" command on remote server stop working after I have installed Mac OS 12.3. The command simply does nothing.

For example, when I open up file from terminal, I could easily do with "code ${FILE}"

After installing Mac OS 12.3, the command does not work anymore on remote server. My second Mac without beta version works fine on remote server, and the command works as usual. Anyone has an idea how to fix the problem with 12.3 version?

**Comment by LunarLanding** [comment]
Apparently this script depends on python3 to provide `realpath`. It's a bit kaufkian.

**Comment by jiteshdhamaniya** [comment]
> 2\. nano code

This works for me. thanks

**Comment by LouieMjr** [comment]
Npm install isn't working now because of the same issue it seems. Anyone get that ERR yet ?

**Comment by dmackinn** [comment]
For those of you having issues with this on 12.3 you can always just symlink python to python3 in /usr/local/bin and it will work.

**Comment by orditeck** [comment]
> For those of you having issues with this on 12.3 you can always just symlink python to python3 in /usr/local/bin and it will work.

I had `python3` installed through `brew` so I simply ran `ln -s /opt/homebrew/bin/python3 /opt/homebrew/bin/python`
