### ISSUE TITLE
Existing terminal tabs not reacting to changes in terminal.integrated.tabs.title

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#141733]
With the following settings:

```
  "terminal.integrated.tabs.title": "${process}${separator}${cwdFolder}",
  "terminal.integrated.tabs.description": "${task}${separator}${process}",
```

I'm not seeing `cwdFolder` show up:

![image](https://user-images.githubusercontent.com/2193314/151571243-6e031b0f-ab9c-443c-b8a6-e6516c72658c.png)

Changing to `"${process}${separator}(${cwdFolder})"` also doesn't show the (), but it does when I add that to description. Creating a new terminal will have it applied though:

![image](https://user-images.githubusercontent.com/2193314/151571754-998e9ef0-9b10-4b99-a22f-f540e7a9177d.png)

**Comment by meganrogge** [comment]
can't repro on mac
![Recording 2022-01-28 at 11 24 13](https://user-images.githubusercontent.com/29464607/151593181-d3259cfa-4dcc-44a6-9d9f-b67ef5e8a26f.gif)
