### ISSUE TITLE
Windows 11, switching to Visual Studio Code freezes that interface

### ISSUE THREAD

**Issue by navidmatin** [microsoft/vscode#141735]
Issue Type: <b>Bug</b>

- Use Windows 11
- Open up a file with visual studio code (I've been using .js)
- Switch to a chrome tab on Windows 11
- switch back to Visual Studio Code by clicking on the taskbar icon
- Intermittently the visual studio code interface freezes and does not allow editing the text or interacting with the window. (this doesn't happen every time, I noticed it more with chrome pages with heavy javascript on the page)
- Workaround: Use the top of the Visual Studio Code screen to resize it or move the window around and it will allow editing again.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.21GB free)|
|Process Argv|. --crash-reporter-id 72c6bb31-79a7-4fad-abea-9a0cb2307c3d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
azurite|Azu|3.15.0
solargraph|cas|0.23.0
npm-intellisense|chr|1.4.0
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
prettier-vscode|esb|9.1.0
rails-snippets|Hri|1.0.8
vscode-edit-csv|jan|0.6.4
minifyall|jos|2.10.0
vscode-docker|ms-|1.19.0
csharp|ms-|1.24.0
remote-wsl|ms-|0.63.13
powershell|ms-|2021.12.0
vscode-react-native|msj|1.9.0
ruby|reb|0.28.1
sass-indented|syl|1.8.18
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30429731
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30428979
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710:30416614
vscop841cf:30429142
vsbas813:30426126

```

</details>

**Comment by deepak1556** [comment]
Same root cause as https://github.com/microsoft/vscode/issues/123257, merging to it. Please follow that issue for updates, thanks!
