### ISSUE TITLE
virtual keyboard 

### ISSUE THREAD

**Issue by AggelosPa** [microsoft/vscode#141771]
Issue Type: <b>Bug</b>

virtual keyboard keeps popping up every time i tap anywhere on the app

I have a surface pro 8 tablet and when I've been using it without a physical keyboard anything I touch inside the vscode window makes the virtual keyboard pop up and if I touch something again the keyboard closes

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (3.34GB free)|
|Process Argv|--crash-reporter-id 8ab0e547-64d7-4892-8eac-1c9f1969a72c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gather|ms-|2021.9.1
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.5
jupyter|ms-|2021.11.1001550889
vsliveshare|ms-|1.0.5273

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30429732
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
wslgetstartedc:30426334
vscop804:30404766
vscop940:30404999
vsrem710:30416614
vsbas813:30426126

```

</details>

**Comment by TylerLeonhardt** [comment]
I wanna see if there's a more narrowed region of VS Code that causes your keyboard to pop up or if it is truly anywhere in the app.

**Comment by AggelosPa** [comment]
Hi guys

I hope this is clear enough! If you need anything else please let me know
![Recording 2022-02-02 at 20 52 57](https://user-images.githubusercontent.com/82258900/152236095-1f1f3dd0-9b61-4efd-934c-5082237de747.gif)

**Comment by alexdima** [comment]
@bpasero @rebornix It looks like taping anywhere on the workbench brings up the touch keyboard on Windows. Do you have any clue what might be causing this? Is it the focus being redirected to the editor?

**Comment by bpasero** [comment]
🤷 , @isidorn I remember you once went through various pieces of our UI to prevent the keyboard from popping up on iPad, is this related?

**Comment by isidorn** [comment]
On the iPad the keyboard pops up when the focus is moved into the editor. So I did some changes to minimise the automatic movement of focus into the editor.

**Comment by bpasero** [comment]
To my knowledge we do not have code that would focus into the editor on touch, but could we add a breakpoint into the focus method of the editor to see if it gets called?

https://github.com/microsoft/vscode/blob/e6a6c81bd14c71f0e2fd29f7a29f1604cc888f78/src/vs/workbench/browser/parts/editor/textEditor.ts#L200-L205

**Comment by AggelosPa** [comment]
Hi guys

I've narrowed down the problem to the insertion point! (the blinking line in your document that indicates where text is inserted when you type)

If any line at all is selected then touching anywhere inside the VScode app brings up the vitrual keyboard. If you open a file and do not click anywhere to start typing then you can freely scroll or tap anywhere inside the app and the virtual keyboard will not pop up

**Comment by TylerLeonhardt** [comment]
@AggelosPa just to rule things out, can you try running vscode with extensions disabled? `code   --disable-extensions` I want to make sure it's not an extension causing the focus in the editor

**Comment by AggelosPa** [comment]
> @AggelosPa just to rule things out, can you try running vscode with extensions disabled? `code --disable-extensions` I want to make sure it's not an extension causing the focus in the editor

Hello, apologies for the late reply.

The behaviour of of the bug has changed a bit. Now on any touch anywhere on the vscode work area the touch keyboard opens and stays open instead of opening and closing after every touch like the video before. 

I tried with all extensions turned off and its still the same behaviour.

**Comment by TylerLeonhardt** [comment]
> Now on any touch anywhere on the vscode work area

is the work area as you describe, just the editor or even things like the side bar, the panel, the tab bar, etc?

**Comment by AggelosPa** [comment]
> Hi Tyler
> 
> I hope this is clear enough! If you need anything else please let me know ![Recording 2022-02-02 at 20 52 57](https://user-images.githubusercontent.com/82258900/152236095-1f1f3dd0-9b61-4efd-934c-5082237de747.gif)

@TylerLeonhardt Same areas as shown in this gif! So that would include all that you mentioned!

**Comment by TylerLeonhardt** [comment]
I just noticed this issue https://github.com/microsoft/vscode/issues/143558 that @bpasero opened and fixed a few days ago... it seems to be related. Can you please try with [VS Code Insiders](https://code.visualstudio.com/insiders) and see if it's fixed for you?
