### ISSUE TITLE
Session is partially lost when opening a file through right-click menu

### ISSUE THREAD

**Issue by david-cortes** [microsoft/vscode#141742]
Does this issue occur when all extensions are disabled?: Not applicable

- VS Code Version: 1.63.2
- OS Version: debian sid (linux)

**Steps to Reproduce:**

1. Launch vscode with default settings, create several tabs, save some but not all of them as files, then close the application without closing the tabs.
2. Launch vscode again, notice that all tabs are there as they were left before, close it.
3. Open a file explorer, right-click some file and select to open it with vscode.

**Expected behavior:** the new file should open as an additional tab at the end when vscode is launched, preserving all tabs that were left there from the previous session.

**Actual behavior:** all tabs that were there from the previous session and which were saved will be missing when a new vscode instance is launched to open the new file.

**Comment by bpasero** [comment]
Setting: `window.restoreWindows: "preserve"`
