### ISSUE TITLE
Workbench opens new editor instances unexpectedly 

### ISSUE THREAD

**Issue by drew-512** [microsoft/vscode#141703]
Issue Type: <b>Bug</b>

Hi friends, long time VS Code evangelist and lover!

I typically have many editor panes open so that I'm looking at 4+ editor panes.

Current behavior:
1) Clicking / opening `foo.go` and have it remain open ​in panel tab stack A (even with a double click no the tab to anchor it).
2) Bring focus to panel tab stack B
3) Clicking on `foo.go` in the workbench and it opens in panel *B*

Expected behavior:
3) Clicking on `foo.go` in the workbench brings focus to the (already open!) `foo.go` editor tab in panel A.

I get that this may be ok behavior for some, but this is miserable for folks like me who have to keep a lot of files in my head, where keeping them in the same pane is helpful for my sanity.

Perhaps then this bug request is really a feature request to add a setting to change this behavior.  It seems like a really easy add/change for you ninjas!

Thanks friends, God bless!
Drew

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|32.00GB (10.00GB free)|
|Process Argv|--crash-reporter-id 28e3a4a8-6d50-4270-878b-98c503fe09bc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
cmake-format|che|0.6.11
doxdocgen|csc|1.3.2
xml|Dot|2.5.1
go|gol|0.29.0
tab-indent-space-align|j-z|0.0.3
better-cpp-syntax|jef|1.15.10
csharp|ms-|1.23.16
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.5.745244803
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.58.5
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
code-spell-checker|str|1.10.2
cmake|twx|0.0.17
unity-debug|Uni|3.0.2
vscode-proto3|zxh|0.5.5

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30424895
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710:30416614
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by bpasero** [comment]
You can change this behaviour by setting `workbench.editor.revealIfOpen: true`.

**Comment by drew-512** [comment]
> You can change this behaviour by setting `workbench.editor.revealIfOpen: true`.

How'd I miss that?!  Thanks warrior!
