### ISSUE TITLE
[Feature] Search/Replace: use a wildcard character in Replace field (RegEx Mode)

### ISSUE THREAD

**Issue by ikourfaln** [Microsoft/vscode#14175]
![search](https://cloud.githubusercontent.com/assets/9744226/19606093/c4e0bcf2-97b7-11e6-89e0-a091eab2b32c.png)

Hi,

Im trying to search and replace my code by using Regulare Expression, but I need a wildcard character to use it in replace content. Really usefull.

Thanx for your hard work

**Comment by roblourens** [comment]
You can capture a group with `()` and use that in 'replace' with `$1`. And if you have more than one, `$2`, etc

**Comment by ikourfaln** [comment]
Ok thanx. I tought that feature doesnt exist
