### ISSUE TITLE
Format Selection support for vue files

### ISSUE THREAD

**Issue by anzuj** [microsoft/vscode#141727]
When working with .vue format, we only have "Format document" option. This is very limiting. For example when fixing a bug in a large component, you want to format only what you've added, but not touch the rest of the component. Formatting the whole thing would create whitespace/minor formatting diffs that would make the diff reading illegible for the code reviewer

Therefore a feature I'd love to see is a "Format selection" also supporting .vue files speeding up the workflow.

**Comment by IllusionMH** [comment]
VS Code doesn't provide support for `.vue` files out of the box and these files and formatting are handled by extension? i think it's Vetur.

Vetur clearly states that Format Selection is not supported without providing reason -
https://vuejs.github.io/vetur/guide/formatting.html#formatters

So this feature should be requested in extension's repo, unless you have concrete request for missing API that would enable Vetur to provide this feature.

**Comment by anzuj** [comment]
@IllusionMH I am using Vetur indeed, but wasn't aware that the missing "Format selection" option in the right click menu was down to Vetur, not VS Code. 

Thank you for a clear explanation, this issue can then be closed and I'll try my luck with Vetur's repo :)
