### ISSUE TITLE
Region / EndRegion not in line with PowerShell ISE

### ISSUE THREAD

**Issue by cjvanderlinden** [Microsoft/vscode#14173]
- VSCode Version: 1.6.1
- OS Version: Windows 7 Pro
- PowerShell Version: v5

Steps to Reproduce:

1. create #Region and #EndRegion tags at the same column tab
2. put code between region tags and make sure they line up at the same column tab
3. VSCode does not allow you to expand or collapse code between region tags when the code between the tags line up with the region tags themselves (where as it does allow you to collapse in PowerShell ISE).

Example:
![image](https://cloud.githubusercontent.com/assets/8312392/19605021/e9ede31c-9785-11e6-85a4-652f455b77ab.png)

based on the final example in screenshot above, it seems like region tagging isn't even working, and just seems to be working due to VSCode's default settings

**Comment by roblourens** [comment]
Code folding is just based on indentation, it's not actually looking at the region tags. #12146
