### ISSUE TITLE
The app opens then immediately closes without displaying any error

### ISSUE THREAD

**Issue by groksrc** [Microsoft/vscode#14182]
- VSCode Version: 1.7.0-insider
  69fe34632fa4651e89db040fb205f0c739598197
- OS Version: macOS Sierra
  Version 10.12

Steps to Reproduce:
1. Double click the `Visual Studio Code - Insiders.app` in the Applications folder to start the app per usual.

Expected Behavior:
The application opens and I can edit files.

Actual Behavior:
The application immediately closes without warning or displaying an error.

Attempted remediation steps:
1. Reinstalling the application has no effect
2. I have removed the directories `~/Library/Caches/com.microsoft.VSCodeInsiders` and `~/Library/Caches/com.microsoft.VSCodeInsiders.ShipIt`
3. `code --disable-extensions` does not open the app

No remediation steps have had any effect. The app simply will not open.

Additional Information:
1. The stable version runs without issue: v1.6.1
   9e4e44c19e393803e2b05fe2323cf4ed7e36880e
2. `code --disable-extensions --disable-gpu -w` returns almost immediately.
3. What led to this? Honestly have no idea. I have not been working on any large projects or things that have been giving the application fits. This problem started today after running successfully for many weeks. I upgraded to macOS Sierra approximately two weeks ago without issue.

**Comment by roblourens** [comment]
How about `~/Library/Application Support/Code - Insiders`?

Someone reported this in gitter too

**Comment by roblourens** [comment]
Can you try launching with `--verbose`?

**Comment by groksrc** [comment]
Interesting...

```
itsacomputer:~ groksrc$ code --verbose
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[main 2:35:04 PM] Starting VS Code in verbose mode
[main 2:35:04 PM] from: /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app
[main 2:35:04 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false }
TypeError: Cannot use 'in' operator to search for 'workspacePath' in null
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:10:17974
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:4833
    at Array.filter (native)
    at Object.d [as distinct] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:4808)
    at e.open (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:10:17930)
    at V (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:11:26216)
    at t.invokeFunction (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:8:18263)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:11:30386
    at Object.v [as _notify] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:5:29802)
    at Object.enter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:6:1367)
```

**Comment by roblourens** [comment]
That line is

```js
t=this.cliToPaths(e.cli,i)}e.restoreBackups&&(this.backupService.getWorkspaceBackupPathsSync().forEach(function(e){t.push(n.toIPath(e))}),t=f.distinct(t,function(e){return"workspacePath"in e?a.isLinux?e.workspacePath:e.workspacePath.toLowerCase():e.workspacePath}));var o=[],s=[],u=t.filter(function(e){return e.workspacePath&&
```

**Comment by groksrc** [comment]
I was just looking through the source, I agree this appears to be related to the changes this iteration for Hot Exit: https://github.com/Microsoft/vscode/blob/aab05a86f5a959accce2fa388a36fb2cbc603f2b/src/vs/platform/backup/node/backupService.ts#L21

**Comment by Tyriar** [comment]
I've reverted the changes responsible and will queue a new build. This will stay open until it's verified to be fixed on the feature branch.

**Comment by Tyriar** [comment]
The new builds will have to wait until this [DNS DDoS attack](arstechnica.com/security/2016/10/dos-attack-on-major-dns-provider-brings-internet-to-morning-crawl/) is over.

**Comment by bpasero** [comment]
Can this be closed?

**Comment by Tyriar** [comment]
Yes this was fixed before second merge

**Comment by KSuttle-cng** [comment]
I'm experiencing this now as well. `code --verbose` outputs nothing at all. Just sits for a 2 Mississippi, and then exits.

**Comment by bpasero** [comment]
@KSuttle-cng maybe another instance of a Code process is hanging around, can you check in the process manager and kill it?

**Comment by KSuttle-cng** [comment]
I rebooted my machine and it worked again. :man_shrugging:
