### ISSUE TITLE
can't start from the command line on macOS 12.3 beta

### ISSUE THREAD

**Issue by zandr14** [microsoft/vscode#141834]
Issue Type: <b>Bug</b>

After upgrading to macos 12.3 beta I get the following:

user@users-MacBook-Pro ~ % code
/usr/local/bin/code: line 6: python: command not found
/usr/local/bin/code: line 10: ./MacOS/Electron: No such file or directory

Tried to use 'Shell Command: Install 'code' command in PATH' and also  to reinstall the Code, but without any luck - the same effect of both times.

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (7.16GB free)|
|Process Argv|--crash-reporter-id 7bd0f5f0-5f46-48ec-b213-c734970518d5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
vscode-test-explorer|hbe|2.21.1
better-cpp-syntax|jef|1.15.10
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.1
cpptools-extension-pack|ms-|1.1.0
test-adapter-converter|ms-|0.1.5
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30429732
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vscop804cf:30404767
vs360cf:30404996
vsrem710:30416614

```

</details>

**Comment by zandr14** [comment]
Seems like the tuned python somehow:

user@users-MacBook-Pro ~ % ls -la /usr/bin/python
lrwxr-xr-x  1 root  wheel  85 Jan 25 10:09 /usr/bin/python -> ../../AppleInternal/Library/Frameworks/PythonLegacy.framework/Versions/2.7/bin/python

user@users-MacBook-Pro ~ % ls -la /usr/bin/python3
-rwxr-xr-x  76 root  wheel  167104 Jan 25 10:09 /usr/bin/python3

**Comment by zandr14** [comment]
Tuned the file /usr/local/bin/code like below:

...
function realpath() { python3 ....

and all started to work.

**Comment by zwaldowski** [comment]
Via the [Release Notes](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes):

> Python 2.7 was removed from macOS in this update. Developers should use Python 3 or an alternative language instead. (39795874)

**Comment by bp88** [comment]
I just want to add some feedback from the perspective supporting VS Code in an enterprise environment. Please do not rely on `python3` as this would require that Xcode CLI tools be installed or that Python 3 be installed from a different source. This would mean that IT administrators deploying VS Code would then have to potentially need to start looking at deploying Python 3 separately in macOS which just adds an extra layer of complication.

It would be good to rethink how to achieve the goal that realpath achieves using built-in shells. Or better yet, make `code` a compiled binary that doesn't rely on any other built-in binaries in macOS.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/134635, will be addressed by https://github.com/microsoft/vscode/pull/138582

**Comment by spaquet** [comment]
@bp88 
Here is my proposed solution:
```
#!/usr/bin/env bash
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

function realpath() {
  if [[ ! -z $(which python3 | grep "/python3") ]]; then
    # python3 is installed and will be used
    python3 -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0";
  elif [[ ! -z $(which python | grep "/python") ]]; then
    # Didn't find python3, let's try python
    python -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0";
  else
    # Python is not installed at all. Exit with error.
    echo "Python is not installed."
    exit
  fi
}

CONTENTS="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
ELECTRON="$CONTENTS/MacOS/Electron"
CLI="$CONTENTS/Resources/app/out/cli.js"
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --ms-enable-electron-run-as-node "$@"
exit $?
```

This tests for python3 and python and if none is installed displays an error message.
