### ISSUE TITLE
VsCode shows task errors before activating the extension

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode#141896]
There is a scenario where the user has saved their extension tasks in the vsCode temporary folder (i.e. 'AppData'). In this case, when launching vscode, vscode will immediately show an error about the cpp extension's defined task (i.e. cppbuild):

`There are task errors. See the output for details.`

and the output is:
```
Error: The cppbuild task detection didn't contribute a task for the following configuration:
{
    "type": "cppbuild",
     .....
    "detail": "AppData Folder."
}
The task will be ignored.
```
The extension has not been activated at this point yet.

**Comment by alexr00** [comment]
> There is a scenario where the user has saved their extension tasks in the vsCode temporary folder (i.e. 'AppData').

Can you describe how a user gets into this situation?

**Comment by alexr00** [comment]
I took a look at the activation events at 
https://github.com/microsoft/vscode-cpptools/blob/6ad565886b9cbfca9876c05d9a0fd1967d4291f6/Extension/package.json#L47-L83

It looks like there is no activation event related to tasks. We have a new activation event you can use starting with version 1.64: `onTaskType:foo`, so for you it would be `onTaskType:cppbuild`. 

For older versions, you can use `onCommand:workbench.action.tasks.runTask` if you must. However, your extension will activate too eagerly if you do this. I would recommend only using the new `onTaskType` event.
