### ISSUE TITLE
Cannot open link in external browser

### ISSUE THREAD

**Issue by Kritiqual** [microsoft/vscode#141858]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Arch Linux (5.16.4-arch1-1)

Steps to Reproduce:

1. Create new untitle file
2. Type down some link, e.g `https://.github.com`
3. Follow link (`Ctrl + left click`)
4. The browser not open that link
5. Something I have tried:
 - Added to trusted domain, suggested by [issue #84265 (comment)](https://github.com/microsoft/vscode/issues/84265#issuecomment-551892925)
 - Via terminal: `xdg-open https://github.com` and it works fine
 - Via vscode developer tool, suggested by [issue #84265 (comment)](https://github.com/microsoft/vscode/issues/84265#issuecomment-553478691) and it give me this error:
![image](https://user-images.githubusercontent.com/67857299/151751687-88d947e5-30f0-49d3-85f5-a6d9497655c3.png)
6. Note: Vscode also do nothing when do some action that open in external program, e.g:
 - I cannot use "sign in to github to sync setting"
 - I have gitlens extension installed, it cannot open commit in github

**Comment by deepak1556** [comment]
Is this with a snap install of vscode ?

**Comment by Kritiqual** [comment]
No, I installed it from AUR (visual-studio-code-bin)

**Comment by deepak1556** [comment]
Can you check if the issue repros with the following build that uses a newer runtime, thanks!

[linux x64 exploration archive](https://az764295.vo.msecnd.net/exploration/8eab3dba050a3bd11dcdd33f6bca2fe807cf3f9c/code-exploration-x64-1643723453.tar.gz)

**Comment by Kritiqual** [comment]
Hi, I downloaded the file, but, I cannot run it, do I need to delete the previous version (visual-sutudio-code-bin)?

**Comment by Kritiqual** [comment]
The problem is no longer exist on the latest version (1.64.0), so I'll close the issue
