### ISSUE TITLE
多行编辑时使用Tab,未按照预期进行缩进

### ISSUE THREAD

**Issue by a15355447898a** [microsoft/vscode#141820]
Issue Type: <b>Bug</b>
# Pressing the tab key in multiline editing doesn't indent the blocks as expected
1. 开启多行编辑(enable multiline editing)
[![H9OKr8.png](https://s4.ax1x.com/2022/01/30/H9OKr8.png)](https://imgtu.com/i/H9OKr8)
2. 按下Tab(press tab)
[![H9OuKf.png](https://s4.ax1x.com/2022/01/30/H9OuKf.png)](https://imgtu.com/i/H9OuKf)
可以看到只有一行缩进了(there is only one line that was indented)

VS Code version: Code - OSS 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2022-01-19T16:00:00.869Z)
OS version: Linux x64 5.16.3-zen1-1-zen
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G3240 @ 3.10GHz (2 x 2762)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 6|
|Memory (System)|11.50GB (0.31GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.1.4
code-runner|for|0.11.6
todo-tree|Gru|0.0.215
latex-workshop|Jam|8.23.0
language-julia|jul|1.5.10
git-graph|mhu|1.30.0
vscode-language-pack-zh-hans|MS-|1.63.3
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.3
jupyter|ms-|2021.11.1001552333
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
cpptools|ms-|1.7.1
markdown-all-in-one|yzh|3.4.0

</details>

**Comment by Lemmingh** [comment]
https://github.com/yzhang-gh/vscode-markdown/issues/829
