### ISSUE TITLE
Renaming Command Line Aliases

### ISSUE THREAD

**Issue by annedranowski** [microsoft/vscode#141808]
Setup: 

Using MacOS Monterey
Installed 'code-insiders' shortcut through vs code insiders editor command palette, it works just fine
But, I do not see the application in the path (on running echo $PATH in terminal) 
I also do not have .zprofile or .bash_profile files 
I do have .zshrc and .bashrc files, but those do not contain any vs code aliases 

Question: Where does vs code put the code insiders shortcut and how do I change it?

Thank you

**Comment by Tyriar** [comment]
From the code it looks like it installs it to `/usr/local/bin`:

https://github.com/microsoft/vscode/blob/4d930765f376af528b5e611c542b27a6a1045986/src/vs/platform/native/electron-main/nativeHostMainService.ts#L353-L355

FYI you should be able to run `which code-insiders` to find that path, typing `alias` should show all your aliases.
