### ISSUE TITLE
I can't run any of my code to test

### ISSUE THREAD

**Issue by kay0826** [microsoft/vscode#141843]
Issue Type: <b>Bug</b>

I just started using VS and I have tried researching other methods on this but every time I have tried to run code in my program, I don't see it in the output section. I have tried installing different extensions to help run the code, but I don't know which one to use. should I try to re install the program?  Please get back to me within a timely manner. 
Thank you.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU 4205U @ 1.80GHz (2 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.85GB (0.60GB free)|
|Process Argv|--crash-reporter-id 711aeb77-8bc8-4c86-a096-c40b8c83aac1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.7.0
code-runner|for|0.11.6
vs-code-runner|Har|2.0.1
csharp|ms-|1.24.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.5
jupyter|ms-|2021.11.1001550889
vscodeintellicode|Vis|1.2.16

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30428978
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710:30416614
vsbas813:30426126

```

</details>

**Comment by weinand** [comment]
What code are you trying to run?

**Comment by kay0826** [comment]
I am trying to run C# code. I think I might have messed up the settings in
the j.son  file but i'm not sure what was there first.
