### ISSUE TITLE
Using VoiceOver with a braille input device causes input to duplicate after a space

### ISSUE THREAD

**Issue by alextraub** [microsoft/vscode#141804]
Issue Type: <b>Bug</b>

##### VoiceOver settings
All settings are found in *VoiceOver Utility>Braille>Translation*.

1. Input: __Six dot__/__Contracted six dot__
2. Translate after: __a delay__
<img width="817" alt="Braille Translation Settings" src="https://user-images.githubusercontent.com/20158051/151676730-0e982bb2-ce8f-4fcd-b5d7-72017d4028ba.png">

##### Steps to reproduce
1. With VoiceOver enabled and a braille input device connected to the machine, open a file in VS Code (any file will work)
2. In the editor, enter some non whitespace text through the braille keyboard
3. Wait for the braille input to get translated __or__ enter a space then backspace on the braille keyboard
4. Enter space on the braille keyboard

![Issue](https://user-images.githubusercontent.com/20158051/151676755-4fc6046f-d444-4ee3-bcc4-271bbb0c6299.gif)
__Note__ This was captured from the Insiders build:  1.64.0-insider (It behaves the same on the version of VS Code I'm using to report this bug)

##### Behavior
For the expected/observed behavior, the editor contents will be in single quotes, using the input 'hello' as an example.

__Expected:__ 'hello '
__Observed:__ 'hellohello '

<details>
<summary>Braille display info</summary>

<img width="816" alt="Braill Display" src="https://user-images.githubusercontent.com/20158051/151677020-8d25be70-1712-4276-9cc0-4ef779d6afb0.png"></details>

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|18, 16, 17|
|Memory (System)|16.00GB (1.30GB free)|
|Process Argv|--disable-extension . --crash-reporter-id 9343622e-38c0-4ce2-aec1-bdff5c819f99|
|Screen Reader|yes|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30429731
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30428979
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710cf:30416617

```

</details>

**Comment by isidorn** [comment]
@alextraub thanks a lot for filling this issue. 
Can you also reproduce this issue with Chrome and a `textArea`. For example on this page https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea 

If yes -> can you please file an issue against Chrome here https://bugs.chromium.org/p/chromium/issues/list
If no -> can you please try to repro with this VS Code build https://az764295.vo.msecnd.net/exploration/8eab3dba050a3bd11dcdd33f6bca2fe807cf3f9c/VSCode-darwin-universal.zip

Somewhat related https://github.com/microsoft/vscode/issues/95783

**Comment by alextraub** [comment]
@isidorn so, it does seem to be an issue with Chrome. I'll open an issue on their repo.

**Comment by isidorn** [comment]
@alextraub great. Can you just share the issue number? We like to have links to upstream issues.

**Comment by alextraub** [comment]
[Chromium Issue 1293153](https://bugs.chromium.org/p/chromium/issues/detail?id=1293153)

**Comment by isidorn** [comment]
@alextraub Chromium people responded. Can you just check if you can repro with Chrome 100, since the engineers there say it can no longer repro with the latest. If that is the case we should pick up that Chrome version hopefully in the next year...
