### ISSUE TITLE
Open terminal as tab in editor

### ISSUE THREAD

**Issue by yuritoledo** [microsoft/vscode#141890]
I'd like to suggest the possibility of open the terminal as a file in editor tabs, just like the print

![image](https://user-images.githubusercontent.com/18474538/151852338-715bd363-949a-487b-bbcc-20aa1800162a.png)

Is it possible today? Can you guys make it viable?

Thanks

**Comment by mhanuszh** [comment]
https://code.visualstudio.com/updates/v1_58#_terminals-in-the-editor-area
