### ISSUE TITLE
Split the color property of dropdown list colors from list.xxxx colors

### ISSUE THREAD

**Issue by huacat1017** [microsoft/vscode#141824]
I'm a VSCode Theme Developer.
I have a hard time customizing the list of dropdown colors.(The dropdown colors I mean doesn't include menu colors.)
The available properties of the list of dropdown:
![dropdown available property](https://user-images.githubusercontent.com/57604590/151696665-7e533192-6cb8-4d63-ada5-37816c873322.png)
The unavailable properties I would like to add is now linked to these properties:
![dropdown unavailable property is linked to](https://user-images.githubusercontent.com/57604590/151697095-c624a64a-bf16-49b2-abca-54d15244dafa.png)
I think hovering the list item of dropdown should be different from hovering sidebar's because the background of the two may be different.
But now hovering the list item of dropdown is included in list.xxx properties.

**Comment by aeschli** [comment]
Not sure who owns the SelectBox these days.

**Comment by bpasero** [comment]
The dropdown widget is implemented on top of the list widget (as far as I remember).

**Comment by isidorn** [comment]
I think @JacksonKearl took it over. Thus assigning this to him for now.

**Comment by JacksonKearl** [comment]
It's a fair feature request but I do not have capacity to dig into it at the moment. A good starting point to anyone interested in implementing this would be here: https://github.com/microsoft/vscode/blob/f4710a198fbc1b727a82f3ede4a718522182394c/src/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L349-L394
https://github.com/microsoft/vscode/blob/24ba24e3298baf980cd6f9ea68b29353f7a45aa9/src/vs/platform/theme/common/styler.ts#L125-L140
