### ISSUE TITLE
Allow debug adapters to customize the behavior of the 'restart' button

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14189]
For the chrome debugging extension, it would be much more useful if the debug 'restart' button/action could refresh the page. This could be implemented by the debug adapter. For other cases, the current behavior should be kept where vscode shuts down/restarts the debug adapter. Is this generic enough to be part of the debug protocol?

**Comment by weinand** [comment]
@roblourens yes, that makes a lot of sense (and we were discussing this use case already when implementing the current 'restart' functionality).
I'll come up with a proposal.

**Comment by weinand** [comment]
I've added a `restart` request to the protocol and a corresponding `supportsRestartRequest` capability.

@isidorn please adopt this by calling the restart request if supportsRestartRequest is true.

**Comment by weinand** [comment]
@roblourens please adopt this feature in the Debugger for Chrome.

**Comment by sandy081** [comment]
Verified by using Chrome debug extension for VS Code. Restarting refreshes VS Code

**Comment by sandy081** [comment]
I am not sure if above comment is the right way of verification, hence removing the verified tag. If you can let me know the right way I can verify it.

**Comment by weinand** [comment]
@roblourens did you surface this new feature in the 'Debugger for Chrome'?
If not it will be difficult to verify it.

**Comment by roblourens** [comment]
Yes, that's correct @sandy081
