### ISSUE TITLE
Once JSON language mode sees an error, it never lets go

### ISSUE THREAD

**Issue by kentquirk** [microsoft/vscode#141836]
Issue Type: <b>Bug</b>

I create `foo.json` with  these contents:
```json
{
    "title": "Tutorial 2",
    "ranks": [
        {
            "type": "Input",
            "id": "InputA"
        },
        {
            "type": "Input",
            "id": "InputB"
        }
    ]
}
```
I want to add a new "rank", so I type a comma after the curly brace that follows `InputB`. It's immediately highlighted as an error, the filename turns red. At that point, this file shows up in the IDE as having an error. If I then immediately delete the comma I just added, it's not fixed. Nor is it fixed if I add a new rank.

In fact, it seems that there's nothing I can do to fix it short of restarting the editor. From this point on, errors in JSON are just spurious noise; there's no real relationship to the state of the file. Saving the file doesn't help, formatting the file doesn't help, closing the file doesn't help. Renaming it DOES help, but if you then rename it back, the (wrong) errors reappear. The only things I've found are quitting and restarting all of VSCode, or (just discovered) "Developer: restart Extension Host". 

Expected result: when the JSON is correct and parseable, it should not show invalid errors in the file, and the filename in the explorer should not indicate errors.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.37GB free)|
|Process Argv|--crash-reporter-id 93eec905-f1b8-4d0c-91eb-e86f0cc2963c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
openscad|Ant|1.1.1
go|gol|0.31.0
vscode-go-template|jin|0.2.1
vscode-gist|ken|3.0.3
csharp|ms-|1.24.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.5
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
vsliveshare|ms-|1.0.5273
if-player|nat|0.3.0
inform-6|nat|0.5.0
inform-7|nat|1.2.0
tads3|N/A|0.0.1
graphviz-interactive-preview|tin|0.1.0
tmlanguage|Tog|0.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30428978
pythonvs932:30410667
vscop804cf:30404767
vs360cf:30404996
vsrem710:30416614

```

</details>

**Comment by aeschli** [comment]
I can't reproduce.

![Peek 2022-01-31 12-47](https://user-images.githubusercontent.com/6461412/151788614-c487a671-2206-45dd-9a37-a9f061018af6.gif)

Maybe the error comes from an extension? Does it reproduce with extensions disabled?

**Comment by kentquirk** [comment]
I apologize. I had an extension ("TextMate Languages") that was breaking it. I had forgotten I installed it.
