### ISSUE TITLE
Debugging closes immediately with no error

### ISSUE THREAD

**Issue by re-jim** [microsoft/vscode#141894]
Issue Type: <b>Bug</b>

Operating System: Pop!_OS 21.10                   
Kernel: Linux 5.15.15-76051515-generic

On a node.js project:

1. Press F5
2. The small window which contains the "step into, step over" buttons briefly appears, and disappears 
3. Nothing else happens.

My launch.json looks like this:

```{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Mocha Tests",
            "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
            "args": ["-u", "tdd", "--timeout", "999999", "--colors", "${workspaceFolder}/src/**/*spec.ts"],
            "internalConsoleOptions": "openOnSessionStart",
            "skipFiles": ["<node_internals>/**"]
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/dist/bin/www.js",
            "outFiles": ["${workspaceRoot}/dist/**/*.js"],
            "console": "integratedTerminal",
            "skipFiles": ["<node_internals>/**/*.js"]
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach by Process ID",
            "processId": "${command:PickProcess}",
            "protocol": "inspector"
        }
    ]
}
```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.15.15-76051515-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.07GB (0.31GB free)|
|Process Argv|--unity-launch --crash-reporter-id 3580ca5b-1b36-4d58-aeb6-7c3775a50e02|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sequence-diagrams|Ale|0.4.7
regex|chr|0.4.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.2.0
json-pretty-printer|eus|1.1.0
go|gol|0.31.0
vscode-docker|ms-|1.19.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.5
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
vscode-js-profile-flame|ms-|0.0.21
savebackup|pur|0.0.4
java|red|1.3.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.2
vscodeintellicode|Vis|1.2.16
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0
licenser|ymo|1.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30428978
pythonvs932:30410667
vscop804cf:30404767
vs360cf:30404996
vsrem710:30416614

```

</details>

**Comment by re-jim** [comment]
When I select Node.js... and then select a script from the package.json to run, like `Run Script start`, it works, but just "Launch Program" from the launch.json exits immediately. 
![image](https://user-images.githubusercontent.com/22106884/151880800-d9b81362-47b4-4243-9dc0-0ce441fc3c9f.png)

**Comment by re-jim** [comment]
[vscode-debugadapter-28557ad3.json.gz](https://github.com/microsoft/vscode/files/7974636/vscode-debugadapter-28557ad3.json.gz)

It says here that the reason is 

```"Can't find Node.js binary \"node\": path does not exist. Make sure Node.js is installed and in your PATH, or set the \"runtimeExecutable\" in your launch.json"``` 

When I type `node` into any terminal window, including vscode's terminal, it works. I can also run this node project normally.

Explicitly setting the "runtimeExecutable" allows the "Launch Program" configuration to work. 

So thanks, I at least found a workaround.

**Comment by connor4312** [comment]
Ah, yea. The lack of visible warning will be fixed in the release next week. Thanks for the issue!
