### ISSUE TITLE
Settings editor breaks after uninstalling extension

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#141895]
I uninstalled the deprecated RemoteHub extension, then tried to open the settings editor, but it was empty. I see this error in devtools:

```
 ERR Cannot read property 'displayName' of undefined: TypeError: Cannot read property 'displayName' of undefined
    at ot (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1682:5909)
    at async Promise.all (index 68)
    at async ci.onConfigUpdate (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1916:31353)
```

It seems like the settings from the extension are still there, but the extension service returns null here:

https://github.com/microsoft/vscode/blob/584d5348da59a02764b1731d9dc0b2c1c272e1e5/src/vs/workbench/contrib/preferences/browser/settingsTree.ts#L422

Maybe the issue is that the settings are not supposed to be returned by the config service anymore once the extension is uninstalled?

**Comment by sandy081** [comment]
> Maybe the issue is that the settings are not supposed to be returned by the config service anymore once the extension is uninstalled?

Depends, it is only if the extension is unloaded from the workbench after getting uninstalled. Otherwise the settings shall remain.

**Comment by rzhao271** [comment]
I couldn't repro the issue, but I changed around the code to handle the case where that variable is null.

**Comment by roblourens** [comment]
> Otherwise the settings shall remain

Sounds like there is a case where the extension settings will be there but the extension service will (probably) not return the extension. Your fix seems fine @rzhao271
