### ISSUE TITLE
Unattended connection to Microsoft while all telemetry off

### ISSUE THREAD

**Issue by locture** [microsoft/vscode#141845]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Debian 11

With all telemetry-related options turned off (including all online service settings) and all extension being disabled, vscode still establishes connection to a Microsoft-owned IP address 13.107.42.18 on a regular basis when being opened. This behavior is not being acknowledged to user, and currently no option is found available in vscode to opt the user out. 

Through tests, this connection is likely tied to the service of Microsoft Marketplace. While connecting to Marketplace is necessary and understandable when people go to extensions and/or make search via the Marketplace, it is totally unnecessary to establish connection and keep it on a regular basis while service not being used, and the connection should be only be established when user is PROACTIVELY using said service at real time. This unattended connection shall be removed, and an option shall be available for users to opt out from using the Marketplace service.

Although this connection hardly has any data exchange, it is still an unattended internet connection which requires action. When users choose to opt out from telemetry, not a single unnecessary connection shall be established, and the program is intended to be totally silent.

Thanks for your time and look forward to your replies.

Steps to Reproduce:

1. run code --disable-extensions with all telemetry-related settings off
2. netstat -tn or wireshark, monitor connection and internet usage

**Comment by sandy081** [comment]
Title seems to be misleading as this is nothing to do with the gallery. VS Code talks to Marketplace automatically for reasons likes checking updates and looking for recommendations. There are settings to disable these but there are still some other scenarios where VS Code reaches to Marketplace for querying for extensions. There is no user information shared to the Marketplace if the telemetry is off. 

Please let me know if you still want to disconnect from Marketplace.

**Comment by locture** [comment]
> 

Yes, as I have written, the connection to Marketplace is totally understandable when users PROACTIVELY use stuff related to it. It is only a problem when user is NOT using anything and vscode still shows connection to Marketplace while it is assumed to remain totally silent. It is meaningless (at least for my point of view) to have the program talk to Marketplace while the user has been doing the following:
1. disabled all extensions
2. disabled extension updates
3. disabled extension recommendations
4. disabled all telemetry-related option
5. is not using the extension option
The program itself is just setting up connections which seems not intentionally to be a telemetry behavior. However, the "request connection" itself is also having information out, which is undesirable while not being requested by user.

I have the knowledge that I can edit the product.json and remove the Marketplace urls or point them to something else. However, can anything be implemented into the program for disabling this connection behavior? I would assume it better to have an option like this.

**Comment by sandy081** [comment]
There is not such an option now to completely disable communicating with Marketplace and I also see no reason to do that. But I see your point.

**Comment by isidorn** [comment]
Good discussions in this issue, but no action items. Thus closing. Thank you
