### ISSUE TITLE
Two VS Code windows have the same terminal

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#141882]
I'm not 100% certain how I got into this state, but the terminal in question has several reconnect messages in it when I scroll up. 

These might be the steps that caused this:
1. Open one VS Code window and open a folder. This will be window/folder A.
2. Open a second VS Code window and open a different This will be window/folder B.
3. Do something that causes all VS Code windows to close in such a way that they'll be restored later. 
4. Open VS Code and see that your open folders are restored.
Window A has the expected terminal (cwd is folder A). 🐛 Window B's terminal has cwd of folder A. Run a command in that terminal, and see that the terminal output is the same between Windows A and B, so it seems they now share a terminal.

**Comment by Tyriar** [comment]
I suspect there's a race condition when windows launch and fetch the orphaned windows such that they get adopted by multiple windows.
