### ISSUE TITLE
Request: TextDocumentWillOpenEvent

### ISSUE THREAD

**Issue by idleberg** [Microsoft/vscode#14188]
- VSCode Version: 1.6.1 
- OS Version: macOS 10.12

Since Visual Studio Code will not open binary files (for good reasons, mostly), I was wondering if you'd consider adding something like`TextDocumentWillOpenEvent`, an event that fires before the file is opened. This would be useful for decoding a file so it *can* be opened.

**Comment by jrieken** [comment]
We have requests to allow plugging in custom file opener's. Closing this issue as duplicate of those

**Comment by idleberg** [comment]
It would have been helpful to reference the original request, as I can't find it

**Comment by jrieken** [comment]
> as I can't find it

You are not alone... We have the same search tools
