### ISSUE TITLE
Focus doesn't shift to the terminal unless once clicked

### ISSUE THREAD

**Issue by vishwakarmad1999** [microsoft/vscode#141835]
Issue Type: <b>Bug</b>

# Problem
When a fresh instance is opened of the VS Code Application and tried to switch between terminal(s) and current file using `cmd + j` or `cmd + ~`, the focus just doesn't shift to the terminal until I click over it. This didn't use to happen before, and I've started to observe this behavior after you introduced this **Last session logged in at (time)**.

# Steps to reproduce
- Open a fresh instance of VS Code.
- Press `cmd + ~` or `cmd + j` to switch between the current file and the terminal.
- Observe the current focus.

## Actual Result
The focus remains on the current file even after the terminal is opened.

## Expected Result
- The focus should switch accordingly between the terminal and current file tab.

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 7f19f082-a2b8-4a44-8666-bd863c084b19|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.0
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
prettier-vscode|esb|9.2.0
rest-client|hum|0.24.6
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.5
jupyter|ms-|2021.11.1001550889
cpptools|ms-|1.7.1
vetur|oct|0.35.0
laravel-blade|one|1.29.0
material-icon-theme|PKi|4.12.1
datetime|rid|2.1.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30429732
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30428979
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710:30416614

```

</details>

**Comment by gjsjohnmurray** [comment]
Does https://github.com/microsoft/vscode/issues/140336#issuecomment-1008158068 help?

**Comment by vishwakarmad1999** [comment]
The solution in the mentioned issue you told me is already there in **`settings.json`**, still, I need to click on the terminal to get things working fine.
**`"terminal.integrated.tabs.focusMode": "singleClick"`**, this is the one you are talking about, right?

**Comment by meganrogge** [comment]
Something that might help you is running the command `Toggle Keybinding troubleshooting`
/"needs-more-info"
