### ISSUE TITLE
Integrated Terminal crashes with Exit code: 1

### ISSUE THREAD

**Issue by Traxpoint** [Microsoft/vscode#14184]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: dcr30.lualinter-1.0.3, donjayamanne.python-0.5.0, fduman.vscode-nodemcu-1.0.5, formulahendry.terminal-0.0.5, keyring.Lua-0.0.8, ms-vscode.csharp-1.4.1, ms-vscode.PowerShell-0.7.2, robertohuertasm.vscode-icons-3.0.5

Steps to Reproduce:

1. Press Ctrl + ö in a german version of VS Code
2.

**Comment by roblourens** [comment]
Is there a keyboard shortcut for that combination?

**Comment by roblourens** [comment]
Can you show a screenshot or something of what this looks like? Does it still happen if you launch with `--disable-extensions`?

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by Traxpoint** [comment]
Tyriar is right, fixed in 1.7 of the insider build

**Comment by Tyriar** [comment]
FYI this is a duplicate of https://github.com/Microsoft/vscode/issues/7727
