### ISSUE TITLE
Delay before cursor is shown

### ISSUE THREAD

**Issue by aheckler** [microsoft/vscode#141825]
Issue Type: <b>Bug</b>

When I cold start VS Code or open a new window, there's a small delay (3-4 seconds) before the cursor is actually placed in the empty file. I can still type into the window before the cursor appears. Video below. This is with all extensions disabled.

https://user-images.githubusercontent.com/5512652/151697901-6f2c2b21-0908-4833-8f4a-c3e7720d5faa.mp4

Happy to send any other info y'all need. :)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:38:17.605Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.77GB free)|
|Process Argv|--crash-reporter-id 331bf7b4-ecc9-4f86-adfb-0f9b2c8108b7|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexdima** [comment]
@aheckler I have configured `"workbench.startupEditor": "newUntitledFile"` but I could not reproduce

https://user-images.githubusercontent.com/5047891/155681031-4b0320e3-4136-4707-8484-d2781d639e0b.mp4

I see the delay in your recording, but I can't tell if it is caused by the editor not getting focus or by the blinking animation not working well. Could you please try the following setting `"editor.cursorBlinking": "solid"` which would remove the doubts about blinking not working?

**Comment by aheckler** [comment]
Here's the same thing with the cursor set to solid.

https://user-images.githubusercontent.com/5512652/155691747-5a0a4e54-012d-458e-b3ff-e982f50d6f2b.mp4

**Comment by alexdima** [comment]
Thank you for trying that, so it looks like the editor gets focused a bit late. Could you please try the steps at https://github.com/microsoft/vscode/wiki/Performance-Issues#slow-startup to create startup profiles and post here the startup times you have?

**Comment by aheckler** [comment]
[prof-TPSk4Ffi.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/8140303/prof-TPSk4Ffi.extHost.cpuprofile.txt)
[prof-TPSk4Ffi.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/8140304/prof-TPSk4Ffi.main.cpuprofile.txt)
[prof-TPSk4Ffi.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/8140306/prof-TPSk4Ffi.renderer.cpuprofile.txt)

**Comment by alexdima** [comment]
According to the CPU profile, the editor was focused about 1s after the renderer process started and the editor was rendered quickly thereafter. This aligns with what I see on my machine. I cannot explain the delay you are observing 🤷 . Could you please also try [with our latest Insiders](https://code.visualstudio.com/insiders/) ?

<img width="670" alt="image" src="https://user-images.githubusercontent.com/5047891/155699146-5aa97be0-7bc0-41f4-99d5-d6e2f8668433.png">

**Comment by aheckler** [comment]
Works fine on the Insiders build. Video with `"editor.cursorBlinking": "solid"` and `"workbench.startupEditor": "newUntitledFile"`.

https://user-images.githubusercontent.com/5512652/155700309-d5215937-7f64-4b00-8d39-ec799c639936.mp4

After installing `code-insiders` to $PATH and running `code-insiders --prof-startup`:

[prof-bHxUiDZK.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/8140460/prof-bHxUiDZK.extHost.cpuprofile.txt)
[prof-bHxUiDZK.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/8140461/prof-bHxUiDZK.main.cpuprofile.txt)
[prof-bHxUiDZK.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/8140463/prof-bHxUiDZK.renderer.cpuprofile.txt)

Not sure if that helps at all. ¯\\_(ツ)_/¯

**Comment by alexdima** [comment]
Thank you, this helps. We will promote the Insiders build to Stable sometime next week, so I think that will resolve the problem. I am not sure what the exact problem was.

**Comment by aheckler** [comment]
I'll set a reminder to check after the release and see if this still happens. :)

**Comment by aheckler** [comment]
@alexdima This was indeed fixed in 1.65.0. :) Cheers!
