### ISSUE TITLE
{ in regex confuses indentation

### ISSUE THREAD

**Issue by thebinarysearchtree** [microsoft/vscode#141816]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: MacOS Monterey

Steps to Reproduce:

1. Create a JavaScript file.
2. Type `const r = /{/;`
3. Press enter.
4. The next line is indented because it doesn't realise the `{` is in a regular expression.

**Comment by IllusionMH** [comment]
Isn't it a syntax error? You should escape it if you want to match character or add closing curly brace.

**Comment by ArturoDent** [comment]
It looks like it is looking for a matching closing bracket.  

Indent: `const r = /{/;`  
Indent: `const r = /\{/;`

No Indent: `const r = /{}/;`  
No Indent: `const r = /\{\}/;`
