### ISSUE TITLE
Box lines around every element and some sort (may have be caused by color inversion on mac)

### ISSUE THREAD

**Issue by klueless-io** [microsoft/vscode#141853]
Issue Type: <b>Bug</b>

My VSCode has changed to look like this, **solid** lines are showing up around elements and also in the indentation level of code.

![image](https://user-images.githubusercontent.com/2956762/151733428-c68dee0d-db43-443a-ba36-a326c094add8.png)

![image](https://user-images.githubusercontent.com/2956762/151733822-ae02d188-11fe-4394-8dad-f2b006616b6f.png)

A couple of weeks ago, I attempted to disable `command+q` on the mac because I kept accidentally closing the app I was using.

The instructions I followed for that issue was found here [How to disable command-Q for Quit?](https://apple.stackexchange.com/a/205742)

This was all working ok for a couple of weeks, every now and then I press `command+q` and instead of quitting the application, my desktop colors would invert and so I would just press `command+q` again and my system would restore to normal colors.

Today this happened again, but it also screwed around with my VSCode as seen in the image above.

I have turned off the color inversion keyboard setting and I have rebooted the Mac, but the vscode issue has not resolved.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|32.00GB (10.69GB free)|
|Process Argv|--crash-reporter-id 5534e9ef-10e0-4b4d-848e-f05cde38340f|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vscode-erb-beautify|ali|0.3.5
vscode-tailwindcss|bra|0.7.6
vscode-postgres|cko|1.4.0
postcss|css|1.0.9
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.1.0
prettier-vscode|esb|9.2.0
auto-rename-tag|for|0.1.9
copilot|Git|1.7.4760
vscode-drawio|hed|1.6.4
vue-snippets|hol|1.0.4
vscode-edit-csv|jan|0.6.4
vue|jcb|0.1.5
vscode-hacker-typer|jev|0.1.1
volar|joh|0.31.1
vscode-csharp-snippets|jor|1.1.0
rainbow-csv|mec|2.0.0
vscode-docker|ms-|1.19.0
csharp|ms-|1.24.0
vscode-edge-devtools|ms-|1.4.2
data-workspace-vscode|ms-|0.1.1
mssql|ms-|1.12.0
sql-database-projects-vscode|ms-|0.14.1
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.5
jupyter|ms-|2021.11.1001550889
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
vsliveshare|ms-|1.0.5273
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
indent-rainbow|ode|8.2.2
live-preview|pro|0.0.3
quicktype|qui|12.0.46
vscode-thunder-client|ran|1.11.1
ruby|reb|0.28.1
vscode-yaml|red|1.3.0
LiveServer|rit|5.7.4
markdown-preview-enhanced|shd|0.6.1
mdx|sil|0.1.0
rbs-syntax|sou|0.1.0
code-spell-checker|str|2.1.4
pdf|tom|1.2.0
intellicode-api-usage-examples|Vis|0.0.9
vscodeintellicode|Vis|1.2.16
gitblame|wad|8.1.0
vscode-todo-highlight|way|1.0.5
vscode-ruby|win|0.28.0
fig|wit|0.0.6
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30429731
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30428979
pythonvs932:30410667
wslgetstartedc:30426334
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30416617

```

</details>

**Comment by joeljose350** [comment]
From your screenshots, it looks like the VS Code theme changed to `High Contrast`. You can change this by opening the `Command Palette` and searching for `Preferences: Color Theme`.

![image](https://user-images.githubusercontent.com/53969297/151737731-e66a0a7f-07e1-42dc-bc1f-f42e548e2afb.png)

**Comment by klueless-io** [comment]
> From your screenshots, it looks like the VS Code theme changed to `High Contrast`. You can change this by opening the Command Palette by pressing F1 or by clicking on View > Command Palette…, and searching for `Preferences: Color Theme`.
> 
> ![image](https://user-images.githubusercontent.com/53969297/151737731-e66a0a7f-07e1-42dc-bc1f-f42e548e2afb.png)

thanks that solved my issue
