### ISSUE TITLE
A11y_visualStudioCodeClient_Customizations and settings_Error Prevention: There is no confirmation message provided before deleting the shortcut key.

### ISSUE THREAD

**Issue by kupatkar99** [microsoft/vscode#141861]
### GitHubTags:
#A11yMAS; #A11yTCS; #A11ySev2; #DesktopApp; #Visual Studio Code Client; #BM-VisualStudioCode-Win32-Nov2021; #Win32; #error Prevention; WCAG3.3.4; #FTP; #STP; #AINotInScope;

### Environment Details:
Application Name: Visual Studio Code Client
Windows Version: Windows 11

### Repro Steps:
1.Open Visual studio code editor.
2.Naviagte to setting icon
3)Select "Keyboard shortcuts options"
4)Verify whether there is any confirmation message is for deleting shortcut or not.

### Actual Result:
There is no confirmation message provided before deleting the shortcut key.

### Expected Result:
There should be any confirmation message provided for deleting the key.

### User Impact:
User will not get any chance to validate the deletion action.

![A11y_visualStudioCodeClient_Customizations and settings_StatusMessages](https://user-images.githubusercontent.com/98530069/151758178-accd1342-78f6-4b30-bc16-66d2bd0f7325.gif)

**Comment by sandy081** [comment]
Assigning to @isidorn for validation
