### ISSUE TITLE
lag while writing code

### ISSUE THREAD

**Issue by devesh-bhushan** [microsoft/vscode#141802]
Issue Type: <b>Bug</b>

while writing code for the .js file .if you are writing a peice of code then writing continues and i am not able to see the code that i am writing after few seconds the code loads.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.86GB (6.73GB free)|
|Process Argv|E:\\WebDevelopment\\todolist --crash-reporter-id b6863295-e621-459f-8baa-b61b48937c0b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
doxdocgen|csc|1.3.2
es7-react-js-snippets|dsz|4.1.0
vscode-html-css|ecm|1.10.2
code-runner|for|0.11.6
better-cpp-syntax|jef|1.15.10
react-icons-snippets|jus|1.0.4
vscode-language-babel|mgm|0.0.35
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
vscode-xml|red|0.18.2
mongo-snippets-for-node-js|roe|1.3.12
cmake|twx|0.0.17
vscode-icons|vsc|11.8.0
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30428979
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710cf:30416617

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by devesh-bhushan** [comment]
![Screenshot 2022-02-02 191539](https://user-images.githubusercontent.com/65954731/152165770-777663c2-7ae5-4fc0-9a4e-ddde41d4c6b4.png)
while writing code in this file .I am writing the code but it's not getting displayed on the vs code editor .after few seconds it get typed

**Comment by IllusionMH** [comment]
Yeah, that's impression from initial report.

However
>Is it reproducible with all extensions disabled?

Is it during editing local files or remote (containers, ssh, etc.)?
