### ISSUE TITLE
MORE TIME IS TAKING TO CLONE FROM AZURE REPOSITORY BUT NOT CLONING

### ISSUE THREAD

**Issue by azuredeepika** [microsoft/vscode#141832]
Issue Type: <b>Performance Issue</b>

it is taking more time to clone from azure repository to visual studio but it is not cloning a lot of time is wasted i faced  a lot of time please correct the error in the visual studio

regards 
deepika 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.95GB free)|
|Process Argv|--open-url --crash-reporter-id 5b350417-bbc7-4093-ac3e-773a07266015 -- vscode://vscode.git/clone?url=https://b1503422026@dev.azure.com/b1503422026/WEBAPP/_git/WEBAPP|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   118	 10400	code main
    0	   135	  2364	   window (git-error-1643551640829 - Visual Studio Code)
    0	    39	  4280	   utility-network-service
    2	   143	  6088	   issue-reporter
    4	   122	 11756	   gpu-process
    0	    26	 13568	   crashpad-handler
    0	    93	 13708	   extensionHost
    0	   172	 14672	   shared-process
    0	    71	  8664	     ptyHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.34.3
vscode-docker|ms-|1.19.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614
vscop841cf:30429836

```

</details>

**Comment by azuredeepika** [comment]
![VSCloneissue](https://user-images.githubusercontent.com/97817617/151704191-f285a0a5-dfc5-4f4c-8c0c-b7127b57cdac.PNG)

**Comment by mediantiba** [comment]
Are you connecting via SSH or HTTPS? I've had a similar issue once and it turned out to be related to git and IPv6.

If you are on Windows and connecting via SSH, try the following:

1. In Powershell, go to your .ssh folder `cd ~\.ssh`
2. Create a new file and name it `ni config`
3. Open the file with a code editor `code .\config`
4. Add the following `AddressFamily inet` to the file, save it and close

Try now, this should configure git to use IPv4 and solve the problem.

**Comment by lszomoru** [comment]
@azuredeepika, could you please provide additional information on the issue that you are facing? Thank you!
