### ISSUE TITLE
 TypeError: Cannot read property 'getChildren' of undefined

### ISSUE THREAD

**Issue by SthuthiNakkina** [microsoft/vscode#141878]
Issue Type: <b>Performance Issue</b>

TypeError: Cannot read property 'getChildren' of undefined
Don't know why I'm encountering this error but whenever I'm starting to type lines except keywords on MySQL I'm getting this error

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 6.3.9600
Restricted Mode: No

<details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    63	  1000	code main
    0	    20	   256	   utility-network-service
    0	    65	   660	   shared-process
    0	    25	  2528	     watcherServiceParcelSharedProcess
    0	    26	  2568	     ptyHost
    0	     3	  3468	       winpty-process
    0	     5	   380	         console-window-host (Windows internal process)
    0	    19	  3264	         C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    11	  2520	   crashpad-handler
    0	    71	  3136	   window (undefined)
    0	   142	  3488	   window (create-db-template.sql - SQL - Visual Studio Code)
    0	    83	  3640	   gpu-process
    0	    68	  3832	   extensionHost
    0	    25	  5500	     "C:\Users\Sthuthi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Sthuthi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=3832
    0	    66	  4568	   window (undefined)
    0	    49	  5840	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (create-db-template.sql - SQL - Visual Studio Code)
|    Folder (SQL): 1 files
|      File types: sql(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
vscode-mysql-client2|cwe|4.5.6
vscode-mysql|for|0.4.1
live-html-previewer|hdg|0.3.0
better-cpp-syntax|jef|1.15.10
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.5
jupyter|ms-|2021.11.1001550889
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.63.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
LiveServer|rit|5.7.4
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30429732
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30428979
pythonvs932:30410667
wslgetstartedc:30426334
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30416617
vscop841cf:30430978

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Does it happens only in some specific file types or everywhere?

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by SthuthiNakkina** [comment]
> /needsMoreInfo
> 
> Does it happen only in some specific file types or everywhere?
> 
> Is it reproducible with all extensions disabled? You can try this with F1 and `>Developer: Reload Window With Extensions Disabled`

It is happening only in MySQL and only when I'm typing words 'otherthan' reserved keywords like 

1.show tables;
2.select * from info;
3.alter table info change column `old_name new_name datatype`  

In the third line of code starting from `old_name` it's showing the error for every letter I type like

2022-01-30 11:08:26 TypeError: Cannot read property 'getChildren' of undefined
2022-01-30 11:08:30 TypeError: Cannot read property 'getChildren' of undefined
2022-01-30 11:15:42 TypeError: Cannot read property 'getChildren' of undefined
2022-01-30 11:15:45 TypeError: Cannot read property 'getChildren' of undefined
