### ISSUE TITLE
CTRL + and CTRL 0 not working on my Windows 10 pc.

### ISSUE THREAD

**Issue by Archanciel** [microsoft/vscode#141838]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: Windows 10.o.19044

Steps to Reproduce:

1. CTRL - several time did reduce the app font size
2. CTRL + or CTRL 0 had no effect
![Snap0](https://user-images.githubusercontent.com/2625211/151709370-eaf035d3-781c-4a6f-a5e4-440bf80fee69.jpg)

**Comment by gjsjohnmurray** [comment]
Did you try them after running the command to reload with all extensions disabled?

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `Ctrl+=`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
