### ISSUE TITLE
Buffer untitled/text file model changed events and make the event type consistent

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14186]
From @bpasero in https://github.com/Microsoft/vscode/pull/14115#discussion_r84486381

> I see the need for an event when untitled or text files are changing so that the backup service can do its business, however I fear that this comes at the cost of spam: you will see many model content change events while the user is typing, so basically each key press will trigger this event. Performance should always be something to be concerned of, especially when it is typing performance we are talking about.
> 
> Some ideas:
> 
> buffer the model content change event and only start to emit the change after a certain delay
> do not always create an event object to send around
> I think buffering would be a good idea anyway because backups should also not be created without some delay.

From @bpasero  in https://github.com/Microsoft/vscode/pull/14115#discussion_r87146511

> @Tyriar I do not see a reason to create an object here each time a character is typed. the untitled event just sends around its resource URI and I would do the same thing here for files.
>
> Cannot say it often enough, this model content change event WILL FIRE like CRAZY. And perf is a hot topic after hot exit :)

**Comment by Tyriar** [comment]
From @bpasero in https://github.com/Microsoft/vscode/pull/14115#discussion_r87333050

> @Tyriar I was more thinking about the event in general: if the model content changes, the event should fire. Looking at the code it seems there are return statements before this event is fired and thus a listener would not get an event if the user e.g. undos to the point of the saved state. I would (for performance reasons) not like to introduce a real event with state here.

My comments below apply to both text and untitled file change events:

I'm thinking the best way forward is to change `onDidContentChange` to trigger on revert as well and be of type `Event<StateChange>` (either `REVERTED` or `CONTENT_CHANGE`). That will allow `BackupModelService` to react differently differently depending on what occurs.

Then move the 1 second timeout from `IBackupService.doBackup` to the `onDidContentChange` event. Any `CONTENT_CHANGE` event will be buffered by a second before it's fired. If a `REVERTED` event occurs, the buffered promises get canceled and the `REVERTED` event is fired immediately.

**Comment by bpasero** [comment]
Yes, +1 for adding the buffer logic to the place where the event is fired. Also +1 for sending this event whenever content changes, no matter how (revert, or typing).

**Comment by bpasero** [comment]
Also notice that now each time you type into the editor you call model.getValue() which converts all lines into a new string each time.

**Comment by Tyriar** [comment]
WIP branch https://github.com/Microsoft/vscode/tree/tyriar/hot_exit/14186
