### ISSUE TITLE
Compilation Result não apresenta nada

### ISSUE THREAD

**Issue by heitorwss** [microsoft/vscode#141889]
Issue Type: <b>Bug</b>

Realizo compilação me é questionado se gostaria de exibir o Compilation Result, confirmo porém não apresenta nada.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (5.03GB free)|
|Process Argv|--crash-reporter-id ffd10f11-1b60-407e-b4ac-f93ba71983c1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
githistory|don|0.6.19
gitlens|eam|11.7.0
vscode-language-pack-pt-BR|MS-|1.63.3
code-spell-checker|str|2.1.4
code-spell-checker-portuguese|str|0.1.10
tds-vscode|TOT|1.3.10
vscodeintellicode|Vis|1.2.16

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30428979
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710cf:30416617

```

</details>

**Comment by Tyriar** [comment]
What are you compiling and what does the dialog look like?
