### ISSUE TITLE
Faster Extension Loading

### ISSUE THREAD

**Issue by KuyaWayne** [microsoft/vscode#141821]
I have made VSCode into my daily driver when it comes to coding for my job, side projects, and as a light coding pass time. However, I began to notice VSCode taking too long to respond with all the extensions I need for my job and I can't uninstall anyone of the extensions I'm using because they're essential for my daily productivity and I got used to coding with them. Definitely not a bug because I know I have over 70+ extensions at the same time but it would be nice if it's somehow optimized. Thanks.

VSCode Version: 1.62.3
OS: Windows NT x64 10.0.19043
Extensions: 70

**Comment by sandy081** [comment]
> However, I began to notice VSCode taking too long to respond with all the extensions

Can you please be explain more about this? Please let us know where exactly you are seeing the slowness?

**Comment by KuyaWayne** [comment]
Right when VS Code starts

**Comment by jmg-duarte** [comment]
@KuyaWayne You can see which extension is taking more time in the extension bar.

Example:
<img width="416" alt="Screenshot 2022-02-08 at 22 18 53" src="https://user-images.githubusercontent.com/15343819/153085236-aa54a9b0-8978-4d30-ae61-35d17e687135.png">

**Comment by sandy081** [comment]
> Right when VS Code starts

That does not explain the slowness. Can you please show a video or gif showing us where is the slowness and what is it exactly?
