### ISSUE TITLE
My menubar is gone

### ISSUE THREAD

**Issue by Dora2601** [microsoft/vscode#141851]
Issue Type: <b>Bug</b>

My menubar in VS doesn`t show up and when I try to:  View-Appearance- show Menu Bar, there is no option for Show menu Bar like in the Windows Version that I have. I'm using MacBook Pro.
I have made Uninstall , but after the Reinstall it doesn`t make any deference. It comes exactly the same VSC.

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (11.01GB free)|
|Process Argv|--crash-reporter-id 6bd5afd9-afb1-4ff7-bc68-13e8e9682500 --crash-reporter-id 6bd5afd9-afb1-4ff7-bc68-13e8e9682500|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.7.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30429731
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710cf:30416617

```

</details>

**Comment by sbatten** [comment]
on macos the menubar is global, menubar visibility is not controllable on macos desktop vs code.
