### ISSUE TITLE
Portable workspace configuration

### ISSUE THREAD

**Issue by stfujnkk** [microsoft/vscode#141870]
Many plug-ins have conflicts, so I often have to disable them. 

My usual practice is to disable all plug-ins globally, and then enable the required plug-ins in the workspace. 

However, the workspace configuration file does not save information about disabling, so if I move the configuration file or share the configuration file, I have to enable the plug-ins one by one again.

I hope the `.code-workspace` file can store more information so that I can move or share it more easily.

**Comment by stfujnkk** [comment]
> /duplicate

Please tell me more specifically which question that this question repeats with

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/40239
