### ISSUE TITLE
Taking long time to clone but finally not succeding in cloning

### ISSUE THREAD

**Issue by azuredeepika** [microsoft/vscode#141874]
Issue Type: <b>Performance Issue</b>

Taking long time to clone but finally not succeding in cloning

Extension version: 0.34.3
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.09GB free)|
|Process Argv|--open-url --crash-reporter-id 5b350417-bbc7-4093-ac3e-773a07266015 -- vscode://vscode.git/clone?url=https://b1503422026@dev.azure.com/b1503422026/WEBAPP/_git/WEBAPP|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   124	 10400	code main
    0	   125	  2364	   window (Get Started - Visual Studio Code)
    0	    39	  4280	   utility-network-service
    0	   125	 11756	   gpu-process
    0	    25	 13568	   crashpad-handler
    0	    75	 13708	   extensionHost
    0	   159	 14672	   shared-process
    0	    65	  8664	     ptyHost
    0	   148	 19232	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614
vscop841cf:30429836

```

</details>

**Comment by lszomoru** [comment]
@azuredeepika, sorry for not getting back to you on this until now. The error message seems to indicate that the problem is related to authentication. Are you still able to reproduce the problem? Could you please check the version of `git` that you have installed by running `git --version`? Do you by any chance have any git credential managers installed?
