### ISSUE TITLE
Cannot use env.clipboard.writeText in Safari from web extension

### ISSUE THREAD

**Issue by lumaxis** [microsoft/vscode#141839]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:36:48.576Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15
- OS Version: macOS 12.2 (21D49)

I'm working on making my existing VS Code extension work in web environments like vscode.dev. My extension's main feature relies on the `env.clipboard.writeText()` API, triggered via a command or keyboard shortcut. That API seems to work fine in e.g. Chromium browsers but in Safari, it fails with:

<img width="886" alt="Screenshot 2022-01-30 at 19 42 34@2x" src="https://user-images.githubusercontent.com/406937/151712922-4e6bbb08-b5c7-42ff-a12c-d790f8d09d0a.png">

I've looked at #139657 but it sounds like that only fixes the built-in copy to clipboard feature. Is there a way for making the clipboard work from my extension?

**Comment by jrieken** [comment]
fixed in 1.64 via https://github.com/microsoft/vscode/pull/139657
