### ISSUE TITLE
Emmet/Co-pilot Key/Expansion Conflicts

### ISSUE THREAD

**Issue by napalm684** [microsoft/vscode#141803]
Would it be possible to give emmet preference inside HTML documents over copilot suggestions? The tab key being a conflict is kind of a pain. It slows me down working on HTML that I have to hit escape from copilot suggestions for the emmet tab expansion to complete as I intended. As you can imagine that gets repetitive.

**Comment by napalm684** [comment]
> See #127797.

Sure I saw that issue. It doesn't resolve the problem though. An extra keystroke in the Esc press every time you use emmet is just cumbersome.

I would much rather change my emmet shortcut if possible or be able to opt out of certain files for copilot.

**Comment by hediet** [comment]
Btw. you can disable copilot for certain files or file name patterns!

**Comment by napalm684** [comment]
> Btw. you can disable copilot for certain files or file name patterns!

Really? Any docs you can share?

**Comment by rzhao271** [comment]
> > Btw. you can disable copilot for certain files or file name patterns!
> 
> Really? Any docs you can share?

I only see a setting for opting out of certain languages, called `github.copilot.enable`.
I'm not sure whether it allows for opting out of certain files.

![A screenshot of github.copilot.enable being configured](https://user-images.githubusercontent.com/7199958/159945107-132ae517-9a61-4070-8bdf-a900cff784c7.PNG)

**Comment by napalm684** [comment]
I mean this would work for me. I could opt out in HTML where arguably copilot is probably of lesser value anyway.
