### ISSUE TITLE
VS Code crash

### ISSUE THREAD

**Issue by meganium** [Microsoft/vscode#14185]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: abusaidm.html-snippets-0.0.17, felixfbecker.php-debug-1.9.7, HvyIndustries.crane-0.2.1, lonefy.vscode-JS-CSS-HTML-formatter-0.2.1, Zignd.html-css-class-completion-1.0.3

Steps to Reproduce:

1. Open a folder (wamp64) for my.
2. VS Code crash
![image](https://cloud.githubusercontent.com/assets/8572485/19609803/8a9fe0aa-97d9-11e6-87e8-0695fac63c83.png)

![image](https://cloud.githubusercontent.com/assets/8572485/19609810/91d5a3dc-97d9-11e6-8cc1-736c8b9b0666.png)

**Comment by roblourens** [comment]
Only when you open that particular folder? What if you launch with `--disable-extensions`?

**Comment by meganium** [comment]
I uninstall the extensions and everything seems to work.
Good work. Thx

**Comment by roblourens** [comment]
It would be really helpful if you can figure out which extension it was and file an issue on them. Maybe 'php-debug'.

**Comment by roblourens** [comment]
In any case they shouldn't be able to cause a crash... reopening in case anyone has other ideas

**Comment by joaomoreno** [comment]
Let's close and keep an eye out.
