### ISSUE TITLE
Enter Key Randomly Stops Working Mid-File

### ISSUE THREAD

**Issue by bradtrue** [microsoft/vscode#141829]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by bradtrue** [comment]
Hello - I am exploring switching to vs code however as I'm getting started, the Enter key will randomly switch to not creating a new line and instead just navigate down the document. Here is a loom showing it. In this video I am hitting enter but it's not pushing the lines down the page. 

https://www.loom.com/share/f2beda7b48d14331b206fcb324c961ea

**Comment by alexdima** [comment]
It looks like you are using the vim extension, which takes over all input when it is installed and activated. Please report issue directly to the vim extension or open a new issue here if the problem reproduces after disabling it.

**Comment by bradtrue** [comment]
Excellent, thank you for the help!
