### ISSUE TITLE
LRU cache for search fields

### ISSUE THREAD

**Issue by Didier68** [microsoft/vscode#141881]
Is it possible to implement a LRU memory cache for to retrieve easily the N last strings used for an search, as well as in a file or in directories ?

**Comment by IllusionMH** [comment]
Could you please clarify use cases for this?

Find in Files has persistent history of searches that can be navigated with <kbd>Atl</kbd>+<kbd>↑</kbd>/<kbd>↓</kbd> (or just <kbd>↑</kbd>/<kbd>↓</kbd> if not multiline).

**Comment by Didier68** [comment]
Thanks !   I didn't know about this feature, and it's been a while since I despaired of having it.

**Comment by IllusionMH** [comment]
If you just looked for history - it's already there.
Also there is hint when field is empty and focused:
![image](https://user-images.githubusercontent.com/1312662/151834272-b57eca2d-aef9-4151-9c15-07d61342ac87.png)

There is existing request for UI improvements is #23099 which I recommend to upvote.

So unless there are something that differentiate this issue from #23099 I think it can be closed.

**Comment by Didier68** [comment]
I'm sorry, I've got all wrong: I never paid attention to that

**Comment by Didier68** [comment]
Already exists, but not seen before...

**Comment by IllusionMH** [comment]
No need to be sorry, this is not first request for this feature as it's hard to discover sometimes, but not something that can be easily implemented as dropdown at the moment.
