### ISSUE TITLE
Keyboard shortcuts for Search/Replace actions

### ISSUE THREAD

**Issue by andyj513** [microsoft/vscode#141840]
In an editor, I click Ctrl-F to bring up the Search Box.  I then click ">" to expand it to show the Replace section on the second line.  I can type text into the Search and Replace fields.

The top row has an Up Arrow and Down Arrow (in addition to other controls).  The second row has a Replace and a Replace All button.

If I hover the mouse over Replace, a tooltip says "Replace (Enter)" which I believe indicates that Enter is the keyboard shortcut for this action.  If I hover over the Down Arrow a tooltip says "Next Match (Enter)".

What I want is a way to pick Replace, or Next Match using the keyboard, but both seem to have the same key (Enter).  Also, the one that is picked when I press Enter seems to change based on the last one I clicked (it looks like there might be a "focus" on the last clicked button, with a square around it).

**Comment by ArturoDent** [comment]
The "Next Match (Enter)" command has this form:

```jsonc
{
  "key": "enter",
  "command": "editor.action.nextMatchFindAction",
  "when": "editorFocus && findInputFocussed"                  // note 'findInputFocussed'
}
```

The "Replace (Enter)" command has this form:

```jsonc
{
  "key": "enter",
  "command": "editor.action.replaceOne",
  "when": "editorFocus && findWidgetVisible && replaceInputFocussed"     // note 'replaceInputFocussed'
}
```

So they do have the same <kbd>Enter</kbd> keybinding but have different when clauses.  One with the `findInput` focused and one with the `replaceInput` focused requirement.

You will have to detail what you mean by "What I want is a way to pick Replace, or Next Match using the keyboard".  What is focused when you want to trigger "Replace" and what is focused when you want to trigger "Next Match"?

**Comment by roblourens** [comment]
Thanks @ArturoDent. Yes, these are the keybindings and you can customize them as you want. "Find next" also has the F3 keybinding. So you can have focus in the replace input and press Enter to replace and F3 to go to the next match, for example.

**Comment by andyj513** [comment]
@ArturoDent Since the tool tips are not so specific (to include the focus info), and I'm not sure where you got the info (but I trust that it is correct), why not list F3 as the keyboard shortcut for Find Next?  That would have saved me some trouble.

My scenario was that I have about 100 lines that matched my expression, but I only wanted to replace a subset of them (say, 50), and it was easier to view each one and manually decide if it should switch or not, than come up with a regular expression to limit the matches (if that would have even been possible for my criteria, which was based on context).  So I wanted to Find Next, view the highlighted text, and then manually decide if it should be switched or not, and move to the next match, etc.  Some of the matches I would want to replace, so I should press Enter, and for those I didn't want to replace, but move to the next match I should also press Enter (according to the tooltips).  I could do it with the mouse, but that requires looking away from the editor -- I wanted to have one keystroke to do Next and another to do Replace.  With your new info, I think I can now figure it out, but I still don't think a user who hadn't seen this discussion would know how.  For example, if I click the mouse button for Next Match to skip the first match, then pressing F3 and Enter both move to the Next Match without replacing it, and I have no keyboard shortcut to Replace.

But if the last button I click with the mouse was the Replace, then F3 moves to the next and Enter does a replace, as I want.  But my point is that ideally, it could be easier to figure this out without needing to go to the forum.  Thanks.
