### ISSUE TITLE
VSCode 1.63.2 does not follow LSP Specification of 3.16

### ISSUE THREAD

**Issue by tm1000** [microsoft/vscode#141893]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: Not Relevant
- OS Version: Not Relevant

The specification states: https://github.com/microsoft/language-server-protocol/blob/gh-pages/_specifications/specification-3-16.md#-diagnostic-

```js
export interface Diagnostic {
	...
	/**
	 * The diagnostic's code, which might appear in the user interface.
	 */
	code?: integer | string;
```

Yet VSCode itself does something entirely out of spec:
https://github.com/microsoft/vscode/blob/1.63.2/src/vscode-dts/vscode.d.ts#L5466

```js
	/**
	 * Represents a diagnostic, such as a compiler error or warning. Diagnostic objects
	 * are only valid in the scope of a file.
	 */
	export class Diagnostic {
		...
		/**
		 * A code or identifier for this diagnostic.
		 * Should be used for later processing, e.g. when providing {@link CodeActionContext code actions}.
		 */
		code?: string | number | {
			/**
			 * A code or identifier for this diagnostic.
			 * Should be used for later processing, e.g. when providing {@link CodeActionContext code actions}.
			 */
			value: string | number;

			/**
			 * A target URI to open with more information about the diagnostic error.
			 */
			target: Uri;
		};
```

Either VSCode should follow the specification or the specification should be adjusted to account for this

**Comment by IllusionMH** [comment]
According to https://github.com/microsoft/language-server-protocol/issues/926 it should be already in 3.16 spec.

**Comment by tm1000** [comment]
@IllusionMH thanks! I actually already reported it there https://github.com/microsoft/language-server-protocol/issues/1406

But they say VSCode can do whatever it wants, which is fine but it seems like from what you are saying and referencing that this should have been in the spec (but it's not).

**Comment by IllusionMH** [comment]
Replied in that thread why I think if should be already documented.

Also - reply from **rcjsuen** is correct. VS Code can extend it's implementation to support additional responses (`{value: string | number; target: Uri;}`) while still maintaining full support for servers that follow spec 1:1 and only will provide plain `code?: string | number;` - VS Code supports this as well.

> Either VSCode should follow the specification

I don't see problem where VS Code doesn't follow specification here - it still supports servers that implement LSP 3.16. And definitely doesn't look like a problem which is strong enough that VS Code would remove feature from editor.

**Comment by tm1000** [comment]
> that VS Code would remove feature from editor

I don't want that. I just wanted to know if VSCode should be using `DiagnosticRelatedInformation` which was created as a result of this anyways.

**Comment by tm1000** [comment]
It was pointed out to me that this was actually solved in the intermediate library!

https://github.com/microsoft/vscode-languageserver-node/blob/292dd0d88b6465337e42ba40ad986fdfdeb42d4d/client/src/common/protocolConverter.ts
