### ISSUE TITLE
A JavaScript error occurred in the main process while opening Visual Studio Code

### ISSUE THREAD

**Issue by renanlq** [microsoft/vscode#141999]
Does this issue occur when all extensions are disabled?: Unable to test, due to VSCode even open.

- VS Code Version: Latest
- OS Version: Windows 10 Enterprise (19042.1466) (Windows Feature Experience Pack 120.2212.3920.0)

Steps to Reproduce:
1. Try to open Visual Studio Code
2. 
![image](https://user-images.githubusercontent.com/15347353/152164117-6904becf-c543-4a83-aed2-ce33600a64ea.png)

I'm already uninstalled and started installing "x64-1.63.2" version due to the fact that I'm in the middle of some urgent work from our side.

**Comment by renanlq** [comment]
As a workaround I needed to uninstall and install again, but it is not the first time that happens.
I'm using the latest version now, downloaded from the VSCode site: x64-1.63.2, with no problem now.

**Comment by joaomoreno** [comment]
In order to prevent this from happening again, can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by renanlq** [comment]
Thanks, so that I'll be necessary to check periodically for the stable updates, right?
![image](https://user-images.githubusercontent.com/15347353/152434574-6e8bfef8-03a8-4e6b-8f34-27b98347e423.png)
