### ISSUE TITLE
Long clicking `Quick Fix` in Content Hover Widget engages the quick fix action closest to the mouse

### ISSUE THREAD

**Issue by SNDST00M** [microsoft/vscode#141958]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows 10 Home 21H2

Steps to Reproduce:

1. Insert the following code into your Maven WebDriver project:
```java
package pageobjects;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

public class OurWorkPage {

    public static WebElement universitiesParagraph(WebDriver driver) {
        return driver.findElement(By.cssSelector("#section_2 > div > div:first-child > p:first-of-type"));
    }

}
```
2. Hover over the errored WebElement.
3. Click on `Quick Fix(Ctrl+.)`.
3. It will apply the suggested fix that was hovered over if long clicked, instead of just showing the list of actions related to WebElement.

I'm rather sure this is a bug, because using the <kbd>Ctrl</kbd>+<kbd>.</kbd> doesn't apply one of the "quick fix" actions.

![image](https://user-images.githubusercontent.com/82655227/152009769-df812b93-af98-476c-9dc1-3ef46f96e74e.png)

**Comment by jrieken** [comment]
Is this with native or custom menus?

**Comment by SNDST00M** [comment]
I'm not familiar with this feature. The Quick Fix action is contributed here I believe:

https://github.com/redhat-developer/vscode-java/blob/v1.3.0/src/extension.ts#L258

**Comment by SNDST00M** [comment]
I'm trying to repro this with TypeScript, but the problem is that I can't think of a "Quick Fix" menu big enough for the mouse position to overlap the menu like that.

I also noticed that if the mouse is held down and moved over to the menu, it selects the first hovered action.

**Comment by SNDST00M** [comment]
It's the VSC one not the OS one.

**Comment by sbatten** [comment]
@alexdima @jrieken not sure the true owner here, but I believe this is where the quick fix menu is actually triggered

https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/editor/contrib/hover/browser/markerHoverParticipant.ts#L231-L234

The problem is that a position is provided,  not an anchor even though the element is being used to decide position and not the cursor position. The menu uses the position and provides a 2px buffer around it (i.e. it has no clue that the mouse is where it is.

Options:

1) Pass the cursor position instead to show the menu. this will make the menu appear next to the cursor instead of aligned with the element.
2) Pass the element position as well as height and width info. this should encompass the cursor position and the menu will avoid drawing over it.

**Comment by jrieken** [comment]
@sbatten I gave this to you because my understand is that the menu reacts to mouse up without the corresponding mouse down. Isn't that what's happening?

**Comment by sbatten** [comment]
@jrieken yes that is designed behavior though, allowing click > drag > release. the proper fix is to not draw the menu underneath the mouse cursor but proper information needs to be given to the menu to behave accordingly.

**Comment by alexdima** [comment]
While I have refactored and moved the code around a lot, the +6 math originally came in via https://github.com/microsoft/vscode/commit/267da0ad50f762d5aa0dc1b6e73778e7f17839a5#diff-af498d9d584c0d8b62514992e13810b69414f530502d9f353c491efc17f81f72R548-R549 @sandy081 . 

@sbatten I also find that the mouse handling of menus could be slightly improved. In this case the following happens: `mouse down > *menu gets created* > mouse up`. Menus could ignore mouse up events which were not preceded by a mouse down event on the menu itself.

**Comment by sbatten** [comment]
sorry @alexdima please see my comment above.. this behavior is as designed

**Comment by jrieken** [comment]
>  this behavior is as designed

Can explain that a little further? Does `mouse down > drag` somehow open/create a menu?

**Comment by sbatten** [comment]
![Recording 2022-02-03 at 09 34 04](https://user-images.githubusercontent.com/6561887/152397129-ed945687-20da-4fee-9f4b-3b6836053d8c.gif)

**Comment by sandy081** [comment]
I do not see this issue happening in Mac which has native hovers. May I know what is recommended action here?

**Comment by jrieken** [comment]
@sandy081 this is about custom menus. Looks like potential consumers of the custom menus need to be aware of its specialities.

**Comment by sbatten** [comment]
This is also native menu behavior on Windows which is what we are mimicking.

**Comment by sandy081** [comment]
@sbatten I can only pass the position. Can you please explain what width and height values to be passed here? It is not clear to me.
