### ISSUE TITLE
Can't set a breakpoint to my project installed in site packages even if justMyCode: false

### ISSUE THREAD

**Issue by ghuname** [microsoft/vscode#141906]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

- OS Version:
Windows 10 64bit

Steps to Reproduce:

1. Project 'B', launch.json has  "justMyCode": false
2. I developed a project 'A' and pushed it to local pypi. Now I am working on project 'B' that has as an prerequisite project 'A'. In project 'B's virtual environment I installed project 'A' with pip install 'A' (project 'A' is in 'B's site-packages). Now while debugging project 'B', I would like to step into project 'A' as well. I tried to set a breakpoint in project 'A' code (while I am in project 'B'), but I got gray dot with tooltip: "Breakpoint in file excluded by filters. Note: may be excluded because of "justMyCode" option (default == true). Try setting "justMyCode": false in the debug configuration(e.g. launch.json)."
As I have already set  "justMyCode": false in project's 'B' launch.json, why I can't set the breakpoint for project 'A'?

**Comment by weinand** [comment]
@ghuname You are talking about Python?

**Comment by ghuname** [comment]
Yes
