### ISSUE TITLE
Content of a file is not updated automatically when it is changed from docker container on MacOS

### ISSUE THREAD

**Issue by Noksa** [microsoft/vscode#141941]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version:
```
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
arm64
```
- OS Version: MacOS Monterey 12.2

Steps to Reproduce:

1. Install `Docker-Desktop`
2. Run the following command:
```
docker run --rm -ti alpine:3.15 sh -c "while true; do echo -e "TEST" && sleep 1; done" &> tmp.txt
```
3. Open a folder that contains `tmp.txt` file
4. Open the `tmp.txt` file in editor.
5. You will see something like that:
<img width="698" alt="image" src="https://user-images.githubusercontent.com/36312857/151979458-47d65eb1-6658-4642-b5cd-60624102c1fb.png">

6. Wait a bit. You will see that the content is not changed automatically.
7. Use `Alt-Tab` to switch to any other opened application.
8. Use `Alt-Tab` to switch back to `VSCode`
9. You will see something like that:
<img width="634" alt="image" src="https://user-images.githubusercontent.com/36312857/151979664-0887d0d3-3b72-416a-8ba6-a730a3203fde.png">

Is there any workaround to make it works? I mean I want to see live changes without alt-tabs when I use redirecting to a file.

This case will work as expected (without redirecting but with volume bind):
```
touch tmp.txt
docker run --rm -ti -v $(pwd)/tmp.txt:/tmp/file.txt alpine:3.15 sh -c "while true; do echo -e "TEST" >> /tmp/file.txt && sleep 1; done"
```

At the same time both cases work perfect on Linux.

Thanks!

**Comment by bpasero** [comment]
How is docker mapping the paths back into macOS? We typically do not guarantee file events work through exotic setups. We only support file events when the files are on the disk where VSCode runs or via our remote server.

**Comment by Noksa** [comment]
@bpasero 
I use the default settings for docker-desktop:
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/36312857/151998731-266aee40-29d6-4756-a94b-7601935ee869.png">

And I share with docker VM only one directory:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/36312857/151998819-bc329b88-dc76-4a26-bf0f-1fb8523a39ad.png">

**Comment by Noksa** [comment]
@bpasero 
Is there any change that you implement file watching for such scenario in future?
