### ISSUE TITLE
Remove .eslintignore workarounds

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#141994]
With https://github.com/microsoft/vscode/commit/7ccb8688351c111345fb928b3dacec10e77fe51a we aligned what's ignore wrt eslint in the editor and the CLI build (`yarn eslint`). Turns out that we are blind on a few spots, meaning we have JS/TS code that we other but that's not under eslint's regime. They are listed here and each respective owner should tackle them

https://github.com/microsoft/vscode/blob/7ccb8688351c111345fb928b3dacec10e77fe51a/.eslintignore#L28-L32

**Comment by jrieken** [comment]
@JacksonKearl for `generateTMLanguage`
@joao for `build/` (I assume?)

**Comment by alexdima** [comment]
I got started and noticed there weren't that many problems and they looked simple enough.

**Comment by joaomoreno** [comment]
![mvp](https://media.giphy.com/media/ALQnCUBuggPxS/giphy.gif)
