### ISSUE TITLE
Search doesn't work in text outputs

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode#141967]
## Environment data

-   VS Code version: 1.64.0-insider (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2022.1.1001760686
-   Python Extension version (available under the Extensions sidebar): v2022.0.1762517795-dev
-   OS (Windows | Mac | Linux distro) and version: Windows (WSL2)
-   Python and/or Anaconda version: conda 4.11.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

1. Run print("hello") in a cell
2. Search "hello"
2. Click filter dropdown, and check everything (including rendered markdown and code cell outputs)
3. Expect the search to find in two places (one in the input and the other in output)

## Actual behaviour

Search doesn't find the search term in the text output

**Comment by greazer** [comment]
Seems like this is important enough to make sure that it's addressed in the next release.
