### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by AquibAmin** [microsoft/vscode#141945]
We have written the needed da
Issue Type: <b>Performance Issue</b>

The terminal is not working. It does not allow me to type anything on the terminal or run my programs on the terminal.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 6.2.9200
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (1.91GB free)|
|Process Argv|--crash-reporter-id 6894a386-3d02-40e9-aa32-8e61a3063bc2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   121	 12508	code main
    0	   162	 13400	   extensionHost
    0	     7	  9344	     C:\Windows\system32\cmd.exe /d /s /c "python -u "c:\Users\Aqib\Downloads\python\Hello World\app.py""
    0	    13	 28184	       python  -u "c:\Users\Aqib\Downloads\python\Hello World\app.py"
    0	    11	 28524	       console-window-host (Windows internal process)
    0	   103	 12896	     "C:\Users\Aqib\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Aqib\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=13400
    0	   102	 16156	     "C:\Users\Aqib\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Aqib\.vscode\extensions\streetsidesoftware.code-spell-checker-2.1.4\packages\_server\dist\main.js --node-ipc --clientProcessId=13400
    0	   242	 24544	     "C:\Users\Aqib\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Aqib\.vscode\extensions\ms-python.vscode-pylance-2022.1.5\dist\server.bundle.js --cancellationReceive=file:97cfb60940039896ca29bfb38a20aad4f68fb0a5b1 --node-ipc --clientProcessId=13400
    0	    69	 29316	     "C:\Users\Aqib\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Aqib\.vscode\extensions\tht13.python-0.2.3\node_modules\vscode-languageclient\lib\utils\electronForkStart c:\Users\Aqib\.vscode\extensions\tht13.python-0.2.3\out\server\src\server.js
    0	    27	 17120	   crashpad-handler
    0	   205	 19980	   window (app.py - python - Visual Studio Code)
    0	    92	 20176	   issue-reporter
    0	   112	 24696	   shared-process
    0	    82	 17624	     ptyHost
    0	    21	 12480	       winpty-process
    0	   110	 19284	         "C:\Program Files\PowerShell\7\pwsh.exe"
    0	    10	 29368	         console-window-host (Windows internal process)
    0	    21	 17116	       winpty-process
    0	    11	 11476	         console-window-host (Windows internal process)
    0	   110	 18100	         "C:\Program Files\PowerShell\7\pwsh.exe"
    0	    19	 22764	       winpty-process
    0	    11	 11088	         console-window-host (Windows internal process)
    0	   109	 12468	         "C:\Program Files\PowerShell\7\pwsh.exe"
    0	    21	 26784	       winpty-process
    0	   114	  3660	         "C:\Program Files\PowerShell\7\pwsh.exe"
    0	    11	 23644	         console-window-host (Windows internal process)
    0	    76	 30404	     watcherServiceParcelSharedProcess
    0	   266	 24948	   gpu-process
    0	    46	 27520	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (app.py - python - Visual Studio Code)
|    Folder (python): 5 files
|      File types: json(2) py(1)
|      Conf files: settings.json(1) tasks.json(1);
```

</details>
<details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
terminal-commands|adr|1.0.5
Bookmarks|ale|13.2.2
vscode-django|bat|1.8.0
vscode-markdownlint|Dav|0.46.0
py-pack|dav|1.2.0
python-preview|don|0.0.4
githistory|don|0.6.19
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
gitlens|eam|11.7.0
linter|fna|0.0.11
code-runner|for|0.11.6
terminal|for|0.0.10
vscode-test-explorer|hbe|2.21.1
python-coding-conventions|igr|0.0.4
vscode-graphviz|joa|0.0.6
vsc-python-indent|Kev|1.14.2
vscode-python-test-adapter|lit|0.7.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.6-pre.1
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
test-adapter-converter|ms-|0.1.5
autodocstring|njp|0.5.4
trailing-spaces|sha|0.3.1
dot|Ste|0.0.1
code-spell-checker|str|2.1.4
python|tht|0.2.3
vscodeintellicode|Vis|1.2.16
jinja|who|0.0.8
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710cf:30416617
vscop841cf:30430978

```

</details>

ta into your clipboard because it was too large to send. Please paste.

**Comment by Satvik-web** [comment]
Try clicking on the Terminal > New Terminal in the menu bar. which will open up a new terminal at the current working directory..

If the terminal doesn't work, you can always open up cmd and get into your working directory using the following command..
```
cd /path/to/dir
```
