### ISSUE TITLE
SyntaxError: Unexpected token '...'

### ISSUE THREAD

**Issue by XtremePlayzCODE** [Microsoft/vscode#14192]
- VSCode Version: Straight from master
- OS Version: Windows 10

Steps to Reproduce:

1. git clone http://github.com/Microsoft/vscode
2. cd vscode
3. gulp (unless you don't have gulp installed, npm install -g gulp is 3rd and this is 4th)

**Comment by roblourens** [comment]
Did you run `./scripts/npm install`?

**Comment by XtremePlayzCODE** [comment]
Yes, I got a ton of errors

**Comment by XtremePlayzCODE** [comment]
I'll make a log

**Comment by roblourens** [comment]
Many people were having issues with npm today because of a DNS issue.

**Comment by XtremePlayzCODE** [comment]
Yes, GitHub was down today.

**Comment by roblourens** [comment]
Maybe try deleting node_modules to ensure you don't have something corrupted, or just try a little later

**Comment by XtremePlayzCODE** [comment]
[log.txt](https://github.com/Microsoft/vscode/files/545399/log.txt)

**Comment by roblourens** [comment]
Actually it just looks like it has an issue with your python version `gyp ERR! stack Error: Python executable "C:\python\python.EXE" is v3.6.0a3, which is not supported by gyp.`. Apparently it requires python 2

**Comment by XtremePlayzCODE** [comment]
I have python 2 installed, is there a way I can switch that

**Comment by XtremePlayzCODE** [comment]
Wait nevermind

**Comment by XtremePlayzCODE** [comment]
Well it's worth an uninstall. 99% of Python projects are 2.0

**Comment by XtremePlayzCODE** [comment]
[log.txt](https://github.com/Microsoft/vscode/files/545490/log.txt)
Somehow, this happened

**Comment by XtremePlayzCODE** [comment]
Apparently, I think, msbuild failed
