### ISSUE TITLE
Lamp icon is not clickable at the first hover

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#14194]
- VSCode Version: 1.7.0-insider
- OS Version: macOS Sierra (10.12)

In the new insiders when these lamp icons appears the first time that you hover on them they disappear for the break point to be placed and in the second time you try to click on them they let you do so. This is a bit too not user-friendly:

![icon](https://cloud.githubusercontent.com/assets/2157285/19615092/e266d450-9807-11e6-8fa8-0618d92a2f2f.gif)

**Comment by pmkary** [comment]
In the very latest nightly I can see this problem is fixed. So this issue is fixed. @alexandrudima  thanks a lot for investigating and fixing 👍

**Comment by alexandrudima** [comment]
@pmkary I didn't do any change in this area. It was probably @jrieken

**Comment by jrieken** [comment]
yeah - that was https://github.com/Microsoft/vscode/issues/14140

**Comment by pmkary** [comment]
Ah @jrieken! good to see you again! Thanks a lot, I really needed the thing 👍 👍

**Comment by pmkary** [comment]
By the way @alexandrudima I was watching your talk just past week and it was super cool! Hoping to see more talks from you...
