### ISSUE TITLE
Unable to downgrade an extension to a previous Pre-Release version with VS Code Insiders

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#141910]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:Version: 1.64.0-insider (user setup)
Commit: a853936292178200eb58c2a9904d7a7dcf98cce8
Date: 2022-01-30T20:09:01.122Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Try to install version 1.8.0 (pre-release) or 1.8.1 (pre-release) of the C/C++ extension using VS Code (possible) versus VS Code Insiders (not possible).

FYI, we have 1.8.2 (non-pre release) and 1.8.3 (pre-release) released.

**Comment by isidorn** [comment]
Before I was getting this dialog

After the fix I can nicely install -> verified

![Screenshot 2022-02-01 at 13 16 50](https://user-images.githubusercontent.com/1926584/151966966-99ff32b4-ff8b-46c2-9b91-c49bad71c61a.png)

**Comment by lramos15** [comment]
Closing as it appears to have been merged into release branch and verified
