### ISSUE TITLE
when chinese in the file path, openning the integrated console error

### ISSUE THREAD

**Issue by julianhu1979** [Microsoft/vscode#14196]
- VSCode Version: 1.6.1
- OS Version: windows 10

Steps to Reproduce:

1.  open a folder, there is chinese in the folder path
2. open the integraded console, the system alert a error message.

**Comment by roblourens** [comment]
I don't see an error when I open a folder with a chinese character. What is the error? Can you share a screenshot?

**Comment by zhanggy** [comment]
1. open a folder, "c:\中文"
2. Ctrl+` open the integraded terminal

<img width="758" alt="untitled" src="https://cloud.githubusercontent.com/assets/4606273/19616374/a41fc1ac-9843-11e6-8733-e69f51c2c0fd.png">

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/7727
