### ISSUE TITLE
integrated terminal inconsistent single quote response

### ISSUE THREAD

**Issue by cbeebe44** [Microsoft/vscode#14198]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: donjayamanne.python-0.5.0

Steps to Reproduce:
1. open docked terminal console
2. press the single quote key

**Comment by roblourens** [comment]
What's the problem, it doesn't show up? Are you using an international keyboard layout?
