### ISSUE TITLE
Formatting of copied code is not correct

### ISSUE THREAD

**Issue by Frank-Merfort** [microsoft/vscode#141984]
Issue Type: <b>Bug</b>

Copy a javascript function with documentation from one file to another, for example
```javascript
    /**
     * Füllt die Tabelle mit den vorhandenen Daten. Der Inhalt der Tabelle ist vorher gelöscht worden.
     * @param {jquery}  $tableBody  jQuery-Objekt des tbody-Elementes
     * @param {array}   data        Array mit den Daten, die angezeigt werden sollen
     */
    fillTable($tableBody, data) {
        for (var i = 0; i < data.length; i++) {
            $tableBody.append(this.getTableRowHTML(data[i]));
        }
    }
```
The copied code has an extra space before fillTable (5 and not 4):
```javascript
    /**
     * Füllt die Tabelle mit den vorhandenen Daten. Der Inhalt der Tabelle ist vorher gelöscht worden.
     * @param {jquery}  $tableBody  jQuery-Objekt des tbody-Elementes
     * @param {array}   data        Array mit den Daten, die angezeigt werden sollen
     */
     fillTable($tableBody, data) {
        for (var i = 0; i < data.length; i++) {
            $tableBody.append(this.getTableRowHTML(data[i]));
        }
    }
```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.69GB free)|
|Process Argv|--crash-reporter-id 55d9546a-7bc8-45d7-b6d3-9f505a422325|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
vscode-intelephense-client|bme|1.8.0
vscode-mysql-client2|cwe|4.5.6
vscode-eslint|dba|2.2.2
todo-tree|Gru|0.0.215
vscode-edit-csv|jan|0.6.4
php-cs-fixer|jun|0.2.10
php-debug|xde|1.23.0

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate

The open PR #136579 is supposed to fix this.
