### ISSUE TITLE
Towards disallowing importing `workbench/api/~` in `workbench/contrib/~`

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#141921]
We currently have 119 imports from `workbench/api/~` to `workbench/contrib/~` and 17 in the other direction. We would like to remove this tangle and in the future prohibit importing `workbench/api/~` in `workbench/contrib/~`. This can be done locally by commenting out [this line](https://github.com/microsoft/vscode/blob/7a5b86a75784ad2f9170c1ae60877082d01b6574/.eslintrc.json#L342) and running `yarn eslint`.

Most of these imports can be removed by just moving the imported types from `/api` to `/contrib/`.

- [x] [commentService.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/comments/browser/commentService.ts#L14) @rebornix
- [x] [debugConfigurationManager.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/debug/browser/debugConfigurationManager.ts#L37) @roblourens
- [x] [debug.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/debug/common/debug.ts#L24) @roblourens
- [x] [terminals.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/debug/node/terminals.ts#L11) @roblourens
- [x] [editorStatusBar.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/notebook/browser/contrib/editorStatusBar/editorStatusBar.ts#L21) @rebornix
- [x] [notebookServiceImpl.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/notebook/browser/notebookServiceImpl.ts#L26) @rebornix
- [x] [backLayerWebView.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L34) @rebornix
- [x] [notebookService.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/notebook/common/notebookService.ts#L9) @rebornix
- [x] [testingExplorerFilter.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/testing/browser/testingExplorerFilter.ts#L20) @connor4312
- [x] [testingProgressUiService.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/testing/browser/testingProgressUiService.ts#L13) @connor4312
- [x] [ownedTestCollection.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/testing/common/ownedTestCollection.ts#L11) @connor4312
- [x] [ownedTestCollection.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/testing/common/ownedTestCollection.ts#L12) @connor4312
- [x] [testCollection.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/testing/common/testCollection.ts#L11) @connor4312
- [x] [testExplorerFilterState.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/testing/common/testExplorerFilterState.ts#L8) @connor4312
- [x] [testStubs.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/testing/test/common/testStubs.ts#L11) @connor4312
- [x] [testStubs.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/testing/test/common/testStubs.ts#L12) @connor4312
- [x] [testStubs.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/testing/test/common/testStubs.ts#L7) @connor4312
- [x] [webviewElement.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/webview/browser/webviewElement.ts#L33) @mjbvz
- [x] [gettingStarted.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.ts#L59) @JacksonKearl
- [x] [contribution.ts](https://github.com/microsoft/vscode/blob/d069da1aad559546d786ca0b2aed872c0d7813a3/src/vs/workbench/contrib/workspace/browser/workspace.contribution.ts#L20) @bpasero

> ![image](https://user-images.githubusercontent.com/5047891/151935313-a2d3a973-8ed7-4194-8128-59070fc1fb1c.png)

**Comment by bpasero** [comment]
👏 , my usage was really not good, nice catch.

**Comment by mjbvz** [comment]
Moved mine up to `webview/common` instead

**Comment by roblourens** [comment]
Fixed mine, all simple, thanks!

**Comment by rebornix** [comment]
Thanks for pointing this out, removed the references to api in notebook and comments.

**Comment by connor4312** [comment]
Is it safe to allow importing types from `vscode` in code outside the `/api`? This is the main reason testing has so much code in `/api` and imported elsewhere -- that's the only way I could avoid having to copy-paste interfaces, which could be confusing and dangerous in case they get desynchronized.

**Comment by alexdima** [comment]
cc @jrieken for guidance. Here's some of the things I keep in mind when dealing with the API:
* our system is built such that the workbench can function without `/workbench/api`. 
* so it should not be necessary to import `/workbench/api` to implement workbench services or workbench contributions.
* so far, we have done all type conversions between API types and workbench types on the extension host process.

**Comment by connor4312** [comment]
The main reason vscode is transitively is used is to implement the 'test collection', which consumes vscode.TestItem's and then generates "diff"s that are sent to the main thread. I reuse this test collection in tests for workbench contributions to build these diffs I can test against (`ownedTestCollection.ts` -> `extHostTestingPrivateApi.ts`). Short of rewriting that into some big generic thing, the alternative is manually writing/copying the diffs and reducing the scope of the tests, though that greatly increases verbosity and reduces scope.

**Comment by jrieken** [comment]
The rule is that the renderer is completely isolated from the extension host, e.g everything can work without it. That means the workbench/editor define API as if there would be no extension host and it is the extension host logic (mainThreadXYZ/extHostExt-files) that does the conversion. The trivial sample is `IRange`  (defined by the editor) and `vscode.Range`  (defined by the API). We exclusively use `IRange` in the renderer and we exclusively use `vscode.Range`  for extensions, also there is explicit conversion between them (usually implemented in `extHostTypeConverter.ts`). A more complex sample is the diagnostics API for extensions and the marker service in the renderer. Making explicit, untangled API for these was natural because they predate the API and extension host. I do see how new features like test don't have this strict separation in their DNA (but they should). 

I am no expert in the details and implementation of testing but it might mean that you need a generic `TestItemCollection<T>` for code-reuse and so that API doesn't bleed into the renderer. Or have an entirely different implementation for the API - which initially sounds bad but often is the over-looked champ of API-stability (because changing an internal domain model has no impact on the API itself)
