### ISSUE TITLE
comment line short cut bug

### ISSUE THREAD

**Issue by baofengyv** [Microsoft/vscode#14199]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 15.6.0
- Extensions: Zignd.html-css-class-completion-1.0.3, abusaidm.html-snippets-0.0.17, donjayamanne.githistory-0.1.0, xabikos.JavaScriptSnippets-1.2.0

Steps to Reproduce:

1.
![2016-10-22 1 08 38](https://cloud.githubusercontent.com/assets/5669938/19617087/288bbecc-9859-11e6-97ad-c1af7bc6931f.png)

2.
![2016-10-22 1 08 45](https://cloud.githubusercontent.com/assets/5669938/19617089/2b537442-9859-11e6-8012-66f3f48a018a.png)

**Comment by roblourens** [comment]
Yes this is #11081
