### ISSUE TITLE
Git extension pulls up quickpicks instead of web interface for auth

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#141901]
On Insiders on Windows:

1. Have both the built-in Git and GHPRI extensions enabled (I wasn't able to repro the issue with just the Git extension).
2. Navigate to a folder with a git repository. The folder I navigate to has a PR already checked out.
3. :bug: Get asked to log in, even though in the Accounts section, I'm already authenticated.
4. Press cancel.
5. :bug: Two quickpicks asking for my username and password show up.

Logs:

```
[2022-01-26T20:53:07.220Z] > git fetch origin test-image [111633ms]
[2022-01-26T20:53:07.220Z] remote: Repository not found.
fatal: Authentication failed for 'https://github.com/rzhao271/testworkspace3.git/'
```

![gitlogin](https://user-images.githubusercontent.com/7199958/151245060-fc7544ee-0e92-4705-8ebd-77655e1e71b8.PNG)
![gitlogin2](https://user-images.githubusercontent.com/7199958/151245057-46ce3613-9f44-46f3-9e9b-27cc61761029.png)

**Comment by TylerLeonhardt** [comment]
The Git extension doesn't use the GitHub auth provider at all and only uses real Git commands. The GitHub extension is different and that _does_ use GitHub auth...

this might be working "as expected" but maybe there's some UX improvements we can do

**Comment by TylerLeonhardt** [comment]
I'm just now reading through this issue again and:

1. I don't see why you call out bug number 2 when you cancelled the auth flow that would have taken you to the browser. The username/password prompts are likely a fallback when the Git/GitHub extension fails to get auth from the GitHub Auth extension
2. bug number 1 should be addressed now with the alignment of scopes with the GitHub and GHPR extensions (so you shouldn't be asked for auth a second time)

Can you give this another go @rzhao271 and let us know what works and what doesn't again?

**Comment by rzhao271** [comment]
Just read over my original posting.
I don't think it's relevant anymore&mdash;the auth and GHPRI experience are both much better now 🎊
