### ISSUE TITLE
Multicursor intellisense only shows up on the first instance

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14195]
Have some code like

```javascript
let a = "";
a.


a.
```

Except imagine that the two `a`s are more than a page apart. From the first one, use cmd+d to add a second cursor to the second. It scrolls to bring the second in view. Now if you press ctrl+space, you get the intellisense popup on the first one, which is off screen, so you don't see it.

**Comment by alexandrudima** [comment]
@jrieken You can reveal the primary position of the editor when intellisense is requested.
