### ISSUE TITLE
Path jump in explorer after deleting files

### ISSUE THREAD

**Issue by frankNiessen** [microsoft/vscode#141949]
Issue Type: <b>Bug</b>

Hi, 

If I have an open folder in the explorer, mark a few files and delete them, VScode will jump into the last folder in that path. The result is that if I continue deleting files, I am now in a different path. This is quite annoying and should be easy to fix, so that the path is not changed when deleting files.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.0-1057-oem
Remote OS version: Linux x64 3.10.0-1160.53.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (16.72GB free)|
|Process Argv|--crash-reporter-id 1e3baf60-bebb-49cf-b790-ce189e6973e0|
|Screen Reader|no|
|VM|33%|

|Item|Value|
|---|---|
|Remote|SSH: MEK-425-026-01|
|OS|Linux x64 5.10.0-1057-oem|
|CPUs|Intel(R) Core(TM) i9-10920X CPU @ 3.50GHz (24 x 1200)|
|Memory (System)|125.61GB (84.49GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Niflheim_svol|
|OS|Linux x64 3.10.0-1160.53.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (80 x 999)|
|Memory (System)|754.19GB (1.50GB free)|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30429731
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30428978
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30416617

```

</details>

**Comment by ArturoDent** [comment]
Could this be related to the `Explorer: Auto Reveal` setting?  Disable that and see if you get the behaviour you want.  With it enable the Explorer will highlight and reveal whatever file tab is to the right of the one you deleted.

**Comment by JacksonKearl** [comment]
Could you include a recording of what you're seeing? There are two behaviors I know of here, based on whether or not there are editors opened. If by deleting one file you cause a different editor to appear, then as @ArturoDent mentioned the auto reveal setting will cause that file to be focused in the explorer

![Recording 2022-02-01 at 10 56 24](https://user-images.githubusercontent.com/8586769/152032797-790e0fb8-f832-4ee7-939c-abb897caf1fc.gif)
.

**Comment by frankNiessen** [comment]
Thank you for the quick and precise support, it was indeed the auto-reveal feature, which I have now deactivated.

**Comment by frankNiessen** [comment]
The issue was fixed by deactivating the auto-reveal option.
