### ISSUE TITLE
Taking a lot of time to execute in terminal

### ISSUE THREAD

**Issue by candy-kush** [microsoft/vscode#141962]
We have written the needed data into your clipboard because it was too large to s
Issue Type: <b>Performance Issue</b>

When I run my C/C++ or any other code in terminal then it is taking a lot of time to execute. This problem is arising in any type of code, whether it is to print "Hello World" or any other code snippet.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.74GB (2.22GB free)|
|Process Argv|--crash-reporter-id 27f3ae45-efa3-4c6a-a4bc-0c379c7101fd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
code-runner|for|0.11.6
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.5
jupyter|ms-|2021.11.1001550889
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
java|red|1.3.0
vscodeintellicode|Vis|1.2.16
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30429732
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30428978
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710:30416614

```

</details>

end. Please paste.

**Comment by meganrogge** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
