### ISSUE TITLE
Code is taking a lot of time to execute in terminal

### ISSUE THREAD

**Issue by candy-kush** [microsoft/vscode#141950]
When I run my C/C++ or any other code in terminal then it is taking a lot of time to execute. This problem is arising in any type of code, whether it is to print "Hello World" or any other code snippet. 
Note- I am currently using the latest version of VS Code i.e. 1.63.2 and my system is Windows 10 with 11th Gen Intel core i5 processor and 8 GB of RAM.

**Comment by meganrogge** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
