### ISSUE TITLE
Debug console intelliSense not taking first char

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14193]
- VSCode Version: 1.7
- OS Version: OS X 10.11.6

![pull](https://cloud.githubusercontent.com/assets/4033249/19614761/24ad8d96-97ad-11e6-8e7a-c60438c326a3.gif)

**Comment by octref** [comment]
Don't know whom to assign. Debug related so giving to you @roblourens :D

**Comment by roblourens** [comment]
I just came here to file this issue, lol

**Comment by roblourens** [comment]
And it seems to be not from the debug adapter.

**Comment by egamma** [comment]
Just got burnt by this too, promoted to an important bug.
