### ISSUE TITLE
Dragging Folders from File System into VS Code PWA

### ISSUE THREAD

**Issue by Offroaders123** [microsoft/vscode#141935]
With the standard Electron version of VS Code, the user is able to drag folders into the workspace from the File System, and it will open that folder in the current window.

I tried using this feature while editing my projects with the PWA version of VS Code at https://vscode.dev, however the folder did not open in the Workspace, as it does with the Electron version. I was using the VS Code PWA on Chrome OS with Chrome 97 installed.

In browsers that support the File System Access API, element `drop` events have the ability to return `FileSystemDirectoryHandle` objects after using the `getAsFileSystemHandle()` method on any `DataTransferItem` entries present on the event, if the user is dragging a folder. This would allow the user to drop a folder into the Workspace, and using the `DataTransferItem` entry to open 
that folder with the Workspace. 

This would be a very helpful feature to also have with the PWA version, it provides another way that the user can open folders from the file system, alongside the currently available "Open Folder" button in the Explorer menu.

Great work on the progress of the PWA by the way, it is working awesome so far!

Here's a reference to the information I found about the `DataTransferItem.getAsFileSystemHandle()` feature I mentioned above:
https://web.dev/file-system-access/#drag-and-drop-integration

**Comment by JacksonKearl** [comment]
fyi @bpasero

**Comment by Offroaders123** [comment]
I have done some of my own testing since this bug, and I stumbled on another issue since my original comment, not having to do with https://vscode.dev's implementation.

I found the issue on Chrome OS, and I think there may an additional implementation issue in terms of the browser itself.

I was going to try an implement a feature like VS Code's Explorer myself, so I can learn more about how it works, and I found out any time you have a directory as a selected item in your drag selection, it will prevent any `FileSystemHandle` objects from appearing inside of `event.dataTransfer.items`.

I will be testing my original issue comment above on other operating systems to see if the issue is still present, or if the whole problem was caused by Chrome OS's implementation issue.

I will do more testing for this new find, and if further results have the same outcome, I will submit a Chrome OS-specific issue report as well.

![Chrome OS Drop Issue](https://user-images.githubusercontent.com/65947371/152943926-c18bfcb5-fd76-4e1d-9f30-02f4b976f201.png)

**Comment by Offroaders123** [comment]
Alright, did some testing with my own code snippet from the last comment on Windows, and everything is behaving as expected in terms of browser implementation.

The original feature request for https://vscode.dev is still accurate as well, it looks like the dropping directories into the app isn't supported in the browser as of now, regardless of platform implementation issues, like the one on Chrome OS.

Summary:
- Original feature proposal still stands for https://vscode.dev
- I happened to find an implementation issue in Chrome OS that would affect this feature from working correctly, had it been part of the PWA at the time of my initial findings.

**Comment by tomayac** [comment]
(Filed the Chrome OS bug as https://crbug.com/1295210.)

**Comment by bpasero** [comment]
Pushed a couple of changes that adds `FileSystemHandle` support to our drop handlers where the browser supports it. 

This already enables a few interesting scenarios:
* dropping files to editor area for opening as real local file editors
* dropping a folder to the editor area for opening as workspace
* dropping a file or folder into a local workspace to copy the contents over

![Recording 2022-02-28 at 13 17 46](https://user-images.githubusercontent.com/900690/155982281-9f7cec58-bb9f-44ac-9080-36eeb4cf9a1d.gif)

I need to test this a bit more around handling N folders being dropped and supporting to add a folder to the workspace when dropped over the explorer, not sure yet why I am not getting asked whether I want to add the folder to the workspace or copy it into. We probably have some `isWeb` checks I need to clean up.

Also interesting how we can support this when a remote (such as GH) is opened. We can still support to open local files, but probably not folders.

**Comment by bpasero** [comment]
Did a complete test of all our drop sensitive locations and pushed some more changes.
* editor area
* editor tabs
* empty explorer
* open editors view

**Comment by Offroaders123** [comment]
Is there a time frame of when it may be likely to see this available in the stable https://vscode.dev @bpasero?
Thanks for your work to have this implemented, it's a very helpful addition!
