### ISSUE TITLE
Handle directories in search link opener as well

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#141956]
Clicking a `fixtures` link in the terminal when the folder exists in the cwd results in a search:

![image](https://user-images.githubusercontent.com/2193314/152005046-5caf4a12-70b9-443b-91b9-a975162ff633.png)

We do resolve this path and find that `${cwd}/fixtures` is a directory, so we could defer to the local folder handlers in this case which should be more useful and consistent with how files are treated.

**Comment by meganrogge** [comment]
to verify, with log level set to debug, make sure that you do not see `Opening link` with `type`:3 which represents a low confidence search link for this case https://github.com/microsoft/vscode/blob/8c20462d2a842a3838a5ba37b2b6557256fbdbf7/src/vs/workbench/contrib/terminal/browser/links/links.ts#L78-L82.

**Comment by Tyriar** [comment]
If you `echo src` in the vscode or xterm.js and click that link, it should focus that folder in the explorer instead of opening the search.

For dirs outside the workspace, eg:

```
cd ..
echo vscode-docs
```

Clicking vscode-docs should open a new window.

We handle local files specially here:

https://github.com/microsoft/vscode/blob/1981fd8ece9ac68c681f60b354e8167fec087a84/src/vs/workbench/contrib/terminal/browser/links/terminalLinkOpeners.ts#L146-L154

See how in `_getExactMatch` we only return based on `fileStat.isFile`, it should also handle directories both in and out of the workspace.

**Comment by Tyriar** [comment]
To verify:

1. Make a directory with a unique name in the folder
2. Run `echo 'directory'` with the dir name
3. Ctrl+click `directory` in the terminal, it should focus the folder in the explorer
4. Create a file somewhere in the folder with the same name
5. Ctrl+click `directory` in the terminal, it should open the search quick pick

**Comment by joyceerhl** [comment]
Verification step 3 fails for me @Tyriar--if I `mkdir foobarbazqux` and `echo foobarbazqux` it goes straight to file search 

![image](https://user-images.githubusercontent.com/30305945/155406232-6b35e6e4-3f4a-4acf-a788-c0a5628f7fb2.png)

**Comment by meganrogge** [comment]
@joyceerhl is `foobarbazqux` a folder in your workspace?

**Comment by meganrogge** [comment]
![Recording 2022-02-23 at 15 40 21](https://user-images.githubusercontent.com/29464607/155413222-16f9109d-0408-4e17-a5d7-1de0aaa052ee.gif)

**Comment by meganrogge** [comment]
also, with a file named `build` and a folder named `build`, the `build` folder is focused in the explorer
![Recording 2022-02-23 at 15 42 12](https://user-images.githubusercontent.com/29464607/155413533-49a41b0a-aebf-4513-8c87-a67ef8351bdf.gif)

**Comment by joyceerhl** [comment]
Yeah the path is `vscode/foobarbazqux` where I have the `vscode` folder open 
![image](https://user-images.githubusercontent.com/30305945/155415187-93ff9b56-4f24-48b0-a78d-a242117dd04c.png)

**Comment by meganrogge** [comment]
can you pls enable debug logging and provide me with the link opener log?

**Comment by meganrogge** [comment]
it should start with `Opening link`

**Comment by joyceerhl** [comment]
I did `code-insiders --log 'debug'` and this is what I see in 'Log (Window)' output:

```
[2022-02-23 14:06:44.779] [renderer1] [debug] Opening link {"text":"foobarbazqux","bufferRange":{"start":{"x":1,"y":65},"end":{"x":12,"y":65}},"type":3}
```

**Comment by Tyriar** [comment]
There is definitely a problem with today's build, links aren't working at all, I do see the opening link log though:

![image](https://user-images.githubusercontent.com/2193314/155560972-1ac725f6-1ff5-4202-97d9-17f17a9b1de3.png)

**Comment by Tyriar** [comment]
The opener ends up calling this with what looks like a valid URI to me as the same form URI works when opening an editor:

https://github.com/microsoft/vscode/blob/0e8fcebfbc9f5ecb1e7db0750fc3eb5a9a8cad69/src/vs/workbench/contrib/terminal/browser/links/terminalLinkOpeners.ts#L92
![image](https://user-images.githubusercontent.com/2193314/155595445-857c8534-a75c-41b4-9f7f-2ccd8fba13fa.png)

This workspace check is failing, but not sure why as I'm not familiar with the code:

![image](https://user-images.githubusercontent.com/2193314/155595596-f72289bc-7b4d-487a-8200-564fc071aa9e.png)


Changing to a lowercase `c` didn't fix it.

**Comment by Tyriar** [comment]
@JacksonKearl can you check this out as owner of the explorer? If it's too hard we can push, but I was hoping to mention this in the release notes.

**Comment by JacksonKearl** [comment]
When I step though this I see the picker appears rather than a revealInExplorer due to this area: 
https://github.com/microsoft/vscode/blob/0e8fcebfbc9f5ecb1e7db0750fc3eb5a9a8cad69/src/vs/workbench/contrib/terminal/browser/links/terminalLinkOpeners.ts#L181-L187

where multiple search results are returned because it's searching for all the files with `src` in their path rather than just finding the one folder. 
<img width="714" alt="image" src="https://user-images.githubusercontent.com/8586769/155786845-ebbe69e3-92a7-401e-bf50-80854985387f.png">


on the other hand if the folder only contains one file clicking on it opens that file 
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/8586769/155791792-e2e22acc-39b0-427d-97f0-14d2f0fdea56.png">

**Comment by Tyriar** [comment]
@JacksonKearl try create a unique folder name where no file would match it to repro; make an empty `foobarbazqux` and run `echo "foobarbazqux"`, it's important that the link isn't prefixed with `./`

**Comment by JacksonKearl** [comment]
Then I just get: 
<img width="817" alt="image" src="https://user-images.githubusercontent.com/8586769/155796058-819ff98c-bd53-4297-86ff-a160d65a0ef1.png">

File search doesn't give empty directory results as far as I'm aware.

**Comment by JacksonKearl** [comment]
Or to follow the instructions exactly: 
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/8586769/155797172-11e01541-ad8a-4332-949a-9ee78d757fb8.png">

**Comment by Tyriar** [comment]
Oh I think this problem with the folders is actually Windows only.

**Comment by JacksonKearl** [comment]
These are the cases I see, `revealInExplorer` doesn't seem to be called for any of them.
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/8586769/155802439-22980f7e-2d65-
4f3c-a959-a8a1b6557684.png">
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/8586769/155802462-5f99c70a-8731-49f9-b954-5af45aa35e0f.png">
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/8586769/155802498-30f52d16-488c-4219-8f16-9373acf5a126.png">

**Comment by Tyriar** [comment]
This is what I see:

![image](https://user-images.githubusercontent.com/2193314/155999672-0dc5dfd4-7420-4ece-aa47-660eb20889f0.png)

Focus remains in the terminal as revealInExplorer failed.

**Comment by Tyriar** [comment]
This is working for me now
