### ISSUE TITLE
Parameter hints popup obscures intellisense when editing at top of window

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#141947]
Old behavior:

![image](https://user-images.githubusercontent.com/2193314/151991453-c1d3be1c-e7bd-43c2-b2b3-b69fc32f1bb7.png)

New behavior:

![image](https://user-images.githubusercontent.com/2193314/151991824-4135f1c7-6207-4b18-aea9-db75fa40025b.png)

This new behavior doesn't happen all the time, this appears to happen because both suggest and parameter hints use z-index 40 right now.

cc @joaomoreno 

Caused by https://github.com/microsoft/vscode/pull/141647

**Comment by Tyriar** [comment]
To verify:

- Find a method with large parameter docs like `String.split`
- Scroll that line to near the top
- Re-type `(` to trigger hints, the parameter hint should show below
- Press ctrl+space (or mac equivalent) to show intellisense

Also:

- Reload window
- Find a method with large parameter docs like `String.split`
- Scroll that line to near the top
- Press ctrl+space (or mac equivalent) to show intellisense
- Press escape
- Re-type `(` to trigger hints, the parameter hint should show below
- Press ctrl+space (or mac equivalent) to show intellisense, intellisense should be on top of parameter hints

**Comment by meganrogge** [comment]
I'm seeing this - I expected to see the definition

![Screen Shot 2022-02-02 at 3 34 20 PM](https://user-images.githubusercontent.com/29464607/152241071-63775ecd-85af-4e08-a5a3-0c2f6a032fa2.png)

**Comment by meganrogge** [comment]
when I scroll down a bit:
![Screen Shot 2022-02-02 at 3 36 57 PM](https://user-images.githubusercontent.com/29464607/152241404-a4c6d8ee-fbab-4c63-868a-47b927a152d6.png)

**Comment by Tyriar** [comment]
@meganrogge that's actually the correct behavior; intellisense should cover the parameter hints popup

**Comment by meganrogge** [comment]
oh I was confused because usually old behavior is bad new is good (expected)

**Comment by meganrogge** [comment]
so this was a regression?

**Comment by Tyriar** [comment]
Yep it was a regression
