### ISSUE TITLE
Keeps crashing constantly

### ISSUE THREAD

**Issue by Ponkabonk** [microsoft/vscode#141900]
I'm using the latest insider build with no extensions installed.  VS Code crashes constantly.  The current reason code is -10734741819.  Sometimes I get no error at all.  The window just closes.  Sometimes, the "preview" pane on the right side goes blank.  I know that a crash is imminent when that happens.  

This also happens on the release version.  Just as bad, just as often.

One of the strangest errors is the attached image.  I've also attached a good one for comparison.

I've got a brand new Dell running Windows 11, 64GB RAM and an 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz   3.40 GHz

I'm happy to collect some logs if someone can tell me where to find them.  The log files I've found don't appear to contain any relevant data.

![vscode weird error](https://user-images.githubusercontent.com/4604965/151866193-948afc53-861a-44e7-9203-d99d965462bf.png)
![vscode good terminal](https://user-images.githubusercontent.com/4604965/151866202-e0837691-f7ff-4935-b8c6-ba3a7520b939.png)

**Comment by Ponkabonk** [comment]
I launched VS Code with this code --crash-reporter-directory c:/vscode_crashes and collected the attached dumps.

[vscode crash dmps.zip](https://github.com/microsoft/vscode/files/7974387/vscode.crash.dmps.zip)

**Comment by Ponkabonk** [comment]
Here's two more.  You'll see that the right preview is missing as is most of my code.  The code that is being displayed appears to have some weird encoding issue.  You'll see by comparing the two versions that some of the text isn't displaying and some of what is displayed is just wrong.  
![Weird 1](https://user-images.githubusercontent.com/4604965/151878816-d9c5ff5a-9346-4910-b5e4-db197906910e.png)
![Weird 1 - what its supposed to be](https://user-images.githubusercontent.com/4604965/151878819-99384113-7a38-4fde-b46d-1e415a2775bd.png)

**Comment by deepak1556** [comment]
Thanks for crash logs, can you give our exploration builds which are based on a newer runtime version and see if the crash repros.

[window x64 user setup](https://az764295.vo.msecnd.net/exploration/8eab3dba050a3bd11dcdd33f6bca2fe807cf3f9c/VSCodeUserSetup-x64-1.64.0-exploration.exe)

**Comment by Ponkabonk** [comment]
Yup.  Same issue.  Sometimes I get a different error message though.
![vs crash 1](https://user-images.githubusercontent.com/4604965/152010871-a2b9f1a6-3392-481f-8a67-94459b0c34c4.png)
.

**Comment by deepak1556** [comment]
Can you start the application with `code-exploration --verbose` and attach the output after the crash happens.

**Comment by Ponkabonk** [comment]
Sure.  Where will I find the crash logs?

**Comment by Ponkabonk** [comment]
I ran code-exploration --verbose from the command line and immediately saw this:
![vs code JS error](https://user-images.githubusercontent.com/4604965/152011842-e231078b-3f26-44f5-8648-876d5aa67e23.png)

**Comment by deepak1556** [comment]
Looks like corrupted script evaluation, can you try starting with a fresh user data directory `code-exploration --verbose --user-data-dir <provide some writable path, ex: %APPDATA%\test-exploration>`

**Comment by Ponkabonk** [comment]
It didn't crash this time but I tried to open a folder.  I got the file explorer and chose my folder.  But nothing opened.  Now the mouse moves around the window but the clicks are unresponsive.  The file menu is stuck open and "New File" is highlighted (which I believe is the default selection when opening that menu).  Even the red X for closing the window doesn't work.  I'll have to kill the app using the task manager.

**Comment by Ponkabonk** [comment]
I kept messing around with the mouse trying to click on things and the app crashed.  I noticed more info was written to the cmd window so I grabbed everything again.  This contains everything from the previous file and more.
[exploration spew with crash info.zip](https://github.com/microsoft/vscode/files/7980489/exploration.spew.with.crash.info.zip)

**Comment by Ponkabonk** [comment]
I was able to load a folder and see my code.  The app crashed while I was typing and I accidentally clicked on whatever the default button is on the error window.  Probably reload.  

I've disabled all nonessential stuff from Startup and am running a direct connection to my router (no wifi).  I'm not seeing any improvement.

[exploration spew noturbo_load_elimination .zip](https://github.com/microsoft/vscode/files/7980613/exploration.spew.noturbo_load_elimination.zip)

**Comment by Ponkabonk** [comment]
Not sure if this will be helpful but here's another symptom.  When the right side preview disappears, I can "select all" and see my code selected on the preview.  But, when I click anywhere on the screen (and all isn't selected) the preview goes blank again.  Also, if I highlight a variable, the preview shows the highlighted lines where the variable occurs.  But no code shows.

![Symptom 1](https://user-images.githubusercontent.com/4604965/152019981-b4120cd5-598d-4f14-bc29-435adb35a672.png)

**Comment by Ponkabonk** [comment]
Hey.  I just spent the better part of 3 hours on the phone with Dell support.  It seems some of my video drivers were FUBAR.  I've been testing for the last few minutes and it is much more stable than it was.  I haven't seen a crash yet.  I'll report back here in a few hours with my observations.  Fingers crossed but the issue might be gone.

**Comment by Ponkabonk** [comment]
I still have the problem but I'm nearly convinced it's not VS Code.  Updating the drivers helped but it still crashes.  Though now I'm seeing it on other apps too.  So, let's consider this issue closed and I'll start a new one if it circles back around to VS Code.  Thanks for the attention.

**Comment by deepak1556** [comment]
Thanks for confirming, will close based on the last comment.
