### ISSUE TITLE
PDFs as images in markdown

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode#141957]
Could the VS Code Markdown preview could support PDFs as images?

[Says here](https://code.visualstudio.com/docs/languages/markdown):

> VS Code targets the CommonMark Markdown specification using the `markdown-it` library.

So I'm guessing the answer is no or submit it to `markdown-it`?

FWIW, Safari already supports this. I converted this markdown to HTML and opened it in Chrome, Brave and Safari.

```markdown
![test](image.pdf)
```

Only Safari displayed the PDF correctly. Other browsers give a missing asset thumbnail:

![Screen Shot 2022-02-01 at 16 31 11](https://user-images.githubusercontent.com/30958850/152009533-a5c87b8c-8d12-4df3-acb2-8c3d450c1735.png)

**Comment by mjbvz** [comment]
This is out of scope of both VS Code and markdown-it. It could potentially be provided by an extension though
