### ISSUE TITLE
Theme issue with template strings in Monakai

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/vscode#14190]
- VSCode Version:
- OS Version:

Copying from Microsoft/TypeScript-TmLanguage#324

Reported by @mohsen1
```ts
function foo(a) { return <div className={`abcd-${a}`}></div> }
```

`a` in template string is not highlighted

![screen shot 2016-10-20 at 6 10 00 pm](https://cloud.githubusercontent.com/assets/543633/19583313/6f9c9dbe-96f0-11e6-8d40-7a38fe05ae8d.png)

VSCode Version 1.6.1 (1.6.1)
Just downloaded the grammar plugin 
Monokai theme

**Comment by aeschli** [comment]
This is caused by #3008
