### ISSUE TITLE
Unable to update via command palette

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#142037]
I've been working with hiding the activity bar and using the side panel for a more "focused" setup. However, I realized that from this setup I can't update VS Code via the command palette as the only way to update is via the settings menu in the bottom left:

<img width="1195" alt="CleanShot 2022-02-02 at 13 08 30@2x" src="https://user-images.githubusercontent.com/35271042/152237673-de0aef1a-b1ea-4780-af31-f3dbbe6660d8.png">

Can we add a command entry for checking / installing updates?

**Comment by joaomoreno** [comment]
The action is there but only available if an update isn't yet in progress. Can you check?

![image](https://user-images.githubusercontent.com/22350/154084582-1abbccfb-58e8-4a33-9bad-d3b0f27a4fa6.png)

**Comment by misolori** [comment]
So I do see the update command if there is no updates pending, but once there is an update available I can't update from the command palette:

<img width="674" alt="CleanShot 2022-02-15 at 21 37 55@2x" src="https://user-images.githubusercontent.com/35271042/154203090-06873b12-d92c-4876-995c-d6c7f3fa9437.png">

Can we add one for when there are updates to install?

**Comment by joaomoreno** [comment]
Yeah, added three global commands for all possible actionable update states:

- Download Update (archive)
- Install Update (windows with background updates disabled)
- Restart to Update (windows + darwin)
