### ISSUE TITLE
[Feature Request] View the TMLanguage scope that is called in the editor.

### ISSUE THREAD

**Issue by longtomjr** [Microsoft/vscode#14204]
This is a feature that is supported in Sublime Text that allows the user to see the scope that is called with (ctrl - shift - alt - P). I find this feature useful because I need to write TMLanguage files to support SKON (a new object notation language) syntax highlighting and error highlighting in VSCode.

I do not know how difficult such an implementation would be, but if it is easy it would be a definite quality of life improvement. If is is a big job, it most likely is not worth the effort

**Comment by siegebell** [comment]
If #580 is resolved, it would be trivial to write an extension that provides hover messages giving the TMLanguage scope for any document.

**Comment by siegebell** [comment]
I've written an extension that provides scope information as you hover over text: https://marketplace.visualstudio.com/items?itemName=siegebell.scope-info

**Comment by siegebell** [comment]
You can see the logic I use to find the grammar file [here](https://github.com/siegebell/scope-info/blob/master/src/extension.ts#L42) -- it likely does not respect the precedence vscode uses to resolve multiple contributions for the same language.

**Comment by longtomjr** [comment]
Thanks a lot, Can I consider this closed?

**Comment by siegebell** [comment]
sure

**Comment by longtomjr** [comment]
Closing as there is a way to dot this now!
