### ISSUE TITLE
Scroll multiple editors together

### ISSUE THREAD

**Issue by lich1288** [Microsoft/vscode#14209]
- VSCode Version: 1.6.0
- OS Version: Windows 10 1607

Steps to Reproduce:
1. Create two editors, one in the left side and one in the right side.
2. When editing a file comparing with another file, I want to scoll both two editors in the same time .

**Comment by mjbvz** [comment]
Related to #5047, which describes a similar feature but for a markdown file and its preview.

**Comment by Dominik-K** [comment]
@lich1288 Why not just using the ["Compare view"](https://code.visualstudio.com/docs/editor/versioncontrol#_viewing-diffs) which has autoscroll enabled?

**Comment by lich1288** [comment]
@Dominik-K Thanks, that's exactly what I want!
