### ISSUE TITLE
No hints for object literals in Typescript Hints

### ISSUE THREAD

**Issue by qavs** [microsoft/vscode#142072]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
- OS Version:
Windows 10 Pro 21H2 19044.1466

Steps to Reproduce:

1. Use `"typescript.inlayHints.parameterNames.enabled": "literals",` in `settings.json`

Result:
![5fa91c6c4b7d3119c0973f1e9e412d4d](https://user-images.githubusercontent.com/98740159/152335391-a2b60560-97a4-4b5e-bf34-ce5614c244d9.png)

**Comment by mjbvz** [comment]
Please always share the text of the code along with screenshots

**Comment by mjbvz** [comment]
Also you've set the inlay hints to `literals` which means that only parameters with simply literal types (number, string, bool, ...) will get inlay hints. Set `"typescript.inlayHints.parameterNames.enabled": "all"` to always show inlay hints
