### ISSUE TITLE
Add support for callback when progress indicator created using `window.withProgress` is clicked

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#142011]
Consider the following `Discovering Python Interpreters` indicator for example:

![image](https://user-images.githubusercontent.com/13199757/152185414-aa791657-0925-4bf6-be55-c45ceef35f88.png)

Sometimes discovering all interpreters can take longer than expected, but meanwhile users only need to select the one interpreter to get started which may already be discovered, users are often tempted to click on the progress indicator only to expand the notification:

![image](https://user-images.githubusercontent.com/13199757/152186411-e9d56359-950a-403f-85d7-af9ca5868c75.png)

We would instead like to show the current progress when a progress indicator is clicked, which in this case would be the currently known list of interpreters:

<img src="https://user-images.githubusercontent.com/13199757/133702997-6fbc769d-080b-4572-b451-5ce47b670026.gif" width=600/>

**Comment by jrieken** [comment]
I understand the request but I wonder if we should tackle this as a platform (and avoid extensions using quick pick individual progress task). The idea of the progress API is to show an overarching message like "Do stuff" and then sending updates for individual work pieces. Today, these pieces are just string or number but it can be extended with more properties that a richer UI would show. This means VS Code could come with a "progress pane"  that expands when clicking the "progress summary" and from there certain commands can be triggered.

**Comment by bpasero** [comment]
Didn't we solve this for our remote extensions that show progress for as long as we install the remote server and provide rich links in the notification that users can click to open the terminal?

@chrmarti @aeschli do you know how remote extensions trigger this?

**Comment by aeschli** [comment]
```ts
	this._resolvePromise = vscode.window.withProgress(
		{
			location: vscode.ProgressLocation.Notification,
			title: `[Starting VS Code in WSL (${distro.name})](command:remote-wsl.showLog)`,
			cancellable: false
		},
		progress => { 
		   //...
		   progress.report({ message: 'Starting Linux Subsystem' });
		}
	);
```

**Comment by misolori** [comment]
There are pros and cons to showing content as it loads:
- **pro:** if the one you want appears earlier you can select it and save time
- **con** if the quick pick does any type of grouping of items (to make it easier) then you can't do this as items will shift around as someone attempts to select

One of the biggest UX annoyances is clicking on an item, as things are loading, and the list shifting and you end up clicking the wrong one. While in the proposed gif that's not exactly happening (the titles are just updating as it learns about each item) this means the user has to make more effort to discern what changed, which gives the impression that the list changed. I'm not sure that is helping the UX.

**Comment by bpasero** [comment]
I think this is a good approach 👍
