### ISSUE TITLE
Add hover background in Settings (light themes)

### ISSUE THREAD

**Issue by lychung7** [microsoft/vscode#142047]
The setting hover background is missing for light themes. It'd be nice to add this to be consistent with the experience in dark themes. 
![image](https://user-images.githubusercontent.com/60596156/152256889-3ed33c34-81c4-4e5b-a711-ad569ffb7adb.png)
![image](https://user-images.githubusercontent.com/60596156/152256977-1bb38073-20ac-4156-bc38-84da51624fbe.png)

**Comment by rzhao271** [comment]
I believe the hover background colour is set based on the focused row background colour, and that's set at https://github.com/microsoft/vscode/blob/c0928519ab70c0e98b970afb0590ea96a166a142/src/vs/workbench/contrib/preferences/common/settingsEditorColorRegistry.ts#L42
Any suggestions for what the colour should be changed to?

**Comment by roblourens** [comment]
Maybe there is something you can take from general list styling for this? I think list styles have been revamped since the settings editor colors were set.

**Comment by lychung7** [comment]
Yes @roblourens, it seems like there are some other hover styles I can try and change the opacity if needed. I'll go through the list!

**Comment by lychung7** [comment]
I tried using the sidebar background color as the hover background color for the settings. For the selected state, I tried it at 50% opacity. Let me know what you think!

![settingshovercolor](https://user-images.githubusercontent.com/60596156/152842125-c21ce57c-ffc1-4ceb-a761-3746afe74c01.png)

<img width="1411" alt="Screen Shot 2022-02-07 at 9 34 30 AM" src="https://user-images.githubusercontent.com/60596156/152842154-a8e07dd0-26a2-44f9-b614-051c2ae0e6e0.png">

<img width="1413" alt="Screen Shot 2022-02-07 at 9 35 39 AM" src="https://user-images.githubusercontent.com/60596156/152842186-09103995-c914-4d48-93ca-207c9455c8c6.png">

**Comment by rzhao271** [comment]
I was about to say that the contrast seems too high with the default light theme, but then I realized that the result really depends on what each theme decides to do with the sidebar colour. I think that the inactive tab background colour might be another option, considering how it seems the Settings editor background colour = the active tab background colour, and how that colour seems to contrast with the inactive tab background colour.

Another possible alternative is to base the focus and hover colours on darker/lighter versions of the Settings editor background colour, though that would just add another set of colours to the palette, so I'd rather do that as a last resort.

**Comment by lychung7** [comment]
Hmm, I tried the inactive tab background color, but it seems darker than the side bar background color, making the contrast even higher.
Also, for some of the light themes, using the inactive tab background color makes it hard to distinguish from the row hover color inside the setting. Shown below:
<img width="790" alt="Screen Shot 2022-02-07 at 11 47 17 AM" src="https://user-images.githubusercontent.com/60596156/152861263-30f5b8c3-d7c2-49c0-98ab-1b823d0df0ac.png">
<img width="774" alt="Screen Shot 2022-02-07 at 11 50 02 AM" src="https://user-images.githubusercontent.com/60596156/152861286-23de0716-5b8a-4ed8-9588-d399c2c1ba17.png">
