### ISSUE TITLE
Explorer collapse/expand folder events

### ISSUE THREAD

**Issue by borislit** [microsoft/vscode#142041]
Hi, Im exploring an option to build an extension that will (among other things) listen on navigation to folders in the explorer(folder tree). For example, when user expands a folder in the explorer tree structure.
There are various use cases to this, like collecting metrics or popping up hints and info based on the folder.
Ive explored the api and currently it seems like the only way to gain those events is to build you own TreeView.
I would like to listen on event on the existing Explorer three.

**Comment by JacksonKearl** [comment]
There is no api for retrieving the explorer's currently selected item. You could however contribute to the context menu of explorer items. Would this work for you?

**Comment by borislit** [comment]
Definitely! Would love to contribute. Could you provide guidance for a starting point and explain the design you were thinking of?

**Comment by JacksonKearl** [comment]
Sorry I may not have been clear -- the guidance here is for the extension to contribute entries to the context menus of the explorer items. An example of an extension that does that is https://github.com/chrisdias/vscode-opennewinstance. We don't want to support extensions being able to react to explorer tree navigation events, though we may support extensions being able to query for the current selected item https://github.com/microsoft/vscode/issues/3553.
