### ISSUE TITLE
Revisit non-recursive watching having moved to shared process

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#142027]
Some core workbench components such as configuration service now cannot reliably watch for file changes on startup. The intent was good given extensions can now add folders for watching, but maybe this needs to be configurable in a way that configuration service still gets file change events from the main process.

//cc @sandy081

**Comment by bpasero** [comment]
@sandy081 now that I see AlexD's fix in https://github.com/microsoft/vscode/issues/142020, can we do the same for configuration service and trigger a reload of the configuration model based on `FileOperation.Write` events?

I saw similar code as for keybindings here:

https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/workbench/services/configuration/browser/configuration.ts#L484

**Comment by sandy081** [comment]
Sure can can

**Comment by sandy081** [comment]
@bpasero Adopted to the file operation event and enabled the smoke test. I would leave to you for revisiting the changes you mentioned in the description.

**Comment by bpasero** [comment]
Thanks a lot, I think I would leave it as is, especially since so far stable users have not reported an issue yet.
