### ISSUE TITLE
Keybindings synced to some extension that doesn't exist in my VS code

### ISSUE THREAD

**Issue by mylospykar** [microsoft/vscode#142092]
Issue Type: <b>Bug</b>

Hello there, I'm faceing an issue with the keybindings where the default vs code keybindings are overridden by an extension keybindings, I've made the basic keybindings to my custom use, still there are lots of shortcuts are binded to unknown extension (I don't have any other keybinding extension).

for example : 
1. shift+A doesn't let me enter the capital letters, it selects the current line (same as ctrl+a)
2. create new file was set to alt+insert by default and I had to customize the keybinding to ctrl+n

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (6.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
wslgetstarted:30426333
vscop940:30404999
vsrem710cf:30416617

```

</details>

**Comment by IllusionMH** [comment]
Please follow steps from https://github.com/microsoft/vscode/wiki/Keybinding-Issues to see what key sequences are received and processed by VS Code.
