### ISSUE TITLE
show the installed extensions while searching

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#142007]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: all
- OS Version: all

Steps to Reproduce:

1. install C/C++
2. offline network
2. search extension `c++`

- online(INSTALLED)
![image](https://user-images.githubusercontent.com/1876302/152178220-1174f14b-96be-4c62-bdaa-6ea92fd8e753.png)

- offline network
![image](https://user-images.githubusercontent.com/1876302/152179812-4781b13f-6286-4fea-979b-675377e9eddf.png)

it is great to show the extensions when offline,
e.g. 
- we are in trouble in network
- another reason. My workmates and I are using vscode in our own RD development env which is offline. we usually search the installed extension for the readme or guide. but we couldn't search out the extensions we want directly. few people even do know how to add filter `@installed` 

propose
------
show the installed extensions even in offline

**Comment by sandy081** [comment]
you can use `@installed` filter to search in installed extensions.

**Comment by heartacker** [comment]
@sandy081  I have  mentioned that few people even do know how to add filter @installed 
 Could you please think about people who are new to vscode.
 And could you please make it better.

 You are professional so you know how to deal with this problem.

**Comment by sandy081** [comment]
Sorry for not showing the UI before but you can find it in the UI as below

![image](https://user-images.githubusercontent.com/10746682/153096909-85db3fd7-5e96-48a3-be54-5ee58eb201f6.png)

**Comment by heartacker** [comment]
> Sorry for not showing the UI before but you can find it in the UI as below
> 
> ![image](https://user-images.githubusercontent.com/10746682/153096909-85db3fd7-5e96-48a3-be54-5ee58eb201f6.png)
> 

 Yes, I know.  I know how to add the filter @installed.
 And I also know how to use UI to show them.  I'm familiar to vscode。
 But others don't.  I had to tell others again again and again to how to show them. 
In their opinion,  They think you should show the results  directly. Me too even I know how to add a filter and use the UI.

 Maybe Keep it simple, keep it stupid.
thanks

**Comment by sandy081** [comment]
I think users generally search for extensions in Marketplace as it mentioned in the input box. This is most common scenario. Searching in installed extensions is not prominent. Hence it is shown in the filter drop down.

**Comment by heartacker** [comment]
@sandy081 hi. Sorry for mentioning it again.

I have an idea about extension searching
I believe we should provide a set of view for installed extensions while searching. either online or offline


- online
show the available extension from network and show the installed in one group（as pic showed）
![image](https://user-images.githubusercontent.com/1876302/153983748-9d2cbe42-dd29-4c5a-9ead-8a343464157d.png)



- offline
show the error message and also show the installed extension in one group
![image](https://user-images.githubusercontent.com/1876302/153983828-667d9aed-e256-4271-86ab-30e6bd0b68ce.png)

that will be easy to search and reduce the user's mental

please 🙏
