### ISSUE TITLE
Source Control Sort Not Working

### ISSUE THREAD

**Issue by Hossy** [microsoft/vscode#142030]
Issue Type: <b>Bug</b>

Regardless of if I choose Name, Path, or Status, the order of the repos on the Source Control tab doesn't change and remains unsorted.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU       X 980  @ 3.33GHz (12 x 3331)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|24.00GB (0.76GB free)|
|Process Argv|--crash-reporter-id b73279b1-b78d-410f-8634-5ebf1cd0b54b|
|Screen Reader|no|
|VM|57%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.19.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.5
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
powershell|ms-|2021.12.0
vscode-yaml-sort|Pas|5.1.2
java|red|1.3.0
vscodeintellicode|Vis|1.2.16
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vs360cf:30404996
vsrem710:30416614

```

</details>

**Comment by gjsjohnmurray** [comment]
I think this controls the sort order of files listed within each repo section, not the order of the multiple repos it sounds like you see.

**Comment by lszomoru** [comment]
Thank is correct. The "Sort" options are for the "changes list" in the "Source Control" view. At the moment there are no options to sort the list of repositories in the "Source Control Repositories" view. That is something that we would like to enable in a future release.
