### ISSUE TITLE
Debugging C++ hangs while using F10 to walk through code

### ISSUE THREAD

**Issue by tcf8461** [microsoft/vscode#142060]
I am getting the following error on the debug console:

"Stopping due to fatal error: ArgumentException: An item with the same key has already been added. Key: (Microsoft.MIDebugEngine.AD7StackFrame, __FUNCTION__)"

I put a breakpoint into the code then stepped into a method and started using F10 to walk through the code. The display item to the left of the **Variable > Locals** entry turned into a wait icon and it never returns. Its done this almost continuously today. I have restarted both vscode and my VirtualBox linux environment I am SSH'd into where my SVN checkout lives. 

The version of vscode I am running is 1.63.2 and it says there is nothing newer. I am running Windows 10 Enterprise 19042.1466. The development environment is linuxmint in a virtualbox VM using SSH to connect. Vscode has not done this to me very often before but I had a lot of windows updates the other day and I am not sure I have done any intensive debug sessions since. This time its impossible to get through a debugging session as this error occurs every time.

**Comment by tcf8461** [comment]
The word FUNCTION above had two underlines before and after, like __FUNCTION __

**Comment by elmhoque** [comment]
I am also having similar issues, when two variables has same name or even with two foreach loops.
