### ISSUE TITLE
can't edit terminal segment

### ISSUE THREAD

**Issue by EmmaGikonyo** [microsoft/vscode#142065]
Issue Type: <b>Bug</b>

when i click the new terminal tab it creates a blank uneditable panel

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 6.2.9200
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU 1000M @ 1.80GHz (2 x 1796)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.62GB free)|
|Process Argv|--open-url --crash-reporter-id dc2bb1e6-6f43-480d-98cb-7c0e7da4c103 -- vscode://vscode.github-authentication/did-authenticate?windowid=1&code=5c24acbb6ea7c63454db&state=0a3a3158-aaa2-4969-93d8-d97e0c06097a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.0
vscode-mysql|for|0.4.1
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.5
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
sqltools|mtx|0.23.0
sqlite-viewer|qwt|0.1.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30428978
pythonvs932:30410667
vscop940:30404999
vsclayoutctrc:30425945
vsrem710:30416614

```

</details>

We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by Tyriar** [comment]
Can you clarify what version of Windows you're on? Also if you're running the correct 32/64 bit VS Code depending on your OS?
