### ISSUE TITLE
with multiple folders in a workspace, terminal description doesn't include cwdFolder

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#142046]
![Screen Shot 2022-02-02 at 5 47 42 PM](https://user-images.githubusercontent.com/29464607/152256867-d89dcbff-0366-48cc-a280-e4ce1e3736d7.png)

**Comment by meganrogge** [comment]
same root cause - https://github.com/microsoft/vscode/blob/5cb6ea993449cfc39202d37ebd9613c02530b7e1/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L2295

**Comment by rchiodo** [comment]
/verified

Stable shows this:

![image](https://user-images.githubusercontent.com/19672699/155594759-d598cb11-2854-4197-8f42-bc40ab6ed190.png)

Insiders shows this:

![image](https://user-images.githubusercontent.com/19672699/155594780-5e6c310f-4968-427d-8da9-7ab31087f0e7.png)

For same operations (open terminal in another folder)
