### ISSUE TITLE
Why is cwd always set to application folder on Windows?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14201]
I'm curious why this is done,, as it's what caused https://github.com/Microsoft/vscode/issues/11735 

The change: https://github.com/Microsoft/vscode/commit/b43c9501474806a11d0d73a26d27759c1401a8ad#diff-1c90ff38a08209f9ebd4d05d1e43358eR102

**Comment by bpasero** [comment]
@Tyriar this makes it work better on windows 👍
