### ISSUE TITLE
Allow configuring a base uri for MarkdownString

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#142051]
## Feature request

Allow configuring a base uri that is used when rendering the contents of a `MarkdownString`. This uri would be used when resolving relative paths that appear as links or image links within the markdown string

## Example use case

```ts
const md = new vscode.MarkdownString(`
[link](toSiblingFile.md)

![img](./image/from/dir.gif)
`);

md.baseUri = vscode.window.activeTextEditor.document.uri
```

When rendered, `link` and `img` should both resolve to files next to the currently active file

## Related issues
- #130968
- #86564

**Comment by mjbvz** [comment]
The alternative today is that extensions have to parse the markdown and transform the uris themselves. This is difficult to get correct

**Comment by DanTup** [comment]
@dbaeumer is this something that should be in the LSP spec (for servers to set), or the client (assuming they should be relative to the document the request relates to)?
