### ISSUE TITLE
Don't expose xterm.js' ILink outside of TerminalLinkManager

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#142031]
After the recent terminal link refactor (https://github.com/microsoft/vscode/pull/141755) there's a new simpler interface for links `ITerminalSimpleLink`. The code for keyboard accessible links should move from selecting from `ILink`s and then calling their `activate` function to `ITerminalSimpleLink`s and passing the selection back to `TerminalLinkManager.openLink` (make `_openLink` public). This will simplify what happens and the interfaces exposed on `TerminalLinkManager` since we don't need to involve the more complex types.

**Comment by Tyriar** [comment]
Let's not do this, struggled to get the tests working after trying yesterday and it works as is currently. Can revisit later if there is motivation.

**Comment by meganrogge** [comment]
I also tried this last night to no avail 🤷🏼‍♀️
