### ISSUE TITLE
Unexpected tab completion

### ISSUE THREAD

**Issue by fronteed** [Microsoft/vscode#14207]
- VSCode Version: 1.6.1
- OS Version: OS X

I've recently added the issue regarding unexpected tab completion https://github.com/Microsoft/vscode/issues/13141

That issue is closed but still not fixed. Current behavior turns me into frustration, I suggest you to make notes on that issue (I still believe it should be fixed) and give some comments.

Thanks.

**Comment by roblourens** [comment]
I'm not sure what happened in that issue, @jrieken?
