### ISSUE TITLE
Usability issue: Painfully hard to select window splitters

### ISSUE THREAD

**Issue by tohagan** [microsoft/vscode#142056]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 

Version: 1.63.2 (system setup)
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

- OS Version: WIndows 10 

Steps to Reproduce:

1.  Split a terminal or Editor view (vertical or horizontal) 

2.  Now try to select the splitter control between the split panel to adjust the split width or height. I find it takes me a few seconds to _finally_ grab it and slide to adjust it. This is annoying, mentally distracting and recurring time waste as I frequently need to do this.

This is most likely because the pixel width of the selectable zone for this splitter control is _too thin_.   So my request is to increase the width of the select zone for the splitter controls by a pixel or two to speed up selection.  For users who suffer any form of motor control disability I'd imagine the UX would be very difficult to wear.  I build web apps with Splitter controls that don't suffer this issue. 

Thanks for the awesome VS Code !!

**Comment by IllusionMH** [comment]
Have you tried to increase `workbench.sash.size` to 10 or more?

**Comment by tohagan** [comment]
Thanks that fixed it.  Was 4,  I set it to 6 and it's fine.  Much appreciated!

**Comment by tohagan** [comment]
Just adding this link for anyone who might pass by ...

- https://code.visualstudio.com/updates/v1_46#_sash-size-configuration
