### ISSUE TITLE
Support common prompts with shell integration

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#142004]
Need to look into supporting these prompts across platforms/shells:

- Oh my zsh
- Oh my posh
- Starship
- powerlevel10k

**Comment by Tyriar** [comment]
oh-my-posh on Windows seems to work fine:

![image](https://user-images.githubusercontent.com/2193314/153955927-b1baf3fc-b3f6-47c7-b2c7-28fb6c0cfafa.png)

**Comment by Tyriar** [comment]
starship on Windows ✅ 

![image](https://user-images.githubusercontent.com/2193314/153956661-e2be3c14-71ac-4403-bd08-213c53c78070.png)

**Comment by KarlScheibelhofer** [comment]
i tried shell integration using zsh (Win 10 21h2, WSL 2, Ubuntu 20.04) and oh-my-zsh using the agnoster theme and git plugin.

![screenshot-setting-1](https://user-images.githubusercontent.com/31418056/158599403-73cc08f1-bc80-48ce-a791-cf86b92e4c8a.png)

in principle, it worked. but it messed with the background color of this scheme. in the screenshot, the upper terminal window was opened bevor activating the integration. the lower terminal with integration. it shows the yellow baackground color of the prompt i still active while typing, which makes this terminal pretty hard to read:

![screenshot-terminals](https://user-images.githubusercontent.com/31418056/158599699-d9644f4b-735e-4a23-b832-b51982161914.png)

**Comment by Tyriar** [comment]
oh-my-pwsh/mac skipped commands aren't getting decorations:

<img width="574" alt="Screen Shot 2022-03-17 at 11 25 25 am" src="https://user-images.githubusercontent.com/2193314/158870753-426d16e4-1861-4a12-a464-918bcaa42b8f.png">

**Comment by Tyriar** [comment]
@KarlScheibelhofer I think the fix to https://github.com/microsoft/vscode/issues/145163 may fix your issue.

**Comment by Tyriar** [comment]
Having trouble installing powerlevel10k on my mac, oh-my-zsh works fine though. Calling this issue done and we can handle any shell-specific problems in other issues.

**Comment by KarlScheibelhofer** [comment]
now having installed the vscode-insider build, i tried some combinations with my ubuntu 20.04 inside WSL2. 

* bash with starship working
* zsh with starship also ok

* zsh with oh-my-zsh does not work. 

i tried with the https://github.com/romkatv/powerlevel10k theme. it gives a warning on startup which might help
![image](https://user-images.githubusercontent.com/31418056/159136462-849e9332-5ea0-4bfc-91a4-4c6accde354e.png)

when disabling terminal shell integration, the terminal starts without this warning
![image](https://user-images.githubusercontent.com/31418056/159136535-684cb73c-2050-418e-8b7a-41458b4742e8.png)

**Comment by romkatv** [comment]
That warning from powerlevel10k simply says that something has printed "Shell integration activated" while zsh was initializing. It's usually a bad idea to print stuff of this sort while zsh is initializing.

**Comment by romkatv** [comment]
Is there a documentation for vscode shell integration that explains the mechanism? Is it OSC 133? OSC 7?

Where can I find zsh code that gets injected by vscode?

**Comment by KarlScheibelhofer** [comment]
@romkatv i guess it might be https://github.com/microsoft/vscode/tree/main/src/vs/workbench/contrib/terminal/browser/media , but @Tyriar might know for sure

**Comment by KarlScheibelhofer** [comment]
... and yes, yo uare right. if i disable the "Show Welcome" this warning disappears 
![image](https://user-images.githubusercontent.com/31418056/159162449-601a47e2-a398-4ac3-a588-5aafea9db731.png)

but the shell integration features do not work either.

**Comment by romkatv** [comment]
> @romkatv i guess it might be https://github.com/microsoft/vscode/tree/main/src/vs/workbench/contrib/terminal/browser/media , but @Tyriar might know for sure

Thanks for the link.

I look a look at zsh integration as that's what I care about. This code has a number of severe bugs. Some are easy to fix, others would require changing the high-level design. Here is an incomplete list of bugs I noticed:

- Shell integration doesn't work in the following cases:
  - If you manually run `zsh` in an existing interactive shell.
    - Perhaps because your login shell is fish but occasionally you want something more POSIX-y.
    - Perhaps because you need to create a temporary session with different environment variables.
    - Perhaps because you are running `sudo -E zsh` to create an interactive privileged shell.
  - If you restart zsh with `exec zsh`. Zsh users (and perhaps other shell users although I'm less familiar with their practices) often apply rc file changes to the current shell with this command.
  - If you SSH to a remote host with zsh as login shell.
  - If you have `tmux` as login shell and configure it to start zsh.
    - The problem here isn't that `tmux` won't propagate OSC 633. VSCode's integration script won't run at all.
  - A variation of the above: If you have zsh as login shell and have this at the top of `~/.zshrc`:
    ```zsh
    if [[ -z ${TMUX+X}${ZSH_SCRIPT+X}${ZSH_EXECUTION_STRING+X} ]]; then
      exec tmux
    fi
    ```
- Shell integration adds lag after each command. https://github.com/romkatv/zsh-bench on my machine shows that VSCode's shell integration increases *command lag* by 30ms. This is 300% of the maximum lag that separates fast prompt from slow. In other words, this is number is large and the lag is detectable by the naked eye.
- Shell integration doesn't work if `ZDOTDIR` is set in the global `zshenv`.
- Shell integration breaks shell if `~/.zshenv` sets `ZDOTDIR`.
- `precmd` and `preexec` hooks are invoked twice.
- Breaks when user rc files define `precmd` or `preexec` (this is fairly common).
- Breaks when user rc files define `update_prompt`, `command_complete` or similar. These names aren't special but they look reasonable enough to have a chance of being defined, which would cause a clash.
- Breaks when user rc files define aliases for things like `history` or global aliases for things like `-n`.
- Breaks when `no_unset` is enabled.

Many users will bump into one or more of these. For shell integration to be useful, it needs to work reliably.

Is there documentation explainign how VSCode uses these marks? E.g., what does it do with right prompt markup? It's likely that there are more bugs in the integration code but to be sure I would need to know what it's supposed to do. This would also allow me to implement correct shell integration for VSCode in powerlevel10k.

Is there a reason VSCode is using OSC 633 instead of the de facto standard OSC 133 and OSC 7? If it used the latter, zsh users would be able to enable shell integration via the same means they enable it for other terminals. E.g., in powerlevel10k it would be enough to define `POWERLEVEL9K_TERM_SHELL_INTEGRATION=true` and in zsh4humans `zstyle ':z4h:' term-shell-integration yes` would do the trick.

It would be really nice if VSCode's shell integration had two features:

- A special variable that signifies that VSCode is attempting to enable shell integration. For example, `VSCODE_SHELL_INTEGRATION=1`. It has to be set at the very beginning so that user rc files can see it.
- A way for user rc files (primarily `zshrc`) to opt out of VSCode shell integration. One way would be for the integration code to check `VSCODE_SHELL_INTEGRATION` after sourcing user rc files. If user rc files unset it, they don't want shell integration.

If these features were implemented, powerlevel10k (and other themes that cannot be supported by the generic VSCode shell integration script), would enable their own VSCode shell integration if `VSCODE_SHELL_INTEGRATION` is set and would opt out from the generic integration code.

**Comment by Tyriar** [comment]
@romkatv thanks for checking it out, this feedback is all extremely valuable! Responses below.

> If you manually run zsh in an existing interactive shell.

Subshells don't work right now, this is tracked in https://github.com/microsoft/vscode/issues/141343. It should degrade gracefully and treat the subshell as a single command (unless you try to run shell integration in the subshell which won't work).

If you want a shell-integration enabled shell you can use one of the other VS Code profiles.

> If you restart zsh with exec zsh

This is the subshell case again. Isn't `. ~/.zshrc` the more common and superior way to do this?

> If you SSH to a remote host with zsh as login shell.

This is the subshell problem again, shell integration should be enabled on Remote - SSH connected windows though.

> If you have tmux as login shell and configure it to start zsh. The problem here isn't that tmux won't propagate OSC 633. VSCode's integration script won't run at all.

I hadn't tested tmux yet and find it surprising that they wouldn't pass 633 through, they don't understand it so shouldn't be disposing of it? But anyway, tmux runs in the alt buffer where command decorations wouldn't show up, I'm not sure we should be aiming to support tmux at all (vscode's reconnect/panes mostly replaces the tmux functionality for most users).

> Shell integration adds lag after each command.

We should look into this #145576, our focus has been making it work rather than making it fast. @meganrogge ran the benchmark and couldn't see a noticeable difference in runtime.

> Shell integration doesn't work if ZDOTDIR is set in the global zshenv.
> Shell integration breaks shell if ~/.zshenv sets ZDOTDIR.

Need to investigate: #145578

> precmd and preexec hooks are invoked twice.

Need to investigate: #145579

> Breaks when user rc files define precmd or preexec (this is fairly common).

Need to investigate: #145580

> Breaks when user rc files define update_prompt, command_complete or similar. These names aren't special but they look reasonable enough to have a chance of being defined, which would cause a clash.

We should make these names more unique like in the pwsh script: #145584

> Breaks when user rc files define aliases for things like history or global aliases for things like -n.

Good observation, we should check the aliases and handle it accordingly: #145580

I'm not sure what you mean by a global alias for `-n`?

> Breaks when no_unset is enabled.

Need to investigate: #145581

> For shell integration to be useful, it needs to work reliably.

I agree, the current approach we're taking if the setting is enabled is to verify both before we launch the shell and after that everything looks good and if not disable it with a warning. We want to enable it by default eventually but it needs to be rock solid.

> Is there documentation explainign how VSCode uses these marks?

Not yet as the marks aren't set in stone yet, we want the flexibility to be able to tweak it as needed at least until we declare the feature non-experimental. You can read about the full protocol to date here, everything's purpose is subject to change but the plan is to keep everything under OSC 633:

https://github.com/microsoft/vscode/blob/14ad945c42c0063598417877ba6eb38c28ff6fc0/src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts#L19-L116

> what does it do with right prompt markup?

RPROMPT support was just added recently and isn't available in the stable version yet. Currently it works similarly to `$PS1`:

https://github.com/microsoft/vscode/blob/14ad945c42c0063598417877ba6eb38c28ff6fc0/src/vs/workbench/contrib/terminal/browser/media/shellIntegration.zsh#L69-L72

> Is there a reason VSCode is using OSC 633 instead of the de facto standard OSC 133 and OSC 7? 

The reason is we needed a richer protocol than what exists for the things that we want to accomplish, like best-in-class Windows/pwsh support, native-autocomplete, the ability to extract as accurately as possible the command position and anything else that comes up in the future.

Taking final term or iterm's code and extending it doesn't seem like a great thing to do, and adding some in a vscode-specific sequence to extend is was getting very messy. I also found [fig](https://fig.io/)'s sequences were confusing our shell integration so it felt safer and more reliable to own the whole protocol.

> A special variable that signifies that VSCode is attempting to enable shell integration. For example, VSCODE_SHELL_INTEGRATION=1. It has to be set at the very beginning so that user rc files can see it.

Great idea :+1: #145582

> A way for user rc files (primarily zshrc) to opt out of VSCode shell integration. One way would be for the integration code to check VSCODE_SHELL_INTEGRATION after sourcing user rc files. If user rc files unset it, they don't want shell integration.

This seems reasonable and plays nicely with our approach of disabling at first sign that something is wrong. I think we would still want to output a warning to the terminal in this case though as the user would expect shell integration to work, something like:

> Shell integration was disabled by the shell

:+1: #145583

**Comment by Tyriar** [comment]
> Can you clarify? Let's say I want to create a temporary zsh session with CC=clang. Normally I would run CC=clang zsh, run a bunch of commands there and finish with exit to go back to my normal shell. How can I do this and still have shell integration in the subshell?

For the case of setting a temporary variable like that you'd need to wait on the subshell support. I meant this if you just wanted to drop into a different shell:

![image](https://user-images.githubusercontent.com/2193314/159332956-5d2e3c2f-e265-4a45-a03c-5bef21add400.png)

> No, it's not. exec zsh doesn't create a subshell.

Ah you're right, good to know. It may not be possible to support this with our current model of injecting shell integration rather than manually installing it. We're trying to get as many users to be able to reap the benefits by avoiding the need to install. This may be one of those cases where you need to manually install the script to get it to work (documentation is yet to be written on this).

> No, . ~/.zshrc is different and it should never be executed.

I'm mostly a bash user where sourcing `~/.bashrc` or `~/.bash_profile` is fine since the scripts are typically idempotent. I guess it changes when you bring in the complexity of oh-my-zsh and all its plugins.

> When you SSH to a remote host with zsh as login shell, there are no subshells. The shell on the remote machine is a login shell and it has SHLVL=1.

From the terminal's perspective it is essentially a sub-shell though (remote zsh running inside local zsh).

> Can you clarify? Is there a way to make it work?

We have a remoting feature that allows you to connect an entire window to a remote via ssh: https://code.visualstudio.com/docs/remote/ssh

> FWIW, other terminals that have shell integration usually supply you with a file that one can source on the remote shell. Doing that enables shell integration. This is the same file that can be sourced locally of course. If VSCode provided a file of this kind, it would solve the bulk of problems I mentioned.
>
> ...
>
> I'm positive that it's impossible to implement generic shell integration that will work with all zsh configs out there.

This is the plan eventually, remember the feature is still experimental. The eventual solution to https://github.com/microsoft/vscode/issues/141343 will probably look like:

- Investigate whether we can inject shell integration automatically (I have doubts here)
- Provide documentation for installing shell integration manually for advanced use cases (sub shells, `ssh` in a local session, etc.)
- Have each command specify a "shell ID" to be able to detect which shell the command is running within

My main concern with providing this documentation now is that shell developers may take that as an indicator that the used escape sequences are set in stone which they aren't yet.

> Users can do it themselves if you document the protocol (OSC 633). I use tmux and zsh and enjoy shell integration in all terminals that support OSC 133 and OSC 7.

I guess I need to play with other terminals where shell integration works in tmux. Since tmux runs in the alt buffer the command decorations will need to get invalidated when any scroll events occur for example and decorations in the scroll bar wouldn't work since tmux owns the scrollback not VS Code. This feature is the scroll bar feature only in insiders build:

![image](https://user-images.githubusercontent.com/2193314/159335747-1aa3f866-f632-4492-a521-c7170e24491e.png)

There is also a request to support iterm2 like tmux integration. Not sure how much of this would be in that vs shell integration: https://github.com/microsoft/vscode/issues/73937

> I want to be optimistic but I fear that you might be underestimating the difficulty of extracting information from zle output. You cannot, for example, extract the command that is being executed. It is trivial, however, to send the command from zsh to the TTY before it starts executing (similarly to how you send PWD).

We're aware it's tough. It's nearly impossible to do this on Windows for example and actually resend the full command line in an OSC 633 sequence to workaround that since Windows ptys via conpty write escape sequences it doesn't recognize in the "rendering phase", meaning the position they fire isn't guaranteed to be correct. If we need to do this for other shells we have that option available.

Currently for zsh and bash we create a model based on command start/end, rprompt start/end, continuation start/end sequences and read the command out on preexec.

> Keep in mind that prompt can be drawn several times for the same command, and each time it can be different (including different height). Right prompt can appear and disappear while the command is being edited.

It's in a fairly good state in the Insiders build now, I'm expecting we'll be fixing a long tail of issues for a while due to the diversity in shell setups. Right prompt support is very new though.

**Comment by romkatv** [comment]
> Currently for zsh and bash we create a model based on command start/end, rprompt start/end, continuation start/end sequences and read the command out on preexec.

I'm afraid this won't work for zsh in the real world. You can make it work for simple cases but it'll break often enough to render this feature unreliable. The command doesn't even have to appear on the screen. Try running `setopt single_line_zle` and then enter a long command (wider than the TTY). A similar thing happens in a multi-line zle when the command is taller than `LINES`.

By the way, zsh users are capable of cloning a git repo and adding one line to `~/.zshrc` that sources a file from it. The whole zsh plugin ecosystem is built around this model. If you provide the said repo, using it will be easy. On the other hand, if you play the game of injecting zsh code into user shell in subtle ways, you might open a can of worm of gargantuan size.

> I'm mostly a bash user where sourcing `~/.bashrc` or `~/.bash_profile` is fine since the scripts are typically idempotent.

Idempotent isn't enough. Say you have `shopt -s globstar` in your `~/.bashrc` and then you decide to remove it. `exec bash` will correctly apply your change but `source ~/.bashrc` won't.

Configs that utilize `PROMPT_COMMAND` are often not idempotent and will make your shell slower and slower every time you re-source rc files.

Virtually all bash rc configs I've seen append/prepend stuff to `PATH` and similar env vars. This isn't idempotent albeit the negative side effects are subtle (gradual perf degradation).

The good news is that you don't need to worry about these issues. Simply never resource rc files manually. You'll save on typing, too. There is no trade off. `exec bash` is just better all around.
