### ISSUE TITLE
git

### ISSUE THREAD

**Issue by venuraj1242** [microsoft/vscode#142088]
Issue Type: <b>Bug</b>

source control not working

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (1.10GB free)|
|Process Argv|--crash-reporter-id 038225a8-1605-4f38-aa3f-5e0575867afb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
code-runner|for|0.11.6
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.5
cpptools|ms-|1.7.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vscop453:30404998
vsrem710cf:30416617

```

</details>

**Comment by lszomoru** [comment]
@venuraj1242, could you please share some more information of what is not working? Thanks!

**Comment by venuraj1242** [comment]
> @venuraj1242, could you please share some more information of what is not working? Thanks! 

Sir now it is working properly thank you

**Comment by lszomoru** [comment]
@venuraj1242, thank for the update. Closing the issue.
