### ISSUE TITLE
Duplicated SCM action buttons on changed file

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#142024]
Issue Type: <b>Bug</b>

I am connected to a repo via GitHub Remote.

Hovering a file in SCM and the title bar shows some actions twice.

<img width="190" alt="image" src="https://user-images.githubusercontent.com/8599/152210119-b3e0014e-3349-4bfa-9da2-b08fac9c6d31.png">

VS Code version: Code - Insiders 1.64.0-insider (4ccfe1100c3c5625804dbc20afd15ba311487883, 2022-02-02T03:02:18.591Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (0.02GB free)|
|Process Argv|--enable-proposed-api donjayamanne.kusto --log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
tsl-problem-matcher|amo|0.5.0
emojisense|bie|0.9.0
github-markdown-preview|bie|0.1.0
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
vscode-github-actions|csc|0.22.0
postcss|css|1.0.9
kusto|don|0.3.8
typescript-notebook|don|2.0.6
prettier-vscode|esb|9.2.0
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
codespaces|Git|1.5.1
copilot|Git|1.7.4812
remotehub|Git|0.23.2022020109
vscode-pull-request-github|Git|0.34.3
restore-git-branch-tabs|gko|0.4.1
headwind|hey|1.7.0
gzipdecompressor|Hyu|1.2.0
theme-monokai-pro-vscode|mon|1.1.20
python|ms-|2022.1.1779589815-dev
vscode-pylance|ms-|2022.1.6-pre.1
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.218.0
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
azure-account|ms-|0.9.11
vsliveshare|ms-|1.0.5330
debugger-for-edge|msj|1.0.15
vscode-commons|red|0.0.6
vscode-xml|red|0.18.2
smart-css-autocomplete|sai|1.5.3
mdx|sil|0.1.0
msft-todo-unofficial|tyl|0.0.17
glean|wix|5.2.2
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30421357
vs360:30404995
vsclayoutctrt:30405800
azactmsal:30409287
pythonvsnew555:30426298
vscscmwlcmc:30428972

```

</details>

**Comment by joyceerhl** [comment]
Yeah, the dialog action will only uninstall Insiders and install pre-release, but doesn't force a reload, which is not ideal.

**Comment by joyceerhl** [comment]
Closing as `github.remotehub-insiders` has been deprecated for 8 months now.
