### ISSUE TITLE
Filter on Extensions Viewlet is not working properly (Desktop - Stable)

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#142096]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.63.3
- OS Version:MacOS Big Sur

Steps to Reproduce:

I'm trying open the Extensions Viewlet with multiple `extensionId` (using the `workbench.extensions.action.showExtensionsWithIds` command) and it is not working properly on VS Code Desktop - Stable Release.

1.I need to open the Extensions Viewlet with a pre-defined filter, which will be the list of extensions I want to search.
2.I found the `workbench.extensions.action.showExtensionsWithIds` command, which seems the be the best fit for this task
3. Call it with two extensions as argument, like:
```ts
    commands.executeCommand("workbench.extensions.action.showExtensionsWithIds", ["alefragnani.delphi-keybindings", "alefragnani.delphi-themes"]);
```
4. The Extensions Viewlet is show, but only one extension is displayed/found.
5. If you look at the filter, it shows `@id:alefragnani.delphi-keybindings @id:alefragnani.delphi-themes`
6. Notice that it uses an empty space, between each extensionId provided.
7. This is caused by this code: https://github.com/microsoft/vscode/blob/f933065f5382cba924c636bb60884389e5388429/src/vs/workbench/contrib/extensions/browser/extensionsActions.ts#L2707

The issue **occurs** on **VS Code Desktop - Stable release** only

The issue **does not occurs** on: 
* VS Code Desktop - Insiders release
* GitHub.dev - Stable / Insiders versions
* vscode.dev - Stable / Insiders versions

I thought it would be a _stable release issue_, but as you can see, both _web-versions_ are working, so it seems to be something else.

Thank you

**Comment by sandy081** [comment]
It works for me in stable

![image](https://user-images.githubusercontent.com/10746682/153084480-27282299-4b4b-4e39-b436-f988d9a9330b.png)

May I know what are you seeing when you apply this filter?

**Comment by alefragnani** [comment]
I guess I found the _real_ issue. 

The problem occurs because **one extension is installed, not both (or none)**. If I install both or uninstall both, it works, just like you tested.

Today, it only shows `delphi-themes` extension (which is installed)

![Screen Shot 2022-02-08 at 19 44 29](https://user-images.githubusercontent.com/3781424/153088484-1177c66b-4e61-4303-9224-d8907d4f2905.png)

If I search for `delphi-keybindings` alone, it displays

![Screen Shot 2022-02-08 at 19 44 43](https://user-images.githubusercontent.com/3781424/153088586-ba673ffc-3404-4d83-a4be-02fd77e46e8a.png)


Hope this helps

**Comment by sandy081** [comment]
To verify:

- Install `eamodio.gitlens` extension
- **Do not** install `dbaeumer.vscode-eslint` extension
- In Extensions View search for `@id:dbaeumer.vscode-eslint @id:eamodio.gitlens`
- Make sure both extensions are shown
