### ISSUE TITLE
Trust No One

### ISSUE THREAD

**Issue by ajorg-aws** [microsoft/vscode#142015]
I review a lot of code projects using VS Code, and I'm not inclined to trust any of it. So while I get why there's a popup asking me if I want to trust something, I wish there were an option to say never, or no to everything under specific paths, so that I didn't have to click through the dialog every time I open a new project (often several times a day). My use case is unusual but not entirely rare. Security engineers likely do similar things, and there are surely also many developers that prefer to not let their IDE trust anything ever.

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/126311

**Comment by ajorg-aws** [comment]
Ah. Thanks! I did *try* to find an already open issue, but I failed to hit on the right search terms.
