### ISSUE TITLE
Git push hangs when authentication fails

### ISSUE THREAD

**Issue by pwright08** [Microsoft/vscode#14208]
- VSCode Version: 1.6.1
- OS Version: OS X Yosemite 10.10.5

When I try to push to a repo I am not authorised to, the git wheel keeps spinning and a reason is not output.

Steps to Reproduce:
1. Set up two-factor authentication on your github account, for a remote you are using https to connect to
2. Try to push a commit

Can get around this by fixing authentication issue, which can be discovered using the git CLI.

**Comment by roblourens** [comment]
An auth window is supposed to pop up on top of Code in this case. Can you check if it's under the Code window or something?
