### ISSUE TITLE
Unable navigate to file from "Errors and Warnings" when errors occur in TypeScript.

### ISSUE THREAD

**Issue by liandaoacc** [Microsoft/vscode#1420]
I followed [Transpiling TypeScript into JavaScript](https://code.visualstudio.com/docs/languages/typescript#_transpiling-typescript-into-javascript), and got an error **Unable to open 'HelloWorld.ts': File not found (e:\SoftwareProgram\Test\E:\SoftwareProgram\Test\HelloWorld.ts)** in step 4 when I clicked on the problem. I report this because I think it should open **HelloWorld.ts**. Am I right?
My version is 0.10.3, and my OS is windows 7.

**Comment by dbaeumer** [comment]
@liandaoacc this works for me. Here is what I see:

![capture](https://cloud.githubusercontent.com/assets/1931590/11873491/256cb128-a4db-11e5-8f7c-c0806add4a68.png)

From the error message I think there is a setup issue telling the tsc compiler to produce errors with absolute paths. Which version of tsc are you using. And can you please run tsc from a command prompt and provide the output.

**Comment by liandaoacc** [comment]
@dbaeumer I changed the path of TEST and still got the error. 

**Error** Unable to open 'HelloWorld.ts': File not found (f:\TEST\F:\TEST\HelloWorld.ts). **Create File** **Cancel**

(I failed to attach image. Github show: *Something went really wrong, and we can't process that file.*)

I installed tsc using **npm install -g typescript**, here is my tsc path and tsc version. 
And I can run tsc from cmd to provide the output.


    F:\TEST>npm list -g
    C:\Users\liandaoacc\AppData\Roaming\npm
    └── typescript@1.7.3
    
    F:\TEST>tsc -V
    Version 1.0.3.0
    
    F:\TEST>tsc HelloWorld.ts
    
    F:\TEST>tsc HelloWorld.ts
    F:\TEST\HelloWorld.ts(3,17): error TS2094: The property 'logg' does not exist on
    value of type 'Console'.

**Comment by egamma** [comment]
@aeschli is covered by the fix you did with Dirk yesterday for 0.10.5?

**Comment by aeschli** [comment]
@egamma No, that fix was not related to paths.

**Comment by dbaeumer** [comment]
@liandaoacc can you provide me with the workspace that shows the problem (e.g as a public git repository). I can't reproduce this on WIndows using VSCode 0.10.6 and tsc version 1.7.5

**Comment by liandaoacc** [comment]
@dbaeumer I tried many times in VSCode 0.10.5 and then update to 0.10.6, and finally I found how I produced this problem in both version.
- **Workspace**  
My workspace is very easy, the directory is 
```
./HelloWorld  
./HelloWorld/.vscode  
./HelloWorld/.vscode/tasks.json  
./HelloWorld/HelloWorld.ts
```
and the codes in files are  
`./HelloWorld/.vscode/tasks.json`  
```json
{
	"version": "0.1.0",
	"command": "tsc",
	"isShellCommand": true,
	"showOutput": "silent",
	"args": ["HelloWorld.ts"],
	"problemMatcher": "$tsc"
}
```
`./HelloWorld/HelloWorld.ts`  
```javascript 
class Startup {
    public static main(): number {
        console.logg('Hello World');
        return 0;
    }
}
```

- **To produce the problem**  
**case 1**: before compiler the **HelloWorld.ts** .  
**case 2**: after compiler the **HelloWorld.ts**, simply pressing `Ctrl+Shift+B` (Run Build Task).  

After some tries, I noticed that the VSCode showed me error message in **case 1**. I did not notice this before. The error message is **Property 'logg' does not exist on type 'Console'**. And I could click on this problem to navigate to **HelloWorld.ts**. 
After I pressed `Ctrl+Shift+B`(**case 2**), another message came. That is **The property 'logg' does not exist on type 'Console'**. Please pay attention to these two message. They are different(the word **The**). I could not click on this problem to navigate to **HelloWorld.ts** and the error **Unable to open 'HelloWorld.ts': File not found (e:\SoftwareProgram\Test\javasrcipt\TypeScript\HelloWorld\E:\SoftwareProgram\Test\javasrcipt\TypeScript\HelloWorld\HelloWorld.ts).** came.  
Sometimes VSCode showed me two error message, **Property 'logg' does not exist on type 'Console'** and **The property 'logg' does not exist on type 'Console'** in **case 2**. But sometimes just **The property 'logg' does not exist on type 'Console'**. 

Since I failed to attach image, so I will reply the email to send some error message images.

**Comment by liandaoacc** [comment]
@dbaeumer Sorry, I found I can't reply the email directly. So if you need the image, please let me know.

**Comment by dbaeumer** [comment]
@liandaoacc The different error message come from the fact that in case1 the message comes from the internal language service where the second comes from the external tsc compiler. However in both cases you should be able to navigate to the file containing the error. 

The problem is actual a very old version of the tsc compiler that is install on your system. tsc -V reports Version 1.0.3.0 on your system (this version reports file names as absolute paths). It should be at least 1.6.x or higher (which report file names as relative paths). I guess that a long time ago you install the tsc compiler through Visual Studio as an executable which now has preference over the npm module. In a command prompt type where tsc to validate this. I am pretty sure it will not take tsc from AppData\Roaming\npm\tsc. 

You can either uninstall the old version of tsc (recommended) or if you really want to use that version of the compiler tweak the tasks.json file to instruct VS Code to use absolute paths from the compiler. 

```json
{
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "showOutput": "silent",
    "args": ["HelloWorld.ts"],
    "problemMatcher": {
        "base": "$tsc",
        "fileLocation": "absolute"  
    }
}
```

**Comment by felixfbecker** [comment]
I have the exact same problem with eslint:

![image](https://cloud.githubusercontent.com/assets/10532611/12521660/30167838-c14c-11e5-8eef-b7a5d2004935.png)

tasks.json:
```json
{
  "version": "0.1.0",
  "command": "npm",
  "args": ["--loglevel", "silent", "run"],
  "isShellCommand": true,
  "showOutput": "silent",
  "tasks": [
    {
      "taskName": "lint",
      "problemMatcher": "$eslint-stylish"
    }
  ]
}
```
Setting the problem matcher with fileLocation: absolute works, but imo this should not be needed. I have the latest eslint version installed so $eslint-stylish should set this automatically.

**Comment by egamma** [comment]
@felixfbecker this looks like a different issue. I've extracted this into a separate issue #2202
