### ISSUE TITLE
HotExit does not work on some instances of VSCode

### ISSUE THREAD

**Issue by Keyacom** [microsoft/vscode#142021]
Issue Type: <b>Bug</b>

1. Make sure the Hot Exit setting is not `off`, and the Auto Save setting is `off`.
2. Open two instances of VSCode.
3. Open a folder in at least one of them.
4. Write something in a new file in both windows.
5. Try closing both windows and see if the save prompt appears.
6. Reopen both windows and see if the file was kept.

Screenshots are below to not clutter space too much.

<details>
<summary>Screenshots for step 1</summary>

![image](https://user-images.githubusercontent.com/70766223/152200445-be2b305e-876a-4a74-bd5b-b3ad19266488.png)
![image](https://user-images.githubusercontent.com/70766223/152200624-b4b769e1-88cc-442e-9da1-ed72d62ba177.png)
</details>
<details>
<summary>Screenshot for step 2</summary>

![image](https://user-images.githubusercontent.com/70766223/152201238-d17bf840-7068-438d-9de4-6cc1019bd04e.png)
</details>
<details>
<summary>Screenshot for steps 3 and 4</summary>

![image](https://user-images.githubusercontent.com/70766223/152201485-2848b897-a400-4efb-b3b4-28f4a8eed9a1.png)
Note the different colors of the bottom bar.
</details>
<details>
<summary>Screenshots for step 5</summary>

![image](https://user-images.githubusercontent.com/70766223/152203299-478badb6-4bcb-4cbc-bc5c-2916a054a5c7.png)
![image](https://user-images.githubusercontent.com/70766223/152203315-905c4dc3-de4a-47d8-969f-99f6b7e9ba81.png)
Pay attention to which window has a red "close" button.
</details>
<details>
<summary>Screenshot for step 6</summary>

![image](https://user-images.githubusercontent.com/70766223/152203439-51f0b7c7-5e0d-415e-9e3c-a4f0742eab57.png)
</details>

**Expected behavior**: Both instances should close without save prompts and have all files in them backed up.
**Actual behavior**: Both instances show save prompts before closing. Only the one without a folder open had all its unsaved changes lost. If both windows have folders open, their changes are entirely lost no matter what.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.05GB free)|
|Process Argv|--crash-reporter-id 57c06a69-98ac-4fc4-8225-c3db59f39ccc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-pl|MS-|1.63.3
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.5
jupyter|ms-|2021.11.1001550889
open-in-github-desktop|wra|1.4.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vscop341:30404997
vsrem710:30416614

```

</details>

**Comment by bpasero** [comment]
I cannot reproduce. I have configured:

```json
"files.hotExit": "onExitAndWindowClose"
```

And I can close a window by clicking on the X without prompt. When I then start again, only the one window restores. This is actually working as intended, we only restore empty windows with unsaved changes because there is no other way of getting back to the workspace. For folders, you can always get back easily by opening the folder again. And the list of recently opened indicates folders with unsaved changes with a dot:

![image](https://user-images.githubusercontent.com/900690/152220001-03b8efd1-92ea-4527-a47b-977643dd8a65.png)
