### ISSUE TITLE
Please bring back ability to move terminal to the RIGHT of the editor

### ISSUE THREAD

**Issue by gotofritz** [microsoft/vscode#142075]
I have always had the panel vertically, to the right of the editor, between editor and sidebar (which I keep to the right). Now with the latest version of insiders it was automatically arranged horizontally. When I right click on the title bar, the only option is a toggle between "Move views to the side" and "Move views to Panel". First of all - what does it even mean? I am trying to move the Terminal, not some weird thing called "views". And what does it mean "move to the Panel"?? Sounds like some weird, unintuitive abstraction. I don't think it helps at all. 

Most importantly, when I move the Term... sorry, the "Views" to the side, it only allows me to the move it to the left. Why remove the ability to move it to the right? It's something that we were able to do for years. What problem are you trying to solve?

And if I move the Term... sorry, the "Views" to the side, then hide it... how do I get it back? The old CMD-J brings up an empty space where the Terminal used to be... the Te.. "Views" is nowhere to be seen. Can you show me a use case where that kind of behaviour would be useful?

If I then do "Terminal > New Terminal" I get a terminal - as a editor tab. So YET ANOTHER place for a terminal. It's not the same terminal I had before - that presumably is still around. Somewhere. 

AAAAARGGGH

I am confused by the changes, which seem totally unnecessary and do not solve any problems. And I am irritated because I am no longer able to use VSC the way I have for years, for what to me looks like an arbitrary decision.

I hope future iterations will bring some of the old functionality back, while avoiding unnecessary abstractions. Thanks.

**Comment by jasonvarga** [comment]
I'd like to know if this is possible too.

Previously I would have my layout like this:

```
|-----------------------|----------|----------|
| editor(s)             | terminal | explorer |
|-----------------------|----------|----------|
```

Depending on whatever other applications I happened to be working on, I had a keyboard shortcut to toggle the terminal to/from the bottom/side so it would change to this:

```
|----------------------------------|----------|
| editor(s)                        | explorer |
|----------------------------------|          |
| terminal                         |          |
|----------------------------------|----------|
```

This workflow worked great for me.

Now it seems like there's only the ability to move the terminal into the "side panel", which seems like it's only ever the opposite side as the side bar. I can't have the "side bar" and the "side panel" on the same side.

**Comment by adam-arold** [comment]
@gotofritz what happened is that the devs got **sloppy** and they just took that functionality away. You can try to run it by hand from the commands panel and you'll get

> Moving the panel with this command has been deprecated in favor of the "Move Views From Panel To Side Panel" and "Move Views From Side Panel To Panel" commands.

They came up with this sidebar thing without thinking twice about all the workflows that **they are breaking** with this nonsense.

**Comment by adam-arold** [comment]
What makes this even worse is that you can maximize the *Panel* (the thing that's in the bottom by default and held all your tabs including the terminal) but you **can't maximize** the side bar! What I've been doing is that I had my terminal on the right side and I could toggle between invisible, visible, and maximized with a keyboard shortcut. It is very useful if you're running tmux for exmaple (or things like mc) in your terminal and you quickly want to jump between coding and doing stuff in a maximized terminal.

Whoever did this to VS Code please **undo it**.

**Comment by adam-arold** [comment]
@gotofritz my suggestion is to opt-out of automatic upgrades and downgrade to `1.63`, you can grab it from [here](https://code.visualstudio.com/updates/v1_63).

**Comment by gotofritz** [comment]
> @gotofritz my suggestion is to opt-out of automatic upgrades and downgrade to 1.63, while they fix this (or roll back the broken version), you can grab it from [here](https://code.visualstudio.com/updates/v1_63)

@adam-arold Sure, but that would only be delaying the inevitable for another month or so, wouldn't it? I'd rather be part of the conversation. Perhaps if enough users let them know their fiddling is unhelpful, they may revisit their roadmap!

**Comment by adam-arold** [comment]
> @adam-arold Sure, but that would only be delaying the inevitable for another month or so, wouldn't it? I'd rather be part of the conversation. Perhaps if enough users let them know their fiddling is unhelpful, they may revisit their roadmap!

I agree with that, but it is broken **now** and I want to work **now**. I can't wait for them to fix this, unfortunately.

**Comment by daviddossett** [comment]
cc @lychung7

**Comment by sbatten** [comment]
feedback here is noted... please continue discussion in this issue  #141349
