### ISSUE TITLE
When setting the state of a TestRun more than once, the last one wins, not the "most failed" one

### ISSUE THREAD

**Issue by stefanhaller** [microsoft/vscode#142028]
- VS Code Version: 1.64.0-insider (4ccfe1100c3c)

In the Catch2 C++ test framework it is possible to have multiple test results for the same test in one run. This happens for example for the following code:
```
TEST_CASE("T")
{
  SECTION("S")
  {
    auto value = GENERATE(3, 7);
    CHECK(value == 7);
  }
}
```
In this scenario, the section "S" is run twice, and the first time it fails, the second time it succeeds.

The C++ TestMate extension will see the two test runs, and call `TestRun.failed` for the first one, and `TestRun.passed` for the second, _with the same `TestItem`_ for both calls. This results in the confusing display that the section is green, even though it shows a failure inside:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/1225667/152218740-80fa64e1-4a53-4c8b-8fd2-78d053fcee09.png">

@connor4312, does it make sense to change `failed()` and `passed()` (et al) so that when called multiple times, it sets the item's state to the max of the old and the new state? This seems to be analogous to what happens with the test messages (they are appended, and `passed()` doesn't clear them).

Or would you say it's the extension's responsibility to not set the state more than once for a given TestItem? (Cc @matepek)

Or maybe it is even Catch2's responsibility to accumulate the results for any section that is run more than once?

**Comment by matepek** [comment]
IMHO,
Catch2 reports it and definitely not the responsibility of vscode. It leaves it to me..

**Comment by stefanhaller** [comment]
> and definitely not the responsibility of vscode

Why definitely? It doesn't seem so unreasonable to me. As I said, it already does something similar with the test messages.

**Comment by matepek** [comment]
As I think of it, vscode part is just the UI, the controlling is in my hand.

**Comment by stefanhaller** [comment]
I'm not so sure in this case. VS Code is also responsible for setting T's state correctly, you don't do that at all (as far as I'm aware). And note that it gets that one right, so it has some logic already for computing the resulting state of all child runs if there are multiple for the same item.

**Comment by stefanhaller** [comment]
@connor4312 I would be very interested in your opinion on this.

**Comment by connor4312** [comment]
Yea, I think it would be reasonable to no-op if the extension tries to change the test state to one with a lower priority. For instance, going from passed->skipped or failed->passed.

**Comment by TylerLeonhardt** [comment]
@connor4312 can you add some steps?

**Comment by connor4312** [comment]
1. Use the test sample: https://github.com/microsoft/vscode-extension-samples/tree/main/test-provider-sample
2. Modify this block https://github.com/microsoft/vscode-extension-samples/blob/2feab6d8f185417e63eaef73b38dae36a6a5dafb/test-provider-sample/src/testTree.ts#L107-L113

```
    if (actual === this.expected) {
      options.enqueued(item);
      options.passed(item, duration); // overwrite
      options.enqueued(item); // should no-op
    } else {
      const message = vscode.TestMessage.diff(`Expected ${item.label}`, String(this.expected), String(actual));
      message.location = new vscode.Location(item.uri!, item.range!);
      options.failed(item, message, duration);
      options.passed(item, duration); // should no-op
      options.skipped(item); // should no-op
    }
```

3. Verify that, with these changes, test that should pass remain passed in the UI, and tests that failed remain failed.
