### ISSUE TITLE
too slow after starting up

### ISSUE THREAD

**Issue by abhmodi** [microsoft/vscode#142079]
Issue Type: <b>Performance Issue</b>

too slow after starting up since last 1 week. no major installations of extensions or anything esle

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.28GB free)|
|Process Argv|--crash-reporter-id 705adcc8-988f-4886-9846-6ba64e5f2dd6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   114	  8392	code main
    1	    81	   704	   shared-process
    0	    66	 16348	     watcherServiceParcelSharedProcess
    0	    66	 16600	     ptyHost
    0	     6	  7852	       console-window-host (Windows internal process)
    0	    54	 26352	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	  2120	   "C:\Program Files\Google\Drive File Stream\54.0.3.0\crashpad_handler.exe" --database=C:\Users\abhishek.modi\AppData\Local\Google\DriveFS\Crashpad --url=https://clients2.google.com/cr/report --annotation=application=Code.exe --annotation=prod=DriveFS --annotation=ver=54.0.3.0 --initial-client-data=0x15e8,0x1640,0x1634,0x1644,0x163c,0x7ffb649f0960,0x7ffb649f0970,0x7ffb649f0980
    0	    80	  5000	   issue-reporter
    0	   167	  7200	   gpu-process
    0	    37	 15984	   utility-network-service
    0	    23	 16392	   crashpad-handler
    0	    99	 22620	   extensionHost
    0	   203	 17484	     "C:\Users\abhishek.modi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\abhishek.modi\.vscode\extensions\ms-python.vscode-pylance-2022.1.5\dist\server.bundle.js --cancellationReceive=file:391f2222f714c22e277a7368aad898536887d4a2c1 --node-ipc --clientProcessId=22620
    0	   107	 20612	     "C:\Users\abhishek.modi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\abhishek.modi\.vscode\extensions\ms-python.vscode-pylance-2022.1.5\dist\server.bundle.js --cancellationReceive=file:6e77bb55ce25242edbd4e3ab7888a23fa37fb65550 --node-ipc --clientProcessId=22620
    0	    66	 28060	     "C:\Users\abhishek.modi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\abhishek.modi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=22620
    0	   166	 23352	   window (idv_offers.py - mcd_ta - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (idv_offers.py - mcd_ta - Visual Studio Code)
|    Folder (mcd_ta): 4373 files
|      File types: pkl(1163) parquet(1004) py(724) ipynb(544) pyc(124) png(98)
|                  R(97) yml(50) csv(34) rst(30)
|      Conf files: makefile(2);
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
sas-syntax|77q|1.0.8
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.5
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.63.13

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30428978
pythonvs932:30410667
vscop940:30404999
vsrem710:30416614
vscop841cf:30430978

```

</details>

**Comment by aeschli** [comment]
Check out https://github.com/microsoft/vscode/wiki/Performance-Issues for tips how to diagnose performance issues.

If it is the startup that is slow, can you create a startup CPU profile? It is described here: https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly

**Comment by abhmodi** [comment]
Thanks for the help. It got resolved
