### ISSUE TITLE
"Electron" and "Code help (renderer)" using all my CPU and not rendering my file

### ISSUE THREAD

**Issue by novitae** [microsoft/vscode#142036]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: macOS 11.1

Steps to Reproduce:

1. Open a python file that is more than 50 lines
2. There you go

I was coding python when suddenly this happened. My Mac starts overheating, and vscode stopped rendering color syntax for python.

![](https://i.imgur.com/knzQVPq.png)

So I looked at the task manager, and I saw:

![](https://i.imgur.com/kziIoO7.png)
(Electron, from `/Applications/Visual Studio Code.app/Contents/MacOS/Electron`, used 95% of my CPU)

10 minutes after doing nothing just listening to my Mac burning, all came back to normal.

![](https://i.imgur.com/hP1hdlX.png)
![](https://i.imgur.com/EirQjkG.png)

Then a single change of character in the file, and it's starting burning again.
So I downgraded to 1.62.3, and the EXACT same thing happened, but now, the process that was making burning my computer and not rendering anything was `Code helper (renderer)`.

![](https://i.imgur.com/ZB9EZsY.png)

🆘

**Comment by lramos15** [comment]
Have you tried disabling your extensions? This can be done with `--disable-extensions` CLI https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions

**Comment by novitae** [comment]
> Have you tried disabling your extensions? This can be done with `--disable-extensions` CLI https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions

This work in term of not making my computer burn, but it terms of render, I don't have the syntax highlight, and I want it because it is very diffult to code without.

![](https://camo.githubusercontent.com/e6a2729ac1a1b26afb09adc40de72d3b82043b3d8338b8bea84bc84f6b951742/68747470733a2f2f692e696d6775722e636f6d2f6b6e7a515650712e706e67)

**Comment by novitae** [comment]
Update: It seems that it is doing this bug for python files larger than a certain size.
A 13600 chars file is loading, but a 14700 chars file isn't loading (the size limit seems to be between these sizes).
Once the file too heavy has started to be launched, the bug will last until the end of the burning computer time (~10 min). And as I said, if I touch something in the too heavy file, its going again for 10 minutes.

**Comment by novitae** [comment]
It seems I'm not the only one having such issues, some people are complaining about it too.
A lot are telling it comes from a certain extension. After trying to disable one-by-one, it seems it is Pylance for me. Probably the most important I need for coding in python ...

**Comment by novitae** [comment]
[https://github.com/microsoft/pylance-release/issues/201#issuecomment-1025633961](https://github.com/microsoft/pylance-release/issues/201#issuecomment-1025633961) after all it might come only from pylance

**Comment by novitae** [comment]
It seems the problem will be fixed very soon
[https://github.com/microsoft/pylance-release/issues/2314](https://github.com/microsoft/pylance-release/issues/2314)
