### ISSUE TITLE
Time limit

### ISSUE THREAD

**Issue by apurvarawal** [microsoft/vscode#142068]
Please provide 2 modes for coding, 1 normal and 2nd competitive, in which there is difference of time limits.

**Comment by rebornix** [comment]
@apurvarawal can you elaborate what "2nd competitive, in which there is difference of time limits" means here? Are you referring to performance?

**Comment by apurvarawal** [comment]
Hello Peng Lyu,

What I meant by this line was, there is a fixed execution time in which
your code has to run on competitive coding sites, but on vs code, the
program can take time to run without any fixed time limit. So, can vs code
also inculcate such a feature so that if there is no internet connection by
chance for the competitive sites to run, the person can practice on vs code
itself?

It will be too useful if there can be 2 modes for coding on it.

The present vs code is great for beginners to motivate them that their code
is correct, even if takes too much runtime, but as a mediator, I feel that
the competitive coding mode can make vs code more productive.
