### ISSUE TITLE
Apparent recurrence of closed issue #104094 on pd dataframe displayed non-scrollable in ipynbs

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [microsoft/vscode#142029]
Does this issue occur when all extensions are disabled?: I don't think it would be possible to try to reproduce this without python&jupyter extensions?

- VS Code Version: 
```
Version: 1.63.2 (Universal)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```
- OS Version: Mac OS Big Sur version 11.6.1 (20G224)

Steps to Reproduce:

1. Run the following code in an `.ipynb` python code cell, with vscode window narrow enough not to display all columns
```
import pandas as pd
pd.set_option("display.max_columns", 50)
pd.set_option('display.width', 1000)
df = pd.DataFrame({"aaaaaa": [1,1,1,1], "bbbbbb":[2,2,2,2], "ccccccc": [3,3,3,3], "dddddddd": [4,4,4,4], "aaaaa": [1,1,1,1], "bbbbb":[2,2,2,2], "cccccc": [3,3,3,3], "ddddddd": [4,4,4,4], "aaaa": [1,1,1,1], "bbbb":[2,2,2,2], "ccccc": [3,3,3,3], "dddddd": [4,4,4,4]})
print(df)
```
2. Observe resulting table wraps instead of being html-table with scroll bar, as if it were printed in terminal.
<img width="660" alt="Screenshot vscode ipynb not formatting dataframe output correctly" src="https://user-images.githubusercontent.com/18562882/152228073-ef4582a2-7ee8-4a82-af0b-7993723425a1.png">

I've found at least two references to this issue popping up but being fixed and closed in 2020 (see e.g. https://github.com/microsoft/vscode/issues/104094 and https://github.com/microsoft/vscode/issues/103981), so am not sure how to proceed. This is my first macbook I've had in years, maybe this is a mac-specific issue?

**Comment by MaxPowerWasTaken** [comment]
my colleague who is on windows/wsl said today her vscode-ipynb dataframe output looks like this as well, so maybe not a mac-specific issue...

**Comment by hello-smile6** [comment]
> my colleague who is on windows/wsl said today her vscode-ipynb dataframe output looks like this as well, so maybe not a mac-specific issue...

Could be related to Unix/Linux. If it happened on WSL, that wouldn't be the Windows version.

**Comment by MaxPowerWasTaken** [comment]
ok this was user error (of course). If I use `display(df)` instead of `print(df)` it shows as expected.
