### ISSUE TITLE
Markdown math doesn't have Latex language scope

### ISSUE THREAD

**Issue by funnym0nk3y** [microsoft/vscode#142022]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest
- OS Version: Win10

When trying to create snippets for markdown it is very difficult to assess how scope works for that. If I understood the documentation correctly, the scope is determined and displayed on the lower right corner. But on the other hand when writing markdown vscode obviously detects yaml in the header as such and displays only yaml snippets. 
But when writing math and setting the scope of a snippet to tex or latex it fails to do so. 

Steps to Reproduce:

1. Create a snippet with scope tex and latex.
2. Create a snippet with scope yaml
3. Create a markdown document with yaml header and math section.
4. See all suggestions for the respective part of the document.

**Comment by mjbvz** [comment]
Can you please share an example of the snippet you are trying to create and a markdown code that explains how you expect this to work

**Comment by funnym0nk3y** [comment]
Sure. I created a example workspace snippet file: 

```json
{
	"markdown-snippet": {
		"scope": "markdown",
		"prefix": "snippet",
		"body": "markdown snippet",
		"description": "A markdown snippet"
	},
	"yaml-snippet": {
		"scope": "yaml",
		"prefix": "snippet",
		"body": "yaml snippet",
		"description": "A yaml snippet"
	},
	"math-snippet": {
		"scope": "tex, latex",
		"prefix": "snippet",
		"body": "math snippet",
		"description": "A math snippet"
	},
}
```

And a example markdown file with yaml header: 

```markdown
---
id: gwxMScgdpeyZab9SNmTqy
title: Test-File
desc: ''
updated: 1643838722839
created: 1643816012552
tags: 
     - test

---

Lorem ispum

$$

$$
```

Those are the snippets recommended by intellisense: 
In the `yaml` section just the yaml snippet gets shown, which is how I would expect it.
![grafik](https://user-images.githubusercontent.com/41870754/152332504-ce9a299e-25b9-4ffb-aecb-d54f2b239559.png)
In the `markdown` section jsut the markdown snippet gets shown, which is also how I would expect it.
![grafik](https://user-images.githubusercontent.com/41870754/152332558-4aeb818a-5485-46ee-b7a9-6cb6402b77ca.png)
In the `math` section however (which is tex or latex based afaik) just the markdown snippet gets shown, but not the math snippet. I'd expect the math snippet be shown and, depending on how one would like it maybe the markdown snippet. In my opinion the markdown snippet should not be shown. 
![grafik](https://user-images.githubusercontent.com/41870754/152332623-e92f235b-4f2e-40be-8283-1a1edca17ca5.png)
The documentation does not specify a scope for markdown math.

**Comment by mjbvz** [comment]
Thanks! 

Simply repo:

1. In md file, write: `$$\sqrt 2$$`
2. Use the `Developer: inspect tokens and scopes command` and see that the language inside the math equation is still `markdown`

**Comment by mjbvz** [comment]
@funnym0nk3y You can likely work around this by adding `markdown-math` to the list of scopes today

**Comment by funnym0nk3y** [comment]
@mjbvz I tried adding exactly that, so that my snippets looks like this: 

```json
{
	"markdown-snippet": {
		"scope": "markdown",
		"prefix": "snippet",
		"body": "markdown snippet",
		"description": "A markdown snippet"
	},
	"yaml-snippet": {
		"scope": "yaml",
		"prefix": "snippet",
		"body": "yaml snippet",
		"description": "A yaml snippet"
	},
	"math-snippet": {
		"scope": "markdown-math",
		"prefix": "snippet",
		"body": "math snippet",
		"description": "A math snippet"
	},
}
```

and it still does not work as expected. However the scope definitly says `markdown-math`.

**Comment by Lemmingh** [comment]
@mjbvz

I doubt whether it's correct to adopt `latex` in the commit 7987c49a081ca4608682afb43dc3b08260b14c98.

The "LaTeX math areas" in Markdown are basically a subset of the "math environments" of LaTeX which are a restricted proper subset of "LaTeX". Generally speaking, we only expect `amsmath` commands plus a few basic commands to exist in a math environment.

For concern about user experience, please see <https://github.com/yzhang-gh/vscode-markdown/issues/846#issuecomment-731700292>, and topics about "math environment" on the Internet.

**Comment by funnym0nk3y** [comment]
@Lemmingh So the issue is not that it does not have the `latex` scope, but the current scope `markdown-math` is not working properly?

**Comment by IanMatthewHuff** [comment]
I verified the change from 'markdown-math' in stable to 'latex' in the insiders release. @mjbvz seems like @Lemmingh had an additional comment on this change. Not sure if I have the full context on that.

**Comment by Lemmingh** [comment]
> an additional comment

I was expressing concern about the UX of this change, based on our experience at [Markdown All in One](https://github.com/yzhang-gh/vscode-markdown).

* The math mode of LaTeX is quite restricted. The current math renderer (KaTeX) limits the environment further. However, using the `latex` language scope allows any snippet defined for LaTeX to appear. Is it good to suggest general LaTeX templates in math areas inside Markdown documents?

* TextMate grammar can never accurately describe Markdown. Is it too risky to take advantage of the `embeddedLanguages` contribution point now to mark embedded languages?
