### ISSUE TITLE
Function breakpoints don't seem to be editable anymore 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#142010]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.0-insider (works on stable)
- OS Version: Windows 11

Steps to Reproduce:
1. Open the Run and Debug view
2. Click on the create a launch.json file link
3. Choose any config
2. Try to create a function breakpoint by clicking on the "+" sign in the breakpoints panel:
![FunctionBreakpointsBug](https://user-images.githubusercontent.com/45497113/152186202-f04cc932-36b4-497b-ad51-e4068f4564a6.gif)

**Comment by weinand** [comment]
@roblourens Yes, function breakpoints are broken. But I'm not aware of any changes in that area.

**Comment by roblourens** [comment]
@connor4312 https://github.com/microsoft/vscode/blob/bef5c27e4301148a5ead300fac204e746e7c8fe5/src/vs/workbench/contrib/debug/browser/media/debugViewlet.css#L245

**Comment by connor4312** [comment]
I think that CSS rule is no longer necessary, seems fine to remove it.

**Comment by roblourens** [comment]
Why was it originally necessary?

**Comment by connor4312** [comment]
I think it was just something I had in one iteration of getting the the inline actions in the Variables view to display correctly

**Comment by weinand** [comment]
Function breakpoints can be edited again in 1.64.2.
