### ISSUE TITLE
cant type anything

### ISSUE THREAD

**Issue by MohammadTaseenKhan** [microsoft/vscode#142018]
Issue Type: <b>Bug</b>

I cant type anything in the editor 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.13.0-28-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 1727)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.73GB (0.14GB free)|
|Process Argv|--unity-launch /home/taseen/Desktop/coding/coding-support/index.html --crash-reporter-id 64c13cf9-578c-4958-9855-b0f084959036|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|12.4.0
vscode-tailwindcss|bra|0.7.6
gitignore|cod|0.7.0
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|11.7.0
css-stacking-contexts|fel|1.0.15
vscode-pull-request-github|Git|0.34.3
vscode-xml|red|0.18.2
LiveServer|rit|5.7.4
code-to-image|tho|0.0.4
blox|vsb|1.0.5
vim|vsc|1.21.10
markdown-all-in-one|yzh|3.4.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vscop453:30404998
vsrem710cf:30416617

```

</details>

**Comment by alexdima** [comment]
@MohammadTaseenKhan it looks like you have installed the vim extension and you don't want to use its input mode. You can disable or uninstall the vim extension.
