### ISSUE TITLE
Insufficient contrast on Pre-Release label on extension hover

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#142017]
Issue Type: <b>Bug</b>

This is with the default light theme (Light+)
![image](https://user-images.githubusercontent.com/6726799/152200997-940fc943-7708-497c-9672-f7c70b9cf2dc.png)

VS Code version: Code - Insiders 1.64.0-insider (4ccfe1100c3c5625804dbc20afd15ba311487883, 2022-02-02T03:04:09.671Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by IanMatthewHuff** [comment]
Looks good now.
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/812783/155431829-11944d57-3c14-44ed-800c-325a0d0f25b2.png">
