### ISSUE TITLE
Autocomplete unavailable for absolute imports using webpack aliases

### ISSUE THREAD

**Issue by char-cole** [microsoft/vscode#142048]
Issue Type: <b>Bug</b>

I am trying to eliminate complicated relative imports in a Gatsby project. I have setup gatsby-node and eslintrc to identify and understand aliased absolute imports, such as "@components": "src/components". However, we are now unable to utilize Intellisense autocomplete for imports using these aliases.

From numerous articles and stackoverflow questions I've been reading, creating and configuring a jsconfig.json file is supposed to fix this. But it doesn't, for me at least. I have tried many, many possible permutations of the aliases I am using. I have also tried using the extensions Path Autocomplete and Include Autocomplete. Nothing works. (I also tried an extension bisect and the issue was not improved.)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv|-psn_0_81940 --crash-reporter-id 3b9b2de1-18fa-4f03-a648-b0d46d4591d8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
jest-snippets|and|1.8.0
vscode-intelephense-client|bme|1.8.0
vscode-tailwindcss|bra|0.7.6
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
prettier-vscode|esb|9.2.0
auto-rename-tag|for|0.1.9
todo-tree|Gru|0.0.215
vscode-sort|hen|0.2.5
path-autocomplete|ion|1.18.0
graphql-for-vscode|kum|1.15.3
vscode-docker|ms-|1.19.0
remote-containers|ms-|0.209.6
reload|nat|0.0.6
vetur|oct|0.35.0
indent-rainbow|ode|8.2.2
react-proptypes-intellisense|OfH|1.0.3
vscode-template-literal-editor|pli|0.10.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.3.0
format-html-in-php|rif|1.7.0
mdx|sil|0.1.0
vscode-stylelint|sty|1.2.1
sort-lines|Tyr|1.9.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
wslgetstarted:30426333
vscop940:30404999
vsrem710cf:30416617

```

</details>

**Comment by mjbvz** [comment]
Please share a minimal example project that demonstrates the issue

**Comment by char-cole** [comment]
@mjbvz apologies for the wasted time, it was all caused by a simple error in our repo. We actually had an unused tsconfig in the repo which was causing interference. Deleting it solved the issue.
