### ISSUE TITLE
Use new terminal link types in terminal link commands

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#142032]
After the recent terminal link refactor (#141755) we now add more specific types for use in the `Open Detected Link...` and `Open Last * Link...` commands:

![image](https://user-images.githubusercontent.com/2193314/152227966-751e3b53-a390-48d4-823b-ee3d7fd57fb4.png)

The new types are more specific (search, url, local file, local folder*) and means we can avoid showing folders in the the `Open Last File Link` command which almost always opens the folder in the explorer for me since it's in the prompt.

**Comment by Tyriar** [comment]
We should call out directories getting excluded in the release notes as it makes it a lot more useful.

**Comment by Tyriar** [comment]
@meganrogge its already a feature request so we should review it at endgame. This was just a note to our future selves.

**Comment by meganrogge** [comment]
yes reopened as a reminder to myself to add this as a note in the project 😄

**Comment by IanMatthewHuff** [comment]
Looks good. I see the Url, Local File, and Workspace Search categories as expected. Open last * link also worked as expected.
