### ISSUE TITLE
CLI: mv code vscode 

### ISSUE THREAD

**Issue by pinguinpfleger** [microsoft/vscode#142038]
vscode is more intuitive than just code as command line tool.
So I suggest to use vscode instead of code for terminal operations.

**Comment by Lemmingh** [comment]
Renaming seems no longer possible nowadays.

<https://github.com/microsoft/vscode/issues/119159#issuecomment-937870845>

**Comment by Tyriar** [comment]
An alias is pretty easy to create: `alias vscode=code`

**Comment by pinguinpfleger** [comment]
Of course you can create an alias or set the symlink yourself, but this is about user experience.
No one will try to type `code` in the console.
You will type something like `vs [tab] `

If renaming the CLI tool from code to vscode is too difficult, setting a symbolic link could be a great improvement.
But I don't understand why renaming is supposed to be a big deal, especially since it's just a bash script.



```
$ which code                                                                   
/usr/local/bin/code
```

```
$ file /usr/local/bin/code                       
/usr/local/bin/code: Bourne-Again shell script text executable, ASCII text
```

```
$ cat /usr/local/bin/code                            
#!/usr/bin/env bash
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

function realpath() { python -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0"; }
CONTENTS="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
ELECTRON="$CONTENTS/MacOS/Electron"
CLI="$CONTENTS/Resources/app/out/cli.js"
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --ms-enable-electron-run-as-node "$@"
exit $?
```

**Comment by Tyriar** [comment]
Renaming is a massive deal when millions of developers are suddenly broken by the change and all online documentation is suddenly obsolete. Adding a symlink is just bloat imo, if you want to use `vs` or `vscode` you should make an alias, I use `alias c=code-insiders` myself.

**Comment by pinguinpfleger** [comment]
Changes and improvements are constantly taking place.

It's very simple:
- code is renamed to vscode
- a symlink is added to make code still working 
- next release notes announce code as deprecated and suggests using vscode from now on

This is not about me. For me, the change is too late anyway.
I already had the bad experience when I wanted to start VSCode in the console with `vscode . ` with the current folder.
It's about improving the user experience millions of new programmers.

**Comment by Tyriar** [comment]
You're underestimating how much disruption this would cause, not everyone reads release notes and not everyone reads them carefully, people would need to change their existing scripts, wasting time, etc.

Additionally if I brought this up with the team I know there would be pushback as "code" is synonymous with vscode (cli, package name, twitter handle, etc.) and this was a decision that was made before I even joined the team. I actually brought this up like 5 years ago and that is how it landed. Sorry but it's not going to change, just use an alias.

**Comment by pinguinpfleger** [comment]
It's okay.
You don't have to apologize to me.
It was just a well-intentioned suggestion for improvement.
I don't want to make endless discussion of it now.
