### ISSUE TITLE
Twitch

### ISSUE THREAD

**Issue by Catrofe** [microsoft/vscode#142039]
Issue Type: <b>Feature Request</b>

O mesmo barra o OBS Studio de capturar a imagem da tela.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please use English when creating issues/requests in this repo.
Also specify: how is this request for VS Code editor itself and what you expect to be implemented?
