### ISSUE TITLE
Flaky search for body and check result smoke test

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#142050]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

  1) VSCode Smoke Tests (Web)
       Search
         searches for body & checks for correct result number:
     Error: Timeout: get text content '.search-view .messages .message' after 20 seconds.
      at poll (D:\a\1\s\test\automation\src\code.ts:109:10)
      at Code.waitForTextContent (D:\a\1\s\test\automation\src\code.ts:237:10)
      at Search.waitForResultText (D:\a\1\s\test\automation\src\search.ts:122:3)
      at Context.<anonymous> (src\areas\search\search.test.ts:36:4)

https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=153574

**Comment by roblourens** [comment]
@aeschli we used to wait for the window to connect in remote before running tests, now we don't do that in web. 8047f9c877930f2bc7122a8e53984c994effd9e2 This will probably cause more flakes like this. If there is no remote indicator, is there something else we can wait on?

**Comment by roblourens** [comment]
Starting a search before the remote EH has connected is something that _should_ work, and always does in my real-world testing, but something doesn't in smoketest, and we gave up on debugging it and decided to just run search after we connect in `checkWindowReady`

**Comment by aeschli** [comment]
Sorry I don't know what we can use as a replacement. There should not be much waiting for the remote connection to be up as it is part of starting up the workbench.

**Comment by roblourens** [comment]
Anybody have an idea here, @Tyriar @bpasero? This is going back to https://github.com/microsoft/vscode/issues/137847

Is there anything we can look at in the workbench which will reliably change/show up once connected? A command we can run to wait on? We could also just re-add a timeout here and it would probably be fine.

I already spent a bunch of time trying to figure out what's going on with search in particular here. I suspect search wouldn't be the only source of flakiness though. Let's start smoketests from a consistent stable workbench state with the remote connected.

**Comment by Tyriar** [comment]
@aeschli we need something in the DOM or that we can access from the driver that we can check when the window connection is ready, without this the smoke tests will start testing before it's ready and timeout like above.

If the decision is to no longer show the remote indicator on web, here are some ideas:

- Keep it in the DOM but use display: none
- Add a class something else to query 
- Allow the driver to query in some other way, I think with our multiple drivers this would need to happen in `playwrightDriver.ts` and `baseDriver.ts`

**Comment by bpasero** [comment]
The driver implementation for the browser is in `src/vs/platform/driver/browser/driver.ts`, it could expose a new method to query on the status of the remote connection maybe?

**Comment by bpasero** [comment]
Even though the driver itself lives in `platform`, it is being created from the workbench and so we could pass down an event or similar to detect when the connection is done and then use that even for desktop too.

**Comment by aeschli** [comment]
What the test before did was - in essence- waiting for `extensionService.whenInstalledExtensionsRegistered()` [to complete](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/remote/browser/remoteIndicator.ts#L221).

Searching for other consumers of this method I also see the search service doing the same:
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/search/common/searchService.ts#L125

Interestingly that code does not await the promise. Maybe a bug?

**Comment by bpasero** [comment]
Funky 👍

**Comment by aeschli** [comment]
I suspect it's a search related issue timing issue and not related to the remote indicator change.

**Comment by roblourens** [comment]
Well, I don't think we've seen a related failure since 9e0d009 at least... will optimistically close this.
