### ISSUE TITLE
Right-click to Copy selection and Paste on Windows

### ISSUE THREAD

**Issue by elahn** [Microsoft/vscode#14202]
- VSCode Version: 1.6.1
- OS Version: 10.0.14393

In the native terminal, right-click pastes from the clipboard, or right-click on selection copies to clipboard. In the integrated terminal, the context menu is displayed to copy and paste, like in previous versions of Windows.

Please update the integrated terminal to use the native behaviour. This change in behaviour is the single greatest usability enhancement that Microsoft has done to the native terminal, bringing it in line with other OS's.

**Comment by Tyriar** [comment]
So right clicking on a selection will skip the clipboard and "paste" it into the terminal? You're talking about the recent updates to cmd.exe when you say native terminal right?

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/8818

**Comment by elahn** [comment]
Yes, cmd.exe. This is the default behaviour since the release of Windows 10, AFAIK. It applies to all terminals on win10, inc. cmd.exe, Powershell and Bash on Ubuntu on Windows.
- Right-clicking on a selection copies the selection to the clipboard.
- Right-clicking (when no selection) pastes from the clipboard into the terminal.
- Under no circumstances does a context menu appear upon right-click.

**Comment by Tyriar** [comment]
Thanks for the clarification. I'm on the fence on this issue, not sure consistency with cmd.exe for this is worth giving up consistency with vscode on the other platforms.

**Comment by elahn** [comment]
This has been the native terminal behaviour on Linux for as long as I can remember and I think it's the same on OS X.

While it can be argued that platform-native consistency across apps is more important than a consistent experience across different platforms, I'll focus on the usability aspect of this specific behaviour. I argue that all terminals on every platform should behave this way. If you search the internet, chat with users on different platforms, run polls, I'm certain you'll find overwhelming agreement.

At the very least, it deserves an option.

I would really like the convenience of using the built-in terminal, rather than running a separate one (as it saves a cd), but the productivity loss and annoyance factor of extra clicks is not worth it. Until the Windows terminal changed to this behaviour, I would do all of my command-line-centric development on Linux, whereas now I stay in Windows most of the time.

**Comment by Tyriar** [comment]
Linux uses middle click globally to paste selection and that works fine in the terminal currently.

I just looked at cmder which I consider to be the best terminal emulator for Windows and it indeed does implement this so 👍 as an option enabled by default on Windows.

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/pull/17496 thanks to @hun1ahpu!
