### ISSUE TITLE
Cannot open multiple remote terminals in Editor

### ISSUE THREAD

**Issue by sidewinder12s** [microsoft/vscode#142086]
When I open terminals, I've set them to open them in the Editor instead of in the view.

I'd expect if I open a new terminal, it'd open a new terminal process so I have 2 different terminals. 

Instead, both terminals will reflect each others state. Even weirder, the new terminal will override the old one; once I close the new terminal, the old terminals state will come back

I am using the Remote - SSH and a Workspace. But I cannot appear to reproduce this behavior in a fresh non-remote editor so I assume something's up with the vscode-remote extension. I also don't appear to see this behavior when using multiple terminals with the View Tab functionality. 

Is this behavior expected?

**Comment by meganrogge** [comment]
Likely fixed in insiders

**Comment by sidewinder12s** [comment]
@meganrogge is that just VSCode Insiders? I can give that a try tomorrow if so.

**Comment by meganrogge** [comment]
yes @sidewinder12s it should be fixed in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by sidewinder12s** [comment]
It appears this is fixed in the latest release: 

```
Version: 1.64.0
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:23:11.224Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-97-generic
```

Thanks!
