### ISSUE TITLE
Side Bar and Side Panel can not be moved to right side together

### ISSUE THREAD

**Issue by slayer** [microsoft/vscode#142179]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.0
- OS Version: Ubuntu 21.04

Steps to Reproduce:

1. Update vscode to 1.64.0
2. Try to move Sidebar and Sidepanel to right.
3. When Sidebar moved to the right, Sidepanel moved to the left.

![image](https://user-images.githubusercontent.com/57521/152518312-0a3efaf5-81a0-4042-9b3a-4fc9e2835ef9.png)
![image](https://user-images.githubusercontent.com/57521/152518447-c849fde2-7216-434f-b53b-685675c7ced4.png)

**Comment by gjsjohnmurray** [comment]
/duplicate - see https://github.com/microsoft/vscode/issues/141349#issuecomment-1021287245
