### ISSUE TITLE
Missing dependency: iconv-lite

### ISSUE THREAD

**Issue by ufttubam** [microsoft/vscode#142137]
Issue Type: <b>Bug</b>

I checkout my repo. Then right click on it and open "Git Bash here" then run ./update-ext.sh
after that this error popup and source control disappeared

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by ufttubam** [comment]
./update-ext.sh :
# apply externals
svn propset svn:externals -F sources.svnext .

# update to retrieve
svn update

**Comment by ycdtosa** [comment]
I just got the same issue here.

1.- open project after update.
2.- go to the Source-Control tab on the side bar

No files in there, got a popup instead.
got popup: 

  missing dependency: iconv-lite
  Source: SVN (Extension)

Removing and then reinstalling the extension does not fix it.

**Comment by christian5011** [comment]
I started having the same problem right now. The SVN extension is not working because of this.
I tried to reinstall the svn extension but it does not fix it.

**Comment by ycdtosa** [comment]
I also tried other svn extensions, most of them a fork of johnstonecode.svn-scm.
and got the same result.

the second most popular svn plugin is XXXX
if i install xxxx i also get:

Missing dependency: jschardet

**Comment by ycdtosa** [comment]
After installing and removing several times those extensions, re-starting visual code as required at some point the problem seems to go away.  I can now use the extension without issues.

**Comment by christian5011** [comment]
Same as @ycdtosa , after some restarts the problem went away. I cannot find what fixed the problem because the version of vscode and the svn pluguin is the same as before and no configuration was changed.
