### ISSUE TITLE
Terminal side panel can no longer be moved to the left, next to explorer

### ISSUE THREAD

**Issue by avianion** [microsoft/vscode#142181]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Latest
- OS Version: Windows 11

Steps to Reproduce:

1. Open VS CODE
2. Try move your side panel to the left. It doesn't work. It only lets you move to the bottom, or right

Fix this asap pls.

**Comment by cameronove** [comment]
@gjsjohnmurray 
This is not the same issue.  The issue you reference is to place the side-bar next to the side-panel on the right.  I don't want to do that at all.

I would like my side-bar on the left, my terminal next to my side-bar on display1 and my editor to the right of those on display 2.  I can no longer do that.  Please open this issue back up.  Why did you remove that capability anyway.  I've been working that way for years now - what did removing it solve.  This is crazy - I about had a heart attack when I updated my vscode and everything came up all mixed up.  Who does this?

**Comment by gjsjohnmurray** [comment]
With respect, what you are unhappy about is one manifestation of the 1.64 change being handled in the issue I referenced.

A short term workaround for you is to downgrade. See https://github.com/microsoft/vscode/issues/141349#issuecomment-1029944661
