### ISSUE TITLE
Sort and filter editor suggestions

### ISSUE THREAD

**Issue by modscleo4** [microsoft/vscode#142114]
I couldn't find any setting to sort suggestions by type and not by name
![image](https://user-images.githubusercontent.com/20730142/152427069-632863d5-9f8d-4503-ac73-3c1595d34150.png)
Also suggestions filter like in VS2022 would be nice
![image](https://user-images.githubusercontent.com/20730142/152427176-fcc940af-6800-4ceb-b373-cf1db83e92b6.png)

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"suggest"

**Comment by modscleo4** [comment]
> This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title 😳 Anyways, searching for issues with the same labels will likely help you 👉 [https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"suggest](https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22suggest)"

It's #80444, I got lost on Issue Search and couldn't find it before.
