### ISSUE TITLE
Jupyter Notebooks only allow searching the whole notebook instead of individual cell

### ISSUE THREAD

**Issue by 392781** [microsoft/vscode#142143]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.0
- OS Version: Mint 20.3

Steps to Reproduce:

1. Create a Notebook with multiple cells and content in those cells
2. Press ctrl-f and search for something that can be found in more than 1 cell
3. The search feature will *only* allow you to search the whole notebook and not the individual focused cell.

The desired behavior is that if I am searching in a given cell, I am only search that one cell and not the whole notebook.

There was an issue submitted about this (that I cannot find right now) that said that this is fixed but that is not the case unfortunately... (Unless I am doing something wrong)

e: #141493 is a related issue... Still can't find the original issue that was closed because it was fixed in insiders.

According to [this stackoverflow post](https://stackoverflow.com/questions/63849023/find-replace-in-vs-code-jupyter-notebooks) it used to be possible to search and replace in cells and not the whole notebook...

**Comment by gjsjohnmurray** [comment]
My reading of that SO thread is, find used only to look in the current cell and you couldn't get it to operate across the whole notebook. Now the opposite is true, and the other issue you linked to is about offering both. I think this one here should be closed as a duplicate.

/duplicate
