### ISSUE TITLE
Lite Version/Mode

### ISSUE THREAD

**Issue by plutoniumm** [microsoft/vscode#142194]
MAIN
Request for "Lite" version of VSC with lesser used features not only turned off but not shipped at all. Or maybe a lite mode in the edition itself which turns off anything which is not Extensions + Intellisense + Monaco (+git). This is different from Zen mode as it is not just visual clarity but also in-memory clarity. 

Everytime a new release comes out turning off features not needed seems like a chore (I very much appreciate & thank the community and MS however for the monumental work they do <3). So a Lite version/mode would straighten this out. Not to mention the performance gains that can be achieved 

EXPLORATORY
I am unaware of the feasibility myself but think it might be worthwhile at least considering [Tauri](https://github.com/tauri-apps/tauri)/[Neutralino](https://github.com/neutralinojs/neutralinojs) as alternatives to Electron should there be a new version (if written from scratch that too). Pros: Performance, Cons: Support etc.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now to gather more feedback. Thanks
