### ISSUE TITLE
The term 'Y' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by andrewpmk** [microsoft/vscode#142145]
I keep getting this error when I run commands like npm install, etc. in Visual Studio Code:

Y : The term 'Y' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
At line:1 char:1
+ Y
+ ~
    + CategoryInfo          : ObjectNotFound: (Y:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Is this caused by this feature:
The terminal is now able to automatically reply when a specific sequence of characters is received. A good example of where this is useful is the Windows batch script message Terminate batch job (Y/N)? after hitting Ctrl+C when running a batch script. This typically just ends up causing problems for the user and so a default automatic reply was added. The terminal will now automatically reply with Y and enter (\r), which makes Ctrl+C in Windows feel much better.

- VS Code Version: 1.6.4 (user setup)
- OS Version: Windows_NT x64 10.0.19044

**Comment by Tyriar** [comment]
Did you hit ctrl+c to trigger this? A screenshot of the terminal around where the bad Y happened would be helpful.

**Comment by Tyriar** [comment]
Also do you use Clink?

**Comment by chrisant996** [comment]
@Tyriar can you please see #142255?  VSCode mentions the abandoned mridgers Clink repo, and it would be great to update the links to point at the current official resurrected [Clink repo](https://github.com/chrisant996/clink).
