### ISSUE TITLE
Allow Application User Settings in Workspace's `settings.json` File

### ISSUE THREAD

**Issue by rbrisita** [microsoft/vscode#142140]
There are some workspaces that I want the last known state to show when I open VSCode and some workspaces that I don't. Currently all options that allow this are application level and not folder level. Any reason why?

**Comment by gjsjohnmurray** [comment]
Which specific settings are you talking about?

**Comment by rbrisita** [comment]
In the `.vscode/settings.json` file, I have these settings:

```json
{
  "files.saveConflictResolution": "overwriteFileOnDisk",
  "files.hotExit": "onExit",
  "window.reopenFolders": "none",
  "window.newWindowDimensions": "maximized",
  "window.openFilesInNewWindow": "on",
  "window.openFoldersInNewWindow": "on",
  "window.openWithoutArgumentsInNewWindow": "on",
  "window.restoreWindows": "none"
}
```

VSCode displays a message for everything under the first property:
`This setting can be applied only in application user settings`

**Comment by sandy081** [comment]
These cannot be applied in workspace as they define the behavior of complete application.

**Comment by rbrisita** [comment]
Sounds limiting.
