### ISSUE TITLE
Copy ´patse command line

### ISSUE THREAD

**Issue by mbeckenbach** [Microsoft/vscode#14217]
- VSCode Version: 1.6.1
- OS Version: Win10

Steps to Reproduce:

1. Paste something into integrated terminal by ctrl+v

---

Windows 10 has ctrl+c, ctrl+v support in command line. In VS code ctrl+v will enter ^V

**Comment by Tyriar** [comment]
Copy and paste on Windows is ctrl+shift+c/v, track https://github.com/Microsoft/vscode/issues/8818 for ctrl+c/v
