### ISSUE TITLE
Regex for 'export activate' matches too much and messes up render loading

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#142125]
Issue Type: <b>Bug</b>

Using webpack, I end up with vs code thinking my js exports an activate function but it doesn't. 

This example matches the regex:

```javascript
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be in strict mode.
(() => {
"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "renderOutput": () => (/* binding */ renderOutput),
/* harmony export */   "disposeOutput": () => (/* binding */ disposeOutput),
/* harmony export */   "activate": () => (/* binding */ activate)
/* harmony export */ });
/* harmony import */ var tslib__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__("./node_modules/tslib/tslib.es6.js");
/* harmony import */ var _client_datascience_interactive_common_interactiveWindowTypes__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__("./src/client/datascience/interactive-common/interactiveWindowTypes.ts");
/* harmony import */ var _client_datascience_messages__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("./src/client/datascience/messages.ts");
/* harmony import */ var _react_common_logger__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__("./src/datascience-ui/react-common/logger.ts");
/* harmony import */ var _react_common_postOffice__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__("./src/datascience-ui/react-common/postOffice.ts");
/* harmony import */ var _common_manager__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__("./src/datascience-ui/ipywidgets/common/manager.ts");
/* harmony import */ var _common_scriptManager__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__("./src/datascience-ui/ipywidgets/common/scriptManager.ts");
```
But is not exporting an activate function.

VS Code version: Code - Insiders 1.64.0-insider (96e996a75c09e5947c151f8b978bdc9496b81aea, 2022-02-01T10:10:59.660Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (14.23GB free)|
|Process Argv|--crash-reporter-id 108b1212-dd8c-4594-8252-c1351bf31268|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.5.0
httpbook|anw|2.2.1
vscode-httpyac|anw|4.9.1
doxdocgen|csc|1.3.2
vscode-eslint|dba|2.2.2
dendron|den|0.79.0
dendron-paste-image|den|1.1.0
prettier-vscode|esb|9.2.0
codespaces|Git|1.5.0
remotehub|Git|0.23.2022012602
handydandy-notebook|jak|0.1.0
better-cpp-syntax|jef|1.15.10
vscode-position|jtr|1.1.2
regexp-preview|Lou|0.1.5
vscode-catch2-test-adapter|mat|4.0.22
template-string-converter|meg|0.6.0
vscode-docker|ms-|1.19.0
python|ms-|2022.1.1786926181-dev
vscode-pylance|ms-|2022.1.6-pre.1
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.215.0
remote-ssh|ms-|0.71.2022012615
remote-ssh-edit|ms-|0.71.2022012615
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
live-server|ms-|0.2.12
vscode-selfhost-test-provider|ms-|0.3.9
vscode-typescript-next|ms-|4.6.20220125
vscode-data-table|Ran|1.8.0
jupyter-tools|rch|0.0.1
rest-book|tan|5.0.1
cmake|twx|0.0.17
errorlens|use|3.4.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30421357
vscop940:30404999
vsclayoutctrc:30405799
pythonvsnew555:30426298
vscscmwlcmt:30428973

```

</details>

**Comment by mjbvz** [comment]
Can you please look into migrating off of the old module style: https://github.com/microsoft/vscode-jupyter/issues/7519

If I recall this check only exists to try to support Jupyter

**Comment by rchiodo** [comment]
Not sure what 'old module style' means? We webpack a bunch of stuff. What output type should I used? Right now I'm forcefully creating an 'activate' function and it seems to work if I use output type 'module'. 

Or is this referring to us loading requirejs?

**Comment by rebornix** [comment]
One idea we discussed in notebook sync meeting about how to avoid the regex for detecting esmodule misbehaving is adding a special banner (`// <notebook-amd-renderer>`) to the bundle file for Jupyter preload and the webiew preload checks if the banner exists or not. @mjbvz would that be an option?

**Comment by mjbvz** [comment]
@rebornix That's safer but I'd much prefer we just align on using modules. That's what our public notebook apis do. The `export` check was only added as a temporary measure to support Jupyter while it got  updated to the new api 

@rchiodo I believe you still should be able to use requirejs, but the entrypoint for your script would need to be a module

**Comment by rchiodo** [comment]
@mjbvz our modules still have to export an 'activate' function, right?

We can work on wrapping requirejs in a module.

**Comment by mjbvz** [comment]
Yes but it doesn't have to do anything if you don't need it to. Here's the values passed to it: https://github.com/microsoft/vscode/blob/7182e32eaaa8bb4d244c3b0afba6f9e220fccc39/src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts#L206

**Comment by mjbvz** [comment]
Closing this in favor of https://github.com/microsoft/vscode-jupyter/issues/7519 Once that is fixed, we will remove this code. 

Let me know if you have any questions/issues with updating to use modules
