### ISSUE TITLE
--install-extension <path to .vsix file> should abort if extension is already installed 

### ISSUE THREAD

**Issue by jsjoeio** [microsoft/vscode#142101]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.0-insider
- OS Version: macOS 11.4

Steps to Reproduce:

1. Download [vsix file](https://open-vsx.org/extension/wesbos/theme-cobalt2)
2. Install - `code-insiders --install-extension <path-to-vsix-file>`
3. Try installing again - `code-insiders --install-extension <path-to-vsix-file>`

Expected:
`code-insiders` should abort/skip installation since extension is already installed. 

Actual:
<img width="1660" alt="image" src="https://user-images.githubusercontent.com/3806031/152397439-249a3661-d26d-409e-91d5-4c6e9a2e1754.png">

**Comment by sandy081** [comment]
This is intentional and designed so that users can override the existing extension version with same by VSIX
