### ISSUE TITLE
Support calling additional `resolveDebugConfiguration` callbacks if one callback changes the debug configuration `type`

### ISSUE THREAD

**Issue by jkoritzinsky** [microsoft/vscode#142135]
Today, VSCode's debug configuration provider API provides partial support for extensions that change the `type` property on a debug configuration returned by the `resolveDebugConfiguration` on a provider. The support today includes activating debuggers for the new debug configuration `type`. This support was added in https://github.com/microsoft/vscode/commit/4150347750b762a3f537ef660e96617083260066 to fix https://github.com/microsoft/vscode/issues/135090.

However, this support does not include running the `resolveDebugConfiguration` callback for configuration providers keyed off the new `type`. This would be desireable for extensions that run highly customized debug configurations whose resolved configuration's `type` may differ depending on other installed extensions, target platform, or on user input.

I would be willing to contribute an implementation of this feature if the idea is amenable.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/110889
