### ISSUE TITLE
typescript hover: option to enable/disable and set modifier key

### ISSUE THREAD

**Issue by mariusa** [microsoft/vscode#142172]
I develop with Javascript/Typescript, but the informative hovers are getting a lot in the way. Moving the mouse somewhere triggers an informative Typescript hover enough times to be annoying.

Searching user preferences for "hover", I see other languages have an option to enable it:
![2022-02-04_11-27_1](https://user-images.githubusercontent.com/1283842/152504796-cb7eb2f6-c997-47f8-ab13-947d6a37e8f1.png)

Request 1: Please add a similar option to enable/disable for Typescript

Request 2: Please add the possibility to trigger hover on Ctrl+Hover.
Now Ctrl shows additional info in hover. I'd prefer to show the hover (with the additional info) only on Ctrl+Hover, so it doesn't get in the way during regular coding, but can be easily triggered only when needed.

Related, but not the same: #94679, #92787, #54503

Thank you!

**Comment by mjbvz** [comment]
Try setting `"editor.hover.enabled": false` to disable hovers

You can then trigger hovers again using a keybinding for `editor.action.showHover`

**Comment by mariusa** [comment]
Thanks. This works, but it's more complex than needed.

`"editor.hover.enabled": false`
Then, with the mouse hovering over an error or area that normally would show the hover tooltip, I'd like to display the tooltip simply by pressing `Ctrl`. That is, get the same behavior as `"editor.hover.enabled": true`

Now I have to 
1. click in that area, then 
2. press a keybinding which is at least 2 keys
