### ISSUE TITLE
Tabbing to quickpick item's 2nd button sets focus outside the quickpick

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#142157]
![quickpick](https://user-images.githubusercontent.com/641685/152486049-954f4529-d6a1-4239-9c47-36b7e19d34a2.gif)

In the video, I am tabbing from the input, to the first item, then to the first button, and then the next tab, leaves the quickpick completely (which caused the quickpick to close since it lost focus).

It seems to only happen on the 2nd tab from a button to the next.

/cc @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
I talked to @joaomoreno about this and he mentioned that this is by-design in that we leave navigating around a widget (Actionbar in this case) to the arrow keys. @isidorn, please let me know if I have this wrong.

in other words:
Tab -> navigation between widgets
Arrow -> navigation within widgets

**Comment by isidorn** [comment]
Yeah this is by design. I agree that this situation here is not the best...
@eamodio check out this aria toolbar example [here](https://www.w3.org/TR/wai-aria-practices/examples/toolbar/toolbar.html) which we are following.

**Comment by eamodio** [comment]
@isidorn I do get not being able to tab between the individual buttons (and having to use the arrows), but this issue is about that.

If you open a quick pick without any buttons on items -- you can keep tabbing to cycle around all the parts of the quick pick and not have the quick pick disappear -- it will just cycle. But once an item has buttons, the "tab" after the buttons have focus, causes the whole quick pick to lose focus and if you don't have the "ignoreFocusOut" setting set, the quick pick will close.

That IMO can't be by-design.

**Comment by isidorn** [comment]
@eamodio I see, thanks for clarifying. I agree with you.
@TylerLeonhardt the only way I know is to listen to focus changes and programatically set and remove `tabIndex` on HTML elements. Which is a pain.

**Comment by TylerLeonhardt** [comment]
hmm ok. I wonder why it's working without buttons but not with buttons... I'll investigate as soon as I get the time.

**Comment by TylerLeonhardt** [comment]
Verification: 
* Install GitLens if you don't already have it
* hover over an inline blame to get the rich hover
![image](https://github.com/microsoft/vscode/assets/2644648/5c31130e-8213-4eb7-bcc7-ba70ebfad15a)
* click the `...` show more actions
![image](https://github.com/microsoft/vscode/assets/2644648/2f2808e9-a8a9-46f7-82ba-12db853a4897)

That gives you the quick pick @eamodio mentions in the original issue. Hitting TAB should cycle between:
* input
* this list
* the first quick pick button
* 🔁 

The quick pick shouldn't be hidden at all during tabbing.

**Comment by eamodio** [comment]
Woo!

/verified
