### ISSUE TITLE
Integrated Terminal can be a fantastic console emulator for Windows

### ISSUE THREAD

**Issue by Oathbinder** [Microsoft/vscode#14219]
I think integrated terminal is the most good-looking console emulator for Windows, but I have to open VS Code to use it. So, what about devloping an independent console emulator based on VS Code Integrated Terminal for Windows users? You know, Windows users need a powerful terminal (cmder has more functions but doesn't look good as Integrated Terminal).

I hope it can be:

1. VS Code style
2. As functional as cmder (more is better)
3. Well cooperate with cmd, powershell, bash on windows
4. Implement some features like zsh

Please consider my suggestion, thanks.

**Comment by roblourens** [comment]
I think Windows could include a better terminal emluator by default but I'm not sure we'd be the ones to do it...

**Comment by Oathbinder** [comment]
@roblourens Electron-based terminal emulator is a great idea, like [black-screen](https://github.com/shockone/black-screen) and [hyper](https://github.com/zeit/hyper), but they don't support Windows now. So I think VS Code will be a good solution. Plus, will it be a huge leap that change the default console of Windows as Microsoft regards compatibility as their first aim.

**Comment by Tyriar** [comment]
Well the core of the terminal is in the project [xterm.js](https://github.com/sourcelair/xterm.js) which I frequently commit to. I've actually considered for some time to build an independent terminal as you say, mainly as a way to use the thing I work on even more. Also Hyper [is considering](https://github.com/zeit/hyper/issues/781) moving to another backing xterm emulator which would also work for me (they also are working on [Windows support](https://github.com/zeit/hyper/issues/167)).

I'll close this off as most of the good stuff in the terminal is housed within the xterm.js project. It's great to hear you like it though 😃
