### ISSUE TITLE
FileSystem writeFile and readFile Untitled Error

### ISSUE THREAD

**Issue by rbrisita** [microsoft/vscode#142138]
Issue Type: <b>Bug</b>

It seems workspace's FileSystem `writeFile` and `readFile` don't handle untitled files well. They both produce this error:

```
Error (FileSystemError): 
Unable to resolve filesystem provider with relative file path 'untitled:Untitled-1'
```

Example:
```
await vscode.commands.executeCommand('workbench.action.files.newUntitledFile');
const uri = vscode.window.activeTextEditor.document.uri;
const uInt8Arr = await vscode.workspace.fs.readFile(uri); // Error
```

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:18:59.299Z)
OS version: Linux arm64 5.15.7-1-MANJARO-ARM
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|unknown (6 x 1416)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|3.77GB (0.37GB free)|
|Process Argv|. --crash-reporter-id 2a85f066-a8e2-4971-b1ff-37959f57a0f0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
vscode-drawio|hed|1.6.4
vsliveshare|ms-|1.0.5330

</details>

**Comment by jrieken** [comment]
You cannot write files of the `untitled` scheme to disk. There is no backing file system behind that and they only exist in memory.

**Comment by rbrisita** [comment]
Thank you for that clarification. There is some cognitive dissonance here: Untitled files are created and handled the same as disk files, there is workspace storage to persist between application launches, and the `FileSystem` interface methods contain a `Uri` parameter. I would suggest, for future developers, to explicitly state in the documentation that `scheme: untitled` is not supported.
