### ISSUE TITLE
VSCode Intellisense do not work

### ISSUE THREAD

**Issue by Salvodif** [Microsoft/vscode#14210]
- VSCode Version: 1.6.1
- OS Version: Windows 10

Steps to Reproduce:
1. Intellisense doesn't work. I cannot see even the global function. ex: console. 

![capture](https://cloud.githubusercontent.com/assets/107290/19622228/425840e0-98a5-11e6-89c9-b1a7e659d5e4.PNG)

of course the `p.` is with no function too.

BTW it never worked even just after the installation.

Can anybody tell me what I'm doing wrong?

**last update** it's seems that if I working on a .js files intellissense works BUT it's still doen't get the dt of PIXI

![capture](https://cloud.githubusercontent.com/assets/107290/19622638/72635190-98ae-11e6-96c5-315437d361c0.PNG)

I forgot that in the main.js file the reference tag **has been removed**

**Comment by waderyan** [comment]
@Salvodif thank you for opening this issue. Can you share your workspace with me so I can take a look on my machine?

**Comment by Salvodif** [comment]
@waderyan sorry mate but I deleted it...

**Comment by waderyan** [comment]
No problem. If you see the issue again and can give us something to reproduce, please open this back up.
