### ISSUE TITLE
wrong comment show 显示错误的注释

### ISSUE THREAD

**Issue by libaoxu** [Microsoft/vscode#14215]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.when in html file , i comment javascript file , 
   it show : <--let bao = 1;-->,  not show  // let bao = 1;or /*let bao = 1*/
   css it show : <--color: red-->, not show  // color: red; or /*color: red*/
2.在html文件里面的script标签里面写js, 和 style标签里面写 css, 如果用快捷键注释它, 都会显示错误的注释方式
   不是显示正确的js注释, 而是在js中, 把js语法当作html语法 , 显示html注释

**Comment by roblourens** [comment]
Yes this is #11081
