### ISSUE TITLE
Bracket Colorization flags .sh case statement parenthesis red.

### ISSUE THREAD

**Issue by Spleeding1** [microsoft/vscode#142117]
Issue Type: <b>Bug</b>

Write a `case` statement in a .sh file with `"editor.bracketPairColorization.enabled": true`. All of the matches `)` get flagged red.

```
case "problem" in
    problem)
        echo "There's a problem"
        ;;
esac
```

VS Code version: Code - Insiders 1.64.0-insider (Universal) (5554b12acf27056905806867f251c859323ff7e9, 2022-02-02T17:14:40.220Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5775R CPU @ 3.30GHz (8 x 3300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstartedc:30421358
vs360cf:30404996
vsclayoutctrt:30405800
pythonvsnew555cf:30426299
vscscmwlcmt:30428973
azactmsalcf:30432849

```

</details>

**Comment by hediet** [comment]
Is the `)` valid there? If so, brackets should not be matched for shell scripts.

**Comment by Spleeding1** [comment]
Yes that is indeed valid. [Shell Case Statement](https://www.tutorialspoint.com/unix/case-esac-statement.htm)

It would be ashamed to lose the matching brackets for all of the shell scripts and would be nicer to just ignore them for case statements. I also realize this would be a lot harder to code and will accept whatever solution you come up with. Although if it is between no colorization or errored case statements I would take the errored case statements.
