### ISSUE TITLE
Is it possible to add project folder instead of opening a new window?

### ISSUE THREAD

**Issue by betimer** [Microsoft/vscode#14214]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: msjsdiag.debugger-for-chrome-2.0.0, pgourlain.erlang-0.0.9, robertohuertasm.vscode-icons-3.0.5

So that a single window could cover all projects we are working on. (similar to atom)

**Comment by roblourens** [comment]
Not at the moment, feature request here - #13066
