### ISSUE TITLE
Accessibility: audio cues fire multiple times on "next error" wraparound

### ISSUE THREAD

**Issue by zersiax** [microsoft/vscode#142121]
Issue Type: <b>Bug</b>

When using the f8 hotkey to navigate between errors, the audio cue for error seems to fire several times in rapid succession when jumping from the final error in a file back up to the first one, making the sound several times louder than it would normally be. We should probably make sure that doesn't happen as it's rather startling :)

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.22538
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 4900HS with Radeon Graphics          (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.42GB (3.48GB free)|
|Process Argv|--crash-reporter-id 75d21a00-6d73-46fa-a9ad-2f9e36f2165a|
|Screen Reader|yes|
|VM|53%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-extra-intellisense|ami|0.6.1
vscode-django|bat|1.8.0
django-snippets|bib|1.1.1
vscode-intelephense-client|bme|1.8.0
laravel-goto-view|cod|1.3.7
vscode-markdownlint|Dav|0.46.0
dendron|den|0.80.3
dendron-markdown-links|den|0.6.20
dendron-markdown-preview-enhanced|den|0.10.57
dendron-markdown-shortcuts|den|0.12.1
dendron-paste-image|den|1.1.0
dendron-snippet-maker|den|0.1.6
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.1.0
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
pythonsnippets|frh|1.0.2
Angular2|joh|12.0.0
vscode-peacock|joh|4.0.0
php-cs-fixer|jun|0.2.10
vsc-python-indent|Kev|1.14.2
kite|kit|0.147.0
MagicPython|mag|1.1.0
php-namespace-resolver|Meh|1.1.8
dotenv|mik|1.0.1
vscode-elixir|mjm|1.1.0
vscode-docker|ms-|1.19.0
csharp|ms-|1.24.0
vscode-edge-devtools|ms-|1.4.3
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.1.5
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.0
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
cpptools|ms-|1.8.2
vscode-typescript-next|ms-|4.6.20220202
vsliveshare|ms-|1.0.5330
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.9.0
php-docblocker|nei|2.6.1
autodocstring|njp|0.5.4
vetur|oct|0.35.0
laravel-blade|one|1.29.0
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.13.0
vscode-phoenix|ped|0.6.0
vscode-php-getters-setters|php|1.2.3
material-icon-theme|PKi|4.12.1
joplin-vscode-plugin|rxl|0.6.0
laravel-artisan|rya|0.0.28
laravel-goto-controller|ste|0.0.15
vue-ls-snippets|van|0.0.5
vscodeintellicode|Vis|1.2.16
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.23.0
php-pack|xde|1.0.3
php-intellisense|zob|1.0.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30428979
pythonvs932:30410667
vscop453:30404998
vsrem710:30416614

```

</details>

**Comment by zersiax** [comment]
cc @isidorn

**Comment by isidorn** [comment]
There was already similar feedback and we agreed we should look into debouncing the error sound. It would help in this case as well.

**Comment by hediet** [comment]
Audio cues are now debounced when the line changes.
