### ISSUE TITLE
TypeScript plugin extensions don't load on Windows in 1.64.0

### ISSUE THREAD

**Issue by dsherret** [microsoft/vscode#142139]
- VS Code Version: 1.64.0
- OS Version: Windows 10

Steps to Reproduce:

1. Load a TypeScript plugin extension like:
   * https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno
   * Or https://marketplace.visualstudio.com/items?itemName=heroboy.generate-switch-case-for-enum-type

With tsserver logs enabled, you will notice the following in the logs:

```
Info 0    [18:48:17.280] Starting TS Server
Info 1    [18:48:17.281] Version: 4.5.5
Info 2    [18:48:17.281] Arguments: C:\Users\david\AppData\Local\Programs\Microsoft VS Code\Code.exe c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\david\AppData\Local\Temp\vscode-typescript\43a6ae4ad4818b5f148f\tscancellation-46d2cad07af3976cd9e1.tmp* --logVerbosity verbose --logFile c:\Users\david\AppData\Roaming\Code\logs\20220203T181651\exthost7\vscode.typescript-language-features\tsserver-log-Hl2L4q\tsserver.log --globalPlugins typescript-deno-plugin --pluginProbeLocations /c:/Users/david/.vscode/extensions/denoland.vscode-deno-3.10.1 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
Info 3    [18:48:17.281] Platform: win32 NodeVersion: 14 CaseSensitive: false
...
Info 18   [18:48:17.298] Loading global plugin typescript-deno-plugin
Info 19   [18:48:17.298] Enabling plugin typescript-deno-plugin from candidate paths: /c:/Users/david/.vscode/extensions/denoland.vscode-deno-3.10.1,c:/Users/david/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../..
Info 20   [18:48:17.298] Loading typescript-deno-plugin from /c:/Users/david/.vscode/extensions/denoland.vscode-deno-3.10.1 (resolved to C:/c:/Users/david/.vscode/extensions/denoland.vscode-deno-3.10.1/node_modules)
Info 21   [18:48:17.309] Loading typescript-deno-plugin from c:/Users/david/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../.. (resolved to c:/Users/david/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/node_modules)
Info 22   [18:48:17.310] Failed to load module 'typescript-deno-plugin' from C:/c:/Users/david/.vscode/extensions/denoland.vscode-deno-3.10.1/node_modules: Error: Could not resolve JS module 'typescript-deno-plugin' starting at 'C:/c:/Users/david/.vscode/extensions/denoland.vscode-deno-3.10.1/node_modules'. Looked in: C:/c:/Users/david/.vscode/extensions/denoland.vscode-deno-3.10.1/node_modules/typescript-deno-plugin/package.json, C:/c:/Users/david/.vscode/extensions/denoland.vscode-deno-3.10.1/node_modules/typescript-deno-plugin.js, C:/c:/Users/david/.vscode/extensions/denoland.vscode-deno-3.10.1/node_modules/typescript-deno-plugin.jsx, C:/c:/Users/david/.vscode/extensions/denoland.vscode-deno-3.10.1/node_modules/typescript-deno-plugin/index.js, C:/c:/Users/david/.vscode/extensions/denoland.vscode-deno-3.10.1/node_modules/typescript-deno-plugin/index.jsx,
...etc...
```

**Cause?**

This may be because vscode started to provide a `pluginProbeLocations` to tsserver in the following format:

```
--pluginProbeLocations /c:/Users/david/.vscode/extensions/denoland.vscode-deno-3.10.1
```

Previously in 1.63 it used this format:

```
--pluginProbeLocations c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.10.1
```

So it's now resolving `/c:/` to `C:/c:/` within ts server.

I will keep investigating.

**Comment by mjbvz** [comment]
Likely caused by fd745e79f5c08e96e6c8a5b7bceaaaa417d098d5

Will push a potential fix but please test on the next insiders build to confirm it works. I don't have a window machine setup to test this easily

**Comment by mjbvz** [comment]
\fixedBy df09257f2e73fb382e2abe8a42d635fb33fe1d31

**Comment by dsherret** [comment]
@mjbvz ok thanks, I will try it out in the next insiders. To be honest, I'm surprised there's no integration tests for TypeScript language service plugins that could be tested on a Windows CI though. I guess there's not much guarantee TypeScript plugins won't stop loading again in the future.

Also, this seems like a pretty critical bug. I think many extensions won't work on Windows anymore.

**Comment by mjbvz** [comment]
We can backport it if the fix works. This is the first report we're seeing of it though

**Comment by csvn** [comment]
I've encountered the same issue in a small Deno project, where the extension stopped working after the new VSCode version. Updating to Insiders fixed the issue for me.

![image](https://user-images.githubusercontent.com/8770194/152546828-3847974a-7087-4775-8257-c8d8a369b174.png)

Will there be a new version of VSCode that fixes this regression? Just curious about a rough timeline when I can switch back to Stable for this project.

**Comment by dsherret** [comment]
It's also now fixed for me in the latest insiders:

```ts
--pluginProbeLocations c:\Users\david\.vscode-insiders\extensions\denoland.vscode-deno-3.10.1
```

I also don't see any trace of any `/c:/` like paths in the ts server logs anymore.

**Comment by lucacasonato** [comment]
I really don't want to be pushy, but we have a lot of users on our end running into this issue. All extensions that include TS compiler plugins are broken on Windows in 1.64. Could this be considered for a 1.64.1 patch release?

Even the official Microsoft TSLint extension (`ms-vscode.vscode-typescript-tslint-plugin`) does not work in 1.64 :-) (See #142244)

**Comment by jasonwilliams** [comment]
I agree with @lucacasonato. Everyone currently using Styled Components is [affected](https://github.com/styled-components/vscode-styled-components/issues/354) and we've had many users bring this up also. I think this is important enough for a patch release.

**Comment by brooketopcoder** [comment]
I'd like to up-vote this fix as well. As you can see in my other report of this bug, https://github.com/microsoft/vscode/issues/142244, this is really poor timing for this to break b/c I got my entire team to switch to this linting configuration, and it breaks literally the next day.

**Comment by dojyorin** [comment]
Thank you for working on the fix.
I posted a temporary workaround by https://github.com/denoland/vscode_deno/issues/620#issuecomment-1032141387 until 1.64 Recovery is released.
