### ISSUE TITLE
Search in File with Regex not working properly

### ISSUE THREAD

**Issue by juergenbosch** [microsoft/vscode#142174]
- VS Code Version: 1.63.2
- OS Version: Window 10 

Steps to Reproduce:

1. Open a file with the following content:
[
  {
    "__metadata": {
      "id": "",
      "uri": "",
      "type": ""
    },
    "ChmlCmplncInfoUUID": "0894ef45-8661-1ee8-b4de-722cc0233ee5",
    "CmplRqRsltUUID": "0894ef45-7651-1edc-a0ee-91a120b281cb",
    "Language": "RO",
    "Language_Text": "Romanian",
    "CmplRqVersName": "ADN 2021",
    "ComplianceRequirement": "ADN",
    "CmplRqRsltProcessingStatus": "IP",
    "DngrsGoodMarkingLabelText": "MARKING3"
  },
  {
    "__metadata": {
      "id": "",
      "uri": "",
      "type": ""
    },
    "ChmlCmplncInfoUUID": "0894ef45-8661-1ee8-b4de-722cc0233ee5",
    "CmplRqRsltUUID": "0894ef45-7651-1edc-a0ee-91a120b281cb",
    "Language": "HR",
    "Language_Text": "Croatian",
    "CmplRqVersName": "ADN 2021",
    "ComplianceRequirement": "ADN",
    "CmplRqRsltProcessingStatus": "IP",
    "DngrsGoodMarkingLabelText": "MARKING3"
  }
]

2. Search with the regex pattern: "__metadata"[^}]*\},

Result: Nothing is found.

Expected: The Search should find the following multiline content:
"__metadata": {
      "id": "",
      "uri": "",
      "type": ""
},

To check if the regex pattern is correct i have matches if i use the same regex pattern on: https://regex101.com/

**Comment by gjsjohnmurray** [comment]
Maybe #131507

**Comment by IllusionMH** [comment]
Are you using find widget inside of editor or for open file?

RegExps searches don't perform multiline matches unless they have hints e.g. `\n` for performance reasons).

As you have `}` at the end of match you can use `"__metadata"[\s\S\n]*?\},` where `\n` will trigger multiline match. Or just add `\n` in the end  of your regexp (use lookahead if it shouldn't be part of match)

P.S. it's better to wrap inline code in backticks `` `code` `` and code blocks as in
````
```
code
```
````
as it looks like `\` is missing in your regexp.

@gjsjohnmurray that issue looks mainly about like duplicates in results

**Comment by juergenbosch** [comment]
Thanks great now it works
