### ISSUE TITLE
Javascript debug launch broken

### ISSUE THREAD

**Issue by murrellr** [microsoft/vscode#142199]
Issue Type: <b>Bug</b>

The January 2022 update broke debugging of Javascript using a file URL.  This is one of my launch configurations:

```
		{
			"name": "aTB (172.23.165.1)",
			"request": "launch",
			"type": "pwa-chrome",
			"file": "${workspaceFolder}/_Battery/debug.html?172.23.165.1"
		},

```
When I start a debug session, Chrome used to start with this URL in the address bar:

`file:///C:/workspace/_Battery/debug.html?172.23.165.1
`

Now it starts with this URL and reports "Your file couldn't be accessed".  I have to manually change the "%3F" to "?":

`file:///C:/workspace/_Battery/debug.html%3F172.23.165.1
`

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (7.30GB free)|
|Process Argv|--crash-reporter-id 87c1d683-95a6-416a-b844-66ab3df3e049|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
shortcut-menu-bar|jer|3.0.3
hexeditor|ms-|1.9.4
vscodeintellicode|Vis|1.2.16

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
vscop940:30404999
vsrem710cf:30416617

```

</details>

**Comment by connor4312** [comment]
Will be fixed in the next nightly https://github.com/microsoft/vscode-js-debug#nightly-extension

The query string and route fragment will be encoded only if there's a matching file on disk (`?` is valid in file paths on unix, and `#` is across platforms.) Otherwise they'll be preserved as before.
