### ISSUE TITLE
enableShellIntegration breaks PowerShell PSReadLine module in terminal

### ISSUE THREAD

**Issue by bwgjoseph** [microsoft/vscode#142161]
- VS Code Version: 1.64.0
- OS Version: Windows 10 x64 21H1 (Build 19043)

## Steps to Reproduce:

1. Add `"terminal.integrated.enableShellIntegration": true` to `settings.json`
2. Restart the shell (pwsh v7.2)

## Previous Behavior

My existing PowerShell is setup with `PSReadLine` module 

```ps
// profile.ps1
// omitted
Import-Module PSReadLine
Set-PSReadLineOption -PredictionSource History
Set-PSReadLineOption -PredictionViewStyle ListView
Set-PSReadLineOption -EditMode Windows
// omitted
```

It would look like the following (with listview of history)

![image](https://user-images.githubusercontent.com/37484538/152490405-8a1d5a07-9b82-46db-a23c-25523b4f046f.png)

## New behavior

When `enableShellIntegration` is configured/enabled and restarted the shell, this is how it looks like

![image](https://user-images.githubusercontent.com/37484538/152490575-881bc74a-ef69-4dff-93ff-4d880428efa4.png)

The history does not show up

## Note

I do have other modules installed such as `Oh-My-Posh` and from the looks of it, it seems to be working fine since the theme is showing correctly as before

Not sure if any other modules are affected as well

**Comment by LuanVSO** [comment]
### fix
this function
https://github.com/microsoft/vscode/blob/61ff43bafe4b2e8cd69f18cfe4df691579970522/src/vs/workbench/contrib/terminal/browser/media/shellIntegration.ps1#L45
should be:
```powershell
function Global:PSConsoleHostReadLine {
                $lastRunStatus = $?
                Microsoft.PowerShell.Core\Set-StrictMode -Off
                $tmp = [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace, $ExecutionContext, $lastRunStatus)
                # Write command executed sequence directly to Console to avoid the new line from Write-Host
                [Console]::Write("`e]133;C`a")
                return $tmp
        }

```

**Comment by Tyriar** [comment]
Had to revert, see https://github.com/microsoft/vscode/pull/142211#issuecomment-1030355580

**Comment by TylerLeonhardt** [comment]
![image](https://user-images.githubusercontent.com/2644648/155772986-3528daab-e7ab-498b-b472-a18f6c507612.png)

looks fixed to me
