### ISSUE TITLE
Button to close empty side panel

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#142134]
Issue Type: <b>Feature Request</b>

I started to drag something there, then decided against it. Now there's an open side panel where it opened up in case I dropped the thing there. And I can't close it with a button. Thought there'd be an X or something.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by sbatten** [comment]
@sdegutis noted. you can however drag it closed for now

**Comment by IllusionMH** [comment]
Would be great if there was some permanent close button, so it will be there as in (bottom) panel.

I have few views there that I don't need constantly (References, Problems, some from extensions) and dragging to close each time is tiresome.

Usual flow - "Find all references", check some places, repeat or close view until next search.

@sbatten this one explicitly mentions empty - do I need to create separate issue for permanent button?

**Comment by Gruntfuggly** [comment]
It looks like there isn't a command to toggle the side panel (at least I couldn't see one in the key preferences). It would be useful if there was, so that extensions could open and close it.

@IllusionMH Not quite what you're after, but you can bind the Toggle Side Panel command to a key, which might help.

**Comment by IllusionMH** [comment]
These look contradicting each other: "there isn't a command to toggle the side panel" and "you can bind the Toggle Side Panel command to a key"

`View: Toggle Side Panel` exists has id `workbench.action.toggleAuxiliaryBar` which I think can be executed from extensions.

My point about having actionable UI element that ca be activated with mouse as it is with Panel (Close Panel button, maybe even Maximize Panel button, but it's separate request) and in some way as with Action Bar - click same active element.

At this moment I don't see any controls that would allow me to quickly (not through menu) hide panel with mouse except resizing it.

**Comment by Gruntfuggly** [comment]
Normally the command shows in the key bindings preferences, but it didn't show up for me. if `workbench.action.toggleAuxiliaryBar` does the right thing (it's inconsistently named) then that's great - I can use that in my extension (activitusbar) to add a button. 😄

**Comment by Gruntfuggly** [comment]
Or you could also use this extension: https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-commands

Agree that it should be native though.

**Comment by MakePixelsWork** [comment]
Solution to make the panel disappear, is to move something to it, so it is set and then moving it back to the old location. Now the empty panel closes itself.

Version: 1.64.0 (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 6.3.9600

**Comment by denishowew** [comment]
Yes please to a permanently visible Side Panel close button.  Call me lazy but having to right-click the header and do "Hide Side Panel" is just too much like hard work.  Nor do I want go via "Configure Layout", nor switch to keyboard and use Cmd+J (which I've bound to `workbench.action.toggleAuxiliaryBar`).  The (bottom) Panel has a close button so why not the Side Panel?
