### ISSUE TITLE
[FR][Bug] Make "move to side panel" not sync between multiple vscode windows

### ISSUE THREAD

**Issue by xwang233** [microsoft/vscode#142151]
I just upgraded to the latest `January 2022 (version 1.64)` version of vscode. I found this "move to side panel" function a bit frustrating. 

For example, I opened 2 vscode windows. I want the first have "Terminal" at the bottom while the second have "Terminal" at the right side. Previously, I was able to do this. After the update, when I click "move view to side panel" on "Terminal" of the second window, the "Terminal" of the first window is also moved.

Feature request: please at least provide an option that allows the panel locations to not synchronize between different vscode windows.

**Comment by xwang233** [comment]
Thanks for the comment @gjsjohnmurray @sbatten .

I think this is more like a "bug" or "regression" than "feature request". I'm using the word "FR" to make it look polite. This change is causing actual regression in user experience. Would it make sense to increase the priority for a fix?

**Comment by sbatten** [comment]
closing this as I believe the FR was due to the removal of the bottom panel movement, but this feature has been restored.

**Comment by xwang233** [comment]
@sbatten No, it's not about that. The panel position (bottom or right) shouldn't be synced over different vscode windows, but now it is.

**Comment by sbatten** [comment]
the old behavior (move panel right/left/bottom) has been restored and it is not synced across windows.
