### ISSUE TITLE
TabCompletion not respecting setting

### ISSUE THREAD

**Issue by funnym0nk3y** [microsoft/vscode#142129]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64
- OS Version: Win10

Unfortunately I don't know how I got there. But I had `tab.Completion` on for some time and decided to turn it off. I checked every possibility where this setting could live (`User Settings`, `Workspace Settings` and `Settings`) and that option is either `"editor.tabCompletion": "off",` or not present. Tab completion is still turned on though.

**Comment by jrieken** [comment]
> Tab completion is still turned on though.

What does that mean for you? Please describe in precise steps what you are doing, observing, and expecting

**Comment by funnym0nk3y** [comment]
Sure. With all the things described in my initial post I'm having the following issue: 

When writing the prefix of a snippet it gets shown as usual. 
The snippet still get completed by pressing `Tab` even though TabCompletion is deactivated everywhere. 
I'd expect, when TabCompletion is turned off, that vscode inserts a tab or when already being in a snippet, to jump to the next position defined by `$number`. 

![issue](https://user-images.githubusercontent.com/41870754/152527072-d74d3771-a6ea-4ec1-b12b-646df594c1bb.gif)

**Comment by jrieken** [comment]
Thanks, understood. For us tab completion is actually a different feature - it's about completing without seeing any suggest window. You have the suggest window and don't want to accept a completion with tab. For that you can unbind a keybinding, follow this guide: https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule

**Comment by jrieken** [comment]
Simpler than in guide

<img width="1244" alt="Screen Shot 2022-02-04 at 18 32 16" src="https://user-images.githubusercontent.com/1794099/152575630-950210bf-c18e-4d03-813e-3b3c660adf0a.png">

**Comment by funnym0nk3y** [comment]
Thanks very much! I did not know that!
