### ISSUE TITLE
 when inputting, the word selection menu keeps shaking

### ISSUE THREAD

**Issue by Pathsis** [microsoft/vscode#142155]
Issue Type: <b>Bug</b>

Using the pinyin input method of win11, when inputting, the word selection menu keeps shaking.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.68GB free)|
|Process Argv|--crash-reporter-id 338c5f25-ba25-44d7-b8b1-c4427148c81b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-footnotes|bie|0.0.7
markdown-preview-github-styles|bie|1.0.1
vscode-psl|ing|1.11.4
latex-workshop|Jam|8.23.0
vscode-gutter-preview|kis|0.29.0
vscode-language-pack-zh-hans|MS-|1.64.6
latex-utilities|tec|0.3.7
latex-support|tor|3.10.0
latex-syntax|vom|0.0.7
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
vs360cf:30404996
vsrem710:30416614

```

</details>

**Comment by alexdima** [comment]
Here are some very good recordings from #142253

---

The candidate list flicker when typing.
![1644031125141](https://user-images.githubusercontent.com/5219550/152627899-553de0d0-2120-4df0-b168-a089103e12fe.gif)

It works fine in notepad.
![1644031923984](https://user-images.githubusercontent.com/5219550/152627900-b0e59bf9-806b-43eb-931d-7c6100770ba2.gif)

**Comment by Pathsis** [comment]
Dear @ alexdima , with this issue I would like to submit another issue, did you notice the change in the style of the cursor when typing in pinyin method? In vscode, the style of the cursor is different for pinyin input and western letters input. This creates a big sense of fragmentation. I have examined Atom, and this problem does not exist. Thank you very much!

**Comment by alexdima** [comment]
@Pathsis Please take a look if any of the existing issues cover the problem you're referring to -- https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aeditor-input-IME . If not, please create a new issue with as much detail as possible.
