### ISSUE TITLE
Smoktest fails: `getaddrinfo ENOTFOUND update.code.visualstudio.com`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#142188]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=154018&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=0699ae84-7245-5a45-5eee-80b086af2725

**Comment by bpasero** [comment]
Looks like our call to `update.code.visualstudio.com` failed. Since this is a source of potential flakiness where we do not control the end point, maybe `node-fetch` offers some kind of retry logic.
