### ISSUE TITLE
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

### ISSUE THREAD

**Issue by joaromi** [microsoft/vscode#142175]
We have written the needed data into your clipboard because it was too large to send. Please paste.Visual studio is not able to display Jupyter notebooks or the Changelogs in the extensions store. I believe it might have been caused by a recent update.

**Comment by joaromi** [comment]
Fixed by switching from snap to apt installation.

**Comment by nosratullah** [comment]
> Fixed by switching from snap to apt installation.

Didn't work for me :'(
