### ISSUE TITLE
Allow displaying view titles as names instead of icons in side panel

### ISSUE THREAD

**Issue by symmetriq** [microsoft/vscode#142191]
I was able to get the side panel set up more or less the way I had it before (previously I just moved the "Panel" to the right), but there's one thing still bothering me — the names for views are now icons, which makes them harder to identify and click. In my case, the side panel is wide enough that the actual names will easily fit, so I'd prefer to just display them as text rather than icons.

**Comment by sbatten** [comment]
thanks for the feedback, please see duplicate https://github.com/microsoft/vscode/issues/141391
