### ISSUE TITLE
Sourcemapped stacktraces mark file locations as "undefined"

### ISSUE THREAD

**Issue by ebousse** [microsoft/vscode#142197]
## Summary

In VSCode 1.63.2, out-of-the-box, when running a TypeScript program using Node, the error message provided in the Debug Console is extremely poor: one line of text giving us the runtime error message, with zero indication of the line content or number causing the problem.

By default in VSCode, I suggest that it would be great to at least have the complete output from Node (which include localization of the error in the compiled js file, which is better than nothing). Even better, it would be fantastic to automatically use source maps using `node -r source-map-support/register`, in which case the error localization and description would be directly done in the typescript code, and fully hide the JS underneath.

### VSCode "Run Without Debugging"

Let's run a TS program with a bug in VSCode 1.63.2, using *Run→ Run Without Debugging → Node*. Here is the result:

![Capture d’écran de 2022-02-04 15-25-11](https://user-images.githubusercontent.com/5868014/152546676-209b0ad8-3bb4-439d-92fc-daaac56acdfc.png)

We basically only learn that something was undefined…

### Node

Now let's try again using simply `node` in the embedded terminal:

![Capture d’écran de 2022-02-04 15-25-44](https://user-images.githubusercontent.com/5868014/152547027-cb7c1042-26b7-4c91-917b-06cade74e468.png)

A little better: now we know that the error is in `hello.js` (thus `hello.ts`), and we have an excerpt with the faulty JS line. Could be confusing if the JS is really different than the TS code, but I find it already much more helpful.

### Node with source-map-support

And let's try one last time with Node _source-map-support_ module (https://www.npmjs.com/package/source-map-support)

This requires first running `npm install --save-dev source-map-support`

Then we run Node using `node -r source-map-support/register`, and we get:

![Capture d’écran de 2022-02-04 15-26-06](https://user-images.githubusercontent.com/5868014/152547422-564e19eb-7441-44f0-9081-2128c7757ae3.png)

This time we finally have some proper fault localization: we know which TS file has the error, which line, and we have an excerpt of the faulty TS line of code. Perfect!

My suggestion is to somehow make this very last case the default in VSCode when using "Run With/Without Debugging" and Node.

**Comment by connor4312** [comment]
This is actually the same as https://github.com/microsoft/vscode/issues/122870 --  the debug console doesn't show multiline output when the logged object has additional properties.

The debugger, since early last year, already has its own version of `source-map-support` in that it parses stacktraces in logged error messages and tries to sourcemap their location.

**Comment by ebousse** [comment]
Hi, thanks for the answer. I have updated to VSCode 1.65.0, and indeed multiline output is now back thanks to #122870 being solved.

However, I do believe my feature request still stands, as currently (1.65.0) out-of-the-box here is what I get using the same example as above:

![Capture d’écran de 2022-03-04 10-09-51](https://user-images.githubusercontent.com/5868014/156733846-72111c04-5d98-4183-969f-e4e77bd36103.png)

While there is indeed multiline, the stack trace tries to point us towards an `undefined` file name − meaning we do not even get a pointer towards the faulty `.js` line, and even less towards the faulty `.ts` line.

**Comment by connor4312** [comment]
@ebousse that's not good! Which version of Node.js are you using? Also, does the problem still happen if the program runs for a slightly longer period of time (e.g. if you add a `setTimeout(() => {}, 100)`). Suspect you might be running into a race condition

**Comment by ebousse** [comment]
I'm using node version v16.14.0.

I've tried with a 10s timeout, and the result is similar:

```
Uncaught TypeError TypeError: Cannot read properties of undefined (reading '0')
    at <anonymous> (undefined:2:21)
    at listOnTimeout (undefined:559:17)
    at processTimers (undefined:502:7)
    --- Timeout ---
    at init (undefined:25:19)
    at emitInitNative (undefined:201:43)
    at emitInitScript (undefined:506:3)
    at initAsyncResource (undefined:162:5)
    at Timeout (undefined:196:3)
    at setTimeout (undefined:164:19)
    at <anonymous> (undefined:2:1)
    at Module._compile (undefined:1103:14)
    at Module._extensions..js (undefined:1155:10)
    at Module.load (undefined:981:32)
    at Module._load (undefined:822:12)
    at executeUserEntryPoint (undefined:77:12)
    at <anonymous> (undefined:17:47)
Process exited with code 1
```

**Comment by ebousse** [comment]
I confirm that in a terminal the problem does not appear (here running the program of the original post, without the timeout):

```
$ node build/hello.js
/home/bousse-e/Téléchargements/idl/monprojet/build/hello.js:2
x[0];
 ^

TypeError: Cannot read properties of undefined (reading '0')
    at Object.<anonymous> (/home/bousse-e/Téléchargements/idl/monprojet/build/hello.js:2:2)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

And for comparison, here is what I get when running using VSCode (same as what can be observed in the screenshot above):
```
/usr/bin/node ./build/hello.js
Process exited with code 1
Uncaught TypeError TypeError: Cannot read properties of undefined (reading '0')
    at <anonymous> (undefined:2:2)
    at Module._compile (undefined:1103:14)
    at Module._extensions..js (undefined:1155:10)
    at Module.load (undefined:981:32)
    at Module._load (undefined:822:12)
    at executeUserEntryPoint (undefined:77:12)
    at <anonymous> (undefined:17:47)
```

**Comment by connor4312** [comment]
We've done some refactorings here, and this seems like it's fixed for me in the latest version of VS Code. Please let me know if you still hit this!

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/2230985/166833613-24ac7754-ccf2-4615-92ab-68c0abdba8b9.png">

**Comment by ebousse** [comment]
Glad to hear that :) what version of VSCode should I try?

**Comment by ebousse** [comment]
Sure, here it is: [vscode-debugadapter-2cbeaeac.json.gz](https://github.com/microsoft/vscode/files/8639107/vscode-debugadapter-2cbeaeac.json.gz)

**Comment by connor4312** [comment]
From the logs it looks like you're no longer getting undefined paths, this is what I see in the output:

```
Uncaught TypeError TypeError: Cannot read properties of undefined (reading '0')
    at <anonymous> (/home/bousse-e/Téléchargements/idl/monprojet/build/hello.js:2:2)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:822:12)
    at executeUserEntryPoint (node:internal/modules/run_main:77:12)
    at <anonymous> (node:internal/main/run_main_module:17:47)
```

Is that right?

**Comment by connor4312** [comment]
To verify, run TypeScript code like in my screenshot here: https://github.com/microsoft/vscode/issues/142197#issuecomment-1117980709

Run it a few times. Ensure that the top line of the stacktrace shows in the `.ts` file and not the compiled `.js` file.
