### ISSUE TITLE
Debugging does not work at all

### ISSUE THREAD

**Issue by kajakIYD** [microsoft/vscode#142154]
Issue Type: <b>Bug</b>

While debugging Python scripts, F5 or "Play button" gives no action - the only thing I see is bar with "stop", "play" and "restart" buttons - but this bar just dissapear after few seconds. In terminal no output is printed.
Since last successful debugging session no system updates or other apps were installed, VSCode is up-to-date.
I have tried restarting VSCode and restarting computer ;)

<details><summary> launch.json </summary>
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false
        }
    ]
}
</details>

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (11.10GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Pawe%C5%82%20Fic/Documents/MOLOS.ANALYTICS/Packages/trend_analysis --crash-reporter-id b5861c78-63a8-433f-adf7-5b3b6a81c16d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
systemd-unit-file|coo|1.0.6
gitlens|eam|11.7.0
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.19.0
csharp|ms-|1.24.0
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
vscode-ai|ms-|0.6.28
vscode-ai-remote|ms-|0.7.0
remote-containers|ms-|0.217.1
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.11
cpptools|ms-|1.8.2
vscode-thunder-client|ran|1.11.1
remote-x11|spa|1.5.0
remote-x11-ssh|spa|1.5.0
usql-vscode-ext|usq|0.2.15
azure-iot-edge|vsc|1.25.6
azure-iot-toolkit|vsc|2.16.6
azure-iot-tools|vsc|0.3.0
vscode-iot-device-cube|vsc|0.3.0
vscode-iot-workbench|vsc|0.16.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
vscop940:30404999
vsrem710cf:30416617

```

</details>

**Comment by gjsjohnmurray** [comment]
What language are you trying to debug?

**Comment by kajakIYD** [comment]
@gjsjohnmurray  - thanks for quick response.
I am trying to debu Python scripts.

**Comment by gjsjohnmurray** [comment]
I suggest you use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions. More details at https://code.visualstudio.com/blogs/2021/02/16/extension-bisect

In your case I think you will need to exclude the Python extension(s) from the Bisect. Do this by manually disabling them in the Extensions view, then running the Start Extension Bisect command, then re-enabling them manually before proceeding with the bisect.

**Comment by kajakIYD** [comment]
@gjsjohnmurray I have done what you've suggested, but unfortunately:
![obraz](https://user-images.githubusercontent.com/28728624/152489257-f9436af2-9cce-4ce4-a9e9-e4bbdffcfed1.png)

**Comment by gjsjohnmurray** [comment]
Python debugging is provided by an extension. Please raise your issue in its repository.

/extPython
