### ISSUE TITLE
Search not matching RegExp(Upper Case letters)

### ISSUE THREAD

**Issue by mielpl** [microsoft/vscode#142177]
Issue Type: <b>Bug</b>

Hello developers! There is not matching regexp on search on the left panel 
I'm typing <[A-Z] to find all capital cases but it returns me all cases of my files
![image](https://user-images.githubusercontent.com/71864316/152512884-628123d0-d922-4774-be9a-b294a051014e.png)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz (4 x 3128)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (2.14GB free)|
|Process Argv|--crash-reporter-id 677c27f5-8de4-4652-a47b-788c0be6a69c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|4.1.0
prettier-vscode|esb|9.2.0
auto-rename-tag|for|0.1.9
copilot|Git|1.7.4812
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
vsliveshare|ms-|1.0.5330

(1 theme extension excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30429732
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
vscop341:30404997
vsrem710:30416614

```

</details>

**Comment by gjsjohnmurray** [comment]
Please click here:

![image](https://user-images.githubusercontent.com/6726799/152518635-350da4d4-cfaa-4393-9439-72860ffcce05.png)

**Comment by roblourens** [comment]
Thanks @gjsjohnmurray. Yes, you need to enable case sensitive mode.
