### ISSUE TITLE
No longer able to open from filezilla.

### ISSUE THREAD

**Issue by boringman16** [Microsoft/vscode#14216]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Steps to Reproduce:
1.VSC as default program.
2.Use  Filezilla to view/edit a js file
3. file will not open.

**Comment by roblourens** [comment]
Can you be more specific? Does vsc open, but the file doesn't?

**Comment by bpasero** [comment]
A bunch of users reported issues like that and I think they are all caused by the issue @joaomoreno is tracking for making VS Code the default editor of a file extension.

**Comment by boringman16** [comment]
VSC does open, but code is not loaded, it ask user to open folder.

**Comment by joaomoreno** [comment]
A recent Windows update broke file associations. Please reset VS Code as the default app for that file type.

**Comment by 50l3r** [comment]
i have the same issue

![image](https://i.gyazo.com/c3aaf6457aa94c5f98853d17bf233fff.png)[]
