### ISSUE TITLE
Allow terminal configuration on Linux (currently hard-coded to gnome-terminal).

### ISSUE THREAD

**Issue by Xorcist77** [Microsoft/vscode#1421]
I don't use gnome, and thus don't use gnome-terminal, but VSCode REALLY wants me to. I scaffolded out a new asp.net web project and can run it just fine from my terminal using 'dnx web', but trying to use 'dnx: web' from the command palette inside VSCode tries to launch gnome-terminal, which obviously fails, with the following error:

Error: spawn /usr/bin/gnome-terminal ENOENT

Note that I located workbench.main.js which appears to be the file that is referenced to open the terminal, however changing "usr/bin/gnome-terminal" to "usr/bin/x-terminal-emulator" didn't help. I didn't get any errors, but no terminal opened either... I would have expected it to use whatever terminal I configured in Linux at that point, instead of the hard coded gnome terminal.

I also tried "usr/bin/lxterminal" but that didn't work either...

**Comment by mosamy** [comment]
I solved this by a simple sudo apt-get install gnome-terminal. It is only 11 mb and the seamless experience is worth it

**Comment by Xorcist77** [comment]
@mosamy: That is more of a work around for the poorly designed, hard-coded, implementation currenty provided by VSCode.

A configurable option would be much more appropriate. The fact something like this was hard-coded at all makes me wonder what other hidden gems l'm bound to uncover.

**Comment by PeterBocan** [comment]
It's that hard adding one key into the config? :-1:  Okay.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#3
