### ISSUE TITLE
Version 1.64.0 breaks task quoting

### ISSUE THREAD

**Issue by SeBaconStrip** [microsoft/vscode#142196]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64
- OS Version: Windows 10 Enterprise, 20H2 Build: 19042.1348

Steps to Reproduce:

1. After updating to VS Code 1.64 the following command ist not working anymore

Workspace task
![image](https://user-images.githubusercontent.com/76108307/152546320-a6010d6a-0fb2-4603-96e1-fc44da8cd519.png)

Output
![image](https://user-images.githubusercontent.com/76108307/152546398-9358f009-974b-45aa-8c7d-a6f75f0b4380.png)

**Comment by alexr00** [comment]
Can you share the entire task and also any `terminal.integrated` and `task` settings you have set?

**Comment by hagaigold** [comment]
there are more issues with tasks since 1.64.
some `quoting` not work as expected for  target shell `Command Prompt` on windows.
see also this issue: microsoft/vscode-makefile-tools#275

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "dir",
            "type": "shell",
            "command": "dir"
        },
        {
            "label": "dir_wt_quating",
            "type": "shell",
            "command": {
                "value": "dir",
                "quoting": "strong"
            },
            "problemMatcher": []
        }
    ]
}
```

when trying `dir_wt_quating`, with ``Command Prompt`` as the default terminal:
```
> Executing task: 'dir' <

''dir'' is not recognized as an internal or external command,
operable program or batch file.
The terminal process "C:\WINDOWS\System32\cmd.exe /d /c 'dir'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```

**Comment by hagaigold** [comment]
maybe the title of the issue also should be changed to something like `Version 1.64.0 breaks vscode.tasks.executeTask`

**Comment by SeBaconStrip** [comment]
Task

```
			{
				"label": "label",
				"detail": "Removes compilation directories (X00X) and temporary files (.aa*, .tag, .deploy, .log and .err)",
				"type": "shell",
				"group": "build",
				"command": "chcp 1252 && ",
				"args": ["${workspaceFolder}\\Cleanup.bat"],
				"problemMatcher": [],
				"presentation": {
					"echo": true,
					"reveal": "never",
					"focus": false,
					"panel": "shared",
					"showReuseMessage": true,
					"clear": false
				}
			},
```

Terminal Output
```
> Executing task in folder PMC Files: 'chcp 1252 && ' C:\Projects\Repositories\xxxxxx\XXXXX\xxxxx\Cleanup.bat <

Der Befehl "'chcp" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
The terminal process "C:\WINDOWS\System32\cmd.exe /d /c 'chcp 1252 && ' C:\Projects\Repositories\xxxxx\XXXX\xxxxx\Cleanup.bat" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```

**Comment by hagaigold** [comment]
hi @alexr00,

it is not just quoting.
if you will run the above `dir_wt_quating` example with `PowerShell`, you will notice another issue- `&` is missing:

```
> Executing task: 'dir' <

dir

Terminal will be reused by tasks, press any key to close it.
```

while with VS Code 1.63.2:
```
> Executing task: & 'dir' <

    Directory: C:\......\src


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          2/6/2022   2:30 PM                .vscode
d-----          2/7/2022   2:55 PM                debug
```

**Comment by hagaigold** [comment]
> it is not just quoting.

check this out: #142449

**Comment by alexr00** [comment]
Thanks for pointing this out @hagaigold!

**Comment by drrnkin** [comment]
I found that any task involving a variable substitution like ${workspaceFolder} seems to cause similar errors (also starting in 1.64.0).  Maybe it's the same thing.

**Comment by SeBaconStrip** [comment]
In my case thats not the problem if i remove `chcp 1252 &&` task is working perfectly fine

**Comment by alexr00** [comment]
To verify (MUST use Windows):
1. Set 
```
	"terminal.integrated.automationProfile.windows": {
		"path": "cmd.exe",
	}
```
2. Open a folder and add these tasks:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "dir",
            "type": "shell",
            "command": "dir"
        },
        {
            "label": "dir_wt_quating",
            "type": "shell",
            "command": {
                "value": "dir",
                "quoting": "strong"
            }
        }
    ]
}
```
3. Run the two tasks and verify they succeed.
4. Set 
```
	"terminal.integrated.automationProfile.windows": {
		"path": "powershell.exe",
	}
```
5. Run the two tasks again verify they succeed.

**Comment by hagaigold** [comment]
isn't spawning a task with different quoting settings should be part of the unit tests suite?
