### ISSUE TITLE
VSCode hangs produces error when opening

### ISSUE THREAD

**Issue by SteveCurran** [Microsoft/vscode#14211]
- VSCode Version: 1.61
- OS Version: Windows Server 2012 R2

Steps to Reproduce:

1. Right click vscode run as administrator
2. Takes 2 minutes to open
3. Click on src folder just shows busy indicator and unresponsive
4. Finally get error message ERROR: read ECONNRESET

Task manager shows VSCode processes one is taking over 90% CPU
VSCode unusable.
No extensions installed.

**Comment by roblourens** [comment]
Does it happen if you don't run as administrator? Why do you need to run as admin? We don't usually recommend that.

**Comment by SteveCurran** [comment]
Yes. I am running this on a HyperV VM, and it maybe related to the similar Atom issue.

**Comment by roblourens** [comment]
Which Atom issue is that?

**Comment by bpasero** [comment]
#13882
