### ISSUE TITLE
vscat - bringing VS Code syntax highlighting to the terminal!

### ISSUE THREAD

**Issue by OmarTawfik** [microsoft/vscode#142141]
> TL;DR; I wrote a terminal highlighting library based on VS Code grammars, and wanted to share it with the team, and possibly have a discussion to see if it is useful in a wider context. Please feel free to close it if not relevant/useful.

## Intro

VS Code has developed phenomenally over the last few years, making it the de facto code editor for millions of developers. With extensive styling and theming, developers quickly became comfortable with its syntax highlighting. Having consistent highlighting means:

* Improved code readability.
* Easier and faster code reviews.
* Consistent and clear diagnostic messages.

Unfortunately, this did not translate to CLI tools that the same developers use. Over the years, I worked on a ton of linters/scripts that process code files and print diagnostics to the users, I've been also integrating some OSS ones like `eslint`, `tsc`, `gulp`, etc... and I found myself duplicating the effort to unify how they render error messages.

This library aims to bridge the gap by bringing VS Code grammars and themes to the terminal, and provide quick shortcuts to render diagnostics or diffs using the same layout that developers are used to. I hope that future build tools, apis, and linters can adopt it to provide a consistent experience across all surfaces.

* NPM Package: https://www.npmjs.com/package/vscat
* Source: https://github.com/OmarTawfik/vscat

---

## Features

It supports all 14 VS Code themes (or you can pass in your own theme file), and the 50+ VS Code languages (or you can pass in your own text mate grammar). It also supports the following three modes (please see the NPM package for more examples):

* Highlighting Source Files:

<table>
  <tr>
    <td>📄 <code>typescript</code> 🖌 <code>default-dark-plus</code></td>
    <td>📄 <code>cpp</code> 🖌 <code>default-light-plus</code></td>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/15987992/126025741-d9780625-638e-4bcc-80bd-a20f5f5d3324.png" /></td>
    <td><img src="https://user-images.githubusercontent.com/15987992/126025742-aea70639-e875-42db-9a7e-343961ebb5ac.png" /></td>
  </tr>
</table>

* Highlighting Diffs and Patches:

<table>
  <tr>
    <td>📄 <code>html</code> 🖌 <code>default-dark-plus</code></td>
    <td>📄 <code>python</code> 🖌 <code>tomorrow-night-blue</code></td>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/15987992/126025745-e65964d8-0684-4ffb-840e-e8d95b2775c3.png" /></td>
    <td><img src="https://user-images.githubusercontent.com/15987992/126025746-05a95519-9cf7-4ae5-9399-063989667d51.png" /></td>
  </tr>
</table>

* Highlighting Diagnostics:

<table>
  <tr>
    <td>📄 <code>javascriptreact</code> 🖌 <code>default-high-contrast</code></td>
    <td>📄 <code>javascriptreact</code> 🖌 <code>default-high-contrast</code></td>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/15987992/126025747-e9d80b42-20f3-41d4-b5b1-a0f75c979a07.png" /></td>
    <td><img src="https://user-images.githubusercontent.com/15987992/126025748-70c3a8e3-0fba-462f-aff3-36a6505e59a1.png" /></td>
  </tr>
</table>

---

## Why am I sharing this here?

This was created ultimately because as a user, I love how VS Code and the Monaco editor has unified syntax highlighting across editors and browsers. I want to see the same benefit in the tools I'm using, like `tsc`, `eslint`, `gulp`, and others. I want to see a world where cli tool authors can use something like this to unify how syntax is highlighted in the terminal as well. I can imagine a future where it automatically detects the VS Code theme I use and reuse that in my iTerm window as well.

Sharing here for feedback and discussion. Please let me know if there is somewhere else I can/should share this in. Unfortunately vscode repo doesn't have a discussions tab (yet).

**Comment by Tyriar** [comment]
Might be misunderstanding, but I don't think we could use something like this in vscode's core since the program running in the terminal is in control of how it renders things and we can't mess with that or bad things will probably happen. I don't feel like unifying how syntax highlighting works is really possible outside of the user learning to pipe the output through your tool or something. Did you have something in particular in mind I'm not seeing?

**Comment by OmarTawfik** [comment]
I don't think VS Code should reuse/implement such functionality. This is up to CLI tools that are commonly running along/inside the editor. One thing the editor can do is perhaps make it possible to fetch/read the currently configured theme name (TOL: cli command?).

Perhaps I should have made the post clearer. I'm just posting here as an FYI. A hat tip to the VS Code team, since there is no discussion tab in this repo. I'll close this if/since there is no actionable steps.

**Comment by Tyriar** [comment]
@OmarTawfik you could mostly get the user's default theme by checking the user's [settings.json file](https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations), but that would ignore when a particular workspace overrides it.

@aeschli is there any easy way to query the current theme from outside the application?

**Comment by OmarTawfik** [comment]
Perhaps then as an environment variable, that is defined/exposed to the built in terminal? At least tools can reuse that (if it was defined) and render code that looks the same as the editor next to it.
It would also work with workspace overrides. I'm not sure if it can change at runtime (if user changes it) without recreating the terminal, but that would be a rare corner case.

**Comment by Tyriar** [comment]
Seems like too niche of a use case to expose an environment variable, we try to keep vscode-specific variables in the terminal to a minimum/clean. You could create a companion vscode extension and then use either the EnvironmentVariableCollection API to set an environment variable, or communicate back to your CLI to set the theme when it changes (by checking config in the extension). Your best approach imo is probably to just parse the settings.json file yourself based on where the `code` CLI lives on the `$PATH`

**Comment by aeschli** [comment]
Yes, reading the user settings file is what I would have suggested too. If you have your own companion extension that updates the settings of your library.
