### ISSUE TITLE
WSL Auto Update broke `code` CLI

### ISSUE THREAD

**Issue by CodeMan99** [microsoft/vscode#142123]
Does this issue occur when all extensions are disabled?: Unknown

- VS Code Version:
- OS Version:

Steps to Reproduce:

Automatic update occurred.

```
$ code .
Installing VS Code Server for x64 (5554b12acf27056905806867f251c859323ff7e9)
Downloading: 100%
Unpacking: 100%
Unpacked 2158 files and folders to /home/cody/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9.
/mnt/c/Users/11954/.vscode/extensions/ms-vscode-remote.remote-wsl-0.63.13/scripts/wslCode.sh: 69: /home/cody/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code: not found
```

Further attempts to use `code .` also errors.

```
$ code
/mnt/c/Users/11954/.vscode/extensions/ms-vscode-remote.remote-wsl-0.63.13/scripts/wslCode.sh: 69: /home/cody/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code: not found
```

**Comment by CodeMan99** [comment]
I also have two different "vscode-server" folders:

```
# output from ls -l
-rwxr-xr-x 1 cody cody 230 Feb  2 23:21 /home/cody/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code-server
-rwxr-xr-x 1 cody cody 335 Dec 15 04:38 /home/cody/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/bin/code
```

**Comment by CodeMan99** [comment]
Opening VSCode via the start menu seem to magically fix the issue. 🤷

**Comment by myusrn** [comment]
I just started getting the same issue, details below, in both my win11 wslg ubuntu and kali-linux distro setups. If i delete the `/home/<my wsl distro username>/.vscode-server-server` executing `code .` redownloads those bits and generates the same error.

As suggested above if i opened win11 vscode, which appeared to have just applied January 2022 (version 1.64) update, and then retried launching it from win11 wslg distro cli things are working again.

```
code .
/mnt/c/Users/<my windows username>/.vscode/extensions/ms-vscode-remote.remote-wsl-0.63.13/scripts/wslCode.sh: 69: 
/home/<my wsl distro username>/.vscode-server-server/bin/5554b12acf27056905806867f251c859323ff7e9/bin/code: not found
```

**Comment by fre-ben** [comment]
> Opening VSCode via the start menu seems to have magically fix the issue. 🤷

Did the trick for me as well, had to start it manually once via Windows. Now the `code x` command works in WSL2 again.

**Comment by SethTales** [comment]
Opening VS code via start menu also fixed it for me. `code` command works again

**Comment by jwatilo** [comment]
Thank God I found this issue report!
Exact same problem with me, also, and doing the "open in native windows first" trick got me up and running again.

**Comment by CodeMan99** [comment]
Re-opening as this seems to be affecting many users, suggesting a migration issue?

**Comment by suvadeep89** [comment]
Facing this exact same issue across multiple linux distros in WSL2 (Centos, Ubuntu, Fedora). Suddenly VSCode update has broken all these

**Comment by benafischer94** [comment]
Can confirm the issue when trying to open with code . within a directory on WSL (Ubuntu 20.04.) Opening VSC from the start menu, then within the same WSL instance trying to start again it works as expected.

**Comment by microhobby** [comment]
Maybe another tip that can be useful, in my case I don't let VS Code update the extensions automatically, so what solved it for me with this January 2022 version was to update the remote and WSL remote extensions to the latest versions ...

**Comment by eitsupi** [comment]
seems related to https://github.com/microsoft/vscode-remote-release/issues/6285

**Comment by sauravbhise** [comment]
Open the start menu and type "code" and hit enter. It will open VS Code. Now try running the `code` command again (in your linux distro terminal) and it should work.
This worked for me. Seems to be an issue with the auto-update.

**Comment by aeschli** [comment]
There was a new Remote-WSL version with the fix. I suspect only after the restart you had the new version.

**Comment by DonKirkham** [comment]
Many posters have stated that restarting VS Code worked for them, but that was not my experience. I was unable to get this working with any version of Remote-WSL version 0.64.x.  I went back to version 0.63.13 and everything returned to normal.

I hope this helps others!

**Comment by CodeMan99** [comment]
@DonKirkham There are many better solutions in the related issue (https://github.com/microsoft/vscode-remote-release/issues/6285)

**Comment by DonKirkham** [comment]
> @DonKirkham There are many better solutions in the related issue ([microsoft/vscode-remote-release#6285](https://github.com/microsoft/vscode-remote-release/issues/6285))

Thank you. I was able to get it working.
