### ISSUE TITLE
The padding of markdown preview is broken when zooming up

### ISSUE THREAD

**Issue by ubnt-intrepid** [Microsoft/vscode#14218]
- VSCode Version: 1.6.1
- OS Version: Windows 10 Home 64bit build 14393.321

Steps to Reproduce:

1. Open any Markdown file
2. Open Markdown preview (`Ctrl + Shift + V`)
3. Zoom up (`Ctrl + ;`)

![image](https://cloud.githubusercontent.com/assets/7354350/19624613/cca22ccc-9939-11e6-928f-2b5d8a911897.png)

Notes:
* The problem occurs only when zooming _up_, not zooming _down_.

**Comment by roblourens** [comment]
Thanks, this is #5745
