### ISSUE TITLE
Accessibility and parameter hints

### ISSUE THREAD

**Issue by sine-w** [microsoft/vscode#142153]
- VS Code Version: 1.64.0
- OS Version: Windows 10 home 21h1 
- nvda version: 2021.3.1

## Problems brief description

parameter hints(below called hints) is not always reported by nvda screen reader 

## Steps to reproduce
Say I have the following python script:

def func(str_=None, happy=True):
    pass

for ease of illustration, below I will use x to mark the position of cursor, 
ctrl+shift+space will be expressed as hint hotkey

func(x)
- if I press the hint hotkey the first time, the nvda will report 'str_=, hint'
- if I press the hotkey the second time, nvda do not report the hint
- I try moving the cursor out of the bracket and moving into the bracket again, i.e. funcx() -> func(x) the hint hotkey do report the hint again

I try entering the first Parameter:
func(str_='hi',x)
- if I press the hotkey at the above position, nvda do not report any hint

Please advice me if I am doing anything wrong, thanks.

**Comment by isidorn** [comment]
@sine-w you are not doing anything wrong. Parameter hints use aria alert (live region) to announce its content. This is not a good approach and ideally we would do the same as the suggest widget does (move focus into the parameter hints and use `activedescendent` to make screen readers aware of the editor - parameter hints relationship).
That though has a problem, when the parameter hints get closed, the editor title and content would get re-read. So we would first have to tackle https://github.com/microsoft/vscode/issues/89098#issuecomment-1031505427 before we do the `activedescendant` work.

@jrieken @mjbvz who owns the parameter hints widget?

Here's a sketch of a PR that I did some time back which changes the paremeter hints to do exactly what I mention above - to use `activedescendant` https://github.com/microsoft/vscode/pull/93606/files

**Comment by isidorn** [comment]
Let's close as dup of https://github.com/microsoft/vscode/issues/90874
And I will move my comment to that issue.
