### ISSUE TITLE
♿❗Breaking Issue - RTL Support❗🚑

### ISSUE THREAD

**Issue by babakfp** [microsoft/vscode#142277]
This text

![Screenshot 2022-02-05 071006](https://user-images.githubusercontent.com/44144724/152647574-50b65d69-9e86-4988-8b31-9f6bf06f5e78.png)

![Screenshot 2022-02-05 070926](https://user-images.githubusercontent.com/44144724/152647451-0d268c53-cf75-4789-885f-077aa84a4601.png)

Most look like this:

![Screenshot 2022-02-05 070826](https://user-images.githubusercontent.com/44144724/152647415-7a7aafdc-7090-41ab-9757-5336e2c519be.png)

Looks correct without that English word:

![Screenshot 2022-02-05 071716](https://user-images.githubusercontent.com/44144724/152647682-5007e6b2-0a01-4e4d-bd26-5b1f7c98310e.png)

---

![Screenshot 2022-02-05 072308](https://user-images.githubusercontent.com/44144724/152647846-4ea9fc94-8e6a-4b53-a86c-eec180a58987.png)

**Comment by babakfp** [comment]
@TylerLeonhardt 
Come on. Such a big issue **doesn't deserve** to get closed. I understand that when a problem doesn't affect us, we just don't care about it. But here I'm **asking you guys to help** to solve this **major problem**. Please reopen the issue.
I'm available on Telegram https://t.me/babakfp to help you guys on this topic. Ask me your questions.

@alexdima (have a look at my explanation)
@HamzaAbdullahMoh
@chadidi
@danyeh (😑)
@Kalmuraee
@janbaltus (dude👍)
@Aminadav
@saibimajdi
@ahamidou
@mahrousfci
@eyalalonn
@elkebirmed
@kazemihabib
@atlanteh
@iddan
@kookma
@Parsoa
@athamzaabdullah (read the explanation in this comment, that's why this problem isn't a priority)
@urielha
@omidgolparvar (این مشکل هنوز حل نشده ولی تو احتمالا الان پدر شدی😂😂)
@akosyakov
@Javanmardi
@tomerm
@adir01
@amirbrans
@amer1616
@jb6
@nathangibson
@MSKhodadady (Telegram also have problems with RTL, but it's better than vsCode)
@KL13NT
@Kagetsuki
@VehpuS
@NotWearingPants
@rafidka
@lior5654 (2022 😂)
@TheEhsanSarshar (feel free to contact me on Telegram https://t.me/babakfp)
@AhmedElTabarani
@marktani
@ebraminio (۲۰۲۲ انگار نه انگار)
@michael-james
@sarmadka
@lwcvl
@drewpotter
@fireheart2008
@RaiKoHoff
@hpwamr
@zspitz
@avipars
@sixtyfive
@RexNext
@chromer030
@amiria703

**Comment by zspitz** [comment]
@babakfp Why do you feel this issue isn't covered by #11770 ?

**Comment by babakfp** [comment]
> Thanks for creating this issue! We figured it's covering the same as another one we already have. Thus, we closed this one as a duplicate. You can search for [similar existing issues](https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+). See also our [issue reporting guidelines](https://aka.ms/vscodeissuereporting).
> 
> Happy Coding!

But aren't you just adding it to the (not-to-do list)? Isn't it best to take time and work on it to fix it forever? It's obviously not great for you guys too to deal with the same issue again and again and again. Do JetBrains's products support RTL correctly? If it doesn't, it's a big win for vsCode. What about other editors? I'm on Telegram https://t.me/babakfp, I'll answer all of your questions, contact me anytime and I'll stay in contact as much as it takes to solve this problem. 

@vscode-triage-bot

**Comment by babakfp** [comment]
> @babakfp Why do you feel this issue isn't covered by #11770 ?

As you can see, it's a big confusion:

![Screenshot 2022-02-05 095447](https://user-images.githubusercontent.com/44144724/152653159-6d270fe7-e609-4027-8d0b-1b31cbd8257d.png)

**Comment by zspitz** [comment]
@babakfp That confusion is cleared up in later comments.

>Also, it's not all about the text being on the right side / starting from right to left

No, it's not. I would say that isn't even the main issue. There are actually a number of issues around this, e.g.:

* RTL1 LTR RTL2 needs to reverse direction and read RTL2 LTR RTL1
* Parentheses (and other pair characters) need to be visually reversed if they're surrounding RTL text
* Sets of numbers should not reverse direction within RTL text

And what makes this all worse, is that VS Code has a lot of custom positioning around cursor/selection placement that has to handle all of this.

All of this is covered in various comments in that thread, and in linked issues.

**Comment by babakfp** [comment]
> And what makes this all worse, is that VS Code has a lot of custom positioning around cursor/selection placement that has to handle all of this.

That doesn't sound correct. Let's walk through with an example because if I read this tomorrow, I probably going to get confused😂. This is the text in Farsi/Persian:

![Screenshot 2022-02-05 111217](https://user-images.githubusercontent.com/44144724/152655616-92fd3737-6776-4545-9d38-3fb94788d36d.png)


If I understand it correctly, you are saying that if the second letter was in English, it should be placed at the cursor's first position. So it's going to be like this:

![Screenshot 2022-02-05 111643](https://user-images.githubusercontent.com/44144724/152655708-36c6891e-a622-4f69-9972-91e472498c4d.png)

This isn't right because nothing about the input should change!. This is the correct example:
![Screenshot 2022-02-05 111833](https://user-images.githubusercontent.com/44144724/152655769-94643c03-b6ec-4cca-b8b1-59bf754aeb6b.png)

Same as how it works on the web. If I copy a mixed lang text like (سلام babakfp خوبی؟) from the vsCode and paste it somewhere on the web, it should look the same (and vice versa).

---

The biggest and breaking issue here is this:

> This text
> 
> ![Screenshot 2022-02-05 071006](https://user-images.githubusercontent.com/44144724/152647574-50b65d69-9e86-4988-8b31-9f6bf06f5e78.png)
> 
> Most look like this:
> 
> ![Screenshot 2022-02-05 070826](https://user-images.githubusercontent.com/44144724/152647415-7a7aafdc-7090-41ab-9757-5336e2c519be.png)

(Not talking about the text being on the right side).


---

> Parentheses (and other pair characters) need to be visually reversed if they're surrounding RTL text
> Sets of numbers should not reverse direction within RTL text


Any visual examples?

**Comment by AhmedElTabarani** [comment]
> @babakfp Why do you feel this issue isn't covered by #11770 ?

The #11770 issue It has become a basket that any problems related to RTL languages ​​are putted into it

There may be various different problems but on the same topic. 

Have you recorded the closed problems that may have different aspects of the problem?

**Comment by babakfp** [comment]
> The https://github.com/microsoft/vscode/issues/11770 issue It has become a basket that any problems related to RTL languages ​​are putted into it

Yep. that's exactly what is happening.

**Comment by AhmedElTabarani** [comment]
@kieferrm 
Can after 'Iteration Plan for January 2022 #139607' end, add #11770 in February's plan and try to solve some RTL problems?

It's not only about the display, there are side problems in the terminal or in the editor, but it was closed under the idea of that it is a duplicate

**Comment by babakfp** [comment]
Maybe something like this for each line:
https://svelte.dev/repl/edf7fdef9634479b9d08064b4fad9b26?version=3.46.4
🤷‍♂️

The same happens on Telegram:
https://user-images.githubusercontent.com/44144724/152657185-e90ae47b-de30-403e-b4de-7538734fc1e4.mp4

**Comment by babakfp** [comment]
😐

**Comment by nathangibson** [comment]
@babakfp Thank you for looping me in. I agree that #11770 has a confusing history. As I understand it, the issue you're describing has to do with VS Code either detecting the base line direction automatically (per Unicode BiDi algorithm) or being able to set the direction. 

#11770 does have some discussion of this, but the issues #65648, #65855, and #4994 are more concise and targeted. Those are all still open. Perhaps you'd want to continue the discussion there?

I am with you that I hope these issues get put into the pipeline and resolved soon!

**Comment by nathangibson** [comment]
@zspitz I appreciate the clarity you've brought to this over at #11770!

**Comment by amiria703** [comment]
This issue is a disaster,
We should have separate issues for each problem and track each one on its own issue rather than mixing them in just one [#11770](https://github.com/microsoft/vscode/issues/11770)

**Comment by babakfp** [comment]
@TylerLeonhardt ?

**Comment by babakfp** [comment]
Hi there @alexr00
Anyone bored to help fix this bug?
DM me in Telegram https://t.me/babakfp if you needed help

**Comment by AhmedElTabarani** [comment]
> Hi there @alexr00 Anyone bored to help fix this bug? DM me in Telegram https://t.me/babakfp if you needed help

I'm sorry, you did a great job but can't you be a little more formal and talk about it professionally
I respect what you did, and you alerted us about it
But you have become completely random and always know about communicating with you on Telegram in a strange way. Why is this?

**Comment by babakfp** [comment]
Hi @AhmedElTabarani
Thank you so much. Yes, I'm trying to let them know that this is a big problem with vsCode and it must get fixed as soon as possible. Unfortunately, no one cares about our problems. It's not even like a small problem for a small group of people, it's a big problem for probably millions of people.
I'm not the kind of person to talk about this kind of stuff in a professional way. As a user what I see is that they don't care about this problem and not caring about your users problems isn't professional.
Telegram is a global way of communicating with other people but I guess it may sound weird when I say it over and over again. My only intention is for this problem to get fixed, nothing more or else.
I gonna try to talk with YouTuber to make a video about this and then vsCode may decide to fix it🤷‍♂️.
Thanks🌸🌸

**Comment by lwcvl** [comment]
@babakfp Thanks for pushing hard for this. I would like to report on it for the online magazine www.digitalorientalist.com. May I use the images you have posted here? Maybe you can contact me off GitHub - I can't immediately track you down but I think you should have no problem contacting me.

**Comment by babakfp** [comment]
Thank you, everyone🌼🌼

@ForrestKnight
@developedbyed
@jamesqquick
@clementmihailescu
@benawad
Frying Pan ??
@hswolff
@shiffman Choo choo!
@CalebCurry
Dani Krossing ??
@iamshaunjp 🥷

**Comment by babakfp** [comment]
What da hell dude!
@TylerLeonhardt
Which team's responsibility this is? Don't you people get paid? It's not been fixed since 2016! HELLOOOOO?
