### ISSUE TITLE
Please provide a way to reliably and unconditionally disable terminal.integrated.autoReplies

### ISSUE THREAD

**Issue by raggi** [microsoft/vscode#142245]
In the most recent release announcement a new feature for terminal automatic replies was demonstrated. In the following documentation it describes a way to disable individual automatic replies by setting the response action to null. It seems that this approach requires careful monitoring of newly introduced replies to ensure that they're always all disabled.

I would like a way to unconditionally disable this behavior for all possible cases, as in all use cases I am currently affected by, the only outcome for this feature for me could be an undesired outcome.

**Comment by Tyriar** [comment]
I don't think there will ever be another default, we could add a disable setting though. Are you affected by the current default or are you just concerned about something potentially going wrong?

**Comment by Tyriar** [comment]
Thanks for the feedback, I'm planning on disabling it by default in the upcoming recovery release: https://github.com/microsoft/vscode/issues/142341#issuecomment-1031860237
