### ISSUE TITLE
GetStarted page content ...

### ISSUE THREAD

**Issue by cdmCEC** [microsoft/vscode#142223]
would be beneficial for this page to include a link to both the current version of the Release Notes AND the archive of all previous release notes.

**Comment by cdmCEC** [comment]
... in some sense, this is just semantics ...

in a VSCode session "Alt+H+R" gets the current version of the Release Notes ...

and these, in turn, contain the link to the page hosting the Release Notes online (https://code.visualstudio.com/updates/v1_64)

which, in the left margin, serves links to what is effectively a two year archive of Release Notes back to v1_43 ...

going back further can be achieved via direct URL modification; i.e. pointing a browser to: https://code.visualstudio.com/updates/v1_42

**Comment by JacksonKearl** [comment]
Could you show an image of the screen you're requesting be changed?

**Comment by cdmCEC** [comment]
![image](https://user-images.githubusercontent.com/78786150/152609031-b089c420-177a-4216-a259-9e3b14a918ad.png)

**Comment by JacksonKearl** [comment]
And you want a link from where on this page to what exactly?

**Comment by cdmCEC** [comment]
per above ... in some sense, this is just semantics ...

that page is probably a focus of "newer" users ... in that context, a link or button that launches the Release Notes (equivalent to "Alt+H+R" on the keyboard ... which, "newer" users might not immediately appreciate) could be added along with a link to the online version of the Release Notes (https://code.visualstudio.com/updates/) ...

so, the suggestion would be to add those two items, for the benefit of "newer" users, to a rather sparse "Get Started" page ...

if this feels like little value added, then i am happy to "Close with comment" ...

**Comment by JacksonKearl** [comment]
We've talked about a blending of release notes and walkthroughs, or potentially as a start item. The concern is always the balance between providing too few options to satisfy the variety of potential use cases, or providing too many options and overloading the page with more choices than anyone wants to consider.

cc @digitarald what do you think?

**Comment by digitarald** [comment]
@cdmCEC more links might be interesting if they add value for users interested in expanding their VS Code skills. Some of those links are in the walkthroughs, but the Help menu holds most of those right now. From all the possible links we could add, I'd be curious on what a new user would get out of release notes specifically though.

**Comment by cdmCEC** [comment]
fair enough ... and entirely reasonable.
