### ISSUE TITLE
1.64 Breaks Problems panel and codeActionsOnSave

### ISSUE THREAD

**Issue by brooketopcoder** [microsoft/vscode#142244]
Issue Type: <b>Bug</b>

Greetings!

I had tslint w/the TSLint plugin working perfectly yesterday. I actually created our internal documentation and updated our readme to explicitly instruct our team how to set up their environments, etc.. I verified my instructions several times yesterday.

I go to start work today, and I see release notes for 1.64, and guess what, my linting setup no longer works...

The TSLint and ESLint plugins no longer show any issues in the Problems panel.

Also, tslint and eslint are no longer fixing issues on save with the following settings:

    "editor.codeActionsOnSave": {
        "source.fixAll.tslint": true,
        "source.fixAll.eslint": true,
    },

I've confirmed tslint and eslint continue to work normally from the CLI.

I also confirmed that formatOnSave continues to work correctly:

    "editor.formatOnSave": true,

After a lot of frustration, I tried rolling back to version 1.63, and the Problems panel displayed the issues correctly; however, issues still weren't fixing on save.

The only problem w/rolling back to 1.63, is that the Repositories panel no longer shows anything in 1.63.

I've repeated this experiment 3 times. 1.63 correctly supports the Problems panel but not the Repositories panel, and 1.64 correctly supports the Repositories panel but not the Problems panel. Neither version supports codeActionsOnSave anymore.

We need to get this fixed asap. It's quite poor timing b/c I have been advocating to switch to this setup, and the 1st day we start using it, it breaks.

Please let me know if there's anything else I can do to help.

Thanks!
~b

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.17134
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.36GB free)|
|Process Argv|--crash-reporter-id 453a394b-6d51-4765-bb08-ed11d1c009a4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|13.2.2
gitlens|eam|11.7.0
vscode-typescript-tslint-plugin|ms-|1.3.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30429731
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
testflightcf:30433671
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vscop341:30404997
vsrem710:30416614

```

</details>

**Comment by dsherret** [comment]
Sounds like #142139

TypeScript language service plugins are don’t work on Windows in 1.64.

**Comment by brooketopcoder** [comment]
thanks @dsherret . that is indeed the same issue.
