### ISSUE TITLE
Settings Sync with Microsoft account hangs forever

### ISSUE THREAD

**Issue by igoracmelo** [microsoft/vscode#142286]
Does this issue occur when all extensions are disabled?: Yes.

- VS Code Version: (Tried snap, .deb, tar.gz and also latest insiders .deb)
![Screenshot_20220205_160402](https://user-images.githubusercontent.com/85039990/152655286-42e91a3b-d89c-421b-bc20-48033e0cb631.png)

- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:
1. Open Settings
2. Click on Turn on Settings Sync
3. Sign in & Turn on
4. Sign in with Microsoft
5. Hangs forever here
![image](https://user-images.githubusercontent.com/85039990/152655370-02103a28-f475-4501-aa07-4cc7985ab29e.png)

**Comment by TylerLeonhardt** [comment]
@igoracmelo couple questions:

1. are you using Firefox?
2. I see that it says: `localhost:....` can you copy it and paste it and tell me if it starts with `https`?
3. What window manager are you using?
4. can you try out the latest insider build of VS Code: http://code.visualstudio.com/insiders  ?

**Comment by igoracmelo** [comment]
@TylerLeonhardt 
Unfortunately I cannot reproduce anymore.
It is working ok here on both Firefox and Chromium-based browsers.

**Comment by TylerLeonhardt** [comment]
If you see it again, don't be afraid to reach out!
