### ISSUE TITLE
Lightbulb always brings error: "Running the contributed command:'_internal_command_delegation' failed""

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode#14223]
It's impossible to me to use the lightbulb in any language using the current insider build. Everytime I want to apply a quick fix I receive the message 

> Running the contributed command:'_internal_command_delegation' failed.

I'm on a Windows 10 machine

**Comment by peterblazejewicz** [comment]
Version 1.7.0-insider (1.7.0-insider)
788caba5a3ca1c2b137353f4384bb0e026db1a31
2016-10-21T23:33:37.032Z
OS X: 10.12 (16A323)

**Comment by fergalmoran** [comment]
Same on Ubuntu 16.04
`Version 1.7.0-insider
Commit 788caba5a3ca1c2b137353f4384bb0e026db1a31
Date 2016-10-21T23:36:48.362Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0`

**Comment by ddecours** [comment]
Also getting under VSCode Version 1.7.0-insider (1.7.0-insider)
Using Win 8.1
angular-cli: 1.0.0-beta.16
node: 6.7.0
os: win32 x64

I'm assuming this is a bug related to VSCode changes
