### ISSUE TITLE
'$' function not working

### ISSUE THREAD

**Issue by gcall166** [microsoft/vscode#142294]
Issue Type: <b>Bug</b>

I am a new user, and this string is not working:

try {const response=await request('${baseUrl}&url=https://api.opensolar.com/api'
 
As all the string is in the same color, it seems the '$' function is not working. 
Please advise, thnaks
Simon

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100T CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.78GB free)|
|Process Argv|--crash-reporter-id 0450d145-7d35-4db5-8d66-418139e2f9d2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30433058
pythonvs932:30410667
wslgetstarted:30433507
vscop453:30404998
vsrem710:30416614
vscscmwlcmt:30433761

```

</details>

**Comment by gcall166** [comment]
Hey, Many thanks. Now I know about backticks!!!!! Simon

Yours,
Simon Tattersall
858-333-7568

**Comment by dbaeumer** [comment]
@IllusionMH thanks for the answer.
