### ISSUE TITLE
One extra pixel at the top of the blinking cursor with Microsoft Pinyin IME

### ISSUE THREAD

**Issue by liyuhang1997** [microsoft/vscode#142291]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.0 stable and 1.65.0-insider
- OS Version: Windows 10 21H1

Steps to Reproduce:

~~Switch between different files, there is a probability of appearing after regenerating the cursor.~~
Switch Microsoft Pinyin IME and typing. See: https://github.com/microsoft/vscode/issues/142253#issuecomment-1030636769

https://user-images.githubusercontent.com/16591303/152656890-9eeeee09-4720-4561-81e6-cbc755b86db7.mp4

![QQ截图20220206033620](https://user-images.githubusercontent.com/16591303/152656905-5468679d-8791-4168-adc4-09d779594660.png)
![QQ截图20220206033719](https://user-images.githubusercontent.com/16591303/152656907-842b82e8-c970-4aba-958b-8d1fe22ef026.png)
![QQ截图20220206033810](https://user-images.githubusercontent.com/16591303/152656911-b34a5533-9bb8-4655-8a34-8394b2c7f1e6.png)

**Comment by alexdima** [comment]
I could no longer reproduce after https://github.com/microsoft/vscode/commit/1dbc782ab9302333ff1b08a7fa15381835a85738 , so I believe that a left over styling was the root cause here.

**Comment by alexdima** [comment]
\closedWith 1dbc782ab9302333ff1b08a7fa15381835a85738

**Comment by HaloWang** [comment]
![image](https://user-images.githubusercontent.com/7344724/155036731-611375b4-4ca2-4660-9975-e9167762b470.png)

This bug still exist in `v1.64.2`

![image](https://user-images.githubusercontent.com/7344724/155036929-41163da6-2abc-4872-8fd9-d8586f79ea3d.png)

https://user-images.githubusercontent.com/7344724/155038497-e84c9c9d-67ec-4dfb-b5e1-99fb02645040.mp4

1. Open vscode with dark theme
2. Switch IME 微软拼音(Microsoft Pinyin) from English mode to Chinese mode
3. Type `A`, `S`, `D`, then `Backspace` to delete them
4. Find one extra pixel
