### ISSUE TITLE
Property rename not working in Angular components

### ISSUE THREAD

**Issue by moniuch** [microsoft/vscode#142298]
Could be considered a bug, could be considered a feature.

In angular cli app:

**Component in separate files (html + ts)**

Rename a component property doesn't update template when initiated from ts.
It works when initiated from template though.

```ts
// mycomp.component.ts
@Component({
  selector: 'my-comp',
  templateUrl: './mycomp.component.html'.
})
export class MyComponent {
  foo: any;
} 
```

```html
<!-- mycomp.component.html -->
<div>{{ foo }}</div>
```

- `foo` **won't** get renamed in html when rename (highlight + F2) initiated from ts.
- `foo` **will** get renamed in ts when rename initiated from html.

**Single file component (ts)**

```ts
@Component({
  selector: 'my-comp',
  template: `<div>{{ foo }}</div>`
})
class MyComp {
  foo: any;
}
```

- Rename won't get initiated from within html template (This element cannot be renamed)
- `foo` **will not** get renamed in html when rename initiated from within class.

**Comment by dsherret** [comment]
@moniuch what OS and VS code version are you using?

**Comment by moniuch** [comment]
VSCode 1.64.0
macOS Monterey

**Comment by mjbvz** [comment]
VS Code doesn't ship with built-in angular support. That is provided by an extension. Please file the issue against them
