### ISSUE TITLE
Close Workspace/Folder keybinding doesn't work by default on 1.64

### ISSUE THREAD

**Issue by Xanewok** [microsoft/vscode#142278]
Issue Type: <b>Bug</b>

Once I updated to the new version, it seems that the Ctrl+K, F sequence doesn't work by default to close the folder. I had to manually add
```json
    {
        "key": "ctrl+k f",
        "command": "workbench.action.closeFolder"
    }
```
in the keybindings.json and can confirm that this fixes the issue.

I couldn't find any relevant note in the [release notes](https://code.visualstudio.com/updates/v1_64) so I figured this might be a bug.

Thanks!

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:23:11.224Z)
OS version: Linux x64 5.13.0-28-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 2839)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|31.28GB (20.51GB free)|
|Process Argv|--unity-launch --crash-reporter-id f575e733-8436-4c04-a211-a933ab8963d9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.2
vscode-intelephense-client|bme|1.8.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.2.2
vscode-wasm|dts|1.3.1
gitlens|eam|11.7.0
prettier-vscode|esb|9.2.0
remotehub|Git|0.24.0
vscode-pull-request-github|Git|0.36.0
nightlight|int|1.4.1
vscode-graphviz|joa|0.0.6
solidity|Jua|0.0.136
dotenv|mik|1.0.1
lalrpop-highlight|mnx|0.0.1
vscode-docker|ms-|1.19.0
csharp|ms-|1.24.0
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.1
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
live-server|ms-|0.2.12
powershell|ms-|2021.12.0
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.5330
vscode-react-native|msj|1.9.0
vscode-jest|Ort|4.2.1
java|red|1.3.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.3
llvm|RRe|0.1.1
rust|rus|0.7.8
crates|ser|0.5.10
trailing-spaces|sha|0.3.1
rewrap|stk|1.16.1
unity-debug|Uni|3.0.2
vscodeintellicode|Vis|1.2.16
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0
vim|vsc|1.21.10

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
testflight:30433670
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vscop940:30404999
vsrem710cf:30416617

```

</details>

**Comment by gjsjohnmurray** [comment]
Here's what my Keyboard Shortcuts editor shows (1.64).

![image](https://user-images.githubusercontent.com/6726799/152650513-dae5c284-ee42-4169-8a2e-774c6fd91e1a.png)

What does yours look like?

**Comment by Xanewok** [comment]
![image](https://user-images.githubusercontent.com/3093213/152650628-a80b1561-28ee-48fc-b92c-b7d4e5af041d.png)

Although I did remove the user and it seems to be... working? In the meantime I pruned some extensions that I was not using, so there's a good chance that some extension interacted badly with it. I'm going to close this since it seems to be working - sorry for the noise!
