### ISSUE TITLE
Search within found files

### ISSUE THREAD

**Issue by gilescope** [microsoft/vscode#142270]
Reopening https://github.com/microsoft/vscode/issues/19940 as the suggested PR that it was closed by does not actually have the functionality of searching within search results.

**Comment by gilescope** [comment]
Is it crazy to want to do an initial search and then do a secondary search without having to write some contorted regex?

**Comment by roblourens** [comment]
There is another open issue for this request at https://github.com/microsoft/vscode/issues/118128
