### ISSUE TITLE
Use `fd` to quick open files by name, similar to how `ripgrep` is used for Find In Files

### ISSUE THREAD

**Issue by colemickens** [microsoft/vscode#142293]
To my understanding, `ripgrep` is used to accelerate "Search/Replace" in VSCode.

I've noticed that with very large workspaces, VSCode's quick open functionality can take a long time to search all of the filenames in the workspace.

Where is this functionality defined? What sort of backend is used? Is there a possibility to add caching, or shell out to an external tool like `fd`?

Thanks! And thanks for VSCode, one of my favorite things.

**Comment by roblourens** [comment]
Yes, ripgrep is used, and after the first search you will be filtering a cache. We have a long-proposed API to allow extensions to implement their own search providers, but it is not on the path towards stabilization.
