### ISSUE TITLE
Document when ReferenceContext.includeDeclarations might be false

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#14225]
I can't find in the documentation where `ReferenceContext.includeDeclaration` would be false. I don't see any user settings or language configuration that can affect this and it is always `true` in my tests.

Documenting the behavior of this would be nice.

**Comment by jrieken** [comment]
Use case is usually code lens which others can implement by using API commands: https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands

**Comment by hoovercj** [comment]
Thanks for clarifying a use case. If I understand, a primary use case is providing a codelens at a class/function/variable declaration for all references while excluding the declaration itself

So then a person in their CodeLens provider would use `commands.executeCommand('vscode.executeReferenceProvider', uri, position)` (following the API you linked), but then how can they request to not include a declaration? It still isn't mentioned there.
