### ISSUE TITLE
Improve folder colors when using Ubuntu bash on Windows 10

### ISSUE THREAD

**Issue by nikolafon** [Microsoft/vscode#14224]
- VSCode Version: 1.6.1
- OS Version: Windows 10 Pro 1607

I have configured Ubuntu bash to use as integrated terminal in VS Code.
I've noticed it that folders are marked differently from files, as if they are highlighted (selected) with green background but the font color is also some kind of green/blue shade. It is very hard to distinguish what is the name of the folder. 
Same goes for dark or light themes.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/7556
