### ISSUE TITLE
Python no longer runs

### ISSUE THREAD

**Issue by bernardo-suez** [microsoft/vscode#142234]
Issue Type: <b>Bug</b>

Open a folder with any Python code file inside.
Try running on debug mode.
The little bar showing up at the top with the debug control buttons for a couple of seconds.
Nothing will happen, not even in the terminal.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (4.22GB free)|
|Process Argv|--log --crash-reporter-id caafeb5b-ad3a-4fd5-83be-5d5a50e34e24|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.35.0
path-intellisense|chr|2.7.0
vscode-svgviewer|css|2.0.0
githistory|don|0.6.19
prettier-vscode|esb|9.2.0
vscode-firefox-debug|fir|2.9.6
vscode-pull-request-github|Git|0.36.0
gc-excelviewer|Gra|4.0.50
latex-workshop|Jam|8.23.0
better-cpp-syntax|jef|1.15.11
kite|kit|0.147.0
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.1
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.8.2
test-adapter-converter|ms-|0.1.5
vsliveshare|ms-|1.0.5330
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
autodocstring|njp|0.5.4
code-spell-checker|str|2.1.5
latex-utilities|tec|0.3.7
octave|toa|0.0.3
json|Zai|2.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vs360cf:30404996
vsclayoutctrc:30425945
vsrem710:30416614

```

</details>

**Comment by bernardo-suez** [comment]
I have tried reinstalling all Python extensions and restarting the computer, none of which worked. Below is a GIF of the issue.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/69978887/152599575-7bfc226a-528f-4efe-b957-688658188887.gif)
.

**Comment by deekahmad** [comment]
have same issue. Any luck resolving this?
