### ISSUE TITLE
Syntax highlighting dissapears when writing something incorrect in a file 

### ISSUE THREAD

**Issue by Loki-Hornsby** [microsoft/vscode#142289]
Issue Type: <b>Bug</b>

Syntax highlighting dissapears when writing something incorrect in a file or even just scrolling or clicking on occasion.
For example if i write `hello` in a file the entire contents of the file loses it's syntax highlighting after detecting the line isn't an inbuilt method - Deleting hello and waiting for it to detect the erroneous text has dissapeared does not fix it visually.
Unfortunately i don't know how to reproduce this.

The below fixes this issue visually but of course typing anything incorrect produces this error again:
Ctrl+Shift+P --> Restart omnisharp 
Ctrl+Shift+P --> Select Project --> Select current project
Ctrl+Shift+P --> Change Theme --> Dark+

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (2.61GB free)|
|Process Argv|--crash-reporter-id 71a7722b-2ce5-4be8-a463-e405bcc3ad22|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
All-Autocomplete|Ati|0.0.23
nsis|idl|3.48.0
path-autocomplete|ion|1.18.0
docomment|k--|0.1.30
unity-code-snippets|kle|1.3.0
csharp|ms-|1.24.0
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
sqlite-viewer|qwt|0.1.4
color-stamp|s3a|1.0.0
html-preview-vscode|tht|0.2.5
unity-tools|Tob|1.2.12
unity-debug|Uni|3.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vscop453:30404998
vsrem710cf:30416617

```

</details>

**Comment by JacksonKearl** [comment]
\extC#

**Comment by JacksonKearl** [comment]
It looks like this is caused by the C# extension. Please file the issue to the [C# extension repository](https://github.com/OmniSharp/omnisharp-vscode.git). Make sure to check their issue reporting template and provide them relevant information such as the extension version you're using. See also our [issue reporting guidelines](https://aka.ms/vscodeissuereporting) for more information.

Happy Coding!
