### ISSUE TITLE
broken snippet in 1.46

### ISSUE THREAD

**Issue by af4jm** [microsoft/vscode#142290]
Issue Type: <b>Bug</b>

x

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (17.55GB free)|
|Process Argv|--file-uri file:///c%3A/src/AF4JM.code-workspace --crash-reporter-id 06338080-eec2-498d-98e0-cf3111dc1cde|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (105)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-icalendar|af4|1.0.1
vscode-m3u|af4|1.0.0
vscode-caniuse|aga|0.5.0
Bookmarks|ale|13.2.2
rtf|ale|2.4.0
vscode-sqlite|ale|0.14.0
swagger-viewer|Arj|3.1.2
spellright|ban|3.0.60
armview|ben|0.4.5
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-footnotes|bie|0.0.7
markdown-mermaid|bie|1.13.1
markdown-yaml-preamble|bie|0.1.0
vscode-tldr|bmu|1.0.0
mermaid-markdown-syntax-highlighting|bpr|1.2.2
npm-intellisense|chr|1.4.0
gitignore|cod|0.7.0
disableligatures|Coe|0.0.10
vscode-markdownlint|Dav|0.46.0
jshint|dba|0.11.0
vscode-eslint|dba|2.2.2
dendron-snippet-maker|den|0.1.6
rushcore|Dev|1.0.2
rushnav|Dev|1.0.2
githistory|don|0.6.19
xml|Dot|2.5.1
escaping-characters|drp|1.0.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
vscode-macros|EXC|1.3.0
git-project-manager|fel|1.8.2
scriptcsRunner|fil|0.1.0
vscode-firefox-debug|fir|2.9.6
vscode-npm|fkn|3.3.0
shell-format|fox|7.2.2
macros|ged|1.2.1
matlab|Gim|2.3.1
vscode-pull-request-github|Git|0.36.0
gc-excelviewer|Gra|4.0.50
beautify|Hoo|1.5.0
vscode-favorites|how|1.10.2
rest-client|hum|0.24.6
path-autocomplete|ion|1.18.0
mediawiki|jak|2.1.0
markdown-katex|jef|0.1.4
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
vscode-peacock|joh|4.0.0
gpg|jva|0.1.2
docomment|k--|0.1.30
vscode-liquid-snippets|kil|2.0.3
gnuplot|mam|1.0.5
markdown-shortcuts|mdi|0.12.0
openapi-lint|mer|1.2.0
HTMLHint|mka|0.10.0
azure-pipelines|ms-|1.195.0
vscode-azureappservice|ms-|0.23.0
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.13.0
vscode-azurevirtualmachines|ms-|0.5.0
vscode-bicep|ms-|0.4.1124
vscode-cosmosdb|ms-|0.18.1
csharp|ms-|1.24.0
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
vscode-ai-remote|ms-|0.7.0
remote-containers|ms-|0.217.1
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.11
azurecli|ms-|0.5.0
live-server|ms-|0.2.12
mono-debug|ms-|0.16.2
powershell|ms-|2021.12.0
vscode-node-azure-pack|ms-|0.2.1
vscode-typescript-tslint-plugin|ms-|1.3.3
azurerm-vscode-tools|msa|0.15.5
debugger-for-edge|msj|1.0.15
language-liquid|nei|0.1.1
bib|phr|0.3.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.4.0
kuskus-kusto-language-server|ros|1.0.20
kuskus-kusto-syntax-highlighting|ros|1.1.20
toggle-case|rya|1.0.2
vscode-hexdump|sle|1.8.1
vscode-zipexplorer|sle|0.3.1
addDocComments|ste|0.0.8
msbuild-project-tools|tin|0.4.3
shell-launcher|Tyr|0.4.1
vscodeintellicode|Vis|1.2.16
nanoid-generator|vk-|0.1.2
vscode-icons|vsc|11.8.0
JavaScriptSnippets|xab|1.8.0
t4-support|zbe|0.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
vs360:30404995
vsrem710:30416614
vscop841cf:30430978

```

</details>

**Comment by af4jm** [comment]
I have the following in my `markdown.json` global snippets:

``` json
    "endash": {
        "prefix": "--",
        "body": ["–$0"],
        "description": "en-dash"
    },
    "emdash": {
        "prefix": "---",
        "body": ["—$0"],
        "description": "em-dash"
    },
```

since updating to 1.64, the em one with 3 dashes no longer works... in the past I would get a menu asking me which of these 2 snippets I wanted to expand, but now I get a popup menu that says "no suggestions" (I don't get several spaces, it doesn't "type" the tab into the text... so it knows it's supposed to do something)

if I change the snippet prefix to `===` or `***` it works fine, there's just something about the 3 (or more) dashes that's gone wonky in 1.64... I suspect it's a regression issue around file path completion

note: dash-dash-tab immediately expands the en snippet, as it always has

**Comment by af4jm** [comment]
one other thing I noticed, possibly related...

in that same markdown snippets file I also have

``` json
    "ellipsis": {
        "prefix": "...",
        "body": ["…$0"],
        "description": "ellipsis"
    },
```

and, since 1.64 when I type a single `.` I get a popup menu offering me this snippet, that I have to `Esc` to continue

this I've worked around by changing `editor.snippetSuggestions` from `bottom` to `none` (but that change has had no effect on the dashes snippets)

**Comment by af4jm** [comment]
I also have snippets in one of my folders that have "bb" and "bbb" as prefixes... I just noticed that like the dashes, the shorter one works fine, the longer one gives the empty menu instead of the 2 relevant snippets

**Comment by jrieken** [comment]
> in the past I would get a menu asking me which of these 2 snippets I wanted to expand, but now I get a popup menu that says "no suggestions

Does that mean you were using tab completion and had quick suggestions disabled, e.g suggestion don't show up when typing but hitting tab would either expand a snippet or show a picker of matching snippets?

**Comment by af4jm** [comment]
still nothing on this bug after a month? I would really like to go back to VSCode for Markdown editing.... but with this bug it's almost impossible, because I'd have to change every snippet to have a shortcut that doesn't end with another shortcut (because with this bug, if I have snippets "bb" and "bbb" or "--" and "---", the longer ones are impossible to expand by any means until this bug is fixed, the only work-around is to switch to another editor)

**Comment by jrieken** [comment]
I have tried the following steps based on my own [interpretation](https://github.com/microsoft/vscode/issues/142290#issuecomment-1031162551)

* have `plaintext` file
* have `"editor.tabCompletion": "onlySnippets"` and `"editor.quickSuggestions": false`
* have two snippets with `---` and `--` as prefix
* type `--` and hit <kbd>Tab</kbd> -> only the first snippet expands (this was always like that)
* type `---` and hit <kbd>Tab</kbd> -> suggest shows both options

**Comment by af4jm** [comment]
I did a little more digging, and realized it's a setting that's causing it... I still believe the setting behavior is buggy... I've opened that as a new issue (<https://github.com/microsoft/vscode/issues/146585>) and I'll close this one, because the title and description here are misleading, in light of the setting tie-in
