### ISSUE TITLE
Triple click selecting carriage return and moving to next line 

### ISSUE THREAD

**Issue by abhaypatil679** [microsoft/vscode#142273]
<b>Description of the Issue</b>

When triple clicking to select the whole line, the cursor is moving automatically to the start of the next line. When copying in this state, it's therefore copying the carriage return, and so you end up pasting two lines, instead of one, with the second line blank. This is causing me headaches when pasting into text entry fields that only show a single input line.

<b>Steps to Reproduce the Issue</b>

Open a text doc that contains multiple lines.
Triple click a line of text, one that has another line of text after it.
Note that the whole line of text is selected, and then the cursor is moved to the next line
CTRL+C or right click->Copy, to copy
Paste elsewhere. Note that the desired line is pasted, along with a new line, that's blank.

<b>Expected Behavior</b>

Only have the current line the cursor is in, copied, after triple click. Only one line should be pasted then.

<b>Actual Behavior</b>

An extra blank line is copied and pasted due to the cursor being moved to the next line on triple click.

**Comment by alexdima** [comment]
This works as designed and aligns with most code editors.

Triple clicking (or clicking on a line number) will select the contents of a line and the End-Of-Line Sequence e.g. `"This is a line\n"`.
