### ISSUE TITLE
Type Script files extension failing after 5 minutes

### ISSUE THREAD

**Issue by anthonygualandri** [microsoft/vscode#142213]
Issue Type: <b>Bug</b>

sytem report that this is happening.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1067-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2223 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (18.09GB free)|
|Process Argv|--crash-reporter-id 3c3b4855-586a-4882-82ee-ba0a11049b5f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1067-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (2 x 2693)|
|Memory (System)|3.84GB (0.13GB free)|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.4.0
codespaces|Git|1.5.1
dotenv|mik|1.0.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
vscode-remote-extensionpack|ms-|0.21.0
project-manager|ale|12.4.0
code-gnu-global|aus|0.2.2
github-markdown-preview|bie|0.1.0
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
npm-intellisense|chr|1.4.0
gitignore|cod|0.7.0
vscode-markdownlint|Dav|0.46.0
vscode-eslint|dba|2.2.2
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
code-runner|for|0.11.6
macros|ged|1.2.1
codespaces|Git|1.5.1
vscode-pull-request-github|Git|0.36.0
todo-tree|Gru|0.0.215
rest-client|hum|0.24.6
vscode-language-babel|mgm|0.0.36
dotenv|mik|1.0.1
vscode-docker|ms-|1.19.0
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.8.2
live-server|ms-|0.2.12
printcode|nob|3.0.0
prettier-standard-vscode|num|0.9.2
ngrok-for-vscode|phi|1.9.2
java|red|1.3.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.4.0
vscode-stripe|str|2.0.11
vscodeintellicode|Vis|1.2.16
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
clang-format|xav|1.9.0
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30429732
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30433058
pythonvs932:30410667
wslgetstarted:30426333
vs360:30404995
vsrem710:30416614

```

</details>

**Comment by anthonygualandri** [comment]
I'm not sure. I can see about testing that, but I'm using GitHub codespaces with the most recent stable version of vs code. Is there a specific extension that's causing this? It pops up like every five minutes.

**Comment by mjbvz** [comment]
Please test using the insiders build with all extensions except codespaces disabled
