### ISSUE TITLE
Latest update breaks due to proxy requirement.

### ISSUE THREAD

**Issue by timothylunaxj4s** [microsoft/vscode#142201]
Issue Type: <b>Bug</b>

Attempting to build my dev container behind a proxy failed with the latest update to 1.64.

This appears to be agnostic to the container used to build and is a widespread issue across the team.

1.63 worked appropriately.

I've attached the output log.

```sh
Process \\.\pipe\vscode-remote-containers-486230f95e3035407c1dcb9437ffb49cad7b9219-sock singleContainer Debug c:\Users\xj4s\AppData\Roaming\Code\logs\20220204T090011\exthost4\ms-vscode-remote.remote-containers 1643986908516
[39117 ms] Start: Run in container: test -d /root/.vscode-server
[39120 ms] 
[39120 ms] 
[39120 ms] Start: Run in container: test -f /var/vscode-server/.patchEtcEnvironmentMarker
[39122 ms] 
[39122 ms] 
[39123 ms] Start: Run in container: test -f /var/vscode-server/.patchEtcProfileMarker
[39125 ms] 
[39125 ms] 
[39125 ms] Start: Run in container: test ! -f '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[39128 ms] 
[39128 ms] 
[39128 ms] Exit code 1
[39129 ms] Start: Run in container: cat /root/.vscode-server/data/Machine/settings.json
[39132 ms] {
 "python.defaultInterpreterPath": "/usr/local/bin/python",
 "python.linting.enabled": true,
 "python.linting.pylintEnabled": true,
 "python.formatting.blackPath": "/projects/rmenv/black-check",
 "python.linting.banditPath": "/projects/rmenv/bandit/bin/bandit",
 "python.linting.flake8Path": "/projects/rmenv/flake8/bin/flake8",
 "python.linting.mypyPath": "/projects/rmenv/mypy/bin/mypy"
}
[39133 ms] 
[39133 ms] Start: Run in container: test -d /root/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9
[39135 ms] 
[39135 ms] 
[39135 ms] Exit code 1
[39135 ms] Start: Run in container: test -d /vscode/vscode-server/bin/linux-x64/5554b12acf27056905806867f251c859323ff7e9
[39138 ms] 
[39138 ms] 
[39138 ms] Exit code 1
[39138 ms] Installing VS Code Server for commit 5554b12acf27056905806867f251c859323ff7e9
[39141 ms] Start: Downloading VS Code Server
[39141 ms] 5554b12acf27056905806867f251c859323ff7e9 linux-x64 stable 
[39341 ms] Error: read ECONNRESET
 at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
[39341 ms] Exit code ECONNRESET
```

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Connection to 'dev-container+7b22686f737450617468223a22633a5c5c55736572735c5c786a34735c5c446f63756d656e74735c5c726574656e74696f6e2d6d6f64656c696e672d656e7669726f6e6d656e74222c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d7d' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (1.05GB free)|
|Process Argv|--crash-reporter-id 99a7683f-cc03-4ee1-96ef-8d18a759dc41|
|Screen Reader|no|
|VM|0%|

Connection to 'dev-container+7b22686f737450617468223a22633a5c5c55736572735c5c786a34735c5c446f63756d656e74735c5c726574656e74696f6e2d6d6f64656c696e672d656e7669726f6e6d656e74222c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d7d' could not be established
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.2
sas-syntax|77q|1.0.8
better-comments|aar|2.1.0
git-temporal-vscode|bee|1.0.0
vscode-coverage-highlighter|bra|1.0.3
better-toml|bun|0.3.2
gitlens|eam|11.7.0
gitlab-workflow|Git|3.40.2
vscode-test-explorer|hbe|2.21.1
r|Iku|2.3.6
mysql-syntax|jak|1.3.1
vscode-python-test-adapter|lit|0.7.0
vscode-docker|ms-|1.19.0
data-workspace-vscode|ms-|0.1.1
mssql|ms-|1.12.0
sql-database-projects-vscode|ms-|0.14.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.1
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
powershell|ms-|2021.12.0
test-adapter-converter|ms-|0.1.5
vsliveshare|ms-|1.0.5330
vscode-data-preview|Ran|2.3.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.4.0
pdf|tom|1.2.0
vscodeintellicode|Vis|1.2.16

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30426334
vs360cf:30404996
vsrem710cf:30416617

```

</details>

**Comment by AntonioL** [comment]
I can confirm that the proxy setting is not used in the 1.64 version, had to downgrade to 1.63 and disable updates.

**Comment by jamiematrix** [comment]
Just had a filesave fail where Prettier had crashed. Restarted VSCode and could see a new version being installed via Windows Terminal. Now Code won't load at all - 90% of my client projects are in Docker.

**Comment by AntonioL** [comment]
Any chance we can release this ASAP? @aeschli 

This breaks VS Code for a multitude of developers working behind corporate proxies

**Comment by aeschli** [comment]
Yes, a fix will be in 1.64.2 coming out in a few days: https://github.com/microsoft/vscode/pull/142441

**Comment by chrmarti** [comment]
Those affected using Remote-Containers could give the latest pre-release of Remote-Containers (0.219.0) a try. That falls back to downloading the server via Electron which is not affected by this bug. (Coincidental timing with this issue.)

Switch to the pre-release version if you haven't:
<img width="777" alt="image" src="https://user-images.githubusercontent.com/9205389/152982620-9fd75bf1-6d69-4840-b926-e51afad2542e.png">

**Comment by chrmarti** [comment]
Also fixed by @aeschli in today's Insiders build (just verified): https://code.visualstudio.com/insiders/

**Comment by AntonioL** [comment]
I confirm it works. Thanks @chrmarti and @aeschli

**Comment by aeschli** [comment]
The backport to 1.64 is #142441

**Comment by chrmarti** [comment]
Verified in the 1.64.2 candidate build (f80445ac).
