### ISSUE TITLE
User interface having a problem

### ISSUE THREAD

**Issue by bensonsulei** [microsoft/vscode#142267]
There really isn't much to it. It just happens every time my visual studio code window is running in the background and not being used or whenever I'm on another window. Please help
![glitch](https://user-images.githubusercontent.com/99082080/152644961-4d630579-5705-4a1d-ac2d-5c28573b7b7a.PNG)

**Comment by IllusionMH** [comment]
That's problem with GPU accelerated rendering.

In this comment update of Nvidia settings helped https://github.com/microsoft/vscode/issues/115189#issuecomment-768239687

Should be also gone if you pass `--disable-gpu` CLI flag or as permanent launch setting - see https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration for details

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/124226
