### ISSUE TITLE
C++ Debugging tool crashes randomly

### ISSUE THREAD

**Issue by a1q123456** [microsoft/vscode#142205]
Version: 1.64.0 (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z (1 day ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

Here are some logs:
```
[Switching to thread 6 (Thread 0x7fffedf60700 (LWP 17857))](running)
=thread-selected,id="6"
[Switching to thread 6 (Thread 0x7fffedf60700 (LWP 17857))](running)
=thread-selected,id="6"
[Switching to thread 6 (Thread 0x7fffedf60700 (LWP 17857))](running)
=thread-selected,id="6"
Stopping due to fatal error: ArgumentException: An item with the same key has already been added. Key: (Microsoft.MIDebugEngine.AD7StackFrame, line)
```

**Comment by a1q123456** [comment]
Looks like it's an issue with the C/C++ extension. Closing this issue.

**Comment by tinebp** [comment]
Having the same problem!!!
