### ISSUE TITLE
Intellisense completion issue in Debug

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#14228]
- VSCode Version: Code - Insiders 1.7.0-insider (788caba5a3ca1c2b137353f4384bb0e026db1a31, 2016-10-21T23:35:35.321Z)
- OS Version: Darwin x64 16.0.0

---

Steps to Reproduce:

1. Type `err` and hit Enter to autocomplete (`err_1`)

![g6vnbokl56](https://cloud.githubusercontent.com/assets/1723815/19627529/dc68cddc-9916-11e6-938a-49b78b79e7aa.gif)

**Comment by roblourens** [comment]
Got that in #14193
