### ISSUE TITLE
menu bar not dark (using dark theme)

### ISSUE THREAD

**Issue by Vlandmist** [Microsoft/vscode#14227]
- VSCode Version: 1.6.1
- OS Version: win7 64bit

why is the top menu bar so light?

![image](https://cloud.githubusercontent.com/assets/6247124/19626188/e083434c-992b-11e6-9f14-d8a347be3894.png)

**Comment by roblourens** [comment]
It's part of the electron window and not currently themable. You can hide it though, under 'View'

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/10070
