### ISSUE TITLE
Shift + Home doesn't select the text 

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode#14226]
_Version: Current insider build
OS: Windows 10_

I'm using <kbd>Shift</kbd>+<kbd>Home</kbd> quite often in order to select everything left of the cursor and place it to the first column of the current line. The selections doesn't work this way with the current insider build. 
Selecting text using these shortcuts works perfectly:
<kbd>Shift</kbd>+<kbd>↑</kbd> 
<kbd>Shift</kbd>+<kbd>↓</kbd> 
<kbd>Shift</kbd>+<kbd>→</kbd> 
<kbd>Shift</kbd>+<kbd>←</kbd> 
<kbd>Shift</kbd>+<kbd>End</kbd>

**Comment by roblourens** [comment]
Can you try launching with `--disable-extensions`? And do you have any relevant personal keyboard bindings?

**Comment by Wosi** [comment]
I can't reproduce it anymore with today's build based on commit 43e46ab. My keyboard shortcuts don't seem to interfere here:

    [
      {
        "key": "ctrl+f5",
        "command": "workbench.action.reloadWindow",
        "when": "editorTextFocus"
      }, 
      {
        "key": "ctrl+shift+t",
        "command": "workbench.action.tasks.test"
      }
    ]
