### ISSUE TITLE
The candidate list flicker when using Microsoft Pinyin IME

### ISSUE THREAD

**Issue by he0119** [microsoft/vscode#142253]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.0 (user setup)
- OS Version: Windows_NT x64 10.0.22000
- IME: Microsoft Pinyin IME

Steps to Reproduce:

1. Open any file
2. Type anything with IME

The candidate list flicker when typing.
![1644031125141](https://user-images.githubusercontent.com/5219550/152627899-553de0d0-2120-4df0-b168-a089103e12fe.gif)

It works fine in notepad.
![1644031923984](https://user-images.githubusercontent.com/5219550/152627900-b0e59bf9-806b-43eb-931d-7c6100770ba2.gif)

**Comment by he0119** [comment]
I found it may be a duplicate of #142155.

**Comment by HaloWang** [comment]
Also found a write dot at top-left of cursor after **switching IME**. I think this might be a same bug?

vscode:
```
Version: 1.64.0 (user setup)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```
windows
```
IME: Microsoft Pinyin
```
theme:
```
vscode theme: Atom One Dark Theme
```


![Screenshot 2022-02-05 223512](https://user-images.githubusercontent.com/7344724/152646371-cef56891-e3ee-47c4-9851-b7a5380e0cb5.png)
![Screenshot 2022-02-05 223558](https://user-images.githubusercontent.com/7344724/152646372-41cf1ed5-77f3-449d-b698-49e5c959bba8.png)
![Screenshot 2022-02-05 223558](https://user-images.githubusercontent.com/7344724/152646404-22ae9f76-b6d5-4bcd-a9a7-f434756b0f78.png)
![Screenshot 2022-02-05 223625](https://user-images.githubusercontent.com/7344724/152646373-06959fe6-9794-464a-af1b-c79a2904ddf6.png)

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/142155
