### ISSUE TITLE
re: Remote-Containers extension not working with VSCode v1.64.0 --ECONNRESET issue while installing VS Code Server

### ISSUE THREAD

**Issue by pthopa** [microsoft/vscode#142207]
After updating to version 1.64.0 of Visual Studio Code, opening a project in remote-containers does not work any more.
Getting the following issue:
5269 ms] Exit code 1
[5269 ms] Installing VS Code Server for commit 5554b12acf27056905806867f251c859323ff7e9
[5269 ms] Start: Downloading VS Code Server
[5269 ms] 5554b12acf27056905806867f251c859323ff7e9 linux-x64 stable
[5618 ms] Error: read ECONNRESET
        at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)

**Version of VSCode: 1.64.0
remote-Containers version: v0.218.0**

VSCode 1.64.0 has commit id 5554b12acf27056905806867f251c859323ff7e9.
Whereas the VSCode version inside the docker container " docker-developer-web" started by remote-containers, folder (/vscode/vscode-server/bin/linux-x64) is commit id  899d46d82c4c95423fb7e10e68eba52050e30ba3. Not sure that matters..

**Comment by AntonioL** [comment]
Related to this one: [#142201](https://github.com/microsoft/vscode/issues/142201)

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode/issues/142201.
