### ISSUE TITLE
Mac OS Keyboard shortcut for formatting a document not working

### ISSUE THREAD

**Issue by abhinavganguly1987** [microsoft/vscode#142261]
Issue Type: <b>Bug</b>

Hi Team,
 Lately i've obeserved that on Mac OS, keyboard shortcut of **"Shift+Option+F"** to format a document is not working, instead it is adding a tilde ~ symbol in the file at the point of current cursor position. 

If i do  **--> right click --> format document with ... --> HTML language features.**
It formats the document.
This is happening with all types of files, currently in my project i have HTML. Markdown, CSS, toml and javascript files.

Appreciate your help..
Regards,
Abhinav

VS Code version: Code 1.64.0 (Universal) (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:20:17.224Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (4.43GB free)|
|Process Argv|--crash-reporter-id 96855504-5e89-44f6-a263-70d4435ba3cf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
language-hugo-vscode|bud|1.3.1
better-toml|bun|0.3.2
prettier-vscode|esb|9.2.0
vetur|oct|0.35.0
prettyxml|Pra|1.4.0
svg-preview|Sim|2.8.3
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30433058
pythonvs932:30410667
vs360cf:30404996
vsrem710cf:30416617

```

</details>

**Comment by chrmarti** [comment]
/needsMoreInfo

Does this occur with all extensions disabled? (`F1` > `Developer: Reload With Extensions Disabled` or `code --disable-extensions`)

**Comment by abhinavganguly1987** [comment]
Hi @chrmarti 
Thank you for your reply,
Yes, i've already tried with the 'Reload with Extension Disabled as well'

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `Shift+Option+F`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by abhinavganguly1987** [comment]
Hello @alexdima 
Thank you for your steps, and apologied for delayed response.
I've followed your mentioned troubleshooting steps, and this is the outcome:
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/10762473/155535306-ec22ff84-094a-46b4-abde-b5aad808053d.png">

Andy thing that i need to change here?

**Comment by abhinavganguly1987** [comment]
Ah

https://user-images.githubusercontent.com/10762473/155545729-48bf69ee-e2b4-489e-b74a-6c6ff46a7079.mov

h @alexdima  i think i found the root cause.
It seems that VS code has a bug with ABC-India keyboard layout. If i toggle it to English keyboard layout, the format shortcut `Shift+⎇(option)+ F` works.
For now, i can do with English keyboard, it is only when i need to use INR symbol like Rupee, i might have to toggle keyboard layout.
Is there any fix for this? 
Im attaching the screen recording for your reference

**Comment by alexdima** [comment]
Thank you for the extra information. This has been reported before and is an upstream issue. Let's track at  https://github.com/microsoft/vscode/issues/41024 .
