### ISSUE TITLE
Open walkthroughs in new sidepanel

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#142225]
The current walkthroughs open in the editor space, which makes it hard to point to editor features. As new files and workspaces get opened, we have so far solved this by switching to split editor mode. Even as we started we already had mockups to explore walkthroughs in the sidebar, but which would then vanish when pointing to other sidebar views.

When the walkthroughs open in the new sidepanel on the right, they have more freedom to highlight different parts of the UI and persist in a stable location as more editors get opened. This will especially help walkthroughs that give UI tours, like [Luna Paint](https://github.com/lunapaint/vscode-luna-paint).

While it works mostly, the walkthrough UI would need some extra thought to make the best of the smaller sidebar space. How can we ensure the high-res SVGs and longer markdown content work well. As a goal, any current 1st and 3rd party walkthrough content should still work in any new UI we come up with, but might need follow up polish to make best use of the available space.

The walkthrough list could still be on the Get Started or be the welcome state of the "Walkthroughs"

This idea was reignited by MakeCode's intuitive onboarding guide (just as reference. We would not 1-1 follow the same UX):

<img src=https://user-images.githubusercontent.com/8599/152584250-dcb4e8e1-7323-48f5-a3ba-c1685377e524.png width=400>

**Comment by lychung7** [comment]
Here's an exploration across different walkthroughs in the new side panel:

In our current walkthrough layout, all walkthroughs have the title on the left-hand side, some have text and a CTA on the left-hand side, and varying amount of text/imagery on the right-hand side. With this side panel design exploration, we grouped the title and the navigation together to create a more consistent, fixed area of the walkthrough. The following section is where any copy, imagery, and CTAs can be grouped together. 

![Option E - 1](https://user-images.githubusercontent.com/60596156/159069265-293f35c4-a9ea-43b8-af12-6d0f01f3ce37.png)

![Option E - 2](https://user-images.githubusercontent.com/60596156/159069270-6568b1ab-b1a9-4fea-ab5c-0ed2d3f5b661.png)

![Option E - 3](https://user-images.githubusercontent.com/60596156/159069277-6f16f52a-17cb-4f5b-b2fc-2a3dd5f6d772.png)

As mentioned by @digitarald, the walkthroughs in the side panel could also allow us to highlight different areas of the UI. Here's an idea of how it could look:

![Option E - 9](https://user-images.githubusercontent.com/60596156/159069281-fdc4a652-ec85-4dcc-8d33-d4c371cedfba.png)
