### ISSUE TITLE
vscode.dev Insiders colouring issue

### ISSUE THREAD

**Issue by Lukas-Batema** [microsoft/vscode#142222]
The Insiders Edition of vscode.dev, does not show any colours on text inside the editor...

### Example:
![Screenshot 2022-02-04 1 00 01 PM](https://user-images.githubusercontent.com/55695493/152579572-853b7036-fa96-4b66-ac91-7e79513a6bcb.png)

---

Version: 1.65.0-insider
Commit: 62de8dc3f78b8bef1eb62deeb093164a8d76c254
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14324.80.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.102 Safari/537.36
Embedder: vscode.dev

**Comment by joyceerhl** [comment]
I can repro this in VS Code Insiders on github.dev: 
![image](https://user-images.githubusercontent.com/30305945/152618169-78027d18-53bc-4ca3-812f-72918a71b333.png)

**Comment by Lukas-Batema** [comment]
Yes, I see it is working now too. Thanks for the help!
