### ISSUE TITLE
Clicking in cell output does not focus the cell

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#142239]
- Execute a cell with a webview output
- Click in the output on an element that is not focusable
- The cell is not focused (focus bar on the side is not blue). If it had focus, it loses focus

**Comment by rebornix** [comment]
@roblourens good catch. the focus tracker is out of date and doesn't really work with current DOM structure/

**Comment by roblourens** [comment]
Oops I was just fixing this haha

**Comment by roblourens** [comment]
This change will set outputIsFocused to true, then it will never go back to false. I was just going to set the tabIndex on the output element, so the 'focus' listener on it would work. What do you think about that? Dunno how this worked before
