### ISSUE TITLE
Switch configuration files in vscode from JSON to YAML

### ISSUE THREAD

**Issue by aebrahim** [microsoft/vscode#142229]
Often configuration needs comments, which JSON technically doesn't allow. In fact, GitHub tools agree, this is what the default header of `.vscode/tasks.json` looks like rendered in GitHub, complaining about the comment as invalid syntax: 

![image](https://user-images.githubusercontent.com/1380168/152586701-b14a7f01-69ae-4938-ac2e-8552d53a2a75.png)

There are also a few other niceties like easy support for multi-line strings in YAML - after all, it was designed to be human editable. Here is an example from one of my `tasks.json` to convert some images to webp. The command is very hard to read here, and any diffs when I try to change it in a pull request are really hard to understand.

```json
        {
            "label": "Transform images",
            "type": "shell",
            "command": "for file in $(ls dir1/**/*.jpg); do convert $file -strip -resize 400x400 -quality 75 assets/pages/dir1/${file:10:$[${#file}-14]}.jpg; done && for file in $(ls dir2/**/*.jpg); do convert $file -strip -resize 400x400 -quality 75 assets/pages/dir2/${file:9:$[${#file}-13]}.webp; done && exiv2 -M\"set Exif.Image.Copyright Ascii © 2022 MyCompany\" -M\"set Xmp.dc.rights lang=en-US © 2022 MyCompany\" assets/pages/dir1/*/*.jpg assets/pages/dir2/*/*.webp",
            "group": {
                "kind": "build",
                "isDefault": true
            },
        },
```

It looks a little bit more readable as a YAML multiline string, and now git diffs will also be more easy to understand.
```yaml
- label: Transform images
  type: shell
  command: |
    for file in $(ls dir1/**/*.jpg);
      do convert $file -strip -resize 400x400 -quality 75 assets/pages/dir1/${file:10:$[${#file}-14]}.jpg;
    done && \
    for file in $(ls dir2/**/*.jpg);
      do convert $file -strip -resize 400x400 -quality 75 assets/pages/dir2/${file:9:$[${#file}-13]}.webp;
    done && \
    exiv2 -M"set Exif.Image.Copyright Ascii © 2022 MyCompany" \
      -M"set Xmp.dc.rights lang=en-US © 2022 MyCompany" \
      assets/pages/dir1/*/*.jpg assets/pages/dir2/*/*.webp
  group:
    kind: build
    isDefault: true

```

As I can imagine a full transition will be quite difficult, at the very least a choice would be really nice. If vscode checked for either a `.yaml` or a `.json` version of each configuration file, people who have more extensive settings files can use the benefits of yaml. In any case, thank you for your consideration!

**Comment by roblourens** [comment]
Fair points, but we have had this discussion in the past, and it's not likely that we will change at this point: https://github.com/microsoft/vscode/issues/4851
