### ISSUE TITLE
pwsh returning non-zero exit code when shell integration is on

### ISSUE THREAD

**Issue by LuanVSO** [microsoft/vscode#142247]
Issue Type: <b>Bug</b>

turn on shell integration and close pwsh typing `exit`
a notification will appear saying that it terminated with code 633
![image](https://user-images.githubusercontent.com/43626415/152622019-23693fe3-29af-453d-8192-e4e4b6ef8b9d.png)
the actual commaline sent to pwsh was
`"C:\Program Files\PowerShell\7\pwsh.exe" -noexit " -command" ". \"c:\Users\luanv\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\""`

tried running the same commanline outside of vs and the process exited with a zero status code

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.77GB free)|
|Process Argv|--crash-reporter-id e7743b00-59b6-4845-9f99-cecf5457b275|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
midl3-language-server|Ale|0.0.27
cmake-format|che|0.6.11
doxdocgen|csc|1.3.2
vscode-great-icons|emm|2.1.82
vscode-pull-request-github|Git|0.36.0
better-cpp-syntax|jef|1.15.11
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-language-pack-pt-BR|MS-|1.64.6
csharp|ms-|1.24.0
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.3
cpptools-extension-pack|ms-|1.1.0
hexeditor|ms-|1.9.4
makefile-tools|ms-|0.3.1
powershell|ms-|2021.12.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.3
code-spell-checker|str|2.1.5
code-spell-checker-portuguese-brazilian|str|2.0.5
even-better-toml|tam|0.14.2
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.16
material-theme|zhu|3.13.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vs360:30404995
vsrem710:30416614

```

</details>

**Comment by Tyriar** [comment]
This is the only part that looks wrong to me.

> ` " -command" `

**Comment by meganrogge** [comment]
Thanks for catching this!

To verify, make sure you can type `exit` into any shell with shell integration enabled and you don't see this.
