### ISSUE TITLE
Cannot uninstall VS Code/delete Code.exe file

### ISSUE THREAD

**Issue by 4th3LuLz0fIt** [microsoft/vscode#142297]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Update VS Code via VS Code update/VS Code settings
2. Error pop up stating code.exe cannot be accessed permission denied

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by mredodos** [comment]
i have the same problem i cant uninstall the file still in the directory and i cant reinstall it,restart the system not solve the problem, im literally stucked.
