### ISSUE TITLE
'Illegal state: service accessor is only valid during the invocation of its target method' error when closing terminal with Cmd+Backspace

### ISSUE THREAD

**Issue by rossng** [microsoft/vscode#142386]
Issue Type: <b>Bug</b>

- Open a terminal
- Select the terminal and press Cmd+Backspace (on macOS, at least)
- The terminal closes, but an error message pops up in the bottom right of the window:
  ```
  Illegal state: service accessor is only valid during the invocation of its target method
  ```

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:20:22.135Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (2.33GB free)|
|Process Argv|--disable-extensions --crash-reporter-id d79747e9-be45-4a3f-bdc4-cce2ea7e8b28|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
testflight:30433670
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vs360cf:30404996
vsrem710:30416614

```

</details>

**Comment by meganrogge** [comment]
I'm not seeing that in insider's. Can you reproduce it there?
