### ISSUE TITLE
Changes in files are not shown

### ISSUE THREAD

**Issue by fro-dev-clau** [microsoft/vscode#142357]
I made a quick branch for a quick fix, but when i wanted to commit the changes I couldn't because notting appeared.

<img width="469" alt="Screen Shot 2022-02-06 at 15 58 13" src="https://user-images.githubusercontent.com/97368672/152707126-6bd35caf-cbd0-42c1-acbf-ace880c0cbf2.png">

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36
Embedder: github.dev

**Comment by jacobweberbowery** [comment]
Seeing the same thing on a Mac M1. I open a git-based project in vscode, make a change, and nothing shows up in the source control view.

It's also hanging when I quit...not sure if that's related.

**Comment by jacobweberbowery** [comment]
Thanks for the details. It stopped happening for me, but I’ll try that if it happens again.

**Comment by bpasero** [comment]
Ok thanks!
