### ISSUE TITLE
Chinese imput panel will flash when editing

### ISSUE THREAD

**Issue by Rao-Jupiter** [microsoft/vscode#142376]
Issue Type: <b>Bug</b>

When editing with Chinese input method in vscode, the input method will flicker like this:

![0207155020](https://user-images.githubusercontent.com/70786042/152746801-be7df6e3-beb7-4dde-a0d8-7198af000c58.gif)
f251c859323ff7e9, 2022-02-03T04:22:20.678Z)

VS Code version: Code 1.64.0 (5554b12acf27056905806867
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.84GB free)|
|Process Argv|--crash-reporter-id 29c1bb96-cf3d-4658-846e-f7723e0475aa|
|Screen Reader|no|
|VM|29%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-spellchecker-fr|adr|1.3.0
All-Autocomplete|Ati|0.0.23
markdown-mermaid|bie|1.13.1
mermaid-markdown-syntax-highlighting|bpr|1.2.2
markdown-word-count|Cur|0.0.6
c-cpp-compile-run|dan|1.0.15
dendron|den|0.80.3
dendron-paste-image|den|1.1.0
githistory|don|0.6.19
vscode-pandoc|Dou|0.0.8
gitlens|eam|11.7.0
dictionary|Exi|0.0.2
foam-vscode|foa|0.17.3
code-runner|for|0.11.6
gitee|g8u|0.0.7
remotehub|Git|0.24.0
vscode-pull-request-github|Git|0.36.0
mdmath|goe|2.7.4
pangu|hal|0.1.6
better-cpp-syntax|jef|1.15.11
shortcut-menu-bar|jer|3.0.3
vscode-mermaid-snippets|kmo|0.5.0
vscode-github|Kni|0.30.7
markdown-math|koe|0.1.0
vscode-markdown-notes|kor|0.0.24
marp-vscode|mar|1.4.7
synonymprovider|Mar|1.0.0
markdown-shortcuts|mdi|0.12.0
git-graph|mhu|1.30.0
vscode-language-pack-zh-hans|MS-|1.64.6
csharp|ms-|1.24.0
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.1
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.2
cpptools-extension-pack|ms-|1.1.0
better-markdown-latex-shortcuts|Ora|2.0.3
markdown-preview-enhanced|shd|0.6.1
code-spell-checker|str|2.1.5
code-spell-checker-french|str|0.1.15
code-spell-checker-german|str|2.0.3
markdown-memo|svs|0.3.18
org-mode|too|0.5.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.0.9
vscodeintellicode|Vis|1.2.16
Pangu-Markdown|xlt|0.0.6
markdown-all-in-one|yzh|3.4.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vscop341:30404997
vsclayoutctrc:30425945
vsrem710:30416614

```

</details>

**Comment by alexdima** [comment]
:+1: Let's track the flickering of the candidate suggestion list in https://github.com/microsoft/vscode/issues/142253
