### ISSUE TITLE
How to increase line height in notebook?

### ISSUE THREAD

**Issue by lakshits11** [microsoft/vscode#142387]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.0
- OS Version: Windows 10

How to increase line height here in output of a notebook cell I executed? The text looks so untidy.

![temp1](https://user-images.githubusercontent.com/54276661/152774431-d8663b67-523b-41e1-b64b-136fc6fa1876.png)

Also here you can see that **letter y and commas** are not printed fully due to line height issue :-

![temp2](https://user-images.githubusercontent.com/54276661/152774477-bbae23d8-f215-497d-8ec9-04e6d412171b.png)

See one more example below:
![image](https://user-images.githubusercontent.com/54276661/152777564-42229452-7bd2-4660-a394-89085a954807.png)

**Comment by lakshits11** [comment]
Hello may I please know some updates about this?

**Comment by rebornix** [comment]
Let's track it in https://github.com/microsoft/vscode/issues/142834
