### ISSUE TITLE
Screen reader detected on macOS while a screen reader is not running

### ISSUE THREAD

**Issue by raboomar** [microsoft/vscode#142351]
Issue Type: <b>Bug</b>

whenever I go to write any code vscode just beeps i'm on a mac I dont know how to turn it off please helppp!!!!!!!!!!!!

VS Code version: Code 1.64.0 (Universal) (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:20:17.224Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 92d2f1c7-353d-4da1-b405-53bf7c27e87c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.6
path-intellisense|chr|2.7.0
bracket-pair-colorizer|Coe|1.0.62
bracket-pair-colorizer-2|Coe|0.2.2
vscode-html-css|ecm|1.11.0
prettier-vscode|esb|9.2.0
auto-rename-tag|for|0.1.9
LiveServer|rit|5.7.4
code-spell-checker|str|2.1.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vscop940:30404999
vsrem710:30416614
vscop841:30430977
vscscmwlcmt:30433761

```

</details>

**Comment by wsmelton** [comment]
Beep noises have a particular meaning in Mac OS if I recall (don't have one) but it would not be associated with VS Code itself. There are no settings to control OS related notification sounds in Windows or Mac.

**Comment by raboomar** [comment]
but it only happens when I have an error in my code and when in VS code

**Comment by gjsjohnmurray** [comment]
Did it happen before 1.64? If not, maybe https://code.visualstudio.com/updates/v1_64#_audio-cues

**Comment by wsmelton** [comment]
Try disabling all the extensions on startup of VS Code:

`code --disable-extensions`

or

`code-insiders --disable-extensions`

That will take out the extensions causing any issue.

**Comment by raboomar** [comment]
it started after the update.

I have disabled all extensions and it still does it

**Comment by dfreire** [comment]
It happens to me too, but only if `prettier-vscode` is enabled

**Comment by hediet** [comment]
Can you go to your users settings.json and add `"audioCues.enabled": "off"` and then try it again?

Do you use a screen-reader?

**Comment by dfreire** [comment]
I can confirm `"audioCues.enabled": "off"` successfully disables the beeping sound.
I'm using a macbook pro.

**Comment by raboomar** [comment]
`"audioCues.enabled": "off"` did work thank you!!

**Comment by hediet** [comment]
Well, you should not need to set that explicitly, it should be off by default, unless a screenreader is attached.

Do you use a screenreader by any chance?

**Comment by dfreire** [comment]
This is probably not related, but I do have an accessibility option active:
Accessibility > Spoken Content > Speak selection

**Comment by raboomar** [comment]
I do not have a screen reader on. this only started after I updated VScode friday

**Comment by isidorn** [comment]
@sbatten worked on the service that detects if a screen reader is attached or not thus also assigning to him

**Comment by raboomar** [comment]
@isidorn what would be the best way to do that?

**Comment by isidorn** [comment]
@raboomar `Cmd + ,`, top right click on Open Settings (JSON). Copy `settings.json` content, paste it here

![Screenshot 2022-02-09 at 11 35 09](https://user-images.githubusercontent.com/1926584/153180808-6023db5a-ec40-4ab3-b37a-0362da2e44b5.png)

**Comment by raboomar** [comment]
`{
    "security.workspace.trust.untrustedFiles": "open",
    "editor.accessibilitySupport": "on",
    "bracket-pair-colorizer-2.depreciation-notice": false,
    "bracketPairColorizer.depreciation-notice": false,
    "git.enableSmartCommit": true,
    "audioCues.enabled": "off",
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
        
    },
    "editor.formatOnSave": true,
    "[javascriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    }
}`

**Comment by isidorn** [comment]
@raboomar please remove `"editor.accessibilitySupport": "on"` from your settings.
You have enabled accessibility support. Probably by accident in the past
