### ISSUE TITLE
auto-completion issue in snippets.

### ISSUE THREAD

**Issue by ahhshm** [microsoft/vscode#142327]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2 899d46d82c4c95423fb7e10e68eba52050e30ba3x64
- OS Version: Arch linux

Steps to Reproduce:

1. Add this snippet:
```json
{
	"Print to console": {
		"scope": "javascript,typescript",
		"prefix": "db",
		"body": ["console.log(\"${2:$1} :\", $1);$0"],
		"description": "Log output to console"
	}
}
```
2. just use it
![2022-02-06-18-13-22](https://user-images.githubusercontent.com/87268103/152686559-9782c62e-438d-4841-bac6-3ba6f3d2577f.gif)

$2 just copies the text of $1 and the cursor should be actually at $1 so why the auto-completion result is like I'm at $2 ("key" is not in the result)?

**Comment by ArturoDent** [comment]
Should there be intellisense on the simpler snippet below

Given:

```js
const obj = { key: "seven"};
```

Trigger the snippet below that code:

```jsonc
"Debug": {
  "prefix": ["db"],
  "body": [

    // "console.log($1, $1)"]      // works as expected

    "console.log(\"$1 \", $1)"    // does not work, $1 wrapped in quotes
  ]
}
```

For tabstop `$1` type `obj.` and it doesn't suggest `obj` properties or `obj` as an object either.

I have `Editor > Suggest: Snippets Prevent Quick Suggestions` disabled and 

```jsonc
"editor.quickSuggestions": {
  "other": true,
  "comments": true,
  "strings": true
}
```

**Comment by ahhshm** [comment]
Thanks for the help. I found a workaround. I had to remove the quotes around $2:
```
"Debug": {
  "prefix": ["db"],
  "body": [
    "console.log(${2:$1 :}, $1)"
  ]
}
```
Now I have intelligence. I can press TAB to select $2 and then surround it with double quotes by pressing the " key.
![image](https://i.stack.imgur.com/AfT9Q.gif)

StackOverflow: https://stackoverflow.com/a/71013280/16225339
