### ISSUE TITLE
too many connections to 13.107.5.93

### ISSUE THREAD

**Issue by bmesuere** [microsoft/vscode#142336]
Issue Type: <b>Bug</b>

Vscode crashes my modem, really.

Every half an hour, I experienced severe packet loss on my home network. After some troubleshooting, I determined the culprit was my own laptop. Since the issue occured at specific times, I was able to capture relevant traffic using wireshark. A lot of the captured packets were directed at `13.107.5.93`. Sure enough, lsof listed over 50 connections to that ip from vscode which generated a lot of traffic every 30 minutes. After closing vscode, the problem disappeared.

Some days later, the issue reappeared: an unstable internect connection and netstat listed over 30 connections to the same ip. At the time, I didn't have time to further investigate the issue so I just killed vscode again.

Now, a few days later, I again see 3 connections to `13.107.5.93`. This doesn't cause any problems yet, but the number of open connections seems to grow over time.

The developer tools console lists these 3 error messages over and over:
```
[Extension Host] rejected promise not handled within 1 second: Error: connect ETIMEDOUT 13.107.5.93:443
I @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:628
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
fire @ event.ts:628
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
x @ ipc.net.ts:60
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188

[Extension Host] stack trace: Error: connect ETIMEDOUT 13.107.5.93:443    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
I @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:628
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
fire @ event.ts:628
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
x @ ipc.net.ts:60
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188

ERR connect ETIMEDOUT 13.107.5.93:443: Error: connect ETIMEDOUT 13.107.5.93:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```

Any help in getting to the bottom of this would be appreciated.

VS Code version: Code 1.64.0 (Universal) (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:20:17.224Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (0.45GB free)|
|Process Argv|--crash-reporter-id e1004944-c039-4919-a69d-26e5e1c01830|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ruby-test-adapter|con|0.9.0
vscode-github-actions|csc|0.22.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
codespaces|Git|1.5.2
copilot|Git|1.7.4812
remotehub|Git|0.24.0
vscode-pull-request-github|Git|0.36.0
vscode-test-explorer|hbe|2.21.1
rainbow-csv|mec|2.0.0
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
test-adapter-converter|ms-|0.1.5
vetur|oct|0.35.0
material-icon-theme|PKi|4.12.1
ruby|reb|0.28.1
lit-plugin|run|1.2.1
code-spell-checker|str|2.1.5
code-spell-checker-dutch|str|0.3.0
vscode-ruby|win|0.28.0
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
vs360:30404995
vsrem710:30416614

```

</details>

**Comment by bmesuere** [comment]
I kept monitoring my connections to this ip using netstat and cleared the errors in the vscode devtools console.
At one time, there were 117 connections with `SYN_SENT` as status and an additional 20 with `ESTABLISHED`. Another triplet of errors showed up in the dev tools console. The number of open connections then returned to the 3 previous ones.

**Comment by Tyriar** [comment]
Looks like the requests are coming from the extension host so chances are it's one of your extensions causing the problem. You could try disabling them and seeing if that makes the problem go away? If so, we have a bisect utility to help identify the problem https://code.visualstudio.com/blogs/2021/02/16/extension-bisect

**Comment by bmesuere** [comment]
I'm running the bisect, but since it needs a few days for the issue to become visible, this takes a while...

**Comment by dsoudakov** [comment]
This happened to me. I almost bought new router and changed the ISP. MSFT... ug. Still need to figure out which extension it is.

**Comment by bmesuere** [comment]
@dsoudakov can you cross check my list from the initial report? I'm still running bisect...

**Comment by dsoudakov** [comment]
> @dsoudakov can you cross check my list from the initial report? I'm still running bisect...

Looks like Copilot. As soon as I enable it connection to 13.107.5.93 (and 140.82.114.6) is established.

**Comment by bmesuere** [comment]
I can confirm that I haven't had any issues since disabling Copilot.

**Comment by Tyriar** [comment]
I think the way to report issues to copilot is via standard GitHub support, locking since this is off topic for core vscode but I encourage you to report to GH.
