### ISSUE TITLE
Format react-native code (.js files)

### ISSUE THREAD

**Issue by mosluce** [Microsoft/vscode#14235]
- VSCode Version: 1.6.1
- OS Version: macOS 10.12（16A323）

Steps to Reproduce:

1. react-native init SomeProject
2. code SomeProject
3. open index.ios.js
4. CMD+SHIFT+P
5. format (enter)

![out](https://cloud.githubusercontent.com/assets/1487051/19628211/23f8b56c-998b-11e6-939a-4a5f2593d7f9.gif)

**Comment by waderyan** [comment]
Thank you for opening this up. I'm not seeing this with the latest release. Can you install [VS Code Insiders](http://code.visualstudio.com/insiders) and try again? The issue is resolved on my end.

**Comment by mosluce** [comment]
The issue is resolved in VS Code Insiders,  Thanks.
