### ISSUE TITLE
Adding a local setting file not syncd

### ISSUE THREAD

**Issue by Darkmagister** [microsoft/vscode#142383]
I'm using vscode with sync of settings active, but i use different platform, and on each i have differente path and some parameters in one that doesn't work on the other, is there a way to have a global setting fos vscode that are not synced with the others?

**Comment by gjsjohnmurray** [comment]
This?

![image](https://user-images.githubusercontent.com/6726799/152767143-8aea4a70-36aa-425c-8aea-a302d34d40d0.png)

**Comment by Darkmagister** [comment]
yes i think that will do it, sorry i'm using the file more often then the UI i didn't see that!
