### ISSUE TITLE
wsl 2 not running. I've set to default, updated and enabled the virtualization.

### ISSUE THREAD

**Issue by Sergei-007** [microsoft/vscode#142338]
Issue Type: <b>Bug</b>

open vscode from ubuntu upon start up the message you are currently using wsl we strongly recommend using wsl 2.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-22000-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (8.49GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/thomas --remote=wsl+Ubuntu --crash-reporter-id 487c465b-a2a2-4c05-a0d1-2de88affaae7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-22000-Microsoft|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|Memory (System)|15.73GB (8.49GB free)|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.64.2
vscode-css-formatter|aes|1.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vs360cf:30404996
vsrem710cf:30416617

```

</details>

**Comment by aeschli** [comment]
Is it a WSL issue or an issue of the VS Code Remote WSL extension?

I assume you followed the steps from https://docs.microsoft.com/en-us/windows/wsl/install-manual
Can you open the new distro in a terminal? (not yet involving VS Code)

If the problem is with VS Code. Can you describe more what's not working? A screenshot would be good, and the WSL Log.

**Comment by Sergei-007** [comment]
I did follow the steps. I just started learning and I resolved the issue by
following the steps using power shell instead of command terminal. My
apologies.
