### ISSUE TITLE
enableShellIntegration multiple lines Run Selection behavior change

### ISSUE THREAD

**Issue by wsmelton** [microsoft/vscode#142355]
Create new script for PowerShell language and just select one line, using F8 or Run Selection the command executes.

Create a multi-line selection to execute using the same process and it adds a simple line break. This requires changing focus to terminal and hitting enter to execute the command.

![image](https://user-images.githubusercontent.com/11204251/152704228-72fbced9-f9f6-4fa1-9c38-fb3158e353b0.png)

**Comment by Tyriar** [comment]
> using F8 or Run Selection the command executes.

Is this a command from the powershell extension?

**Comment by Tyriar** [comment]
This one might also be improved from updating to today's insiders, like https://github.com/microsoft/vscode/issues/142354

**Comment by wsmelton** [comment]
Yep, confirmed latest build resolves.
