### ISSUE TITLE
VSCode will not launch after unexpected (improper) shutdown.

### ISSUE THREAD

**Issue by ninjarogue** [microsoft/vscode#142380]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
> 1.64.0
> 5554b12acf27056905806867f251c859323ff7e9
> arm64

- OS Version: macOS Monterey (version 12.2)

Steps to Reproduce:

1. open terminal
2. execute following command in a project folder
  - `$ code --disable-extensions --verbose`

Result:

```
[main 2022-02-07T09:23:26.870Z] Error: ENOENT: no such file or directory, mkdir '/Users/jiangthang/.vscode/extensions'
[main 2022-02-07T09:23:26.867Z] [File Watcher (node.js)] Request to start watching: /Users/jiangthang/Library/Application Support/Code/User (excludes: <none>),/Users/jiangthang/Library/Application Support/Code/User/settings.json (excludes: <none>)
[main 2022-02-07T09:23:26.870Z] Lifecycle#kill()
[main 2022-02-07T09:23:26.870Z] Lifecycle#onWillShutdown.fire()
```

Further details:
- VSCode was working fine up until my machine shutdown unexpectedly.
- If I run the following command: `ps aux | grep Code.app` several times — I see a new PID with each result.

**Comment by bpasero** [comment]
Is `/Users/jiangthang/.vscode/` maybe now owned by a different user than the one you started Code with? Does a uninstall and reinstall help?

**Comment by ninjarogue** [comment]
@bpasero No I am the only user here. Unfortunately, an uninstall or reinstall does not solve the issue.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by ninjarogue** [comment]
@bpasero I tried to reproduce it with the nightly insider build and it worked.

**Comment by bpasero** [comment]
Cool, then I suggest you stick to that version until we have released the next stable in March.

**Comment by ninjarogue** [comment]
@bpasero How do I stop VSCode from continuously spawning processes on my machine? I'm not sure if it is VSCode that is specifically responsible but everytime I run `ps aux | grep Code.app` I see a new process ID.
