### ISSUE TITLE
Editor: Close to the Left

### ISSUE THREAD

**Issue by lexxyungcarter** [microsoft/vscode#142322]
There is a 'Close to the Right' option. It would be wonderful having a 'Close to the Left' as well. 
Closing them manually is no fun.

![image](https://user-images.githubusercontent.com/19994360/152679991-770ddba7-bfb8-4608-84e3-3f64c77111e6.png)

**Comment by gjsjohnmurray** [comment]
A command to do this is already available in the Command Palette.

**Comment by vngmar** [comment]
> A command to do this is already available in the Command Palette.

Do we have a "close others" too?

**Comment by dipankardas011** [comment]
I will notify you if been able to add it🤞🏼

**Comment by gjsjohnmurray** [comment]
> I will notify you if been able to add it🤞🏼

@dipankardas011 even if you submit a PR it's not guaranteed to be accepted. Adding extra items to menus is often controversial, particularly ones not appended.

**Comment by dipankardas011** [comment]
Could not get so leaving this issue🙁
