### ISSUE TITLE
Don open file linking

### ISSUE THREAD

**Issue by sggonzalezg** [microsoft/vscode#142398]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Versión: 1.64.0 (Universal)
- OS Version: Darwin x64 20.6.0

Steps to Reproduce:

1. Open any .sccs file with import without extension
example: @import '../shared';

2. cmd+click in file route not open

**Comment by aeschli** [comment]
What do you mean by 'autofill' ? It will propose hello, but it should not fill it in automatically unless you press tab or enter.

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/207405443-8524b9c8-e9fe-45c4-bd09-55d5ca178479.png)
