### ISSUE TITLE
Surround with snippets (for JS/TS) is very confusing

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#142399]
vscode add snippet within surround supported as highligh in  1.64.0 release note

https://code.visualstudio.com/updates/v1_64#_surround-with-snippets-for-jsts

But, how can users know that which snippet is supporting the surrounding feature?

you vscode developers use TS as the dev language, so, how do you know or distinguish those ts/js snippets are supporting surround?

you maybe know `while` is surround supported because you're used to it, but how about `switch`?
![image](https://user-images.githubusercontent.com/1876302/152799353-1d893732-72f7-4acc-8fb7-42e77a5a7ce0.png)

https://github.com/microsoft/vscode/blob/f8fe16b97a9201dadceaab42c57c0f0a8438b358/extensions/typescript-basics/snippets/typescript.code-snippets#L216-L238

the truth is that you insert `switch`, the code you selected will be deleted~~ Inconceivable

## propose

so, please provide a mechanism to let users know and to distinguish.
may be a flag/icon or something when the snippet list showed

**Comment by heartacker** [comment]
not only for TS/JS, please for all

**Comment by alinnert** [comment]
Maybe a new command "Surround selection with snippet" could be introduced. When running this command it displays a list with only those snippets that support surrounding selected code.

**Comment by heartacker** [comment]
> Maybe a new command "Surround selection with snippet" could be introduced. When running this command it displays a list with only those snippets that support surrounding selected code.

thanks, and I just want vscode could add some Identification to snippet list for user to distingue, there is no conflict with `insert snippet` and/or `Surround selection with snippet`.

@alinnert  BTW, could you please vote 👍 for this if there is somehow useful, thanks a lot.

**Comment by alinnert** [comment]
If "Insert snippet" reverts back to its previous behavior (which I'd prefer if there's also a "Surround... " command) I don't think a distinction is necessary. A separate command alone would already eliminate the confusion.

**Comment by heartacker** [comment]
I had published an extension of snippets, because this, I have to add extra information to let users(include my team mates) know which is support surrounding.

https://marketplace.visualstudio.com/items?itemName=heartacker.snippets-plus

![image](https://user-images.githubusercontent.com/1876302/153034117-d102bf50-53b2-434c-9449-1c0da4e49823.png)

After all, it does work, and they stopped complaining 😄

**Comment by alinnert** [comment]
> yes, but the insert snippet command also contains the surround-snippets. that is the problem

I don't think that's a problem. I've checked out how I could create my own snippets that support *surround selection*. A snippet supports that if it contains the tag `${TM_SELECTED_TEXT}`. You can still *insert* them. Then `${TM_SELECTED_TEXT}` just gets ignored.

E.g. the following snippet does support *insert* and *surround selection*:

```
console.log(${TM_SELECTED_TEXT}$0)
```

I wouldn't bother if a snippet like this gets listed in "Insert snippet" and "Surround with snippet".

**Comment by heartacker** [comment]
No， I'm talking about the snippet usage.
 I'm not talking about the snippets creation.


 When you selected some code,
 And trigger the  Insert snippet

 How do you distinguish which snippet is  Surrounding support?

**Comment by alinnert** [comment]
@heartacker If there were two commands I'd say all snippets just replace the selection if you choose "Insert snippet". This makes the behavior of this command consistent and predictable and gives "Surround selection with snippet" actually a reason to exist. Also, it makes snippets more flexible. You can use one snippet to replace **and** surround the selection, depending on the command you run.
