### ISSUE TITLE
vs code powershell auto responding Y

### ISSUE THREAD

**Issue by nantonacci** [microsoft/vscode#142367]
Issue Type: <b>Bug</b>

when using powershell in vs code terminal, terminal automatically responds Y to Y/N questions without any such setting enabled. also responds Y after conducting an npm install. confirmed regular powershell does not have the same behavior. this was occurring on a separate work computer as well, different windows account, installs, etc. hence i suspect it might have gotten added to a recent update. i would appreciate a workaround, or something i could add to my settings.json.
thank you!
[https://i.imgur.com/02TOd6g.png](url)

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.38GB free)|
|Process Argv|--crash-reporter-id 7e6f7f0a-258f-4b0c-89d1-d5708ad6d5fb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.2.0
vue|jcb|0.1.5
vetur|oct|0.35.0
synthwave-vscode|Rob|0.1.10
code-spell-checker|str|2.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vs360cf:30404996
vsrem710:30416614

```

</details>

**Comment by iammola** [comment]
The feature is new and came with the January 2022 release. [Automatic Replies v1.64](https://code.visualstudio.com/updates/v1_64/#_automatic-replies)

You can disable it by setting the reply to null.
```json
"terminal.integrated.autoReplies": {
  "Terminate batch job (Y/N)": null
}
```

**Comment by nantonacci** [comment]
thank you for your swift response! i appreciate the workaround.

**Comment by nantonacci** [comment]
main issue i would say is: automatically enabling this without user input. this could cause problems for some users.
additionally, having it respond Y after an npm i that does not prompt for [y/n] would not be expected behavior

**Comment by melgish** [comment]
Since this feature was added I've been seeing tons of  false activations

Y : The term 'Y' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
and try again.
