### ISSUE TITLE
Integrated terminal automatically sends 'Y' when terminating node batch script

### ISSUE THREAD

**Issue by stephenmatheis** [microsoft/vscode#142341]
Thank you so much for looking into this 🙏 !

Issue Type: <b>Bug</b>

```console
~ > npm run concurrently \"script-1.js\" \"script-2.js\"
~ > [ type >> ctrl + c]
~ > Terminate batch job (Y/N)? Y (this character is automatically sent, but only terminates first script, putting remaining output in prompt on next line)
~ > [0] node script-name
~ > [type >> enter]
~ >                                                   y (character is still present, with spaces prepended)
~ > y : The term 'y' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name,   
or if a path was included, verify that the path is correct and try again.
At line:1 char:1
```

* The character <kbd>y</kbd> is never typed.
* This does not happen in Windows Terminal. <kbd>ctrl</kbd> + <kbd>c</kbd> works as expected.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (22.74GB free)|
|Process Argv|C:\\Users\\steph\\OneDrive\\Documents\\GitHub\\robi --crash-reporter-id bc47a489-a287-44e8-9f71-a241e2b29255|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
es6-string-css|bas|0.1.0
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
remote-wsl|ms-|0.64.2
powershell|ms-|2021.12.0
LiveServer|rit|5.7.4
es6-string-html|Tob|2.12.0
vscode-todo-highlight|way|1.0.5
es6-string-javascript|zjc|1.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vscop940:30404999
vsrem710:30416614
vscop841:30430977

```

</details>

**Comment by meganrogge** [comment]
You can fix this by setting the value of terminate hatch job within terminal.integrated.autoReplies to null

**Comment by stephenmatheis** [comment]
@meganrogge, Thank you so much! I should have checked if this was a setting first. Just curious - is this a new setting/behavior? Just started happening with 1.64.

**Comment by Snailedlt** [comment]
This is still a bug.

This happens for me too. Every time I type `CTRL+C` it autoresponds `Y`. Now every time I type anything in the terminal after this, it writes Y after it: 
![image](https://user-images.githubusercontent.com/43886029/152754656-df8d0083-a428-4ad5-8791-4dac52a0d12a.png)
```powershell
Y : The term 'Y' is not recognized as the name of a cmdlet, function, script file, or operable progr
am. Check the spelling of the name, or if a path was included, verify that the path is correct and t 
ry again.
At line:1 char:1
+ Y
+ ~
    + CategoryInfo          : ObjectNotFound: (Y:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
If I type any command that gives a prompt, it stops autoresponding with `Y`. It also seems that writing git commands in the terminal somehow stops the `Y`autoresponse.

**Comment by Tyriar** [comment]
Updating to Windows 11 might workaround this as I've never hit this issue. The theory is that something running in the terminal is triggering conpty (the backend component) to reprint the screen which would re-output the match text.

**Comment by Tyriar** [comment]
Thanks for the report, I'm going to disable it by default to be safe. We also had an idea for later on to allow the feature to be discovered intuitively when the user responds manually.

**Comment by filiptronicek** [comment]
> meganrogge, Thank you so much! I should have checked if this was a setting first. Just curious - is this a new setting/behavior? Just started happening with 1.64.

This indeed is new with 1.64, see the [release notes](https://code.visualstudio.com/updates/v1_64#_automatic-replies) for details.

**Comment by Tyriar** [comment]
Yes on older versions of Windows this is less reliable as the terminal emulation provided by Windows ends up reprinting the screen, causing the phrase to show up again.

**Comment by Snailedlt** [comment]
Shouldn't this be fixed for Windows 10 too though? It's still supported by Microsoft and VSCode, right?

**Comment by Regenhardt** [comment]
So is the conclusion just "Not supported you gotta disable it on Windows 10 yourself" and case closed? Doesn't seem right.

**Comment by Regenhardt** [comment]
Ok I see you disabled it by default in a merge request. So the state is now "this isn't supported on Windows 10"?

How about this:

Currently it seems to go "if (buffer.Contains(trigger)) send(reply);"  
So what if instead it goes "if (buffer.Contains(trigger) && !buffer.Contains(trigger+reply)) send(reply);"

You know, just check if the line that was found already has a reply?
