### ISSUE TITLE
A way to add a "read-only" marker to a webView or a variable indicating the current tab is a webview

### ISSUE THREAD

**Issue by HannaSwidaPieces** [microsoft/vscode#142397]
I need to make a webview be able to communicate to the extension that it is a webview. End goal is displaying a message that the chosen text snippet cannot be inserted into a webview (as opposed to a regular text editor). I tried creating a try catch for a registerTextEditorCommand but I guess technically it is a text editor so I have to way of marking it as a webview.

**Comment by mjbvz** [comment]
Webviews have an icon you can set to whatever you want: https://github.com/microsoft/vscode/blob/261adce05c180fbe1802dd26d8d802c00bfedbe5/src/vscode-dts/vscode.d.ts#L8096

You can use this to make it clearer to users that the current tab is a webview. You can even change it dynamically if you want although I'd be careful about doing this too aggressively as it could easily become distracting
