### ISSUE TITLE
BUG: Instances of Color not reported with Themes

### ISSUE THREAD

**Issue by samusxx** [microsoft/vscode#142368]
VSCode 1.64 on Windows 11.

### Instances of Color not reported.
Instance 1:
- Documentation for `"editor.bracketPairColorization.enabled": true`, for example on the _editor tooltip_, does not report _from where_ it gets the _three default values_ to colorize the brace particles when `"editorBracketHighlight.foreground1"-3` in `"workbench.colorCustomizations" : {}`, are undefined. 

Instance 2 of Color not reported:
- The _Developer: Inspect Editor Tokens and Scopes **tooltip**_ when the cursor is pointing to a _brace_, while `"editor.bracketPairColorization.enabled": true`, fails to report the color accurately: the brace color on the tooltip has a default foreground value of `#BBBBBB` regardless of what color the brace is set to by `"workbench.colorCustomizations" : { "editorBracketHighlight.foreground1"-3 }`. 
         This occurs whether or not the `"editorBracketHighlight.foreground1"-3` are undefined or specify colors, as long as `"editor.bracketPairColorization.enabled":true`.  

BUG in display of color from load order of theme declarations not being respected (conflict):
- `"editor.bracketPairColorization.enabled": true` in settings.json, will ignore later declarations of colors for a token match of scope `meta.square.brace`, specifically for this example it's the case of `"editor.tokenColorCustomizations" : { "textMateRules" : {} }` being declared after  `"workbench.colorCustomizations" : {}` to illustrate the point (why do this? another matter and I filed the issue describing it - in short **the square braces can't be separately colored while `"editor.bracketPairColorization.enabled": true`**).

Steps to reproduce _Instance 2 of Color not reported_ (all extensions disabled or not):
1. In settings.json, set `"editor.bracketPairColorization.enabled": true`. Save.
2. Create new javascript file and write 3 pairs of nested, normal braces and 1 or 2 nested square brace pairs inside the innermost normal brace pair.
3. Try to obtain the foreground color reading from the _Developer: Inspect Editor Tokens and Scopes **tooltip**_. It will show default gray.
4. Set colors of all 3 `"editorBracketHighlight.foreground1"-3` in `"workbench.colorCustomizations" : {}`.
5. Repeat step 3. It will not display the colors set in Step 4.

Steps to reproduce BUG of load order affecting colors of the square braces declared afterward (goal is selectively color square braces while normal braces have nested colors).
   6. Create theme `"editor.tokenColorCustomizations" : { "textMateRules" : {} }`) of scope `meta.brace.square` for setting the square brace to any color (like `#ff0000`) **after** `"workbench.colorCustomizations" : {}`.
   7. The square braces still retain nested coloring and not the specific scope color just set in Step 6.

**Comment by samusxx** [comment]
I had to edit it because of a mistake. (sorry).

**Comment by aeschli** [comment]
"editor.tokenColorCustomizations" is for token colors that are coming from syntax and semantic highlighting. 

All colors from editor features such as `bracketPairColorization`, `find`, `word highlight`, editor decorations go on top of the token colors and are defined in "workbench.colorCustomizations".

It's important to understand that the `Developer: Inspect Editor Tokens and Scopes` hover only is about the token colors. I see the confusion if the color at the current place happend to be a different color, e.g. due to an editor decoration.

**Comment by samusxx** [comment]
> We closed this issue because it is a question about using VS Code rather than an issue or feature request. 

**### It's not a question!** 
Don't assume his dismissal of the issue implies I'm wrong and it's a misunderstanding.

1. Developer: Inspect Editor Tokens and Scopes hover incorrectly identifies the color. This is a fact, regardless of "how it works". The UI reports the wrong color. Period.
2. If you put the `"editor.tokenColorCustomizations"` afterward, it should apply the color as an override feature. There should be a way to do this, to highlight the square brace while keeping the workbench colors. This is a FEATURE REQUEST to either respect the after declaration and make it somehow work, implement a priority property of scope's settings, or change the workbench to allow cases like square braces.

**Comment by samusxx** [comment]
Clarifying how it works made the other guy close the issue, by saying I
asked a question. This is clearly not the case. It's *still an issue* and
it's *very annoying*. A discussion could have taken place but it was
arbitrarily closed.

The color is still misrepresented by the UI and it's confusing.  Tell me
ANYWHERE IN THE WORLD a sign doesn't report what is meant? It never
happens.  This applies to the other issue that was summarily closed. The
problem is still present. The bot said it was "outside the scope of this
project" which is false.

**Comment by aeschli** [comment]
@samusxx Your issue description was a bit difficult to understand.

Is it fair to summarize:
a. the "editor.bracketPairColorization.enabled" settings sdescriptionhould mention the `editorBracketHighlight` colors
b. `Developer: Inspect Editor Tokens and Scopes` should also show colors coming from the bracket pair colorization`

**Comment by samusxx** [comment]
a. yes, when true.
b. or this option is also fine. but it should say it overrides a.

**this is better:**
C. the square braces `[ ]` colorization in the `workbench.colorCustomizations` settings and separated from `"editor.bracketPairColorization.enabled"` 

_The reasoning for this is, you don't need nested pair colorization on square braces_, but you sitill want it on regular...why? _because square braces are never far apart_, or rarely. I want to see a different color on them while `"editor.bracketPairColorization.enabled"`  is true and so would many others.

Implementation can be easier. 
1. Simply remove the square braces from `"editor.bracketPairColorization.enabled"` only. This immediately doesn't overwrite the [meta.braces.square].  _Resolved_
_Optionally also:_
2. If you want to allow nested colorization of square braces still, make a duplication of the code `"editor.bracketPairColorization.enabled"` to be `"editor.**square**BracketPairColorization.enabled"`, also still using `"editorBracketHighlight.foreground1"-3`. The latter can still use the 3 settings for normal braces it just is now selectively implemented between both `( )` and `[ ]` , so nothing more needs to change. 
_Optionally also:_
 3. Make `"editor**Square**BracketHighlight.foreground1"-3` to apply to nested `[ ]` square braces. Then `"editorBracketHighlight.foreground1"-3` needs to be set only to normal braces `( )`.
  

_**OR**_
A. Make a new property of `"TextMateRules" : {  { "settings" } }` called `priority`. This would be used for the final color determination above workbench, if `1`. And could also be useful for any other situation, because it would place the execution of the piece last (either by compiler, interpreter, or at a higher code level).

_**OR**_
B. Allow multi-declarion of JSON object literals, where they extend the first declaration, rather than override it.
Known issue: This may be problematic for any situation for overwriting the first declaration etc. Not sure how to resolve this complication.

So choose, 1.
Or choose, 1+2.
Or choose, 1+2+3.
Or A or B, alternatively.

**Comment by samusxx** [comment]
@aeschli Thankyou for replying to ask what is meant.

**Comment by aeschli** [comment]
ok, so the main request is: offer a way that bracket pair colorization does not include square braces ?
