### ISSUE TITLE
Better handling of TSServer issues

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#14230]
- VSCode Version: Code - Insiders 1.7.0-insider (788caba5a3ca1c2b137353f4384bb0e026db1a31, 2016-10-21T23:35:35.321Z)
- OS Version: Darwin x64 16.0.0

---

Steps to Reproduce:

1. I hovered the function and instead of information about function I just got `Loading ...` that was stuck forever
2. Going into Output Window:

![image](https://cloud.githubusercontent.com/assets/1723815/19627605/49fda1e6-9918-11e6-9239-698a4b38fcef.png)

3. I had to restart VSCode

**Comment by waderyan** [comment]
@wallverb thank you for opening this. We are seeing manifestations of this in a few different ways and are having a hard time recreating. Can you go to this [issue](https://github.com/Microsoft/TypeScript/issues/10735) and share any insights you might have on how to reproduce this behavior? 

Closing this as a dup of this [issue](https://github.com/Microsoft/TypeScript/issues/10735).

**Comment by waderyan** [comment]
Will reopen if there ends up being a different cause.
