### ISSUE TITLE
Can not commit any change from source control

### ISSUE THREAD

**Issue by kumard3** [microsoft/vscode#142335]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:
1. I cloned repo from GitHub.
2. I added new file to it and wrote something into it.
3. I pressed the "tick" button to commit the  changes.
I have add my personal access token , but still it is not working .

https://user-images.githubusercontent.com/62591080/152691965-fdb151da-3391-401c-a088-c60fdc3fc640.mov

**Comment by gjsjohnmurray** [comment]
In your screenshot it seems you didn't stage your change first.

**Comment by lszomoru** [comment]
@kumard3, could you please stage your changes first and then try to commit?

**Comment by misolori** [comment]
You should be able to commit without staging:

https://user-images.githubusercontent.com/35271042/157742986-939ccd38-2823-4f50-b514-863c8cf5776a.mp4

@kumard3 can you also check your user settings to see if you have `git.suggestSmartCommit` set to false? You may have chosen "No"

<img width="486" alt="CleanShot 2022-03-10 at 11 48 48@2x" src="https://user-images.githubusercontent.com/35271042/157743140-e00ab374-ff05-4952-8126-a01975d5da41.png">

**Comment by kumard3** [comment]
thank you every one for resolving my this issue 🤗
