### ISSUE TITLE
Could you please ask for confirmation when we delete a file in the VSCode explorer?

### ISSUE THREAD

**Issue by jvesouza** [microsoft/vscode#142395]
Issue Type: <b>Feature Request</b>

When we remove a file in vscode explorer, the file is deleted without any confirmation prompt. This in my opinion is bad because if I hit the del key by accident, the file will be removed and as I am blind it will probably take me some time to figure this out since the screen reader I use doesn't give me any indication that there was the file removal.
Maybe there is already a configuration option to activate confirmation but honestly I didn't find it.

VS Code version: Code - Insiders 1.65.0-insider (97c1e76d668d23d568044feb31083407f4c4b1ed, 2022-02-07T08:57:29.966Z)
OS version: Linux x64 5.16.5-arch1-1
Restricted Mode: No

**Comment by JacksonKearl** [comment]
by default you should see this:
<img width="356" alt="image" src="https://user-images.githubusercontent.com/8586769/152881904-b17cba2a-e99f-473b-8669-0904df5cd8ea.png">

you may have clicked the checkbox, in which case you should toggle this setting: 
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/8586769/152881976-18efd57d-e04e-4de1-807e-61e979474834.png">

is this in line with what you're seeing?

**Comment by jvesouza** [comment]
I didn't really know about this option, it's exactly what I was looking for.
Thank you very much.

**Comment by HongYurui** [comment]
Things just go opposite as I failed to delete any file without getting prompted, even after modifying "confirm delete". There's no "Do not ask again" on the prompting window, either.

**Comment by JacksonKearl** [comment]
@HongYurui please open a new issue if you are experiencing problems.
