### ISSUE TITLE
Api: allow customization of the tab border/color of all tabs

### ISSUE THREAD

**Issue by colemickens** [microsoft/vscode#142300]
I often have mono-repo type directories open in VSCode, with many tabs open in many panes, from various sub-projects. I was excited at the sight of "ColorTabs" - https://marketplace.visualstudio.com/items?itemName=orepor.color-tabs-vscode-ext as a way to bring a bit of quick-glance clarity to the barrage of tabs open.

But unfortunately, this seems to only be able to affect the currently visible tab, rather than being able to provide some sort of visual grouping/indicator to all of the tabs on screen.

My brain forgets where certain documents are and it's not the case that they're organized visibly on-screen by project. Sometimes there's a cross-cutting feature, but my brain still knows "oh for this feature, I next need to edit the [projectA] file, which I've already been editting, so we know it's an open tab with [projectA's color] tab-border.

Maybe I should try to get more accustomed to just using the quick switcher, but I still feel like this would be a pretty useful mental/visual coordination tool.

(I'm wondering if an example version could be hacked up, the colortabs extension could be modified write out a bit of extra CSS, on-the-fly, to produce tab-specific rules that would add the border highlight, or otherwise modify the tab appearance)

**Comment by colemickens** [comment]
I use VSCode via `code-server` and have authored a userscript that enables this in a less-than-ideal manner:

https://github.com/cole-mickens/nixcfg/blob/063d1b16a7b9bd676805350511a4e9d78ce0d529/misc/userscripts/vscode-tabhighlight.js

The userscript takes a bit of config like this:

```js
let assignments = {
  "~/code/nixcfg":          "darkviolet",
  "~/code/nixpkgs":         "dodgerblue",
  "~/code/nixpkgs/cmpkgs":  "deeppink",
  "~/code/tow-boot":        "orange",
  "~/code/mobile-nixos":    "green",
};
```

This results in:
![vscode](https://user-images.githubusercontent.com/327028/152667049-3069717d-88d3-4b55-8725-ef9ca08fdff2.png)

**Comment by bpasero** [comment]
//cc @lramos15

**Comment by colemickens** [comment]
So much for 10 more days, I guess. :) I'm fine with it being closed of course, I'm on to [Helix](https://github.com/helix-editor/helix)!

**Comment by lramos15** [comment]
Sorry about that, I misread the bots response. It's very similar to the closing one and I thought it just failed to close. Reopening to give it the necessary 10 days. Happy coding!
