### ISSUE TITLE
No Remote-SSH connection to Raspberry Pi 3b and 4 (ARM based) previously working properly

### ISSUE THREAD

**Issue by Napan0s** [microsoft/vscode#142318]
Does this issue occur when all extensions are disabled?: Yes/No
yes, other than the required ssh extension

- VS Code Version: 
Version: 1.65.0-insider (user setup)
Commit: 62de8dc3f78b8bef1eb62deeb093164a8d76c254
Date: 2022-02-04T11:47:20.200Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
ERROR is:  (node:3602) UnhandledPromiseRejectionWarning: Error: Cannot find module 'minimist'

Steps to Reproduce:

1. Try to connect to a remote device via the Remote-ssh extension
2. Connection (that was working properly up until 2 days ago) fails on all raspberrys that I tried:
3. I can connect to other non raspberry based devices (intel based) but none of the 8 different raspberrys that were configured are now working. Also tried with a different pc that was also configured and was working correctly in the past (windows 11 and same vscode insiders version) and still no connection.

**Comment by Napan0s** [comment]
Tried downloading VSCode and everything is working correctly.
Version: 1.64.0 (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by plwalsh** [comment]
And similar to @Napan0s switching over to the mainline *VSCode* v1.64.0, it also works to roll back to a *VSCode - Insiders* release from last week, such as:

https://az764295.vo.msecnd.net/insider/5554b12acf27056905806867f251c859323ff7e9/VSCodeUserSetup-x64-1.64.0-insider.exe

```
Version: 1.64.0-insider (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-02T17:16:15.360Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by stygarfield** [comment]
I'm having the same issue when trying to connect to a Raspberry Pi 4.

Have tried killing/uninstalling the server, and still no joy on connecting.

`[12:06:00.098] > Server did not start successfully. Full server log at /home/pi/.vscode-server-in
> siders/.97c1e76d668d23d568044feb31083407f4c4b1ed.log >>>
> (node:28749) UnhandledPromiseRejectionWarning: Error: Cannot find module 'minimi
> st'
[12:06:00.105] > 
> Require stack:
> - /home/pi/.vscode-server-insiders/bin/97c1e76d668d23d568044feb31083407f4c4b1ed/
> out/server-main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15) 
>     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
[12:06:00.120] > 
>     at start (/home/pi/.vscode-server-insiders/bin/97c1e76d668d23d568044feb31083
> 407f4c4b1ed/out/server-main.js:1:292)
>     at Object.<anonymous> (/home/pi/.vscode-server-insiders/bin/97c1e76d668d23d5
> 68044feb31083407f4c4b1ed/out/server-main.js:11:28)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)   
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:28749) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
>  error originated either by throwing inside of an async function without a catch
>  block, or by rejecting a promise which was not handled with .catch(). To termin
> ate the node process on unhandled promise rejection, use the CLI flag `--unhandl
> ed-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejecti
> ons_mode). (rejection id: 1)
> (node:28749) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
> ecated. In the future, promise rejections that are not handled will terminate th
> e Node.js process with a non-zero exit code.
> <<< End of server log
> a165f0e86134: start
> exitCode==32==
> listeningOn====
> osReleaseId==raspbian==
> arch==armv7l==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult==success==
> didLocalDownload==0==
[12:06:00.125] > 
> downloadTime==2500==
> installTime==41217==
> extInstallTime====
> serverStartTime==7134==
> a165f0e86134: end
[12:06:00.126] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==raspbian==
arch==armv7l==
tmpDir==/run/user/1000==
platform==linux==
unpackResult==success==
didLocalDownload==0==
downloadTime==2500==
installTime==41217==
extInstallTime====
serverStartTime==7134==

[12:06:00.129] Cannot find module 'minimi

[12:06:00.130] Resolver error: Error: Cannot find module 'minimi

	at Function.ServerInstallError (c:\Users\styga\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.73.2022020715\out\extension.js:1:585851)
	at d (c:\Users\styga\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.73.2022020715\out\extension.js:1:578326)
	at Object.t.handleInstallOutput (c:\Users\styga\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.73.2022020715\out\extension.js:1:582959)
	at Object.t.tryInstall (c:\Users\styga\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.73.2022020715\out\extension.js:1:680470)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\styga\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.73.2022020715\out\extension.js:1:643329
	at async Object.t.withShowDetailsEvent (c:\Users\styga\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.73.2022020715\out\extension.js:1:646674)
	at async Object.t.resolve (c:\Users\styga\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.73.2022020715\out\extension.js:1:644408)
	at async c:\Users\styga\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.73.2022020715\out\extension.js:1:721424
[12:06:00.147] ------`

**Comment by cmendible** [comment]
Same issue with WSL2 on ARM64 device, as mentioned here: https://github.com/microsoft/vscode-remote-release/issues/6294 

I'm experiencing: `(node:302) UnhandledPromiseRejectionWarning: Error: Cannot find module 'minimist'` while trying to open a folder on WSL2.

My setup:

```
Device name	...
Processor	Microsoft SQ2 @ 3.15 GHz   3.15 GHz
Installed RAM	16.0 GB (15.5 GB usable)
Device ID	...
Product ID	...
System type	64-bit operating system, ARM-based processor

Edition	Windows 11 Pro
Version	21H2
Installed on	‎11/‎25/‎2021
OS build	22000.469
Serial number	...
Experience	Windows Feature Experience Pack 1000.22000.469.0

Version: 1.65.0-insider (user setup)
Commit: 97c1e76d668d23d568044feb31083407f4c4b1ed
Date: 2022-02-07T08:56:11.586Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT ia32 10.0.22000 
```

**Comment by Napan0s** [comment]
Also, I tried the solution from the WSL2 issue and it did not work for me.
[https://github.com/microsoft/vscode-remote-release/issues/6294](url)

From @thesteve0:
> OK here is how I fixed it:
> 
> 1. Open VS Code on Windows
> 2. Open Extensions and then search on WSL
> 3. It should say the extension needs to be reloaded - go ahead and reload it
> 4. Open WSL and type `code`
> 5. This should force another upgrade of code and this time it should launch.
> 
> I actually closed Code on windows and WSL after this and then tried to launch code from WSL and it worked. Hope this helps

**Comment by Napan0s** [comment]
Yes, as said in my first comment, the stable version works just fine 

> Tried downloading VSCode and everything is working correctly. Version: 1.64.0 (user setup) Commit: [5554b12](https://github.com/microsoft/vscode/commit/5554b12acf27056905806867f251c859323ff7e9) Date: 2022-02-03T04:22:20.678Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.22000

**Comment by stygarfield** [comment]
@roblourens It seems to be working now, as per at least the latest build

Version: 1.65.0-insider (user setup)
Commit: 1aa9684ba81ae56b340981411a3deaf19544bafa
Date: 2022-02-10T02:55:15.514Z
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by deepak1556** [comment]
\closedWith [1aa9684ba81ae56b340981411a3deaf19544bafa](https://github.com/microsoft/vscode/commit/1aa9684ba81ae56b340981411a3deaf19544bafa)

**Comment by Napan0s** [comment]
It works indeed. Thank you all for the support!

**Comment by cmendible** [comment]
Working for ARM64 too! Thanks!

```
Version: 1.65.0-insider (user setup)
Commit: 82a8bec63666b0883d9bf762ee2aaa87e9be9a3a
Date: 2022-02-10T05:17:03.659Z
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Windows_NT arm64 10.0.22000
```
