### ISSUE TITLE
Bold text when converting Japanese.

### ISSUE THREAD

**Issue by standard-software** [microsoft/vscode#142371]
Issue Type: <b>Bug</b>

When you are writing markdown
The "#" and "###" characters are displayed in bold.
If you perform Japanese conversion at that location, the text will be converted in bold.

After that, even if the markdown description does not show "#" or "##", it will be converted in bold.
In the process of Japanese conversion
It becomes bold characters during conversion.

If you do "Developer: Reload Window", the problem will go away.

This problem seems to occur in recent versions.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by tsupox** [comment]
I've faced the same issue today.
I took two gif animations during typing Japanese - markdown and plain text.
Please see attached files.

<MARKDOWN - inputted Japanese>
日本語だと、変換時に太字になっています。
確定後、通常に戻ります。
In Japanese, it is in bold when converted.
After confirmation, it will return to normal.

![github_142371](https://user-images.githubusercontent.com/93517937/153994785-382a0070-d0c8-4928-8284-3e3a6a8e73fc.gif)

<PLAIN TEXT - inputted Japanese>
日本語でも、変換時に太文字になってないことがわかります。
Even in Japanese, you can see that it is not bold when converted.

![github_142371_2](https://user-images.githubusercontent.com/93517937/153995401-b95a257e-d1df-4b06-8c9d-c311eb869340.gif)
