### ISSUE TITLE
enableShellIntegration issue with PowerShell built-in keyboard shortcuts

### ISSUE THREAD

**Issue by wsmelton** [microsoft/vscode#142354]
Testing with Insider Edition and PowerShell 7.2.1 the shortcuts associated with PSReadline are not usable.

Enable shell integration, open a new terminal and load some content (file output, etc.). Try using CTRL+L to clear the shell screen and only output is `^L`.

When the shell is loaded you can run `Get-PSReadlineKeyHandler` and this shows the enabled shortcut keys. `CTRL+L` is tied to `ClearScreen` function.

**Comment by Tyriar** [comment]
@wsmelton could you retest with today's build? We made some tweaks late last week: https://github.com/microsoft/vscode/commit/7ec8fa422f465aa250d99ff930d9c8924d4dda2a

**Comment by wsmelton** [comment]
Yep, confirmed latest build resolves this issue.
