### ISSUE TITLE
Scrolling Issue

### ISSUE THREAD

**Issue by GourishettySairam** [microsoft/vscode#142344]
Whenever i am editing a line, and use my mousepad to scroll a little bit, then I am losing my focus on my editing part. 
Scrolling a little bit is taking me to some other place in the editor.

please fix this issue.

Attaching the same problem's complete description: https://github.com/microsoft/vscode/issues/28795#issuecomment-341273788

**Comment by alexdima** [comment]
Let's track in #28795
