### ISSUE TITLE
Extract Method command not available

### ISSUE THREAD

**Issue by jdavchev** [microsoft/vscode#142317]
Issue Type: <b>Bug</b>

Extract Method command not available. Using latests visual studio code and latest python extension on macOS M1.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:20:22.135Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.03GB free)|
|Process Argv|--crash-reporter-id f175f91e-2d5e-4be1-8c1d-f741d27f7564|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
vim|vsc|1.21.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vs360:30404995
vsrem710cf:30416617
vscscmwlcmc:30433760

```

</details>

**Comment by mjbvz** [comment]
Please provide steps to reproduce the issue. What language is this even for?

**Comment by jdavchev** [comment]
1. Brand new macbook m1.
2. installed vscode build.
3. installed python extension (full list reported originally with the issue).
4. Read the whole vscode manual. When tried "Extract method" command I couldn't find it/use it.  (see attached image).

<img width="1217" alt="Screenshot 2022-02-07 at 22 02 51" src="https://user-images.githubusercontent.com/58908009/152862937-fe037159-8959-41b7-852b-fe1f33f138db.png">

Hope this puts more clarity. Thanks.

P.S. Followed the steps through Help->Report Issue in vscode.

**Comment by jdavchev** [comment]
Is there any update on the issue?
