### ISSUE TITLE
"ś" letter cannot be entered into Integrated Terminal

### ISSUE THREAD

**Issue by pmbanka** [Microsoft/vscode#14234]
- VSCode Version: 1.6.1
- OS Version: Windows 10 pro (10.0.14393 Build 14393)

Steps to Reproduce:
1. Open Integrated Terminal (cmd.exe)
2. Paste any text containing letter "ś" to the terminal

Result:
String which appears in Integrated Terminal does not contain "ś" letters anymore. For example, trying to paste "---śśś---" results in "-----" appearing in the command line (notice one dash missing).

All other Polish letters work without issues (use "zażółć gęślą jaźń" for testing).

**Comment by wojtekmaj** [comment]
I believe that is because alt+[letter] is doing the same as ctrl+[letter] in some languages (most languages). Polish is one of the exceptions here, and when Polish language support is added, that should be fixed.

**Comment by wojtekmaj** [comment]
Connected issues: #13198 #11090 #9205
A serious issue for Polish keyboard users...

**Comment by Tyriar** [comment]
Let me know if you're still experiencing this issue in 1.11
