### ISSUE TITLE
Triple click should select whole line

### ISSUE THREAD

**Issue by hickford** [Microsoft/vscode#1423]
Open a document with a long line, so that it wraps. Triple click should select the whole logical line, not just one physical line.

This works correctly in other text editors:

1. Notepad++
2. Sublime Text
3. Atom
3. Microsoft Word
4. Google Chrome
5. Internet Explorer

![image](https://cloud.githubusercontent.com/assets/105314/11873172/1de66426-a4d1-11e5-8e1d-eddc0582e770.png)

[alice.txt](https://github.com/Microsoft/vscode/files/65528/alice.txt)

**Comment by hickford** [comment]
Visual Studio (the IDE) has the same bug, but I don't know where to report it

**Comment by bpasero** [comment]
@alexandrudima fyi

**Comment by alexandrudima** [comment]
We actually shipped already in February with the proposed behaviour.

**Comment by hickford** [comment]
Thanks. Works for me `Version 0.10.11`

**Comment by hickford** [comment]
The same bug still occurs in Visual Studio. Please vote for https://developercommunity.visualstudio.com/content/problem/138283/triple-click-should-select-logical-line.htmla
