### ISSUE TITLE
Terminal malfunction

### ISSUE THREAD

**Issue by AquibAmin** [microsoft/vscode#142331]
Issue Type: <b>Bug</b>

Terminal is not working. It displays a warning 'Extensions have made changes to this terminal's environment'.
This issue is very irritating. I have tried everything, uninstalled and installed vs code, killed and switched terminals but nothing works.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 6.2.9200
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (1.64GB free)|
|Process Argv|--crash-reporter-id 6894a386-3d02-40e9-aa32-8e61a3063bc2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.2.3
vscode-django|bat|1.8.0
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
vscode-test-explorer|hbe|2.21.1
vsc-python-indent|Kev|1.14.2
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
test-adapter-converter|ms-|0.1.5
dot|Ste|0.0.1
python|tht|0.2.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vscop453:30404998
vsrem710cf:30416617
vscop841cf:30430978

```

</details>

se it was too large to send. Please paste.

**Comment by MarkMoretto** [comment]
I'm not part of the Microsoft team, but have you tried enabling / disabling different extensions to see which one might be triggering the error?

Also, it might be good if you could provide a list of extensions that you have installed in VSCode. You can do that from the command line via the following command (assuming VSCode is on your PATH):

`code --list-extensions`

**Comment by meganrogge** [comment]
You can also run the command extension bisect that will disable  extensions for you to identify the troublemaker
