### ISSUE TITLE
"it is recommended" is overly passive

### ISSUE THREAD

**Issue by jpeddicord** [Microsoft/vscode#14238]
- VSCode Version: 1.6.1
- OS Version: Linux

Time for a really petty bug report. Ready?

There are several locations where VS Code uses "it is recommended" without any context, and it just feels wrong. Specific examples:
- "It is recommended to keep the commit's first line under 50 characters" when typing a commit message > 50 char. **What** is recommending that? This could be reworded as:
  - "The Git style guide recommends the first line is under 50 characters."
- "It is recommended to install the 'someone.something' extension" when opening certain filetypes. **What** is recommending this and **why**? Plenty of replacements here; off the top of my head:
  - "You may want to install '{extension}' to edit this type of file."
  - "The extension '{extension}' may be useful in your project." -- still kind of vague, but removes the "it" that doesn't refer to anything
  - "This filetype can be handled by the '{extension}' extension in the Marketplace."

You can see more [in a search](https://github.com/Microsoft/vscode/search?utf8=%E2%9C%93&q=%22it+is+recommended%22), though the two above are the main ones that are a little bothersome.

**Comment by roblourens** [comment]
Worth thinking about, although I'm not sure where to send this issue.

**Comment by pcgeek86** [comment]
I think it's a sound recommendation to improve the user experience. Good feedback.

**Comment by davidwhitman** [comment]
Just came here to add this as an issue, as well. "It is recommended..." immediately tripped my "non-native speaker" alarm because it's a very common phrasing that, for examples, some of my Romanian colleagues would use. 

It's technically correct, of course, but doesn't feel right as OP stated, with examples. 

unrelated, but it took me a while to figure out why this was tagged as "polish" when it's clearly only an English issue.

**Comment by callummr** [comment]
Just had one of these pop up saying "It is recommended to install the docker extension" when I wasn't doing anything with docker. Ended up here wondering if advertising was introduced to Code or something, so I definitely think it's worth changing.
