### ISSUE TITLE
Code conflict resolution shortcut is gone

### ISSUE THREAD

**Issue by wsw2000** [microsoft/vscode#142372]
<img width="846" alt="image" src="https://user-images.githubusercontent.com/63382474/152736155-eb19e6b1-0214-4010-a030-87f4f5ffdb26.png">
What I want is git code conflict. There will be shortcut keys such as current modification, but I don't have money at present. I'm the vscode of Mac version

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

Please also post version and platform information.

/needsMoreInfo
