### ISSUE TITLE
Property 'moduleName' is missing in type.

### ISSUE THREAD

**Issue by sverrirs** [Microsoft/vscode#14239]
- VSCode Version: master branch
- OS Version: Win7

Hi,

I checked out the master branch code and am playing around with the code. 

However I keep running into this same error for every class I create and add to the project when I try to use the IInstantiationService to create an instance of it.

The error is always the same but MY_TYPE is different and the X-number of the AsyncDescriptorX class (depending on the number of constructor arguments needed).
```
Error: Argument of type 'typeof MY_TYPE' is not assignable to parameter of type 'AsyncDescriptor0<>'.  Property 'moduleName' is missing in type 'typeof MY_TYPE'.
```
for code
```
const dataSource = this.instantiationService.createInstance(MY_TYPE);
```

Is there something non-obvious that I must do when creating new classes. This happens also when I create a new class that has the exact same implementation as an existing class in the project (just a different class-name and file-name).

Cleaning, building, restarting, etc do not work.

Steps to Reproduce:

1. Create any new class in the master branch
2. Use the `instantiationService.createInstance()` function to instantiate it

**Comment by roblourens** [comment]
Can you post the code for `MY_TYPE`?

**Comment by sverrirs** [comment]
Hi Rob, 

Sure thing, all the code I've been working on is in my feature branch at https://github.com/sverrirs/vscode/tree/ftp-vscode

I didn't want to complicate things with actual code if this was something obvious.

The problematic classes are:

```
vs/workbench/parts/ftp/browser/views/ftpView.ts(116,57): Argument of type 'typeof RefreshFtpSiteAction' is not assignable to parameter of type 'AsyncDescriptor2<ITree, FileStat, {}>'.
  Property 'moduleName' is missing in type 'typeof RefreshFtpSiteAction'.
  
vs/workbench/parts/ftp/browser/views/ftpView.ts(159,63): Argument of type 'typeof FtpFileDataSource' is not assignable to parameter of type 'AsyncDescriptor0<{}>'.
  Property 'moduleName' is missing in type 'typeof FtpFileDataSource'.
  
vs/workbench/parts/ftp/browser/ftpViewlet.ts(113,77): Argument of type 'typeof FtpView' is not assignable to parameter of type 'AsyncDescriptor4<FtpViewletState, IActionRunner, any, number, {}>'.
  Property 'moduleName' is missing in type 'typeof FtpView'.
```

Cheers,
Sverrir S.

**Comment by jrieken** [comment]
This error usually means that the call to `createInstance` doesn't provide the constructor arguments needed to create the object. Like 

```
class MY_TYPE {
 constructor(a: number) {}
}

createInstance(MY_TYPE, "not a number");
```

**Comment by sverrirs** [comment]
Hi Johannes,

Oh dear, I just realized that all the classes depend on a new service I created `IFtpService`. I haven't explicitly registered it with the dependency injection container. How do you go about registering your types with the instantiation service?

**Comment by sverrirs** [comment]
Thanks for your replies Johannes and Rob. I found the issue. I noticed that all the services in the codebase had a `_serviceBrand: any;` declared on their interfaces. My service didn't include this member and as soon as I added it the errors went away. 

Thanks again for taking the time to reply. Cheers!
Sverrir S.
