### ISSUE TITLE
Small Customize Layout Update

### ISSUE THREAD

**Issue by Samyak-Bumb** [microsoft/vscode#142385]
Add **Toggle Breadcrumb**, in Customize Layout.

**Comment by misolori** [comment]
I believe the original idea was to show the most popular entries from the "Appearance" menu as this can become a slippery slope to just re-introduce the same entries:

<img width="501" alt="CleanShot 2022-02-07 at 14 14 23@2x" src="https://user-images.githubusercontent.com/35271042/152881263-5c9eacd9-771c-416f-9616-1cc4b9036288.png">

**Comment by sbatten** [comment]
I also agree that this is not really a layout feature

**Comment by Samyak-Bumb** [comment]
> I also agree that this is not really a layout feature

Bro, It Can Change the Look of VSCode some people (like me) don't like breadcrumb but some times it is used & it's imp roll in **layout**.
