### ISSUE TITLE
Debugger stops after 1 second of launching

### ISSUE THREAD

**Issue by Engensmax** [microsoft/vscode#142384]
We have written the needed d
Issue Type: <b>Bug</b>

The debugger does not start and immediately stops after 1 second of launching. The debug icons are visible for that brief time (like pause, step over, step into, etc). It does not work with and without a launch.json file. I use the default python debugger configuration ("python current file (workspace)").
This issue appeared today and was not present last week.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
python-preview|don|0.0.4
xml|Dot|2.5.1
gitlens|eam|11.7.0
gc-excelviewer|Gra|4.0.50
favorites|kdc|2.4.5
vsc-python-indent|Kev|1.14.2
git-graph|mhu|1.30.0
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
vscode-python-typehint|njq|1.4.1
vscode-yaml|red|1.4.0
vscode-qt-for-python|sea|1.1.7
python|tht|0.2.3
vscode-counter|uct|3.0.3
vscode-todo-highlight|way|1.0.5

(1 theme extensions excluded)

</details>
ata into your clipboard because it was too large to send. Please paste.

**Comment by 0kto** [comment]
I am running into the same problem, updated VS Code this morning.

VS Code version: Code 1.64.0
OS version: Windows_NT x64 10.0.19044

<html>
<body>


CPUs | Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 31.76GB (17.70GB free)
Process Argv | --crash-reporter-id 81e7c2a9-89a2-416d-bc10-06f1aa23d832
Screen Reader | no
VM | 0%
Remote | WSL: Arch
OS | Linux x64 5.10.60.1-microsoft-standard-WSL2
CPUs | Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (6 x 2304)
Memory (System) | 23.48GB (20.46GB free)
VM | 0%


</body>
</html>

**Comment by weinand** [comment]
May be your program is short running and actually finishes fast?
Do you see the same behavior if you set a breakpoint on a line of your program and the start debugging?

**Comment by 0kto** [comment]
Yes, I have set multiple breakpoints.
Usually, the debugger opens up a new terminal, changes into the (conda) environment, and executes the program, with all the logging data visible in the terminal.  This is not happening at all.

**Comment by Engensmax** [comment]
Yes, breakpoints have no effect on the behaviour.

**Comment by 0kto** [comment]
Thanks :)

**Comment by Engensmax** [comment]
Solved by installing previous version of the python extension.
Also discussed here:
https://github.com/microsoft/vscode-python/issues/18453
