### ISSUE TITLE
Outline view dissapeared

### ISSUE THREAD

**Issue by molt-coder** [microsoft/vscode#142346]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.0
- OS Version: WIn 10 Pro, 10.0.19044 fully patched

Steps to Reproduce:

1. I have used the new feature and positioned Code Outline outside the Explorer and to the right
2. After a while I noticed the Code Outline dissapeared from one instance of VC and then on restarting the other instance of VC (I had 2 instances running) Code Outline was out for good. 
3. Interestingly, I can navigate classes etc in the breadcrumbs just below the file's tab header. But the Outline that was in Explore before is nowhere to be seen. 
4. I have tried looking in options, settings, explorer three dots etc for a way to activate the Outline view (as my guess it just got closed somehow) but I can't find outline view anywhere. 3. There does not seem to be a way to deliberatly opening of Code Outline if it's not available.
4. Sorry I know this is not a reproducible description of a bug
5. I tried disabling extensions but did this not help
6. I have tried switching projects (tried JavaScript/React and Python/Django) but it didn't seem Outline was related to the language or type of project. Breadcrumbs worked in both projects.

**Comment by molt-coder** [comment]
Just to add, I have tried this with 2 different projects, one using JavaScript/React and another Python/Django so availability of Outline was not linked to the type of project etc. Breadcrumbs worked in both cases though.

**Comment by gjsjohnmurray** [comment]
Maybe you dragged it into the new Side Panel and then the Side Panel got hidden. Try running the `View: Toggle Side Panel` command.

**Comment by vushe** [comment]
I confirm the issue for Timeline view as well. It looks like everything moved to side panel and then hidden from there from side bar becomes unavailable from everywhere, including new side panel as well.

**Comment by vushe** [comment]
I was able to fix the issue by `Ctrl+Shift+P` -> `Focus on outline view`, `Focus on timeline view`.
Outline appeared as a tab in terminal window 🤣 
In order to fix timeline, I had to disable "GitLens" extension first.
PS Last time I updated VSCode so fast.

**Comment by molt-coder** [comment]
Thanks all `View: Toggle Side Panel` did sort it for me and the pannel appeared in the right place too. 

It would seem logical that there is a tickbox in the "View" menu to enable/disable Outline panel as it is one of the core panels. 

The config options via the command bar are powerful but let's be honest, is really only suitable for one-off advanced tasks. It is just not convenient or memorable enough for everyday usage.

**Comment by gjsjohnmurray** [comment]
@molt-coder do you have this control on your title bar, with a menu appearing when you click it?

![image](https://user-images.githubusercontent.com/6726799/152756904-0583d207-a751-4598-b71c-c1479f2c5c97.png)

If not, this is the setting you need:

```json
"workbench.experimental.layoutControl.enabled": true
```

**Comment by molt-coder** [comment]
Thanks John, once again you're a life saver! I didn't have that control and have just enabled it. 

I hope Microsoft makes this a little bit more intuitive soon and without requireing 'experimental' controls

**Comment by gjsjohnmurray** [comment]
@sbatten I think that if the user's action in one window (e.g. drag of Outline to the opposite side) causes the Side Panel to be made visible in that window, it should do the same in all other open windows. I can see the sense in visibility changes to the panel etc not generally applying to all windows, but in this case it should probably happen. Or maybe only if the Side Panel was empty until the view got dragged onto it.

**Comment by sbatten** [comment]
@gjsjohnmurray interesting idea, i can see the logic in that
