### ISSUE TITLE
[Feature Request] REST Client

### ISSUE THREAD

**Issue by Vladimir37** [Microsoft/vscode#14231]
REST client (or HTTP client) supported in IDEA and other IDEs and editors.

How it work:

1) Enter url.
2) Select type (GET/POST/PUT/DELETE)
3) Add request data:
3.1) Click "Add parameter"
3.2) Add key
3.3) Add value
3.4) GOTO 3.1
4) Send http request
5) See response (may be different MIME-types)

Many developers need this REST client. REST client need for debug API and web-application without HTML interface.

**Comment by kaiwood** [comment]
https://marketplace.visualstudio.com/items?itemName=humao.rest-client

**Comment by Phrohdoh** [comment]
I think Postman / Advanced REST Client / the above-linked addin / etc. cover this just fine.
vscode should not be a catch-all for developer tooling.

**Comment by Vladimir37** [comment]
>https://marketplace.visualstudio.com/items?itemName=humao.rest-client

Thanks, but REST client with GUI (like pic) more comfortable.
![restclient_7173](https://cloud.githubusercontent.com/assets/10130199/19637657/45d26380-99e1-11e6-8748-c616a6b173d2.png)

**Comment by Phrohdoh** [comment]
https://www.getpostman.com/
https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo

**Comment by mjbvz** [comment]
Closing as extension candidate. Please see [this guide](https://code.visualstudio.com/docs/extensions/overview) for information about authoring an extension
