### ISSUE TITLE
Can't find proxy setting

### ISSUE THREAD

**Issue by relgaard** [microsoft/vscode#142324]
Issue Type: <b>Bug</b>

I'm using this version of VS Code:
Version: 1.64.0 (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363

I have until this update been using VS Code without any problems. The problem occursw both when via the Azure extension tries to conenct to Axure and when I try to check for updates in the help menu - so it seems to be a generel problem.
Pretty annoying - please help

Thanks in advance
Robert Elgaard

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (2.47GB free)|
|Process Argv|--crash-reporter-id fea21742-3685-4326-ae39-b2e5d85ea516|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azureappservice|ms-|0.18.0
csharp|ms-|1.24.0
data-workspace-vscode|ms-|0.1.1
mssql|ms-|1.12.0
sql-database-projects-vscode|ms-|0.14.1
azure-account|ms-|0.9.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30433058
pythonvs932:30410667
vscop453:30404998
vsrem710cf:30416617

```

</details>

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode/issues/142201.

**Comment by relgaard** [comment]
> Issue Type: Bug
> 
> I'm using this version of VS Code: Version: 1.64.0 (user setup) Commit: [5554b12](https://github.com/microsoft/vscode/commit/5554b12acf27056905806867f251c859323ff7e9) Date: 2022-02-03T04:22:20.678Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.18363
> 
> I have until this update been using VS Code without any problems. The problem occursw both when via the Azure extension tries to conenct to Axure and when I try to check for updates in the help menu - so it seems to be a generel problem. Pretty annoying - please help
> 
> Thanks in advance Robert Elgaard
> 
> VS Code version: Code 1.64.0 ([5554b12](https://github.com/microsoft/vscode/commit/5554b12acf27056905806867f251c859323ff7e9), 2022-02-03T04:22:20.678Z) OS version: Windows_NT x64 10.0.18363 Restricted Mode: No
> 
> System Info
> Extensions (6)
> A/B Experiments

Thanks guys, but how do I get the new release when VS Code can't communicate :(
When I click 'Check for updates....' in the help-menu I instantly get 'ER_PROXY_CONNECTION-FAILED' ??

![image](https://user-images.githubusercontent.com/58980013/152804635-844c292f-f612-489b-8025-0b73827aaf9c.png)

**Comment by chrmarti** [comment]
@relgaard That is a different issue, please open a new bug report. Thanks.
