### ISSUE TITLE
Recent update has made the terminal panel more challenging to move from left or bottom locations

### ISSUE THREAD

**Issue by timothymarois** [microsoft/vscode#142362]
This isn't a bug, but it's part of a feature, and looks like it was released during the recent update, which has made it complicated now to move the terminal from the bottom to the right side and vise versa. This used to be easy, and maybe it still is, but the view menu controls no longer work as you would expect with the terminal panel, and a bit annoying moving from large resolutions to  reduced, and not have an easy way to flip the view.

**Comment by timothymarois** [comment]
There's no longer a way to change the terminal from bottom to left side and vice-versa from the view menu like it was in the previous version.

<img width="532" alt="Screen Shot 2022-02-06 at 8 37 22 PM" src="https://user-images.githubusercontent.com/2489333/152711853-c00e3aaa-0850-4833-9899-95e404aee31a.png">

**Comment by dkms-its** [comment]
That's a bit of a bummer. I was using the terminal on the right side because i simply have enough space on an extra-wide monitor. While i could move the terminal to the new side panel, the shortcut to toggle the terminal (CMD + J) doesn't work anymore and there's also no (obvious) possibility to maximize the side panel as it was possible with the terminal.

Bottom line, at least for me, the side panel is an unfinished step backwards.

**Comment by sbatten** [comment]
Addressing a few items brought up here:

**Quickly moving the panel left/right/bottom**
<img width="209" alt="image" src="https://user-images.githubusercontent.com/6561887/152856005-54df5882-a3b7-4507-9c45-3f381da868ab.png">

There are new commands for this, the guidance is to use these instead, but the old move panel commands are remapped to this. The new commands are "Move views from panel to side panel" and "Move views from side panel to panel". Also you can use the context menu of the panel to quickly execute this action from the mouse.

**Command+J does not toggle the side panel**
That's right, there is a separate command "Toggle Side Panel" that you can bind to whatever keybind you like. You can also use `Ctrl+Backtick` if your primary view in the panel is terminal.


@timothymarois the new commands are intended specifically for the use case you describe so please let me know if I misunderstand.

**Comment by laukondrup** [comment]
@sbatten I am facing the same "issue" and followed your instructions.

My issue now is that `Side Panel` seems to be hard-coded to be opposite the `Side Bar`. My personal preference, which was supported before, is to have both `Side Panel` and `Side Bar` on the right side and only code editors on the left.

Please let me know if I can recreate that setup somehow 😊

**Comment by sbatten** [comment]
@laukondrup we reintroduced the bottom panel movement to the left/right of the editor. if your use case is to have the side bar and panel next to each other, this is the recommended setup today.
