### ISSUE TITLE
Strange behaviour backticking selected code.

### ISSUE THREAD

**Issue by CaBazaga** [microsoft/vscode#142389]
Issue Type: <b>Bug</b>

Select a piece of text then press ` key to backtic it as a whole.
As trying to set it as a code snippet on markdown.
(detected while doing so but problems exists with independence of the language)

The text momentarly dissapears and it resembles like a prompt expecting some input, any key press seems to finish that strange state and ends with the text backticked, but it requires one more keypress/click than expected that may lead to erased content.

Also not sure what's the purpouse of that behabiour, found not documentation neither refferences on the changelogs.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:20:17.224Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.0
gitignore|cod|0.7.0
vscode-markdownlint|Dav|0.46.0
gitlens|eam|11.7.0
LogFileHighlighter|emi|2.14.0
gc-excelviewer|Gra|4.0.50
todo-tree|Gru|0.0.215
restructuredtext|lex|168.0.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.19.0
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.1
remote-wsl|ms-|0.64.2
live-server|ms-|0.2.12
vsliveshare|ms-|1.0.5330
code-spell-checker|str|2.1.5
mako|tom|0.2.0
pdf|tom|1.2.0
simple-rst|tro|1.5.1
markdown-pdf|yza|1.4.4

</details>

**Comment by gjsjohnmurray** [comment]
Did you investigate whether one of your extensions is causing this? Please use the `Start Extension Bisect` command.

**Comment by CaBazaga** [comment]
Hi @gjsjohnmurray, thanks for your fast response.

I did the bisect test:
`Extension Bisect is done but no extension has been identified. This might be a problem with Code.`

I'm attaching a video of the behaviour:

https://user-images.githubusercontent.com/86959571/152809563-e9c99376-0790-482a-9fcc-c16aa7b95093.mov

Despite it says is markdown it's actually plain text editor, no highlight done. 
Verified it to happen at least on markdown files, plain text, python and sh by now. 

As you can see, until I click out or press any key the text is gone, just one backtick is present and seems to be waiting for something.

**Comment by gjsjohnmurray** [comment]
Maybe you have a keybinding that is causing this.

Use the `Preferences: Open Keyboard Shortcuts (JSON)` command

Try commenting out all the array elements by adding a `/*` line immediately after the `[` line and a `*/` immediately before the `]`. Save the change, then re-test.

**Comment by CaBazaga** [comment]
Done, no change, also, I'm usually using markdown and so using the `a lot for marking text as code snippet.

Both block with 

```codelang
my code
```
 and single line with `my code`
 
 But the first time noticing this behaviour is today.
 
 I made an update, not sure friday last hour or today at first, but not noticed this behaviour before despite.
 I searched for a downgrade option inside vscode, similar as with extensions, to test when it started to do this but found none.
 
 I test on a windows machine, the issue described happened on MAC, in which I had an outdated vsc, behaves completely different, before and after update, there I have to press twice the ` key in order for it to actually backtick the word.
 
 In any case I'm not sure how it behaves before on windows as I'm not usually coding under windows.

**Comment by gjsjohnmurray** [comment]
It works OK for me on Windows (all extensions disabled). Double-click to select the word. Press backtick key once and the word gets wrapped. This is Plain Text language mode, which I think is what you reported it on.

![junk](https://user-images.githubusercontent.com/6726799/152832046-0c4df77e-45c1-41c0-9e75-54892eea4701.gif)

My version info:

Version: 1.64.0 (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by CaBazaga** [comment]
I made some tests and concluded this is related to macOS, I've been noticing this behaviour on other editors now, it stays like waiting for some extra input and once it's done then it's properly sent to the editor, which is when VSCode backticks the word.

And it only happens on "spanish" layout, switching to UK PC standard it does not behave like that and backtics works as expected.

VSCode +1
macOS   -1
😃 

It may be closed, thanks a lot for your time.

**Comment by rzhao271** [comment]
I wonder if it is a dead key layout. On layouts such as US-International on Windows, you have to press another key after the backtick to even get the backtick to show up. Therefore, backtick + space = `, backtick + e = è, and so on.
