### ISSUE TITLE
Extension's settings often not shown

### ISSUE THREAD

**Issue by vanowm** [microsoft/vscode#142450]
Issue Type: <b>Bug</b>

When opening an extension's settings it opens settings tab, but more often than not it doesn't automatically filter the settings with `@ext:myextension` filter, sometimes it shows totaly different extension's setting instead. I have to click on extension's setting icon several times before it properly filters settings.
I do normally have mutiple VSC windows opened.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.95GB (39.38GB free)|
|Process Argv|--verbose|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-userscript|adp|1.3.2
vscode-log-viewer|ber|0.12.2
vscode-intelephense-client|bme|1.8.0
insert-unicode|bru|0.13.1
bracket-pair-colorizer-2|Coe|0.2.2
autoit|Dam|1.0.6
copy-directory-path|dan|1.0.2
jshint|dba|0.11.0
xml|Dot|2.5.1
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.82
vscode-macros|EXC|1.3.0
vscode-highlight|fab|1.5.1
auto-rename-tag|for|0.1.9
vscode-pull-request-github|Git|0.36.0
vscode-test-explorer|hbe|2.21.1
beautify|Hoo|1.5.0
reg|ion|1.0.3
tabsanity|jed|0.0.11
auto-comment-blocks|kev|1.0.1
node-module-intellisense|lei|1.5.0
render-crlf|med|1.5.23
vscode-language-babel|mgm|0.0.36
git-graph|mhu|1.30.0
vscode-filesize|mkx|3.1.0
vscode-apache|mrm|1.2.0
vscode-edge-devtools|ms-|1.4.3
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
cpptools|ms-|1.8.2
hexeditor|ms-|1.9.4
test-adapter-converter|ms-|0.1.5
debugger-for-edge|msj|1.0.15
color-highlight|nau|2.5.0
vscode-auto-scroll|pej|1.0.4
material-product-icons|PKi|1.1.2
vscode-phpunit|rec|2.0.76
format-html-in-php|rif|1.7.0
color-manager|roy|0.6.3
comment-divider|sta|0.4.0
code-spell-checker|str|2.1.5
tabnine-vscode|Tab|3.5.22
tauri-vscode|tau|0.1.3
vscode-ltex|val|13.1.0
vscodeintellicode|Vis|1.2.16
vscode-backup|Wes|0.0.6
php-debug|xde|1.23.0
local-history|xyz|1.8.1
json-color-token|yec|1.3.1

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
@rzhao271 This seems to be an issue with Settings Editor filtering. Please let me know if you need any info here.

**Comment by rzhao271** [comment]
I'm unable to reproduce the issue on the latest Insiders in Windows 10.

\gifPlease
