### ISSUE TITLE
Feature Suggestion: Allow using multiple tsconfig.jsons

### ISSUE THREAD

**Issue by TylorS** [Microsoft/vscode#14242]
Hello, I have a possible feature suggestion.

In the project I am working on at work we currently have our main `tsconfig.json` which points the the entry point of our application `app.ts` and our main external typings folder (for custom typings not yet placed on DefinitelyTyped).

However we also use a tsconfig-tests.json which we use to run all of our tests which live beside our source files with the ending in `.test.ts`. In each file we have to use a reference to our custom typings eg. `../../../typings/index.d.ts`. It'd be wonderful to somehow allow configuring multiple tsconfigs based on file endings.

Thanks for your time!

**Comment by roblourens** [comment]
A workaround is keeping your source files and test files in different folders, each with their own tsconfig files.

**Comment by TylorS** [comment]
Thanks for the workaround @roblourens. We'll continue to do as we have for now. Our application will be extremely large, many many files and folders, and refactoring will be quite expensive when your test folder will typically become a mirror of the source file folder.

Thank you for any work that is done here :D

**Comment by waderyan** [comment]
@TylorS thank you for opening up this issue. We want to address some of these issues around configuration. This is a JavaScript language service issue. I am moving to that repo to discuss more.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11827
