### ISSUE TITLE
Allow commenting out/uncommenting multiple cells all at once

### ISSUE THREAD

**Issue by frank-yifei-wang** [microsoft/vscode#142437]
## Pain point

In Jupyter notebook experience the users often need to turn different cells on or off (e.g. import, read/write files, different versions of the same function in debugging, etc). Currently you can manually skip cells or commenting out/uncommenting lines in a cell on a cell by cell basis, but it becomes inefficient when you need to do this for multiple cells. Alternatively you can temporarily change those cells to Markdown, but this is a messy workaround (especially when a code cell begins with #).

## Desired experience
1. Select multiple cells
2. Press Ctrl + / to comment out all lines in selected code cells (add # to the beginning of each line. No action for Markdown cells if also selected)
3. Press Ctrl + / again to uncomment (remove # in the beginning of each line in selected code cells. If no # then do nothing to that line)

Thank you for considering this feature request.

**Comment by magrella** [comment]
What's the status of this please? 

I just switched from Jupyter Notebook to VSC, I have many commented cells on a older notebook ands it is very time consuming having to uncomment each line manually without this feature:


"Press Ctrl + / again to uncomment (remove # in the beginning of each line in selected code cells. If no # then do nothing to that line)"

**Comment by Frozen105** [comment]
This would be a great feature. Struggling because of the lack of it right now.
