### ISSUE TITLE
Allow alias for code snippet

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#142469]
This is to request to add alias support for code snippet. A snippet will appear in the completion list as long as its label or its alias match the completion item.

### Background

In Java, there are some very commonly used snippets, for example: `System.out.println()`. The label of this snippet differs from different IDEs. For example:

- Eclipse: `sysout`
- IntelliJ: `sout`

In VS Code, we followed the Eclipse's convention, but we received a lot of feedbacks that users want to have snippet support for things like `sout` in IntelliJ.

It would be great if we can have alias support for snippets

**Comment by jrieken** [comment]
@jdneo Snippets to support an array of prefixes, like so

```json
"stdo": {
  "prefix":["sout", "sysout"],
  "body": "System.out.println()"
},
```

Would that solve your issue?

**Comment by jdneo** [comment]
Looks like it's for the client-side snippet. Is the `prefix` field also supported for the server-side snippet? I didn't find it in the LSP spec.

**Comment by jrieken** [comment]
> Is the prefix field also supported for the server-side snippet? I didn't find it in the LSP spec.

Sorry but I don't know much about LSP defined snippets... Is that snippets via completion item providers or is that a thing by itself

**Comment by jdneo** [comment]
Yes it's a completion item with `Snippet` as the completion item kind.

**Comment by jrieken** [comment]
But if it's completions then it is dynamic and your completion provider can do whatever it wants right?

**Comment by jdneo** [comment]
Do you mean provide both `sout` and `sysout` in the completion list?

Yes, we can do thatas a short-term solution. I'm just thinking that if it makes sense to support `alias` in LSP as well.

**Comment by jrieken** [comment]
> Do you mean provide both sout and sysout in the completion list?

If you are completion item provider can dynamically look at the current prefix and decide what snippet to return. Prefixes or aliases don't matter anymore, they are only used for static snippets but not in completions
