### ISSUE TITLE
Web: Extension host fails to initialize when certain browser extensions are installed

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#142485]
The root cause is that the init message first sent to an extension host worker might be preceded with messagse sent by various browser extensions, since they have access to the DOM and can (and will) freely call `postMessage` on iframes they find.

**Comment by joaomoreno** [comment]
Fixed by https://github.com/microsoft/vscode/commit/2e9ed4340092ab9a879d2e07b4ad8e52be31188f

**Comment by joaomoreno** [comment]
Speculation on why Stylebot breaks it:

- https://cs.github.com/ankit/stylebot/blob/4d6c30276ca4ea6ff525b392c5dd8a1e2f961196/src/editor/components/TheCodeEditor.vue#L65

**Comment by alexdima** [comment]
> Anyway the two editors could interfere, @alexdima?

Who knows 🤷 . The standalone editor doesn't ship a web worker extension host, so my best guess is that an unexpected `postMessage` was causing this.
