### ISSUE TITLE
Korean input problem 

### ISSUE THREAD

**Issue by HeeMyung** [microsoft/vscode#142474]
Issue Type: <b>Bug</b>

정확한 원인은 알 수 없으나 한국어 입력 중 IME문제인지 마지막 글자가 바로 앞에 쓰여진 글자를 덮어써버려 같은 글자가 두번 찍히게 되어 오탈자를 발생시킵니다.

예) 
입력: 요청
결과: 청청

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 3792)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (18.48GB free)|
|Process Argv|--crash-reporter-id 16260183-eaa2-4ac9-9e8e-ae3bd8e60795|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
graycat-sql-formatter|Ada|0.0.7
vscode-sqlite|ale|0.14.0
clipboard-history|Anj|1.0.7
xml|Dot|2.5.1
gitlens|eam|11.7.0
code-runner|for|0.11.6
vscode-antlr4|mik|2.2.4
vscode-language-pack-ko|MS-|1.64.6
powershell|ms-|2021.12.0
ActiveFileInStatusBar|Ros|1.0.3
xml-toolkit|SAP|1.1.0
lua|sum|2.6.3
terminal-all-in-one|yas|1.12.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vscop453:30404998
vsclayoutctrc:30425945
vsrem710cf:30416617

```

</details>

**Comment by Cruising0904** [comment]
I have the same issue I am not sure what is trigger exactly sometimes it just overwrites a letter at where cursor clicked, in Korean mode it
It's been a while I had it in windows 10 and windows 11 now too

**Comment by JacksonKearl** [comment]
cc @rebornix looks like an IME issue, translate says:

> The exact cause is unknown, but if it is an IME problem in Korean typing, the last letter will be overwritten by the letter written directly in front of it, causing the same letter to be stamped twice, causing a typography.

**Comment by CodeCrazy-ywt** [comment]
This issue is perhaps similar to #138704, although that issue is about Japanese typing.

**Comment by HeeMyung** [comment]
> 이 문제를 만들어 주셔서 감사합니다!
> 
> 그러나 설명은 영어로되어 있지 않기 때문에 우리가 그것을 작업하기가 어렵습니다. 당신이 할 수있는 경우, 영어로이 문제를 편집하시기 바랍니다. 새 주석을 추가하거나 새 문제를 만들지 말고 기존 문제를 편집하십시오.
> 
> 안타깝게도 자동 번역 서비스는 소프트웨어 문제에 대해 효과적으로 전달하는 데 필요한 기술 언어를 처리할 수 없으므로 번역을 위해 당사의 기술에 익숙한 인간 번역기를 찾는 것이 좋습니다.
> 
> 그렇지 않으면 이 문제는 번역이 필요한 것으로 표시되었으며 커뮤니티 구성원이 번역을 도울 수 있습니다.
> 
> Thanks for creating this issue!
> 
> Unfortunately, as the description is not in English, it's hard for us to work on. If possible, please edit the original issue to be in English.
> 
> In our experience, automatic translation services are not able to handle the technical language needed to effectively communicate about software issues, so we recommend finding a human translator who is familiar with our technology to help.
> 
> Otherwise, we have marked this as needing translation and a community member may be able to help out.

The English translation is below,

I don't know the exact cause of this problem, but I assume that it could be related with IME or something.
While typing in Korean, sometimes the last letter is overwritten to the right before letter after the IME completion processed, causing a letter is stamped twice.

example:
input) 요_청_
result) 청청

**Comment by alexdima** [comment]
@HeeMyung @Cruising0904 Could you please attach a screen recording of the problem and explain exactly which keys you are pressing and what should happen vs what happens? Please consider that I cannot read/write Korean. Here is the level of detail that would help me reproduce: [for example, this issue](https://github.com/microsoft/vscode/issues/138763).

**Comment by HeeMyung** [comment]
@alexdima I'v tested some case and brings some clues of this problem.

The problem only occurs when the xml file is huge (200k lines in my test case). you can see just writing some Koreans break the text and going crazy.
Here's my short recording
![bug2](https://user-images.githubusercontent.com/2211197/154288173-f92102f8-e71d-4736-aef8-28d1b05ed0f5.gif)

I assume that the ime composition buffer is not cleared well when I move the cursors while composing text. (I'm not a professional in this area so just ignore it if not this case)

Problem looks like occurs more dynamically when I'm enable some plugins. ([XML Tools](https://marketplace.visualstudio.com/items?itemName=DotJoshJohnson.xml) in this case)

**Comment by Cruising0904** [comment]
testing without vim it was fine sorry!

**Comment by alexdima** [comment]
I believe this is also fixed by e356139a1095b92e0a89be34553aeedb24aa78c0. Please verify with tomorrow's insiders.

**Comment by alexdima** [comment]
\closedWith e356139a1095b92e0a89be34553aeedb24aa78c0

**Comment by alexdima** [comment]
This bug has been fixed in the latest release of [VS Code Insiders](https://code.visualstudio.com/insiders/)!

@standard-software, you can help us out by commenting `/verified` if things are now working as expected.

If things still don't seem right, please ensure you're on version 1d618b2df1cf08f0e3ab706353f0a8f6f1424795 of Insiders (today's or later - you can use `Help: About` in the command palette to check), and leave a comment letting us know what isn't working as expected.

Happy Coding!

**Comment by HeeMyung** [comment]
After testing with the Insider version, the problem seems to have been solved well.
In addition, the problem of changing text blinking uncomfortably when IME Composing is in progress seems also disappeared.
I think it's well-modified.
/verified
