### ISSUE TITLE
Testing: MarkdownString in vscode.TestMessage is always sanitized (strips color styles)

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/vscode#142457]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: all
- OS Version: alll

Following code snippet:
```js
    const mds = new vscode.MarkdownString();
    mds.supportHtml = true;
    mds.value = `
# Title
## Title
### Title
<span style="color: red">RED</span>
`;
    mds.isTrusted = true;
    const message = new vscode.TestMessage(mds);
```

Results in:
<img width="112" alt="Screen Shot 2022-02-07 at 4 26 07 PM" src="https://user-images.githubusercontent.com/883973/152894789-2e221040-56e2-4bae-bc5b-c8c286970977.png">

Expected: RED should be red.

// @connor4312

**Comment by mjbvz** [comment]
This is by-design. We only allow a one or two css properties for security and presentation reasons

Marking as a feature request to gauge interest in broadening the subset of css that is supported

**Comment by connor4312** [comment]
While I'm not certain that we want to do this, eventually we will probably add webview-like capabilities to testing output, as we've had asks for more complex scenarios, and it's easy to imagine even more advanced ones like image diffing.
