### ISSUE TITLE
"Find" box doesn't automatically populate the selected word in Notebook editing mode

### ISSUE THREAD

**Issue by frank-yifei-wang** [microsoft/vscode#142436]
## Environment data

-   VS Code version: 1.63.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.18363
-   Python and/or Anaconda version: 3.9.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda 4.11.0
-   Jupyter server running: Local

## Steps to reproduce

Screenshot shows details:

![image](https://user-images.githubusercontent.com/42301547/152609430-e6458006-a223-43a2-a3f3-ba2f8291ef93.png)

Compare the correct behavior of editing a .py file:

![image](https://user-images.githubusercontent.com/42301547/152609167-6a8adbcc-a482-4c6b-a75a-fb86e90e5bee.png)

**Comment by greazer** [comment]
Find box features for notebooks are in the core codebase.

**Comment by rebornix** [comment]
Available now in latest VS Code.
