### ISSUE TITLE
Clicking on the gutter in notebook cells should select the line, like in a normal editor

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#142454]
![image](https://user-images.githubusercontent.com/641685/152893317-4054ad4a-5b9f-41f6-8a9c-c8d8bb42d46f.png)

Clicking as indicated should select line 3.

/cc @rebornix

**Comment by rebornix** [comment]
This should already be fixed.

**Comment by mjbvz** [comment]
Works great!

PS: going to add a code20/20 tip about clicking on line numbers :)
