### ISSUE TITLE
File Open dialog scales using primary display settings only

### ISSUE THREAD

**Issue by michmerr** [microsoft/vscode#142426]
Issue Type: <b>Bug</b>

My current configuration has a secondary 17" 1920x1080 display and a primary 15" laptop display at 3840x2160. The laptop display is scaled 200%, the 17" display 100%. 

The VSC IDE scales properly on both displays, but when I open a file or folder, that dialog always scales using the settings for the primary display. On the 17" display, it makes everything huge. It's usable, but not ideal.

I made a quick check and similar dialogs in apps like notepad and notepad++ scale properly.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.52GB (15.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
/duplicate

Caused by an upstream Electron issue. See https://github.com/microsoft/vscode/issues/85898#issuecomment-782869321
