### ISSUE TITLE
 Cannot set property 'totalFrames' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#14247]
Issue Id: <b>5d380d95-5372-17db-ef19-57457b040dd1</b><br /><br />_Versions_ <br />\- 1.6.1<br />\-  e52fb0bc87e6f5c8f144e172639891d8d8c9aa55<br />\-  602155bb781f509c7a4ddcd700b57cb9b9f5286d<br />\-  093d09e9e8a6b76ec09af97da45e242e317d8d95<br />\-  782e3ad7e504c308a5f1592ca6ae2574a13b0e73<br />_Stack_ <br />TypeError: Cannot set property 'totalFrames' of undefined<br />[/vs/workbench/parts/debug/common/debugModel.ts#L139:37 (response)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/parts/debug/common/debugModel.ts#L139:37 %28response%29)<br />[/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/common/winjs.base.raw.js#L1170:0 %28onComplete%29)<br />[/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/common/winjs.base.raw.js#L852:0 %28_notify%29)<br />[/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/common/winjs.base.raw.js#L1068:0 %28enter%29)<br />[/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/common/winjs.base.raw.js#L1036:0 %28_run%29)<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L54:5 (completeDispatch)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/parts/debug/node/v8Protocol.ts#L54:5 %28completeDispatch%29)<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L139:6 (clb)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/parts/debug/node/v8Protocol.ts#L139:6 %28clb%29)<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L107:11 (dispatch)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/parts/debug/node/v8Protocol.ts#L107:11 %28dispatch%29)<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L44:8 (handleData)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/workbench/parts/debug/node/v8Protocol.ts#L44:8 %28handleData%29)<br />    at emitOne (events.js:96:13)<br />    at Socket.emit (events.js:188:7)<br />

**Comment by isidorn** [comment]
Fixes a long time ago, now there a null guard there
