### ISSUE TITLE
Output view dropdown scrollbar UI is not clickable/usable (regression)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#142421]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:Version: 1.64.0 (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
or
Version: 1.65.0-insider (user setup)
Commit: 97c1e76d668d23d568044feb31083407f4c4b1ed
Date: 2022-02-07T08:55:59.620Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce: View the Output view, expand the dropdown after it's filled with enough options (and/or reduce the height of the Output UI area) and try to drag/scroll the scrollbar on the right. See the screenshot:
![image](https://user-images.githubusercontent.com/19859882/152836871-4249ef60-a5b3-4e84-83c0-3168641703b9.png)

Bug: The scrollbar is not clickable or draggable. The workaround is to use the keyboard to scroll through the list.

**Comment by sbatten** [comment]
seems to be caused by f4710a198fbc1b727a82f3ede4a718522182394c

**Comment by meganrogge** [comment]
![Recording 2022-02-10 at 10 57 00](https://user-images.githubusercontent.com/29464607/153457322-4844e7b5-6add-4d20-b4f2-59de20f316f4.gif)

**Comment by sbatten** [comment]
@meganrogge I think that's macos behavior, this bug was specific to windows presentation of select boxes

**Comment by sbatten** [comment]
since @rzhao271 made this change, I have verified
