### ISSUE TITLE
vs code doesnt work?

### ISSUE THREAD

**Issue by JuliScarlata** [microsoft/vscode#142443]
I've had problems with vs code several times since i started using its cloud version for my cs50 classes. At first it was mostly annoying stuff like really consistent reloads or not responding for a few minutes, then problems when it came to save my work that made me lose some of it. But most recently, its become even worse. On top of all the issues stablished before, the page wouldnt respond to any commands i gave it, like running my program or clearing the terminal window. It didnt do absolutely anything, and i started having serious problems when i tried to test my test or even saving it. I am certain the issue is not because of bad connection or anything like that because my brother works with other IDEs and has no problem of the sort at all.

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.43
Embedder: codespaces

**Comment by meganrogge** [comment]
likely caused by an extension. will need your settings and other relevant info

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" terminal
