### ISSUE TITLE
Extension readme not rendered if it contains indented code block

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode#142445]
Does this issue occur when all extensions are disabled?: Not sure because I'm testing an extension (and I don't want to lose all my open windows).

- VS Code Version: 1.64.0
- OS Version: MacOS 11.6.2

Steps to Reproduce:

1. Create an extension.
2. In the `README.md` put an indented code block (4 spaces).
3. Build & install it from vsix.

For some reason if the `README.md` contains a code block made by indenting 4 spaces, the entire readme won't be shown! The "Details" tab of the extension info page is just blank. If you use the triple backtick method it works fine. You can imagine how long it took me to figure this out!

**Comment by Timmmm** [comment]
That was fast! Thanks!

**Comment by tanhakabir** [comment]
Verified by verifying Hourly Beep extension rendered its README
