### ISSUE TITLE
Initial build task launch takes a long time to launch

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#142413]
For this tasks.json https://github.com/xtermjs/xterm.js/blob/master/.vscode/tasks.json

I waited a bit after startup to ensure everything settled down, the lines represent:

- Blue: Status bar item appears
- Red: Status bar item goes away (800ms later)
- Green: Terminals are created (2 seconds later)

![image](https://user-images.githubusercontent.com/2193314/152821894-ecac432f-f723-4445-b1ac-7099b3259979.png)

Profile:

[Profile-20220207T074700.zip](https://github.com/microsoft/vscode/files/8016656/Profile-20220207T074700.zip)

**Comment by alexr00** [comment]
Faster resolving of `dependsOn` tasks requires two things:
- The `dependsOn` task must be configured in the workspace (tasks.json or workspace file). ✅ The build task in https://github.com/xtermjs/xterm.js/blob/master/.vscode/tasks.json has this.
- In the task configuration there must be a `label` set. ❌ The build task in https://github.com/xtermjs/xterm.js/blob/master/.vscode/tasks.json does not have this and it should be added to take advantage of the faster resolving.

**Comment by Tyriar** [comment]
Much faster when label is set 👍

@alexr00 anyway to avoid needing the label? Most people won't end up getting the performance benefit because of that.
