### ISSUE TITLE
Prior cell output gets momentarily rendered on top of cell below when scrolling up.

### ISSUE THREAD

**Issue by curzona** [microsoft/vscode#142438]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When scrolling up, some prior cell output gets rendered on top of the cell below and the scroll bar jumps up and then back down. This happens at the moment when the prior cell output is not visible and then becomes visible. This happens for matplotlib cell output but not text output.

https://user-images.githubusercontent.com/1147498/152693767-ce531848-3678-4d07-8883-d02f98f717ad.mp4

### VS Code Version

Version: 1.64.0 (user setup) Commit: 5554b12acf27056905806867f251c859323ff7e9 Date: 2022-02-03T04:22:20.678Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.19043

### Jupyter Extension Version

Jupyter v2022.1.1001775990

### Coding Language and Runtime Version

Python 3.9.10 64-bit

**Comment by rebornix** [comment]
This is now fixed via our off-canvas cell rendering optimization.
