### ISSUE TITLE
crashed 

### ISSUE THREAD

**Issue by MadonaAbbott** [microsoft/vscode#142467]
Issue Type: <b>Bug</b>

Vscode crashed. It won't let me commit

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3250U with Radeon Graphics          (4 x 2595)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.92GB (1.70GB free)|
|Process Argv|--crash-reporter-id 6a669b16-f59b-4201-a179-ebab9a9f2986|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.7.0
prettier-vscode|esb|9.2.0
LiveServer|rit|5.7.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vscop453:30404998
vsrem710:30416614

```

</details>

**Comment by hello-smile6** [comment]
> Issue Type: Bug
> 
> Vscode crashed. It won't let me commit
> 
> VS Code version: Code 1.64.0 ([5554b12](https://github.com/microsoft/vscode/commit/5554b12acf27056905806867f251c859323ff7e9), 2022-02-03T04:22:20.678Z) OS version: Windows_NT x64 10.0.18363 Restricted Mode: No
> 
> System Info
> Extensions (3)
> A/B Experiments

Try disabling GitLens and trying again. That might fix it. What is the error?

**Comment by lszomoru** [comment]
@MadonaAbbott, are you able to reproduce the crash when starting VSCode using the `--disable-extensions` flag?
