### ISSUE TITLE
Search: keep .gitignore exclusions when searching with "files to include"

### ISSUE THREAD

**Issue by jacobweber** [microsoft/vscode#142428]
Say my workspace looks like this:
```
client
    build
.gitignore
    # contains client/build/
```

and I have `search.useIgnoreFiles` and `search.useParentIgnoreFiles` turned on, and the "Use exclude settings and ignore files" button in Search selected.

Normally, if I do a search, it will exclude files from `client/build`, as expected.

But if I do a search where I set "Files to include" to `./client`, it will ignore the ignore files, and include results from `client/build`.

Usually I'd prefer to maintain the same exclusion rules, even when searching in a subdirectory. It does seem to respect the `search.exclude` rules, just not the ones from `.gitignore`.

```

Version: 1.64.0 (Universal)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:20:17.224Z (4 days ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.3.0
```

**Comment by roblourens** [comment]
searching with `client` instead of `./client` will probably work for you. Setting `search.useParentIgnoreFiles` would probably also give the behavior you want. Using `./` changes the "root" of the search to that folder. That might not be what is typically desired so I'll leave this open.

**Comment by jacobweberbowery** [comment]
@roblourens Thanks, but `client` still returns results in the excluded folders, even with `search.useParentIgnoreFiles` on.

**Comment by jacobweber** [comment]
@roblourens Thanks, but client still returns results in the excluded folders, even with search.useParentIgnoreFiles on.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/26574
