### ISSUE TITLE
Tab completion for unicode

### ISSUE THREAD

**Issue by ryan-j-h** [microsoft/vscode#142442]
In Jupyter Notebooks, you can write unicode characters with a tab completion command. You can write \alpha and press the Tab key to create the symbol α. Is there a way to do this when using pylance/VSCode?

**Comment by greazer** [comment]
This is a bigger issue to fix than just in notebooks. May be bigger than PyLance too.

**Comment by moble** [comment]
This works in Julia files when using the Julia extension.  That might be easy to copy over.  The lack of this feature is enough to make me go back to emacs when I'm writing python.
