### ISSUE TITLE
Python debug can not start on VSCode 1.64.0

### ISSUE THREAD

**Issue by Honghe** [microsoft/vscode#142488]
Issue Type: <b>Bug</b>

Click `Debug Python File` icon on top-right.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:23:11.224Z)
OS version: Linux x64 5.4.0-42-generic
Restricted Mode: No
Remote OS version: Linux x64 5.11.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.55GB (0.83GB free)|
|Process Argv|--unity-launch --crash-reporter-id d1342c61-ab2f-444c-8817-05c0593ae50f|
|Screen Reader|yes|
|VM|67%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: 172.28.52.19|
|OS|Linux x64 5.11.0-46-generic|
|CPUs|Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz (12 x 3500)|
|Memory (System)|62.50GB (53.16GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
markmap-vscode|ger|0.0.10
copilot|Git|1.7.4924
better-cpp-syntax|jef|1.15.11
rainbow-csv|mec|2.0.0
git-graph|mhu|1.30.0
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.1
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
hexeditor|ms-|1.9.4
live-server|ms-|0.2.12
remote-x11-ssh|spa|1.5.0
asymptote|sup|1.2.0
vscodeintellicode|Vis|1.2.16

(1 theme extensions excluded)

</details>

**Comment by iKeepo** [comment]
same problem, can't debug using python from conda, but python from usr/bin which marked Global work fine.
reinstall 1.59.1 to continue my work
