### ISSUE TITLE
Python debugging no longer works after update

### ISSUE THREAD

**Issue by SuschNL** [microsoft/vscode#142404]
Updated to version 1.64.0 and now "Debug Python File" no longer works. Clicking on "Run Python File" works as expected, but clicking on "Debug Python File" does nothing other than pop up the debug control bar (continue, set over, step into, restart, stop) for about 2 seconds then it disappears.

Everything worked fine prior to update.

Version: 1.64.0 (user setup)
Date: 2022-02-03T04:22:20.678Z (4 days ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363

(NOTE: would be nice to be able to cut/paste the above info from the "About" window and not have to retype...)

**Comment by SuschNL** [comment]
Downgrading the Python extension fixed the issue. Thanks!

I've turned off auto updates to try and alleviate this confusion (multiple items updating at once) in the future.

**Comment by rfernand2** [comment]
That fixed it for me also.  Use the dropdown arrow on the "Uninstall" button on the Python Extension for VS Code page to select a previous version to install.
