### ISSUE TITLE
Pressing End key twice should move to end of line

### ISSUE THREAD

**Issue by hickford** [Microsoft/vscode#1424]
Open a document with a long line (example attached), so that it wraps. 
1. Press the End key. The cursor should move to the end of the screen line. This works correctly.
2. Press the End key again. Expected: The cursor should move to the end of the physical line. What actually happens: nothing.

This works correctly in other editors: Sublime Text and Notepad++.

Similarly, pressing the Home key twice should always move the cursor to the start of physical line.

[alice.txt](https://github.com/Microsoft/vscode/files/65536/alice.txt)

**Comment by hickford** [comment]
Atom has this bug too https://github.com/atom/atom/issues/10112

**Comment by hickford** [comment]
Visual Studio the IDE has this bug too, but I don't know where to report it

**Comment by bpasero** [comment]
@alexandrudima fyi

**Comment by kumarharsh** [comment]
This is a very painful bug while working with multiple cursors, and there is no way of going to the real end of line, and any transformations I do, like deleting a word in 100 lines, or adding an ID field in a bunch of `<FormattedMessage...>` elements, mostly creates side-effects which break the whole file.

**Comment by alexandrudima** [comment]
This has been implemented since quite some time:

![kapture 2017-10-24 at 15 24 29](https://user-images.githubusercontent.com/5047891/31945498-a204448a-b8cf-11e7-84f1-7448b1d6647f.gif)

**Comment by hickford** [comment]
Brilliant, thanks.

Works for me in version 1.17.2

**Comment by hickford** [comment]
One last word wrap bug https://github.com/Microsoft/vscode/issues/36839

**Comment by kumarharsh** [comment]
Yeah, I noticed this got fixed a while back (I think 1.12 or so). There were apparently a bunch of issues on GH regarding this (it's so hard to keep track of issues I participated in!!), forgot to post the 🎉 here.

# So, 🎉!!!

**Comment by hickford** [comment]
> Visual Studio the IDE has this bug too

If anyone would like this bug fixed in Visual Studio too, please vote for https://developercommunity.visualstudio.com/content/problem/138274/pressing-end-key-twice-should-move-cursor-to-end-o.html
