### ISSUE TITLE
jupyter notebook cell pending indicator missing

### ISSUE THREAD

**Issue by FAQinghere** [microsoft/vscode#142466]
Issue Type: <b>Bug</b>

When a Jupyter notebook cell is pending the completion of other cells, the UI used to show a pending indicator in the bottom left corner of the cell. This is visible in screen shots in the online documentation as well. However, I am no longer seeing the indicator.

To replicate: 
- make cell A: a long running cell (eg. sleep 5 seconds)
- make cell B
- click run on cell A
- click run on cell B

Expect:
- while waiting, cell B shows a pending indicator

Seen
- no indication that cell B is waiting / will run

Extension version: 2022.1.1001775990
VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (32 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.92GB (111.41GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/mnt/c/Users/intro/Box%20Sync/OMSCS/ML/a1 --remote=wsl+Ubuntu-20.04 --crash-reporter-id 6a615412-1ff4-4e58-a8a3-08e8de215d54|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor (32 x 3500)|
|Memory (System)|62.77GB (57.63GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vs360cf:30404996
vsrem710cf:30416617

```

</details>

**Comment by roblourens** [comment]
Will be fixed in tomorrow's insiders, and next week's stable release
