### ISSUE TITLE
Downlaod patch for proxy-setting

### ISSUE THREAD

**Issue by relgaard** [microsoft/vscode#142410]
Issue Type: <b>Bug</b>

With reference to the sloved bug: #142324
I need an alternative way for upgrading VS Code - simply because VS Code can't connect to the network and check for updates.

Could you please provide a endpoint for manually downloading and installing the update?

Thanks a lot 

Br Robert

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (1.49GB free)|
|Process Argv|--crash-reporter-id fea21742-3685-4326-ae39-b2e5d85ea516|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azureappservice|ms-|0.18.0
csharp|ms-|1.24.0
data-workspace-vscode|ms-|0.1.1
mssql|ms-|1.12.0
sql-database-projects-vscode|ms-|0.14.1
azure-account|ms-|0.9.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30433058
pythonvs932:30410667
vscop453:30404998
vsrem710cf:30416617

```

</details>

We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
Links are at the top of https://code.visualstudio.com/updates/v1_64

**Comment by joaomoreno** [comment]
https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions
