### ISSUE TITLE
Typescript error showing on js file with extensions disabled

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [microsoft/vscode#142459]
Issue Type: <b>Bug</b>

I found a weird behaviour where typescript plugin is triggering an error on stable release, where the same snippet on a clean insiders build it does not trigger the error. I have disabled the extensions and the error persists.

Error: 
```
Operator '+=' cannot be applied to types 'number' and 'string | number'. ts(2365) 
```

Example code:
```javascript
const fs = require('fs');

const vector = {forward: 0, depth: 0};

fs.readFileSync(`${__dirname}/input.txt`).toString().split('\n')
.map(directions => directions.split(' ').map((v, i) => i % 2 !== 0 ? parseInt(v, 10) : v))
.forEach(instruction => {
    switch (instruction[0]) {
        case 'forward': vector.forward += instruction[1];   break;
        case 'down':    vector.depth += instruction[1];     break;
        case 'up':      vector.depth -= instruction[1];     break;
        default: break;
    }
})

console.log(vector.forward   * vector.depth);
```

VS Code version: Code 1.64.0 (Universal) (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:20:17.224Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (26.84GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 6d073b49-7d03-4343-a1a1-c977e1822595|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
testflightcf:30433671
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vscop940:30404999
vsrem710cf:30416617
vscscmwlcmc:30433760

```

</details>

**Comment by mjbvz** [comment]
So this is working the current insiders build? If so, then either this was already fixed or it was caused by one of your extension/settings

**Comment by tiagomsmagalhaes** [comment]
After posting this issue, I tried to uninstall vscode for the 3rd time and remove any associated data, and I might have cleaned it all, because I reinstalled it and then no more issue.

on the first uninstall I might have not delete some leftover files or configs.

Thanks nonetheless
