### ISSUE TITLE
Vscode Terminal still black screen 

### ISSUE THREAD

**Issue by qaeqwg** [microsoft/vscode#142472]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest version(1.64)
- OS Version: windows 10

I have used vscode for 2 years and I have never see like this issue.
I am using wsl2 with window. Before the bug, the default terminal of vscode was wsl2, and I turned off the hyper -v option to use linux as vmware without using wsl2 for a while.
After that, even if I turned on the hyper -v option and turned on vscode again, vscode's terminal did not work.
The same is true if you change the default terminal to a shell other than wsl2.
The problem is still there even if you connect to vscode through the code command in wsl2
No text is displayed in the terminal and there is no response
how can I bug this?

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by qaeqwg** [comment]
Sorry for the late reply
Several files were deleted while updating Windows, and at the same time, the terminal problem of vscode was resolved.
Maybe there is a problem with the path of vscode or some file itself is broken.
thank you for the reply
