### ISSUE TITLE
Horizontal scrollbar not working when visibility is set to "auto" 

### ISSUE THREAD

**Issue by jakobhu** [microsoft/vscode#142492]
Does this issue occur when all extensions are disabled?: Yes/No

Yes

- VS Code Version:
Version: 1.64.0
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:23:11.224Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-99-generic

- OS Version:
OS: Linux x64 5.4.0-99-generic
Ubuntu 20.04.3 LTS (focal)

Steps to Reproduce:

1. launch "code --disable-extensions"
2. add plenty of text  in the editor - such that the horizontal and vertical scrollbars appear.
3. use the horizontal scrollbar at the bottom of the editor - using mouse left click, and drag right/left - ~~observe that this wrongly affects vertical scrollbar.~~ observe that text gets selected instead of horizontal scrolling 

- if the setting Editor > Scrollbar > : Horizontal is changed from "auto" to "visible" - the problem goes away, at the expense of an ever present horizontal scrollbar.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/124895
