### ISSUE TITLE
`TextSearchProvider` requires that documents are open to display results correctly

### ISSUE THREAD

**Issue by isc-bsaviano** [microsoft/vscode#142422]
While investigating https://github.com/intersystems-community/vscode-objectscript/issues/849 I noticed that the proposed `TextSearchProvider` requires that files be open to display results correctly. This causes significant performance issues for our InterSystems Language Server extension because it needs to synchronously parse hundreds of files that are never shown to the user in an editor tab. The `TextSearchResult` type contains all of the information that VS Code needs to show in the UI and open the document if the user clicks on it. I think it's a bug that it also requires that the document be opened. 

This is what the UI looks like if the correct information is reported via the progress callback but the documents **aren't** open:

<img width="294" alt="Screen Shot 2022-02-07 at 12 30 35 PM" src="https://user-images.githubusercontent.com/44776135/152841045-e70aecdf-fbc9-4dde-9ee8-d952753ee71f.png">

And this is what the UI looks like if the correct information is reported via the progress callback but the documents **are** open:

<img width="298" alt="Screen Shot 2022-02-07 at 12 31 53 PM" src="https://user-images.githubusercontent.com/44776135/152841160-d63f90f5-b2f5-4039-88bb-adc1f6ef5c7d.png">

**Comment by gjsjohnmurray** [comment]
@roblourens per #59921 I think you own the TextSearchProvider API.

**Comment by roblourens** [comment]
This shouldn't be the case, I don't see it in our usages of the search provider. Can you give me steps to repro it with your extension, or a simpler code snippet that reproes the issue?

**Comment by isc-bsaviano** [comment]
@roblourens Here are the steps to reproduce this using a modified version of the MemFS extension that I've attached to this message:

- Download and install my modified MemFS extension and edit your `argv.json` to include this line:
```json
"enable-proposed-api": ["isc-bsaviano.vscode-memfs"]
```
- Close VS Code and open a new window with no workspace open.
- Use the MemFS commands to create a new workspace and fill it with files. (`MemFS: Setup Workspace` and `MemFS: Create Files`)
- Open the search view and search for "foo" with case-sensitive search ***disabled***. This will execute the search without opening the document. Observe that the UI is incomplete and that you can't click to open the document.
- Now search for "foo" with case-sensitive search ***enabled***. This will execute the search and open the document. Observe the difference in UI behavior. 

[vscode-memfs-0.0.3.vsix.zip](https://github.com/microsoft/vscode/files/8018250/vscode-memfs-0.0.3.vsix.zip)

**Comment by roblourens** [comment]
Also you realize that this is only proposed API, will not be stabilized soon, and can't be used in a published extension, right?

**Comment by roblourens** [comment]
I can repro the issue with your sample, thanks

**Comment by isc-bsaviano** [comment]
Yes, I understand that. I figured I would still report it to see if the issue was caused by our extension or not.

**Comment by roblourens** [comment]
It looks like your extension is only reporting TextSearchContext objects. This is just to add surrounding context to matches. They don't show up in the sidebar, only the Search Editor. Make sure you return `TextSearchMatch` objects (with the uri, ranges, preview properties)

**Comment by isc-bsaviano** [comment]
Thanks, that fixes the problem with the MemFS example
