### ISSUE TITLE
VSCode cannot detect node: protocol modules

### ISSUE THREAD

**Issue by paolomainardi** [microsoft/vscode#142452]
Does this issue occur when all extensions are disabled?: Yes

Whenever I import a node built-in module using the "node:" format I get an error saying that typescript cannot find the module.

```
Version: 1.64.0
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:23:11.224Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.15.21-1-lts
```

**Steps to Reproduce**:

Create a new Typescript (nodejs) file.
require the "node:fs" module (or any other "node:" module)

Related to this one: https://github.com/microsoft/vscode/issues/123968

**Comment by mjbvz** [comment]
As mentioned on the related issue, this is actually a Typescript problem. See the links on https://github.com/microsoft/vscode/issues/123968#issuecomment-841900646 or file an issue against TS if you don't believe that covers what you are seeing
