### ISSUE TITLE
A right mouse button erro

### ISSUE THREAD

**Issue by csu-lf** [microsoft/vscode#142409]
Issue Type: <b>Bug</b>

if i click right button, sometimes it will happens as my picture. i hope there would be some space between my mouse and that menu.
<img src="https://blog.csu-lf.cn/wp-content/uploads/2022/02/2022-02-07_23-09.png">

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:23:11.224Z)
OS version: Linux x64 5.13.0-27-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|15.38GB (2.68GB free)|
|Process Argv|--unity-launch --crash-reporter-id 28cb01c4-0723-423a-9ef7-6b6e3651d96f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
Doxygen|bbe|1.0.0
bracket-pair-colorizer|Coe|1.0.62
doxdocgen|csc|1.3.2
c-cpp-compile-run|dan|1.0.15
gitlens|eam|11.7.0
vsc-material-theme-icons|equ|2.2.1
code-runner|for|0.11.6
todo-tree|Gru|0.0.215
beautify|Hoo|1.5.0
better-cpp-syntax|jef|1.15.11
vscode-gutter-preview|kis|0.30.0
vscode-leetcode|Lee|0.18.0
vscode-docker|ms-|1.19.0
vscode-language-pack-zh-hans|MS-|1.64.6
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.2
cpptools-extension-pack|ms-|1.1.0
hexeditor|ms-|1.9.4
clang-tidy|not|0.5.1
vscode-hexdump|sle|1.8.1
tabnine-vscode|Tab|3.5.21
cmake|twx|0.0.17
txt-syntax|xsh|0.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vscop453:30404998
vsrem710:30416614

```

</details>

**Comment by sbatten** [comment]
duplicate #113175
