### ISSUE TITLE
Show XFAIL tests as different from standard 'passed' tests

### ISSUE THREAD

**Issue by gitgovdoc** [microsoft/vscode#142407]
When using the "Testing" panel in VSCode with pytest, the visual indicator for tests that pass is no different from the visual indicator for tests that have been marked as expected to fail (and are functionally being skipped). 

Whether passing or marked XFAIL, the test is shown in the Testing panel as having a small green circle with a green checkmark in the center.

Instead, tests marked with XFAIL should have a different visual cue to show that they have not actually passed and instead are being skipped by the test suite.

**Comment by gjsjohnmurray** [comment]
I assume a [testing extension](https://code.visualstudio.com/api/extension-guides/testing) is providing this. I think it's the responsibility of the extension to report skipped tests differently from passed tests.

**Comment by gitgovdoc** [comment]
Thanks, you're right. Closing the issue.
