### ISSUE TITLE
GVFS: can't open file

### ISSUE THREAD

**Issue by dima424658** [microsoft/vscode#142481]
Does this issue occur when all extensions are disabled?: Yes
Tried to reset the settings by deleting config folders

- VS Code Version: 1.64
- OS Version: Arch Linux stable

Steps to Reproduce:
1. Connect to FTP server using Nautilus (GVFS)
2. Try to open any file on the server

Verbose logs:
`[INFO:CONSOLE(578)] "%cTRACE color: #888 [text file model] resolve() - enter file:///run/user/1000/gvfs/ftps:host=31.31.196.58/mail.log", source: vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js (578)
[INFO:CONSOLE(578)] "%cTRACE color: #888 [text file model] resolveFromFile() file:///run/user/1000/gvfs/ftps:host=31.31.196.58/mail.log", source: vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js (578)
[INFO:CONSOLE(578)] "%cTRACE color: #888 [text file model] dispose() file:///run/user/1000/gvfs/ftps:host=31.31.196.58/mail.log", source: vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js (578)
[INFO:CONSOLE(578)] "%cTRACE color: #888 [backup tracker] discarding backup file:///run/user/1000/gvfs/ftps:host=31.31.196.58/mail.log ", source: vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js (578)
[INFO:CONSOLE(578)] "%c  ERR color: #f33 Error: Не удалось считать файл "/run/user/1000/gvfs/ftps:host=31.31.196.58/mail.log" (Unknown (FileSystemError): Произошла неизвестная ошибка. Подробные сведения см. в журнале.)", source: vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js (578)
[INFO:CONSOLE(788)] "Невозможно открыть "mail.log": Не удалось считать файл "/run/user/1000/gvfs/ftps:host=31.31.196.58/mail.log" (Unknown (FileSystemError): Произошла неизвестная ошибка. Подробные сведения см. в журнале.).", source: vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js (788)`

Tried to reset settings, reinstall GVFS(gio) library but nothing helps
Code 1.63 works fine, there is no ftp issues

**Comment by peon501** [comment]
#142475 we are in the same boat, I also have problems with GVFS after the update of vs code.

**Comment by bpasero** [comment]
Can someone distill steps for me to set this up step by step? I am not so familiar with how to do that.

**Comment by peon501** [comment]
![image](https://user-images.githubusercontent.com/1125765/152947414-1905ca1d-392a-4bce-8ebe-3a31e2235559.png)
GUI way would be:
"+Other Locations"
"Connect to server" and then open that folder in vscode

**Comment by bpasero** [comment]
Thanks a lot, I understand the issue and it will be targeted as a recovery fix for this week.
