### ISSUE TITLE
vscode marketplace query not working

### ISSUE THREAD

**Issue by kseikyo** [microsoft/vscode#142401]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.64.0
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T22:59:58.092Z
Electron: 13.6.8
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.40-electron.0
OS: Linux x64 5.16.5-zen1-1-zen

Steps to Reproduce:
1. Open vs code
2. Click on extensions icon (or use shortcut)
3. Type anything on the extension query

Do I use a VPN/Proxy?
- Yes, and the issue still persists when disabling it.

Can I access the marketplace website?
- Yes, it loads and queries extensions.

![image](https://user-images.githubusercontent.com/29212286/152802466-5c43c84d-1727-4c6c-958c-3fb578c27bfb.png)
![image](https://user-images.githubusercontent.com/29212286/152802538-d93a0528-0d5e-4b76-8773-233e2dbd6730.png)

**Comment by gjsjohnmurray** [comment]
Maybe related to #142201

**Comment by chrmarti** [comment]
This is different from https://github.com/microsoft/vscode/issues/142201 because it occurs using Chromium's network stack. 503 suggests a problem with the server.
