### ISSUE TITLE
Windows 7: title does not change when opening another one from File > Recent

### ISSUE THREAD

**Issue by Handsome2734** [Microsoft/vscode#14244]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: donjayamanne.python-0.5.0, liuji-jim.vue-0.1.3

Steps to Reproduce:

1.Open 'Folder_1' in code, and edit 'File_1'.
2.Open 'Folder_2' in File->Open Recent.
3.As the workspace finished loading, the window's title is still 'File_1 - Forder_1 - Visual Studio Code', rather than 'File_x - Folder_2 - Visual Studio Code'

**Comment by bpasero** [comment]
@Handsome2734 is this reproducible everytime you do this?

**Comment by Handsome2734** [comment]
@bpasero yes, it's reproducible.
This is a screen capture of mine.
https://s21.postimg.org/jy03hpvjr/screen_capture.gif

**Comment by bpasero** [comment]
@Handsome2734 I wonder if this is related to opening workspaces from E: drive, does it reproduce with folders from C: drive?

**Comment by Handsome2734** [comment]
@bpasero it's the same with C: drive.
The title will not change, unless I switch to another program window(e.g. File Explore) and switch back, or I minize the Code and return.

**Comment by bpasero** [comment]
@Handsome2734 but that sounds awfully like a bug on Windows then and not a bug with VS Code. We are setting the title, it is just windows refuses to show it for some odd reason.

**Comment by bpasero** [comment]
@Handsome2734 did some cleanup/refactoring in this area (window title). Care to see if you can still reproduce this using our insider build?

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by Handsome2734** [comment]
@bpasero 
I'd like to have a try. Do I need to uninstall the current release version?

**Comment by bpasero** [comment]
@Handsome2734 no, you can install insiders side by side.

**Comment by Handsome2734** [comment]
@bpasero 
I've tried the insider build, but it still fails to work properly.  
![sorry man](http://i.giphy.com/l0Exq6f5yaMeb7Uic.gif)

**Comment by bpasero** [comment]
Thanks for trying :)
