### ISSUE TITLE
[vscode-extension] `vscode.languages.registerHoverProvider` multiple languages not working

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/vscode#142494]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.64.0 (Universal)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:20:17.224Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0

Steps to Reproduce:
here is my code 
```js
vscode.languages.registerHoverProvider(
    [
      "javascript",  // only this works
      "typescript",
      "javascriptreact",
      "typescriptreact",
      "json",
      "jsonc",
    ],
    {
      async provideHover(document, position) {
// ....

} 
})
```

1. fork this repo https://github.com/HomyeeKing/vscode-plugin-preview
2. `f5` enter debug mode
3.  create a ts \ tsx \ jsx \js  file and copy follow code:
 ```
const img = "https://miro.medium.com/max/1400/1*6ahbWjp_g9hqhaTDSJOL1Q.png"; // whole url
const img1 = "//miro.medium.com/max/1400/1*6ahbWjp_g9hqhaTDSJOL1Q.png"; // omit protocol, pretend it's https by default
const img2 =
  "https://img0.baidu.com/it/u=3486467821,3996728349&fm=253&fmt=auto&app=138&f=JPEG?w=500&h=500"; // infer from response header
```

4. if you can see the picture, then it works, but only works in js file for now

**Comment by jrieken** [comment]
This works for me using a provider as shown below. I suspect that your provider isn't always returning a result and therefore no hover is shown. Please try with a simple/static provider as below

```js
    vscode.languages.registerHoverProvider([
        'fooLang',
        "javascript",  // only this works
        "typescript",
        "javascriptreact",
        "typescriptreact",
        "json",
        "jsonc",
    ], {
        provideHover() {
            const markdownString = new vscode.MarkdownString();
            markdownString.appendText("Hello: https://github.com/microsoft/vscode/issues/142494")
            return new vscode.Hover(markdownString);
        }
    })

```
