### ISSUE TITLE
Resizing Terminal

### ISSUE THREAD

**Issue by Andlet95** [microsoft/vscode#142483]
Issue Type: <b>Feature Request</b>

When I increase the size of the terminal, the information I want to see is kept hidden, while an increasingly larger blank space is introduced. If I scroll up because I was looking for something further up, I will still be presented with the blank space if anything new happens in the terminal until it has been filled by text.
Would it be possible to keep the text at the bottom, and just show the older text in the terminal when resizing?

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" terminal
