### ISSUE TITLE
Forgetting parentheses when calling a method in a <script> doesn't trigger a problem

### ISSUE THREAD

**Issue by sukiletxe** [microsoft/vscode#142598]
Issue Type: <b>Bug</b>

Related to #119035 (which got closed without fixing because of lack of enough upvotes). Steps:
1. Create a html file, put a doctype declaration, and insert this:
```
<script type="text/javascript">
var date = new Date();
if (date.getMonth == 1) {
 document.write("February");
} else {
 document.write("Not February")
}
</script>
```

This would trigger no problem (go to beginning of file, press F8, nothing happens). But because I forgot the parenthesis, an unset attribute is accessed, which yields undefined, which makes the condition false, "not February" is output in the document.

I would expect that a problem would be triggered, especially when hovering over getMonth correctly deduces that it is a method.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (8.16GB free)|
|Process Argv|C:\\Users\\sukil\\OneDrive\\unibertsitatea\\Informatica\\examenes.html --crash-reporter-id 2e56a695-05ce-40ed-88c1-2cfc5995aa83|
|Screen Reader|yes|
|VM|80%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30429732
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vscop341:30404997
vsrem710:30416614

```

</details>

**Comment by armgp** [comment]
Hi, First-time contributor!... Can I give it a try?

**Comment by aeschli** [comment]
In the HTML language service we don't emit diagnostics. The main reason is that we only know the code in the same file, we don't know the content of the imported code. 
Because of that we would emit many wrong errors and confuse users.

There are currently no plans to work on that (it's also very hard, so not the best issue for a first time contributor..., but thanks :-))
