### ISSUE TITLE
Typescript go to definition no longer working

### ISSUE THREAD

**Issue by dmcd** [microsoft/vscode#142564]
Issue Type: <b>Bug</b>

Load a typescript project, command click or right click on a type name, the go to definition option is no longer available.

VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:26:08.977Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id 9b1dda95-bb03-4b84-aa39-6cf6657594ae|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
prettier-vscode|esb|9.2.0
auto-rename-tag|for|0.1.10
copilot|Git|1.7.4924
intellij-idea-keybindings|k--|1.5.0
vscode-open-in-github|sys|1.16.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30435083
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vscop940:30404999
vsrem710:30416614

```

</details>

**Comment by mjbvz** [comment]
Please share a minimal code example that demonstrates the issue

**Comment by dmcd** [comment]
https://user-images.githubusercontent.com/4025574/153108862-b6b298ae-2b1b-4415-a49e-0d1474062f62.mov

Sorry, here's a screen recording, as you can see there is no option to go to definition on the ListingStatus type, option click or command click doesn't navigate either. 

I notice that the Typescript version is not displayed in the window I'm using, its set to auto detect.

**Comment by dmcd** [comment]
hi @mjbvz,

I've spent some more time trying to figure out why this is happening for me but haven't had any luck yet. Goto definition is still missing from the context menu. 

This is what I've tried:

- disabling all extensions
- clearing all my custom vscode settings
- Using a simple project with `npx create-next-app -e with-typescript`
- Switching from [asdf](https://github.com/asdf-vm/asdf) managed node to [volta.sh](https://volta.sh/) managed node
- Downgrading to vscode 1.62

It was working fine a few weeks ago 🤔

**Comment by mjbvz** [comment]
Can you please share a project that demonstrates this problem?

Also make sure you have not disabled the built-in typescript extension:

1. In the extensions view
2. Search `@builtin typescript`
3. Make sure `TypeScript and JavaScript Language Features` is enabled

**Comment by dmcd** [comment]
Oh thank you so such!! I can't remember disabling it but the builtin typescript extension was disabled.

Its all good now :)
