### ISSUE TITLE
Error Viewing Web View

### ISSUE THREAD

**Issue by nisarg0606** [microsoft/vscode#142596]
Error loading webview: Error: Could not register service workers: NotSupportedError: Failed to register a ServiceWorker for scope ('https://604d05e0-3f14-4e81-b014-37527232e9b7.vscode-webview.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/contrib/webview/browser/pre/') with script ('https://604d05e0-3f14-4e81-b014-37527232e9b7.vscode-webview.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?id=805b4f6a-c8c4-4054-a4c2-e2989e08c609&swVersion=2&extensionId=vscode.markdown-language-features&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-webview.net&parentOrigin=https%3A%2F%2Fgithub.dev'): The user denied permission to use Service Worker..

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version, platform and simple repro steps.

**Comment by dannyfritz** [comment]
I updated `visual-studio-code` on brew today and now see this error any time I try to preview a Markdown file.

I included the extensions installed, most are disabled. But I also see the problem when I run `code --disable-extension .` and open a Markdown preview.

```
daniel.fritz ~/Dev/splat (feat/splat1-2779/cdk-cfninclude !$)
% uname -a
Darwin Ibis.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

daniel.fritz ~/Dev/splat (feat/splat1-2779/cdk-cfninclude !$)
% code --version
1.64.1
d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
x64

daniel.fritz ~/Dev/splat (feat/splat1-2779/cdk-cfninclude !$)
% code --list-extensions
alefragnani.Bookmarks
bungcip.better-toml
cssho.vscode-svgviewer
dbaeumer.vscode-eslint
DigitalBrainstem.javascript-ejs-support
dmnsgn.vscode-wavefront
DotJoshJohnson.xml
eamodio.gitlens
EditorConfig.EditorConfig
esbenp.prettier-vscode
Gruntfuggly.todo-tree
hashicorp.terraform
matklad.rust-analyzer
mikestead.dotenv
ms-vscode.hexeditor
ms-vsliveshare.vsliveshare
nwolverson.ide-purescript
nwolverson.language-purescript
PolyMeilex.wgsl
raczzalan.webgl-glsl-editor
sibiraj-s.vscode-scss-formatter
slevesque.shader
vscodevim.vim
wgsl-analyzer.wgsl-analyzer

daniel.fritz ~/Dev/splat (feat/splat1-2779/cdk-cfninclude !$)
%
```
