### ISSUE TITLE
add go to cwd action to command context menu

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#142549]

**Comment by meganrogge** [comment]
not sure this is useful given we have the command and might just feel like clutter. thoughts @Tyriar ?

**Comment by Tyriar** [comment]
The command isn't very discoverable, we'll eventually have autocomplete to help with this though like run recent command. We should only show this if the cwd differs which would reduce the amount of clutter, it still seems like a valid thing to have there but I personally wouldn't use it. Let's leave it off for now and wait for feedback?
