### ISSUE TITLE
Quick Fix: Keyboard shortcut CTRL+. shows a small 'e'

### ISSUE THREAD

**Issue by danjaredg** [microsoft/vscode#142583]
Related to the problem reported in https://github.com/microsoft/vscode/issues/135084

This problem occurs in KDE and the IBus Panel. To fix it you need to remove the keyboard shortcuts for emojis.

![fix-bug-ctrl+dot](https://user-images.githubusercontent.com/2866615/153119486-cbb3f983-0eb6-45a7-bfc4-b14da5c054fb.jpg)

**Comment by mjbvz** [comment]
I don't understand the issue. Can you please provide more details 

/needsMoreInfo

**Comment by danjaredg** [comment]
@mjbvz  if you run vscode in linux with kde desktop with Ibus-daemon enable, the default shortcut Quick Fix <ctrl+.> doesn't work and print a small 'e' character just like this post https://github.com/microsoft/vscode/issues/135084#issuecomment-943347988. This 'e' is like a special character not exactly letter 'e'.

as a workaround:
If you disable emoji shortcuts from ibus-daemon (run "ibus-setup" to show ibus preferences) the shortcut Quick Fix <ctrl+.> works again.

I'm using this kde distribution:
Operating System: Kubuntu 21.10
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-28-generic (64-bit)
Graphics Platform: X11

**Comment by alexdima** [comment]
@danjaredg Thank you for the extra info. Since this is a problem caused by the environment, there is nothing we can do on our side to improve. However, I have documented this as a known issue at https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings :

> <img width="864" alt="image" src="https://user-images.githubusercontent.com/5047891/154252392-abc5087d-e749-406b-8fe8-effb6a8da7ee.png">
