### ISSUE TITLE
Active terminal can get out of sync after dragging and dropping tabs

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#142562]
Repro:

1. Create some terminals, write something in them to differentiate them
2. Select terminal B
3. Drag and drop terminal A below terminal B

Notice how the blue bar is next to pwsh but the actual active terminal is the test task:

![image](https://user-images.githubusercontent.com/2193314/153083870-c5e0f011-b412-4431-902f-74248940e29a.png)

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/150541

**Comment by meganrogge** [comment]
the blue bar doesn't represent the active terminal - you have to double click that tab for to change it to be the active one

**Comment by meganrogge** [comment]
seems fixed
