### ISSUE TITLE
test failure: Normalization -- removeAccents

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#142544]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=154672&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=821d316a-2fa3-581f-c34c-57a961b8e328

  1) Normalization
       removeAccents:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\test\unit\node\index.js)
      at processImmediate (internal/timers.js:464:21)

**Comment by jrieken** [comment]
Closing without action. The test is as simple as it gets and it must have been some pipeline hickup
