### ISSUE TITLE
vscode无法打开wsl

### ISSUE THREAD

**Issue by jyyqaj** [microsoft/vscode#142576]
Issue Type: <b>Bug</b>

安装remote on wsl插件后尝试打开wsl上的文件时无法正常打开

VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:16:22.147Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Connection to 'WSL: Ubuntu' could not be established  VS Code Server for WSL failed to start. No messages received for 90s
Check WSL terminal for more details.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (22.79GB free)|
|Process Argv|--crash-reporter-id 0571489f-12f8-4147-abf3-a861fcb4aecc --crash-reporter-id 0571489f-12f8-4147-abf3-a861fcb4aecc|
|Screen Reader|no|
|VM|0%|

Connection to 'WSL: Ubuntu' could not be established  VS Code Server for WSL failed to start. No messages received for 90s
Check WSL terminal for more details.
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30433058
pythonvs932:30410667
wslgetstarted:30433507
vscop341:30404997
vsrem710:30416614

```

</details>

**Comment by CodeCrazy-ywt** [comment]
With “remote on wsl” extension on, unable to open files on wsl.
