### ISSUE TITLE
Don't show multi-line paste warning when bracketed paste mode is enabled

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#142525]
See https://github.com/microsoft/vscode/issues/122683#issuecomment-1032381062

We have modes exposed in xterm.js now, need to check this prop: https://github.com/xtermjs/xterm.js/blob/a13f11adb4b04245684b24a5b33cbbc2351588d4/typings/xterm.d.ts#L1701-L1704

**Comment by rzhao271** [comment]
What are some verification steps for this issue?

**Comment by meganrogge** [comment]
In `bash` (might be different for other shells), run ` printf "\e[?2004h"` in the terminal. Copy and paste some multiline text. You shouldn't see the warning. 

To disable it, run `printf '\e[?2004l'`
