### ISSUE TITLE
Allow to minimize Side Panel

### ISSUE THREAD

**Issue by ngdangtu-vn** [microsoft/vscode#142579]
I totally love the Side Panel idea. And it would be great if I can minimize/collapse it to small icon like InkScape (or Photoshop)

![image](https://user-images.githubusercontent.com/68631458/153110132-04a1a34f-1779-4801-9df9-f19288111024.png)

InkScape example:
![image](https://user-images.githubusercontent.com/68631458/153110433-2924f407-8d60-49e0-96d5-baa44222226b.png)

Photoshop example (image source: internet from google)
![f0002-01](https://user-images.githubusercontent.com/68631458/153110496-82e64a3d-9bf7-4698-bdc1-4c9369ebb77a.jpg)

**Comment by IllusionMH** [comment]
Related to #141569
@sbatten does #141569 imply that new button will be added as well?

**Comment by ngdangtu-vn** [comment]
> Related to #141569 @sbatten does #141569 imply that new button will be added as well?

I think he has the same idea with me but mistook it with bug. It just similar term.

**Comment by ngdangtu-vn** [comment]
My bad, I never plan to move the panel so I didn't know about this. but toggle with shortcuts can be done for panel with `Ctrl + J` right?

**Comment by nguyendviet** [comment]
Yes. That's the default shortcut in VSCode. This is helpful: https://code.visualstudio.com/docs/getstarted/keybindings 
You can also open the keybindings add search for what you need.

**Comment by ngdangtu-vn** [comment]
> I still believe that it would be perfect if we could have the float panel rather than side panel

I somewhat agree with you. Float panels and float tabs can be extremely useful for double monitors. But what I was talking about was enhancing feature. You may be off topic.
