### ISSUE TITLE
failure to commit

### ISSUE THREAD

**Issue by MadonaAbbott** [microsoft/vscode#142535]
Issue Type: <b>Bug</b>

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

$ git status
warning: could not open directory 'Application Data/': Permission denied
warning: could not open directory 'Cookies/': Permission denied
warning: could not open directory 'Local Settings/': Permission denied
warning: could not open directory 'My Documents/': Permission denied
warning: could not open directory 'NetHood/': Permission denied
warning: could not open directory 'PrintHood/': Permission denied 
warning: could not open directory 'Recent/': Permission denied    
warning: could not open directory 'SendTo/': Permission denied    
warning: could not open directory 'Start Menu/': Permission denied
warning: could not open directory 'Templates/': Permission denied 
On branch making_websites     
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    OneDrive/Desktop/JWD/MAKING WEBSITE PRACTICE FOLDER/simpleherosection.html
        deleted:    OneDrive/Desktop/JWD/MAKING WEBSITE PRACTICE FOLDER/simpleherostyle.css
        deleted:    README.md

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .gitconfig
        .vscode/
        AppData/
        Contacts/
        Documents/
        Downloads/
        Favorites/
        Landing_Page/
        Links/
        MicrosoftEdgeBackups/
        Music/
        NTUSER.DAT
        NTUSER.DAT{fd9a35db-49fe-11e9-aa2c-248a07783950}.TM.blf
        NTUSER.DAT{fd9a35db-49fe-11e9-aa2c-248a07783950}.TMContainer00000000000000000001.regtrans-ms
        NTUSER.DAT{fd9a35db-49fe-11e9-aa2c-248a07783950}.TMContainer00000000000000000002.regtrans-ms
        OneDrive/.849C9593-D756-4E56-8D6E-42412F2A707B
        OneDrive/Desktop/Grammarly.lnk
        OneDrive/Desktop/IMPORTANT CODES/
        OneDrive/Desktop/Ivan_Challenge/
        OneDrive/Desktop/JWD/ivan_studentsite/
        OneDrive/Desktop/Landing_Page HTML and CSS/
        OneDrive/Desktop/SPICUS FEEDBACKS.txt
        OneDrive/Desktop/Spicus.html
        OneDrive/Desktop/Spicus.lnk
        OneDrive/Desktop/Spicus_files/
        OneDrive/Desktop/VIPKID FEEDBACKS/
        "OneDrive/Desktop/Your Progressive Home Advantage\302\240Homeowners Insurance Quotation - thecoolestnameintheworld@gmail.com 
- Gmail_files/"
        OneDrive/Desktop/desktop.ini
        OneDrive/Desktop/website_practice_folders/
        OneDrive/Document 2.docx
        OneDrive/Documents/
        OneDrive/Personal Vault.lnk
        OneDrive/Pictures/
        OneDrive/desktop.ini
        Pictures/
        Saved Games/
        Searches/
        Tracing/
        Videos/
        bootstrap_practice/
        fonts/
        jwd_final_project/
        my-portfolio-site/
        ntuser.dat.LOG1
        ntuser.dat.LOG2
        ntuser.ini

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3250U with Radeon Graphics          (4 x 2595)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.92GB (1.58GB free)|
|Process Argv|--crash-reporter-id 19329e6f-dd01-44c3-b8de-bf42d4a98350|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vscop453:30404998
vsrem710:30416614

```

</details>

**Comment by gjsjohnmurray** [comment]
It looks like you are trying to use git to manage a Onedrive folder. See https://github.com/microsoft/vscode/issues/106287#issuecomment-688934395

**Comment by lszomoru** [comment]
@MadonaAbbott, could you please confirm that you are trying to use git with a OneDrive folder? Thanks!
