### ISSUE TITLE
Requires Github sign-in every time after opening the VSCode

### ISSUE THREAD

**Issue by ragokan** [microsoft/vscode#142553]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.64.0
- OS Version: macOS Monterey V 12.2 (21D49)

Steps to Reproduce:

1. I open the app.
2. I get this prompt:
![image](https://user-images.githubusercontent.com/63511519/153075788-31a9e6b0-daaf-4812-a0b8-ea4d4ce44249.png)
3. I login for both of them
4. Restart the VSCode, all accounts are gone, wants me to sign in again..

Same thing happens for VSCode Insiders.

I had this issue when I firstly installed Big Sur, too. After a week, this went away. Today I did a clean install, now this problem appeared again.

--Edit: It also breaks the install code or code-insiders to path command.

**Comment by TylerLeonhardt** [comment]
> --Edit: It also breaks the install code or code-insiders to path command.

can you elaborate on this?

Can you also follow these steps so that we can get more information on what's going on?

* Open the Command Palette
* Run the `Developer: Set Log Level...` command
* Choose `Trace`
* _Wait for the issue to happen..._
* Open the Output pane
* drop in this issue he contents of the following:
  * `GitHub Authentication` or `Microsoft Authentication` Output channel
  * `Log (Settings Sync)` Output channel
  * `Log (Window)` Output channel

**Comment by ragokan** [comment]
> 

Microsoft Auth
![image](https://user-images.githubusercontent.com/63511519/153160949-9158b8f5-6613-4195-b5dd-4624ac779a4b.png)

Github Auth
![image](https://user-images.githubusercontent.com/63511519/153160986-e5389b98-6d4e-4d98-aa0a-6878fe112811.png)

Log (Window)
![image](https://user-images.githubusercontent.com/63511519/153161038-0ec23bb4-9908-4461-88de-deb92b6fd1f5.png)

**Comment by ragokan** [comment]
I also think there can be more errors
Log (Main)
![image](https://user-images.githubusercontent.com/63511519/153161251-b1cf1334-1182-4ef0-b5e1-0d37c6c31688.png)

Log (Setting Sync)
![image](https://user-images.githubusercontent.com/63511519/153161306-8428bc4f-10e2-42c2-b8ff-28cf6658aee1.png)


Lastly Git
![image](https://user-images.githubusercontent.com/63511519/153161381-130e2b69-0833-4c87-ae9f-a70057d1f582.png)

**Comment by ragokan** [comment]
> I also think there can be more errors Log (Main) ![image](https://user-images.githubusercontent.com/63511519/153161251-b1cf1334-1182-4ef0-b5e1-0d37c6c31688.png)
> 
> Log (Setting Sync) ![image](https://user-images.githubusercontent.com/63511519/153161306-8428bc4f-10e2-42c2-b8ff-28cf6658aee1.png)
> 
> Lastly Git ![image](https://user-images.githubusercontent.com/63511519/153161381-130e2b69-0833-4c87-ae9f-a70057d1f582.png)

Not sure if I font it correctly but I think the main problem was permissions of code. Even though I gave it full permission, there were some problems. So I installed VSCode with Brew. For now, it looks like fixed. If it does not ask to log in again tomorrow I will close this issue.
Thank you @TylerLeonhardt for showing where the logs are.
