### ISSUE TITLE
The background of the vscode icon in the right-click menu is black

### ISSUE THREAD

**Issue by EastMonster** [microsoft/vscode#142504]
Issue Type: <b>Bug</b>

As you can see, when you right click a file, there is a option shows that "Open with VSCode". But the icon of VSCode is always black even if the entire menu is white. It's just a visual effect problem, which doesn't bother me when using VSCode. But I hope this "bug" can be fixed later. Thanks! :)
<img width="320" alt="light" src="https://user-images.githubusercontent.com/89259667/152970963-a3bdd0b1-a551-46ad-acdb-88a79e26e900.png">
<img width="323" alt="dark" src="https://user-images.githubusercontent.com/89259667/152970973-48235620-0d8b-4900-921e-dae150bb9dfb.png">

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.87GB (5.52GB free)|
|Process Argv|--crash-reporter-id eace3f5c-756b-4cf3-a63b-6d99150927ba|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
code-runner|for|0.11.6
vscode-language-pack-zh-hans|MS-|1.64.6
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-wsl|ms-|0.64.2
cpptools|ms-|1.8.5
java|red|1.3.0
python|tht|0.2.3
vscodeintellicode|Vis|1.2.16
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vs360cf:30404996
vsrem710cf:30416617

```

</details>

**Comment by sbatten** [comment]
@EastMonster this is actually a bug in Windows 11 that has been fixed in more recent builds. When the next major update to Windows 11 is released, this will be resolved. Thanks
