### ISSUE TITLE
Cannot 'send' variables while debugging node script

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#142557]
Issue Type: <b>Bug</b>

1. Create an invalid node script:

```js
const fetch = require('node-fetch');

function main() {
    const result = await fetch('https://example.com');
    const data = await result.arrayBuffer();

    console.log(result.ok);
}

main();
```

Notice how `main` is missing `async`

2. `F5` to debug

**Bug**
The debug console prints:

```
No debugger available, can not send 'variables'
```

![Screen Shot 2022-02-08 at 1 52 44 PM](https://user-images.githubusercontent.com/12821956/153082023-63d13c5d-ad1e-43ec-9aef-101c41f8b9f2.png)

The line number is listed but not the error about the missing `async`. I think the `No debugger available, can not send 'variables'` message is red herring

VS Code version: Code - Insiders 1.65.0-insider (Universal) (f8c36556a2c305327f5417dc7f93220f39ed608f, 2022-02-08T09:50:40.699Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (2.56GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
salesforce-soql-editor|all|1.8.0
tsl-problem-matcher|amo|0.5.0
comment-tagged-templates|bie|0.3.1
docs-view|bie|0.0.9
emojisense|bie|0.9.0
folder-source-actions|bie|0.2.1
github-markdown-preview|bie|0.1.0
jsdoc-markdown-highlighting|bie|0.0.1
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
vscode-eslint|dba|2.2.2
dendron|den|0.81.0
dendron-paste-image|den|1.1.0
typescript-notebook|don|2.0.6
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
codespaces|Git|1.5.2
copilot|Git|1.7.4924
remotehub|Git|0.24.0
vscode-pull-request-github|Git|0.37.2022020809
vscode-drawio|hed|1.6.4
vscode-postfix-ts|ipa|1.9.4
latex-workshop|Jam|8.23.0
vscode-platform-specific-sample|joa|1.15.0
vscode-platform-specific-sample|joa|1.5.0
vscode-memfs|jri|0.0.3
vscode-position|jtr|1.1.2
template-string-converter|meg|0.6.0
git-graph|mhu|1.30.0
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.19.0
vscode-language-pack-de|MS-|1.64.6
python|ms-|2022.1.1786926181-dev
vscode-pylance|ms-|2022.1.6-pre.1
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.219.0
remote-ssh|ms-|0.73.2022020715
remote-ssh-edit|ms-|0.73.2022020715
azure-account|ms-|0.9.11
hexeditor|ms-|1.9.4
js-debug-nightly|ms-|2022.2.809
live-server|ms-|0.2.12
vscode-github-issue-notebooks|ms-|0.0.113
vscode-typescript-next|ms-|4.6.20220207
vsliveshare|ms-|1.0.5330
debugger-for-chrome|msj|4.13.0
vetur|oct|0.35.0
java|red|1.3.0
code-spell-checker|str|2.1.6
rest-book|tan|5.0.1
ayu|tea|1.0.5
luna-paint|Tyr|0.13.1
sort-lines|Tyr|1.9.1
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Oddly copy and pasting from the debug console reveals the error message:

```
Note: Using the "preview" debug extension
[/Users/matb/.nvm/versions/node/v14.17.6/bin//node]() [./index.js]()
Process exited with code 1
Uncaught [/Users/matb/projects/san/index.js:4]()
    const result = await fetch('[https://example.com]()');
                   ^^^^^

SyntaxError: await is only valid in async function
No debugger available, can not send 'variables'
```

However I can't find any way to view this in the debug console itself

**Comment by connor4312** [comment]
The "cannot send variables" is expected after a debug session ends, the underlying issue is that multiline errors are not shown for complex objects in the debug console. This is the same as https://github.com/microsoft/vscode/issues/122870
