### ISSUE TITLE
Changed files are not appearning in SCM

### ISSUE THREAD

**Issue by xi2318-rahulrajput** [microsoft/vscode#142500]
Issue Type: <b>Bug</b>

The files that have been changed are not appearing in the SCM, although the count is still appearing over the icon, signifying that x number of files have changed.

VS Code version: Code 1.59.0 (Universal) (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id c111468c-d9f5-41f8-9ae8-bd2d4cf20d74|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.6
gitlens|eam|11.6.1
vscode-author-generator|edw|0.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstartedc:30433508
vs360:30404995
vsrem710cf:30416617
vscop841cf:30434590

```

</details>

**Comment by gjsjohnmurray** [comment]
You are several versions behind. Can you update to 1.64 and test again?

**Comment by xi2318-rahulrajput** [comment]
thanks, working now
