### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by tyxou2** [microsoft/vscode#142512]
Issue Type: <b>Bug</b>

any changes to files using git require restart of app to show (macOS 10.13.6)

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:20:17.224Z)
OS version: Darwin x64 17.7.0
Restricted Mode: No

Version: 1.64.0
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:20:17.224Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 17.7.0

**Comment by DoubleCorner** [comment]
I have the same problem. I user [git add .] or [git commit] in terminal，the panel of source control is not update, I need to force to refresh.

**Comment by gjsjohnmurray** [comment]
@DoubleCorner what platform? And is your git repo in an ordinary local folder?

**Comment by tyxou2** [comment]
my git repo is a local folder. To clarify: when I update any code in any file, the file in the file-tree shows there's a change which needs to be committed (change colour to orange-ish). When these changes are committed (or even changing branch, the bottom task-bar keeps showing the previous branch) the file-tree structure keeps showing the same orange-ish colour on the files that were just committed. Closing and opening VS Code is the only "solution" I have, to "force" it to update accordingly.

**Comment by DoubleCorner** [comment]
@gjsjohnmurray macOS 12.2. My git repo is a local folder.

**Comment by tyxou2** [comment]
Version: 1.64.2 fixed this issue for me on macOS High Sierra (10.13.6)
