### ISSUE TITLE
Hover-over Intellisense shows comments from code block eliminated by preprocessor.

### ISSUE THREAD

**Issue by zfields** [microsoft/vscode#142506]
Does this issue occur when all extensions are disabled?: Yes/No

Yes.

- VS Code Version:
- OS Version:

```
Version: 1.64.0
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:23:11.224Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.15.15-76051515-generic
```

Steps to Reproduce:

1. Create two implementations of a function controlled by a preprocessor switch...

```c
#if 0
// I DO NOT expect to see this description of `foo`
// param: bar can only be a value between 0 and 7
void foo (int bar) {}
#else
// I DO expect to see this description of `foo`
// param: bar can only be a value between 8 and 15
void foo (int bar) {}
#endif
```

2. Hover over `foo(...)` elsewhere in your code, and you will be shown the wrong comment block.

Obviously, this example is trivial, but in my real scenario the code comments I was being shown were very misleading and would have caused me to introduce a bug into the system.

The editor already detects which blocks should be "darkened" to indicate they are commented out. It would be very helpful to use this same logic to decide whether or not a comment block should be shown when you hover over text.

**Comment by jrieken** [comment]
What language, what extension is this?

**Comment by zfields** [comment]
It is C and/or C++.
