### ISSUE TITLE
Side panel vertical border no longer shown

### ISSUE THREAD

**Issue by JordanPak** [microsoft/vscode#142519]
Issue Type: <b>Bug</b>

1. Open "panel" with debugger output, terminal, etc.
2. Run "Move views from panel to side panel" to get the debugger output, terminal, etc over to the right "sidebar". The left side border of the panel is no longer displayed. The bottom panel's top border was displayed before moving everything to the side panel, though.

Thanks for your time

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.29GB free)|
|Process Argv|--crash-reporter-id 9b37e760-2a20-438d-b520-00788ceb97ce|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics (16 x 3193)|
|Memory (System)|12.37GB (9.93GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.4.0
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
vscode-icons|vsc|11.8.0
material-theme|zhu|3.13.19
vscode-intelephense-client|bme|1.8.0
gitlens|eam|11.7.0
beautify|Hoo|1.5.0
postcss-language|mhm|2.1.0
color-highlight|nau|2.5.0
trailing-spaces|sha|0.3.1
php-debug|xde|1.23.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vscop940:30404999
vsrem710:30416614

```

</details>

**Comment by sbatten** [comment]
The side panel is themed like the side bar and therefore uses the border key from the side bar if set.

**Comment by sbatten** [comment]
see relevant https://github.com/microsoft/vscode/issues/141397

**Comment by JordanPak** [comment]
Ah ok @sbatten, thanks for your time. You were right: I'm pretty sure it was just a different background color and that went away, removing the contrast and making me think there used to be a border xD

'Preciate your help!
