### ISSUE TITLE
ctrl+k, ctrl+d does not format code as indicated

### ISSUE THREAD

**Issue by ayyash** [Microsoft/vscode#14255]
I am looking at Default keyword shortcuts and can see two entries:
```
{ "key": "ctrl+k ctrl+d",        
 "command": "editor.action.formatDocument",
 "when": "editorHasDocumentFormattingProvider && editorTextFocus && !editorReadonly" },
{ "key": "shift+alt+f",         
  "command": "editor.action.formatDocument",
  "when": "editorHasDocumentFormattingProvider && editorTextFocus && !editorReadonly" },
```

Yet the first shortcut never seems to work, i tried overriding with shift+alt+ set to empty command, but that doesn't work, what do I do to make it work?

meta:
- VSCode Version: Code - Insiders 1.7.0-insider (788caba5a3ca1c2b137353f4384bb0e026db1a31, 2016-10-21T23:41:55.553Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.17|
|htmltagwrap|bradgashler|0.0.3|
|vscode-stylesheet-formatter|dbalage|0.2.0|
|vscode-npm-script|eg2|0.0.21|
|auto-rename-tag|formulahendry|0.0.7|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.1|
|JasmineSnippets|xabikos|0.2.0|

---

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
It depends on the current file, its language, and the set of installed extensions. Note this bit of the keybinding rule: `editorHasDocumentFormattingProvider`. It means, that formatting is only available when a formatter has been installed. An easy quick-check is the context menu - it will only show the format document entry when a formatter *for that language* is available.

**Comment by ayyash** [comment]
but "shift+alt+f" work on the same file (for example HTML)

**Comment by jrieken** [comment]
You are right... Very funky...

**Comment by jrieken** [comment]
Seems like there is a conflict with [`MoveSelectionToNextFindMatchAction`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/find/common/findController.ts#L641). Tough call... On the one side I don't want to break an existing keybinding but on the other I think it would be good if we have common VS shortcuts.

@waderyan Do we have a VS key-map extension? That seems like a nice place to define  such a keybinding.

**Comment by waderyan** [comment]
@jrieken VS keymap is on the roadmap. This use case is noted.

**Comment by isidorn** [comment]
Removed label bug since we have decided to remove that keybinding

**Comment by ayyash** [comment]
Is this released yet? Code insiders? Does the change indicate that i will have to create my own shortcut?
