### ISSUE TITLE
Support DnD for problem markers and search matches

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#142508]
In Problems/Search view, one can DnD a file resource into editor. This request is to support the same functionality for Problem Marker entries and Search match entries.

**Comment by sandy081** [comment]
To support range selection in URI, extended URI fragment selection syntax to support ranges. Eg:

`file:///some/file.js#73,84-83,52`
`file:///some/file.js#L73,84-L83,52`

**Comment by sandy081** [comment]
CC @roblourens - Search matches also support this behavior now.

**Comment by roblourens** [comment]
Thanks!
