### ISSUE TITLE
Performance issue rendering test peek window during test run

### ISSUE THREAD

**Issue by JDaance** [microsoft/vscode#142514]
Does this issue occur when all extensions are disabled?: Yes (except for the one being debugged)

- VS Code Version:
Version: 1.65.0-insider
Commit: 0283cec6ec2c2d5ec39006a1048b8dc3ea8bc955
Date: 2022-02-08T05:16:19.099Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.15.19-1-MANJARO snap

Edit: This also occurs on the latest official release

I have built my own test extension for a lua based game that I have used for a long time with the external Test Explorer UI. I am now migrating to "native" vscode api. I have about 2000 tests which run fine if the test result peek window is not showing. If this view is showing, like it does if a test fails in an open editor, the GUI grinds to a complete halt and spends minutes being frozen, according to profiler screenshot below:

![image](https://user-images.githubusercontent.com/1148112/152999209-1f660736-2915-4169-a98f-0d4dcbfec2d9.png)

![image](https://user-images.githubusercontent.com/1148112/152998940-28b65900-07b5-4740-b046-aaeeb230d615.png)

Screenshots are from running just 177 tests (the full 2000 takes too long)
177 tests takes about 8 seconds with peek open
With peek closed (no files open) it takes an imperceptible amount of time, say 100 ms.
Closing the "Test History" in the peek view does not help.

Similar code worked fine with the old external test explorer UI extension. I realize I am may be causing this by some error on my end, since I can't find any other reports on this issue. If there are any ideas what I might be doing wrong, or what usage pattern might trigger this behavior, that would be most helpful.

**Comment by JDaance** [comment]
**Here is a profile of related/same performance problem when opening the peek view after running tests.**

With the peek view set to not open automatically (this is with all 2000 tests) then after run clicking to open the peek view takes a noticeable amount of time, which I have screenshots of profile below:

![image](https://user-images.githubusercontent.com/1148112/153005220-f70a68fb-4a28-4109-bf42-e5b86094a192.png)
![image](https://user-images.githubusercontent.com/1148112/153005381-4e3def09-ec57-4a03-afe6-c613e661b4f5.png)

It does indeed seem to spend time in similar (or the same) areas of the code

**Comment by connor4312** [comment]
Thanks, I'll look into this! If it's not too much trouble, could you export one of your performance profiles and share it here?

![image](https://user-images.githubusercontent.com/2230985/153024073-261f9aaf-f20f-418e-8bda-8f855577e892.png)

I will profile it myself too, of course, but want to make sure I fix the same problem you're seeeing.

**Comment by JDaance** [comment]
> Thanks, I'll look into this! If it's not too much trouble, could you export one of your performance profiles and share it here?
> 
> ![image](https://user-images.githubusercontent.com/2230985/153024073-261f9aaf-f20f-418e-8bda-8f855577e892.png)
> 
> I will profile it myself too, of course, but want to make sure I fix the same problem you're seeeing.

I didn't realize that was possible, of course what a good idea!

[Profile-20220208T183858.zip](https://github.com/microsoft/vscode/files/8026183/Profile-20220208T183858.zip)

This is the same run with 177 tests but it took even longer this time, around 18 seconds.

**Comment by connor4312** [comment]
@JDaance to confirm -- are all these tests creating messages/output that are getting displayed in the test output peek?

**Comment by JDaance** [comment]
> @JDaance to confirm -- are all these tests creating messages/output that are getting displayed in the test output peek? That's how I can repro.

Indeed that was it, it works great, thanks a lot!
