### ISSUE TITLE
bracket completion error in chinese

### ISSUE THREAD

**Issue by TuRan-sino** [microsoft/vscode#142528]
When i input '(' while using chinese input method
Vscode will output "(()" but not "()

https://user-images.githubusercontent.com/51948125/153028780-d901aa0a-5ae7-4c55-b071-cd32cd8dffa1.mp4

**Comment by alexdima** [comment]
@TuRan-sino Does this reproduce when disabling all extensions? (the `vim` extension handles most of the typing when it is active).

**Comment by TuRan-sino** [comment]
I 've try it when disabling all extensions, but it still has problems

**Comment by alexdima** [comment]
I believe this is also fixed by e356139a1095b92e0a89be34553aeedb24aa78c0. Please verify with tomorrow's insiders.
