### ISSUE TITLE
MacOS: Dark Custom Title Bar

### ISSUE THREAD

**Issue by Fenwil** [Microsoft/vscode#14258]
It will be great if next versions of Visual Studio Code has a Custom title bar like [this](https://cloud.githubusercontent.com/assets/378023/19135767/24a16dde-8ba2-11e6-83a3-b6d75180fc65.png) that is on Atom 1.11.

You could see the feature in their [blog](http://blog.atom.io/2016/10/11/atom-1-11.html)

**Comment by DickvdBrink** [comment]
Slightly related to https://github.com/Microsoft/vscode/pull/12628

**Comment by bpasero** [comment]
PR welcome 👍

**Comment by bpasero** [comment]
Landed with https://github.com/Microsoft/vscode/issues/15098
