### ISSUE TITLE
Refactoring option: for of loop to forEach method

### ISSUE THREAD

**Issue by PositiveUser** [microsoft/vscode#142597]
We cannot use index of array elements using for of loop because we can only work with elements, but I realized I also needed index and this is possible with forEach method.

Please include a refactoring option to convert for of loop to forEach method

---

**Example**

```js
for (let question of questions) {
    // ...
}
```

The above code should be the below code after refactoring

```js
questions.forEach((question) => {
    // ...
})
```

**Comment by mjbvz** [comment]
This seems like a good candidate for an extension. If it is popular enough, we could then consider integrating it into core VS Code
