### ISSUE TITLE
Every time I update VS code, all my envs stop working

### ISSUE THREAD

**Issue by chozandrias76** [microsoft/vscode#142567]
Issue Type: <b>Bug</b>

Couldn't start SonarLint Language Server
Java 11 or more recent is required to run
Ruby Test Explorer failed...

VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:16:22.147Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Darwin x64 20.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (48.79GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bmac/Users/crashoverride/work/ledger --crash-reporter-id 820f842f-d221-4d2b-8f3a-3ef6c2c97d65|
|Screen Reader|no|
|VM|31%|

|Item|Value|
|---|---|
|Remote|SSH: mac|
|OS|Darwin x64 20.6.0|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|Memory (System)|32.00GB (0.14GB free)|
|VM|0%|
</details><details><summary>Extensions (133)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
project-manager|ale|12.4.0
es7-react-js-snippets|dsz|4.2.0
vscode-firefox-debug|fir|2.9.6
auto-rename-tag|for|0.1.10
rbs-syntax|Gra|0.3.0
ruby|gro|0.1.0
output-colorizer|IBM|0.1.2
vscode-react-typescript|inf|1.3.1
customize-ui|ioc|0.1.58
monkey-patch|ioc|0.1.16
vscode-peacock|joh|4.0.0
dotenv|mik|1.0.1
vscode-edge-devtools|ms-|1.4.3
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.70.0
code-settings-sync|Sha|3.4.3
errorlens|use|3.4.1
haml|vay|1.0.1
gistfs|vsl|0.3.0
jinja|who|0.0.8
vscode-ruby|win|0.28.0
ReactSnippets|xab|2.4.0
material-theme|zhu|3.13.19
rails-db-schema|aki|0.2.4
Bookmarks|ale|13.2.2
vscode-erb-beautify|ali|0.3.5
vscode-zipfs|arc|2.3.0
chronicler|arc|0.1.16
All-Autocomplete|Ati|0.0.23
vscode-database|baj|2.2.3
vscode-django|bat|1.8.1
markdown-checkbox|bie|0.3.2
insert-unicode|bru|0.13.1
vscode-gemfile|bun|0.4.2
solargraph|cas|0.23.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.7.0
regex|chr|0.4.0
vscode-postgres|cko|1.4.0
vscode-devtools-for-chrome|cod|0.0.7
gitignore|cod|0.7.0
vscode-ruby-test-adapter|con|0.9.0
vscode-markdownlint|Dav|0.46.0
jshint|dba|0.11.0
vscode-eslint|dba|2.2.2
vscode-quick-select|dba|0.2.9
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
gitlens|eam|11.7.0
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.2.0
ft-extension-pack|Fer|0.0.1
code-runner|for|0.11.7
docker-explorer|for|0.1.7
shell-format|fox|7.2.2
copilot|Git|1.7.4924
vscode-graphql|Gra|0.3.41
ruby|gro|0.1.0
todo-tree|Gru|0.0.215
ruby-signature|han|0.0.2
vscode-test-explorer|hbe|2.21.1
docker-linter|hen|0.5.0
monkey-patch|ioc|0.1.16
vscode-heroku|iva|1.2.6
hungry-delete|jas|1.6.0
search-node-modules|jas|1.3.0
jbockle-format-files|jbo|3.4.0
nbpreviewer|jit|1.2.2
lorem-whatever|job|1.0.2
vsc-python-indent|Kev|1.14.2
vscode-markdown-notes|kor|0.0.24
vscode-format-context-menu|lac|1.0.4
go-to-spec|Lou|0.1.3
MagicPython|mag|1.1.0
metago|met|4.2.0
MetaJump|met|1.4.0
MetaWord|met|1.3.0
vscode-language-babel|mgm|0.0.36
git-graph|mhu|1.30.0
vscode-checkpoints|mic|1.3.2
ruby-rubocop|mis|0.8.6
vscode-docker|ms-|1.19.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
test-adapter-converter|ms-|0.1.5
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0
gremlins|nho|0.26.0
autodocstring|njp|0.5.4
rails-run-spec-vscode|nok|0.1.4
vscode-jest|Ort|4.2.1
vscode-yaml-sort|Pas|5.1.2
vscode-jscpd|pau|0.3.4
yard|pav|0.4.0
material-icon-theme|PKi|4.12.1
heroku-command|pko|0.0.8
polacode|pnp|0.3.4
vscode-data-preview|Ran|2.3.0
ruby|reb|0.28.1
java|red|1.3.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.4.0
explorer-exclude-vscode-extension|Red|1.2.0
bash-debug|rog|0.3.9
vscode-paste-and-indent|Rub|0.0.8
vscode-coverage-gutters|rya|2.9.1
vscode-cy-helper|She|1.2.2
sonarlint-vscode|Son|3.2.0
autoimport|ste|1.5.4
code-spell-checker|str|2.1.6
vscode-stylelint|sty|1.2.1
control-snippets|svi|1.9.1
pdf|tom|1.2.0
sort-lines|Tyr|1.9.1
errorlens|use|3.4.1
haml|vay|1.0.1
vscodeintellicode|Vis|1.2.17
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-maven|vsc|0.35.0
Ruby-extension-pack|wal|1.0.0
quokka-vscode|Wal|1.0.443
wallaby-vscode|Wal|1.0.325
jinja|who|0.0.8
vscode-ruby|win|0.28.0
vscode-import-cost|wix|2.15.0
ReactSnippets|xab|2.4.0
txt-syntax|xsh|0.2.0
markdown-all-in-one|yzh|3.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vscop341:30404997
vsrem710:30416614
vscop841:30434589

```

</details>

**Comment by chozandrias76** [comment]
The bug seems to have auto resolved itself the next day. Curious.

**Comment by lramos15** [comment]
Glad it's fixed 👍
