### ISSUE TITLE
Introduce command "Help: Sound Cues"

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#142540]
We should add the command "Help: Sound Cues" that would move focus to the quick pick and list all the sounds there. The user can navigate through the quick pick and we would play the sound based on the active item. That way new users can get introduced to the sounds we use and to the new ones as we introduce them.

fyi @gino-scarpino @jrieken

**Comment by hediet** [comment]
Available in latest insiders.

**Comment by hediet** [comment]
I improved the command a bit. It is called now `Help: List Audio Cues` to indicate the command's purpose.
Also, the focus is initially set to the first element of that list, so the confusing initial message is no longer being read, but instead the first element.
The update will be available in Mondays insider build.

Let me know what you think of that!

**Comment by isidorn** [comment]
@hediet this is cool work 👏  
I just tried it out of source and it behaves well for me. Let's see what @jvesouza says once he gets a chance to try it out.

**Comment by jvesouza** [comment]
@isidorn  @hediet
I downloaded vscode today, installed and tested it. The behavior is exactly the same as with the previous version. It's like the changes hadn't been applied.

Today's version has the following commit id:
a0da9978b10ae0b9307c7f545b50a8500efff7eb

**Comment by jvesouza** [comment]
@hediet Yes, the accessibility support is turned on.
Except for audio cues has warnnings, all options are set to auto.

**Comment by hediet** [comment]
This is the current behavior with NVDA in the latest vscode insider. Make sure to turn up the volume:

https://user-images.githubusercontent.com/2931520/154960051-2eb08e68-9d57-4d19-b88a-15b6ce975b7e.mp4
