### ISSUE TITLE
Can we add a feature to quickly collapse folders like node_modules?

### ISSUE THREAD

**Issue by joshivaibhavs** [microsoft/vscode#142599]
When I click into a node module to check the source code/type definition, the explorer section (to the left side) expands the entire node_modules folder and I have to scroll all the way to the top to collapse that one folder, as I want the rest of the folders in the same condition that they were. For larger projects, this could take like half a minute of scrolling. It would be great if I could see the open folder pinned at the top, to be able to collapse it quickly.

**Comment by JacksonKearl** [comment]
Your best bet is using left arrow to go to the parent folder and collapse it. 

This issue could also be addressed by an existing ticket with a name like "auto reveal excludes" that I can not find at the moment.

**Comment by joshivaibhavs** [comment]
Thanks. :+1:
