### ISSUE TITLE
Save button permanently visible

### ISSUE THREAD

**Issue by FirstVertex** [microsoft/vscode#142575]
I'm tired of chasing the Save All button around.  I'm tired of always having to switch over to files to get to save all.  I'm tired of mistaking the tile horizontal button for the save all button.

The Save All button needs a permanent presence on the UI.  It's too important to bury under a tab.

**Comment by gjsjohnmurray** [comment]
Maybe there already an extension which does this.

If not, it's a good subject for you to build your first extension. See https://code.visualstudio.com/api which includes a pointer to a sample that adds a click able panel to the status bar.

Alternatively, commission an extension writer to do the job for you.
