### ISSUE TITLE
When I use @import on a sass file, aparently WSL disconnects, and it shows a window to reload the window

### ISSUE THREAD

**Issue by danielcaste1** [microsoft/vscode#142560]
Issue Type: <b>Bug</b>

1. create a sass file
2. use '@import' statement
3. try to add an url

VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:16:22.147Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Connection to 'WSL: Ubuntu' could not be established  Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3400G with Radeon Vega Graphics     (8 x 3693)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|12.94GB (8.44GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/danielsword/Cursos/sass --remote=wsl+Ubuntu --crash-reporter-id 12b7cab9-3fd5-4f07-90c8-c1b182325a2b|
|Screen Reader|no|
|VM|0%|

Connection to 'WSL: Ubuntu' could not be established  Canceled
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vs360cf:30404996
vsrem710:30416614
vscop841cf:30434590
vscscmwlcmc:30433760

```

</details>

**Comment by danielcaste1** [comment]
I just reinstalled WSL and It worked, maybe the error wasn't on VSCode

**Comment by bilaalukis** [comment]
Hi, this issue still occurs. I'm also not sure if this is a VSCode issue but as soon as I try to import anything into a sass file I get disconnected from WSL. Even when I try to reload the page and reconnect WSL it goes back to the same reload screen as soon as I open my sass file. 

Anyways, hoping to find a fix to this. Thank you!

VS Code version: Code 1.64.2
OS version: Windows_NT x64 10.0.19044

**Comment by danielcaste1** [comment]
> Hi, this issue still occurs. I'm also not sure if this is a VSCode issue but as soon as I try to import anything into a sass file I get disconnected from WSL. Even when I try to reload the page and reconnect WSL it goes back to the same reload screen as soon as I open my sass file.
> 
> Anyways, hoping to find a fix to this. Thank you!
> 
> VS Code version: Code 1.64.2 OS version: Windows_NT x64 10.0.19044

Yep, that is exactly the issue I had, as I said, I Just reinstalled WSL (without Docker) and problem solved, now I can import files on sass while being connected on WSL

**Comment by danielcaste1** [comment]
It's happening again 🙄

**Comment by danielcaste1** [comment]
Oh

> It's happening again 🙄

XD, Fixed again, It's because of Color Highlight extension, I unistalled it and now it works...

**Comment by meister0** [comment]
> Oh
> 
> > It's happening again 🙄
> 
> XD, Fixed again, It's because of Color Highlight extension, I unistalled it and now it works...

ty <3
