### ISSUE TITLE
make editor link detector more specific

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#142522]
We observed some code snippets in comment block (e.g. `opt.off`) are linkified. 
"editor.links" setting will disable vscode's default link detector but it will also
disable links completely (so, no link for https://vscode.dev).
Can we consider an option to linkify only those with schemes explicitly stated?

**Comment by hediet** [comment]
opt.off is not linkified for me:

![image](https://user-images.githubusercontent.com/2931520/153210979-213471b0-a113-4543-aac1-e70918c39d96.png)
