### ISSUE TITLE
Test Failure: environmentVariableCollection should respect clearing entries

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#142566]
```
  1) vscode API - terminal
       Terminal
         environmentVariableCollection
           should respect clearing entries:
     Error: Timeout: ~a1~ should be printed after 20 seconds.
Did not pass accept function
      at poll (D:\a\1\s\extensions\vscode-api-tests\src\utils.ts:167:10)
      at Context.<anonymous> (D:\a\1\s\extensions\vscode-api-tests\src\singlefolder-tests\terminal.test.ts:791:5)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=154847&view=logs&j=306b2268-2a17-5e97-ab97-f41a26dc5206&t=ad0cf992-b66d-54d3-7b97-28b0a2304eda

**Comment by JacksonKearl** [comment]
Again in release branch build 

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=154878&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=c55167a9-8752-5898-67fa-9d7c918c61b3

**Comment by Tyriar** [comment]
Skipped the suite on Windows only in https://github.com/microsoft/vscode/commit/339cbb38e268789e627ab4b3cc88b6dfa478d30a, will skip on all platforms if it fails again.
