### ISSUE TITLE
Unable to use some keyboard shortcuts while focused in terminal

### ISSUE THREAD

**Issue by RobbyCBennett** [microsoft/vscode#142555]
Since the January 2022 update that I received today, I can't hide/close the side panel while I'm focused on the terminal. The new command is `workbench.action.toggleAuxiliaryBar`. It seems that I can't do any simple keyboard shortcut while in the terminal, other than `workbench.action.focusLastEditorGroup`.

The following shortcuts work.

```json
{
	"key": "alt+t",
	"command": "workbench.action.focusLastEditorGroup",
	"when": "terminalFocus",
},
{
	"key": "ctrl+shift+w",
	"command": "workbench.action.toggleAuxiliaryBar",
	"when": "terminalFocus",
},
```

However, the following shortcuts don't work.
```json
{
	"key": "ctrl+w",
	"command": "workbench.action.toggleAuxiliaryBar",
	"when": "terminalFocus",
},
{
	"key": "alt+w",
	"command": "workbench.action.toggleAuxiliaryBar",
	"when": "terminalFocus",
},
```

I don't see a pattern here, so it looks like there might be multiple bugs. I can't use simple shortcuts sometimes, and other times I can.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64
- OS Version: Windows 10

Steps to Reproduce:

1. Assign one of the 2 broken shortcuts listed above.
2. Open a file
3. Focus on the terminal
4. Try to use the key

**Comment by sbatten** [comment]
@RobbyCBennett this is because Alt+w is being eaten by the terminal. You will need to add to the setting `terminal.integrated.commandsToSkipShell` => workbench.action.toggleAuxiliaryBar
