### ISSUE TITLE
Plot viewer window no-longer updates on file change

### ISSUE THREAD

**Issue by winni2k** [microsoft/vscode#142502]
Issue Type: <b>Bug</b>

When using vscode from windows over WSL2 with all extensions disabled:
1. Create two png images
2. Open the first image in vscode
3. In a terminal copy the second image to the location of the first image
4. switch back to vscode

- Expected behavior: vscode updates the image in the plot viewer
- Actual behavior: vscode does not update the image in the plot viewer
- Work around: switch to another tab away from the plot viewer and then switch back. The image now updates

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (11.62GB free)|
|Process Argv|--crash-reporter-id 04d22900-b60a-424a-bd06-d8c5583e064c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|24.88GB (22.32GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
stan-vscode|iva|0.2.3
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
vscode-singularity|onn|0.5.1
snakemake-lang|sna|0.1.6
jupyter-keymap|ms-|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vscop453:30404998
vsrem710cf:30416617

```

</details>

**Comment by winni2k** [comment]
Downgrading vscode to the previous release (November 2021 (version 1.63)) fixes this issue.

**Comment by mjbvz** [comment]
What is the plot viewer?

**Comment by winni2k** [comment]
I don't know. Whatever allows me to view a PNG file in vscode. A tab? A window? Or some other synonym of those words.

**Comment by winni2k** [comment]
#justausertryingtogetbye

**Comment by mjbvz** [comment]
It sounds like you are talking about the image view. To be sure though, 
does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by winni2k** [comment]
I don't know.

**Comment by mjbvz** [comment]
Please test it out. The links above include everything you need to try this
