### ISSUE TITLE
Debug not starting for Python suddenly

### ISSUE THREAD

**Issue by grpandi** [microsoft/vscode#142521]
We ha
Issue Type: <b>Bug</b>

Run and Debug not working/STarting. No error message. When click a short process happen to start Debug but stop in while.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.23GB free)|
|Process Argv|--crash-reporter-id 7a5fac78-a976-4c84-a44a-67891672fc9e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2022.0.1786462952
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
team|ms-|1.161.1
vscode-yaml|red|1.4.0
LiveServer|rit|5.7.4
python|tht|0.2.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30433058
pythonvs932:30410667
wslgetstartedc:30433508
vscop940:30404999
vsrem710:30416614

```

</details>

ve written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by ulucsahin** [comment]
I have the exact issue since friday. Started happening suddenly.
