### ISSUE TITLE
Test failure: parseServerConnectionToken // --connection-token-file:

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#142545]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=154737&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=0d55b56b-c0b2-5f64-1c6a-62c9163a0d5b

  1) parseServerConnectionToken
       --connection-token-file:

      Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      + expected - actual

**Comment by JacksonKearl** [comment]
Again (in addition to #142608) https://dev.azure.com/monacotools/Monaco/_build/results?buildId=155140&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=821d316a-2fa3-581f-c34c-57a961b8e328

**Comment by alexdima** [comment]
I really doubt that the 3 async fs operations take longer than 2s or 5s. My best guess is that there are other tests before that are not clean and leave async stuff to execute which ends up preempting these fs executions. I will change the test to use sync fs.

**Comment by sandy081** [comment]
This failed again - https://dev.azure.com/monacotools/Monaco/_build/results?buildId=158086&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=0d7e5bc9-922f-51dd-b06a-a90d0b9feeeb

**Comment by alexdima** [comment]
@sandy081 Sorry about that! But this is ridiculous! How is it possible that 3 sync fs operations in the test and 1 sync fs operation in the function being tested take longer than 2 seconds? Also, from the raw logs, it doesn't look like that particular test is actually taking 2s:

It looks like the entire `parseServerConnectionToken` suite takes 19ms:

```
2022-02-25T21:07:05.2537680Z   Normalization
2022-02-25T21:07:05.2539370Z     ✓ removeAccents
2022-02-25T21:07:05.2539780Z 
2022-02-25T21:07:05.2540290Z   parseServerConnectionToken
2022-02-25T21:07:05.2541340Z     ✓ no arguments generates a token that is mandatory
2022-02-25T21:07:05.2543340Z Breaking change in the next release: Please use one of the following arguments: '--connection-token', '--connection-token-file' or '--without-connection-token'.
2022-02-25T21:07:05.2545010Z     ✓ no arguments with --compatibility generates a token that is not mandatory
2022-02-25T21:07:05.2548470Z     ✓ --without-connection-token
2022-02-25T21:07:05.2550740Z     ✓ --without-connection-token --connection-token results in error
2022-02-25T21:07:05.2552120Z     ✓ --without-connection-token --connection-token-file results in error
2022-02-25T21:07:05.2553350Z     ✓ --connection-token-file --connection-token results in error
2022-02-25T21:07:05.2556800Z     1) --connection-token-file
2022-02-25T21:07:05.2557970Z     ✓ --connection-token
2022-02-25T21:07:05.2559630Z     ✓ --connection-token --compatibility marks a as not mandatory
2022-02-25T21:07:05.2560110Z 
2022-02-25T21:07:05.2560610Z   ResourceTree
2022-02-25T21:07:05.2561500Z     ✓ ctor
2022-02-25T21:07:05.2562430Z     ✓ simple
2022-02-25T21:07:05.2565390Z     ✓ folders with data
2022-02-25T21:07:05.2565810Z 
```

**Comment by alexdima** [comment]
@bpasero Do you have any ideas what is going on? IMHO the nodejs unit tests must be somehow misconfigured or mocha must be confused because this particular test appears to be very fast, yet it is being blamed for taking long than 2s.

**Comment by bpasero** [comment]
That is indeed weird, especially given that there are tons of node.js fs tests for our file system provider that all go down to disk and they seem to not timeout. 

I can only speculate that maybe this is not running in the same environment as it would run locally, i.e. the CI environment having a somewhat special file system that maybe virtual?

@lszomoru @deepak1556 how is our macOS Azure pipelines setup, is that a normal full VM or a real macOS machine?

**Comment by lszomoru** [comment]
> Agents that run macOS images are provisioned on Mac pros with a 3 core CPU, 14 GB of RAM, and 14 GB of SSD disk space. These agents always run in the US irrespective of the location of your Azure DevOps organization. If data sovereignty is important to you and if your organization is not in the US, then you should not use macOS images. [Learn more](https://docs.microsoft.com/en-us/azure/devops/organizations/security/data-location?view=azure-devops).

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#hardware

**Comment by bpasero** [comment]
@alexdima something really seems off with the node.js test runner, for example in this failing CI a test timed out for 2 seconds that is not even using any node APIs, nor is it async:

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=158472&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=1e8c3e2f-290b-5032-cda4-e76fc340a0f5&l=3579

Test:

https://github.com/microsoft/vscode/blob/0bc255b69262477c1975f5bfb3710399b567d4fc/src/vs/base/test/common/fuzzyScorer.test.ts#L630-L641

The test runner implementation is:

https://github.com/microsoft/vscode/blob/df645f14506142d6b20be6f6bda6bc40286ff739/test/unit/node/index.js#L193

And I think it originated from code you wrote a long time ago. I glanced over it but could not find something obvious that is done wrong in that file, at least from my understanding. Most code is around supporting to load our AMD modules I believe. 

A few things to note: we will update to a newer node.js version when we resume Electron 16 update, so maybe that helps. 

Our mocha version is `8.2.1`, but `9.x` has been released meanwhile.

**Comment by alexdima** [comment]
Most of the code in `test/unit/node/index.js` is about what AMD modules to load and then once the code is loaded, it basically calls `mocha.run()`. There's no custom test reporter or anything controversial that might have a bug there. Do you think the Electron unit tests have a longer default timeout than 2 seconds and that's why only the nodejs unit tests fail in this particular way?

**Comment by bpasero** [comment]
@alexdima oh yeah nice you found an actual difference!

Electron mocha setup:

https://github.com/microsoft/vscode/blob/eb4096228889a1263c860403ad1f85d0a6d80019/test/unit/electron/renderer.html#L38

We should probably align both to have same timeouts. 

Also web has 5000:

https://github.com/microsoft/vscode/blob/eecbd962ef68873795e21e0a00c4d70ee203246c/test/unit/browser/renderer.html#L36

**Comment by alexdima** [comment]
:+1: I've increased the timeout to 5000 via https://github.com/microsoft/vscode/commit/f52664a3a3b4a72b887e1985deeb3a451afefbcd
