### ISSUE TITLE
Alt key to toggle menu does not work after opening 'Release Notes' from Help menu

### ISSUE THREAD

**Issue by vijay-singh-16** [microsoft/vscode#142594]
Issue Type: <b>Bug</b>

if I use the setting shown below 

```
"window.titleBarStyle": "native",
"window.menuBarVisibility": "toggle"
```
and then open menu item: 'Help -> Release Notes', the 'Alt' key to toggle menu doesn't work until I restart VSCode.
This is 100% reproduceable on multiple machines.

Does this issue occur when all extensions are disabled?: Yes

Version: 1.64.1
Commit: d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
Date: 2022-02-07T17:16:22.147Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by mjbvz** [comment]
Duplicate of #121379
