### ISSUE TITLE
git.exe, pageant.exe, ssh.exe builds up over time

### ISSUE THREAD

**Issue by tonyeung** [Microsoft/vscode#1425]
Currently I have four of each process (git.exe, pageant.exe, ssh.exe) in my process manager (win 7 ent). I'm using vscode for diff handling and gitex for everything else. I tried not using gitex but push and pulls to github hangs through vscode. 

V. 0.10.3

**Comment by joaomoreno** [comment]
Closing, this should be resolved by now.
