### ISSUE TITLE
NVDA reads the markdown link in walkthrough as button instead of link

### ISSUE THREAD

**Issue by HuihuiWu-Microsoft** [microsoft/vscode#142589]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.1
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Install an extension with walkthrough contributed(in the walkthrough, there's markdown link inside like "[Google](https://www.google.com))". (ps, you can try our Teams Toolkit extension)
2. Start NVDA(screen reader) and tab to the walkthrough page, the 'Google' will be read as button instead of link

**Comment by Ashutoshsahoo164** [comment]
Hi @JacksonKearl Please dont close the bug until it is fixed. Please reopen the bug as it is required for tracking purpose.

CC : @HuihuiWu-Microsoft

**Comment by Ashutoshsahoo164** [comment]
#Visual Studio Code Client; #GH-TeamsToolkitExtension-Win32-Jan2022

**Comment by JacksonKearl** [comment]
In standard use the widgets behave as buttons, as they execute commands. Opening an `https://` link as the command is possible, but is not the standard use, thus this is as-designed.

**Comment by HuihuiWu-Microsoft** [comment]
> as they execute comma

Hi @JacksonKearl , does that mean it's not officially supported to use link as command? Then what is the standard use for opening links to make accessibility work?

**Comment by JacksonKearl** [comment]
I'm not sure I understand your question. The widgets are designed to run commands, thus they are labeled as such. We do not know if running the command will end up opening a link, so we can not adapt the label to represent that. While it would be theoretically possible to detect the special case of `https` url's, there are many other ways to open a link programmatically that we could not detect.
