### ISSUE TITLE
VSC latest version problem with intellisense and Suggestion

### ISSUE THREAD

**Issue by MrSmith9** [microsoft/vscode#142558]
I have update my vscode and now i can't use intellisense and Suggestion example: message.channel.send(). but on my vsc wont show like message............ nothing pop up suggestion. How i can enable it and Other way can downgrade vsc version?

**Comment by gjsjohnmurray** [comment]
Downgrade info is at https://code.visualstudio.com/docs/supporting/faq#_how-do-i-opt-out-of-vs-code-autoupdates

But before you do that, try the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by MrSmith9** [comment]
> 

Thank you for reply, I don't have any Extension but only SSH Remote that all.. but i have been test to remove SSH Remote still issues. So i have try downgrade and still issued. I can see suggestion only in like index.js work fine but if am use in commands example ping.js, It's wont show suggestion or intellisense too.

**Comment by MrSmith9** [comment]
First one picture, it's in index.js work can see intellisense but not in commands. see second picture.
![1](https://user-images.githubusercontent.com/63478559/153090655-e9229e18-e623-4049-826a-e9c89d464cf1.PNG)

![2](https://user-images.githubusercontent.com/63478559/153090726-630be63c-4771-4099-9ec1-246686fc2f31.PNG)

**Comment by MrSmith9** [comment]
Fixed it. My bad...
`const { Client, Message } = require('../../index.js')` change to `const { Client, Message } = require('discord.js')`

**Comment by MrSmith9** [comment]
It't went back again and it's not show like 2nd picture. How i can fix it?

**Comment by MrSmith9** [comment]
<html>
<body>
System Information


CPUs | Intel(R) Core(TM) i7-6820HK CPU @ 2.70GHz (8 x 2712)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 23.96GB (18.39GB free)
Process Argv | --crash-reporter-id b376507f-6d99-4f16-9f3a-c09687cee2a2
Screen Reader | no
VM | 0%


</body>
</html>

<html>
<body>


Extension | Author (truncated) | Version
-- | -- | --
remote-ssh | ms- | 0.70.0
remote-ssh-edit | ms- | 0.70.0


</body>
</html>

**Comment by MrSmith9** [comment]
I have test TypeScript and JavaScript same wont show intellisense and suggestion option too..

**Comment by MrSmith9** [comment]
Close this issues. Solved...
