### ISSUE TITLE
Does not execute the latest code

### ISSUE THREAD

**Issue by john-2016** [microsoft/vscode#142580]
After I modify the code (saved), when I execute the code on the command line, the command line does not execute the latest code.

**Comment by gusbemacbe** [comment]
It happened on both VSCode Insiders and Explorations. I suspect the problem be dated to the https://github.com/microsoft/vscode/pull/137241, pulled by @deepak1556 and merged by @bpasero.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

You haven't said what coding language.

Please provide simple repro steps.

**Comment by gusbemacbe** [comment]
> /needsMoreInfo
> 
> You haven't said what coding language.
> 
> Please provide simple repro steps.

I didn't write nothing. I just open and it closed. I checked on the terminal, it said a segmentation fault. 

I downgraded to the old version and it open.

**Comment by gjsjohnmurray** [comment]
What platform are you running VS Code on?

**Comment by gusbemacbe** [comment]
> What platform are you running VS Code on?

Arch Linux.

**Comment by deepak1556** [comment]
@gusbemacbe the issue you are facing is tracked in https://github.com/microsoft/vscode/issues/142574, will be fixed in next insiders release.
