### ISSUE TITLE
Terminal description should not include cwdFolder for tasks

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#142633]
As it's already included in the title
![Screen Shot 2022-02-09 at 8 18 11 AM](https://user-images.githubusercontent.com/29464607/153219538-4f1e0562-4788-4ba9-81f6-d5ee5ede7b8e.png)

**Comment by meganrogge** [comment]
@alexr00 the fix I pushed will get rid of the `cwdFolder` in the description.

@Tyriar and I were rethinking this and wondering if it looks better in the description and not in the title.

Thoughts?
![Screen Shot 2022-02-09 at 2 35 11 PM](https://user-images.githubusercontent.com/29464607/153285605-f7ef912d-aa50-44b0-9054-910d02636117.png)

**Comment by Tyriar** [comment]
Just thought of an extra complication that this would only show up on mac/linux or when shell integration is enabled on Windows. Maybe we should shelve this discussion until shell integration is more widely used?

**Comment by alexr00** [comment]
I agree that for now we should maintain consistency between mac/linux and Windows.
