### ISSUE TITLE
tasks incorrectly assume yarn is being used with npm workspaces with subfolders

### ISSUE THREAD

**Issue by Alloyed** [microsoft/vscode#142653]
Issue Type: <b>Bug</b>

related to  #139654. In my case I'd like to use vscode directly from the subfolder for each individual package, to customize the default build tasks and limit the scope of autocomplete.

repro steps:

clone https://github.com/wixplosives/sample-monorepo
nvm use 16
`npm i` inside root folder ("sample-monorepo")
open vscode on subfolder (eg. "packages/app")
launch any script from "npm scripts" panel

observed result:
task is run using yarn, which will fail if not installed

expected result:
task is run using npm

VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:16:22.147Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by alexr00** [comment]
Have you tried setting `"npm.packageManager": "npm"`? Our auto package manager detection is good, but not perfect.

**Comment by Alloyed** [comment]
yep, manually specifying works perfectly as a workaround. Thanks for bringing that option to my attention!
I'd be totally ok with closing the issue if this is just the limit of autodetection.
