### ISSUE TITLE
Commits list view screen cheese

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#142655]
Version: 1.65.0-insider (Universal)
Commit: f8c36556a2c305327f5417dc7f93220f39ed608f
Date: 2022-02-08T09:50:40.699Z (1 day ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0

Not sure how it ends with this state

<img width="380" alt="image" src="https://user-images.githubusercontent.com/876920/153262001-31e1802a-b0bd-4dbc-9733-1a704364b846.png">

**Comment by joaomoreno** [comment]
@rebornix Which extension contributes the COMMITS list?

**Comment by alexr00** [comment]
I spent some time trying to a tree view into this state, but I wasn't able to repro it. Maybe related to d0500b3f52132a7ec3bbbc231930c053e4c79e9c, I'll keep looking.

**Comment by alexr00** [comment]
I'm still unable to repro this. @eamodio have you had any reports of this kind of issue in GitLens? If not, I'll close this as no-reproducible until we get a second report of the issue.

**Comment by eamodio** [comment]
@alexr00 I don't think I've seen any. Close away 👍
