### ISSUE TITLE
Feature Request: flip order of alluded path

### ISSUE THREAD

**Issue by jimsnab** [microsoft/vscode#142635]
Inside panels such as Search, the directory of a file is shown in a small font, with ellipsis when the path doesn't fit. For me, the path pretty much never fits.

The more meaningful part of the path tends to be the end of it. Unfortunately this is usually hidden for me, and getting the mouse pointing to the tiny font to see the full path with a tool tip is a bit annoying. Widening the pane to show the full path eats precious screen real estate.

I propose flipping the truncation to keep the right side of the path text instead of the left. Alternately, place the ellipsis in the middle.

Given a hypothetical path in find results such as `tf-layers-gcp-hashicorp-vault/src/layers/app/data-sources.tf`

Instead of

```
data-sources.tf tf-layers-gcp-hashic...
```

How about showing

```
data-sources.tf ...orp ▪ layers ▪ app
```

or second best

```
data-sources.tf tf-laye...yers ▪ app
```

or wouldn't it be cool if vscode picks which side to truncate based on most uniqueness in the overall list of matches.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/74637 for a related discussion, but we display paths in this way pretty much everywhere in vscode. You may be interested in search editors, and we also have an issue to display search results in a tree view, which I can't find righ tnow
