### ISSUE TITLE
Variable selection is moved after entering a code snippet

### ISSUE THREAD

**Issue by 4kochi** [Microsoft/vscode#14265]
- VSCode Version: Version 1.7.0-insider (788caba5a3ca1c2b137353f4384bb0e026db1a31)
- OS Version: macOS 10.12 (16A323)
- TypeScript Version: 2.0.3

Steps to Reproduce:
1. Have a folder with a `jsconfig.json`
2. Use a Snippet in a `.js` file

The code from the snippet is inserted but the selection to enter the variable is moved so then when waiting to long the body of the snippet overwritten by the input.

Here is a gif with problem:

![snippet error](https://cloud.githubusercontent.com/assets/1742426/19639999/0d05cb4c-99db-11e6-8807-3f4dbd0af62e.gif)

Here is the code of the snippet: 

```
"Print to console": {
  "prefix": "cc",
  "body": [
    "console.log('${data}');",
    "console.log(${data});",
    "$0"
  ],
"description": "Log output to console"
}
```

Here is the `jsonfig.json`

```
{
    "compilerOptions":{
        "target": "ES6",
        "module": "commonjs"
    },
    "exclude": [
        "node_modules",
        "build"
    ]
}
```

Side note: The snippet works fine in TypeScript.

**Comment by alexandrudima** [comment]
@4kochi I could not reproduce (in JavaScript):

![snippet](https://cloud.githubusercontent.com/assets/5047891/19656529/ac3e4e42-9a20-11e6-9993-11968a537e42.gif)

**Comment by 4kochi** [comment]
I see. It is curious. I the same `.js` file it works in some cases, but not always. I can't see the pattern when it's not working. The only thing I noticed is that when it does not work the code is indented. I use 4 spaces.

**Comment by 4kochi** [comment]
It also works when I copy the content of the file in a new VSCode Window and select JavaScript as file type. So there is not `jsonfig.json` in this case.

**Comment by alexandrudima** [comment]
Do you maybe have format on type enabled?

**Comment by 4kochi** [comment]
Yes, `"editor.formatOnType"` is enabled. But disabling this settings does not help.

**Comment by alexandrudima** [comment]
I believe there is another party that is automatically editing the file after the snippet is inserted (editing the actual snippet text or something around the snippet text) that causes the cursors to lose their positions and for the snippet mode to be left.

Can you please try with `code --disable-extensions`

**Comment by 4kochi** [comment]
It works when the extensions are disabled. But it also works now with the extensions. I have updated to the new insider version this morning (5bafcdb3d67b29b1f4667a3f497ac05a41dde667).

I will look if it's work from now on and when there is a problem again, I will try make the steps reproduceable.

**Comment by 4kochi** [comment]
The problem is back. All extensions are disabled and also `"editor.formatOnType"` is set to `false`. The interesting thing is that it works when the is not indention. But when the the snippet is nested, it does not work correctly. 

```
console.log('data'); // works
console.log(data);

function demo(){
    console.log('data'); // does not work
    console.log(data);
}
```

**Comment by alexandrudima** [comment]
@4kochi Here is what I tried, without success, to reproduce:

* I am on the insiders version from 2hrs ago.
* added the snippet to JavaScript:
```json
"Print to console": {
  "prefix": "cc",
  "body": [
    "console.log('${data}');",
    "console.log(${data});",
    "$0"
  ],
"description": "Log output to console"
}
```
* created a new empty folder
* added jsconfig.json:
```json
{
    "compilerOptions":{
        "target": "ES6",
        "module": "commonjs"
    },
    "exclude": [
        "node_modules",
        "build"
    ]
}
```
* commented out all of my user settings

Thanks for your patience, maybe there is some other factor ?

![snippet](https://cloud.githubusercontent.com/assets/5047891/19683408/5d5f8574-9ab2-11e6-8d63-5b9bf93ce796.gif)

**Comment by 4kochi** [comment]
I think I found something. I have the setting `"files.autoSave": "afterDelay"`.

If I set it to `off`, the problem disappears. If I then save directly after the snippet is inserted, the selection is moved again.

**Comment by alexandrudima** [comment]
Could it be that you have format on save enabled in user settings or in workspace settings or that you have an extension that formats on save. Otherwise, is there a file watcher running that might modify the file outside of vscode?

**Comment by 4kochi** [comment]
No, format on save is false and there are no external file watchers. I will try again with all extensions disabled.

**Comment by alexandrudima** [comment]
In that case, it is most likely you have an extension that listens to the save event and then **edits** the text.

**Comment by 4kochi** [comment]
I guess that's the case. I will try to find out which extension it might be.

**Comment by alexandrudima** [comment]
Closing after a number of days without a response
