### ISSUE TITLE
FR: Create views with Markdown

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode#142617]
Hi,

I was wondering if would be possible to allow extensions to create views using Markdown.
Sometimes it is useful to show the user content / information as part of an extension, but a treeview is not well suited to the data and a webview can feel like overkill.

> Webviews are pretty amazing, but they should also be used sparingly and only when VS Code's native API is inadequate. Webviews are resource heavy and run in a separate context from normal extensions. A poorly designed webview can also easily feel out of place within VS Code.

It is possible for an extension to provide markdown views indirectly by setting the welcome content, but this does not allow the content to be dynamic at all, or to have one markdown view alongside other views.

Implementation wise, the main issue is that every view is a treeview, but it is relatively simply to support markdown if we expose `domNode` on src/vs/workbench/common/views.ts. Alternatively, it could be created to float over the treeview and track its position like a webview does.

**Comment by alexr00** [comment]
> It is possible for an extension to provide markdown views indirectly by setting the welcome content, but this does not allow the content to be dynamic at all, or to have one markdown view alongside other views.

You can change the welcome content by changing the context specified in the `when` https://code.visualstudio.com/api/references/contribution-points#contributes.viewsWelcome.  You can also contribute multiple views to the same view container, where one has welcome content and other do.

**Comment by a-stewart** [comment]
> You can change the welcome content by changing the context specified in the when https://code.visualstudio.com/api/references/contribution-points#contributes.viewsWelcome.

This only works if you know the content ahead of time. One example could be if there is a desire for a welcome screen that allows you to select something and would like to provide the option to choose from a few "recent options" which are generated dynamically.

A webview allows for this fairly conveniently, but if you only want something very basic then a webview can be overkill.
