### ISSUE TITLE
Unresponsive debugger

### ISSUE THREAD

**Issue by epaezrubio** [Microsoft/vscode#14261]
- VSCode Version: 1.6.1 (latest)
- OS Version: Windows 10 Pro

Steps to Reproduce:
1. Start nodejs debugger
2. Make the code reach a breakpoint or an exception

After waiting some seconds waiting for the debugger to respond, I get a new tab of the file which stopped the execution labeled with the absolute path to the file. In the editor the content of the file is not displayed, instead it shows: _Could not retrieve content_ . The call stack and variables seem to be correct, I am just not able to see the file content and debug properly.

There is no error in the developer console, and I am having this error since I updated to 1.6.1

**Comment by epaezrubio** [comment]
I made a fresh installation of the newest version (1.7.1) and it worked as a charm 👍 You can close the issue or investigate it if you prefer, but it's solved for me.

**Comment by weinand** [comment]
@epaezrubio great to hear, thanks!
