### ISSUE TITLE
Terminal is firing 'default responses', while none is defined

### ISSUE THREAD

**Issue by bencresty** [microsoft/vscode#142601]
The latest version of VS Code keeps trying to use automatic responses while no response is ever set.

Being able to use automatic responses is nice and all, but it should never use auto responses when not set. So be off per default. For some reason it's either not disabled per default or there's an issue with it.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.0
- OS Version: Windows 10 build 19042.1466

Steps to Reproduce:

1. run command `pnpm install` from the build in terminal (set to powershell)
2. vs code is reacting with a `Y` to the return
3. vs code is reacting again with a 'Y' to the return of the first time the command throws a message that `Y` is not recognized as a command
4. so this warning shows two times
![image](https://user-images.githubusercontent.com/69322733/153166969-3ad95165-a6a1-4983-bca4-eb458befd2b9.png)

BTW the `pnpm` installation here has not be renewed lately, so it's definitely no change in the command itself.

**Comment by gjsjohnmurray** [comment]
See #142432 which will arrive in 1.64.2

/duplicate

**Comment by bencresty** [comment]
@gjsjohnmurray  thanks. I did search for it, but couldn't find any issue on this. Great to see it's fixed and will be merged later.
