### ISSUE TITLE
JS debug terminal doesn't get name restored on revive

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#142632]
![image](https://user-images.githubusercontent.com/2193314/153212853-57add6b1-0d22-4b0e-afd1-4af3f7a7d486.png)

After restart:

![image](https://user-images.githubusercontent.com/2193314/153212895-67953f82-76cd-4fdc-b7ce-856bd8434175.png)

It does keep the name after reload.

We should disable persistence all together in https://github.com/microsoft/vscode-js-debug/issues/1196, but this is a bug we should fix for extension-launched(?) terminals.

**Comment by Tyriar** [comment]
Root cause is because TerminalInstance fires onTitleChanged a few times which end up syncing with the pty host.

**Comment by meganrogge** [comment]
Marking this as verified because now these don't persist so this issue is no longer relevant https://github.com/microsoft/vscode-js-debug/issues/1196
