### ISSUE TITLE
Japanese IME suggestion list flickers

### ISSUE THREAD

**Issue by roargiol** [microsoft/vscode#142684]
Issue Type: <b>Bug</b>

When using Japanese IME to type, the window that shows word predictions flickers every time you type a new character, resulting in a really bad typing experience.

This didn't happen up until a few days ago, and does not happen on other Microsoft apps as far as I could check.

VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:16:22.147Z)
OS version: Windows_NT x64 10.0.22538
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (15.49GB free)|
|Process Argv|--crash-reporter-id 31a782c1-4f23-42a9-8d6c-52472eddc8b7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2021.12.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vs360:30404995
vsrem710cf:30416617

```

</details>

**Comment by alexdima** [comment]
@roargiol Could you please record and post here the flickering ?

**Comment by roargiol** [comment]
https://user-images.githubusercontent.com/64945957/154279716-c11639d8-81a6-419f-b39b-58bf8647f884.mov

Hi @alexdima, I've uploaded a video in which I reproduce the issue. Please kindly have a look.

**Comment by alexdima** [comment]
Thank you for the video. Let's track in https://github.com/microsoft/vscode/issues/142155

**Comment by roargiol** [comment]
Thank you!
