### ISSUE TITLE
OAuth flow is broken

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#142666]
1. Open VS Code with a fresh user data dir
2. Run `Git: Clone`, pick `Clone from GitHub` to follow the GitHub OAuth
3. Let the browser call into VS Code

🐛 VS Code handles the URL in a new window, instead of the original one

**Comment by joyceerhl** [comment]
I can repro the above in Insiders, additionally in OSS I get an error modal 
![image](https://user-images.githubusercontent.com/30305945/153297816-0d696d2b-07d9-4725-822a-c1b0fe6957c1.png)

**Comment by yume-chan** [comment]
See #142685, looks like the protocol handler is broken.
