### ISSUE TITLE
launch.json option for debugpy.debug_this_thread()

### ISSUE THREAD

**Issue by dakotajunkman** [microsoft/vscode#142657]
Currently, to debug Python scripts called by external applications (e.g. Python being called by MATLAB) it is necessary to import debugpy and call debugpy.debug_this_thread() at the top of the file. I am proposing a launch.json option that handles this, or some other way to no longer need to manually add this statement to a Python script in order to properly debug.

**Comment by weinand** [comment]
VS Code knows nothing about Python.
