### ISSUE TITLE
Markdown cells not displaying properly

### ISSUE THREAD

**Issue by Inspired1601** [microsoft/vscode#142650]
Issue Type: <b>Bug</b>

The bug appears randomly. While working with a Jupyter Notebook, I sometimes find that some cells are only partially displayed. Some of them lose their title, others disappear completely. Instead, an empty space remains on the screen. If you double-click on this empty space, the cell opens in edit mode. But after leaving the edit mode, the cell does not always start to display correctly.

Moreover, sometimes in split screen mode, the same cell is displayed correctly in one panel, but incorrectly in another (see screenshot below).

![image](https://user-images.githubusercontent.com/47291029/153246708-fe4fa222-c5d9-4211-804f-a1ab7a0661f7.png)

Extension version: 2022.1.1001775990
VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.94GB (2.87GB free)|
|Process Argv|--crash-reporter-id b0a3d91a-b073-470a-8715-c873fe3c9feb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30435083
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30433058
pythonvs932:30410667
wslgetstarted:30433507
vscop453:30404998
vsrem710:30416614
vscop841cf:30434590

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

If so, can you please share a notebook that demonstrates this issue so we can investigate?
