### ISSUE TITLE
Side Panel

### ISSUE THREAD

**Issue by nksfrank** [microsoft/vscode#142612]
Issue Type: <b>Bug</b>

Steps to reproduce:
Dragging "Search" from left Side Panel over to a new Side Panel on the right.
Dragging "Source Control" from Left Side Panel over to bottom half of Right Side Panel.
Dragging "Search" from Right Side Panel back to Left Side Panel.

What happens:
Right Side Panel disappears completely, hiding "Source Control" panel.

![vs_code_panel](https://user-images.githubusercontent.com/7352072/153181325-1040815f-4fae-4b22-8101-09d5a9c157dd.gif)

VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:16:22.147Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vscop940:30404999
vsrem710cf:30416617

```

</details>

**Comment by gjsjohnmurray** [comment]
This is as designed. When you drop Source Control below Search you are adding it to the Search tab. So when you later drag the Search tab back to the left, both SEARCH and SOURCE CONTROL move, leaving the side panel empty.

Change your 3rd step so you drag the SEARCH view header over to the left, not the magnifier tab which represents the view **container**.

**Comment by sbatten** [comment]
@gjsjohnmurray describes this exactly, thank you
