### ISSUE TITLE
Escape key removes focus from filter search bar when in problems/debug console panels

### ISSUE THREAD

**Issue by simonalford42** [microsoft/vscode#142698]
Typically pressing escape will remove focus from the search bar back to the main area of the application.
However, this is not the case for the filter search bar in the problems pane.
In the problems panel, I would like pressing escape to change focus from the filter search bar back into the filter view. This would mirror the way escape typically closes search bars, for example called by command-F in the editor.
The same thing would apply to the debug console panel,  whose filter search bar also doesn't lose focus when pressing escape. 

I tried adjusting the keyboard shortcut to do this with the following in my keybindings.json, but it didn't work:
```json
{ "key": "escape",
  "command": "problems.action.focusProblemsFromFilter",
  "when": "problemsFilterFocus" },
```

**Comment by sandy081** [comment]
You can set ESC key for the following command `problems.action.focusProblemsFromFilter` which will move focus to the main problems panel.

**Comment by simonalford42** [comment]
Even if it is possible to do this with a shortcut, I think it would be a sensible default behavior, so that the search bar in the Problems and Debug panel view behaves the same way as the search bar in the editor, terminal, and other views, and goes away when pressing escape. What do you think?

As I mentioned in my original post, I have indeed tried to do the shortcut, and it did not work. From the keyboard shortcuts troubleshooting log, it looks like escape events are instead being registered as control or meta keypresses when in the problem panel filter search bar. I will create a separate issue to determine what is going on with this bug.

**Comment by sandy081** [comment]
You are right that following keybinding is not working

```
{ "key": "escape",
  "command": "problems.action.focusProblemsFromFilter",
  "when": "problemsFilterFocus" },
```

**Comment by simonalford42** [comment]
Thank you for the response and willingness to investigate, I appreciate it. Let me know if I can help.

**Comment by simonalford42** [comment]
On a related note, it appears that pressing escape after using cmd + E to "find with selection" does not close the search bar, whereas doing so after using cmd + F does.
