### ISSUE TITLE
Test: allow to navigate in navigation locations

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#142647]
Refs: https://github.com/microsoft/vscode/issues/27112

- [x] anyOS @kimadeline
- [x] anyOS @dbaeumer
- [ ] anyOS @chrisdias (Optional)

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23142647%0A%0A&assignees=bpasero)

---

We always provided methods to navigate through editor locations via "Go Back" and "Go Forward". These locations are being put on stack based on changing editors and changing text selection (i.e. moving the cursor with mouse or keyboard). 

This milestone we introduce a new navigation stack that works similar to the existing one but only navigates between locations that have been added from navigation commands such as "Go to definition". This navigation will ignore any changes to selections done via keyboard or mouse interaction and only navigate between these dedicated locations.

**Note:** if you run with `--verbose` you can see the history navigation stack by searching for `[History` in the console:

![image](https://user-images.githubusercontent.com/900690/153216328-b5a7aaab-d36f-4392-8af9-f82eeff9ae8a.png)

**Testing**
* accumulate navigation locations across same editors and different editors, for example
  * "Go to definition"
  * Problem marker
  * Symbol (via quick pick or outline)
* make sure you can navigate along these locations with the new actions
  * "Go back in navigation locations"
  * "Go forward in navigation locations"
  * "Go previous in navigation locations" (this toggles between previous and current location)
  * "Go to last navigation location"
* verify that when you click away from a navigation location to select another place in text, the navigation actions will put you first to the current entry of the stack (except for "Go to last navigation location" that will always put you to the last) [1]

**[1] example:** you navigate around editors with commands such as "Go to definition". When you now change the selection in the editor and select "Go back in navigation locations", we want to go back to the last definition that was selected and not the one before that.

**Comment by dbaeumer** [comment]
Works as advertised :-)

**Comment by kimadeline** [comment]
Works for me! 🥳
