### ISSUE TITLE
Side Panel closes when views context keys are slow to activate breaking restore

### ISSUE THREAD

**Issue by cedbesafilm** [microsoft/vscode#142610]
Does this issue occur when all extensions are disabled?: Yes/No

Versione: 1.64.1 (user setup)
Commit: d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
Data: 2022-02-07T17:16:22.147Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
Sistema operativo: Windows_NT x64 10.0.22000

Steps to Reproduce:

First bug: on restart vscode hide side panel
1. Enable side panel
2. Exit and restart vscode
3. Side panel is hidden, we have to enable again from menu

Second bug: the view on sidepanel disappear after restart
1. Enable side panel
2.  Move a view on side panel
3.  Exit and restart vs code
4.  Side panel is hidden , enable it
5. At this moment, the view is not show in side panel and from contextual menu in the activity bar

**Comment by gjsjohnmurray** [comment]
I can repro the first, but not the second.

/assign @sbatten

**Comment by cedbesafilm** [comment]
> I can repro the first, but not the second.
> 
> /assign @sbatten

I had move Maven and Testign view on side panel, on restart randomly no view or one view at time is visible on side panel, but when a view is not visibile on side panel there is no way to use it except from the command palette

I had to uninstall completely vscode and reinstall from scratch to return to normal functionality (but for now i'm not using side panel)

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/142382#issuecomment-1031321173 for how to add a title bar control that should help.

**Comment by sbatten** [comment]
@cedbesafilm can you please provide a gif of the experience? both repros please. 

also, if you ever lose a view due to drag and drop and don't want to re-install ,you can run the command `Reset View Locations`

**Comment by cedbesafilm** [comment]
for the second bug I think I understand why

in the same workspace I have java and angular projects

if I open the angular project first, the maven and test views open to me as a result, and when I switch to the angular project, these remain open anyway

while if I restart vscode and step directly to the angular project the maven and test views are not displayed until I open a java file

**Comment by sbatten** [comment]
@sandy081 dug into this today. the conditions of this issue are as follows:

1) An extension contributes a view with a when condition 
2) The when condition is set by the extension (requires full activation)
3) The user moves the view to the side panel (or panel) with no other views or view containers present in the part

When we load, the extension has not yet set the context to show the view, so the part hides.

One thought I had was to allow the panel to stay visible even if it has no views. Both parts have explicit actions for hiding them. But ideally we could workaround this without flashing. But the knowledge is well out of reach of the views themselves (controlled by the extension).

Thoughts?

**Comment by enoguchi-lmi** [comment]
yup have same issue, I am using the right side panel for npm scripts but it disappears on reload, So I just added the search panel to the right and now it works as it takes some time for the npm scripts panel to kick in

**Comment by sandy081** [comment]
@sbatten This is tricky. I am not sure what is the right way to go here because any approach would have drawbacks. Best would be to leave side panel open on reload instead of hiding it.

**Comment by JacksonKearl** [comment]
Verified with the JSON outliner in tree view sample 👍
