### ISSUE TITLE
[Feature Request] Synchronize changes key binding

### ISSUE THREAD

**Issue by abarisic86** [Microsoft/vscode#14266]
- VSCode Version: Version 1.6.1 (1.6.1)
- OS Version: Mac OS.X El Capitan 10.11.6

Steps to Reproduce:
1. https://code.visualstudio.com/docs/customization/keybindings
2. There is no way to set binding for "Synchronize changes" (lower left corner)

Future state:
1. Use ctrl + shift + G to go to Git page
2. Write commit message
3. Use command cmd + enter to close commit message
4. Use ctrl + shift + Y to synchronize changes

**Comment by ChristianAlexander** [comment]
As far as I can tell, this should be possible with [`workbench.action.git.sync`](https://github.com/Microsoft/vscode/blob/4482704deb34590b1599bfe20b6cdfe4268fe775/src/vs/workbench/parts/git/browser/gitActions.ts#L1148).

Perhaps [the keybindings page](https://code.visualstudio.com/docs/customization/keybindings) should be updated to tell users to check the "Here are other available commands" section of the `Default Keyboard Shortcuts` window.

This option is in the list of available commands:
![default keyboard shortcuts 1 6 1](https://cloud.githubusercontent.com/assets/6108845/19878433/9d157898-9fa5-11e6-86cb-7ed8b2ec7d04.png)

**Comment by joaomoreno** [comment]
Thanks @ChristianAlexander !
