### ISSUE TITLE
Status bar no longer shows pending build

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#142615]
Running the default build task no longer shows progress for me.

**Comment by alexr00** [comment]
Thanks for catching this so quickly! A change to make resolving dependent tasks revealed this bug in the npm task provider. The bug occurs when all of the following are true:
- The task is an npm task
- The task is a `dependsOn` task of the task that was executed
- The task is configured in tasks.json without a `group`
- The task has the word "build" in the script name
