### ISSUE TITLE
Intellisense/OmniSharp stops working

### ISSUE THREAD

**Issue by widL** [Microsoft/vscode#14262]
- VSCode Version:
Version 1.7.0-insider
Commit 43e46ab67f3bc70490b5e8348cde431dca036397
Date 2016-10-24T06:19:39.417Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0

- OS Version: Ubuntu 16.04 with kernel 4.6.0

Steps to Reproduce:

1. Open any project. OmniSharp works fine for a few seconds up to a minute (different every time).

When it stops working, the "# references" labels above the methods disappear, and when I press ctrl+space anywhere, it just says "Loading..." and nothing happens. The OmniSharp log doesn't give any hints, it simply stops outputting. I'll attach the [omnisharp log](https://github.com/Microsoft/vscode/files/547281/omnisharp_log.txt) of a typical run, where I just opened the project and pressed ctrl+space until it stopped working.

I also have the same issue as #14223. May or may not be related?

**Comment by widL** [comment]
This should get a Linux tag. Just tried the same project in Windows, and everything works perfectly!

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#836

**Comment by luyzfernando** [comment]
It was the same with me.

After installation of version 1.5.0-beta4 the problem was solved

https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.5-beta4
