### ISSUE TITLE
Notebooks - Add support of minimap

### ISSUE THREAD

**Issue by macsunmood** [microsoft/vscode#142645]
Have to recreate this topic, since the previous issues were recursevly closed.
It would be great to have minimap support on Notebooks.

**Comment by rebornix** [comment]
We have this on our roadmap, thanks for sharing your interest on this. May I ask what you would expect from the Minimap for notebook? It would be great if you share what you wish to see on the roadmap, how to interact with it etc to help us better understand it (despite the technical challenge to make it happen)

**Comment by claudiaregio** [comment]
@rebornix Adding my thoughts here since I've wanted this for a long time 😛 I was hoping the minimap would also include mini versions of the rendered outputs so i could navigate to outputs that way. The outline/table of contents doesnt really cut it for this because I dont have a memorized mapping in my head of what output was under which markdown header.

**Comment by rebornix** [comment]
@macsunmood thanks for the detailed feedback. A short summary of what you and @claudiaregio mentioned:

* Table of contents (similar to how Xcode handles it)
* Mini version of outputs
* Zoom Preview

Including outputs in Minimap can be challenging (not low hanging and that's probably why no other editors experiment with this idea yet) but we can start from exploring showing markdown previews, code, and placeholders for outputs, and then offer easier preview and navigation of table of contents through the Minimap.

**Comment by macsunmood** [comment]
@rebornix 
Can't the output be displayed in Minimap just schematically, with simple rendering, similar to the existing option for text? The main need is hotspot navigation, rendering quality could be plays no big role in this case. To be fair, I'm not familiar with how XCode handles ToC, as you've mentioned, but navigation of Table of Contents through the Minimap **would be awesome**!

**Comment by macsunmood** [comment]
@rebornix hi! Are there any updates on this ?

**Comment by rebornix** [comment]
Let's merge this issue in https://github.com/microsoft/vscode/issues/115266. Thanks for all the input.
