### ISSUE TITLE
Smart Code Snippets (Complete the feature please)

### ISSUE THREAD

**Issue by aminchoroomi** [Microsoft/vscode#14269]
- VSCode Version: 1.6.1
- OS Version: 10.0.14393

Code Snippets as you already know are very important in terms of coding speed. Now code snippets are supported in VS Code but have a little issue. I'll try to show it with one example.

When you type `prop` in C#, then press `Tab` it will result to 
`public int PropertyName { get; set; }` and that's fantastic.

But if you type `for, if, while`, or any keyword that is both code snippet and c# known keyword, you cannot access the snippet by pressing `Tab`. Instead, you have to scroll to the snippet of that keyword in the intellisense menu, then press `Enter` to get the result.
![issue-1](https://cloud.githubusercontent.com/assets/1765653/19642491/75c315ba-99f2-11e6-9971-b5f4f749da03.jpg)
![issue-2](https://cloud.githubusercontent.com/assets/1765653/19642492/75c6c192-99f2-11e6-8ba1-02bff43b492f.jpg)

**Comment by kaiwood** [comment]
There's a setting you can put in your preferences for this:

    "editor.snippetSuggestions": "top"

If set, the snippets come always first in the suggestion list.

**Comment by jrieken** [comment]
Joining @kaiwood on this. There is the aforementioned property to change the sort order for snippets (default is bottom) and then there is also tab completion. You can turn off 24x7 IntelliSense and enable tab completion to expand snippets just by pressing tab, like so:

```
"editor.tabCompletion": true,
"editor.quickSuggestions": false
```
