### ISSUE TITLE
Scrolling in the terminal completely skips ~10 lines

### ISSUE THREAD

**Issue by swantzter** [microsoft/vscode#142616]
Issue Type: <b>Bug</b>

## Steps to reproduce:

1. make some terminal output so you can scroll
  ```console
  cat > rows <<EOF
  #!/usr/bin/env bash
  
  for f in {1..1000}
  do
    echo $f
  done
  EOF
  chmod +x rows
  ./rows
  ```
2. Scroll the terminal one ratchet on your mouse, it'll scroll up like 30-40 lines

| before | after |
| --- | --- |
| ![screenshot 1644403972](https://user-images.githubusercontent.com/10356719/153186119-6638b63c-0360-4f82-8d9b-9086dc914a91.png) | ![screenshot 1644403980](https://user-images.githubusercontent.com/10356719/153186204-e8231da5-dd2d-4da3-af68-caeb3eef475a.png) |

This might have something to do with my settings, but it only occurs in VSCode's terminal which leads me to believe it's some weird clash between those things. (for reference it works fine in Windows Terminal where it scrolls the configured (in windows settings) 5 lines)
I've been hacing this issue for some months now.

The issue persists with all extensions disabled

## Settings

For reference, I believe these are my relevant settings and setup:

### Windows

Scroll the mouse wheel to scroll: `Multiple lines at a time`
Lines to scroll at a time: `5`
Scroll inactive windows when hovering over them: `true`

### VSCode

```json
{
  // default
  "editor.mouseWheelScrollSensitivity": 1,
  "editor.scrollbar.scrollByPage": false,
  "editor.smoothScrolling": false,
  "workbench.list.mouseWheelScrollSensitivity": 1,
  "terminal.integrated.mouseWheelScrollSensitivity": 1,
  "editor.fastScrollSensitivity": 5,
  "workbench.list.fastScrollSensitivity": 5,
  "workbench.list.smoothScrolling": false,
  // changed to see if it helped, it didn't
  "terminal.integrated.fastScrollSensitivity": 1,
  // other non-default
  "terminal.integrated.fontSize": 12
}
```

### Mouse

I'm using an MX Master Pro 3 connected over bluetooth, the following are settings from Log Options+

Scroll direction: `Standard`
Smooth scrolling: `false`
SmartShift: `false`
Scroll type: `Ratchet`

VS Code version: Code - Insiders 1.65.0-insider (d09aeab62c1f93acf4a89b93e9a8a82419d6249a, 2022-02-09T05:16:17.063Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (9.11GB free)|
|Process Argv|--crash-reporter-id 4d991305-2f89-4f51-af39-a0b9a4621445|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|15.51GB (4.73GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|15.51GB (4.73GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|15.51GB (4.73GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|15.51GB (4.73GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|15.51GB (4.73GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|15.51GB (4.73GB free)|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
vscode-nginx|wil|0.7.2
github-markdown-preview|bie|0.1.0
vsliveshare-pack|ms-|0.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstartedc:30421358
vs360cf:30404996
vsclayoutctrc:30405799
vscop841:30434589
pythonvsnew555:30426298
vscscmwlcmc:30428972
azactmsal:30432848
vscgsvidc:30433759

```

</details>

**Comment by meganrogge** [comment]
Try changing `terminal.integrated.mouseWheelScrollSensitivity` to a lower number
