### ISSUE TITLE
support to declare a json schema attribute as deprecated

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#14260]
for details see https://github.com/Microsoft/vscode/issues/13353

**Comment by aeschli** [comment]
I added a (vscode custom) property 'deprecationMessage' to the JSON schema.
If present, the given message will be shown. Typically you would set it to something like:
'Property foo is deprecated, use bar instead'

**Comment by weinand** [comment]
I've reopened this feature because the attribute is `deprecatedMessage` and not `deprecationMessage`. I would prefer `deprecationMessage`.

In addition some suggestions:
- don't show the description of a deprecated attribute in the hover
- don't suggest deprecated attributes in Intellisense
- a fixed font is used for the deprecation message in the hover:
![2016-11-11_17-18-50](https://cloud.githubusercontent.com/assets/1898161/20221909/91a6ade2-a833-11e6-924b-269f84a4525a.png)

**Comment by aeschli** [comment]
> deprecatedMessage and not deprecationMessage
ok, will change
> don't show the description of a deprecated attribute in the hover
You can make the fix for that in your schema: Remove the description from the attribute
> don't suggest deprecated attributes in Intellisense
ok makes sense
> don't use a fixed width font for the deprecation message in the hover
You have to file that against the problem hover (not under my control). I agree that a fixed size is not use useful.

**Comment by aeschli** [comment]
To verify have a launch.json with a node section that contains a "outDir" property.
