### ISSUE TITLE
handle python print error 

### ISSUE THREAD

**Issue by TBWISK** [Microsoft/vscode#14263]
- VSCode Version:1.6.1 (1.6.1) 9e4e44c19e393803e2b05fe2323cf4ed7e36880e
- OS Version:10.12 (16A323)

Steps to Reproduce:

1. when i use python to handler string ,and this string with xA char ,when print this string in vscode,it  like a '\n' char in my mac, like 
2. print "helloxAthisxAisxAabug"     
and it would be show in the screen
such as :   
hello   
this  
is  
abug

**Comment by weinand** [comment]
This issue was moved to DonJayamanne/pythonVSCode#427

**Comment by DonJayamanne** [comment]
Reopening as this is an issue with VS Code (probably string being interpreted incorrectly).

Steps to reproduce:
1. Create a file named ```test.py```
2. Add the following contents into the file
```python
print('this is all in one line')
print("helloxAthisxAisxAabug")
```
3. Add the following to the ```tasks.json```
```json
{
    "version": "0.1.0",
    "command": "python",
    "isShellCommand": true,
    "args": ["${file}"],
    "showOutput": "always"
}
```
4. Run the above task and the output is as follows:
```
this is all in one line
hello
this
is
abug
```

Expected output is:
```
this is all in one line
helloxAthisxAisxAabug
```

**Comment by isidorn** [comment]
Fixed in latest insiders. Please let me know if you can still see it there

**Comment by TBWISK** [comment]
@isidorn  ok, I would still focus it   ,   
and thanks for your help @DonJayamanne
