### ISSUE TITLE
Very simple case where intellisense is not working

### ISSUE THREAD

**Issue by kalin-toshev** [Microsoft/vscode#14267]
- VSCode Version: 1.6.1
- OS Version: Microsoft Windows [Version 10.0.14953]

Steps to Reproduce:

* md foobar
* Create the following simple module (mod.js) - 
```
var exports = {};
exports.f = function (a, b) {
  return a + b;
};
module.exports = exports;
```
* 'Consume' the module (i.e. in main.js); open vscode with [code . in the foobar folder]

```
const m = require('./mod');
m. <- no intellisense at this point!
```

Note: jsconfig.json is present in the same directory with the following content - 
```
{
	"compilerOptions": {
		"target": "es6",
		"module": "commonjs"
	}
}
```
If I comment the assignment to module.exports, intellisense will re-appear. 

I would not use this pattern for exporting stuff, but unfortunately, there are libraries out there, using such pattern (for example adal-node (`npm install adal-node`)), for which intellisense does not work.

**Comment by waderyan** [comment]
Thank you for opening this issue. This is strange to me. I am going to move this issue to the JavaScript language service repo (TypeScript).

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11867
