### ISSUE TITLE
file move changes "Date Modified"

### ISSUE THREAD

**Issue by itisdesign** [microsoft/vscode#142652]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.1 (user setup)
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. In VS Code > Explorer, create "FolderA" and "FolderB" sibling folders within same parent folder
2. In FolderA, create "movetest.txt" file
3. In Windows Explorer, note movetest.txt's "Date Modified" timestamp
4. In Windows Explorer, move movetest.txt from FolderA to FolderB
5. In Windows Explorer, note movetest.txt's "Date Modified" timestamp is the same as it was in step 3 (good)
6. In VS Code > Explorer, move movetest.txt from FolderB to FolderA
7. In Windows Explorer, note movetest.txt's "Date Modified" timestamp is not the same as it was in step 3 (bad)

**Comment by JacksonKearl** [comment]
Tracked down to:
https://github.com/microsoft/vscode/blob/01df559c184549248fcfbcecc5a616462e00c252/src/vs/base/node/pfs.ts#L490-L497

cc @bpasero

**Comment by itisdesign** [comment]
Possibly related? [https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-6.0#copying-and-moving-folders](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-6.0#copying-and-moving-folders)

> The operating system and FileSystemWatcher object interpret a cut-and-paste action or a move action as a rename action for a folder and its contents.

**Comment by bpasero** [comment]
See https://github.com/microsoft/vscode/issues/142652#issuecomment-1034147995

There is no harm in updating mtime, and I think it can help file watching as the comment indicates.

**Comment by itisdesign** [comment]
Updating mtime for move breaks the expected result of .NET's own FileSystemWatcher.

**Comment by bpasero** [comment]
Interesting, I was not aware of that. You say, the Windows file system watcher is able to figure out move events based on the mtime staying the same?

**Comment by itisdesign** [comment]
That is what the FileSystemWatcher documentation says in "Remarks > Copying and moving folders" at [https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-6.0#copying-and-moving-folders](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-6.0#copying-and-moving-folders)

**Comment by bpasero** [comment]
I cannot find any mention? Where?

**Comment by bpasero** [comment]
Anyway, let me just remove this, I was never really a big fan. Native macOS and Windows explorer are not touching mtime either.

**Comment by itisdesign** [comment]
Perhaps I mistakenly misread the section I quoted. However, this, under "Remarks > Events and Buffer Sizes", might be relevant:

> For example, when a file is moved from one directory to another, several [OnChanged](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher.onchanged?view=net-6.0) and some [OnCreated](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher.oncreated?view=net-6.0) and [OnDeleted](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher.ondeleted?view=net-6.0) events might be raised.

That leads me to believe FileSystemWatcher doesn't rely on mtime being changed, since Windows Explorer doesn't change mtime during a file move. Thank you very much sir!

**Comment by bpasero** [comment]
Yeah nevermind, the VSCode explorer should behave like OS native file tools imho, so I hope this is not breaking anything.
