### ISSUE TITLE
Auto create multiple cursor depending on find results

### ISSUE THREAD

**Issue by barsdeveloper** [microsoft/vscode#142624]
I would like to be able to create multiple cursors that are automatically placed depending on the results of the find feature.
Let's consider the following content
![image](https://user-images.githubusercontent.com/84736467/153198114-2701ed52-5ce2-4bfc-aaf7-b88aeedc4f72.png)
Now, when I search for a word, for example "imperdiet", it finds 6 results. It would be an awesome feature to be able to auto place cursors in all those positions automatically. For example I could click with Alt key down (or any other key binding that is set to create an additional cursor) somewhere in the text input field and be able to auto place cursors in all the lines. Let's do Alt+Click after letter "m" => "im|perdiet". At this point we will have cursors in all those places:
![image](https://user-images.githubusercontent.com/84736467/153198955-c4e10ed9-6aaa-4b0b-95c9-f2eeabed6e53.png)

To make the feature more discoverable, you could add a button that places the link at the beginning or end of the found text (maybe this way could work also with regex).

**Comment by gjsjohnmurray** [comment]
The command `Select All Occurrences of Find Match` already does this. On Windows the shortcut is Ctrl+Shift+L

**Comment by barsdeveloper** [comment]
Ahh nice, I guess I can close this. Thanks
