### ISSUE TITLE
All my project files were deleted

### ISSUE THREAD

**Issue by ImReGall123** [microsoft/vscode#142674]
On 2022-02-08 ~22:00 I coded in my D:\VisualStudio\projects folder, and the next day I couldn't find the folder. A tiny fraction of it was in the trash, the other part is still missing. No sign of bugs, problems, warnings, simply out of the blue. 3 weeks of work is on the line, please help me.

**Comment by JacksonKearl** [comment]
To help me better understand, is this the folder that VS Code created as its install location? Or is this a folder you manually created?

**Comment by ImReGall123** [comment]
I created manually in the install location as D:\VisualStudio\projects.

**Comment by JacksonKearl** [comment]
I am not sure what could have caused that to happen. I have not heard reports of that happening for any other users. Could an antivirus have possibly removed the files?
