### ISSUE TITLE
Extension Host terminated unexpectedly.

### ISSUE THREAD

**Issue by jonny-harte** [microsoft/vscode#142663]
Issue Type: <b>Bug</b>

Extension Host terminated unexpectedly has been happening on a regualar basis since updating to 1.64. I havent been able to track down what exactly is causing it.

VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:29:17.911Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|72, 69, 65|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 040328b8-1615-40c9-a234-19798a9b2adb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
salesforce-snippets|aji|1.2.1
salesforce-soql-editor|all|1.8.0
vscode-raml|blz|3.0.1
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.7.0
apex-pmd|chu|0.5.8
gitignore|cod|0.7.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.3.1
gitlens|eam|11.7.0
vscode-html-css|ecm|1.11.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.2.0
lana|Fin|1.4.1
vscode-pull-request-github|Git|0.36.0
todo-tree|Gru|0.0.215
sfdx-autoheader|Hug|0.7.2
codewind-openapi-tools|IBM|0.14.1
emotionsnippets|iJS|1.1.2
vscode-gist|ken|3.0.3
graphql-for-vscode|kum|1.15.3
rainbow-csv|mec|2.0.0
vscode-language-babel|mgm|0.0.36
git-graph|mhu|1.30.0
apex-code-coverage-visualizer|mod|0.9.6
vsliveshare|ms-|1.0.5330
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
lwc-salesforce|Nik|2.3.0
vscode-salesforce-doc-lookup|Obl|1.3.1
indent-rainbow|ode|8.2.2
vscode-jest|Ort|4.2.1
vscode-css-peek|pra|4.2.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.3
vscode-yaml|red|1.4.0
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode|sal|53.16.0
salesforcedx-vscode-apex|sal|53.16.0
salesforcedx-vscode-apex-debugger|sal|53.16.0
salesforcedx-vscode-apex-replay-debugger|sal|53.16.0
salesforcedx-vscode-core|sal|53.16.0
salesforcedx-vscode-lightning|sal|53.16.0
salesforcedx-vscode-lwc|sal|53.16.0
salesforcedx-vscode-soql|sal|53.16.0
salesforcedx-vscode-visualforce|sal|53.16.0
code-spell-checker|str|2.1.6
sfdx-vs-test-class-generator|tea|1.0.0
pdf|tom|1.2.0
sfdx-package-xml-generator|Vig|2.0.7
vscodeintellicode|Vis|1.2.17
vscode-icons|vsc|11.8.0
vscode-import-cost|wix|2.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vs360cf:30404996
vsrem710:30416614

```

</details>

**Comment by joaomoreno** [comment]
Here is a **checklist** to find out more about the issue
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line - NOT the integrated terminal of Code)
    - if it does not reproduce with extensions disabled, you can stop testing and report this!
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] there is no suspicious output when running from the command line (`code --verbose`)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces after deleting `<appdata>/User/keybindings.json` and `<appdata>/User/settings.json` (backup first! see below for paths)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`

**Comment by weathery** [comment]
The same issue with v1.64.2 in Win7 x86-64.

**Comment by weathery** [comment]
> The same issue with v1.64.2 in Win7 x86-64, with the extension redhat.java-1.3.0.

For detail:
https://github.com/redhat-developer/vscode-java/issues/2315
