### ISSUE TITLE
Visual Code Insiders crashes on Start

### ISSUE THREAD

**Issue by werto87** [microsoft/vscode#142623]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version:
1.65.0-insider
d09aeab62c1f93acf4a89b93e9a8a82419d6249a
x64

- OS Version:
Operating System: Arch Linux                      
Kernel: Linux 5.16.7-arch1-1

I get a gray screen and after 1 second it closes. Note I installed code-insiders from aur "https://aur.archlinux.org/packages/visual-studio-code-insiders-bin" and someone else has the same problem.

> MuratOzsoyler commented on [2022-02-09 10:08 (UTC)](https://aur.archlinux.org/packages/visual-studio-code-insiders-bin#comment-851031) (edited on 2022-02-09 10:10 (UTC) by [MuratOzsoyler](https://aur.archlinux.org/account/MuratOzsoyler))
visual-studio-code-insiders-bin 1644385586-1 (Wed 09 Feb 2022 12:38:23 PM +03) Causes core dump. Is this related to upstream changes? Or anything wrong with package?

Steps to Reproduce:
1. Run 'code-insiders --disable-extensions'

[code_insiders_crash.zip](https://github.com/microsoft/vscode/files/8032574/code_insiders_crash.zip)

**Comment by ralwing** [comment]
same here,
installed using snap 
`d09aeab6` Ubuntu 20.04.

**Comment by dev117uday** [comment]
refer to this issue : https://github.com/microsoft/vscode/issues/142574
