### ISSUE TITLE
Two machines with the same ID

### ISSUE THREAD

**Issue by bowencool** [microsoft/vscode#142630]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.1 (Since Settings Sync Published)
- OS Version: Mac OS 12.1 (21C52)(Since Settings Sync Published)

Steps to Reproduce:

https://github.com/microsoft/vscode/issues/104732#issuecomment-703081384

I saw this solution, but where is the `machineid` file ?

**Comment by yume-chan** [comment]
`~/Library/Application Support/Code/machineid`

**Comment by bowencool** [comment]
I've tried it and it doesn't work for me.
VSCode did not regenerate the `machineid` file.

**Comment by lramos15** [comment]
Do you happen to have telemetry disabled?

**Comment by bowencool** [comment]
> Do you happen to have telemetry disabled?

How do I check if it's on

**Comment by lramos15** [comment]
@bowencool Search your settings for telemetry and make sure it's set to all

**Comment by bowencool** [comment]
> @bowencool Search your settings for telemetry and make sure it's set to all

it's set to `all`

**Comment by lramos15** [comment]
@sbatten Do you have any ideas?

**Comment by bowencool** [comment]
> @bowencool Have you tried disabling all your extensions? You can do that by starting from the command line `code --disable-extensions`

I just tried it and nothing changed. 
By the way, I'm getting a new computer soon

**Comment by lramos15** [comment]
> I just tried it and nothing changed.
> By the way, I'm getting a new computer soon

Thanks for trying. We still want to figure out the issue to avoid other issues hitting a similar issue. If you do `code --user-data-dir 'some folder'` you can start VS Code with a completely fresh folder for all user data. If you do this let me know if a machineid file is created in that folder.

**Comment by bowencool** [comment]
> > I just tried it and nothing changed.
> > By the way, I'm getting a new computer soon
> 
> Thanks for trying. We still want to figure out the issue to avoid other issues hitting a similar issue. If you do `code --user-data-dir 'some folder'` you can start VS Code with a completely fresh folder for all user data. If you do this let me know if a machineid file is created in that folder.

Doing `code --user-data-dir 'some folder'` solves the problem by generating a new ID

**Comment by lramos15** [comment]
Thanks for testing. I'm closing this for now since I have yet to see any other new reports and a new user dir does cause a new id to be generated. Feel free to copy that new id into your default user directory and that should work as well.
