### ISSUE TITLE
Find and Replace Text Input is Too Small

### ISSUE THREAD

**Issue by bash-j** [microsoft/vscode#142686]
Issue Type: <b>Feature Request</b>

Can only see 8-9 characters in the text input for the Find. Does it need to be so small? Would love something like the UI in Notepad++ or Jupyter Notebook Classic for single cell find and replace.

VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:16:22.147Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
If you're referring to the widget that appears in the upper right of an editor when you press Ctrl/Cmd+F, did you try using the drag-handle on the left edge to make it wider?

**Comment by bash-j** [comment]
Yes, sorry the widget. It doesn't look like the drag handle works. I've also noticed the replace all button is greyed out.

**Comment by gjsjohnmurray** [comment]
/gifPlease

Here's mine:
![junk](https://user-images.githubusercontent.com/6726799/153312974-395ab62e-30db-423c-ba2b-6a4d2e614fe1.gif)


Version info:

Version: 1.64.1 (user setup)
Commit: d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
Date: 2022-02-07T17:16:22.147Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by bash-j** [comment]
![Recording 2022-02-10 at 12 45 34](https://user-images.githubusercontent.com/3195567/153324284-064d49b0-390d-4bdb-8d6a-cf12a116dfb9.gif)

I am editing a jupyter notebook (ipynb) by the way.
