### ISSUE TITLE
Editor/title command does not return proper visible editors list

### ISSUE THREAD

**Issue by nickImbirev** [microsoft/vscode#142629]
Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: 1.64.0
- OS Version: MacOs BigSur 11.6.1

Steps to Reproduce:
1. Clone the [repo](https://github.com/nickImbirev/vscode-editor-title-command-bug) with a bug sample
2. Run the `npm install` command
3. Press F5 button (to start the debugging process)
4. Open the folder in the Explorer panel with some files inside (it will be enough to open the repo folder in it)
5. Open two (or more) files in the opened folder (i.e. README.md and package.json)
6. Click the `Hello-world` button in the right top corner of the active editor to emulate the bug

**AS IS:** the user will see a notification with amount of visible editors (it will be only 1 editor)

**TO BE:** the user should see a notification with a **proper** amount of visible editors (it should be the same, as the amount of editors they opened in the step 5)

**Comment by jrieken** [comment]
Visible editor is not visible editor tabs. Think about visible editors as the number of cursors that you can see. Tho, there is a feature request to also expose tabs to extensions.

**Comment by nickImbirev** [comment]
Hey @jrieken! Thank you for your reply!

So, if I understood it correctly, the function `window.visibleTextEditors` will return me the visible editors, but not the visible editors **in the opened tabs**?
Is it possible to ask you to provide some link or description to the `visible editors` in VSCode, because I really don't understand, how the editor might be visible in the UI, but not returned by this function...

**Comment by nickImbirev** [comment]
Oh, ok, I see the feature request and the explanation there, in the comments. Sorry for bothering :(
