### ISSUE TITLE
Electron 16: dev tools console no longer filters in all output

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#142611]
When we log something via `console.log` and pass multiple arguments (e.g. `console.log('a', 'b', 'c')`), the console filter no longer reports a find match for anything that is not the first argument.

![Recording 2022-02-09 at 11 20 03](https://user-images.githubusercontent.com/900690/153180430-bff90c71-e05e-4877-9b9f-56c710256ee1.gif)

**Comment by rzhao271** [comment]
I verified this issue is fixed in electron 17.0.0
TODO: verify that backporting https://bugs.chromium.org/p/chromium/issues/detail?id=1263070 to electron 16-x-y branch (https://github.com/electron/electron/tree/16-x-y) fixes the issue.
