### ISSUE TITLE
Git Bash terminal adds "01~" characters after pasting strings longer than 38 characters

### ISSUE THREAD

**Issue by pyxelr** [microsoft/vscode#142677]
Issue Type: <b>Bug</b>

I have observed a weird behaviour for the "_Git Bash_" terminal inside of VS Code.

After copying a longer string (e.g., git hash, and it does not matter from where), such as `1a694e7948986c45dcb6dcf73b293df5d4bb1eb7`, and later pasting it inside of the Git Bash VS Code terminal (e.g., using the RMB or Ctrl+V), it becomes: `1a694e7948986c45dcb6dcf73b293df5d4bb1eb71~`. As we can observe, it attached the `~` character at the end of the pasted string.

This is however not the case when I use "_PowerShell_", "_Command Prompt_", the native "_Git Bash_" Windows terminal, the native "_Powershell_" "_CMD.exe_", or any other terminal client like "_ConEmu_". It does not seem also to be affected by the modified `.bash_profile` - use of a prompt theme engine (Oh My Posh).

Therefore, I am assuming it is just an error inside my VS Code.

After pasting other string lengths, I observed the following:

- for 38 characters, it pastes correctly
- for 39 characters, it adds `~`
- for 40 characters, it adds `1~`
- for 41 characters, it adds `01~`
- for 42 and 43 characters, it adds `~`
- for 44 characters, apparently it pastes correctly

**This was, however, fixed when I disabled bracketed paste using this command: `$ bind 'set enable-bracketed-paste off'`.**

Therefore, I assume that Git Bash does not support bracketed mode correctly? Is there a way to permanently turn off bracketed mode only for the Git Bash terminal of VS Code, without modifying the general `.bash_profile` on my system?

---

VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:16:22.147Z)
OS version: Windows_NT x64 10.0.19044
Git version:  2.35.1.windows.2 (64-bit)
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.71GB (49.39GB free)|
|Process Argv|--crash-reporter-id d7dcf2ef-574d-4eda-b577-a33178df578d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
project-manager|ale|12.5.0
asciidoctor-vscode|asc|2.9.4
vscode-opennewinstance|chr|0.0.12
vscode-postgres|cko|1.4.0
vscode-autohotkey-plus|cwe|2.6.2
vscode-markdownlint|Dav|0.46.0
python-preview|don|0.0.4
githistory|don|0.6.19
gitlens|eam|11.7.0
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.2.0
pythonsnippets|frh|1.0.2
todo-tree|Gru|0.0.215
debug-visualizer|hed|2.2.4
d3-js-snippets|Hri|1.0.0
vsc-python-indent|Kev|1.14.2
MagicPython|mag|1.1.0
rainbow-csv|mec|2.0.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.19.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.1
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
material-icon-theme|PKi|4.12.1
java|red|1.3.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.4.0
jinjahtml|sam|0.16.0
tabnine-vscode|Tab|3.5.24
errorlens|use|3.4.1
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0
JavaScriptSnippets|xab|1.8.0
viml|Xad|1.0.1
markdown-all-in-one|yzh|3.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vscop940:30404999
vsrem710:30416614

```

</details>

**Comment by Tyriar** [comment]
I believe this will fix itself automatically as you update Windows as we will move onto a newer version of conpty like what Windows Terminal ships to. We recently added a FAQ to workaround this but looks like you already figured that out: https://code.visualstudio.com/docs/editor/integrated-terminal#_i-see-1-or-201-when-i-paste-something
