### ISSUE TITLE
file watcher excludes all, still get "unable to watch in large workspace"

### ISSUE THREAD

**Issue by Deena-B** [microsoft/vscode#142673]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I get the "Unable to watch for file changes in this large workspace folder" message in both of my remote workspaces. 

I have set my settings.json to the following, which should exclude every folder that is in my workspace!

{
    "security.workspace.trust.untrustedFiles": "open",
    "window.zoomLevel": 1,
    "terminal.integrated.scrollback": 1000000,
    "terminal.integrated.persistentSessionScrollback": 1000000,
    "editor.wordWrap": "wordWrapColumn",
    "files.autoSave": "onFocusChange",
    "scm.alwaysShowRepositories": true,

    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/.hg/store/**": true,
        "**/node_modules/*/**": true,
        "**/venv/**": true, 
        "**/env/**": true, 
        "env -*": true,
        "/home/**": true,
        "/rnd/users/**": true, 
        "/ops/**": true
    }
}

I don't want to increase my max_user_watches, I just want to exclude what's watched. What am I missing?

Thanks,
Deena

VS Code version: Code 1.64.1 (Universal) (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:26:08.977Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 4.18.0-240.22.1.el8_3.x86_64
Remote OS version: Linux x64 4.18.0-193.19.1.el8_2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|64.00GB (38.88GB free)|
|Process Argv|--crash-reporter-id 05475dd1-2faf-4f0a-8b4a-b95e52ccd493|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: scops|
|OS|Linux x64 4.18.0-240.22.1.el8_3.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (20 x 2494)|
|Memory (System)|125.65GB (46.44GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: scrnd1|
|OS|Linux x64 4.18.0-193.19.1.el8_2.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (20 x 2494)|
|Memory (System)|125.65GB (0.57GB free)|
|VM|100%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
gc-excelviewer|Gra|4.1.52
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001775990

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30433058
pythonvs932:30410667
wslgetstartedc:30433508
vscop341:30404997
vsrem710cf:30416617

```

</details>

**Comment by bpasero** [comment]
Glob patterns are unsupported.

/duplicate https://github.com/microsoft/vscode/issues/137872
