### ISSUE TITLE
Please allow for Multiple Profiles for Settings Sync

### ISSUE THREAD

**Issue by vyacheslav31** [microsoft/vscode#142687]
Hello,

While the Settings Sync feature is very useful for quickly setting up your development environment. The tools, extensions and themes that I wish to use vary across different devices. It would be nice if I could manage different Settings Profiles and load each one of them up on the fly.

FYI, I do understand that this is technically achievable right now by logging into different accounts. But I am sure most people could understand why it would just be easier to have multiple profiles for a single account. (No one likes account bloat)

Please consider adding this feature in the future.

Thank you

Vyacheslav
VSCode User

**Comment by sandy081** [comment]
/duplicate

CC @sana-ajani
