### ISSUE TITLE
Notebooks IntelliSense: DocString covers up auto-complete list when cell is at the bottom of the screen

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode#142683]
Version: 1.65.0-insider (user setup)
Commit: d09aeab62c1f93acf4a89b93e9a8a82419d6249a
Date: 2022-02-09T05:16:17.063Z
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. in an ipynb file, add enough cells so the last cell is at the bottom of the screen
2. put in the following code in the last cell:
import pandas as pd
X = ['A','B','C']
Y = pd.Series(X)
3. then type in the following line of code and stop after the "." following the second "Y"
print(Y,Y.)

Actual: auto-complete list comes up behind DocString
![image](https://user-images.githubusercontent.com/26419852/153302983-bfa7a282-7c4c-4e82-917d-d26289a36e50.png)

**Comment by jrieken** [comment]
Can you provide a screen shot of the full window? The details widget should try to position it to the sides when there isn't enough space at its preferred location. Is that the case here? Does this recover when you resize the details widget?
