### ISSUE TITLE
Alwasy log out from github account

### ISSUE THREAD

**Issue by endrasww** [microsoft/vscode#142699]
Issue Type: <b>Bug</b>

GitHub account I use to sync always get log out when I close VS Code and need to log in back when it launches

VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:17:47.733Z)
OS version: Linux x64 5.15.19-1-MANJARO snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX-7600P Radeon R7, 12 Compute Cores 4C+8G (4 x 2532)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 2, 1|
|Memory (System)|6.73GB (1.49GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id ff30c43c-4075-4d60-9cc3-d9f0a221a0aa|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|1.11.0
prettier-vscode|esb|9.2.0
r|Iku|2.3.8
rainbow-csv|mec|2.0.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.1
jupyter|ms-|2022.1.1001821375
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
LiveServer|rit|5.7.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vscop453:30404998
vsrem710cf:30416617

```

</details>

**Comment by TylerLeonhardt** [comment]
/duplicate https://github.com/microsoft/vscode/issues/142799

In that issue, I asked some questions. Can you answer those questions over there so we track this issue in one place? Thanks!

**Comment by morallys** [comment]
With the other person's answer in the issue, installing gnome-keyring on my machine solved the problem.
