### ISSUE TITLE
Source control loading state gone after moving to new sidebar

### ISSUE THREAD

**Issue by matzeso** [microsoft/vscode#142712]
Issue Type: <b>Bug</b>

We have a few things running through husky on commit, e.g. linting. Also, when switching branches, we have automatic build steps.
Normally, there was a visual loading bar showing in the Source Control sidebar while this was running. The same loading was also showing when pulling/pushing to remote.

I moved source control to the new sidebar on the right side and now the loading indicator is gone. Moving the sidebar back to the left does not bring the loading indicator back.

It is now quite hard to tell when the automation scripts are done, I am looking at the git output console and wait until there are no more logs (which is not a good indicator that it is finished).

VS Code version: Code 1.64.1 (Universal) (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:26:08.977Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id 0470f9df-969d-45d5-85ec-39fb9af08f91|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.7.6
npm-intellisense|chr|1.4.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
prettier-vscode|esb|9.2.0
vscode-jest-runner|fir|0.4.47
vscode-pull-request-github|Git|0.36.0
todo-tree|Gru|0.0.215
volar|joh|0.31.2
i18n-ally|lok|2.8.1
vscode-docker|ms-|1.19.0
vsliveshare|ms-|1.0.5330
env-cmd-file-syntax|Nix|0.3.0
svg-preview|Sim|2.8.3
vscode-stylelint|sty|1.2.2
vscode-field-lights|sve|0.0.11
vsfire|tob|1.4.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
testflight:30433670
vsc1dsc:30433058
pythonvs932:30410667
wslgetstartedc:30433508
vscop940:30404999
vsrem710cf:30416617
vscop841:30435957

```

</details>

**Comment by gjsjohnmurray** [comment]
I think this is a duplicate of #135215

**Comment by matzeso** [comment]
I can confirm that once I run `View: Reset View Locations` the loading bar in source control appears again.
