### ISSUE TITLE
"Debug: Open Debug" Setting working incorrectly

### ISSUE THREAD

**Issue by enesaltinkaya** [microsoft/vscode#142780]
I'm on Linux working with java, also tested with c++.

Selecting **openOnDebugBreak** acts as if **openOnFirstSessionStart** is selected.

**Comment by weinand** [comment]
Please be more specific and provide detailed steps:
what are you trying to do?
what should happen?
what does happen?

**Comment by enesaltinkaya** [comment]
I meant to say "acts as if **openOnFirstSessionStart**", i corrected it.

if Debug: Open Debug setting is set to openOnFirstSessionStart, after starting VsCode, first time running a Debug makes sidebar to switch to "Run and Debug" side view automatically.

Subsequent Debug runs will not switch to Run and Debug side view any more.

Now if we set that setting to openOnDebugBreak, it will still switch to Run and Debug side view automatically at first Debug.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/140089
