### ISSUE TITLE
Consider adding test for TypeScript server plugins

### ISSUE THREAD

**Issue by dsherret** [microsoft/vscode#142758]
In vscode 1.64.0, all extension functionality that used TypeScript server plugins did not work at all on Windows #142139 (ex. the [Deno](https://github.com/denoland/vscode_deno/issues/620) extension, [Styled Components](https://github.com/styled-components/vscode-styled-components/issues/354), etc.). The way this error occurred indicates that there's no tests for TypeScript server plugins. Perhaps it would be useful to add a basic test for this functionality to help reduce the chance of this happening in the future.

**Comment by mjbvz** [comment]
I doubt the benefits of a test outweigh the cost of maintaining a test that spans three different products: vscode, TS server, and a plugin. This is first time we've seen a failure of this nature

To help, make sure you are testing your extension on VS Code insiders and share feedback if something no longer works as expected

**Comment by dsherret** [comment]
@mjbvz couldn't this just be a test in typescript-language-features? I don't think it would span three products, but I don't understand the vscode codebase that well.

Using insiders doesn't seem realistic because something could break that was merged between the insiders build someone downloaded and the new release.

**Comment by mjbvz** [comment]
Insiders tracks the next stable version of VS Code that will ship, besides a few minor differences like product name and icon

In this case, TS plugins on windows were broken in insiders for around 3 weeks. We would have been able to fix this issue quickly if we had seen reports of the issue during that period. You can help us by testing your extension on insiders and letting us know if something regresses
