### ISSUE TITLE
Output lldb/gdb

### ISSUE THREAD

**Issue by acaldas1984** [microsoft/vscode#142714]
When typing certain instructions on debug console like:

```
-exec breakpoint list
-exec thread list
-exec register read
-exec disassemble --frame 
```

I can see no feedback from lldb, which is a pitty. Sometimes I need to do certain operations which are not available in vscode. It would be desirable to show the output from the debugger in vscode.

**Comment by weinand** [comment]
Please file this issue against the debugger extension you are using. VS Code knows nothing about lldb/gdb.
