### ISSUE TITLE
Find, replace, find all, replace all: add keyboard shortcut tooltip

### ISSUE THREAD

**Issue by fulldecent** [microsoft/vscode#142779]
# Feature 
The find/replace widget has a button for switching between find and find/replace modes. This button has a tooltip. Also there is a keyboard shortcut for this.

In other places in VS Code, a button which has a tooltip and has a keyboard shortcut, the keyboard shortcut is shown in the tooltip, for example here [the find/replace Replace and Dismiss buttons](https://github.com/microsoft/vscode/issues/131095#issuecomment-902250900).

I am requesting that these discoverability niceties also be added in these places:

FIND (this should show the tooltip for FIND+REPLACE)
<img width="600" alt="Screen Shot 2022-02-10 at 17 11 02" src="https://user-images.githubusercontent.com/382183/153505960-6b0e2e15-f59f-4fe9-a5e2-6b4804844c02.png">

REPLACE (this should show the tooltip for JUST FIND)
<img width="590" alt="Screen Shot 2022-02-10 at 17 11 11" src="https://user-images.githubusercontent.com/382183/153505992-e9a5fd55-d727-4730-be34-e7f35745b32b.png">

FIND ALL (this should show the tooltip for FIND+REPLACE ALL)
<img width="334" alt="Screen Shot 2022-02-10 at 17 11 20" src="https://user-images.githubusercontent.com/382183/153506043-2eb4f296-0c6f-4169-a64a-cac4badf2462.png">

REPLACE ALL (this should show the tooltip for JUST FIND ALL)
<img width="322" alt="Screen Shot 2022-02-10 at 17 11 23" src="https://user-images.githubusercontent.com/382183/153506056-8d8ce111-a4b2-4a24-86ba-32fa018ff2ce.png">

# Implementation notes

Another commit which [implements this same improvement for the Remote button](https://github.com/microsoft/vscode/commit/0547e04d242550f9e4a0ed0f5fda27c090e5ec0b) can be a starting point to study for implementing this issue.

**Comment by fulldecent** [comment]
Pinging a potentially interested person (and sorry if not interested): @JacksonKearl

**Comment by rebornix** [comment]
@fulldecent thanks for feedback, this makes perfect sense.

**Comment by amunger** [comment]
unless I'm not finding it, there isn't actually a keyboard shortcut for toggling replace when the find widget is open. i.e. ctrl+f/h don't perform the same action that the carrot button does
