### ISSUE TITLE
Terminal text disappearing on macOS under VMware.

### ISSUE THREAD

**Issue by precisionpete** [microsoft/vscode#142752]
Does this issue occur when all extensions are disabled?: Yes/No

Yes!

- VS Code Version: 1.64.1
- OS Version: Darwin x64 21.3
- VMware 16 Pro v16.2.1 (linux host), vmware-tools Darwin v15+

Steps to Reproduce:

1. Open vscode
2. Open a Terminal

The terminal text is either black on black or white on white depending on the theme. Occasionally it flashes to something you can read. But it will not stay that way...

I suspect it has to do with Electron and the VMware drivers. But I have no idea how to debug...

**Comment by meganrogge** [comment]
This might have to do with an extension you have installed. Can you try running the extension bisect command?
