### ISSUE TITLE
VS Code hung after window reload

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#142766]
In today's insiders, I ran `Developer: Reload Window` with the Extension view open, and when VS Code reloaded it just hung. And I saw the following in the console.

```
 INFO IExtensionHostStarter.start() took 50 ms.
workbench.desktop.main.js:3038 The customer named _initialize has been holding on to the lock for 30s. This might be a problem.
```

I tried the same scenario again but it worked ok.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/142786
