### ISSUE TITLE
Git's fatal error: authentication failed occured only on VSCode

### ISSUE THREAD

**Issue by Pandede** [microsoft/vscode#142741]
Issue Type: <b>Bug</b>

I tried to push my code with Git on VSCode, but "Fatal error: Authentication failed" occured, then I have tried to clone, pull or fetch but it failed.
After that, I tried to execute Git command by using Linux Terminal, it worked fine! Furthermore, there was the same issue reported in past, is that a bug of latest version of VSCode?

VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:16:22.147Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Connection to 'SSH' could not be established  Connecting was canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.39GB (3.45GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bxinxpa-dl01/data/AI/user/steven/t1-lpr --crash-reporter-id 05ec48bd-d912-4f91-bb16-c34438dfd458|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH' could not be established  Connecting was canceled
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vscop453:30404998
vsrem710cf:30416617

```

</details>

**Comment by lszomoru** [comment]
@Pandede, where is the repository hosted? 
Have you used an HTTPS or SSH link when you cloned the repository?
