### ISSUE TITLE
Allow vertical selection

### ISSUE THREAD

**Issue by jhonathanc** [microsoft/vscode#142718]
Is there any plan to add a feature to allow vertical selection (Alt + mouse drag'n'drop on the desired area) like other advanced editors?

**Comment by IllusionMH** [comment]
Have you seen this part of docs?
https://code.visualstudio.com/docs/editor/codebasics#_column-box-selection

I think it's <kbd>Alt</kbd>+<kbd>Shift</kbd>+Mouse by default or just middle mouse button.

**Comment by jhonathanc** [comment]
Wow, exactly what I need. Thank you.
