### ISSUE TITLE
problema

### ISSUE THREAD

**Issue by natilla-giovanni** [microsoft/vscode#142709]
Issue Type: <b>Feature Request</b>

salve
platform ide non si installa su questo pc

VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:16:22.147Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide clear description of problem and steps to reproduce in English.
Current issue doesn't look actionable.

**Comment by natilla-giovanni** [comment]
hello my problem is this.  After successfully installing VSCODE I have
installed 1 language 2 marlin 3 platformio. The download of platformio
crashes in the middle.  i have disabled python and python 3 from windows
alians as the ghitub forum explains, but it doesn't go anyway.  vscode I
installed it on 2 PCs of my property, why doesn't it work on my new PC?
Thanks

Il Gio 10 Feb 2022, 13:24 VS Code Issue Triage Bot ***@***.***>
ha scritto:
