### ISSUE TITLE
Shortcuts Cmd+J or Cmd + M  don't affect on Console panel if it's aside

### ISSUE THREAD

**Issue by egorovsa** [microsoft/vscode#142744]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.1 Commit: d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
- OS Version: MacOS 12.1 (21C52)

Steps to Reproduce:

1. Open console panel  with Cmd+J or Cmd + M 
2. It will be opened in the bottom of the editor
3) Right button click on the top of the console window and chose "Move views to side panel"
4)  Cmd+J or Cmd + M  shortcuts no more affect on this panel, moreover it opens new empty one in the bottom...

**Comment by meganrogge** [comment]
works for me in insider's

This has already been fixed in Insider's and will be a part of our recovery release.

/duplicate https://github.com/microsoft/vscode/issues/142176
