### ISSUE TITLE
git hub problem

### ISSUE THREAD

**Issue by faruk56-arch** [microsoft/vscode#142782]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

hello just cant connect to git hub its got to microsoft site to connect

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
OS version: Linux x64 5.14.14-surface snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2799)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 2, 2|
|Memory (System)|15.55GB (2.17GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 1e823049-bec2-444c-8015-3d87ad9b05e7|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.0
vscode-tailwindcss|bra|0.7.6
es7-react-js-snippets|dsz|4.3.2
copilot|Git|1.7.4924
vscode-pull-request-github|Git|0.36.1
php-namespace-resolver|Meh|1.1.8
vetur|oct|0.35.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.4
tabnine-vscode|Tab|3.5.24

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vsrem710:30416614

```

</details>

**Comment by lszomoru** [comment]
@faruk56-arch, could you please share the steps that you are following as well as the error that you are seeing? Thank you!
