### ISSUE TITLE
Find - Replace all option in Jupyter Notebook has become non-actionable

### ISSUE THREAD

**Issue by rohan-paul** [microsoft/vscode#142756]
![image](https://user-images.githubusercontent.com/12703975/153481580-27250886-abee-4063-b9fa-1f43cc021b59.png)

- VS Code Version:
Version: 1.64.1
Commit: d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
Date: 2022-02-07T17:17:47.733Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-28-generic

- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. In a Jupyter notebook, just do Ctrl+H and put some strings in find and replace boxes.

**Comment by rebornix** [comment]
Just realized this is a regression from previously stable.

**Comment by rohan-paul** [comment]
I am using the latest stable version, and the issued does not look to be resolved yet.

```
Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T15:36:26.048Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-39-generic

```

**Comment by rohan-paul** [comment]
After updating to  version 1.66.0 - I get the "Replace All" button activated (as in not grayed-out any more)  - But it does NOT work. i.e. after clicking on the button naothing happens.

```
Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:41.156Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.13.0-39-generic
```

**Comment by rohan-paul** [comment]
Hi, this is still not resolved after today's release to Version: 1.67.1

Below my current version details.

```
Version: 1.67.1
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:39:22.915Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.13.0-41-generic
```

**Comment by rzhao271** [comment]
@rohan-paul can you try again on [VS Code Insiders](https://code.visualstudio.com/insiders
)?
Otherwise, you'll have to wait for version 1.68.

**Comment by rohan-paul** [comment]
> @rohan-paul can you try again on [VS Code Insiders](https://code.visualstudio.com/insiders)? Otherwise, you'll have to wait for version 1.68.

Great its working in the Insider version. Thanks.
