### ISSUE TITLE
Wrong margin on markdown table in notebook

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#142791]
Have a notebook with a markdown cell like this

```md
| A | B |
| ---- | ---- |
| Cell 1 | Cell 1 |
| Cell 2 | Cell 2 |
```

The second column has weird padding

![image](https://user-images.githubusercontent.com/323878/153521487-650b6283-6192-4bfb-ba0d-c3d8454cc898.png)

That is coming from this style rule, I don't understand the purpose:

https://github.com/microsoft/vscode/blob/53c29fc51fa2741732bba39f7ed6aa2234fca8e7/extensions/markdown-language-features/notebook/index.ts#L114-L118

It looks find in the normal markdown preview

**Comment by mjbvz** [comment]
I think this rule is too generic. It should only target top level elements of the preview instead of using `*`
