### ISSUE TITLE
Better editor tabs sorting to improve workflow

### ISSUE THREAD

**Issue by cartok** [microsoft/vscode#142708]
I think it would be helpful make editor tabs in sort in the following way:
1. Pinned Tabs
2. Tabs where the source control noticed changes
3. Other tabs

That's because it would make context switching easier. I find myself often searching in the project, reading some files that I do not want to change, just look at and understand the code. Then I want to return to the files where I'm working on currently. I then often find myself switching to the source control in the sidebar to open the file I want to continue on even though it's already opened, because it is easier to find but it requires me to change the sidebar view. Another advantage would be that I would be able to close temporarily opened files easier by keyboard.

One could also think about allowing us to configure auto sorting for pinned tabs.

Another enhancement could be to allow configuring the sorting sorting (default, alphabetical) for `pinned`, `pinned & source control diff`, `unpinned & source control diff`, `unpinned` tabs.

One also make diff tabs open next to the file, if the file is already opened, or reuse the file and make it easy to "switch back to nromal editing mode".

What lastly comes to my mind is that it would also be good to have a command for returning to the previously opened file. This could be used well in conjunction with indexed tabbing. Indexed tabbing would with all of this allow to manually cleanup tab sections easily by keyboard and it would also be easy to get back to business in the situation where you did a projectwide search, and opened the search result in another editor group (for example) to get back to where you want to continue writing on.

_PS: In general I think editors have too many functions assinged to just too many shortcuts. Shortcuts should just allow proper code navigation in the first place. I would not even allow plugins to set new shortcut, they should document their functions and define the commands, the configuration should be up to the user._

**Comment by shadow-light** [comment]
I'm similar. I frequently consult the source control panel to go back to what I'm working on, rather than look through a list of tabs only to discover the file I'm looking for isn't actually open (but is modified in git).
