### ISSUE TITLE
ConfigurationRegistry handles contributed configs very poorly

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#14272]
Sorry I cannot save the cpuprofile.

With the default extensions this consumes 31ms of start-up time.

Long story short, for each contributed configuration, the configuration registry ends up emitting one event, which ends up triggering N configuration change events, where N is the number of contributed configurations. IMHO they should result in a single configuration change event.

![image](https://cloud.githubusercontent.com/assets/5047891/19644053/faea83d6-99ed-11e6-85de-e803bb79a9d5.png)

**Comment by bpasero** [comment]
Yeah, I wonder who introduced this ;)

**Comment by alexandrudima** [comment]
When I added it, there was only one customer, so the loop was effectively a single call at that time :D

Thank you! :heart:

**Comment by bpasero** [comment]
Better fix is to introduce a bulk API registerConfiguration**s**

**Comment by alexandrudima** [comment]
Nice! Thank you!
