### ISSUE TITLE
Closing with unsaved changes

### ISSUE THREAD

**Issue by scrooby** [Microsoft/vscode#1427]
When closing Code with unsaved changes, I get the expected dialog asking me if I want to save my changes:

![vscode-save-changes](https://cloud.githubusercontent.com/assets/1249722/11877265/1af924d2-a4e6-11e5-85ed-27c5a8b14ede.PNG)

If I click "Don't Save", the dialog disappears, but the application doesn't close.

If I click "Cancel", the dialog disappears and the application closes.

Should this behavior be the other way around?

![vscode-version](https://cloud.githubusercontent.com/assets/1249722/11877253/033ead58-a4e6-11e5-85c5-c17de536af86.PNG)

**Comment by timReynolds** [comment]
This seems like intended behaviour for windows based on textFileServices.ts.

    const buttons = [save];
    if (isWindows) {
        buttons.push(dontSave, cancel);
    } else {
        buttons.push(cancel, dontSave);
    }

I agree it's very confusing however.

**Comment by myty** [comment]
I was coming here to report the same thing.  Definitely should be the other way around.

**Comment by bpasero** [comment]
Has been fixed for our december drop!
