### ISSUE TITLE
GitHub authentication callback doesn't get to the right window in today's insiders

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#142775]
Today, when I tried to authenticate with GitHub (for Copilot), the redirect opened a whole new vscode window and didn't work.

I've tried it multiple times, and only with a single vscode window open, but it always has the same behavior.

I don't know if this is just today, but it is very recent.

/cc @TylerLeonhardt

**Comment by IllusionMH** [comment]
I also can reproduce this issue on two Windows devices.

Looks like duplicate of #142685 or at least related.

**Comment by TylerLeonhardt** [comment]
/duplicate #142685

Thanks @IllusionMH!
