### ISSUE TITLE
Moving the cursor to an adjacent line doesn't move it directly above/below the original position with proportional fonts.

### ISSUE THREAD

**Issue by matj1** [microsoft/vscode#142738]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64
- OS Version: Manjaro 21.2.3-1

When I use a proportional font and move the cursor originally on the ‹x›th character on the line to an adjacent line, it moves to the ‹x›th character on that line, which is usually not directly above or below the original position. 

![Snímek z 2022-02-10 15-56-07 cropped](https://user-images.githubusercontent.com/22873928/153437975-13f5c66d-c78f-479c-8f78-136bb92d3b61.png)
This shows how it is after the cursor is originally in the position on the first line, and a new cursor is created below it, on the second line. The position on the second line is the same as that to which the cursor moves after the down arrow is pressed.

### Steps to Reproduce

1. Use a proportional font.
2. Have two lines with different characters.
3. Place the cursor on the top line not too close to the beginning of the line.
4. Move the cursor by pressing the down arrow to the next line.

The cursor probably won't be directly below the original position.

### Expected behavior

The cursor would be as close to the original position as possible, like it's in most other code editors and IDEs that I know.

**Comment by alexdima** [comment]
I acknowledge that this is a limitation we have. This problem is not limited to proportional fonts, it is also a problem with RTL, bidi text, or text with some emojis. The problem is that we want to support arrow up/arrow down for text outside of the viewport (e.g. adding multiple cursors at areas outside the viewport and then pressing arrow up/arrow down), yet we can only implement pixel offset based up/down movement on visible text. We can query the browser for character-level layout information only for the visible text.

**Comment by matj1** [comment]
> it is also a problem with … some emojis.

Is the problem with emojis caused by that the emoji glyphs have a double width in comparison to most glyphs in a mostly monospaced font?

> The problem is that we want to support arrow up/arrow down for text outside of the viewport (e.g. adding multiple cursors at areas outside the viewport and then pressing arrow up/arrow down), yet we can only implement pixel offset based up/down movement on visible text. We can query the browser for character-level layout information only for the visible text.

Can a line of text be rendered if it's outside of what's visible to the user by having a view larger than the editor window and showing only a part of the view or that each line of text with a cursor outside of what the user sees would be in its ow view which wouldn't be displayed? I don't know how Electron works in this regard; this is just a thought off the top of my head.
