### ISSUE TITLE
how can we lay side-bar and side panel at the same side

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#142742]
![image](https://user-images.githubusercontent.com/1876302/153436539-7030c80e-e09d-4401-bc4b-b719e977759b.png)

Another question， how can we lay like this?
(side-bar and side-panel are at the same side(left or right), and keep panel in bottom)

_Originally posted by @heartacker in https://github.com/microsoft/vscode/issues/141349#issuecomment-1035037128_

**Comment by heartacker** [comment]
Originally posted by @martin-braun in https://github.com/microsoft/vscode/issues/142819#issue-1132181909 

> First of all I love the new side panel, thank you for that. I'm really amazed by it's capabilities so far and the execution was well done, especially that I can even put things from the bottom panel into it.
> 
> Right now the new side-panel has to be on the opposite side of the explorer panel, but I would like to put the side-panel and explorer next to each other, so I end up with 3 columns like so:
> 
> ```
> +------------------------------+-------------+-------------+
> |                              |             |             | 
> |                              |             |             | 
> |                              |             |             | 
> |        Main Context          | Side Panel  |  Explorer   | 
> |                              |             |             | 
> |                              |             |             | 
> |                              |             |             | 
> +------------------------------+-------------+-------------+
> ```
> 
> It would be nice if the side-panel could be moved to the left or right in a similar fashion like the explorer panel or bottom panel.
> 
> I would welcome a context menu entry "move side panel to left/right" when right-clicking it:
> 
> <img alt="Screen Shot 2022-02-11 at 10 24 12 AM" width="273" src="https://user-images.githubusercontent.com/24259245/153566712-32bd5249-1b7d-4023-b16b-e3cde9b533a1.png">
> 
> This would really be helpful to use the full potential of the new side-panel. Some more background info why I want both panels next to each other:
> 
> I use an extension to auto-collapse the explorer panel and I use the side-panel for opened editors and outline. I hided tabs and use VSCode in portrait aspect ratio. When I open new files I expand the explorer panel or use a command to open a file and only the side-panel is seen permanently to de-clutter my session, I just keep all relevant files to my session open for quicker access. I wish to have both panels on the right side to make my work-flow simpler.
> 
> Thank you!

**Comment by vngmar** [comment]
Previously possible, now impossible; which equals "change no one asked for."

**Comment by martin-braun** [comment]
@vngmar Sorry, but this is wrong. The new side-panel didn't exist before, so it was not possible previously. There are more than enough linked issues to allow you to educate yourself before making a judgement.

**Comment by pbiggar** [comment]
I am also struggling with this issue. I used to have VScode laid out as follows:

```
+--------+--------+-------------+------------+
|   S    |        |             |            |
|   i    |        |             |            | 
|   d    |        |             |            |
|   e    | Panel  |   Code 1    |   Code 2   | 
|   b    |        |             |            |
|   a    |        |             |            |
|   r    |        |             |            |
|        |        |             |            |
+--------+--------+-------------+------------+
```

Now the panel won't go on the left anymore, and the Side Panel seems to only be allowed on the opposite side from the Side bar so I can't put everything on the right.

**Comment by pbiggar** [comment]
> @vngmar Sorry, but this is wrong. The new side-panel didn't exist before, so it was not possible previously. There are more than enough linked issues to allow you to educate yourself before making a judgement.

You used to be able to put the "panel" on the side, which AFAICT no longer is possible.

**Comment by ArturoDent** [comment]
You can put the Panel to either side with v1.64.2.  See the move panel command.

**Comment by carlfriedrich** [comment]
> You used to be able to put the "panel" on the side, which AFAICT no longer is possible.

@pbiggar It is possible with 1.64.2 again. See https://github.com/microsoft/vscode/issues/141349#issuecomment-1034871314.

**Comment by pbiggar** [comment]
thanks @carlfriedrich and @ArturoDent. I was just reading and found how this could be done. Deleted my comments but it seems you had already replied - appreciate the responses, will try 1.64.2 now!

**Comment by martin-braun** [comment]
@ArturoDent Oh good then, I thought you replied to us. Removing comments can cause some confusion. 😅

**Comment by beedell-roke** [comment]
https://github.com/microsoft/vscode/issues/183084#issuecomment-1557548891 is relevant.

**Comment by escalonn** [comment]
still waiting for this, especially with copilot around. i don't have a large display so i often keep panels closed when not in use, and any user story with a side effect of _moving the left margin of my open file_ is a massive UI fail for me. both primary and secondary panels need to be able to exist on the right side at the same time so that my code doesn't jump 600 pixels to the side just because i open a panel. copilot chat is clunky and annoying to use specifically because it pushes my code out of the way when i open it.
