### ISSUE TITLE
Extension debugging not working in notebook renderer sample

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#142774]
Issue Type: <b>Bug</b>

* `yo code`
* choose notebook renderer
* add some code to extension
* in launch.json, disable `"debugWebviews": true,`

breakpoints don't hit in `activate`. 

VS Code version: Code - Insiders 1.65.0-insider (Universal) (82a8bec63666b0883d9bf762ee2aaa87e9be9a3a, 2022-02-10T05:15:52.984Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.32GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --enable-proposed-api donjayamanne.jupyterpowertools --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api rchiodo.jupyter-tools --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.1
github-markdown-preview|bie|0.1.0
markdown-emoji|bie|0.2.1
markdown-preview-github-styles|bie|1.0.1
vscode-eslint|dba|2.2.2
kusto|don|0.3.8
gitlens|eam|11.7.0
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.2.0
codespaces|Git|1.5.2
copilot|Git|1.7.4924
remotehub|Git|0.24.0
vscode-pull-request-github|Git|0.37.2022021014
vscode-drawio|hed|1.6.4
handydandy-notebook|jak|0.1.0
fluent-icons|mig|0.0.16
vscode-fluent-icons|mig|0.0.1
theme-monokai-pro-vscode|mon|1.1.20
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestaticwebapps|ms-|0.9.0
vscode-docker|ms-|1.19.0
vscode-language-pack-zh-hans|MS-|1.64.6
csharp|ms-|1.24.0
python|ms-|2022.1.1814617073-dev
vscode-pylance|ms-|2022.2.2-pre.1
jupyter|ms-|2022.2.1001822818
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
notebook-renderers|ms-|0.0.1
remote-containers|ms-|0.220.0
remote-ssh|ms-|0.73.2022021015
remote-ssh-edit|ms-|0.73.2022021015
azure-account|ms-|0.9.11
azure-repos|ms-|0.4.0
hexeditor|ms-|1.9.4
js-debug-nightly|ms-|2022.2.917
powershell-preview|ms-|2022.2.0
remotehub-insiders|ms-|2021.6.302
vscode-github-issue-notebooks|ms-|0.0.113
vscode-js-profile-flame|ms-|0.0.24
vscode-markdown-notebook|ms-|0.0.26
vscode-notebook-history|ms-|0.0.1
vscode-selfhost-test-provider|ms-|0.3.8
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.1.0-dev
debugger-for-chrome|msj|4.13.0
vetur|oct|0.35.0
excalidraw-editor|pom|1.2.0
geo-data-viewer|Ran|2.5.0
jupyter-tools|rch|0.0.1
better-jupyter-errors|reb|0.0.1
toggle|reb|0.0.2
typing-practice|reb|0.0.1
vscode-code-renderer|reb|0.0.1
vscode-jupyter-checkpoint|reb|0.0.1
java|red|1.3.0
kuskus-extensions-pack|ros|1.0.10
kuskus-kusto-language-server|ros|1.0.20
kuskus-kusto-syntax-highlighting|ros|1.1.20
vsc-nwjs|rua|1.0.18
rust|rus|0.7.8
rest-book|tan|5.0.1
tldraw-vscode|tld|1.6.1
luna-paint|Tyr|0.13.1
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.6.10
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0
notebook-editing|vsc|1.0.0
vscode-test-resolver|vsc|0.0.1

(6 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Breakpoints are unbound, not matter if the source map is inline or external file.

**Comment by connor4312** [comment]
@rebornix having trouble reproducing. Did you make sure to add `activationEvents` to the extension? By default the template doesn't have (or need) any.

**Comment by rebornix** [comment]
@connor4312 i added activation events and console log works fine, only that breakpoints are unbound.

**Comment by connor4312** [comment]
Could you grab a trace log?

/jsDebugLogs

**Comment by rebornix** [comment]
[vscode-debugadapter-5b9ef8bf.json.gz](https://github.com/microsoft/vscode/files/8050863/vscode-debugadapter-5b9ef8bf.json.gz)

@connor4312 log is attached.

**Comment by rebornix** [comment]
@connor4312 helped figure out it's a webpack config issue which messed up with source map.
