### ISSUE TITLE
Insiders: "undefined - <email> (Microsoft)" displayed for MS Account

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#142776]
Issue Type: <b>Bug</b>

I think this was changed in recent builds.
In Accounts menu (Actions Bar) and in quick pick when settings sync are turned on and you need to pick account - `undefined` is displayed for Microsoft account.

Steps to reproduce:
1. Sign in with MS account
2. Click on Accounts to see menu

![image](https://user-images.githubusercontent.com/1312662/153502980-c031dea6-676a-4cb3-a365-896292883347.png)

VS Code version: Code - Insiders 1.65.0-insider (82a8bec63666b0883d9bf762ee2aaa87e9be9a3a, 2022-02-10T05:16:36.093Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (17.96GB free)|
|Process Argv|--crash-reporter-id cf52dbde-2c94-45c3-9bf3-45d8b9966b04|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by TylerLeonhardt** [comment]
@Yash621, would you like to fix this? Basically don't include the name if it's undefined. I can fix it next week when I get back from vacation unless you beat me to it

**Comment by Yash621** [comment]
@TylerLeonhardt for sure, enjoy you vacation and I will fix it till then!

**Comment by TylerLeonhardt** [comment]
@IllusionMH this should be fixed now. Can you verify for me?

**Comment by IllusionMH** [comment]
/verified

Now I only see email part which seems expected behavior (I also think that's what I saw in previous versions).

**Comment by IllusionMH** [comment]
@Yash621 @TylerLeonhardt thanks for the fix!
