### ISSUE TITLE
GitHub Auth Tas Client error

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#142778]
Looks like tas client might need updating in the github auth extension. I didn't want to go updating it without knowing the implications.

I see `(node:23759) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/lramos15/upstream/vscode/extensions/github-authentication/node_modules/tas-client/package.json' of './out/src/index'. Please either fix that or report it to the module author` when running OSS

**Comment by TylerLeonhardt** [comment]
Upstream: https://github.com/microsoft/tas-client/issues/9

I'll wait til the fix is released and then rev our version.

**Comment by TylerLeonhardt** [comment]
Updated vscode-tas-client here:
https://github.com/microsoft/vscode/commit/c254a23e721bda6905d7278e197025c18db97204
