### ISSUE TITLE
testing.iconSkipped theme color not used

### ISSUE THREAD

**Issue by iamfraggle** [microsoft/vscode#142783]
# Behaviour
## Expected vs. Actual

Expect skip icon in test explorer sidebar panel to be controlled by theme setting 'testing.iconSkipped'

## Steps to reproduce:

1. Create a unittest.py test suite
2. Preface a test with @unittest.skip("")
3. Run tests from Test Explorer view

PS - also, the theme system in vscode is not well documented in general and it is unclear when I should expect to see the following colors used.  If some additional information on this could be provided it would be very useful:

testing.iconQueued
testing.message.info.decorationForeground
testing.message.info.lineBackground

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.5
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: false
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "autopep8"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: true
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

insidersChannel: "off"

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

**Comment by JDaance** [comment]
Maybe related, the skip icon is not used in the gutter of the editor, making it difficult to note skipped tests when scrolling through the editor, since it looks very similar to passed tests.

Editor gutter (easily mistaken for passed tests due to the same green color):
![image](https://user-images.githubusercontent.com/1148112/154287738-bb8bcd1f-dd54-4ff6-98ba-b5ab902237b9.png)

Test tree (very clear that tests are indeed skipped):
![image](https://user-images.githubusercontent.com/1148112/154287781-1f7aa5b1-1680-4745-bfed-45596be818f6.png)

I would prefer the skip icon to be used in the editor as well (it was this way in the previous test explorer extension)

Holler at me if I should make a new issue instead
