### ISSUE TITLE
Tangles in notebook land

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#142724]
![image](https://user-images.githubusercontent.com/900690/153412038-425d0f05-2a40-41bf-9773-895b64796b4d.png)

I would have not expected `notebookRenderingCommon` to depend on anything.

**Comment by bpasero** [comment]
There is a similar tangle here:

![image](https://user-images.githubusercontent.com/900690/153412151-ce3668e9-0074-4c98-918b-89db179fae1f.png)

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/commit/baa9d84de0d5ab48e3821678599a5e5c533fd092 untangles the last comment

**Comment by rebornix** [comment]
Polished tangles and there is only one left now

<img width="367" alt="image" src="https://user-images.githubusercontent.com/876920/167190657-f2f2438a-e7c4-4431-8fcb-111a9f4d8cb1.png">

Fixing this would introduce more typing file, I would leave it this way for now.
