### ISSUE TITLE
Tangle `testingExplorerView` <=> `testExplorerActions`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#142722]
![image](https://user-images.githubusercontent.com/900690/153411560-3ad12908-9a6c-4a98-943d-de796abfb7d3.png)

Maybe instead of depending on the actions inside the view, the view could expose a contributable (`testing.contribution.ts`) menu that some menu contribution file contributes to?

**Comment by connor4312** [comment]
Test testing view only depends on command IDs, so I can pull those out to a different file like debug does
