### ISSUE TITLE
Copy and paste problem of pandas dataframe

### ISSUE THREAD

**Issue by kuelumbus** [microsoft/vscode#142750]
## Environment data
Version: 1.65.0-insider
Commit: 97c1e76d668d23d568044feb31083407f4c4b1ed
Date: 2022-02-07T08:57:29.966Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.10.92-14504-gce3218298464

-   Jupyter Extension version (available under the Extensions sidebar): 2022.2.1001822818
-   Python Extension version (available under the Extensions sidebar): 2022.1.1814617073-dev
-   OS (Windows | Mac | Linux distro) and version: Ubuntu
-   Python and/or Anaconda version: Python 3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): poetry
-   Jupyter server running: Remote 

## Behaviour

Copy and paste of a pandas dataframe pastes the cell content sometimes. Also, the context menu does not open on right-click on the mouse and the selection color does somehow change from blue to grey. 

https://user-images.githubusercontent.com/44866753/153435483-d1a09347-5b96-426f-bd2d-23ad37bcdd20.mp4

## Steps to reproduce:

```python
import pandas as pd
df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
df
```

**Comment by firegate22** [comment]
#142974 duplicate, sorry (just searched here after it was transferred to this repo).

**Comment by rebornix** [comment]
This should be fixed now.
