### ISSUE TITLE
Search text in interactive window

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#142748]
Is there a way to search text in the output displayed in the interactive window? I could not find a way to do It, although it is a very handy feature.

_Originally posted by @GitHunter0 in https://github.com/microsoft/vscode-jupyter/issues/1444#issuecomment-1034767503_

**Comment by gjsjohnmurray** [comment]
Is this a duplicate of #130587?

**Comment by greazer** [comment]
Yes, dupe of #130587
