### ISSUE TITLE
[Keybindings] "panelPosition" 'when' condition no longer working

### ISSUE THREAD

**Issue by SelfAdjointOperator** [microsoft/vscode#142749]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.1
- OS Version:

Steps to Reproduce:
The following used to allow me to swap my panel's position between bottom and right on-the-fly
```
    {
        "key": "shift+f4",
        "command": "workbench.action.positionPanelRight",
        "when": "panelPosition == 'bottom'"
    },
    {
        "key": "shift+f4",
        "command": "workbench.action.positionPanelBottom",
        "when": "panelPosition == 'right'"
    },
```
Now with the migration to `workbench.action.movePanelToSidePanel` and `workbench.action.moveSidePanelToPanel` the following does not work:
```
    {
        "key": "shift+f4",
        "command": "workbench.action.movePanelToSidePanel",
        "when": "panelPosition == 'bottom'"
    },
    {
        "key": "shift+f4",
        "command": "workbench.action.moveSidePanelToPanel",
        "when": "panelPosition == 'right'"
    },
```
It seems the `panelPosition` condition is not working.

**Comment by meganrogge** [comment]
works for me in insider's

This has already been fixed in Insider's and will be a part of our recovery release.

/duplicate https://github.com/microsoft/vscode/issues/142176

**Comment by SelfAdjointOperator** [comment]
Thank you!

**Comment by dankox** [comment]
@meganrogge Does it work for you for both moves? I tried the insider and it works for moving the panel to the side panel, but not back. Basically the condition `panelPosition == 'right'` doesn't trigger the command.
