### ISSUE TITLE
"editor.renderLineHighlight": "gutter"

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#14273]
Hey,

It will be a great if we can have an option to configure the way the current line is highlighted, and instead of having "complete line highlighted" or "nothing" :  

![capture d ecran 2016-10-24 a 13 18 40](https://cloud.githubusercontent.com/assets/5599375/19644870/6efde2e6-99f2-11e6-8787-9cfe58982e02.png)

can add a "gutter" highlight like sublime does : 

![capture d ecran 2016-10-24 a 13 18 19](https://cloud.githubusercontent.com/assets/5599375/19644871/6efdcf22-99f2-11e6-87f3-33e047e1def3.png)

**Comment by alexandrudima** [comment]
This has been implemented by @rebornix
