### ISSUE TITLE
Open  Multiple folders

### ISSUE THREAD

**Issue by mazhan465** [Microsoft/vscode#14271]
When I open a new folder,last folder must be close,but at some time this isn't what we want.
So,that's so fun if I can open multiple folders which arrange like project inVS.

**Comment by aluanhaddad** [comment]
At least you can open a new window with `ctrl + shift + n`, but what would be nice is to be able to right click a folder and select open in new window.

**Comment by saada** [comment]
https://github.com/Microsoft/vscode/issues/396
Duplicate
