### ISSUE TITLE
Bold highlighting causes misalignment in editor

### ISSUE THREAD

**Issue by rockboynton** [microsoft/vscode#142785]
Issue Type: <b>Bug</b>

Use a theme with bold font and see how things become slightly misaligned.

E.g. try this snippet of text:

```
AAAAAAAAAAA         = 1
BBBBBBBBBBBBBBBB    = 1
CCCCCCC             = 1
DDDDDDDDDD          = 1
EEEEEEEEEEE         = 1
FFFFFFFF            = 1
```
Theme with bold:
![image](https://user-images.githubusercontent.com/32227280/153514887-071591c1-443d-49a5-818f-2da78f214683.png)

Theme without bold:
![image](https://user-images.githubusercontent.com/32227280/153514976-9063eea9-6920-424c-b03d-f776a2ddb186.png)

E.g. try this snippet of text:

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.0-91-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (16.20GB free)|
|Process Argv|--crash-reporter-id 6da5d16f-f659-414e-8903-e16d034b5abf|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|Memory (System)|24.88GB (19.41GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ci-dev11|
|OS|Linux x64 5.4.0-91-generic|
|CPUs|AMD EPYC 7742 64-Core Processor (255 x 1493)|
|Memory (System)|503.70GB (27.85GB free)|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
Bookmarks|ale|13.2.3
Doxygen|bbe|1.0.0
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
better-cpp-syntax|jef|1.15.11
vscode-valgrind|kro|0.0.1
Kotlin|mat|1.7.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.217.2
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
material-icon-theme|PKi|4.12.1
scala|sca|0.5.5
rewrap|stk|1.16.1
vscode-icons|vsc|11.8.0
tms320c54x-support|Xie|0.0.1
spice|xua|0.1.0
vcode-ppc|zac|0.0.4
material-theme|zhu|3.13.19
linkerscript|Zix|1.0.2
TabOut|alb|0.2.1
doxdocgen|csc|1.3.2
gitlens|eam|11.7.0
shell-format|fox|7.2.2
elf-lens|Gra|0.1.1
better-cpp-syntax|jef|1.15.11
dbc|lha|1.2.3
compare-folders|mos|0.22.2
vscode-docker|ms-|1.19.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.1
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
hexeditor|ms-|1.9.4
html-preview-vscode|tht|0.2.5
vscode-decompiler|tin|0.0.8
gnu-mapfiles|tro|1.1.0
better-align|wwm|1.1.6

(9 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30435082
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vsrem710:30416614
dsvsc009:30436279

```

</details>

**Comment by alexdima** [comment]
In the editor area, we delegate all text rendering to the browser engine (Chromium). It uses the information present in the font to layout the text. It looks like with the font family you are using the bold characters are slightly wider than a non breaking space. I can recommend to try out a different font family, like [Cascadia Code](https://github.com/microsoft/cascadia-code) or [Fira Code](https://github.com/tonsky/FiraCode)

**Comment by rockboynton** [comment]
@alexdima Ahhh, I am using `Fira Code Retina` which leads to this problem. Changing it to `Fira Code` fixed it (although it isn't as nice looking imo 😕. Thanks!
