### ISSUE TITLE
Error while fetching extension. XHR failed.

### ISSUE THREAD

**Issue by ajayglory5** [microsoft/vscode#142705]
Does this issue occur when all extensions are disabled?: Unable to install even a single extension

- VS Code Version: 1.63.2 (used code_1.63.2-1639562499_amd64.deb to install)
- OS Version: Ubuntu 20.04.3 LTS

Steps to Reproduce:

1. Freshly installed VS code in Ubuntu 20.04.3
2. Open the tool and go to extension tab. Search for an extension to install, and the error is seen.
![Error](https://user-images.githubusercontent.com/21119553/153372701-a23c0120-1b41-4ffd-977b-ce83773a4523.png)

**Comment by ajayglory5** [comment]
@sandy081 can you please support.

**Comment by sandy081** [comment]
Can you please check the console and see what is the error?

- Open Developer Tools using command `F1: Toggle Developer Tools`

**Comment by linkrope** [comment]
```
 ERR Error: XHR failed
   at XMLHttpRequest.E.onerror (workbench.desktop.main.js:83)

POST https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery net::ERR_NAME_NOT_RESOLVED
```

BTW: same issue for me

**Comment by ajayglory5** [comment]
> Can you please check the console and see what is the error?
> 
> * Open Developer Tools using command `F1: Toggle Developer Tools`

`default.exp-tas.com/vscode/ab:1 Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED
workbench.desktop.main.js:577   ERR [Extension Host] (node:131928) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
workbench.desktop.main.js:77 [Extension Host] (node:131928) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `code --trace-deprecation ...` to show where the warning was created)
I @ workbench.desktop.main.js:77
workbench.desktop.main.js:577   ERR net::ERR_PROXY_CONNECTION_FAILED: Error: net::ERR_PROXY_CONNECTION_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:109:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED
workbench.desktop.main.js:577   ERR XHR failed: Error: XHR failed
    at XMLHttpRequest.C.onerror (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:27247)
workbench.desktop.main.js:77 [Extension Host] ApplicationInsights:CorrelationIdManager Array(1)
I @ workbench.desktop.main.js:77
workbench.desktop.main.js:77 [Extension Host] ApplicationInsights:CorrelationIdManager Array(1)
I @ workbench.desktop.main.js:77
workbench.desktop.main.js:77 [Extension Host] ApplicationInsights:CorrelationIdManager Array(1)
I @ workbench.desktop.main.js:77
workbench.desktop.main.js:577   ERR Error: XHR failed
    at XMLHttpRequest.C.onerror (workbench.desktop.main.js:85)
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED
vscodeexperiments.azureedge.net/experiments/vscode-experiments.json:1 Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED
workbench.desktop.main.js:577   ERR Error: XHR failed
    at XMLHttpRequest.C.onerror (workbench.desktop.main.js:85)
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED
workbench.desktop.main.js:577   ERR Error: XHR failed
    at XMLHttpRequest.C.onerror (workbench.desktop.main.js:85)
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED
DevTools failed to load source map: Could not parse content for https://ticino.blob.core.windows.net/sourcemaps/899d46d82c4c95423fb7e10e68eba52050e30ba3/core/vs/base/worker/workerMain.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/899d46d82c4c95423fb7e10e68eba52050e30ba3/core/vs/base/parts/sandbox/electron-browser/preload.js.map: Connection error: net::ERR_PROXY_CONNECTION_FAILED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/899d46d82c4c95423fb7e10e68eba52050e30ba3/core/bootstrap.js.map: Connection error: net::ERR_PROXY_CONNECTION_FAILED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/899d46d82c4c95423fb7e10e68eba52050e30ba3/core/vs/loader.js.map: Connection error: net::ERR_PROXY_CONNECTION_FAILED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/899d46d82c4c95423fb7e10e68eba52050e30ba3/core/bootstrap-window.js.map: Connection error: net::ERR_PROXY_CONNECTION_FAILED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/899d46d82c4c95423fb7e10e68eba52050e30ba3/core/vs/code/electron-browser/workbench/workbench.js.map: Connection error: net::ERR_PROXY_CONNECTION_FAILED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/899d46d82c4c95423fb7e10e68eba52050e30ba3/core/vs/workbench/workbench.desktop.main.js.map: Connection error: net::ERR_PROXY_CONNECTION_FAILED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/899d46d82c4c95423fb7e10e68eba52050e30ba3/node_modules/tas-client-umd/lib/tas-client-umd.js.map: Connection error: net::ERR_PROXY_CONNECTION_FAILED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/899d46d82c4c95423fb7e10e68eba52050e30ba3/node_modules/vscode-textmate/release/main.js.map: Connection error: net::ERR_PROXY_CONNECTION_FAILED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/899d46d82c4c95423fb7e10e68eba52050e30ba3/node_modules/xterm/lib/xterm.js.map: Connection error: net::ERR_PROXY_CONNECTION_FAILED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/899d46d82c4c95423fb7e10e68eba52050e30ba3/node_modules/xterm-addon-unicode11/lib/xterm-addon-unicode11.js.map: Connection error: net::ERR_PROXY_CONNECTION_FAILED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/899d46d82c4c95423fb7e10e68eba52050e30ba3/node_modules/xterm-addon-search/lib/xterm-addon-search.js.map: Connection error: net::ERR_PROXY_CONNECTION_FAILED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/899d46d82c4c95423fb7e10e68eba52050e30ba3/node_modules/xterm-addon-webgl/lib/xterm-addon-webgl.js.map: Connection error: net::ERR_PROXY_CONNECTION_FAILED`

**Comment by ajayglory5** [comment]
@deepak1556 @chrmarti @sandy081 any updates? I have provided the needed logs already.

**Comment by linkrope** [comment]
That's the result for me (same issue, but Ubuntu 21.04 and VS Code updated to 1.64.2):
[netlog.json.zip](https://github.com/microsoft/vscode/files/8118175/netlog.json.zip)

**Comment by chrmarti** [comment]
The DNS lookups fail. Can you access https://marketplace.visualstudio.com using Chrome or Chromium?

**Comment by linkrope** [comment]
Yes: with Chrome as well as with Firefox.
```
$ ping marketplace.visualstudio.com
PING marketplace.visualstudio.com(2620:1ec:a92::175 (2620:1ec:a92::175)) 56 data bytes
64 bytes from 2620:1ec:a92::175 (2620:1ec:a92::175): icmp_seq=1 ttl=53 time=24.4 ms
...
```

**Comment by linkrope** [comment]
Still an issue with 1.65.0

**Comment by chrmarti** [comment]
@deepak1556 Any idea what to look for here?

**Comment by linkrope** [comment]
That's bad: "needs-more-info" label has not been removed, although I provided all the information I was asked for.
The issue is not yet resolved. How can I reopen it? Report a new one?

**Comment by deepak1556** [comment]
@linkrope can you check if the issue repros with our latest insiders https://code.visualstudio.com/insiders/, if it does please attach netlog generated from this version. Thanks!

**Comment by linkrope** [comment]
OK: issue is avoided even with "Visual Studio Code" (no need for "Insiders") after I installed the .deb packages.
I uninstalled the snap package "code" via "Ubuntu Software" and reinstalled it, and I can confirm that I still get "XHR failed".

So: works for me after switching from snap to .deb. Thanks.
