### ISSUE TITLE
debug repl: unhelpful intellisense

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#14270]
- set breakpoint in line 1 and debug this program:
```javascript
var x = 1;
```
- in debug repl type 'x'

Observe: proposal menu appears with item '__dirname' selected.
Pressing 'return' appends '__dirname' to 'x'.

Expectation:
- type 'x' in in editor opens proposal menu with entry 'x' selected properly.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/14193
