### ISSUE TITLE
Search field is cleared when splitting settings menu

### ISSUE THREAD

**Issue by CarbonGhost** [microsoft/vscode#142733]
Issue Type: <b>Bug</b>

1. Enter a string into the settings search field.
2. Move the settings panel between being fullscreen, split horizontally, vertically, etc.
3. Search field will be empty.

VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:16:22.147Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (16.50GB free)|
|Process Argv|--crash-reporter-id 7e4333c8-1a22-4b00-816f-b39cfc00473d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (113)</summary>

Extension|Author (truncated)|Version
---|---|---
minimal-icon-theme|7ut|1.0.0
theme-cubed|Al3|1.0.3
vscode-unfancy-file-icons|ale|3.15.0
ng-template|Ang|13.2.3
icons-carbon|ant|0.2.4
material-icon-theme|art|0.0.5
chalice-icon-theme|art|1.2.17
intellij-theme|arz|1.10.0
vscode-browser-preview|auc|0.7.2
tailwind-docs|aus|1.4.0
vscode-icontheme-nomo-dark|be5|1.3.6
beardedicons|Bea|0.15.0
tailwindshades|bou|0.0.5
vscode-tailwindcss|bra|0.7.6
better-toml|bun|0.3.2
quill-icons|cdo|0.0.2
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.7.0
sharp-icons|Cib|1.1.1
magpix|cra|1.1.0
xpathtester|cre|1.2.0
postcss|css|1.0.9
vscode-mysql-client2|cwe|4.5.10
typewriter|dan|1.0.1
macos-modern-theme|dav|2.1.9
jshint|dba|0.11.0
vscode-eslint|dba|2.2.2
drkryz-theme|drk|1.5.1
rust-syntax|dus|0.6.0
gitlens|eam|11.7.0
vscode-html-css|ecm|1.11.0
vscode-npm-script|eg2|0.3.24
el-vsc-product-icon-theme|ElA|0.1.8
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.2.0
dark-taste-theme|fae|1.2.4
file-icons|fil|1.0.29
vscode-flatland-icon-theme|geb|0.0.6
vscode-glsl|GeF|0.2.3
base16-generator|gol|1.15.0
gc-excelviewer|Gra|4.0.50
headwind|hey|1.7.0
scarpet|ImU|0.1.14
monkey-patch|ioc|0.1.16
sf-symbols|j-f|2.2.0
easy-icons|jam|0.3.1
vscode-icontheme-js-nomo|jay|0.0.3
gruvbox-material-icon-theme|Jon|1.1.5
vs-one-dark-theme|jor|0.0.5
vscode-icon-theme|jtl|1.6.6
vscode-format-context-menu|lac|1.0.4
fluent-ui-vscode|lea|2.0.3
MagicPython|mag|1.1.0
jetbrains-icons|mar|1.1.0
rust-analyzer|mat|0.2.932
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.16
prettify-json|moh|0.0.3
theme-monokai-pro-vscode|mon|1.1.20
vscode-autoprefixer|mrm|3.0.1
vscode-stylefmt|mrm|2.6.2
vscode-docker|ms-|1.19.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.1
jupyter|ms-|2022.1.1001821375
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.1
live-server|ms-|0.2.12
powershell|ms-|2021.12.0
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.5330
vsliveshare-audio|ms-|0.1.91
rose-pine|mvl|2.0.0
color-highlight|nau|2.5.0
deepdark-material|Nim|3.3.0
origamid-next|ori|2.0.4
awesome-icons|pak|1.0.2
macos-dark-mode-theme|phi|1.0.2
material-icon-theme|PKi|4.12.1
material-product-icons|PKi|1.1.2
json-helper|pra|1.0.1
nextjs-snippets|Pul|0.0.5
java|red|1.3.0
vscode-yaml|red|1.4.0
LiveServer|rit|5.7.4
bootstrap-product-icons|rub|1.0.2
uniform-dark-theme|sae|1.5.0
nomo-dark-extended|Sen|1.4.2
crates|ser|0.5.10
vsc-material-theme-italicize|Ser|0.0.14
prettier-vscode|Sim|2.0.7
shader|sle|1.1.5
addDocComments|ste|0.0.8
code-spell-checker|str|2.1.6
rust-pack|Swe|0.2.29
resttext|Tat|0.1.2
ayu|tea|1.0.5
vscode-counter|uct|3.0.3
theme-generator|use|0.0.8
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0
vscode-icons|vsc|11.8.0
nextjs|Wil|0.0.8
vscode-nonicons|yam|0.0.10
city-lights-icon-vsc|Yum|1.1.3
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.13.19

(167 theme extensions excluded)

</details>

**Comment by rzhao271** [comment]
Is this the same as https://github.com/microsoft/vscode/issues/133444?

**Comment by CarbonGhost** [comment]
Yes, this is a duplicate issue.
