### ISSUE TITLE
Code-insiders > File > Open Folder  with Keyboard-shortcut  > is opening the Folder Prompt behind the Main Code-Insider Window - after todays update

### ISSUE THREAD

**Issue by rohan-paul** [microsoft/vscode#142710]
Code-insiders > File > Open Folder with Keyboard-shortcut is opening the Folder Prompt in behind the Main Code-Insider Window - after today's update. i.e. the prompt to select folder is opened in the background instead of the foreground.

So then I have to click on the second window (i.e. the prompt that is opened in the background ) to select my Folder.

Step to reproduce => In Keyboard just press Ctrl + K and then immediately Ctrl + O

But this problem will NOT happen, if instead of the Keyboard shortcut, I just go to File > Open Folder. 

Insider Version 
```
Version: 1.65.0-insider
Commit: 82a8bec63666b0883d9bf762ee2aaa87e9be9a3a
Date: 2022-02-10T05:16:52.926Z
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Linux x64 5.13.0-28-generic
```
My Machine is - Ubuntu 20.04

**Comment by bpasero** [comment]
![Recording 2022-02-10 at 13 34 07](https://user-images.githubusercontent.com/900690/153409525-12b01a36-844f-444c-b9ff-de5e937f5e3c.gif)

I cannot reproduce, same Ubuntu.

**Comment by rohan-paul** [comment]
The problem continues for me though. Not sure, if something else in Ubuntu is causing this behavior.
