### ISSUE TITLE
Too many "Save before ..." preferences (task, debug, testing)

### ISSUE THREAD

**Issue by dinofx** [microsoft/vscode#142765]
TL;TD, "Save before doing X" preferences should be replaced with, or at least default to inheriting from, some common preference.

## Details
As VSCode continues to add more and more great features, there is a growing list of "Save before" preferences that need to be manually discovered and modified by users.  I'm aware of at least 3:

```
  "task.saveBeforeRun": "never",
  "debug.saveBeforeStart": "none",
  "testing.saveBeforeTest": false
```

I prefer if VSCode never saves a file for me.  Maybe I temporarily typed a phone number, or accidentally pasted a password, or I'm just in the middle of editing code.

I originally noticed this behavior when debugging code and modified that preference.  Then I noticed it appeared again when I started using build tasks more often.  I encountered a third preference when I started using the Jest extension.

Also strange is the fact that each one of these preferences offers different choices.  For example, only the "Run" preference supports prompting.

## The Ask
These preferences should standardize on one set possible behaviors. This would be a prerequisite to then having these prefs inherit from some higher-level preference.

**Comment by roblourens** [comment]
Maybe we could align these, but they might not be trying to handle all the same cases. For example, in debug we are thinking about users who start typing in a new untitled file and try to debug it, but the other features probably don't have a similar common scenario.

**Comment by alexr00** [comment]
The tasks one is for saving all dirty files in the workspace before a task is run. That doesn't sound that different from the debug scenario.

**Comment by connor4312** [comment]
Debug is also different than testing, for example, in that testing is uninterested in saving untitled files; as far I know no test system/extension has had a use case for that.

While in retrospect using consistent values for the string enums may have been nice, I don't think we gain much from trying to align them to a greater degree.

**Comment by roblourens** [comment]
@alexr00 But you aren't trying to save untitled editors before running a task right?

I agree that there isn't that much to gain, and we lose flexibility, in particular debug has seen some churn and discussion around those settings.

I would say that Testing could probably avoid future pain by using an enum here though! :)

**Comment by dinofx** [comment]
In the repos where I noticed these, saving dirty editors doesn't guarantee much.  For example, saving a *.ts file doesn't guarantee that a tsc watch process will finish transpiling before debugging has loaded stale output. In my testing scenario, webpack was running in watch mode, and the output of the webpack build is used by the jest tests.  Again, jest could still load the stale webpack output even though dirty editors were saved.

At a very minimum, I would argue that default preferences should err on the side of not writing user content to disk.  I think at least the debug defaults to prompting the user.

**Comment by alexr00** [comment]
@roblourens no, we're not trying to save untitled editors before running a task. 

@dinofx many users have probably come to rely on the default behavior of dirty files being saved before running a task, and changing it to the `"promp"` option will result in a notification being shown to many users who don't want to see it. I don't think we should change the default behavior for tasks. 

Maybe Testing could align with the tasks enum values.

**Comment by dinofx** [comment]
If the prompt had a checkbox not to not ask again (i.e. setting the pref to "always") it seems like a minor inconvenience compared to avoiding possible code loss (workspaces not using git) or committing unintended edits.

**Comment by roblourens** [comment]
> For example, saving a *.ts file doesn't guarantee that a tsc watch process will finish transpiling before debugging has loaded stale output. 

Yeah, but if you have it all put together with a preLaunchTask then that will work.

In any case, trying to align settings across features will just lead to endless discussions about different cases and scenarios, so we should just do what is right for our feature.
