### ISSUE TITLE
Add Pin Tabs

### ISSUE THREAD

**Issue by Dirett** [Microsoft/vscode#14278]
- VSCode Version: 1.6.1
- OS Version: Mac

Feature Request: 

Add Pin Tabs to VS Code like Visual Studio has which allows you to Pin Tabs effortlessly

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by dmay** [comment]
For those who come from google - here is open issue https://github.com/Microsoft/vscode/issues/12622
