### ISSUE TITLE
spawn comes with a broken locale and $LANG

### ISSUE THREAD

**Issue by artagnon** [microsoft/vscode#142857]
This is most probably a bug in:

```
$ code -v
1.65.0-insider
bb221a61d29deabd99ee9431736d04f2175cb596
x64
```

as it cannot be reproduced on `1.64`.

My system locale is:

```
$ locale
LANG="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_CTYPE="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_ALL=
```

I observed the problem in James-Yu/LaTeX-Workshop#3081 -- it uses a package called 'cross-spawn' (which boils down to an Electron spawn) to spawn a subprocess. Now, if that certain subprocess checks for a valid locale, then the task fails. This is because spawn seems to use `LANG=fr`, which is an invalid version of `LANG=fr_FR.UTF-8`. I found this out by stepping through the code. I can confirm that the problem is not in the `cross-spawn` package itself, as the same versions of `James-Yu/LaTeX-Workshop` were operating on both versions of vscode.

I'm a little tired, and don't have the motivation to cook up a reduced case at the moment, but please feel free to ask for more information.

**Comment by StephenWeatherford** [comment]
Note: This is a severe regression for all extensions that depend on the https://github.com/dotnet/vscode-dotnet-runtime.  From the investigation there (thanks @sihde!):

1) Does not repro in released version 1.64.2 but does repro in 1.65.x-insiders
2) Running the dotnet install script manually suceeds (from outside vs code and in the vscode terminal) but fails when run by the vscode-dotnet-runtime extension (see https://github.com/dotnet/vscode-dotnet-runtime/blob/fe54a616a8a8df2a507028474a56b5b5423de734/vscode-dotnet-runtime-library/src/Acquisition/AcquisitionInvoker.ts#L39)

**Comment by tamuratak** [comment]
Version: 1.65.0-insider (Universal)
Commit: 50089c3f92c17584a4aca179f51f220b56c22020
Date: 2022-02-14T05:17:15.582Z
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Darwin arm64 20.6.0

I am one of  the maintainers of LaTeX Workshop.

I have confirmed that when starting VS Code Insiders from Dock, the environment variable `LANG` of the extension host is set as `ja`. On the stable version of VS Code 1.64.2, it is `undefined`.

When starting VS Code Insiders from Terminal.app, it is set as `ja_JP.UTF-8`.

The root cause is that `ja` is **NOT** a valid locale. VS Code Insiders picks an invalid locale as a default locale.

```
$ locale -a | grep ja
ja_JP.SJIS
ja_JP
ja_JP.UTF-8
ja_JP.eucJP
```

**Comment by sihde** [comment]
> I have confirmed that when starting VS Code Insiders from Dock, the environment variable `LANG` of the extension host is set as `ja`. On the stable version of VS Code 1.64.2, it is `undefined`.

Thanks @tamuratak . This allows me to reproduce the .NET installation error message in dotnet/vscode-dotnet-runtime#397:

```
$ LANG=ja tar xf /dev/null
tar: Failed to set default locale
```
Same for LANG=en, etc. This is the same error that `tar` emits when the .NET installation fails.

I also confirmed that when starting VS Code Insiders from the command line (where, in my case, `LANG=en_US.UTF-8`), it works correctly. 

So, it seems this is breaking multiple extensions.

**Comment by tamuratak** [comment]
@rzhao271  It might be related to #141095

**Comment by deepak1556** [comment]
\closedWith https://github.com/microsoft/vscode/commit/e8cfc68ce46c5868d53af90064a731233e80c829
