### ISSUE TITLE
Remove transition on position for terminal decorations

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#142847]
Looks like the transition is causing the animation when scrolling the terminal:

![Recording 2022-02-11 at 06 29 56](https://user-images.githubusercontent.com/2193314/153610137-622a5206-6722-43f7-bbf6-9ddd654bcbfa.gif)

**Comment by meganrogge** [comment]
Going with the codicon and will do the background highlight that we do for other buttons instead of the scale transform
