### ISSUE TITLE
Diff view doesn't allow staging specific lines

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#142874]
Issue Type: <b>Feature Request</b>

STR:
- Open unstaged changes in SCM, opens diff view
- Right-click removed text lines

<img width="643" alt="image" src="https://user-images.githubusercontent.com/8599/153657366-6098fe08-c063-45b9-ae09-f2cb70f070ad.png">

AR: Offers revert or copy menus
ER: Menu for staging selected changes

Clicking the green text offers to stage and unstage.

VS Code version: Code - Insiders 1.65.0-insider (82a8bec63666b0883d9bf762ee2aaa87e9be9a3a, 2022-02-10T05:15:52.984Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

**Comment by lszomoru** [comment]
The diff editor now support staging block/selection as well as reverting block/selection.
