### ISSUE TITLE
Since latest update I'm getting "It's taking a while to configure your breakpoints." message

### ISSUE THREAD

**Issue by MarByteBeep** [microsoft/vscode#142830]
Issue Type: <b>Bug</b>

I have a Javascipt only application, with no transpiling or conversion going on. My `launch.json` is like this:

```
{
	"type": "node",
	"request": "launch",
	"name": "Fetch",
	"program": "${workspaceFolder}/exec.js",
	"args": ["fetch.js"],
	"outputCapture": "std",
	"skipFiles": [
		"${workspaceFolder}/node_modules/**/*.js",
		"${workspaceFolder}/lib/**/*.js",
		"<node_internals>/**/*.js"
	]
},
```

Exec.js is just a wrapper that executes a method in `fetch.js`.

Starting this program now *sometimes* takes a long time and I get the following warning:

```It's taking a while to configure your breakpoints. You can speed this up by updating the 'outFiles' in your launch.json.```

I only have a few breakpoints, nor was this causing a problem before the update. What's changed? And why am I advised to update `outFiles` while I'm only running a simple javascript script?

VS Code version: Code - Insiders 1.65.0-insider (82a8bec63666b0883d9bf762ee2aaa87e9be9a3a, 2022-02-10T05:16:36.093Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.72GB free)|
|Process Argv|--crash-reporter-id 82b0b2fc-aa31-4181-9863-56bf85ed5e36|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstartedc:30421358
vsclayoutctrt:30405800
dsvsc008:30436272
pythonvspyt640:30426300
vsbas813:30436447
vscscmwlcmc:30428972
azactmsal:30432848

```

</details>

**Comment by maowenzhang** [comment]
We met same issue at VSCode 1.64.2, it becomes super slow to get debug started. Tried a workaround is adding outFiles in the launch.json config. 
Also tried go back to old VSCode 1.63.2, which doesn't have this issue.

**Comment by MarByteBeep** [comment]
I've sent the log to that mail address.  I've tried parsing it using your online tool, and it seemed to work, but I couldn't see some sort of share button. If you need anything else, let me know!

**Comment by connor4312** [comment]
@roblourens did something change in ripgrep in the last release? It looks like the time is all spent in `findTextInFiles`. The only change js-debug made is that where previously it would have searched with

```
{ include: new vscode.RelativePattern(workspaceFolder, '**/*.js'), exclude: '**/node_modules/**' }
```

it now also includes an excluding explicitly using the workspace folder, like

```
{ include: new vscode.RelativePattern(workspaceFolder, '**/*.js'), exclude: `**/node_modules/**,${workspaceFolder}/**/node_modules/**` }
```

**Comment by cdaringe** [comment]
For the Javascript Debug Terminal, I'm not sure which `attach` configuration to plop `trace` into. Any advice--I'd like to do some profiling as well :)

**Comment by roblourens** [comment]
No change to ripgrep or relevant search code that I can think of

**Comment by knaos** [comment]
I confirm our team has the same issue in the latest release.

**Comment by knaos** [comment]
Following the advice from issue #140427 to start VsCode with --disable-gpu flag fixes the problem.

**Comment by connor4312** [comment]
That is quite surprising... can anyone else in the thread verify whether the same steps fix it for them?

**Comment by nickchomey** [comment]
I have this issue as well. `--disable-gpu` didn't help for me, however. As per the previous comment, I tried using just my laptop screen rather than only external monitor and that didn't help either.

**Comment by connor4312** [comment]
Are the size of your workspaces very large? For instance, do you hit this issue on smaller, trivial repos, or only larger ones?

**Comment by cdaringe** [comment]
> Are the size of your workspaces very large?

**Very**. We are in a monorepo

> do you hit this issue on smaller, trivial repos

No

**Comment by nickchomey** [comment]
> Are the size of your workspaces very large? For instance, do you hit this issue on smaller, trivial repos, or only larger ones?

Yes. It's an entire WordPress website with many plugins

**Comment by connor4312** [comment]
It sounds like both your cases are expected, and that you want to follow the message's instructions to configure your outFiles: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-map-discovery

**Comment by cdaringe** [comment]
We used to explicitly use the legacy debugger, as it was plenty performant in our large repository. VSCode forced upgraded us to use the new debugger, which is more-or-less unusable due to this issue, and forced our users to use `chrome` debugger. VSCode debugger is certainly less preferred--users don't need the editor 😄 . Our project uses `ts-node` for the scripts relevant for debugging, so `outFiles` unfortunately is not an option for us--albeit we did entertain the message.

**Comment by connor4312** [comment]
For `ts-node`, the `outFiles` can be specified to point to your source files. Alternatively, you can set `outFiles` to an empty array `[]` and `resolveSourceMapLocations: null` to say "don't scan for any sourcemaps, but also don't restrict where sourcemaps can be resolved".

**Comment by MarByteBeep** [comment]
> Are the size of your workspaces very large? For instance, do you hit this issue on smaller, trivial repos, or only larger ones?

My repo is very small, only a dozen files, none of them exceeding 1000 lines of code. It does use quite a bunch of npm modules, but obviously I never set a BP in that code.

**Comment by connor4312** [comment]
Hm, okay, thanks. Seems like something is up with your machine separate from the expected behavior that cdaringe/nickchomey are running into.

Quick check -- do you have any 3rd party antivirus running? Often seen them mess with things and cause spooky slowdowns.

**Comment by MarByteBeep** [comment]
No AV here. I do have multiple versions of Visual Studio though. Would a dxdiag or other report be useful for you?

**Comment by nickchomey** [comment]
> It sounds like both your cases are expected, and that you want to follow the message's instructions to configure your outFiles: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-map-discovery

Thanks very much, this solved my problem. Apologies for the trouble!

**Comment by knaos** [comment]
@connor4312 I confirm that running Code with flag `--disable-gpu` is not fixing the issue. It was just some coincidence. 
Anyways with VSCode 1.64.2 on Windows 10, the debugger takes ages to start. And this happened to all our team mates after they upgraded to the newer version.

**Comment by connor4312** [comment]
@knaos does setting your `outFiles` to a more specific path resolve the issue for you? https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-map-discovery

**Comment by AlCalzone** [comment]
I'm seeing the same issue in a TypeScript monorepo. I'm transpiling the ts files for debugging on the fly using `esbuild-register`, which has inline sourcemaps, so specifying the out files is off the table for me.
Before the recent VSCode update, debugging worked flawlessly and without much delay.

**Comment by weinand** [comment]
@AlCalzone the `outFiles` glob patterns specify the locations of the **generated JavaScript**. So there is no issue with inlined sourcemaps.

**Comment by AlCalzone** [comment]
@weinand I'm not seeing the original TS sources though when debugging this way. The breakpoints end up in some generated files which contain a sourcemap comment at the end. Note that there are no generated .js files on disk, because the .ts files are transpiled similar to how `ts-node` does it (except using esbuild which is faster).

**Comment by connor4312** [comment]
@AlCalzone please see https://github.com/microsoft/vscode/issues/142830#issuecomment-1048240356

**Comment by AlCalzone** [comment]
```json
"outFiles": [],
"resolveSourceMapLocations": null,
```
does the trick 👍🏻

Still weird that this used to work before, but now VSCode becomes unusable after debugging without this configuration. When the `It's taking a while to configure your breakpoints.` message is shown, debugging gets stuck and I have to restart VSCode to be able to use it again.

**Comment by connor4312** [comment]
I think it would be reasonable to automatically configure the config like that if we see the `runtimeExecutable` is `ts-node` or similar.

A nicer way that would solve lots of problems is if the debugger could do a "test run" of the program to see how it's configured and then automatically update the launch.json appropriately... https://github.com/microsoft/vscode-js-debug/issues/1214

**Comment by AlCalzone** [comment]
> automatically configure the config like that if we see the `runtimeExecutable` is `ts-node` or similar.

I think this heuristic is going to be interesting. In my case, the runtime config is this:
```jsonc
			"runtimeExecutable": "yarn",
			"runtimeArgs": [
				"node",
				"--async-stack-traces",
				"--inspect-brk=9229",
				"-r",
				"esbuild-register",
				"${workspaceFolder}/test/run.ts"
			],
```

**Comment by connor4312** [comment]
We could see flags like `-r`/`--register` pretty easily, and we already parse runtimeArgs for other reasons. But if you had a launch config which just runs something like `npm run start` or a custom shell script, we can't see that.

**Comment by meetgaurang** [comment]
We are having a mono-repo project. Suggested solution to add `"outFiles": [],"resolveSourceMapLocations": null,` didn't work. This specific issue happens only with the VSCode version `1.64.2`. The moment we switch back to previous version `1.63.2`, the problem disappears. Our `launch.json` looks like this,

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${file}",
      "outFiles": [],
      "resolveSourceMapLocations": null,
    }
  ]
}
```

**Comment by connor4312** [comment]
@meetgaurang please collect trace logs using the instructions in the 2nd comment

**Comment by AlCalzone** [comment]
@connor4312 here's a trace where NO breakpoint is set:
[vscode-debugadapter-c18555ee.json.gz](https://github.com/microsoft/vscode/files/8176289/vscode-debugadapter-c18555ee.json.gz)

and here's the same situation but with an existing breakpoint, which took roughly 5 minutes to resolve:
[vscode-debugadapter-b587cb99.json.gz](https://github.com/microsoft/vscode/files/8176349/vscode-debugadapter-b587cb99.json.gz)

**Comment by meetgaurang** [comment]
I confirm that we no longer face this issue with the recent release - 1.65.0. It seems to be fixed.

**Comment by MarByteBeep** [comment]
Any idea what might have fixed it? I'll update and verify as well tomorrow.

**Comment by AlCalzone** [comment]
Can confirm, 1.65.2 does work like 1.63.x

**Comment by jefersonlucio** [comment]
This problem started to bug me about 3 weeks ago, when I updated to 1.67.2 (OS Windows_NT x64 10.0.19044). Adding "--disable-gpu" to VSCode's shortcut icon solved it immediately.
