### ISSUE TITLE
Creating a new jupyter notebook in an empty workspace with vanilla VS Code is thorny

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#142872]
Creating a new jupyter notebook out of the box in en empty workspace has too many rough edges.

1) Create a new `ipynb` file in the explorer: This works mostly correctly. The notebook editor opens as expected. What is not great is that there is an empty code cell with `Plain Text` as language type. `Plain Text` is never a good code cell language. Contrary to empty text editors, we don't show any hint in the editor toward choosing/determining the language.

2) Out of the box the `File > New ...` does not exist. So, if I go through the File menu, the only way to create a new notebook is using `File> New File` and then save it as a `ipynb` file.  (This is also a common workflow for keyboard users> <kbd>Cmd</kbd>+<kbd>N</kbd> followed by <kbd>Cmd</kbd>+<kbd>S</kbd>.) At that moment we keep the editor type as text editor and change the language id to `Jupyter (JSON)` which is unexpected.  By default we should switch to the notebook editor. Currently, they user has to know to go through the `Open with...` motion themselves.

3) In scenario 2, if I add a few empty lines to the untitled text file before I try to open it with the notebook editor, we fail because of "Unexpected end of JSON input." and I'm stuck. We should treat a file with only whitespace characters in it the same way we treat an empty file.

4) Even if `File > New ...` exists (because I have for example an image editor installed), it does not provide a new Jupyter notebook entry. Out of the box, the Jupyter extension is not installed. We prompt users to install it when they open a `ipynb` file. Since this is an empty workspace,  we have a catch-22. Since we already understand `ipynb` files out of the box, we should support creating new Jupyter notebook files.
 
5) Creating an untiled file and using the language status bar item I can change the language type to `Jupyter (JSON)` only. There should also be an entry for `Jupyter` flipping me directly into a notebook editor.

**Comment by rebornix** [comment]
Thank you for the summary. Here are some ideas we discussed before around how to improve these 

> So, if I go through the File menu, the only way to create a new notebook is using File> New File and then save it as a ipynb file. (This is also a common workflow for keyboard users> Cmd+N followed by Cmd+S.) At that moment we keep the editor type as text editor and change the language id to Jupyter (JSON) which is unexpected. By default we should switch to the notebook editor

cc @lramos15 . It makes good sense to open the editor in notebook as we are renaming an untitled file to a file type which is supported by a "custom" editor. If this is users' first time ever opening/creating an ipynb file we can ask if they want to keep this behavior (like how we prompt when we have a new extension contributing custom/notebook editor).

> What is not great is that there is an empty code cell with Plain Text as language type
> ...
> if I add a few empty lines to the untitled text file before I try to open it with the notebook editor, we fail because of "Unexpected end of JSON input."

IMHO the default language can be Python, which is the common used one. If the untitled file is not empty, maybe we should open a notebook with a single cell with all the content. The language id for the cell can either be Python, or the language from the Language Auto Detect.

> Creating an untiled file and using the language status bar item I can change the language type to Jupyter (JSON) only

A prototype we did before, merging editor/viewtypes into the language picker https://github.com/microsoft/vscode/pull/93669#issue-589661829 , we didn't continue on this idea when we have the `File -> New ...` available. 

![Kapture 2020-03-28 at 14 20 21](https://user-images.githubusercontent.com/876920/77834119-63b50300-70ff-11ea-9bef-db7e961f9aff.gif)

**Comment by lramos15** [comment]
> cc @lramos15 . It makes good sense to open the editor in notebook as we are renaming an untitled file to a file type which is supported by a "custom" editor. If this is users' first time ever opening/creating an ipynb file we can ask if they want to keep this behavior (like how we prompt when we have a new extension contributing custom/notebook editor)

A similar discussion has occurred before here https://github.com/microsoft/vscode/issues/81832

**Comment by misolori** [comment]
In the past we discussed possibly showing alternate file types via a separate category that can prompt users to install but we it gets tricky trying to decide what would show up here:

<img width="636" alt="CleanShot 2022-02-11 at 15 40 01@2x" src="https://user-images.githubusercontent.com/35271042/153685112-cb800f98-da31-412f-b4a8-00b266b96910.png">

**Comment by dynamicwebpaige** [comment]
`File -> New...` behavior for several alternate IDEs displayed below. It is interesting to note that PyCharm -- which is focused more on Python web and application developers -- does *not* list a notebook in their `File -> New...` flow; while IDEs that are targeted at data science and scientific computing do.

| IDE | Image |
| --- | --- |
| JupyterLab | <img width="530" alt="Screen Shot 2022-02-14 at 9 32 08 AM" src="https://user-images.githubusercontent.com/3712347/153917876-182aff0d-97a9-4b16-a3dc-7ae58392c0f8.png"> |
| PyCharm: Community Edition | <img width="224" alt="Screen Shot 2022-02-14 at 9 36 35 AM" src="https://user-images.githubusercontent.com/3712347/153917988-c31a0692-51f2-4681-af2f-cb9f0975c532.png"> |
| DataSpell | ![image](https://user-images.githubusercontent.com/3712347/153918154-ffae65c6-b70c-4dfb-8b87-4b25c16eeadf.png) |

**Comment by rebornix** [comment]
`File -> New...` is appealing as we are expanding what you can open in the editor group, e.g., text file, notebook, and also terminal. Technically this can be used for opening anything which VS Code supports, the structure will be the same as @greazer 's second proposal

```
File ->
  New File
  New ...  ->
      Notebook
      Luna Paint
      Terminal
      Search custom* editor on marketplace
  New Window
```

On which we still keep Open File and Open Window as shortcuts.

In addition to IDEs @dynamicwebpaige shared above, here is how Xcode's File menu looks, it's a mix of opening window, projects, editor, and a submenu for picking file types

<img width="568" alt="image" src="https://user-images.githubusercontent.com/876920/154113007-2bee9143-dd68-41dd-bcf2-de2a5fc26d00.png">

**Comment by rebornix** [comment]
> Even if File > New ... exists (because I have for example an image editor installed), it does not provide a new Jupyter notebook entry. Out of the box, the Jupyter extension is not installed

This is currently contributed by the Jupyter extension to allow it support choosing languages when users attempt to create a notebook. We can probably register one from the core when there is no Jupyter extension installed or even better having the logic in the core if that's not complicated.

**Comment by rebornix** [comment]
We have push some changes for the out of box file opening workflow during the last few days. We have tackled most of the rough edges originally listed the issue description https://github.com/microsoft/vscode/issues/142872#issue-1132997174 , which includes

> What is not great is that there is an empty code cell with Plain Text as language type. Plain Text is never a good code cell language
1. The default language for a cell will be set to `python`, which is the widely used language in Jupyter notebooks. It's not perfect but it's better than showing plain text as users always have to change the language through the language picker. Follow ups will be experimenting either language detection for untitled notebook, or using information from the kernels (which has "supported languages"). @misolori had design mock up for this before.

> the only way to create a new notebook is using File> New File and then save it as a ipynb file. (This is also a common workflow for keyboard users> Cmd+N followed by Cmd+S.) At that moment we keep the editor type as text editor and change the language id to Jupyter (JSON) which is unexpected
2. With @lramos15 's change, when saving untitled file to `*.ipynb` files, it will save the content and then immediately open it in a notebook editor.

> In scenario 2, if I add a few empty lines to the untitled text file before I try to open it with the notebook editor, we fail because of "Unexpected end of JSON input." and I'm stuck. We should treat a file with only whitespace characters in it the same way we treat an empty file.
3. We would trim whitespaces in this case to ensure that the file can be opened successfully. Supporting corrupted ipynb file is a bigger item and we need to tackle this separately, we may need to have some heuristics of how to resolve the corruption:
  * If the content is Python, we might want to open a notebook with a python cell 
  * If the content is corrupted JSON (say containing comments, or redundant comma), we may want to open a notebook with a JSON cell. Users can get a chance to fix the error with the help of JSON language service
  * If the content contains merge conflict, we might need to be creative here. It can be opened in a notebook diff editor with actions to choose which one to save to disk
 
> Since we already understand ipynb files out of the box, we should support creating new Jupyter notebook files
4. We would now contribute a `File -> New` entry if Jupyter is not installed/enabled but hide it once users have Jupyter

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/876920/154346392-d85b012e-83f4-475c-9d39-52f3e268ba72.png">


> Creating an untiled file and using the language status bar item I can change the language type to Jupyter (JSON) only. There should also be an entry for Jupyter flipping me directly into a notebook editor.
5. We now removed `Jupyter (JSON)`, users won't get confused if they see this on language status bar item if they open the ipynb file in text editor. 


Fixes mentioned above will all be available from tomorrow's Insiders.

**Comment by misolori** [comment]
To extend what @rebornix has mentioned, I've also been looking at improving the overall experience of the `New File...` UX and have a proposal that introduces a new set of `New {other files}` from the app menu and welcome page. Additionally for notebooks, we'd like to propose that when a user selects `Notebook (ipynb)` from the language selector that we auto-switch to the notebook UI, since ipynb is still a valid file type. Would love to get feedback from everyone here on this proposed experience and how it scales out to other file types.

[<img width="943" alt="CleanShot 2022-02-17 at 15 11 57@2x" src="https://user-images.githubusercontent.com/35271042/154587140-3ca9fe47-5815-406a-8abb-d4388bad8663.png">
](https://www.loom.com/share/ca801472be08483a9dc57f74f81040cc)

**Comment by DonJayamanne** [comment]
Closing this issue as completed as we now have a better workflow and UX for createing new notebooks
