### ISSUE TITLE
"Follow link" path is resolved incorrectly if package.json exists within SCSS project.

### ISSUE THREAD

**Issue by slynagh** [microsoft/vscode#142836]
Functionality doesn't exist in latest insiders version - could not test.

Does this issue occur when all extensions are disabled?: Yes

VSCode version: 1.64
OS version MacOS Big Sur 11.6.2

Steps to reproduce:

1. Create a project with this structure:
- src
  - foo
    - _foo.scss
  - _bar.scss
 
2. Add this line to `_foo.scss`
```scss
@use "../bar";
```
3. Hover over "../bar" and cmd-click to successfully follow link. 

4. Add a `package.json` file to the project and repeat step 3. File is not found. Creating it from dialog shows it is incorrectly resolving to to the wrong path.

**Comment by slynagh** [comment]
A quick update: Navigating to folder paths work ie: if `bar/_index.scss` exists at the path rather than the file `_bar.scss`.
I have now rolled back to VSCode v 1.63.2 and the issue does not occur.

**Comment by sKopheK** [comment]
hi, any better workaround besides rolling back to previous version?

**Comment by fsufitch** [comment]
It works if you do `@use '../_bar.scss'`, but both the underscore and file extensions are necessary. Thankfully, `scss` itself doesn't complain that they're there, but it's quite ugly.

**Comment by sKopheK** [comment]
found out, it's not about filename (extension, missing underscore etc.), but the path
specifying absolute path opens file correctly

the first one won't work, the second will
```
@import "../../../../v1/conf/paths";
@import "/scss/_public/v1/conf/paths";
```

**Comment by slynagh** [comment]
Any update on this @aeschli? I can literally make the follow path function work properly by renaming my `package.json` file to `_package.json`. Why would vscode be doing this?
