### ISSUE TITLE
Inability to use Check50 and submit 50

### ISSUE THREAD

**Issue by Tomileye** [microsoft/vscode#142848]
ADD ISSUE DESCRIPTION HERE

Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
User Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
Embedder: codespaces

Any time I try to use the check 50  it shows error

**Comment by IllusionMH** [comment]
/needsMoreInfo

What is "check 50 function" is it from an extension?
