### ISSUE TITLE
Cannot connect to remote machine on VS Code Insiders

### ISSUE THREAD

**Issue by andrew-weisman** [microsoft/vscode#142880]
Issue Type: <b>Bug</b>

The past couple days I have tried to connect to a remote machine as usual but now it fails with an error "Could not establish connection to "XXXX": The VS Code Server failed to start." VS Code non-Insiders works as expected.

VS Code version: Code - Insiders 1.65.0-insider (bb221a61d29deabd99ee9431736d04f2175cb596, 2022-02-11T05:19:13.554Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Connection to 'SSH' could not be established  The VS Code Server failed to start

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.67GB (3.68GB free)|
|Process Argv|--crash-reporter-id 1d7ad2b2-e206-4e41-9068-9640edf7bc8a|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH' could not be established  The VS Code Server failed to start
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstartedc:30421358
vsclayoutctrt:30405800
dsvsc009:30436273
pythonvsnew555cf:30426299
vsbas813:30436447
vscscmwlcmc:30428972
azactmsalcf:30432849
vscgsvidc:30433759

```

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/6328

You can work around it by switching to the pre-release version of Remote-SSH

**Comment by adnanfuat** [comment]
> [microsoft/vscode-remote-release#6328](https://github.com/microsoft/vscode-remote-release/issues/6328)
> 
> You can work around it by switching to the pre-release version of Remote-SSH

Yes, it solved my problem too. Thanks @roblourens
