### ISSUE TITLE
Settings conflicts & overwrites: user VS workspace, in v1.64 update

### ISSUE THREAD

**Issue by laggingreflex** [microsoft/vscode#142852]
Since the v1.64 update it seems User settings & Workspace settings are not playing well together. 

It seems some settings are being modified automatically. 

For example I have the following default setting that sets the sidebar to the right: 

* **Default Settings**: `%AppData%\Code\User\settings.json`

  ```json
  "workbench.sideBar.location": "right"
  ```

But in some projects I set the sidebar to the left:

*  **Project Settings** `LeftProject\LeftProject.code-workspace`

  ```json
  "workbench.sideBar.location": "left"
  ```

**Expected** behaviour as it was before v1.64:
* The LeftProject would have sidebar on the left
* Others projects would have sidebar on the right
* No settings would be modified automatically

**Actual** behaviour after v1.64:
* All projects have sidebar on the same side, depending on which setting was set last...
* If I modify Default Settings then the Project Settings are modified automatically (when I switch to the project)
* If I modify Project Settings then the Default Settings are modified automatically

---
Version: 1.64.1 (system setup)
Commit: d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
Date: 2022-02-07T17:16:22.147Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by milanbgd011** [comment]
Same happens to me, really confusing bug. Kudos to laggingreflex for the detailed bug report. I reverted to 1.63.2 and all works now.

I am using MacOS with latest updates, that is the difference with initial comment.
