### ISSUE TITLE
php 8.1.1 enum types has wrong syntax highlighting

### ISSUE THREAD

**Issue by Temepest74** [microsoft/vscode#142824]
Issue Type: <b>Bug</b>

1. create new php fiel
2. add a new enum into it, somethig like this
```
<?php
enum Status : string
{
    case VALID = 'VALID';
    case NOT_FOUND = 'NOT_FOUND';
}
```

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (16.40GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/cata/client --remote=wsl+Ubuntu --crash-reporter-id 71692702-3f77-4482-9a75-b5ffd6c91b20|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz (8 x 2999)|
|Memory (System)|19.55GB (13.08GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz (8 x 2999)|
|Memory (System)|19.55GB (13.08GB free)|
|VM|0%|
</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
laravel-blade|cjh|1.1.2
apacheconf-snippets|eim|1.3.0
auto-rename-tag|for|0.1.10
openssl-configuration-file|gee|0.0.1
monkey-patch|ioc|0.1.16
vscode-peacock|joh|4.0.0
dotenv|mik|1.0.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.217.2
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
php-docblocker|nei|2.6.1
vscode-icons|vsc|11.9.0
JavaScriptSnippets|xab|1.8.0
rainbow-brackets|2gu|0.0.6
vscode-css-formatter|aes|1.0.2
laravel-extra-intellisense|ami|0.6.1
beautify-blade|api|1.0.1
laravel-blade-spacer|aus|2.1.3
vscode-intelephense-client|bme|1.8.0
vscode-tailwindcss|bra|0.7.6
turbo-console-log|Cha|2.1.7
path-intellisense|chr|2.7.0
laravel-goto-view|cod|1.3.7
gitlens|eam|11.7.0
vscode-html-css|ecm|1.11.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
apacheconf-snippets|eim|1.3.0
prettier-vscode|esb|9.2.0
shell-format|fox|7.2.2
vscode-pull-request-github|Git|0.36.1
svg|joc|1.4.17
dockerfile-validator|mar|1.2.0
php-namespace-resolver|Meh|1.1.8
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
file-downloader|min|1.0.11
vscode-docker|ms-|1.19.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.1
jupyter|ms-|2022.1.1001821375
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
sqltools|mtx|0.23.0
sqltools-driver-mysql|mtx|0.2.0
sqltools-driver-sqlite|mtx|0.2.0
reload|nat|0.0.6
php-docblocker|nei|2.6.1
laravel-extension-pack|one|1.0.0
vscode-php-getters-setters|php|1.2.3
composer-links|pix|0.0.1
vscode-css-peek|pra|4.2.0
vscode-xml|red|0.18.3
vscode-yaml|red|1.4.0
laravel-artisan|rya|0.0.28
vscode-blade-formatter|shu|0.12.3
laravel-goto-controller|ste|0.0.15
code-spell-checker|str|2.1.6
code-spell-checker-medical-terms|str|1.0.14
pdf|tom|1.2.0
vscode-import-cost|wix|2.15.0
php-debug|xde|1.23.0
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30433058
pythonvs932:30410667
wslgetstarted:30433507
vsrem710:30416614
pythonvspyt640:30436486
vsbas813:30436447
vscscmwlcmc:30433760

```

</details>

**Comment by Temepest74** [comment]
This is how the enum looks inside my IDE.
![image](https://user-images.githubusercontent.com/28103890/153572162-f6abcb67-d526-40b2-9045-8638ae4f3580.png)
I am certain that it should look different. With some colors at least for the enum and the name of the enum.

**Comment by roblourens** [comment]
Filed this upstream: https://github.com/atom/language-php/issues/451

**Comment by KapitanOczywisty** [comment]
@roblourens Merged upstream :)

**Comment by roblourens** [comment]
Thank you!
