### ISSUE TITLE
Autocompletion is losing type information in variable initialization

### ISSUE THREAD

**Issue by weaknespase** [Microsoft/vscode#14285]
- VSCode Version: 1.6.1
- OS Version: Windows 10, Build 14393.321

Much to my surprise, any attempt to assign constructor function to a variable doesn't lead to correct autocompletion if that variable used to construct new object.

Example:
![3_cr](https://cloud.githubusercontent.com/assets/12257359/19645109/d1133e64-99fb-11e6-81e1-1351ab4b1042.png)

What is actually surprising, that doing same operation in object initializer or constructor works:
![4_cr](https://cloud.githubusercontent.com/assets/12257359/19645525/c6251b56-99fd-11e6-9e61-80d2c5b4ad0d.png)
![5_cr](https://cloud.githubusercontent.com/assets/12257359/19645522/befb0e26-99fd-11e6-91e9-20f8dba6822d.png)

If if works with object properties, it must work with scope variables as well.

**Comment by weaknespase** [comment]
I dived deep into the code and figured that this issue stems from **TypeScript**, not VSCode itself. The problem in variable identifiers not resolving correctly by `getResolvedSymbol` function in `checker.ts`. I think it is better to move issue to TypeScript repository.

**Comment by waderyan** [comment]
@weaknespase thank you for opening this issue. Can you point me to the TypeScript issue you opened? I want to track it on VS Code's end.

**Comment by weaknespase** [comment]
@waderyan of course, here it is: https://github.com/Microsoft/TypeScript/issues/11857
