### ISSUE TITLE
Markdown path IntelliSense should escapse URLs

### ISSUE THREAD

**Issue by laggingreflex** [microsoft/vscode#142838]
Steps to Reproduce:

1. Use [Markdown path IntelliSense](https://code.visualstudio.com/updates/v1_64#_markdown-path-intellisense)
1. Select a path that has space in it, e.g.: `"../Other File.md"`

Expected:

It should insert "../Other%20File":

```md
[Other File](../Other%20File.md)
```

Actual: 

It inserts "../Other File.md" with the space which breaks the link: 

```md
[Other File](../Other File.md)
```

---
Version: 1.64.1

**Comment by lramos15** [comment]
@mjbvz While this works now is there anyway to have the make it so the text in the completion widget still has the space while the inserted link has the escaped characters?
