### ISSUE TITLE
CWD no longer present in terminal tabs

### ISSUE THREAD

**Issue by matthias-ccri** [microsoft/vscode#142863]
Issue Type: <b>Bug</b>

Recently the cwd has been present in the terminal tabs, which is very helpful. But then it stopped working and I can no longer see the cwd.
![Selection_154](https://user-images.githubusercontent.com/18034092/153640596-3094af06-6bec-4e9e-8878-6384111f1dd7.png)

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
OS version: Linux x64 4.15.0-167-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3637)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|15.56GB (6.13GB free)|
|Process Argv|--unity-launch --crash-reporter-id 60fa2716-04d8-4f22-9f87-5d74c8c60d72|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.3
quitcontrol-vscode|art|4.0.0
openmatchingfiles|bca|0.5.2
comment-tagged-templates|bie|0.3.1
vscode-eslint|dba|2.2.2
javascript-ejs-support|Dig|1.3.1
xml|Dot|2.5.1
gitlens|eam|11.7.0
permute-lines|ear|1.1.0
EditorConfig|Edi|0.16.4
vscode-styled-components|jpo|1.7.0
select-highlight-minimap|mde|0.1.0
rainbow-csv|mec|2.0.0
remote-containers|ms-|0.217.4
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
json-parse-stringify|nex|1.0.2
ejs-language-support|Qas|0.0.1
prettier-now|rem|1.4.9
code-settings-sync|Sha|3.4.3
language-stylus|sys|1.15.0
sort-lines|Tyr|1.9.1
vscode-counter|uct|3.0.3
material-theme|zhu|3.13.19
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vsrem710cf:30416617
vsbas813:30436447

```

</details>

**Comment by Tyriar** [comment]
It should be working, if this is still happening could you provide some repro steps? Note that it doesn't show up by default if you're in the workspace folder. You can tweak the behavior via the `terminal.integrated.tabs.description` setting
