### ISSUE TITLE
Debugging failed on VSCode with SDK arm64 7.0.100-preview.1.22101.1

### ISSUE THREAD

**Issue by JiahongJin1** [microsoft/vscode#142822]
- VS Code Version:1.64.2
- OS Version:Monterey(12.2) & Big Sur(11.6.3) M1 chip

Steps to Reproduce:

1.Clean M1 machine
2.Install version 1.64.2:https://code.visualstudio.com/download
3.Install C# extension 1.24.0 arm64: https://github.com/OmniSharp/omnisharp-vscode/releases/download/v1.24.0/csharp-1.24.0-darwin-arm64.vsix
4.Install SDK arm64-7.0.100-preview.1.22101.1 (runtime-7.0.0-preview.1.22076.8)
5.Create new .NET 7.0 console application with reference to a .NET Standard class library
6.Open the project and put breakpoint in the code, then debug.

Expected behavior:
the breakpoint is hit.

Actual behavior:
Debug faied
![Screen Shot 2022-02-11 at 5 39 03 PM](https://user-images.githubusercontent.com/46206739/153568917-6d0b7c2d-f0d2-429d-ab4c-0f934376cd5b.png)
![Screen Shot 2022-02-11 at 5 18 40 PM](https://user-images.githubusercontent.com/46206739/153568946-23dbbf84-87dc-445c-9bd7-9b03d94d7ac4.png)
![Screen Shot 2022-02-11 at 5 38 44 PM](https://user-images.githubusercontent.com/46206739/153568973-4a0b5eb0-f59e-4eb1-b4dc-590812cbfcef.png)

**Comment by NicoleWang001** [comment]
It is not repro on windows arm64 with vscode(1.64.2) arm64 by using C# extension 1.24.0 win32 arm64
![image](https://user-images.githubusercontent.com/1578239/153793567-244ffe77-0ec0-4627-ace6-0d19e129dabc.png)
