### ISSUE TITLE
Github Authentication error: 'UNIX[No such file or directory]' on MacOS X

### ISSUE THREAD

**Issue by andrei-dascalu** [microsoft/vscode#142882]
Issue Type: <b>Bug</b>

After updating VSCode to latest version (as of today), I was logged out of Github and all related extensions (Sync feature, Git Lens, Copilot) asked for re-authentication with Github.

After what was reported as a successful authentication, on return to VSCode I got the error saying "'UNIX[No such file or directory]'.'

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.56GB free)|
|Process Argv|--crash-reporter-id 48d62c0d-9a8a-42a3-bff7-73151bc24c11|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.0
better-toml|bun|0.3.2
systemd-unit-file|coo|1.0.6
vscode-github-actions|csc|0.22.0
vscode-php-getters-setters-cv|cve|1.4.0
vscode-markdownlint|Dav|0.46.0
githistory|don|0.6.19
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.2.0
composer-companion|fae|0.2.6
copilot|Git|1.7.5003
go|gol|0.31.1
todo-tree|Gru|0.0.215
terraform|has|2.19.0
rest-client|hum|0.24.6
elixir-ls|Jak|0.9.0
latte|Kas|0.18.0
rust-analyzer|mat|0.2.932
twig-language-2|mbl|0.9.2
rainbow-csv|mec|2.0.0
git-graph|mhu|1.30.0
vscode-azureterraform|ms-|0.3.2
vscode-docker|ms-|1.19.0
vscode-kubernetes-tools|ms-|1.3.6
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.1
jupyter|ms-|2022.1.1001821375
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.4
azure-account|ms-|0.9.11
vsliveshare|ms-|1.0.5330
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
material-icon-theme|PKi|4.13.0
quicktype|qui|12.0.46
jenkinsfile|rec|1.2.0
vscode-commons|red|0.0.6
vscode-tekton-pipelines|red|1.0.1
vscode-yaml|red|1.4.0
code-settings-sync|Sha|3.4.3
teamhub|Tea|14.0.8
vscode-lldb|vad|1.6.10
vscode-icons|vsc|11.9.0
gitblame|wad|8.1.0
php-debug|xde|1.23.0
vscode-proto3|zxh|0.5.5

</details>

**Comment by TylerLeonhardt** [comment]
/duplicate #115525

This is a tricky one that seems to have something to do with updating vscode. It's very hard to reproduce reliably.
