### ISSUE TITLE
Terminal shows noise corrupt pixels 

### ISSUE THREAD

**Issue by srikanthrajj** [microsoft/vscode#142816]
Recently came across this issue where text gets rendered in weird noise textured, unable to read anything, please provide me a solution for the same. attached screenshot for reference....
![image](https://user-images.githubusercontent.com/1089447/153556768-b7abcd93-7159-4458-a30f-80f4560287f8.png)

**Comment by IllusionMH** [comment]
That's problem with GPU accelerated rendering.

In this comment update of nvidia settings helped https://github.com/microsoft/vscode/issues/115189#issuecomment-768239687

Should be also gone if you pass `--disable-gpu` CLI flag or as permanent launch setting https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
