### ISSUE TITLE
Formatting / spelling / grammar nit in tabs API proposal 

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#142805]
https://github.com/microsoft/vscode/blob/947a99acad4f68f751cb364a6fd23200a8fb4002/src/vscode-dts/vscode.proposed.tabs.d.ts#L83

Indentation is wrong.

"occurred". 

Grammar could be improved.

/assign @lramos15

**Comment by lramos15** [comment]
Ouch, I'm getting roasted. I guess this is why they call it proposed. Thanks for pointing it out :)
