### ISSUE TITLE
Cannot Right Click on icon when in taskbar

### ISSUE THREAD

**Issue by VanessaRussell** [microsoft/vscode#142862]
Issue Type: <b>Bug</b>

Have VS Code either pinned to the taskbar or showing in the taskbar.  Attempt to right click on the icon to bring up the jump list menu.  It doesn't work.  VS Proper still works, so not an issue with jump lists being disabled on my system.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10810U CPU @ 1.10GHz (12 x 1608)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.77GB (49.96GB free)|
|Process Argv|--crash-reporter-id 8ee654bc-dcf4-48cb-a550-5c05f1a3fd7f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.7.0
azure-pipelines|ms-|1.195.0
csharp|ms-|1.24.0
vscode-dotnet-runtime|ms-|1.5.0
azure-account|ms-|0.9.11
powershell|ms-|2021.12.0
azurerm-vscode-tools|msa|0.15.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vsrem710cf:30416617
vsbas813:30436447

```

</details>

**Comment by VanessaRussell** [comment]
![Recording 2022-02-17 at 08 19 31](https://user-images.githubusercontent.com/86689712/154524676-527aabcf-c42b-469c-ae17-46e3133ffb37.gif)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
👍 , we ship insiders to stable next week, so until then I suggest to stick to insiders if you need this functionality.

**Comment by bpasero** [comment]
Oh and if you just uninstall and reinstall VSCode stable, I am sure the issue also goes away.

**Comment by VanessaRussell** [comment]
I was just able to correct the issue by unpinning the icon from the taskbar followed by pinning it back to the taskbar.  This makes me think that there might be something wrong with the upgrade process.  We'll see if it breaks again once the next stable updates come through.
