### ISSUE TITLE
Pressing `.` on github.com repo fails to setup editor

### ISSUE THREAD

**Issue by paul90** [microsoft/vscode#142813]
Pressing `.` on github repo fails to load the edit with the message "Error loading webview: Error: Could not register service workers: SecurityError: The operation is insecure.." (see image below).

![Screenshot 2022-02-11 at 07 43 08](https://user-images.githubusercontent.com/1552489/153554077-db95b7dd-dc6c-44a0-9b34-b65d34d00e78.png)

Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0
Embedder: github.dev

**Comment by filiptronicek** [comment]
@paul90 could you try in Chrome? I think this is a Firefox-only issue, so I'd appreciate if you could test it 🙏.

**Comment by paul90** [comment]
I see much the same error in Chrome 98.0.4758.80 

![Screenshot 2022-02-11 at 11 28 03](https://user-images.githubusercontent.com/1552489/153583902-19276230-d33b-49e2-86fa-a5d4a36a84a0.png)

I notice in Firefox's console it is complaining that `Error: Could not register service workers: SecurityError: The operation is insecure..
![Screenshot 2022-02-11 at 11 17 53](https://user-images.githubusercontent.com/1552489/153585684-18764ab6-9003-4b61-b4d3-a779edaa5424.png)
`

**Comment by mjbvz** [comment]
Likely a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1320796

Are you using private mode or have you enabled any additional security settings?

**Comment by paul90** [comment]
Not using private mode, or enabled any additional security - at least as far as I can remember.

**Comment by mjbvz** [comment]
Is this the official Firefox build?

**Comment by paul90** [comment]
Yes

**Comment by SjoerdV** [comment]
Same issue, so the question is how to configure firefox so that the CORS error and connection to api.github.com succeeds?

Seems to be a long standing firefox bug though: https://bugzilla.mozilla.org/show_bug.cgi?id=1552376 (no service workers allowed if 'delete cookies & site data when FF closes' is checked)

**Comment by ChaseKnowlden** [comment]
I don't see errors in Firefox console, and Markdown preview doesn't work either, but it works fine in Chrome.

**Comment by ChaseKnowlden** [comment]
And it's on Firefox 101.0.1

**Comment by mgmgwi** [comment]
I have a similar error on Brave ([Version 1.40.107 Chromium: 103.0.5060.53 (Official Build) (64-bit)]). I see the same error as @paul90 (https://github.com/microsoft/vscode/issues/142813#issuecomment-1036122610) Additionally those errors are shown in the script console:

![brave-github-dev-error](https://user-images.githubusercontent.com/43027257/177286106-dd122e6f-2aca-455e-b74f-196e9f0525c0.png)

**Comment by MasterInQuestion** [comment]
The core of the issue appears to be the "3p" (3rd party) property of the Worker's domain.

    Browsers may have disabled 3p cookies (and storage requests) by default.
    [ See also: [https://bugzilla.mozilla.org/show_bug.cgi?id=1413615#c5](https://bugzilla.mozilla.org/show_bug.cgi?id=1413615#c5) ]

**Comment by MasterInQuestion** [comment]
[ Quote mjbvz @ CE 2023-09-25 16:47:46 UTC:
[https://github<i>.</i>com/microsoft/vscode/issues/194002#issuecomment-1734120563](https://github.com/microsoft/vscode/issues/194002#issuecomment-1734120563)
    We use a third party domain to keep webviews isolated from the main VS Code window ]
<^>    Would you mind explaining the rationale of such design?
    The related functionalities don't seem to accept the attack vectors that would cause the security problems.
