### ISSUE TITLE
File settings.json was reseted or deleted after 1.64 update

### ISSUE THREAD

**Issue by PedroMVM** [microsoft/vscode#142845]
Does this issue occur when all extensions are disabled?: Unknown

- VS Code Version: 1.64.1
- OS Version: Windows 10

I have updated VS Code to 1.64.1 and I found out that my settings.json file was reseted. I made a search about this issue and it seems to happen in certain updates.

If there is a conflict in any setting, I think a backup file should be created and then alert the user, so we, the users, can put them back one by one and see what is breaking something.

**Comment by sandy081** [comment]
Very sorry about that. By any chance do you have settings sync enabled?

**Comment by willi84** [comment]
have the same issue with one managed windows, where I don't have admin priviledges. And it doesn't matter if sync is enabled or disabled. Beside admin priviledges the only difference is the OS build  (ok: 19043, not ok: 19041) and this issue always happens after restart and writes weired stuff into the settings

Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
![220215-vscode-settings-issue](https://user-images.githubusercontent.com/6207308/154042698-e557dfb7-39be-4760-8529-7acf59f7a216.png)

Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by sandy081** [comment]
@willi84 It seems that your issue is different. Can you please file a separate issue for yours?

**Comment by sandy081** [comment]
@PedroMVM Please see [comment](https://github.com/microsoft/vscode/issues/142845#issuecomment-1036498334)
