### ISSUE TITLE
Extension API - Settings - Broken default settings

### ISSUE THREAD

**Issue by Tilesto** [microsoft/vscode#142820]
Does this issue occur when all extensions are disabled?: No
Problem with default extension settings.

- VS Code Version: 1.64.2
- OS Version: Windows 10 Pro x64

Steps to Reproduce:

**Behavior before updating to 1.64 version** (and it's an expected result) 
- I create extension settings in package.json in contributes section (according to [documentation](https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema) )
- user opens Settings -> Extensions -> ~someExtension~Settings
- user **cannot** delete default settings

**Behavior after updating to 1.64 version** (and it's an actual result) 
- _I create extension settings in package.json in contributes section (according to [documentation](https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema) )_
- _user opens Settings -> Extensions -> ~someExtension~Settings_
- user **can** delete default settings (it's a **1st issue**)
- if get all settings by vscode.workspace.getConfiguration() - we get these deleted default settings (it's a **2nd issue**)

As result, **the user deleted default settings, but it's still there, but not visible**

Video: https://recordit.co/3Dw1jBQmv9

**Comment by rzhao271** [comment]
I think it is fine for the user to delete default settings to change the setting value away from the default.
That change comes from https://github.com/microsoft/vscode/issues/139175.

But, the deleted settings still showing up when we fetch the configuration doesn't seem correct.

**Comment by sandy081** [comment]
It is because of merging strategy of object value settings. For eg merging following objects 

``` 
{
      "a": "1"
}
```

``` 
{
      "b": "2"
}
```

results to

```
{
    "a": 1,
    "b": 2
}
```

So, this is expected.

Not sure what changed in UI so leaving to you @rzhao271
