### ISSUE TITLE
Move to last active window when clicking on a search result

### ISSUE THREAD

**Issue by greggman** [microsoft/vscode#142807]
In the left pane is file 'foo', in the right pane file 'cap'.
I want to see 2 things in 'foo' side by side (for example a call to a function on the left and that same function's implementation on the right.

I have the function's call on the left. I active the right pane. I click on the result in the search pane.

#### What happens now:

The left pane, because it was already showing 'foo', moves to the result of the search therefore losing the very thing I wanted to reference while looking at the search result

![vsc](https://user-images.githubusercontent.com/234804/153540728-d47a3b4c-df7c-4d0a-b7b2-290e24e11440.gif)

#### What I wish happened:

The last active pane switches to show file 'foo' and moves to the location of the search result

![ss](https://user-images.githubusercontent.com/234804/153540738-a5848d40-2c2a-40c5-bf61-e44d5fac4401.gif)

Is there any way to get VSCode to behave the second way? 

If there is no way, then as an appeal: The 2nd way, "move the last active window to the search result", lets you compare 2 or more results in different windows from the same file easily. Want to compare 4 locations from the same file, open 4 panes, click a pane, click a result, repeat.  If you want the window with the file already in it to be the one to receive the result you just make that the active window before clicking. Conversely, the 1st your just out of luck. You can't use the global search. You instead have to manually open the file in 4 panes and then do a local search in each pane.

**Comment by roblourens** [comment]
I think what you are asking for should be the default behavior. Have you changed the `workbench.editor.revealIfOpen` setting?

**Comment by greggman** [comment]
<img width="690" alt="Screen Shot 2022-02-11 at 11 40 31" src="https://user-images.githubusercontent.com/234804/153658509-754db57a-22a4-4c18-994e-5d2fb733dba2.png">

I tried with `code --user-data-dir=<some-dir>` and I get the same behavior (the first gif above)

**Comment by roblourens** [comment]
Ah you are right, Search does not use that setting, open issue with discussion here: https://github.com/microsoft/vscode/issues/94705

**Comment by greggman** [comment]
The new "Drag and drop Problems and Search results" solves this issue for me in the February 2022 version 1.65 version of VSCode. You can drag a search result to any editor pane and that pane will go to that result.
