### ISSUE TITLE
Using Chinese input method will produce another white cursor

### ISSUE THREAD

**Issue by tomial** [microsoft/vscode#142811]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2 f80445acd5a3dadef24aa209168452a3d97cc326
- OS Version: macOS Monterey 12.1

Steps to Reproduce:

1. Use macOS's Chinese input method to input something

https://user-images.githubusercontent.com/38778062/153551211-d9f57b89-5d18-4108-bdac-61f5692ae08a.mov

**Comment by alexdima** [comment]
I could no longer reproduce after https://github.com/microsoft/vscode/commit/1dbc782ab9302333ff1b08a7fa15381835a85738 , so I believe that a left over styling was the root cause here.
