### ISSUE TITLE
[loc][query][VSCode] Please clarify the placeholder

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#14283]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Click to show {0} definitions.

File Name:
src\vs\editor\contrib\goToDeclaration\browser\goToDeclaration.nls.resx

Resource ID:
".resx", 0; "multipleResults"

Query:
Can you please let us know what the placeholder stands for? Is it a numeral value? Thanks!

**Comment by jrieken** [comment]
That's a number as in 'Click to show 4 definitions'
