### ISSUE TITLE
Drag to split horizontally

### ISSUE THREAD

**Issue by martin-braun** [microsoft/vscode#142840]
The big brother Visual Studio has a very interesting small feature that had a huge impact on my QoL experience when building a WPF app recently, it's the ability to drag the top end to split the editor horizontally: 

![2022-02-11 2 06 17 PM](https://user-images.githubusercontent.com/24259245/153597178-b423455b-4929-4d0b-b529-205cf719aad8.gif)

It's not just a smooth experience due to the drag mechanic, but it's also incredibly useful, because unless on regular splitting, you don't lose focus on the line of interest, since the splitting is smooth. It really made temporary working on two places in the same file more convenient, because as fast as it's split as fast it un-splits again.

The closest I came up with in VSCode was to first split the layout and then toggle the layout and I would end up with horizontally centered split. It feels a little bit clunky.

**Comment by heartacker** [comment]
I really want this, as mentioned in https://github.com/microsoft/vscode/issues/36700#issuecomment-914055632

**Comment by gjsjohnmurray** [comment]
> The closest I came up with in VSCode was to first split the layout and then toggle the layout

Once you have set `"workbench.editor.splitInGroupLayout": "vertical"` all subsequent uses of `View: Split Editor in Group` should give you the effect you want. Not as slick as what you show from VS, but it's a start.

pinging @bpasero

**Comment by martin-braun** [comment]
@gjsjohnmurray thanks, that's some useful information, but there are also cases where I want the quick vertical split, i.e. when comparing line by line in fullscreen mode when horizontal space is no issue. It really depends on the task and the screen real estate / window size. 

Also in VS I had quite some situations where I would have two files opened side by side (vertically split) and would drag down the horizontal split on one file to edit two places in one file while still looking for reference on the other opened file.

I hope this feature will be implemented in the future, because it would make VS Code so flexible and great to work with. Really fell in love with this particular feature in VS. :)

**Comment by bpasero** [comment]
The functionality is there, but you cannot start the split by dragging, you need to use a command.

**Comment by martin-braun** [comment]
@bpasero You are right, I found the command "View: Split Editor Down", so I can shortcut it at least, still would appreciate the drag mechanic for the smoothness.

**Comment by martin-braun** [comment]
Uff 10 days, but only 4 likes. I guess no smoothness for Visual Studio Code then. 🙄
