### ISSUE TITLE
"Accept Both Changes" misbehaviour in conflict resolution

### ISSUE THREAD

**Issue by fansek** [microsoft/vscode#142850]
Issue Type: <b>Bug</b>

### Steps to Reproduce

1. Open a file, which contains a merge conflict like this:
   ```
   1
   <<<<<<< a.txt
   3
   4
   ||||||| base.txt
   2
   3
   4
   =======
   2
   >>>>>>> b.txt
   5
   ```
2. Hit "Accept Both Changes"

Actual result is:

```
1
3
4
2
5
```

However, I would expect that if both current and incoming changes are line deletions, accepting both changes would combine these deletions and result in:

```
1
5
```

https://user-images.githubusercontent.com/5702176/153611558-f0d6ae66-707b-4976-bcb4-41c9561a934e.mov

What do you think?

### Additional details:

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|16.00GB (0.42GB free)|
|Process Argv|-psn_0_577677|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2

</details>

**Comment by fansek** [comment]
First of all, thank you very much for your reply.

I think that many editors simply don't respect the merge base which usually makes it clear, which lines should be added and which deleted. Either way, in VS Code, there is not an option to "add lines from both versions", but to "Accept Both Changes", which (I think) means that these changes should be reapplied.

If these changes didn't conflict, they would be applied exactly the same way (as deletions). To illustrate, what I am saying, please, try following:

```sh
printf '1\n2\n3\n4\n5\n' > base.txt
printf '1\n3\n4\n5\n' > a.txt
printf '1\n2\n3\n5\n' > b.txt
git merge-file -p a.txt base.txt b.txt
```

Result:
```
1
3
5
```

As you can see, both lines were deleted. If we turn it other way around, we would get additions instead of deletions. Please, try following:

```sh
printf '1\n3\n5\n' > base.txt
printf '1\n3\n4\n5\n' > a.txt
printf '1\n2\n3\n5\n' > b.txt
git merge-file -p a.txt base.txt b.txt
```

Result:
```
1
2
3
4
5
```

On the other hand, there is a case where you cannot say whether lines should be added or deleted. This happens, when conflict markers don't show which lines were in the merge base (base.txt).

Example of conflict markers without base.txt merge base:

```
1
<<<<<<< a.txt
3
4
=======
2
>>>>>>> b.txt
5
```

In such a case, I would prefer to remove the option to "Accept Both Changes" and maybe add other options to either include both snippets or neither of them. I am intentionally calling them snippets, not changes, since changes can be also deletions.

**Comment by lszomoru** [comment]
@fansek, apologies for not getting back to you on this until now. I was wondering whether you have tried the same scenario in the new 3-way-merge editor that we have added and iterated on during the last few milestones. We are not planning any improvements in the merge experience that use code lenses as we suggest that the 3-way-merge editor is used for more complex merges.

**Comment by fansek** [comment]
@lszomoru, thanks for your response. I understand that 3-way-merge editor takes priority. "Accept Combination" button in 3-way-merge editor works as expected.

![1](https://user-images.githubusercontent.com/5702176/206210698-fde8458f-3195-4738-810c-0c2207559f03.png)
![2](https://user-images.githubusercontent.com/5702176/206210703-201124cf-baea-4cd2-981d-c339a5e1cef5.png)
![3](https://user-images.githubusercontent.com/5702176/206210704-efa40fce-5a92-46d3-8160-c41a97839f8a.png)
