### ISSUE TITLE
Session contents restored messages should not be shown when only shell integration activated message has been written to the terminal

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#142855]
![Screen Shot 2022-02-11 at 10 06 53 AM](https://user-images.githubusercontent.com/29464607/153626271-7e0ca7de-0778-4aa4-a376-81e6b1f087b4.png)

**Comment by meganrogge** [comment]
More broadly, I find myself killing the terminals when I restart because the `Session contents restored` message makes the terminal look a bit busy/messy IMO. @Tyriar thoughts?

**Comment by Tyriar** [comment]
Not sure why this is happening as the message doesn't cause input, can reproduce though.

>  I find myself clearing the terminals when I restart because the Session contents restored message makes the terminals look a bit busy/messy IMO.

I restart them sometimes to get into a "clean state", the `Terminal: Clear` command would do something similar though. Are you proposing a different style or something?

**Comment by meganrogge** [comment]
I use terminal clear. I'm proposing not showing them at all because that is what I'd prefer. Isn't it obvious that they're restored when they're restored?

I realize other terminals also show the session restored banner, but don't think it adds to the experience; in fact, it detracts from mine.

**Comment by Tyriar** [comment]
Discussed offline, to avoid this problem so it's less of an issue how loud the message is:

![image](https://user-images.githubusercontent.com/2193314/154096613-721e477b-c3c0-4fcc-9c11-75c8f460678b.png)

We could discard that middle section if the terminal has had no input so only the following would show after multiple reloads without terminal interaction:

```
Tyriar\xterm.js  master [?]
❯

 Session contents restored from 2/15/2022 at 7:39:34 AM 

Shell integration activated!

Tyriar\xterm.js  master [?] 
❯    
```
