### ISSUE TITLE
Go To Symbol (Ctrl+Shift+O) doesn't pick up on prototype methods

### ISSUE THREAD

**Issue by KrofDrakula** [Microsoft/vscode#1428]
It seems that the code editor only scans for symbols with named functions, not functions assigned to variables, which makes the following code not have any symbols to go to, except for the constructor:

```js
function A() {}
A.prototype.myMethod = function() {};
```

## Expected behavior

The Go To Symbol command should find the `myMethod` function symbol instead of just `A` in the dropdown list.

## Current behavior (0.10.3)

The Go To Symbol dropdown only lists `A` as the only symbol in the file (the only named function).

**Comment by egamma** [comment]
@jrieken fyi

**Comment by jrieken** [comment]
Will move to TypeScript since they to the math for us.

**Comment by jrieken** [comment]
This issue was moved to Microsoft/TypeScript#6145
