### ISSUE TITLE
Test: command to maximize the panel

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#14297]
Complexity: 1
Refs: #7314

- [x] any os @Tyriar 

We have introduced a global workbench command that maximizes the size of the panel (80% of the total height).
Verify this command works as expected.

**Comment by Tyriar** [comment]
Linking the issues I've already filed for this:

- https://github.com/Microsoft/vscode/issues/13906 Toggle maximize panel should go to its previous state when the editor is focused
- https://github.com/Microsoft/vscode/issues/13898 Toggle maximize panel should restore the old panel height not the default height

Please consider fixing #13898 for this version. I've found this to be a pretty big annoyance after using it for a week or so, it forces me to resize the panel to be smaller after I use it.

**Comment by gregvanl** [comment]
Consider adding a keyboard shortcut https://github.com/Microsoft/vscode/issues/14556
