### ISSUE TITLE
Testing API Tree View does not represent most recent Controller State

### ISSUE THREAD

**Issue by PascalSenn** [microsoft/vscode#142966]
Does this issue occur when all extensions are disabled?: No

I am currently working on integrating the testing api into Omnisharp Vscode https://github.com/OmniSharp/omnisharp-vscode/pull/5054. The problem I face there is that sometimes the test explorer does not update correctly.
It seems like parts of the tree still represent a old test item.

I discover the tests like this:
1. Register Project change listener on omnisharp
2. On change discover the tests contained in the project via omnisharp
3. Add the tests to the test controller under a specific directory

This process is done on every new project discovered and on every change detected in a test file. The test items that represent the directory structure stay the same, the test for each project are replaced when ever a project is (re)discovered. 

It happens often that the tree view of vscode is out of date, even when the test controller actually knows that there are tests. 

Here is and example:
![image](https://user-images.githubusercontent.com/14233220/153755852-731e37fe-3594-4a70-94fa-1294fe7c54c4.png)

You see that in the test tree the `Test7` does not appear to be visible. But the test controller knows about it's existence and I can also execute it:
![image](https://user-images.githubusercontent.com/14233220/153755940-cff370c8-a72a-47d9-bca6-72c094579266.png)

Sometimes the test explorer updates the view on it's own. But usually I have to switch to the "list view" and then back to the "tree view" so see the updates:

*Before Switching:*
![image](https://user-images.githubusercontent.com/14233220/153756076-8cf3ef81-bd8a-430e-bdb1-45fe0f45604a.png)

*After Switching:*
![image](https://user-images.githubusercontent.com/14233220/153756118-c7b27f2d-f05a-4866-a63b-820db2c8ccbf.png)

- VS Code Version: 1.64.2
- OS Version: Big Sur

Steps to Reproduce:

I am open to try to reproduce this in a more isolated environment. You folks just have to tell me what setup you like to have. Because the current reproduction of the bug requires dotnet in two versions installed and a custom build vscode extension. I do understand that this probably is not ideal for you to debug :D 

1. Checkout, build and add the extension: https://github.com/OmniSharp/omnisharp-vscode/pull/5054
2. Open (https://github.com/PascalSenn/vscode-testing-api-reproduction)
3. Change some test files and see the tree go out of sync.

**Comment by connor4312** [comment]
Thanks for the repro!
