### ISSUE TITLE
Add the ability to jump to a specific numbered search result

### ISSUE THREAD

**Issue by Nixinova** [microsoft/vscode#142937]
### Feature Request

When searching in a file, this is the UI:
![image](https://user-images.githubusercontent.com/42429413/153728650-1c6a5372-42b0-4ec3-963e-bcf41fceb82a.png)
It is quite annoying being at search item \#\29 and wanting to jump back to item \#\1; to do so you have to spam the arrow button.
Afaik there is no way to jump to specific results.

It would be good if
- the first number ('25' in the image) was editable so you could quickly jump to a specific result (better option)
- or, it at least had ↓↓ and ↑↑ buttons to jump to bottom/top result quickly

**Comment by heartacker** [comment]
I believe that is necessary
