### ISSUE TITLE
Visual Studio has insufficient previleges to debug the process

### ISSUE THREAD

**Issue by VidhyashreeHS** [microsoft/vscode#142991]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Visual Studio 2012 Professional Version 11.0.61219.00 Update 5
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Open code in VS 2012 Professional as Administrator.
2. Navigate to Debug --> Attach to process.
3. Select desired process --> Click Attach.
4. Error --> Unable to attach to the process. Visual Studio has insufficient previleges to debug this process. To debug this process, Visual Studio must be run as an administrator.
<img width="706" alt="VS1" src="https://user-images.githubusercontent.com/99638178/153818102-9d6a3770-d0bb-4337-8252-d57d4315b5bc.png">
<img width="706" alt="VS2" src="https://user-images.githubusercontent.com/99638178/153818129-ae2a2a08-58f4-4436-abdd-059ef9e4ee42.png">

**Comment by gjsjohnmurray** [comment]
You have reported this in the wrong place. You are use Visual Studio, but this repository is for Visual Studio Code. Please close it.
