### ISSUE TITLE
Enabling exp. shell integration makes me lose prompt colors

### ISSUE THREAD

**Issue by warpdesign** [microsoft/vscode#142994]
Issue Type: <b>Bug</b>

- enable the experimental `Shell integration` setting
- open an ssh session

Notice how the prompt does not have any colors:

https://user-images.githubusercontent.com/199648/153829495-f7183a5e-8c98-44c2-9136-50c7bc52f845.mov

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No
Remote OS version: Linux arm 5.10.92-v7l+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-7Y32 CPU @ 1.10GHz (4 x 1200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 3, 3|
|Memory (System)|8.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id e5f134f9-b859-4b99-99be-b323642a3eec|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: pi|
|OS|Linux arm 5.10.92-v7l+|
|CPUs|ARMv7 Processor rev 3 (v7l) (4 x 600)|
|Memory (System)|3.75GB (0.60GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
arm|dan|1.7.2
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
vetur|oct|0.35.0
php-debug|xde|1.23.0
php-pack|xde|1.0.3
php-intellisense|zob|1.0.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
vsbas813:30436447
vscscmwlcmt:30436993

```

</details>

**Comment by warpdesign** [comment]
Note: I'm using bash.

**Comment by Tyriar** [comment]
Can you paste in the output of `echo $PS1`?

**Comment by warpdesign** [comment]
> \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w \$\[\033[00m\]

**Comment by warpdesign** [comment]
@Tyriar  the prompt is set here:

> if [ "$color_prompt" = yes ]; then
>     PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w \$\[\033[00m\] '
> else
>     PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
> fi

`$color_prompt` is set a few lines above:

force_color_prompt=yes

> if [ -n "$force_color_prompt" ]; then
>     if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
>         # We have color support; assume it's compliant with Ecma-48
>         # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
>         # a case would tend to support setf rather than setaf.)
>         color_prompt=yes
>     else
>         color_prompt=
>     fi
> fi

**Comment by meganrogge** [comment]
@warpdesign where are you setting your `PS1`? In your `.bashrc`, `.bashprofile`, ...?

**Comment by meganrogge** [comment]
Using the script you provided above in my `.bash_profile`, I get this result, so cannot repro the issue
![Screen Shot 2022-02-24 at 8 03 28 PM](https://user-images.githubusercontent.com/29464607/155639795-9e435584-21be-4e98-9049-dd39c9a6dcf8.png)

Is that in your `.bashrc`?

**Comment by meganrogge** [comment]
Using the script you provided above in my `.bash_profile`, I see the following, so cannot reproduce the issue.
![Screen Shot 2022-02-24 at 8 06 10 PM](https://user-images.githubusercontent.com/29464607/155640015-3fbd658c-0c90-490b-a428-8fad95273897.png)

Where do you have that script? In your `.bashrc`?

**Comment by meganrogge** [comment]
Can you provide the terminal profile you're currently using for `bash`?

**Comment by Tyriar** [comment]
@warpdesign could you try in the next stable? This might have been fixed since?
