### ISSUE TITLE
"read ECONNRESET" and "unexpected end of file" errors

### ISSUE THREAD

**Issue by Kizmar** [Microsoft/vscode#14292]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: None

This morning I started getting "read ECONNRESET" and "unexpected end of file" errors in both the stable and insiders versions of vscode. I tried uninstalling both versions and reinstalled just the stable version, and I'm still getting the errors. I also confirmed that I have proper internet connectivity. I also closed the open folder to see if my project was causing it, and still get errors.

Not sure what else to do to troubleshoot this. I'm unable to search for extensions and such.

[EDIT] More error detail:
messageService.ts:128read ECONNRESET: Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:564:26)

workbench.main.js:91 unexpected end of file: Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17)

**Comment by bpasero** [comment]
Seems to me like zlib issue. It is being used in https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/request.ts#L16

**Comment by joaomoreno** [comment]
Can you open https://marketplace.visualstudio.com? Are you behind a proxy? Is the issue still happening?

This sounds like an issue with your machine not being able to reach the Marketplace.

**Comment by Kizmar** [comment]
@joaomoreno 
For context, I work on a Mac laptop in a VirtualBox VM with Windows 10. I have the VM firewall turned off. I get these errors in the VM at the office and at home. I can hit the marketplace URL in the VM and search for extensions without issue.

I am only experiencing this within the VM. When I run vscode on OSX, I don't get these errors. Additionally, I have a similar setup on my Windows 10 desktop at home (working in a VirutalBox VM with Windows 10). That instance is not throwing these errors either.

It does seem like an issue with vscode (specifically) on my Mac hosted VM, but I'm not sure what changed between Friday and Monday that would have caused it. It worked when I shut down Friday, and didn't work when I booted up on Monday.

I thought maybe a file was corrupt and uninstalling vscode didn't remove it. I uninstalled vscode again, and manually deleted every "code" directory I could find in my user directory. Re-installed vscode and I still immediately get "unexpected end of file" followed by "read ECONNRESET". :(

I'm going to chalk this up as "not your problem", but if you have any other troubleshooting suggestions, please let me know.

**Comment by joaomoreno** [comment]
Any chance you could send me a snapshot of the VM itself?

**Comment by Kizmar** [comment]
@joaomoreno Do to security reasons, I cannot.

**Comment by eugirdor** [comment]
I have a similar issue.  I get a "read ECONNRESET" error whenever I start Visual Studio Code or search for an extension.

Errors are only occur when running inside of Windows (7, 8.1 and 10) VirtualBox VM running on MacOS.  Everything works fine from the host OS and from Windows 10 running on real hardware.  For me, the issue started around Thursday, October 20th.

Mac OS 10.10.5
VirtualBox 5.0.28 r111378
Visual Studio Code 1.6.1

**Comment by eugirdor** [comment]
@Kizmar FWIW, I reverted to VirtualBox 5.0.26 r108824 and it fixed my issue.

**Comment by joaomoreno** [comment]
@Kizmar Can you check?

**Comment by cnrudd** [comment]
same issue here.  
my config: 
Mac OS 10.11.6
VirtualBox 5.0.28 r111378
Visual Studio Code 1.6.1

**Comment by joaomoreno** [comment]
@cnrudd @Kizmar Do you see the issue when rolling back to VirtualBox 5.0.28 r111378?

**Comment by Kizmar** [comment]
@joaomoreno Confirmed! Removing VirtualBox 5.0.28 r111378 and installing VirtualBox 5.0.26 r108824 fixed the issue for me as well.

@eugirdor & @cnrudd: Have either of you started a thread on VirtualBox's forum about this? I'll pile on on if so. :)

**Comment by joaomoreno** [comment]
Thanks for the confirmation, @Kizmar

**Comment by eugirdor** [comment]
@Kizmar I haven't, but there's a few in their bug tracker that look like the same issue https://www.virtualbox.org/search?q=reset+5.0.28&noquickjump=1&ticket=on

**Comment by cnrudd** [comment]
Hi,
I solved this issue bychanging VB 5.0.28 r111378's networking setting from NAT to Bridged.
In Bridged mode, I don't get the ECONNRESET error.
-Colin
