### ISSUE TITLE
Every next zoom change is slower than previous

### ISSUE THREAD

**Issue by SnosMe** [microsoft/vscode#142975]
Issue Type: <b>Performance Issue</b>

Every next zoom change (Ctrl+NumPlus, Ctrl+NumMinus) makes zoom operation to perform slower and slower.
Feels like it takes O(n^2) for every next zoom change.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by SnosMe** [comment]
Tested and it happens there as well. Think my issue is duplicate of #142595
