### ISSUE TITLE
macOS: inconsistent UI when it comes to inputs border radius

### ISSUE THREAD

**Issue by brunovieira97** [microsoft/vscode#142928]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2 (Universal)
- OS Version: macOS 12.2.1

On MacOS, even though some inputs such as selects have rounded corners, the focus indicator (1px solid border) does not:

<img width="187" alt="image" src="https://user-images.githubusercontent.com/19749621/153717226-c4ebb643-3702-4b76-ac6f-272d7106dd76.png">
<img width="204" alt="image" src="https://user-images.githubusercontent.com/19749621/153717220-54a24e1c-115e-47eb-9d07-023befd98045.png">

I believe that, going forward, all of VS Code's inputs should have rounded corners such as the one in the picture above. The focus indicators should, as well, if possible. This goes for both macOS and Windows, since Win11 has a similar design principle.

Currently, there's inconsistency between selectors and text inputs where the first ones are rounded (4px) and other inputs don't have any radius applied.

I'd be happy to help with this, but as this is such a large project, some guidance is welcome.

Steps to Reproduce:

1. Click on Output panel
2. Click on the select input
3. Dismiss the dropdown menu

**Comment by misolori** [comment]
This is because we use `outline` for our focus border, which does not support `border-radius`. I am not sure if we're able to switch to border for all focus items.

cc @sbatten

**Comment by isidorn** [comment]
I think the `outline` could use some more love. Even though it will be a tedious job making sure this works in all cases.
In the case shown in the picture we use a native select box, but on Windows we use a custom one. So fyi @JacksonKearl 

@bpasero might be the one that originally introduced the outline for focus border, so just fyi for thoughts

**Comment by daviddossett** [comment]
I'm seeing this as fixed. Feel free to reopen if that's not the case 👍 

<img width="365" alt="CleanShot 2022-12-14 at 15 47 59@2x" src="https://user-images.githubusercontent.com/25163139/207739621-56ecb1d4-49cd-4aee-b3bb-d6c1915442b7.png">
