### ISSUE TITLE
`Toggle Line Comment` in Fenced code blocks for JSONC doesn't work well in Markdown

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [microsoft/vscode#142960]
This problem still occurs even if you disable all extensions.

# `Toggle Line Comment` in Fenced code blocks for JSONC doesn't work well in Markdown

`Toggle Line Comment` in Fenced code blocks for JSONC doesn't work well in Markdown.

On the other hand, `Toggle Line Comment` in Fenced code blocks for JSON and JSON5 does work well.

## demo

Create the following Fenced code blocks for JSONC.

````markdown
```jsonc
{
  "settings": true
}
```
````

Then run `Toggle Line Comment` on the line with `"settings"`.
You will get the following results:

````markdown
```jsonc
{
  <!-- "settings": true -->
}
```
````

The correct result is:

````markdown
```jsonc
{
  // "settings": true
}
```
````

### GIF animation

Execute `Ctrl+/` repeatedly

![toggleLineCommentJSONC](https://user-images.githubusercontent.com/75878492/153751443-f5685340-8232-42cb-94ba-e4c87d72c39f.gif)

## Version

```
 Version: 1.64.1 (user setup)
  Commit: d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
    Date: 2022-02-07T17:16:22.147Z
Electron: 13.5.2
Chromium: 91.0.4472.164
 Node.js: 14.16.0
      V8: 9.1.269.39-electron.0
      OS: Windows_NT x64 10.0.19043
```

**Comment by babakks** [comment]
@mjbvz I'd like to work on this. Could you please give me some leads?

**Comment by babakks** [comment]
I made the PR. Could you please check it?
@mjbvz
