### ISSUE TITLE
[createInstance] modelService depends on ILanguageFeaturesService which is NOT registered

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#142913]
Running unit tests:

`[25176:0212/094651.760927:INFO:CONSOLE(148)] "[createInstance] modelService depends on ILanguageFeaturesService which is NOT registered.", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js (148)`

**Comment by alexdima** [comment]
@jrieken Is there a way to turn these console warnings into errors? I seem to be triggering these warnings lately whenever I add a service dependency to `ModelService`

**Comment by jrieken** [comment]
The instantiation service can be created with the `strict` option and than it should fail. Tho, I need to check for this specific case, something looks fishy

**Comment by alexdima** [comment]
@jrieken Nice! In editor tests, I use the `TestInstantiationService` and that one doesn't expose `strict` as a ctor option. I will push a change to expose it and adopt it in editor tests.

**Comment by jrieken** [comment]
> I will push a change to expose it and adopt it in editor tests.

🤞 this might unveil many shortcuts that we have been taking
