### ISSUE TITLE
TS Server fails to start with 2 month old TS version.

### ISSUE THREAD

**Issue by MarkKahn** [microsoft/vscode#142968]
VSCode 1.64.2 & TS 4.5.3 (released Dec 11, 2011) fail to start together.  This wasn't a problem with last month's VSCode release.  There is a bug in 4.5.4 that's currently preventing us from upgrading.  I don't think forcing VSCode users to be on bleeding edge TS releases is appropriate.  Also tested TS 4.4 & TS 4.3

**Comment by mjbvz** [comment]
Please fill in the issue template and provide the actual error message you are seeing

I just tested that version and a year+ old version of TS. Both work fine

/needsMoreInfo
