### ISSUE TITLE
VSCode Does not Clean Up After Itself. workspaceStorage has Gigabytes of Useless Data!

### ISSUE THREAD

**Issue by elibroftw** [microsoft/vscode#142972]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Go to  `%APPDATA%\Code\User\`
2. Alt +Enter on `workspaceStorage`

![image](https://user-images.githubusercontent.com/21298211/153771256-ab1e0f85-e257-4a33-823a-98b368b8404a.png)

![image](https://user-images.githubusercontent.com/21298211/153771281-9a2d6fe6-cdb5-4d18-855d-d2e865b7f5a8.png)

These are all workspace folders from 2019 - 2021. 2GB for basically nothing.

VSCode should scan these folders every 3 months and remove 3 month old data. Please respect my storage.

**Comment by gjsjohnmurray** [comment]
See #32461
