### ISSUE TITLE
Copy & Paste from cell output not possible

### ISSUE THREAD

**Issue by firegate22** [microsoft/vscode#142974]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I get an error in executing a cell, e.g. 

`[ValueError: Unable to parse string "305-03-2012" at position 7277424]()`

I do select the message or parts of it, press the shortcut to copy the marked text and it copies the actual cell content (the executed code). That happens almost always... as seen here, I was at least at some point able to copy the whole error message, but that's not always the case.

In the interactive window, I do get the same behaviour. I do see an error popup at the bottom with this content:
![image](https://user-images.githubusercontent.com/37472736/153770563-5e9eceea-ca7a-4132-8c8b-5b5b5d231457.png) 
in text: startIndex 1 out of bounds

That appears when I actually use the copy shortcut (like ctrl + c, but I am on a mac).

I do post this a bug because I think that's not the intended behaviour although I do see a "copy the whole cell" as features for some use cases.

### VS Code Version

Version: 1.65.0-insider (Universal) Commit: bb221a61d29deabd99ee9431736d04f2175cb596 Date: 2022-02-11T05:16:57.139Z (2 days ago)

### Jupyter Extension Version

v2022.2.1001828435

### Coding Language and Runtime Version

Python 3.10.2

### Language Extension Version (if applicable)

v2022.1.1797165283-dev

### Running Jupyter locally or remotely?

Local

**Comment by rebornix** [comment]
This should be fixed now.
