### ISSUE TITLE
There is a problem with integrated terminal of vs code.

### ISSUE THREAD

**Issue by GaryZhen** [microsoft/vscode#142932]
Issue Type: <b>Bug</b>

I am a windows 10 user, when I had download nodemon in npm, I had tried many times to use ndoemon. But, the terminal always show 
  "The term 'nodemon' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was  included, verify that the path is correct and try again."
  Finally, I found it's not my problem of path or something else, it just is the vscode terminal cannot show it. When I restart vscode, everything is fine. 
  It spend me lots of time, hope you guys can fix it and save more time for other users

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.71GB (2.08GB free)|
|Process Argv|--crash-reporter-id cbbcf61c-f5a7-49ed-8688-1d0bae58171c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.5.0
gitignore|cod|0.7.0
doxdocgen|csc|1.3.2
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|11.7.0
code-runner|for|0.11.7
vscode-pull-request-github|Git|0.36.1
plantuml|jeb|2.17.2
better-cpp-syntax|jef|1.15.13
vscode-language-pack-zh-hans|MS-|1.64.6
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.1
jupyter|ms-|2022.1.1201831736
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.4
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5330
vsliveshare-audio|ms-|0.1.91
markdown-preview-enhanced|shd|0.6.1
cmake|twx|0.0.17
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
testflight:30433670
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc008:30436278
pythonvsnew555cf:30436485
vsbas813:30436447
vscscmwlcmc:30436992

```

</details>

**Comment by meganrogge** [comment]
That means that the program is not installed on your path
