### ISSUE TITLE
mac m1 VS Code is not able to debug using Jest

### ISSUE THREAD

**Issue by hengshanMWC** [microsoft/vscode#142950]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64
- OS Version: macOS big sur 11.4
- OS chip: Apple M1
- node Version: 16.13.1

Steps to Reproduce:

1. git clone https://github.com/vuejs/core.git
2. pnpm inistall
3. debug using Jest
result: 
<img width="648" alt="image" src="https://user-images.githubusercontent.com/45714422/153743255-dd20e9cb-1df7-46ee-9be3-b6c6eef7ce44.png">

launch.json:
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Jest",
      "type": "node",
      "request": "launch",
      "program": "${workspaceFolder}/node_modules/.bin/jest",
      "stopOnEntry": false,
      "args": ["${fileBasename}", "--runInBand", "--detectOpenHandles"],
      "cwd": "${workspaceFolder}",
      "preLaunchTask": null,
      "runtimeExecutable": null,
      "runtimeArgs": ["--nolazy"],
      "env": {
        "NODE_ENV": "development"
      },
      "console": "integratedTerminal",
      "sourceMaps": true,
      "windows": {
        "program": "${workspaceFolder}/node_modules/jest/bin/jest",
      }
    }
  ]
}

**Comment by weinand** [comment]
@hengshanMWC in your launch config you are setting `program` to the shell script `${workspaceFolder}/node_modules/.bin/jest`. This fails because VS Code's node debugger cannot debug shell scripts.

It makes more sense to set `runtimeExecutable` to `${workspaceFolder}/node_modules/.bin/jest` and tweak pass the correct arguments in `runtimeArgs`.

**Comment by hengshanMWC** [comment]
Thank @[weinand](https://github.com/weinand),I'm currently set to：
```JS
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Jest",
      "type": "node",
      "request": "launch",
      "stopOnEntry": false,
      "args": ["${fileBasename}", "--runInBand", "--detectOpenHandles"],
      "cwd": "${workspaceFolder}",
      "preLaunchTask": null,
      "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/jest",
      "env": {
        "NODE_ENV": "development"
      },
      "console": "integratedTerminal",
      "sourceMaps": true,
      "windows": {
        "program": "${workspaceFolder}/node_modules/jest/bin/jest",
      }
    }
  ]
}
```
However, if you want to trigger the breakpoint correctly, you must preview the test file with the breakpoint set, otherwise the breakpoint will be ignored。

Is it normal？

<img width="877" alt="WechatIMG748" src="https://user-images.githubusercontent.com/45714422/154017891-18257070-eba2-4a96-82c8-9178651f1f69.png">
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/45714422/154018061-2a9cbef2-47ec-4fc4-bd99-d76ac8b276e6.png">

**Comment by hengshanMWC** [comment]
[case](https://github.com/hengshanMWC/core/tree/fixbug-jest-debugg-20220215)
