### ISSUE TITLE
`code` command not working properly on my remote dev machine after latest update. 

### ISSUE THREAD

**Issue by Alan-chenhx** [microsoft/vscode#142992]
`code` command not working properly on my remote dev machine after latest update. The code binary was moved to `remote-cli/code` not as it used to be under `bin`. As I tried to execute the new `code`, it occured an error with `./node not found`.

**Comment by ivensli** [comment]
I have the same problem！Is it solved？

**Comment by aeschli** [comment]
Is this with Remote-SSH? Do you have `"terminal.integrated.inheritEnv": false` in your settings?
Then it's https://github.com/microsoft/vscode-remote-release/issues/6289
