### ISSUE TITLE
Add convenient modifier-less keybindings to timeline diff navigation

### ISSUE THREAD

**Issue by codecoll** [microsoft/vscode#142908]
Issue Type: <b>Feature Request</b>

When I open the Timeline of a file and click a change there then vscode shows me the changes in a file.  I can use (Shift-)Alt-F5 to navigate between the changes.

In Emacs if a view is read only then it allows the user to configure modifier-less keybindings. This is very convenient for frequent operations.

Currently, if I type 'n', for example, in the vscode change view shown by clicking timeline then it says: 'cannot edit in read ony editor'.

Since single char keybindings are unused there it could be very convenient to use them for navigation. E.g. 'n' to go the next change and 'p' to go to the previous one.

Please add single char keybindings as alternatives keybdingins when showing a read only view where typing is not allowed anyway, so single char bindings can be used.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 6.3.9600
Restricted Mode: No

**Comment by JacksonKearl** [comment]
cc @bpasero I tried adding:
```
  {
    "key": "cmd+n",
    "command": "workbench.action.editor.nextChange",
    "when": "editorReadonly"
  }
```

but it didn't do anything , I believe as a result of the precondition being `TextCompareEditorActiveContext.toNegated()` (not sure why that is)
