### ISSUE TITLE
laravel .blade.php files have no icon

### ISSUE THREAD

**Issue by diontron** [microsoft/vscode#142935]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: monterey

Steps to Reproduce:

1. open vs code
2. create a `.blade.php` file
3. see the file has no laravel icon, it looks like a standard text file icon instead

would be nice if i didn't need to install an icon pack to get these files to have the laravel icon

**Comment by aeschli** [comment]
With the built-in Seti theme and no additional extensions installed, I get the 'php' icon:
![image](https://user-images.githubusercontent.com/6461412/154988160-7f6c93d9-7fc1-4f25-b852-94be70c792c1.png)

Is your request to have a separate different icon for files of the blade language? If yes, file a feature request against the Seti theme: https://github.com/jesseweed/seti-ui/issues
