### ISSUE TITLE
files dissappear

### ISSUE THREAD

**Issue by JAINSANVEG37** [microsoft/vscode#142926]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Today when i opened vs code ,there is no earlier projects saved ,That I did.I remember yesterday everything was working fine.Today no program is there infact the shortcut i created on desktop to save the files also not opening ,I actually know the path where all my programs has been saved but today no similar folder is there.Can anybody help me with this issue?

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx   (4 x 2595)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.38GB (0.32GB free)|
|Process Argv|--crash-reporter-id 09714c3f-8a14-4e8d-ac2a-20650e9e8bb5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
competitive-programming-helper|Div|5.9.1
code-runner|for|0.11.7
better-cpp-syntax|jef|1.15.13
remote-containers|ms-|0.217.4
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
vsbas813:30436447
vscscmwlcmc:30436992

```

</details>

**Comment by gjsjohnmurray** [comment]
It sounds like maybe you created your projects in folders within the folder where VS Code was installed.

If so, they will have been deleted when VS Code updated.

**Comment by JAINSANVEG37** [comment]
Yes I am saving the codes in vs code folder
Now i understand.
But can u tell if there is any way to recover them,because there are so
many codes.

**Comment by gjsjohnmurray** [comment]
> But can u tell if there is any way to recover them

@JAINSANVEG37 unfortunately there probably isn't, unless you had put them into source control or have a backup of your disk. See https://github.com/microsoft/vscode/issues/138815#issuecomment-990950773 by @joaomoreno who is a member of the core team.

**Comment by JAINSANVEG37** [comment]
Ok, I'll check it out.
