### ISSUE TITLE
Some commands in command palette have their original command category names translated.

### ISSUE THREAD

**Issue by y-tsutsu** [microsoft/vscode#142910]
When the command palette is displayed with VS Code with the Japanese pack extension installed, the category of the original command name is translated for some commands.
For many commands, the original command name category remains in English.

Does this issue occur when all extensions are disabled?: No (language pack only)

- VS Code Version: 1.64.2
- OS Version: Windows10 Pro 21H2

# Steps to Reproduce:

1. Install the language pack. (For example, Language pack extension for Japanese)
2. Display the command palette.
3. Display the target command.(For example, About)
![image](https://user-images.githubusercontent.com/1199726/153701159-0c9faeac-406a-46d7-ba85-f0be5484d63b.png)
4. For successful commands, the original command name category is displayed in English.
![image](https://user-images.githubusercontent.com/1199726/153701178-686eaa26-0a77-4870-94a1-b2429a499749.png)

# Expected Result:

The original command name category is not translated.
![image](https://user-images.githubusercontent.com/1199726/153701211-85c1cb31-59f3-4b0e-a24e-ea7120a2103a.png)

**Comment by weartist** [comment]
hi, can I work on this issue?
