### ISSUE TITLE
Change HTML grammar to be more precise (embedded modes)

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#14295]
Follow up from #14136

Currently, the HTML grammar gives `source.css.embedded.html` also to `<style>` and `</style>`.

The fix is to use `contentName` instead of `name` in the 4 places where HTML embeds other languages.

![bad-ranges](https://cloud.githubusercontent.com/assets/5047891/19652525/5a1363c8-9a11-11e6-836b-db0284f1c99b.gif)

**Comment by alexandrudima** [comment]
e.g. => https://github.com/Microsoft/vscode/blob/master/extensions/html/syntaxes/html.json#L155

```
"name": "source.css.embedded.html",
===>
"contentName": "source.css.embedded.html",
```

This will make it that the begin and end matches will not be `source.css.embedded.html`

**Comment by aeschli** [comment]
To verify, try to add a comment before/inside/after the script/style tag to see that the correct comment style is used.
