### ISSUE TITLE
Add drop into editor API

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#142990]
Exploration of dragging a file from VS Code's explorer into an editor to create a link. Example use case would be dragging a file into a markdown editor to insert a link

**Comment by mjbvz** [comment]
I have a prototype but need to think more about what the design should look like. Biggest question I have right now:

Should we allow there to be multiple of these drop handlers active at one time? We do want to allow there to be multiple drop handlers where each one handles a different dropped mime type, but what about multiple handlers for a single mime type? In markdown for example, you can imagine having one drop handler that creates links and another that creates image links

If we did allow this, presumably we then need some way for the user to control what happens on drop, either with a setting to configure the default or by presenting a list of actions to them

---

Answering this helps determines if we go with more of a provider style api or more of an event api

**Comment by mjbvz** [comment]
@misolori @sbatten  I've added some basic prompt text to the drop overlay:

https://user-images.githubusercontent.com/12821956/161646117-3538234e-d20c-4f56-a28b-b068565612ae.mov

This text only shows up when you are dropping into the whole editor. It hides itself if the drop is previewing a split (however holding down shift still lets you enter "drop into editor" mode)

Let me know what you think about this behavior. I also think we need to make the `Hold shift to drop into editor` text more prominent, potentially by adding a solid background to it. Would appreciate some design help and suggestions on this

**Comment by Ark-kun** [comment]
I would really love this feature for CustomEditor/CustomTextEditor VSCode extensions.

I'm integrating my drag-and-drop based [Pipeline Editor](https://cloud-pipelines.net/pipeline-editor) with VSCode. I want the users to be able to drag `component.yaml` files on the pipeline canvas.

https://www.youtube.com/watch?v=Wgg7Qs1zdB4
