### ISSUE TITLE
Tab Changes Focus regardless of mode

### ISSUE THREAD

**Issue by mbish** [microsoft/vscode#142923]
I don't know how this happened. The only thing I've done today is install a docker extension. When I hit tab it behaves as though it's in "Tab Moves Focus" mode is enabled regardless of what the current setting is. I've tried toggling that mode and off again, I've tried restarting the editor, restarting my computer, disabling all extensions, removing the keybinding and nothing has worked. 

Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:29.527Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.16.8-arch1-1

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
