### ISSUE TITLE
Add Scroll to Top Color Change

### ISSUE THREAD

**Issue by Samyak-Bumb** [microsoft/vscode#142916]
Hello Guys, Add a new Feature in the theme to **Change the Color of the Scroll to Top** while reading any Extension's Readme. Because _Default Blue_ Color Does not match some Theme's. <br><br>

Example:- _**"extensionButton.scrolltotop": "#ff0000";**_

![Screenshot (18)](https://user-images.githubusercontent.com/88429776/153706649-2b3fa7b2-98d8-46b0-b2b2-ab30a8b3d4d2.png)<br><br>

#### Hope this Feature will be added

**Comment by mjbvz** [comment]
We don't need a new theme key specifically for this. Instead it should use one of the existing ones, likely the ones for buttons

**Comment by luoriyuhui21** [comment]
hello! Can I work on this issue? Maybe we can using existing one , or create  new color setting for these buttons.
