### ISSUE TITLE
Failed to annotate Object type in JavaScript

### ISSUE THREAD

**Issue by LittleYe233** [microsoft/vscode#142987]
It seems that VS Code can't annotate `Object` type for JavaScript files, while other types like `number` and `string` work well.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.0
- OS Version: Windows 10 21H2 (OS build 19044.1526)

Steps to Reproduce:

1. Create a new JavaScript file.
2. Write the code below:
```js
/** @type {object} */
let obj;
```
3. Check the hover information of this variable which will read: "let obj: any".

**Comment by mjbvz** [comment]
TS treats `object` as `any` in JS because they are essentially the same for type checking. Add a more specific type if you want specific typings
