### ISSUE TITLE
File nesting: alignment issues seemingly caused by ignoring the tree indent setting

### ISSUE THREAD

**Issue by miss-programgamer** [microsoft/vscode#142938]
Issue Type: <b>Bug</b>

1. Use the experimental file nesting feature to nest some files
2. Use any setting other than 22 for `workbench.tree.indent`

Alignment when workbench tree indent is 22:
![image](https://user-images.githubusercontent.com/23565302/153729360-9969d36e-bab0-4185-897e-bf23b478c782.png)

Alignment when workbench tree indent is 18:
![image](https://user-images.githubusercontent.com/23565302/153729373-1b512c27-12e5-4637-949f-17c4c1eca703.png)

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (50.06GB free)|
|Process Argv|--crash-reporter-id cd995679-7303-4ddf-a9ac-69e69c2b647b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
tsl-problem-matcher|amo|0.5.0
toml|be5|0.6.0
github-markdown-preview|bie|0.1.0
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
vscode-intelephense-client|bme|1.8.0
npm-intellisense|chr|1.4.1
doxdocgen|csc|1.3.2
jshint|dba|0.11.0
vscode-glsllint|dto|1.7.1
vscode-wasm|dts|1.3.1
gitlens|eam|11.7.0
vscode-html-css|ecm|1.11.0
vscode-npm-script|eg2|0.3.24
vscode-firefox-debug|fir|2.9.6
dotnet-test-explorer|for|0.7.7
cmake-test-adapter|fre|0.15.2
go|gol|0.31.1
todo-tree|Gru|0.0.215
vscode-test-explorer|hbe|2.21.1
compareit|in4|0.0.2
vscode-insertdatestring|jsy|2.3.1
vscode-uuid-generator|mot|0.3.0
vscode-duplicate|mrm|1.2.1
csharp|ms-|1.24.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.1
jupyter|ms-|2022.1.1201831736
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
hexeditor|ms-|1.9.4
test-adapter-converter|ms-|0.1.5
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.5330
env-cmd-file-syntax|Nix|0.3.0
vetur|oct|0.35.0
laravel-blade|one|1.31.0
laravel5-snippets|one|1.14.0
pixelbyte-love2d|pix|0.1.22
rust|rus|0.7.8
laravel-artisan|rya|0.0.28
yarn-spinner|Sec|2.0.0
vscode-autohide|sir|1.0.7
shader|sle|1.1.5
sass-indented|syl|1.8.19
cmake|twx|0.0.17
unity-debug|Uni|3.0.2
vscode-icons|vsc|11.9.0
code-d|web|0.23.2
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
vsbas813:30436447
vscscmwlcmc:30436992

```

</details>

**Comment by JacksonKearl** [comment]
@aeschli that's intentional. The case we want to avoid is when a child's icon is indented less than its parent's icon. If the user configures a very large indentation where this isn't a concern we just go with the default behavior.

**Comment by aeschli** [comment]
ok, thanks for the heads up. Marking as verified then.
