### ISSUE TITLE
Ctrl+P (find) takes way too long even on a small project ~1000 files

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#1429]
Sublime ctrl+p file search is insanely fast. Why does VSCode take forever. I don't want to search for a private variable or method name. Just search files. This is 99% of the use case.

**Comment by KrofDrakula** [comment]
+1. It's the main blocking issue for me, in conjunction with the Go To Symbol issue I posted earlier.

**Comment by egamma** [comment]
This is high on our backlog.
@bpasero fyi.

**Comment by bpasero** [comment]
#55
