### ISSUE TITLE
Clean up indentation guide lines

### ISSUE THREAD

**Issue by SunnyMonster123** [microsoft/vscode#142953]
When I'm writing code I like to sometimes indent my line by a few tabs rather than just one. 
This is one example where I would use it: 
![image](https://user-images.githubusercontent.com/68454823/153745740-4901af3d-cdec-4164-bc2e-d98114752df6.png)
However, the indent guides/lines make it look very unclean. 

I quite like the way Visual Studio 2022 handles this: Only show the lines where curly braces/parenthesis, etc. is separated into two lines: 
<img width="496" alt="image" src="https://user-images.githubusercontent.com/68454823/153745799-d8e6e6ea-6c54-4d8b-bcd9-aece3cdad2c2.png">

That will not only give me an indication of where indents are, it will also keep my editor clean.

**Comment by hediet** [comment]
VS Code has bracket pair guides for this. You can then disable indentation guides.
