### ISSUE TITLE
Disable auto-add imports by default, or add a confirmation option

### ISSUE THREAD

**Issue by NickWoodward** [microsoft/vscode#142981]
The number of times I've made a typo, corrected it, but not before VSCode has silently added an import at the top of the current file, which has then sent webpack into a spin... I can't count. It's too annoying, because the errors webpack then throws aren't always particularly useful in tracking down the bug.

Why not have some sort of confirmation? Or have it auto complete but have your cursor jump to the import so you know it's happened?

**Comment by mjbvz** [comment]
We're not turning them off by default. They add tremendous value and have been enabled for multiple years. If you don't like them, see the `typescript.suggest.autoImports` / `javascript.suggest.autoImports` settings

Can you share an example where imports are added incorrectly?

**Comment by mjbvz** [comment]
Closing this due to lack of additional info about how auto imports are working incorrectly and lack of additional feedback

As I noted in my earlier comment, turning off auto imports is not a reasonable request but we definitely want to to fix bugs about auto imports
