### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by vatshal1** [microsoft/vscode#142924]
i am getting 'permisssion denied error in .exe file' while using code runner . how to resolve it?

**Comment by itzsimplysurya** [comment]
Hi, @vatshal1

Try disabling your Anti-virus. In most cases, the antivirus causes this kind of problem.

**Comment by vatshal1** [comment]
Thank you it works . Should i always disable antivirus while using vs code?

**Comment by itzsimplysurya** [comment]
@vatshal1 

You are most welcome, No need of having your anti-virus disabled while working on vs-code instead exclude vs-code from the anti-virus. If you're on windows follow this [article ](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26#:~:text=Go%20to%20Start%20%3E%20Settings%20%3E%20Update,%2C%20file%20types%2C%20or%20process.)

**Comment by vatshal1** [comment]
Thx U so much. now the issue is solved.
