### ISSUE TITLE
Text after {{"{{"}} is colored as if between quotes in Angular

### ISSUE THREAD

**Issue by DaniilKanaki** [microsoft/vscode#142903]
Does this issue occur when all extensions are disabled?: It is mentioned below after the problem description.

- VS Code Version: 1.64.2
- OS Version: Windows 10 Pro 21H1, Build 19043.1466, Windows Feature Experience Pack 120.2212.3920.0
- Angular Language Service Version: 13.2.3.

Steps to Reproduce:

1. Writing _{{"{{**"}} something_** or _{{'{{**'}} something_** in application template "src/app.component.html".
2. Seeing that the part I marked bold is colored in VS Code as if between quotes in Angular. By **something** I mean everything before end of line or... I tried to insert _{_ symbol before **something** and it worked so that **something** turned back to normal non-quoted color. But then I deleted it, did something else and tried to insert it again to the same location before **something**. And this time it had no effect because **something** was still colored as if between quotes.

Note: _{{"}}**"}_ something** looks good.

Does this issue occur when all extensions are disabled?: I had only 1 extension turned on and it was Angular Language Service. When I turned it off, whole the Angularity evaporated away, so whole the expression _{{"{{"}} something_ looked like an ordinary text as if it had no any syntactic meaning.

VS Code is amazing! Thank you for paying attention!

**Comment by aeschli** [comment]
Can you add a screenshot and the full code snippet that show the problem?
Does this reproduce with extensions disabled? 

Here is what I see with only the HTML extension (no Angular extension installed/enabled):
![image](https://user-images.githubusercontent.com/6461412/154986284-e7b68ae6-28e8-426a-a98f-f61160dbfd7a.png)
