### ISSUE TITLE
Zoom in the sidebar

### ISSUE THREAD

**Issue by techflashYT** [microsoft/vscode#142939]
Would it be possible to add a feature to zoom in the sidebar?  
For example, go from the default level of: 
![image](https://user-images.githubusercontent.com/72118300/153733066-772a8c09-1773-4ab1-b3c7-262c7cb25421.png)
To something like this: (Excuse the awful quality, just used a crappy image editor)
![image](https://user-images.githubusercontent.com/72118300/153733117-dacc634c-d004-424f-898e-204f5b442a65.png)

**Comment by sbatten** [comment]
@techflashYT are you requesting that only the side bar be zoomed?

**Comment by techflashYT** [comment]
Yes, a feature that allows the sidebar to be zoomed in without affecting the rest of the GUI, because currently, the only way (that I know) to do this is to zoom in the entire window with `CTRL` + `+`
