### ISSUE TITLE
Problems not Dispalyng

### ISSUE THREAD

**Issue by Temujin-47** [microsoft/vscode#142963]
Issue Type: <b>Feature Request</b>

VS Code is not showing problems in my program even if there is an error. 

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Please provide more details, including coding language.

/gifPlease

**Comment by gjsjohnmurray** [comment]
An email reply to GitHub will not add a video or screenshot attachment to the issue. Please update the issue directly on GitHub instead. Use the link in the footer of the email notification that my comment will send you.

**Comment by Temujin-47** [comment]
Hi,
Basically Vs Code is not recognizing problems in my code. Even though there
are errors in the code, Vs code fails to display it in the problems window. It's happening in both C++ and Python.
I am sending you a video as an example.

Please reach out quickly as it is a major issue for a beginner like me.
![bandicam 2022-02-13 21-37-21-292](https://user-images.githubusercontent.com/97385793/153762683-14d58de3-59c9-491b-8c36-5e1846b752c8.gif)

Thank You

**Comment by sandy081** [comment]
May I know if you installed the [c++ extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools)

**Comment by Temujin-47** [comment]
Yes I installed the c++ extension as well as code runner.

**Comment by sandy081** [comment]
Ok, please file issue against the C++ extension because the extension is responsible to create the problems
