### ISSUE TITLE
Test: editor history navigation scoped to group or editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#142952]
Refs: https://github.com/microsoft/vscode/issues/36634, https://github.com/microsoft/vscode/issues/45233

- [x] anyOS @daviddossett
- [x] anyOS @alexr00

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23142952%0A%0A&assignees=bpasero)

---

We always provided methods to navigate through editor locations via "Go Back" and "Go Forward". These locations are being put on stack based on changing editors and changing text selection (i.e. moving the cursor with mouse or keyboard). 

This milestone a new setting is added to scope this navigation on the active editor group or active editor. By default navigation will be across all opened editor groups and editors.

**Note:** if you run with `--verbose` you can see the history navigation stack by searching for `[History` in the console:

![image](https://user-images.githubusercontent.com/900690/153216328-b5a7aaab-d36f-4392-8af9-f82eeff9ae8a.png)

**Testing**
* review the `workbench.editor.navigationScope` setting makes sense to you
* accumulate editor history state across multiple editors and multiple groups including text selection changes within text editors that are meaningful (>10 lines apart)
* enable `editorGroup` as scope and validate that commands such as "Go Back", "Go Forward", "Go Last" and "Go Previous" only operate on the active editor group
* verify each editor group has its own stack that can be navigated individually
* verify you never end up in the editor of a different group when navigating with this setting
* enable `editor` as scope and validate that commands such as "Go Back", "Go Forward", "Go Last" and "Go Previous" only operate on the active editor in the active group
* verify each editor has its own stack that can be navigated individually
* verify you never end up in a different editor when navigating with this setting

**Comment by daviddossett** [comment]
Works great! 👍
