### ISSUE TITLE
Text buffer memory leak

### ISSUE THREAD

**Issue by cynecx** [microsoft/vscode#142933]
```
Version: 1.65.0-insider
Commit: bb221a61d29deabd99ee9431736d04f2175cb596
Date: 2022-02-11T05:18:07.499Z
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Linux x64 5.16.8-arch1-2
```

Same as in https://github.com/microsoft/vscode/issues/107999.

Steps to Reproduce:

1. Prepare a large text file (Citylots.json is ~190MB):
```sh
wget "https://github.com/zemirco/sf-city-lots-json/blob/master/citylots.json"
cp citylots.json evenlarger.json
cat citylots.json >> evenlarger.json
cat citylots.json >> evenlarger.json
```
2. Open evenlarger.json in vscode.
3. Scroll around.
4. Close the file.
5. Observe the memory usage through "Process Explorer".

![Screenshot from 2022-02-12 18-27-44](https://user-images.githubusercontent.com/5961244/153721559-ee918063-4305-4d96-9596-ff6866e34ab2.png)

Does this issue occur when all extensions are disabled?: Yes

This is certainly a regression because 1-3 months ago, I haven't noticed this memory leak.

A memory snapshot proves that a reference to the text buffer is still around somewhere:

![Screenshot from 2022-02-12 18-30-13](https://user-images.githubusercontent.com/5961244/153721646-fcb9afd9-eab9-4943-b03a-e3aef5e38464.png)

![image](https://user-images.githubusercontent.com/5961244/153721733-cdefcef0-71be-4fb4-951b-776ac1743a73.png)

**Comment by hediet** [comment]
I cannot reproduce. Also, the download link to the json file is invalid, you need to pass `?raw=true`.

Note that garbage collection takes some time until unused text models are cleaned up.
I cannot explain why there are some text models kept alive even if all editors are closed, but even after opening hundreds of files, there are at most two such hanging (and disposed) text models. These text models no longer keep the text buffer alive.

**Comment by bpasero** [comment]
I think a text model that is being disposed when you close an editor is immediately freed from memory if there are no more references. But one thing I remember is that when an extension resolves a text document for any reason, we only free up such a reference after a certain timeout because there is no API to release the use of a text model. So maybe retry with extensions disabled.

**Comment by cynecx** [comment]
@alexdima https://github.com/microsoft/vscode/commit/120318d90ede07db2331de994bd9870a809a5a62 seems to have fixed this. I can't seem to reproduce this on the latest insiders. Thanks!
