### ISSUE TITLE
Vscode not responding before displaying breakpoint

### ISSUE THREAD

**Issue by alessandrosales** [microsoft/vscode#142940]
Issue Type: <b>Bug</b>

I'm using WSL with Ubuntu for my development environment. I notice that when trying to debug vscode crashes before displaying the breakpoint stop.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (3.68GB free)|
|Process Argv|--crash-reporter-id 61784ae5-dcc7-4cbe-8b44-51100054accb|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 x 2904)|
|Memory (System)|12.43GB (7.38GB free)|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
nestjs|ash|1.4.2
vscode-drawio|hed|1.6.4
rails-snippets|Hri|1.0.8
vue|jcb|0.1.5
vscode-language-pack-pt-BR|MS-|1.64.6
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.217.4
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
debugger-for-chrome|msj|4.13.0
slim|sia|0.1.2
vscode-icons|vsc|11.9.0
vscode-ruby|win|0.28.0
vscode-sqlite|ale|0.14.0
vscode-gemfile|bun|0.4.2
vscode-github-actions|csc|0.22.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.2.0
go|gol|0.31.1
beautify|Hoo|1.5.0
vscode-docker|ms-|1.19.0
vscode-language-pack-pt-BR|MS-|1.64.6
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.1
jupyter|ms-|2022.1.1201831736
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
vsliveshare|ms-|1.0.5330
sftp|Nat|1.15.13
vetur|oct|0.35.0
polacode|pnp|0.3.4
ruby|reb|0.28.1
slim|sia|0.1.2
html-preview-vscode|tht|0.2.5
php-debug|xde|1.23.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
vsbas813:30436447
vscscmwlcmc:30436992

```

</details>

**Comment by weinand** [comment]
What debugger are you using?
