### ISSUE TITLE
problem tab

### ISSUE THREAD

**Issue by Abbas2609** [microsoft/vscode#142988]
Issue Type: <b>Bug</b>

even if there is a error it doesnt appear in the problem window and this makes stuff difficult to correct

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.87GB (6.67GB free)|
|Process Argv|--crash-reporter-id 3ae74772-9f3b-4515-9d80-bf0e2f84a222|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
code-runner|for|0.11.7
c-cpp-runner|fra|3.1.1
better-cpp-syntax|jef|1.15.13
remote-containers|ms-|0.217.4
remote-ssh|ms-|0.70.0
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.9.0
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17
c-cpp-flag-debugging|uts|0.0.1
vscode-lldb|vad|1.6.10

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
pythonvspyt640:30436486
vsbas813:30436447
vscscmwlcmt:30436993

```

</details>

**Comment by sandy081** [comment]
> even if there is a error it doesnt appear in the problem window and this makes stuff difficult to correct

Can you please let us know how do you know that there is an error?
