### ISSUE TITLE
No code action for XX when XX is associated to a Command and not a WorkspaceEdit

### ISSUE THREAD

**Issue by lrnv** [microsoft/vscode#142982]
Issue Type: <b>Bug</b>

Hi, 

This is a followup to https://github.com/valentjn/vscode-ltex/issues/363#issuecomment-893600573.
It seems like putting the following in `keybindings.json`: 

```json
[
    {
      "key": "ctrl+shift+q",
      "command": "editor.action.codeAction",
      "args": {
        "kind": "quickfix.ltex.acceptSuggestions"
      }
    },
    {
      "key": "ctrl+shift+d",
      "command": "editor.action.codeAction",
      "args": {
        "kind": "quickfix.ltex.addToDictionary"
      }
    }
]

```

does work for `acceptSuggestions`, which is a code action associated to a `WorkspaceEdit`, and does not for `addToDictionary`, which is a code action associated to a `Command`, and produce the `No code action for quickfix.ltex.addToDistionary available` popup when hit. According to @valentjn, this seems to be a bug of VS Code:

> I think that's a bug in VS Code. The difference between `acceptSuggestions` and the other kinds of quick fixes is that the code action corresponding to `acceptSuggestions` is [associated to a `WorkspaceEdit`](https://github.com/valentjn/ltex-ls/blob/23f83f2fd0e4fea4930bbbb0997fc5f23d7ff576/src/main/kotlin/org/bsplines/ltexls/server/CodeActionGenerator.kt#L127-L131), but the others are [associated to a `Command`](https://github.com/valentjn/ltex-ls/blob/23f83f2fd0e4fea4930bbbb0997fc5f23d7ff576/src/main/kotlin/org/bsplines/ltexls/server/CodeActionGenerator.kt#L176-L179). However, I don't see a reason why VS Code shouldn't be able to run those quick fixes, too. Please refer to [microsoft/vscode](https://github.com/microsoft/vscode) for this.

Thoughts ? 

VS Code version: Code - Insiders 1.65.0-insider (0283cec6ec2c2d5ec39006a1048b8dc3ea8bc955, 2022-02-08T05:16:42.414Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.90GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/u009192/Documents/project_ggchd/ggchd_paper --crash-reporter-id ba05d066-2a4b-4588-a50c-4c80808f45e6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.36.1
latex-workshop|Jam|8.23.0
vscode-ltex|val|13.1.0

</details>

**Comment by mjbvz** [comment]
Please share a minimal extension sample that demonstrates  what you think the issue is

**Comment by lrnv** [comment]
I do not now what you mean by a minimal extension sample, but i can tell you taht the following acitons reproduces the issue : 

- Open a new folder in VSCode, and add the upper code in the `keybindings.json`. 
- Install the `LTeX` extension
- Open a new file, set its language to markdown (or name it file.md), with the following content : 

```
This is a sentences in a file, with a typo in it. 
This is a second sentence, with a new unknown WordToAddToDistionary. 
```

You'll see that the words `a sentences` and `WordToAddToDictionary` are both underlined by LTeX. On the first one, you can use `ctrl+shit+q` to activate the `quickfix.ltex.acceptSuggestions`, which would work. 
On the second one, `ctrl+shift+d` will NOT launch `quickfix.ltex.addToDictionary`, but instead provide a popup that says : 

```
No code action for `quickfix.ltex.addToDictionary` available
```

Is that enough of a reproducible exemple ?

**Comment by mjbvz** [comment]
Please put together a small extension that demonstrates the issue. Testing with full LaTeX extension takes a lot of time because we have to figure out what that extension is doing and if it's the root cause or if VS Code is causing problems

You can build on the code actions sample: https://github.com/microsoft/vscode-extension-samples/tree/main/code-actions-sample

**Comment by lrnv** [comment]
Sorry but I do not have the skills to put together another extension that will show off the problem.
