### ISSUE TITLE
.vscode folder missing from zipped Java project 

### ISSUE THREAD

**Issue by cpa-student** [microsoft/vscode#142936]
Issue Type: <b>Bug</b>

Windows 11  only
Right click on Java project folder and select  Compress to ZIP file
Zip file is created, but .vscode folder and contents are missing

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (8.83GB free)|
|Process Argv|--crash-reporter-id bf46b757-6fd9-49d0-b996-c01e29f7292e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
quick-html-previewer|dai|1.0.1
javadoc-generator|Kee|2.0.0
git-graph|mhu|1.30.0
vscode-boot-dev-pack|Piv|0.1.0
vscode-spring-boot|Piv|1.31.0
material-icon-theme|PKi|4.13.0
java|red|1.3.0
markdown-preview-enhanced|shd|0.6.1
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
vscop841cf:30437298
dsvsc009:30436279
pythonvsnew555cf:30436485
vsbas813:30436447
vscscmwlcmc:30436992

```

</details>

**Comment by gjsjohnmurray** [comment]
I don't think VS Code itself provides a "Compress to ZIP" option.

You could use the `Start Extension Bisect` command to discover which one is contributing it in your setup.

/causedByExtension
