### ISSUE TITLE
maven的localRepository不生效

### ISSUE THREAD

**Issue by yidahuan** [microsoft/vscode#142956]
maven.settingsFile、java.configuration.maven.userSettings和java.configuration.maven.globalSettings 这3个参数都配置到我的settings.xml了，重启，重新加载项目目录无数次，maven仓库路径始终用默认的~/.m2/repository

**Comment by CodeCrazy-ywt** [comment]
I have configured `maven.settingsFile`, `java.configuration.maven.userSettings` and `java.configuration.maven.globalSettings` in my settings.xml, but even after I reload vscode and project directory, maven repository is still using the default directory.
