### ISSUE TITLE
Be able to treat AltGr as a different key for extra keybindings possibilities

### ISSUE THREAD

**Issue by igoracmelo** [microsoft/vscode#143033]
In my keyboard there are two alt keys: left alt (regular alt) and right alt (AltGr).
I would like to be able to create shortcuts with AltGr without causing conflicts with my left alt key. 
In other words, be able to treat them as distinct keys.

**Comment by alexdima** [comment]
@igoracmelo What OS are you on? Are you aware of any software that is able to do this?

**Comment by igoracmelo** [comment]
@alexdima I'm not sure if any app I used before could differenciate between alt and altgr.
I am on Ubuntu 20.04 LTS.

I used the command xev to check keycodes of alt and altgr, and they are different in my keyboard.
<kbd>Alt</kbd> keycode is 64 while <kdb>AltGr</kbd> is 108.

Not sure if VSCode could treat them as separate things though.

**Comment by alexdima** [comment]
VS Code is built with Electron, which is built on top of Chromium. We dispatch keyboard events as they come from the browser, using the [`keydown`](https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event) event. From experimenting with it, I can't find a difference between an `Alt+something` keypress and an `AltGr+something` keypress:

Using https://w3c.github.io/uievents/tools/key-event-viewer.html

> <img width="1097" alt="image" src="https://user-images.githubusercontent.com/5047891/154661421-3d0c001d-c440-42b7-81e1-a11888be52c7.png">

Notice how rows `#2` and `#4` don't have any distinguishable difference.
