### ISSUE TITLE
Debug Protocol bug: stackTraceRequest fires twice, every stop

### ISSUE THREAD

**Issue by theIDinside** [microsoft/vscode#143097]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61
- OS Version: any

VSCode sends two stackTraceRequests every stop, with `{ start: 0, levels: 20 }`. With supportsDelayedStackTraceLoading set to true, the first takes `{ start: 0, levels: 1 }` and the second `{start 1: levels 19 }`

**Comment by gjsjohnmurray** [comment]
Does this also happen on the current release, 1.64.2?

**Comment by weinand** [comment]
This is the expected behavior:
the first call is used to probe for the total number of frames (optional property "totalFrames").
