### ISSUE TITLE
minimap does not scroll 

### ISSUE THREAD

**Issue by illmillrig** [microsoft/vscode#143023]
the minimap does not scroll if you click anywhere in it and drag the mouse up or down.  You MUST click the button.  which means you can only drag from where you currently are viewing.  which basically makes it a normal scrollbar that's extra wide.

seems like quite a few tickets have been created over this, briefly discussed, then closed without a solution and also preventing further discussion.

**Comment by gjsjohnmurray** [comment]
> You MUST click the button

Which button?

/needsMoreInfo including version, platform and maybe a screenshot. My 1.64.2 on Windows isn't behaving as you describe.

**Comment by alexdima** [comment]
@illmillrig This is because, by default, the minimap might not represent the entire file, but a fixed number of lines around the viewport. So by default, the minimap can also scroll if the file is too long. It can therefore not be used "like a scrollbar". However, you can configure `"editor.minimap.size": "fit"` or `"editor.minimap.size": "fill"` which will prevent that the minimap also scrolls and then the click & drag works as you request.

Here's what I mean:

https://user-images.githubusercontent.com/5047891/153907220-194ebf22-3ea0-4b8c-bafc-aa72990a0c8e.mp4

**Comment by illmillrig** [comment]
that's not a workaround. that's just how it currently works.  but you should be able to click outside the highlighted area and with the mouse button still pressed, drag up and down to scroll. this is how this works in other ide's.

**Comment by illmillrig** [comment]
hmmm, I see what you're saying.  But I still think it's possible in proportional mode. forget about the code for a second and play around with it, it sure seems there's no reason why it can't scroll up and down with the mouse still pressed after clicking/jumping to somewhere in the minimap. it's logical functionality.

Even with a file that has lots of lines, the highlighted region may not be under the mouse cursor after the click/jump, but I don't think that matters much.  It can still move with the mouse as though it were.  not being able to click and drag just feels half implemented.  

I'd honestly prefer to use the proportional setting if i could.  It only really seemed to matter on longer line files anyways. for a few files i tested it in, there is no discernible difference between proportional and fit, except that you can't click/drag the minimap in proportional.

**Comment by illmillrig** [comment]
so on a large file, I click towards the bottom of the minimap, the editor jumps to show those lines, but the highlighted region is not even close to where I clicked in the minimap due to the size/length of the file.  but the mouse is still pressed, and I move the mouse 100px down, so then just scroll down that much.

I think it's a valid transformation to make, I don't think it matters that the highlighted region is not directly under the mouse after clicking.
