### ISSUE TITLE
Test: verify objects and array previews

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#14305]
Test for https://github.com/Microsoft/vscode/issues/14304:
Complexity: 1

- [x] node: any OS - @sandy081  
- [x] node2: any OS - @weinand 

See #14304 for the details what has changed.

Verify that the previews for objects and arrays in the variables and watches view, and the debug repl are correct and useful.

**Comment by roblourens** [comment]
Should we say that this item covers verifying the same thing in node2, or should I create a separate item?

**Comment by weinand** [comment]
@roblourens I will test for node2
