### ISSUE TITLE
Cursor Jumps to wrong position with Snippet

### ISSUE THREAD

**Issue by snoweuph** [microsoft/vscode#143099]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64
- OS Version: Linux Mint 20.3 x86_64

Steps to Reproduce:

1. Add this custom Snippet
```json
"CommandCategory": {
		"prefix": "!command-category",
		"scope": "javascript,typescript",
		"body": [
			"import BaseCommandCategory from '../../types/BaseCommandCategory'",
			"",
			"const Category: BaseCommandCategory = {",
			"\tdisplayName: '${1:DisplayName}',",
			"\tuniqueId: 'test',",
			"\tpermissions: [${2:'ADMINISTRATOR'}],",
			"}",
			"",
			"export default Category;"
		],
		"description": "the definition of a command category"
	}	
```
2. execute the snippet
3. enter first value and press tab, the cursor doesn't jump to the second value but to the end of the line of the first value instead

**Comment by jrieken** [comment]
Works for me. Please refine your steps. When you say "enter first value" does that mean plain typing or invoking IntelliSense?

**Comment by snoweuph** [comment]
did a update since then and its now fixed, cant reproduce anymore, sry for stealing your time
