### ISSUE TITLE
Chinese IME is broken on github.dev`s web editor

### ISSUE THREAD

**Issue by LeoooY** [microsoft/vscode#143018]
### Steps to reproduce
1. create a new '.md' file
2. input more than 10 lines
3. insert some word with chinese IME in the middle of the '.md' file.

https://user-images.githubusercontent.com/38848201/153891052-73e82159-c632-46a5-9cb8-915da0774015.mov

### What you expected to see
successfully input word '微软'
### What you actually saw
the first word of the chinese pinyin is cutted off unexpectedly.

### Version of VS Code
1.64.2 on github.dev

### Operating System
- MacOS Monterey 12.2.1 (m1 chip)
- Chrome 98.0.4758.80
- User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36
- Embedder: github.dev

**Comment by alexdima** [comment]
@LeoooY As a workaround, you can configure `"editor.accessibilitySupport": "off"`.

---

Simplified repro steps:
* create a plaintext file with the content:
```
line1
line2
line3
line4
line5
line6

line8
line9
line10
line11
```
* switch to `Pinyin - Traditional` keyboard layout
* type `weiruan` and press `1`
* you should end up with `為軟`, not `w欸軟`

**Comment by alexdima** [comment]
This is also fixed by e356139a1095b92e0a89be34553aeedb24aa78c0. Please verify with tomorrow's insiders.

**Comment by alexdima** [comment]
For verification, you can use https://insiders.vscode.dev/

**Comment by LeoooY** [comment]
it works well on the insider vesion, thanks you alexdima. 👍👍👍
