### ISSUE TITLE
Delayed input on bash terminal 

### ISSUE THREAD

**Issue by abitamaspp** [microsoft/vscode#143008]
Issue Type: <b>Performance Issue</b>

I have WSL installed in my laptop, and I love the fact that VS Code can open my Linux repo/folder. But in this version (although I believe it had happened before this version), everytime I type command on the bash terminal, it always show the command delayed.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.43GB (1.97GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu-20.04/mnt/c/Users/ADMIN/Documents/Automatalabs/tekstrak_OTS --crash-reporter-id ef002fd7-f681-4e59-bfa2-b347810c7e8f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|Memory (System)|7.43GB (1.97GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    93	   224	code main
    0	   215	  5004	   gpu-process
    0	    72	  5052	   extensionHost
    0	    59	 14520	     "C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\ADMIN\.vscode\extensions\ms-vscode-remote.remote-wsl-0.64.2\dist\wslDaemon.js
    0	     6	 12528	       C:\WINDOWS\System32\wsl.exe -d Ubuntu-20.04 sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" f80445acd5a3dadef24aa209168452a3d97cc326 stable code-server .vscode-server --host=127.0.0.1 --port=0 --connection-token=188664130-3969116729 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms'
    0	     6	  8932	         console-window-host (Windows internal process)
    0	     6	 14836	         C:\WINDOWS\system32\lxss\wslhost.exe {6a02d980-e10e-4fa6-8465-07720fead956} 496 504 508
    0	     8	  9460	           console-window-host (Windows internal process)
    0	    24	  6488	   crashpad-handler
    0	    79	  8900	   issue-reporter
    0	    37	 10592	   utility-network-service
    0	    85	 13016	   shared-process
    0	    60	  8088	     fileWatcher
    0	    60	 13208	     ptyHost
    0	   225	 13744	   window (main.py - tekstrak_OTS [WSL: Ubuntu-20.04] - Visual Studio Code)
Connection to 'wsl+ubuntu-20.04' could not be established
```

</details>
<details>
<summary>Workspace Info</summary>

```

Connection to 'wsl+ubuntu-20.04' could not be established;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.64.2
tabnine-vscode|Tab|3.5.24

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
vsbas813:30436447
vscscmwlcmt:30436993
cppdebug:30437093

```

</details>

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" terminal
