### ISSUE TITLE
Tell VSCode how many stack frames it should request

### ISSUE THREAD

**Issue by theIDinside** [microsoft/vscode#143095]
I would like a feature where I can explicitly tell VSCode to only request 10 frames at a time. For non-trivial applications this would be a huge performance gain. Right now, VSCode no matter what, forces one to get 20 frames (anything less will hint VSCode that there are no more frames, and the monotonic increasing of "totalFrames" according to the specs, doesn't seem to help here)

For instance, if the debug adapter could tell VSCode to only request 5 at a time, even a naive approach in such a context can be done; where it just keeps requesting the top 5 at every step. But for non trivial applications, this naive approach is entirely not feasible. It can take above second-responses to get 20 stack frames, if those frames are spread out across a large library or binary.

**Comment by weinand** [comment]
@theIDinside since this feature asks for an addition to the Debug Adapter Protocol, I suggest that you file it against DAP.
Please note: there are more DAP clients than just VS Code. So you probably want to have support for this feature in all clients...

**Comment by roblourens** [comment]
I haven't checked the implementation to be sure, but it seems like if the client asks for 20, maybe you could simply respond with 5 but set `totalFrames` to indicate that there are more
