### ISSUE TITLE
New VS code freezes Linux OS

### ISSUE THREAD

**Issue by janbodnar** [microsoft/vscode#143025]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: The newest one
- OS Version: Xubuntu Linux

I cannot add any more details since the OS is broken. 

I have updated the Code to the most recent one. When working with code, I was about to delete a larger file (around 400MB) from the Code by right-clicking a selecting delete. The whole system froze. I had to do a cold reboot which resulted in a completely broken system. 

Were there any IO updates in the recent Code update?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Alfetta159** [comment]
I'm seeing this in Zorin OS 16.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by janbodnar** [comment]
My OS is broken now; I use Windows now. I have to save my data & reinstall. I was curious if there were some big changes in IO in Code.

**Comment by bpasero** [comment]
Ok we can reopen when you come back to Linux.
