### ISSUE TITLE
"next problem in files" is broken

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#143070]
Issue Type: <b>Bug</b>

i have 233 problems in my problems window, but "Next problem in files..." (f8) just cycles between problem numbers 5, 6 & 7. When I'm on problem #7 and hit f8, it just goes to problem #5. what about the other 226 problems?

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-19041-Microsoft
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.66GB (19.64GB free)|
|Process Argv|--crash-reporter-id 70645636-42ae-4864-b371-1810b42a2956|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2901)|
|Memory (System)|47.66GB (19.66GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.34GB (15.84GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.34GB (15.84GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.15.13
remote-containers|ms-|0.217.4
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
doxdocgen|csc|1.3.2
better-cpp-syntax|jef|1.15.13
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17

(2 theme extensions excluded)

</details>

**Comment by Spongman** [comment]
this seems to happen more when there are '#include errors detected' or 'cannot open source file' errors in the problem list.

**Comment by Spongman** [comment]
Yes, clicking the errors in the problems window works fine.

**Comment by sandy081** [comment]
@Spongman Can you please provide steps to reproduce? It would be great if you can share a sample repo in which we can reproduce this.

**Comment by Spongman** [comment]
[q.tar.gz](https://github.com/microsoft/vscode/files/8112442/q.tar.gz)

i'm running vscode on windows connected to a CentOS7 wsl guest, although you could probably use _any_ wsl guest.

- extract archive
- open `q/` in code
- install cpptools extension
- open _both_ `a.cpp` and `b.cpp` files in code
- wait for intellisense scan to complete. you should see 4 errors in the problems window.
- you may need to edit `tasks.json` to fix the path to `gcc`
- make sure `a.cpp` is the currently focused document in code...
- run the build task
- you should now see 5 errors.
- f8 repeatedly. the 'N of 5 problems' message should go 1,2,3,4,5,1,2,3 etc. it doesn't. just now it's gone 1,1,2,3,4,3,4,1,2,1,2,3,4,1,2

**Comment by jrieken** [comment]
This doesn't reproduce with a simple TypeScript sample... Tho, there should no difference. @Spongman can you maybe attach a screen recording of what you are seeing? Are all problems errors or are some warnings?


https://user-images.githubusercontent.com/1794099/155406385-f0d0fd75-ea69-4197-9f9a-a1ea5ead68e2.mov

**Comment by piersh-aetheros** [comment]
@jrieken did you try with the steps I included above?

**Comment by jrieken** [comment]
Well, I told you that I have tried with a simple sample. I also know that marker navigation is independent of the language for which they are reported and I do know that the severity makes a difference. So, please answer these questions

**Comment by piersh-aetheros** [comment]
please let me know if you can reproduce with the exact series of steps i indicated above. _that_ is the bug i have reported here.

**Comment by piersh-aetheros** [comment]
no more information is needed, unless you are not able to reproduce using the steps i indicated above.

**Comment by piersh-aetheros** [comment]
![Recording 2022-02-23 at 13 15 01](https://user-images.githubusercontent.com/66884198/155409760-34dbf072-9c8b-4530-80c5-c870f2ed0361.gif)

**Comment by jrieken** [comment]
This is helpful and the navigation does indeed seems random. I wonder for what locations (line, column) those errors have been reported for. Can you open the problems view (F1 > Toggle Problems) and take a screen shot showing the 5 errors across those files. Thanks.

**Comment by Spongman** [comment]
![image](https://user-images.githubusercontent.com/1088194/155412231-765ebd85-6e9f-411c-ae17-820cd3294d86.png)

to be honest i was _really_ hoping that providing the archive & repo steps would be sufficient for you (MS) to be able to repro this yourselves.

**Comment by jrieken** [comment]
> to be honest i was really hoping that providing the archive & repo steps would be sufficient for you (MS) to be able to repro this yourselves.

I do understand and you have reported a good issue! Tho sometimes it's complicated... I work on the mac, so running WSL is a bit extra effort, getting the cpp extension (which?) is some extra effort. Trying things in TS or writing a fake extension that adds exactly those diagnostics is very, very easy and quick for me. On top, I know that all our UI is language agnostic. All of this makes me ask these (annoying) questions and thanks for standing by. 

The good news is that I am able to reproduce now (with some staged TS files). Fix should be easy and should make it in the next release

**Comment by jrieken** [comment]
This is a regression from https://github.com/microsoft/vscode/pull/135736

**Comment by piersh-aetheros** [comment]
interesting. i was also able to reproduce while connected to a linux VM over remote-ssh. the c++ extension i used was `cpptools`, as indicated in the repro steps.

**Comment by jrieken** [comment]
To verify

* have `a.ts` with `console.logg('dddd');console.logg('dddd');console.logg('dddd')`
* have `b.ts` with `b;console.logg();console.logg()`
* repeatedly hit `F8` and make all errors are travered in sane order  (starting at current cursor and than in order of position)
