### ISSUE TITLE
Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by gpoluch** [microsoft/vscode#143068]
Issue Type: <b>Bug</b>

1. Open VS Code and wait some time.
2. Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory appears.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<img width="422" alt="Javascript heap out of memory" src="https://user-images.githubusercontent.com/10855110/153956129-a4ea8ba7-ca43-4954-9aec-da41164add7e.PNG">

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.39GB (8.14GB free)|
|Process Argv|--crash-reporter-id 166ecbff-3b92-4564-965e-22a9c4c09ce7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
apex-pmd|chu|0.5.8
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
prettier-vscode|esb|9.2.0
lana|Fin|1.4.1
git-graph|mhu|1.30.0
vscode-xml|red|0.19.0
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode-apex|sal|53.16.0
salesforcedx-vscode-apex-debugger|sal|53.16.0
salesforcedx-vscode-apex-replay-debugger|sal|53.16.0
salesforcedx-vscode-core|sal|53.16.0
salesforcedx-vscode-expanded|sal|53.16.0
salesforcedx-vscode-lightning|sal|53.16.0
salesforcedx-vscode-lwc|sal|53.16.0
salesforcedx-vscode-visualforce|sal|53.16.0
errorlens|use|3.4.1
sfdx-package-xml-generator|Vig|2.0.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438167
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
vsbas813:30436447
vscscmwlcmt:30436993

```

</details>

**Comment by mjbvz** [comment]
Please try tracking down which extension causes this issue by running an extension bisect: https://code.visualstudio.com/blogs/2021/02/16/extension-bisect

Once you figure this out, file an issue against that extension so they can investigate

**Comment by gpoluch** [comment]
I verified with bisect and XML Language Support by Red Hat causing this issue. I suppose that we can close.

<img width="403" alt="XML Extension Issue" src="https://user-images.githubusercontent.com/10855110/154047522-37589d10-2ce1-4c45-897b-69dd3190ec49.PNG">
