### ISSUE TITLE
Syntax highlight is lagged.

### ISSUE THREAD

**Issue by zzh8241102** [microsoft/vscode#143087]
Issue Type: <b>Bug</b>

**Syntax Highlight is so slow on my m1 machine. And all of my friends apple silicon machine. It's not responsive at all! we can barely use vsc to develop, it's such a big issue.**

Expected result: No lagging when the editor is highlighting the syntax

Actual result: Very noticable lagging when the editor is higlighting the syntax. Error highlighting  also suffers from this problem.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:56.651Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id 20d7662b-0021-4192-a46d-220f2e102f0f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
bracket-pair-colorizer|Coe|1.0.62
doxdocgen|csc|1.3.2
auto-rename-tag|for|0.1.10
code-runner|for|0.11.7
copilot|Git|1.7.5003
vscode-pull-request-github|Git|0.36.1
beautify|Hoo|1.5.0
better-cpp-syntax|jef|1.15.13
vscode-github|Kni|0.30.7
vscode-latex|mat|1.2.0
theme-monokai-pro-vscode|mon|1.1.20
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.1
jupyter|ms-|2022.1.1201831736
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.4
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
material-icon-theme|PKi|4.13.0
LiveServer|rit|5.7.4
vscode-lldb|vad|1.6.10
vscode-icons-mac|way|7.25.3
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrt:30437039
vsrem710cf:30416617
pythonvspyt640:30436486
vsbas813:30436447
vscscmwlcmt:30436993

```

</details>

**Comment by gjsjohnmurray** [comment]
I suggest you test with the absolute minimum set of extensions you need for the language you are coding in (which you didn't tell us). If performance is good, enable other extensions progressively until you find which one is causing the slow-down.

**Comment by mmlacak** [comment]
Try to disable everything Jupyter related, if you don't use it.

**Comment by CmpCtrl** [comment]
I have noticed the same on windows 10 with a core i7. Roughly 8-10 seconds of lag for basic syntax highlighting with only the pylance and python extensions enabled. 

I noticed it yesterday, which i think was the first time i had restarted allowing vscode to update.

**Comment by zzh8241102** [comment]
> I have noticed the same on windows 10 with a core i7. Roughly 8-10 seconds of lag for basic syntax highlighting with only the pylance and python extensions enabled.
> 
> I noticed it yesterday, which i think was the first time i had restarted allowing vscode to update.

The same problem.
