### ISSUE TITLE
Helping to resolve conflicting shortcuts

### ISSUE THREAD

**Issue by cognominal** [microsoft/vscode#143020]
## Motivation

Because default shortcuts are curated, conflicts can come from additional keybindings from user and/or extensions.

Extensions that emulate other editors cause major problems if there is no way for the user to identify the conflicts and choose in certain cases the shortcut provided by default or the shortcut provided by the extension.

## The problem in context

The shortcut preference panel is insufficient

The preference panel obtained by the command workbench.action.openGlobalKeybindings does specify the provenance of the keybinding. But in the case of extension, it does not say the specific extension. Sometimes the `when` field gives a clue. Sometimes not.

## A possible solution

For a given shortcut, I propose the context menu to provide two new entries. In the case of an extension it would provide its name.

One menu entry would show the shortcuts that conflict with other shortcuts.  In addition it may show identical shortcuts from different that don't conflict because of specific when fields. These are not really a major problem but can cause confusion.

The second entry would show all the shortcuts for the extension.
Maybe that already exists and that would be a good way to advertise it.

## Another partially complementary way to do it

Maybe the `source` field should name the extension. Clicking on it would sort the shortcuts by source.

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/121673
