### ISSUE TITLE
Kotlin Support 

### ISSUE THREAD

**Issue by jaivardhan-bhola** [microsoft/vscode#143010]
VS Code doesn't have intellisense and other tools for development in Kotlin. I can't even run a .kt file without a 3rd party extension. I have to switch to ItelliJ IDEA or Android Studio for Kotlin.

**Comment by JacksonKearl** [comment]
Many languages require extensions. This is by design, we want to keep the core VS Code as slim as possible.

**Comment by jaivardhan-bhola** [comment]
If Vscode gets a Extension by Microsoft that supports running for Kotlin script it would be very helpful as developers would not have to switch to other interpreters for Mobile Development
