### ISSUE TITLE
Expanding selection not working as expected

### ISSUE THREAD

**Issue by ronytesler** [microsoft/vscode#143019]
Does this issue occur when all extensions are disabled?: Yes/No - Yes

- VS Code Version: 1.64.1
- OS Version: Windows 10

Steps to Reproduce:

1. I have this code in a dart file:
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // runApp(Register()());
}

class MyHomePage  {
  MyHomePage({Key? key, required this.title});


  final String title;
}
```
2. put the cursor on MyHomePage, then expand selection. After the second time, the whole 'MyHomePage' word is selected.
3. After the third time the selection is expanded to 'class MyHomePage {' and after the forth time, it's selecting the whole file.

The expected behavior is that after selecting the 'MyHomePage' word, the whole class will be selected, the same way it works in Android Studio for example.

**Comment by ronytesler** [comment]
Opened throug

**Comment by IllusionMH** [comment]
> Opened through VS, although reporting an issue has its own bug - the windows disappears and not shown in the alt+tab menu.

There is open issue for that.

**Comment by mjbvz** [comment]
Please file this against the Dart extension
