### ISSUE TITLE
Freezes when Chrome generates userDataDir in workspace

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14301]
- VSCode Version: 1.7 Insider
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. `mkdir test && cd test && git init`
2. Run `chrome --user-data-dir=.vscode/chrome`
3. VSCode freezes, with git activity bar icon showing count 1. When you restart VSCode it's showing count 99+ for all the files Chrome created. Guess the culprit is git watching folder but too many files are created at the same time.

Found this when I was using `"userDataDir": "${workspaceRoot}/.vscode/chrome"` in Chrome Debugger.

This doesn't seem to repro if I set `userDataDir` to `"${workspaceRoot}/chrome"`, though.

**Comment by roblourens** [comment]
I had seen this very rarely while using the Chrome extension and was never able to narrow it down. If you add the chrome folder to `.gitignore`, does that fix it?

**Comment by bpasero** [comment]
@octref fire up the profiler and find out where time is spend?

**Comment by octref** [comment]
@roblourens Adding it to .gitignore doesn't fix it.

**Comment by octref** [comment]
@bpasero 

I opened the profiler before it freezes, but the profiler ends up freezing too:

![image](https://cloud.githubusercontent.com/assets/4033249/19655994/d8e57a9a-99d2-11e6-9a64-425691c04fec.png)

**Comment by octref** [comment]
Not related to git it seems. Simpler repro:

1. Run `chrome --user-data-dir=.vscode/chrome` in your terminal (integrated or external, but pwd must be workspace's root path), for any project.

As the hang is two steps:

![hang](https://cloud.githubusercontent.com/assets/4033249/19668706/7c056d6c-9a0e-11e6-9772-567d099191dc.gif)

My guess is we are watching files in `.vscode`, but the open Chrome instance messed up our watcher.

**Comment by bpasero** [comment]
`.vscode` folder is special because we watch it for config changes, this might cause some slow down.

**Comment by bpasero** [comment]
Great catch, we ended up loading >500 JSON files are settings because we look for changes in JSON files recursively below .vscode. I pushed a fix to only support top level JSON files.
