### ISSUE TITLE
vscode window crashes unexpectedly

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#143080]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

https://github.com/golang/vscode-go/issues/2062

**Comment by weinand** [comment]
@hlbbt are you debugging a Go program?
And the database query is a function of your program?
Please translate the Chinese text of the Alert window (or reproduce the crash in an environment with english locale).
What version of VS Code are you using?

**Comment by hlbbt** [comment]
@weinand 
1. Yes，i am debugging my go program.
2. Yes, database query is the main function of my program
3. mac version:  apple m1
4. go extension version : 0.31.1
5. vscode version: 
    1.64.2
    f80445acd5a3dadef24aa209168452a3d97cc326
    arm64

![vscode-crashed](https://user-images.githubusercontent.com/52640622/154023705-34a6ed7a-94cf-43d8-bfcb-784f8722090c.png)

**Comment by weinand** [comment]
@hlbbt does this crash occur in the previous version of VS Code?
does this crash occur if you disable all but the Go extension?

**Comment by hlbbt** [comment]
@weinand 
The situation has not occurred in other versions. This is the last week when vscode pushed an update and appeared after the upgrade.

All extensions have not been changed for a long time recently.

And the same code, debugging with goland runs find, no problem.

**Comment by weinand** [comment]
@hlbbt does the crash occur in VS Code 1.64.0 ?

**Comment by hlbbt** [comment]
@weinand 
Sorry, i don't know, this program started after i upgraded vscode last week

**Comment by weinand** [comment]
@deepak1556 do you know anything about these "Code 5" crashes?
E.g. https://github.com/microsoft/vscode/issues/143101, https://github.com/microsoft/vscode/issues/141711
