### ISSUE TITLE
Show remote name for files in recently opened

### ISSUE THREAD

**Issue by swarnendubiswas** [microsoft/vscode#143096]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Visit `$HOME/.bashrc` from the local and other remote systems.
2. Invoke Ctrl+R to see recent files, and type `.bashrc`. 
3. The file pick dialog does not show the hostname, making it difficult to identify which file I should open. 

It will be a good feature to include the hostname by the side.

The three `.bashrc` files in the below figure are from three hosts.

![Screenshot from 2022-02-15 16-13-50](https://user-images.githubusercontent.com/7343807/154047105-84d454a7-5f98-4cf2-82f5-61bd875890e0.png)

**Comment by bpasero** [comment]
I had thought we show the remote label for recently opened entries, but maybe we do not for files only for folders?

**Comment by swarnendubiswas** [comment]
Yes, the remote labels do show up with folders. It does not with files.
