### ISSUE TITLE
Command decorations aren't device pixel ratio aware

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#143076]
The decoration top positions are about double the size on my monitor since `window.devicePixelRatio` is `2`. Should be able to test on a standard DPI monitor with window.zoomLevel/browser zoom:

<img width="541" alt="Screen Shot 2022-02-14 at 3 46 43 pm" src="https://user-images.githubusercontent.com/2193314/153965933-f7d511ea-3e92-4eb6-acf1-0305d76b69d0.png">

I think we need to use actual* instead of scaled* here: https://github.com/xtermjs/xterm.js/blob/4da2db8e0b5e0e4b62cabb3b8cbc9d26f0ed21cb/src/browser/services/DecorationService.ts#L114-L125

**Comment by meganrogge** [comment]
Yes I believe I was using the actual originally, but you had thought we should use scaled? 

I went with that thinking scaled would take device pixel ratio into account - if not, what is it scaled by?

**Comment by meganrogge** [comment]
Scaled takes device pixel ratio into account 

https://github.com/xtermjs/xterm.js/blob/master/src/browser/renderer/Renderer.ts#L171

**Comment by meganrogge** [comment]
So perhaps this issue should be entitled `command decorations inappropriately take device pixel ratio into account for height`?

**Comment by Tyriar** [comment]
The wording is very confusing and I'm to blame there 😅, we want "css pixels" which are before you multiply window.devicePixelRatio.

**Comment by meganrogge** [comment]
@Tyriar not sure why you reopened this, but this should be fixed now.

**Comment by rzhao271** [comment]
I'm wondering what some verification steps for this issue are?
I notice when I change the zoom level after running some commands, that the decorations become misaligned with the prompts.

**Comment by meganrogge** [comment]
to verify this, you'll need a monitor with a devicePixelRatio of 2

re zoom - zooming in and out works for me. 
![Recording 2022-02-25 at 14 30 45](https://user-images.githubusercontent.com/29464607/155798267-8733e609-f854-4582-a9eb-653ce577b928.gif)

**Comment by rzhao271** [comment]
Looks like I needed to get it to scroll first, otherwise I also get the correct behaviour above:
![Example recording](https://user-images.githubusercontent.com/7199958/155805587-cdca74c1-4571-4652-a38f-58f8a4845086.gif)
