### ISSUE TITLE
Problem saving files

### ISSUE THREAD

**Issue by sir-oliver** [microsoft/vscode#143094]
Issue Type: <b>Bug</b>

Approximately after every 15 minutes of use, none of the following works on files changed:- Save File, - Save All Files- Trigger save question by closing window. There is no error message. The Indicator in the file-tab still indicates, that the file is unsaved.

I started vscode with the --log parameter and enclosed the logged data.
After I created a file "saving-problem.tpl" i entered text and periodically saved it.
At timestamp 2022-02-15 11:08:15.251 it stopped saving in the described way.
When i tried to shut down vscode it logged these last 2 lines, then hang indefinitely.

[2022-02-15 11:16:55.879] [renderer1] [warning] [backup tracker] suspended, ignoring dirty change event file:///Users/oliver/Servers/BLACKBOX/vhosts/partnernet.oekofen.com/templates/_backup/saving-problem.tpl 
[2022-02-15 11:17:00.926] [renderer1] [warning] [lifecycle] onWillShutdown is taking a long time, pending operations: join.textFiles

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:56.651Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (0.99GB free)|
|Process Argv|--crash-reporter-id ab14bf31-80b9-4738-8a7b-589af7ba42ad|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
smarty-template-support|asw|1.9.0
material-icon-theme|PKi|4.13.0

</details>
<!-- generated by issue reporter --
[20220215T110226.zip](https://github.com/microsoft/vscode/files/8068174/20220215T110226.zip)
>

**Comment by kewp** [comment]
I'm having the same problem @sir-oliver . Have been having it for the last month. Randomly, I can't figure a pattern, I cannot save files with VS Code. I also am running macOS on arm! (M1).

I also have issues with the open dialog - nothing happens when I click File -> Open, or Command-O.

When this happens I switch to Sublime. But it seems the issue goes away when I close VS Code and re-open it (temporarily).

I am not using an external drive / ftp / etc.

BTW where is your VS code executable located? I open mine straight from the Download folder. Maybe that is the issue...

**Comment by sir-oliver** [comment]
@kewp I also just switched back to Sublime ;-( The problem came back just a few moments ago.
What MacOS version are you on? I think the issue started after updating to MacOS 12.2
My VS code executable is located in the Applications folder.

**Comment by sir-oliver** [comment]
@bpasero Just downloaded the nightly build. Will try it tomorrow.

**Comment by bpasero** [comment]
Thanks. Another thing to try is to disable extensions and figure out whether maybe an extension could have impact. Can do so by passing `--disable-extensions`.

**Comment by sir-oliver** [comment]
> Another thing to try is to disable extensions

I tried that already. The problem kept popping up.
Will be using the Insiders build without any extensions.

**Comment by kewp** [comment]
@sir-oliver yup I also recently updated to 12.2. I think the timing might coincide as well!

**Comment by bpasero** [comment]
This could very well be https://github.com/microsoft/vscode/issues/142462. Bottom line: if for any reason a single `fs.write` call never returns, our relatively new resource lock mechanism would simply refuse to write to the same file until the previous write has finished.

Still, it puzzles me how a `fs.write` call could never return. That is why I am asking about any special setup, such as network drives.

**Comment by kewp** [comment]
I'm not using any special setup. It's just my laptop, writing locally.

**Comment by sir-oliver** [comment]
I am running `code-insiders --verbose`  now and waiting for the issue to happen.

The file I am editing is located on a remote webserver. 
The server is mounted on my computer using MountainDuck.io

**Comment by bpasero** [comment]
@kewp the fact that in your case even opening a folder does not work makes me think there is something more fundamental broken in VSCode in your setup. Opening a folder and saving should be isolated operations that are not waiting on anything as far as I can tell.

@sir-oliver ok that is interesting and hints to a similar setup as https://github.com/microsoft/vscode/issues/142462. If you can easily reproduce, I would be curious if you could follow the steps in https://github.com/microsoft/vscode/issues/142462#issuecomment-1041220150 to see if it reproduces in the November release.

**Comment by sir-oliver** [comment]
Reproduced the issue with `code-insiders --verbose`

Line 2666 of console-log.txt

`[18439:0216/100918.040344:INFO:CONSOLE(605)] "%cTRACE%c [text file model] doSave(24) - exit - because busy saving ...`

[console-log.txt](https://github.com/microsoft/vscode/files/8078474/console-log.txt)
[20220216T095442.zip](https://github.com/microsoft/vscode/files/8078479/20220216T095442.zip)

Will try the same with VSCode 1.63.2 as you suggested.

**Comment by sir-oliver** [comment]
> I would expect this to reproduce in `1.63.2` as well.

Just used `1.63.2` for 4 hours without any issues.

**Comment by bpasero** [comment]
@sir-oliver maybe you can also follow along my thread here:
* https://github.com/microsoft/vscode/issues/142462#issuecomment-1041348531
* https://github.com/microsoft/vscode/issues/142462#issuecomment-1041430539
* https://github.com/microsoft/vscode/issues/142462#issuecomment-1041533431

For an insiders build with additional capabilities to diagnose further. I need to understand what changed from `1.63.x` to now better.
