### ISSUE TITLE
HTML tag in doc comment fail to be rendered as formatted text

### ISSUE THREAD

**Issue by NewbieToEverything** [microsoft/vscode#143081]
Issue Type: <b>Bug</b>

When hovering the cursor over whatever code piece, the resulting tooltip information failed to parse and format HTML tags correctly.

- `C++`
![image](https://user-images.githubusercontent.com/36309469/153995656-18c9749c-ccd5-4f52-9de6-2134473198e9.png)
- `R`
![image](https://user-images.githubusercontent.com/36309469/153995725-d445c6ff-05ca-4900-a6be-22c8c2fcca25.png)
which is supposed to be something like this
![image](https://user-images.githubusercontent.com/36309469/153995908-2b34612e-6ade-4c67-929d-19cb2cee5082.png)

---
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (9.15GB free)|
|Process Argv|--crash-reporter-id 8e88eceb-2eb2-4c74-b867-12ee0b6d85fe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
cpp-reference|Guy|0.1.7
r|Iku|2.3.8
latex-workshop|Jam|8.23.0
better-cpp-syntax|jef|1.15.13
cpptools|ms-|1.9.0
markdown-preview-enhanced|shd|0.6.1
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
vscop841:30438243
dsvsc008:30436278
vsbas813:30436447
vscscmwlcmt:30436993
helix:30438275
cppdebug:30437093

```

</details>

**Comment by pingu8007** [comment]
This issue also happened on Java project (#143942) so it's probably not a `caused-by-extension` issue
![image](https://user-images.githubusercontent.com/8936513/155666534-ce28df02-a779-4c0f-bd97-a19ef63e550a.png)
