### ISSUE TITLE
Interactive Python tab: ANSI Color Escape codes and error messages readability differs by Theme

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#143016]
Does this issue occur when all extensions are disabled?: It needs the Python extension

- VS Code Version: 1.62.2
- OS Version: Windows 8.1

Steps to Reproduce:

1. Use a Python environment with Pandas installed
2. Create the following python file
```
# %%
import pandas as pd
from io import StringIO

# force a "show more (open raw output data in a text editor)" link
print('\n'.join(['dummy text']*50))

with StringIO() as file:
  df = pd.read_csv(file)

# %%
# Try reproduce error
print("\u001b[1;32m----> 8\u001b[0m   df \u001b[38;5;241m=\u001b[39m \u001b[43mpd\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mread_csv\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfile\u001b[49m\u001b[43m)\u001b[49m\n")
print("File \u001b[1;32mpandas\\util\\_decorators.py:311\u001b[0m")

# %%
# Removed \u001b[49m
print("\u001b[1;32m----> 8\u001b[0m   df \u001b[38;5;241m=\u001b[39m \u001b[43mpd\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mread_csv\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfile\u001b[49m\u001b[43m)\n")
print("File \u001b[1;32mpandas\\util\\_decorators.py:311\u001b[0m")

# %%
# Removed 38;5;241; (color of the .)
print("\u001b[1;32m----> 8\u001b[0m   df \u001b[38;5;241m=\u001b[39m \u001b[43mpd\u001b[49m\u001b[43m.\u001b[39;49m\u001b[43mread_csv\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfile\u001b[49m\u001b[43m)\u001b[49m\n")
print("File \u001b[1;32mpandas\\util\\_decorators.py:311\u001b[0m")
```
3. Execute the first cell, you get an error message, depending on the Theme you can read the file path or it is green on green. I tried with `Light+` and `Eva Light`. In `Eva Light` the green background code is displayed as orange background.
4. By clicking on the `show more (open raw output data in a text editor)` you can get a view of what text, with ANSI Escape Color Codes, is used. The last line of the first stack trace block (`----> 8   df = pd.read_csv(file)`) ends with the text `\u001b[49m\n` (Reset Background color and line feed).
5. [Cell 2] If I use print statements to simulate this line and the next I can't reproduce the effect of unreadable file path in `Light+` theme. You might need to scroll the cell output out of view and back in view to get updated coloring on a Theme switch. The error message coloring is updated immediately.
6. [Cell 3] By removing the `\u001b[49m` at the line end reproduces the effect. But in Theme `Eve Light` the file path now has a background color but not in the error message.
7. [Cell 4] With the print statements the `.` has no background although the Escape codes tell it `\u001b[38;5;241;43m` (set foreground (38;5;241) and background (43)). If I remove the set-foreground-color the `.` gets a background.

Why does the **Reset Background Color** work in certain Themes and some not? 

Also the HTML structure is very different:

* Error message uses a deep nested tree of `span` tags with theme color variables
    `<span style="background-color:var(--vscode-terminal-ansiYellow)">`
* print statement output uses a sequence of `span` tags with hard coded style colors
    `<span class="code-background-colored" style="background-color: rgb(240, 170, 11);">`

**Comment by rebornix** [comment]
@rioj7 we have made changes to the ansi color rendering recently, can you try latest Stable and see if you can reproduce? I find it a bit hard to check what goes and what doesn't so if we can have some screenshots, it would be really helpful. Appreciate your contribution to this, thanks in advance!
