### ISSUE TITLE
Use `PULL_REQUEST_TEMPLATE.md` to create `Pr` if `PULL_REQUEST_TEMPLATE.md` exists in `.github` directory (a feature of `Github` extension).

### ISSUE THREAD

**Issue by zys864** [microsoft/vscode#143083]
Use `PULL_REQUEST_TEMPLATE.md` to create `Pr` 
if `PULL_REQUEST_TEMPLATE.md` exists in `.github` directory.

Not just using latest commit to create `Pr`.

**Comment by gjsjohnmurray** [comment]
Are you using an extension which adds the ability to create a PR? If so, please report the issue on the extension repo. The Report Issue dialog from VS Code's Help menu may be able to assist you.

/needsMoreInfo

**Comment by zys864** [comment]
> Are you using an extension which adds the ability to create a PR? If so, please report the issue on the extension repo. The Report Issue dialog from VS Code's Help menu may be able to assist you.
> 
> /needsMoreInfo

Yes, after recheck,it's a feature of `Github` extension,which seems to be a builtin `VsCode` exttension.

**Comment by joaomoreno** [comment]
> Yes, after recheck,it's a feature of `Github` extension,which seems to be a builtin `VsCode` exttension.

Can you give me the full name of the extension? Maybe a screenshot of it in the product? Or the view where you can create a PR?

**Comment by zys864** [comment]
> Can you give me the full name of the extension? Maybe a screenshot of it in the product? Or the view where you can create a PR?

The full name is exactly `github`

<img src="https://user-images.githubusercontent.com/23713554/154636384-a1920122-9233-487d-a7c7-67391d2900a1.png" alt="drawing" width="200"/>

Here is I create Pr

![Screenshot_20220218_151738](https://user-images.githubusercontent.com/23713554/154636247-48f657ee-40ba-4671-884d-c3d7b5f9917a.png)

**Comment by babakks** [comment]
@joaomoreno I'd like to fix it. Any leads are appreciated.

**Comment by joaomoreno** [comment]
Sure, this would be a great starting point: https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/extensions/github/src/pushErrorHandler.ts#L91

**Comment by joaomoreno** [comment]
**Verification:**

1. Run `Git: Clone` and clone https://github.com/joaomoreno/test-pr-templates/
2. Create a branch
3. Make a change to `README.md` and commit
4. Attempt to push/publish that branch. Code should tell you you can't push to that repo and will offer to fork the repository, accept.
5. Code should then ask you whether you'd like to create a PR, accept.

You should get shown exactly 9 PR templates to choose from.

Reference: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by babakks** [comment]
@joaomoreno I tried but after selecting a repository to fork (which then successfully creates a fork on Github) nothing is pushed without any error message. However, the developer console and the Git extension logs show this:
![Screenshot from 2022-04-27 15-26-46](https://user-images.githubusercontent.com/36728931/165503788-c0e59f04-75ed-4e66-88dc-77d6ddd36349.png)

It seems the source of the problem lies [here](https://github.com/babakks/vscode/blob/24e73f3551a59166d34d0deecbb623c24af67645/extensions/github/src/pushErrorHandler.ts#L74) when calling `addRemote`:

```ts
// Issue: what if there's already an `upstream` repo?
await repository.renameRemote(remote.name, 'upstream');

// Issue: what if there's already another `origin` repo?
await repository.addRemote('origin', ghRepository.clone_url);
```

Maybe no rename occurs when calling `renameRemote` (with no exception thrown).

**Comment by joaomoreno** [comment]
Very strange, can you easily reproduce? Delete your fork and try again.

**Comment by babakks** [comment]
Yes. I checked it several times and the results were the same.

**Comment by joyceerhl** [comment]
I did get the list of PR templates:
![image](https://user-images.githubusercontent.com/30305945/165588454-628d1096-c9b0-4bef-9dc8-cacc352b3570.png)

However, I had no way to get back to the picker after taking that screenshot (which dismissed the picker). At minimum I feel we should use `ignoreFocusOut: true`, since the Create PR functionality is not exposed as a command palette command, I am stuck.

Additionally, after I selected a template to create the PR, nothing happened.

Finally, it was unexpected that I get two popups to create a PR when the GitHub Pull Requests and Issues extension is installed: 
![image](https://user-images.githubusercontent.com/30305945/165589263-a942ee6d-33f7-44be-89a6-20eeae520b7a.png)

**Comment by babakks** [comment]
@joyceerhl 
You mean no PR was created, right? Nonetheless, I think the Github extension needs more visible error messages (e.g., via notifications).

**Comment by joyceerhl** [comment]
@babakks Yes, no PR was created (I checked on GitHub).

**Comment by joaomoreno** [comment]
Created two issues from the discoveries.

**Comment by joaomoreno** [comment]
Actually three. Creating a PR just doesn't work at all anymore: https://github.com/microsoft/vscode/issues/148326

**Comment by rzhao271** [comment]
For step 4, when I try publishing the branch, I get the error "Git: remote: Permission to joaomoreno/test-pr-templates.git denied to rzhao271." There is no option to create a fork:
![Screenshot showing modal dialog. None of the options are to create a fork](https://user-images.githubusercontent.com/7199958/166001530-d7c884e3-edcd-4fdf-9124-ab3c15712faa.PNG)

**Comment by joaomoreno** [comment]
@rzhao271 Is the Github extension enabled for you?

**Comment by rzhao271** [comment]
Just confirmed that it's enabled for me.

**Comment by joaomoreno** [comment]
Can you file a separate issue? 👌

**Comment by joyceerhl** [comment]
Verification of this issue fails since the user is no longer prompted to create a PR as found in https://github.com/microsoft/vscode/issues/143083#issuecomment-1113597175 :/

**Comment by joaomoreno** [comment]
> Verification of this issue fails since the user is no longer prompted to create a PR as found in [#143083 (comment)](https://github.com/microsoft/vscode/issues/143083#issuecomment-1113597175) :/

Wait you hit this too? I totally can't repro, that's why I asked to follow up with a separate issue. We can move this to May just for verification sake.

**Comment by joyceerhl** [comment]
Yeah I hit the same thing as @rzhao271

**Comment by stuartleeks** [comment]
I just tried testing this:

On pushing the new branch, I get
![image](https://user-images.githubusercontent.com/1824461/171147512-d131551f-dd3a-4c1c-9abc-850543880594.png)

and then:
![image](https://user-images.githubusercontent.com/1824461/171147576-2988e781-27ef-4b7a-a1d2-87ca9cc3b8c0.png)

**Comment by TylerLeonhardt** [comment]
Reopening due to @stuartleeks's comment but @joaomoreno feel free to do what you want with this

**Comment by connor4312** [comment]
I got the same issue on the latest Insiders

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/2230985/176970138-7cf0c0fc-9841-471e-8bd3-f5fd9c879707.png">

Command output:

```
> git push -u origin test-branch
ERROR: Permission to joaomoreno/test-pr-templates.git denied to connor4312.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by joaomoreno** [comment]
This is: https://github.com/microsoft/vscode/issues/148568

**Comment by joaomoreno** [comment]
Moving verification to July to account for https://github.com/microsoft/vscode/issues/148568#issuecomment-1173021392
