### ISSUE TITLE
Save All doesn't include active document

### ISSUE THREAD

**Issue by Dillie-O** [Microsoft/vscode#14308]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 16.0.0
- Extensions: Kasik96.format-indent-1.3.0, Telerik.nativescript-0.3.1, dbankier.vscode-instant-markdown-0.1.0, donjayamanne.python-0.5.0, ikappas.phpcs-0.6.1, lonefy.vscode-JS-CSS-HTML-formatter-0.2.1, makao.phpcsfixer-0.0.1, mohsen1.prettify-json-0.0.3, ms-vscode.PowerShell-0.7.2, wwwalkerrun.nativescript-ng2-snippets-1.2.0

Steps to Reproduce:

1. Open up multiple files in the editor and make changes to all of them, but do not save them.
2. Note how all of the files have the dot icon indicating.
3. Select one of the files that are open to make it the "active" file.
4. From the menu, select "Save All"

Expected result: The circle icon is removed from all files since they have all been saved.

Actual result: The circle icon is removed from all files except the active file. It also appears that some code that was stored in the clipboard was automatically pasted in.

Notes: 

As an added means of verification, I've been using the NativeScript livesync feature and noted that all of the changes appear in the synchronized app simulator, except for the active file.

After performing an undo action on the active file, to remove the odd content pasted into the status of the file goes to the "unchanged" status. It could be that the file is actually saving, but then a paste command is erroneously being executed by the app.

I hope this helps. Keep up the great work. I love VS Code!

![vscode_openfiles](https://cloud.githubusercontent.com/assets/991466/19655250/3280db24-99d0-11e6-8c68-1dde21b722f3.png)
![vscode_savedfiles](https://cloud.githubusercontent.com/assets/991466/19655251/329d9624-99d0-11e6-82d9-2cf1b1e5d9a8.png)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Dillie-O** [comment]
The `--disable-extensions` argument keeps coming back with an "unrecognized option" error. Does it matter that my main shell is ZSH or not?

**Comment by Dillie-O** [comment]
I went ahead and deleted all of my extensions and was not able to replicate the issue. I'll go ahead and close this bug and re-open in the appropriate extensions section when I track down which one is the culprit.

Thanks!

**Comment by bpasero** [comment]
@Dillie-O weird to hear you cannot use --disable-extensions, it should work in any terminal.

**Comment by Dillie-O** [comment]
Yeah, works in Win10 but not macOS Sierra and I verified both versions were up to date

Sent with Outlook<https://aka.ms/qtex0l> for iOS




On Mon, Oct 24, 2016 at 9:13 PM -0700, "Benjamin Pasero" <notifications@github.com<mailto:notifications@github.com>> wrote:


@Dillie-O<https://github.com/Dillie-O> weird to hear you cannot use --disable-extensions, it should work in any terminal.

-

**Comment by bpasero** [comment]
@Dillie-O please report this as a new issue.

**Comment by Dillie-O** [comment]
Done. See issue #14545
