### ISSUE TITLE
[A11y] accessibilityInformation.role API for TreeItem not work 

### ISSUE THREAD

**Issue by HuihuiWu-Microsoft** [microsoft/vscode#143085]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.1
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. In my extension,  set the accessibility information to {label: "this is a test message", role: "treeitem"} through TreeItem.accessibilityInformation API
2. Start VSC and screen reader(NVDA), the accessibilityInformation label("this is a test message") is read but role("treeitem") is not.

**Comment by alexr00** [comment]
I think this depends on your screen reader. The `role` is not guaranteed to be read, it is for giving the screen reader more information about the element so it can decide how to interact with it. I have confirmed that the `role` is set correctly.

**Comment by HuihuiWu-Microsoft** [comment]
> I think this depends on your screen reader. The `role` is not guaranteed to be read, it is for giving the screen reader more information about the element so it can decide how to interact with it. I have confirmed that the `role` is set correctly. For example, if you set the role to `button`, then the word "button" will be read.

Hi @alexr00 , thanks for your response. It does work for 'button' role. But when I set role to 'treeitem', it will read 'Not selected, one of <number>, level 1" instead of 'treeitem' role. Is that native behavior of NVDA screen reader or VSCode behavior? Accessibility team raised an issue to us that the role is not read for these tree items so we'd like to figure out the expected behavior.

**Comment by alexr00** [comment]
@HuihuiWu-Microsoft whether the role is read is dependent on the screen reader, so you would need to ask the folks who make NVDA what is expected here. Or, maybe @isidorn would know.

**Comment by isidorn** [comment]
It is as @alexr00 says. Screen reader can decide what to read for the `treeitem`.
I think the screen reader is correct here. No point in reading `treeitem` it would be spam to the user
So just talk to you accessibility team @HuihuiWu-Microsoft
