### ISSUE TITLE
Linux CI: tons of crash dumps created

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#143000]
Not sure if related to https://github.com/microsoft/vscode/issues/142999, but I see lots of crash dumps getting attached to Linux CI runs, for example:

[Archive.zip](https://github.com/microsoft/vscode/files/8059865/Archive.zip)

From https://dev.azure.com/monacotools/Monaco/_build/results?buildId=155814&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/142572

Refs https://github.com/microsoft/vscode/issues/142572#issuecomment-1040431433
