### ISSUE TITLE
Source Control Tab - Git message hidding squash/discard/stage all buttons

### ISSUE THREAD

**Issue by 1bberto** [microsoft/vscode#143036]
Issue Type: <b>Bug</b>

When typing the commit message, if it is too long, an alert message is displayed on top of the actions buttons.
I suggest to change this in a way where we could see the warning message and the same time have access to the actions.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (5.00GB free)|
|Process Argv|--folder-uri file:///c%3A/Projects/SenseiOS --crash-reporter-id 0ec6cdf6-03d9-4f4f-bac9-0e019fff5276|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.8.2
lit-html|bie|1.11.1
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
gitlens|eam|11.7.0
vscode-html-css|ecm|1.11.0
prettier-vscode|esb|9.2.0
vscode-jest-runner|fir|0.4.47
vscode-test-explorer|hbe|2.21.1
vscode-docker|ms-|1.19.0
csharp|ms-|1.24.0
remote-containers|ms-|0.217.4
test-adapter-converter|ms-|0.1.5
language-liquid|nei|0.1.1
angular-karma-test-explorer|raa|1.2.8
vscode-yaml|red|1.4.0
sonarlint-vscode|Son|3.3.0
code-template-tool|yua|0.6.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
vsbas813:30436447
vscscmwlcmt:30436993

```

</details>

**Comment by 1bberto** [comment]
long line commit message

![image](https://user-images.githubusercontent.com/3129978/153919951-bda105ef-4d75-4a23-911a-0169229a40a7.png)

small line commit message

![image](https://user-images.githubusercontent.com/3129978/153920042-16f7bdf1-c731-4b62-8b07-e25659a17eca.png)

**Comment by 1bberto** [comment]
@lszomoru, any update on this issue ?

**Comment by lszomoru** [comment]
Adding @misolori, to get his thoughts on this.

**Comment by misolori** [comment]
Our current pattern for input messages does not allow this and would require us to create a new pattern. This also applies to all areas that use input validation and not just SCM (search, settings, quick pick, etc.)

**Comment by gjsjohnmurray** [comment]
As a pragmatic solution how about adding a close-button on the right-hand end of the message?
