### ISSUE TITLE
Dependancies for internal extensions

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#14307]
- VSCode Version: 1.7
- OS Version: All

Dependancies view does not work well with internal dependancies.  This is actually important as the dependent extension is overridden but does provide interesting context e.g. language ID for activation in the case of `go`.

Steps to Reproduce:

1.  Install Go extension
2. Click dependancies
3. Go depends on `vscode.go` (shipped in box)
4. An error is displayed as the view can't resolve it

**Comment by ramya-rao-a** [comment]
@sandy081 Just to confirm, your fix was to not show the built-in extensions in the dependency list correct?

**Comment by sandy081** [comment]
@ramya-rao-a No. Fix is also to show the built in extensions if they are mentioned as dependencies. Looks like Go extension has removed `vscode.go` from extensionDependencies list. You can verify adding the built-in extension to any other extensions and check the dependencies tab.
