### ISSUE TITLE
ability to lookup symbols definitions using static analysis & cache the result for future use

### ISSUE THREAD

**Issue by noureddine-taleb** [microsoft/vscode#143090]
1. symbol lookup in vscode is an expansive operation, especially in large projects, I think it is a good idea to be able to save the lookup result for future use instead of computing it every time. also it might be even cooler if it's able to like "compile" the whole project and build a symbol lookup table once and then cache it for faster navigation later (it should be saved to disk, to persist even after reboot). I think this feature is especially useful for developers reading source code of large projects, and want to have quick navigation around, and find their way out.

2. the current symbol lookup engine is not perfect either, it is useful only for simple obvious cases, and sometimes is not able to detect some symbols (I use it in linux kernel, and it doesn't detect most symbols, due to heavy use of macros), and if it works it is somewhat slow. so most of the time I opt out to heuristically greping the entire source tree, and trying different combination (it might be a function or a macro, or it's declared in different format ...), I think some kind of static analyzer would solve the issue, it should just blindly scan the project looking for different combination of symbol definitions ignoring all runtime/compiletime constraints (like #ifdef's in c).

I think the above features should be available in the ui, so that the user should explicitly request them (means it shouldn't be done automatically for performance reasons). something like a tab that contains the list of available caches for a project. and maybe another tab just like the existing search tab, but it takes a symbol name and looks for possible definitions.

**Comment by dbaeumer** [comment]
This is usually something that can either be done using a language server (which has symbol look up requests as well) or if you wan to have a static dump upfront LSIF is a good option. But both require an implementation form a language service / compiler.

**Comment by jrieken** [comment]
I like the ideas and it is something that should be done, tho it is for extensions and/or language services do implement. VS Code has no understanding of all of this and only provides UX and an API to ask for symbols, the rest in the realm of extensions.
