### ISSUE TITLE
Missing keyboard shortcut features from Atom

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#14316]
I created an [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.atom-keybindings) to port Atom keybindings to VS Code keybindings. I made a list of all the keybindings that were missing analogous commands in VS Code. 

Below is the list roughly ordered by importance. Please comment if I missed one. If an extension exists with the functionality, I added it in the far right column. 

| Windows, Linux | Mac | Description | Issue | Extension |
| --- | --- | --- | --- | --- |
| ctrl+j, ctrl+j | cmd+j | Join current line and next line | https://github.com/Microsoft/vscode/issues/1759 | [Join Lines](https://marketplace.visualstudio.com/items?itemName=wmaurer.join-lines) |
| ctrl+shift+v | cmd+shift+v | Paste and indent | https://github.com/Microsoft/vscode/issues/6392 | [Paste and Indent](https://marketplace.visualstudio.com/items?itemName=Rubymaniac.vscode-paste-and-indent) |
| ctrl+t | ctrl+t | Transpose | https://github.com/Microsoft/vscode/issues/8574 | [transpose](*https://marketplace.visualstudio.com/items?itemName=v4run.transpose) |
| ctrl++ | cmd++ and cmd+= | Increase Font Size | https://github.com/Microsoft/vscode/issues/14031 | [FontSize Shortcuts](https://marketplace.visualstudio.com/items?itemName=peterjuras.fontsize-shortcuts) |
| ctrl+- | cmd+- | Decrease Font Size | https://github.com/Microsoft/vscode/issues/14031 | [FontSize Shortcuts](https://marketplace.visualstudio.com/items?itemName=peterjuras.fontsize-shortcuts) |
| <kbd>ctrl</kbd>+<kbd>k</kbd> <kbd>ctrl</kbd>+<kbd>u</kbd> | <kbd>cmd</kbd>+<kbd>k</kbd> <kbd>cmd</kbd>+<kbd>u</kbd> | Upper case | https://github.com/Microsoft/vscode/issues/14096 | [change case](https://marketplace.visualstudio.com/items?itemName=wmaurer.change-case) |
| <kbd>ctrl</kbd>+<kbd>k</kbd> <kbd>ctrl</kbd>+<kbd>l</kbd> | <kbd>cmd</kbd>+<kbd>k</kbd> <kbd>cmd</kbd>+<kbd>l</kbd> | Lower case | https://github.com/Microsoft/vscode/issues/14096 | [change case](https://marketplace.visualstudio.com/items?itemName=wmaurer.change-case) |
| ctrl+k ctrl+6 | cmd+k cmd+6 | Fold level 6 | https://github.com/Microsoft/vscode/issues/14106 | None |
| ctrl+k ctrl+7 | cmd+k cmd+7 | Fold level 7 | https://github.com/Microsoft/vscode/issues/14106 | None |
| ctrl+k ctrl+8 | cmd+k cmd+8 | Fold level 8 | https://github.com/Microsoft/vscode/issues/14106 | None |
| ctrl+k ctrl+9 | cmd+k cmd+9 | Fold level 9 | https://github.com/Microsoft/vscode/issues/14106 | None |

**Comment by alexandrudima** [comment]
Thank you, I really appreciate the tables you've come up with

**Comment by Tyriar** [comment]
| Windows, Linux | Mac | Description | Issue | Extension | 
|---------------- | ---- | ------------ | ----- | --------- |
| alt+left | ctrl+alt+left | Go to previous word boundary | None | |
| alt+right | ctrl+alt+right | Go to next word boundary | None | |

**Comment by alvinsight** [comment]
Hey guys, what's the status of this?
Is it still in the roadmap ?
Thanks,
Alvin

**Comment by Tyriar** [comment]
@waderyan can we close this off in favor of https://github.com/waderyan/vscode-atom-keybindings/issues?

**Comment by alvinsight** [comment]
Hi,
I don't think so, I believe @waderyan created his extension *as a bandaid* while we're waiting for these features to exist natively in VSCode, but please correct me if I'm wrong :)
Thanks

**Comment by waderyan** [comment]
@Tyriar unfortunately no. The keymap covers keyboard shortcut commands that do exist. That being said, many of these now exist in the product. I will update the issue.

**Comment by Tyriar** [comment]
@waderyan since each feature is tracked in its own issue is this worth keeping open?

**Comment by waderyan** [comment]
yep that's a good point. I was using this issue as a reference for all the issues together, but I can still do that with the issue closed.
