### ISSUE TITLE
Overwriting language definition from extension is not reliable

### ISSUE THREAD

**Issue by jlelong** [microsoft/vscode#143187]
I am one of the maintainers of [LaTeX-Workshop](https://github.com/James-Yu/LaTeX-Workshop) and [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics), which is used by VS Code to provide built-in syntax support for LaTeX.

Related to James-Yu/LaTeX-Workshop#3083, see in particular [this comment](https://github.com/James-Yu/LaTeX-Workshop/issues/3083#issuecomment-1041143822)

Ensure `"editor.quickSuggestions"` is set to its default value. Consider the LaTeX file 

```latex
\documentclass{article}

\begin{document}
        test
\end{document}
```

Open this file in VS Code with LaTeX-Workshop activated and type `\\`. Observe

![poo](https://user-images.githubusercontent.com/10665499/154085128-6c42ba9c-e674-4f71-8cb2-da7cb65dbcf4.png)

In particular, observe the leading `\` in blue whereas LaTeX-Workshop excludes `\` from word characters

https://github.com/James-Yu/LaTeX-Workshop/blob/05d613575e5500ff6a6fbc2f7d5c8f01b0c634fa/syntax/latex-language-configuration.json#L114-L115

You may need to reload VS Code a couple of times to observe this behaviour. A reliable way to reproduce the issue is to

- deactivate LaTeX-Workshop
- reload VS Code with the .tex file opened (note that the file is properly highlighted)
- activate LaTeX-Workshop
- type `\\` and see the completion popping up

If you remove `extensions/latex` from the VS Code application content, the issue will not show up anymore. 

Note that the `\` is considered as a word character by `vscode-latex-basics`
https://github.com/Microsoft/vscode/blob/main/extensions/latex/latex-language-configuration.json#L110 

My understanding is that the built-in LaTeX language definition is not properly overwritten by LaTeX-Workshop. @aeschli wrote at https://github.com/James-Yu/LaTeX-Workshop/issues/2731#issuecomment-851959132

> For backward compatibility, your extension can continue to define language id, configurations and grammar and your settings will win over the ones from the basic language extension

This issue appears with both the stable and insiders versions.

Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0

Version: 1.65.0-insider (Universal)
Commit: 50089c3f92c17584a4aca179f51f220b56c22020
Date: 2022-02-14T05:17:15.582Z
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Darwin x64 21.3.0

**Comment by aeschli** [comment]
I can reproduce the issue. Another way to see the current word pattern is to set the cursor in the middle of `\begin` and look at the highlighting.
