### ISSUE TITLE
request: support preserveFocus for webview

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#14311]
Feature request: support `preserveFocus` on the `vscode.previewHtml` command. When true, the focus should not change to the preview. This parameter is already supported by `window.showTextDocument` and `OutputChannel.show`.

**Comment by chongchai** [comment]
Is any plan to add this feature to the release version? @jrieken

**Comment by Huachao** [comment]
@weinand @jrieken any updates on this issue?

**Comment by jrieken** [comment]
Yes, we will ship a proper webview API for April. That also means we will not invest further in the preview-command

**Comment by jrieken** [comment]
Assigning to @mjbvz - unsure if the current api already supports this

**Comment by Huachao** [comment]
@jrieken good job, thanks. Waiting for the April Release.
