### ISSUE TITLE
Enum Auto-Suggestion from Enum Definition, for Variable or Member on Assignment (=) [ Language : C ]

### ISSUE THREAD

**Issue by JWSlogisza** [microsoft/vscode#143128]
In my context, I have structures with members defined as enums. 

Current functionality has no auto-suggestion when trying to assign a value to one of these members. 
![image](https://user-images.githubusercontent.com/99756250/154122658-ce01e77c-a432-4a08-ad93-c259cfae9a43.png)

Preferably, the auto-suggestion would suggest type defined values before any text is entered (Picture below is showing example suggestions, disregard typed characters).
![image](https://user-images.githubusercontent.com/99756250/154122711-d7d31a5a-0576-4dc8-8511-f0f871dd1880.png)

Without this functionality, users need to jump to enum definitions if unfamiliar with the codebase or adhere to a stricter naming convention for an archaic form of auto-completion.

**Comment by JWSlogisza** [comment]
@jrieken How can I help clarify the issue?

**Comment by jrieken** [comment]
Did you read the issue reporting guidelines that are linked above? Is there anything from the guideline that you need help or clarification with?

**Comment by JWSlogisza** [comment]
I apologize, I skimmed it but the post requirements didn't jump out at me. I'll further clarify when I have the time, thanks for the quick response.
