### ISSUE TITLE
Leakage caused by `Stacktrace`

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#143111]
I noticed this while investigating https://github.com/microsoft/vscode/issues/142933

* `curl https://raw.githubusercontent.com/zemirco/sf-city-lots-json/master/citylots.json >citylots.json`
* open the file
* close all editors
* take a heap snapshot
* observe a 300KB minimap `Uint8ClampedArray` that is being referenced via an `Error` stored in a `Stacktrace` in a `Listener`.
* [Heap-20220215T162359.heapsnapshot.zip](https://github.com/microsoft/vscode/files/8072359/Heap-20220215T162359.heapsnapshot.zip)

> <img width="1027" alt="image" src="https://user-images.githubusercontent.com/5047891/154093116-010773a4-c116-40d4-b2f6-994ea195cc1a.png">

**Comment by jrieken** [comment]
We do this since a couple of years, what has changed is the lazy creation of the actual string (by holding a reference to the error). We can turn that back to be a string, esp. since the stacktrace value is used just after its creation. @alexdima I see how this consumes memory (more than before) but I fail to see leak here. Can you explain?

**Comment by alexdima** [comment]
Using the original steps, there is now a reference to an array buffer, kept alive by a minimap instance, kept alive by an editor view instance, which is kept alive by something called `StackFrameInfo`, which I guess is an internal v8 class. All these objects are logically disposed, the original steps involve closing the editor. 

Of note is that the editor core does not have any listeners to `IKeybindingService.onDidUpdateKeybindings` so I cannot explain why the `_listeners` list of `IKeybindingService._onDidUpdateKeybindings` would end up referencing an editor view instance.

Do you think that this leak always existed, even when reading `Error.stack` eagerly?

**Comment by jrieken** [comment]
Went back to eagerly getting the value of a stacktrace via `new Error().stack`. Still a mystery why the `StackFrameInfo` hold onto "random" thing tho.
