### ISSUE TITLE
JSX attribute completion inserting single quotes instead of double quotes

### ISSUE THREAD

**Issue by nifte** [microsoft/vscode#143164]
Issue Type: <b>Bug</b>

For some reason the JSX attribute completion setting is now tied to the file's auto-detected quote setting, meaning if you use single quotes in your imports, JSX attribute completion will insert single quotes instead of double quotes.

Example:
```javascript
import React from 'react'

export default () => <div className='|'></div>
```
```javascript
import React from "react"

export default () => <div className="|"></div>
```

Expected behavior is to always use double quotes (`=""`) for string attributes, according to the default "Auto" setting.

This bug is currently happening in both .tsx and .jsx files, and I believe it started happening in version 1.62

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:56.651Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.30GB free)|
|Process Argv|--crash-reporter-id ea8be2de-fee4-482c-9efd-2d935be862a5|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvid1:30438799
helixcf:30438807

```

</details>

**Comment by mjbvz** [comment]
The type of quote used is controlled by `javascript.preferences.quoteStyle` and matches the description of the setting:

> Preferred quote style to use for quick fixes: single quotes, double quotes, or auto infer quote type from existing imports.

The example listed under `javascript.preferences.jsxAttributeCompletionStyle` uses double quotes as an example of what will be inserted. I'll make it more clear that it is not the literal text that will be aded
