### ISSUE TITLE
How to edit notebook output line height

### ISSUE THREAD

**Issue by fry404006308** [microsoft/vscode#143199]
How to edit notebook output line-height，as shown below. 

I spent much time to find a way, but I failed.

![7867](https://user-images.githubusercontent.com/33335064/154277529-9a72fd81-f920-470f-8da5-80691ff9d69c.png)

**Comment by rebornix** [comment]
Thanks bot, it doesn't need 20 upvotes, it's a valid feature request we should look into.

**Comment by amunger** [comment]
fixed as part of #123149

**Comment by fry404006308** [comment]
您好，我是范仁义，您的邮件我已经收到，我会尽快处理，谢谢。
