### ISSUE TITLE
Drag and drop elements in the outline to rearrange code

### ISSUE THREAD

**Issue by kevduc** [microsoft/vscode#143192]
It would be very practical to be able to drag and drop let's say a function in the outline panel to change its position in the file.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"outline"

**Comment by kevduc** [comment]
Thanks @jrieken! I had a look at the issues with the "outline" tag and found this one: https://github.com/microsoft/vscode/issues/131948
It's also about moving items in the outline but specifically for notebook cells.

I was thinking more about any code file, e.g. moving JavaScript functions/variable declarations around directly from the outline (instead of having to manually select all the corresponding lines of code in the editor, copy, scroll to another spot, paste)

But if that other issue also covers that then it's all good!

**Comment by phil294** [comment]
This is the one: #68353
It got closed as out of scope.

**Comment by jrieken** [comment]
You can still vote on closed issues
