### ISSUE TITLE
Font choice

### ISSUE THREAD

**Issue by dshuman52** [microsoft/vscode#143156]
[Issue](url) Type: <b>Feature Request</b>

A monospaced font with a slashed zero would be nice especially one that does not look like there are spaces after i's and n's (Monaco).  I also like the exaggerated parens,  braces and brackets, too.  I prefer small font sizes and with most fonts differentiating between the above 3 is not easy.  one, lowercase L and upper case I and vertical bar | can also be difficult to tell apart.  highlighting paired quotes double and single would also be nice.  I found the highlighting matching brackets, (parens and braces too?)

Font ligatures are nice too.  However secondary to the above considerations.

Lastly a suggestion select mechanism that allows a tab to be ONLY a tab also not using the enter key would be nice.

Thanks.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux arm64 5.4.0-1050-raspi

**Comment by IllusionMH** [comment]
Not sure why this is request for editor itself? VS Code doesn't ship with fonts bundled (even with Cascadia Code).
You can find a font you are looking for, install it and set it to `editor.fontFamily`, moreover ligatures are supported (look for `editor.fontLigatures` setting).


Not sure why request for 
> Lastly a suggestion select mechanism that allows a tab to be ONLY a tab also not using the enter key would be nice.

is in same issue as font related request. It's bad practice to merge unrelated requests as it makes tracking of them, impossible. Moreover - you should look for duplicates of this one.

**Comment by IllusionMH** [comment]
/questions

As said above - bring your own font.

`editor.acceptSuggestionOnEnter` already exists, so you should open separate issue if there is something wrong with it.

**Comment by dshuman52** [comment]
I tried to disable auto closure of parenthesis and quotes -- only partially effective, they still occasionally happen when I am typing without looking at the monitor one example had ''"test"''  that is two single quotes double quotes around the text and a pair of single quotes after the trailing double quote and automatic quote closure was DISABLED.  Yes it is intermittent and I cannot tell you how to reproduce it.  PS I was trying to replace the double quotes at the time and typed a single quote on each side.

I have disabled suggestions from appearing.  The only thing that can be disabled from my search of the settings  what ever that  is having the enter key automatically approve an arbitrary suggestion.  THERE IS NO WAY I have found to disable the tab key from auto accepting a suggestion while one is typing a line and not necessarily aware there is a suggestion on the screen.   What I call a bad practice is to take a logical action of pressing the tab key when entering text to be anything other than the desire to place a tab at the current cursor position into the text.  Most touch typists are not watching the screen for suggestions that "automatically" get accepted when one wanted a tab to appear in the text.
In terns there are  far too many setting options many of unknown importance or purpose;  including many tied to some feature called intellisense that I tried to globally disable and could not find the option  meaning I disabled about 30 automatic action settings because one could not find the way to totally disable intellisense.
    On Wednesday, February 16, 2022, 05:57:40 AM EST, Alexandru Dima ***@***.***> wrote:  
 
 


Closed #143156.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alexdima** [comment]
@dshuman52 VS Code has options for almost anything in order to accommodate everyone. From your description, I think you might find it better if you disable some more things via options:
* `"editor.quickSuggestions": { "other": false, "comments": false, "strings": false }`
* `"editor.autoSurround": "never"`
* `"editor.autoClosingQuotes": "never"`
* `"editor.autoClosingBrackets": "never"`
You can also customize each and every keybinding of VS Code:
* `F1 > Preferences: Open Keyboard Shortcuts (JSON)`
* Add `{ "key": "tab", "command": "-acceptSelectedSuggestion" }`

**Comment by dshuman52** [comment]
Finally the setting I may be looking for 

Add { "key": "tab", "command": "-acceptSelectedSuggestion" }
Does this mean if I turn suggestions back on that only the mouse will/can accept them == meaning I can still touch type and be assured no suggestions will be accepted? And still have suggestions available if i stop typing and look and choose to use a mouse?  If so this would be a GOOD DEFAULT SETTING.  NOTE also I already had the following turned off.  I believe the first was the default setting the second I believe was NOT.

    "editor.acceptSuggestionOnCommitCharacter": false,
    "editor.acceptSuggestionOnEnter": "off",

By the way these were the "default fonts" VScode installed with.             Consolas, 'Courier New', monospace
as stated before no slashed zero, l, 1, I and | not clearly distinguishable and (, {, [ also not clearly distinguishable particularly ( and {.  Monaco fixes many of those issues the problem being I believe kerning -- one would expect a monospaced font not to have odd spacing between letters bordering on half spaces to my eye.  Courier New seems to fix that with the serifs on the font making all characters roughly equal in width.  A cross between Courier New and Monaco would be nice.  I tried a couple of the new fonts with ligatures in them, the ligatures were nice but I would prefer getting clear basic character differences to the fanciness of a ligature.

this one I was missing "editor.quickSuggestions": { "other": false, "comments": false, "strings": false }

what I had.
 {
    "workbench.colorTheme": "Default Dark+",
    "editor.fontSize": 12,
    "editor.fontFamily": "Monaco, Consolas, 'Courier New', monospace",
    "editor.renderWhitespace": "all",
    "editor.wordWrap": "on",
    "editor.autoClosingBrackets": "never",
    "editor.autoClosingDelete": "never",
    "editor.autoClosingOvertype": "never",
    "editor.autoClosingQuotes": "never",
    "editor.autoSurround": "never",
    "editor.bracketPairColorization.enabled": true,
    "editor.copyWithSyntaxHighlighting": false,
    "editor.detectIndentation": false,
    "editor.dragAndDrop": false,
    "editor.emptySelectionClipboard": false,
    "editor.inlayHints.enabled": false,
    "editor.insertSpaces": false,
    "remote.SSH.remotePlatform": {
        XXXXXXXXXXXXXXX  (removed by me)
    },
    "editor.minimap.enabled": false,
    "editor.acceptSuggestionOnCommitCharacter": false,
    "editor.acceptSuggestionOnEnter": "off",
    "editor.inlineSuggest.enabled": false,
    "editor.suggest.showClasses": false,
    "editor.suggest.showColors": false,
    "editor.suggest.showConstants": false,
    "editor.suggest.showConstructors": false,
    "editor.suggest.showCustomcolors": false,
    "editor.suggest.showDeprecated": false,
    "editor.suggest.showEnums": false,
    "editor.suggest.showEnumMembers": false,
    "editor.suggest.showFields": false,
    "editor.suggest.showEvents": false,
    "editor.suggest.showFiles": false,
    "editor.suggest.showFolders": false,
    "editor.suggest.showStatusBar": true,
    "editor.suggest.showSnippets": false,
    "editor.suggest.showReferences": false,
    "editor.suggest.showProperties": false,
    "editor.suggest.showOperators": false,
    "editor.suggest.showModules": false,
    "editor.suggest.showMethods": false,
    "editor.suggest.showIssues": false,
    "editor.suggest.showKeywords": false,
    "editor.suggest.showInterfaces": false,
    "editor.suggest.showInlineDetails": false,
    "editor.suggest.showIcons": false,
    "editor.suggest.showFunctions": false,
    "shellcheck.customArgs": [
        "-x"
    ]
}
   On Tuesday, February 22, 2022, 04:35:55 PM EST, Alexandru Dima ***@***.***> wrote:  
 
 


@dshuman52 VS Code has options for almost anything in order to accommodate everyone. From your description, I think you might find it better if you disable some more things via options:
   
   - "editor.quickSuggestions": { "other": false, "comments": false, "strings": false }
   - "editor.autoSurround": "never"
   - "editor.autoClosingQuotes": "never"
   - "editor.autoClosingBrackets": "never"   
You can also customize each and every keybinding of VS Code:
   - F1 > Preferences: Open Keyboard Shortcuts (JSON)
   - Add { "key": "tab", "command": "-acceptSelectedSuggestion" }

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
