### ISSUE TITLE
Test: ESLint autofix on save

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#14319]
Tests ESLint auto fix on save.

- [ ] Any platform @rebornix 

Complexity - 2

vscode-eslint is now supporting autofix on save:
- The setting is enabled using `eslint.autoFixOnSave`. Notice that the setting is only honored when `autoSave` is not set to `after delay`.

### Set up
- install the latest version of the vscode-eslint extension (version 1.0.8)
- create a new workspace with eslint install (npm install eslint). Also create a .eslintrc file
```json
{
    "env": {
        "commonjs": true,
        "es6": true,
        "node": true
    },
    "rules": {
        "no-const-assign": "warn",
        "no-this-before-super": "warn",
        "no-undef": "warn",
        "no-unreachable": "warn",
        "no-unused-vars": "warn",
        "constructor-super": "warn",
        "valid-typeof": "warn",
        "no-extra-semi": "warn"
    }
}
```
- file issues here: https://github.com/Microsoft/vscode-eslint

### Test
- ensure that you have auto save after delay disabled
- ensure that you have format on save disabled.
- create a JS file and add an extra semicolon. It should be removed on save. 
- test other ESLint warnings that offer a auto fix. See rules with a wrench here: http://eslint.org/docs/rules/. Please note that some rules need an n pass fix approach which is currently not implemented yet. So only test one rule at a time.

**Comment by rebornix** [comment]
Run into two issues https://github.com/Microsoft/vscode-eslint/issues/158 and https://github.com/Microsoft/vscode-eslint/issues/161 , the first one is filed by community.
