### ISSUE TITLE
.Net Core Run And Debug Variables breakpoint

### ISSUE THREAD

**Issue by luismendes070** [microsoft/vscode#143134]
Issue Type: <b>Bug</b>

.Net Core Run And Debug Variables breakpoint

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  J1800  @ 2.41GHz (2 x 2417)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.49GB free)|
|Process Argv|C:\\Users\\Luis\\Documents\\GitHub\\curso-colecoes-dio --crash-reporter-id d129a162-225f-4e00-8ef3-621459994f59|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.10.7
vscode-labs|aut|1.3.3
aws-amplify-vscode|aws|0.0.4
armview|ben|0.4.6
comet-debug|Cla|0.3.15
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.2.0
vscode-firefox-debug|fir|2.9.6
vscode-pull-request-github|Git|0.36.1
terraform|has|2.19.0
Ionide-fsharp|Ion|5.10.2
snowstorm|Jan|2.3.2
csharpextensions|jch|1.3.1
minecraft-debugger|moj|0.1.1
mongodb-vscode|mon|0.8.0
vscode-android-webview-debug|mpo|1.2.1
azure-pipelines|ms-|1.195.0
vscode-azureappservice|ms-|0.23.0
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.13.0
vscode-azureterraform|ms-|0.3.2
vscode-azurevirtualmachines|ms-|0.5.0
vscode-bicep|ms-|0.4.1272
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.19.0
csharp|ms-|1.24.0
dotnet-interactive-vscode|ms-|1.0.3103010
vscode-dotnet-pack|ms-|1.0.8
vscode-dotnet-runtime|ms-|1.5.0
vscode-kubernetes-tools|ms-|1.3.6
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.1
jupyter|ms-|2022.1.1201831736
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.4
azure-account|ms-|0.10.0
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.2.1
vscode-typescript-next|ms-|4.6.20220211
azurerm-vscode-tools|msa|0.15.5
vscode-yaml|red|1.4.0
LiveServer|rit|5.7.4
salesforcedx-vscode-core|sal|53.16.0
slacksnippets|Sla|0.0.4
vscode-icons|vsc|11.10.0
dingo-vscode|Wal|1.0.9
quokka-vscode|Wal|1.0.447
wallaby-vscode|Wal|1.0.326
browserslist|web|1.1.0
php-debug|xde|1.23.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
vsbas813:30436447
vscscmwlcmc:30438657
helixcf:30438276

```

</details>

**Comment by weinand** [comment]
@luismendes070 what's the problem?
