### ISSUE TITLE
VS Code does not recognize the .git folder and is not enabling source control

### ISSUE THREAD

**Issue by JGabrielNeto** [microsoft/vscode#143127]
Issue Type: <b>Bug</b>

1) Cloned a brand new repository from github.
2) Created and Next-app with "yarn create next-app --typescript"
3) cd into the folder, and opened vs code with "code ."
4) tried to push code back to github via source control but as soon as i opened the tab i got a  message "The folder currently open doesn't have a git repository.".
5) I pushed the code without any problems via terminal and i double checked if the .git folder with "ls -a" and it is there. Here's the output:

jgabriel@jgabriel-Aspire-A315:~/Documents/challenges/sunnyside-landing-page$ ls -a
.   .eslintrc.json  .gitignore  next.config.js  node_modules  pages   README.md  tsconfig.json
..  .git            LICENSE     next-env.d.ts   package.json  public  styles     yarn.lock

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
OS version: Linux x64 5.13.0-28-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz (4 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|19.42GB (12.72GB free)|
|Process Argv|. --crash-reporter-id f6b17abb-4cf5-4a4b-86b5-dfbf5e7f7197|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|budgie-desktop|
|XDG_CURRENT_DESKTOP|Budgie:GNOME|
|XDG_SESSION_DESKTOP|budgie-desktop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-modules|cli|0.4.1
vscode-eslint|dba|2.2.2
EditorConfig|Edi|0.16.4
vscode-styled-components|mf|0.2.2
dotenv|mik|1.0.1
vscode-docker|ms-|1.19.0
vscode-kubernetes-tools|ms-|1.3.6
remote-containers|ms-|0.217.4
cpptools|ms-|1.8.4
color-highlight|nau|2.5.0
vscode-yaml|red|1.4.0
LiveServer|rit|5.7.4
sass-indented|syl|1.8.19
vscode-icons|vsc|11.10.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
vsbas813:30436447
vscscmwlcmc:30438657
helixcf:30438276
cppdebug:30437093

```

</details>

**Comment by PierreJeanjacquot** [comment]
same here

**Comment by lszomoru** [comment]
@JGabrielNeto, @PierreJeanjacquot are you able to reproduce the problem when you start `code` with the `--disable-extensions` option? I am asking as we have recently found an issue in the extension activation code that could result in the `vscode.git` extension not getting activated.

**Comment by PierreJeanjacquot** [comment]
Hi @lszomoru 
I do not reproduce the issue with v1.65.1 of VS Code.
