### ISSUE TITLE
Code hangs indefinitely when opening from WSL commandline

### ISSUE THREAD

**Issue by mauve** [microsoft/vscode#143184]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.64.2 (system setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22543

Steps to Reproduce:

1. Open WSL
2. Type `code` + [ENTER]

Output:

```
mikae@STATION:~/repos$ VSCODE_WSL_DEBUG_INFO=true code
+ COMMIT=f80445acd5a3dadef24aa209168452a3d97cc326
+ APP_NAME=code
+ QUALITY=stable
+ NAME=Code
+ SERVERDATAFOLDER=.vscode-server
+ realpath /mnt/c/Program Files/Microsoft VS Code/bin/code
+ dirname /mnt/c/Program Files/Microsoft VS Code/bin/code
+ dirname /mnt/c/Program Files/Microsoft VS Code/bin
+ VSCODE_PATH=/mnt/c/Program Files/Microsoft VS Code
+ ELECTRON=/mnt/c/Program Files/Microsoft VS Code/Code.exe
+ IN_WSL=false
+ [ -n Ubuntu-20.04 ]
+ IN_WSL=true
+ [ true = true ]
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID
+ wslpath -m /mnt/c/Program Files/Microsoft VS Code/resources/app/out/cli.js
+ CLI=C:/Program Files/Microsoft VS Code/resources/app/out/cli.js
+ WSL_EXT_ID=ms-vscode-remote.remote-wsl
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Program Files/Microsoft VS Code/Code.exe C:/Program Files/Microsoft VS Code/resources/app/out/cli.js --ms-enable-electron-run-as-node --locate-extension ms-vscode-remote.remote-wsl
```

**Comment by mauve** [comment]
I tried reinstalling a couple of times (and deleting ~/.vscode-server) which didn't work. However a reboot fixed it :)

**Comment by ghostoy** [comment]
I'm experiencing the same problem. Reboot would work, but it's quite annoying.

**Comment by aeschli** [comment]
Can you reproduce the issue by running `ELECTRON_RUN_AS_NODE=1 "/mnt/c/Program Files/Microsoft VS Code/Code.exe" "C:/Program Files/Microsoft VS Code/resources/app/out/cli.js" --ms-enable-electron-run-as-node --locate-extension ms-vscode-remote.remote-wsl` in a WSL terminal?
