### ISSUE TITLE
Search: Add checkbox to toggle include or exclude fields when searching

### ISSUE THREAD

**Issue by johnpaulensign** [microsoft/vscode#143108]
Depending on the project, I am often searching around for certain things and I need to use the include or exclude filters a lot.

During this time I maybe filtering out tests, including specific directories, or some combination. I am also frequently including/excluding the same things depending on which point I am at in development. It is a little tedious to have to type *.spec.ts into exclude, remove it when doing a different search, and then add it back when done. 

It would be awesome if there was a checkbox next to the input that would toggle the filter but keep the contents of the input. It would also be great if it were enabled when the input changes.

**Comment by IllusionMH** [comment]
FYI. An this moment you can use <kbd>↑</kbd>/<kbd>↓</kbd> to navigate between history entries with and without spec files.

**Comment by roblourens** [comment]
I see the problem but in my view, using history is the best thing to do here.
