### ISSUE TITLE
Cannot get grammar injection to work

### ISSUE THREAD

**Issue by EdCordata** [microsoft/vscode#143155]
I am trying to inject custom grammar's into an existing language, but I can't seem to get it to work.

`package.json`:
```json
{
  "name": "custom-grammar",
  "displayName": "custom-grammar",
  "version": "0.0.1",
  "engines": {
    "vscode": "^1.64.0"
  },
  "contributes": {
    "grammars": [
      {
        "path": "./ruby.has_many.json",
        "scopeName": "ruby.has_many.injection",
        "injectTo": [ "source.ruby" ]
      }
    ]
  }
}
```

`ruby.has_many.json`:
```json
{
  "scopeName": "ruby.has_many.injection",
  "injectionSelector": "L:variable.other.ruby",
  "patterns": [
    {
      "include": "#has_many"
    }
  ],
  "repository": {
    "has_many": {
      "match": "has_many",
      "name": "keyword.other.has_many.rails.ruby"
    }
  }
}
```

![image](https://user-images.githubusercontent.com/71574639/154175568-f51b548e-3597-4326-8bc9-fced5bec6534.png)

Could someone, please, point out what is wrong here? I am not sure if this is a bug or i am just doing something wrong.

I even copy/pasted the `CREATING A BASIC INJECTION GRAMMAR` example from the official guide:
https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#injection-grammars).

But that also did not work.

Here is the example, for quick test:
[custom-grammar.zip](https://github.com/microsoft/vscode/files/8078854/custom-grammar.zip)

VS Code version:
![image](https://user-images.githubusercontent.com/71574639/154724495-c940a124-08f3-4e26-9796-1c0e30352739.png)

**Comment by aeschli** [comment]
Can you paste the Ruby code snippet?

**Comment by EdCordata** [comment]
> 

```ruby
class User < ApplicationRecord
  has_many :comments
end
```

**Comment by aeschli** [comment]
Doesn't look right
![image](https://user-images.githubusercontent.com/6461412/155019735-d2aed3c0-92ce-4119-a4fc-58d25c490ddb.png)

**Comment by EdCordata** [comment]
> Doesn't look right ![image](https://user-images.githubusercontent.com/6461412/155019735-d2aed3c0-92ce-4119-a4fc-58d25c490ddb.png)

I am not sure why you have those dots there, but, as you can see, you have `source.ruby` scope.

You probably don't have other scopes, cos you don't have `rails` plugin installed.

You can change:
```json
"injectionSelector": "L:variable.other.ruby",
```
to
```json
"injectionSelector": "L:source.ruby",
```
in `ruby.has_many.json` file and you will be able to test this issue anyway.

**Comment by aeschli** [comment]
In the devtools (Help > Toggle Dev Tools) you can see that there's a problem reading the `ruby.has_many.json` file.
It has 3 extra bytes in the beginning, you need to remove them (e.g. with the hex editor).
We expect the grammar files to be UTF-8.

**Comment by EdCordata** [comment]
That file's encoding was `UTF-8 with BOM`. I changed it to `UTF-8` and now it indeed works.
I didn't realize that would be a problem. I also should have checked the dev tools myself. That kinda slipped my mind.

You can close this issue, it's solved.  Thank you @aeschli.
