### ISSUE TITLE
Installing VSCode for MacOs impossible because it is "damaged" 

### ISSUE THREAD

**Issue by planetarysafari** [microsoft/vscode#143188]
Does this issue occur when all extensions are disabled?: This is prior to using VSCode

- VS Code Version: Darwin Universal/Intel or Darwin Insider
- OS Version: MacOs Catalina 10.15.7 

Steps to Reproduce:

1. Download from https://code.visualstudio.com for MacOs
2. Use Archive Utility to unzip 
3. Open the app 
4. Result : PopUp window stating "Visual Studio Code is damaged and cannot be opened.

<img width="411" alt="Screenshot 2022-02-16 at 11 21 34" src="https://user-images.githubusercontent.com/68694612/154246881-eafd688a-bf29-43fe-936b-a4a768e521d9.png">

**Comment by deepak1556** [comment]
which archive utility are you using to extract ?

Can you also provide the output of `xattr -lv <path-to-zip>`
