### ISSUE TITLE
Images view slow to load in windowed mode

### ISSUE THREAD

**Issue by macccorehenni** [microsoft/vscode#143157]
Issue Type: <b>Performance Issue</b>

ChromeOS-- running through Chrostini, have 8g total of ram

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:01:35.750Z)
OS version: Linux arm64 5.10.92-14515-g04cab5a472cd
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|unknown (8 x 0)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 2, 1|
|Memory (System)|2.71GB (2.70GB free)|
|Process Argv|--unity-launch --crash-reporter-id b1a727e0-e096-49cf-9a76-6eae29d98243|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   183	   291	code main
    0	    14	   309	   zygote
    0	   344	   387	     gpu-process
    0	    14	   392	       broker
    0	    14	   310	   zygote
    0	     8	   313	     zygote
    0	   194	  5775	       window (undefined)
    3	    86	  5831	       window (Issue Reporter)
    0	    25	   391	   utility-network-service
    0	    89	   500	   shared-process
    0	    39	   579	     ptyHost
    0	     3	  4666	       /usr/bin/bash
    0	    17	  4926	         /usr/bin/python3 ./vitsrc
    0	    31	   729	     fileWatcher
    0	     0	  5850	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  5851	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   352	   701	   window (image_9.JPG in images)
    0	   230	   728	   extensionHost
    0	    69	   797	     /usr/share/code/code --ms-enable-electron-run-as-node /home/maccore/.vscode/extensions/streetsidesoftware.code-spell-checker-2.1.7/packages/_server/dist/main.js --node-ipc --clientProcessId=728
    0	    67	  1162	     /usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=728
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (image_9.JPG in images)
|    Folder (my_linux_setup): 6 files
|      File types: json(1) md(1) deb(1) sh(1)
|      Conf files: settings.json(1)
|    Folder (my-files-sync): 30 files
|      File types: JPG(9) txt(4) json(3) gitignore(1) mhtml(1) kdbx(1)
|                  code-workspace(1) docx(1) py(1)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: python bashdb;
```

</details>
<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-office|cwe|2.5.3
auto-dark-mode-windows|dan|1.0.11
github-repository-manager|hen|1.3.2
switch-editor|man|1.0.4
web-browser|mas|0.0.1
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.1
linux-desktop-file|nic|0.0.18
material-icon-theme|PKi|4.13.0
vscode-git-commit|rio|2.1.0
bash-debug|rog|0.3.9
code-spell-checker|str|2.1.7
luna-paint|Tyr|0.13.1
vscodeintellicode|Vis|1.2.17
auto-git|zei|1.0.3

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
vsbas813:30436447
vscscmwlcmc:30438804
helixcf:30438807

```

</details>

**Comment by macccorehenni** [comment]
ChromeOS platform: Google_Juniper.12573.244.0

**Comment by mjbvz** [comment]
This is not an actionable bug report. What does very slow mean for example? Try following [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information
