### ISSUE TITLE
GIT

### ISSUE THREAD

**Issue by Yeyu83** [microsoft/vscode#143110]
Issue Type: <b>Feature Request</b>

Source Control don't refresh the changes properly. Have to close and re-open the editor to see the changes I've just made. This issue is on the Linux current version

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
OS version: Linux x64 5.13.0-28-generic snap
Restricted Mode: No

**Comment by lszomoru** [comment]
@Yeyu83, could you please provide more details on the behaviour that you are seeing? Thank you!
