### ISSUE TITLE
Decorations aren't positioned correctly when using dom renderer

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#143113]
After setting `"terminal.integrated.gpuAcceleration": "off"`

![image](https://user-images.githubusercontent.com/2193314/154095151-b21ef8e9-4b24-455d-be16-56bddb2d1b6c.png)

**Comment by meganrogge** [comment]
it's working for me
![Screen Shot 2022-02-15 at 11 48 31 AM](https://user-images.githubusercontent.com/29464607/154119517-53d63643-9934-404d-af7e-b702c7c469ff.png)

**Comment by meganrogge** [comment]
maybe this was actually just a problem related to resizing?

**Comment by meganrogge** [comment]
Could be because of your multiline prompt?

**Comment by Tyriar** [comment]
I doubt it, it was working fine and happened right after switching the setting

**Comment by meganrogge** [comment]
I see them shift slightly right, but nothing like what you showed
![Recording 2022-02-15 at 12 28 39](https://user-images.githubusercontent.com/29464607/154125853-1ad25248-0d65-41ff-9d66-989f99e15200.gif)

**Comment by meganrogge** [comment]
better

![Recording 2022-02-15 at 12 40 18](https://user-images.githubusercontent.com/29464607/154127633-b8f2a147-3451-4fc0-961b-50a3def2a165.gif)
