### ISSUE TITLE
TypeError: Cannot assign to read only property 'write' of object '#<Socket>

### ISSUE THREAD

**Issue by tourajvaziri** [microsoft/vscode#143132]
Does this issue occur when all extensions are disabled? Yes

- VS Code Version: 1.64.2 (user setup)
- OS Version: Windows 10

Sample project to use : [extension-sample.zip](https://github.com/microsoft/vscode/files/8073088/extension-sample.zip)

Steps to Reproduce:

1. Unzip the attached extension-sample project
2. Open the project in VSCODE 1.64.2 (user setup)
3. Open terminal and run npm install
4. Click on the Run And Debug icon from the left panel in vscode
5. Select Run Extension and Click on 'Start Debugging'
6. Once the [Extension development Host] window is opened, open command Pallete (Ctrl + Shift + P), Type 'Hello Test' and Hit Enter

Actual Behaviour: 
Test failed.
With error: 
TypeError: Cannot assign to read only property 'write' of object '#<Socket>'

![image](https://user-images.githubusercontent.com/16887964/154114339-eb8dfc44-c18d-493b-ad51-c8c052202a43.png)

Expected Behavior:
Test should run OK with no errors.

Note:
If we run the same above steps with vscode version 1.63.2 or earlier versions the test will pass with no error. You can also see the jest output in the developers console.

More info:
After more investigation, we found out that the problem exists when running jest.runCLI from our extension.
Seems that the process.stdout.write is no longer writable in vscode version 1.64.2 (user setup) and under the hood jest is setting the process.stdout.write, specifically in the default reporter classes: DefaultReporter.js and VerboseReporter.js
Also if the test is run from the terminal (using npm test) it also works and there is output from jest with summary of test excecutions.

**Comment by weinand** [comment]
@connor4312 might be related to https://github.com/microsoft/vscode/commit/538988cf720422bdc9f6b960398e98375c747f56

**Comment by tourajvaziri** [comment]
Thanks for fixing. Verfied it is working in the latest vscode insider build!
