### ISSUE TITLE
Exporting and importing of breakpoints

### ISSUE THREAD

**Issue by dhiraj113** [Microsoft/vscode#14314]
Does VSCode support exporting and importing of breakpoints? If so, how to export and import breakpoints.
- VSCode Version: 1.6.1
- OS Version: Ubuntu 14.04 LTS

Steps to Reproduce:
1. 
2.

**Comment by weinand** [comment]
@dhiraj113 export/import of breakpoints is not yet possible.

**Comment by dhiraj113** [comment]
Okay. Would love to see the feature implemented soon. Thanks.

**Comment by weinand** [comment]
Okay, then please submit a pull request. Thanks. ;-)
