### ISSUE TITLE
Test: TypeScript upgrade to 2.0.6

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#14315]
The tsserver we ship out of the box with VS Code got upgraded to 2.0.6. Since 2.0.6 has API changes the code talking to the tsserver is now version aware. We therefore need to sanity check the TS features against a 1.8.10, a 2.0.3 and the shipped 2.0.6 version.

- [x] 1.8.10 -  @mousetraps
- [x] 2.0.3 -  @roblourens 
- [x] 2.0.6 - @egamma 

Complexity: 4

## Feature testing
- create a new workspace. If you test 1.8.10 or 2.0.3 install typescript into the workspace using npm install typescript@x.x.x and use the `typescript.tsdk` to point to the local tsserver directory.
- test all TS functions like: error reporting, intellisense, goto definition, find references, format, format on type, hover, rename, document symbols and workspace symbols.
- try things...
- if you test the 2.0.6 version also test the following scenario: create a new workspace with two js files but no tsconfig.json or jsconfig.json. The two JS file should reference globals symbols from the other file but should not refer to the other file using /// reference statements or import statements. Open both files and trigger workspace symbols. Ensure that you see the symbols from both files. Also test find references on a symbol that is referenced in the other file
- if the error is an 'obvious' TypeScript problem file the issue directly against the TS repository: https://github.com/Microsoft/TypeScript. Otherwise file it against vscode.

**Comment by roblourens** [comment]
In 2.0.3 I just see that I don't get language service support for a new ts file until I close and reopen the document, but I assume this is a known issue.
