### ISSUE TITLE
我的vscode每次换行都有声音

### ISSUE THREAD

**Issue by PeaceFL** [microsoft/vscode#143109]
Issue Type: <b>Bug</b>

我的vscode在使用时，每次都有声音呢

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (10.37GB free)|
|Process Argv|--crash-reporter-id ebccfac1-ae2a-48cb-bb16-ecaf9575e27c|
|Screen Reader|yes|
|VM|44%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.3
aliyun-serverless|ali|1.27.19
vscode-django|bat|1.9.0
htmlplay|bia|0.0.10
tf2snippets|cha|0.1.0
path-intellisense|chr|2.8.0
c-cpp-compile-run|dan|1.0.15
vscode-markdownlint|Dav|0.46.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
vscode-html-css|ecm|1.11.0
alstructurecreator|Edy|0.3.8
code-runner|for|0.11.7
vscode-javac|geo|0.2.39
beautify|Hoo|1.5.0
path-autocomplete|ion|1.18.0
nbpreviewer|jit|1.2.2
pdf|k5h|4.2.3
translation|liw|0.0.7
vscode-clang|mit|0.2.4
vscode-docker|ms-|1.19.0
vscode-language-pack-zh-hans|MS-|1.64.6
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.1
jupyter|ms-|2022.1.1201831736
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-wsl|ms-|0.64.2
azure-account|ms-|0.10.0
cpptools|ms-|1.8.4
autodocstring|njp|0.6.0
java|red|1.3.0
LiveServer|rit|5.7.4
salesforcedx-vscode-core|sal|53.16.0
salesforcedx-vscode-lwc|sal|53.16.0
salesforcedx-vscode-visualforce|sal|53.16.0
open-in-browser|tec|2.0.0
cloudbase-toolkit|ten|0.3.1
tencent-cloud-vscode-toolkit|ten|2.0.17
pdf|tom|1.2.0
tensorflow-snippets|vah|0.3.3
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0
vscode-spring-initializr|vsc|0.8.0
cors-browser|Wsc|1.0.11

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30438340
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc008:30436278
vsbas813:30436447
vscscmwlcmc:30436992
helixcf:30438276

```

</details>

**Comment by rzhao271** [comment]
Rough translation: "Every time I use VS Code, there is sound"
It might be because of the `audioCues.enabled` setting. Can you see if setting it to `off` helps?

**Comment by hediet** [comment]
Actually, the fix only fixes a bug in insiders.
