### ISSUE TITLE
File icon doesn't update on save as.

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#143129]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Open a file with a file icon
2. Save as a file type with a different file icon i.e. `.json` -> `.js`
3. 🐛 The `.js` file will still have the `.json` file icon. Note reloading the window updates them properly.

**Comment by aeschli** [comment]
I can't reproduce.

![Peek 2022-02-21 18-07](https://user-images.githubusercontent.com/6461412/154999999-366ab15a-b780-4fef-9fd8-d5530007260c.gif)
 
What theme is it?

**Comment by lramos15** [comment]
Hmmm cannot reproduce this anymore.
