### ISSUE TITLE
Problema di visualizzazione dell'interfaccia

### ISSUE THREAD

**Issue by GardenP** [microsoft/vscode#143196]
All'apertura ed all'utilizzo del software vengono riscontrati problemi di visualizzazione corretta di tutta l'interfaccia. 
La visualizzazione risulta sgranata e non è possibile fruire correttamente dell'applicazione che presenta bug visivi.
Risoluzione utilizzata 2560x1440 
Frequenza aggiornamento monitor 144Hz
Tempo di risposta 1ms

![Desktop Screenshot 2022 02 16 - 13 31 51 96](https://user-images.githubusercontent.com/99808455/154265278-90ccbff8-bf68-4a2b-ae0b-59ef072b2dfe.png)

.

**Comment by alexdima** [comment]
This looks like a problem caused by the GPU. Does closing all instances and launching `code --disable-gpu` help?

**Comment by deepak1556** [comment]
Can you also test if the issue repros with insiders version of the application which you can download from https://code.visualstudio.com/insiders
