### ISSUE TITLE
Test: Sublime Text Keymap 

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#14317]
Test for [Sublime Text Keymap Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings)

- [x] macOS @Tyriar 
- [x] Windows @alexandrudima 
- [x] Linux @kieferrm 

Test Details

1. Install [Sublime Text Keymap extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings). 
2. Try a handful of keyboard shortcuts from the contributions list.

**Comment by rebornix** [comment]
Take @kieferrm 's test task.
