### ISSUE TITLE
Ability to edit both the source code and the code in a custom text editor

### ISSUE THREAD

**Issue by mastevb** [microsoft/vscode#143169]
Hi developers,

I'm not sure if this has already been addressed or not, but I'm looking for a feature that would allow users to edit both the source code and the code in a custom text editor, side by side, just like a editable webview panel. I've checked out the custom text editor feature and it seems to be closest to what I'm thinking about, but I couldn't figure out a way to display both the source code and the rendered code in the custom text editor.

Thanks!

**Comment by mjbvz** [comment]
Falls under #22068
