### ISSUE TITLE
ctrl+alt+p no longer works as a keybinding when the editor is focused

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14313]
- VSCode Version: Code - Insiders 1.7.0-insider (c038219f8d137b4972a15346b81ea03751d669d4, 2016-10-24T10:03:46.015Z)
- OS Version: Linux x64 4.4.0-45-generic, Ubuntu 16.04

Steps to Reproduce:

1. Run `code-insiders --disable-extensions`
2. Add keybinding: `{ "key": "ctrl+alt+p",    "command": "workbench.action.closeAllEditors" },`
3. Focus an editor and use it, nothing happens

I saw this when trying to use https://marketplace.visualstudio.com/items?itemName=felipecaputo.git-project-manager, it's a regression in the last 1-3 days I would guess.

**Comment by Analyst3** [comment]
Related keybinding that is not working

1. Use Ctrl+5 to run code in attachment (this is default keybinding, code runs as expected)
2. Use F5 to stop run (this is default keybinding) 
>> result: Keybinding does not trigger VSCode action

![image](https://cloud.githubusercontent.com/assets/23038495/19659079/bf40acc4-9a2a-11e6-94dc-44fc2fb67e6c.png)

**Comment by alexandrudima** [comment]
This works for me on Windows. @Tyriar is it possible that your OS is "eating" that specific keybinding?
What happens when you press `ctrl+alt+p` in the Define keybinding widget?

**Comment by Tyriar** [comment]
In the define keybinding widget pressing ctrl+alt+p results in ctrl+alt+unknown, it doesn't get the p event.

I haven't upgraded to Ubuntu 16.10 yet on this machine but I may have installed some regular updates. Based on what [I'm](http://askubuntu.com/q/291338/409516) [seeing](https://forum.sublimetext.com/t/ctrl-alt-p-does-not-work/9113/3) after a quick search though it's very likely an OS-level issue. Thanks @alexandrudima

**Comment by Tyriar** [comment]
Actually, the fact that it works when the explorer is focused goes against the OS hypothesis.

**Comment by alexandrudima** [comment]
@Tyriar If the define keybindings widget doesn't see `ctrl+alt+p`, then nowhere in vscode do we get to see `ctrl+alt+p`. Is it possible that the OS or an app eats up `ctrl+alt+p` intermittently?

**Comment by Tyriar** [comment]
Looked into it a little more, I'm quite sure it's related to only when a `textarea` is selected as the keybinding doesn't work when the focus is on the debug console, terminal or the editor, but it works elsewhere. So yeah, it's either Ubuntu or Chromium (under Linux?).

**Comment by alexandrudima** [comment]
In the last 1-3 days I think we've update to electron 1.3.8 so that might be the culprit. You can try getting an older build from our build website or using the stable 1.6.x to confirm.

**Comment by Tyriar** [comment]
Hm, it's not Chromium, I just checked 1.7.0 from 8 days ago as well as stable. Probably just another case of don't use <kbd>alt</kbd> for Linux.

**Comment by alexandrudima** [comment]
Most weird. Also possible that `ctrl+alt+p` is interpreted as `altgr+p`. Perhaps it depends on the keyboard layout you're using (in case you've been using different ones recently).

**Comment by Tyriar** [comment]
Doesn't work regardless of keyboard layout, tried English (US), English (UK) and Korean.

**Comment by Tyriar** [comment]
@alexandrudima just an FYI in case you see it elsewhere; it works perfectly fine on my home PC (Ubuntu 16.10) but not on my work PC (Ubuntu 16.04), it definitely worked on 16.04 before though. So the theory is that it's still some OS-level conflict.
