### ISSUE TITLE
I can't execute any command associated with the shortcut Ctrl+Shift+S

### ISSUE THREAD

**Issue by MiguelGuthridge** [microsoft/vscode#143173]
Issue Type: <b>Bug</b>

When I try pressing Ctrl+Shift+S, nothing will happen even though I have commands bound to that shortcut. When I try to bind new commands to the shortcut using the shortcut editor, the 's' key won't register if Ctrl and Shift are both pressed. Any other key that I've tried has worked for this.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
OS version: Linux x64 5.13.0-28-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 3083)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.38GB (1.77GB free)|
|Process Argv|--crash-reporter-id 3b081b92-7439-479f-bf43-f2c2416480cb|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|13.2.3
doxdocgen|csc|1.3.2
mustache|daw|1.1.1
pick-file-command|eth|0.0.1
change-case|Fin|0.0.4
todo-tree|Gru|0.0.215
latex-workshop|Jam|8.23.0
better-cpp-syntax|jef|1.15.13
vscode-nuget-package-manager|jmr|1.1.6
mips|kda|0.0.9
vsc-python-indent|Kev|1.14.2
restructuredtext|lex|168.0.0
mypy|mat|0.2.1
git-graph|mhu|1.30.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.1
jupyter|ms-|2022.1.1201831736
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.4
remote-ssh|ms-|0.74.0
remote-ssh-edit|ms-|0.74.0
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5330
autodocstring|njp|0.6.1
material-icon-theme|PKi|4.13.0
java|red|1.3.0
synthwave-vscode|Rob|0.1.11
vscode-xml-complete|rog|0.3.0
vscode-open|san|0.1.0
vscode-autohotkey|sle|0.2.2
code-spell-checker|str|2.1.7
even-better-toml|tam|0.14.2
simple-rst|tro|1.5.1
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30438340
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
vsbas813:30436447
vscscmwlcmc:30438804
helix:30438806

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Are you sure that VS Code receives this combination and it's not intercepted by OS or other apps?

See https://github.com/microsoft/vscode/wiki/Keybinding-Issues for troubleshooting steps.

**Comment by MiguelGuthridge** [comment]
@IllusionMH thanks so much for the fix! Turns out some random Kwin script updated and registered a new shortcut that overrode it, which is sorta yucky. Thanks for the pointer :)
