### ISSUE TITLE
Terminal reprints path and duplicates characters when using some unicode chars on Windows

### ISSUE THREAD

**Issue by misaka00251** [microsoft/vscode#143103]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.0-insider
- OS Version: Windows 10 21H2

Steps to Reproduce:

1. Install oh-my-posh and use the theme [here](https://github.com/JanDeDobbeleer/oh-my-posh/issues/1747)
2. Run anycommand in VSCode terminal

![2022-02-12_13-28-04](https://user-images.githubusercontent.com/3908746/153698170-d4ee0780-ef6f-448f-ae39-43b83babbbeb.gif)

By installing another fresh Visual Studio Code won't solve either.

For escape sequence logging:

![image](https://user-images.githubusercontent.com/3908746/154074221-c26f46f3-b5d6-4dea-84b0-af5cc2a9fa8e.png)

**Comment by meganrogge** [comment]
can you toggle screen cast mode and make a new gif of it happening?

Also, can you try this in an external terminal and confirm it doesn't happen?

**Comment by misaka00251** [comment]
Sure, here you go:
![2022-02-16_13-51-35](https://user-images.githubusercontent.com/3908746/154204583-b83f0650-c224-4ed7-94aa-6ea78f27d30b.gif)

It didn't happen in external terminal:
![2022-02-12_13-29-54](https://user-images.githubusercontent.com/3908746/153698243-a029bf34-886b-4a59-b760-b3d5e2bbc8e1.gif)

**Comment by misaka00251** [comment]
I found the problem in my theme. In my theme, this block have a [[variation selector](https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block))](https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block)) `\ufe0f`.

```
        {
          "background": "#0077c2",
          "foreground": "#ffffff",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "template": " PE\u2197\ufe0fKO\u2198\ufe0f "
          },
          "style": "powerline",
          "type": "text"
        },
```

Without the variation selector the character still renders fine, but there's no additional information about presentation.

Strangely this only happens in VSCode, remove `\ufe0f` and there's no more problem.

**Comment by demcgovern** [comment]
I'm experiencing this issue as well, though it's only happening with the first character. I'm using [starship](https://starship.rs/).

About:

![image](https://user-images.githubusercontent.com/10171896/165210592-8c71effc-0540-4173-8828-c99a6d0106ec.png)

Integrated Terminal:

![Recording 2022-04-25 at 21 49 53](https://user-images.githubusercontent.com/10171896/165210666-40720b84-2b8d-4bf8-b8d9-76dc3edb7634.gif)

Windows Terminal:

![Recording 2022-04-25 at 21 56 41](https://user-images.githubusercontent.com/10171896/165211027-868ed089-a0b5-493a-9cb5-6e45029c1364.gif)

**Comment by ehawman-rosenberg** [comment]
Confirming that I see this issue as well. Using Oh-My-Posh

![image](https://user-images.githubusercontent.com/81652082/167053718-7e41b98b-9b70-4d1c-a530-17f278253cba.png)
(typed "abcdefg")

**Comment by Hamdysaad20** [comment]
i have the same issue

**Comment by Tyriar** [comment]
This happens because of ambiguous width unicode symbols conflicting between vscode/xterm.js and conpty reprinting the screen. The only solution currently is to remove problem characters from your prompt.

**Comment by RichardCYC** [comment]
I encountered the same problem and the duplicated characters showed up when I press tab.

**Comment by sidewinder12s** [comment]
I think I've also been noticing this in macos & linux vscode instances.

**Comment by nalinvyas** [comment]
> ~ Found the suggestion [here](https://github.com/microsoft/vscode/issues/66200#issuecomment-452347096) and switching to a theme without icon at the start of the line fixed the issue!

This didn't fix my issue

**Comment by saberSakin** [comment]
> I found the Unicode problem in my theme. In my theme, this block have a [[variation selector](https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block))](https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block)) `\ufe0f`.
> 
> ```
>         {
>           "background": "#0077c2",
>           "foreground": "#ffffff",
>           "powerline_symbol": "\ue0b0",
>           "properties": {
>             "template": " PE\u2197\ufe0fKO\u2198\ufe0f "
>           },
>           "style": "powerline",
>           "type": "text"
>         },
> ```
> 
> Without the variation selector the character still renders fine, but there's no additional information about presentation.
> 
> Strangely this only happens in VSCode, remove `\ufe0f` and there's no more problem.



> I found the Unicode problem in my theme. In my theme, this block have a [[variation selector](https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block))](https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block)) `\ufe0f`.
> 
> ```
>         {
>           "background": "#0077c2",
>           "foreground": "#ffffff",
>           "powerline_symbol": "\ue0b0",
>           "properties": {
>             "template": " PE\u2197\ufe0fKO\u2198\ufe0f "
>           },
>           "style": "powerline",
>           "type": "text"
>         },
> ```
> 
> Without the variation selector the character still renders fine, but there's no additional information about presentation.
> 
> Strangely this only happens in VSCode, remove `\ufe0f` and there's no more problem.

Where to find this in vscode?

**Comment by saberSakin** [comment]
i have the same problem. I have no themes and no extension installed but still the vscode terminal is doing this.

**Comment by Tyriar** [comment]
I'm going to close this since it's unfortunately not actionable by us. To clarify the issue:

- xterm.js uses width of chars based on unicode spec via the `terminal.integrated.unicodeVersion` setting. We currently support 6 and 11 but there's a new one in the works on the xtermjs/xterm.js: A terminal for the web project
- ConPTY (or Oh-My-Posh?) has it's own width for ambiguous characters like this, when reprinting the screen it sets the cursor position directly based on what it thinks the character width is but this can differ from xterm.js'/vscode's

The recommendation is still to not use ambiguous width characters in your prompt.
