### ISSUE TITLE
javascript code got deleted on its own

### ISSUE THREAD

**Issue by rainerhamal** [microsoft/vscode#143161]
Issue Type: <b>Performance Issue</b>

VSCode was not running lagging while performing javascript until VScode shut itself dow. when opening the vscode again my javascript codes have been wiped out.!

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
live-sass|gle|5.1.1
vscode-edge-devtools|ms-|1.4.4
live-server|ms-|0.2.12
LiveServer|rit|5.7.4
html5-boilerplate|sid|1.1.1
vscode-icons|vsc|11.10.0

</details>

**Comment by gjsjohnmurray** [comment]
Does https://github.com/microsoft/vscode/issues/142926#issuecomment-1037257705 apply to your situation?
