### ISSUE TITLE
IntelliSense messed with code snippets

### ISSUE THREAD

**Issue by ericsia** [microsoft/vscode#143224]
removed. Not an big issue.

**Comment by ericsia** [comment]
> This should probably be filed on VS Code. We don't control priority of snippet over completion.

@karthiknadig 
sure it is priority but not the extension itself? Because as you can see in the picture the `np` word is gone when the extension is enabled

**Comment by karthiknadig** [comment]
IntelliSense is provided over language server protocol. Based on your setting in your case it comes from the `pylance` extension. But that extension also provides completions over LSP. The python extension does not control how this is displayed.

/cc @judej

**Comment by ericsia** [comment]
@karthiknadig just curious, do you know how the intellisense obtain the definition? I mean where is it store, because I like to add additional text or simplify some.
Like this one bytearray should be classified as built-in method but I see it is just label as class.

![image](https://user-images.githubusercontent.com/24624808/154836188-c0462e07-1e1f-474a-bb05-4b4737848bf4.png)

**Comment by karthiknadig** [comment]
@ericsia For `"python.languageServer": "Jedi"` the code lives [here](https://github.com/davidhalter/jedi). 

For `"python.languageServer": "Default"` or `"python.languageServer": "Pylance"` you may have to file a bug here https://github.com/microsoft/pylance-release
