### ISSUE TITLE
Contributions showing "unknown" for keybindings

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#14323]
VS Code Insiders 1.7
macOS

I have created this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.atom-keybindings). The contributions is a list of keybindings from Atom. 

The following keybindings are not resolving. In the contributions list it shows the keybinding as unknown. 

```json
{
  "mac": "cmd+shift+{",
  "win": "ctrl+pagedown",
  "linux": "ctrl+pagedown",
  "key": "ctrl+pagedown",
  "command": "workbench.action.nextEditor"
},
{
  "mac": "cmd+shift+}",
  "win": "ctrl+pageup",
  "linux": "ctrl+pageup",
  "key": "ctrl+pageup",
  "command": "workbench.action.previousEditor"
},
{
  "mac": "cmd++",
  "win": "ctrl++",
  "linux": "ctrl++",
  "key": "ctrl++",
  "command": "workbench.action.zoomIn"
}
```

macOS:

![image](https://cloud.githubusercontent.com/assets/2449568/19661094/25460f6c-99e7-11e6-9f3e-7243f939c4c1.png)

Windows:
![image](https://cloud.githubusercontent.com/assets/2449568/19661396/67e67306-99e8-11e6-9706-ed2bb2fa586a.png)

My first thought was that the characters `{`, `}`, and `+` needed to be escaped. However, doing so causes an error. 

![image](https://cloud.githubusercontent.com/assets/2449568/19661253/de221760-99e7-11e6-974b-44ab5ffd6b25.png)

This is also happening with [Sublime Text Keymap](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings) extension. 

Windows:

```json
 {
  "mac": "alt+cmd+[",
  "key": "ctr+shift+[",
  "command": "editor.fold",
   "when": "editorFocus"
},
```

![image](https://cloud.githubusercontent.com/assets/2449568/19661572/19963b36-99e9-11e6-805c-c4fc10bdf27b.png)

```json
{
  "mac": "cmd++",
  "key": "ctrl++",
  "command": "workbench.action.zoomIn"
}
```

![image](https://cloud.githubusercontent.com/assets/2449568/19661581/21338d1c-99e9-11e6-90ad-44170f354436.png)

```json
{
  "mac": "alt+f12",
  "key": "context_menu",
  "command": "editor.action.showContextMenu",
  "when": "editorTextFocus"
},
```

![image](https://cloud.githubusercontent.com/assets/2449568/19661620/42c1903c-99e9-11e6-86d7-353b1a38c47b.png)

**Comment by alexandrudima** [comment]
`+` and `{` are not valid key codes. Please see https://code.visualstudio.com/docs/customization/keybindings#_accepted-keys

**Comment by waderyan** [comment]
Thanks @alexandrudima. To clarify my understanding - there is no way to set a keybinding for `{` or `+`? Sounds like I need to make a feature request for this :)

**Comment by waderyan** [comment]
Created this issue - https://github.com/Microsoft/vscode/issues/14478
