### ISSUE TITLE
Syntax Highilighting not working

### ISSUE THREAD

**Issue by TheVaccin3** [microsoft/vscode#143254]
Issue Type: <b>Bug</b>

Open any C++ file (.cpp, .h, etc) and text is not using colors. its all white except for integers, strings, and control flow keywords. ive installed the c++ extension pack but its still all white. 

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.42GB free)|
|Process Argv|--crash-reporter-id 129070ce-ba03-4eab-9b17-5784631bb742|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
make-hidden|dev|3.0.3
prettier-vscode|esb|9.2.0
syntax-highlighter|evg|0.5.0
better-cpp-syntax|jef|1.15.13
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.3
jupyter|ms-|2022.1.1301854968
remote-containers|ms-|0.217.4
remote-ssh|ms-|0.74.0
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5330
hide-gitignored|npx|1.1.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.17
vscode-icons|vsc|11.10.0

(1 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/19929553/154417102-cbedf367-cb24-4f64-a334-399aa5386304.png)
Edit: here is a code snippet if this explains my situation better. is this expected, or not?

**Comment by JacksonKearl** [comment]
\extC++
