### ISSUE TITLE
Integrated terminal unlimited buffer

### ISSUE THREAD

**Issue by wilrnh** [Microsoft/vscode#14320]
- VSCode Version: 1.6.1
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Run command in terminal that continuously spits output
2. Monitor memory usage with Activity Monitor

It seems as if, at least by default, vscode's integrated terminal has an unlimited buffer. Is this by design, or is there a way to limit this somehow?

**Comment by wilrnh** [comment]
Looks like this is a setting in Terminal.app. Close this issue if this is the case. I'll go ahead and try this out.

**Comment by Tyriar** [comment]
I believe the buffer is capped at 1000 lines, are you sure you're seeing more than that?

**Comment by marcusball** [comment]
On Windows, during my debugging, I occasionally accidentally put a print statement in an infinite loop. This spams the output window, and Code immediately becomes very unresponsive. If I click the garbage can icon to delete the output console, Code will take _a minute or two_ before the delete is handled and the console is closed; only after this does everything become responsive again. 

At this point, terminating the Code process forcefully is easier than trying to recover from the buffer getting filled.

**Comment by wilrnh** [comment]
@Tyriar I definitely got more than that into the buffer. I'm pretty convinced that the terminal app that vscode launches for the integrated terminal is responsible. I previously had Terminal.app using up as much memory as possible for the buffer, which is what I think causes the system impact when sending too much output to the terminal. Now, I have Terminal.app capped at 10k lines which seems to keep things running smoothly for now. I'd close this as a non-issue unless you want to document this in settings.json. I already have an answer on stackoverflow: http://stackoverflow.com/questions/39881395/visual-studio-code-scroll-back-buffer/

**Comment by wilrnh** [comment]
@marcusball I believe cmd.exe has a scrollback limit setting as well.

**Comment by Tyriar** [comment]
@marcusball see https://github.com/sourcelair/xterm.js/issues/280 for that, that's not the buffer but issues with the rendering.

@wilrnh I don't think the answer to the question is correct, VS Code does not touch xterm or Terminal.app, it launches bash and then communicates with [xterm.js](https://github.com/sourcelair/xterm.js) (an xterm emulator for the web). I would expect the `scrollback` setting in xterm.js to override any shell's scrollback, as that's the thing that holds onto the data: https://github.com/sourcelair/xterm.js/blob/269540bfedc9fc4b160d75d15e54a2e07854f7e5/src/xterm.js#L340

I've certainly hit the 1000 line limit on Linux as it's frustratingly small for me sometimes. I think you're also seeing the performance issues with xterm.js, unrelated to scrollback https://github.com/sourcelair/xterm.js/issues/280 https://github.com/sourcelair/xterm.js/issues/150 https://github.com/sourcelair/xterm.js/issues/134 - the issues here are to do with how the text is rendered and how the scrolling is implemented.

Let me know if you think I'm wrong but I'm going to close this in favor of https://github.com/Microsoft/vscode/issues/11805

**Comment by wilrnh** [comment]
I think you're right. I think `"terminal.external.osxExec": "Terminal.app",` probably confused me. Its obviously for the external, not internal terminal.

I'm not convinced the scrollback settings in Terminal.app settings are insignificant here though. I just switched it back on to full (make full use of memory) and I can definitely see the memory starting to jump on my machine. However like you said this could be due to some other unrelated issue than scrollback buffer lengths eg rendering or even something in my local system configuration.

One thing I didn't mention is that i'm using tmux and oh-my-zsh. Not sure if thats relevant.

**Comment by Tyriar** [comment]
Yes I expect the memory to go nuts due to garbage collection being defered when it's creating and throwing out so many HTMLElements.
