### ISSUE TITLE
Can't sign in with GitHub.

### ISSUE THREAD

**Issue by biswasmoheshwar** [microsoft/vscode#143292]
Does this issue occur when all extensions are disabled?: Yes

VS Code Version: 1.64.2 (user setup)
OS Ver: Windows_NT x64 10.0.22000
Steps to Reproduce:

1. Click Source Control.
2. Click Publish Branch.
3. Click Continue.
4. Click Authorize.
5. Click Ok.
6. Click Yes.

Then nothing happens signing into github.com is gone too.

**Comment by lszomoru** [comment]
@TylerLeonhardt, possible issue with GitHub auth?

**Comment by TylerLeonhardt** [comment]
Can you follow these steps so that we can get more information on what's going on?

* Open the Output pane (ctrl+shift+u I think on Windows)
* Choose `GitHub Authentication` from the drop down on the right
* drop in this issue the contents of it (the logs)

**Comment by biswasmoheshwar** [comment]
The issue have been fixed now.
