### ISSUE TITLE
Markdown preview: pipe character inside code span element in a table generates new column

### ISSUE THREAD

**Issue by ikozak** [microsoft/vscode#143218]
We have written the needed data into your clipboard because it was too large to send. Please 
Issue Type: <b>Bug</b>

Pipe in code span element in a table is not interpreted as a code, but it is used to add another column
![image](https://user-images.githubusercontent.com/7537867/154313683-6313375f-c07f-4bf3-8563-1cba067481bc.png)
renders as:

| col1 | col2 | col3 |
| --- | --- | --- |
| `text | text1` | text2 |

should look more like this:
![image](https://user-images.githubusercontent.com/7537867/154313963-cb5e7f2a-8cca-476b-9324-e45c4890b322.png)

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.62GB (0.06GB free)|
|Process Argv|--crash-reporter-id de1d012b-81fb-46d4-af3e-c5cff2ca357a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.46.0
xml|Dot|2.5.1
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.1
team|ms-|1.161.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30438341
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
pythonvspyt640:30436486
vsbas813:30436447
vscscmwlcmt:30438805
helix:30438806
vscaac:30438847

```

</details>

paste.

**Comment by mjbvz** [comment]
See https://github.com/markdown-it/markdown-it/issues/808

The current rendering matches GitHub's rendering and [markdown-it's](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%7C%20col1%20%7C%20col2%20%7C%20col3%20%7C%5Cn%7C%20---%20%7C%20---%20%7C%20---%20%7C%5Cn%7C%20%60text%20%7C%20text1%60%20%7C%20text2%20%7C%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)
