### ISSUE TITLE
[html] A 'return' statement can only be used within a function body

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#143220]
Does this issue occur when all extensions are disabled?: Yes/No

Yes.

- VS Code Version: 1.65.0-insider
- OS Version: MacOs 12.2.1

Steps to Reproduce:

1. create new HTML file
2. paste following code

```HTML
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Hammer Explorer</title>
    </head>
    <body oncontextmenu="return false;">
    </body>
</html>
```

<img width="937" alt="image" src="https://user-images.githubusercontent.com/41773861/154317704-9e916159-e2b6-494b-a830-3186afddc075.png">

**Comment by lramos15** [comment]
That's not a valid javascript function to be used for the callback. You can see similar docs here https://www.w3schools.com/tags/ev_oncontextmenu.asp

**Comment by tjx666** [comment]
@lramos15 https://stackoverflow.com/a/16987533/11027903

I know it isn't a valid function. But It indeed works to forbidden event handler.

**Comment by lramos15** [comment]
@tjx666 Ah yes this is a weird edge case of the spec https://www.w3.org/TR/2017/REC-html52-20171214/webappapis.html#the-event-handler-processing-algorithm.

Functions which return false don't work but just the string literal `return false;` seems to.

**Comment by crymic** [comment]
Yeah I just noticed all of javascript now is erroring out in VS Code cause of the `return`.
Any temporary fixes to just have it ignore return on problems?

**Comment by DanielTOsborne** [comment]
I just turned off the HTML setting to validate embedded scripts.

For those that don't want to wait for a fix, the setting to turn this off is `html.validate.scripts`.

I couldn't stand the errors in all my HTML files, and the 100+ in the project.
At least for me, actual embedded scripts are nearly non-existent in my project, aside from the element event handlers.

**Comment by RyanHeid** [comment]
> I just turned off the HTML setting to validate embedded scripts.
> 
> For those that don't want to wait for a fix, the setting to turn this off is `html.validate.scripts`.
> 
> I couldn't stand the errors in all my HTML files, and the 100+ in the project. At least for me, actual embedded scripts are nearly non-existent in my project, aside from the element event handlers.

I'm having the same problem right now. Sorry, I am a newb to coding. How do I turn this off? You said 'html.validate.scripts'. I'm using VS code, and don't know where to find that. Thanks!

**Comment by crymic** [comment]
I tried this too, still shows the same error.

**Comment by tjx666** [comment]
Verified in latest insider:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/160227602-514e0679-8c14-4488-a76c-67a845779943.png">

**Comment by tjx666** [comment]
Oprn settings by shortcut `cmd + ,`, and search that setting @RyanHeid

**Comment by RyanHeid** [comment]
I found it, and it solved my issue. Thank you so much! @tjx666

**Comment by crymic** [comment]
I am working in javascript exclusively and this is still an issue.
`html.validate.scripts` on or off does nothing. It still shows it's an error.

**Comment by aeschli** [comment]
@crymic Please file a new issue with 
- the vs code version you are using
- a small code sample
- information which language the editor is in (status bar, lower right)

**Comment by DanielTOsborne** [comment]
> I am working in javascript exclusively and this is still an issue. `html.validate.scripts` on or off does nothing. It still shows it's an error.

The specific setting I mentioned is only for HTML pages. If you are editing .js files, then it won't work. There's a separate setting for that, but it will disable all javascript validation, and probably not what you want.
Wait for the official fix when it comes out.
