### ISSUE TITLE
Typescript language service keeps dying

### ISSUE THREAD

**Issue by BoilerTom90** [microsoft/vscode#143283]
I'm not doing anything special. I just noticed a popup in the lower-right corner telling me the typescript language service keeps dying. Something like 5 times in a row...

**Comment by danvervlad** [comment]
![image](https://user-images.githubusercontent.com/32311513/155109494-ad50818e-c96a-4038-941f-232ff7f7ae66.png)
![image](https://user-images.githubusercontent.com/32311513/155110095-5567ca60-1a52-4ef4-9a6b-8f5543f23eb1.png)
![image](https://user-images.githubusercontent.com/32311513/155110193-8e009cd0-102c-44cc-8e9a-62872ee7628c.png)
![image](https://user-images.githubusercontent.com/32311513/155110284-83a197a0-2f71-4c54-976e-e4e88e994e8f.png)

The same here. After opening random file (~600 lines) in my TS repository - there are no full syntax highlight, go to definition doesn't work and this popup is shown.

**Comment by mjbvz** [comment]
Closing as we need information from the original poster to investigate this
