### ISSUE TITLE
Wishing you all a happy new year!   A long-requested feature has been left unfinished, hopefully it will be resolved in the next milestone.

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#143247]
Wishing you all a happy new year! A long-requested feature has been left unfinished, hopefully it will be resolved in the next milestone.

VS Code Version: 1.64
OS Version: Windows 10
Steps to Reproduce:

Hello, teacher!
Wishing you all a happy new year! A long-requested feature has been left unfinished, hopefully it will be resolved in the next milestone. Thank you here!
https://github.com/microsoft/vscode/issues/134326
https://github.com/microsoft/vscode/issues/138457
https://github.com/microsoft/vscode/issues/132756
https://github.com/microsoft/vscode/issues/141621
Hope to fix them in the next milestone, thank you so much teachers!
vscode contributors

**Comment by weinand** [comment]
Please don't waste our time by creating issues with links existing issues.
