### ISSUE TITLE
Feature request: Per-keystroke audio cue for multiple cursors

### ISSUE THREAD

**Issue by bland328** [microsoft/vscode#143246]
I suggest/request the ability to turn on a per-keystroke audio cue when typing/deleting with multiple cursors active.

I see value both as an accessibility feature and as a bonus for people like me who occasionally lose track of the fact that multiple cursors are active--especially when all but one are off-screen.

I imagine it such that that only actual edits would generate the per-keystroke audio cue, and not cursor movement.

**Comment by hediet** [comment]
@isidorn FYI

**Comment by isidorn** [comment]
Not a bad idea. Let's keep this in the back of our heads and if more users request it we might reopen it. Though I do agree nothing for now and closing is fine. Thanks for the ping.
