### ISSUE TITLE
IntelliSense stops working after npm install

### ISSUE THREAD

**Issue by johnlahut** [microsoft/vscode#143228]
After doing an `npm install`, all IntelliSense stops working in VS Code. All tooltips on hover just display "Loading..." forever. On first launch after restarting VS Code, I can hover over definitions and the tooltips will partially load for just a second. After that they are stuck in the "Loading..." state.

I cannot cmd + click to jump to any code. 

If I delete my `node_modules` directory, the application behaves as normal. Once I reinstall all dependencies, it breaks. I did not recently add a new dependency.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64 Stable, 1.65 Insider
- OS Version: macOS 12.0.1

Steps to Reproduce:

1. `npm install` 
2. All IntelliSense stops working in VS Code.

If it helps this is a React TypeScript project.

**Comment by mjbvz** [comment]
Can you please share a small project that demonstrates this issue?

**Comment by bwyx** [comment]
ran into this issue too
i think it tsserver issue, it's hogging my cpu all the time

**Comment by bwyx** [comment]
ran into this issue too
i think it's tsserver issue, it's hogging my cpu all the time

**Comment by johnlahut** [comment]
I figured out the cause of the problem yesterday, but not sure the root of it.

I am using `@mui` for our component library. I was trying to extend `SxProps` for one of my components. 

For some reason importing `SxProps` from `@mui` causes the entire editor to become slow and IntelliSense to stop working. I observed similar slowness with Atom as well after the import. I could not cmd + click to jump in either editor after this import.

The import in my code:
`import { SxProps } from "@mui/material"`

I decided not to use that type in the code, so my editor is working again.

**Comment by mjbvz** [comment]
@johnlahut Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If so, can you share a small project that demonstrates the issue?
