### ISSUE TITLE
unable to load static files

### ISSUE THREAD

**Issue by amrendra22** [microsoft/vscode#143231]
We have written the needed data into your clipboard because it was too large to send. Please paste
![Screenshot (405)](https://user-images.githubusercontent.com/97384915/154337142-d7671b63-1320-41a2-87b8-7534decdaa71.png)
.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please specify how exactly this is related to VS Code editor itself?
If you are using some extension to provide live server - issue should be reported in extension's repo.
