### ISSUE TITLE
Visible whitespace disappears when `editor.renderIndentGuides` is true

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#14326]
- VSCode Version: `Version 1.7.0-insider (1.7.0-insider)` c038219f8d137b4972a15346b81ea03751d669d4
- OS Version: `macOS Sierra 10.12 (16A323)`

Steps to Reproduce:
1. Set `"editor.renderWhitespace": "boundary"` and `"editor.renderIndentGuides": true`
2. Open a TypeScript file (haven't tried others
3. Only the indent guides are visible

Although if you toggle those settings while the file is opened it will render properly.

**Comment by alexandrudima** [comment]
@eamodio I tried with the following user-level settings.json:
```json
"editor.renderWhitespace": "boundary"
, "editor.renderIndentGuides": true
```

in a folder without any other settings and without any extensions and I cannot reproduce.

Is there something more to it? Can you repro with `code --disable-extensions`?

**Comment by eamodio** [comment]
@alexandrudima I can no longer reproduce with on 1.7 or 1.8
