### ISSUE TITLE
Auto-Expand/Collapse Windows Breaks

### ISSUE THREAD

**Issue by BrianPittVP** [microsoft/vscode#143299]
Issue Type: <b>Bug</b>

If you split your main view horizontally, so you have 2 files open, one above the other, and drag the divider all the way to the bottom, VS Code seems to understand that you want that minimized until it is accessed.  If you click a file tab in the minimized frame, that frame maximizes.  It's rather cool!

The problem is, if you have something minimized at the bottom and you open a panel that comes up from the bottom (i.e. Console), then close that panel, the bottom frame is no longer fully minimized and the auto-min/max doesn't work anymore until you drag the divider back down.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-1128-aws

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.3
remote-ssh|ms-|0.74.0
remote-ssh-edit|ms-|0.74.0
vscode-intelephense-client|bme|1.8.1
githistory|don|0.6.19
xml|Dot|2.5.1
php-docblocker|nei|2.7.0
vscode-php-getters-setters|php|1.2.3
vscode-xml|red|0.19.1
php-debug|xde|1.24.0
php-pack|xde|1.0.3
local-history|xyz|1.8.1

</details>

**Comment by sbatten** [comment]
likely the same cause as https://github.com/microsoft/vscode/issues/70083
