### ISSUE TITLE
Unable to use User Snippet for HTML code

### ISSUE THREAD

**Issue by 3035782126** [microsoft/vscode#143256]
Issue Type: <b>Bug</b>

I am trying to add a user snippet with language snippet scope of HTML using the built-in User Snippet function inside VScode but somehow it is not showing up by typing the relevant prefix in HTML files. I have checked multiple times and could not figure out where is the problem. Can anyone help me look at what the problem is?
Thanks in advance. Below is the code in my html.json:

{
	// Place your snippets for html here. Each snippet is defined under a snippet name and has a prefix, body and 
    // description. The prefix is what is used to trigger the snippet and the body will be expanded and inserted. Possible variables are:
    // $1, $2 for tab stops, $0 for the final cursor position, and ${1:label}, ${2:another} for placeholders. Placeholders with the 
    // same ids are connected.
    // Example:
    // "Print to console": {
    //  "prefix": "log",
    //  "body": [
    //      "console.log('$1');",
    //      "$2"
    //  ],
    //  "description": "Log output to console"
    // }

    "Django Tutorial: template extending layout.html": {
        "prefix": "djextlayout",
        "body": [
            "{% extends \"hello/layout.html\" %}",
            "{% block title %}",
            "$0",
            "{% endblock %}",
            "{% block content %}",
            "{% endblock %}"
        ],
        
        "description": "Boilerplate template that extends layout.html"
    },   
}

**Comment by aouos** [comment]
What is your html snippet,you can try [snippet generator](https://snippet-generator.app/)

**Comment by 3035782126** [comment]
Oh here is my html snippet that is in my html.json file:
`{
	// Place your snippets for html here. Each snippet is defined under a snippet name and has a prefix, body and 
    // description. The prefix is what is used to trigger the snippet and the body will be expanded and inserted. Possible variables are:
    // $1, $2 for tab stops, $0 for the final cursor position, and ${1:label}, ${2:another} for placeholders. Placeholders with the 
    // same ids are connected.
    // Example:
    // "Print to console": {
    //  "prefix": "log",
    //  "body": [
    //      "console.log('$1');",
    //      "$2"
    //  ],
    //  "description": "Log output to console"
    // }

    "Django Tutorial: template extending layout.html": {
        "prefix": "djextlayout",
        "body": [
        "{% extends \"hello/layout.html\" %}",
        "{% block title %}",
        "$0",
        "{% endblock %}",
        "{% block content %}",
        "{% endblock %}"
        ],
        
        "description": "Boilerplate template that extends layout.html"
        },     
}`

**Comment by 3035782126** [comment]
Here is the html snippet that I used in my html.json file for user snippets:
`{

    "Django Tutorial: template extending layout.html": {
        "prefix": "djextlayout",
        "body": [
        "{% extends \"hello/layout.html\" %}",
        "{% block title %}",
        "$0",
        "{% endblock %}",
        "{% block content %}",
        "{% endblock %}"
        ],
        
        "description": "Boilerplate template that extends layout.html"
        },     
}`
