### ISSUE TITLE
vscode does not start anymore on Windows - no window, no clue

### ISSUE THREAD

**Issue by djey47** [microsoft/vscode#143275]
Does this issue occur when all extensions are disabled?: YES - vscode can't start at all

- VS Code Version: 1.64.1, 1.64.2, ZIP file install
- OS Version: W10 - 1909

Steps to Reproduce:

1. Extract portable Windows' vscode ZIP to any user directory
2. Run code.exe from either explorer, cmd, or git bash
3. Wait for a couple of seconds, nothing happens

- Does work well with 1.64.0, or 1.65.0-insider but NOT 1.64.1, 1.64.2
- There's no remaining code.exe process running afterwards
- Running in terminal with --verbose switch has no effect.
- Exit code  (%errorlevel% var) is 0, when launching from git bash ($? var) is 3...
- No application logs written at all
- I have sadly no access to Windows event log as I have restricted privileges onto this PC.

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/"needs-more-info"

**Comment by djey47** [comment]
Here are my settings : https://gist.github.com/djey47/6fe6a50cd390adbd9e79e242c1879b7f

Issue with trace logging is I'm not getting anything in AppData\Roaming\Code\logs directory : to be sure I've deleted all logs before starting vscode. (`code --log trace`).

**Comment by djey47** [comment]
Issue solved with newest 1.65.0 as expected. Thanks for your support.
