### ISSUE TITLE
tsconfig.json falsely processed

### ISSUE THREAD

**Issue by klocke** [Microsoft/vscode#14322]
- VSCode Version: 1.6.1
- OS Version: OS X El Capitan 10.11.5

Steps to Reproduce:

1. Install [Yeoman Office-Generator](https://code.visualstudio.com/Docs/runtimes/office) and generate a project.
2. Run "tsd install" from project folder (alternatively use typings).
3. Test IntelliSense in VS Code by typing "Office." in "home.js" f.e.
4. Set allowJs in tsconfig.json to true => Now it should work.

allowJs in tsconfig.json should be true by default (according to [the doc](https://www.typescriptlang.org/docs/handbook/compiler-options.html)). So I guess it´s a bug that VS Code does not allowJS by default.

**Comment by waderyan** [comment]
@klocke thank you for opening this issue. 

@dbaeumer any idea why this would happen? Does VS Code change the defaults of the config file? Would seem that we would not.

**Comment by dbaeumer** [comment]
@waderyan no we don't. What has changed in 1.6.1 is that we ship TS 2.0.3. May be something changed in the tsserver. Can you check with @mhegazy

**Comment by mhegazy** [comment]
`--allowjs` is false by default this is a documentation bug. I have merged in a fix for it.
