### ISSUE TITLE
"Allow automatic tasks in folder" prompt never appears

### ISSUE THREAD

**Issue by alandonpk** [microsoft/vscode#143298]
Issue Type: <b>Bug</b>

1. Clone a Git repo containing tasks.json where one of the tasks has 
```
"runOptions": {
    "runOn": "folderOpen"
  }
```
2. File -> Open Folder
3. Open the just-cloned repo
4. There is no prompt to allow automatic tasks in folder, nor any other visible indication that there are automatic tasks in this project for the user to enable

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (17.85GB free)|
|Process Argv|--crash-reporter-id 3b8e0853-c466-44d0-aaad-3f4daf14ad25|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.34.0
flutter|Dar|3.34.0
gitlens|eam|11.7.0
bloc|Fel|6.5.0
remotehub|Git|0.24.0
go|gol|0.31.1
pubspec-assist|jer|2.3.2
gitpatch|par|0.2.1
java|red|1.3.0
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30438341
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30440023
vsbas813:30436447
vscscmwlcmt:30438805
helixcf:30438807

```

</details>

**Comment by alandonpk** [comment]
Our use case for automatic tasks is to enforce coding standards across the team. This issue makes the automatic task feature unusable for that purpose. Getting everyone to enable an invisible setting for every project is a coordination problem on the same order of complexity as getting them all to code to standards in the first place.

**Comment by alexr00** [comment]
We don't show the automatic tasks notification until you run a task. This is to prevent notification spam on startup, when there are often many notifications that are all ignored. 

You can manually enable automatic tasks for a folder by running the command "Tasks: Manage Automatic Tasks in Folder".
