### ISSUE TITLE
command decoration hover should not show when the context menu is open

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#143221]
![Recording 2022-02-16 at 11 06 25](https://user-images.githubusercontent.com/29464607/154318069-d019c749-d12a-4907-bdb8-3c8c6cec6e45.gif)

the hover is a little annoying and obscures the terminal a bit too much IMO when the menu is open. @tyriar thoughts?

**Comment by Tyriar** [comment]
Let's hide the hover/cancel the timer when opening the context menu
