### ISSUE TITLE
Box overlaps single-line cells

### ISSUE THREAD

**Issue by ghylander** [microsoft/vscode#143213]
Issue Type: <b>Bug</b>

When creating a code cell, the box with the "Run by line, execute all above, etc" options overlaps the cell, covering the line number (if enabled) and approximately the first 16-20 characters

If you create a new line in the cell, the box moves to its usual spot

Extension version: 2022.2.1010480428
VS Code version: Code - Insiders 1.65.0-insider (52e65499654de7525e30df3a8228b69320796bf5, 2022-02-16T05:16:18.653Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.70GB (2.04GB free)|
|Process Argv|--crash-reporter-id 4285aea8-8024-49ba-97f2-9d60622a70f0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|Memory (System)|5.65GB (4.02GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|Memory (System)|5.65GB (4.02GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstartedc:30421358
vsclayoutctrc:30405799
dsvsc008:30436272
pythonvspyt640:30438691
vsbas813:30436447
vscscmwlcmt:30428973
azactmsalcf:30432849
vscgsvidc:30433759
dockersurvey3:30438168

```

</details>

**Comment by roblourens** [comment]
Fixed in 9bf9403e9a8d28f715dc992c2d3290e12476c7f7, thanks
