### ISSUE TITLE
Get current file hierarchy (outline)?

### ISSUE THREAD

**Issue by foobar-translate** [microsoft/vscode#143209]
On VSCode API, I believe there is no way to get the file structure hierarchy (the outline), correct? 

For example, let's say I have a markdown file opened, I want to get the structure, token, parsed result in any form of the document, so I can pass the data to my extension program (and render on the Treeview for example). 

I googled some and found a issue on Github such as [this](https://github.com/Microsoft/vscode/issues/66990), or SO posts such as [this](https://stackoverflow.com/questions/55846146/make-vs-code-parse-and-display-the-structure-of-a-new-language-to-the-outline-re), according to my research I could use something like `vscode.DocumentSymbol.children`, but this code doesn't show an output. (I could expect this since I just tried to run to see if it works by chance) 

So is it possible to implement this feature for the API? Thanks.

**Comment by gjsjohnmurray** [comment]
Maybe `vscode.executeDocumentSymbolProvider` (see https://code.visualstudio.com/api/references/commands#commands)

**Comment by jrieken** [comment]
The API commands allow you access the model that VS Code UX uses, but the syntax tree of the language in question. VS Code doesn't help with detailed language/syntax information for usage outside of the UC. If you need that you have to see if the corresponding extension exposes an API or use your own parser
