### ISSUE TITLE
New predefined variable: OS dependent environment variable path list separator

### ISSUE THREAD

**Issue by gschwaer** [microsoft/vscode#143289]
## Problem
When specifying environment variables that contain multiple paths (e.g., `PATH`, `PYTHONPATH`) the list separator is OS dependent. 

On Windows you do
```cmd
SET VAR="some\path;some\other\path"
```
and on POSIX compliant OS (e.g. Linux) you do
```bash
VAR="some/path:some/other/path"
```
(note the different list separator `;` and `:`)

In vscode configs you would use something like:
```jsonc
"env": {
    // works on Windows:
    "VAR": "some${pathSeparator}path;some${pathSeparator}other${pathSeparator}path"
    // works on Linux:
    "VAR": "some${pathSeparator}path:some${pathSeparator}other${pathSeparator}path"
}
```

## Request
Add a new [predefined variable](https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables) (maybe `${pathListSeparator}`?) that contains this symbol to make `launch.json`/`settings.json`/`tasks.json` more sharable between OS.

## FWIW
This problem ist also described [here](https://code.visualstudio.com/docs/python/environments#_use-of-the-pythonpath-variable), but no solution is provided other than the advice to make sure and use the right symbol depending on your OS.

**Comment by weinand** [comment]
@gschwaer I understand the need for this but I see two issues:
- finding a good name since `${pathSeparator}` is already used with a different semantic,
- paths using both variables are really hard to read and error prone:
   ```
   "VAR": "some${pathSeparator}path${AltPathSeperator}some${pathSeparator}other${pathSeparator}path"
   ```

I suggest to use OS-specific sections:
```
"windows": {
    "env": {
        "VAR": "some\\path;some\\other\\path"
    }
},
"linux": {
    "env": {
        "VAR": "some/path:some/other/path"
    }
}
```
