### ISSUE TITLE
Hello, teacher! VSCode is a great project that gives users the greatest autonomy from the very beginning, allowing users to personalize configurations according to their own habits, so it can fully surpass the long-born jetbrion series in just 5 years. The most important reason is that VSCode's open source thinking and allowing users to customize and configure VSCode development methods to the greatest extent can achieve today's achievements. I hope VSCode can continue to develop this way of thinking and development, focusing on every reasonable request of users and need. Thank you here! vscode contributors 20220217

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#143204]
Hello, teacher! VSCode is a great project that gives users the greatest autonomy from the very beginning, allowing users to personalize configurations according to their own habits, so it can fully surpass the long-born jetbrion series in just 5 years. The most important reason is that VSCode's open source thinking and allowing users to customize and configure VSCode development methods to the greatest extent can achieve today's achievements. I hope VSCode can continue to develop this way of thinking and development, focusing on every reasonable request of users and need. Thank you here! vscode contributors 20220217

VS Code Version: 1.64
OS Version: Windows 10
Steps to Reproduce:

Hello, teacher!
VSCode is a great project that gives users the greatest autonomy from the very beginning, allowing users to personalize configurations according to their own habits, so it can fully surpass the long-born jetbrion series in just 5 years. The most important reason is that VSCode's open source thinking and allowing users to customize and configure VSCode development methods to the greatest extent can achieve today's achievements. I hope VSCode can continue to develop this way of thinking and development, focusing on every reasonable request of users and need. Thank you here!
https://github.com/microsoft/vscode/issues/134326
https://github.com/microsoft/vscode/issues/138457
https://github.com/microsoft/vscode/issues/132756
https://github.com/microsoft/vscode/issues/141621
Hope to fix them in the next milestone, thank you so much teachers!
vscode contributors

**Comment by alexdima** [comment]
Thank you for your kind words!

**Comment by zhouxinghong** [comment]
> 感谢您的客气话！

Why not accept it? And always close it?
