### ISSUE TITLE
Select All Occurrences keyboard shortcut stops working when the Find dialog is open

### ISSUE THREAD

**Issue by alexqfredrickson** [microsoft/vscode#143225]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.2
- OS Version: MacOS

Steps to Reproduce:

1. Open an editor and paste this text in:

    amzn2-core-debuginfo/2/x86_64             Amazon Linux 2 cor disabled
    amzn2-core-source/2                       Amazon Linux 2 cor disabled

2. `Command+F` to find all occurrences of 'amzn2'.
3. `Command+Shift+L` doesn't simultaneously select all occurrences of 'amzn2'.
4. Press escape to exit the find prompt.
5. Manually highlight an occurrence of 'amzn2'.
6. `Command+Shift+L` now simultaneously selects all occurrences of 'amzn2'.

It's not obvious that this behavior should change depending on whether or not the find window is open.  I'd bet that the most common use-case for the "find" feature is that a user wants to do a "find and replace".  It doesn't make sense that you have to exit the find dialog and manually highlight a word to do a find and replace. It's a really jarring disruption.

**Comment by ArturoDent** [comment]
<kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>L</kbd> `Select All Occurrences of Find Match has a context key of `editorFocus`.  That is why in your second case with focus in the editor that it works as you expect.

You can use <kbd>Alt</kbd>+<kbd>Enter</kbd> to select all the find matches with focus still in the Find Widget.

**Comment by alexqfredrickson** [comment]
> Cmd+Shift+L `Select All Occurrences of Find Match` has a context key of `editorFocus`. That is why in your second case with focus in the editor that it works as you expect.
> 
> You can use Alt+Enter to select all the find matches with focus still in the Find Widget.

I'm glad this can be accomplished from the find window - but I'm surprised that a different set of shortcuts are required altogether.  This could be made more user-friendly if the same shortcuts could be used in both the `editorFocus` and `Find Widget` contexts.  The need to remember multiple shortcuts is confusing for a lot of people, including myself (see https://stackoverflow.com/questions/46539714/select-all-occurrences-of-selected-word-in-vscode).

**Comment by amunger** [comment]
seems to work now
