### ISSUE TITLE
Large minified JavaScript files cause VSCode to lockup and then crash

### ISSUE THREAD

**Issue by Zarrey** [Microsoft/vscode#14325]
- VSCode Version: 1.6.1
- OS Version: Windows 10

Steps to Reproduce:
1.  Open a very large minified JavaScript file in vscode, like that of wordpress.  More than 30,000 characters over about 400-500 lines.  Sometimes it doesn't lock up right away, but after a few minutes it does.  I have had instances where it kept locking up immediately after opening the file.  I have had to use notepad++ in order to edit these files.

Note: Trying to save this file doesn't work, no matter how many times I click save.

This is the dialog I am presented with after being in the file for a few minutes or trying to save.

![image](https://cloud.githubusercontent.com/assets/7989333/19663708/26d5b73c-9a0b-11e6-85bd-5864146ff62d.png)

**Comment by alexandrudima** [comment]
@Zarrey Can you please point me to the file or a similar file that causes the freeze?

I just downloaded wordpress from https://wordpress.org/download/ and I got tired of clicking on random js files.

**Comment by alexandrudima** [comment]
Closing after a number of days without a response
