### ISSUE TITLE
CSS file not integrating with HTML file

### ISSUE THREAD

**Issue by nyeakky** [microsoft/vscode#143200]
Issue Type: <b>Bug</b>

I have my code files(html and css) saved in same folder, yet onload via a web browser, only the html is executed without the css styles. 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by aeschli** [comment]
How is VS Code related to that?

**Comment by nyeakky** [comment]
Am using Visual Studio to write my codes

**Comment by aeschli** [comment]
Please give more information, the code samples and detailed steps (including screenshots) that show that there's a bug in VS Code and not your code or the browser.

**Comment by nyeakky** [comment]
> Please give more information, the code samples and detailed steps (including screenshots) that show that there's a bug in VS Code and not your code or the browser.

I reviewed my code again, and I found I did this

<link rel="stylesheet" href="styles.css" type="txt/css">

Thats where i found the error

Now i changed "txt" to "text", and it have started working properly. Thank you @aeschli for your contribution
