### ISSUE TITLE
Git operations still frequently freeze - please add even better logging!

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode#143279]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.1
- OS Version: Mac something. Remote is CentOS.

This is a follow-up of #138743. Basically when using the remote SSH extension to connect to a *reasonably* heavily loaded machine, Git operations can take ages. I can't figure out why. Running the same commands in the Git Output window but in the terminal they seem to run much faster.

Since command duration was added (#138168) I can now see that it's something in-between the measured times that is slow. For example see this log:

```
[2022-02-17T11:07:22.569Z] > git ls-tree -l HEAD -- /path/to/foo.py [11ms]
[2022-02-17T11:07:45.787Z] > git ls-files --stage -- /path/to/foo.py [17ms]
```

I stopped interacting with the UI *before* the first command, and each command executed quickly, yet there was a massive 23 second wait between them while the UI just shows progress bars. My network connection is pretty good so I feel like there's something else going on.

Is there any chance of adding even more logging? How does the local GUI actually communicate with the remote Git extension?

**Comment by Timmmm** [comment]
I haven't actually seen this for a while now so it seems like something accidentally fixed it.

**Comment by lszomoru** [comment]
@Timmmm, thank you very much for the update. Please feel free to re-open the issue in case you run into this again.
