### ISSUE TITLE
Makefile syntax highlighting incorrectly highlights string as comment

### ISSUE THREAD

**Issue by SethFalco** [microsoft/vscode#143272]
Does this issue occur when all extensions are disabled?: Yes

VS Code:
```
Version: 1.65.0-insider
Commit: 50089c3f92c17584a4aca179f51f220b56c22020
Date: 2022-02-14T05:19:23.146Z
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Linux x64 5.10.0-11-amd64 snap
```

OS: Debian 11

Steps to Reproduce:

1. Open or create a Makefile in Visual Studio Code
2. Insert a string wrapped in quotes that contains a `#`.

For example:
```mk
PASSWORD='jF$rbr*b9uRuTxsUdSH38jo5wcAYQXp3fn7#uU^3BJUGEeycV4ziS*h7V&m6bh^VKN24Q^&rF'
```

Everything after the `#` is highlighting as a comment, but this is actually part of the string. (Wrapped in `'` to avoid any processing in bash due to special characters like `$`.)

**Comment by alexr00** [comment]
Opened an issue in the upstream repository that we get our makefile syntax highlighting grammar from https://github.com/fadeevab/make.tmbundle/issues/14
