### ISSUE TITLE
Product needs to be renamed to remove "visual studio" from name to make web searches more meaningful.

### ISSUE THREAD

**Issue by souptown** [Microsoft/vscode#14324]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:
1. Search for visual studio code
2. See the noise

**Comment by chrisdias** [comment]
Hi @souptown,

We've discussed this a bunch of times (#2150, #2722) but I think we're too far down the road to change the name at this point. We find a search for "VSCode" works quite well, hopefully that will work for you.

Thanks for taking the time to submit the suggestion, even though I'm closing this one, please do keep the suggestions coming in.

Chris
