### ISSUE TITLE
Add Folder to Workspace Hanging

### ISSUE THREAD

**Issue by ralph-dev** [microsoft/vscode#143296]
Issue Type: <b>Bug</b>

This is on a Macbook M1 Pro (ARM), the issue must be due to the File Dialog Hanging or Visual Studio Code never sending the request through. This issue has happened before and I always do the same steps to resolve it/

1) Open Project A
2) Add Project B to Workspace
3) Make some Changes to Project A
4) Attempt to Add Project C to Workspace 

Current Broken Behaviour: (Dialog Never Opens)

Expected Behaviour: File Selector Dialog should open to add a new folder to the workspace.

Current Resolution: Quit Visual Studio Code and Re-Create the Workspace by adding the folders at the beginning of the VSC Session

VS Code version: Code 1.64.2 (Universal) (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|18, 18, 17|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 2a765c2f-e2ef-40d5-85f9-b32867fb30f2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.1
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.2.0
vscode-jest-runner|fir|0.4.47
copilot|Git|1.7.5067
vscode-styled-components|jpo|1.6.6
vscode-docker|ms-|1.19.0
remote-containers|ms-|0.217.4
angular-console|nrw|17.14.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30438341
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc009:30440023
pythonvsnew555cf:30436485
vsbas813:30436447
vscscmwlcmt:30438805
helixcf:30438807

```

</details>

**Comment by bpasero** [comment]
Thanks

**Comment by ralph-dev** [comment]
Closing until I can record a video of this issue then I will open it again.
