### ISSUE TITLE
How do I change the default cell width of a notebook ?

### ISSUE THREAD

**Issue by neel6762** [microsoft/vscode#143208]
I am so used to the Jupyter Notebook on the browser and the padding that they have, that I feel VSCode's Jupyter Notebook cells are so wide. I was wondering if there is any way that I can reduce the width of the cell. Simply, how to get additional padding on both sides.

**The current cell looks like this** 
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/38160394/154195517-47ad0f5a-eb6e-4733-90b5-3266c1230d75.png">

**I would prefer something like the following (the color theme in VSCode is fine for me)**
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/38160394/154195854-a77921a4-2af9-4431-b6f5-75dc44bff49d.png">

Thank you!

**Comment by bergwerf** [comment]
Use `View > Appearance > Centered layout` to make the notebook area width adjustable.

**Comment by neel6762** [comment]
> Use `View > Appearance > Centered layout` to make the notebook area width adjustable.

Thank you so much!
