### ISSUE TITLE
Have command decorations use same red as scm decorations

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#143205]
![image](https://user-images.githubusercontent.com/2193314/154294846-d6573d7e-5aa5-4429-8886-033658f9f071.png)

**Comment by Tyriar** [comment]
Actually the default is right, it's just really dark by default on Dark+. @misolori we should probably tweak for contrast?

![image](https://user-images.githubusercontent.com/2193314/154297686-ccfd0f47-c440-4616-a643-c2e75e980dac.png)

**Comment by Tyriar** [comment]
Also should we fallback to SCM colors so themes get the defaults if they're already set, or is that weird having terminal success/fail depend on scm added/deleted. It would be nice if we had some core colors for these sorts of common things so we could depend on platform/base instead of editor.

**Comment by meganrogge** [comment]
Is there some other styling impacting how it looks in the editor vs the terminal? The color looks quite different.

![Screen Shot 2022-02-16 at 10 19 54 AM](https://user-images.githubusercontent.com/29464607/154309084-1ad5b244-8962-476f-b808-adbb244524a0.png)

**Comment by Tyriar** [comment]
This is what I see in Dark+/Insiders:

![image](https://user-images.githubusercontent.com/2193314/154310182-962155b7-c503-4d2e-bc46-8d2626df2f68.png)

**Comment by meganrogge** [comment]
I think we're statically doing it at the moment - couldn't find where that code is located

**Comment by meganrogge** [comment]
think I found it

**Comment by misolori** [comment]
those are stored here:

https://github.com/microsoft/vscode/blob/17709700fc7f04b682b64c648bc98749469b5735/src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts#L851-L867

**Comment by meganrogge** [comment]
We should also decide if we want to show the "skipped" decoration, which color to use. Currently we use 

https://github.com/microsoft/vscode/blob/2ac67c722c98d768c2260ec5ff0fa9a8ce4d2848/src/vs/workbench/contrib/terminal/common/terminalColorRegistry.ts#L40-L44

**Comment by Tyriar** [comment]
@meganrogge oh we still want new terminal theme keys, just to fallback to the gutter colors, like this:

https://github.com/microsoft/vscode/blob/2ac67c722c98d768c2260ec5ff0fa9a8ce4d2848/src/vs/workbench/contrib/terminal/common/terminalColorRegistry.ts#L45-L49

**Comment by Tyriar** [comment]
WRT the layer breaker, let's copy the gutter colors directly into the new theme colors instead of referencing them as we want theme authors to have control over what they are. The long term fix here is having a set of base theme colors we can depend upon in common

**Comment by Tyriar** [comment]
We want the following:

- terminalCommandDecoration.defaultBackground (grey)
- terminalCommandDecoration.successBackground (blue)
- terminalCommandDecoration.errorBackground (red)

**Comment by Tyriar** [comment]
To verify ensure these theme keys work as expected:

```
terminalCommandDecoration.defaultBackground (grey)
terminalCommandDecoration.successBackground (blue)
terminalCommandDecoration.errorBackground (red)
```
