### ISSUE TITLE
Used variables get shown as unused sporadically

### ISSUE THREAD

**Issue by amks1** [microsoft/vscode#143266]
Issue Type: <b>Bug</b>

Everything works fine initially, but after moving a few times from one tab to another, used variables get greyed out as if they are unused. 
I'm on Python.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.80GB (14.60GB free)|
|Process Argv|--crash-reporter-id a9957413-6361-4f37-8c33-4f9b5cd34d7e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-sqlite|ale|0.14.0
strike-vscode|art|3.0.0
vscode-django|bat|1.9.0
python-preview|don|0.0.4
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.3.2
gitlens|eam|11.7.0
vscode-npm-script|eg2|0.3.24
json-tools|eri|1.0.2
pip-packages|etm|0.4.3
vscode-todo-plus|fab|4.18.4
copilot|Git|1.7.5003
gc-excelviewer|Gra|4.0.50
Untabify|ili|0.0.2
vscode-env|Iro|0.1.0
vscode-requirements|jan|0.1.0
MagicPython|mag|1.1.0
json|Mee|0.0.1
vscode-docker|ms-|1.19.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.3
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
autodocstring|njp|0.6.1
java|red|1.3.0
jinjahtml|sam|0.16.0
html5-boilerplate|sid|1.1.1
svg-preview|Sim|2.8.3
tabnine-vscode|Tab|3.5.25
vscode-counter|uct|3.0.3
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0
jinja|who|0.0.8
jinja2-snippet-kit|Wya|2.0.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30438340
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
vsbas813:30436447
vscscmwlcmc:30438804
helix:30438806

```

</details>

**Comment by IllusionMH** [comment]
/extPython

Python functionality provided by extension(s), so you should report this issue there first.
Also more details might be necessary about project, files, last actions
