### ISSUE TITLE
Sometimes layout broken via RDP connection

### ISSUE THREAD

**Issue by Victsz** [microsoft/vscode#143245]
After reconnected to my working desktop, the vs code window layout does not fit with my screen size and leaving a dark area. See the pic below.

![image](https://user-images.githubusercontent.com/8154646/154380572-14d3650c-210e-401a-a612-f8ce8152e79c.png)
And cursor focus miss-match...for example, to open the "file" menu , I have to click the dark area.
![image](https://user-images.githubusercontent.com/8154646/154380659-58284203-4a8f-47a4-87c1-a144d2e4b666.png)

![image](https://user-images.githubusercontent.com/8154646/154381173-4026550d-850e-4828-bce8-8a197bd91eb4.png)

Reload window command does not solve this problem. but close the window by "X" button and open again works.

**Comment by kuhlaid** [comment]
I'm having the same issue, but I'm thinking it is a problem with Electron apps in general. I have the same problem happen with Azure Data Studio (also Electron based) when working with these apps remotely via remote desktop connection and reconnecting. Restarting the app will resolve the issue but it is annoying to restart these apps after losing a remote desktop connection.

**Comment by Victsz** [comment]
The problem exists
