### ISSUE TITLE
wants API proposal 'commentTimestamp' but that proposal DOES NOT EXIST

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#143274]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.0-insider
- OS Version: MacOs12.2.1

Steps to Reproduce:

1. open devtools

![image](https://user-images.githubusercontent.com/41773861/154468527-93d7fbdd-73c6-4613-b5f4-ccf71ff9ee2c.png)

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/commit/a330b89e5d83293bacee75ac910626b64ad8c3fd

It is being finalized in this iteration.

**Comment by tjx666** [comment]
I use insider version for daily work. I think vscode insider version should not appear thease experiment and test info.

**Comment by alexr00** [comment]
The next (0.38.0) stable version of GitHub Pull Requests and issues will not cause this error. In the mean time, you can use the pre-release version of that extension if you want! https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build

**Comment by tjx666** [comment]
@alexr00 I didn't install that extension.

**Comment by alexr00** [comment]
@aeschli I think some extensions need to be removed from product.json files for the icons contribution points.

I removed the one for `commentTimestamp` earlier this week.

**Comment by aeschli** [comment]
Copilot wants to wait pushing a new version until 1.65 stable is out: https://github.com/github/copilot/issues/1759
