### ISSUE TITLE
Keypad Middle Key (non numlocked numberic centre key 5) producing "unknown"

### ISSUE THREAD

**Issue by AaronNGray** [microsoft/vscode#143239]
I am trying to create a BRIEF (Basic Reconfigurable Interactive Editting Facility) Keymap I would like the middle cursor (numeric 5) keypad key to produce a code I can use in keymap, but instead its producing "unknown".

In BRIEF the non numlocked numberic centre key 5, centres the window on the current line.

So an appropriate key name code would be ideal, just "Centre", or "CursorCentre" ? after KeyCode.PageDown, 'cursorPageDown' keycode.

**Comment by AaronNGray** [comment]
I am fetting KeyCode 12 being converted to KeyCode 0

```
 [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: Numpad5, keyCode: 12, key: Clear
[2022-02-16 23:22:50.079] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: Numpad5, keyCode: 0 ('unknown')
[2022-02-16 23:22:50.079] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
```

**Comment by AaronNGray** [comment]
ideally the ScanCode is assigned correctly and a new KeyCode.Clear is created and assigned.

**Comment by AaronNGray** [comment]
The keyboard code is a bit crazy and could really do with recoding for efficiency and simplification. All the obvious changes to the  keymap result in 'unknown' still. @[alexdima](https://github.com/alexdima) I think it really needs someone who knows this area well to solve this and maybe rewrite the keyboard code for efficicncies sake.

**Comment by AaronNGray** [comment]
I pulled the pull request https://github.com/microsoft/vscode/pull/143324 as it does not actually work yet.
The patch/pull request is not actually resulting in a key binding to it. I am getting 'No keybinding entries' :-
```
[2022-02-18 05:19:28.451] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: Numpad5, keyCode: 12, key: Clear
[2022-02-18 05:19:28.452] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: Numpad5, keyCode: 105 ('Clear')
[2022-02-18 05:19:28.459] [renderer1] [info] [KeybindingService]: | Resolving Clear
[2022-02-18 05:19:28.459] [renderer1] [info] [KeybindingService]: \ No keybinding entries.
```
 
This is hapening despite having the following in keybindings.json :-
```
// Place your key bindings in this file to override the defaults
[
	{
		"key": "Clear",
		"command": "center-editor-window.center",
		"when": "editorTextFocus"
	}
]
```

**Comment by AaronNGray** [comment]
@alexdima If you could still look into this please.

**Comment by AaronNGray** [comment]
```
[2022-02-18 10:08:24.247] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: Numpad5, keyCode: 12, key: Clear
[2022-02-18 10:08:24.248] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: Numpad5, keyCode: 126 ('Clear')
[2022-02-18 10:08:24.256] [renderer1] [info] [KeybindingService]: | Resolving Clear
[2022-02-18 10:08:24.257] [renderer1] [info] [KeybindingService]: \ No keybinding entries.
```
No change I think the key code is being generated from my patch :-
https://github.com/AaronNGray/vscode/blob/main/src/vs/base/common/keyCodes.ts#L572

**Comment by alexdima** [comment]
Using the `main` branch, the following worked for me:
```
{ "key": "clear", "command": "actions.find" }
```

**Comment by AaronNGray** [comment]
Still getting "No keybinding entries".
```
[2022-02-18 10:21:01.046] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: Numpad5, keyCode: 12, key: Clear
[2022-02-18 10:21:01.051] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: Numpad5, keyCode: 126 ('Clear')
[2022-02-18 10:21:01.051] [renderer1] [info] [KeybindingService]: | Resolving Clear
[2022-02-18 10:21:01.052] [renderer1] [info] [KeybindingService]: \ No keybinding entries.
```
This is from main branch

**Comment by AaronNGray** [comment]
I tried moving it to alt+F11 and thats not working either.

**Comment by alexdima** [comment]
Not sure what might be causing the difference we are seeing. Could please try to kill and restart `yarn watch` (the compilation task)? Changing const enums (such as in this case with `KeyCode.MAX_VALUE`) does not propagate correctly through our `gulp-tsb` builder and requires a restart to regenerate the JS files with inlined values.

**Comment by AaronNGray** [comment]
Yes I noticed that. I am just installing from scratch.

**Comment by AaronNGray** [comment]
I have another keyboard related issue if I may pass it by you, I am trying to do a BRIEF Editor keymapping. the funny thing about brief is it has HOME to goto the beginning of the line, HOME HOME to the top of the current window, then HOME HOME HOME to goto the top of the document. END behaves simularly, end of line, bottom of window, and end of document.
I can see I can get HOME HOME, but not HOME HOME HOME. Shall I do a separate Feature Request ?

**Comment by alexdima** [comment]
Yes, we already have a feature request for longer chords -- https://github.com/microsoft/vscode/issues/6966.

But I don't think chords would be the best way to tackle this because with chords you cannot dispatch both variants `home` and `home home`. One of them will win depending on their order and if it is the chord (`home home`), it will never fall back to `home` (see also discussion in https://github.com/microsoft/vscode/issues/140226).

In the core editor, we also have something similar with `home`, where first pressing `home` moves the cursor to the position before the first non whitespace character on the line, then pressing `home` again takes it to the first character on the line. Similarly, `home` on wrapped lines first moves the cursor to the start of the wrapped line, then a subsequent `home` moves the cursor to the start of the logical line. This is not implemented with chords, but rather by looking at the current state. If `home` is pressed and the cursor is in the middle of a line, it moves to the first non whitespace character. If `home` is pressed and the cursor is already at the first non whitespace character, it moves to the first character.

**Comment by AaronNGray** [comment]
The first HOME moves to the beginning of the line, follow that by a second HOME and it goes to the top of the window, follow that by a third HOME and it will got to the top of the document. SO what your saying is the HOME HOME HOME binding will override the others and they will not be done in sequence as they are matched ?

**Comment by AaronNGray** [comment]
So it has to be done with a new conditional function. Is there any command history at all that could be examined, for previous HOME commands ?

**Comment by alexdima** [comment]
Given:
```
[
    { "key": "home", "command": "cursorBeginningOfLine" },
    { "key": "home home", "command": "cursorBeginningOfWindow" },
]
```

When you press `home` the first time, the keybinding system will enter chord mode and will print "Home pressed. Waiting for second part of chord...". If `home` is pressed again within 5 seconds, then `cursorBeginningOfWindow` is invoked. If nothing is pressed within 5 seconds, nothing happens.

>  there any command history at all that could be examined, for previous HOME commands ?

My suggestion was to look at the cursor state and determine based on it what to do. If the cursor is at the start of the line and the user presses `home` once, it is very likely they wanted to move to the top of the window. However, if you wish to build up a history, you can do so, but it would need to be something done in your extension.

**Comment by AaronNGray** [comment]
Thank you for your help !

**Comment by alexdima** [comment]
To verify, you must use a keyboard with numpad keys and turn off numlock, and press the numpad 5. It will be identified as `Clear`.
