### ISSUE TITLE
Add support for large text files

### ISSUE THREAD

**Issue by danechitoaie** [Microsoft/vscode#14321]
Now when you open a file that is a bit large you get a message that the file is too large and can't be opened.

Would it be possible to still allow the file to be opened in a "stream mode"? Basically you can disable the syntax highlight (and maybe other features that would be resource intensive to implement on large files) but open and read the file in chunks of data (what's needed to be displayed on screen) and load more as you scroll (up or down)?

**Comment by mrmlnc** [comment]
> Let's track in #9832
>
> From @alexandrudima in #14257
