### ISSUE TITLE
Markdown Preview not filling buffer when zooming on UI

### ISSUE THREAD

**Issue by kube** [Microsoft/vscode#14329]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 16.0.0
- Extensions: EditorConfig.EditorConfig-0.3.4, PKief.material-icon-theme-1.1.2, eg2.vscode-npm-script-0.0.21, freebroccolo.reasonml-0.0.67, hackwaly.ocaml-0.6.3, justusadam.language-haskell-1.2.2, kube.42header-0.42.6, kube.ClangComplete-0.0.4, kube.kube-header-0.0.1, kube.theme-kay-0.0.3, lukehoban.Go-0.6.45, ms-vscode.latex-0.1.3, ms-vscode.typescript-javascript-grammar-0.0.6, vsmobile.vscode-react-native-0.2.1

Steps to Reproduce:

1. Open Markdown file with some text in it
2. Zoom on the UI multiple times (`CMD` + `+`)

Markdown preview is now not filling window.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/5745
