### ISSUE TITLE
Not registerTreeDataProvider to default explorer

### ISSUE THREAD

**Issue by Muromi-Rikka** [microsoft/vscode#143280]
`
  vscode.window.registerTreeDataProvider(
    "explorer",
    new FolderAliasTreeProvider()
  );
` 
or
`
  vscode.window.registerTreeDataProvider(
    "Folders",
    new FolderAliasTreeProvider()
  );
`

**Comment by alexr00** [comment]
@Muromi-Rikka I don't understand the issue, can you please provide more details about what you expect to happen and what's actually happening?

**Comment by Muromi-Rikka** [comment]
@alexr00 I want to achieve this effect in the default explorer
![123](https://user-images.githubusercontent.com/22149502/164135998-407c8528-18bc-4c16-91d7-8f91a0493c0d.png)

**Comment by alexr00** [comment]
The docs show how to contribute a view to the "Explorer" view container: https://code.visualstudio.com/api/references/contribution-points#contributes.views

**Comment by Muromi-Rikka** [comment]
@alexr00 Instead of adding a new view, I want to modify the default explorer

**Comment by alexr00** [comment]
@Muromi-Rikka we do not support modifying existing views, but you can always duplicate some of the functionality of the default explorer with a tree view, use the menu contribution point to add more actions to the explorer, or use icon themes to change the icons!
