### ISSUE TITLE
Integrated terminal find next not working for wrapped lines

### ISSUE THREAD

**Issue by varunbpatil** [microsoft/vscode#143255]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: Linux

Steps to Reproduce:

1. Run a command which generates long (wrapped) lines in the output in the integrated terminal.
2. Ctrl + F and search for a word.
3. "Enter" searches backwards successfully.
4. "Shift + Enter" **doesn't** search forwards.

Verified that keybindings is correct - "Shift + Enter" is bound to `workbench.action.terminal.findNext`.

Used to work correctly in VSCode 1.63.2.

**Comment by varunbpatil** [comment]
Additional details:

This seems to be happening only for ourput of certain commands like `kubectl logs`.

Verified that this is an issue even in 1.65

**Comment by Tyriar** [comment]
Cannot repro:




![Image](https://user-images.githubusercontent.com/2193314/207201241-c11fc267-00a2-41e2-a407-2cbc35a129a9.gif)
