### ISSUE TITLE
vscode does not understand "~" refer to home directory

### ISSUE THREAD

**Issue by henrysky** [microsoft/vscode#143252]
Does this issue occur when all extensions are disabled?: N/A, cannot really run jupyter notebook if disable all extension

- VS Code Version: 1.64.2
- OS Version: Windows 10 21H2 x64

Steps to Reproduce:

1. Run some python codes that will raise error
2. Attempt to open one of the file in trace (e.g. click on the number `267` below to open `constant_op.py` ). Since VSCode seems to treat `~` literally `~`, it will fail to open the file. If select "create file", a folder `~` will literally be created under C drive.

![Untitled](https://user-images.githubusercontent.com/28623434/154404472-fdef7fbe-d8f2-4a5b-bee4-9a90e305188a.png)

**Comment by JacksonKearl** [comment]
Please file against the jupyter extension: https://github.com/microsoft/vscode-jupyter, I do not know why it is displaying POSIX styler paths on Windows.
