### ISSUE TITLE
Access to KeybindingService in extension API

### ISSUE THREAD

**Issue by aioutecism** [Microsoft/vscode#1432]
I'm currently building an vim extension for vscode when I encountered this problem.
I need to bind keys such as `i` in `Normal Mode` and unbind it in `Insert Mode` so suggestions and other vscode's builtin features could work as normal.
In detail, my desired package.json can be:

```
{
    "contributes": {
        "keybindings": [
            {
                "command": "vim.i",
                "key": "i",
                "when": "editorTextFocus && !isVimInsertMode"
            },
            // ...
        ]
        // ...
    }
    // ...
}
```

It would be a great help if extension can access `KeybindingService` to register context to keybindings or bind/unbind in runtime.

ps: I can mimic all the default behaviours in `Insert Mode`, but that's just a lot of duplicate code and unnessery time.

**Comment by egamma** [comment]
@alexandrudima fyi

**Comment by alexandrudima** [comment]
@aioutecism This is now possible on master. e.g.:

```javascript
vscode.commands.executeCommand('setContext', 'isVimInsertMode', true);
```

Please see https://github.com/alexandrudima/vscode-vim if you are authoring a vim emulation extension for VS Code.

**Comment by aioutecism** [comment]
Cooooool!
When will the new version be released?

**Comment by alexandrudima** [comment]
I think the insider version will be released tomorrow.

**Comment by aioutecism** [comment]
@alexandrudima 
Thanks!
Will update amVim as soon as possible.
