### ISSUE TITLE
Unbound breakpoint when go to implementations works

### ISSUE THREAD

**Issue by UchihaYuki** [microsoft/vscode#143295]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

Please take a look at the following gif.
![unbound-breakpoint](https://user-images.githubusercontent.com/38900426/154533537-d45bbe0b-0679-498f-83e4-bc45a9a261ed.gif)

**Comment by weinand** [comment]
@UchihaYuki I do not really understand your problem.

Please note: if you are in an active debug session, breakpoints show up as "unbound" if their code is not yet loaded by the runtime (node.js).

**Comment by UchihaYuki** [comment]
The breakpoint should be hit in right.ts.
As you can see the breakpoint in channels.ts is hit, it executes the function Right.isAllowed which is located in right.ts, and I also set breakpoint in right.ts, but it never hits. According to the source map, it should hit.

**Comment by connor4312** [comment]
Sourcemaps inside of node_modules are not bound by default. You can configure the `outFiles` in your launch.json to include some or all of your `node_modules`

**Comment by UchihaYuki** [comment]
After setting launch.json to:
```json
      "outFiles": [
        "${workspaceFolder}/**",
        "**/node_modules/**"
      ],
```
Both breakpoints in right.js and right.ts hit, is this the expected behavior? or Should only the breakpoint in right.ts hit?

For vscode chome debugger, I don't need to set outFiles but breakpoint in node_modules still work. Is this the expected behavior? My launch.json for chrome:
```json
      {
          "name": "www - attach",
          "request": "attach",
          "type": "chrome",
          "port": 9222,
          "webRoot": "${workspaceFolder}",
      }
```

**Comment by connor4312** [comment]
> Both breakpoints in right.js and right.ts hit, is this the expected behavior?

Yes

> For vscode chome debugger, I don't need to set outFiles but breakpoint in node_modules still work. Is this the expected behavior? 

Yes, since sourcemaps are read from the runtime and not ahead of time from disk
