### ISSUE TITLE
Hello teacher! After verifying that still missing items 1 and 2 in this iteration not solved it

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#143288]
code 1.64
system Windows 10 19043

Hello teacher! After verifying that still missing items 1 and 2 in this iteration not solved it
please see: https://github.com/microsoft/vscode/issues/138457
Please seriously consider this request and hopefully it will be resolved in the next milestone. Thank you so much!

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/143247#issuecomment-1042817211
