### ISSUE TITLE
github.dev often shows no diff anymore for me

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#143216]
Lately, maybe since a few weeks, a diff on a PR opened in github.dev shows no file diff anymore:

![image](https://user-images.githubusercontent.com/900690/154310196-4e3b4bd5-c0c0-4a3e-ba78-3521fc78005f.png)

I cannot pin point the reason for this, was this reported before?

I suspected some caching index but it reproduces after reload with empty caches.

**Comment by bpasero** [comment]
Now it recovered after another window reload with devtools opened.

**Comment by joyceerhl** [comment]
Yeah, we are tracking this in https://github.com/microsoft/vscode-remote-repositories-github/issues/121, but I can't repro it reliably (and cannot repro it at all in extension development host) so the last thing I did is add debug logging. If you switch to pre-release RemoteHub and GHPRI (or use insiders.vscode.dev), and enable `"remoteHub.logLevel": "debug"`, could you possibly pull the RemoteHub and GHPRI logs please?

**Comment by bpasero** [comment]
Yeah can do when I see this again. I am on insiders of GitHub.dev so I think the extensions are insiders too?

![image](https://user-images.githubusercontent.com/900690/154321355-676813ed-ee73-4e13-be95-24bbfe55d85a.png)

**Comment by joyceerhl** [comment]
github.dev always bundles stable RemoteHub and GHPRI regardless of VS Code quality. vscode.dev bundles stable RemoteHub and GHPRI, insiders.vscode.dev bundles pre-release RemoteHub and GHPRI. 😅

**Comment by bpasero** [comment]
@joyceerhl oh, this happens for me on github.dev btw, I did not try vscode.dev. Does it make any difference?

**Comment by joyceerhl** [comment]
We have reports of it reproing in vscode.dev as well so it is embedder-agnostic. However only pre-release RemoteHub has the new logging I added, so insiders.vscode.dev would be the easiest way to pull those logs.

**Comment by bpasero** [comment]
@joyceerhl I just hit this again on github.dev and I am on pre-release versions it seems. The output is constantly talking about `readFile` calls, so I wonder if actually the issue here is starvation of file reads that occur and thus the diff cannot compute in time?
![Recording 2022-02-17 at 17 15 18](https://user-images.githubusercontent.com/900690/154523346-04d02cf6-6711-4241-be8b-18fed7ea51b5.gif)

**Comment by joyceerhl** [comment]
> starvation of file reads

🤔 this could be from anycode reading the files in the workspace to build an index--do you repro if you disable anycode?

**Comment by bpasero** [comment]
Sorry, indeed I was not on the pre-release version. I now have installed:
* `GitHub.remotehub`: `v0.25.2022021709`
* `GitHub.vscode-pull-request-github`: `0.37.2022021709`
* `GitHub.codespaces`: `v1.5.3`

It continues to reproduce with these pre-release versions, but let me capture a log now.

**Comment by bpasero** [comment]
Sent you the logs for this:

![image](https://user-images.githubusercontent.com/900690/154526921-aa95c981-66d7-4832-b024-ffac41eac498.png)

Right after reload, the first change opened and no diff shown.

**Comment by joyceerhl** [comment]
I tried opening 10 different PRs in github.dev from microsoft/vscode and haven't been able to repro this issue--all diffs work for me even after closing and reopening. Can you still repro this @bpasero? I wonder if it's related to the size of the file or the number of files changed.

**Comment by bpasero** [comment]
My quick testing in Chrome indeed does not reproduce this anymore, but I am not sure how so. I noticed that github.dev insiders was updated to a insiders version 1 day ago, not sure whether a change went in that could have an impact?

**Comment by joyceerhl** [comment]
@rebornix says he can still repro 100% of the time in Safari and it may be due to some bad local state. (I'm using Chrome always on Windows) Hoping we can debug together on his machine when he has the time

**Comment by joyceerhl** [comment]
Reliable repro:
1. Set `experimental.fs.useTars` to `always` or `ifAvailable` (the latter is default now)
1. Open PR
2. Trigger file search which will cause a repository index download
3. Go back to the PR view and open some diffs
4. :bug: diff is empty

Workaround is to set `experimental.fs.useTars` to `never`

Thank you @rebornix for helping to track this down!

**Comment by joyceerhl** [comment]
Repro steps:

1. Install the latest stable release (`0.28.0`) of GitHub Repositories and latest pre-release of GitHub Pull Requests and Issues in desktop VS Code
2. In settings, set `"githubRepositories.experimental.fs.useTars": "ifAvailable"` (there is a separate, unresolved bug when `useTars` is `"always"` which I will look into for the April milestone)
3. Open a GitHub pull request using the Open Remote Repository command
4. Trigger a fulltext search via ctrl+shift+f / cmd+shift+f and wait for the Downloading repository index progress notification to appear in the bottom right
5. Open a diff 
6. :bug: Diff editor shows same contents on the left and right (if you see the diff initially show up with different contents, just close and reopen it; the file contents will be correct if the repository index hasn't been downloaded yet)

To validate that this is fixed, _uninstall GitHub Repositories_, then install the latest pre-release (`0.29.2022033103`) of GitHub Repositories (ensure that you also have the pre-release of Remote Repositories installed) and repeat.

/cc @lszomoru
