### ISSUE TITLE
 vscode ignores "window.titleBarStyle": "native" if "window.activeBorder" is set to any value

### ISSUE THREAD

**Issue by demimurych** [microsoft/vscode#143332]
| Abstract |  |
|---:|:---| 
|<b>Issue Type</b>|bug</b>|
|                <b>Reproduced</b>|allways|
|      <b>Description</b>|vscode not respect setting  <code>{"window.titleBarStyle": "native" }</code><br/> in case then <code>"window.activeBorder" </code> is set                   |              

<br/>

## Step to reproduce
In settings.json set following settings:
```JSON
{
    "window.menuBarVisibility": "classic",
    "window.titleBarStyle": "native",
    "window.dialogStyle": "native",

     "workbench.colorCustomizations": { 
        "window.activeBorder": "#00FF00",
     }

}
```
<br/>

|Expected Result|Actual Result|
|---|---| 
|![Expected Result](https://user-images.githubusercontent.com/545828/154597396-ea1bca21-c918-481a-b667-0ba88a903f69.png)|![Actual result](https://user-images.githubusercontent.com/545828/154597391-5044eb65-178b-456b-98b6-c931be293a14.png)| 
|Mark 1:<ul><li>window title bar expected  in native system style| Mark 1:<ul><li> vscode render <b>custom title bar</b>  <li>Buttons: `minimize`, `maximize`, `close` render twice.<br/> <em>on custom titlebar and on native titlebar</em></ul> |
|Mark 2:<ul><li> menu expected in native system style|Mark 2: <ul><li>Menu have <b>no native style</b> |

<details>
<summary><b>Additional info</b></summary>
<p>
<ol>
<li>So actual result  (<code>title bar</code> and <code>menu</code>) looks like setting <code>"window.titleBarStyle"</code> is set to <code>"custom"</code>
<li>
Changing the settings: 
<code>menuBarVisibility</code>,
<code>titleBarStyle</code>,
<code>dialogStyle</code> -  have no effect. 
</ol>
</details>   

</br></br>

## Summary
<details>
<summary><b>Resume</b></summary>
<ul>
<li>if setting  <code>"window.activeBorder"</code> is set to any value then vscode stop reacting on settings:<br/>
<code>"window.titleBarStyle": "native"</code> and  <code>"window.dialogStyle": "native"</code><br/>
and allways show  menus and title bar in custom style.
<li>Sometimes doubled <code>close</code> and <code>minimize</code> <code>maximize</code> button
</details> 
</br>

<details>
<summary><b>Then all work like expected</b></summary>
If In settings.json remove <code>window.activeBorder</code> setting then all work like expected. </br>
Vscode respect all settings. 

```JSON
{
    "window.menuBarVisibility": "classic",
    "window.titleBarStyle": "native",
    "window.dialogStyle": "native",

     "workbench.colorCustomizations": { 
        // comment next setting
        // "window.activeBorder": "#00FF00",
     }
}
```

</details> 
</br>

<details>
<summary><b>What was I trying to do</b></summary>
<ul>
<li>Disable all plugins have no effect.<br/>
<li>Clear install have no effect.
</ul>
</details>  
  
</br>
<details>
<summary><b>System Info</b></summary>

|Item|Value|
|---|---|
|VS Code version| Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)|
|Restricted Mode| No|
|OS version| Linux x64 5.4.0-99-lowlatency|
|Operating System|Kubuntu 20.04|
|KDE Plasma Version|5.18.8|
|KDE Frameworks Version|5.68.0|
|Qt Version|5.12.8|
|Kernel Version|5.4.0-99-lowlatency|
|OS Type|64-bit|
|Processors|4 × Intel® Core™ i7-3520M CPU @ 2.90GHz|
|Memory|15,6Gb|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by sbatten** [comment]
the active border setting does not work with a native titlebar style so having this customization forces custom. cc @bpasero
