### ISSUE TITLE
Builtin renderer for `application/json` output from notebook is no longer available

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#143300]
Issue Type: <b>Bug</b>

1. Install [REST Book](https://marketplace.visualstudio.com/items?itemName=tanhakabir.rest-book) extension.
2. Run its `REST Book: Creat a new blank REST Notebook` command.
3. In the first cell enter and run a GET request, for example:

```
GET https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
```

4. From the `...` output cell menu choose `Change Presentation`

![image](https://user-images.githubusercontent.com/6726799/154548573-5d1b2452-1062-4bdb-9b63-e8eb27588001.png)

:bug: No rendered for `application/json` is available.

Same steps work on 1.64

![image](https://user-images.githubusercontent.com/6726799/154549100-be80f13b-2210-465f-8623-e70a122b38fa.png)

pinging @rebornix

VS Code version: Code - Insiders 1.65.0-insider (86200d542474b26aa28034e0fd5789c45c747d8b, 2022-02-17T07:18:54.447Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 4.19.128-microsoft-standard

**Comment by rebornix** [comment]
@gjsjohnmurray `application/json` was added at the very beginning as experiment but later on we moved towards a more generic mime type syntax `text/x-{lan}` so you can use `text/x-json` for the same purpose. Sorry for the breaking change though.

**Comment by rebornix** [comment]
@tanhakabir can we replace `application/json` with `text/x-json` in the REST extension?

**Comment by gjsjohnmurray** [comment]
@rebornix I think it's up to the REST endpoint to decide what content-type it returns.

The [IANA site](https://www.iana.org/assignments/media-types/media-types.xhtml) lists `application/json` and makes no mention of `text/x-json', nor of any beginning `text/x-`

Can you treat the two as synonymous?

**Comment by pgfearo** [comment]
This change is good to know as it effectively breaks the XPath Notebook extension. I will make the necessary change to the extension.
