### ISSUE TITLE
Finding outdated extensions is difficult 

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#143303]
I have +100 extensions installed and whenever I see a "outdated" extension, I have a hard time finding that extension:

https://user-images.githubusercontent.com/35271042/154535899-b05ba72c-c42b-4f18-ba02-4b96739f6ead.mp4

## Suggestions

Bubble actionable extensions to the top

<img width="408" alt="CleanShot 2022-02-17 at 10 39 07@2x" src="https://user-images.githubusercontent.com/35271042/154548615-0363889e-44a6-4d8f-b444-296cfda850a8.png">

**Comment by gjsjohnmurray** [comment]
There is already an option on the filter button.

**Comment by misolori** [comment]
@gjsjohnmurray yes, that is captured in my screen recording but it is also not highly discoverable (how would you know there's a filter for it?)

**Comment by benibenj** [comment]
Closing with #161577
