### ISSUE TITLE
Can I merge multiple terminals into one terminal After reloading the vscode?

### ISSUE THREAD

**Issue by Shuai-Xie** [microsoft/vscode#143339]
When reloading the vscode project to load a new environment or something else, I find that **the parallel terminals used before change to sequential like below**.

I wonder if there is a method that can help me merge `1:ssh` and `2:bash` to a single panel like before.

Thanks a lot.

![image](https://user-images.githubusercontent.com/18352713/154610130-37cafb63-91f6-4020-b644-f768e39d950b.png)

**Comment by meganrogge** [comment]
It looks like you have terminal tabs disabled or on a super old version of vscode. 

you can reload the window and keep the split terminals if you set `terminal.integrated.tabs.enabled` to true
