### ISSUE TITLE
How to stat a directory using `IFileService`?

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#143394]
For https://github.com/microsoft/vscode/issues/142078 , I am trying to replace `pfs` with `IFileService`. 

[Here](https://github.com/microsoft/vscode/blob/b5d09a82f2f0fcdb6b9004a2175e76ba8319eb96/src/vs/workbench/services/extensions/electron-browser/cachedExtensionScanner.ts#L161-L162) I need to read the `mtime` of a directory. I could not find `IFileService.stat` so I am trying to use `IFileService.resolve()`.

However, I have noticed that `IFileService.resolve()` returns all children for a directory, which in the case of the builtin extensions directory is about 100 children, and I am concerned that this might be costly. Is there a way to stat a directory without reading its children?

**Comment by bpasero** [comment]
There is now `IFileService.stat` that will not resolve children.

**Comment by gjsjohnmurray** [comment]
@bpasero is your change relevant / applicable to extensions, either ones that implement a FileSystemProvider or ones that use `vscode.workspace.fs.stat()` to learn about a folder?

**Comment by bpasero** [comment]
@gjsjohnmurray extensions have a more primitive form of API and can use `vscode.fs.stat` which is pretty much the same as the internal API I now added.

In March debt week I might see to adopt this new `IFileService.stat` method over `IFileService.resolve` given it is probably faster in most cases where the `children` are not required.

**Comment by alexdima** [comment]
Nice! Thank you @bpasero !
