### ISSUE TITLE
Linting errors on the composite configuration suggesting missing request and cwd attributes

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#14335]
Testing #14171

A composite configuration shouldnt need anything other than `name`, `type` and `configurationNames`

![image](https://cloud.githubusercontent.com/assets/16890566/19667084/8e94a2fa-9a03-11e6-986d-2aec1f98e56b.png)

**Comment by isidorn** [comment]
This is just a temporary way that we have surfaced multi debug sessions, we have to figure out what is our plan for this in november

**Comment by isidorn** [comment]
Fixed on branch `isidorn/compound` - however we have chosen not to ship this feature yet. We will provide more details about the reasoning behind this in #14842

For now we will only ship with the manual click on play button multiple times approach.
