### ISSUE TITLE
Extension host: Trying to load the allocator multiple times. This is *not* supported.

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#143353]
When running exploration builds I see this error message printed right on startup:

![image](https://user-images.githubusercontent.com/900690/154642610-e847f3fe-6ccf-4f89-8c15-05672f00f1ab.png)

**Comment by deepak1556** [comment]
Issue only affects internal builds, regressed with https://domoreexp.visualstudio.com/Teamspace/_git/electron-build/pullrequest/472054

Error is from the partition allocator trying to be registered more than once in the same process https://source.chromium.org/chromium/chromium/src/+/main:base/allocator/allocator_shim_override_mac_default_zone.h;l=247-254

**Comment by deepak1556** [comment]
Addressed in https://domoreexp.visualstudio.com/Teamspace/_git/electron-build/pullrequest/480015
