### ISSUE TITLE
shell integration for zsh doesn't work because script isn't in the right directory

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#143389]
![Screen Shot 2022-02-18 at 10 34 17 AM](https://user-images.githubusercontent.com/29464607/154724087-5c6e8926-7c2b-4b76-a228-527fa81a7f85.png)

**Comment by roblourens** [comment]
I still see this

**Comment by roblourens** [comment]
```
ls -la '/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/browser/media'
total 16
drwxr-xr-x  4 roblou  staff   128 Feb 24 05:15 .
drwxr-xr-x  3 roblou  staff    96 Feb 24 05:15 ..
-rwxr-xr-x  1 roblou  staff  2231 Feb 24 05:01 shellIntegration-bash.sh
-rw-r--r--  1 roblou  staff  2632 Feb 24 05:01 shellIntegration.ps1
```

**Comment by meganrogge** [comment]
Yep @roblourens thanks. We're aware of that - it's because `.zshrc` is filtered out by the gulp task that puts files in that folder.

**Comment by Tyriar** [comment]
I guess this is essentially the same as https://github.com/microsoft/vscode/issues/143629 now

/duplicate
