### ISSUE TITLE
When I'm in a string, in javascript and I type the interpolation operator, convert the string to a template literal

### ISSUE THREAD

**Issue by ankopainting** [microsoft/vscode#143333]
When I'm in a string such as 

```
"hello ^"  
```
or
```
'hello ^'
```

(the caret represents the cursor)

and I type ${, the string should be converted automatically to a template literal

eg.

```
`hello ${^`
```

Many other ides do this and it saves a lot of time.  it should be added to the undo buffer so undoing it (for example if that's not what you want) is as easy as ctrl-z / cmd-z / edit-undo

**Comment by mjbvz** [comment]
See https://marketplace.visualstudio.com/items?itemName=meganrogge.template-string-converter

**Comment by ankopainting** [comment]
thank you
