### ISSUE TITLE
JS documentation shows only 'any'

### ISSUE THREAD

**Issue by erikmartinessanches** [microsoft/vscode#143321]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.0-insider (Or not insider, regular 1.64.2, doesn't matter, same outcome.)
- OS Version: macOS 11.6.4

Steps to Reproduce:

1. Download VS Code (insiders).
2. Open folder with JS documents, documentation on hover works. 
3. Install an extension such as git lens or sync my settings and now the popup works perhaps for the first but not subsequent .filter in my file. :(

**Comment by mjbvz** [comment]
Please share example code that demonstrates the issue

**Comment by erikmartinessanches** [comment]
> Please share example code that demonstrates the issue

entire sample.js:
```

const ages = [32, 33, 16, 40];
const result = ages.filter(checkAdult); //Documentation popup over filter works here.

function checkAdult(age) {
  return age >= 18;
}


function dishType(dish) {
  if (dish.dishTypes !== undefined) {
    const tp = dish.dishTypes.filter(isKnownTypeCB); // 'any' popup over filter here.
    if (tp.length > 0) return tp[0];
  }
  return "";
}

function isKnownTypeCB(type) {

  return true;

}
```

**Comment by mjbvz** [comment]
You need to add JSDoc comments to tell VS Code what the type of the `dish` parameter is. For example:

```js
/**
 * @param {{ dishTypes: string[] }} dish
 */
function dishType(dish) {
  if (dish.dishTypes !== undefined) {
    const tp = dish.dishTypes.filter(isKnownTypeCB); // 'any' popup over filter here.
    if (tp.length > 0) return tp[0];
  }
  return "";
}
```

The types cannot be inferred from your code otherwise. They can in the first example because `ages` is clearly an array of nubers
