### ISSUE TITLE
Can't see contents of C:\

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#143308]
* on Windows
* `scripts\code-server.bat`
* do Open Folder
* press Backspace until `C:\`
* observe that the contents of `C:\` are never presented while other folders are:
* I speculate there could be a problem with `readdir` or calling stat on one of the root directories.

<img width="716" alt="image" src="https://user-images.githubusercontent.com/5047891/154563564-02d3cf27-4b36-4141-8012-44e7b8737248.png">

<img width="665" alt="image" src="https://user-images.githubusercontent.com/5047891/154563535-0f3f1a95-6640-4555-b151-20feb0f739a3.png">

**Comment by alexr00** [comment]
@alexdima did you just click the " " link? What browser are you using?

The contents of "C:\" show properly for me with Edge dev:

![image](https://user-images.githubusercontent.com/38270282/154984126-496b5ebb-3b6d-451a-859e-91641e66edab.png)

**Comment by alexr00** [comment]
Accidentally closed.

**Comment by alexdima** [comment]
Not sure what's special on my VM, but by adding some logging I believe there might be a problem with the fs provider which returns only `node.exe` as a child of `C:\`:

```patch
diff --git a/src/vs/platform/files/common/diskFileSystemProviderClient.ts b/src/vs/platform/files/common/diskFileSystemProviderClient.ts
index 1980081887f..ace2fab093e 100644
--- a/src/vs/platform/files/common/diskFileSystemProviderClient.ts
+++ b/src/vs/platform/files/common/diskFileSystemProviderClient.ts
@@ -73,8 +73,16 @@ export class DiskFileSystemProviderClient extends Disposable implements
 		return this.channel.call('stat', [resource]);
 	}
 
-	readdir(resource: URI): Promise<[string, FileType][]> {
-		return this.channel.call('readdir', [resource]);
+	async readdir(resource: URI): Promise<[string, FileType][]> {
+		console.log(`readdir ${resource}`);
+		try {
+			const r: any = await this.channel.call('readdir', [resource]);
+			console.log(`FINISHED readdir ${resource}: `, r);
+			return r;
+		} catch (err) {
+			console.log(`ERR readdir ${resource}`);
+			throw err;
+		}
 	}
 
 	//#endregion

```

<img width="648" alt="image" src="https://user-images.githubusercontent.com/5047891/155209433-8a218ae7-f46d-4cbb-a4e0-e237c8b9c391.png">

**Comment by alexdima** [comment]
@alexr00 This only reproduces when using the test resolver or when running in the web, so it does not reproduce with `"files.simpleDialog.enable": true`. It seems to be related to the scheme being `vscode-remote:` and not `file:` and to different behaviors with trailing slashes. In the `file:` case we see a `readdir` for `C:\` while in the `vscode-remote:` case we see a `readdir` for `C:` which is apparently an invalid path.

**Comment by bpasero** [comment]
Just to clarify, when the file service gets a path `C:` it calls `path.normalize` which will return `C:.` (not the trailing `.`). This seems to translate into `fs.readdir(.)`, i.e. current working directory.

**Comment by alexr00** [comment]
@alexdima and I looked together and tested on 4 Windows computers. 3/4 had the behavior that he sees (`readdir('c:')` is the same as `readdir('.')` and 1/4 had the behavior I see. Unclear why there is different behavior, but at least now I have a repro I can test with.
