### ISSUE TITLE
markdown preview fails from command line (code .)

### ISSUE THREAD

**Issue by trheehs-ms** [microsoft/vscode#143373]
[Issue in SO
](https://stackoverflow.com/questions/70790953/vscode-markdown-preview-blank-on-launch-from-command-line-code?noredirect=1#comment125771760_70790953)
- Repro'd

**Problem description:** When launching /directory containing markdown files using `code .` from the command line into VSCode, the files fail to render in markdown preview window. The preview window opens, and is blank. When opening code from windows menu, preview button works and renders markdown content.

I have tried:
- Problem is persistent across Windows 10 and Windows 11 OS.
- If I open VSCode from file explorer or Windows menu, the markdown content renders using preview.
- If I open VSCode using `code .`, the preview button fails to render markdown content and displays blank preview window.
- If I launch from the command line using `code`, render also seems to fail.

**Workaround:** Open VSCode from file explorer or Windows menu and markdown content renders in preview.

Looking for confirmation if this is a known issue or not, or others have encountered? Would like to be able to launch Code from command line and have markdown preview work.

![image](https://user-images.githubusercontent.com/66136181/154700393-94e648c9-3f18-426e-a23d-537f2426235a.png)

**Comment by mjbvz** [comment]
Please fill in the issue template so we know what build you are on

Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
