### ISSUE TITLE
show installed extensions as a group while searching

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#143340]
I have an idea about extension searching
I believe we should provide a set of view for installed extensions while searching. either online or offline

- online
show the available extension from network and show the installed in one group（as pic showed）
![image](https://user-images.githubusercontent.com/1876302/153983748-9d2cbe42-dd29-4c5a-9ead-8a343464157d.png)

- offline
show the error message and also show the installed extension in one group
![image](https://user-images.githubusercontent.com/1876302/153983828-667d9aed-e256-4271-86ab-30e6bd0b68ce.png)

that will be easy to search and reduce the user's mentalcost

please 🙏

_Originally posted by @heartacker in https://github.com/microsoft/vscode/issues/142007#issuecomment-1039798341_

**Comment by sandy081** [comment]
Reopened #142007
