### ISSUE TITLE
编写中文的时候持续的闪烁

### ISSUE THREAD

**Issue by DogMing** [microsoft/vscode#143337]
Issue Type: <b>Bug</b>

在使用编辑器输入中文的时候，编辑器会持续的闪烁，非常的刺眼

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 10, 13|
|Memory (System)|16.00GB (1.43GB free)|
|Process Argv|--crash-reporter-id 155ce01a-4c7a-4ede-9f3f-458a21b1ac09|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.7.0
vscode-lombok|Gab|1.0.1
plantuml|jeb|2.17.2
vscode-docker|ms-|1.19.0
remote-containers|ms-|0.217.4
remote-ssh|ms-|0.74.0
remote-ssh-edit|ms-|0.74.0
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
vscode-thunder-client|ran|1.12.0
java|red|1.3.0
vscode-xml|red|0.19.1
vscode-yaml|red|1.4.0
open-in-browser|tec|2.0.0
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0
vscode-spring-initializr|vsc|0.8.0
vim|vsc|1.22.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30438341
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
vsbas813:30436447
vscscmwlcmt:30436993
helixcf:30438276
cppdebug:30437093

```

</details>

**Comment by DogMing** [comment]
I'm sorry this bug is a bug of vim extention.
The text always twinkle when I type character.

**Comment by wenfangdu** [comment]
I'm having the same issue, switched to `asvetliakov.vscode-neovim`, and it has no issues.
