### ISSUE TITLE
Smoke test setup `ETIMEDOUT` downloading stable code

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#143386]
It looks like the smoke test had a generic startup error caused by a TLS stream (maybe a https request?)

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=156657&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=00d0ae10-f5a4-5438-a3b8-c58076933cab&l=21

```
 1) "before all" hook in "{root}":
     Uncaught Error: read ETIMEDOUT
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
```

**Comment by bpasero** [comment]
```
[2022-02-18T09:10:19.259Z] Starting operation 'download stable code...
[2022-02-18T09:10:37.376Z] Starting operation 'rimraf(testDataPath)...
[2022-02-18T09:10:37.380Z] Finished operation 'rimraf(testDataPath)' successfully after 4ms
```

This is from using the `vscode-test` module to download VSCode:

https://github.com/microsoft/vscode/blob/b667613ff88dd68a11c308fe75a519652f335cc1/test/smoke/src/main.ts#L283

@connor4312 did you see this before?

**Comment by bpasero** [comment]
One idea would be to wrap `vscodetest.download` is a `retry`, similar to this call:

https://github.com/microsoft/vscode/blob/b667613ff88dd68a11c308fe75a519652f335cc1/test/smoke/src/main.ts#L265

But I am not 100% sure that method can be just retried like that.

**Comment by joaomoreno** [comment]
If we depend on a library and that fails, I suggest the retry logic be in the library itself.

**Comment by bpasero** [comment]
Added retry logic, but would be nice to get this from `vscode-test` natively.
