### ISSUE TITLE
Add setting to disable terminal line wrapping for all terminals by default

### ISSUE THREAD

**Issue by jwarkentin** [microsoft/vscode#143346]
It is extraordinarily rare that I ever want line wrapping in terminals. It would be awesome if I could just switch the default state that terminals start in so I don't have to toggle every terminal I open. If that were the default, I doubt I'd even want to toggle it once a year. While #134623 sits in the backlog, this would go a long way toward resolving the major pain point since it side-steps the need to perform the action that causes the problem. And even if that gets fixed, it would be nice to not have to toggle every terminal I open.

**Comment by meganrogge** [comment]
Thanks for the issue. At this time, there's not enough demand for this sort of thing. You can run the `Terminal: set fixed dimensions command` and that will persist across reloads/restarts.
