### ISSUE TITLE
Settings sync does not sync extension version when downgrading

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#143343]
- VS Code Version: stable/insiders

Steps to Reproduce:

1. Open github.dev and enable settings sync
2. Install some extension like vim extension
3. Downgrade to older version 
4. Open github.dev in another browser/machine
5. Vim extension gets synced using latest version instead of older version from first machine

**Comment by jeanp413** [comment]
@sandy081 could you link the original issue please :pray:

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/93332
