### ISSUE TITLE
runing c# build task always stuck

### ISSUE THREAD

**Issue by Cinorid** [microsoft/vscode#143312]
Issue Type: <b>Bug</b>

install c# extention
run 'dotnet new webapi -n test1'
run 'code test1'
then hit Terminal => Run Build Task
it always stuck in running tasks.
'The connection to the terminal's pty host process is unresponsive, the terminals may stop working.'
but if I copy generated command and run it manually with cmd it goes successfull.

![image](https://user-images.githubusercontent.com/10947730/154566862-cdb2c740-3271-4a44-9a43-8649d68c16ca.png)
![image](https://user-images.githubusercontent.com/10947730/154567274-64a5d3b0-d10b-4248-9e4d-92e44866565e.png)

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.90GB free)|
|Process Argv|--crash-reporter-id 0d7b0b9c-022a-4dc0-92e3-c3bd2b70cacf|
|Screen Reader|no|
|VM|57%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.0
ts-to-csharp|box|0.2.2
doxdocgen|csc|1.3.2
vscode-eslint|dba|2.2.2
vscode-npm-script|eg2|0.3.24
msys2|fou|0.9.1
copilot|Git|1.7.5003
vscode-test-explorer|hbe|2.21.1
electron-builder|idl|0.7.2
search-node-modules|jas|1.3.0
vscode-docker|ms-|1.19.0
csharp|ms-|1.24.0
vscode-kubernetes-tools|ms-|1.3.6
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.1.5
remote-containers|ms-|0.217.4
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
test-adapter-converter|ms-|0.1.5
vs-keybindings|ms-|0.2.1
vscode-react-native|msj|1.9.0
vscode-yaml|red|1.4.0
LiveServer|rit|5.7.4
vscode-xml-complete|rog|0.3.0
html-preview-vscode|tht|0.2.5
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.16
vscode-ruby|win|0.28.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30438340
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc008:30440022
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvid2:30438800
helix:30438806

```

</details>

**Comment by Cinorid** [comment]
It seems related to calling 'conhost.exe' process.
C:\Windows\system32\conhost.exe --headless --inheritcursor --width 143 --height 11 --signal 0x2f8 --server 0x2f0

**Comment by alexr00** [comment]
I'm not able to reproduce this issue:

```
> Executing task: C:\Program Files\dotnet\dotnet.exe build C:\Users\alros\Documents\testing\dotnetweb\test1/test1.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <

Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  test1 -> C:\Users\alros\Documents\testing\dotnetweb\test1\bin\Debug\netcoreapp3.1\test1.dll

Terminal will be reused by tasks, press any key to close it.
```

If you're still seeing it you can try opening an issue on the C# extension.

**Comment by Cinorid** [comment]
@alexr00 
I managed to fix the problem.
problem is related to 'terminal.integrated.windowsEnableConpty'
default value is 'true' and changing it to 'false' fixed the problem.
my os: Windows 10 Enterprise 21H1 build 19043.1503

**Comment by alexr00** [comment]
@Tyriar FYI, not sure why changing that setting would solve this.

**Comment by Tyriar** [comment]
Not sure, but updating Windows might fix it if it's a bug in conpty.
