### ISSUE TITLE
terminal input isn't parsed

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#143397]
I have no extensions enabled and tried all of the renderer types. I see this happening frequently when I've moved focus from the terminal and move it back.

Pretty sure I've seen it with/without shell integration enabled
![Recording 2022-02-18 at 12 07 30](https://user-images.githubusercontent.com/29464607/154738268-cec31bba-d776-4109-86bf-f0fc717aa8ab.gif)
.

**Comment by meganrogge** [comment]
also commented my settings out

**Comment by meganrogge** [comment]
We think this could be a problem with the pty service - going to look at the shared process logs when it happens next

**Comment by meganrogge** [comment]
@deepak1556 @rzhao271 

@Tyriar and I think this could be a regression in Electron

We don't touch `unref` and this is happening on electron run as a node process (the pty host).

![Screen Shot 2022-02-23 at 11 05 14 AM](https://user-images.githubusercontent.com/29464607/155371413-86cba037-79e4-45fb-86b0-2e04b42837f2.png)

![Screen Shot 2022-02-23 at 11 06 55 AM](https://user-images.githubusercontent.com/29464607/155371411-cf4f24bd-3038-4061-a6db-5e1e0736f6f8.png)


I'm on a mac 
![Screen Shot 2022-02-23 at 11 16 39 AM](https://user-images.githubusercontent.com/29464607/155371713-b6f1008a-f899-4cf8-b152-72172298821c.png)

and this started happening recently - perhaps coinciding with the electron update

**Comment by meganrogge** [comment]
can confirm this is not terminal specific - also happens in the output channel
![Recording 2022-02-23 at 11 59 56](https://user-images.githubusercontent.com/29464607/155379191-5c4dd682-3d30-4674-8b05-2512c68320ce.gif)

**Comment by meganrogge** [comment]
Something I saw popup right before this stopped working was:

![Screen Shot 2022-02-23 at 11 59 19 AM](https://user-images.githubusercontent.com/29464607/155379639-6c56dcfb-865b-4ca9-8d0b-c98fe348e6b2.png)

**Comment by meganrogge** [comment]
@rzhao271 has pointed out that's probably unrelated. I was using dev tools to debug, which is probably why that wouldn't work

**Comment by meganrogge** [comment]
seeing the same issue in stable - looks related to reconnection. Which is weird because I did not reload the window
![Screen Shot 2022-02-23 at 1 28 05 PM](https://user-images.githubusercontent.com/29464607/155393485-74d56471-89c6-4f75-8b39-25ffdc4c32b4.png)

**Comment by Tyriar** [comment]
> can confirm this is not terminal specific - also happens in the output channel when debugging

@meganrogge the debug console is readonly unless you're in a debug session

**Comment by meganrogge** [comment]
I disabled `enabledPersistentSessions` and haven't seen this happen since

**Comment by Tyriar** [comment]
I don't think we've had any other reports of this? Perhaps you should re-enable the setting when we upgrade Electron in Insiders?

**Comment by Tyriar** [comment]
@meganrogge have you seen this recently?

**Comment by meganrogge** [comment]
No
