### ISSUE TITLE
Typo on "Testing" screen

### ISSUE THREAD

**Issue by ghaccount** [microsoft/vscode#143341]
Issue Type: <b>Bug</b>

It says "Install Additional Text Extensions...". 

I believe it should be "Test", not "Text"

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

**Comment by sbatten** [comment]
duplicate , this appears to be fixed for the next release
