### ISSUE TITLE
A11y_VisualStudioCodeClient_text cursor indicator: Text cursor indicator is not following in the editor

### ISSUE THREAD

**Issue by kupatkar99** [microsoft/vscode#143355]
### GitHubTags:
#A11yMAS; #A11yTCS; #A11ySev2; #DesktopApp; #Visual Studio Code Client; #BM-VisualStudioCode-Win32-Nov2021; #Win32; #No Disruption of Accessibility Features; #WCAG4.3.1

### Environment Details:
Application Name: Visual Studio Code Client
Windows Version: Windows 11

Repro Steps:
1)Open Visual studio code app.
2)Navigate to app with magnifier at 200%.
3)Turn on Text cursor indicator .
4)Verify that Text cursor indicator is following in the editor or not.

### Actual Result:
Text cursor indicator is not following in the editor.

### Expected Result:
Text cursor indicator is should follow in the editor.

### User Impact:
Low vision users will face difficulty if text cursor indicator is not following in the editor.

![A11y_visualStudioCodeClient_textCursorIndicator](https://user-images.githubusercontent.com/98530069/154645015-3c9dfd04-ea2a-46cf-b840-77f28682042c.gif)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/105558
