### ISSUE TITLE
configurationNames property should not be allowed on launch configurations other than "composite"

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#14336]
Testing #14171

![image](https://cloud.githubusercontent.com/assets/16890566/19667168/29c64c06-9a04-11e6-8c42-ef9108c1c27a.png)

**Comment by isidorn** [comment]
This is just a temporary way that we have surfaced multi debug sessions, we have to figure out what is our plan for this in november

**Comment by ramya-rao-a** [comment]
Duplicate of #14486
