### ISSUE TITLE
XML files are opened in PHP Language Mode

### ISSUE THREAD

**Issue by starki7** [microsoft/vscode#143383]
Issue Type: <b>Bug</b>

Hi!
XML files are opened in PHP Language Mode.
I have tried several ways of changing this setting, but eventually, it comes always back to PHP.
Interesting, file first opens as XML, then changes to PHP.
Sincerely,
Goran

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (17.85GB free)|
|Process Argv|C:\\Users\\Petrol\\OneDrive - Petrol d.d\\Documents\\CEEPS\\Merilna točka\\3.sestanek\\Priloga_A XSD v2.5.xml --crash-reporter-id d37aa53d-b28e-47d9-b025-929b35c49dcb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.8.2
swagger-viewer|Arj|3.1.2
advanced-abap-snippet-generator|Bra|1.2.8
npm-intellisense|chr|1.4.1
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.2.0
vscode-firefox-debug|fir|2.9.6
url-encode|fle|1.1.0
abap-snippets|fre|0.1.0
hclappscancodesweep|HCL|1.2.0
cds|hud|0.7.1
db2forzosdeveloperextension|IBM|1.3.3
reg|ion|1.0.3
vscode-nuget-package-manager|jmr|1.1.6
vscode-abap|lar|0.5.6
vscode-swissknife|lui|1.3.1
vscode-docker|ms-|1.19.0
csharp|ms-|1.24.0
vscode-kubernetes-tools|ms-|1.3.6
remote-containers|ms-|0.217.4
remote-wsl|ms-|0.64.2
hexeditor|ms-|1.9.4
powershell|ms-|2021.12.0
vscode-abap-remote-fs|mur|1.0.2
winregistry|mur|0.0.1
vscode-versionlens|pfl|1.0.9
java|red|1.3.0
vscode-yaml|red|1.4.0
vsc-extension-sa|SAP|1.3.5
vscode-cds|SAP|4.5.1
vscode-hexdump|sle|1.8.1
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc009:30440023
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343

```

</details>

**Comment by roblourens** [comment]
> Interesting, file first opens as XML, then changes to PHP.


This sounds like something that a misbehaving extension could do. Does it work if you start with `--disable-extensions`?

**Comment by starki7** [comment]
Hi!
No, when I disable Extensions, it works ok.
I will disable all Extensions and then enable one by one and see when problem occurs.
Thank You,
Goran

**Comment by starki7** [comment]
Hi,
have find the culprit, **HCL AppScan CodeSweep** is causing XML displaying in PHP Language Mode.
Thanks again @roblourens,
Goran
