### ISSUE TITLE
Unable to resolve content when attempting to open cell with 500+ outputs

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#143348]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8586769/154633030-dfb40704-8c9f-4205-bfc9-37dc024682cb.png">
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/8586769/154633087-33469b46-fd8f-4554-a534-c9892b6a7a08.png">

Not sure of exact repro, ran a cell that produced a large number of output items across 20+ minutes, tried to view them all, got this.

**Comment by JacksonKearl** [comment]
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/8586769/154633303-4f488e69-906a-4790-a78a-68309fef0c51.png">

rendering issue too, whole page got offset upwards, overlapping breadcrumbs

**Comment by roblourens** [comment]
That URI has a `%2C` at the end, this is a comma, weird...
