### ISSUE TITLE
cant connect to wsl: Ubuntu

### ISSUE THREAD

**Issue by saechben** [microsoft/vscode#143319]
Issue Type: <b>Bug</b>

when I open an ocaml file the WSL disconnects

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Connection to 'WSL: Ubuntu' could not be established  Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.39GB free)|
|Process Argv|--crash-reporter-id 9a8d135d-37dc-47ea-80d1-a32610dc648f|
|Screen Reader|no|
|VM|0%|

Connection to 'WSL: Ubuntu' could not be established  Canceled
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
vscop841:30438915
dsvsc009:30440023
vsbas813:30436447
vscscmwlcmc:30438804
helix:30438806

```

</details>

**Comment by aeschli** [comment]
Is it only with this specific file?
We don't have any language support out-of-the box for `ocaml`. You mention that you have no extensions enabled. So the file opened as a plain text file? And WSL disconnects?
