### ISSUE TITLE
fs.readFile causing Error: spawn EPERM

### ISSUE THREAD

**Issue by alanhamlett** [microsoft/vscode#143335]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Unknown
- OS Version: Windows

Steps to Reproduce:

1. Install the [wakatime extension](https://github.com/wakatime/vscode-wakatime) on Windows
2. Open your vscode dev console
3. See the error `spawn EPERM` caught after trying to `fs.readFile`

More info in the original issue https://github.com/wakatime/vscode-wakatime/issues/262.

**Comment by lramos15** [comment]
Sorry but this sounds like a bug specific to your extension. I do not have any specific guidance but your issue seems to have some pointers. You may also try using VS code's filesytem APIs
