### ISSUE TITLE
Built-in notebook output renderer no longer supports `text/x_LANGUAGE_ID` mimetype

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#143358]
Issue Type: <b>Bug</b>

This capability is documented at https://code.visualstudio.com/api/extension-guides/notebook#rich-output and works in 1.64.2 but not in Insiders.

Looks like a breaking change similar to #143300

/assign @rebornix

VS Code version: Code - Insiders 1.65.0-insider (1d618b2df1cf08f0e3ab706353f0a8f6f1424795, 2022-02-18T05:17:35.717Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by rebornix** [comment]
We have just brought it back to the core through markdown output renderer.
