### ISSUE TITLE
Feature request for adding system prefered theme

### ISSUE THREAD

**Issue by aayushchugh** [microsoft/vscode#143365]
I am requesting feature to have a theme setting which sync your vscode theme to windows setting
eg. if I am changing my windows color settings to `light` it should set my vscode theme to `Light+` but if I change my windows color setting to `dark` than my vscode theme should be converted to `Dark+`

**Comment by IllusionMH** [comment]
/question

Already exists https://code.visualstudio.com/docs/getstarted/themes#_auto-switch-based-on-os-color-scheme

If you have issues with this feature - you should create proper bug reports.
