### ISSUE TITLE
Code Snippet should appear before other IntelliSense

### ISSUE THREAD

**Issue by ericsia** [microsoft/vscode#143388]
I can imagine the only reason user use self defined code snippet over intellisense is for own convenient.
Thus user defined code snippet matching should appear at the top instead of intellisense one.
![counterintuitive](https://user-images.githubusercontent.com/24624808/154723336-bf98593a-9d52-4fd4-8770-ac1c718d0303.gif)

It is so troublesome for user who entirely use keyboard, sometime long pressing down arrow result it too bottom.

VS Code version: Code 1.64.2
OS version: Windows 10
Restricted Mode: No

**Comment by jrieken** [comment]
You can use the `editor.snippetSuggestions` with value `top`

**Comment by ericsia** [comment]
> You can use the `editor.snippetSuggestions` with value `top`

I have an extension for vscode marketplace, is there anything I can do for my user so this setting apply to that particular language automatically?
Meaning they don't need to manually add that line causing other language snippet appeared on top too.
Like is there an existed configuration for package.json?

**Comment by ericsia** [comment]
> You can use the `editor.snippetSuggestions` with value `top`

@jrieken  I have an extension for vscode marketplace, is there anything I can do for my user so this setting apply to that particular language automatically?
Meaning they don't need to manually add that line causing other language snippet appeared on top too.
Like is there an existed configuration for package.json?
