### ISSUE TITLE
why is my window / title bar orange?

### ISSUE THREAD

**Issue by amilz** [microsoft/vscode#143391]
Issue Type: <b>Performance Issue</b>

i opened a new repo and my title bar is orange. it makes me think there is something wrong...but there's no warning. it's unclear what is going on!?

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by amilz** [comment]
nothing?

**Comment by roblourens** [comment]
Status bar (bottom) or title bar (top)?

The status bar is orange when the window has an active debug session

**Comment by amilz** [comment]
Thanks @roblourens. It's both. See screenshot: 
![image](https://user-images.githubusercontent.com/85324096/155259575-5c967d8b-73fa-4b7f-b1c5-39b5caf30563.png)

**Comment by roblourens** [comment]
You could have color overrides in settings for that workspace, or an extension that is doing this. Check `.vscode/settings.json` or your extensions

**Comment by PEZ** [comment]
This just happened to me when pulling a branch from a PR. The contributor had added it temporarily. Funny it was orange in my case too, so I could find help here. Adding the following line to maybe help people googling for it with other colors:

## Why is my VS Code window / title / status bar orange / blue / green / red / pink / purple / yellow / gray / black / white?
