### ISSUE TITLE
quick pick cursor will not move to the right

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#14337]
- VSCode Version: Insiders 1.7 (c038219f8d137b4972a15346b81ea03751d669d4)
- OS Version:Mac

Steps to Reproduce:

1. Cmd+P to open quick open
2. type in any number of characters that match a file name
3. press left arrow to move to the left
4. press right arrow to move to the right

result: cursor does not move to the right.

**Comment by wprater** [comment]
related to #14350 

/cc @bpasero
