### ISSUE TITLE
Changes are not automatically detected

### ISSUE THREAD

**Issue by ekutner** [microsoft/vscode#143371]
Issue Type: <b>Bug</b>

I'm reporting two issues together here because I believe they may be related.

**Issue #1** - In a multi-root container, file changes are not consistently auto-detected in the source control tab. The are only detected after pressing the refresh button. This sometimes works for the folder that was mounted with "mounts" instruction the devcontainer.json but sometimes it doesn't. I couldn't find a pattern for when it does and when it doesn't.

**Issue #2** - In this example folder2 is a Python module that is used by the module in folder1. When editing files in folder1 the intellisense is not aware of changes made to the module in folder2 after the initial load of teh container.

Steps to reproduce:
1. Create a worksapce folder.
2. Clone https://github.com/ekutner/home-connect-hass into a subfolder called home-connect-hass
3. Clone https://github.com/ekutner/home-connect-async into a subfolder called home-connect-async
4. Open the home-connect-hass folder in vscode. Let it build the container.
5. Add /workspaces/home-connect-async to the workspace
6. Save the workspace file to the local folder home-connect-hass
7. Close vscode and reopen the workspace.

Expected behavior:
File changes are automatically detected by source control and intellisense across root folders.

Actual behavior:
File changes are not auto-detected by git.
File changes in module2 (home-connect-async in the above example) are not reflected in module1 (home-connect-hass).

**This issue may be related to #142694**

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.93GB (18.92GB free)|
|Process Argv|--crash-reporter-id 90988990-5651-4903-8dfa-d0915a585e95|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Home Connect Alt Integration Development|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3695)|
|Memory (System)|23.44GB (17.00GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-drawio|hed|1.6.4
vscode-auto-open-markdown-preview|hnw|0.0.4
better-cpp-syntax|jef|1.15.13
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.217.4
remote-wsl|ms-|0.64.2
material-icon-theme|PKi|4.13.0
material-theme|zhu|3.13.19

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
testflightcf:30433671
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc009:30440023
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343

```

</details>

**Comment by DoubleCorner** [comment]
I have the same problem with issue 1, also a multi-root container. use [git add] or [git commit], file changes are not consistently auto-detected in the source control tab. The are only detected after pressing the refresh button.
version: 1.64.2. macOS: 12.2.1

**Comment by bpasero** [comment]
This issue could originate from a problem with file watching. Let me explain how file watching works in VSCode first and then provide some details how to get more logging data from how file watching behaves in your case.

**Synopsis**
VSCode has different strategies for file watching depending on your workspace and setup:
* no folder opened: files in opened editors are watched via node.js `fs.watch`
* folder opened: folder is watched recursively for all changes via [parcel](https://github.com/parcel-bundler/watcher), opened editors with files not within the folder are watched via node.js `fs.watch`

If you are connected to a remote (SSH, WSL, Docker), the file watcher will run within the target file system. As such, even though you maybe on Windows where VSCode runs, if the remote is Linux, the file watcher will run in the Linux environment.

**Platforms**
Depending on the platform you are on, file watching is differently implemented:
* macOS: using `fsevents` services
* Windows: using `ReadDirectoryChangesW` method
* Linux: using `inotify`

Specifically on Linux, watching a large folder recursively can result in VSCode consuming too many file handles. If that is the case, you will see a warning notification with instructions how to solve that.

**Limitations**
File watching comes with a set of limitations:
* symbolic links are not followed automatically but you can explicitly add symbolic links to be watched via the `files.watcherInclude` setting
* mapped network drives or third party file system drivers are not guaranteed to produce file events
* in general, the operating system may decide to drop file events at any time, there is no 100% guarantee

**Settings**
Please review your settings to see if maybe a folder is excluded by accident. Specifically, the `files.watcherExclude` setting is relevant.

**Logging (local)**
!!! This is ONLY when you open a local workspace, for remote see below !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the local workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `Help | Toggle Developer Tools`
* select `Console`
* filter the output by typing `File Watcher` into the filter box
* attach the output when doing the operation that exhibits the issue

![image](https://user-images.githubusercontent.com/900690/156323290-f3ba6470-dfed-4066-a19c-951395611738.png)

**Logging (remote)**
!!! This is ONLY when you open a remote workspace (WSL, Docker, SSH), for local see above !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the remote workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `View | Output`
* select `Log (Remote Server)` from the dropdown
* attach the output when doing the operation that exhibits the issue

![image](https://user-images.githubusercontent.com/900690/156323886-6b7dfa25-d6ac-4316-9150-80e5c8104d04.png)

**Comment by ekutner** [comment]
I verified that the watcherExclude has only the default settings:
```
"files.watcherExclude": {
  "**/.git/objects/**": true,
  "**/.git/subtree-cache/**": true,
  "**/node_modules/*/**": true,
  "**/.hg/store/**": true
}
```

Here is the [trace log](https://github.com/microsoft/vscode/files/8171615/vscode.trace.1.txt). The log has two file edits, one in the "main" folder (home-connect-hass) and one in the mounted folder (home-connect-async), there are no file watcher events at all. 
Note that the behavior is now a bit different than what I described above. Previously, changes were detected in the mounted folder/volume but not in the main folder/volume, where the devcontainer is. Now, changes are not detected at all, in either volumes. I'm not sure exactly what has changed but at least it's more consistent.

**Comment by bpasero** [comment]
@ekutner can you run `code --verbose` from the command line and do the steps again, this time you don't have to change the trace level within the application as it will be in trace mode from startup. This ensures we print the initialization of the file watcher on startup, e.g. a message like this one:

```
[2022-03-02 19:41:34.284] [remoteagent] [trace] [File Watcher (parcel)] Request to start watching: /Users/bpasero/Desktop/test-ts (excludes: **/.git/objects/**,**/.git/subtree-cache/**,**/node_modules/*/**,**/.hg/store/**,/Users/bpasero/.vscode-server-oss-testresolver/extensions/**)
[2022-03-02 19:41:34.285] [remoteagent] [trace] [File Watcher (parcel)] Started watching: '/Users/bpasero/Desktop/test-ts' with backend 'fs-events' and native excludes '/Users/bpasero/Desktop/test-ts/.git/objects, /Users/bpasero/Desktop/test-ts/.git/subtree-cache, /Users/bpasero/Desktop/test-ts/.hg/store'
```

**Comment by ekutner** [comment]
@bpasero 
Here is the [log](https://github.com/microsoft/vscode/files/8172455/vscode.trace.4.txt). The file watcher is starting to watch the relevant folders but the file changes (at the end of the log) are not detected.

**Comment by bpasero** [comment]
Yes, so it looks like `/workspaces/home-connect-hass` is watched recursively. Can you please do the following:
* open vscode on that folder as usual
* select "Duplicate as workspace in new window"
* put the 2 windows side by side
* open any file that is within `/workspaces/home-connect-hass` in both windows as text editor
* make changes in the 1 window to that file and save
* see if the file in the other way updates properly

Thanks

**Comment by ekutner** [comment]
I tried that.
If I edit a file directly under workspaces/home-connect-hass or under workspaces/home-connect-async then those changes are detected immediately by the other window. However, if I edit a file in a subfolder of these folders then the change is not detected by the other window until I click into it and bring it into focus.
Interestingly, even when editing files in the root, which are automatically picked up by the other window, only git tab of the vscode window where the edit was made is reflecting that the file was changed.

**Comment by bpasero** [comment]
Curious if you could attach the full logs for those scenarios just to see what is logged for when it works and when it does not work.

**Comment by ekutner** [comment]
Here is the [full log](https://github.com/microsoft/vscode/files/8178475/vscode.trace.5.txt), the interesting stuff is at the end. Edited 4 files, one in each root folder and one in a subfolder of each root.

.

**Comment by bpasero** [comment]
Yeah that is strange indeed. You mentioned https://github.com/microsoft/vscode/issues/142694 could be related, but in that case the sub-directory-structure is really created ad-hoc and does not exist on startup. If all folders are there right on startup, I would expect `parcel` to recursively attach itself to all folders within the workspace without problems. 

So it does seem as if either:
* `parcel` does not attach itself recursively to subfolders
* no events are emitted from subfolders, maybe due to the fact that this is WSL

Next thing to try: if you explicitly add the sub-folders via the `files.watcherInclude` setting, does that work? One thing to note is that symbolic links are not automatically followed for watching, but not sure these subfolders would be symbolic links or not.

**Comment by ekutner** [comment]
It didn't make any difference and none of these subfolders is a symlink.
I tried using fswatch to monitor the file system independently of vscode and found something interesting. When making changes to root level files (those that vscode also detects), fswatch detects the change and reports the full path of the file, however, when changing a file in a subfolder, fswatch also detects the change but only reports the directory path of the file, without the file name. This behavior is not related to the location of the watch, it behaves the same if I place the watch on /workspaces/home-connect-hass or on /workspaces . This makes me think that this is either a problem with docker itself or with the way the volume is mounted, because the file watching only works for the root of the two mounted volumes.
I'm not sure where to take it from here.

**Comment by bpasero** [comment]
Yeah good findings, I was suspecting an upstream issue with the setup too and feel VSCode cannot really resolve them. I suggest to take this issue to them via https://github.com/microsoft/WSL/issues and continue the discussion there.

**Comment by ekutner** [comment]
I can reproduce the issue with a clean container that I created manually, without vscode at all, so the root cause is definitely upstream. That said, I see that this is a known issue with WSL1 and there is a polling based workaround in vscode, since I'm using WSL2 I assume this workaround doesn't kick in, but maybe it would be a good idea to enable it for WSL2 as well.

**Comment by bpasero** [comment]
@aeschli is there a way to force polling for file watching in WSL2?

**Comment by ekutner** [comment]
@bpasero @aeschli 
Looking into issues in the WSL project, this still seems to be a problem in WSL2. There is even a suggested workaround (https://levelup.gitconnected.com/docker-desktop-on-wsl2-the-problem-with-mixing-file-systems-a8b5dcd79b22), which I find unreasonable. Looks like polling would be a good temporary solution until it is resolved at the WSL level.

**Comment by aeschli** [comment]
No, for WSL2 we don't offer to turn on polling.
WSL2 has a known issue of lack of events when the resources are on a mount (e.g. the `/mnt/c/...` mount): https://github.com/microsoft/WSL/issues/4739. 
The problem with `/mnt/c/...` is that file accesses are much slower, so polling is running into performance issues.

**Comment by ekutner** [comment]
@aeschli Since a lot of vscode functionality seems to depend on getting these events it seems that polling is the only option. Even  if it's done every 30 seconds , to overcome the performance issue, it's still much better than not having it at all. I would also guess that the slow performance is only noticeable with very large projects which, are probably not the majority of projects out there. Since the functionality already exists for WSL1 why not enable it for WSL2 as well?

**Comment by aeschli** [comment]
The proper thing is if this is fixed in WSL. There are other tools besides WSL that depend on reliable file events. I've talked to the WSL team and they are aware of the request.
