### ISSUE TITLE
The list of available terminals doesn't show up and the default profile not respected

### ISSUE THREAD

**Issue by cateyes99** [microsoft/vscode#143307]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: _**1.64.2** portable zip version_
- OS Version: _**Windows 10 Enterprise**, Version 20H2, OS Build 19042.1415_

The issue:

1. With _**1.64.2**_, i found it doesn't show up the list of available terminals
![image](https://user-images.githubusercontent.com/19678455/154563320-8a02ec7e-9824-4185-a37f-55c1a2dd1df6.png)
While until _**1.63.2**_, VSCode always show the list correctly without problem as:
![image](https://user-images.githubusercontent.com/19678455/154563837-bd9f96f7-f1c1-4daa-ad86-0bc0279e1edd.png)
More oddly, sometimes when i check with _**1.64.2**_ after many actions being done, it will show the list up though (I haven't figured out what makes the list show up eventually though)

2. I have a setting in my user **settings.json**: `"terminal.integrated.defaultProfile.windows": "Command Prompt",`. In the case of the list disappeared, _**1.64.2**_ will make only the `pwsh` terminal available. When trying to open a terminal, it just opens a `pwsh` terminal, instead of a `Windows CMD`. Looks like it doesn't respect my setting.
![image](https://user-images.githubusercontent.com/19678455/154565595-20af49d5-b466-46c8-b1d4-586c23abd8bc.png)

3. I've run _**1.63.2**_ and _**1.64.2**_ side by side, whenever _**1.64.2**_ has the issue occurring, _**1.63.2**_ always runs perfectly.

**Comment by cateyes99** [comment]
I found if giving enough time the list of available terminals will eventually turn up. I think it's related to the fact that it's company's laptop, and the company set up some **windows profile folders** to **remote** locations. So on VPN, this issue won't occur for **_1.64.2_**, as it can access those remote folders immediately. Off VPN, it occurs from time to time.

I think there is another issue I observed only with **_1.64.2_**, not **_1.63.2_** which is also related. Go to the `Extension View`, observe it takes really **ages** (_about 5, 8, or 12 minutes_) to show the extensions! Same thing. On VPN, there's no issue. Off VPN, it happens very often.

When these issues (including the **Extension View** issue mentioned just now) happens, the subsequent **VSCode windows** opened will suffer the same issues. Once the list of available terminals and the extensions show up eventually (_also interestingly, i observe the list of available terminals and the extensions might take different time to show up_ ), the subsequent **VSCode windows** opened won't suffer these issues then. But giving a long enough time, the issues come back (_but I also observed that sometimes when the terminal issue came back, the extensions turn up OK_).

But not sure why my terminal's default profile setting won't be respected in this case.

**Note**: **_up to 1.63.2_**, VSCode doesn't have these issues at all. I guess, 1.64.2 might have changed to somehow touch some of those remote windows profile folders on my laptop, but doesn't really use them, so after long time trying to access the remote folders and failed, it can still work fine and show up the list of available terminals and the extensions!

> does this happen for only the first terminal that you open?

@meganrogge, No, it happens to the following terminals opened, until the list of available terminals eventually shows up.

**Comment by meganrogge** [comment]
Our understanding of this issue is that when off of VPN, VSCode can't access certain folders so certain features are slow/don't work. Not sure there's anything we can do about this, so closing this as out-of-scope.

**Comment by cateyes99** [comment]
@meganrogge but as I said, up to **1.63.2**, VSCode doesn't have this issue. when running **1.63.2** side by side with **1.64.2**, **1.63.2** doesn't have this issue, but **1.64.2** does.

**Comment by adinriv** [comment]
I see the same behavior on Red Hat Enterprise Linux release 8.5 (Ootpa) on local folders.  Not accessing a VPN.
