### ISSUE TITLE
Multi-target debugging - Can trigger commands with keyboard but not buttons, or vice-versa

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14334]
Sometimes when debugging, keyboard shortcuts for debug actions stop working, but I can click the buttons in the debug palette to do actions. Or, the other way around. Often I try to kill the processes with 'shift+F5' and it works the first time, but I have to click the stop button to kill the second process.

**Comment by roblourens** [comment]
#14171

**Comment by isidorn** [comment]
db09b30 should fix this. And I can not repro this after that push,
Can you please try reporoducing this and if you can let me know.
Even if you can not find steps let me know if it happens and I will reopen. Thanks!
