### ISSUE TITLE
Install in browser option not shown when installing extension that prefers ['ui', 'web'] on remote 

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#143327]
- VS Code Version: stable and from sources

Steps to Reproduce:

1. Run server `./scripts/code-server.sh --without-connection-token --install-extension=ms-vscode.anycode --install-extension=ollyhayes.colmak-vim --start-server`
2. Open code in browser and got to extensions view
3. Observe `ms-vscode.anycode` has option to `Install in browser`
4. :bug: Observe `ollyhayes.colmak-vim` doesn't have option to `Install in browser`

![image](https://user-images.githubusercontent.com/25115070/154594279-7ca4af9f-f672-4d6d-9154-bea4c615dff5.png)
![image](https://user-images.githubusercontent.com/25115070/154594359-bfb41ace-79a5-4b44-bb6e-e4082b52b038.png)

**Comment by jeanp413** [comment]
Created PR #143328 fixing this cc @sandy081

**Comment by sandy081** [comment]
/duplicate 

https://github.com/microsoft/vscode/issues/142007

**Comment by jeanp413** [comment]
@sandy081 I think you linked the wrong issue, https://github.com/microsoft/vscode/issues/142007 is for showing a `installed` section in the extensions view.
Could you link the correct issue please :pray:

**Comment by sandy081** [comment]
Sorry for wrong link. Here is the actual issue - https://github.com/microsoft/vscode/issues/141322
