### ISSUE TITLE
Draw focus border over whole status bar once the full status bar is focused

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#143379]
1. Focus in the editor
2. Press F6
3. Focus is now on the whole status bar. Or if it is on an item press `esc` to move focus on the full status bar.
4. We should render the new nice outline over the whole status bar. As we do over individual items now.

**Comment by isidorn** [comment]
@daviddossett yes! This looks great!

You can actually tab onto it, but the focus behaviour is a bit specialised. The focus will remember what last element had focus in the status bar and focus that one directly. If no element had focus previously than the whole status bar will get focused. And you can always focus the full status bar by pressing `esc` as you discovered.
So in short: yes, this is by design :)

**Comment by isidorn** [comment]
@daviddossett great, thanks a lot 👏

**Comment by bpasero** [comment]
Is the color properly wired in? See https://github.com/microsoft/vscode/issues/144574 and https://github.com/microsoft/vscode/issues/144586

**Comment by i007c** [comment]
> Is the color properly wired in? See #144574 and #144586

if you change the `statusBar.focusBorder` token. value of `--vscode-statusBar-focusBorder` will chane but not the `--statusbar-focusborder`!

**Comment by daviddossett** [comment]
Moved this from the stylesheet to use the same logic as we use for status bar items.

https://github.com/microsoft/vscode/blob/0140fba8bb128d7481a4bcd380de774ab1210c5d/src/vs/workbench/browser/parts/statusbar/statusbarPart.ts#L530-L534
