### ISSUE TITLE
Multi-target debugging - Breakpoints show as unbound, but execution still pauses there

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14332]
We saw this with the Go debugger and node2, but not node.

Set breakpoints in two files. Launch them with two separate configs and a 'composite' config. In one file, the breakpoint will show as unbound, but execution still pauses there, because it is actually bound.

This doesn't happen with every setup, but it happens pretty often, and I have one where it happens every time that I can send if needed. The logs show that the debug adapter reported the bp as verified.

**Comment by roblourens** [comment]
#14171

**Comment by weinand** [comment]
@isidorn breakpoint validation state needs to track the current session too.

**Comment by isidorn** [comment]
@weinand true. However that is currently not working perfectly and that I plan to adress in november

**Comment by ramya-rao-a** [comment]
Verified in Go

**Comment by roblourens** [comment]
And Node
