### ISSUE TITLE
Workspace makes "Go To File... Ctrl+P" rather slow

### ISSUE THREAD

**Issue by sacredaioros** [microsoft/vscode#143356]
I'm using Remote SSH to editor a python project on Debian 10.11.
I found that if i create a workspace which contains multiple folders, it is rather slow to use "Go To File... Ctrl+P"(it takes several minutes to find a file).
But if I do not use workspace , it tooks only several seconds to find the same file.

my workspace meta:
|  Remote: SSH: *.*.*.*|    Folder (Python): 19457 files|      File types: py(14984) pyc(3135) pyi(263) so(71) txt(21) md(13) pyw(8)
|                  xml(7) pkl(4) json(3)
|      Conf files: settings.json(1)

my enabled extensions:
Extension | Author (truncated) | Version
-- | -- | --
project-manager | ale | 12.5.0
vsc-material-theme | Equ | 33.1.2
vsc-material-theme-icons | equ | 1.2.2
better-cpp-syntax | jef | 1.15.13
vscode-boost-jam | mlo | 0.0.2
jupyter-keymap | ms- | 1.0.0
remote-containers | ms- | 0.217.4
remote-ssh | ms- | 0.74.0
remote-ssh-edit | ms- | 0.74.0
remote-wsl | ms- | 0.64.2
vscode-icons | vsc | 11.10.0
doxdocgen | csc | 1.3.2
gitlens | eam | 11.7.0
better-cpp-syntax | jef | 1.15.13
code-eol | jef | 1.0.11
svn-scm | joh | 2.15.3
regionfolder | map | 1.0.15
git-graph | mhu | 1.30.0
python | ms- | 2022.0.1814523869
vscode-pylance | ms- | 2022.2.3
jupyter | ms- | 2022.1.1301854968
jupyter-keymap | ms- | 1.0.0
jupyter-renderers | ms- | 1.0.6
cmake-tools | ms- | 1.9.2
cpptools | ms- | 1.9.0
cpptools-extension-pack | ms- | 1.1.0
autodocstring | njp | 0.6.1
indent-rainbow | ode | 8.2.2
cmake | twx | 0.0.17

**Comment by roblourens** [comment]
Can you give some more details? Searching more stuff simultaneously will be slower. How much slower? How many folders?

**Comment by sacredaioros** [comment]
My first folder has 19461 files. It usually tooks 2-3 seconds to find a file.
Then I add a second folder which contians less than 10000 files. It tooks 2-3 minutes to find a file.

**Comment by sacredaioros** [comment]
![image](https://user-images.githubusercontent.com/39549937/154899761-ec7b87e7-70c8-4aa5-a40b-e9cb2d26cc16.png)

**Comment by sacredaioros** [comment]
I found that if Pylance Plugin is enabled, "Go To File" became very slow...

**Comment by roblourens** [comment]
I guess you have `search.quickOpen.includeSymbols` enabled?

**Comment by sacredaioros** [comment]
Oh, yes.. 
That works for me.
Thank you.
