### ISSUE TITLE
Exclude folders from implementation search

### ISSUE THREAD

**Issue by sonalys** [microsoft/vscode#143352]
I use "search for all implementations" for GoLang all the time, however, vs code almost always choose the mock folder instead of the real implementation, I would love to see an option to hide any specified folders from the implementation search.

Example:
![image](https://user-images.githubusercontent.com/15274059/154641915-c06b50b6-e518-4950-9955-bc0d5f950366.png)

It would be much more assertive if I could always ignore the mock folder because I will never want to see the mock implementation.

**Comment by roblourens** [comment]
I think this would be a feature request for the Go extension
