### ISSUE TITLE
No option to login through github.com

### ISSUE THREAD

**Issue by Dragonizedpizza** [microsoft/vscode#143301]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
f80445acd5a3dadef24aa209168452a3d97cc326
x64

- OS Version: Arch Linux Rolling

Steps to Reproduce:

1. Select "Publish to GitHub" from the commands pallete.
2. attempt to login to GitHub.
3. Get no option on the method to login, only this:
![image](https://user-images.githubusercontent.com/70718540/154548442-2bb05573-0e8d-4760-bf4a-b48c22506701.png)

**Comment by TylerLeonhardt** [comment]
Can you tell me how you installed vscode and what package you used?
