### ISSUE TITLE
autocorrect in text elements html

### ISSUE THREAD

**Issue by Cheespeasa1234** [microsoft/vscode#143304]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.53.2
- OS Version: Mac OS 10.15.7 catalina

Steps to Reproduce:

1. Make a new HTML file...
2. Make a new text element.
3. Start typing some stuff out.

What happens:
It will try to autocorrect words you have ever said in a text element. For example, if I type Hello in a `<p>` element then later on in the file, try to type Help, it will suggest I say hello.

Please make it so that it does not autofill in a text element.

**Comment by aeschli** [comment]
What do you mean by 'autofill' ? It will propose hello, but it should not select it automatically unless you press tab or enter.

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/207405443-8524b9c8-e9fe-45c4-bd09-55d5ca178479.png)
