### ISSUE TITLE
Valid regex pattern being rejected

### ISSUE THREAD

**Issue by misery7111** [microsoft/vscode#143347]
Issue Type: <b>Bug</b>

Pattern: a(],\[|$)
Valid in other editors

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: Yes

**Comment by misery7111** [comment]
> You forgot to take code into backticks so it's unclear if some of escapes are missing in report
> 
> From how it looks not `a(],[|$)` - this one is both invalid for JS (find, editor widget) and PCRE2 (find in files).
> 
> You need to escape `[` as it converts closing group to regular `)` and doesn't have corresponding closing bracket itself and for capture group.

Actually, I did escape the [, but github reformat the report :)
The pattern is (],\\[|$)
![Video_2022-02-19_070301](https://user-images.githubusercontent.com/34360739/154779220-880a62f1-03ae-42f3-8bb4-8bc56b23dce8.gif)

**Comment by thebinarysearchtree** [comment]
vscode adds the unicode flag behind the scenes which makes that regular expression invalid. You will have to do ```(\],\\\[|$)```

**Comment by thebinarysearchtree** [comment]
It is a valid regular expression, but vscode adds the unicode flag behind the scenes and then it becomes an invalid regular expression. You have to escape both the ```]``` and the ```[``` when the unicode flag is set.

**Comment by misery7111** [comment]
> (\],\[|$)

This is the problem. Thanks a lot everyone.
