### ISSUE TITLE
Names of the terminals are no longer displayed

### ISSUE THREAD

**Issue by sckraa** [microsoft/vscode#143400]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.2
- OS Version: Linux x64

Steps to Reproduce:

1. Open the terminal tab
2. Create a new terminal (so now we have 2 terminals)
3. Close the terminal tab without killing the terminals
4. Reopen the terminal tab

After the last update of VS Code, the names of the terminals are no longer displayed when I reopen the terminal tab. 

![vs_code_terminal_issue](https://user-images.githubusercontent.com/45497492/154742549-88e64e0b-cf19-4251-9bc7-50156f0943ca.png)

**Comment by ArturoDent** [comment]
Possibly related:  https://github.com/microsoft/vscode/issues/139868 and https://github.com/microsoft/vscode/issues/139276.

**Comment by meganrogge** [comment]
Fixes itself (refreshes) when you click on a terminal tab
