### ISSUE TITLE
Python fold also collapses vertical white space

### ISSUE THREAD

**Issue by Qudware** [Microsoft/vscode#14346]
- VSCode Version: 1.6.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a python script with functions/classes/code block (thing that you can fold)
2. Add some new lines after the code block 
3. Press the [-] on the left to fold the code block
4. Observe as the new lines (that don't belong to the code block) also collapse into the block
5. This means you can't have vertical space between collapsed blocks!

This is really annoying when working with python. This behavior is not present in Visual Studio nor in Atom so I'm sure it is not expected behavior.

**Comment by aeschli** [comment]
Note that folding in VSCode is purely indentation based. There is no language awareness at the moment. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.
The request for language aware folding is #3422

**Comment by acls** [comment]
This would be fixed by PR #26258
