### ISSUE TITLE
Opening file with same name but different folder appends a suffix to the filename

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#143414]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:24.333Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.50

Steps to Reproduce:
1. Open vscode.dev
2. Go to File->Open File and open the file
3. Click the x in the file bar to close the file
4. Open the same file again

Expected: The same file opens: test-file.txt
Actual: The same file opens with the suffix -2: test-file.txt-2. This breaks language services for the file.

![close-file-error](https://user-images.githubusercontent.com/22576531/154756120-7759b372-287f-4133-92af-7311186d92d1.gif)

**Comment by bpasero** [comment]
This maybe impossible for us to fix given https://github.com/microsoft/vscode/issues/136486

**Comment by bpasero** [comment]
Unfortunately, a handle we get from the local file system API does not carry the full absolute path and as such we do not know whether the same file is opened or a different file with the same name. We store the handle in memory for the duration of the usage and need to come up with a `URI` to associate the handle with. As such, when a handle with the same name shows up, we just append a number to produce a unique handle identifier. We used to encode this information in the authority part of the `URI` but that was causing other issues. 

I fear it will not be so easy for us to move away from this model.

**Comment by alyssajotice** [comment]
Would it be possible to not store the handle in memory or delete it when closing the file? Then subsequent opens would be treated the same as first opens.

**Comment by bpasero** [comment]
> Would it be possible to not store the handle in memory

No, one limitation of the file system handle API is that you can only get a handle by asking the user for a file or folder from a dialog, there is no other way. You cannot just get a handle without the dialog (or maybe drag and drop, but that is equally a user action).

> or delete it when closing the file

That is something I would like to avoid actually. Because the layer at where the file system handle comes into the system is really low level and editors are high level. There is no ref-counting of file handles between these 2 components because file handles typically do not have a lifecycle for normal operations. I would not want to add this kind of tangle only to workaround a limitation in the file system API.

**Comment by bpasero** [comment]
Wow, I just found out `FileSystemHandle.isSameEntry` which can be used to compare an existing handle to a new one. With this we can avoid appending numbers to files and even folders that have been opened.

**To verify:**
* opening the same file multiple times does not append suffix
* opening the same folder multiple times does not append suffix

**Comment by alyssajotice** [comment]
This is great. Thanks @bpasero!

**Comment by meganrogge** [comment]
I can still reproduce the issue

**Comment by meganrogge** [comment]
![Recording 2022-02-28 at 15 46 11](https://user-images.githubusercontent.com/29464607/156063916-43d9adc0-996a-4489-ad08-b8638a7183b3.gif)

**Comment by bpasero** [comment]
Same here until I reloaded the page, seems like a caching issue, filed https://github.com/microsoft/vscode/issues/144146

**Comment by rzhao271** [comment]
I can reopen the same folders and files just fine now, but I see something off after opening two different package.json files:
![Screenshot showing second package.json file fail to pick up syntax highlighting](https://user-images.githubusercontent.com/7199958/156215278-56a55a3c-0258-464c-8e92-b83ae64863c5.PNG)

The editor is probably confused at what `.json-2` is.

**Comment by bpasero** [comment]
Oh yeah, nice catch. Instead of adding the suffix at the end, we really need to put it before the extension. I can fix that for March!

**Comment by bpasero** [comment]
Oh and this was actually the original issue reported too, lets reopen and move to March then, since this is only fixed partially.

**Comment by bpasero** [comment]
The increment is now put after the file name but before the extension:

![image](https://user-images.githubusercontent.com/900690/156313465-6aa404f2-ca18-4402-aeab-514f71fa8584.png)

I cannot really address this for language contributions that match on the full file name, such as `.gitignore` though, but I think that is tolerable for now until we figure out a better solution.
