### ISSUE TITLE
Test: Shell integration command and directory previous session history

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#143430]
Refs: #141006, #141009

- [x] macOS @paulacamargo25
- [x] linux @isidorn
- [x] windows @karthiknadig

Complexity: 3

Authors: @Tyriar, @meganrogge 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23143430%0A%0A&assignees=Tyriar,meganrogge)

---

Shell integration now features persisting recent commands and directories across sessions. These are accessible via the following commands:

- `workbench.action.terminal.runRecentCommand`
  - Handy keybinding: `{ "key": "ctrl+space", "command": "workbench.action.terminal.runRecentCommand", "when": "terminalFocus"}`
- `workbench.action.terminal.goToRecentDirectory`

You need shell integration enabled to add entries to these commands.

Ideas for testing:

- Running commands in the terminal adds entries to recent commands
- Running commands in pwsh on Windows cannot be accessed in cmd (this shell detection isn't implemented yet on non-Windows)
- Changing the directory in the terminal adds entries to go to recent directory
- `terminal.integrated.shellIntegration.history` configured the history limit of each type
- The history works as expected across multiple windows
- `Terminal: Clear Command History` clears all history
- Entries from the `previous sessions` section can be removed

**Comment by paulacamargo25** [comment]
I'm closing the issue even though there are some open bugs, please let me know if that isn't the right thing to do.

**Comment by isidorn** [comment]
@paulacamargo25 once we have all tested the item it is the right thing to close it even though there might be open issues :)
