### ISSUE TITLE
Test: Light Hight Contrast Theme

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#143425]
Refs: #143398 

- [x] macOS @alexdima
- [x] linux @roblourens
- [x] windows @luabud

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23143425%0A%0A&assignees=daviddossett)

---

A new light high contrast theme was added to the default themes list accompany our dark high contrast theme. While there will be more work needed to react to OS-level light/dark HC modes, this first step simply adds the theme marked as "Beta" so we can collect early feedback on the theme itself. 

Scenarios to test:
- Open a folder with at least a few folders/file. Verify text readability/contrast on main UI areas (sidebar, titlebar, tabs, quick pick, etc.)
- Open the terminal and run a few basic commands (e.g. npm i). Verify text readability/contrast on output.
- Open a file. Verify syntax token readability/contrast.
- Make a change and view the diff. Verify that changed lines are easily identified.
- Bonus: poke around the areas of the UI you are most familiar with to see if there are any obvious issues.

**Comment by isidorn** [comment]
Let's increase complexity to 3 since I think this can be time consuming :)
