### ISSUE TITLE
Keybinding for recently opened projects / folders functionality

### ISSUE THREAD

**Issue by nottoseethesun** [Microsoft/vscode#14342]
- VSCode Version: Version 1.6.1 (1.6.1)
- OS Version: Mac OS Sierra

Currently, apparently the user must mouse over to the VS Code "File" menu and click before keys can be used to select the recent Folder to open. 

It would be good to at least have a  way to open the "File" top menu with a keybinding.  Or alternatively, some keybinding to browse recent projects.

**Comment by bpasero** [comment]
You can assign a keybinding to `workbench.action.openRecent` for this functionality.

**Comment by kaiwood** [comment]
@nottoseethesun Besides `workbench.action.openRecent`  (wich is even bound to `^r` by default) that bpasero mentioned, there are 2 global shortcuts provided by the OSX, that might help you for every other application as well:

`Move focus to the menu bar`

<img width="780" alt="screen shot 2016-10-25 at 07 25 16" src="https://cloud.githubusercontent.com/assets/7542/19673985/165f0fdc-9a85-11e6-9ebc-8afccd6945b3.png">

The second one was introduced with Snow Leopard and I consider it as an essential one, that every keyboard focused OSX user should know:

`Show Help menu`

<img width="780" alt="screen shot 2016-10-25 at 07 25 37" src="https://cloud.githubusercontent.com/assets/7542/19674069/a73a7726-9a85-11e6-81c8-2fcc2cd77c4e.png">

It sounds so innocent, but the first entry in the Help menu is the search feature where you can narrow-down-search the complete menu. It's basically VSCode's command palette

**Comment by nottoseethesun** [comment]
Using the tip above, here's what I ended up doing (wfm):
```
// Place your key bindings in this file to overwrite the defaults
// Place your key bindings in this file to overwrite the defaults
[
  {
    "key": "cmd-shift-o",
    "command": "workbench.action.openRecent",
  }
]
```
