### ISSUE TITLE
Is there an existing feature to split the right panel into 2 parts vertically?

### ISSUE THREAD

**Issue by EizEddin** [microsoft/vscode#143499]
Is there an existing feature to split the right panel into 2 parts vertically? If not, it will be very helpful to have this feature.

So we could for example have the termina view on the top, and the outline at the bottom. Almost like having multiple views over each other on the left side panel.

Something like this (picture copied from the internet):

![image](https://user-images.githubusercontent.com/3897959/154846079-435c4b8c-8982-4204-9ebb-d5389b735031.png)

**Comment by yume-chan** [comment]
You can drag and drop another view into it, if you were not using such an old version of Code.

**Comment by EizEddin** [comment]
Thanks @yume-chan,
Yes actually it works as you mentioned, I didn't know that feature already exists and that simple 👍
