### ISSUE TITLE
Command start decoration problems

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#143421]
The new decoration when the command starts appears alongside the future decoration, should we dispose of the temporary command decoration when the real one gets registered? Additionally we should stick it on the line where the command starts, not the prompt starts:

![image](https://user-images.githubusercontent.com/2193314/154771186-24a53d57-4c47-432e-8128-fa7c8dfe8aae.png)

**Comment by meganrogge** [comment]
This is either only a problem for Windows or only a problem for multi-line prompts
![Recording 2022-02-22 at 11 22 43](https://user-images.githubusercontent.com/29464607/155184999-704afcd4-7bd3-4c42-8252-456595cfd32d.gif)

**Comment by meganrogge** [comment]
the placeholder gets disposed of whenever a command is finished

https://github.com/microsoft/vscode/blob/2de0f469d8f3b37ef3c974985198c0a17afa3e6a/src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts#L117-L120

**Comment by Tyriar** [comment]
I think it's only a problem with multi-line prompts, makes the experience really bad for mine as I use starship or other similar ones.

**Comment by meganrogge** [comment]
oh that's because we don't track changes to the prompt variable ?

**Comment by meganrogge** [comment]
can confirm that just using command start marker instead of prompt start marker fixes the issue for shells with multi-line prompts
![Screen Shot 2022-02-22 at 12 01 56 PM](https://user-images.githubusercontent.com/29464607/155191947-ddfeeb15-0bf7-46b1-99ab-26c3bfac5a27.png)
