### ISSUE TITLE
Test builtin notebook output renderer

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#143437]
Refs: #142429

- [x] anyOS @kimadeline
- [x] anyOS @karrtikr

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23143437%0A%0A&assignees=rebornix)

---

We moved following mimetypes into the builtin notebook renderer extension

```
"image/gif",
"image/png",
"image/jpeg",
"image/git",
"image/svg+xml",
"text/html",
"application/javascript",
"application/vnd.code.notebook.error",
"application/vnd.code.notebook.stdout",
"application/x.notebook.stdout",
"application/x.notebook.stream",
"application/vnd.code.notebook.stderr",
"application/x.notebook.stderr",
"text/plain"
```

To test the new renderer, yon can

* Open [microsoft/vscode-jupyter/src/test/datascience/notebook/withOutput.ipynb](http://github.com/microsoft/vscode-jupyter/src/test/datascience/notebook/withOutput.ipynb) in VS Code
* Or if you can want to play around with Jupyter a bit
  * Install Python extension
  * Install Jupyter
  * File -> New File... -> Jupyter Notebook to create new file
  * Start to write some python code, you can follow this book https://github.com/donnemartin/data-science-ipython-notebooks 

You don't necessarily have to test all mimetypes but following features are good ones to validate

* Find in Outputs work (e.g., find in output works for text output `print(1)`). Some guidance on how to test find in output https://github.com/microsoft/vscode/issues/141346
* Error output are colorized properly
  ```python
  with Error
  ```
* Large output won't block the UI
  ```python
   for i in range(0, 10000):
     print(i)
  ```

**Comment by kimadeline** [comment]
- [x] Test mimetypes: gif, png
- [x] Find in Outputs work: tested both markdown source and rendered markdown (I also hit https://github.com/microsoft/vscode/issues/141375)
- [x] Error output are colorized properly
- [x] Large output won't block the UI
