### ISSUE TITLE
Click region for removed git lines in the gutter does not match that of the visual location

### ISSUE THREAD

**Issue by jespertheend** [microsoft/vscode#143497]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.65.0-insider (Universal)
Commit: 97c1e76d668d23d568044feb31083407f4c4b1ed
Date: 2022-02-07T08:54:27.868Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0

**Steps to Reproduce**
1. Remove a line in a project with git setup
2. Click right below the red arrow of the removed line

**Expected result**
The changed lines in git opens in peek

**Actual result**
Nothing

https://user-images.githubusercontent.com/2737650/154844458-3bf3c75e-4acd-4be0-a628-cb320d44f51b.mp4

Also see #143496

**Comment by lszomoru** [comment]
This issue has been resolved since the issue has been filed. Please feel free to reopen in case you are still able to reproduce the issue. Thanks!
