### ISSUE TITLE
Braces in new line extension/feature missing

### ISSUE THREAD

**Issue by JulianTmmn** [microsoft/vscode#143459]
I installed VS Code yesterday and I couldn't find an extension or a feature which automatically puts braces in a new line, when coding in C#. There once was a feature request like this before and the guy there said that there once was such an extension. I hope this will come back so my code will be easier to read. Visual Studio 2022 has this feature enabled automatically but for no reason this feature doesnt exist in VS Code.

**Comment by lramos15** [comment]
Maybe the C# extension has something built-in or you can try something like prettier and https://github.com/warrenseine/prettier-plugin-csharp. I'm not too familiar with this exact case but VS Code does allow for extensible formatters.
