### ISSUE TITLE
Status bar doesn't work with vscode.dev

### ISSUE THREAD

**Issue by HRTK92** [microsoft/vscode#143487]
Status bar does not respond

https://user-images.githubusercontent.com/70054655/154835520-b100161e-0326-43ce-a9f5-74c76c0dcc69.mp4

Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
User Agent: Mozilla/5.0 (Linux; Android 11; S8-KC) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.101 Mobile Safari/537.36
Embedder: vscode.dev

**Comment by bpasero** [comment]
Does it work today on https://insiders.vscode.dev/ (make sure to reload 2-3 times, we have a caching issue).

**Comment by HRTK92** [comment]
The status bar is working. Thank you
