### ISSUE TITLE
Settings Sync prompts for login every time VSCode restarts

### ISSUE THREAD

**Issue by shasherazi** [microsoft/vscode#143447]
- VS Code Version: 1.64.2
- OS Version: Linux x64 5.15.21-1-MANJARO

Steps to Reproduce:

1. Restart vscode
2. Asks to login to sync settings

Also happens in the insiders build

**Comment by cp-Coder** [comment]
I am also facing the same issue.

**Comment by shasherazi** [comment]
Do you also use Manjaro?

**Comment by cp-Coder** [comment]
I use Arch Linux

**Comment by TylerLeonhardt** [comment]
Do you have gnome-keyring installed on your system? Or another org.freedesktop.secrets compatible keyring application?

**Comment by shasherazi** [comment]
I don't think so, coz I never even heard of these things (new to linux). Is there a way to check?

**Comment by cp-Coder** [comment]
I didn't install any keyring software on my Arch Linux.

**Comment by HVisMyLife** [comment]
https://github.com/MicrosoftDocs/live-share/issues/224#issuecomment-383324321

**Comment by TylerLeonhardt** [comment]
Thats a good reference @HVisMyLife. This is also somewhat covered in our Settings Sync docs:
https://code.visualstudio.com/docs/editor/settings-sync#_troubleshooting-keychain-issues

I'm going to close this because it is almost certainly related to the installation of gnome-keyring.
