### ISSUE TITLE
Errors stay in files even after you delete them

### ISSUE THREAD

**Issue by Qudware** [Microsoft/vscode#14345]
- VSCode Version: 1.61
- OS Version: Windows 10

Steps to Reproduce:

1. Create a project with a file that has errors in it (in my case, an F# Ionide project)
2. See that the lower left error count is up
3. Delete the file that has the errors
4. Observe the lower left error count persist (even though the file is gone)

Ps. you can access it by also pressing Ctrl+Shift+M

**Comment by sandy081** [comment]
@Qudware This looks to me an issue with the F# extension. It is not removing the errors on file delete. Can you please open issue against that extension.

Thanks
