### ISSUE TITLE
Azure function was working and now has error when compiling

### ISSUE THREAD

**Issue by anderson9149** [microsoft/vscode#143476]
Issue Type: <b>Bug</b>

My Azure functions were working fine.  I went to deploy them today with a minor code update and the will no longer deploy.  I am receiving this error

/Users/panderson/.nuget/packages/microsoft.azure.webjobs.script.extensionsmetadatagenerator/4.0.1/build/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error : Metadata generation failed. Exit code: '137' Error: 'Failed to initialize CoreCLR, HRESULT: 0x80004005' [/Users/panderson/Projects/AzureFunctions/AzureFunctions.csproj]

I did update my Visual Studio last night and now I get this error in Visual Studio Code.  I have tried many things and the issue persits.  I am on a Mac.  I saw this post for someone who had a similar error, but ther were in Visual Studio and not Visual Studio Code.

https://developercommunity.visualstudio.com/t/netcore31-build-error-in-azure-function-project-me/953931

VS Code version: Code 1.64.2 (Universal) (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.79GB free)|
|Process Argv|--crash-reporter-id 32a5a661-8872-472f-8d16-85c549dfe95f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nuget-package-manager|jmr|1.1.6
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
csharp|ms-|1.24.0
azure-account|ms-|0.10.0
playfab-explorer|Pla|0.1.15

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30440023
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343

```

</details>

**Comment by Tyriar** [comment]
This doesn't have anything to do with VS Code core, you probably want to report to some azure extension or cli tool.

**Comment by anderson9149** [comment]
To fix the issue I deleted all my DotNet versions and reinstalled Visual Studio Code 2019, instead of Visual Studio Code 2022.  After doing this the issue is resolved.
