### ISSUE TITLE
Copy JSON value

### ISSUE THREAD

**Issue by ttodua** [microsoft/vscode#143451]
This issue is same as https://github.com/microsoft/vscode/issues/36704 , as I couldn't comment there (issue was closed).
I think that , majority of programmers in debugger (for js/node.js) do use JSON as data type, so in addition to 'Copy Value' there could be 'Copy JSON', so, instead of : 
```
{
   key1: "value",
   deep:  {
       key2: "value2",
   }
}
```
We could get:
```
{
   "key1": "value",
   "deep":  {
       "key2": "value2",
   }
}
```

So, we could quickly use that JSON data to use/test in our other applications (which depend/use JSON format). Currently, with 'Copy value' it is not possible, as it is not JSON format. The reference issue was closed as @isidorn thought (that was 5 years ago) that JSON format was 'too specific to js', but I cant agree, it is not too specific, but it is probably the way which developers use. moreover , if you are concerned the 'Copy JSON' can be hidden for other languages, but shown for JS. 

p.s. In the meantime if you know any extension which does that with one click, let us know.

**Comment by ttodua** [comment]
So, github's voting system decides what feature is worth to be implemented? do you expect people to start scrolling and browsing among 5000+ issues to upvote? :) what a broken system.

**Comment by weinand** [comment]
@connor4312 js-debug could offer a 'Copy JSON' action...
