### ISSUE TITLE
Suggestions of link references for headings that contain multibyte characters display encoded string

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [microsoft/vscode#143455]
This problem still occurs even if you disable all extensions.

# Suggestions of link references for headings that contain multibyte characters display encoded strings

This is a bug in markdown files.

When the suggestion of the link reference is displayed, the decoded character strings is output. Now you don't know which heading you want to reference.

Please display the undecoded strings.

## Demo 1

```markdown
# Heading

# 見出し

[見出し](#)
```

The meaning of decoded `%E8%A6%8B%E5%87%BA%E3%81%97` is `見出し`. (`見出し` means heading in Japanese)

![multiByteLinkReference](https://user-images.githubusercontent.com/75878492/154807302-9edd51b9-0282-4c66-9cde-bfbdeafa3ad8.png)

## Demo 2

```markdown
# ■ heading

[heading](#)
```

The meaning of decoded `%E2%96%A0` is `■`.

![multiByteLinkReference2](https://user-images.githubusercontent.com/75878492/154807316-dbb53799-948c-4f4d-919f-6ee7fe6497bb.png)

## By the way

When Markdown All in One is enabled, suggestion of the link references that undecoded multibyte characters are displayed, but you'll also see the decode strings.

- [Markdown All in One \- Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one)
- [yzhang\-gh/vscode-markdown: Markdown All in One](https://github.com/yzhang-gh/vscode-markdown)

```markdown
# Heading

# 見出し

[見出し](#)
```

![multiByteLinkReference-MarkdownAllinOne](https://user-images.githubusercontent.com/75878492/154807328-dddb880d-667c-4c72-8d3e-f7d9e4af6839.png)

```markdown
# ■ heading

[heading](#)
```

![multiByteLinkReference2-MarkdownAllinOne](https://user-images.githubusercontent.com/75878492/154807380-a38cb448-33fc-48a9-b465-b8a11e01669d.png)

## Version

```
 Version: 1.64.2 (user setup)
  Commit: f80445acd5a3dadef24aa209168452a3d97cc326
    Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
 Node.js: 14.16.0
      V8: 9.1.269.39-electron.0
      OS: Windows_NT x64 10.0.19043
```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Yarakashi-Kikohshi** [comment]
I'm sorry, I don't know if this issue will be reproduced in the insider version.

I only use the stable version... (As already shown, the stable version will be reproduced with all extensions disabled.)

Should I download the insider version and test this issue? (It's a little troublesome...)
If so, it may take some time, but it is possible to verify the reproducibility.

**Comment by mjbvz** [comment]
Yes please testing using the insider version linked to above. Otherwise I have to, which is not scalable

**Comment by Yarakashi-Kikohshi** [comment]
# Requested report

I downloaded the insider version and tested the reproducibility of the problem.
(When I actually worked on it, there wasn't much of a troublesome. I'm sorry to whine.)

I just downloaded it and haven't installed any extensions. Therefore, it is the same as when all extensions are disabled.

I tested it like the first post. It didn't seem to be a problem in demo 1, but I felt that another problem was occurring in demo 2.

## Demo 1

```markdown
# Heading

# 見出し

[見出し](#)
```

![insiderMultiByte](https://user-images.githubusercontent.com/75878492/155261411-8ba99937-4b2c-4bf3-a6dc-0c7e8977849c.png)


Here, the decoded string is suggested as expected. There seems to be no problem.

## Demo 2

```markdown
# ■ heading

[heading](#)
```

![insiderMultiByte2](https://user-images.githubusercontent.com/75878492/155261404-22139705-6dca-4f14-a123-333ab6aca311.png)

I'm expecting a suggestion like `#-heading` here. `■` is not required.

For example, I tested it with Gist as follow. Please actually refer to it.

https://gist.github.com/Yarakashi-Kikohshi/3e549446c27762c857d0d8bc4687f1a4


<details>
<summary>
I tested this in Gist:
</summary>
<div>

````markdown
# Heading

```markdown
[Heading](#heading)
```

[Heading](#heading)

# 見出し

```markdown
[見出し](#見出し)
```

[見出し](#見出し)

# ■ heading

```markdown
[■ heading](#-heading)
```

[■ heading](#-heading)


```markdown
[■ heading](#■-heading)
```

[■ heading](#■-heading)
````

</div>
</details>

In the case of `#■-heading`, the link does not seem to work well. I didn't know which characters should be removed in general. However, at least in Gist, `■` needs to be removed.

On the other hand, when used in VS Code (*insider 1.65*) built-in preview, the link works in `#■-heading` but not in `#-heading`. (Both links did not work in the *stable (1.64.2)* built-in preview. I don't know what it was like before that.)

If you think based on the built-in preview, you don't need to remove `■` from the link. However, if you think based on Gist, you need to remove it.
I don't think which link style to take as VS Code, so I'll leave it to you.

## Insider version

```
 Version: 1.65.0-insider
  Commit: eeeab304b9ac777b4a8dddf55f66ffebd9e4e7f2
    Date: 2022-02-22T14:29:15.294Z
Electron: 16.0.9
Chromium: 96.0.4664.174
 Node.js: 16.9.1
      V8: 9.6.180.23-electron.0
      OS: Windows_NT x64 10.0.19043
```

**Comment by Lemmingh** [comment]
Your last request is substantially #106296

VS Code and GitHub take different algorithms to generate heading ID.

**Comment by Yarakashi-Kikohshi** [comment]
@mjbvz
@Lemmingh

I'm sorry that the last mention was different from the original issue. It was superfluous within this issue.

The last thing I wanted to mention was that heading ID style provided by IntelliSense should not be different between 1.64 and 1.65. It doesn't matter what heading ID style you have, but it's very inconvenient to have changes from version to version.

However, current version 1.65 solves the issue raised here. Therefore, you can close this issue at your discretion.

Thank you for your efforts in solving the issue :smile:
