### ISSUE TITLE
Regression: Copy in notebook output doesn't work

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#143469]
This was introduced via https://github.com/microsoft/vscode/commit/82a65e1a8d696e07a922454333f6c7323d06a573 which will set focus to the notebook cell list container always when clicking on the webview, it blurs the webview (or never focuses the webview).

**Comment by rebornix** [comment]
@roblourens I don't have ideas of how to fix this properly yet, we want to update the model/viewModel but not really changing the DOM focus.

**Comment by roblourens** [comment]
This is annoying. Tried a bunch of things, https://github.com/microsoft/vscode/commit/8ac38cb0cc093c40145099ac9ac44ad40f401cea is also involved, and that change is basically at odds with this issue.

I wonder whether we should extend the cell `focusMode` to include representing Output focus. Then we can only force focus out of the webview when the newly focused cell has Container/Editor focus.

For now I can probably just revert my commit
