### ISSUE TITLE
 breakdown 

### ISSUE THREAD

**Issue by wjvinson** [microsoft/vscode#143490]
Issue Type: <b>Bug</b>

 breakdown  "OOM" #XXXXXXXXXXX

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.00GB free)|
|Process Argv|E:\\Indoor_161CC_Cypress\\Indoor161CC_V1.9(2020.12.30 add128&CRC16) --crash-reporter-id cbedd674-0403-4f2f-945f-691336fa9ac6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.3.2
better-cpp-syntax|jef|1.15.13
vscode-language-pack-zh-hans|MS-|1.64.7
remote-containers|ms-|0.222.0
remote-ssh|ms-|0.75.2022021903
remote-ssh-edit|ms-|0.75.2022021903
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
vscop841:30438915
dsvsc009:30440023
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343

```

</details>

**Comment by deepak1556** [comment]
Please follow our issue reporting guidelines https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests, closing due to lack of information.
