### ISSUE TITLE
Strange text behavior with 'TextEditorDecorationType' after setting 'font-size'

### ISSUE THREAD

**Issue by yfzhao20** [microsoft/vscode#143485]
### Help wanted: About `font-size` in `TextEditorDecorationType`

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2 (user setup)
- OS Version: windows10 21H2

### Steps to Reproduce:

1.  new an extension template by `yo code`, choose `JavaScript`
2. copy the code and cover `extension.js` 
```javascript
const vscode = require('vscode'); 
let decoration = vscode.window.createTextEditorDecorationType({});
/**
 * @param {vscode.ExtensionContext} context
*/
function activate(context) {
    vscode.window.onDidChangeTextEditorSelection(()=>{
	const beginPosition = vscode.window.activeTextEditor.selection.active
	const endPosition = new vscode.Position(beginPosition.line,beginPosition.character+1)
		
	decoration.dispose();
	decoration = vscode.window.createTextEditorDecorationType({
			textDecoration: `none; font-size:5rem`,
	})
          vscode.window.activeTextEditor.setDecorations(decoration, [new vscode.Range(beginPosition,endPosition)])	
    })
}

function deactivate() {}
module.exports = {
  	activate,
  	deactivate
}
```

of which main code is
```javascript
decoration = vscode.window.createTextEditorDecorationType({
    textDecoration: `none; font-size:5rem`,
    })
vscode.window.activeTextEditor.setDecorations(decoration, [new vscode.Range(beginPosition,endPosition)])	
```

3. Run Extension and new an any-type file
4. input some text

Then you will find :
- without textDecoration:
  ![image](https://user-images.githubusercontent.com/80528249/154832715-d1aa341f-a4b1-4195-af2d-fbc97959b55e.png)
- with textDecoration:
  ![image](https://user-images.githubusercontent.com/80528249/154832735-d9c64810-7f7f-43cd-b8d3-9f7c0ad6cc1a.png)

The whole line of text moves down and overlaps on other line of text!

### Expected Behavior

What I want is like:
![Snipaste_2022-02-20_15-24-341](https://user-images.githubusercontent.com/80528249/154833235-90b6262e-b778-471f-b302-160daf4b6c18.png)

I don't know if it is a bug or feature. Having searched for a long time, I didn't find how to achieve this effect.

If there is any way, please let me know. Thanks a lot! 😃

**Comment by ArturoDent** [comment]
`font-size` or `fontSize` are not suuported `DecorationRenderOptions`.

see https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions

**Comment by yfzhao20** [comment]
> `font-size` or `fontSize` are not suuported `DecorationRenderOptions`.
> 
> see https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions

I don't think so. Actually you can use more css options in `createTextEditorDecorationType`. See [this discussion](https://github.com/microsoft/vscode/issues/9078#issuecomment-390512079). Actually these extensions have used this method : [hoovercj.vscode-power-mode](https://github.com/hoovercj/vscode-power-mode) and [	yfzhao.ultra-math-preview](https://github.com/yfzhao20/vscode-ultra-math-preview)

**Comment by ArturoDent** [comment]
I searched for `font-size` or `fontSize` in the two extension repositories you mentioned.  No matches.

**Comment by yfzhao20** [comment]
> I searched for `font-size` or `fontSize` in the two extension repositories you mentioned.  No matches.
> 
> The first extension uses this for example: `textDecoration: `none; margin-top: 0px;` I would say that syntax isn't officially supported, so don't be surprised if trying to inject `font-size` into that doesn't work.

They do not contain `font-size` option. Actually they are just examples to show how to add css to `textDecoration` . If you set 'height' larger than 1rem, that bug will occur , too.

I'm more interested in how the bug occurs and the solutions. If it is exactly unsupported, I'd like to request the feature🧐

**Comment by hoovercj** [comment]
@yfzhao20 I'm the author of vscode-power-mode -- the technique that I use in that extension is very much **not supported** by the API and it is only through the mercy of the vs code team that they haven't blocked it.

In the meantime, though, you can try also setting the `line-height` property on your decoration along with the `font-size` property.
