### ISSUE TITLE
Quick fix doesn't work: No code actions available 

### ISSUE THREAD

**Issue by OnkelTem** [microsoft/vscode#143495]
`Ctrl + '.'` (quck fix) feature works very inconsistently. Every other time it either doesn't bring any suggestions (No code actions available) or doesn't show the "import from..." item.

Here is an example where I do have the needed export, it is available, yet VSCode doesn't help:

Video: https://imgur.com/zsh6nGU

![image](https://user-images.githubusercontent.com/114060/154843658-5b25ade6-8166-484c-95dc-8e4c9856811e.png)

OS: Linux Kubuntu 20.04
VSCode: 
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:29.527Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-30-generic

**Comment by mjbvz** [comment]
Please share an example project that demonstrates the issue

**Comment by OnkelTem** [comment]
I cannot do it right now, it's not easy to extract.
Meanwhile here is a another example, now VSCode doesn't "see" node_modules packages.

https://www.youtube.com/watch?v=KLxIr0QtCu8

**Comment by mjbvz** [comment]
Sorry but we can't investigate this without a code sample. Please share one
