### ISSUE TITLE
intellisense in debug console adds extra character

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#14344]
- VSCode Version: insiders 1.7 c038219f8d137b4972a15346b81ea03751d669d4
- OS Version: Mac

Steps to Reproduce:

1. new node/express app
2. npm install
3. set up debugging
4. hit breakpoint
5. in debug console, type in name of a variable and get intellisense to complete
6. accept completion by hitting enter

result: extra dupe character at beginning of line

![image](https://cloud.githubusercontent.com/assets/1487073/19673083/72f31328-9a31-11e6-81dd-6291b23391e3.png)

now press enter, note extra 'r' at beginning.

![image](https://cloud.githubusercontent.com/assets/1487073/19673091/7e48fd6e-9a31-11e6-80bb-ceb125087ab1.png)

**Comment by weinand** [comment]
dup of https://github.com/Microsoft/vscode/issues/14193
