### ISSUE TITLE
Unnecessary "Do you trust the authors of these files?"

### ISSUE THREAD

**Issue by fulldecent** [microsoft/vscode#143467]
Issue Type: <b>Bug</b>

I got smacked in the face by this warning "Do you trust the authors of these files?" for opening a CSV file.

The fact that you even need to ask me about trusting a CSV file makes me trust YOU less.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:56.651Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (2.86GB free)|
|Process Argv|--crash-reporter-id 887f8733-a96a-44f8-b91e-d4df21ec6bd3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.60
unique-lines|bib|1.0.0
vscode-intelephense-client|bme|1.8.1
binary-plist|dni|0.8.0
vscode-html-css|ecm|1.11.0
solidity|Jua|0.0.136
remote-ssh|ms-|0.74.0
remote-ssh-edit|ms-|0.74.0
sublime-keybindings|ms-|4.0.10
material-icon-theme|PKi|4.13.0
unique-window-colors|stu|1.0.51
vscode-import-cost|wix|2.15.0

</details>

**Comment by fulldecent** [comment]
Expected behavior:

Big, scary warning in shown the first time you are planning on doing something dangerous. Not the first time I open a file.

**Comment by hello-smile6** [comment]
> Expected behavior:
> 
> Big, scary warning in shown the first time you are planning on doing something dangerous. Not the first time I open a file.

If that is shown, it likely means that nodeIntegration or something is enabled in the current window, which means that malicious files could have a larger impact on your system.

**Comment by fulldecent** [comment]
Thank you for explaining.

I'm not sure if that is the root cause.

But if it is, it should be shown on that dialog. Rather than only knowable by reporting a bug.

**Comment by hello-smile6** [comment]
> Thank you for explaining.
> 
> I'm not sure if that is the root cause.
> 
> But if it is, it should be shown on that dialog. Rather than only knowable by reporting a bug.

It could be for another reason, I'm just guessing.

**Comment by IllusionMH** [comment]
See https://code.visualstudio.com/docs/editor/workspace-trust for details

And there is noticeable link in text(if you don't click on big buttons immediately) that should lead you to details.

Just opening csv shouldn't hurt, but if you open it from folder that also contains malicious build tasks, runtime packages used by extension(from workspace dir) etc. this might pose a threat.

**Comment by fulldecent** [comment]
The appropriate thing to show this box should be:

> **Do you trust the authors of the files in this folder?**
>
> You have enabled the XXXX extension that may automatically execute files in this folder if you trust this folder.
>
> If you don't trust the authors of these files, we recommend to continue in restricted mode as the files may be malicious. See our docs to learn more.
>
> [ ] Trust the authors of all files in the parent folder 'myFolders'
>
> Yes, I trust the authors
> Trust folder and enable all features
> 
> No, I don't trust the authors
> Browse folder in restricted mode


---

Or possibly 100x better:

> **Do you trust the authors of the files in this folder?**
>
> The extension XXXX wants to execute a command that might destroy your computer, steal all your bitcoin and leak your nude photos if only one thing in this folder is misconfigured.
>
> See our docs to learn more and see how easy it is to misconfigure.
>
> [ ] Trust the authors of all files in the parent folder 'myFolders'
>
> Yes, I trust the authors
> Run the command.
> 
> No, I don't trust the authors
> Do not run the command.

**Comment by lszomoru** [comment]
Thank you very much for the feedback. The default "workspace trust flow" errs on the side of security and that is why you are seeing the prompt. Having said that there are multiple settings that one can use to customise the workspace trust feature to their needs. You can use the `security.workspace.trust.emptyWindow` to control whether the empty window is in restricted mode or not, and the `security.workspace.trust.untrustedFiles` to control how untrusted files are being handled when opened. 

At the moment, we do not have any plans on making any changes are not planning on making any further changes to the workspace trust flow.
