### ISSUE TITLE
ConfigurationChangeEvent not fired with resource scoped properties on multiroot workspace

### ISSUE THREAD

**Issue by jlelong** [microsoft/vscode#143462]
You can use https://github.com/jlelong/config-event-vscode to reproduce the issue. This is a very basic extension build on https://github.com/microsoft/vscode-extension-samples/tree/main/configuration-sample. It only prints the value of the property `dummySetting`, which has a `resource` scope, whenever an `ConfigurationChangeEvent` is fired.

Consider the multi-root workspace.

```
event.code-workspace

A/
  .vscode/settings.json
  A.txt

B/
  B.txt
```

with `A/.vscode/setting.json` containing 

```json
{
    "conf.dummySetting": false
}
```

Note that the default value is `true`. Run the extension and toggle between `A.txt` and `B.txt` and note that nothing is printed in the `console` whereas the value of `conf.dummySetting` changes.

Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0

**Comment by tamuratak** [comment]
I think it is not a bug. When toggling between `A.txt` and `B.txt`, the value of `conf.dummySetting` for each workspace does not change. Only the active editor does change.

**Comment by jlelong** [comment]
Yes you are right. I somehow misinterpreted how `WorkspaceConfiguration.get` was obtained. It is clear that the `WorkspaceConfiguration`'s of workspaces  `A` and `B` do not change.

I am closing the issue
