### ISSUE TITLE
Terminal CTRL+C disconnects telnet host instantly

### ISSUE THREAD

**Issue by hongz1** [microsoft/vscode#143401]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. opened git-bash (Windows-git) and connected telnet, ran express with nodemon and hit CTRL+C and nodemon was exited without any issues. 
2. opened git-bash terminal in VSCODE, connected telnet, ran express with nodemon and hit CTRL+C and entire telnet was exited.

Something has been definitely happened in VSCODE because I used to use CTRL+C to exit nodemon without disconnecting telnet for years. I noticed this issue since end of January or beginning of February.

This is when I use external Windows git-bash and use CTRL+C to exit nodemon gracefully.
![image](https://user-images.githubusercontent.com/6565136/154742312-bf1f9575-d1ef-4ff7-9d4e-3cf7f28b11f4.png)

This is what happened when I do CTRL+C in VSCODE and it disconnects telnet and I had to connect to telnet and kill the process manually.

![image](https://user-images.githubusercontent.com/6565136/154742788-d12aeccf-e076-4b8f-a987-86f161464be4.png)

![image](https://user-images.githubusercontent.com/6565136/154743042-f95dc0a7-9ddb-47a0-8126-3ab21dddd560.png)

**Comment by meganrogge** [comment]
You're probably seeing this because of `terminal.integrated.autoReplies`. You can disable the feature by setting the value to null

**Comment by meganrogge** [comment]
Do you have `terminal.integrated.autoReplies` enabled?

**Comment by hongz1** [comment]
No. It has default as null.

![image](https://user-images.githubusercontent.com/6565136/155598071-90d0fcad-87a8-46c8-9315-ad7e79a19694.png)

**Comment by hongz1** [comment]
Nope. It is null as default.

**Comment by meganrogge** [comment]
Can you toggle escape sequence logging and share the logs?

**Comment by hongz1** [comment]
You mean console log in vscode?

**Comment by meganrogge** [comment]
open the command palette, run `Terminal: toggle escape sequence logging`, share what's in the console when you disconnect

**Comment by hongz1** [comment]
`
LogService.ts:62 xterm.js: sending data "n" [110]
LogService.ts:62 xterm.js: parsing data "n" [110]
LogService.ts:62 xterm.js: parsing data "[K" (3) [27, 91, 75]
LogService.ts:62 xterm.js: sending data "p" [112]
LogService.ts:62 xterm.js: sending data "m" [109]
LogService.ts:62 xterm.js: parsing data "pm" (2) [112, 109]
LogService.ts:62 xterm.js: parsing data "[K" (3) [27, 91, 75]
LogService.ts:62 xterm.js: sending data " " [32]
LogService.ts:62 xterm.js: parsing data "[1C" (4) [27, 91, 49, 67]
LogService.ts:62 xterm.js: sending data "r" [114]
LogService.ts:62 xterm.js: parsing data "[?25l" (6) [27, 91, 63, 50, 53, 108]
LogService.ts:62 xterm.js: parsing data "
[14:30:40 jl cubs cubs-api]$ [mnpm r[K[?25h" (52) [27, 91, 51, 50, 109, 13, 91, 49, 52, 58, 51, 48, 58, 52, 48, 32, 106, 108, 32, 99, 117, 98, 115, 32, 99, 117, 98, 115, 45, 97, 112, 105, 93, 36, 32, 27, 91, 109, 110, 112, 109, 32, 114, 27, 91, 75, 27, 91, 63, 50, 53, 104]
LogService.ts:62 xterm.js: sending data "u" [117]
LogService.ts:62 xterm.js: sending data "n" [110]
LogService.ts:62 xterm.js: sending data " " [32]
LogService.ts:62 xterm.js: parsing data "un[K" (5) [117, 110, 27, 91, 75]
LogService.ts:62 xterm.js: parsing data "[1C" (4) [27, 91, 49, 67]
LogService.ts:62 xterm.js: sending data "s" [115]
LogService.ts:62 xterm.js: parsing data "[?25l" (6) [27, 91, 63, 50, 53, 108]
LogService.ts:62 xterm.js: parsing data "
[14:30:40 jl cubs cubs-api]$ [mnpm run s[K[?25h" (56) [27, 91, 51, 50, 109, 13, 91, 49, 52, 58, 51, 48, 58, 52, 48, 32, 106, 108, 32, 99, 117, 98, 115, 32, 99, 117, 98, 115, 45, 97, 112, 105, 93, 36, 32, 27, 91, 109, 110, 112, 109, 32, 114, 117, 110, 32, 115, 27, 91, 75, 27, 91, 63, 50, 53, 104]
LogService.ts:62 xterm.js: sending data "t" [116]
LogService.ts:62 xterm.js: parsing data "t" [116]
LogService.ts:62 xterm.js: parsing data "[K" (3) [27, 91, 75]
LogService.ts:62 xterm.js: sending data "a" [97]
LogService.ts:62 xterm.js: parsing data "a" [97]
LogService.ts:62 xterm.js: parsing data "[K" (3) [27, 91, 75]
LogService.ts:62 xterm.js: sending data "r" [114]
LogService.ts:62 xterm.js: parsing data "r" [114]
LogService.ts:62 xterm.js: parsing data "[K" (3) [27, 91, 75]
LogService.ts:62 xterm.js: sending data "t" [116]
LogService.ts:62 xterm.js: parsing data "t" [116]
LogService.ts:62 xterm.js: parsing data "[K" (3) [27, 91, 75]
LogService.ts:62 xterm.js: sending data "-" [45]
LogService.ts:62 xterm.js: parsing data "-" [45]
LogService.ts:62 xterm.js: parsing data "[K" (3) [27, 91, 75]
LogService.ts:62 xterm.js: sending data "d" [100]
LogService.ts:62 xterm.js: parsing data "d" [100]
LogService.ts:62 xterm.js: parsing data "[K" (3) [27, 91, 75]
LogService.ts:62 xterm.js: sending data "e" [101]
LogService.ts:62 xterm.js: parsing data "e" [101]
LogService.ts:62 xterm.js: parsing data "[K" (3) [27, 91, 75]
LogService.ts:62 xterm.js: sending data "v" [118]
LogService.ts:62 xterm.js: parsing data "v" [118]
LogService.ts:62 xterm.js: parsing data "[K" (3) [27, 91, 75]
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data "[?25l" (6) [27, 91, 63, 50, 53, 108]
LogService.ts:62 xterm.js: parsing data "
[?25h" (8) [13, 10, 27, 91, 63, 50, 53, 104]
LogService.ts:62 xterm.js: parsing data "[?25l" (6) [27, 91, 63, 50, 53, 108]
LogService.ts:62 xterm.js: parsing data "
> cubs-api@1.0.0 start-dev /home/jl/jlwork/node_express/cubs-api[75C" (70) [10, 62, 32, 99, 117, 98, 115, 45, 97, 112, 105, 64, 49, 46, 48, 46, 48, 32, 115, 116, 97, 114, 116, 45, 100, 101, 118, 32, 47, 104, 111, 109, 101, 47, 106, 108, 47, 106, 108, 119, 111, 114, 107, 47, 110, 111, 100, 101, 95, 101, 120, 112, 114, 101, 115, 115, 47, 99, 117, 98, 115, 45, 97, 112, 105, 27, 91, 55, 53, 67]
LogService.ts:62 xterm.js: parsing data "
> NODE_ENV=development nodemon index.js[100C" (47) [13, 10, 62, 32, 78, 79, 68, 69, 95, 69, 78, 86, 61, 100, 101, 118, 101, 108, 111, 112, 109, 101, 110, 116, 32, 110, 111, 100, 101, 109, 111, 110, 32, 105, 110, 100, 101, 120, 46, 106, 115, 27, 91, 49, 48, 48, 67]
LogService.ts:62 xterm.js: parsing data "
[139C" (8) [13, 10, 27, 91, 49, 51, 57, 67]
LogService.ts:62 xterm.js: parsing data "
[?25h" (8) [13, 10, 27, 91, 63, 50, 53, 104]
LogService.ts:62 xterm.js: parsing data "[nodemon] 2.0.12" (21) [27, 91, 51, 51, 109, 91, 110, 111, 100, 101, 109, 111, 110, 93, 32, 50, 46, 48, 46, 49, 50]
LogService.ts:62 xterm.js: parsing data "[m[K[?25l[123C" (18) [27, 91, 109, 27, 91, 75, 27, 91, 63, 50, 53, 108, 27, 91, 49, 50, 51, 67]
LogService.ts:62 xterm.js: parsing data "
[nodemon] to restart at any time, enter `rs`[95C" (56) [27, 91, 51, 51, 109, 13, 10, 91, 110, 111, 100, 101, 109, 111, 110, 93, 32, 116, 111, 32, 114, 101, 115, 116, 97, 114, 116, 32, 97, 116, 32, 97, 110, 121, 32, 116, 105, 109, 101, 44, 32, 101, 110, 116, 101, 114, 32, 96, 114, 115, 96, 27, 91, 57, 53, 67]
LogService.ts:62 xterm.js: parsing data "
[?25h" (8) [13, 10, 27, 91, 63, 50, 53, 104]
LogService.ts:62 xterm.js: parsing data "[nodemon] watching path(s): *.*" (31) [91, 110, 111, 100, 101, 109, 111, 110, 93, 32, 119, 97, 116, 99, 104, 105, 110, 103, 32, 112, 97, 116, 104, 40, 115, 41, 58, 32, 42, 46, 42]
LogService.ts:62 xterm.js: parsing data "[K[?25l[108C" (15) [27, 91, 75, 27, 91, 63, 50, 53, 108, 27, 91, 49, 48, 56, 67]
LogService.ts:62 xterm.js: parsing data "
[nodemon] watching extensions: js,mjs,json[97C" (49) [13, 10, 91, 110, 111, 100, 101, 109, 111, 110, 93, 32, 119, 97, 116, 99, 104, 105, 110, 103, 32, 101, 120, 116, 101, 110, 115, 105, 111, 110, 115, 58, 32, 106, 115, 44, 109, 106, 115, 44, 106, 115, 111, 110, 27, 91, 57, 55, 67]
LogService.ts:62 xterm.js: parsing data "
[nodemon] starting `node index.js`[K[105C" (55) [13, 10, 27, 91, 51, 50, 109, 91, 110, 111, 100, 101, 109, 111, 110, 93, 32, 115, 116, 97, 114, 116, 105, 110, 103, 32, 96, 110, 111, 100, 101, 32, 105, 110, 100, 101, 120, 46, 106, 115, 96, 27, 91, 51, 51, 109, 27, 91, 75, 27, 91, 49, 48, 53, 67]
LogService.ts:62 xterm.js: parsing data "
[?25h" (13) [27, 91, 51, 50, 109, 13, 10, 27, 91, 63, 50, 53, 104]
LogService.ts:62 xterm.js: parsing data "info: Listening CUBS development on port 9052... {"timestamp":"2022-02-25 14:30:57"}" (84) [105, 110, 102, 111, 58, 32, 76, 105, 115, 116, 101, 110, 105, 110, 103, 32, 67, 85, 66, 83, 32, 100, 101, 118, 101, 108, 111, 112, 109, 101, 110, 116, 32, 111, 110, 32, 112, 111, 114, 116, 32, 57, 48, 53, 50, 46, 46, 46, 32, 123, 34, 116, 105, 109, 101, 115, 116, 97, 109, 112, 34, 58, 34, 50, 48, 50, 50, 45, 48, 50, 45, 50, 53, 32, 49, 52, 58, 51, 48, 58, 53, 55, 34, 125]
LogService.ts:62 xterm.js: parsing data "[K[?25l[55C" (14) [27, 91, 75, 27, 91, 63, 50, 53, 108, 27, 91, 53, 53, 67]
LogService.ts:62 xterm.js: parsing data "
[?25h" (8) [13, 10, 27, 91, 63, 50, 53, 104]
LogService.ts:62 xterm.js: parsing data "info: Client connected and ready to use redis... {"timestamp":"2022-02-25 14:30:57"}" (84) [105, 110, 102, 111, 58, 32, 67, 108, 105, 101, 110, 116, 32, 99, 111, 110, 110, 101, 99, 116, 101, 100, 32, 97, 110, 100, 32, 114, 101, 97, 100, 121, 32, 116, 111, 32, 117, 115, 101, 32, 114, 101, 100, 105, 115, 46, 46, 46, 32, 123, 34, 116, 105, 109, 101, 115, 116, 97, 109, 112, 34, 58, 34, 50, 48, 50, 50, 45, 48, 50, 45, 50, 53, 32, 49, 52, 58, 51, 48, 58, 53, 55, 34, 125]
LogService.ts:62 xterm.js: parsing data "[K[?25l[55C" (14) [27, 91, 75, 27, 91, 63, 50, 53, 108, 27, 91, 53, 53, 67]
LogService.ts:62 xterm.js: parsing data "
[?25h" (8) [13, 10, 27, 91, 63, 50, 53, 104]
LogService.ts:62 xterm.js: sending data "" [3]
LogService.ts:62 xterm.js: parsing data "
" [10]
LogService.ts:62 xterm.js: parsing data "[?2004h]0;MINGW64:/c/JLBash" (30) [27, 91, 63, 50, 48, 48, 52, 104, 27, 93, 48, 59, 77, 73, 78, 71, 87, 54, 52, 58, 47, 99, 47, 74, 76, 66, 97, 115, 104, 7]
LogService.ts:62 xterm.js: parsing data "[m
SUPPLY+eoleejae@eoleejae-12947 MINGW64 ~[K
" (68) [27, 91, 109, 10, 27, 91, 51, 50, 109, 83, 85, 80, 80, 76, 89, 43, 101, 111, 108, 101, 101, 106, 97, 101, 64, 101, 111, 108, 101, 101, 106, 97, 101, 45, 49, 50, 57, 52, 55, 32, 27, 91, 51, 53, 109, 77, 73, 78, 71, 87, 54, 52, 32, 27, 91, 51, 51, 109, 126, 27, 91, 51, 50, 109, 27, 91, 75, 13]
LogService.ts:62 xterm.js: parsing data "[m
$[1C" (9) [27, 91, 109, 10, 36, 27, 91, 49, 67]
`

**Comment by hongz1** [comment]
To clarify,,,
1. VSCODE worked before...
2. Windows git-bash still works fine.

**Comment by hongz1** [comment]
Any updates?

**Comment by Tyriar** [comment]
We only send this when ctrl+c is pressed which is correct:

```
LogService.ts:62 xterm.js: sending data "�" [3]
```

From here we essentially hand this off to the process and backend (conpty). I don't know why this would happen, but it feels like it's out of our hands since we're sending the correct sequence on ctrl+c. Things you could try:

- Look into differences in the environment between git bash and your vscode git bash session
- Update Windows so you're on a newer version of conpty
- Consult telnets docs?

**Comment by hongz1** [comment]
well, I configured vscode to run windows git-bash and both vscode and git-bash runs winpty.
What I don't understand is why vscode worked before and now it disconnects telnet immediately???

**Comment by Tyriar** [comment]
vscode uses conpty by default, winpty when you set `"terminal.integrated.windowsEnableConpty": false`. I'm not sure either and I don't think this is actionable without more information about the root cause.

**Comment by hongz1** [comment]
I tried to set false but same issue. so that explains it is not caused by conpty.
