### ISSUE TITLE
Build task quits without showing errors/warning

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#143407]
Issue Type: <b>Bug</b>

I was running into this multiple times while using build for VS Code. It quits immediately without showing any error (or at least I can't see as it was opened and closed quickly). However `yarn watchd` in normal terminal works fine.

Some potential improvements:

* Keep the terminal when the build tasks fail to give users a chance to know what happens
* Redirect errors to outputs 

VS Code version: Code - Insiders 1.65.0-insider (Universal) (86200d542474b26aa28034e0fd5789c45c747d8b, 2022-02-17T07:19:54.062Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 6, 5|
|Memory (System)|32.00GB (3.86GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --enable-proposed-api donjayamanne.jupyterpowertools --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api rchiodo.jupyter-tools --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (76)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.1
github-markdown-preview|bie|0.2.0
markdown-emoji|bie|0.2.1
markdown-footnotes|bie|0.0.7
markdown-preview-github-styles|bie|1.0.1
vscode-eslint|dba|2.2.2
kusto|don|0.3.8
gitlens|eam|11.7.0
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.2.0
codespaces|Git|1.5.3
copilot|Git|1.7.5067
remotehub|Git|0.24.0
vscode-pull-request-github|Git|0.37.2022021709
vscode-drawio|hed|1.6.4
handydandy-notebook|jak|0.1.0
github-graphql-nb|joy|0.0.7
fluent-icons|mig|0.0.16
vscode-fluent-icons|mig|0.0.1
theme-monokai-pro-vscode|mon|1.1.20
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestaticwebapps|ms-|0.9.0
vscode-docker|ms-|1.19.0
vscode-language-pack-zh-hans|MS-|1.64.7
csharp|ms-|1.24.0
python|ms-|2022.1.1854775815-dev
vscode-pylance|ms-|2022.2.4-pre.1
jupyter|ms-|2022.2.1010491003
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
notebook-renderers|ms-|0.0.1
remote-containers|ms-|0.222.0
remote-ssh|ms-|0.75.2022021715
remote-ssh-edit|ms-|0.75.2022021715
azure-account|ms-|0.10.0
azure-repos|ms-|0.4.0
hexeditor|ms-|1.9.4
js-debug-nightly|ms-|2022.2.1717
powershell-preview|ms-|2022.2.1
remotehub-insiders|ms-|2021.6.302
vscode-github-issue-notebooks|ms-|0.0.113
vscode-js-profile-flame|ms-|0.0.24
vscode-markdown-notebook|ms-|0.0.26
vscode-notebook-history|ms-|0.0.1
vscode-selfhost-test-provider|ms-|0.3.8
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.1.0-dev
debugger-for-chrome|msj|4.13.0
vetur|oct|0.35.0
excalidraw-editor|pom|1.2.0
geo-data-viewer|Ran|2.5.0
jupyter-tools|rch|0.0.1
better-jupyter-errors|reb|0.0.1
toggle|reb|0.0.2
typing-practice|reb|0.0.1
vscode-code-renderer|reb|0.0.2
vscode-jupyter-checkpoint|reb|0.0.1
java|red|1.3.0
kuskus-extensions-pack|ros|1.0.10
kuskus-kusto-language-server|ros|1.0.22
kuskus-kusto-syntax-highlighting|ros|1.1.20
vsc-nwjs|rua|1.0.18
rust|rus|0.7.8
rest-book|tan|5.0.1
tldraw-vscode|tld|1.6.1
luna-paint|Tyr|0.13.2
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.6.10
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0
notebook-editing|vsc|1.0.0
vscode-test-resolver|vsc|0.0.1

(6 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
When a task is a watch task we have always closed it when the task exits. There is a property that can be set on the task to keep the terminal around on exit. Happy to add it to our tasks.json!
