### ISSUE TITLE
Test: terminal command decorations

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#143433]
Refs: #140308

- [x] macOS @paulacamargo25 
- [x] linux @joaomoreno 
- [x] windows @joyceerhl 

Complexity: 4

Authors: @meganrogge, @Tyriar 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23143433%0A%0A&assignees=meganrogge,Tyriar)

---

The terminal now features "shell integration" with the opt-in setting `terminal.integrated.shellIntegration.enabled`. 

See https://github.com/microsoft/vscode/issues/141339 for details.

Since a shell script needs to be written on a shell-by-shell basis, only the following are currently supported:

- Windows
  - pwsh (6+, not "Windows PowerShell")
- Linux/macOS
  - pwsh
  - bash
  - *NOT* zsh for now

We have added command decorations decorations (codicons) in order to bring awareness to some of the new insights and capabilities shell integration provides. 

We have 3 decoration styles:
- default - a hollow, grey circle
- error - a red circle with an x
- success - a blue filled circle

Verify that:
- for default commands:
    - nothing was entered and there was no output
    - when you hover them, nothing happens
    - you can't click them
- for error commands 
    - the command had a non-zero exit code
    - on hover, you see the exit code
    - on click, you can re run the command or copy the output
- for success commands:
   - the command's exit code was zero
   - on click, you can re run the command or copy the output

Some things to try:

- run `clear` and similar commands - the decorations should disappear
- scroll - make sure they show and hide appropriately
- anything else you can think of
- change the renderer type via `terminal.integrated.gpuAcceleration`
- set the `terminal.integrated.shellIntegration.commandIcon` settings to new codicon IDs and empty strings and verify that works

Here are some of the main limitations you may hit while testing:

- Right prompts aren't supported yet https://github.com/microsoft/vscode/issues/140928
- Decorations don't work on reconnection (for persisted terminals)

**Comment by paulacamargo25** [comment]
I'm closing the issue even though there are some open bugs, please let me know if that isn't the right thing to do.
