### ISSUE TITLE
Irregularity: Regex parse error: lookbehind assertion is not fixed length

### ISSUE THREAD

**Issue by joshuajeschek** [microsoft/vscode#143453]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: Windows 11 Home, Build 22000.527 

When using the <kbd>ctrl+F</kbd> search+replace feature, lookbehinds/lookaheads in regex can be non-fixed length, while in the sidepanel they cannot be. If it works in the editor, why doesn't it work in the sidepanel?

Steps to Reproduce:

1. Try using this regex in <kbd>ctrl+F</kbd> search: `(?<=^ *)-(?!-)`
2. This works and the characters can even be replaced
3. Search using the same regex in the search sidepanel
4. It doesn't work anymore:
![image](https://user-images.githubusercontent.com/64850647/154805818-96dba1ca-bd41-4d39-b105-6f49896981a5.png)

(I wanted to use this regex to replace enumeration hyphens in markdown files)

**Comment by gjsjohnmurray** [comment]
> If it works in the editor, why doesn't it work in the sidepanel?

Sidepanel feature ("Search") works across files and uses a package to do that. This package lacks support for the regex feature you want.

In-editor feature ("Find") only works in one document.

**Comment by joshuajeschek** [comment]
Okay, I would've thought that it uses the same internal feature. So it wouldn't make sense to change this up?

**Comment by ArturoDent** [comment]
Related to performance reasons no doubt.  Non-fixed length lookbehinds across "many" files in the Search Panel could very well be quite bad.  In a single editot Find much less of a concern.
