### ISSUE TITLE
Networked Drives

### ISSUE THREAD

**Issue by clintparsley** [microsoft/vscode#143431]
Issue Type: <b>Bug</b>

No steps here .... had an SSH connected workspace open and attempted to close the remote connection. VS Code froze up and presented me with message "Discarding backups is taking longer than expected". I did not have control of any of my VS windows. First time it happened it crashed my Macbook Pro. 2nd time it happened I needed to force quit the app.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|16, 15, 15|
|Memory (System)|16.00GB (0.54GB free)|
|Process Argv|--crash-reporter-id 376cfb59-7eb8-40c7-8c72-b95f9866157a|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bpasero** [comment]
Could be a duplicate of https://github.com/microsoft/vscode/issues/134180
