### ISSUE TITLE
Content providers do not have `exclusive` property on vscode.dev

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#143412]
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:24.333Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.50

Live Share Jupyter notebooks in vscode.dev are currently broken because the Live Share content provider is not being used to open the files. Rather, the built-in vscode.dev Jupyter notebooks provider is being used. 

We used to use the `exclusive` flag in `NotebookRegistrationData` to mark a content provider as the default one for a file type. PR here: https://github.com/microsoft/vscode/commit/f5b2c93911a4c8115387c297db61e1d1efc71d96. When I made a repro extension, `vscode.proposed.notebookContentProvider.d.ts:registerNotebookContentProvider` does not include a parameter for `NotebookRegistrationData`, so it looks like that option has been removed?

We need a way to mark Live Share content providers as 'default' or 'exclusive' so that they are used rather than the built-in ones. 

This extension creates a content provider for *.ipynb files, but when opening one on web, the file automatically opens and shows the built-in default was selected:
![image](https://user-images.githubusercontent.com/22576531/154753776-e47afaff-4487-45f5-80e1-8759a2358286.png)

extension.ts
```
import * as vscode from 'vscode';
export function activate(context: vscode.ExtensionContext) {
	const contentProvider = new NotebookContentProvider('ally-vsls');
	context.subscriptions.push(vscode.workspace.registerNotebookContentProvider(
		'ally-vsls',
		contentProvider,
		{
			transientOutputs: false,
			transientCellMetadata: {},
			transientDocumentMetadata: {}
		}
	));
	context.subscriptions.push(vscode.workspace.onDidOpenNotebookDocument((document: vscode.NotebookDocument) => onDidOpenNotebookDocument(document)));
}
export function deactivate() {}
class NotebookContentProvider implements vscode.NotebookContentProvider {
    constructor(private readonly viewType: string) {}
    async openNotebook(uri: vscode.Uri): Promise<vscode.NotebookData> {
        let metadata = {};
        return {cells: [ new vscode.NotebookCellData(vscode.NotebookCellKind.Code, 'Ally\'s Content Provider', 'cpp')], metadata: metadata};
    }
    async saveNotebook(): Promise<void> { }
    async saveNotebookAs(): Promise<void> { }
    async backupNotebook(): Promise<vscode.NotebookDocumentBackup> { return { id: '', delete: () => { } }; }
}
```

cc @rebornix

**Comment by rebornix** [comment]
https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vscode-dts/vscode.proposed.notebookLiveShare.d.ts#L13

@alyssajotice The `exclusive` flag is now in `notebookLiveShare` proposed api so you may need to add that to you enable proposed api list.

**Comment by alyssajotice** [comment]
@rebornix this is not working for me. I made a new repro extension with the exclusive flag.

I am testing using [this method](https://code.visualstudio.com/api/extension-guides/web-extensions?msclkid=7badd509a61d11ecba16521ddfad9078#test-your-web-extension-in-on-vscode.dev) on insiders.vscode.dev. When I open a `.ipynb` file, I see the following: 
<img width="409" alt="image" src="https://user-images.githubusercontent.com/22576531/158870327-9fdb5eb6-0a48-4f01-a6b1-2ad556feacfc.png">

I would expect `ally-vsls` to be the default provider when using the exclusive flag. 

extension.ts
```
import * as vscode from 'vscode';
export function activate(context: vscode.ExtensionContext) {
	const contentProvider = new NotebookContentProvider('ally-vsls');
	context.subscriptions.push(vscode.workspace.registerNotebookContentProvider(
		'ally-vsls',
		contentProvider,
		{
			transientOutputs: false,
			transientCellMetadata: {},
			transientDocumentMetadata: {}
		},
		{
			displayName: `Live Share`,
			filenamePattern: ['*'],
			exclusive: true
		}
	));
	context.subscriptions.push(vscode.workspace.onDidOpenNotebookDocument((document: vscode.NotebookDocument) => onDidOpenNotebookDocument(document)));
}
export function deactivate() {}
class NotebookContentProvider implements vscode.NotebookContentProvider {
    constructor(private readonly viewType: string) {}
    async openNotebook(uri: vscode.Uri): Promise<vscode.NotebookData> {
        let metadata = {};
        return {cells: [ new vscode.NotebookCellData(vscode.NotebookCellKind.Code, 'Ally\'s Content Provider', 'cpp')], metadata: metadata};
    }
    async saveNotebook(): Promise<void> { }
    async saveNotebookAs(): Promise<void> { }
    async backupNotebook(): Promise<vscode.NotebookDocumentBackup> { return { id: '', delete: () => { } }; }
}
```

package.json
```
	"contributes": {
		"notebooks": [
            {
                "id": "ally-vsls",
                "type": "ally-vsls",
                "displayName": "ally-vsls",
                "selector": [
                    {
                        "filenamePattern": "*.ipynb"
                    }
                ]
            }
        ],
}

```

**Comment by rebornix** [comment]
@alyssajotice thanks for the detailed steps 👍 

https://github.com/microsoft/vscode/blob/5ca45d8e11a4783584fe6d74064947d4f6e2f14c/src/vs/workbench/contrib/notebook/browser/notebookServiceImpl.ts#L232-L238

@jrieken it seems that we don't allow the extension registration to override the initial registrations from the static contributions. In the live share case, they would register a serializer/contentProvider with an `exclusive` flag but it doesn't override the previous registration and throws an error.

**Comment by jrieken** [comment]
I see the bug but I also wonder if the approach of overriding content providers is really thought through. Since this can happen any time, e.g LS comes late with its exclusive/overriding content provider, there can be the situation where notebook working copies already exists. What is supposed to happen to them? Do we expect a transparent handover?

Also, stepping back one more step. What's the point of exclusive content provider again? I mean why are they needed? To my understanding, LS registers a remote file system and an existing, local content provider should be able to handles notebooks coming from that FS too.

**Comment by alyssajotice** [comment]
There are a few reasons we register local content providers. First, we provide Live Share support even if a guest does not have a content provider extension downloaded. Another reason is that we need the guest and the host to have the exact same document data so we can provide coediting and syncing. For example, if a guest installs version 2 of a notebook extension, and the host has version 1, one version could have extra data in the cells, making it impossible to be sure they have the same content. We also use this for cell operations: we add an id to each cell for the Live Share content provider to help track moving, adding, and deleting cells. Last, we register our notebook controller to be activated for all notebook files. I'm not sure if it would work if we had multiple controllers trying to execute notebook cells. 

@daytonellwanger and I brainstormed a few ideas. What if we created a setting for the user to specify which content provider they'd like to use? Then we can override that setting to favor the Live Share one. To address the timing issue where the user's built in content provider opens the notebook before Live Share's content provider is created, then we can add a toast to ask the user if they want to use Live Share's provider, and if so, we can close and reopen the notebook with the correct provider. 

Another thing I'd like to address: we do not have this issue when sharing/joining from VS Code desktop. What difference in web could be causing this problem? Is there a simpler solution here where we could make the behavior the same?

**Comment by jrieken** [comment]
>  What difference in web could be causing this problem? Is there a simpler solution here where we could make the behavior the same?

I don't know tbh. There is no `if(web) { ... }` code, maybe something related to timing or different extension availability? 

> What if we created a setting for the user to specify which content provider they'd like to use? Then we can override that setting to favor the Live Share one.

That made me wonder if you really need to override existing notebook types? Could it be additive, e.g contributing another notebook serializer that always delegates to LiveShare? Users can then pick which extension to use and we can help to make sure LiveShare is a "strong" default. It should also make it simpler to associate the LS notebook controller from the host, but it would make it hard to use a guest-side controller for a host-side notebook (which I am unsure if that's actually wanted or not...)

**Comment by alyssajotice** [comment]
For reference, here is a sample extension.ts on desktop that works as expected. 

extension.ts
```
import * as vscode from 'vscode';
export function activate(context: vscode.ExtensionContext) {
	const contentProvider = new NotebookContentProvider('ally-vsls');
	context.subscriptions.push(vscode.workspace.registerNotebookContentProvider(
		'ally-vsls',
		contentProvider,
		{
			transientOutputs: false,
			transientCellMetadata: {},
			transientDocumentMetadata: {}
		},
		{
			displayName: `Live Share`,
			filenamePattern: ['*'],
			exclusive: true
		}
	));
}
export function deactivate() {}
class NotebookContentProvider implements vscode.NotebookContentProvider {
    constructor(private readonly viewType: string) {}
    async openNotebook(uri: vscode.Uri): Promise<vscode.NotebookData> {
        let metadata = {};
        return {cells: [ new vscode.NotebookCellData(vscode.NotebookCellKind.Code, 'Ally\'s Content Provider', 'cpp')], metadata: metadata};
    }
    async saveNotebook(): Promise<void> { }
    async saveNotebookAs(): Promise<void> { }
    async backupNotebook(): Promise<vscode.NotebookDocumentBackup> { return { id: '', delete: () => { } }; }
}
```

package.json
```
		"notebooks": [
            {
                "id": "ally-notebook",
                "type": "ally-notebook",
                "displayName": "ally-notebook",
                "selector": [
                    {
                        "filenamePattern": "*.ipynb"
                    }
                ]
            }
        ],
```

When this extension is activated and I click to open a `*.ipynb` file, it opens with my content provider.

One interesting thing to note is that when I right click on the files, there is no `Open with` option like there is on web. I am going to take a minute to address your previous comment.

**Comment by alyssajotice** [comment]
> it would make it hard to use a guest-side controller for a host-side notebook 

We do have one guest-side controller for the host-side notebooks. The controller proxies execution requests to the host and updates the cell's execution states and outputs using execution tasks. We couldn't give the guest the ability to execute cells without it. 

> maybe something related to...different extension availability

Could there be something wrong with the built-in web python notebooks extension? Is there a built-in python notebooks extension for desktop? Perhaps that is the difference?

**Comment by jrieken** [comment]
> One interesting thing to note is that when I right click on the files, there is no Open with option like there is on web. I am going to take a minute to address your previous comment.

Yeah, I don't know why that is. @lramos15 would you know? Can an editor be so exclusive that it hides all others, like builtin text and such? On first load I do get the notification asking if I want to use it as default but no chance to revisit that?

@alyssajotice btw - I am running your sample code successfully in web and desktop. That is expected because in the sample no conflicting notebook types are defined. So when LS registers its content provider does it use `jupyter-notebook` as id or `vls-jupyter-notebook`. The former will be problematic, the latter should be fine

**Comment by alyssajotice** [comment]
> I am running your sample code successfully in web and desktop. That is expected because in the sample no conflicting notebook types are defined. So when LS registers its content provider does it use jupyter-notebook as type or vls-jupyter-notebook. The former will be problematic, the latter should be fine.

I am a bit confused by what you mean by this. If you're referring to the most recent extension.ts I provided, I would expect this to not work on web. This is what I would expect: https://github.com/microsoft/vscode/issues/143412#issuecomment-1071185412. My extension specifies notebook type `ally-vsls` and Live Share uses `vsls-...` for our notebook types.

**Comment by jrieken** [comment]
> I would expect ally-vsls to conflict with the built-in python content provider because they both have the same filenamePattern *.ipynb

We do support that - you can have multiple possible editors for a file type. Unless "exclusive" is used, VS Code allows you to open a file with any of them and also allows to reopen a file with another editor. Notebooks also support that. What's not supported is

* define the same _notebook type_ multiple times, e.g you can have `{"type": "ally-notebook", "selector": [{"filenamePattern": "*.ipynb" }]}` and `{"type": "jupyter-notebook", "selector": [{"filenamePattern": "*.ipynb" }]}` because the `type` property is different but you cannot reuse the same type property
* you can reopen notebooks with different serialisers (different notebook types) but one file can only opened as one notebook type at a time.

**Comment by jrieken** [comment]
This is now fixed, to verify

* have two content providers for one file type
* double click to open a notebook file (make sure it isn't in preview mode, tab title must not be italic)
* from the tab context menu select "reopen with" and select the alternative notebook type
* the editor content changes, no errors

**Comment by alyssajotice** [comment]
Are these changes on Insiders, stable, or both? I want to make sure I'm testing correctly.

**Comment by jrieken** [comment]
Insiders for now, will than make it into 1.67 stable

**Comment by lramos15** [comment]
@alyssajotice Did you verify this fix works?
