### ISSUE TITLE
Test: Extensions recommendations per language mode

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#14348]
#13415

- [x] any OS @kieferrm 
- [x] any OS @jrieken 

![img](https://cloud.githubusercontent.com/assets/22350/19602049/f8354836-97ab-11e6-8b17-f36ff0f29a97.png)

There is now a new item in the language mode picker which lets the user search for extensions in the Marketplace that can handle or are related to that extension.

**Comment by rebornix** [comment]
Test this one for @kieferrm .

**Comment by gregvanl** [comment]
https://github.com/Microsoft/vscode/issues/14549

**Comment by gregvanl** [comment]
Doesn't work very well for Markdown files. https://github.com/Microsoft/vscode/issues/14549
