### ISSUE TITLE
Notify users of extensions when opening unknown file type

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#14347]
cc @seanmcbreen @waderyan 

> The scenario here is that the user adds a new file say foo.tex we don;t out of the box know what .tex is so we render as plaintext. We could do a check in the background to see if the marketplace understands .tex since it does we would notify the user and let them review the marketplace for results.
> 
> There is some concern that this could be annoying for some users who look at lots of files with random extensions - so we need to go here carefully. We would for instance need to offer the ability to stop the nag permanently for some file types.

**Comment by mjbvz** [comment]
I believe this was implemented
