### ISSUE TITLE
Add keyboard shortcuts for scrolling horizontally

### ISSUE THREAD

**Issue by Brikaa** [microsoft/vscode#143466]
There are keyboard shortcuts for scrolling vertically (scrollLineUp and scrollLineDown) but there aren't any for scrolling horizontally.

**Comment by Samyak-Bumb** [comment]
Yes, It should be implemented

**Comment by tobealive** [comment]
Waiting quiet a while for this feature, hoping that it's implementation is coming closer I wanted to bring it on the table again. Is there any update or plans ? Which is pretty sassy to ask looking at the full schedule 😬 please forgive ✌️

**Comment by linqingyao** [comment]
I also need this feature, but I can't force a line wrap on virtual text with Error len

**Comment by edgar-ta** [comment]
Agree; it'd be nice to be able to scroll horizontally without using the mouse

**Comment by mccrimmonmd** [comment]
I would also like this feature. It's always a nasty surprise when I'm using ctrl+up and ctrl+down to look over my code and then I try to scroll sideways in the intuitive way...

**Comment by rudrakshkarpe** [comment]
It seems an interesting topic and multiple times I missed an ultimate productivity feeling on my mechanical keys cuz of scrolling horizontally with a mouse 

Implementation of this feature would lead to more productivity for developers!

**Comment by Brikaa** [comment]
@alexdima I am thinking about implementing this. What should the measuring unit be? Columns? Character width currently seems to be coupled with the font info.

**Comment by alexdima** [comment]
To verify, you can use the following keybindings:
```
{ "key": "ctrl+alt+left", "command": "scrollLeft" },
{ "key": "ctrl+alt+right", "command": "scrollRight" },
```

**Comment by Brikaa** [comment]
Aren't these shortcuts used by default for splitting tabs?

**Comment by ArturoDent** [comment]
@Brikaa Those aren't default keybindings.  You have to set your own, so those are only examples (for teting).
