### ISSUE TITLE
Tab size Indentation

### ISSUE THREAD

**Issue by ymrabti** [microsoft/vscode#143417]
Issue Type: <b>Bug</b>

tab size is not taked on consideration in settings:
my settings
    "editor.tabSize": 4,
    "[javascript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features",
        "editor.tabSize": 4
    },

but does not work
actualy he sets the default indentation tab size : 2 

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.05GB free)|
|Process Argv|--crash-reporter-id ddecd975-5500-46dc-acc0-a1fe3e5fee2f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.2
nodejs-helper|Ard|0.0.4
puzzle-vscode|big|0.0.2
xdml-vscode|big|0.0.1
vscode-intelephense-client|bme|1.8.1
vscode-office|cwe|2.5.3
dart-code|Dar|3.34.0
flutter|Dar|3.34.0
vscode-eslint|dba|2.2.2
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
vscode-html-css|ecm|1.11.0
kotlin|fwc|0.2.23
live-html-previewer|hdg|0.3.0
svgeditor|hen|2.9.0
rest-client|hum|0.24.6
svg|joc|1.4.17
vsc-python-indent|Kev|1.14.2
share|lyu|0.4.4
MagicPython|mag|1.1.0
Kotlin|mat|1.7.1
fluent-icons|mig|0.0.16
dotenv|mik|1.0.1
vscode-docker|ms-|1.19.0
vscode-language-pack-fr|MS-|1.64.7
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.3
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cmake-tools|ms-|1.9.2
vscode-typescript-next|ms-|4.7.20220217
vsliveshare|ms-|1.0.5330
vscode-groovy-lint|Nic|1.7.5
autodocstring|njp|0.6.1
vscode-thunder-client|ran|1.12.1
vscode-xml|red|0.19.1
vscode-yaml|red|1.4.0
LiveServer|rit|5.7.4
custom-xml-formatter|tho|1.3.2
cmake|twx|0.0.17
tab-groups|usa|1.4.8
vscodeintellicode|Vis|1.2.17
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrt:30437039
vsrem710:30416614
dsvsc009:30440023
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvid2:30438800
helix:30440343

```

</details>

**Comment by ArturoDent** [comment]
Review the setting `Editor: Detect Indentation`.  If the file already has 2-spaced tabs then your `tabSize` settings will not take effect if `Detect Indentation`  is enabled.  You could include the `Detect Indentation` in your javascript language-specific setting if you wish.
