### ISSUE TITLE
Allow to protect out of workspace file

### ISSUE THREAD

**Issue by CaptainGopher** [microsoft/vscode#143445]
Intellij platform has a nice [feature](https://www.jetbrains.com/help/idea/non-project-files-access-dialog.html) that can protect from accidental modifications of file that was opened through (Go to definition) and which is not belonging to the workspace folder.

For example, I write golang with goland, and it will prevent me modifying go library file.
![image](https://user-images.githubusercontent.com/28745416/154800779-e7df5e03-7d76-45b9-b252-5c98de77914c.png)

Does vscode have similar protection mechanism?

**Comment by WorkerYifei** [comment]
I think it's useful for go developer.
