### ISSUE TITLE
cmd + shift + g not works on mac to open source control panel

### ISSUE THREAD

**Issue by nabtron** [microsoft/vscode#143439]
All other sidebar tabs shortcuts work with cmd + shift + (e,f,d) and also with ctrl + shift + ... on a mac. However, source control panel opens with ctrl + shift + g only and does not work with cmd + shift + g.

**Comment by gjsjohnmurray** [comment]
Please use the advice at https://github.com/microsoft/vscode/wiki/Keybinding-Issues to investigate.
