### ISSUE TITLE
debug ts/js async function and local variables all null, this variables is null

### ISSUE THREAD

**Issue by leafsnow** [microsoft/vscode#143477]
![384785a1f11f5ad463ce03e53276779f7e082112_2_1035x217](https://user-images.githubusercontent.com/6291246/154825246-6d1258f4-c637-465c-b298-d551e5149576.png)

tsconfig.json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "target": "ES2015",
    "module": "ES2015",
    "strict": true,
    "types": [
      "./temp/declarations/jsb",
      "./temp/declarations/cc.custom-macro",
      "./temp/declarations/cc",
      "./temp/declarations/cc.env"
    ],
    "paths": {
      "db://internal/*": [
        "D:\\CocosDashboard_1.0.12\\resources\\.editors\\Creator\\3.4.1\\resources\\resources\\3d\\engine\\editor\\assets\\*"
      ],
      "db://assets/*": [
        "F:\\Project\\Quest\\Quest\\assets\\*"
      ]
    },
    "experimentalDecorators": true,
    "isolatedModules": true,
    "moduleResolution": "node",
    "noEmit": true,
    "forceConsistentCasingInFileNames": true
  }
}

{
  /* Base configuration. Do not edit this field. */
  "extends": "./temp/tsconfig.cocos.json",

  /* Add your custom configuration here. */
  "compilerOptions": {
    "strict": false,
    "lib": [
      "es2017",
      "dom",
    ],
  }
}

**Comment by leafsnow** [comment]
Compiled js has code:
var _this2 = this;
![image](https://user-images.githubusercontent.com/6291246/154828608-ed24d509-893d-4839-a3e0-8106aa3265d4.png)

**Comment by alekk84** [comment]
I have same trouble.
Watch and variables (on hover) not showing in async ts function. In sync function everything is showing. In Chrome devtools everything is showing too.
