### ISSUE TITLE
higlightActiveIndentation conflicts with bracketPairs in JSX/TSX

### ISSUE THREAD

**Issue by rolandleth** [microsoft/vscode#143484]
[](https://user-images.githubusercontent.com/5285733/141713992-46c5f550-1b7c-4a62-9dde-e4368ff34da1.png)[](https://user-images.githubusercontent.com/5285733/141714021-2a9f8c51-b3ec-4d73-99f4-7d8af7306641.png)Does this issue occur when all extensions are disabled?: No

VS Code Version: 1.64
OS Version: Mac Monterey
Steps to Reproduce:

When only `editor.guides.highlightActiveIndentation` is enabled, the HTML active indentation in TSX shows correctly
![141713992-46c5f550-1b7c-4a62-9dde-e4368ff34da1](https://user-images.githubusercontent.com/1858700/154832988-6011a0fd-b19e-4f88-9542-f4f3033766d3.png)

But after enabling `editor.guides.bracketPairs` at the same time, the HTML active indentation in TSX gets disabled
![141714021-2a9f8c51-b3ec-4d73-99f4-7d8af7306641](https://user-images.githubusercontent.com/1858700/154832995-e0ce65b1-756b-48ab-898b-c1196d4f9c82.png)

Please don’t mark this as a feature request, because it’s clearly missing functionality, functionality that Bracket Pair Colorizer had (which is now discontinued).

If we can agree that this is useful in pure HTML, then we can agree that not having it in TSX is detrimental.

**Comment by hediet** [comment]
Please reference any related issues (in this case #137190), that helps us a lot.

I'll keep this open as the original duplicate has been closed automatically.

**Comment by rolandleth** [comment]
Sorry, didn't realise linking it would help 🙈 Thanks for keeping it open! If there's any other info/input I can help with, let me know.

**Comment by hediet** [comment]
With tomorrows insiders build, you can set this:
```json
"editor.guides.highlightActiveIndentation": "always",
```

Which will cause the desired behavior:

![image](https://user-images.githubusercontent.com/2931520/164448341-f9f08ebb-b10f-4497-9a2c-3ab1d7738da8.png)


The default behavior remains unchanged:
```json
"editor.guides.highlightActiveIndentation": true,
```
![image](https://user-images.githubusercontent.com/2931520/164448389-c0e7912b-af80-45ee-ba64-c217c79fcc49.png)

@isidorn what do you think of the name of the setting value?

**Comment by isidorn** [comment]
@hediet I find the difference between `true` and `always` very hard to understand by the user :)
Why don't we just behave like this by default? What is the downside? You are worried about two active indentations at the same time?

**Comment by hediet** [comment]
> What is the downside? You are worried about two active indentations at the same time?

If set to `always`, there would always be both the indentation guide and the bracket pair guide, not necessarily aligning. Because the bracket pair guide is more precise, the idea was to not show the active indentation guide (this was a feature request early on from @alexdima).

I also have a slight preference for the current default, but don't really mind.
