### ISSUE TITLE
built-in feature to sort contents of file

### ISSUE THREAD

**Issue by GoddnessTimothy** [microsoft/vscode#143560]
Please implement built-in sorting for vscode.  At the moment, I rely on an extension but it would be really nice to have this feature built-in. As a guide, please refer to screenshot below showing that Notepad++ (also a great editor) has this built into the edit menu.  This will ultimately make comparing 2 or more files much easier especially when they are from the interweb and aren't always sorted. 
![sort](https://user-images.githubusercontent.com/8746379/155003561-4b7fe01e-88db-46f2-ab44-6360edf2bf7e.png)

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/155047274-f2dde54f-ed0a-4adc-9e82-c2765671ce43.png)

There are built-in commands to sort lines. If that's not enough, extensions are recommended over adding them into Code itself.
