### ISSUE TITLE
Como sumir com os itens da extesão do Docker: Containers, Volumes e outros 

### ISSUE THREAD

**Issue by RenanNeumann** [microsoft/vscode#143569]
Issue Type: <b>Bug</b>

Since the report interface was shown in portuguese, and I did not read its first line, here it is in english:

The problem may be with the Docker extension but it is related to the use of the Side Panel.
## To reproduce the issue:

With Docker extension in the activity bar open, click on Containers, Images or other and move/drag to Side Panel
In the Side Panel, right-click the top bar and click Move Views to Panel
Done
The Docker extension will not have the item listed in the (...) and when you open the Side Panel it will be without the Docker extensions

After the first restart of the Docker extension, it was shown duplicated and the items came back inside the second icon
After the second test, deactivation and reactivation, the bug was proved to be "permanent"

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
OS version: Linux x64 5.4.0-99-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 5, 4|
|Memory (System)|7.68GB (0.34GB free)|
|Process Argv|--unity-launch --crash-reporter-id 2d42cbda-23b0-499f-bedd-4d65f76eacbb|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-twig-pack|baj|1.1.0
vscode-intelephense-client|bme|1.8.1
bracket-pair-colorizer|Coe|1.0.62
python-preview|don|0.0.4
prettier-vscode|esb|9.3.0
docker-linter|hen|0.5.0
beautify|Hoo|1.5.0
rest-client|hum|0.24.6
twig-language-2|mbl|0.9.2
git-graph|mhu|1.30.0
vscode-docker|ms-|1.19.0
vscode-language-pack-pt-BR|MS-|1.64.7
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.3
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
indent-rainbow|ode|8.2.2
format-html-in-php|rif|1.7.0
todotasks|san|0.5.0
python|tht|0.2.3
lorem-ipsum|Tyr|1.3.1
bootstrap-3-snippets|wcw|0.1.0
twig|wha|1.0.2
php-debug|xde|1.24.0
php-pack|xde|1.0.3
php-intellisense|zob|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc008:30440022
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvidc:30438801
helix:30440343

```

</details>

**Comment by RenanNeumann** [comment]
Since the report interface was shown in portuguese, and i did not read its first line, here it is in english:

The problem may be with the Docker extension but it is related to the use of the Side Panel.
## To reproduce the issue:

With Docker extension in the activity bar open, click on Containers, Images or other and move/drag to Side Panel
In the Side Panel, right-click the top bar and click Move Views to Panel
Done
The Docker extension will not have the item listed in the (...) and when you open the Side Panel it will be without the Docker extensions

After the first restart of the Docker extension, it was shown duplicated and the items came back inside the second icon
After the second test, deactivation and reactivation, the bug was proved to be "permanent"

**Comment by sbatten** [comment]
@RenanNeumann can you please show a screen recording of the issue or similar. I followed the steps, but everything did what was expected so I am unclear on the issue currently.

**Comment by RenanNeumann** [comment]
Well this is somewhat embarrassing, but the real problem was that I didn't notice the docker extension showing up next to the terminal, I only noticed it while I was recording the screen, and thinking about it, maybe I didn't notice it before because there was text in the terminal and its sudden pop distracted me from the docker "tab" next to it, if I could take anything out of it I would suggest a focus effect on the new tab of the panel or switching to it.
Thank you for your attention

**Comment by sbatten** [comment]
@RenanNeumann thanks for taking the time to provide feedback. the reason we don't focus moved panels is because there can be multiple and the user could be moving many through a variety of interactions and we want to minimize the UI churn/interruptions.
