### ISSUE TITLE
Open in background hotkey should only activate if cursor is at end of line

### ISSUE THREAD

**Issue by wprater** [Microsoft/vscode#14350]
- VSCode Version: 1.7

The right arrow key used to open the selected quick open item in the background should only dispatch if the cursor was at the end of the line and not used with another modifier e.g. option or command/ctrl.

When navigating up/down through the list, the cursor should be placed to the end of the line.  This behavior is similar to ST.

/cc @bpasero 

Feel free to assign to me and comment regarding your feelings on the UX.

**Comment by bpasero** [comment]
@wprater would it not make more sense to ask the user to hold a modifier key before opening a file in the background? the user might quickly arrow to the right and would not expect any editor to open.

**Comment by wprater** [comment]
yeah, I think that is a valid approach as well.  I was going with what ST had modeled.  We cannot use the `cmd` or `option` modifiers as they are used to jump word boundaries.  ST uses the end of line technique to prevent this, perhaps?

I have another idea for UX: when you first pull up the quick open widget, can we have no items selected until one hits down or starts to type?

**Comment by bpasero** [comment]
Maybe we just do it if you press Alt key while using the arrow keys. It is less discoverable though.

No, we cannot change the auto selection, if we did, you would always have to arrow down after searching, that is very awful UX.

**Comment by bpasero** [comment]
@wprater pushed a change to behave like Sublime, maybe you give it a swirl.

**Comment by wprater** [comment]
> No, we cannot change the auto selection, if we did, you would always have to arrow down after searching, that is very awful UX.

the idea would be upon typing the first entry could be auto-selected.  if none were found, nothing would be selected.  you can still use the down arrow to navigate.

**Comment by wprater** [comment]
> @wprater pushed a change to behave like Sublime, maybe you give it a swirl.

made a comment on your commit.

**Comment by Tyriar** [comment]
@bpasero is this feature documented anywhere? I only just discovered it from this.

**Comment by wprater** [comment]
@Tyriar here is a PR, if that's helpful to you
https://github.com/Microsoft/vscode/pull/13925
