### ISSUE TITLE
Extension's language overides `files.associations` setting

### ISSUE THREAD

**Issue by Commandtechno** [microsoft/vscode#143567]
Does this issue occur when all extensions are disabled?: No

The issue does not seem with the extension itself, but with how VSCode decides which language to use. If this is still not applicable here, please tell me.

- VS Code Version: 1.64.2 (Stable)
- OS Version: Ubuntu 21.10

Steps to Reproduce:

1. Install an extension with a language that has the same file extension as a built-in language. Example: The [PostCSS Language Support](https://marketplace.visualstudio.com/items?itemName=csstools.postcss) extension which registers the language with the `.css` file extension
2. Create, or open a file with that file extension, in this case a css file
3. Here it will show the file as the extension's registered language, in this case, PostCSS
4. Select "Change Language Mode" from the command pallete, then "Configure File Association for '.{extension}'"
5. Select the original VSCode language, in this case, the default CSS

This adds `files.associations` to `settings.json` with `*.css` mapped to `css`.

Though when you go back to the original file it is still the extension's language.

In this case the file still shows as PostCSS when it should be showing as CSS.

**Comment by Commandtechno** [comment]
Just thought I would add a few screenshots

`files.associations` with `*.css` set to css in the settings

![image](https://user-images.githubusercontent.com/68407783/155180170-f282789e-30ef-48b4-b36d-92a833621497.png)

`.css` file still registering as PostCSS

![image](https://user-images.githubusercontent.com/68407783/155180320-10992604-ae69-477c-a348-c3c1420f2a7e.png)

PostCSS language from its package.json registering with the `.css` extension

![image](https://user-images.githubusercontent.com/68407783/155180433-16646f25-1c29-41bb-999b-2ad57331fac9.png)

**Comment by aeschli** [comment]
I can reproduce on Version: 1.65.0-insider (user setup)
Commit: 32456dc9e7d3194a94dd3ee0322ccf47e461d09c
Date: 2022-02-23T05:16:22.798Z

I would also expect that the file opens as CSS if that's specified in the user settings.

**Comment by bpasero** [comment]
The editor mime type and thus language is determined here:

https://github.com/microsoft/vscode/blob/d2b75508eebb93d95b185e542cdca28e6853c4fb/src/vs/editor/common/services/languagesAssociations.ts#L109

If someone wants to investigate, open for help.

**Comment by bpasero** [comment]
This appears to be an issue in the `languagesRegistry`: 

https://github.com/microsoft/vscode/blob/35af2cd91d8c6e770928ec13503aa971916214fc/src/vs/editor/common/services/languagesRegistry.ts#L351-L359

Here the `mimeType` is `text/css` which is the one configured in settings. But the `_mimeTypesMap` has `postcss` stored for this mime type.
