### ISSUE TITLE
Test comments panel refresh

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#143545]
Refs: #142081

- [x] anyOS @sana-ajani
- [x] anyOS @lszomoru
- [x] anyOS @roblourens

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23143545%0A%0A&assignees=alexr00)

---

The comments panel as been given a refresh. There are new icons, not all comments are shown, and in general the view is more thread focused with the goal being to provide an overview of the comments and not full comments. The main idea behind not showing full comments is that the best place to show full comments is in the editor where you have the full context of the comment.

To verify:
1. Install the pre-release version of GitHub Pull Requests and Issues (instructions: https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build). Browser is fine if you want.
2. Open a PR that you don't mind leaving comments in (You can open a PR from the "Pull Requests" view). Preferably one that has comments and replies from others too. If it doesn't, ask me or someone else to leave you a few comments + replies.
3. Open the "Comments" view (command "Comments: Focus on Comments View").
4. Since this is mostly a layout/display change, most of what needs to be verified is very opinion based. Verify the following:
    - You can understand what's going on in the "Comments" view.
    - The "Comments" view functions well as an overview of comments.
    - Alignment/size/colors/etc. looks good in "Comments" view.
    - When you add a reply to a comment, the "Comments" view updates and the update make sense.
    - When you add a new comment thread the "Comments" view updates and the update makes sense.

**Comment by roblourens** [comment]
Looks great!
