### ISSUE TITLE
Test Improved Audio Cues

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#143550]
Refs: https://github.com/microsoft/vscode/issues/142540 https://github.com/microsoft/vscode/issues/141444  https://github.com/microsoft/vscode/issues/142121 

- [x] anyOS @isidorn
- [ ] anyOS @amunger

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23143550%0A%0A&assignees=hediet)

---

* Trigger the command "Help: List Audio Cues" and verify that it works and is helpful
* Search for `audiocue` settings and configure them as you like:
![image](https://user-images.githubusercontent.com/2931520/154982918-8d7523ed-b203-4de7-b48e-6d19c631b415.png)
* Verify they work
* Verify audio cues are debounced
    * error audio cues are debounced by typing
    * fast line changes are debounced

**Comment by isidorn** [comment]
Great job, works nicely!

**Comment by amunger** [comment]
very minor bug when multiple queues fire at once, but sounds good other than that
