### ISSUE TITLE
1.65.0-insider/Electron 16  Fails to launch using native Wayland

### ISSUE THREAD

**Issue by mmarinero** [microsoft/vscode#143579]
VS Code Insider has stopped working using native Wayland after the 1.65 upgrade. Current VS Code stable works correctly on Wayland. The crash only happens when using Wayland native, when using XWayland it works properly.

This version also bumped Electron to 16 so it may be that or the related chromium bump but the current chromium version works fine on Wayland in the same system.

This is the end of the verbose output

```log
[main 2022-02-21T23:58:13.337Z] IPC Object URL: Registered new channel vscode:abaf6d3d-205e-4932-9350-82657babf20a.
[main 2022-02-21T23:58:13.337Z] window#validateWindowState: validating window state on 2 display(s) { mode: 1, x: 565, y: 262, width: 1028, height: 773 }
[main 2022-02-21T23:58:13.337Z] window#validateWindowState: multi-monitor working area { x: 0, y: 0, width: 1920, height: 1080 }
[main 2022-02-21T23:58:13.338Z] window#ctor: using window state { mode: 1, x: 565, y: 262, width: 1028, height: 773 }
[39177:0222/005813.339139:WARNING:wayland_surface.cc(116)] Server doesn't support zcr_alpha_compositing_v1.
[39177:0222/005813.339163:WARNING:wayland_surface.cc(127)] Server doesn't support overlay_prioritizer.
[39177:0222/005813.339727:ERROR:cursor_loader.cc(114)] Failed to load a platform cursor of type kNull
```
Full log [insider-crash.log](https://github.com/microsoft/vscode/files/8112665/insider-crash.log)

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0-insider
a0da9978b10ae0b9307c7f545b50a8500efff7eb
x64
- OS Version: Ubuntu 21.10

Steps to Reproduce:

1. Run `code-insiders --ozone-platform=wayland` or `code-insiders --ozone-platform=wayland  --verbose --disable-extensions`
2. VS Code doesn't start

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/141964
