### ISSUE TITLE
Cannot change python image file name to save.

### ISSUE THREAD

**Issue by shishirpy** [Microsoft/vscode#14353]
- VSCode Version: 1.6.1
- OS Version: OS X El Capitan 10.11.6

Steps to Reproduce:

1. Install the package - "Python" by Don Jayamanne
2. Write simple python script to plot a graph.
3. `cmd + shift + p`  
4. select "Python: Run python file in terminal"
5. Once the graph shows up click save button on the plot window.
6. Try changing the name of the file being saved.
7. **You will not be able to change the file name**.

**Comment by bpasero** [comment]
@shishirpy where does the image show up? can you share screenshots?

**Comment by shishirpy** [comment]
@bpasero : The image opens as a new window. 


<img width="1440" alt="screenshot 2016-10-25 14 54 05" src="https://cloud.githubusercontent.com/assets/1947809/19680325/dd2028a8-9ac2-11e6-94f9-083ba1347fae.png">

**Comment by bpasero** [comment]
@shishirpy this window does not seem to belong to VS Code but some other application. We do not provide a save button in such a window, please report to the program.
