### ISSUE TITLE
A keypad button not functioning

### ISSUE THREAD

**Issue by Start2finish** [microsoft/vscode#143509]
Issue Type: <b>Performance Issue</b>

I notice that the S button is not working on my vs code. please I need an urgent solution to this. Please help!!!

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.82GB free)|
|Process Argv|--crash-reporter-id 67ee15ab-9a58-482f-9ee2-9a863e61abc7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    88	  7108	code main
    0	   149	  2360	   gpu-process
    0	   143	  2388	   window (● index.html - cmm007 - Visual Studio Code)
    0	    97	  6944	   shared-process
    0	    77	  8572	     ptyHost
    0	     6	  7340	       console-window-host (Windows internal process)
    0	    67	  7820	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    73	 12272	     fileWatcher
    0	    77	  8524	   issue-reporter
    0	    38	 10464	   utility-network-service
    0	   136	 10952	   extensionHost
    0	    96	 10816	     "C:\Users\user\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=10952
    0	    25	 11720	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● index.html - cmm007 - Visual Studio Code)
|    Folder (cmm007): 5 files
|      File types: html(1) md(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.5.0
gitignore|cod|0.7.0
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|11.7.0
prettier-vscode|esb|9.2.0
vscode-firefox-debug|fir|2.9.6
vscode-pull-request-github|Git|0.36.2
github-repository-manager|hen|1.3.2
LiveServer|rit|5.7.4
open-in-browser|tec|2.0.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
vscop841:30438915
dsvsc009:30440023
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

If that doesn't help, look at https://github.com/microsoft/vscode/wiki/Keybinding-Issues for advice.
