### ISSUE TITLE
`vscode.workspace.onDidCreateFiles` doesn't fire on Explorer copy/paste or drag/drop operations

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#143557]
Issue Type: <b>Bug</b>

1. Clone microsoft/vscode-extension-samples
1. Open the helloworld-sample folder
1. Install, build, verift that its contributed "Hello World" command activates the extension and shows a notification.
1. Update the vscode version references in package.json in two places to use 1.43 minimum.
1. Add code to activate function in extension.ts, for example:
```ts
	context.subscriptions.push(
		vscode.workspace.onDidCreateFiles((e: vscode.FileCreateEvent) => {
			return;
		})
	);
```
1. Build, run, use "Hello World" command to activate.
1. Set breakpoint on return line above.
1. Open a folder.
1. Use Explorer button or context menu to create a new file. Confirm that the event fires and your breakpoint is hit.
1. Continue from breakpoint.
1. Use Explorer context menu to copy/paste or use drag/drop with modifier to drip as a copy.
:bug: The event callback does not run, despite the API doc stating:

> Note: This event is triggered by user gestures, like creating a file from the explorer, or from the workspace.applyEdit-api, but this event is not fired when files change on disk, e.g triggered by another application, or when using the workspace.fs-api.

Issue also exists in 1.64.2

VS Code version: Code - Insiders 1.65.0-insider (a0da9978b10ae0b9307c7f545b50a8500efff7eb, 2022-02-21T05:15:17.930Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by bpasero** [comment]
cc @isidorn

**Comment by JacksonKearl** [comment]
@bpasero the extension host's event is only emitting from `workingCopyFileService`'s `_onDidRunWorkingCopyFileOperation` event, but the explorer is using the `bulkEditService`'s `apply`, which doesn't seem to talk to the working copy service. What do you think the fix here should be? (cc @jrieken)

**Comment by JacksonKearl** [comment]
My bad, the real bug is that this block:
https://github.com/microsoft/vscode/blob/751b611639ba772dedacdfc2aeffd86eda3de5ba/src/vs/workbench/api/common/extHostFileSystemEventService.ts#L172-L186

doesn't handle `FileOperation.Copy` events. 

cc @jrieken

**Comment by bpasero** [comment]
Pragmatic fix would probably to treat `COPY` the same as `CREATE`.
