### ISSUE TITLE
Files from linux home folder not always properly opened (wsl2 to windows 11 path translation)

### ISSUE THREAD

**Issue by alkesander** [microsoft/vscode#143504]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
- OS Version:
W11 Version 10.0.22000 Build 22000 + WSL2 Ubuntu 20.04.3 LTS

Steps to Reproduce:

1. Go to Windows home folder, for example: cd /mnt/c/Users/alke
2. Open some file from linux home folder (for example /home/alke) using ~ as a shortcut: code ~/.ssh/known_hosts
3. See that file does not exist.
4. Go to linux home folder: cd ~
5. Open the same file by running the same command: code ~/.ssh/known_hosts
6. See that file is properly opened.

Apparently there is some problem when translating path from wsl2 ubuntu to windows depending on what is the context where the command is executed.

**Comment by aeschli** [comment]
Is this in the integrated terminal of a WSL window, or from an external Ubuntu terminal?

The steps above work for me for both. The `~` is correctly resolved. This is done by the shell.
If it's with the external terminal,
can you run `VSCODE_WSL_DEBUG_INFO=true code ~/.ssh/known_hosts`? You should then see that `wslCode.sh` is called and it should happen with the resolved input path.
