### ISSUE TITLE
New notebook 'text/plain' renderer breaks alignment

### ISSUE THREAD

**Issue by tvaucher** [microsoft/vscode#143538]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0-insider (Universal) Commit: a0da9978b10ae0b9307c7f545b50a8500efff7eb
- OS Version: Mac OS Monterey 12.2.1

Follow up issue to #143194 as this is a degradation in UX compared to the non-Insider version. Any input on that @rebornix ?

Current:
![image](https://user-images.githubusercontent.com/8888706/154943705-46796a05-28cd-4919-b707-fa4f98abf629.png)

Expected: Different columns should be aligned
![image](https://user-images.githubusercontent.com/8888706/154943762-2dff00be-2eae-431c-ae0d-1b2d9cf9530c.png)

**Comment by rebornix** [comment]
@tvaucher thank you for the bug report!
