### ISSUE TITLE
Request languageServerProvider-any.request failed with message: Extension 'vscode.typescript-language-features' CANNOT use API proposal: extensionRuntime.

### ISSUE THREAD

**Issue by robiXxu** [microsoft/vscode#143525]
Issue Type: <b>Bug</b>

Request languageServerProvider-any.request failed with message: Extension 'vscode.typescript-language-features' CANNOT use API proposal: extensionRuntime. Its package.json#enabledApiProposals-property declares: inlayHints, languageStatus, resolvers, workspaceTrust but NOT extensionRuntime. The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api vscode.typescript-language-features

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
OS version: Linux x64 5.16.10-arch1-1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.67GB (51.04GB free)|
|Process Argv|--crash-reporter-id f9f582dc-5973-48dd-988a-991eca2f4772|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.3.6
gitlens|eam|11.7.0
prettier-vscode|esb|9.2.0
cpp-reference|Guy|0.1.7
vscode-auto-open-markdown-preview|hnw|0.0.4
backbone-js-snippets|ioa|0.0.1
Sbt|itr|0.1.7
search-node-modules|jas|1.3.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.3
jupyter|ms-|2022.1.1301854968
vsliveshare|ms-|1.0.5330
vsliveshare-pack|ms-|0.4.0
vscode-yaml|red|1.4.0
scala|sca|0.5.5
mdx|sil|0.1.0
sass-indented|syl|1.8.19
cpp-compile|tch|0.0.2
vim|vsc|1.22.2

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30438340
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrt:30437039
vsrem710cf:30416617
dsvsc008:30440022
pythonvsnew555:30436484
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343

```

</details>

**Comment by gjsjohnmurray** [comment]
What version number shows in the upper right of your equivalent of this screenshot?

![image](https://user-images.githubusercontent.com/6726799/154921927-2cca4ba7-8e39-4c8d-9dab-daf43931b355.png)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all non-builtin [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
