### ISSUE TITLE
Test Contextual Unicode Highlighting

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#143553]
Refs: https://github.com/microsoft/vscode/issues/140960

- [x] anyOS @tanhakabir
- [x] anyOS @rchiodo

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23143553%0A%0A&assignees=hediet)

---

* Verify that nothing is highlighted in the following string (trusted workspace):
```ts
const str1 = `
في الرياضيات والمنطق والمعلوماتية، يطلق مصطلح اللغة الشكلية L على أي مجموعة من
الجمل محدودة الطول المأخوذة من مجموعة نهائية A تسمى الحروف الأبجدية. فمن خلال
مختلف تطبيقات اللغات الشكلية، يمكن أن ننظر إلى اللغة الشكلية على أنها مماثلة
لمجموعة كلمات أو مجموعة جمل.
`

const str3 = "п рото текст каириллицей";

```

* Verify that critical characters in ASCII situations are still highlighted:
```ts
const str4 = "аdmin";
```

**Comment by justanotheranonymoususer** [comment]
Adding a test case suggestion from #140960:
```
if (variable_א || variable_ב || vаriable_ג) {
    admin = true;
}
```
Should highlight.

**Comment by hediet** [comment]
Exactly.

**Comment by rchiodo** [comment]
Non highlights work but highlights are not showing up at all for me.
