### ISSUE TITLE
Ruby: After pasting code block, the following line is reindented (for full autoindent)

### ISSUE THREAD

**Issue by 64kramsystem** [microsoft/vscode#143573]
Issue Type: <b>Bug</b>

The VSC default Ruby editor (full autoindentation) has a quirky behavior, that is often disruptive - it reindents the line following the code pasted. It's not present in the other languages I've tested.

## Reproduction steps

The indentation used for this example is the default (4). It works the same also for 2.

Copy the following text into the copy/paste buffer (Ctrl+C):

```rb
def bar
end
```

Create a Ruby file with the following content:

```rb
    def foo; end
    def baz; end
```

Now, go to the beginning of the second line (`  def baz...`) and paste the buffer (Ctrl+V); the `    def baz` line will be reindented:

```
    def foo; end
    def bar
    end
        def baz; end
```

## Considerations

This behavior is disruptive, as I often find myself having to revert the reindentation. Interestingly, if typing `Ctrl + Z` after the paste, all the text (including the paste) is realigned as intended, so it seems that the VSC editor is automatically inserting an extra step.

The example presented is artificial, for simplicity, but it frequently happens on real-world use cases.

I've tried on other languages (e.g. C, Shell Script), and they don't share this behavior. As far as I remember, this is the first time I see something similar.

I've always experienced this behavior in any VSC version I've used, and it's not related to any (installed) extension.

## VSC data

VS Code version: Code - Insiders 1.65.0-insider (a0da9978b10ae0b9307c7f545b50a8500efff7eb, 2022-02-21T05:15:22.150Z)
OS version: Linux x64 5.13.0-30-generic
Restricted Mode: Yes

Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstartedc:30421358
vs360:30404995
vsclayoutctrt:30405800
azactmsalcf:30409288
vscop841:30430977
pythonvspyt640:30426300
vscscmwlcmc:30428972

```

</details>

**Comment by pushkine** [comment]
this is a common issue across all languages whenever the indentation level cannot be inferred from delimiter tokens

**Comment by 64kramsystem** [comment]
> this is a common issue across all languages whenever the indentation level cannot be inferred from delimiter tokens

I see. The issue is about moving a line that it's not included in the paste, though (the `def baz`) - I think that's unusual across editors (I've tried a few, and nothing comparable happens).

**Comment by 64kramsystem** [comment]
Other test case follows (this is actually a real-world case). Again, there's no reason to reindent the line after the paste.

Write this block:

```rb
array = [
  "foo",
]
```

Copy this block to the clipboard:

```rb
"bar",
"baz",
```

Move the cursor to the closing bracket, and paste. The paste will cause the closing bracket to be moved:

```rb
array = [
  "foo",
  "bar",
  "baz",
  ]
```

**Comment by rebornix** [comment]
It looks like that the indentation rules for Ruby is not covering this case. Currently the indentation rules for  auto indent feature in VS Code is regex based, which doesn't really understand the scope (function, statement) etc. Formatting works more consistently in this scenario, so I would recommend to enable formatting on type or save. Closing this as we don't expect to get around it in the near future.
