### ISSUE TITLE
Connecting terminal... Error: unable to verify the first certificate with VS Code

### ISSUE THREAD

**Issue by shashibhooshanzade-tomtom** [microsoft/vscode#143544]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.64.2
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1.New version installed for VS code and it starts giving issue "requesting a Cloud Shell...
Connecting terminal...
Error: unable to verify the first certificate"
2.

**Comment by meganrogge** [comment]
Sounds like an extension causing problems. Try running the command `Help: Start Extension Bisect`
