### ISSUE TITLE
Python r string looks weird.

### ISSUE THREAD

**Issue by WiiliamC** [microsoft/vscode#143597]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:
1. Create a python file
2. Type a r string like:
`
folder = r"C:\intel\code"
`
3. The r string looks weird:
![image](https://user-images.githubusercontent.com/48458974/155096510-4efc9c69-921e-4eb8-89bc-05dd736e4f99.png)
Maybe the letters' color should be the same in this case?

I've already disabled all the extensions.
I also tried other themes like One Dark Pro, still the same.

**Comment by alexr00** [comment]
Apparently this is a feature: https://github.com/MagicStack/MagicPython/issues/114#issuecomment-349115524

You can use uppercase `R` to highlight as a raw string.
