### ISSUE TITLE
In APScheduler, exceptions are not raised?

### ISSUE THREAD

**Issue by IavTavares** [microsoft/vscode#143530]
Issue Type: <b>Bug</b>

When using a BlockingSchedule with APScheduler, in vscode, I don't seem to find the correct key combination to throw what in Linux is ctrl+C. I've tried ctrl+Fn+Pause (my keyboard has no break key)

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.40GB free)|
|Process Argv|--crash-reporter-id 4ed69ec5-1dc8-4bce-ae8d-82ac139c5e01|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
ipython|Hoa|2021.10.17
better-cpp-syntax|jef|1.15.13
vscode-docker|ms-|1.19.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.3
jupyter|ms-|2022.1.1301854968
remote-containers|ms-|0.217.4
remote-ssh|ms-|0.74.0
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
vscop841cf:30438916
dsvsc009:30440023
pythonvsnew555cf:30436485
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvid1:30438799
helix:30440343

```

</details>

**Comment by meganrogge** [comment]
Hi, I'm not familiar with what you're trying to do. Could you pls include a gif?
