### ISSUE TITLE
Support installing a mix of pre-release and normal extensions from CLI

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#143540]
At present CLI supports `--pre-release` flag that allows installing pre release version for all passed extensions. It would be useful and efficient to handle installing mix of pre-release and normal extensions in one go. 

Eg: `code --install-extension pub1.name1@prerelease --install-extension pub2.name2`

installs pre release version of `pub1.name1` and normal version of `pub2.name2`

**Comment by sandy081** [comment]
CC @chrmarti

**Comment by chrmarti** [comment]
Thanks @sandy081. I'm updating the regex in the devcontainer.json schema to allow for `@prerelease`.

**Comment by sandy081** [comment]
To verify:

- From CLI, install a mix of prerelease and released extensions. For example: `code-insiders --install-extension GitHub.vscode-pull-request-github@prerelease --install-extension GitHub.remotehub` - this shall install pre-release version of **GitHub.vscode-pull-request-github** extension and normal version of **GitHub.remotehub** extension
