### ISSUE TITLE
Test debugging lazy variables

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#143572]
Refs: #134450

- [x] macOS @weinand 
- [x] linux @JacksonKearl
- [x] windows @connor4312 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23143572%0A%0A&assignees=roblourens)

---

We have changed the debug protocol and VS Code debug UI to allow debug adapters to return a "lazy" variable, which will not have its real value retrieved until the user clicks a button. No "real" debug adapters have implemented this feature yet, so you can test it with the vscode-mock-debug.

- Install the **pre-release** https://marketplace.visualstudio.com/items?itemName=ms-vscode.mock-debug or make sure you have at least 0.49.5
- Open https://github.com/microsoft/vscode-mock-debug/tree/main/sampleWorkspace, debug it, and step through until you reach a variable with "lazy" in its name
- In the variables view, the variable should not have its real value, but a `(...)` button. When you click it, the real value should appear
- Test this variable in all places in the debug UI where a variable appears:
  - Watch, Debug Console, hover: you should see the real value immediately with no button
  - Inline debug values (`debug.inlineValues`): you should see a placeholder value returned by the DA, in mock-debug's case, "lazy var". When expanding the value in the variables view, the inline value should change
- When stepping, an expanded lazy var in the variables view should go back to its unexpanded state with the button

**Comment by weinand** [comment]
@roblourens great stuff! 

I've verified (by changing Mock Debug) that an empty value placeholder prevents an inline value from showing.
