### ISSUE TITLE
Test: Language Detection Improvements

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#143576]
Refs: #137104

- [x] anyOS @TylerLeonhardt 
- [x] anyOS @sbatten (web)
- [x] anyOS @lramos15 (desktop)

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23143576%0A%0A&assignees=JacksonKearl)

---

Improved language detection for small inputs is (finally) out! Context:
- If the existing model can detect the language, it is used
- If not, we try a new model which detects with biasing from recently opened files, files in the workspace, and historically opened files.  

Please test:
- files are able to be detected with less text than before, and ambiguities can be influenced by workspace contents and recently opened. For example:
```
# hello world
- this 
- is
```
can be MD or YAML, so if you have recently opened MD and/or have md files in your workspace, md should be picked, otherwise YAML. Similarly:
```
class Foo {
   private foo: Foo
   constructor() {
      this.foo = ''
   }
}
```
can be CS or TS, and again your recent files should influence this.

- working with very large untitled files doesn't have poor performance
- can go back to old way of detection by disabling `workbench.editor.historyBasedLanguageDetection`

**Comment by sbatten** [comment]
Will test this more tomorrow with the changes from today.

**Comment by TylerLeonhardt** [comment]
Here's a list of good samples to test too.
https://github.com/microsoft/vscode/issues/131450
