### ISSUE TITLE
idea: better tsconfig.json auto fix problems.

### ISSUE THREAD

**Issue by jimmywarting** [microsoft/vscode#143506]
First, thanks for a wonderful vscode, really amazing!

you do a grate job with auto code suggestion fixes and modernization such as convert this function to a es class and so on. I think most of this comes from eslint and auto fix plugins. but this is fairly limited to just only the file you are working in.

I feel like it's missing some quick fix features regarding some of the typescript config. 
I can present two issues with solution i want to see being implemented:

- Cannot find module 'node:fs/promises'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?ts(2792)
- Top-level 'await' expressions are only allowed when the 'module' option is set to 'es2022', 'esnext', 'system', or 'nodenext', and the 'target' option is set to 'es2017' or higher.

it would have been nice if it can solve this issues by modifying the existing tsconfig.json to add eg: moduleResolution option and setting the minimum target, or if no tsconfig exist, then maybe a way of configuring workspace option could work also?

**Comment by mjbvz** [comment]
Can you please file these features [against the  TypeScript project](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

Open a separate feature request for each proposed quick fix so we can judge which ones would be most helpful to people
