### ISSUE TITLE
underscores missing in terminal window

### ISSUE THREAD

**Issue by ucfjimg** [microsoft/vscode#143548]
Issue Type: <b>Bug</b>

Open a terminal window. Type or cat a file that contains underscores in the text. Note that the underscores are missing and display as spaces.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.4.0-94-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 1199)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|62.73GB (19.31GB free)|
|Process Argv|. --crash-reporter-id 5d1a56e1-f1c6-49c0-a9da-9c430d9412bb|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
better-toml|bun|0.3.2
bracket-pair-colorizer-2|Coe|0.2.2
rust-syntax|dus|0.6.0
syntax-highlighter|evg|0.5.0
go|gol|0.27.2
zopeneditor|IBM|1.4.1
rust-doc-viewer|JSc|2.0.1
language-haskell|jus|3.4.0
rust-flash-snippets|lor|1.2.0
rust-analyzer|mat|0.2.834
asm-code-lens|maz|1.9.0
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2022.1.3
jupyter|ms-|2021.8.1054968649
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.70.0
cmake-tools|ms-|1.9.2
cpptools|ms-|1.6.0
veriloghdl|msh|1.5.0
rust-and-friends|nyx|1.0.0
rust-targets|Pol|1.0.1
java|red|1.1.0
synthwave-vscode|Rob|0.1.11
crates|ser|0.5.9
vscode-asl|Tho|1.0.0
cmake|twx|0.0.17
vscode-lldb|vad|1.6.10
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.34.2
markdown-all-in-one|yzh|3.4.0
rust-mod-generator|Zha|1.0.10
vscode-extension-for-zowe|Zow|1.22.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30429732
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30440023
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343
vscaac:30438847

```

</details>

**Comment by gjsjohnmurray** [comment]
Please update to the current release (1.64.2) and re-test.

**Comment by meganrogge** [comment]
already fixed 

/duplicate #130967
