### ISSUE TITLE
Bring back ability to create diagnostic that highlights entire word

### ISSUE THREAD

**Issue by matangover** [microsoft/vscode#143515]
Starting with [this commit](https://github.com/microsoft/vscode/commit/7443621e3b4366b7dabca94b0ba988cf8f47e164), VS Code no longer highlights the entire word if a `Diagnostic` has a zero-length range. It now displays the zero-length range instead. Highlighting the entire word was a documented feature - I have submitted a [PR](https://github.com/microsoft/vscode-docs/pull/5194) to update the docs.

The mypy-vscode extension I wrote relied on this feature, since mypy doesn't output an end column for its diagnostics. Highlighting the word at the position given by mypy was very useful in this case.

As for bringing back the ability to highlight words – instead of specifying a zero-length range, maybe it's cleaner to have a flag on `Diagnostic` such as `highlightEntireWord`.

For now I can work around this by using `getWordRangeAtPosition`, but I need to do this in `onDidOpenTextDocument` which is somewhat clunky.

**Comment by jrieken** [comment]
> For now I can work around this by using getWordRangeAtPosition, but I need to do this in onDidOpenTextDocument which is somewhat clunky.

Yeah, that's undesirable because it can mean you open many documents

**Comment by jrieken** [comment]
@alexdima I not a fan of adding new API flags for this (esp since it used to behave like this) but it could be an internal marker option that is always used by extensions and tasks

**Comment by alexdima** [comment]
I plan to try to bring back the old behavior with the exception on positions that are at the end of a line. Let's track in #142810
