### ISSUE TITLE
Breakpoints should render snippet of code line

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#14351]
Similar to how we show snippets in find references we should also show references in breakpoints pane. code snippet         filename : line number alligned to the right
Code snippet should be shown using a mono space font

**Comment by weinand** [comment]
@isidorn I'm questioning the usefulness of this. In many cases the code of the breakpoint line is not very interesting and does not identify the breakpoint. I would rather show the enclosing function.

**Comment by isidorn** [comment]
@weinand after discussion in the standup I have decided not to show the code snippet. We can leave this open as a feature request and we can see if it generates some interest from users

**Comment by weinand** [comment]
Closing because we are not planning to implement this within the next 12 months.
