### ISSUE TITLE
Deleting folder on vscode's explorer, can't sync a delete status in vscode's scm explorer.

### ISSUE THREAD

**Issue by yubaoquan** [microsoft/vscode#143519]
Issue Type: <b>Bug</b>

1. git init an repo.
2. create a file aaa.txt, input some text in it.
3. create a folder named my-folder
4. create a file bbb.txt with some text in my-folder
5. git commit 
6. delete file aaa.txt
7. delete my-folder

Expect: 
2 changes show in SCM explorer: one is aaa.txt deleted, another is bbb.txt deleted.

Actual:
Only aaa.txt deleted is listed in SCM explorer.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (1.40GB free)|
|Process Argv|--crash-reporter-id 6fed4d11-05dd-470a-b43e-fe5a64d871e2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
spaces-inside-braces|Air|0.4.0
tsl-problem-matcher|amo|0.5.0
better-toml|bun|0.3.2
vscode-clock|Com|0.0.1
vscode-markdownlint|Dav|0.46.0
vscode-eslint|dba|2.2.2
vscode-deno|den|3.10.1
fileheadercomment|doi|0.0.5
gitlens|eam|11.7.0
auto-rename-tag|for|0.1.10
beautify|Hoo|1.5.0
vscode-todo-highlight|jgc|2.0.4
select-highlight-minimap|mde|0.1.0
template-string-converter|meg|0.6.0
vscode-json5|mrm|1.0.0
vetur|oct|0.35.0
advanced-new-file|pat|1.2.2
bracketeer|pus|1.3.1
code-settings-sync|Sha|3.4.3
vscode-stylelint|sty|1.2.2
sass-indented|syl|1.8.19
language-stylus|sys|1.15.0
pdf|tom|1.2.0
sort-lines|Tyr|1.9.1
reg-visualizer|ybq|0.0.1
style-dts|ybq|0.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30438341
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc008:30440022
pythonvspyt640:30436486
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343

```

</details>

**Comment by gjsjohnmurray** [comment]
Please confirm whether or not the problem also happens after you run the command to reload with all extensions disabled.

**Comment by yume-chan** [comment]
Git only tracks files, it doesn't care about folders.

An empty folder is equal to a non-exist folder. If you only delete `bbb.txt` (leaving `my-folder`), commit, push to somewhere like GitHub, the `my-folder` folder will also be gone.

**Comment by yubaoquan** [comment]
> Please confirm whether or not the problem also happens after you run the command to reload with all extensions disabled.

Looks like this issue doesn't happen every time. Now I can't reproduce it in both extensions enabled and disabled mode.

**Comment by yubaoquan** [comment]
> Git only tracks files, it doesn't care about folders.
> 
> An empty folder is equal to a non-exist folder. If you only delete `bbb.txt` (leaving `my-folder`), commit, push to somewhere like GitHub, the `my-folder` folder will also be gone.

I'm not talking about deleting empty folder. I'm deleting a folder with a file in it. Sometimes git doesn't mark files in deleted folder as deleted. Maybe its a bug with git, not vscode.
