### ISSUE TITLE
"Debug: Inline Values" setting should support "on"/"off" instead of true/false

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#143543]
Today the "Debug: Inline Values" setting uses low-level "true" and "false" values (in addition to the more high-level "auto"):

<img width="352" alt="CleanShot 2022-02-21 at 14 31 00@2x" src="https://user-images.githubusercontent.com/1898161/154965234-e4f8726f-4366-473b-bc22-a775c3a78123.png">

I suggest to support (and surface in the UI) "on" and "off" values and only keep the booleans for backward compatibility.

**Comment by hannahcoles** [comment]
Hi! Can I work on this issue?

**Comment by weinand** [comment]
@roblourens I think this is a "good first issue", do you agree?

**Comment by roblourens** [comment]
Yes, I would take a PR for this. Make sure that it's backwards compatible so that if a user has true or false set, that those still work as they did before.
