### ISSUE TITLE
dont select $ in duble click

### ISSUE THREAD

**Issue by sajjadef98** [microsoft/vscode#143570]
Issue Type: <b>Bug</b>

don't select $  ($myvar) in duble click in vscode but in  php storm selected $ but in vscode No. fix that

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.88GB (12.96GB free)|
|Process Argv|--crash-reporter-id 414d9e03-982b-4f35-8c6b-0b9e7d2c95fc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-languagetool|ada|3.8.0
vscode-languagetool-fa|ada|3.8.0
save-typing|akh|0.1.0
vscode-intelephense-client|bme|1.8.1
doxdocgen|csc|1.3.2
rtl-markdown|dal|0.0.10
vscode-html-css|ecm|1.11.0
vue-snippets|hol|1.0.4
better-cpp-syntax|jef|1.15.13
auto-save|mcr|1.0.3
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.217.4
remote-ssh|ms-|0.74.0
remote-ssh-edit|ms-|0.74.0
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
notepadplusplus-keybindings|ms-|1.0.7
vscode-react-native|msj|1.9.1
sqltools|mtx|0.23.0
vetur|oct|0.35.0
laravel5-snippets|one|1.15.0
php-ci|sma|0.4.2
tabnine-vscode|Tab|3.5.26
symfony-vscode|The|1.0.2
cmake|twx|0.0.17
php-debug|xde|1.24.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc008:30440022
pythonvsnew555:30436484
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343

```

</details>

**Comment by babakfp** [comment]
+1
This can be added as a config option for the `.php` files👌

**Comment by ArturoDent** [comment]
```jsonc
"[php]": {
  "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?"
}
```

I removed the `$` from that `wordSeparators` list and it now selects the `$` along with the rest of the word.

**Comment by babakfp** [comment]
> ```js
> ```js
> 
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

Yep, it works.

**Comment by roblourens** [comment]
In the past https://github.com/microsoft/vscode/issues/106860 I had decided to keep it, but maybe we can try changing it in March

**Comment by babakfp** [comment]
Hi
I agree with https://github.com/microsoft/vscode/issues/106860#issuecomment-696148943. a PHP variable (<dollar_symbol><var_name>) is a whole 1 thing. You don't really need to be able to only select the name. I will say that **the best thing to do is to make the whole variable be selectable by default for the new users and for the current users show a popup/alert box and explain to them what is what and ask `yes` or `no` to go on with the current config or change it...**
Thanks👍🌸

**Comment by KapitanOczywisty** [comment]
@roblourens IMO It's better to not touch that. I wonder if it's possible to make that triple click?

> You don't really need to be able to only select the name.

There are cases to do so, for example when you're using named arguments you may want to copy only name, or class properties - which are used as `$this->name`.

**Comment by roblourens** [comment]
I wouldn't change that @KapitanOczywisty - if you double click `name`, you would still only select `name`.

I would probably defer to your judgement here. I am not writing PHP every day, but it seems like `$varName` is one "thing" and would make sense to select it with a double click. Of course users can still configure this in either direction if they don't like the default.

**Comment by roblourens** [comment]
I'm going to leave this alone- users can configure it as needed. Also to me it seems like a common thing to do would be to double click the name to rename a variable, and then you don't want the `$` selected.
