### ISSUE TITLE
Display schemas on sidebar sort of like how Amazon Athena console does for JSON/CSV files

### ISSUE THREAD

**Issue by GoddnessTimothy** [microsoft/vscode#143561]
Please add the ability to display JSON/CSV schemas on the sidebar.  As a reference, please see screenshot below.  Also, add the ability to extract JSON/CSV schemas so that we can compare them.  Example use case:  On S3, we have 3 years of partitioned historical data  (2016-2019) in JSON format.  If we were to run a Glue crawler, there is potential that the crawler will create additional tables and fail to add new partitions.  This is because between 2016 and 2019, there was a chance that the schema changed (added additional column, removed column).  It would be SO MUCH easier to identify where the schema changed by being able to extract the schema for the entire data set and do a comparison.
<img width="1155" alt="athena" src="https://user-images.githubusercontent.com/8746379/155004336-069dbf74-8783-4865-a110-641071f98c77.png">

**Comment by aeschli** [comment]
Sorry, I don't understand what you want VS Code to add? Is it a request for a specific extension?

**Comment by timchan96** [comment]
Hi @aeschli, I am looking for vscode to add two features:
1.  Ability to show structure of CSV/JSON files
2. Extract the structure (DDL) for CSV and JSON files.

**Comment by aeschli** [comment]
With structure, do you mean the outline?
![image](https://user-images.githubusercontent.com/6461412/155226988-02e89b0e-6f70-431f-82d8-98555bffec62.png)

We have an outline for JSON.
For CSV this would have to come from an extension.

Extracting the structure could again come from an extension.
