### ISSUE TITLE
Vs code crashing

### ISSUE THREAD

**Issue by programwithabhi33** [microsoft/vscode#143503]
Issue Type: <b>Bug</b>

My vs code crashing many times,im using the vs code with wsl remote ubuntu

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Connection to 'WSL: Ubuntu' could not be established  Canceled

**Comment by aeschli** [comment]
Can you explain what you mean by crashing? The VS Code window closes? The remote connection cannot be established, or is timing out?

**Comment by programwithabhi33** [comment]
Disconnected. Attempting to reconnect... and cannot reconnect , I forced to close the window and reopen the window
