### ISSUE TITLE
No Extension details

### ISSUE THREAD

**Issue by huyhoang8398** [microsoft/vscode#143577]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
  - Version: 1.64.2
  Commit: f80445acd5a3dadef24aa209168452a3d97cc326
  Date: 2022-02-09T22:02:29.527Z
  Electron: 13.5.2
  Chromium: 91.0.4472.164
  Node.js: 14.16.0
  V8: 9.1.269.39-electron.0
  OS: Linux x64 5.13.0-30-generic
- OS Version: Ubuntu 20.04.3

Steps to Reproduce:

1. Open Vscode
2. Search/open an extension
![image](https://user-images.githubusercontent.com/25379882/155036820-ffe05019-bd08-4e72-b43d-fd21ac098cb6.png)

**Comment by ridlwan17** [comment]
I have similar problem. Is many extension doesn't work ? In my vs code many extension doesn't work.

**Comment by ridlwan17** [comment]
UPDATE.

I'm recently try to restore my vs code version to 1.54, and my vs code working normally. My extenstions is back normally again. I don't know why. But i hope someone fix this problem in the latest version of vs code.

**Comment by sandy081** [comment]
Can you please check if other tabs in the extension are working? Can you also please check if there are any errors in the console `F1 > Developer: Toggle Developer Tools` ?

**Comment by ridlwan17** [comment]
When i click Toggle Developer Tools, nothing happened. I Can't open it in latest version and 1.54.

**Comment by huyhoang8398** [comment]
> Can you please check if other tabs in the extension are working? Can you also please check if there are any errors in the console `F1 > Developer: Toggle Developer Tools` ?

INFO IExtensionHostStarter.start() took 361 ms.
log.ts:313   ERR [Extension Host] (node:23642) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:23642) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `code --trace-deprecation ...` to show where the warning was created)
I @ console.ts:137
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: ENOENT: no such file or directory, open '/home/kn/.config/Code/User/globalStorage/vscodevim.vim/.registers'
I @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: ENOENT: no such file or directory, open '/home/kn/.config/Code/User/globalStorage/vscodevim.vim/.registers'
I @ console.ts:137
log.ts:313   ERR ENOENT: no such file or directory, open '/home/kn/.config/Code/User/globalStorage/vscodevim.vim/.registers': Error: ENOENT: no such file or directory, open '/home/kn/.config/Code/User/globalStorage/vscodevim.vim/.registers'

**Comment by sandy081** [comment]
@ridlwan17 

Can you please check if other tabs in the extension editor are working?

**Comment by ridlwan17** [comment]
> @ridlwan17
> 
> Can you please check if other tabs in the extension editor are working?

My extensions which require new tab is not working like git graph and markdown preview. But extension which not required new tab is still working like code snippet and theme.

**Comment by sandy081** [comment]
> My extensions which require new tab is not working like git graph and markdown preview. But extension which not required new tab is still working like code snippet and theme.

Not sure if I understand. Can you please click on Feature Contributions tab in the following screenshot and let me know if you can see the content. I wanted to know if only Details tab is not working

![image](https://user-images.githubusercontent.com/25379882/155036820-ffe05019-bd08-4e72-b43d-fd21ac098cb6.png)

**Comment by ridlwan17** [comment]
> > My extensions which require new tab is not working like git graph and markdown preview. But extension which not required new tab is still working like code snippet and theme.
> 
> Not sure if I understand. Can you please click on Feature Contributions tab in the following screenshot and let me know if you can see the content. I wanted to know if only Details tab is not working
> 
> ![image](https://user-images.githubusercontent.com/25379882/155036820-ffe05019-bd08-4e72-b43d-fd21ac098cb6.png)
Its the feature contributions tab
![ss-feature-contributions](https://user-images.githubusercontent.com/82127706/155705354-5e506c2b-8366-42be-8661-cfc6d741b9c6.PNG)

**Comment by ridlwan17** [comment]
> > My extensions which require new tab is not working like git graph and markdown preview. But extension which not required new tab is still working like code snippet and theme.
> 
> Not sure if I understand. Can you please click on Feature Contributions tab in the following screenshot and let me know if you can see the content. I wanted to know if only Details tab is not working
> 
> ![image](https://user-images.githubusercontent.com/25379882/155036820-ffe05019-bd08-4e72-b43d-fd21ac098cb6.png)

![ss-feature-contributions](https://user-images.githubusercontent.com/82127706/155705587-3b5688df-1f0a-44b8-accd-3b93eeba60ed.PNG)
It's feature contributions

**Comment by ridlwan17** [comment]
Its my vs code version

Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by ridlwan17** [comment]
Has it been fixed? My vs code extensions working normally again.

**Comment by huyhoang8398** [comment]
it works fine now
