### ISSUE TITLE
[debug] Provide a general setting to configure the default debug console

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#143582]
You can see that more and more debuggers support terminals as program console, and they provide the same `console` option individually in launch configuration. See that 'java', 'python' and 'node' all define the same `console` option in their launch configuration. The `console` option seems to be a common requirement rather than language specific, so it's better to have VS Code provide a general option for it.

Also, it is convenient to have it as a user setting. If a user has a preference for using a specific console, they only need to change the settings.json once, rather than having to modify launch.json repeatedly for each different project.

// cc: @isidorn

**Comment by isidorn** [comment]
Currently Java has introduced their own java setting for this. Which I thought does not really make sense, and we should consider making this into a general vscode setting, so Java could deprecate their own.

**Comment by weinand** [comment]
@testforstephen I understand the feature request, but we are no longer in a position to make `console` a "built-in" VS code property because that would break all extensions that already use `console` but in a slightly different way.
E.g. the C# debugger uses `console` but with more options. And the C++ extension uses `externalConsole` instead of `console` because they cannot support all `console` options.
Dealing with this zoo in a non-breaking way would probably mean to find a new unused property name, agree on a common feature set, and then all extension would have to adopt the new property and migrate the user's debug configurations. IMO this effort is no longer feasible.

**Comment by testforstephen** [comment]
@weinand got it, thanks for your concern. If there are already some extensions that have different implementation for console, then making it a common setting will be a little tricky.

**Comment by weinand** [comment]
@testforstephen even if it is no longer possible to promote the `console` property to become a standard ("built-in") VS code property, we could introduce more "standard" user settings for VS Code's built-in "debug console".

That means every debugger extension that wants to support the debug console will still have to add the `console` property to its schema, but it could automatically profit from the built-in "debug console" settings.

Are there any generally useful user settings for the debug console that you would like to use in the Java extension?

**Comment by testforstephen** [comment]
> That means every debugger extension that wants to support the debug console will still have to add the console property to its schema, but it could automatically profit from the built-in "debug console" settings.

Could you explain more how we can benefit from the built-in "debug console" settings when we have to add the `console` to its schema by ourself?

> Are there any generally useful user settings for the debug console that you would like to use in the Java extension?

On Java extension, we define a user setting `java.debug.settings.console` and also `console` property in launch.json schema. By default, the launch console inherits the value from settings, and user can customize it per debug session via modifying `console` in launch.json. The allowed values for `console` are  ["internalConsole", "integratedTerminal", "externalTerminal"].
