### ISSUE TITLE
Test: Markdown Hovers in Timeline

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#143574]
Refs: #114806

- [x] anyOS @lszomoru
- [x] anyOS @karthiknadig

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23143574%0A%0A&assignees=JacksonKearl)

---

We added support for markdown string hovers to the timeline API, please try out making a timeline providing extension that uses markdown hovers, some good features to test:
- Links 
- Images (svg's?)
- code blocks
- Anything your heart desires

I have some starter code up at: https://github.com/JacksonKearl/vscode-solunar-timeline

**Comment by karthiknadig** [comment]
Tested out links, images, animated SVGs, and code blocks. Works great!
