### ISSUE TITLE
Syntax highlighting for R is too colorful.

### ISSUE THREAD

**Issue by artinmg** [microsoft/vscode#143549]
I'm not sure whether to call this a feature request or a bug, but I see an issue with syntax highlighting for R in VS Code. Look at the following R code snippets from VS Code and Sublime Text:

# VS Code
<img width="460" alt="Screen Shot 2022-02-21 at 10 15 37 AM" src="https://user-images.githubusercontent.com/68201207/154983908-f488cdcf-a61b-4c42-b87e-04c0b81c6839.png">

# Sublime Text
<img width="260" alt="Screen Shot 2022-02-21 at 10 18 42 AM" src="https://user-images.githubusercontent.com/68201207/154983920-ae41a67d-374d-465e-8224-ad91e59b3c75.png">

Since this is a very minimal example it doesn't look so bad, but once you actually start writing code the fact that "normal" R code is styled with the scope "variable.other.r" means the entire screen lights up with colored text, when e.g., "df" and "three" here should really just be black.

My current workaround since most VS Code themes don't take this into account is to add customizations to each theme I use to overwrite the foreground color for "variable.other.r", which is frustrating.

The simplest fix would to fix the scope seen here from "variable.other.r" to just "source.r".

Thanks!

**Comment by aeschli** [comment]
The default light+/dark+ have a spcific color for variables, and `three` and `df` are variables. Consistency is important so I don't think we should add an exception for R.
What about using theme that uses less colors, like the Default Light/Dark?

**Comment by aeschli** [comment]
No plans to make changes to the default+ themes. I recommend using a theme that suits your preferences better.

If you see that the scopes generated by the R grammar could be improved, please file an issue against https://github.com/Ikuyadeu/vscode-R

**Comment by artinmg** [comment]
However this is not the case with, say, Python code: 

<img width="778" alt="Screen Shot 2022-02-22 at 7 23 32 AM" src="https://user-images.githubusercontent.com/68201207/155131806-c485e9b2-26cd-4c7d-8e1f-131158f28dbe.png">

The variable still only has the scope "source.python", and as a result has the generic "source.python" foreground color. Here I'm showing a completely fresh run of VS Code with no extensions and the default theme to show that it has nothing to do with the vscode-R extension or the theme I'm using. It's also why I showed the Sublime Text example for how "df" and "three" would not receive a special scope other than "source.r".

**Comment by aeschli** [comment]
It a good question why the grammar for python does not create any scope for variables name. https://github.com/MagicStack/MagicPython is the place to request that.
The python semantic highlighting later adds that information (you need the python extension for that)

**Comment by artinmg** [comment]
I see what you mean about semantic highlighting. Indeed, I normally have it turned off as I find it distracting for nearly all text in my code to have some coloring or other rather than the default foreground color. And yet, this would be traditionally normal (as you can see from how Sublime Text highlights R code, or non-semantic highlighting VS Code highlights Python code).

Regardless, the point here is that only R seems to have this "variable.other.r" scope as the "default" scope. Compare C, Python, and R, again with no extensions and the default Dark+ theme: 

<img width="757" alt="Screen Shot 2022-02-22 at 8 53 51 AM" src="https://user-images.githubusercontent.com/68201207/155146413-b4560417-dfaa-433a-a20d-72fcfe72a18f.png">
