### ISSUE TITLE
Fullscreen VSCode doesn't allow the taskbar, if set to autohide, to appear in Windows 11

### ISSUE THREAD

**Issue by asampal** [microsoft/vscode#143529]
Issue Type: <b>Bug</b>

In the latest insider's build of VSCode, double-click the titlebar to maximize it. Note that the taskbar, when set to autohide, will no longer appear when VSCode is in this state and the mouse cursor is moved to the bottom edge of the screen.

I think something changed recently as I normally keep my VSCode instance in a maximized state and my taskbar was able to show even if set to auto-hide.

VS Code version: Code - Insiders 1.65.0-insider (a0da9978b10ae0b9307c7f545b50a8500efff7eb, 2022-02-21T05:15:17.930Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (16.65GB free)|
|Process Argv|--crash-reporter-id af1c7f06-1fe5-4a50-bddd-2de5a14c940d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (4 x 4007)|
|Memory (System)|5.80GB (4.63GB free)|
|VM|0%|
</details><details><summary>Extensions (117)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.8.2
project-manager|ale|12.5.0
svelte-intellisense|ard|0.7.1
zls-vscode|Aug|1.0.4
pharo-language-server|bad|1.1.2
spellright|ban|3.0.60
toml|be5|0.6.0
vscode-unison|Ben|0.3.0
emojisense|bie|0.9.0
markdown-checkbox|bie|0.3.2
better-toml|bun|0.3.2
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
codeswing|cod|0.0.21
gitignore|cod|0.7.0
transformer|dak|1.12.0
vscode-deno|den|3.10.1
githistory|don|0.6.19
xml|Dot|2.5.1
arturo|drk|0.3.0
gitlens|eam|11.7.0
vscode-npm-script|eg2|0.3.24
json-tools|eri|1.0.2
magic-racket|evz|0.6.3
vscode-firefox-debug|fir|2.9.6
vscode-svelte-snippets|fiv|0.5.0
code-runner|for|0.11.7
shell-format|fox|7.2.2
kotlin|fwc|0.2.23
godot-tools|gee|1.1.3
copilot|Git|1.7.5067
remotehub|Git|0.24.0
vscode-pull-request-github|Git|0.36.2
go|gol|0.31.1
cloudcode|goo|1.17.0
gc-excelviewer|Gra|4.0.50
terraform|has|2.19.0
vscode-drawio|hed|1.6.4
rest-client|hum|0.24.6
output-colorizer|IBM|0.1.2
figma|ide|0.1.1
r|Iku|2.3.8
Ionide-FAKE|Ion|1.2.3
Ionide-fsharp|Ion|5.11.0
Ionide-Paket|Ion|2.0.0
svelte-vscode|Jam|0.9.3
search-node-modules|jas|1.3.0
plantuml|jeb|2.17.2
vscode-gnupg-tool|JHe|1.3.9
vscode-text-pastry|jkj|1.3.1
vscode-peacock|joh|4.0.0
language-julia-insider|jul|1.5.11
vscode-gutter-preview|kis|0.30.0
nim|kos|0.6.6
node-module-intellisense|lei|1.5.0
rust-analyzer|mat|0.2.940
rainbow-csv|mec|2.0.0
file-downloader|min|1.0.11
vscode-docker|ms-|1.19.0
csharp|ms-|1.24.0
vscode-kubernetes-tools|ms-|1.3.6
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.3
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.222.0
remote-ssh|ms-|0.74.0
remote-ssh-edit|ms-|0.74.0
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.9.2
cpptools|ms-|1.9.0
live-server|ms-|0.2.12
powershell-preview|ms-|2022.2.1
test-adapter-converter|ms-|0.1.5
vsliveshare-pack|ms-|0.4.0
vscode-react-native|msj|1.9.1
gradle-language|nac|0.2.3
vscode-json-editor|nic|0.3.0
text-power-tools|qcz|1.30.0
red|red|0.4.3
java|red|1.3.0
vscode-commons|red|0.0.6
vscode-microprofile|red|0.3.0
vscode-quarkus|red|1.9.0
vscode-yaml|red|1.4.0
shellman|Rem|5.6.0
LiveServer|rit|5.7.4
shebang-snippets|rpi|0.1.4
partial-diff|ryu|1.4.3
scala|sca|0.5.5
scala-snippets|sca|0.1.0
metals|sca|1.12.0
imba|scr|0.5.2
incremental-search|sie|0.2.1
vscode-hexdump|sle|1.8.1
rewrap|stk|1.16.2
imba|tir|0.4.0
pdf|tom|1.2.0
unison-ui|Tom|0.1.0
cmake|twx|0.0.17
vscode-lldb|vad|1.6.10
vscodeintellicode|Vis|1.2.17
vscode-vlang|vla|0.1.11
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.0
vscode-maven|vsc|0.35.0
vscode-icons|vsc|11.10.0
codetour|vsl|0.0.58
gistfs|vsl|0.3.0
gitdoc|vsl|0.0.8
quokka-vscode|Wal|1.0.448
ballerina|wso|3.0.0
local-history|xyz|1.8.1

</details>

**Comment by lllopo** [comment]
Same on Windows 10. Huge pain !!!

**Comment by deepak1556** [comment]
Regressed with https://github.com/microsoft/vscode/issues/143529

Fixed in latest insiders.
