### ISSUE TITLE
Light high contrast: highlight + hover = not enough contrast

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#143536]
Put a cursor on some word a highlight appears = already not enough contrast.
Now hover over it = hardly visible

![Screenshot 2022-02-21 at 11 46 45](https://user-images.githubusercontent.com/1926584/154940230-4aca9622-3d43-4189-98e6-3d54dbb52512.png)

**Comment by daviddossett** [comment]
Thanks! Fixed this + a handful of other editor issues in https://github.com/microsoft/vscode/commit/08b18a259a774a2467ec90a69cdba22478d700fa

**Comment by isidorn** [comment]
Great, then let's add the bug label so I verify this. And add it to this milestone and close 😊
