### ISSUE TITLE
Test: Enhanced TAR downloading

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#143575]
Refs: https://github.com/microsoft/vscode-anycode/issues/9

- [x] anyOS @chrmarti (web, insiders.vscode.dev)
- [x] anyOS @rchiodo (desktop RemoteHub Insiders)

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23143575%0A%0A&assignees=JacksonKearl)

---

Ensure you are on latest build with `remoteHub.indexing.maxIndexSize: 50` by default.

The latest RemoteHub now downloads tar files much more aggressively. By default they will be downloaded on request from either workspace search or AnyCode's indexing, with the only exception being that the request is by default cancelled after 50MB.

Test on a variety of repo sizes (I used microsoft/vscode, microsoft/typescript, and torvalds/linux) and network throttles:

- Search gives good results and respects flags/etc. by default
- AnyCode doesn't make a ton of network requests (check devtools, requests for `tree`'s are expected, but not requests for file contents)
- The notification about downloading the TAR has a good progress indication and supports cancellation.
   - Upon cancelling the request, the code should fall back to API-powered utils, for example search should gracefully fall back to GitHub API powered search when you cancel without needing further interaction. 
   - The search view should also notify you of the cancellation and give a link to retry downloading the index
   - Once you cancel index downloading for a repo, it doesn't attempt to download the index again until you manually opt back in
- `remoteHub.indexing.maxIndexSize`, configures the limit for downloading, try setting to `0`, empty, or a very large number
- `remoteHub.indexing.verboseDownloadNotification`, configures how loud the progress is, make sure that when this is set false you can still cancel long running downloads by clicking the status bar entry then cancelling in the popup.

**Comment by rchiodo** [comment]
@JacksonKearl is there a way to clear the flag that indicates whether or not to download? 

I did this and didn't get what I expected:

1. Opened a repository with more than 50MB of files
2. Went to search
3. Download started
4. Download gave a warning at 50
5. Change maxIndexSize to 1
6. How do I get the warning again?

**Comment by JacksonKearl** [comment]
The `Configure indexing of Repositories` command should give you a picker with those options. Alternatively the `Delte all repository indexes" command will clean you slate too.

**Comment by rchiodo** [comment]
Neither of those seem to work. It never downloads again unless I explicitly click the 'Enable indexing' link.
