### ISSUE TITLE
Incorrect opening bracket color in Rust attributes

### ISSUE THREAD

**Issue by EFanZh** [microsoft/vscode#143518]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: Arch Linux

Steps to Reproduce:

1. Set `editor.bracketPairColorization.enabled` to `true`.
2. Create a Rust source file in Visual Studio Code with the following content:

   ```rust
   #[cfg(test)]
   mod tests {}
   ```
2. Observe the color of `[`.
3. I got the following highlighting result:

   ![](https://user-images.githubusercontent.com/2160692/154881297-7dbc010a-5b68-4043-8231-2a1e3fceb29d.png)

You can see the color of `[` does not match the color of `]`.

**Comment by alexr00** [comment]
I can't reproduce in VS Code insiders. Maybe @hediet has already fixed this?

**Comment by hediet** [comment]
I'm very sure this is due to a rust extension that assigns `[` and `]` different language kinds, thus confusing the bracket colorization.
You can use the inspect token feature to verify that.

**Comment by alexr00** [comment]
I can't reproduce in 1.64.2 either. Token scopes all look good in both. @EFanZh maybe you have an extension installed that is causing this. You can use the [extension bisect feature](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to determine which one if it isn't obvious.

**Comment by EFanZh** [comment]
I started VS Code with `code --disable-extensions`, so I don’t think it is caused by extensions.

@alexr00 Were you trying on Linux? Because I am have this problem on Linux platform.

**Comment by EFanZh** [comment]
I have downloaded the official one from <https://az764295.vo.msecnd.net/stable/f80445acd5a3dadef24aa209168452a3d97cc326/code-stable-x64-1644446282.tar.gz>, and run it with `./code --disable-extensions`:

![](https://user-images.githubusercontent.com/2160692/155514548-b98ef4b8-402a-40a8-a864-58eb0e13215a.png)

The problem persists.

**Comment by EFanZh** [comment]
OK, I think this has something to do with font ligatures.

Try this figuration:

```json
{
    "editor.bracketPairColorization.enabled": true,
    "editor.fontLigatures": true,
    "editor.fontFamily": "Cascadia Code"
}
```

Where Cascadia Code can be found at <https://github.com/microsoft/cascadia-code>.

If I disable font ligatures, the problem goes away.

**Comment by hediet** [comment]
Oh yes, this is a known issue. Missed that in your screenshot.

See #130996.
