### ISSUE TITLE
Copies a strange link when copying code

### ISSUE THREAD

**Issue by lalatech-de** [microsoft/vscode#143511]
Issue Type: <b>Bug</b>

Reproducibility: Once

Reproducing steps:
1. Copy string "uid not found" from file app.js (via CRTL+C)
2. Paste it to "app.spec.js" file (via CRTL+V)

Behavior:

Instead of copying "uid not found" it copies a suspecting link.

Link> !WARNING! it could be a malicius link: https://tei.ai/NJQPpRzy

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
OS version: Linux x64 5.13.0-30-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.67GB (32.63GB free)|
|Process Argv|--unity-launch --crash-reporter-id 12481e75-5bcf-494f-9eb9-c1acd9cc6992|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
vscode-nginx-conf|ahm|0.1.3
angular-schule-extension-pack|ang|0.5.0
ng-template|Ang|13.2.3
angulardoc-vscode|Ang|6.1.3
armview|ben|0.4.6
path-intellisense|chr|2.8.0
vscode-eslint|dba|2.2.2
javascript-ejs-support|Dig|1.3.1
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
elm-ls-vscode|elm|2.4.1
vscode-firefox-debug|fir|2.9.6
vscode-jest-runner|fir|0.4.47
auto-rename-tag|for|0.1.10
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.24.6
volar|joh|0.31.4
vscode-codemetrics|kis|1.24.0
VS-code-vagrantfile|mar|0.0.7
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
azure-pipelines|ms-|1.195.0
vscode-azureappservice|ms-|0.23.0
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.13.0
vscode-azurevirtualmachines|ms-|0.5.0
vscode-bicep|ms-|0.4.1272
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.19.0
vscode-dotnet-runtime|ms-|1.5.0
azure-account|ms-|0.10.0
azurecli|ms-|0.5.0
test-adapter-converter|ms-|0.1.5
vscode-node-azure-pack|ms-|0.2.1
vscode-typescript-tslint-plugin|ms-|1.3.3
azurerm-vscode-tools|msa|0.15.5
angular-console|nrw|17.14.1
vetur|oct|0.35.0
vscode-spring-boot|Piv|1.31.0
material-icon-theme|PKi|4.13.0
vscode-thunder-client|ran|1.12.1
java|red|1.3.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.4.0
rust|rus|0.7.8
vue-vscode-snippets|sdr|3.1.1
mdx|sil|0.1.0
autoimport|ste|1.5.4
better-align|wwm|1.1.6
vscode-mdx-preview|xyc|0.3.3
cursor-align|yo1|1.1.0

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by weinand** [comment]
Before trying "Start Extension Bisect" I suggest that you disable all extensions and then try to reproduce the problem.

**Comment by gjsjohnmurray** [comment]
@weinand my understanding of paragraph 4 at https://code.visualstudio.com/blogs/2021/02/16/extension-bisect#_troubleshoot-faster is that the first thing "Start Extension Bisect" does is disable all extensions. If so, I'm not clear why it's worth doing that explicitly as a fist diagnostic step.
