### ISSUE TITLE
Test: Layout Control Types

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#143581]
Refs:  #137633

- [ ] anyOS @mjbvz
- [x] anyOS @rebornix
- [x] anyOS @jrieken

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23143581%0A%0A&assignees=sbatten)

---

**Context**
The layout control is visible in the top right of the window when the title bar style is custom. It is enabled by default in insiders and controlled via `workbench.experimental.layoutControl.enabled`.

Due to feedback that the layout control menu in the title bar is too many clicks, we experiment with new options. Please try out the new experimental setting `workbench.experimental.layoutControl.type`.

**Comment by rebornix** [comment]
The new layout buttons and quick pick help with discoverability and I enjoy using them. Good work!

**Comment by mjbvz** [comment]
Main issues I ran into was getting the layout control to show up in the first place due to having nativeFullScreen disabled #143820 and clicking on the configure layout button sometimes doing nothing #143826

Also opened a few issues for the layout control itself
