### ISSUE TITLE
Invisible Notebook cellls

### ISSUE THREAD

**Issue by capem** [microsoft/vscode#143551]
Some Notebook cells are invisible and cells borders are intermingled.
See attached gif.

Does this issue occur when all extensions are disabled?: Yes/No (Still investigating since issue appears randomly )

- VS Code Version: 1.64.2
- OS Version: 21H2 (build 22000.493)

Steps to Reproduce: Can't reproduce ,bug appears randomly throughout the last couple of months.
![Animation](https://user-images.githubusercontent.com/49783022/154985137-f920f731-ee18-4f49-862e-96338d513c0b.gif)

**Comment by rebornix** [comment]
I think this is already fixed by @mjbvz

**Comment by capem** [comment]
Not solved yet, even in Insiders.
