### ISSUE TITLE
Stop recommending Vetur for Vue v3+

### ISSUE THREAD

**Issue by zigomir** [microsoft/vscode#143531]
Since Vue.js version 3, [new recommended extension](https://vuejs.org/guide/scaling-up/tooling.html#ide-support) has been [Volar](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar).

It would be great if VSCode could take this into account and stop recommending `Vetur` in Vue 3 projects.

**Comment by isidorn** [comment]
@zigomir thanks for filling this!
Currently we recommend based on `.vue` file type. So we do not really know what vue.js version is used.
Do you have some info how wide is version 3 adopted? 
Would it be ok to recommend Volar extension for all Vue users?

Sorry but I do not use vue thus all the questions....

fyi @sandy081 @octref @hediet

**Comment by zigomir** [comment]
I see. I don't have the info, but if I had to guess, v2 is still used more than v3.

About recommending Volar for Vue 2 (great question), it doesn't seem to be working out of the box [based on the docs](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar) (look for Setup for Vue 2 details). I never used Volar and Vue 2 so am not best person to say. /cc @johnsoncodehk 

I guess I hoped VSC knows what version of Vue is being used, but if not, then maybe it's too soon to change this 🤷‍♂️ and am sorry to waste anyone's time 😊

**Comment by isidorn** [comment]
Then I suggest that we only update this recommendation in the future once v3 becomes more popular than v2.
Currently it would be weird for users using v2 to get an extension recommendation which does not work.

I am open for suggestions from the community here.

**Comment by isidorn** [comment]
We have decided to start recommending Volar instead of Vetur starting in April for insiders. Which means May for VS Code stable.
That should hopefully give more time for the vue community to transition to v3.

fyi @octref @johnsoncodehk

**Comment by isidorn** [comment]
This has been done, and you can try it out with VS Code insiders from Thursday. Let's see how it goes.
