### ISSUE TITLE
Cannot launch web extension using basic 'yo code' steps

### ISSUE THREAD

**Issue by m-paternostro** [microsoft/vscode#143614]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2 (Universal) Commit: f80445acd5a3dadef24aa209168452a3d97cc326
- OS Version: Mac OS Monterey 12.2.1 (21D62)
- Chromium Version (launched by VSCode): 94.0.4595.0 (Developer Build)
- Chrome Version (available on machine): 98.0.4758.102 (Official Build) 

Steps to Reproduce:

1. Create a web extension using the recommended steps
    - yo code
    - New Web Extension
    - Any name
    - Accept all defaults
    - npm
    - Open with code
   
2. In VSCode, launch with "Run Web Extension"
    - *Result:* a desktop instance is launched
   
3. On the terminal, run `npm run run-in-browser`
    - *Result:* after downloading and unpacking the VS Code Insiders, Chromium on port 3000 shows up but the page is blank. Looking at the Console View of the Developer Tools, there are 71 errors and 13 warnings. Here's the first few lines of the terminal's output

```
❯ npm run run-in-browser

> webexttest@0.0.1 run-in-browser
> vscode-test-web --browserType=chromium --extensionDevelopmentPath=. .

@vscode/test-web: 0.0.15
(node:46699) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Downloading VS Code Insiders: complete
Unpacking VS Code Insiders: complete
Serving dev extensions from /Users/mpaternostro/tmp/webexttest
Serving local content /Users/mpaternostro/tmp/webexttest at /static/mount
Listening on http://localhost:3000
GET / 200 12.194 ms - 2803
GET /static/build/out/vs/workbench/workbench.web.api.css 404 9.668 ms - 9
GET /static/build/out/vs/workbench/workbench.web.api.nls.js 404 6.924 ms - 9
GET /static/build/out/vs/workbench/workbench.web.api.js 404 7.258 ms - 9
GET /static/build/out/vs/loader.js 200 11.105 ms - 38927
GET /static/build/out/vs/code/browser/workbench/workbench.js 200 10.960 ms - 8104
GET /static/build/out/vs/webPackagePaths.js 200 13.466 ms - 715
GET /static/build/out/vs/workbench/workbench.web.api.nls.js 404 2.525 ms - 9
GET /static/build/out/vs/workbench/workbench.web.api.js 404 1.396 ms - 9
GET /static/build/out/vs/base/browser/browser.js 404 13.106 ms - 9
GET /static/build/out/vs/base/common/cancellation.js 404 11.770 ms - 9
GET /static/build/out/vs/base/common/marshalling.js 404 9.156 ms - 9
GET /static/build/out/vs/base/common/lifecycle.js 404 7.764 ms - 9
GET /static/build/out/vs/base/common/network.js 404 8.582 ms - 9
...
```

**Comment by aeschli** [comment]
2. is expected. Web extension can also run on the desktop. See https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension-in-vs-code-running-on-desktop

3. Please update the dev dependency `@vscode/test-web` to the latest: `"@vscode/test-web": "^0.0.22",`

(I'm updating the generator)

**Comment by m-paternostro** [comment]
Thank you for the quick reply and for all the amazing work you guys are doing on both VSCode and TypeScript.

2. A suggestion if I may: for my web extension I have actually created two launchers ("Run Desktop" and "Run Web") because some people are not too comfortable with npm.

3. It works!!!

**Comment by m-paternostro** [comment]
If creating two launchers is not ideal for the sample, perhaps renaming the existing one to "Run on Desktop"...

**Comment by aeschli** [comment]
@m-paternostro Our debugging currently only works when running on the desktop. That's why we only have that as launch config.
