### ISSUE TITLE
Test drag and drop of problems and matches in problems and search view

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#143608]
Refs:  #142508

- [x] anyOS @tanhakabir 
- [x] anyOS @weinand

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23143608%0A%0A&assignees=sandy081)

---

- Generate some problems
- Test drag and drop the problem entry (not the file resource) in to the editor is working as expected
- Generate some search results
- Test drag and drop the search match (not the file resource) in to the editor is working as expected

**Comment by sandy081** [comment]
@weinand Do you mind testing this again given that @bpasero changed some underlying implementation?

**Comment by weinand** [comment]
@sandy081 sure, will do

**Comment by weinand** [comment]
I've retested - one finding: https://github.com/microsoft/vscode/issues/143686#issuecomment-1049732006
