### ISSUE TITLE
Stop OUTPUT panel from popping up

### ISSUE THREAD

**Issue by brmassa** [microsoft/vscode#143657]
Similar to #33262. Extensions dev decide to focus a certain output and the bottom panel simply shows up.

Examples:
* C# extensions gives "Installing C# dependencies..." EVERY time I open vscode. 
* Gitlab extension also pop a message when the remote is not pointing to a Gitlab repository.

But it's not the extension fault. We need a user toggle to disable this behavior altogether.

[EDIT]
Hiding the tab does not work! I disabled it, hiding, but once I reopen vscode (or it triggers the extension output), it REOPENS IT!

**Comment by gjsjohnmurray** [comment]
Why do you think this is not the extensions' fault? They are deciding to specify that this should happen.

**Comment by brmassa** [comment]
4 reasons:

1* the same reason browsers do not allow js create pop ups anymore or Android/iOS let you manage notifications... devs abuse. 
2* I did HIDE the output tab in the panel. Therefore, I'm expecting VSCode ignore any pop up event. The same if I hide any other element of the UI, like the status bar.
3* if I am working in the terminal tab, it switches to the output tab! Holy!
4* extensions being able to force display an output window is in feature-or-bug threshold at best.

so I propose 2 solutions:
1* ignore such behavior if the tab/panel is hidden (partial solution)
2* a global/user/workspace/extension flag disallowing ANY automatically output display, regardless the extension own implementation

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/105270
