### ISSUE TITLE
Enabling shell integration requires terminal restart

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#143687]
Testing #143430

Have a terminal, enable `terminal.integrated.shellIntegration.enabled`
In order for this setting to be picked up a new terminal session needs to be started.
It would be a nicer user experience if the current session (if not busy) would auto restart and apply the setting. Or at least offer to restart. 

If none of that is possible at least the setting description should mention this.

**Comment by Tyriar** [comment]
I mentioned how it's applied on terminal creation in the setting. Auto restarting is too destructive imo, we do have a mechanism to automatically restart _some_ shells safely but if we did that only it would be inconsistent. The safest approach is to just mention it in the config.
