### ISSUE TITLE
Use a real button for lazy variables

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#143602]
Testing #143572 

Currently the string `(...)` is used to indicate that a variables is "lazy" and that an additional click is required to retrieve the variable's value:

<img width="362" alt="CleanShot 2022-02-22 at 11 49 53@2x" src="https://user-images.githubusercontent.com/1898161/155117533-cbb91cb4-c5c7-4fc6-a397-be2f5c11e9ea.png">

To make more obvious that the `(...)` is not a value but an interaction element, I propose to use a button:

<img width="321" alt="CleanShot 2022-02-21 at 12 38 04@2x" src="https://user-images.githubusercontent.com/1898161/155118443-cae3e041-54c6-4fc9-a0a8-b21d536634de.png">

@misolori what do you think?

**Comment by misolori** [comment]
+1 to using a more obvious button, though we do use the `...` for expanding selection in folded regions and folded notebook cells

<img width="417" alt="CleanShot 2022-02-22 at 09 53 37@2x" src="https://user-images.githubusercontent.com/35271042/155190659-a9d6f6b0-0638-4565-9264-3b8544acfa33.png">

**Comment by roblourens** [comment]
I could easily use that type of button, but I'm worried that it wouldn't be more obvious as a button since it doesn't have a background color except on hover, and in this view we already use `...` when text overflows

**Comment by weinand** [comment]
I'm fine with this kind of button as long as the background color is always shown.
<img width="417" alt="CleanShot 2022-02-22 at 09 53 37@2x" src="https://user-images.githubusercontent.com/35271042/155190659-a9d6f6b0-0638-4565-9264-3b8544acfa33.png">
Without the background color it just looks like the ellipsis we use in text overflows.

**Comment by weinand** [comment]
yes, that's the reason why I proposed the button: to increase discoverability
if the three dots look like a text overflow ellipsis '...' or the random string `(...)`, users won't hover over it because they are not expecting an action.

But I'm not insisting on the button...
@misolori could you please decide what to do here?

**Comment by misolori** [comment]
If we decide to go with a button, I'd say we use our common icon buttons that have the hover feedback so that it's consistent:

https://user-images.githubusercontent.com/35271042/155575791-8df0b0f1-d2c1-4a85-b0d5-d68b3271ca84.mp4

**Comment by weinand** [comment]
@misolori yep, makes sense: if the button neither looks like an ellipsis nor like some random text, then it will work and users will be curious to hover over or click on it.

**Comment by roblourens** [comment]
I'm not crazy about that icon. We just replaced it in notebooks with the `...`

**Comment by weinand** [comment]
I'm not a fan of **that** icon, but I like the fact that it is an icon and not some random text.

**Comment by roblourens** [comment]
I'm also not sure about that icon which looks like "refresh"/"reload". @connor4312 suggested an eye, which I don't hate

![image](https://user-images.githubusercontent.com/323878/163283713-7690fea4-ec5f-4fa6-9ae0-4eabacfc0ef4.png)

Although with no context, I wonder whether the codicon looks enough like an eye

**Comment by roblourens** [comment]
There is also the "expand"

![image](https://user-images.githubusercontent.com/323878/163284333-7a5ca050-1243-489d-8a6e-2f7a422edc30.png)

**Comment by weinand** [comment]
I like the concept of an "eye" but not the [octicon suggested](https://github.com/microsoft/vscode/issues/143602#issuecomment-1098559144) above.

This eye would work for me:
![CleanShot 2022-04-14 at 10 19 01](https://user-images.githubusercontent.com/1898161/163344098-9506d7e0-8340-40ee-8d27-665670fdae4e.png)

from https://primer.style/octicons/eye-24

**Comment by roblourens** [comment]
@misolori do you think it's worth taking another look at the shape of the eye codicon?

**Comment by misolori** [comment]
I can adjust the eyes to be a bit wider, the Fluent icon library (which is what ours are based on) also has updated versions that we can try:

![image](https://user-images.githubusercontent.com/35271042/163883036-2cd5196a-59cd-48d7-86e8-93210d92c57a.png)

**Comment by weinand** [comment]
The new icon actually looks more like an eye because the distance between the pupil and the eyebrow is smaller.
Let's go for it.

**Comment by misolori** [comment]
Eye has been updated:

<img width="146" alt="CleanShot 2022-04-19 at 08 35 26@2x" src="https://user-images.githubusercontent.com/35271042/164041508-048b09dc-e604-4f83-9874-c60319eb3979.png">

**Comment by roblourens** [comment]
I strongly prefer the new version, thanks @misolori!

**Comment by capegreg** [comment]
illuminati symbol? This was a terrible and unnecessary change. The ellipse was a better lazy variable indicator, it made scrolling through a list of nodes or elements easier than this weird-looking eye. At least allow a setting to choose preference.

**Comment by capegreg** [comment]
> If we decide to go with a button, I'd say we use our common icon buttons that have the hover feedback so that it's consistent:
> 
>  CleanShot.2022-02-24.at.09.25.11.mp4

Why did you think VSCode needed this. Such a mistake!
