### ISSUE TITLE
Preserve `disable-extensions` argument when changing folders in extension development host

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#143601]
1. Clone the https://github.com/microsoft/vscode-extension-samples repository
2. Open the `helloworld-sample` folder in VS Code Insiders
3. Open `launch.json` and add the following argument: `"--disable-extensions"`
4. Press `F5` which will start the extension development host with all extensions disabled
5. Open a folder in the extension development host

Expected behaviour:
All extensions are still disabled

Actual behaviour:
The `"--disable-extensions"` is dropped

**Comment by bpasero** [comment]
I think all that is needed is another entry here:

https://github.com/microsoft/vscode/blob/dafc40bca5439520d7e8b1c4a5c15c744bf69c10/src/vs/platform/windows/electron-main/window.ts#L830-L837

**Comment by lszomoru** [comment]
Could we also add `--extensionDevelopmentKind` to the list as that would help with web extension development. Thanks!

**Comment by bpasero** [comment]
Looks like it was explicitly decided to not preserve it: https://github.com/microsoft/vscode/pull/48978

Let's keep it open as feature request, maybe others have input as well.

**Comment by lszomoru** [comment]
@bpasero, if I understand the pull request that was linked, the conversation was related to the `--disable-extensions` flag in general. This particular request is about maintaining flags like `--disable-extensions` and `--extensionDevelopmentKind` in the extension development host specifically.

**Comment by bpasero** [comment]
👍

**Comment by heysujal** [comment]
Hi @bpasero  , I want to contribute by fixing this issue . Can you guide me on how to do that?
