### ISSUE TITLE
Layout picker doesn't show keybinding

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#143669]
Testing #143581

* F1 > Customize Layout 
* Some of the entries have keybindinding with the same effect, like `cmd+b` to show/hide the side bar, `cmd+j` for the panel, or `cmd+k z` for zen mode
* The corresponding commands should show those keybinding so that I can learn how to achieve my goal faster

**Comment by bpasero** [comment]
This can be easily done:

<img width="633" alt="image" src="https://github.com/microsoft/vscode/assets/900690/7be301e7-9925-4b34-9207-f5898c4b9be0">

PR: https://github.com/microsoft/vscode/pull/199512

**Comment by bpasero** [comment]
**Verification:**
* open the layout picker ("Customize Layout")
* verify some of the entries show their keybindings
