### ISSUE TITLE
Unselect JSON/YAML Schema

### ISSUE THREAD

**Issue by mechaot** [microsoft/vscode#143621]
When syntax-highlighting YAML-Files one can select a "schema" in the light-blue lower pane of VS Code. VS Code starts out with "No JSON Schema" but once a schema has been selected one cannot go back to "No JSON Schema". No such entry does appear in the "Select JSON Schema"-list, nor any icon indicating "unselect all schema". Thus, if one has a "custom data yaml file" without a provided schema it'll stay red-flagged forever which is not deal-breaker but somewhat annoying.

![image](https://user-images.githubusercontent.com/34485446/155150325-82d21053-125d-457b-a7cf-372111e97ee3.png)

**Comment by aeschli** [comment]
You need to file this issue against the yaml extension: https://github.com/redhat-developer/vscode-yaml/issues
