### ISSUE TITLE
Not enough spacing between first item in TOC and User/Workspace tabs

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#143692]
Testing #143138

The top item looks like it should have more spacing:
![image](https://user-images.githubusercontent.com/1704059/155302871-28656577-4396-4580-8f49-39e328268a39.png)

In comparison, this is how it looks in stable:
![image](https://user-images.githubusercontent.com/1704059/155302967-45cb1198-f83a-4ba8-8669-369c709de589.png)

**Comment by rzhao271** [comment]
Closing in favour of https://github.com/microsoft/vscode/issues/143771
