### ISSUE TITLE
View is reported hidden but is visible

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#143625]
Finally found steps for a bug which I've seen for quite a while.

1. Have Settings Sync enabled
1. Hide both Outline and Timeline from the explorer view container, make sure only the Folders is visible there.

Then, in https://vscode.dev:

3. Reset user data
3. Open a repo like https://vscode.dev/github/microsoft/vscode, accept GH auth
4. Enable Settings Sync

🐛 Timeline view appears visible, but context menu says it should be hidden.

<img width="268" alt="image" src="https://user-images.githubusercontent.com/22350/155166447-700f75fc-4c10-494e-95d2-282225f89453.png">

cc @bpasero

**Comment by sbatten** [comment]
@joaomoreno is the local instance workspace important?

**Comment by joaomoreno** [comment]
That's just what I used to hide the Open Editors and Timeline views... but I guess not. I guess all you need is Settings Sync to remember that state.

**Comment by sandy081** [comment]
Not similar. This has a different root cause and repro steps. Only similarity is that Settings Sync will help in reproducing this bug.

**Comment by sandy081** [comment]
To verify:

* setup new machine, hide Timeline and Outline views in explorer. Turn on Settings Sync
* setup new browser (private mode - Turn on Settings Sync
* 🐛 Timeline view is visible but in the context menu it shows unchecked

<img width="597" alt="Screenshot 2022-03-09 at 15 55 41" src="https://user-images.githubusercontent.com/1794099/157469610-a9a1d3f8-9bd1-4c8f-8401-0e08aaca9492.png">
