### ISSUE TITLE
Task lists (also referred to as checklists and todo lists) is not working 

### ISSUE THREAD

**Issue by bgajjela** [microsoft/vscode#143634]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.59.1
- OS Version:Darwin x64 20.6.0

Steps to Reproduce:

1.Create a task list in a README.md file
2.Check in preview mode if its working or not

**Comment by gjsjohnmurray** [comment]
/duplicate

For instance, see #138845
