### ISSUE TITLE
shellIntegration not load .zshrc

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#143629]
Does this issue occur when all extensions are disabled?: Yes/No
Yes.

- VS Code Version: 1.65.0-insider
- OS Version: MacOS12.2.2

Steps to Reproduce:

1.enable with setting `"terminal.integrated.shellIntegration.enabled": true`
2.open new terminal

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/155169893-9d314c26-8e1b-453c-8c7e-669f0d45cfef.png">

**Comment by meganrogge** [comment]
Thanks, we're aware of this issue and have been working toward its resolution
