### ISSUE TITLE
Titlebar text color is transparent when switching to HC light theme

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#143650]
Testing #143425

<img width="923" alt="image" src="https://user-images.githubusercontent.com/35271042/155226947-3352d4a1-a817-4f9d-8103-8b8808ed299d.png">

1. start with default theme
2. change to HC light theme
3. :bug: title bar text is not visible

It appears that if I reload or make any changes in my settings.json the theme gets updated so I'm wondering if this has to do with our themeing service cc @aeschli

**Comment by daviddossett** [comment]
Hmm. I did notice this and pushed a fix the other day. Wonder why you're still seeing this now. Will look into it.

<img width="653" alt="CleanShot 2022-02-22 at 14 38 44@2x" src="https://user-
images.githubusercontent.com/25163139/155231483-60a243d0-134d-44a8-9e0b-2a9e98bbca5f.png">

**Comment by daviddossett** [comment]
```
"titleBar.activeBackground": "#ffffff",
"titleBar.inactiveForeground": "#292929",
"titleBar.inactiveBackground": "#ffffff",
"titleBar.activeForeground": "#292929",
```

Does this match what you're seeing if you generate the theme?

**Comment by misolori** [comment]
Yea those are the same colors, they also appear after a reload which makes me wonder if this isn't related to your theme specifically (but also can't repro on others). Also noticed that the terminal does the same thing:

<img width="546" alt="CleanShot 2022-02-22 at 14 42 24@2x" src="https://user-images.githubusercontent.com/35271042/155231937-ced119e4-ce32-4ae9-a32e-4d57196a9d53.png">

**Comment by misolori** [comment]
Oh you know what, I was using the old vsix extension and not the built-in one and see this fixed. Sorry for the noise!

**Comment by daviddossett** [comment]
Not a problem! I suspected it was something like that 🙏
