### ISSUE TITLE
Extension tree hover keybinding fails to bring focus back to tree

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#143698]
Testing #143547

Tested in Linux

1. Trigger the keyboard shortcut to open the popup
2. Press any key

🐛 Focus is gone from the tree, so I can't navigate to another tree item

**Comment by alexr00** [comment]
This is a known issue. We will need to make a change to the hover service to support this.

**Comment by benibenj** [comment]
This has been fixed a couple milestones back
