### ISSUE TITLE
Layout control should invoke customize layout

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#143668]
Testing #143581

* select the layout controller
* it opens context menu
* select "Customize Layout"
* it opens a similar, but more powerful menu

I don't believe that the three "Show" actions are used that frequently to justify a special in-between step. Jumping right into the customize layout control would be much faster

<img width="1122" alt="Screen Shot 2022-02-23 at 09 22 55" src="https://user-images.githubusercontent.com/1794099/155283476-43869393-5a8c-4dbf-892e-fa3b0a492215.png">

**Comment by daviddossett** [comment]
This now behaves as described, correct? 

![CleanShot 2022-12-06 at 11 31 18](https://user-images.githubusercontent.com/25163139/206005235-eb9c034b-6caa-458a-8a5a-747cb1f0ecdb.gif)
