### ISSUE TITLE
Markers introduce editors with `query` and `fragment` URIs

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#143686]
Testing #143608

- open a TypeScript file and create a syntax error
- activate problems view
- drag and drop problem from problem view into editor area

Observe: a second editor is opened for the file

- drag and drop problem again from problem view into editor area

Observe: no additional editor is opened for the file

![CleanShot 2022-02-23 at 11 29 28](https://user-images.githubusercontent.com/1898161/155302054-19998605-3aa2-4b50-bd96-75069fe66389.gif)

I do not see a reason why the file is opened in an additional editor on first drag-and-drop

BTW, wenn dragging a file from the Finder (outside of VS Code) into the editor area (where the file is already open), no additional editor is opened.

I'm seeing the same problem with the Search view.

**Comment by sandy081** [comment]
I suspect this is because the marker resource has location information in the URI. Probably workbench editor is treating URIs with and without location as different resource.

Since Drop is handled by the editor assigning to @bpasero

**Comment by bpasero** [comment]
We cannot introduce URIs like that for opening editors. Please do not add `query` or `fragment`. For example, here we remove fragment before passing to editor service, so maybe we miss a place:

https://github.com/microsoft/vscode/blob/f08ebcee85b83b886a27331dfa7f458e2ae251f2/src/vs/editor/browser/services/openerService.ts#L67

**Comment by bpasero** [comment]
With this fix I believe the feature needs to be tested again from scratch because editors now use the proper URI but still should apply the selection.

**Comment by weinand** [comment]
@sandy081 I've verified that no new editors are opened when drag-and-dropping problems or search results.
But when drag-and-dropping search results the editor is scrolled to the corresponding line.
This is not done for problem markers.

**Comment by weinand** [comment]
I've retested this - one finding: https://github.com/microsoft/vscode/issues/143686#issuecomment-1049732006

**Comment by sandy081** [comment]
Thanks @weinand for reporting above issue - I filed separate issue for this  - https://github.com/microsoft/vscode/issues/143878
