### ISSUE TITLE
Test creating an output channel with language id

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#143612]
Refs: https://github.com/microsoft/vscode/issues/19561

- [x] anyOS @rzhao271
- [x] anyOS @chrmarti

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23143612%0A%0A&assignees=sandy081)

---

There is a new API proposal to create an output channel with language id. The proposal is at https://github.com/microsoft/vscode/blob/1ecb5f53a739dd84c66b51e2be1ea7f440141db7/src/vscode-dts/vscode.proposed.outputChannelLanguage.d.ts. 

Please make sure that you can create an output channel by passing any language id (say `typescript`) and content in that output channel is colored according to the passed language.

**Comment by rzhao271** [comment]
I'm wondering which language IDs are supported for that API?
I tried using `bash` and `sh` but didn't see any highlighting happen. I'm on Windows.

**Comment by sandy081** [comment]
> I'm wondering which language IDs are supported for that API?

Its open and it is up to extension creating the channel. Extension can have its own custom language specific for the output channel they create.
