### ISSUE TITLE
Terminal will not open in the main panel

### ISSUE THREAD

**Issue by liborty** [microsoft/vscode#143658]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.2
- OS Version: Linux

Steps to Reproduce:

1. ctrl ^ ~
2. terminal opens in new 'side panel' instead of the main panel
3. terminal can not be dragged or otherwise moved to the main panel on the left
4. nor are there any terminal settings to enable this, what used to be common functionality

**Comment by ArturoDent** [comment]
You could try the `View: Reset View Locations` setting. 

You are not able to drag the little icon at the top left of the Side Panel representing the terminal?  It works for me.

**Comment by liborty** [comment]
No but after hours of research, I managed to discover amongst the commands lists "move views from side panel to panel" which seems to have restored some kind of normality, so you can close this issue if you like, thanks.

I still consider this extremely user unfriendly though, as there does not seem to be any way of doing it easily and directly.

**Comment by liborty** [comment]
P.S. I have tried dragging just about everything at the top of the Side Panel with no luck, before I created this issue. Maybe I just missed that particular little icon or maybe it does not work unless the main panel is already opened, I do not know.
