### ISSUE TITLE
Variables view and watch view are not in sync

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#14365]
Testing #14305 (Might not be related)
- VSCode Version: Latest Insiders
- OS Version: Mac OS

Steps to Reproduce:
1. Create a snippet that contains an Object. Say:

```
let myObject = {
  a: 1
  b: 2
  c: 3
}
....
```
1. Put a break point after array definition. Start debugging 
2. Watch `myObject` variable
3. After break point is hit, change value of any property of myObject

Expected:
`myObject` values should be same in Variables and Watch view

**Comment by isidorn** [comment]
October to investigate

**Comment by isidorn** [comment]
This is basically a duplicate of https://github.com/Microsoft/vscode/issues/2399
However there is an issue in node-debug that it is given stale variables for a variables request. Do the exactly like in @sandy081 steps however do not expand the `myObject` in variables view until you have changed a value of `myObject.a` inside the repl. Only then expand the `myObject` -> notice the `myObject.a` is stale - which is a proof that node debug is giving stale variables.

Thus assigning this to @weinand 
And #2399 captures the issue on vscode side that vscode should always request new variables on each evaluation

**Comment by weinand** [comment]
No longer an issue in node-debug2
