### ISSUE TITLE
Scrolling is too fast

### ISSUE THREAD

**Issue by amansk0307** [microsoft/vscode#143633]
Hello there, 
I am using a Lenovo laptop, that has Elan touchpad driver.
everything works fine but, in VSCode the **scrolling is too fast**. It goes right to the bottom by a single scroll. My mouse sensitivity is set to 0.002% still having the same problem.....
Please help me with this.

**Comment by alexdima** [comment]
You can try configuring `"editor.mouseWheelScrollSensitivity"` and `"workbench.list.mouseWheelScrollSensitivity"`.

**Comment by amansk0307** [comment]
I did try those...
And it worked....
But it's not working on Jupyter extension...

**Comment by alexdima** [comment]
> But it's not working on Jupyter extension...

cc @rebornix . Not sure what would be best here, to eventually add a new setting specific for notebooks, to simply respect the editor setting, or to introduce a global setting that would affect all scrollbars...

**Comment by amansk0307** [comment]
I would like to have a dedicated option for notebooks, and a global feature that affects all scrollbars including notebooks....
Maybe I'm just greedy 😅
