### ISSUE TITLE
Multiple cursors can lead to accidental edits

### ISSUE THREAD

**Issue by madprops** [microsoft/vscode#143664]
- VS Code Version: 1.64.2
- OS Version: Linux

If you have multiple cursors selected, but you're not actually aware of that, and then go editing some line, you end up editing multiple lines in the wrong places which leads to catastrophe!

I'm thinking there should be a way to be really sure that you're multi-cursor editing. Some sort of visual warning (with the cursor count perhaps) that appears until you exit multi-cursor mode.

**Comment by alexdima** [comment]
When having multiple cursors, this is shown in the following areas:
* status bar: 
 > <img width="115" alt="image" src="https://user-images.githubusercontent.com/5047891/155282618-3b7cb9cb-92e3-4341-9fad-6c031bdcf657.png">
* overview ruler:
> <img width="34" alt="image" src="https://user-images.githubusercontent.com/5047891/155282657-dbbd3187-0448-4899-93ac-c29cbb7f5dcb.png">
* in the editor itself:
> <img width="246" alt="image" src="https://user-images.githubusercontent.com/5047891/155282747-7a0df4c3-619b-456a-b3c5-09309f64f642.png">
