### ISSUE TITLE
Move nested files when location of parent file is changed

### ISSUE THREAD

**Issue by davidgabrichidze** [microsoft/vscode#143632]
Wouldn't it be more UX-friendly if nested files will move with the parent one when I change the location of the parent file?
(e.g., drag and drop, or copy-paste).

It would be the same experience when I change the folder's location, including its content.

**Comment by JacksonKearl** [comment]
Makes good sense. Delete should perhaps also work this way, though that's more debatable.

**Comment by JacksonKearl** [comment]
setting `explorer.experimental.fileNesting.operateAsGroup` will enable this
