### ISSUE TITLE
Terminal: run recent command - why does it matter how long ago the command was run

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#143696]
Testing #143430

The commands are already sorted by timestamp. I do not understand what is the benefit of rendering the exact time when the command was run. We do not do this in other places (like recent folders, recent commands in debug console, recent search terms in search etc).

imho it only brings noise to the quick pick items. Sorting by time is enough.

![Screenshot 2022-02-23 at 11 43 42](https://user-images.githubusercontent.com/1926584/155304203-d96eee6e-c7f2-4994-8d21-46c7e25a374d.png)

**Comment by Tyriar** [comment]
It could be used as an indicator as to whether opening historical output would be useful:

![image](https://user-images.githubusercontent.com/2193314/155378020-75c6e501-872b-4a5a-9ed3-6b94258466df.png)

I don't mind too much though, thoughts @meganrogge @misolori?

**Comment by misolori** [comment]
I agree that the time doesn't really matter and was also surprised to see the "output" icon always visible, which also adds noise. Why isn't that visible on hover instead like our other quick pick actions?

**Comment by meganrogge** [comment]
iTerm tells you when the commands were run, so it's consistent with that. 

I like knowing when it was run, but agree that it's not necessary.

**Comment by meganrogge** [comment]
We will hide the output icon unless focused. 

For now, we're leaving it as is wrt the time since run.

**Comment by misolori** [comment]
but what is the reason why the time is necessary? the terminal doesn't ever mention time so the user has no frame of reference

**Comment by Tyriar** [comment]
Then same reason some people add timestamps to their prompt; it's useful to know when something was run and it's not clear if it was yesterday or 2 minutes ago from the quick pick, this would be particularly useful if the user wants to copy the output. But yeah, I don't think either @meganrogge or I feel too strongly about it so we can remove it.

**Comment by meganrogge** [comment]
part 1 done so we will only show the output button on focus of that item
https://github.com/microsoft/vscode/commit/3abc4e497c7e203dbf8bdfb3d86dd84122b2319f
