### ISSUE TITLE
Terminal run recent command should use suggest widget and history

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#143693]
Testing #143430

1. Have the terminal with some commands
2. F1 > Run recent command
3. Quick pick gets opened

I think this is not a nice flow. Since most likely the terminal is at the bottom and the quick pick gets open at the top of the screen, breaking the user visual flow.

Instead the terminal should use the suggest widget like the Debug Console does and show previous history entries in line.
We also have a [historyNavigationWidget](https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/history.ts#L6) that could be reused here.
I understand that the terminal does not use the editor as an implementation and this would not be straightforward but IMHO this would be the only good UX. Also for consistency since we use this flow in all other locations.

fyi @misolori

**Comment by misolori** [comment]
I like the idea of using a suggest widget to show the commands in the terminal 👍

**Comment by Tyriar** [comment]
Yep, this is definitely the plan when we do autocomplete which is where shell integration is headed, it'll probably consume a full iteration to get right. We're focusing on shell integration fundamentals right now and using these commands as another way to test it. It's tracked on the roadmap only currently https://github.com/microsoft/vscode/wiki/Roadmap#terminal, closing off as I'll create a detailed issue when we're getting closer to doing it.
