### ISSUE TITLE
Integration tests timed out

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#143678]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=157254&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=ff86458e-371d-5daa-d7a2-208b9a858585

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=157270&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=8df5a49b-98a5-577e-6c23-929b1dbd5f98

**Comment by sandy081** [comment]
Not sure who owns the integration tests infrastructure. Hence assigned it to you @bpasero @Tyriar - Please reassign it to right owner. Thanks.

**Comment by bpasero** [comment]
CI machine seems unhealthy for those runs, but not sure why.

Some things from the logs:

@mjbvz 

```
[4248:0222/191619.615556:INFO:CONSOLE(0)] "ResizeObserver loop limit exceeded", source: vscode-webview://5eb49c9b-dd03-416e-8894-343b335c9d2b/index.html?id=5eb49c9b-dd03-416e-8894-343b335c9d2b&swVersion=4&extensionId=&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-webview.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=notebookRenderer (0)
 ```

@Tyriar 

```
vscode API - globalState / workspaceState
Terminal disposed of during xterm.js creation: Error: Terminal disposed of during xterm.js creation
    at bi._createXterm (vscode-file://vscode-app/Users/runner/work/1/VSCode-darwin-x64/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2811:112179)
```

@jrieken we should probably not start profiling on an extension test run?

```
[main 2022-02-22T19:20:29.985Z] Enabling inspect port on extension host with pid 4273.
[main 2022-02-22T19:20:30.071Z] Enabling inspect port on extension host with pid 4273.
    ✓ editor, onDidChangeVisibleTextEditors (9799ms)
UNRESPONSIVE extension host: received responsive event and cancelling profiling session
```

The remote one shows suspicious `ENOSPC` errors so I wonder if something changed with the hardware we are running on and sometimes we get allocated a slow CI machine?

Typically these tests seem to finish in under 5 minutes, so I do not think we are reaching the timeout limit usually.

**Comment by jrieken** [comment]
> @jrieken we should probably not start profiling on an extension test run?

🤷 Profiling doesn't really come at a cost and I don't really want to litter my code with "if running tests"-check. IMO we should be concerned that the extension host apparently is frozen during test runs

**Comment by Tyriar** [comment]
The xterm warning is harmless in this case and I don't particularly want to remove it because it could be useful in diagnosing an issue where the terminal failed to be created.

**Comment by Tyriar** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=157254&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=ff86458e-371d-5daa-d7a2-208b9a858585 , the timeout seems to be getting hit. Not sure what the normal runtimes are but a lot of tests relating to webviews (markdown, notebooks) take nearly 20 seconds.

---

For https://dev.azure.com/monacotools/Monaco/_build/results?buildId=157270&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=8df5a49b-98a5-577e-6c23-929b1dbd5f98 , `ipynb serializer` starts at 19:30:01 which is ~3 minutes after the task starts, it's caused by remote connection problems:

```
[main 2022-02-22T19:30:01.164Z] Waiting for extension host with pid 11714 to exit.
[remote-connection][Management   ][63cfc…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
[main 2022-02-22T19:30:01.213Z] Extension host with pid 11714 exited with code: 0, signal: null.
[remote-connection][Management   ][63cfc…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
An unknown error occurred. Please consult the log for more details.
The STDIO streams did not close within 10 seconds of the exit event from process '/bin/bash'. This may indicate a child process inherited the STDIO streams and has not yet exited.
##[error]The task has timed out.
```

@alexdima?

**Comment by bpasero** [comment]
I feel this is not happening anymore in recent builds, so maybe it was a temporary hiccup with the build machines. Will leave open for a while and then close if that remains true.

**Comment by sbatten** [comment]
it looks like this build may have had the same issue https://dev.azure.com/monacotools/Monaco/_build/results?buildId=190037&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=9fd0bccc-90ad-5118-165a-bb6fa0e94027

**Comment by sbatten** [comment]
and also the one after that
