### ISSUE TITLE
Confusing reference  counts in TypeScript code lens 

### ISSUE THREAD

**Issue by amcasey** [microsoft/vscode#143648]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.65.0-insider (user setup)
Commit: eeeab304b9ac777b4a8dddf55f66ffebd9e4e7f2
Date: 2022-02-22T14:29:15.294Z
Electron: 16.0.9
Chromium: 96.0.4664.174
Node.js: 16.9.1
V8: 9.6.180.23-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Create a TypeScript file
```ts
function F(f: (x: number) => string) {
}

F(x => x.toString());

F((y: number) => y + "");
```
2. Enable CodeLens

![image](https://user-images.githubusercontent.com/10508071/155227015-5443ee1f-5764-48b1-b312-e104fa9cc7f7.png)

I was not expecting CodeLens to appear above the function invocations.  Based on the results, it looks like it's for the first token of the arrow function (`x` for the first and `(` for the second).

I strongly suspect that this will end up on TS, but @mjbvz asked for a bug.

**Comment by amcasey** [comment]
Incidentally, I noticed that I couldn't trigger this with `const x = y => y.toString()` which makes me think something's getting a false positive (i.e. for is-a-function) from the call expression.

**Comment by mjbvz** [comment]
Note this only repos when you also enable `typescript.referencesCodeLens.showOnAllFunctions`

**Comment by mjbvz** [comment]
The root cause is that we are trying the get the reference count for the callback, but end up invoking the references request on `x` since the start of the function is `x`
