### ISSUE TITLE
Shared Process and Extension Host terminated unexpectedly with SIGTERM

### ISSUE THREAD

**Issue by joeSaad** [microsoft/vscode#143623]
Does this issue occur when all extensions are disabled?: Yes
I removed my vscode completely and installed a completely a new fresh copy of vscode with no extensions in it. 

- VS Code Version: 1.64.2
- OS Version: Mac OSX 10.15.7

Steps to Reproduce:

Updated to version 1.64.2 and kept getting this: 
![image](https://user-images.githubusercontent.com/1170032/155163757-5b57983c-8729-4a91-975b-ba700c122aa8.png)

When Opening developer tools, this is what i find: 
![image](https://user-images.githubusercontent.com/1170032/155164433-49efbd5d-311c-4cca-9e7d-e02a2c81158e.png)

Steps I took to avoid this: 
1. Cleared Editors history
2. Removed vscode completely from my mac
3. Deleted All extensions I had
4. Deleted all folders I had with vscode in it
5. Restarted/ rebooted the machine several times
6. Upgraded the version of node to `16.14.0`
7. Cleared more space on my machine

How do I fix this?

**Comment by joeSaad** [comment]
update: I just updated my OSX to Big Sur `11.6.1 ` and still getting the same error. 
I downgraded my VSCode to `1.61.2` and still getting the same error `Extension host terminated unexpectedly` 

I can't get VSCode to work at all now.. Please advise.

**Comment by Robert-Springer** [comment]
I'm having the same issue as you Joe

**Comment by alexdima** [comment]
The extension host terminates with the `SIGTERM` signal. This indicates that there is something on your machine that is sending this signal to the extension host process. Also, from your screenshot, it looks like the extension host process is not the only one that is being terminated, it looks like our shared process is also killed with `SIGTERM` on your machine. I'm not sure what could be causing this on your machine, but AFAIK we do not use `SIGTERM` to terminate our own processes.

cc @deepak1556 @bpasero

**Comment by joeSaad** [comment]
@alexdima thanks for your response. so what new information you might need? 
any suggestions on how to go around this?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by joeSaad** [comment]
@alexdima when you said `SIGTERM` i searched it up.. and i found it terminates programs.. and i already had put a crontab last week on my machine to terminate node instances `pkill -f node` 
this was the culprit.. 
Thank you very much @alexdima @bpasero
