### ISSUE TITLE
drag-and-drop multiples items of same resource opens multiple editors

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#143694]
Testing #143608

- drag-and-drop multiples items of same resource opens multiple editors

![CleanShot 2022-02-23 at 11 38 52](https://user-images.githubusercontent.com/1898161/155303424-27d5be70-75c4-4c4f-bd7d-08e99406fcd1.gif)

I'm not sure whether this is a bug or a feature because the resulting editors show different scroll positions for the different items.

**Comment by sandy081** [comment]
Interesting, I think it is working as expected because each of them are pointing to different locations. I do not know who is DnD expert, hence CCing @bpasero for opinions.

**Comment by weinand** [comment]
This is fixed now.
