### ISSUE TITLE
Typescript Language Service keeps crashing

### ISSUE THREAD

**Issue by eddiemoore** [microsoft/vscode#143651]
Issue Type: <b>Bug</b>

No real steps to reproduce.

VS Code version: Code 1.64.2 (Universal) (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (5.54GB free)|
|Process Argv|-psn_0_143395 --crash-reporter-id 0f35b197-d852-4d80-8a77-21c69d39ef2e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-apollo|apo|1.19.9
better-toml|bun|0.3.2
gitlens|eam|11.7.0
prettier-vscode|esb|9.3.0
vscode-firefox-debug|fir|2.9.6
vscode-jest-runner|fir|0.4.47
flow-for-vscode|flo|2.0.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
go|gol|0.31.1
todo-tree|Gru|0.0.215
jsonnet|hep|0.1.0
cypher-query-language|jak|1.0.2
sort-typescript-imports|mic|1.4.1
dotenv|mik|1.0.1
vsliveshare|ms-|1.0.5330
color-highlight|nau|2.5.0
rust|rus|0.7.8
vscode-nginx|sha|0.6.0
mdx|sil|0.1.0
code-spell-checker|str|2.1.7
vscode-styled-components|sty|1.7.2
svelte-vscode|sve|105.12.1
vscode-icons|vsc|11.10.0
quokka-vscode|Wal|1.0.448
material-theme|zhu|3.13.20

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

If yes, please follow steps described in https://github.com/microsoft/vscode/issues/143140#issuecomment-1040904820 and this will help to provide info required to resolve problem.
**Please pay attention at the end of the comment about paths etc.**
