### ISSUE TITLE
workbench.activityBar.visible for multi windows

### ISSUE THREAD

**Issue by MarekLew** [microsoft/vscode#143666]
Issue Type: <b>Bug</b>

When I change in one workspace 

settings.js:
  workbench.activityBar.visible: false

then it't change Activity bar visibility in another windows and change their settings

In version 1.61.0 this work correct, this setting from one workspace not interfere in another workspace.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Connection to 'WSL: Ubuntu-20.04' could not be established  Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.48GB free)|
|Process Argv|--crash-reporter-id 97cb982d-87de-498c-847c-bf156e71e235|
|Screen Reader|yes|
|VM|0%|

Connection to 'WSL: Ubuntu-20.04' could not be established  Canceled

</details>

**Comment by MarekLew** [comment]
I excepted efect like this #133111

**Comment by tanhakabir** [comment]
Do you have settings sync turned on?

**Comment by MarekLew** [comment]
Yes. Create two workspace and change theirs setting multiple times. Tested on Two computers. On One computer , before update to 1.64.0 on version 1.61.x work ok. After update, when setting change in one workspace change in another.

**Comment by sbatten** [comment]
this will be fixed in the next release and is already fixed in insiders.
