### ISSUE TITLE
Audio cue settings do not migrate into new settings

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#143635]
Testing https://github.com/microsoft/vscode/issues/143550

I previously set `audioCues.enabled` to `on` given the [previous release notes](https://code.visualstudio.com/updates/v1_64#_audio-cues), but noticed that with the new audio cue settings that nothing was migrated over, or at least I wasn't prompted to update my settings:

<img width="499" alt="CleanShot 2022-02-22 at 09 09 27@2x" src="https://user-images.githubusercontent.com/35271042/155182697-93eec889-c69a-4d10-8545-cbfb29fc66fe.png">

<img width="293" alt="CleanShot 2022-02-22 at 09 11 15@2x" src="https://user-images.githubusercontent.com/35271042/155182986-ed33cb7a-22c9-4e44-97c7-7da6347653cb.png">

This means that everyone else who had enabled this last month will no longer get audio cues, which is a bit annoying. Can we at least make it so that if you have the previous setting enabled that it updates the new settings?

**Comment by hediet** [comment]
Good catch, thanks!

**Comment by misolori** [comment]
This is great, thanks!

<img width="579" alt="CleanShot 2022-02-24 at 08 30 24@2x" src="https://user-images.githubusercontent.com/35271042/155566639-21c35246-4bce-4400-a9c8-3e436807550c.png">

<img width="583" alt="CleanShot 2022-02-24 at 08 32 25@2x" src="https://user-images.githubusercontent.com/35271042/155566663-78f96995-6c8b-421f-bb2b-ae06ed76ece5.png">
