### ISSUE TITLE
Terminal: go to recent directory should be better aligned with our open recent flow

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#143699]
Testing #143430

F1 > terminal go to recent directory
Opens a quick pick of recent folders worked on in the terminal.
I think this experience should be better aligned with our Open Recent flow.

For example:
Ctrl + R, should at the bottom have a new group Terminal with all the terminal entries
Triggering Ctrl + R, when in the terminal would open this list, but just focus the first terminal entry
There would be no separate command etc...

fyi @sbatten @misolori @bpasero for more ideas

**Comment by Tyriar** [comment]
Going to a recent directory in the terminal by typing `cd ...` is very different to opening a new window, this doesn't really work from a code layer perspective either as we'd need the terminal to contribute paths into it. Ultimately though, we cannot intercept ctrl+r in the terminal as it's a critical keybinding for reverse search in nearly every shell. This command (and command history) is mostly a holdover until we get native autocomplete in the terminal.
