### ISSUE TITLE
Test finalized icon contribution API

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#143637]
Refs: https://github.com/microsoft/vscode/issues/119101

- [ ] anyOS @Tyriar

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23143637%0A%0A&assignees=aeschli)

---

To verify:
- create a new extension with `yo code`
- add https://github.com/microsoft/vscode/blob/main/extensions/theme-seti/icons/seti.woff to the extension's root
- add to `contributes` in package.json
```
	"icons": {
		"foo-climate": {
			"description": "Climate icon",
			"default": {
				"fontPath": "./seti.woff",
				"fontCharacter": "\\E014"
			}
		},
		"foo-search_light": {
			"description": "Search light icon",
			"default": {
				"fontPath": "./seti.woff",
				"fontCharacter": "\\E015"
			}
		}
	}
```

- create a status bar entry and use $(foo-climate)
```
		const item = vscode.window.createStatusBarItem();
		item.text = 'Hello $(foo-climate) $(foo-search_light) $(zap)';
````

Test that the icons show
Test that no `enabledApiProposals` is needed.

**Comment by Tyriar** [comment]
@aeschli probably not an issue but fyi:

![image](https://user-images.githubusercontent.com/2193314/155374011-c083eebc-56bc-4993-a7e8-5a4b708e4be6.png)

**Comment by aeschli** [comment]
I corrected the sample, underscore is not allowed.
