### ISSUE TITLE
Debug console default suggest widget item icon looks broken

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#143691]
1. [Smoketest-express repo](https://github.com/microsoft/vscode-smoketest-express)
2. Start debugging, put breakpoint in `index.js:6`
3. `localhost:3000` -> hit breakpoints
4. Debug console -> trigger suggest widget

A lot of icons look broken.
Is this js-debug not providing a proper item type?
Still if this is the default icon it looks like a rendering glitch.

fyi @connor4312 @jrieken 

![Screenshot 2022-02-23 at 11 30 42](https://user-images.githubusercontent.com/1926584/155302230-27352c4d-82ec-42e5-8f57-57f5225d7ca5.png)

**Comment by jrieken** [comment]
Which icon do you mean? The wrench is for property, the half-shredded paper is for snippets. Maybe the question is why do snippet suggestions appear in the debug console?

**Comment by isidorn** [comment]
Thanks for clarifying so we have two things here as you say:
1) Snippets should not appear in debug console
2) Snippet half-shredded paper icon looks like broken rendering to me. I think we need a better icon (though it might be just me) @misolori @daviddossett what do you think?

**Comment by misolori** [comment]
These icons haven't changed from the originals 😄 

![image](https://user-images.githubusercontent.com/35271042/155377644-e592834c-675d-445e-8052-9a21a70f24f4.png)

**Comment by roblourens** [comment]
> Snippets should not appear in debug console

So then that is the issue? Did it ever work that way before?

**Comment by jrieken** [comment]
I believe there is no, at least not a new issues, unless snippet where muted before. I agree that there is value in snippets for the debug console but maybe not the default JS snippets like class, for-each, etc... 

@isidorn Can it be that you have been using `"editor.suggest.showSnippets": false` for the longest time and that it's the first time you see snippets in suggest now?

**Comment by isidorn** [comment]
@roblourens no, this never worked.
@jrieken no, I do not have snippets disabled. I just never saw them taking up most of the items in the suggest widget, thus this is the first time my brain registered this icon fully.

Having said all of that, feel free to close if there are no clear action items here and if I am the only one that find the icon look like a placeholder broken icon. Thanks!
