### ISSUE TITLE
Debug: inform user how to enable expression/hit-count breakpoint

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14361]
Testing #13211

It seems only by pressing enter can you confirm a change to expression or hit-count, I suggest to show this in the ghost-text of the input field. Also mention ESC to cancel and close the box.

![image](https://cloud.githubusercontent.com/assets/900690/19679027/847e6a7e-9aa0-11e6-8e13-367431d0c066.png)

**Comment by isidorn** [comment]
It was like that before but @joaomoreno suggested to remove it.
Bringing it back makes sense to me
