### ISSUE TITLE
Accept switch between workspace without save files.

### ISSUE THREAD

**Issue by jverblud** [microsoft/vscode#143639]
I would like to change to project workspace without saving the files (like sublime text). Sometimes we are working on multiples projects and need to fast switch without save any file, and then return to the modification. that's it

**Comment by IllusionMH** [comment]
Have you checked `files.hotExit`? I think with `onExitAndWindowClose` there shouldn't be any prompts.

**Comment by jverblud** [comment]
@IllusionMH , its works! Apologies for this requests, I'm new in this environment and I assumed that regarding feature was not added...
Thanks for helping, @IllusionMH .
