### ISSUE TITLE
Almost all smoke tests failed with same reason

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#143628]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=157189&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=79e950e2-ae58-5fea-a241-0229f56d23a3

There is following common warning in all reported screenshots

![verifies_that_auto_save_triggers_on_shutdown](https://user-images.githubusercontent.com/10746682/155169492-10785381-4b66-4534-807f-0ae63a6a85c2.png)

**Comment by bpasero** [comment]
Looks like the machine is not very healthy / was running out of file handles. I would not assume that smoke tests run well then. However I noticed how the runner log is megabytes in size and pushed https://github.com/microsoft/vscode/commit/63db74895b88655a52f9aa792868e10198aa91c8 to bring that back to normal. Will keep an eye out if this happens again, but with the current logs, hard to tell.
