### ISSUE TITLE
Terminal customization

### ISSUE THREAD

**Issue by ShaikRehan123** [microsoft/vscode#143684]
Add support for customization for terminal like the code editor like changing font family,cursor type , line height and more

**Comment by gjsjohnmurray** [comment]
have you investigated existing settings?

![image](https://user-images.githubusercontent.com/6726799/155308123-d3563cf1-0c4d-4442-a7fc-cf1ccf080c48.png)

**Comment by ShaikRehan123** [comment]
@gjsjohnmurray I am really Sorry
