### ISSUE TITLE
Unit test failure - memoized property should not be writable

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#143676]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=157236&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=821d316a-2fa3-581f-c34c-57a961b8e328

```
 1) Decorators
       memoized property should not be writable:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\_work\1\s\test\unit\node\index.js)
      at processImmediate (node:internal/timers:464:21)
```

**Comment by joaomoreno** [comment]
I can't explain why this test took more than 2s when no code change has happened and when it's been green and fast forever. The only reason I can find is that the build agent VM froze or was busy doing something else right around that time.
