### ISSUE TITLE
 node: command not found

### ISSUE THREAD

**Issue by han6054** [microsoft/vscode#143600]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. The following figure shows an error when using the debug script
2. node verison 14.18.1
<img width="1461" alt="WechatIMG5" src="https://user-images.githubusercontent.com/16551126/155104361-7e80c5e9-1502-4e4b-a379-6d90e4ab6769.png">

**Comment by han6054** [comment]
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/16551126/155105625-a204001e-b11f-4eae-ab87-9c6aa2690ff7.png">

**Comment by weinand** [comment]
@han6054 Do you have node.js installed and available in your PATH?

**Comment by han6054** [comment]
> @han6054 Do you have node.js installed and available in your PATH?

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/16551126/155118150-1fc00c0b-e849-41e0-a703-42c981bf2db6.png">

**Comment by weinand** [comment]
@han6054 what's the result of `which node`?

**Comment by han6054** [comment]
> @han6054 what's the result of `which node`? Are you running `code.sh` in the same integrated terminal as the `echo $PATH` and the `which node`?

I ran code.sh under version 14.18.1

**Comment by weinand** [comment]
@han6054 please type "which node" in VS Code's integrated terminal.
Does it show the correct path to the node executable?
