### ISSUE TITLE
error loading language detection model TypeError: Failed to fetch

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#143631]
* run `./scripts/code.sh`
* create a new file

  | getRegexpModel | @ | ../../../vs/workbenc…nSimpleWorker.js:78
-- | -- | -- | --
  | await in getRegexpModel (async) |   |  
  | runRegexpModel | @ | ../../../vs/workbenc…nSimpleWorker.js:83
  | detectLanguage | @ | ../../../vs/workbenc…nSimpleWorker.js:44
  | await in detectLanguage (async) |   |  
  | _handleMessage | @ | ../../../vs/base/com…simpleWorker.js:368
  | handleMessage | @ | ../../../vs/base/com…simpleWorker.js:353
  | _handleRequestMessage | @ | ../../../vs/base/com…simpleWorker.js:157
  | _handleMessage | @ | ../../../vs/base/com…simpleWorker.js:126
  | handleMessage | @ | ../../../vs/base/com…simpleWorker.js:119
  | onmessage | @ | ../../../vs/base/com…simpleWorker.js:358
  | self.onmessage | @ | workerMain.js:81

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/5047891/155174824-04cdafe8-b235-4a31-89ce-bd213914a003.png">

**Comment by JacksonKearl** [comment]
Model is only available in product builds so I'll just swallow that error.
