### ISSUE TITLE
Customize layout quick pick doesn't update when layout state changes

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#143789]
Testing #143581

![Recording 2022-02-23 at 10 26 34](https://user-images.githubusercontent.com/876920/155383650-836ac38d-1c35-4b0f-b17a-ab41f6a0ef99.gif)

The visibility state doesn't change when updating through any way.

**Comment by sbatten** [comment]
visibility state is reflected on hover

**Comment by rebornix** [comment]
@sbatten this is confusing to me. We show checkmarks based on if a position is picked but we never show the visibility if we don't hover/focus on the option. Why don't we use the same UX (checkmark) here?

**Comment by sbatten** [comment]
this is not the final form of the quick pick. eventually we will support checkboxes and radio buttons and we will move to that. for now we want to differentiate between checkboxes and radio buttons without actually having them. so we aren't using the same icon for both.
