### ISSUE TITLE
Give lazy expand link a tooltip

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#143799]
Testing #143572

Hovering the lazy expander `(...)` does not have a tooltip describing what the click will actually do

**Comment by roblourens** [comment]
Any suggestions for what it should be? The placeholder value could go here.

cc @weinand @connor4312

**Comment by connor4312** [comment]
Something like `Evaluate ${name}`?

**Comment by weinand** [comment]
@connor4312 you said somewhere that "evaluate" is not the correct term. What does Chrome devtools do?

**Comment by connor4312** [comment]
Chrome devtools is "Invoke Property Getter". Which is good but also somewhat language specific. Maybe Rob's suggestion of using the `value` is a good idea, js-debug could pass back a label like that. It would also look nice in UIs who haven't yet adopted the lazy flag.

**Comment by JacksonKearl** [comment]
`Resolve` makes sense to me.

**Comment by roblourens** [comment]
I want to start with the `value`, I think it will be more helpful. Let's see if that works in js-debug. Otherwise I would go with `Resolve $name`
