### ISSUE TITLE
UX of Disable and Uninstall feels weird to me

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#14379]
Testing #14288
- Disable looks like a button (which makes me think it should be single-clickable) but then it pops up a menu.
- I would personally have a wrench icon or a "Manage" link and put the three actions in there:
  - Disable for current workspace
  - Disable
  - Uninstall

Suggested menu:
![image](https://cloud.githubusercontent.com/assets/5047891/19680555/77d23b06-9aa6-11e6-9697-c16fad92100f.png)
- Also I believe the Reload button should not be a button, but a fly-out at the top of the viewlet that pushes everything down and reads "Some changes will not be applied until you restart" or something like that.

![image](https://cloud.githubusercontent.com/assets/5047891/19680245/451f8336-9aa5-11e6-9c63-d367d7a8db76.png)

**Comment by sandy081** [comment]
@alexandrudima Thanks for the feedback. I do like moving uninstall/enable/disable actions to a context menu which will simplify UI a lot.

Currently reload button indicates the user, what extensions to reload. I think having a global reload button also makes sense.

**Comment by alexandrudima** [comment]
@sandy081 I suggest removing the Reload button from each extension and using some sort of other affordance:

Each button does the same thing and it is not related to an extension, plus it gives me the feeling that it will apply only for that extension, meanwhile it applies for all extensions.

![image](https://cloud.githubusercontent.com/assets/5047891/19681466/cf4df87c-9aa9-11e6-8bad-c41db4163cce.png)

**Comment by sandy081** [comment]
Did some improvements by moving the actions (Uninstall, Enable, Disable) under settings icon. 

Moving this to November for the rest
