### ISSUE TITLE
Duplicate editor opens in active group instead of staying where it was originally

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#143753]
Repro steps:

- open file A and click somewhere in it
- open file B in the same group
- move file B to a side group
- click in file B
- navigate back in history
- 🐛  file A opens in the side group
- I expected it to focus the original in the other group 

Testing #142503
![Recording 2022-02-23 at 10 20 38](https://user-images.githubusercontent.com/29464607/155361292-0ebb6654-6c6f-4fdc-a44f-883d554f3f12.gif)

**Comment by bpasero** [comment]
I tried a minimal repro with text files, moving one to the other group and navigating and cannot reproduce:

![Recording 2022-02-23 at 18 34 43](https://user-images.githubusercontent.com/900690/155374914-c7445453-68d2-4a60-af1e-cca45fd39e9b.gif)

Is there a repro from scratch?

**Comment by meganrogge** [comment]
I can't reproduce it now 🤷🏼‍♀️ .
