### ISSUE TITLE
If the line is too long, it doesn't get highlighted

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#143757]
Testing #143612

This might be as-designed but I'll file this issue just in case.

1. Create an output channel and append a long line.
```ts
const channel2 = vscode.window.createOutputChannel('Test C++ channel', 'cpp');
for (let i = 0; i < 10000; i++) {
	channel2.append('std::cout << test(2) << std::endl;');
}
```
2. :bug: Test the extension and notice the line isn't highlighted.

**Comment by sandy081** [comment]
Output channel uses editor underneath and I assume syntax highlighting is disabled when the line gets longer for performance reasons.
