### ISSUE TITLE
Folded code icon in editor is wrong

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#143772]
- Fold some code
- The `...` button at the end of the line is not correct

<img width="288" alt="image" src="https://user-images.githubusercontent.com/323878/155376293-f9e2b8ae-a967-4288-b11e-1b57686b3196.png">

**Comment by roblourens** [comment]
Maybe the encoding got mangled during the build?

<img width="265" alt="image" src="https://user-images.githubusercontent.com/323878/155376390-c80161b2-4340-4eb1-881c-0eb4130cad1b.png">

**Comment by aeschli** [comment]
Where do you see this? What build and platform?
I can't see it in the latest insiders, neither on Linux, Windows nor the web.
Also there hasn't been any changes to the css file in the last years.

**Comment by roblourens** [comment]
Actually, I think devtools might be messing up that file. It only happens after I open devtools...

**Comment by roblourens** [comment]
Yeah, I saw it on two different platforms at different times and thought there was something real, but no, this is bug in devtools' CSS pretty printer...

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode/issues/145897
