### ISSUE TITLE
No highlight around ascii charactered string

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#143768]
Testing #143553

I'm not seeing any highlights around the suggested character's string (https://github.com/microsoft/vscode/issues/143553#issuecomment-1048734093):
<img width="538" alt="image" src="https://user-images.githubusercontent.com/12758612/155373415-d790b8f3-7bdc-401f-905f-8f330fa86bd5.png">

**Comment by hediet** [comment]
This is by design (but the design is not really fixed).

The weird looking characters (λ and ℕ) indicate already visually that something funny is going on. Contextual highlighting only highlights characters when it would not be obvious that something unexpected is going on.
