### ISSUE TITLE
timeout during open a file in mounted folder

### ISSUE THREAD

**Issue by raminrch** [microsoft/vscode#143726]
hi,
i mount a cifs share folder but when i want to open a file in tha that directory, the vscode doesn't respond and below error displayed :
INFO:CONSOLE(1)] "TypeError: setTimeout(...).unref is

**Comment by raminrch** [comment]
![Recording 2022-02-24 at 21 33 07](https://user-images.githubusercontent.com/53653018/155581900-2057d0ec-a8a8-42b8-8fa7-b2359369878f.gif)

thanks for your reply, 
i upload a gif that describe my problem.

**Comment by bpasero** [comment]
Does it go faster if you open `code <path>` from the command line?

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by raminrch** [comment]
> "Does it go faster if you open code <path> from the command line?"
yes, when i try to open file from shell with command it is faster but the problem still exists.

> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from
i tried this versio of insider 1.65.0-insider , 8440b8f47231147823ba9696913d642e5f2d9d58, but unfortunately the problem still exists.

**Comment by bpasero** [comment]
Does the file open eventually?

**Comment by raminrch** [comment]
no the open does not open until the error dialogue display on the screen.

**Comment by raminrch** [comment]
finally i solve my problem.
i mount my share directory using Ubuntu GUI Tool. and the file now open normally by vscode.
