### ISSUE TITLE
Creating a new stash using icon does not close diff editors

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#143709]
Testing #143619

![image](https://user-images.githubusercontent.com/13199757/155308771-e1a8c3aa-f198-4b69-8176-bec37d0bf0cb.png)

> 4. Invoke the command to create a new stash based on the changes

However if I invoke it via the command as mentioned, it works fine.

**Comment by gjsjohnmurray** [comment]
@karrtikr I think this command icon is contributed by GitLens

**Comment by karrtikr** [comment]
That is actually true, it's still confusing as the rest of the icons work fine.

**Comment by gjsjohnmurray** [comment]
I suggest you report it on GitLens. When the new command arrives in 1.65 maybe they will adopt it.

**Comment by karrtikr** [comment]
Created https://github.com/gitkraken/vscode-gitlens/issues/1830
