### ISSUE TITLE
Remote hub indexing cannot be turned on after it is canceled

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#143780]
Testing #143575

1. Remote hub to something that is larger than 50 MB (I used https://github.com/plotly/plotly.js)
2. Go to search 
3. Search for 'module.exports'
4. Cancel download when it happens
5. Run command 'Configure indexing of Repositories'
6. Turn off 'Disallowed:' for the repository
7. Try search again

Expected to download a second time.

**Comment by JacksonKearl** [comment]
![Recording 2022-02-23 at 10 19 29](https://user-images.githubusercontent.com/8586769/155382486-27743aa0-a253-419e-b895-bfd3024beabc.gif)
I see this when I try, it sounds like you may be on an old version? Or a deeper bug. If you include a screengrab I could better diagnose

**Comment by rchiodo** [comment]
What would you like a screen grab of?

**Comment by JacksonKearl** [comment]
Same as #143770, if you include the output channel that'd help. Also once you `Turn off 'Disallowed:' for the repository` and re-run the `'Configure indexing of Repositories'` command, do you see the entry removed? The check box quick pick is unfortunately easy to misuse.

**Comment by rchiodo** [comment]
'Configure indexing of Repositories' isn't enabled after I turn it off. But I can turn it back on again with 'Enable indexing of Respositories'

When it's off, it's supposed to ask, right? If that's true it is not asking.

Here's the log after trying to get this to ask:
[githublog.txt](https://github.com/microsoft/vscode/files/8172601/githublog.txt)

**Comment by JacksonKearl** [comment]
When it's off it should attempt to download the repo by default. That repo is big so it should then error out at 50 MB and ask if you want to use partial or full results. If you cancel the download manually then click the "Download full contents" link you wont be prompted at 50MB. This is what I see: 

![Recording 2022-03-02 at 16 09 49](https://user-images.githubusercontent.com/8586769/156471112-78e4ad9e-03ca-47f6-b5f0-c5f7cdfcacc3.gif)

**Comment by rchiodo** [comment]
Yeah it never asks.

**Comment by joyceerhl** [comment]
This doesn't repro for me anymore in latest github.dev so closing--please reopen if you continue to see issues!
