### ISSUE TITLE
Layout quick pick loses focus after pressing enter

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#143782]
Testing #143581

* Customize Layout
* Use keyboard to navigate 
* Press enter on a layout option
* It takes effect immediately but the quick pick loses focus, though it's still visible

**Comment by sbatten** [comment]
@rebornix can you share what it loses focus to... we work to keep focus but some things try to steal it

**Comment by rebornix** [comment]
@sbatten open either the settings editor or a notebook editor, you would see that both of them steal the focus when changing layouts.

**Comment by rebornix** [comment]
This could be an issue with the editors though

**Comment by sbatten** [comment]
@TylerLeonhardt I am calling focus on the quick input, but it has no effect even if I delay it by 1000ms

https://github.com/microsoft/vscode/blob/00b3baf903bcbf09f9f410e1e6ba2d1318b45adc/src/vs/workbench/browser/actions/layoutActions.ts#L1263
