### ISSUE TITLE
Insider's vscode.dev opens to a random PR

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#143749]
Testing #143461

I signed in to github and this is what I saw. I have never seen this PR before and have no idea where it's coming from. 

Is this expected?

![Screen Shot 2022-02-23 at 9 48 02 AM](https://user-images.githubusercontent.com/29464607/155354791-58d43503-21ec-462e-976f-110e4e5d7e20.png)

**Comment by meganrogge** [comment]
Other info:
![Screen Shot 2022-02-23 at 9 49 46 AM](https://user-images.githubusercontent.com/29464607/155355142-3c54b4ef-c68b-4ca6-873f-17b5ae4325ad.png)

**Comment by meganrogge** [comment]
cc @alexr00

**Comment by meganrogge** [comment]
I exited review mode (having never entered it myself in the first place) and am still in this random repo
![Screen Shot 2022-02-23 at 9 52 46 AM](https://user-images.githubusercontent.com/29464607/155355700-b3a78597-6a32-421f-8305-6044e21d36b8.png)

**Comment by alexr00** [comment]
What URL did you enter to get there? Was it the one in https://user-images.githubusercontent.com/29464607/155354791-58d43503-21ec-462e-976f-110e4e5d7e20.png?

**Comment by meganrogge** [comment]
Oh - mystery solved. This randomness is coming from edge's search results 
![Screen Shot 2022-02-23 at 10 07 48 AM](https://user-images.githubusercontent.com/29464607/155358771-15aec8e5-4045-4736-b24e-b38ff360225d.png)
