### ISSUE TITLE
Extensions: disablement state needs to be communicated across windows

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14372]
Testing #14288
- open one window and disable an extension for the workspace
- open another window and disable the same extension always

=> the first window still thinks the disabled state is only for the workspace when it was globally disabled

**Comment by sandy081** [comment]
Another dependent of #58957

**Comment by bpasero** [comment]
I would have expected this to work:
* open one window with a workspace
* open extensions view
* open a second empty window
* disable an extension globally from the second empty window
* back in the first window the extension still shows as enabled

**Comment by sandy081** [comment]
@bpasero it works for me

![kapture 2019-01-30 at 0 07 25](https://user-images.githubusercontent.com/10746682/51946839-22559480-2423-11e9-8115-7a35d3cb9914.gif)

**Comment by bpasero** [comment]
@sandy081 I see it working nicely when disabling the extension globally but this flow still seems broken:
* disable extension for workspace in one window
* disable extension globally in other window
* 🐛 first window still thinks the extension is only disabled for workspace, is that expected?

**Comment by sandy081** [comment]
Yes, workspace disabled extensions are not overridden when globally disabled or enabled.
