### ISSUE TITLE
Menu Bar

### ISSUE THREAD

**Issue by TilerDaniels99** [microsoft/vscode#143793]
Issue Type: <b>Feature Request</b>

There is no menu bar on MacOS cause when I go to View < Apperace, there is no option that says "Show Menu Bar"

VS Code version: Code 1.64.2 (Universal) (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

**Comment by sbatten** [comment]
macos uses a global application menu and is always visible. there is no setting to change this.
