### ISSUE TITLE
audio cue echo when error and warning exists on a line

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#143759]
Issue Type: <b>Bug</b>

while testing #143550

1. Turn on audio cues for warnings and errors
2. write a line with both and error and a warning

result:
navigating to that line produces an inconsistent sound, and sounds like two sounds are being played which don't always line up

VS Code version: Code - Insiders 1.65.0-insider (32456dc9e7d3194a94dd3ee0322ccf47e461d09c, 2022-02-23T05:16:22.798Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (16.52GB free)|
|Process Argv|--crash-reporter-id 1202dc88-403d-4ebc-8393-af3551a8bd5b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.3
vscode-eslint|dba|2.2.3
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.3.0
vscode-pull-request-github|Git|0.37.2022022309
python|ms-|2022.1.1854775815-dev
vscode-pylance|ms-|2022.2.4-pre.1
jupyter|ms-|2022.2.1010551006
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.223.0
remote-ssh|ms-|0.75.2022022115

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstartedc:30421358
vsclayoutctrc:30405799
dsvsc009:30440021
pythonvspyt640:30438691
vsbas813:30436447
vscscmwlcmt:30428973
azactmsal:30432848
vscgsvid1:30433757
dockersurvey3:30438168

```

</details>

**Comment by hediet** [comment]
This is a side effect of warnings and errors using the same sound (which might change at some time).

I added some logic to avoid this case.
