### ISSUE TITLE
Second level lazy variables fail in WATCH view, debug hover, and REPL

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#143730]
Testing #143572

- use version 1.49.5 of Mock Debug since I've added second level lazy variables
- add variable `$o` as a WATCH expression
- set a breakpoint in line 28 of `sampleWorkspace/readme.md`
- start debugging and hit breakpoint
- for `$o.flazyInteger` press "lazy" button in Variables view, Watches view, and debug hover, and REPL

Observe: the value is only fetched in the Variables view, but not in Watches view, debug hover, or REPL 

![CleanShot 2022-02-23 at 15 07 38](https://user-images.githubusercontent.com/1898161/155335699-0d24fe1a-1219-479b-9d4a-df710db86931.gif)

**Comment by JacksonKearl** [comment]
Noticed that in REPL, I can click the `(...)` of the object's `flazyInteger` and nothing changes, but upon collaping and re-expanding the object I do see the resolved value.

**Comment by weinand** [comment]
Works fine now!
