### ISSUE TITLE
Setting a lazy variable reveals the intermediary variable

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#143751]
Testing #143572

Setting a lazy variable reveals the intermediary variable:

![CleanShot 2022-02-23 at 17 12 11](https://user-images.githubusercontent.com/1898161/155359698-51b02745-310a-4188-98f0-545490bd8c4e.gif)

**Comment by roblourens** [comment]
I will just disable "set value" on lazy props

**Comment by connor4312** [comment]
I don't think it's good to disable "set value" on lazy props, but in the latest Insiders it seems like "set value" works correctly. (Did you just disable "set value" on unexpanded properties?

**Comment by roblourens** [comment]
Yes that's what I meant
