### ISSUE TITLE
Inlay hints that support double click gestures should use cursor: pointer

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#143740]
Follow steps from https://github.com/microsoft/vscode/issues/141576#issuecomment-1047059437
The inlay hints can be clicked upon. But this is very hard to discover.
I suggest to at least render the mouse as a point on hover over those inlay hints.

Also why is it double click and not single click? Double click makes it even harder to discover.

Also only the right inlay decoration renders the underline. Let me know if you would like me to file a separate issue for that (image attached).

![Screenshot 2022-02-23 at 15 52 13](https://user-images.githubusercontent.com/1926584/155343853-240dbdc0-d321-44fa-94a1-d0166e24703c.png)

**Comment by jrieken** [comment]
> Also only the right inlay decoration renders the underline. Let me know if you would like me to file a separate issue for that (image attached).

The underline is something different than the dbl-click gesture... It's complicated but parts of an inlay hint can be links and the whole inlay hint can have a double click command. That should also answer why it is double click, not single click. Tho, I still like the pointer suggestion

**Comment by jrieken** [comment]
Closing as `InlayHint#command` has been removed for now
