### ISSUE TITLE
MacOS Monterey: Can’t switch between windows with localized keyboard shortcuts

### ISSUE THREAD

**Issue by dieulot** [microsoft/vscode#143712]
Issue Type: <b>Bug</b>

With MacOS Monterey set up with a French keyboard layout on installation, cmd + < doesn’t work.

https://mjtsai.com/blog/2021/06/17/macos-12-localized-keyboard-shortcuts/
(The link to the WWDC video is apparently all the docs about the change that Apple provides. The Twitter thread has some more details but they’re probably irrelevant, the only notable thing is that MacOS needs to be fresh-installed with a non-English layout for those localized keyboard shortcuts to take effect.)

(On older macOS versions cmd+` didn’t work either in VSCode with a French keyboard layout, but that’s not my issue anymore.)

VS Code version: Code 1.64.2 (Universal) (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz (4 x 1100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.19GB free)|
|Process Argv|--crash-reporter-id c2c6893c-e7e1-4519-a7dc-5aae8495167d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.3
jupyter|ms-|2022.1.1301854968

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30438340
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
vscop841cf:30438916
dsvsc009:30440023
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvid1:30438799
helix:30440343

```

</details>

**Comment by alexdima** [comment]
Switching between windows (which on a US kb layout is at `` cmd + ` ``) is a keybinding handled by the OS. I am not sure if even Electron/Chromium can do anything to influence it in any way.

@dieulot Have you found that other applications behave differently than VS Code? How about Edge or Chrome?
