### ISSUE TITLE
Whitespace color seems too strong in Light High Contrast

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#143739]
Testing #143425

<img width="512" alt="image" src="https://user-images.githubusercontent.com/5047891/155343587-d2bc9d93-abcd-4ff6-8a47-a278b61f5988.png">

<img width="525" alt="image" src="https://user-images.githubusercontent.com/5047891/155343726-ee86772a-df9f-46c1-9d0c-106bc2826c06.png">

**Comment by daviddossett** [comment]
Updated to use `#CCCCCC`
