### ISSUE TITLE
Preserve type of (effectively) constant variables in the outer scope inside callbacks

### ISSUE THREAD

**Issue by Forlini91** [microsoft/vscode#143745]
We often have a situation like this:
The result of a function is stored in a variable and we use that variable in a callback
![image](https://user-images.githubusercontent.com/12827228/155343933-9beac559-2c13-40d0-a0a1-b7c7d4a4acf3.png)

As you can see, the variable x is "effectively" constant (not const, but it is never reassigned. I use var because my project must support ECMA Script 5) and a quick check make sure the value is not null. As soon as we enter the callback, the variable has "number | null" type again. 
I understand this happens because, generally speaking, "var" and "let" variables may change value by the time the callback is called, while "const" correctly preserve the "number" type in this scenario.

My request is: is it possible to detect an "effectively" constant variable (like in this case) and consider it as a "const", and so preserving the current type inside a callback ("number" in this case)? 
Maybe VSCode could see all var/let variables as "constants" (when evaluating their type) unless assigned more than once

**Comment by mjbvz** [comment]
This already works if you use `const`. I suggest looking into using this and then compiling down to ES5 instead

Marking this as by-design for uses of `var`
