### ISSUE TITLE
Debug hover could trigger a lazy variable refresh 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#143725]
Testing #143572

- hover over a lazy variable to trigger a fetch of the value

Observe: hover shows real value but Variables view or inline values do not

![CleanShot 2022-02-23 at 14 40 17](https://user-images.githubusercontent.com/1898161/155330768-420a9b96-e485-4d8c-9435-75740213b0f4.gif)

This behavior is different from the Variables view where fetching a "lazy" value triggers an inline values update.

**Comment by roblourens** [comment]
I don't want to try to tie the hover expression to something in the variables view, it's complicated and can't be done perfectly.

**Comment by weinand** [comment]
@roblourens makes sense. I support your decision.
