### ISSUE TITLE
Terminal scrollbar width is 4px thinner than editor's scrollbar

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#14374]
Testing #13440

Terminal scrollbar is 4px thinner than editor scrollbar. IMHO it would be more pleasent if their widths would match.

![image](https://cloud.githubusercontent.com/assets/5047891/19679960/28fb56a4-9aa4-11e6-8296-88c22a11b637.png)

**Comment by Tyriar** [comment]
That's because it's a native scroll bar. Since the viewport/scroll bar logic is housed entirely within an external library it is non-trivial to change and I don't think forcing hooks to enable our custom scroll bars within upstream would be a good decision for the project.
