### ISSUE TITLE
Should there be a fast access to active tab group?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#143718]
We have `activeTab` on `tabGroup` but no way of getting fast at the active tab group other than looping over all it seems.

**Comment by bpasero** [comment]
Maybe `window.activeTabGroup`?

**Comment by bpasero** [comment]
The name and location is probably an API discussion item, but I find `all` and `activeTabGroup` very asymmetric. It is either `window.activeTabGroup` or `active` imho.

**Comment by lramos15** [comment]
> The name and location is probably an API discussion item

I'll bring it up at the API sync today. Feel free to join and plea your case :p
