### ISSUE TITLE
Provide an easy way to disable command decorations

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#143737]
Currently you can disable them via:

```
  "terminal.integrated.shellIntegration.commandIconDefault": "",
  "terminal.integrated.shellIntegration.commandIconError": "",
  "terminal.integrated.shellIntegration.commandIcon": "",
```

But this is not particularly easy and the decorations still end up rendering. We should have a switch that disables them outright, including adding them to xterm.

**Comment by pitust** [comment]
<img width="1096" alt="Screen Shot 2022-02-23 at 5 03 05 PM" src="https://user-images.githubusercontent.com/41321673/155357901-aa998891-5562-4733-8bfe-7518d2b4eb5c.png">

It is enabled even though shell integration is off... But thanks for the fix, now i can go back to using the integrated terminal!

**Comment by Tyriar** [comment]
@pitust they're rectangles so you're probably on a pretty old build (1 week+?), updating will probably fix it for you.

**Comment by misolori** [comment]
@meganrogge are there any verification steps?

**Comment by meganrogge** [comment]
It's still unreleased, but use `terminal.integrated.commandDecorationsEnabled:false` to disable them.
