### ISSUE TITLE
Confusing 'Show Command Actions...' text in command decoration hover

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#143791]
Testing #143433

The 'Show Command Actions...' text that appears on hovering a terminal command decoration seems to suggest a context menu of some sort. Should I be able to click on this somehow?

**Comment by meganrogge** [comment]
Miguel had this feedback too ![Screen Shot 2022-02-23 at 1 53 05 PM](https://user-images.githubusercontent.com/29464607/155397343-23835b3f-c7a7-4c50-a96c-4a1af8c7fd0e.png)

@Tyriar I thought you had resolved this?
