### ISSUE TITLE
In VSC no </> to allow "Retrieve and Open Source".

### ISSUE THREAD

**Issue by apear1** [microsoft/vscode#143711]
In VSC when connected to any Salesforce org. there is no </> next to the metadata item for reports and dashboards to allow "Retrieve and Open Source" of the item - for other items there are as per the attached screenshot.
![HoverScreenshots_NoBrackets](https://user-images.githubusercontent.com/100283778/155311361-dd0448f7-a739-453f-9553-e89933a427f2.png)
.

**Comment by IllusionMH** [comment]
/causedByExtension

Looks like these views are contributed by an extension (I think Salesforce) and therefore requests/questions should be addressed in corresponding extensions repo/issue tracker.

**Comment by apear1** [comment]
Thanks for the pointer but can you provide the link to channel this issue in the right direction? Thanks.
