### ISSUE TITLE
Trigger inline suggestion command does not do anything

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#143734]
Testing #143550

1. Go to a line where Copilot suggests you something. Sound is played -> great!
2. Now F1 > trigger inline suggestion command
3. No effect 🐛 

I would expect the inline suggestion hover to show up and that focus is passed into it.

**Comment by hediet** [comment]
What do you mean with "No effect"?

> I would expect the inline suggestion hover to show up

You can do that with Ctrl+K, Ctrl+I.

**Comment by isidorn** [comment]
I mean nothing happened when "trigger inline suggestion" command is triggered. What is that supposed to do exactly if not trigger the hover?

Feel free to use this issue as a placeholder for "tab does not move focus inside hover"

**Comment by hediet** [comment]
Fixed by 07447e81.

**Comment by isidorn** [comment]
If I have "tab key moves focus" and I trigger the suggest widget I still can not select the buttons inside the hover. Reopening.
So you double check if this works for you and if I might be doing something wrong.

**Comment by hediet** [comment]
Did you enable accessibility support? Only then the hover is focused after triggering it. This is a general property of all hovers.

**Comment by isidorn** [comment]
You are right, I missed that. Let's close this.
And I created a follow up issue https://github.com/microsoft/vscode/issues/144060
