### ISSUE TITLE
Bind remember tabs to a branch, by switching branches the tabs automatically update

### ISSUE THREAD

**Issue by arousta** [microsoft/vscode#143794]
It happens all the time. When I work on different tickets and each one is related to something in my project. For each branch I want to have a specific set of files to be open.

It would be very handy if vscode can save the open tabs for a branch and recover those when I switch my branches.

**Comment by gjsjohnmurray** [comment]
I have used the [Restore Git Branch Tabs](https://marketplace.visualstudio.com/items?itemName=gkotas.restore-git-branch-tabs) extension for this.

**Comment by arousta** [comment]
Thanks @gjsjohnmurray for introducing this. What I was looking for 👍 😃
