### ISSUE TITLE
Diff Editors are not closed when running `Git: Close All Diff Editors`

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#143746]
Testing #143619

* open some git diff editors
* focus a regular editor
* run `Git: Close All Diff Editors`
* 🐛  the diff editors do not close

https://user-images.githubusercontent.com/5047891/155348884-5cb01dae-4b03-4e42-8a07-63991918cca5.mp4

**Comment by lramos15** [comment]
Proposed API changed, forgot to update the git extensions consumptions of this API

**Comment by lszomoru** [comment]
Thank you @lramos15!

**Comment by rzhao271** [comment]
I still see the diff editors remain open.

**Comment by lszomoru** [comment]
The first build that contains all the necessary fixes is: 

Version: 1.65.0-insider
Commit: 8440b8f47231147823ba9696913d642e5f2d9d58
Date: 2022-02-25T05:18:40.990Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0

**Comment by alexdima** [comment]
This worked for me today.

**Comment by rzhao271** [comment]
I added a new ipynb file and opened it from the SCM viewlet. The diff isn't using the diff editor, but I'm wondering whether that tab should also close when running the command?
![Screenshot of the new notebook opened from the SCM viewlet](https://user-images.githubusercontent.com/7199958/155743975-7f1f037c-91d6-4de7-b218-e0f14e887a51.PNG)

**Comment by lramos15** [comment]
@rzhao271 That's a bug I pushed a fix. Thanks!
