### ISSUE TITLE
Settings search box seems too wide

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#143700]
Testing #143138

It looks like the settings search box is now taking the full width of the search editor rather than being centred. This makes it seem too wide. For example, the number of settings found and the control for clearing the search area are way off to the right:

![image](https://user-images.githubusercontent.com/1704059/155305295-8ae98398-eb74-449a-aba3-ab3dc7d55ade.png)

Could the search box be positioned in the blank space to the right of the User/Workspace tabs? That way it could be centred and positioned directly above the settings editor.

@misolori - what do you think?

**Comment by rzhao271** [comment]
I increased the max width for the entire Settings editor so that it can take up more horizontal space for users on higher resolutions. I can see whether I can get the search container back to max 1200px wide though.

**Comment by rzhao271** [comment]
I can get the search box centered with a max width of 1200px.
Centering the search box on top of the settings tree container or to the right of the tabs is more difficult, considering how the table of contents is resizeable now, and how there could be more tabs if the user opens, for example, a multi-root workspace in a remote container.
Thoughts on how the following looks?

![Screenshot showing the search box going back to max 1200px wide](https://user-images.githubusercontent.com/7199958/155390468-83654cd4-aa50-4ed1-b40c-7e1deae7d3ac.PNG)

**Comment by misolori** [comment]
Maybe you can use media queries to target larger screens? I don't think we want to cap certain elements, it was more of the entire content area being too wide.
