### ISSUE TITLE
Low contrast in breakpoints line numbers in Light High Contrast

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#143742]
Testing #143425

<img width="323" alt="image" src="https://user-images.githubusercontent.com/5047891/155344438-2b6a716f-95cb-4605-a64a-8fb2452b213f.png">

**Comment by daviddossett** [comment]
It looks like this the opacity of the background and foreground of the badge are hardcoded here. @isidorn any suggestions on an override for HC modes?

Similar issue on the dark HC theme:

<img width="306" alt="CleanShot 2022-02-23 at 10 41 45@2x" src="https://user-images.githubusercontent.com/25163139/155385955-351f85b3-55aa-404a-b611-eb8de0063ea8.png">

https://github.com/microsoft/vscode/blob/e102191a6ffdc4bfc572c538913f292314092e48/src/vs/workbench/contrib/debug/browser/debugColors.ts#L128-L132

**Comment by isidorn** [comment]
@daviddossett I think for HC modes we should not apply the transparency. 
In code we could do that by checking above if the `theme` is highContrast, and only if not apply the transparency.

fyi @roblourens

**Comment by daviddossett** [comment]
Took this approach for now:

https://github.com/microsoft/vscode/blob/c223b04c93f450b51118a311cb8b95b9beabb7b6/src/vs/workbench/contrib/debug/browser/debugColors.ts#L184-L191
