### ISSUE TITLE
Issues with Sublime Text Keymap

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#14371]
Testing #14317

#### `+` is not a valid key code
Please see https://code.visualstudio.com/docs/customization/keybindings#_accepted-keys for a list of accepted key codes
![image](https://cloud.githubusercontent.com/assets/5047891/19679754/6abc963a-9aa3-11e6-960a-c181dddde74d.png)

#### `shift-tab` is not indenting in sublime
![image](https://cloud.githubusercontent.com/assets/5047891/19679498/47b8f8dc-9aa2-11e6-9591-f8cf202ef185.png)

#### `ctrl+shift+[` is bound to fold in Sublime (not to unfold)
![image](https://cloud.githubusercontent.com/assets/5047891/19679662/e721ca2a-9aa2-11e6-8c93-8d928e3efc72.png)
![image](https://cloud.githubusercontent.com/assets/5047891/19679670/f01881fa-9aa2-11e6-9631-8aca1acd7c59.png)

#### all fold level-related commands (`ctrl+k ctrl+number`)

**Comment by waderyan** [comment]
Migrated this to Sublime Text keybindings repo. https://github.com/Microsoft/vscode-sublime-keybindings/issues/17
