### ISSUE TITLE
Clarify how base URI is handled as folder

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#143717]
Testing #143647

```
If the `baseUri` is a directory, relative paths in the markdown are resolved relative to that directory:
```

This seems to be determined by whether the `baseUri` has a trailing slash or not but I was first expecting you to figure this out just by the path and maybe `fs.stat`. I would clarify the requirement for a trailing slash if the base URI is a folder.

**Comment by mjbvz** [comment]
No we don't want to actually hit the file system for this. I'll clarify that it's just about ending with `/`
