### ISSUE TITLE
When pasting a something followed by a trailing new line (this would make the feature annoying)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#143716]
Testing #143428

> When pasting a something followed by a trailing new line (this would make the feature annoying)

I still get a warning when I paste the following into `bash` on `macOS` which is multi-line but with a trailing new line:

```
asdaasdj
asdasd

```

![image](https://user-images.githubusercontent.com/900690/155314618-acf417ef-a6fd-48c6-843f-2e3e898a3f5b.png)

**Comment by Tyriar** [comment]
This is the feature working as designed, the setting could be a number but I think that needlessly over complicates things when you're probably someone who should disable the feature outright if you do this a lot. Alternatively get used to hitting enter after pasting.

**Comment by bpasero** [comment]
Reading the test description I had expected that a string that I paste that has a trailing new line will not bring up the dialog.

**Comment by Tyriar** [comment]
Oh I'll fix that up, it's just a special case for pasting a single line followed by a new line as that's essentially a single line.
