### ISSUE TITLE
Terminal: Dropdown popup doesn't always work

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#143703]
Testing #143433

1. Enable `terminal.integrated.shellIntegration.enabled`
2. Run any command in the terminal
3. Click the decoration, popup menu comes up
4. Resize the terminal
5. Click the decoration again

🐛 Popup menu doesn't come up

**Comment by Tyriar** [comment]
Can repro

![Recording 2022-02-23 at 07 58 48](https://user-images.githubusercontent.com/2193314/155356979-d0aed333-112d-4e2d-8445-32c45a368b8e.gif)

**Comment by Tyriar** [comment]
Actually this appears to be fixed in main now, repro was easy in insiders and can no longer make it happen in oss.
