### ISSUE TITLE
Powershell 7 should automatically be detected by terminal profiles

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#143773]
1. Have your SSD fail and install a clean Windows 11
2. Install Powershell 7.2 via its `.msi`
3. Expect that it's available in the list of terminal profiles, but it's not 🐛

**Comment by connor4312** [comment]
Huh, maybe this works? I restarted Insiders for updates and got Powershell 7. 🤷

**Comment by Tyriar** [comment]
fyi @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
Maybe an environment variable issue? Did you install PowerShell before opening vscode?
