### ISSUE TITLE
Inconsistent layout icon size

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#143787]
Testing #143581

<img width="145" alt="image" src="https://user-images.githubusercontent.com/876920/155382912-39d1d82b-3481-4968-a90b-a76e2f656dbd.png">

The last icon is larger than the first three. It feels larger than any toolbar icon we have in the workbench.

**Comment by misolori** [comment]
Made the icon smaller, will keep gauging feedback if the icons needs to be updated

<img width="177" alt="CleanShot 2022-02-23 at 14 27 05@2x" src="https://user-images.githubusercontent.com/35271042/155419822-9191f597-f607-4e24-89da-a60ccf6f38ea.png">

**Comment by daviddossett** [comment]
Looking good 👍
