### ISSUE TITLE
Customize layout picker is sluggish  

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#143785]
Testing #143581

![Recording 2022-02-23 at 10 18 18](https://user-images.githubusercontent.com/876920/155382416-537b25e2-8e13-4c61-aac5-21ccdfd15eab.gif)

It seems that we would change the layout first and then update the checkmark, which makes it sluggish, especially when we are clicking fast to experiment. Maybe we can

* Update the checkmark first
* Trigger layout update
* If users click on another layout, cancel the previous one, update the checkmark immediately, trigger new layout update

**Comment by benibenj** [comment]
It's actually not to bad and in this case you are actively trying to break it. Closing for now
