### ISSUE TITLE
Terminal command decorations stop working when zoom level is increased

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#143783]
Testing #143433

1. Run a few commands with shell integration enabled
2. Decorations work (display popup on click, etc)
3. Ctrl + to zoom
4. :bug: decorations stop working (they do nothing when clicked) and also no longer render next to the command they were associated with, e.g. the default decoration in the screenshot below which renders at the bottom of the terminal area:
![image](https://user-images.githubusercontent.com/30305945/155381755-9d171cda-2296-4123-b7d4-48ebb906e07b.png)

**Comment by meganrogge** [comment]
Good catch - the context menus don't work for decorations rendered prior to the zoom.

As for the other part - on mac for me, the decorations are rendered properly thereafter and the menus work.
![Recording 2022-02-23 at 13 44 13](https://user-images.githubusercontent.com/29464607/155396033-f9f29234-0cfa-461e-9cce-a195f089ad20.gif)

**Comment by meganrogge** [comment]
related #143703

**Comment by meganrogge** [comment]
can't repro this in insider's
