### ISSUE TITLE
Highlights not showing up at all

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#143796]
Testing #143553

I believe this text should highlight?

```
if (variable_א || variable_ב || vаriable_ג) {
    admin = true;
}
```

But it doesn't? It works in stable but not in insiders.

**Comment by hediet** [comment]
Contextual unicode highlighting would previously allow this and highlight nothing - the rationale was that `ג` would already indicate that something weird is going on.

I tweaked the algorithm to highlight those characters in any case if the word has at least one ASCII character.
