### ISSUE TITLE
Lag in rendering walkthroughs

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#143777]
Version: 1.65.0-insider (Universal)
Commit: 32456dc9e7d3194a94dd3ee0322ccf47e461d09c
Date: 2022-02-23T05:27:54.628Z
Electron: 16.0.9
Chromium: 96.0.4664.174
Node.js: 16.9.1
V8: 9.6.180.23-electron.0
OS: Darwin x64 21.3.0

On new windows I was used to having no walkthroughs and my recents on the right. I believe because some walkthroughs updated or something happened I get the walkthroughs again but there's a lag so I end up misclicking into a walkthrough often. Also the lag is quite noticeable.

![Recording 2022-02-23 at 09 49 44](https://user-images.githubusercontent.com/12758612/155377698-98d3f70d-64ad-4f82-8bff-8796e627fa0e.gif)

**Comment by JacksonKearl** [comment]
The idea here is you meant to click into a recent entry but instead hit a walkthrough?

**Comment by tanhakabir** [comment]
@JacksonKearl yeah exactly but mostly because of the visual lag

**Comment by lramos15** [comment]
@tanhakabir Do you still see this, I can't seem to reproduce on my mac

**Comment by tanhakabir** [comment]
I don't think I do anymore! I'll recreate issue if I do see it
