### ISSUE TITLE
Glitched rendering with some output

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#143764]
Testing #143612

Using the following code:

```ts
const channel2 = vscode.window.createOutputChannel('Test C++ channel', 'cpp');
for (let i = 0; i < 5000; i++) {
	channel2.append('for (size_t i = 0; i < 5000; i++');
	channel2.append(') {');
	channel2.append('\n\tstd::cout << test(2) << std::endl;\n');
	channel2.append(')\n');
}
```
I get the output console highlighting and scrollbar to glitch:

![Screencap](https://user-images.githubusercontent.com/7199958/155369555-befee99e-f7db-4a35-b261-7eeb57869d68.gif)

**Comment by sandy081** [comment]
Output channel uses editor underneath. Hence assigning to @hediet / @alexdima . 

Please let me know if there is something output channel has to do while creating the editor.

**Comment by hediet** [comment]
I also cannot reproduce.

**Comment by rzhao271** [comment]
I can still sometimes repro it, but it's flaky. Considering how it takes long inputs to even repro, I'll take another look at this next week.
Another step might be to switch between the different output views.

**Comment by alexdima** [comment]
@rzhao271 Does this reproduce after disabling all other extensions?

**Comment by rzhao271** [comment]
Yep it does, forgot to mention that earlier, sorry.

**Comment by rzhao271** [comment]
I can still reproduce the issue.
But, considering how one essentially has to spam the output channel to get there in the first place, I'd rather wait to see whether an "actual" extension actually hits this problem before re-opening or looking more into this issue.

**Comment by alexdima** [comment]
@rzhao271 Does this happen 100% consistently for you? How about if you use a different language, like `css`? I wouldn't want to close this without understanding the root problem.

**Comment by rzhao271** [comment]
For me, with that output, the scrollbar ends up glitching very consistently but I'm not sure if it's 100% of the time.
Here's another case that's failing for me:

```ts
export async function activate(context: vscode.ExtensionContext) {
	vscode.window.showInformationMessage('Congratulations, your extension "exturl2" is now active!');

	const channel2 = vscode.window.createOutputChannel('Test C++ channel', 'css');
	for (let i = 0; i < 5000; i++) {
		channel2.append('.myclass {');
		channel2.append('\n\toverflow-x:')
		channel2.append(' hidden;\n')
		channel2.append('\n');
	}
}
```

In this case, the scrollbar doesn't even seem to render in that viewlet.
It might have to do with the content being invalid. If I make it print closing braces as well, i.e. `channel2.append('}\n');`, it seems to work again.

**Comment by alexdima** [comment]
@rzhao271 We need to screenshare to figure this one out. I have just tried again and I still cannot reproduce. 🤷 Just as a last resort, does this reproduce with a fresh user data dir?

**Comment by rzhao271** [comment]
The issue reproduces for me with a fresh user data dir.
However, something I noticed is that in the problems view, I get a lot of errors.
But, when I click into the problems view, the errors suddenly go away, maybe because the output view got unloaded.

### The good case (50 repetitions of the buggy CSS code)

There is a scrollbar, and the problems view shows a small number (fewer than 50 problems)
![css-50](https://user-images.githubusercontent.com/7199958/159374715-54507fe1-fcc8-4222-aaaf-355f00f5b9a1.PNG)

### The bad case (5000 repetitions of the buggy CSS code)

The output panel does not load properly. The problems view shows a large number (over 1000 problems)
![css-5000](https://user-images.githubusercontent.com/7199958/159374713-50d70bce-8b87-4671-be81-cdafb661e982.PNG)

**Comment by panoply** [comment]
For anyone getting here and unsure on how to leverage this great capability. You can extend upon the built in grammars of the vscode which uses a scope name of `text.log` or for the defaults you can simply infer the `log` language id name:

```ts
const output =  window.createOutputChannel('Liquid', 'log');
``` 

For those who want customize the, just include the grammars and apply your own patterns. 

```json
{
  "name": "Your Log",
  "scopeName": "your.log",
  "patterns": [
    {
      "include": "text.log"
    }
  ]
}
```
From here contribute the language. Happy coding.

**Comment by alexdima** [comment]
@rzhao271 I tried again to reproduce, but still no luck. Does this still reproduce for you?

**Comment by rzhao271** [comment]
Seems to be fixed now :tada:
