### ISSUE TITLE
Terminal scroll commands on OS X should be preceded with Cmd

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#14370]
#13440

Terminal scroll commands on OS X should be preceded with <kbd>Cmd</kbd>. <kbd>Home</kbd> and <kbd>End</kbd> should put the cursor at the beginning and end of the input line.

**Comment by joaomoreno** [comment]
These user keybindings give me the expected behaviour:

```json
,
	{
		"key": "cmd+end",
		"command": "workbench.action.terminal.scrollToBottom",
		"when": "terminalFocus"
	},
	{
		"key": "cmd+home",
		"command": "workbench.action.terminal.scrollToTop",
		"when": "terminalFocus"
	},
	{
		"key": "end",
		"when": "terminalFocus"
	},
	{
		"key": "home",
		"when": "terminalFocus"
	}
```

**Comment by Tyriar** [comment]
I have to use fn+left/right in the default terminal. I'm assuming this is home and end. I do notice though that cmd+fn+left/right is also bound via the VIew menu. As a non-Mac use I'll go with what you think, please confirm :smiley:

**Comment by joaomoreno** [comment]
I also have to use Fn. 👍 The keybindings that I provided in the previous comment make it behave like in iTerm.

**Comment by Tyriar** [comment]
Scroll to top and scroll to bottom are cmd+home/end in the menu (Terminal v2.7). iTerm is a custom terminal right? It might make sense to use keybindings for that if they improve upon it (and allow go to start/end of prompt).
