### ISSUE TITLE
Compile errors when setting engines.vscode to *

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#14378]
Testing #14290

* open your extensions `package.json` file
* change the `engine.vscode` property to `*`
* run `npm run postinstall` (assuming you have the `vscode` module as dev-dependency)

Import references to `'vscode'` will have errors:

![image](https://cloud.githubusercontent.com/assets/22350/19680182/0002f49a-9aa5-11e6-8cd2-6b0e6320f2c7.png)

**Comment by jrieken** [comment]
We should add a marker after the module declaration such that it doesn't get removed by older versions of the node module

**Comment by jrieken** [comment]
We will add this to the release notes

**Comment by jrieken** [comment]
release noted in https://github.com/Microsoft/vscode-docs/commit/fd47d661fa748f7c2e54b764207013bf5346be5d

**Comment by bpasero** [comment]
I added a link to http://code.visualstudio.com/updates#_authoring-in-typescript in the release notes.
