### ISSUE TITLE
Documentation for languageId can be more descriptive

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#143779]
Testing #143612

The current docstring for the languageId parameter is:
`@param languageId — The identifier of the language associated with the channel.`

It should also include the fact that it allows output that matches that language to have syntax highlighting.

**Comment by sandy081** [comment]
There are various other features which can be enabled with language id and not just syntax highlighting. This is very similar to the language id associated to a text document. A visible or active output channel is also made accessible as a text document via visible or active text editors API. Updated the documentation to include this information.
