### ISSUE TITLE
Support shell integration on WSL in a local window

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#143761]
A profile to get it kind of working, the positioning of the commands and exit codes are broken for me though:

```
    "Debian (WSL)+": {
      "path": "C:\\WINDOWS\\System32\\wsl.exe",
      "args": ["-d", "Debian", "--", "bash", "--init-file", "/mnt/c/Github/microsoft/vscode/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh"]
    }
```

**Comment by Tyriar** [comment]
I think it doesn't work right now because even on WSL, conpty doesn't order the sequences right:

![image](https://user-images.githubusercontent.com/2193314/156233765-358dafec-adad-4f17-a3f2-56c83076dae5.png)

So the command never gets filled in:

![image](https://user-images.githubusercontent.com/2193314/156233900-1417b2ff-08e7-4591-81a4-e7dd1bacbe47.png)

I think there are better areas to focus than this and git bash currently as fixing this is working around how conpty does things once again like we did with pwsh which took some time to get right.

**Comment by meganrogge** [comment]
I think we should close this for now and can revisit if there are requests
