### ISSUE TITLE
Shell integration: suggestion for message tweak

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#143713]
![image](https://user-images.githubusercontent.com/6726799/155313018-e386c332-3043-410c-a43d-1a7b1dc883e4.png)

Maybe align the shell integration activation message appearance with how session contents restore gets reported.

Also, perhaps drop the exclamation mark.

**Comment by Tyriar** [comment]
@JacksonKearl FYI multiple `/assign` commands may not be working as expected? Is `/assign @a,@b` or something the right syntax?

**Comment by Tyriar** [comment]
The session restore one is really loud to make it very clear about the separation in the buffer. I'll drop the exclamation mark.
