### ISSUE TITLE
SCM commit message should say main instead of master

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#143750]
Testing #143461

![Screen Shot 2022-02-23 at 10 01 08 AM](https://user-images.githubusercontent.com/29464607/155357475-e44c4428-27ac-4788-b35a-eb8f0d8ad0f4.png)

**Comment by joyceerhl** [comment]
@meganrogge Which branch are you on? That message should reflect what the branch/tag picker in the bottom left says, e.g. for the microsoft/vscode repo:

![image](https://user-images.githubusercontent.com/30305945/155367661-7c7b41cb-12d8-4dde-81a8-f986a2ee3174.png)

If the branch you are on is `main` but the validation message refers to `master`, can you share a link to the vscode.dev repo and branch that you are seeing this on?
