### ISSUE TITLE
Settings TOC needs more padding

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#143771]
Can we add some additional padding to the top of the TOC, to match the container on the right?

![CleanShot 2022-02-23 at 09 41 13@2x](https://user-images.githubusercontent.com/35271042/155376087-3c3fbd46-7cde-442f-97c1-5638967ae845.png)

**Comment by rzhao271** [comment]
Good idea. Assigning to March, though, because when I added padding earlier, the end of the list got cut off, and I couldn't find a quick workaround.

**Comment by rzhao271** [comment]
This one's tough. A few attempts:
- Increasing the padding and doing nothing else results in the last entry being cut off.
- Increasing the padding and manually making the lists render at different heights results in the last entry showing, but the scrollbar not touching the bottom when the user scrolls to the bottom of the list.
- Creating a new element to stick above the scrollable list results in the shadow being pushed down. We want to keep the shadow at the top edge of the container.
- Adding a fake settings group with no settings to try and get the list to add a spacer element does nothing, because a settings group needs settings to show up in the ToC.

**Comment by misolori** [comment]
@roblourens how did we get the padding to work before? Maybe we can ask the list widget to provide a padding param to adjust the height?

**Comment by rzhao271** [comment]
Before, we weren't using a splitview. The shadow was lower, and there was no sash.
If we add padding elements above the splitview views right now, we will have the sash and the shadow intersect again in a + shape rather than a T shape.

**Comment by roblourens** [comment]
Do you want the padding inside the list view, or outside of it?

If you want it inside the listview, you can add it to an element and include this in the size returned from `getHeight`. If you just put css padding inside the list by itself, that will mess the list up

**Comment by rzhao271** [comment]
I would like the padding to be inside the listview. Adding the padding to the element results in a different focus border shape for that element.

**Comment by roblourens** [comment]
What if you use a margin-top on the first element instead of padding?

**Comment by misolori** [comment]
I wouldn't mind it if the list had that top margin, I still think the line connecting to the user/workspace heading gives the impression that the top is also resizable (like editor grids) so staying away from that as much as possible would be preferred:

<img width="855" alt="CleanShot 2022-03-14 at 14 03 38@2x" src="https://user-images.githubusercontent.com/35271042/158260995-3025af7e-0148-46b9-913f-139b09529944.png">

<img width="851" alt="CleanShot 2022-03-14 at 14 02 34@2x" src="https://user-images.githubusercontent.com/35271042/158260947-b0712ab9-43e7-4679-9dc3-116a74f3e1e4.png">

**Comment by rzhao271** [comment]
Verification steps:
1. The Settings editor should look closer to https://github.com/microsoft/vscode/issues/143771#issuecomment-1067285118. In other words, there should be a gap between the vertical splitview sash and the horizontal tabs/scope widget underline. When one scrolls down on either side, horizontal shadows should appear below the horizontal underline.

**Comment by Tyriar** [comment]
Verified at described, not sure it looks better now than before though because the shadow no longer aligns with the horizontal bar above.
