### ISSUE TITLE
cause macbook restart

### ISSUE THREAD

**Issue by Phoutthalak** [microsoft/vscode#143861]
Issue Type: <b>Bug</b>

when run 
nom run build my macbook pro restarted 

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|42, 24, 10|
|Memory (System)|12.00GB (1.91GB free)|
|Process Argv|--crash-reporter-id d7cccb53-c202-42ee-ae61-6f49f0c319e9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
project-manager|ale|12.5.0
emmet-jss|car|1.0.0
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
gitignore|cod|0.7.0
bracket-pair-colorizer|Coe|1.0.62
git-extension-pack|don|0.1.3
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|11.7.0
vscode-npm-script|eg2|0.3.24
auto-import|Ele|0.4.4
vsc-material-theme|Equ|33.1.2
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|1.2.2
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.3.0
mithril-emmet|Fal|0.7.6
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
csharp|ms-|1.24.0
cpptools|ms-|1.8.4
vsliveshare|ms-|1.0.5330
debugger-for-chrome|msj|4.13.0
vscode-extension-auto-import|Nuc|1.4.3
material-icon-theme|PKi|4.13.0
LiveServer|rit|5.7.4
autoimport|ste|1.5.4
vscodeintellicode|Vis|1.2.17
vscode-icons|vsc|11.10.0
gitblame|wad|8.1.0
change-case|wma|1.0.0
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30442554
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc008:30440022
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343
vscaat:30438848

```

</details>

**Comment by chrmarti** [comment]
Please provide detailed steps on how to reproduce the issue.
