### ISSUE TITLE
Unity - New InputSystem Namespace

### ISSUE THREAD

**Issue by GvNiK** [microsoft/vscode#143896]
Visual  Code suddenly stopped recognising Unity's new InputSystem namepsace. When I type the namespace "using UnityEngine.InputSystem"; it does not recognise it.
Till yesterday it was recognising. But from today it stopped recognising.  I creaeted 4-5 new projects, serached on Google and YoutTube, yet still getting the same issue.
Please patch this issue. It's important. Without that I cannot do anything.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including your version, platform, and what you think changed from when it was working.
