### ISSUE TITLE
Some extensions not found

### ISSUE THREAD

**Issue by nclarius** [microsoft/vscode#143890]
Issue Type: <b>Bug</b>

### Steps to reproduce
1. Search for `C++` or `QML` in extensions.
2. Run Ctrl+P with `ext install ms-vscode.cpptools`  or `ext install felgo.felgo`.

### Expected result
Extensions "C/C++" and "QML Syntax/Tools" are found.

### Actual result
The extensions are not found.

### Additional information
Installing these extensions from a .vsix file downloaded from the browser works.
Other extensions like "Bash ID", "ShellCheck", "Atom One Dark" theme are found.

### Systen information
VS Code version: Code - OSS 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-10T19:07:05.314Z)
OS version: Linux x64 5.16.10-arch1-1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1510)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 2|
|Memory (System)|15.52GB (5.15GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
I think Arch Linux builds of VS Code use [Open VSX Registry](https://open-vsx.org/) for their extension library instead of Microsoft's [Marketplace](https://marketplace.visualstudio.com).

Do the extensions you are looking for show up on Open VSX?

**Comment by nclarius** [comment]
No, I can not find them there, so that appears to be the problem. I'll look into the options layed out in the [Arch Wiki](https://wiki.archlinux.org/title/Visual_Studio_Code#Extensions_support). Thanks for figuring out where the issue comes from.

**Comment by gjsjohnmurray** [comment]
Please close the issue here.
