### ISSUE TITLE
Command decorations after starting are moving up incorrectly

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#143894]
Seeing this in today's build:

![image](https://user-images.githubusercontent.com/2193314/155560216-f0824b0e-ef85-4d38-8b5d-4b4f63394680.png)

Might be related to the fix https://github.com/microsoft/vscode/issues/143798

**Comment by meganrogge** [comment]
Weird that it looks like it reproduces inconsistently. I wonder if that always happens following one of the "empty commands"

**Comment by Tyriar** [comment]
The change I had in mind isn't working as I thought, this is too risky for Feb.

**Comment by Tyriar** [comment]
I haven't seen this happen for some time.

**Comment by Tyriar** [comment]
I have seen this actually

**Comment by Tyriar** [comment]
One(?) problem case, notice B (command start) happens before the new line of the prompt:

![image](https://user-images.githubusercontent.com/2193314/158876199-2972fea9-abf2-4c14-9eb0-0b709b6d920e.png)

**Comment by Tyriar** [comment]
Other problem case:

![image](https://user-images.githubusercontent.com/2193314/158877318-f8c104d2-9d6c-4266-8a29-64a14fa46139.png)

Notice that a cursor move event is happening on line 50 which is the line above the prompt:

![image](https://user-images.githubusercontent.com/2193314/158877535-bce96c3c-94cf-45fa-9b9d-70e64bf942ad.png)
