### ISSUE TITLE
Cmd + C without selection copies <empty> to clipboard

### ISSUE THREAD

**Issue by djc** [microsoft/vscode#143866]
Issue Type: <b>Bug</b>

1. Select some text in an editor pane
2. Use `Cmd + C` to copy
3. Make sure no text is selected
4. Hit `Cmd + C` again as if by accident
5. Hit `Cmd + V` to paste the text copied in step 2

In other apps on macOS, this would paste the text from step 2. In VS Code, this pastes nothing (that is, it appears that the empty string was copied to the clipboard in step 4). I'm pretty sure the same behavior would be expected on other platforms, though I have not tested it.

This is a long-standing issue that has been around for at least a year.

VS Code version: Code 1.64.2 (Universal) (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (25.41GB free)|
|Process Argv|--crash-reporter-id 340097ba-bfe5-4da5-b466-1b1cdc0f41f6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.3.0
copilot|Git|1.7.5118
terraform|has|2.19.0
rust-analyzer|mat|0.2.948
crates|ser|0.5.10
vscode-stylelint|sty|1.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30440023
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343

```

</details>

**Comment by alexdima** [comment]
It looks like you would like to configure `"editor.emptySelectionClipboard": false`

**Comment by djc** [comment]
@alexdima actually I would like to challenge that `true` is a good default for that setting.

**Comment by alexdima** [comment]
I have to be honest, unless there is some huge amount of feedback about this, we will not change the default. There is no upside to change this default after more than 6 years and risk breaking everyone that today relies on it.
