### ISSUE TITLE
Open in integrated terminal not working

### ISSUE THREAD

**Issue by alinz07** [microsoft/vscode#143848]
Issue Type: <b>Bug</b>

When i right click on a directory/file and select open in integrated terminal, instead the terminal opens in my computers root directory. I've ensured that there is no terminal.integrated:cwd, it is blank. I even tried downloading the terminal here extension, but every terminal only opens at my root directory. There are no vscode updates avail. I run on windows 11.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (9.40GB free)|
|Process Argv|--crash-reporter-id 6881ff56-3a9f-4b19-aa5b-f712b8f275ce|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
heroku-command|pko|0.0.8
LiveServer|rit|5.7.4
html5-boilerplate|sid|1.1.1
vscode-zipexplorer|sle|0.3.1
open-in-browser|tec|2.0.0
pdf|tom|1.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30442554
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc008:30440022
pythonvspyt640:30442238
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by meganrogge** [comment]
This is working for me.

**Comment by alinz07** [comment]
![image](https://user-images.githubusercontent.com/93682942/155630044-d9b5e6d6-4477-4d9a-bb0d-8a35bb87be63.png)
![image](https://user-images.githubusercontent.com/93682942/155630077-cd5d8501-1aab-442f-8352-abaa1dff3d11.png)

**Comment by alinz07** [comment]
I changed terminal > integrated > default profile : windows setting to powershell instead of git bash and now I can open in integrated terminal. Is there a way I can use git bash instead and have it open in integrated terminal? Or am I misunderstanding something about the nature of the terminal?

**Comment by meganrogge** [comment]
Thanks for the info. We'll see if we can repro the issue on windows. It should work for git bash

**Comment by meganrogge** [comment]
Are there any errors in the dev tools console when you try to do that with git bash as the default?

**Comment by alinz07** [comment]
Thank you for your prompt help. I am an amateur coder, so I apologize if this isn't what you're looking for, but I searched developer tools in the command palette and found the console, I believe. When I open vs code with powershell as the terminal.integrated.default profile.windows option, I get this in the console: 
![image](https://user-images.githubusercontent.com/93682942/155649170-0dc63985-5059-4666-ae19-b11f7ca440c9.png)
When I right click a file and attempt to open with integrated terminal, I get the following picture, which I believe matches the first. Again this is using powershell and the terminal will correctly open at the file location: 
![image](https://user-images.githubusercontent.com/93682942/155649400-60728f22-16f4-4f9f-8539-24603c3faa70.png)
Then I changed the terminal.integrated.default profile.windows option to git bash, closed vscode, reopened vscode, opened the dev tools and I get this picture: 
![image](https://user-images.githubusercontent.com/93682942/155649482-390605e5-c4e8-4dce-9b0a-65507cf5cd4c.png)
Then I right click a file and attempt to open with integrated terminal, I get the following picture: 
![image](https://user-images.githubusercontent.com/93682942/155649679-8cb10ef1-1a1b-4efb-a8f4-a05f38094673.png)
 The only difference I spot is another instance of the message "WARN Settings pattern "keyboard.*" doesn't match any settings" log.ts.307 ( the same line at the top when I started vscode), and the terminal will not open at the correct file location, only the root directory.

**Comment by Tyriar** [comment]
Git bash works fine for me, could you try updating git?

**Comment by alinz07** [comment]
Without re-installing bash, I found the solution:
My .bashrc file had one line of code "cd C/users/gener". We were doing a git demo to show how to run shell scripts and I hashed this line out. Now my git bash terminal correctly opens to the project from which I select 'Open in integrated terminal."
