### ISSUE TITLE
Add note that layout control does not currently support MacOS

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#143820]
Testing #143581

I don't think the `workbench.experimental.layoutControl.enabled` setting currently works on MacOS since custom title bars are not supported. We should note this in the setting

Also in the setting description, `custom title bar` should link to the `window.titleBarStyle` setting just to make it clear what this is talking about

**Comment by sbatten** [comment]
@mjbvz the custom title bar is the default experience in macos (when using a built product)

**Comment by sbatten** [comment]
updated with markdown reference to title bar style setting

**Comment by mjbvz** [comment]
@sbatten Any idea why I can't get these new controls to show on MacOS

![Screen Shot 2022-02-23 at 2 43 08 PM](https://user-images.githubusercontent.com/12821956/155421780-47d6cf7f-a514-47e4-8479-43e1af61eefb.png)

They worked fine on windows for me but don't show on MacOS

**Comment by mjbvz** [comment]
Oh it's the `window: native full screen` option. This disables the custom title bar:

https://github.com/microsoft/vscode/blob/ef70f99af7c90bb37f6dbb797c36de76a51ba73b/src/vs/platform/window/common/window.ts#L150

I would never have found this without looking through the code though
