### ISSUE TITLE
Comments in view don't persist in bottom panel 

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#143831]
Testing #143545

Experiencing a weird issue where I see comments in the side panel, but when I drag the comments view into the bottom panel the comments disappear and I no longer see them when I drag the view back to the side panel. Tried this with multiple repos! Here's an example: https://github.com/sana-ajani/taskrunner-code/pull/33

![Recording 2022-02-23 at 18 15 00](https://user-images.githubusercontent.com/9721254/155425487-5d4042da-3342-48b3-9078-9e7f3e48c485.gif)
.

**Comment by alexr00** [comment]
Thanks for catching!
