### ISSUE TITLE
High Contrast error/warnings/info colors

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#143898]
Was looking at deprecated settings #143897 and noticed that our HC themes don't consistently show error/warning/info colors and maybe we should figure out which one we want to show.

## HC Dark
<img width="585" alt="CleanShot 2022-02-24 at 08 46 04@2x" src="https://user-images.githubusercontent.com/35271042/155569017-fc4f4d4f-5d62-4452-8cfb-d6efc8a2602d.png">
<img width="486" alt="CleanShot 2022-02-24 at 08 46 33@2x" src="https://user-images.githubusercontent.com/35271042/155569095-d2b253ad-85a0-4135-9c42-ad4ab44169c0.png">

## HC Light
<img width="581" alt="CleanShot 2022-02-24 at 08 46 48@2x" src="https://user-images.githubusercontent.com/35271042/155569129-250feff9-013e-408f-9a33-e1536e762f0a.png">
<img width="480" alt="CleanShot 2022-02-24 at 08 47 00@2x" src="https://user-images.githubusercontent.com/35271042/155569169-e2d09647-ae1e-49c5-9e3e-6ea0c8a7b04f.png">

## Other HC Themes

<img width="567" alt="CleanShot 2022-02-24 at 08 47 53@2x" src="https://user-images.githubusercontent.com/35271042/155569352-7514ed74-556f-4c65-b26f-b07b87282e18.png">

<img width="479" alt="CleanShot 2022-02-24 at 08 48 11@2x" src="https://user-images.githubusercontent.com/35271042/155569365-73d49217-f76c-45f7-84db-e6a9a8134a18.png">

<img width="490" alt="CleanShot 2022-02-24 at 08 51 59@2x" src="https://user-images.githubusercontent.com/35271042/155570017-15becdfd-a8de-434a-9302-4cd0b6e63459.png">

<img width="478" alt="CleanShot 2022-02-24 at 08 52 11@2x" src="https://user-images.githubusercontent.com/35271042/155570054-9f3cbb19-1ddb-4821-a94d-2424df0198a7.png">

**Comment by daviddossett** [comment]
It looks like we've set the `error` and `warning` base foreground tokens to be null in hc themes:

https://github.com/microsoft/vscode/blob/30e1c0cfdaa3d1b3e7d4a0141bb8b0d3bcb51887/src/vs/platform/theme/common/colorRegistry.ts#L271-L280

Any idea why that would be? In any case, it looks like the notifications specifically aren't picking up the overrides, hence the info icon rendering `#3794FF` and the other two seeming to default to some base foreground color higher up the hierarchy. Probably something like `editor-foreground` or whatever.

**Comment by daviddossett** [comment]
Disregard—saw that we have specific tokens for notifications.

**Comment by daviddossett** [comment]
Updated `editorWarningForeground` and `editorErrorForeground` to use actual values instead of `null` for both HC themes. Here's how it looks for the notifications icon that inherit that change:

<img width="535" alt="CleanShot 2022-03-30 at 10 24 34@2x" src="https://user-images.githubusercontent.com/25163139/160894985-9dfbfc4a-9f93-4f59-b956-fb147f991bd2.png">

<img width="517" alt="CleanShot 2022-03-30 at 10 21 41@2x" src="https://user-images.githubusercontent.com/25163139/160894647-f2866905-4040-4cf9-a311-e57ac31d1dd1.png">

@misolori I'm not sure how to view a deprecated settings but I'll check this in and can tune those up as well if needed.

**Comment by rzhao271** [comment]
The colours of the error and warning icons look different to me on the high contrast dark theme:
![A screenshot showing the icon colours on the high contrast dark theme](https://user-images.githubusercontent.com/7199958/165584314-f09454ba-a1d5-4502-8ebb-e71a3a9088b1.PNG)

**Comment by daviddossett** [comment]
Will take a look

**Comment by rzhao271** [comment]
Light high contrast theme LGTM. For both themes, the error icon for the deprecated settings uses the same colour as the error icon for the notification. 

One can get a deprecated setting to show up by adding a deprecationMessage to an existing setting in the extension's package.json file (assuming that extension provides settings), or by finding a setting with that field already included, and then modifying that setting in the settings.json file. After navigating back to the Settings UI and searching for the setting, it should show up with the deprecation error message.
