### ISSUE TITLE
Completion edits are applied inconsistently when additionalTextEdits and textEdit start at the same offset

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#143888]
This simple completion item provider simulates inserting an item that requires an `import` statement. Add this to an extension, open a _completely empty_ text file, start typing "MyClass" so that completion is invoked after the `M` is typed and then accept the suggestion.

```ts
export function activate(context: vscode.ExtensionContext) {
	context.subscriptions.push(vscode.languages.registerCompletionItemProvider({ pattern: '**/*.txt' }, {
		provideCompletionItems: (document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext) => {
			const position0 = new vscode.Position(0, 0);
			const completion = new vscode.CompletionItem(
				'MyClassName',
			);
			completion.insertText = 'MyClassName';
			// Replace text from start to where caret is
			completion.range = new vscode.Range(position0, position);
			completion.additionalTextEdits = [
				// Insert import at start of doc
				new vscode.TextEdit(new vscode.Range(position0, position0), 'import "my_class.txt";\n')
			];
			return [completion];
		}
	}));
}
```

The result is that both edits are applied. The main edit is inserted at 0,0 and then the import is inserted before it. I believe, this is expected behaviour:

![Feb-24-2022 13-52-43](https://user-images.githubusercontent.com/1078012/155537037-d900429f-151e-4f12-88e5-b8dc02b4d3e1.gif)

However, instead of typing, if you just invoke completion immediately and select the item without typing anything, then the `import` is never inserted:

![Feb-24-2022 13-52-51](https://user-images.githubusercontent.com/1078012/155537059-0f5797a4-0dae-4104-b138-e376d479bb4c.gif)

I don't think this is intended. To a user, there isn't really any difference between these operations.

**Comment by jrieken** [comment]
(https://github.com/microsoft/vscode/blob/261adce05c180fbe1802dd26d8d802c00bfedbe5/src/vscode-dts/vscode.d.ts#L4242-L4243)

**Comment by jrieken** [comment]
With overlapping and touching edits you are in `undefined`-land... I can see if this specific case can be tweaked tho

**Comment by DanTup** [comment]
> With overlapping and touching edits you are in `undefined`-land

Is it possible to make it explicitly defined? :) 

If it's not possible to make these consistent, could the docs be expanded to say _overlap or touch_ to make it really clear? If they can be made consistent, could the docs also make it clear which order they'll be applied in to avoid confusion? Thanks! :-)

**Comment by jrieken** [comment]
What seems to happen is that the texts from the additional edits is selected and later overtyped, so it is there for a few cycles and than gets overwritten by accident.

**Comment by jrieken** [comment]
I have pushed a change that fixes this but I need to validate that this is the right fix

**Comment by jrieken** [comment]
This was a good fix

**Comment by DanTup** [comment]
@jrieken awesome, thanks! Is it possible to update the docs/comment (which mention "overlapping" but not "touching" edits) about this behaviour. I think there's similar ambiguity around multiple insertions with the same offset in other places, like `WorkspaceEdit.insert`. It's really useful for the docs to be really explicit (especially since LSP tends to mirror this, where there are both multiple servers and multiple clients involved). Thanks!
