### ISSUE TITLE
Deprecated setting icon does not have correct color

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#143897]
Have a deprecated setting like `"audioCues.enabled": "on"` and see the message:

<img width="290" alt="CleanShot 2022-02-24 at 08 33 02@2x" src="https://user-images.githubusercontent.com/35271042/155566829-35bf1332-ff67-428c-a9ec-3650ae7f22f9.png">

We previously had the error icon colorized.

**Comment by misolori** [comment]
<img width="290" alt="CleanShot 2022-02-24 at 08 38 45@2x" src="https://user-images.githubusercontent.com/35271042/155567845-86904cc7-76a3-48d6-a216-e6c4a1cb8100.png">

**Comment by kimadeline** [comment]
Verified, although the markdown in the deprecation message doesn't render properly (see `audioCues.*`):

![image](https://user-images.githubusercontent.com/51720070/155613140-cbbc2473-1c72-4f38-a2e3-d4aaf915a67d.png)

**Comment by rzhao271** [comment]
I don't think the fix is in yet. The circled x icon is still not red.
The audioCues issue is a different issue. I can fix that one.

**Comment by joyceerhl** [comment]
Verified: 
![image](https://user-images.githubusercontent.com/30305945/155771243-44f3e67c-6c9d-4644-bc75-852265833b7c.png)
