### ISSUE TITLE
Customize layout visibility buttons should say what the buttons do instead of the current view state

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#143829]
Testing #143581

1. Open the 'customize layout' control
2. Hover over one of the visibility buttons for something like the side bar

**Bug**
If the side bar is visible, the hover will say `Side bar (visible)`. Instead I think the title should tell the user that clicking the button will hide the side bar

**Comment by sbatten** [comment]
@misolori do we have pre-existing guidelines for this?
