### ISSUE TITLE
Allow resetting layout in customize layout

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#143830]
Testing #143581

While experimenting with the 'customize layout' control, I switched my panel alignment but then wasn't sure what to reset it back to

Can we add a indicator that tells users what the default alignment is?

**Comment by sbatten** [comment]
I suppose this feedback should be applied to the other options as well. it isn't the only item with a default value, but I am also a little hesitant as it makes the experience somewhat noisy and the user can select whatever option they like the most. thoughts?

**Comment by mjbvz** [comment]
This was the only option that was confusing to me but I can see just adding a default label to one section would be a little weird

Another option is to add a `reset` entry inside `customize layout` that resets the entire layout. That is pretty much what I was wanted after experimenting with these options

**Comment by sbatten** [comment]
I think reset is quite interesting, I will update this as a feature request for that

**Comment by sbatten** [comment]
To verify:

1. Execute the "Customize Layout" action
2. Customize the layout
3. Click the reset icon in the top right of the quick pick

From the code, here is the list of stuff that I expect to be reset:
```ts
				// Reset all layout options
				resetSetting('workbench.activityBar.visible');
				resetSetting('workbench.sideBar.location');
				resetSetting('workbench.statusBar.visible');
				resetSetting('workbench.panel.defaultLocation');

				if (!isMacintosh || !isNative) {
					resetSetting('window.menuBarVisibility');
				}

				commandService.executeCommand('workbench.action.alignPanelCenter');

```
