### ISSUE TITLE
Current working-directory [grey-text] not always showing in the list of active terminals

### ISSUE THREAD

**Issue by drywolf** [microsoft/vscode#143841]
I usually have open multiple integrated zsh terminals at the same time.
The active folder-name of the directory I am in is then shown as grey text for each terminal in the list of active terminals.
This works very well, and helps me see what are the terminals that I have opened, and which one to click on if I need to work in a certain directory.

The Bug:
When I close vscode down (completely closed) ... and then reopen the workspace, it restores the list of terminals that were active at the time when vscode was closed. This works fine so far, all the terminals are there and are restored to the correct working-directories that they had before the shutdown.
The issue is, that the grey text, that indicates which terminal is at which directory, is then **no longer visible** ⚡. It does not matter what I tried, those terminals then will never show in which directory they are again.

Curiously enough, when I create a new terminal while the others are still open, then the grey text shows up for the newly created terminal. The "old ones" from before the vscode shutdown still will never show the grey working-directory text ever again.

In this screenshot you can see 5 terminals that are left over from before the vscode shutdown.
The last two terminals I opened after I reopened vscode, and only they correctly show the grey text, indicating their current working directory.

![image](https://user-images.githubusercontent.com/394294/155442760-ef69d66d-8c6b-4682-a595-761d4df540f5.png)

```
Version: 1.64.2 (Universal)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z (2 wks ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0
```

Thanks 🙏

**Comment by meganrogge** [comment]
Are you able to reproduce the issue in insider's? Very possible it's been fixed
