### ISSUE TITLE
(editor) Cursor should be moved to the Rename Symbol edit field

### ISSUE THREAD

**Issue by RaphTronic** [microsoft/vscode#143892]
Issue Type: <b>Feature Request</b>

When using Rename Symbol in the editor the cursor stays on the code line instead of moving to the symbal rename field. Forces to click in that box to change the name, instead of typing right away which is the intuitive thing to do. And typing right away overwrites the initial name in the actual code line, messing everything up.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by jrieken** [comment]
This doesn't reproduce for me... @RaphTronic How do you invoke rename, via the keybinding or via the context menu?

**Comment by RaphTronic** [comment]
Via context menu.
This seems to be intermittent. Has been bugging me for the last 2weeks but impossible to repro this morning (normal editing, during a run pause, during a run error, etc).
Seems to be an intermittent issue, like the non alphanumeric keys not working anymore in the editor after a run error (clicking on any menu makes them work again).
Ok, let's close. I'll reopen if I stumble on a way to repro some day.
Thanks.
