### ISSUE TITLE
Need to install updates every time I open VS code while switching on the computer

### ISSUE THREAD

**Issue by varshaneya-v** [microsoft/vscode#143882]
Issue Type: <b>Bug</b>

I am using VS code on Windows 10. VS code is asking me to install updates everyday I login to the machine though I had already installed them for the month. Though I have installed extensions like remote-ssh and pylance, they are not enabled automatically when I open VS code after logging in. I need to restart VS code and install the same updates daily to enable the extensions.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.67GB (5.46GB free)|
|Process Argv|--crash-reporter-id 371e886e-a16e-4563-a4b0-bcf5737b2398|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.79.105.22|
|OS|Linux x64 5.4.0-65-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz (80 x 2714)|
|Memory (System)|503.79GB (161.34GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.217.4
remote-ssh|ms-|0.74.0
remote-ssh-edit|ms-|0.74.0
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
cake-vscode|cak|2.0.0
vscode-markdownlint|Dav|0.46.0
vscode-docker|ms-|1.20.0
csharp|ms-|1.24.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.3
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
python|tht|0.2.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30429731
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc009:30440023
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343

```

</details>

**Comment by joaomoreno** [comment]
> install updates everyday I login to the machine

Can you show me a screenshot of that update prompt?

**Comment by varshaneya-v** [comment]
Every single day I login to the PC and open VS Code I get this notification to download update even though I have installed the update a day ago:

<img width="249" alt="image" src="https://user-images.githubusercontent.com/70888225/156696497-5c8c5628-3314-4dfe-89d5-7e28656dc2f1.png">

Once the update is downloaded, I am forced to install the update otherwise none of the installed VSCode extensions show up:

<img width="252" alt="vscodeError" src="https://user-images.githubusercontent.com/70888225/156696769-763c83e8-82a2-4a01-8127-47775db7294e.png">

**This happens every single day!** I dont understand if there is an update everyday or it is a bug.

**Comment by joaomoreno** [comment]
Can you uninstall and reinstall VS Code altogether? https://code.visualstudio.com/download

**Comment by varshaneya-v** [comment]
I uninstalled and reinstalled VS Code completely. The issue is not there now. We can close this.
