### ISSUE TITLE
Ctrl + alt keybindings should not be used by default under Windows

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#14389]
- VSCode Version: insiders
- OS Version: windows

Steps to Reproduce:

1.  Open vscode-insders, open console notice warning

![screen shot 2016-10-25 at 11 43 36](https://cloud.githubusercontent.com/assets/1926584/19681081/5d445038-9aa8-11e6-8ad0-209c389b9c88.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13567
