### ISSUE TITLE
Extension: Reload button jumps from index 1 to 2 in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14386]
Testing #14288

* have a disabled extension that also shows an update
* 
![image](https://cloud.githubusercontent.com/assets/900690/19680979/faa2a0b0-9aa7-11e6-98ba-48a12a25bcd1.png)
* click on enable

=> the reload button is now moved to the right

![image](https://cloud.githubusercontent.com/assets/900690/19680991/0589500a-9aa8-11e6-8f8b-27456ad5464b.png)

**Comment by ramya-rao-a** [comment]
This is a moot point now that we have Disable/Enable/Uninstall in the menu
