### ISSUE TITLE
Vscode not highlight all occurrences of cursor word

### ISSUE THREAD

**Issue by zxyzgt** [microsoft/vscode#143839]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: Windows 10

Steps to Reproduce:
VScode highlights/borders the cursor word for all occurrences except those appearing on the left side of the assignment symbol. I tried editor.wordHighlightBackground, editor.selectionHighlightBackground, editor.wordHighlightBorder or editor.selectionBackground under workbench.colorCustomizations, but no luck. They are highlighted by a default background color and override my colorCustomizations settings.
![image](https://user-images.githubusercontent.com/21346832/155440273-23b11b5e-0e8d-43c4-bbcd-4c8ecab14edf.png)

**Comment by alexdima** [comment]
@zxyzgt Semantic word highlighting has two variants, one regular (used for example when reading a variable) and one strong (used for example when writing to a variable). The colors are:
* `editor.wordHighlightBackground`
* `editor.wordHighlightBorder`
* `editor.wordHighlightStrongBackground`
* `editor.wordHighlightStrongBorder`

**Comment by alexdima** [comment]
@zxyzgt Semantic word highlighting has two variants, one regular (used for example when reading a variable) and one strong (used for example when writing to a variable). The colors are:
* `editor.wordHighlightBackground`
* `editor.wordHighlightBorder`
* `editor.wordHighlightStrongBackground`
* `editor.wordHighlightStrongBorder`

**Comment by alexdima** [comment]
@zxyzgt Semantic word highlighting has two variants, one regular (used for example when reading a variable) and one strong (used for example when writing to a variable). The colors are:
* `editor.wordHighlightBackground`
* `editor.wordHighlightBorder`
* `editor.wordHighlightStrongBackground`
* `editor.wordHighlightStrongBorder`

**Comment by zxyzgt** [comment]
@alexdima It works. Thank you!!
