### ISSUE TITLE
Don't remove not found files from recents

### ISSUE THREAD

**Issue by renyhp** [microsoft/vscode#143864]
When a file is not found, VSCode removes it from recents. It could be useful not to remove it, or at least to remember it so that, if it becomes available again, VSCode can show it again.

Use-case: you have a project in an external mount. If you don't have mounted the external filesystem and you open VSCode, the recents from that filesystem are gone, and you have to search and open them again from scratch.

**Comment by gjsjohnmurray** [comment]
This has been requested a few times over the years, but never gets beyond Backlog Candidate.

For example, #128107, #116880, #74350, #96474, #55160
