### ISSUE TITLE
Terminal: Running from recent command does not run from where it was previously run

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#143846]
Testing #143430

Run a command for dir1, run some other command, go to another directory, run the same command as in dir1. Now use run recent command and run the command from dir1. the directory is not switched.
![image](https://user-images.githubusercontent.com/3840081/155450960-ea748285-c588-4dec-8f14-09eb69b7fd55.png)

see the tree command. From the text it feels like it will run from that directory.

**Comment by meganrogge** [comment]
This behavior is consistent with how history / reverse search (ctrl r) works in terminals. That's where this will eventually be used when autocomplete has been added.
