### ISSUE TITLE
No file path can be confusing

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#143852]
Testing #143456

Files appear in the Open Recent list and editor without the containing file path.

This is confusing if you are working with files with the same name, for example README.md

1. Open a README file from a repo, such as vscode-docs
2. File is open as an editor as README.md with path \README.md
3. Open another README file from another repo, such as vscode-website
4. File is open in another editor as README.md-2 with same parent path \README.md-2
5. Reload insiders.vscode.dev

The Open Recent dropdown lists both files but there is no way to tell which file came from which folder.

![image](https://user-images.githubusercontent.com/12818376/155464507-e4f321e2-f96e-467d-a472-b97a93e23f16.png)

**Comment by gregvanl** [comment]
The same confusion can occur when opening folders with the same name.

![image](https://user-images.githubusercontent.com/12818376/155466007-3a7b46fa-1b63-4091-a3a9-43141482f2bd.png)

**Comment by bpasero** [comment]
Unfortunately the web local file access API does not provide any access to the full path: https://github.com/microsoft/vscode/issues/136486
