### ISSUE TITLE
No symbols found for C++

### ISSUE THREAD

**Issue by nclarius** [microsoft/vscode#143850]
Summary:
With C++ files, no symbols (function and variable declarations etc.) are found in quick-navigation features.

Steps to Reproduce:
1. Open a C++ file.
2. Try to navigate symbols via explorer panel or Ctrl+Shift+O.

Expected result:
Symbols available to navigate to.

Actual result:
No symbols found.

Additional information:
Syntax highlighting in C++ and symbol navigation in other languages works.

Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-10T19:07:05.314Z
Electron: 13.6.9
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.40-electron.0
OS: Linux x64 5.16.10-arch1-1

**Comment by gjsjohnmurray** [comment]
Which extensions have you installed? Using the Report Issue option from the Help menu usually adds a list of extensions to the report.

Have you followed the instructions at https://code.visualstudio.com/docs/languages/cpp already?

**Comment by nclarius** [comment]
The Report Issue from the Help menu is broken, will open a separate issue for that.

The extension was not findable so I had wrongly assumed that C/C++ language basics was the right one. Downlaoding the extension from the browser as a flie and installing from VSIX solved the problem. Thank you.

Should I open a seperate issue about ntierh searching for `C/C++` or `ext install ms-vscode.cpptools` producing any results?

**Comment by gjsjohnmurray** [comment]
> Should I open a seperate issue about neither searching for `C++` nor `ext install ms-vscode.cpptools` finding the extension?

Yes please.
