### ISSUE TITLE
Search UI: Improve message for partial results after exceeding max index size

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#143873]
Testing #143575

With partial results after exceeding the max index size the search UI shows:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/9205389/155508977-6c27f440-5eb7-4a94-b84a-3a4553aca631.png">

Clicking `enable indexing` seems to fully download the index. That message could be improved by mentioning that the index was too large, but can be downloaded in full. Maybe the link could be `download full index` and the text could mention the size, so the user has an understanding of what is going on.

**Comment by chrmarti** [comment]
The message is the same after cancelling the download and clicking the link then doesn't stop at the download limit which is a bit unexpected since that limit (and its dialog) wasn't reached previously.

**Comment by JacksonKearl** [comment]
"Download Full Index" makes good sense, we unfortunately don't know the size so we can't show it.

**Comment by chrmarti** [comment]
Not published to insiders.vscode.dev yet.

**Comment by joyceerhl** [comment]
Verified: 
![image](https://user-images.githubusercontent.com/30305945/156062549-77449703-617a-4597-9985-aa9e28971b85.png)
