### ISSUE TITLE
Help extension authors through TypeScript 2.0 adoption in `compile` script

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#14385]
![image](https://cloud.githubusercontent.com/assets/22350/19680931/c6705bfc-9aa7-11e6-8736-5b6b7625ea2f.png)

Maybe the `compile` script should still exist and simply tell the user to read the following link:

http://code.visualstudio.com/updates/v1_6#_extension-authoring

**Comment by dbaeumer** [comment]
Fixed in vscode-extension-vscode.
