### ISSUE TITLE
UI flickers cant see text, blocker to use the tool

### ISSUE THREAD

**Issue by saikumar-k99** [microsoft/vscode#143822]
Issue Type: <b>Bug</b>

after opening a workspace, the file structure and any commands that i type in the integrated terminal are not visible

VS Code version: Code 1.64.2 (Universal) (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|53, 33, 27|
|Memory (System)|32.00GB (2.05GB free)|
|Process Argv|Podfile --crash-reporter-id 6812ac53-cb1c-4c72-8974-760a810cff69|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.6
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
format-json|Cle|1.0.2
bracket-pair-colorizer|Coe|1.0.62
bracket-pair-colorizer-2|Coe|0.2.2
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.46.0
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|4.4.3
vscode-npm-script|eg2|0.3.24
react-native-react-redux|EQu|2.0.6
json-tools|eri|1.0.2
prettier-vscode|esb|9.3.0
flow-for-vscode|flo|2.0.0
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
gitlab-workflow|Git|3.40.2
search-node-modules|jas|1.3.0
rn-full-pack|kel|0.7.0
vscode-language-babel|mgm|0.0.36
vscode-react-native|msj|1.9.1
vscode-react-native-preview|msj|2022.2.2220
color-highlight|nau|2.5.0
git-extension-pack|nie|1.0.4
gitlab-extension-pack|nie|0.0.1
material-icon-theme|PKi|4.13.0
code-settings-sync|Sha|3.4.3
code-spell-checker|str|2.1.7
gitblame|wad|8.1.0
vscode-todo-highlight|way|1.0.5
change-case|wma|1.0.0
react-native-vscode-extensionpack|zet|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30442554
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
vscop841:30438915
dsvsc008:30440022
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343

```

</details>

**Comment by meganrogge** [comment]
Thanks, I might have seen a similar issue. What version of macOS are you on (Monterey, Big Sur)?

**Comment by meganrogge** [comment]
Also, can you pls include a gif of this?
