### ISSUE TITLE
Terminal cwd seems to be behind a command

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#143832]
At least, that's what it seems like. Testing https://github.com/microsoft/vscode/issues/141502 with Powershell 7

1. Follow the setup for `a` and `b`.
2. Open vscode in folder `a`
3. In the terminal, `cd ../b`
4. In the terminal, _type out_ `echo foo.txt` without hitting enter and ctrl+click `foo.txt`. `a/foo.txt` opens 🐛 
5. Hit enter, or run any other command. Even hitting enter on an empty prompt works.
6. Repeat step 4, but this time `b/foo.txt` opens correctly

**Comment by Tyriar** [comment]
Ah this is because the command doesn't get fully registered until it finishes, same root cause as https://github.com/microsoft/vscode/issues/143704

**Comment by joyceerhl** [comment]
This works but the opened file has a strange breadcrumb: 
![image](https://user-images.githubusercontent.com/30305945/160063694-a049d701-f175-4409-8766-3af87f52f8f3.png)

**Comment by Tyriar** [comment]
Good URI (b/foo.txt):

![image](https://user-images.githubusercontent.com/2193314/160141140-fe5b2750-fd13-47e4-b330-ee11b94fa6b4.png)

Bad URI: (cd b; foo.txt)

![image](https://user-images.githubusercontent.com/2193314/160141304-3e59cb4e-4b85-4e17-a780-f52d37a808bd.png)
