### ISSUE TITLE
Download size limit wording

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#143874]
Testing #143575

<img width="529" alt="image" src="https://user-images.githubusercontent.com/9205389/155510075-4f67fed6-5493-4dcb-9d8b-8f73fd3ba52e.png">

The setting talks about the 'index', but the dialog calls it 'contents'. Shouldn't they align?

There appears to be a typo: `partials version` should maybe be `a partial version`.

**Comment by JacksonKearl** [comment]
The idea was to better define `index` as `this repositories full contents`, so we can use the short from elsewhere.
