### ISSUE TITLE
File > Open Folder behavior is different than File > Open Recent

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#143857]
Testing #143456

I found it confusing that File > Open Folder adds folders to the default workspace but File > Open Recent and selecting a folder, closes the current workspace and just opens the new folder.

Given how these commands are listed together in the File menu and in the empty window, I would have expected them to behave the same in that you are just picking a folder. In one case you are picking from the platform folder picker and in the other from the Open Recent list.

**Comment by bpasero** [comment]
Yeah I noticed this too and think aligning the behaviour would be good.

cc @joaomoreno this would slightly change the experience but I think for the good. Users can still add folders via the explicit "Add Folder to Workspace..." action.

**Comment by bpasero** [comment]
Any "Open Folder..." invocation from `insiders.vscode.dev` should now replace the folders in the explorer, this applies to:
* File menu
* Getting started
* Empty explorer

**Comment by joaomoreno** [comment]
Oh I see, it doesn't really "Open Folder" but actually removes the previous folder from the folders list of the workspace and adds the new one. Makes sense.
