### ISSUE TITLE
vscode.dev It closes when you press the button

### ISSUE THREAD

**Issue by HRTK92** [microsoft/vscode#143854]
It closes when you press the button

https://user-images.githubusercontent.com/70054655/155465478-41b8051f-10f8-4a48-9c8d-0a8410a515c6.mp4

Version: 1.65.0-insider
Commit: 32456dc9e7d3194a94dd3ee0322ccf47e461d09c
User Agent: Mozilla/5.0 (Linux; Android 11; S8-KC) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.101 Mobile Safari/537.36
Embedder: vscode.dev

**Comment by lramos15** [comment]
Unable to reproduce with iPhone, iPad, or Chrome dev tools in mobile mode.
