### ISSUE TITLE
Selection is not revealed when DnD the resource with selection when the resource is already open

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#143878]
Testing https://github.com/microsoft/vscode/issues/143608

From @weinand 

- Open a file in the editor (make sure the file has content with more than one page), place the cursor at the top.
- Search for some content that is at the bottom of the file
- From the search view, DnD the match into the editor area where the file is opened
🐛  Match position is not revealed.

![CleanShot 2022-02-24 at 11 58 17](https://user-images.githubusercontent.com/1898161/155511826-59ef6ed5-7368-4484-8bff-d9fda96e3d20.gif)

I suspect that even though selection parameters are properly passed, the editor is not respecting them

**Comment by bpasero** [comment]
Fun one, `ITextEditorOptions` allows to set both `viewState` and `selection` but we always preferred `viewState` over an explicit `selection`. Fix is to apply both if present but remove the selection portion of `viewState` when a `selection` is present to avoid a redundant selection event.
