### ISSUE TITLE
Customize layout quick pick visibility buttons slightly shift on toggle

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#143828]
Testing #143581

1. Open the customize layout view
2. Toggle the side bar

**Bug**
On toggle, the visibility button appears to shift up/down:

![Recording 2022-02-23 at 14 58 04](https://user-images.githubusercontent.com/12821956/155423912-e5b7635c-87db-428b-bf3b-3a741fd208cf.gif)

**Comment by TylerLeonhardt** [comment]
@mjbvz you sure that's not just the icon?
![image](https://user-images.githubusercontent.com/2644648/155629819-5022cb72-6e68-496b-855a-3436a61f504f.png)

Here they are side-by-side.

**Comment by TylerLeonhardt** [comment]
I think this is you @misolori, but if there is something I can do, let me know :)

**Comment by misolori** [comment]
Yea it looks like the icons are off by 1px, here's both overlaid on top:

<img width="389" alt="CleanShot 2022-02-24 at 20 48 11@2x" src="https://user-images.githubusercontent.com/35271042/155655596-11136a6c-0a6b-4999-97a3-db278d2f0a79.png">

**Comment by misolori** [comment]
Update the icon to now be aligned

https://user-images.githubusercontent.com/35271042/155656141-ed14af26-59e8-4560-8673-5bac16eae4db.mp4
