### ISSUE TITLE
Markdown hover - Increase line height for headers

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#143883]
Testing #143574

We should consider increasing the line height for headers in order to provide spacing between lines.

![image](https://user-images.githubusercontent.com/3372902/155525702-93c4fd42-6983-4c2e-a90a-3c1ddc7a2f0e.png)

**Comment by ArturoDent** [comment]
Possibly related: https://github.com/microsoft/vscode/issues/133488 and  

https://github.com/microsoft/vscode/issues/88417

**Comment by JacksonKearl** [comment]
cc @mjbvz @misolori

**Comment by michaeljones** [comment]
It is also perhaps reasonable to suggest that the top margin is too great on the first header so you end up with more space at the top of the markdown block than at the bottom and it is not possible to balance if you want a header at the top.

It might be worth considering some styles that remove the margin-top from headers when inside a `markdown-hover`?
