### ISSUE TITLE
Code sections in markdown have low contrast text when using the Light High Contrast theme

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#143837]
Testing #143425

Create a new markdown file with the following content:

> # This is a title! 
> ```
> This is a code section
> ```
> And this is just plain text :D

Run the "Markdown: Open Preview to the Side" command and check the code box:

![image](https://user-images.githubusercontent.com/45497113/155434394-a87870ec-9002-40ed-b7d5-c4f3aaf63fd7.png)

**Comment by daviddossett** [comment]
Yikes! Good catch. This was hardcoded elsewhere as `rgb(0,0,0)`
