### ISSUE TITLE
Label for "Goto Previous Problem" is incorrect

### ISSUE THREAD

**Issue by neeleshb** [microsoft/vscode#143821]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2

.Steps to Reproduce:

1. Make an error while coding, and open the "View Problem" box. 
2. Observe that the up-arrow has the label "Goto next problem". Ideally it should be "Goto previous problem". 
![goto_prev_problem_issue](https://user-images.githubusercontent.com/2174646/155414671-a6a7c23d-5061-467f-96a4-1fbfa0804ffb.png)

**Comment by isidorn** [comment]
You accidentally closed this @neeleshb, let's reopen and assign to me.

fyi @sandy081
