### ISSUE TITLE
'defaultSideBySideLayout' naming

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#14387]
Refs: #14016

'defaultSideBySideLayout' should be 'defaultEditorGroupLayout'

Especially if you already expose 'editor group layout' everywhere in the UI.

I understand that editor group is nowhere used in settings and that we already have 'sideBySide'. However I do not think that is a good enough reason to go with 'sideBySide'.

**Comment by bpasero** [comment]
Yup, you convinced me 👍
