### ISSUE TITLE
code is not saving until i close the file and save it

### ISSUE THREAD

**Issue by Dixith-MGD** [microsoft/vscode#143973]
Issue Type: <b>Feature Request</b>

code is not saving until i close the file and save it

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by Dixith-MGD** [comment]
code is not saving until i close the file and save it

**Comment by gjsjohnmurray** [comment]
Please explain exactly what you do and exactly what you expect to happen.
