### ISSUE TITLE
Custom profiles dont use the integrated shell

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#143906]
Issue Type: <b>Bug</b>

Setup a custom profile using 'pwsh' on windows.
Set it as the default
Turn on integration

Expected:
Shell Integration activated

Actual:
Runs like a normal terminal

VS Code version: Code - Insiders 1.65.0-insider (3112460dc48ce7e557ea9feeaae04b912164b48b, 2022-02-24T05:15:20.989Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (17.68GB free)|
|Process Argv|--crash-reporter-id 108b1212-dd8c-4594-8252-c1351bf31268|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.5.0
httpbook|anw|2.2.2
vscode-httpyac|anw|4.10.2
doxdocgen|csc|1.3.2
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.2.0
codespaces|Git|1.5.3
remotehub|Git|0.25.2022022301
handydandy-notebook|jak|0.1.0
better-cpp-syntax|jef|1.15.11
vscode-position|jtr|1.1.2
language-julia-insider|jul|1.5.11
regexp-preview|Lou|0.1.5
vscode-catch2-test-adapter|mat|4.0.25
template-string-converter|meg|0.6.0
vscode-docker|ms-|1.19.0
python|ms-|2022.1.1887581501-dev
vscode-pylance|ms-|2022.2.4-pre.1
jupyter|ms-|2022.2.1010551006
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.223.0
remote-ssh|ms-|0.75.2022022115
remote-ssh-edit|ms-|0.75.2022022115
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
anycode|ms-|0.0.57
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
live-server|ms-|0.2.12
vscode-selfhost-test-provider|ms-|0.3.9
vscode-typescript-next|ms-|4.6.20220210
jupyter-tools|rch|0.0.1
rest-book|tan|5.0.1
cmake|twx|0.0.17
vscode-issue-130883|und|0.0.3
errorlens|use|3.4.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30421357
vsclayoutctrc:30405799
dsvsc009:30440021
pythonvsnew555:30438690
vsbas813:30436447
vscscmwlcmt:30428973
azactmsalcf:30432849
vscgsvid2:30433758
dockersurvey3cf:30438169
vscaac:30438845
pynewfile477:30443519

```

</details>

**Comment by rchiodo** [comment]
Here's my relevant settings:

```json
 "terminal.integrated.shellIntegration.enabled": true,
  "terminal.integrated.profiles.windows": {
    "Integrated PowerShell": {
      "path": "pwsh.exe",
      "args": ["-noexit"]
    }
  },
  "terminal.integrated.defaultProfile.windows": "Integrated PowerShell",
  "terminal.integrated.shellIntegration.decorationsEnabled": true
```

**Comment by rchiodo** [comment]
I get this in my terminal:

![image](https://user-images.githubusercontent.com/19672699/155584793-4c5ecae0-9269-46f8-ba9a-1f28861bb86f.png)

If I switch the ```terminal.integrated.defaultProfile.windows``` to just ```Powershell``` then it works as expected:

![image](https://user-images.githubusercontent.com/19672699/155584896-1b323758-6f94-4b39-8877-94f13d6ca969.png)

**Comment by meganrogge** [comment]
This is expected - we don't support custom args at the moment. We warn in the console about this.
