### ISSUE TITLE
Console Location is not window dependent

### ISSUE THREAD

**Issue by MatthewTeta** [microsoft/vscode#143944]
Issue Type: <b>Bug</b>

There was recently a change to the window system (at least for the console). I like to have my console on the side of the window for horizontal monitors and at the bottom of the window for vertical monitors. After the change to how I can move the console window, when I change the position in one VSCode window instance, it changes the placement in all of the other windows that I have open. 

I think that I should be able to have one window with the console on the bottom of the screen and another window with the console on the side of the screen. This used to be the case before I updated within the last couple of weeks. 

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4610M CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (6.39GB free)|
|Process Argv|--crash-reporter-id b7a16a02-e88d-4439-8810-d5e245a9fd92|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
insert-unicode|bru|0.13.3
npm-intellisense|chr|1.4.1
doxdocgen|csc|1.3.2
vscode-eslint|dba|2.2.2
vscode-babel-coloring|dza|0.0.4
gitlens|eam|11.7.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.3.0
vscode-yarn|gam|2.1.0
matlab|Gim|2.3.1
vscode-pull-request-github|Git|0.36.2
beautify|Hoo|1.5.0
better-cpp-syntax|jef|1.15.13
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.4
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.4
remote-ssh|ms-|0.74.0
remote-ssh-edit|ms-|0.74.0
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
debugger-for-chrome|msj|4.13.0
material-icon-theme|PKi|4.13.0
bracketeer|pus|1.3.1
markdown-preview-enhanced|shd|0.6.1
code-eol|soh|0.3.3
cmake|twx|0.0.17
tiff-preview|uco|0.0.1
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30442554
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc008:30440022
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343

```

</details>

**Comment by gjsjohnmurray** [comment]
By "the console" I guess you are referring to the Panel, which by default lies at the bottom of the window and contains tabs for PROBLEMS, OUTPUT, DEBUG CONSOLE, and TERMINAL.

![image](https://user-images.githubusercontent.com/6726799/155687742-32d55f00-5cf3-47d1-89a8-5494192fbe25.png)


I also guess you used the "Move Views to Side Panel" command and you see all windows affected.

![image](https://user-images.githubusercontent.com/6726799/155687906-a0c2833e-9075-4770-b5eb-51221c146b0b.png)

I suggest you revert this by using "Move Views to Panel". When those tabs are back in the Panel at the bottom, use its context menu "Move Panel Right".  This will only affect the current window.

**Comment by sbatten** [comment]
as designed, @gjsjohnmurray describes the solution accurately, thanks again @gjsjohnmurray
