### ISSUE TITLE
Missed localization for "You have no recent folders, open a folder to start." in the getting started window

### ISSUE THREAD

**Issue by ralphchung** [microsoft/vscode#143995]
Does this issue occur when all extensions are disabled?: N/A (Language extension needs to be enabled.)

- VS Code Version: 1.64.2
- OS Version: macOS 12.2.1 (Darwin arm64 21.3.0)

Steps to Reproduce:

1. Open the getting started tab with a non English localization extension.
2. You should see the string "You have no recent folders, open a folder to start." is not localized.

Seems like the issue may be related to this line. https://github.com/microsoft/vscode/blob/07601513c73783f8ae2c2e802d9042b0feca4ed8/src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.ts#L1098

Thank you!

**Comment by rzhao271** [comment]
Doesn't seem translated for me yet, even using the pseudolanguage extension.

**Comment by JacksonKearl** [comment]
This is what I see in spanish: <img width="1081" alt="image" src="https://user-images.githubusercontent.com/8586769/159841780-8951353d-1df8-458d-a524-7ca253f1bf94.png">

**Comment by rzhao271** [comment]
TIL there's the "clear recently opened" command. I had to reload the workbench after that to get that message, though.
