### ISSUE TITLE
Sympy output no longer centered

### ISSUE THREAD

**Issue by GodOfDeathSam** [microsoft/vscode#143916]
## Environment data

-   VS Code version: 1.64.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.1.1301854968
-   Python Extension version (available under the Extensions sidebar): v2022.0.1814523869
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Python 3.10.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local | Remote | N/A: local

## Expected behaviour

Displaying sympy variables and expressions should be centered like so (sorry for the complicated output, it's an old pic of back when the output used to be centered. In general though the behaviour is reproduced with the simplest of expressions):
![image](https://user-images.githubusercontent.com/87801374/154809443-4292b9de-9270-4d4f-b74b-aa2352cbb404.png)

## Actual behaviour

All the output is left aligned like so:
![image](https://user-images.githubusercontent.com/87801374/154809651-a45f5cb7-73b1-48ad-bc61-48ca2bd8ac6b.png)

## Steps to reproduce:

1. Either run any cell with a sympy expression as it's output, or use the display() function of IPython.display

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Info 21:32:28: Execute Cells request 0
Info 21:32:28: Execute Cell 0 untitled:Untitled-1.ipynb?jupyter-notebook
Info 21:32:29: Cell 0 executed with state Success
Info 21:32:31: Execute Cells request 1
Info 21:32:31: Execute Cell 1 untitled:Untitled-1.ipynb?jupyter-notebook
Info 21:32:31: Cell 1 executed with state Success
```

</p>
</details>

**Comment by DonJayamanne** [comment]
@GodOfDeathSam Thanks for filing this issue, I've tested this in classic Jupyter Notebooks, and they too left align the output (see screenshot below).
We strive to be consistent with Jupyter notebooks, hence I'm closing this issue.
I agree this was center aligned in the past, however we were relying on a seprate package at the time which we had little control over.

![image](https://user-images.githubusercontent.com/1948812/155626340-f2ea0384-91e4-4f18-8036-74ed55f1a12f.png)
