### ISSUE TITLE
vscode starts extremely slow...

### ISSUE THREAD

**Issue by BlackMojito** [microsoft/vscode#143943]
1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`/C:/Users/xuc/prof-3m8jnFOV.main.cpuprofile.txt`
-`/C:/Users/xuc/prof-3m8jnFOV.renderer.cpuprofile.txt`
[prof-3m8jnFOV.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/8139108/prof-3m8jnFOV.main.cpuprofile.txt)
[prof-3m8jnFOV.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/8139109/prof-3m8jnFOV.renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
Can you try this with [VS Code Insiders](https://code.visualstudio.com/insiders/)?
