### ISSUE TITLE
"Search" doesn't work inside interactive HTML reports

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode#143917]
## Environment data
-   VS Code Version: 1.65.0-insider (user setup)
-   Commit: eeeab304b9ac777b4a8dddf55f66ffebd9e4e7f2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.2.1010561006
-   Python Extension version (available under the Extensions sidebar): v2022.1.1854775815-dev
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.22000
-   Python and/or Anaconda version: 4.11.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

1. Ctrl + F
2. Perform a string search
3. Expect to search in the entire notebook, including interactive HTML reports

## Actual behaviour

Does not search inside interactive HTML reports (for my case, it didn't search inside pandas profiling)

## Steps to reproduce:

On this notebook: https://github.com/minsa110/titanic/blob/main/titanic.ipynb

Under "Data Exploration", doesn't search the result of this cell:
```pandas_profiling.ProfileReport(titanic_df)```

**Comment by rebornix** [comment]
Did you enable search in output?

<img width="413" alt="image" src="https://user-images.githubusercontent.com/876920/156475814-c3c2d7b0-1dc8-4a35-a912-87bcb9bc3193.png">
