### ISSUE TITLE
Deleted a folder from laptop(this pc)

### ISSUE THREAD

**Issue by NikhilNani3** [microsoft/vscode#143976]
Issue Type: <b>Feature Request</b>

I added a folder(consisting of images) into vscode when i removed the folder from vscode, it also deleted from my laptop

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by meganrogge** [comment]
When you say "removed the folder" do you mean you deleted it?

**Comment by JacksonKearl** [comment]
Is the folder in your recycling bin?

**Comment by NikhilNani3** [comment]
> When you say "removed the folder" do you mean you deleted it?

Yes at first i added a folder which contains of pictures in to vs code and i saw the images slowly were moving into vscode and when i deleted the file in vscode it permanently got deleted from laptop and i couldnt find it anywhere

**Comment by JacksonKearl** [comment]
Deleting a folder from the VS Code window is supposed to delete it from your computer. The file should be in the recycling bin or similar, or if your platform does not provide such a container we should have prompted you that the file would be permanently deleted. I do not know what steps you took to reach what you saw. If you include a screen recording I might be able to better understand. My expectation is that the files would be in the recycling bin.
