### ISSUE TITLE
R language support

### ISSUE THREAD

**Issue by srinath29** [Microsoft/vscode#14393]
- VSCode Version: Recent (1.6)
- OS Version: All

This is more of a request for a feature. I searched lot of places to get the R support in visual studio code but I didn't hit any useful places. Are there any plans in future to support it. Microsoft has it's R-tools. And a visual studio extension specifically for R. If they can help for visual studio code. It will be ultimate IDE.

**Comment by erickhouse1** [comment]
I would be interested in contributing to something like this. I want to visualize data on the web with R + JavaScript without having to flip between multiple IDE's on Mac/Linux.

**Comment by tiagoh** [comment]
+1

Would really love to see it!

**Comment by srinath29** [comment]
I would like to know any updates regarding this feature request.

**Comment by asdncg** [comment]
+1
please

**Comment by GautamDMan** [comment]
is this being worked on ?

**Comment by shane-kercheval** [comment]
Yeah, would be curious. I'm using Sublime and despite decent support, about ready to pay someone to customize syntax highlighting for me. But would like to see VSCode support for both .R and .Rmd files, it's a cleaner application in general.

**Comment by MikhailArkhipov** [comment]
Also here https://github.com/Microsoft/RTVS/issues/1295

**Comment by cszang** [comment]
+1

**Comment by dnacuna** [comment]
:pray: +1

**Comment by kliron** [comment]
+1

**Comment by PabloDoval** [comment]
I'd really love this one! I am using VSCode more and more each day, and while the RTools for VS are quite nice, having them integrated in VSCode would benefit a greater audience - I'm thinking about Mac and Linux users here.

**Comment by rmln** [comment]
+1

**Comment by sardap** [comment]
+1

**Comment by jaxspades** [comment]
+1

**Comment by dio4ev** [comment]
+1

**Comment by Ikuyadeu** [comment]
+1
I made R extension.
https://marketplace.visualstudio.com/items?itemName=Ikuyadeu.r
If interested, please tell me what you think.

**Comment by Bienias** [comment]
+1

**Comment by MikhailArkhipov** [comment]
You can close this one in favor of https://github.com/Microsoft/RTVS/issues/1295 which is in progress. Folks can file requests there :-)

**Comment by chrisdias** [comment]
@MikhailArkhipov great to hear, looking forward to it!
