### ISSUE TITLE
HTML tag in doc comment fail to be rendered as formatted text

### ISSUE THREAD

**Issue by pingu8007** [microsoft/vscode#143942]
Issue Type: <b>Bug</b>

1. Open any Java project
2. Hover on any token (class/method/field/param/...)
3. Tooltip is shown but HTML is not rendered

![image](https://user-images.githubusercontent.com/8936513/155666534-ce28df02-a779-4c0f-bd97-a19ef63e550a.png)

It's similar to previous issue #143081 but on Java project rather than cpp.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Windows_NT x64 10.0.19044

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|39.86GB (25.08GB free)|
|Process Argv|--crash-reporter-id b8f457c0-9048-433e-a6ca-4f6fc6e425e9|
|Screen Reader|no|
|VM|29%|

|Item|Value|
|---|---|
|Remote|SSH: HCA2101023.uft.com|
|OS|Windows_NT x64 10.0.19044|
|CPUs|Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz (12 x 3096)|
|Memory (System)|31.75GB (17.55GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hant|MS-|1.64.7
remote-containers|ms-|0.217.4
remote-ssh|ms-|0.74.0
remote-ssh-edit|ms-|0.74.0
remote-wsl|ms-|0.64.2
vscode-lombok|Gab|1.0.1
vscode-language-pack-zh-hant|MS-|1.64.7
vscode-spring-boot|Piv|1.31.0
java|red|1.3.0
vscodeintellicode|Vis|1.2.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrt:30437039
vsrem710cf:30416617
dsvsc008:30440022
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343
vsnot107cf:30443615

```

</details>

**Comment by mjbvz** [comment]
This is something that the Java extension can enable if they feel it makes sense

/extJava
