### ISSUE TITLE
When multiple files are selected in "open editors" pane, clicking an "X" for a file closes all files

### ISSUE THREAD

**Issue by elias6** [microsoft/vscode#143970]
Issue Type: <b>Bug</b>

## Steps to reproduce
1. Open multiple files in VS Code.
2. In the "open editors" pane on the left side, select multiple files. This can be done by clicking the top file, then holding down your shift key and clicking the bottom file.
3. Click one of the "X"es on the left to close one of the files.

## Expected
The file whose "X" you clicked should be closed. And only that file.

## Actual
All of the files that you have selected are closed.

You may be able to reopen them by repeatedly using the "Reopen Closed Editor" command (Command+Shift+T on Mac), but that seems to not always reopen all the files you had open, if you had more than about 20 files open.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|16, 15, 14|
|Memory (System)|16.00GB (0.70GB free)|
|Process Argv|--crash-reporter-id 8546bdc4-919c-427c-bd8c-2a7b47b5943e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Nix|bbe|1.0.1
gitlens|eam|11.7.0
prettier-vscode|esb|9.3.0
pyformat|giy|1.0.2
vscode-graphql|Gra|0.3.41
vscode-docker|ms-|1.20.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.4
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
vsliveshare|ms-|1.0.5330
color-highlight|nau|2.5.0
fish-vscode|sky|0.2.1
language-stylus|sys|1.15.0
selectline-statusbar|tom|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
vscop841:30438915
dsvsc008:30440022
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343
vsnot107cf:30443615

```

</details>

**Comment by gijocode** [comment]
Isn't this expected behaviour though?

When you select multiple files, you expect the operation you perform to be applied to all. For example copy, cut, delete.

**Comment by elias6** [comment]
I would say no, this is not expected behavior. I would think the Xes that show for individual files would correspond to only the file they appear next to, not all the files.

And regardless of that, it is annoying, and a definite bug, to not be able to undo closing the files.

**Comment by elias6** [comment]
What was this closed for? Are you sure this is as designed?

**Comment by JacksonKearl** [comment]
Yes, actions executed in the open editors view should apply to all selected items. The existence of a limit in the size of the closed editor history is also intended, though you can open a separate feature request for a way to configure that if you'd like.

**Comment by elias6** [comment]
OK... I guess I learned something.
