### ISSUE TITLE
Matplotlib widget not rendering in Notebook output

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#143922]
## Environment data

-   VS Code version: VS Code Insiders
-   Jupyter Extension version (available under the Extensions sidebar): Latest Pre-release version
-   Python Extension version (available under the Extensions sidebar): 3.8
-   OS (Windows | Mac | Linux distro) and version: WSL
-   Python and/or Anaconda version: Python
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): VIrtual Env 
-   Jupyter server running: Local

## Expected behaviour

Widget renders, and is completely visible.

## Actual behaviour

Only a small portion of the widget is displayed (almost 2 lines worth of the widget)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Create a cell with the following code and run it
```python
import numpy as np
import pandas as pd
%matplotlib widget
import matplotlib.pyplot as plt
p = np.linspace(0,20,100)
plt.plot(p,np.sin(15*p))
plt.show()
```

Looks like a regression in VS Code insiders.

![image](https://user-images.githubusercontent.com/1948812/155618784-3804a527-47d4-4479-af74-38c3a00bafab.png)

Exact same code in VS Code stable (same version of Python & Jupyter)

![image](https://user-images.githubusercontent.com/1948812/155618873-bfe27525-76f4-40d6-8926-36962ca50327.png)

**Comment by DonJayamanne** [comment]
@rebornix looks like we'll be shipping something in VSCode insiders, that will break widgets (break = not rendering in a usable manner)

**Comment by mjbvz** [comment]
@DonJayamanne Do you see this in an otherwise empty jupyter notebook with that cell? I just tried but could not reproduce the problem

<img width="1083" alt="Screen Shot 2022-02-24 at 2 54 20 PM" src="https://user-images.githubusercontent.com/12821956/155621177-59da7252-ad5e-4fbb-a3e7-ea0246fecd6f.png">

**Comment by DonJayamanne** [comment]
> Do you see this in an otherwise empty jupyter notebook with that cell?

Yes, thats what I've done
![widget](https://user-images.githubusercontent.com/1948812/155621644-4f422818-27e7-4f0e-94e2-a7c66a8bc835.png)

**Comment by roblourens** [comment]
Any errors?

**Comment by roblourens** [comment]
I can't get it to work at all, in environments where I'm sure I've used this stuff before: `ModuleNotFoundError: No module named 'ipympl'`

**Comment by DonJayamanne** [comment]
You'd need to install that `python -m pip install ipympl` or in the cell type `%pip install ipympl`

**Comment by DonJayamanne** [comment]
FYI - just tested outside WSL and that works

**Comment by DonJayamanne** [comment]
Yes, confirmed works outside WSL, but in WSL it doesn't work in VS Code insiders even in different workspaces in WSL (different folder names).
But exact same notebook works in WSL when using VS Code stable.

**Comment by roblourens** [comment]
Works in ssh. Can you check for errors in devtools, or look at the DOM? Maybe something related to the webview in a remote window.

It looks like it managed to render something though, so I'm a little confused, like if the webview was failing to load scripts it would be worse

**Comment by rchiodo** [comment]
Let me try to see if I can repro

**Comment by rchiodo** [comment]
Works for me in WSL

**Comment by DonJayamanne** [comment]
Errors when opening this notebook (however i get this same error in Stable as well)

![image](https://user-images.githubusercontent.com/1948812/155623667-a094c016-c55d-4539-a13a-6834fccbe53b.png)

No errors after running the cell,

**Comment by DonJayamanne** [comment]
I manually adjusted the height of the widget container and this is what I can see
I think the whole widget didn't get rendered as the container was too small (or some other issue)
![image](https://user-images.githubusercontent.com/1948812/155623931-1c4e7039-ede6-4abe-823d-ebe92ed09fda.png)

**Comment by DonJayamanne** [comment]
> Works for me in WSL

Weird, fails on insiders for me and works on stable, consistently.

**Comment by DonJayamanne** [comment]
@rchiodo this is my version of VS Code insiders, please could you compare against yours

Version: 1.65.0-insider (user setup)
Commit: 3112460dc48ce7e557ea9feeaae04b912164b48b
Date: 2022-02-24T05:15:20.989Z
Electron: 16.0.9
Chromium: 96.0.4664.174
Node.js: 16.9.1
V8: 9.6.180.23-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by rchiodo** [comment]
Version: 1.65.0-insider (user setup)
Commit: 3112460dc48ce7e557ea9feeaae04b912164b48b
Date: 2022-02-24T05:15:20.989Z
Electron: 16.0.9
Chromium: 96.0.4664.174
Node.js: 16.9.1
V8: 9.6.180.23-electron.0
OS: Windows_NT x64 10.0.19044

Yeah same

**Comment by rchiodo** [comment]
Maybe the script we download for the widget is out of date? Mine asked to download.

**Comment by DonJayamanne** [comment]
Yes you are right, weird, a new version must have been uploaded in the past day (the scripts are in the extesnsion folder, which gets blown away with each new version of insiders).
Closing this issue.

Thanks,
