### ISSUE TITLE
How does VSCode's terminal autodetect port launched by a process and auto port forward.

### ISSUE THREAD

**Issue by chimmy-changa** [microsoft/vscode#143958]
Unfortunately, I'm having to post this question as a feature request because I couldn't find relevant information on stackoverflow.

I wanted to know how VSCode's terminal auto detects a port being allocated by a command and then immediately port forwards it. 

For example: 
If I'm working remotely in VsCode using the Remote Explorer and I open a terminal by pressing Ctrl + ` key.
```bash
$ docker run --rm -it -p 8888:8888 httpd
```  
VSCode is smart enough to recognize that the above command has requested the OS for allocating port 8888 and autoport forwards it, which is awesome and a really helpful feature which I use almost daily!

I wanted to learn how VSCode has acheived this ?

Is it related to adding bash commands or something at the Editor level, if yes, can you point me to the file in the source code ?

Thanks in advance.

If this is not the right place to ask this question, please feel free to close the issue.

**Comment by alexr00** [comment]
@chimmy-changa two ways, depending on what `remote.autoForwardPortsSource` is set two:

**process**: For this setting, we poll the proc filesystems and look for ports process that are listening on ports: 
https://github.com/microsoft/vscode/blob/9c04bd5cc6075a116373b9c2dfd2f10e3bdb0867/src/vs/workbench/api/node/extHostTunnelService.ts#L130-L145

**output**: For this setting, we watch output locations for things that look like ports: 
https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/workbench/contrib/remote/browser/remoteExplorer.ts#L460-L461

**Comment by chimmy-changa** [comment]
Thank you for the prompt and helpful response!
