### ISSUE TITLE
Open in Notebook Editor codelens for large notebook outputs throws error

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#143966]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Have a notebook cell with large output
2. Show more
3. Click Open in Notebook Editor codelens
4. :bug: `Unable to resolve filesystem provider with relative file path 'vscode-notebook-cell-output:Untitled-1.ipynb?jupyter-notebook#opfc1db2e2-45b6-4750-b67e-504e39a2bdef,untitled'`
    ![Recording 2022-02-25 at 07 51 12](https://user-images.githubusercontent.com/30305945/155745535-f0df0c83-b1a5-4995-a5bd-4361acc68fe1.gif)

**Comment by joyceerhl** [comment]
I am able to reproduce this on both desktop VS Code and in vscode.dev. The GIF above is for vscode.dev.

**Comment by rebornix** [comment]
The codelens should be ignored in the output file.

**Comment by joyceerhl** [comment]
Tiny cosmetic issue: the hyperlink should not include the space preceding "in a text editor"
![image](https://user-images.githubusercontent.com/30305945/160044603-e4867f73-49b9-42b3-bba0-9e4d677f0204.png)
