### ISSUE TITLE
tsconfig "extends" link hover says "Execute Command"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#143933]
From https://github.com/microsoft/vscode/issues/141112

- Open a tsconfig.json with an "extends"
- Hover the "extends" link
- It used to say "Follow link", now it says "Execute Command"

<img width="230" alt="image" src="https://user-images.githubusercontent.com/323878/155599284-486c9711-5332-415d-95b0-71b382f8bd0a.png">

<img width="272" alt="image" src="https://user-images.githubusercontent.com/323878/155599326-2afd4408-e939-4626-afcf-3b8dbff02027.png">

**Comment by mjbvz** [comment]
Should be fixed by 2a72cf7070ba4da435260c3df2a826a2e41a7cf5
