### ISSUE TITLE
Terminal decorations don't seem to scale with terminal font size

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#143932]
Issue Type: <b>Bug</b>

Found while testing #142894

1. Enable shell integration
1. Run a few commands in the terminal that produce decorations
1. Now scale the terminal font size up or down

**bug**

The decorations don't seem to adjust along with the font size. Here's with a  very small font size:

<img width="251" alt="Screen Shot 2022-02-24 at 4 10 54 PM" src="https://user-images.githubusercontent.com/12821956/155628880-816f66e2-70bc-4eaa-b971-4ad8f9bda775.png">

And with a very large font size:

<img width="327" alt="Screen Shot 2022-02-24 at 4 11 32 PM" src="https://user-images.githubusercontent.com/12821956/155628927-138d5154-6b52-4b32-a039-032d219c2562.png">

VS Code version: Code - Insiders 1.65.0-insider (Universal) (3112460dc48ce7e557ea9feeaae04b912164b48b, 2022-02-24T05:14:50.798Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|32.00GB (1.11GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d --crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d --crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by meganrogge** [comment]
We don't currently adjust the font size of the codicons on zoom or when the font size changes because we only have a `10px` or `20px` margin to work with in the terminal.
Not sure if we can do anything about this
![Screen Shot 2022-02-24 at 8 33 18 PM](https://user-images.githubusercontent.com/29464607/155642763-155a3620-71a3-4d22-a55b-9f5a722bb03f.png)

**Comment by meganrogge** [comment]
We'd have to dynamically change the `margin-left` for all of these if we wanted to update the codicon's font size to match that of the terminal 
![Screen Shot 2022-02-24 at 8 33 18 PM](https://user-images.githubusercontent.com/29464607/155643065-4b967820-a1c4-4943-9de4-8d835eb2457e.png)
https://github.com/microsoft/vscode/blob/fe61abc5134a4274c8eaf6c1af4e51330edb939c/src/vs/workbench/contrib/terminal/browser/media/terminal.css#L105-L114

**Comment by meganrogge** [comment]
doing so would look like this
![Screen Shot 2022-02-24 at 8 37 24 PM](https://user-images.githubusercontent.com/29464607/155643156-f297a2c5-088f-4292-a999-57ff2988ecab.png)

**Comment by meganrogge** [comment]
an issue with that is for splits (beyond the first) and when the terminal is in the side panel/editor area, we don't have enough room to accommodate the codicon. So could cap the size based on that gutter width?
![Screen Shot 2022-02-24 at 8 41 05 PM](https://user-images.githubusercontent.com/29464607/155643531-595e434a-54c2-4e54-9dd6-2e4c66bf8d86.png)

**Comment by joyceerhl** [comment]
Scaling doesn't seem to work for very large font sizes, e.g. with `"terminal.integrated.fontSize": 40`:

![image](https://user-images.githubusercontent.com/30305945/156037886-1656419f-2e01-4200-a9bf-34e88d34a438.png)

**Comment by meganrogge** [comment]
@joyceerhl that is by design. we cap the size because we are limited to that gutter width

**Comment by meganrogge** [comment]
See https://github.com/microsoft/vscode/pull/143939#issue-1149997128 for details
