### ISSUE TITLE
Terminal command decorations: When I move the terminal to a side panel, the previous decorations stop working.

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode#143900]
Testing #143433

1. Run command a decoration is created, when you click it show the options ro run again or copy the output.
2. Move terminal to a side panel.
3. Move back to the previous panel.
4. Clicking on the decoration now doesn't show anything, or do anything.

**Comment by meganrogge** [comment]
I believe this is now fixed in the latest insiders. Can you pls confirm?
