### ISSUE TITLE
Format Selection and Format Document don't do anything for JavaScript

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#14391]
Testing #14287

go to `/gulpfile.js`

Edit the last lines:
```js
						if (runningEditorTasks) {
							require(`./build/gulpfile.editor`);
							require(`./build/gulpfile.hygiene`);
						} else {
							// Load all the gulpfiles only if running tasks other than the editor tasks
							const build=path.join(__dirname, 'build');
							require('glob').sync('gulpfile.*.js', {cwd:build})
.forEach(f => require(`./build/${ f }`));
						}
```

Observe: No changes occur
![image](https://cloud.githubusercontent.com/assets/5047891/19681314/3f844926-9aa9-11e6-8c00-961503d5a685.png)

**Comment by dbaeumer** [comment]
@alexandrudima this works for me:

![14391](https://cloud.githubusercontent.com/assets/1931590/19695027/e19b251c-9ae1-11e6-808b-643112c85467.gif)

Can you still reproduce this. Can you enable `"typescript.server.trace"="verbose"` and see if the format message is sent to the tsserver. Could you paste the result here.

**Comment by alexandrudima** [comment]
I can reproduce on this version:

![image](https://cloud.githubusercontent.com/assets/5047891/19727690/c106e2f0-9b90-11e6-8e0d-a755f276bf93.png)

I am now updating the insiders build and checking on the latest version

**Comment by alexandrudima** [comment]
Also doesn't work on latest insiders:
![image](https://cloud.githubusercontent.com/assets/5047891/19727749/f92fcdcc-9b90-11e6-8472-1c16198233e3.png)

Extensions:
![image](https://cloud.githubusercontent.com/assets/5047891/19727757/01990d0c-9b91-11e6-9222-08c160db0a12.png)

User settings:
```js
// Place your settings in this file to overwrite the default settings
{
	"files.autoSave": "afterDelay"
	, "editor.fontFamily": "Hack"
	// , "editor.fontFamily": "'IBM 3270'"
	// , "editor.renderWhitespace": true
	, "editor.fontSize": 16
	, "editor.lineHeight": 22
	, "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?"
	// , "editor.autoClosingBrackets": false
	, "editor.renderIndentGuides": true
	, "workbench.editor.showTabs": true
	, "editor.renderWhitespace": true
	// , "editor.wrappingColumn": 0
	, "editor.mouseWheelScrollSensitivity": 1
	// , "files.exclude": null
	// "search.exclude": null
	// , "terminal.integrated.shell.windows": 0

	, "telemetry.enableCrashReporter": false
	,
	"telemetry.enableTelemetry": false,
	"git.confirmSync": false
}
```

I will now begin fishing :)

**Comment by alexandrudima** [comment]
After disabling extensions and commenting out all my settings, it still does not work.

Moreover, I have noticed that none of the rich language features appear to work for me:

![javascript](https://cloud.githubusercontent.com/assets/5047891/19727899/8b1caeee-9b91-11e6-84ff-2a65930b3607.gif)

**Comment by alexandrudima** [comment]
The same behaviour when opening vscode with `scripts\code.bat`.

**Comment by alexandrudima** [comment]
Note `"typescript.server.trace"="verbose"` has no effect. Also `"typescript.tsserver.trace": "verbose"` has no effect...

**Comment by alexandrudima** [comment]
Hmm, maybe #14500 is affecting you

**Comment by alexandrudima** [comment]
d'oh I was looking in the console and not in the output channel.

**Comment by alexandrudima** [comment]
@dbaeumer Everything results in this:

```
[Info  - 3:47:14 PM] Using tsserver from location: c:\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js
[Error - 3:47:18 PM] 'completions' request failed with error.
Error processing request. LanguageService is disabled
Error: LanguageService is disabled
    at Object.throwLanguageServiceIsDisabledError (c:\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js:5397:19)
    at IOSession.Session.getCompletions (c:\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js:54911:64)
    at Session.handlers.ts.createMap._a.(anonymous function) (c:\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js:54156:61)
    at IOSession.Session.executeCommand (c:\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js:55223:28)
    at IOSession.Session.onMessage (c:\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js:55243:35)
    at Interface.<anonymous> (c:\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js:56300:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:232:10)
    at Interface.<anonymous> (readline.js:365:12)
[Error - 3:47:19 PM] 'completions' request failed with error.
Error processing request. LanguageService is disabled
Error: LanguageService is disabled
    at Object.throwLanguageServiceIsDisabledError (c:\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js:5397:19)
    at IOSession.Session.getCompletions (c:\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js:54911:64)
    at Session.handlers.ts.createMap._a.(anonymous function) (c:\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js:54156:61)
    at IOSession.Session.executeCommand (c:\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js:55223:28)
    at IOSession.Session.onMessage (c:\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js:55243:35)
    at Interface.<anonymous> (c:\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js:56300:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:232:10)
    at Interface.<anonymous> (readline.js:365:12)
```

**Comment by alexandrudima** [comment]
@dbaeumer I see we are shipping with typescript@^2.0.6-insiders.20161014 which does not appear to be locked in `npm-shrinkwrap`. I am confused by how this is set up. Shouldn't we have shipping dependencies locked in for reproducible builds ?

**Comment by alexandrudima** [comment]
Is it perhaps our auto-updater that leaves behind old files on disk ?

**Comment by dbaeumer** [comment]
The reason why this is not in `npm-shrinkwrap` yet is that we didn't want to lock it during the insider build timeframe. Now that TS 2.0.6 final is out we should lock it. I thought that using 2.0.6 as an exact dependency in the package.json does the trick and since it is MS code no need for shrinkwarp. @alexandrudima is that assumption correct. I opened #14548 to discus this further.

However all this doesn't explain why the language service is disabled for you. Do you see this for all your projects. In VS Code does TS code assist work. Does it only fail for JS files?

@mhegazy @vladima any idea how this can happen. I saw in the tsserver code that there is now a flag to disable language smartness for a project but we don't have any code that disables this.

**Comment by alexandrudima** [comment]
@dbaeumer yeah, it's only disabled for the top level gulpfile.js, all the rest of the gulpfiles and TS code work as expected. Regarding npm, I don't know :)

I can zip up my vscode install (which is insiders updated on top of insiders since a long time) and my vscode folder, if you think that'll help

**Comment by mhegazy** [comment]
The language service is "disabled" if the server found too many files in the project. previouslly it would have crashed with out of memory exception. there should be an error event generated. how can i reproduce this locally?

//cc: @zhengbli

**Comment by alexandrudima** [comment]
Aha! Nice hint @mhegazy

Steps:
* clone vscode
* scripts/npm install
* do a few builds such as:
* gulp watch
* gulp editor-distro
* gulp vscode-win32

These end up creating lots of out-* folders:

They will contain lots of JavaScript
![image](https://cloud.githubusercontent.com/assets/5047891/19743783/f97c176a-9bca-11e6-9317-1ad2828a927c.png)

**Comment by alexandrudima** [comment]
Yep, after removing the out folders and more node_modules that I had under build/monaco/node_modules (coming in with `npm run monaco-editor-setup`) it starts to work again 👍

**Comment by dbaeumer** [comment]
@mhegazy @zhengbli: what error event do I get here. VS Code needs to react on this and basically stop sending requests to the server because the current behavior is very confusing for the user.

And why do you stop single file actions like format as well. I am not against degrading the tsserver features if projects get too big but the tsserver could be smarter than on/off. For example the editor still shows large file but for example stops coloring and doesn't simply stop showing the file at all.

**Comment by dbaeumer** [comment]
I opened https://github.com/Microsoft/TypeScript/issues/11888 to discuss on how to continue with this in general. I also tweaked our jsconfig.json to exclude more of the editor specific out and node_modules stuff.
