### ISSUE TITLE
Unable to install GitLens Insider from the instructions on site

### ISSUE THREAD

**Issue by thenexxuz** [microsoft/vscode#143974]
Issue Type: <b>Bug</b>

https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders

When I paste "ext install eamodio.gitlens-insiders" into the VS Code Quick Open it opens the extensions panel but does not show the "insiders" version of GitLens.

I then tried to manually install but then it failed because it did not automatically install it's dependancy "gitkraken.gitkraken-authentication".

After manually installing the dependency I was able to then manually install the GitLens Insider.

Once everything was installed I was not able to see the settings for GitLens until I opened a file or project either.

VS Code version: Code - OSS 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T22:59:58.092Z)
OS version: Linux x64 5.10.98-1-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 3093)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.57GB (0.38GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens-insiders|eam|2022.2.2417
gitkraken-authentication|git|1.0.1

</details>

**Comment by gjsjohnmurray** [comment]
I think Manjaro builds a VS Code that uses the Open VSX Registry. I guess the extensions you want are not published there.
