### ISSUE TITLE
Add systemd highlighting for Markdown code blocks

### ISSUE THREAD

**Issue by SebDanielsson** [microsoft/vscode#143911]
It would be pretty neat to have highlighting for systemd unit files inside Markdown code blocks. It was recently added to github/linguist and is already available with prismjs and chroma for Go. I think this is handled by the Markdown Preview extension, right?

**Comment by mjbvz** [comment]
This can be contributed by extensions, see https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example
