### ISSUE TITLE
`Could not find pty with ID` should be excluded from telemetry

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#143998]
This error seems to spam the error telemetry for no good reason. The recently new `ErrorNoTelemetry` class can be used to exclude it.

//cc @lramos15

**Comment by bpasero** [comment]
Didnt this happen?

**Comment by lramos15** [comment]
Yes it did. Do you still see many in the error telemetry website?

**Comment by bpasero** [comment]
I am not looking currently, but when I filed this I was likely error telemetry meister.
