### ISSUE TITLE
Add dedicated padding for terminal command decorations

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#143986]
Ref https://github.com/microsoft/vscode/issues/143778

From @Tyriar: 

> We could add a dedicated 20px column there when shell integration is on, regardless of split status? Similar to how disabling folding will hide the folding column in the editor.

**Comment by rzhao271** [comment]
When I turn off `terminal.integrated.shellIntegration.decorationsEnabled`, the padding remains.

When I turn off `terminal.integrated.shellIntegration.enabled`, the decorations go away for the current terminal, even though shell integration is still on for the terminal.

Are either of these results expected?

**Comment by Tyriar** [comment]
@rzhao271 I don't think we're considering the `terminal.integrated.shellIntegration.decorationsEnabled` setting currently, could you create a new issue on that?

For `terminal.integrated.shellIntegration.enabled` were you testing for terminals that were not the left-most split? The padding should always be 20px for the left-most terminal so the character grid aligns with the first panel title.

![image](https://user-images.githubusercontent.com/2193314/159713621-670bf8cc-de9f-409d-96ad-c43d64362968.png)

**Comment by meganrogge** [comment]
We are considering that:

https://github.com/microsoft/vscode/blob/e659fcb3975ff587985ab4767bcf599480f6f297/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L498-L501

It's working for me

https://user-images.githubusercontent.com/29464607/159735935-9677761e-d7ab-45e9-8717-8fe6ec24ff31.mov

**Comment by rzhao271** [comment]
I just tested it with a non-leftmost terminal now. I can confirm the padding goes away when I disable the decorations.
When I re-enable them, the padding reappears, but the decorations don't seem to show up for new commands.

**Comment by Tyriar** [comment]
@rzhao271 that one's tracked in https://github.com/microsoft/vscode/issues/145212 already 👍
