### ISSUE TITLE
Unit test failure - StreamDebugAdapter (NamedPipeDebugAdapter) can initialize a connection

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#143967]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=158012&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=0d55b56b-c0b2-5f64-1c6a-62c9163a0d5b

```
Debug - StreamDebugAdapter
       StreamDebugAdapter (NamedPipeDebugAdapter) can initialize a connection:

      Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      + expected - actual
```

**Comment by joaomoreno** [comment]
Just broke again: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=169084&view=logs&j=a5d99aad-4929-5289-bf4a-26b78032353d&t=09f0ef64-9426-5a04-b553-e61db928edd9

**Comment by roblourens** [comment]
Added a timeout to the initialize request which will tell me if that's the part that's timing out, but it's probably not. Any guess @weinand?

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/155801
