### ISSUE TITLE
Code do not inherit environment variables from cmd

### ISSUE THREAD

**Issue by dlindmark** [microsoft/vscode#143960]
I expect that when I start vscode from a cmd that instance of visual studio code should inherit the environment variables from that cmd and no other. However, if I already have a vscode open from another cmd, with other environment variables the new vscode will have the same environment variables set as the one first opened. Even though they are started from cmd:s with different environment variables.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: windows 11

Steps to Reproduce:

1. Open new cmd
2. Run `set foo=bar`
3. Run `code .`
4. check that `foo=bar` in integrated terminal
5. Open fresch cmd
6. Check that `foo` is not set
7. Run `code .` in new cmd
8. Then will `foo=bar` in the new code instance
9. If I would have closed the first code window the second would not have `foo=bar`

**Comment by Tyriar** [comment]
When you launch the first VS Code instance the "main process" is created with its environment. All successive windows share this environment by design.
