### ISSUE TITLE
Related to this, I also get C++ guessed if I open a new untitled file and type:

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#143930]
Related to #143901, I also get C++ guessed if I open a new untitled file and type:
```
<
```
yes just one character. I was attempting to type `<html` which does guess correctly, but I feel like those first few characters that guess C++ is a little much.

For my issue, maybe we wait for like 5 characters at least?

_Originally posted by @TylerLeonhardt in https://github.com/microsoft/vscode/issues/143901#issuecomment-1050259225_

**Comment by JacksonKearl** [comment]
Going to take this in as candidate because a hot fix is easy enough and it gives rise to annoyances like #143901.
