### ISSUE TITLE
name quick fixes that should run on save

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#14399]
testing #14299

Instead (or in addition) I wonder if it would be more useful to name the quick fixes that I want to run on save. This might not be a problem today as only a small subset of problems are auto-fixable but I can see conflicts from warnings that you want to be aware of vs warning you want to auto-magically fix (think of remove unused import).

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-tslint#152
