### ISSUE TITLE
[Request] Move line alt+up/down should autoindent

### ISSUE THREAD

**Issue by ice-blaze** [Microsoft/vscode#14390]
- VSCode Version: 1.6.1
- OS Version: Ubuntu 14.04

I think it would be nice if the moveline feature manage the indentation. For example:

```
hello = "hello"
for i in range(1,10):
    pass                    
```

Move `hello` variable down (current behaviour):

```
for i in range(1,10):
hello = "hello"
    pass
```

Expected behaviour:

```
for i in range(1,10):
    hello = "hello"
    pass
```

**Comment by philippelesaux** [comment]
+1

Was hoping v1.9.0 would include this in their indentation update, but it doesn't look like it.

**Comment by gavinr** [comment]
This is a feature of atom.io that I really wish VS Code had! Glad to see this on the June 2017 milestone. Thanks team!

**Comment by rebornix** [comment]
Already added this feature in Insider. Thanks!

**Comment by wprater** [comment]
> Already added this feature in Insider. Thanks!

@rebornix which PR?

**Comment by gavinr** [comment]
Did this land in v1.14.2? I'm not seeing the expected behavior.

**Comment by rebornix** [comment]
@gavinr right now we didn't turn it on by default on 1.14 yet, you can set `editor.autoIndent` to `true` in your settings file.

**Comment by gavinr** [comment]
@rebornix Thanks for that clarification. When I turn that setting to true, it works! Thanks!
