### ISSUE TITLE
Too many quotes?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#14396]
I have this tslint rule active `"quotemark": [ true,  "double"]` and I see nice error messages ala `''should be " (quotemark)'`. When I select the light bulb tho the code action is a little confusing because I see 3 single quotes and 2 double quotes

<img width="336" alt="screen shot 2016-10-25 at 11 54 46" src="https://cloud.githubusercontent.com/assets/1794099/19681542/13d1e314-9aaa-11e6-859d-6ad536974ae3.png">

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-tslint#151
