### ISSUE TITLE
Support alternate git installation

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode#143980]
Recently I updated my system git installation and decided to try using the new `zdiff3` config option for `conflictStyle`. However when I used any built-in git commands in VSCode I would get an error complaining about an unrecognized config option. I would like an option to set an alternate git installation from the one built-in to VSCode. If this isn't practical I should at least be able to easily discover the version of the current git installation so I can know what features are supported.

**Comment by yume-chan** [comment]
> complaining about an unrecognized config option

What's exactly the error message?

> from the one built-in to VSCode

Code doesn't ship with Git, it calls the system one.

> set an alternate git installation

`git.path` setting.

**Comment by diminutivesloop** [comment]
That's good to know. I can't reproduce the error anymore even with that setting enabled so hopefully it was just a fluke.
