### ISSUE TITLE
node2: error message "Exception evaluating `process.pid`: . Will try again later."

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#14398]
Testing #14341:

VSCode Version: 1.7.0
node-debug2: 1.7.0
node: v6.5.0
OS Version: macOS 10.11.6

Steps to Reproduce:

1. run any node program with node2

Observe: a message "Exception evaluating `process.pid`: . Will try again later." shows up on the debug console.

![2016-10-25_11-57-57](https://cloud.githubusercontent.com/assets/1898161/19681686/b49d5ae4-9aaa-11e6-9cf0-fc0215259a23.png)

**Comment by roblourens** [comment]
Haven't seen it, but it shouldn't really be logged as an error anyway.

**Comment by rebornix** [comment]
Tried plain nodejs project and extensions, but haven't seen it.
