### ISSUE TITLE
"Simple Browser" is unable to view https sites with self-signed certs

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#143919]
Issue Type: <b>Bug</b>

it seems like a pretty common development scenario to test https browsing using a self-signed cert.

opening the "Simple Browser" window and navigating to `https://<hostname>` serving a self-signed cert just shows a blank window. the `Log (Main)` output window shows:

```
[2022-02-24 14:09:28.945] [main] [error] CodeWindow: failed to load (reason: ERR_CERT_AUTHORITY_INVALID, code: -202)
```

Opening the same URL in Chrome (on Windows) shows the "Your connection is not private" window with an 'Advanced' button and an opportunity to circumvent the certificate warning.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-19041-Microsoft
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.66GB (1.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2901)|
|Memory (System)|47.66GB (1.70GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.34GB (4.53GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.34GB (4.53GB free)|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.74.0
remote-ssh-edit|ms-|0.74.0
remote-wsl|ms-|0.64.2

</details>

**Comment by hello-smile6** [comment]
Related to Electron webviews

**Comment by mjbvz** [comment]
We actually don't use electron's webviews, it's all normal iframes

**Comment by hello-smile6** [comment]
> We actually don't use electron's webviews, it's all normal iframes

Then must be something with how electron displays iframes.

**Comment by mjbvz** [comment]
After more consideration, I'm closing this as out of scope. As the name suggests, the simple browser is intentionally very simple and I don't think it's worthwhile to go mucking around with electron to let it show sites with self-signed certs

**Comment by gjsjohnmurray** [comment]
Integrated Browser gives me a warning when I visit a site with a self-signed cert. It allows me to proceed if I choose.
