### ISSUE TITLE
Reading file that is constantly being modified causes a crash

### ISSUE THREAD

**Issue by npandrei** [Microsoft/vscode#1439]
I have a log file of 27 MB to which messages are constantly being written. If I open with Code, then it will crash after about 2-3 seconds.

**Comment by alexandrudima** [comment]
@bpasero I think we always read the entire file content again when the file changes on disk, right?

We need to investigate if we have any memory leaks that cause this OOM

**Comment by bpasero** [comment]
@npandrei is this file open all the time in the editor?

**Comment by npandrei** [comment]
@bpasero Yes, the file is opened all the time in the editor.

**Comment by bpasero** [comment]
@alexandrudima in that case, yes the file is being read from disk everytime there is a change. I am not sure how this could be optimized and yeah there is a chance of leakage during this process. It should be easy to capture this from the profile tab in the inspector actually.

**Comment by bpasero** [comment]
This looks like a good chance for endgame leak testing.

**Comment by jrieken** [comment]
I don't see leakage with a smallish file (80KB) which shows in the editor and updates every 100ms. My guess is that during the event we open the file while we still have its old contents in memory - so effectively doubling the size and thereby killing it

```
var uuid = require('node-uuid');
var fs = require('fs');
var path = require('path');

console.log('starting');

setInterval(() => {
	try {
		fs.appendFileSync(path.join(__dirname, 'large.txt'), uuid.v4() + '\n');
	} catch (e) {
		console.error(e);
	}

}, 100);

```

**Comment by jrieken** [comment]
Profiling what happens reveals a few (low hanging) performance issues. 

* StopWatch#start/stop is slow (it uses the performance.now which takes too long for what it does)
* BaseTextEditorModel#update first run `Model#getValue` before `Model#setValue` (to check for changes) which is a *big* hit on perf (20%). Also that extra string _will put pressure on the heap_.

**Comment by jrieken** [comment]
![screen shot 2016-03-15 at 14 22 47](https://cloud.githubusercontent.com/assets/1794099/13779130/dbefa85a-eab9-11e5-9308-8cfdc351d187.png)
[large_file_update.cpuprofile.zip](https://github.com/Microsoft/vscode/files/173981/large_file_update.cpuprofile.zip)

**Comment by jrieken** [comment]
@bpasero/@alexandrudima I suggest you guys find a better way of comparing a string with an existing model (without constructing the whole model string)

**Comment by bpasero** [comment]
@alexandrudima I pushed the change to avoid getValue() but I am leaving it up to you to change something about StopWatch

**Comment by alexandrudima** [comment]
I have removed the usage of performance.now() from the tokenization. I think there are still some good optimization opportunities in this case, such as:
- stream the contents of the file (this would help in all cases)
- detect specifically the content appended case (such as log files that get content added at the bottom) and don't create a new view model, but translate the diff into a model edit.

**Comment by bpasero** [comment]
@alexandrudima yes +1 for post GA :)

**Comment by bpasero** [comment]
@alexandrudima interesting thought about the model append case, I wonder if the setValueIfChanged() method could be smart about the RawText that I insert: it could detect the append case and do a model edit that would even preserve the undo history.

I wonder how common the append case is in real life work though...

**Comment by alexandrudima** [comment]
This no longer reads to a crash. I have tested with:

Generate the initial large file
```js
var fs = require('fs');

var contents = [];
for (var i = 0; i < 100000; i++) {
	contents.push('Just a log entry Just a log entry Just a log entry Just a log entry Just a log entry Just a log entry ' + i);
}
fs.writeFileSync('test.txt', contents.join('\n'));
```

Append to the file every second:
```js
var fs = require('fs');

setInterval(function() {

	fs.appendFileSync('test.txt', 'Another line ' + new Date() + '\n');

}, 1000);
```

I then opened the file in the workbench for 5 minutes, seeing the lines as they come in. I've also profiled this, and most of the time is spent in reading the 10MB file again and again and again... Replacing the entire buffer with the new value takes in the order of 100ms which I guess is acceptable for a 10MB file.
