### ISSUE TITLE
GitHub repository not syncing changes correctly

### ISSUE THREAD

**Issue by macccorehenni** [microsoft/vscode#143935]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 
1.64.2
f80445acd5a3dadef24aa209168452a3d97cc326
x64
- OS Version:
Debian GNU/Linux 11 (bullseye) through ChromiumOS terminaVM
Steps to Reproduce:
not clear why it's happening
![Screenshot 2022-02-24 5 27 55 PM](https://user-images.githubusercontent.com/93945758/155638219-fa720f4d-d1da-4cbd-8f9a-50778062757c.png)
![Screenshot 2022-02-24 5 23 37 PM](https://user-images.githubusercontent.com/93945758/155638222-699dd6a0-518d-4776-8f79-d2c2c7e5dc5d.png)
I tried using .gitignore, reverting the changes, making a new master, and the issue still occurs.
I am not able to reproduce the issue on a seperate device running the same OS.

**Comment by lszomoru** [comment]
@macccorehenni, could you please elaborate on the issue? Is the issue that you are opening a folder/workspace in VS Code and the `vit` file is listed as a modified file? If you click on the file, what does the `diff` editor show? What happens when you revert the change, and reopen the folder/workspace?

**Comment by macccorehenni** [comment]
The diff editor doesn't show any changes. I don't know if that's just a git
issue, or what?

**Comment by lszomoru** [comment]
@macccorehenni, so if I understand correctly, the `vit` file, appears in the list of files that have changes, but when you click on the file itself, the `diff` editor loads but it does not seem to show any changes. Is there a chance that the file only has white space differences? In the upper right hand corner of the diff editor there is a button to toggle white space differences. Does clicking that button reveal the difference in the file?

![image](https://user-images.githubusercontent.com/3372902/162481683-f7406f49-6efe-4f3d-9445-a76fd64a9d15.png)

**Comment by macccorehenni** [comment]
Perhaps.
