### ISSUE TITLE
Holding ctrl should not hide terminal link hover/highlight

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#143982]
![Recording 2022-02-25 at 12 15 15](https://user-images.githubusercontent.com/2193314/155793431-a5e3b7fd-810f-4c64-9c84-7dd0ad803f15.gif)

**Comment by meganrogge** [comment]
isn't that caused by this?

https://github.com/microsoft/vscode/blob/2517c1f4b2ea5233b2e7e5ef19df4cb1efe3569f/src/vs/workbench/contrib/terminal/browser/links/terminalLink.ts#L151-L158

**Comment by meganrogge** [comment]
same thing happens on mac but with `alt`. 

Commenting this out fixes the issue
https://github.com/microsoft/vscode/blob/2517c1f4b2ea5233b2e7e5ef19df4cb1efe3569f/src/vs/workbench/contrib/terminal/browser/links/terminalLink.ts#L76-L80

**Comment by Tyriar** [comment]
We might only want to do that for low confidence links? Looks like we can figure this out pretty easily for next month.

**Comment by Tyriar** [comment]
Regressed due to https://github.com/microsoft/vscode/pull/128362 in July 2021 🤦
