### ISSUE TITLE
Terminals can't run newly installed commands when re-opening a folder/window as long as vscode is still running as a process

### ISSUE THREAD

**Issue by shenoy-anurag** [microsoft/vscode#143996]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

VS Code Version: 1.64.2

Electron: 13.5.2

OS Version: Windows_NT x64 10.0.19044

OS: Windows 10

Extensions:
- Debugger for Java
- Extension pack for Java
- Go
- Jupyter
- Jupyter Keymap
- Jupyter Notebook Renderer
- Language Support for Java by Redhat
- Live Share
- Maven for Java
- Project Manager for Java
- Pylance
- Python
- test Runner for Java
- Visual Studio Intellicode

Steps to Reproduce:

1. Have VSCode open as a process.
2. Install ruby+devkit from <https://rubyinstaller.org/downloads/>. I assume this happens with any new software install.
3. Open a new folder/project.
4. The new terminal within VSCode cannot recognize the newly installed commands such as `ruby -v` or `bundle add webrick`.

A new terminal should always be able to run the latest commands/software added to PATH.

However, vscode seems to use the same terminals, until you close all vscode windows and stop the process.

Upon restarting, the new terminals are now able to recognize the commands.

**Comment by hello-smile6** [comment]
Can reproduce. To test:
1. Open Visual Studio Code.
2. Download a program and put it in an empty directory.
3. Add that folder to your path environment variable.
4. Open a new terminal and try to run your program.

I noticed this before but never thought to report it as a bug.
