### ISSUE TITLE
node2: running mocha tests shows empty lines on debug console

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#14395]
Testing https://github.com/Microsoft/vscode/issues/14341:

- VSCode Version: 1.7.0
- node-debug2: 1.7.0
- OS Version: macOS 10.11.6

Steps to Reproduce:

1. open vscode-node-debug project
2. run mocha tests with node2

Some mocha test output is followed by an empty lines:

![2016-10-25_11-49-58](https://cloud.githubusercontent.com/assets/1898161/19681403/8879c23c-9aa9-11e6-832f-dc42dc7bee2b.png)

Whereas running tests with node shows this:

![2016-10-25_11-54-19](https://cloud.githubusercontent.com/assets/1898161/19681459/c66566e6-9aa9-11e6-8ed3-a53bb526d0b4.png)

**Comment by roblourens** [comment]
For some reason, I only see this in vscode-node-debug and not in my projects that use Mocha. But it has to do with the color control characters. Fixed, thanks.
