### ISSUE TITLE
[Node 2] Previews for objects and arrays are not shown in Debug console

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#14400]
Testing #14340

- VSCode Version: Insiders
- OS Version: Mac OS

Steps to Reproduce:

1. Have a simple object say
```
myObject = {
a: 1
b: 2
c: 3
d: 4
}
```
2. Look for this object in debug console

Current Debug shows the preview

![image](https://cloud.githubusercontent.com/assets/10746682/19681757/fa81beba-9aaa-11e6-826d-38cb16068f6c.png)

Debug 2 shows all the properties

![image](https://cloud.githubusercontent.com/assets/10746682/19681770/0b66248c-9aab-11e6-84a6-d5b7df002768.png)

**Comment by roblourens** [comment]
One difference with node2 that I should have mentioned - I show up to 8 properties in the console, because there's more room, and only 3 elsewhere :)

@weinand FYI. I also truncate all properties to 50 characters.

**Comment by weinand** [comment]
@roblourens I will adopt that for node-debug too.
