### ISSUE TITLE
debug repl: sometimes intellisense comes into my way...

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#14405]
- VSCode Version: 1.7.0

Steps to Reproduce:

- in debug console type 'process.env'
- intellisense appears and shows a rather unhelpful "env" suggestion.
- press enter: the "env" suggestion disappears but the evaluate is not triggered
- press enter again: now  'process.env' is evaluated

I would prefer not to see intellisense in this case and have the first enter start the evaluation.

**Comment by isidorn** [comment]
Dup of #11944
