### ISSUE TITLE
SCM input box restores already-committed messages

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#144013]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Write a commit message and commit using the SCM viewlet
2. Reload or reopen the same workspace later
3. :bug: the commit message is restored to the input box even though I already created a commit applying that message

**Comment by joyceerhl** [comment]
Saw this twice in insiders.vscode.dev today. Even if I delete it, the stale commit message comes back on a window reload.

**Comment by lszomoru** [comment]
I will try to take a look at this one tomorrow.

**Comment by lszomoru** [comment]
Tried to repro/debug this issue today without much luck. Do you by any chance have a consistent repro?

**Comment by joyceerhl** [comment]
Not yet unfortunately, I see it happen quite persistently for some repos.

**Comment by lszomoru** [comment]
I will optimistically close this as I have refactored the code that clears the commit message. Let me know if you see this again.
