### ISSUE TITLE
Debugging controls annoying spot & useless auto widget inspector opening 

### ISSUE THREAD

**Issue by SwiftyFlow** [microsoft/vscode#144002]
Maybe we can and I simply can't find how but...

On mac, on VSCode, developing flutter projects, when we run/test the app... 

I know we can move the debugging controls (play/pause/stop/jump over, hot reload, ...) but I can only move it at useless spots where it's always over the file names and other useful things. I keep moving that thing around when it should simply be in the left sidebar (where there is soooo much space and where the buttons could be bigger and prettier) ; left sidebar meaning the explorer, search, run/debug, ...

Also since I'm here, I wish I didn't have to close the widget inspector every single time I run the app... I probably never looked at it but when I'll need to I pretty sure I can find it somewhere...

Please add/fix these as they're pretty much an every 10 min frustration that seams like it should have been easy to find if it's in or already a default thing.

**Comment by DanTup** [comment]
> Also since I'm here, I wish I didn't have to close the widget inspector every single time I run the app... I probably never looked at it but when I'll need to I pretty sure I can find it somewhere...

The Widget Inspector tab comes from the Dart/Flutter extensions - please file an issue at https://github.com/Dart-Code/Dart-Code with more details about the issue here so I can take a look. You should be able to just keep the Widget Inspect tab visible and when you re-run the app it'll just re-connect.

**Comment by weinand** [comment]
@SwiftyFlow could the setting `"debug.toolBarLocation": "docked"`address your problem?

**Comment by SwiftyFlow** [comment]
I did try "debug.toolBarLocation": "docked" which is even worst. It was good at first but it completely disappears from time to time and to see it back, I have to quit VSCode as I cannot stop the running app... So I'll just accept it as it is, a pain floating over useful things...

Re the Widget inspector: same thing I'm just gonna ignore the fact that every single run opens a new dedicated tab with this in it... Great concept... But good news is that it has finally be useful once!

![vs](https://user-images.githubusercontent.com/5778905/156145690-b05f0961-127e-410d-9dd3-b84fc346df06.png)

But thanks for your help overall guys!

**Comment by weinand** [comment]
> I did try "debug.toolBarLocation": "docked" which is even worst. It was good at first but it completely disappears from time to time and to see it back, I have to quit VSCode as I cannot stop the running app...

Could you please provide more details about the disappearing "docked debug toolbar" problem.
When does it occur?

> Re the Widget inspector: ...

Since the Widget inspector is not part of VS Code, we cannot do anything about it.

**Comment by SwiftyFlow** [comment]
Could you please provide more details about the disappearing "docked debug toolbar" problem.
When does it occur?

Just randomly. I'm testing my app, all good, no breakpoint nothing interrupting... Going on with my things then at some point I want to fully restart. It's not there. Nothing I can tell...

Since the Widget inspector is not part of VS Code, we cannot do anything about it.
Got that hahaha

Thanks anyway we can close that when you want.

**Comment by DanTup** [comment]
> Re the Widget inspector: same thing I'm just gonna ignore the fact that every single run opens a new dedicated tab with this in it... Great concept... But good news is that it has finally be useful once!

@SwiftyFlow please file an issue at https://github.com/Dart-Code/Dart-Code with details about this, I would like to fix it :-)
