### ISSUE TITLE
Smoke tests time out

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#144064]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=158233&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=fff0fe4e-512d-573e-9d0b-0e9f3e677ab7

**Comment by bpasero** [comment]
The only change I pushed is an update to `playwright` and that seems to have caused almost 100% perf decrease running our web smoke tests.

Reverted in https://github.com/microsoft/vscode/commit/57394140ac85435426c9871bf39c84ea9240000a and files https://github.com/microsoft/playwright/issues/12400
