### ISSUE TITLE
微软账户和GitHub登录失败(The Microsoft account and GitHub login failed)

### ISSUE THREAD

**Issue by zgw0416** [microsoft/vscode#144078]
Issue Type: <b>Bug</b>

windows x64  1.64.2 微软账户和GitHub账号无法登录，登录超时 (Windows10 x64 1.64.2 failed to log in to Microsoft account and GitHub account, and the login times out symptom)

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (6.61GB free)|
|Process Argv|--crash-reporter-id 0abe339e-51cc-4892-94d0-247269eba4ef|
|Screen Reader|no|
|VM|25%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.64.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30442553
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
vscop841:30438915
dsvsc008:30440022
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343
vscaat:30438848
vsnot107cf:30443615

```

</details>

**Comment by zgw0416** [comment]
Hello, developer, modified
Currently, with the latest version of vscode, you cannot log in to Microsoft account and GitHub
Could you please see what the problem is, please

**Comment by zgw0416** [comment]
The login synchronization function of the VScode account is abnormal at present. The specific situation is that the Microsoft account cannot be logged in. GitHub was also unavailable

**Comment by TylerLeonhardt** [comment]
Can you follow these steps so that we can get more information on what's going on?

* Open the Command Palette
* Run the `Developer: Set Log Level...` command
* Choose `Trace`
* _Wait for the issue to happen..._
* Open the Output pane (ctrl+shift+u I think on Windows)
* drop in this issue he contents of the following:
  * `Microsoft Authentication` Output channel
  * `GitHub Authentication` Output channel
  * `Log (Settings Sync)` Output channel
  * `Log (Window)` Output channel

**Comment by zgw0416** [comment]
Hello, developer, follow your instructions
This is what it shows

[2022-03-01 00:52:29.687] [settingssync] [info] Using Settings sync service https://vscode-sync.trafficmanager.net/
[2022-03-01 00:52:29.687] [settingssync] [info] Auto Sync is disabled.

**Comment by TylerLeonhardt** [comment]
I need the contents of:
* `Microsoft Authentication` Output channel
* `GitHub Authentication` Output channel

**Comment by TylerLeonhardt** [comment]
I also would like to see a GIF or video of the issue you are seeing so that I know exactly what you are seeing.

**Comment by zgw0416** [comment]
https://user-images.githubusercontent.com/92322221/156029550-fbb282f7-e3a2-4551-8ca5-084eb77f3b4d.mp4
![caacace016ec1811af7c130f44d4064](https://user-images.githubusercontent.com/92322221/156029640-0b2ec438-218d-4c5d-9892-b22f5c811aaa.png)

**Comment by TylerLeonhardt** [comment]
please still provide:

* Microsoft Authentication Output channel
* GitHub Authentication Output channel

**Comment by TylerLeonhardt** [comment]
No. Do not give me your password.

I am asking for the contents of this:
![image](https://user-images.githubusercontent.com/2644648/156035896-97ce2681-ba16-4daa-b26a-37b7b12e7115.png)

These are the logs of the GitHub Authentication login.

**Comment by zgw0416** [comment]
Hello, I have tested it and now I can log in. Thank you very much. Microsoft and GitHub have logged in normally now.
The Microsoft one requires an email address and can't be logged in using face recognition

**Comment by TylerLeonhardt** [comment]
Glad it's working for you now.
