### ISSUE TITLE
Unable to start vscode from WSL

### ISSUE THREAD

**Issue by levyaraujo** [microsoft/vscode#144099]
Issue Type: <b>Bug</b>

When I type "code" in WSL terminal raise a error:

"/mnt/c/Users/levyaraujo/AppData/Local/Programs/Microsoft VS Code/Code.exe: Invalid argument"

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics     (8 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.91GB (0.97GB free)|
|Process Argv|--crash-reporter-id c36a3202-9bb9-433a-90ce-d0fb22c3c77f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Arch|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics (8 x 3593)|
|Memory (System)|2.81GB (1.97GB free)|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
flask-snippets|cst|0.1.3
remote-wsl|ms-|0.64.2
material-icon-theme|PKi|4.13.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30442553
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrt:30437039
vsrem710cf:30416617
dsvsc009:30440023
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343
vscaac:30438847
n3:30442354
vsnot107:30443614

```

</details>

**Comment by aeschli** [comment]
Can you run with `--verbose` ?

**Comment by levyaraujo** [comment]
Well, I reinstall the Remote - WSL extensions and works

**Comment by levyaraujo** [comment]
The problem was resolved
