### ISSUE TITLE
[EXTENSION] Blocked script execution

### ISSUE THREAD

**Issue by axelthat** [microsoft/vscode#144006]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.2 (Universal)
- OS Version: macOS 12.2.1

Steps to Reproduce:

1. Clone https://github.com/axelthat/vscode-bug.
2. Click Run > Run Without Debugging after opening the project inside vscode.
3. Create a file `a.web` and check developer tools.

I am trying to build a custom editor in vscode. Basically I am trying to show an alert inside webview but I get the following error,

`
main.js:861 Blocked script execution in 'vscode-webview://9a6c171c-2393-4d09-a34d-eaf8088f72d9/index.html?id=9a6c171c-2393-4d09-a34d-eaf8088f72d9&swVersion=4&extensionId=undefined_publisher.web&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-webview.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
`

**Comment by mjbvz** [comment]
Scripts are disabled by default in webviews. You need to enable them by changing the options:

https://github.com/microsoft/vscode-extension-samples/blob/2feab6d8f185417e63eaef73b38dae36a6a5dafb/custom-editor-sample/src/catScratchEditor.ts#L43

**Comment by axelthat** [comment]
Oops I don't know how I missed that. Anyway, thank you so much.
