### ISSUE TITLE
'Command Failed' when excuting `execSync`

### ISSUE THREAD

**Issue by Wybxc** [microsoft/vscode#144094]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.2 f80445acd5a3dadef24aa209168452a3d97cc326
- OS Version: Windows 11 Chinese Home 22000.493

Steps to Reproduce:

1. Open VSCode Developer Tools
2. Execute `require('child_process').execSync('pnpm root -g')` (or other commands)

It raises `Command Failed`:
![image](https://user-images.githubusercontent.com/25005856/155992589-d2022526-ae81-41ed-a5d6-0664e7176524.png)

Outside VSCode, it works well:
![image](https://user-images.githubusercontent.com/25005856/155993817-b6252266-ed8a-48fd-ac43-0956a97ad326.png)

**Because many extensions depends on command executing to work, they failed to start up because of the fault.**

**Comment by weinand** [comment]
@Wybxc What do you mean by "VSCode developer tools" then?
VS Code has a "Toggle Developer Tools" command? Are you using this?

**Comment by Wybxc** [comment]
> @Wybxc What do you mean by "VSCode developer tools" then? VS Code has a "Toggle Developer Tools" command? Are you using this?

Yes.

**Comment by weinand** [comment]
Sorry, but "Toggle Developer Tools" opens "Chrome Dev Tools", which is not a node.js environment.

you said:
> Because many extensions depends on command executing to work, they failed to start up because of the fault.

Only UI extensions run in the browser where they don't have access to node.js API.
Workspace extensions run in node.js and they do have access to node API like  `child_process`.

**Comment by Wybxc** [comment]
I found more infomation about the problem. 

When I run VSCode as administrator, it can run the command and get correct results.
