### ISSUE TITLE
Publish and Sync buttons do not immediately respond.

### ISSUE THREAD

**Issue by mikebronner** [microsoft/vscode#144014]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: macOS 12.2.1

Steps to Reproduce:

1. When working in an SSH Remote project: commit changes.
2. Immediately click on the Publish or Sync button.
3. Note that the button does not immediately respond, but requires the user to wait about 3 or 4 seconds before it actually does something, it appears that background tasks are being performed prior to allowing the button to take action.

Suggestions:
1. Show the button in a disabled state until ready to take action.
2. Better yet, allow the button to be clicked and queue up the action to be performed as soon as it is ready, allowing the user to move on to the next task, as waiting and clicking multiple times is frustrating from a mental flow perspective.

**Comment by lszomoru** [comment]
@mikebronner, apologies for not getting back to you on this until now. Over the last several months we have made several changes in this area introducing the new "action button" in the "Source Control" view. Are you still able to reproduce this issue with the new action button? Thanks!

**Comment by mikebronner** [comment]
Thanks for checking up on this. It appears to have been resolved a while back. :)
