### ISSUE TITLE
VS Code does not implicitly trust empty directories

### ISSUE THREAD

**Issue by schuelermine** [microsoft/vscode#144032]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: NixOS 22.05.20220220.d5f2378 (Quokka)

Steps to Reproduce:

1. Create a new folder
2. Open this folder in VSCode

Expected result:

VSCode trusts the folder, since it is empty

Actual result:

“Do you trust the authors” dialog pops up

**Comment by lszomoru** [comment]
Thank you very much for your feedback. The current behaviour is as intended since the concept of workspace trust operates at the folder path level and it does not factor in the actual contents of the folder as those change over time.
