### ISSUE TITLE
Restore files being developed on Codespaces

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/vscode#144004]
Does this issue occur when all extensions are disabled?: N/A

Hello, I was developing on GitHub Codespaces and unfortunately, it crashed, so I want to know VSCode stores backups of files of Codespaces on Local Machine, it will save my life. Please help me restore my files🙏

**Comment by bpasero** [comment]
@jkeech fyi I am not sure where users can provide issues for Codespaces extension.

**Comment by jkeech** [comment]
This type of request should probably go to GitHub Support via support ticket. https://aka.ms/ghcs-support. General feedback is handled through https://github.com/github/feedback/discussions/categories/codespaces-feedback.

@vedantmgoyal2009, please create a support ticket if you are still having issues. You can also try exporting your changes to a branch even if you can't login to your codespace for some reason: https://docs.github.com/en/codespaces/troubleshooting/exporting-changes-to-a-branch.

**Comment by vedantmgoyal2009** [comment]
Thanks for your reply. I have created a support ticket and I was able to recover my data. I have now made a new codespace and everything is fine now.
