### ISSUE TITLE
VS Code fails to open big files (40GB)

### ISSUE THREAD

**Issue by AnyByte** [microsoft/vscode#144053]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: Windows 11 Pro 22000.527

Steps to Reproduce:

1. Open file that is 40GB and VSCode crashes

**Comment by alexdima** [comment]
@AnyByte When opening a file, VS Code currently loads the entire file in memory. Do you have sufficient RAM on your machine?
