### ISSUE TITLE
Output highlights the empty line

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#14402]
- VSCode Version: Insiders
- OS Version: Mac OS

Steps to Reproduce:

- Open VS Code with output view shown

![image](https://cloud.githubusercontent.com/assets/10746682/19682356/76647c32-9aad-11e6-88ab-03eb30ff68d0.png)

**Comment by isidorn** [comment]
Dup https://github.com/Microsoft/vscode/issues/14360
