### ISSUE TITLE
Editor incorrectly formats python code that uses type annotation

### ISSUE THREAD

**Issue by GregSal** [microsoft/vscode#144026]
Issue Type: <b>Bug</b>

When a python function definition contains output type annotation the editor formatting does not recognize the beginning of the function's doc string.  The doc string is formatted as code and in the next function the code following the end of the docstring is formatted as a multi-line string.

all other code analysis tools, such as IntelliSense and "Go to Definition" work as they should

For example:
```
def true_iterable(variable)-> bool:
    '''Indicate if the variable is a non-string type iterable.
    Arguments:
        variable {Iterable[Any]} -- The variable to test.
    Returns:
        True if variable is a non-string iterable.
    '''
    return not isinstance(variable, str) and isinstance(variable, Iterable)
```
will not format the doc string as a string.
```
def true_iterable(variable):
    '''Indicate if the variable is a non-string type iterable.
    Arguments:
        variable {Iterable[Any]} -- The variable to test.
    Returns:
        True if variable is a non-string iterable.
    '''
    return not isinstance(variable, str) and isinstance(variable, Iterable)
```
will format the do string correctly.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.64GB free)|
|Process Argv|\\Users\\smoke\\OneDrive - Queen's University\\Python\\Projects\\sectionary package\\workspace.code-workspace --crash-reporter-id a49824f5-6796-408e-895d-4601d64fa899|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.2.4
path-intellisense|chr|2.8.0
gitignore|cod|0.7.0
python-snippets|cst|0.1.2
vscode-markdownlint|Dav|0.46.0
python-preview|don|0.0.4
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
gitlens|eam|11.7.0
graphviz-preview|EFa|1.5.0
vscode-great-icons|emm|2.1.82
git-extensions-for-vs-code|for|1.1.3
vscode-python-config|fra|1.4.0
pythonsnippets|frh|1.0.2
vscode-pull-request-github|Git|0.36.2
gc-excelviewer|Gra|4.0.50
todo-tree|Gru|0.0.215
vscode-test-explorer|hbe|2.21.1
python-coding-conventions|igr|0.0.4
vscode-graphviz|joa|0.0.6
vsc-python-indent|Kev|1.14.2
kite|kit|0.147.0
vscode-python-test-adapter|lit|0.7.0
regexp-preview|Lou|0.1.5
git-graph|mhu|1.30.0
gitignore|mic|1.0.1
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.4
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
notepadplusplus-keybindings|ms-|1.0.7
test-adapter-converter|ms-|0.1.5
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.4.1
material-icon-theme|PKi|4.13.0
vscode-xml|red|0.19.1
vscode-yaml|red|1.4.0
visual-regex|rel|0.0.5
code-settings-sync|Sha|3.4.3
indenticator|Sir|0.7.0
regexworkbench|ste|2.0.5
code-spell-checker|str|2.1.7
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.17
Python-extension-pack|wal|1.0.1
vscode-todo-highlight|way|1.0.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30442553
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30440023
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvidc:30438801
helix:30440343
vsnot107cf:30443615

```

</details>

**Comment by IllusionMH** [comment]
/extPython

Formatting provided by extension ensure that you have proper configuration of Python extension or other used formatter, and report in their issue trackers if needed.

**Comment by GregSal** [comment]
duplicate submission
