### ISSUE TITLE
Emoji panel not opened when pressing CTRL-CMD-SPACE on macOs 12.x

### ISSUE THREAD

**Issue by mikebronner** [microsoft/vscode#144010]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: macOS 12.2.1

Steps to Reproduce:

1. In any VSCode window other than keyboard shortcuts, try pressing CTRL-CMD-SPACE to open the emoji picker. This doesn't do anything.
2. The shortcut in the edit window is defined as:
  <img width="289" alt="Screen Shot 2022-02-26 at 7 20 58 AM" src="https://user-images.githubusercontent.com/1791050/155846567-b0eee88b-f9b7-48c3-9d92-e3802edb9f8f.png">
3. My keyboard does not have a function key. I am using a Mac Mini, and the original magic keyboard with num pad from 2017.

4. The system keyboard settings show as follows:
  <img width="644" alt="Screen Shot 2022-02-26 at 7 23 44 AM" src="https://user-images.githubusercontent.com/1791050/155846647-f103c710-6f55-425b-bbd2-2bb942709541.png">
5. I was unable to find a way to customize the shortcut in VSCodes keyboard bindings.

I have reviewed some of the other bugs regarding similar issues, but none described my problem exactly, and the solutions offered there didn't apply to me, because of different OS, hardware, etc.

**Comment by alexdima** [comment]
The keybinding for this menu entry comes from the OS and not from us. See https://github.com/microsoft/vscode/issues/135480#issuecomment-963946617 for how macOS settings would change the keybinding to a "globe" on a laptop with a touch bar. All of this happens outside of our application's control.

**Comment by mikebronner** [comment]
@alexdima This does not appear to be the case. I read that thread you referenced extensively. This is not the globe shortcut. macOS has the shortcut set to CTRL-CMD-SPACE, yet that does NOT work in VSCode.

**Comment by alexdima** [comment]
@mikebronner VS Code doesn't have any code to handle the keybinding `ctrl+cmd+space`. VS Code doesn't have any code to change it to a `"globe"` on laptops with a touch bar. VS Code also doesn't have any code to change it to `fn + E` as it is in your screenshot. I acknowledge that you run into this (it is clear from your screenshot), and I'm sorry about it, but there's nothing we can do on our side to improve things. To my knowledge, it is the OS that assigns that keybinding. 

Actually, it looks like even on my machine it is using sometimes the same unrealisable `fn+E` keybinding. I am using an external keyboard without a `fn` key. Here is for example Safari:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/5047891/156001120-2a2aa769-3b3f-4f18-a774-609e8f783318.png">

**Comment by mikebronner** [comment]
@alexdima Thank you for the update! I didn't realize this, my safari and other apps do the same! This was not that way some time ago, it must be something with macOS. arggg

Thanks for the clarification!
