### ISSUE TITLE
insiders  there are more icons in the upper right corner of the editor

### ISSUE THREAD

**Issue by chenguo666** [microsoft/vscode#144050]
Issue Type: <b>Bug</b>

how to turn off this function ??? help me pls

![QQ截图20220228133426](https://user-images.githubusercontent.com/32004911/155929661-90b4b129-ce75-4059-9e72-aba8aacce5bb.png)

VS Code version: Code - Insiders 1.64.0-insider (9afbea7caab9dd06592ddd98aa4161b43b126d3f, 2022-01-06T05:15:07.481Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.15GB free)|
|Process Argv|--crash-reporter-id 554cfc42-4e4a-487a-a78f-c725325f603c|
|Screen Reader|no|
|VM|57%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.3.0
auto-rename-tag|for|0.1.10
todo-tree|Gru|0.0.215
vscode-power-mode|hoo|3.0.0
vscode-language-pack-zh-hans|MS-|1.64.7
remote-ssh|ms-|0.75.2022022515
remote-ssh-edit|ms-|0.75.2022022515
vetur|oct|0.35.0
LiveServer|rit|5.7.4
tabnine-vscode|Tab|3.5.26
vscode-import-cost|wix|2.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstartedc:30421358
vsclayoutctrt:30405800
dsvsc009:30440021
pythonvspyt640:30438691
vsbas813:30436447
vscscmwlcmc:30428972
azactmsalcf:30432849
vscgsvid1:30433757
pynewfile477cf:30443520
vsnot107:30443614

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by chenguo666** [comment]
> 请使用 Start Extension Bisect 命令来调查问题是否是由您的扩展之一引起的。

thanks I found the problem
