### ISSUE TITLE
Vscode.dev accounts not loading

### ISSUE THREAD

**Issue by ZeroXiphYT** [microsoft/vscode#144020]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: vscode.dev
- OS Version: Chrome OS Version 98.0.4758.107 (Official Build) (64-bit)

Steps to Reproduce:

1. Open vscode.dev and sign it with a github account
2. open vscode.dev again later(same day,  2 days, weeks etc...) then when you click accounts it will keep saying loading

this means for some reason that emmet and autocompletion stop working but intellisense only shows words I already wrote and not actual code so if I write hello world in a p tag in html it won't show p or any tag but just hello world, thanks.
Edit: Bug won't always happen but happens 98% of the time for me, also you can check if the bug is happening or not if you click "Open Remote Repository" or checking the accounts if it says loading, if when you click open remote repository the screen to open them doesn't show up that means that the bug is happening

**Comment by ZeroXiphYT** [comment]
https://user-images.githubusercontent.com/94765932/155908342-cb6eca2a-86f2-41d2-91df-9b473c80e6ee.mp4

**Comment by TylerLeonhardt** [comment]
That gif doesn't seem related to you having issues logging in to GitHub. We try to have 1 issue relate to 1 problem users are seeing.

Can you place include a gif of the vscode.dev & github sign in issue you were seeing?

As for the tab issue you are seeing, can you open a new issue for it? Also, it does sound like an issue that an extension is contributing... it's a good idea to try out [Extension Bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect#_welcome-extension-bisect) to see if you can narrow down the extension that might be causing the issue.

**Comment by ZeroXiphYT** [comment]
its not an extension and,
![a39c2b91-4358-413b-b03c-6670b128ed86](https://user-images.githubusercontent.com/94765932/156487044-f492c5b9-ee25-4a6c-bbba-936b93546545.gif)

**Comment by TylerLeonhardt** [comment]
@ZeroXiphYT we just did a new release yesterday. Can you give this another try and see if you still see the behavior? If you do, I need you to open the Output panel (I think it's Ctrl+Shift+U) and in the dropdown can you share what's in:
* `Log (Extension Host)` or `Log (Worker Extension Host)`
* `GitHub Repositories`

**Comment by ZeroXiphYT** [comment]
@TylerLeonhardt My output doesn't show


-  `Log (Extension Host)` or `Log (Worker Extension Host)`
- `GitHub Repositories`
and how do I update vscode.dev or does it automatically update

**Comment by TylerLeonhardt** [comment]
Can you show me what's in your browsers Developer Tools console? That may have useful information in this case.

**Comment by ZeroXiphYT** [comment]
my dev tools are very buggy and just crash my chromebook

**Comment by TylerLeonhardt** [comment]
I'm sorry to hear that :( I need that information to be able to help, unfortunately
