### ISSUE TITLE
Performance issue with VScode using Golang

### ISSUE THREAD

**Issue by rexdivakar** [microsoft/vscode#144095]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.2
- OS Version: Windows 10 Pro (64)

Steps to Reproduce:

Steps to reproduce on Windows 10 , latest build:

1. Install Go Lang from the official site
2. Install Visual Studio Code
3. Enable Go support in Visual Studio
4. Create this program (saved as main.go) in Visual Studio Code:
` package main

import "fmt"

func main() {
   fmt.Println("Hi there!")
}`

5. Upon writing scripts using VScode in golang language the editor freezes due to Antimalware scan from Windows Defender

Weirdest part is that this doesn't happen with Python or using Goland IDE (from Jetbrains), Kindly help me fix this issue.

![2022-02-27 (2)](https://user-images.githubusercontent.com/15235122/155997081-e2325e3a-5e22-4de8-b99a-e426d74fb34a.png)

**Comment by TylerLeonhardt** [comment]
\extGo
