### ISSUE TITLE
[html] suggest `_self` and `_blank`

### ISSUE THREAD

**Issue by mohamad228** [microsoft/vscode#144037]
hi i have problem with some attribute 
forb example in target attribute didnt suggest me
 _self or _parent _blank 
even with ctrl space
* language is on html

**Comment by rzhao271** [comment]
I still don't see those suggestions when I start typing `<a href="test" target="`

**Comment by aeschli** [comment]
Updated through 66b9a8a460a18a6fd0a249d114ee790d84d48569
