### ISSUE TITLE
Notebook Controller interruptHandler invoked automatically by VS Code when it should not be

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#144043]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders
- OS Version: WSL

Steps to Reproduce:

1. Create a notebook 
2. Select a kernel & the previous controller gets interrupted.
3. Or open an existing notebook and the controller gets interrupted

**Problems**
* If opening an existing notebook, the nothing has been executed, hence interrupting the kernel just when opening a notebook is not right.
* When switching kernels, interrupting the previous kernel is also in my opinion not the right thing. VS Code is now making the decision to interrupt previous kernels instead of the user. I.e. its now no longer possible to run a cell against a remote kernel & switch the kernel to something else while having the code still running in the kernel. 
* In the case of remote kernels, we have the ability to connect to an existing remote kernels, i.e. we should be able to open a notebook that was used to run code against a remote kernel. However now the first thing that happens is the kernel is interrupted (hence any code that was running is now stopped - & that's not the desire user experience - execution can run for hours, merely opening a notebook could now stop it without the users consent).

I think this may have been done as a cleanup, not sure.
If that's the case, then extension authors should own cleaning up of resources, extensions already get events when a kernel is selected/un-selected. Thus extension authors can decide whether to interrupt/kill the kernels accordingly.

I.e., interrupting kernels should be left for the users, I don't think VS Code shouldn't dictate how and when kernels are interrupted.

**Comment by drykovanov** [comment]
By the way, Is it possible to avoid interrupting kernel when closing notebook tab? We have remote kernel which execution can continue for really long time.

**Comment by roblourens** [comment]
Yeah, I made changes to interrupt in some cases that I thought were obvious, as a convenience to notebook implementors, but I see the issue.
