### ISSUE TITLE
Test API: UI always switches to explorer after running tests

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode#144005]
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Steps to reproduce:
1. Use the sample unit test provider from here: https://github.com/microsoft/vscode-extension-samples/tree/main/test-provider-sample
2. Switch to test explorer
3. Run a testcase

Result:
After the test case has finished, the UI is switched from the test explorer to the file explorer.

Expected result:
vscode stays in the current test explorer.

The behavior is very annoying as you always have to switch back manually.
I have noticed this behavior also in my own test provider, so it seems to be a general issue.
See here the behavior:

![testapi](https://user-images.githubusercontent.com/3081973/155841544-6aaca1e2-394f-4a5b-9562-b7c386e86a96.gif)

**Comment by connor4312** [comment]
This is configurable with the `testing.openTesting` setting
