### ISSUE TITLE
Can't save

### ISSUE THREAD

**Issue by liukdev** [microsoft/vscode#144011]
Using mountain duck to mount directories via sftp from ubuntu 20.04 servers.
VSC v1.64.2 on macOS Monterey very often can't save edited files, switching back to v1.63.2 everything works perfectly.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by liukdev** [comment]
the insiders version seems to work fine
