### ISSUE TITLE
Option to indent under access specifiers.

### ISSUE THREAD

**Issue by ChrisBlueStone** [microsoft/vscode#144049]
There currently doesn't seem to be an option to indent class members that are listed under access specifiers. The only related option is `cpp_indent_access_specifiers` which indents the access specifiers themselves, but when set to true, they are aligned with the members.

With `cpp_indent_access_specifiers=false`:
```cpp
class A
{
public:
    void func();
private:
    int member;
};
```

With `cpp_indent_access_specifiers=true`:
```cpp
class A
{
    public:
    void func();
    private:
    int member;
};
```

No option available to achieve the following:
```cpp
class A
{
    public:
        void func();
    private:
        int member;
};
```

**Comment by IllusionMH** [comment]
/extCpp

C++ functionality provided by extension and this should be reported/requested there.
