### ISSUE TITLE
Cannot tab through modal buttons

### ISSUE THREAD

**Issue by irasanchez** [microsoft/vscode#144030]
Issue Type: <b>Bug</b>

Try to close VSCode with an unsaved file
Modal with warning should pop up
The modal has 3 buttons
Expected -- To be able to hit "tab" and "enter" to interact with the buttons
Actual -- Cannot use "tab" key to navigate these buttons

VS Code version: Code 1.64.2 (Universal) (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.82GB free)|
|Process Argv|--crash-reporter-id 6a816f95-1fc0-418d-ba59-1daad013b284|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.7.7
npm-intellisense|chr|1.4.1
dart-code|Dar|3.34.0
vscode-markdownlint|Dav|0.46.0
gitlens|eam|11.7.0
prettier-vscode|esb|9.3.0
copilot|Git|1.7.5118
remotehub|Git|0.24.0
vscode-pull-request-github|Git|0.36.2
headwind|hey|1.7.0
git-graph|mhu|1.30.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.4
jupyter|ms-|2022.1.1301854968
vscode-github-projects|Pod|1.0.0
html-to-jsx|ria|0.0.1
vscode-markdown-paste-image|tel|0.18.4
vscodeintellicode|Vis|1.2.17
quokka-vscode|Wal|1.0.448

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30442554
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
vscop841:30438915
dsvsc009:30440023
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343
vscaat:30438848
vsnot107cf:30443615

```

</details>

<img width="287" alt="image" src="https://user-images.githubusercontent.com/14080134/155892041-8a1d8ca7-e7c4-42a1-a83d-ee047c07a257.png">

**Comment by bpasero** [comment]
https://www.idownloadblog.com/2015/03/15/tab-key-between-buttons-mac-os-x/
