### ISSUE TITLE
Method invocations are coloured differently in Monokai theme

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#14406]
Testing #14310  

- VSCode Version: Insiders
- OS Version: Mac OS

![screen shot 2016-10-25 at 12 34 26](https://cloud.githubusercontent.com/assets/10746682/19682807/9a9c8638-9aaf-11e6-86af-ee73c7a77abb.png)

**Comment by aeschli** [comment]
'search' is considered a library function and Monokai gives library functions a different color.
