### ISSUE TITLE
Certain files do not have a corresponding icon when using .txt or .md extension

### ISSUE THREAD

**Issue by Semphriss** [microsoft/vscode#144143]
Certain files, like CHANGELOG, CONTRIBUTING, TODO etc. have special icons. However, if they are suffixed with `.md` or `.txt`, they sometimes no longer have their icons.

I would like that such special files also have those icons when they have extensions in their names; many OSes support linking a program to open files with certain extensions (e. g. a markdown reader for .md, or a text editor for .txt). Although VSCode does not have this problem, many of my users use the regular Notepad to read those files; for their convenience, I need to append all my documentation files with .txt (or .md) so that they can easily open those files in their preferred program.

For convenience, here are the pairings that have special icons:

| File name | .md | .txt | (no extension) |
| --- | --- | --- | --- |
| Readme | x |  |  |
| Changelog | x |  | x |
| Changes | x |  |  |
| Version | x |  | x |
| Licen[cs]e | x |  | x |
| Copying |  |  | x |
| Compiling |  |  | x |
| Contributing |  |  | x |
| Todo |  |  | x |

I would like to propose to make it so all pairings have the special icon corresponding to the file name.

**Comment by aeschli** [comment]
This is related to https://github.com/microsoft/vscode/pull/144144, correct?

It's the seti theme that has the mappings of icons to the file names. Please create a PR against https://github.com/jesseweed/seti-ui
