### ISSUE TITLE
Extra confirmation message seems weird

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#14412]
testing #14291

Install an extension and see the extra confirmation message about it (attached below). It feels like we show that message because our UI fails to indicate that an extension pack is different from an extension. Instead of the message why don't we change the 'Install' button to something like _Install Extension Pack_

<img width="769" alt="screen shot 2016-10-25 at 13 19 44" src="https://cloud.githubusercontent.com/assets/1794099/19684125/d96ebeac-9ab5-11e6-804b-a8d4dc39428c.png">

**Comment by ramya-rao-a** [comment]
I agree with @aeschli's comment from the linked duplicate issue.
If I have chosen to install an extension pack and can read all the extensions that come as part of it, then why the extra prompt?

**Comment by sandy081** [comment]
Marking this as a dup as it is listed in UX improvement item #18354

**Comment by sandy081** [comment]
Installing an extension with dependencies should install the dependencies similar to npm install. 

Hence we decided to remove the message that tells about dependencies and without any additional UI.
