### ISSUE TITLE
Work items from visualstudio.com should not be visible when they are in a resolved or fixed state.

### ISSUE THREAD

**Issue by cj13579** [Microsoft/vscode#14416]
- VSCode Version: 1.6.1
- OS Version: Windows 10.0.14393.0

Work items from visualstudio.com should not be visible in VSCode when they are in a resolved or fixed state.

![vs-code-resolved](https://cloud.githubusercontent.com/assets/1965454/19684317/f17ff048-9a8c-11e6-9e19-d4f25b16fa8c.png)

I think that the item is visible in vscode because there is no filter on the list and it is showing all items that are assigned to me.

![bug1_vs_resolved](https://cloud.githubusercontent.com/assets/1965454/19684553/34099d28-9a8e-11e6-8963-725b302a4780.png)

**Comment by weinand** [comment]
Please file this against the extension you are using.
