### ISSUE TITLE
settings.json eror

### ISSUE THREAD

**Issue by firsy04** [microsoft/vscode#144164]
Issue Type: <b>Bug</b>

i want to change the font size, zoomlevel, and others but it doesn't work 
this is what i typed on it:
{
    "editor.fontSize": 18,
    "window.zoomLevel": 0,
    "workbench.colorTheme": "Noctis Minimus",
    "workbench.iconTheme": "vscode-icons" ,
}
I've saved and downloaded the extensions but the size and others are still the same, nothing change

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.80GB free)|
|Process Argv|--crash-reporter-id 5e0b8f5c-46e2-4cc3-9a67-f973696fb714|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.4
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
vscode-icons|vsc|11.10.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30442554
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30440023
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343
vsnot107cf:30443615

```

</details>

![Screenshot (886)](https://user-images.githubusercontent.com/100686659/156155434-6ac97354-cc0e-4b6e-9f82-a6918d531fac.png)
)

**Comment by rzhao271** [comment]
I notice you're in a workspace. In the command palette (F1 key), run the "Preferences: Open Workspace Settings (JSON)" command. The settings file for workspaces is in a different location.
Another alternative is to create a `.vscode` folder within each folder of the workspace, but then you end up implementing folder-level (resource) settings rather than workspace settings.
