### ISSUE TITLE
日本語入力すると表示が乱れる

### ISSUE THREAD

**Issue by Yuki311** [microsoft/vscode#144147]
Issue Type: <b>Bug</b>

During Japanese input, another line is displayed.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id d47dfb24-2b85-449b-ad40-2c874b15aa7f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.2
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.2
empty-indent|Dmi|0.2.0
prettier-vscode|esb|9.3.0
lana|Fin|1.4.1
todo-tree|Gru|0.0.215
vscode-phpfmt|kok|1.0.31
dotenv|mik|1.0.1
zenkaku|mos|0.0.3
material-icon-theme|PKi|4.13.0
vscode-xml|red|0.19.1
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode|sal|54.2.0
salesforcedx-vscode-apex|sal|54.2.0
salesforcedx-vscode-apex-debugger|sal|54.2.0
salesforcedx-vscode-apex-replay-debugger|sal|54.2.0
salesforcedx-vscode-core|sal|54.2.0
salesforcedx-vscode-lightning|sal|54.2.0
salesforcedx-vscode-lwc|sal|54.2.0
salesforcedx-vscode-soql|sal|54.2.0
salesforcedx-vscode-visualforce|sal|54.2.0
trailing-spaces|sha|0.3.1
code-spell-checker|str|2.1.7
codetour|vsl|0.0.58

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc008:30440022
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvid2:30438800
helix:30440343

```

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com).

**Comment by Yuki311** [comment]
Thank you for your reply, updating to ver. 1.6.5 has improved the display disorder from before. However, the display is still corrupted when typing text, as in the gif I have attached.

https://gyazo.com/a59faf595dca6dc6d52b196d398a1b5f

**Comment by Umigishi-Aoi** [comment]
I have same probrem.

I want to write Japanese in .dart file and some files.
But input is misaligned.

Braces nest is deeper , the misaligned is bigger.

I record this problem in .dart file.

https://user-images.githubusercontent.com/84505829/158066462-660042ed-1e45-45d0-97a8-8db666b06e65.mov

Please tell me the solution.

Thank you.

**Comment by Yuki311** [comment]
> Thank you for your reply, updating to ver. 1.6.5 has improved the display disorder from before. However, the display is still corrupted when typing text, as in the gif I have attached.
> 
> https://gyazo.com/a59faf595dca6dc6d52b196d398a1b5f

I’m sorry.
I had mistakenly thought that the VSCode update had slightly improved the problems we are having.

Depending on the situation in which you are typing, the disorder in Japanese input can be significant.

**Comment by Umigishi-Aoi** [comment]
I solved this problem.

I disabled "Pubspec Assist" Extension, so this problem is solved.
Please try this.

**Comment by Yuki311** [comment]
This problem has been resolved.
Thank you very much.
