### ISSUE TITLE
Reload button overkill

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#14415]
testing #14291

* Install an extension pack, reload, 
* uninstall the extension pack
* 🐛 the extension viewlet is full of 'Reload buttons' showing that we might not be using the right UX for that...

<img width="393" alt="screen shot 2016-10-25 at 13 38 41" src="https://cloud.githubusercontent.com/assets/1794099/19684622/95bdf01c-9ab8-11e6-9843-bf10b8f50c60.png">

**Comment by sandy081** [comment]
Duplicates #14384
