### ISSUE TITLE
Support dark and light high contrast theme types

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#144193]
Adding the new light high contrast theme (#143398) uncovered challenges across the codebase when attempting to render unique styles or assets based on the theme settings. [Here's a simple example ](https://github.com/microsoft/vscode/issues/143765#issuecomment-1049156614)where the letterpress SVG used in an empty editor view was hardcoded for the original dark HC theme. 

## Proposal

Currently we only expose a general high contrast theme type. A couple of things I think would be worth supporting:
- Split `hc` into something like `hc-light` and `hc-dark`
- Support `workbench.preferredLightHighContrastColorTheme` and `workbench.preferredDarkHighContrastColorTheme` if we're able to pick up the OS mode as an additional input like we do for regular dark/light themes.

Ideally the outcome here is that we can continue to use the theme type as an input in both logic (e.g. `this.theme.type === ColorScheme.LIGHT_HIGH_CONTRAST` and in stylesheets (e.g. `.hc-light` or `.hc-black`).

It would be great to get any additonal thoughts/opinions. cc @isidorn @aeschli @misolori

**Comment by misolori** [comment]
I think this makes sense and we'll likely start seeing requests for this (to create a new Light HC based off the new version) so 👍

**Comment by isidorn** [comment]
I agree with the proposal, it makes sense. I know @aeschli is buried in issues so maybe somebody else can drive this debt work? Martin do you have suggestions?

fyi @bpasero

**Comment by bpasero** [comment]
Splitting `hc` up into `hc-light` and `hc-dark` resonates with me.

**Comment by aeschli** [comment]
Yes, makes sense.

**Comment by aeschli** [comment]
I'm happy to do the workbench theme service changes if you look at the css fixes.
Currently all colors have default colors for `light`, `dark` and `hc`. That means we would need new defaults for hc-light as well.

So it's quite some work...

**Comment by daviddossett** [comment]
> I'm happy to do the workbench theme service changes if you look at the css fixes. Currently all colors have default colors for `light`, `dark` and `hc`. That means we would need new defaults for hc-light as well.

That works for me! 👍
