### ISSUE TITLE
'Install Extension' searches by name, but only shows displayName, description, and version in the results

### ISSUE THREAD

**Issue by jwulf** [Microsoft/vscode#1441]
In https://github.com/Microsoft/vscode/issues/140#issuecomment-165473225 @egamma recommends installing @dbaeumer's `vscode-eslint` extension.

While doing this, I notice that I can search for `vscode-eslint` in the Install Extensions dialog. I find the correct extension, but the results pane does not show me the `vscode-eslint` that I searched for (`name` in `package.json`). It shows `displayName`, `description`, `version`, and `publisher`.

I was left wondering if that was the right package, because it said `ESLint`, and I couldn't see `vscode-eslint` anywhere.

In the case where a user searches on `name`, and VS Code finds a match, if the results pane contained feedback that the package listed is the right package, it would be good. 

An idea: Maybe show `name` in the results if the match was on `name`?

I've attached a screen shot - hope that clarifies what I'm talking about. 

Thanks!

![screen shot 2015-12-18 at 7 31 05 pm](https://cloud.githubusercontent.com/assets/406975/11893634/ef16ba04-a5bd-11e5-89f0-1c9bc9192f4e.png)

**Comment by egamma** [comment]
@jwulf - convinced after watching your [video](https://www.youtube.com/watch?v=badlvpaSMn8) :smile:

**Comment by joaomoreno** [comment]
Showing all attributes in the UI will simply make it cluttered. We still let you filter on the underlying ID since that is a nice thing to do.

@egamma, why **important**?

**Comment by egamma** [comment]
@joaomoreno this [video](https://www.youtube.com/watch?v=badlvpaSMn8) illustrates that this results in confusion.

**Comment by joaomoreno** [comment]
Ok, what's your pick?

- Do not show readable extension name, but extension ids in the UI
- Show both readable name and id, for every extension in the UI
- Stop filtering on the extension id

**Comment by jwulf** [comment]
What about option 4: "show the extension id when that is what was searched and matched"




If they didn't search on extension id, no need to show it. 




If they searched on extension id and we found matches, then show it. 




In other words: have the behaviour match the user's intent and expected context. 




Or more simply: show them what they are looking for. 



—

**Comment by joaomoreno** [comment]
I don't really like that solution since it would make labels come in and out of the view as you type and poses the following questions: Where to show it? Do we replace the readable name with it? Do we append to it?

**Comment by jwulf** [comment]
Great questions. 




One possibility:




Show only the names while the user is typing, then when the user stops typing for a (specified delay period), make a decision about what to show. 




That addresses the labels coming in and out of view. 




What about having the Name as a tooltip, and it could only be a tooltip for items where the match was made on name. 




That would be kind of like Google's "Why am I seeing this ad?" pattern. 



—

**Comment by joaomoreno** [comment]
How about a tooltip over every extension's readable name that would display its id? Would that help?

**Comment by jwulf** [comment]
I think so.

**Comment by egamma** [comment]
+1
