### ISSUE TITLE
Titlebar controls are faded

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#144180]
On latest insiders, using my GitHub Sharp theme, notice the three titlebar buttons to the right:

![image](https://user-images.githubusercontent.com/22350/156197776-8e932ecb-1775-496a-b429-d4a61cdd7a1e.png)

This is stable:

![image](https://user-images.githubusercontent.com/22350/156198041-80906af1-ade4-4c36-ac53-ba9f19c14e35.png)

If there are new theme colors to style those, what are their IDs?

**Comment by misolori** [comment]
@sbatten did anything change in the windows titlebar/controls area?
