### ISSUE TITLE
Terminal Console Not Working in Visual Studio Code - Exit Code: 4294901760

### ISSUE THREAD

**Issue by Scottywonderful** [microsoft/vscode#144152]
Hi team,

<details>
<summary>Run down of issue</summary>

I am currently coding a Discord Bot and had not seen this error until about a month ago which was when it showed the first time (unfortunately that's how long I have been trying to research and troubleshoot this issue).
I at first thought it was possibly an issue with my code within my scripts so I reverted all files and the folder to before I got the error and it somehow still shows the error message, additionally I have followed several help articles, google searches and even a list of issues already posted about this type of issue and nothing seems to work or fix the issue.

</details>

As I have been unsuccessful in resolving this issue on my own, I am now requesting your assistance to resolve this.

I have attached an image below of the error message along with other information that I thought you might need.
Please let us know if you require any more information and if so, what you would like me to provide.

Issue Type: **Performance Issue**

This issue when happened when going to "Terminal" and clicking "New Terminal".
It opens the Terminal displaying this message:
```
Windows PowerShell terminated with the following error:
 Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The module was expected to contain an assembly manifest.
```
Which a split second later it closes and shows the pop up window saying:
```The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: 4294901760.```

<details>
<summary>VS Code Information</summary>

Version: 1.64.2 (system setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
No Extensions Installed or Active.

</details>

<details>
<summary>List of file extensions used</summary>

| File Extensions |
|:----:|
| node_modules |
| .gitattributes |
| .gitignore |
| .png |
| .json |
| .js |
| .md |

</details>

<details>
<summary>Error Image</summary>

![image](https://user-images.githubusercontent.com/7965509/156117360-132e797b-a0b9-491c-907d-1433bf5af0af.png)
As you can see in the image it talks about some type of System.Management.Automation failing to contain an assembly manifest which I am unsure of.

</details>

<details>
<summary>Computer/System Info</summary>

| Item | Value |
| --------------- | --------------- |
| OS Name | Microsoft Windows 10 Pro |
| Version | 10.0.19044 Build 19044 |
| Processor | AMD Ryzen 5 2600 Six-Core Processor, 3400Mhz, 6 Core(s), 12 Logical Processor(s) |
| GPU | NVIDIA GeForce RTX 2060 |
| Total Physical Memory | 16.0 GB (6.31 GB Available) |
| Total Virtual Memory | 34.0 GB (17.3 GB Available) |

</details>

I have found and tried to follow all the below articles/issue reports for help plus documentation and googling online for more but nothing seems to have worked thus far;

- https://github.com/microsoft/vscode/issues/114830
- https://github.com/microsoft/vscode/issues/113268
- https://github.com/microsoft/vscode/issues/109927
- https://github.com/microsoft/vscode/issues/109342
- https://github.com/microsoft/vscode/issues/106838
- https://github.com/microsoft/vscode/issues/107371
- https://github.com/microsoft/vscode/issues/113440
- https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423

Please let me know if I need to provide anything and if so, what you would like me to provide.
Thanks for your help in advance, look forward to your support.

**Comment by Scottywonderful** [comment]
Apologies about the 3 edits, It somehow posted before I was ready to post it.
Still requiring assistance.

**Comment by yume-chan** [comment]
Does it work if you launch PowerShell directly? (Run -> powershell.exe)

Does it work in an old version of Visual Studio Code? (You can download them from release note page on https://code.visualstudio.com)

**Comment by Scottywonderful** [comment]
> Does it work if you launch PowerShell directly? (Run -> powershell.exe)
> 
> Does it work in an old version of Visual Studio Code? (You can download them from release note page on https://code.visualstudio.com)

Hi @yume-chan,
Thanks for your reply, I have just attempted to open powershell by itself and is not working, it's in fact immediately closing.
I will see first if maybe a uninstall of powershell, a restart of my computer and then a re-install of powershell will fix the issue.

Will update this issue once I have done the following and have an update.

**Comment by Scottywonderful** [comment]
> > Does it work if you launch PowerShell directly? (Run -> powershell.exe)
> > Does it work in an old version of Visual Studio Code? (You can download them from release note page on https://code.visualstudio.com)
> 
> Hi @yume-chan, Thanks for your reply, I have just attempted to open powershell by itself and is not working, it's in fact immediately closing. I will see first if maybe a uninstall of powershell, a restart of my computer and then a re-install of powershell will fix the issue.
> 
> Will update this issue once I have done the following and have an update.

Hey @yume-chan,

I have initially attempted to reinstall PowerShell, which was unfortunately unsuccessful on the first attempt, though on the second attempt after a restart of the computer it seemed to have worked, though the issue still persisted where the PowerShell Window would show but instantly close on starting up. I attempted to start and open PowerShell multiple different ways and even with admin privileges.

I performed a ```DISM.exe /Online /Cleanup-image /Restorehealth``` command in an admin command prompt window and it seemed to have fixed and resolved multiple issues.
With this result, I performed a ```sfc /scannow``` command in the command prompt which stated there was no issues or violations.
So I went ahead and started PowerShell normally though this unfortunately still did not seem to fix the issue.

I am currently performing a full system deep security scan with my Anti-Virus Software and will possibly soon perform a full wipe of my computer if PowerShell still does not work after all these steps are completed.

In the meantime, **would you suggest anything I should try before doing a full computer wipe and if so, what would you recommend I perform to see if the issues can be resolved?**

Thanks in advance for further help and appreciate your help earlier.

**Comment by Scottywonderful** [comment]
> Maybe you can try PowerShell Core,you can install it from Microsoft Store or PowerShell's GitHub page, it should support your Windows version.
> 
> It installs side-by-side with the old Windows PowerShell, but it's newer and more feature-riched. Code can also use it in the integrated terminal.

Hey mate,

My system is still doing the deep scan but I have installed the PowerShell Core from the Github .MSI file and installed the extension into VS Code and it seems to be working, though I do get a warning message I don't believe this message would be a huge deal at this time.

Thank you for all your help @yume-chan.

The warning message I am getting is:
![image](https://user-images.githubusercontent.com/7965509/156197848-e3f1d049-5bb6-4ac5-8127-7f01fc32802d.png)
![image](https://user-images.githubusercontent.com/7965509/156197914-f539c8f1-6d1d-4d75-b4fd-cd66cd5f7cad.png)

Hope you have a wonderful day!
Peace to you.

**Comment by Scottywonderful** [comment]
**This issue has been resolved thanks to help from @yume-chan**

If anyone else reads this message and they also get the warning message and would like to get rid of it (worked for me):
```Warning: PowerShell detected that you might be using a screen reader and has disabled PSReadLine for compatibility purposes. If you want to re-enable it, run 'Import-Module PSReadLine'.```

I suggest you do the command ```Import-Module PSReadLine``` in the PowerShell window you have the message in and then close that window and go to your "Registry Editor" and change the following key:

```

Windows Registry 
Computer\HKEY_CURRENT_USER\Control Panel\Accessibility\Blind Access\On

```

In the 'On' Registry, Right-Click and edit the value from ```1``` to ```0``` and reboot your computer.

This will stop this message from popping up (It worked for me though be aware it may not work for you).

Thanks for all the support on this issue.
Hope you all have a wonderful day!
