### ISSUE TITLE
Find widget doesn't respect selection column for multi-line selection

### ISSUE THREAD

**Issue by ShafinKhadem** [microsoft/vscode#144184]
Find scope respects column only in single line selection, but not in multi-line selection. It was designed to be like this in e1bb3ad6f3950e9a1a13fb988ead768f91b783ff: https://github.com/microsoft/vscode/blob/e1bb3ad6f3950e9a1a13fb988ead768f91b783ff/src/vs/editor/contrib/find/common/findModel.ts#L159-L162

Steps to reproduce:

1. Have the following text in your editor:
   ```
   abc
   abc
   abc
   abc abc
   abc
   ```
2. Select from 2nd abc to 4th abc
3. Enable find widget, possibly by pressing <kbd>Ctrl</kbd><kbd>f</kbd>
4. Enable find in selection, possibly by pressing <kbd>Alt</kbd><kbd>l</kbd>
5. Enter abc

Notice that it highlights 2nd to 5th abc, instead of 2nd to 4th:

![before](https://user-images.githubusercontent.com/26321479/156194245-b2fa9262-2d22-4547-900f-8ddaca80d68d.gif)

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.13.0-22-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 5300U with Radeon Graphics (8 x 2842)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 1, 1|
|Memory (System)|7.12GB (1.21GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id f9ef0483-9e99-46a3-9f8c-1e6a71b29e0e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614
py55gd98:30411514
vscexrecpromp3t1:30407762

```

</details>

**Comment by rebornix** [comment]
there is a long history of why the find scope is extended to first line start and last line end, making it risky to change the behavior.

**Comment by amunger** [comment]
duplicate https://github.com/microsoft/vscode/issues/80008
