### ISSUE TITLE
VS Code comments inline JavaScript code with HTML comments

### ISSUE THREAD

**Issue by aidantomcy** [microsoft/vscode#144174]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: Windows 10 Version 21H2  (OS Build 19044.1526)

Steps to Reproduce:

1.  When I try to comment a line in an inline script in HTML
2. VS Code comments the line with an HTML comment.

For example, this was the code before commenting:
![2022-03-01 19_09_52-deleteme html - saintsforus - Visual Studio Code](https://user-images.githubusercontent.com/80614206/156179737-56997157-fa74-44a2-adfa-c541e79d54b2.png)
and here's what it looked like after commenting:
![2022-03-01 19_10_29-● deleteme html - saintsforus - Visual Studio Code](https://user-images.githubusercontent.com/80614206/156179934-69025c63-b1f6-4b14-89a0-019ffd62c53e.png)

**Comment by aeschli** [comment]
I cannot reproduce with the buillt-in language HTML language support.

What is the language mode in the status bar?

**Comment by aidantomcy** [comment]
The language mode in the status bar is HTML.

**Comment by aeschli** [comment]
Can you provide the small code sample that shows this. Where do you place the cursor, what command do you call.
What does the `Developer: Inspect Editor Tokens and Scopes` hover show at the cursor location?
![Peek 2022-03-02 12-37](https://user-images.githubusercontent.com/6461412/156354758-a5bf224e-538f-4456-9245-00d5db16cc4c.gif)

**Comment by aidantomcy** [comment]
Heres the code sample:
![video](https://user-images.githubusercontent.com/80614206/156703986-f6f8d7f0-b43b-4118-8f83-fb4b61ae9e0a.gif)

**Comment by aeschli** [comment]
Does this reproduce with extensions dissabled?

**Comment by aidantomcy** [comment]
Yes, but I only disabled extensions specific to HTML.

**Comment by aeschli** [comment]
Just use the command `Developer: Reload with extension disabled`.
I think you are using an extension for `jinja` which causes that. A `jinja` scope can also be seen in the scopes hover.

**Comment by aidantomcy** [comment]
Yes, some of my extensions for Jinja were causing this to happen.
Thank you for your help!
