### ISSUE TITLE
Unhelpful error message when uninstalling extension pack

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#14413]
testing #14291

Uninstall extension pack another pack depends on and see the following little helpful error message

<img width="820" alt="screen shot 2016-10-25 at 13 24 17" src="https://cloud.githubusercontent.com/assets/1794099/19684258/92f2a97e-9ab6-11e6-87bd-c9650a12b8a3.png">

Instead, it should show me what pack depend on the one to be uninstalled and offer me to also uninstall those.

**Comment by sandy081** [comment]
Improved the message to show maximum two extensions depending on the to be uninstalled extension. 

Created #14544 for viewing and uninstalling dependent extensions
