### ISSUE TITLE
Scrollbar indicators get out of step for very large line numbers

### ISSUE THREAD

**Issue by joachim-n** [microsoft/vscode#144166]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.64.2
- OS Version: 10.15.7

Steps to Reproduce:

1. Open a large file with merge conflicts
2. At lines > 10k, the merge conflict indicator in the scroll bar is not correctly positioned relative to the viewport indicator. Eg in the screeshot, the conflict is at the top, but the scrollbar shows it as being at the bottom.

<img width="1572" alt="Screenshot 2022-03-01 at 11 23 49" src="https://user-images.githubusercontent.com/105262/156160802-978cd69b-ce87-441a-8892-ea0ce1782540.png">

**Comment by alexdima** [comment]
Let's track in #82087. This is because we artificially enforce a min height of 20px on the scrollbar slider. See also https://github.com/microsoft/vscode/issues/82087#issuecomment-768601184 for a visual comparison about how the artificial min height affects the geometry of the scrollbar.
