### ISSUE TITLE
Terminal: Clear command sometimes does not work

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#144109]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65-insider
- OS Version: Windows 11

Steps to Reproduce:

I don't have good repro steps yet, but filing this to keep track/in case anyone else does (below I have mapped the clear command to ctrl+k):
![Recording 2022-02-28 at 10 34 12](https://user-images.githubusercontent.com/30305945/156038813-1ade836b-c40d-42f5-9f6f-4631b7cec5ee.gif)

**Comment by meganrogge** [comment]
@Tyriar have you seen this on windows?

**Comment by joyceerhl** [comment]
OK, I have a repro
1. Run any command, e.g. `pwd`
2. Run `clear`
3. Run Ctrl+K / Terminal: Clear
4. :bug: command decorations not cleared from terminal

**Comment by Tyriar** [comment]
I can repro on Winodws when running `clear` (step 2), this is what conpty does:

```
xterm.js: parsing data "[?25l[3J[H[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[H[?25h"
```

Decorations are all cleared after running the `Terminal: Clear` command though.

**Comment by meganrogge** [comment]
reopened this issue to address that case

/duplicate https://github.com/microsoft/vscode/issues/143784
