### ISSUE TITLE
Invalid Value for Token Color - Regex

### ISSUE THREAD

**Issue by csestito** [microsoft/vscode#144194]
Hi, we are seeing this error while using vscode monaco editor. 
![Screen Shot 2022-03-01 at 9 50 29 AM](https://user-images.githubusercontent.com/29921380/156225796-c4ebf412-fc6e-4092-8cda-bd3f46a76a70.png)

Our css-minifier replaces `#aaaaaa` with `#aaa` and that fails the regex below. I'm unsure what this Regex is looking to match on.   

https://github.com/microsoft/vscode/blob/973684056e67153952f495fce93bf50d0ec0b892/src/vs/editor/common/languages/supports/tokenization.ts#L153

In my head, it makes sense to see if the value is a 6 digit hex code or a [3 digit hex code](https://www.w3schools.com/css/css_colors_hex.asp#:~:text=3%20Digit%20HEX%20Value&text=The%203%2Ddigit%20hex%20code,some%206%2Ddigit%20hex%20codes.&text=Where%20r%2C%20g%2C%20and%20b,the%20same%20for%20each%20components.) 
```js
const colorRegExp = /^#?([0-9A-Fa-f]{6})?$|^#?([0-9A-Fa-f]{3})?$/
```
Here it would match on a 3 digit or 6 digit hex code. 

Happy to submit a pull request, but wanted to see if I was just missing something in the way this is matching colors.

**Comment by aeschli** [comment]
The TextMate theme syntax currently only supports 6 and 8 digit hex codes. We don't want to change that as this will have ripples into `vscode-textmate` and other places.

Who defined that theme with `IStandaloneThemeService.defineTheme`? 
I can add validation there if it helps to detect this earlier.
