### ISSUE TITLE
Support more than sortText for suggestion ordering (such as matchPriority from Roslyn)

### ISSUE THREAD

**Issue by kjackson1998** [microsoft/vscode#144149]
nuint is prioritized over null in code completion suggestions. vscode needs support (I think) for dealing with match priority for completion items more complex than just sortText, such as also a match priority like Roslyn can provide.

My full stack understanding here: https://github.com/OmniSharp/omnisharp-vscode/issues/5084

**Comment by kjackson1998** [comment]
vscode is more than Roslyn, I understand, but vscode completion could be better for C# if it supported at least as much as Roslyn supports here, I think: https://github.com/dotnet/roslyn/blob/main/src/Features/Core/Portable/Completion/CompletionList.cs

**Comment by jrieken** [comment]
> nuint is prioritized over null in code completion suggestions.

Can you provide more context and sample around this? Extensions can define the initial sort order from then it is user choice depending on the prefix they select

**Comment by kjackson1998** [comment]
Sorry for the confusion. You are correct if the C# VSCode extension just provided a different sort order text you can get any sort order you want. I suppose I am claiming weakly that if you look at the roslyn completion contract, sorting on more than just sortText for each item is useful. For example, items can also have a matchPriority that takes priority over sortText: https://github.com/dotnet/roslyn/blob/main/src/Features/Core/Portable/Completion/CompletionItemRules.cs

This is how roslyn pushes nuint underneath null in the order. The C# extension would need to re-interpret matchPriority+sortText into just sortText to solve the nuint/null problem. "Not vscode's problem" really I suppose but in thinking about how I'd implement that in the extension I'd have to prefix each sortText with a matchPrefix integer (-maxint to +maxint).

Or vscode could expand the completion contract.

I suppose I'm saying the roslyn completion contract seems fuller featured than vscode, and would be nice for vscode to incorporate some of that.

In my ideal naive world, vscode and roslyn completion experts would work together to have similar completion contracts from their respective learnings.

**Comment by jrieken** [comment]
I do understand where you are coming from but any integrator of language services can ask for this - we cannot make our API the union of all API concepts, it's more a common denominator approach. Generally, these discussions shouldn't at the level of API symbols but about features and things that can not be done. It's expected that some things hard than other to implements (despite us having taken much inspiration from roslyn)

On the matter of `matchPriority`. From reading its doc "True if the related completion item should be initially selected." it sounds very much like our [preselect](https://github.com/microsoft/vscode/blob/33aeada8904e540d1fa39ffe676704a46e1f0e0c/src/vscode-dts/vscode.d.ts#L4213)-property. Is that true or am I mistaken?
