### ISSUE TITLE
Issue with debugger on docker containers

### ISSUE THREAD

**Issue by mahajanankur** [microsoft/vscode#144145]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: **1.64.2 (Universal)**
- OS Version: **Darwin arm64 21.2.0**

The debugger is not attaching with docker container for remote debugging. I followed the steps mentioned on [the official link](https://code.visualstudio.com/docs/remote/attach-container), it was working with the old OS release **OS: Darwin arm64 20.6.0**

Steps to Reproduce:

1. Create `NodeJS` based code template.
2. Create `docker-compose.yml` and add debug script in `package.json` `"debug": "node --inspect-brk=0.0.0.0:2700 src/index.js"`
3. Create `launch.json` and `tasks.json` file in `.vscode` directory with specified configuration as mentioned below. 

**launch.json**

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Remote",
            "address": "localhost",
            "port": 2700,
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/home/codebase/app1",
            "preLaunchTask": "container-debugging",
            "restart": true
        }
    ]
 } 
```
tasks.json

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "container-debugging",
            "type": "shell",
            "command": "sh",
            "args": [
                "-c",
                "docker-compose -f docker-compose-mac-debug.yml --compatibility up -d && docker restart app"
            ],
            "presentation": {
                "reveal": "always",
                "panel": "shared"
            }
        }
    ]
 }
```
I tried checking the logs as well but no luck.

**Comment by saravjotsingh** [comment]
I am facing the similar issue. Debugger not attaching to the docker and it's keep on loading.
<img width="303" alt="debugger" src="https://user-images.githubusercontent.com/26213231/156121706-786b531c-0b45-4e56-bd0a-4885b6c5a038.png">

**Comment by connor4312** [comment]
Also, verify that you can actually hit that address from your host machine. E.g. `curl -v localhost:2700` should produce something.

**Comment by mahajanankur** [comment]
I tested on `OS Version: Darwin arm64 21.3.0` as well but same issue persists there.

**Comment by weinand** [comment]
@alexr00 are you aware of a task issue with the "args" property in recent versions of macOS (maybe Arm specific)?

**Comment by alexr00** [comment]
I was not aware! I will see if I can track down a machine with `OS Version: Darwin arm64 21.2.0` to test with. 

@Tyriar FYI, since this may be a terminal issue.

**Comment by alexr00** [comment]
Found someone to test on OS Version: Darwin arm64 21.3.0. Output was as expected:

![image](https://user-images.githubusercontent.com/38270282/156338488-0be97601-0818-4d42-b96a-c69f99a36ebd.png)

@mahajanankur can you describe and provide some screen shots of how it didn't work for you?

**Comment by saravjotsingh** [comment]
I am getting unexpected behavior, sometimes it works but most of the time it keeps on loading. I tried with the same **tasks.json** file but I am not getting any output in the debugger console.
<img width="851" alt="debuggervs" src="https://user-images.githubusercontent.com/26213231/156345534-f9eedf23-ba01-4986-abd7-9bc67d3bb419.png">

**Comment by connor4312** [comment]
The "Hello vs debugger" will not be printed to the Debug Console, as it's a task, not a debug session. Its output can be found in a Terminal tab.

**Comment by mahajanankur** [comment]
`Its output can be found in a Terminal tab.` @connor4312 I checked in the terminal as well no traces are there.

**Comment by mahajanankur** [comment]
@connor4312 we have rectified the issue. It was a permission issue with `rg` once we give a specified access it started working.

`sudo chmod 777 rg`
