### ISSUE TITLE
Task executions "cwd" is lost when customising a task using the cog icon

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#144165]
Take the [Task Provider sample](https://github.com/microsoft/vscode-extension-samples/tree/main/task-provider-sample) and modify it produces tasks that run `ls` in `/tmp`:

Change:

```ts
		return new vscode.Task(definition, vscode.TaskScope.Workspace, `${flavor} ${flags.join(' ')}`,
			CustomBuildTaskProvider.CustomBuildScriptType, new vscode.CustomExecution(async (): Promise<vscode.Pseudoterminal> => {
				// When the task is executed, this callback will run. Here, we setup for running the task.
				return new CustomBuildTaskTerminal(this.workspaceRoot, flavor, flags, () => this.sharedState, (state: string) => this.sharedState = state);
			}));
```

to:

```ts
		return new vscode.Task(
			definition,
			vscode.TaskScope.Workspace,
			`${flavor} ${flags.join(' ')}`,
			CustomBuildTaskProvider.CustomBuildScriptType,
			new vscode.ProcessExecution( // run "ls" in "tmp"
				'ls',
				[],
				{ cwd: '/tmp' },
			),
		);
```

Running the task with **Tasks: Run Task** -> `custombuildscript` correctly runs in that directory. However if you click the cog icon, it adds the following to `tasks.json`:

```js
		{
			"type": "custombuildscript",
			"flavor": "32",
			"flags": [],
			"problemMatcher": [],
			"label": "custombuildscript: 32 "
		}
```

I was expecting it to also include:

```js
			"options": {
				"cwd": "/tmp"
			}
```

The tasks being produced might be project-specific in a workspace that contains multiple projects and need to run in a specific project. Trying to customise them shouldn't lose which folder they are associated with.

**Comment by alexr00** [comment]
@DanTup because you included the `cwd` in the `ProcessExecution` constructor the task will run with that cwd anyway. The folder is hard coded in the task provided in your example and will never be lost. 

I ran your example twice, once before customizing the task, and once after and the output was the same (I don't have a `/tmp`, but it illustrates that the cwd is correct.):

```
> Executing task: \tmp\ls  <

The terminal process failed to launch: Starting directory (cwd) "\tmp" does not exist.

Terminal will be reused by tasks, press any key to close it.
```

**Comment by DanTup** [comment]
@alexr00 

> The folder is hard coded in the task provided in your example and will never be lost.

This was just a trivial sample to show that it's not being recoded in `tasks.json`. In my real task provider, it's not hard-coded, it's based on the actual folders in the project (eg. we'll produce two of these tasks, one for each project folder). If the user wants to customise one of them, they would expect the `cwd` to be added to `launch.json`?

**Comment by DanTup** [comment]
I'm a little confused about how this is intended to work. If I update the sample to this:

```ts
	public resolveTask(_task: vscode.Task): vscode.Task | undefined {
		const flavor: string = _task.definition.flavor;
		if (flavor) {
			const definition: CustomBuildTaskDefinition = <any>_task.definition;
			return this.getTask(definition.flavor, definition.flags ? definition.flags : [], definition, (_task.execution as vscode.ProcessExecution).options?.cwd);
		}
		return undefined;
	}

	private getTasks(): vscode.Task[] {
		if (this.tasks !== undefined) {
			return this.tasks;
		}
		// In our fictional build, we have two build flavors
		const flavors: string[] = ['32', '64'];
		// Each flavor can have some options.
		const flags: string[][] = [['watch', 'incremental'], ['incremental'], []];

		this.tasks = [];
		flavors.forEach(flavor => {
			flags.forEach(flagGroup => {
				this.tasks!.push(this.getTask(flavor, flagGroup, undefined, "/tmp"));
				this.tasks!.push(this.getTask(flavor, flagGroup, undefined, "/Users"));
			});
		});
		return this.tasks;
	}

	private getTask(flavor: string, flags: string[], definition: CustomBuildTaskDefinition | undefined, cwd: string | undefined): vscode.Task {
		if (definition === undefined) {
			definition = {
				type: CustomBuildTaskProvider.CustomBuildScriptType,
				flavor,
				flags,
			};
		}
		return new vscode.Task(
			definition,
			vscode.TaskScope.Workspace,
			`${flavor} ${flags.join(' ')} ${cwd}`,
			CustomBuildTaskProvider.CustomBuildScriptType,
			new vscode.ProcessExecution(
				'ls',
				[],
				{ cwd },
			),
		);
	}
```

And then run **Tasks: Run Task** -> `custombuildscript` I see this:

![Screenshot 2022-03-01 at 13 41 12](https://user-images.githubusercontent.com/1078012/156179572-5c5083af-dccb-4a8e-b32f-dad283aeab35.png)

The only place constructing tasks that puts the cwd in the description is _also_ providing the `ProcessExecution` that has the actual `cwd`. So when clicking the cogs next to the items marked `/tmp` and `/Users`, I expected it to add tasks to `tasks.json` that have that `cwd` set. However, I see that when I run the task (without adding a `cwd` in `tasks.json`) it still uses the correct `cwd`. It's not clear to me where this is coming from. I thought maybe it was matched up by `label`, so I changed the `label` to have `/Users` instead of `/tmp`, however it still runs the command in `/tmp`. and more confusingly it's updated the tasks in the **Run Task** list:

![Screenshot 2022-03-01 at 13 45 02](https://user-images.githubusercontent.com/1078012/156180319-51475300-a512-44a6-849d-9e2079dc16cd.png)

So the task from task.json has overridden one of the tasks in this list, but it's not at all clear how it's matching them up (now I have two that say `/Users` but the task provider is producing them for `/tmp` and `/Users`).

**Comment by alexr00** [comment]
Extension provided tasks are identified by their definition. In this case:

https://github.com/Microsoft/vscode-extension-samples/blob/2bc23042f186e4ff5899b89f89768de099610e66/task-provider-sample/package.json#L41-L56

So, tasks with the same definition properties, in this case `type`, `flavor`, and `flags` will be treated as the same, because to the task system they have the same identifier.  The changes in https://github.com/microsoft/vscode/issues/144165#issuecomment-1055458634 give the same task two different labels, which is pretty confusing.

If you want users to be able to specify a `cwd` that will not have this confusion, you should add it to the task definition properties. Or, your task provider just knows the right thing to do already without users adding a `cwd` and you set it yourself in the task provider without any input needed from the user.

**Comment by DanTup** [comment]
@alexr00 

> If you want users to be able to specify a cwd that will not have this confusion, you should add it to the task definition properties.

Ah, got it - I didn't notice it was using those fields when matching the tasks up. This sounds like a plan - I'll just add a `cwd` to the definition and copy it into the process options in the provider. Thanks for the help, and sorry for the bother!
