### ISSUE TITLE
one placeholder marker is not disposed of when shell integration / decorations are disabled

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#144137]
To repro:
- create two split terminals w shell integration enabled
- run some commands
- disable shell integration or command decorations
- 🐛 all decorations except for one placeholder are gone

**Comment by joyceerhl** [comment]
I don't see any placeholder markers after disabling shell integration, but when I reenable shell integration, my decorations don't come back--is that expected?

**Comment by meganrogge** [comment]
we have an issue for that, so yep that's expected

**Comment by Tyriar** [comment]
I fixed that one yesterday, should be good in today's build.
