### ISSUE TITLE
MarkdownString#appendText shows escaped whitespace

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#144190]
* have an MD string as below
* :bug: the hover renders `&nbsp;` for the space

```js
const markdownString = new vscode.MarkdownString();
markdownString.appendText("Hello: https://github.com/microsoft/vscode/issues/142494")
return new vscode.Hover(markdownString);
```

**Comment by jrieken** [comment]
<img width="505" alt="Screen Shot 2022-03-01 at 18 30 16" src="https://user-images.githubusercontent.com/1794099/156218695-d81a24c0-2493-4381-ba5d-e48e72cf30a1.png">

**Comment by jrieken** [comment]
not sure when/how this happened...

**Comment by mjbvz** [comment]
I can't reproduce this with a simple hover provider. Can you please share a complete set os steps to trigger this?

<img width="826" alt="Screen Shot 2022-03-02 at 3 06 30 PM" src="https://user-images.githubusercontent.com/12821956/156464780-d7f27ee5-a45e-405e-8c6d-71faa6097202.png">

**Comment by jrieken** [comment]
Turns out that was me with a bad commit that has been reverted in the meantime
