### ISSUE TITLE
option+delete in terminal behaves different from editor

### ISSUE THREAD

**Issue by spalger** [microsoft/vscode#144187]
Issue Type: <b>Bug</b>

If you have a string of text in the editor with / separators, option+delete (at least on mac) deletes each segment and separator one at a time. In the terminal it deletes the entire path and I think it should be the same in both places.

VS Code version: Code 1.64.2 (Universal) (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No
Remote OS version: Linux x64 5.11.0-1029-gcp

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 6, 5|
|Memory (System)|32.00GB (1.00GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote+kibana@backport-126309.spalger.kbndev.co/home/kibana/dev/kibana --crash-reporter-id dafd89b2-5e5f-4723-a4fe-2e5cb4ecf3ee|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev.spalger.kbndev.co|
|OS|Linux x64 5.11.0-1029-gcp|
|CPUs|AMD EPYC 7B12 (8 x 2249)|
|Memory (System)|31.35GB (27.25GB free)|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.1
codespaces|Git|1.5.4
gitkraken-authentication|git|1.0.3
vscode-json5|mrm|1.0.0
remote-ssh|ms-|0.74.0
remote-ssh-edit|ms-|0.74.0
atom-keybindings|ms-|3.0.9
material-icon-theme|PKi|4.13.0
mdx|sil|0.1.0
vscode-nginx|wil|0.7.2
material-theme|zhu|3.13.20
vscode-css-formatter|aes|1.0.2
vscode-zipfs|arc|2.3.0
asciidoctor-vscode|asc|2.9.5
vscode-eslint|dba|2.2.2
bazel-code|Dev|0.1.9
gitlens|eam|12.0.0
permute-lines|ear|1.1.0
EditorConfig|Edi|0.16.4
gitkraken-authentication|git|1.0.3
terraform|has|2.20.0
asciidoctor-vscode|joa|2.8.0
vscode-styled-components|jpo|1.7.0
vscode-language-babel|mgm|0.0.36
ansi-color-code|Seb|0.1.1
vscode-stylelint|sty|1.2.2
shellcheck|tim|0.18.9
vscode-sort-package-json|uni|1.2.2
expand-selection-to-scope|vit|0.2.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.4.0
file-size|zh9|1.0.0
vscode-open-in-github|ziy|1.3.6

(13 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30442553
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc008:30440022
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343
vsnot107:30443614

```

</details>

**Comment by spalger** [comment]
I tried setting `"terminal.integrated.wordSeparators": " ()[]{}',\"`─‘’/"` but it doesn't seem to impact the delete-by-word feature

**Comment by spalger** [comment]
in iTerm I enable this feature by binding `option+delete` to "Send Hex Code: 0x1B 0x08"

**Comment by spalger** [comment]
I see the following in my keybindings but don't see any indicate of what sequence is sent

```
{
  "key": "alt+delete",
  "command": "workbench.action.terminal.sendSequence",
  "when": "terminalFocus"
}
```

**Comment by spalger** [comment]
Looks like setting the following allows this to work how I would expect, but if someone could point me in the direction I would love to submit a PR to get this working even when the workbench is processing my keystrokes.

```
"terminal.integrated.sendKeybindingsToShell": true
```

**Comment by meganrogge** [comment]
As described here `terminal.integrated.sendKeybindingsToShell`, if you want to fine tune what gets sent to the shell vs workbench, you can do so via `terminal.integrated.commandsToSkipShell`

**Comment by spalger** [comment]
@meganrogge do you have a suggestion for what I should add to `terminal.integrated.commandsToSkipShell`? `workbench.action.terminal.sendSequence`? This is the only relevant "command" I can find and it doesn't seem to do anything.

**Comment by erhhung** [comment]
With `terminal.integrated.sendKeybindingsToShell` set to `false` and adding a single item `-workbench.action.terminal.sendSequence` (note the leading minus sign) to the `terminal.integrated.commandsToSkipShell` list, I'm able to get the delete-by-word behavior in the terminal that I want without blocking all keybindings, like Ctrl-Tab which I use everywhere.

**Comment by spalger** [comment]
Fantastic, that did the trick @erhhung. Thank you!!
