### ISSUE TITLE
Opening a walkthrough to the side should only do that if there is something open

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#144127]
I know this is the default behavior for editors, etc when you say to open to the side -- it will create a blank area on the left and open it to the right. And while I don't love that behavior generally, for walkthroughs I find it worse (mainly because the stacked walkthrough layout is not as nice as when its side by side).

It would be great if the walkthrough command could alter its behavior and only honor the "to the side" behavior is there was a tab or something open.

/cc @JacksonKearl

**Comment by JacksonKearl** [comment]
The `toSide:` modifier prefix is supposed to always open to the side, so that the walkthrough remains open for reference. If you don't want things to open to the side then I'd say just don't include that prefix?

**Comment by eamodio** [comment]
I want to open it to the side IF it would affect the context of the user, but if nothing else is open, then there really is nothing to open it to the side of -- and creating a blank space IMO feels like a bug. And extensions can't tell if there are other tabs opened currently, so there isn't a way for me to control this behavior myself.

**Comment by JacksonKearl** [comment]
It opens to the side of itself, no? I don't see what the "blank space" here is, it should be the content opened.

**Comment by eamodio** [comment]
Here's what I mean:

![open-to-side](https://user-images.githubusercontent.com/641685/156234200-4c5c4e05-623f-4e83-8c79-ab1e159766f2.gif)

That GitLens command opens the walkthrough to the side.

**Comment by JacksonKearl** [comment]
What command are you running to do that?

**Comment by eamodio** [comment]
I'm using the `workbench.action.openWalkthrough` command

**Comment by JacksonKearl** [comment]
Oh, I was thinking of individual steps that use a `toSide` command.
