### ISSUE TITLE
Problems panels shows line number and column info inconsistently

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#144198]
![CleanShot 2022-03-01 at 11 02 00@2x](https://user-images.githubusercontent.com/35271042/156232390-7ed4f9b6-ab49-4d70-a90a-a10893bf3865.png)

It's not clear what the `[XX, XX]` numbers mean in the problems view and after inspecting it appears that these are the line numbers and columns. We should update the string to keep it consistent with the way the status bar highlights this as `Ln XX, Col XX`.

**Comment by sandy081** [comment]
I think this is the least useful information in the problems view. One will be taken into that position when clicking on it. I am in favour of removing this info rather than make it more informative.
