### ISSUE TITLE
MarkdownString cannot render webp image

### ISSUE THREAD

**Issue by Sean10** [microsoft/vscode#144188]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.0
- OS Version: mac 10.15.7

Steps to Reproduce:

1. preview this file
```  ts
const md = new vscode.MarkdownString('![](./leveldb2.webp)')
```

2. not work.

**Comment by mjbvz** [comment]
Do they render in other places in vscode, such as the markdown preview?

**Comment by Sean10** [comment]
> Do they render in other places in vscode, such as the markdown preview?

In [yzhang\-gh/vscode\-markdown: Markdown All in One](https://github.com/yzhang-gh/vscode-markdown), it could work. `webp` is rendered correctly. 

 Maybe my usage is wrong. I will try it.
