### ISSUE TITLE
Allow `workbench.action.terminal.focus<Next|Previous>` to focus back to the selected terminal 

### ISSUE THREAD

**Issue by denik1981** [microsoft/vscode#144128]
Currently, I can switch through the open terminals but the focus remains in the terminal group control instead of returning back to the selected terminal. It will be nice if the command can complete its task returning the focus back to the terminal allowing me to start typing on it. 

**Steps to reproduce**
- Open at least two terminal instances.
- Switch to Next/Previous using the keyboard shortcut that calls to `workbench.action.terminal.focus<Next|Previous>`
- Try to start typing and you will notice the focus remains in the terminal group control instead of the selected terminal itself.

**Comment by meganrogge** [comment]
A gif with screen cast mode enabled would be helpful

**Comment by denik1981** [comment]
@meganrogge I cannot screencast the lack of focus as is invisible to the screen. 
I think the steps to reproduce are more than enough.

**Comment by meganrogge** [comment]
Works for me with workbench.action.terminal.focusNext and workbench.action.terminal.focusPrevious
