### ISSUE TITLE
Intellisense Works With White Space

### ISSUE THREAD

**Issue by name2name2** [Microsoft/vscode#14418]
- VSCode Version: 1.6.1
- OS Version: win10

Now 'Tab' and 'Enter' can trigger the intellisense word,  I hope it can be triggered with 'White Space' too.

![image](https://cloud.githubusercontent.com/assets/10517310/19685907/5a9709f4-9af1-11e6-80cf-a3aa9dcb7d06.png)

**Comment by jrieken** [comment]
You can do that using a custom keybindings configuration

* press `F1`, type `Open Keyboard Shortcuts` and paste the following

```
	{
		"key": "space",
		"command": "acceptSelectedSuggestion",
		"when": "editorTextFocus && suggestWidgetVisible"
	}
```
