### ISSUE TITLE
Too easy to delete a notebook cell

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#144113]
Deleting a cell is just an action in the cell toolbar. Clicking on it by mistake is very easy.
All the other potential data loss we always prompt in VS Code.

So I suggest that we either:
1) Prompt user if they are sure they want to delete the cell
2) Do not have this action in the toolbar (if telemetry shows it is not as popular as the other ones). Since it is already present in the `...` actions

p.s no need to have the action duplicated. If you decide to leave it in the primary toolbar, I suggest to remove from the `...` actions

fyi @minsa110 @nneva

![Screenshot 2022-02-28 at 18 06 13](https://user-images.githubusercontent.com/1926584/156026632-178f3011-55de-4b1e-9299-de59b2bc2f5f.png)

**Comment by rebornix** [comment]
@isidorn the delete button is rendered as the end of the toolbar to allow users to delete cells in sequence easily enough. Moving it elsewhere or moving it into `...` would make deleting two or more cells in sequence in the notebook through mouse painfully uneasy.

> Prompt user if they are sure they want to delete the cell

We can experiment of showing prompt the first time when users click on that but I doubt if we want to do it all the time.

**Comment by roblourens** [comment]
I haven't heard this feedback from anyone else, so I'd like to clean this up
