### ISSUE TITLE
[language bug] some scss properties aren't highlighted correctly

### ISSUE THREAD

**Issue by whaaaley** [microsoft/vscode#144101]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version:
- OS Version:

Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

This is not an issue with the theme this is an issue with the language mode itself. There is no theme scope available for SCSS to fix this inconsistency without affecting other highlighting.

1. Open an scss file that has a class name with the `font` property used.
2. Swap between scss and css highlighting in the bottom right

The SCSS looks like: 
![image](https://user-images.githubusercontent.com/7419947/156021197-4eea4a46-4b2e-44b2-a35f-30783fa6065c.png)

The CSS looks like: 
![image](https://user-images.githubusercontent.com/7419947/156021268-b1690b74-418d-41ba-b4ea-6ebd20c254cf.png)

**Comment by alexr00** [comment]
Moved to https://github.com/atom/language-sass/issues/290, which is where we get our scss syntax highlighting grammar from.
