### ISSUE TITLE
Set default level for outline

### ISSUE THREAD

**Issue by komorebi-0409** [microsoft/vscode#144156]
Issue Type: <b>Feature Request</b>

I hope I can set the default expansion level of the outline instead of expanding all symbols, which is very useful in a big file.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"outline"
