### ISSUE TITLE
TSDoc in optional parameter

### ISSUE THREAD

**Issue by tpl-eugenerebong** [microsoft/vscode#144158]
Issue Type: <b>Bug</b>

```
interface ScheduleProps {
  teacherId?: string;
}

const SchedulePage: React.FC<ScheduleProps> = ({
  teacherId,
}: ScheduleProps) => {
```

when opening the tsdoc via intellisense it's not showing teacherId as optional like "teacherId?: string"

VS Code version: Code 1.61.2 (Universal) (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 6, 7|
|Memory (System)|8.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id 9353c7f3-1bd8-48c2-a817-fa25c4a9a145|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.19.9
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
gitlens|eam|11.6.1
prettier-vscode|esb|9.3.0
vscode-firefox-debug|fir|2.9.6
vscode-pull-request-github|Git|0.32.0
todo-tree|Gru|0.0.215
git-graph|mhu|1.30.0
mongodb-vscode|mon|0.8.0
vscode-docker|ms-|1.20.0
remote-containers|ms-|0.202.5
vscode-typescript-next|ms-|4.7.20220228
vsliveshare|ms-|1.0.5418
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.13.0
vscode-git-flow|Psy|0.5.1
vs-code-prettier-eslint|rve|3.1.0
git-merger|sha|0.4.1
gitblame|wad|8.1.0
cors-browser|Wsc|1.0.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
pythonvspyt640:30436486
vsbas813:30436447
vscscmwlcmt:30438805
helix:30438806

```

</details>

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/156143521-8601fb33-3dde-4067-876a-2a2b9a121302.png)

I can't reproduce. Do you have `"strictNullChecks": true` or `"strict": true` in your tsconfig.json?

**Comment by mjbvz** [comment]
Yes @yume-chan is correct here. `| undefined` is only shown when strict null checks are enabled
