### ISSUE TITLE
Large output shows no scrollbar and feel broken

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#144111]
1. Open notebook that generates a large output
2. Run that notebook

Notice that the output can not be scrolled and the output just gets overwritten 🐛 

Repro open this folder, run all cells `Dinosaurus_Island_Character_level_language_model` file, notice output of cell is large and broken.
```
parameters, last_name = model(data.split("\n"), ix_to_char, char_to_ix, 22001, verbose = True)

assert last_name == 'Trodonosaurus\n', "Wrong expected output"
print("\033[92mAll tests passed!")
```
[Assignment_2 (1).zip](https://github.com/microsoft/vscode-jupyter/files/8155175/Assignment_2.1.zip)

fyi @minsa110 @nneva

**Comment by rebornix** [comment]
We have been discussing this for long time. The challenge here is how do we ensure a reasonable experience when we have nested scrollable element.

**Comment by greazer** [comment]
See https://github.com/microsoft/vscode-jupyter/discussions/9863 for the latest version of this complaint
