### ISSUE TITLE
Add `when` option on `package.json` for `contributes.terminal.profiles`

### ISSUE THREAD

**Issue by SeaDve** [microsoft/vscode#144135]
Basically something similar to the `when` options on `menus.commandPalette`. Currently, there is no possible way I know of to disable a terminal provider on certain conditions.

**Comment by meganrogge** [comment]
Can you pls provide your use case?

**Comment by SeaDve** [comment]
In a Flatpak application development, it is possible to open a terminal within the build environment. However, it is necessary to setup the build environment first for the terminal to be valid/launchable. Then `when` option is useful to hide the terminal provider form the `+` dropdown

**Comment by meganrogge** [comment]
Inside `provideTerminalProfile` throw if the build environment is not ready with your own error message or setup the build environment at that time if possible.
