### ISSUE TITLE
Context menu too cluttered for VS Code

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#144112]
Can we try to declutter the context menu so it does not feel like it is from Visual Studio IDe.
Can we get some telemetry data on the actions to see which ones the users do not click on.

fyi @minsa110 @nneva

![Screenshot 2022-02-28 at 18 04 20](https://user-images.githubusercontent.com/1926584/156026149-60e5d6f4-b4e9-41d9-87cc-1c2ed1d6a9ed.png)

**Comment by rebornix** [comment]
This is definitely not good when we have three layers in the context menu.

**Comment by roblourens** [comment]
Which ones do you think we should remove? I don't think it's an issue. Other users are asking for more actions in the context menu.

**Comment by isidorn** [comment]
@roblourens can we look at telemetry data and see what commands are not popular?

Of course users will always ask for more actions... We have to resist this urge of adding everything :)

**Comment by roblourens** [comment]
These are mostly commands which are not exposed anywhere else besides the context menu (and command palette), many don't have keybindings. I think this is the right place to put them for discovery.

**Comment by isidorn** [comment]
If you feel like that is the best way to make the users discover these actions feel free to close this issue as designed...
I do not really know if all the actions here are necessary, my point is that we should just review them. For example: isn't it possible to collapse cell input / output without using the context menu, isn't there a UI gesture for this.

**Comment by roblourens** [comment]
Yeah, actually I'm thinking now that we have tried to make collapsing more accessible with the blue buttons and there are 3 other ways to do it, I will remove those.

Also, now that the toolbar is sticky, I can remove the ones that show up in the toolbar by default (run by line, split, execute above/below)

**Comment by roblourens** [comment]
Yeah, actually I'm thinking now that we have tried to make collapsing more accessible with the blue buttons and there are 3 other ways to do it, I will remove those.

I will remove "delete cell", it is actually in its own menu. I can't remove the others that also show up in the cell toolbar - they will not show up when you click the `...` overflow button in that menu, only in the editor context menu which is just showing all the actions in the cell toolbar menu. I think the others are ok.

**Comment by isidorn** [comment]
Great, thanks for making it less cluttered 👏
