### ISSUE TITLE
Notebooks: run by line does not go across cells

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#144106]
Run by line currently only works in a single cell. It is not possible to step in or to go to the next cell.
Also no debug toolbar is shown. Luckily the cell toolbar is now more sticky, so this feature is more usable for large cells - when I tried it I really could not click because the toolbar was getting hidden for larger cells.

From my perspective this feels like a limited debug experience. Was there any reasoning why we designed the feature in such a way?

fyi @minsa110

**Comment by roblourens** [comment]
It's designed to be as simple as possible, and if you want the debug toolbar, you can use the "Debug cell" mode.

Normally in a notebook you focus on one cell at a time, so I think that stepping across cells would not be intuitive
