### ISSUE TITLE
Extension info pop-up chasing, while a nostalgic throwback to early 2000s web design problems, is an annoying usability issue that should be fixed

### ISSUE THREAD

**Issue by posita** [microsoft/vscode#144100]
```
Version: 1.64.2 (Universal)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

1. Navigate to your extensions (I'm accessing them in a remote container, but I don't think it matters).
2. Hover over one to reveal the pop-up. Note that someone has placed a link in there (that isn't available on any other surface). Great! Let's follow it!
3. Realize in utter frustration that, unless you're Flash Gordon, the pop-up disappears before you can move your mouse cursor over it. It taunts you, seductively holding out the keys to unlock the secrets of the universe, while remaining ever out of reach. Neat!

https://user-images.githubusercontent.com/222581/156019191-e17da1ec-7529-49b9-a913-26735efd7232.mov

While I appreciate the retro feel, I think usability suffers. If that surface is going to be interactive, consider keeping the pop-up open long enough for normal human users to get their mouse over there.

**Comment by posita** [comment]
@sharedrory, I noticed you down-voted this. Is that because you can't reproduce it? If that's the case, can you post the version details of which version of VS Code you're running? If this is a regression, or platform-specific, that is probably helpful to know.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/115034
