### ISSUE TITLE
When connected to VPN extension do not load in the extension panel

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#144153]
Issue Type: <b>Bug</b>

When connected to VPN the extension panel does not load.
If updates are available for extensions it shows `installing` perpetually.

Sometimes this also affects the content assist (only `Loading...` is displayed)

i tried to set the http.proxy setting but nothing changed.
Everything works fine if I disconnect from VPN
![image](https://user-images.githubusercontent.com/9264813/156130598-189f5aaf-2ba4-4c51-b0d2-d9792115ee66.png)

VS Code version: Code - Insiders 1.65.0-insider (b7730c807c1e0fdacdcc91a854bb963715b2a89b, 2022-02-28T14:37:48.095Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (7.17GB free)|
|Process Argv|--crash-reporter-id f5a247d1-3472-440d-8ba1-1c2f1706a088|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|13.2.4
vscode-markdownlint|Dav|0.46.0
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.0
prettier-vscode|esb|9.3.0
gitkraken-authentication|git|1.0.3
output-colorizer|IBM|0.1.2
vscode-typescript-next|ms-|4.7.20220228
angular-console|nrw|17.14.1
vscode-yaml|red|1.4.0
sonarlint-vscode|Son|3.3.3
code-spell-checker|str|2.1.7
vscode-stylelint|sty|1.2.2
vscodeintellicode|Vis|1.2.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30421357
vsclayoutctrc:30405799
dsvsc009:30440021
pythonvsnew555:30438690
vsbas813:30436447
vscscmwlcmt:30428973
azactmsalcf:30432849
vscgsvidc:30433759
dockersurvey3cf:30438169
pynewfile477:30443519
vsnot107:30443614

```

</details>

**Comment by sandy081** [comment]
Can you please provide following logs?

-  F1 > Open View... > Log (Shared Process)

Also try putting some text in the extensions search input box and share following log

- F1 > Developer: Toggle Developer Tools > Console

**Comment by sanket-bhalerao** [comment]
shared process log:
[2022-03-07 20:00:09.442] [sharedprocess] [info] Starting worker process with pid 34508 (type: fileWatcher, window: 1).
[2022-03-07 20:00:10.227] [sharedprocess] [info] Getting Manifest... redhat.vscode-yaml
[2022-03-07 20:00:11.903] [sharedprocess] [info] Installing extension: redhat.vscode-yaml
[2022-03-07 20:00:16.416] [sharedprocess] [info] Downloaded extension: redhat.vscode-yaml c:\Users\username\AppData\Roaming\Code - Insiders\CachedExtensionVSIXs\redhat.vscode-yaml-1.5.0
[2022-03-07 20:00:16.879] [sharedprocess] [info] Extracted extension to c:\Users\username\.vscode-insiders\extensions\.53d15389-c7c2-4f18-b5d2-294066801563: redhat.vscode-yaml
[2022-03-07 20:00:16.895] [sharedprocess] [info] Renamed to c:\Users\username\.vscode-insiders\extensions\redhat.vscode-yaml-1.5.0
[2022-03-07 20:00:16.921] [sharedprocess] [info] Extracting completed. redhat.vscode-yaml
[2022-03-07 20:00:16.935] [sharedprocess] [info] Extension installed successfully: redhat.vscode-yaml
[2022-03-07 20:02:58.565] [sharedprocess] [info] Starting worker process with pid 81888 (type: fileWatcher, window: 3).
[2022-03-07 20:03:04.000] [sharedprocess] [info] Worker process with pid 81888 terminated normally (type: fileWatcher, window: 3).
[2022-03-07 20:03:15.982] [sharedprocess] [info] Starting worker process with pid 85888 (type: fileWatcher, window: 3).

**Comment by sanket-bhalerao** [comment]
devtools:
 WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.references-view' wants API proposal 'treeViewDragAndDrop' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:sourcemap:1960 Overwriting grammar scope name to file mapping for scope source.js.jsx.
Old grammar file: file:///c%3A/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/javascript/syntaxes/JavaScriptReact.tmLanguage.json.
New grammar file: file:///c%3A/Users/username/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.7.20220306/syntaxes/JavaScriptReact.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1960
workbench.desktop.main.js:sourcemap:1960 Overwriting grammar scope name to file mapping for scope source.js.
Old grammar file: file:///c%3A/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/javascript/syntaxes/JavaScript.tmLanguage.json.
New grammar file: file:///c%3A/Users/username/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.7.20220306/syntaxes/JavaScript.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1960
workbench.desktop.main.js:sourcemap:1960 Overwriting grammar scope name to file mapping for scope source.ts.
Old grammar file: file:///c%3A/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/typescript-basics/syntaxes/TypeScript.tmLanguage.json.
New grammar file: file:///c%3A/Users/username/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.7.20220306/syntaxes/TypeScript.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1960
workbench.desktop.main.js:sourcemap:1960 Overwriting grammar scope name to file mapping for scope source.tsx.
Old grammar file: file:///c%3A/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/typescript-basics/syntaxes/TypeScriptReact.tmLanguage.json.
New grammar file: file:///c%3A/Users/username/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.7.20220306/syntaxes/TypeScriptReact.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1960
workbench.desktop.main.js:sourcemap:1960 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///c%3A/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///c%3A/Users/username/.vscode-insiders/extensions/redhat.vscode-yaml-1.4.0/syntaxes/yaml.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1960
workbench.desktop.main.js:sourcemap:71 [Extension Host] undefined (at s.getReferenceBranchNameForFile (c:\Users\username\.vscode-insiders\extensions\sonarsource.sonarlint-vscode-3.3.3\dist\extension.js:1:349830))
workbench.desktop.main.js:sourcemap:605   ERR [uncaught exception in main]: Render frame was disposed before WebFrameMain could be accessed: Error: Render frame was disposed before WebFrameMain could be accessed
    at De (C:\Users\username\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:75:56966)
    at Function.<anonymous> (C:\Users\username\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:75:57136)
workbench.desktop.main.js:sourcemap:71 [Extension Host] undefined (at s.getReferenceBranchNameForFile (c:\Users\username\.vscode-insiders\extensions\sonarsource.sonarlint-vscode-3.3.3\dist\extension.js:1:349830))
workbench.desktop.main.js:sourcemap:605   ERR [uncaught exception in main]: Render frame was disposed before WebFrameMain could be accessed: Error: Render frame was disposed before WebFrameMain could be accessed
    at De (C:\Users\username\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:75:56966)
    at Function.<anonymous> (C:\Users\username\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:75:57136)
workbench.desktop.main.js:sourcemap:71 [Extension Host]% Object (at s.getReferenceBranchNameForFile (c:\Users\username\.vscode-insiders\extensions\sonarsource.sonarlint-vscode-3.3.3\dist\extension.js:1:349830))
workbench.desktop.main.js:sourcemap:605   ERR [uncaught exception in main]: Render frame was disposed before WebFrameMain could be accessed: Error: Render frame was disposed before WebFrameMain could be accessed
    at De (C:\Users\username\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:75:56966)
    at Function.<anonymous> (C:\Users\username\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:75:57136)
workbench.desktop.main.js:sourcemap:71 [Extension Host] ApplicationInsights:CorrelationIdManager Array(1) (at Function.e.warn (c:\Users\username\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\html-language-features\client\dist\node\htmlClientMain.js:1:1215))
I @ workbench.desktop.main.js:sourcemap:71
workbench.desktop.main.js:sourcemap:71 [Extension Host]% Object (at s.getReferenceBranchNameForFile (c:\Users\username\.vscode-insiders\extensions\sonarsource.sonarlint-vscode-3.3.3\dist\extension.js:1:349830))
workbench.desktop.main.js:sourcemap:71 [Extension Host]% Object (at s.getReferenceBranchNameForFile (c:\Users\username\.vscode-insiders\extensions\sonarsource.sonarlint-vscode-3.3.3\dist\extension.js:1:349830))
workbench.desktop.main.js:sourcemap:71 [Extension Host]% Object (at s.getReferenceBranchNameForFile (c:\Users\username\.vscode-insiders\extensions\sonarsource.sonarlint-vscode-3.3.3\dist\extension.js:1:349830))
workbench.desktop.main.js:sourcemap:71 [Extension Host] undefined (at s.getReferenceBranchNameForFile (c:\Users\username\.vscode-insiders\extensions\sonarsource.sonarlint-vscode-3.3.3\dist\extension.js:1:349830))
workbench.desktop.main.js:sourcemap:605   ERR [uncaught exception in main]: Render frame was disposed before WebFrameMain could be accessed: Error: Render frame was disposed before WebFrameMain could be accessed
    at De (C:\Users\username\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:75:56966)
    at Function.<anonymous> (C:\Users\username\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:75:57136)
workbench.desktop.main.js:sourcemap:71 [Extension Host]% Object (at s.getReferenceBranchNameForFile (c:\Users\username\.vscode-insiders\extensions\sonarsource.sonarlint-vscode-3.3.3\dist\extension.js:1:349830))
workbench.desktop.main.js:sourcemap:71 [Extension Host] undefined (at s.getReferenceBranchNameForFile (c:\Users\username\.vscode-insiders\extensions\sonarsource.sonarlint-vscode-3.3.3\dist\extension.js:1:349830))
workbench.desktop.main.js:sourcemap:71 [Extension Host]% Object (at s.getReferenceBranchNameForFile (c:\Users\username\.vscode-insiders\extensions\sonarsource.sonarlint-vscode-3.3.3\dist\extension.js:1:349830))
workbench.desktop.main.js:sourcemap:71 [Extension Host]% Object (at s.getReferenceBranchNameForFile (c:\Users\username\.vscode-insiders\extensions\sonarsource.sonarlint-vscode-3.3.3\dist\extension.js:1:349830))
workbench.desktop.main.js:sourcemap:71 [Extension Host] undefined (at s.getReferenceBranchNameForFile (c:\Users\username\.vscode-insiders\extensions\sonarsource.sonarlint-vscode-3.3.3\dist\extension.js:1:349830))
workbench.desktop.main.js:sourcemap:71 [Extension Host]% Object (at s.getReferenceBranchNameForFile (c:\Users\username\.vscode-insiders\extensions\sonarsource.sonarlint-vscode-3.3.3\dist\extension.js:1:349830))
workbench.desktop.main.js:sourcemap:605   ERR [uncaught exception in main]: Render frame was disposed before WebFrameMain could be accessed: Error: Render frame was disposed before WebFrameMain could be accessed
    at De (C:\Users\username\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:75:56966)
    at Function.<anonymous> (C:\Users\username\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:75:57136)
workbench.desktop.main.js:sourcemap:71 [Extension Host] undefined (at s.getReferenceBranchNameForFile (c:\Users\username\.vscode-insiders\extensions\sonarsource.sonarlint-vscode-3.3.3\dist\extension.js:1:349830))
workbench.desktop.main.js:sourcemap:605   ERR [uncaught exception in main]: Render frame was disposed before WebFrameMain could be accessed: Error: Render frame was disposed before WebFrameMain could be accessed
    at De (C:\Users\username\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:75:56966)
    at Function.<anonymous> (C:\Users\username\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:75:57136)
workbench.desktop.main.js:sourcemap:71 [Extension Host] undefined (at s.getReferenceBranchNameForFile (c:\Users\username\.vscode-insiders\extensions\sonarsource.sonarlint-vscode-3.3.3\dist\extension.js:1:349830))

**Comment by sandy081** [comment]
May I know if the Extensions Viewlet hangs while looking for installed extensions or it also hangs when searching for extensions in Marketplace?

**Comment by sanket-bhalerao** [comment]
In both cases it goes in loading state.
Sometimes this behaviour appears after a while of launching vscode.

**Comment by sandy081** [comment]
When it goes into loading state, can you please try following and share what is shown in the console?

- F1 > Toggle Shared Process

**Comment by sanket-bhalerao** [comment]
it shows a blank window
![image](https://user-images.githubusercontent.com/9264813/158334469-77617196-fb5a-4254-ad44-a0c9bfb31298.png)

**Comment by sandy081** [comment]
Hmm no info from here too. 

Can you please record following and share with us?

- Enable log level to trace. Use command `F1 > Set Log Level...`
- Open the Shared Process Log. Use command `F1 > Open View... > Log (Shared)`
- Go to extensions view and click on Filter/Funnel icon on the top and select `Installed` filter

Share us the shared process log.

**Comment by sanket-bhalerao** [comment]
nothing shows up in the logs :(

![Recording 2022-03-18 at 01 04 16 (1)](https://user-images.githubusercontent.com/9264813/158881799-abb4a593-d000-432f-ab62-d58c80f09f8a.gif)

attaching devtools log if that helps
[devtools log.log](https://github.com/microsoft/vscode/files/8289974/devtools.log.log)

**Comment by sanket-bhalerao** [comment]
@sandy081 just FYI, things run smoothly on stable vscode build while connected to the same VPN. 
has anyone else observed similar issues with just insiders build (I do not see any such open issue or comments on this issue).
could it be the insiders' installation I have is corrupted?

**Comment by sandy081** [comment]
I do not see any activity in the shared process so, I suspect something is wrong with it. @deepak1556 is there any other way to troubleshoot it?

**Comment by sanket-bhalerao** [comment]
@sandy081 any additional info i can help with?

**Comment by rtabulov** [comment]
i have exactly the same issue 
i'm using ivpn and latest stable vscode

**Comment by rtabulov** [comment]
this line is present when not connected to vpn and is not present when connected, i think it might be the problem
```
[2022-04-18 22:09:10.130] [sharedprocess] [trace] RequestService#request https://az764295.vo.msecnd.net/extensions/workspaceRecommendations.json.gz
```
@sanket-bhalerao can you suggest a fix please?

**Comment by sanket-bhalerao** [comment]
@rtabulov,
I have not found any fix so far. The best workaround I have is to disconnect VPN altogether or move to a Stable release.
I am waiting for someone @sandy081 or @deepak1556 to revert on this.

**Comment by sandy081** [comment]
@deepak1556 I do not see any activity happening in the shared process from the [video](https://github.com/microsoft/vscode/issues/144153#issuecomment-1071279548). Is there a way to troubleshoot shared process? 


@sanket-bhalerao Meanwhile can you please profile shared process by following this wiki https://github.com/microsoft/vscode/wiki/Performance-Issues#shared-process and see if it is healthy or not.

**Comment by sanket-bhalerao** [comment]
@sandy081 does VSCode insiders connect to something diff for getting the git icons or to get extensions? 
VSCode Stable version do not get this issue on the same VPN.
This makes me wonder what is different here?

**Comment by sandy081** [comment]
Seems to be a set up issue, hence assigning to @deepak1556

**Comment by sanket-bhalerao** [comment]
@deepak1556 anything i can check in this regards? Does any URL need to be whitelisted?

> @sandy081 does VSCode insiders connect to something diff for getting the git icons or to get extensions? VSCode Stable version do not get this issue on the same VPN. This makes me wonder what is different here?

**Comment by sanket-bhalerao** [comment]
> while can you please profile shared process by following this wiki

@sandy081 I tried to profile but the start button appears disabled
![image](https://user-images.githubusercontent.com/9264813/177375188-cbc3b989-4607-40fb-b8fd-4ecac9f3ac0c.png)

**Comment by sanket-bhalerao** [comment]
@sandy081 @deepak1556 , 
i found a list of hostname that should be allowed by the firewall https://code.visualstudio.com/docs/setup/network,
is this list any different in case of insiders build and stable build?

**Comment by sanket-bhalerao** [comment]
i had "window.enableExperimentalProxyLoginDialog": true, in my settings.json.
not sure what this does or why I added it to begin with but removing it seems make insiders build run normally 🥳
