### ISSUE TITLE
No way to see cell progress if bottom of the cell is out of view

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#144114]
1. Have a large notebook cell such that the bottom of the cell is out of view
2. Run the cell
3. There is no feedback to the user that the run is a success or that it is in progress. Since that is rendered on the bottom of the cell which is not visible. 

The bottom of the cell needs to be more sticky.

fyi @minsa110 @nneva

**Comment by isidorn** [comment]
Hmm show blue progress in the editor title area whenever any of the cell are in progress? Same as we do for other editors?

fyi @bpasero for progress ideas

**Comment by roblourens** [comment]
We already do that, if the cell is not scrolled into view. And you do have the indication that the run is in progress, there is a progress bar on the cell and the run button changes to a stop button. I thought this was just about missing the checkmark or X.

**Comment by isidorn** [comment]
But my case is that the cell is scrolled into view, just the cell is large so the bottom of the cell is not visible.

**Comment by roblourens** [comment]
Is it that the bottom and the top are both not visible? But you get the stop button still right?

**Comment by isidorn** [comment]
Correct.

**Comment by roblourens** [comment]
Sure let's try it
