### ISSUE TITLE
VSCode Problem seeing non-existent Folder

### ISSUE THREAD

**Issue by SercanKaya0** [microsoft/vscode#144116]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

I'm clearing the VSCode cache, how does it see a file that I have deleted completely, which is not anywhere, including the finder? It's been making a ridiculous mistake for hours.

path -> xxx/xxxx/Yyyyyy/ => 
path -> xxx/xxxx/yyyyyy/ => 
How to bypass a problem like the one above?

**Comment by JacksonKearl** [comment]
Please explain what you are seeing, including your operating system and vs code version number, the steps you took, and any photos of the result
