### ISSUE TITLE
No editor symbols when open files

### ISSUE THREAD

**Issue by qiray** [microsoft/vscode#144177]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.64.2 f80445acd5a3dadef24aa209168452a3d97cc326 x64
- OS Version: `Linux Mint 20.2 Uma Linux 363 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

I found very strange issue. Editor symbols dissapear when I open some new files.

Steps to Reproduce:

1. Open VS Code
2. Open some source files.
3. Ctrl+Shift+O to watch symbols.
4. Symbols exist.
5. Open more files.
6. Symbols disappear even in already opened files.

I found this issue in some language provider extensions. For example in C/C++ for Visual Studio Code (https://github.com/microsoft/vscode-cpptools) and vscode-lua (https://github.com/trixnz/vscode-lua). In previous version of VS Code (or maybe in version before last) I didn't have this problem. 

I will provide extra info if you need it.

**Comment by bpasero** [comment]
This sounds like a general issue to me then with regards to language services for the file. From the video it seems as if symbols stop to be resolved as soon as the XML file has been opened.

Do you have a specific extension installed for XML that maybe get's activated?

**Comment by qiray** [comment]
@bpasero, well it was a problem with an extension : https://github.com/danschultequb/qub-typescript-xml-vscode. I disabled it and now everything is correct. Sorry for wasting your time.
