### ISSUE TITLE
Ability to move file explorer like editor window

### ISSUE THREAD

**Issue by willmexe** [microsoft/vscode#144186]
I would love to be able to move the file explorer like a regular window as it would open up a ton of customizability like having the terminal under the file explorer which I would prefer to have on my laptop as it has a smaller screen and any saved space is good.

**Comment by JacksonKearl** [comment]
It's not clear to me what you mean by "regular window", though you can drag and drop the terminal to be under the explorer:
<img width="729" alt="image" src="https://user-images.githubusercontent.com/8586769/156218012-7ef28788-378c-47ed-ad0a-55485982e191.png">
