### ISSUE TITLE
Jupyter Notebook needs a minimap

### ISSUE THREAD

**Issue by Hkllopp** [microsoft/vscode#144162]
Issue Type: <b>Feature Request</b>

Can we please have a minimap of our notebook as we do in other files open in VSCode ?
Notebooks can sometimes get very long and fastidious to navigate in, even with title architecture and a dynamic minimap would be really helpful !
Thanks !

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by rebornix** [comment]
Thanks for the feedback, let's merge this into https://github.com/microsoft/vscode/issues/115266
