### ISSUE TITLE
Irrelevant "information" message when using missing identifier for composite debugging

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#14419]
#14171

``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program 1",
            "program": "${workspaceRoot}/app.js",
            "cwd": "${workspaceRoot}"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program 2",
            "program": "${workspaceRoot}/app2.js",
            "cwd": "${workspaceRoot}"
        },
        {
            "type": "composite",
            "request": "launch",
            "name": "Launch Both Programs",
            "configurationNames": [
                "fake"
            ]
        }
    ]
}
```

In this launch config, I reference a `fake` configuration which does not exist.

When pressing Play I get this:

![image](https://cloud.githubusercontent.com/assets/22350/19686159/48b244fa-9ac0-11e6-82be-a8754e521557.png)
- The message tells me to configure the launch config, which I already did.
- The message is an information, when it should be a warning/error, since the feature can't work without fixing the issue.

**Comment by joaomoreno** [comment]
Also, when setting up two configuration names, one correct but one wrong, you still get the message but the correct one will actually launch. Either all should launch or none should.

**Comment by isidorn** [comment]
Not applicable anymore we have put composits / compounds on hold
