### ISSUE TITLE
vs code becomes heavy and response is too slow after each update is received

### ISSUE THREAD

**Issue by kumaryashwanth07** [microsoft/vscode#144199]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: Windows_NT x64 10.0.18362

**VS Code becomes heavy and response is too slow after each update is received**

* after each update it has become so heavy and loaded with bloatware
* enough of adding too many unnecessary features
* **as much as possible concentrate on improving overall performance as well initial startup time**

**Comment by vfonic** [comment]
I came to this repo today to say exactly this.

I opened Sublime text today by mistake and it was such a smooth experience. Everything was instant.

Couple of things that are too slow:
1. Syntax highlighting (language parser/server)
2. Basic editor functionality: typing, searching, changing/selecting language
3. Opening new editor window (new project or a single file)
This is especially noticeable when you need to quickly edit something in a single file. It takes ~10+ seconds for the editor to load. It should take less than 1 second.
4. Basically everything is slightly slow.

**Comment by deepak1556** [comment]
Please attach the startup profiles and timer numbers following these steps 

https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly
https://github.com/microsoft/vscode/wiki/Performance-Issues#read-the-startup-timers

**Comment by vfonic** [comment]
Wow! The exploration build is more than twice as fast! It took roughly ~10 seconds to start VS Code and about ~3 seconds to start VS Code - Exploration! 😱 

When is this going live? :)

I'm switching to exploration build immediately, but I'd love to see this as stable to experience less compatibility issues while working in VS Code daily.

**Comment by deepak1556** [comment]
Thanks for testing, we are currently targeting March 2022 for update to the newer runtime. You can follow https://github.com/microsoft/vscode/issues/136260 issue for updates which has the same root cause.

**Comment by flaviodelgrosso** [comment]
I personally didn't notice slowness during starting up, it's quite immediate and this is awesome, but after some days of utilization it takes a while to close (command + Q). The window close immediately but It seems there's some delay before effectively quitting the process.
If I clear the `Library/Application Support/Code` folder, the application quit instantly again.
This behaviour appeared 3-4 times during this last 2 months.

I'm on macOS Monterey 12.2.1 ARM64.
