### ISSUE TITLE
Shell integration terminal silently fails to run tasks

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#144103]
`"terminal.integrated.shellIntegration.enabled": true`
Do not have `ipykernel` installed

1. Open a notebook file, try to run it
2. You get a dialog that `ipykernel` is not installed. You click install
3. Terminal opens, but nothing gets installed. Notification progress keeps on spinning

I see two issues here. I am in a terminal state where it seems that tasks can not be run properly
There is no "fail" return code for the task runner, so the Jupyter extension keeps on showing progress for the task that is not being run

fyi @minsa110

![Screenshot 2022-02-28 at 17 54 45](https://user-images.githubusercontent.com/1926584/156024797-cbb99412-c174-458b-b687-ad0e1032fc19.png)

**Comment by Tyriar** [comment]
I don't think this is a task. Also the build that just went out should fix shell integration in zsh: https://github.com/microsoft/vscode/issues/143629
