### ISSUE TITLE
scrolloff doesn't work in jupyter notebook cell

### ISSUE THREAD

**Issue by spiffamoo** [microsoft/vscode#144221]
Issue Type: <b>Bug</b>

Not sure if this is intended behaviour, but setting a nonzero scrolloff option does nothing in a jupyter notebook cell. It works fine in other filetypes.

1. Have "editor.CursorSurroundingLines" set to a nonzero value, say 8.

2. Open a .py file, cursor behaviour when scrolling works as expected.

3. Export that .py file to .ipynb. scrollOff no longer works. 

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.98GB free)|
|Process Argv|--crash-reporter-id 24e71f4a-58c1-42ef-b1e2-20d7b343a49b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
gitlens|eam|12.0.0
gitkraken-authentication|git|1.0.3
align-by-regex|jan|1.0.4
csharp|ms-|1.24.1
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.4
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
autodocstring|njp|0.6.1
indent-rainbow|ode|8.2.2
material-icon-theme|PKi|4.13.0
material-product-icons|PKi|1.1.2
comment-divider|sta|0.4.0
errorlens|use|3.4.1
vim|vsc|1.22.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
vscop841cf:30438916
dsvsc009:30440023
pythonvspyt640:30442238
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvid2:30438800
helix:30440343
vscaac:30438847
vsnot107:30443614

```

</details>

**Comment by yar00001** [comment]
Any updates for this issue by any chance?

**Comment by dqgthb** [comment]
I'm also interested in solving this annoying behavior. :(((

**Comment by rebornix** [comment]
let's merge this issue into https://github.com/microsoft/vscode/issues/167967
