### ISSUE TITLE
the marked "Reload Required" extensions not reload automatically once vscode restart

### ISSUE THREAD

**Issue by SilenceHe** [microsoft/vscode#144226]
Issue Type: <b>Feature Request</b>

Once vscode restart, the marked "Reload Required" extensions not reload automatically, we need do it by manual, is there any plans to improve this?

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22563
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

**Comment by ctf0** [comment]
same here except that i now need to remove the extension then install it for the `reload required` button to go away.

```
Version: 1.66.0-insider
Commit: 6b7453421201c888b81eae5c04ec822a6423608f
Date: 2022-03-11T05:28:10.803Z
Electron: 17.1.1
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.3.0
```

**Comment by alexdevero** [comment]
Also same here, but I have all allowed extensions showing the `Reload required` button. Reloading editor does nothing.
```
Version: 1.66.0-insider
Commit: 6b7453421201c888b81eae5c04ec822a6423608f
Date: 2022-03-11T05:17:19.559Z
Electron: 17.1.1
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by IllusionMH** [comment]
/needsMoreInfo

@SilenceHe please update to the latest stable version (at least 1.65.1)and see if this issue is still reproducible.

------

@ctf0 @alexdevero you have different version from OP and different bug. See #144900 which should be fixed in next Insiders build.
