### ISSUE TITLE
Code is jumping when I have an error

### ISSUE THREAD

**Issue by eli1stark** [microsoft/vscode#144200]
- VS Code Version: 1.64.2
- OS Version: macOS Monterey 12.1

Steps to Reproduce:

1. Try to write code that causes an error
2. Remove add the code like in the video
3. In the video I'm using Dart code + Flutter plugins

https://user-images.githubusercontent.com/57593530/156234546-cf899ab4-24b3-40b2-9446-56d9c86cd882.mp4

**Comment by matty-r** [comment]
I'm getting this as well with the Rust Analyzer extension. It's infuriating.

https://user-images.githubusercontent.com/9965448/156260502-c42b9535-ea87-44c5-8053-d767af9bdce5.mp4

**Comment by Tyriar** [comment]
Yeah this looks like an extension using the code lens API.
