### ISSUE TITLE
Proposal  to save the context of opened files

### ISSUE THREAD

**Issue by nicosampler** [Microsoft/vscode#14424]
Would be great if the editor provide us the functionality to save the context of the opened files and be able to save different contexts. this would be really useful when you works in different issues in the same project.

**Comment by weinand** [comment]
@nicosampler what do you mean by 'context of the opened files'? Please provide more details about your feature request.

**Comment by nicosampler** [comment]
Hey @weinand,
 Let me put an example, I'm working in the Issue_A and I need open the files A, B, C, D, then for some reason I need start to work on Issue_B and I need open the files J, H, D, Z. would be very useful if I can save the context for the current opened files with a descriptive name. That would be useful too when you need work on some part of the app where you usually need open the same files.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
