### ISSUE TITLE
Notifications with 2+ buttons should use primary and secondary button styles

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#144207]
Currently notifications are configurable to display multiple primary buttons. Here's an example from our [notification guidelines](https://code.visualstudio.com/api/references/extension-guidelines#notifications):

<img width="451" alt="notification-warning" src="https://user-images.githubusercontent.com/25163139/156245970-9d6726ca-6478-45a3-a610-24e9361d9097.png">

Generally using a bunch of primary actions is avoided as a basic UX principle—mostly given the added load it places on users to understand which option is the most likely one to take.

I can think of a few approaches off the top of my head:
- Strictly enforce against using multiple primary actions in the API
- Somehow lint for multiple contributed primary actions to gently discourage extension authors
- Just add guidance to the notification API docs
- Some combination of the above

This could extend to other areas as well (empty views, for example).

**Comment by gjsjohnmurray** [comment]
I'm not aware that we extension developers currently have a way of signalling that a [MessageItem](https://code.visualstudio.com/api/references/vscode-api#MessageItem) is or is not a primary action.

**Comment by bpasero** [comment]
I am not sure I understand the motivation behind this:
* is this about only ever showing a single button in a notification 
* or about having a way to mark 1 button as primary so that the others can be shown less prominently?

@misolori maybe my memory is wrong, but didn't you once work on a design where only 1 button in a notification toast shows in blue and the others in grey or less prominent to simulate how a real dialog would look like?

**Feedback to suggestions:**

> Strictly enforce against using multiple primary actions in the API

We cannot do that unless we want to break our API which we never do.

> Somehow lint for multiple contributed primary actions to gently discourage extension authors

I think that is equally against our rules, besides I wouldn't even know how to do that with TypeScript today, and we have no API specific linting as far as I know. I also think this would be against our model of shipping a `vscode.d.ts` file that extensions compile against to get their errors and warnings.

> Just add guidance to the notification API docs

Sure we can do that but I doubt it would change anything since we cannot enforce it.

If we want to go down the path of a visual update, a pragmatic solution could be to only render the first button in blue and the others in a different color to indicate the primary button, like a dialog:

![image](https://user-images.githubusercontent.com/900690/156309664-640a882e-1336-4b55-b9ee-78fbdf0eed2e.png)

**Comment by daviddossett** [comment]
> - is this about only ever showing a single button in a notification
> - or about having a way to mark 1 button as primary so that the others can be shown less prominently?

The latter. The basic idea is to ensure we aren't confusing users with 2+ primary buttons. Instead I think we should follow the modal pattern (like your screenshot above) where there can be multiple buttons, but only one primary. The rest would be styled as secondary buttons.

> If we want to go down the path of a visual update, a pragmatic solution could be to only render the first button in blue and the others in a different color to indicate the primary button, like a dialog.

I think this could work. I'd imagine it would put some of the burden on the author to ensure the action they deem to be primary in the first position. Certainly better than nothing as they would get the visual feedback when they see the notification and could correct the order as needed.

**Comment by bpasero** [comment]
Let's wait for Miguels feedback, I think we had designs on this...

**Comment by bpasero** [comment]
I also wonder if the notification toast is focused and I hit `Enter` key, whether the primary action should execute.

**Comment by daviddossett** [comment]
> I also wonder if the notification toast is focused and I hit Enter key, whether the primary action should execute.

Not sure off the top of my head. This sounds reasonable in principle but I suppose it depends if there any potentially destructive actions that could be accidentally triggered. Probably not a great use of notifications in the first place if that were the case, but still worth considering.

**Comment by misolori** [comment]
Yea I remember we discussed this in https://github.com/microsoft/vscode/issues/102087 when I introduced the secondary button style (https://github.com/microsoft/vscode/issues/58399) for the very same reasons: making it easier for users to tell which actions is the default. The API was one of the limiting factors but if we're able to provide a visual update to avoid breaking the API, that would be great. It would be great if extension authors can also figure out how to designate a "primary" or "default" action.

**Comment by bpasero** [comment]
Yeah this is the design I had in mind:

![image](https://user-images.githubusercontent.com/900690/156425756-4fdd387f-cd86-4e61-919e-37d75b69ca4b.png)

Btw modal dialogs work quite the same: the first button is the primary button by definition, I do not even think you can change that in Electron programmatically and I think this also makes sense from a UX point of view.

**Comment by bpasero** [comment]
Oh, I am wrong: 

https://github.com/electron/electron/blob/16-x-y/docs/api/dialog.md#dialogshowmessageboxbrowserwindow-options

You can specify a `defaultId` which is the index of the primary button. 

Nevertheless, having the first button be primary imho is OK to go with, not sure an explicit API would be needed.

Btw one likely reason why extensions tend to use more primary buttons is that there is no API for showing secondary actions in the menu.

**Comment by daviddossett** [comment]
Good to know they provide that option. Makes sense to me.

> Btw one likely reason why extensions tend to use more primary buttons is that there is no API for showing secondary actions in the menu.

That was my assumption. Rendering the first button with primary styling seems like enough as a starting point. Are there any other considerations for the actual markup? E.g. how primary buttons in forms use the `submit` attribute. Not sure if anything is needed in this context.

**Comment by bpasero** [comment]
I think our custom buttons have never really been using the `submit` kind of `<form>` in HTML. My understanding is that `submit` is to signal the target URL to send data to, but we always handle the click via TypeScript.

**Comment by bpasero** [comment]
Oh nevermind, we already have the design from custom dialogs:

![image](https://user-images.githubusercontent.com/900690/156427648-1860ed05-0e84-48fc-93c9-cfe689662f37.png)

**Comment by bpasero** [comment]
Not sure that color has sufficient contrast though, maybe David you could check that out.

**Comment by daviddossett** [comment]
Perhaps form markup wasn't the best example from my end—I'm mostly thinking about whether or not we need to distinguish between primary and secondary actions for accessibility purposes. Maybe @isidorn would have some input here?

I'll look into the existing secondary button styling 👍 

There are other areas around the workbench this treatment could apply to as well. E.g. welcome views that feature multiple buttons.

<img width="316" alt="CleanShot 2022-03-02 at 10 47 51@2x" src="https://user-images.githubusercontent.com/25163139/156428096-cd1fc2ee-d3e6-4a9d-9eff-6f82c7974724.png">

**Comment by bpasero** [comment]
Yeah I had thought about welcome views, but there I think all of the buttons are probably somewhat primary, or at least there is not a main button imho.

Yeah agree for accessibility, but whatever we do there I would have assumed we already did for the custom dialogs and if not it should apply there too.

**Comment by daviddossett** [comment]
Nice! Looks great. 

Out of curiosity, do we have the same ordering logic for notification button groups as we do for custom dialogs? I.e. the primary buttons are ordered far left for Windows and far right for Mac?

**Comment by bpasero** [comment]
I am not sure, we use a `ButtonBar` for notifications:

https://github.com/microsoft/vscode/blob/94322e8258eb28e4ff82d32c092d06cc0414e278/src/vs/workbench/browser/parts/notifications/notificationsViewer.ts#L470

@sbatten did the custom dialogs initially and can maybe chime in on whether custom dialogs follow the OS style of how to order the buttons.

Changing the order of buttons for notifications might break muscle memory though, so I am not sure we should do it unless there is good reason for it.

**Comment by sbatten** [comment]
yes custom dialogs follow OS conventions regarding ordering. on windows primary on the left and cancel is last. on mac os primary is on the right and cancel is to the left of the primary.

**Comment by bpasero** [comment]
I am not seeing any special accessibility requirements for buttons in a modal dialog checking out https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html so I suspect we are fine here. Also https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role does not indicate anything more. 

Since I pushed this, I think we can go ahead and close this as fixed.

**Comment by daviddossett** [comment]
Thanks for taking care of this! Looks great 🎉

I'll do a separate investigation on the button ordering across the product. Definitely good to keep muscle memory in mind in any case.

**Comment by bpasero** [comment]
**Verification:** verify that notifications (really any) with buttons show only the first one in a primary color. Changing themes preserves the semantic meaning of a primary button, similar to how native dialogs work.

**Comment by bpasero** [comment]
Yes, its a bug that the extension has put the primary action as a secondary action. @chrmarti can fix that

**Comment by MrAndersen1** [comment]
On mac on insiders my custom dialogs show the primary button to the left (blue color), which it shouldn't if I understand this correctly

> yes custom dialogs follow OS conventions regarding ordering. on windows primary on the left and cancel is last. on mac os primary is on the right and cancel is to the left of the primary.

Or is it supposed to be to the left on mac too like this comment suggests?

> **Verification:** verify that notifications (really any) with buttons show only the first one in a primary color. Changing themes preserves the semantic meaning of a primary button, similar to how native dialogs work.

Not sure if I should file a bug report.

I have only checked my extension's dialogs since I cannot find a vscode dialog with buttons which isn't modal. But regardless it would have been nice to be able to specify this in extensions, especially if they don't automatically follow the os convention.

**Comment by sbatten** [comment]
My comment around custom dialogs refers to modal dialogs that pop up in the center of the window. Notifications refers to the non-modal info boxes in the bottom right of the window.

**Comment by MrAndersen1** [comment]
Thanks for explaining @sbatten, I believe I understand now. I'm assuming this is e.g. the "open file"-dialog and indeed it follows os convention.

I also assume there is no way to make the modals from e.g. showInformationMessage have buttons aligned left to right which was also confusing me talking about modals :) This is unfortunate.

So there is probably an issue here, regarding notifications, even though it's not really a bug. It should have a new issue however and I might open one in the future when it has bothered me for a while :) unless someone makes one before me.
