### ISSUE TITLE
Unable to enable extension that depends on another disabled extension (AzML)

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#144294]
The Azure ML extension requires itself and the Azure ML Remote extension to b enabled in order to operate.  It seems that the situation is detected, but when VS Code prompts to enable the main extension it fails silently and asks again and again.
![EnableBug](https://user-images.githubusercontent.com/11685408/156483076-73ec5011-974f-4604-a78f-b11a8a897285.gif)

**Comment by connor4312** [comment]
@greazer could you verify this issue or share steps on how to get into that scenario with the AML extension?

**Comment by sandy081** [comment]
Verification steps:

- Install `sandy081.999-urlhanlder` extension
- Disable `sandy081.999-urlhanlder` and `sandy081.998-test-code` extensions
- Open following url `code --open-url vscode://sandy081.999-urlhanlder/helloWorld`
- Make sure you are asked to Enable the extension and Open the URL
- Clicking on `Enable and Open` shall enable above two extensions and show `/helloWorld` notification

**Comment by connor4312** [comment]
Thanks! Will verify after lunch if no one gets to it faster

**Comment by ChaseKnowlden** [comment]
Doesn't show Hello World Notification and Doesn't enable both extensions.

**Comment by ChaseKnowlden** [comment]
Doesn't show Hello World Notification and Doesn't enable both extensions on Stable, but verification steps work on insiders.

**Comment by sandy081** [comment]
Fix is in insiders only. Stable will be released next week.
