### ISSUE TITLE
With DPI scaling, window wanders away from session to session, hiding UI elements

### ISSUE THREAD

**Issue by h-h-h-h** [microsoft/vscode#144227]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2 (user setup)
- OS Version: Windows_NT x64 10.0.19042

---

I have a wide 4K monitor with my taskbar on the right edge (not automatically hiding). I normally place VS Code on the right side of the work area (screen area minus taskbar) with Areo Snap, then resize it on the left side of the window to make it wider. I want VS Code to stay that way among sessions. However, there's a very noticible effect of the right side of the window being moved further and further under the taskbar from session to session, hiding valuable information and UI elements.

I collected the following window placement data with [WinSpy++](https://www.catch22.net/software/winspy) v1.7 (portable) with a shortcut to it where I configured under "Compatibility" that the app itself should do the scaling, meaning the window coordinates it produces are exact and numerically unscaled. One line is one VS Code session, if not otherwise specified -- i.e., I always closed and reopened VS Code.

- 125% DPI scaling, wide taskbar on right edge of screen:

```
(left,top) - (excl. right,bottom)  -  width x height
(984,219) - (2909,1367)  -  1925x1148
(983,218) - (2915,1372)  -  1932x1154
(982,217) - (2919,1377)  -  1937x1160
(981,216) - (2924,1382)  -  1943x1166
(980,215) - (2928,1385)  -  1948x1170 [only width changes for 4 lines]
(980,215) - (2930,1385)  -  1950x1170
(980,215) - (2933,1385)  -  1953x1170
(980,215) - (2935,1385)  -  1955x1170
(979,214) - (2934,1384)  -  1955x1170 [manually 1px left and up in same session as line before]
(978,213) - (2940,1389)  -  1962x1176
(977,212) - (2944,1395)  -  1967x1183
(976,211) - (2949,1399)  -  1973x1188
(975,210) - (2953,1400)  -  1978x1190 [only width changes for 4 lines]
(975,210) - (2955,1400)  -  1980x1190
(975,210) - (2958,1400)  -  1983x1190
(975,210) - (2960,1400)  -  1985x1190
```

- 125% DPI scaling, taskbar on bottom edge of screen:

```
(987,197) - (2969,1384)  -  1982x1187
(986,196) - (2974,1389)  -  1988x1193
(985,195) - (2975,1393)  -  1990x1198 [only height changes for 5 lines]
(985,195) - (2975,1395)  -  1990x1200
(985,195) - (2975,1398)  -  1990x1203
(985,195) - (2975,1400)  -  1990x1205
(985,195) - (2975,1403)  -  1990x1208
```

- 125% DPI scaling, wide taskbar on left edge of screen:

```
(999,209) - (2988,1416)  -  1989x1207
(998,208) - (2992,1422)  -  1994x1214
(997,207) - (2997,1427)  -  2000x1220
(996,206) - (3002,1432)  -  2006x1226
(995,205) - (3005,1435)  -  2010x1230 [only width changes for 5 lines]
(995,205) - (3008,1435)  -  2013x1230
(995,205) - (3010,1435)  -  2015x1230
(995,205) - (3013,1435)  -  2018x1230
(995,205) - (3015,1435)  -  2020x1230
```

- 100% DPI scaling, wide taskbar on right edge of screen:

```
(1024,298) - (2638,1280)  -  1614x982 [identical lines]
(1024,298) - (2638,1280)  -  1614x982
(1024,298) - (2638,1280)  -  1614x982
```

**Comment by bpasero** [comment]
And/or https://github.com/microsoft/vscode/issues/115768
