### ISSUE TITLE
Emojis are considered "invisible characters"

### ISSUE THREAD

**Issue by TechStudent11** [microsoft/vscode#144286]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: `1.64.2`
- OS Version: Microsoft Windows Version 21H2 (OS Build 22000.218)

Steps to Reproduce:

1. Insert Emoji in file

### Screenshots

![image](https://user-images.githubusercontent.com/76978184/156463678-deecdae8-2dd7-4cf5-827b-5c5f5ae8412f.png)

**Comment by hediet** [comment]
This is because that particular emoji contains an invisible modifier to select a certain variant.

We could have a list of exceptions to address this though.

**Comment by TechStudent11** [comment]
> This is because that particular emoji contains an invisible modifier to select a certain variant.

Ah okay.

> We could have a list of exceptions to address this though.

So basically a list of every emoji? Or just every invisible modifier?

**Comment by hediet** [comment]
> Or just every invisible modifier?

That would be dangerous, as these invisible modifiers can be inserted between ASCII characters to invisibly change a string (`e.g. "user" or "admin"`).

**Comment by TechStudent11** [comment]
> > Or just every invisible modifier?
> 
> That would be dangerous, as these invisible modifiers can be inserted between ASCII characters to invisibly change a string, for example:
> 
> ```
> if (user.type === "us[invisible modifier here]er") {
>     ... // user
> } else {
>     ... // admin
> }
> ```

Ah okay I understand.

**Comment by KendallDoesCoding** [comment]
This seems to be resolved, please close the issue @TechStudent11

**Comment by hediet** [comment]
This is resolved because of [contextual unicode highlighting](https://github.com/microsoft/vscode/issues/140960).
