### ISSUE TITLE
Cann't run dev server over http2

### ISSUE THREAD

**Issue by zWingz** [microsoft/vscode#144233]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest
- OS Version: Github codespace

Steps to Reproduce:

1. Run a codespace
![image](https://user-images.githubusercontent.com/13031838/156307782-15c0cef0-208e-44cc-a8f5-2473afe57b8a.png)

2. `yarn && yarn compile && ./scripts/code-server.sh --without-connection-token --port 8000  --host 0.0.0.0`
3. open the dev server. It will lose some resource
![image](https://user-images.githubusercontent.com/13031838/156308023-f5ecdd13-630f-43fa-a0d6-f7818f6724c8.png)

**Comment by aeschli** [comment]
I assume the new codespace is created on a VS Code repo?

**Comment by zWingz** [comment]
@aeschli yes

**Comment by aeschli** [comment]
I can reproduce, but don't know what the problem is, sorry. Some of the requests go through, others fail.

I don't think it's related to the VS Code server but the tunneling provided by Codespaces.

**Comment by aeschli** [comment]
The error in the console is
GET https://xx-fuzzy-spork-4r4x967g962xj7-8000.preview.app.github.dev/oss-dev/static/out/vs/platform/list/browser/listService.js net::ERR_HTTP2_SERVER_REFUSED_STREAM

**Comment by aeschli** [comment]
I created an issue in the internal github codespaces bug database.
