### ISSUE TITLE
vscode stuck and crashed, causing restart

### ISSUE THREAD

**Issue by hlbbt** [microsoft/vscode#144234]
Issue Type: <b>Bug</b>

I started the project with vscode, and when I swipe to the vscode interface from other pages, vscode gets stuck and cannot be clicked.
Occasional bug, which has not appeared before, I think it is caused by the latest update

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:56.651Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 52ca6aee-7a0e-4077-9fd8-eb29e2f34f99|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.5.0
vscode-intelephense-client|bme|1.8.2
path-intellisense|chr|2.8.0
EnglishChineseDictionary|Cod|1.1.0
githistory|don|0.6.19
gitlens|eam|12.0.0
code-runner|for|0.11.7
copilot|Git|1.7.5185
gitkraken-authentication|git|1.0.3
go|gol|0.31.1
comment-translate|int|2.0.1
vscode-todo-highlight|jgc|2.0.4
simple-vim|jpo|0.0.5
identical-sublime-monokai-csharp-theme-colorizer|max|1.1.0
php-namespace-resolver|Meh|1.1.8
vscode-language-pack-zh-hans|MS-|1.64.7
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.4
gremlins|nho|0.26.0
material-icon-theme|PKi|4.13.0
var-translation|sve|0.13.33
open-in-browser|tec|2.0.0
errorlens|use|3.4.1
better-align|wwm|1.1.6
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
vscop841:30438915
dsvsc009:30440023
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343
vsnot107:30443614

```

</details>

**Comment by deepak1556** [comment]
Does the issue happen with latest stable `1.66.2` ?
