### ISSUE TITLE
Command annotations are not cleared after `cls`

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#144253]
Steps to Reproduce:
Using pwsh on Windows

1. Enable terminal shell integrations
2. Run some commands to get command annotations
3. Run `cls`

🐛 => command annotations persist after cleared new fresh prompt

**Comment by sbatten** [comment]
This actually creates additional problems as more commands are run as annotations appear in seemingly random places of larger output commands afteward

**Comment by meganrogge** [comment]
never mind, the fix for this hasn't yet been released

https://github.com/microsoft/vscode/issues/143784#issuecomment-1054371478
