### ISSUE TITLE
Shell Integration without PSReadLine in PowerShell

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#144215]
Version: 1.65.0-insider (user setup)
Commit: b7730c807c1e0fdacdcc91a854bb963715b2a89b
Date: 2022-02-28T14:37:48.095Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Enable a blind access in registry (note this is done by NVDA or JAWS when you install them): Computer\HKEY_CURRENT_USER\Control Panel\Accessibility\Blind Access
2. Make sure shell integration is on
3. if you did it right, when you load powershell you should see: `Warning: PowerShell detected that you might be using a screen reader and has disabled PSReadLine for compatibility purposes. If you want to re-enable it, run 'Import-Module PSReadLine'.`
4. Notice that the prompt gets printed over and over and over again without any way to interrupt it

Workaround: disable shell integration

**Comment by Tyriar** [comment]
I think we can just avoid this all together if PSReadLine is not loaded since on Windows we end up sending the whole command line anyway:

https://github.com/microsoft/vscode/blob/77abae96a780338d9b395ef7f6ef153607b5be99/src/vs/workbench/contrib/terminal/browser/media/shellIntegration.ps1#L31-L39
