### ISSUE TITLE
How to instruct vscode in Linux OS (Ubuntu) to trust in my CA

### ISSUE THREAD

**Issue by lgonzalezsa** [microsoft/vscode#144268]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

I was testing more my environment and notice the following:

1. My lab server has a SSL certificate issued by an internal CA
2. Using Windows OS in a VM with setup provided by my organization (which includes the CA certs) the vscode connects properly to my lab server even not having the "Allow unauthorized" setting true
3. Then for additional testing, setting up a new VM with Ubuntu installing fresh latest version of vscode and extensions
4. Adding CA certs to my Linux OS via update-ca-certificates and still not able to connect
5. In parallel, notice curl complains with curl: (60) SSL certificate problem: unable to get local issuer certificate
6. If I pass the --cacert [file] option no issues with curl command
7. Finally tried using --ignore-certificate-errors option for vscode, but no luck

**Question**: how vscode trust in CAs? is based on Chrome/Chromium certificate store? How can I instruct vscode in Linux OS to trust in my CA?

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
OS version: Linux x64 5.15.23-76051523-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|31.24GB (10.99GB free)|
|Process Argv|--unity-launch --crash-reporter-id d47ba435-3be3-4834-8f45-d41f283cb19c|
|Screen Reader|no|
|VM|24%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
commit-message-editor|ada|0.19.7
format-json|Cle|1.0.2
docs-markdown|doc|0.2.100
gitlens|eam|12.0.0
prettier-vscode|esb|9.3.0
copilot|Git|1.7.5185
gitkraken-authentication|git|1.0.3
todo-tree|Gru|0.0.215
prettify-json|moh|0.0.3
vscode-docker|ms-|1.20.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.4
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.74.0
remote-ssh-edit|ms-|0.74.0
remote-wsl|ms-|0.64.2
vsliveshare|ms-|1.0.5418
autodocstring|njp|0.6.1
code-spell-checker|str|2.1.7
visualize-control-flow|tea|0.2.0
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc009:30440023
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343
vsnot107cf:30443615

```

</details>

**Comment by deepak1556** [comment]
Yes VSCode uses the same certificate store as chromium, please try the steps at https://chromium.googlesource.com/chromium/src/+/master/docs/linux/cert_management.md#linux-cert-management.
