### ISSUE TITLE
`f` removed from origin name in git log?

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#144205]
See how the origin is supposed to be `bwateratmsft` but somehow the tag command executed is against `bwateratms t`

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/8586769/156241583-f5ef7406-a65c-4446-907b-2c957b6fffa0.png">

**Comment by JacksonKearl** [comment]
this is the PR I'm on: https://github.com/microsoft/vscode-github-triage-actions/pull/44

**Comment by lszomoru** [comment]
_Adding @alexr00 as well as FYI_

@JacksonKearl, I see that the PR has been merged. Could the user create a new PR so that we can try to reproduce the issue again? Or if you have any steps that we can use to reproduce the problem please let us know. Thank you!

**Comment by JacksonKearl** [comment]
Try just setting ```
"githubPullRequests.queries": [
    {
      "label": "Created By bwateratmsft",
      "query": "author:bwateratmsft"
    }
  ],
```
in the vscode repo and check out any of his existing PR's then try to sync: 

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/8586769/156424888-72a3b193-3537-4d52-a072-7789973f02d3.png">
this time the `r` was removed. 

these are my git settings:
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/8586769/156425073-5f0eb8d2-91ec-4e21-8374-5bc798ef1463.png">

**Comment by lszomoru** [comment]
This is a regression that was introduced by https://github.com/microsoft/vscode/commit/6011bf7e7ad87a06908e9947fd5ccd948739f953. The regression surfaces when the local branch name does not match the remote branch name. The current plan is to revert that commit and include this in the recovery release.

**Comment by lszomoru** [comment]
Repro steps:
1. Create a new branch called `foo` and publish it
2. Checkout the remote branch using a different name - `git checkout -b foobar origin/foo`
3. Change a file, and try to sync the changes. This will fail with an error
    ```
    [2022-03-09T19:24:32.671Z] > git pull --tags ori in/foo [49ms]
    [2022-03-09T19:24:32.671Z] fatal: 'ori' does not appear to be a git repository
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
    ```

**Comment by lszomoru** [comment]
I have reverted the commit that has introduced the regression - https://github.com/microsoft/vscode/commit/fa5aa53695fa4b72c36fcb83133a4b6e62a1d63c.
This should be fixed in tomorrow's Insiders release. Will port the fix to the release branch.

**Comment by hediet** [comment]
Closing, as this has been fixed in the release branch.
