### ISSUE TITLE
My visual studio code shows a shiny number when editing. 

### ISSUE THREAD

**Issue by Skylar327016** [microsoft/vscode#144273]
Issue Type: <b>Bug</b>

The shiny number is in the top right of the editor.  And the format is like a shiny horizontal line with a number and an "x" character in the below. When I am editing, the number goes up and it would need some time to disappear.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (13.71GB free)|
|Process Argv|-psn_0_7005870 --crash-reporter-id 6ba4b413-5799-4374-8376-506eb666711e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
php-intellisense|fel|2.3.14
code-runner|for|0.11.7
vscode-power-mode|hoo|3.0.1
better-cpp-syntax|jef|1.15.13
unity-code-snippets|kle|1.3.0
csharp|ms-|1.24.1
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.74.0
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
fabric8-analytics|red|0.3.5
java|red|1.3.0
vscode-commons|red|0.0.6
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.1
vscode-maven|vsc|0.35.1
php-debug|xde|1.24.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc008:30440022
pythonvspyt640:30442238
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343
vscaat:30438848
vsnot107:30443614

```

</details>

**Comment by Skylar327016** [comment]
<img width="1440" alt="Screenshot 2022-03-02 at 19 35 49" src="https://user-images.githubusercontent.com/60724206/156440715-2efaf694-4b39-4705-ad1b-c91b37637960.png">

**Comment by misolori** [comment]
@Skylar327016 that is coming from an extension, Power Mode https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-power-mode

<img width="707" alt="CleanShot 2022-03-02 at 12 07 03@2x" src="https://user-images.githubusercontent.com/35271042/156441164-369dd4ef-7933-4dfe-8900-1570b9dc73ca.png">


You can disable/uninstall that extension.
