### ISSUE TITLE
Hit count expression isn't validated

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#14423]
Testing #13211

The hit count expression isn't validated and you can enter arbitrary text. Could at least to some lexical validation (digits and relational operators)

![image](https://cloud.githubusercontent.com/assets/172399/19686538/d7502d98-9ac1-11e6-93e1-8fff19ae2ac3.png)

**Comment by isidorn** [comment]
This logic is coming from the debug adapter, thus forwarding to @weinand to consider adding this

**Comment by weinand** [comment]
dup of https://github.com/Microsoft/vscode/issues/14364
