### ISSUE TITLE
`editor.action.smartSelect.expand` doesn't work if only basic language features are available

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#144297]
Version: 1.65.0-insider (Universal)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T03:14:48.052Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0

Steps to Reproduce:

1. Disable the built-in JSON language feature extension.
2. Open a JSON file.
3. Enter `Ctrl + Shift + Right` (`editor.action.smartSelect.expand`)
4. Selection doesn't expand.
5. In VS Code 1.64.2, it expands well. `editor.action.smartSelect.expand` should work even if only  basic language features are available.

**Comment by aeschli** [comment]
I checked in the code and I think you are right, there's ni default extend selection provider.
https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/smartSelect/browser/smartSelect.ts#L82

**Comment by hediet** [comment]
Did this use to work?

**Comment by jrieken** [comment]
Not really - there is some level of default support but it is mostly about words and lines. Maybe a good candidate for the bracket AST

**Comment by PrzemyslawSarnacki** [comment]
I can confirm that smartSelect grow and shrink are also no longer working

**Comment by jrieken** [comment]
There is actually a regression from https://github.com/microsoft/vscode/commit/05a6debf1838c3b54ac36570392d0e8ac0fa739b which causes us to return (too) early here: 

https://github.com/microsoft/vscode/blob/6136c815bc6e7b99ec2dac56dccb3869574d2dd8/src/vs/editor/contrib/smartSelect/browser/smartSelect.ts#L82

**Comment by jrieken** [comment]
To verify:

* have a c-file (see below), have no c extensions
* put the cursor into the `"Hello world"` string
* select F1 > Expand Selection repeatedly and ensure the selection grows along word, brackets, line brackets etc


```c
#include <stdio.h>
int main()
{
	printf("Hello world.");
	return 0;	
}
```
