### ISSUE TITLE
Replace In Files : Regex Lookaround breaks Capture Group Substitution

### ISSUE THREAD

**Issue by maxsu** [microsoft/vscode#144231]
Using lookaround breaks capture group substitution in Replace In Files, but not in the ordinary Replace widget.

- All extensions are disabled
- VS Code Version: 1.65.0-**insider**
- OS Version: Windows_NT x64 10.0.22000

### Steps to Reproduce:

1.  Create file with contents
  >Item
  >Some Stuff
  >Some more Stuff! 😵
  >End
  > 
  > Item
  > Not as much stuff 😌
  > End

2. Open Replace in Files (<kbd>CMD+SHIFT+H</kbd>)
3. Enable regex mode (<kbd>ALT+R</kbd>)
4. Use search string `(?<=Item\n)(.*)\n(?!End)(.*)`
5. Use replace string `$1, $2`
6. Replace All (<kbd>CMD+ALT+Enter</kbd>)

### Result:
  >Item
  >$1, $2
  >End
  > 
  > Item
  > Not as much stuff 😌
  > End

### Expected result:
  >Item
  >Some Stuff, Some more Stuff! 😵
  >End
  > 
  > Item
  > Not as much stuff 😌
  > End
  

### Notes:
- Any lookahead or lookbehind causes similar results 
  - e.g. replacing `(.*)(?=\nEnd)`  with `$1` replaces text with a verbatim `$1` instead of capture group contents 
- We get the expected result if we use the  the Replace Widget (<kbd>CMD+H</kbd>).

**Comment by gjsjohnmurray** [comment]
Cause of the difference is explained in https://github.com/microsoft/vscode/issues/143453#issuecomment-1048139108

**Comment by gjsjohnmurray** [comment]
Further details in https://github.com/microsoft/vscode/wiki/Search-Issues#notes-on-regular-expression-support

**Comment by roblourens** [comment]
Yeah, this is a hole in how we compute the replace string, since we currently recompute it outside of rg, but only have the match string available, not the string outside of the match range that matched the lookaround. 

https://github.com/microsoft/vscode/issues/128134#issuecomment-880953562

**Comment by maxsu** [comment]
@roblourens Ah, I see. This is effectively a duplicate of #128134, since solving that would solve this issue too. I'll make a remark over there, thanks!
