### ISSUE TITLE
Repl indicator is shifted a few pixels down

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#14429]
#14171

In Windows:

![image](https://cloud.githubusercontent.com/assets/22350/19686995/fedd521c-9ac3-11e6-91d1-3b9309d25f67.png)

**Comment by Tyriar** [comment]
Something funny is still going on.

Initial state:

![image](https://cloud.githubusercontent.com/assets/2193314/19781010/4d21df50-9c3c-11e6-9ce0-8c13245d1ac7.png)

After window width is reduced:

![image](https://cloud.githubusercontent.com/assets/2193314/19780993/3c7ffcae-9c3c-11e6-952f-8211a2720165.png)

**Comment by isidorn** [comment]
It is not that it is not vertically centered but the we somehow layout the editor wrongly so more than one line is visible. Once an expression is entered it gets into a nice one line state again

**Comment by isidorn** [comment]
ACtually Joao caputres this issue quite well here so let's keep that one open
https://github.com/Microsoft/vscode/issues/14649
