### ISSUE TITLE
Window frozen when file unsaved.

### ISSUE THREAD

**Issue by tramchamploo** [microsoft/vscode#144243]
Issue Type: <b>Bug</b>

I have lots of unsaved work now, any help is appreciated.
Freezing happens when I drag my splitted window of jupyter to a new window, the target window says unsupported then my origin window freezes. Mouse and keyboard is not responding but the editor focus seems to be there.

How can I save now? I checked git diff and AppData\Roaming\Code\Backups\. There isn't any my newest changes.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (0.62GB free)|
|Process Argv|--crash-reporter-id 67428a7b-0ff7-4804-b84b-377f52454488|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz (4 x 2599)|
|Memory (System)|6.12GB (3.18GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.64.7
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.4
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-wsl|ms-|0.64.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc008:30440022
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343
vsnot107cf:30443615

```

</details>

**Comment by tramchamploo** [comment]
I save my file turning on autosave with a new window. But the bug is there, can't post a gif as I restarted.
Here is the thing, I have two monitors and a VSCode window on each of them. I split the notebook tab on my first screen. And I drag the new tab to the window on the second screen. The second screen says unsupported operation or something and the first window freeze.

**Comment by bpasero** [comment]
Are you running as admin?

**Comment by tramchamploo** [comment]
No Im not

**Comment by bpasero** [comment]
Maybe you could record somehow a video by phone to get an understanding of how the interaction is like.

**Comment by tramchamploo** [comment]
Cannot reproduce anymore.
