### ISSUE TITLE
I can't see my recent projects when i click ctrl+r(shell command) . It is empty

### ISSUE THREAD

**Issue by rohitvenerate** [microsoft/vscode#144299]
Issue Type: <b>Bug</b>

I can't see my recent projects when i click ctrl+r(shell command) . It is empty

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (7.24GB free)|
|Process Argv|--crash-reporter-id 01295026-5b46-4164-92cd-cabffece305c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
intellij-theme|arz|1.10.0
shell|bbe|0.3.0
vscode-tailwindcss|bra|0.7.7
emmet-jss|car|1.0.0
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.2
vuerd-vscode|din|0.9.15
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.4.3
vscode-go-syntax|dun|0.0.18
vscode-html-css|ecm|1.11.0
vscode-great-icons|emm|2.1.82
prettier-vscode|esb|9.3.0
lana|Fin|1.4.1
auto-rename-tag|for|0.1.10
code-runner|for|0.11.7
go|gol|0.31.1
go-nightly|gol|2022.3.214
rest-client|hum|0.24.6
vscode-env|Iro|0.1.0
rainbow-csv|mec|2.0.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.20
vscode-docker|ms-|1.20.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.4
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.2
remote-wsl|ms-|0.64.2
cpptools|ms-|1.8.4
vsliveshare|ms-|1.0.5418
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.13.0
sqltools|mtx|0.23.0
material-icon-theme|PKi|4.13.0
prisma|Pri|3.10.0
vscode-xml|red|0.19.1
LiveServer|rit|5.7.4
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode|sal|54.2.0
salesforcedx-vscode-apex|sal|54.2.0
salesforcedx-vscode-apex-debugger|sal|54.2.0
salesforcedx-vscode-apex-replay-debugger|sal|54.2.0
salesforcedx-vscode-core|sal|54.2.0
salesforcedx-vscode-lightning|sal|54.2.0
salesforcedx-vscode-lwc|sal|54.2.0
salesforcedx-vscode-soql|sal|54.2.0
salesforcedx-vscode-visualforce|sal|54.2.0
js-jsx-snippets|sky|11.0.0
sfdx-package-xml-generator|Vig|2.0.8
vscode-icons|vsc|11.10.0
vscode-go-autotest|win|1.6.0
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0
json|Zai|2.0.2
material-theme|zhu|3.13.20

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc008:30440022
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvid2:30438800
helix:30440343
vsnot107:30443614

```

</details>

**Comment by roblourens** [comment]
Can you give some more details? What do you mean (shell command)?
