### ISSUE TITLE
Support clearing existing commands when re-running or navigating to recent directory

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#144279]
Repro:

1. Type `abc` in a terminal
2. `Terminal: Run Recent Command` and select something

![image](https://user-images.githubusercontent.com/2193314/156445027-fddc57a8-ff2e-4a92-b333-8018d602f2a6.png)

We should hit ctrl+c beforehand (`0x03`) which should work properly on all shells

**Comment by meganrogge** [comment]
We should also do this when `Re-run command` is clicked in the decoration's context menu

**Comment by Tyriar** [comment]
I attempted this in #144289 but it was more complicated than I originally anticipated. Moving to backlog.
