### ISSUE TITLE
Re-running cd commands should handle relative path

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#144254]
Cool feature maybe?

<img width="178" alt="image" src="https://user-images.githubusercontent.com/6561887/156403063-44645606-8b1c-4756-888c-e3a6625f02ee.png">

In the above image, I navigate to `~\Source\github\microsoft` one directory at a time. It would be cool if re-running any one of the cd commands would work no matter my current working directory. It seems the path is already remembered in the link decorator.

**Comment by Tyriar** [comment]
Right now it acts as you would expect from ctrl+r though. If you run a recent command and hit `cd ..`, you generally wouldn't expect that to be resolved relative to the last cwd in which you ran that command from.

**Comment by sbatten** [comment]
yea `cd ..` is special in that it can be run anywhere, but paths that were relative and no longer resolve in the cwd don't make sense to re-run without moving to the original working. i definitely view this as a cool-to-have feature, not something I expected to work.

**Comment by Tyriar** [comment]
Yes it would be cool but it would mean how only those specific directories is handled specially to other `cd` calls and every other recent command. I think we should keep this as is and if you want to go to a different dir you should use the go to recent directory command instead which uses an absolute dir.
