### ISSUE TITLE
[question] [highlight bug] Missing scopes for default node libraries. Is this supported?

### ISSUE THREAD

**Issue by whaaaley** [microsoft/vscode#144218]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

Builtins in node have no scopes applied

![image](https://user-images.githubusercontent.com/7419947/156266858-0a6ce4f3-2e30-47f5-9835-f50ab74b7403.png)

The expected token would be `variable.defaultLibrary` similar to `console`, `window` and `JSON`

![image](https://user-images.githubusercontent.com/7419947/156266943-1ad9e2e7-8b62-4ec7-a0e5-989b6dac56fe.png)

Should this be supported by the JS/TS language modes? Is there a proposed workaround for adding these scopes on a per-theme basis? I can't find any information on this if there is.

Also is this the best place to report this or is there a more appropriate repository to report highlighting issues? Thanks.

**Comment by mjbvz** [comment]
We removed some of the built-in function highlighting from the text mate grammars as they are a better fit for semantic highlighting 

Please file a feature request against typescript if you want to specifically colorize nodejs built-ins: https://github.com/microsoft/TypeScript

**Comment by mjbvz** [comment]
Here's the code that does this: https://github.com/microsoft/vscode/blob/76a647c33c04d0b9db566dec0757f953ea838d3c/extensions/typescript-basics/build/update-grammars.js#L20

**Comment by whaaaley** [comment]
I agree that semantic highlighting should be the end goal, but I would suggest not removing scopes before semantic highlighting actually provides an alternative scope.
