### ISSUE TITLE
Text Line Limit can not exceed 1000  / truncates after 1000

### ISSUE THREAD

**Issue by JJPak** [microsoft/vscode#144208]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I work with the Jupyter-Extension and I need to print over 1000 lines. Yet, even if I increase the "notebook.output.textLineLimit" to values >1000, the output is still being truncated to 1000 lines.

Is there some other way to incrase the amount of lines printed in the output?

For example try this:

print(list(range(100000)))

Then I get the following output after 1000 lines -> "Output exceeds the size limit. Open the full output data in a text editor"

### VS Code Version

1.64.2

### Jupyter Extension Version

v2022.1.1301854968

### Jupyter logs

```shell
Output exceeds the size limit. Open the full output data in a text editor.
```

### Coding Language and Runtime Version

Python v.3.8.2

### Running Jupyter locally or remotely?

Local

**Comment by rebornix** [comment]
The setting actually works but what's missing is we didn't re-render the output when the setting changed, closing the file and then reopen the file should fix it.

Snippet I tried 

```
for i in range(1000):
    print(i)
```

**Comment by JJPak** [comment]
@rebornix 
I tried that before but it didn't help then. However, after the update to version 1.65 it worked, even without reopening the file! Thank you for your time and help!
