### ISSUE TITLE
negative filters to exclude problems in the problem pane seems not to have any effect

### ISSUE THREAD

**Issue by andrewufrank** [microsoft/vscode#144262]
Does this issue occur when all extensions are disabled?: Yes/No yes

- VS Code Version:
- OS Version: Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:29.527Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.10.0-11-amd64

Steps to Reproduce:

1. run a compiler (e.g. haskell) which produces messages resulting in problems in the problem pane. 
some of these are produced by the vscode integration, e.g. issues originating with a spell checker. 
try to filter these out in order not to clobber the display. 
(erros produced by the haskell compiler, for example, can effectively be suppressed - not an issue here)

2. enter a filter expression e.g. `!"spelling"` has no effect. 

I have seen a discussion on essentially this issue. it came to a conclusion with a fix which was merged. It seems not to have the desired effect.

It would be highly desirable, to allow filtering by components/extension and a combination of negative filter for text, logically combinable at least with `or` 
4.

**Comment by gjsjohnmurray** [comment]
Is the word `spelling` enclosed in doublequotes in the entries in your Problems pane? If not, try `!spelling` as the filter text.
