### ISSUE TITLE
incorrect SVG warning when editing VS Code extension package.json

### ISSUE THREAD

**Issue by devhawk** [microsoft/vscode#144258]
Issue Type: <b>Bug</b>

I'm setting the url property of an object in the badges array in my extension's package.json file. WHen I set it to a badge from a trusted badge provider (https://github.com/neo-project/neo-debugger/actions/workflows/build-vscode.yml/badge.svg) I get a "SVGs are not a valid image source" warning.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (19.76GB free)|
|Process Argv|--crash-reporter-id 19e61f47-cae7-4f91-ae80-60edd1b7067f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.5.0
es6-string-css|bas|0.1.0
markdown-preview-github-styles|bie|1.0.1
better-toml|bun|0.3.2
vscode-path-tools|cg-|0.0.4
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.0
vscode-npm-script|eg2|0.3.24
dotnet-test-explorer|for|0.7.7
codespaces|Git|1.5.4
remotehub|Git|0.24.0
vscode-pull-request-github|Git|0.36.2
gitkraken-authentication|git|1.0.3
vscode-nuget-package-manager|jmr|1.1.6
vscode-peacock|joh|4.0.0
csharpsortusings|jon|0.0.3
vscode-typescript-to-json-schema|mar|0.0.16
rust-analyzer|mat|0.2.956
git-graph|mhu|1.30.0
azure-pipelines|ms-|1.195.0
vscode-azureappservice|ms-|0.23.1
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.13.0
vscode-cosmosdb|ms-|0.18.1
blazorwasm-companion|ms-|1.1.0
csharp|ms-|1.24.1
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.4
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.74.0
remote-ssh-edit|ms-|0.74.0
remote-wsl|ms-|0.64.2
azure-account|ms-|0.10.0
azurecli|ms-|0.5.0
cpptools|ms-|1.8.4
hexeditor|ms-|1.9.5
vscode-node-azure-pack|ms-|0.2.1
vscode-versionlens|pfl|1.0.9
vscode-gitignore-generator|pio|1.0.3
crates|ser|0.5.10
code-spell-checker|str|2.1.7
rest-book|tan|6.0.1
es6-string-html|Tob|2.12.0
errorlens|use|3.4.1
vscode-lldb|vad|1.6.10
vscode-icons|vsc|11.10.0
literally-html|web|0.1.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
vscop841:30438915
dsvsc009:30440023
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343
vsnot107cf:30443615

```

</details>

**Comment by chrmarti** [comment]
@joaomoreno The regex seems to miss the `actions` segment: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge.

**Comment by joaomoreno** [comment]
@chrmarti I am confused, didn't you implement this? https://github.com/microsoft/vscode/commit/997bcf9001a30d25876638df35bde934ac2ec0aa

**Comment by joaomoreno** [comment]
Oh I see: https://github.com/microsoft/vscode/commit/cb29362cc79fa0c64d29857aa3becd787176203b
