### ISSUE TITLE
Hit count input box could provide hint about expression syntax

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#14421]
Testing #13211

It would be nice to show the expression syntax for hit counts in the input box

![image](https://cloud.githubusercontent.com/assets/172399/19686370/128196fa-9ac1-11e6-8da3-f6dcc7ef8505.png)

**Comment by isidorn** [comment]
This logic should come from the adapter since the UI is not aware of that, thus assigning first to @weinand to consider adding this to the protocol

**Comment by weinand** [comment]
dup of https://github.com/Microsoft/vscode/issues/14363
