### ISSUE TITLE
Organize imports auto isn't working

### ISSUE THREAD

**Issue by GIT-MDW** [microsoft/vscode#144203]

**Comment by GIT-MDW** [comment]
![image](https://user-images.githubusercontent.com/94377644/156914765-44987f91-bb78-47c6-a7e6-759baa57183b.png)

**Comment by GIT-MDW** [comment]
does not work on click and with shortcut

**Comment by mjbvz** [comment]
Please follow the issue reporting guide. Fill in the issue template with your VS Code version and also share steps to reproduce the problem
