### ISSUE TITLE
ellipses appears/disappears every time codefile is edited

### ISSUE THREAD

**Issue by royBrocken** [microsoft/vscode#144248]
Issue Type: <b>Bug</b>

create typescript file
focus cursor in open file
type anything
result:  
line is inserted momentarily at top of file with '...'
all file contents shift down one line
line disappears
all file contents shift up one line

- This becomes tedious and distracting, causing my eye to chase the cursor and the area I'm actively editing
Thanks

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
OS version: Linux x64 5.13.0-30-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|62.46GB (36.31GB free)|
|Process Argv|/home/subatai/Documents/code/clubforce/app --crash-reporter-id e0ed23cd-195f-4cf0-a266-26d0b87e72fc|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.15.1
laravel-extra-intellisense|ami|0.6.2
ng-template|Ang|13.2.4
docs-view|bie|0.0.9
vscode-intelephense-client|bme|1.8.2
npm-intellisense|chr|1.4.1
vscode-postgres|cko|1.4.0
vscode-database-client2|cwe|4.7.3
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
gitlens|eam|12.0.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.3.0
vscode-jest-runner|fir|0.4.47
gitkraken-authentication|git|1.0.3
gc-excelviewer|Gra|4.0.50
todo-tree|Gru|0.0.215
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.24.6
open-in-browser|igo|1.0.2
angular-essentials|joh|12.0.0
vscode-peacock|joh|4.0.0
eml|lei|0.4.0
template-string-converter|meg|0.6.0
vscode-docker|ms-|1.20.0
csharp|ms-|1.24.1
vscode-dotnet-runtime|ms-|1.5.0
remote-containers|ms-|0.217.4
test-adapter-converter|ms-|0.1.5
debugger-for-chrome|msj|4.13.0
angular-console|nrw|17.14.1
autolaunch|phi|2.0.9
material-icon-theme|PKi|4.13.0
fabric8-analytics|red|0.3.5
vscode-commons|red|0.0.6
vscode-xml|red|0.19.1
vscode-yaml|red|1.4.0
code-settings-sync|Sha|3.4.3
vscode-scss-formatter|sib|2.3.3
sass-indented|syl|1.8.19
ayu|tea|1.0.5
lorem-ipsum|Tyr|1.3.1
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.24.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc008:30440022
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343
vsnot107cf:30443615

```

</details>

**Comment by philBrown** [comment]
Same problem as reported here on StackOverflow ~ [3 dots above first line while I write code in react in Visual Studio Code, it moves the code and its very annoying](https://stackoverflow.com/questions/71317219/3-dots-above-first-line-while-i-write-code-in-react-in-visual-studio-code-it-mo)

**Comment by philBrown** [comment]
Restarting with extensions disabled prevents it so most likely not a core issue

**Comment by cplpearce** [comment]
Encountering the same issue:
![image](https://user-images.githubusercontent.com/11462961/156465755-e7f43f6b-8ccc-456c-a755-dc9269f4041f.png)

I believe this is related to GitLens, try disabling it and see if it helps with your issue.

**Comment by philBrown** [comment]
Already reported here ~ https://github.com/gitkraken/vscode-gitlens/issues/1742

**Comment by gonrivas** [comment]
I this issue fixed???

**Comment by IllusionMH** [comment]
/causedByExtension

As mentioned above - issue is caused by extension. Thanks for the link to gitlens issue.

Everybody who has this issue should wait for extension update or switch to preview version of extension.
