### ISSUE TITLE
zsh doesn't activate as expected when inheritEnv is set to false

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#144272]
Issue Type: <b>Bug</b>

```
/Users/penlv/.zshrc:100: command not found: yarn
/Users/penlv/.zshrc:104: command not found: brew
/Users/penlv/.zshrc:source:104: no such file or directory: /nvm.sh
Shell integration activated
```

There is no issue when shell integration is disabled

VS Code version: Code - Insiders 1.65.0-insider (Universal) (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T03:14:48.052Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|32.00GB (0.15GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --enable-proposed-api donjayamanne.jupyterpowertools --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api rchiodo.jupyter-tools --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Tyriar** [comment]
@rebornix can you provide you settings.json (only terminal parts matter), your .zshrc file, output of `which yarn` and where you set your $PATH to include yarn/brew?

**Comment by rebornix** [comment]
Sure, my terminal settings

```
    "terminal.integrated.rendererType": "dom",
    "terminal.integrated.fontFamily": "FiraCode Nerd Font, Jetbrains Mono",
    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.environmentChangesIndicator": "on",
    "terminal.integrated.inheritEnv": false,
    "terminal.integrated.commandsToSkipShell": [
        "workbench.action.toggleSidebarVisibility",
        "language-julia.interrupt"
    ],
    "terminal.integrated.windowsEnableConpty": false,
    "terminal.integrated.showExitAlert": false,
    "terminal.integrated.localEchoLatencyThreshold": 0,
    "terminal.integrated.defaultProfile.windows": "PowerShell",
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "source": "Git Bash",
            "icon": "terminal-linux"
        },
        "MY Ubuntu": {
            "source": "Ubuntu-20.04 (WSL)",
            "icon": "terminal-linux"
        }
    },
    "terminal.integrated.scrollback": 10000,
    "terminal.integrated.confirmOnKill": "never",
    "terminal.integrated.gpuAcceleration": "on",
```



`.zshrc` file

```
export ZSH="/Users/penlv/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh
export PATH="$(yarn global bin):$PATH"
. ~/.z_z/z.sh

export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
```

and yarn is globally installed

```
penlv % which yarn
/usr/local/bin/yarn
```

**Comment by rebornix** [comment]
It's already included before the line where it's updated (this line was not added manually but might be part of installation of some packages)
`/Users/penlv/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/penlv/.dotnet/tools`

**Comment by Tyriar** [comment]
Oh then `$(yarn global bin)` shouldn't fail then? Is that the line it fails on?

**Comment by rebornix** [comment]
Resetting `terminal.integrated.inheritEnv` fixed it.

**Comment by meganrogge** [comment]
That's because `useShellEnvironment` is set to false when `inheritEnv` is false

https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/workbench/contrib/terminal/browser/terminalProfileResolverService.ts#L150

**Comment by meganrogge** [comment]
so it gets the default environment 

https://github.com/microsoft/vscode/blob/9d8ad9289f73f916f3074318d2228c580ec26d44/src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts#L375-L381

**Comment by rebornix** [comment]
After reverting the setting, it works for a short period but today it stopped working again. Even worse, running build tasks failed as it can't find `yarn`.

**Comment by meganrogge** [comment]
Shell integration isn't enabled for tasks, so I'm surprised to hear that.

**Comment by meganrogge** [comment]
I can't reproduce this. @rebornix can you still?

**Comment by rebornix** [comment]
Just reproduced it after updating to latest Insiders, the first error prompt I got is 

```
notificationsAlerts.ts:42 Unable to resolve your shell environment in a reasonable time. Please review your shell configuration.
onDidChangeNotification @ notificationsAlerts.ts:42
```

and then `yarn` can't be found in tasks (only).

**Comment by meganrogge** [comment]
Yep I'm able to repro this when inheritEnv: false and I reload the window/ the terminals are reconnected. Even creating a new terminal with inheritEnv: false after a reload doesn't work and I see `yarn: command not found`

**Comment by meganrogge** [comment]
This makes sense for the reason I mentioned above. Is this as designed or should the default env contain our shell integration injection too?

**Comment by meganrogge** [comment]
I am not seeing that error anymore. 

To be clear, we don't expect shell integration to work when `inheritEnv` is false. 

As for the

**Comment by meganrogge** [comment]
@rebornix please attach a gif if you can reproduce it
![Recording 2022-04-20 at 14 40 10](https://user-images.githubusercontent.com/29464607/164327464-02e6896a-e9d4-4aaf-9ac1-23ca078f15d7.gif)
