### ISSUE TITLE
Failing Markdown tests in build

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#144206]
Build that introduce this is IMO 

https://monacotools.visualstudio.com/Monaco/_traceability/runview/changes?currentRunId=158523

With the problematic commits:

https://github.com/microsoft/vscode/commit/6d04ed55c7d5fde915210f8443da3d759e4add49
https://github.com/microsoft/vscode/commit/13bde28fe8d028b40f8b0c31079130ffe38c0180

The build got fixed here:

https://monacotools.visualstudio.com/Monaco/_build/results?buildId=158529&view=results

But from that on the markdown tests failed.

**Comment by dbaeumer** [comment]
Made tests green again via https://github.com/microsoft/vscode/commit/30e1c0cfdaa3d1b3e7d4a0141bb8b0d3bcb51887

Not sure if that is the correct fix though.

**Comment by jrieken** [comment]
@dbaeumer Thanks for jumping on this. There is definitely a change in my commit that wasn't intended - the escape regex should have been unchanged!
