### ISSUE TITLE
Vscode vim in ssh shows extra characters from the terminal

### ISSUE THREAD

**Issue by YiwenZhu77** [microsoft/vscode#144249]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.64.2
- OS Version: Mac OS Monterey V12.1

Steps to Reproduce:

1. Connected to a ssh sever in VScode using the ssh extension
2. Use vim to open a file

**Comment by YiwenZhu77** [comment]
Hi everyone,

When I use VScode to access ssh and use vim to open a file, the file will show some unexpected characters that are coming from the terminal. As shown in the figure, fig 1 is the what the file should be looking like, fig 2 is the what the file looks like when opened with vim, it can be seen that some characters are prepending the each line of the file, and I am sure these characters are what's been printed in the terminal before I used the vim to open the file. (For example, there's no problems if before using vim to open a file there's no content printed in terminal)

Fig1:
![image](https://user-images.githubusercontent.com/67499424/156391315-097b4256-009e-45fa-b2e3-a80cfe5c6335.png)

Fig2:
![image](https://user-images.githubusercontent.com/67499424/156391382-196af9c3-487d-4b77-875b-3be962872c3d.png)

**Comment by andrewnicolalde** [comment]
I'm noticing this as well on both of my machines, both while actually using vim on a remote host via the SSH development extension and while using a shell on the same machine, i.e. not connecting to a remote host using the SSH development extension.

# Version & Other Info

- `Remote - SSH` version installed on Linux: `v0.76.1`
- Version of zsh installed on Linux (same host that VSCode runs on): `zsh 5.8.1 (x86_64-redhat-linux-gnu)`
- Version of VSCode installed on Linux:
```
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:29.527Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.16.9-200.fc35.x86_64
```
- `Remote - SSH` version installed on macOS: `v0.74.0` 
- Version of zsh installed on Linux (same host that VSCode runs on): `zsh 5.8 (x86_64-ubuntu-linux-gnu)`
- Version of VSCode Installed on local macOS:
```
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```
- In both cases, the `$TERM` is set to `xterm-256color`.
- Re-initializing the terminal with `reset` doesn't seem to resolve the issue.

I've observed this on every machine I've tried (2 so far):

- Example on Linux (shell running on same machine as VSCode itself, i.e. not connecting through the Remote SSH extension)
![Example on Linux (shell running on same machine as VSCode itself, i.e. not connecting through the Remote SSH extension)](https://user-images.githubusercontent.com/21282811/156464680-67ec5a78-fa2f-42a3-88a4-5bcbb47799e7.png)

- Example on macOS connecting to an Ubuntu 20.04 host through the Remote SSH extension
![image](https://user-images.githubusercontent.com/21282811/156466588-19cc5e11-6ad7-4d04-a388-af3a5ce055cf.png)

**Comment by YiwenZhu77** [comment]
> 

Thanks for your reply, I guess then this is something about using vim on a ssh terminal, independent of machine.

**Comment by olix0r** [comment]
I've noticed this recently as well. Using `Remote - SSH` and `Remote - Containers` to work inside of a devcontainer.

* Code version (on macOS)
```
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0
```
* Remote extension versions:
```
ms-vscode-remote.remote-containers@0.224.2
ms-vscode-remote.remote-ssh@0.76.1
ms-vscode-remote.remote-ssh-edit@0.76.1
ms-vscode-remote.vscode-remote-extensionpack@0.21.0
```

![image](https://user-images.githubusercontent.com/240738/157114715-8bb60641-5ceb-445b-ace0-0ac258c1d733.png)

Hitting Ctrl+L clears these characters.
![image](https://user-images.githubusercontent.com/240738/157114751-2c6b6459-6b1d-452c-a01a-fab9f85330fe.png)

**Comment by ewqqx** [comment]
I confirm. Just retyped "add" word on a screenshot and extra characters appeared.

> Version: 1.70.2 (Universal)
> Commit: e4503b30fc78200f846c62cf8091b76ff5547662
> Date: 2022-08-16T05:36:37.829Z (1 wk ago)
> Electron: 18.3.5
> Chromium: 100.0.4896.160
> Node.js: 16.13.2
> V8: 10.0.139.17-electron.0
> OS: Darwin arm64 21.6.0

<img width="464" alt="Screenshot 2022-08-30 at 02 12 41" src="https://user-images.githubusercontent.com/35928525/187308491-2bda7ed2-6a18-4a39-b535-71accf745a06.png">
