### ISSUE TITLE
Node debugger breakpoints not bound

### ISSUE THREAD

**Issue by leqwasd** [microsoft/vscode#144209]
[

Some time ago, I submitted an issue: https://github.com/microsoft/vscode/issues/134482 Got no real answer, but the problem didn't go away. I just found some ways to go around it. I think I found the reason - why it was not working. You could read more info for context there.

Steps to Reproduce:

1. clone this: https://github.com/leqwasd/node-attach-issue/tree/master and https://github.com/leqwasd/node-attach-issue/tree/broken and follow what's in the README.md

The only change in the branches is - the working one has `"name": "attach-issue"` in package.json, the broken one it has `"name": "@my/attach-issue"`

I attached a screenshot from https://microsoft.github.io/vscode-pwa-analyzer/index.html to show the difference. Bottom one is working, top one is broken.
![image](https://user-images.githubusercontent.com/6339540/156250637-d5a8dc71-4d3e-4b99-825f-a9c376acb886.png)

**Comment by connor4312** [comment]
This now appears to work on the "broken" branch, probably with https://github.com/microsoft/vscode-js-debug/commit/ed4b51bf0e2dd21c53bda124c0897165773b51f0
