### ISSUE TITLE
allow rearranging of "source control" sections

### ISSUE THREAD

**Issue by enatividad** [microsoft/vscode#144241]
this is for VSCode version 1.64.2

the current layout for source control is like this: Staged Changes section at the top (IF there are staged git changes) and Changes section at the bottom (EVEN IF there are no untracked git changes)
<img width="319" alt="Screen Shot 2022-03-02 at 5 34 30 PM" src="https://user-images.githubusercontent.com/9736478/156335902-2c23d65a-6606-422d-b9d5-f450acf35421.png">

I'd really appreciate it if I can move the Staged Changes section BELOW the (Untracked) Changes section. if possible, also allow moving of the "Add Commit Message" text below the the Staged Changes section. here is a reference image from Atom Editor's git side panel:
<img width="372" alt="Screen Shot 2022-03-02 at 5 44 11 PM" src="https://user-images.githubusercontent.com/9736478/156336595-74dc4b2e-79a4-4bef-8597-7899a47b3ae6.png">

I personally find Atom's approach at git layout pretty convenient:
1. from the very top, view all untracked changes then cherrypick the changes to be staged.
2. in the middle, review all staged changes, to ensure their correctness
3. and finally at the very bottom, approve the changes by leaving a commit message.

if moving the sections around is not an acceptable change for whatever reason, can we at least make the Staged Changes section always visible and have a FIXED HEIGHT? because the other problem I have with it being the top section is that when I stage a change from the (Untracked) Changes section, the Staged Changes section grows in height which pushes the (Untracked) Changes section down. This makes it hard for me to click the next (Untracked) Change item I wanted to click: instead of my cursor being right above the next item, the cursor is instead right above the "Changes" section header.

before staging App.js :
<img width="301" alt="Screen Shot 2022-03-02 at 5 54 49 PM" src="https://user-images.githubusercontent.com/9736478/156339062-2b5b18d7-94fc-4125-9359-ee6ed7538c80.png">

after staging App.js, where cursor highlights section header instead of index.js :
<img width="299" alt="Screen Shot 2022-03-02 at 5 55 12 PM" src="https://user-images.githubusercontent.com/9736478/156339363-4b774dfa-5cec-4781-aeb5-750e2db56974.png">

thanks for taking this idea in consideration

**Comment by enatividad** [comment]
for reference, this is my current vscode layout:
<img width="1611" alt="Screen Shot 2022-03-02 at 6 01 54 PM" src="https://user-images.githubusercontent.com/9736478/156340299-3f270862-4887-4e38-a9d1-409009a17d5b.png">

and this was my Atom layout:
<img width="1612" alt="Screen Shot 2022-03-02 at 6 04 07 PM" src="https://user-images.githubusercontent.com/9736478/156340353-164889e0-6e6c-4455-82a5-00960544dc1d.png">

I switched to VSCode because Atom's eslint has been giving me problems (probably because Atom's electron version still uses Node 12, whereas VSCode uses Node 14).

**Comment by lszomoru** [comment]
//cc @misolori

**Comment by enatividad** [comment]
> @enatividad try setting `"git.alwaysShowStagedChangesResourceGroup": true`
> 
> Initially the Staged Changes group should be collapsed, with a count of zero:
> 
> ![image](https://user-images.githubusercontent.com/6726799/156351014-caa778a5-5a07-46a3-97e4-97c1cd1fd503.png)
> 
> Then as you stage each change the count will increase but the group remains collapsed, so the position of remaining unstaged changes doesn't get affected:
> 
> ![image](https://user-images.githubusercontent.com/6726799/156351184-4cb11469-e385-4a70-a141-18e232f76912.png)

thank you very much, this will definitely help for now

**Comment by misolori** [comment]
Atom is a "top down" approach where you progressively move down visual hierarchy of modified > staged > commit and for VS Code we use a "bottom up" approach where it is reversed. So this would be "as-designed" and know that it can be challenging to transition from one tool to another.

**Comment by misolori** [comment]
And thanks to @gjsjohnmurray for the setting change, it looks like that has solved your issue so I'll go ahead and close this issue. Thanks again!
