### ISSUE TITLE
Failed to rename the folder and unsaved files loss

### ISSUE THREAD

**Issue by Sun-ZhenXing** [microsoft/vscode#144306]
Issue Type: <b>Bug</b>

at Windows 10, rename a folder while the folder is opened in other program, and it failed, the source code editors becoming blank...

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.31GB free)|
|Process Argv|--crash-reporter-id 59849a5d-da8a-4149-aa2f-73f6c3142797|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
better-cpp-syntax|jef|1.15.13
vscode-docker|ms-|1.20.0
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.4
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
vscode-paste-image|mus|1.0.4
vetur|oct|0.35.0
vscode-hexdump|sle|1.8.1
cmake|twx|0.0.17
vscode-arduino|vsc|0.4.11
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc008:30440022
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343
vscaat:30438848
vsnot107cf:30443615

```

</details>

**Comment by JacksonKearl** [comment]
\gifPlease

**Comment by Sun-ZhenXing** [comment]
When renaming contains ` / `, moving and other operations, the closed file operation will not be prompted and will not be saved.
![issue](https://user-images.githubusercontent.com/44517244/156688296-08e4118d-046d-4741-8764-bd1a23a1282e.gif)
