### ISSUE TITLE
Allow referencing environment variable with `${env:Name}` in `terminal.integrated.profiles.<platform>.env`

### ISSUE THREAD

**Issue by mon-jai** [microsoft/vscode#144316]
It would be useful if we can access environment variable in terminal profile settings, making it possible to append or prepend existing environment variables.

For example, to prepend something to path, we can:

```
{
  "terminal.integrated.profiles.windows": {
    "Powershell with MinGW": {
      "path": ["powershell"],
      "env": {
        "Path": "C:/msys64/mingw64/bin;${env:Path}"
      }
    }
  }
}
```

**Comment by psycho-neon** [comment]
wouldn't it be the same as using the setting
```
"terminal.integrated.env.windows": {
        "PATH": "${env:PATH};.....;"
    },
``` 
?

**Comment by mon-jai** [comment]
@psycho-neon Not the same. I am overwriting the Path variable in `Powershell with MinGW` profile only, but your configurations will overwrite it for all profiles.

**Comment by AnrDaemon** [comment]
Revert to 1.64.2, it works there.
