### ISSUE TITLE
Cell output font is no longer monospaced with VS Code update

### ISSUE THREAD

**Issue by alexdauenhauer** [microsoft/vscode#144350]
## Environment data

-   VS Code version: 1.65.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.2.1010630101
-   Python Extension version (available under the Extensions sidebar): v2022.2.1924087327
-   OS (Windows | Mac | Linux distro) and version: macOS 12.2.1
-   Python and/or Anaconda version: python 3.8.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pyenv
-   Jupyter server running: Local | Remote

## Expected behaviour

output font would be monospaced like it used to be

## Actual behaviour

![image](https://user-images.githubusercontent.com/11903445/156660226-cbd97eca-7a2a-4e16-9087-4ec69d0ca288.png)
the output font is not monospaced

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. execute a cell

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by agkphysics** [comment]
I believe this is fixed by https://github.com/microsoft/vscode/commit/8c73ac4811b6aabf59a7f02c08cd0df4997961fc which is in the latest VSCode Insiders build.

**Comment by dtrizna** [comment]
Same here, VSCode and Mac versions are the same.

**Comment by agkphysics** [comment]
I can confirm this is now fixed for me in VSCode 1.65.2.
