### ISSUE TITLE
error to access chrome

### ISSUE THREAD

**Issue by chethan07git** [microsoft/vscode#144325]
Issue Type: <b>Feature Request</b>

the following issue i am facing :

unable to launch browser: "spawn  ....\chrome.exe  EACCES"

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 6.3.9600
Restricted Mode: No

**Comment by weinand** [comment]
what are you trying to do?
please provide reproducible steps.
