### ISSUE TITLE
VS Code attach to shared process does not work with node2 type

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#14434]
Testing #14341 

- VSCode Version: Latest Insiders
- OS Version: Mac OS

Steps to Reproduce:

1. Set up VS Code development workspace
2. Launch vs code dev using ./scripts/code.sh
3. Configure the shared process launch to use `node2` type
4. Start the launch

>> It fails

**Comment by roblourens** [comment]
How do you configure the shared process launch to use node2? Is it an Electron renderer process? If so it won't work because of https://github.com/Microsoft/vscode-node-debug2/issues/4.

**Comment by sandy081** [comment]
@roblourens It is not a renderer process.. It is a node process. I just changed type from `node` to `node2`.

**Comment by roblourens** [comment]
In the launch config though? That's an attach config, so where does it get started in debug mode?

**Comment by roblourens** [comment]
Oh right node-debug can put running processes into debug mode, but node2 can't. https://github.com/Microsoft/vscode-node-debug2/issues/15 - so, can't support this unless you can get it to start up in debug mode somehow.

**Comment by weinand** [comment]
@roblourens I suspect that the 'code.sh' script configures VS Code to launch the shared process with '--debug'. This prevents node-debug2 from connecting successfully because it needs the '--inspect' flag. The https://github.com/nodejs/node/issues/8464 approach is not used here.

**Comment by roblourens** [comment]
Oh I see this - https://github.com/Microsoft/vscode/blob/master/src/vs/code/node/sharedProcess.ts#L35 but, there's no way to know ahead of time whether someone will want to attach with node or node2. Maybe at some point we want to switch it to `--inspect`. I don't know who uses it and cares one way or the other.

**Comment by weinand** [comment]
The shared process runs on Electron's node. Does this already support '--inspect'?
Is it possible to launch node with both '--debug' and '--inspect' and decide later what debugger protocol to use?

**Comment by roblourens** [comment]
I guess I'm not sure whether it will have the same problem as forking a renderer process with --inspect. It's not possible to use both though, you can only pick one.
