### ISSUE TITLE
variable `${env:xxx}` not work

### ISSUE THREAD

**Issue by 836454543** [microsoft/vscode#144355]
Issue Type: <b>Bug</b>

After I updated to version 1.65.0, my `task` on `tasks.json` is not work. Because I set `"terminal.integrated.automationProfile.windows":{"path":"${env:windir}\\System32\\cmd.exe"}` on my `settings.json`. The variable `${env:windir}` is not work on version 1.65.0, which makes my `task` unusable.

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.36GB free)|
|Process Argv|--crash-reporter-id c14d01f9-4268-4eb5-ae17-6ee32559e534|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc008:30440022
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvid1:30447480
helix:30440343
vsnot107:30443614

```

</details>

**Comment by mon-jai** [comment]
Maybe related: https://github.com/microsoft/vscode/issues/144316

I don't know if `${env:Name}` did work in terminal profiles in previous releases, or it was just not implemented in the first place.

**Comment by plollaton** [comment]
I'm having same problem.

Any alternative solution until bugfix became released?
