### ISSUE TITLE
Blank line shows as empty quotes when "terminal.integrated.shellIntegration.enabled": true

### ISSUE THREAD

**Issue by jibbers42** [microsoft/vscode#144378]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/797824/156744851-d56fd2ab-2763-45b9-a10f-017ee30e44ec.png)

I have bash set to enter a blank line between commands. I'm unsure being on WSL2 matters - this may reproduce directly on Ubuntu.
1. Open WSL2 Ubuntu terminal.
2. Edit .bashrc and append `PS1="\n$PS1"`
3. Open the folder in code: `code .`
4. Notice the `""` between commands.
5. Execute: `exec bash`
6. Notice for some reason there is now, correctly, an empty blank line with no quotes between commands.

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: Yes
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (11.61GB free)|
|Process Argv|--crash-reporter-id d51a3662-848c-4670-bb91-d4225ab4af73|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|15.50GB (8.31GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|15.50GB (8.31GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|15.50GB (8.31GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.4
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
remotehub|Git|0.24.0
gitkraken-authentication|git|1.0.3
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.64.2
trusty-rusty-snippets|pol|0.0.5
flutter-riverpod-snippets|rob|1.1.0
gitlens|eam|12.0.1
vscode-pull-request-github|Git|0.36.2
gitkraken-authentication|git|1.0.3
go|gol|0.31.1
volar|joh|0.32.1
dotnet-interactive-vscode|ms-|1.0.3103011
jupyter|ms-|2022.2.1020642448
vscode-xml|red|0.19.1
vscode-yaml|red|1.4.0
vscodeintellicode|Vis|1.2.17

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30440023
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvid1:30447480
helix:30440343
vsnot107cf:30443615

```

</details>

**Comment by meganrogge** [comment]
Using your exact `PS1="\n$PS1"`, I cannot reproduce the issue.
![Screen Shot 2022-03-04 at 1 28 19 PM](https://user-images.githubusercontent.com/29464607/156828998-0ba3394b-9766-4304-a2ea-096e1f31f9d9.png)

The reason you don't see command decorations after running exec `bash` is because we currently don't support shell integration for sub-shells.

**Comment by jibbers42** [comment]
@meganrogge I have installed code-insiders to test with the latest available to me and the issue persists.

The only extension I have installed is "Remote - WSL".
The only custom setting is `"terminal.integrated.shellIntegration.enabled": true`

To simplify my normal prompt, I've added the following at the end of my `.bashrc`:
```
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
PS1="\n$PS1"
```
This is a copy of the of default prompt from earlier in .bashrc, but with the `@\h` removed to remove my hostname, then I've added the newline.

Please let me know of any thoughts to get our environments to line up.

![image](https://user-images.githubusercontent.com/797824/156854268-4706765f-d2a2-46e3-8dce-2af81b33b6f2.png)
