### ISSUE TITLE
Add a setting to ignore dirty tabs in `workbench.editor.limit.value`

### ISSUE THREAD

**Issue by buggymcbugfix** [microsoft/vscode#144309]
I have long been looking for a way to keep my tabs tidy and was extremely happy to find the `workbench.editor.limit` feature.
Per @[bpasero](https://github.com/bpasero) https://github.com/microsoft/vscode/issues/9872#issuecomment-567463617, dirty tabs count towards the editor tabs limit. This is unfortunate, because I often have several dirty tabs and once their number approaches the open tabs limit, I no longer get to open several clean tabs in parallel. I would like to have an option for `workbench.editor.limit.value` to ignore dirty tabs.

**Comment by buggymcbugfix** [comment]
I would like dirty tabs to never get auto-closed (same behaviour as now). Dirty tabs should simply not count towards the limit. If my limit is 3 and I have 5 dirty tabs, then I still want to be able to open 3 clean tabs.

**Comment by bpasero** [comment]
Oh I see.

**Comment by bpasero** [comment]
I think this can be done by a contribution via PR, relevant code piece is:

https://github.com/microsoft/vscode/blob/cc76605726772f454a8ba93e03e1a2921af26270/src/vs/workbench/browser/parts/editor/editorsObserver.ts#L341

**Comment by luoriyuhui21** [comment]
hello，could I work on this issue as my first one ？

**Comment by bpasero** [comment]
Yes, anyone can work on this 👍

**Comment by luoriyuhui21** [comment]
this pr is as 
https://github.com/microsoft/vscode/pull/144545

**Comment by bpasero** [comment]
Thanks, will take a look later this month.

**Comment by buggymcbugfix** [comment]
thanks @bpasero @luoriyuhui21 ❤️

**Comment by bpasero** [comment]
**Verification:** play with the new `workbench.editor.limit.excludeDirty` setting and ensure it is working as advertised.

**Comment by lramos15** [comment]
@bpasero This setting is sort of what I do with the tabs API sample. I wonder if we should just have an extension which implements all these caveats.
