### ISSUE TITLE
HOW THE FUCK MY DEBUG IS NOT WORKING ??????

### ISSUE THREAD

**Issue by conmeobeo121** [microsoft/vscode#144356]

**Comment by januwA** [comment]
![image](https://user-images.githubusercontent.com/22570563/156688619-50bf1592-db4c-4b3e-b403-f364816f8f86.png)

版本: 1.65.0 (user setup)
提交: b5205cc8eb4fbaa726835538cd82372cc0222d43
日期: 2022-03-02T11:12:08.962Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by kkocdko** [comment]
With `yarn web`:

```
Version: 1.65.0
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T10:58:34.946Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
```

Open a js file and start debug, choose nodejs, the UI freezed.

Now I downgrade to `1.64`

**Comment by connor4312** [comment]
/needsMoreInfo

In addition, please review the Microsoft Open Source [Code of Conduct](https://opensource.microsoft.com/codeofconduct/).
