### ISSUE TITLE
Make breakpoint colour configurable/themeable

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#1443]

**Comment by isidorn** [comment]
:+1:
@aeschli some pointers on how to do this would be appreciated - how can my .css rule come from a theme?

**Comment by aeschli** [comment]
Applying the colors from a thTheme file to css happens in
`src/vs/workbench/services/themes/node/themeService.ts`  in `_processThemeObject`
Besides colors for syntax elements, each tmTheme has some keys for general colors.
Of course you can also add your own keys, but so far we have not done any customization of tmThemes.
