### ISSUE TITLE
Git Source control branch name mangled in latest update

### ISSUE THREAD

**Issue by CloudlessBrown** [microsoft/vscode#144369]
Issue Type: <b>Bug</b>

In the latest release of VSCode I am no longer able to sync changes with master branch on BitBucket. It appears to be mangling the BitBucket branch name when attempting to sync, resulting in a failed sync. It appears to be inserting a '/' (forward slash) into the branch name.

This is a guess, but it may be somehow related to me using both BitBucket and GitHub (for historical reasons) with a branch named master on each platform, but locally named different things. While this has worked fine for years, it now fails when I sync with BitBucket. Looking at the traces, it is mangling the branch name.

The error occurs even with all extensions turned off. Screen shot of message just prior to syncing - notice extraneous forward slash in the branch name.

![Screenshot 2022-03-03 235616](https://user-images.githubusercontent.com/40311951/156714668-a2b18fe8-e27a-4f9c-aff3-7160e13c72b6.jpg)

Then throwing error:
![Screenshot 2022-03-04 000134](https://user-images.githubusercontent.com/40311951/156715403-e535f74a-96d6-43a0-acc2-1166dac633f9.jpg)

with trace:
```
> git pull --tags BitBucket-ori in/master
fatal: 'BitBucket-ori' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

Git Graph output showing master on Bitbucket (top of screen capture) and master on Github (bottom of screen capture)

![Screenshot 2022-03-03 235757](https://user-images.githubusercontent.com/40311951/156715010-c9c52397-d7be-4296-93b1-182be0c64c98.jpg)

I notice that the remote name is truncated at the same number of characters as the same name on the other remote.
```
BitBucket-ori
origin/master
```

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.95GB (2.47GB free)|
|Process Argv|--crash-reporter-id be669926-a8c5-495c-a453-ffedd5020d52|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
vscop841:30447409
dsvsc009:30440023
pythonvspyt640:30442238
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvidc:30447482
helix:30440343
vsnot107:30443614

```

</details>

**Comment by CloudlessBrown** [comment]
Git's perspective (showing fully formed remote branch name correctly):
`
$ git status
On branch BB-master
Your branch is up to date with 'BitBucket-origin/master'.
'

**Comment by lszomoru** [comment]
This is [a regression](https://github.com/microsoft/vscode/issues/144205) that was introduced in `1.65`. Sorry about that.
The issue has already been fixed in Insiders, and it will be part of the next recovery release.
