### ISSUE TITLE
Extension debugging doesn't work with two IP6 network interfaces 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#144315]
VS Code's Extension debugging fails with the following message when the computer is connected to two IP6 network interfaces, e.g. a wired ethernet and WLAN:

![image](https://user-images.githubusercontent.com/1898161/156572243-c43b5234-7d84-46de-ac1f-bcd871db4b79.png)

To make investigation of this problem easier I was able to find a simpler repro:

- have your computer connected to two IP6 network interfaces, e.g. wired ethernet and WLAN
- create "server.js" with this contents:
   ```
   let i = 0;
   setInterval(() => {
     console.log(`hello world ${i++}`);
   }, 1000);
   ```
- launch server.js from VS Code's integrated terminal with `node --inspect-brk=12345 server.js`
- create launch config:
  ```
  {
     "name": "Attach to server",
     "type": "node",
     "request": "attach",
     "port": 12345
  }
  ```
- open chrome dev tool console
- run "Attach to server" launch config

Observe:
debugger cannot attach to server and console shows this:

![CleanShot 2022-03-03 at 12 35 07](https://user-images.githubusercontent.com/1898161/156559395-1c37bd04-b148-46ad-a0f5-97e52d3b7d4c.png)

- add a `"address": "127.0.0.1"` to the launch config
- run "Attach to server" launch config

Observe:
debugger attaches without problems.

- replace "127.0.0.1" with "localhost" and try again

Observe:
debugger cannot attach to server.

So it seems that using "localhost" does not always work and we should use "127.0.0.1" instead when connecting to the debug port.

@connor4312 could you please make sure that js-debug uses "127.0.0.1" as a fallback.
This is especially important for extension debugging because there it is not possible to specify an explicit address in the launch config.

/cc @alexdima

**Comment by weinand** [comment]
@connor4312 the fallback happens but doesn't help...

here is my setup:
- open and built latest version of js-debug in VS Code Insiders
- set breakpoint in "basicResourceProvider.ts":96
- run "Debug Server" launch config
- open another VS Code window with my "server.js" from above
- add `"debugServer": 4711` to launch config from above
- run launch config
- wait until breakpoint is hit
- step and continue until error appears on debug console

Here is a recording:
https://user-images.githubusercontent.com/1898161/157644634-25715fe1-8186-4a0e-9cdd-f4d469de78ab.mp4

If I change the launch config to use "127.0.0.1" js-debug is able to attach:

https://user-images.githubusercontent.com/1898161/157645898-a3f86ee6-1516-4fc7-922b-d26d5c3187fd.mp4

Please note that I was not able to hit any breakpoints in server.js.

**Comment by connor4312** [comment]
If I don't get to this next debt week, I will just plan on tackling it in June when I'll be in the Zurich office solely for the opportunity to fix this bug ;)

**Comment by weinand** [comment]
@connor4312 wow, that's an excellent move ;-)

**Comment by connor4312** [comment]
Verified by @weinand

**Comment by weinand** [comment]
@connor4312 since I'm in the office today, I could actually verify that this issue has been fixed in Insiders.
