### ISSUE TITLE
Enable mob / ensemble programming shared workspace (perhaps via Teams?)

### ISSUE THREAD

**Issue by jimbethancourt** [microsoft/vscode#144398]
A shared/collaborative synchronous workspace that enables remote mob/ensemble programming would be incredibly helpful and would simplify remote mob workflows.  

Integration with Microsoft Teams would be wonderful as well, something similar to how the Whiteboard app is integrated with Teams.  This could also help accelerate and simplify development of the feature.

This idea is inspired by the IntelliJ CodeWithMe plugin.  If VS Code were integrated with Teams, this feature could be deployed much easier in environments where technical difficulties may be encountered when attempting to collaboratively work on code that is transmitted through a third party server that is not already in the organization's trust store.

**Comment by IllusionMH** [comment]
VS Code already have Live Share extension. How proposed solution differs?
