### ISSUE TITLE
code doesnt suport your windows message

### ISSUE THREAD

**Issue by Chaursiya54** [microsoft/vscode#144367]
We have written the needed data int
Issue Type: <b>Performance Issue</b>

hello
while using vs code, it often shows  code is crashed, reopen or close it. 

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 6.2.9200
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-9225 RADEON R4, 5 COMPUTE CORES 2C+3G    (2 x 2595)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.89GB (4.02GB free)|
|Process Argv|--crash-reporter-id 2600da00-1974-41b5-8bd8-b2026b0929be|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   115	  2112	code main
    0	    35	  2752	   crashpad-handler
    0	    43	  3224	   utility-network-service
    0	    96	  5404	   shared-process
    0	    75	  2972	     ptyHost
    0	    21	  2936	       winpty-process
    0	    11	  6376	         console-window-host (Windows internal process)
    0	    84	  6688	         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    21	  4840	       winpty-process
    0	    11	  1468	         console-window-host (Windows internal process)
    0	    66	  6200	         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    21	  6028	       winpty-process
    0	    11	  1928	         console-window-host (Windows internal process)
    0	    66	  8876	         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    73	  9088	     fileWatcher
    0	   137	  5984	   window (Get Started - Visual Studio Code [Administrator])
    0	   168	  7924	   gpu-process
    0	   102	  8832	   extensionHost
    0	    77	  8508	     "C:\Users\rohit\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\rohit\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=8832
    0	   167	 10112	   "C:\Program Files\Google\Chrome\Application\chrome.exe" --single-argument https://github.com/Microsoft/vscode/issues/new?title=this%20code%20doesnt%20suport%20your%20windows&body=We%20have%20written%20the%20needed%20data%20into%20your%20clipboard%20because%20it%20was%20too%20large%20to%20send.%20Please%20paste.
    0	    21	  3308	     utility
    0	   133	  4520	     gpu-process
    0	    83	  6348	     window (undefined)
    0	    57	  6588	     window (undefined)
    0	    42	  7172	     utility-network-service
    0	    30	  7488	     window (undefined)
    0	   133	  7500	     window (undefined)
    0	    11	  8248	     crashpad-handler
    0	    85	 10136	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.7
LiveServer|rit|5.7.4

**Comment by dbaeumer** [comment]
@Chaursiya54 do you still have the data. Without it it is very hard to act on this issue.
