### ISSUE TITLE
Two prompts when uninstalling an extension pack

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#14438]
Testing #14291

- install the '999 Martins Favourite Extensions' extension pack
- uninstall the extension pack. You are prompted with:

> Are you sure to uninstall 'Martins Favourite Extensions' 

Press ok 

> Would you like to uninstall 'Martins Favourite Extensions' only or its dependencies also.

A single prompt would do

**Comment by sandy081** [comment]
Duplicates #14414
