### ISSUE TITLE
Terminal typing fade-in effect

### ISSUE THREAD

**Issue by zjtalia** [microsoft/vscode#144341]
Issue Type: <b>Bug</b>

When typing in the terminal, the text that i type is initially dim and fades in. This issue began after updating to the most recent version of VS Code (1.65). After I reverted to the previous version, the behavior stopped.

VS Code version: Code 1.65
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.11.0-1028-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.20GB (16.72GB free)|
|Process Argv|--crash-reporter-id 7dc3e13b-ba4c-4641-af01-49f4cef1dcd1 --crash-reporter-id 7dc3e13b-ba4c-4641-af01-49f4cef1dcd1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: zach-dev|
|OS|Linux x64 5.11.0-1028-aws|
|CPUs|AMD EPYC 7571 (2 x 2199)|
|Memory (System)|3.79GB (0.48GB free)|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc009:30440023
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343
vsnot107:30443614

```

</details>

**Comment by meganrogge** [comment]
does setting `terminal.integrated.localEchoEnabled` to `off` solve the problem?

**Comment by zjtalia** [comment]
Yes it did, thank you so much!
