### ISSUE TITLE
tooltips de sugestões

### ISSUE THREAD

**Issue by samuk159** [microsoft/vscode#144390]
Issue Type: <b>Feature Request</b>

Ao passar o mouse em cima de uma tag do html ele abre um tooltip com a descrição da tag. Isso pode ser útil para iniciantes, mas para quem usa para o trabalho é extremamente irritante. Eu procurei como desativar e a única coisa que funcionou foi desativar o hover ("editor.hover": false), mas dessa forma os tooltips de erros também não aparecem. Seria bom ter uma opção de desativar os tooltips por tipo, para desativar por exemplo apenas os de html, ou ativar somente os de erro.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.8.0-63-generic
Restricted Mode: No

Google translate:

When you hover over an html tag it opens a tooltip with the tag description. This can be useful for beginners, but for those who use it for work it is extremely annoying. I looked for how to disable and the only thing that worked was to disable the hover ("editor.hover": false), but that way the error tooltips also do not appear. It would be nice to have an option to disable tooltips by type, to disable for example only html ones, or to enable only error ones.

**Comment by aeschli** [comment]
We have the options `html.hover.documentation` and `html.hover.references` for that. Please give it a try.
