### ISSUE TITLE
Clicking on a file path in the terminal opens a new VS Code window

### ISSUE THREAD

**Issue by geajack** [microsoft/vscode#144384]
Does this issue occur when all extensions are disabled?: Yes

Version information:
```
Version: 1.65.0 (user setup)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:12:08.962Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
```

Steps to Reproduce:

1. Put a relative path to a file in the same folder VS Code is currently in, in the terminal, e.g.:
![](https://i.imgur.com/LcdqdvC.png)
2. I expect alt-clicking it to simply open that file in the current VS Code window, but instead it launches a new VS Code window opened to a seemingly random folder (presumably the most recent folder I was in?).

**Comment by meganrogge** [comment]
That's working for me in insider's. Could you pls see if you can repro the issue there?

If you can, then pls set log level to debug and provide me with the `Opening link...` log that appears when you click that.
![Recording 2022-03-04 at 10 31 30](https://user-images.githubusercontent.com/29464607/156801999-230c7364-10ba-4c52-99f1-680ece329a50.gif)
