### ISSUE TITLE
Newest update to Jupyter and Python extensions broke ability to save .IPNYB files 

### ISSUE THREAD

**Issue by ikanter66** [microsoft/vscode#144360]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

Issue Type: <b>Bug</b>

After receiving the latest update to VS Code as well as Jupyter and Python extensions, I can no longer save jupyter notebook files. I have attempted to reinstall VS Code, as well as uninstall and reinstall Jupyter and python extesions. I have to select no file associate and save the file. 

Extension version: 2022.2.1020642448
VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.64GB (6.70GB free)|
|Process Argv|--crash-reporter-id 9695621a-f4b0-40cd-a8f9-7046515a1d2d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc009:30440023
pythonvspyt640:30442238
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvid1:30447480
helix:30440343
vscaac:30438847
vsnot107cf:30443615

```

</details>

**Comment by eduardo-fernandes-marques** [comment]
Same problem for _typescriptreact_ files. I had to uninstall my django extension for starts to work again but there other problems as node environment like when i try to run a next application I am receiving this error: 

`ReferenceError: process is not defined`

But I have my config set in my .env file.

This problem did not happen before VSCode update.

**Comment by rebornix** [comment]
From the info above, it doesn't seem to be notebook specific.

**Comment by ikanter66** [comment]
This seems to have been fixed for me. There was another update made on 03/04/2022.
