### ISSUE TITLE
Weird highlighting behaviour on Rust file

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#144354]
Version: 1.65.0-insider (Universal)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T03:14:48.052Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0

Rust extension: v0.7.8

Unexpected highlighting of words.
![Recording 2022-03-03 at 16 56 26](https://user-images.githubusercontent.com/12758612/156678821-6d5eb954-c045-4861-8ea8-29f9deae4bb1.gif)

**Comment by yume-chan** [comment]
Note: the token reference highlight is provided by extensions.

I remember rust-analyzer only update this on save (cargo check), and if your code doesn't compile, it won't update either.

**Comment by aeschli** [comment]
The highlighting very likely comes from an extension.

Does the issue reproduce with extensions disabled? (Run command: `Developer: Reload With Extensions Disabled`).

**Comment by tanhakabir** [comment]
You're right it was the extension
