### ISSUE TITLE
VSCode refuses to open plain text file that begins with digits

### ISSUE THREAD

**Issue by af4jm** [Microsoft/vscode#14433]
- VSCode Version: Code - Insiders 1.7.0-insider (5bafcdb3d67b29b1f4667a3f497ac05a41dde667, 2016-10-25T06:11:16.069Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-caniuse|akamud|0.5.3|
|Bookmarks|alefragnani|0.9.2|
|code-gnu-global|austin|0.2.1|
|gitignore|codezombiech|0.2.0|
|vscode-markdownlint|DavidAnson|0.5.0|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.0.8|
|githistory|donjayamanne|0.1.0|
|python|donjayamanne|0.5.0|
|xml|DotJoshJohnson|1.6.0|
|escaping-characters|drphrozen|1.0.0|
|EditorConfig|EditorConfig|0.3.4|
|tslint|eg2|0.5.39|
|matlab|Gimly81|0.4.0|
|CppSnippets|hars|0.0.5|
|vscode-firefox-debug|hbenl|0.7.0|
|icalendar|AF4JM|0.0.1|
|Ionide-fsharp|Ionide|2.8.2|
|vstsbuildstatus|jeppeandersen|0.5.0|
|docthis|joelday|0.3.5|
|docomment|k--kato|0.0.7|
|HTMLHint|mkaufman|0.0.3|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.4.1|
|mono-debug|ms-vscode|0.11.0|
|PowerShell|ms-vscode|0.7.2|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|team|ms-vsts|1.108.0|
|debugger-for-chrome|msjsdiag|2.0.0|
|Ruby|rebornix|0.10.1|
|yo|samverschueren|0.9.0|
|Spell|seanmcbreen|0.8.6|
|code-settings-sync|Shan|2.3.3|
|vscode-hexdump|slevesque|1.0.1|
|lodash-snippets|tomphilbin|0.7.0|
|change-case|wmaurer|0.4.1|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

I have a 74.6MB plain text file (with a client's HR data), tried to use VSCode to find out if there was a byte-order mark or whatever at the beginning of the file, it refused to open.  The vscode-hexdump extension also crashed trying to open the file.  So opened the file in Visual Studio's binary editor.  First 6 bytes are digits, then a bunch of spaces.  Screen clip attached (deliberately chopped down to omit PII, but it clearly shows there's no stray bytes, nor BOM, at the beginning of the file).

![vscode bin bug](https://cloud.githubusercontent.com/assets/849948/19687204/955d974c-9a92-11e6-97cb-14a8e945c4c4.png)

**Comment by bpasero** [comment]
Please report this against the binary editor extension, you did the right thing to try to use that extension for opening 👍

**Comment by af4jm** [comment]
OK, I can do that... but that doesn't answer the question why VSCode is refusing to open a plain text file and claiming that it's binary.  If there was some borked BOM or other stray character at the front of the file, I'd chalk it up to bogus input, but I should be able to create a file with no header that starts with ASCII digits and have it open in VSCode's text editor.  (I'd go so far as to say, since it's a text editor, it should NEVER error that the file is binary, in the same way that I can open a DLL or EXE in notepad; but it seems it's been decided to be more restrictive with VSCode.)

**Comment by bpasero** [comment]
@af4jm we refuse to open files that contain 0 bytes (as your file does) unless it contains a UTF-16 BOM in the beginning. We do this to protect from opening potentially large binary files as text files.

**Comment by af4jm** [comment]
My file does not contain 0 bytes.  The only character in the file that's not ASCII printable (x20-x7E) is line feed (x0A).  The 0 in the far left column of my screen shot is the hex number of the first bit in that row (in the non-cropped screen shot it looks like BASIC line numbers), in this case the digit 7 (x37)

**Comment by bpasero** [comment]
@af4jm can you attach the file for me to try out?

**Comment by af4jm** [comment]
@bpasero I can't post it anywhere that's public, because it contains phone & email of every employee & contractor of one of my employer's clients, we receive the file encrypted (and I'm actually investigating an issue where our communication & translation tool--BizTalk competitor--is having issues decrypting it, where other tools including GPG4Win decrypt it without issue).  I also don't want to try to clean the data or truncate the file, in case it is something wonky with the file, the edit & save could change the results.

**Comment by bpasero** [comment]
Ok I understand, I think I cannot help you then.
