### ISSUE TITLE
No outline view in markdown file when using footnotes

### ISSUE THREAD

**Issue by odelaf** [microsoft/vscode#144340]
Issue Type: <b>Bug</b>

1. Create any markdown file with headings. Outline view works.
2. Create footnotes like [^1] and [1]:
3. Outline view not found message

VS Code version: Code 1.65.0 (Universal) (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:11:20.886Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 87ba1aa6-1b33-4e0e-aa33-fbfbba993ffe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-languagetool|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
vscode-languagetool-es|ada|3.8.0
markdown-footnotes|bie|0.0.7
dakara-foldplus|dak|1.5.2
vscode-markdownlint|Dav|0.46.0
vscode-pandoc|Dou|0.0.8
vscode-fold|fel|1.4.3
mdmath|goe|2.7.4
unicode-math-vscode|Gui|0.3.3
vscode-markdown-footnote|hou|1.0.0
markdown-extended|jeb|1.1.1
markdown-toc|jof|1.4.0
markdown-math|koe|0.1.0
pandoc-markdown-preview|kzv|0.4.1
zotero|mbl|0.1.10
markdown-shortcuts|mdi|0.12.0
vscode-language-pack-es|MS-|1.65.1
wordcount|ms-|0.1.0
pandocciter|not|0.9.2
vscode-markdown-table|pha|1.5.0
word-counter|plu|0.0.1
languagetool|ray|1.0.1
java|red|1.4.0
markdown-preview-enhanced|shd|0.6.2
even-better-toml|tam|0.14.2
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.1
vscode-maven|vsc|0.35.1
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc008:30440022
pythonvspyt640:30442238
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvidc:30438801
helix:30440343
vsnot107:30443614

```

</details>

**Comment by mjbvz** [comment]
Please share example markdown that demonstrates the issue

Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
