### ISSUE TITLE
Cache API's cache.put() crashing in pwa-msedge

### ISSUE THREAD

**Issue by bmakan** [microsoft/vscode#144303]
Issue Type: <b>Bug</b>

Cache API doesn't work on Edge when opened via pwa-msedge debugger. I tried the same code via Microsoft Edge, Firefox and Google Chrome opened without vscode's debugger and it worked as expected.

1. Run `caches.open('v1').then((cache) => cache.add(<some_valid_url>));`
2. results in the following error (expanded from the vscode's console):
```
Uncaught DOMException: Entry already exists.
    arg0:DOMException: Entry already exists. {code: 15, name: 'InvalidAccessError', message: 'Entry already exists.'}
        code:15
        message:'Entry already exists.'
        name:'InvalidAccessError'
        [[Prototype]]:DOMException
        ABORT_ERR:20
        code (get):ƒ code()
        DATA_CLONE_ERR:25
        DOMSTRING_SIZE_ERR:2
        HIERARCHY_REQUEST_ERR:3
        INDEX_SIZE_ERR:1
        INUSE_ATTRIBUTE_ERR:10
        INVALID_ACCESS_ERR:15
        INVALID_CHARACTER_ERR:5
        INVALID_MODIFICATION_ERR:13
        INVALID_NODE_TYPE_ERR:24
        INVALID_STATE_ERR:11
        message (get):ƒ message()
        name (get):ƒ name()
        NAMESPACE_ERR:14
        NETWORK_ERR:19
        NO_DATA_ALLOWED_ERR:6
        NO_MODIFICATION_ALLOWED_ERR:7
        NOT_FOUND_ERR:8
        NOT_SUPPORTED_ERR:9
        QUOTA_EXCEEDED_ERR:22
        SECURITY_ERR:18
        SYNTAX_ERR:12
        TIMEOUT_ERR:23
        TYPE_MISMATCH_ERR:17
```

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1062.18.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.40GB (2.47GB free)|
|Process Argv|--crash-reporter-id 0e2907cf-6f55-46cf-9c6a-ef4845ad0d17|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: <removed by reporter>|
|OS|Linux x64 3.10.0-1062.18.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU           X3440  @ 2.53GHz (8 x 1333)|
|Memory (System)|15.50GB (7.21GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
gitkraken-authentication|git|1.0.3
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
vscode-icons|vsc|11.10.0
vscode-sql-formatter|adp|1.4.4
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.0
vscode-npm-script|eg2|0.3.24
gitkraken-authentication|git|1.0.3
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.4
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc009:30440023
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343
vsnot107:30443614

```

</details>

**Comment by connor4312** [comment]
Please report an error via the Edge issue reporter, this doesn't appear to be something we can fix from the debugger side.
