### ISSUE TITLE
Improve rendering of keybindings for combining accents

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#14431]
This is a spin off from #12682 for the issue pointed by @BairDev

Specifically, under the German Keyboard Layout (in Gnome/Mutter window manager), ``ctrl+` `` for toggle integrated terminal gets rendered with a combining accent and it looks a bit garbled, making appear that it is ``ctrl + ` `` when in fact it should look more like `ctrl + ^`

Layout:

![image](https://camo.githubusercontent.com/7acd47da8677ca24757c60e068f408452d4c068e/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f332f33362f4b425f4765726d616e792e737667)

Rendered:

![F1 list](https://cloud.githubusercontent.com/assets/2767014/19684557/23b0bde2-9ab8-11e6-81e3-be762995ec09.png)

**Comment by BairDev** [comment]
Alright, thanks for opening this separate one.

**Comment by alexandrudima** [comment]
Ok, the character U+0302 combining circumflex accent will be from now on rendered with the character U+005E circumflex accent

![image](https://cloud.githubusercontent.com/assets/5047891/19690920/8ce542c8-9ad2-11e6-80b5-f6b077886859.png)

Moreover, I've mapped the following:

|  FROM  |  TO  |
|---------|------|
| Combining_Grave_Accent | GRAVE_ACCENT |
| Combining_Acute_Accent | ACUTE_ACCENT |
| Combining_Circumflex_Accent | CIRCUMFLEX |
| Combining_Tilde | SMALL_TILDE |
| Combining_Macron | MACRON |
| Combining_Overline | OVERLINE |
| Combining_Breve | BREVE |
| Combining_Dot_Above | DOT_ABOVE |
| Combining_Diaeresis | DIAERESIS |
| Combining_Ring_Above | RING_ABOVE |
| Combining_Double_Acute_Accent | DOUBLE_ACUTE_ACCENT |

**Comment by BairDev** [comment]
Thanks for fixing this, I'm looking forward to see it fixed.

Because you've mentioned the *circumflex* accent: Indeed, when I use `ctrl+^` it toggles the **internal** terminal, but only two times. Then the following message appears:
![vscode_circumflex](https://cloud.githubusercontent.com/assets/2767014/19759774/be2cefea-9c2e-11e6-9fc7-ebac2a56a50e.png)

This seems to be weird to me.

Additionally: should I open a new issue for the *internal/external* terminal problem?

**Comment by alexandrudima** [comment]
@BairDev Does the problem reproduce for you if you run `code --disable-extensions`?

### How to find out why this command tries to execute

I don't believe `extensions.togglecodeblock` is a command we ship with, perhaps you have installed an extension that binds this **missing** command. To confirm, can you open your keybindings and search in the default keybindings (that contains also those coming in from extensions) for `extensions.togglecodeblock`.

### How to find out which extension defines this keybinding

At this point, you need to click on each installed extension (or perhaps on those that hint at this functionality) and go to the "Contributions" section. There you will see, for each extension, what sort of things it contributes, including keybindings.

**Comment by BairDev** [comment]
Oh year, this works perfectly! I'll figure out, which extension is the evil one. Thanks a lot!

**Comment by isidorn** [comment]
Verified by user adding verified tag
