### ISSUE TITLE
Leverage new support for markdown in timeline hovers for the git contribution

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#144397]
There is now support for using Markdown in timeline hovers, this should be used to embellish the current Git hover with improved formatting, emojis, avatar, and command links. This is the existing hover:

![image](https://user-images.githubusercontent.com/172399/156771449-96be02c3-44b7-4d72-b5c7-0b42735be284.png)

Here are some examples for how Markdown is leveraged in hovers:

Remote Explorer/remote containers:
![image](https://user-images.githubusercontent.com/172399/156772301-c4eccdd3-3430-4986-a193-b099e49b2101.png)

Remote Explorer/codespaces
![image](https://user-images.githubusercontent.com/172399/156772417-6444b021-4ba4-4efa-97a6-3e9952f53002.png)

GitLens 
![image](https://user-images.githubusercontent.com/172399/156772690-ab7d63b6-8944-4dad-b05a-a7ed4b62305b.png)

**Comment by lszomoru** [comment]
In the first iteration we have settled on using links and codicons.
We will be exploring whether it makes sense to also add actions to the hover. 

<img width="411" alt="image" src="https://user-images.githubusercontent.com/3372902/159351821-a58c7e3f-1032-4d42-95a2-2ec14d73b25c.png">

**Comment by lszomoru** [comment]
Verification steps:
1. Open a folder/workspace that contains a git repository
2. Open an file in the editor
3. Open the `Timeline` view, and filter the view to "Git History"
4. Hover over multiple changes and confirm that the hover information renders correctly
