### ISSUE TITLE
Evaluating expression in the repl takes two Enter key presses

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#14430]
#14171

![image](https://cloud.githubusercontent.com/assets/22350/19687072/56872812-9ac4-11e6-9254-2ff8ddb93746.png)

Since the repl now has suggest embedded it became a terrible experience since I always have to click <kbd>Enter</kbd> twice to evaluate anything: the first to accept the automatic suggestion that came up and the second to submit the expression.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/11944
