### ISSUE TITLE
TS/JS language server keeps crashing

### ISSUE THREAD

**Issue by serkangunes** [microsoft/vscode#144380]
Issue Type: <b>Bug</b>

During live share sessions, language server keeps crashing.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|64.00GB (3.92GB free)|
|Process Argv|--crash-reporter-id b1e1d7a8-d45f-4055-aea9-9382e760e408|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (67)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.2.4
jest-snippets|and|1.8.0
svelte-intellisense|ard|0.7.1
atlascode|atl|2.10.9
scratchpad|awe|0.1.0
vscode-tailwindcss|bra|0.7.7
turbo-console-log|Cha|2.1.7
gitignore|cod|0.7.0
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|1.11.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.3.0
vscode-svelte-snippets|fiv|0.5.0
auto-rename-tag|for|0.1.10
kotlin|fwc|0.2.23
copilot-nightly|Git|1.7.5219
vscode-pull-request-github|Git|0.36.2
gitkraken-authentication|git|1.0.3
gitpod-desktop|git|0.0.29
go|gol|0.31.1
terraform|has|2.20.0
vscode-drawio|hed|1.6.4
output-colorizer|IBM|0.1.2
plantuml|jeb|2.17.2
vscode-hygen|jon|0.0.2
Kotlin|mat|1.7.1
vscode-github-actions|me-|3.0.1
openapi-lint|mer|1.2.0
git-graph|mhu|1.30.0
import-sorter|mik|3.3.1
dotenv|mik|1.0.1
vscode-docker|ms-|1.20.0
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.5418
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
gremlins|nho|0.26.0
git-semantic-commit|nit|2.0.0
terraform-advanced-syntax-highlighting|pjm|1.4.0
material-icon-theme|PKi|4.13.0
polacode|pnp|0.3.4
ponicode|Pon|0.66.4
quicktype|qui|12.0.46
java|red|1.4.0
vscode-yaml|red|1.4.0
openapi-vs-code|Red|0.2.4
explorer-exclude-vscode-extension|Red|1.2.0
LiveServer|rit|5.7.4
partial-diff|ryu|1.4.3
scala|sca|0.5.5
aws-dynamo-json-to-type|Ser|0.0.1
svelte-vscode|sve|105.12.1
pdf|tom|1.2.0
errorlens|use|3.4.1
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-pack|vsc|0.21.0
quokka-vscode|Wal|1.0.449
change-case|wma|1.0.0
local-history|xyz|1.8.1
vscode-surround|yat|1.2.2
html-css-class-completion|Zig|1.20.0
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30438340
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc009:30440023
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvid1:30438799
helix:30440343

```

</details>

**Comment by mjbvz** [comment]
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
