### ISSUE TITLE
Explore alternate locations for the notifications center

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#144330]
The current location of the notification center in the status bar presents a few potential problems:
- Notifications feel like a concept global to the application, even if many notifications are scoped to the current workspace. The status bar is mostly scoped to the current workspace/file, so it feels strange to have notifications located there.
- The notification icon looks and feels like a regular status bar item, so it's hard to visually locate
- It can be easy to miss notifications in the far lower right on the window

A few quick sketches to show what notifications could look like if moved to a more obvious area:

## Move notification center to the title bar

This builds off the explorations by @lychung7 and @misolori to start moving more features to the title bar. E.g. search/commands, layout controls, etc.

### macOS
<img width="1034" alt="mac-dot" src="https://user-images.githubusercontent.com/25163139/156622550-a7748562-3720-480d-8c90-19d3b374714c.png">

### Windows
<img width="1025" alt="windows-dot" src="https://user-images.githubusercontent.com/25163139/156622577-4a71357f-a407-48fe-9282-66839b839727.png">

## Use a different color for the notification dot

This could make notifications even more obvious. This might only make sense if we were to someday enable notifications _without_ a toast.

### macOS
<img width="1037" alt="mac-red-dot" src="https://user-images.githubusercontent.com/25163139/156622622-b84fc404-7d01-4975-b126-860cd96796f6.png">

### Windows
<img width="1020" alt="windows-red-dot" src="https://user-images.githubusercontent.com/25163139/156622647-de29df37-8c09-4618-92fd-90e7d7691be8.png">

## Considerations

There are a few obvious trade offs here:
- Notification list and toasts would overlap some workbench actions and tabs
- Existing users are used to where notifications are located today
- Potentially adds noise to the UI by moving notifications to a more prominent location
- Should feedback have the same treatment given the global scope argument above?

**Comment by misolori** [comment]
cc @sbatten

**Comment by bpasero** [comment]
I don't really understand how this works when notification toasts show up. Would we move them also to the top right then?

**Comment by daviddossett** [comment]
That's the idea, yes. Something like this:

## Toast
<img width="707" alt="CleanShot 2022-03-04 at 08 53 04@2x" src="https://user-images.githubusercontent.com/25163139/156805658-a76df52f-9e01-4ba7-a438-252936fe5473.png">

## Notification center
<img width="614" alt="CleanShot 2022-03-04 at 08 53 31@2x" src="https://user-images.githubusercontent.com/25163139/156805693-d5f8aa16-7d0f-4e5a-a150-1a92e871ab3a.png">

**Comment by daviddossett** [comment]
I explored another option based on an idea from @lychung7:

## Notifications in Activity Bar

As the title says—this looks at how notifications might benefit from a dedicated view container. This explorations shows:
- An activity bar contribution w/ badge indicating "unread" notification count
- List of notifications with unread/read states, message, source, and actions
- Dedicated actions for "clear notification". Experiementing with a `check` icon instead of `close` to lean towards the notion of "done" rather than "delete".

Another potential benefit of this model would be the ability to keep older viewed notifications around to avoid them being lost in the ether. [People complain](https://twitter.com/idangazit/status/1503582722903609344) about this happening today.

One downside here is that the Profile and Settings icons below the bell are context menus, not view containers. So a bit of a dissonance there.

https://user-images.githubusercontent.com/25163139/159587549-bfbc06cb-a67e-42be-b59b-b33e1c0d726f.mp4

## Notifications in Title Bar

I also updated the title bar example with some realistic notifications for reference:

https://user-images.githubusercontent.com/25163139/159587625-423e628d-7245-47b9-b422-019cb34aaa59.mp4

**Comment by bpasero** [comment]
cc @stevencl : didn't we had discussions in the past that for UX consistency an icon in the activity bar that is bottom left cannot change the view contents. Rather those should appear top left? 

I personally think that entries bottom left in the activity bar should open menus / global things and not change the sidebar.

**Comment by stevencl** [comment]
We used to have notifications dropping down from the title bar in the centre. This was considered very disruptive and was one of the main reasons we moved them down to the bottom of the screen.

We did have those discussions about bottom left not changing the sidebar and I think that consistency is worth preserving. 

Notifications in VS work very similarly to VS Code but there is an affordance to pin the notification centre so that it doesn't auto hide. It's set to auto hide by default but you can pin it if you want. If you do, then a notifications view and associated tab is added to the existing views. 

I think David's design for managing old/read notifications is worth exploring further and is orthogonal I think to the position of the notification centre.

**Comment by daviddossett** [comment]
Agreed that the old design was disruptive from the perspective of where the toasts show up. I also like the spirit of the restrictions re: bottom activiy bar items being context menus, not view containers. 

> I think David's design for managing old/read notifications is worth exploring further and is orthogonal I think to the position of the notification centre.

This has been one of the more interesting themes I've seen pop up from these explorations. I'll keep exploring this independent of the notification center's location.

**Comment by daviddossett** [comment]
Closing since we opted against this some months ago
