### ISSUE TITLE
linux用yum下载code-insiders的问题

### ISSUE THREAD

**Issue by linux-rm** [microsoft/vscode#144388]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:code-insiders-1.65.0-1645162554.el7.x86_64.rpm
- OS Version:Linux localhost 5.16.9-200.fc35.x86_64 #1 SMP PREEMPT Fri Feb 11 16:29:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1.
```
# yum search code-insiders
上次元数据过期检查：0:22:11 前，执行于 2022年03月04日 星期五 19时34分37秒。
===== 名称 精准匹配：code-insiders =====
code-insiders.x86_64 : Code editing. Redefined.
```

2.
```
# yum download code-insiders
上次元数据过期检查：0:24:09 前，执行于 2022年03月04日 星期五 19时34分37秒。

没有可用的软件包 code-insiders。
退出由于严格设置。
错误：没有可用的软件包 code-insiders。
```
问题:linux(fedora)不能通过yum下载code-insiders,只能手动下载rpm文件才能安装
![1](https://user-images.githubusercontent.com/100938047/156760319-0c110641-97d9-4238-bee8-6c9ec99392fb.png)

**Comment by Tyriar** [comment]
It's not clear what you're asking

**Comment by linux-rm** [comment]
已经正常了
Already normal.
