### ISSUE TITLE
how to stop wsl mode in vscode

### ISSUE THREAD

**Issue by amitdvs** [microsoft/vscode#144322]
Issue Type: <b>Bug</b>

like i am done with wsl in vscode.
i can find a option to stop current wsl mode in vscode.
and when i restart it open in wsl mode

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.84GB (12.02GB free)|
|Process Argv|--crash-reporter-id 46186884-37e0-4c31-b8ca-25d990e78a64|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (2 x 2592)|
|Memory (System)|3.84GB (3.59GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|4.4.3
auto-rename-tag|for|0.1.10
gitkraken-authentication|git|1.0.3
remote-containers|ms-|0.224.2
remote-wsl|ms-|0.64.2
material-icon-theme|PKi|4.13.0
errorlens|use|3.4.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc008:30440022
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343
vsnot107cf:30443615

```

</details>

**Comment by aeschli** [comment]
Click on the remote menu (status bar, lower left, `WSL..`) and choose `Close Remote Connection`

**Comment by aeschli** [comment]
Or, when closing VS Code close all windows but make sure the las closed window is not a WSL window.
A empty , non-WSL window can also be created by `New Window` from the file menu.

**Comment by aeschli** [comment]
Let me know if I misunderstood.
