### ISSUE TITLE
Code snippet "Choice" feature no longer working 

### ISSUE THREAD

**Issue by NJK-HOME** [microsoft/vscode#144362]
Does this issue occur when all extensions are disabled?: Not applicable as this requires PowerShell extension

- VS Code Version: 1.65.0
- OS Version: Windows 10 and 11 (Tested in both)

Steps to Reproduce:

1.  Create a code snippet for PowerShell to provide a choice to the user to select from, such as this:
`{
    "Test":
    {
        "prefix": "Test",
        "body":
        [
            "# ${1|Option1,Option2,Option3|}$0"
        ],
        "description": "Test choice snippet"
    }
}`
2. Add code snippet to a PS1 file (using ctrl-alt-j).
3. Snippet should provide a drop-down list of three options (Option1, Option2, Option3) for the user to select.
4. Instead it just shows Option1 and says "Loading" under that.
![image](https://user-images.githubusercontent.com/61813693/156705419-8916f951-1470-4f31-9900-8e27783e674a.png)
5. I have confirmed this worked in the previous version (1.63.2).
6. Documentation I found shows this, so I believe I am doing correctly:

[User Defined Snippets | Choice](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_choice)
Placeholders can have choices as values. The syntax is a comma-separated enumeration of values, enclosed with the pipe-character, for example ${1|one,two,three|}. When the snippet is inserted and the placeholder selected, choices will prompt the user to pick one of the values.

Thank you.
NJK

**Comment by Urkallinger** [comment]
The same problem occurs with Python snippets.

**Comment by henryas** [comment]
Got the same problem with Go snippets.

**Comment by jrieken** [comment]
A fix for this will be in next [VS Code Insiders](https://code.visualstudio.com/insiders/). Also, this will be part of a 1.65.x recovery release

**Comment by jrieken** [comment]
To verify: 

* F1 > Configure Snippets
* Add the snippet shown below or any other snippet that uses choise
* Insert the snippet
* Make sure the choice-placeholder shows the options in suggest


```json
{
    "Test": {
        "prefix": "Test",
        "body": [
            "# ${1|Option1,Option2,Option3|}$0"
        ],
        "description": "Test choice snippet"
    }
}
```

**Comment by Raydir** [comment]
Seems to work again, thanx @jrieken

**Comment by NJK-HOME** [comment]
Hmmm...this is still broken for me.  I have upgraded to 1.65.1 and it still shows "loading".  Is there a newer recovery release that I need to wait for?  I don't use insider builds.

Thanks
NK

**Comment by NJK-HOME** [comment]
Ah, I see - looks like it will available here in "February 2022 Recovery 2".  I will test it out once that is released.

Thanks again.
NK

**Comment by NJK-HOME** [comment]
Looks good!  Thank you for fixing this.
NK

**Comment by geoffw123** [comment]
Why has this issue been closed. It is still broken for me, using the choice syntax used to work fine for ages but now I get "No Suggestions" instead of the optional choices. I have changed nothing in my snippets file.
I am using today's insiders build 1.67.0
