### ISSUE TITLE
Improve prompt when installing extension packs

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#14435]
Testing #14291

- create an extension pack (see #14291)
- install the extension pack. You are prompted with:

> Installing 'Martins Favourite Extensions' also installs its dependencies. Would you like to continue?

I wonder if the prompt is useful. 
As a user, is it something to worry about? Should I say yes or no? 

I guess the prompt can be removed. Else it can be replaced with an more of an information.
Press ok to install 'Martins Favourite Extensions' and 6 dependencies.

**Comment by sandy081** [comment]
Duplicates #14412
