### ISSUE TITLE
Go to definition with ctrl+click is not working.

### ISSUE THREAD

**Issue by Senior-Software-Developer** [microsoft/vscode#144305]
Issue Type: <b>Bug</b>

I am a web developer and use visual studio code as an editor.
Recently, Ctrl+click  is not working.
I googled but, I didn't find a suitable solution.
I expect this issue to be solved soon.
Thanks.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.51GB free)|
|Process Argv|--crash-reporter-id f8ce5e9a-df46-452f-b2c8-42ef02488fd9|
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.6
simple-react-snippets|bur|1.2.6
react-redux-react-router-snippets|dis|0.4.29
docs-images|doc|0.0.9
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|9.3.0
vscode-react-typescript|inf|1.3.1
cpptools|ms-|1.8.4
vscode-typescript-next|ms-|4.7.20220302
language-vscode-javascript-angular2|nwa|0.0.11
tsimporter|pmn|2.0.1
typescript-hero|rbb|3.0.0
vscode-javascript-booster|sbu|14.0.1
move-ts|str|1.12.0
eno|Wsc|2.3.53
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc008:30440022
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343
vscaat:30438848
vsnot107cf:30443615

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command to investigate.

**Comment by mjbvz** [comment]
There's also not enough information to investigate this. Please see our issue reporting guidelines for help filing an issue. Be sure to include all the steps to reproduce the problem
