### ISSUE TITLE
${env:PATH} not detected on terminal

### ISSUE THREAD

**Issue by psycho-neon** [microsoft/vscode#144339]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0
- OS Version: Windows 10

Issue: `${env:PATH}` is not detected on terminal

Steps to Reproduce:

1. Set settings for `terminal.integrated.env.windows`
```
"terminal.integrated.env.windows": {
        "PATH": "${env:PATH};"
    },
```
2. open terminal inside vscode and type `echo %PATH%`.
3. it will return empty.

**Comment by Hivemind9000** [comment]
I'm experiencing exactly the same problem after the latest update today. I haven't changed a thing, it just suddenly stopped working after the update.

In settings:

```
"terminal.integrated.env.windows": {
      "Path": "C:\\Users\\XX\\AppData\\Local\\Google\\Cloud SDK\\google-cloud-sdk\\bin;${env:Path};"
}
```

If I open a terminal and type `echo %PATH%` it returns:

`C:\Users\XX\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;;`

**Comment by marektakac** [comment]
I have the same problem since this morning. It suddenly doesn't work and I spent an hour figuring out, what's the problem. I guess my VSCode was updated yesterday.

**Comment by AnrDaemon** [comment]
Same issue #144385

**Comment by AnrDaemon** [comment]
>  I guess …

Teach you to disable automatic updates. Always.

**Comment by tjprescott** [comment]
@Tyriar as a workaround, is there a way for users to roll back the update?

**Comment by meganrogge** [comment]
you can uninstall the current version and re-install 1.64 @tjprescott

**Comment by tjprescott** [comment]
> you can uninstall the current version and re-install 1.64 @tjprescott 

And make sure to disable VSCode's automatic updates before installing the old version or you end right up back with the broken one. 

Settings > "Update" > Update: Mode = Manual

**Comment by Tyriar** [comment]
Verified on Insiders

**Comment by Maxim-Mazurok** [comment]
I thought that this was a workaround:
```json
"terminal.integrated.defaultProfile.windows": "PowerShell",
"terminal.integrated.profiles.windows": {
  "PowerShell": {
    "source": "PowerShell",
    "icon": "terminal-powershell",
    "env": { "PATH": "${env:PATH};${workspaceRoot}\\node_modules\\.bin" }
  },
  "Command Prompt": {
    "path": [
      "${env:windir}\\Sysnative\\cmd.exe",
      "${env:windir}\\System32\\cmd.exe"
    ],
    "args": [],
    "icon": "terminal-cmd",
    "env": { "PATH": "${env:PATH};${workspaceRoot}\\node_modules\\.bin" }
  },
  "Git Bash": {
    "source": "Git Bash"
  }
},
```
but it doesn't seem to always work...

**Comment by jganser** [comment]
> I thought that this was a workaround:
> 
> ```json
> "terminal.integrated.defaultProfile.windows": "PowerShell",
> "terminal.integrated.profiles.windows": {
>   "PowerShell": {
>     "source": "PowerShell",
>     "icon": "terminal-powershell",
>     "env": { "PATH": "${env:PATH};${workspaceRoot}\\node_modules\\.bin" }
>   },
>   "Command Prompt": {
>     "path": [
>       "${env:windir}\\Sysnative\\cmd.exe",
>       "${env:windir}\\System32\\cmd.exe"
>     ],
>     "args": [],
>     "icon": "terminal-cmd",
>     "env": { "PATH": "${env:PATH};${workspaceRoot}\\node_modules\\.bin" }
>   },
>   "Git Bash": {
>     "source": "Git Bash"
>   }
> },
> ```
> 
> but it doesn't seem to always work...

It has the same result as not mentioning any PATH variable for me.
The original PATH is available, but the extension is not happening.

Are there any other workarounds yet?

**Comment by alexr00** [comment]
We intend to release a stable build with the fix today, so soon you will not need a work around.

**Comment by xy9485** [comment]
Any update? terminal.integrated.env.linux is still broken on:
Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044
