### ISSUE TITLE
[Feature Request] Select all the instances of selected text on a single line

### ISSUE THREAD

**Issue by usamazansari** [microsoft/vscode#144392]
> VS Code Editor

Add a feature to select all the instances of a selected text on a _single line_.

An extension of the shortcut `Ctrl + F2` which selects all the instances of the text in the entire file, likewise a shortcut `Ctrl + Shift + F2` which would select the instances of the text in the line where the cursor is at.

Example:

```ts
const object = {
  one: 'deeply/nested/directory/path/to/one',
  two: 'deeply\\nested\\directory\\path\\to\\two',
}
```

I copy `three: 'deeply\nested\directory\path\to\three'` from elsewhere and paste it after `two`

```ts
const object = {
  one: 'deeply/nested/directory/path/to/one',
  two: 'deeply\\nested\\directory\\path\\to\\two',
  three: 'deeply\nested\directory\path\to\three'
}
```

I place the cursor on line containing `three` and hit `Ctrl + Shift + F2` to select all the `\` in that line and not the next or previous line or anywhere else in the file.

**Comment by ArturoDent** [comment]
You can do that with an extension I wrote, [Find and Transform](https://marketplace.visualstudio.com/items?itemName=ArturoDent.find-and-transform&ssr=false#overview).

Use this keybinding:

```jsonc
  {
    "key": "alt+w",
    "command": "findInCurrentFile",
    "args": {
      "restrictFind": "line"
    }
  }
```

Select what you want to find and select on the line, in your case `\`, and trigger the keybinding.  If you want ed the whole word, like `three` you don't have to even select it.


![slelectSeparator](https://user-images.githubusercontent.com/31813701/156845489-9e0657dc-20b5-47de-8edc-43311d6d2a5f.gif)

**Comment by usamazansari** [comment]
Thanks a lot 🥳  @ArturoDent
