### ISSUE TITLE
Find in file is not fast enough...

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#14437]
Open https://github.com/alexandrudima/unicode-utils/blob/master/UnicodeData.txt

Search for `;NSM;` in regex mode. Press `F3` repeatedly. This should be very fast.

**Comment by dakaraphi** [comment]
@alexandrudima FYI, you might find a pending pull request for Brackets as a useful resource.  I worked on improving the search performance and reached some pretty amazing results, but due to time constraints I couldn't continue the work to finalize.
https://github.com/adobe/brackets/pull/12442
