### ISSUE TITLE
VSCode TypeScript project references resolve of duplicate files

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/vscode#144317]
Does this issue occur when all extensions are disabled?: Yes 

# Bug Report

### 🔎 Search Terms

VSCode, tsconfig ,project references

### 🕗 Version & Regression Information

- TypeScript Version: 4.5.5
- VS Code Version: 1.64.2 (Universal)
- OS Version: Darwin x64 21.2.0
### ⏯ Example repo

https://github.com/xiaoxiangmoe/typescript-project-reference-demo.git)

### 💻 Code

// tsconfig.json
```json
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.test.json"
    },
  ]
}
```
// tsconfig.app.json

```json
{
  "include": ["src/**/*"],
  "exclude": ["src/**/__tests__/*"],
  "compilerOptions": {
    "moduleResolution": "Node",
    "composite": true,
    "target": "ESNext",
    "noEmit": true,
    "strict": true,
    "lib": ["DOM", "ESNext"],
    "types": []
  }
}
```
// tsconfig.test.json
```json
{
  "extends": "./tsconfig.app.json",
  "exclude": [],
  "compilerOptions": {
    "types": ["node"]
  }
}
```

// src/components/Foo.ts
```ts
export type FooProps = { a: number };
export function Foo(props: FooProps) {
  return null;
}
/**
 * this file is included in both `tsconfig.app.json` and `tsconfig.test.json`
 * 
 * So we should follow the order of `references` in `tsconfig.json`
 * 
 * `tsconfig.app.json` comes before `tsconfig.test.json`, so we should use config file `tsconfig.app.json` in vscode
 * 
 */
const cwd = process.cwd()
```
### 🙁 Actual behavior

I think `const cwd = process.cwd()` should has an Error.

Because file `src/components/Foo.ts` are included in `tsconfig.app.json`. So it has not include type `@types/node`.

### 🙂 Expected behavior

`const cwd = process.cwd()`  has no Error.

File `src/components/Foo.ts` is included in both `tsconfig.app.json` and `tsconfig.test.json`.  VSCode search references field and use the last item of references —— `tsconfig.test.json`. So it has no error.

I think we should use first reference. I remember that earlier versions of vscode did this too. I want to know why VSCode/TS change it to use last reference?

---

related issue: https://github.com/microsoft/TypeScript/issues/48058

**Comment by mjbvz** [comment]
Closing in favor of upstream issue (https://github.com/microsoft/TypeScript/issues/48058) since the references ultimately are computed by typescript
