### ISSUE TITLE
Display color Bug from Light High Contrast Theme

### ISSUE THREAD

**Issue by YuanzheTian** [microsoft/vscode#144357]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- 
![image](https://user-images.githubusercontent.com/44792821/156688884-c8937ee1-5a59-4092-be07-f96fa2178669.png)

- OS Version:

Steps to Reproduce:

Python Code
imported but not used
![image](https://user-images.githubusercontent.com/44792821/156688958-bcd7d114-da6f-4e98-8c47-e1a1941827d6.png)
![image](https://user-images.githubusercontent.com/44792821/156688974-e2548d1d-c30e-476d-bdf1-16019a9da61a.png)
![image](https://user-images.githubusercontent.com/44792821/156688996-6fed8785-e25c-4d61-ad7b-7dee90d39153.png)
White underline may be used like black high contrast theme, which cannot be displayed in white high contrast theme.

1.
2.

**Comment by daviddossett** [comment]
Thanks for the catch @YuanzheTian. I'll be fixing a batch of bugs on the new HC theme in the coming week 👍

**Comment by daviddossett** [comment]
Fixed 👍

<img width="591" alt="CleanShot 2022-03-07 at 11 04 57@2x" src="https://user-images.githubusercontent.com/25163139/157100953-3942d204-4616-4bae-b44d-5894a206b55a.png">
