### ISSUE TITLE
Code preview map not synced with scroll

### ISSUE THREAD

**Issue by rotarur** [microsoft/vscode#144319]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: Darwin x64 21.3.0

Steps to Reproduce:

1. Enable code preview
2. Select two files to compare
3. Scroll down

Description:

I'm having a strange bug when I'm checking differences between two files in vscode and scroll down my preview is not in sync with the scroll position on my page.

The diff status happens in the middle of the page but the scroll is showing the top of it. I've put some arrows in the screenshot so you can understand better what I mean.

This bug is very strange but confuses me sometimes, especially when I have multiple matches in my code.

![image](https://user-images.githubusercontent.com/5681717/156575228-d2001e73-2388-4acc-b32a-d2f8d965b77a.png)

**Comment by alexdima** [comment]
This is because we artificially enlarge the slider to 20px. Let's track in https://github.com/microsoft/vscode/issues/82087
