### ISSUE TITLE
Loading stuck

### ISSUE THREAD

**Issue by kristian-nostdal** [microsoft/vscode#144377]
Issue Type: <b>Bug</b>

Open vscode, look at live share - loading stuck and can never join others

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:11:20.886Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|32.00GB (6.92GB free)|
|Process Argv|--crash-reporter-id 3f4708eb-c360-4ce9-800d-a13fd41b1921|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|13.2.4
azurite|Azu|3.16.0
format-json|Cle|1.0.2
angular-schematics|cyr|5.1.1
gitlens|eam|12.0.1
prettier-vscode|esb|9.3.0
vs-code-xml-format|fab|0.1.5
gitkraken-authentication|git|1.0.3
vscode-test-explorer|hbe|2.21.1
vue|jcb|0.1.5
volar|joh|0.32.1
prettify-json|moh|0.0.3
vscode-docker|ms-|1.20.0
csharp|ms-|1.24.1
remote-containers|ms-|0.224.2
test-adapter-converter|ms-|0.1.5
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.5418
vetur|oct|0.35.0
vscode-thunder-client|ran|1.12.2
fabric8-analytics|red|0.3.5
java|red|1.4.0
vue-vscode-snippets|sdr|3.1.1
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.34.1
vscode-maven|vsc|0.35.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30440023
pythonvspyt640:30442238
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvidc:30447482
helix:30440343
vscaat:30438848
vsnot107:30443614

```

</details>

**Comment by lszomoru** [comment]
@kristian-nostdal, could you please file an issue in [the extension's repository](https://github.com/MicrosoftDocs/live-share/issues)? Thanks!
