### ISSUE TITLE
Bundling errors because of sanitize-html

### ISSUE THREAD

**Issue by mgranlund-ms** [microsoft/vscode#144326]
Issue Type: <b>Bug</b>

When I try to bundle the code to deployment it errors out because of using sanitize-html.
Error messages:
Error - [tsc] node_modules/htmlparser2/lib/index.d.ts(36,11): error TS1005: 'from' expected.
Error - [tsc] node_modules/htmlparser2/lib/index.d.ts(36,14): error TS1005: ';' expected.
Error - [tsc] node_modules/htmlparser2/lib/index.d.ts(36,23): error TS1005: ';' expected.
Error - [tsc] node_modules/htmlparser2/lib/index.d.ts(36,28): error TS1005: ';' expected.

sanitize-html has been installed, I see it in the node_modules

Snippet of the code where it is used.
import * as sanitizeHTML from 'sanitize-html';
      this.domElement.innerHTML = sanitizeHTML(
        `<div class="${ styles.ahsiMutliUseBanner}">
          <div data-ng-controller="HomeController as vm">
            <div class="${styles.loading}" ng-show="vm.isLoading">
              <div class="${styles.spinner}">
                <div class="${styles.spinnerCircle} ${styles.spinnerLarge}"></div>
                <div class="${styles.spinnerLabel}">Loading...</div>
              </div>
            </div>
            <div ng-show="vm.isLoading === false">
              <div class="${styles.option1}" ng-class="{'${styles.active}':vm.opt1}">
                <div class="${styles.banner_box}" ng-repeat="box in vm.boxList" ng-class="{'${styles.shadow}': box.shadow, '${styles.notitle}': box.notitle}" style="box-shadow:{{box.boxShadowStyle}};">
                  <div class="${styles.banner_title}" ng-class="{'${styles.small}': box.hdrFontSize == 'small', '${styles.large}': box.hdrFontSize == 'large', '${styles.bold}': box.fweight}" style="color:{{box.hdrFontColor}};background-color:{{box.hdrBgColor}};border-color:{{box.hdrBorderColor}};border-width:{{box.hdrBorderWidth}};">{{box.Title}}</div>
                  <div class="${styles.banner_content}" style="background-color:{{box.cntBgColor}};border-color:{{box.cntBorderColor}};border-width:{{box.cntBorderWidth}};" ng-bind-html="vm.convertHTML(box.Content);"></div>
                </div>
              </div>
              <div class="${styles.option2}" ng-class="{'${styles.active}':vm.opt2}">
                <div class="${styles.banner_box}" ng-repeat="box in vm.boxList"  ng-class="{'${styles.shadow}': box.shadow, '${styles.notitle}': box.notitle}" style="box-shadow:{{box.boxShadowStyle}};">
                  <div class="${styles.banner_content}" style="background-color:{{box.cntBgColor}};border-color:{{box.cntBorderColor}};border-width:{{box.cntBorderWidth}};" ng-bind-html="vm.convertHTML(box.Content);">{</div>
                  <div class="${styles.banner_title}" ng-class="{'${styles.small}': box.hdrFontSize == 'small', '${styles.large}': box.hdrFontSize == 'large', '${styles.bold}': box.fweight}" style="color:{{box.hdrFontColor}};background-color:{{box.hdrBgColor}};border-color:{{box.hdrBorderColor}};border-width:{{box.hdrBorderWidth}};">{{box.Title}}</div>        
                </div>
              </div>                           
              <div class="${styles.option3}" ng-class="{'${styles.active}':vm.opt3}">
                <div class="${styles.banner_box}" ng-repeat="box in vm.boxList" ng-class="{'${styles.shadow}': box.shadow, '${styles.notitle}': box.notitle}" style="box-shadow:{{box.boxShadowStyle}};">
                  <div class="${styles.banner_box_img}" style="background-color:{{box.imgBgColor}};"><img src="{{box.Image.Url}}"/></div>
                  <div class="${styles.banner_box_text}">
                      <div class="${styles.banner_title}" ng-class="{'${styles.small}': box.hdrFontSize == 'small', '${styles.large}': box.hdrFontSize == 'large', '${styles.bold}': box.fweight}" style="color:{{box.hdrFontColor}};background-color:{{box.hdrBgColor}};border-color:{{box.hdrBorderColor}};border-width:{{box.hdrBorderWidth}};">{{box.Title}}</div>
                      <div class="${styles.banner_content}" style="background-color:{{box.cntBgColor}};border-color:{{box.cntBorderColor}};border-width:{{box.cntBorderWidth}};" ng-bind-html="vm.convertHTML(box.Content);"></div>
                  </div>
                </div>
              </div>
            </div>             
          </div>
        </div>`, {        
          allowedTags: ['div', 'img'],
          allowedAttributes:{
            div: ['class', 'data-ng-controller', 'ng-show', 'ng-class', 'ng-repeat','ng-bind-html','style'],   
            img: [ 'src' ] 
          },
          selfClosing: ['img']
        });

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (3.52GB free)|
|Process Argv|--crash-reporter-id 50346276-bb80-4025-9b19-08aefe339d02|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aeschli** [comment]
I don't think this is related to VS Code.
Looks like the TypeScript compiler (tsc) is not happy about the content of `node_modules/htmlparser2/lib/index.d.ts`.
I would start by checking out the content of that file.
