### ISSUE TITLE
Word suggestion seems to have been broken for a couple of days: existing word is not overriden

### ISSUE THREAD

**Issue by Nevor** [Microsoft/vscode#14445]
- VSCode Version: 1.7.0-insider
- OS Version: Windows 10 Version 1607

When word suggestion is invoked with Ctrl+space after some existing prefix, the list is correctly displayed and filtered but does not overwrite existing prefix/word when validated. The completion is simply appended after the current cursor position.

Steps to Reproduce:

1. open a text file with "--disable-extensions"
2. type 'foobar'
3. move back the cursor three times 
4. trigger suggestion with ctrl+space: 'foobar' is correctly displayed but not highlighted
5. accept suggestion with enter: foobar is appended in the middle, was expecting an identity transformation

**Comment by jrieken** [comment]
Good catch!

**Comment by jrieken** [comment]
this is a regression from https://github.com/Microsoft/vscode/commit/929d6a5504b5bd59f862ac729295d81e1331c7e2#diff-1deeb8bade7d1505128d6eee90a5868c
