### ISSUE TITLE
terminal.integrated.tabs.title

### ISSUE THREAD

**Issue by FMLjs** [microsoft/vscode#144403]
Issue Type: <b>Bug</b>

If you go to terminal.integrated.tabs.title and set ${workspaceFolder} to variable value, then the working directory will no longer be displayed. Previously, when I right-clicked on a folder and clicked the "open in integrated terminal" button, a new terminal would open with the name of that folder.

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by FMLjs** [comment]
Downgraded to 13.5.2 and now everything works.

**Comment by meganrogge** [comment]
Works for me in insider's. Can you attach a gif of this happening?
![Recording 2022-03-04 at 10 12 54](https://user-images.githubusercontent.com/29464607/156799014-b41a3ff9-a6b4-417d-bd5e-dc1421fc4562.gif)
