### ISSUE TITLE
Node bug crashes the vscode debugger

### ISSUE THREAD

**Issue by erights** [microsoft/vscode#144493]
Issue Type: <b>Bug</b>

Start a debug session using the JavaScript Debug Terminal.

In the debug console:
```js
p = Promise.resolve(8);
Promise {[[PromiseState]]: 'fulfilled', [[PromiseResult]]: 8, Symbol(async_id_symbol): 3543, Symbol(trigger_async_id_symbol): 1783, Symbol(destroyed): {…}}
names = Reflect.ownKeys(p);
(3) [Symbol(async_id_symbol), Symbol(trigger_async_id_symbol), Symbol(destroyed)]
for (const name of names) {
  delete p[name];
}
true
Object.freeze(p);
Promise {[[PromiseState]]: 'fulfilled', [[PromiseResult]]: 8}
q = p.then(x => console.log(x));
```
Now check the JavaScript Debug Terminal. If you reproduce the bug, you should find that the last line above caused the debug session to crash, leaving on the JavaScript Debug Terminal a stack trace containing:

```
  TypeError: Cannot add property Symbol(async_id_symbol), object is not extensible
    at Promise.then (<anonymous>)
```

I reported the Node bug causing this at https://github.com/nodejs/node/issues/42229

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.60GB free)|
|Process Argv|--crash-reporter-id 4edc82fd-0c8d-48dc-8226-2dcbe3400d35|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|3.4.0
svelte-intellisense|ard|0.7.1
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.1
graphviz-preview|EFa|1.5.0
vscode-pull-request-github|Git|0.36.2
gitkraken-authentication|git|1.0.3
debug-visualizer|hed|2.2.4
cpptools|ms-|1.8.4
vs-code-prettier-eslint|rve|3.1.0
svelte-vscode|sve|105.12.1

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrt:30437039
vsrem710:30416614
dsvsc008:30440022
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343
vsnot107:30443614

```

</details>

**Comment by connor4312** [comment]
This isn't a bug we can fix in VS Code, Node.js will need to fix it upstream.
