### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by apflaker** [microsoft/vscode#144491]
Issue Type: <b>Bug</b>

Application popup: inno_updater.exe - System Error : The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.  this error happens everytime i try to update

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 6.3.9600
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-5550M APU with Radeon(tm) HD Graphics    (4 x 2096)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.21GB (12.53GB free)|
|Process Argv|--crash-reporter-id 0d0a7b2d-aa86-487b-9c42-85039952f5fd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|8.2.0
vscode-color|ans|0.4.5
npm-intellisense|chr|1.4.1
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
gitlens|eam|12.0.1
prettier-vscode|esb|9.3.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc008:30440022
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvid2:30447481
helix:30440343
vsnot107cf:30443615

```

</details>

**Comment by joaomoreno** [comment]
Can you install the [Visual C++ Redistributable for Visual Studio 2015
](https://www.microsoft.com/en-in/download/details.aspx?id=48145)?
