### ISSUE TITLE
search error when including an absolute path

### ISSUE THREAD

**Issue by r3inbowari** [microsoft/vscode#144474]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.2
- OS Version: Win 11

Steps to Reproduce:

1.  Use an absolute path, seems to be fine.
![image](https://user-images.githubusercontent.com/30739857/156892771-97debaa4-daf1-4744-9810-1ed4af8c0066.png)

2. When a relative path to a same file, error occurred.
![image](https://user-images.githubusercontent.com/30739857/156892739-3ab9f49b-adca-4933-b105-071685931d40.png)

**Comment by roblourens** [comment]
This works with a folder, but not a file https://github.com/microsoft/vscode/issues/20530
