### ISSUE TITLE
Light High Contrast theme extension view: no contrast between active/inactive extensions

### ISSUE THREAD

**Issue by GabenGar** [microsoft/vscode#144437]
Does this issue occur when all extensions are disabled?: Yes, because there is no contrast difference for disabled extensions.

- VS Code Version: 1.65.0
- OS Version: Windows 7

Steps to Reproduce:

1. Go into extensions view with at least one extension enabled and one disabled
2. Select Light High Contrast theme
3. Select Light+ theme
4. Observe the difference

Screenshots:
![light-plus](https://user-images.githubusercontent.com/87906913/156834103-6eb04d9c-ad99-44c2-80a0-6739809b0340.png) | ![light-high-contrast](https://user-images.githubusercontent.com/87906913/156834151-36240d1a-e19a-4b8d-9eb0-1cb1f56e1d12.png)

**Comment by tacc-wbomar** [comment]
**Another Detail**
If the user does **not** select/click/focus a disabled extension, the extension has the problem as stated.
But, if user selects/clicks/focuses a disabled extension, the extension appears disabled.

**Comment by daviddossett** [comment]
Thanks for the details, @tacc-wbomar 🙏

**Comment by daviddossett** [comment]
@sandy081 @bpasero -- tagging since I see you've touched various parts of this:

Any ideas why this is working for normal light, dark, and dark HC themes but not light HC? It looks like it's manipulating the foreground color to be 50% opaque and then supposedly making it opaque based on the background color.

That all seems sensible enough. Can't understand why it's resulting in `#141414`, which is essentially as dark as the theme's base foreground color.

https://github.com/microsoft/vscode/blob/30e1c0cfdaa3d1b3e7d4a0141bb8b0d3bcb51887/src/vs/workbench/contrib/extensions/browser/extensionsList.ts#L253

**Comment by bpasero** [comment]
Adding @aeschli.

I wonder if this is a missing adoption of the new `hc-light` theme specifically for the window background? We have code on the main process to update the windows background color based on the selected theme and I see no mention of `hc-light`, so maybe we end up setting a dark background color?

https://github.com/microsoft/vscode/blob/dde804e1e928aabc3964ec0cf89b5262a46edf86/src/vs/platform/theme/electron-main/themeMainService.ts#L12-L14

**Comment by bpasero** [comment]
Also, shouldn't we adopt it here and return a light color:

https://github.com/microsoft/vscode/blob/8bfa08790435ca4f6a6b1e54c4037fa384867b1a/src/vs/workbench/common/theme.ts#L13-L22

**Comment by aeschli** [comment]
Having the light contrast theme kind is on the plan, but no work has been done yet.

But I think what this issue shows is that are missing a overall background color that a theme can define. 
We need something like `workbench.background` or `background`. We already have `foreground` as 'Overall foreground color'.

`WORKBENCH_BACKGROUND` will then take the color from there.

All colors in the UI should be definable in the active color theme. The defaults should really just be defaults.
-> https://github.com/microsoft/vscode/blob/30e1c0cfdaa3d1b3e7d4a0141bb8b0d3bcb51887/src/vs/workbench/contrib/extensions/browser/extensionsList.ts#L253 is not proper

**Comment by aeschli** [comment]
@daviddossett I've started working on https://github.com/microsoft/vscode/tree/aeschli/hcLightThemeKind
