### ISSUE TITLE
`isWeb` when clause does not work while using `pwa-extensionhost` approach

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#144472]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65 (stable)
- OS Version: MacOS Big Sur

Steps to Reproduce:

1. Create or adapt some extension to be web-ready, following https://code.visualstudio.com/api/extension-guides/web-extensions
2. Choose any `command` and/or `walkthrough` step to be disabled on _web_, adding `"when": "!isWeb"` to it
3. Debug/Test the extension using the `pwa-extensionhost` approach, as defined in https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension-in-vs-code-running-on-desktop
4. Try to run the `command` or navigate to the `walkthrough` and you will notice that both are active/enabled
5. Now, Debug/Test the extension using the _sideload_ approach, as defined in https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension-in-on-vscode.dev
6. Try to run the same `command` or navigate to the `walkthrough` and you will noticed that bot are properly inactive/disabled (as expected)

Thank you

**Comment by aeschli** [comment]
There are many different setups that VS Code can run in. Web or Electron UI, with Node and/or Web extension hosts.
`isWeb` reflects only the UI. It is only true when running in a browser. 

There's no built-in context key that can tell you where your extension runs (Web or NodeJS) as that is specific to your extension (of it has main and/or browser, defines certain contribution points, see[here](https://code.visualstudio.com/api/advanced-topics/extension-host#preferred-extension-location)).
But, your extension can define it's own context key.  the best is to use them to describe a capability your extension has (can run XY command, can format).

**Comment by alefragnani** [comment]
If this is a limitation and there is no way to properly support it, that’s ok. As I pointed out, side loading the extension works, so it’s a good workaround. 

> But, your extension can define it's own context key. the best is to use them to describe a capability your extension has (can run XY command, can format).

Right now, I only need enable commands/menus, so `isWeb` is the perfect solution. 

On the other hand, if in the future I need to detect in source if _running on the web_, I guess `env.uiKind === UIKind.Web` would do the trick. At least, until a `getContext` API is available.

Thank you

**Comment by aeschli** [comment]
`env.uiKind === UIKind.Web` again only tells you in what type of UI VS Code runs.
If the UI is web, that doesn't mean your extension runs in the browser, it might run on Node, in a remote code server. Example for that is the Web UI for Codespaces.

**Comment by alefragnani** [comment]
Ops, that's true. Thanks for remember me that.
