### ISSUE TITLE
Error inserting multiple snippets

### ISSUE THREAD

**Issue by DewarCG** [microsoft/vscode#144418]
- VS Code Version: 1.65.0
- OS Version: Linux x64 5.13.0-30-generic

Steps to Reproduce:

1. Create the following snippet: `"test": { "prefix": "test", "body": [ "$1.$SELECTION = ${1/(.+)UpdateInput$/$1/}" ] }`
2. Select two or more words separated by endlines
3. Create multiple cursors (one by line) by executing the command: "Add cursors to line ends"
4. Select word (one by line)
5. Execute the "Surround with snippet" command with the previous snippet

VsCode will throw the following error:

**this._placeholderGroups[this._placeholderGroupsIdx] is not iterable**

**Comment by jrieken** [comment]
I can't reproduce that error. Please update/refine your steps. Thanks


https://user-images.githubusercontent.com/1794099/156877504-3fb263ee-53ff-4869-828d-7f782f08dff1.mov

**Comment by DewarCG** [comment]
I fixed the steps description

**Comment by jrieken** [comment]
This is still something missing, I don't see the error you do. Please check your steps again and add a recording of what you do

https://user-images.githubusercontent.com/1794099/158385621-8526b470-55b6-4f1b-9c17-e44261a01b31.mov
