### ISSUE TITLE
typescript file extension is truncated when import

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#144435]
Does this issue occur when all extensions are disabled?: Yes/No

Yes.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/156830663-1ce62546-6697-4d37-9631-7f8597e34e37.png">

I know there is a setting `typescript.preferences.importModuleSpecifierEnding`, which default value is `auto`, that value will not auto add '.ts` extension.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/156830804-cda1b8b5-46f5-4e11-8c1f-25a04f562f48.png">

@mattbierner

- VS Code Version: 1.66.0-insider
- OS Version: MacOS 12.2.1

Steps to Reproduce:

1. enter a ts project
2. import a relative module

**Comment by mjbvz** [comment]
This is by-design. The typescript team can add more detail but the gist is that having a `.ts` ending would cause the compiled javascript  to try importing a typescript file, which is almost never what you want

**Comment by mjbvz** [comment]
The `js` ending exists for JavaScript files because having a `.js` import is valid (and even required for some module systems)
