### ISSUE TITLE
TypeScript language server exited with error.Error message is : write EPIPE

### ISSUE THREAD

**Issue by rikian** [microsoft/vscode#144494]
![image](https://user-images.githubusercontent.com/84202969/156912104-b15317b2-496f-48d3-8022-4654e6a5fbd3.png)

**Comment by victorlmneves** [comment]
Don't know why this issue was closed as it still happens

**Comment by ruslankonev** [comment]
Confirm, I've got 5 instances of vscode open, and got a this error

**Comment by mjbvz** [comment]
If you're still seeing this, then open a new issue. Be sure to fill in the issue template and as much info as you can to reproduce it
