### ISSUE TITLE
Unable to jump to a component or class when hovering over it 

### ISSUE THREAD

**Issue by Mickbear18** [microsoft/vscode#144461]
Issue Type: <b>Bug</b>

 Hello! 
Unable to jump to a component or class when hovering over it 

I import js module() and I want to open it, hover over and hold command.. it doesn't work, also it doesn't work with css classes 

VS Code version: Code 1.65.0 (Universal) (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:11:20.886Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

**Comment by mjbvz** [comment]
Please share code that demonstrates this issue and steps to reproduce it
