### ISSUE TITLE
Suggest Preview for Snippets

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#144421]
For now, we can using suggest details to check the snippet content:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/156810304-78a6ad12-09c9-4345-b2fe-107b85174c76.png">

It would be more convenient to support suggest preview to snippet especially for user disable suggest details. @hediet

**Comment by jrieken** [comment]
> It would be more convenient to support suggest preview to snippet especially for user disable suggest details.

Can you clarify? Do you mean the "ghost text feature"?  Do you know about the `"editor.suggest.preview": true,` setting?

**Comment by tjx666** [comment]
Yes, I want that feature apply to snippets.

**Comment by jrieken** [comment]
It does that

<img width="740" alt="Screen Shot 2022-03-05 at 10 21 08" src="https://user-images.githubusercontent.com/1794099/156877089-36738ee3-dae9-4893-992d-406062e10073.png">

**Comment by tjx666** [comment]
Some of them works, but some not:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/156877249-d2d67f83-613d-4450-8ca1-a92136e692c4.png">

**Comment by jrieken** [comment]
True story. Assigning to @hediet but seems unexpected (a bug?) to me

**Comment by hediet** [comment]
/duplicate #130297.

We can only preview snippets that are extensions of the abbreviation.

`console.log` is not an extension of `log`.
