### ISSUE TITLE
Ao fazer alteração no arquivo aparece um número que se multiplica de acordo com o que eu altero.

### ISSUE THREAD

**Issue by VitorMeloDS** [microsoft/vscode#144487]
### Here below is a link to a video with a real example of what my PC looks like.. 👇🏾 

<a href="https://www.youtube.com/watch?v=hEOoEvAmojw">Link to video</a>

**Comment by brunovieira97** [comment]
Hello, @VitorMeloDS! Just so you know, that's a functionality of the Power Mode extension.
You should refer to the extension authors on how to disable the "combo meter".

You can see it demonstrated here: https://github.com/hoovercj/vscode-power-mode

**Comment by VitorMeloDS** [comment]
Obrigado, @brunovieira97 eu percebi que era por causa da extensão mais irei ficar sem ela mesmo, de toda forma obrigado!
