### ISSUE TITLE
Glob patterns `**/p*` incorrectly match on `/foo/ap`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#144458]
VSCode is implement its own solution for glob pattern matching and does not rely on a 3rd party module. The reasons are mostly historic but our glob patterns also behave slightly different compared to others (e.g. `**/foo.txt` matches on `foo.txt`, both backslash and slash are supported). 

Our glob matching works in 2 stages:
* if it matches a typical pattern (such as `**/*.js`), we optimize the matching to avoid a regex use ([from here](https://github.com/microsoft/vscode/blob/c7fcb30b39f4d6bbfede3dad767a7ad86a7f07eb/src/vs/base/common/glob.ts#L258-L263))
* otherwise we try to convert the pattern into a single regex to match ([from here](https://github.com/microsoft/vscode/blob/c7fcb30b39f4d6bbfede3dad767a7ad86a7f07eb/src/vs/base/common/glob.ts#L451-L461))

Specifically for the conversion of `**` to a regular expression we have a flaw that results in the issue at hand here, the regex is:

https://github.com/microsoft/vscode/blob/c7fcb30b39f4d6bbfede3dad767a7ad86a7f07eb/src/vs/base/common/glob.ts#L57-L60

Or specifically for `**/p*` ends up to be:

```
/^(?:[/\\]|[^/\\]+[/\\]|[/\\][^/\\]+)*?p[^/\\]*?$/
```

Unfortunately, given a string of `/foo/ap`, the segment `[/\\][^/\\]+` eagerly matches on `/a` and as such, the overall result is a match, even though that is unexpected.

**Help wanted**
Opening up for others to contribute, the solution should:
* preserve our tests for globs to succeed ([`glob.test.ts`](https://github.com/microsoft/vscode/blob/789bbca6d0d7fd3196eec6a093a2f8e9138cca73/src/vs/base/test/common/glob.test.ts#L12))
* enable the now skipped test to succeed ([code](https://github.com/microsoft/vscode/blob/789bbca6d0d7fd3196eec6a093a2f8e9138cca73/src/vs/base/test/common/glob.test.ts#L728))
* somewhat preserve our strategy for computing a single regex for matching [1]

[1] however if this is not possible, I am also open for ideas how to solve this differently if the solution is not overly complex.

**Comment by jeanp413** [comment]
Created a PR #144473 with a possible fix
