### ISSUE TITLE
Option to duplicate file/folder in "explore" sidebar and then rename

### ISSUE THREAD

**Issue by melanierichards** [Microsoft/vscode#14449]
- VSCode Version: 1.6.1
- OS Version: Windows 10 (14393)

Would like to be able to right click on a file/folder in the explore sidebar and have the option to duplicate and rename that item. Thanks!

(I looked through open issues and didn't see this but apologies if I missed it)

**Comment by coreh** [comment]
Yeah a shortcut for that would be good, right now whenever I need that I need to Cmd + C and Cmd + V, then rename the new file (Which gets a .1 appended at the end)

**Comment by vannleonheart** [comment]
Yeah +1 for this feature, it will be very helpful, Thanks

**Comment by thisislawatts** [comment]
Ahead of this being integrated this [Duplicate File extension](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-duplicate) from @mrmlnc does the job 👌

**Comment by walpek** [comment]
@thisislawatts I think that extension will only duplicate files and not folders.

**Comment by jeffreysbrother** [comment]
Yes, this is a very good idea.
