### ISSUE TITLE
Deep copy variables during debug

### ISSUE THREAD

**Issue by boardofchris** [microsoft/vscode#144430]
During debugging I would like to copy a variable's ENTIRE value for inspection. This was broken in February 2022 (version 1.65) for nodejs and perhaps other languages as well.

The behavior now is to copy the variable display value. For longer values it truncates the result with a .... This breaks the variable format and omits part of the variable value.

See Advanced copy variable values in debugger #27950 for the original feature request.

**Comment by roblourens** [comment]
I think this would be in js-debug, did anything change @connor4312?

**Comment by boardofchris** [comment]
The issue appeared after updating VSC and persisted through a several application restarts. It then resolved itself without anything I've done. A second VSC update occurred a few days later and was without issue. 

Not a VSC issue.
