### ISSUE TITLE
VS Code terminal confused with custom bash prompt

### ISSUE THREAD

**Issue by Fortschrittarier** [microsoft/vscode#144400]
Issue Type: <b>Bug</b>

I changed the colors of my bash prompt and added a newline :

#### .bashrc
'''bash
if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[47m\]\[\033[01;34m\]\w\$\n\[\033[1;30m\]\[\033[48;5;252m\]>>>>\[\033[00m\] '
else
...
'''

In the Ubuntu terminal it looks fine.

In the VS Code terminal the background of the current working directory ("\w") is a very dark grey and the path is basicly invisible.

Pressing "Enter" without any command changes nothing. Calling for example "uname -a" works and changes also nothing.

When I do "ls"  files are shown as expected but the entire line after ">>>>" becomes also dark grey as above and stays like that. Entered text in this line has no background, only the rest of the line stays grey.

Example ([...] means dark grey background):

    cinpro@cinpropc:[~/dev/tmp/cu$]
    >>>> ls
    build  CMakeLists.txt  lib  src  test
    cinpro@cinpropc:[~/dev/tmp/cu$]
    >>>> asdf[                                                                                ]

Thanks anyway for VS Code ;-)

Regards
Alexander

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:36.248Z)
OS version: Linux x64 5.13.0-30-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4500U with Radeon Graphics (6 x 2370)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 0, 0|
|Memory (System)|7.76GB (2.15GB free)|
|Process Argv|--unity-launch --crash-reporter-id 755c4435-2713-4a44-a76b-5da3fc19dbdb|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.5.0
cucumberautocomplete|ale|2.15.1
gitignore|cod|0.7.0
doxdocgen|csc|1.4.0
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|12.0.1
gitkraken-authentication|git|1.0.3
better-cpp-syntax|jef|1.15.13
vscode-docker|ms-|1.20.0
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc008:30440022
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvidc:30447482
helix:30440343
vsnot107:30443614

```

</details>

**Comment by meganrogge** [comment]
what color theme are you using for VS Code? With that in my `.bashrc` file, I have no such issue.
![Screen Shot 2022-03-04 at 10 24 55 AM](https://user-images.githubusercontent.com/29464607/156800818-ec558b58-19e6-4575-a6aa-e131dfb9d505.png)

**Comment by Fortschrittarier** [comment]
Hi, thanks for your reply. Please see the screenshots:

Terminal:
![terminal](https://user-images.githubusercontent.com/42855173/156990545-1c1fd734-d7b9-4ceb-a450-b70a8e282a3b.png)

VS Code - Light (Visual Studio - C/C++):
![light](https://user-images.githubusercontent.com/42855173/156990646-e20a0a10-8d43-45f6-8670-5d3ec13b2331.png)

VS Code - Dark (Visual Studio - C/C++):
![dark](https://user-images.githubusercontent.com/42855173/156990724-acb21822-f3ce-46dc-8b7a-d8d51110cb10.png)

Bash version:

    cinpro@cinpropc:~$
    >>>> bash --version
    GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
    Copyright (C) 2019 Free Software Foundation, Inc.

This is an Ubuntu 20.04 ran in Virtual Box 6.1 on Kubuntu 20.04.

**Comment by Fortschrittarier** [comment]
I just found out that the problem might not be specific to the VS Code terminal:

Ubuntu terminal:
![terminal_strange](https://user-images.githubusercontent.com/42855173/156996904-48762d1a-3461-4a84-9b78-719edaf29f86.png)

Please reject the issue if you think so, too.

**Comment by meganrogge** [comment]
this is working as designed based on the prompt that you've written. The foreground color is blue because `34` is used and the background color is white because `47` is used.
