### ISSUE TITLE
Shell decoration: show the last return code status on current prompt

### ISSUE THREAD

**Issue by warpdesign** [microsoft/vscode#144412]
The decoration on current prompt, shows the status of current command execution.

The problem is that if you execute a command that produces a long output, in order to see the status of the just executed command and/or copy its output, the user has to scroll all the way up to the previous prompt in order to see its decoration.

I wish the decoration on the active prompt/line would actually show the status code of the `previous command that was run`.

What this means is that if you execute some command which produces a long output (taller than the terminal height), once it returns and you get your prompt back, the decoration you will see would be the status of `the previous command`: you don't have to scroll all the way up to see what was the status of your command and/or copy its output.

**Comment by Tyriar** [comment]
That's how you would do it with a traditional prompt but it would be pretty confusing if it was like that here. You should use cmd+up/down to quickly see what the exit code if you need it, or keep an indicator in your regular prompt
