### ISSUE TITLE
[Request] Keybinding / scriptability of target pane for opening file with Ctrl/Cmd-P

### ISSUE THREAD

**Issue by Phrohdoh** [Microsoft/vscode#14443]
- VSCode Version: 1.6.1
- OS Version: macOS Sierra (10.12)

I think it would be quite useful if users could open a file directly into the right pane instead of opening said file then dragging the tab to the right part of the screen.

I am really requesting this so that I can eventually get behaviour similar to `:vnew` in https://github.com/VSCodeVim/Vim.

```
:[N]vne[w] [++opt] [+cmd] [file]			*:vne* *:vnew*
		Like |:new|, but split vertically.  If 'equalalways' is set
		and 'eadirection' isn't "ver" the windows will be spread out
		horizontally, unless a width was specified.
```

**Comment by kaiwood** [comment]
You can. Just hold CMD down before pressing Return. ;)

**Comment by Phrohdoh** [comment]
You are right! I could have swore I tried that.
I'll close this then.
