### ISSUE TITLE
snippet's prefix is number or some characters would not trigger tips

### ISSUE THREAD

**Issue by Equis17** [microsoft/vscode#144495]
Does this issue occur when all extensions are disabled?: Yes/No

Issue Type: Bug

- VS Code Version: 1.65.0 (Universal)
- OS Version: macOS Big Sur 11.0.1

Steps to Reproduce:

1. create snippet
`
".": {
		"prefix": ".",
		"body": [
			"/",
		],
		"description": ". to /"
	},
"2 to |": {
		"prefix": "q2",
		"body": [
			"|",
		],
		"description": "2 to |"
	},
",": {
		"prefix": ",",
		"body": [
			".",
		],
		"description": ", to ."
	},
`

<img width="553" alt="image" src="https://user-images.githubusercontent.com/38281455/156913399-23057316-14a1-4f87-b28b-9b56f5ef347e.png">
<img width="333" alt="image" src="https://user-images.githubusercontent.com/38281455/156913427-fb6cc1f5-146a-4f8d-8114-fccbceed1e02.png">
<img width="337" alt="image" src="https://user-images.githubusercontent.com/38281455/156913436-1457de00-f81c-489c-8619-02bc0bc2be5f.png">

**Comment by jrieken** [comment]
1. what languages is this?
1. does this work when invoking snippets manually via `ctrl+space`
