### ISSUE TITLE
VS Code crashes itself and ALL open apps on macOS Monterey

### ISSUE THREAD

**Issue by mikew67** [microsoft/vscode#144492]
Issue Type: <b>Bug</b>

Follow Nordic's nRF Connect installation instructions for installing their SDK v1.9.1, followed by VS Code and their extension, nRF Connect for VS Code, instructions.  Then add the hello_world sample app from their samples and build it.  That results in the VS Code window and panes shown in the screen shot below.  Note the bold text at the bottom right: "Terminal will be reused by tasks, press any key to close it."  If you then click in the Terminal pane to give it focus and type a character, VS Code will immediately crash AND take down all other open macOS apps, INCLUDING the Finder.  A macOS reboot is required.

This bug has persisted for about a year, through several versions of all the associated software components.  I have previously reported it to Nordic, but they disclaimed any responsibility, noting that I was using a patched version of macOS (in order to run macOS Monterey on my 2013 MacBook Pro 10,1).  But, later another user with a current MacBook Pro noted the same problem.

VS Code version: Code 1.65.0 (Universal) (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:11:20.886Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id 94c6693f-eee7-478f-91be-1245de31115e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
esp-idf-extension|esp|1.4.0
oneapi-samples|int|0.0.43
vscode-circuitpython|joe|0.1.15
cortex-debug|mar|1.2.2
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.0
jupyter|ms-|2022.2.1020642448
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
vsliveshare|ms-|1.0.5418
nrf-connect|nor|2022.1.192
nrf-connect-extension-pack|nor|2021.9.1
nrf-devicetree|nor|2022.1.153
nrf-kconfig|nor|2022.1.78
nrf-terminal|nor|2022.1.30
platformio-ide|pla|2.4.2
gnu-mapfiles|tro|1.1.0
cmake|twx|0.0.17
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrt:30448491
vsrem710cf:30416617
dsvsc008:30440022
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343

```
![VS Code screen just before macOS crash](https://user-images.githubusercontent.com/1269461/156906554-3b721935-e613-4c39-9732-548b0338c10f.jpg)

</details>

**Comment by deepak1556** [comment]
Can you attach the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports

**Comment by milspect18** [comment]
I have experienced the same issue.  I launched code with the crash reporter directory argument, but no logs were produced.  

VS Code info:
```
Version: 1.65.2 (Universal)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.4.0
```

Host system:
```
2021 Macbook Pro 16
M1 Pro
macOS v12.3
```

***Conditions***
I am using VS Code with openocd and GDB for debugging an embedded C application via a PicoProbe.  The debug session works as expected.  After stopping the debug session, any interaction with the terminal (input or closing) or attempting to close VS Code will result in the crash of all open programs as well as finder.  This results in a black screen which will re-display the desktop after a second.

***More Information***
The terminal after successful debug session looks as follows:
<img width="743" alt="image" src="https://user-images.githubusercontent.com/10535192/158710613-aa341354-3be4-49f4-8405-a905e0d3a6e2.png">

**Comment by mikew67** [comment]
"Lack of information"?  "Crash logs"?  Sorry, this crash is too severe to produce any crash logs.  Only reasonable action possible is to reboot.
Having said that, I should note that the most recent time I had VS Code in a similar state, it DID NOT crash, but behaved as expected.  Not sure if a recent update to VS Code or some other extraneous factor was responsible.

**Comment by scotthosking** [comment]
I'm having the same issue on my mac. I open up VS Code and it crashes, then causes other apps to crash. I then need to do a hard reset of the machine.

**Comment by mikew67** [comment]
Updating to the latest VS Code release (or maybe macOS updates during the same time period) solved this issue for me.

HTH,

Mike

**Comment by devcula** [comment]
I am still facing this issue. Getting all the latest updates didn't work. Any other solution?
