### ISSUE TITLE
Can not uninstall a extension dependecy but can disable it

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#14440]
Testing #14291.
- install '999 Martins Favorite Extensions'
- try to uninstall the 'CSS Formatter'. Error dialog says 

>  Cannot uninstall extension 'CSS Formatter'. Some of the installed extensions depends on this.

But I can disable the extension.

Any strong reason why I can't uninstall the extension?

**Comment by sandy081** [comment]
@aeschli That's a good one. Only reason is that other dependent extensions will break if it is uninstalled. This is also true for disabling which we should think about.

@joaomoreno FYI

**Comment by joaomoreno** [comment]
Don't deny uninstalling it. Make it a prompt. Same for disabling.

**Comment by ramya-rao-a** [comment]
What does disabling an extension pack even mean? The dependent packages do not get disabled when the pack is disabled. Maybe we shouldnt have the disable option on an extension pack

**Comment by joaomoreno** [comment]
Problems come when we think of _packs_ as first class citizens. It becomes easier when we drop the notion of packs and just think about extensions individually, and its dependencies. You should be able to disable any extension you'd like, regardless of it having dependencies.

**Comment by ramya-rao-a** [comment]
my bad, I keep forgetting that non-pack extensions have extension dependencies as well.
