### ISSUE TITLE
frozen. Cannot work on anything.

### ISSUE THREAD

**Issue by Landl3ss** [microsoft/vscode#144457]
ADD ISSUE DESCRIPTION HERE

Version: 1.65.0
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
Embedder: codespaces

**Comment by Landl3ss** [comment]
I was writing and running my code I was creating an output.txt file because my code outputs a lot and I wanted to see what was happening. I would then delete my output file and run it again. Then it started getting slow and started disconnecting. But now it won't even come up. Just frozen and non responsive.

**Comment by weinand** [comment]
What programming language are you using?
How are you running your code?

**Comment by Landl3ss** [comment]
the problem doesn't seem to exist anymore. I was using C language.
