### ISSUE TITLE
Window position gets messed up when you open a text file from terminal in Linux

### ISSUE THREAD

**Issue by steel-steven-87** [microsoft/vscode#144462]
Does this issue occur when all extensions are disabled?: Yes (clean install of vscode on a clean install of Kubuntu)

Version: 1.65.0 (can also be reproduced in 1.66.0-insider)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-30-generic snap (Kubuntu 21.04)

Steps to Reproduce:

1. Open VSCode.
2. Maximize the window.
3. Minimize the window.
4. Open a file from inside of a terminal, e.g. `code test.txt`.

The window gets restored, but it is not maximized anymore. Window position and size gets messed up randomly.

**Comment by steel-steven-87** [comment]
Attaching a recording. You can see that the window was maximized, but when you open a file, it is not maximized anymore. You have to maximize the window every time you open a new file.

![recording](https://user-images.githubusercontent.com/89798696/157316621-b0526657-744f-4371-9bc7-56bce0ee510a.gif)

**Comment by bpasero** [comment]
Does the same happen when you click on the icon in the task bar after the window is minimized?

**Comment by steel-steven-87** [comment]
> Does the same happen when you click on the icon in the task bar after the window is minimized?

It doesn't happen when you click the icon to restore the window.

The position gets messed up only when you open a file. This also happens if you have a file association to open text files with VSCode and double click on a file. So, this affects the daily use of VSCode since any file you open will unmaximize the window.

**Comment by bpasero** [comment]
This sounds like an Electron issue to me, in the end we simply call this method to make sure the window has focus:

https://github.com/microsoft/vscode/blob/e9f5380d4f8c3360b130c79fa5aafb88991f68d4/src/vs/platform/windows/electron-main/window.ts#L341-L362

@deepak1556 any advice?

**Comment by bpasero** [comment]
I think `this._win.restore();` does the wrong thing then and does not preserve the maximized bit.
