### ISSUE TITLE
Latest version breaks Git Bash integration on Windows 10.

### ISSUE THREAD

**Issue by kyle-goodwin** [microsoft/vscode#144414]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0
- OS Version: Windows 10

Steps to Reproduce:

1. Update to 1.65.0

Latest update broke Git Bash integration. Git Bash no longer appears in the list of available terminals. "Git Bash" is not longer a valid option for "terminal.integrated.defaultProfile.windows". The Internet suggests adding a terminal by setting the path in "terminal.integrated.shell.windows" but that appears to no longer be an option.

![image](https://user-images.githubusercontent.com/45823898/156795718-9f0f3df9-d6a0-429d-90ab-282bb74c166e.png)

Setting the path in "terminal.integrated.automationProfile.windows" makes bash the default but it still does not appear in the list of options. Also every time I start VSCode I get a new terminal session below the old one which I cannot clear.

![image](https://user-images.githubusercontent.com/45823898/156796135-a4e278da-47dc-4eb7-b6e7-d11c07299570.png)

**Comment by AnrDaemon** [comment]
Remove `terminal.integrated.shell.***` entirely, see the note in the property description.

**Comment by kyle-goodwin** [comment]
> Remove `terminal.integrated.shell.***` entirely, see the note in the property description.

Removing the line does not solve the problem. The property description says:

`recommended way to configure your default shell is by creating a terminal profile in `#terminal.integrated.profiles.windows#` and setting its profile name as the default in `#terminal.integrated.defaultProfile.windows#`.`

I cannot set the name in `terminal.integrated.defaultProfile.windows` as it only accepts the default values. The note for this property also references deprecated properties: `terminal.integrated.shell.windows` or `terminal.integrated.shellArgs.windows`.

**Comment by kyle-goodwin** [comment]
The configuration as described in here https://code.visualstudio.com/docs/editor/integrated-terminal does not work.
![image](https://user-images.githubusercontent.com/45823898/156889551-a07ede78-86ed-4399-9710-9eacadb60c87.png)

The only configuration that functions partially is using the deprecated "terminal.integrated.shell.windows". I would still prefer it function as it did prior to the update.

**Comment by meganrogge** [comment]
Try to restart vscode or re-install git to the default directory. We're not sure why the configuration you tried above is not working for you.

Does it work if you use a different name, IE `Git bash 2`?
