### ISSUE TITLE
Hard to click on a web link in VSCode: zone is too small

### ISSUE THREAD

**Issue by VashJuan** [microsoft/vscode#144428]
Issue Type: <b>Bug</b>

Enter a routine "https://blah.com" link in the code, or terminal window. Then try to Ctrl-Click on it. Even with a large 4K screen and a mouse, the area to click on is only ~5-10px high: really hard to find.

Hovering over the actual text won't work (surprisingly), one has to go just underneith, pretty much on the underline (text-decoration) only.

VS Code version: Code - Insiders 1.66.0-insider (6dca4c1a1f7bb3529074601eb32938526fa9ecc7, 2022-03-04T05:15:52.197Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (15.26GB free)|
|Process Argv|--crash-reporter-id ae21117e-22b4-42cf-9530-e93c75e8c52d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (95)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.9.1
better-comments|aar|2.1.0
csharp-to-typescript|adr|1.12.1
project-manager|ale|12.5.0
tsco|alj|1.0.20
iis-express-executer|And|1.2.5
ng-template|Ang|13.2.4
material-icons|Arc|0.2.0
vscode-django|bat|1.10.0
markdown-preview-github-styles|bie|1.0.1
linkcheckerhtml|Bil|6.3.0
vscode-ripgrep|bok|0.2.2
xml2json|bui|1.2.4
path-intellisense|chr|2.8.0
gitignore|cod|0.7.0
angular-schematics|cyr|5.1.1
vscode-markdownlint|Dav|0.46.0
jshint|dba|0.11.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
xml|Dot|2.5.1
dotup-vscode-interface-generator|dot|1.0.15
vscode-generate-getter-setter|DSK|0.5.0
gitlens-insiders|eam|2022.3.304
vscode-html-css|ecm|1.11.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|2.2.1
ng-evergreen|exp|2.1.1
file-icons|fil|1.0.29
vscode-firefox-debug|fir|2.9.6
vscode-angular-html|gha|1.7.0
vscode-pull-request-github|Git|0.36.2
gitkraken-authentication|git|1.0.3
gc-excelviewer|Gra|4.0.50
json2ts|Gre|0.0.6
todo-tree|Gru|0.0.215
debug-visualizer|hed|2.2.4
realtime-debugging|hed|0.1.0
vscode-drawio|hed|1.6.4
vscode-power-mode|hoo|3.0.1
fontawesome-autocomplete|Jan|1.1.2
plantuml|jeb|2.17.2
angular-essentials|joh|12.0.0
Angular2|joh|12.0.0
pwa-tools|joh|0.1.0
vscode-peacock|joh|4.0.0
vscode-icon-theme|jtl|1.6.6
vscode-map-preview|jum|0.5.9
sftp|lix|1.12.10
ts-extension-pack|loi|0.3.0
materialdesignicons-intellisense|luk|4.0.0
git-graph|mhu|1.30.0
formate|Mik|1.2.1
vscode-kanban|mkl|1.32.0
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.0
jupyter|ms-|2022.2.1020642448
remote-containers|ms-|0.225.0
remote-wsl|ms-|0.64.2
powershell-preview|ms-|2022.2.2
vscode-typescript-next|ms-|4.7.20220303
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-edge|msj|1.0.15
microsoft-office-add-in-debugger|mso|0.2.0
printcode|nob|3.0.0
angular-console|nrw|17.14.1
prettier-standard-vscode|num|0.9.2
codemap|ole|1.16.2
vscode-print|pdc|0.9.14
tsimporter|pmn|2.0.1
vscode-powerquery|Pow|0.1.27
prettyxml|Pra|1.4.0
resxpress|Pra|4.4.0
typescript-hero|rbb|3.0.0
vscode-yaml|red|1.4.0
LiveServer|rit|5.7.4
synthwave-vscode|Rob|0.1.11
partial-diff|ryu|1.4.3
rainbow-fart|sae|1.4.1
xml-toolkit|SAP|1.1.0
html-to-css-autocompletion|sol|1.1.2
vba|spe|1.7.1
move-ts|str|1.12.0
open-in-browser|tec|2.0.0
dnn-theming-snippets|the|0.0.6
vscode-pets|ton|1.10.0
vscodeintellicode|Vis|1.2.17
vscode-icons|vsc|11.10.0
quokka-vscode|Wal|1.0.449
html-snippets|wge|0.1.5
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2
vscode-as-git-mergetool|zaw|0.14.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstartedc:30421358
vsclayoutctrt:30405800
dsvsc009:30440021
pythonvspyt640:30438691
vsbas813:30436447
vscscmwlcmt:30428973
azactmsal:30432848
vscgsvid1:30433757
dockersurvey3cf:30438169
pynewfile477cf:30443520

```

</details>

**Comment by VashJuan** [comment]
I'm trying to come up with a nice example: it is not pervasive!

**Comment by gjsjohnmurray** [comment]
Please check whether the issue also occurs after you run the command to reload with all extensions disabled.

**Comment by VashJuan** [comment]
Sorry for the false alarm. I'll reopen if I can resolve it. (I had seen it a bunch, but maybe the March update resolved it?!)
