### ISSUE TITLE
Can't turn on setting sync, Error while turning on Settings Sync. No authentication providers are available.

### ISSUE THREAD

**Issue by needhourger** [microsoft/vscode#144471]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: visual-studio-code-bin 1.65.0-1
- OS Version: Manjaro kde 

Steps to Reproduce:

1. install vscode through yay from AUR
2. open it and try to trun on settings sync
3. Click on the account button but there is no reaction.
4. try to trun on setting sync from start page,  and it will say: "Error while turning on Settings Sync. No authentication providers are available."

In all , I can't turn on  settings sync using github account or microsoft account.

**Comment by theodiv** [comment]
I also had the exact same problem after applying the same update in Arch Linux. I solved by installing gnome-keyring libsecret libgnome-keyring.

**Comment by blender222** [comment]
I also had same problem. I solved by installing VS Code 1.64.2 Version.

**Comment by needhourger** [comment]
> I also had the exact same problem after applying the same update in Arch Linux. I solved by installing gnome-keyring libsecret libgnome-keyring.

Wow, that's work for me too. Eventhrough my desktop application is kde. thank you very much.
But I wonder is that the correct solutions to this issue.
it does make sync work again, but it tell me to set  and store a new keyring which i never came across before.

**Comment by theodiv** [comment]
> But I wonder is that the correct solutions to this issue.

I really don't know, but it makes sense to me because when I run vscode through the command line using `$ code --verbose`, when I clicked the account button it thrown an error/warning reading: "The name org.freedesktop.secrets was not provided by any .service files". In many desktop environments, gnome-keyring is the one that provides org.freedesktop.secrets, and I believe it is safe to use it as an alternative to KDE.

> it tell me to set and store a new keyring which i never came across before

On first run, gnome-keyring creates the default keyring, which is used by applications to store tokens and passwords. VSCode also stores a token there when doing a first sync. You can read more about gnome-keyring in the official Arch documentation located at [https://wiki.archlinux.org/title/GNOME/Keyring](url).

**Comment by mukaschultze** [comment]
Same issue here also on Manjaro. Installing `gnome-keyring`, `libsecret`, and `libgnome-keyring` does work but seems a little hacky

**Comment by sandy081** [comment]
It seems this offering is not an official offering from VS Code. Please file an issue against the package provider offering this.

**Comment by mukaschultze** [comment]
@sandy081 care to explain how this is not an official feature from VS Code? Both the settings sync feature and GitHub auth provider are built-in in VS Code.

**Comment by terminal-root** [comment]
I used the official deb package from the [VS Code website](https://code.visualstudio.com/), and I am getting the same error. @sandy081 
```
Error while turning on settings sync. No authentication providers...
```

**Comment by sandy081** [comment]
@mukaschultze No authentication providers error implies that offering is not complete and missing some info from the `product.json`.

> Installing gnome-keyring via apt solves the issue. It seems gnome-keyring should be included as a dependency in the .deb package.

Interesting to know. CC @TylerLeonhardt for this.

**Comment by TylerLeonhardt** [comment]
It's a tough one because gnome-keyring isn't a dependency... our dependency is "anything that implements org.freedesktop.secrets API which is gnome-keyring, kwallet, or KeePassXC...

gnome-keyring is the easiest to set up but not everyone wants that.

**Comment by mukaschultze** [comment]
@TylerLeonhardt makes sense, but I still have some questions:

1. Why is this happening happening now? I've used settings sync before without having any of those installed (only `libsecret`) and it worked just fine.
2. If adding `gnome-keyring` as a dependency is not viable (which I agree), wouldn't at least be possible to show a proper error message instead of the generic `No auth providers`? This message just adds to the confusion instead of actually informing the user of what's happening

**Comment by TylerLeonhardt** [comment]
> Why is this happening happening now? I've used settings sync before without having any of those installed (only libsecret) and it worked just fine.

It's a good question. I did make some changes around error handling so it's possible that we are now throwing when we didn't in the past... but best case if you didn't have one of those installed, it would fail silently and on reload of the window you'd lose your session.

> No authentication providers are available

@sandy081 can you give me more context on this error message? Maybe I can throw an error for you about this so this error can be better surfaced to the user?

**Comment by sandy081** [comment]
I am not sure if I can show the errors from the auth extension but the message can be improved and give guidance to user to look at auth extensions in the extensions view.

**Comment by mukaschultze** [comment]
> give guidance to user to look at auth extensions in the extensions view

The problem is not with the auth providers, it's about the app dependencies.

The `authenticationProviders` is empty because something else is preventing it from initializing, most likely the `getCurrentAuthenticationSessionInfo` method below is throwing an error and preventing the `updateAuthenticationProviders` from being called, which would, in turn, result in the array having the default value of `[]`.

https://github.com/microsoft/vscode/blob/757b70873ecff24b138b3d0c9c5bc8896c5ecc89/src/vs/workbench/services/userDataSync/browser/userDataSyncWorkbenchService.ts#L171-L180

This is a wild guess from looking at the code where the error is thrown and trying to guess the reason behind it. I have no experience in the vscode codebase.

**Comment by vnylbscr** [comment]
> > I used the official deb package from the [VS Code website](https://code.visualstudio.com/), and I am getting the same error. @sandy081
> > ```
> > Error while turning on settings sync. No authentication providers...
> > ```
> 
> Installing `gnome-keyring` via apt solves the issue. It seems `gnome-keyring` should be included as a dependency in the .deb package.

Thanks. Installing gnome-keyring solved my issue.

**Comment by TylerLeonhardt** [comment]
To the folks who just installed gnome-keyring and it worked...

Before you did that and before the most recent update that caused the Accounts from not loading... did your credentials persist when you restarted vscode?

**Comment by JunkuiZhang** [comment]
It seems that vscode uses gnome key-ring to save the credentials of the users, but KDE based linux distributes use KDE Wallet for credentials, which GNOME Key-ring is not installed by default.
Install gnome-keyring can solve this problem.

**Comment by terminal-root** [comment]
> It seems that vscode uses gnome key-ring to save the credentials of the users, but KDE based linux distributes use KDE Wallet for credentials, which GNOME Key-ring is not installed by default.
> Install gnome-keyring can solve this problem.

I believe that solution has been established in this thread. The problem with it is that KDE users should not have to use gnome-keyring.

**Comment by TylerLeonhardt** [comment]
@terminal-root take a look at this thread:

https://github.com/microsoft/vscode/issues/104319#issuecomment-1057588052

That's all covered there. 

What I need to know is what happened before this version. You didn't have gnome-keyring installed before so how did it work? Did your sign in state persist when you quit vscode?

**Comment by terminal-root** [comment]
> @terminal-root take a look at this thread:
> 
> [#104319 (comment)](https://github.com/microsoft/vscode/issues/104319#issuecomment-1057588052)
> s
> That's all covered there.
> 
> What I need to know is what happened before this version. You didn't have gnome-keyring installed before so how did it work? Did your sign in state persist when you quit vscode?

Thank you for the link @TylerLeonhardt. I do not believe my sign-in state persisted. This menu would not show up upon clicking the Accounts icon while not having gnome-keyring installed.

![Visual Studio Code Accounts Menu](https://user-images.githubusercontent.com/24536673/159282889-e3f6b12a-0dda-46b7-b0da-f7aff9e5e0b6.png)

---

I removed gnome-keyring, killed the process, and restarted VS Code to take another look.

The sign-in state did not persist. The Accounts icon appears with a notification counter and tooltip saying "Accounts - Sign In Requested".

![image](https://user-images.githubusercontent.com/24536673/159284439-c056a524-98fb-4b47-a9a5-a5fe4c199f1c.png)
(couldn't get the tooltip in the screenshot)

Also, things like Live Share and GitHub Classroom are prompting for sign-in.

Hope that helps.

**Comment by TylerLeonhardt** [comment]
/duplicate https://github.com/microsoft/vscode/issues/145282

We now show a notification that points to a doc that will mention installing gnome-keyring. The notification use to be there, but a somewhat recent change prevented it from showing up. Now it shows up.

**Comment by zf1976** [comment]
opensuse: sudo zypper install libgnome-keyring

**Comment by evildom** [comment]
> I also had the exact same problem after applying the same update in Arch Linux. I solved by installing gnome-keyring libsecret libgnome-keyring.

it worked for kubuntu 22.04 thanks a lot bro!

**Comment by baimahambetov** [comment]
> > I also had the exact same problem after applying the same update in Arch Linux. I solved by installing gnome-keyring libsecret libgnome-keyring.
> 
> it worked for kubuntu 22.04 thanks a lot bro!
How did u installed?

**Comment by baimahambetov** [comment]
> it worked for kubuntu 22.04 thanks a lot bro!

How did you installed?

**Comment by wiredhikari** [comment]
Same error on nixos(without a desktop environment). Installing  gnome-keyring, libsecret, and libgnome-keyring didnt work.

**Comment by TylerLeonhardt** [comment]
@wiredhikari what do you mean by "without a desktop environment"?

**Comment by wiredhikari** [comment]
> @wiredhikari what do you mean by "without a desktop environment"?

I am running only awesome window manager (no kde,gnome)

**Comment by evildom** [comment]
> > it worked for kubuntu 22.04 thanks a lot bro!
> 
> How did you installed?

sudo apt-get install gnome-keyring

**Comment by TylerLeonhardt** [comment]
@wiredhikari my guess is that the keyring isn't getting unlocked or the secret service provided by libsecret isn't launching properly... you may have to do some digging around awesome wm & libsecret or gnome-keyring. I'll try to do some digging on my side but you might have more context than I since you have context on awesome wm.

**Comment by wiredhikari** [comment]
> @wiredhikari my guess is that the keyring isn't getting unlocked or the secret service provided by libsecret isn't launching properly... you may have to do some digging around awesome wm & libsecret or gnome-keyring. I'll try to do some digging on my side but you might have more context than I since you have context on awesome wm.

Ya sure I will try figuring it out and let you know how it goes.

**Comment by wiredhikari** [comment]
@TylerLeonhardt  Ok so I had to enable gnome-keyring daemon and it works fine.
