### ISSUE TITLE
MalwareBytes breaks VSCode installer

### ISSUE THREAD

**Issue by milnak** [microsoft/vscode#144446]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65
- OS Version: Windows 11 21H2 (22000.493)

Steps to Reproduce:

1. Install MalwareBytes trial with real-time protection
2. Ensure Ransomware protection is ON (right click task bar icon to verify.
3. Run VS Code User installed, with all defaults.
4. You should get a MoveFile error 183 during installation.
5. Cancel install.
6. Now right click MalwareBytes taskbar icon and turn OFF Ransomware protection.
7. Rerun VS Code User installer.
8. Install should work.

**Comment by joaomoreno** [comment]
We'd appreciate if you could let MalwareBytes know that their application prevents harmless applications from installing. This is not an issue with VS Code.
