### ISSUE TITLE
"files.simpleDialog.enable": true, not honored on web

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#144439]
Version: 1.66.0-insider
Commit: 6dca4c1a1f7bb3529074601eb32938526fa9ecc7
Date: 2022-03-04T05:19:16.597Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4880.0 Safari/537.36

> Enables the simple file dialog. The simple file dialog replaces the system file dialog when enabled.

Steps to Reproduce:

1. go to insiders.vscode.dev
2. apply setting `"files.simpleDialog.enable": true,`
3. Open Folder

Expected

Simple file dialog

Actual

System file dialog

@alexr00 I see your name in the code for this setting... maybe @bpasero as well since you do things in that space as well?

**Comment by bpasero** [comment]
We cannot change that, access to local files is only possible with that dialog. See https://github.com/microsoft/vscode/issues/136486
