### ISSUE TITLE
Python (Pylance) Intellisense doesn't work on many packages.

### ISSUE THREAD

**Issue by tperl-cg** [microsoft/vscode#144483]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.1 (Universal)
- OS Version: 12.2 (21D49), macOS Monterey, MacBook Air M1

Steps to Reproduce:

1. import open3d as o3d
2. When typing o3d.geometry.(should auto complete to PointCloud, Image etc.)
3. When using PyCharm or Jupiter notebook the completion does occur.

**Comment by gjsjohnmurray** [comment]
I suggest you try updating your VS Code to the current release, 1.65.

**Comment by tperl-cg** [comment]
updated to 1.65. Still completion is lacking.
