### ISSUE TITLE
camelcase text transform snippet doesn't work

### ISSUE THREAD

**Issue by ssoroka** [microsoft/vscode#144452]
example snippet 
```json
	"struct yaml tags": {
		"prefix": "yaml",
		"body": [
			"`yaml:\"${1:${CLIPBOARD/(.*)/${1:/camelCase}/}}\"`$0"
		],
		"description": "wrap an error with more context"
	},
```
Clipboard contents for Input: `ExtensionDeadline`
Expected result: `yaml:"extensionDeadline"`
Actual result: `yaml:"ExtensionDeadline"`

Seems to be specific to `/camelcase`, as `/downcase` works

**Comment by jrieken** [comment]
The format-identifier is `camelcase`, not `camelCase`
