### ISSUE TITLE
pandas groupby output reformat difficult to read

### ISSUE THREAD

**Issue by lgonzalezsa** [microsoft/vscode#144422]
Issue Type: <b>Bug</b>

Comparing vscode 1.65 vs 1.64.2 the pandas groupby output seems was reformatted and now is difficult to read.

Here minimal reproducible code and screenshots.

```
import pandas as pd
from datetime import datetime

data = {
    'start': [datetime(2018, 1,  3), datetime(2018, 3,  3), datetime(2018, 7, 15)],
    'end': [datetime(2018, 1, 31), datetime(2018, 3, 30), datetime(2018, 9, 23)],
    'start_event': ['Event 1234545567676', 'Event 2243234345', 'Event 2'],
    'end_event': ['Event1', 'Event2', 'Event2'],   
}

df = pd.DataFrame(data)

df.groupby(['start_event']).size()

```
Getting this result:
![image](https://user-images.githubusercontent.com/704686/156812023-0fccdbab-16fe-4045-8738-2550250e9f02.png)

Expected output:
![image](https://user-images.githubusercontent.com/704686/156811825-4acb437f-6b4e-4893-a117-60a21daa93ed.png)

![image](https://user-images.githubusercontent.com/704686/156811944-cc554ea7-92fa-4980-8720-7bdde3c6298f.png)

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:36.248Z)
OS version: Linux x64 5.16.11-76051611-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.24GB (0.25GB free)|
|Process Argv|--unity-launch --crash-reporter-id d47ba435-3be3-4834-8f45-d41f283cb19c|
|Screen Reader|no|
|VM|24%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitkraken-authentication|git|1.0.3
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.0
jupyter|ms-|2022.2.1020642448
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
code-spell-checker|str|2.1.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc009:30440023
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343

```

</details>

**Comment by rebornix** [comment]
Already fixed in Insiders and will push a fix for recovery build. Thanks for the bug report!
