### ISSUE TITLE
Unable to parse content from 'https://aka.ms/terminal-profiles-schema': Parse error at offset 14830.(768)

### ISSUE THREAD

**Issue by nbros** [microsoft/vscode#144459]
With Microsoft Windows Terminal installed, either go in **Settings** and click **Open JSON file** or open VS Code directly:
`code --disable-extensions "C:\Users\$env:USERNAME\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json"`

VS Code complains about a parse error in the schema:
![image](https://user-images.githubusercontent.com/141089/156875082-43ac8b84-51b7-4141-8dcf-6fa5f73f4133.png)

But this is the official Microsoft schema and when I open this schema directly VS Code only finds warnings on trailing commas, but no errors.

---
Does this issue occur when all extensions are disabled?: *Yes*

**VS Code Version:** 
Version: 1.65.0 (user setup)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:12:08.962Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

**OS Version**
Windows 10 Pro 21H2

**Comment by sandy081** [comment]
Settings file does not support these contents, May I know why you have this content in this file?

**Comment by nbros** [comment]
This is a Windows Terminal settings file that I just opened in VS Code.

**Comment by aeschli** [comment]
It's a Windows terminal issue. I created https://github.com/microsoft/terminal/issues/12639
