### ISSUE TITLE
Add file size somewhere in the toolbar, possibly at the bottom

### ISSUE THREAD

**Issue by deepyes02** [microsoft/vscode#144416]
When selecting a file, it would be nice to have information on it's size. While working on a project, today I felt it would be really helpful, for example to see how minimized codes stand up to the development version, it could be so many things.

I was thinking the bottom blue bar has so much space and that could appear somewhere

**Comment by JacksonKearl** [comment]
Something like: https://marketplace.visualstudio.com/items?itemName=zh9528.file-size

**Comment by deepyes02** [comment]
Thank you for your response,

Is that a lot of code to write to display file size ?

I'm curious on this.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JacksonKearl** [comment]
You can view the repository for the extension I mentioned here: https://github.com/zhcode-fun/file-size/
