### ISSUE TITLE
I can't sign in with github after sign in with Microsoft

### ISSUE THREAD

**Issue by dooGitit** [microsoft/vscode#144448]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65
- OS Version: Windows 10 

Steps to Reproduce:
1. To sync, I sign in with Microsoft
2. Sign out with Microsoft for sign in with github
3. but I can't select the 'Sign in with Github' because Microsoft login page was opened.

https://user-images.githubusercontent.com/64671175/156863025-d873985c-6d65-4a46-9c0e-72ee424942f7.mp4

![image](https://user-images.githubusercontent.com/64671175/156863011-3f5d94d8-5e39-405e-a452-8c85e3b4f3dc.png)

**Comment by TylerLeonhardt** [comment]
Can you follow these steps so that we can get more information on what's going on?

* Open the Output pane (ctrl+shift+u I think on Windows)
* attach the contents of the following:
  * `Microsoft Authentication` Output channel
  * `Log (Settings Sync)` Output channel
  * `Log (Window)` Output channel

**Comment by dooGitit** [comment]
1. Microsoft Authentication 
![image](https://user-images.githubusercontent.com/64671175/156952724-14c2b09b-83cc-4867-bdf9-086eef39f160.png)

2. Log (Setting Sync)
![image](https://user-images.githubusercontent.com/64671175/156952770-de07c87a-e95b-4f79-b02a-c9e5961b819a.png)


3. Log (Window)
![image](https://user-images.githubusercontent.com/64671175/156952852-ec5b8086-4309-4e96-9a28-9b0efd83276b.png)

**Comment by TylerLeonhardt** [comment]
@dooGitit based on your logs, I don't see that you actually logged out of your Microsoft account. Can you please show me how you "Sign out with Microsoft"?

**Comment by dooGitit** [comment]
Sorry, I upload again include sign out.

1. Microsoft Authentication
![image](https://user-images.githubusercontent.com/64671175/157127701-217edadd-2b9f-4eef-beff-427a3849308e.png)

2. Log Setting Sync 
![image](https://user-images.githubusercontent.com/64671175/157127759-6c79e06d-2b8a-44f7-810c-43c89e986451.png)

3. Log (Window)
![image](https://user-images.githubusercontent.com/64671175/157127902-1f088121-805b-494b-8ab5-6d937ce8f138.png)

**Comment by TylerLeonhardt** [comment]
@sandy081 this might be on your side... from the logs it looks like even though the user signs out of Microsoft, they are not asked to choose between Microsoft and GitHub anymore and are instead taken down the path to log in with Microsoft again. Perhaps some account preference not being cleared?

**Comment by dooGitit** [comment]
@sandy081 @TylerLeonhardt Hello? can I get some answer?

**Comment by sandy081** [comment]
Trying to sign in (after signing out) I am being shown with account picker. 

@dooGitit After signing out, do you see following?

<img width="316" alt="image" src="https://user-images.githubusercontent.com/10746682/158322003-386b880e-2fca-444e-bb54-63bd3bb22e56.png">

**Comment by dooGitit** [comment]
![image](https://user-images.githubusercontent.com/64671175/158491410-68c601a8-c0d7-4de5-9c61-0419816f6b8f.png)

Yes

**Comment by sandy081** [comment]
What picker does it show when you click on this action?

**Comment by dooGitit** [comment]
I can't show anything just login page of Microsoft open.

https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?response_type=code&client_id=aebc6443-996d-45c2-90f0-388ff96faa56&response_mode=query&redirect_uri=https://vscode-redirect.azurewebsites.net/&state=vscode,80,F1Aq0pcCeZOmoXyf0lgzQQ%253D%253D,windowId%253D3&scope=email%20offline_access%20openid%20profile&prompt=select_account&code_challenge_method=S256&code_challenge=4uxgOjxuLgPFhNbVeoG_xbOiWgSIvgLhls5h8giPLHU

**Comment by sandy081** [comment]
Can you please check the status of GitHub Authentication extension?

- Go to extensions view and type `@builtin Github`

**Comment by dooGitit** [comment]
It was disabled! 
after change enable, I can sign in github. 
Thank you. 

but does the extension set disable automatically?

**Comment by sandy081** [comment]
It should not be disabled automatically. May be have you disabled it unknowingly ?

**Comment by dooGitit** [comment]
I didn’t know the extension. I had test in two computers. The results are same.
