### ISSUE TITLE
Shell integration messes up with my PATH

### ISSUE THREAD

**Issue by warpdesign** [microsoft/vscode#144407]
Issue Type: <b>Bug</b>

My `PATH` appears to be incomplete when enabling `Shell integration`: `/usr/local/bin` (in addition to other paths) is missing from `PATH`.

When shell integration is disabled, opening a new terminal and typing some commands shows the following:

> ~/Dev/react-explorer (master) ✗ > ps -p $$
>   PID TTY           TIME CMD
>  8023 ttys008    0:00.34 /bin/zsh -l
> 
> ~/Dev/react-explorer (master) ✗ > echo $PATH
> /usr/local/opt/ruby/bin:/Users/nicolas.ramz/go/bin:/Users/nicolas.ramz/.nvm/versions/node/v14.17.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin

When shell integration is enabled, here is the output of the same commands:

> Shell integration activated
> 
> ~/Dev/react-explorer (master) ✗ > ps -p $$
>   PID TTY           TIME CMD
>  8430 ttys008    0:00.32 /bin/zsh -i
> 
> ~/Dev/react-explorer (master) ✗ > echo $PATH
> /usr/local/opt/ruby/bin:/Users/nicolas.ramz/go/bin:/Users/nicolas.ramz/.nvm/versions/node/v14.17.5/bin:/usr/bin:/bin:/usr/sbin:/sbin

Notice how the `$PATH` appears to be incomplete when shell integration is enabled.

As a consequence, lots of commands, including command line tool `code` aren't found when shell integration is enabled.

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:11:20.886Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 10, 38|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 8a62a4ff-e416-46c8-bdf6-c66057d5ae5c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|12.0.1
gitkraken-authentication|git|1.0.3
vscode-pets|ton|1.10.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrt:30437039
vsrem710cf:30416617
dsvsc009:30440023
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvid2:30447481
helix:30440343
vsnot107cf:30443615

```

</details>

**Comment by AnrDaemon** [comment]
#144339 ?
