### ISSUE TITLE
Can't use MacOS shortcuts to open emoji keyboard in VSCode full screen mode

### ISSUE THREAD

**Issue by nguyendviet** [microsoft/vscode#144405]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.65.0 (Universal)
- OS Version: MacOS 12.1

Steps to Reproduce:

1. Open VSCode
2. Go to full screen mode
3. Use default shortcuts `ctrl+cmd+space`. Emoji keyboard doesn't show up.
4. If use the mouse to click on Input Source and select Show Emojis & Symbols, it will show up on top of VSCode.

Similar to #17499, #16562

**Comment by alexdima** [comment]
This reproduces in all software on macOS and is controlled by a macOS setting. Please see https://github.com/microsoft/vscode/issues/135480#issuecomment-963946617 . Please also see https://github.com/microsoft/vscode/issues/144010#issuecomment-1054320641

**Comment by nguyendviet** [comment]
Thank you @alexdima . I checked the comment and I do have the setting for `Change input source`. However, this seems like a MacOS' issue, not VSCode's issue. I believe the emoji keyboard was opened but it was placed in a different workspace. That's why I couldn't "call" it in the workspace where I had my VSCode.
