### ISSUE TITLE
Having Invalid extension id results in 'Server returned 400'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#14442]
Testing #14291

- I updated my extension (999 Martins Extension Pack Testing ) with a new version
```json
{
    "name": "999-martin-pack",
    "displayName": "999 Martins Extension Pack Testing",
    "description": "999 Martins Extension Pack Testing",
    "version": "1.0.3",
    "publisher": "aeschli",
    "engines": {
        "vscode": "^1.6.0"
    },
    "categories": [
        "Other"
    ],
    "galleryBanner": {
        "color": "#882299",
        "theme": "light"
    },
    "license": "MIT",
    "extensionDependencies": [
        "aeschli.vscode-css-formatter",
        "kisstkondoros.csstriggers",
        "999-martin-pack"
    ]
}
```
Note the extension has a circular dependency to itself.

- Install the extension using the extensions viewlet
Error shows: 'Server returned 400'

- In the extension view, clicking on the 'Dependecies' tab result in endless progress balls

**Comment by aeschli** [comment]
Maybe related: The extension has a circular dependency to itself.

**Comment by aeschli** [comment]
Removing the circular dependency and republishing the extension solves the issue.

**Comment by alexandrudima** [comment]
I have code in the activation phase to break out of loops. Perhaps the install should also have something like that?

**Comment by sandy081** [comment]
I am already having the code to break the cycle. Will see where is this being caused.

**Comment by sandy081** [comment]
@aeschli `999-martin-pack` is not a valid extension identifier. Right format is `aeschli.999-martin-pack`. 

Regarding the error, this is what being sent from the server. 

But still, there is a fix needed to show the error in the editor.

**Comment by aeschli** [comment]
@joaomoreno @sandy081 Can vsce catch the invalid identifier and warn when publishing?

**Comment by joaomoreno** [comment]
Microsoft/vscode-vsce#138

**Comment by aeschli** [comment]
Verified that installing now works without error
