### ISSUE TITLE
Font of Jupyter Notebook output is not monospaced anymore

### ISSUE THREAD

**Issue by sleepope** [microsoft/vscode#144417]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I open VScode and it automatically updates to 1.65.0 just now. When I open Jupyter notebook I find the font of the output is not monospaced anymore. I wonder if this issue comes with the new version because I worked with Jupyter notebook just several days ago. I try to find any configuration items in the settings but there is nothing.

![image](https://user-images.githubusercontent.com/60078041/156697627-c7921f8d-7ee2-49dd-a73e-8a979433206c.png)

Thanks!

### VS Code Version

Version: 1.65.0 (user setup) Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43 Date: 2022-03-02T11:12:08.962Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.19043

### Jupyter Extension Version

v2022.2.1020642448

### Coding Language and Runtime Version

Python 3.8.10

### Language Extension Version (if applicable)

Python Extension; Pylance Extension

### Anaconda Version (if applicable)

Not using Anaconda

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
Notebook output is controlled by VS Code, transferring.
Confirmed that on 1.64 with the latest Jupyter pre-release the output had the previous format.

**Comment by vstenby** [comment]
Windows 10 Enterprise signing in here. I was so confused this morning and spent some time trying to figure it out. Uninstalling VS Code and installing 1.64.2 again (user setup) from [here ](https://code.visualstudio.com/updates/v1_64) resolved the issue for me!

**Comment by vkkodali** [comment]
Is there a workaround for this other than rolling back to previous release?

**Comment by pcsee** [comment]
Exactly. This is important as VS code doesn't support version downgrading. I don't want to reinstall VS code


-------- Original message --------
From: Vamsi Kodali ***@***.***>
Date: Sat, 5 Mar 2022, 6:49 am
To: microsoft/vscode ***@***.***>
Cc: PC See ***@***.***>, Comment ***@***.***>
Subject: Re: [microsoft/vscode] Font of Jupyter Notebook output is not monospaced anymore (Issue #144417)

Is there a workaround for this other than rolling back to previous release?

**Comment by vaiibhavgupta** [comment]
Same issue here.

**Comment by Cepadues** [comment]
To fix the output add this to the beginning of your jupyter notebooks :
```python
from IPython.core.display import HTML
HTML(r"""
<style>
    .output-plaintext, .output-stream, .output {
        font-family: Fira Code; # Any monospaced font should work
        line-height: 1.3 !important;
        font-size: 14px !important;
    }
</style>
""")
```

**Comment by sleepope** [comment]
> To fix the output add this to the beginning of your jupyter notebooks :
> 
> ```python
> from IPython.core.display import HTML
> HTML(r"""
> <style>
>     .output-plaintext, .output-stream, .output {
>         font-family: Fira Code; # Any monospaced font should work
>         line-height: 1.3 !important;
>         font-size: 14px !important;
>     }
> </style>
> """)
> ```

This works. Thanks!

**Comment by pcsee** [comment]
Having the IPython.core.display on top of notebook is not a fix, I am still hoping for a permanent repair at VS Code side. VS Code is cool. Please re-open the issue tracking

**Comment by pcsee** [comment]
So I am temporarily getting VSCodium version 1.64 .zip on my computer as I do not want to go through the hassle of re-installing the past version. I will wait for a fix before getting back to VS Code

**Comment by vstenby** [comment]
@pcsee - for me, it wasn't that big a hastle of re-installing previous installation. It saved all of my extensions, all of my settings etc. etc. Takes 5 minutes tops.

**Comment by vstenby** [comment]
But I agree that the issue should not be closed.

**Comment by pcsee** [comment]
True


-------- Original message --------
From: Viktor Stenby ***@***.***>
Date: Mon, 7 Mar 2022, 9:14 pm
To: microsoft/vscode ***@***.***>
Cc: PC See ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/vscode] Font of Jupyter Notebook output is not monospaced anymore (Issue #144417)

@pcsee<https://github.com/pcsee> - for me, it wasn't that big a hastle of re-installing previous installation. It saved all of my extensions, all of my settings etc. etc. Takes 5 minutes tops.

**Comment by pcsee** [comment]
Issue re-opened as #144593

**Comment by pcsee** [comment]
Tested the nightly build - VS Code insider and confirmed the fix works well. Thanks for the effort, good job
