### ISSUE TITLE
 VsCode does not open after changing MACOS user folder.

### ISSUE THREAD

**Issue by arnaldocarpi** [microsoft/vscode#144445]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.0
- OS Version: macOS 11.6.4 (20G417)
- other hd's filesystem: ExFAT

Steps to Reproduce:

Hi, I have a problem with vscode.

The application no longer opens after I change the user folder location to another disk.

clicking on the app, it does not open.

I will send the image of the problem when I try to open the terminal (to show the error)

I'll leave the app print for last - opening when I go back to the default user folder.

directory where I would like to leave my home folder: /Volumes/Arquivos/Users/Arnaldo

system default directory: /Users/arnaldocarpi

![Captura de Tela 2022-03-04 às 20 53 19](https://user-images.githubusercontent.com/51098299/156857417-f8097dd8-1bbd-4454-bdba-a8c583b38a45.png)
![Captura de Tela 2022-03-04 às 20 54 02](https://user-images.githubusercontent.com/51098299/156857421-ba9ab67a-650c-4fb3-a661-9095fd8c6df5.png)
![Captura de Tela 2022-03-05 às 18 28 52](https://user-images.githubusercontent.com/51098299/156900460-eb5affca-77bc-40ec-b39c-ac891dfa78b9.png)

**Comment by alexdima** [comment]
It looks like our main process socket cannot be created.
