### ISSUE TITLE
Path auto-completion not working under remote ssh with vscode 1.65.0 release

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode#144499]
- VS Code Version: 1.65.0
- OS Version: macOS 12.2.1

Steps to Reproduce:

1. Connect to a remote server via Remote SSH.
2. Install either [Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense&ssr=false#overview) or [Path Autocomplete](https://marketplace.visualstudio.com/items?itemName=ionutvmi.path-autocomplete).
3. Type a path and the path completion never appears.

Both extensions are not working:

* https://github.com/ChristianKohler/PathIntellisense/issues/200
* https://github.com/ionutvmi/path-autocomplete/issues/108

I guess it is caused by some upstream issue here. However, it seems to be already fixed in the latest insider. Not sure if it goes to any of the recovery releases soon.

**Comment by dbaeumer** [comment]
@roblourens starting with you. Not sure if this is a extension problem or a general problem with remote.

**Comment by lhyuen** [comment]
I am having the same issue too except that I am on VSCode in windows. I am currently on 1.66 insider and the autocomplete is not working. I am using Path Autocomplete.

**Comment by roblourens** [comment]
I can't repro any issue, it works fine locally and in SSH for me. Can you give exact repro steps? 

Is your remote Windows @renkun-ken?

**Comment by lhyuen** [comment]
> 

Sorry, I should be more clear. My VSCode is on a windows machine, and I was sshing into a linux environment working with a python Jupyter notebook. I tried to type a path in a cell but the there was no suggestion on the path nor did it show anything within the same directory. It would show the relevant information (showed folder/files) before the update. Addition information is that I have pathMappings enabled with Path-Autocomplete and all the path mappings seem to fail.

**Comment by roblourens** [comment]
Does it work in another scenario, like outside of a notebook, or in a local folder?

**Comment by renkun-ken** [comment]
I tried the following and none works:

Local: Ubuntu 21.10, macOS 12.2.1
Remote: Ubuntu 18.04

**Comment by roblourens** [comment]
Do you see any errors in the devtools (Help > Toggle Developer tools)? I probably need the extension author to investigate, it works fine for me.

**Comment by lhyuen** [comment]
It wasn't working for me outside a notebook or local folder.

Turning on the Toggle Developer tools showed that 
autocomplete' failed: Cannot find module 'original-fs'

**Comment by LambdaZed** [comment]
Same problem under wsl.
Desktop / Windows 10 x64 (21H1) / WSL-2 / Ubuntu-20.04
```log
workbench.desktop.main.js:2355 
Activating extension 'ionutvmi.path-autocomplete' failed: Cannot find module 'original-fs'
Require stack:
- /home/user/.vscode-server/extensions/ionutvmi.path-autocomplete-1.19.0/out/src/features/FsUtils.js
- /home/user/.vscode-server/extensions/ionutvmi.path-autocomplete-1.19.0/out/src/features/PathAutocompleteProvider.js
- /home/user/.vscode-server/extensions/ionutvmi.path-autocomplete-1.19.0/out/src/extension.js
- /home/user/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/out/vs/loader.js
- /home/user/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/out/bootstrap-amd.js
- /home/user/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/out/bootstrap-fork.js.
$onExtensionActivationError @ workbench.desktop.main.js:2355
```

**Comment by renkun-ken** [comment]
Local: macOS, Remote: Ubuntu, sometimes works but very laggy
Local: Ubuntu, Remote: Ubuntu, never works at all.

**Comment by roblourens** [comment]
I see this discussion: https://github.com/microsoft/vscode/issues/143393#issuecomment-1047518447

Is this an electron module, so it won't exist in pure node, when running in a remote vscode server? The extension author would need to handle that case properly.

cc @deepak1556 @alexdima

**Comment by lhyuen** [comment]
> > 
> 
> Sorry, I should be more clear. My VSCode is on a windows machine, and I was sshing into a linux environment working with a python Jupyter notebook. I tried to type a path in a cell but the there was no suggestion on the path nor did it show anything within the same directory. It would show the relevant information (showed folder/files) before the update. Addition information is that I have pathMappings enabled with Path-Autocomplete and all the path mappings seem to fail.

My problem seems to have disappeared with the most recent insider update.

**Comment by roblourens** [comment]
Appears to have been fixed in the extension https://github.com/ionutvmi/path-autocomplete/issues/108
