### ISSUE TITLE
[ : ] charactor is not work in wordSeparators

### ISSUE THREAD

**Issue by gintering1000** [microsoft/vscode#144451]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

![Screen Capture 2022-03-05 at 11 55 40](https://user-images.githubusercontent.com/77244047/156865122-7a10ec48-05df-43ce-80b9-ee2f894b92e0.gif)

[ : ] charactor is not work in wordSeparators

**Comment by JacksonKearl** [comment]
Since `"`, `:`, and ` ` are all word separators they are all grouped together when navigating by word.
