### ISSUE TITLE
Bug with tab spaces in markdown

### ISSUE THREAD

**Issue by B3DTech** [microsoft/vscode#144594]
I have the following set:

Editor: Tab Size 4
Editor: Detect Indentation False
Editor: Insert Spaces True

I see no custom Markdown code in settings.

However when I'm editing a markdown file I see strange behavior.  Pressing tab on a new line adds 4 spaces.  However when I'm typing an ordered list, and press tab to indent the numbers, it inserts 3 spaces.  If I'm using an unordered list and tabbing, it only inserts 2 spaces.

<img width="481" alt="image" src="https://user-images.githubusercontent.com/32655512/157062128-4fa8c223-25b1-47ae-b736-3c094454acdd.png">

The tab spacing should be consistent as set in the settings.  This is an issue for me as BitBucket requires 4 spaces in markdown lists to display the indentations properly.  I hope it's just a settings I'm missing somewhere.  Thanks.

**Comment by Lemmingh** [comment]
If you're using **Markdown All in One**, please refer to
<https://github.com/yzhang-gh/vscode-markdown/issues/1044#issuecomment-973703585>

**Comment by B3DTech** [comment]
Thank you!  I forgot I had enabled that plugin and it was exactly the issue.
