### ISSUE TITLE
ctrl+s destroys the file when saving

### ISSUE THREAD

**Issue by xinyugit** [microsoft/vscode#144520]
Issue Type: <b>Bug</b>

The Chinese content of the file encoding is ansi gb2312
vscode opens garbled characters, and the file data can no longer be recovered after pressing ctrl+s
crtl+z doesn't work either

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (7.41GB free)|
|Process Argv|C:\\Users\\Administrator\\Desktop\\a --crash-reporter-id 351ca3c4-1a3a-4657-aa64-0a15ace5b904|
|Screen Reader|no|
|VM|44%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
code-runner|for|0.11.7
better-cpp-syntax|jef|1.15.13
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-language-pack-zh-hans|MS-|1.65.1
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
hexeditor|ms-|1.9.5
markdown|sta|1.2.8
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30440023
pythonvspyt640:30442238
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvidc:30438801
helix:30440343
vsnot107:30443614

```

</details>

**Comment by xinyugit** [comment]
![image](https://user-images.githubusercontent.com/23651947/156938774-d1795d40-b760-421b-85b1-d3d6d5c8ae96.png)
![image](https://user-images.githubusercontent.com/23651947/156938831-4b20745d-b8fc-417a-83f7-f2743efa8a16.png)

Can't restore after pressing ctrl+s
![image](https://user-images.githubusercontent.com/23651947/156938870-865bca8e-ff48-49c8-85b1-9d892e2e3439.png)

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding
