### ISSUE TITLE
deprecated tag is not display strikethrough in javascript file

### ISSUE THREAD

**Issue by LuckyRabbitFeet** [microsoft/vscode#144572]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0
- OS Version: macos 11.6.1

Steps to Reproduce:

```js
/**
 * ??
 * @deprecated test
 */
 export function func() {
  console.log('deprecated');
}

export class Foo {
  /**
   * @deprecated
   */
  test() {
      console.log('a')
  }
}

status

func();

const bar = new Foo();
bar.test();
```

in javascript file
<img width="408" alt="image" src="https://user-images.githubusercontent.com/32757528/157001480-e9a35dcf-d1dd-488b-9073-8b136534b740.png">

in typescript file
<img width="360" alt="image" src="https://user-images.githubusercontent.com/32757528/157001560-ee30dff5-01a6-4953-a722-169a4ca8df81.png">

follow the instructions of [Deprecated tag support for JavaScript and TypeScript](https://code.visualstudio.com/updates/v1_49#_deprecated-tag-support-for-javascript-and-typescript) i think `status`, `func` and `test` should also show strikethrough for deprecated in javascript files.

i am not sure if this is a bug, please help me if I missed something.

thanks

**Comment by IllusionMH** [comment]
Do you have `tsconsfig.json`/`jsconfig.json` files that might exclude this file?
Are you using built-in or some specific TS version?

Unable to reproduce this in workspace or buffer(Untitled-x) files.

Version: 1.65.0
Date: 2022-03-02T11:12:08.962Z
OS: Windows_NT x64 10.0.19043

Built-in TS Server 4.6.2

**Comment by LuckyRabbitFeet** [comment]
> Do you have `tsconsfig.json`/`jsconfig.json` files that might exclude this file? Are you using built-in or some specific TS version?
> 
> Unable to reproduce this in workspace or buffer(Untitled-x) files.
> 
> Version: 1.65.0 Date: 2022-03-02T11:12:08.962Z OS: Windows_NT x64 10.0.19043
> 
> Built-in TS Server 4.6.2

thank you for your reply.

i just open a empty folder then create a new js file, so i have not use `tsconfig.json` or `jsconfig.json`, and i think i used built-in TS on this occasion.

**Comment by mjbvz** [comment]
Also works fine for me

- Do other JS Intellisense features work? 
- Do toy see this with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
- What's the language mode of the file? (this is shown in the status bar)

**Comment by LuckyRabbitFeet** [comment]
> Also works fine for me
> 
> * Do other JS Intellisense features work?
> * Do toy see this with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
> * What's the language mode of the file? (this is shown in the status bar)

thanks for your reply.

- other JS Intellisense features is work
- yes, i used `code . --disable-extensions ` command to open the folder
- the language mode is javascript

i found one thing, after I disable all my customizations it works fine.
i am pretty sure this setting is not editor.showDeprecated, so i will check what settings are making the difference myself

thanks

**Comment by mjbvz** [comment]
Yes that's the expected behavior 

`javascript.validate.enable ` enables/disables error reporting in JS files. Deprecations strikethroughs are errors even though it is rendered differently than other errors (you can hover over them to see this)

You can't disable validation while keeping deprecation enabled (but you can do the reverse: have validation enabled and disable deprecation using `editor.showDeprecated`)
