### ISSUE TITLE
account feature not working 

### ISSUE THREAD

**Issue by sirazsk** [microsoft/vscode#144529]
Issue Type: <b>Bug</b>

installed visual studio code using pacman in endeavouros an arch based system

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:36.248Z)
OS version: Linux x64 5.16.12-arch1-1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor (8 x 3193)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|7.73GB (2.75GB free)|
|Process Argv|--crash-reporter-id d5616a6f-7751-4b55-808a-51be7891ca32|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.3.0
auto-rename-tag|for|0.1.10
dotenv|mik|1.0.1
indent-rainbow|ode|8.2.2
es7-react-js-snippets|rod|1.9.3
markdown-preview-enhanced|shd|0.6.2
code-spell-checker|str|2.1.7
vscode-styled-components|sty|1.7.2
highlight-matching-tag|vin|0.10.1
vscode-icons|vsc|11.10.0
quokka-vscode|Wal|1.0.449
five-server|yan|0.1.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrt:30448491
vsrem710:30416614
dsvsc009:30440023
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe #144471

**Comment by sirazsk** [comment]
yes solved
