### ISSUE TITLE
Add an option to report suspicious extensions in the marketplace

### ISSUE THREAD

**Issue by TheBigEye** [microsoft/vscode#144510]
A moment ago while checking an extension, I have noticed that there are some times where somewhat *suspicious* extensions appear in search results, I have searched how to report extensions on the internet but apparently there is no result, there is also no button to report those extensions in vscode

![dung2](https://user-images.githubusercontent.com/63316583/156925615-d728fe47-0104-4e39-a387-7abd108d11e6.gif)

Add a button or option to the Marketplace to be able to report extensions (the user should have an account linked to vscode to do it)

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/143210#issuecomment-1041930244

**Comment by TheBigEye** [comment]
> See [#143210 (comment)](https://github.com/microsoft/vscode/issues/143210#issuecomment-1041930244)

oh, thanks

**Comment by SidBlack** [comment]
Hello, I have a question, I do not know why you are asking me with this
problem I do not know programming I do not know what you mean, this is not
my field

pon., 7 mar 2022 o 00:11 TheBigEye ***@***.***> napisał(a):
