### ISSUE TITLE
I want a feature like VS to add links to existing files

### ISSUE THREAD

**Issue by wmtiger** [microsoft/vscode#144576]
In VS, you can add existing files as links. Vscode does not. In some scenarios it would be much easier to use file links.

**Comment by wmtiger** [comment]
Add --> Existing item
[https://pic002.cnblogs.com/images/2010/79886/2010101810505665.jpg](url)
Add As Link
[https://pic002.cnblogs.com/images/2010/79886/2010101810510864.jpg](url)
Created link file
[https://pic002.cnblogs.com/images/2010/79886/2010101810512529.jpg](url)

**Comment by wmtiger** [comment]
Add --> Existing item

![11](https://user-images.githubusercontent.com/3124854/157402955-15c9b046-a74e-4e14-9389-e1b02333c781.jpg)

Add As Link
![22](https://user-images.githubusercontent.com/3124854/157402982-d47e81f6-313d-4940-bdf8-555e8ecdb838.jpg)

Created link file
![33](https://user-images.githubusercontent.com/3124854/157403014-ae6726ae-2a3c-4264-9dbd-2f3e12fefe6b.jpg)

**Comment by wmtiger** [comment]
> Thanks for reporting this issue! Unfortunately, it's hard for us to understand what issue you're seeing. Please help us out by providing a screen recording showing exactly what isn't working as expected. While we can work with most standard formats, `.gif` files are preferred as they are displayed inline on GitHub. You may find https://gifcap.dev helpful as a browser-based gif recording tool.
> 
> If the issue depends on keyboard input, you can help us by enabling screencast mode for the recording (`Developer: Toggle Screencast Mode` in the command palette).
> 
> Happy coding!

I added a graphic, you can have a look

**Comment by JacksonKearl** [comment]
So a way to create symlinks from the explorer? An extension should be able to provide this functionality.
