### ISSUE TITLE
Weird editor behaviour when typing ''

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#144590]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.66.0-insider
Commit: 6dca4c1a1f7bb3529074601eb32938526fa9ecc7
Date: 2022-03-04T05:18:46.542Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0

Steps to Reproduce:
1. Open a TypeScript file in the editor
2. Type `''` -> This will render `'''` in the editor
3. Press right arrow, and this will transform `'''` into `''`.
4. Select a full word and press `'`. Editor will render `'`
5. Press right arrow, and this will render `'word'`

**Comment by alexdima** [comment]
@lszomoru I can't reproduce with the US keyboard layout. Are you perhaps using a keyboard layout where `'` is used as a composition character / for IME?

**Comment by lszomoru** [comment]
I am only able to reproduce the issue using `US International - PC` keyboard layout, and it does look like on this keyboard layout the `'` is used as a composition character. If this is expected, please feel free to close the issue. Thanks!

**Comment by alexdima** [comment]
I'm having trouble reproducing, let's look into this together sometime.

**Comment by alexdima** [comment]
From our discussion, I've extracted the following issues, so we can continue tracking them independently:
* #144690
* #144691
* #144693
