### ISSUE TITLE
Issue installing ms-python.python extension

### ISSUE THREAD

**Issue by krageth** [microsoft/vscode#144589]
C:\Users\myUser\> code --install-extension ms-python.python
Installing extensions...
Installing extension 'ms-python.python'...
(node:10220) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)

Windows 10
VScode version 1.65.0 b5205cc8eb4fbaa726835538cd82372cc0222d43x64
Issue Type: Bug

**Comment by sandy081** [comment]
@krageth Can you please let me know what is the issue here? Does the extension installed eventually?
