### ISSUE TITLE
Allow to change font and color per file

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode#144542]
The font and color can be modified for a single file

**Comment by mamiu** [comment]
@ydmykr Could you please be more specific? What is the problem, how to reproduce it, what is your preferred solution, etc?

**Comment by ydmykr** [comment]
We know that the font size and color settings in vscode are applicable to the whole world. We hope to set the font of the file selected by the user separately
________________________________
发件人: Paul Miu ***@***.***>
发送时间: 2022年3月7日 14:15
收件人: microsoft/vscode ***@***.***>
抄送: Mingjie Zhang (Shanghai Wicresoft Co,.Ltd.) ***@***.***>; Mention ***@***.***>
主题: Re: [microsoft/vscode] The font and color can be modified for a single file (Issue #144542)


@ydmykr<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fydmykr&data=04%7C01%7Cv-mingjzhang%40microsoft.com%7C598615c5748c49c6575608da0001d72f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637822305152893081%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JbwlVEp0fnwwk55ApeXfZjk9YfKOZ3HVnO5oPCA7meE%3D&reserved=0> Could you please be more specific? What is the problem, how to reproduce it, what is your preferred solution, etc?

―
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode%2Fissues%2F144542%23issuecomment-1060229779&data=04%7C01%7Cv-mingjzhang%40microsoft.com%7C598615c5748c49c6575608da0001d72f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637822305152943065%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0U2w71dAMYbGcfYWAEfLrZDG7IsGPXVYgFzcTLqTTCU%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYBFECRPANIEFPDP7RFCZLLU6WNHBANCNFSM5QCJCZFA&data=04%7C01%7Cv-mingjzhang%40microsoft.com%7C598615c5748c49c6575608da0001d72f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637822305152943065%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ayc5Hz8dDzpmozddxHE9tIROwCnpngogfDiMANh%2BhE0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cv-mingjzhang%40microsoft.com%7C598615c5748c49c6575608da0001d72f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637822305152943065%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6t7kHpW0KWog0SgSkoqX0F%2FrCnH5UuldW5zi4NBxrMg%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cv-mingjzhang%40microsoft.com%7C598615c5748c49c6575608da0001d72f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637822305152943065%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QBVEa4hGxpNFuFXUTTWgbKCi7AopmaHBYCyFI%2Fn%2Fyhg%3D&reserved=0>.

**Comment by mamiu** [comment]
You can change the font in the settings. Just go to your settings and search for font.
Or edit the following properties in your `settings.json`:

```js
{
  // Controls the font family.
  "editor.fontFamily": "Consolas, 'Courier New', monospace",

  // Configures font ligatures or font features. Can be either a boolean to enable/disable ligatures or a string for the value of the CSS 'font-feature-settings' property.
  "editor.fontLigatures": false,

  // Controls the font size in pixels.
  "editor.fontSize": 14,

  // Controls the font weight. Accepts "normal" and "bold" keywords or numbers between 1 and 1000.
  "editor.fontWeight": "normal"
}
```

**Comment by ydmykr** [comment]
How can I use one font for document A and another for document B
________________________________
发件人: Paul Miu ***@***.***>
发送时间: 2022年3月7日 16:39
收件人: microsoft/vscode ***@***.***>
抄送: Mingjie Zhang (Shanghai Wicresoft Co,.Ltd.) ***@***.***>; Mention ***@***.***>
主题: Re: [microsoft/vscode] The font and color can be modified for a single file (Issue #144542)


You can change the font in the settings. Just go to your settings and search for font.
Or edit the following properties in your settings.json:

{
  // Controls the font family.
  "editor.fontFamily": "Consolas, 'Courier New', monospace",

  // Configures font ligatures or font features. Can be either a boolean to enable/disable ligatures or a string for the value of the CSS 'font-feature-settings' property.
  "editor.fontLigatures": false,

  // Controls the font size in pixels.
  "editor.fontSize": 14,

  // Controls the font weight. Accepts "normal" and "bold" keywords or numbers between 1 and 1000.
  "editor.fontWeight": "normal"
}

―
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode%2Fissues%2F144542%23issuecomment-1060331599&data=04%7C01%7Cv-mingjzhang%40microsoft.com%7C93ad8158db0d496f333a08da00160279%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637822391773625994%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3RF1Z5zTUx3DNwGKQ56hGxexoEwJj5Clfrq8WL0LWQI%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYBFECSDAADZYYUNRJ7TXTDU6W6EPANCNFSM5QCJCZFA&data=04%7C01%7Cv-mingjzhang%40microsoft.com%7C93ad8158db0d496f333a08da00160279%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637822391773625994%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jEMEPiA2rxo8CzjBXHa3N5khoasRe%2F5myrY1897Rm8E%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cv-mingjzhang%40microsoft.com%7C93ad8158db0d496f333a08da00160279%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637822391773625994%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wRl%2FV5zUWsCiWJmCORU1gI7iSxrOPJmZN0RA02B13xU%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cv-mingjzhang%40microsoft.com%7C93ad8158db0d496f333a08da00160279%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637822391773625994%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=reDaTaJKLgmqoUMBeR8YINueYZ%2BqCEdOH9eRE9%2FBqv4%3D&reserved=0>.

**Comment by mamiu** [comment]
Why do you want to use different fonts for different files?

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/35350
