### ISSUE TITLE
`statusBar.focusBorder` not working ?

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#144574]
**Does this issue occur when all extensions are disabled?:**
 Yes

**Details**
With this new function (https://code.visualstudio.com/updates/v1_65#_status-bar-focus-borders)
we have two options:
```
statusBar.focusBorder: The border color of the entire status bar when focused.
statusBarItem.focusBorder: The border color the status bar items when focused
```

**My settings:**
```
            "statusBar.focusBorder": "#00000000",   <---- this one not working
            "statusBarItem.focusBorder": "#00000000",    <---- this one works fine
```

**VS Code/OS Version**
```
Version: 1.65.0 (system setup)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:12:08.962Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

**But the status bar still has a white border when I click the mouse**

https://user-images.githubusercontent.com/30685349/157014538-882e0502-4800-4df0-983b-8f18e0990113.mp4

**Comment by bpasero** [comment]
Moving to March and setting `bug` label to get verification during endgame.
