### ISSUE TITLE
Unable to run a current program

### ISSUE THREAD

**Issue by UddeshSD** [microsoft/vscode#144512]
We have written the neede
Issue Type: <b>Performance Issue</b>

I am unable to run a current program please resolve the issue

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (9.77GB free)|
|Process Argv|--crash-reporter-id 67f2f305-bf69-47e2-9eca-d6dda571e3a7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   132	  1116	code main
    0	    27	  2708	   crashpad-handler
    0	    42	 12720	   utility
    0	   188	 13148	   gpu-process
    0	    91	 14288	   shared-process
    0	    85	 13260	     ptyHost
    0	     5	  4016	       C:\WINDOWS\System32\cmd.exe
    0	     7	  4908	       console-window-host (Windows internal process)
    0	     5	 11916	       C:\WINDOWS\System32\cmd.exe
   13	     4	 13488	         "c:\Users\deshm\OneDrive\Desktop\Apnacollege\"031conversion
    0	     7	 16040	       console-window-host (Windows internal process)
    0	    84	 15532	   window (Issue Reporter)
    0	   247	 16476	   window (031convert.cpp - workspace (Workspace) - Visual Studio Code)
    0	   140	  6232	     extensionHost
    0	    69	   560	       c:\Users\deshm\.vscode\extensions\ms-vscode.cpptools-1.7.1\bin\cpptools.exe
    0	    69	  3148	         c:\Users\deshm\.vscode\extensions\ms-vscode.cpptools-1.7.1/bin/cpptools-srv.exe 560 {F7DE35E8-5058-4307-86FF-65E9F7163EBE}
    0	    12	  3940	         console-window-host (Windows internal process)
    0	    53	  5952	         c:\Users\deshm\.vscode\extensions\ms-vscode.cpptools-1.7.1/bin/cpptools-srv.exe 560 {E8D3B2CC-D49A-45F3-8B14-BC1914B2C86B}
    0	    39	 15528	         c:\Users\deshm\.vscode\extensions\ms-vscode.cpptools-1.7.1/bin/cpptools-srv.exe 560 {373C0961-76A4-4660-9C20-8721E2974156}
    0	    78	  2680	       "C:\Users\deshm\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\deshm\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=6232
    0	    17	  9696	     watcherService 
    0	    12	  4736	       console-window-host (Windows internal process)
    0	    80	 13588	     searchService
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (031convert.cpp - workspace (Workspace) - Visual Studio Code)
|    Folder (Apnacollege): 65 files
|      File types: cpp(32) exe(31) json(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.7
cpptools|ms-|1.7.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrt:30448491
vsrem710cf:30416617
vscop841:30447409
dsvsc008:30440022
pythonvspyt640:30442238
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvid1:30447480
helix:30440343
dockersurvey3:30446832

```

</details>

d data into your clipboard because it was too large to send. Please paste.

**Comment by SidBlack** [comment]
Hello, I have a question, I do not know why you are asking me with this
problem I do not know programming I do not know what you mean, this is not
my field

pon., 7 mar 2022 o 00:19 VS Code Issue Triage Bot ***@***.***>
napisał(a):

**Comment by weinand** [comment]
@SidBlack you are receiving these messages because you are "subscribed" to this issue.
Please press the "Unsubscribe" button on the right to stop receiving email notifications.
