### ISSUE TITLE
Error: <semantic> TypeScript Server Error (4.6.2) No Project. Error: No Project.

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#144547]
Deminified Stack
Error: <semantic> TypeScript Server Error (4.6.2) No Project. Error: No Project.
at Object.ThrowNoProject in /extensions/node_modules/typescript/lib/tsserver.js:164826:23
at ScriptInfo.getDefaultProject in /extensions/node_modules/typescript/lib/tsserver.js:165673:46
at ProjectService.doEnsureDefaultProjectForFile in /extensions/node_modules/typescript/lib/tsserver.js:168708:48
at ProjectService.ensureDefaultProjectForFile in /extensions/node_modules/typescript/lib/tsserver.js:168703:75
at IpcIOSession.Session.getFileAndProjectWorker in /extensions/node_modules/typescript/lib/tsserver.js:173232:87
at IpcIOSession.Session.getProjectInfoWorker in /extensions/node_modules/typescript/lib/tsserver.js:173075:36
at IpcIOSession.Session.getProjectInfo in /extensions/node_modules/typescript/lib/tsserver.js:173072:29
at Session.handlers.ts.Map.ts.getEntries._a.<computed> in /extensions/node_modules/typescript/lib/tsserver.js:172354:61
at <anonymous> in /extensions/node_modules/typescript/lib/tsserver.js:174044:88
at IpcIOSession.Session.executeWithRequestId in /extensions/node_modules/typescript/lib/tsserver.js:174035:28
at IpcIOSession.Session.executeCommand in /extensions/node_modules/typescript/lib/tsserver.js:174044:33
at IpcIOSession.Session.onMessage in /extensions/node_modules/typescript/lib/tsserver.js:174070:35
at process.<anonymous> in /extensions/node_modules/typescript/lib/tsserver.js:176705:31
at process.emit in events.js:315:20
at emit in internal/child_process.js:903:12
at processTicksAndRejections in internal/process/task_queues.js:81:21
at Function.create in /extensions/typescript-language-features/dist/extension.js:1:503379
at dispatchResponse in /extensions/typescript-language-features/dist/extension.js:1:497227
[at dispatchResponse in extensions/typescript-language-features/src/tsServer/server.ts:147:12](https://vscode.dev/github/microsoft/vscode/blob/b5205cc8eb4fbaa726835538cd82372cc0222d43/extensions/typescript-language-features/src/tsServer/server.ts#L147:12)
at ChildProcess.<anonymous> in /extensions/typescript-language-features/dist/extension.js:1:495580
at ChildProcess.emit in events.js:315:20
at emit in internal/child_process.js:903:12
at processTicksAndRejections in internal/process/task_queues.js:81:21

From error telemetry.

**Comment by razzeee** [comment]
https://github.com/microsoft/TypeScript/issues/20357

**Comment by ataravati** [comment]
I'm having the same issue.

**Comment by mjbvz** [comment]
This specific error is not useful without full server logs to understand how we got into this state

Closing as not-actionable
