### ISSUE TITLE
Suggestion: Rethink the "FeatureDebounce" logic

### ISSUE THREAD

**Issue by PieterBranderhorst** [microsoft/vscode#144541]
I encountered this issue while debugging an extension. I added a breakpoint to a folding provider, then paused at the breakpoint for a bit while thinking. Then when I continued execution it was as if debugging was broken. I couldn't get a breakpoint to hit anymore. I eventually backtracked into vscode and realized that invocation of the folding provider was now being delayed 40 seconds by the recently added "FeatureDebounce" logic.

I suggest removing the "FeatureDebounce" code. I don't know what issues this code was intended to address but I doubt this approach is addressing them well. Its effect is to modify the delay which occurs between when a feature's code, e.g. folding range calculations, is triggered and when it actually runs.

There is good reason for having that delay. The code which implements a feature may be in an extension outside your control and may be slow. Changes to the text being edited may come in bursts due to the user's typing or due to some internal activity which is divided across a promise chain. Extensions may not check for cancellation. It all adds up to being a good idea to delay starting these tasks slightly to reduce the number of cases where they are launched and then cancelled and re-launched.

For folding range calculations the previous code delayed launching by 1/5th of a second. The new "FeatureDebounce" logic delays by the average execution time of recent range calculations with a minimum of 1/5th second and a maximum of 40 seconds.

When the calculation takes longer than 1/5th second, what good can it do to delay starting the calculation by the average time it takes to perform the calculation? How does doing so better serve the user? If I edit a 40,000 line Typescript file the typescript folding provider takes about 5 seconds to update folding info on my machine. How does it help anything to make this take 10 seconds (or even 6) by adding additional delay at the start?

Also, this approach will sometimes incorrectly penalize fast extensions. Two or more extensions may be triggered by the same events, e.g. text content changed. Due to the single threaded nature of the extension host a fast extension 'B' may take a long time to respond because it is launched after some slow extension 'A'. The "FeatureDebounce" logic as it currently stands will increase the delay added to 'B' by at least as much as it increases 'A'. And that's the opposite of what one would want. Only 'A's delay should be increased so that the speedier 'B' then starts running before 'A'. To get that result the extension host must be the source of elapsed time information. (And perhaps should be where action is taken based on performance.) Even with that the final result will remain imperfect because a well-behaved slightly slow extension which timeslices will still come out behind a very slow extension which doesn't timeslice. I think that's part of the same can of worms. I think that a real solution will require some surgery in the extension host.

**Comment by jrieken** [comment]
> If I edit a 40,000 line Typescript file the typescript folding provider takes about 5 seconds to update folding info on my machine. How does it help anything to make this take 10 seconds (or even 6) by adding additional delay at the start?

Features like folding or outline can take long on huge files and can be fast on "normal" files. These features are ambient and update as type. We cannot recompute things as you type, so debouncing is needed. Huge files is actually why we do dynamic debounce and why the average is managed [per file](https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/editor/common/services/languageFeatureDebounce.ts#L26).  Any hard-coded debounce value cannot do justice to the variety of files and extensions - it would just be the observed value that I see on my machine and thereby wrong for corner-cases like huge files, slow machines etc. 

> Also, this approach will sometimes incorrectly penalize fast extensions. Two or more extensions may be triggered by the same events, e.g. text content changed. 

This isn't true in practice. All features (except for hover) wait for all extensions before showing a result and therefore there isn't an observable difference. 


I do understand and acknowledge that you had a bad experience while debugging. No debate, but it's also not what this feature is optimised for. Dynamic debounce isn't new - it always existed for code lens and outline and now adopted broadly and it useful. What can be discussed if there is a special mode while debugging or developing an extension.

**Comment by PieterBranderhorst** [comment]
I already knew those things, thanks.

**Comment by jrieken** [comment]
Closing because #184159 will make dynamic debounce be ignore when developing
