### ISSUE TITLE
multi target debugging: floating debug action widget needs to show session

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#14450]
Testing https://github.com/Microsoft/vscode/issues/14171:

Since we will probably continue to use the floating debug action widget, we will have to improve how we show the current debug session. Without that it is pretty difficult to understand what the action buttons do because they depend on what is currently selected in the CALLSTACK view.

I suggest to show the current debug session on the floating debug action widget (ideally as a switcher drop-down). If we show this drop-down menu on the right hand-side of the widget, we could easily add and remove it as sessions come and go without changing the location of the individual buttons (this is important if a user wants to press the continue button for multiple sessions without having to track the location of the button). In addition we have to take into account that some sessions might add addition buttons (e.g. for back-in-time-debugging). To accommodate for this I suggest that we have only a single floating debug action widget that is multiplexed between the sessions and shows the union of all buttons used by the sessions, but disables the buttons that are not configured for the sessions.

**Comment by isidorn** [comment]
Fixed via befd068
