### ISSUE TITLE
Error in file changing

### ISSUE THREAD

**Issue by dostonnabotov** [microsoft/vscode#144511]
Issue Type: <b>Performance Issue</b>

When I installed Visual Studio Code, I decided to put them in D:downloads folder instead of C. Then, It worked smoothly for a few weeks. Later on, I needed to work with Node.js and downloaded it from Microsoft Edge. It also worked fine for a while. But, suddenly when i was coding in VS Code yesterday, it started to show Error: code 5 on every startup. And, it said that it couldn't find file or something on D:downloads folder and alerted me to setup again. Now, whenever I open VS code, it always occurs.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 6.2.9200
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz (2 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.53GB free)|
|Process Argv|--crash-reporter-id 0e4acd59-0170-4ec2-b619-10f04d5ab25f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    98	  8608	code main
    0	    26	  2596	   crashpad-handler
    0	    96	  2604	   shared-process
    0	    71	 10028	     fileWatcher
    0	    67	 10616	     ptyHost
    0	   120	  4232	   window (VS Code - Visual Studio Code)
    5	    84	  7064	   issue-reporter
    0	   119	  7092	   extensionHost
    0	    71	  9124	     "D:\Downloads\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "d:\Downloads\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=7092
    4	   138	 10940	   gpu-process
    1	    43	 10956	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (VS Code - Visual Studio Code)
|    Folder (VS Code): 18 files
|      File types: scss(5) svg(5) css(1) map(1) jpg(1) png(1) html(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-html-css|ecm|1.11.0
code-runner|for|0.11.7
live-sass|rit|3.0.0
LiveServer|rit|5.7.4
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrt:30448491
vsrem710:30416614
dsvsc008:30440022
pythonvspyt640:30442238
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvidc:30447482
helix:30440343
vscaat:30438848

```

</details>

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the error?

**Comment by dostonnabotov** [comment]
Sent from Mail for Windows From: João MorenoSent: Monday, March 7, 2022 6:17 PMTo: microsoft/vscodeCc: Doston Nabotov; AuthorSubject: Re: [microsoft/vscode] Error in file changing (Issue #144511) Can you show me a screenshot of the error?—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by dostonnabotov** [comment]
Also my terminal in VS Code is not working as I can’t type anything  Sent from Mail for Windows From: João MorenoSent: Monday, March 7, 2022 6:17 PMTo: microsoft/vscodeCc: Doston Nabotov; AuthorSubject: Re: [microsoft/vscode] Error in file changing (Issue #144511) Can you show me a screenshot of the error?—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by joaomoreno** [comment]
Please come to GitHub and attach the screenshot. You can't send it via e-mail.
