### ISSUE TITLE
Improve hover tooltip on top-level call stack nodes

### ISSUE THREAD

**Issue by sbj42** [microsoft/vscode#144540]
When the sidebar is narrow, some strings are cut off in the Call Stack panel.  Top-level nodes in that tree get ellipses, but the hover tooltip on them is a different string entirely.  This is an issue in the built-in JavaScript debugger, but also potentially in other debuggers, including `vscode-java-debug` where I initially [submitted this issue](https://github.com/microsoft/vscode-java-debug/issues/1128).

Please allow the tooltip for those items to include the truncated text.

For instance, in vscode 1.66.0-insiders with extensions disabled, see the following screenshot:

![image](https://user-images.githubusercontent.com/99791/156971356-ed9318bc-0617-4e9b-b2f2-ca9fe416d393.png)

The top-level node label would be `Launch Program: test.js [1724]`, but is truncated to `L...`.  The hover tooltip text is just `Paused on breakpoint`.  My request is that `Launch Program: test.js` should be included in the hover text somehow.

The problem is worse in the `vscode-java-debug` extension:

![image](https://user-images.githubusercontent.com/99791/156971650-0fb18542-3005-4149-98cc-d396c7eb8085.png)

In Java there can be many threads, and the names of those threads is useful information, but the hover tooltip does not help because it merely says `Thread`.  @testforstephen [says](https://github.com/microsoft/vscode-java-debug/issues/1128#issuecomment-1060122102) that vscode is showing the "node kind" as the tooltip.  It sounds like the vscode-java-debug extension needs better control over the tooltip text in the vscode API.

**Comment by roblourens** [comment]
I think the "paused on breakpoint" label comes from the debug extension, but I think we could include the session name too. And I don't see why we wouldn't use the whole Thread name. Any reason not to do that @isidorn?

**Comment by isidorn** [comment]
"Paused on"  is coming from here https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/callStackView.ts#L878
Currently it is probably re-used between hover and title area label (when there is just one session).
So I think if there are multiple sessions the label should contain the session name.

Yeah I think using the full thread name is better on hover.

**Comment by rchiodo** [comment]
/verified

Tried with typescript and python. Tooltips are much more descriptive.
