### ISSUE TITLE
After reading the file, I can get relevant comments at compile time

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode#144536]
I hope to use the properties class to read the file during compilation. When using the relevant fields, I can directly and intelligently remind you to get the relevant information in the read file

**Comment by weinand** [comment]
I don't understand what are you asking for.
Please be more specific.
What language are you referring to?

**Comment by ydmykr** [comment]
Java
When I import one .properties file
I hope to be able to directly and intelligently prompt the  value in the properties file when using the key keyword in the properties file when compiling the content.

object.properties
First.Value=SomeValue

.java file
import java.io.*;
import java.util.*;

public class testProperties {
    public static void main(String[] args) throws FileNotFoundException, IOException {

        Properties prop = new Properties();
        prop.load(new FileInputStream("C:\\my_code\\object.properties"));
        String someKey = "First.Val";
        String abc = prop.getProperty(someKey);
    }
}


I hope when the mouse is placed on the penultimate line of first Val can get relevant information


________________________________
发件人: Andre Weinand ***@***.***>
发送时间: 2022年3月7日 17:23
收件人: microsoft/vscode ***@***.***>
抄送: Mingjie Zhang (Shanghai Wicresoft Co,.Ltd.) ***@***.***>; Author ***@***.***>
主题: Re: [microsoft/vscode] After reading the file, I can get relevant comments at compile time (Issue #144536)


I don't understand what are you asking for.
Please be more specific.
What language are you referring to?

―
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode%2Fissues%2F144536%23issuecomment-1060380682&data=04%7C01%7Cv-mingjzhang%40microsoft.com%7Cdcb25a901ac943afde0608da001c314c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637822418340000156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=icEYQrhjt9HdiUV2EjMUayjISaqDzsjWqBnwLAHajcs%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYBFECV4MRLDX4W73NGFTE3U6XDKNANCNFSM5QB7NYHA&data=04%7C01%7Cv-mingjzhang%40microsoft.com%7Cdcb25a901ac943afde0608da001c314c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637822418340050460%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3nrS4w7sCT5cl05fCd86bx0SdEyTbES9mT1xXNVjYbo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cv-mingjzhang%40microsoft.com%7Cdcb25a901ac943afde0608da001c314c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637822418340050460%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=myAQGUY9XTAa1kxaFcgCfcLH2EHEX3ITrRK2UclPW5k%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cv-mingjzhang%40microsoft.com%7Cdcb25a901ac943afde0608da001c314c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637822418340050460%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eNapQFMVNDx4LsDas7XsMwW%2FYBmGAvQRwO8uV0iN2O4%3D&reserved=0>.
