### ISSUE TITLE
Placeholder decoration overlaid with success/error decoration

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#144597]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Enable shell integration
2. Run a successful command
3. :bug: see that success/error decorations are rendered on top of placeholder decorations
![image](https://user-images.githubusercontent.com/30305945/157068243-92b745a4-974a-4185-85ea-fe4fe5cf6ea4.png)

**Comment by joyceerhl** [comment]
Still seeing this. In addition, when I click on the overlaid command decorations, the entire VS Code UI locks up for about 3-5 seconds before the decoration menu appears:
![Recording 2022-03-24 at 19 51 02](https://user-images.githubusercontent.com/30305945/160045089-1bd1718b-1d97-496d-8f6b-e171c501151e.gif)

**Comment by Tyriar** [comment]
@joyceerhl how did you get the error icon to overlap the other icon on the first line? I'm guessing this is a Windows only problem.

**Comment by joyceerhl** [comment]
OK, repro steps (this is reproducible 100% of the time for me):

1. Run a command
2. Run Terminal: Clear
3. Run another command
4. Run Terminal: Clear again
5. :bug: decorations overlaid

https://user-images.githubusercontent.com/30305945/160165573-7230eeff-e9a0-453b-8f8b-72e42980d46f.mp4

**Comment by meganrogge** [comment]
on Mac cannot repro - possibly because of [this bug](https://github.com/microsoft/vscode/issues/145148)

https://user-images.githubusercontent.com/29464607/160446112-1b77c12e-7559-4d7d-98d5-a9c416801b9e.mov

**Comment by Tyriar** [comment]
Think this is a Windows problem

**Comment by Tyriar** [comment]
Deferring this as it's pretty low impact

**Comment by meganrogge** [comment]
can't reproduce anymore
