### ISSUE TITLE
Terminal link hover doesn't go away unless tooltip is hovered

### ISSUE THREAD

**Issue by jibbers42** [microsoft/vscode#144583]
Issue Type: <b>Feature Request</b>

I'd like an option to disable the "Open file in editor (ctrl + click)" tooltip in the terminal that pops up when the mouse rests over a file path. If you are in a section with a lot of paths, like a stack trace, then the tool tip can easily pop up when you don't want it to. Simply moving the mouse away from the path or even clicking a blank spot isn't enough to dismiss the tooltip; you have to mouse over it.

One example output that has a lot of paths is a stack trace from something like test errors. I use the mouse wheel to scroll this type of output and have to be very careful where the mouse is to not get the pop up. I find the path underlining on hover to be enough to know you can open it with the mouse.

I did a search in settings for `tooltip` and didn't see a relevant setting.

![image](https://user-images.githubusercontent.com/797824/157035515-aec198ab-e4ed-4a79-9cc8-c7f39c9678e4.png)

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

**Comment by Tyriar** [comment]
I noticed today the pointer-events fix now causes the hover not to hide unless you hover the tooltip. We wouldn't want a new setting but to fix that bug.
