### ISSUE TITLE
Customizing Individual Syntax Element Color

### ISSUE THREAD

**Issue by Triangle4** [microsoft/vscode#144533]
Recently, you updated the dark theme for C# to have constructors show up as the same color as a type, instead of a method. 
This is creating mass confusion. 
I would think by now, it would be a high priority to give the general community a way to edit the individual syntax element colors.
Please add a feature for this, I need my constructors back to the normal yellow.
Also, my using tags are now blue. Its weird, because on a refresh, they turn to their normal color and then everything turn blue like a type.

**Comment by aeschli** [comment]
Can you provide
- a small code sample
- name the theme that you are using.
- add a screenshot
- Set the cursor on the constructor and use the `Developer: Inspect Editor Tokens and Scopes...` command and make a screenshot of the hover
