### ISSUE TITLE
issue in power calculaion by using for loop

### ISSUE THREAD

**Issue by dhirajnande0461** [microsoft/vscode#144575]
``#include <stdio.h>
#include <math.h>
int main()
{
    int numb, power;
    for (int i = 0; i < 10; i++)
    {
        numb = pow(10, i);
        printf("%d\n", numb);
    }
    power = pow(10, 0);
    printf("\n\n\n%d\n", power);
    power = pow(10, 1);
    printf("\n\n\n%d\n", power);
    power = pow(10, 2);
    printf("\n\n\n%d\n", power);
    power = pow(10, 3);
    printf("\n\n\n%d\n", power);
    power = pow(10, 4);
    printf("\n\n\n%d\n", power);
    power = pow(10, 5);
    printf("\n\n\n%d\n", power);
    power = pow(10, 6);
    printf("\n\n\n%d\n", power);
    power = pow(10, 7);
    printf("\n\n\n%d\n", power);
    power = pow(10, 8);
    printf("\n\n\n%d\n", power);
    power = pow(10, 9);
    printf("\n\n\n%d\n", power);

    return 0;
}

**Comment by Tyriar** [comment]
This isn't anything to do with vscode.
