### ISSUE TITLE
Theme statusbar small issue

### ISSUE THREAD

**Issue by i007c** [microsoft/vscode#144586]
https://github.com/microsoft/vscode/blob/5fbfb8a751ef86d94ac1cc5d9c0bb636ae7448dd/src/vs/workbench/browser/parts/statusbar/media/statusbarpart.css#L18

Iam assuming that you meant `--vscode-statusBar-focusBorder` instead of `--statusbar-focusborder`

**Comment by daviddossett** [comment]
Fixed via 0140fba8bb128d7481a4bcd380de774ab1210c5d

Had we not already been using JS to style dynamic bits in the status bar, I'd have used the normal `--vscode..` token as you displayed. Thanks for the catch 🙏
