### ISSUE TITLE
A full tab bar has a 1px wide section to the left of the actions that has the hand cursor but doesn't work as expected

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14459]
Testing #14016

This potentially also happens on the very edge of a non-full tab bar, dragging on this specific spot does not drag the editor group as I would expect. I assume that there is a CSS cursor style in a `:hover` rule that does not match the element that you actually grab.

![img_20161025_101521](https://cloud.githubusercontent.com/assets/2193314/19696587/9da21630-9a9c-11e6-8893-d20327efd1fd.jpg)

**Comment by bpasero** [comment]
good catch
