### ISSUE TITLE
Jupyter notebook output font is not proportional anymore

### ISSUE THREAD

**Issue by adamsatyr** [microsoft/vscode#144579]
We have written the needed data into your clipboard because it was too
Issue Type: <b>Bug</b>

Please change back output of notebook to proportional font.
Like, why? Why would you even change that?

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz (12 x 3096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.34GB (0.74GB free)|
|Process Argv|--crash-reporter-id 0a583669-9aef-4d37-bcbc-188cc8e424c2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.19
json-tools|eri|1.0.2
gitkraken-authentication|git|1.0.3
gitlab-workflow|Git|3.40.2
gc-excelviewer|Gra|4.0.50
rainbow-csv|mec|2.0.0
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.0
jupyter|ms-|2022.2.1020642448
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
powershell|ms-|2021.12.0
indent-rainbow|ode|8.2.2
code-spell-checker|str|2.1.7
pdf|tom|1.2.0
markdown-all-in-one|yzh|3.4.0

</details>

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/commit/8c73ac4811b6aabf59a7f02c08cd0df4997961fc
