### ISSUE TITLE
Powershell last statement output not seen

### ISSUE THREAD

**Issue by jbruns2015** [Microsoft/vscode#14458]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: ms-vscode.PowerShell-0.7.2

Steps to Reproduce:

This shows me '1' in debug console
$a = 1
Write-Host $a
Exit

This shows me nothing in debug console
$a = 1
Write-Host $a

**Comment by jbruns2015** [comment]
If I do not use breakpoints and run this:

$a = 1
Write-Host $a
Exit

I don't see the '1' in the Output console or the Debug Console.

**Comment by weinand** [comment]
This issue was moved to PowerShell/vscode-powershell#326
