### ISSUE TITLE
Visual Studio code opens two windows on launch

### ISSUE THREAD

**Issue by miguelangelss4** [microsoft/vscode#144569]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.65.0 (user setup)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:12:08.962Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
- OS Version: Windows 10 Enterprise 21H2 19044.1526

Always I open vscode, it open two windows: one with my last forlder opened and other one with nothing open, only an empty instance of vscode.

Steps to Reproduce: 

1. Open vscode from any method (shortcut, start menu item, taskbar pinned item, by terminal, by terminal with --disable-extensions option, or using the shortcuts only with keyboard avoiding use of mouse.

That is not a duplicate of [#77302](19044.1526), I tested opening only using keyboard, using different mouses. Always same result.

**Comment by miguelangelss4** [comment]
I can't post the gif generated, its size is always much more tahn 10MB. I uploaded one here: [](https://gfycat.com/gleefulashamedfritillarybutterfly).

It doesn't matter how you open the vs code: by console, shortcut, or in any way (with mouse or only with keyboard), it ALWAYS opens two windows of the vs code.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by miguelangelss4** [comment]
The computer is corporate, I can't install or uninstall anything (it is done by the IT administrator of the organization).
I can ask them to look at the installation, but they ask me if I can have both versions installed: the one I have now without touching any of its installation or configuration, and the one for insiders.
I have several projects that depend on vscode for debugging and I can't afford the risk that the configuration will be messed up and we need to spend time recovering it.
(apologies for my English)

**Comment by bpasero** [comment]
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by miguelangelss4** [comment]
Doing this opens only one vscode window, without extensions loaded or any folder opened.

**Comment by bpasero** [comment]
Then I suspect there is something off withe the standard user data directory. Maybe a backup that fails to restore, is there anything in `C:\Users\<your name>\AppData\Roaming\Code\Backups`

**Comment by miguelangelss4** [comment]
Yes, it is something there:
![image](https://user-images.githubusercontent.com/15887424/157428752-d9e1afbf-acaf-4719-a110-5a7800158959.png)

Today vscode is blocking my CPU:
![image](https://user-images.githubusercontent.com/15887424/157428891-08e6e0ea-ae45-4b50-b5ce-48ec6a53fa3c.png)

it can be related with `code --disable-extensions --user-data-dir <directory>` command? this never hapenned before.

**Comment by bpasero** [comment]
If you close all instances and copy this folder away to your desktop or somewhere else safe just in case it is changes you want to preserve it should be fine.

**Comment by miguelangelss4** [comment]
Apparently, moving that solved the issue. Thanks!
