### ISSUE TITLE
`vscode.proposed.tabs.d.ts` feedback

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#144605]
I wonder why we end up having a `window.tabGroups` property and not something along the lines of `TextEditor`:
* `window.activeTabGroup: TabGroup`
* `window.visibleTabGroups: TabGroup[]`
* `window.onDidChangeTabGroup`
* `window.onDidChangeActiveTabGroup`

If we decide to keep `window.tabGroups` I find it a bit inconsistent to have `tabGroups.all` and `tabGroup.tabs` where the one uses `all` for the "thing" that is contained and the other uses a specific name of "what" is contained.

PS: happy to join API finalization call when you let me know when that is

**Comment by lramos15** [comment]
The idea is that the window contains a grid (which we call tabGroups) so it should be the only thing that lives on the window object and everything lives inside that. I agree `all` is weird though so may decide to rename it to `window.tabGroups.groups`
