### ISSUE TITLE
Render output expression between $$ $$ as TeX

### ISSUE THREAD

**Issue by pammacdotnet** [microsoft/vscode#144628]
Dear developers, 

The output delivered by the standard Jupyter interface and VS code is different when the output expression is between $$ $$. Please see image attached. I think the behaviour should be the same. BTW, the kernel is [Wolfram](https://github.com/WolframResearch/WolframLanguageForJupyter). 
![vectores_-_Jupyter_Notebook](https://user-images.githubusercontent.com/4954983/156844161-63a3db27-26d1-47db-acef-033d99268214.png)

**Comment by greazer** [comment]
VS Code core handles rendering of latex in output.

**Comment by pammacdotnet** [comment]
But… is it solvable in the VS Code side?

**Comment by mjbvz** [comment]
I'm closing this as by-design. Two reasons:

The output mimetype in this case seems to be `text/html`. We don't render math markup inside html (which maybe other notebook editors do, but that seems like a very strange thing to do to me)

Furthermore, the output is then encoded in a form that we would not recognize even if you were to write it in markdown (again it seems very weird to me that you'd want to run a math pass after decoding the output but 🤷 )

If someone can explain why these design decisions make sense or if there's enough feedback on this, we can revisit it in the future

**Comment by pammacdotnet** [comment]
Ok, thanks for taking my concern into account. Anything I could tell the [Wolfram Jupyter team](https://github.com/WolframResearch/WolframLanguageForJupyter) so that their output is more VS code compatible? Could you please tell me what should I tell them specifically? Thanks in advance.

**Comment by mjbvz** [comment]
Again I don't know if there's a standard for this but my suggestion from the outside are:

- Don't encode the output unnecessarily (and specifically don't encode characters that have meaning in the markup that is to be rendered)

- Use `text/markdown` as the output mime type if the output contains math markup. Markdown also allows embedded html if you need to go beyond standard markdown+math syntax
