### ISSUE TITLE
Search using Regex is broken

### ISSUE THREAD

**Issue by zabcik** [microsoft/vscode#144663]
Issue Type: <b>Bug</b>

Search using Regex is broken when file is not opened in Editor...
If I open file then Regex searching works as expected.

There is sample of problematic Regex:
https://regex101.com/r/kFtSye/1

Pattern: 
\bfield\b\(.*\)\s*\n*\{[^\}]*\s+FieldClass = FlowField;[^\}]*\}

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

![img1](https://user-images.githubusercontent.com/19779185/157215934-7fccfaad-eb2e-400b-a47a-2a9e106d6080.png)
![img2](https://user-images.githubusercontent.com/19779185/157215937-8acfa3bf-fdc5-471c-83cb-b63d50749d90.png)
![img3](https://user-images.githubusercontent.com/19779185/157215941-7eaf45e1-fe58-439e-9d67-6473fc1c79d8.png)

**Comment by roblourens** [comment]
This is the same underlying issue as https://github.com/microsoft/vscode/issues/131507
