### ISSUE TITLE
"terminal.integrated.env.linux" was broken on 1.65

### ISSUE THREAD

**Issue by asanoic** [microsoft/vscode#144685]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65
- OS Version: Debian Bullseye

Steps to Reproduce:

1. add 
```
    "terminal.integrated.env.linux": {
        "PATH": "/opt/node/bin:${env:PATH}",
    },
```
   to settings.json

2. restart terminal, and `echo $PATH`

**Comment by crobertdiii** [comment]
I've experienced this issue too - tried backdating to previous versions and issue was not resolved. It appears that none of the user environment variables are being expanded anymore.
