### ISSUE TITLE
Finalise notebook API for notebook document change events

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#144662]
LSP adds support for notebooks but currently depends on some proposed API, mostly events for saving and observe changes to the document. We should investigate what it takes to finalise those

* [x] support `notebookType` in document selectors
* [x] notebook document events -> `src/vscode-dts/vscode.proposed.notebookDocumentEvents.d.ts`

**Comment by jrieken** [comment]
fyi @dbaeumer @rebornix

**Comment by jrieken** [comment]
fyi @karthiknadig The simplified events are defined in https://github.com/microsoft/vscode/blob/d4c26aa154f2506614f5a292bc598c7ce07dbf36/src/vscode-dts/vscode.proposed.notebookDocumentEvents.d.ts. They will replace the following events defined in `vscode.notebook` (from the [`notebookEditor`](https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vscode-dts/vscode.proposed.notebookEditor.d.ts)-proposal): 

* ~~`vscode.notebook.onDidChangeCellMetadata`~~ -> replaced with `vscode.workspace.onDidChangeNotebookDocument` 
* ~~`onDidChangeCellOutputs`~~ -> replaced with `vscode.workspace.onDidChangeNotebookDocument`  
* ~~`onDidChangeNotebookCells`~~ -> replaced with `vscode.workspace.onDidChangeNotebookDocument` 
* ~~`onDidChangeNotebookDocumentMetadata`~~ -> replaced with `vscode.workspace.onDidChangeNotebookDocument` 
* ~~`vscode.notebook.onDidSaveNotebookDocument`~~ -> moved into `vscode.workspace`, no other changes

**Comment by dbaeumer** [comment]
Did the same for Pylance and eslint so we can move off when I have released a new version of the LSP libs

**Comment by jrieken** [comment]
Moving to April for

* removal of the old events
* finalisation attempt of the new events

**Comment by jrieken** [comment]
Moving to April for

* removal of the old events
* finalisation attempt of the new events

**Comment by DonJayamanne** [comment]
> I have enroled ms-toolsai.jupyter into the notebookDocumentEvents proposal meaning the extension can migrate safely.

Done

**Comment by dbaeumer** [comment]
Thanks!!

**Comment by jrieken** [comment]
To verify:

make sure `vscode.d.ts` has `vscode.workspace.onDidChangeNotebookDocument` and `vscode.workspace.onDidSaveNotebookDocument`
