### ISSUE TITLE
Crl + z within find and replace window of Jupyter notebook deletes document

### ISSUE THREAD

**Issue by peterbartlett64** [microsoft/vscode#144602]
Issue Type: <b>Bug</b>

Within a jupyter notebook containg multiple sections:
1. Search for a value which is contained
2. Find and replace with another value
3. With the cursor still within the replace input, press ctrl + z

This will irriversibly delete the entire document and replace with a single empty section. Becuase undo is specific to the section which modifications have been made in, there is no way to reverse the delete.

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (3.00GB free)|
|Process Argv|--crash-reporter-id 1fa9ebb7-6f1e-450a-a47c-c5ec85f85730|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.2
python-preview|don|0.0.4
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
vscode-install-vsix|fab|1.4.0
matlab|Gim|2.3.1
vscode-pull-request-github|Git|0.38.0
fluent-icons|mig|0.0.17
anaconda-extension-pack|ms-|1.0.1
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.0
jupyter|ms-|2022.2.1020642448
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
atom-keybindings|ms-|3.0.9
cpptools|ms-|1.8.4
powershell|ms-|2021.12.0
indent-rainbow|ode|8.2.2
vscode-commons|red|0.0.6
vscode-yaml|red|1.5.0
snakemake-lang|sna|0.1.6
snakefmt|tfe|0.1.0
material-theme|zhu|3.13.20

(10 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrt:30448491
vsrem710cf:30416617
dsvsc009:30440023
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvid2:30447481
helix:30440343

```

</details>

**Comment by rebornix** [comment]
> Thanks for the bug report, we should prevent undo of document when focus is in the find widget.

I can't reproduce this in today's Insiders though. It would be great if you can share some more details about how to reproduce it more stably?

**Comment by peterbartlett64** [comment]
When I posted I was able to do it 5 times in a row. Since then I have disabled and re-enabled the Jupyter extension.  I am no longer able to get the same issue. If I am able to get the same bug, I will be sure to update this chain.

**Comment by peterbartlett64** [comment]
When I posted, I was able to get the bug 5 times in a row. Since then I have disabled and re-enabled the Jupyter extension. I am no longer able to get the same issue. If I encounter the bug again, I will be sure to update this chain.
