### ISSUE TITLE
Allow extensions to report "additional"/groups of references via ReferenceProvider

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#144699]
Find References/`ReferenceProvider` can return multiple results, but they all appear in a flat list and are treated equally. In some cases, a language server might want to return some additional references that are of interest, but are not strictly references to what was requested.

For example, let's say you have code using a Builder pattern. The Builder may be code-gen'd and in a different file:

```ts
// user_builder.generated.ts
export class UserBuilder {
	private readonly _user: User = {
		name: "",
	};

	public set name(name: string) {
		this._user.name = name;
	}

	build(): User {
		return this._user;
	}
}
```

Code that defines the `User` class and uses the builder may look like this:

```ts
export interface User {
	name: string; // Do find references on `name` here
}

const builder = new UserBuilder();
builder.name = "Danny"; // This is not a direct reference
const user = builder.build();
```

If the user does "Find References" on `name` in the `User` interface, it will not include the setting of `builder.name` near the end, because it's not a direct reference. However, in this case it's possible the user would be very interested in this reference because if they're doing Find References on `name`, they might be looking for all places that set names for `User`s.

It would be nice if a language server/extension could provide additional references like this, that are visually separated in the UI, for example:

<img width="1250" alt="Screenshot 2022-03-08 at 17 57 00" src="https://user-images.githubusercontent.com/1078012/157297739-c89fc64d-d080-4cbc-8eaf-9631cfb78eb2.png">

Note: Although I've used TypeScript as an example here for familiarity, I'm not necessarily asking for TypeScript to support the scenario above, I'm interested in VS Code having the API for other extensions/language servers to be able to use where they might have this sort of data.

**Comment by jrieken** [comment]
folding this issue into https://github.com/microsoft/vscode/issues/74237

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"editor-symbols"

**Comment by DanTup** [comment]
Do you mean a different issue to https://github.com/microsoft/vscode/issues/74237 you linked above, or that one? That does seem the same to me (sorry I missed it while searching... the GH search isn't amazing 🙃). Thanks!
