### ISSUE TITLE
Git colors in Light HC on web appear off in vscode.dev

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#144607]
<img width="290" alt="CleanShot 2022-03-07 at 08 36 30@2x" src="https://user-images.githubusercontent.com/35271042/157077190-2ac28d70-15f3-419e-a9e2-8922077df8b5.png">

Steps to reproduce:
1. open a repo on vscode.dev
2. have changes committed to the same repo from different source
3. :bug: git colors appear lighter

These colors appear different from regular modified files:

<img width="250" src="https://user-images.githubusercontent.com/35271042/157078225-4d47fee9-0847-491b-9b5f-bc09e62791e2.png">

Seems like these are unique color tokens @joyceerhl? Inspecting reveals these tokens coming from remotehub:

- `remoteHub.decorations.addedForegroundColor`
- `remoteHub.decorations.conflictForegroundColor`
- `remoteHub.decorations.deletedForegroundColor`
- `remoteHub.decorations.incomingAddedForegroundColor`
- `remoteHub.decorations.incomingDeletedForegroundColor`
- `remoteHub.decorations.incomingModifiedForegroundColor`
- `remoteHub.decorations.incomingRenamedForegroundColor`
- `remoteHub.decorations.modifiedForegroundColor`
- `remoteHub.decorations.possibleConflictForegroundColor`
- `remoteHub.decorations.workspaceRepositoriesView.hasUncommittedChangesForegroundColor`

**Comment by joyceerhl** [comment]
Related: https://github.com/microsoft/vscode-remote-repositories-github/issues/123

**Comment by daviddossett** [comment]
Certainly a contrast issue in this context. However I'm wondering if the foreground text color actually needs to be different from a local modification in the first place since we have the special icon? 

In any case, where are these tokens defined @joyceerhl? My initial thought is to align them to the normal git tokens in an HC context to avoid really subtle differences.

**Comment by joyceerhl** [comment]
Sent you a pointer to the token definitions on Slack. AFAIK these colors haven't changed in months--I personally like the foreground text color being lighter but I assume there's an a11y concern at play with these defaults?

**Comment by daviddossett** [comment]
Based on what I saw, the tokens defined for high contrast themes are hardcoded for dark HC themes. So I'd guess they work perfectly fine with our existing dark HC theme.

Unless we have another way of doing so, I'd guess we would have to wait until @aeschli splits the theme types into `hc-light` and `hc-dark` so we're able to serve specific tokens for light HC themes. I'm sure I'm over-simplifying it but that's my general thinking of how this could be staged.

**Comment by daviddossett** [comment]
FYI now that #144759 has been merged there should be a contribution point for `highContrast` and `highContrastLight` now: 

```
"colors": [
      {
        "id": "gitDecoration.addedResourceForeground",
        "description": "%colors.added%",
        "defaults": {
          "light": "#587c0c",
          "dark": "#81b88b",
          "highContrast": "#1b5225"
          "highContrastLight": "#587c0c"
        }
      }
    ]
```

What do you think about copying the git colors contributed for `highContrastLight` [here](https://github.com/microsoft/vscode/pull/144759/files#diff-d23089c2fa38a847e0a53ecab3dac76b63d4e8d21aa297c6e06e4f0fb7d86c11) for their remote hub counterparts? I feel that HC users wouldn't benefit from the subtle color variations given that they both need to be quite dark to meet our contrast bar.

**Comment by joyceerhl** [comment]
Thanks for following up--I've added the `highContrastLight` defaults for RemoteHub's tokens.

**Comment by joyceerhl** [comment]
Going to close this so it'll get verified during endgame--feel free to reopen if necessary!
