### ISSUE TITLE
consider to use an existing file name when generating program attribute

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#14462]
Testing https://github.com/Microsoft/vscode/issues/13585:
- VSCode Version: 1.7.0
- OS Version: Win 10

I had a single 'test.ts' file open in VS Code and the generated launch.json got a 'sourceMaps' and 'outFiles' attribute but the program path uses 'app.js'. This mismatch looks strange.

I suggest to use the path of the open file (if there is exactly one) or let the user pick a file (if there are more). The same could be done for js projects.

**Comment by isidorn** [comment]
Was discussing this with @egamma in the tram.
The downside of this approach is that it can be confusing for the user and the user might not be aware how this file was picked. It can be especiially confusing if we provide a choice and none of the files is the actual entry point.
It might be more intuitive to put something that obviously needs to be changed. I know that Powershell and C++ do something in the likes of 'PUT_NAME_HERE'

Anyways it is up to the node debug to imelment it anyway it wants

**Comment by isidorn** [comment]
This is now in the control of the debug extensions with the start debug command
