### ISSUE TITLE
Edge of the application window

### ISSUE THREAD

**Issue by yalin** [microsoft/vscode#144642]
Issue Type: <b>Bug</b>

I am using Ubuntu 20.04. When I open VSCode, the left and right top edge of the program is rounded ; [https://i.imgur.com/S1P9KqD.png](https://i.imgur.com/S1P9KqD.png)
But, when I maximize the window clicking square button and then clicking it again (going back to windowed size) breaks the edge's roundness; [https://i.imgur.com/aFMpA3V.png](https://i.imgur.com/aFMpA3V.png)
I don't know if it is noticable but, there is a small black area at the corner. This is not a functional issue. I just want to inform.
Thank you

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:36.248Z)
OS version: Linux x64 5.13.0-30-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|15.28GB (2.16GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 273268cc-70f3-455a-a78a-ea2bb12dc1d8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
quasar-snippets|abd|1.0.0
shaderlabvscodefree|aml|1.2.9
vscode-database|baj|2.2.3
print-it|bma|0.1.5
vscode-intelephense-client|bme|1.8.2
gitignore|cod|0.7.0
bracket-pair-colorizer|Coe|1.0.62
dart-code|Dar|3.36.0
flutter|Dar|3.36.0
vscode-eslint|dba|2.2.2
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.83
prettier-vscode|esb|9.3.0
auto-close-tag|for|0.5.14
html-preview-vscode|geo|0.2.5
gc-excelviewer|Gra|4.0.50
beautify|Hoo|1.5.0
volar|joh|0.32.1
vscode-csharp-snippets|jor|1.1.0
docomment|k--|0.1.30
swift|Kas|0.2.0
vsc-python-indent|Kev|1.14.2
unity-code-snippets|kle|1.3.0
vscode-github|Kni|0.30.7
MagicPython|mag|1.1.0
gitignore|mic|1.0.1
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.20
csharp|ms-|1.24.1
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.0
jupyter|ms-|2022.2.1030672458
cpptools|ms-|1.8.4
debugger-for-chrome|msj|4.13.0
latex-formatter|nic|1.0.5
vetur|oct|0.35.0
material-icon-theme|PKi|4.14.0
vscode-thunder-client|ran|1.12.2
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.4
vs-code-prettier-eslint|rve|3.1.0
glassit|s-n|0.2.4
gruvbox-material|sai|6.5.0
shader|sle|1.1.5
vscode-stylelint|sty|1.2.2
cwtools-vscode|tbo|0.9.10
ayu|tea|1.0.5
open-in-browser|tec|2.0.0
unity-tools|Tob|1.2.12
vscode-icons|vsc|11.10.0
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0
unity-snippets|Ycl|0.1.2

(11 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30448491
dsvsc008:30440022
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvid1:30447480
helix:30440343

```

</details>

**Comment by luoriyuhui21** [comment]
the issue seems related to window manager in linux, the window is decorated by window manager and the corner become rounded, I guess.

**Comment by yalin** [comment]
> the issue seems related to window manager in linux, the window is decorated by window manager and the corner become rounded, I guess.

I guess you are right. I thought it is the design of VSCode but I guess it is related to Linux UI. I mark it closed, sorry.

**Comment by rzhao271** [comment]
Hi @yalin, 

Does the problem occur when you open other programs such as the file explorer or web browser?
If not, does the problem occur when you download, install, and open the Electron Fiddle program? https://www.electronjs.org/fiddle

Answering these questions can help us start to narrow down whether the issue is specific to VS Code, Electron, or the OS.

**Comment by yalin** [comment]
> Hi @yalin,
> 
> Does the problem occur when you open other programs such as the file explorer or web browser? If not, does the problem occur when you download, install, and open the Electron Fiddle program? https://www.electronjs.org/fiddle
> 
> Answering these questions can help us start to narrow down whether the issue is specific to VS Code, Electron, or the OS.

@rzhao271 Yes, I've tried and the problem is with the Linux window manager. I closed the post. Thank you :)
