### ISSUE TITLE
Cannot disable `new file/jupyter notebook (ipynb)`.

### ISSUE THREAD

**Issue by hxsf** [microsoft/vscode#144667]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.0
- OS Version: Darwin x64 21.3.0

Steps to Reproduce:

1. click the `new file` button in Start Page or menu -> file / new file...
2.  <img width="698" alt="image" src="https://user-images.githubusercontent.com/7581607/157218825-12f69655-4e7d-4c54-9dc2-ea4286f22f5a.png">

I read the source code.
https://github.com/microsoft/vscode/blob/1a9016d0a4aa0eb98fd6dce3baf1678a3ccc35b9/extensions/ipynb/package.json#L53-L59
if I don't have plugin:python installed. plugin:ipynb will show this for me.
or I install plugin:python, plugin:jupyter wil show another for me.
I just need a simple behaive for `new File`: 'just open a new tab. and let me write something'.

I try to disable built-in plugin, and no way.
Can we add a setting to disable built-in plugins?
Maybe it will make launch fast, and just enable what we need.

**Comment by rebornix** [comment]
<img width="397" alt="image" src="https://user-images.githubusercontent.com/876920/157534968-5ca5eeee-8d83-4414-8be8-3987835db266.png">

shouldn't File -> New create an untitled file you?

**Comment by hxsf** [comment]
`New File` works fine.
`New File...` will open the dialog.

and the `New File...` in  `Get Started` page open the dialog too.
<img width="451" alt="image" src="https://user-images.githubusercontent.com/7581607/157577909-317455ab-b94e-4ebb-a330-ea5d0c3560f9.png">

BTW, can we have some options or settings to disable built-in plugin we don't need.

**Comment by JacksonKearl** [comment]
It's intentional that the `New File...` menu opens that quick pick. I've made some changes to ensure the "Text File" entry is always at the top of the quick pick to make that easier to access. If you just want to open a new text file without bothering with the quick pick or menu, I recommend `Ctrl/Cmd+N`.
