### ISSUE TITLE
Preserve editor relative sizes when switching layouts

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14464]
Testing #14016
- VSCode Version: Code - Insiders 1.7.0-insider (5bafcdb3d67b29b1f4667a3f497ac05a41dde667, 2016-10-25T06:19:07.301Z)
- OS Version: Linux x64 4.4.0-45-generic, Ubuntu 16.04
- Extensions:

| Extension | Author | Version |
| --- | --- | --- |
| EditorConfig | EditorConfig | 0.3.4 |
| lorem-ipsum | Tyriar | 1.0.0 |
| sort-lines | Tyriar | 1.1.0 |
| terminal-tabs | Tyriar | 0.0.6 |
| theme-glacier | Tyriar | 0.0.10 |
| vscode-icontheme-nomo-dark | be5invis | 1.1.5 |
| vscode-svgviewer | cssho | 1.2.0 |
| vscode-eslint | dbaeumer | 1.0.8 |
| git-project-manager | felipecaputo | 0.1.15 |
| Theme-Wombat | gerane | 0.0.2 |
| csharp | ms-vscode | 1.4.1 |
| typescript-javascript-grammar | ms-vscode | 0.0.6 |
| nova | rebornix | 0.0.5 |
| sass-indented | robinbentley | 1.1.0 |
| annotator | ryu1kn | 0.10.1 |

Steps to Reproduce:
1. Open 2 editor groups
2. "Minimize" one to enable snapping
3. Toggle editor group layout, the editor groups will both be the default sizes.

**Comment by rebornix** [comment]
After the third step @Tyriar mentioned above, if you do a fourth step `Toggle editor group layout` which switches back the previous layout, snapping state should be retained at least.

**Comment by charlespierce** [comment]
I'm interested in tackling this feature request. From a quick look, it appears to be relatively straightforward, but I'm curious if there are any potential pitfalls that immediately jump out to be aware of?

**Comment by bpasero** [comment]
* [ ] **To verify:** 
Switch the editor layout and verify the editor dimensions are kept relatively.
