### ISSUE TITLE
ipynb stops giving outputs and background turns gray

### ISSUE THREAD

**Issue by josemariamoreira** [microsoft/vscode#144674]
Issue Type: <b>Performance Issue</b>

The occurance does not happen after a specific series of steps. Sometimes the notebook runs without problems, up until a point where it stops working properly. Last time I opened the notebook, I didn't even run any cell, and the background already turned gray. I thought it would be a RAM issue (because the dataframes I am using are rather big), but even using a small sample, I run into the same problem.

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (24.55GB free)|
|Process Argv|--crash-reporter-id 534dbc00-0bcb-4348-a54d-542b33ad4276|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by wdeaderick** [comment]
Also experiencing this same issue. Deleted all VSCode files and reinstalled, but it's still happening. Oftentimes the application will crash or stop responding shortly after this happens.

**Comment by wdeaderick** [comment]
Sorry, what issue is this a duplicate of...? Still unresolved for me

**Comment by wdeaderick** [comment]
@rebornix
