### ISSUE TITLE
View menu Toggle Editor Group Layout does not show warning as Command Palette does

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#14466]
Testing #14016

When there is only one editor group

* In "opened editors" view, toggle editor group button is greyed out. 
* If you try to change layout through Command palette, a warning box pops up saying `Command 'View: Toggle Editor Group Layout' is not enabled in the current context.`
* If you press `Toggle Editor Group Layout` in Menu, nothing happens.

The later two behaviors need to be consistent.

**Comment by bpasero** [comment]
I have another bug that asks to just always enable this action and I kind of agree because it allows to toggle the layout and then start to open editors. Closing as duplicate.
