### ISSUE TITLE
Sometimes `cursor: grabbing` behaves weird when dragging an editor group

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14461]
Testing #14016

Similar to DND in the explorer, the style should be applied when dragging an editor group as another indication it's "grabbed".

**Comment by bpasero** [comment]
@Tyriar but we do: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/media/titlecontrol.css#L86

**Comment by Tyriar** [comment]
Oh this is about the empty space on the editor group, not the tabs (which work fine).

**Comment by bpasero** [comment]
@Tyriar I am confused, are you saying the cursor should change to dragged when dragging an explorer file over the editor group?

**Comment by Tyriar** [comment]
This is about dragging the empty area in the editor group to drag the editor group to another position. After playing with it a bit the grabbing cursor seems to apply after a bit of movement, particularly vertical movement. Here's a picture showing the issue:

![image](https://cloud.githubusercontent.com/assets/2193314/19713969/201e6c3c-9aff-11e6-8c75-cf11d5221674.png)

This is after dragging it back and forth horizontally a few times.

**Comment by bpasero** [comment]
I am sorry I do not understand the issue. Please reopen it after you are able to explain it. Thanks.

**Comment by bpasero** [comment]
Is this about the fact that the cursor only turns to grabbing after a bit of movement?

**Comment by Tyriar** [comment]
@bpasero after a lot of movement, and movement mainly along the horizontal axis doesn't seem to trigger it. You can grab the editor group and move it to another position without the grabbing cursor activating.

**Comment by bpasero** [comment]
I have seen Chrome behave weird with regards to this cursor where often the hand would not grab but only show as hand for some weird reason. 

The only thing I see now is that the hand removes when I start to drag, move the mouse above the editor title out of the window and back into the editor title. Then the cursor seems to be the arrow and never change back to the hand. Is that what you see too?

**Comment by Tyriar** [comment]
Yeah I see the fixed arrow after going out of the window too.

**Comment by bpasero** [comment]
I suspect a Chrome bug since it happens randomly (I just had the case of the hand not grabbing until I release the mouse...).

**Comment by bpasero** [comment]
@Tyriar seems a bit better for me when I try with a newer Electron. If you wanna check it out: https://az764295.vo.msecnd.net/insider/ae0002b4ac8290e1572c2d243c112783fcfa7ec9/code-insider-1.8.0-1478856193_amd64.tar.gz
