### ISSUE TITLE
Maximize terminal pane button disappeared

### ISSUE THREAD

**Issue by adriancuadrado** [microsoft/vscode#144688]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0
- OS Version: Windows 10

![image](https://user-images.githubusercontent.com/29214635/157264018-194c6a08-efcc-4de6-9748-64ec06d77dc7.png)

The `View: Toggle Maximized Panel` is not there either.

![image](https://user-images.githubusercontent.com/29214635/157268115-6b9312bd-c28f-42fd-bda4-10b73160b588.png)

Steps to Reproduce:

1. Open VSCode and then open the terminal pane or search in the command palette for `View: Toggle Maximized Panel`.

![image](https://user-images.githubusercontent.com/29214635/157268764-298423ff-0d18-4df7-b9a0-32f36c645262.png)

**Comment by vngmar** [comment]
It has, in a way. If you right click on the top area between DEBUG CONSOLE and the Terminal Selection area and select "Move Views to Panel," it will reappear. Elsewhere, someone got mad at me for questioning the reason why that was done.

**Comment by sbatten** [comment]
@adriancuadrado are you using a non-center panel alignment? the panel cannot be maximized in this configuration and there is an existing feature request for this. to get back to "center panel alignment", run the command `Set Panel alignment to Center`

**Comment by adriancuadrado** [comment]
@vngmar Your solution didn't work, but @sbatten 's one worked like a charm.

![image](https://user-images.githubusercontent.com/29214635/157286852-f4aa71ed-321d-4ef4-8bf1-153c206f8d61.png)
![image](https://user-images.githubusercontent.com/29214635/157286871-a49cb93b-657d-468a-bb87-d7232579deef.png)

**Comment by vngmar** [comment]
> @vngmar Your solution didn't work, but @sbatten 's one worked like a charm.
> 
> ![image](https://user-images.githubusercontent.com/29214635/157286852-f4aa71ed-321d-4ef4-8bf1-153c206f8d61.png) ![image](https://user-images.githubusercontent.com/29214635/157286871-a49cb93b-657d-468a-bb87-d7232579deef.png)

Good! I certainly misunderstood what you were looking for.
