### ISSUE TITLE
Hover view problem/quick fix dialog is not selectable

### ISSUE THREAD

**Issue by iamn1ck** [microsoft/vscode#144655]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0
- OS Version: Arch Linux x86_64 Kernel: 5.16.12-arch1-1 
          
Steps to Reproduce:

1. Have some error in you code
2. Hover over the offending line
3. Try to select View Problem or Quick Fix
4. The dialog disappears unexpectedly

This bug has been in vscode for over a year now and I am not sure how it has gone unnoticed. This feature was last working on version 1.55.2 and I have been using that version for the last year, however I need to update to a newer version of vscode.

I have also attached a video of the problem below

https://user-images.githubusercontent.com/3345597/157207056-bca291bf-c752-44b9-8dc9-e28e9052f8ba.mp4

**Comment by alexdima** [comment]
I can't reproduce on Ubuntu 20.04. `1.56` coincides with our update to Electron 12. I see many issues in our issue tracker [labeled with `electron-12-update`](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aelectron-12-update) that are related to wayland. Are you using wayland?

https://user-images.githubusercontent.com/5047891/157317057-5da5431a-e4af-47d2-84fe-0db68ccfc83d.mp4

**Comment by iamn1ck** [comment]
I am using X with windows manager Fluxbox. Is there any other info I could provide?

**Comment by alexdima** [comment]
I think this is a dup of https://github.com/microsoft/vscode/issues/124895#issuecomment-970329733 . That also mentions Fluxbox and that problems first started with 1.56.

**Comment by iamn1ck** [comment]
> I think this is a dup of [#124895 (comment)](https://github.com/microsoft/vscode/issues/124895#issuecomment-970329733) . That also mentions Fluxbox and that problems first started with 1.56. Looks like the upstream issue is https://bugs.chromium.org/p/chromium/issues/detail?id=713746

Thank you Alex for finding this, I added the argument like was mentioned in the issue and it has fixed this problem.
