### ISSUE TITLE
Terminal hyperlink is not opened with control + click command

### ISSUE THREAD

**Issue by iamn1ck** [microsoft/vscode#144656]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0
- OS Version: Arch Linux x86_64 Kernel: 5.16.12-arch1-1

Steps to Reproduce:

1. Have an error in your terminal with a reference file / Have a hyperlink in the terminal
2. Control click on the hyperlink
3. Vscode does not open the file/hyperlink

This bug has been in vscode for over a year now and I am not sure how it has gone unnoticed. This feature was last working on version 1.55.2 and I have been using that version for the last year, however I need to update to a newer version of vscode.

Attached below is a video of the problem

https://user-images.githubusercontent.com/3345597/157208166-cb49a041-6231-486d-a2bd-aa1c36ac0bed.mp4

**Comment by heysujal** [comment]
Can I work on this issue ?
Can anybody how to go about fixing this issue?

**Comment by meganrogge** [comment]
Are you able to reproduce this issue in insider's?

**Comment by iamn1ck** [comment]
I am still experiencing this issue even with the Insiders edition. I have also opened another issue here https://github.com/microsoft/vscode/issues/144655#issuecomment-1062166997 and the bug occurred in the same update as this one, from version 1.55 - 1.56 and the other developer mentions it was during the electron 12 update. Could this also be the same problem?

**Comment by iamn1ck** [comment]
This issue was fixed by adding the arguments suggested here https://github.com/microsoft/vscode/issues/124895#issuecomment-970329733

Thanks
