### ISSUE TITLE
Occur "The window has crashed (reason: 'crashed', code: '-1073740791')" message after upgrade from 1.64.2 to 1.65.

### ISSUE THREAD

**Issue by supershowwei** [microsoft/vscode#144682]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.65
- OS Version: Windows Pro 21H2

Steps to Reproduce:

1. Click "Install Update".
2. Wait for the installation to finish.
3. Boom

![image](https://user-images.githubusercontent.com/4360325/157252500-0d63494a-04d6-4348-ad22-a7cdfb244a3b.png)

No problem after downgrade to 1.64.2.

**Comment by deepak1556** [comment]
Can you follow the steps in https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and attach the crash logs, thanks!

**Comment by supershowwei** [comment]
Problem disappear after reinstall 1.65
