### ISSUE TITLE
Can't Save File

### ISSUE THREAD

**Issue by IAmHopp** [microsoft/vscode#144614]
Issue Type: <b>Bug</b>

Open a file (in my case the hosts file in Windows)
Press Ctrl. + S or go to File > Save

Expected Result: File saved successfully. (Or at least an error asking to retry as administrator, since it's a system file)
Actual Result:

![image](https://user-images.githubusercontent.com/8302437/157092738-d7873a0b-bfc2-42db-a7ae-a14df4a586ad.png)

VS Code version: Code - Insiders 1.66.0-insider (e80a0ca648fe9bef07070e4f7fb04e67f2243252, 2022-03-07T05:16:48.804Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|21.94GB (4.47GB free)|
|Process Argv|--crash-reporter-id 1e3fa7b6-bc32-40ff-8f5b-cc46fa4e5dfc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vuerd-vscode|din|0.9.15
gitlens|eam|12.0.1
gitkraken-authentication|git|1.0.3
terraform|has|2.20.0
rest-client|hum|0.24.6
l13-diff|L13|1.0.3
vscode-docker|ms-|1.20.0
csharp|ms-|1.24.1
vscode-kubernetes-tools|ms-|1.3.6
vscode-postgresql|ms-|0.3.0
remote-containers|ms-|0.225.0
remote-ssh|ms-|0.77.2022030315
remote-ssh-edit|ms-|0.77.2022030315
powershell-preview|ms-|2022.2.2
vsliveshare|ms-|1.0.5418
vscode-sanddance|msr|3.3.0
fabric8-analytics|red|0.3.5
java|red|1.4.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.5.0
scala|sca|0.5.5
sonarlint-vscode|Son|3.3.3
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.0
vscode-java-test|vsc|0.34.1
vscode-maven|vsc|0.35.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30421357
vsclayoutctrt:30405800
dsvsc009:30440021
pythonvspyt640:30438691
vsbas813:30436447
vscscmwlcmc:30428972
azactmsal:30432848
vscgsvid2:30433758
dockersurvey3:30438168
pynewfile477:30443519

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by IAmHopp** [comment]
![image](https://user-images.githubusercontent.com/8302437/157123948-5d93368c-8615-4293-9510-446ddac0bbdc.png)

**Comment by yume-chan** [comment]
I also have this issue. Error when saving files owned by Administrator.

Bisect gives https://github.com/microsoft/vscode/compare/b5205cc8eb4fbaa726835538cd82372cc0222d43...6dca4c1a1f7bb3529074601eb32938526fa9ecc7

**Comment by redfave** [comment]
I got the same issue in Jupyter notebooks. Extension Bisect resulted that it's an issue in VS Code itself as the issue persists even when all extensions are disabled including the one for Jupyter.

Windows 11 x64
VS Code: 1.66.2

**Comment by bpasero** [comment]
Can you open a new issue and give as much details how to reproduce as possible?

**Comment by redfave** [comment]
> I can't reliably reproduce it,

The same goes for me. Discarding the changes made fixed the issue.

**Comment by ralbso** [comment]
This happens to me multiple times a day. While I haven't been able to pinpoint the origin of this behavior, I believe it might be related to certain git actions -- branch switching and pulling.

**Comment by Jaime02** [comment]
In my case it happens when I run black in the ipynb file. The format does not change but then I'm unable to save it.

**Comment by JeppeKlitgaard** [comment]
Mine was unrelated to git, but it seems like it might be related to the underlying .ipynb file changing?

**Comment by redfave** [comment]
It is definitely unrelated to git, as my Jupyter notebooks aren't saved in a git repo.
But I think it is related to fiddling around with the notebook cells. Before this error appears, I made some changes like deleting cells in the middle of the notebook and pasting the code to some other place (but not the start or end of the notebook).

**Comment by JeppeKlitgaard** [comment]
It just happened to me again – I think I might have run `black` while a cell was executing?

![image](https://user-images.githubusercontent.com/1814611/164746069-5fe9ae9c-afd0-411c-a7cb-a009ef5ab25b.png)

This is the error in the dev console.

It might be unrelated, but I am also getting a lot of these: 
![image](https://user-images.githubusercontent.com/1814611/164746361-a032c8db-c9e4-4c14-8ac0-aaee806a5894.png)


Full logs: 
[vscode-app-1650641355098.log](https://github.com/microsoft/vscode/files/8542179/vscode-app-1650641355098.log)

**Comment by bpasero** [comment]
Pushed a fix for https://github.com/microsoft/vscode/issues/147929 which was actually a real bug in the code that handles errors on save, however you would still see a save failure I suppose, so I suggest that people report back on Monday with insiders what happens.

**Comment by shababo** [comment]
I just experienced this with VSCode remote using an ipynb - it seems like it was caused by having two tabs of the same ipynb open at the same time. Once I closed one of them, it resolved.
