### ISSUE TITLE
Support terminalShellType context key on non-Windows

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#144619]
This will allow separating commands in command detection by shell (esp. important for pwsh).

**Comment by Tyriar** [comment]
To verify on mac or linux, bind a keybinding to use the terminalShellType context key (eg. bash or zsh) and ensure it works as expected depending on the active terminal session.

**Comment by connor4312** [comment]
A couple cases I can hit on OSX:

1. Create a zsh terminal
2. Observe terminalShellType == zsh ✅ 
3. Reload the window
4. Observe that the terminal is restored, but terminalShellType is not set 🐛 

---

1. Create a zsh terminal
2. Observe terminalShellType == zsh ✅ 
3. Create a bash terminal in a new tab
2. Observe terminalShellType == bash ✅ 
3. Switch back to the zsh terminal
2. Observe terminalShellType == bash 🐛
