### ISSUE TITLE
Not supporting hover variable with hyphen 

### ISSUE THREAD

**Issue by teju242** [microsoft/vscode#144626]
I extended debug extension protocol (For Cobol) and I have variables name with hyphen in it e.g: Emp-salary.
I am trying to hover this kind of variable but it is not considering this as complete one variable name. It is splitting variable as emp as one and salary as another. What I need to implement so it will consider hyphen separated variable as one variable?

**Comment by weinand** [comment]
Please see the section "New Debug Hover API" in https://code.visualstudio.com/updates/v1_43#_extension-authoring
