### ISSUE TITLE
Vscode web editor: Draft lost due to lost of connection to the database

### ISSUE THREAD

**Issue by mangost** [microsoft/vscode#144650]
Due to a failure of the VPN, the connection to the database was lost. The editor shows a error indicating the lost of connection. Then, I joined another working VPN and the refreshed the webpage.  All edit was lost. 

I have once thought that the editor cached edit offline and internet connection instability should be appropriately managed. But it seems it is not. If this is the case, I suggest that the develop team may take this into consideration. 

Despite this, I still prefer vscode and the web version. Sincere thanks to the develop team and all contributors. 

--------------------------

Version: 1.65.0
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36 Edg/99.0.1150.30
Embedder: github.dev

**Comment by joyceerhl** [comment]
@sandy081 Should IndexedDB connections be impacted by an unstable network connection?

**Comment by sandy081** [comment]
I doubt because the indexedDB is on the client side.

**Comment by joyceerhl** [comment]
> the editor cached edit offline

This is correct--github.dev stores your uncommitted changes client-side in browser storage.

I tried the following and was unable to reproduce data loss:
1. With network connection, make changes to a file
2. Disable network connection
3. Make some more changes to same file
4. Reload page
5. Restore network connection
6. Changes are still there

@mangost Do you have any reproducible steps for this scenario?
