### ISSUE TITLE
Update Extension - Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by jameslj** [Microsoft/vscode#14465]
- VSCode Version: 1.6
- OS Version: Win 7

Steps to Reproduce:

1. Extension indicates to update
2. Click "Update"
3. Error message displays, "unable to verify the first certificate".

Machine is domain joined and is routed through an authenticated corporate proxy (McAfee Web Gateway).

Set the preferences as recommended, see below (removed private information)

// Place your settings in this file to overwrite the default settings
{
    "http.proxy": "http://{userid}:{password}@{host}:port",
    "http.proxyStrictSSL": false
}

Error from the developer console:

/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:93 unable to verify the first certificate: Error: unable to verify the first certificate,    at Error (native),    at TLSSocket.<anonymous> (_tls_wrap.js:1065:38),    at emitNone (events.js:80:13),    at TLSSocket.emit (events.js:179:7),    at TLSSocket._finishInit (_tls_wrap.js:593:8),    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:425:38)

**Comment by jameslj** [comment]
Works in 1.6.1

**Comment by bierenjiadehaizi** [comment]
what mean ?
