### ISSUE TITLE
Source Control Pane broken after Git for windows update to 2.35.1

### ISSUE THREAD

**Issue by kaiseruncc** [microsoft/vscode#144627]
I recently updated Git on my Windows 10 instance to 2.35.1.  Since then the ability to use the "Source Control" section within VSCode has been broken.  IT appears to be an issue with rendering, since i can still perform git commands at the command line of the repo but not through the Source Control section.  The only thing showing on Source Control now is the section to commit changes.  The sections for managing branches and remotes are completely gone.

**Comment by lszomoru** [comment]
@kaiseruncc, I see that you have close the issue? Were you able to resolve the problem?

**Comment by kaiseruncc** [comment]
Yes, best I can tell, the parts of the source control pane I used to switch
branches, view commits, file history, and view remotes came from an
extension that was completely missing after VSCode updated.  GIT could
still see all the remotes and branches at command line level, but all that
functionality I was used to in the Source Control pane was gone.  Until I
went after more extensions around GIT in the marketplace, got those
installed, and all those abilities came back.  I thought that was there out
of the box, but I guess I was wrong and needed to go after extensions again.

**Comment by lszomoru** [comment]
hm, VS Code contains a built-in extension called `vscode.git` that provides Git functionality. There should not be a need to download any extension from the marketplace. Are you able to reproduce the problem if you start `code` with the `--disable-extensions` flag? Also, what version of VS Code are you running at the moment? Thank you!
