### ISSUE TITLE
codelens bounce when input with setting window.zoomLevel: 1

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#144612]
OS: MacOS 12.2.2
VSCode: 1.65.0-insider
rust-analyzer: pre-release v0.3.952
rustc: 1.59.0

code in video:

```rust
/*
结构体
 */

#[allow(unused)]

fn main() {
    // ------------------------ 定义结构体 -----------------------------
    // 注意是使用逗号分隔字段，习惯了在 ts 里面用分号分隔接口字段，切换到 rust 到容易敲错
    // aaaaaaaaaaaaaaa
    struct Layer {
        name: String,
        left: i32,
        top: i32,
        width: i32,
        height: i32,
    }
}
```

https://user-images.githubusercontent.com/41773861/155765638-edc35241-521d-4d65-871a-9bca04933559.mov

This is releated with following setting. If I remove this setting, the codelens won't bounce.

```
"window.zoomLevel": 1,
```

gitlen also has this issue:

https://user-images.githubusercontent.com/41773861/157090278-3e2da25d-2fb5-42f9-b137-92b33f088a6f.mov

ref: https://github.com/rust-analyzer/rust-analyzer/issues/11553

**Comment by alexdima** [comment]
Simplified repro steps:
```
"window.zoomLevel": 1,
"typescript.referencesCodeLens.enabled": true
```


https://user-images.githubusercontent.com/5047891/157238057-bd6e6ee8-ade2-485b-94cc-7dddf816ef69.mp4

**Comment by alexdima** [comment]
@jrieken Running with the following patch:
```diff
diff --git a/src/vs/editor/browser/viewParts/contentWidgets/contentWidgets.ts b/src/vs/editor/browser/viewParts/contentWidgets/contentWidgets.ts
index 3ac19795247..6bbf3e016ab 100644
--- a/src/vs/editor/browser/viewParts/contentWidgets/contentWidgets.ts
+++ b/src/vs/editor/browser/viewParts/contentWidgets/contentWidgets.ts
@@ -471,6 +471,7 @@ class Widget {
 				const domNode = this.domNode.domNode;
 				this._cachedDomNodeOffsetWidth = domNode.offsetWidth;
 				this._cachedDomNodeOffsetHeight = domNode.offsetHeight;
+				console.log(`reading offsetHeight from ${this.id}: ${domNode.offsetHeight}`);
 			}
 		}
 ```

I see that the `offsetHeight` of the content widget alternates between 20 and 21 pixels. This is the cause of the jumpiness. Is there something special done while typing to the code lens content widget which would cause it to change its size?
https://user-images.githubusercontent.com/5047891/157239151-098fe195-3dd7-4a21-9cf0-3da042776dbd.mp4

**Comment by jrieken** [comment]
@alexdima we re-layout the view zones of code lenses as type. Maybe that's how this happens?

**Comment by alexdima** [comment]
> we re-layout the view zones of code lenses as you type

The relayout causes the editor to drop its height cache and read again the `domNode.offsetHeight`. So not calling that will stop the issue from happening. But I was wondering why would the `offsetHeight` of the content widget change from one reading to the next, so I was thinking maybe the contents inside are changing... If the contents inside are not changing, then it is possible that we are observing a rounding error, like when the content widget is at top 165px, its height is 20px, when it is at top 166px, its height is 21px and equilibrium is never reached.
