### ISSUE TITLE
Outputs of df.dtypes does not format well

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/vscode#144631]
## Environment data

-   VS Code version: 1.65
-   Jupyter Extension version (available under the Extensions sidebar): v2022.3.1000652335
-   Python Extension version (available under the Extensions sidebar): v2022.2.1924087327
-   OS (Windows | Mac | Linux distro) and version: win10
-   Python and/or Anaconda version: 3.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

![Capture2](https://user-images.githubusercontent.com/21306413/156996218-9ec7c75a-e10c-4ca6-a782-4adadf40c96d.PNG)

![Capture3](https://user-images.githubusercontent.com/21306413/156996227-8acfa97a-ecd8-413a-a85d-bfa886a59b64.PNG)

## Actual behaviour

![Capture1](https://user-images.githubusercontent.com/21306413/156996242-e9dec290-a99e-4728-a27d-eb2e57f8fc0e.PNG)

I don't know how to configure it, I can not find the relative configuration on the Internet. I tried to switch the color theme and install the older version of Jupyter Extension but still did not work.

**Comment by greazer** [comment]
Output fonts are vscode core.
