### ISSUE TITLE
if-statement

### ISSUE THREAD

**Issue by ZYXGeo-Rge** [microsoft/vscode#144659]
Issue Type: <b>Bug</b>

Seeking help: I've tried to run the looking-fine code many times but still showing warning messages...

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by ZYXGeo-Rge** [comment]
code:
x = int(input("enter a number"))
  if x % 2 == 0:
  print('even number')
     else:
  print('odd number')

error:
 if x % 2 == 0:
IndentationError: unexpected indent

**Comment by quanzhuo** [comment]
I guess your are coding in python. Python require different indent for code block. obviously your code has no indentation
