### ISSUE TITLE
VScode colours - too vibrant

### ISSUE THREAD

**Issue by stilyansky** [microsoft/vscode#144678]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Update VS Code to v.1.65.0

Since the last update all colours went waaay too vibrant - I am using same theme, same settings - everything. I tried to run it without extensions and it still looks too vibrant.

Luckily i had an a screenshot of the old view, so here is an image of before and after the update:

 
![vscode - too vibrant](https://user-images.githubusercontent.com/31994426/157250396-0e338483-cc91-45bc-b61b-f43a8dc19de8.png)

**Comment by aeschli** [comment]
Which theme is this? Can it be that the theme might have updated its colors?

There's always the chance that this is the result of an update of Electron/Chromium. @deepak1556 Do you know more?

**Comment by deepak1556** [comment]
There was no runtime update with `1.65` release, so I highly doubt its a regression from the runtime.

Just in case, can you check if the behavior exists in our [exploration build](https://az764295.vo.msecnd.net/exploration/17ae8c014b3a1b6fe4556bcedb36ec76a58a2a63/VSCode-darwin-universal.zip) that ships with a newer runtime, thanks!

**Comment by stilyansky** [comment]
ok i just updated to the new version (see spec bellow) and the issue is fixed :O 

Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z (16 hrs ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0

btw it can not be from the theme, because the terminal colours were also affected and i have set custom colours there myself.

In any case, now it is back to normal so i am a happy camper and will close the issue :)
