### ISSUE TITLE
Java Web project compiles all the time when save

### ISSUE THREAD

**Issue by Matheeus00** [microsoft/vscode#144633]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65
- OS Version: Windows 10 64bits

Steps to Reproduce:

1. Open a Java Web project with Gradle;
2. Every time a file has saved by pressing CTRL + S, the whole project compiles again, it takes a lot of time, preventing to make changes in the code.

**Comment by luciano-zimermann** [comment]
This is happening for me as well, its a big project
