### ISSUE TITLE
Code region is always inactive

### ISSUE THREAD

**Issue by netms7** [microsoft/vscode#144694]
Does this issue occur when all extensions are disabled?: Yes
I use Visual Studio Code on Windows. On Windows all work without issues.
I also use Arch Linux and there I use VS Code installed from AUR mirrors.
No styles, themes, extensions are installed. Just fresh installation.
On linux I have an issue. The code region is always seems inactive, like an inactive C define region. It has low brightness level. It appears in any file I open, even in text files.
I attach a screenshot:
![image](https://user-images.githubusercontent.com/94935557/157282095-bf704f74-cf57-458a-81a4-2ba9b5853439.png)
I also tried Code OSS. The same problem.
Just to compare, on Windows it looks like:
![image](https://user-images.githubusercontent.com/94935557/157282506-cbb944d2-be03-481b-b07d-bec9a7553393.png)

- VS Code Version: 1.65.0-1
- OS Version: Arch Linux (kernel 5.16.12)

Steps to Reproduce:

1. Install "code" or "visual-studio-code-bin" package from AUR
2. Run Code OSS

**Comment by alexdima** [comment]
@netms7 Are things better when launching `code --disable-gpu`?

**Comment by netms7** [comment]
> @netms7 Are things better when launching `code --disable-gpu`? I noticed that also the "Untitled" in the tab looks a bit dimmer. Could you please share a screenshot of the entire window?

Unfortunately, no difference with --disable-gpu flag. I also tried --disable-extensions flag, the same.
The screenshot of the entire window:
![image](https://user-images.githubusercontent.com/94935557/157318785-84109325-be26-4513-a24d-22649e561120.png)

**Comment by alexdima** [comment]
@netms7 On linux, the editor uses by default the following font family: `'Droid Sans Mono', 'monospace', monospace`. Could you please try changing the `"editor.fontFamily"` setting to `Arial` or some other font installed on your system? (It is possible that the default monospace font looks washed out on this system).

**Comment by netms7** [comment]
> @netms7 On linux, the editor uses by default the following font family: `'Droid Sans Mono', 'monospace', monospace`. Could you please try changing the `"editor.fontFamily"` setting to `Arial` or some other font installed on your system? (It is possible that the default monospace font looks washed out on this system).

![image](https://user-images.githubusercontent.com/94935557/157324645-851de956-820e-4d89-b074-dfb0734b6f60.png)
It worked. I also fixed the issue with the default font by installing ttf-ms-fonts package in my system.
Now all works great! Thank you!
