### ISSUE TITLE
Snap of editor groups doesn't work as expected when activating another editor group by clicking on an inactive tab

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14463]
Testing #14016

- VSCode Version: Code - Insiders 1.7.0-insider (5bafcdb3d67b29b1f4667a3f497ac05a41dde667, 2016-10-25T06:19:07.301Z)
- OS Version: Linux x64 4.4.0-45-generic, Ubuntu 16.04
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.1.0|
|terminal-tabs|Tyriar|0.0.6|
|theme-glacier|Tyriar|0.0.10|
|vscode-icontheme-nomo-dark|be5invis|1.1.5|
|vscode-svgviewer|cssho|1.2.0|
|vscode-eslint|dbaeumer|1.0.8|
|git-project-manager|felipecaputo|0.1.15|
|Theme-Wombat|gerane|0.0.2|
|csharp|ms-vscode|1.4.1|
|typescript-javascript-grammar|ms-vscode|0.0.6|
|nova|rebornix|0.0.5|
|sass-indented|robinbentley|1.1.0|
|annotator|ryu1kn|0.10.1|

This happens on both vertical and horizontal editor group layouts, it's just easier to reproduce when horizontal is used.

Steps to Reproduce:

1. Turn on horizontal editor group layout
2. Open files `a`, `b` in editor group 1
3. Open files `c`, `d` in editor group 2
4. Minimize the non-active editor group so that snapping is enabled
5. Click on the inactive tab in the other editor group, if snapping works as expected then try a few more times (it felt > 50% repro rate for me)

Here's what the bugged state looks like:

![image](https://cloud.githubusercontent.com/assets/2193314/19696936/2e0e0962-9a9e-11e6-807a-b15c97af14a2.png)

Note that snapping is still enabled and will snap correctly if you switch the editor groups back by click on the active tab in the inactive editor group twice.

**Comment by bpasero** [comment]
@Tyriar I believe you managed to get the top editor group into a state where it is not snapped to minimize. I pushed some changes during the milestone to prevent an editor from snapping to minimize unless you actually move a sash to make the editor small enough or unless you execute the minimize editor command.

The reason I did this is because when you are in horizontal layout and you move up the panel until the editors are minimial size you do not want any editor to stay in minimized position. You want them to restore normally.

Please reopen if you disagree this is what was happening.

**Comment by Tyriar** [comment]
Not sure what you mean by *"you do not want any editor to stay in minimized position"*, basically this issue is about the snapping behaving not the same when you activate the other editor by clicking a non-active tab. Shouldn't it behave the same regardless of whether the tab was active or not?

**Comment by bpasero** [comment]
@Tyriar thing is, I cannot reproduce no matter how hard I try:

![editors](https://cloud.githubusercontent.com/assets/900690/19755471/7643c540-9c16-11e6-9354-cb61b021fd5f.gif)

What I was trying to say is that it is possible to have an editor group in minimal size without it being in the snapped position. I show you why that is important:

![editors](https://cloud.githubusercontent.com/assets/900690/19755527/e445ebcc-9c16-11e6-8cbc-33100ccdaf2b.gif)

**Comment by Tyriar** [comment]
While it was very consistent before, I'm having difficulty reproducing now as well. Let's close it since it wasn't that big of an issue anyway.
