### ISSUE TITLE
using ${command} variable in launch config passes the launch config as argument

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#144648]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62
- OS Version: Windows 8.1

Steps to Reproduce:

1. Create a launch config that uses a `${command}` variable. I used a command from the extension [Command Variable](https://marketplace.visualstudio.com/items?itemName=rioj7.command-variable)
1. Executing the launch config calls the command with an argument. This argument is the complete launch config object (name, type, request, ......)

Some commands can be used in keybindings and `${input}` variables with arguments. And have defaults if no arguments are supplied.

What is the reason that `${command}` variable has the complete launch config object as argument?

How to check if the argument is a launch config or an object passed in a keybinding or from `${input}` variable?

As a workaround I check if `request` property is present.

This is not documented in the [Command variables](https://code.visualstudio.com/docs/editor/variables-reference#_command-variables) section of the Variables doc page.

**Comment by weinand** [comment]
Passing the complete launch config object to command variables is an undocumented feature.
Command implementations relying on this must make sure that they can deal with a missing launch config.
