### ISSUE TITLE
Error Icon proposes confusion

### ISSUE THREAD

**Issue by JeffBusterCase** [microsoft/vscode#144634]
**Is your feature request related to a problem? Please describe.**
Whenever I try to close a error dialog, I miss the close button by the error Icon.

**Describe the solution or feature you'd like**
Select a different Icon to represent an error or change the error dialog div width so it's easy to close the error popup.

**Describe alternatives you've considered**
none

**Additional context**
This shows when you click on View Problem
And Error Icon is much more close to the query, so we Look at him... and want to close it, so we click on it. But it dosen't work.. because the close button is the X without the circle around it. Yet, they seem too much alike, and permits confusion.
![image](https://user-images.githubusercontent.com/12688410/156879014-0b5d9a9b-f036-4eab-aba8-1a570a8e1444.png)

A simple search for close icon on google displays better this problem:
![image](https://user-images.githubusercontent.com/12688410/156879175-b926e77d-e1df-4e8f-aec5-17429f51ba1f.png)

What I suggest is to use ! instead:
![image](https://user-images.githubusercontent.com/12688410/156879430-02726f73-6d03-4a37-97bf-fefa70a6ac03.png)

**Comment by misolori** [comment]
Appreciate the feedback, we do already use the triangle and circle with the exclamation for other statuses:

<img width="318" alt="CleanShot 2022-03-08 at 07 35 20@2x" src="https://user-images.githubusercontent.com/35271042/157271062-11e84288-5669-465f-911c-26254d35a8ac.png">

We hope that the color + enclosure of the shape will help make it distinct enough from a regular close that has the default color but know that it doesn't work for everyone. You can also look into [product icon themes](https://marketplace.visualstudio.com/search?term=tag%3Aproduct-icon-theme&target=VSCode&category=All%20categories&sortBy=Relevance) to see if there are other "solid" icon themes that might help you out better.
