### ISSUE TITLE
using ssh vscode keeps stucking at Initializing JS/TS language features and hangs/crashes vps 

### ISSUE THREAD

**Issue by aanishacharyaa** [microsoft/vscode#144603]
Does this issue occur when all extensions are disabled?: Yes/No 
Not sure cause without remote ssh extension can't connect to vps

- VS Code Version: 1.65.0
- OS Version: linux x64

![5](https://user-images.githubusercontent.com/60659030/157072963-32ef556d-41c3-4932-8902-059fc92aa685.png)

Steps to Reproduce:
1. connect vscode  to vps using official remote ssh extension
2. open any nodejs/ javascript project file

![1](https://user-images.githubusercontent.com/60659030/157073039-caaf447a-be8b-4ef3-884b-731985810039.png)
![2](https://user-images.githubusercontent.com/60659030/157073048-a2e1fe5b-103f-4e6f-83a9-f0a9777399bf.png)
![3](https://user-images.githubusercontent.com/60659030/157073076-fcdfc049-5213-49b0-a6db-b282e3536f0e.png)
![4](https://user-images.githubusercontent.com/60659030/157073089-e532f028-aa0c-49d0-9473-0d44e4857768.png)

vps is running ubuntu 20.04 

interestingly it works flawlessly on more powerful 4 core vps but dosen't work on 1core vps. It is causing vps to disconnect and become unresponsive

**Comment by mjbvz** [comment]
You're on an older VS Code version 

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled) (besides the ones you need to use like ssh)?

**Comment by aanishacharyaa** [comment]
> You're on an older VS Code version 
> 
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled) (besides extensions like `remote ssh` that you need for this scenario)? 

There's typo I'm on 1.65.0 as shown in screen shot attached

**Comment by mjbvz** [comment]
Please also test with insiders and extensions disabled to make sure one of them is not causing this
