### ISSUE TITLE
The Cell output font and size looks deviant

### ISSUE THREAD

**Issue by SnakeHit** [microsoft/vscode#144630]
## Environment data

-   VS Code version: 1.65.0 (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2022.3.1000652335
-   Python Extension version (available under the Extensions sidebar): v2022.2.1924087327
-   OS (Windows | Mac | Linux distro) and version: Mac Darwin arm64 21.1.0
-   Python and/or Anaconda version: 3.8.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | Local

## Maybe a bug?
when I run the python script, the cell output some outcomes. But the outcomes font looks abnormal
My editor font is: 'Fira Code', 'MesloLGS NF', a ligature nerd font
But my output font looks like another font. 
BUT!!! The exception of the python script is the ligature nerd font...
![Xnip2022-03-08_03-05-07](https://user-images.githubusercontent.com/45898625/157100870-089be844-099d-412b-b6c4-1bf8a00d5790.jpg)

**Comment by greazer** [comment]
Believe this is already fixed in vscode core.

**Comment by aidannicks** [comment]
I'm having similar issues with the cell output.

Both the font type and the spacing has changed in the recent update.
Previous version output:

![image](https://user-images.githubusercontent.com/79814394/157138085-3dcc2be3-3836-463c-b4d3-1faee971cb49.png)

current version of output:

![image](https://user-images.githubusercontent.com/79814394/157138179-163e0881-274c-4a11-934f-1ef4f340ed45.png)

In the current version the space between the column names, the non-null, count, and dtype is inconsistent. A similar result occurs when displaying the output of a value_counts() function. 

Environment data
Version: 1.65.0 
OS: Windows_NT x64 10.0.18363
Jupyter Extension version (available under the Extensions sidebar): v2022.3.1000681942
Python Extension version (available under the Extensions sidebar): v2022.3.1000681942
Python and/or Anaconda version: 3.7.6
Type of virtual environment used (conda)
Jupyter server running: Remote

**Comment by erwinwanders** [comment]
* Version: 1.65.0
* OS: MACos Darwin x64 21.3.0
* Jupyter Extension version (available under the Extensions sidebar): v2022.2.1030672458
* Python Extension version (available under the Extensions sidebar): v2022.2.1924087327
* Python and/or Anaconda version: 3.9.5
* Type of virtual environment used: venv
* Jupyter server running: local

experiencing same bug. The march update sets the output of the interactive window to a non-monospaced font (prob. Segoe UI)

![image](https://user-images.githubusercontent.com/31048285/157225570-df8a78e5-2849-4f93-a540-77346e29f726.png)

I've tried to set all fonts to a monospaced font without any luck.

**Comment by rebornix** [comment]
This would be fixed with the coming recovery build.
