### ISSUE TITLE
Integrated terminal is not auto focused when debug session starts

### ISSUE THREAD

**Issue by BIKA-C** [microsoft/vscode#144665]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
```
Version: 1.65.0
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:13:50.741Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.3.0
```
- OS Version: osx 12.2.1 (21D62)

Steps to Reproduce:
1. enter the command to start debug

The cursor is not focused to the terminal. I tried this in C and java. I remember it used to do that.

**Comment by weinand** [comment]
what exactly do you mean by "enter the command to start debug"?
