### ISSUE TITLE
Markdown user snippet not working in math context or brackets

### ISSUE THREAD

**Issue by yangcyself** [microsoft/vscode#144768]
Issue Type: <b>Bug</b>

For the markdown file like the following, with "mu" defined as a prefix of "\mu" in user snippets.
```markdown
mu

$mu$

$(mu)$

$$
mu
$$

mu
``` 
The user snippet
```json
{
	"mu2":{"prefix": "mu",
		"body": [
			"\\mu ",
		],
		"description": "output mu"}
}
```
The suggestion is disabled for the "mu" in `$(mu)$` or `$$ mu $$`. When using Ctrl+Space behind "mu", it shows "no suggestions". However, the suggestions works good for other "mu"s. And I can use Tab completion in these cases.

I noticed this situation from about Feb 2021. And I have the same issue on other platforms e.g. windows.

VS Code version: Code 1.65.1 (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:09:03.269Z)
OS version: Linux x64 5.13.0-30-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1100)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 1, 1|
|Memory (System)|15.46GB (2.22GB free)|
|Process Argv|--no-sandbox . --crash-reporter-id 284dee97-23a9-4159-8c8a-a2f0e9b68a20|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
c-cpp-compile-run|dan|1.0.15
gitlens|eam|12.0.2
matlab|Gim|2.3.1
gitkraken-authentication|git|1.0.3
python|ms-|2022.2.1924087327
jupyter|ms-|2022.2.1030672458
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.9.2
cpptools|ms-|1.9.2
autodocstring|njp|0.6.1
vscode-yaml|red|1.5.1
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.17
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30448491
dsvsc009:30440023
pythonvspyt640:30450168
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvidc:30447482
helix:30440343
vscaat:30438848
pynewfile477:30450038

```

</details>

**Comment by yangcyself** [comment]
Here are two screenshots to illustrate the issue.
![image](https://user-images.githubusercontent.com/31209418/157485002-07c3ca19-df11-4961-889a-56b23f7aaf50.png)
![image](https://user-images.githubusercontent.com/31209418/157484931-db0db483-f993-4247-b980-dec5ef21550a.png)

**Comment by Lemmingh** [comment]
Your problem is a complex topic involving how:

* [TextMate-based tokenization](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide) works.

* VS Code understands [embedded languages](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages).

* Snippets and languages are [connected](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-scope).

I hope that the [Scope Inspector](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector) and issue #142022 can help you understand it.

Given the current design (VS Code 1.65), your experience is basically the expected behavior.

**Comment by yangcyself** [comment]
I see, now I changed the user snippets instead of markdown snippets and it works, thank you very much.
