### ISSUE TITLE
Failed to open folder because it contains (Actually NO) system files

### ISSUE THREAD

**Issue by GusarevKirill** [microsoft/vscode#144753]
Hello. I'm trying to open my code folder with vscode.dev, but it tells me: "Failed to open folder because it contains system files".
But there is no system files in this folder (I make visible hidden system files, but didn't see any changes - there is no hidden files in explorer).

Version: 1.65.1
Commit: 8908a9ca0f221f36507231afb39d2d8d1e182702
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
Embedder: vscode.dev

**Comment by GusarevKirill** [comment]
Hello. I'm trying to open my code folder (named "1" ("ZKI/1/") (I have attached this folder to this comment)) with vscode.dev, but it tells me: "Failed to open folder because it contains system files".
But there is no system files in this folder (I make visible hidden system files, but didn't see any changes - there is no hidden files in explorer).

Screenshot of error: [](https://imgur.com/a/0GhzpYD
[ZKI.zip](https://github.com/microsoft/vscode/files/8214997/ZKI.zip)
)

**Comment by yume-chan** [comment]
It's one of stupid restrictions of File System Access API, your folder may not "contain" system files, but it may be in a "system file folder". The full block list in Chrome is here:

https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/file_system_access/chrome_file_system_access_permission_context.cc;l=172-235;drc=359c4471ef9ffdf94d1080815d51f28ce0302b94;bpv=0;bpt=1
