### ISSUE TITLE
dependsOn executes wrong tasks in multi-root workspaces

### ISSUE THREAD

**Issue by dedChar** [microsoft/vscode#144761]
Issue Type: <b>Bug</b>

Running tasks with dependencies in a multi-root workspace executes the wrong dependency tasks, if there are multiple tasks defined under the same label but in different root folders. VSCode will just pick the first occurance in the order of the root folders defined in the workspace settings.

To reproduce the issue:

1. Setup a simple multi-root workspace, e.g.
```json
{
	"folders": [
		{
			"path": "root1"
		},
		{
			"path": "root2"
		},
		{
			"path": "root3"
		}
	],
	"settings": {}
}
```
2. In each root folder, add a tasks.json with two tasks. One task depends on the other. Example tasks of `root1`:
```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "dependency",
            "type": "shell",
            "command": "echo 'This is the dependency task of root1'"
        },
        {
            "label": "main",
            "type": "shell",
            "dependsOn": ["dependency"],
            "command": "echo 'And this is the main task of root1'"
        }
    ]
}
```

`root2` and `root3` have the same tasks configured except that they echo their respective folder name instead.

3. Run task `main` of either `root2` or `root3`.

### Expected output for `main` of `root2`

```
> Executing task in folder root2: echo 'This is the dependency task of root2' <

This is the dependency task of root2

Terminal will be reused by tasks, press any key to close it.

> Executing task in folder root2: echo 'And this is the main task of root2' <

And this is the main task of root2

Terminal will be reused by tasks, press any key to close it.
```

### Actual output on 1.65.1
```
> Executing task in folder root1: echo 'This is the dependency task of root1' <

This is the dependency task of root1

Terminal will be reused by tasks, press any key to close it.

> Executing task in folder root2: echo 'And this is the main task of root2' <

And this is the main task of root2

Terminal will be reused by tasks, press any key to close it.
```

VS Code version: Code 1.65.1 (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:06:27.846Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.94GB free)|
|Process Argv|--crash-reporter-id d9b02cb9-bd4f-4c77-be31-8b430da86809|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrc:30448490
dsvsc009:30440023
pythonvspyt640:30450168
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvidc:30447482
helix:30440343
pynewfile477:30450038

```

</details>

**Comment by StanVC** [comment]
Experiencing same issue on:
VS Code version: 1.65.1
OS version: macOS 12.2.1 BuildVersion:21D62

**Comment by alexr00** [comment]
To verify:
1. Open or create a multi root workspace with 2 roots, FolderOne and FolderTwo (or names of your choice).
2. In each of your roots add a .vscode folder.
3. In each of your .vscode folders add a tasks.json file with the following contents:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "PrimaryTask",
            "type": "shell",
            "dependsOrder": "sequence",
            "dependsOn": [
                "Task2" 
            ],
            "command": "echo PrimaryTask ${workspaceFolder}" 
        },
        {
            "label": "DependsTask",
            "type": "shell",
            "command": "echo DependsTask ${workspaceFolder}" 
        }
    ]
}
```
4. Run "PrimaryTask" in FolderOne (command "Tasks: Run Task" and choose the task with the label "PrimaryTask" that says "FolderOne" next to it). Verify that both PrimaryTask and DependsTask echo FolderOne's path.
5. Run "PrimaryTask" in Folder Two (command "Tasks: Run Task" and choose the task with the label "PrimaryTask" that says "FolderTwo" next to it). Verify that both PrimaryTask and DependsTask echo FolderTwo's path.
