### ISSUE TITLE
Column Selection Mode menu item needs a check mark for status indicator

### ISSUE THREAD

**Issue by oscarrutt** [microsoft/vscode#144724]
Issue Type: <b>Bug</b>

Selecting Edit -> Column Select Mode enters Column Selection Mode in an editor. Selecting it again toggles off Column Select Mode.

The standard (macOS) method of indicating a status when it is selected by a menu item is to place a check mark next to the item. VSC does not. VSC instead places an indicator in the status bar. Here, it is (1) not expected, (2) hard to notice, (3) at odds with the menu item when the mode is selected, (4) disappears when the mode is toggled off, and (5) not visible at all when the status bar is hidden.

I am filing this as a bug rather than a feature request because it is violates normal OS operation.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 15.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|4, 4, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
ada|Ada|23.0.1
Bookmarks|ale|13.2.2
pascal|ale|9.4.0
pascal-formatter|ale|2.6.0
project-manager|ale|12.4.0
preview-tiff|ana|1.0.1
octave-hacking|apj|0.2.12
vscode-svgviewer|css|2.0.0
vcard|cst|1.0.1
vscode-mac-color-picker|dae|1.0.2
textpad-icon-theme|dam|1.19.21
vscode-markdownlint|Dav|0.46.0
ada-snippets|Ent|0.3.0
gc-excelviewer|Gra|4.0.50
vscode-back-forward-button|gri|0.1.6
vscode-lyx|gyt|0.0.4
applescript|idl|0.21.1
latex-workshop|Jam|8.23.0
svn-scm|joh|2.15.2
language-julia|jul|1.5.10
keen-neutral-icon-theme|kee|1.0.8
octave|lea|0.1.1
eps-preview|mkv|0.3.0
python|ms-|2021.12.1559732655
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
postscript|mxs|1.0.1
vscode-json-editor|nic|0.3.0
vsc-octave-debugger|pau|0.4.24
bib|phr|0.3.0
ipf|qms|1.0.1
vscode-data-preview|Ran|2.3.0
markdown-preview-enhanced|shd|0.6.1
html-preview-vscode|tht|0.2.5
octave|toa|0.0.3
pdf|tom|1.2.0
debug|web|0.25.1
txt-syntax|xsh|0.2.0
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30448491
dsvsc008:30440022
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvid2:30447481
helix:30440343
vscaac:30438847

```

</details>

**Comment by alexdima** [comment]
@oscarrutt Please update to latest VS Code, this has been changed in the meantime.

<img width="459" alt="image" src="https://user-images.githubusercontent.com/5047891/157411483-cf742f97-a254-4a35-b69a-edbbf75c0dd7.png">
