### ISSUE TITLE
Icon display error

### ISSUE THREAD

**Issue by czqn8** [microsoft/vscode#144739]
After creating a new file with file.0 and selecting vscode as the open method
 affects other folders.
For example, after opening file.0, the icon of other folder xxx.0 is changed, not the folder icon, and this 0 is not the file extension.

![image1](https://thumbnail1.baidupcs.com/thumbnail/486dd23e4h93df2610f38a8467b13a77?fid=4011644425-250528-759929328534333&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-AB1nHC5PU9LaB7rdVVVoeXYeBv4%3d&expires=8h&chkbd=0&chkv=0&dp-logid=418199027751272428&dp-callid=0&time=1646816400&size=c1680_u1050&quality=90&vuk=4011644425&ft=image&autopolicy=1)

![image1](https://thumbnail1.baidupcs.com/thumbnail/87d84fa1cq56685349614a966dce3970?fid=4011644425-250528-1124876156129764&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-QE0LNZrv6iw8acvIrVKX8O9KWpg%3d&expires=8h&chkbd=0&chkv=0&dp-logid=418218861910930955&dp-callid=0&time=1646816400&size=c1680_u1050&quality=90&vuk=4011644425&ft=image&autopolicy=1)

**Comment by czqn8** [comment]
![image3](https://thumbnail1.baidupcs.com/thumbnail/5b46f6496g13a5f1d6bf7252c49a5b66?fid=4011644425-250528-657281907359012&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-i8vPhrFlx39%2bqAfhFfqheJk1G78%3d&expires=8h&chkbd=0&chkv=0&dp-logid=418308307051458096&dp-callid=0&time=1646816400&size=c1680_u1050&quality=90&vuk=4011644425&ft=image&autopolicy=1)

**Comment by joaomoreno** [comment]
Similar? https://github.com/microsoft/vscode/issues/107306

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/107306
