### ISSUE TITLE
Output cells in Jupyer notebook are rendering with a weird font family

### ISSUE THREAD

**Issue by kawaremu** [microsoft/vscode#144773]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.65.1 (user setup)
- OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. It started about 2 weeks ago, I was running my jupyter notebook normally and everything was working smoothly.
2. I'm using this released version of the Jupyter notebook support as well as its renderer.
![image](https://user-images.githubusercontent.com/58731392/157504559-4ea2e1b4-15a2-4a39-8b26-06dc6a645425.png)
![image](https://user-images.githubusercontent.com/58731392/157504746-f3e6c6dc-1404-492f-a2d3-09ee0e759f77.png)
3. Before this "bug", my cells used to look like this image bellow (I know it's taken from the jupyter instance running on my local server) :
![image](https://user-images.githubusercontent.com/58731392/157504909-424a1fec-367d-4bb8-8f13-b56b43aab8d3.png)

4. Now, they look like this : 
![image](https://user-images.githubusercontent.com/58731392/157504939-76e330d5-dc3f-421a-bd89-3b6638e163c1.png)

5. If anyone knows how to change the font-family, I would very much appreciate. I'm looking for a solution since a week and no one has encoutered this before (I checked some identic issues but they were not cell-outputs related)
6. Also, I went through different types of settings in the json file and nothing had to do with the font-family of jupyter notebook **output-cell**.

Thanks in advance and have a nice day.

**Comment by rebornix** [comment]
Will be fixed in the coming recovery build, thanks for the report!
