### ISSUE TITLE
Error while fetching extensions. XHR Failed

### ISSUE THREAD

**Issue by FahmiMaulana98** [microsoft/vscode#144745]
Issue Type: <b>Feature Request</b>

I can't download extensions because XHR Failed. I don't know why this happened

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by sandy081** [comment]
Seems like issues with your network. Open following logs and see the reasons of failures

- F1 > Toggle Developer Tools
- F1 > Toggle Shared Process
