### ISSUE TITLE
Vertical scrolling erratic when clicking on scroll bar and immediately moving mouse

### ISSUE THREAD

**Issue by jimsnab** [microsoft/vscode#144770]
Does this issue occur when all extensions are disabled?: Yes/No

Yes

- VS Code Version:
1.65.1
8908a9ca0f221f36507231afb39d2d8d1e182702
x64
- OS Version:
  Operating System: Ubuntu 20.04.4 LTS
            Kernel: Linux 5.13.0-30-generic
      Architecture: x86-64
Steps to Reproduce:

1. Open a source code file with many pages of text
2. On the right side scroll bar, click a part of the file distant from the current cursor position, and immediately move the mouse back into the document.

Expected: Document scrolls many pages to the new location as clicked.

Result: There appears to be a race condition. The document will scroll to the clicked position within the document, and then scroll back to where it was, occasionally. Easy to reproduce.

It won't reproduce if the mouse pointer stays in the scroll bar for a moment after clicking.

It seems to reproduce less if the part of the document was recently visible. That is, opening a long source file fresh, then jumping around, seems to reproduce the problem easily, but after viewing enough of the document, it behaves as it should.

**Comment by alexdima** [comment]
I think you might be running into https://github.com/microsoft/vscode/issues/124895#issuecomment-970329733 . Upstream issue is https://bugs.chromium.org/p/chromium/issues/detail?id=713746
