### ISSUE TITLE
Account button won't open since 1.65.x

### ISSUE THREAD

**Issue by DevDorrejo** [microsoft/vscode#144769]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.0 & 1.65.1
- OS Version: openSUSE and Fedora

Steps to Reproduce:

1. Install VSCode version 1.65.0 or 1.65.1
2. Click accounts icon to sync account.
3. The drop-menu won't appear

**Comment by TylerLeonhardt** [comment]
@DevDorrejo do you have a libsecret based application installed like gnome-keyring?

If you don't, installing gnome-keyring should fix this for you you.

If it does, I'm curious to ask... did vscode force you to log into your accounts every time you opened it before 1.65?

**Comment by DevDorrejo** [comment]
Hello, sorry for delay, installing gnome-keyring fix the issue.

Before there were a message on notification and on terminal saying that gnome-keyring was needed, on the latest version was removed.

before 1.65 i didn't have issue with re-login each time i opened vscode.

thanks
