### ISSUE TITLE
Latest exploration renders terminal differently

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#144762]
Not saying it's a bug per se, but further investigation might be needed in order to understand the impact moving to the new Electron build might have in terms of terminal rendering:

![image](https://user-images.githubusercontent.com/22350/157467507-0f3c498c-4aa9-4f0c-bbeb-9e481f1b4523.png)

cc @Tyriar @meganrogge

**Comment by deepak1556** [comment]
@joaomoreno I am unable to see differences on my machine,

```
Edition	Windows 11 Enterprise
Version	21H2
OS build	22000.556
Resolution 1920 x 1080 @ 125% scaling
```

Couple of things to check,

* Do you have different settings between insiders and exploration ?
* Is this issue only with terminal rendering ? Does editor rendering look fine ?
* Can you tweak the values of `"terminal.integrated.gpuAcceleration"` and see if they make a difference ?

**Comment by deepak1556** [comment]
@meganrogge @Tyriar can you also try the [latest exploration](http://builds.code.visualstudio.com/builds/exploration) on your machines and confirm if you notice similar regression. We plan to promote the exploration runtime to insiders this week, so it would be helpful to understand if this is a blocker or not. Thanks!

**Comment by joaomoreno** [comment]
Weird, I can't repro on fresh user data dirs:

![image](https://user-images.githubusercontent.com/22350/157674367-fccf5364-5109-4c39-b3f2-fa55fbc51eab.png)

**Comment by joaomoreno** [comment]
OK so it turns out this has nothing to do with rendering. I thought I saw a difference between rendering... but this is just a difference in blue tint of that `vscode` first word in my PS1. And I can only repro when using my GitHub Sharp theme:

![image](https://user-images.githubusercontent.com/22350/157676026-ecb2e9b3-c6b7-4766-915e-8357486d39c3.png)

So steps:

1. Fresh user data dir, fresh extensions dir, install GitHub Sharp and enable the light theme

**Comment by joaomoreno** [comment]
Just got today's Insider update... and it has the same blue tint as exploration... just it just happened that someone changed that blue tint somewhere deep down at the same time we were testing Exploration. A huge coincidence.

**Comment by Tyriar** [comment]
The change in the blue was intentional as we (finally) switched the default of `terminal.integrated.minimumContrastRatio` to meet 4.5 (WCAG AA minimum). If it bothers you then you can switch back to 1, but having this included by default fixes some nasty issues like some pwsh args being invisible on Solarized Dark.

**Comment by joaomoreno** [comment]
Definitely not a bother. 👌
