### ISSUE TITLE
Typescript keeps on dying in vscode

### ISSUE THREAD

**Issue by Allan690** [microsoft/vscode#144750]
Issue Type: <b>Bug</b>

This is a wholly intermittent issue. Typescript keeps on dying and restarting on vscode. I'm on the February release of vscode.

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:13:50.741Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|8.00GB (0.16GB free)|
|Process Argv|. --crash-reporter-id 16f94a00-ba76-441a-bb61-24c54113eac4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ndjson|adr|0.100.0
vscode-django|bat|1.10.0
dart-code|Dar|3.36.0
flutter|Dar|3.36.0
vscode-markdownlint|Dav|0.46.0
vscode-eslint|dba|2.2.2
docs-yaml|doc|0.2.8
gitlens|eam|12.0.1
prettier-vscode|esb|9.3.0
vscode-jest-runner|fir|0.4.47
copilot|Git|1.7.5250
gitkraken-authentication|git|1.0.3
vscode-graphql|Gra|0.3.41
vscode-env|Iro|0.1.0
elixir-ls|Jak|0.9.0
vue|jcb|0.1.5
restructuredtext|lex|175.0.0
django-commands|Max|0.1.3
vscode-docker|ms-|1.20.0
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.0
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
makefile-tools|ms-|0.3.1
vscode-typescript-next|ms-|4.7.20220307
vetur|oct|0.35.0
prisma|Pri|3.10.0
quicktype|qui|12.0.46
java|red|1.4.0
vscode-yaml|red|1.5.1
elixir-formatter|sar|1.3.0
beamdasm|Val|1.1.5
intellicode-api-usage-examples|Vis|0.0.10
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.0
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
vscode-icons|vsc|11.10.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes516:30244333
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc008:30440022
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvid1:30447480
helix:30440343
vsnot107cf:30443615

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Allan690** [comment]
checking

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this. The most likely cause is an extension (perhaps a bad TS nightly build from the TS nightly extension)
