### ISSUE TITLE
Cannot save one specific file.

### ISSUE THREAD

**Issue by aoxpedition** [microsoft/vscode#144719]
Issue Type: <b>Bug</b>

1 file will not save. Others files in the same folder will save. The file was created by copying another file within VSCode explorer bar. There is no error or any reaction when I use File > Save or press Command + S. When I close all files there is still a "1 UNSAVED" badge on Open Editors.

VS Code version: Code 1.64.2 (Universal) (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.44GB free)|
|Process Argv|--crash-reporter-id 3eb03756-466e-4183-8ce8-379f80acda87|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.10.0
vscode-pull-request-github|Git|0.36.2
beautify|Hoo|1.5.0
minifyall|jos|2.10.0
markdown-preview-enhanced|shd|0.6.2
open-in-browser|tec|2.0.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30438341
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30436279
pythonvspyt640:30436486
vsbas813:30436447
vscscmwlcmc:30438804
helix:30438806
vscaat:30438848

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by JacksonKearl** [comment]
Please include detailed steps on how you got to this state, also can you check if "Save All" works here?
