### ISSUE TITLE
Settings list widget items that are not being edited don't seem to have a max width

### ISSUE THREAD

**Issue by peterokeefe-barbri** [microsoft/vscode#144783]
![image](https://user-images.githubusercontent.com/77631144/157533397-5373aa12-ee4d-40d0-a431-ceed3c26e390.png)

Issue Type: <b>Bug</b>

There is a setting that I am trying to edit that is wider horizontally than the window, and I can't scroll over to actually perform any action on it.  There is no visible horizontal scroll bar.  I tried zooming out (control -) and the settings screen's total width reduced as well.  

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|39.76GB (14.73GB free)|
|Process Argv|C:\\Users\\peter.okeefe\\Development\\code\\Alfresco\\componize-barbri-alfresco\\src\\main\\resources\\com\\componize\\barbri\\doctypes --crash-reporter-id 827e5a44-457b-448f-aadc-8a334124bc49|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|13.2.5
csharp|ms-|1.24.1
vscode-dotnet-runtime|ms-|1.5.0
powershell|ms-|2021.12.0
vsliveshare|ms-|1.0.5418
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
azurerm-vscode-tools|msa|0.15.6
vetur|oct|0.35.0
vscode-xml|red|0.19.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30448491
dsvsc009:30440023
pythonvspyt640:30442238
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvid1:30447480
helix:30440343

```

</details>

**Comment by rzhao271** [comment]
That's definitely a problem. I'll check if I forgot to reduce some widths, or if it's coming from the extension.
