### ISSUE TITLE
Files opened by Drag/Drop do not appear in File > Open Recent

### ISSUE THREAD

**Issue by ericlaw1979** [Microsoft/vscode#14474]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: ms-vscode.cpptools-0.9.2

Steps to Reproduce:

1. Drag drop a file to VS Code.
2. Edit it.
3. Close VS Code
4. Restart VS Code.
5. Click File > Open Recent

BUG: File opened in step 1 isn't shown.

Also, note that Open Recent does not log SAVED files; if you open a file and save it under a new name, the new name isn't recorded in the RECENT list.

**Comment by bpasero** [comment]
I am quite sure we have a duplicate issue for this filed already 👍

**Comment by ericlaw1979** [comment]
https://github.com/Microsoft/vscode/issues/7935 for anyone keeping score.
