### ISSUE TITLE
intellisense error in Typescript & javascript

### ISSUE THREAD

**Issue by Sangeetha-zenwork** [microsoft/vscode#144748]
We have written the needed data into yintellisense, ctrl+click going to definition are not working in .ts and .js files

Version: 1.65.1 (user setup)
Date: 2022-03-08T02:06:27.846Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by Sangeetha-zenwork** [comment]
<img width="604" alt="Screenshot_73" src="https://user-images.githubusercontent.com/101260556/157587527-2262d043-86df-4605-9ef5-fbe0c1d808f9.png">
<img width="609" alt="Screenshot_74" src="https://user-images.githubusercontent.com/101260556/157587608-2fc2e3a4-d897-48e8-a1bf-0251634fa3e0.png">
In the html file I can see the format, Find All occurrences and other options but those are not available in .ts or .js files.
I even cannot go to the definition of variables or to the file on ctrl +click on variable or file path. I started happening after version updating. It was working as usual till 08-03-2022.
I has become very difficult to work without these options.
I have tried setting "editor.multiCursorModifier": "alt" in the settings but that does not help.
Please try to help to resolve these.

**Comment by IllusionMH** [comment]
Do you see any errors that TS language service died?
Are you using workspace TS version or built-in?
Is it for each workspace or just this one?

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by Sangeetha-zenwork** [comment]
Yes, I got the some error of "VSCode - TypeScript language service died unexpectedly 5 times in the last 5 minutes" and after that it stopped working.
I am using built-in ts version. Even ts version is not shown in visual studio code and I am not able to configure it although I have typescript installed globally.
It is for every workspace,
yes, it is reproducible with all extensions disabled. In fact I didn't used any extensions

I tried even this, with F1 and >Developer: Reload Window With Extensions Disabled, but that did not help.
<img width="769" alt="Screenshot_75" src="https://user-images.githubusercontent.com/101260556/157637965-f998836b-5a3d-4505-917a-6f208ef9e96a.png">
<img width="149" alt="Screenshot_76" src="https://user-images.githubusercontent.com/101260556/157637972-514985bc-fb29-4261-b690-1300f44c73eb.png">

**Comment by IllusionMH** [comment]
Please follow steps from https://github.com/microsoft/vscode/issues/144711#issuecomment-1062427507 and also pay attention to note in that comment.

**Comment by Sangeetha-zenwork** [comment]
After TypeScript language service died, my built-in extension "TypeScript and JavaScript Language Features" was disabled. Now after enabling it, My issue is resolved,
We can enable it through Settings --> Extensions -->Type "@builtin typescript" in search bar --> Enable "TypeScript and JavaScript Language Features.

Happy coding!

Thanks for looking into it @IllusionMH
