### ISSUE TITLE
Git - Prompt and configure `user.name` and `user.email` for me

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#144738]
It would be great if VS Code would prompt and configure `user.name` and `user.email` for me.

Currently it just shows me this error, forcing me to use the CLI:

> Make sure you configure your 'user.name' and 'user.email' in git.
> 
> ![image](https://user-images.githubusercontent.com/2931520/157415251-856cd71f-ba68-47fd-b3fe-3f2425abec7c.png)

This is annoying, especially if I just installed `git` and didn't restart my computer so that it is available in `%PATH%`.
This easily puts off new users an many ways (they also need to google how to do that).

**Comment by Takerman** [comment]
I have the same problem even when I set them in the global config with the nano editor like that
`git config --global -e`
or with the standard command like that:
```
git config --global --add user.name Name
git config --global --add user.email email@work.com
```
As a temporary solution just for a repository scope I would suggest to not specifying the global flag so it can work for this repository and it will add github.com to the known hosts like that
```
git config user.name me
git config user.email me@work.com
```

**Comment by heartacker** [comment]
1. if user do not config in a special repo, Prompt that using repo-only name and email,
   - user can config the name and email
3. and give the option to use global config

**Comment by lszomoru** [comment]
Duplicate of [114049](https://github.com/microsoft/vscode/issues/114049)
