### ISSUE TITLE
auto complete snippets not available 

### ISSUE THREAD

**Issue by develop-akumar** [microsoft/vscode#144744]
Issue Type: <b>Bug</b>

Hi team,
 
auto complete snippet is not present for:

1. request.user.is_staff:

2. request.session
 snippet do not come by typing "request.se" etc

it also happens in html files and python files both.

please  add this functioality also

thankyou

VS Code version: Code 1.65.1 (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:06:27.846Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.95GB (4.57GB free)|
|Process Argv|--folder-uri file:///e%3A/01%20Python/Z%20PROJECTS%20FOR%20RESUME/HOSP_MGMT --crash-reporter-id dd577626-8f4e-4dfc-af39-fca218d4a67f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.10.0
doxdocgen|csc|1.4.0
prettier-vscode|esb|9.3.0
code-runner|for|0.11.7
beautify|Hoo|1.5.0
better-cpp-syntax|jef|1.15.13
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.0
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30448491
dsvsc008:30440022
pythonvsnew555:30450167
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvidc:30447482
helix:30440343
dockersurvey3cf:30446834
vscaac:30438847
pynewfile477:30450038

```

</details>

We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by jrieken** [comment]
Please provide minimal sample files in which this doesn't work
