### ISSUE TITLE
Word Wrap not respecting settings on open

### ISSUE THREAD

**Issue by Newcool1230** [microsoft/vscode#144727]
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.65.1 (user setup)
- Commit: 8908a9ca0f221f36507231afb39d2d8d1e182702
- Date: 2022-03-08T02:06:27.846Z
- Electron: 13.5.2
- Chromium: 91.0.4472.164
- Node.js: 14.16.0
- V8: 9.1.269.39-electron.0
- OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. File -> Preferences -> Settings -> Search(word wrap) -> Set  `editor.wordWrap` and  `diffEditor.wordWrap`: `off`
![image](https://user-images.githubusercontent.com/10657253/157390137-fe090ed5-2324-43a8-860f-e323ea31594e.png)

2. Check `settings.json` to confirm settings
![image](https://user-images.githubusercontent.com/10657253/157392074-8bea06d2-156b-4b56-a087-479774db0987.png)

3. Make sure `Word Wrap` is unselected
![image](https://user-images.githubusercontent.com/10657253/157391796-73fe856b-91b1-4d6f-9484-afd7d2f6730b.png)

4. Close VScode.
5. Open and see `Word Wrap` checked
![image](https://user-images.githubusercontent.com/10657253/157392230-e7fd578a-22ce-42bc-ad5d-7df7231fe138.png)

**Comment by gjsjohnmurray** [comment]
Did you check for any workspace-level settings?

**Comment by Newcool1230** [comment]
> Did you check for any workspace-level settings?

workspace had the same settings
![image](https://user-images.githubusercontent.com/10657253/157394524-88eea046-03df-440a-91a3-944b19793bd9.png)

**Comment by alexdima** [comment]
This file is most likely identified as being dominated by long lines (i.e. >50% of the characters in the file lie on lines longer than 10k chars). This can be disabled using Alt+Z or the word wrap toggle button that appears in this case in the editor title area. Let's track in https://github.com/microsoft/vscode/issues/139340#issuecomment-1008630140
