### ISSUE TITLE
All my work is gone.

### ISSUE THREAD

**Issue by Lexihig98** [microsoft/vscode#144796]
Issue Type: <b>Performance Issue</b>

I havent signed into VS in a couple weeks, but when I did its showing that all my files are gone and the dont exist? saying "file not found" I always save my work why is this happening ? it was 4 weeks worth of my time 

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.76GB free)|
|Process Argv|--crash-reporter-id fca55cd3-c992-4bda-be5b-698026489cf1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    91	  8072	code main
    0	   131	  6680	   gpu-process
    0	   156	 12852	   window (Lexihignellassignment3change.html - Untitled (Workspace) - Visual Studio Code)
    0	    94	 13980	   shared-process
    0	    70	 19808	     fileWatcher
    0	    67	 21280	     ptyHost
    2	    81	 14564	   issue-reporter
    0	    25	 18612	   crashpad-handler
    0	    12	 18880	   C:\Users\Lexi\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-8908a9ca0f221f36507231afb39d2d8d1e182702.exe /verysilent /update="C:\Users\Lexi\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-8908a9ca0f221f36507231afb39d2d8d1e182702.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0	    40	 16748	     "C:\Users\Lexi\AppData\Local\Temp\is-0L4AL.tmp\CodeSetup-stable-8908a9ca0f221f36507231afb39d2d8d1e182702.tmp" /SL5="$20856,74695536,828416,C:\Users\Lexi\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-8908a9ca0f221f36507231afb39d2d8d1e182702.exe" /verysilent /update="C:\Users\Lexi\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-8908a9ca0f221f36507231afb39d2d8d1e182702.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0	    38	 19572	   utility-network-service
    0	   104	 19848	   extensionHost
    0	    94	 17872	     "C:\Users\Lexi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Lexi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=19848
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Lexihignellassignment3change.html - Untitled (Workspace) - Visual Studio Code)
|    Folder (assignment3-Lexihig98): 1 files
|      File types: md(1)
|      Conf files:
|    Folder (ass2): 0 files
|      File types:
|      Conf files:;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30442554
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc008:30440022
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvid1:30438799
helix:30440343

```

</details>

**Comment by gjsjohnmurray** [comment]
Where were you storing your work? Some people make the mistake of storing it in subfolder of the Windows folder in which VS Code gets installed on Windows. That entire folder tree gets deleted during a VS Code update to a new version.

**Comment by joyceerhl** [comment]
@bpasero assigning to you to start off since this seems file i/o related.

**Comment by gjsjohnmurray** [comment]
Maybe #138815
