### ISSUE TITLE
Grid: support proportional resize

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1447]
- open 2 editors, and layout them in a wat that one occupies a bigger part of the screen
- cmd + B closes the viewlet, now each editor gets additional space, you give them additional space proporitonal to their current size
- I argue that it would be better to just give them all equal space

This style would fit my workflow better. Since the way you are doing it the small will keep being small, and the larger just get super large -> like in kapitalistic society

**Comment by isidorn** [comment]
Assigning back to @bpasero and @alexr00 since you guys worked on this and this seems to have been my wish for the past 4 years :D

**Comment by bpasero** [comment]
@isidorn not sure the grid will do what you want though: if when the window size changes (or the sidebar hides/shows) it looks like the space is added simply to the last grid, but not evenly across groups as we do currently:

[video.gif.zip](https://github.com/Microsoft/vscode/files/1990607/before.gif.zip)

**Comment by isidorn** [comment]
@bpasero yeah I would say that is unexpected. Preserving layout would be the best. And for that the new availble space shuold be split up evenly.

**Comment by bpasero** [comment]
@isidorn ok this is now entirely handled by the grid widget so I will move this to @joaomoreno

**Comment by joaomoreno** [comment]
The fix was done in the splitview, so many UI areas improved with the changes: grid, panels, terminal.
