### ISSUE TITLE
bracket pair highlight support for `<>`

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#144723]
Recently I did many typescript type excercises by https://github.com/type-challenges/type-challenges. I need to write many generic with `<>` bracket pair.

For example:

```
    Expect<Equal<UnionToIntersection<(() => 'foo') | ((i: 42) => true)>, (() => 'foo') & ((i: 42) => true)>>
```

I hard to regonize which part is the generic parameter for type `UnionToIntersection`.

I can recogonize the function part by put cursor bufore `(` like:

![image](https://user-images.githubusercontent.com/41773861/157382883-bf270f56-d721-495a-a9ca-5b24e0f3380e.png)

But can't by put cursor before `<`:

![image](https://user-images.githubusercontent.com/41773861/157382978-22f5bfac-02a4-40f8-acfb-edabc128a34b.png)

@hediet

**Comment by IllusionMH** [comment]
This was intentionally disabled as `<>` breaks on many occasions as highlight is text based (for performance reasons). See #132476 and ton of duplicates for details.
If you follow steps from https://github.com/microsoft/vscode/issues/131412 and enable it for TS you would get much worse result
![image](https://user-images.githubusercontent.com/1312662/157396621-c67f7d72-cda2-4824-8ef1-32c2735b2fa5.png)

I guess that you should use extension that provides languages specific highlights if you prefer correctness/features over performance(main reason to implement it in editor).

**Comment by tjx666** [comment]
Seems need ast to analyze the color pair in typescirpt  for `<>`

**Comment by hediet** [comment]
In theory, the grammar could mark certain unbalanced occurences of `<` and `>` as a special token kind (like comment, string or regexp).
Proper support is not planned at the moment.
