### ISSUE TITLE
Use textmate grammar token kind to exclude unbalanced brackets from being colorized

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#144736]
When a bracket is marked as comment, string or regexp token, it is not considered for bracket pair matching. It would be great to have a `non-bracket` token, so that we can use `<` ... `>` in languages such as TypeScript or rust, where it is both used as bracket and as comparison operator. The comparison operator should have token-kind `non-bracket`.

Would fix #144723, #138868, #142117, #145219 and others.

@alexdima FYI

---

We could some bits from the background color:

https://github.com/microsoft/vscode-textmate/blob/677f741f5b5ef69589e0e5d2a6e556f94514cbfd/src/main.ts#L217

**Comment by Lemmingh** [comment]
I like the idea of taking advantage of parsing result.

However, I wonder if it's reliable to use TextMate-based tokenization. TextMate grammar has serious limitations, and cannot correctly express many languages, like C++, TypeScript, HTML, and Markdown. For example, we **have to compile** the whole project first to understand this C++ code:

```cpp
a<b<c>> d;
```

Perhaps [semantic tokens](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-token-classification) will be a good candidate to power this feature.

**Comment by hediet** [comment]
verification steps:

A grammar contribution can now define `balancedBracketScopes` (defaults to `['*']`) and `unbalancedBracketScopes` (defaults to `[]`).

The easiest way to try this is out is by changing an existing grammar contribution (package.json -> contributes/grammars, like [here](https://github.com/microsoft/vscode/blob/2b14c472348f0289fc5ce25d1d5651db43138af8/extensions/shellscript/package.json#L80))

There you can list scopes to exclude or include scopes which contains balanced brackets. 
```
"balancedBracketScopes": [
    "*"
],
"unbalancedBracketScopes": [
    "meta.scope.case-pattern.shell"
]
```

Verify that bracket pair colorization does not colorize scopes which contain unbalanced brackets.

**Comment by rchiodo** [comment]
/verified, I think?

I opened a 'sh' file with stable and insiders.

For the case-pattern, stable will show this:

![image](https://user-images.githubusercontent.com/19672699/165583508-4c1a7e7c-c84b-4663-b569-61476a8d759b.png)

Insiders shows this, where it looks to me like it's allowing the unbalanced bracket scope.

![image](https://user-images.githubusercontent.com/19672699/165583628-6f06d61a-d78f-48ba-b77c-710c6d58c19b.png)
