### ISSUE TITLE
Default place for extension to store cache/data?

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14476]
I'm writing an extension that downloads a few files, and I don't know where I should put it to.

- Extension Path -> Will be wiped out when updating
- Workspace -> I don't want to pollute user's workspace

Imo VSCode should give extension a default place to put cache, downloaded files, etc.

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/blob/988968870172253522e61e63a3811fd660021676/src/vs/vscode.d.ts#L3197

**Comment by thelink2012** [comment]
I don't think this is a solution, I don't want to duplicate cached data for each workspace.

**Comment by joaomoreno** [comment]
cc @jrieken

**Comment by jrieken** [comment]
Pick any folder you like and store the path as global memento

**Comment by Jakobud** [comment]
Last year I developed the following Node module that simplifies caching data for extensions:

https://www.npmjs.com/package/vscode-cache

It has a very simple api.

**Comment by jrieken** [comment]
There is also [`storagePath`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3357)
