### ISSUE TITLE
Linux: DND of editor tabs flickers

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14470]
Testing #14016 
- VSCode Version: Code - Insiders 1.7.0-insider (5bafcdb3d67b29b1f4667a3f497ac05a41dde667, 2016-10-25T06:19:07.301Z)
- OS Version: Linux x64 4.4.0-45-generic, Ubuntu 16.04
- Extensions:

| Extension | Author | Version |
| --- | --- | --- |
| EditorConfig | EditorConfig | 0.3.4 |
| lorem-ipsum | Tyriar | 1.0.0 |
| sort-lines | Tyriar | 1.1.0 |
| terminal-tabs | Tyriar | 0.0.6 |
| theme-glacier | Tyriar | 0.0.10 |
| vscode-icontheme-nomo-dark | be5invis | 1.1.5 |
| vscode-svgviewer | cssho | 1.2.0 |
| vscode-eslint | dbaeumer | 1.0.8 |
| git-project-manager | felipecaputo | 0.1.15 |
| Theme-Wombat | gerane | 0.0.2 |
| csharp | ms-vscode | 1.4.1 |
| typescript-javascript-grammar | ms-vscode | 0.0.6 |
| nova | rebornix | 0.0.5 |
| sass-indented | robinbentley | 1.1.0 |
| annotator | ryu1kn | 0.10.1 |

I may have reported this before but it really bugs me, I have a recording this time.

Steps to Reproduce:
1. Grab a tab
2. Move it over another tab, in particular in between the title and the close button

![out](https://cloud.githubusercontent.com/assets/2193314/19697963/531151e8-9aa2-11e6-9173-96e3c7417a31.gif)

**Comment by bpasero** [comment]
Does not reproduce on Mac at least.

**Comment by bpasero** [comment]
If someone wants to look into this, we have the DND logic here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L141

I think we get lots of drag-leave and drag-enter events and on Linux you see the flashing while on other platforms Chrome seems smarter how to apply the feedback and the flash is not visible.

**Comment by bpasero** [comment]
More findings: On all OS the `drag_leave` event is fired while dragging over a tab because of the elements within the tab (label, icon, close button). However only on Linux you notice this event causing a visual effect (the drop feedback is removed). On all other OS the feedback stays I guess because quickly after you get a `drag_over` event that invalidates the previous event.

**Comment by bpasero** [comment]
Good solution: http://stackoverflow.com/questions/7110353/html5-dragleave-fired-when-hovering-a-child-element

**Comment by Tyriar** [comment]
Great, this will make it feel a lot more responsive on Linux :tada:

**Comment by chrmarti** [comment]
Verified and filed #16992, which seems to be related, but not the same.
