### ISSUE TITLE
Tabbed sidebars

### ISSUE THREAD

**Issue by PineaFan** [microsoft/vscode#144785]
The bottom of the screen (terminal, comments, output etc.) can have tabs to switch between, however, the sidebars (outline, file tree, extensions etc.) are forced to be in an expanding list with dropdowns. Adding this would also remove inconveniences with resizing the sections each time you open up different ones

**Comment by gjsjohnmurray** [comment]
Have you tried using the Side Panel yet?

**Comment by PineaFan** [comment]
I tried to get that, but couldn't find an easy way to make it

If it is possible, change the feature request to just making it easier to create, maybe by dragging 2 pannels over each other

**Comment by sbatten** [comment]
Side bars are already "tabbed" ... In the primary side bar (the one you mention), the activity bar acts as a tab picker. The same is true for the "side panel" (currently undergoing a rename in insiders). THe "side panel" works just like the bottom panel in terms of tabbing except it uses a horizontal row of icons. Can you help me understand what you'd like to see changed here?

**Comment by PineaFan** [comment]
For the side bar (left/right), is there a way to make it only the words as tabs like the terminal, or as a row of icons to switch between?
Currently it's only a list with each extension being a bar which can expand downwards, and it'd be nice to have one button to change the whole sidebar like terminal/output/comments etc.

**Comment by sbatten** [comment]
No, not with one button, but you can drag views into their own tab to replicate this behavior
