### ISSUE TITLE
Integrated Terminal eats half of the first line when you zoom

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#14479]
- VSCode Version: 1.7.0-Insiders
- OS Version: macOS

Steps to Reproduce:
1. Launch Integrated Terminal
2. Keep press `cmd +` to zoom out from zoom level `0` to `5`, you can see that the first line is not shown correctly for every zoom level.

**Comment by ramya-rao-a** [comment]
Same thing happens when you increase `editor.fontsize`

**Comment by Tyriar** [comment]
To verifier: Please test in Windows and Mac

**Comment by dbaeumer** [comment]
Tested under Windows and it works. Don't have a Mac.

**Comment by joaomoreno** [comment]
LGTM
