### ISSUE TITLE
Markdown source view strikethroughs/tildes unescapable and wrongly being strikethrough.

### ISSUE THREAD

**Issue by rubyleehs** [microsoft/vscode#144715]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.65.1
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Create a new empty markdown file.
2. Type the following: 
```
~Case 1~

\~Case 2~

~Case 3\~

~~Case 4~

~Case 5~~

~~Case 6~~

~~ Case 7 ~~

~\~Case 8~~

~~Case 9~\~

\~\~Case 10\~\~ 
```

![Code_2022-03-09_10-43-35](https://user-images.githubusercontent.com/29061180/157362508-35b43fd7-b7eb-4966-b131-acf8c6c24f2f.png)

**Comment by rubyleehs** [comment]
More cases:
```
| ~Case 11 | ~Case 12 |
|:--------:|:--------:|
| This is  | A table  |
```
![image](https://user-images.githubusercontent.com/29061180/157363426-1b2b3fcb-ba4a-4b77-b4cb-f13eb7f8fc5f.png)

**Comment by mjbvz** [comment]
Thanks for the examples

This is already tracked by  https://github.com/microsoft/vscode-markdown-tm-grammar/issues/104
