### ISSUE TITLE
Ability to display Symbols list on a Panel

### ISSUE THREAD

**Issue by coreh** [Microsoft/vscode#14473]
I'd love to have the ability to persistently display the Symbols list for the current file on a Panel, that way I could have a split screen of my code on the left, and this on the right:

<img width="620" alt="screen shot 2016-10-25 at 16 07 49" src="https://cloud.githubusercontent.com/assets/418473/19698335/a2eb1ce6-9acd-11e6-962a-e3fe895bc5c7.png">

Instead of having to press Cmd + Shift + O to display it like a popover every time.

This is possibly related to #9418, but not exactly the same.

Thanks in advance!

**Comment by mikesmullin** [comment]
this guy's plugin does the job
https://github.com/Microsoft/vscode/issues/5605#issuecomment-312248074

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/5605
