### ISSUE TITLE
Disabled button looks enabled when focused

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#144749]
Are the colors correct here? If a disabled button gets focus, it no longer looks disabled

![recording](https://user-images.githubusercontent.com/2931520/157441150-c34b6a6c-b7a9-4683-bd08-ce0355de3970.gif)

https://github.com/microsoft/vscode/commit/3479bb35904eb046c0974090794cac9c76173796

**Comment by joaomoreno** [comment]
@isidorn This started from: https://github.com/microsoft/vscode/commit/3479bb35904eb046c0974090794cac9c76173796

What's the reasoning behind keeping tab indexes on disabled elements? Doesn't make much sense to me.
