### ISSUE TITLE
Problems with snippets using choice as values

### ISSUE THREAD

**Issue by pelos6** [microsoft/vscode#144756]
Issue Type: <b>Bug</b>

I'm using a snippet with choice like the one attached and it doesn't work. It does not show the elements of the selection and also keeps showing the message "Loading"

"PRUEBA": {
		"prefix": "PRUEBA ",
		"body": [
			"# ${1|CORREO,LLAMADA|} DE ${2|JUAN,PEDRO,ANA,MARIA|}"
		] ,
		"description": "para probar el posible error"
	}

VS Code version: Code 1.65.1 (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:06:27.846Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.02GB free)|
|Process Argv|. --crash-reporter-id 5277205b-ea6b-4ea4-8d6c-baca55cc7719|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-insertdatestring|jsy|2.3.1
vscode-language-pack-es|MS-|1.65.2
vscode-fileutils|sle|3.5.0

</details>

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"snippets"+label%3A"new release"
