### ISSUE TITLE
Intelisense in Vue.js component

### ISSUE THREAD

**Issue by Kcko** [microsoft/vscode#144751]
Hi,

I have problem with JavaScript intelisense in *.vue file.

Im using standard packages like JS linter, Prettier, Vetur, Vue snippets etc.

When i load heavy project (huge node_modules dir etc), intelisense in vue files works very slowly, very often never.

I see very often these messages: https://bit.ly/3MF8jhs

I don't know how to configure VSC and generally I don't know how to find out what it causes.
Javascript (native) hints don't work, tailwind classes don't tell me, vue snippets don't work.

- https://bit.ly/3Cpwrji (native js intelisense - loading 4ever)
- https://bit.ly/3CrwJpK (some message which points to configuring excludes or what...)

How exactly to configure exclude files, to what file, some example or is it something else?

My failed attempt: 
- https://bit.ly/35Gw33X  (json config file in root of project)

Thx

**Comment by mjbvz** [comment]
Please file this against the due extension

**Comment by Kcko** [comment]
Hi,
is not related to any JS extension or Vue extension.

this is topic which help me https://stackoverflow.com/questions/59653911/project-wide-javascript-typescript-language-error-from-built-in-language-extensi

And config which help me.

```
{
  "exclude": [
    ".git",
    "vendor",
    ".app-cache",
    ".npm",
    "www",
    ".npm-tmp",
    "dist",
    "dist*",
    "node_modules",
    "subfolder/dist",
    "subfolder/node_modules",
    "**/dist/*",
    "**/node_modules/*"
  ]
}
```
