### ISSUE TITLE
Auto show debug console when starting a debug session

### ISSUE THREAD

**Issue by Susensio** [microsoft/vscode#144734]
I would be nice if Debug Console could be automatically focused (maybe via an option) or at least it could be brought to front when it is hidden, when a debug session starts. Right now, the terminal in which that debug session is launched is shown. This is a good behaviour.
I have my terminal in the sidepanel, and problems and debug console in the regular panel (at the bottom). Normally the problems tab is on top.
What I would like is to bring debug console to front.

What happens:
![image](https://user-images.githubusercontent.com/11474625/157402727-3211156d-f2a8-47dc-9eb8-46b084f74c28.png)

What I would like to happen:
![image](https://user-images.githubusercontent.com/11474625/157402824-ebe8bd48-1f20-4151-bdc0-83960a1958b9.png)

**Comment by weinand** [comment]
@Susensio Have you tried the setting `"internalConsoleOptions": "openOnSessionStart"`?

**Comment by Susensio** [comment]
I've just tried that. It did not change the behaviour.

**Comment by roblourens** [comment]
Are you sure? It works for me. The setting is `"debug.internalConsoleOptions": "openOnSessionStart"`

**Comment by Susensio** [comment]
Affirmative. It is not working. I have the integrated terminal in the side panel (maybe this is an issue).


With `"debug.internalConsoleOptions": "openOnSessionStart"`
before:
![image](https://user-images.githubusercontent.com/11474625/157631496-10aced5a-882a-4f1d-a724-2bc4b5d5da39.png)

`F5`

![image](https://user-images.githubusercontent.com/11474625/157631731-d5638614-4c7c-4aec-811e-93d0013a300f.png)

As you can see, the Python Debug Console opens on the side, but not the DEBUG CONSOLE that's on the bottom, it keeps showing PROBLEMS. I would like the bottom one to show up.

**Comment by roblourens** [comment]
I see that it's working differently with Python, not sure why, thanks

**Comment by roblourens** [comment]
I see that this setting gets overridden dynamically by the python debug extension. But you can override that by creating a launch.json with your own debug configuration, and setting `"internalConsoleOptions": "openOnSessionStart",` in that debug config
