### ISSUE TITLE
title and split decoration are orange when an extension wants to change environment variables

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#144705]
Not sure if this is by design, but I find it distracting and think it would be better to not have the title, description, and split decoration colored.
![Screen Shot 2022-03-08 at 2 12 10 PM](https://user-images.githubusercontent.com/29464607/157317367-0a30f139-9da4-43dd-bd6d-058e51315592.png)

**Comment by Tyriar** [comment]
I think this was harder to do than expected
