### ISSUE TITLE
disable jupyter editor in vscode

### ISSUE THREAD

**Issue by uselibrary** [microsoft/vscode#144722]
I know this issue might be duplication, but there is no way to disable jupyter editor in vscode since 2019.
As [#103526](https://github.com/microsoft/vscode/issues/103526) and [#105661](https://github.com/microsoft/vscode/issues/105661) said, "I want to new a file just for text or markdown, I do not like to appear a choice between two, but just default for the inner editor applied by vscode.", "I don't think the current New File behavior should be the default for everyone who uses VSCode" and "how to disable jupyter editor in vscode?".

related: ms-python.python @ vscode

**Comment by Lemmingh** [comment]
Your words confuse me.

---

Which "New File" command did you refer to?

* `explorer.newFile`
* `workbench.action.files.newUntitledFile`
* `welcome.showNewFileEntries`

Only the `welcome.showNewFileEntries` command can lead to the ["Create New" menu](https://code.visualstudio.com/api/references/contribution-points#contributes.menus), to my knowledge. The commonly used `workbench.action.files.newUntitledFile` command invokes the built-in text editor.

---

What do you mean by "disable"?

As you probably already know, the "Jupyter Notebook" option in the "Create New" menu comes from the Jupyter (`ms-toolsai.jupyter`) extension: <https://github.com/microsoft/vscode-jupyter/pull/7597>

If you want to remove the Python and Jupyter extensions, just uninstall them and restart VS Code.

**Comment by lramos15** [comment]
@uselibrary as @Lemmingh pointed out there is a lot of new flows here. You should be able to go File > New file (note the lack of the three dots) and get a blank text file. Command / Ctrl + N should do this for you as well.
