### ISSUE TITLE
Restart kernel and Stop kernel commands should have a 'when' clause to exclude them when not using Jupyter (extension) kernels

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#144792]
Similar to https://github.com/julia-vscode/julia-vscode/issues/2757
Basically we too are displaying items in the toolbar when we shouldn't be

**Comment by greazer** [comment]
Discussed at notebook standup. Determined there's an issue in core to help here.

**Comment by weinand** [comment]
@DonJayamanne it would be great if you could assign these issues and not only label them.
Otherwise th3 bot assigns them to random devs and they all have waste time trying to assign them.

**Comment by DonJayamanne** [comment]
> it would be great if you could assign these issues and not only label them.

I didn't transfer this issue.

**Comment by roblourens** [comment]
Sorry, I don't see the issue. It looks like we are applying context keys correctly and I don't see the buttons showing up when they shouldn't
