### ISSUE TITLE
Badges for problems in file explorer and tab when colors are turned off

### ISSUE THREAD

**Issue by shahsaumya** [microsoft/vscode#144794]
I have disabled decorations for problems however want to keep the badges in the explorer view and the file tabs. The colors are disabled because they get mixed up with the git decorations and can get confusing. However having the badges on the side like in gitDecorations would be useful for errors and warnings. This is available in the Outline View but not in the File Explorer or File tabs.

Thanks!

Version: 1.65.0 (Universal)
OS Version: MacOS Monterey (v12.0)

**Comment by jrieken** [comment]
You should be able to disable colours and badges individually. Which exact setting did you configure?

<img width="647" alt="Screenshot 2022-03-11 at 08 31 38" src="https://user-images.githubusercontent.com/1794099/157822411-07129f86-7729-4cdb-ad69-d772a83fea85.png">

**Comment by jrieken** [comment]
ping @shahsaumya ⬆️

**Comment by shahsaumya** [comment]
Sorry for the late response. I wanted to show errors and warnings as badges only in the file explorer, no colors on the file names. I can disable colors in the outline, but not in the file explorer. It shows up as "decorations" only. 
<img width="1249" alt="Screen Shot 2022-03-24 at 12 07 55" src="https://user-images.githubusercontent.com/22012604/160007298-07d61a53-68f7-4846-a430-119393461a8c.png">

**Comment by jrieken** [comment]
You can do with this setting: `explorer.decorations.colors`
<img width="1279" alt="Screenshot 2022-03-25 at 08 37 33" src="https://user-images.githubusercontent.com/1794099/160075768-4358f73f-3579-4012-a6f1-65fc0fc9e481.png">
