### ISSUE TITLE
Dark/Light UI mode changes open settings.json in editor with errors

### ISSUE THREAD

**Issue by 497e0bdf29873** [microsoft/vscode#144888]
Issue Type: <b>Bug</b>

Either vscode has a universal bug or it has somehow gone into a "mode", which I do not know to trigger.  However, *whenever* the operating system switches between dark/light user interface mode, vscode opens `settings.json` in the editor and complains with a notification popup that

> Failed to save 'settings.json': The content of the file is newer.  Please compare your version with the file contents or overwrite the content of the file with your changes.

Sometimes there is also:

> Unable to write into user settings because the file has unsaved changes. Please save the user settings file first and then try again.

This happens both on schedule, or simply going into `System Settings -> General` and switching between Auto/Light/Dark (Switching between Light and Auto when the mode would be schedule be Light does not trigger the issue.  Same with Dark/Auto when the scheduled mode would Dark.)

I've closed `settings.json` every time after it is opened, but consistently, whenever there is a Dark/Light mode switch, vscode opens it in the editor with the above complaints.

VS Code version: Code 1.65.0 (Universal) (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:11:20.886Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id de7fcaec-566a-4c68-9643-27cba9b0c7c0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.4
texlab|efo|3.3.2
markdown-extended|jeb|1.1.1
touchbarcommandshortcuts|jos|0.0.2
vscode-insertdatestring|jsy|2.3.1
language-julia|jul|1.5.11
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.1
vscode-paste-image|mus|1.0.4
rust|rus|0.7.8
trailing-spaces|sha|0.3.1
non-breaking-space-highlighter|vik|0.0.3
latex-syntax|vom|0.0.7
vscode-todo-highlight|way|1.0.5
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30440023
pythonvspyt640:30450904
vscscmwlcmt:30438805
dockersurvey3:30446832
pynewfile477cf:30450039

```

</details>

**Comment by yume-chan** [comment]
Does it happen with all extensions disabled? (F1 -> Reload with extensions disabled)

> The content of the file is newer. Please compare your version with the file contents 

Did you try to hit compare button and see what's conflicting?

> whenever the operating system switches between dark/light user interface mode

Does your Code change theme in sync to OS? (`"window.autoDetectColorScheme": true`)

**Comment by 497e0bdf29873** [comment]
Yes, auto-detect is on.

It seems that the culprit may have been the `touchbarcommandshortcuts` extension, which I didn't even notice that I still had (it is a leftover from my previous laptop that I don't even need on this one). Sorry I didn't notice to disable that before reporting. (I did already disable Monkey Patch and Customise UI that I use to get a compact title bar, as those seemed liked potential culprits.)

I'll close this for now.
