### ISSUE TITLE
vscode intellisense does not work? Input fails ,but deletion works~

### ISSUE THREAD

**Issue by horrylala** [microsoft/vscode#144818]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.65.1 (Universal)
Commit: 8908a9ca0f221f36507231afb39d2d8d1e182702
Date: 2022-03-08T02:20:11.670Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0

Steps to Reproduce:
1.when i input some characters , it does not show tips.
2.when i delete some characters, it shows.

The issue only occurs in javascript/typescript, in html/css, it works fine.

![20220310-154425](https://user-images.githubusercontent.com/12706476/157613023-f11c96b5-31d7-45f0-b387-1d767eb35274.gif)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also, please share you user settings so we can investigate if one of them is causing this

**Comment by horrylala** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
> 
> Also, please share you user settings so we can investigate if one of them is causing this

My VS Code is latest and disabled all extensions.
Version: 1.65.2 (Universal)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0

![image](https://user-images.githubusercontent.com/12706476/157788322-2e603857-22f6-43e9-8d45-a40d0958e5f6.png)

My settings.json file is as follows:
// settings.json
{
    "workbench.colorCustomizations": {
    },
    "files.associations": {
        "*.wpy": "vue",
        "*.js": "javascript",
        "*.wxml": "wxml",
        "*.wxss": "css",
        "*.cjson": "jsonc",
        "*.wxs": "javascript",
        "*.tpl": "tpl"
    },
    "editor.fontFamily": "Monaco, 'Courier New', monospace",
    "editor.fontSize": 14,
    "editor.tabSize": 2,
    "typescript.updateImportsOnFileMove.enabled": "always",
    "[vue]": {},
    "javascript.updateImportsOnFileMove.enabled": "never",
    "editor.wordWrap": "on",
    "javascript.validate.enable": false,
    "javascript.format.insertSpaceBeforeFunctionParenthesis": true,
    "typescript.format.insertSpaceBeforeFunctionParenthesis": true,
    "emmet.includeLanguages": {
        "wxml": "html"
    },
    "terminal.external.osxExec": "/bin/zsh",
    "git.autofetch": true,
    "leetcode.defaultLanguage": "javascript",
    "git.enableSmartCommit": true,
    "editor.foldingStrategy": "indentation",
    "files.exclude": {
        "**/*.meta": true,
        "library/": true,
        "local/": true,
        "temp/": true
    },
    "search.exclude": {
        "**/*.anim": true
    },
    "editor.codeActionsOnSave": {
        "source.fixAll.tslint": true
    },
    "diffEditor.ignoreTrimWhitespace": false,
    "[typescript]": {},
    "workbench.colorTheme": "Solarized Light",
    "gitlens.views.commits.files.layout": "tree",
    "[javascript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "editor.quickSuggestions": true,
    "typescript.tsserver.trace": "verbose"
  }

When i delete all  configurations in settings.json, the same problem still exists.
By the way, it works not well after i upgrade my Mac OS Stystem to macOS Montery.Hope this should help.

**Comment by mjbvz** [comment]
Hm, I can't reproduce this using those settings

Do suggestions show up if you manually them using `ctrl` + `space`? Also what's the language mode of your keyboard layout and operating system?

**Comment by horrylala** [comment]
> Hm, I can't reproduce this using those settings
> 
> Do suggestions show up if you manually them using `ctrl` + `space`? Also what's the language mode of your keyboard layout and operating system?

Wow, it's amazing, when i change my input source(the keyboard layout) , it works, thanks a lot.
