### ISSUE TITLE
VS Code breaks my internet connection

### ISSUE THREAD

**Issue by artrayd** [microsoft/vscode#144816]
Issue Type: <b>Bug</b>

It downloads something all the time on each start!
Everything was great before, this issue started few weeks ago.

I  think that I will move to another code editor - I have no idea how to solve that problem, I can't use internet till VS Code downloads 500MB of some data. That looks suspicious! 

VS Code version: Code 1.64.2 (Universal) (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.75GB free)|
|Process Argv|--crash-reporter-id 9896fab0-ee99-454e-adae-ad01a7744d23|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.2
prettier-vscode|esb|9.3.0
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.1
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
vetur|oct|0.35.0
vue-vscode-snippets|sdr|3.1.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc008:30440022
pythonvsnew555:30450902
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvidc:30447482
helix:30440343
vscaat:30438848
pynewfile477:30450038

```

</details>

**Comment by IllusionMH** [comment]
> VS Code version: Code 1.64.2

What are your update settings? Looks like VS Code might try to auto-update to 1.65.

**Comment by artrayd** [comment]
@IllusionMH that was on default. Previously I had no issues with updates, just had "What's New Screen", now it just downloads something for a while without any result. 

I will try to update manually

**Comment by artrayd** [comment]
Thank you @IllusionMH seems like it solved the issue :)
