### ISSUE TITLE
fontStyle: underline does not decorate text with underline style

### ISSUE THREAD

**Issue by rbadapanda** [microsoft/vscode#144805]
Issue Type: <b>Bug</b>
Apply the following in settings.json and open a .js file with a function definition

```
    "editor.tokenColorCustomizations": {
        "textMateRules":[
            {
                "scope": "entity.name.function",
                "settings": {
                    "fontStyle": "underline bold"
                }
            }
        ]
    },
```

REPRO: you will notice the text is rendered bold but is not underlined

VS Code version: Code 1.65.1 (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:20:11.670Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ArturoDent** [comment]
`underline` is not a css `font-style` value, see https://developer.mozilla.org/en-US/docs/Web/CSS/font-style.

And so is not supported in the  `tokenColorCustomizations`.

**Comment by alexdima** [comment]
@rbadapanda I cannot reproduce:

<img width="810" alt="image" src="https://user-images.githubusercontent.com/5047891/157625831-4cf827a8-e76d-49d8-9df0-143e66abdcfb.png">

**Comment by rbadapanda** [comment]
Hi Alex,

It was my bad one of my extensions - customizeUI - was responsible for it.

Please ignore it. I am going ahead to close this one.

Thanks!
