### ISSUE TITLE
Testing: Test peek auto open opens first output instead of error output

### ISSUE THREAD

**Issue by JDaance** [microsoft/vscode#144833]
Does this issue occur when all extensions are disabled?: No

Version: 1.65.1
Commit: 8908a9ca0f221f36507231afb39d2d8d1e182702
Date: 2022-03-08T02:09:03.269Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.15.25-1-MANJARO snap

I have general test output at the test declaration line 40, visible in grey. Then there is a specific error at line 47 visible in red. The auto open test peek opens as it should, but at line 40 instead of 47. I want it to focus on the error first, not the general output

Without peek open:
![image](https://user-images.githubusercontent.com/1148112/157668871-e064128b-e67a-4361-80a5-275f7cf1b157.png)

With auto opened peek:
![image](https://user-images.githubusercontent.com/1148112/157668570-b5e9b7ba-005e-4528-831a-4e34dd6d5162.png)

**Comment by TylerLeonhardt** [comment]
@connor4312 how about some verification steps unless @JDaance resurfaces?

**Comment by connor4312** [comment]
1. In some vscode test, add console.log's
2. Make the test fail a few lines down
3. Use the selfhost test provider, and run the test
4. Verify that the error message is opened in the peek, rather than the first console.log

**Comment by TylerLeonhardt** [comment]
![image](https://user-images.githubusercontent.com/2644648/215228376-a0965a07-119c-4d85-9fe1-c6a99f55fd00.png)
LGTM
