### ISSUE TITLE
Updating causes Vscode Error code 183

### ISSUE THREAD

**Issue by Robotrowful** [microsoft/vscode#144872]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.1
- OS Version: Windows 10

Steps to Reproduce:

1. Load Visual studio code
2. Get notified an update is available
3. Update
4. Error
 
After updating Vscode's shortcut wont open, Code.exe has became blank. saying I don't have permission to access item. 
Opening as administrator does nothing.
Using the uninstaller leaves code.exe behind.
Reinstalling doesn't replace code.exe
Unable to delete the file whilst as administrator
Unable to change the permissions even as admin  

I am now stuck to two Code.exe that cant be removed from my system
![Error File 2](https://user-images.githubusercontent.com/96312403/157784992-3c26b230-f769-49ef-91ca-a3788c287fcf.png)
![Error File](https://user-images.githubusercontent.com/96312403/157786621-f47dffba-bec3-4994-a6ed-900a91357819.png)
![Error File 3](https://user-images.githubusercontent.com/96312403/157786702-e2eeb25f-874c-4f93-93a4-25d19aa94461.png)
![Error File 4](https://user-images.githubusercontent.com/96312403/157785787-df750d36-8944-4926-9ffd-f28dcd7ea207.png)
![Error File 5](https://user-images.githubusercontent.com/96312403/157786292-cef242d2-b404-416b-ac37-44c79d7a96f7.png)

**Comment by joaomoreno** [comment]
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by Robotrowful** [comment]
Sorry I dont know how set `update.enableWindowsBackgroundUpdates`  to false . I am sorry

Uninstalling keeps Code.exe
https://user-images.githubusercontent.com/96312403/157914138-d1d44cb3-9529-4cc9-9132-5909f560787a.mov

Installing and updating 
https://user-images.githubusercontent.com/96312403/157916023-10f14e79-b234-401d-a3cf-7e47462b25fe.mp4

After I ended the recording I clicked cancel and these two messages popped up 
![Error 2 msvsc3](https://user-images.githubusercontent.com/96312403/157916272-c1389599-25b3-4430-add5-54d248c9fbde.png)
![Error msvsc3](https://user-images.githubusercontent.com/96312403/157915284-92a75eb4-5210-44ce-be9d-f5924be98119.png)

Here are the error logs 
[vscode-inno-updater-1646763309.log](https://github.com/microsoft/vscode/files/8233932/vscode-inno-updater-1646763309.log)
[vscode-inno-updater-1646961307.log](https://github.com/microsoft/vscode/files/8233933/vscode-inno-updater-1646961307.log)
[vscode-inno-updater-1647018192.log](https://github.com/microsoft/vscode/files/8233915/vscode-inno-updater-1647018192.log)

(Now I have 3 inaccessible code.exe)

**Comment by joaomoreno** [comment]
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.
