### ISSUE TITLE
Remote connection: not accepting license

### ISSUE THREAD

**Issue by lorenzoinm** [microsoft/vscode#144895]
Issue Type: <b>Bug</b>

When I try to connect to a linux machine, i get an error about not accepting the license from the vs-code server:
"To accept the license terms, start the server with --accept-server-license-terms"
I did as this answer suggests and it works for now: https://stackoverflow.com/a/71133075

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.15.0-161-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.34GB free)|
|Process Argv|--crash-reporter-id 77d2c1a1-381a-4a61-8de9-ec1ee07728f3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ws-lnx4|
|OS|Linux x64 4.15.0-161-generic|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 897)|
|Memory (System)|7.68GB (0.63GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-drawio|hed|1.6.4
better-cpp-syntax|jef|1.15.10
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.66.1
remote-wsl|ms-|0.58.5
devicetree|plo|0.1.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30440023
pythonvspyt640:30450904
vscscmwlcmc:30438804
vscgsvid1:30447480
cppdebug:30451566
pynewfile477:30450038

```

</details>

**Comment by roblourens** [comment]
You are on a pretty old version of the Remote-SSH extension. Please update it.
