### ISSUE TITLE
Prompt before revealResourcesInOS on many resources

### ISSUE THREAD

**Issue by ava3a13** [microsoft/vscode#144899]
I have had selected my entire solution with `CTRL+A`. After that, having another window open to the side, seeing that I had assets folder selected (Meaning in the second window) I tried to open resource in explorer with a standard key binding `ALT+SHIFT+R`. So what basically happened is that explorer glitched out trying to open 60+ folders.
Thinking about it, maybe no one wants to open that amount of folders at the same time and/or modal, like one present on `workspace.contribution.ts` `doShowModal()` provides, maybe helpful.
`fileCommands.ts` already checks for the `resources.length`:

```
	if (resources.length) {
		sequence(resources.map(r => async () => {
			if (r.scheme === Schemas.file || r.scheme === Schemas.userData) {
				nativeHostService.showItemInFolder(r.fsPath);
			}
		}));
	}

```

**Comment by JacksonKearl** [comment]
To be clear, you're saying that you'd like a modal confirming before opening a large number of files via `revealResourcesInOS`?

**Comment by ava3a13** [comment]
> To be clear, you're saying that you'd like a modal confirming before opening a large number of files via `revealResourcesInOS`?
Modal, alert, anything that needs user confirmation would be helpful to prevent such accidents.
