### ISSUE TITLE
Add setting to control the state of "toggle search details" after reload/reboot

### ISSUE THREAD

**Issue by ppggff** [microsoft/vscode#144808]
Current version: Keep the state before reload, always expand if non-default values exist

When using it, I often need to keep some non-default settings for a long time, and every time I reload (after update extension), I need to turn it off manually, which is very troublesome. Expect to add setting as:

* Auto: same as current version
* Always expand
* Always close
* Keep the state before reboot/reload

**Comment by JacksonKearl** [comment]
IMO this has too much potential to get people stuck in states where they do not know search include/excludes are being applied. I believe this is why the auto-expanding on reload feature was added in the first place.

cc @roblourens

**Comment by ppggff** [comment]
@JacksonKearl Why? there is a default option that nothing changed. Users who really need this feature will never stuck in "where they do not know search include/excludes are being applied" states.

**Comment by JacksonKearl** [comment]
It's easy to enable a setting once and forget, then get stuck in nasty situations in the future. There is the `workbench.action.search.toggleQueryDetails` command for a faster way to expand the section, it's bound to Cmd+Shift+J by default.

**Comment by ppggff** [comment]
@JacksonKearl 'Cmd+Shift+J' only work in search panel (with focus on it), not a real solution. And press a command every time after reloading vscode is not a good solution.

Consider the following scenario:
* Use vscode with the project root
* Search always (most time) only in 'root/src', so 'files to include' is set

Then, after updating an extension, restart computer, user must click the 'toggle search details' button to save the screen space.

> It's easy to enable a setting once and forget, then get stuck in nasty situations in the future.
This should be another problem, maybe put a hint some where? For example:
* Display a hit text in the search box (addition to 'Search (↑↓ for history)')
* Show some summary information with the search result, this should be helpful, really

Thanks, this is really a problem I encounter every day, very troubling.

**Comment by ppggff** [comment]
for user who want a simple fix:
```
sed -i _bak -e 's/&&this.toggleQueryDetails(!0,!0,!0),/\&\&0\&\&this.toggleQueryDetails(!0,!0,!0),/' "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js"
```

`workbench.desktop.main.js_bak` is a backup.

ignore the warning message after restart.
