### ISSUE TITLE
[feature] Quote selected text

### ISSUE THREAD

**Issue by brendandixon** [Microsoft/vscode#14484]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 16.0.0
- Extensions: DotJoshJohnson.xml-1.6.0, Shan.code-settings-sync-2.3.3, donjayamanne.python-0.5.0, groksrc.haml-0.0.2, lukehoban.Go-0.6.45, ms-vscode.csharp-1.4.1, rebornix.Ruby-0.10.1

Steps to Reproduce:

1. Select text
2. Type ", ', or any other bounding character
3. Text is replaced

SublimeText (and other editors) wrap the selected text with quote or such character (both single and double quotes).

**Comment by joaomoreno** [comment]
This feature is only active in some modes, since there are modes in which it would't make sense.

It works for JavaScript, TypeScript, C#, etc...

What mode are you trying it on?

**Comment by brendandixon** [comment]
@joaomoreno It most definitely *does not* work in C# mode. Is it possibly a recent regression?

**Comment by joaomoreno** [comment]
Oh yeah... looks like one, can you file an issue on https://github.com/OmniSharp/omnisharp-vscode/issues?

**Comment by wprater** [comment]
does not work on Plain Text module either

**Comment by joaomoreno** [comment]
@wprater Plain Text isn't a mode in which it makes sense to have this.

**Comment by wprater** [comment]
alright. I'm just used to it from another editor. no worries!

**Comment by marcelombc** [comment]
This doesn't work with Mac US International - PC keyboard.
In Atom works with ' + space

**Comment by grahamb** [comment]
@joaomoreno I'm curious why you say that this doesn't make sense in plain-text mode? Atom and Sublime both support this in plain text. I often use this feature in Atom as a sort of scratch-pad (e.g. for quoting a bunch of lines of text all at once).

![untitled](https://user-images.githubusercontent.com/146111/29348795-fd162c4a-820a-11e7-8af0-e79b6fe087dc.gif)

**Comment by joaomoreno** [comment]
@grahamb Created #32616
