### ISSUE TITLE
PUSH OR PULL do not work via GIT PLUGIN, IF REPO IS CLONED VIA SSH

### ISSUE THREAD

**Issue by omonimus1** [microsoft/vscode#144859]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version: Mac 

Steps to Reproduce:

1. CLONE A repo (via ssh)
2. make any change 
3. stage file via official git plugin
4. try to push (this is where you will see the error).

It gives error:
> git push origin omonimus1/feature/#6-adds-unit-test-email:omonimus1/feature/#6-adds-unit-test-email
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by ag-eitilt** [comment]
I have this same issue (VS Code 1.66.1, Windows 10); it seems like the git plugin doesn't provide any support for password-protected SSH keys.  Previous closed answers suggest using credentials managers, but I'm connecting to my repo through the Remote Explorer, and while a credential manager setup is indeed a quality-of-life improvement I could look into (I'm still typing my password into the terminal pane every time I manually `git push`), I feel like the plugin should still probably have at least backup support for cases where starting that manager is a bit more complex than going through the options of a local Git For Windows install.

**Comment by Doc94** [comment]
i have the same issue and only with VSCode.. if use git things in console or another software all works fine.
