### ISSUE TITLE
Terminal Content Dissapearing

### ISSUE THREAD

**Issue by studentdevelops** [microsoft/vscode#144875]
Issue Type: <b>Bug</b>

Hello there,

I am using VScode for web development at the moment when i encountered this bug, to be specific NextJS.
After running the command npm run dev the terminals shows the output etc but once i alt tab check the output on chrome then alt tab back the terminal is empty and the cursor is in the middle with no text at all, It happened after installing the recent update on vscode. To get them to appear again I usally terminate the task using ctrl c it asks for terminate batch i do yes and start the npm server again.

Thanks for looking into it and have a nice day

VS Code version: Code 1.65.1 (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:06:27.846Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-sqlite|ale|0.14.0
bracket-pair-colorizer|Coe|1.0.62
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|9.3.0
auto-rename-tag|for|0.1.10
icon-fonts|idl|2.5.3
vscode-peacock|joh|4.0.0
auto-save|mcr|1.0.3
fluent-icons|mig|0.0.17
test-adapter-converter|ms-|0.1.5
vscode-typescript-next|ms-|4.7.20220310
vsliveshare|ms-|1.0.5418
material-icon-theme|PKi|4.14.1
vscode-xml|red|0.19.1
LiveServer|rit|5.7.5
code-spell-checker|str|2.1.7
vscodeintellicode|Vis|1.2.17
vscode-icons|vsc|11.10.0
quokka-vscode|Wal|1.0.450
bracket-lens|wra|1.5.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30440023
pythonvspyt640:30450904
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvidc:30447482
helix:30440343
pynewfile477cf:30450039

```

</details>

**Comment by studentdevelops** [comment]
![image](https://user-images.githubusercontent.com/31382363/157796024-5a3e8c25-6697-4fb5-9541-4c567fa2b47c.png)
All of it just gone

**Comment by meganrogge** [comment]
when this happens, can you toggle escape sequence logging and provide those?

**Comment by studentdevelops** [comment]
Can u share how to do that?

**Comment by meganrogge** [comment]
Yes Ctrl shift p -> toggle escape sequence logging -> repro the issue -> copy and paste the logs
