### ISSUE TITLE
Check diff of last commit

### ISSUE THREAD

**Issue by madprops** [microsoft/vscode#144878]
Something I need often, is to know for sure if the thing I just pushed is correct. So what I do is go to the github repo and click the commit id to see the diff. This can take several seconds to load. Would it be possible to have vscode show the diff of the last commit, like what I could get with `git diff HEAD^ HEAD` (but better) ?

**Comment by lszomoru** [comment]
You have couple of options to check the diff of the last commit even without pushing your changes to GitHub:
1. Timeline - In the `Explorer` viewlet there is a `Timeline` view which will display the history of the file that is currently active in the editor. Clicking on the top most item in the `Timeline` view will open the diff editor. 
2. GitLens - If you install the `GitLens` extension, you will get a `Commits` view in the `Source Control` viewlet, which will display the list of commits for the git repository. You can use the information in the `Commits` view to see the file in each commit, and clicking on the file will open the diff editor.

**Comment by madprops** [comment]
Didn't know about Timelines :o

I see I can check individual files, but can I check all the file diffs from a certain commit, without going to each file?

**Comment by lszomoru** [comment]
You can see all the files in the commit using the `Commits` view provided by the GitLens extension.
