### ISSUE TITLE
Reports as crashed after updaing

### ISSUE THREAD

**Issue by hasen6** [microsoft/vscode#144871]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: Recent previous few versions..
- OS Version: MacOS High Sierra 10.13.6

Steps to Reproduce:

1. Select 'Restart to update'
2. After successfully updating, Vscode displays an error message saying it crashed last time and did I want to report the error.

A minor issue, doesn't really affect anything but I thought it would be better to let you know anyway. It's happened the last 2-3 times after updating but never happened before that. I'm now using 165.2 after updating.

**Comment by joaomoreno** [comment]
Any additional details on that prompt to report?

**Comment by hasen6** [comment]
> Any additional details on that prompt to report?

I don't know, like what? It's rather a simple thing, it just updates and then reports that it crashed, what else might there be?

**Comment by joaomoreno** [comment]
A screenshot would be helpful. Or a literal transcription of what the message actually says.

**Comment by hasen6** [comment]
> A screenshot would be helpful. Or a literal transcription of what the message actually says. If you need help please give more info about the problem you need help with.

Well I can't really update with any new information until I update it again. It's surely the default message for when VSCode crashed accidentally last time? I'd imagine you'd have access to that in the source code which I don't have access to.

**Comment by joaomoreno** [comment]
OK, let me know once it happens again.
