### ISSUE TITLE
localhost

### ISSUE THREAD

**Issue by gogpg** [microsoft/vscode#144863]
Hello,
I'm learning html+css.
All the time I was executing the code by F5.
And one day it changed: after I press F5 or cntrl+F5 I get blank window with the adrress: 
http://localhost:8080

I cheked the file launch.jason, and there is a line:
"url": "http://localhost:8080"

I don't know how it appeared.
How I can fix this problem?
I want to be able to execute my html files.

**Comment by weinand** [comment]
@gogpg what's in your "launch.json"?
Please show the full launch config.
