### ISSUE TITLE
Improve how snippets use suggest for choice elements

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#144839]
Today snippets use the only once suggest provider for choice picks. This isn't ideal and has debt. Instead, the snippet session should register a short-lived completion provider that's aware of the current snippet and its state. It can than repeatedly suggest choice elements

**Comment by stfujnkk** [comment]
I seem to have the same problem as you.

I did a test. There is no drop-down menu.

```json
{
    "test": {
		"prefix": "test",
		"body": "${1|one,two,three|}"
	}
}
```
