### ISSUE TITLE
Enable Bracket Pair Colorization By Default

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#144820]
We want to explore enabling bracket pair colorization by default and gather some feedback.
For now, we will just enable it for Insiders. If only a neglectable amount of users complain (they can still turn it off) while the majority likes the feature, we will roll it out for stable.

FYI @alexdima @egamma

**Comment by Tyriar** [comment]
Count me as one of the complaining users. I've disabled it so the problem's fixed for me, my gut feeling is that most users wouldn't want this but could be wrong.

**Comment by davidjaldred** [comment]
I remember seeing bracket pair colorization a few months back. I assume it was enabled by default when it was introduced natively and then changed to an 'opt-in' setting... unfortunately I'd forgotten all about it.

Very happy to see it again. Fully in support of it being enabled by default.

**Comment by therealgilles** [comment]
Not a big fan myself. It would be great if there was clear documentation on how to disable this new colorization scheme, thank you :)
