### ISSUE TITLE
Right-click in terminal no longer scrolls to bottom

### ISSUE THREAD

**Issue by maverickfalcon** [microsoft/vscode#144854]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.0
- OS Version: Windows 10

Steps to Reproduce:

1. Install latest version of VS code
2. Right click in Terminal using cmd
3. No longer scrolls to bottom of terminal

Please get this working again!!!

**Comment by meganrogge** [comment]
I don't believe it ever worked like that?
<img width="451" alt="Screen Shot 2022-03-11 at 12 44 17 AM" src="https://user-images.githubusercontent.com/29464607/157809489-b734e9cc-45e7-4543-a528-eb6ac795fdb7.png">
