### ISSUE TITLE
Unexpected markdown preview effect

### ISSUE THREAD

**Issue by fuxichen** [microsoft/vscode#144811]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.1
- OS Version: windows11

Steps to Reproduce:

1. Bold the text
```markdown
**test**test

**test** test

**.** test

**.**test
```
![image](https://user-images.githubusercontent.com/17411462/157601824-c4ae808d-ddc1-4d7d-a201-19f5d5364e83.png)

**Comment by Lemmingh** [comment]
<https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis>

This exactly reflects how CommonMark defines "delimiter run".

**Comment by Lemmingh** [comment]
> A **right-flanking delimiter run** is a delimiter run that is
> (1) not preceded by Unicode whitespace,
> **and**
> (2b) preceded by a Unicode **punctuation** character and followed by Unicode **whitespace** or a Unicode **punctuation** character.

Thus, this is indeed **expected** behavior.

**Comment by fuxichen** [comment]
> > A **right-flanking delimiter run** is a delimiter run that is
> > (1) not preceded by Unicode whitespace,
> > **and**
> > (2b) preceded by a Unicode **punctuation** character and followed by Unicode **whitespace** or a Unicode **punctuation** character.
> 
> Thus, this is indeed **expected** behavior.

Thank you
