### ISSUE TITLE
error eslint tips in .vue file, Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add 'node' to the types field in your tsconfig.ts(2591)

### ISSUE THREAD

**Issue by WormGirl** [microsoft/vscode#144809]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.I confirm add this package, and add it to tsconfig  types field,  and restart the vscode.
2.this error just in edit,  cmd never show this error.
![image](https://user-images.githubusercontent.com/16078260/157601876-bd2f468b-4fa6-4764-9bff-859c0e4d959e.png)
![image](https://user-images.githubusercontent.com/16078260/157601947-66ee0db4-6878-4fb6-b896-a99bdf3bdbcc.png)

**Comment by mjbvz** [comment]
Please file this against your Vue extension
