### ISSUE TITLE
Control-clicking url in launch.json does bring Edge browser to foreground

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#14487]
Testing https://github.com/Microsoft/vscode/issues/13585:

- VSCode Version: 1.7.0
- OS Version: Win 10

Control-clicking on the url in the launch.json does not open the file in MS Edge but just makes the Edge icon blink in the Windows start bar.

I'm not sure that this is the desired behaviour: since I did not spot the blinking icon I thought that the feature is broken.

If I run the 'View license' action from the VS Code Help menu, the license file opens directly. So there must be a better way to open an url in the browser.

**Comment by isidorn** [comment]
This is just how we open urls from the workbench on win. Forwarding to @bpasero

**Comment by bpasero** [comment]
Nothing that is under our control...

**Comment by weinand** [comment]
The (changed) title of this issue now says the opposite of my original complaint.
The problem I am seeing is that control-clicking an url in launch.json does *not* bring Edge to foreground but makes Edge's icon blink in the task bar.
In contrast to that the 'View license' action from the VS Code Help menu works as expected.
@bpasero you are saying that it is 'not under our control' to get the same behaviour for control clicking a URL as for the 'View license' action?

**Comment by bpasero** [comment]
@weinand yes, the difference is that from the menu we open the URL from our main process which is the foreground process on Windows and is allowed to bring other processes to the front. Opening a URL from the renderer process for Windows looks like a background process trying to bring another Window to the front and it prevents it.

I guess we could probably fix this by forcing all URLs to open from the main process, so that might be a workaround.

**Comment by bpasero** [comment]
More info on this topic: https://blogs.msdn.microsoft.com/oldnewthing/20090220-00/?p=19083

**Comment by bpasero** [comment]
October to investigate, if we can fix this by doing business on the main thread we should do it.
Also applies to: reveal in explorer

**Comment by bpasero** [comment]
Verifier: please test on all OS that links open outside VS Code when clicked from the editor and that the browser is in the foreground properly.

**Comment by weinand** [comment]
Verified for Windows 10, macOS, and linux.

**Comment by bpasero** [comment]
@weinand thanks (also for pushing me to think about it again)
