### ISSUE TITLE
Remove `ComplexNotebookEditorModel` and friends

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#144810]
If not used anymore.

**Comment by bpasero** [comment]
Friendly ping, my understanding is we still carry around old notebook code pre-working-copy times? Why not get rid?

//cc @jrieken

**Comment by jrieken** [comment]
I believe LS is still on the old API but they are inching away from it.

**Comment by rebornix** [comment]
@mjbvz this is what's used by the notebook content provider, once LS moves off the API, we can also remove this.

**Comment by kieferrm** [comment]
This is blocked by https://github.com/microsoft/vscode/issues/147248

**Comment by jrieken** [comment]
This can finally happen 👯

**Comment by mjbvz** [comment]
Still blocked on #163377

**Comment by jrieken** [comment]
🥳
