### ISSUE TITLE
Icon request for local history entry

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#144823]
I am exploring to add entries to the "Timeline" view from saving files (= local history). This requires to use an icon to tell apart from SCM entries:

![image](https://user-images.githubusercontent.com/900690/157634121-945f1ed9-e4db-4456-8317-4adbbc450408.png)

I am happy to use an existing icon or a new one, filing this issue to discuss.

**Comment by bpasero** [comment]
Some ideas:

`Codicon.file`

![image](https://user-images.githubusercontent.com/900690/157640805-dfdb3064-d48d-46c5-b7b8-e4058ecdbfb7.png)

`Codicon.history`

![image](https://user-images.githubusercontent.com/900690/157640892-49f467ca-1cba-488c-9313-d5ed728cc470.png)

`Codicon.versions`

![image](https://user-images.githubusercontent.com/900690/157641402-a8749fcb-b811-4683-a33d-a4c3a0f0507c.png)

**Comment by daviddossett** [comment]
I like `history` since it represents an idea of time. But it also feels like it references a list of events, not a specific event. `file` could work. Here are some other options from our existing icons. This shows them as indented too just to give an example of the idea above.

`save`
<img width="451" alt="CleanShot 2022-03-10 at 09 03 45@2x" src="https://user-images.githubusercontent.com/25163139/157716340-09eeebb9-2ed0-4179-835f-54439e413974.png">

`check`
<img width="448" alt="CleanShot 2022-03-10 at 09 03 59@2x" src="https://user-images.githubusercontent.com/25163139/157716469-68eea4d8-b3f7-4796-a59c-d6db88222e8c.png">

**Comment by bpasero** [comment]
> I also wonder if they should be children of the "Uncommitted Changes" entry?

That is not possible with how the API works: "Uncommitted changes" originates from the Git extension, "Local history" originates from the core workbench.

> save icon

I like the save icon, because that is the event that triggers the addition of a new local history entry: every save of a file.

>  we know what other types of entries will appear here for local history entries?

The trigger is saving but I was planning to add support to provide a label for the circumstances: for example a file might be saved by the user typing in the editor but also via refactoring. Would be nice to tell apart the one from the other to see a nice history of what actually happened to the file. but I would probably not show a different icon, just a different label.

**Comment by daviddossett** [comment]
> That is not possible with how the API works: "Uncommitted changes" originates from the Git extension, "Local history" originates from the core workbench.

Ah ok, I misunderstood. Got it.

**Comment by bpasero** [comment]
Btw even more interesting: entries from Git are mixed with entries from Local history, so grouping them under "Uncommitted changes" is not really telling the truth. It is 2 distinct sources of timeline entries, you can have 5 Git entries, followed by 5 local history entries, followed by 5 git entries and so on.

**Comment by daviddossett** [comment]
Makes sense. I think the save icon probably is the most truthful then. The file with the nested +/- icons could also work but may be a little bit too close to git concepts like a diff.

**Comment by bpasero** [comment]
Will go with the save icon.

**Comment by bpasero** [comment]
From the UX call feedback was that the save icon looks like 1980. And in reality we have more sources of history events than the user hitting save (e.g. refactorings, search and replace).

Maybe a more generic icon after all should be used then?

Reopening to consider that.

//cc @isidorn

**Comment by bpasero** [comment]
Yeah works really well imho:

![image](https://user-images.githubusercontent.com/900690/158667896-06856846-291b-47a4-a1fb-eeaa1fa4d023.png)

**Comment by bpasero** [comment]
Btw I am not yet sure we can get to the solution where local history entries appear as a tree node with children, at least not in the first iteration. If I can somehow get the "Load more..." thing to behave like I want for my items, it would be very similar, the entries would simply appear at the place you clicked.

**Comment by daviddossett** [comment]
Would they appear below the commits? I didn't quite follow that bit when we were talking through it earlier.

**Comment by bpasero** [comment]
@daviddossett here is a complete end to end with the label and icon changes including timeline and editor:
![Recording 2022-03-16 at 21 06 42](https://user-images.githubusercontent.com/900690/158681065-9c59d12c-6137-4b99-8d56-03f1a18011f7.gif)

> Would they appear below the commits? I didn't quite follow that bit when we were talking through it earlier

I think so, yeah. basically you see a placeholder for a group (1-many) of local history entries anywhere in the timeline where multiple entries of the local history appear. And when you click that item, it would go away and resolve the local history entries, similar how "Load more..." loads more items to the list.

That said, agree it is not such a nice model, because you can also not go back. Having a way to expand/collapse might be the way to go, will see. UI wise that is probably the better solution, but need to see it in action first.

**Comment by isidorn** [comment]
Looks good and modern!

Nit: can we use a longer vertical line for the Git icon so they look a bit more connected and easily distinguishable from the new saved icon?

**Comment by bpasero** [comment]
Nevertheless, I really like that both icons look somewhat similar in a way, because that conveys the information that each entry is a change to the file. Just the kind of change is different, or rather: the source 👍

**Comment by daviddossett** [comment]
> here is a complete end to end with the label and icon changes including timeline and editor:

Looking good! 

> I think so, yeah. basically you see a placeholder for a group (1-many) of local history entries anywhere in the timeline where multiple entries of the local history appear. And when you click that item, it would go away and resolve the local history entries, similar how "Load more..." loads more items to the list.

I see. I probably wouldn't have expected the behavior before clicking on it. I think a tree would make more sense if it's possible.
