### ISSUE TITLE
Intellisense for 'configurationNames' in a composite launch config?

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14481]
Is this possible? Would be cool to have autocomplete for the launch config names.

**Comment by isidorn** [comment]
Might add that once we decide how we want to surface multile debug sessions in november

**Comment by isidorn** [comment]
We have chosen not to ship this feature yet. We will provide more details about the reasoning behind this in #14842

For now we will only ship with the manual click on play button multiple times approach.
