### ISSUE TITLE
Intellisense is slow and TypeScript crashes frequently

### ISSUE THREAD

**Issue by hedzerkoolstra** [microsoft/vscode#144828]
Since a few days Intellisense is very slow, going to (type) definition is stuck in pending and I get an error  that TypeScript is crashing multiple times in 5 minutes. 

I tried disabling all extensions which fixes the issue for a few minutes but than I get the same slow behavior again. Any ideas what can cause this?

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please share repo with reproduction if possible or follow steps from https://github.com/microsoft/vscode/issues/144711#issuecomment-1062427507 and also pay attention to note in that comment.

**Comment by hedzerkoolstra** [comment]
Thanks for the reply. It's very random and it happens in multiple repo's so it's hard to determine reproduction steps. I was hoping this would be a known bug from the new update. I'll try and gather more information and if I can't solve it I'll open a new issue according to your guidelines. You can close this one. Thanks!
