### ISSUE TITLE
separated code navigation history for split editor views

### ISSUE THREAD

**Issue by walidbarakat** [microsoft/vscode#144860]
when i'm working on different files - specially heavy code review tasks - i prefer for use split editor views as grouping of the files, but sometimes it's annoying to navigate back and forth and find my self jumping from view ( group ) to another, can we have such feature to enable flexibility?

**Comment by bpasero** [comment]
Like https://code.visualstudio.com/updates/v1_65#_new-editor-history-navigation ?

**Comment by walidbarakat** [comment]
Hi, thanks for pointing out this update, it's what i needed.
