### ISSUE TITLE
An error occurred during software account synchronization. Procedure

### ISSUE THREAD

**Issue by nyhxiaoning** [microsoft/vscode#144884]
I changed my Microsoft email account, and the result is that vscode always prompts the following every time I open it
You have been deregistered because stored authentication information could not be read.

![Snipaste_2022-03-11_10-22-50](https://user-images.githubusercontent.com/34833782/157815465-811fc403-7412-4a59-ad75-39e90de295eb.jpg)
![Snipaste_2022-03-11_10-22-59](https://user-images.githubusercontent.com/34833782/157815478-18227f97-0939-4a00-9eee-370d28700ea7.jpg)

**Comment by TylerLeonhardt** [comment]
/duplicate https://github.com/microsoft/vscode/issues/145189

(It has slightly more information)
