### ISSUE TITLE
consider to generate paths with forward slashes only

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#14489]
Testing https://github.com/Microsoft/vscode/issues/13585:
- VSCode Version: 1.7.0
- OS Version: Win 10

Since the node ecosystem (and the glob patterns of the `outFiles` attributes) use forward slashes, we should consider to generate only forward slashes.

**Comment by weinand** [comment]
The fix does the opposite of what I was suggesting: it creates back slashes on windows.

**Comment by isidorn** [comment]
Reverted commit

**Comment by sandy081** [comment]
@isidorn Looks like this is reverted and verification found is still on. what needs to be verified here?

**Comment by weinand** [comment]
On all platforms the generated `program` path should only use forward slashes '/' because that's what the node ecosystem (and the glob patterns of the outFiles attributes) accepts.

**Comment by sandy081** [comment]
@weinand This is what I see in Windows 10 for `program` attribute. It has back slashes `\`,

![image](https://cloud.githubusercontent.com/assets/10746682/21008846/da5dbca4-bd43-11e6-9293-9904a55f1d4f.png)

**Comment by isidorn** [comment]
@weinand did we update the node debug in vscode since I reverted this commit? If yes then it seems like my revert fix is not working since Sandeep is getting wrong slashes

**Comment by weinand** [comment]
@isidorn I didn't update node-debug yesterday. But I did today. So this can be verified with tomorrows Insiders.

**Comment by ramya-rao-a** [comment]
I still see backslashes in Windows. 
Re-opening and moving to next milestone as this is not critical for the current milestone

**Comment by weinand** [comment]
This works fine in the latest Insiders.
