### ISSUE TITLE
Anaconda cannot be connected to the bottom, and it is difficult for Python to switch the environment

### ISSUE THREAD

**Issue by monkeycc** [microsoft/vscode#144870]
Issue Type: <b>Bug</b>

Anaconda cannot be connected to the bottom, and it is difficult for Python to switch the environment

This problem occurred after upgrading the version

VS Code version: Code 1.65.1 (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:06:27.846Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (7.01GB free)|
|Process Argv|F:\\1

.py --crash-reporter-id e8095d80-4b16-4d5d-adca-2402a7b74008|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
xml|Dot|2.5.1
go|gol|0.32.0
ipython|Hoa|2021.10.17
better-cpp-syntax|jef|1.15.13
conda-cheatsheet|joj|1.2.7
vscode-language-pack-zh-hans|MS-|1.65.2
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.1
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
vscode-qt-for-python|sea|1.1.7
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30440023
pythonvspyt640:30450904
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvid2:30447481
helix:30440343
pynewfile477cf:30450039

```

</details>

<img width="1918" alt="微信截图_20220311092156" src="https://user-images.githubusercontent.com/6490927/157783525-e6b677f2-efa3-481e-9e81-9c819398f182.png">

**Comment by Lemmingh** [comment]
/extPython

I can't make heads or tails of your words. But you might be interested in the recent changes of the Python extension:

* <https://github.com/microsoft/vscode-python/issues/18040>
* <https://github.com/microsoft/vscode-python/issues/18283>

**Comment by monkeycc** [comment]
I need to switch the python version

Unfortunately, you cannot change the python version in the status bar
