### ISSUE TITLE
do not suggest attribute 'configurationNames' outside of 'composite' launch config 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#14486]
Testing https://github.com/Microsoft/vscode/issues/13585:
- VSCode Version: 1.7.0
- OS Version: Win 10

Content assist suggests attribute 'configurationNames' for node debug type.

**Comment by isidorn** [comment]
Simlar as all other launch.json bugs I got. Will not polish this experience in october since we might decide to change it completely. Assignign to november since then we will definetly decide how we want to surface this

**Comment by isidorn** [comment]
Fixed on branch `isidorn/compound` - however we have chosen not to ship this feature yet. We will provide more details about the reasoning behind this in #14842

For now we will only ship with the manual click on play button multiple times approach.
