### ISSUE TITLE
VSCode can't find header files (happens randomly)

### ISSUE THREAD

**Issue by Samega7Cattac** [microsoft/vscode#144830]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.1
- OS Version: Linux x64 5.16.13-arch1-1

Steps to Reproduce:

1. Have a C++ project that require some edits to include path
2. Watch VSCode randomly struggle to find the header files and keeps asking to add the same include path over and over

**Comment by Samega7Cattac** [comment]
In my c_cpp_properties I have some WIn32 and Linux specific configs (and this should be no problem since when I "quick fix" it adds the path to the correct configuration) and I also use environment variables 
An Example:
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${env:SystemDrive}/path_to_somewhere/include",
                ... (more struff)
                "${env:MYPROJECT_INSTALL_PATH}/include",
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "${env:SystemDrive}\\msys64\\mingw64\\bin\\gcc.exe",
            "cStandard": "gnu17",
            "cppStandard": "gnu++20",
            "intelliSenseMode": "windows-gcc-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        },
        {
            "name": "Linux",
            "includePath": [
                "${env:MYPROJECT_INSTALL_PATH}include/",
                "${env:MYPROJECT_INSTALL_PATH}include/lib1",
                "${env:MYPROJECT_INSTALL_PATH}include/lib2",
                "${workspaceFolder}/**",
                "/usr/include/some_stuff/",
                "/usr/lib/some_stuff/include",
                "/same_path_has_MYPROJECT_INSTALL_PATH/include/lib1"
            ],
            "cStandard": "gnu17",
            "cppStandard": "gnu++20",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```
For example I'm edition something on LInux that require the "lib1" headers, it keeps asking to add `"/same_path_has_MYPROJECT_INSTALL_PATH/include/lib1"` to the include path, over and over.
This happens on random files and with random libs on this project. But when i compile the errors go away and sometimes they come back later.

**Comment by Samega7Cattac** [comment]
This seems to make the intellsense unusable, slow, not responding to input or straight crashes

**Comment by IllusionMH** [comment]
/extCpp

These features are provided by cpp extension and should be reported there first.
