### ISSUE TITLE
Save input box on a remote window has weird suggestion for file name when closing an untitled file

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode#144822]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0
- OS Version: Windows 11 Enterprise

Steps to Reproduce:

1. On a remote window, create an untitled file and paste these contents. `$schema: https://azuremlschemas.azureedge.net/latest/azureDataLakeGen1.schema.json`
![image](https://user-images.githubusercontent.com/44413557/157633317-fcb0f94b-90ea-4de7-9943-d45816032145.png)
2. Close this untitled file, a save prompt (modal) will appear. Click Save button. You will see something like this:
![image](https://user-images.githubusercontent.com/44413557/157633739-ded8cf18-bc21-43d2-9718-9affa3ad819d.png)
3. The suggested file name is **$schema: https:/azuremlschemas.azureedg.yml** and only **azuremlschemas.azureedg** is highlighted and not the whole file name which was suggested

This works fine on a local window as the suggested file name is **azuremlschemas.azureedg:** as shown below:
![image](https://user-images.githubusercontent.com/44413557/157634289-75a62969-2f05-48f6-a655-cb60076622f6.png)

**Comment by bpasero** [comment]
For untitled files, the first line is used as file name. I am not sure why there would be any difference between the simple and native dialog but I actually think the simple one behaves correctly here, though there seems to be mentioned highlighting issue.

**Comment by shsuman** [comment]
@bpasero  I think our main concern is the highlight, for the name we would ideally like to have custom inputs from the extension but that is a completely different discussion.

**Comment by alexr00** [comment]
All the simple file dialog knows is that there is a default save URI given to it. The highlight is done by using the basename of that default URI. 

I took a look at where the default save URI comes from, and it looks like `hasValidBasename` suffers from the same issue of using the basename that simple file dialog does: 

https://github.com/microsoft/vscode/blob/bf1c9e93913714c85b0db6f2e2690b0bddbab7e4/src/vs/workbench/services/textfile/browser/textFileService.ts#L579-L580

The best fix seems to be to fix the default save URI. PR incoming.
