### ISSUE TITLE
Shell Integration: enabled problem with $PROMPT_COMMAND (bash)

### ISSUE THREAD

**Issue by gullevek** [microsoft/vscode#144804]
Issue Type: <b>Bug</b>

My normal bash PROMPT_COMMAND:

$ echo $PROMPT_COMMAND;
setLastCommandState;history -a; history -c; history -r; echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007";setGitPrompt

If I enable Shell Integration and start a new shell:
$ echo $PROMPT_COMMAND;
prompt_cmd_original
bash: setLastCommandState;history: command not found

before each call I get:
bash: setLastCommandState;history: command not found

It seems the first part of the PROMPT COMMAND "setLastCommandState;history -a" has a space in there and that cuts it off wrong it seems

VS Code version: Code 1.65.1 (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:20:11.670Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.0-11-cloud-amd64
Remote OS version: Linux x64 5.10.0-11-cloud-amd64
Remote OS version: Linux x64 5.10.0-11-cloud-amd64
Remote OS version: Linux x64 5.10.0-11-cloud-amd64
Remote OS version: Linux x64 5.10.0-11-cloud-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|-psn_0_6481454 --crash-reporter-id 4284444f-7b66-4290-a251-d91b7ba6d909|
|Screen Reader|no|
|VM|13%|

|Item|Value|
|---|---|
|Remote|SSH: soba-dev|
|OS|Linux x64 5.10.0-11-cloud-amd64|
|CPUs|AMD EPYC 7571 (4 x 2199)|
|Memory (System)|15.50GB (6.96GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: soba|
|OS|Linux x64 5.10.0-11-cloud-amd64|
|CPUs|AMD EPYC 7571 (4 x 2199)|
|Memory (System)|15.50GB (6.96GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: soba|
|OS|Linux x64 5.10.0-11-cloud-amd64|
|CPUs|AMD EPYC 7571 (4 x 2199)|
|Memory (System)|15.50GB (6.96GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: soba-dev|
|OS|Linux x64 5.10.0-11-cloud-amd64|
|CPUs|AMD EPYC 7571 (4 x 2199)|
|Memory (System)|15.50GB (6.96GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: soba|
|OS|Linux x64 5.10.0-11-cloud-amd64|
|CPUs|AMD EPYC 7571 (4 x 2199)|
|Memory (System)|15.50GB (6.96GB free)|
|VM|0%|
</details><details><summary>Extensions (76)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.4
vscode-rust-syntax|dun|0.0.32
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
remotehub|Git|0.26.0
gitkraken-authentication|git|1.0.3
smarty|imp|0.3.0
better-perl-syntax|jef|1.0.14
vscode-peacock|joh|4.0.0
latte|Kas|0.18.0
vscode-apache|mrm|1.2.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
php-docblocker|nei|2.7.0
svg-preview|Sim|2.8.3
errorlens|use|3.4.2
highlight-matching-tag|vin|0.10.1
vscode-icons|vsc|11.10.0
gistfs|vsl|0.3.0
material-theme|zhu|3.13.20
Bookmarks|ale|13.2.4
vscode-intelephense-client|bme|1.8.2
better-toml|bun|0.3.2
vscode-perl|cfg|1.18.0
vscode-svgviewer|css|2.0.0
jshint|dba|0.11.0
vscode-eslint|dba|2.2.2
vscode-quick-select|dba|0.2.9
githistory|don|0.6.19
gitlens|eam|12.0.2
vscode-npm-script|eg2|0.3.24
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
gitkraken-authentication|git|1.0.3
todo-tree|Gru|0.0.215
vscode-perl|hen|1.17.0
phpcs|ika|1.0.5
vscode-edit-csv|jan|0.6.6
svg|joc|1.4.17
bash-ide-vscode|mad|1.12.1
rust-analyzer|mat|0.2.964
rainbow-csv|mec|2.0.0
git-graph|mhu|1.30.0
vscode-filesize|mkx|3.1.0
vscode-duplicate|mrm|1.2.1
language-gettext|mro|0.2.0
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.1
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
hexeditor|ms-|1.9.5
vscode-typescript-tslint-plugin|ms-|1.3.3
sqltools|mtx|0.23.0
sqltools-driver-mysql|mtx|0.2.0
sqltools-driver-pg|mtx|0.2.0
color-highlight|nau|2.5.0
php-docblocker|nei|2.7.0
autodocstring|njp|0.6.1
indent-rainbow|ode|8.2.2
phpdoc-comment-vscode-plugin|rex|1.3.0
perl|ric|2.3.0
rust|rus|0.7.8
trailing-spaces|sha|0.3.1
vscodeintellicode|Vis|1.2.17
php-debug|xde|1.25.0
php-pack|xde|1.0.3
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.20.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrc:30448490
dsvsc008:30440022
pythonvsnew555:30450902
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343
vscaac:30438847
pynewfile477cf:30450039

```

</details>

**Comment by Tyriar** [comment]
I believe this is fixed now
