### ISSUE TITLE
README.md no longer shows embedded Base64 images and anchor links inside extensions

### ISSUE THREAD

**Issue by s4mu313** [microsoft/vscode#144897]
Issue Type: <b>Bug</b>

- From the VSCode version 1.64.2, the README.md of an extension is no longer showing images if they are encoded in Base64 inside the README.md.
- Also anchor links are broken from that version. They are recognized as links but it's like the "onclick event" is missing. 
- This only applies for the README.md shown when clicking on an extension. If I open the README.md is VSCode -> right click -> open preview it works!

To reproduce this:
- git clone https://github.com/microsoft/vscode-extension-samples
- cd vscode-extension-samples/helloworld-minimal-sample
- Edit the README.md in this way:

```
## Table of contents

- [Section1](#section1)
- [Sub section1](#sub-section1)
- [Section2](#section2)
- [SubSection2](#sub-section2)


# Section1

- section 1

## Sub section1

- subsection 1

# Section2

- section 2

## Sub section2

- subsection 2

Below a red point is shown. This is taken from Wikipedia snippet: https://en.wikipedia.org/wiki/Data_URI_scheme#HTML

RED POINT: ![Alt text](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==)
```

- open package.json and remove the publisher section
- build this extension with npm install and vsce package
- install with code --install-extension helloworld-minimal-sample-0.0.1.vsix
- click on extension button in the left bar
- click on this extension
- look at its "home page". Links and images are broken. With the version 1.64.1 this doesn't happen. I've checked, the 1.64.2 is the first version that introduces this problem.

![Extension Homepage](https://user-images.githubusercontent.com/23222133/157834018-12bc2842-edbe-4e64-99e1-45111f283011.png)

- By the way if I open the README.md in the editor with OpenPreview, it works.

![Readme Preview](https://user-images.githubusercontent.com/23222133/157834069-e5b98161-9745-448e-bdfa-c486c59f87be.png)

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.15.25-1-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.27GB (7.67GB free)|
|Process Argv|-n --crash-reporter-id d17cabc3-8575-4b4e-ab00-ab1d8c6a0100|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.20.0
remote-containers|ms-|0.224.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30440023
pythonvsnew555:30450902
vscscmwlcmt:30438805
pynewfile477cf:30450039

```

</details>

**Comment by mjbvz** [comment]
Good catch! Thanks for the report
