### ISSUE TITLE
Editor automatically inserts quotes after =

### ISSUE THREAD

**Issue by stljeff1** [microsoft/vscode#144864]
Does this issue occur when all extensions are disabled?: Yes/No YES

- VS Code Version: 1.65
- OS Version: UBUNTU 20.10

Steps to Reproduce:

1. open html doc
2. write a tag, add an attribute, type equal....

VS code automatically updated, and now it auto inserts quotes after pressing equals key.

Ref: https://github.com/microsoft/vscode/issues/18071

Why was this the default option? Did you not consider long time developers who didn't have auto completion anything for the longest, and have always had the habit of pressing `=` + `"`? This small update has been driving me crazy for weeks because it is basically impossible for me to NOT type the quotes, resulting in heavily distorted HTML. Its sad to read some of the comments by people requesting this, asking to be more like webstorm and what not. Its even sadder that I got this update automatically and I have no idea how to disable it.

Please don't include keyboard shortcuts in automatic updates. Please me mindful of people who have disabilities and have a dificult time typing. What is simply "convenient" for some can cause major disruptions to others

**Comment by amritnagi** [comment]
This has been bugging me as well… it seems to be behaving strangely… for html if I do class= the cursor ends up after the quotes (class=“”|) but for vue attributes like v-if it is correctly putting the cursor in the middle.

Can we have some advice on how to toggle the functionality?

**Comment by yume-chan** [comment]
`"html.autoCreateQuotes": false`

**Comment by amritnagi** [comment]
> "html.autoCreateQuotes": false

That worked for me, thanks @yume-chan  👍

**Comment by Nutz-ello** [comment]
> `"html.autoCreateQuotes": false`
where do you do this?
