### ISSUE TITLE
Sync settings reset my setting from time to time

### ISSUE THREAD

**Issue by FredUA** [microsoft/vscode#144841]
Issue Type: <b>Bug</b>

Randomly from time to time, I have this issue. My settings.json becomes empty.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (2.97GB free)|
|Process Argv|--crash-reporter-id 18901fc5-6e3a-49a2-bb77-4edf817b8d99|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.10.9
open-html-in-browser|cod|0.1.21
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.84
prettier-vscode|esb|9.3.0
vscode-diff|fab|1.4.2
todo-tree|Gru|0.0.215
vue-snippets|hol|1.0.4
path-autocomplete|ion|1.18.0
fluent-icons|mig|0.0.17
dotenv|mik|1.0.1
ecdc|mit|1.4.0
vscode-postcss-sorting|mrm|3.0.1
vetur|oct|0.35.0
indent-rainbow|ode|8.2.2
require-cartridge-resolve|pik|1.8.1
material-icon-theme|PKi|4.14.1
view-in-browser|qin|0.0.5
vscode-yaml|red|1.5.1
synthwave-vscode|Rob|0.1.11
prophet|Sqr|1.4.26
vscode-stylelint|sty|1.2.2
todo-list|Tza|1.6.0
vscode-icons|vsc|11.10.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.13.20

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30440023
pythonvspyt640:30442238
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343
vsnot107cf:30443615

```

</details>

**Comment by sandy081** [comment]
Can you please give more information about when your settings are getting reset? Do you have settings sync enabled?

**Comment by FredUA** [comment]
> Can you please give more information about when your settings are getting reset? Do you have settings sync enabled?

Yes, setting sync enabled. Some times it synchronies and reset all my settings

**Comment by sandy081** [comment]
Can you please go to following view and figure out which machine of your's is resetting your settings

- F1 > Settings Sync: Show Synced Data
- Open Sync Activity (Remote) view
- Look at Settings entries and check which entry has pushed empty settings into cloud
