### ISSUE TITLE
Unable to remove breakpoints

### ISSUE THREAD

**Issue by pjyoung63** [microsoft/vscode#144901]
Issue Type: <b>Bug</b>

Running Visual Studio Code from Ubuntu in WSL2, I can debug code correctly, browse source code etc and set breakpoints, but once a breakpoint is set it is cannot be removed , it will appear to be removed in Visual Code but will continue to halt execution, breakpoints are only removed by restarting the target application.

VS Code version: Code 1.65.1 (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:06:27.846Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-10855M CPU @ 2.80GHz (12 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (9.99GB free)|
|Process Argv|--crash-reporter-id 92722e12-497c-4f57-8443-8b5b0e11dbac|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Xeon(R) W-10855M CPU @ 2.80GHz (12 x 2807)|
|Memory (System)|24.84GB (15.64GB free)|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
CppSnippets|har|0.0.15
better-cpp-syntax|jef|1.15.13
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
jinja|who|0.0.8
code-gnu-global|aus|0.2.2
vscode-django|bat|1.10.0
jsonviewer|cci|1.2.3
json-tree-view|Cha|2.6.0
doxdocgen|csc|1.4.0
jsonschemautils|dag|0.1.1
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
code-runner|for|0.11.7
CppSnippets|har|0.0.15
better-cpp-syntax|jef|1.15.13
cpp-pack|jew|0.0.2
vsc-python-indent|Kev|1.14.2
MagicPython|mag|1.1.0
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.1
jupyter|ms-|2022.2.1030672458
jupyter-renderers|ms-|1.0.6
cmake-tools|ms-|1.9.2
cpptools|ms-|1.9.3
cpptools-extension-pack|ms-|1.1.0
autodocstring|njp|0.6.1
java|red|1.4.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.0
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
jinja|who|0.0.8
json|Zai|2.0.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrc:30451274
dsvsc008:30440022
pythonvspyt640:30450904
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvidc:30447482
helix:30440343
vscaat:30438848
pynewfile477:30450038

```

</details>

**Comment by gjsjohnmurray** [comment]
What language are you debugging? All debugging is implemented by extensions, so you probably need to report this to the extension author.

**Comment by pjyoung63** [comment]
This is when debugging C++, I can manually remove some breakpoints using -exec info break to view them and -exec disable <bp_num> to remove them, it’s just only possible from the command line.
