### ISSUE TITLE
problem of settings sync on different OS

### ISSUE THREAD

**Issue by bi-kai** [microsoft/vscode#144968]
- VS Code Version: 1.65.2
- OS Version: macos 12.2

using "settings sync" plugin to sync settings in different os, config with absolute path is not working well in diff os:
```
  // golang
  "go.goroot": "D:\\go\\anzhuang",
  "go.gopath": "D:\\go\\go_modules",
```
it's not work in macos.

how to distinguish configs with diff os?

**Comment by sandy081** [comment]
>using "settings sync" plugin

Are you using the Settings Sync extension?
