### ISSUE TITLE
All extensions require reload 

### ISSUE THREAD

**Issue by DillonB07** [microsoft/vscode#144987]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
```
Version: 1.66.0-insider (Universal)
Commit: 6b7453421201c888b81eae5c04ec822a6423608f
Date: 2022-03-11T05:16:52.815Z
Electron: 17.1.1
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 19.6.0
```
- OS Version: macOS Catalina 10.15.7

Steps to Reproduce:

I'm not sure how to reproduce this, but when I opened the extensions tab, all of my extensions had `Reload Required` showing and when I do reload, it stays the same.

The extensions do work though...

I'm using the latest Insiders build(1.66.0).

**Comment by Wutus** [comment]
I have identical issue, all extensions have "Reload Required" label, but on Windows.
- VSCode version
```
Version: 1.66.0-insider (user setup)
Commit: 6b7453421201c888b81eae5c04ec822a6423608f
Date: 2022-03-11T05:17:19.559Z
Electron: 17.1.1
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044
```
- OS Version:
Windows 10 Pro, version 21H2, compilation 19044.1586

Problem appeared immediately after update.
