### ISSUE TITLE
Some the language configuration word definitions do not work well with specific characters

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [microsoft/vscode#144913]
This problem still occurs even if you disable all extensions. This problem was confirmed in LaTeX file.

# ~~`editor.wordSeparaters` do not work well with specific characters~~

When `editor.wordSeparators` is configured as follows, `．` (`U+FF0E`) doesn't work well as a separaters. This problem is also seen in `，` (`U+FF0C`).

```jsonc
  "editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?，．",
//                                              Added these: ^ ^
```

In Japanese, writing `．` at the end of the sentence indicates the end of the sentence, like a period. `，` is used like a comma. Especially, it is inconvenient that the suggestion is not displayed after the separater because the text is typed after `．` or `，`.

As an example, I gave some demonstrations to the following sentence.

```
こんにちは．先生
```

## Demo 1

Place the cursor. The entire text will be shaded. Should be separated by `．`.

![Place the cursor](https://i.gyazo.com/eba149db44c5bef8196562d4c31116dc.gif)

## Demo 2

Continue to type lestters and call suggestions (`Ctrl+Space`). In advance, I created `先生` and `teacher` as a snippet.

```json
{
  "Teacher in Japanese": {
    "prefix": "せんせい",
    "body": "先生",
    "description": "先生: Teacher in Japanese"
  },
  "Teacher in English": {
    "prefix": "teacher",
    "body": "Teacher",
    "description": "Teacher in English"
  }
}
```

Suggestions are not displayed. Even if you press `Ctrl+Space`, `No suggestions` are displayed.

![suggestions](https://i.gyazo.com/a2502c4215f5e239a110bc9aa9944e34.gif)

## Demo 3

Execute `Ctrl+Backspace` (`deleteWordLeft`) and `Ctrl+D` (`editor.action.addSelectionToNextFindMatch`).

- `Ctrl+Backspace`

    ![Ctrl+Backspace](https://i.gyazo.com/ff522f53cce55b3591b99184ddc4fbbc.gif)

- `Ctrl+D`

    ![Ctrl+D](https://i.gyazo.com/e4a97ab7dac1401b39bc85e8a66109fb.gif)

These seem to work well.

## For Markdown

I also tried Markdown.

If you do the same with Markdown with all extensions disabled, this problem will not occur but, if you enable [Markdown All in One](https://github.com/yzhang-gh/vscode-markdown), you will have similar problems. For that reason, it was difficult to know where this problem came from and to determine where to submit this issue.

If the issue with Markdown is due to the extension, please let me know.

I don't know what the results will be for other languages.

## Version

```
  Version: 1.65.2 (user setup)
  Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
    Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
  Node.js: 14.16.0
      V8: 9.1.269.39-electron.0
      OS: Windows_NT x64 10.0.19043
```

**Comment by alexdima** [comment]
@Yarakashi-Kikohshi In VS Code, there are two conceptual "word definitions". The first one is derived from the setting `editor.wordSeparators` and the second one is defined via a mechanism called language configuration by extensions and is programming language specific. 

---

#### 1. occurrence highlighting
This comes up when clicking on a word and the language doesn't have a semantic occurrence highlighting registered. This uses the language configuration word definition.

#### 2. suggestions
Suggestions also use the language configuration word definition.

#### 3. Delete word Left, Select next find match with word toggle on
These two commands use the configured `editor.wordSeparators`

---

This is the current built-in word definition for markdown:
https://github.com/microsoft/vscode/blob/3e5c7e2c570a729e664253baceaf443b69e82da6/extensions/markdown-basics/language-configuration.json#L55

And this is the current built-in word definition for LaTeX:
https://github.com/microsoft/vscode/blob/3e5c7e2c570a729e664253baceaf443b69e82da6/extensions/latex/latex-language-configuration.json#L110

---

@alexr00 Given LaTeX is similar to markdown, forwarding to you to investigate if the LaTeX word definition could be improved using some new concepts that markdown is using.

**Comment by Yarakashi-Kikohshi** [comment]
Thank you for the very clear explanation, @alexdima !



I had assumed that the three behaviors that I mentioned in the demonstration came from `editor.wordSeparators`, but now I understand that the first and second come from "the language configuration word definition". I also learned that "the language configuration word definition" is defined for each language.

Given the above, I can guess that `Markdown All in One` is the cause of the same problem with LaTeX when `Markdown All in One` is enabled.

I don't mean to be nosy, but...
You may need to change the title for this issue. In the current title, it looks like a problem with `editor.wordSeparators`, but it's actually a problem with "the language configuration word definition".

**Comment by jlelong** [comment]
> @alexr00 Given LaTeX is similar to markdown, forwarding to you to investigate if the LaTeX word definition could be improved using some new concepts that markdown is using.

@alexdima, @alexr00  I am the maintainer of [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics) used by `vscode/extensions/latex`. I am pretty confident that we could use these new concepts for LaTeX word definition. If they are fine for markdown, they should be for LaTeX too.

**Comment by alexr00** [comment]
@jlelong thanks for taking a look at this! Once you're confident of the new word definition please let me know and I'll copy it into `vscode/extensions/latex`. Or, feel free to make a PR that does the same I will take a look!

**Comment by jlelong** [comment]
To really make sure the new word definition is fine, I suggest a two step approach

1. I make a PR in [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics) and make a reference to it here so that people involved in this issue can test it.
2. Once step 1 is completed, I will make a PR against `vscode`. I will keep you posted.

**Comment by alexr00** [comment]
I appreciate the thoroughness. Sounds good!

**Comment by jlelong** [comment]
Here is the PR for the LaTeX language jlelong/vscode-latex-basics/pull/19. It would be really helpful if people using LaTeX could test this PR before it finds its way into VS Code.

**Comment by Yarakashi-Kikohshi** [comment]
@alexr00 

It seems that this issue has already been fixed, so I think it's okay to close it.
