### ISSUE TITLE
Ctrl + click doesn't not open a new VsCode window when selecting file on Quick Open Recent menu

### ISSUE THREAD

**Issue by dg00GT00** [microsoft/vscode#144979]
Issue Type: <b>Bug</b>

Ctrl + click doesn't not open a new VsCode window when selecting file on Quick Open Recent menu

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:36.248Z)
OS version: Linux x64 5.13.0-35-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx (8 x 1579)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|5.73GB (0.46GB free)|
|Process Argv|--unity-launch --crash-reporter-id 33142c45-c63c-4a92-8058-19c02c8c8545|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.2.4
armview|ben|0.4.6
better-toml|bun|0.3.2
dart-code|Dar|3.36.0
xml|Dot|2.5.1
gitlens|eam|12.0.4
prettier-vscode|esb|9.3.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vscode-test-explorer|hbe|2.21.1
vscode-react-typescript|inf|1.3.1
docomment|k--|0.1.30
intellij-idea-keybindings|k--|1.5.0
git-graph|mhu|1.30.0
azure-pipelines|ms-|1.195.0
vscode-azureappservice|ms-|0.23.1
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestaticwebapps|ms-|0.9.1
vscode-azurestorage|ms-|0.13.0
vscode-azurevirtualmachines|ms-|0.5.0
vscode-bicep|ms-|0.4.1318
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.20.0
csharp|ms-|1.24.1
vscode-dotnet-runtime|ms-|1.5.0
data-workspace-vscode|ms-|0.1.1
mssql|ms-|1.13.0
sql-database-projects-vscode|ms-|0.14.1
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.1
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.10.1
azurecli|ms-|0.5.0
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
powershell|ms-|2021.12.0
test-adapter-converter|ms-|0.1.5
vscode-node-azure-pack|ms-|0.2.1
azurerm-vscode-tools|msa|0.15.6
debugger-for-chrome|msj|4.13.0
cargo|pan|0.2.3
material-icon-theme|PKi|4.14.1
vscode-yaml|red|1.5.1
rust|rus|0.7.8
crates|ser|0.5.10
code-settings-sync|Sha|3.4.3
code-spell-checker|str|2.1.7
vscode-rust-test-adapter|Swe|0.11.0
cmake|twx|0.0.17
rust-extension-pack|wol|0.1.1

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by dg00GT00** [comment]
The issue still reproducible even on Windows.

Version: 1.66.0-insider (user setup)
Commit: 3e5c7e2c570a729e664253baceaf443b69e82da6
Date: 2022-03-14T05:15:38.097Z
Electron: 17.1.1
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by bpasero** [comment]
I cannot reproduce 🤷

**Comment by dg00GT00** [comment]
Please, watch the video for more insights: [VsCode issue](https://www.youtube.com/watch?v=IZkXMstMai8).
This issue was not hapenning a couple of version before. The last time I can remenber it worked as expected was until last November updated, but I can be wrong!

**Comment by bpasero** [comment]
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by dg00GT00** [comment]
Done. Same result as before

**Comment by bpasero** [comment]
Does it reproduce on a different machine, same OS?

**Comment by dg00GT00** [comment]
Yes. On my job machine. Not exactly the same OS version
OsVersion=10.0.19043; OsName=Microsoft Windows 10 Pro.
