### ISSUE TITLE
All Extensions show "Reload Required"

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#144930]
Issue Type: <b>Bug</b>

All of my extensions are showing a badge claiming "Reload Required". Clicking any will reload the window, but the badges don't go away. Quitting and relaunching does not clear it out.

![image](https://user-images.githubusercontent.com/13488/157973872-7c966d7d-7028-427c-bb2d-11b7a0e18d59.png)

VS Code version: Code - Insiders 1.66.0-insider (6b7453421201c888b81eae5c04ec822a6423608f, 2022-03-11T05:17:19.559Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (17.72GB free)|
|Process Argv|--crash-reporter-id 362817d9-b661-4b35-92b7-fe18e5872851|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
TabOut|alb|0.2.1
sync-scroll|dqi|1.3.0
vs-code-xml-format|fab|0.1.5
git-graph|mhu|1.30.0
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.13.0
csharp|ms-|1.24.1
azure-account|ms-|0.10.1
hexeditor|ms-|1.9.5
material-icon-theme|PKi|4.14.1
quicktype|qui|12.0.46
vscode-thunder-client|ran|1.13.3
hl7tools|Rob|1.13.2
msbuild-project-tools|tin|0.4.3
vscodeintellicode|Vis|1.2.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vsclayoutctrt:30405800
dsvsc009:30440021
pythonvspyt640:30438691
vscscmwlcmc:30428972
vscgsvid1:30433757
dockersurvey3:30438168
pynewfile477:30451556

```

</details>

**Comment by JustinGrote** [comment]
+1, happened to me too on March 11th build

**Comment by gjsjohnmurray** [comment]
/duplicate and expected to be fixed in Monday's build.
