### ISSUE TITLE
"unable to resolve resource"

### ISSUE THREAD

**Issue by freshyill** [microsoft/vscode#144943]
Anytime I try to access my files in a remote repository, I get an "Unable to resolve resource [name of repository]" error. Googling it doesn't seem to come up with anything relevant.

Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
Embedder: github.dev

**Comment by joyceerhl** [comment]
/gifPlease

@freshyill Thanks for the bug report--is this a recent issue or have you always seen this in github.dev?
