### ISSUE TITLE
Selecting a code-block using mouse results in multiple cursors

### ISSUE THREAD

**Issue by deadcoder0904** [microsoft/vscode#144915]
Issue Type: <b>Bug</b>

1. Select a chunk of code using mouse (selection needs to be >1 line)
2. See multiple cursors

https://user-images.githubusercontent.com/16436270/157888595-20e0a9d0-a303-4bb2-846e-2be026e59703.mp4

this is without holding <kbd>ctrl</kbd> or <kbd>cmd</kbd> (yes, it happened on my **mac** too)

started happening only since recently. i even disabled all extensions & it still happens.

on mac, multiple-cursors stopped showing when i held <kbd>cmd</kbd> but on windows, even holding <kbd>ctrl</kbd> doesn't do a thing. it still shows multiple-cursors so don't know how to cut-paste.

---

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4350T CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.80GB free)|
|Process Argv|--disable-extensions .|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc008:30440022
pythonvspyt640:30450904
vscscmwlcmc:30438804
vscgsvidc:30447482
pynewfile477:30450038

```

</details>

**Comment by alexdima** [comment]
It looks like you have enabled column selection mode (`Selection > Column Selection Mode`)

**Comment by deadcoder0904** [comment]
oh thank you so much....this really needs to rank on google as i waited for a long time but i knew it was due to a custom shortcut i probably pressed by accident.
