### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by dataangel** [microsoft/vscode#144941]
yarn install v1.22.10
$ node build/npm/preinstall.js
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.                                                                                             Done in 0.31s.                                                                                                          gyp info it worked if it ends with ok                                                                                   gyp info using node-gyp@8.4.1                                                                                           gyp info using node@16.14.0 | win32 | x64                                                                               gyp info ok
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.3.1: The platform "win32" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > css-loader@3.2.0" has incorrect peer dependency "webpack@^4.0.0".
warning " > eslint-plugin-jsdoc@19.1.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
warning " > file-loader@4.2.0" has incorrect peer dependency "webpack@^4.0.0".
warning " > gulp-postcss@9.0.0" has unmet peer dependency "postcss@^8.0.0".
warning " > gulp-tsb@4.0.6" has incorrect peer dependency "typescript@^3.0.0".
warning " > sinon-test@3.1.0" has incorrect peer dependency "sinon@2.x - 10.x".
warning " > style-loader@1.0.0" has incorrect peer dependency "webpack@^4.0.0".
[4/4] Building fresh packages...
[1/19] ⠂ @parcel/watcher
[6/19] ⠂ native-keymap
[3/19] ⠄ @vscode/sqlite3
[4/19] ⠄ keytar
error G:\vscode-main\vscode-main\node_modules\native-is-elevated: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: G:\vscode-main\vscode-main\node_modules\native-is-elevated
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.14.0 | win32 | x64
gyp info find Python using Python version 3.7.3 found at "D:\tools\Anaconda3\python.exe"
gyp info find VS using VS2022 (17.1.32228.430) found at:
gyp info find VS "d:\tools\Microsoft Visual Studio\2022\Professional"
gyp info find VS run with --verbose for detailed information
gyp info spawn D:\tools\Anaconda3\python.exe
gyp info spawn args [
gyp info spawn args   'H:\\npm\\global_yarn\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'G:\\vscode-main\\vscode-main\\node_modules\\native-is-elevated\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'H:\\npm\\global_yarn\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\dataangel\\AppData\\Local\\node-gyp\\Cache\\13.5.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\dataangel\\AppData\\Local\\node-gyp\\Cache\\13.5.2',
gyp info spawn args   '-Dnode_gyp_dir=H:\\npm\\global_yarn\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\dataangel\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\13.5.2\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=G:\\vscode-main\\vscode-main\\node_modules\\native-is-elevated',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'G:\\vscode-main\\vscode-main\\node_modules\\native-is-elevated\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (H:\npm\global_yarn\node_modules\node-gyp\lib\configure.js:261:16)
gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "D:\\tools\\nodejs\\node.exe" "H:\\npm\\global_yarn\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild

**Comment by deepak1556** [comment]
Seems like corrupted header installation, issue is not present in our CI. Please try with latest source tree.
