### ISSUE TITLE
Create new file using Plop - Default CRLF, not LF

### ISSUE THREAD

**Issue by ngoc199** [microsoft/vscode#144907]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.2 (user setup)
- OS Version: Windows 11

I have changed the end of line sequence settings by adding `"files.eol": "\n"` to the `settings.json` file.

When I create a new file using VSCode command or terminal command, the file eol is LF, which is expected.

But when I create a new file using PlopJS command, the file eol is CRLF. I don't know why this happens, but it does.

Steps to Reproduce:

1. Add `"files.eol": "\n"` to the settings.json file
2. Install PlopJS
3. Config PlopJS in `plopfile.js` and create a template for PlopJS to create a new file
4. Create a new file using PlopJS

**Comment by IllusionMH** [comment]
Could you please specify how it's problem with VS Code if file is created by PlopJS?
Do files actually have LF only line endings or CRLF before you open them?

**Comment by ngoc199** [comment]
@IllusionMH I think this is VS Code problem because if the file is created by PlopJS on macOS or Linux, the file eol is LF. I am using Windows, so the default eol is CRLF.

After changing the default eol in VS Code, I have created a file using a command line and its eol is LF, so I think VS Code handles the file creation correctly.

But the files created by PlopJS, which is also using command line, those files eol are CRLF. That's weird.

**Comment by IllusionMH** [comment]
Do you see how two last paragraphs contradict each other? You are saying that VS Code works correctly by itself, but something CRLF in files created by 3rd party tool.

Again - open files created by 3rd party tool in hex editor and check what they are using.

I don't think that VS Code would convert line endings in existing files if they were different just by itself. There are commands to explicitly convert line endings, indentation, and encoding, but they change file and require user action.

**Comment by ngoc199** [comment]
@IllusionMH Could you tell me what that command is? It will help me a lot by running it after creating new files using Plop.

**Comment by IllusionMH** [comment]
Hex Editor extension or in node console `fs.readFileSync` and check if content has `\r\n`

**Comment by bpasero** [comment]
I suggest to file a bug against `PlopJS`. If you can reproduce this issue without `PlopJS`, we can reopen this issue.
