### ISSUE TITLE
VS Code should re-open all editors, and keep all the state after restarting VS Code to install/enable a plugin

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode#14492]
VS Code should re-open all the editors, and put back everything in the same exact state after restarting VS Code to finish installing/enabling a plugin

Steps to Reproduce:
1. Have an editor open on a certain line
2. Install a plugin, and enable it. VS Code says it needs to restart to enable the plugin
3. Now the editor view is closed.

**Comment by bpasero** [comment]
@digeff was this for when you had a folder opened in VS Code or when you had no folder opened?

**Comment by digeff** [comment]
I had a folder opened. The folder did-reopen, but not the editors.

**Comment by bpasero** [comment]
@digeff this is weird, we always restore the opened editors no matter what. Can you see if simply reopening Code keeps your editors? Can you reproduce this issue always with any extension you install?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Comment by digeff** [comment]
@bpasero Sorry, I wasn't able to reproduce this issue. It if happens again I'll reopen it
