### ISSUE TITLE
1.65.2 version fail when launch

### ISSUE THREAD

**Issue by Thinking-calculus** [microsoft/vscode#144971]
Issue Type: <b>Bug</b>

After upgrading my vscode to 1.65.2v, the following question always shows up as a popup on the bottom left no matter if I open vscode with the file or not. I didn't have any other changes to the settings before or after the upgrade. If MS knows anything about this, please let me know or fix it asap. thanks.

log >>>>
No view is registered with id: codespaces.explorerDetails

No view is registered with id: codespaces.explorer

Activating extension 'ms-vsonline.vsonline' failed: Extension 'ms-vsonline.vsonline' CANNOT use API proposal: resolvers. Its package.json#enabledApiProposals-property declares: [] but NOT resolvers. The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-vsonline.vsonline.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.90GB (7.15GB free)|
|Process Argv|--crash-reporter-id 6e6418c8-8712-4a42-88a3-389e0f1a7d21|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|asc|2.9.8
markdown-mermaid|bie|1.13.2
doxdocgen|csc|1.4.0
xml|Dot|2.5.1
vue|jcb|0.1.5
better-cpp-syntax|jef|1.15.13
vscode-docker|ms-|1.20.0
vscode-language-pack-zh-hans|MS-|1.65.2
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.1
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
hexeditor|ms-|1.9.5
vscode-typescript-next|ms-|4.7.20220312
vsonline|ms-|1.0.3076
vetur|oct|0.35.0
highlight-words|rsb|0.1.4
markdown-preview-enhanced|shd|0.6.2
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30450902
vscscmwlcmc:30438804
pynewfile477:30450038

```

</details>

**Comment by connor4312** [comment]
That error message is coming from the old, deprecated Codespaces extension. You can uninstall it.

**Comment by bfeng** [comment]
The `ms-vsonline.vsonline` extension doesn't show in UI. This command resolved the issue for me:
```
code --uninstall-extension ms-vsonline.vsonline
```

**Comment by ginpei** [comment]
I uninstalled the [GitHub Codespaces extension](https://marketplace.visualstudio.com/items?itemName=GitHub.codespaces) but still it happened.

For me, setting `"codespaces.accountProvider": "GitHub"` solved. (I've logged in to GitHub)

![VS Code settings > search by "codespaces.accountProvider" > set GitHub](https://user-images.githubusercontent.com/355808/159051831-72f3af96-8759-4d35-b99f-c6647890fb54.png)
