### ISSUE TITLE
Add editor option to start line number with zero

### ISSUE THREAD

**Issue by allan-silva** [microsoft/vscode#144942]
Like  #79124, would be great a options to set display lines number as zero-based index.
![image](https://user-images.githubusercontent.com/9947646/158000703-14394a97-3d62-433a-a7e6-82eba220ba00.png)

This is a new chance to get 20 upvotes from community.

My use case is use the editor to help-me debug string manipulation programs.
![image](https://user-images.githubusercontent.com/9947646/158000860-9e88a00a-5a17-40db-b711-f7f90834293b.png)

**Comment by david-fong** [comment]
Another failed feature-request: #107869

**Comment by starball5** [comment]
Another failed feature-request: #107869

**Comment by Daniel-Chin** [comment]
How lines are numbered is a language-specific convention. For example, [mlog](https://mindustrygame.github.io/wiki/logic/0-introduction/) programs starts at line 0.

**Comment by DroneBetter** [comment]
Can the scope of this be extended also to the indicator of the column containing the cursor (in the bottom-right) and the find menu, please? (ie. a new menu subsection that contains 'indexing' for each of them)

**Comment by hediet** [comment]
No other editor I know of supports this feature.
I don't think implementing rendering of 0-based line numbers just to aid debugging is justified. 
Rather, I think an extension could help here by providing a webview to render the text with all the required information.

**Comment by rgu3st** [comment]
At this point, I'm use to counting almost everything starting at zero and I do find it jarring then to start at one in the code editor...

**Comment by CiramorDev** [comment]
It would indeed be nice to be able to change the starting number!
