### ISSUE TITLE
Highlighter crashes for some reason related to whitespaces

### ISSUE THREAD

**Issue by sharon-adm** [Microsoft/vscode#14493]
- VSCode Version:1.6.1
- OS Version:windows 10(1607)

This portion of code breaks the highlighter

![before](https://cloud.githubusercontent.com/assets/16360766/19703708/a6a9d8e2-9b11-11e6-9f37-7f00f5b20872.PNG)

However I found out that if you place a space before the "size" it all fixes up

![after](https://cloud.githubusercontent.com/assets/16360766/19703713/a9d2c2ea-9b11-11e6-8132-62e1d4886e25.PNG)

**Comment by waderyan** [comment]
Thank you for opening this issue. I have tested this issue using the latest JavaScript / TypeScript grammar. You can test this with this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar). It is in beta now and we are looking at brining it into the product soon. 

If for some reason this doesn't work on your end then let me know and I will reopen.

**Comment by sharon-adm** [comment]
@waderyan Thanks :)
