### ISSUE TITLE
Multi file intellisense for typescript in vscode web 

### ISSUE THREAD

**Issue by ameerthehacker** [microsoft/vscode#144953]
Codesandbox supports import suggestions and reactors across typescript files but vscode web does not, I'm curious to know the technical difficulty behind this and if this can be supported I'm willing to work on it :)

**Comment by Lemmingh** [comment]
This idea has been on the iteration plans of TypeScript and VS Code for a long time.

Please turn to the repo of TypeScript where the development of a web-based TS Server mainly takes place. There are lots of discussions, for example:

* <https://github.com/microsoft/TypeScript/issues/45314>

**Comment by ameerthehacker** [comment]
Got it thanks
