### ISSUE TITLE
Handle version mismatch between auto-acquired definition and local package

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14495]
Testing #14328

If I have project A where automatic type acquisition got lodash@4's definition, and in project B I installed lodash@3, now VSCode would use the cached definition of lodash@4 for project B and provide incorrect definition.

In packages under `@types`, `package.json` include a field that specifies which version is compatible with the current definition, like so:

```
  "_from": "@types/lodash@>=4.14.37 <5.0.0",
```

We should read that and only provide intelliSense if it matches against the version in local `package.json`.

**Comment by octref** [comment]
#14491 need upstream fix, but this check against mismatch is something we can do. So I opened a new issue instead.

**Comment by mjbvz** [comment]
I believe this was addressed by https://github.com/Microsoft/TypeScript/issues/13964

TS should now prefer the local typings files over the globally installed ones. In this case, you'd still have to install the correct type package for lodash 3 into your project
