### ISSUE TITLE
Option to uninstall only the pack doesn't add much value

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#14496]
Testing #14291 

![image](https://cloud.githubusercontent.com/assets/16890566/19707412/4cb22000-9acc-11e6-9ace-5bfeab23f9cf.png)
 
Instead of the 3 options : "Only", "All", "Cancel"
We should have a simpler message 

> Would you like to uninstall all the extensions in the pack 'extension pack name'?  **Uninstall** **Cancel**

**Comment by sandy081** [comment]
@ramya-rao-a All extensions with dependencies are not necessary to be packs. They will have functionality themselves. Pack is an extension with just dependencies.

**Comment by ramya-rao-a** [comment]
@sandy081 Got it.
