### ISSUE TITLE
Can't change devtools theme

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#144959]
Does this issue occur when all extensions are disabled?: Yes/No

Yes

- VS Code Version: 1.66.0-insider
- OS Version: MacOS 12.2.1

Steps to Reproduce:

1. open devtools
2. go to settings and change theme to dark
3. quit and reopen vscode
4. open devtools, the theme still is light theme

**Comment by aeschli** [comment]
Not sure how/where the dev tools settings are stored.

**Comment by deepak1556** [comment]
This is a known regression in the runtime https://github.com/electron/electron/issues/31864, pending new release with the fix.
