### ISSUE TITLE
Cursor jumps to end of file on save

### ISSUE THREAD

**Issue by pjc2007** [microsoft/vscode#144948]
Issue Type: <b>Bug</b>

I have had this issue in previous versions of VSCode, but it has been find until the second last update (1.65.1). Whenever I save a file (or auto save saves it), the cursor jumps to the end of the file. Just updated to 1.65.2 hopeing this was fixed, but I still have it. I have had to turn off autosave as is unusable now.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:34:03.833Z)
OS version: Windows_NT ia32 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (6.76GB free)|
|Process Argv|--crash-reporter-id e4210f4e-8bfa-4f1f-84cc-bf3a4a982af9|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.4
ng-template|Ang|13.2.5
emojisense|bie|0.9.0
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.4
filter-line|eve|2.0.1
vscode-test-explorer|hbe|2.21.1
csharp|ms-|1.24.1
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.1
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.8.4
test-adapter-converter|ms-|0.1.5
vscode-typescript-tslint-plugin|ms-|1.3.3
cordova-tools|msj|2.4.1
debugger-for-chrome|msj|4.13.0
vscode-auto-scroll|pej|1.0.4
angular-karma-test-explorer|raa|1.2.8
vscode-scss-formatter|sib|2.3.3
code-spell-checker|str|2.1.7
vscode-todo-highlight|way|1.0.5
change-case|wma|1.0.0
intelligence-change-case|zhe|1.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmc:30438804
vscgsvidc:30447482
vscaat:30438848
pynewfile477cf:30450039

```

</details>

**Comment by Lemmingh** [comment]
/duplicate #144800

The extension "Auto Scroll" (`pejmannikram.vscode-auto-scroll`) seems incompatible with VS Code 1.65.

**Comment by pjc2007** [comment]
This this was the problem. I have uninstalled this extension, and the problem is resolved.

**Comment by mongoose666** [comment]
Same for me. Removing the extension works a treat 😉
