### ISSUE TITLE
Similar to Issue #132171

### ISSUE THREAD

**Issue by Advantos** [microsoft/vscode#144916]
Every time I open VS Code then close it I get a dialog saying "Updating Visual Studio Code...".  This started recently (I don't use VSCode much so haven't opened it in a month or so).

After 60 seconds or so I get another dialog saying "There was an error while Opening file handle: "D:\\Microsoft\\VSCode\\logs\\custom-scanners-service.log": Failed to create file handle: The process cannot access the file because it is being used by another process.  Please verify there are no Visual Studio Code processes still executing."

Looking at task manager I see VSCode's "inno_updater.exe (32 bit) (2)" is running and "Setup/Uninstall (32 bit)" is running.  Looking further down in the background processes running I see "Visual Studio Code Setup (32 bit)".

My solution is to cancel everything and not mess with VSCode, but there is probably a better solution.

Windows 10 Pro
Build 18362

Visual Studio Code
Version: 1.64.2 (user setup)
Date: 2022-02-09T22:02:28.2527 (4 wks ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18362
![VSCodeErrorUponClosing_20220311](https://user-images.githubusercontent.com/69653888/157889048-1aa7cf7c-2c8a-4cdf-9b95-2b72d3710df2.gif)
![VSCodeErrorUponClosing1_20220311](https://user-images.githubusercontent.com/69653888/157889341-474d10e1-190d-450e-87a0-f5d3721673eb.gif)

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
