### ISSUE TITLE
Autocomplete aggressively tries to fill "await" keyword

### ISSUE THREAD

**Issue by richardcocks** [microsoft/vscode#144949]
Issue Type: <b>Bug</b>

If I type out a simple loop in dotnet/c#, for example when typing out this method:

    public void AddRect(int a, int b)
            {
                for(int i = 0; i < a

Then as soon as I hit either the second 'i' or the first 'a' in the for loop line, the autocomplete tries to aggressively fill in the "await" keyword and make my method asynchronous.

It doesn't always do this if the method is already async, but if it's a synchronous method it seems to very aggressively try to autocomplete the await keyword for any letter that appears in await.

I've not noticed this behaviour be so bad before, I've used vscode for years and while occassionally I might try up a bad autocomplete when already in invalid syntax, I've never noticed so many bad completions when typing 'correct' syntax.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 3900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (23.52GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Rich/Documents/code/aoc/adventserver --crash-reporter-id 09e1179b-7e25-417e-acec-e791f03bab00|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
pgn|jak|1.0.1
csharp|ms-|1.24.1
poe-filter-language|Nev|2.0.4
vetur|oct|0.35.0
lua|sum|2.6.7
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30440023
pythonvsnew555:30450902
vscscmwlcmt:30438805
vscgsvid2:30447481
pynewfile477:30450038

```

</details>

**Comment by richardcocks** [comment]
This might be due to omnisharp, so I'm trying `"omnisharp.useModernNet": true` as a potential fix.

**Comment by ZoKixMo** [comment]
A temporary solution would be to disable autocomplete when pressing space and only allow it for tab and enter. But I can only find key bindings for enter and tab but not for space...
