### ISSUE TITLE
UX: Visual indication for acquiring type definition file

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14494]
While testing #14328

When opening a JS project in VSCode, the types are acquired in the background silently.

To users who know this feature: After typing `var fs = require('fs')`, should they wait for VSCode to download the typings? When would they know VSCode is done and they can enjoy intelliSense?

To users who don't know this feature: intelliSense wouldn't work first but start to work later. Might make them think it's unreliable.

I suggest a visual indication on status bar.

**Comment by mjbvz** [comment]
Closing in favor of #15209
