### ISSUE TITLE
problemMatcher/fileLocation does not work on UNC paths

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode#144951]
Version: 1.65.1 (user setup)
Commit: 8908a9ca0f221f36507231afb39d2d8d1e182702
Date: 2022-03-08T02:06:27.846Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

I was trying to setup a build environment on a UNC path.
Specifically I have a build environment in docker and want to call it from windows vscode.
The docker build returns an absolute path for found errors.
The following problemMatcher extracts the relative path from it.

~~~json
           "problemMatcher": [{
               "owner": "docker run",
               "source": "docker run",
               "fileLocation": ["relative", "${workspaceFolder}" ],
               "pattern": [{
                   "regexp": "^/home/src/(.*):(\\d+):(\\d<file://d+/):(/d>+): error:\\s+(.*)$",
                   "file": 1,
                   "line": 2,
                   "column": 3,
                   "message": 4
               }]
           }],
~~~

Vscode is having the source files under the UNC path 
~~~
\\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes\docker-volume\_data\
~~~
which is also the workspace folder.

I can see that the regex is working if I change the fileLocation to "absolute".
But if I use the "relative" form for fileLocation the found errors are not even shown.

Strange enough: If I change fileLocation to some none existing folder the errors **are shown** in the problem pane. Eg.
~~~json
"fileLocation": ["relative", "abcd" ],
~~~
makes them appear in the problem pane, but obviously this is useless.

So the problem pane area is filled only for absolute paths or senseless paths but **not for the relative paths to an UNC** workspaceFolder.

I did some more investigation by setting the  workspace folder in parenthesis (```"\"${workspaceFolder}\""```) and it seems that during substitution the first slash is removed, giving only "\wsl$". Maybe that is the reason why it's not working.

**Comment by maziac** [comment]
Is there any update on this?

**Comment by alexr00** [comment]
@maziac can you give an example of some of the output from your task?

**Comment by maziac** [comment]
This is not a regex / pattern error. I can see something in the problem pane if I just change 'fileLocation' from 'relative' to 'absolute'. Even with the same regex.

**Comment by alexr00** [comment]
Thank you for posting your work around!
