### ISSUE TITLE
Search File List Lexicographic Ordering

### ISSUE THREAD

**Issue by atom0s** [microsoft/vscode#144937]
It would be nice to have the option to set the `sortOrderLexicographicOptions` of the search file list. At this time, it uses the `default` setting always with no means of altering it.

The main explorer file list already has the ability to set a natural sort order using the `Unicode` option with the setting: `"explorer.sortOrderLexicographicOptions"`. 

Going between the explorer file list and the search with completely different sort orders is pretty jarring and unproductive, especially in folders where file names are hexadecimal and the default sort order does not work well, at all, with those kinds of file names.

For example, I have a folder of hex file names such as `0x0000.md` to `0x00FF.md`. With the `default` sort order the files are entirely out of order and annoying to sift through to find the one I wish to edit. Changing `explorer.sortOrderLexicographicOptions` to `Unicode` works great and enables a natural sort order, keeping the files in proper hexadecimal order. But, this feature is missing from the search file list.

**Comment by eleanorjboyd** [comment]
This feature request is now a candidate for our backlog. The community has 60 days to [[upvote](https://github.com/microsoft/vscode/wiki/Issues-Triaging#up-voting-a-feature-request)](https://github.com/microsoft/vscode/wiki/Issues-Triaging#up-voting-a-feature-request) the issue. If it receives 20 upvotes we will move it to our backlog. If not, we will close it. To learn more about how we handle feature requests, please see our [[documentation](https://aka.ms/vscode-issue-lifecycle)](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!

**Comment by eleanorjboyd** [comment]
Hi! Since this has been open since last year- closing since it had enough time to collect upvotes, sorry for the confusion
