### ISSUE TITLE
Can start two debug configs manually, if the first one is slow to start

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14498]
Probably not intentional for this release? But if you start a node attach config with the wrong port, it will spin quietly in the background for 10 seconds, and during that time, you can start a launch config. The run button is not disabled in the debug viewlet until the launch has finished starting up and attaching.

**Comment by isidorn** [comment]
Yeah this is not intentional for this release, will look into

**Comment by isidorn** [comment]
It is still possible to start two by clicking really really fast, but will not fix that since we will support this in the future either way

**Comment by bpasero** [comment]
I can still reproduce:
* in selfhost press play on "Attach to CLI process"
* click again (only now the button gets disabled)

I get 2 error messages of timeout too.
