### ISSUE TITLE
Load extensions and start terminal very slow

### ISSUE THREAD

**Issue by DukeHouse** [microsoft/vscode#144939]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T15:36:26.048Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-25-generic

Steps to Reproduce:

1. load all extensions is very slo
2. start terminal is very slow
3. disable all extensions maybe load extensions faster

**Comment by DukeHouse** [comment]
all the deveices have this peoblems ，Ubuntu 20.04 ，Windows10 and macOS 12，please pay more attention for this

**Comment by meganrogge** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
/label "needs more info" terminal

**Comment by DukeHouse** [comment]
i opened vscode progress expolrer,find that ptyhost display then the terminal will display. It would take 50 seconds.

**Comment by DukeHouse** [comment]
i opened vscode progress expolrer,find that ptyhost display then the terminal will display. It would take 50 seconds.

**Comment by DukeHouse** [comment]
btw ， while i used vpn or reopen the wifi， the problem never come again，all my team member ‘s computer has this issue，i think maybe the progress request the network.

**Comment by DukeHouse** [comment]
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
[19261:0315/164247.967151:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Version:          Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS Version:       Linux x64 5.13.0-25-generic
CPUs:             AMD Ryzen 7 5800H with Radeon Graphics (16 x 1300)
Memory (System):  13.51GB (7.08GB free)
Load (avg):       1, 1, 1
VM:               67%
Screen Reader:    no
Process Argv:     --unity-launch --crash-reporter-id 59c021a3-78c3-4310-a816-504ff21f878c
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     enabled_on
                  rasterization:              disabled_software
                  skia_renderer:              enabled_on
                  video_decode:               disabled_software
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %	Mem MB	   PID	Process
    0	   152	 18990	code main
    0	    28	 18995	   zygote
    2	   166	 19025	     gpu-process
    0	    28	 18996	   zygote
    0	     0	 18998	     zygote
    0	    42	 19032	   utility-network-service
    7	    83	 19172	   extensionHost
    0	   111	 19185	   shared-process

Workspace Stats: 
|  Window (main.py - agv_ros - Visual Studio Code)
|    Folder (agv_ros): 1423 files
|      File types: cpp(116) launch(96) xml(85) py(82) txt(80) h(76) hpp(65)
|                  yaml(63) msg(45) rst(43)
|      Conf files: settings.json(2) makefile(2) launch.json(1) tasks.json(1)

**Comment by DukeHouse** [comment]
this is prof-C7YZxDzm.main.cp
[prof-C7YZxDzm.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/8252158/prof-C7YZxDzm.main.cpuprofile.txt)

**Comment by meganrogge** [comment]
> the problem never come again，all my team member ‘s computer has this issue，i think maybe the progress request the network.

Unfortunately I think you've figured out your issue and there's nothing we can do on our end to fix this.

**Comment by mintxtinm** [comment]
It looks like the problem is caused by VSCode requesting [exp-tas.com](https://default.exp-tas.com/vscode/ab) on launch before the extension list and terminal initialization, which is extremely slow in mainland China

**Comment by mintxtinm** [comment]
Setting workbench.enableExperiments to false can fix this issue.

**Comment by DukeHouse** [comment]
yes , my opinion is the same as yours, but your advice is not work for me , i set a wrong proxy to avoid network, when i need extension market i delete the proxy. And i really hope the MS provide a method for users in mainland China. @meganrogge

**Comment by DukeHouse** [comment]
@mintxtinm Thanks for your attentions  , my opinion is the same as yours, but your advice is not work for me , i set a wrong proxy to avoid network, when i need extension market i delete the proxy. And i really hope the MS provide a method for users in mainland China. @meganrogge
