### ISSUE TITLE
Not able to give space

### ISSUE THREAD

**Issue by Vasudev32** [microsoft/vscode#144945]
Issue Type: <b>Bug</b>

Facing this issue from a week in vs code. I am not able to give space in my code/syntax .

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.65GB (2.95GB free)|
|Process Argv|--crash-reporter-id 2927c73b-8836-4b57-85ef-49a319292158|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
competitive-programming-helper|Div|5.9.2
prettier-vscode|esb|9.3.0
code-runner|for|0.11.7
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.1
java|red|1.4.0
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.0
vscode-maven|vsc|0.35.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc008:30440022
pythonvspyt640:30450904
vscscmwlcmc:30438804
vscgsvidc:30447482
pynewfile477cf:30450039

```

</details>

**Comment by gjsjohnmurray** [comment]
If the problem remains after you run the command to reload with all extensions disabled, please paste a screenshot and a detailed explanation of what you mean.

**Comment by Vasudev32** [comment]
@gjsjohnmurray I tried your solution but the problem remains as it is. The problem is  spacebar is not working to give space between the words in vs code instead of it i have to use shift + Tab to give space.

**Comment by gjsjohnmurray** [comment]
I suggest you use the Command Palette (F1) to run `Preferences: Open Keyboard Shortcuts (JSON)` and look for any entries that might be intercepting the space character.

**Comment by Vasudev32** [comment]
@gjsjohnmurray yeah now i got it i added a shortcut key combination with space that's why i was facing this issue.
Thank U
