### ISSUE TITLE
Vs code Git Bash . code Not working

### ISSUE THREAD

**Issue by 161134077** [microsoft/vscode#144973]
Hello,

I Have Problem Vs code using Terminal Git Bash:
`. code`

Notif Error : The terminal process "C:\Program Files\Git\bin\bash.exe '--login'" terminated with exit code: 127.
![terminal bash error](https://user-images.githubusercontent.com/39833970/158051912-6e6179f3-9106-4a7d-8273-b2b8c8786efa.JPG)

**Comment by Lemmingh** [comment]
Out of curiosity, **why did you use sourced invocation?**

---

The dot command (sourced invocation) breaks the precondition of

<https://github.com/microsoft/vscode/blob/6b7453421201c888b81eae5c04ec822a6423608f/resources/win32/bin/code.sh#L14-L15>

, producing an invalid path. Thus, Git Bash quits with exit code 127.

---

A solution is [replacing `"$0"` with `"${BASH_SOURCE[0]}"`](https://stackoverflow.com/a/35006505).

However, the script expects `sh` according to the shebang:

<https://github.com/microsoft/vscode/blob/6b7453421201c888b81eae5c04ec822a6423608f/resources/win32/bin/code.sh#L1>

[The nonstandard `$BASH_SOURCE` variable might not exist in `sh`.](https://stackoverflow.com/a/29835459)

**Comment by 161134077** [comment]
@Lemmingh  thanks working
