### ISSUE TITLE
Typescript Language Server crashing

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#144922]
The output channel
[typescriptoutput.log.zip](https://github.com/microsoft/vscode/files/8234343/typescriptoutput.log.zip)

It's in a crashing loop and there are a ton of tsserver-log-* folders and the files are very large. I zipped a bunch of them. Hopefully you can find something useful in here.
[Archive.zip](https://github.com/microsoft/vscode/files/8234352/Archive.zip)

**Comment by mjbvz** [comment]
Thanks for the logs!

Can you try disabling the tslint extension to see if this fixes the issue? I've seen a few other reports of it causing issues with in-memory files
