### ISSUE TITLE
Graphic display error in debug mode

### ISSUE THREAD

**Issue by iceice** [microsoft/vscode#144981]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.2 (Universal)
- OS Version: macOS 10.15.7

Steps to Reproduce:
As shown in the figure, there are two yellow arrows

<img width="661" alt="image" src="https://user-images.githubusercontent.com/17559521/158060096-8637814c-367d-4395-b636-b93d3aaccb44.png">

launch.json
```Json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "(lldb) Launch",
      "type": "lldb",
      "request": "launch",
      "program": "${workspaceFolder}/build/db_bench",
      "args": [],
      "stopAtEntry": true,
      "cwd": "${fileDirname}",
      "environment": [],
      "MIMode": "lldb",
      "miDebuggerPath": "/usr/local/opt/llvm/bin/lldb",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for lldb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": false
        }
      ]
    }
  ]
}

```

**Comment by weinand** [comment]
If your debugger supports multiple "column"  breakpoints, then this is expected.
