### ISSUE TITLE
Windows/Git: password prompt does not seem to work on windows

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1449]
Windows 10
git version 2.6.2.windows.1

I entered my user name and access token and wanted to push and it failed with authentication required. But the same operation works fine from the command line.

**Comment by jamesxv7** [comment]
I'm having the same problem with version 2.5.1.windows.1. This [issue](https://github.com/Microsoft/vscode/issues/490) mention something about Github Desktop authentication.

**Comment by JamesEarle** [comment]
Experiencing the same problem, version 0.10.6
