### ISSUE TITLE
'Run Task...' quick pick does not display separate category for contributed task type

### ISSUE THREAD

**Issue by andreeageorgian** [microsoft/vscode#144912]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65
- OS Version: 

Up until VS Code 1.63, the 'Run task...' quick pick displayed a separate category corresponding to a custom contributed task type:

![question](https://user-images.githubusercontent.com/25352050/157878148-4f309328-c04b-4982-8ca9-13164249225d.png)

But starting with VS Code 1.64 this is not the case anymore.

Thank you!

**Comment by alexr00** [comment]
Each of those "folders" (Custom Tasks, typescript, grunt, gulp, jake, npm) comes from an extension. There is no built in extension that contributes a task type of "Custom Tasks", so that is coming from an extension that you installed.

**Comment by andreeageorgian** [comment]
There actually is an extension that contributes with "Custom Task":

![tasks](https://user-images.githubusercontent.com/25352050/157902362-ff75ca34-c94a-490e-a179-79b58aefa89f.gif)

As you can see, the tasks with a "Custom Task" type are displayed in the list, but the "Custom Task" folder is not there.

**Comment by andreeageorgian** [comment]
@alexr00 Can you please help me figure out if this is indeed a bug or did i just miss a configuration?

Thanks.

**Comment by andreeageorgian** [comment]
Thank you for your help! :)
