### ISSUE TITLE
Mouse wheel click in the file selector

### ISSUE THREAD

**Issue by emfierro** [microsoft/vscode#144978]
Does this issue occur when all extensions are disabled?: Yes, exept russian language pack, for some reason it can't be disabled

- VS Code Version: 1.65.2
- OS Version: 21H2 Windows_NT x64 10.0.22000 

1. Mouse wheel click on any file in the VS Code file explorer changes windows cursor shape. Some times it can be restored by pressing mwheel on any other file, some times even mouse LB can, some times nothing helps.
![Screenshot_1](https://user-images.githubusercontent.com/60270967/158057107-796eccc9-c6ab-48bb-b533-09f1eb6ab7d7.png)

**Comment by JacksonKearl** [comment]
Interesting. I don't have a mouse so cannot really test this.

**Comment by amanasifkhalid** [comment]
I can try to reproduce this once I get home in about an hour. May I work on this?

**Comment by KarKarbI4** [comment]
Couldn't reproduce on Windows 11

Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
