### ISSUE TITLE
Opening VSCode in WSL  getting error

### ISSUE THREAD

**Issue by samzalahi** [microsoft/vscode#144988]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.2
- OS Version: Windows 11

Steps to Reproduce:

1. Opening VSCode in WSL ubuntu terminal by typing 'code .'
2. Getting this error
![Screenshot 2022-03-13 192746](https://user-images.githubusercontent.com/10072900/158069710-3d9304f0-d8ad-4e22-91a3-f3b3c3d867c1.png)

3. While opening WSL-remote from VSCode getting this error.
![Screenshot 2022-03-13 193003](https://user-images.githubusercontent.com/10072900/158069784-66ef13f4-f535-4528-8deb-ffc8f4734ccc.png)

**Comment by aeschli** [comment]
Looks like a connection problem to our update service. Are you behind a proxy?
Is the URL working when opening it in a browser?

**Comment by samzalahi** [comment]
Yes I believe it is from your end. yesterday it was not working and now today it is working.
