### ISSUE TITLE
Terminal not responding, so does extension market

### ISSUE THREAD

**Issue by Shoreshen** [microsoft/vscode#144935]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T15:36:26.048Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.16.11-2-MANJARO

Steps to Reproduce:

1. In China ..........
2. Install latest manjaro, update to latest vscode using pamac for package `visual-studio-code-bin`
3. Start vscode and open a new terminal, it will stuck there for a very long time (5 mins around) like [this](https://stackoverflow.com/questions/71431161/vscode-cannot-open-terminal-unless-connect-to-vpn)

BTW, the insider version is OK.......

**Comment by meganrogge** [comment]
Since it works in insiders, closing this as we must've fixed something
