### ISSUE TITLE
Keyboard shortcut for macOS Character Viewer has stopped working

### ISSUE THREAD

**Issue by callumlocke** [microsoft/vscode#144974]
Issue Type: <b>Bug</b>

Steps to reproduce

1. Typing in any file, press <kbd>ctrl+cmd+space</kbd>
2. Observe that nothing happens

Expected:

This shortcut is supposed to bring up the [macOS Character Viewer](https://support.apple.com/en-gb/guide/mac-help/mchlp1560/mac) for inserting special characters.

Notes:

It used to work until recently. It still works in other macOS apps. Now the only way to get the Character Viewer in VS Code is to click `Edit > Emoji and Symbols`. This isn't as good, it brings up a force-foregrounded window that must be closed manually after each use, instead of the usual streamlined pop-out which is more convenient for entering the odd special character while typing code. And there's apparently nothing in the VS Code command palette that will activate this menu item, so there's no way to set up a manual keyboard shortcut for it anyway.

---

VS Code version: Code 1.65.1 (Universal) (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:20:11.670Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|. --crash-reporter-id e893d351-46db-4ce4-9b20-c6fd16db7314|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
rails-partial|aki|0.3.2
rails-routes|aki|0.6.1
vscode-styled-jsx|bla|2.1.1
vscode-tailwindcss|bra|0.7.7
rails|bun|0.17.8
vscode-gemfile|bun|0.4.2
js-codeformer|cms|2.6.1
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.4
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.3.0
styled-components-extractor|Fal|0.0.7
flow-for-vscode|flo|2.0.0
copilot|Git|1.7.5250
gitkraken-authentication|git|1.0.3
applescript|idl|0.21.1
rails-fast-nav|jem|1.3.6
svg|joc|1.4.17
vscode-insertdatestring|jsy|2.3.1
vscode-deno-extensionpack|jus|0.3.0
theme-karyfoundation-themes|kar|25.2.3
deno-std-lib-snippets|lau|0.0.8
dotenv|mik|1.0.1
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
vscode-remote-extensionpack|ms-|0.21.0
rails-run-spec-vscode|nok|0.1.4
vscode-commons|red|0.0.6
vscode-yaml|red|1.5.1
slim|sia|0.1.2
gitconfig|sid|2.0.1
unique-window-colors|stu|1.0.51
svelte-vscode|sve|105.12.1
selectline-statusbar|tom|0.0.2
rails-snippets|Ven|0.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30440023
pythonvspyt640:30450904
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvid1:30447480
helix:30440343
pynewfile477cf:30450039

```

</details>

**Comment by alexdima** [comment]
This reproduces in all software on macOS and is controlled by a macOS setting. Please see https://github.com/microsoft/vscode/issues/135480#issuecomment-963946617 . Please also see https://github.com/microsoft/vscode/issues/144010#issuecomment-1054320641
