### ISSUE TITLE
Example using MSYS produces no output

### ISSUE THREAD

**Issue by maacl** [microsoft/vscode#144972]
Does this issue occur when all extensions are disabled?: Yes/No - not relevant

- VS Code Version:
Version: 1.65.1 (user setup)
Commit: 8908a9ca0f221f36507231afb39d2d8d1e182702
Date: 2022-03-08T02:06:27.846Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

- OS Version:
OS: Windows_NT x64 10.0.22000

- MSYS Version:
msys2-x86_64-20220128.exe (installer)

- task.json:
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cppbuild",
			"label": "C/C++: g++.exe build active file",
			"command": "C:\\msys64\\mingw64\\bin\\g++.exe",
			"args": [
				"-fdiagnostics-color=always",
				"-g",
				"${file}",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe"
			],
			"options": {
				"cwd": "${fileDirname}"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "compiler: C:\\msys64\\mingw64\\bin\\g++.exe"
		}
	]
}
```

Steps to Reproduce:

1.Follow tutorial to this step https://code.visualstudio.com/docs/cpp/config-mingw#_add-hello-world-source-code
2. Code builds but running resulting exe does not produce any output.
3. If I skip the use of "`using namespace std;`" and prefix all with "`std::`", output is produced as expected.

**Comment by aeschli** [comment]
You need to file this against the c++ extension: https://github.com/Microsoft/vscode-cpptools/issues
