### ISSUE TITLE
snap versions dont open links in default browser profile

### ISSUE THREAD

**Issue by kinghat** [microsoft/vscode#144994]
Issue Type: <b>Bug</b>

with a snap install of stable and insiders, links from within vscode open in the default browser(firefox via flatpak) in a new profile and not the default. other snaps on my system open links in the correct, default profile of my default browser. its frustrating when authenticating things because you are only logged in on your default browser profile.

https://user-images.githubusercontent.com/16073360/158073798-b0e5c37b-1848-49b2-a805-9f384e25199c.mp4

VS Code version: Code - Insiders 1.66.0-insider (6b7453421201c888b81eae5c04ec822a6423608f, 2022-03-11T06:27:47.212Z)
OS version: Linux x64 5.13.0-35-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 1961)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 1, 1|
|Memory (System)|11.57GB (0.59GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 15161101-26f9-4506-af66-9a27612d8292|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vsclayoutctrc:30405799
dsvsc009:30440021
pythonvsnew555:30438690
vscscmwlcmt:30428973
vscgsvid2:30433758
cppdebugcf:30451567
dockersurvey3cf:30438169
pynewfile477:30451556

```

</details>

**Comment by joaomoreno** [comment]
Did you read this? https://github.com/microsoft/vscode/issues/96829
