### ISSUE TITLE
Bad Default/Regression: C++ .h headers colored as C files

### ISSUE THREAD

**Issue by Yelmond** [Microsoft/vscode#145]
The new syntax highlighting in **0.10.0** is great-ish but it seems to have broken all **.h** files in a C++ project as they are defaulted to C syntax which is missing all C++ keywords.

![image](https://cloud.githubusercontent.com/assets/178878/11263299/73207fac-8e57-11e5-9679-b264f538fe51.png)

The vast majority of C++ projects I've worked on or encountered here on Github use .h for their header files and not **.hpp**, **.hh**, or **.hxx**. Even Microsoft-shipped C++ include headers are all **.h**.

Since I cannot change the extensions of my files in any reasonably mature C++ project, I'm left with either modifying the VS Code root installation cpp extension or manually change the syntax highlighting to C++ every time I open a **.h** file. Both of these solutions are not ideal, especially since this was NOT a problem in earlier versions of VS Code.

**Comment by aeschli** [comment]
I now put .h files in the list of cpp file suffixes, in the hope that for colorizing this also works for header files in C programs.
