### ISSUE TITLE
ConfigurationResolverService should ignore some files

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#145049]
1. Have a launch configuration that as a program has a `${file}`
2. Open your file, do some debugging
3. Open the `launch.json` to change some `args`
4. Press F5. Error happens, since `launch.json` is the active editor

I hit this multiple times today and I believe users are hitting this all the time. Probably also for `tasks.json` - would love to hear @alexr00 thoughts.

I am suggesting that the clients can tell the `resolverService` what files to ignore (or what file types). In this example debug would tell the `resolverService` to ignore the `launch.json`. So when `${file}` gets resolved it would get resolved to the previously active editor - ignoring `launch.json`.

fyi @roblourens @connor4312 

Assigning first to @weinand for initial thoughts.

**Comment by weinand** [comment]
I understand the pain point, but I do not like to make the semantics of variables like `${file}` context dependent.

How would the description for `${file}` look like?
![CleanShot 2022-03-15 at 12 10 31@2x](https://user-images.githubusercontent.com/1898161/158365537-497d8053-6440-4ea0-b071-d9143049dc21.png)

What we could do is to introduce a new variable, e.g. "${debuggableFile}".

@alexr00 what do you think?

**Comment by alexr00** [comment]
💯percent agree with not making variables context dependent. Something like `${debuggableFile}` makes sense to me.

**Comment by isidorn** [comment]
I like this approach. Though we would need to market it to our debugger partners that they start generating `launch.json` files with the new variable and to no longer use `${file}`

I would also suggest that the new name is something a bit more generic. Since it would be used for Run, Debug and maybe Tasks?
`${runnableFile}`?

**Comment by weinand** [comment]
I don't think that a single variable should cover both debug and tasks, because that results in the fuzzy semantics.

**Comment by connor4312** [comment]
> Since it would be used for Run, Debug and maybe Tasks? ${runnableFile}?

My initial thought was along these same lines to have `${file}` only be one of the `debuggers.languages`. However, I've seen cases--admittedly edge ones--where users have generated tests that create assertion files which may be plain text, and in order to debug that test case they open the assertion files.

But having a separate `${debuggableFile}` would solve this.

**Comment by roblourens** [comment]
This variable would be a little strange to me, we look backwards in history until we find a file that we can debug? The name should reflect that it's based on history. But it feels weird to press F5 and not necessarily be sure which file it's going to run.

**Comment by weinand** [comment]
@roblourens you are right, a variable based on an editor's access history is strange. A possible name could be `${mostRecentDebuggableFile}` but this sounds really like a kludge...

**Comment by isidorn** [comment]
+1 for `{debuggableFile}`. And how we figure out what is a `debuggableFile` could be improved over time. To start we would look at history but maybe in the future there are better ways to figure this out (by asking the adapter?).
So my point is that looking at the history should not be obvious to the user since we might change this heuristic.

If you really want to make it obvious, here's a name proposal `${lastDebuggableFile}`

**Comment by weinand** [comment]
@isidorn please provide the semantics of `${debuggableFile}` in a simple sentence that we can use for the "Predefined Variables" list (similiar to: "${file} - the current opened file").

**Comment by isidorn** [comment]
`${file}` should be changed to "the current active file"
`${debuggableFile}` should be "One of the open files that can be debugged. Does not have to be the active file."

And I suggest that the heuristic only looks at all the open files.

**Comment by weinand** [comment]
@isidorn thanks for your suggestion
which nicely shows what the problem is:

> ${debuggableFile} One of the open files that can be debugged. Does not have to be the active file.

sounds basically like "opens a random file that can be debugged"

**Comment by roblourens** [comment]
Instead of looking at editor history, it could be "the current file, or the last file that was debugged". But this is still kind of unclear to me.

**Comment by weinand** [comment]
yeah, I was trying to go into the same direction: "the current file, or the last file that was debugged" 
But this introduces state ("last file that was debugged") that is somehow associated with a specific debugger and a debug configuration - too ugly for my taste...
