### ISSUE TITLE
Erro Loading webview for Configure Java Runtime

### ISSUE THREAD

**Issue by Cyclotron555** [microsoft/vscode#145087]
Issue Type: <b>Bug</b>

Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.. 

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (55.18GB free)|
|Process Argv|--crash-reporter-id d29a38dd-ab3f-4799-bf33-a9d1a7bcd2a0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
GetterAndSetterGenerator|afm|1.0.3
jar-builder|asl|1.1.1
bracket-pair-colorizer|Coe|1.0.62
doxdocgen|csc|1.4.0
vscode-lombok|Gab|1.0.1
vscode-pull-request-github|Git|0.38.1
better-cpp-syntax|jef|1.15.13
kite|kit|0.147.0
vscode-github|Kni|0.30.7
kite-snippets-basic|lum|0.0.2
vscode-kite|mrk|0.0.2
csharp|ms-|1.24.1
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.1
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.9.2
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5418
vsliveshare-audio|ms-|0.1.91
sqltools|mtx|0.23.0
java|red|1.4.0
c-cpp-definition-generator|rei|0.0.2
javafx-support|shr|0.0.1
java-generate-setters-getters|soh|7.4.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.0
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmc:30438804
pynewfile477:30450038

```

</details>

**Comment by itomcat666** [comment]
I hava the same problem 0.0...
