### ISSUE TITLE
Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'vscode-webview' is not allowed

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#145093]
- VS Code Version: 1.66.0-insider
- OS Version: MacOS 12.2.1

I try to develop VSCode webview with webpack + HMR. After configure the right CSP, it seems webpack-dev-server can't make a WebSocket Object.

Steps to Reproduce:

1. clone project https://github.com/tjx666/scripting-listener
2. install dependencies by `npm install`
3. open debugger panel, click `Run Extension`
4. go to Extension Development Host workspace
5. open webview panel by call command `Open Scripting Listener Log Viewer`
6. open devtools, will show following screenshot error message

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/158300681-132a3cb4-4c56-4b40-bd19-7b1895c2b81b.png">

I had configured the CSP to allow `ws://localhost:3000`, check details [here](https://github.com/tjx666/scripting-listener/blob/master/src/LogViewer.ts#L56):

```typescript
 private setupHtmlForWebview() {
        const webview = this.panel.webview;
        const nonce = getNonce();
        const isProd = false;
        const localPort = 3000;
        const localServerUrl = `localhost:${localPort}`;
        const scriptRelativePath = 'webview.js';
        const scriptUri = isProd
            ? webview
                  .asWebviewUri(Uri.joinPath(this.extensionUri, 'build', scriptRelativePath))
                  .toString()
            : `http://${localServerUrl}/${scriptRelativePath}`;

        // prettier-ignore
        const csp = [
            `default-src 'none'`,
            `img-src ${webview.cspSource} 'self' 'unsafe-inline'`,
            `script-src ${isProd ? `'nonce-${nonce}'` : `http://${localServerUrl} http://0.0.0.0:${localPort}`} 'unsafe-eval'`,
            `style-src ${webview.cspSource} 'self' 'unsafe-inline'`,
            `font-src ${webview.cspSource}`,
            `connect-src ${isProd ? '' : `ws://${localServerUrl} ws://0.0.0.0:${localPort} http://${localServerUrl} http://0.0.0.0:${localPort}`}`
        ];
        const html = `<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="Content-Security-Policy" content="${csp.join('; ')}">
        <title>Scripting Listener</title>
    </head>
    <body>
        <div id="root"></div>
        <script ${isProd ? `nonce="${nonce}"` : ''} src="${scriptUri}"></script>
    </body>
</html>`;
        this.panel.webview.html = html;
    }

```

**Comment by mjbvz** [comment]
Can you please try putting together a self contained example that clearly demonstrates how the web socket is constructed? I suspect the url for it is getting passed through `asWebviewUri` (either directly or being resolved relative to a script that was). As the error message says, this is not supported

**Comment by tjx666** [comment]
I have fixed it. 
ref: 
1. https://github.com/webpack/webpack-dev-server/issues/4338#event-6250580841
2. https://github.com/tjx666/scripting-listener/commit/34ace884434794db21d4772c6712d3bfd3725de5
