### ISSUE TITLE
only the first command runs when an array is provided to PROMPT_COMMAND

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#145036]
1. set `PROMPT_COMMAND` to `function1;function2` 
2. `function1` and `function2` run ✅ 
3. set `PROMPT_COMMAND` to `(function1 function2)`
4. 🐛  only `function1` runs

**Comment by mjbvz** [comment]
I need additional steps to verify this. I got the first case (`function1;function2`) working under zsh but couldn't get the second working and couldn't get either one working under bash

**Comment by meganrogge** [comment]
PROMPT_COMMAND is only a bash thing. 

Can you pls provide me with the ones that you tried in bash?
