### ISSUE TITLE
Webview: Could not register service workers

### ISSUE THREAD

**Issue by bcanzanella** [microsoft/vscode#145047]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.65.2 (Universal)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Steps to Reproduce:

1. open https://github.com/microsoft/vscode-extension-samples/tree/main/webpack-sample, install, compile, run
2. run `Cat Coding...` 

<img width="2317" alt="Screen Shot 2022-03-14 at 10 56 32 AM" src="https://user-images.githubusercontent.com/834948/158198818-c3462eb9-0dc4-450f-bc38-0120ee980530.png">

**Comment by bcanzanella** [comment]
hmm, ok, now it works... closing.

**Comment by bgryks18** [comment]
how did you solved ?

**Comment by bgryks18** [comment]
I've figured out that why you said "it works" and closed. when i restarted the computer, it's solved. I guess it had exist an temporary error
