### ISSUE TITLE
Intellisense for import-statements --> show folders/files

### ISSUE THREAD

**Issue by mxii** [Microsoft/vscode#14506]
Would be great to get help writing import-statements!

If I am writing this: `import { xxx } from '../zzz/'`

It could/should show all folders/files in `../zzz/`

**Comment by kaiwood** [comment]
This extension does exactly this: https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense

**Comment by mxii** [comment]
Thanks! Will try that extension.. but this feature should be natively supported by vscode. :)

It could/should even suggest possible available packages too..

**Comment by waderyan** [comment]
@mxii thank you for your feedback and I agree with you :) Stay tuned as we're looking into improvements in this and many areas. 

I'll keep this open as a feature request for others to up vote.

**Comment by mjbvz** [comment]
I believe completion for paths was added in vscode 1.8 which shipped with TS 2.1.4:

![jan-25-2017 23-56-30](https://cloud.githubusercontent.com/assets/12821956/22323783/eb2c3d08-e359-11e6-9f4d-3a2eb7a3ef77.gif)

VSCode 1.9 also includes improved icons for these items.
