### ISSUE TITLE
10 bit color depth for theme colors

### ISSUE THREAD

**Issue by bboysnick5** [microsoft/vscode#145010]
Can we add support for 10 bit color depth for theme colors

**Comment by aeschli** [comment]
VS Code is built on Electron/Chromium using HTML and CSS. I don't know how a 10bit+ color would be specified in CSS.

**Comment by bboysnick5** [comment]
Thanks for the comment. I guess we can incoporate CSS color level 4 once it's turned into standard if draft is not an option.
