### ISSUE TITLE
cursorSurroundingLines not working for the notebook

### ISSUE THREAD

**Issue by shah-xad** [microsoft/vscode#145071]
I have set this: `"editor.cursorSurroundingLines": 10,` but, I'm getting a view like this, line 3 is just at the extreme bottom of the screen.
![dsX7u](https://user-images.githubusercontent.com/32363363/157813352-19b90b1d-d47c-49de-a68e-957faae6bb5b.png)

Is there any way to put some fixed space/padding below the current cursor position? In simple I don't want my cursor at the extreme bottom of the screen.

**Comment by greazer** [comment]
This behavior is core VS Code.

**Comment by shah-xad** [comment]
@vscode-triage-bot  bro, shouldn't you mention that issue? BTW happy "boting". :D
