### ISSUE TITLE
Merge conflict markers left in file but hidden by editor (still)

### ISSUE THREAD

**Issue by sayboltm** [microsoft/vscode#145048]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2, commit: 899d46d82

- OS Version: Windows 10 (Windows_NT x64 10.0.18363)

Related issue:
https://github.com/Microsoft/vscode/issues/67959

Steps to Reproduce:

1. Try and resolve a merge conflict in VS Code. Click accept changes, they go away in the editor
2. Open the code in question in any other editor (including Visual Studio) and you will see the arrows are still there!

Here is a screenshot of VSCode on the left and Visual Studio on the right:
![image](https://user-images.githubusercontent.com/25088020/158197431-8482741a-85b9-43d5-9c52-e3ec220ccd38.png)

Opening in Notepad++ or notepad.exe both show the conflict markers still there, it is easy to commit them, and without automated build testing or a pre-commit hook, push the changes and have some conflict markers 3 merge commits deep that is a pain to undo for something so simple.  I LOVE VS Code merge conflict resolution, but I also expect it primarily being a text editor, to render plain text as actual, plain text, and I am quite curious why this happens. Tried restarting, and it still shows them as gone, so there must be some abstraction layer that is not working properly, or the file is not being written, or the status of if the file is being written is not working properly (it shows no unsaved changes, and lets me close without asking). 

This related/near duplicate issue was closed and locked:
https://github.com/Microsoft/vscode/issues/67959

I am also using that Python extension, but also Vim by vscodevim, v1.22.2, C# v1.24.1 by Microsoft, and a Jupyter extension, but the user of !67959 had this issue without these and it seems to have persisted for some time.

**Comment by sayboltm** [comment]
As ducttape, I can use another editor, or run:

`grep -Rniw '<<<<<<< HEAD' ./`

**Comment by sayboltm** [comment]
I am using this as a status indicator of file write:

unsaved changes:
![image](https://user-images.githubusercontent.com/25088020/158206661-1ed34d66-411e-48d9-8eec-47103f613fad.png)

saved:
![image](https://user-images.githubusercontent.com/25088020/158206747-f7d20b0b-f93f-4b36-a567-739d4feec1ac.png)

and at the bottom:
![image](https://user-images.githubusercontent.com/25088020/158206850-9078cedc-20ea-46c2-9ded-5785de4fe6bd.png)

perhaps provided by the VIM plugin

**Comment by sayboltm** [comment]
At this time it appears to be writing and updating statuses just fine. Baffling. But I have seen this before and it undermines my confidence in VSCode (unfortunately, because it is awesome). Are there any steps I should take to try and capture its state?

**Comment by chrmarti** [comment]
When you run the merge actions inside the editor, you then also need to save the file to disk. (Reloading VS Code will preserve the unsaved file's content, but not automatically save it.)

You could enable `File` > `Auto Save`, that will automatically save any changes you make in any editor. (Might be unexpected if you are used to work with unsaved files.)

Does this address your concerns?
