### ISSUE TITLE
Placing 2 letters left on CSS autocomplete

### ISSUE THREAD

**Issue by YaGRRusso** [microsoft/vscode#145099]
When i use autocomplete on CSS the cursor goes 2 steps left.

expect:
background-color: |;
padding: |;
margin: |;

what is happening:
background-colo|r: ;
paddin|g: ;
margi|n: ;

**Comment by DamianAexol** [comment]
I've got the same issue. 

Whenever I write a css and it gets autocompleted cursor is being placed exactly 2 letters on the left.

**Comment by aeschli** [comment]
Please paste the complete sample code... Not just a screenshot.

**Comment by DamianAexol** [comment]
![vscbug](https://user-images.githubusercontent.com/90246296/158619634-f7bdab8f-24e1-44a7-9bfe-f83124c9efc0.gif)

I hope this gif explains everything.

**Comment by DamianAexol** [comment]
I've just realized autocomplete works just fine in normal .css file.

The problem exists while using @emotion/styled

**Comment by aeschli** [comment]
If I understand right, this is when editing in a TypeScript/Java Script file, correct?

**Comment by DamianAexol** [comment]
Yes, You are right. this is a .tsx file with the usage of styled-components.

I'm sorry for not providing all the necessary data. 

Actually its my first time asking for help :)

**Comment by DamianAexol** [comment]
Topic can be closed.

I've changed my extension to the one provided directly by styled-components and everything works good.

Sorry for the problem!

**Comment by matheusf31** [comment]
> When i use autocomplete on CSS the cursor goes 2 steps left.
> 
> expect: background-color: |; padding: |; margin: |;
> 
> what is happening: background-colo|r: ; paddin|g: ; margi|n: ;

You solve this? I have the same problem here
