### ISSUE TITLE
colorized bracket pairs for angle bracket in C++ also colors operators 

### ISSUE THREAD

**Issue by bboysnick5** [microsoft/vscode#145012]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: macOS 12.2.1

For C++ if you set the colorized bracket pair for angle bracket, the operators such as stream operators or less than operator will also be colored. Example
<img width="640" alt="image" src="https://user-images.githubusercontent.com/16312136/158120257-54d2e1d2-cc29-454f-b85d-19e81afa6161.png">

Steps to Reproduce:

1. In settings.json add 
```json
"[cpp]": {
    "editor.defaultFormatter": "ms-vscode.cpptools",
    "editor.language.colorizedBracketPairs": [
      [
        "<",
        ">"
      ]
   ]
}
```

**Comment by Lemmingh** [comment]
/duplicate

This is a known issue. The bracket pair colorization is currently text-based. Please see

* #131412
* #132476
* #144723
* #144736
* ...

**Comment by IllusionMH** [comment]
/duplicate

Thanks @Lemmingh
