### ISSUE TITLE
always jump to a CODE cell by default

### ISSUE THREAD

**Issue by X3vvv** [microsoft/vscode#145039]
when in markdown cell, 

press shift+enter will jump to a new MARKDOWN cell, 

but the expected result is jumping to a CODE CELL.

**Comment by rchiodo** [comment]
Verified Jupyter behaves the way the user is asking for.

If the last cell is a markdown cell and you hit SHIFT+ENTER, it will generate a new 'code' cell and not a new 'markdown' cell.
