### ISSUE TITLE
Windows 7: Watcher fails for subst directories

### ISSUE THREAD

**Issue by DerTolleEmil** [Microsoft/vscode#1450]
I sometimes map a drive letter to a directory using the Windows subst command. However, when I open that drive in VSCode new files (or file/folder deletions outside of the editor) will not get detected. This will also lead to an inconsistent UI when using git because git works just fine but will eventually show deletions and new files that aren't visible in the editor's folder tree.

Opening a folder that is a soft link or a directory junction (both created by mklink.exe) works fine though.

This is on Windows 7 x64 by the way.

**Comment by bpasero** [comment]
This issue was moved to Microsoft/vscode-filewatcher-windows#7
