### ISSUE TITLE
Prevent VSCode from using git repo in parent dirs

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#145066]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.2

I have a git repository in my $HOME directory, which may have modified tracked files. Now whenever I open vscode in a dir that doesn't have a git repo, that repository is in use.

I tried to use different settings but couldn't prevent this from happening. Having a git repo in $HOME dir isn't an uncommon things for us to do, you know, to track dotfiles.

How can I prevent vscode to not look for git repo in the parent directories of the directory I have opened vscode

**Comment by gjsjohnmurray** [comment]
Did you setting `git.autoRepositoryDetection` to `false` or to `subFolders`?

**Comment by frogtile** [comment]
> Did you setting `git.autoRepositoryDetection` to `false` or to `subFolders`?

I tried both, but non of them worked. Currently I have `"git.autoRepositoryDetection": "subFolders"`

**Comment by gjsjohnmurray** [comment]
Is `git.ignoredRepositories` any use?

**Comment by gjsjohnmurray** [comment]
Related - #140800 and #137432
