### ISSUE TITLE
I cannot get menu bar once I have removed it.Like file edit view etc

### ISSUE THREAD

**Issue by prianca2512** [Microsoft/vscode#14507]
- VSCode Version: latest
- OS Version: windows 7

Steps to Reproduce:

1. open VSC and remove the menu bar . 
![capture](https://cloud.githubusercontent.com/assets/13521531/19715270/99080d2a-9b71-11e6-9e81-6197bdfdb1b8.PNG)

2. Now you can nowhere get them back.. PFA

**Comment by weinand** [comment]
@prianca2512 press the 'Alt' key to get the menu bar back.
