### ISSUE TITLE
Explore variations for File > New file and File > New file...

### ISSUE THREAD

**Issue by lychung7** [microsoft/vscode#145046]
This is the current experience in the File menu for creating a new file and we want to explore different variations to improve the UX.
 
<img width="304" alt="Screen Shot 2022-03-14 at 7 52 05 AM" src="https://user-images.githubusercontent.com/60596156/158198134-0f2ba8fa-edbc-4cba-be6e-284752338d81.png">

**Comment by lychung7** [comment]
As a duplicate of _New File_ and _New File..._ in the File menu can be confusing, here are a couple of ideas to distinguish between the two.

<img width="684" alt="Screen Shot 2022-03-15 at 3 13 25 PM" src="https://user-images.githubusercontent.com/60596156/158511710-8daca5a0-55c1-4005-a5e0-f6270af4f15b.png">
 
The first idea on the left is using _New Text File_ and _New Editor..._. There was previous feedback around introducing the term _Editor_  to the File menu and I thought this could distinguish between immediately opening up a file vs. opening up a quick pick of editor options like below. The second idea was to call the two menu items _New Untitled File_ and _New File..._.

![new editor  quick pick](https://user-images.githubusercontent.com/60596156/158511987-8f8c7fb6-230d-4a23-8360-119e53f153c3.png)

Also, to help users not have to switch editors, there is another idea of adding a second entry point in the placeholder text of an empty text file. Clicking on _choose a rich editor_ would open a similar quick pick with editor options. 

![choose a rich editor link](https://user-images.githubusercontent.com/60596156/158513001-c2658598-5dd2-44c5-9ae8-372c3b3941e9.png)

![choose a rich editor link-1](https://user-images.githubusercontent.com/60596156/158512722-90877a0e-2ce6-4633-8b06-edcc111eefd9.png)

**Comment by Zerotask** [comment]
It would be great if VS Code could offer the creation of specific files.
For example I have a PHP project, then a new file is mostly a PHP class which consists of specific content. This menu could then additionally offer me the option `New PHP class`.  If I enter `User`, it would create:

```php
<?php

class User {

}
```

**Comment by AlbertoFabbri93** [comment]
In my opinion option B is more clear.

**Comment by Sukrit303** [comment]
B is more clear.

**Comment by misolori** [comment]
Closing this as complete:

<img width="668" alt="CleanShot 2022-07-25 at 09 03 29@2x" src="https://user-images.githubusercontent.com/35271042/180823668-70960fbf-7c90-4cb5-bb61-7c9a0d8adb00.png">

<img width="290" alt="CleanShot 2022-07-25 at 09 03 39@2x" src="https://user-images.githubusercontent.com/35271042/180823713-c18aab6b-e810-434d-8769-6b3f30786d28.png">

<img width="522" alt="CleanShot 2022-07-25 at 09 04 05@2x" src="https://user-images.githubusercontent.com/35271042/180823825-dc18d73e-e5ab-4dc3-b003-3d728e1e20b7.png">
