### ISSUE TITLE
菜单栏中的自动换行 Alt +z 功能 

### ISSUE THREAD

**Issue by Tools-s7ck** [microsoft/vscode#145070]
我现在的版本是1.65.2
首先感谢 VScode 的开发贡献  ，在使用VScode 过程中 我发现 自动换行功能使用的不便捷 所以我提供以下建议
一，建议在设置勾选 自动换行功能后 我们的每一页代码都是默认自动换行（并且在编辑代码超出边框的时候可以默认取消这个文件的自动换行） 并且在关闭编辑器重新打开后依然是自动换行 直到不需要自动换行手动取消
二，建议这样的自动换行设置可以同步到账号云配置 
谢谢 ，以上是我的个人对自动换行功能的小期许

**Comment by Lemmingh** [comment]
/duplicate

Please see alexdima's explanation under <https://github.com/microsoft/vscode/labels/editor-wrapping>:

* <https://github.com/microsoft/vscode/issues/21124#issuecomment-308644030>
* <https://github.com/microsoft/vscode/issues/103199#issuecomment-686763015>

**Comment by Tools-s7ck** [comment]
OK,&nbsp;thank&nbsp;you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月2日(星期六) 凌晨1:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode] 菜单栏中的自动换行 Alt +z 功能  (Issue #145070)





 
/duplicate
 
Please see alexdima's explanation under https://github.com/microsoft/vscode/labels/editor-wrapping:
  
#21124 (comment)
 
#103199 (comment)
