### ISSUE TITLE
cpptools auto-install windows debuger fail

### ISSUE THREAD

**Issue by mazhan465** [Microsoft/vscode#14503]
Downloading package 'Visual Studio Windows Debugger' (12073 KB) .................... Done!
Downloading package 'C/C++ language components (Windows)' Failed at stage: downloadPackages
Error: write EPROTO 0:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:y:\jenkins\workspace\electron-win-ia32\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:769:

**Comment by weinand** [comment]
In the future please file extensions specific issues against the corresponding extension itself and not against VS Code.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#307
