### ISSUE TITLE
Não consigo escrever nenhum código CSS

### ISSUE THREAD

**Issue by Gstvo-Oliveira** [microsoft/vscode#145081]
Quando começo a escrever, aparece este erro, já tentei desinstalar o programa, mas não resolveu o problema

![Captura de tela 2022-03-14 191611](https://user-images.githubusercontent.com/100328262/158270085-3bd88b3f-6601-4024-b0b2-c7f9998ad19f.png)
.

**Comment by brunovieira97** [comment]
Olá, @Gstvo-Oliveira!

O erro é por que o arquivo CSS é inválido com o conteúdo atual. Ao utilizar `@charset`, tu precisas informar uma string em seguida, como por exemplo `"UTF-8"`. Como isso não foi feito, o CSS é inválido.

Pode continuar a edição sem problemas, quando tu finalizar a edição da linha e adicionar o charset direitinho, ele não vai mais exibir o erro.

**Comment by Gstvo-Oliveira** [comment]
Obrigado!
