### ISSUE TITLE
vscode.env.clipboard new feature suggest

### ISSUE THREAD

**Issue by mmdjiji** [microsoft/vscode#145015]
The requirement is to get the picture or other files from the clipboard, and now we only have the api to get/set the string of clipboard:
```js
vscode.env.clipboard.readText(): Thenable<string>;
vscode.env.clipboard.writeText(value: string): Thenable<void>;
```

So I suggest that add `vscode.env.clipboard.readObject(): Thenable<object>` and every object can be defined as:
```js
{
  type: "image",
  index: "C:\\User\\AppData\\...\\tmp.png"
}
```
or
```js
{
  type: "file",
  index: "C:\\Windows\\System32\\cmd.exe"
}
```

**Comment by Lemmingh** [comment]
#77790

**Comment by mmdjiji** [comment]
Thanks, I goto https://github.com/microsoft/vscode/issues/77790#issuecomment-1066587519
