### ISSUE TITLE
Typescript intellisense performance timeouts/hints

### ISSUE THREAD

**Issue by mataslib** [microsoft/vscode#145030]
I have recently found out, that certain dependency import kills vscode intellisense in my project for some reason (I have to yet investigate reason why - it's local dependency, so issue is on my side - maybe circular dep or smthing). It went from 5 seconds "Loading..." to about 255 seconds "Loading..." waiting for autocomplete dropdown. Hovers also don't work with "Loading...". Due to nature of my "nonstandard" setup, I had no idea what went wrong, did not notice exact time when it started and therefore suspected many things. (wsl2, docker devcontainer, monorepo, wrong configurations...).

Luckily I found this great guide https://github.com/microsoft/TypeScript/wiki/Performance-Tracing which pointed me to two files having mentioned local dependency import, taking about 100 seconds each to compile.  I'm using nextjs devserver so I don't  build with `tsc` (I think nextjs even doesn't use tsc in background - rather swc), editor probably does use `tsc`, therefore I did not suspect typescript to be an issue since devserver worked fine, just autocomplete did not.

I don't like fact, that single dependency import can kill your editor intellisense. You can't even use snippets / text occurence autocomplete. It even stops working for other files too (other than one having problematic import). I can imagine some npm dependency to introduce similar issue "killing" our editors time to time. I don't like fact that due to my local dependency issue, autocomplete for other things, eg. other npm library stops working too.

Could this be improved somehow? Eg. Automagically performing performance tracing in background and throwing alerts in editor for problematic files. Or getting just partial intellisense while timeouting bad performing files. Waiting 200+ secs for autocomplete dropdown is nonsense.

**Comment by mjbvz** [comment]
Please file this against the TypeScript project with an example project demonstrating the issue
