### ISSUE TITLE
Emmet i completion inside anchor

### ISSUE THREAD

**Issue by Vernando05** [Microsoft/vscode#14504]
- VSCode Version: 1.6.1
- OS Version: Windows 7 Ultimate SP1

Steps to Reproduce:
1. Set language to handlebars or HTML
2. Emmet is working for a>i  but not for `<a href="">i (hit tab)</a>`

**Comment by mrmlnc** [comment]
Hello, @Vernando05,

It's works fine in VS Code 1.7.1.

![2016-11-04_15-25-34](https://cloud.githubusercontent.com/assets/7034281/20005375/f4cbc6d2-a2a2-11e6-8a81-731a8fcd909f.gif)

I think that this Issue related to https://github.com/Microsoft/vscode/issues/5427.

**Comment by Vernando05** [comment]
Yep it's related, I need to escape from anchor first to enable i completion, if this is expected behaviour, I think it's resolved.
