### ISSUE TITLE
Problem syncing

### ISSUE THREAD

**Issue by gilberto-sassi** [microsoft/vscode#145031]
Issue Type: <b>Bug</b>

I can't sync visual studio code with github account using the account button.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.15.25-1-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.47GB (5.90GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id fded02a1-f2b9-4a2e-a027-58fdffb3b31e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasmawayland|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by TylerLeonhardt** [comment]
do you have a libsecret based application installed like gnome-keyring?

If you don't, installing gnome-keyring should fix this for you you.

If it does, I'm curious to ask... did vscode force you to log into your accounts every time you opened it before 1.65?

**Comment by gilberto-sassi** [comment]
It worked!

I installed gnome-keyring and issue was solved.

Thank you!
