### ISSUE TITLE
Insiders Go to Definition (Cmd + Click) not working 

### ISSUE THREAD

**Issue by dcavanagh** [microsoft/vscode#145075]
Issue Type: <b>Bug</b>

Pressing cmd and clicking on a method or variable name does not bring you to the definition

VS Code version: Code - Insiders 1.66.0-insider (3e5c7e2c570a729e664253baceaf443b69e82da6, 2022-03-14T05:15:31.903Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 6, 5|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|-psn_0_27576907 --crash-reporter-id fb8f44c2-138a-4c04-b718-84d42eb848d5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
ng-template|Ang|13.2.6
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.4
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
vscode-peacock|joh|4.0.0
git-graph|mhu|1.30.0
sort-typescript-imports|mic|1.4.1
vscode-docker|ms-|1.20.0
cpptools|ms-|1.9.3
vsliveshare|ms-|1.0.5418
indent-rainbow|ode|8.2.2
material-icon-theme|PKi|4.14.1
tsimporter|pmn|2.0.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vsclayoutctrt:30405800
dsvsc009:30440021
pythonvsnew555:30438690
vscscmwlcmt:30428973
vscgsvidc:30433759
dockersurvey3cf:30438169
vscaac:30438845
pynewfile477:30451556

```

</details>

**Comment by mjbvz** [comment]
What language is this for? Please share steps to reproduce the issue /needsMoreInfo

**Comment by dcavanagh** [comment]
@mjbvz It is happening in all languages. I tried Typescript, Javascript, javascript in html file and Python

Open vscode insiders in new workspace
disable all extensions
create file test.js with 
```javascript
function test() {}

test();
```
press and hold cmd and click on the `test()` call.  
Nothing happens

expected behavior is that it would open the window showing the definition or take you to the definition

same result for Typescript 
```Typescript
function testTS() {}

testTS();
```

same result for python

```
def test():
  print 'test'

test()
```

**Comment by mjbvz** [comment]
What if you run `go to definition` from the command palette or by pressing `f12`?

**Comment by dcavanagh** [comment]
@mjbvz pressing f12 works, command palette, works, and right clicking and selecting go to definition works

**Comment by mjbvz** [comment]
Have you changed `editor.multiCursorModifier` so that cmd+click creates a new cursor instead?

**Comment by dcavanagh** [comment]
That was it. Thank you for the help
