### ISSUE TITLE
Update Swift grammar from https://github.com/textmate/swift.tmbundle/blob/master/Syntaxes/Swift.tmLanguage

### ISSUE THREAD

**Issue by DavidGoldman** [microsoft/vscode#145056]
The grammar at https://github.com/textmate/swift.tmbundle/blob/master/Syntaxes/Swift.tmLanguage has been recently updated, please pull the changes back into VS Code. Thanks!

**Comment by DavidGoldman** [comment]
@alexr00 are you still the right person for this?

**Comment by alexr00** [comment]
Done, thanks for the ping! 57f776891738fbc70388baf541afcbba1c1bdc8c
