### ISSUE TITLE
Warning: could not download https://pkg.julialang.org/registries

### ISSUE THREAD

**Issue by HerClau** [microsoft/vscode#145057]
julia> VERSION
v"1.7.2"

(@v1.7) pkg> up

Installing known registries into `C:\Users\Hermesr\.julia`
┌ Warning: could not download https://pkg.julialang.org/registries
│   exception = schannel: failed to receive handshake, SSL/TLS connection failed while requesting https://pkg.julialang.org/registries
└ @ Pkg.Registry C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:82
┌ Warning: could not download https://pkg.julialang.org/registries
│   exception = schannel: failed to receive handshake, SSL/TLS connection failed while requesting https://pkg.julialang.org/registries
└ @ Pkg.Registry C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:82
     Cloning registry from "https://github.com/JuliaRegistries/General.git"
ERROR: failed to clone from https://github.com/JuliaRegistries/General.git, error: GitError(Code:ERROR, Class:OS, failed to send request: The connection with the server was terminated abnormally
)

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please specify how this is related to VS Code editor itself

**Comment by HerClau** [comment]
System information
CPUs	Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)
GPU Status	2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg)	
Memory (System)	7.89GB (3.26GB free)
Process Argv	--crash-reporter-id a7784d60-886f-4cdf-ace9-54ad361b7c25
Screen Reader	no
VM	0%

Enable Extension:
Extension	Author (truncated)	Version
easy-cpp-projects	ACh	2.0.0
include-autocomplete	ajs	0.0.4
markdown-julia	col	0.0.1
doxdocgen	csc	1.4.0
c-cpp-compile-run	dan	1.0.15
code-runner	for	0.11.7
vscode-pull-request-github	Git	0.38.1
python-in-julia	hab	0.1.0
CppSnippets	har	0.0.15
better-cpp-syntax	jef	1.15.13
language-julia	jul	1.5.11
ccpp-extension-pack	Leo	1.1.0
vscode-clangd	llv	0.1.15
theme-monokai-pro-vscode	mon	1.1.20
python	ms-	2022.2.1924087327
vscode-pylance	ms-	2022.3.1
jupyter	ms-	2022.2.1030672458
jupyter-keymap	ms-	1.0.0
jupyter-renderers	ms-	1.0.6
remote-containers	ms-	0.224.2
remote-ssh	ms-	0.76.1
remote-ssh-edit	ms-	0.76.1
remote-wsl	ms-	0.64.2
cmake-tools	ms-	1.9.2
cpptools	ms-	1.8.4
cpptools-extension-pack	ms-	1.1.0
vsliveshare	ms-	1.0.5418
vsliveshare-audio	ms-	0.1.91
material-icon-theme	PKi	4.14.1
vscode-julia-formatter	sin	0.6.3
pdf	tom	1.2.0
cmake	twx	0.0.17
vscode-icons	vsc	11.10.0
(4 theme extensions excluded)

A/B experiment
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrc:30451274
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmt:30438805
pynewfile477:30450038

**Comment by IllusionMH** [comment]
That doesn't answer to question how it's VS Code bug. Sounds like extension issue or some misconfiguration. VS Code by itself doesn't support and download anything from julia registry, but extensions can.
Please provide proper steps to reproduce this issue.

**Comment by HerClau** [comment]
From the VSCode terminal in the Julia REP, when typing in (@v1.7) pkg> up
those alerts appear.
I think it's Julia protocol problem when trying to access the github.com/JuliaRegistries/General.git server.
  I say this because I manage to install VScode AND R packages from my server
These same steps performed in Julia give the following alert: 

~~~
julia> Pkg.add("Plots")
  Installing known registries into `C:\Users\Hermesr\.julia`
┌ Warning: could not download https://pkg.julialang.org/registries
│   exception = Failed to connect to pkg.julialang.org port 443: Timed out while requesting https://pkg.julialang.org/registries
└ @ Pkg.Registry C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:82
┌ Warning: could not download https://pkg.julialang.org/registries
│   exception = Failed to connect to pkg.julialang.org port 443: Timed out while requesting https://pkg.julialang.org/registries
└ @ Pkg.Registry C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:82
     Cloning registry from "https://github.com/JuliaRegistries/General.git"
ERROR: failed to clone from https://github.com/JuliaRegistries/General.git, error: GitError(Code:ERROR, Class:OS, failed to send request: The operation timed out
)
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types C:\Users\Hermesr\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\Types.jl:68
  [2] clone(io::Base.TTY, url::String, source_path::String; header::String, credentials::Nothing, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.GitTools C:\Users\Hermesr\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\GitTools.jl:126
  [3] (::Pkg.Registry.var"#38#40"{Base.TTY, String, Pkg.Registry.RegistrySpec, Nothing})(tmp::String)
    @ Pkg.Registry C:\Users\Hermesr\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:224
  [4] mktempdir(fn::Pkg.Registry.var"#38#40"{Base.TTY, String, Pkg.Registry.RegistrySpec, Nothing}, parent::String; prefix::String)
    @ Base.Filesystem .\file.jl:750
  [5] mktempdir(fn::Function, parent::String) (repeats 2 times)
    @ Base.Filesystem .\file.jl:748
  [6] download_registries(io::Base.TTY, regs::Vector{Pkg.Registry.RegistrySpec}, depot::String)
    @ Pkg.Registry C:\Users\Hermesr\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:194
  [7] download_registries
    @ C:\Users\Hermesr\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:166 [inlined]
  [8] download_default_registries(io::Base.TTY; only_if_empty::Bool)
    @ Pkg.Registry C:\Users\Hermesr\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:113
  [9] download_default_registries
    @ C:\Users\Hermesr\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:101 [inlined]
 [10] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API C:\Users\Hermesr\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\API.jl:144
 [11] add(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API C:\Users\Hermesr\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\API.jl:144
 [12] #add#27
    @ C:\Users\Hermesr\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\API.jl:142 [inlined]
 [13] add
    @ C:\Users\Hermesr\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\API.jl:142 [inlined]
 [14] #add#26
    @ C:\Users\Hermesr\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\API.jl:141 [inlined]
 [15] add(pkg::String)
    @ Pkg.API C:\Users\Hermesr\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\API.jl:141
 [16] top-level scope
    @ REPL[3]:1

caused by: GitError(Code:ERROR, Class:OS, failed to send request: The operation timed out
)
~~~

**Comment by rebornix** [comment]
Please file against the Julia extension.
