### ISSUE TITLE
Unresponsive mouse scroll wheel

### ISSUE THREAD

**Issue by Spacew1se** [microsoft/vscode#145001]
Issue Type: <b>Bug</b>

When scrolling in any window in vscode with the mouse wheel, the scrolling is unpredictably unresponsive, sometimes taking 3 or 4 scrolls to actually register one. This does not happen in the OS or in any other programs I have tested. I am using vscode on xubuntu in a vm on windows 10. Again, this problem does not happen in the host or guest OS, or in any program in either OS I have used except vscode. This leads me to believe it is a bug in vscode. It is frustrating to the point of being unusable. 

Edit: upon further inspection it appears this happens in all chromium apps, not just vscode. The scroll wheel does not work while the mouse is moving. I was able to resolve this by changing the mouse input driver from libinput to evdev, then installing imwheel and using it to intercept the scroll wheel input. With those changes, everything works as it should as far as I can tell

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.13.0-35-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900KF CPU @ 3.70GHz (2 x 3695)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|5.76GB (3.55GB free)|
|Process Argv|--crash-reporter-id 009f85f1-1f69-4664-a48a-67147b82482b|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by deepak1556** [comment]
Closing since there is a workaround and issue needs to be filed against Chromium using specific hardware.
