### ISSUE TITLE
Webviews do not respect `"workbench.editor.openSideBySideDirection": "down"`

### ISSUE THREAD

**Issue by gls7** [microsoft/vscode#145084]
Until I updated to 1.65.1 last week it was working. I just updated to 1.65.2 and still it's a problem.

To reproduce:

I am running a query using SQL Server (mssql) v1.13.0

When the query executes it opens a new panel and shows the results

The new panel is on the right side of the workspace
![image](https://user-images.githubusercontent.com/4521044/158270332-442893a4-8cde-42a2-8cd3-bd9a038cc788.png)

It should display at the bottom of the workspace (I have to _Flip Layout_ to make it right)
![image](https://user-images.githubusercontent.com/4521044/158270427-fb594c06-efe4-4815-9d8b-fb768b257ba6.png)

I duplicated the problem with all extensions disabled (and restart) except the Sql Server extension

Version: 1.65.2 (system setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by bpasero** [comment]
Maybe a bit too soon, this could be a webview issue. Moving to Matt.

**Comment by bpasero** [comment]
Yes, this is wrong:

https://github.com/microsoft/vscode/blob/95ba1e1b4746766fa20f9a97338321bd3bfeb519/src/vs/workbench/api/browser/mainThreadWebviewPanels.ts#L232-L234

Good version that you should be using:

https://github.com/microsoft/vscode/blob/6c89a38cfcc8d6ae4b4804302b709f5256e4a02b/src/vs/workbench/services/editor/common/editorGroupFinder.ts#L69-L80

**Comment by mjbvz** [comment]
Thanks for identifying the problem and for the suggested fix @bpasero!
