### ISSUE TITLE
VS code not able to launch after installed

### ISSUE THREAD

**Issue by SusanYong123** [Microsoft/vscode#14505]
- VSCode Version: 1.6.1.0
- OS Version: Windows 7

Steps to Reproduce:
1. Download VS code from https://code.visualstudio.com/docs/?dv=win
2. after installed, click on VS code, but nothing happen.
3. Try to un-install and error occurs while reinstalling

**Comment by joaomoreno** [comment]
It would be great if you could show us the error, at least a screenshot.

**Comment by FirePho** [comment]
VSCode Version: 1.6.0
OS Version: Windows 10 

I have the same problem since version 1.6.0
Nothing happens at all, there are no errors.

![image](https://cloud.githubusercontent.com/assets/1927599/20025525/29f2798e-a300-11e6-93da-5cf85a89c704.png)

I tried builds source and got an error:

![image](https://cloud.githubusercontent.com/assets/1927599/20025557/6f6b81a4-a300-11e6-9140-bbb3ffaee6f7.png)

**Comment by joaomoreno** [comment]
@FirePho Did it work with 1.5?

And can you run the barebones Electron build?

https://github.com/electron/electron/releases/download/v1.3.7/electron-v1.3.7-win32-ia32.zip
https://github.com/electron/electron/releases/download/v1.3.8/electron-v1.3.8-win32-ia32.zip

**Comment by FirePho** [comment]
Versions 1.5.* work perfectly.

The barebones Electron work too.
![image](https://cloud.githubusercontent.com/assets/1927599/20071848/3381cc1e-a537-11e6-80ed-2a3eaad99c31.png)

I tried to change "electronVersion" in package.json and for versions 1.2.0 - 1.4.5 I receive error from previous message. For versions < 1.2.0 behavior as shown on screenshot

![image](https://cloud.githubusercontent.com/assets/1927599/20072902/501a0afe-a53b-11e6-8095-6c1d04a580a6.png)
![image](https://cloud.githubusercontent.com/assets/1927599/20072934/67bbc7b0-a53b-11e6-9d47-b76206c5a712.png)

I get this error even in other 2 pc

**Comment by joaomoreno** [comment]
Does it also happen when running straight from the archive release, without installing? https://vscode-update.azurewebsites.net/latest/win32-archive/stable

**Comment by FirePho** [comment]
Nothing happens, as well as the version 1.6

**Comment by joaomoreno** [comment]
And if you start `Code.exe`, from the archive, from the Command Line?

**Comment by FirePho** [comment]
I did so, 
![image](https://cloud.githubusercontent.com/assets/1927599/20091851/ff49e926-a5a5-11e6-8833-5e10403208fa.png)

**Comment by joaomoreno** [comment]
And, using a process monitor, do you see any Code.exe processes laying around?

Also, any output when running `Code.exe --verbose`?

**Comment by FirePho** [comment]
![image](https://cloud.githubusercontent.com/assets/1927599/20115066/e94a1738-a607-11e6-8af8-6cc7219ce111.png)

Code.exe process appears for a moment and terminated

![image](https://cloud.githubusercontent.com/assets/1927599/20115845/e9adef9e-a60a-11e6-8cdf-5cf22e522f2e.png)

![image](https://cloud.githubusercontent.com/assets/1927599/20116306/cb39bca8-a60c-11e6-98f9-228d652d9fd7.png)

![image](https://cloud.githubusercontent.com/assets/1927599/20116343/f13f9a4e-a60c-11e6-97a3-0fe1e271feae.png)

**Comment by FirePho** [comment]
Exit code -1073741819(C0000005) says that there was an access violation exception

**Comment by joaomoreno** [comment]
@bpasero any ideas?

**Comment by bpasero** [comment]
@FirePho are you running inside a VM?

**Comment by FirePho** [comment]
No, on host OS.

**Comment by bpasero** [comment]
@FirePho it does reproduce in 1.6 right?

**Comment by FirePho** [comment]
Right! From version 1.6 it reproduce, even 1.8.

**Comment by bpasero** [comment]
Sounds very much like a problem with our Electron update in 1.6.

**Comment by bpasero** [comment]
@FirePho does your OS run in english locale or any other?

**Comment by FirePho** [comment]
I have 2 configuration where it is reproduced: 
- Russian language, Russian format 
- English language, Russian format
![image](https://cloud.githubusercontent.com/assets/1927599/20138213/25619f74-a690-11e6-9a51-8c6a5adefec1.png)

**Comment by FirePho** [comment]
I tried to debug Сode.exe and saw that assemblies from "Cryptopack" for OpenVPN loading into process. I just deleted "СryptoPack" and it worked.

![image](https://cloud.githubusercontent.com/assets/1927599/20154595/20f850d8-a6d9-11e6-98cd-3397fca47668.png)

**Comment by bpasero** [comment]
@FirePho this issue is resolved for you, Code opens?

**Comment by FirePho** [comment]
@bpasero Yes, for me the issue is resolved.

**Comment by bpasero** [comment]
@FirePho thanks, we should keep this in mind when we get similar reports like that.

**Comment by joaomoreno** [comment]
Great catch, @FirePho!
