### ISSUE TITLE
Typescript engine failure

### ISSUE THREAD

**Issue by horlorlahdeh** [microsoft/vscode#145021]
Issue Type: <b>Bug</b>

I leave my VS Code idle after restarting my Mac and it just happens.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 20.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|8.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 776ec741-7977-45c8-ad41-a9f7493e0498|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-zipfs|arc|2.3.0
better-toml|bun|0.3.2
npm-intellisense|chr|1.4.1
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.2
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|1.11.0
vscode-npm-script|eg2|0.3.24
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|9.3.0
vscode-express-snippets|Exp|1.1.1
auto-rename-tag|for|0.1.10
copilot|Git|1.7.5250
HTML-Classes|mik|1.0.6
HTMLHint|mka|0.10.0
vsliveshare|ms-|1.0.5418
vscode-react-native|msj|1.9.2
vetur|oct|0.35.0
LiveServer|rit|5.7.5
autoimport|ste|1.5.4
ejs-snippets|Tao|0.1.0
quokka-vscode|Wal|1.0.450
vscode-webhint|web|1.6.5
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmt:30438805
cppdebug:30451566
dockersurvey3:30446832
pynewfile477:30450038

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by nati-maskens** [comment]
Maybe related: #145309

**Comment by mjbvz** [comment]
Closing as we need more info from the original poster
