### ISSUE TITLE
Disabled Code Actions do not show disabled reason in menu

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#145058]
If an extension provides a disabled reason for a Code Action, it renders disabled in the menu, but there's no tooltip to show the reason to the user.

<img width="418" alt="Screenshot 2022-03-14 at 16 34 37" src="https://user-images.githubusercontent.com/1078012/158218498-37731f0f-3ffc-4853-a460-b142c2fef114.png">

This is rather confusing. The server has done the work to explain why it's not available to the user - it seems like it should be accessible on the main refactoring menu somewhere.

**Comment by justschen** [comment]
@DanTup Feature can now be previewed in Insiders!  Make sure that `editor.contrib.experimental.codeActionWidget.enabled` is set to true, and the setting can also be enabled by going to Editor › Experimental: Use Custom Code Action Menu!

![image 9](https://user-images.githubusercontent.com/54879025/182679560-97474c47-c776-4c41-845a-461a654c9045.png)
