### ISSUE TITLE
Goto Definition Not Working PHP

### ISSUE THREAD

**Issue by trooperken** [microsoft/vscode#145041]
Issue Type: <b>Bug</b>

Goto Definition and Peek Not Working PHP. 
Have tried:
1) Disabling extensions
2) New Workspace
3) Adding PHP executable to Path (winodws)
4) Adding PHP executable to VSCode JSON Settings
5) Restarting VSCode..

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (1.69GB free)|
|Process Argv|--crash-reporter-id c3376a25-165a-46be-8535-7e385ac2fdb0|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmt:30438805
vscgsvid1:30447480
cppdebug:30451566
vscaac:30438847
pynewfile477cf:30450039

```

</details>

**Comment by roblourens** [comment]
This is not supported by our simple builtin PHP support, you need an extension
