### ISSUE TITLE
Please remove unnecessary UI effects

### ISSUE THREAD

**Issue by mdogancay** [microsoft/vscode#145014]
Issue Type: <b>Performance Issue</b>

Hi,
Please remove unnecessary UI effects from vscode. For example on the OUTLINE, "Collapse all" and options buttons only visible if mouse over the OUTLINE tab. it's unnecessary and wasting the CPU time. Remove all effects like this.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.13.0-27-generic
Restricted Mode: No

**Comment by mdogancay** [comment]
> 

Thanks for advice, could some way to disable all this taste? like windows performance or beauty selection on system settings?
I think this will be a good for everyone

**Comment by mdogancay** [comment]
> It's more about personal taste. I recommend that you tune workbench settings to meet your needs.
> 
> ```
> workbench.view.alwaysShowHeaderActions
> workbench.tree.renderIndentGuides
> workbench.reduceMotion
> ```

Thanks for advice, could some way to disable all this taste? like windows performance or beauty selection on system settings?
I think this will be a good for everyone

**Comment by misolori** [comment]
This issue is covered by https://github.com/microsoft/vscode/issues/46403 where it will allow users to hide these actions, closing as duplicate.
