### ISSUE TITLE
Terminal in the editor area has decorations clipped 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#145044]
![Screen Shot 2022-03-14 at 10 35 59 AM](https://user-images.githubusercontent.com/29464607/158194616-1379a644-fee5-4979-a6b7-c358b8358dde.png)

**Comment by meganrogge** [comment]
fixed by setting a `margin-left` of `10px`, but then the scrollbar is partially obscured

**Comment by meganrogge** [comment]
`$('.integrated-terminal.shell-integration .xterm')` has left padding of `20px` applied which seems to make the difference. That element doesn't exist when the terminal is in the editor area
![Screen Shot 2022-03-14 at 10 43 40 AM](https://user-images.githubusercontent.com/29464607/158196047-be34690a-f52a-4215-91f9-614e369878d2.png)

**Comment by Tyriar** [comment]
Let's add a selector to the 20px rule for `.monaco-workbench .editor-instance .xterm`
