### ISSUE TITLE
VSCode freezes while scrolling through C++ code

### ISSUE THREAD

**Issue by evdenaxas** [microsoft/vscode#145032]
Issue Type: <b>Performance Issue</b>

Frequencly vscode will just freeze for 2 seconds when browsing through the code. Nothing in particular is happening so I am not sure how to repro this. Some times it even pops up the message that the window is unresponsive and I have to close it and restart it. 

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.14.0-1027-oem
Restricted Mode: No
Remote OS version: Linux x64 5.14.0-1027-oem

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 4|
|Memory (System)|62.52GB (19.59GB free)|
|Process Argv|--unity-launch --crash-reporter-id 6c529226-9ade-46f9-9f8f-605035834569|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Container |
|OS|Linux x64 5.14.0-1027-oem|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|Memory (System)|62.52GB (19.59GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.2
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
idl|myt|0.3.1
vscode-bazel|Baz|0.5.0
doxdocgen|csc|1.4.0
vscode-docker|ms-|1.20.0
cpptools|ms-|1.8.4
vscode-protolint|ple|0.6.0
vscode-yaml|red|1.5.1
vscode-proto3|zxh|0.5.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
testflightcf:30433671
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmc:30438804
vscgsvidc:30447482
pynewfile477cf:30450039

```

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by evdenaxas** [comment]
@bpasero code-insiders for me opens and crashes immediately with no errors. Cannot repro with it.

**Comment by evdenaxas** [comment]
Is there any way I can collect any data from my side?

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by bpasero** [comment]
@deepak1556 can you check on the provided crash, looks like it could originate from the Electron 17 update.

**Comment by deepak1556** [comment]
@evdenaxas are you running on wayland session ?

**Comment by evdenaxas** [comment]
@deepak1556 I do not know what that is. So, no?

**Comment by deepak1556** [comment]
Can you provide the output of `code-insiders --verbose`

**Comment by evdenaxas** [comment]
[code_insiders.log](https://github.com/microsoft/vscode/files/8246865/code_insiders.log)

**Comment by evdenaxas** [comment]
echo output: $XDG_SESSION_TYPE
x11

**Comment by evdenaxas** [comment]
code-insiders --disable-gpu also crashes.

**Comment by deepak1556** [comment]
Can you provide the output of `code-insiders --disable-gpu --verbose`

**Comment by deepak1556** [comment]
Can you also check if the crash happens with snap installation of `code-insiders` ?
