### ISSUE TITLE
High CPU usage caused by listener leak

### ISSUE THREAD

**Issue by lufixSch** [microsoft/vscode#145063]
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected:
Working on python files in VSCode with a CPU usage of about 5%

Acutal:
CPU usage increases at random times when working in a python environment. While working on a python file or jupyter notebook (The problem seems to appear mor often with Jupyter) at some point the CPU usage is increasing up to 100% percent. This is accompanied by a spawning of a large ammount of Python3.9 Processes.

Sometimes linting errors and warnings of python libraries pop up in the "Problems" section. 

By deactivating Pycodestyle with `"python.linting.pycodestyleEnabled": false,` the CPU usage decreases to about 50% and the proccesses causing the problem are now called "Electron".

<img width="993" alt="Bildschirmfoto 2022-03-11 um 13 03 42" src="https://user-images.githubusercontent.com/62517060/157866475-8429c586-0826-4ea8-b4eb-f9460df7b2f7.png">

From the console of the developer tools i got the following warning:

```
[9a6] potential listener LEAK detected, having 26223 listeners already. MOST frequent listener (26047):
check @ workbench.desktop.main.js:65
check @ workbench.desktop.main.js:65
​ Error
    at Function.create (workbench.desktop.main.js:65)
    at r._event._event [as onDidChange] (workbench.desktop.main.js:67)
    at Y (workbench.desktop.main.js:731)
    at new Ti (workbench.desktop.main.js:731)
    at K (workbench.desktop.main.js:731)
    at workbench.desktop.main.js:731
    at f.invoke (workbench.desktop.main.js:67)
    at c.fire (workbench.desktop.main.js:67)
    at f.createModel (workbench.desktop.main.js:731)
    at qi.doCreateTextEditorModel (workbench.desktop.main.js:1551)
    at qi.createTextEditorModel (workbench.desktop.main.js:1551)
    at qi.doCreateTextModel (workbench.desktop.main.js:2399)
    at qi.resolveFromContent (workbench.desktop.main.js:2399)
    at qi.resolveFromFile (workbench.desktop.main.js:2399)
    at async l.doResolve (workbench.desktop.main.js:2410)
    at async h.acquire (workbench.desktop.main.js:17)
    at async d.createModelReference (workbench.desktop.main.js:2399)
    at async s._handleAsResourceInput (workbench.desktop.main.js:2404)
    at async s.$tryOpenDocument (workbench.desktop.main.js:2404)
```

## Steps to reproduce:

1. Installing Python Extension
2. Open Python file ore Jupyter Notebook
3. Wait ... (takes between 1h and 10min)
4. CPU usage will increase and VSCode becomes unusuable.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.4
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: false
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "autopep8"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: ["pythonDeprecatePythonPath"]

insidersChannel: "off"

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2022.2.1924087327
VS Code version: Code 1.65.1 (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:20:11.670Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 10, 8|
|Memory (System)|16.00GB (2.86GB free)|
|Process Argv|--enable-proposed-api genuitecllc.codetogether --crash-reporter-id 241d8245-9a74-481c-972a-11ed265f23fe|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30440023
pythonvsnew555:30450902
vscscmwlcmc:30438804
vscgsvidc:30447482
pynewfile477cf:30450039

```

</details>

**Comment by lufixSch** [comment]
> I can understand the python processes being launched, but we don't create listeners for that case.

Okay I understand. Just to make sure I want to clarify, that I only get this problem when working on python projects.

**Comment by Bovey0809** [comment]
Thanks a lot for proving such hint, after I disable the lint in Python.settings, the CPU became normal. Now I can code!

**Comment by karthiknadig** [comment]
We now have linting over LSP, for `pylint` and `flake8`. They are available as separate extensions from marketplace. The way we launched python for linting will soon be replaced with linting over LSP.
