### ISSUE TITLE
Errors doesnt show up

### ISSUE THREAD

**Issue by Playyer96** [Microsoft/vscode#14502]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: ms-vscode.csharp-1.4.1, ms-vscode.mono-debug-0.11.0, ms-vscode.Theme-MaterialKit-0.1.1, PKief.material-icon-theme-1.1.3, robertohuertasm.vscode-icons-3.0.6, Unity.unity-debug-1.1.0

Steps to Reproduce:
1. I can see my mistakes for a couple of seconds and the they disappeare.

**Comment by sandy081** [comment]
@Playyer96 Can you please let me know what errors are those, where are they coming from, and where are you seeing them?

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this.

@Playyer96 If you are still seeing this in VSCode 1.8.1, please provide the information sandy081 requested so that we can investigate. 

Thanks
