### ISSUE TITLE
builtin git extension API should also expose revert()

### ISSUE THREAD

**Issue by sbresin** [microsoft/vscode#145028]
The built-in git extension exposes methods for most of the base git operations.
Unfortunately not `revert()`, which would be used to unstage changes.

Could easily be added to `extensions/git/src/api/api1.ts`, i'll open a PR for this sometime today.

**Comment by lszomoru** [comment]
@joaomoreno, could you verify this by reviewing https://github.com/microsoft/vscode/pull/145029?
