### ISSUE TITLE
Shortcut for "Copy Relative Path (Alt + Ctrl + Shift + C)" is not Working

### ISSUE THREAD

**Issue by nicolaslima321** [microsoft/vscode#145076]
Issue Type: <b>Bug</b>

Hello there!

I can't copy the relative path from a file through shortcut "Alt + Ctrl + Shift + C", only through right click, then clicking in the menu option.

I looked at https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-generic-keybindings but I trust these cases is not appliable for me

If possible, I would appreciate to solve this problem :)

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.13.0-30-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|15.53GB (1.03GB free)|
|Process Argv|. --crash-reporter-id c46fed50-e32c-4433-a003-bb223a23024c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by tanhakabir** [comment]
Could you share with us a gif of what you see?

And why was https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-generic-keybindings not helpful for you?

/gifPlease
