### ISSUE TITLE
Add a filter mechanism for branches in the source control view

### ISSUE THREAD

**Issue by SloppyCoderAtWork** [microsoft/vscode#145055]
<img width="551" alt="image" src="https://user-images.githubusercontent.com/70450971/158208027-1e8d55b4-f2d0-4258-9d33-91052f0960ca.png">
It would be nice to have a possibility to filter the displayed branches that shall be displayed in the REMOTES row. If you are working on a project with many developers and there will inevitably a large amount of feature and bug-fix branches present at a specific point in time. If you create a new feature branch for yourself to work on, it is sometimes very hard to find your branch from the myriad of all the other branches.

**Comment by gjsjohnmurray** [comment]
I think those views are provided by an extension (probably GitLens) rather than by the core VS Code product. Please raise the issue with the extension author.

**Comment by lszomoru** [comment]
That is correct. The `Branches` and `Remotes` views are being provided by [the GitLens extension](https://github.com/gitkraken/vscode-gitlens).
