### ISSUE TITLE
Corrupted Software after update

### ISSUE THREAD

**Issue by guillaumearnx** [microsoft/vscode#145083]
Does this issue occur when all extensions are disabled?: Can't Test

- VS Code Version: Latest
- OS Version: Windows 10 21H2

Steps to Reproduce:

1. Close VSCode

For a few weeks, when closing visual studio code, I have an up-to-date window appearing randomly.
When it appears, the update does not complete (error) and I can no longer start VSCode. I have to reinstall it. 

Error after update :

![image](https://user-images.githubusercontent.com/37373941/158271080-cadbe354-be1d-46f7-9182-d5e60c487045.png)

Uptodate popup :

![image](https://user-images.githubusercontent.com/37373941/158271115-9a337d08-13b8-41bc-a2c4-a63f4fcab01d.png)

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
