### ISSUE TITLE
executeTask doesn't seem to execute the task it is directly given

### ISSUE THREAD

**Issue by michaeljones** [microsoft/vscode#145065]
Issue Type: <b>Bug</b>

# Steps

- Clone vscode-extension-samples repository and pull down this pull request: https://github.com/microsoft/vscode-extension-samples/pull/573
- `cd  task-provider-sample`
- `npm install`
- `npm run compile`
- Load VS Code
- Run 'Debug extension'
- Run the command 'Example: Custom task' from the command palette
- Observe the output

# Expected
The output in the terminal should include 'command' as the 'Example: Custom task' command runs a new Task which inserts the string 'command 'into the output.

# Actual
The output in the terminal includes 'getTask' as VS Code appears to run 'provideTasks' on the relevant TaskProvider and then execute one of the tasks provided from there.

# Notes
I'm sure I'm doing something wrong but I'm experiencing this in a much larger project and it doesn't seem intuitive to me. 

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.4.0-104-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz (4 x 2379)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.77GB (1.03GB free)|
|Process Argv|. --crash-reporter-id cae562b8-988d-4a72-b66b-6bc1663de467|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.15.1
esbuild-problem-matchers|con|0.0.2
vscode-eslint|dba|2.2.2
RunOnSave|eme|0.2.0

</details>

**Comment by alexr00** [comment]
Thank you for the clear example!

**Comment by alexr00** [comment]
Your example was correct, this is a recent regression.

**Comment by michaeljones** [comment]
Do you consider it to be important enough for inclusion in a 1.65.3 at some point or will we see the change in the March release instead?

**Comment by michaeljones** [comment]
Thank you. Good to know. I will examine our extension with that in mind.

**Comment by michaeljones** [comment]
For anyone else that comes across this, I've ended up changing both a value in the task definition and the task name in order to stop the confusion happening. I don't know why I have found this to be necessary. Also worth making sure that all fields are properly declared in the package.json taskDefinition entry.
