### ISSUE TITLE
`Install Another Version...` show some double entries for the C# extension only

### ISSUE THREAD

**Issue by cateyes99** [microsoft/vscode#145003]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: _**1.64.2** portable zip version_
- OS Version: _**Windows 10 Enterprise**, Version 20H2, OS Build 19042.1526_

Steps to Reproduce:
i've noticed that among the all extensions i've installed, the C# one is the only one has this issue. Go to the Extensions view. `Click Install Another Version...` on the menu for the C# extension. Observe that there are double entries on the list showing up since `1.23.17`.
![image](https://user-images.githubusercontent.com/19678455/158086399-9d141668-c7e7-4989-bb27-4843397eec7f.png)

**Comment by sandy081** [comment]
I cannot repro it on Mac, will see if I can repro it in windows

**Comment by sandy081** [comment]
Please verify this on Windows
