### ISSUE TITLE
The window has crashed (reason: "killed', code: '9')

### ISSUE THREAD

**Issue by xapenny** [microsoft/vscode#145033]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.65.2
- OS Version:macOS 12.3 (21E230)

Steps to Reproduce:
1. Update macOS to 12.3
2. Launch vscode
3. After showing "The window has crashed (reason: "killed', code: '9')" dialog, the app immediately crashed.

Note: The app functions entirely normal under rosetta2.
I have tried:
1. Re-install VSCode
2. "code --disable-extensions"
3. "code --disable-gpu"
4. Delete everything under /Users/<Username>/Library/Application Support/Code/
None of above works for me.
Crash dump: [crash1.zip](https://github.com/microsoft/vscode/files/8244959/crash1.zip)

**Comment by mindesik** [comment]
Just upgraded to macos 12.3, try to ENABLE System Integrity Protection if you have disabled it before: https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection

**Comment by xapenny** [comment]
> Just upgraded to macos 12.3, try to ENABLE System Integrity Protection if you have disabled it before: https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection

Thanks! It works!
