### ISSUE TITLE
Erro plugin TOTVS (SSL HandShaque)

### ISSUE THREAD

**Issue by RONILTONOB** [microsoft/vscode#145074]
Issue Type: <b>Bug</b>

Ao tentar criar um server para conexão com a versão do Protheus 12.1.33 ocorre um erro no server do Protheus impedindo a criação do ambiente. 

Segue o erro que ocorre:

[VDRPORT] 220314_172520 01F8 VSS0782 E ctx:019 HANDSHAKE line=320 cmd=[SSL_read,
 alocated: 16384] error=336130315 msg=[error:1408F10B:SSL routines:ssl3_get_reco
rd:wrong version number]

Isso começou a ocorrer após a última atualização do VsCode.

Fico no aguardo,

Ronilton O, Barros

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (3.26GB free)|
|Process Argv|--crash-reporter-id b6510b3a-d7fd-47c0-80d8-5f64b47e4503|
|Screen Reader|no|
|VM|80%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|8.2.0
gitlens|eam|12.0.4
vscode-language-pack-pt-BR|MS-|1.65.2
data-workspace-vscode|ms-|0.1.1
mssql|ms-|1.13.0
sql-database-projects-vscode|ms-|0.14.1
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.1
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.8.4
tds-monitor|TOT|0.0.7
tds-vscode|TOT|1.2.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmt:30438805
vscgsvid2:30447481
pynewfile477cf:30450039

```

</details>

**Comment by brunovieira97** [comment]
@RONILTONOB você deve reportar este problema aos desenvolvedores da extensão utilizada.
Este repositório compreende apenas o código e issues do Visual Studio Code, não de suas extensões.
