### ISSUE TITLE
Torch progress bar not working in notebooks

### ISSUE THREAD

**Issue by VictorJouault** [microsoft/vscode#145061]
Since the February update, the rendering of the output of Jupiter notebooks has decreased in quality for me. Particularly, the output doesn't seem to handle well the progress bar of pytorch_lightning model training, which is harmful to model development.

Below is the new output. It doesn't print the progress bar after each epoch.

<img width="1262" alt="Screen Shot 2022-03-14 at 11 12 57 AM" src="https://user-images.githubusercontent.com/63021225/158224885-61a4d8d4-24e4-429e-8e55-373b497528f1.png">

Below is the old output, which worked a lot better for me (the cell had been run before I updated VScode).

<img width="1192" alt="Screen Shot 2022-03-14 at 11 13 49 AM" src="https://user-images.githubusercontent.com/63021225/158225055-ee706556-c1ba-424c-9963-d724bcad4514.png">

**Comment by rebornix** [comment]
@VictorJouault do you mind share the code snippet you run to help me reproduce and troubleshoot?
