### ISSUE TITLE
VSC uninstalls itself when performing built in update.

### ISSUE THREAD

**Issue by GotITCovered** [microsoft/vscode#145045]
I'm having an issue with Visual Studio Code where it un-installs itself whenever I try to apply an update.
I get the prompt to restart to update, and when I do, it closes VSC, tries to perform the update, but midway through I get an error that code.exe can't be found, and the program is now installed.

I have not installed this in a different directory, I've used the default provided with the installation and this issue has occurred since at least the updates in October.

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
