### ISSUE TITLE
vscode jupyter notebook debug cell cannot stop

### ISSUE THREAD

**Issue by X3vvv** [microsoft/vscode#145085]
Issue Type: <b>Bug</b>

start debug a cell in jupyter notebook
click the "end debug" button next to the cell
the debugging process cannot stop, the way to stop i found is restarting the kernel

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by roblourens** [comment]
Please set `"jupyter.logging.level": "verbose"` and share the logs from the jupyter output channel. Also, what version of python and ipykernel are in your environmen?
