### ISSUE TITLE
pwsh terminal sometimes hangs when running git diff

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#145157]
Issue Type: <b>Bug</b>

1. On Windows with pwsh, run `git diff` in a repo with several diffs. For me, less opens, and I can use j and k to scroll down/up.
2. Switch to another window to do something else, then switch back to VS Code.
3. Press q to try and quit.
4. :bug: I'm unable to leave the less program.

I do not have terminal integration enabled.

How my terminal looks during Step 3:
![View of my terminal during Step 3](https://user-images.githubusercontent.com/7199958/158448236-4ee4a9dc-150b-4d73-a6f5-f7c3ae427b08.PNG)

VS Code version: Code - Insiders 1.66.0-insider (79d9bb8754331225372e892393619d4072474a19, 2022-03-15T05:16:13.157Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.59GB (14.89GB free)|
|Process Argv|--log trace --crash-reporter-id 504c9256-58c2-451f-8cc0-983584dae98d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.2
better-comments|aar|2.1.0
vscode-css-formatter|aes|1.0.2
Bookmarks|ale|13.2.4
read-only-indicator|ale|3.7.0
tsl-problem-matcher|amo|0.5.0
preview-mp4|ana|0.0.1
gitstash|art|5.1.0
emojisense|bie|0.9.0
vscode-intelephense-client|bme|1.8.2
path-intellisense|chr|2.8.0
vscode-markdownlint|Dav|0.46.0
gitlens|eam|12.0.4
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
codespaces|Git|1.5.6
vscode-pull-request-github|Git|0.39.2022031509
vscode-styled-components|jpo|1.7.0
vscode-memfs|jri|0.0.3
fluent-icons|mig|0.0.17
vscode-docker|ms-|1.20.0
vscode-language-pack-de|MS-|1.65.2
vscode-language-pack-fr|MS-|1.65.2
vscode-language-pack-pt-BR|MS-|1.65.2
vscode-language-pack-qps-ploc|MS-|1.65.2
vscode-language-pack-zh-hans|MS-|1.65.2
vscode-language-pack-zh-hant|MS-|1.65.2
dotnet-interactive-vscode|ms-|1.0.3164021
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.3.1931132634-dev
vscode-pylance|ms-|2022.3.2-pre.1
jupyter|ms-|2022.3.1000751005
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.226.0
remote-ssh|ms-|0.77.2022031115
remote-ssh-edit|ms-|0.77.2022031115
remote-wsl|ms-|0.66.0
cpptools|ms-|1.9.3
hexeditor|ms-|1.9.5
js-debug-nightly|ms-|2022.3.717
live-server|ms-|0.2.12
mock-debug|ms-|0.49.6
test-adapter-converter|ms-|0.1.5
vscode-github-issue-notebooks|ms-|0.0.115
vscode-js-profile-flame|ms-|1.0.0
vscode-markdown-notebook|ms-|0.0.26
vscode-selfhost-test-provider|ms-|0.3.9
vsliveshare-pack|ms-|0.4.0
vetur|oct|0.35.0
laravel-blade|one|1.32.0
java|red|1.4.0
vscode-xml|red|0.19.1
trailing-spaces|sha|0.3.1
vscode-scss-formatter|sib|2.3.3
sass-indented|syl|1.8.19
lorem-ipsum|Tyr|1.3.1
luna-paint|Tyr|0.13.2
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-icons|vsc|11.10.0
clang-format|xav|1.9.0

(5 theme extensions excluded)

</details>

**Comment by meganrogge** [comment]
Windows is sometimes slow in general. Can you repro this in an external terminal?

**Comment by rzhao271** [comment]
Doesn't repro reliably for me. I'm currently unable to repro it in an external terminal, either.
Closing for now.
