### ISSUE TITLE
Make the "Sort Lines" feature respect indented sub-lines and keep them under their parent lines after sorting 

### ISSUE THREAD

**Issue by ninotu** [microsoft/vscode#145117]
When i have lines such as the following snippet of a YAML configuration:
```
ports:
  - 80:80
build:
  context: ./.docker/app
```

After doing `>Sort Lines Ascending`, currently, the result will be:
```
  - 80:80
  context: ./.docker/app
build:
ports:
```

However, since in this kind of a context it is important for the child lines to remain under their corresponding parent lines after rearranging the top-level lines, then the desired output looks like this:
```
build:
  context: ./.docker/app
ports:
  - 80:80
```

Meaning that I would wish for the top-level lines to be sorted alphabetically, but keep all their corresponding child lines under them.

## Proposed solutions

One way to possibly achieve this is to respect the currently folded lines, which means I would be able to achieve the desired result by first doing `>Fold Level 1`, and then `>Sort Lines Ascending`. 

Another way might be to introduce sorting options such as `>Sort Lines Ascending Level 1`, which would imply that children (indented) lines get moved over together with their parent (unindented) lines. 

(post edited for a more real-world example)

**Comment by ninotu** [comment]
Absolutely not, yaml was just the example here. This can be applied to workspace settings which are in json, or to sort the functions in your class alphabetically. I only want the command to understand indentation.

**Comment by alexdima** [comment]
I suggest that this feature request is implemented as a vscode extension.
