### ISSUE TITLE
Request - Permanent VSCode display language setting

### ISSUE THREAD

**Issue by ptr2null** [microsoft/vscode#145192]
**Feature Request**

I use Windows with OS language "german". VS Code wants to be nice, I guess, and suggests me very often if I want VS Code in the same display language as my OS. I _ALWAYS_ click the option "I dont' want to change" (or something similar), because I want it to be in English and I want to stick with it.

Excuse me if I oversee the settings to do this permanently, but if there is no setting yet, please add one. This is really annoying.
Ideally the setting can be synchronized.

**Comment by TylerLeonhardt** [comment]
@dbaeumer does such a setting for this exist? If not, I look into adding one as soon as I can.

**Comment by dbaeumer** [comment]
What a user can do is to set the display language explicitly to English. In this case I think we shouldn't prompt about it. So I would not introduce another setting.

**Comment by TylerLeonhardt** [comment]
Thanks @dbaeumer! That seems like a reasonable solution. Closing as answered but @ptr2null let us know if you have any other questions about that.

**Comment by ptr2null** [comment]
@dbaeumer and @TylerLeonhardt  Thanks for your idea. Well I can live with it that the settings won't be synchronized. If the setting persists and doesn't change after every update that's sufficient.
