### ISSUE TITLE
Closing a tab via API changes focus

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#145111]
There is currently no way to specific the focus behaviour when closing tabs. The API usually does that via the `preserveFocus` boolean

**Comment by jrieken** [comment]
fyi @lszomoru this can help to keep focus inside the SCM box when making a commit. Today this happens

* many diff editor
* make a commit
* focus moves to editor pane :sad:
* I would rather keep focus in the commit box and press tab for the "big button"

**Comment by lszomoru** [comment]
@jrieken, I believe this has been addressed already by @lramos15 as he has refactored the code.
https://github.com/microsoft/vscode/blob/d8a95daebc2ec1f881489bdb1f7c2de69b175c51/extensions/git/src/repository.ts#L1290

**Comment by jrieken** [comment]
Yeah, we decided to simply push that 🤓

**Comment by lramos15** [comment]
To verify:

1. Ensure `"git.closeDiffOnOperation": true` is in your settings
2. Open a change in the changes view
3. Stage the file
4. 🎉 It should close the diff while preserving focus
