### ISSUE TITLE
'commant + shift + t'  is not working

### ISSUE THREAD

**Issue by YaphiX** [microsoft/vscode#145110]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.65.0
- OS Version:MacOS Monterey12.1 (21C52)
- Electron: 13.5.2
- Chromium: 91.0.4472.164
- Node.js: 14.16.0
- V8: 9.1.269.39-electron.0
- OS: Darwin x64 21.2.0

Steps to Reproduce:

1.open vscode
2.open a new tab
3.close the tab
4. i want to use 'command + shift + t' to reopen the tab closed just now like chrome.

**Comment by gjsjohnmurray** [comment]
Please check for any customize keyboard shortcuts.

The information at https://github.com/microsoft/vscode/wiki/Keybinding-Issues might also help.
