### ISSUE TITLE
View action dropdown background inconsistency

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145145]
While working on a dropdown for the timeline view I noticed how the background color is the sidebar background color, which is different from the debug dropdown:

![image](https://user-images.githubusercontent.com/900690/158423811-13ad593c-8479-4e1b-a176-091cbe2928fa.png)

![image](https://user-images.githubusercontent.com/900690/158423845-6fa4b6cb-aaf0-4e83-91f2-20328610e0af.png)

Same already applied to output if moved into the sidebar:

![image](https://user-images.githubusercontent.com/900690/158423887-619f930f-688d-4957-b2b6-e91744581523.png)

I am not sure the idea here whether to align or not.

**Comment by daviddossett** [comment]
I'd imagine these are intended to use `dropdown.background`? Not sure if these smaller style dropdowns are intentionally different for some reason @misolori?

**Comment by bpasero** [comment]
Btw there is quite a bit of CSS duplicated across all views that use a dropdown:
* Output
* Terminals
* Timeline (now with my changes)

That typically looks like this:

https://github.com/microsoft/vscode/blob/f38056689e48b412858bc558234dc98b8fba1a8e/src/vs/workbench/contrib/timeline/browser/media/timelinePane.css#L65-L102

**Comment by misolori** [comment]
Verified this works now 👍 

<img width="420" alt="CleanShot 2022-03-30 at 15 41 19@2x" src="https://user-images.githubusercontent.com/35271042/160942809-a8b37729-1fbe-42d7-bfce-2d9dba1ec52b.png">

<img width="411" alt="CleanShot 2022-03-30 at 15 42 11@2x" src="https://user-images.githubusercontent.com/35271042/160942917-bfcdd506-d616-4bda-83fe-9746e60d5f48.png">
