### ISSUE TITLE
Color of text changes

### ISSUE THREAD

**Issue by richarddunnebsc** [microsoft/vscode#145156]
Issue Type: <b>Bug</b>

Copied an list in array format from Excel (text surrounded by double quotes with comma in between) into an array in .js file in VSCode.  Although no problems have been detected in the work space, the text color is white instead of brown.   If I reduce the length of the array sufficiently, the text color changes to brown.  No idea why this is happening.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by richarddunnebsc** [comment]
Version: 1.65.2 (system setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps
Get a list of cities in a country, e.g. Argentina from any website.
Copy list into Excel, remove columns leaving city names
Undo Wrap Text
Clear Hyperlinks
Sort A-Z.
Transpose list column to row
select all cells, format cells Custom, delete General, type \"@\",   This surrounds names in double quotes with a trailing comma, select all names,
In a .js file create array var argentina = [];
Then paste the names between the brackets.  // The text color is be white, expected brown
Delete about half of the array, the text color changes to brown

**Comment by richarddunnebsc** [comment]
Type a backslash before each double quote, Github remove them after submitting.

**Comment by jrieken** [comment]
> Get a list of cities in a country, e.g. Argentina from any website.
Copy list into Excel, remove columns leaving city names
Undo Wrap Text
Clear Hyperlinks
Sort A-Z.
Transpose list column to row
select all cells, format cells Custom, delete General, type "@", This surrounds names in double quotes with a trailing comma, select all names,

I doubt these are minimal and free-of-interpretation steps: So please simply attach the file/contents that you are pasting
