### ISSUE TITLE
On mac ctrl-n did'n work when vim goto insert mode

### ISSUE THREAD

**Issue by limj0825** [microsoft/vscode#145125]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.64.2 (Universal)
- OS Version: monterey 12.0.1

Steps to Reproduce:

1. vim plugins goto insert mode
2. press 'ctrl + n' but didn't work
3. delete: 
{
  "key": "ctrl + n",
  "command": "extension.vim_ctrl+n"
}
4. work

**Comment by rebornix** [comment]
Please file against the Vim extension, thanks!
