### ISSUE TITLE
Language status item shows duplicate spinning icons when busy

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode#145115]
Does this issue occur when all extensions are disabled?: No

Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Currently if we pin an item and we mark it busy, the spinning icon will appear in both language status item (the left one) and pinned item (the right one).

![Screenshot 2022-03-15 163021](https://user-images.githubusercontent.com/45906942/158350720-05c8d25b-421e-4acd-8575-c892035b8a6f.png)

IMO it's a little duplicated and it would be great to show the busy icon only in the language status item (the left one) to help users focus on the item.

**Comment by jrieken** [comment]
Pushed a fix that ensures that one item isn't causing two spinners. However, when a pinned and unpinned item mark themselves as busy you can still see two spinners.

**Comment by CsCherrYY** [comment]
@jrieken just tested in the insiders version, works great, thanks!

![image](https://user-images.githubusercontent.com/45906942/159833469-f96a3d12-fd7f-4cf6-8016-07a660d7c3aa.png)
