### ISSUE TITLE
Settings Sync doesnt work on keybindings

### ISSUE THREAD

**Issue by chaukhoa97** [microsoft/vscode#145104]
Issue Type: <b>Bug</b>

I'm using Ubuntu on a new machine and it seems like all my settings are well synced except for keybindings. The keybindings.json is empty at all. I think it is because Ubuntu since it worked well between my old PC and my Laptop, which used Windows

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.13.0-35-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 3315)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.36GB (3.85GB free)|
|Process Argv|--unity-launch --crash-reporter-id 50fa0ec4-21f8-484c-8eea-550fd88da661|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
codesnap|adp|1.3.4
Bookmarks|ale|13.2.4
vscode-tailwindcss|bra|0.7.7
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
gitlens|eam|12.0.4
vscode-html-css|ecm|1.11.0
prettier-vscode|esb|9.3.0
vscode-jest-runner|fir|0.4.48
auto-rename-tag|for|0.1.10
code-runner|for|0.11.7
copilot|Git|1.8.5320
vscode-graphql|Gra|0.3.52
vscode-scss|mrm|0.10.0
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.5418
color-highlight|nau|2.5.0
indent-rainbow|ode|8.2.2
material-icon-theme|PKi|4.14.1
vscode-css-peek|pra|4.2.0
sass-indented|syl|1.8.19
vscodeintellicode|Vis|1.2.17
material-theme|zhu|3.13.20

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmt:30438805
vscaat:30438848
pynewfile477cf:30450039

```

</details>

**Comment by gjsjohnmurray** [comment]
What is your `settingsSync.keybindingsPerPlatform` set to?

**Comment by chaukhoa97** [comment]
In the Preferences menu, it is ticked but I can't find the setting in `settings.json` file

**Comment by sandy081** [comment]
Keybindings are synced per platform. If you want them to sync across platforms disable this setting `settingsSync.keybindingsPerPlatform`
