### ISSUE TITLE
Consider snippets for launch.json

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#14513]
Testing #13585

Right now if you want to add an additional debug configuration, you need to copy and paste an existing config. We should consider adding a couple snippets to make it easier to get started with adding an additional configuration via simple code completions.

![image](https://cloud.githubusercontent.com/assets/762848/19715150/1603de68-9b08-11e6-9c8f-c2bcab633066.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/13886
