### ISSUE TITLE
SQL code completion: preference for upper case keywords

### ISSUE THREAD

**Issue by mariusa** [microsoft/vscode#145129]
When editing a .sql file and typing "sel", vscode offers 2 code completion options:
```sql
select
SELECT
```
(same for any other SQL keyword)

Would it be possible to please recommend only UPPERCASE keywords? Maybe have a preference for this? (trying to avoid cluttering preferences)

**Comment by aeschli** [comment]
VS Code does not have SQL specify code completion out of the box. Do you use an extension?

**Comment by mariusa** [comment]
> VS Code does not have SQL specify code completion out of the box

I can see that now on a fresh install, thanks. Will report to the extension.
