### ISSUE TITLE
Flake8 Does Not Exclude Subdirectories Indicated in .flake8 File.

### ISSUE THREAD

**Issue by FeryET** [microsoft/vscode#145130]
Issue Type: <b>Bug</b>

Flake8 does not ignore the patterns in `.flake8` when called by the VSCode linter, but when directly called in the terminal, it works.

Somehow it cannot find the subdirectories in the way vscode calls it, since by typing this: `test/A/B/*.py`, it works, but by typing `test/` it does not ignore the python files in B folder.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.13.0-27-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1456)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|7.51GB (0.44GB free)|
|Process Argv|--unity-launch --crash-reporter-id 355bcffe-c3aa-4b6e-a779-e66010575b25|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.5.0
toml|be5|0.6.0
gitignore|cod|0.7.0
vscode-github-actions|csc|0.22.0
gitlab-ci-validator|cst|1.0.0
vscode-markdownlint|Dav|0.46.0
gitlens|eam|12.0.4
gc-excelviewer|Gra|4.2.53
todo-tree|Gru|0.0.215
intellij-idea-keybindings|k--|1.5.0
restructuredtext|lex|178.0.0
file-downloader|min|1.0.11
mindaro|min|1.0.120220125
vscode-docker|ms-|1.20.0
vscode-kubernetes-tools|ms-|1.3.7
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.2-pre.1
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
autodocstring|njp|0.6.1
vscode-yaml-sort|Pas|5.1.6
material-icon-theme|PKi|4.14.1
vscode-yaml|red|1.5.1
pdf|tom|1.2.0
simple-rst|tro|1.5.2
vscodeintellicode|Vis|1.2.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
testflight:30433670
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30450902
vscscmwlcmt:30438805
vscgsvidc:30447482
cppdebug:30451566
pynewfile477cf:30450039

```

</details>

**Comment by IllusionMH** [comment]
/extPython

VS Code doesn't support Python etc. out of the box and this functionality is provided by Python extension.

You should check if you have proper config according to Python extension docs and report issue in extension's repo if config is correct but issue still present.
