### ISSUE TITLE
Make some China mirrors boost download speed

### ISSUE THREAD

**Issue by jinfagang** [microsoft/vscode#145128]
currently download vscode is very slow behind GFW.

<img width="253" alt="image" src="https://user-images.githubusercontent.com/21303438/158384715-57cc6320-c654-4cf8-b9d5-df4e4a75d8a9.png">

**Comment by joaomoreno** [comment]
We currently have some China territory detection and route users to a different CDN: `https://vscode.cdn.azure.cn`. Are you in Chinese territory right now? If you use proxies, it might appear that our detection fails in that case.

**Comment by jinfagang** [comment]
@joaomoreno yes. but I found if I manually replace the http url from default one, it's 10x faster now. It maybe your website returns my url are from outside of cdn.

**Comment by joaomoreno** [comment]
I'm happy that it's faster now.
