### ISSUE TITLE
Trimmed cross (X) that closing the tab when a name is long

### ISSUE THREAD

**Issue by KalitaAlexey** [Microsoft/vscode#14516]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Steps to Reproduce:

1. Create an empty file with name "Approach Document for SIP96X1-21274.txt"
2. Open it in VSCode.

**Comment by weinand** [comment]
I followed your steps from above but I don't understand what you mean and what the problem is. Please provide better steps for how to reproduce the problem and add a screenshot.

**Comment by KalitaAlexey** [comment]
![issue](https://cloud.githubusercontent.com/assets/11215191/19718920/42fce37a-9b70-11e6-91bf-39360f77039b.JPG)

**Comment by weinand** [comment]
@KalitaAlexey thanks, that helps...

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13668
