### ISSUE TITLE
More easily see what extension flagged a problem

### ISSUE THREAD

**Issue by wbt** [microsoft/vscode#145169]
Sometimes, problems stay flagged as problems far longer than they should, even after they've been fixed.
In [this issue](https://github.com/microsoft/vscode/issues/111443), the idea of a refresh button on the problems pane was rejected with instructions to file an issue on the extension which keeps the problem around too long.  The problem is then: of the many installed extensions, which one flagged this issue?  I don't see how to figure that out from the current interface beyond reasoned-guess-and-check, but there should be an easier way to find that within the Problems display.

**Comment by gjsjohnmurray** [comment]
Previously requested in #141987
