### ISSUE TITLE
Search across multiple repos in workspace generates error

### ISSUE THREAD

**Issue by oneEyedBunny** [microsoft/vscode#145165]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.58
- OS Version: MacOS Monterey v 12.1

Steps to Reproduce:
1. Add more than 1 repository into your workspace
2. Select search and enter any value
3. No value returned but search box is highlighted with red box with error message displaying: 
"spawn
/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/@vscode/ripgrep/bin/rg EACCES"

Additional Info:
*Repos: Java11
*This functionality worked fine on Friday 3/11/22, but was an issue on Monday 3/14/22
-Node Version: 14.16

**Comment by roblourens** [comment]
Tracked in https://github.com/microsoft/vscode/issues/136373, but I don't understand why this is happening for some people.
