### ISSUE TITLE
Prevent case change the drive letter in Terminal

### ISSUE THREAD

**Issue by iqfareez** [microsoft/vscode#145195]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.2
- OS Version: Windows 11

Steps to Reproduce:

1. Open terminal
2. Run
  ```console
  echo http://localhost/C:/Iqmal
  ```
3. Click the echo-ed link.

The link will open in the browser, but the driver letter has been changed to lowercase, causing error.
For context, I'm using Flutter migration tool. It will open the tools in the browser, but since vscode alter the casing, the tools will fail to load (404)
Example:
```
View the migration suggestions by visiting:

  http://127.0.0.1:58459/D:/Iqmal/Documents/flutterapps/migration_error?authToken=8lTfzawzrgE%3D 

```
![image](https://user-images.githubusercontent.com/60868965/158777604-c504bf0e-daa4-4a8a-babe-4f7aa2293142.png)

**Comment by Tyriar** [comment]
This looks like a problem in the flutter migration tool as it's not correctly respecting Windows' case insensitive paths.
