### ISSUE TITLE
JS/TS > Check JS for .vue files

### ISSUE THREAD

**Issue by mariusa** [microsoft/vscode#145147]
Hi,

In Settings I enabled `JS/TS > Check JS`
```"js/ts.implicitProjectConfig.checkJs": true```

This works fine for `.js / .ts` files. How to make it work for `<script>` and `<script lang="ts">` in `.vue` files?

Found this was asked on [so](https://stackoverflow.com/questions/63516353/how-do-i-enable-javascript-type-checking-in-vue-files-on-visual-studio-code), without any answer. Don't want to add `//@ts-check` directly underneath each script tag.

Thanks!

**Comment by mjbvz** [comment]
Please file this feature request against your vue extension

**Comment by mariusa** [comment]
Hi, would it be possible to vscode to handle this natively, or is an extension required?

I already asked Volar extension to use vscode's engine for `<script>`, but they prefer to use `prettyhtml`. That's why I'm looking for a native solution.
