### ISSUE TITLE
when i press command+S twice,the code file saved twice even i do not change any code

### ISSUE THREAD

**Issue by wusama** [Microsoft/vscode#14515]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 15.6.0
- Extensions: abusaidm.html-snippets-0.0.18, christian-kohler.npm-intellisense-0.1.4, donjayamanne.githistory-0.1.0, formulahendry.code-runner-0.4.1, hnw.vscode-auto-open-markdown-preview-0.0.3, iradul.debugger-for-phantomjs-0.1.1, itryapitsin.Scala-0.1.7, itryapitsin.ScalaSnippets-0.1.7, jaylinwang.weex-0.4.0, johnpapa.Angular1-0.1.16, naumovs.node-modules-resolve-1.0.2, robertohuertasm.vscode-icons-3.0.6, tanato.vscode-gulp-0.0.4, vladmrnv.expresssnippet-0.0.8, wcwhitehead.bootstrap-3-snippets-0.0.7

Steps to Reproduce:

1.press command+S
2.file not change,press command+S again, gulp will find file change, and reload web

**Comment by weinand** [comment]
@wusama are you seeing this even when disable all extensions by launching code with `--disable-extensions`?

**Comment by bpasero** [comment]
This is as designed and since 1.6.0. People want to be able to trigger external file watchers by saving, even if the file is not dirty.
