### ISSUE TITLE
Typescript server died 5 times in 5 minutes

### ISSUE THREAD

**Issue by ESClay** [microsoft/vscode#145183]
Issue Type: <b>Bug</b>

Use...typescript?

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (12.35GB free)|
|Process Argv|--crash-reporter-id 0b110518-2d31-4312-814f-0042bcc47afd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2591)|
|Memory (System)|15.61GB (11.22GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|4.4.3
remote-wsl|ms-|0.64.2
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|4.4.3
vs-code-prettier-eslint|rve|3.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmt:30438805
vscgsvid1:30447480
pynewfile477cf:30450039

```

</details>

**Comment by fuale** [comment]
it also says
```
Please update your TypeScript version
The workspace is using an old version of TypeScript (4.6.2).

Before reporting an issue, please update the workspace to use the latest stable TypeScript release to make sure the bug has not already been fixed.
```
But 4.6.2 is latest

**Comment by albertosantini** [comment]
Please, follow these steps to collect info: https://github.com/microsoft/vscode/issues/139530#issuecomment-1004415300

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by fuale** [comment]
> Does this reproduce in the latest VS Code insiders build

No, i download and it's works 
![image](https://user-images.githubusercontent.com/36966275/158735127-6516bb5d-890d-4758-85c3-9ccf81517617.png)

**Comment by fuale** [comment]
Ok, sorry, it was plugins

**Comment by fuale** [comment]
Maybe one of
- svelte.svelte-vscode
- scrimba.vsimba

**Comment by fuale** [comment]
I follow @albertosantini debug method

**Comment by fuale** [comment]
@mjbvz Close this issue
