### ISSUE TITLE
VsCode Alt + Enter not working

### ISSUE THREAD

**Issue by raus98** [microsoft/vscode#145121]
Issue Type: <b>Bug</b>

I'm currently working with Flutter when I want to open menu fast I select object then press Alt + Enter but nothing happens.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by mjbvz** [comment]
Please file this against the flutter/dart extension
