### ISSUE TITLE
[scss] support @forward configuration

### ISSUE THREAD

**Issue by stratboy** [microsoft/vscode#145108]
Issue Type: <b>Bug</b>

Hi, I'm experiencing an issue with Dart Sass syntax: editor reports an error at the 'with' statement on @forward rules if the 'as' statement is used as well:

```scss
@forward "../node_modules/lr-css-modules/components/_forms.scss" as components-* with (
  $field-border-radius: 16px,
  $field-border: false
); 
```

That is valid syntax instead, and compiles properly.

<img width="757" alt="Schermata 2022-03-15 alle 09 08 05" src="https://user-images.githubusercontent.com/437598/158333421-e361323d-08f9-4449-8154-94be7b9cbeef.png">
<img width="580" alt="Schermata 2022-03-15 alle 09 08 14" src="https://user-images.githubusercontent.com/437598/158333425-3d6a848f-660a-4280-8aff-303e7d966aa2.png">

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (1.28GB free)|
|Process Argv|--crash-reporter-id be98acbe-d6d8-4759-8f3a-afeac4211d43|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-extra-intellisense|ami|0.6.2
vscode-eslint|dba|2.2.2
vscode-html-css|ecm|1.11.0
vscode-great-icons|emm|2.1.84
vsc-material-theme-icons|equ|1.2.2
php-intellisense|fel|2.3.14
vscode-firefox-debug|fir|2.9.6
text-transform|flo|0.1.0
html-slim-scss-css-class-completion|gen|1.7.8
material-color|guo|1.3.2
smarty|imp|0.3.0
volar|joh|0.33.2
vscode-docker|ms-|1.20.0
remote-containers|ms-|0.224.2
laravel-blade|one|1.32.0
material-icon-theme|PKi|4.14.1
text-power-tools|qcz|1.30.0
subtle-brackets|raf|3.0.0
inputer|syp|0.0.9
vscode-icons|vsc|11.10.0
file-icons-mac|way|1.0.1
php-debug|xde|1.25.0
php-pack|xde|1.0.3
php-intellisense|zob|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmc:30438804
vscgsvidc:30447482
pynewfile477:30450038

```

</details>

**Comment by aeschli** [comment]
Spec is here: https://sass-lang.com/documentation/at-rules/forward#configuring-modules

**Comment by mariamhmahmoud** [comment]
Hi, I'm new to open source and would like to work on this issue!

**Comment by aeschli** [comment]
The parser code is here: https://github.com/microsoft/vscode-css-languageservice/blob/11ed0f7f417fd5139a2e1743c48930cbe0759f60/src/parser/scssParser.ts#L852

You would create a PR in that repo

See [here](https://github.com/microsoft/vscode-css-languageservice/blob/main/README.md#development) how you can develop and test this.

**Comment by mariamhmahmoud** [comment]
I'm having a hard time setting up the development environment. Whenever I run yarn link vscode-css-languageservice as detailed in https://github.com/microsoft/vscode-css-languageservice/blob/main/README.md#development, I get an error that there is no registered package. I made to run npm install --save vscode-css-languageservice first.

**Comment by aeschli** [comment]
You need to run `yarn link` in the folder of `vscode-css-languageservice`. I updated the readme.

**Comment by mariamhmahmoud** [comment]
When I get to the Debug: Attach to Node Process part, I am not seeing any code-oss process with the css-language-features path. I completed all steps before this one and have VSCode running out of sources, but I am unable to develop and test because of this.

**Comment by aeschli** [comment]
Did you open a scss file?
