### ISSUE TITLE
Weird behavior with tab completion in terminal

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#145163]
System info: macOs, Zsh, shell integration on.

1. Navigate to vscode folder
2. Type `./script` and hit tab
3. Watch it autocompletes to `./scripts/`
4. 🐛 Hit tab again to autocomplete the names, it instead creates a big space and adds `./scripts/` again.
![Recording 2022-03-15 at 15 59 21](https://user-images.githubusercontent.com/4544166/158461151-9228a76a-0365-408c-b3d1-8607b5541d47.gif)

**Comment by Tyriar** [comment]
Not sure if we're tracking this one yet but I've seen it too in pwsh/Windows.

**Comment by ChaseKnowlden** [comment]
Works fine in pwsh.

**Comment by Tyriar** [comment]
Maybe I didn't see it on Windows actually. Happens on zsh/mac when pasting:
<img width="418" alt="Screen Shot 2022-03-17 at 10 57 44 am" src="https://user-images.githubusercontent.com/2193314/158866018-0d858eae-137e-4d45-a4b0-583a3a90651c.png">

**Comment by Tyriar** [comment]
Oh I bet I know what's causing this, we need to wrap "invisible" parts of the prompt in `\[` and `\]`

**Comment by Tyriar** [comment]
Simpler repro:

1. Type `echo`
2. Press tab

<img width="242" alt="Screen Shot 2022-03-17 at 11 08 21 am" src="https://user-images.githubusercontent.com/2193314/158867771-682636e9-5424-49fa-84a1-9ff85eab53a4.png">
l
