### ISSUE TITLE
"activeViewlet" is not usable in 'when' clauses for extension contributed views.

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#145118]
If I use "Developer: Inspect Context Keys" to find out what the `activeViewlet` is set to, for anything other than standard views (e.g. Explorer, Search, etc.) it contains a UUID, e.g. `"workbench.views.service.sidebar.cad36e69-5c36-45de-991a-327cc9800310"`

The UUID also changes when a view is moved from the activity bar.

This makes it impossible for users to set a when clause on the visibility of the view in keybindings.

**Comment by sbatten** [comment]
the viewlet (or view container) is static after being created. the views have their own identifier which is more readable.

**Comment by chipbite** [comment]
Thanks alot for your reply @sbatten to the OP! 

Sorry for reviving this but the reply is not clear to me, is there an identifier for a given extension that we can use right now in a key binding when clause? 

If yes, can you please give a concrete/real world example of such an identifier - it would be great if you would use [the todo tree extension](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree), which is a [popular](https://medium.com/@EclecticCoder/manage-todo-list-in-vscode-beb53774d776) [extension](https://medium.com/@EclecticCoder/manage-todo-list-in-vscode-beb53774d776) and a great example for this problem.

Reason for asking for clarification is also that I am fairly certain that the developer that raised this issue also did not fully understand the reply. 

And as user, I dont know if or how this can be resolved. 

Example 1: Keyboard binding where I would want to use the when clause to identify that the extension viewlet is in focus: 
```
    {
        "key": "ctrl+space",
        "command": "todo-tree.reveal",
        "when": "sideBarFocus && !editorFocus"
    },
```

Example 2, for the built-in sidebar viewlet explorer, a corresponding and working binding is of course:
```
    {
        "key": "alt+n",
        "command": "explorer.newFolder",
        "when": "explorerViewletVisible && sideBarFocus && !editorFocus"
    },

```
So, what exactly would I enter in example 1 to achieve what would correspond to what the `explorerViewletVisible` criteria in the example 2 when clause achieves?


If there is no way to do this as of now, it would of course be valuable to have that clear.

BR! /marcus
