### ISSUE TITLE
PHP Syntax highlighting broken by SQL comment

### ISSUE THREAD

**Issue by M393** [microsoft/vscode#145124]
Issue Type: <b>Bug</b>

Syntax highlighting breaks after a SQL comment on the last line of a multi-line SQL statement.
```php
<?php
$qry = "SELECT 1
        -- test";
$x = str_len($qry);
```
Syntax highlighting is wrong (left). With a new line after the comment it is correct (right).
![image](https://user-images.githubusercontent.com/56256405/158380352-09c916e6-7a77-4ad2-911e-61f8e66b684c.png)

VS Code version: Code - Insiders 1.66.0-insider (79d9bb8754331225372e892393619d4072474a19, 2022-03-15T05:16:13.157Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 x 3690)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (3.03GB free)|
|Process Argv|--disable-extensions --crash-reporter-id ecde767b-a1bc-4af3-80bf-762c0363ec82|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vsclayoutctrc:30405799
dsvsc009:30440021
pythonvspyt640:30438691
vscscmwlcmt:30428973
vscgsvid2:30433758
dockersurvey3cf:30438169
pynewfile477:30451556

```

</details>

**Comment by alexr00** [comment]
Since `--` indicates  that the whole line is a comment, this is by design.

**Comment by alexr00** [comment]
Yes, I don't think that the syntax highlighting grammar we use can do any better than this.
