### ISSUE TITLE
Save doesn`t work

### ISSUE THREAD

**Issue by 4zriel** [Microsoft/vscode#14518]
- VSCode Version:
Visual Studio Code - Insiders

[Main Instruction]
Visual Studio Code - Insiders

[Content]

Version 1.7.0-insider
Commit 889c720db5e83f4649ba1317fc8fdd3387cbf975
Date 2016-10-26T06:50:42.691Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0

[OK]
- OS Version:Windows 10

Steps to Reproduce:

1. Simply press ctrl-s or save button
2. Nothing happens
3. Even if I close unsaved file and get errror message - stil save from this window doesn`t work..

**Comment by weinand** [comment]
@4zriel  It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces.

**Comment by 4zriel** [comment]
EDIT:
It looks like it is problem with one extension -> HTML CSS Class Completion - https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion
(same error is on stable VSCode version)

**Comment by 4zriel** [comment]
@weinand 
Just try with install/uninstall extension one by one and try to figure out which one cause this strange behaviour

**Comment by weinand** [comment]
Please report an issue against the problematic extension.
