### ISSUE TITLE
Hiding snippets from intellisense upon definition

### ISSUE THREAD

**Issue by gtm-nayan** [microsoft/vscode#145142]
Users can hide snippets from intellisense, for example if they're only using it for the `wrap in` functionality through the `Insert snippet` command. There should be a way to hide them by default when they're defined, something like:

```json
[
  "A snippet": {
   "prefix":...,
   "body": ...,
   "hideFromIntellisense": true
  }
]
```
Particularly handy if extensions want to provide snippets for certain features in the `Insert snippet` command, but want to hide them from intellisense to avoid duplicate suggestions (eg. if they also provide similar context aware autocompletions).

**Comment by gtm-nayan** [comment]
Okay maybe I was just being dum. Removing the prefix from the definition does what I want at least in user snippets. @jrieken are there any caveats that I'm missing? Otherwise this can be closed.

**Comment by jrieken** [comment]
True thing. I forgot about that. Not having a prefix is exactly what you want. Closing as "already implemented" (but forgotten by the author)
