### ISSUE TITLE
terminal not "reading" -- (dash dash) flags. Unable to verify transactions

### ISSUE THREAD

**Issue by ZnXCreators** [microsoft/vscode#145167]
Creating NFT collection with CodeSTACKr v.2.0.0 repo on vscode (https://github.com/codeSTACKr/create-10k-nft-collection), as per following tutorial (https://www.youtube.com/watch?v=quGdJweadFM)

NFTs minted and trying to confirm transaction with the command:
 npm run check_txns --dir=minted

vsCode seems unable to know in which directory the files are, although I clearly added the flag '--dir=minted' to the command 'npm run check_txns'. Conversely, when minting I had add a flag '--start=1 --end=100', which was ignored during the minting process. 
It seems that somehow vs code is not "reading" the '--' (dash dash) flags. 

Error log below. 
Please specify the directory to check. Use "minted" or "revealed"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 10k-collection-video@2.0.0 check_txns: `node utils/nftport/checkTxns %npm_config_dir%`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the 10k-collection-video@2.0.0 check_txns script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

- VS Code Version: 1.65.2
- OS Version: macOS Monterey 12.2 (running on a Mac M1)

**Comment by yume-chan** [comment]
Your arguments are handled by npm, instead of your script.

Use `npm run script -- --args` instead.

Check the doc: https://docs.npmjs.com/cli/v8/commands/npm-run-script#description

**Comment by ZnXCreators** [comment]
Thank you @yume-chan, very useful guidance. It sounds right, but I am very new to vsCode and still learning my way around, could you confirm exactly why I need to do / to type, and where? Should I enter the following command:  'npm run script -- --args' [Enter] (as is or I need to specify what 'args' refers to'?, in Terminal?). And then vsCode should proceed to correctly read my '--' in subsequent commands that I launch in Terminal?

i.e. when minting NFTs, I am running 1) 'npm run mint --start=1 --end=100'    (But vsCode is ignoring the flag/argument to limit minting from #1 to #100 and continues to go on)
And also 2) 'npm run check_txns --dir=minted'  (But vsCode is ignoring the flag/argument and not referencing the directory)
