### ISSUE TITLE
Add ability to hide Layout Icons

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode#145105]
These icons: 

<img width="274" alt="Screenshot 2022-03-15 at 09 37 47" src="https://user-images.githubusercontent.com/6391776/158329041-c3b4bd8c-b41f-423a-b391-e10825b4ffad.png">

I looked everywhere and there seems to be no way to hide them. Please add a setting for it.

**Comment by gjsjohnmurray** [comment]
Did you try the `workbench.experimental.layoutControl.type` setting?

**Comment by nikitavoloboev** [comment]
@gjsjohnmurray 

`"workbench.experimental.layoutControl.type": "menu",` is the closest one to what I want but it still has the icon left.

<img width="185" alt="Screenshot 2022-03-15 at 10 40 10" src="https://user-images.githubusercontent.com/6391776/158338726-1486e931-c3b9-4de7-95f8-7c018657c175.png">

So the issue still stands. There should be a setting:

`workbench.experimental.layoutControl.enabled` setting with `false` as possible value that hides the icon all together.

**Comment by gjsjohnmurray** [comment]
Isn't workbench.experimental.layoutControl.enabled already there?

**Comment by nikitavoloboev** [comment]
You are right. Thank you lots @gjsjohnmurray
