### ISSUE TITLE
Add support for Ruby on Rails (IntelliSense)

### ISSUE THREAD

**Issue by bellagio** [Microsoft/vscode#14514]
Code completion in Rails projects.

**Comment by chrisdias** [comment]
@rebornix is this request better suited for the ruby extension?

**Comment by rebornix** [comment]
@chrisdias it requires language server or autocomplete for rails so it's better for a separate extension to do it.

**Comment by mjbvz** [comment]
Closing as extension candidate. Please see [this guide](https://code.visualstudio.com/docs/extensions/overview) for information about authoring a language extension
