### ISSUE TITLE
GUI stop working - all freeze (using git via ssh)

### ISSUE THREAD

**Issue by PaoloFalomo** [Microsoft/vscode#14517]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: bajdzis.vscode-twig-pack-1.0.0, felixfbecker.php-debug-1.9.7, Kasik96.format-indent-1.3.0, lukasz-wronski.ftp-sync-0.3.1, PKief.material-icon-theme-1.0.3, wcwhitehead.bootstrap-3-snippets-0.0.7, xabikos.JavaScriptSnippets-1.1.0, zhuangtongfa.Material-theme-1.0.3, Zignd.html-css-class-completion-1.0.1

Steps to Reproduce:
1. Configure a gitlab.com git repo folder via ssh (non http://)
2. Try to view a file or do something and the ui will freeze.

**Comment by PaoloFalomo** [comment]
I'm currently trying to run `Code.exe` as administrator.

**Comment by PaoloFalomo** [comment]
40 minutes and no problems since running as administrator. I guess there are some _permissions_ that using `Code.exe` as non-administrator might block the **ssh**... just a theory. Hope it helps

**Comment by joaomoreno** [comment]
So... when you run as administrator, the issue doesn't happen?

**Comment by PaoloFalomo** [comment]
@joaomoreno Yes! Exactly.

**Comment by chrmarti** [comment]
@PaoloFalomo Does this still occur? Could you try running without `Zignd.html-css-class-completion`?

**Comment by joaomoreno** [comment]
Since git moved to an extension, this has changed considerable and GUI should not stop working.
