### ISSUE TITLE
Inlay hint shows `?` in wrong position

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#145131]
0. Have type hints on
1. Have a function with an optional parameter and don't specify the type.
2. 🐛 The `?` appears after the hinted type but the variable name shows before it. I would expect the `?` to go with the variable.

See screenshot since my explanation is probably not great
<img width="399" alt="Screen Shot 2022-03-15 at 9 52 56 AM" src="https://user-images.githubusercontent.com/4544166/158393207-136fd9fe-c681-484a-9d40-be89d73568f6.png">

**Comment by jrieken** [comment]
Looks like TypeScript is giving the wrong position here

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/48277 to track upstream
