### ISSUE TITLE
Consider highlighting "program" line in launch.json after creating default configuration

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#14510]
Testing #13585

I've found that this is where users tend to struggle the most when setting up launch configurations, and it may help to simply position the cursor in the right place so that the line stands out a little more. So after the file is created, it would look more like this:

![image](https://cloud.githubusercontent.com/assets/762848/19715724/047615e0-9b0c-11e6-9dc8-0f665ef45c9a.png)

**Comment by isidorn** [comment]
@mousetraps nice idea! However we currently have the limitation that the content of this file is coming from the debug adapter and the editor is controlled by vscode. And there is no way for the debug adapter currently to specify what is the most important attribute.

Assigning to @weinand to consider this feature request

**Comment by weinand** [comment]
Closing because we are not planning to implement this within the next 12 months.
