### ISSUE TITLE
Use left/right instead of full for terminal overview ruler decorations

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#145255]
Currently we use "full" position for the terminal overview ruler:

![image](https://user-images.githubusercontent.com/2193314/158666756-eb8ca4e2-92e4-4b98-9e5b-992976cf07bb.png)

Let's change this to use left for success/skipped and right for errors so it's less noisy, more readable and blends in with the editor more:

![image](https://user-images.githubusercontent.com/2193314/158666866-9763ef3d-c9fd-4876-96d9-b3be98604e55.png)

**Comment by meganrogge** [comment]
done in https://github.com/microsoft/vscode/commit/a854e41105496eff1ba0b39e7d61e988cb3a8b9a
