### ISSUE TITLE
Panel is not closed when active output channel is disposed

### ISSUE THREAD

**Issue by m417z** [microsoft/vscode#145260]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2 (user setup)
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Create an extension that runs the following code:
```javascript
const logOutputChannel = vscode.window.createOutputChannel('MyOutputChannel');
logOutputChannel.show();

setTimeout(() => {
	logOutputChannel.dispose();
	vscode.commands.executeCommand('workbench.action.closePanel');
	setTimeout(() => {
		vscode.commands.executeCommand('workbench.action.closePanel');
	}, 2000);
}, 2000);
```
2. Observe that the first `workbench.action.closePanel` command has no effect, and the panel closes after 4 seconds, not 2.

This looks like a race condition and it affects my extension. Reproduces on latest nightly.

**Comment by m417z** [comment]
@gjsjohnmurray it didn't help, it looks like disposing the currently selected output channel makes the panel visible if it's hidden.

**Comment by sandy081** [comment]
To verify, make sure extension with following code shows the **MyOutputChannel** channel and after 2s output view is hidden. Opening the output view shall not show the **MyOutputChannel**

```
const logOutputChannel = vscode.window.createOutputChannel('MyOutputChannel');
    logOutputChannel.show();
    setTimeout(() => {
        logOutputChannel.dispose();
        vscode.commands.executeCommand('workbench.action.closePanel');
    }, 2000);
```
