### ISSUE TITLE
where is the visual studio "Account menu" ??

### ISSUE THREAD

**Issue by mdyeamin** [microsoft/vscode#145290]
I wanna log in Github account in my visual studio code. 
but my vs code account menu didn't find it. so sad😥
![image](https://user-images.githubusercontent.com/73517661/158753520-d74c27d9-0f3f-43aa-bd33-6472aa2724e9.png)

**Comment by Cypherjac** [comment]
When you right click on the empty space in the sidebar, you should get a menu showing the items to display on the sidebar.. Check if 'accounts' is unchecked

**Comment by TylerLeonhardt** [comment]
Looks like that suggestion by @Cypherjac might have fixed your issue. Closing. Feel free to let us know if that's not the case.
