### ISSUE TITLE
'Explorer' getting opened by default

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/vscode#14521]
- VSCode Version: 1.6.1
- OS Version: Windows 10 Version 1607 OS Build: 14393.321

Steps to Reproduce:

1.  Open any html file from context menu
2. The 'Explorer' window is open. How to have it closed. Snapshot attached for reference: 
![1](https://cloud.githubusercontent.com/assets/16834561/19721418/c3737d56-9b8f-11e6-85b6-aa14f3c412f1.png)

**Comment by bpasero** [comment]
@kieferrm @chrmarti fyi this seems to be experiments.

**Comment by ranjan-ranjan** [comment]
is there some way to keep it closed. in the user settings may be?

**Comment by chrmarti** [comment]
You can use `"telemetry.experiments.showDefaultViewlet": false` for now. (Not an official setting.)
