### ISSUE TITLE
"relative" fileLocation problem matchers don't take cwd into account

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#145229]
If I have a task with the following attribute:
```
"options": {
        "cwd": "${workspaceFolder}/Tests"
      },
```
and the problem matcher includes
```
        "fileLocation": [
          "relative", "${cwd}"
        ],
```
when the problem matcher runs, it doesn't take the specified folder into account, i.e. the files are looked for in the workspace folder. If I add `/Tests` to the fileLocation, e.g. "${cwd}/Tests", it finds the correct file.

**Comment by alexr00** [comment]
`${cwd}` is the current working directory of the VS Code process, not the terminal or task's process. 

The docs [here](https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables) try to say that, but they aren't very clear. I'll update it.

**Comment by Gruntfuggly** [comment]
Thanks for clarifying the docs. Is there any way to get the current working directory for the task?

**Comment by alexr00** [comment]
Not using `${}` style variables. However, since you set the cwd using `options`, you presumably know what your cwd is (unless the task changes it).

**Comment by Gruntfuggly** [comment]
The problem is that I'm trying to write a reusable problem matcher (provided by an extension), so although I do know the cwd, the problem matcher doesn't. Unfortunately the task output doesn't provide full paths.

Thanks for the explanation.
