### ISSUE TITLE
[theme] Typescript: argument values not colored

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1452]
Notice how `6` and `false` are not colored

![screen shot 2015-12-18 at 16 13 52](https://cloud.githubusercontent.com/assets/1926584/11899860/6047fba0-a5a2-11e5-8fcd-1de698b91526.png)

**Comment by aeschli** [comment]
Scope of `6` is `token block body constant declaration function meta method numeric object parameter type ts'
Problem is that parameter.type is stronger than constant.

It's a consequence of us flattening all the tm scopes. No easy fix here.

**Comment by aeschli** [comment]
duplicate of #3008
