### ISSUE TITLE
Overview ruler decorations don't react when the theme changes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#145215]
We might need to make color mutable on the decoration options?

![image](https://user-images.githubusercontent.com/2193314/158594164-db5a821a-f7c6-41a8-a1c4-7804160a92ef.png)

**Comment by Tyriar** [comment]
This partially works, the canvas doesn't redraw immediately, you need to press enter to update it for example.

**Comment by meganrogge** [comment]
fixed with #147116
