### ISSUE TITLE
Settings toc unable to be resized in smaller screens

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#145243]
https://user-images.githubusercontent.com/35271042/158651056-1bf94179-335d-4ebd-945c-c26888750822.mp4

Compared to previous versions:

<img width="611" alt="CleanShot 2022-03-16 at 10 27 09@2x" src="https://user-images.githubusercontent.com/35271042/158651029-0ff2a025-d179-4a27-bb05-7c09fc01953b.png">

In this state I think we should either restrict resizing (like the previous version) or hide it completely. Seems very silly that I can only resize for only a few pixels.

**Comment by rzhao271** [comment]
Verification steps:
1. Navigate to the Settings editor.
2. For smaller VS Code window widths, the Settings editor table of contents goes away completely.
3. When one slowly widens the VS Code window, the Settings editor table of contents reappears. 
4. The vertical sash after step 3 should have at least 100px of movability. (You don't have to measure that it's exactly 100px, just that it's noticeably more than say 10px).
