### ISSUE TITLE
Notebooks onDidChangeCellOutput does not work 

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#145259]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.66.0-insider (user setup)
Commit: 3e5c7e2c570a729e664253baceaf443b69e82da6
Date: 2022-03-14T05:15:38.097Z
Electron: 17.1.1
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

The function `NotebookEditor.onDidChangeCellOutput` is not called when a cell's output is updated.

Steps to Reproduce:
1. Install the extension below.
2. Put a breakpoint in `onDidChangeCelLoutputs`
3. Execute a cell, ensure there is output
4. Observe breakpoint

Expected: `onDidChangeCellOutput` is called.

Actual: `onDidChanceCellOutput` is not called. 

extension.ts:

```
import * as vscode from 'vscode';
export function activate(context: vscode.ExtensionContext) {
	context.subscriptions.push(vscode.notebooks.onDidChangeCellOutputs((e) => onDidChangeCellOutputs(e)));
}

function onDidChangeCellOutputs(e: vscode.NotebookCellOutputsChangeEvent) {
	console.log(e.document.uri.toString());
}
```

package.json:
```
"enabledApiProposals": ["notebookEditor"],
```

Zip:
[onDidChangeCellOutput.zip](https://github.com/microsoft/vscode/files/8270227/onDidChangeCellOutput.zip)

cc @rebornix

**Comment by rebornix** [comment]
Starting from @jrieken, not sure if recent changes have impact on this.

**Comment by jrieken** [comment]
> Starting from @jrieken, not sure if recent changes have impact on this.

Should not have changed. However, the event is marked deprecated and should not be used. Please migrate to [`notebookDocumentEvents`](https://github.com/microsoft/vscode/blob/cdb839aa63e04f939bf8587b009621ed2712220e/src/vscode-dts/vscode.proposed.notebookDocumentEvents.d.ts)

**Comment by jrieken** [comment]
Closing as won't fix. The event will be removed next week, the new event should be used and issues should be filed against that.

**Comment by alyssajotice** [comment]
@jrieken I don't think Live Share has access to this API. Can you give us permission? This is what I see when I try to add it:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/22576531/160017699-52c36135-781a-4690-b6d6-f86c6937e617.png">

**Comment by jrieken** [comment]
Done!

**Comment by alyssajotice** [comment]
@jrieken can you confirm that this will be released to stable with the April release?

**Comment by jrieken** [comment]
Confirmed
