### ISSUE TITLE
JS type checking: recognize globalThis.vars set in functions

### ISSUE THREAD

**Issue by mariusa** [microsoft/vscode#145210]
In Settings, enable `JS/TS: Check JS`

Create app.js
```js

globalThis.uti = {}

function init() {
    globalThis.gigel = 1
}

function plugin(options) {

    console.log('ready on port', process.env.PORT)

    console.log(uti) // this works

    console.log(gigel) // Error: cannot find name

}

init()
plugin()

```

`gigel` should be recognized as a global variable, even though it was set in a function.

**Comment by IllusionMH** [comment]
This kind of issue should be reported in TS repo.

Most likely same as https://github.com/Microsoft/TypeScript/issues/9998

**Comment by mariusa** [comment]
Ok, thanks!
