### ISSUE TITLE
Native crash in linux integration tests (remote)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145246]
In https://dev.azure.com/monacotools/Monaco/_build/results?buildId=161313&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=8df5a49b-98a5-577e-6c23-929b1dbd5f98&l=741

Dump:
[32b5ef8e-4aea-41d3-a938-f74cf3d23e98.dmp.zip](https://github.com/microsoft/vscode/files/8266920/32b5ef8e-4aea-41d3-a938-f74cf3d23e98.dmp.zip)

**Comment by deepak1556** [comment]
I couldn't get complete symbolicated report, but the top stack shows that it is a return of https://github.com/microsoft/vscode/issues/143186. Do we want to try https://github.com/microsoft/vscode/issues/143186#issuecomment-1047458228 and also bring back the logs from https://github.com/microsoft/vscode/commit/361c94253de6bbefea4d09e46970390ba7da9e43 ?

**Comment by bpasero** [comment]
My hope was that https://github.com/microsoft/vscode/commit/bb1045cde2b225bc31974d6455dfc027e084bb6d fixes the fact that a window might communicate back to the main side via IPC messages to ask for workspace storage access and then would create a new SQLite DB even though we are in the process of shutting down.

If that does not help, I wonder how we can still get into that situation... I have now restored the original fix I had where we return an in-memory DB when being asked for storage and we are going down via `kill`. 

I wonder if there could still be a race condition when storage has been created, but not yet initialized. Will monitor the builds to see if this issue remains even after my latest change.
