### ISSUE TITLE
zsh suggestion is hidden when enable shellIntegration

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#145296]
- VS Code Version: 1.66.0-insider
- OS Version: MacOS 12.3

In iterm2:

<img width="810" alt="image" src="https://user-images.githubusercontent.com/41773861/158761243-5a581c20-a29f-47cd-96fd-fe250c1c358c.png">

In VSCode terminal when enable shellIntegration:

![image](https://user-images.githubusercontent.com/41773861/158761420-5dd86a7d-7c4d-4bf7-9676-afd99c85f8d5.png)

If I disable shellIntegration, everything goes ok:

![image](https://user-images.githubusercontent.com/41773861/158761655-0157f8bb-7008-4d3b-a7e1-65043cbf7057.png)

**Comment by meganrogge** [comment]
related to #145254

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/"needs-more-info"

**Comment by JacksonKearl** [comment]
Not quite yet... this is why I personally have shell integration disabled btw. 

![Recording 2022-04-28 at 11 55 14](https://user-images.githubusercontent.com/8586769/165826010-afebbdf4-fd9a-4d35-9bc1-ebd2dd637d43.gif)

**Comment by meganrogge** [comment]
This is working for me
![Screen Shot 2022-04-28 at 12 41 43 PM](https://user-images.githubusercontent.com/29464607/165833116-b04133f5-b160-47d1-8736-8a3baca0f3d4.png)

Here's what I did
![Screen Shot 2022-04-28 at 12 43 44 PM](https://user-images.githubusercontent.com/29464607/165833183-05ddf4e1-0857-4190-84cd-4b294008bf5c.png)

**Comment by meganrogge** [comment]
@JacksonKearl has reported it does not work if you just have `plugins=(git zsh-autosuggestions)` in your `.zshrc`

**Comment by JacksonKearl** [comment]
Looks like suggestion text does show up, but it uses a different history file. So it will suggest entries you have made with shell integration enabled, but not those made in normal terminals.

**Comment by Tyriar** [comment]
@meganrogge is this fine now because we revert `$ZDOTDIR` to the original? We definitely want to share the zsh history file.

**Comment by meganrogge** [comment]
@Tyriar it's using the history from within VS Code only - when should it get refreshed and also suggest things from the broad shell history? tried reloading the window
<img width="464" alt="Screen Shot 2022-06-30 at 11 37 34 AM" src="https://user-images.githubusercontent.com/29464607/176718628-c9bfaf9e-b354-4329-920a-6fff8f0a3359.png">

**Comment by meganrogge** [comment]
also does not pull from history of terminals that did not have shell integration enabled

**Comment by Tyriar** [comment]
@meganrogge it depends when zsh flushes history to `~/.zsh_history`, not sure if it's when the shell closes or a command is run.

**Comment by meganrogge** [comment]
<img width="978" alt="Screen Shot 2022-06-30 at 12 45 40 PM" src="https://user-images.githubusercontent.com/29464607/176732891-9463d403-fbe0-4c2c-93ef-72201a70d661.png">

**Comment by Tyriar** [comment]
I'm guessing we need to fix up `$HISTFILE` as well to point at `<original ZDOTDIR or ~>/.zsh_history`?

**Comment by fredrikaverpil** [comment]
@Tyriar @meganrogge would you think my [McFly](https://github.com/cantino/mcfly/releases) error is related to the above discussion? (Cc @cantino)

<img width="847" alt="image" src="https://user-images.githubusercontent.com/994357/185788754-d733b478-c316-4b54-b8f3-414b54e82311.png">

After a `touch /var/folders/cp/njmrk_0j57q3t5c8666fqr0r0000gn/T/vscode-zsh/.zsh_history` my prompt looks normal again:

<img width="846" alt="image" src="https://user-images.githubusercontent.com/994357/185788811-aea16c6e-85a8-40f0-8cd8-c6ad9a19609e.png">

I believe this usually happens when vscode is updated ...?

**Comment by Tyriar** [comment]
@fredrikaverpil we expect this to be fixed in the upcoming version, see https://github.com/microsoft/vscode/issues/157128

Sorry about the hassle, please let us know if it's not fixed in 1.71
