### ISSUE TITLE
Code changes not recognized after saving and running/debugging

### ISSUE THREAD

**Issue by moonj94** [microsoft/vscode#145228]
We have written the needed data into your clipboard because it was too large to send. 
Issue Type: <b>Bug</b>

I am not sure how to provide the steps to reproduce the problem. I should also mention that I am relatively new to vscode.

I have set up an anaconda environment and downloaded the necessary packages to run my company's code.

I have set up a test script and function to show a simplified version of the problem.

Edit: I am using Jupyter to run cell by cell. when I get rid of the cells and debug in the terminal, the problem disappears.

script: test.py
```
# %%
from add import add
a=3
b=10
c=add(a,b)
print(c)
```

function: add.py

```
import numpy as np
def add(a,b):
    print('Hello world')
    return(a+b)

```
After running the cell, the output should read Hello world. When I change the string to something else entirely, the change is not recognized and it keeps reading 'Hello World'

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (14.97GB free)|
|Process Argv|--crash-reporter-id 1f69ff88-bc2c-496d-86da-ee182071c101|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.1
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmc:30438804
vscaac:30438847
pynewfile477:30450038

```

</details>

Please paste.

**Comment by roblourens** [comment]
I get the same behavior in Jupyter lab. I think that once a module is imported, it won't be reimported. You will have to reload the kernel.
