### ISSUE TITLE
Overlapping text in intellisense suggestions

### ISSUE THREAD

**Issue by marvinhagemeister** [Microsoft/vscode#14520]
- VSCode Version: 1.7.0-insider 5bafcdb3d67b29b1f4667a3f497ac05a41dde667
- OS Version: Mac OS Sierra

Steps to Reproduce:

1. Create a css file (or any other file)
2. start typing

![Image of overlapping text](http://i.imgur.com/xZqApHn.png)

**Comment by joaomoreno** [comment]
#13813
