### ISSUE TITLE
Option to override `FileSystemProvider`'s default error handling

### ISSUE THREAD

**Issue by isc-bsaviano** [microsoft/vscode#145266]
An extension I work on contributes a `FileSystemProvider`. In certain cases when a `FileNotFound` error would be thrown for a `readFile()` call, I would like to replace the default modal dialog with a custom message and options. I've tried wrapping the code in `readFile()` in a try/catch and if the caught error matches a specific value, serve the user a modal message. However, even if I don't re-throw the error, or if I return an empty `UInt8Array`, the `FileSystemProvider` still shows the default modal dialog after my custom message. Is there a way to prevent VS Code from showing the `FileNotFound` without giving document contents to show?

**Comment by jrieken** [comment]
> Is there a way to prevent VS Code from showing the FileNotFound without giving document contents to show?

Can you explain why you would want to do that? The strength of VS Code is that we show the same UI for the same kind of errors. So, until now it doesn't sound like a good idea to redefine error UX for certain schemes.

**Comment by isc-bsaviano** [comment]
@jrieken We use the `FileSystemProvider` to show files that live on a remove server. Our servers support grouping an arbitrary number of files and packages of files into collections called "projects". If the workspace folder URI specifies a project in the query parameters (`isfs://server:namespace/?project=prjname`) I would like to ask the user if they want to remove the file from the project if they try to open it and it doesn't exist on the server. It doesn't make sense for a user to see this message, select "Yes", then be prompted to create the file. I guess I could show my message after the default one (if the user doesn't elect to create the file) but I'm not sure if that's possible either.

**Comment by isc-bsaviano** [comment]
Closing this because we no longer need it.
