### ISSUE TITLE
debug console: only collapse identical lines when they appear consecutively

### ISSUE THREAD

**Issue by Holo-Viktor** [microsoft/vscode#145250]
The current behavior is that new logs are collapsed with identical logs which appear before other, non-identical logs.
This breaks chronology, which can be confusing, misleading and straight up unusable.
I suggest maintaining the chronological order when collapsing identical lines.

A chain of logs like `update` -> `update` -> `render` -> `update`

should appear as follows in the debug console

```
(2) update
render
update
```
instead of

```
(3) update
render
```

which is the case in the current version.

---
Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by weinand** [comment]
If your observation is true, that would be a bad bug.

**Comment by roblourens** [comment]
Seeing your expected behavior here - 

<img width="471" alt="image" src="https://user-images.githubusercontent.com/323878/158733241-2e35f6fb-7526-4657-9130-db195a45fd6a.png">


can you give a specific example?

**Comment by Holo-Viktor** [comment]
Huh that's odd, I'm debugging a c++ application, if that makes a difference.

**Comment by roblourens** [comment]
Impossible to say without a specific example
