### ISSUE TITLE
Decorations disappear when scroll bar thumb fades

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#145213]
Is the thumb fading to the opaque bg color instead of fully transparent?

![Recording 2022-03-16 at 05 29 53](https://user-images.githubusercontent.com/2193314/158590273-cc80ca70-8470-478c-9eae-59aa89f3852c.gif)

**Comment by meganrogge** [comment]
setting the z-index of `xterm-decoration-overview-ruler` to 50 fixes the issue

**Comment by Tyriar** [comment]
I looked into it as well just now, starting to think it's not possible without a non-native scroll bar. Wouldn't be surprised if it's different on different browsers too.

**Comment by Tyriar** [comment]
A high z-index seems to fix it, that didn't work for you? We just need to make sure to add `pointer-events: none` as well.

It's not perfect as then it's different to the editor, but it's a very subtle difference.
