### ISSUE TITLE
Lots of borders in package.json hover

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14526]
![image](https://cloud.githubusercontent.com/assets/900690/19724107/cd409f5a-9b7e-11e6-8370-c983968babf5.png)

**Comment by aeschli** [comment]
There seem to be at least 2 hover providers participating here. The JSON mode is responsible for the last two entries which are returned a MarkedString in the form [description, version].
@joaomoreno I agree that there are a lot of lines. Maybe only a line between different hover providers? Or do you recommend me to creare a single string for description & version?

**Comment by joaomoreno** [comment]
Each provider opts to send multiple MarkedStrings in an array. Each MarkedString will live in a block. The provider can choose to put everything in a single MarkedString instead.

**Comment by jrieken** [comment]
This is *visual api breakage* because it did not use to be like that. If we continue the path of https://github.com/Microsoft/vscode/issues/14526#issuecomment-256346118 we should release-note this

**Comment by joaomoreno** [comment]
I can release note it.
