### ISSUE TITLE
Add Save option to File Right-click Menu

### ISSUE THREAD

**Issue by elharony** [microsoft/vscode#145283]
When right-clicking a File from the `Sidebar Menu` or `Tab Bar`, there's no option to "Save changes" or "Save As".
This would save some time instead of opening a file, then `CTRL+S` to save or `File > Save`

Here's a snapshot of right-click menu:
![no-save-option](https://user-images.githubusercontent.com/16986422/158722387-4c2e830e-beff-4d32-a57c-53c76a858726.png)

**Comment by JacksonKearl** [comment]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/8586769/158730717-13344fdb-885c-4cf6-b970-e82944f4881b.png">
The open editors view provides a save entry. cc @bpasero for the tab.

**Comment by elharony** [comment]
Thanks for taking the time to review it, @JacksonKearl & @bpasero!
I would love to contribute to VSCode and add this feature. Are there any helpers/things to be considered before starting out?

**Comment by vinit-pipl** [comment]
still not solved i think
