### ISSUE TITLE
Testing tabs proposed api: groups not populated unless focus an editor

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#145287]
Does this issue occur when all extensions are disabled?: Yes/No

@lramos15 

Steps to Reproduce:

1. Running Insiders with `src/vscode.proposed.tabs.d.ts` in `src`
2.  Put	`const groups =  vscode.window.tabGroups.groups;` into the extension `activate` function. (or anywhere really that can be run prior to focusing a different editor)

3. Debug

Notice that `groups` above is always an empty array.  **Unless** prior to reading `vscode.window.tabGroups.groups` , like via a command you register, you first click another editor, then it populates as expected.

So this is similar to the searching in open editors bug where sometimes all the open editors were not available unless one focused different editors.

This situation prevents building a view using the proposed tab api.

Version: 1.66.0-insider (user setup)
Commit: 6fa3243d3facbbf8b87222bcf4e81c5eddf5d47f
Date: 2022-03-16T05:17:27.938Z
Electron: 17.1.1
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22572

**Comment by lramos15** [comment]
@ArturoDent Thanks for testing the API 🙂, I pushed a large refactor that should be out in insiders today. I believe I fixed this issue but feel free to test it again today and let me know. If not I'll do a deeper investigation.

**Comment by ArturoDent** [comment]
It is working as expected now with the latest Insiders.  Thanks.
