### ISSUE TITLE
Starting VSCode from PowerShell does not support UNC Paths

### ISSUE THREAD

**Issue by crossan007** [Microsoft/vscode#14529]
- VSCode Version: 1.6.1
- OS Version: Windows 10

Steps to Reproduce:
1.  Open PowerShell to a UNC patch
2.  run "Code .<filename>"
   ![image](https://cloud.githubusercontent.com/assets/11679900/19726015/ca75483e-9b56-11e6-82ee-6824d530079e.png)

VS Code opens a new, blank file with the supplied name at the root of c:\windows, instead of the file stored on the UNC path:
![image](https://cloud.githubusercontent.com/assets/11679900/19726036/e555057c-9b56-11e6-9940-9a40e3a87d85.png)

**Comment by bpasero** [comment]
It does work if I directly use the code.exe so it seems to be an issue with our code.cmd.

**Comment by cashlalala** [comment]
Encounter the bug as well~

**Comment by wtjones** [comment]
I created a [PowerShell module](https://github.com/wtjones/PSCode) that aliases the `code` command to a cmdlet that emulates the behavior of `code.cmd`.

**Comment by joaomoreno** [comment]
As a workaround, please use @wtjones's solution. Thanks man!
