### ISSUE TITLE
Error with code hints completion on Live Share

### ISSUE THREAD

**Issue by luke-atp** [microsoft/vscode#145253]
Issue Type: <b>Bug</b>

Request languageServerProvider-any.request failed with message: Extension 'vscode.typescript-language-features' CANNOT use API proposal: extensionRuntime. Its package.json#enabledApiProposals-property declares: inlayHints, languageStatus, quickPickSeparators, resolvers, workspaceTrust but NOT extensionRuntime. The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api vscode.typescript-language-features

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.67GB (17.01GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/LukeBicknese/workspace/vtg-ui --crash-reporter-id 997e9bdf-ee19-430a-96f7-072b7476e49c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|12.0.4
copilot|Git|1.8.5320
vscode-peacock|joh|4.0.1
file-downloader|min|1.0.11
azure-pipelines|ms-|1.202.0
azure-account|ms-|0.10.1
vsliveshare|ms-|1.0.5449
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vscode-yaml|red|1.5.1
vscode-conventional-commits|viv|1.24.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30450902
vscscmwlcmc:30438804
vscgsvidc:30447482
pynewfile477cf:30450039

```

</details>

**Comment by luke-atp** [comment]
I'm not seeing the error when not in Live Share. Right now I'm only seeing it when doing Live Share. The code hints even being presented are spotty, and when they do show I get the above error. In some cases the action will work and still present the error.

I'll need some time to test with the insiders build. Are there log files that I can pull from my machine that would help with debugging?

**Comment by luke-atp** [comment]
I have attempted to use the Insider version of VS Code during a Live Share. I have no other Extensions installed, aside from Live Share and Live Share Audio. I'm not seeing the error anymore, but that is because it no longer provides code actions at all.

I am working on an Angular project. In my use right now, I can't get missing imports actions or other code refactoring actions to work.

**Comment by mjbvz** [comment]
@jrieken Any ideas why we only seem to see this error in live share? I just checked and am pretty sure that the typescript extension does not actually use the `extensionRuntime` api

**Comment by luke-atp** [comment]
I'll add that I only have this problem when I am the guest (the host can still use the code actions). If I host the Live Share the code actions work.

**Comment by jrieken** [comment]
@luke-atp Please attach the full stack trace, not just the error message, when this is happening

**Comment by luke-atp** [comment]
I'll try to get the stack trace the next time the error appears. With the Insiders build I have not seen any errors, yet. The behavior on the Insiders build is that the code actions don't show up at all. On the stable build I will occasionally get the error, but in most cases I simply do not get any code actions.
