### ISSUE TITLE
VS Code debugger should be able to use an external file for environment setup

### ISSUE THREAD

**Issue by mariosant** [Microsoft/vscode#14523]
**Issue:**
I am looking for ways to load a `.env` file into debugger environment.

`launch.json` provides an `env` section, where you can define such variables. In typical use cases, `launch.json` is being version controlled though, forbidding adding sensitive data, such as api keys.

**Expectation:**
It would be really helpful, if there was a syntax like the following example:

``` json
"env" : "${workspaceRoot}.env"
```

Not sure where to mention that, this is a **FEATURE REQUEST**.

**Comment by weinand** [comment]
@mariosant loading from a file would be **in addition** to the existing "env" attribute and not a replacement, right? So you could load some env vars from a file and add more variables to that in the launch.json.

**Comment by mariosant** [comment]
That is correct, @weinand. Loading from env file, should *add* to current environment. It *should not* replace it.

Loading vars from a file and adding more variables to launch.json, would be awesome!

**Comment by weinand** [comment]
Is it necessary to support loading multiple env files or is one typically enough?

**Comment by mariosant** [comment]
Most cases, a single `.env` file exists. I believe this is the most common use case, IMHO.

Ruby users typically use: https://github.com/bkeepers/dotenv to handle it.
Nodejs users use: https://github.com/motdotla/dotenv to handle it.

Not very sure about other ones :)

**Comment by weinand** [comment]
@roblourens fyi, another feature for node-debug2

**Comment by weinand** [comment]
@mariosant you can now use an attribute `envFile` in a launch config to specify a file containing environment variable definitions.

**Comment by mariosant** [comment]
This is great to hear! I will surely check it out @weinand.

**Comment by ancashoria** [comment]
@weinand This functionality is also needed for `tasks.json` and would allow complete removal of env variables from source code.
Is it available somewhere and I'm not finding it?

Thanks

**Comment by weinand** [comment]
@ancashoria please create a new issue against tasks for this.
