### ISSUE TITLE
Bracket pair color tokens don't work well in high contrast

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#145268]
1. Have bracket pair colorization turned on
2. Have some code with lots of brackets
3. Switch to either light or dark high contrast theme
4. 🐛 There are some light blues and yellows that are particularly bad in the light high contrast theme.

**Comment by daviddossett** [comment]
Could you grab a screenshot? This _should_ be fixed after today now that we checked in the official support for `hcLight` and did some theme tweaking as part of that PR. 

I noticed that it was an issue in the one-off theme before.

**Comment by lramos15** [comment]
@daviddossett Alright I'll wait until tomorrow's build and grab some screenshots

**Comment by lramos15** [comment]
Seems better in todays build closing 👍
