### ISSUE TITLE
Allow to undock the sidebar into a new window

### ISSUE THREAD

**Issue by bimbo1989** [Microsoft/vscode#14525]
At work I can only use a small screen, and I need the explorer view always open.
The matter is that keeping it opened leaves very small place for actual code.
So I started looking for a undocking option, but I found out that there's none.
I'd really love to be able to switch between explorer and code in two different windows (just like I do, for example, with Chrome and Chrome Debugger).

(I don't know how to add tags to the request, I wanted to use explorer-files, feature-request, ux)

Thanks!

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/10121
