### ISSUE TITLE
PowerShell Integrated console regional format

### ISSUE THREAD

**Issue by pejuborg** [microsoft/vscode#145207]
Issue Type: <b>Bug</b>

The PowerShell integrated console does not present date and time in the format that is configured in Windows.

![image](https://user-images.githubusercontent.com/51705186/158580187-0ad4a0a1-4618-4917-a6a8-3a4195a0b9ae.png)

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (18.12GB free)|
|Process Argv|C:\\Users\\pejuborg\\OneDrive - Microsoft\\Customers\\CTT\\devel\\CTT.Selenium\\ --crash-reporter-id 2072155d-09a9-4054-99e0-47130269ffee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|12.0.4
copilot|Git|1.8.5320
openvpn|idl|0.2.3
vscode-colorize|kam|0.11.1
ecdc|mit|1.4.0
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-dotnet-runtime|ms-|1.5.0
azure-account|ms-|0.10.1
azurecli|ms-|0.5.0
powershell|ms-|2021.12.0
azurerm-vscode-tools|msa|0.15.6
vscode-xml|red|0.19.1
kuskus-kusto-syntax-highlighting|ros|1.1.20

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30450902
vscscmwlcmt:30438805
vscgsvidc:30447482
cppdebugcf:30451567
dockersurvey3cf:30453610
pynewfile477cf:30450039

```

</details>

**Comment by Tyriar** [comment]
We're actually removing the date in https://github.com/microsoft/vscode/pull/152078, we may add it back at a later date if we support hovers on the * though.
