### ISSUE TITLE
Docker plugin cannot detect Docker is installed when it actually is

### ISSUE THREAD

**Issue by mpconte** [microsoft/vscode#145235]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.2
- OS Version: Windows 10 Enterprise (version 20H2)

Steps to Reproduce:

1. Installer Docker plugin
2. Install Docker Desktop (version 4.6.0)
3. Select Docker tab, it indicates "Failed to connect. Is Docker installed?"

**Comment by sandy081** [comment]
Please file the issue against the docker extension - https://github.com/microsoft/vscode-docker
