### ISSUE TITLE
VS Code uninstalls itself

### ISSUE THREAD

**Issue by hopru7** [microsoft/vscode#145239]
Issue Type: <b>Bug</b>

It is the second time that for some reason, VS Code disappears from my machine. I suspect this is caused by VS Code, since I can't think of anything else that would uninstall it.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (19.23GB free)|
|Process Argv|--crash-reporter-id bdf26146-a483-4964-b9d4-32f383e9af09|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vbscript|Dar|1.0.4
prettify-json|moh|0.0.3
csharp|ms-|1.24.1
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.1
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.8.4
powershell|ms-|2021.12.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrc:30451274
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmc:30438804
vscgsvid1:30447480
dockersurvey3cf:30453610
vscaat:30438848
pynewfile477cf:30450039

```

</details>

**Comment by joaomoreno** [comment]
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.
