### ISSUE TITLE
Timeline: expose a way to trigger an input box on an element

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145236]
Local history entries can be renamed by the user to change the label. Today I am using a quick picker as input, but it would be nice if a timeline item could signal that it wants to be editable and then show an in-place input field like the explorer does.

![image](https://user-images.githubusercontent.com/900690/158638186-8a263c1b-8707-46a9-816e-4054f255b972.png)

![image](https://user-images.githubusercontent.com/900690/158638223-09112e9b-bb3e-4493-bff7-21d5ac9eacac.png)

//cc @isidorn

**Comment by JacksonKearl** [comment]
IMO this should be in list/tree land. There's a ton of code for supporting this in explorer and it's not entirely rock solid. I wouldn't want to duplicate that in timeline. cc @joaomoreno

**Comment by bpasero** [comment]
Agreed, I was hoping this is available from the widget, too bad it is not. Custom trees would probably also benefit.

**Comment by joaomoreno** [comment]
If there's any reusability to be achieved, I suggest someone implement a Renderer which provides this functionality. This shouldn't be pushed down to the list at all since it doesn't own the _insides_ of each row.
