### ISSUE TITLE
Error when I open integrated terminal

### ISSUE THREAD

**Issue by rahdev** [Microsoft/vscode#14528]
- VSCode Version:1.6.1
- OS Version:Windows 7

Error: The terminal process terminated with exit code: 1

Steps to Reproduce:
1. Open integrated terminal
2.

**Comment by Tyriar** [comment]
Does the current folder you have non-ascii characters in the path? If so this is fixed in the insiders build #7727

**Comment by mjbvz** [comment]
Closing as fixed. @rahdev Please let us know if you are still seeing this issue with VSCode 1.8.1

Thanks
