### ISSUE TITLE
changes of tsconfig not updates error

### ISSUE THREAD

**Issue by willi84** [Microsoft/vscode#14524]
- VSCode Version: 1.6.1
- OS Version: Win10

Steps to Reproduce:
1. have an error like https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/470 (https://twitter.com/robertSPD/status/790950380570087424)
2.  update tsconfig but error-tooltip is not leaving
3. need to restart for update

it would cool, if changes are loaded without restart

**Comment by waderyan** [comment]
@willi84 thank you for opening this issue. Can you share your workspace so we can recreate this on our machines? 

@dbaeumer it seems this is being provided by the language service... we just aren't kicking off the refresh until the file is reloaded.

**Comment by dbaeumer** [comment]
@waderyan we do re-ask for all errors after waiting for 1.5 seconds. The problem however might be that the tsserver didn't process the file event in that time frame. To make this work nicely the tsserver either needs to sent and event when the [jt]sconfig.json changes or needs to retrigger error computation (builder work) by itself when these file change.

**Comment by waderyan** [comment]
@dbaeumer thank you. To confirm - https://github.com/Microsoft/TypeScript/issues/11229 will solve this for OP?

**Comment by dbaeumer** [comment]
yes.

**Comment by waderyan** [comment]
Closing as dup of https://github.com/Microsoft/TypeScript/issues/11229
