### ISSUE TITLE
Integrated terminal does not honour system `$SHELL` on macOS

### ISSUE THREAD

**Issue by edmorley** [microsoft/vscode#145233]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: macOS 12.2.1 (Monterey)
- Architecture: Apple M1 (arm64)

## Overview:

The VSCode documentation ([here](https://code.visualstudio.com/docs/editor/integrated-terminal#_terminal-profiles)) says:

> The terminal's shell defaults to `$SHELL` on Linux and macOS and PowerShell on Windows. VS Code will automatically detect most standard shells that can then be configured as the default.

However on a Macbook M1 running macOS Monterey, the system's default shell (as reported by the `SHELL` env var) is not honoured, and instead VSCode's intergrated shell defaults to `zsh` and doesn't list the shell defined by `SHELL` in the "available shells" list at all.

## Steps to Reproduce:

1. Install Homebrew on a new Apple M1 machine (which for M1 causes it to install into `/opt/homebrew` rather than `/usr/local`).
2. `brew install bash` (to install bash 5.x, since macOS system bash is still the older 3.x).
3. `chsh -s /opt/homebrew/bin/bash` (to set Homebrew's newer bash as the default system shell, rather than Apple's new default of `/bin/zsh`).
4. Log out/in for change to take effect.
5. Open `terminal.app` (or `iterm.app`), and `echo $SHELL` to confirm the default shell has successfully been changed.
6. Install VSCode.
7. Open the integrated terminal and run `echo $SHELL`.
8. Open command palette -> `Terminal: Select Default Profile`.
9. Scroll through available options to find the Homebrew bash shell.

## Expected:

- When opening the integrated terminal (at step 7) without having adjusted any VSCode setttings, VSCode by default uses the system shell defined by the `SHELL` environment variable.
- In the shell list shown by `Terminal: Select Default Profile` (at step 9), the Homebrew bash shell (`/opt/homebrew/bin/bash`) should be listed, since:
   - (a) it's set by the `SHELL` env var,
   - (b) Homebrew is pretty popular, so it seems like scanning its default install locations (as well as the system locations) would be useful regardless of whether `SHELL` was set or not.

## Actual:

- When opening the integrated terminal (at step 7), the terminal defaults to zsh, with `echo $SHELL` reporting `/bin/zsh` even though that's no longer the system default shell.
- In the shell list shown by `Terminal: Select Default Profile` (at step 9), the Homebrew bash shell (`/opt/homebrew/bin/bash`) is not listed.

**Comment by edmorley** [comment]
@meganrogge Hi! 

Thank you taking a look at this, however it's not a duplicate. 
Could you reopen it? :-)

Issue #142425 is about:
- the 1st terminal opened (subsequent terminals work fine)
- VSCode not honouring VSCode's own settings (whatever the user has configured them to be)

This issue is different, since it's about:
- every terminal opened (not just the first)
- VSCode not honour the default **macOS** system terminal (when the docs say it should use that, unless it's been overridden by the user)

**Comment by meganrogge** [comment]
Can you try running `code .` from the terminal in step 5 and see if it works then?

**Comment by edmorley** [comment]
So typically I just tried to reproduce using the original STR (prior to trying your suggestion of launching from a terminal), and I can't reproduce now, after having been able to consistently reproduce previously. This morning I updated from macOS 12.2.1 to 12.3 - perhaps doing that resolved it? Either way, closing out for now.
