### ISSUE TITLE
Inconsistent auto-scroll state

### ISSUE THREAD

**Issue by arsdever** [microsoft/vscode#145225]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.1 (Universal) Commit: 8908a9ca0f221f36507231afb39d2d8d1e182702
- OS Version: macOS Monterey 12.2.1 (21D62)

Steps to Reproduce:
Reproduced on `CMake` outputs specifically

1. Open any `CMake` project in `vscode`
2. Unlock the lock in the output pane
3. Run any job (i.e. `configure`)
4. Click in the output text (somewhere)
5. Run a job again

Expected behavior:
The auto scroll state remains in the same state as it was before

Actual behavior:
The state falls back to the `locked` state when clicking on the output text.

While trying other scenarios, I noticed that the feature doesn't behave consistently (even the bug is not consistent). For more details, please watch the recording.

https://user-images.githubusercontent.com/22396275/158609166-67654ef6-9da9-4fc5-b1de-21a8a6921d85.mov

It kinda depends on the scroll amount of the pane.

**Comment by sandy081** [comment]
This is because of this setting - `output.smartScroll.enabled` . Please disable this.

**Comment by arsdever** [comment]
I interpreted that config in the opposite way and manually set it `true` expecting it to behave as I described in the `Expected behavior` section. Thanks for the hint.
