### ISSUE TITLE
Brackets in PlantUML are sometimes incorrectly highlighted as broken

### ISSUE THREAD

**Issue by nikoladev** [microsoft/vscode#145219]
To draw [Entity Relation diagrams][er] in PlantUML you sometimes need to use syntax like `}|--` to show a "one or many" relationship with unclosed curly brackets. These unclosed curly brackets are totally fine PlantUML syntax, but they are shown as errors by the bracket pair colorizer:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/15011519/158600466-184c3dd3-a0fc-431f-805b-d71c0398ba06.png">

Does this issue occur when all extensions are disabled?: No (but that's because I need the extension to have syntax highlighting at all)

- VS Code Version: 1.66.0-insider, Commit: 6fa3243d3facbbf8b87222bcf4e81c5eddf5d47f, Date: 2022-03-16T05:17:03.981Z
- OS Version: macOS 11.6.5

Steps to Reproduce:

1. Install the [PlantUML extension][ext]
2. Open up a file new and select `plantuml` as the language
3. Copy+paste the following code:
```plantuml
@startuml show-syntax-highlighting

entity Entity01 {
  * identifying_attribute
  --
  * mandatory_attribute
  optional_attribute
}

Entity01 }|..|| Entity02
Entity03 }o..o| Entity04
Entity05 ||--o{ Entity06
Entity07 |o--|| Entity08

@enduml
```
4. You should see error syntax highlighting on `}|..||`, `}o..o|`, and `||--o{` as in the image above

Is this a bug with the extension? Or with VS Code's bracket pair colorization?

[ext]: https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml
[er]: https://plantuml.com/ie-diagram

**Comment by hediet** [comment]
PlantUML should not mark `{` ... `}` as bracket pair, as they are not always balanced.

**Comment by nikoladev** [comment]
@hediet Is it possible to only sometimes mark `{` ... `}` as a bracket pair? Because there are valid use cases for curly braces as bracket pairs in PlantUML, see line 3 and line 8 in the image in the starting post.

**Comment by hediet** [comment]
See #144736.
