### ISSUE TITLE
Terminal overview ruler width doesn't change when zooming

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#145227]
Repro:

1. Open shell integration enabled terminal
2. Run some commands
3. Zoom in, the overview ruler should be the same width as the scroll bar

![image](https://user-images.githubusercontent.com/2193314/158614240-b330f901-7db2-46f0-9b83-62b4232f723b.png)

This also seems to apply on new terminals (is 10px hardcoded?), I also notice the overview ruler is 1 pixel too left at this particular zoom level (4):

![image](https://user-images.githubusercontent.com/2193314/158614601-b01f8759-b7a2-4a92-b30c-4a7523ab5739.png)
![image](https://user-images.githubusercontent.com/2193314/158614652-1cad6f4f-0a7c-4935-9cc2-f928d6abd802.png)

**Comment by Tyriar** [comment]
Decorations are tiny because of this on a macbook (dpr=2):
<img width="91" alt="Screen Shot 2022-03-17 at 10 54 31 am" src="https://user-images.githubusercontent.com/2193314/158865418-88da0fb7-842c-412a-8914-9cebffc0f179.png">

**Comment by meganrogge** [comment]
should this be up to the embedders or xterm.js to handle when dpr changes (when zooming etc)?

**Comment by meganrogge** [comment]
I see the renderers handle this themselves

https://github.com/xtermjs/xterm.js/blob/fea1079b1ec91b2406ea73a3cbda0e940436bf73/addons/xterm-addon-webgl/src/WebglRenderer.ts#L136-L143

**Comment by Tyriar** [comment]
Yep xterm.js should handle dpr changes

**Comment by meganrogge** [comment]
It does already. Looking at where overviewRulerWidth is set at the moment

**Comment by meganrogge** [comment]
https://github.com/xtermjs/xterm.js/blob/e293d29fd3306fc04b9a0b6fa5308eb16bb4f4d7/src/browser/Decorations/OverviewRulerRenderer.ts#L54

**Comment by meganrogge** [comment]
the problem 
https://github.com/microsoft/vscode/blob/d2433fba88b7b4699586c4bcf8f4c86b55144366/src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts#L134

**Comment by meganrogge** [comment]
should be `15`

**Comment by Tyriar** [comment]
That's fine (it should be CSS pixels), where ever it's used inside xterm.js should be multiplied by dpr though

**Comment by meganrogge** [comment]
it is

**Comment by meganrogge** [comment]
https://github.com/xtermjs/xterm.js/blob/e293d29fd3306fc04b9a0b6fa5308eb16bb4f4d7/src/browser/Decorations/OverviewRulerRenderer.ts#L109

**Comment by meganrogge** [comment]
reopening until the canvas width (which factors in dpr) is used for the decoration width

**Comment by Tyriar** [comment]
Looks like this is fixed now
