### ISSUE TITLE
on show of previously hidden terminal panel, overview ruler decorations are gone

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#145214]
Not sure on repro but I switch back to terminals sometimes and the overview ruler is gone:

![image](https://user-images.githubusercontent.com/2193314/158593757-c9376c3b-9822-4c79-986a-85d653b09ead.png)

**Comment by meganrogge** [comment]
pretty sure this is related to the scrollbar

**Comment by meganrogge** [comment]
Haven't seen this since the Zindex adjustment

**Comment by Tyriar** [comment]
Happened when switching to an old session in my current window:

![image](https://user-images.githubusercontent.com/2193314/158858293-e0944b0e-e7fb-4b26-ba92-02ae15fa6a2a.png)

Height of the canvas is 0:

![image](https://user-images.githubusercontent.com/2193314/158858520-56a11f7f-a82c-4f13-924d-43af9a9bf05e.png)

**Comment by Tyriar** [comment]
We're probably refreshing the canvas height when the terminal is not visible

**Comment by meganrogge** [comment]
should this issue be transferred to xterm.js?

we should return in refreshDecorations if the screen element's height is 0 I think

**Comment by Tyriar** [comment]
If it can be handled over there yes, could maybe fix by using an intersection observer in queueRefresh?

**Comment by meganrogge** [comment]
Repro is create two terminal tabs, click on 1 (hide the other). Click on the second 🐛 overview decorations are gone
