### ISSUE TITLE
Accounts button not working in Linux

### ISSUE THREAD

**Issue by sh0rtyc4t** [microsoft/vscode#145282]
Hello, I'm creating this issue because today I installed vscode for the first time on my new system, and as I normally do, I wanted to sync the settings saved in my Microsoft account. But when clicking on the accounts button nothing happens, I tried to wait a long time to load but nothing worked.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2-1646927742
- OS Version: Linux Debian 11.2

Steps to Reproduce:

1. Download and install vscode 
2. Initiate the program and click on Account the button

**Comment by TylerLeonhardt** [comment]
do you have a libsecret based application installed like gnome-keyring?

If you don't, installing gnome-keyring should fix this for you you.

If it does, I'm curious to ask... did vscode force you to log into your accounts every time you opened it before 1.65?

**Comment by LPRegen** [comment]
Worked for me on Arch Linux (5.16.14-arch1-1)

**Comment by shuvo360** [comment]
I am facing the same problem..i use manjaro kde.

**Comment by sh0rtyc4t** [comment]
> do you have a libsecret based application installed like gnome-keyring?
> 
> If you don't, installing gnome-keyring should fix this for you you.
> 
> If it does, I'm curious to ask... did vscode force you to log into your accounts every time you opened it before 1.65?

Thanks! Worked for me, I think there should be an error of missing dependencies when installing or opening the program

**Comment by educroch** [comment]
Worked for me on Arch 5.15.10-arch1-1.

**Comment by TylerLeonhardt** [comment]
cc @rzhao271 if you don't mind verifying this one for me on the monday insiders build.

**Comment by rzhao271** [comment]
Finally verified that a notification with a troubleshooting guide comes up.
