### ISSUE TITLE
[Feature Request] Bring VSCode On the Mac App Store

### ISSUE THREAD

**Issue by singhalrishi27** [microsoft/vscode#145289]
It would be so much easier if I could download this app from Mac App Store I won't have to check I have a apple silicon or intel Mac it will automatically be downloaded for appropriate Hardware eliminate all sorts of fiction like extracting zip copying into application folder and warnings like this app has been downloaded from an unknown source etc

there is already an issue but its 4 year old and vscode came to Microsoft Store but not on Mac App Store

**Comment by singhalrishi27** [comment]
Also Updating VS Code is Pain from its in app updater no progress bar no size no eta and any interruptions in network restarts the downloading from beginning

**Comment by joaomoreno** [comment]
We're keeping our original stance as _out of scope_: https://github.com/microsoft/vscode/issues/19544
