### ISSUE TITLE
"Minimize window" shortcut doesn't work on MacOS Monterey

### ISSUE THREAD

**Issue by sereyn** [microsoft/vscode#145205]
For every app on MacOS, the shortcut to minimize the window is "cmd+m". This is not working with vscode.

I guess vscode is intercepting the event but doesn't do anything with it. I would like that it minimizes the vscode window, like every other app.

**Comment by sereyn** [comment]
It was an extension, sorry 😅

**Comment by aNullValue** [comment]
For any future people who happen across this issue: I had the same problem; I've always depended upon Cmd+M to minimize my window, and suddenly today it stopped working (though I hadn't used VSCode for a few weeks). I still haven't figured out what caused it, but I was able to "fix" my problem by disabling all of my extensions and then re-enabling them.
