### ISSUE TITLE
Image zoom out when holding shift key

### ISSUE THREAD

**Issue by nattwasm** [microsoft/vscode#145355]
When holding down the shift key, it's expected is to be able to zoom out (opposite of current action, in this case zooming in) and change to zoom out cursor
<img width="1137" alt="CleanShot 2022-03-17 at 15 20 24@2x" src="https://user-images.githubusercontent.com/31426677/158903852-091caacf-9a42-4607-9afb-f2fc96b56a68.png">

**Comment by mjbvz** [comment]
Try holding down `option` / `alt` for this instead
