### ISSUE TITLE
Installing extensions into remote host doesn't work

### ISSUE THREAD

**Issue by gbritton1** [microsoft/vscode#145319]
Issue Type: <b>Bug</b>

1.  connect to remote host

2.  view extensions

3.  try to install any extension on the remote host

4.  nothing happens

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)

OS version: Windows_NT x64 10.0.19042

Restricted Mode: No

Remote OS version: Linux x64 3.10.0-1160.49.1.el7.x86_64

 

<details>

<summary>System Info</summary>

 

|Item|Value|

|---|---|

|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|

|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|

|Load (avg)|undefined|

|Memory (System)|31.84GB (15.38GB free)|

|Process Argv|.\\.ssh\\config --crash-reporter-id 004025b8-1239-4199-b821-cb00c2f87a05|

|Screen Reader|yes|

|VM|0%|

 

|Item|Value|

|---|---|

|Remote|SSH: batbvapv10|

|OS|Linux x64 3.10.0-1160.49.1.el7.x86_64|

|CPUs|Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz (40 x 2300)|

|Memory (System)|125.63GB (0.67GB free)|

|VM|0%|

</details><details><summary>Extensions (11)</summary>

 

Extension|Author (truncated)|Version

---|---|---

jupyter-keymap|ms-|1.0.0

remote-ssh|ms-|0.76.1

remote-ssh-edit|ms-|0.76.1

jenkinsfile-support|sec|0.1.0

vscode-edit-csv|jan|0.6.6

rainbow-csv|mec|2.0.0

python|ms-|2022.2.1924087327

vscode-pylance|ms-|2022.3.2

jupyter|ms-|2022.2.1030672458

jupyter-renderers|ms-|1.0.6

csv-to-table|php|1.4.0

 

 

</details><details>

<summary>A/B Experiments</summary>

 

```

vsliv368cf:30146710

vsreu685:30147344

python383cf:30185419

vspor879:30202332

vspor708:30202333

vspor363:30204092

pythonvspyl392:30443607

pythontb:30283811

pythonptprofiler:30281270

vshan820:30294714

vstes263cf:30335440

pythondataviewer:30285071

vscod805cf:30301675

pythonvspyt200:30340761

binariesv615:30325510

bridge0708:30335490

bridge0723:30353136

vsaa593cf:30376535

vsc1dst:30438360

pythonvs932:30410667

wslgetstarted:30449410

vsclayoutctrt:30451275

dsvsc009:30452663

pythonvsnew555:30450902

vscscmwlcmc:30438804

vscgsvid1:30447480

dockersurvey3:30453609

pynewfile477:30450038

 

```

 

</details>

**Comment by sandy081** [comment]
Can you please share following logs when you click on Install action?

- Enable log level to trace - F1 > Set Log Level... > Trace
- Click on `Install on...` action
- Share following logs:
  - F1 > Open View... > Log (Window)
  - F1 > Open View... > Log (Remote)

**Comment by gbritton1** [comment]
> > Note that I when I try to view the remote log, VS Code hangs,
> 
> This hints that your remote connection is not healthy and hence I suspect that extension installation on remote is not working.
> 
> @alexdima Is there a way to troubleshoot if remote connection is active/healthy or not?

I use the remote connection all day every day without issue for editing files, running terminal commands and more.  The only thing that *doesn't* work is installing remote extensions

**Comment by alexdima** [comment]
> Is there a way to troubleshoot if remote connection is active/healthy or not?

This is shown in the status bar e.g.:

<img width="358" alt="image" src="https://user-images.githubusercontent.com/5047891/159328646-d245e2b9-a87e-42ee-82eb-e46357b5b570.png">

**Comment by gbritton1** [comment]
Just tried: remote.downloadExtensionsLocally 

It did not resolve the issue

**Comment by sandy081** [comment]
Please share the window log after enabling the setting `remote.downloadExtensionsLocally`. Please do following:

- Open Window log - F1 > Open View.. > Log (Window)
- Clear the log
- Set log level to trace
- Try installing the extension
- Wait for some time
- Share the window log

**Comment by gbritton1** [comment]
attached 
[renderer3.log](https://github.com/microsoft/vscode/files/8319183/renderer3.log)

**Comment by sandy081** [comment]
From the log, I can say the client is behaving properly. We would need remote logs to know what is happening. Can you please share a gif/video of what you are seeing when you try to access remote server log?

**Comment by gbritton1** [comment]
Remove agent log
[remoteagentLog.log](https://github.com/microsoft/vscode/files/8324627/remoteagentLog.log)

**Comment by sandy081** [comment]
Thanks for the log - Can you please confirm if you followed these [steps](https://github.com/microsoft/vscode/issues/145319#issuecomment-1074287468) before capturing the remote agent log? Because I am not finding following statement in the log `ExtensionManagementService#install`

**Comment by gbritton1** [comment]
confirmed

**Comment by gbritton1** [comment]
I just cleared those logs and retried the install, fresh (short!) logs attached
[log.zip](https://github.com/microsoft/vscode/files/8324993/log.zip)

**Comment by sandy081** [comment]
Thanks for the logs - It seems that the server has not received the client request, if it would have received I shall have seen following statement in the remote server log

```
ExtensionManagementService#install
```

@alexdima Can you please help here to debug this - Client has requested server to install extension but the server has not received the request. It seems the connection status is good.

@gbritton1 Just to confirm can you please clear all logs also in Developer Tools: Console and also clear network requests in Developer Tools and retry. Please look for any errors in the console and also check if the request to Marketplace is successful. These request might look something like this

```
https://ritwickdey.gallery.vsassets.io/_apis/public/gallery/publisher/ritwickdey/extension/LiveServer/5.7.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?redirect=true&install=true

https://ritwickdey.gallerycdn.vsassets.io/extensions/ritwickdey/liveserver/5.7.5/1646738284779/Microsoft.VisualStudio.Services.VSIXPackage
```

**Comment by alexdima** [comment]
@sandy081 Does `ExtensionManagementService#install` appear for you on the remote server log with these steps? From looking at `LogLevelChannel`, I believe setting the log level to trace on the client side has no effect on the log level of the server side.

**Comment by gbritton1** [comment]
[VSCode Extension Issue 145319.zip](https://github.com/microsoft/vscode/files/8333604/VSCode.Extension.Issue.145319.zip)

Uploaded fresh logs and console s/s (How to save that as text?) 

Found the root cause, maybe.  the remote host cannot access the windows.net host.  Can't even ping it.  Local host accesses fine, so maybe a firewall is the culprit.

However,  I think the **extension installer should report the problem** in some obvious way.

**Comment by sandy081** [comment]
@alexdima I can see the trace logs in the remote server log and I confirm that log level is updated in the server.

**Comment by gbritton1** [comment]
> > Found the root cause, maybe. the remote host cannot access the windows.net host. Can't even ping it. Local host accesses fine, so maybe a firewall is the culprit.
> 
> Not sure what do you mean by this? Do you mean remote machine does not have network connection? Or the remote machine itself is not accessible from the client?
> 
> Regarding logs, I do not see the network requests tab in developer tools. Can you please confirm if the extension is getting downloaded?

The console log screenshot has the error: DevTools failed to load source map, with a url

On my remote host, I cannot reach that host, though I can on my local side

**Comment by gbritton1** [comment]
I attached the network trace file, zipped
[vscode-app.zip](https://github.com/microsoft/vscode/files/8335397/vscode-app.zip)

**Comment by sandy081** [comment]
Thanks for the logs - It seems the extension is getting downloaded successfully on the client. After downloading the extension, client asks the remote to install the VSIX - and I do not see that request on the server as I am not seeing the log statement. 

https://github.com/microsoft/vscode/blob/c726a43b774d23a89ea33cf82ffafb4677d16eb1/src/vs/workbench/services/extensionManagement/electron-sandbox/remoteExtensionManagementService.ts#L98

@alexdima any insights?

**Comment by gbritton1** [comment]
interestingly, I do not see the extension under ~/.vscode-server/extensions.  should it be there?

**Comment by alexdima** [comment]
@gbritton1 While the extension is installing are you able to create a new file in the explorer or do `ls` in a terminal? Both creating files and terminal input/output make use of the same connection as the one used by the remote extension installation and it would be helpful to find out if it is healthy or not.

**Comment by gbritton1** [comment]
yup

**Comment by alexdima** [comment]
@gbritton1 Some extensions require a post install step which might download things from the internet (I think C# is one of those). Could you please try installing a very small extension like `alexdima.copy-relative-path`?

**Comment by gbritton1** [comment]
copy-relative path worked

**Comment by sandy081** [comment]
Interesting, so only C# extension seems to be not working. Can you please share the logs while installing `alexdima.copy-relative-path` extension?

**Comment by gbritton1** [comment]
[rendererLog.txt](https://github.com/microsoft/vscode/files/8342591/rendererLog.txt)


seems the install worked though the extension itself threw an error
[remoteExtHostLog.txt](https://github.com/microsoft/vscode/files/8342515/remoteExtHostLog.txt)

**Comment by gbritton1** [comment]
I got C# working.  just a really slow install

**Comment by sandy081** [comment]
Right, C# extension is larger in size and it might take time for downloading.
