### ISSUE TITLE
Using VS Code as external tool to open a file sometimes results in file not found error

### ISSUE THREAD

**Issue by martin-wiseweb** [Microsoft/vscode#14534]
- VSCode Version: **1.6.1**
- OS Version: **Windows 10**

Steps to Reproduce:
1.  Create a password-protected archive with 7-Zip (`.zip` for example)
2.  Open anything else in VS Code
3. Open the password-protected archive, and try to open a file with VS Code

Expected Result:
- The file would open in a new VS Code window

Actual Result:
- A new VS Code window opens with nothing loaded

**Comment by bpasero** [comment]
@martin-wiseweb can you show me how this flow goes? do you leave the zip archive untouched?

@joaomoreno fyi this could be your bug

**Comment by joaomoreno** [comment]
Yes, this is #13919.

@martin-wiseweb Please re-associate Code with those file types.

**Comment by martin-wiseweb** [comment]
@joaomoreno There is no fancy filetypes. In this case, I'm opening a `.yml` file and it's already associated to VS Code. When VS Code is not already open, it opens just fine.

I tried to remove `--open-url` from the registry and it did not help

**Comment by joaomoreno** [comment]
So, when opening the same file, but outside the archive, it works?

**Comment by martin-wiseweb** [comment]
Yes. I can also open the same file within the archive, if VS code is not already open

**Comment by joaomoreno** [comment]
If you associate the file with another text editor, can you locate where 7Zip places the file temporarily?

**Comment by martin-wiseweb** [comment]
Changed default file association to Sublime, and it seems to work.

The file is placed: `%USERPROFILE%\AppData\Local\temp\<some random dir>\<myfile>`

**Comment by martin-wiseweb** [comment]
I think I will open an issue on [7-zip](https://github.com/Strachu/7-zip) repo too, they might have some info.

**Comment by bpasero** [comment]
Something weird is going on with 7zip, it seems to delete the files right after opening them? What seems to work a little bit better for me is to configure:

"window.openFilesInNewWindow": false

But those files in VS Code seem to be gone right after. Setting as upstream, this is fishy behaviour in 7zip. I believe they delete the file right after creating the tmp file and on startup we always check if a path exists and refuse to open if it does not.

**Comment by joaomoreno** [comment]
@bpasero That is the behaviour I predicted. Double click a file inside 7Zip will make 7Zip put the file in a temporary location and spawn a process with that file. Now, the file shouldn't lay around forever, especially if it comes from a password protected archive, so 7Zip needs to eventually delete it. The best indicator 7Zip has that the file isn't being used anymore by the process is the fact that the process itself remains alive.

It works in Sublime because sublime.exe stays alive for the duration of the Sublime lifespan.

We have a different startup mechanism in which the starting process dies immediately. 7Zip would need to use the `--wait` argument for this to work.

**Comment by martin-wiseweb** [comment]
Okay... so how do I get this to work, guys?

**Comment by joaomoreno** [comment]
Actually this works for me on the latest Insiders. @martin-wiseweb wanna give it a try on the latest Insiders?

**Comment by bpasero** [comment]
With todays insider build (get it from http://code.visualstudio.com/Download#insiders) there is a new setting `workbench.editor.closeOnFileDelete` that will keep editors open when set to `false` provided that the file has been deleted outside of Code. This might help in this case here, please let me know.

**Comment by bpasero** [comment]
This should work OK now if you set `workbench.editor.closeOnFileDelete: false`
