### ISSUE TITLE
The terminal process failed to launch when I reopen VSCode after using Command+Q to quit VSCode

### ISSUE THREAD

**Issue by SilvRunrun** [microsoft/vscode#145364]
1. create a directory at path: /Users/ma/本地/demo_project.(contains Chinese component)
2. open the directory from VSCode top menu: File - Open...
3. open a new terminal from top menu: Terminal - New Terminal. and terminal window automatically goes to path (demo_project).
4. use Command + Q shortcut to quit VSCode completely.
5. reopen VSCode from mac dock icon. and VSCode shows error: The terminal process failed to launch: Starting directory (cwd) "/Users/ma/\xe6\x9c\xac\xe5\x9c\xb0/demo_project" does not exist.
6. when the path in step1 does not contain Chinese(like /Users/ma/local/demo_project.), no error shows. the error only shows when the path contains Chinese.

Extra VSCode information：
Version: 1.65.2 (Universal)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z (1 wk ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.4.0

**Comment by SilvRunrun** [comment]
> * create a directory at path: /Users/ma/本地/demo_project.(contains Chinese component)
> * open the directory by VSCode.
> * open a new terminal from top menu: Terminal - New Terminal. and terminal window automatically goes to path (demo_project).
> * use Command + Q shortcut to quit VSCode completely.
> * reopen VSCode from mac dock icon. and VSCode shows error: The terminal process failed to launch: Starting directory (cwd) "/Users/ma/\xe6\x9c\xac\xe5\x9c\xb0/demo_project" does not exist.
> * when the path in step1 does not contain Chinese(like /Users/ma/local/demo_project.), no error shows. the error only shows when the path contains Chinese.

**Comment by Tyriar** [comment]
To verifier: When testing make sure shell integration is off
