### ISSUE TITLE
Printing CSV files line by line does not work in the java vscode terminal.

### ISSUE THREAD

**Issue by Kainech** [microsoft/vscode#145302]
Issue Type: <b>Bug</b>

I have been sat here for a long long time trying to figure this out. I have been googling for hours, i have tried everything i possibly can.
The file runs and there are no errors what so ever, but it simply won't appear in the console.
Moving to another software works just fine, vscode works fine too, but its no use to me if i can see the data im reading in the output section.
Please get back to me on this.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by meganrogge** [comment]
You'll need to file an issue with the java extension about this
