### ISSUE TITLE
Generate invalid encoding file when saving (Ctrl +S)

### ISSUE THREAD

**Issue by silabs-trtrinh** [microsoft/vscode#145331]
- VS Code Version: 1.65
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Open project
2. Save a file
3. Auto-generate file invalid encoding

![Capture](https://user-images.githubusercontent.com/94961032/158856730-c3cf5a1f-b3de-4ece-8988-2cf0c063ad50.PNG)

**Comment by gjsjohnmurray** [comment]
Maybe a duplicate of https://github.com/microsoft/vscode/issues/145297

**Comment by silabs-trtrinh** [comment]
Done, Thank you @gjsjohnmurray I uninstall old plugins and re-install them
