### ISSUE TITLE
symbol search in shellscript

### ISSUE THREAD

**Issue by brianjmurrell** [microsoft/vscode#145399]
Issue Type: <b>Feature Request</b>

It would be nice if shell script (i.e. bash, /bin/sh, etc.)  symbol searching worked.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.16.12-200.fc35.x86_64
Restricted Mode: No

**Comment by aeschli** [comment]
Maybe https://marketplace.visualstudio.com/items?itemName=mads-hartmann.bash-ide-vscode already provides that?

**Comment by brianjmurrell** [comment]
Hrm.  Interesting find.  At first glance, it appears to.  I will give that some more attention.  Thanks @aeschli.

FWIW, I did look for an extension for this.  Clearly I just didn't have the right search terms or even concepts.
