### ISSUE TITLE
vscode ignores leading zeros of file name

### ISSUE THREAD

**Issue by silphire** [microsoft/vscode#145365]
Issue Type: <b>Bug</b>

* launch vscode as `code 0123`
* vscode opens a file named "123"

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (16.53GB free)|
|Process Argv|--crash-reporter-id bfa167ff-3a61-4529-af0b-cc0c168abf10|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|15.59GB (12.73GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
gitkraken-authentication|git|1.0.3
better-cpp-syntax|jef|1.15.13
vscode-language-pack-ja|MS-|1.65.3
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.224.3
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
doxdocgen|csc|1.4.0
vscode-pull-request-github|Git|0.38.1
go|gol|0.32.0
better-cpp-syntax|jef|1.15.13
vscode-docker|ms-|1.20.0
vscode-language-pack-ja|MS-|1.65.3
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.2
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cmake-tools|ms-|1.10.4
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5449
vsliveshare-audio|ms-|0.1.91
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmt:30438805
pynewfile477:30450038

```

</details>

**Comment by bpasero** [comment]
Wild guess: `minimist` CLI parsing issue. And I think we had issues like this in the past.

**Comment by mariamhmahmoud** [comment]
Hi, I'd like to work on this issue if possible!
