### ISSUE TITLE
When split to two views, the unactive view for jupyter notebook is not fixed

### ISSUE THREAD

**Issue by AnakinShieh** [microsoft/vscode#145340]
Issue Type: <b>Bug</b>

Perhaps it's not a bug, but when split to two different views and modify one of them, jupyter notebook doesn't work as common python file.

For example, when you try to add a lot lines from top, the unactive view would be fixed to current position, but not scroll up in common python file or jupyter notebook web version. But in vsc juypyer notebook, it scrolls up which is annoying since it would make multiple views totally meaningless.

Extension version: 2022.2.1924087327
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.92GB (84.87GB free)|
|Process Argv|--crash-reporter-id de098579-2cc4-4e22-8ec0-f3fd8b564df0|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
testflightcf:30433671
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30450902
vscscmwlcmt:30438805
dockersurvey3:30453609
pynewfile477cf:30450039

```

</details>

**Comment by rebornix** [comment]
Thanks for the feedback, good catch.
