### ISSUE TITLE
If I type non-alphabet, the letters look truncated.

### ISSUE THREAD

**Issue by aio39** [microsoft/vscode#145314]
Issue Type: <b>Bug</b>

If I type non-alphabet, the letters look truncated.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22572
Restricted Mode: No
Remote OS version: Linux x64 5.10.93.2-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800HS with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|39.42GB (16.23GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bub/home/aio/dev/miko-nest --crash-reporter-id d07f4b64-6250-43a2-bd03-255bab3a1856|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: ub|
|OS|Linux x64 5.10.93.2-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 4800HS with Radeon Graphics (16 x 2894)|
|Memory (System)|19.25GB (14.35GB free)|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|12.5.0
vscode-sqlite|ale|0.14.0
laravel-extra-intellisense|ami|0.6.2
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
tab-jumper|Chr|1.0.4
laravel-goto-view|cod|1.3.7
vscode-eslint|dba|2.2.2
vscode-styled-jsx-languageserver|Div|1.3.1
quicktype-refresh|dog|0.1.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.4
vscode-npm-script|eg2|0.3.24
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.3.0
comment-anchors|Exo|1.9.6
auto-rename-tag|for|0.1.10
vscode-drawio|hed|1.6.4
vscode-peacock|joh|4.0.1
vscode-language-babel|mgm|0.0.36
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.20.0
vscode-language-pack-ko|MS-|1.65.3
vscode-edge-devtools|ms-|1.4.5
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.2
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.9.4
vsliveshare|ms-|1.0.5449
debugger-for-chrome|msj|4.13.0
vetur|oct|0.35.0
indent-rainbow|ode|8.2.2
laravel-blade|one|1.32.0
material-icon-theme|PKi|4.14.1
code-settings-sync|Sha|3.4.3
sonarlint-vscode|Son|3.3.3
autoimport|ste|1.5.4
code-spell-checker|str|2.1.7
sass-indented|syl|1.8.19
html5resetcss|the|1.1.1
vscode-status-bar-format-toggle|tom|3.0.0
errorlens|use|3.4.2
vscode-wakatime|Wak|18.0.7
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
save-as-root|yy0|1.3.9

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmc:30438804
vscgsvid1:30447480
dockersurvey3cf:30453610
pynewfile477:30450038

```

</details>

**Comment by aio39** [comment]
![image](https://user-images.githubusercontent.com/68348070/158822368-ae91388f-50c6-4ca4-bf16-7bde85c310d9.png)
![image](https://user-images.githubusercontent.com/68348070/158822441-d5156628-5f2e-42ae-b4e4-80463e9d43bf.png)
![image](https://user-images.githubusercontent.com/68348070/158822526-65742e9b-cfda-4dc5-9db2-8108afa3dec4.png)

**Comment by alexdima** [comment]
@aio39 Could you please check your settings, are you perhaps using a non zero value for `"window.zoomLevel"` or perhaps are you using zoom at the level of the operating system ?

**Comment by aio39** [comment]
> 



> @aio39 Could you please check your settings, are you perhaps using a non zero value for `"window.zoomLevel"` or perhaps are you using zoom at the level of the operating system ?

![image](https://user-images.githubusercontent.com/68348070/158982000-8008f5f2-ee5b-4a3d-ab8c-59c5ca02d1aa.png)
@alexdima 
It was resolved by setting window.zoomLevel to 0. Thank you.

**Comment by alexdima** [comment]
Let's track in #144691
