### ISSUE TITLE
Fine black lines visible in multi-line selection

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#14537]
- VSCode Version: Code - Insiders 1.7.0-insider (889c720db5e83f4649ba1317fc8fdd3387cbf975, 2016-10-26T06:50:42.691Z)
- OS Version: Windows_NT ia32 10.0.10586

Open larger file, select all.
I see fine black lines in the selection, but now for all lines.
![image](https://cloud.githubusercontent.com/assets/6461412/19729067/fb45a5dc-9b95-11e6-83b3-37905544ff91.png)
It's also visible when zooming in.
![image](https://cloud.githubusercontent.com/assets/6461412/19728945/9ad73896-9b95-11e6-9f4a-0b039de8b1f7.png)

**Comment by weinand** [comment]
@aeschli are you running Windows in Parallels on macOS and on a retina display?
IIRC It could be related to that...

**Comment by alexandrudima** [comment]
@aeschli Are you running with any sort of zoomLevel set? What happens when you go to https://microsoft.github.io/monaco-editor/

If you inspect the dom nodes, are they positioned at integer coordinates (`top`) of the dom node?

**Comment by aeschli** [comment]
@alexandrudima No it's on my Lenovo X1. It also has 'kind of retina' resolution. I'll check when in the office...

**Comment by alexandrudima** [comment]
Closing after a number of days without a response
