### ISSUE TITLE
Debug: break on exception does not reveal line properly in minified source

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145372]
Steps to Reproduce:

1. use insiders
2. add a breakpoint into `src/vs/workbench/services/workingCopy/test/electron-browser/workingCopyHistoryService.test.ts` line `150`
3. enable "Caught Exceptions" and "Uncaught Exceptions" break points
4. debug the `addEntry` test using the `ms-vscode.vscode-selfhost-test-provider` extension

=> 🐛  you end up in this file but the line that is breaked on is not revealed properly

![image](https://user-images.githubusercontent.com/900690/158950071-fcb07da2-e298-4f96-a0c7-24838565b6e0.png)

Rather it should have revealed this line:

![image](https://user-images.githubusercontent.com/900690/158950100-095e513d-7375-4557-a71c-cebbee269388.png)

**Comment by alexdima** [comment]
@connor4312 @roblourens What editor method is debugging calling on the editor in this case?

**Comment by alexdima** [comment]
I'm asking because if you're calling `revealLineInCenter` you can switch to use `revealRangeInCenter`.

**Comment by connor4312** [comment]
We are, I'll see if that fixes it

**Comment by connor4312** [comment]
Works nicely, thanks for the tip :)

**Comment by bpasero** [comment]
👏

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/159475483-f46d3bd9-83c7-4b8e-86be-5d8af2149d1d.png)

Helpful now 👍
