### ISSUE TITLE
Local history: add a button to open the backup folder of a given file

### ISSUE THREAD

**Issue by badrelmers** [microsoft/vscode#145330]
It is hard to find the backup folder of a given file inside the History folder, because folders are hashes of the original file name, it would be useful to add a button to open that backup folder (so we can easily grep inside it or delete some or all the entries...).

This button will be useful to appear in the "timeline page" menu `...` and near the entries of the command "Local History: Find Entry to Restore" 

timeline page:
![image](https://user-images.githubusercontent.com/40046489/158853050-cc7c3216-fa29-4694-a61a-27671e76a2f6.png)

**Comment by bpasero** [comment]
Added a "Reveal in Finder" right click action:

![image](https://user-images.githubusercontent.com/900690/158978854-c02c4822-4031-4a00-b582-77b19204930a.png)

**Comment by badrelmers** [comment]
super it seems to work on files too, thank you very much.
