### ISSUE TITLE
pre-commit npm package breaks GIT commit

### ISSUE THREAD

**Issue by ThePeach** [Microsoft/vscode#14535]
- VSCode Version: 1.6.1
- OS Version: Linux (Arch - latest)

**Steps to Reproduce:**
1. install pre-commit via npm `npm install pre-commit` 
2. configure pre-commit script to be triggered in `package.json`, e.g. 
   `json
   {
     "scripts": { "test": "uname -a" },
     "pre-commit": [ "test" ]
   }
   `
3. try to commit via the internal GIT tool

**Expected Results:**

committing should work without problems

**Actual Results:**

Committing will result in the following error:

``` shell
git commit --quiet --allow-empty-message --file -
.git/hooks/pre-commit: line 49: : command not found
.git/hooks/pre-commit: line 49: : command not found
```

**Comment by joaomoreno** [comment]
Does it work when running from the command line?

**Comment by ThePeach** [comment]
hi @joaomoreno, yes it does.

**Comment by ThePeach** [comment]
I'd also like to add that I'm using `nvm` and `.nvmrc` for node version management so I don't know if that has any implications in this behaviour.

**Comment by joaomoreno** [comment]
Does it work when running `code` from the command line?

**Comment by ThePeach** [comment]
@joaomoreno: yes it does

**Comment by joaomoreno** [comment]
Strange, sorry for asking that twice. Can you show me the contents of `.git/hooks/pre-commit`?

**Comment by ThePeach** [comment]
@joaomoreno https://github.com/observing/pre-commit/blob/master/hook

**Comment by joaomoreno** [comment]
`$BINARY` seems to be empty. They even source your `bashrc` et al. Maybe add some statements in that script that will help you find why the hook can't find `node`?

**Comment by ThePeach** [comment]
so the whole initialization of node is currently handled by [`nvm`](https://github.com/creationix/nvm). I do use [`.nvmrc`](https://github.com/creationix/nvm#nvmrc) on a per-project basis, which selects the right version of node.
Maybe this issue should be converted into a feature request to implement and use `nvm` and `.nvmrc` support?

**Comment by joaomoreno** [comment]
Any chance I can clone the repo and try it out myself?

**Comment by ThePeach** [comment]
unfortunately not, but I can try to set-up a barebone project here on GitHub to replicate the behaviour so you can try it, but I won't be able to do it before the weekend thou. Once again it can be replicated by having nvm and the node dependency, and configure it as explained in the issue description.

**Comment by joaomoreno** [comment]
That would be awesome, let me know. :+1:

**Comment by joaomoreno** [comment]
That would be awesome, let me know. :+1:

**Comment by joaomoreno** [comment]
Closing due to silence.
