### ISSUE TITLE
Debug console cuts last line of pandas dataframe

### ISSUE THREAD

**Issue by ghuname** [microsoft/vscode#145347]
Issue Type: <b>Bug</b>

1. put this code in main.py
```
import pandas as pd

df = pd.DataFrame(
    {
        'A': [1, 2, 3, 4],
        'B': ['x', 'y', 'z', 'w']
    }
)

print(df)

pass
```
2. set a breakpoint on line with "pass"
3. start debugging main.py
4. notice in output 4 rows (0-3):
```
   A  B
0  1  x
1  2  y
2  3  z
3  4  w
```
5. go to debug console and enter df <enter>, last row is missing (only 0-2):
```
df
   A  B
0  1  x
1  2  y
2  3  z
```

Debug should show last row of the dataframe.

Extension version: 2021.12.1559732655
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64

**Comment by ghuname** [comment]
The important thing is that when you start executing "df" in debug console, you have to execute it several times (depends on size of the debug console panel) in order to fill out debug console output.
Then new execution of "df" will be with missing last row.

**Comment by roblourens** [comment]
I think this is the same scrolling issue that I am fixing in https://github.com/microsoft/vscode/issues/117674. Will be sure to test that case with my fix.
