### ISSUE TITLE
Allow saving markdown preview as an HTML document

### ISSUE THREAD

**Issue by areyoureddy** [Microsoft/vscode#14538]
Feature request.

VS Code already does a great job of rendering markdown previews in a web view, it would be great if we could have the option to right click and save the preview as an HTML file like Atom allows us to do.

**Comment by eaglexiang** [comment]
VS-Code markdown preview supports self-defined css now, but the third HTML build extension doesn't. Wish new feature can support it.

**Comment by mjbvz** [comment]
This is not functionality I feel should be in the core markdown extension. The idea of the markdown preview is to give you preview of what your document will look like in production, and we allow customizing the preview CSS to that end.

Using the preview to generate html is the opposite of this intent. Such functionality also bring up many design complexities and lots of edge cases to consider. 

An extension should be able to provide this functionality if you absolutely need it, but I would encourage setting up a simple markdown-to-html build pipeline instead: https://code.visualstudio.com/Docs/languages/markdown#_compiling-markdown-into-html

**Comment by yukulele** [comment]
Markdown preview should should allow to save as HTML fragment without CSS
