### ISSUE TITLE
Incredibly sticky quick open from very prominent action

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#145376]
![image](https://user-images.githubusercontent.com/22350/158963827-187f751b-41e8-4172-baed-242cbe655060.png)

Clicking this button will open the layout quick open menu, which is incredibly sticky. Suggestions to make it less sticky:

- Clicking the button should always toggle visibility, instead of always making sure it's visible 
- Clicking outside the quick open should close it, while clicking actions within it shouldn't

**Comment by gjsjohnmurray** [comment]
See #145020

**Comment by sbatten** [comment]
can take the first piece

**Comment by sbatten** [comment]
resolving this to https://github.com/microsoft/vscode/issues/145376
