### ISSUE TITLE
opening vscode.d.ts takes too long

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#145327]
Issue Type: <b>Bug</b>

in today's Insiders opening vscode.d.ts takes too long (about 30 seconds) and I see this alert:

<img width="1658" alt="CleanShot 2022-03-17 at 17 24 48@2x" src="https://user-images.githubusercontent.com/1898161/158847555-13d5f5d2-99df-4450-ab40-c83ae9839f52.png">

VS Code version: Code - Insiders 1.66.0-insider (db0525ff4ba814780e901a5b9e399aaf596b9b20, 2022-03-17T05:18:05.656Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|32.00GB (0.33GB free)|
|Process Argv|--crash-reporter-id 785023c0-aeb7-4708-b29f-2c6aa9e59a8d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.5.0
esbuild-problem-matchers|con|0.0.2
vscode-eslint|dba|2.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vsclayoutctrt:30405800
dsvsc009:30440021
pythonvsnew555:30438690
vscscmwlcmc:30428972
vscgsvidc:30433759
dockersurvey3:30438168
pynewfile477:30451556

```

</details>

**Comment by weinand** [comment]
@mjbvz since you are not able to reproduce this, I've tried to investigate more...

When trying with a clean "user-data-dir"  the problem no longer occurs, so it seemed that the culprit was some persisted state or setting...
After doing a "bisect" on my settings I found this setting to be the problem:
```json
    "editor.wordWrap": "on",
```

I haven't touched that setting for years, so something must have changed in today's Insiders.

**Comment by alexdima** [comment]
@weinand We have two algorithms for computing wrapping points, one that is fast and assumes that characters are of the same width, and one which delegates each line's wrapping point computation to the browser. This is toggled using:

```
"editor.wrappingStrategy": "advanced"
```

Could you please check if you have been using also that setting?

**Comment by weinand** [comment]
@alexdima indeed, I was using `"editor.wrappingStrategy": "advanced"`. Setting it to `simple` fixed the problem.

But I still don't understand why this slowness started recently. I have not touched `"editor.wordWrap"` and `"editor.wrappingStrategy"` for months...

**Comment by alexdima** [comment]
After doing `./node_modules/.bin/vscode-bisect --verify-main-branch -r desktop`, it ends up pointing to https://github.com/microsoft/vscode/compare/f407da25ec62fc82d8f038eb4ae0df1fe8ff246a...6b7453421201c888b81eae5c04ec822a6423608f .

I believe it is https://github.com/microsoft/vscode/commit/32d40cf44e893e87ac33ac4f08de1e5f7fe077fc , the Electron 17 update.

**Comment by deepak1556** [comment]
I am unable to repro with latest insiders with `"editor.wrappingStrategy": "advanced","editor.wordWrap": "on"`, closing as resolved.
