### ISSUE TITLE
View toolbar actions hide when showing a menu unless `menuAsChild: true` is provided

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#145381]
Issue Type: <b>Bug</b>

Testing #145232

![junk](https://user-images.githubusercontent.com/6726799/158979317-6851742f-c02b-43b5-bc3d-2f8cfa9283bc.gif)

/assign @bpasero 

VS Code version: Code - Insiders 1.66.0-insider (d572d6e9d1282b352227916cb8f95bb2b03ddcaa, 2022-03-18T05:15:32.366Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by bpasero** [comment]
Reproduces when custom menus are enabled or on Windows.

@sandy081 @sbatten any idea how to solve this? Looks like the menu takes focus away from the view toolbar and then entries hide.

Interestingly this does not happen with "..." menu, so I might be setting up the dropdown wrong:

![image](https://user-images.githubusercontent.com/900690/158987363-2d1aa512-2244-4ea9-89e4-5385c80b2b3e.png)

**Comment by sbatten** [comment]
dropdowns can opt in to rendering the menu as a child element which prevents focus loss https://github.com/microsoft/vscode/blob/442227c0db5b9d298d896efd4c72f8c762e4e59b/src/vs/base/browser/ui/dropdown/dropdown.ts#L212

**Comment by bpasero** [comment]
@sbatten I do not really create the dropdown menu, someone else seems to do that from the `Toolbar` of the view, I think the action item is being created from here:

https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/workbench/browser/parts/views/viewPane.ts#L512

But we do not pass the option in, nor do I know how to pass this in from the outside.

To clarify, here is how I create the menu:

https://github.com/microsoft/vscode/blob/714420d4c9ed7a7de213185ec7fa0988dac57778/src/vs/workbench/contrib/timeline/browser/timelinePane.ts#L1210-L1216

**Comment by bpasero** [comment]
I was able to solve this from the `TimelinePane` by overriding `getActionViewItem` and passing the related option down:

https://github.com/microsoft/vscode/blob/801ad86ce10939dbca554f764e6b767223be8973/src/vs/workbench/contrib/timeline/browser/timelinePane.ts#L969-L971

It sounds to me though that this should be made the default somewhere in a generic supertype so that not every view has to adopt this when they show a menu.

**Comment by sandy081** [comment]
Moved the change to base class

**Comment by bpasero** [comment]
Thanks!
