### ISSUE TITLE
Several tasks in task manager

### ISSUE THREAD

**Issue by mbeckenbach** [Microsoft/vscode#14530]
Is it intended that one vs code instance produces 7 tasks at the moment it starts?

- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: abierbaum.vscode-file-peek-1.0.1, AdamCaviness.theme-monokai-dark-soda-0.0.5, benjpas.close-all-1.0.2, christian-kohler.path-intellisense-1.1.0, dbalage.vscode-stylesheet-formatter-0.2.0, DSKWRK.vscode-generate-getter-setter-0.4.1, dweber019.vscode-style-formatter-0.0.2, eg2.tslint-0.5.39, fknop.vscode-npm-3.3.0, formulahendry.auto-close-tag-0.3.4, formulahendry.auto-rename-tag-0.0.7, HookyQR.beautify-0.5.2, iBotMedia.tstools-1.1.3, kevinmcgowan.TypeScriptImport-1.7.0, kisstkondoros.typelens-1.2.3, mohsen1.prettify-json-0.0.3, mrmlnc.vscode-autoprefixer-2.0.0, mrmlnc.vscode-scss-0.3.1, ms-vscode.csharp-1.4.1, msjsdiag.debugger-for-chrome-2.0.0, nwallace.language-vscode-javascript-angular2-0.0.11, pmneo.tsimporter-1.2.7, rbbit.typescript-hero-0.9.0, robertohuertasm.vscode-icons-3.0.6, SirTori.indenticator-0.2.1, spywhere.guides-0.5.1, steoates.autoimport-1.2.2, web-dave.vsc-angular-cli-0.0.9

Steps to Reproduce:

1. Start vs code

![image](https://cloud.githubusercontent.com/assets/6654388/19725984/eb53dbec-9b88-11e6-927b-6649c52e1522.png)

**Comment by weinand** [comment]
Yes, I think this is intended.

**Comment by mbeckenbach** [comment]
Ok. I've noticed it because I had 4 instances open on several virtual desktops and one of my instances crashed in a way that I needed to kill the task. So there where many processes more :-)

**Comment by bpasero** [comment]
We spawn many processes and some come from Chrome itself:
* main process (once per app)
* renderer process (one per window)
* GPU process (once per app)
* extension host process (one per window)
* shared process (once per app)
* helper processes for compute intense tasks (e.g. git, search, file watchers) (one per window)
* any extension can spawn more processes (e.g. many language extensions spawn a language server)

As for your crash please report it as bug once you have steps to reproduce. It would also be interesting to find out the command line arguments of the processes that crash and hang.

**Comment by mbeckenbach** [comment]
@bpasero 
Thanks for your explaination. I was just wondering. 

ignore the creash. its related to one specific machine. same version, same project, same extensions work without any problem on several other machines. It's ok if it crashes once a day on a single computer, that should be reinstalled anyway. :-)
