### ISSUE TITLE
Could workbench.action.quickOpenTerm show more information to aid terminal selection?

### ISSUE THREAD

**Issue by MilesMcBain** [microsoft/vscode#145367]
I frequently use VSCode with multiple projects attached to the workspace. Usually each has at least one terminal associated with it.

The dialogue invoked by this command does not give the user a lot of context with which to choose terminals:

![image](https://user-images.githubusercontent.com/9996346/158938457-ee5b37de-13c3-448a-87a8-1b4028cf9222.png)

Contrast this with the drop select in corner of the terminal pane:

![image](https://user-images.githubusercontent.com/9996346/158938485-9be6e7ea-3a7e-4b2f-9069-2b8fc00483a9.png)

The advantage of `workbench.action.quickOpenTerm` is that it does not require using the mouse. But it becomes unusable with more than a couple of terminals (assuming the user hasn't edited the terminal names).

I know that you can name them, but would it be possible to show the root folder associated with the terminal as per the drop select in the terminal pane?

**Comment by wendy5667** [comment]
Hello! Can I take a look at this issue? Thanks!

**Comment by Tyriar** [comment]
@wendy5667 sure, here a code pointer for where the quick pick is defined to get your started:

https://github.com/microsoft/vscode/blob/00fa317c433d6c56f7853887ed42715bc7f29808/src/vs/workbench/contrib/terminal/browser/terminalQuickAccess.ts#L34
