### ISSUE TITLE
wrong column alignment with wide chars

### ISSUE THREAD

**Issue by yinrong** [microsoft/vscode#145395]
wrong column alignment with wide chars
![image](https://user-images.githubusercontent.com/4221569/159001227-22848560-4c91-423f-a0e0-78292e3a888e.png)
![image](https://user-images.githubusercontent.com/4221569/159001357-95dfdb84-2985-45c2-a099-beb84f2084a3.png)

The expected behavior is like what Sublime Text does:
![image](https://user-images.githubusercontent.com/4221569/159001260-25af66fe-dcfa-463c-a298-ba66070a9231.png)

**Comment by alexdima** [comment]
Let's track in #142738, as this shares the same root cause.
