### ISSUE TITLE
Add Option To 'Close Tabs to the Left'

### ISSUE THREAD

**Issue by dipankardas011** [microsoft/vscode#145398]
Add Option To 'Close Tabs to the Left' inside the VSCODE editor
Here is a screenshot

**Comment by dipankardas011** [comment]
![image](https://user-images.githubusercontent.com/65275144/159011872-6a828f15-0bc2-4c0f-ad42-449661b3278c.png)

**Comment by dipankardas011** [comment]
If you all don't mind can I take a few days to figure out whether I can add it or not 🙂

**Comment by gjsjohnmurray** [comment]
/duplicate of #142322 which you may want to upvote
