### ISSUE TITLE
Uknown extension vscode.ipynb

### ISSUE THREAD

**Issue by thistlillo** [microsoft/vscode#145357]
All of a sudden (yesterday I was using the Python notebooks on a remote machine, then disconnected and today I connected again) I cannot even open ipynb files on VS Code.

I did not install other extension, nor did I upgrade VSC.

```
Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```
The remote machine is a kubernetes pod running linux ubuntu 20.04.

I searched but could not find any answer.

What did I do?
- Remove extension Jupyter v2022.1.1301854968 (Microsoft)
- Reloaded
- Clicked on a .ipynb file
- VS Code asked to install the required extensions, I accepted
- VS Code reinstalled Jupyter v2022.1.1301854968 (Microsoft)
- Reloaded
- Re-opened a .ipynb file
- Got the same error message on the unknown extension

This issue happened with past releases, I found many references in 2020. However, I could not find any solutions.

I have read somewhere that this might be related to the python interpreter. I tried to change the interpreted, choosing also "Python select interpreter": I get an error also with this: python.setInterpreter not found.

What caused this mess?

**Comment by sandy081** [comment]
@thistlillo 

> Solved, the issue was caused by an extension for syncing Settings

Do you have Settings Sync extension installed?

**Comment by thistlillo** [comment]
Sorry for not having posted the solution I found. I uninstalled the extension Settings Sync everywhere and now I have no problems anywhere.
