### ISSUE TITLE
isWindowsPty doesn't get serialized in restored terminals

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#145345]
Need to serialize this:

https://github.com/microsoft/vscode/blob/23b444aaaa0dd696901b60ceb11b3a92ad044b2b/src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts#L43

Otherwise all the workarounds for conpty don't work in the reconnected terminal.

**Comment by rzhao271** [comment]
What are some verification steps for this issue?

**Comment by Tyriar** [comment]
I just verified this myself and @meganrogge reviewed the code, that should be sufficient for this one.
