### ISSUE TITLE
vsCode not recognizing --args from npm

### ISSUE THREAD

**Issue by ZnXCreators** [microsoft/vscode#145362]
creating an NFT (non-fungible tokens) collection with CodeSTACKr v.2.0.0 repo on vscode (https://github.com/codeSTACKr/create-10k-nft-collection), as per following tutorial (https://www.youtube.com/watch?v=quGdJweadFM). been able to generate our images and do the NFTs minting but command does not respond well and doesn’t read the arguments,  i.e. the -- (dash dash) “flags”, and ignores anything that comes after.

Example of commands:
a) WHEN MINTING : npm run mint --start=1 --end=100
b) TO CONFIRM TRANSACTIONS: npm run check_txns --dir=minted

vsCode is unable to read/understand the “flags”, i.e. the -- (dash dash). FYI, in mint.js the argument in question defines the range of NFTs to mint, and checkTxns.js points to the directory where files are.  

I understand that my arguments are handled by npm, instead of my script and to try npm run-script -- --args instead. (https://docs.npmjs.com/cli/v8/commands/npm-run-script#description). I tried entering  npm run-script mint --start=1 --end=100 
To no avail.

I do understand conceptually that the Terminal will execute the command as per the script of each node/package, but as far as I can tell, these scripts are already specified in the two js files in questions.

Error logs below.

When running npm run check_txns --dir=minted

Please specify the directory to check. Use "minted" or "revealed"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 10k-collection-video@2.0.0 check_txns: node utils/nftport/checkTxns %npm_config_dir%
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 10k-collection-video@2.0.0 check_txns script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

When minting npm run mint --start=1 --end=100
Minting works, but ignores the --flags and mints everything (i.e. does not respect the range I indicated).

Working on: 
VS Code Version: 1.65.2
OS Version: macOS Monterey 12.2 (running on a Mac M1
[chckTxns.docx](https://github.com/microsoft/vscode/files/8299746/chckTxns.docx)
[mint.docx](https://github.com/microsoft/vscode/files/8299747/mint.docx)
)

**Comment by gjsjohnmurray** [comment]
See also #145167

**Comment by myoon19** [comment]
were you able to fix this error???

**Comment by weinand** [comment]
No, since this is not a VS Code problem.
Please read #145167

**Comment by myoon19** [comment]
Then I can't reveal my nfts?

**Comment by myoon19** [comment]
I got the minting done but check_txns command is not working

**Comment by weinand** [comment]
As said before: your problems have nothing to do with VS Code. Please find help elsewhere.
