### ISSUE TITLE
Search is not excluding directories and files from .gitignore

### ISSUE THREAD

**Issue by jvlobo** [microsoft/vscode#145311]
Issue Type: <b>Bug</b>

When searching globally on my project, I'm getting results from files that are part of the `.gitignore` list.

I have the "Search: Use Ignore Files" disabled both on my User and Workspace settings.
![Screenshot 2022-03-17 at 12 26 52](https://user-images.githubusercontent.com/5671420/158808337-f1c9b43f-009a-4207-b0d3-6b03ceaa821b.png)
![Screenshot 2022-03-17 at 12 27 11](https://user-images.githubusercontent.com/5671420/158808345-94f37ea6-e2eb-4271-9c06-17c6726f9df6.png)

Also, when searching, the `Use Exclude Settings and Ignored Files` is actived.
![Screenshot 2022-03-17 at 12 27 44](https://user-images.githubusercontent.com/5671420/158808397-c8a9f5b5-93c7-4059-86e2-fd54a0b5f770.png)

I've tried restarting Visual Studio Code and also my computer, but it didn't make a difference.

VS Code version: Code 1.65.2 (Universal) (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 6, 9|
|Memory (System)|64.00GB (38.78GB free)|
|Process Argv|--crash-reporter-id f6c3a385-505d-4640-8a53-e887ef3049da|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.4
vscode-graphql|Gra|0.3.52
vetur|oct|0.35.0
fig|wit|0.0.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30450902
vscscmwlcmt:30438805
dockersurvey3:30453609
pynewfile477:30450038

```

</details>

**Comment by gjsjohnmurray** [comment]
I think your settings are telling VS Code to ignore (pay no attention to) the instructions in those files about which files to exclude from its searching. So VS Code behaves as if you have an empty (or no-existent) `.gitignore` file.

**Comment by jvlobo** [comment]
Wow.... thanks a lot @gjsjohnmurray 
So simple and I was not seeing it. I was understanding with `Search: Use Ignore Files` that if this option was enabled, it would actually use all the ignore files when searching, but I was wrong.
Thanks for pointing it out. This is solved then.
