### ISSUE TITLE
The icon in taskbar goes wrong

### ISSUE THREAD

**Issue by NaiveONe2** [microsoft/vscode#145385]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2-1
- OS Version: ArchLinux 5.16.14
- DE: Plasma 5.24.3

Sometimes when I open VSCode (official binary version) , vscode's icon in the taskbar becomes winterm's. The insider version has no such problem.

<img src=https://user-images.githubusercontent.com/61965533/158989001-b090421e-9651-4d60-951e-44a3fa1e823d.png width=80% />
<img src=https://user-images.githubusercontent.com/61965533/158986081-7a31a1af-b93f-4b31-8dcf-84d3c0c451f2.png width=80% />

**Comment by NaiveONe2** [comment]
> Please check if the issue is still present with latest stable `1.73`

Thanks. The issue is not present. Could you tell me the cause of the issue？

**Comment by deepak1556** [comment]
Thanks for confirming. The issue might be addressed with one of the runtime updates.
