### ISSUE TITLE
Test error peek only replaces out first \r?\n of reported failure text

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#145320]
The fix for #138336 at https://github.com/microsoft/vscode/commit/6cc3fe1806e9e58c1693974ddd0328fa776b19cd only replaces the first instance of `\r?\n` in the string, not all of them. I suspect the regex needs `/g` on the end.

<img width="1028" alt="Screenshot 2022-03-17 at 14 46 58" src="https://user-images.githubusercontent.com/1078012/158831687-cceb8bff-3aaa-4a8a-a09f-1b4c9a836ad0.png">

@connor4312 FYI :)

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/blob/ed18710e404a1c228a807e7822647bc06b559b2f/src/vs/workbench/contrib/testing/browser/testingDecorations.ts#L856

**Comment by DanTup** [comment]
heh, I found that and was going to change it, but GitHub fell over.

I can easily add the `g`, but it's not clear to me where/how to write a test against this class (which is actually the part that I get stuck on any time I want to contribute something). I can't find any similar tests in this area to use as a template.
