### ISSUE TITLE
Output from IW is not scrolled to

### ISSUE THREAD

**Issue by crsqq** [microsoft/vscode#145353]
There is an issue with the IW (might be related to microsoft/vscode-jupyter#9259): the most recent output from commands entered through the interactive prompt is not shown if the windows is filled by previous output.

E.g. in this screencast: the output of `i`, `i*2`, `i/0` is not shown, manual scrolling is thus necessary.

https://user-images.githubusercontent.com/4514040/157456743-2bd74f44-8bf7-4473-b387-0d3b23b4f7c9.mp4

Also happens with the changes from microsoft/vscode-jupyter#9299 applied and `jupyter.alwaysScrollOnNewCell` does not change the behavior

Steps to reproduce:
1) fill IW output with
```
# %%
for i in range(100):
    print(i)
```
2) type something in the interactive prompt

#### Environment data
-   VS Code version: Version: 1.66.0-insider, Commit: 92f4bd7894c3b790d37b1eec3c7fb5e5f8618f70
-   Jupyter Extension version (available under the Extensions sidebar): v2022.3.1000691006
-   Python Extension version (available under the Extensions sidebar): v2022.3.10681004
-   OS:  Linux x64 5.4.0-102-generic
-   Python and/or Anaconda version: 3.8.10
-   Type of virtual environment used: venv
-   Jupyter server running: Local

**Comment by Demcorazy** [comment]
I think here is a tradeoff way that keeping the last cell in the middle of the window instead of the bottom, can help avoid many annoying scrolling by hand.

**Comment by karahanyilmazer** [comment]
I also have the same problem for a while. I had a look at other related issues and I understand that the fix may require core changes. Still, I believe that a lot of people would appreciate a fix to this issue. Thanks!

**Comment by rafaelha** [comment]
![interactive-terminal-gif](https://user-images.githubusercontent.com/34611791/165414645-2351072a-15e3-479c-99ed-442efdf37aa6.gif)
Note that for me the terminal scrolls correctly when I run a cell from within a python file. Just when code is run from the interactive terminal, it does not work...

**Comment by ba-tno** [comment]
A temporary, partial workaround can be achieved with the [multi-command extension](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command).

Steps:
1. Install the multi-command extension
2. Add the following to your `settings.json` file:
    ```
    "multiCommand.commands": [
            {
                "command": "multiCommand.runPythonInteractive",
                "interval": 50,
                "sequence": [
                    "interactive.execute",
                    "interactive.scrollToBottom",
                ]
            }
        ]
    ```
3. Add a keybinding for this command in `keybindings.json` (I chose the <kbd>Enter</kbd> key):
    ```
    {
        "key": "enter",
        "command": "extension.multiCommand.execute",
        "args": {
            "command": "multiCommand.runPythonInteractive"
        },
        "when": "!notebookKernel && resourceScheme == 'vscode-interactive' || resourceScheme == 'vscode-interactive' && notebookKernel =~ /^ms-toolsai.jupyter\\//"
    }
    ```

Now every time you execute a command in the interactive window using <kbd>Enter</kbd> the multi-command extension executes the command `interactive.execute`, waits 50 milliseconds and then executes the command `interactive.scrollToBottom`, scrolling the output in view.

The `interactive.scrollToBottom` only seems to work for small output, i.e.  `l = [1, 2, 3, 4]; len(l)`.  
Larger output (e.g. the for loop in [the issue description](https://github.com/microsoft/vscode/issues/145353#issue-1172947886)) does not scroll fully into view. It only seems to scroll down as longs as the input line remains in view.

Interestingly, long running commands, (more than the configurable 50 ms interval), e.g. `import time; l = list(range(0, 10)); time.sleep(1); len(l)`, also scroll into view!
