### ISSUE TITLE
Couldn't find a compatible version of Scala with this version of Code.

### ISSUE THREAD

**Issue by daltonjorge** [Microsoft/vscode#14533]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 16.0.0
- Extensions: vscodevim.vim-0.4.0

Steps to Reproduce:

1. Launch VS Code Quick Open (⌘+P)
2. Paste the following command: `ext install Scala`
3. Press enter

**Comment by weinand** [comment]
Please report that against the Scala extension you are using.
