### ISSUE TITLE
Account Sync Notifications Icon Bubble

### ISSUE THREAD

**Issue by Chiramisu** [microsoft/vscode#145343]
First of all, thank you for implementing this feature natively in VS Code.  Currently the Accounts icon, at the bottom of the left bar, displays a number inside a blue bubble over the icon that indicates the number of available services. In my mind, this is silly and should not be. The only way to make that go away would be to sync your settings over every available service, but this would make no sense. Rather, please only show a notification bubble on this icon if there is some issue with the current account being used to sync the settings. This, to me, seems a more sensible notification rather than showing one for each available unused service.

**Comment by TylerLeonhardt** [comment]
Can you share what things are in your Account list that are causing the account bubbles? They are marked with a `(1)` next to them.

From that list, which ones do you expect and which ones do you want to go away?

**Comment by Chiramisu** [comment]
As requested:

![vscode-account-bubbles](https://user-images.githubusercontent.com/944951/159755035-7055bf0a-4d4b-4496-b80b-acdd588c0eb0.png)

I want all of them to go away, or at the very least permanently dismissible or hidable. This is a notification bubble, which should only be used for alerting the user to an issue or new information, and should ALWAYS be dismissible. A notification should NOT be used to merely bring attention to a static thing. They should be dynamic, not static. I don't mean to be rude, but isn't this an elementary design concept?
