### ISSUE TITLE
Search file feature is not working properly

### ISSUE THREAD

**Issue by mohaknigam** [microsoft/vscode#145305]
Issue Type: <b>Bug</b>

do ctrl+shift+f, and then search for anything, result will be 'nothing found', but the file and the searched keyword exists

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (5.43GB free)|
|Process Argv|--crash-reporter-id 4964dbd8-8f0c-4d57-90ff-6b451d2d97dc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.4
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.3.0
vscode-jest-runner|fir|0.4.48
dotnet-test-explorer|for|0.7.7
path-autocomplete|ion|1.19.1
csharpextensions|jch|1.3.1
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.1.30
csharpextensions|kre|1.6.0
csharp|ms-|1.24.1
vscode-jest|Ort|4.2.1
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.14.1
vscode-thunder-client|ran|1.12.5
LiveServer|rit|5.7.5
msbuild-project-tools|tin|0.4.3
lorem-ipsum|Tyr|1.3.1
vscode-todo-highlight|way|1.0.5
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30450902
vscscmwlcmt:30438805
dockersurvey3cf:30453610
pynewfile477:30450038

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo
Please check if you have this file excluded by files to exclude pattern or they are in ignored files (toggle in that field)

https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options

**Comment by mohaknigam** [comment]
Thanks

**Comment by roblourens** [comment]
Please check what @IllusionMH says and give more details if that doesn't help
