### ISSUE TITLE
Terminal auto exit

### ISSUE THREAD

**Issue by AkashJaishwal** [microsoft/vscode#145479]
Terminal is automatically getting terminated in VS cod with the error and the main issue is related to the every terminal (cmd, powershell)
![image](https://user-images.githubusercontent.com/97788908/159150564-27992ea7-23a9-45ac-b18b-2260d0b6cc07.png)

**Comment by meganrogge** [comment]
These might be helpful to you:
https://bytes.com/topic/c/answers/217841-return-code-4294967295-uint_max#:~:text=A%20process%20cannot%20fail%20with%20an%20exit%20code,question%20is%3A%20what%20is%20returning%20-1%20%28whatever%20returns
https://github.com/microsoft/vscode/issues/93016#issuecomment-601490985
