### ISSUE TITLE
"Open with Code" from Windows File Explorer should put Terminal in the folder of the file opened

### ISSUE THREAD

**Issue by jdenicola-pa** [microsoft/vscode#145421]
In Windows, when I right-click on a file in Windows File Explorer, such as Powershell script, and use "Open with Code", it loads the file into VS Code, and starts a Terminal session in the lower pane.

However, the current directory of the Terminal is always my home directory (c:\users\myname). If the script I am editing needs any files that are in the same folder as the script, it won't find them unless I do a CD in the Terminal pane first.

I would like to see an option where it will start the Terminal session in the same folder as the file that was opened via "Open with Code".

**Comment by Tyriar** [comment]
Do you have the powershell extension and could you show a screenshot of the terminal including its tab/title?

**Comment by jdenicola-pa** [comment]
Yes, see attached
![s1](https://user-images.githubusercontent.com/61470867/159098894-0915dc42-31e6-426e-9979-2ac980c0aa5c.png)
![s2](https://user-images.githubusercontent.com/61470867/159098896-7e054332-6e07-4db4-b41e-ba4790fe5c42.png)
![s3](https://user-images.githubusercontent.com/61470867/159098899-705d95f2-cb5f-4dc6-b6a9-c58a9571cf89.png)

**Comment by jdenicola-pa** [comment]
Does this still need more info?

**Comment by Tyriar** [comment]
This is either another case of https://github.com/microsoft/vscode/issues/83496 or an issue with the pwsh extension not handling unicode.

**Comment by jdenicola-pa** [comment]
Not a unicode issue. No special characters in my home directory name.

**Comment by Tyriar** [comment]
Oh the first character is probably a j, I thought it was a non-ascii character. In that case it sounds like a powershell extension problem as they launch that terminal.
