### ISSUE TITLE
Linux tar downloaded vscode does not directly execute on double click.

### ISSUE THREAD

**Issue by soumyajitsamanta** [microsoft/vscode#145490]
Hi Team, when we download vscode as tar in linux like for elementary os, the code executable cannot be started by double click even if chmod +x is done already. The file type is shared executable. Is there going to be correction of the file type of codes executable to elf binary or likes of it in linux tar build specifically?

**Comment by mathroc** [comment]
@soumyajitsamanta which tar.gz exactly have you donwloaded? and which file from it are you trying to execute?

**Comment by soumyajitsamanta** [comment]
I went to this site of more download options here https://code.visualstudio.com/#alt-downloads and then downloaded tar.gz option in linux section.
Then i unzip the tar and try running the code executable and it asks what to open with.
I use file command and see it is shared library.
Os Elementary Os 6

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/131491

Its an issue with your OS file manager, should launch fine when run from the terminal
