### ISSUE TITLE
Cannot invoke an expression whose type lacks a call signature (ES6)

### ISSUE THREAD

**Issue by hmoritz** [Microsoft/vscode#1454]
The following code works when transpiled with babel but vscode has a problem with it:
```javascript
// module1.js
const str = 'abc';
export const fn = () => ({
  key: 'value'
});

export default [str, fn];
```
```javascript
// module2.js
import {fn, default as module1} from './module1';

let str, obj;

// this works ...
str = module1[0];
obj = fn();

// ... but this shows the following error:
// Cannot invoke an expression whose type lacks a call signature.
obj = module1[1]();
````
Am I doing something wrong or is this a bug? I'm using version 0.10.3 on Windows 10.

**Comment by hmoritz** [comment]
The 'Format Code' command also turns `export default [str, fn];` into `export default[str, fn];` which seems to work.

**Comment by jrieken** [comment]
Likely an issue with the TS version we use for JS.

**Comment by jrieken** [comment]
Closed with the adoption of Salsa (https://code.visualstudio.com/Updates#_languages-javascript).
