### ISSUE TITLE
Markdown Path IntelliSense breaks when a directory with spaces is involved

### ISSUE THREAD

**Issue by laggingreflex** [microsoft/vscode#145447]
Steps to Reproduce:

1. Use [Markdown path IntelliSense](https://code.visualstudio.com/updates/v1_64#_markdown-path-intellisense)
1. Have a directory with spaces, and a file in it: `My Projects/Something.md`
1. Invoke path IntelliSense by typing `../My Projects/`

**Expected:**

After typing `../My Projects/` it should suggest `Something.md`

**Actual:**

It doesn't suggest `Something.md` (or anything) under `../My Projects/`

**Additional info** 

#142838 might be related which was fixed so now it does insert `%20` instead of spaces but breaks after that in that it doesn't suggest child dirs/files. 

---
Version: 1.65.2

**Comment by mjbvz** [comment]
What if you trigger suggestions at the start of the path, i.e. after `../`?

**Comment by laggingreflex** [comment]
Doesn't seem to help.. Here's a screen gif trying different ways: 

![Code_2022-03-22_17-10-10](https://user-images.githubusercontent.com/2523987/159538479-d9d3a011-6852-4dee-b409-972b8bbd370c.gif)

**Comment by mjbvz** [comment]
Thanks for the example. Should be fixed in the next insiders build
