### ISSUE TITLE
UI Render background-colors inconsistantly

### ISSUE THREAD

**Issue by nogorilla** [Microsoft/vscode#14540]
- VSCode Version: 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e)
- OS Version: macOS 10.12

Steps to Reproduce:

1. Open VS Code

Upgraded to 10.12 last night and today am noticing inconsistent render of VS Code background colors. See screenshots below.

![screen shot 2016-10-26 at 9 50 42 am](https://cloud.githubusercontent.com/assets/1786677/19729525/446c197a-9b65-11e6-8d3c-263eed3f4d6a.png)
![screen shot 2016-10-26 at 9 50 50 am](https://cloud.githubusercontent.com/assets/1786677/19729529/484ce15a-9b65-11e6-8c28-18865fd3e1e9.png)
![screen shot 2016-10-26 at 9 55 45 am](https://cloud.githubusercontent.com/assets/1786677/19729536/4cd39a70-9b65-11e6-90e5-ceaef9f5db2b.png)

I removed VS Code and did a clean install without any extensions installed and this was the result:
![screen shot 2016-10-26 at 10 13 19 am](https://cloud.githubusercontent.com/assets/1786677/19729559/5f3629d0-9b65-11e6-9fc9-fcf53fb5efb7.png)
![screen shot 2016-10-26 at 10 13 48 am](https://cloud.githubusercontent.com/assets/1786677/19729563/6249159c-9b65-11e6-9333-dde0e1f10933.png)

**Comment by bpasero** [comment]
@nogorilla see http://code.visualstudio.com/updates#_macos-sierra-support

**Comment by bpasero** [comment]
And https://github.com/Microsoft/vscode/issues/12473

**Comment by nogorilla** [comment]
@bpasero utilizing `--force-gpu-rasterization` still results in rendering issues

![screen shot 2016-10-26 at 10 24 15 am](https://cloud.githubusercontent.com/assets/1786677/19729898/83c686ae-9b66-11e6-93a9-ce79af2ebe4a.png)

**Comment by bpasero** [comment]
Ok, sucks :-/

**Comment by jensvdh** [comment]
Can confirm. I'm still seeing rendering issues. Even with forced GPU rasterisation.
