### ISSUE TITLE
Editor line number bar render bug

### ISSUE THREAD

**Issue by li1234yun** [microsoft/vscode#145488]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.2
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. line number bar breaks
<img width="125" alt="image" src="https://user-images.githubusercontent.com/26505658/159158539-39f54738-03b4-4c55-98e7-2c974f2711b1.png">

2. line break will dispear when cursor hover the break line

<img width="321" alt="image" src="https://user-images.githubusercontent.com/26505658/159158578-24667d19-6041-4a46-992c-a95da801f667.png">

3. line number bar's number shake when hover change

**Comment by IllusionMH** [comment]
Do you have any value specified for `window.zoom`?

**Comment by li1234yun** [comment]
@IllusionMH You are right! 👍 

When I set the `window.zoomLevel`, the break will appear. However, it still maybe a bug?

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/85581#issuecomment-559090986
