### ISSUE TITLE
Debuging problem

### ISSUE THREAD

**Issue by angelaun** [microsoft/vscode#145463]
Issue Type: <b>Bug</b>

When i try to run and debug, it says run Google Chrome against Localhost and it opens, but it shows that an error was produced
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>

Extension|Author (truncated)|Version
---|---|---
htmlplay|bia|0.0.10
vscode-edge-devtools|ms-|1.4.5
vsliveshare|ms-|1.0.5449
cors-browser|Wsc|1.0.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmc:30438804
vscgsvidc:30447482
cppdebug:30451566
pynewfile477:30450038

```

</details>

**Comment by weinand** [comment]
Please provide reproducible steps.
