### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by EnriqueGambra** [microsoft/vscode#145411]
- Issue Type: `Bug`
- Extension Name: `typescript-language-features`
- Extension Version: `1.0.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.65.2`

Typescript-Language-Features extension is completely unresponsive, freezing up VS Code entirely.

Data: ```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 70,
		"activateCallTime": 5431,
		"activateResolvedTime": 11,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "vscode.typescript-language-features",
				"_lower": "vscode.typescript-language-features"
			},
			"activationEvent": "onLanguage:typescript"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
