### ISSUE TITLE
List: Support scroll by page

### ISSUE THREAD

**Issue by Z-E-D** [microsoft/vscode#145458]
I searched for the request in subject, but didn't find it. I saw numerous requests to make scrolling page by page in editors, and thanfully we got that option with the "editor.scrollbar.scrollByPage". However, the scrolling in almost every other situation is absolute, i.e. you get scroll to the place where you clicked. AFAIK, the only other place in VSCode where we have scrolling page by page is the extension web pages displayed in the editor, which works like that even if "editor.scrollbar.scrollByPage": false.

I would like if the mentioned scrollByPage setting is global for all places that have scroll bars, like Explorer/Search/Extensions panels. Or, you could add another setting which will apply to these other places independently of the editor setting.

**Comment by Balastrong** [comment]
Hello! I'd like to give it a try on this one as I'm a potential user of this new feature :)

Could I get some pointers?

**Comment by joaomoreno** [comment]
Sure. The solution here is  to create a `workbench.list.scrollByPage` setting. Follow the trail of `editor.scrollbar.scrollByPage` and `workbench.list.horizontalScrolling` for hints on how to get that in.

**Comment by gjsjohnmurray** [comment]
If someone is doing the work to pass the value of a new `workbench.list.scrollByPage` setting downwards by every user of scrollableElement then maybe it's worth adding a setting to make scrollbars always visible, as discussed in #66000.

**Comment by yecril71pl** [comment]
Hopefully will fix #139922.
