### ISSUE TITLE
TypeScript settings header has period in the title

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#14547]
- VSCode Version:1.7.0 insiders
- OS Version:Windows 7

Steps to Reproduce:

1. File > Preferences > User Settings
2. Look at the collapsed Default Settings heading.

Only the TypeScript heading has a period at the end "TypeScript."
Not sure why (it is a heading not a sentence) and granted this issue is nit but we should be consistent.

**Comment by sandy081** [comment]
@dbaeumer FYI Fix was to remove `.` from the label. So pushed it.
