### ISSUE TITLE
Extension recommendations from Language Mode doesn't find Markdown extensions

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#14549]
- VSCode Version:1.7.0 insiders
- OS Version:Windows 7

Steps to Reproduce:
1. Open a Markdown file.
2. Language Mode > Search Marketplace Extensions for '.md'

Only an HTML grammar extension is show (viatsko.html-mason).
Expectation is that you would see a list of Markdown extensions.
Not sure if this is due to extensions needing to be updated to list their supported file extensions (.md), but I don't think this feature is very useful at present.

**Comment by gregvanl** [comment]
@weinand This is a general extension Marketplace issue, not specific to Markdown extensions. 
If you open a JavaScript file and look at the .js tagged extensions, they are a rag tag group (mostly Babel, nothing with JavaScript in the title) compared to when the user searches for "javascript".
The Markdown scenario is just a simple repro.
The issue should probably go to @joaomoreno or @waderyan.

**Comment by joaomoreno** [comment]
@waderyan @seanmcbreen

**Comment by mjbvz** [comment]
This seems to be working fairly well now:

![screen shot 2017-01-31 at 2 36 36 pm](https://cloud.githubusercontent.com/assets/12821956/22487545/b5c635d4-e7c2-11e6-8224-fd191d0ceaaf.png)


Other languages also return reasonable looking results.
