### ISSUE TITLE
Inconsistent behavior of ${env:PATH}

### ISSUE THREAD

**Issue by therealchjones** [microsoft/vscode#145434]
Issue Type: <b>Bug</b>

With `tasks.json`:
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "task path",
			"type": "shell",
			"command": "echo task path: $PATH",
		},
		{
			"label": "vscode path",
			"type": "shell",
			"command": "echo vscode path: ${env:PATH}",
		}
	]
}
```

and no other customized settings, running the two tasks produces identical results. On my machine:
```
task path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin
vscode path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin
```

However, adding a workspace `settings.json` *and launching via click rather than from a shell*:
```
{
	"terminal.integrated.env.osx": {
		"PATH": "${env:PATH}"
	}
}
```

results in a change in running the two tasks:
```
task path: /usr/bin:/bin:/usr/sbin:/sbin
vscode path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin
```

while I would expect the results to be identical and unchanged from the previous.

(Indeed, despite the output from the `vscode path` task, Developer Tools displays `process.env.PATH` to be `/usr/bin:/bin:/usr/sbin:/sbin`.)

As noted from the [tasks.json schema](https://code.visualstudio.com/docs/editor/tasks-appendix), I would expect the default environment for the tasks to be the same as the parent process', i.e., VS Code's. That would additionally seem to be the expected behavior for the integrated terminal environment setting.

I am not certain whether this is an error in VS Code or in my expectations. (Of note, this is a minimal reproducible example. I realize this specific workspace setting should be redundant, but this occurs similarly with any `PATH` setting that includes `${env:PATH}`.)

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (42.86GB free)|
|Process Argv|--crash-reporter-id b6b54fc7-28be-4f61-997b-8049ec3900be|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmc:30438804
vscgsvidc:30447482
dockersurvey3:30453609
pynewfile477:30450038

```

</details>

**Comment by therealchjones** [comment]
I'll note that many issues seem to similarly relate the "default" `/usr/bin:/bin:/usr/sbin:/sbin` path within process.env as the "error" here. However, whether or not that bit is intended, I cannot intuit why `${env:PATH}` is apparently interpreted differently between tasks and settings.

**Comment by therealchjones** [comment]
See also: https://github.com/microsoft/vscode/issues/118460

**Comment by therealchjones** [comment]
A simpler example may be more illustrative of the discrepancy. Again, this is on macOS when code is not launched from the command line:
`settings.json`:
```json
{
	"terminal.integrated.env.osx": {
		"PATH": "${env:PATH}"
	}
}
```
`tasks.json`:
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "Use env from settings",
			"type": "process",
			"command": "sh",
			"args": [
				"-c",
				"echo Using env from settings: PATH=$PATH"
			],
		},
		{
			"label": "Use env from task",
			"type": "process",
			"command": "sh",
			"args": [
				"-c",
				"echo Using env from task: PATH=$PATH"
			],
			"options": {
				"env": {
					"PATH": "${env:PATH}"
				}
			}
		}
	]
}
```
Output from running tasks:
```
> Executing task: sh -c echo Using env from settings: PATH=$PATH <

Using env from settings: PATH=/usr/bin:/bin:/usr/sbin:/sbin

Terminal will be reused by tasks, press any key to close it.

> Executing task: sh -c echo Using env from task: PATH=$PATH <

Using env from task: PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin

Terminal will be reused by tasks, press any key to close it.
```

**Comment by alexr00** [comment]
I don't have a mac to test with, but I do see a difference in the value of PATH in your two tasks in the original issue on Windows too. 

@meganrogge, how does terminal decide which environment variables to add when `useShellEnvironment === true` in the shell launch config? In tasks, we get the default terminal profile, the use the `env` from that (which is an empty object in this case) in the `IShellLaunchConfig` that we pass into `createTerminal`.

**Comment by meganrogge** [comment]
When useShellEnv is true, we get the env from ![Here](https://user-images.githubusercontent.com/29464607/162368416-d75c7e0c-1acd-435a-9ef6-67a25fa96beb.png)

**Comment by meganrogge** [comment]
According to the description, the env will differ based on how the process was started and that's expected.

**Comment by meganrogge** [comment]
there was an issue with resolving env:PATH with version 1.65. does this persist for you in insider's? When I try it, they're the same
<img width="1139" alt="Screen Shot 2022-04-08 at 12 23 27 AM" src="https://user-images.githubusercontent.com/29464607/162385222-9fa6440f-44cf-447e-99bc-6284d98d5321.png">
?

**Comment by therealchjones** [comment]
I'm afraid the problem persists for me on Insiders (and just to be sure, on clean install on VM). Recall to reproduce we must launch from GUI and have settings.json set to use ${env:PATH} as well, just in case the above testing didn't.

![Screen Shot 2022-04-08 at 20 12 23](https://user-images.githubusercontent.com/4241732/162548643-b57c681f-e9c7-4d12-8e24-aef25e4c6afe.png)

**Comment by therealchjones** [comment]
(For the sake of testing, I get the same behavior by setting a custom path in my external shell session and using the `--force-user-env` flag:
```
PATH=/bin:/usr/bin:/usr/local/bin code --force-user-env
```
)

I'm having trouble tracking down the variable resolution differences between the configuration(settings.json) and the tasks. However, here's a start: though it appears variables in both are resolved using the same resolver in https://github.com/microsoft/vscode/blob/29eb316bb9f154b7870eb5204ec7f2e7cf649bec/src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts#L360, the task command options at this point in the task launching process have already been resolved in https://github.com/microsoft/vscode/blob/eda166b7fa6377d2bd2fd2c33e5a844ea1b7bddd/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L719

It would seem this is a reasonable place that the `${env:PATH}` variable is being replaced with the `shellEnv` path instead of the `process.env` path, since if we replace the task option path setting with `${config:terminal.integrated.env.osx.PATH}` we still get the same result! 

<img width="1226" alt="Screen Shot 2022-04-13 at 16 33 57" src="https://user-images.githubusercontent.com/4241732/163265725-89a9a0b6-b0ad-4886-b044-b7f1e0feab23.png">

If someone who is able to follow the various variable/configuration resolver methods better than I can could compare the two, perhaps this could yield an answer.

Philosophically, of course, I suppose the question remains: *should* `${env:PATH}` resolve to the same thing in tasks.json as in settings.json? And should it always be `process.env.PATH` or `shellEnv.PATH`?

Thanks as always for all the hard work on this product!

**Comment by alexr00** [comment]
After taking another look, the issue appears to be that for tasks, we use `process.env` for the VS Code extension host process and for the terminal setting we use the `process.env` of the remote terminal channel. Since they're different process, you end up with different environment values. 

@meganrogge does this sound correct from the terminal side? I think it's correct that tasks uses the extension host env and terminal uses the terminal channel env, so if you agree then this is intentional.

**Comment by meganrogge** [comment]
Yes @alexr00 I believe this is as designed

**Comment by alexr00** [comment]
@therealchjones thank you for all your investigation! Given that we're looking at the env for two different processes, this is as-designed.
