### ISSUE TITLE
Unable to resolve shell variables after Mac reboot

### ISSUE THREAD

**Issue by erictraut** [microsoft/vscode#145416]
Every time I reboot my Mac and I have VS Code running, I receive the following dialog box when VS Code restarts.

<img width="454" alt="Screen Shot 2022-03-18 at 12 05 28 PM" src="https://user-images.githubusercontent.com/7040122/159059085-c825335d-8758-4728-9b3d-ad5ba33397bd.png">

I presume it's because the shell variable resolution times out because the computer is busy launching other apps. I wonder if the timeout could be increased somewhat to avoid this condition.

To repro:
1. On a Mac, open VS Code and a bunch of other apps
2. Restart the Mac and wait for it to reboot

When this occurs (which is every time I reboot), I need to quit and relaunch VS Code so it properly resolves my shell variables.

**Comment by ZantsuRocks** [comment]
The best solution to this issue is to let the user choose the timeout.
