### ISSUE TITLE
Have Explorer explicitly sort using a .order file

### ISSUE THREAD

**Issue by marckassay** [microsoft/vscode#145414]
Azure DevOps Wiki has a feature ([.order file](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-file-structure?view=azure-devops#order-file)) to explicitly set the sequence of TOC (table of contents) of pages listed. Likewise, I propose to have Explorer be able to do the same.

For instance, when a workspace is configured for [Component Driven](https://www.componentdriven.org/) development, and the sorting method is set to any of the existing options for Explorer, the libraries or folders listed conceptually may cause some hindrance for the user when deciding which one to drill into.

The image below illustrates this in the 'libs' folder of this workspace:

![image](https://user-images.githubusercontent.com/459665/159055950-98da3e68-5bef-4b59-8f0a-4e8a83334cac.png)

The current sorting method is alphabetical, but conceptually it's slightly confusing. Ideally, it should have 'macro' between 'micro' and 'page'. The hierarchy image in the Component Driven link above should give context for this feature.

At the moment, 2 setting options that perhaps can be added to `settings.json` are the following:

```json
{
  "explorer.enableOrderFiles": true,
  "explorer.showOrderFiles": true,
}
```

Hopefully, I explained this well so that it can be considered. Thanks!

**Comment by JacksonKearl** [comment]
Don't want to have sorting dependent on file reading, potential for lots of hangups, especially in remote contexts.
