### ISSUE TITLE
Support powerlevel10k prompt in shell integration

### ISSUE THREAD

**Issue by LuanVSO** [microsoft/vscode#145410]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: Microsoft Windows [Version 10.0.19044.1586] + WSL Ubuntu 21.10
- using remote WSL extension

Steps to Reproduce:

i have a custom prompt that is supposed to look like this
![image](https://user-images.githubusercontent.com/43626415/159044383-4e1d7da7-69ab-425f-859a-7fb7dc4d15a3.png)
but on VSCode terminal with shell integration enabled i get this:
![image](https://user-images.githubusercontent.com/43626415/159044618-a440597b-9590-436a-9829-e416809e5b4a.png)
the config files are running (verified it by putting "-v" in zsh profile) but the customization doesn't show up on the prompt

attached is a tar ball with my shell config files (extract to $home)
[shellconfigs.tar.gz](https://github.com/microsoft/vscode/files/8307266/shellconfigs.tar.gz)

**Comment by Tyriar** [comment]
@LuanVSO could you test on [Insiders](https://code.visualstudio.com/insiders)? Bunch of improvements have happened since.

**Comment by LuanVSO** [comment]
![image](https://user-images.githubusercontent.com/43626415/159092784-214b16df-98d5-450a-b5f1-494f9042589a.png)

**Comment by Tyriar** [comment]
@LuanVSO thanks, guessing powerlevel10k just doesn't work at all. It was on the list for https://github.com/microsoft/vscode/issues/142004 but had problems installing. Let's track the support here.

**Comment by Tyriar** [comment]
A bunch of problems came up in https://github.com/microsoft/vscode/issues/142004, see the linked issues there.

**Comment by Tyriar** [comment]
As per the discussion in https://github.com/microsoft/vscode/issues/142004 and https://github.com/microsoft/vscode/pull/145610, the plan for powerlevel10k is for it to implement VS Code's shell integration protocol eventually, but for now in the next version it will be explicitly disabled by the shell until it's more mature.
