### ISSUE TITLE
Disable Extensions Option Unavailable

### ISSUE THREAD

**Issue by Dillie-O** [Microsoft/vscode#14545]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 16.1.0
- Extensions: Kasik96.format-indent-1.3.0, Telerik.nativescript-0.3.1, felixfbecker.php-debug-1.9.7, felixfbecker.php-intellisense-0.0.9

Steps to Reproduce:

1. Open a terminal instance
2. Enter `code --disable-extensions` and hit enter

Expected Result:
Application launches with all extensions disabled

Actual Result:
Error is displayed that the argument is not recognized

Note: I use iTerm2 and ZSH as my default environment. Could it be something with the pathing that was setup?

![1__dillieo_bombadil____projects_prayer-odyssey-mobile__zsh__and_login_component_ts_-_prayer-odyssey-mobile](https://cloud.githubusercontent.com/assets/991466/19732466/b0badb8a-9b55-11e6-9274-9cad7089983a.png)

**Comment by joaomoreno** [comment]
Please remove the old `code` alias from your `.zshrc` and install the `code` shortcut by running the `Shell Command: Install 'code' command in PATH` from the command palette.

**Comment by Dillie-O** [comment]
I've removed the path in my .zshrc file, but I'm not sure I follow your second step. Do I simply execute the command `Install 'code'` and if so, from what folder? I tried in my /Applications/Visual Studio Code.app path and I get an error about usage of the 'Install' command

**Comment by joaomoreno** [comment]
In Code, use <kbd>Cmd Shift P</kbd> to open the Command Palette. Search for `Shell Command` and you'll find the command I mentioned.

**Comment by Dillie-O** [comment]
That seems to have done the trick! Thanks!
