### ISSUE TITLE
macOS Monterey Update: Mouse hover on functions, files not working

### ISSUE THREAD

**Issue by Narayan-Gopalappa** [microsoft/vscode#145426]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.65.2 (Universal)
- OS Version: macOS Monterey

Steps to Reproduce:

Create a node js file: I work in NPM projects and I have node JS files. Before I updated my mac to Monterey, hover on functions, files were all working fine. Post the update it stopped working.

In settings.json, I have Editor > Hover: Enabled, I see all other hover related settings are enabled too. Not sure how to get rid of this issue.

Thanks for your help.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Narayan-Gopalappa** [comment]
I do not see this issue on the latest insider's version. Thanks for your help.
**Version: 1.66.0-insider (Universal)**

I still see issue in **Version: 1.65.2 (Universal)** even with all extension disabled.

**Comment by Narayan-Gopalappa** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Closing as this is already fix in insiders then (either that or an extension/setting in your stable build was causing this)
