### ISSUE TITLE
Refresh and collapse buttons cause unexpected file tree collapse in `workbench.view.explorer` and iOS

### ISSUE THREAD

**Issue by bcho** [microsoft/vscode#145485]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: iOS 15.4

```
Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:30.517Z
Browser: Mozilla/5.0 (iPad; CPU OS 15_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/99.0.4844.59 Mobile/15E148 Safari/604.1
```

Steps to Reproduce:

1. open https://github.dev/kubernetes/kubernetes or https://vscode.dev/kubernetes/kubernetes in iPad (or any iOS devices, like simulator)
2. click the refresh or collapse buttons in the explorer view
3. the workbench tree collapses completely (while in desktop, the tree remains open)

https://user-images.githubusercontent.com/1975118/159155287-7634cb09-4142-4b1f-a5fd-cc2ababe0396.MP4

**Comment by bcho** [comment]
This looks like when tapping to these two buttons, the touch event got propagated to the title element, which collapsed the tree.

**Comment by JacksonKearl** [comment]
Haven't been able to reproduce this on my iPad, can you confirm you're still seeing this?
