### ISSUE TITLE
unable to install react native expo getting 31 vulnerabilities (20 moderate, 11 high)

### ISSUE THREAD

**Issue by ghaffmam** [microsoft/vscode#145483]
I am trying to install react native expo on visual studio code, when I run the following commands

PS C:\Users\mona_> npm install -g expo-cli
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
https://v8.dev/blog/math-random for details.
https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See 
https://v8.dev/blog/math-random for details.
npm WARN deprecated subscriptions-transport-ws@0.9.8: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migusing `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated graphql-tools@3.0.0: This package has been deprecated and now it only exports makeExecutableSchema.\nAnd it will no longer receive updates.\nWe recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.\nCheck out https://www.graphql-tools.com to learn what package you should use instead

changed 1549 packages, and audited 1550 packages in 23s

31 vulnerabilities (20 moderate, 11 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
PS C:\Users\mona_> npm audit
found 0 vulnerabilities
PS C:\Users\mona_> npm audit fix

up to date, audited 333 packages in 1s

found 0 vulnerabilities
PS C:\Users\mona_> npm audit fix --force
npm WARN using --force Recommended protections disabled.

up to date, audited 333 packages in 1s

found 0 vulnerabilities

no vulnerabilities were found, and I repeat the same things in a circle. I tried to find a solution but I don't find anything related to my issue. Please help me with this thank you

**Comment by gjsjohnmurray** [comment]
What makes this a VS Code specific issue?
