### ISSUE TITLE
Menu doesn't render text if it's a codicon

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#145480]
Create a status bar item with the text and the name of a codicon:

```js
const statusBarItem = window.createStatusBarItem();
statusBarItem.name = '$(save)';
statusBarItem.text = '$(save)';
statusBarItem.show();
```

- Expected: rendered menu with the text `$(save)`
- Actual: rendered empty menu item

<img width="400" src="https://user-images.githubusercontent.com/9638156/159152059-ab887552-32fd-4cae-bc25-0bf21d304b32.png" alt="codicon-menu-item">

Version: 1.65.2 (user setup)
OS: Windows_NT x64 10.0.19044

**Comment by gjsjohnmurray** [comment]
If this problem is specific to the context menu for controlling visibility of StatusBarItem entries, maybe edit the title to say this.

**Comment by sbatten** [comment]
This is not supported. macOS is using native menus for this purpose and don't use codicons
