### ISSUE TITLE
Pick basecase is timing out on windows CI

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#145401]
https://github.com/microsoft/vscode/runs/5601364482?check_suite_focus=true
https://github.com/microsoft/vscode/runs/5601139103?check_suite_focus=true

Two recent timeouts of 

https://github.com/microsoft/vscode/blob/4ac8fc0c265027d6b563ee15d83364cd6cefa1a5/src/vs/base/parts/quickinput/test/browser/quickinput.test.ts#L66-L74

**Comment by TylerLeonhardt** [comment]
I don't think we've seen this in a while so I'll close this.
