### ISSUE TITLE
native modules in vscode extension

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode#145408]
I would like bundle a vscode extension with prebuilt native binaries for all 3 major OSes (i.e. macOS, Windows and Linux).
However it seems that this is not possible.

In particular I would like to include the 
npm package serial port (https://github.com/serialport/node-serialport)
which has prebuilt binaries since version 10.

**Comment by bpasero** [comment]
> However it seems that this is not possible.

How so?

**Comment by maziac** [comment]
I had problems in the past because of vscode's electron and node version.

Is it safe to assume that the extension will not break in future vscode versions if the native packages included in the extension would use the n-api?

**Comment by bpasero** [comment]
Yes, with `N-API` you ensure that updates of Electron will not break your extension.

See also:
* https://github.com/microsoft/vscode-docs/blob/main/docs/remote/troubleshooting.md#extensions-that-ship-or-acquire-pre-built-native-modules-fail
* https://github.com/microsoft/vscode-docs/blob/main/api/advanced-topics/remote-extensions.md#using-native-nodejs-modules
