### ISSUE TITLE
Unable to unpin pinned folders from taskbar right click menu

### ISSUE THREAD

**Issue by CodeYimin** [microsoft/vscode#145475]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: Windows 11

Issue:
![Screenshot_1](https://user-images.githubusercontent.com/56568926/159147580-a947bbfd-c1d7-47a9-8f45-ef06b1d41a4b.png)
I pinned several folders to the vscode right click taskbar menu. I then changed the root folder name of my windows user (C:/Users/{I changed this}). It was a difficult process to change my user folder name since it's linked to my microsoft account, I remember messing with regedit and permissions etc. 
After doing so, I was unable to unpin the previously pinned folders. When I click the unpin icon, it just refreshes the menu and nothing happens. When I click to open, it just opens a blank file with the same file name as the folder that says "Select a language to get started. Start typing to dismiss, or don't show this again", which makes sense since I changed my user folder name so the path doesn't exist anymore.

Steps to Reproduce:
Simply making a folder, pinning it, and deleting it does not reproduce the issue. I'm not sure exactly how to reproduce other than what I said above as I don't want to go through the trouble of trying to rename the folder of my user again.

I just want a way to hard reset the pinned folders of my task bar right click menu.

**Comment by gjsjohnmurray** [comment]
Does https://github.com/microsoft/vscode/issues/69365#issuecomment-467791945 help?

**Comment by JacksonKearl** [comment]
I am not sure how these folders get pinned, is this something handled by VS Code or Windows?
