### ISSUE TITLE
The run button has disappeared. 

### ISSUE THREAD

**Issue by jin8864** [microsoft/vscode#145449]
Hi, I've been using Visual Studio Code for learning Python and the run button has worked fine until 5 minutes ago. It's disappeared all of sudden and I have no idea how to bring it back. 
I googled and people said that it will come back if I enable the Python extension, but it's enabled. 
Please let me know what I should do. 
Thanks.

**Comment by weinand** [comment]
The run button is only shown for Python files. Make sure that the Python file ends in ".py"
