### ISSUE TITLE
cin<<

### ISSUE THREAD

**Issue by QasimAhmad-khan** [microsoft/vscode#145467]
Issue Type: <b>Bug</b>

when ever i use cout and cin to enter some numeriacal input 
it shows me like some pre declared numerical

like
#include<iostream>
using namespace std;
int sum (int num)
{
    if(num!=0)
    {
        return num+sum(num-1);
    }
}
int main()
{
    int num;
    cout<<" enter the number: "<<num;
    cin>>num;
    cout<<" value is "<<sum(num);
    return 0;
}

when i run this code 
IT shows 
enter the number; 4201190 
here 4201190 is already declared i dont know what is this but every time i use to enter numerical input it shows i tried to reset the vs code settng but it didn't work

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.61GB (2.16GB free)|
|Process Argv|--crash-reporter-id 0e3be556-a9d4-4565-a49f-fc189f451abd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.4.0
code-runner|for|0.11.7
better-cpp-syntax|jef|1.15.13
remote-containers|ms-|0.224.3
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.10.4
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmc:30438804
vscaac:30438847
pynewfile477cf:30450039

```

</details>

**Comment by QasimAhmad-khan** [comment]
![Capture](https://user-images.githubusercontent.com/101948503/159136065-1f068c97-0373-435a-b273-8ae69894fdfa.PNG)
this!

**Comment by Lemmingh** [comment]
**This issue has nothing to do with VS Code. The issue tracker is not a place to learn programming.**

---

Please format your issue description with [GitHub Flavored Markdown](https://docs.github.com/en/articles/basic-writing-and-formatting-syntax), like this:

```cpp
#include <iostream>

using namespace std;

int sum(int num)
{
    if (num != 0)
    {
        return num + sum(num - 1);
    }
}

int main()
{
    int num;
    cout << " enter the number: " << num;
    cin >> num;
    cout << " value is " << sum(num);
    return 0;
}
```

Now, let's take a look at your code:

```cpp
int num;
cout << " enter the number: " << num;
```

Obviously, the local variable `num` is not initialized before using, which leads to Undefined Behavior in C++. Thus, this line may output an arbitrary number.

Using uninitialized memory is a serious pitfall. I recommend you increase the warning level of your compiler to protect you from such mistakes.
