### ISSUE TITLE
Rename from hints is not working

### ISSUE THREAD

**Issue by dickydewantoro** [microsoft/vscode#145442]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Copy java file example : Product.java and rename TestRename.java
2. At file click hints icon and click "Rename type to 'TestRename.java'"
3. Class name is not change to TestRename
![Annotation 2022-03-19 154418](https://user-images.githubusercontent.com/62507377/159114316-0acff990-4bc5-407e-b233-225293e27743.png)

**Comment by dickydewantoro** [comment]
> 
OS  : Windows

Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by dickydewantoro** [comment]
![image](https://user-images.githubusercontent.com/62507377/159115817-23f08277-c91b-4c6c-a29e-6aec491d4265.png)
error like this

**Comment by dickydewantoro** [comment]
> It looks like this is caused by the Java extension. Please file the issue to the [Java extension repository](https://github.com/redhat-developer/vscode-java). Make sure to check their [troubleshooting instructions](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting) and provide relevant information such as the extension version you're using. See also our [issue reporting guidelines](https://aka.ms/vscodeissuereporting) for more information.
> 
> Happy Coding!

![image](https://user-images.githubusercontent.com/62507377/159115928-deb48120-1fbd-4292-a461-99d8b010c136.png)

**Comment by gjsjohnmurray** [comment]
Please report this to the repository associated with the extension.
