### ISSUE TITLE
Inline suggestions are jumping

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#145586]
Using:

```
"editor.quickSuggestions": {
  "other": "inline",
  "comments": "inline",
  "strings": "inline"
}
```

* Type something to get suggestions
* Do drag and drop to select some characters

https://user-images.githubusercontent.com/5047891/159321796-99ef6370-a379-4e7c-9b88-13c97c1ea31c.mp4

**Comment by jrieken** [comment]
I see two things: 

* while inline completions are re-requested the strikeout shows 
* inline completions are showing in-between words. That's something we don't do with "normal" quick suggest

I can push a change to show inline quick suggestion at word ends only but it raises if inline completions should trigger in-between words at all or iff so if they should have more strict rules.

**Comment by jrieken** [comment]
I have pushed a change that enables inline quick suggestion only when typing at word ends. That's aligns this with "normal" quick suggestions and should feel less nervous
