### ISSUE TITLE
VSCode Debug: No Configuration loaded when .vscode/launch.json is on a network share.

### ISSUE THREAD

**Issue by Dragonsong3k** [Microsoft/vscode#14555]
- VSCode Version: 1.6.1
- OS Version: Windows 10 Version 10.0.14393

Steps to Reproduce:
1. In VSCode, open a folder using a UNC share path (\server\share\somefolder)
2. Go to Debug and try to debug a Powershell script
3. Use the Gear symbol to create the launch.json for Powershell
4. The Debug drop down will always say "No Configuration"

Trying this on a local path seems to work fine.

**Comment by isidorn** [comment]
@Dragonsong3k what happens if you click on explorer and go back to the debug viewlet? Do you see some configurations then? How about if you restart vscode?

**Comment by Dragonsong3k** [comment]
In either of those cases I do not see any configurations in the debugger drop down. I see a launch.json is created in the .vscode folder but I cant seem to get vscode to recognize that unless I use a local folder instead.

**Comment by isidorn** [comment]
Sounds like the configuration service can not read launch.json when it is on a unc share -> forwarind to @bpasero

**Comment by bpasero** [comment]
I cannot reproduce when I try from the local UNC path syntax (`\\localhost\c$\my_dir`).

@Dragonsong3k 
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by Dragonsong3k** [comment]
Sorry for the delay, Here is the requested details.

**# Dev tools console output**

keybindingsRegistry.ts:109Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  41004  for  code-runner.run
keybindingsRegistry.ts:109Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  41000  for  code-runner.runByLanguage
keybindingsRegistry.ts:109Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  41003  for  code-runner.stop
keybindingsRegistry.ts:109Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  40995  for  PowerShell.ExpandAlias
keybindingResolver.ts:190Conflict detected, command `workbench.action.terminal.openNativeConsole` cannot be triggered by ctrl+shift+c due to startanyshell.startShell
keybindingResolver.ts:190Conflict detected, command `workbench.action.terminal.copySelection` cannot be triggered by ctrl+shift+c due to startanyshell.startShell
extensionHost.ts:255[Extension Host] powershell.exe started, pid: 247476, exe: C:\WINDOWS\Sysnative\WindowsPowerShell\v1.0\powershell.exe
extensionHost.ts:255[Extension Host] Socket connected!
csharpWatcherService.ts:71 [File Watcher] [ADDED] \\pjmia-srv-dev0\PSModules\.vscode\launch.json
csharpWatcherService.ts:71 [File Watcher] [CHANGED] \\pjmia-srv-dev0\PSModules\.vscode\launch.json
csharpWatcherService.ts:71 [File Watcher]  >> normalized [ADDED] \\pjmia-srv-dev0\PSModules\.vscode\launch.json
csharpWatcherService.ts:71 [File Watcher] [CHANGED] \\pjmia-srv-dev0\PSModules\.vscode
csharpWatcherService.ts:71 [File Watcher]  >> normalized [CHANGED] \\pjmia-srv-dev0\PSModules\.vscode
csharpWatcherService.ts:71 [File Watcher] [CHANGED] \\pjmia-srv-dev0\PSModules\.vscode\launch.json
csharpWatcherService.ts:71 [File Watcher]  >> normalized [CHANGED] \\pjmia-srv-dev0\PSModules\.vscode\launch.json

**# cmdline output**

[93m[main 1:16:45 PM][0m Starting VS Code in verbose mode
[93m[main 1:16:45 PM][0m from: c:\Program Files (x86)\Microsoft VS Code\resources\app
[93m[main 1:16:45 PM][0m args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
[93m[main 1:16:47 PM][0m IPC#vscode:startCrashReporter
[168308:1115/131647:INFO:CONSOLE(66)] "Ctrl+Alt+ keybindings should not be used by default under Windows. Offender: ", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (66)
[168308:1115/131647:INFO:CONSOLE(66)] "Ctrl+Alt+ keybindings should not be used by default under Windows. Offender: ", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (66)
[168308:1115/131647:INFO:CONSOLE(66)] "Ctrl+Alt+ keybindings should not be used by default under Windows. Offender: ", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (66)
[168308:1115/131647:INFO:CONSOLE(66)] "Ctrl+Alt+ keybindings should not be used by default under Windows. Offender: ", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (66)
[168308:1115/131647:INFO:CONSOLE(62)] "Conflict detected, command `workbench.action.terminal.openNativeConsole` cannot be triggered by ctrl+shift+c due to startanyshell.startShell", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (62)
[168308:1115/131647:INFO:CONSOLE(62)] "Conflict detected, command `workbench.action.terminal.copySelection` cannot be triggered by ctrl+shift+c due to startanyshell.startShell", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (62)
[93m[main 1:16:47 PM][0m IPC#vscode:setHeaders
[93m[main 1:16:48 PM][0m IPC#vscode-workbenchLoaded
[168308:1115/131648:INFO:CONSOLE(121)] "%c[Extension Host]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (121)
[168308:1115/131650:INFO:CONSOLE(121)] "%c[Extension Host]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (121)
[168308:1115/132320:INFO:CONSOLE(89)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (89)
[168308:1115/132320:INFO:CONSOLE(89)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (89)
[168308:1115/132321:INFO:CONSOLE(89)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (89)
[168308:1115/132321:INFO:CONSOLE(89)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (89)
[168308:1115/132321:INFO:CONSOLE(89)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (89)
[168308:1115/132337:INFO:CONSOLE(89)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (89)
[168308:1115/132337:INFO:CONSOLE(89)] "%c[File Watcher]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (89)
[168308:1115/132741:WARNING:CONSOLE(2063)] "'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.", source: chrome-devtools://devtools/bundled/inspector.js (2063)

**Comment by Dragonsong3k** [comment]
I have tried deleting the launch.json and having code create a new one. That part works fine, but when I go to debug a powershell script the drop down still says No Configuration.

**Comment by Dragonsong3k** [comment]
I happened to notice that this line in the code console output
csharpWatcherService.ts:71 [File Watcher] [ADDED] \pjmia-srv-dev0\**PSModules.vscode**\launch.json
Refers to the path of the launch.json but in the paste the "\" is omitted before the .vscode

However, in the actual console, the slash is there.

![image](https://cloud.githubusercontent.com/assets/18618111/20318611/e447cac4-ab38-11e6-8e54-dee4d0079113.png)

**Comment by bpasero** [comment]
@Dragonsong3k great, thanks for that. If you restart after having created a launch.json, is the dropdown showing the changes you made?

**Comment by Dragonsong3k** [comment]
No they do not appear.

Here is the console output when I use a local path instead

Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  41004  for  code-runner.run
keybindingsRegistry.ts:109Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  41000  for  code-runner.runByLanguage
keybindingsRegistry.ts:109Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  41003  for  code-runner.stop
keybindingsRegistry.ts:109Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  40995  for  PowerShell.ExpandAlias
keybindingResolver.ts:190Conflict detected, command `workbench.action.terminal.openNativeConsole` cannot be triggered by ctrl+shift+c due to startanyshell.startShell
keybindingResolver.ts:190Conflict detected, command `workbench.action.terminal.copySelection` cannot be triggered by ctrl+shift+c due to startanyshell.startShell
extensionHost.ts:255 [Extension Host] powershell.exe started, pid: 248280, exe: C:\WINDOWS\Sysnative\WindowsPowerShell\v1.0\powershell.exe
extensionHost.ts:255 [Extension Host] Socket connected!
csharpWatcherService.ts:71 [File Watcher] [DELETED] c:\Users\raulo\Desktop\PSModules\.vscode\launch.json
extensionHost.ts:255 [Extension Host] TextEditor disposed
csharpWatcherService.ts:71 [File Watcher]  >> normalized [DELETED] c:\Users\raulo\Desktop\PSModules\.vscode\launch.json
csharpWatcherService.ts:71 [File Watcher] [ADDED] c:\Users\raulo\Desktop\PSModules\.vscode\launch.json
csharpWatcherService.ts:71 [File Watcher] [CHANGED] c:\Users\raulo\Desktop\PSModules\.vscode\launch.json
csharpWatcherService.ts:71 [File Watcher] [CHANGED] c:\Users\raulo\Desktop\PSModules\.vscode
csharpWatcherService.ts:71 [File Watcher]  >> normalized [ADDED] c:\Users\raulo\Desktop\PSModules\.vscode\launch.json
csharpWatcherService.ts:71 [File Watcher]  >> normalized [CHANGED] c:\Users\raulo\Desktop\PSModules\.vscode

**Comment by bpasero** [comment]
@Dragonsong3k to clarify, you have a "`.vscode`" folder in the folder you open with VS Code and it has a `launch.json` file within and you do not see dropdowns in the debug viewlet after a full restart? can you please share the contents of `launch.json` with me?

**Comment by Dragonsong3k** [comment]
Yes that is all correct. I have a folder called .vscode with a launch.json in it and the viewlet shows No Configuration.

Here is the contents of the file.
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "PowerShell",
            "type": "PowerShell",
            "request": "launch",
            "program": "${file}",
            "args": [],
            "cwd": "${file}"
        }
    ]
}

**Comment by bpasero** [comment]
@Dragonsong3k can add a `settings.json` file in `.vscode` with the following content and restart:

```
{
   "window.zoomLevel": 4
}
```

And see if the zooming did apply? I wonder if none of the files in .vscode can be read.

**Comment by Dragonsong3k** [comment]
I added the settings.json The zoom was not applied

![image](https://cloud.githubusercontent.com/assets/18618111/20324783/e175e314-ab4f-11e6-9404-cb8564004acb.png)

I restarted code and did not see the change.

**Comment by bpasero** [comment]
@Dragonsong3k what kind of network share is that?

**Comment by Dragonsong3k** [comment]
@bpasero It is a standard unc share path. \\server\share 
I tried with no plugins and got the same results. Its weird. I thought it was NTFS perms based but not the case.

**Comment by bpasero** [comment]
@Dragonsong3k would you be able to run VS Code out of sources?

**Comment by Dragonsong3k** [comment]
I could if someone were to show me. I am not to familiar with doing this. Is there a document on how I could do this?

**Comment by bpasero** [comment]
@Dragonsong3k https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

**Comment by bpasero** [comment]
@Dragonsong3k does it still reproduce with our insider release? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by Dragonsong3k** [comment]
I installed the insider preview and now the debugging works when the open folder is a remote share.
The only issue is that the launch.json configuration does not appear in the drop down.

![image](https://cloud.githubusercontent.com/assets/18618111/22155951/3fe5d688-deff-11e6-9f5a-b93f6b31091d.png)

**Comment by bpasero** [comment]
Hm ok, I am not sure if this is not the same bug, just meanwhile we might have changed something in the debugger to make this work :)

**Comment by sevaa** [comment]
For me, still an issue.

The share is a SAMBA one on a Debian Linux machine. I'm debugging PHP via the PHP Debug extension and XDebug. The configuration drop-down is empty, even though launch.json lists two default configurations.

When I open the very same folder via a mapped drive (as opposed to UNC), the configurations drop-down is populated.

Running with --verbose produces the following:

```
[main 9:02:08 PM] Starting VS Code in verbose mode
[main 9:02:08 PM] from: c:\Program Files (x86)\Microsoft VS Code\resources\app
[main 9:02:08 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false,
  'sticky-quickopen': false }
[main 9:02:08 PM] Unable to read folders in C:\Users\Seva\AppData\Roaming\Code\Workspaces (Error: ENOENT: no such file or directory, scandir 'C:\Users\Seva\AppData\Roaming\Code\Workspaces').
[main 9:02:09 PM] IPC#vscode-machineId
[main 9:02:09 PM] IPC#vscode-workbenchLoaded
[main 9:02:39 PM] Lifecycle#unload() 1
[main 9:02:41 PM] IPC#vscode-machineId
[main 9:02:42 PM] IPC#vscode-workbenchLoaded
```
