### ISSUE TITLE
Test: Workspace and workspace folder settings

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#145594]
Refs: https://github.com/microsoft/vscode/issues/58038

- [x] anyOS @bpasero
- [x] anyOS @luabud

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145594%0A%0A&assignees=rzhao271)

---

Workspace settings and workspace folder settings are now preserved until manually reset by the user. The rationale behind this change is that workspace settings should be specific to the workspace, and that in some cases, users were not able to override their user settings with their workspace settings using the Settings editor.

For example, let the value of `editor.tabSize` be 8 in the user settings. If we want it to be 4 in the workspace settings, we switch to the Workspace tab in the Settings editor, but see that the value is already 4. It used to be that changing the value to 5, and then changing it back to 4, would simply reset the workspace value, and the configuration service would just use the user-configured value instead, because it saw that the workspace value was unconfigured. Now, changing the value twice like that configures the workspace setting to be 4, meaning the configuration service can start using that value for the given workspace.

Note that user and remote settings are still reset and removed from the settings JSON file when the user selects a value that is the same as the default value of the setting. This behaviour may change in the future.

To test this feature:
1. After opening a folder, navigate to the Workspace tab of the Settings editor, and modify a workspace setting that has also been modified in the user settings. Then, modify the workspace setting to equal the default value, or to equal the configured user value of the setting. In both cases, the setting should still display as configured with a blue bar on the left, and the setting key should still appear in the workspace settings JSON file.
2. Reset the workspace setting. The blue bar should disappear. The setting key should disappear from the workspace settings JSON file.
3. Repeat steps 1 and 2 with a multi-root workspace open, and using the Folder tab instead of the Workspace tab. The results should be similar.
4. Repeat steps 1 and 2 with the user settings. When the user setting is equal to the default value, it should disappear from the user settings JSON file, and it should display as unmodified in the Settings editor. The same should be true for remote settings.

**Comment by bpasero** [comment]
Works as outlined here, but makes me think that it is important to explore a different presentation of a setting to account for configuration scopes at the level of the setting. So that for example I can see and adjust the value of the setting for all scopes from the setting directly and not have to switch to the workspace or folder tab.

**Comment by luabud** [comment]
Really like this improvement!
