### ISSUE TITLE
Creaate bundle js

### ISSUE THREAD

**Issue by Maheshwar234** [microsoft/vscode#145526]
Issue Type: <b>Feature Request</b>

Bundle.js is not created

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22572
Restricted Mode: No

**Comment by mjbvz** [comment]
Yes this is almost certainly not a VS Code issue
