### ISSUE TITLE
Hide sidebar loses focus on terminal to editor

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14550]
- VSCode Version: 1.7 Insider
- OS Version: macOS 10.11.6

Steps to Reproduce:

1. Focus on terminal
2. Realize I want more screen width, Cmd+B to hide sidebar
3. Now focus is on editor

I understand #14312 can be as-designed.
Toggling open sidebar -> focus on sidebar, then closing sidebar -> return focus to editor by default. This makes sense. But when terminal has focus, hiding sidebar -> focus on editor doesn't make sense.

**Comment by Tyriar** [comment]
I think the underlying issue is that the hide the sidebar command focuses the sidebar or forces focus on the editor.
