### ISSUE TITLE
precmd and preexec are invoked twice

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#145579]
>
- `precmd` and `preexec` hooks are invoked twice.
_Originally posted by @romkatv in https://github.com/microsoft/vscode/issues/142004#issuecomment-1073263418_

**Comment by meganrogge** [comment]
wonder if this is fixed now that the functions have been renamed? 

couldn't repro them being invoked twice

**Comment by romkatv** [comment]
> wonder if this is fixed now that the functions have been renamed?

Yep. `preexec` and `precmd` are special names. They get invoked without being added to `preexec_functions` and `precmd_functions`. Renaming them fixed the double invocation.

**Comment by meganrogge** [comment]
Thanks! Created an issue for that @romkatv
