### ISSUE TITLE
Esc doesn't work in macOS to exit the breakpoint expression editor

### ISSUE THREAD

**Issue by Drarig29** [microsoft/vscode#145561]
Here, the message says to hit 'esc' to exit, but it doesn't work in macOS: I have to hit 'return' instead.

https://github.com/microsoft/vscode/blob/2ca31fc845ad1e2da4fdb1b7892ab7c79dd394a7/src/vs/workbench/contrib/debug/browser/breakpointWidget.ts#L136-L145

**Comment by weinand** [comment]
@Drarig29 I cannot reproduce.
Do you still see this issue in the latest VS Code?

**Comment by Drarig29** [comment]
Hi! Sorry I forgot about this issue, and never noticed it was working again.

I can't reproduce it either, so it must have been fixed!

**Comment by weinand** [comment]
Great, thanks.
