### ISSUE TITLE
Open notebooks in vscode.dev/gh.dev is slow

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#145567]
* use GHINBs or any other notebook extension in the web
* open a notebook file
* 🐢 notice how slow the notebook opens, it takes roughly a second for its contents to appear

https://user-images.githubusercontent.com/1794099/159287099-6c9828a5-403d-4f58-8695-1ee72b439657.mov

---

The slowness is because of the fetching of "dynamic" resources. Fetching iframe resources takes ~300ms in average - that's why subsequent fetches of the same notebook are fast, but of a different notebook are slow. 

<img width="863" alt="Screenshot 2022-03-21 at 15 47 44" src="https://user-images.githubusercontent.com/1794099/159286535-66b05324-bebc-4042-8345-8cc876f33266.png">

Things that we should investigate

* Why is `*.vscode-webview.net/` so slow? @joaomoreno 
* San we reuse the same dynamic subdomain per notebook-type (or notebook extension)? That would mean only the first load of a notebook of a type is slow, not all @mjbvz @rebornix

**Comment by jrieken** [comment]
I assume the same is true for custom editors,  the web worker extension isn't suffering from this because we re-use the dynamic subdomain if possible

**Comment by joaomoreno** [comment]
> * Why is `*.vscode-webview.net/` so slow? @joaomoreno

Unsure. Maybe the fact that it's a new domain every time doesn't help at all, even at the Front Door layer.

**Comment by mjbvz** [comment]
I'm going to inline the webview's `main.js` into `index.html`. Should save one request at least

As for reusing origins, I can test to see if this makes any difference

(the ideal solution is to not need a server at all, but this is blocked by https://github.com/w3c/ServiceWorker/issues/765)

**Comment by mjbvz** [comment]
Also for the server, I wonder if a simple redirect server would be faster than having Front Door do the directs? We serving the same CDN resources for every subdomain and I suspect that Front Door is not optimized for that use case

**Comment by mjbvz** [comment]
This should be fixed now. We try using a consistent origin for the backlayer webview in notebooks: b6f4df8a5ec09a0997f6629599e19e3f4b7797a2

![Screen Shot 2022-11-03 at 3 34 18 PM](https://user-images.githubusercontent.com/12821956/199847125-35876049-99ee-42f8-8118-142a54f97c8f.png)

This allows the browser to cache the resource and also makes the CDN faster
