### ISSUE TITLE
File -> Open Folder quick pick auto complete error

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#145596]
Testing the vscode.dev insiders today and the quick pick for open folder doesn't handle auto complete properly

https://user-images.githubusercontent.com/876920/159334359-3b25647e-1f64-4e7b-990f-a5b3cc322764.mov

**Comment by bpasero** [comment]
@alexr00 owns simple file dialogs

**Comment by alexr00** [comment]
Likely a bug with https://github.com/microsoft/vscode/issues/140912
