### ISSUE TITLE
Code Definition (CTRL)

### ISSUE THREAD

**Issue by Vahan1991** [microsoft/vscode#145536]
Issue Type: <b>Feature Request</b>

Dear VS, not sure where did this issue come up, but now when I'm trying to see the code definitions or navigating via CRTL+Click, it does nothing, please help. (Have tried to re-install the app, restart PC and so on...)

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

Attachment 

https://user-images.githubusercontent.com/81253561/159236591-3b5ce540-cdd3-4b2e-85f7-4f4179f22422.mp4

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo before someone stands a chance of being able to help you.

/gifPlease by pasting a screenshot into your reply at the G website (not into a reply to a notification email from GH).

**Comment by Vahan1991** [comment]
Oh sorry that without any attachment... Here's the video (in the video when I'm trying to use CTRL on a code or variable, it does nothing)

https://user-images.githubusercontent.com/81253561/159232491-2fcb3f0e-ce10-48de-bb86-431400ddfba4.mp4

**Comment by mjbvz** [comment]
Does `Go do definition` from the command palette work?

**Comment by Vahan1991** [comment]
Have tried but hopeless, no seems from the command palette also does not work.

**Comment by mjbvz** [comment]
Did you disable the  built-in JS/TS language featrues extension. Search `@builtin typescript` in the extensions view to check this

**Comment by Vahan1991** [comment]
Have checked that, so it was disabled, and I enabled that, then it shows the code definitions now thanks! But CTRL+Click navigation is still unable to use ((( What about that?

**Comment by mjbvz** [comment]
You likely have configured `editor.multiCursorModifier`. Try switching it to `alt` so that `alt` inserts cursors and `ctrl` goes to definition

**Comment by Vahan1991** [comment]
Fine, thanks a lot, now I know how it works 👍
