### ISSUE TITLE
Tab bar display is not correctly updated when editors open and close

### ISSUE THREAD

**Issue by julie777** [microsoft/vscode#145518]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: Windows 10

Steps to Reproduce:

1. open and close many tabs

I originally planned to submit this based on 
- the last tab sometimes had the x for close after the menus icons in the tab bar
    when hovering over the tab the "X" to close would show to the right of the icons
![image](https://user-images.githubusercontent.com/5090005/159184844-a7370616-4ddc-40be-b5d8-384e7c007937.png)

- the last tab would hide the menu icons in the tab bar

I can't seem to reproduce those two issues with today's version of vscode, but I am including them for completeness.

However, there are still some things that don't look right.
Based on what I see today, maybe it is only:
1. last tab is longer than necessary and puts the close "X" at the right edge of the panel, when all other tabs are sized based on title content. The below image without hovering shows the modified file "dot", but hovering would put the "X" there too.
    
![image](https://user-images.githubusercontent.com/5090005/159184960-bfaf2d42-39a8-4855-b85e-2da4d5fb5e51.png)

2. sometimes a tab is left on a second line when there is clearly room for both it and the menu icons on the first line. Added to the previous problem it looks very strange.
    
![image](https://user-images.githubusercontent.com/5090005/159185008-8c84e565-ee3c-4876-b82f-c6c9f9c77724.png)

Just a thought, but it might also help to always have the menu icons at the end of the first line, even if there are multiple lines. That would leave less of a gap after the last tab when the next tab and the menu icons won't both fit on the first line.

**Comment by bpasero** [comment]
If you disable tab wrapping (via `workbench.editor.wrapTabs: false`), it should work as desired. With tabs wrapping enabled, in order for the wrapping to work properly, some UI behaviour was added that might seem not natural. 

Related issues: https://github.com/microsoft/vscode/issues/126532 and https://github.com/microsoft/vscode/issues/115136

**Comment by julie777** [comment]
> If you disable tab wrapping (via `workbench.editor.wrapTabs: false`), it should work as desired. With tabs wrapping enabled, in order for the wrapping to work properly, some UI behaviour was added that might seem not natural.
> 
> Related issues: #126532 and #115136

I shouldn't have to disable wrapping to get it to work correctly.
Thanks for the related issues. I will read them.

Today I have this showing. Yet another variation of bad. This time the last tab is under the menu icons.

![image](https://user-images.githubusercontent.com/5090005/159326473-30b704a9-7f97-4ffc-9122-7308055bfce4.png)

**Comment by julie777** [comment]
I read #126532 and it had the same suggest that I gave. If the last tab and the menu icons won't fit, leave the menu icons on the top line and put the tab on another line. Actually I think the menu icons should stay on the top line all the time.

**Comment by julie777** [comment]
I also read #115136 and #46403. All of them seem to be closed without a good resolution.
