### ISSUE TITLE
Test tree drag and drop API

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#145577]
Refs: https://github.com/microsoft/vscode/issues/32592

- [x] anyOS @jrieken 
- [x] anyOS @sbatten 

Complexity: 5
Roles: Developer

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145577%0A%0A&assignees=alexr00)

---

We have finally finalized the tree drag and drop API. The goal with this test is to test both the functionality and documentation of this API by adding drag and drop to an existing tree or by modifying how the tree extension sample uses it: https://github.com/microsoft/vscode-extension-samples/blob/main/tree-view-sample/src/testViewDragAndDrop.ts. 

Things to make sure are covered:
- Verify that the documentation is clear and helpful.
- Verify that trees that don't have a drag and drop controller don't allow dragging and dropping.
- Verify that only the types specified in `dropMimeTypes` are allowed to be dropped on the tree.
- Verify that `handleDrag` and `handleDrop` are called when appropriate.

**Comment by jrieken** [comment]
fyi - pushed https://github.com/microsoft/vscode/commit/945019764567961d65eb9ecb302f62a32c1836a0 to sprinkle some `{@link symbol title}` reference here and there. Figured that's simpler than filing issues

**Comment by boan-anbo** [comment]
Great feature! I have a quick question: how does one tell the difference between two intentions: 1. drop node onto another node to become the target's child, and 2. drop node before or after another node to become the target's siblings?? 

Right now I can only get 1 to work with the example.

**Comment by alexr00** [comment]
You should be able to handle this as the extension, but following what we do in the explorer view would make sense. The extension owns the tree elements and will know which ones are allowed to have children and which ones are not. Some examples:
- Drop target does not allow children: dragged elements can only become siblings.
- Drop target does allow children: it's up to the extension, but I would expect the dragged elements to become children.
