### ISSUE TITLE
Change ARM build image for ripgrep

### ISSUE THREAD

**Issue by navehgrofi** [microsoft/vscode#145541]
VSCode version - 1.65.2, Windows x64.

Im controlling RPI via Remote-SSH for over a year now.
on latest version, global search is not working on remote machine anymore.
when opening a local folder, global search works great. 
when opening remote folder, global search is only working on open files **_and only if you have viewed this file 1 time at least!_**

what i tried:

1. not use ignore files
2. remove all ignore patterns
3. delete user JSON settings file
4. verify that the "search only in open editors" button is not selected

im not sure what else to try

**Comment by roblourens** [comment]
Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" and "Log (Extension Host)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by navehgrofi** [comment]
> Please do the following
> 
> * Run the command "Set log level" and change it to "Trace"
> * Run the search again
> * Show the search-related messages in the "Log (Window)" and "Log (Extension Host)" output panel
> 
> ![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

thanks, here is the Log(Window) trace:

[https://pastebin.com/wJ0SpUrF](https://pastebin.com/wJ0SpUrF)

===============================
Log (Extension Host) output show no log from this action, but Log (Remote Extension Host) does show and here it is:

https://pastebin.com/AGgugcDf

**Comment by roblourens** [comment]
I guess this is the problem

```
[2022-03-22 12:35:46.467] [exthost] [debug] RipgrepSearchEH#search /home/pi/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/node_modules/@vscode/ripgrep/bin/rg: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /home/pi/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/node_modules/@vscode/ripgrep/bin/rg)
```

If this used to work, I guess it would be from https://github.com/microsoft/ripgrep-prebuilt/commit/f764a98a23560f7a5ad36bbde25e0372ff276253

@deepak1556 do we have a certain GLIBC requirement for vscode? Should I build ripgrep in the same image we use for vscode?

**Comment by deepak1556** [comment]
I haven't addressed this for our arm server builds yet but we will target `glibc >= 2.24` based on this table https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list.

> Should I build ripgrep in the same image we use for vscode?

Yup that sounds good and in your case it only needs to be done for the arm flavors of ripgrep which rely on the gnu C library, intel flavors are built using musl so they should be fine.

I can share the image details once I address https://github.com/microsoft/vscode-remote-release/issues/4069

**Comment by deepak1556** [comment]
Sorry forgot to update here, our arm64 server uses the following image to build https://github.com/microsoft/vscode-linux-build-agent/blob/main/centos7-devtoolset8-arm64/Dockerfile which provides support for `glibc >= 2.17`

armhf server uses https://github.com/microsoft/vscode-linux-build-agent/blob/main/stretch-armhf/Dockerfile which supports `glibc >= 2.24`

**Comment by navehgrofiSYNA** [comment]
@roblourens @deepak1556 

is there any plan to solve it?

**Comment by roblourens** [comment]
Example of an issue that will be addressed: https://github.com/microsoft/vscode-remote-release/issues/6930

We technically support glibc 2.17 in vscode, but ripgrep is not built for it

**Comment by roblourens** [comment]
We are building a statically-linked version of ripgrep now, this should be resolved.
