### ISSUE TITLE
Test inline quick suggestions

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#145548]
Refs: https://github.com/microsoft/vscode/issues/126375

- [x] anyOS @sana-ajani
- [x] anyOS @hediet

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145548%0A%0A&assignees=jrieken)

---

Quick suggestions describe the feature of showing IntelliSense while you type words (precisely: type at word ends). This can be configured via `editor.quickSuggestions`. This setting has been extend to support showing quick suggestion as inline completions (instead of showing the full suggest widget). Please test that

* `editor.quickSuggestions.[strings|comments|other]` now accept `on`, `inline`, `off` in addition to the `true` and `false`
* think about the setting names/descriptions and if they makes sense to you
* use `inline` and make sure the best matching completion shows while are typing
* you can always show the suggest widget via `ctrl+space`
* completions triggered by trigger characters, like `.` for TypeScript, still show the suggest widget
* try this for different languages like TypeScript, JSON, and CSS

**Comment by hediet** [comment]
Works nicely! (Expect the known issues, such as #145586 or flickering as discussed)
