### ISSUE TITLE
Test anycode extension pack

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#145560]
Refs: https://github.com/microsoft/vscode-anycode/issues/24

- [x] anyOS @aeschli
- [x] anyOS @bamurtaugh

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145560%0A%0A&assignees=jrieken)

---

Anycode is becoming an extension pack. There is now `anycode` and `anycode-rust`, `anycode-java` etc pp. This TPI is to make sure that anycode is now an extension pack. _Note_ that the latest version isn't released to the marketplace yet (due to other limitations) For now, it needs to be installed from VSIX. Do the following:

* uninstall anycode if you have it installed
* install the extension from this VSIX [anycode-0.0.61.vsix.zip](https://github.com/microsoft/vscode/files/8316161/anycode-0.0.61.vsix.zip)
* make sure it also installs language extensions like `anycode-cpp`, `anycode-php` etc. It should be 8 language extension plus anycode itself
* pick any of the languages, like php or rust, and make sure anycode works for me, e.g offers outline

**Comment by aeschli** [comment]
I only see 7 languages + anycode. Looks like anycode-typescript is missing. Created #145739
