### ISSUE TITLE
shell integration does not work when rc define aliases for certain things

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#145580]
>
- Breaks when user rc files define aliases for things like `history` or global aliases for things like `-n`.
_Originally posted by @romkatv in https://github.com/microsoft/vscode/issues/142004#issuecomment-1073263418_

**Comment by connor4312** [comment]
This doesn't seem fixed for me.

1. Use zshell with shell integration turned on
2. Add the aliases from https://github.com/microsoft/vscode/issues/145580#issuecomment-1074182188 to the end of my `.zshrc`
3. Create a terminal. Notice an error gets printed and there's no decorations

![image](https://user-images.githubusercontent.com/2230985/165819979-74d79a95-0200-451f-ae8d-95ac6cbebf95.png)

**Comment by meganrogge** [comment]
@connor4312 that also happens with that example in ITerm. Try with just the first alias IE `alias history=for`. It will work
