### ISSUE TITLE
JSX comments

### ISSUE THREAD

**Issue by vvatikiotis** [Microsoft/vscode#14553]
- VSCode Version: 1.6.1
- OS Version: Mac OS 10.11.6

Is there a way to comment JSX?

**Comment by weinand** [comment]
@vvatikiotis I don't understand what you mean. Please explain.

**Comment by vvatikiotis** [comment]
In MacOS Cmd-/ comments out the current line and the comment syntax depends on the language the opened file is associated with. When editing a `.js` file with JSX code in it, Cmd-/ comments out using the JS line comment syntax, `//`. That's correct for JS code, but not correct for JSX code.

Ideally, what I want to do is, select some JSX code and when Cmd-/ I want that particular code to be enclosed in `{/* */}, which is the JSX comment syntax. Is this a VSS core function or does it depend on something else, e.g. an extension?

Thx

**Comment by waderyan** [comment]
@vvatikiotis thank you for the explanation. I believe this is a language service issue. Migrating to TypeScript repo (TypeScript powers the JavaScript language service).

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11960
