### ISSUE TITLE
Coverage on non-built VS Code only covers *.js files

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode#145598]
1. Build VS Code locally
2. Run `test.[sh|bat] --coverage` (note that this is currently broken, see https://github.com/microsoft/vscode/issues/145593 for workaround)

The coverage files are generated, but they only show coverage for the *.js files. 

![image](https://user-images.githubusercontent.com/28519865/159333644-d7013f17-36ac-4a8d-80f1-08e0bde95e21.png)

This was broken with https://github.com/Microsoft/vscode/commit/43552705438d57a706cba465ee3a2c354124a082 - since we inline the source maps for non-built compiles now the .js.map files aren't generated which means that https://github.com/Microsoft/vscode/blob/ca5144362b0d8a8908127c99f942d69f86d4933e/test/unit/coverage.js#L27 fails to find it.

If I comment that line out then the source map files are generated and coverage works as expected. 

![image](https://user-images.githubusercontent.com/28519865/159335682-d7bfa10d-5c46-4793-8afe-5a8f9b8b942f.png)

**Comment by Charles-Gagnon** [comment]
@connor4312 I'm not sure the context of the change you made - was that fixing some other issue?

**Comment by connor4312** [comment]
We may fix this eventually, perhaps for self-hosting purposes when I add code coverage to built-in VS Code testing. But right now code coverage is not something that we have great interest in.
