### ISSUE TITLE
Test: terminal scroll bar annotations 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#145599]
Refs: #144595

- [x] macOS @rebornix  
- [x] linux @roblourens  
- [x] windows @rzhao271 

Complexity: 4

Authors: @meganrogge, @Tyriar 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145599%0A%0A&assignees=meganrogge,Tyriar)

---

The terminal now features [shell integration](https://github.com/microsoft/vscode/issues/141339) with the opt-in setting `terminal.integrated.shellIntegration.enabled`. 

Since a shell script needs to be written on a shell-by-shell basis, only the following are currently supported:

- Windows
  - pwsh (6+, not "Windows PowerShell")
- Linux/macOS
  - pwsh
  - bash
  - zsh

Last iteration, we added command decorations decorations (codicons) to the left gutter of the terminal in order to bring awareness to some of the new insights and capabilities shell integration provides. 

This iteration, we added scroll bar annotations corresponding to the command decorations. 

Verify that:
- each annotation's color matches the command decoration associated with it
- for errors, the annotation appears to the right 
- for success/default, the annotation appears to the left
- the color is updated when the associated `workbench.colorCustomization` is changed 

Some things to try:
- run `clear` and similar commands - the annotations should disappear
- scroll - make sure they show and hide appropriately
- anything else you can think of
- change the renderer type via `terminal.integrated.gpuAcceleration`
- open an alt buffer - for ex, `vim`, verify the annotations aren't shown there
- close an alt buffer - `esc :wq` and verify the annotations come back

Known issues:
- https://github.com/microsoft/vscode/issues/145214
- https://github.com/microsoft/vscode/issues/145227

**Comment by roblourens** [comment]
Sweet, no problems at all

**Comment by rebornix** [comment]
It looks pretty nice, good work!
