### ISSUE TITLE
no connect to marketplace

### ISSUE THREAD

**Issue by procolost** [microsoft/vscode#145512]
Issue Type: <b>Bug</b>

build  VSCode from release tag, tried to open the marketplace, no results showing up. Looks like there is no internet connection. Even though I do have internet, no proxy and Visual Studio works normally

VS Code version: Code - OSS 1.65.2 (03f12fb7d4a4aa99f0aee6205adaaba676e4e3c4, 2022-03-19T21:54:22.671Z)
OS version: Linux x64 5.16.12-200.fc35.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3704)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|15.58GB (6.90GB free)|
|Process Argv|--verbose|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
OSS build cannot connect to Marketplace. To install an extension, download the VSIX file from Marketplace, then drop it onto the Extensions view.
