### ISSUE TITLE
Release notes tab does not zoom properly

### ISSUE THREAD

**Issue by cveld** [Microsoft/vscode#14557]
- VSCode Version: 1.6.1
- OS Version: Windows 7

Steps to Reproduce:

1. Open up Release notes tab 
2. Zoom some factor

The result is that the content pane's width and height are decreasing with each zoom level. E.g.

![image](https://cloud.githubusercontent.com/assets/6196260/19743576/0f7564f0-9bca-11e6-95b9-a654b731024c.png)

**Comment by joaomoreno** [comment]
#5745
