### ISSUE TITLE
Writting Problem

### ISSUE THREAD

**Issue by Mandy1200** [microsoft/vscode#145571]
From a month I'am trying to typing , but it was only showing a block and letting me to type, please help me the main problem is in the cursor
![Screenshot (56)](https://user-images.githubusercontent.com/102048798/159297381-abce3990-b7e9-4d8f-acb9-433187aad53b.png)

**Comment by lramos15** [comment]
Please try disabling all your extensions

**Comment by Lemmingh** [comment]
@Mandy1200
Judging from the left corner of your Status Bar, you have a Vim emulator enabled, which traps all your input.

You'd better not install such extensions **unless** you're very familiar with Vim.

**Comment by Mandy1200** [comment]
Thank You So Much 😀
