### ISSUE TITLE
Show message in the terminal when shell integration is disabled by the shell

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#145583]
Pertains to the feedback
_Originally posted by @romkatv in https://github.com/microsoft/vscode/issues/142004#issuecomment-1073263418_

**Comment by rchiodo** [comment]
This doesn't seem to work for me?

pwsh shows this:

![image](https://user-images.githubusercontent.com/19672699/159762449-5561cad3-1172-4e79-8eb6-11316a75e234.png)

cmd shows nothing? Is it supposed to show shell integration is not enabled?
![image](https://user-images.githubusercontent.com/19672699/159762519-ae6bbb3c-cc53-42da-aa56-1c392270fc6a.png)

**Comment by Tyriar** [comment]
Sorry should have added repro steps here, additionally we decided against the warning so this will be covered in the verification of https://github.com/microsoft/vscode/issues/145582

**Comment by rzhao271** [comment]
I'll add on verification-needed and verified so it doesn't show up in the queries.
