### ISSUE TITLE
Issue with vscode.workspace.getConfiguration

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14559]
- Install the python extension
- Create a folder with one python file
- Open in vscode and see that you have python intellisense. 
- Close/reopen vscode on the same folder
- Now the extension fails to load with this error - 

![image](https://cloud.githubusercontent.com/assets/323878/19744550/d2e1b120-9b82-11e6-8b48-6e76fe930645.png)

This works in stable. Debugging, it looks like an issue with these lines -

```typescript
let pythonSettings = vscode.workspace.getConfiguration('python');
this.pythonPath = systemVariables.resolveAny(pythonSettings.get<string>('pythonPath'));
```

The first time the folder is opened, (and every time in stable), `pythonSettings.get('pythonPath')` returns 'python', which is the default value of that setting. If I add a settings.json file in the workspace with 'python' or some other interpreter, it works. Otherwise, it seems like vscode is doing the wrong thing.

**Comment by bpasero** [comment]
@alexandrudima fyi maybe a regression from your changes?

**Comment by roblourens** [comment]
Actually I think this is #14500 according to DonJayamanne/pythonVSCode#14500
