### ISSUE TITLE
Test simple file dialog "Save As" filename suggestion

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#145573]
Refs: https://github.com/microsoft/vscode/issues/140912

- [x] macOS @lychung7
- [x] windows @dbaeumer
- [x] wsl @karthiknadig
- [x] dev container @TylerLeonhardt

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145573%0A%0A&assignees=alexr00)

---

1. If not testing with a remote, set `"files.simpleDialog.enable": true`.
1. Open a folder that has a file in it.
1. Open the file.
1. Run the "Save as" command.
1. Change the name of the file in the input box, but don't accept the change. 
1. Change file directories using keyboard and mouse. 
1. Verify that when you change directories your new filename is preserved.

**Comment by TylerLeonhardt** [comment]
works really well! @alexr00 should we also test with RemoteHub or is that separate?

**Comment by alexr00** [comment]
If it works with all of the already tested options then RemoteHub should also be ok!
