### ISSUE TITLE
Test updating extension to specific target platform

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#145544]
Refs: https://github.com/microsoft/vscode/issues/141696

- [x] windows @chrmarti (x64)
- [x] windows @devinvalenciano (x64)

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145544%0A%0A&assignees=sandy081)

---

VS Code on Windows 64 falls back to install an extension that is compatible with Windows 32 bit if the extension does not have Windows 64 bit version. If 64 bit version is available later, VS Code shall update to it. To test:

- Create a sample extension and publish it for `win32-ia32` target platform. Make sure you have a command that prints `Hello Windows 32` (For help refer to [publish docs](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions))
- Make sure this extension can be installed in windows x64 platform
- Publish same version of the above extension for `win32-x64` target platform - Change the command to print **Hello Windows 64**
- Make sure VS Code updates to `win32-x64` version.
- Test other possible scenarios and make sure VS Code installs and updates the best compatible version available.

**Comment by chrmarti** [comment]
I notice it updates to and installs a newer ia32 version when there is an older x64 version available. Is this expected? If the x64 release is delayed for some reason, users might see an update to the newer ia32 version and later another update to the x64 version when that becomes available.

(Similarly when there is a x64 stable version and an ia32 pre-release version, but I guess that is part of the same logic and reasoning.)

**Comment by sandy081** [comment]
Yes, it is expected. We always tries to install latest compatible version. Since ia32 is compatible with x64 we install it. 

> If the x64 release is delayed for some reason, users might see an update to the newer ia32 version and later another update to the x64 version when that becomes available.

Yes, hence we recommend extension authors to publish x64 first then ia32 as part of their publish pipeline.
