### ISSUE TITLE
Feature Request:  Find in files>Replace All option to save and close

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#14554]
- VSCode Version: Version 1.7.0-insider
- OS Version: 10.12.1

Currently when you execute "find in files" and want to replace multiple items in many files, the files all open into the editor.  You then need to either save each or "save all", and then close them all.

It would be nice to have an option to do the bulk replace without the files needing to open at all in the workspace, as is possible with Atom and Sublime.

**Comment by sandy081** [comment]
@bpasero Is it possible to do bulk edits without opening the files?

**Comment by bpasero** [comment]
@sandy081 yeah easy, if you configure auto save delay below 1s, I do not see the files opening. I think if you save after bulk edit quickly enough, the files will not open 👍

**Comment by Skura23** [comment]
Nearly a year passed. Seems that this function is still not added, do you have any work around on this by now? @smlombardi

**Comment by smlombardi** [comment]
@Skura23 Nope, I've just learned to live with it.

**Comment by Skura23** [comment]
@smlombardi alright, me too...

**Comment by keego** [comment]
Any updates? This issue has been quite frustrating to me as it makes refactoring much more time consuming (and nearly impossible in large applications). Changing my auto-save settings to under 1 second as mentioned above still opens all the files, which I have to manually close (user settings have `"files.autoSave": "afterDelay"` and `"files.autoSaveDelay": 500`). Not to mention I have to toggle auto save back off for my live-reload flow to continue working.

The most reasonable workaround I've found is to spin up Atom and do a find-and-replace-all through there. It would be really nice for VS Code to have a find-and-replace-all flow similar to the on point user experience Atom provides.

**Comment by JJTimmons** [comment]
+1

**Comment by boyangwang** [comment]
+1 on this

**Comment by gusbemacbe** [comment]
Referring to https://github.com/Microsoft/vscode/issues/22322.

3 months passed...

It is one of the worst experiences I had in VSCode, both stable and insider. I prefer replacing a word in all files and saving all files **without** opening the files. 

Microsoft really failed.

**Comment by sandy081** [comment]
Sorry for not getting on to this due to other priorities.

Will look into this in February.

Thanks.

**Comment by AlCalzone** [comment]
I just ran into this issue aswell. I want to replace one line in 2800 text files of ~700 KB each (18000 lines). Before anyone asks, these are automatically generated input files for numeric parameter study.

Replace preview works just fine, but when I actually do replace them, it kills VSCode.

**Comment by sandy081** [comment]
Replace action will save the file automatically. Because of this, files are not opened while replacing all.

**Comment by gusbemacbe** [comment]
@sandy081, I have just updated... but the files still open when replacing one word in all files.

**Comment by sandy081** [comment]
@gusbemacbe This will be available from tomorrow's insiders

**Comment by gusbemacbe** [comment]
@smlombardi, @Skura23, @JJTimmons , @boyangwang and all!

# Microsoft has just updated the version of VSCode and you can find and replace one word in all file **without opening**!!! I tested and it worked!
