### ISSUE TITLE
Folder path truncated after resizing window

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14558]
![image](https://cloud.githubusercontent.com/assets/323878/19744356/12eabef2-9b82-11e6-9475-553c06c6a74e.png)

Make the vscode window small, then open a file that will show the folder path hint. Here, the user settings file. Then maximize the window, and the label is cut off.

**Comment by bpasero** [comment]
This looks like a chrome rendering bug to me because the span has enough space it just does not show the path:

![image](https://cloud.githubusercontent.com/assets/900690/19755800/67851c32-9c18-11e6-9185-6999ea9c98df.png)

**Comment by bpasero** [comment]
Seems to be fixed in Chrome 53.
