### ISSUE TITLE
Don't save / Abort swapped

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#1455]
When you open a file in the latest update, make changes to it, close the file a dialog pops up "would you like to save the file". Clicking Don't Save will do nothing and close the dialog, clicking Abort will discard the changes without saving.

**Comment by bpasero** [comment]
This has been fixed for 0.10.5, please reopen if you still see it there!

**Comment by felixfbecker** [comment]
Fixed, thanks
