### ISSUE TITLE
New Toggle Maximize Panel command should have a keybinding

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#14556]
- VSCode Version:1.7.0 insiders
- OS Version:Windows 10

Toggle commands should have a keybinding and users will want to quickly maximize then shrink the panel.
Perhaps a binding with Ctrl+Shift to match other panel commands. How about Ctrl+Shift+A?

**Comment by isidorn** [comment]
No, this was discussed in the ux meeting and we decided against it.
This action is only for a specifc users and they can assign a keybinding on their own.

**Comment by Tyriar** [comment]
We decided this because there are so few keybindings available and this is more of a power user feature so it can be bound by the user if necessary.
