### ISSUE TITLE
Workbench unresponsive unless started with `--disable-gpu`

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#145575]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Start VS Code Insiders with `code-insiders --disable-extensions` or just `code-insiders`
2. :bug: window is unresponsive (started seeing this as of today's Insiders build) 
![image](https://user-images.githubusercontent.com/30305945/159304546-173aa092-8c77-4a70-aaf3-455664b736c9.png)

Starting with `code-insiders --disable-gpu` as was recommended last time https://github.com/microsoft/vscode/issues/132086 fixes the slow startup.

**Comment by joyceerhl** [comment]
[startup.log](https://github.com/microsoft/vscode/files/8317304/startup.log)

**Comment by deepak1556** [comment]
Startup log looks healthy, couple of clarifications,

1) The issue only started with today's insider ?
2) `--disable-gpu` solves the hang ?
3) Is this on a vm ?

I am unable to repro the issue on my windows 11 machine,

**Comment by deepak1556** [comment]
Is this still happening with latest insiders which comes with newer runtime ?

**Comment by joyceerhl** [comment]
I haven't seen this in a long time, we can close it for now.
