### ISSUE TITLE
Undefined reference to external files

### ISSUE THREAD

**Issue by Joeblack1788** [microsoft/vscode#145517]
I have 3 files, main.c, openFile.c, and seconds.c. When run with VS Code, I get p_new_logic\multiple_files\" && gcc mulFile.c -o mulFile && "c:\Users\ssangcha\Documents\c_cpp_new_logic\multiple_files\"mulFile
C:\Users\ssangcha\AppData\Local\Temp\1\cc8sTL2j.o:mulFile.c:(.text+0x16): undefined reference to `openFile'
C:\Users\ssangcha\AppData\Local\Temp\1\cc8sTL2j.o:mulFile.c:(.text+0x22): undefined reference to `second'

I can ran it in command window and it works.
C:\Users\ssangcha\Documents\c_cpp_new_logic\multiple_files>g++ mulFile.c  openFile.c second.c -o mulFile

C:\Users\ssangcha\Documents\c_cpp_new_logic\multiple_files>mulFile
Print from openFile  12
second  50
I have added searchPaths but still it doesn't work.

**Comment by Lemmingh** [comment]
GitHub cannot parse your issue description properly and renders it into corrupted pieces.

Please [format it](https://docs.github.com/en/articles/editing-a-comment) with [GitHub Flavored Markdown](https://docs.github.com/en/articles/basic-writing-and-formatting-syntax).
