### ISSUE TITLE
Support prerelease semver versions in marketplace

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode#145519]
The docs for pre-release extension versions currently say

> We only support `major.minor.patch` for extension versions and `semver` pre-release tags are not supported. Support for this will arrive in the future.

I didn't find any issues that tracks this last part, i.e. an issue that tracks future support for pre-release semver tags. So maybe this issue here can be that.

Also, is there some very rough order of magnitude sense when that might happen? Weeks, months or years?

**Comment by Lemmingh** [comment]
> I didn't find any issues

The issue was transferred to the Marketplace repository:
<https://github.com/microsoft/vsmarketplace/issues/50#issuecomment-990764201>
