### ISSUE TITLE
Enable smooth scrolling by default for code and lists

### ISSUE THREAD

**Issue by psnet** [microsoft/vscode#145513]
Issue Type: <b>Feature Request</b>

`Smooth scrolling` makes visual navigation on code and lists much easier and expectable and nowadays it is a must for IDE software.

When enabled it feels much more comfortable.

VS Code version: Code 1.65.2

**Comment by joaomoreno** [comment]
I agree. But some people don't and that's why it's a setting! Thanks for the feedback!
