### ISSUE TITLE
zsh config doesn't initialize correctly with shell integration enabled

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#145587]
Turned on shell integration again, and my zsh configuration still isn't loading correctly, so I dug into it. I have these lines in my .zshrc which come from Prezto:

```
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  echo init
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
```

With shell integration disabled, $ZDOTDIR is not defined, and it enters the block. With it enabled, $ZDOTDIR is `/var/folders/tx/p0ycbfpj37786p760wwdg6y80000gn/T/vscode-zsh` so my config isn't sourced

**Comment by Tyriar** [comment]
I guess ZDOTDIR should be unset before we run the init scripts:

https://github.com/microsoft/vscode/blob/f37acd3b99f701caae29ae2f9eece1dd5e1b4c68/src/vs/workbench/contrib/terminal/browser/media/shellIntegration.zsh#L7-L16
