### ISSUE TITLE
Test drop into editor prototype API

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#145635]
Test for #142990

- [x] AnyOS @weinand
- [x] AnyOS @karrtikr

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145635%0A%0A&assignees=mjbvz)

---

## Summary

The new [drop into editor api](https://github.com/microsoft/vscode/blob/bfc026b97a1c28d8288aa2510c066d03e5bcde54/src/vscode-dts/vscode.proposed.textEditorDrop.d.ts#L10) lets extension hook into when something is dropped on a text editor

To test this api, you must set `"workbench.experimental.editor.dragAndDropIntoEditor.enabled": true` and then hold shift while dropping into the editor

## Testing

Create a new extension to test out the new `onWillDropOnTextEditor` event. Some things to try out:

- Try dropping one or more files from the explorer into an editor. Confirm you can use `resourceurls` on the `dataTransfer` to read the list of files
- Try dropping files from the OS into the an editor
- Try dropping tabs and opened editors and file lists within VS Code views wi
- Use the [tree drag and drop](https://github.com/microsoft/vscode-extension-samples/tree/main/tree-view-sample) to set custom data on the drag and then try reading it back when the tree item is dropped into the editor

Known limitations:
- At present, there is no way to get the file contents when dropping a file from the OS to web
- There is presently no UI hints that you can use shift to drop into an editor. We are actively investigating this

**Comment by weinand** [comment]
@mjbvz what do you mean by "file lists" in
> Try dropping tabs and opened editors and file lists within VS Code views wi

**Comment by weinand** [comment]
I had difficulties with testing the `cancellationToken` of the `TextEditorDropEvent`. Pressing ESC and Shift at the same time cancelled the drag-and-drop but no event was emitted.

**Comment by karrtikr** [comment]
> Confirm you can use resourceurls on the dataTransfer to read the list of files

@mjbvz I'm unable to get the type for `DataTransfer`, which makes this hard to check. What is the type?

**Comment by weinand** [comment]
@karrtikr `DataTransfer` is defined in the latest `vscode.d.ts`.
As recommended [here](https://code.visualstudio.com/api/advanced-topics/using-proposed-api#proposed-api-incompatibility) I've removed `@types/vscode`from the package.json and  used `npx vscode-dts main` to load the latest `vscode.d.ts`.
