### ISSUE TITLE
Test: rpm package dependencies

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#145608]
Refs: https://github.com/microsoft/vscode/issues/17142

- [x] linux @chrmarti (Fedora or CentOS)
- [x] linux @TylerLeonhardt (Fedora or CentOS)

Complexity: 5

Authors: @rzhao271, @deepak1556 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145608%0A%0A&assignees=rzhao271,deepak1556)

---

We now manually calculate rpm package dependencies per packaging build. This step takes around 5 seconds.
Before, we were using a hardcoded list.

Preferably on a fresh VM:

1. Obtain the latest Insiders rpm package from the builds page, as well as an older Stable package.
2. Verify the requirements list is longer than before. Also verify that the list does not contain `libffmpeg`, because we already include the `.so` file for that in the package ourselves.
3. Install the package. Verify that the package can be installed successfully.
4. Verify the package is sane, and that no missing dependencies errors show up.

**Comment by chrmarti** [comment]
Tested on CentOS 8. 👍

**Comment by TylerLeonhardt** [comment]
Tested on Fedora 👍

Funny story, I just used a live usb but it didn't have enough space to install vscode so I uninstalled the browser :)
