### ISSUE TITLE
"explorer.fileNesting.operateAsGroup" weird setting and weirder semantics

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#145665]
Testing #145640

imho all operations on the parent resource should affect the child resource. Same as with folders.
Why do we make this configurable? Do users actually not expect this and want to change this? Why is the default `false`?

If we really decide that a setting for this is needed then `operateAsGroup` is misleading because it is not actually a group. All operations on the child are not done on the parent.

**Comment by JacksonKearl** [comment]
The main problem I saw was how do we make it possible to only copy the single file when you copy a parent. One idea I considered was making the nest operate as a group when it's collapsed, but individual files when it's expanded? That way you would: 
1. collapse the nest and copy it as one item always, 
2. expand the nest and select the subset of entries you want to copy
3. expand the nest and select just the parent, then only operate on the parent.

what would you think of that flow?

**Comment by JacksonKearl** [comment]
Enabled the `operateAsGroup` setting by default though

**Comment by JacksonKearl** [comment]
Setting is removed sorry. New intended behavior is that it operates as group when collapsed.
