### ISSUE TITLE
Is setting "fileNesting.expand" really needed?

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#145666]
Testing #145640

I find the setting `fileNesting.expand` weird. Do we really need it?
Why don't we have the same setting for folders with single children.

**Comment by JacksonKearl** [comment]
> Why don't we have the same setting for folders with single children.

I actually recently put a PR up for that because I was surprised myself... #145606.

I think we do need it, folks expressed interest in both nesting as {purely an ordering mechanism} versus {a way to hide derived files by default but allow for quick access}.
