### ISSUE TITLE
Only one type of contributes entry is displayed for Extension Details Contributions

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#14564]
- VSCode Version: 1.7.0 insiders
- OS Version: Windows 7

Steps to Reproduce:

1. Look at an extension (Go, Python) which has a number of different types of contributions (settings, commands, language).
2. Extension details view Contributions only shows Settings

This does not repro for 1.6.1 stable

**Comment by joaomoreno** [comment]
Great catch.

**Comment by joaomoreno** [comment]
@sandy081 This was broken by aa4efa36

**Comment by sandy081** [comment]
@joaomoreno That was a very bad mistake. I should have swapped computation of `&&` arguments. Your fix looks simple and nice.
