### ISSUE TITLE
Unexpected group change event when opening editor in a side group

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145690]
Testing #145585

![Recording 2022-03-22 at 13 39 01](https://user-images.githubusercontent.com/900690/159483866-6fcdfb2e-1734-467c-9da9-3e6bf90ff065.gif)

I get an `vscode.window.tabGroups.onDidChangeTabGroup` event for the first group, even though all I do is open an editor in the second group.

**Comment by lramos15** [comment]
\closedWith https://github.com/microsoft/vscode/commit/95a3f881552f8ff1b044cd21183974d18363af4a

**Comment by lramos15** [comment]
You will still receive these events when we rebuild the model. i.e a group is added, a group is moved, a group is removed. However, as patching gets better less of these erroneous events should be received. This fix covers editor open and close which are quite common.
