### ISSUE TITLE
WebviewPanel onDidChangeViewState not triggering consistently on initial webview load

### ISSUE THREAD

**Issue by adamerose** [microsoft/vscode#145648]
### Steps to Reproduce:

- Run my modified version of the CatScratch sample extension ([repo link](https://github.com/adrotog/vscode-webview-focus-example))
- Open the three sample `.cscratch` files
- Left click `example1.cscratch` so it is in focus
- Reload the workspace (Command `Developer: Reload Window`)
- Observe debug console output, which seems to show 2 unexpected behaviors...
  - `webviewPanel.active` is `true` inside `resolveCustomTextEditor` for all 3 panels including `example2.cscratch` and `example3.cscratch` even though we never clicked those panels
  - The workspace reload triggers `onDidChangeViewState` for only webview panels other than the active one

![image](https://user-images.githubusercontent.com/10884874/159383352-999c09bc-7a58-44ae-a145-53f2d6e8c236.png)

Debug Console output:
```
(Initial Load) Active: true - file:///d%3A/_MyFiles/Programming/vscode-webview-focus-example/exampleFiles/example1.cscratch
(Initial Load) Active: true - file:///d%3A/_MyFiles/Programming/vscode-webview-focus-example/exampleFiles/example2.cscratch
(Initial Load) Active: true - file:///d%3A/_MyFiles/Programming/vscode-webview-focus-example/exampleFiles/example3.cscratch
(onDidChangeViewState) Active: false - file:///d%3A/_MyFiles/Programming/vscode-webview-focus-example/exampleFiles/example2.cscratch
(onDidChangeViewState) Active: false - file:///d%3A/_MyFiles/Programming/vscode-webview-focus-example/exampleFiles/example3.cscratch
```

### Additional Context

I am trying to use `onDidChangeViewState` on my CustomTextEditor webviews to keep track of the current active editor. This is done with the snippet below inside of `resolveCustomTextEditor`

```javascript
// Keep track of focus changes so we can track what the currently active editor is.
// We need to do this ourselves because with a CustomTextEditor vscode.window.activeTextEditor is always undefined.
function handleDidChangeViewState(panel: vscode.WebviewPanel, initialLoadFlag = false) {
	console.log(
		`${initialLoadFlag ? '(Initial Load)' : '(onDidChangeViewState)'} Active: ${
			panel.active
		} - ${document.uri.toString()}`
	);
	if (panel.active) {
		extensionState.activeWebviewPanel = panel;
		extensionState.activeDocument = document;
	} else {
		extensionState.activeWebviewPanel = undefined;
		extensionState.activeDocument = undefined;
	}
}
// We need to manually trigger this once inside of resolveCustomTextEditor since onDidChangeViewState does not run on initial load.
handleDidChangeViewState(webviewPanel, true);
webviewPanel.onDidChangeViewState((e) => {
	handleDidChangeViewState(e.webviewPanel);
});
```

I believe [this issue](https://github.com/microsoft/vscode/issues/111980) closed by @mjbvz is relevant.

---
<details>
<summary>Details</summary>
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
<details>
<summary>System Info</summary>
|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.95GB (39.94GB free)|
|Process Argv|D:\\_MyFiles\\Programming\\keep-clone\\backend --crash-reporter-id 4fa76dc8-18c1-4dfa-80b0-9ec9ac7ebb01|
|Screen Reader|no|
|VM|0%|
Extensions: none
</details>

**Comment by mjbvz** [comment]
This looks like a but but this sequence of events is expected with the current design as webview panels start as `active`

I'm going to change them to start as inactive when they are restored. However I'm not entirely confident some extensions out there are depending on the incorrect state so we may end up having to revert this
