### ISSUE TITLE
New editor DND insert cursor shows up in notebook cell editors

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#145644]
- Drag a notebook cell over another one
- The cursor shows up like a drop location inside the editor, but it shouldn't do that here

I assume this is related to the new feature to drag file paths into editors? Do you know about this @mjbvz?

**Comment by mjbvz** [comment]
Good find! I've gone ahead and disable dropping into the in all editors except our main text editors

In the future though I would like to support dropping into notebook cells too. Will investigate how that can be supported as we continue working on this api
