### ISSUE TITLE
Add Option to Disable "Alt" Showing Menu Bar When Toggled to be Hidden

### ISSUE THREAD

**Issue by sprinkle131313** [Microsoft/vscode#14567]
The Menu Bar can be hidden through a setting/toggle, when it is toggled to be hidden the "alt" key is used to make it temporarily visible again. Certain shortcuts require the "alt" button and most of the time I don't mean to reveal the Menu Bar but I simply misclick a shortcut which causes the menu bar to rapidly flicker open and then closed. So having an option to disable "alt" from toggling the menu would be appreciated.

I've looked through the keyboard shortcut settings and I didn't find anything associated with it there.

**Comment by xwvvvvwx** [comment]
#17517
