### ISSUE TITLE
Test CSS formatter

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#145604]
Refs: #19166

- [x] anyOS @meganrogge
- [x] anyOS @jrieken  
- [x] web @connor4312 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145604%0A%0A&assignees=aeschli)

---

- test we now provide a formatter for CSS through the built-in `vscode.css-language-features` extension
- test that it works for full documents as well as selected source ranges
- test that it works for css, less and scss documents
- test that the provided settings, e.g. for `css`
  - `css.format.enable`
  - `css.format.newlineBetweenRules`
  - `css.format.selectorSeparatorNewline`
  - `css.format.spaceAroundSelectorSeparator`

test that the setting descriptions are understandable and that the settings work. Note that there are different settings for `css`, `less` and `scss`

**Comment by connor4312** [comment]
I'm not sure what the "new line" settings are meant to do. Regardless of how I have them, they always format

```
.gh-header-title {margin-right: 150px;margin-bottom: 0;font-weight: 400;line-height: 1.125;word-wrap: break-word}.gh-header-title {margin-right: 150px;margin-bottom: 0;font-weight: 400;line-height: 1.125;word-wrap: break-word}
```

to

```
.gh-header-title {
    margin-right: 150px;
    margin-bottom: 0;
    font-weight: 400;
    line-height: 1.125;
    word-wrap: break-word
}
.gh-header-title {
    margin-right: 150px;
    margin-bottom: 0;
    font-weight: 400;
    line-height: 1.125;
    word-wrap: break-word
}
```
