### ISSUE TITLE
Extremely unresponsive

### ISSUE THREAD

**Issue by alone-jpeg** [microsoft/vscode#145609]
Issue Type: <b>Bug</b>

After the past few updates my vs code  is being totally unresponsive. I mean I can't even write a single line of code. It's so buggy. Despite my ram and CPU is more than enough and and I can even type a single character. Fi the problem ASAP!

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (2.12GB free)|
|Process Argv|--crash-reporter-id 0afb1ed3-d4ee-4cec-8509-93faf532b48f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.2
phpserver|bra|3.0.2
doxdocgen|csc|1.4.0
dart-code|Dar|3.36.0
flutter|Dar|3.36.0
vscode-html-css|ecm|1.11.0
code-runner|for|0.11.7
vscode-mysql|for|0.4.1
vscode-pull-request-github|Git|0.38.1
go|gol|0.32.0
better-cpp-syntax|jef|1.15.13
language-julia|jul|1.6.5
vscode-azureappservice|ms-|0.23.1
vscode-azureresourcegroups|ms-|0.4.0
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.2
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.3
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
azure-account|ms-|0.10.1
azurecli|ms-|0.5.0
cmake-tools|ms-|1.10.4
cpptools|ms-|1.8.4
cpptools-extension-pack|ms-|1.1.0
notepadplusplus-keybindings|ms-|1.0.7
ruby|reb|0.28.1
java|red|1.4.0
vscode-yaml|red|1.5.1
synthwave-vscode|Rob|0.1.11
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.1
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
vscode-ruby|win|0.28.0
php-debug|xde|1.25.0
php-pack|xde|1.0.3
php-intellisense|zob|1.0.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvid2:30447481
cppdebugcf:30451567
dockersurvey3cf:30453610
pynewfile477cf:30450039

```

</details>

**Comment by tanhakabir** [comment]
What happens if you start VS Code with all extensions disabled? Launch with `code --disable-extensions` to check.

**Comment by alone-jpeg** [comment]
It works fine! Thanks! 
.
I only have important extensions related to my work nothing fancy. Do you think it's for the theme extension that I installed recently?

**Comment by tanhakabir** [comment]
You can run Extension Bisect to figure out which extension is the culprit. Here's a blog on how to use it and more details about it: https://code.visualstudio.com/blogs/2021/02/16/extension-bisect
