### ISSUE TITLE
Make it open the file to drag and drop a file to third-party app.

### ISSUE THREAD

**Issue by HubKing** [microsoft/vscode#145619]
Dragging a file in the Explorer panel of VS Code to a third-party app, such as Notepad or Notepad++, just makes the app display the file path. This is different from dragging a file from File Explorer to that app, which makes the app open the file in it.

https://user-images.githubusercontent.com/10900489/159359983-57e5ec01-dc8e-40e7-9712-ff1ac696bbfc.mp4

**Comment by JacksonKearl** [comment]
Duplicate of #164
