### ISSUE TITLE
Allow to set image as background of explorer panel

### ISSUE THREAD

**Issue by folknor** [Microsoft/vscode#14569]
- VSCode Version: Any
- OS Version: Any

Hi,
So I recently started testing vscode coming from atom, and I'm proooobably here to stay :-P
The one thing I'd like to do is set a background image in the explorer panel.

Nothing fancy, I don't need an easy way to do it.
In fact, it's probably already possible with some fancy CSS file I can drop somewhere?

But Atom lets you do it through themes, so I figured I'd create this ticket for the possibility.

I clicked the "Related projects" link in the guidelines for contributing, and it guided me to the "vs themes" project, but that only seems related to icon themes and syntax themes from what I could tell. So please do excuse me if this is the wrong place for the ticket.

Thank you.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by folknor** [comment]
I don't understand that at all, so there's nothing to thank me for.

https://bugzilla.mozilla.org/show_bug.cgi?id=9940
