### ISSUE TITLE
Internal file error in explorer: this may be due to file nesting

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#145664]
Testing #145640

1. Enable file nesting. Have `hello.ts` and `hello.js`. 
2. Delete `hello.js`
3. `Cmd + Z` to restore it -> exception "internal file error in explorer" 🐛

**Comment by zkindest** [comment]
It also throws same error when moving files.

**Comment by JacksonKearl** [comment]
@zkindest I believe I fixed that within the past couple days in Insiders, are you still seeing it?

**Comment by zkindest** [comment]
It's working fine after restart.

**Comment by JacksonKearl** [comment]
Another good catch, thanks. Note to verifiers, seems to only have effected files at root of workspace.
