### ISSUE TITLE
Let f8 show current marker first

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14561]
While verifying #11400

Currently it shows next first. I looked through the keybindings but didn't find anything that shows current marker (the section enclosed by the green line)

![mark](https://cloud.githubusercontent.com/assets/4033249/19746125/da29af8a-9b89-11e6-8a30-2fa165eb24cf.gif)

**Comment by jrieken** [comment]
It's always relative to the current cursor pos

**Comment by jrieken** [comment]
Ah, I see. When you are already on a marker we should be more relaxed - ala position contains range.

**Comment by octref** [comment]
Yea, if the green hint is not present, I hope f8 will open it **for the current word/line**, and further f8 will go to the next hint.
