### ISSUE TITLE
Active group is never `undefined`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145684]
Testing #145585

There is always at least 1 tab group active, even when no tabs are opened:

```
readonly activeTabGroup: TabGroup | undefined
```

Should be

```
readonly activeTabGroup: TabGroup
```

**Comment by hannahcoles** [comment]
Hi! I am new to contributing on GitHub. Is there any way I could claim this issue?

**Comment by lramos15** [comment]
Hi @hannahcoles!

This issue in particular is not up for grabs but many of the issues in our repository are. Take a look at https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22 to see issues that require assistance and feel free to ask there for a code pointer to get you started. You can read more about how to get started contributing to the VS Code project by reading the wiki https://github.com/microsoft/vscode/wiki/How-to-Contribute

Happy coding!
