### ISSUE TITLE
A tab might not close

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145685]
Testing #145585

`Closes the tab. This makes the tab object invalid and the tab should no longer be used for further actions.`

Not if the tab is dirty and the user cancels the dialog.

**Comment by lramos15** [comment]
Maybe the promise should return an array of the closed tabs or something along those lines. How will the user know which tabs are still good? How do we know what tabs are cancelled from `group.CloseEditors`?

**Comment by bpasero** [comment]
Workbench tends to return a `boolean`, but interestingly not for `closeEditors`, only `closeEditor`.

**Comment by lramos15** [comment]
> Workbench tends to return a `boolean`, but interestingly not for `closeEditors`

Wonder if we should enhance it to turn an array of booleans that way we know which closes were successful and which were not
