### ISSUE TITLE
Test: Pasted text copied from a terminal should retain colors

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#145601]
Refs: #20813

- [x] macOS @kimadeline
- [x] linux @dbaeumer  
- [x] windows @minsa110 

Complexity: 2

Authors: @meganrogge, @Tyriar 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145601%0A%0A&assignees=meganrogge,Tyriar)

---

The terminal has a new context menu entry, `Copy as HTML` and a new action `Terminal: Copy as HTML`. This enables copying the terminal buffer as HTML.

Find some apps that support rich text pasting - for example, Outlook. You can verify they support this via copying and pasting from the editor into the app; if the text retains its colors, ✅ . 

Verify that the action carries over color and styling of the terminal text to the app when the text is pasted.

A helpful terminal command for testing is `msgcat --color=test`

**Comment by dbaeumer** [comment]
Small tip: to have an application you can paste HTML log into office in the Web.
