### ISSUE TITLE
Make it clear in docs that returning an InputBoxValidationSeverity.Error the InputBox will not be accepted

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#145673]
Testing #145626

If you return an `InputBoxValidationSeverity.Error` the `InputBox` will not be accepted on Enter. This makes sense but I think it should be called out in docs. Or maybe I missed it and this is a common pattern that we already do?

**Comment by TylerLeonhardt** [comment]
Verification: use the proposed API (`inputBoxSeverity`) and read the new docs associated with the `InputBoxValidationMessage` interface.
