### ISSUE TITLE
Replace all shortcut doesn't work anymore 

### ISSUE THREAD

**Issue by franciscocpg** [Microsoft/vscode#14566]
```
Visual studio code

Version 1.6.1
Commit 9e4e44c19e393803e2b05fe2323cf4ed7e36880e
Date 2016-10-13T15:43:46.054Z
Shell 1.3.7
Renderer 52.0.2743.82
Node 6.5.0
```
```
XUbuntu

NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

Linux francisco-Inspiron-5537 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Replace All (Ctrl+Alt+Enter) is not working at Edit -> Replace (Ctrl+H).

I realize this issue after 1.6.0.

**Comment by sandy081** [comment]
October for investigation

**Comment by sandy081** [comment]
@franciscocpg <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Enter</kbd> is triggering replace all for me. Can you please check your keyboard bindings and see if it is not taken by another command?

Thanks

**Comment by franciscocpg** [comment]
@sandy081,
After opening developer tools I realize that it is a plugin problem so I created this issue https://github.com/DonJayamanne/pythonVSCode/issues/470.
