### ISSUE TITLE
Notebook find decorations are not removed when clearing the search text

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#145675]
Testing #145636

1. Create a new `.ipynb` notebook with the following code in the cell 
```
str1 = "Foo"
str2 = "Bar"

# convert both the strings into lowercase
str1 = str1.lower()
str2 = str2.lower()

# check if length is same
if(len(str1) == len(str2)):

    # sort the strings
    sorted_str1 = sorted(str1)
    sorted_str2 = sorted(str2)

    # if sorted char arrays are same
    if(sorted_str1 == sorted_str2):
        print(str1 + " and " + str2 + " are anagram.")
    else:
        print(str1 + " and " + str2 + " are not anagram.")

else:
    print(str1 + " and " + str2 + " are not anagram.")
```
2. Press `Cmd + F` to bring up the search widget. Press `s` to which will display the find decorations
3. Delete `s` in the find widget -> Find decorators are not being removed
![image](https://user-images.githubusercontent.com/3372902/159472298-622d8f9c-53c0-4ecb-9985-cd3450b78a4d.png)

**Comment by rebornix** [comment]
@lszomoru thank!
