### ISSUE TITLE
Enable the debugger to show the process ID

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#145633]
The VS debugger UI supports this.

When I initially use the C/C++ debugger to attach to a process, it shows the process ID in the dropdown, but then I can't remember it and then I need to check later on which process ID I'm attached to and it doesn't show me in the UI.

Our debugger team says this is a limitation in VS Code and not our C/C++ extension.

**Comment by weinand** [comment]
Please be more specific: where in the UI do you want to see the process ID?
A screenshots might help.

**Comment by sean-mcmanus** [comment]
Anywhere I guess, as long as it's visible. VS shows it as part of the Debug toolbar menu control:
![image](https://user-images.githubusercontent.com/19859882/159434245-8883cc13-4d77-4643-a113-d5211cfcd959.png)

Maybe near the top in some of the existing UI sections. As long as it doesn't get in the way of other stuff. I wouldn't mind expanding a tool view or whatever like the call stack view, etc.
![image](https://user-images.githubusercontent.com/19859882/159434802-b027d1b9-cbe2-41ff-89c6-a60d2dfae3b1.png)

I don't really need the process name to appear but you can if you want -- the process name already appears in the call stack symbol info if I forget.

**Comment by weinand** [comment]
I don't recognize the first screenshot as something that VS Code provides. Could you show that with more context?

Typically processes are shown in the CALL STACK view:

<img width="479" alt="CleanShot 2022-03-22 at 09 31 42@2x" src="https://user-images.githubusercontent.com/1898161/159439482-5f34aa2d-f410-4e2f-b7ce-c759cbf7f555.png">
Is this not possible for C++?

**Comment by sean-mcmanus** [comment]
The 1st screenshot is from Visual Studio 2022.

Showing the process ID in the call stack window would be fine with me too -- are you saying that our C/C++ debugger could show it there? @WardenGnaw is our debugger developer.

We currently just show the threads used without any process node in the tree:
![image](https://user-images.githubusercontent.com/19859882/159445315-95dd85d8-7ad1-4f34-b4f3-6bc067d76242.png)

**Comment by weinand** [comment]
@sean-mcmanus yes, showing the process ID in the CALL STACK view is the recommended way (since there is no other place where to show it and since VS Code knows nothing about processes).

And if the thread name gets truncated because it's too long, then the hover will show the full name
(we have fixed related issue https://github.com/microsoft/vscode/issues/144540 in this milestone).

**Comment by sean-mcmanus** [comment]
Okay, thanks a lot for the info -- I filed a feature request on our C/C++ extension instead: https://github.com/microsoft/vscode-cpptools/issues/9065

**Comment by WardenGnaw** [comment]
> (since there is no other place where to show it and since VS Code knows nothing about processes).

In the multi-session view there is a dropdown showing the configuration name that was used.
![image](https://user-images.githubusercontent.com/3953714/159569537-c469bd97-a075-4dd3-a7cf-d9ce074db497.png)

Can we use this to show the process name and PID, and instead of showing it during multiple sessions, just always show it? VS Code can get this information via the [Process Event ](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Process)

**Comment by sean-mcmanus** [comment]
@WardenGnaw Should I re-open this issue?

**Comment by weinand** [comment]
@WardenGnaw the dropdown shows debug sessions and VS Code does not know how they relate to processes. This is an implementation detail of the debug extension.

**Comment by WardenGnaw** [comment]
The debug extension can add a specific support for it by adding it to the thread name in the CallStack window but that seems to be a workaround. Another question is, how can a debug adapter re-write the session label?

I believe this is better handled with the VS Code UI if it sees a debug adapter that sends a ProcessEvent. This would allow any debug adapter that sends a ProcessEvent to have the process name and process id shown in the UI.

**Comment by weinand** [comment]
How should this work?

See this node.js example: one session (and hence no dropdown) and 7 processes:

<img width="878" alt="CleanShot 2022-03-23 at 10 17 50@2x" src="https://user-images.githubusercontent.com/1898161/159665297-2faa5d69-2455-43b0-92d3-205f788f3885.png">

> Another question is, how can a debug adapter re-write the session label?

A debug adapter cannot not, but the extension can:

![CleanShot 2022-03-23 at 10 21 50@2x](https://user-images.githubusercontent.com/1898161/159666016-9184c1b0-efc6-4572-a38a-d9705feeb9c7.png)

**Comment by WardenGnaw** [comment]
Both C++/C# extension will have a single process but multiple threads.
The images below come from a single process spawning multiple threads and there is no way to see what the current PID is. 
![image](https://user-images.githubusercontent.com/3953714/159765548-962ed61e-0a38-4228-a5e2-efb312345f6e.png)

If we start adding it to the threads, it starts being a bit too redundant even with multiple sessions 
![image](https://user-images.githubusercontent.com/3953714/159768225-6fde8d95-77cd-468f-931b-2172f2ac795a.png)

It also looks like the session name only shows up if there are multiple debug sessions, so even if we update the session name, it will not be visible unless there are multiple sessions. 

If its possible to get something like this for a single session:
![image](https://user-images.githubusercontent.com/3953714/159768540-7b547e6a-6169-4364-829b-8cfeb74af936.png)

**Comment by sean-mcmanus** [comment]
I'd be fine with the info available on hover.

**Comment by WardenGnaw** [comment]
How do I modify the hover label? All I could get on hover is `Thread`.

I also don't see it in the DAP protocol in the [Thread](https://microsoft.github.io/debug-adapter-protocol/specification#Types_Thread) object.
