### ISSUE TITLE
Have a `TabKind` for split in editor group

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145688]
Testing #145585

There is currently no tab kind for an editor that is split inside a group. The workbench typically treats this kind of editor as if it was just 1 editor.

![image](https://user-images.githubusercontent.com/900690/159483163-210ffae7-5bbc-43bf-9354-140deb15a620.png)

**Comment by jrieken** [comment]
Yeah, some initial sketch for this was a generic type that has a direction (vertical or horizontal) and "child" inputs. That's more than we currently allow for but will be future proof. 

```ts
class TabKindSplit {
	readonly all: Array<TabKindText, TabKindNotebook, TabKindCustom, TabKindTextDiff, TabKindNotebookDiff>;
	readonly direction;
}
```

**Comment by lramos15** [comment]
I decided to make the split in editor group just report as TabKindText.

To verify:

Ensure that a tab that was `Split in editor group` reports as `TabKindText` with the proper resource.

**Comment by bpasero** [comment]
Yes, for this case that is a good solution 👍

**Comment by hello-smile6** [comment]
> Testing #145585
> 
> There is currently no tab kind for an editor that is split inside a group. The workbench typically treats this kind of editor as if it was just 1 editor.
> 
> ![image](https://user-images.githubusercontent.com/900690/159483163-210ffae7-5bbc-43bf-9354-140deb15a620.png)

Can reproduce, encountered it about an hour ago

**Comment by lramos15** [comment]
@hello-smile6 I do not think the updated insiders was out yet to test these. Please updated your code insiders and try again. Thanks!

**Comment by hello-smile6** [comment]
> @hello-smile6 I do not think the updated insiders was out yet to test these. Please updated your code insiders and try again. Thanks!

I'm referencing the stable version.

**Comment by lramos15** [comment]
> I'm referencing the stable version.

Ah yes. This fix is only in the insiders version of VS Code. It will be in stable next month.
