### ISSUE TITLE
Extension changelog only displays if extension is installed

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#14562]
- VSCode Version:1.7.0 insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Search for an extension with a CHANGELOG.md (example Go, Debugger for Chrome)
2. In the Extension View details, select the Change Log view

Shows "No Changelog available."

3. Install the extension and reload

Now the changelog can be viewed.

**Comment by joaomoreno** [comment]
Extensions need to be published with a recent version of vsce.

**Comment by gregvanl** [comment]
@joaomoreno Reopening to double check.  The symptom is that changelogs are not displayed when viewing uninstalled extensions from the Marketplace but are displayed once the extension is installed. The extensions have enough metadata to display the changelog when they are under .vscode-insiders\extensions. Is there another change required for changelog viewing from the Marketplace?

**Comment by joaomoreno** [comment]
Thanks for rechecking. But yes: there is another change. Only later versions of vsce publish extensions with the correct metadata for this feature to work. Microsoft/vscode-vsce#132 was the issue tracking this.

When an extension is installed locally, the mechanism is different since all data is local.

**Comment by gregvanl** [comment]
Got it. I was going to call out these new Details sections in the release notes but we may want to wait until more extensions fully support the changelog.

**Comment by gregvanl** [comment]
@joaomoreno Which changelog version will take precedence, the local installed version or the Marketplace one, perhaps updated? I can see arguments for either, should the user what they have or show them what they'll get. The same applies to the Readme.
I'm in favor of showing the Marketplace versions.n

**Comment by joaomoreno** [comment]
👍  Create an issue for it.

**Comment by gregvanl** [comment]
https://github.com/Microsoft/vscode/issues/14616
