### ISSUE TITLE
Do not offer both Stop and Disconnect when supportTerminateDebuggee is false

### ISSUE THREAD

**Issue by polinasok** [microsoft/vscode#145650]
If an adapter does not set `SupportTerminateDebuggee`, the UI should show only one option to end the session. With the following traffic:
```
client <- {"seq":0,"type":"response","request_seq":1,"success":true,"command":"initialize","body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":true,"supportsConditionalBreakpoints":true,"supportsEvaluateForHovers":true,"supportsSetVariable":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsLogPoints":true,"supportsDisassembleRequest":true,"supportsClipboardContext":true,"supportsSteppingGranularity":true,"supportsInstructionBreakpoints":true}}
client -> {"seq":2,"type":"request","command":"launch","arguments":{"name":"Launch file","port":54321,"type":"go","request":"launch",...}}
...
```
I still see both options, even though they will result in identical behavior.
<img width="336" alt="image" src="https://user-images.githubusercontent.com/51177946/159412099-619fad36-5c06-482b-817e-e0a7d96b4666.png">

The same approach should apply to `suspendDebuggee`-based controls when they are added in https://github.com/microsoft/vscode/issues/134412.

**Comment by weinand** [comment]
We could address this as part of #134412

**Comment by roblourens** [comment]
The menu infrastructure doesn't support disabling the alt action, but I filed https://github.com/microsoft/vscode/issues/147024, looking into it.

**Comment by weinand** [comment]
Oh, I see... thanks for trying and filing https://github.com/microsoft/vscode/issues/147024
