### ISSUE TITLE
Test: Reduced Motion

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#145641]
- [x] macOS @daviddossett
- [x] Windows @alexr00

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145641%0A%0A&assignees=JacksonKearl)

---

Ref #128595

With this release VS Code adapts to the OS's "Reduce Motion" config, and provides the `workbench.reduceMotion` setting to override the behavior on or off. Test:

- Reduced motion mode is enabled based on OS setting and/or `workbench.reduceMotion` enablement. 
- Animations are removed when in reduced motion mode (see getting started, view collapsing, find widget)
- Extension contributed webview editors and views can adapt to reduced motion via the `.reduce-motion` class placed on the root element.

**Comment by alexr00** [comment]
What kind of motion should I expect to get reduced when I put `reduce-motion` on the root element of a webview? I tried adding a css animation, but it still animated. I also can see that `vscode-reduce-motion` is automatically added to the root element of my webview.

**Comment by daviddossett** [comment]
> Reduced motion mode is enabled based on OS setting and/or workbench.reduceMotion enablement.

Worked 👍

> Animations are removed when in reduced motion mode (see getting started, view collapsing, find widget)

Worked 👍

>Extension contributed webview editors and views can adapt to reduced motion via the .reduce-motion class placed on the root element. 

Worked 👍 

```
body {
  animation: slidein 1s;
}

.vscode-reduce-motion {
  animation: none;
}
```
