### ISSUE TITLE
How to set some files / folders to read-only mode and cannot be edited

### ISSUE THREAD

**Issue by yalezhangk** [microsoft/vscode#145652]
When I write code, I want to set some files / folders to read-only mode, that is, non editable, especially the code of third-party libraries，how to do?

**Comment by yalezhangk** [comment]
Read only mode is added to some files or folders, for example, the third-party library is modified to read-only mode

**Comment by Lemmingh** [comment]
@yalezhangk

Could you clarify your idea? Looks like the issue description was changed again and again to almost different things. The latest one sounds like #4873
