### ISSUE TITLE
Test: Rename Side Panel

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#145634]
- [x] macOS @chrmarti
- [x] anyOS @misolori

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145634%0A%0A&assignees=sbatten)

---

When shipping the side panel, we deprecated the ability to move the bottom panel hoping to leverage view movement to solve most of the use cases. Unfortunately, this did not work as expected and instead we decided to keep the bottom panel movement. As part of this change in direction, we decided to rename the Side Panel to avoid the confusion of a side panel and a panel that moves to the left/right (to the side).

In the UX, we now refer to the 3 surfaces: Primary Side Bar, Secondary Side Bar, and Panel.

### Testing
Review the editor strings to ensure we have correct presentations of these new names:
1) Menu Bar > View > Appearance
2) Command Palette Commands
3) The Layout Control in the custom title bar (hovers)
4) Customize Layout command quick pick
5) Setting descriptions (we don't change setting titles for compatibility reasons)
6) Right click menus of parts (e.g. Hide Primary Side Bar)
7) Anything that comes to mind I might have overlooked. 

**Note** Under the hood, commands are using `AuxiliaryBar` as a clear distinction from the other to surfaces which allowed us to change names without ties to the command name.

**Comment by misolori** [comment]
> Under the hood, commands are using `AuxiliaryBar` as a clear distinction from the other to surfaces which allowed us to change names without ties to the command name.

Should this get updated at some point? i know one piece of debt that lingers is the renaming of areas that have been changed over time (like the simple checkbox example @TylerLeonhardt recently renamed)

**Comment by sbatten** [comment]
There is a separate debt item for cleanup of the code. I didn't mix this here because unlike the checkbox example, this has a direct impact on the users keybindings.
