### ISSUE TITLE
Looks like ipynb builtin extension build is broken in 1.65 in browser mode 

### ISSUE THREAD

**Issue by drykovanov** [microsoft/vscode#145689]
Does this issue occur when all extensions are disabled?: Yes (problem with builtin extension)

- VS Code Version: 1.65 (git release/1.65)
- OS Version: Any

Steps to Reproduce:

1. Check out ipynb/package.json and extension-browser.webpack.config.js:
package.json still expects "browser": "./dist/browser/ipynbMain.js",
but webpack builds to dist/ipynbMain.js

2. build with `node --max_old_space_size=4096 ./node_modules/gulp/bin/gulp.js vscode-reh-web-darwin`
3. check the content of resulting ipynb/

**Comment by drykovanov** [comment]
```
jupyter@b131103ecb50:/app/vscode-reh-web-linux-x64/extensions/ipynb$ pwd
/app/vscode-reh-web-linux-x64/extensions/ipynb
jupyter@b131103ecb50:/app/vscode-reh-web-linux-x64/extensions/ipynb$ ls -la
total 24
drwxr-xr-x 3 root root 4096 Mar 21 18:39 .
drwxr-xr-x 1 root root 4096 Mar 21 18:46 ..
-rw-r--r-- 1 root root  263 Mar 21 18:18 README.md
drwxr-xr-x 2 root root 4096 Mar 21 18:39 dist
-rw-r--r-- 1 root root 1056 Mar 21 18:18 package.json
-rw-r--r-- 1 root root  127 Mar 21 18:18 package.nls.json
jupyter@b131103ecb50:/app/vscode-reh-web-linux-x64/extensions/ipynb$ ls -la dist/
total 164
drwxr-xr-x 2 root root   4096 Mar 21 18:39 .
drwxr-xr-x 3 root root   4096 Mar 21 18:39 ..
-rw-r--r-- 1 root root 155657 Mar 21 18:38 ipynbMain.js
```

**Comment by drykovanov** [comment]
Probably I'm not building the right way?
```
node --max_old_space_size=4096 ./node_modules/gulp/bin/gulp.js vscode-reh-web-darwin
```

**Comment by connor4312** [comment]
Check out the "web" section of https://github.com/microsoft/vscode/wiki/How-to-Contribute
