### ISSUE TITLE
[javascript] Shebang should be highlighted as a line comment.

### ISSUE THREAD

**Issue by alexlur** [Microsoft/vscode#14560]
- VSCode Version: 1.6.1
- OS Version: OS X Sierra

**Steps to Reproduce:**

1. Switch language to JavaScript (or TypeScript)
2. Type shebang into the first line
3. Expect it *not* to be parsed with JavaScript grammar.

![image](https://cloud.githubusercontent.com/assets/8125011/19746156/183dc37e-9ba3-11e6-893c-28d7ca2fe1b4.png)

**Comment by waderyan** [comment]
Thank you for opening this issue. This issue is specific to the grammar in this repo https://github.com/Microsoft/TypeScript-TmLanguage. 

Opened this https://github.com/Microsoft/TypeScript-TmLanguage/issues/337

**Comment by alexlur** [comment]
Thanks!
