### ISSUE TITLE
Update Dark HC theme preview in walkthrough

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#145622]
![CleanShot 2022-03-21 at 14 31 32@2x](https://user-images.githubusercontent.com/35271042/159367337-79eca96d-3844-47a5-b9fa-4e35f594058c.png)

We never updated our Dark HC theme preview, which is currently using the monokai theme 😄  @daviddossett assigning to you since you recently updated these

**Comment by daviddossett** [comment]
Thanks for filing. Been meaning to replace this one too! Will take care of it 👍

**Comment by daviddossett** [comment]
Fixed in 8df9ddb994b115cf27b22116315baa0bc0c477d1

<img width="828" alt="CleanShot 2022-03-22 at 10 35 41@2x" src="https://user-images.githubusercontent.com/25163139/159541837-73054a85-ca4b-42dd-89d4-12fa3fde5336.png">
