### ISSUE TITLE
Internal error in FileExplorer on nested resources drop

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#145667]
Testing #145640

Enable file nesting. Enable operateAsGroup setting
1. Have folder `A`,  inside it have `test.ts` and `test.js`.
2. Have folder `B`, inside it have `test.ts` and `test.js`
3. Drop `test.ts` from `A` -> `B`
4. Internal error in FileExplorer 🐛

**Comment by JacksonKearl** [comment]
Wasn't able to repro that exact error but did make some changes to get things working smoother.
