### ISSUE TITLE
Test: Proposed `InputBoxMessageSeverity` API

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#145626]
Refs: https://github.com/microsoft/vscode/issues/144944

- [x] anyOS @isidorn
- [x] anyOS @rzhao271

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145626%0A%0A&assignees=TylerLeonhardt)

---

This milestone we introduced a new Proposed API that allows you to specify an Severity for the InputBox validation message APIs.

```ts
	export enum InputBoxValidationSeverity {
		Info = 1,
		Warning = 2,
		Error = 3
	}

	export interface InputBoxOptions {
		/**
		 * The validation message to display. This will become the new {@link InputBoxOptions#validateInput} upon finalization.
		 */
		validateInput2?(value: string): string | { content: string; severity: InputBoxValidationSeverity } | undefined | null |
			Thenable<string | { content: string; severity: InputBoxValidationSeverity } | undefined | null>;
	}

	export interface InputBox {
		/**
		 * The validation message to display. This will become the new {@link InputBox#validationMessage} upon finalization.
		 */
		validationMessage2: string | { content: string; severity: InputBoxValidationSeverity } | undefined;
	}
```

> NOTE: we have to use `2` because we are extending an OR type. When they are finalized, they will not be called `2` and will be folded into the existing API

Here's what it looks like:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/2644648/158004242-f882253a-2bca-473e-b0b8-750a3e231c8f.png">

Play around :)

### Useful stuff

* [Create an extension guide](https://code.visualstudio.com/api/get-started/your-first-extension)
* [Extensions samples repo](https://github.com/Microsoft/vscode-extension-samples)
* Add a proposed API:
  * First add the proposed API to the `package.json` (see below)
  * Then run `npx vscode-dts dev` to get the typings
```json
	"enabledApiProposals": [
		"inputBoxSeverity"
	],
```
> Note the name of the proposed API is gathered from the [file name in the vscode-dts folder](https://github.com/microsoft/vscode/tree/main/src/vscode-dts)

**Comment by isidorn** [comment]
Works great!
