### ISSUE TITLE
Test: LSP meta data model

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#145617]
Ref: https://github.com/microsoft/language-server-protocol/issues/67

- [x] anyOS @aeschli 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145617%0A%0A&assignees=dbaeumer)

---

I added a meta model for LSP to the protocol this milestone. Please review the following:

- the [meta model](https://github.com/microsoft/vscode-languageserver-node/blob/main/tools/src/metaModel.ts) itself Check if you think anything relevant is missing from the model.
- the [LSP meta data](https://github.com/microsoft/vscode-languageserver-node/blob/main/protocol/metaModel.json). Only do some sanity checking since the mode is huge.

**Comment by aeschli** [comment]
I directly fixed some typos in the doc comments: https://github.com/microsoft/vscode-languageserver-node/commit/2e55c6d56fbe25b0b66e9190e27f2c85e6319c0d
https://github.com/microsoft/vscode-languageserver-node/commit/6650db3b26f8641dbe19b53ec5b02cf2c3a41ee1


The meta model looks good. Very readable.

- The spec for `reference` should mention that this points to a custom type defined in  'structures` and `typeAliases` or 'enumerations`.
- The spec for `mixin` should explain what's the difference between `mixin` and `extends`
- For the `Map` type, can the `key` really be any `Type`?

**Comment by dbaeumer** [comment]
Very good feedback. Addressed all of them. 

For the Map key there is now a special definition

```ts
/**
 * Represents a type that can be used as a key in a
 * map type. If a reference type is used then the
 * type must either resolve to a `string` or `integer`
 * type. (e.g. `type ChangeAnnotationIdentifier === string`).
 */
export type MapKeyType = { kind: 'base'; name: 'Uri' | 'DocumentUri' | 'string' | 'integer' } | ReferenceType;
```
