### ISSUE TITLE
Selecting text with mouse stopped working

### ISSUE THREAD

**Issue by kuelumbus** [microsoft/vscode#145613]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.66.0-insider
Commit: eaa2b431ac259fddf5aa11aa53060a9b70068b29
Date: 2022-03-21T07:24:31.757Z
Electron: 17.1.2
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.10.101-14951-g87a0c73c8eec

I can't use the mouse to select text anymore. SHIFT + arrow down/up works, but left click + drag mouse doesn't work. Double click left mouse also works. 

https://user-images.githubusercontent.com/44866753/159348240-618a9248-791e-46f8-aed3-8286305bdbe7.mp4

**Comment by alexdima** [comment]
@kuelumbus What Linux distribution are you using? Are there any errors in the console (`Help > Toggle Developer Tools`)?

**Comment by kuelumbus** [comment]
Debian bullseye on Chrome OS. Yes, there are errors that probably help. 
![image](https://user-images.githubusercontent.com/44866753/159356908-30da1fb4-6bf9-4392-b54c-6c11ef5a604d.png)

**Comment by alexdima** [comment]
Thank you for the extra info. Let's track in #144584

**Comment by alexdima** [comment]
@kuelumbus Could you please verify that things are working using today's Insiders build?

**Comment by kuelumbus** [comment]
It is fixed for me. Thanks.
