### ISSUE TITLE
Test preferred high contrast light color theme

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#145616]
Ref: #144193

- [x] Windows @hediet
- [x] MacOS @paulacamargo25 
- [x] Linux @TylerLeonhardt 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145616%0A%0A&assignees=aeschli)

---

We already have a setting `workbench.preferredHighContrastColorTheme` that lets you specify a theme that is used when 'autoDetectHighContrast' is enabled and the OS enters high contrast mode.

Now we can distinguish between *high contrast dark* and *high contrast light* 

The existing setting `workbench.preferredHighContrastColorTheme` is now used as the preferred dark theme
The new setting `workbench.preferredHighContrastLightColorTheme` is used for the preferred light theme

Note currently only Windows and Mac support setting high contrast dark and light modes. Linux seems to support only a (single) high contrast mode

Test:

 - Makes sure that `window.autoDetectHighContrast` is true (that's the default)
 - Leave `workbench.preferredHighContrastColorTheme` and `workbench.preferredHighContrastLightColorTheme` as default 
 - Switch the OS high contrast mode and observe that VS Code updates the theme accordingly
    - On Windows
      - use `Use high contrast` in the `High Contrast` settings to enable high contrast mode
      - on the same settings page switch between `High Contrast White` and `High Contrast Black`
       
    - On the Mac use `Invert colours` in the Accessibility settings page to enable high contrast mode
      - use the 'Light' and 'Dark' mode on the General page 
    - On Linux (e.g. Ubunto) use the 'High Contrast` in the Accessibility settings page
       -  Ubuntu seems to only have High Contrast mode, no possibility of making it light or dark. For backward compatibility we always use the preferred HC dar theme.
- close VS Code, make an OS high contrast change and open VS Code. Observe that VS Code updates the theme accordingly
- Note that in order to switch light/dark in non-high contrast mode you also need to set `window.autoDetectColorScheme`
- Set different themes for `preferredHighContrastLightColorTheme` and `preferredHighContrastColorTheme` and test that they are used.

**Comment by daviddossett** [comment]
Should this setting also listen to the "Increase contrast" setting? 

<img width="194" alt="CleanShot 2022-03-22 at 10 20 45@2x" src="https://user-images.githubusercontent.com/25163139/159538787-f75434c8-c5eb-4c7c-b243-eff4ba324923.png">

**Comment by aeschli** [comment]
@daviddossett  You are correct, my last change modified the behaviour and `Increase contrast` is no longer used as an indicator for *high* contrast.

Discussions about this are in 
https://github.com/microsoft/vscode/issues/106704
https://github.com/microsoft/vscode/issues/107359

I can change this back, let me know what you think.

**Comment by aeschli** [comment]
I brought back the old behavior for the Mac: High contrast is set if either `Invert color` or `Increase contrast` is set (or both)

**Comment by daviddossett** [comment]
I was surprised to see pushback on rendering a HC theme when `Increase contrast` is enabled. That one makes sense to me.

As I tried this again, `Invert colors` was the one that took me by surprise since I realized it was flipping over to a dark theme (my OS was using a light mode) and then inverting it. I would have expected us to keep the same theme type.

**Comment by aeschli** [comment]
With 'invert colors': Yes I agree it's strange that we are in `dark` appearance but all is light. But it's the case for all applications. IMO it would be wrong to go to dark HC.
