### ISSUE TITLE
[themes] high contrast theme not switched to regular theme on startup

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#145698]
Testing #145616

Steps:
1) Set a color theme in VS Code (no high contrast) -> Works
2) Enable high contrast theme in OS (Windows) -> VS Code switches to high contrast theme
3) Restart VS Code -> VS Code stays in high contrast theme
4) Disable high contrast theme in OS -> VS Code stays in high contrast theme!

For step 4, I would have expected that VS Code would go back to the normal color theme.
When leaving out step 3, it does so.

**Comment by aeschli** [comment]
Yes, I know it's inconsistent, but it's something we do on purpose: Never switch away from a high contrast theme on restart. IMO it's time to remove that. @bpasero any objections?

**Comment by bpasero** [comment]
No, feel free to change.
