### ISSUE TITLE
Test: Command navigation improvements

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#145627]
Refs: #46561 #145241, #145240 

- [x] macOS @bpasero
- [x] linux @brettcannon
- [x] windows @misolori

Complexity: 3

Authors: @Tyriar, @meganrogge

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145627%0A%0A&assignees=Tyriar,meganrogge)

---

Command navigation in the terminal allows navigating between commands. Historically this has only been bound by default on mac but got new keybindings on Windows and Linux.

![image](https://user-images.githubusercontent.com/2193314/159374065-d1898f12-e022-4c98-b0ba-72db6df4c9bc.png)

Please test the following:

- Command navigation works as expected with cmd+up/down (mac) or ctrl+up/down (linux/windows). It should move the terminal's viewport to show the command in question about 25% down the viewport, of just highlight it if the command is already in the viewport.
- An outline shows briefly as expected when using command navigation.
- Ctrl/cmd+shift+up/down should select content from the previous anchor point
- Test the feature with shell integration enabled and disabled, both should work but results should be better when it's enabled.

**Comment by bpasero** [comment]
Pretty cool 👍

**Comment by bpasero** [comment]
@Tyriar is there an issue for accessibility already? It looks like when I test this with voice over on, I do not really get meaningful output.

**Comment by Tyriar** [comment]
@bpasero it works still, just a minor style issue https://github.com/microsoft/vscode/issues/145725
