### ISSUE TITLE
Integrated Terminal Cursor always is a block

### ISSUE THREAD

**Issue by dinhanhx** [microsoft/vscode#145643]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

Set Integrated Terminal Cursor to Line
Type something in the terminal
Cursor magically become a Block
![Video_2022-03-22_100442](https://user-images.githubusercontent.com/38489776/159400093-c0e99fa6-e7a9-4c94-8ffd-fce93205ca2f.gif)

**Comment by meganrogge** [comment]
it's working for me. try insider's and disabling your extensions

**Comment by dinhanhx** [comment]
@meganrogge 
> try insider's 
It works

> disable all extentions 
it doesn't show the cursor at all

**Comment by dinhanhx** [comment]
Sorry for bothering. It was Clink bugging with the Vscode.
