### ISSUE TITLE
One file nested multiple times leads to a weird experience

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#145671]
Testing #145640

Have `test.js`, `test.js.map` and `test.min.js`. Have the default fileNesting patterns in your user settings and the following in your workspace settings:

```
"explorer.fileNesting.patterns": {
		"bootstrap.js": "bootstrap-*.js",
		"*.js": "*.js.map"
	}
```

Notice how there is `test.js.map` is nested twice. So the user gets the wrong impression there are 4 files, when in fact there are 3 🐛 

![Screenshot 2022-03-22 at 12 00 32](https://user-images.githubusercontent.com/1926584/159467359-7c16fea4-b9d7-479f-942e-51387efe75de.png)

**Comment by JacksonKearl** [comment]
the config: `"*.js": "*.js.map",` is saying "every file ending in `.js.map` should be nested under every file ending in `.js`", which is what's happening here. You probably want "*.js": "$(capture).js.map",
