### ISSUE TITLE
Unable to get vscode to hit break point for Node.js 16.14.0 on macOS 12.2.1 if NODE_OPTIONS is set

### ISSUE THREAD

**Issue by aeroxy** [microsoft/vscode#145646]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: macOS 12.2.1

Steps to Reproduce:

1. create a breakpoint
2. run node.js script in debug mode with NODE_OPTIONS set (for example `NODE_OPTIONS=--max-old-space-size=8192 node index.js`)

**Comment by connor4312** [comment]
The debugger depends on setting the NODE_OPTIONS to enable debugging. If you want to change them, please append to the options instead of replacing them (e.g. with `NODE_OPTIONS="$NODE_OPTIONS --max-old-space-size=8192"`)
