### ISSUE TITLE
Test: terminal find / display all matches

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#145629]
Refs: #134790

- [x] macOS @sandy081
- [x] linux @gregvanl  
- [x] windows @Tyriar

Complexity: 3

Authors: @meganrogge

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23145629%0A%0A&assignees=meganrogge)

---

We want to align the terminal find experience with that of the editor, so this iteration, made use of the new Xterm `registerDecoration` API to do so.

Verify that the find experience in the terminal:
- feels nice
- looks good
- behaves similarly to the editor 
- shows scrollbar annotations in the right places and an indicator for the currently selected term that updates with `findNext` and `findPrevious`
- try setting `workbench.colorCustomizations.editor.findMatchBackground` and `workbench.colorCustomizations.editor.findMatchHighlightBackground` to custom colors. These should work on the next search
- try searching for something then adding lines to the buffer - the search results should be updated
- scrolling shouldn't impact anything
- closing the find widget (that still has input) should remove the decorations
- clearing the find widget should delete the decorations

Known issues:
- https://github.com/microsoft/vscode/issues/145630

**Comment by Tyriar** [comment]
Added myself as a tester despite doing a bit of the end work on it as I want to test it thoroughly anyway.
