### ISSUE TITLE
My code is bad...HELP !

### ISSUE THREAD

**Issue by ArtemIDD** [microsoft/vscode#145658]
Issue Type: <b>Feature Request</b>

What happened? help with code

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by ARTEMIGOREVITCH** [comment]
from pixellib.instance import instance_segmentation #ImportError: numpy.core.multiarray failed to import ,numpy.core.multiarray failed to import
  File "[C:\Users\User\Desktop\My]() Programming\object_detection_in_an_image\my.py", line 1, in <module>
    from pixellib.instance import instance_segmentation


def object_detection_on_an_image():
    segment_image = instance_segmentation()
    segment_image.load_model(r"C:\Users\User\Desktop\My Programming\object_detection_in_an_image\mask_rcnn_coco.h5")

    segment_image.segmentImage(
        image_path="istockphoto.jpg",
        output_image_name="output.jpg"
    )
        
    

def main():
    object_detection_on_an_image()

**Comment by IllusionMH** [comment]
/question

This is issue tracker for VS Code editor itself that is not suitable to general questions.
