### ISSUE TITLE
when there are many find matches, the overview ruler is not useful

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#145787]
Testing #145629

![Screen Shot 2022-03-22 at 3 24 17 PM](https://user-images.githubusercontent.com/29464607/159559688-e9af7858-7a39-4510-899a-f05bd37cdd0d.png)

**Comment by meganrogge** [comment]
when I search for ` ` in the editor area, the result is pretty similar
![Screen Shot 2022-03-22 at 3 42 02 PM](https://user-images.githubusercontent.com/29464607/159562614-c9fdaa05-25e2-429d-b8c8-cd9d981642dc.png)

**Comment by meganrogge** [comment]
maybe when there are matches on x % of the lines, we should only show a decoration if it's on that line y times or more?

**Comment by Tyriar** [comment]
I think it's fine and working as designed, it tells you there are a lot results just like in the editor when it's full. You can either refine the search or maximize the terminal.

**Comment by meganrogge** [comment]
Yeah it looks close enough to the editor
