### ISSUE TITLE
@lang autocomplete for list of languages would be nice

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#145718]
Testing #145588

Type `@lang:` in the settings editor. It would be nice if there was autocomplete for a list of languages.  This is a finite list which we should be able to suggest

fyi @sandy081 

![Screenshot 2022-03-22 at 15 08 10](https://user-images.githubusercontent.com/1926584/159500471-72e76c74-152b-40b0-85fe-d8aa3293c1ba.png)

**Comment by joyceerhl** [comment]
It's easier to discover language overrides in the settings.json editor because there is autocomplete there: 
![image](https://user-images.githubusercontent.com/30305945/159520197-4ca155a2-4c00-4631-a66d-9d1a6d712928.png)

**Comment by rzhao271** [comment]
Thanks to @sandy081 for pointing out the language service to me the other day. PR ready above.

**Comment by rchiodo** [comment]
/verified? 

The autocomplete works but no matter what I write there I get the same set of settings? I suppose all of these apply to all languages. 

![image](https://user-images.githubusercontent.com/19672699/159998839-78fce83b-2395-43bf-bcbd-51ecc5e50d77.png)
![image](https://user-images.githubusercontent.com/19672699/159998944-4345ad2c-4930-4d3e-b4dd-afc77bcdeb92.png)

**Comment by rzhao271** [comment]
Yep, the idea is for it to show all language-configurable settings. Then, the user can read and write settings for that language. I plan on making it so that the tab says which language you're on, for extra confirmation.
