### ISSUE TITLE
Clarifying questions about tabs API JSDoc

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#145738]
Testing #145585

- When would a `TabGroup` have an `undefined` `activeTab`--would this be when the tab group is empty?
- The docstring for `isActive` says this property is "Dictated by being the selected tab in the group", is there a difference between selected and active?
- Should pinned tabs be closable by the `close` API, and should that be called out in the JSDoc?
- The JSDoc for `onDidChangeActiveTabGroup` says "Whether it be which group is active." which I don't really understand

**Comment by lramos15** [comment]
> * When would a `TabGroup` have an `undefined` `activeTab`--would this be when the tab group is empty?

Yes

> * The docstring for `isActive` says this property is "Dictated by being the selected tab in the group", is there a difference between selected and active?

I don't believe there is a distinction no. I also try to avoid a word in the property in its description as I feel it is similar to when a dictionary uses a word in the description of the word it's defining

> * Should pinned tabs be closable by the `close` API, and should that be called out in the JSDoc?

It should be, if not I'll take a look as most likely is a bug. Closing in the API is explicit and therefore we only prevent it in the case of data loss which pinning isn't

> * The JSDoc for `onDidChangeActiveTabGroup` says "Whether it be which group is active." which I don't really understand

Sounds like a semantic error. Thank you I'll take a look.

**Comment by joyceerhl** [comment]
Yeah verified that pinned tabs can be closed with the `close` function (though `isPinned` is never `true` so not sure if addressing that will change this behavior)
