### ISSUE TITLE
The TypeScript language service died 5 times over the past 5 minutes

### ISSUE THREAD

**Issue by S3Stellar** [microsoft/vscode#145715]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Happens even by only keeping the visual studio open with my workspace (several projects in it), not running anything on terminal. everything slow down as well, autocomplete take ages

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900K (24 x 3187)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (24.90GB free)|
|Process Argv|--crash-reporter-id dffb8ffc-d1f1-4adf-954d-6f99b8cbbcca|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|13.3.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
workspace-terminal|igr|0.0.2
mongodb-vscode|mon|0.9.2
vscode-docker|ms-|1.21.0
remote-containers|ms-|0.224.3
vscode-typescript-next|ms-|4.7.20220320
LiveServer|rit|5.7.5
vscode-todo-highlight|way|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvid1:30447480
pynewfile477:30450038

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by S3Stellar** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Yeah it does, for the moment it seems like the only workaround is downgrading to:

**Version: 1.47.3 (user setup)**
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19044

On this version it seems like my  CPU is not dying (12900K), on the newer versions one of my CPU cores is constantly on 85-100%, which seems to be happening due to IntelliSense -> 
TypeScript and JavaScript Language Features  @builtin extension causes that, disabling it turn down cpu load to normal, but then I miss all the features of autocomplete/syntax check etc'.

**Comment by mjbvz** [comment]
Can you share a project which causes the issue?

**Comment by S3Stellar** [comment]
> Can you share a project which causes the issue?

Send me your email

**Comment by mjbvz** [comment]
Can you try putting together a minimal project first that can be shared publicly? That's much easier for us to investigate

**Comment by mjbvz** [comment]
Closing as we need logs or ideally a project which lets us easily reproduce the problem so we can fix it
