### ISSUE TITLE
Add API call to show Test Explorer output pane.

### ISSUE THREAD

**Issue by adam-fowler** [microsoft/vscode#145724]
Could we have an API call to show the Test Explorer output pane. Currently the user has to press the `Show Output` button at the top of the Test Explorer. Ideally I would like to be able to show this automatically as soon as the user requests a test run.

**Comment by connor4312** [comment]
You can use the `testing.showMostRecentOutput` command for this. Most things in the Command Palette are commands you can call from extensions.
