### ISSUE TITLE
+ button not appearing when hovering lines on linux

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#145733]
Testing #145574

OS: Fedora 34
VSCode:
```
Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T15:36:26.048Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.12-300.fc34.x86_64
```

Extension Info:
```
Name: GitHub Pull Requests and Issues
Id: GitHub.vscode-pull-request-github
Description: Pull Request and Issue Provider for GitHub
Version: 0.39.2022030911
Publisher: GitHub
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github
```

Recording: https://streamable.com/8zdbh3

**Comment by alexr00** [comment]
@deepak1556 I think this was around the time that we started seeing GitHub outage issues. I tested today on Ubuntu 18, and works well. Would you be able to try again?
![Recording 2022-03-23 at 10 46 18](https://user-images.githubusercontent.com/38270282/159670969-219977df-0800-47aa-a1a9-c10833b12d11.gif)

**Comment by deepak1556** [comment]
It still repros, the problem might be localized to my vm setup. Is there a particular layer or node I should check whether it receives mouse events ? I did confirm the workbench receives mouse events.
