### ISSUE TITLE
Reconsider $(basename) in file/search exclude

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#145753]
The `$(basename)` expansion gets removed from tooltips as part of codicon processing. In file nesting I got out of this by using a nonbreaking space between the `$` and `(` but it's a bit of a hack (need to strip nonbreaking spaces from the value in core in case people copy/paste). 
<img width="918" alt="image" src="https://user-images.githubusercontent.com/8586769/159530623-27ee1e8f-9e92-40f6-a64b-93171c385411.png">

<img width="711" alt="image" src="https://user-images.githubusercontent.com/8586769/159530720-15e52dfc-2bb4-46d2-9ad3-0b423218f355.png">

File nesting is moving over to `${...}` expansions, which are used heavily in core. Should excludes perhaps also adopt that style?

**Comment by JacksonKearl** [comment]
Not really sure who to cc since the code has been around since the [beginning of time](https://github.com/microsoft/vscode/blame/21d1c6249b900acf1e511f6b6d5c6022c787d51b/src/vs/base/common/glob.ts#L298)... @bpasero @roblourens ?

**Comment by bpasero** [comment]
@JacksonKearl just to clarify, you suggest to align the explorer file nesting syntax with our `basename` syntax in glob patterns? I don't think we can really change the syntax for glob patterns, it is a somewhat established pattern for many users and it would just ask for breakage. 

Maybe you could clarify the intent of this issue further.

**Comment by JacksonKearl** [comment]
Explorer file nesting is already moving over to use `${basename}/${extname}/${dirname}/etc.`. I think at minimum we should change the description text of the excludes to use `$\u200b(basename)` so it doesn't get swallowed by the codicon replacer. cc @aeschli

**Comment by bpasero** [comment]
Yeah that sounds good to me, I wasn't aware the hover was hiding those.

**Comment by aeschli** [comment]
Use `\\$(..)` to avoid an icon is rendered

**Comment by JacksonKearl** [comment]
@aeschli looks like it doesn't work in markdown sections: 
<img width="161" alt="image" src="https://user-images.githubusercontent.com/8586769/159715884-e838ee39-1f16-407d-8f41-caf23045c10a.png">
but the plaintext rendering works well enough for my use case.
