### ISSUE TITLE
`onDidChangeTab` fires twice when dirty state changes

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#145762]
Testing #145585

1. Have two editor groups
2. Modify the active file in one of the groups
3. Hit save to mark editor not dirty
4. :bug: two `onDidChangeTab` events are fired

**Comment by joyceerhl** [comment]
Also, should `onDidChangeTab` fire when a tab group closes? Right now it doesn't, but the other two events do fire

**Comment by lramos15** [comment]
> 4\. 🐛 two `onDidChangeTab` events are fired

Two events when you hit save? You should get one for when you make the edit because the tab becomes dirty and then one when you hit save because the tab is no longer dirty.



> Also, should `onDidChangeTab` fire when a tab group closes? Right now it doesn't, but the other two events do fire

Probably not since we don't have any tab to return to you as it is gone

**Comment by joyceerhl** [comment]
I only see one event fired now on save, and `isDirty` is correctly updated, thus closing.
