### ISSUE TITLE
No number shows how many files are found after searching

### ISSUE THREAD

**Issue by jsntcy** [Microsoft/vscode#14575]
- VSCode Version: 1.6.1
- OS Version: Win 10

Steps to Reproduce:

1.  Search specified string in a folder,
2.  Return some results, but there is no number showing how many files are found after searching.

**Comment by sandy081** [comment]
Duplicates #6669

**Comment by fascox** [comment]
IMHO this is not a duplicate. The poster ask for **number of files** match the criteria not how many occurrences in the files.

**Comment by sandy081** [comment]
@fascox #6669 also talks about number of files. Hence made it a dup.

**Comment by fascox** [comment]
sorry but talk not implies the same feature request... should be re-opened as a NEW feature

**Comment by sandy081** [comment]
@fascox Updated the summary of the other one to include both matches count and files count. Since they are very much related, I think one feature request is good enough.

Thanks.

**Comment by fascox** [comment]
thanks, awesome.
