### ISSUE TITLE
launch.json ignored (sometimes)

### ISSUE THREAD

**Issue by joem5636** [microsoft/vscode#145750]
Issue Type: <b>Bug</b>

If I start using F5 or Run/Start with Debugging, my "args" are 'seen' but if I start using the control on the right of the screen, they are ignored!!!!!

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.13.0-35-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II N620 Dual-Core Processor (2 x 2800)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|5.48GB (0.27GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 8a952d56-41f5-4f03-a063-103fba8f9dfd|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.10.0
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
vscode-pull-request-github|Git|0.38.1
vsc-python-indent|Kev|1.14.2
vscode-github|Kni|0.30.7
python|ms-|2021.12.1559732655
jupyter|ms-|2022.2.1030672458
autodocstring|njp|0.6.1
intellicode-api-usage-examples|Vis|0.0.10
vscodeintellicode|Vis|1.2.17
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvidc:30447482
cppdebug:30451566
pynewfile477cf:30450039

```

</details>

**Comment by joem5636** [comment]
If I start using F5 or Run/Start with Debugging, my "args" are 'seen' but if I start using the control on the right of the screen, they are ignored!!!!!  Nothing to do with restarting VSCode. Seems really lame to me!

**Comment by weinand** [comment]
@joem5636 I assume with "control on the right" you mean the editor's "Run/Debug" button:

![CleanShot 2022-03-22 at 22 43 32@2x](https://user-images.githubusercontent.com/1898161/159581364-bf122854-f632-4ed0-952d-74de399d25e2.png)

If yes, then the behavior you are seeing is expected:
- the editor's "Run/Debug" button launches the contents of the current active editor. Since no launch/debug configuration is used for this, you cannot specify any arguments or other options.
- F5 launches the currently selected launch/debug configuration which makes it possible to specify arguments and all kinds of options.

**Comment by joem5636** [comment]
Yes -- how about two more options for that control to use the
configuration. Also, the control on the Run view really ought to trigger
the configuration since you just selected it!

Joe
