### ISSUE TITLE
Local History - some entries do not have a timestamp

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#145726]
Testing #145461

![image](https://user-images.githubusercontent.com/3372902/159511836-8981fac7-e8d7-47b0-9292-09be1a7c8b67.png)

Hovering over the item will show the timestamp.
Hitting the "Refresh" button in the Timeline view does not resolve it.

Reloaded the window and now I have two entries without a timestamp:
![image](https://user-images.githubusercontent.com/3372902/159512281-14299210-2a57-40d7-a790-661a163281e5.png)

**Comment by IllusionMH** [comment]
Looks like this is "deduplication" feature of timeline, where same relative time representations are skipped to minimize noise (screenshot below).
Most likely 9 min case is just result of "rounding" in that moment.
![image](https://user-images.githubusercontent.com/1312662/159528345-09611457-0939-4169-a10e-d00b988c5d50.png)


Or am I missing something?

**Comment by bpasero** [comment]
Yup, works really well 👍

**Comment by daviddossett** [comment]
The idea here was to not show the full timestamp in the list. It does show in the editor tab title when clicked, however.

**Comment by connor4312** [comment]
It seems strange that we still show the time on hover, though -- should it be hidden all the time?

**Comment by daviddossett** [comment]
I thought it felt like a useful compromise in case someone doesn't want to open the diff but still wants more detailed info. Did it feel in the way or annoying when you first used it?

**Comment by connor4312** [comment]
The tooltip already shows the full date, which is probably fine for those looking for details

![image](https://user-images.githubusercontent.com/2230985/159590800-5aa3f2fe-9caf-47d6-99a8-c37fb5242cdf.png)

It felt more like a bug when I first used it, I didn't understand why some dates were always visible but some were hidden until I hovered.

**Comment by bpasero** [comment]
Can you show a gif of what you mean? I wonder if that is intentional or a bug in core timeline.
