### ISSUE TITLE
Some local history diffs show the same contents side by side

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#145706]
Testing #145461

1. Open a file with a class
2. Refactor the class name to something different
3. Save
4. 🤷 The diff in the local history shows no changes 

I noticed that the diff always appears against the current file. I'm wondering in the event of a save for example if it should be before and after the save that the diff is against. I'm more interested in how that history event changed the file but it's really a culmination of all history events making only the most recent entry helpful. Sometimes even that doesn't show changes as noted above.

**Comment by IllusionMH** [comment]
See related response https://github.com/microsoft/vscode/issues/145160#issuecomment-1069390398
Context menu provides a way to check "change/save diff"

**Comment by lramos15** [comment]
Thanks @IllusionMH I guess that addresses my statement at the bottom. Maybe a setting to change the default behavior would be nice to match git like you said but I'll leave that up to @bpasero. The initial issue of some diffs showing no changes in the case of a refactor still stands though so I'll leave this open

**Comment by bpasero** [comment]
My feeling is that a diff from one local history event to another is really not helpful because there is really little semantic meaning to most local history entries. Local history is also not like git changes that are logically group under a name.

As the comment outlines, I followed what other IDEs seem to do. I would suggest to wait for real user feedback before making a change here.

**Comment by lramos15** [comment]
👍  I'll leave it up to you if you want to close this issue or use it for tracking others that come in. The bug described above I think was as-designed as well and just a dupe of https://github.com/microsoft/vscode/issues/145714

**Comment by connor4312** [comment]
Titling the change based off the diff changes that were might might be useful such as "Changed 4 lines, deleted 2"

**Comment by bpasero** [comment]
> Titling the change based off the diff changes that were might might be useful such as "Changed 4 lines, deleted 2"

I am not sure how useful that kind of information really is. How can you use that information later to find the right entry?

Leaving this issue open for until we have shipped this feature to stable to see if more users react to it. From my testing:
* Eclipse behaves like we do now
* IntelliJ seems to hide local history entries that are identical to the saved version but I am not sure I like that

**Comment by tommai78101** [comment]
What determines when to create a new local history entry when editing a document multiple times throughout a single day?

On every hour? If the local history is older than 1 hour, it creates a new local history?
On every day? If the local history is older than 1 day, it creates a new local history?

Would like to know more on this feature.

**Comment by IllusionMH** [comment]
Check VS Code release notes https://code.visualstudio.com/updates/v1_66#_local-history and also pay attention to settings to see when/how they are applied

**Comment by tommai78101** [comment]
Oh, that's what `mergeWindow` means. When I read that setting, I was confused on what it means. But now, after playing around with the Local History, I didn't think of re-reading the release notes. I now understood what the settings do.

Another question about "File Saved" and "File Created":

* When File Created local history is opened, it shows the entire content of the file, meaning every line is considered to be a change.
* When File Saved local history is opened, it shows the differences between the adjacent File Saved local history entries.

The release notes didn't really explain about categorizations (File Saved, File Created, File Restored, etc.) and the differences in how the changes are displayed when they are opened. Where can I find more information about how document changes are shown to the user?

**Comment by tommai78101** [comment]
May I ask if there could be a label "(current)" added to the label at the top?

editorPanes.ts (File Saved - April 1, 2022, 12:01 PM) <-> editorPanes.ts (current) ...

**Comment by tommai78101** [comment]
Understood.
