### ISSUE TITLE
Not being prompted to update vscode-go on Windows

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14574]
Shows .43 which is not the latest, with no update button.
![image](https://cloud.githubusercontent.com/assets/323878/19756009/9956847a-9bce-11e6-91dc-ab6c09d6a99b.png)

Searching for it, it thinks I don't have it installed.
![image](https://cloud.githubusercontent.com/assets/323878/19756024/b133f640-9bce-11e6-87ed-7233bc86b347.png)

And after installing it, it looks correct in the extensions UI, but I have both versions in my .vscode/extensions folder.

**Comment by joaomoreno** [comment]
What are the contents of the locally installed extension's `package.json`?

**Comment by roblourens** [comment]
On second thought, I think that original one was installed from a vsix, as it has `__metadata: null`. Sorry it was awhile ago.
