### ISSUE TITLE
Indicate if setting has a language-specific value

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#145731]
Testing #145588

Introduce an indicator when a setting has language specific value when viewing that setting in non-language specific scope. 

For example

1. Filter to `@lang:css`
2. Change a setting
3. Remove filter
4. Search for that setting
5. There's no indication that the setting's value has changed for the current scope ('User') and also there is a language overriding this value.

![image](https://user-images.githubusercontent.com/30305945/159518287-9a0fb3db-472e-4d82-9345-6369b7a7c68d.png)

Also same if the setting has a different value for other languages contributed in defaults

**Comment by rzhao271** [comment]
The lack of a modified filter is intentional, but imo there should at least be text saying that the setting has been overridden for some languages.
Adding to next milestone.

**Comment by sandy081** [comment]
@rzhao271 and myself discussed on this and decided to introduce some minimal UI when the setting has language specific values when shown in non-language specific scope. UI includes text as follows:

`Other languages have overridden this setting`.

**languages** shall be rendered as link, clicking on it shows the list of languages overriding the setting. Selecting the language shall apply language and setting filter in the search box.

**Comment by heartacker** [comment]
hi all, I think that will be great to show the language-specific value-item if there are. 
![image](https://user-images.githubusercontent.com/1876302/173720486-b28db62f-748c-43c0-84cb-a18e640dfaa4.png)
