### ISSUE TITLE
cannot transfer custom data on drag-and-drop 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#145757]
Testing #145635

I've tried to add "custom data" to the data transfer of the "tree-view-sample" with this change in the "handleDrag()" method:  

<img width="1123" alt="CleanShot 2022-03-22 at 18 44 41@2x" src="https://user-images.githubusercontent.com/1898161/159543048-d2570010-aa1c-4695-9451-d62c7aea06a9.png">

But this did not arrive in my `onWillDropOnTextEditor` handler: 

```ts
	vscode.workspace.onWillDropOnTextEditor(e => {

		e.token.onCancellationRequested(x => {
			console.log(`cancel: ${e.token.isCancellationRequested}`);
		});

		console.log(`dest name: ${e.editor.document.fileName}`);
		console.log(`dest position: ${e.position}`);

		e.dataTransfer.forEach(async (v, k) => {
			console.log(`datatransfer: ${k}: ${await v.asString()}`);
		})

	});

```

which produced this output:

<img width="961" alt="CleanShot 2022-03-22 at 18 50 47@2x" src="https://user-images.githubusercontent.com/1898161/159544154-f10c05d2-5851-452f-85c4-787fcd5febba.png">

I tried other custom data and other mime types, but nothing worked. 

Most likely I'm not doing the right thing...

**Comment by mjbvz** [comment]
I believe this works as expected now. To test:

1. Build and install the tree view sample: https://github.com/microsoft/vscode-extension-samples/tree/main/tree-view-sample

1. Run the drop sample from sources: https://github.com/microsoft/vscode-extension-samples/tree/main/drop-on-document

1. Try dragging from the new tree view (`test view drag and drop`) into a plain text editor. Confirm it inserts a uri

1. Now try reading the custom data that the tree view sets

```
const a = await dataTransfer.get('application/vnd.code.tree.testviewdraganddrop')?.asString();
```

This should be something like: 

```
'{"id":"testViewDragAndDrop","itemHandles":["1[/ab]()"]}'
```

**Comment by rchiodo** [comment]
/verified

Thanks for the excellent verification steps.
