### ISSUE TITLE
Find match results are too dim

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#145742]
Testing #145629

Opacity is being applied to the overview ruler:
![image](https://user-images.githubusercontent.com/2193314/159532849-3a03be0d-45c2-4761-9484-8fe54e06c2f6.png)

This also makes overlapping results not look good:
![image](https://user-images.githubusercontent.com/2193314/159532876-0414943b-b9c4-48b8-9e03-8061a8664246.png)

**Comment by meganrogge** [comment]
I can't find where opacity is getting applied

**Comment by Tyriar** [comment]
Oh also that method would only get customizations in settings, not themes.

**Comment by rebornix** [comment]
It looks great with overlap 

<img width="652" alt="image" src="https://user-images.githubusercontent.com/876920/159986206-4bd99197-5e1a-4779-9b26-cf0188447f8a.png">
