### ISSUE TITLE
Language specific default overrides not marked in settings UI

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#145719]
Testing #145588

1. Settings UI, open Workspace tab
2. Search for `@lang:markdown wordwrap`
3. Notice how the `wordwrap` appears as not changed (no blue line) -> 🐛 

`wordwrap` should be rendered as modified since none of my workspace settings actually change the word wrap value, and the markdown default value should take precedence here.

fyi @sandy081 

![Screenshot 2022-03-22 at 15 09 39](https://user-images.githubusercontent.com/1926584/159500813-3228e753-4159-420b-9dd2-e6f9cbd7548c.png)

**Comment by rzhao271** [comment]
If the default value has been overridden by the markdown language/extension, there should be a badge, or some text. That part is a bug.
I'm not sure about showing a blue line, though, because to me that means the workspace-scope setting value has been manually configured.

**Comment by rzhao271** [comment]
Tracking in https://github.com/microsoft/vscode/issues/148672. We already have default override indicators for when an extension contributes a non-language-specific setting default value override, but we currently don't have them for extension-contributed language-specific setting default value overrides.
