### ISSUE TITLE
Debug Console

### ISSUE THREAD

**Issue by davidvehn** [microsoft/vscode#145780]
My name is David and I'm trying to run a Flutter app on Visual Studio Code, but when I was trying to run it with the debugging tool, it wasn't displaying the output of the codes. The DEBUG COSOLE was displaying potential errors. 

I was wondering whether you can help me fix the issue. I've attached a link to the picture down below this email. 

Thanks and I look forward to hearing from you!

Best,
David Emereonye
Email: DavidVehn@gmail.com 

![Debug Console](https://user-images.githubusercontent.com/102182429/159554587-ca9897ac-6d8e-4c0d-a9b7-346e894254be.png)

**Comment by weinand** [comment]
@davidvehn sorry, but we cannot help you fixing the problems in your programs.
