### ISSUE TITLE
Scroll bar annotation doesn't adjust when changing settings 

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#145760]
Testing #145599

1. Customize the colours
2. Run a few commands to add some annotations in the scroll bar
3. Customize the colours again
4. :bug: The left side colours update, but not the right side ones.

In the following screenshot, I only updated the error colour, by changing it from magenta to red:

![Screenshot showing only one side of annotations updated](https://user-images.githubusercontent.com/7199958/159546461-01b78590-2d38-4bd7-908a-ba75990ad49a.PNG)

**Comment by meganrogge** [comment]
This is because we only allow passing in the find decoration colors to the `findNext` and `findPrevious` calls. One way to work around this would be to provide the colors instead as `TerminalOptions`

**Comment by Tyriar** [comment]
Seems like we should be able to fix this by tracking the old colors via IThemeService and calling incremental find when they change

**Comment by Tyriar** [comment]
Too risky for this late in endgame. I think the right fix here is for a new API in the search addon to update the theme colors, I tried an approach by listening to the theme service and researching but it felt hacky and inefficient.

**Comment by Tyriar** [comment]
This works now
