### ISSUE TITLE
command 'shellCommand.execute' not found

### ISSUE THREAD

**Issue by fraxx001** [microsoft/vscode#145735]
Issue Type: <b>Bug</b>

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.4.0-104-generic
Restricted Mode: No

Steps to Reproduce:

1. Run shell task from tasks.json

Hi since I updated VSCode to the latest version, I am unable to run any kind of shell task from the specified in tasks.json 
I always get:

`command 'shellCommand.execute' not found`

The Log(Window) output shows:
`[2022-03-22 16:50:30.259] [renderer5] [error] command 'shellCommand.execute' not found: Error: command 'shellCommand.execute' not found
    at b._tryExecuteCommand (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1504:3532)
    at b.executeCommand (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1504:3414)
    at async i.resolveWithInputAndCommands (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1922:24779)
`
I am not sure i this is a config issue on my side but it works before the update.

**Comment by jamietre** [comment]
@fraxx001 what was the problem? This just started happening to me this morning for no apparent reason!

**Comment by fraxx001** [comment]
The extension `augustocdias.tasks-shell-input` was missing.
I had the issue in in an devcontainer where the tasks.json was updated together with the devcontainer.json but the rebuild of the devcontainer did not installed the extension although it was specified. I had to install the extension manually or rebuild the devcontainer without cache.

**Comment by jamietre** [comment]
Ha - yeah i just figured that out too ;) Thanks.
