### ISSUE TITLE
Insiders regression: vscode.WorkspaceConfiguration.get<string> on an enum no longer returns "non-enum" strings

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#145772]
Does this issue occur when all extensions are disabled?: Yes -- however, repro involves an extension.

- VS Code Version: 1.66.0 (1.65.2 non-Insiders doesn't repro the bug)
- OS Version: Windows.

Steps to Reproduce:

1. Use the C/C++ extension or some other extension that has an enum string setting.
2. Set the C_Cpp.loggingLevel setting to "7" or set an enum string setting to a value that doesn't match one of the enum values.

Bug: The `vscode.WorkspaceConfiguration.get<string>` call returns "Debug" (the last enum) instead of "7". Our extension considers this a breaking change because we intentionally want "7" to be usable as a hidden value that users shouldn't normally use unless they specifically set the string to that value (they'll get a warning in the settings.json about it not matching a valid enum value).

Is this a "by design" change with Insiders? If so, what is the recommended fix for extensions who relied on the previous behavior?

Our relevant code is at
https://github.com/microsoft/vscode-cpptools/blob/main/Extension/package.json#L2137
https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/LanguageServer/settings.ts#L205

The bug report at https://github.com/microsoft/vscode-cpptools/issues/9066 shows a user using our hidden "7" value to get important logging info for us.

**Comment by sandy081** [comment]
@sean-mcmanus This seems to work for me. Here is my sample extension


<details>
<summary>Extension</summary>
```json
"configuration":{
			"title": "test settings",
			"properties": {
				"test.setting": {
					"type": "string",
					"enum": [
						"None",
						"Error",
						"Warning",
						"Information",
						"Debug"
					],
					"default": "Error",
					"scope": "window"
				}
			}
		}
```
```ts
export async function activate(context: vscode.ExtensionContext) {
    vscode.commands.registerCommand('test.helloWorld', () => {
        console.log(vscode.workspace.getConfiguration().get('test.setting'));
    });
}
```
</details>

On running the command I see following output

<img width="741" alt="image" src="https://user-images.githubusercontent.com/10746682/159767510-d555cd50-a525-48f9-8443-3289541e9e68.png">

**Comment by sean-mcmanus** [comment]
It's no longer reproing with today's VS Code Insiders. Seems to me like it was fixed.
