### ISSUE TITLE
`workbench.localHistory.exclude` doesn't work well

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#145720]
Testing #145461
1. Add `workbench.localHistory.exclude: {"*": true}` to your settings.json
2. :bug: Notice settings.json still shows local history changes
3. :bug: Notice notebooks still show local history changes

**Comment by bpasero** [comment]
https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options

**Comment by lramos15** [comment]
Sorry if I'm still a bit confused. How would I go about including settings.json from showing the history? The linked doc says some files are excluded by default for search but this is local history and these are being _included_ not excluded.

**Comment by bpasero** [comment]
I do not understand the question but my comment was trying to help out how glob patterns work. `*` matches on a name without path and will never match an absolute path that is on disk. Only `**` matches everything.
