### ISSUE TITLE
Tabs API `isPreview` and `isPinned` do not work

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145734]
Testing #145585

I have only the welcome tab opened:

And it reports as `isPreview: true` even though it is not in preview.

Same actually for pinned state, the state is not updating when I change it. To clarify: I print the state from a `onDidChangeTab` event handler.

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/159525061-5aa288da-af56-4970-ba5b-5ae2fddc06d9.png)

This is mystery to me. Could it be that pinned and preview is mixed?

**Comment by JacksonKearl** [comment]
Settings editor also reports as `isPreview: true` always.
