### ISSUE TITLE
Deb and Rpm file launcher executes "Exec=/usr/share/code/code --unity-launch %F" , Unity launcher no longer used by Ubuntu

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#145798]
Does this issue occur when all extensions are disabled?: Yes

Deb and Rpm file launcher executes "Exec=/usr/share/code/code --unity-launch %F"

The launcher for the deb and rpm installs runs  "Exec=/usr/share/code/code --unity-launch %F" , I assume this has something to do with the fact old versions of Ubuntu used the "Unity" launcher , the unity launcher is now retired I assume this flag no longer does what it is intended.

- VS Code Version: 1.64.2 (all from what I have tested)
- OS Version: Ubuntu 20.04 (also all from what I have tested)

Steps to Reproduce:

1. Download any deb or rpm package
2. Look at laucher (code.desktop)

**Comment by Tyriar** [comment]
I think this was for supporting shift+click on the unity dock to open a new window, we may be able to switch this to use --new-window but it would need testing. Also yes it's a bit weird that it says unity now but it doesn't do any harm.

**Comment by andrewpacific** [comment]
> I think this was for supporting shift+click on the unity dock to open a new window, we may be able to switch this to use --new-window but it would need testing. Also yes it's a bit weird that it says unity now but it doesn't do any harm.

That would be cool , it would be reassuring to know it's not a mistake and the launcher is working as intended. I can build texts from source if wanted.

**Comment by deepak1556** [comment]
Steps for verification when changing args, https://github.com/microsoft/vscode/issues/21133#issuecomment-282107689

**Comment by rzhao271** [comment]
Merging into #212125
