### ISSUE TITLE
use ctrl+P open a file, and do this action again, the older file was colsed

### ISSUE THREAD

**Issue by cainiaoDJ** [Microsoft/vscode#14570]
- VSCode Version:1.6.1
- OS Version:win7

Steps to Reproduce:

step1. use ctrl+P open a file,named A
step2. use ctrl+P open a file,named B
step3. now you can see A was closed.  We found that the tab page is italicized. 

In the sublime to do this operation, there is no such problem

**Comment by bpasero** [comment]
You can set `"workbench.editor.enablePreviewFromQuickOpen": false` to control this.
