### ISSUE TITLE
find result decorations jump on scroll

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#145789]
Testing #145629

https://user-images.githubusercontent.com/29464607/159562079-54c2de33-24dc-4e1c-867d-54aa02086e5b.mov

**Comment by Tyriar** [comment]
I can't reproduce for here, you might be seeing skipped frames because it's taking too long to update in which case this would be as expected unless we can speed it up?

**Comment by meganrogge** [comment]
We will want to try to use the renderer's animation frame if it's available
