### ISSUE TITLE
improve decoration rendering efficiency

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#145751]
Testing #145629

Could repro this slowness by filling the buffer and then searching for a single letter, this is on a 12th gen i7 (fast modern CPU):

![image](https://user-images.githubusercontent.com/2193314/159537006-1d816cc3-e42f-45b1-a3b4-5a6f1f74126d.png)

A similar thing happens when pressing enter in this state since we don't do any diffing, just clear and re-render.

Ideas to explore:

- Move from rendering each decoration to calculating colored zones which merge similar rectangles into the same zone and render them
- If the buffer is full, explore shifting the texture up depending on how much scrolling occurs (might be tricky to get right)

**Comment by meganrogge** [comment]
@connor4312 that is by design - we don't show the count or decorations beyond 1000 results

**Comment by meganrogge** [comment]
you'll need to set workbench color customizations to see the results highlighted. 

here are some examples:

```
        "terminal.findMatchBorder": "#ce1a1a",
        "terminal.findMatchHighlightBorder": "#00ffbf",
        "terminalOverviewRuler.findMatchForeground": "#00c8ff",
```

**Comment by connor4312** [comment]
Got it. With 900 results I'm still seeing a pretty decent delay on my macbook, which looks similar to the original problematic one Daniel posted

![image](https://user-images.githubusercontent.com/2230985/166069474-239ae063-dbad-4264-a9ad-d8a67a330304.png)
