### ISSUE TITLE
Some situations result in rendering glitches

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#145764]
Testing #145599

Scenario 1:
1. Create a new extension that uses yarn.
2. Run `yarn watch`. It will clear the terminal in between.
3. :bug: The annotations still show up.

![yarn watch clears the terminal but the annotations remain](https://user-images.githubusercontent.com/7199958/159548169-a65eb02b-4fc3-4342-aa2c-8fbf77b87c22.PNG)

Scenario 2:
1. Run just `git commit`. Vim should open up.
2. Immediately leave by typing `:q!<enter>`. The commit should fail.
3. :bug: The annotations are slightly messed up afterwards.

![An aborted commit results in misaligned annotations](https://user-images.githubusercontent.com/7199958/159548419-64539902-cba2-4991-b2fb-9b33d397bb8f.PNG)

**Comment by meganrogge** [comment]
Wondering if there's a way to know a program like vim has been entered so we can hide the decorations. It looks a little broken when they still show up

**Comment by meganrogge** [comment]
this is in the works https://github.com/microsoft/terminal/commit/13fb1f58d0b7e4c0865c34d05c3527a1eced6257

**Comment by Tyriar** [comment]
Verifier: I have a fix out in #148973. Note that scenario 1 (tsc watch) above is fixed, I don't think we should fix scenario 2 (git commit), see https://github.com/microsoft/vscode/pull/148973#issue-1228447243.
