### ISSUE TITLE
Find is sometimes not highlighting all matches

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#145740]
Testing #145629

The current selection/overview ruler is working but not all matches

![image](https://user-images.githubusercontent.com/2193314/159532503-1fe6df96-f80b-4fd3-972a-08886a729876.png)
![image](https://user-images.githubusercontent.com/2193314/159532519-9ea81be1-4474-4142-a3b7-fed487e2d4ca.png)

It works sometimes though:
![image](https://user-images.githubusercontent.com/2193314/159532564-41bfee9c-f71c-43fd-935b-83dca6beb130.png)

**Comment by meganrogge** [comment]
trying to find a repro of this. I've seen it a few times

**Comment by meganrogge** [comment]
Will be fixed the next time we update xterm.js

**Comment by rzhao271** [comment]
Has this issue been fixed in VS Code? The find highlights seem a bit off to me:

![Screenshot showing the find highlights seem unaligned with the text](https://user-images.githubusercontent.com/7199958/159986790-f712d75c-10e6-4c1f-94b0-9a09f1044ade.PNG)
