### ISSUE TITLE
Differences or equalities with `resourceurls` and `text/uri-list`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#145713]
Testing #145577

I have just realised that we ended up mentioning/supporting [text/uri-list](https://github.com/microsoft/vscode/blob/945019764567961d65eb9ecb302f62a32c1836a0/src/vscode-dts/vscode.d.ts#L9845) and [resourceurls](https://github.com/microsoft/vscode/blob/945019764567961d65eb9ecb302f62a32c1836a0/src/vscode-dts/vscode.d.ts#L9794). One is for reading/dropping and one writing/dragging. Both types accept a list of stringified uris and I wonder if there is actually any difference apart from the names and if we should treat/recommend them equally?

**Comment by alexr00** [comment]
The docs should say `text/uri-list`, so I will update that. `resourceurls` is another internal type that existed long before tree dnd.

I will also add it to the exclude list in tree dnd land so that it doesn't get logged or passed to the extension.

fyi @mjbvz that I'm updating the docs to remove reference to `resourceurls`.

**Comment by alexr00** [comment]
The two types do have a different format: `text/uri-list` is not JSON, and `resourceurls` is.

**Comment by mjbvz** [comment]
Thanks @alexr00! Didn't know about `text/uri-list`. Will look into adopting that for drop into editor and also make sure we filter out some of the other internal types

**Comment by mjbvz** [comment]
@alexr00 When dropping into an editor, I am now using `extractEditorsDropData` to get a list of resources and then exposing those through the `text/uri-list` mime type

Let me know if this may be a problem. I was trying to align with the tree drag and drop api and also think it makes sense to expose dropped resources to extensions in a consistent way

**Comment by jrieken** [comment]
@alexr00 When dragging a file from the editor or an editor I still see `resourceurls` and no `text/uri-list`. I was expecting those to arrive only or also as `text/uri-list`?

**Comment by alexr00** [comment]
With the latest change, you will no longer see `resourceurls` in the log or in `handleDrop` and you should see `text/uri-list` in both places when appropriate.

**Comment by jrieken** [comment]
verified but I found that `text/uri-list` doesn't make it to the extension host https://github.com/microsoft/vscode/issues/146031
