### ISSUE TITLE
Tab objects for terminals created in editor area have bogus values

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#145778]
Testing #145585

1. Execute the Create Terminal in Editor Area command
2. `onDidChangeActiveTabGroup` fires 
3. :bug: `activeTab` is undefined, tab object has `isActive: false`, `isPreview: true`, `kind: undefined`, `label: ''`

**Comment by joyceerhl** [comment]
Oh, seems like the above is after the editor group is created but before the tab is created? After `onDidChangeTab` fires, `group.activeTab` is correct and `isActive: true`. However, the following are still dubious `isPreview: true`, `kind: undefined`, `label: ''`.

**Comment by lramos15** [comment]
@joyceerhl `onDidChangeTab` should fire 5 times here actually (the terminal is actively resolving its label this is a noisy event) and have a  proper label. The other two values being incorrect are https://github.com/microsoft/vscode/issues/145755  and https://github.com/microsoft/vscode/issues/145680#issuecomment-1075371920

**Comment by joyceerhl** [comment]
Ah I didn't wait for all the events to fire. The properties are expected and the label is now correctly set. Though, now I see `onDidChangeTab` fire 9 times in total.
