### ISSUE TITLE
Can't evaluate when not at a breakpoint

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14571]
![oct-26-2016 21-12-47](https://cloud.githubusercontent.com/assets/323878/19754324/2c42fce0-9bc1-11e6-9ea4-d0725f46a976.gif)
With any debug adapter

**Comment by isidorn** [comment]
Awesome catch! After the debug model restructuring I was missing the concept of evaluation without a stack frame. Now introduced that. To verify:
* Make sure all watch expressions are nicely evaluated based on the focused stack frame
* Make sure the repl can always be evaluted - including complex objects and their deep expansion
* Make sure the hover get nicely evaluated if your debug session has `supportsEvaluateForHovers`

There is currently a limitation that all watch expressions get cleared when the session is in running mode - however that is a limitation which I will fix in november
