### ISSUE TITLE
TestItem tags array is empty when passed to command triggered by additional menu item

### ISSUE THREAD

**Issue by KaravolisL** [microsoft/vscode#145777]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:
I have an extension that is creating a TestController object and creating a few TestItems. I'm adding TestTags to each items' tags array in order to categorize them. I have an additional contributed menu item (inline) that triggers a command for the selected TestItem. I'd expect that the selected test item gets passed to the command with its TestTags, but it shows as empty (see below).

![image](https://user-images.githubusercontent.com/6414474/159549807-0530324c-331f-45d4-bd9a-c5556053d819.png)

I've uploaded a simple extension that demonstrates the problem here: https://github.com/KaravolisL/simple-test-extension
Please let me know if any more information is needed. Thanks!

**Comment by KaravolisL** [comment]
@connor4312 Thanks for working on this so quickly! I tried to verify this in insiders, but now the command is not even getting executed when the test item is clicked. I'm using the same sample extension in the original report. Here is my setup information: 

Version: 1.67.0-insider (user setup)
Commit: 909602cf04e0fa42528d692676d0d4e15e67bba2
Date: 2022-03-31T11:00:49.798Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19043

Should I submit a new issue for this?

**Comment by connor4312** [comment]
Thanks for verifying! Please try this once more tomorrow, I put in a fix earlier today for that, which was a result of some other refactors 804dc2f7de5c1501d6b3328aba39ef7804b6ff41

**Comment by KaravolisL** [comment]
Looks like it's fixed: 

Version: 1.67.0-insider (user setup)
Commit: 8b7086afdbfd42bf6e7b8c0bb586530bf7cf1396
Date: 2022-04-01T05:16:02.350Z
Electron: 17.3.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19043

![image](https://user-images.githubusercontent.com/6414474/161307257-fa92ce1b-9ab1-47bc-9c64-9234f0438922.png)
