### ISSUE TITLE
github.dev with Insiders VS Code fails to load builtin extensions

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#145791]
Does this issue occur when all extensions are disabled?: n/a

- VS Code Version: 1.66.0-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Access github.dev with VS Code Insiders enabled
2. :bug: **file explorer does not load**, GitHub.remotehub is not auto installed, I see the following message in the developer tools log:

```
 INFO Skipping the additional builtin extensions because their compatible versions are not foud. 
(2) [{…}, {…}]
0: {id: 'github.remotehub', preRelease: false}
1: {id: 'GitHub.vscode-pull-request-github', preRelease: false}
length: 2
[[Prototype]]: Array(0)
```

**Comment by sandy081** [comment]
This should be fixed in latest insiders.
