### ISSUE TITLE
Remove "Uncomitted Changes" in timeline

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#145723]
Testing #145461

1. Open a GH/Azure Repos repository on https://insiders.vscode.dev
2. Open and file, and open the timeline view
3. Ensure that both Git and Local History entries are shown
4. Make a change to the file and save
    - Local History entry is added to the top of the list
    - Local History entry is then moved under "Uncommitted Changes" entry

**Comment by bpasero** [comment]
I think this works as designed: the "Uncommitted Changes" from Git is probably always updating when you save and is more recent than the actual save event. 

@JacksonKearl would you agree this works as intended?

**Comment by JacksonKearl** [comment]
Roughly as designed, but could be smoother.

**Comment by connor4312** [comment]
I agree, I don't think "uncommitted changes" should be a history entry at all. It's not a historical event. You might _have_ uncommitted changes, but itself is not a change like everything else the timeline shows.

**Comment by bpasero** [comment]
I really like the idea to not have "Uncommitted Changes" at all. It seems to originate from the git extension:

https://github.com/microsoft/vscode/blob/2626c7f17ce7536722054cbaf70bb2da5c93c372/extensions/git/src/timelineProvider.ts#L228

Especially now that we have local history enabled, there will always be an entry for local history above the last committ, so the information is redundant. 

Lets do this.

**Comment by bpasero** [comment]
@joyceerhl not sure whether we want to remove those for remotehub extension as well:

https://github.dev/microsoft/vscode-remotehub/blob/68fa1962af31c0d1b84044735feff2d98af32a4b/extensions/remotehub/src/timelineProvider.ts#L126-L128

**Comment by joyceerhl** [comment]
@bpasero Removed the Uncommitted Changes timeline entries for RemoteHub. I kept the Staged Changes timeline entry though, since that is a historical event and it looks like we also kept those for the git extension.

**Comment by bpasero** [comment]
Thanks!

**Comment by maurobalbi** [comment]
This change has actually caught me off guard. While I like the idea for the "Local History" in general, It's sometimes too granular and I'd like to view all the changes since the last commit. Imho, the "Uncommited Changes" entry should be shown when "local history" is disabled, or it should be configurable by settings.

**Comment by bpasero** [comment]
Can you report a new feature request for this?
