### ISSUE TITLE
Webview non-custom editors do not appear to have a `kind`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145747]
Testing #145585

I would have expected a custom tab kind, but it is really nothing. I wonder if we miss another tab kind for non-custom-but-webview editors?

**Comment by bpasero** [comment]
Oh, same is true for a GH PR btw!

![image](https://user-images.githubusercontent.com/900690/159535329-19970f0a-bec2-4c10-b4b1-cbb772df7563.png)

**Comment by lramos15** [comment]
Added a webview tab kind. Did not include resource as felt that wasn't super helpful in the case of a webview. Let me know if you feel strongly otherwise.

To verify
Ensure that the tabs API returns a tab with the `TabKind` `TabKindWebview` when a webview tab is open

**Comment by lramos15** [comment]
> My gut feeling is that extensions will ask for a `uri` property for this kind.

I can give it to them but then it just feels like `TabKindCustom` and more people will ask why they are different which is purely a future proofing thing. I'm trying to think of the benefits of having a URI. I guess you can distinguish between two webviews of the same type in the same group? It doesn't allow you to open them or do anything like that

**Comment by bpasero** [comment]
Yeah, I was mainly concerned about identity and comparing tabs, but since tabs now remain stable even after changes, the `resource` is not needed for comparing anymore. And you are right, you cannot open a web view editor like that either.

I wonder though if it should be called `TabKindWebviewPanel` because I think the API talks about it here:

https://github.com/microsoft/vscode/blob/0a123b02d099e973b7c3360e62a64f830193a21e/src/vscode-dts/vscode.d.ts#L9427

**Comment by lramos15** [comment]
> I wonder though if it should be called `TabKindWebviewPanel` because I think the API talks about it here:

I say in the JSDoc that the `viewType` is equivalent but I felt like the word panel feels more like the rendered content within which is not the point of the tab API so I left it just as webview

**Comment by bpasero** [comment]
Sure, up to you and maybe pending API discussion when becoming final.

**Comment by JacksonKearl** [comment]
Verified Hex Editor is vscode.TabKindCustom, GHPR description page is vscode.TabKindWebview. I think that's correct, not entirely sure what the difference between the two is though -- aren't they all webviews?

**Comment by lramos15** [comment]
> entirely sure what the difference between the two is though -- aren't they all webviews?

They are both webviews just one has a backing filesystem resource and the other doesn't. So a custom editor is a webview but a webview is not a custom editor. The distinction is made because you can reopen a custom editor but not a webview.
