### ISSUE TITLE
Local history doesn't show notebook diff

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#145714]
Testing #145461

1. Open one of the github issue notebooks in the vscode repo
2. Make change
3. Save
4. Click the file saved entry to open the diff
5. 🐛 Says no changes when git shows changes

**Comment by bpasero** [comment]
@lramos15 the top entry always matches the version on disk, so you don't see any change.

**Comment by lramos15** [comment]
My bad, for some reason I keep thinking of the diff as before and after change.
