### ISSUE TITLE
Is settings sync on or off?

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#145794]
Testing #145623, but I don't know/think it is related.

- go to https://insiders.vscode.dev
- open a remote repository, sign into GitHub
- go to the Account icon on the Activity Bar, choose "Sign in for Settings Sync"
- choose to use your Microsoft account

Result: I'm prompted that SS is on and that I have to turn SS on, which is is?

![image](https://user-images.githubusercontent.com/1487073/159565001-89fedb48-0f6f-4bbd-a63c-4ef628d4df5d.png)

**Comment by TylerLeonhardt** [comment]
@sandy081 maybe you?

**Comment by sandy081** [comment]
@chrisdias Following the steps, I only see the second prompt that **Settings Sync was turned off from another device** but not both the prompts. First prompt **Settings Sync is turned on** is shown only if you turn on sync manually. I do not see you turned on Settings Sync manually in the steps. I assume that you would have turned on sync before these steps and the prompt was there already?

**Comment by chrisdias** [comment]
- in an InPrivate Window, go to https://insiders.vscode.dev
- click on `Open Remote Repository` button in Explorer
- Choose `Open Repository from GitHub` in quick pick
- `Allow` the extension 'GitHub Repositories' to sign in using GitHub
- Sign into GitHub, using 2FA
- Authorize `Microsoft` 
- Now I'm prompted to log in with my Microsoft credentials into GitHub, so Sign In with microsoft id
  - since i am on Mac I use my Password, then I'm prompted to authenticate with the app on my phone 
  - Again, authorize Microsoft account
- Once logged in, but do not choose a repository to open (for me it hangs), click on the Account Icon and `Turn on Settings Sync`
- Uncheck everything but `Keyboard Shortcuts`
- Click `Sign in & Turn on`
- Choose `Insiders`
- Choose `Sign in with Microsoft`

Result: the two prompts noted above.  

I'll try to do a video...

**Comment by chrisdias** [comment]
https://user-images.githubusercontent.com/1487073/159806896-441a6bd0-8e86-4b45-bff1-cf4bd7df77ac.mp4

**Comment by sandy081** [comment]
Thanks for the steps. I can reproduce.

**Comment by sandy081** [comment]
Here are simple steps to reproduce this:

- Start VS Code freshly (new user data dir and new extensions dir)
- Turn on Settings Sync and select only Keyboard Shortcuts
- Choose Settings Sync service in which you have not synced before
🐛 Both prompts are shown
