### ISSUE TITLE
Secondary sidebar does not have move commands

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#145752]
Testing #145634

Given that we show moving actions in the activity bar, primary side bar, and panel, I expect to see it here:

<img width="303" alt="CleanShot 2022-03-22 at 10 27 27@2x" src="https://user-images.githubusercontent.com/35271042/159540059-1d850d0d-33b9-42b2-aa14-f7cc8beb1bc0.png">

Examples:

<img width="304" alt="CleanShot 2022-03-22 at 10 23 39@2x" src="https://user-images.githubusercontent.com/35271042/159539339-b3eee1e1-4bf4-42e7-8155-8b3d4e133fd9.png">

<img width="341" alt="CleanShot 2022-03-22 at 10 23 13@2x" src="https://user-images.githubusercontent.com/35271042/159539307-68e12c9f-2772-4b49-ac5c-04311d1aefb9.png">

**Comment by sbatten** [comment]
hmm interesting, since it is only a function of the primary side bar, I did not add this. Do you think we should do something like "Swap Primary/Secondary Side Bar Positions" in both?

**Comment by misolori** [comment]
I think for consistency it should be the same, using "swap" might confuse users

**Comment by sbatten** [comment]
I was suggesting "Swap Side Bar Positions" in both, so it would be consistent. But, I can see that might cause some confusion, so just "Move Secondary Side Bar "Left/Right" then?
