### ISSUE TITLE
Commands that don't designate primary/secondary

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#145765]
Testing #145634

Found these commands that did not designate primary/secondary and not sure if they need updating:

- File: Reveal Active File in Side Bar `workbench.files.action.showActiveFileInExplorer` 
- Git: Reveal in Side Bar `git.revealInExplorer`
- View: Maximize Editor Group and Hide Side Bar `workbench.action.maximizeEditor`
- `search.action.revealInSideBar`

**Comment by misolori** [comment]
Similarly, found that `workbench.sideBar.location` doesn't mention primary/secondary in the title

<img width="643" alt="CleanShot 2022-03-22 at 11 21 51@2x" src="https://user-images.githubusercontent.com/35271042/159549519-cfd3ee0e-8050-4581-9c10-6919d38afc19.png">

**Comment by sbatten** [comment]
For the setting, this is intentional as the setting name has existed for a long time and would require updating users settings for little benefit.

For the commands above: good catch. I remember seeing the first 2 and thinking we shouldn't add Primary Side Bar but rather, they should say "Explorer" as they are revealing a specific view that at some point is likely to be moveable to other parts.

I think the Maxmize Editor Group command should be updated to say "side bars" and actually do that.

I don't know what the search action reveal in side bar does, I bound to it and nothing happened.

**Comment by bpasero** [comment]
> I think the Maxmize Editor Group command should be updated to say "side bars" and actually do that

👍 , yes the intent is to really maximize the editor, though now I wonder if it should also hide the panel, or maybe it does so already.

**Comment by sbatten** [comment]
@bpasero its not hiding the panel today, but we also have "Maximize Editor" which does no part hiding. I'm not sure what the full suffix should be for the one that hides everything.

possibilities:
- Maximize Editor Group and Area
- Maximize Editor Group and Hide Views
- Maximized Editor Group and Hide Panel and Side Bars

like any of those? or just want to stick to hiding the side bars?

**Comment by bpasero** [comment]
@sbatten I cannot recall the history of the command but to play it safe I would suggest to change it minimally that it hides both side bars, but otherwise does not care about the panel. The command is maybe older than the panel but I also never got complaints about how it behaves.

**Comment by gjsjohnmurray** [comment]
> I remember seeing the first 2 and thinking we shouldn't add Primary Side Bar but rather, they should say "Explorer"

@sbatten I think these were intentionally changed to not use the word Explorer because of confusion with the Windows Explorer, for which other Reveal commands exist.

**Comment by sbatten** [comment]
I wonder if we could say "Explorer View" or something like that. As we have "Focus on X View" as a pattern for command names.

**Comment by roblourens** [comment]
Same with the search command - this command is in the search context menu, it reveals the file in the Explorer view, and we used "side bar" for the reason @gjsjohnmurray points out.

We aren't specifying _which_ side bar, so the name sort of seems ok, it will reveal in some side bar. Or we could switch to "Reveal in Explorer View", that's fine with me too.

**Comment by rzhao271** [comment]
@sbatten what are some verification steps for this issue?

**Comment by sbatten** [comment]
1. Review the commands listed in @misolori's original post.
2. Verify their display names now make sense (search in command palette)
3. Execute the Maximize Editor Group and Hide Side Bars and verify it hides both side bars

**Comment by rzhao271** [comment]
I'm having trouble seeing `git.revealInExplorer` and `search.action.revealInSideBar` in the command palette. In the keybindings editor, I see that `git.revealInExplorer` is now "Git: Reveal in Explorer View", though.

**Comment by gjsjohnmurray** [comment]
@rzhao271 I doubt they appear in Command Palette, but you can see them in the context menu of a file in the SCM view and Search view respectively.
