### ISSUE TITLE
Editor is improperly marked `isPreview` in tabs api

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#145755]
Testing #145585

1. Have an extension which listens to `onDidChangeTabs`
2. Have a file open in two editor groups
3. Modify a file and hit save
4. :bug: tab is marked `isPreview`

![image](https://user-images.githubusercontent.com/30305945/159540401-eb7a0b69-5398-4151-ba8b-8d8a5c4c35fa.png)

**Comment by lramos15** [comment]
Hmm @bpasero https://github.com/microsoft/vscode/blob/c4370d1887e15a46bdf62bccf079a95ad7233365/src/vs/workbench/api/browser/mainThreadEditorTabs.ts#L310 is returning true even though the tab is no longer in preview mode. Will investigate further after triaging all tab issues but doesn't look like this is a bug within tab code.

**Comment by lramos15** [comment]
Thanks for the fix 😅! That was definitely a silly one on my part
