### ISSUE TITLE
VSCode API tests no longer run from within Code

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14579]
Mac OS X

I am not sure when that broke but I am quite sure it used to work:

![image](https://cloud.githubusercontent.com/assets/900690/19758026/91a60b12-9c26-11e6-9a6e-e0f53a35d1c3.png)

**Comment by jrieken** [comment]
Works for me - also build machines are happy. Make sure you have crap extension installed in you dev environment 

![screen shot 2016-10-27 at 18 04 52](https://cloud.githubusercontent.com/assets/1794099/19775185/e01f98b4-9c6f-11e6-9e9b-6775dc5bb7a1.png)

**Comment by bpasero** [comment]
@jrieken Yeah, I was suspecting this to be an issue with running the tests from within Code vs. running them in our build machines. 

I did git clean -xfd followed by scripts/npm.sh install and ran the tests again from insiders with same result. 

What else am I missing?

**Comment by bpasero** [comment]
So to clarify: I am trying to run the tests from within Code via our launch config.

**Comment by jrieken** [comment]
I run them via `./scripts/test-integration.sh` and I think that's also what the build machines do. I am not aware of other ways how to launch them - tho it might be a hint that those are broken?

**Comment by bpasero** [comment]
Wow, this is https://github.com/Microsoft/vscode/issues/14611
