### ISSUE TITLE
[css] selector separator newline 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#145766]
Testing #145604

It's a bit verbose to have `or not` and unnecessary IMO since it's a checkbox. I think it would be cleaner to have:

- [x] separate selectors with a new line
- [ ] separate selectors with a new line

![Screen Shot 2022-03-22 at 2 16 51 PM](https://user-images.githubusercontent.com/29464607/159548718-ffdb6644-de56-4116-9abb-6adf6ded6e49.png)

**Comment by hannahcoles** [comment]
Hi! Would I be able to work on this issue? I am contributing to a GitHub project for the first time and this seems like a good first issue for me.

**Comment by aeschli** [comment]
@hannahcoles Thanks for offering help. In this case I'd rather fix this myself as it's a new feature that we are still polishing, and I want to make these changes today.
