### ISSUE TITLE
anycode-typescript not installed and showing up randomly on the Extension Pack tab 

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#145739]
Testing #145560

Version: 1.66.0-insider
Commit: b0966eddca8cc86d3051213b6bf8327ef67ecf6d
Date: 2022-03-22T07:31:20.178Z
Electron: 17.1.2
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.13.0-30-generic

* uninstall anycode if you have it installed
* install the extension from this VSIX [anycode-0.0.61.vsix.zip](https://github.com/microsoft/vscode/files/8316161/anycode-0.0.61.vsix.zip)
* in the extension viewlet query `@installed anycode`: anycode-typescript is missing
* go to the `Extension Pack` tab of the `anycode` extension: anycode-typescript is missing
* open some other tabs in `anycode` extension then come back to `Extension Pack` : anycode-typescript is shown (but not installed)

![Peek 2022-03-22 17-44](https://user-images.githubusercontent.com/6461412/159532201-cd5dc9dd-79fe-44ef-b9d9-bbbae0d81957.gif)

**Comment by bamurtaugh** [comment]
I see the same (all extensions installed except TS):

![image](https://user-images.githubusercontent.com/25310137/159533787-78d94760-ea2b-4ce0-b1f1-b68a75b2aebb.png)

**Comment by jrieken** [comment]
Needs help from @sandy081. The `anycode-typescript`-extension does exists in the marketplace like the others... 

<img width="1274" alt="Screenshot 2022-03-22 at 18 01 43" src="https://user-images.githubusercontent.com/1794099/159535119-8e82c32e-df91-4bf0-ac2b-d9cae4584551.png">

**Comment by bamurtaugh** [comment]
I just tried again, and now `anycode-typescript` did install. Here are the logs anyways (although likely not as useful since this worked):

> [2022-03-22 12:10:00.282] [sharedprocess] [info] Installing extension: ms-vscode.anycode
> [2022-03-22 12:10:00.532] [sharedprocess] [info] Getting Manifest... ms-vscode.anycode-java
> [2022-03-22 12:10:00.843] [sharedprocess] [info] Getting Manifest... ms-vscode.anycode-python
> [2022-03-22 12:10:01.033] [sharedprocess] [info] Getting Manifest... ms-vscode.anycode-cpp
> [2022-03-22 12:10:01.233] [sharedprocess] [info] Getting Manifest... ms-vscode.anycode-php
> [2022-03-22 12:10:01.443] [sharedprocess] [info] Getting Manifest... ms-vscode.anycode-rust
> [2022-03-22 12:10:01.669] [sharedprocess] [info] Getting Manifest... ms-vscode.anycode-c-sharp
> [2022-03-22 12:10:01.873] [sharedprocess] [info] Getting Manifest... ms-vscode.anycode-go
> [2022-03-22 12:10:02.072] [sharedprocess] [info] Getting Manifest... ms-vscode.anycode-typescript
> [2022-03-22 12:10:02.495] [sharedprocess] [info] Installing extension: ms-vscode.anycode-java
> [2022-03-22 12:10:02.495] [sharedprocess] [info] Installing extension: ms-vscode.anycode-python
> [2022-03-22 12:10:02.496] [sharedprocess] [info] Installing extension: ms-vscode.anycode-cpp
> [2022-03-22 12:10:02.496] [sharedprocess] [info] Installing extension: ms-vscode.anycode-php
> [2022-03-22 12:10:02.496] [sharedprocess] [info] Installing extension: ms-vscode.anycode-rust
> [2022-03-22 12:10:02.496] [sharedprocess] [info] Installing extension: ms-vscode.anycode-c-sharp
> [2022-03-22 12:10:02.496] [sharedprocess] [info] Installing extension: ms-vscode.anycode-go
> [2022-03-22 12:10:02.497] [sharedprocess] [info] Installing extension: ms-vscode.anycode-typescript
> [2022-03-22 12:10:03.287] [sharedprocess] [info] Downloaded extension: ms-vscode.anycode-python c:\Users\brmurtau\AppData\Roaming\Code - Insiders\CachedExtensionVSIXs\ms-vscode.anycode-python-0.0.3
> [2022-03-22 12:10:03.287] [sharedprocess] [info] Downloaded extension: ms-vscode.anycode-cpp c:\Users\brmurtau\AppData\Roaming\Code - Insiders\CachedExtensionVSIXs\ms-vscode.anycode-cpp-0.0.3
> [2022-03-22 12:10:03.287] [sharedprocess] [info] Downloaded extension: ms-vscode.anycode-java c:\Users\brmurtau\AppData\Roaming\Code - Insiders\CachedExtensionVSIXs\ms-vscode.anycode-java-0.0.3
> [2022-03-22 12:10:03.288] [sharedprocess] [info] Downloaded extension: ms-vscode.anycode-php c:\Users\brmurtau\AppData\Roaming\Code - Insiders\CachedExtensionVSIXs\ms-vscode.anycode-php-0.0.4
> [2022-03-22 12:10:03.288] [sharedprocess] [info] Downloaded extension: ms-vscode.anycode-c-sharp c:\Users\brmurtau\AppData\Roaming\Code - Insiders\CachedExtensionVSIXs\ms-vscode.anycode-c-sharp-0.0.3
> [2022-03-22 12:10:03.288] [sharedprocess] [info] Downloaded extension: ms-vscode.anycode-go c:\Users\brmurtau\AppData\Roaming\Code - Insiders\CachedExtensionVSIXs\ms-vscode.anycode-go-0.0.3
> [2022-03-22 12:10:03.288] [sharedprocess] [info] Downloaded extension: ms-vscode.anycode-rust c:\Users\brmurtau\AppData\Roaming\Code - Insiders\CachedExtensionVSIXs\ms-vscode.anycode-rust-0.0.3
> [2022-03-22 12:10:03.615] [sharedprocess] [info] Removed the extension from uninstalled list: ms-vscode.anycode-cpp
> [2022-03-22 12:10:03.645] [sharedprocess] [info] Removed the extension from uninstalled list: ms-vscode.anycode-php
> [2022-03-22 12:10:03.665] [sharedprocess] [info] Removed the extension from uninstalled list: ms-vscode.anycode-python
> [2022-03-22 12:10:03.684] [sharedprocess] [info] Removed the extension from uninstalled list: ms-vscode.anycode-java
> [2022-03-22 12:10:03.727] [sharedprocess] [info] Removed the extension from uninstalled list: ms-vscode.anycode-go
> [2022-03-22 12:10:03.767] [sharedprocess] [info] Removed the extension from uninstalled list: ms-vscode.anycode-c-sharp
> [2022-03-22 12:10:03.781] [sharedprocess] [info] Removed the extension from uninstalled list: ms-vscode.anycode-rust
> [2022-03-22 12:10:04.071] [sharedprocess] [info] Downloaded extension: ms-vscode.anycode-typescript c:\Users\brmurtau\AppData\Roaming\Code - Insiders\CachedExtensionVSIXs\ms-vscode.anycode-typescript-0.0.3
> [2022-03-22 12:10:04.135] [sharedprocess] [info] Extracted extension to c:\Users\brmurtau\.vscode-insiders\extensions\.21598f8c-8a1b-4cb7-be64-476d3bd45076: ms-vscode.anycode-typescript
> [2022-03-22 12:10:04.146] [sharedprocess] [info] Renamed to c:\Users\brmurtau\.vscode-insiders\extensions\ms-vscode.anycode-typescript-0.0.3
> [2022-03-22 12:10:04.153] [sharedprocess] [info] Extracting completed. ms-vscode.anycode-typescript
> [2022-03-22 12:10:04.445] [sharedprocess] [info] Removed the extension from uninstalled list: ms-vscode.anycode
> [2022-03-22 12:10:04.506] [sharedprocess] [info] Deleted from disk ms-vscode.anycode c:\Users\brmurtau\.vscode-insiders\extensions\ms-vscode.anycode-0.0.61
> [2022-03-22 12:10:04.601] [sharedprocess] [info] Extracted extension to c:\Users\brmurtau\.vscode-insiders\extensions\.363df0b1-862d-483b-9fd7-66bcf50d9471: ms-vscode.anycode
> [2022-03-22 12:10:04.614] [sharedprocess] [info] Renamed to c:\Users\brmurtau\.vscode-insiders\extensions\ms-vscode.anycode-0.0.61
> [2022-03-22 12:10:04.620] [sharedprocess] [info] Extracting completed. ms-vscode.anycode
> [2022-03-22 12:10:04.622] [sharedprocess] [info] Extension installed successfully: ms-vscode.anycode-cpp
> [2022-03-22 12:10:04.622] [sharedprocess] [info] Extension installed successfully: ms-vscode.anycode-php
> [2022-03-22 12:10:04.622] [sharedprocess] [info] Extension installed successfully: ms-vscode.anycode-python
> [2022-03-22 12:10:04.622] [sharedprocess] [info] Extension installed successfully: ms-vscode.anycode-java
> [2022-03-22 12:10:04.622] [sharedprocess] [info] Extension installed successfully: ms-vscode.anycode-go
> [2022-03-22 12:10:04.622] [sharedprocess] [info] Extension installed successfully: ms-vscode.anycode-c-sharp
> [2022-03-22 12:10:04.623] [sharedprocess] [info] Extension installed successfully: ms-vscode.anycode-rust
> [2022-03-22 12:10:04.623] [sharedprocess] [info] Extension installed successfully: ms-vscode.anycode-typescript
> [2022-03-22 12:10:04.623] [sharedprocess] [info] Extension installed successfully: ms-vscode.anycode

**Comment by sandy081** [comment]
Closing this as it seems working.
