### ISSUE TITLE
Language filter not discoverable, needs funnel icon inline action

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#145710]
Testing #145588

I liked some of the mocks that @lychung7 did, to use the inline action in the search box to make the language filter more discoverable.
With the current approach no user will find this feature.

I apologise if this is already planned for next milestone and if this issue is just duplication.

fyi @sandy081

**Comment by rzhao271** [comment]
This issue is planned but I don't think I made an issue for it yet, so we can use this one to track.
