### ISSUE TITLE
Configuration schema should show squiggles for missing "hightContrastLight" on contributed colors

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#145704]
I saw https://github.com/microsoft/vscode-pull-request-github/issues/3425 and while making the update I found that there is no intellisense or squiggles for `"hightContrastLight"` in the `"defaults"` property of a color.

**Comment by aeschli** [comment]
The property is not required, so it's not an error of not having `highContrastLight`. Not super easy to add the the JSON schema as it only supports required or not required.

**Comment by alexr00** [comment]
It seems like it's required since leaving it off creates warnings.

**Comment by aeschli** [comment]
The warning should just be an info... :-)

**Comment by aeschli** [comment]
I removed the warning/info. `highContrastLight` is optional and if not provided, `light` is used. IMO that's a good default.
For consistency I did the same to `highContrast`. It is now also optional and `dark` is used if not set.
