### ISSUE TITLE
Refresh button doesn't check history for deleted files

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#145708]
Testing #145461

1. Create a bunch of local history
2. Delete the local history files from user data dir
3. Hit refresh button
4. 🐛 Entries still there.

Entries are not there on reload of the window so I would expect clicking the refresh button would force a refresh as well

**Comment by bpasero** [comment]
@JacksonKearl this might need support from the timeline, i.e. when the refresh command is used from the timeline toolbar, give me a hint that I should really go to disk and resolve all entries.

I see how there is this:

https://github.com/microsoft/vscode/blob/d0f7122bb97c6232b4423185ab80c8e17bc0ea33/src/vs/workbench/contrib/timeline/common/timeline.ts#L81-L84

But `resetCache` seems to be `true` even when I just go from one editor to the other. 

I would rather want to limit going to disk to the refresh action specifically.

**Comment by bpasero** [comment]
Don't think this is critical, it is not advised to tamper with contents in the user data dir.
