### ISSUE TITLE
No split icon on the panel toolbar when there are multiple terminals

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#145784]
I'm only using one terminal and always split it through the split icon on the panel toolbar. 

<img width="237" alt="image" src="https://user-images.githubusercontent.com/876920/159556730-f8eaf510-da25-462d-bc61-dfe3530b52cc.png">

However the very moment I run build task, there are more than one terminal instances, the split button is then gone. I have to now hover on the tiny terminal name and click on the split button there. I also need to be careful to avoid clicking on the delete button. I personally find it painful every time using mouse to split the terminal.

<img width="132" alt="image" src="https://user-images.githubusercontent.com/876920/159556849-aca48134-b35a-4dfc-afc7-83187319af22.png">

Version: 1.66.0-insider
Commit: b0966eddca8cc86d3051213b6bf8327ef67ecf6d
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4911.0 Safari/537.36 Edg/101.0.1193.0
Embedder: vscode.dev

**Comment by Tyriar** [comment]
This has come up before and I'm waiting on https://github.com/microsoft/vscode/issues/46403 to be implemented at which point the kills/split icons could still be there but be toggled on.
