### ISSUE TITLE
Have a `TabKind` for terminals

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145895]
Testing #145585

currently if I open a terminal, there is no `kind` then.

**Comment by lramos15** [comment]
This was done initially on purpose. What information would you expect on a terminal tab kind? It would just be an empty class.

**Comment by bpasero** [comment]
Yeah I was more thinking that it would enable an extension to build something specifically for terminals or excluding terminals. E.g. "Close All Terminals". Doesn't mean you need to access any properties within.

To me, tab kinds allow to tell apart different kinds of tabs primarily, the resource within comes after.

**Comment by lramos15** [comment]
To verify:
Ensure a terminal tab populates kind correctly
