### ISSUE TITLE
Hard to tell where navigation is on slower machines

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#145801]
Testing #145627

When working on a machine that is slow/sluggish, it is impossible to tell where the navigation goes to because the line highlight fades away. I think having some type of subtle decoration on the line would help alleviate this issue for time based animations. The Terminal app shows a line:

<img width="238" alt="CleanShot 2022-03-22 at 15 10 38@2x" src="https://user-images.githubusercontent.com/35271042/159584788-0f0075bc-7187-40ae-9b1b-ef3eb1662dec.png">

Tried capturing this experience:

https://user-images.githubusercontent.com/35271042/159584936-12fa1e18-fb81-4454-90f1-5280c21a7e7f.mov

**Comment by roblourens** [comment]
Maybe you can verify this on the same machine @misolori
