### ISSUE TITLE
Support find history in simple find widget (terminal, webview)

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#145871]
Testing #145629

<img width="451" alt="image" src="https://user-images.githubusercontent.com/10746682/159671296-745d593a-e7b6-4425-9842-2ca5ec5b857b.png">

**Comment by meganrogge** [comment]
What is your image supposed to show?

**Comment by sandy081** [comment]
Sorry for not uploading right image.. here you go

<img width="458" alt="image" src="https://user-images.githubusercontent.com/10746682/159761664-9a2ea20f-62b9-4f35-86cd-7968302382a2.png">
