### ISSUE TITLE
Folded decoration is rendered garbled

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#145897]
Issue Type: <b>Bug</b>

Fold a region and observe it. Unfortunately this went away after a window reload:

> <img width="459" alt="Screenshot 2022-03-23 at 16 18 29" src="https://user-images.githubusercontent.com/5047891/159733514-73d154f6-3818-44a2-8cae-3db886b7d458.png">

VS Code version: Code - Insiders 1.66.0-insider (2eebd2a0159af379057a58c8bcb519f95bfd6328, 2022-03-23T05:27:08.615Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

**Comment by aeschli** [comment]
There haven't been any changes from mein that area recently. 
https://github.com/microsoft/vscode/blob/22e246d2512d4dfa21c29b569edc991f4f97513a/src/vs/editor/contrib/folding/browser/folding.css#L27

Likely a Chromium glitch.

Please reopen if you have it reproducible.

**Comment by aeschli** [comment]
I still don't know why this happens sometimes, but it shows up regularly. In the dev tools it shows that chromium has loaded the stylesheet in a wrongly encoded way.

I hope to avoid this by escaping the ellipses unicode character.
