### ISSUE TITLE
Keyboard reference should get some UI love

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14580]
I find our keybinding PDF a bit boring, especially hard to distinguish a keybinding from a command. In the end we want people to print this out and put it over their desk or even print T-Shirts with it.

Inspirations:
- Atom cheat sheet http://d2wy8f7a9ursnm.cloudfront.net/atom-editor-cheat-sheet.pdf
- Sublime cheat sheet https://www.cheatography.com/martinprins/cheat-sheets/sublime-text-3-osx/

Ours:
![image](https://cloud.githubusercontent.com/assets/900690/19758310/c8f6d410-9c27-11e6-8fdd-3752389c5dcb.png)

Atom:
![image](https://cloud.githubusercontent.com/assets/900690/19758316/cfa1948a-9c27-11e6-85dc-0ffe9c93f187.png)

Sublime:
![image](https://cloud.githubusercontent.com/assets/900690/19758330/d883ca46-9c27-11e6-9f27-ca5fd1f275c8.png)

**Comment by bpasero** [comment]
Maybe this is yet a placeholder? I also see only Windows keybindings when I am on Mac.

/cc @isidorn

**Comment by isidorn** [comment]
@bpasero when I am on a mac I am correctly directed to this page
http://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf

What page gets opened for you?

**Comment by bpasero** [comment]
@isidorn the same but all keys are Ctrl keys and not Cmd

**Comment by isidorn** [comment]
@bpasero then it should be fixed by @waderyan or @gregvanl who are in charge of the content of that document

**Comment by waderyan** [comment]
@gregvanl made what you are seeing as placeholders. Stay tuned for the awesome work from @bgashler1

**Comment by bpasero** [comment]
Ah ok cool :)

**Comment by bgashler1** [comment]
Updated as of Friday

**Comment by bpasero** [comment]
Very nice 👍
