### ISSUE TITLE
Monospacing broken by Chinese character 

### ISSUE THREAD

**Issue by actboy168** [Microsoft/vscode#14589]
- VSCode Version: Code - Insiders 1.7.0-insider (9d472850269c3f7ff1043b86f823115927af1982, 2016-10-27T06:11:25.272Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

---

[yahei_mono.zip](https://github.com/Microsoft/vscode/files/555425/yahei_mono.zip)

notepad:
![1](https://cloud.githubusercontent.com/assets/1836844/19762787/f2825cdc-9c6d-11e6-9033-eb01b6b61250.png)

vscode:
![2](https://cloud.githubusercontent.com/assets/1836844/19762894/5e2dfc0c-9c6e-11e6-865f-c7b8a5d00441.png)

Steps to Reproduce:

1.Setup 'Yahei Mono' font.
2.Set to setting.json

```
{
    "editor.fontFamily": "Yahei Mono"
}
```

3.Input

```
中文汉字  KLMN
中文汉字IJKLMN
中文EFGHIJKLMN
ABCDEFGHIJKLMN
```

**Comment by alexandrudima** [comment]
@actboy168 Does it work with `"editor.fontFamily": "'Yahei Mono'"

**Comment by actboy168** [comment]
![3](https://cloud.githubusercontent.com/assets/1836844/19769353/aa94bed6-9c8d-11e6-9a37-161cddaceaab.png)

**Comment by alexandrudima** [comment]
I can reproduce the problem, but I'm sorry the ultimate font rendering is done by Chromium. So, feel free to create an issue against Chromium https://bugs.chromium.org/p/chromium/issues/list

Here for example I am using Inconsolata (http://levien.com/type/myfonts/inconsolata.html)
![image](https://cloud.githubusercontent.com/assets/5047891/19770883/3623e56c-9c61-11e6-89d2-94dc850b2900.png)

We use 100% the same code to render. When changing fontFamily we simply let Chromium know the desired font family and let it render the text.

**Comment by abcfy2** [comment]
Same issue here. Chinese fonts does not work with monospace.

Here is my vscode config:
```json
{
    "editor.fontFamily": "'Monaco', 'Source Han Sans'",
    "editor.fontSize": 20,
    "editor.wrappingColumn": 0,
    "editor.wrappingIndent": "indent",
    "editor.formatOnType": true,
    "editor.tabCompletion": true,
    "editor.mouseWheelZoom": true,
    "editor.renderControlCharacters": true,
    "editor.renderIndentGuides": true,
    "files.autoSave": "afterDelay",
    "editor.renderWhitespace": "all",
    "editor.rulers": [80]
}
```

Chinese fonts always mono.

`vim` or terminal works very vell.

But vscode doesn't.

**Comment by alexandrudima** [comment]
@abcfy2 Please create an issue against Chromium if you believe the font you are trying is monospace and Chromium renders it incorrectly https://bugs.chromium.org/p/chromium/issues/list

In the meantime, the Inconsolata font I link to above **is monospace** and renders consistent widths for CJK characters.

**Comment by CnSimonChan** [comment]
xterm.js creates spans for each CJK characters to adjust their width to be equal to two Latin characters, so they look perfect in the Integrated Terminal.

![image](https://user-images.githubusercontent.com/1330321/29494566-a27ab750-85df-11e7-9637-c7099226a638.png)

Can Code do the same thing?

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
