### ISSUE TITLE
Terminal Find match highlighting appears off

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#145808]
Testing #145629

Windows 11 PowerShell

The brownish highlighting appears to be several characters off.

![image](https://user-images.githubusercontent.com/12818376/159587863-cc95a7cd-bfa9-43f6-8131-d5d831180c80.png)

Makes it really hard to read the matched text

**Comment by meganrogge** [comment]
That's because you have zoom level set to something other than the default. Try resetting zoom

**Comment by gregvanl** [comment]
Hmm, my zoom level window.zoomLevel is 0

**Comment by Tyriar** [comment]
Can repro, need gpuAcceleration to be off. Problem is related to the dom cell width being different.
