### ISSUE TITLE
Running a test should not reveal the test viewlet / sidebar

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#145892]
I love that I can run tests straight from the editor!

But when using the gutter run test action, the sidebar is always revealed and switched to the test viewlet. I personally find this disruptive, as I might have collapsed the sidebar intentionally to save screen real estate or I might be using the search viewlet.

https://user-images.githubusercontent.com/5047891/159719112-d9fce38f-e672-4e27-a75c-b2610fcb3733.mp4

**Comment by bpasero** [comment]
Yes, I configure `"testing.openTesting": "neverOpen"` for that reason.

**Comment by alexdima** [comment]
Oh, nice, thank you. Wasn't aware of the setting!

**Comment by alexdima** [comment]
@connor4312 Leaving the issue open in case you want to consider changing the default. But please consider me happy!

**Comment by connor4312** [comment]
Yea, this is something I've heard input both ways on. I eventually made it open by default under the logic that it's the best experience for new users (who might not be very familiar with vscode ui and use run tests from the gutter icon) and experienced users who want to tweak it can figure out how to do so.
