### ISSUE TITLE
Wrong decorations for commands

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#145819]
Testing #145599

I was repeatedly running `ll` and `ls -al`

* multiple `ll` commands, the decorations are all gray
* `ls -al` the decoration is blue
* multiple `ls -al`, the decorations are all blue
* multiple `ll`, the decorations are still blue

The colors in the scrollbar are the same as the dots before each command, but I don't know how to interprete the colors.

**Comment by meganrogge** [comment]
What does ll do?

**Comment by meganrogge** [comment]
Had you run clear before repro'ing this?
