### ISSUE TITLE
onWillSaveTextDocument not firede after frequent save operations

### ISSUE THREAD

**Issue by SherrybabyOne** [microsoft/vscode#145859]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: macOS 11.6.4

I implemented a formatter to format each time the file is saved in VSCode, so I listened to the onWillSaveTextDocument event, but onWillSaveTextDocument will not be triggered after frequent save operations, what is the reason for this?

I provide a demo: https://github.com/SherrybabyOne/vscode-format-test

Steps to Reproduce:

1. yarn
2. F5 to launch the debugger
3. Open a file, save and wait for 10s, you will find an extra "test" string
4. Save it again, modify the file within 10s and save it. After repeating the operation, you will find that the "test" string will not be added again, and the debugger terminal will not print the "Format require from" string.

**Comment by SherrybabyOne** [comment]
The code is roughly as follows:

```
async function format(code: string): Promise<string> {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(code + 'test');
    }, 10000)
  });
}

async function autoFormat(document: vscode.TextDocument, editor: vscode.TextEditor): Promise<void> {
  const { version, fileName } = document;
  const code = document.getText();

  console.log(`Format request of ${fileName} received.\n`);

  try {
    const startPosition = new vscode.Position(0, 0);
    const endPosition = new vscode.Position(document.lineCount, 0);
    const replaceRange = new vscode.Range(startPosition, endPosition);

    const result = await format(code);

    console.log('Format result!', editor.document.version, version);
    
    if (code !== result && editor.document.version === version) {
      await editor.edit(edit => edit.replace(replaceRange, result));
    }
  } catch (e) {
    console.log(e);
  }
}

export function activate(context: vscode.ExtensionContext): void {
  context.subscriptions.push(vscode.workspace.onWillSaveTextDocument((e) => {
    const editor = vscode.window.activeTextEditor;

    if (editor && editor.document === e.document) {
      e.waitUntil(autoFormat(e.document, editor));
      // format(e.document, textEditor, number);
    }
  }));
}
```

It seems that it may be related to format being an asynchronous function, can't asynchronous operations be performed in waitUntil?

Or is there a more recommended way to save autoformat?

**Comment by jrieken** [comment]
Maybe you listener is considered to be slow or throwing errors? Iff we will stop calling it. You can check your self for that with the extension host log: F1 > Show Logs... > Extension Host. It would contain messages starting with `onWillSaveTextDocument-listener from extension...`


Apart from that I do **strongly** advice against the approach you have chosen. Please do not implement format on save with the `onWillSaveTextDocument` event but implement a [`DocumentFormattingEditProvider`](https://github.com/microsoft/vscode/blob/0a123b02d099e973b7c3360e62a64f830193a21e/src/vscode-dts/vscode.d.ts#L3834). That gives you format on save out of the box and also gives you more time to format the document. Also see https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices where this is explained further

**Comment by SherrybabyOne** [comment]
Thank you very much for your reply, this way is great
