### ISSUE TITLE
GoToDefinition ommit indirect or nested definitions 

### ISSUE THREAD

**Issue by analityk** [microsoft/vscode#145806]
#define SRC_bit 	(1)
#define SRC_shf	(5)
#define FIRST_OPT (SRC_bit << SRC_shf)
#define SECOND_OPT_bit	(3)
#define SECOND_OPT_shf	(9)
#define SECOND_OPT	(SECOND_OPT_bit << SECOND_OPT_shf) 
#define TIMER_START_UPCNT (FIRST_OPT | SECOND_OPT)

main[...]
...
if(TIMER_START_UPCNT == 0){
when i try go to definition of TIMER_START_UPCNT i am redirect to #define SECOND_OPT_shf	(9) instead  #define TIMER_START_UPCNT (FIRST_OPT | SECOND_OPT) what i expect. This example work's in main and also in entire solution, so options like goto Def or goto implementatition are useless. 

In any case reading the code and navigation throught it is most important thing that IDE can offer and any nested define shoudn't be skipped by it. 

- VS Code Version: February 2022 (version 1.65)
- OS Version: Win 7 Pro x64 
- HP Z600, Xeon 5630 x 2, 32GB RAM, 1T SSD, GTX1660Ti
- I have installed platformio but it is not any project from it. 
Here you have my repository:
https://github.com/analityk/maketest/tree/master/maketest
here is how it look like (YT):
https://www.youtube.com/watch?v=5FADq5yRp6g

EDIT:
How to reproduce it:
search c_cpp_properties.json,
set "compilerPath" to different than windows compiler (in my case it was arm-none-eabi-gcc from arm toolchain), 
set "compilerArgs" - set any, 
Save file and save folder. Reopen VScode. 

Now when i open folder with my code VSCode throw information "

[23.03.2022, 14:41:51] W przypadku plików źródłowych w języku C++ wartość właściwości IntelliSenseMode została zmieniona z „windows-msvc-arm” na „windows-gcc-arm” na podstawie argumentów kompilatora i wykonywania zapytań dotyczących właściwości compilerPath: „C:/dev/tools/gcc-arm-none-eabi-10.3-2021.10/bin/arm-none-eabi-gcc.exe”

[23.03.2022, 14:41:51] W przypadku plików źródłowych w języku C wartość właściwości IntelliSenseMode została zmieniona z „windows-msvc-arm” na „windows-gcc-arm” na podstawie argumentów kompilatora i wykonywania zapytań dotyczących właściwości compilerPath: „C:/dev/tools/gcc-arm-none-eabi-10.3-2021.10/bin/arm-none-eabi-gcc.exe” " 

So you think is it matter? 

I totaly delete my compiler patch and it's arguments and now gotoDefinition work good and as anyone expect. In my opinion changes in gotodefinition shoud not be compiler-dependent.

**Comment by jrieken** [comment]
> Steps to Reproduce: just always

Just tried this with TypeScript and works great. If you want this issue to addressed please start by mentioning the language that you are using what extension is offering services for that language

**Comment by zmday22** [comment]
I am having a similar issue even after removing any custom compiler settings. A quick sample in C...
```
#define Z 1
#define Y (Z + 1)
#define X Y

char test = X;

int main(void)
{
    char test2 = X;
}
```

Going to the definition of `X` when it is assigned to `test` works as expected.
Going to the definition of `X` when it is assigned to `test2` brings me to the definition of Z, which is inconvenient and incorrect.

 
![image](https://user-images.githubusercontent.com/91489493/166710011-d112c792-4e2f-4f5c-ae6d-581e4f21fc1b.png)

**Comment by analityk** [comment]
In file c_cpp_properties.json set "intelliSenseMode": "windows-msvc-x86". It look like issue with this socket and not with VSC but all this product is from microsoft, so they should be shame.

**Comment by jrieken** [comment]
Sorry, the bot failed. This issue is valid but in the wrong repo. Please file against the C++ extensions, not vscode itself. Thanks
