### ISSUE TITLE
Toggle side bar command name consistency

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#145858]
Testing #145634

Nit: Both should have or not have 'Visibility' in their name:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/9205389/159661040-82ab6ed7-358c-4b13-b96e-22d7b9267875.png">

**Comment by sbatten** [comment]
I've opted to add Visibility to the Secondary Side Bar command AND the Toggle Panel command as well. All workbench parts had a `Toggle X Visibility` command aside from the panel and secondary side bar before the change. Now all do.
