### ISSUE TITLE
Indentation keeps changing to "Spaces" for files without indentations

### ISSUE THREAD

**Issue by aptash** [microsoft/vscode#145857]
Issue Type: <b>Bug</b>

Hello!
I spent/lost a lot of time while trying to change indentation for my new project.

How it works now:
1. Create a new file.js
2. Change indentation from "Spaces: 4" to "Tab Size: 4" by clicking on the status bar.
3. Save and close the file.
4. Reopen the file. You will see "Spaces: 4" in the status bar instead of "Tab Size: 4".

How it should work:
The status bar shows the "Tab Size: 4" after reopening the file.

-------------
Though everything works alright in case there are some strings with indentation!

But I was strugling with Prettier, VS Code settings, searching the web, trying different settings and advices on how to change indentation and keep it that way.
Though it was enough just to write some code. But I wanted to set desired settings BEFORE writing any code. 

Thanks in advance!

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by alexdima** [comment]
The indentation settings can be controlled by 3 options:
```js
// The number of spaces a tab is equal to. This setting is overridden based
// on the file contents when `editor.detectIndentation` is on.
"editor.tabSize": 4,
// Insert spaces when pressing `Tab`. This setting is overridden based on 
// the file contents when `editor.detectIndentation` is on.
"editor.insertSpaces": true,
// Controls whether `editor.tabSize#` and `#editor.insertSpaces` will be 
// automatically detected when a file is opened based on the file contents.
"editor.detectIndentation": true,
```
