### ISSUE TITLE
Highlights are shown even if find widget is closed

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#145866]
Testing #145629

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/10746682/159664819-43e48141-5f67-4e7e-8206-9321468c9747.png">

**Comment by meganrogge** [comment]
The widget is open in your screenshot

**Comment by meganrogge** [comment]
![Screen Shot 2022-03-23 at 12 02 34 PM](https://user-images.githubusercontent.com/29464607/159743135-b3d5bfe9-f6a2-4a8b-8772-220e7736f8c6.png)

**Comment by meganrogge** [comment]
Thanks, but I cannot repro this - could you pls attach a gif?

**Comment by sandy081** [comment]
- Have a split terminal
- Focus in second terminal and open find widget and search for some text to show highlights
- Focus in first terminal and press escape
