### ISSUE TITLE
VS Code requires git ssh keys to be named as "id_rsa"

### ISSUE THREAD

**Issue by SathyaBhat** [Microsoft/vscode#14581]
- VSCode Version: 

 Version 1.6.1
 Commit 9e4e44c19e393803e2b05fe2323cf4ed7e36880e
 Date 2016-10-13T15:43:46.054Z
 Shell 1.3.7
 Renderer 52.0.2743.82
 Node 6.5.0

- OS Version: Linux Mint 18

Steps to Reproduce:

1.  Create a ssh-key for github with filename something other than id_rsa (ex: github_key_id_rsa)
2. Try to push to the remote github repository

VS Code's git push fails with error messages:

> 
> Please make sure you have the correct access rights
> and the repository exists.
> git fetch
> Permission denied (publickey).
> fatal: Could not read from remote repository.

Push to repo on the command line with `git push` works. If I rename the key to id_rsa then the push operations work fine

**Comment by joaomoreno** [comment]
#13680

**Comment by tr0yspradling** [comment]
This issue is still vary much alive. Why was this closed?

My security preference for SSH configurations is to use a different key for my services. One master key isn't very smart. So I'd like to have the option to set a filename of the keys to use in a configuration file or something.

**Comment by joaomoreno** [comment]
@tr0yspradling It's a duplicate of #13680
