### ISSUE TITLE
With some files, VS Code cannot find modules that exist

### ISSUE THREAD

**Issue by TurnrDev** [microsoft/vscode#145880]
Similar to #10391, but with Python. Sometimes modules won't be detected on a single file. Renaming the file solves the issue, and it seems closing the Workspace and reopening it (twice) solved the issue for me. But it's definitely a bug that needs fixing.

Things I tried which failed:
* Clearing the Python Language Server cache
* Restarting the Python Language Server
* Restarting VSCode
* Restarting the computer

Version: 1.65.2 (system setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

> I have noticed that if I use `File -> Close folder` and then `File -> Open Folder...` and open the project folder again, the errors are gone. If I just restart VS Code instead, I keep getting the errors. I presume that some internal cache gets cleared?

_Originally posted by @jankalfus in https://github.com/microsoft/vscode/issues/10391#issuecomment-238854913_

**Comment by TurnrDev** [comment]
Can we say for sure though? If the TypeScript extension had the same regression, surely it's an issue in vscode itself?

**Comment by mjbvz** [comment]
Yes, even though the symptom is similar the root causes are almost certainly different
