### ISSUE TITLE
Ctrl-up/down bindings cease to work on 0.10.4 insiders update

### ISSUE THREAD

**Issue by borgdylan** [Microsoft/vscode#1458]
After updating Visual Studio Code from 0.10.1 to 0.10.4, I noticed that the ctrl-up/down no longer moved my selection or current line of code up or down.

**Comment by borgdylan** [comment]
I can confirm that ctrl-[ and ctrl-] still indent/dedent code as before.

**Comment by borgdylan** [comment]
Just in case anyone asks:
OS: Ubuntu 15.10
Kernel: Linux 4.3.0 for Intel x86
Code: 0.10.4

**Comment by borgdylan** [comment]
I also confirm that this remain broken in 0.10.5 (december release).

**Comment by borgdylan** [comment]
I am closing this issue. The actions that used to be ctrl+up/down have now moved to alt-up/down according to the docs. This will be a nuisance for many so please edit the release notes to mention this breaking change.

**Comment by alexandrudima** [comment]
@borgdylan Sorry about the nuisance, I did it to address #51.

It is a bit difficult to spot, but the release notes contains the change: https://code.visualstudio.com/Updates#_changed-defaults-and-key-bindings
