### ISSUE TITLE
Deleting huge files from explorer result in crash

### ISSUE THREAD

**Issue by frx08** [microsoft/vscode#145894]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. In the file explorer I right click on a big zip file (eg. 2gb) without opening it
2. from the right click menu I select 'delete'
3. VS Code crashes

**Comment by gjsjohnmurray** [comment]
Can you re-test this with Insiders? I think there was a recent change which might help you.

**Comment by frx08** [comment]
I confirm that with Insiders the problem is fixed. Thank you
