### ISSUE TITLE
Prioritize perfect match over substring match on code completion

### ISSUE THREAD

**Issue by tonymk** [Microsoft/vscode#14583]
- VSCode Version: 1.7.0-insider 
- OS Version: Win10

Steps to Reproduce:

1. open a typescript file 
2. write log
3. You get a lot of suggestions for autocomplete
4. I would like to use the log which matches perfect as default over SVGFEMorphologyElement, which has a log in it.

Other from that, thanks a lot for a great editor!
ps. please make it possible to copy Help -> about

**Comment by bpasero** [comment]
I am on Linux with latest insider build and I am seeing the first letter I type not being picked up. A video shows it:

 
![editors](https://cloud.githubusercontent.com/assets/900690/19762486/6c8055d6-9c3a-11e6-8318-173b3e019587.gif)

**Comment by jrieken** [comment]
this is a regression from #14446
