### ISSUE TITLE
Find widget shall be shown per split terminal

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#145865]
Testing #145629

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/10746682/159664819-43e48141-5f67-4e7e-8206-9321468c9747.png">

Find widget is shown for all split terminals which makes it confusing where I am searching. For eg., in above screenshot the wrong terminal is highlighting find results which is not matched with with text in find widget.

**Comment by Tyriar** [comment]
I think it's just the find widget was added before splits. It would make sense to do this especially now considering we needed to reimplement parts of find inside the terminal editor; it'd be easier if it was encapsulated inside TerminalInstance or XtermTerminal.

**Comment by jeanp413** [comment]
Created PR https://github.com/microsoft/vscode/pull/155361 fixing this
