### ISSUE TITLE
No Santa hat

### ISSUE THREAD

**Issue by donno2048** [microsoft/vscode#145812]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: all

The steps to get the Santa hat back (as mentioned in the "Looking forward…" section of #87440) do not work...
![image](https://user-images.githubusercontent.com/61805754/159591385-93e680d8-4048-4d5b-bafb-b98be0e431e5.png)

**Comment by chrisdias** [comment]
Sorry, this was removed once we enabled the ability for extensions to contribute Product Icon Themes, which can change the gear icon to whatever you want :) 

see https://code.visualstudio.com/api/extension-guides/product-icon-theme
