### ISSUE TITLE
Local changes sometimes disappear

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#145813]
Testing #145461

1. Have an editor open and the timeline visible beside the explorer
2. Go to the search view, and find and replace something in the file
3. Switch back to the explorer view
4. Notice that the local changes are not visible 🐛

**Comment by bpasero** [comment]
Good find, I can reproduce. However, my timeline provider is asked to `provideTimeline` and I correctly return an entry for the search and replace, so I suspect a bug in the timeline view.

**Comment by JacksonKearl** [comment]
Managed to get a solid repro for this by adding a delay to the git timeline provider's `provideTimeline` call. Found via bisect that it was fixed by this commit: 777b3866f296da18a96dfbb13423387efcb4f716

\closedWith 777b3866f296da18a96dfbb13423387efcb4f716
