### ISSUE TITLE
overview ruler Decorations are not updated when theme changes

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#145821]
Testing #145599

* Use light theme
* Run a few commands
* Switch to dark theme
* Existing decorations are not updated to the right color

**Comment by meganrogge** [comment]
This is working for me in insider's. Please reopen if you can still repro @rebornix

**Comment by Tyriar** [comment]
@meganrogge I set `"terminalCommandDecoration.successBackground": "#ff0000",` in `workbench.colorCustomizations` and it didn't change:
![image](https://user-images.githubusercontent.com/2193314/161312749-21bcbd47-9818-43a6-b56a-3cf163107ad3.png)

**Comment by meganrogge** [comment]
this is another case where I was looking at decorations instead of overview ruler decorations

**Comment by meganrogge** [comment]
https://github.com/xtermjs/xterm.js/issues/3729
