### ISSUE TITLE
Overlap of successful and failing command decorations

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#145818]
Testing #145599

<img width="66" alt="image" src="https://user-images.githubusercontent.com/876920/159596795-2b4fc30b-dad2-4a29-939d-05b6cea361ad.png">

The first command fails, the second succeeds, but their decoration has some overlap

**Comment by Tyriar** [comment]
They overlap because the scroll bar is small. See the below image which shows the y draw origin of each decoration:

![image](https://user-images.githubusercontent.com/2193314/159754642-538aec61-6762-48f6-8bb3-021af56863ff.png)

**Comment by rebornix** [comment]
@Tyriar thanks for explaining, if I understand correctly, there is min height for the decoration on the scrollbar, right?

**Comment by Tyriar** [comment]
Yep, for left/center/right it's 6px*dpr, full is 2px*dpr
