### ISSUE TITLE
Switching off high contrast removes setting

### ISSUE THREAD

**Issue by TylerLeonhardt-alt** [microsoft/vscode#145802]
Testing #145616
![Recording 2022-03-22 at 15 15 28](https://user-images.githubusercontent.com/98423974/159585337-08c37588-20a2-4302-8048-a99d692f2d9a.gif)

Basically I'm mimicking the behavior of a user who turns on OS-wide high contrast, but wants to use a specific theme in VS Code.

The odd behavior to me is that I specify a new theme color (and it's not the preferred high contrast theme) then switch off high contrast on the OS, the setting I set is removed.

I think you should only remove this setting if it's the preferred value.

This is @TylerLeonhardt's alt account on linux.

**Comment by aeschli** [comment]
We have the setting `window.autoDetectHighContrast` that controls whether themes are automatically switched.
A user that wants a specific theme can either disable that, or specify the prefferred hc theme with `workbench.preferredHighContrastColorTheme`/`workbench.preferredHighContrastLightColorTheme

**Comment by aeschli** [comment]
Agree that the user needs to learn about `window.autoDetectHighContrast`.
If that setting is on and a OS scheme change happen, we change the theme, regardless if you have changed it manually.
The old behaviour led to situation where users wouldn't understand why `window.autoDetectHighContrast` was on and would not work.

In the end I think what we have now the most predictable approach.
