### ISSUE TITLE
Duplicate panel commands for moving views

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#145856]
Testing #145634

The first two and the second two seem to do the same:
<img width="605" alt="image" src="https://user-images.githubusercontent.com/9205389/159660275-c77495b3-401b-43f1-859c-e169bd10982d.png">

**Comment by sbatten** [comment]
this is intentional to avoid breaking the likely small amount of people using keybinds for the commands, but I will remove the old version from the command palette.
