### ISSUE TITLE
VS and Code Tabs 

### ISSUE THREAD

**Issue by WebSpectrum** [microsoft/vscode#145875]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- OS Version: Windows 1.65.2

Steps to Reproduce:

1. Update to the latest version of VSCode
2. Open file with VSCode from within WinSCP (have VSCode setup as default error)

Since updating to the latest VSCode version when I open a file from within WinSCP i get two tabs opening 'VS' and 'Code.exe' which is a weird glitch, I'm posting here as it only started happening after I updated VSCode.

**Comment by aeschli** [comment]
Can you give more details how `Open file with VSCode from within WinSCP` works. Maybe some screenshots?

**Comment by WebSpectrum** [comment]
Thanks, I did a clean reinstall and it seemed to cure the issue ....

**Comment by WebSpectrum** [comment]
Just to add FYI, on the WinSCP forum, this is an issue that has been discussed previously so it isn't a single isolated incident.
