### ISSUE TITLE
Sidebar vs side bar

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#145863]
Testing #145634

Found sidebar in this setting's description, everywhere else it is side bar:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/9205389/159667331-53f33777-f279-4134-8581-1f0b3dc2ffa5.png">

**Comment by chrmarti** [comment]
Similarly, also missing 'primary', although this view can be moved around:
<img width="902" alt="image" src="https://user-images.githubusercontent.com/9205389/159668951-b21d6424-a36c-4c60-90a8-06654dc9b576.png">

**Comment by chrmarti** [comment]
"window.menuBarVisibility" also has 'sidebar' in its description and enum description. (This setting is not available on Mac.)

**Comment by sbatten** [comment]
great finds :)
