### ISSUE TITLE
Add "snapshot" button

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#145815]
Testing #145461

Often when I'm working, I'm making changes, and then realize I actually want to do something a different way but still want to use some of the code I've written. In this case, I usually `cmd+a cmd+c cmd+n cmd+v` to copy my current contents to a new file, and then hold ctrl+z to get back to an older state.

Local history could make this flow simpler, however for this I would want an explicit "snapshot" button to save the current file state before I undo it, without worrying about my changes disppearing in the `mergeWindow`.

**Comment by bpasero** [comment]
Added a new F1 command to create entries over the active editor:

![Kapture 2022-03-23 at 09 23 26](https://user-images.githubusercontent.com/900690/159655117-20aaa17f-db6b-4ccb-9c5d-1e0a86aefdc2.gif)

**Comment by bpasero** [comment]
I thought about having a button somewhere in the timeline view, but the timeline view is really limited to the active file and may also not be visible, so I went with F1 list. Let me know if you have a better idea.

//cc @daviddossett

**Comment by daviddossett** [comment]
Looks good to me!
