### ISSUE TITLE
internal html link does not jump to correct position in notebook

### ISSUE THREAD

**Issue by brandonlind** [microsoft/vscode#145809]
I believe this is somewhat related to [#103519](https://github.com/microsoft/vscode/issues/103519) and microsoft/vscode-jupyter#1330 but the examples within these issues were not implemented as I have implemented them here, and the unexpected behavior persists for my use case.

## Environment data

Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z (1 wk ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): v2022.2.1030672458
-   Python Extension version (available under the Extensions sidebar): v2022.2.1924087327
-   OS (Windows | Mac | Linux distro) and version: macOS 12.2.1 (21D62)
-   Python and/or Anaconda version: python 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...):  conda 4.8.2

## Expected behaviour - the 'description' hyperlink should jump to the id='link' cell within the notebook.
```
*in a markdown cell*
[description](#link)

*in a different markdown cell*
<a id='link'></a>
```
## Actual behaviour

The internal links do not jump to the correct position in the notebook.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by mjbvz** [comment]
Seems to work fine for me:

![Recording 2022-03-10 at 10 38 13](https://user-images.githubusercontent.com/12821956/159805499-41fe7363-e4b3-4ddd-9289-aca2fabae16a.gif)


Are you still editing the cell when trying to click the link?

**Comment by brandonlind** [comment]
Add a bunch of cells in between, it looks like there are only two cells in the notebook.

**Comment by brandonlind** [comment]
The cell is no longer in edit mode when I try and click the link.

**Comment by mjbvz** [comment]
Still works for me:

![Recording 2022-03-23 at 15 33 19](https://user-images.githubusercontent.com/12821956/159807154-da027a6c-01d5-4f67-8f56-309b3f8048e0.gif)

Are you sure you tested this in insiders (aka VS Code 1.66)? If so, share an example notebook and exacts steps to reproduce the issue

**Comment by brandonlind** [comment]
not for me

https://user-images.githubusercontent.com/8821725/159918532-d5a7171d-908c-44d8-b219-b54d415d1955.mov

**Comment by brandonlind** [comment]
Thanks, when should these capabilities be available in the normal VS Code?
