### ISSUE TITLE
Terminal find match in overview ruler doesn't update immediately when changing theme

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#145837]
Testing #145629

On Windows 11 and Linux

Changed editor.findMatchBackground and editor.findMatchHighlightBackground:

```json
    "workbench.colorCustomizations": {
        "editor.findMatchBackground": "#ff0000",
        "editor.findMatchHighlightBackground": "#00ff00"
    }
```

The color customizations worked in the regular editor but don't appear to work in the terminal find results

![image](https://user-images.githubusercontent.com/12818376/159627747-7a66d2a1-7bdd-43e1-8e13-fab3379f7045.png)

**Comment by meganrogge** [comment]
They'll work on the next search - not for existing decorations

**Comment by gregvanl** [comment]
I've never seen the colors applied. I've tried:
start a new search
close and reopen the Find widget
delete all terminals and create a new
reload the window

**Comment by meganrogge** [comment]
This is working for me in insider's. @gregvanl pls reopen if you can repro a case where that doesn't happen

**Comment by Tyriar** [comment]
We want to figure out how to redraw the canvas immediately when changing the theme when there are find results. The red bar is find results and should be green here:

![image](https://user-images.githubusercontent.com/2193314/161313304-d797bb63-799d-449f-b996-f586e28d0923.png)

**Comment by meganrogge** [comment]
https://github.com/xtermjs/xterm.js/issues/3729

**Comment by meganrogge** [comment]
fixed with #147116

**Comment by rzhao271** [comment]
I tried using Greg's colours and it seems the red got applied, but not the lime:
![A screenshot of the current terminal find result](https://user-images.githubusercontent.com/7199958/165854975-5c6463c7-7d81-464f-9253-da2d76785954.PNG)

I'm using the Night Owl Light theme.

**Comment by rzhao271** [comment]
The other match results also don't seem to have any highlighting applied.

**Comment by meganrogge** [comment]
@rzhao271 the keys have changed. what did you try?

**Comment by meganrogge** [comment]
@rzhao271 the setting name has changed. gif please

https://user-images.githubusercontent.com/29464607/165858386-9cfd94c0-cf13-45ac-a163-b3ac9d865fee.mov
