### ISSUE TITLE
Format for tsx remove some space in string

### ISSUE THREAD

**Issue by mosluce** [Microsoft/vscode#14588]
- VSCode Version: 1.6.1
- OS Version: macOS 10.12

Steps to Reproduce:
1. Follow this doc
2. and [Youtube](https://youtu.be/1Q7475lTzVw)
3. in the video, I also try it in vscode-insiders, and It's show a --jsx problem(I have added it in tsconfig.json)

**Comment by mosluce** [comment]
3. resolved when I add rootDir, outDir to tsconfig.json

**Comment by weinand** [comment]
I cannot decipher the video. Please explain the problem in words.

**Comment by waderyan** [comment]
@mosluce also please provide code we can copy and paste on our machines to reproduce the issue.

**Comment by mjbvz** [comment]
I believe this is the same issue as #13490, which is now being tracked by this TypeScript issue https://github.com/Microsoft/TypeScript/issues/11619
