### ISSUE TITLE
Add Char to status bar (besides Line and Col)

### ISSUE THREAD

**Issue by mgerner** [Microsoft/vscode#14585]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:43:46.054Z)
- OS Version: Linux x64 4.7.0-1-amd64
- Extensions: donjayamanne.githistory-0.1.0, donjayamanne.python-0.5.0, felipecaputo.git-project-manager-0.1.15, formulahendry.auto-close-tag-0.3.4, ms-vscode.cpptools-0.9.2

Steps to Reproduce:
1. Open a new file
2. If indentation is set to spaces, click the "Spaces" button in the bottom status bar to switch to tab indentation, and a tab size of 4.
3. Into the empty file, enter `[tab]23456789` (where "[tab]" is a tab character)
4. Click the Ln/Col indicator in the status bar and go to position 1,5 (line 1, column 5)
5. The cursor will now be placed between "4" and "5", indicating that the "go to line,col" command treated the tab as 1 "column", but the line/col indicator in the status bar shows "Ln 1, Col 8", indicating that it treats the tab as 4 "columns".

I can't say which is correct -- treating a tab as 1 "column" or treating it as 4 "columns" (if it is represented as 4 spaces), but my feeling is that the former is better (compilers and the like would report character counts with tabs only counting as 1, right?). However, it's clear that whichever mode should be used, the goto command and the line/column indicator should be consistent.

**Comment by alexandrudima** [comment]
Other editors, such as Visual Studio show both in the status bar:

![image](https://cloud.githubusercontent.com/assets/5047891/19769026/129567bc-9c5a-11e6-8481-688c1f5a0287.png)

The go-to works with line,char meanwhile in the status bar we show the line,col

**Comment by alexandrudima** [comment]
fyi @bpasero

**Comment by mgerner** [comment]
If the go-to is supposed to work with line,char, then you may want to change its description (if I open the goto command and type "1,5", it displays "Go to line 1 and column 5" below.

**Comment by alexandrudima** [comment]
Ahaa, I didn't realize that

**Comment by bpasero** [comment]
I am very sure this was already filed in another issue...

**Comment by bpasero** [comment]
Closing, this is nothing we would add but extensions can provide.
