### ISSUE TITLE
Terminal Find up and down arrows appeared enabled even if no matches 

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#145807]
Testing #145629

1. Create a terminal and open the Find widget.
2. Type some text that doesn't have any matches

The up and down navigation arrows are bright and look enabled even though there are no locations to navigate to.

![image](https://user-images.githubusercontent.com/12818376/159587544-65dc307e-c57e-4e86-b500-1cc4684b93da.png)

**Comment by Tyriar** [comment]
This needs https://github.com/microsoft/vscode/issues/134791 first. Assigning to April to see if we can get it done with that issue.

**Comment by rzhao271** [comment]
There is still a bit of a difference between the terminal find widget and the editor find widget when there are no find results.
1. When pressing down on the arrows in the terminal find widget, the arrows darken. When pressing down on the arrows in the editor find widget, the arrows continue to have the disabled/greyed-out look.
2. The arrow buttons in the editor find widget appear rounded whereas the ones on the terminal find widget do not.
![A screencap demonstrating the points above](https://user-images.githubusercontent.com/7199958/165641703-6a0c9cc7-41d6-4dc8-8761-4d176fe28268.gif)

**Comment by meganrogge** [comment]
@rzhao271  yep the style inconsistencies will be fixed by this https://github.com/microsoft/vscode/pull/148306

**Comment by meganrogge** [comment]
I do see that the button focus border still won't be rounded though and the arrows shouldn't be dark when clicked. Looking into it now

**Comment by meganrogge** [comment]
fixed those too https://github.com/microsoft/vscode/pull/148306/commits/f72ab1b09ce1aa19094d8740033157a28d37591c thanks @rzhao271
