### ISSUE TITLE
Startup files invoked in the wrong order for zsh with shell integration

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#145824]
startup files are invoked in the wrong order and also the wrong set of files is sourced. See https://zsh.sourceforge.io/Doc/Release/Files.html. Note that user rc files can `no_rcs` and `no_global_rcs` and it should affect the subsequent initialization process.

Sorry for not opening an issue for this.

_Originally posted by @romkatv in https://github.com/microsoft/vscode/issues/145579#issuecomment-1075809235_

**Comment by JacksonKearl** [comment]
I'm not seeing `~/.zshenv`, `/etc/zprofile`, or `~/.zprofile` get run when shell integration is enabled:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8586769/165867379-530cd24a-0322-4eea-b14e-9cfad58491a3.png">

**Comment by JacksonKearl** [comment]
![Recording 2022-04-29 at 10 36 00](https://user-images.githubusercontent.com/8586769/165994848-9418a1c4-9b34-4dc1-a6f2-e1f036fd08a7.gif)

I do not seem to see them executed in any terminal.

**Comment by meganrogge** [comment]
@JacksonKearl do you see them executed in iterm?

**Comment by meganrogge** [comment]
![Screen Shot 2022-04-29 at 10 50 31 AM](https://user-images.githubusercontent.com/29464607/165996839-bc3dcef8-6927-4828-979e-c3e58ed64c6e.png)

**Comment by JacksonKearl** [comment]
Base iTerm works, not sure how to use shell integration in iTerm.
<img width="651" alt="image" src="https://user-images.githubusercontent.com/8586769/165997123-44add2a7-1955-4d9a-b64b-b79a86246cbf.png">

**Comment by meganrogge** [comment]
It looks like you're not using a login shell so what you're seeing is expected

**Comment by meganrogge** [comment]
add this to your `profiles.osx`

```
 "zsh": {
            "path": "zsh",
            "args": [
                "-l"
            ],
            "color": "terminal.ansiCyan",
            "icon": "zap"
        },
```

**Comment by JacksonKearl** [comment]
Verified with `"terminal.integrated.defaultProfile.osx": "zsh"`, tracking not needing that in the above.
