### ISSUE TITLE
my 1 number is not working 

### ISSUE THREAD

**Issue by Gudakalyan1** [microsoft/vscode#145840]
Issue Type: <b>Bug</b>

when i try enter one while coding it will automaticly open my command pallate 

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 4650U with Radeon Graphics (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.23GB (5.88GB free)|
|Process Argv|--crash-reporter-id fff53725-17bb-4495-b46f-393a0e078ce7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
LiveServer|rit|5.7.5
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode|sal|54.5.0
salesforcedx-vscode-apex|sal|54.5.0
salesforcedx-vscode-apex-debugger|sal|54.5.0
salesforcedx-vscode-apex-replay-debugger|sal|54.5.0
salesforcedx-vscode-core|sal|54.5.0
salesforcedx-vscode-lightning|sal|54.5.0
salesforcedx-vscode-lwc|sal|54.5.0
salesforcedx-vscode-soql|sal|54.5.0
salesforcedx-vscode-visualforce|sal|54.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvidc:30447482
cppdebug:30451566
pynewfile477:30450038

```

</details>

**Comment by gjsjohnmurray** [comment]
Sounds like you accidentally set a keybinding.

I suggest you use the Command Palette (F1) to run `Preferences: Open Keyboard Shortcuts (JSON)` and look for any entries that might be intercepting the 1 character.
