### ISSUE TITLE
TypeScript (and emmet) suggestions show up in the wrong order

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#145877]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

When using [import statement completions](https://github.com/microsoft/TypeScript/pull/43149) the suggestions which come back are not always in a great order, meaning I need to cycle down a couple of times until i get what I need. This makes the development process a bit degraded compared to others IDEs.

An example is this:
<img width="1160" alt="Screenshot 2022-03-23 at 10 44 00" src="https://user-images.githubusercontent.com/936006/159684328-e07e3fdd-749f-4403-afbc-bae786549321.png">

In the image above, i want `ContentType` but the suggestions I get back are `ContentTypeHeaderStories` and an emmet suggestion. The one i want is on the 3rd row down.

I don't want to swtich emmet off but I don't think emmet should be prioritised so high above TypeScript suggestions, especially when (in this case) it's being used as a "catch all".

Secondly (and this may be more for @andrewbranch) I would expect the default export `ContentTypeHeaderStories` to be below `ContentType` and only be higher when I type `ContentTypeH..`.

Steps to Reproduce:

1. Clone https://github.com/jasonwilliams/autocomplete-testcase
2. follow steps in readme

**Comment by mjbvz** [comment]
Thanks for the repo  @jasonwilliams!

@jrieken I believe the suggestions are sorted like this due to the prefix match. `contentTypeHeaderStories` has an insert text of `import contentTypeHeaderStories ...` so it matches the text already on the line

However for `ContentType`, the insert text is `import { ContentType }` which does not match the existing text as well

This behavior makes sense once I understood it but feels confusing as a user. Any ideas on how we can work around this?

**Comment by jrieken** [comment]
The insert text doesn't matter but the filter text does. Emmet is using the line text as filter text and therefore matches fairly strong. You can see scores when pressing `cmd+/` while IntelliSense shows:

`prefix` is the text value that's selected with the completion items range, `word` is the filterText
<img width="573" alt="Screenshot 2022-03-30 at 09 11 28" src="https://user-images.githubusercontent.com/1794099/160773142-9c6410a2-71e6-4269-a4d8-ec4a5c9fe276.png">
<img width="571" alt="Screenshot 2022-03-30 at 09 11 33" src="https://user-images.githubusercontent.com/1794099/160773147-9a7be61e-98e5-438e-af67-b4a21d03c8af.png">
<img width="757" alt="Screenshot 2022-03-30 at 09 11 37" src="https://user-images.githubusercontent.com/1794099/160773151-d29c7c15-ec02-478e-826c-74d58e411982.png">

**Comment by rzhao271** [comment]
Emmet shouldn't be showing up there.
Though I feel that the most thorough fix for Emmet in this case would involve adding on a JSX parser (rather than just an HTML one), I realized the other day that I might be able to reduce the locations where Emmet suggestions show up.
For example, see https://github.com/microsoft/vscode/pull/146757

**Comment by heroboy** [comment]
I find in recent updated vscode, the emmet suggestion is always on the top.
![image](https://user-images.githubusercontent.com/54468/165783494-6d71d8db-db73-43f5-861e-c52fc24228e6.png)

**Comment by jodymgustafson** [comment]
This seems to be getting worse. When I'm creating an object and I want to see what fields are available in the type, they always show at the bottom of the list. So I have to scroll down past a large number of suggestions that don't even make sense in the context. It's very frustrating and annoying.

![image](https://user-images.githubusercontent.com/8438587/180452625-58fbe0b9-e89f-47e7-b34d-68d7268e5db9.png)

**Comment by rzhao271** [comment]
@jodymgustafson I think in your case those completions are from another extension, meaning you'll have to file a separate issue at that extension's GitHub repository.

**Comment by rzhao271** [comment]
I believe the worst offender here is the Emmet suggestion, and will close this issue in favour of the Emmet-specific issue https://github.com/microsoft/vscode/issues/51537
