### ISSUE TITLE
Disable automatic updates for specific extensions.

### ISSUE THREAD

**Issue by dibalavs** [microsoft/vscode#145845]
As you know, recently, some open source components have distruction code, which was committed by their authors/maintainers. For example, node-ipc package has code which destroy all files on computer with Russian/Belarus IP addresses.

Now I, and many many many many people cannot trust to open source.
I want to have more control for extension updates. For example, manual disable updates for some packages, which I not fully trust.

Currently I can see some settings about updates:
- Auto Update: All extensions / Only enabled /none
- Mode: default/manual/start
But I cannot find option, for disable updates for some enabled extensions, which I personally not fully trust.

**Comment by dibalavs** [comment]
Duplicate of what?
It is usually good idea to reference duplicated issue before closing.

**Comment by Chrobob-777** [comment]
Some people said they are nothing trust the open sources. So how should I do to source codes with this application?[VPN Application ](vpn.fastnet.jets) @vscode-triage-bot

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/131733
