### ISSUE TITLE
Why the createFileSystemWatcher `onDidCreate` event fired twice ? 

### ISSUE THREAD

**Issue by shezhangzhang** [microsoft/vscode#145834]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce: 

### **Why the createFileSystemWatcher `onDidCreate` event fired twice ?** 

1. event handler:
```js
let folders = vscode.workspace.workspaceFolders;
  if (folders) {
    let watcher = vscode.workspace.createFileSystemWatcher(
      new vscode.RelativePattern(folders[0], '.vscode/example.json'),
      false,
      true,
      true
    );
    watcher.onDidCreate((uri) => console.log(`created ${uri}`));
}
```
2. create file and the onDidCreate callback will be invoke:
```js
const outputFilePath = path.join(__dirname, 'example.json');
fs.writeFileSync(outputFilePath, JSON.stringify(results, null, 2));
```

3. Then I got the event fired twice:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/26793777/159623369-046536a6-ae0a-4e01-ad43-fa122aee46ee.png">

**Comment by bpasero** [comment]
Writing to a file is:
* truncating (removing all contents from the file, so that it has 0 bytes)
* writing the contents (until all data has been written)

Depending on how slow the file system is, you might see 2 events. There is a debounce of events over a short period (I think 50ms) but it may not be sufficient to cover every case.

**Comment by shezhangzhang** [comment]
> Writing to a file is:
> 
> * truncating (removing all contents from the file, so that it has 0 bytes)
> * writing the contents (until all data has been written)
> 
> Depending on how slow the file system is, you might see 2 events. There is a debounce of events over a short period (I think 50ms) but it may not be sufficient to cover every case.

Thanks! I'll do the debounce!
