### ISSUE TITLE
Antivirus not allowing to stage changes for Github under Source Control in VS Code

### ISSUE THREAD

**Issue by KendallDoesCoding** [microsoft/vscode#145839]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 2019
- OS Version: Windows 10

Steps to Reproduce:

1. Go to source control
2. Tap stage changes

**Comment by gjsjohnmurray** [comment]
Which antivirus?

Does it happen if you stage outside VS Code?

**Comment by KendallDoesCoding** [comment]
> Which antivirus?
> 
> Does it happen if you stage outside VS Code?

> Which antivirus?

> Does it happen if you stage outside VS Code?

No, although I just had a look and it seems to antivirus messed with the files there, hence may be a reason it wasn't staging, fixed the issue by disabling the antivirus.
