### ISSUE TITLE
vscode.window.tabGroups.move: Attempted to close tab with id 0 which does not exist

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#145833]
Testing #145585

Open diff editor of two images, refresh, then run: 
```ts
const activeTab = vscode.window.tabGroups.activeTabGroup?.activeTab;
			console.log('moving', activeTab);
			vscode.window.tabGroups.move(activeTab, vscode.ViewColumn.Beside, 0, true);
```

see:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8586769/159617167-b79e10e0-9069-415e-8aee-3a1926441abc.png">

**Comment by lramos15** [comment]
I think this was fixed somewhere down the line. Same code no longer reproduces the issue.
