### ISSUE TITLE
`Tab.kind` and kinds feedback

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145896]
Testing #145585

I think `tab.kind` makes good sense to me, and the different classes for each kind resonate. One thing however I am not sure about: are we in the future introducing support to create a tab too? I.e. be able to open a tab by passing in one of the kinds? If so, I wonder if `kind` is the right word to describe what previously was the `input`.

In other words, would we think that this API would exist:

```ts
window.tabGroups.createTab(new TabKindText(resource))
```

Or wouldn't it make more sense to talk about "tab construction options"?

Another aspect: `kind` to me sounds more like an enumeration that does not have more dynamic properties within. But in reality, `kind` here is an instantiated object with more properties (the resource(s)) to distinguish.

This issue is food for thought when it comes to finalization of the API, not necessarely for endgame.

//cc @jrieken

**Comment by jrieken** [comment]
Thanks for the diligence!

Yeah, the idea of them being classes is that eventually extensions can use them to create new tabs. I share the concern and something like "TabCreationOptions" or "TabOptions" have been consider and should be re-considered. That would also align with [TerminalOptions](https://github.com/microsoft/vscode/blob/0a123b02d099e973b7c3360e62a64f830193a21e/src/vscode-dts/vscode.d.ts#L10129) and how it is used/exposed

**Comment by lramos15** [comment]
It's so much more than options though especially if we decide to expose the text document for example on the text kind. I liked input more for that but I'm open to any names really

**Comment by bpasero** [comment]
My 2 cents is to keep these objects super minimal like they are in the workbench where we have "untyped editor input" that pretty much only have `Uri` and some options. 

I would have not expected to be able to access anything of the actual editor via the tab kind, specifically not the `TextDocument`. But I think that is a discussion to have then.

**Comment by jrieken** [comment]
Agreed. If we expose something content'ish then it should not be on the `kind`-property but on something else. Like visible content and it would be an editor, notebook editor, or terminal. Tho I am also still skeptical of the idea, esp. as only works for active tabs

**Comment by ArturoDent** [comment]
I would think that a primary usage of the tabs api would be a sort of tab groups manager that could store and re-create groups of tabs.  So the ability to open a resource and thus re-create the same tab as one previously saved is pretty important.

I have been wondering how one would do this for markdown previews, for example, which currently have a TabKind of `unknown` and not much info to go on to open a preview of the correct resource.

**Comment by lramos15** [comment]
> I would think that a primary usage of the tabs api would be a sort of tab groups manager that could store and re-create groups of tabs. So the ability to open a resource and thus re-create the same tab as one previously saved is pretty important.

This is not the current focus of this finalization. We will start by finalizing reading + closing tabs but opening is a whole new can of worms. Of course future proofing is important. A tabkind for webview has been added `TabKindWebview` and should allow you to know that it is a markdown preview. Actually reopening the markdown preview itself is out of the scope of this proposal and quite difficult.

**Comment by lramos15** [comment]
From a lot of API discussion it sounds like the kind name is the best and everyone is indifferent towards pretty much any name here. I don't think it's the end of the world if we introduce a create and you pass a kind object in. The other option is to call it like `TabRepresenter` or `TabInput` because it's like a seed object. Open to suggestions but we haven't come up with anything better in the meantime

**Comment by jrieken** [comment]
I kept chewing on this in the back of my head and my current preference is `Input` but I don't have very strong feelings about this

**Comment by bpasero** [comment]
I also like `Input`, but I am obviously not neutral on this because I had introduced that name to the workbench. Btw the origins are Eclipse: https://archive.eclipse.org/eclipse/downloads/documentation/2.0/html/plugins/org.eclipse.platform.doc.isv/reference/api/org/eclipse/ui/IEditorInput.html

**Comment by lramos15** [comment]
Back to input we go with https://github.com/microsoft/vscode/commit/aa69f3d7623c464aba726d12ea0d83428f43e8b9
