### ISSUE TITLE
"Local History: Find Entry to Restore" naming is inaccurate

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#145814]
Testing #145461

Based off the name, I expected "Local History: Find Entry to Restore" to actually restore the entry. But it's more of just a "Find Entry" (I may or may not actually want to store it).

**Comment by bpasero** [comment]
Understood, however I wanted to explicitly include "restore" in the command so that people that just search for how to restore something can find this. I don't think it's a big deal or source of confusion, but we can reopen if more people think the same.
