### ISSUE TITLE
technovibing terminal

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#145887]
<img width="995" alt="image" src="https://user-images.githubusercontent.com/8586769/159708999-22ebf3bc-4c70-4cda-aff5-86975eeefda4.png">
this was on my Ubuntu parallels VM, appeared when I switched back to that window (full screen).

**Comment by meganrogge** [comment]
https://github.com/microsoft/vscode/issues/110378#issuecomment-725690351

**Comment by meganrogge** [comment]
This is a bug in Chromium and we can't do anything about it
