### ISSUE TITLE
On the "clear" command, only clear decorations in the viewport

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#145816]
Testing #145599 on macOS

`clear` doesn't flush the scrollback, which means, after running `clear`

* The decorations are gone, the cursor is now at the top of the terminal
* Run another command, the decoration shows at the very bottom of the scrollbar, which is different from initial creation of the terminal

**Terminal just created, run a command**
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/876920/159596087-8db9b400-25d9-4e2f-8bbf-6a1155a11ccc.png">

**Terminal cleared, run a command**
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/876920/159596122-e70ded97-c0b6-497f-b560-30ee1ad401c0.png">

It seems this is because the scrollback is not really cleared, instead they are just pushed out of view (you can still scroll up to reveal the previous commands). Considering that the history is still in the buffer, it doesn't make sense to clear the decoration either.

**Comment by rebornix** [comment]
While if I use cmd+k to clear the terminal, it works as expected.

**Comment by meganrogge** [comment]
That's how clear works in the terminal, so believe this is as designed. @Tyriar will reopen if I'm wrong

**Comment by Tyriar** [comment]
I think better behavior would be to change this to only clear decorations in the viewport:

https://github.com/Microsoft/vscode/blob/483ec484c3814bd826d548c9623d984b1bb66fd2/src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts#L174-L180

The scrollback is immutable so the commands should remain valid. We may just need to fix any end markers to ensure they are still good.
