### ISSUE TITLE
Window Border around VS Code

### ISSUE THREAD

**Issue by mweel1** [microsoft/vscode#145925]
It would be nice if there was a border around the VS Code application.  It gets lost in dark mode with multiple windows open.

Thanks!

**Comment by meganrogge** [comment]
@misolori I tried `window.activeBorder` and `window.inactiveBorder` and neither do anything for me. Do you know who this should be assigned to?

**Comment by misolori** [comment]
`windows.activeBorder` for me on mac:

<img width="885" alt="CleanShot 2022-03-23 at 15 30 34@2x" src="https://user-images.githubusercontent.com/35271042/159806872-c4064173-7f11-4245-b4af-ab58a0bd1c26.png">

I suspect this is related to #140647, @sbatten?

**Comment by mweel1** [comment]
That worked on the PC also.  Thank you!

**Comment by meganrogge** [comment]
Strange 🤔 

![Screen Shot 2022-03-23 at 6 54 31 PM](https://user-images.githubusercontent.com/29464607/159809474-02ed2adb-f335-4188-bf46-45b601492820.png)

**Comment by mweel1** [comment]
This is on my PC,  funny thing is the bottom border doesn't work.

![image](https://user-images.githubusercontent.com/77025147/159812269-7618e3a8-297a-4098-a83c-5d7f2abd5048.png)

**Comment by mweel1** [comment]
![image](https://user-images.githubusercontent.com/77025147/159812517-59e29d16-dfa0-4db7-aa29-6ae1525ab226.png)

**Comment by sbatten** [comment]
@meganrogge can you try with a fresh user data dir?
