### ISSUE TITLE
icon display error

### ISSUE THREAD

**Issue by tanvinh152** [microsoft/vscode#145982]
Issue Type: <b>Feature Request</b>

icon display error when I import file

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
![Screenshot 2022-03-24 213738](https://user-images.githubusercontent.com/54593144/159940593-53505511-7029-43a6-8aad-03a66f093fd3.png)

**Comment by mjbvz** [comment]
What is the error?

**Comment by tanvinh152** [comment]
![image](https://user-images.githubusercontent.com/54593144/161183345-38d7af6b-c7ac-4022-b0af-995102d4a86c.png)
I mean the file icon should show like this when importing.
But it was fixed in the latest update.
