### ISSUE TITLE
console stop show logs when I debug golang project

### ISSUE THREAD

**Issue by iiimapidan** [microsoft/vscode#145966]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.2
- OS Version: win11

Steps to Reproduce:

1.golang print log immediately, console print log then stopped
2.program stopped run

a := 1
for {
	a++
	fmt.Printf("%v\r\n", a)
}

**Comment by roblourens** [comment]
Sorry, I don't quite understand the issue, can you give exact steps to reproduce it? And is this an issue for the Go extension?
