### ISSUE TITLE
Mention default set of fileNesting patterns in setting description 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#145980]
While verifying #142341 I was not aware of the fact that the setting `"explorer.experimental.fileNesting.enabled": true` comes with a full set of implicit default patterns even if no `"explorer.experimental.fileNesting.patterns"` exists in the settings.json. Only when modifying the default set, will the `"explorer.experimental.fileNesting.patterns"` setting show up.

![CleanShot 2022-03-24 at 15 23 24@2x](https://user-images.githubusercontent.com/1898161/159937995-6db0eaf1-7da9-46d2-a43d-71025c0f74e5.png)

The setting description need to make this clearer!

**Comment by JacksonKearl** [comment]
This is roughly equivalent to what the file/search exclude already does today:
<img width="776" alt="image" src="https://user-images.githubusercontent.com/8586769/161874290-8bad9c70-006f-4a2b-9fd2-f32c78df2b73.png">

**Comment by lramos15** [comment]
Closing due to following other patterns. What specifically drove you to thinking they're examples maybe we could work on polishing the settings UI.
