### ISSUE TITLE
Scroll to Top btn Bug in Release Notes

### ISSUE THREAD

**Issue by Samyak-Bumb** [microsoft/vscode#145970]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66 (Insiders)
- OS Version: Windows 10

Steps to Reproduce:

1. There is one problem in Scroll to top btn in **Release Notes**: The color is NOT Set.

 In Extension the Scroll to top btn is specified with theme color, But not in Release Notes.

**Comment by mjbvz** [comment]
@gregvanl These styles come from `inproduct_releasenotes.css`. I pushed https://github.com/microsoft/vscode-docs/commit/35b61c0a6822adae34f31a0b32e774a7ba27db00 to fix this but think this change needs to be published so we can pick it up

**Comment by gregvanl** [comment]
@mjbvz Published and looks good. 
The only surprise for me was that Solarized Dark would be transparent.

![image](https://user-images.githubusercontent.com/12818376/160040531-aeaae4f0-d14d-4bb2-902b-8df9b079934e.png)
