### ISSUE TITLE
Terminal UI issue with new Light High Contrast Theme

### ISSUE THREAD

**Issue by vpatel-gb** [microsoft/vscode#145973]
Issue Type: <b>Bug</b>

Hi,

I am like the Light HIgh Constrast Theme very much. But, noticed followign bug.

When I use the new Light High Contrast Theme. The VSCode terminal does not show highlighted text. I can highlight the text and copy it but there is no visual hint on what text I highlighted.

Thanks,
Vish

VS Code version: Code 1.65.2 (Universal) (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

**Comment by meganrogge** [comment]
The selection does look quite light
<img width="157" alt="Screen Shot 2022-03-25 at 10 34 29 AM" src="https://user-images.githubusercontent.com/29464607/160141376-ff1265bc-488f-4215-98c8-a10f3f73b391.png">

**Comment by daviddossett** [comment]
Yeah, this is a known issue. There's actually a similar, perhaps slightly less problematic contrast issue with the existing Dark HC theme:

<img width="690" alt="CleanShot 2022-03-30 at 10 03 06@2x" src="https://user-images.githubusercontent.com/25163139/160891437-88233132-9d16-479b-9485-a00272f9b104.png">

I think we need something like `TERMINAL_SELECTION_FOREGROUND_COLOR` to pair with this existing token:

https://github.com/microsoft/vscode/blob/fa2d19c9d26954efa7042f31e824d400de2783ff/src/vs/workbench/contrib/terminal/common/terminalColorRegistry.ts#L26-L31

Similar to:

https://github.com/microsoft/vscode/blob/cb3c811610f37c9dcc22f3ad8834acfd2ada5e8b/src/vs/platform/theme/common/colorRegistry.ts#L346

Thoughts @Tyriar @meganrogge?

**Comment by Tyriar** [comment]
@daviddossett what's the problem there? The foreground color of each character is changed to ensure the minimum contrast ratio is met, it's a superior system to the editor's uniform color imo. Doesn't this just need to hcLight value to be #000000 or something?

**Comment by daviddossett** [comment]
Here's how it looks if I set the background selection token to be consistent with that we use in the editor. From what I'm seeing, the terminal's foreground color isn't adjusting to meet any sort of specific ratio. Am I doing something wrong?

<img width="653" alt="CleanShot 2022-03-30 at 11 03 00@2x" src="https://user-images.githubusercontent.com/25163139/160901543-88608b5d-0a62-45c4-bff2-9530a3348cc8.png">

Here's what we have in the editor:

<img width="776" alt="CleanShot 2022-03-30 at 11 02 09@2x" src="https://user-images.githubusercontent.com/25163139/160901560-da59a59f-b3c9-488e-82e0-8c28dc38e4e0.png">

**Comment by Tyriar** [comment]
Oh I see, this would be an improvement we should make to min contrast ratio to not just go in one direction but in the other if contrast isn't met too. I created https://github.com/xtermjs/xterm.js/issues/3720 for that but we should go with the darker blue in the meantime imo

**Comment by daviddossett** [comment]
Thanks for creating that. I pushed the change to use the intended background color pictured above.

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/149495
