### ISSUE TITLE
tensorboard failed to start

### ISSUE THREAD

**Issue by yongshangli** [microsoft/vscode#145954]
vsode notification：We failed to start a TensorBoard session due to the following error: Timed out after 60 seconds waiting for TensorBoard to launch.
browser is ok，TensorBoard Integration is not
![2022-03-24 160004](https://user-images.githubusercontent.com/59642489/159869859-32c42c29-469c-4fdb-b4f6-125a41188c01.png)
. I don't why.

**Comment by IllusionMH** [comment]
/question

This is tracker for issues with VS Code editor itself.

This one looks like a general question or issue with extension(where message comes from).
