### ISSUE TITLE
Debug console suggest not accepting

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#145955]
![Kapture 2022-03-24 at 09 02 41](https://user-images.githubusercontent.com/900690/159869796-ef0777af-38b5-4405-8dfb-bece888b3f91.gif)

**Comment by roblourens** [comment]
Are you pressing tab or enter? The debug console is different than the editor here, you have to press tab, see the hint at the bottom of the suggest widget.

**Comment by bpasero** [comment]
I press `Enter`

**Comment by roblourens** [comment]
You can set `debug.console.acceptSuggestionOnEnter` to make that work
