### ISSUE TITLE
Cannot liveshare from devcontainer

### ISSUE THREAD

**Issue by crumdev** [microsoft/vscode#145924]
Issue Type: <b>Bug</b>

Live share is stuck on starting collaboration session for liveshare from inside a devcontainer

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (36.32GB free)|
|Process Argv|--folder-uri vscode-remote://dev-container%2B633a5c7372635c436c6f7564417263685c436c6f7564417263685f5465727261666f726d/workspaces/CloudArch_Terraform --crash-reporter-id 76c418a4-7083-47c0-a177-41828519cf78|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2711)|
|Memory (System)|50.09GB (44.48GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
remotehub|Git|0.26.0
terraform|has|2.21.0
vscode-peacock|joh|4.0.1
fluent-icons|mig|0.0.17
blazorwasm-companion|ms-|1.1.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.229.0
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
proto|pet|0.0.2
jinja|who|0.0.8
rainbow-brackets|2gu|0.0.6
terraform|has|2.21.0
vscode-azureterraform|ms-|0.3.2
azure-account|ms-|0.10.1
vsliveshare|ms-|1.0.5449
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvid2:30447481
pynewfile477cf:30450039

```

</details>

**Comment by lszomoru** [comment]
As this is specific to the Live Share extension, can you please file an issue in [this repository](https://github.com/MicrosoftDocs/live-share/issues)? Thank you!
