### ISSUE TITLE
VS Code is unusable! The Latest update broke it. 

### ISSUE THREAD

**Issue by alone-jpeg** [microsoft/vscode#145993]
Recently I posted about VS code not working and after disabling and re-enabling all the extensions my vs code was working pretty much almost fine with some few slow downs. 

After restart it bacame unusable again. I disbaled all the extentions, used bisect feature and reinstalled it but nothing seems to work. Even Google Chrome works smoothly but VS Code doesn't. I don't know, Either it's cuz the Java Extention Pack as I saw it had previous flare-up to slow-down vs code or VS code latest update itself. VS code was working perfectly fine before the January Update and February 2022 update completely broke my vs code. 

Either VS code had some issues with their code or something about the new update broke some extentions line. Can someone help me? :(

**Comment by mjbvz** [comment]
Please fill in the issue template 

/needsMoreInfo
