### ISSUE TITLE
Contributed command is not visible in command palette for webview panel

### ISSUE THREAD

**Issue by sathya-1994** [microsoft/vscode#145963]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create a webview using vscode API,
  webviewPanel = vscode.window.createWebviewPanel(
                        'my.webview'
                        'My Webview',
                        vscode.ViewColumn.Beside,
                        {
                            retainContextWhenHidden: true
                        }
                    );
2. Try to contribute new command to above webview panel in package.json  
{
    "command": "my.command",
    "title": "My Command",
    "enablement": "activeCustomEditorId == 'my.webview'"
}

**Issue: Contributed command "my.command" will not be visible in the command palette(we have to select webview and open command palette and search for command)**

I have used few more enablement conditions but I am not able to contribute command to webview panel.
e.x.:  "enablement": "**activePanel**== 'my.webview'", "enablement": "**focusedView**== 'my.webview'

If we contribute new custom editor then we can contribute command to its webview panel but I am creating simple webview panel.

Any way we can refer a webview panel based on its view type inside when/enablement conditions?

**Comment by mjbvz** [comment]
`activeCustomEditorId` is only set for custom editors (not regular webviews). For those you currently have to set your context keys, see `markdownPreviewFocus` in the build-in markdown extension: https://github.com/microsoft/vscode/blob/307364a17478bb2045d3fb29399f99ecb06f6cb6/extensions/markdown-language-features/src/features/previewManager.ts#L58
