### ISSUE TITLE
Window title not updated on Open Recent

### ISSUE THREAD

**Issue by 92cad2ed** [Microsoft/vscode#14591]
- VSCode Version:
Version 1.6.0
Commit e25fb0bc
Shell 1.3.7
Renderer 52.0.2743.82
Node 6.5.0
- OS Version:
Windows 7

Steps to Reproduce:

1. Open Visual studio code such that it opens the last opened project
1. File -> Open Recent
1. Select a recent project

Expected behaviour:

Window title reflects the name of the newly opened folder

Actual behaviour: 

Window title remains as the first opened project

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/14244
