### ISSUE TITLE
Debug configuration property to automatically install Chrome extensions on launch

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode#145947]
I would like to be able to add a property to the chrome debug configuration to automatically install certain extensions when launching the debug configuration.

As the debugger uses a separate profile, it won't have any extensions by default. Some frameworks like React or Vue come with a super useful devtools extension which anyone is likely to want to have when debugging such a project. As such, it would be nice to have it automatically installed according to a launch configuration property so you don't have to install it yourself the first time you debug a project, and a new chrome profile (`userDataDir`) is created.

The same applies to other browsers, should they also not support such a property (Edge, Firefox).

**Comment by weinand** [comment]
In your sentence "As the debugger uses a separate profile, it won't have any extensions by default"?
what do you mean by "profile" and "extensions"?
Are you talking about VS Code extensions or Chrome devtools extensions?

**Comment by segevfiner** [comment]
> In your sentence "As the debugger uses a separate profile, it won't have any extensions by default"? what do you mean by "profile" and "extensions"? Are you talking about VS Code extensions or Chrome devtools extensions?

I mean the Chrome profile (`userDataDir`), and Chrome devtools extensions, such as vue-devtools.

**Comment by connor4312** [comment]
Note that you can also set `userDataDir: false` to use the global user data dir. However, if you already have the browser open in a non-debug mode, this will fail.

**Comment by segevfiner** [comment]
Yeah. I know. The idea is to do this for the separately created `userDataDir`, so I can use such devtools extensions by default, without anything else dirtying the environment or having issues with multiple instances of Chrome.

**Comment by BurtHarris** [comment]
I think I've got automatic loading of a Chrome extension working through the **runtimeArgs** configuration option.  My launch.json looks like this:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "runtimeArgs": ["--load-extension=${workspaceFolder}/dist"],
            "name": "Launch Chrome against example.com",
            "url": "https://example.com",
            "webRoot": "${workspaceFolder}" ,
            "sourceMapPathOverrides": {
                "chrome-extension:.*": "${workspaceFolder}/src/*",
                "webpack:///./~/*": "${workspaceFolder}/node_modules/*",
                "webpack://?:*/*": "${workspaceFolder}/*"
        }       }
    ]
}

I am still experimenting with the "sourceMapPathOverrides" to get my source maps working, but I think this accomplishes the feature you want.
```

**Comment by segevfiner** [comment]
This one is about being able to use devtools extensions, e.g. vue devtools, rather than actually developing them.
