### ISSUE TITLE
Terminal links should require an associated mouse down event on the same link to activate it

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#145977]
Repro:

1. Write some content to the terminal
2. Make a selection and do the mouse up event on a link, it will activate it

![Recording 2022-03-24 at 06 17 17](https://user-images.githubusercontent.com/2193314/159924687-0138a82b-0b58-45ce-b024-e3ae2c2fdff3.gif)

**Comment by babakks** [comment]
@Tyriar I've just submitted a PR. I tried to keep things simple. Could you please review it?

**Comment by Tyriar** [comment]
Sorry about the delay, this issue seems to have fixed itself in the meantime.

**Comment by daiyam** [comment]
Yep, the issue has been resolved!
