### ISSUE TITLE
Leaving behind breakpoint hover decorations in notebooks

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#145928]
- Move your mouse cursor over the breakpoint margin in a notebook
- Breakpoint decorations are shown on hover, but sometimes not properly hidden when the cursor leaves the editor quickly
- This seems to just be an issue with the editor decorations, nothing special is done for notebooks here. Is that something you know about @hediet? 

![Recording 2022-03-23 at 15 04 22](https://user-images.githubusercontent.com/323878/159803682-28b3caa7-07e4-430d-a155-9c6e60632469.gif)

**Comment by hediet** [comment]
This is news to me.
Can you debug/log the mouse enter/exit events?
Maybe it's because of the iframe in the background.

**Comment by roblourens** [comment]
Can you show me where these events are for the editor?

**Comment by hediet** [comment]
It seems like `onMouseLeave` is not being called to clear the debugger breakpoint preview:
https://github.com/microsoft/vscode/blob/e8753df2e88e8982c550a9318d0b8f473fa9cf14/src/vs/workbench/contrib/debug/browser/breakpointEditorContribution.ts#L304-L306

I have no idea why.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/138789
