### ISSUE TITLE
Clearing the terminal throws off navigation selection

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#145920]
Testing #145627

![clear](https://user-images.githubusercontent.com/35271042/159773966-f8af074c-ddf7-4555-8ef0-1fd2fc973eb2.gif)

1. run a lot of commands
2. type in `clear`
3. run more commands
4. :above: as you navigate around the selection will often highlight the wrong item

**Comment by Tyriar** [comment]
Looks like we need a similar Windows workaround when clearing a screen when shell integration is disabled as well.

**Comment by Tyriar** [comment]
To verify make sure you do not have shell integration enabled. Note when verifying that the experience after clearing may be a little wonky because of https://github.com/microsoft/vscode/issues/145917, try not navigating until running clear to workaround that.
