### ISSUE TITLE
Memory leak and slow ui

### ISSUE THREAD

**Issue by mdbetancourt** [microsoft/vscode#145952]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: Linux valr 5.15.28-1-MANJARO SMP PREEMPT Fri Mar 11 14:12:57 UTC 2022 x86_64 GNU/Linux

Steps to Reproduce:

1. Clone this project https://github.com/n8n-io/n8n
2. Make some changes
3. Wait sometime and memory usage starts to raise
![Screenshot from 2022-03-24 03-15-13](https://user-images.githubusercontent.com/22435967/159863633-cf0c0b31-6284-473c-92cb-01e95a2d04a1.png)

It didn't stop until make my computer to crash (eating my all 32gb of ram)

**Comment by aeschli** [comment]
Can you follow the instructions [here](https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu) to find out which process is to blame?

**Comment by mdbetancourt** [comment]
> Can you follow the instructions [here](https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu) to find out which process is to blame?

Window process

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process describes how you can profile the Window (renderer) process.
