### ISSUE TITLE
Syntax highlighting for text/jsx

### ISSUE THREAD

**Issue by mcclda** [microsoft/vscode#145992]
Issue Type: <b>Bug</b>

When editing an HTML file, syntax highlighting for `<script type="text/javascript">` is working just fine:

![image](https://user-images.githubusercontent.com/100710489/159971700-49f23fbf-bcd0-4285-90b4-84cd282f7233.png)

But it is not working as soon as I change it to `<script type="text/jsx">`:

![image](https://user-images.githubusercontent.com/100710489/159971545-0eb64df1-a6f8-4e23-8565-f92c9c9f1c30.png)

Also:  I noticed that the "Format Document" command works on the contents of `<script type="text/javascript">` but not when it is changed to `<script type="text/jsx">`

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (5.60GB free)|
|Process Argv|--crash-reporter-id 282d362e-68be-4706-9e62-c0228a6b8475|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.3.0
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestaticwebapps|ms-|0.9.1
csharp|ms-|1.24.1
dotnet-interactive-vscode|ms-|1.0.3103011
vscode-dotnet-pack|ms-|1.0.8
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
azure-account|ms-|0.10.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvid1:30447480
cppdebugcf:30451567
pynewfile477cf:30450039

```

</details>

**Comment by aeschli** [comment]
Can you file this request against https://github.com/textmate/html.tmbundle/issues? We use the grammar from there.
