### ISSUE TITLE
Allow extensions to opt-in to pinning their Language Status Item by default

### ISSUE THREAD

**Issue by andschwa** [microsoft/vscode#145995]
_Originally posted by @andschwa in https://github.com/microsoft/vscode/issues/145950#issuecomment-1077811671_

Have talked with @TylerLeonhardt about this too. When the PowerShell extension switched from its own status bar icon to the new Language Status Item API, the user experience was forcibly changed: the PowerShell icon (with the current version) is now by default hidden under `{}` (the language status item icon), which is confusing enough to our users that we've added it to our [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#how-do-i-change-the-powershell-version) document, and have kept it in our extension's preview channel.

While I understand the rationale of having _all_ language status items under the `{}` menu, and like being able to pin each icon, it seems that extension's should be able to opt-in to pinning their icon be default so as to not overly change the existing user experience.

**Comment by jrieken** [comment]
I believe that the population of VS Code users isn't divided by "power shell" users, "fooLang" users, or "barLang" users. Instead, I believe that the population is divided by users that like feature A to be a certain way, and feature B to be a certain other way. I also believe that extension authors are naturally biased towards "their feature contributions". So, I am trying to say "no" to allowing extensions to control this and "yes" to let's consider if this could/should be a user setting.

**Comment by andschwa** [comment]
Well, the user setting is to click the "pin" button; this is more about a breaking change in behavior that _all_ are users are having to contend with.

**Comment by jrieken** [comment]
> Well, the user setting is to click the "pin" button;

No, I meant a user setting that goes "all language status items are pinned by default and need to be unpinned"

> a breaking change in behavior that all are users are having to contend with.

Well, what should I say 🤷  Yes, many people don't like changes. If you truly believe that _all_ your users are put off by this then don't make this change or only make this change for new users and let existing users chose. Python, for instance, takes a two step approach: move status to the right, later move status into the language status item. This is all up to you and 100% in your control.

**Comment by andschwa** [comment]
Hey @CsCherrYY in https://github.com/microsoft/vscode/issues/129037#issuecomment-1068650735 I think I see the confusion. I had unpinned the menu bar item "Editor Language" which you have pinned, so you see `{} Java <language status item>`, and the `Java` part is just the selected "Editor Language". The `{}` icon does look a little less weird with the language next to it!

**Comment by andschwa** [comment]
> Well, what should I say 🤷 Yes, many people don't like changes. If you truly believe that _all_ your users are put off by this then don't make this change or only make this change for new users and let existing users chose. Python, for instance, takes a two step approach: move status to the right, later move status into the language status item. This is all up to you and 100% in your control.

I didn't say "my" users I said "our" users, as in the users of VS Code and its extensions. We're already at Python's step 1, our status icon has been on the right-side (and was one of the impetuses for the development of the language status item, so all extensions can converge on this API). I'm just pointing out that (our, collective) users  of VS Code and its extensions (like PowerShell, and Python, and TypeScript) have a breaking change incoming and we should either make it _less breaking_ for them, or more documented, as the small userbase we've tested with have complained. I will point them this way if ship with it unpinned by default 😊

**Comment by CsCherrYY** [comment]
> Hey @CsCherrYY in https://github.com/microsoft/vscode/issues/129037#issuecomment-1068650735 I think I see the confusion. I had unpinned the menu bar item "Editor Language" which you have pinned, so you see {} Java <language status item>, and the Java part is just the selected "Editor Language". 

@andschwa Yeah, that's the gap here. 

> The {} icon does look a little less weird with the language next to it!

That would be the reason why the default behavior of "Editor Language" is pinned. I didn't try to unpin the "Editor Language" before🙂.

**Comment by andschwa** [comment]
FWIW after GA'ing with the language status item that is not pinned...no complaints (except the original few from our preview users) 🤷

**Comment by jrieken** [comment]
Thanks for the update
