### ISSUE TITLE
Support jumping to X of Y in Editor Find functionality

### ISSUE THREAD

**Issue by Sossenbinder** [microsoft/vscode#145953]
Currently, when using the "Find" feature in the editor, there are only a few limited ways of navigating through search results, primarily by either moving ahead or backwards.

If one works on a large file in which a search might result in >500 find hits, this can be a bit annoying. If I know that the result should be in the bottom half of my file, then my only options are:

1. Manually moving forward a few hundred times
2. Selecting the bottom half of the file (Which can get annoying performance-wise if the file is large)
3. Searching in the whole file, then clicking at the start of the bottom half, and then moving ahead in the search again (this will skip to the next entry starting from the respective position)

However, it would be great if the find functionality would just support a simple input field which would allow me to enter a number between 0 and N with N being the amount of search results, so I can just skip ahead.

**Comment by Balastrong** [comment]
Hello!

I think that's quite a useful feature and I wanted to give it a try with a PR. Please have a look :)
