### ISSUE TITLE
Terminal path

### ISSUE THREAD

**Issue by m1stik** [microsoft/vscode#145957]
Issue Type: <b>Bug</b>

The terminal in VS Code (Windows PowerShell) is using path of its location (location of the terminal) (C:\WINDOWS\System32\WindowsPowerShell\v1.0) even when I've opened a directory as a project.
Expected the terminal path to be already located in the project directory.
Such behavior of the terminal makes it inconvenient to work with paths.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.66GB free)|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.3
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvidc:30447482
cppdebugcf:30451567
pynewfile477:30450038

```

</details>

**Comment by meganrogge** [comment]
what are your terminal settings?

**Comment by m1stik** [comment]
`{
    "security.workspace.trust.untrustedFiles": "open",
    "python.defaultInterpreterPath": "C:\\Users\\Ivan\\AppData\\Local\\Programs\\Python\\Python39\\python.exe",
    "python.linting.enabled": false,
    "python.linting.pycodestyleEnabled": false,
    "python.linting.pylintEnabled": true
}`

Such a problem appears only when using Windows PowerShell
When setting Git Bash as an internal terminal, a program works as expected

Apparently, the problem is in the Windows PowerShell

**Comment by meganrogge** [comment]
Can you repro the problem in an external windows powershell?
