### ISSUE TITLE
[C++] single quotes in numeric literals are parsed incorrectly

### ISSUE THREAD

**Issue by jplatte** [Microsoft/vscode#14595]
- VSCode Version: 1.6.1
- OS Version: Ubuntu 16.04.1 LTS

Steps to Reproduce:

Open a `.cpp` file with a literal with a single quote in it:

```c++
constexpr int a = 100'000;

int main() {}
```

Expected result: The main function should be highlighted as normal.
Actual result: Everything after the single quote is formatted as if it was in a string literal.

[int]: http://en.cppreference.com/w/cpp/language/integer_literal
[float]: http://en.cppreference.com/w/cpp/language/floating_literal

See [integer literal][int] (and [floating point literal][float]) on cppreference for the details about numeric literals in C++.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#312

**Comment by weinand** [comment]
In the future please file extensions specific issues against the corresponding extension itself and not against VS Code.
