### ISSUE TITLE
Run selected text in active terminal opens a new terminal if current terminal is in editor area 

### ISSUE THREAD

**Issue by juandarias** [microsoft/vscode#145986]
Issue Type: <b>Bug</b>

1) Move terminal to the Editor area, e.g. using the command `Terminal: Move terminal into editor area`

2) Run a line of code in active terminal by using command `Terminal: Run Selected Text in Active Terminal` 

Result: This will run the code as desired in the active terminal but in addition, it will open a new and unnecessary terminal in the panel area. Furthermore, it will make the newly created terminal the active one.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.81GB (44.48GB free)|
|Process Argv|--crash-reporter-id 8799a5c7-2227-47bf-b5f4-31014027d780|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|31.26GB (27.18GB free)|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
rtf|ale|2.5.0
remotehub|Git|0.26.0
better-cpp-syntax|jef|1.15.13
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.224.3
remote-ssh|ms-|0.77.2022031115
remote-ssh-edit|ms-|0.77.2022031115
remote-wsl|ms-|0.64.2
matlab-formatter|Aff|2.9.1
matlab-interactive-terminal|apo|0.4.0
matlab-code-run|bra|1.0.2
doxdocgen|csc|1.4.0
matlab|Gim|2.3.1
latex-workshop|Jam|8.23.0
better-cpp-syntax|jef|1.15.13
svn-scm|joh|2.15.3
language-julia|jul|1.6.6
compare-folders|mos|0.22.2
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.3
jupyter|ms-|2022.2.1030672458
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
makefile-tools|ms-|0.3.1
vscode-js-profile-flame|ms-|1.0.0
explicit-folding|zok|0.21.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvid1:30447480
cppdebugcf:30451567
pynewfile477cf:30450039

```

</details>

**Comment by juandarias** [comment]
Here you have, thank you for checking the issue:

![Animatie](https://user-images.githubusercontent.com/31775008/160562387-d50d775d-460f-457d-bded-29e187971063.gif)

**Comment by Tyriar** [comment]
This is actually working by design; since you clicked the `x` button, that focused the terminal panel so the terminal within the panel was the last active terminal instance. You click click into the editor one to have it be the last active instance. Alternatively use one of these commands instead to bypass the panel all together:

![image](https://user-images.githubusercontent.com/2193314/160609238-4fd51220-8ed0-47be-883f-f0578c793589.png)

**Comment by juandarias** [comment]
It also happens if I don't click on the terminal panel:

![Animatie2](https://user-images.githubusercontent.com/31775008/160778819-1d8a383c-5ba0-43fa-ae9b-04d8eda42bed.gif)
