### ISSUE TITLE
Provide a feature for extension profiles

### ISSUE THREAD

**Issue by lakshits11** [microsoft/vscode#145908]
As you know, VS Code can be and is used for a large number of programming languages. So many people use extensions which are relatable and useful for that language only and not in other languages.
For Example: I do web dev,  C++ coding, python and jupyter notebooks, java projects etc. When I am working in c++, I don't need all web dev or python or java extensions enabled at all and taking time to load and eating memory. Presently what I do is manually disable (workspace) each unwanted extension by hand, but it literally boring job and also takes my time and I have to do that for each folder I create. I also cannot disable globally, since then I would have to enable each extension manually.

So I request you to please create a extension profile feature in which if I select a profile ( suppose webdev) only my selected and set extensions will be enabled ( that is extensions aiding in web development in vscode) and others will be disabled automatically. It will be memory efficient for low end pcs too.

Or atleast please provide an alternate solution for this. Thanks!

**Comment by lakshits11** [comment]
Atleast tell the issue number of duplicate

**Comment by lakshits11** [comment]
I tried to search with term 'extension' and also 'extension profile' and could not find anything. Please help.

**Comment by lakshits11** [comment]
Please give more info about the duplicate issue.

**Comment by gjsjohnmurray** [comment]
#40239
