### ISSUE TITLE
clang-format and clangd

### ISSUE THREAD

**Issue by FuXiii** [microsoft/vscode#145903]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.652
- OS Version: x64

Steps to Reproduce:

1.I installed clangd extension for intellisense
2. reformat the code file, the code format it not visual code style, maybe become llvm style.
3. I create .clang-format file in the project root. run the command `clang-format -style=Microsoft -dump-config > .clang-format`
4. code style not become Microsoft style

**Comment by aeschli** [comment]
I I understand right, the clangd extension provides a code formatter and your issue is about that code formatter not properly working?
Can you file the issue against the extension? https://github.com/clangd/vscode-clangd/issues
