### ISSUE TITLE
Html sample is not rendered/colored properly

### ISSUE THREAD

**Issue by jmvtrinidad** [Microsoft/vscode#14590]
- VSCode Version: 1.6.1
- OS Version: Windows 8.1

Steps to Reproduce:

1.  Download this [zip](https://github.com/googlecodelabs/your-first-pwapp/archive/master.zip) file from PWA sample.
2. Then open `work/index.html`

The coloring for this html gets wierd.
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="canonical" href="https://weather-pwa-sample.firebaseapp.com/final/">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Weather PWA</title>
  <link rel="stylesheet" type="text/css" href="styles/inline.css">
</head>
<body>
    
</body>
</html>
```

**Comment by weinand** [comment]
@jmvtrinidad why is the colouring 'weird'? If you switch to a different theme, does it look better?

**Comment by weinand** [comment]
What do you mean by "vscode seems have a conflict on line where declaring viewport"?

Sorry, but I still don't understand what you mean. Please try to explain the problem for someone who is not able to detect the error in the screenshot from above...

**Comment by jmvtrinidad** [comment]
I'm not be able to capture a screenshot of the issue, but I suspect that it is because of [aurelia-vscode-extension](https://github.com/aurelia/vscode-extension) version 0.1.9. When I try to uninstall it then it works perfectly without that weird color. I also try it to reinstall then it seems it fix my issue.

By the way thanks for great support.

**Comment by weinand** [comment]
@jmvtrinidad glad to hear that you found the issue yourself.
