### ISSUE TITLE
TypeScript formatter suddenly forgets about formatting rules

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#14599]
While developing on Code's source code, the following has happened to me twice: as I edit a file, the language service somehow forgets about the formatting rules and starts formatting everything with 4 spaces, [instead of a tab](https://github.com/Microsoft/vscode/blob/master/tsfmt.json#L5).

@jrieken suggests that

> yes - typescript has ‘forgotten’ to which project your file belongs and now uses default settings (from the default project)
> this happens after a rebase/sync/etc
> restart typescript server and you’ll be happy again

This happened during regular coding, I did not mess with rebase/sync. It literally changed mid-edit. Reloading the TypeScript didn't fix it. Only reloading the window did.

**Comment by sandy081** [comment]
I also saw this issue. I do following steps

- Reload window
- Convert to tabs manually

I felt it was my git config but do not know if it is related to it

**Comment by jedfonner** [comment]
Happens to me too on v1.7.1 on OSX.

**Comment by dbaeumer** [comment]
@jedfonner do you have any reproducible steps ?

**Comment by faisalhakim47** [comment]
it happens to me too in javascript, I cant reproduce it, because it happens occasionally after paste some code and format it. I use format on save.

**Comment by dbaeumer** [comment]
@mhegazy @vladima any idea why this happens. 

The bug came in with our update to tsserver 2.0.3. We use the formatter by setting the format options to use per file using the `configure` request. It looks like these settings can get lost in the tsserver.

**Comment by dbaeumer** [comment]
@mhegazy @vladima after our discussion today I have an idea what might cause this. Will look into fixing this on our end.

**Comment by dbaeumer** [comment]
So what I think happens is as follows:

- all files of a TS project are close
- tsserver unloads the project

However the formatter provide doesn't `unload` the fact that it needs to resent the formatting options. I added code to remove that info on file close.

**Comment by sandy081** [comment]
I have not seen this happening now. Hence marking this as verified.
