### ISSUE TITLE
Vertical resizing minimizes panel

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14594]
- VSCode Version: 1.7 Insider
- OS Version: OS X 10.11.6

![resize](https://cloud.githubusercontent.com/assets/4033249/19748785/c365b5be-9b98-11e6-99ec-47966b6ffc1c.gif)

Expected: in the gif, when dragging down, the panel should be fully resized to its previous size. The rest of space should be given to each editor group by proportion.

**Comment by bpasero** [comment]
Not anymore.
