### ISSUE TITLE
Optional quick start from snippet/template in empty files

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#145929]
> When starting a new file, I want to have the option to pick from template, so that I don't have to start from scratch and google for a boilerplate to paste in.

It happened a few times like this in user testing. Participants create a file, discover the intuitive language quick pick that the placeholder offers and are delighted 😁. With a blank file in hand they then wander off to search engines to find boilerplate to test 🤨. Some languages suffer worse than others from impossible to remember boilerplate (HTML 😭). I never saw participants using snippets or emmet as the magic fast path to fill a file quickly.

**How might we apply the placeholder text that allows picking a language to also picking a template:**

_Starting with an _untitled buffer_:_
1. Create untitled buffer
2. Placeholder text offers to pick a language -> Quick pick `HTML`
3. Placeholder text offers to start from a template --> Quick pick `html!!`
4. 🎉

_From creating an empty file in the workspace:_
1. Create new `index.html` file in _Explorer_ and open it.
2. Placeholder text offers to start from a template --> Quick pick `html!!`
3. 🎉

Snippets could be the existing system to provide those templates. They already have a `prefix` and `description`, which can be used in the quick pick. Their placeholders can also help to quickly name a component that is being created, set a title, etc.

cc @stevencl @sana-ajani 

Ideas:
- The quick pick selection could also preview the snippet as ghost text.
- Easter egg for pasting a little HTML game or spinning VS Code logo.

**Comment by digitarald** [comment]
Related user feedback: https://github.com/microsoft/vscode/issues/145046#issuecomment-1080480826

**Comment by jrieken** [comment]
@digitarald Let's discuss but the implementation has to wail till July

**Comment by digitarald** [comment]
Examples from the wild:

General extension issue causing spam: https://github.com/ritwickdey/vscode-live-server/issues/2460
Performance issue without profile causing extra work: https://github.com/aws/aws-toolkit-vscode/issues/2703

**Comment by jrieken** [comment]
* for snippets add `"isTopLevel": true` property
* new file flow (plaintext): add to existing ghost text, "start from snippet" which shows all snippets of languages and sets both: language and snippet
* Also, automatically populate new files with configured snippets. Have user/workspace setting that links langId to snippet-source or snippet-reference
* update built-in snippets with this new feature
* ping extension authors

**Comment by jrieken** [comment]
With https://github.com/microsoft/vscode/pull/155321 (a bigger PR with some other things as well)

https://user-images.githubusercontent.com/1794099/179263194-4c609641-21a0-4eed-a888-100cfc93fb84.mov

@digitarald I believe we should reconsider the `isTopLevel`-name. Maybe be all explicit and name it "isForEmptyFile" or so 🤷

**Comment by hahn-kev** [comment]
I like `newFileSnippet` or `fileSnippet` all snippets can be templates already (meaning they have a variable that gets substituted at evaluation time) so I'm not sure using the word template is helpful here.

**Comment by jrieken** [comment]
We went with `isFileTemplate`

**Comment by jrieken** [comment]
To verify:

* have a custom or contributed snippets that uses the `isFileTemplate`-property (see below)
* run F1 > Populate File From Snippet
* verify that it replaces the file contents the selected snipppet _and_ that it sets the language 
* verify it only sets the language when the snippets defines one (via scope for *.code-snippets files)
* invoke code actions (cmd+.) in an empty file and make sure there is a code action for each template snippet

```
"css-template": {
"isFileTemplate": true,
"scope": "css,javascript",
"body": [
	"* {",
	"\tcolor: ${1:green};",
	"}",
]
},
```

**Comment by andreamah** [comment]
I find that files that are out-of scope are also allowing for code snippets. I made a txt file for your example above and it still allowed me to paste it in.
![Recording 2022-07-27 at 11 14 27](https://user-images.githubusercontent.com/31675041/181343445-221ab60b-d6c1-4859-a34c-16269cc5f532.gif)

**Comment by jrieken** [comment]
> I find that files that are out-of scope are also allowing for code snippets.

It will always show all "file snippets" but it will only update the language mode if the snippets defines one. The point of the feature is to populate the (empty) file with contents and set the corresponding language. That why there is no filtering

**Comment by rzhao271** [comment]
When I insert the JS snippet in a new empty file, the language changes to JS, but then auto-detection changes it back to CSS.

**Comment by hinell** [comment]
Please, update documentation on this feature in the related documentation:
* [VSCode # Userdefinedsnippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets)

I also request to update every new snippet header file to:

```js
// ...
// "Print to console": {
// 	"scope": "javascript,typescript",
//     "isTopLevel": true,
// 	"prefix": "log",
// 	"body": [
// 		"console.log('$1');",
// 		"$2"
// 	],
// 	"description": "Log output to console"
// }
```
