### ISSUE TITLE
Playwright: page.pause() not working in terminal

### ISSUE THREAD

**Issue by dfdumaresq** [microsoft/vscode#145936]
Issue Type: <b>Bug</b>

1. Install Playwright and add `await page.pause()` in one of the example tests or copy the code below onto the example test.
2. run within an integrated terminal. 
3. `$ npx playwright test --project=chromium --headed`
4. notice the test does not pause
![image](https://user-images.githubusercontent.com/20051/159816003-0c5e6b21-efb0-4c45-82a3-47510433a7f2.png)

1. Next, open an standard terminal and perform the same test. 
2. `$ npx playwright test --project=chromium --headed`

![image](https://user-images.githubusercontent.com/20051/159815805-e57e2eeb-111f-4781-a94a-9ce68f910224.png)

```typescript
import { test, expect, Page } from '@playwright/test';

test.beforeEach(async ({ page }) => {
  await page.goto('https://demo.playwright.dev/todomvc');
});

const TODO_ITEMS = [
  'buy some cheese',
  'feed the cat',
  'book a doctors appointment'
];

test.describe('New Todo', () => {
  test('should allow me to add todo items', async ({ page }) => {
    // Create 1st todo.
    await page.locator('.new-todo').fill(TODO_ITEMS[0]);
    await page.locator('.new-todo').press('Enter');

    // Make sure the list only has one todo item.
    await expect(page.locator('.view label')).toHaveText([
      TODO_ITEMS[0]
    ]);

    // Create 2nd todo.
    await page.locator('.new-todo').fill(TODO_ITEMS[1]);
    await page.locator('.new-todo').press('Enter');

    await page.pause();

    // Make sure the list now has two todo items.
    await expect(page.locator('.view label')).toHaveText([
      TODO_ITEMS[0],
      TODO_ITEMS[1]
    ]);

    await checkNumberOfTodosInLocalStorage(page, 2);
  });

});

async function checkNumberOfTodosInLocalStorage(page: Page, expected: number) {
  return await page.waitForFunction(e => {
    return JSON.parse(localStorage['react-todos']).length === e;
  }, expected);
}
```

Here's an example in Typescript
```
const { test, expect } = require('@playwright/test');
test('basic test', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navbar__title');
  await expect(title).toHaveText('Playwright');

  await page.pause();
});
```

VS Code version: Code 1.65.2 (Universal) (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.87GB free)|
|Process Argv|--crash-reporter-id 161e5da9-f592-4143-baa2-0a9d01a1bfab|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvidc:30447482
pynewfile477cf:30450039

```

</details>

**Comment by dfdumaresq** [comment]
I've removed my settings.json and that fixed my issue. Playwright  will now pause. Any suggestions about what to look for in the settings.json?

**Comment by dfdumaresq** [comment]
Changing "always" to "smart" seems to fix things. 

`"debug.javascript.autoAttachFilter": "smart",`

**Comment by Tyriar** [comment]
Ok it looks like this was VS Code's debug session via auto attach conflicting with Playwright's debug session. The playwright extension may want to detect this case? FYI @connor4312.

**Comment by dfdumaresq** [comment]
FYI @Tyriar, @connor4312, I was not using any extensions.

**Comment by Tyriar** [comment]
Oh right, playwright debug session, not their extension.
