### ISSUE TITLE
Dev Containers terminal output no longer displays each line as it gets written

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#145974]
Issue Type: <b>Bug</b>

1. Open a local workspace that contains a `.devcontainer/devcontainer.json` file specifying how to run it in Docker Desktop.
2. When the notification appears, choose to reopen the workspace in the container.
3. When the progress notification appears, click on its link to show the log.

![image](https://user-images.githubusercontent.com/6726799/159921378-2c9d9a2d-8b36-4e59-bfa5-f60cc228f3ac.png)

A terminal titled "Dev Containers" displays in the Terminal tab of the panel, but its content doesn't display until the startup completes.

By comparison, when I do this on 1.65.2 the startup messages stream into the terminal display.

I decided not to log this on the extension repo as it seems to be a regression.

VS Code version: Code - Insiders 1.66.0-insider (2eebd2a0159af379057a58c8bcb519f95bfd6328, 2022-03-23T05:14:59.126Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

**Comment by chrmarti** [comment]
I think this is https://github.com/microsoft/vscode/issues/144729. Does it work when you disable shell integration?

**Comment by gjsjohnmurray** [comment]
Yes it does. :+1:

/duplicate
