### ISSUE TITLE
Go To description mentions line, column but it should be line, character

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#14598]
Extracted from https://github.com/Microsoft/vscode/issues/14585#issue-185619632

**Comment by bpasero** [comment]
@alexandrudima in the end I am passing a Range to the editor with start line number and start column (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/quickopen/browser/gotoLineHandler.ts#L98). Are you saying that this API talks about characters and not columns?

**Comment by alexandrudima** [comment]
@bpasero I haven't seen a screenshot, but apparently there is somewhere some UI string the widget shows that mentions "column". That UI string should mention "character". 

@mgerner  Can you please include a screenshot.

**Comment by bpasero** [comment]
@alexandrudima it is this one:

<img width="804" alt="screen shot 2016-10-27 at 17 29 54" src="https://cloud.githubusercontent.com/assets/900690/19773743/fecd0850-9c6a-11e6-8e0c-ba271064a005.png">

So when I pass a startColumn to the editor it will actually put it at the character position I give it?

**Comment by alexandrudima** [comment]
@bpasero Please change your nls string such that it shows:
"Go to line 45 and character 34"

**Comment by bpasero** [comment]
<img width="1292" alt="screen shot 2016-10-27 at 17 55 57" src="https://cloud.githubusercontent.com/assets/900690/19774827/a4645bc6-9c6e-11e6-8704-2691effd051d.png">

I fixed the one in goto line quick open but I still see more places where we talk about column when it should maybe be character?

Bouncing back to you to decide if those are valid. I think they are in markers land mainly.

**Comment by alexandrudima** [comment]
Thank you. The editor configurations talk about the correct columns. i.e. a ruler at column 4 will be rendered possibly after character 1 if that character is 4. Same is for wrappingColumn.

giving to @dbaeumer and @sandy081 to think about their use-cases.

**Comment by dbaeumer** [comment]
Makes sense to me to use character consistently.

**Comment by sandy081** [comment]
To me too.

**Comment by sandy081** [comment]
Changed it for markers panel.

**Comment by dbaeumer** [comment]
Fixed except for the cases where the doc was referring to properties. Since these properties are API and I didn't want to break the API I left them with column.

**Comment by chrmarti** [comment]
`gotoLine.ts` has 3 occurrences of 'column'. argv.ts has 3 related to 'go to line'. Reopening.

**Comment by dbaeumer** [comment]
As discussed assigning to you.
