### ISSUE TITLE
The search window is not limited to the current project

### ISSUE THREAD

**Issue by Mark531** [microsoft/vscode#145964]
Does this issue occur when all extensions are disabled?: Yes/No
I cannot disable all extensions because I need to use remote SSH to have access to my project.

- VS Code Version: 1.65.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open a project in remote SSH
2. Type some string in the search window
3. The string is searched on the whole machine, not the project, which causes the search to last for more than 30 min

**Comment by roblourens** [comment]
Do you have a path in the `files to include` box?

Can you share a screenshot?

**Comment by Mark531** [comment]
Here is a screenshot, I didn't modify anything in the search box.
![image](https://user-images.githubusercontent.com/17707763/160355663-0335f6b1-2f26-4cd7-b2de-fcdb5def07b1.png)

**Comment by roblourens** [comment]
This looks like a file in your workspace, it would be at `./sku_potential_forecast/dataprep.py`

**Comment by Mark531** [comment]
Sure, the search window returns results from all the machine. Is it possible to restrict the search to a project?

**Comment by roblourens** [comment]
> Is it possible to restrict the search to a project?

This is what happens by default. It would be helpful to share a screenshot showing the issue, otherwise I can't really help. 

If search is leaving the workspace, maybe you have a symlink pointing outside of the workspace.
