### ISSUE TITLE
How to install plugins!!

### ISSUE THREAD

**Issue by crperlin** [Microsoft/vscode#146]
Such as editor plugins : Emmet!! ,jsformat l

theme !!!

thanks~~

**Comment by Yelmond** [comment]
In the top menu, go to **View > Command Palette...**. Now type "`ext`" and select the first option which should be **Extensions: Install Extension**. You can now search the Gallery for an extension by name or simply "theme" to search themes.

I do agree that a menu entry to go directly to this extension search mode would be a bit more intuitive but feature requests seem to be directed to VS Code's UserVoice here: https://visualstudio.uservoice.com/forums/293070-visual-studio-code

Here's some docs on the matter:
* Installing themes from Extensions Gallery: https://code.visualstudio.com/docs/customization/themes#_adding-themes-from-the-extension-gallery
* Extension Docs: https://code.visualstudio.com/docs/customization/themes
