### ISSUE TITLE
My vs code won't start a completely new projects

### ISSUE THREAD

**Issue by mwikalikyalo** [microsoft/vscode#146035]
Issue Type: <b>Bug</b>

When I open a new project i keep having a previous project's changes reflecting in my new project. I would like for the file theracare to be deleted from my vs code.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.13.0-35-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 1734)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.65GB (2.98GB free)|
|Process Argv|--unity-launch --crash-reporter-id 3884c079-2868-4ede-8b86-25b0f7a7ebb8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|13.3.0
vscode-color|ans|0.4.5
bracket-pair-colorizer|Coe|1.0.62
prettier-vscode|esb|9.3.0
auto-rename-tag|for|0.1.10
code-runner|for|0.11.7
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.5.0
icon-fonts|idl|2.5.3
vscode-colorize|kam|0.11.1
JavaScriptSnippets|lba|1.8.0
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.3
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
vsliveshare|ms-|1.0.5449
LiveServer|rit|5.7.5
vscode-wakatime|Wak|18.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
cppdebug:30451566
pynewfile477cf:30450039

```

</details>

**Comment by aeschli** [comment]
Can you add a screenshot that show how the old changes show up in the new project?
