### ISSUE TITLE
HC Light: GHPR description view buttons blank

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#146015]
<img width="949" alt="image" src="https://user-images.githubusercontent.com/8586769/160030812-dcd8a909-79ee-46ed-8194-d58291062feb.png">

**Comment by daviddossett** [comment]
I've had a PR open for this: https://github.com/microsoft/vscode-pull-request-github/pull/3343

cc @alexr00

**Comment by alexr00** [comment]
@daviddossett I had a question for you in that PR, but I do want to merge it!

Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3342
