### ISSUE TITLE
Higher version required for github copilot

### ISSUE THREAD

**Issue by bfgelectronics** [microsoft/vscode#146081]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: Arch Linux

Steps to Reproduce:

1. Download the Github Copilot Extension
2. Log in to the extension 
3. Get greated with the notification: `GitHub Copilot requires VS Code 1.57+. Please update your VS Code`

**Comment by lszomoru** [comment]
Can you please post your feedback in [the Copilot GitHub Discussion](https://github.com/github/feedback/discussions/categories/copilot-feedback). Thank you!
