### ISSUE TITLE
Allow `createFileSystemWatcher` to bypass `files.watcherExclude` for flat watching

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#146066]
We recently added support to create file watchers for folders including recursive watching. However, a misconfigured `files.watcherExclude` could result in events not being delivered to the extension.

One idea would be to simply ignore user configured file watcher excludes when the file watcher was created from an extension and only if the file watcher is not recursive. The setting was mainly targeted for reducing the overhead of the recursive watcher and is less useful for flat watchers.

The challenge though is that the implementation would then have to install new file watchers on top of the existing recursive one. This means that a change to a file can now result in multiple file events from different watchers that are installed. We could try some kind of deduplication but we don't really know when the one file watcher emits an event and when the other does.

**Comment by lszomoru** [comment]
Here is [an example](https://github.com/microsoft/vscode/issues/139656) of two users having git related issues due to misconfigured settings.

**Comment by bpasero** [comment]
@lszomoru the change to move to `createFileSystemWatcher` [landed](https://github.com/microsoft/vscode/commit/044092db5597de273b8fe7030332ec3454043102) Jan 14 2022, but https://github.com/microsoft/vscode/issues/139656 was reported 22 Dec 2021, so it cannot be related originally.
