### ISSUE TITLE
`extensionKeys` are never cleaned up

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#146048]
Noticed how my SQLite DB has tons of rows for these:

![image](https://user-images.githubusercontent.com/900690/160116159-b8238759-11d5-4e35-8a02-05e69c4c7c9c.png)

If an extension version uninstalls, associated storage should be deleted as well.

Besides, I don't fully understand the need for the version as part of the key, couldn't this be a JSON object within and the key left stable?

**Comment by sandy081** [comment]
Clean up is called now on every start up to remove these outdated/non-existing keys.
