### ISSUE TITLE
eclipse keymap ?

### ISSUE THREAD

**Issue by rijine** [Microsoft/vscode#1460]

**Comment by rijine** [comment]
like,
[
    {
        "key": "ctrl+shift+c",
        "command": "editor.action.commentLine",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+d",
        "command": "editor.action.deleteLines",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+k",
        "command": "editor.action.addSelectionToNextFindMatch",
        "when": "editorFocus"
    },
    {
        "key": "alt+shift+2",
        "command": "workbench.action.splitEditor"
    },
    {
        "key": "ctrl+shift+f",
        "command": "editor.action.format",
        "when": "editorTextFocus"
    },
]

**Comment by bpasero** [comment]
@rijine can you clarify please what you are asking for?

**Comment by rijine** [comment]
eclipse keybinding, so that i can use same keys in vscode also.
like, https://github.com/enlangs/vscode-eclipse-keybindings

**Comment by bpasero** [comment]
You can change keybndings within VSCode, did you do that?

**Comment by bpasero** [comment]
Please reopen if you need more help.
