### ISSUE TITLE
Ctrl+Shft+P shortcut not working

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/vscode#146061]
Issue Type: <b>Bug</b>

I really don't know how to reproduce this.
It also does not work with extensions disabled.

I have tried to remove the mapping to Show All Commands.  When I tried to remap this command in the UI, it would not allow me to type Ctrl+Shft+P, but my P key is definitely NOT broken.  There were also a seemingly random selection of other keys that the UI keyboard mapper would not accept.

I cleared out the mapping in the JSON keyboard settings to restore it to default and it shows it mapped when I bring up keyboard settings in the UI and when I display the palette with Ctrl+, and type >.

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (16.03GB free)|
|Process Argv|--crash-reporter-id f98b4540-53af-4472-8651-57333f87f83b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
libman|adr|1.0.1
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.5
EditorConfig|Edi|0.16.4
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|9.4.0
auto-rename-tag|for|0.1.10
rest-client|hum|0.24.6
better-cpp-syntax|jef|1.15.13
vscode-nuget-package-manager|jmr|1.1.6
react-native-snippet|jun|0.5.6
compare-folders|mos|0.22.2
vscode-docker|ms-|1.21.0
csharp|ms-|1.24.1
vscode-edge-devtools|ms-|1.4.6
remote-containers|ms-|0.224.3
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
azure-account|ms-|0.10.1
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
powershell|ms-|2021.12.0
test-adapter-converter|ms-|0.1.5
vsliveshare|ms-|1.0.5449
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.9.2
vetur|oct|0.35.0
vscode-jest|Ort|4.2.1
vscode-nuget-gallery|pat|0.0.24
vscode-coverage-gutters|rya|2.9.1
code-spell-checker|str|2.1.7
es6-string-html|Tob|2.12.0
cmake|twx|0.0.17
vscode-icons|vsc|11.10.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvidc:30447482
pynewfile477cf:30450039

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please follow steps from https://github.com/microsoft/vscode/wiki/Keybinding-Issues to see if VS Code even receives this shortcut or it is intercepted by system/other app.
