### ISSUE TITLE
Debugging doesn't start without any error messages when trying to debug C code using WSL

### ISSUE THREAD

**Issue by ClaudiusKa** [microsoft/vscode#146034]
Issue Type: <b>Bug</b>

Hi!

I'm trying to debug C code using VS Code in combination with WSL (Ubuntu-20.04) and a gdb debugger but despite having double checked my launch.json file, the process aborts after the debug toolbar appears for approximately half a second without any error messages. The weird part is that I didn't have any problems debugging in the past but a few days ago it suddenly stopped working.

WSL is working properly in the command prompt as well as in the VS Code terminal, so I guess WSL isn't causing the problem. Executing the C file in the command prompt using WSL is working fine as well, which is why I think VS Code is causing the issue.

Things I tried so far:
- un and reinstalling my extensions as well as VS Code
- switching to VS Code Insiders
- editing my settings.json file to {"terminal.integrated.shell.windows": "C:\\Windows\\System32\\bash.exe"} 
- obvious, but perhaps worth mentioning: rebooting my PC
- debugging manually using "gdb filename" in the VS Code terminal which is working properly

If you need any additional information just let me know.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (20.96GB free)|
|Process Argv|--crash-reporter-id a6dfd0b5-b9fd-4439-a20c-90c82835b0fb|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|Memory (System)|24.88GB (24.31GB free)|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.64.2
cpptools|ms-|1.9.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvid1:30447480
cppdebugcf:30451567
pynewfile477cf:30450039

```

</details>

**Comment by mzient** [comment]
For me, this happens between two native Linux machines. It used to work and then just stopped. There's no error message, the debugger process simply isn't started (or terminates immediately) on the remote matchine.
