### ISSUE TITLE
Sometimes autoComplete words deleted the next letter

### ISSUE THREAD

**Issue by MohammadAminZamaniAfshar** [microsoft/vscode#146065]
Does this issue occur when all extensions are disabled?: Yes, except dart and flutter

- VS Code Version: 1.65.2 (user setup)
- OS Version: Windows_NT x64 10.0.19044

https://user-images.githubusercontent.com/88077166/160160121-2fefc2f5-8e38-4807-ae79-56eb2efa2abe.mp4

### How can i fix it?

Thanks

**Comment by jrieken** [comment]
What language is this? What extension is providing the auto completion entries? Does this repo when that extension is disabled

**Comment by MohammadAminZamaniAfshar** [comment]
This is Flutter framework which uses dart language.
Just Dart and Flutter extension was enable
I think that extension is Flutter extension and no it was enable bc it's necessary

**Comment by jrieken** [comment]
> I don't know but i think it's not related to these extensions becuase text2 is just a local variable

It is. Extension tell us what to overtype
