### ISSUE TITLE
Source control directs user to install git for Windows when on Linux

### ISSUE THREAD

**Issue by andrewward2001** [microsoft/vscode#146093]
Issue Type: <b>Bug</b>

1. Fresh install of VSCode via Ubuntu Software app
2. Open VSCode
3. Click Source Control
4. Click "Download Git for Windows" - expected "Download Git for Linux"

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.13.0-37-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (4 x 3593)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 1, 1|
|Memory (System)|3.80GB (0.11GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvid1:30447480
pynewfile477cf:30450039

```

</details>

**Comment by hello-smile6** [comment]
Attempting to reproduce using https://6080-traversaro-gitpodubuntu2-na5z0vtjrr8.ws-us38.gitpod.io/vnc.html?autoconnect=true&reconnect=true&reconnect_delay=1000&resize=scale&quality=9

**Comment by lszomoru** [comment]
@andrewward2001, could you please post a screenshot/gif? Thank you!

**Comment by andrewward2001** [comment]
On second look, the title doesn't properly reflect the issue. Clicking the button directs the user to the Git downloads page online, but the button still says "Download Git for Windows"


![Screenshot from 2022-03-28 19-45-50](https://user-images.githubusercontent.com/3325089/160522945-c4bf8e4f-2644-426d-bd35-fb448255c83a.png)

**Comment by andrewward2001** [comment]
The button in the Source Control menu which says "Download Git for Windows" directs the user to the [Windows-specific download page](https://git-scm.com/download/win). However, the popup in the lower-right corner directs the user to the [platform-agnostic download page](https://git-scm.com/downloads).

![Screenshot from 2022-03-28 19-46-4512](https://user-images.githubusercontent.com/3325089/160524010-371ba851-37b7-475e-93d5-58efdd08f9a2.png)

**Comment by lszomoru** [comment]
@digitarald, is this something that you could take a look at? Thank you!

**Comment by hello-smile6** [comment]
Text source appears to be here.
https://github.com/microsoft/vscode/blob/c13a518ffd88fb2ecb3ba2348abffb98c33ef6ba/extensions/git/package.nls.json#L225

**Comment by hello-smile6** [comment]
Found the source of the problem.
https://github.com/microsoft/vscode/blob/b8a5e18171718af676e2bcacfb0dbe5e89b62e43/extensions/git/package.json#L2418-L2421

**Comment by hello-smile6** [comment]
Bug introduced in a9e136f1f466a8e5e53e9960a306f82acfd8b984

**Comment by lszomoru** [comment]
Thanks @hello-smile6 for submitting a fix.

**Comment by connor4312** [comment]
The button now says "Download Git for Linux", which is correct, but it links to the page for downloading Git on OS X.

**Comment by hello-smile6** [comment]
> The button now says "Download Git for Linux", which is correct, but it links to the page for downloading Git on OS X.

Does it ever end?

**Comment by connor4312** [comment]
Turtles all the way down 🐢 

Looks like @digitarald fixed this in his commit
