### ISSUE TITLE
typescript dies unexpectedly

### ISSUE THREAD

**Issue by RaniqueTedder** [microsoft/vscode#146087]
Issue Type: <b>Bug</b>

received message that typescript died and will not run local host, restart vs code and computer without success

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1072-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics     (8 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.87GB free)|
|Process Argv|--crash-reporter-id ba135cb2-51cc-42af-9e9b-1755aa92e139|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1072-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (8 x 2593)|
|Memory (System)|15.63GB (0.20GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.4
codespaces|Git|1.5.7
gitkraken-authentication|git|1.0.3
path-intellisense|chr|2.8.0
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.5
prettier-vscode|esb|9.4.0
codespaces|Git|1.5.7
vscode-pull-request-github|Git|0.38.1
vscode-graphql|Gra|0.3.52
vscode-docker|ms-|1.21.0
color-highlight|nau|2.5.0
indent-rainbow|ode|8.2.2
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.14.1
velocity|sod|0.2.0
code-spell-checker|str|2.1.7
appsync-resolver-autocomplete|the|1.6.0
serverless-ide-vscode|Thr|0.5.33
vscode-svg-previewer|vit|0.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
pynewfile477cf:30450039

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
