### ISSUE TITLE
Workbench services should self-register

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#146027]
There should be no reason why these 2 cannot self register like the other workbench services above:

https://github.com/microsoft/vscode/blob/939b896aad5b8c5829432c26cd342272366a17dc/src/vs/workbench/workbench.sandbox.main.ts#L85-L91

Please align if possible.

The only reason why it may not be possible to self-register is if these files are somehow dependent on from desktop too, e.g. via inheritance. In that case I typically create an abstract super type to depend on.

**Comment by bpasero** [comment]
Looks like a few more for web:

https://github.com/microsoft/vscode/blob/f592d91cf36297727f5bfc8708ac524739f36fac/src/vs/workbench/workbench.web.main.ts#L87-L90

**Comment by sandy081** [comment]
Following services are registered in this file mainly because 

- IUserDataInitializationService: It is created as a start up service in web where are as a normal service in desktop.
- IUserDataSyncEnablementService: has different implementations for web and desktop.

Not sure about other two services  `IConfigurationResolverService` and `IDiagnosticsService`

**Comment by sandy081** [comment]
@bpasero do you want me to close this or would you like to transfer ownership for other services?

**Comment by bpasero** [comment]
The issue title is "should", so I would say that it is really up to service owners if they want to self register or not. I only reported this because I noticed that some services that live in `workbench` would not self register while most others actually do. We tend to only have `platform` services not self register because they are used in other contexts too where this may not be supported.

**Comment by sandy081** [comment]
Fixed it for `IUserDataSyncEnablementService` and assigning corresponding owners for other services

**Comment by alexr00** [comment]
Fixed it for `IConfigurationResolverService`.

**Comment by JacksonKearl** [comment]
I think I was assigned for `IAccessibilityService`? Leaving that alone as it is a `platform` service which I understand to be allowed to self-register.
