### ISSUE TITLE
[MacOS] When used native tabs, title bar style changes

### ISSUE THREAD

**Issue by ragokan** [microsoft/vscode#146079]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: macOS Monterey 12.3

Steps to Reproduce:

1. When I set the setting   `window.nativeTabs` to `true`, the title bar style changes. Even thought I set the `titleBarStyle` to `custom`, it does not get updated.

A (when native tabs is true):
![used](https://user-images.githubusercontent.com/63511519/160179775-7926b716-40ed-4191-92bc-9316aa78db20.png)

B (when false):
![notused](https://user-images.githubusercontent.com/63511519/160179809-38ab0278-8609-4762-887c-cc9ce939ff17.png)

I basically want it to show like B even though I set the `nativeTabs` to `true`.

(In some themes, it looks even more weirder)
![image](https://user-images.githubusercontent.com/63511519/160180070-20d196b9-b90d-4628-ace1-764f0b663633.png)

**Comment by sbatten** [comment]
This is expected and described in the setting description:
> Enables macOS Sierra window tabs. Note that changes require a full restart to apply and that native tabs will disable a custom title bar style if configured.

**Comment by ragokan** [comment]
> This is expected and described in the setting description:
> 
> > Enables macOS Sierra window tabs. Note that changes require a full restart to apply and that native tabs will disable a custom title bar style if configured.

I see but isn't there any way to enable custom title bar again? Even a workaround would be amazing.

**Comment by sbatten** [comment]
cc @bpasero in case anything has changed since this was disabled.
