### ISSUE TITLE
too many http redirects

### ISSUE THREAD

**Issue by rsadeh-dn** [microsoft/vscode#146099]
Issue Type: <b>Bug</b>

i'm running vscode 1.63.x
trying to update it fails with "too many http redirects" error.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|32.00GB (18.23GB free)|
|Process Argv|--crash-reporter-id 1c49a797-b3e7-4990-ab81-57236abb41e0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.15.13
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.3
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.63.13
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.9.7
jinjahtml|sam|0.17.0
cython|tcw|0.1.0
jinja|who|0.0.8

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvid1:30447480
pynewfile477:30450038

```

</details>

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the error?

**Comment by joaomoreno** [comment]
Interesting, any thoughts @deepak1556?

@rsadeh-dn Are you in a corporate network, behind a proxy maybe?

**Comment by rsadeh-dn** [comment]
This happens to me both in the office but also at home and not on any vpn.
My work MAC does have corporate "tools" installed such as Zscaler and Falcon but this problem is not experienced by everybody in the office (although obviously i didn't ask "everybody")

**Comment by joaomoreno** [comment]
@deepak1556, any chance we can trace the Squirrel update network requests?

**Comment by rsadeh-dn** [comment]
guys, thanks.  i gave up on this.  uninstalled and re-installed and issue solved.
thanks.
