### ISSUE TITLE
Render combining characters in different color in the F1 list (in keybindings)

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#14605]

**Comment by bpasero** [comment]
@alexandrudima is this not applying to any place where we show keybindings? e.g.
* quick open (commands)
* watermark
* tooltips that show the keybinding in hover

**Comment by alexandrudima** [comment]
I haven't added it yet on my side. I used to have a getHTMLLabel() that would do a slightly better rendering that was used in the tooltips, but @aeschli took that out once we moved the hover to markdown.

LMK how you would like to approach this. I can revive the getHTMLLabel() (I would use `<span>` to color it differently) or I can add a getMarkdownLabel() (not sure how to render it differently).

**Comment by bpasero** [comment]
@alexandrudima the tooltips are native and cannot show HTML.

**Comment by alexandrudima** [comment]
I was talking about these keybinding hovers:

![image](https://cloud.githubusercontent.com/assets/5047891/20062795/4fb0e780-a505-11e6-9103-d505b74cd3fe.png)

Meanwhile I guess you were talking about these ones:
![image](https://cloud.githubusercontent.com/assets/5047891/20062821/69818d40-a505-11e6-96e6-e022515d56bd.png)

We can also drop this feature request and not do anything about it.

It was just a thought I had that it would be nice to render the combining characters in a special color, as they do it here:

![image](https://cloud.githubusercontent.com/assets/5047891/20062872/91741db8-a505-11e6-9160-7af0d514e9e2.png)

:+1: for closing since we won't be able to do anything about the menus and native tooltips.

**Comment by bpasero** [comment]
Let's discuss tomorrow in person 👍

**Comment by bpasero** [comment]
We decided that this is a bit too crazy :).
