### ISSUE TITLE
Debugger tool uninstalled not disappeared or disabled

### ISSUE THREAD

**Issue by javmonisu** [Microsoft/vscode#14606]
- VSCode Version: 1.6.1
- OS Version: Windows 7 SP1

Steps to Reproduce:

1. Install Python (or whatever you will use to debug) extension and restart VS Code.
2. Select it as a debug tool, run it and do whatever.
3. Uninstall it and restart
4. Debug tool will be visible and not disabled to run debugger on it.

Thanks

**Comment by weinand** [comment]
VS Code's debug UI will stay even if you uninstall the python debugger because VS Code has a built-in debugger for Node.js.
