### ISSUE TITLE
Please add basic tool bar for formatting (comment/uncomment, do/ undo)

### ISSUE THREAD

**Issue by qasims** [Microsoft/vscode#14601]
- VSCode Version:
- OS Version:

Steps to Reproduce:
1. 
2.

**Comment by bimbo1989** [comment]
It would also be nice for the formatting to be language-oriented (  for html, /* */ for PHP, ecc. )

**Comment by weinand** [comment]
All commands are easily reachable via the command palette (F1).
Please explain why this does not work for you.

**Comment by weinand** [comment]
@bimbo1989 your comment will be ignored because it is unrelated to the original request.

**Comment by aeschli** [comment]
Closing due to lack of additional information. We don't have a toolbar for actions and there are no plans for one.
