### ISSUE TITLE
[Feature Request] Option to seperate bracket guide opacity from bracket opactity

### ISSUE THREAD

**Issue by CoenraadS** [microsoft/vscode#146030]
I was trying to get the native bracket line coloring to match the original look of the default settings of Bracket Pair Colorizer 2, which uses the css properties `"Gold", "Orchid", "LightSkyBlue"` at 50% opacity. Because I like the guides to be 'background' and barley noticeable.

I added the following to my settings:

`
  "workbench.colorCustomizations": {  
        "editorBracketHighlight.foreground1": "#ffd90080",   
        "editorBracketHighlight.foreground2": "#CC66CC80",  
        "editorBracketHighlight.foreground3": "#87CEFA80",  
    },  
`

BPC2:

![image](https://user-images.githubusercontent.com/5593825/160075107-86327580-1491-4a83-9098-70bd02fdb235.png)

Native:

![image](https://user-images.githubusercontent.com/5593825/160075523-f1d143cb-5646-4f97-b977-b1e982ff7d3f.png)

Now the brackets themselves are really hard to see

**Comment by hediet** [comment]
You can use `editorBracketPairGuide.activeBackground1...6` to style the guides independent from the bracket colors! (You should also style `editorBracketPairGuide.background1` for inactive guides then)
By default they are all set to `#00000000`, which makes them reuse the bracket pair colors.

```json
"workbench.colorCustomizations": {
    // Bracket colors
    "editorBracketHighlight.foreground1": "#FFD700",
    "editorBracketHighlight.foreground2": "#DA70D6",
    "editorBracketHighlight.foreground3": "#179fff",

    // Inactive guide colors
    "editorBracketPairGuide.background1": "#ffd90080",
    "editorBracketPairGuide.background2": "#CC66CC80",
    "editorBracketPairGuide.background3": "#87CEFA80",

    // Active guide colors
    "editorBracketPairGuide.activeBackground1": "#ffd90080",
    "editorBracketPairGuide.activeBackground2": "#CC66CC80",
    "editorBracketPairGuide.activeBackground3": "#87CEFA80",
},
```
