### ISSUE TITLE
Pacckage.json file unable to create 

### ISSUE THREAD

**Issue by dbbaukon** [microsoft/vscode#146071]
Issue Type: <b>Feature Request</b>

npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or   
operable program. Check the spelling of the name, or if a path was included, verify that    
the path is correct and try again.
At line:1 char:1
+ npm -i init
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], CommandNotFoundException 

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

**Comment by IllusionMH** [comment]
/needsMoreInfo

Looks like you don't have `npm` in `PATH` (at least PowerShell doesn't see it).
Not cleat how it's related to VS Cote though. Do you see same error if you run that commend directly in PowerShell (not in internal terminal)
