### ISSUE TITLE
Geting started page has Dark preselected even when default is detected as light high contrast

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#146006]
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/8586769/160012780-f32c131d-a905-4055-badc-9f93d9322fa6.png">

**Comment by lramos15** [comment]
Having trouble reproing this. With the settings

```
    "window.autoDetectHighContrast": true,
    "window.autoDetectColorScheme": true,
```

I always see the theme change and the right thing selected.
