### ISSUE TITLE
Improve hover in Call Hierarchy UI 

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#146085]
Our language server provides useful information as the `detail` of CallHierarchyItem,
but that is often too long to be presented fully in the narrow side bar.
So, some users ask to trim down info included in the details (e.g. https://github.com/golang/vscode-go/issues/2057)
but I don't think that's the right approach. When function names are rather long, the details are completely hidden.

The current call hierarchy UI seems to use only `name` for its hover message.

![Screen Shot 2022-03-25 at 4 53 39 PM](https://user-images.githubusercontent.com/4999471/160199368-b47d9ef0-ee14-4934-85ca-a58f4c96bb1c.png)

How about adding the `detail` info to the hover message, too?

**Comment by babakks** [comment]
@jrieken I've just submitted a PR for this.
