### ISSUE TITLE
Cursor after injected text

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#146042]
* enable inline quick suggestions
* type `_curr` to get member completion for `this._currentChoice`
* the cursor shows at the wrong end

https://user-images.githubusercontent.com/1794099/160101000-29c2f0a1-6ed0-4dcf-b702-304df26d50cb.mov

**Comment by andrewbranch** [comment]
I’m on an Insiders that includes this fix (c63ed49) but I’m still seeing it:

https://user-images.githubusercontent.com/3277153/160172091-d96a6a5f-36b0-48d4-8f33-f5158482f941.mp4

**Comment by rzhao271** [comment]
Reopening as verification-found based on above.

**Comment by andrewbranch** [comment]
The full text of the file is seen in the screen capture. Also, it doesn’t seem to require parens. All it takes is to type over an inline suggestion. Note that this does not happen with completions that are previewed in Inline Suggestion; GitHub Copilot is the only thing that repros it for me—IIRC that uses a different API than completions.

**Comment by andrewbranch** [comment]
Makes sense that the fix didn’t apply to Copilot’s inline suggestion usage a the patch seems to be specific to completions.

**Comment by rzhao271** [comment]
Closing again and marking as verified for now.

**Comment by andrewbranch** [comment]
Sorry, what’s the solution then?

**Comment by rzhao271** [comment]
Will let @hediet decide whether to reopen this issue or create a new one for your case.
