### ISSUE TITLE
Double quotes when typing HTML attribute

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#146008]
* in a html file
* type `<div style="background:red">` without looking at the screen
* the outcome is `<div style=""background:red">`

**Comment by avi5079** [comment]
Hello @alexdima,
I am a beginner to open source. I would like to learn by contributing to this repo. Can you please guide me in this project like how to get started?

**Comment by yume-chan** [comment]
See also #144864

@avi5079 You can read [How to Contribute](https://github.com/microsoft/vscode/wiki/How-to-Contribute) for how to build and debug Code locally. Then search for https://github.com/microsoft/vscode/labels/good%20first%20issue or https://github.com/microsoft/vscode/labels/help%20wanted issues, which are usually pretty easy to get started.

**Comment by aeschli** [comment]
duplicate of https://github.com/microsoft/vscode/issues/140698
