### ISSUE TITLE
Remove all contributed terminal variables that aren't needed when git.useIntegratedAskPass is false

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#146082]
Minor follow up from https://github.com/microsoft/vscode/issues/111839 

I'm assuming these variables are only used by askpass.sh:

- VSCODE_GIT_ASKPASS_NODE
- VSCODE_GIT_ASKPASS_EXTRA_ARGS
- VSCODE_GIT_ASKPASS_MAIN

They should also be removed from the environment if so. `VSCODE_GIT_IPC_HANDLE` too if that's its only use.

**Comment by lszomoru** [comment]
This has been addressed. `VSCODE_GIT_IPC_HANDLE` is used for other git scenarios.
