### ISSUE TITLE
 Allow Explorer to be docked on the bottom/top

### ISSUE THREAD

**Issue by jamesfranklinnetsec** [microsoft/vscode#146017]
Related to #49923 and #10121 and now #118926 from which I'm plagiarising this.
### Feature Request

Allow Explorer to be docked on the bottom/top similar to other panels and not explicitly only a sidebar to support cases where vertical monitors are used.
### Context

I use a vertical monitor for my work, normally Kakoune, but I'm using VS Code to work with a client. I spent a bit trying to shift the explorer/sidebar to the bottom and realized it was only able to be docked on the left or right. Would be nice to have explorer work like other panels to be shifted where we need it. I'd personally like the bottom.

### why it's in scope, despite #118926 being closed
> We closed this issue because we don't plan to address it in the foreseeable future. You can find more detailed information about our decision-making process [here](https://aka.ms/vscode-out-of-scope). If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.
> 
> If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Thanks for your understanding and happy coding!

^^ from @vscode-triage-bot this issue was incorrectly triaged and categorised as out-of-scope because the issue doesn't meet the criteria for out of scope which are:

>1. Does the functionality described in the feature request have any reasonable chance to be implemented in the next 24 months? 24 months is longer than our [roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) which outlines the next 6-12 months. Thus, there is some crystal ball reading on our part, and we'll most likely keep more feature requests open than what we can accomplish in 24 months.

yes, there exist plugins that implement a fix already such as [customize UI](https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui), so if some random plugin guy can do this, then it shouldn't take too much time to make this feature.

>2. Has the community at large expressed interest in this functionality? I.e. has it gathered more than 10 up-votes or more than 10 comments? This criterion alone covers more than 650 of the 2850 open feature requests as of right now, October 9th, 2019.

yes, see #49923 #10121 #118926, also [this blogpost](https://howchoo.com/vscode/vs-code-move-search-to-bottom),  this [stackoverflow question](https://stackoverflow.com/questions/55255456/vscode-customization-move-activity-bar-to-bottom). 

>3. Do we think the feature request is bold and forward looking and would we like to see it be tackled at some point even if it's further out than 24 months? (Clearly, this one is the most subjective criterion.)

sure why not, I'd ideally like VScode to treat all panes/windows/whatever as being managed by whats in functionality a tiling window manager. Theyre very hot in demand right now, all the best nerds are using them, very forward looking move.

**Comment by JacksonKearl** [comment]
This is not substantially different from existing issues.
