### ISSUE TITLE
Debugger for Chrome extension not working

### ISSUE THREAD

**Issue by javmonisu** [Microsoft/vscode#14607]
- VSCode Version: 1.6.1
- OS Version: Windows 7 SP1

Steps to Reproduce:

1.  Install it , enable it etc...
2. Try to use it as a debugger
3. It does not show as an option:

![image](https://cloud.githubusercontent.com/assets/2870998/19773716/ed032f8c-9c6a-11e6-8e39-a97eb3d7544d.png)
![image](https://cloud.githubusercontent.com/assets/2870998/19773769/1282222c-9c6b-11e6-9695-7f83cf254527.png)

**Comment by weinand** [comment]
The drop down doesn't show debuggers but launch configs. Please read https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome for how to use the debugger.
