### ISSUE TITLE
[Extension API] Provide a way to discover uninitialized extension settings

### ISSUE THREAD

**Issue by hasufell** [microsoft/vscode#146044]
In the haskell language extension, we've currently designed a setting like so:

```json
        "haskell.manageHLS": {
          "scope": "resource",
          "type": "string",
          "default": null,
          "description": "How to manage/find HLS installations.",
          "enum": [
            "GHCup",
            "PATH"
          ],
          "enumDescriptions": [
            "Will use ghcup and manage Haskell toolchain in the default location (usually '~/.ghcup')",
            "Discovers HLS and other executables in system PATH"
          ]
```

So on first start, the setting will be `null`, signalling us the user has not made any choice yet. A choice is mandatory though and we provide a Dialog box asking for the preferred setting.

The problem with this approach is that `null` will show up in the GUI drop-down menu, which confuses users.

![Screenshot_2022-03-25_11-16-53](https://user-images.githubusercontent.com/1241845/160102013-77f62a3b-c554-4691-8b21-ba201079a48a.png)

So what we want is a way to discover uninitialized settings, without it showing up in the GUI drop-down.

A couple of alternatives we considered:

1. instead of `null`, use something more descriptive like "ask on start" (this is still no ideal, since it's not a reasonable option to manually select... all options shown in the GUI dropdown should be reasonable to select by the user)
2. add a new separate setting `manageHLSinitialized: bool`... while this would work, it's a setting that isn't relevant to the user again

Some brainstorming as to what might be a solution:

1. simply hide `null` values from the drop-down box for enum settings: this would be a breaking change, so probably not possible
2. allow the concept of "hidden" settings that don't show up in the GUI, but can still be changed in the `settings.json`

**Comment by rzhao271** [comment]
Can the options just be the two non-null ones, and the extension uses another variable in its implementation to check whether the user has been prompted yet, or not?

**Comment by gjsjohnmurray** [comment]
> A variable? How would that persist across VSCode restarts?

One way is to use the `globalState` `Memento` of the `ExtensionContext` which your `activate` method receives.

See https://code.visualstudio.com/api/references/vscode-api#ExtensionContext
