### ISSUE TITLE
oom always 

### ISSUE THREAD

**Issue by AnDaLinShui** [microsoft/vscode#146033]
远程连接开发设备
使用过程中经常出现oom

**Comment by AnDaLinShui** [comment]
Does the world need Google Translate?

**Comment by AnDaLinShui** [comment]
![image](https://user-images.githubusercontent.com/38171981/160082947-dbddd6b2-3da9-4e99-ad41-beb0fe892ec0.png)

**Comment by deepak1556** [comment]
Does the issue happen when you run with `--disable-extensions`

**Comment by AnDaLinShui** [comment]
> Does the issue happen when you run with `--disable-extensions`
i need to debug... if --disable-extensions  later, debug still available?

**Comment by deepak1556** [comment]
Can you explain what debug functionality you are referring to ?

**Comment by AnDaLinShui** [comment]
> 
![image](https://user-images.githubusercontent.com/38171981/161175579-e43d37a9-2db5-48de-a10a-ddfaccc4f48c.png)

**Comment by deepak1556** [comment]
Thanks for clarifying, you will not be able to use the debugging feature from the go extension with `--disable-extensions`, but the flag is the easiest way to narrow down if the issue is caused by extension or the core.
