### ISSUE TITLE
intelliSense in configuration file can be improved

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14604]
- VSCode Version: 1.7 Insider

Ctrl-space before typing `"`:

![image](https://cloud.githubusercontent.com/assets/4033249/19772873/6e2cbd84-9c1c-11e6-8f27-b07c912b2e5a.png)

What it should show:

![image](https://cloud.githubusercontent.com/assets/4033249/19772886/7816da6e-9c1c-11e6-90a4-03077da62d87.png)

**Comment by aeschli** [comment]
It doesn't show these because these properties are already present. 

![image](https://cloud.githubusercontent.com/assets/6461412/19775211/f61a14fa-9c6f-11e6-88d7-6af5d19f78b9.png)
