### ISSUE TITLE
Mac M1 SSH starts Electron high CPU resources consumption

### ISSUE THREAD

**Issue by tamet83** [microsoft/vscode#146090]
Issue Type: <b>Performance Issue</b>

Whatever ssh addon I use, my M1 mac uses a lot of CPU resources.
The electron process eats up to 180% of my CPU and it remains active even if I close the ssh connection.
Are you aware about thi issue?

VS Code version: Code 1.65.2 (Universal) (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 50dae77b-d4f9-40ba-92f2-b6b546f91402|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	    98	  9928	code main
    0	    41	  9931	   gpu-process
    0	     8	  9934	   utility-network-service
    0	    90	  9935	   window (config — Senza titolo (Area di lavoro))
    0	    25	  9949	   extensionHost
    0	     8	  9989	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=9949
  165	  2048	 11615	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Users/matteo/.vscode/extensions/keesschollaart.vscode-home-assistant-1.26.0/out/server/server.js --node-ipc --clientProcessId=9949
    0	    49	  9950	   shared-process
    0	    16	  9952	     ptyHost
    0	     8	  9972	     fileWatcher
    0	     0	 12157	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    66	 12155	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (config — Senza titolo (Area di lavoro))
|    Folder (ssh://sonar/): Workspace stats not available.;
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.0
path-autocomplete|ion|1.19.1
vscode-home-assistant|kee|1.27.0
vscode-sshfs|Kel|1.24.1
vscode-language-pack-it|MS-|1.65.3
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.3
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvid1:30447480
pynewfile477cf:30450039

```

</details>

**Comment by deepak1556** [comment]
Process info indicates `keesschollaart.vscode-home-assistant-1.26.0` seems to be consuming high cpu, does the issue repro when you disable this extension ?

**Comment by tamet83** [comment]
> Process info indicates `keesschollaart.vscode-home-assistant-1.26.0` seems to be consuming high cpu, does the issue repro when you disable this extension ?

Hello, you're right.
I disabled the extension, killed the process and rebooted the app.
Everything seems working right now.

Thank you

**Comment by deepak1556** [comment]
Thanks for confirming and opening an issue with the extension, I am closing this issue since it is not a problem with the core.
