### ISSUE TITLE
Tabs not rendering right

### ISSUE THREAD

**Issue by bimbo1989** [Microsoft/vscode#14608]
- VSCode Version: 1.6.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Open some tabs
2. Close VSCode
3. Re-open VSCode

Minor issue, I know, but still strange.
Looks like that, when opened, VSCode tries to fit all tabs in the given space.
When I click on one of the unselected tabs, the rendering starts to work and the horizontal scrollbar appears.

Freshly opened
https://i.imgsafe.org/2239ae0c43.png

After click
https://i.imgsafe.org/223ac7eb7f.png

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13668
