### ISSUE TITLE
Multiple GitHub Codespaces for same repository show up ambiguously in Recent section of Getting Started page

### ISSUE THREAD

**Issue by michaelbprice** [microsoft/vscode#146086]
If someone creates more than one GitHub Codespace for the same project, and they've opened both recently, each one shows up in the Recents section with the same identifying information.

![vscode-multiple-codespaces-ambiguous](https://user-images.githubusercontent.com/60362/160207682-7a312b72-c6f4-4a95-bb8a-7506e75ab316.png)

The same is probably true if the Codespaces are for different repositories that happen to have the same name.

There should be some unique identifying information visible for the user to be able to choose the truly desired one. Such as using the generated container names for each Codespace, as can be seen on the GitHub management page at https://github.com/codespaces.

**Comment by JacksonKearl** [comment]
This would be up to the codespaces extension to control, they can use the recent uri label provider extension point to customize uri names.

**Comment by michaelbprice** [comment]
@JacksonKearl Do you happen to know which repository I should file a feature request issue in for the Codespaces extension?

**Comment by JacksonKearl** [comment]
Not really, it looks like they track requests in discussions: https://github.com/github/feedback/discussions/categories/codespaces-feedback

**Comment by michaelbprice** [comment]
Filed at https://github.com/github/feedback/discussions/14394
