### ISSUE TITLE
Please fix the search-replace in a selection

### ISSUE THREAD

**Issue by Ammo999** [microsoft/vscode#146051]
Can somebody.. ANYBODY , please fix the stupid Search and Replace in a selection.  It is so counterintuitive and doesnt work 90% of the time.  Please follow the guidelines of 99% of the other software which works as expected. 

1. Select Text
2. Press Control-H ( The search and replace should know only to work in the selected area)
3. Enter the search term
4. enter the replace term
5. execute

**Comment by IllusionMH** [comment]
/needsMoreInfo
Have you tried to change `editor.find.autoFindInSelection` setting?

**Comment by kkocdko** [comment]
I think I know what you said. This function need me to **reselect the region manually** after type search pattern.

I agree with you.

**Comment by Ammo999** [comment]
> Have you tried to change editor.find.autoFindInSelection setting?

hello, I didn't know about this. This is acceptable for me and it does work - although i feel this should have been the default.

Thank you.  you may close this ticket
