### ISSUE TITLE
Infinite repeated crash!!!!

### ISSUE THREAD

**Issue by abcz316** [microsoft/vscode#146070]
- VS Code Version: **code_1.65.2-1646927742_amd64.deb**
- OS Version:  Ubuntu20.4

Steps to Reproduce:

1.Change the system RAM to 4096
2.Vscode opens more than 2000 files
3.The system sends Kill 9 signal to vscode
4.Reopen vscode. Vscode will automatically open the previous 2000 files and crash again. **Infinite program crash!**

**Comment by kkocdko** [comment]
Many wrong operation will cause the same, like buggly extension...

So it's not a bug? You can pass `-n` argument to start a new session without reopen files.

**Comment by abcz316** [comment]
> start

Did you try? My newly installed system. There is no extension plug-in. If there is, I will mark it out.

**Comment by abcz316** [comment]
Thank kkocdko for giving me effective advice
