### ISSUE TITLE
`code-oss://` opens in new window when running under debugger on Windows

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#146195]
Steps to Reproduce:

1. revert this workaround change: https://github.com/microsoft/vscode/commit/b1fb11e18cbdd3aba09e4aef0b4be07c0731d86f
2. Launch `code-oss` via debugger
3. Go through GitHub auth flow (you can do this using the Clone Repository button here)
<img width="376" alt="image" src="https://user-images.githubusercontent.com/2644648/160443487-3371809d-bfcb-4055-a36e-11b67bafcfae.png">

#### Expected

Auth flow redirects to window that you initiated the flow from

#### Actual

Auth flow (browser) opens a new `Code - OSS` process and flow doesn't complete 

#### Notes

@deepak1556 in chat:

> this was reported only under debug configuration, might want to test insiders under the same flow. The OS handling of the link should be fine since we confirmed the registry values. When user clicks the popup from the browser it would delegate to the OS which will then run the registry value as the command and end up launching a code-oss instance with --open-url and any additional arguments provided from the browser. This would then go through our singleton instance flow, which is basically if there is already an active instance of code then it will have a singleton server which basically listens for new instance launches and they will connect to this server. The server will then extract the arguments from the new instance and kill the new instance, applies the arguments to the running instance. In this case --open-url would bring back data from the browser to current active window. The problem currently is that this flow breaks under debugging, need to investigate why that is the case.

**Comment by deepak1556** [comment]
This turned out to be a side effect of OSS not being packaged and requiring `VSCODE_DEV`, `VSCODE_CLI` environment variables to forward to running instance. I don't think we can support this scenario with our current implementation and also not worth the complexity given there haven't been asks for this case since the issue was opened.
