### ISSUE TITLE
about terminal

### ISSUE THREAD

**Issue by sulamvaishnavi** [microsoft/vscode#146162]
![Screenshot (43)](https://user-images.githubusercontent.com/84628047/160334183-062fe9e8-0461-4c3f-b4f6-9a19bf0ce5ce.png)

**Comment by sulamvaishnavi** [comment]
its not taking input

**Comment by meganrogge** [comment]
can you reproduce the issue when you've disabled all extensions?

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
