### ISSUE TITLE
VS Code Integrated Terminal Not Outputting Complete print() - PrettyTable()

### ISSUE THREAD

**Issue by DJDaDingo** [microsoft/vscode#146119]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

I have been trying to use VS Code for some python coding for a class I am currently taking. We must use PrettyTable() to generate tables of data after having filled them with data. However, it seems that every time it comes to printing these tables, VS Code cuts off the ends of each table. In this specific assignment, one table should be 4,940,992 characters long, but it only prints the first 9,648 characters before stopping any output and the other table should be 648,516 characters long, but only prints 10,123 characters.

I noticed #38137 was very similar to this issue, however I am not able to print each line individually without headers printing with them. This has occurred with other scripts in the past, but I normally just use a different application like WingIDE to confirm all my outputs are accurate, but for this particular assignment WingIDE is incredibly slow and I would much prefer to use VS Code.

I should also mention I have been unable to find any patterns with the cutting of the output. It may be time based since I haven't found a link with character count.

Are there any other solutions to this weird output cap in VS Code?

Thanks!

**Comment by meganrogge** [comment]
I think what you're looking for is the setting `terminal.integrated.scrollback` which is 1000 lines by default
