### ISSUE TITLE
Allow users to restore files instead of just folders while restarting Code

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#14612]
- VSCode Version: 1.6.1
- OS Version: OSX

Steps to Reproduce:

1. Launch VS Code, open several files separately in Code instead of any folder
2. Close VS Code
3. Launch VS Code again, Code opens a blank file instead of previous opened files

Currently folders can be restored while files can not.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by rebornix** [comment]
@bpasero sorry for wasting your time on this. I saw ppl reported this problem on social network and I can reproduce it myself. Then I tried to see if we have this issue reported already but unluckily I didn't, after searching for 5-10 minutes. The keywords I used were `restore files` and `restore editors`.

The only issue that looks similar is https://github.com/Microsoft/vscode/issues/14492 while it's marked as `more info` and I can't reproduce his problem.

But sorry again, I think it's me that don't have a good understanding of all issues about this component. It would be great that you can direct to the issue that describes this problem precisely. Thanks in advance.

**Comment by bpasero** [comment]
While not so easy to associate, it is https://github.com/Microsoft/vscode/issues/4429
