### ISSUE TITLE
Notebook - Setting for cell output limit

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode#146139]
I recently started getting this warning when trying to display more than 2 outputs from a notebook cell (eg 3 dataframes):
<img width="736" alt="image" src="https://user-images.githubusercontent.com/29611875/160294274-32901acc-92f3-4891-9f38-f949e7b50bee.png">

I'm pretty sure it's related to this recent change:
https://github.com/microsoft/vscode/blob/e16d9ef81c4740b6f0a6afec86b69583067de0a8/src/vs/workbench/contrib/notebook/browser/view/cellParts/codeCell.ts#L57

Could you please add a setting so this value can be modified by the user? Thanks!

**Comment by gjsjohnmurray** [comment]
Being fixed in  #146228

**Comment by rebornix** [comment]
Thanks @gjsjohnmurray for referencing. It should be fixed in next Stable/Insiders.
