### ISSUE TITLE
code running

### ISSUE THREAD

**Issue by ashu7337** [microsoft/vscode#146101]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

whenever i try to run my program it does not showing me any output this problem happening from yesterday please give me solution. 

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 6.2.9200
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (7.83GB free)|
|Process Argv|--crash-reporter-id ea3f5a2b-8f33-46c1-aab4-e3368c5c636a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
code-runner|for|0.11.7
c-cpp-runner|fra|3.2.4
better-cpp-syntax|jef|1.15.13
csharp|ms-|1.24.1
remote-containers|ms-|0.224.3
remote-ssh|ms-|0.76.1
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17
vscode-lldb|vad|1.7.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrc:30451274
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvidc:30447482
pynewfile477cf:30450039

```

</details>

**Comment by weinand** [comment]
What programming language are you using?
How are you trying to run your program?
Please provide reproducible steps.

**Comment by ashu7337** [comment]
I am using c language
