### ISSUE TITLE
Snippet transform `camelcase` not working well.

### ISSUE THREAD

**Issue by AkatQuas** [microsoft/vscode#146166]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.2
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Create a code snippet like this.

```json
{
	"TS -> Inject Service": {
		"scope": "typescript",
		"description": "Constructor Injection Pattern",
		"prefix": "@inject",
		"body": "@inject(${1/(.*)/I${1}Token/}) private readonly ${1/(.*)/${1:/camelcase}/}: I${1},$0"
	}
}
```

2. Using the snippet. 

![camelcase](https://user-images.githubusercontent.com/24731539/160342428-b0d6e71e-f472-4c34-8ce3-48b28ffc7e51.gif)

As I as concerned, the camelcase of `PathService` should be `pathService`. However, the result is `pathservice`. 

https://github.com/microsoft/vscode/blob/049b0e564b6bc1fcc07e9a39b727bca9836274f4/src/vs/editor/contrib/snippet/browser/snippetParser.ts#L404-L418

The implementation doesn't seems to tackle it well. 

I'd like to help if you could be so nice to give me a hint to fix the problem. 😃

**Comment by AkatQuas** [comment]
However, I am curious about how to deal with the word `stub_PathServiceToken`.

In my opinion, the camelized expectation should be `stubPathServiceToken` rather `stubPathservicetoken`.

**Comment by AkatQuas** [comment]
I'd like to help if you help to define the actual expectation of the `camelcase` transform function.

**Comment by jrieken** [comment]
Thanks. Your definition (https://github.com/microsoft/vscode/issues/146166#issuecomment-1081287990) seems reasonable, add camel case but don't remove them
