### ISSUE TITLE
Terminal colors regression

### ISSUE THREAD

**Issue by andyearnshaw** [microsoft/vscode#146168]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.66.0-insider
Commit: 10dc49b279e2f8ab0194a0e831ade4ea773b8a55
Date: 2022-03-27T12:23:35.556Z (18 hrs ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 19.6.0

After the most recent VSCode update on the Insiders track, my terminal foreground colours have changed:
![image](https://user-images.githubusercontent.com/1826067/160347620-4f9e3491-29b1-4d9a-a58d-240bc0aefe4a.png)

This is what they looked like before, and what they look like on the stable track:
![image](https://user-images.githubusercontent.com/1826067/160348009-06bfe9dc-259f-456a-801e-184c9ea28518.png)

I can confirm this issue persists when starting code with `--disable-extensions`. Could this be related to the work @daviddossett has been doing?

**Comment by Tyriar** [comment]
This is by design as we've have changed the default minimum color contrast to be 4.5 for accessibility reasons, you can change it to use original theme colors by setting `"terminal.integrated.minimumContrastRatio": 1`
