### ISSUE TITLE
prettier not working

### ISSUE THREAD

**Issue by EdisonVan** [microsoft/vscode#146103]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.65.2(Universal)
- OS Version: macOS Big Sur 11.2

Steps to Reproduce:

1.set Prettier as default formatter
2.confit .prettierrc on the project,but prettier not working

**Comment by RobertPietraru** [comment]
Try reinstalling vscode

**Comment by ntotten** [comment]
This seems to be impacting many users. See https://github.com/prettier/prettier-vscode/issues/2466

**Comment by tyler-brandt** [comment]
Same issue for CSharpier - reinstalling the extension and reinstalling vscode did not solve the issue

**Comment by chrmarti** [comment]
@ntotten Could you provide additional details on how this is caused by VS Code?

**Comment by jrieken** [comment]
I have tried with prettier 9.5.0 (this extension https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and cannot reproduce. I successfully installed and activated. So, please provide the version and extension id. Thanks
