### ISSUE TITLE
Inconsistent font size in a comment with inline `code` blocks

### ISSUE THREAD

**Issue by arsdever** [microsoft/vscode#146183]
- Extension version: 0.38.1
- VSCode Version: 1.65.2
- OS: macOS 12.3

Steps to Reproduce:

1. Create a comment with some inline `code` blocks and a regular text, e.g. "\`noexcept\` for these 3 \`register\` functions?"

<img width="465" alt="Screen Shot 2022-03-25 at 11 13 50" src="https://user-images.githubusercontent.com/22396275/160073352-483ee025-4f12-444e-94a9-b3c550ab456a.png">

As you see, the code blocks are way larger than the regular text.

**Comment by arsdever** [comment]
BTW. Why isn't there the background color change for the code blocks in the comments? Would be nice to have, although it's a totally different issue, I'd say.

**Comment by mjbvz** [comment]
@alexr00 I believe markdown renderer only generates html and does not provide default styling. Try looking into the css for the comment widget

**Comment by alexr00** [comment]
It looks like this was done intentionally. Here's what I think the reasoning is:
- Comments are shown in the editor, where by default the font size is 14px
- Non-code text in VS Code is 13px
- So, non code text in a comment is 13px
- But, since code in a comment is still within an editor, it might look small, so make it 14px to match the editor. 

Some original discussion: https://github.com/microsoft/vscode-pull-request-github/issues/168

I will get some more feedback and see what a majority of people think.

**Comment by alexr00** [comment]
Feedback is that all codeblocks int he comment widget should be 13px (same size as non-codeblock text).

**Comment by arsdever** [comment]
@alexr00 at least like that. Today I tried to set the font size for the rest of the UI, but it seems that I'm only in control of the code block font size. Hence my experience is always bad because the UI font is always hardcoded, but the code block font size can be configured.

**Comment by alexr00** [comment]
The intended new behavior will be that the size of the codeblock font will match the size of the surrounding non-codeblock font. You will be able to change the size of all workbench font, including codeblocks, by zooming.

**Comment by arsdever** [comment]
> The intended new behavior will be that the size of the codeblock font will match the size of the surrounding non-codeblock font. You will be able to change the size of all workbench font, including codeblocks, by zooming.

It is already nice to have the fonts matching. But one question is having them match, another to have them customizable (even when they have to be the same). Look. If I set the font size of my code, say, 20px and I want my comments to have a size of 24px. This means that I will have to zoom in enough, to make the default font size (13px) look like 24px. When I zoom in, the rest will also increase the size of the text, and no longer be something I wanted with 20px. I hope I communicate my thoughts clean and understandable enough 🙂

**Comment by alexr00** [comment]
@arsdever makes sense, thank you for clarifying.

The comment widget inherits it's font size from the workbench font size. This is true for almost all of the workbench (which is basically everything that isn't the editor part), so we would not have a separate setting for just the font size of the comment widget.

There is a feature request to have a setting for the workbench font size: https://github.com/microsoft/vscode/issues/519.

**Comment by meganrogge** [comment]
not sure if there's anything we can do about the extra space between normal text and `code` here, but that would look nice now that they're the same font size
![Screen Shot 2022-04-28 at 10 54 34 AM](https://user-images.githubusercontent.com/29464607/165816648-babdde55-
0831-402c-a686-675e71799c05.png)
