### ISSUE TITLE
VS Code refactoring (symbol renaming) in JS doesn't work in unopened files

### ISSUE THREAD

**Issue by campmdabt** [microsoft/vscode#146120]
Issue Type: <b>Bug</b>

When trying to refactor function names, variable names, or class names within all files using F2 (as shown at https://code.visualstudio.com/docs/editor/refactoring#_rename-symbol), I only seem to have success when those other files are open in the editor. If they're closed, VS Code won't rename those instances. Am I missing something?

1. Create 3 files as shown below
2. Close all files in the editor
3. Open `class.js`
4. Use F2 to rename `testVar` in `class.js`
5. Observe the name change in `class.js`
6. Open `main.js`, observe the name did not change
7. Undo that change in `class.js`
8. Keep `main.js` open, and use F2 to rename` testVar` in `class.js`
9. Observe the name change in both `class.js` and `main.js`
10. Repeat steps 2 thru 9 for `TestClass.testMethod` in `class.js` and `moduleVar` and `moduleFn` in `module.js`

The expectation would be that even with `main.js` closed, renaming the symbol would work across all files.

class.js:
```
export default class TestClass {
	constructor() {
		this.testVar = 'test';
	}

	testMethod() { return; }
}
```

module.js:
```
export const moduleVar = 'test';
export function moduleFn() { return; }
```

main.js:
```
import TestClass from './class';
import { moduleFn, moduleVar } from './module';

const test = new TestClass();

test.testMethod();

test.testVar = 'test 2';

moduleFn();

moduleVar = 'hello';
```

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (45.04GB free)|
|Process Argv|--crash-reporter-id c898a3f9-eb5b-4cbd-a834-91caf53e7c8d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-css-formatter|aes|1.0.2
format-json|Cle|1.0.2
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
auto-rename-tag|for|0.1.10
gc-excelviewer|Gra|4.2.53
todo-tree|Gru|0.0.215
icon-fonts|idl|2.5.3
innosetup|idl|1.6.1
reg|ion|1.0.3
vscode-colorize|kam|0.11.1
vscode-idea64-formatter|LeT|0.0.1
rainbow-csv|mec|2.2.0
csharp|ms-|1.24.1
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.3
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.9.7
powershell|ms-|2021.12.0
vscode-typescript-next|ms-|4.7.20220325
fix-json|oli|0.1.2
serverless-vscode-snippets|raf|0.0.5
vscode-commons|red|0.0.6
vscode-yaml|red|1.5.1
LiveServer|rit|5.7.5
partial-diff|ryu|1.4.3
code-settings-sync|Sha|3.4.3
perforce|sle|3.2.0
highlight-matching-tag|vin|0.10.1
vscode-import-cost|wix|2.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvid1:30447480
vscaat:30438848
pynewfile477:30450038

```

</details>

**Comment by IllusionMH** [comment]
https://code.visualstudio.com/docs/languages/javascript#_javascript-projects-jsconfigjson

Looks like those files are not part of inferred project. Config with proper includes should correctly resolve all necessary files.

**Comment by campmdabt** [comment]
Thank you Andrii! Confirmed in test workspace as well as my production workspace. The default config below works in my case.

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6"
  },
  "exclude": ["node_modules"]
}
```

Again, thanks for the response. Please stay safe.
