### ISSUE TITLE
can not open a simple document rep

### ISSUE THREAD

**Issue by xum07** [microsoft/vscode#146158]
github.dev even can not open a simple document rep......

ADD ISSUE DESCRIPTION HERE

Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36
Embedder: github.dev

**Comment by gjsjohnmurray** [comment]
What happens when you try?

/gifPlease

**Comment by xum07** [comment]
forget the img, just like blow 
![image](https://user-images.githubusercontent.com/19642011/160535015-4dc8cb7e-85f9-4235-a192-356eaa9512fb.png)

I try to open my rep(no codes,only some markown notes), but github-dev can not open it,. Only the moving blue line tells me this page still alive

**Comment by mjbvz** [comment]
Please provide steps to reproduce the problem
