### ISSUE TITLE
createFileSystemWatcher doesn't trigger on Remote-SSH Linux on sub-directories

### ISSUE THREAD

**Issue by arnaudsylvestre** [microsoft/vscode#146182]
Issue Type: <b>Bug</b>

I created a file system watcher thanks to the createFileSystemWatcher provided by the API :

```
const pattern = new vscode.RelativePattern(vscode.workspace.workspaceFolders?.[0], "**/Config/*.ini")
	var watcher = vscode.workspace.createFileSystemWatcher(pattern);
	watcher.onDidChange(e => {
		console.log(e)
	});
```
It works on Windows (Local), Remote-SSH on Windows Server but it doesn't work on Remote-SSH Linux.

Another thing : it works at root level
```
const pattern = new vscode.RelativePattern(vscode.workspace.workspaceFolders?.[0], "**/*.ini")
	var watcher = vscode.workspace.createFileSystemWatcher(pattern);
	watcher.onDidChange(e => {
		console.log(e)
	});
```

Any idea ?

Thans in advance !

VS Code version: Code - Insiders 1.65.0-insider (32456dc9e7d3194a94dd3ee0322ccf47e461d09c, 2022-02-23T05:16:22.798Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.59.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.61GB (3.48GB free)|
|Process Argv|--crash-reporter-id 6f81bbc9-a04c-423e-8d06-d48f3ff30e44|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: **********.com|
|OS|Linux x64 3.10.0-1160.59.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz (12 x 2900)|
|Memory (System)|15.49GB (1.23GB free)|
|VM|100%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-dashboard|kru|2.5.1
remote-ssh|ms-|0.77.2022031115
remote-ssh-edit|ms-|0.77.2022032415
vscct|Ade|0.0.37
vscode-intelephense-client|bme|1.8.2
githistory|don|0.6.19
data-workspace-vscode|ms-|0.1.1
mssql|ms-|1.13.0
sql-database-projects-vscode|ms-|0.14.1
php-debug|xde|1.25.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vsclayoutctrc:30405799
pythonvspyt640:30438691
vscscmwlcmc:30428972
pynewfile477:30451556

```

</details>

**Comment by bpasero** [comment]
This issue could originate from a problem with file watching. Let me explain how file watching works in VSCode first and then provide some details how to get more logging data from how file watching behaves in your case.

**Synopsis**
VSCode has different strategies for file watching depending on your workspace and setup:
* no folder opened: files in opened editors are watched via node.js `fs.watch`
* folder opened: folder is watched recursively for all changes via [parcel](https://github.com/parcel-bundler/watcher), opened editors with files not within the folder are watched via node.js `fs.watch`

If you are connected to a remote (SSH, WSL, Docker), the file watcher will run within the target file system. As such, even though you maybe on Windows where VSCode runs, if the remote is Linux, the file watcher will run in the Linux environment.

**Platforms**
Depending on the platform you are on, file watching is differently implemented:
* macOS: using `fsevents` services
* Windows: using `ReadDirectoryChangesW` method
* Linux: using `inotify`

Specifically on Linux, watching a large folder recursively can result in VSCode consuming too many file handles. If that is the case, you will see a warning notification with instructions how to solve that.

**Limitations**
File watching comes with a set of limitations:
* symbolic links are not followed automatically but you can explicitly add symbolic links to be watched via the `files.watcherInclude` setting
* mapped network drives or third party file system drivers are not guaranteed to produce file events
* in general, the operating system may decide to drop file events at any time, there is no 100% guarantee

**Settings**
Please review your settings to see if maybe a folder is excluded by accident. Specifically, the `files.watcherExclude` setting is relevant.

**Logging (local)**
!!! This is ONLY when you open a local workspace, for remote see below !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the local workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `Help | Toggle Developer Tools`
* select `Console`
* filter the output by typing `File Watcher` into the filter box
* attach the output when doing the operation that exhibits the issue

![image](https://user-images.githubusercontent.com/900690/156323290-f3ba6470-dfed-4066-a19c-951395611738.png)

**Logging (remote)**
!!! This is ONLY when you open a remote workspace (WSL, Docker, SSH), for local see above !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the remote workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `View | Output`
* select `Log (Remote Server)` from the dropdown
* attach the output when doing the operation that exhibits the issue

![image](https://user-images.githubusercontent.com/900690/156323886-6b7dfa25-d6ac-4316-9150-80e5c8104d04.png)

**Comment by arnaudsylvestre** [comment]
Hi @bpasero,

Thanks for the explanation, it is very clear now.
I activated the trace log level but I didn't see your last two lines concerning the file watcher. Here is my log
`[2022-03-29 09:02:33.498] [remoteagent] [trace] [Disk FileSystemProvider]: createResourceLock() - request to acquire resource lock (/var/www/vhosts/***.com/httpdocs/Config/config-dev.ini)
[2022-03-29 09:02:33.498] [remoteagent] [trace] [Disk FileSystemProvider]: createResourceLock() - new resource lock created (/var/www/vhosts/***.com/httpdocs/Config/config-dev.ini)
[2022-03-29 09:02:33.499] [remoteagent] [trace] [Disk FileSystemProvider]: open() - storing lock for handle 23 (/var/www/vhosts/***.com/httpdocs/Config/config-dev.ini)
[2022-03-29 09:02:33.503] [remoteagent] [trace] [Disk FileSystemProvider]: close() - resource lock removed from handle-lock map 23
[2022-03-29 09:02:33.503] [remoteagent] [trace] [Disk FileSystemProvider]: close() - disposing lock for handle 23
[2022-03-29 09:02:33.503] [remoteagent] [trace] [Disk FileSystemProvider]: createResourceLock() - resource lock dispose() (/var/www/vhosts/***.com/httpdocs/Config/config-dev.ini)
[2022-03-29 09:02:33.503] [remoteagent] [trace] [Disk FileSystemProvider]: createResourceLock() - resource lock removed from resource-lock map (/var/www/vhosts/***.com/httpdocs/Config/config-dev.ini)
[2022-03-29 09:02:33.503] [remoteagent] [trace] [Disk FileSystemProvider]: createResourceLock() - resource lock barrier open() (/var/www/vhosts/***.com/httpdocs/Config/config-dev.ini)`

And indeed, I can see the last two lines for a file at the root of my repository...

Any idea to force file watcher events ?

Thanks in advance

**Comment by bpasero** [comment]
The file watcher is installed very early on startup so enabling logging later might miss it, but when you change the `files.watcherExclude` setting and observe the log, you should see entries for the file watcher restarting, can you try that?

**Comment by arnaudsylvestre** [comment]
Indeed, I can see that :

`[2022-03-29 10:25:43.448] [remoteagent] [trace] [File Watcher (parcel)] Request to start watching: /var/www/vhosts/***.com/httpdocs (excludes: **/.git/objects/**,**/.git/subtree-cache/**,**/node_modules/*/**,**/.hg/store/**,/var/www/vhosts/***.com/.vscode-server/extensions/**)`
`[2022-03-29 10:25:43.449] [remoteagent] [trace] [File Watcher (parcel)] Request to stop watching: /var/www/vhosts/***.com/httpdocs`
`[2022-03-29 10:25:43.449] [remoteagent] [trace] [File Watcher (parcel)] stopping file watcher on /var/www/vhosts/***.com/httpdocs`
`[2022-03-29 10:25:43.449] [remoteagent] [trace] [File Watcher (parcel)] Started watching: '/var/www/vhosts/***.com/httpdocs' with backend 'inotify' and native excludes '/var/www/vhosts/***.com/httpdocs/.git/objects, /var/www/vhosts/***.com/httpdocs/.git/subtree-cache, /var/www/vhosts/***.com/httpdocs/node_modules, /var/www/vhosts/***.com/httpdocs/.hg/store'`
`[2022-03-29 10:25:44.642] [remoteagent] [trace] [File Watcher (parcel)] Request to start watching: /var/www/vhosts/***.com/vscode-extension (excludes: **/.git/objects/**,**/.git/subtree-cache/**,**/node_modules/*/**,**/.hg/store/**,/var/www/vhosts/***.com/.vscode-server/extensions/**)`
`[2022-03-29 10:25:44.642] [remoteagent] [trace] [File Watcher (parcel)] Request to stop watching: /var/www/vhosts/***.com/vscode-extension`
`[2022-03-29 10:25:44.642] [remoteagent] [trace] [File Watcher (parcel)] stopping file watcher on /var/www/vhosts/***.com/vscode-extension`
`[2022-03-29 10:25:44.643] [remoteagent] [trace] [File Watcher (parcel)] Started watching: '/var/www/vhosts/***.com/vscode-extension' with backend 'inotify' and native excludes '/var/www/vhosts/***.com/vscode-extension/.git/objects, /var/www/vhosts/***.com/vscode-extension/.git/subtree-cache, /var/www/vhosts/***.com/vscode-extension/node_modules, /var/www/vhosts/***.com/vscode-extension/.hg/store'`

But after that, I still have the same problem...

**Comment by arnaudsylvestre** [comment]
Yes it is exactly that !

**Comment by bpasero** [comment]
Is there a possibility that the folder is `config` and not `Config` on disk? I.e. a casing difference.

Does it reproduce with all patterns of this kind, e.g. what if you try a different glob pattern on a different path than `Config`?

**Comment by arnaudsylvestre** [comment]
Yes I tried with other folders, other casing but impossible to make it work...

For example, I tried the following patterns :
- **/config/*.ini
- **/Config/*.ini
- **/Custom/configuration/*.ini (I have another folder with the same problem...)
- **/custom/configuration/*.ini

But without results. the following pattern is the only one which works :
- **/*.ini

**Comment by bpasero** [comment]
One thing that puzzles me: when you call `createFileSystemWatcher` on a path that is inside the workspace (as you do in this case), we actually do not create a new file watcher, we just participate in the existing one that we create anyway when you open a workspace. There is always a default recursive watcher over the entire contents of the workspace and the only exception is all paths that match any of the `files.watcherExclude` setting.

So independent from the pattern you provide, and even before you call `createFileSystemWatcher`, I would expect that file evens are maybe already broken in that `Config` folder.

For that to confirm: when you enable trace logging as I had outlined before, do you see file change events in the log for root files at least? And when you change files in `Config` folder you don't?

**Comment by arnaudsylvestre** [comment]
Yes I confirm that I can see file change events in the log for root files but none for files in Config directory...

**Comment by bpasero** [comment]
Ok, I am sorry I cannot be of more help, I fear I have no clue what is going on. Could be some configuration issue on the target, maybe hitting a limit of file handles, though we do warn if that is the case: 

https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc
