### ISSUE TITLE
Many shells launched from the integrated terminal on Windows don't function in various ways

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14613]
- #13809 mongoDb shell: _"it is not possible to write brackets and curly brackets. in fact that key combinations with ALT-GR doesnt work."_
- #14577 `irb` (Ruby): _"The cursor can move in the normal terminal , but can't when entered the irb!"_
- #7345, #15481 #15869 #17122, #18277 git-bash sometimes drops letters / Backspace, left and right in Windows integrated terminal cause prompt to go out of sync in Git bash
- #16914, #16986 *"press Tab to next file, leaves blank space and traces"*
- #8117 Terminal has display bugs with julia console
- #17586 Terminal name autocomplete (with TAB) shifts the completed string to left

**Comment by emanuelbuholzer** [comment]
The same error as shown in #13809 also occurs when using the GHCi REPL (Haskell). It is not possible to use combinations with ALT-GR.

- VSCode Version: 1.6.1
- OS Version: Win 7.1 x64

**Comment by Tyriar** [comment]
Could be fixed by updating to winpty@0.4.0 in https://github.com/Tyriar/pty.js/issues/10

**Comment by jimmyharris** [comment]
Is there any issue on this? I am still seeing this issue in git bash on Windows 10 with the latest release of visual studio code.

**Comment by Tyriar** [comment]
https://github.com/Tyriar/pty.js/issues/10 is on the iteration plan for January which should hopefully improve the situation, it's one of the lower priority tasks though so it may not make it in.

**Comment by Tyriar** [comment]
I'll verify this one

**Comment by Tyriar** [comment]
- ✔️ julia issue
- ✔️ git bash issue
- ✔️ tab autocomplete issue
- 🚫 arrows in irb, reopened and filed upstream issue https://github.com/rprichard/winpty/issues/99
