### ISSUE TITLE
Jupyter Notebook not showing output + background turning grey

### ISSUE THREAD

**Issue by PepperPile** [microsoft/vscode#146153]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.2
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open an existing notebook OR create a new notebook
2. Run any code
3. Wait for a few seconds
4. The background will turn grey and any existing output will be covered
![C6D881FD-905D-42E4-9835-C835B92240EA](https://user-images.githubusercontent.com/69230815/160315691-8e2ae5cd-ce66-4163-9d79-2be8172db2a3.png)

#144803

**Comment by PepperPile** [comment]
This is a new issue in 1.65 and cannot be replicated in 1.64

**Comment by gjsjohnmurray** [comment]
Are you able to test with Insiders? 1.66 is due to ship later this week.

**Comment by PepperPile** [comment]
1.66 seems to be alright and this behaviour cannot be replicated.

**Comment by willparkhouse** [comment]
I'm on 1.66.2 and am currently having this issue. 
Was the update from 1.65 to 1.66 the fix for you?

**Comment by PepperPile** [comment]
> I'm on 1.66.2 and am currently having this issue.
> Was the update from 1.65 to 1.66 the fix for you?
> For me this is only occurring on one notebook in particular, all my other notebooks run as expected.

Yes.
Basically, I was using Insiders 1.66 and I cannot replicate this issue in Insiders. And about a week later, I upgraded vsc from 1.65 to 1.66 and the issue was gone. What I can confirm is that while I was playing with Insiders 1.66, vsc 1.65 was still having this issue.

**Comment by willparkhouse** [comment]
> I'm on 1.66.2 and currently having same issue. Some notebooks are working fine and some having this issue. How can I fix this?

For my affected notebooks I simply created a new notebook and copy-pasted all of the code/markdown, which fixed the issue for some reason.. Still needs to be fixed, but I can't reproduce it.

**Comment by poconnell7** [comment]
I had similar issues. I could see in my Mac Activity Monitor that the Code Helper (Renderer) process went from 4GB up to 12GB in a minute or two (as I scrolled through the notebook) and then crashed, which apparently causes the Jupyter Notebook output to be greyed out. This is VS Code V1.67.1.  I was processing a large data file (86MB) and my .ipynb notebook had grown to 277MB after creating a topic model. However copying the relevant code snippets into a new Notebook (as per @willparkhouse) seems to have resolved the problem, so it may not be related to the large data size. My extensions are GitHub Copilot (waitlisted for access), Jupyter, Jupyter Keymap, Jupiter Notebook Renderers, Pylance and Python.
