### ISSUE TITLE
Settings sync merge conflict UI renders button offscreen when diff is in inline view

### ISSUE THREAD

**Issue by yzhang-gh** [microsoft/vscode#146152]
This is exactly the same issue as #105767 back to 2020 which was marked as duplicated.

However, the issue seems to still be there now. @sandy081 Could you point me out to the main issue? Thanks.

cc @RMacfarlane 

---

Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/104672
