### ISSUE TITLE
Letter case change undetected in source control

### ISSUE THREAD

**Issue by AuracleTech** [microsoft/vscode#146135]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Create a file and commit your files
![image](https://user-images.githubusercontent.com/40531871/160292612-e4b54da3-b46c-4179-aa26-4da246364476.png)
2. Change the case from lowercase to uppercase (same name but alternative case)
![image](https://user-images.githubusercontent.com/40531871/160292633-73c192f3-fe3b-4de2-af9d-beb07dd64316.png)
3. Check source control
![image](https://user-images.githubusercontent.com/40531871/160292681-dc8a1720-b71d-4eab-9cad-0a5c8ce6f6da.png)
4. Source control detected no changes even though the file name changed

Why does this matter : Linux file system is case sensitive. My current GitHub tests are failing due to a file name that's not updated, and I can't update it.

**Comment by yume-chan** [comment]
https://stackoverflow.com/questions/1793735/change-case-of-a-file-on-windows

**Comment by AuracleTech** [comment]
For next users with the same issue
`git config --global core.ignorecase false`
