### ISSUE TITLE
Intellisense Suggestions Ignoring LocalityBonus

### ISSUE THREAD

**Issue by picks-1** [microsoft/vscode#146123]
Issue Type: <b>Bug</b>
![Capture](https://user-images.githubusercontent.com/102442277/160263839-89f85ea7-b34b-4ced-a4cc-c031548cf2ff.JPG)

As seen in the image attached, the option of 'await' is suggested before 'i'.
This makes no sense. Even with editor.suggest.localityBonus set to true, there seems to be no sorting applied.

The issue has only appeared in the last 24 hours.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.24.1
unity-debug|Uni|2.7.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvidc:30447482
vscaat:30438848
pynewfile477:30450038

```

</details>

**Comment by gjsjohnmurray** [comment]
> The issue has only appeared in the last 24 hours.

VS Code 1.65.2 won't have changed so maybe an extension or a setting did.

Do you get any extra diagnostic information if you press Ctrl+Space while the suggestion list is displayed?

**Comment by picks-1** [comment]
My extensions are listed in the issue above and they haven't updated recently and I haven't deliberately changed any settings - is there perhaps some keyboard shortcut that I hit which changed a setting which controlls the order the suggestions are provided in? I installed previous versions of VSCode, and it's happening in all versions back to 1.60 - in this version the intellisense behavior goes back to 'normal' (providing the local variable 'i' as the first suggestion).

Below is the only information provided with Ctrl+Space while the suggestion list is displayed.

![Capture](https://user-images.githubusercontent.com/102442277/160272845-c7cb5acc-319b-48ab-972a-c08fc0603d91.JPG)

Interestingly, if I don't remove async from the function declaration (it is added to the function automatically if you select 'await' from the suggestion list), I get the behavior that I've come to expect (pictured below)

![Capture2](https://user-images.githubusercontent.com/102442277/160272909-a4dd7591-8f73-4e3d-a66d-9e791d75d462.JPG)

I know there are solutions like adding a delay to the suggestion list appearing so that I can press the spacebar and not have 'await' populate into my for loop and add async to the function declaration, or I could disable the spacebar as the suggestion confirmation button, but I don't like changing my process for some issue that could just propagate into further issues down the line.

**Comment by Lemmingh** [comment]
/extC#

It's from OmniSharp.

* <https://github.com/OmniSharp/omnisharp-vscode/issues/5096>
