### ISSUE TITLE
Callhierarchy clicked item revealed code is inconsistent in peek vs. references view

### ISSUE THREAD

**Issue by pbaksa** [microsoft/vscode#146145]
Does this issue occur when all extensions are disabled?: No, because feature isn't available without TS extension. I don't know which language has this feature with extensions disabled.

- VS Code Version: 1.65.2
- OS Version: WIN

Steps to Reproduce:

1. open some TS code
2. peek call hierarchy (outgoing calls)
3. clicking an item the place of the call (source) is revealed
4. show call hierarchy for the originally peeked word
5. clicking an item the definition of the call (target) is revealed

It is easy to get lost when using both, and not clear in the API documentation which one to provide in an extension.

**Comment by pbaksa** [comment]
When there are cross-document links, preferences view shows clicked items' document correctly either if I provide source or target uri.
However peek view tries to show the range in the parent document of the selected item if I provide the source uri.

**Comment by gianmarcoodorizzi** [comment]
Hi @jrieken, should https://github.com/microsoft/vscode/issues/111454 be already fixed? Has it been released yet? Thanks :)
