### ISSUE TITLE
.bashrc file not loading

### ISSUE THREAD

**Issue by ZeroXiphYT** [microsoft/vscode#146141]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: Chrome OS 99.0.4844.86 (Official Build) (64-bit)

Steps to Reproduce:

1. open bashrc file with code ~/.bashrc and enter your bash code for terminal, my code is
```bash
bind 'TAB:menu-complete'
GREEN=$(tput setaf 051)
TEAL=$(tput setaf 044)
RES=$(tput sgr0)

PS1="\[$TEAL\]<\t> "
PS1+="\[$GREEN\]{\W}"
PS1+="\[$RESET\]$ "
export PS1
```
how terminal is supposed to look
![Screenshot 2022-03-27 10 50 58 AM](https://user-images.githubusercontent.com/94765932/160294296-1d822fe6-27a7-4841-ad42-79f899829324.png)

2. Open another vscode instance or whatever and open terminal
how terminal looks now
![Screenshot 2022-03-27 10 58 45 AM](https://user-images.githubusercontent.com/94765932/160294313-67d0f726-32d5-4ee2-abfe-95759dde42fc.png)

**Comment by ZeroXiphYT** [comment]
the integrated terminal and this always happens

**Comment by Tyriar** [comment]
Cannot repro on Linux:

![Image](https://user-images.githubusercontent.com/2193314/207193013-28ab88fa-6218-49b3-b780-d012ade41587.png)

Could be a Chrome OS problem?
