### ISSUE TITLE
Support macos "Scale to fit below built-in camera"

### ISSUE THREAD

**Issue by artyil** [microsoft/vscode#146130]
This is to request better compatibility with the "Scale to fit below built-in camera" macos feature.
More information is here - apple https://support.apple.com/en-us/HT212842.
Please consider to prioritize if it is not on the roadmap already.

**Comment by deepak1556** [comment]
Depends on https://github.com/electron/electron/issues/31478

**Comment by abarisain** [comment]
What would this even do though? VSCode behaves properly in fullscreen: the area under the notch shows a black bar

If you uncheck "Automatically hide and show the menubar in fullscreen" (not sure what the default state is) in "Dock & Menubar" preferences, you even see the menu bar on top of a fullscreened vscode

Safari does the same and so does finder.

Not sure what VSCode needs to support here. The setting you've linked downscales the whole screen when the target app is launched, and is meant for compatiblity. VSCode doesn't even have this enabled by default.

**Comment by artyil** [comment]
@abarisain according to your input current behavior already support what I was asking for. Probably we can close this thread as resolved. Thanks a lot!
