### ISSUE TITLE
 t.getId is not a function

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#14614]
Issue Id: <b>03bb3666-4d56-a8c6-e4f9-cbf7719cf0a5</b><br /><br />*Versions* <br />- 1.7.0-insider (10/24/2016 9:49:46 AM)<br />*Stack* <br />TypeError: t.getId is not a function<br />[/vs/workbench/parts/debug/electron-browser/debugViewer.ts#L274:47 (getProcesses)](https://github.com/microsoft/vscode/blob/c038219f8d137b4972a15346b81ea03751d669d4/src/vs/workbench/parts/debug/electron-browser/debugViewer.ts#L274:47 (getProcesses))<br />[/vs/base/parts/tree/browser/treeModel.ts#L394:58 (_this)](https://github.com/microsoft/vscode/blob/c038219f8d137b4972a15346b81ea03751d669d4/src/vs/base/parts/tree/browser/treeModel.ts#L394:58 (_this))<br />[/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/c038219f8d137b4972a15346b81ea03751d669d4/src/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/c038219f8d137b4972a15346b81ea03751d669d4/src/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/c038219f8d137b4972a15346b81ea03751d669d4/src/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/c038219f8d137b4972a15346b81ea03751d669d4/src/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />[/vs/workbench/parts/debug/electron-browser/terminalSupport.ts#L96:8](https://github.com/microsoft/vscode/blob/c038219f8d137b4972a15346b81ea03751d669d4/src/vs/workbench/parts/debug/electron-browser/terminalSupport.ts#L96:8)<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L67:9 (prototype)](https://github.com/microsoft/vscode/blob/c038219f8d137b4972a15346b81ea03751d669d4/src/vs/workbench/parts/debug/node/v8Protocol.ts#L67:9 (prototype))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L28:9 (this)](https://github.com/microsoft/vscode/blob/c038219f8d137b4972a15346b81ea03751d669d4/src/vs/workbench/parts/debug/node/v8Protocol.ts#L28:9 (this))<br />[/vs/workbench/parts/debug/electron-browser/terminalSupport.ts#L85:85](https://github.com/microsoft/vscode/blob/c038219f8d137b4972a15346b81ea03751d669d4/src/vs/workbench/parts/debug/electron-browser/terminalSupport.ts#L85:85)<br />

**Comment by bpasero** [comment]
@isidorn fyi this was from an insiders build.

**Comment by isidorn** [comment]
@bpasero I do not think this is possible. Is the stack trace 100% accurate, how many times did it happen might you know.

**Comment by bpasero** [comment]
```typescript
public getId(tree: tree.ITree, element: any): string {
	if (typeof element === 'number') {
		return element.toString();
	}
	if (typeof element === 'string') {
		return element;
	}

	return element.getId();
}
```

I would put my bet that `element` is `null/undefined` or another primitive type.

**Comment by isidorn** [comment]
Wow first time ever that error telemetry uncovered an awesome bug for me!
This was a regression that 'Load more stack frames' scenario was not working

Though the error stack frame I was looking at did no lead to that function, not sure how you got that

**Comment by isidorn** [comment]
To verify:
1. Have a breakpoint that has a deep stack when hit, for instance a recursive fibonaci function
2. Make sure you get 'Load more stack frames' in the call stack view and that you can browse them
