### ISSUE TITLE
C# for vs extentions?

### ISSUE THREAD

**Issue by Shadowblitz16** [microsoft/vscode#146129]
Can we have support for writing vscode extensions in C#?

**Comment by Lemmingh** [comment]
/duplicate #136167

You can, but you still have to code in TypeScript, plus tedious stuff about JavaScript-dotNET interop: module loading systems, JSON, TypedArray, WASM, Blazor (with AOT), WebSocket, Web Worker, etc.

In short, this requires an in-depth understanding of both front-end web technologies and .NET technologies.

Here is an interesting project that may help you:
<https://github.com/Elringus/DotNetJS>
