### ISSUE TITLE
The syntax highlighting for CSS is not working properly inside multiline strings

### ISSUE THREAD

**Issue by decrovert** [microsoft/vscode#146146]
This issue occurs when all the extensions are disabled.

## Version info

- VS Code Version: 1.65.2
- OS Version: Windows 11 Pro Education 21H2

## Steps to Reproduce

1. Create a CSS file;
2. Open it in VS Code;
3. Use line-breaking syntax to separate a string into multiple lines (see example below);

## Image illustrating the issue

See that after using that syntax for breaking the line, the syntax highlighting becomes messed up.

<img src="https://user-images.githubusercontent.com/99348582/160298688-20bd0d67-e021-4a0c-97a2-0bbbf8794866.png" width="400">

Note that this does not happen in other languages. Here is an example in C:

<img src="https://user-images.githubusercontent.com/99348582/160299193-b77d781f-d183-42c2-a202-02ae39427abb.png" width="400">

**Comment by aeschli** [comment]
For CSS, we use the grammar from  https://github.com/atom/language-css. 
The issue has already been reported there:  https://github.com/atom/language-css/issues/181
Closing as duplicate.
