### ISSUE TITLE
Can't open directories from CLI using path with tilde (~) on Windows

### ISSUE THREAD

**Issue by rgwood** [microsoft/vscode#146116]
Issue Type: <b>Bug</b>

1. From the CLI (any shell), attempt to open a subdirectory of your home directory: `code ~\some_project\`
2. Observe that VS Code launches *but does not open the directory*; instead it opens to a new blank file called `some_project`

I'm only able to reproduce this on Windows, this works as expected on WSL2.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (6.00GB free)|
|Process Argv|~\\source\\nushell.github.io\\ --crash-reporter-id 31cf0ca9-5e39-4b6b-ad68-7d099578036b|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvid2:30447481
vscaac:30438847
pynewfile477cf:30450039

```

</details>

**Comment by IllusionMH** [comment]
Widows doesn't has `~` as Linux does.
Git Bash (installed with Git for Windows) does conversions in CLI so VS Code will receive converted path, but cmd/PowerShell doesn't support it.

**Comment by rgwood** [comment]
Hmm, I'm not sure about that. I can do `cd ~` in PowerShell (Windows PowerShell or PowerShell 7).

**Comment by IllusionMH** [comment]
You can do `cd ~`(but not in cmd) however apps will receive different arguments when you call `app ~/folder-name`: in Git Bash app will receive converted to full path `C:\Users\User_name\folder` string, but in PS it would be just regular string(path) `~/folder-name` and for OS `~` doesn't have special meaning therefore it's treated as regular relative path.

So it shouldn't be a Bug

In PS you should be able to hit <kbd>Tab</kbd> after path to get expanded version and VS Code then will open expected folder.

**Comment by rgwood** [comment]
This is functionality that works elsewhere in Windows but not for VS Code. For example `start ~/foo.txt` launches `~/foo.txt` as expected.

Maybe this should be a feature request instead of a bug report, but I think it would be very useful to implement either way.

**Comment by Lemmingh** [comment]
My suggestion:

No. I do not think it's worth adding such support on the Windows version.

This problem involves how the shells, OS, and native applications handle command-line. I've seen Windows Terminal and PowerShell struggling with such complex and bizarre things for a long time.

Explanation is as below.

---

In PowerShell, '`cd`' and '`start`' are aliases of cmdlets.

```powershell
Get-Command -All -Name @('cd', 'start') | Format-List
```

```yaml
DisplayName       : cd -> Set-Location
CommandType       : Alias
Definition        : Set-Location

DisplayName       : start -> Start-Process
CommandType       : Alias
Definition        : Start-Process
```

They use the PowerShell FileSystem provider to resolve paths which [interprets `~` as `$env:USERPROFILE` under certain circumstances](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/resolve-path#example-1-resolve-the-home-folder-path).

```powershell
(Convert-Path '~') -eq (Convert-Path $env:USERPROFILE)
```

```text
True
```

---

On Linux, `glibc` (GNU C Library) and shells have some similar logic named "Tilde Expansion".

---

In [CMD](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands) and [native applications compiled by MSVC](https://docs.microsoft.com/en-us/cpp/cpp/main-function-command-line-args#parsing-c-command-line-arguments), however, command-line arguments are treated in much different ways.

---

`~` can actually be entry name on Windows.

```powershell
New-Item -ItemType File -Force -Path 'C:/temp/~/~' | Select-Object -ExpandProperty FullName
```

```text
C:\temp\~\~
```

---

The VS Code CLI already interprets arguments in a [quite complicated manner](https://code.visualstudio.com/docs/editor/command-line#_opening-files-and-folders).

> For both files and folders, you can use absolute or relative paths. Relative paths are relative to the current directory of the command prompt where you run `code`.

**Comment by aeschli** [comment]
It's the shell that handles the `~`. The application get's the full path.
I'm not aware of code in VS Code that converts `~` to the home folder, except when users type it in the custom file/folder selection dialog we have.

No plans on our side to add such support so this also works in powershell.
