### ISSUE TITLE
Drag drop folder not merged, but replaced.

### ISSUE THREAD

**Issue by 80avin** [microsoft/vscode#146137]
Issue Type: <b>Bug</b>

1. Have file structure like this
```
root
+---dirA
|   \---dirB
|           file1.txt
|
\---dirB
        file2.txt
```

2. In `Explorer` sidepanel, drag `dirB` and drop on `dirA`

3. Observe that file1.txt is replaced.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (7.88GB free)|
|Process Argv|--crash-reporter-id 6e9fa3e7-1256-46aa-8a75-c284ecd0319d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.4
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.2.2
typescript-notebook|don|2.0.6
gitlens|eam|12.0.5
prettier-vscode|esb|9.4.0
remotehub|Git|0.26.0
CppSnippets|har|0.0.15
better-cpp-syntax|jef|1.15.13
cortex-debug|mar|1.4.3
python|ms-|2022.2.1924087327
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.3
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
jsflowchart|MUL|0.1.6
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.17
vscode-arduino|vsc|0.4.11
vscode-todo-highlight|way|1.0.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvid2:30447481
cppdebug:30451566
pynewfile477cf:30450039

```

</details>

**Comment by h-h-h-h** [comment]
I can confirm this. This is very bad! 

[.zip file for quick directory structure construction.](https://github.com/microsoft/vscode/files/8385220/vscodebug.zip)

The side bar showed `dirA \ dirB` with `file1.txt` in it, and I dropped the other `dirB` on the `dirA` mentioned here. I was left with a deleted `file1.txt`. I got the following message dialog before:

> [Window Title]
> Visual Studio Code
>
> [Main Instruction]
> A file or folder with the name 'dirB' already exists in the destination folder. Do you want to replace it?
>
> [Content]
> This action is irreversible!
>
> [Replace] [Cancel]

**Comment by JacksonKearl** [comment]
```
[Main Instruction]
A file or folder with the name 'dirB' already exists in the destination folder. Do you want to replace it?

[Content]
This action is irreversible!

[Replace] [Cancel]
```
sounds like the behaviour was exactly as described? We do not claim to support merging as far as I can tell, and are explicit that an irreversible replacement will occur.

**Comment by 80avin** [comment]
@JacksonKearl Then, I think this should be converted into a feature request?
Folder merging is the more obvious behaviour than replacing it and it is so in almost every file manager I can recall.

I agree that the current behaviour is as described, but it is not the behaviour which a user would expect for folders. Therefore, I think it is reasonable to atleast add another button in the confirmation dialogue which replaces files & merges folders.

**Comment by JacksonKearl** [comment]
Duplicate of #143028
