### ISSUE TITLE
Add "Code here" for each platform's explorer context menu?

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14618]
In macOS, I have an app called [TermHere](https://itunes.apple.com/us/app/termhere/id1114363220?mt=12) that adds a context menu item:

![image](https://cloud.githubusercontent.com/assets/4033249/19779444/fb2927c2-9c35-11e6-86e1-f1c4e92589a5.png)

Windows:

![image](https://cloud.githubusercontent.com/assets/4033249/19779460/092c4dfe-9c36-11e6-8414-ba437556fa18.png)

I don't know about Linux, but would be really useful for macOS and Win users.

**Comment by joaomoreno** [comment]
Windows supports this at the installation step (there is an option for it).

OS X supports this via [services](http://www.hongkiat.com/blog/customize-mac-right-click-menu/).
