### ISSUE TITLE
Incorrect hover value provided to debug adapter

### ISSUE THREAD

**Issue by ivanhernandez13** [microsoft/vscode#146191]
Issue Type: <b>Bug</b>

When hovering over a pointer variable being initialized (e.g. `int *ptr = (int *)malloc(sizeof(int));`), VS Code provides the debug adapter an evaluate string that dereferences the variable instead of just the variable (e.g. `*ptr` vs `ptr`). 

With the debugger included with the C++ extension, this results in getting an integer value  instead of a memory address. With the debugger that I work on we also provide type information for pointer values (e.g. `(int *) 0x00007ff7bfefeda8`) which makes a noticeable difference when working in Objective-C because almost everything in Objective-C is a pointer. Because of the way VS Code provides the evaluate value when hovering, the debugging experience is inconsistent, providing different levels of information depending on where you hover. 

An easy way to repro this issue is to run the following file with the C++ extension
```
// main.c
int main() {
  int a = 5;
  int *b = &a; // 1
  int y = *b; // 2
  void *z = b; // 3
  return 0;
}
```
Note that in the C-family languages `int *ptr` and `int* ptr` are two perfectly valid and equivalent ways to declare a variable named `ptr` of type `int *` so the hover over the line labeled 1 would make more sense to be equivalent to the hover on the line labeled 3 despite looking more like line labeled 2.

Also, I'm filing this under VS Code instead of the C++ extension or handling it in my extension because VS Code does not provide the debug adapter with any way of differentiating between whether the hover value is part of a variable declaration. For example, hovering over line 1 and line 2 in the sample program above would send the same request to the debug adapter:
```
{
  "command": "evaluate",
  "arguments": {
    "expression": "*b",
    "frameId": 524288,
    "context": "hover"
  },
  "type": "request",
  "seq": 14
}
```

I don't know if VS Code has this information but ideally VS Code would be able to lookup the symbol that is being hovered on instead of just the raw text and therefore know what part of that text is the type and what is the variable name that needs to be evaluated.

VS Code version: Code 1.65.2 (Universal) (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|CppProj --crash-reporter-id b5a447da-2982-4269-91cd-d8398f01fd39|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.5.0
vscode-bazel|Baz|0.5.0
memento-explorer|bwa|0.1.1
arm|dan|1.7.4
binary-plist|dni|0.8.0
LogFileHighlighter|emi|2.15.0
vscode-diff|fab|1.4.2
shell-format|fox|7.2.2
misc-additions|iva|1.0.6
better-cpp-syntax|jef|1.15.13
nickel-syntax|kub|0.0.1
jupyter|ms-|2022.2.1030672458
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.9.7
vscode-js-profile-flame|ms-|1.0.0
indent-rainbow|ode|8.2.2
shellman|Rem|5.6.0
bash-debug|rog|0.3.9
shellcheck|tim|0.18.10
errorlens|use|3.4.2
vim|vsc|1.22.2
change-case|wma|1.0.0
clang-format|xav|1.9.0
propertylist|zho|0.0.2
material-theme|zhu|3.13.20

</details>

**Comment by weinand** [comment]
The C++ extension seems to rely on VS Code's built-in generic debug hover implementation, which is language agnostic and uses a regular expression to match the expression under the cursor.
This works reasonable well for some languages, but not for all.

To address these issues debug extensions can register an `EvaluatableExpressionProvider` that better understands the corresponding language and passes the correct expression to the debug adapter.

See section "New Debug Hover API" in https://code.visualstudio.com/updates/v1_43.

The corresponding feature request: https://github.com/microsoft/vscode/issues/89084

Here is an example from Mock Debug: https://github.com/microsoft/vscode-mock-debug/blob/393ee2b2443e270bacd9f11fa219c39a88fc987d/src/extension.ts#L63-L84
