### ISSUE TITLE
Launch: first argument for workspace path no longer reaches extension window

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14611]
I am no longer able to launch an extension on a specific workspace. To reproduce:
* generate an extension
* open launch.json
* add a folder to open as first argument

=> the folder is not opened in the window that opens the extension

* add the folder again so that it shows up as the first two entries in the arguments

=> now the folder is opened

@weinand @isidorn any ideas?

**Comment by bpasero** [comment]
My suspect is https://github.com/Microsoft/vscode/blob/master/src/vs/platform/environment/node/argv.ts#L87

/cc @joaomoreno

**Comment by bpasero** [comment]
I commented out that code and it still reproduces so it must be something else...

**Comment by bpasero** [comment]
@joaomoreno this might be a regression from using the shared `IEnvironmentService` also for the main process. A much easier repro is this:

* go into the folder of the Electron executable
* run `./Electron --nolazy someFolder`
* notice that Code refuses to open that folder

Debug adds `--nolazy` to our startup and somehow as soon as you pass an argument to an app that uses minimist for parsing that is not registered as known argument, things go wrong.

If I add `nolazy` to our list in https://github.com/Microsoft/vscode/blob/master/src/vs/platform/environment/node/argv.ts#L38 this issue is gone.

Any clue?

**Comment by joaomoreno** [comment]
> as soon as you pass an argument to an app that uses minimist for parsing that is not registered as known argument

Probably minimist is parsing `--nolazy` as an option that takes a string instead of as a boolean flag. So, try adding `nolazy` as a boolean option in [here](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/environment/node/argv.ts#L51).

**Comment by joaomoreno** [comment]
Awesome. Good catch.

**Comment by bpasero** [comment]
@joaomoreno yup, added it. Just sucks that we need to be aware of this in the future. I think it would be better if debug adds their arguments maybe as last thing to the list and not first.

**Comment by joaomoreno** [comment]
`nolazy` is a node flag, not a debug flag.

On second thought, the real fix here is to not let Node and Electron arguments reach our system at all. But this is a good quick fix.

**Comment by weinand** [comment]
I've introduced this issue through this fix https://github.com/Microsoft/vscode/issues/13434
It does not make sense to pass the `--nolazy` flag here because VS Code controls how the extension host is launched.
@bpasero should I revert this?

**Comment by weinand** [comment]
I'm no longer adding the `--nolazy` flag for EH debugging.
