### ISSUE TITLE
FIle nesting: A different approach

### ISSUE THREAD

**Issue by eugenious** [microsoft/vscode#146126]
Thanks for creating such an amazing product, which I use every day!

I was excited to see the file nesting experimental feature land in version 1.64. I'd like to propose a slightly different take on this concept, so I put together some mockup designs. Actually I was hoping to build it out as an extension first, but couldn't figure out how to do it without recreating the entire File Explorer from scratch (which wouldn't make sense to do).

Original view:

![default-view](https://user-images.githubusercontent.com/6581160/160264868-cdcae091-68a0-4fc8-a2e7-c3d2bcac87bd.png)

Proposed view:

![proposed-view](https://user-images.githubusercontent.com/6581160/160264895-cc743ac8-387a-4dc9-93fa-d84e3a8abf47.png)

Features of the proposed view:

- files with the same "base name" are grouped on one line

- each extension represents a file, and can be clicked to open, just like a regular file

- a unique file icon (for example a symbol representing an array) to indicate it is a "collapsed" file entry

- perhaps clicking on the base name might expand it to show one file per line as in the original view

It's similar but not quite the same as the experimental nesting view which I show here for comparison:

![nesting-view](https://user-images.githubusercontent.com/6581160/160265197-af5c413f-80b0-4445-a680-2ea12818b5d8.png)

The major difference is that with the experimental nesting view, non-"parent" files are hidden away and you don't know what they are, and you can't open them, unless you expand to view all the children files.

**Comment by JacksonKearl** [comment]
Thanks for submitting! It's an interesting idea but unfortunately is big a departure from what our existing tree widgets support and would require significant work to implement (things like drag and drop, renaming, context menus, keyboard shortcuts, accessibility, etc. would all need to be reconsidered). Similar features in other editors use the existing approach so I'm going to go ahead and close this out.

**Comment by eugenious** [comment]
Okay, thanks for your consideration. Maybe I could still try it out myself by making an extension at some point.
