### ISSUE TITLE
"Your First Extension" failed, Task runs forever

### ISSUE THREAD

**Issue by limboy** [microsoft/vscode#146134]
Does this issue occur when all extensions are disabled?: Yes/No

Yes

- VS Code Version: Version: 1.65.2 (Universal)
- OS Version: Mac OS 12.3

Steps to Reproduce:

1. follow [this](https://code.visualstudio.com/api/get-started/your-first-extension) tutorial, open workspace with `code`, run debug 
2. pop up an error window
![CleanShot 2022-03-28 at 00 39 31@2x](https://user-images.githubusercontent.com/35974/160291813-acb299c3-87c9-42f8-8b98-9d934ea656a0.png)
3. in the host window, trigger `Hello World` command pop up another error window, with some error
![CleanShot 2022-03-28 at 00 41 14@2x](https://user-images.githubusercontent.com/35974/160291843-69284b38-7fc3-4804-b69a-2361418fa522.png)
![CleanShot 2022-03-28 at 00 41 37@2x](https://user-images.githubusercontent.com/35974/160291851-c34bff94-866b-41bb-b4a2-ca75014c8bd7.png)

PS: if I create a new task(with simple command like `echo foo`), and set that task as entry task, then this task keeps running 

![CleanShot 2022-03-28 at 00 33 41](https://user-images.githubusercontent.com/35974/160291908-8e42a49b-97ae-435b-aed6-c360770006cd.gif)

**Comment by alexr00** [comment]
I'm not able to reproduce the issue. Can you share all your VS Code settings?
