### ISSUE TITLE
More complete Unity Support

### ISSUE THREAD

**Issue by hadi77ir** [Microsoft/vscode#1461]
It's just OmniSharp and C# support, not Unity integration. Even with using a Unity Editor Plugin, nothing changes: We have only C# support without UnityEngine.UI, UnityEngine.EventSystems, UnityEngine.* and UnityEditor namespaces!

Also we don't have any Boo or UnityScript support when we're using VS Code, So we had to switch back to the MonoDevelop.

What Unity Community wants from Visual Studio Code is:
1. Implementing UnityScript and Boo Support
2. Fixing assembly referencing problems (specially for UnityEngine.UI, but I think that it's a Unity problem, not an OmniSharp bug)
3. Intellisense for Boo and UnityScript (by using Roslyn, since they're .NET languages)

**Comment by egamma** [comment]
@hadi77ir the feature request makes sense, but this is also a great opportunity for a Code contribution/extension from to the Unity community.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#9

**Comment by rakkarage** [comment]
http://forum.unity3d.com/threads/vs-code-unity-debugger-extension-preview.369775/
