### ISSUE TITLE
Disable middle-click paste

### ISSUE THREAD

**Issue by jez9999** [Microsoft/vscode#14610]
Some of us are used to middle-click not pasting so it is very annoying for it to paste into the editor on Linux.  There should be a config option to disable middle-click paste.

**Comment by mbeckenbach** [comment]
@jez9999 
For windows i would like to have an option to enable that. :-D

**Comment by alexandrudima** [comment]
`editor.selectionClipboard`

**Comment by WhatFreshHellIsThis** [comment]
@alexandrudima is that the answer? I've looked into it and I don't see how this prevents the center button (wheel in my case) from randomly pasting text into source code while scrolling files which I think was the original (and my) issue.  It looks like your response is related to selecting and copying text..no?

**Comment by alexandrudima** [comment]
@WhatFreshHellIsThis Please set `"editor.selectionClipboard": false` in your user settings. This will make it so we don't paste from the selection clipboard when you press the middle button and we don't write to the selection clipboard when a selection is made in the editor.

**Comment by WhatFreshHellIsThis** [comment]
Ten thousand thundering typhoons!  It worked!  Thank you @alexandrudima , it's counter-intuitive but it does the job!
