### ISSUE TITLE
vscode.dev PWA fails to start offline after cached file expires

### ISSUE THREAD

**Issue by dr-vortex** [microsoft/vscode#146189]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2 (vscode.dev)
- OS Version: Chrome OS 99.0.4844.86 (Platform 14469.58.0)

Steps to Reproduce:

1. Open the VS Code PWA
2. Disconnect internet
3. Reset the cache by waiting about 30 minutes (or the browers default cache time) or by clearing cached files in the clearing the browser history page
4. refresh the page (not using `Ctrl` + `Shift` + `R`)
5. Error occurs

Error Screenshot:
![image](https://user-images.githubusercontent.com/75621402/160428106-5f7f2ce3-9d9a-46ed-bd32-31c3ee18288f.png)

I believe this can be mostly solved by setting a `Cache-Control` http header for the js file with a `max-age` of `2592000` (30 days), and `immutable`, so that reloading it does not reset the cache.

**Comment by dr-vortex** [comment]
Hi @joyceerhl,

I'm using it to edit a local folder.

**Comment by dr-vortex** [comment]
Yes, here is a screenshot:
![image](https://user-images.githubusercontent.com/75621402/160487937-5633c5b6-24e0-4aa8-9091-420444b1729b.png)
The file path does not appear here.

**Comment by joaomoreno** [comment]
Very interesting. When vscode.dev starts up, you should see a few log messages from `SW` like this:

![image](https://user-images.githubusercontent.com/22350/161266299-bbd2b719-8984-4079-afed-f2a46403ad15.png)

What does yours show?

**Comment by dr-vortex** [comment]
It's looks similar, except for these error messages. I noticed that the first one is the same file that is not being cached:
![image](https://user-images.githubusercontent.com/75621402/161338788-edcfea05-ee48-47bc-8f6e-94d7afba5b07.png)

**Comment by joaomoreno** [comment]
Got it. This is an issue with our CDN, which is currently resolved in https://insiders.vscode.dev and will be released next month on https://vscode.dev.
