### ISSUE TITLE
Blurry text in vscode while playing a video (klite, windows media player)

### ISSUE THREAD

**Issue by t0ngub1n** [microsoft/vscode#146140]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2 (user setup)
- OS Version: Windows 10 Version 21H2 KB5011543
- Intel Graphics

```
version: 1.65.2 (user setup)
Фиксация? (looks like a hash): c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
time: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
os: Windows_NT x64 10.0.19044
```
Steps to Reproduce:

1. just unfocus the window and wait two-three seconds with opened media player
2. profit

No problem with vscode.dev but I don't want to use it.

![screenshot](https://user-images.githubusercontent.com/81907213/160294230-bbd5414d-1a56-4cf3-8bcf-907615485b52.png)

![](https://user-images.githubusercontent.com/81907213/160294338-e2881e6e-1a49-42a9-8652-5cd743c49aa4.png)

![](https://user-images.githubusercontent.com/81907213/160294434-5762412b-3962-4c6e-8df6-33837c60a953.png)

**Comment by t0ngub1n** [comment]
EVEN MORE BLURRY

![even more blurry](https://user-images.githubusercontent.com/81907213/160294338-e2881e6e-1a49-42a9-8652-5cd743c49aa4.png)

**Comment by t0ngub1n** [comment]
![Снимок экрана (6)](https://user-images.githubusercontent.com/81907213/160294434-5762412b-3962-4c6e-8df6-33837c60a953.png)

what is that

**Comment by deepak1556** [comment]
Does the issue happen when you launch with `--disable-features=CalculateNativeWinOcclusion`

**Comment by t0ngub1n** [comment]
excuse me but how to enable `--disable-features=CalculateNativeWinOcclusion`?

**Comment by deepak1556** [comment]
You can open powershell or command prompt and start the program like `code-insiders.cmd --disable-features=CalculateNativeWinOcclusion`

**Comment by t0ngub1n** [comment]
> You can open powershell or command prompt and start the program like `code-insiders.cmd --disable-features=CalculateNativeWinOcclusion`

it got worse
text is blurry even without media player

**Comment by deepak1556** [comment]
Just to confirm this was tested with the latest insiders version https://code.visualstudio.com/insiders ?

**Comment by t0ngub1n** [comment]
> Just to confirm this was tested with the latest insiders version https://code.visualstudio.com/insiders ?

it wasn't. it was tested on stable version. and yes, insider build didnt fix anything\
also just noticed that it happens only on second workplace and not in the 1st one.

**Comment by deepak1556** [comment]
Can you check if the issue repros with `--disable-gpu` ?
