### ISSUE TITLE
Add vscode.markdown-language-features to test-remote-integration.sh proposed API exception

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#146172]
From @alexdima 

AFAIK the remote integration tests execute with a built client and server. But a built client or server don’t contain extension tests, because we don’t ship tests. So it loads up extensions from their checkout location. This means that the tested extensions are not built-in, because they are not in the extensions folder of the client or the server. It seems like this is a known issue in that file, because others have overcome this in the past by passing --enable-proposed-api to the integration test invocation -- https://github.com/microsoft/vscode/blob/dc44ff664989a8653528a5d61a56a42d89a8c838/scripts/test-remote-integration.sh#L66 . Maybe markdown needs the same treatment.

**Comment by dbaeumer** [comment]
Fixed in release/1.66 and main

**Comment by rzhao271** [comment]
Is this issue verifiable? If so, I'm wondering what are some verification steps for this issue?

**Comment by dbaeumer** [comment]
The verification is a successful stable build. Since we have two of them already, I will mark the issue as verified.
