### ISSUE TITLE
Ctrl+Alt+Up Down Arrow flips display upside down.

### ISSUE THREAD

**Issue by markThompson45** [Microsoft/vscode#14617]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Steps to Reproduce:

1. press ctrl+alt+down arrow

In your shortcuts on an empty window you say that this will add cursors. Instead it flips the display of everything on the screen upside down. You need to provide a different hotkey sequence for this.

**Comment by mbeckenbach** [comment]
Never realized that. But yes. It does. I think this is a feature of intel graphics, isnt it?

**Comment by mbeckenbach** [comment]
yes it is an intel feature but you can change the hotkeys.

![image](https://cloud.githubusercontent.com/assets/6654388/19779175/3a54170a-9c80-11e6-8a8e-98527f4a2078.png)

**Comment by markThompson45** [comment]
I ended up just disabling the hotkeys for Intel, due to the fact that I rarely use them, and can always do it through the interface. Thanks for helping me find the fix.

**Comment by weinand** [comment]
VS Code cannot anticipate all shortcuts used by these tools.
