### ISSUE TITLE
Extension details view should show Marketplace version of README and CHANGELOG

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#14616]
- VSCode Version:1.7.0 insiders

I'm not sure which version of the README and CHANGELOG is displayed in the details view but I think it should be the Marketplace versions.  We show the user what they will get if they install the update. For the changelog, the user should be able to match the changelog entry versions to their installed version which is displayed in the Extension view tile.

The other choice is also valid, show the user what they have installed but I prefer to see the latest version of both the README and CHANGELOG.

**Comment by joaomoreno** [comment]
#12913
