### ISSUE TITLE
Stack traces function names are always off by one?

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#14628]
See #13852

_Stack_ <br />TypeError: Cannot read property 'toString' of undefined<br />[/vs/editor/browser/viewParts/viewZones/viewZones.ts#L202:36 (toString)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/viewParts/viewZones/viewZones.ts#L202:36 %28toString%29)<br />[/vs/editor/browser/view/viewImpl.ts#L689:39 (removeZone)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/view/viewImpl.ts#L689:39 %28removeZone%29)<br />[/vs/editor/contrib/zoneWidget/browser/zoneWidget.ts#L132:13 (removeZone)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/contrib/zoneWidget/browser/zoneWidget.ts#L132:13 %28removeZone%29)<br />[/vs/editor/browser/view/viewImpl.ts#L959:9 (func)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/view/viewImpl.ts#L959:9 %28func%29)<br />[/vs/editor/browser/view/viewImpl.ts#L696:16 (safeInvoke1Arg)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/view/viewImpl.ts#L696:16 %28safeInvoke1Arg%29)<br />[/vs/editor/browser/view/viewImpl.ts#L951:9 (func)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/view/viewImpl.ts#L951:9 %28func%29)<br />[/vs/editor/browser/view/viewImpl.ts#L807:11 (safeInvokeNoArg)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/view/viewImpl.ts#L807:11 %28safeInvokeNoArg%29)<br />[/vs/base/common/eventEmitter.ts#L295:9 (func)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/common/eventEmitter.ts#L295:9 %28func%29)<br />[/vs/base/common/eventEmitter.ts#L225:20 (safeInvokeNoArg)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/base/common/eventEmitter.ts#L225:20 %28safeInvokeNoArg%29)<br />[/vs/editor/browser/view/viewImpl.ts#L806:31 (deferredEmit)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/view/viewImpl.ts#L806:31 %28deferredEmit%29)<br />

TypeError: Cannot read property 'toString' of undefined 
at t.removeZone (out/vs/workbench/workbench.main.js:60:18502) 
at Object.removeZone (out/vs/workbench/workbench.main.js:76:14756) 
at out/vs/workbench/workbench.main.js:45:5919 
at W (out/vs/workbench/workbench.main.js:75:30272) 
at out/vs/workbench/workbench.main.js:76:14832 
at F (out/vs/workbench/workbench.main.js:75:30208) 
at out/vs/workbench/workbench.main.js:76:17079 
at i (out/vs/workbench/workbench.main.js:29:21502) 
at e.deferredEmit (out/vs/workbench/workbench.main.js:29:24579) 
at t._renderOnce (out/vs/workbench/workbench.main.js:76:17049)

**Comment by ramya-rao-a** [comment]
@alexandrudima Where are you seeing the off by one issue? Can't find it ....

**Comment by alexandrudima** [comment]
/vs/editor/browser/viewParts/viewZones/viewZones.ts#L202:36 (toString)

should say

/vs/editor/browser/viewParts/viewZones/viewZones.ts#L202:36 (removeZone) because the stack location is inside the function named `removeZone`

**Comment by alexandrudima** [comment]
Hey @ramya-rao-a 

Can you point me to the source code where the deminifying is implemented. I can do a PR to fix this off-by-one issue. It annoys me everytime I see it.

![screen shot 2018-02-16 at 17 18 19](https://user-images.githubusercontent.com/5047891/36314405-6e3717a4-133d-11e8-92fe-691ba1424b24.png)

All the deminified stack trace function names are off by one.

**Comment by ramya-rao-a** [comment]
@alexandrudima I have pushed in a fix, but finding trouble publishing the website due jit access. Will get back to this on tuesday. Sorry for the wait.

**Comment by ramya-rao-a** [comment]
Done

I have tested with a few call stacks

Do keep an eye out for any discrepancies and let me know if you find any

**Comment by alexandrudima** [comment]
Nice! Thank you!
