### ISSUE TITLE
Update menu when reassigning keybindings or installing keybinding extension

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#14625]
Below, Ctrl+S has been reassigned to `workbench.action.relaodWindow`, and `Ctrl+I` has been assigned to `workbench.action.files.save`, but he File context menu has not been updated appropriately.

![image](https://cloud.githubusercontent.com/assets/762848/19784165/970e2b84-9c49-11e6-87d5-ab650aefddc7.png)

**Comment by bpasero** [comment]
Yes, that has always been like that but I think we can fix it easily.

**Comment by arthur801031** [comment]
@bpasero  May I work on this? I'm a first time contributor to vscode.

**Comment by bpasero** [comment]
Sure, feel free.

**Comment by arthur801031** [comment]
@bpasero Could you please help me out with these questions? Thank you!

- I think I need to make changes in vscode/out/vs/base/common/keybinding.js and vscode/out/vs/code/electron-main/menus.js, but I don't know how to debug these files since the code has already been run when vscode is opened. 

- How do I access user's keybindings.json file for the user's new keys?

**Comment by bpasero** [comment]
Let me forward the debug questions to our debug team: @roblourens @weinand @isidorn are we able to debug the Electron main side these days?

@arthur801031 I suggest to check how keybindings are resolved today right on startup (https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/menus.ts#L180) and then add a listener for keybindings.json changes to run a similar call to update the menu.

**Comment by arthur801031** [comment]
@bpasero 

It seems that Electron does not support updating menus dynamically: [https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/menus.ts#L197](url)
If the user quits and restarts vscode, the menus are updated according to keybindings.json. As long as the user restarts vscode, the menus should show the correct keybindings.

**Comment by bpasero** [comment]
That is true. On startup we read the keybindings from a cached location on disk, then we start a window and ask that window to resolve all keybindings. If the keybindings differ, we update the menu once again. Ugly, but the only way possible atm.

**Comment by arthur801031** [comment]
I've changed 2 keys in keybindings.json and I restarted vscode. When vscode was opened, the menus' shortcut keys have been updated accordingly.
<img width="1680" alt="screen shot 2016-11-14 at 5 02 39 pm" src="https://cloud.githubusercontent.com/assets/4562118/20258839/8b912e9a-aa8c-11e6-94e2-2b341790bd9b.png">
<img width="1680" alt="screen shot 2016-11-14 at 5 02 25 pm" src="https://cloud.githubusercontent.com/assets/4562118/20258836/8886cc5a-aa8c-11e6-9cf8-cce7def3349c.png">

So it seems what mousetraps ran into was that she didn't restart vscode after updating keybindings.json, so the menus were not updated accordingly.

**Comment by bpasero** [comment]
@arthur801031 yes, this issue is about updating the menu without the need for restart.

**Comment by arthur801031** [comment]
Hi @bpasero, I'm trying to create a listener for keybindings.json, but I can't get the keybindings.json file path right. Here is my code in the registerListeners function of /vscode/out/vs/code/electron-main/menus.js:
<img width="477" alt="screen shot 2016-11-15 at 9 31 02 am" src="https://cloud.githubusercontent.com/assets/4562118/20289694/33c4bd6e-ab16-11e6-933b-fa7edf7a2d88.png">

Here is the error output:
<img width="859" alt="screen shot 2016-11-15 at 9 32 17 am" src="https://cloud.githubusercontent.com/assets/4562118/20289715/51c43eb6-ab16-11e6-8752-ee583c87a69d.png">

Another question that I have is if I place these code inside src/vs/code/electron-main/menus.ts that piece of code wouldn't run, which means the error message wouldn't even show up. Please help. Thank you so much!

**Comment by bpasero** [comment]
Also applies to when installing a keymap extension (/cc @chrmarti). happy to review a PR on this one, I think what is needed is to:
* update the menu when a change to `keybindings.json` is detected (for example by using [`ConfigWatcher`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/config.ts#L41))
* update the menu when a keymap extension gets installed (ideally this could be triggered also from the main side by listening to extension events that happen in the shared process)

**Comment by bpasero** [comment]
Needs verification on **macOS**, **Windows** and **Linux**:
* keybindings in the menu still show as before and make sense for your config
* changing keybindings.json updates the menu live
* installing or uninstalling a keybindings extension and reloading the window updates the menu too
