### ISSUE TITLE
Incorrect formatting in unicode highlighting

### ISSUE THREAD

**Issue by ambar** [microsoft/vscode#146225]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.2
- OS Version: Darwin x64 20.6.0

Steps to Reproduce:

1. Input  fullwidth right parenthesis `（淡）x`
2. Hover the right parenthesis

<img width="688" alt="image" src="https://user-images.githubusercontent.com/105919/160514006-aaf69d4a-7e68-4276-8045-e0e0f9c3f6ca.png">

**Comment by ambar** [comment]
`)` should be escaped: `encodeURIComponent(')') === ')'`, `escape(')') === '%29'`

**Comment by hediet** [comment]
Thanks a lot for reporting & investigating! Up for a PR? 😉
