### ISSUE TITLE
Wrong tokenization for text in hover for Python comment

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14620]
Looking at this file with Python extension https://github.com/pallets/flask/blob/master/flask/config.py

Words like `for`, `from` are tokenized as Python keywords, even if they are in comment.

![width](https://cloud.githubusercontent.com/assets/4033249/19781109/b9b9fa12-9c3c-11e6-9a99-428576683d73.jpg)

~~Guess this is introduced while fixing #11331~~

Reproducible with Python extension in both Insider and stable.

**Comment by alexandrudima** [comment]
either @joaomoreno or @jrieken 

my guess is the comment text is indented with tabs which triggers this logic to treat it as code.

**Comment by octref** [comment]
Just curious if anyone knows how to inspect the dom structure of hover. Using `:hover` from Chrome devtool won't keep it there...

**Comment by octref** [comment]
The root cause is Python doc are written in [reStructuredText](http://docutils.sourceforge.net/rst.html), not Markdown.

**Comment by jrieken** [comment]
@DonJayamanne When a hover should not be interpreted as markdown you it needs to be escaped before passing it on

**Comment by DonJayamanne** [comment]
This has been fixed (https://github.com/DonJayamanne/pythonVSCode/issues/433).
Fix will be in the next release of the [Python extension](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python)
