### ISSUE TITLE
that it wont run 

### ISSUE THREAD

**Issue by tylerevact** [microsoft/vscode#146290]
on the terminal it wont elt me run but on the terminal it says this  and are u able to help with that and fixed it for me bc im confused
Issue Type: <b>Performance Issue</b>

it say somthing on the terminal are u able to help me it says this before i put it heres my email tony.willaims1177@gmail.com to fixed now this is what it says

gcc : The term 'gcc' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At line:1 char:74
+ ... nyw\OneDrive\Documents\C C++\VS code raylib\" ; if ($?) { gcc main.c  ...
+                                                               ~~~
    + CategoryInfo          : ObjectNotFound: (gcc:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon Silver 3050U with Radeon Graphics    (2 x 2296)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.42GB (0.35GB free)|
|Process Argv|--crash-reporter-id 0c2d4307-4b96-442b-81b4-1bb3292774a0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    88	   228	code main
    0	    71	  2136	   extensionHost
    0	    59	  6196	     "C:\Users\tonyw\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\tonyw\.vscode\extensions\streetsidesoftware.code-spell-checker-2.1.9\packages\_server\dist\main.js --node-ipc --clientProcessId=2136
    0	    29	  6728	     "C:\Users\tonyw\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\tonyw\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=2136
    0	    23	 10124	     c:\Users\tonyw\.vscode\extensions\ms-vscode.cpptools-1.9.7\bin\cpptools.exe
    0	    15	  4728	       c:\Users\tonyw\.vscode\extensions\ms-vscode.cpptools-1.9.7/bin/cpptools-srv.exe 10124 {CC97611F-114F-4131-A733-25051CCCB536}
    0	    10	  9168	       console-window-host (Windows internal process)
    0	    86	  2148	   gpu-process
    0	    23	  3404	   utility-network-service
    0	    57	  8380	   shared-process
    0	    32	  1236	     fileWatcher
    0	    54	  4952	     ptyHost
    0	     6	  3104	       console-window-host (Windows internal process)
    0	     5	  3212	       console-window-host (Windows internal process)
    0	    63	  4228	       C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     5	  9392	       console-window-host (Windows internal process)
    0	    76	 11988	       C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	 12244	       console-window-host (Windows internal process)
    0	    62	 13376	       C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    63	 14284	       C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	   135	  8428	   window (main.c - VS code raylib - Visual Studio Code)
    0	    14	 10944	   crashpad-handler
    2	    50	 13740	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (main.c - VS code raylib - Visual Studio Code)
|    Folder (VS code raylib): 9 files
|      File types: json(4) c(1) code-workspace(1) Android(1)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1) makefile(1)
|      Launch Configs: cppdbg(4);
```

</details>
<details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
ue4-snippets|CAP|2.0.1
doxdocgen|csc|1.4.0
code-runner|for|0.11.7
c-cpp-runner|fra|3.2.4
better-cpp-syntax|jef|1.15.13
remote-containers|ms-|0.224.3
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
code-spell-checker|str|2.1.9
lua|sum|2.6.7
cmake|twx|0.0.17
c-cpp-flag-debugging|uts|0.0.1
vscode-lldb|vad|1.7.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvidc:30447482
pynewfile477:30450038

```

</details>

**Comment by gjsjohnmurray** [comment]
Did you follow all the instructions at https://code.visualstudio.com/docs/cpp/config-mingw?

**Comment by rougeplane** [comment]
If you are compiling a C++ code file,  use g++ instead of gcc as gcc is for C files. Other than that: 

> Did you follow all the instructions at https://code.visualstudio.com/docs/cpp/config-mingw?

**Comment by meganrogge** [comment]
That usually means the command that you're trying to run isn't on your `PATH`

**Comment by tylerevact** [comment]
thanks for need I didn't use the instructions thanks
