### ISSUE TITLE
Menu items is actually emulating keyboard press?

### ISSUE THREAD

**Issue by imkzh** [microsoft/vscode#146283]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. open vscode
2. open any file
3. in menu, select `Help` > `Toggle Developer Tools` (you can see the kbd shortcut as ctrl+shift+I)
4. And surprisingly the opened file is formatted, or a message pops out:
![image](https://user-images.githubusercontent.com/5917425/160736273-ceb7258d-f59d-4419-a493-5c19f76151ce.png)

In keyboard shortcuts settings, we can see the `ctrl+shift+I` keybinding is registered to multiple command, and `Format Document` shares shortcut key with `Toggle Developer Tools`:

![image](https://user-images.githubusercontent.com/5917425/160735745-118cd2ae-ad07-4ca7-b8bc-dcba114e242d.png)

But, I was wondering why would clicking menu item call something else?

**Comment by imkzh** [comment]
Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T15:36:26.048Z (2 wks ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 4.15.0-23-generic

**Comment by sbatten** [comment]
@deepak1556 I haven't investigated yet, but is this a known behavior of electron menus that they trigger the specified keybinding shortcut?

**Comment by imkzh** [comment]
Any updates?

**Comment by deepak1556** [comment]
Yes this is default behavior of the menu action from the runtime, closing as issue is not actionable.
