### ISSUE TITLE
Obsolete extensions can cause high `shared-process` CPU usage (with possible solution)

### ISSUE THREAD

**Issue by bartvanandel** [microsoft/vscode#146201]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: Windows 11, Version 21H2 (OS Build 22000.527) (`code --status` reports it as "Windows_NT x64 10.0.22000")

Steps to Reproduce:

1. Use VSCode for a long time
2. Run into the issue randomly.

I'm aware that this is not really a nice reproduction scenario. However, I found out the hard way that VSCode would cause my fans to blast at full speed 100% of the time since a week or so. Can't really tell, I only found out after starting to work from home again where the ambient noise level is way lower.

Things I've tried:
- Tried running with `--disable-extensions` to no avail.
- Tried to get the existing dependencies to update, however the Extension view would just show a loading indicator and never even show the installed dependencies. Searching for new ones kept working though.
- Physically removing backups from the VSCode user profile on disk. Didn't help.

Finally, I noticed a file called `.obsolete` in the `data\extensions` directory. Physically removing the indicated plugin versions from disk did resolve the situation. Starting VSCode, I noticed that the high CPU usage by the `shared-process` process was gone. Then VSCode started updating plugins. And asked for a restart. Guess what? Same issue again after a restart! Fortunately, repeating the manual fix (manually delete obsolete plugin versions) fixed the problem again.

Looks like VSCode has some trouble auto uninstalling these obsolete plugin versions. If it helps, I've installed VSCode using `scoop install -g vscode`.

<details>
    <summary>Output of `code --status`</summary>

    [main 2022-03-28T17:07:12.171Z] [File Watcher (node.js)] correcting a path to watch that seems to be a symbolic link or wrong casing (original: c:\ProgramData\scoop\apps\vscode\1.65.2\data\user-data\User, real: C:\ProgramData\scoop\persist\vscode\data\user-data\User)
    [main 2022-03-28T17:07:12.173Z] [File Watcher (node.js)] correcting a path to watch that seems to be a symbolic link or wrong casing (original: c:\ProgramData\scoop\apps\vscode\1.65.2\data\user-data\User\settings.json, real: C:\ProgramData\scoop\persist\vscode\data\user-data\User\settings.json)
    Version:          Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
    OS Version:       Windows_NT x64 10.0.22000
    CPUs:             Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)
    Memory (System):  31.75GB (6.70GB free)
    VM:               0%
    Screen Reader:    no
    Process Argv:     --crash-reporter-id 4d8e1a02-1872-4066-90bf-13acebd457a0
    GPU Status:       2d_canvas:                  enabled
                      gpu_compositing:            enabled
                      multiple_raster_threads:    enabled_on
                      oop_rasterization:          enabled
                      opengl:                     enabled_on
                      rasterization:              enabled
                      skia_renderer:              enabled_on
                      video_decode:               enabled
                      vulkan:                     disabled_off
                      webgl:                      enabled
                      webgl2:                     enabled
    
    CPU %   Mem MB     PID  Process
        0      108   14432  code main
        0       82    1684     shared-process
        0       70   33736       fileWatcher
        0       74   37884       ptyHost
        0        9   21888         console-window-host (Windows internal process)
        0       71   40912         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
        0      208   23168     gpu-process
        0       25   26748     crashpad-handler
        0       36   32176     utility-network-service
        0      291   32876     window (package.json - Home - Visual Studio Code)
        0      199   37172     extensionHost
        0        9    4660       C:\WINDOWS\system32\cmd.exe /c C:\ProgramData\scoop\apps\nvm\current\nodejs\nodejs\npm.cmd start
        0       44   28988         "C:\ProgramData\scoop\apps\nvm\current\nodejs\nodejs\\node.exe"  "C:\ProgramData\scoop\apps\nvm\current\nodejs\nodejs\node_modules\npm\bin\npm-cli.js" start
        0        8    4568           C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/start.js
        0     1115   38612             node  scripts/start.js
        0       37   29928               C:\ProgramData\scoop\apps\nvm\current\nodejs\nodejs\node.exe c:\ProgramData\scoop\apps\vscode\1.65.2\resources\app\extensions\ms-vscode.js-debug\src\watchdog.bundle.js
        0       62   39672               C:\ProgramData\scoop\apps\nvm\current\nodejs\nodejs\node.exe --max-old-space-size=2048 d:\src\dytter\Home\node_modules\fork-ts-checker-webpack-plugin\lib\typescript-reporter\reporter\TypeScriptReporterRpcService.js
        0       36   29076                 C:\ProgramData\scoop\apps\nvm\current\nodejs\nodejs\node.exe c:\ProgramData\scoop\apps\vscode\1.65.2\resources\app\extensions\ms-vscode.js-debug\src\watchdog.bundle.js
        0       62   40272               C:\ProgramData\scoop\apps\nvm\current\nodejs\nodejs\node.exe --max-old-space-size=2048 d:\src\dytter\Home\node_modules\fork-ts-checker-webpack-plugin\lib\typescript-reporter\reporter\TypeScriptReporterRpcService.js
        0       36   19948                 C:\ProgramData\scoop\apps\nvm\current\nodejs\nodejs\node.exe c:\ProgramData\scoop\apps\vscode\1.65.2\resources\app\extensions\ms-vscode.js-debug\src\watchdog.bundle.js
        0       33   33828           C:\ProgramData\scoop\apps\nvm\current\nodejs\nodejs\node.exe c:\ProgramData\scoop\apps\vscode\1.65.2\resources\app\extensions\ms-vscode.js-debug\src\watchdog.bundle.js
        0       15   37364         console-window-host (Windows internal process)
        0      107    8172       C:\ProgramData\scoop\apps\vscode\current\Code.exe --ms-enable-electron-run-as-node c:\ProgramData\scoop\apps\vscode\1.65.2\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain --node-ipc --clientProcessId=37172
        0      123   17616       C:\ProgramData\scoop\apps\vscode\current\Code.exe --ms-enable-electron-run-as-node c:\ProgramData\scoop\apps\vscode\1.65.2\data\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js --node-ipc --clientProcessId=37172
        0       68   18476       C:\ProgramData\scoop\apps\vscode\current\Code.exe --ms-enable-electron-run-as-node c:\ProgramData\scoop\apps\vscode\1.65.2\resources\app\extensions\css-language-features\server\dist\node\cssServerMain --node-ipc --clientProcessId=37172
        0      256   31976       C:\ProgramData\scoop\apps\vscode\current\Code.exe --ms-enable-electron-run-as-node --max-old-space-size=3072 c:\ProgramData\scoop\apps\vscode\1.65.2\resources\app\extensions\node_modules\typescript\lib\tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\<me>\AppData\Local\Temp\vscode-typescript\14e9917c2832b41a136e\tscancellation-f69068fe23923dbab46f.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
        0       75   40504         C:\ProgramData\scoop\apps\vscode\current\Code.exe --ms-enable-electron-run-as-node c:/ProgramData/scoop/apps/vscode/1.65.2/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation C:/Users/<me>/AppData/Local/Microsoft/TypeScript/4.6 --enableTelemetry --typesMapLocation c:/ProgramData/scoop/apps/vscode/1.65.2/resources/app/extensions/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation
        0       80   32752       C:\ProgramData\scoop\apps\vscode\current\Code.exe --ms-enable-electron-run-as-node --max-old-space-size=3072 c:\ProgramData\scoop\apps\vscode\1.65.2\resources\app\extensions\node_modules\typescript\lib\tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName C:\Users\<me>\AppData\Local\Temp\vscode-typescript\14e9917c2832b41a136e\tscancellation-10108dbb305ba1b86780.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
        0       26   35316       C:\ProgramData\scoop\persist\vscode\data\extensions\ms-mssql.mssql-1.13.0\sqltoolsservice\3.0.0-release.205\Windows\SqlToolsResourceProviderService.exe --log-file c:\ProgramData\scoop\apps\vscode\1.65.2\data\user-data\logs\20220328T171042\exthost1\ms-mssql.mssql\resourceprovider.log --tracing-level Critical
        0        8   27304         console-window-host (Windows internal process)
        0       43   40088       C:\ProgramData\scoop\persist\vscode\data\extensions\ms-mssql.mssql-1.13.0\sqltoolsservice\3.0.0-release.205\Windows\MicrosoftSqlToolsServiceLayer.exe
        0        8   36804         console-window-host (Windows internal process)
        0       65   40184       C:\ProgramData\scoop\apps\vscode\current\Code.exe --ms-enable-electron-run-as-node c:\ProgramData\scoop\apps\vscode\1.65.2\data\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js --node-ipc --clientProcessId=37172
    
    Workspace Stats:
    |  Window (package.json - Home - Visual Studio Code)
    |    Folder (Home): 835 files
    |      File types: svg(292) js(131) json(111) jsx(76) scss(74) ttf(7) jpg(7)
    |                  yml(4) html(4) png(3)
    |      Conf files: launch.json(1) settings.json(1) webpack.config.js(1)
    |                  package.json(1) tsconfig.json(1)
    |      Launch Configs: node
</details>

<details>
    <summary>Output of `code --list-extensions`</summary>
  
    adelphes.android-dev-ext
    bencoleman.armview
    byCedric.vscode-expo
    dbaeumer.vscode-eslint
    DotJoshJohnson.xml
    eamodio.gitlens
    esbenp.prettier-vscode
    firsttris.vscode-jest-runner
    fknop.vscode-npm
    Gruntfuggly.todo-tree
    jock.svg
    jtr.vscode-position
    mechatroner.rainbow-csv
    ms-azure-devops.azure-pipelines
    ms-azuretools.vscode-azureappservice
    ms-azuretools.vscode-azurefunctions
    ms-azuretools.vscode-azureresourcegroups
    ms-azuretools.vscode-azurestorage
    ms-azuretools.vscode-azurevirtualmachines
    ms-azuretools.vscode-bicep
    ms-azuretools.vscode-cosmosdb
    ms-azuretools.vscode-docker
    ms-dotnettools.csharp
    ms-dotnettools.vscode-dotnet-runtime
    ms-mssql.data-workspace-vscode
    ms-mssql.mssql
    ms-mssql.sql-database-projects-vscode
    ms-python.python
    ms-python.vscode-pylance
    ms-toolsai.jupyter
    ms-vscode-remote.remote-containers
    ms-vscode-remote.remote-wsl
    ms-vscode.azure-account
    ms-vscode.azurecli
    ms-vscode.powershell
    ms-vscode.vscode-node-azure-pack
    msazurermtools.azurerm-vscode-tools
    msjsdiag.vscode-react-native
    mtxr.sqltools
    planbcoding.vscode-react-refactor
    RandomFractalsInc.geo-data-viewer
    viktorzetterstrom.non-breaking-space-highlighter
    yzhang.markdown-all-in-one
</details>

The `.obsolete` file is still here after a restart (could be caused by even newer plugin versions, haven't checked yet).

<details>
    <summary>`cat .obsolete | jq`</summary>

    {
      "ms-vscode.azure-account-0.9.11": true,
      "ms-azuretools.vscode-bicep-0.4.1124": true,
      "ms-vscode-remote.remote-wsl-0.63.13": true,
      "ms-toolsai.jupyter-2021.11.1001550889": true,
      "ms-vscode-remote.remote-containers-0.209.6": true,
      "ms-python.vscode-pylance-2022.2.1": true,
      "esbenp.prettier-vscode-9.2.0": true,
      "mechatroner.rainbow-csv-2.0.0": true,
      "firsttris.vscode-jest-runner-0.4.47": true,
      "ms-vscode.azure-account-0.10.0": true,
      "ms-azuretools.vscode-azureappservice-0.23.0": true,
      "ms-azuretools.vscode-docker-1.19.0": true,
      "ms-azure-devops.azure-pipelines-1.195.0": true,
      "msjsdiag.vscode-react-native-1.9.1": true,
      "ms-azuretools.vscode-azurefunctions-1.6.0": true,
      "eamodio.gitlens-11.7.0": true,
      "msazurermtools.azurerm-vscode-tools-0.15.5": true,
      "ms-python.python-2022.0.1814523869": true,
      "ms-mssql.mssql-1.12.0": true,
      "ms-azuretools.vscode-bicep-0.4.1272": true,
      "ms-dotnettools.csharp-1.24.0": true
    }
</details>

**Comment by sandy081** [comment]
VS Code tries to clean up obsolete extensions on restart. If you think this is impacting, can you please share the following logs while this is happening?

- F1 > Open View... > Log (Shared)

**Comment by bartvanandel** [comment]
I'll keep an eye out and report back when this happens again. I haven't noticed the issue since reporting it 9 days ago, but it might just resurface.

**Comment by sandy081** [comment]
Sure, closing it for now. Please reopen it when you see this issue again with requested info.
