### ISSUE TITLE
Code documentation <code> blocks format code content with escapes.

### ISSUE THREAD

**Issue by mhouckcd** [microsoft/vscode#146218]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2 c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1 x64
- OS Version: 

> Edition	Windows 10 Pro
> Version	21H1
> Installed on	‎3/‎12/‎2021
> OS build	19043.1586
> Experience	Windows Feature Experience Pack 120.2212.4170.0
> 

Steps to Reproduce:

1. Create XML documentation with code blocks
2. Insure code blocks do not have illegal characters (as per https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#code)
3. View shows dots, and other strings escaped (see attached images)

```
/// <summary>
/// Extension method used for a more terse creation of a list from a null list already instanced or created elsewhere.
/// i.e. Given: 
/// <code>
///     List&lt;CustomObjectType&gt; co;
/// </code>
/// we may create a quick instance as so:
/// <code>
///     co = co.Init();
/// </code>
/// as opposed to:
/// <code>
///     co = new List&lt;CustomObjectType&gt;();
/// </code>
/// I would like to be able to do this as just co.Init();, however due to a restriction on the language itself
/// you are unable to perform a ref this on non struct types. 
/// </summary>
public static List<T> Init<T>(this List<T> nullListToInitialize)
{
    return new List<T>();
}
```

VSCode view of the documentation
![vscode-escape-code-blocks](https://user-images.githubusercontent.com/102558897/160495878-8b634405-89c0-4cdc-a086-b6f43b7f7727.png)

Visual Studio display of same comment (2022 in this example):
![vs2022-noescape-code-block](https://user-images.githubusercontent.com/102558897/160496095-b2164c71-99f3-45b9-83c7-c9cb69450b27.png)

**Comment by mjbvz** [comment]
I think this should start over on the c# extension

If they find there's an issue with VS Code itself, they can then provide a self contained example extension that demonstrates the problem 

/extC#
