### ISSUE TITLE
Existing GIT repository not recognized/found after opening existing Workspace file _or_ folder

### ISSUE THREAD

**Issue by g40** [microsoft/vscode#146251]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: Windows 10 x64 1909

Steps to Reproduce:

1. This is _not_ a problem using the same version of VS Code on Linux (Ubuntu 20.04 for example)
2. Open a shell and create a new directory (`test`). `cd test`
3.  `git init`
4. `touch main.py`
5. `git add main.py`
6. Open folder (`test`) in VS Code.
7. Open `Source Control` tab: 

![image](https://user-images.githubusercontent.com/812250/160628337-55701287-9562-4f08-a93b-9d45cf377154.png)

**Comment by lszomoru** [comment]
* Are you able to reproduce the same behaviour with the latest VS Code Insiders release?
* Are you able to reproduce the same behaviour if you start `code` with `--disable-extensions` flag?
* If you invoke the `Show Running Extensions` command, do you see the `Git` extension in the list of running extensions?
* If you invoke the `Git: Show Git Output` command, and see if that causes the `Git` extension to activate? 
* If you invoke the `Git: Show Git Output` command, could you please share the contents of the output channel?

**Comment by g40** [comment]
1. Yes - here is an opened workspace with a working GIT repository
 
![image](https://user-images.githubusercontent.com/812250/160852827-65724642-852e-4ec7-9de1-9f690fc77eee.png)

2. All extensions _are_ disabled as per bug report 
![image](https://user-images.githubusercontent.com/812250/160851062-e58bc09d-81f0-470b-82cc-fd873a999627.png)

3. Yes 
![image](https://user-images.githubusercontent.com/812250/160851826-9ab45909-c966-42ce-aa70-f9d11e48df4e.png)

4. Apparently so.
5. ```
C:\Users\moi\AppData\Local\Programs\Git\cmd\git.exe
[2022-03-29T18:23:26.137Z] Validating found git in: R:\apps\msys64\usr\bin\git.exe
[2022-03-29T18:23:26.358Z] Using git 2.27.0 from R:\apps\msys64\usr\bin\git.exe
```

**Comment by lszomoru** [comment]
@g40, thank you very much for the provided information. Based on the shared log, it looks like VS Code is using the version of git that is being installed through MSYS2 (ex: `R:\apps\msys64\usr\bin\git.exe`). Could you please confirm that? I am asking as currently, VS Code does not support this version of git (feature request is tracked [here](https://github.com/microsoft/vscode/issues/143165)). To make sure that all git functionality within VS Code works as expected, please install [Git for Windows](https://gitforwindows.org/).

**Comment by g40** [comment]
@lszomoru Thank you for your help. Much appreciated. 

This raises a question though: How is Code picking up the msys version? 

I do have both installed and Git for Windows (GfW) is definitely the executable that is found. 

Let me add a bit more information. Running a command shell shows, I think,  the right path is followed. 

```
r:\>where git
r:\apps\Git\cmd\git.exe
r:\>which git
/r/apps/git/cmd/git
r:\>git --version
git version 2.35.1.windows.2
```
Do let me know if you need more info.

**Comment by lszomoru** [comment]
@g40, here is the order, and the folders that are being probed by VS Code in an attempt to find git:
- paths specified in the `git.path` setting. Do you have any values set here? Can you reset the value of this setting?
- System folders in the order that is specified [here](https://github.com/microsoft/vscode/blob/9f7eaad160412c1ad588802b88b92838dbc43fc3/extensions/git/src/git.ts#L137-L138).
- PATH environment variable

**Comment by g40** [comment]
@lszomoru Thanks again. Where would I find the `git.path` setting? 

Do you know precisely why the msys64 version does not work? (https://github.com/microsoft/vscode/issues/143165)

**Comment by lszomoru** [comment]
* Please invoke the `Preferences: Open Settings (UI)` command from the command palette.
* Run a search for `git.path` which should reveal the setting. Use the cog action next to the setting name to reset it.

**Comment by g40** [comment]
Thanks again @lszomoru. The resulting JSON paste is `"git.path": null`.

I have one more question. When I opened VSC this morning it updated to 1.66.0. The results from `Git: Show Git Output` are now very different to the previous version. Question is why does the output say `found git` - when there is only one copy and that is located in `r:\apps\git`. Makes it more than a bit confusing!

Anyway, once again, muchas gracias for your support here. 

```
[2022-03-31T14:23:12.398Z] Validating found git in: C:\Program Files\Git\cmd\git.exe
[2022-03-31T14:23:12.414Z] Validating found git in: C:\Program Files (x86)\Git\cmd\git.exe
[2022-03-31T14:23:12.416Z] Validating found git in: C:\Program Files\Git\cmd\git.exe
[2022-03-31T14:23:12.419Z] Validating found git in: C:\Users\JEvans\AppData\Local\Programs\Git\cmd\git.exe
[2022-03-31T14:23:15.045Z] Validating found git in: r:\apps\git\cmd\git.exe
[2022-03-31T14:23:15.171Z] Using git 2.35.1.windows.2 from r:\apps\git\cmd\git.exe
```

**Comment by g40** [comment]
Thanks again @lszomoru. The resulting JSON paste is "git.path": null.

I have one more question. When I opened VSC this morning it updated to 1.66.0. The results from Git: Show Git Output are now very different to the previous version. Question is why does the output say found git - when there is only one copy and that is located in r:\apps\git. Makes it more than a bit confusing!

Anyway, once again, muchas gracias for your support here.

[2022-03-31T14:23:12.398Z] Validating found git in: C:\Program Files\Git\cmd\git.exe
[2022-03-31T14:23:12.414Z] Validating found git in: C:\Program Files (x86)\Git\cmd\git.exe
[2022-03-31T14:23:12.416Z] Validating found git in: C:\Program Files\Git\cmd\git.exe
[2022-03-31T14:23:12.419Z] Validating found git in: C:\Users\moi\AppData\Local\Programs\Git\cmd\git.exe
[2022-03-31T14:23:15.045Z] Validating found git in: r:\apps\git\cmd\git.exe
[2022-03-31T14:23:15.171Z] Using git 2.35.1.windows.2 from r:\apps\git\cmd\git.exe

**Comment by lszomoru** [comment]
@g40, VS Code does not support the version of git installed with MSYS2 because of the format of the path that is being returned by various `git` commands. In the log above, VS Code has found `git.exe` in `r:\apps\git\cmd\git.exe`. Does this mean that the repository discovery has completed successfully, or VS Code is still not able to discover the repository? Are there any lines *after*, or is this the complete log?

**Comment by g40** [comment]
@lszomoru Version 1.66 works as expected. Thanks again for the help.
