### ISSUE TITLE
Disabling hover references doesn't apply to .vue files

### ISSUE THREAD

**Issue by mattgilbertnet** [microsoft/vscode#146256]
Issue Type: <b>Feature Request</b>

1) Disable HTML > Hover: References
2) Create a file with name ending in .vue.
3) Add a <style> tag with something like this:
<style>
h1 {
  margin-bottom: 0.5em;
}
</style>

4) Hover over margin-bottom, or almost anything. You will recieve an intrusive lesson in this basic css property that covers up the file you are working on.

Yes, the setting is specific to "HTML". But the ability to disable these ridiculous MDN tooltips in other files is crucial to productivity, ease-of-use, sanity, accessibility, and wrist health. This issue has been raised many times, and it seems as if Microsoft is worried about the inevitable dip in accidental traffic to the MDN site. I'm considering switching to a different editor.

VS Code version: Code 1.65.2 (Universal) (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

**Comment by IllusionMH** [comment]
Embedded languages use different settings  and there 4 settings for `hover documentation` which you can toggle as you need.

----

> seems as if Microsoft is worried about the inevitable dip in accidental traffic to the MDN site

Are you confusing MDN (from Mozilla) with MSDN (from Microsoft) website which was discontinued long time ago?

**Comment by mattgilbertnet** [comment]
Ah, you're right. My bad.
