### ISSUE TITLE
Improve progress reporting for upload, download, import progress in explorer

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#146226]
<img width="260" alt="CleanShot 2022-03-28 at 19 45 23@2x" src="https://user-images.githubusercontent.com/35271042/160522597-6d8f754a-efa6-4cf7-af6c-405afd5e0872.png">

<img width="500" src="https://user-images.githubusercontent.com/35271042/160522688-72be26e9-3dc1-4198-aea4-273552895976.png">

1. connect to a remote (ssh/codespaces)
2. upload a large file (mine was 1gb)
3. :bug: progress never shows any specific info and feel like it's stuck
4. :bug: also noticed that the status bar just says "copy" and then when clicking on it the notification shows two items and closing the notification center shows the title of the file

In my specific case, I was hoping to see XX of XX mb/gb uploaded or even a % to know that it's still working on uploading, like:

<img width="247" alt="CleanShot 2022-03-28 at 19 51 53@2x" src="https://user-images.githubusercontent.com/35271042/160523387-2f80b5c6-ad3a-4dec-a9b8-146fa73efc9a.png">

**Comment by bpasero** [comment]
We have a few places where we show progress for uploading, downloading and importing:

https://github.com/microsoft/vscode/blob/32d40cf44e893e87ac33ac4f08de1e5f7fe077fc/src/vs/workbench/contrib/files/browser/fileImportExport.ts#L89

https://github.com/microsoft/vscode/blob/32d40cf44e893e87ac33ac4f08de1e5f7fe077fc/src/vs/workbench/contrib/files/browser/fileImportExport.ts#L409

https://github.com/microsoft/vscode/blob/32d40cf44e893e87ac33ac4f08de1e5f7fe077fc/src/vs/workbench/contrib/files/browser/fileImportExport.ts#L590

We may not get all the information we need such as knowing the overall size, but if we do we should make sure that the label for the progress is as accurate as possible.

This sounds like a fun area for a contribution where someone can geek out on providing the best progress info possible. As such, opening for help wanted.

**Comment by neel-desh** [comment]
I love using vs code and I would love to contribute, I was searching for good first issues.
Can I pick this issue? @bpasero

**Comment by bpasero** [comment]
Sure, anyone can pick it with a meaningful reasonably small PR 👍

**Comment by neel-desh** [comment]
I will start the work on this then.

**Comment by neel-desh** [comment]
I asked myself this question, as a vs code user while transferring the files what information I would like to see.

1.  From where the files are coming from and where are the files going ( source and destination )?
2. How many files are there to transfer?
3. How much time it would take to transfer those files? ( Time remaining )
4. How much of the file transfer is done at the current state? ( Current Progress. eg: 70% done.. )
5. What is the rate at which the files are being transferred? 

This list is not exhaustive, there might be some things that are missing, but it's something we could start with for now.

I would love some feedback on this @bpasero 

PS: I have started reading, understanding the codebase and how files are structured.

**Comment by bpasero** [comment]
If we can copy/mimic what typically browsers show when you download or upload a file I think that would be nice, but it is not clear to me we get at the level of information easily. For example, when the browser takes care of the upload, we may not get hold of the transfer speed easily.

**Comment by yume-chan** [comment]
Related #111580

**Comment by neel-desh** [comment]
![Bottom](https://user-images.githubusercontent.com/43532747/161004345-2363a87b-e34f-471c-a1af-d1596ea888fd.jpeg)
![In Browser Downloads ](https://user-images.githubusercontent.com/43532747/161004351-42e446df-7733-48cf-936e-d91b2cb5b7d6.jpeg)

This information is being displayed in the browser

**Comment by bpasero** [comment]
Yeah I think Chrome browser is a pretty good example of a meaningful progress indicator.

**Comment by neel-desh** [comment]
> Yeah I think Chrome browser is a pretty good example of a meaningful progress indicator.

So, how should I go with this?

**Comment by neel-desh** [comment]
@bpasero What's the decision on this, I'm free this weekend, and I would love to start coding this improvement.

**Comment by bpasero** [comment]
I am not sure I follow, what decision you ask for? This issue is opened for contribution in a PR and I am happy to review a PR, but I cannot assist in creating the PR / the initial prototype. Sorry if I did not make that clear, but I tried to signal that I cannot devote time into this issue other than reviewing a working solution.

**Comment by neel-desh** [comment]
Oh great then, ill raise the pr and tag you.

Thanks.

**Comment by neel-desh** [comment]
Im not able to make any progress, I'm just not able to start writing code..
