### ISSUE TITLE
Glob matcher fails to check on `Promise` for expression matching

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#146294]
While reviewing some code in `glob.ts` I noticed potential issues:

https://github.com/microsoft/vscode/blob/ce3f26732fdce460f16a439b9bc80a70983bfbc4/src/vs/base/common/glob.ts#L582-L585

and

https://github.com/microsoft/vscode/blob/ce3f26732fdce460f16a439b9bc80a70983bfbc4/src/vs/base/common/glob.ts#L621-L624

Will wrongly stop the `for` loop when the result is a `Promise` even when that result resolves to `null`.

Would be good to have a test case for this too.

**Comment by bpasero** [comment]
@roblourens I think you added the support for `Promise` for the expression matching via https://github.com/microsoft/vscode/commit/188ef21ab32a9eb311c9a3ce4e6dd3c49910220e, do we really still need this? I feel this makes glob matching overly complicated. Checking on usages, I think search component uses it to lazily resolve children...

**Comment by bpasero** [comment]
PR: https://github.com/microsoft/vscode/pull/146304

**Comment by roblourens** [comment]
Are you suggesting to resolve children before doing the glob matcher? It would be a lot faster to avoid matching children until you need them. I don't like the flexible typing of this though. It should be explicitly sync or not.
