### ISSUE TITLE
Intermittent failing storage unit tests

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#146280]
Refs https://dev.azure.com/monacotools/Monaco/_build/results?buildId=164046&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=821d316a-2fa3-581f-c34c-57a961b8e328&l=9386

This might be a one of issue due to flakiness since the builds following that were fine, but nevertheless worth confirming from the owner about the resource contention.

**Comment by bpasero** [comment]
Likely caused by my tests for using `VACUUM` in SQLite, I have reverted those changes.
