### ISSUE TITLE
SQLite Storage Library        "after each" hook for "very large item value":        Error: EBUSY: resource busy or locked, unlink 'C:\Users\CLOUDT~1\AppData\Local\Temp\vsctests\storagelibrary\PX2TK7Fe\storage.db'       +

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#146231]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=163641&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=821d316a-2fa3-581f-c34c-57a961b8e328

**Comment by bpasero** [comment]
That was fixed 2min later with https://github.com/microsoft/vscode/commit/8b284de9b23e27457ef4343f49b4638be00efbdd
