### ISSUE TITLE
Tmux in integrated terminal ignores mouse scroll events/shits itself on selection events

### ISSUE THREAD

**Issue by wilrnh** [Microsoft/vscode#14627]
- VSCode Version: 1.6.1
- OS Version: osx 10.11.6

Steps to Reproduce:

1. Open integrated terminal in vscode
2. `tmux attach`
3. Enable mouse mode in tmux `set -g mouse on`
4. Scroll or select text in terminal window

Maybe not an issue with vscode itself, but thought I might open this here since this is where I'm experiencing this. All mouse activity works pretty perfectly in Terminal.app

**Comment by Tyriar** [comment]
This is likely an upstream issue. Could you check the https://github.com/sourcelair/xterm.js demo and report there if so?

**Comment by wilrnh** [comment]
Reproduced in the demo. Moved to upstream.

**Comment by Tyriar** [comment]
Thanks!

**Comment by piggyslasher** [comment]
https://github.com/sourcelair/xterm.js/issues/329#issuecomment-292895984

![image](https://cloud.githubusercontent.com/assets/1991125/24855124/2887153a-1e13-11e7-9740-a633cfc500fe.png)

**Comment by jtanx** [comment]
Although I can get this to work when running VSCode on Linux/Ubuntu, this doesn't work when running VSCode on Windows under a git bash ssh session.
