### ISSUE TITLE
Webview integration tests timing out on GitHub CI

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#146272]
Seeing webview integration tests timeout more often today. This specifically seems to happen on the GitHub CI.

https://github.com/microsoft/vscode/runs/5742978871?check_suite_focus=true
https://github.com/microsoft/vscode/runs/5742931259?check_suite_focus=true
https://github.com/microsoft/vscode/runs/5742931058?check_suite_focus=true
https://github.com/microsoft/vscode/runs/5741763332?check_suite_focus=true
https://github.com/microsoft/vscode/runs/5742831884?check_suite_focus=true
https://github.com/microsoft/vscode/runs/5742831969?check_suite_focus=true

Azure Pipeline failure
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=164020&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=07088cf7-fede-5f74-0d50-155edd53af7d

**Comment by mjbvz** [comment]
Removed for now with #157155
