### ISSUE TITLE
Latest Update broke it (Februrary Update)

### ISSUE THREAD

**Issue by alone-jpeg** [microsoft/vscode#146216]
Issue Type: <b>Bug</b>

I had reinstalled vscode with teh November update and vscode forcefully made me install latest version of vscode despiteI setting the update to manual it somehow hijacked my command and updated itself with the latest February update. VS code started to break from January update and February made it totally useless. A computer where I can parallelly use Google Chrome with 50 Tabs and Adobe illustrator and Audition same time vs code is totally unresponsive. Before anyone starts with Extention even disabling the extentions the problem presists. MS just broke it!

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (2.10GB free)|
|Process Argv|--crash-reporter-id 0afb1ed3-d4ee-4cec-8509-93faf532b48f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.38.1
go|gol|0.32.0
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.3
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
ruby|reb|0.28.1
vscode-ruby|win|0.28.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvid2:30447481
cppdebugcf:30451567
pynewfile477cf:30450039

```

</details>

**Comment by bpasero** [comment]
> VS code started to break from January update and February made it totally useless.

How so?

**Comment by alone-jpeg** [comment]
Okay, here's the deal, On October 2021 version VS code has a bug with command prompt it won't show run button for running my code on October update bit for November update everything works perfectly fine! Previously I've used bisect option and disabling all extensions but unfortunately vs still froze significantly for January and February updates!

That means it's not for some extension the freeze was happening rather its something with the core update that broke something with Windows 11

Can you help?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by alone-jpeg** [comment]
I can reproduce the same issue with the nightly build of vs code. Though the freezing not as severe as the version 1.65.2

**Comment by bpasero** [comment]
How does the freeze surface and when?

**Comment by mhesham93** [comment]
My VS started freezing too in the latest version, MacOS 12.3 (M1) here.

**Comment by alone-jpeg** [comment]
> How does the freeze surface and when?

When I launch the VS code it slights sllows down activitiy within it's windows and after I open-up a windows it just freezes abruptly!

**Comment by alone-jpeg** [comment]
> My VS started freezing too in the latest version, MacOS 12.3 (M1) here.

Same! I'm facing with Windows 11. I believe the new functions that Microsoft Implemented they're the initial reason behind such freezing.

**Comment by alone-jpeg** [comment]
I think it might be "VS code for web" and "Setting Editor" these two update might be the culprit cuz I had seen some improvent after disabling the GitHub Extention but still it was so freezing it was unusable anyway.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
