### ISSUE TITLE
`ensureAllNewCellsHaveCellIds` leaks 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#146240]
The [`ensureAllNewCellsHaveCellIds`](https://github.com/microsoft/vscode/blob/998ee04a724e9ad1b64069bf4ec88c59b4129b5a/extensions/ipynb/src/cellIdService.ts#L17)-function listens for notebook change event but doesn't ever stop doing that, e.g it's disposable isn't clear or collected in the extension context

**Comment by jrieken** [comment]
For clarity it should likely also do a check for the notebook type. It seems to work for all possible types and if a foreign notebook happens to have fitting metadata it is receiving cell ids.

**Comment by DonJayamanne** [comment]
> disposable isn't clear or collected in the extension context

Perhaps I'm missing something, but I thought passing the subscriptions array like done here would clear the disposable 
`notebooks.onDidChangeNotebookCells(onDidChangeNotebookCells, undefined, context.subscriptions);`
Or do I need to do something else?

**Comment by jrieken** [comment]
Oh, my bad! I didn't see that 🙈
