### ISSUE TITLE
can't open file or dir

### ISSUE THREAD

**Issue by junkeLee** [microsoft/vscode#146299]
Issue Type: <b>Bug</b>

I want open some dir, use menu 'file -> open...', but not work

VS Code version: Code 1.65.2 (Universal) (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id 5a7df1b0-2235-4c40-9a5e-cf1076b61b71|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|13.3.0
simple-react-snippets|bur|1.2.6
dart-code|Dar|3.36.0
flutter|Dar|3.36.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.5
Angular2|joh|13.0.0
intellij-idea-keybindings|k--|1.5.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.21.0
vscode-language-pack-zh-hans|MS-|1.65.3
remote-containers|ms-|0.224.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvid2:30447481
cppdebug:30451566
pynewfile477:30450038

```

</details>

**Comment by gjsjohnmurray** [comment]
> but not work

/needsMoreInfo

If someone else asked you like this to solve their problem, where would you start?
