### ISSUE TITLE
Integrated terminal should trim whitespace from copied lines

### ISSUE THREAD

**Issue by bbarry** [Microsoft/vscode#14624]
- VSCode Version: 1.6.1
- OS Version: Win7 x64

Steps to Reproduce:
1. open integrated terminal (configured to powershell in my case)
2. run a command to get multiple lines 
3. select multiple lines
4. copy (`ctrl+shift+c`)
5. paste into an editor window

Expected:

\5. trimmed output

Actual:

\5. many spaces at right side of terminal copypasta

**Comment by Tyriar** [comment]
I think this might be a Windows only issue as I haven't seen it in a long time on Linux.

**Comment by bbarry** [comment]
Updating to 1.7.1, seems to be working now (lines are trimmed under this reproduction sequence)
