### ISSUE TITLE
Chord keybindings do not show up in menus

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#14622]
For instance, the keybinding for "Save All" is missing, even though it is assigned
![image](https://cloud.githubusercontent.com/assets/762848/19783910/a3aa1066-9c48-11e6-97d5-2c2912d0aa16.png)

**Comment by bpasero** [comment]
@mousetraps it would really help if you could tell me to which keybinding you assigned it to?

**Comment by mousetraps** [comment]
@bpasero - no customization in this case - pre-assigned to Ctrl+K S

**Comment by bpasero** [comment]
@mousetraps right, unfortunately we are not able to show chords in the electron menu. I suggest you file a feature request @ Electron and ask if we could just show any string label in the menu.

**Comment by bpasero** [comment]
Worth noting that Sublime seems to just show the keybinding as label next to the menu label if chords are being used:

![image](https://cloud.githubusercontent.com/assets/900690/21420170/5283c622-c82c-11e6-86e2-8dea7327ace1.png)

**Comment by bpasero** [comment]
Good summary of what would be needed in Electron to support this natively: https://github.com/electron/electron/issues/5448#issuecomment-217763159

Unlikely to ever happen.

**Comment by bpasero** [comment]
We now show keybindings as part of the label that cannot be shown natively. E.g. on macOS:

![image](https://cloud.githubusercontent.com/assets/900690/22657445/cf09fe80-ec96-11e6-9ec3-c189c011b53c.png)
