### ISSUE TITLE
License Clarifications:  Use of vscode for Training 

### ISSUE THREAD

**Issue by cburchett** [microsoft/vscode#146217]
We would like to package vscode in a hosted environment to be used as a code editor for multiple-day training.  This training and use of the hosted environment (which embeds vscode) would be resold for a particular period of time (not lasting more than 5 days).  

License point 5 from https://code.visualstudio.com/license states:
"You may not.. share, publish, or lend the software, or provide it as a hosted solution for others to use, or transfer the software or this agreement to any third party."

Is using vscode in training as described allowed?

**Comment by chrisdias** [comment]
Hi sorry, no, per the license this is not permitted.
