### ISSUE TITLE
output container only renders two outputs

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#146227]
This looks like a bug in VS Code, I'm seeing a lot of weird behaviors
* Basically sometimes the 2nd progress is not visible (but when i scroll or add a new cell it magically appears)
* The output `Done` is not displayed at the end (but when i scroll or add a new cell it magically appears)

_Originally posted by @DonJayamanne in https://github.com/microsoft/vscode-jupyter/issues/9397#issuecomment-1075728958_

**Comment by rchiodo** [comment]
Verifying the corresponding bug on jupyter and I found there's still a problem.

VS code shows this:
![tqdm](https://user-images.githubusercontent.com/19672699/165836195-e62b9a1a-4420-4faf-bf16-6e3278930964.gif)

Jupyter shows this:

![jupyter](https://user-images.githubusercontent.com/812783/158871157-6680d338-6c09-4b7f-a203-93f927df1636.gif)

**Comment by rebornix** [comment]
See https://github.com/microsoft/vscode-jupyter/issues/9397#issuecomment-1119003596
