### ISSUE TITLE
ctrl+_ isn't functional on mac os x

### ISSUE THREAD

**Issue by clarkeaa** [Microsoft/vscode#1462]
Mapping a function to the keyboard shortcut "ctrl+_" doesn't get called on mac os x with 0.10.3 (783ecf841)

**Comment by bpasero** [comment]
@clarkeaa how is it going in 0.10.5?

**Comment by alexandrudima** [comment]
@clarkeaa Please see https://code.visualstudio.com/docs/customization/keybindings#_accepted-keys and https://code.visualstudio.com/docs/customization/keybindings#_keyboard-layouts

**Comment by clarkeaa** [comment]
OK, thanks.  I think ctrl+_ previously worked since I've checked out code that uses it.  So, for posterity, you have to use "ctrl+shift+-" instead of "ctrl+_".
