### ISSUE TITLE
py file extremely slow

### ISSUE THREAD

**Issue by Onapmek** [microsoft/vscode#146258]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

The problem is, is that the .py file is extremely slow for me. I just print "Hello" and it takes 3 seconds to print. In VScode, with a jupyter notebook, it only takes me 0.5 second. I am not sure why this is happening, I disabled most plugins. Is there a way for me to start "clean"? I uninstalled and installed VScode but it just keeps all the old setting, I think I have messed something up in the settings.
In the terminal also the code "run -n base --no-capture-output --live-stream python" shows before printing, not sure if that has anyone to do with it?

**Comment by rebornix** [comment]
@Onapmek if I understand correctly, you are only seeing this in the integrated terminal, right?

**Comment by Tyriar** [comment]
Can you please provide version/OS information (Help > About) and [show a gif](https://gifcap.dev/) of the issue?

**Comment by Onapmek** [comment]
@Tyriar Hi, yes, 
Here the OS information:

Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Here a gif of the issue:

![Recording 2022-03-29 at 21 41 33](https://user-images.githubusercontent.com/101557992/160694230-0414835b-ab16-4230-9926-8e9a8a701c7e.gif)

**Comment by Tyriar** [comment]
I'm no python expert but my guess is it's taking a while because you'd be starting up a conda session every time with conda.exe but it's shared when using a notebook.
