### ISSUE TITLE
In color theme Solarized dark when running a command on terminal tags are not visible

### ISSUE THREAD

**Issue by piyushm-dt** [microsoft/vscode#146243]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.2
- OS Version: Windows 10 21H2 19044.1586

Steps to Reproduce:

1. Enable Solarized dark color theme and run any command like npm i -D tailwindcss or docker run -p 3000 ..... . Tags like"-D" and "-p" aren't visible.
2.

**Comment by piyushm-dt** [comment]
![Screenshot 2022-03-29 162225](https://user-images.githubusercontent.com/34549904/160596060-4624095d-c0e7-4565-a893-8c6f6a0cdac4.png)
![Screenshot 2022-03-29 162255](https://user-images.githubusercontent.com/34549904/160596067-a91130e4-9b61-47e9-8756-aa1e9e306ce7.png)

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/"needs-more-info"

**Comment by Pyrolistical** [comment]
can confirm fixed on 1.66
