### ISSUE TITLE
remote desktop user can't  edit

### ISSUE THREAD

**Issue by czseng** [microsoft/vscode#146298]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version: windows 10 10.0.19044

Steps to Reproduce:

1. user1 local login system  and open vscode，edit 1.txt 
2. user1 remote login system (rdp), vscode can't continue edit 1.txt .
3. user1 remote login system (rdp), reopen 1.txt using vscode , edit permission normal

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/167556
