### ISSUE TITLE
Local history causing problems for Markdownlint extension

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#146281]
- VS Code Version: 1.66.0
- OS Version: Windows

Steps to Reproduce:

1. Install the Markdownlint extension https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint
2. With Local History enabled, open a Markdown file and begin making changes.
3. Click on a File Saved entry.

The Markdownlint extension starts spewing to the Output panel.

[4:17:22 PM] ERROR: Exception while linting with markdownlint-cli2:
SyntaxError: Unexpected number in JSON at position 1
	at JSON.parse (<anonymous>)
	at c:\Users\gregvanl\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.46.0\bundle.js:37:4010
	at c:\Users\gregvanl\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.46.0\bundle.js:37:4879
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Promise.all (index 0)
	at async c:\Users\gregvanl\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.46.0\bundle.js:37:8417
	at async T (c:\Users\gregvanl\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.46.0\bundle.js:37:8359)
[4:17:22 PM] ERROR: Exception while linting with markdownlint-cli2:
Error: Unable to parse 'c:/Users/gregvanl/vscode-docs/release-notes/.markdownlint.jsonc'; Parser 0: Unexpected number in JSON at position 1; Parser 1: Source contains multiple documents; please use YAML.parseAllDocuments()
	at c:\Users\gregvanl\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.46.0\bundle.js:33:29570
	at c:\Users\gregvanl\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.46.0\bundle.js:1:2260
	at processTicksAndRejections (node:internal/process/task_queues:96:5)

If you try to close the Output panel, it pops back open. Reloading the window stops the output briefly but the Output panel opens again.

If you select a Git History item, Markdownlint stops the output.

**Comment by bpasero** [comment]
Please report to them, my guess is that they cannot properly deal with diff editors: opening a history entry is a diff editor and not a normal editor.

I tried to debug this in their extension but had to give up because I do not understand the code well enough.
