### ISSUE TITLE
Custom IMU example missing files

### ISSUE THREAD

**Issue by bshmid** [microsoft/vscode#146261]
Issue Type: <b>Bug</b>

Open OpenIMU330BI/IMU project
compile/run main.c file get following messages:
Cannot find "c:\Users\USER\Documents\PlatformIO\Projects\220329-180150-IMU\Platform\CAN\include".
Cannot find "c:\Users\USER\Documents\PlatformIO\Projects\220329-180150-IMU\SPIComm".
Cannot find "c:\Users\USER\Documents\PlatformIO\Projects\220329-180150-IMU\Platform\CAN\include".
Cannot find "c:\Users\USER\Documents\PlatformIO\Projects\220329-180150-IMU\include".
Cannot find "c:\Users\USER\Documents\PlatformIO\Projects\220329-180150-IMU\SPIComm".
Cannot find "c:\Users\USER\Documents\PlatformIO\Projects\220329-180150-IMU\Platform\CAN\include".

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.25GB free)|
|Process Argv|--crash-reporter-id 6417802c-f159-4ca8-809f-f987667bb54d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
armview|ben|0.4.6
vscode-pull-request-github|Git|0.38.1
azure-pipelines|ms-|1.202.0
vscode-azureappservice|ms-|0.23.1
vscode-azurefunctions|ms-|1.6.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.13.0
vscode-azurevirtualmachines|ms-|0.5.0
vscode-bicep|ms-|0.4.1318
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.21.0
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.3
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
azure-account|ms-|0.10.1
azurecli|ms-|0.5.0
cpptools|ms-|1.9.7
vscode-node-azure-pack|ms-|0.2.1
azurerm-vscode-tools|msa|0.15.6
aceinna-ide|pla|0.1.2
platformio-ide|pla|2.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvid2:30447481
cppdebug:30451566
vscaat:30438848
pynewfile477cf:30450039

```

</details>

**Comment by Tyriar** [comment]
This doesn't appear to have anything to do with VS Code

**Comment by bshmid** [comment]
Aren't these files which VS Code instalation missed out?

**Comment by bshmid** [comment]
And possibly another one: when I run main.c file in above mentioned project the message I get is: 'C:\Users\USER\Documents\PlatformIO\Projects\220329-180150-IMU\src\main.exe' does not exist
sounds like I'm missing more staff.
Please teach me!

**Comment by bshmid** [comment]
Thank you
How do I report to platformio?
