### ISSUE TITLE
Jupyter Notebook search/replace not being seeded by selection

### ISSUE THREAD

**Issue by 392781** [microsoft/vscode#146361]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: Linux Mint 20.3

Steps to Reproduce:

1. Create a `.ipynb` file.
2. Type some text/code
3. Select a piece of text/code
4. Press Ctrl-F/Ctrl-R to open Search/Replace

The result will be that Search/Replace opens up without any text of the selection added to the "Find" area.

This is not the case for regular `.py` files but is a problem for `.ipynb`

**Comment by babakks** [comment]
@rebornix @rchiodo 
I'd like to take this. I appreciate any hints.

**Comment by 392781** [comment]
@rebornix I just want to clarify: this isn't a feature request. 

This is a bug in the search/replace feature.  It works on one file type but not another.  In fact, the expected behavior of seeding the search _worked_ in a previous release.

**Comment by kailunxu** [comment]
I have tried to fix the bug by introducing the same logic used in the normal editor.

**Comment by rebornix** [comment]
@392781 thanks for the feedback. I don't recall I added this feature to the notebook find widget. It looks similar/identical to the file editor one (UI code shared) but the controllers are not (e.g., how to handle selections).

@kailunxu thanks for your help!
