### ISSUE TITLE
Debugging docs should warn Linux users that they probably need to relax their kernel's `ptrace` security in order to attach to a running process

### ISSUE THREAD

**Issue by mosbasik** [microsoft/vscode#146348]
## Issue

If a Linux user following the Debugging docs tries to attach a debugger to a running process, they are likely to get a somewhat mystifying error like "Timed out waiting for debug server to connect".

## Cause

On some (most? I know Arch and Ubuntu are like this) Linux systems, the kernel is configured by default to forbid non-root processes from using `ptrace` on processes other than their own children.

## Fix

Basically, one needs tell the kernel "It's fine for non-root processes to use `ptrace` to snoop on and/or affect any other process."

That's certainly less secure than the default config, so it's probably best to only change this temporarily and return to the default on a reboot.  This command does that:

```bash
$ echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
```

## Request

I haven't found the above mentioned in the Debugging docs anywhere, and people keep figuring it out independently in various issues and bug trackers.

It would be great for the docs to mention this potential pitfall and maybe some hints about how to fix it (at the very least, something like "search your distribution's docs to find out if it defaults to limiting how `ptrace` can be called).

## Other

I experienced this issue on Arch Linux, and I've seen online discussion of it happening to Ubuntu users.  Not sure how common this setting is for other distros.

I experienced this issue while trying to use VSCode's  Python debugger, but the nature of the issue makes me think it's likely to affect debugging regardless of the language used.

Things I found while searching for an official recommendation for how to proceed:

- https://github.com/microsoft/vscode-python/issues/8384#issuecomment-561398099 vscode-python dev mentions that pycharm recommends this incantation in their docs and notes that vscode will probably have to do the same
- https://github.com/microsoft/vscode-python/issues/15427#issue-810279258 otherwise-unrelated issue that happens to shows a docker-compose config with a little block that says "if you're planning to use a ptrace-based debugger, turn off the default seccomp profile" (I bet that default profile also forbids ptracing random processes)
- https://github.com/microsoft/debugpy/issues/102#issuecomment-604724933 someone ran into this issue while setting up their WSL environment
- https://github.com/microsoft/debugpy/issues/102#issuecomment-940834793 and then later someone else mentioned it would be nice if the docs described this fix
- StackOverflow question: [Keep getting ptrace: Operation not permitted when trying to attach to process in a docker container](https://stackoverflow.com/questions/66879826/keep-getting-ptrace-operation-not-permitted-when-trying-to-attach-to-process-in)
- A comment on the above question linked this issue: https://github.com/microsoft/debugpy/issues/80
- The opener of that issue found this AskUbuntu answer describing Ubuntu's default config and how to work around it: [after upgrade gdb won't attach to process](https://askubuntu.com/questions/41629/after-upgrade-gdb-wont-attach-to-process)
- And then opened this request for a docs enhancement (still open at time of writing): https://github.com/microsoft/debugpy/issues/82
- https://github.com/microsoft/vscode/issues/92486 probably this issue; opener described this fix; incorrectly closed as caused by an extension

**Comment by mosbasik** [comment]
It's worth mentioning that even after making the described change, I haven't yet successfully attached the Python debugger to a running process on Linux.  That's a different issue; I opened https://github.com/microsoft/vscode-python/issues/18817 for that.

I'm assuming that the goal is possible on Linux.  Maybe it's not, and the reason the docs don't describe this Linux-specific thing is because attaching to a running process isn't supported yet on Linux.  I sure hope that's not the case!

**Comment by weinand** [comment]
VS Code only ships with the JS debugger which does not use ptrace.
So it would be confusing if we would warn linux users about ptrace permissions.

Please file this issue against the debug extensions that have the ptrace issue.

**Comment by mosbasik** [comment]
Thanks for the quick response; I've re-filed this issue against the Python extension repo.
