### ISSUE TITLE
When I change the HTML files in the vscode, preview will not change

### ISSUE THREAD

**Issue by csyj501** [Microsoft/vscode#14633]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: ms-vscode.cpptools-0.9.2

Steps to Reproduce:

When I change the HTML files in the vscode, preview will not change

**Comment by weinand** [comment]
@csyj501 please translate the title and the issue description to English.

**Comment by shibang** [comment]
兄弟，提Issue好歹把它翻译成英文啊

**Comment by csyj501** [comment]
I want to say that when I change the HTML files in the vscode, preview will not change!

**Comment by weinand** [comment]
@csyj501 VS Code doesn't provide html preview out of the box. Please file this issue against the extension you are using.

**Comment by csyj501** [comment]
thinks
