### ISSUE TITLE
Jupyter Notebook progress bar is broken

### ISSUE THREAD

**Issue by juanitorduz** [microsoft/vscode#146397]
Hi 👋 ! I am running into an issue issue when using vscode 1.66 : when running pymc models there is a progress bar output which was working fine before the update and now the progress bar simply prints down :( See pic below

![image](https://user-images.githubusercontent.com/22996444/161008856-42534bd3-241c-4308-a432-a5feb21118d4.png)

This is how it prints in Jupyter notebooks (anaconda) and it was looking so in vscode 1.65.2

![image](https://user-images.githubusercontent.com/22996444/161012084-cddc510e-2a81-43e9-afd1-7c2c9f31a949.png)

Here is the info about my session

```
Version: 1.66.0 (Universal)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:04.419Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 21.4.0
```

**Comment by juanitorduz** [comment]
Here is a reproducible example:

![image](https://user-images.githubusercontent.com/22996444/161125323-46e06da8-922c-4811-bbc7-fb3ff31c5c5e.png)

```python
import numpy as np
import pymc3 as pm

x = np.random.normal(loc=0, scale=1, size=100)

with pm.Model() as model:

    mu = pm.Normal("mu", mu=0, sd=1)
    sigma = pm.HalfNormal("sigma", sigma=3)
    likelihood = pm.Normal("likelihood", mu=mu, sigma=sigma, observed=x)

    trace = pm.sample(1000)
```

**Comment by juanitorduz** [comment]
Thank you for working so fast on this one! Looking forward for the next update/release 🚀 !

**Comment by joaomoreno** [comment]
@rebornix I couldn't verify this fix:

![image](https://user-images.githubusercontent.com/22350/161500972-92b8131f-a740-4a25-aa44-0ba775e4291d.png)

**Comment by rchiodo** [comment]
Works for me too. 

![image](https://user-images.githubusercontent.com/19672699/161861441-a7b8afb0-59d3-4cdf-8f01-763ff532d89a.png)
