### ISSUE TITLE
Allow to cancel test unit run

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#146302]
From the notification allow to cancel:

![image](https://user-images.githubusercontent.com/900690/160768788-a6d0bfd0-b6e3-4b7e-a0c4-26af3c16edf7.png)

Can just terminate the test run process.

**Comment by lonix1** [comment]
Only for typescript or other languages too?

(This would be helpful .net tests which run forever without stopping - and the only way to kill them is to restart vscode.)

**Comment by connor4312** [comment]
We don't have this as a notification any longer
