### ISSUE TITLE
Deleted line source control decorators is hard to click

### ISSUE THREAD

**Issue by mrleblanc101** [microsoft/vscode#146360]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66
- OS Version: macOS 12.3

Steps to Reproduce:

1. Open a project with a Git repo
2. Delete lines of code
3. Try to click the "Red arrow" source control decorator. The hit box is not aligned with the icon, sometime it's very hard to press.
![2022-03-30 16 51 09](https://user-images.githubusercontent.com/17392251/160928900-7df9fe5a-7d11-49d9-8553-c8836f1b6624.gif)

**Comment by Dromantor** [comment]
Seems the hit box is placed on the line above while the arrow is between the lines. Interresting.

**Comment by joaomoreno** [comment]
Broken by https://github.com/microsoft/vscode/issues/95599

**Comment by joaomoreno** [comment]
@lszomoru I can take this since I broke it.

**Comment by mrleblanc101** [comment]
It would be nice to improve the touch target at the same time. Even before it was broken, the touch target was very small and hard to click.
Thanks ☺️
