### ISSUE TITLE
config maximum amount of lines not work

### ISSUE THREAD

**Issue by iiimapidan** [microsoft/vscode#146393]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.0
- OS Version: win11

I need print full logs, but scrollback can't work.

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/100209029/161000367-47d7da86-2479-4e24-94e7-0e64135b6535.png)

**Comment by Tyriar** [comment]
Ideally you should redirect the output of your command to a file or something if you need to do this. Just use a more reasonable number here, the scrollback defines how much memory the terminal uses, so I'm not surprised this doesn't work.
