### ISSUE TITLE
debug console filter not work

### ISSUE THREAD

**Issue by iiimapidan** [microsoft/vscode#146384]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.0
- OS Version: win11

Steps to Reproduce:

1.print a large amount of logs, filter  a key wrod, console can't show log contain key word.

**Comment by myron123456** [comment]
I have the same problem. If the debug console log uses color decoration, the filter will have problems

**Comment by myron123456** [comment]
@weinand 
I have the same problem. If the debug console log uses color decoration, the filter will have problems

**Comment by myron123456** [comment]
> @weinand 我也有同样的问题。如果使用任何问题，过滤器出现问题
@roblourens I am a vscode extension developer and I use the vscode.debug.activeDebugConsole.append() interface to output my logs to the debug console. The parameters are '\u001b[' + 32 + 'm' + 'hello stack' + '\u001b[0m', with this I can add a lot of color to the debug console log. But in the filter I can't find the correct log exactly, thank you

**Comment by roblourens** [comment]
This is working for me. Can you share a screenshot?

**Comment by myron123456** [comment]
> 这对我有用。可以分享截图吗？
This is my debug console log:
![image](https://user-images.githubusercontent.com/41883925/167233558-2c9d1145-a314-4b8e-9412-f26700a1f9f3.png)
When I tried to search for core in the debug filter, I got the wrong filter result
![image](https://user-images.githubusercontent.com/41883925/167234310-b9802f00-09cf-4aa4-892c-2bd72d17e14e.png)
When I try to search the debugging filter for the millisecond timestamp 4629, I can't filter it
![image](https://user-images.githubusercontent.com/41883925/167234268-01e3a768-f1d0-4bd8-9c7f-cadfc4e1ae37.png)

**Comment by roblourens** [comment]
Thanks, that's obviously not right. I tried some more scenarios and still can't repro an issue. Is this a program that you can share with me, or can you try reducing it?

**Comment by myron123456** [comment]
@roblourens   Hello, I'm sorry to see your reply just now. I have made a lot of comparative analysis and found that the reason for the problem is the append interface I use, which is the real parameter "\u001b[1;31m"+'2022-05-11 16:06:24.2349 [I]-[Hello world!]\r\n'+"\u001b[0m", I moved to the end, and the filter returned to normal. Now my parameters are "\u001b[1;31m"+'2022-05-11 16:06:24.2349 [I]-[Hello world!]'+"\u001b[0m\r\n". 
        Although I avoided the problem, it should be a bug. I guess it may be that "\u001b[0m" caused some exceptions in the filter.thanks
       in addition,I changed vscode mock debug and reproduced the problem.I modified lines 527-538 of "src/ mockdebug.ts". You can run vscode mock debug and reproduce the issue in the debug log generated by stepin.
       This is my test modification point
![image](https://user-images.githubusercontent.com/41883925/168015137-d531d4e2-b887-40b3-8e17-58f5bdc366b4.png)
        This is my test program
[vscode-mock-debug.zip](https://github.com/microsoft/vscode/files/8675772/vscode-mock-debug.zip)

**Comment by roblourens** [comment]
I see - since you're using append with newlines, you are actually creating a single multiline row in the debug console. We are only filtering based on these rows, so if some line in the row matches, you will see all the text in the row.

I'd recommend using appendLine for something like this.
