### ISSUE TITLE
Pretty style for .csv file

### ISSUE THREAD

**Issue by nityanand86876** [microsoft/vscode#146311]
vscode simply shows .csv file in text format like his as shown below:
![image](https://user-images.githubusercontent.com/85880458/160804457-6cc12466-30ae-4460-b95a-ebaa26e5093d.png)
but i like to see it like this as github shows any .csv file like this given below :
![image](https://user-images.githubusercontent.com/85880458/160804776-74d17879-ecb7-4ec1-9d40-212895796397.png)
so please do something and bring this feature in vscode as soon as possible.
This will help many peoples.
Thanks and reguards,
@nityanand86876

**Comment by michaeljones** [comment]
I randomly saw this. There are some extensions that are aimed at this: 

- https://marketplace.visualstudio.com/items?itemName=janisdd.vscode-edit-csv
- https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer
- https://marketplace.visualstudio.com/items?itemName=mechatroner.rainbow-csv

They might help?
