### ISSUE TITLE
Go language syntax for function with generic not properly highlighted

### ISSUE THREAD

**Issue by uudashr** [microsoft/vscode#146313]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.2
- OS Version: Darwin arm64 20.6.0

Steps to Reproduce:

1. Create new file `math.go`
```
package generics

type Number interface {
	int64 | float64
}

func SumInts(m map[string]int64) int64 {
	var s int64
	for _, v := range m {
		s += v
	}
	return s
}

func SumFloats(m map[string]float64) float64 {
	var s float64
	for _, v := range m {
		s += v
	}
	return s
}

func SumIntsOrFloats[K comparable, V int64 | float64](m map[K]V) V {
	var s V
	for _, v := range m {
		s += v
	}
	return s
}

func SumNumbers[K comparable, V Number](m map[K]V) V {
	var s V
	for _, v := range m {
		s += v
	}
	return s
}

```

The generic function is inside the red rectangle. We can see the expected should be like on the green rectangle.  
<img width="581" alt="Screen Shot 2022-03-30 at 16 57 52" src="https://user-images.githubusercontent.com/166053/160808104-404d8d95-b440-4e2e-ae60-1453adf66edc.png">

**Comment by alexr00** [comment]
Moved to the upstream repository that we pull our go syntax highlighting grammar from: https://github.com/jeff-hykin/better-go-syntax/issues/30
