### ISSUE TITLE
Allow users to undo keybindings they set in the `Keyboard Shortcuts` tab with `Ctrl` + `Z`.

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode#146373]
Allow users to undo keybindings they set in the `Keyboard Shortcuts` tab with `Ctrl` + `Z`.

**Comment by sandy081** [comment]
Do you mean following?

- Open Keyboard Shortcuts Editor
- Set a keybinding
- Press ctrl+z
- Remove the assigned keybinding?
