### ISSUE TITLE
Double clicking markdown file reveals markdown document but doesn't scroll it

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#146333]
1. Open a markdown preview
2. Close the associated markdown document
3.  Scroll the markdown document
4. Double click a line of text in the markdown document
5. 🐛 The markdown document appears but does not scroll to the text double clicked in the file.
![Recording 2022-03-30 at 13 55 11](https://user-images.githubusercontent.com/4544166/160900184-be63df87-c6e7-44b4-8c05-c61e92fa4dfb.gif)

**Comment by mjbvz** [comment]
@lramos15 Please give this a try in the next insiders build and let me know if there are any cases where it still doesn't work

**Comment by lramos15** [comment]
Works for me 👍 . Not sure if i'm allowed to mark as verified this early on, so I will test again for the endgame cycle.
