### ISSUE TITLE
Option to reorder repositories in Source Control Repositories view

### ISSUE THREAD

**Issue by ruxpendp** [microsoft/vscode#146359]
With the 1.66.0 release, the SCR view was changed to always sort repositories by name. Previously they would appear in the order they were discovered by vscode.

The old behavior was billed as a feature (e.g. [comment](https://github.com/microsoft/vscode/issues/43527#issuecomment-365218955)), and I preferred that behavior because my multi-folder workspaces usually contain a primary git repo (that I put at the top) and a few ancillary ones.

So the minimum viable feature request would be to:
* have a vscode setting that allows switching between the new and old behaviors

But the "best QoL" feature request would be to:
* have repos initially sorted by name
* be able to drag to reorder repos in the SCR view (and the multi-folder workspace would remember the order)

**Comment by lszomoru** [comment]
Today's Insiders release (2022-04-14), contains two changes related to repository sorting:
- The default sorting was reverted to be by discovery time, which was the original behaviour
- A new setting `scm.repositories.sortOrder` was added that can be used to control the repository sorting (discovery time, name, path)
