### ISSUE TITLE
Extension activation fails as `env` is null when restoring VSCode

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14632]
- VSCode Version: Insider
- OS Version: OS X 10.11.6

Today I noticed language extensions like https://github.com/Dart-Code/Dart-Code and https://github.com/DonJayamanne/pythonVSCode failed to activate.

Both fails as `env` is null when being activated. Dart for example:

![image](https://cloud.githubusercontent.com/assets/4033249/19790262/c1ff38e8-9c6b-11e6-8d83-655f1923cb8a.png)

The line in trouble:
(Put a log, will use it soon in gif)

![image](https://cloud.githubusercontent.com/assets/4033249/19790287/fe0acd52-9c6b-11e6-9656-2c3daf1a7725.png)

This is in the beginning of that file:

![image](https://cloud.githubusercontent.com/assets/4033249/19790433/fab2b5c4-9c6c-11e6-8ec6-536b401cb010.png)

Now, if I go to a Dart project and open a dart file, the Dart extension will activate correctly. However, if I leave an open tab, and restart VSCode, so it restores the tab, Dart extension fails to activate, as `env` is null.

![bug](https://cloud.githubusercontent.com/assets/4033249/19790420/d067e816-9c6c-11e6-9fbe-102e5a4849ae.gif)

Also happened to @roblourens 

I'll be available tonight. Let me know how can I help if you can't repro.

**Comment by kieferrm** [comment]
This seems related to https://github.com/Microsoft/vscode/commit/2f8c5c118991ddf1b33a797da02922553e7b9f28.

**Comment by octref** [comment]
Downloaded older Insider builds:

- Does not repro with 889c720db5e83f4649ba1317fc8fdd3387cbf975, so not 2f8c5c1
- Repro with 9d472850269c3f7ff1043b86f823115927af1982

It's somewhere in here I believe: @alexandrudima 

![image](https://cloud.githubusercontent.com/assets/4033249/19796854/0f33c0c2-9c9c-11e6-983e-21bd2c90fd2a.png)

**Comment by jrieken** [comment]
I'd say this is caused by [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHost.api.impl.ts#L95) line of code. We have since a long time but my assumption is that recent changes in the extension startup sequence is now triggering this...

**Comment by jrieken** [comment]
To *verify*:  Write an extension that activates on start up (`*` activation event) with the code below. Start, restart a few times and make sure never prints errors on the console, but the `env` object

```
import * as vscode from 'vscode';
console.log(vscode.env);
```

**Comment by bpasero** [comment]
@jrieken I am seeing a new error popping up when doing so:

![image](https://cloud.githubusercontent.com/assets/900690/19803521/7394bb8a-9d09-11e6-991e-b21caf8d5709.png)

Related to: https://github.com/Microsoft/vscode/commit/31d39b0a371fef6134d5799367e7ddf7d128438c

**Comment by bpasero** [comment]
@jrieken works fine when calling from within the `activate` method, just not when called outside. But maybe that never worked...?

**Comment by jrieken** [comment]
@bpasero You are not on latest! There the variable is called `initTelemetryInfo`. Please verify this with a later build.

<img width="600" alt="screen shot 2016-10-28 at 12 31 16" src="https://cloud.githubusercontent.com/assets/1794099/19803717/89917742-9d0a-11e6-9f78-91a5343a88f4.png">

**Comment by bpasero** [comment]
@jrieken ah ok sorry.

**Comment by bpasero** [comment]
Verified on Mac this works 👍
