### ISSUE TITLE
dark mode for vscode site

### ISSUE THREAD

**Issue by NewUserHa** [microsoft/vscode#146367]
dark mode for https://code.visualstudio.com/updates

To catch up with new functions of vscode, users can read it in vscode with dark background/mode, but it can't be navigated to update history for older versions.

**Comment by gregvanl** [comment]
@NewUserHa Thank you for the suggestion. We already have an issue for this in our website infrastructure repository, which is unfortunately private. I'll add a comment and upvote that issue.

**Comment by NewUserHa** [comment]
great thanks!
