### ISSUE TITLE
Panel toggle button icons blurry on non-retina display

### ISSUE THREAD

**Issue by alexwhitman** [microsoft/vscode#146395]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.6.6.
- OS Version: MacOS Monterey 12.3

Steps to Reproduce:

The new panel show/hide icons at the top right of the window seem blurry on a non-retina display. I have a 1920x1200 resolution monitor attached to a MacBook Pro. The icons look fine on the internal monitor, but blurry on the external monitor. Screenshot below (how well this will show the issue on other people's screens I don't know):

![Screenshot 2022-03-31 at 08 56 05](https://user-images.githubusercontent.com/422013/161006821-df80627a-dc18-4082-bfbd-d31cfe8c56f8.png)

Other icons, such as those in the sidebar are sharp.

**Comment by deepak1556** [comment]
Very likely an edge case in the toggle icons implementation and not related to the runtime versions since the issue does not affect the titlebar text, but will have to repro and confirm to be sure. I also don't have the required setup to test this now.

**Comment by sbatten** [comment]
does this still reproduce?

**Comment by alexwhitman** [comment]
@sbatten Unfortunately I no longer have a Mac to be able to check, having changed jobs. The icons look fine on the same monitor when running 1.74.0 on Windows 11.
