### ISSUE TITLE
Allow hiding tooltips on custom tree view items

### ISSUE THREAD

**Issue by michaeljones** [microsoft/vscode#146310]
I work on an extension that has a custom tree view. Some of the items don't have meaningful extra information to show in a tooltip but setting the `tooltip` field in the `TreeItem` to `undefined` or `""` results in the label being used for the tooltip which looks odd as it provides no additional information.

We would like it if there was some way to disable tooltips for a tree item. 

It might be hard to used `undefined` for that now as that would be a breaking change but perhaps there is some other approach that would be possible. 

I would note that if the tooltip is required for accessibility in some way then I'm happy that it stays but I think that angle is covered by the aria-label attribute and the tooltip is something else entirely.

I have searched and I can't see reference to this from an extension API point of view in the current issues.

I am not well versed in the VS Code code base but I believe the issue comes from these lines: 

https://github.com/microsoft/vscode/blob/a3e739fee9a63c932bf2d9578547f52bc6a59a62/src/vs/workbench/browser/parts/views/treeView.ts#L939-L940

**Comment by michaeljones** [comment]
Here is an example screenshot of the issue:

![image](https://user-images.githubusercontent.com/5390/160816677-30a52250-3f94-48ee-bd41-a932098f2c63.png)

The supported features are programmatically detected and we don't have a reliable way of providing any additional useful information for the tooltip so being able to avoid it entirely would be desirable.

**Comment by alexr00** [comment]
To verify, modify an extension that provides a tree view so that the `tooltip` of it's tree items is an empty string. Verify that no hover is shown on those tree items. 

You can use the sample for this:
https://github.com/Microsoft/vscode-extension-samples/blob/4a0b22cf62265482f892eee9142c37b64eee209a/tree-view-sample/src/testView.ts#L76-L81
