### ISSUE TITLE
Exclude search results that are within the prompt

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#146394]
Now that we have shell integration, we should be able to provide `beginSearchAfterTerm:string` to `ISearchOptions` in xterm.js so that results don't include matches that are within the prompt.

For example, if prompt is `prompt`, findPrevious would only start searches at col 5 if the translateLineToString at the row being searched starts with `prompt`.

**Comment by Tyriar** [comment]
I don't think this is really needed? For any search of substance the prompt probably wouldn't be included and the user may also want to search the prompt (for the cwd for example).
