### ISSUE TITLE
Can no longer break in debugger on Mac (breakpoints or "debugger" statement in JS)

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#146366]
Issue Type: <b>Bug</b>

This only started happening recently, and happens in both stable and insiders.  Happens with my regular extension project and simple samples

1)  git clone https://github.com/microsoft/vscode-extension-samples.git
2) cd vscode-extension-samples
3) npm i
4) open vscode
5) set breakpoints anywhere inside src/extension.ts
6) add some "debugger;" statements inside extension.ts
7) F5
8) F1 -> "Hello World"
!) EXPECTED: breakpoint or debugger statement should get hit in the debugger
ACTUAL: code runs but no breakpoints are hit

VS Code version: Code 1.66.0 (Universal) (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 6|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|--crash-reporter-id b64e85d2-fb27-46b5-b6ca-96a47f461f90|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
yaml-preview|dai|0.0.1
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.5
vscode-bicep|ms-|0.4.1318
vscode-dotnet-runtime|ms-|1.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
pynewfile477:30463512

```

</details>

**Comment by weinand** [comment]
@StephenWeatherford the `vscode-extension-samples` project contains many sample extension and F5 only makes sense if you open a specific extension in VS Code.
What extension did you try?

**Comment by StephenWeatherford** [comment]
I'm working on https://github.com/Azure/bicep but it also repros for me in helloworld-sample.  You're on Mac, right?  Not a problem for me on Windows.

**Comment by weinand** [comment]
Yes, I'm on Mac (Intel).
Could you try it again after a reboot?
Make sure to run `npm i` in the `helloworld-sample` directory.

**Comment by StephenWeatherford** [comment]
Weird, rebooting seems to have fixed it (yes, I ran npm i - the command ran but just wouldn't set breakpoints).

Settings breakpoints on Mac has always been a bit unreliable for me, but adding a "debugger;" statement has generally started breakpoints working again in the past.  Don't know how to repro that issue, though.

Thanks!

**Comment by weinand** [comment]
@StephenWeatherford setting breakpoints should not be unreliable (on any platform).

Whenever it looks "unreliable", it is most likely a source map issue: source maps are out of date or the "outFiles" property is not specified correctly.

**Comment by StephenWeatherford** [comment]
Should it even be possible to get into an out of date state?  It does seem like cleaning the tree has fixed this before (but not this time).

**Comment by weinand** [comment]
source maps are created by the compiler/transpiler you are using (which is out of VS Code's control).
So you are responsible for setting up your build pipeline correctly.

**Comment by StephenWeatherford** [comment]
Okay, thanks again.

**Comment by StephenWeatherford** [comment]
Okay, it's happening again, and this time restarting the Mac and cleaning/rebuilding haven't made any difference.  Both my development extension and hello world sample.  Both insiders and stable.  Any ideas?

**Comment by StephenWeatherford** [comment]
Never mind, figured it out.

**Comment by weinand** [comment]
@StephenWeatherford what was the problem?

**Comment by StephenWeatherford** [comment]
At least for the last case, pilot error.
