### ISSUE TITLE
Rename failed

### ISSUE THREAD

**Issue by chenjiayu119** [microsoft/vscode#146382]
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。
Rename failed,The prompt is 'Error:EPERM:operation not permitted,rename'.
Using administrator run permissions still failed and Fails regardless of whether a project is running.

Issue Type: <b>Bug</b>

Rename failed,The prompt is 'Error:EPERM:operation not permitted,rename'.
Using administrator run permissions still failed and Fails regardless of whether a project is running.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.82GB free)|
|Process Argv|--crash-reporter-id ca469273-1d6e-4a93-ac97-9aba3ceb9c60|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.2
jquerysnippets|don|0.0.1
gitlens|eam|12.0.5
vscode-html-css|ecm|1.11.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.11.7
vscode-yarn|gam|2.1.0
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
path-alias|IWA|0.12.3
vue|jcb|0.1.5
vue-alias-skip|lih|0.0.25
jsdoc|lll|1.0.3
template-string-converter|meg|0.6.0
git-graph|mhu|1.30.0
vscode-language-pack-zh-hans|MS-|1.65.3
debugger-for-chrome|msj|4.13.0
vetur|oct|0.35.0
indent-rainbow|ode|8.2.2
docthis|oou|0.8.2
vuehelper|oys|0.1.0
vue-beautify|pea|2.0.4
LiveServer|rit|5.7.5
vs-code-prettier-eslint|rve|3.1.0
vscode-gitter|scr|1.0.3
prettier-vscode|Sim|2.0.7
code-spell-checker|str|2.1.11
tabnine-vscode|Tab|3.5.38
open-in-browser|tec|2.0.0
vscode-icons|vsc|11.10.0
JavaScriptSnippets|xab|1.8.0
super-comprehensive|xue|1.9.9
local-history|xyz|1.8.1
vue-component|zhu|1.1.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvid1:30447480
pynewfile477:30463512

```

</details>

**Comment by mjbvz** [comment]
Please provide steps to reproduce the issue
