### ISSUE TITLE
Update `path.ts` to be in sync with node.js `16.14.2`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#146317]
We will ship Electron `17` with node.js `16.13.0` to stable soon so we should also look into bringing our copy of `path` library to the same version.

Checking for the diff, it seems to be a few commits after https://github.com/nodejs/node/commit/ed45b5164217fb9b0241ec8e9a4e90b0377ca44c and up until https://github.com/nodejs/node/commits/v16.13.0/lib/path.js

//cc @deepak1556

**Comment by bpasero** [comment]
Hm, the first change is already pretty bad for us: 

https://github.com/nodejs/node/blob/187a862d221dec42fa9a5c4214e7034d9092792f/lib/path.js

Because it seems to depend on a new `primordials` thing which is maybe defined globally and probably optimized / cached /snapshotted. 

Maybe we should rather look out for actual bug fixes and focus on those...

Changes:
* [path: refactor to use more primordials](https://github.com/nodejs/node/commit/187a862d221dec42fa9a5c4214e7034d9092792f)
* [lib: refactor to use validateObject](https://github.com/nodejs/node/commit/029d1fd797975ef89b867f9d606257f0f070a462#diff-092f2be30e312ebf7517f3d5f08b4c8d38a4bea3449ab15eb87f408a8f301dff)
* [path: refactor to use more primordials](https://github.com/nodejs/node/commit/3ef95627cc911da8198f093960f4490facdfb8e2)
* [path: fix posix.relative() on Windows](https://github.com/nodejs/node/commit/b0d5e036d8677633d82032deac055ad716a55531)
* [path: fix POSIX path.resolve() perf regression](https://github.com/nodejs/node/commit/e38d62a8c9e3494a464c0de6218178329f245440)
* [typings: add types for internalBindings('fs')](https://github.com/nodejs/node/commit/cb2bdc632a802eed7ee8c5c9388811de73029602#diff-092f2be30e312ebf7517f3d5f08b4c8d38a4bea3449ab15eb87f408a8f301dff)
* [typings: add JSDoc types to lib/path](https://github.com/nodejs/node/commit/f1a21e5c914f9bcbbb2a77b436eae2bc4f4c2a86)
* [path: inline conditions](https://github.com/nodejs/node/commit/be4b3a4164d95045ae30a8b4bb3d0b6330680b85)

I think only the 2 fix commits stand out from the others 🤔

**Comment by bpasero** [comment]
@sbatten I assume you skipped over https://github.com/nodejs/node/commit/187a862d221dec42fa9a5c4214e7034d9092792f right?

**Comment by bpasero** [comment]
Reopening given unit test failures, I had to revert the change for now.

**Comment by sbatten** [comment]
@bpasero yes I skipped the primordials. I didn't dig into why they do this, but it seemed easy enough to just call the string functions instead.

As for the test failures, new PR https://github.com/microsoft/vscode/pull/169028

**Comment by deepak1556** [comment]
Primordials are only meant for Nodejs internal code usage, external users should just replace them with corresponding JavaScript builtins. You can read more about why Nodejs does it [here](https://github.com/nodejs/node/blob/main/doc/contributing/primordials.md)
