### ISSUE TITLE
Windows 10: VS Code doesn't open

### ISSUE THREAD

**Issue by dend** [Microsoft/vscode#14631]
- VSCode Version: 1.6.1
- OS Version: Windows 10 AU
# Steps to Reproduce:
1. Try to launch VS Code
# Results:

VSCode never launches. Even though it shows up in the taskbar.

<img width="505" alt="code" src="https://cloud.githubusercontent.com/assets/1389609/19789657/664c468a-9c66-11e6-9d1e-05e8a13ef543.PNG">

If I hover over the icon, I can see a window preview:

<img width="426" alt="code2" src="https://cloud.githubusercontent.com/assets/1389609/19789670/8b0a00d4-9c66-11e6-9912-a4fea12104d6.png">

Clicking on the preview does nothing.

This is a Surface Pro 3 device with 2 external monitors - I tried detaching those and only leave the Surface as the display, but no luck - the window seems to be there, yet never shows up.

**Comment by jeffwilcox** [comment]
I've been having similar issues this week, I figured it was something with my flight of Windows just causing regressions though.

**Comment by bpasero** [comment]
@dend @jeffwilcox are you guys on the fast track for Windows update or on a stable version?

**Comment by jeffwilcox** [comment]
Fast track for me, so totally get that this may correct itself!

**Comment by dend** [comment]
Fast-track for me too.

**Comment by bpasero** [comment]
Ok I assume this is Win10 issue then as we did not hear this from other people on Win10.
