### ISSUE TITLE
Collapse/Expand All items in Outline (Sidebar panel)

### ISSUE THREAD

**Issue by suspectinside** [microsoft/vscode#146375]
Add quick way to **Collapse/Expand** All items (at one level or just everywhere) in **Outline** (Sidebar panel)

To quickly figure out complete relations in some unknown library, be able to navigate fast etc it's would be realy helpfull if **Outline** Pane will have controls to collapse/expand, remember the opened|closed states for all items, plus will provide some additional features to analyze the sources.

that's the process just to introspect in a "quick way" which methods being defined and which classes in the source file, for **vscode**:

https://user-images.githubusercontent.com/101431780/160950386-fb776ee0-1cc6-4b53-9d05-94c3500fc74d.mp4

and the same for pycharm (i want just to **Outline** and **Overview** what we have in there):

https://user-images.githubusercontent.com/101431780/160950449-8f259c8f-d9cd-4c4b-be59-d52f91c89a83.mp4

the latest one is much much simpler, faster and just for __humans__

So, i really interesting if there is a way to Expand/Collapse all the items for **Outline** panel in vscode in a quick way.

**Comment by jrieken** [comment]
> Add quick way to Collapse/Expand All items (at one level or just everywhere) in Outline (Sidebar panel)

Hold the `alt`-key while pressing the expand/collapse arrow and it does that. Is that enough?

**Comment by suspectinside** [comment]
> Hold the `alt`-key while pressing the expand/collapse arrow and it does that. Is that enough?

do you mean that it will expand/collapse only children nodes of being pressed parent node or all the classes presented in **Overview** ?

i think that the best and the easiest way to do it for vscode's users - as shown on the second video between 0:10 and 0:18 seconds. we may use this feature very often especially when exploring some new library to build some "mental model" about available classes and methods in that classes.

but in practice it should be enough just to Collapse/Expand **root** nodes on **Outline** panel with one action (binded Hot Key to toggle state), smth like this:

**Collapsed State**:
![collapsed](https://i.imgur.com/DKUwcjH.png)

**Expanded State**:
![expanded](https://i.imgur.com/PnaivSy.png)

there are two toggle buttons (expand/collapse) which being pressed change the expanding state, but it should be totally ok if we will be able just to bind **Hot Keys** to "Expand all root nodes"/"Collapse all root nodes" (possible with some special visualization for inherited members)

**Comment by jrieken** [comment]
> do you mean that it will expand/collapse only children nodes of being pressed parent node or all the classes presented in Overview ?

It applies to all children of the node pressed
