### ISSUE TITLE
Merge conflict (via cherry-pick) does not show inline action bar for accepting changes

### ISSUE THREAD

**Issue by MircoBabin** [microsoft/vscode#146300]
Does this issue occur when all extensions are disabled?: Yes, I checked with "code --disable-extensions" and it shows the same behavior as the screenshot.

- VS Code Version: 1.65.2 (system setup)
- OS Version: Windows/10

Extension | Author (truncated) | Version
-- | -- | --
openmatchingfiles | bca | 0.5.2
githistory | don | 0.6.19
prettier-vscode | esb | 9.5.0
remotehub | Git | 0.26.0
php-cs-fixer | jun | 0.2.10
php-docblocker | nei | 2.7.0

Steps to Reproduce:

1. Create a merge conflict by using the commandline "git cherry-pick".
2. Open Visual Studio
3. Show merge conflict file.
4. Navigate to the line containing "<<<<<<"
5. There is no inline action bar "Accept current change | Accept incoming change ...", as described in https://code.visualstudio.com/docs/editor/versioncontrol#_merge-conflicts

![image](https://user-images.githubusercontent.com/8981285/160764192-af7e31e0-2069-4b34-a646-0d00730f2e87.png)

**Comment by chrmarti** [comment]
Make sure you have code lenses for editors and merge conflicts enabled:
<img width="420" alt="image" src="https://user-images.githubusercontent.com/9205389/162455249-b4eef854-f4c3-4a7f-b2c7-8b0d12568190.png">
<img width="331" alt="image" src="https://user-images.githubusercontent.com/9205389/162455297-bfa9f8c5-0d99-4399-8260-29c4e399bc53.png">

**Comment by chrmarti** [comment]
I see your point, I think the global setting for all code lenses was introduce long before we added support for merge conflicts.

Maybe check if you can turn off the code lenses that generate to much noise specifically without using the global setting for all code lenses.

**Comment by MircoBabin** [comment]
I will enable the global code lens. And see how it goes with the "noise".
