### ISSUE TITLE
March 2022 - Recovery 1

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#146388]
- [x] Create a milestone `<Month> <Year> Recovery` **endgame champion**
- [x] Bump the version number **endgame champion**
- [ ] [🔖candidate issues](https://github.com/issues?utf8=✓&q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22March+2022+Recovery%22)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `main`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **endgame champion**
- [x] Issues are verified on `stable` build and the `verified` label is added **endgame champion**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **endgame champion**
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [x] Sanity check of installable bits ([server instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers))
  - [x] Windows 32 bit @dbaeumer 
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
    - [x] server 32-bit
  - [x] Windows 64 bit @dbaeumer
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
    - [x] server 64-bit
  - [x] Windows ARM64 @bpasero 
    - [x] signed installer ARM64
    - [x] signed user installer ARM64
    - [x] zip ARM64
  - [x] macOS
    - [x] Universal 
    - [x] Intel
    - [x] Intel server
    - [x] Apple Silicon
  - [x] Linux x64
    - [x] deb 
    - [x] rpm @rzhao271 
    - [x] archives @rzhao271 
    - [x] snap (`sudo snap install --classic --dangerous <file>.snap`) 
  - [x] Linux server
    - [x] x64
    - [x] x64 Alpine
    - [x] ARM32
    - [x] ARM64
- [x] Publish website **@gregvanl**
- [x] Publish stable build **endgame champion**
- [x] Create an official release **endgame champion**
  - [x] Create a tag (make sure you pull the release branch first): `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)
- [x] Close the milestone on [GitHub](https://github.com/microsoft/vscode/milestones) **endgame champion**

**Comment by TylerLeonhardt** [comment]
1.66.1 is released! 🎉

**Comment by an-boxbrite** [comment]
FYI the link on the [VS Code updates page](https://code.visualstudio.com/updates/v1_66#_notable-fixes) is broken:
![image](https://user-images.githubusercontent.com/87533853/162266181-28fffc5d-0e97-4368-bd9b-4725242cc510.png)

Should be: https://github.com/microsoft/vscode/issues?q=is%3Aissue+milestone%3A%22March+2022+Recovery+1%22+is%3Aclosed+

**Comment by dbaeumer** [comment]
@an-boxbrite fixed. I named the milestone Recovery

**Comment by an-boxbrite** [comment]
👍 Unfortunately now the link on the [release page](https://github.com/microsoft/vscode/releases/tag/1.66.1) is broken, still points at "...Recovery 1"

**Comment by TylerLeonhardt** [comment]
I think we're all good here now. Can you confirm it's fixed on your end?

**Comment by SIkebe** [comment]
Filtered result has no issue. Is that correct?
![image](https://user-images.githubusercontent.com/17608272/162348496-0dcbf066-74cc-4742-a523-c2cb90a1061c.png)

**Comment by dbaeumer** [comment]
Fixed the release page as well.

**Comment by SIkebe** [comment]
Thanks!
