### ISSUE TITLE
Missing command to open errors / warnings window

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#14639]
- VSCode Version: 1.6.1
- OS Version: Windows 10 Anniversary Update

Steps to Reproduce:
1. Open VSCode
2. Write some code with syntactical errors (eg. NodeJS)
3. Notice that the lower-left corner of VSCode indicates more than 0 errors or warnings
4. If you click the errors/warnings, an Error pane will appear in VSCode
5. Hit `F1` to open the command palette
6. Search for `error`
7. Notice that there is no command in the Command Palette to invoke the errors / warnings window that appears in step 4

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by weinand** [comment]
@pcgeek86 in the command palette search for "Problems". The 'error pane' is called "Problems View" in VS Code.

**Comment by pcgeek86** [comment]
@weinand might benefit from an alias pertaining to errors and warnings, too.

**Comment by jrieken** [comment]
@sandy081 Shouldn't we just call it Error & Warnings instead of Problems? Also, the action labels are misaligned, since one is prefixed with *View: *

**Comment by sandy081** [comment]
@jrieken Since the panel is called `Problems` I think it makes sense to called `Problems`. `Errors and Warnings` is an alias to assist users looking for errors and warnings

**Comment by jrieken** [comment]
Well, that's my suggestion: We rename the panel to `Errors & Warnings`. No one talks about "compile problems" but "compile errors"
