### ISSUE TITLE
Hierarchical View for "Go to symbol in Editor"

### ISSUE THREAD

**Issue by suspectinside** [microsoft/vscode#146374]
Add **Hierarchical View** for **Go to symbol** popup nav (with "Show/Hide inherited members" checkbox)
Here is how the similar functionality looks like in **PyCharm** (__/Navigate/File Structure__):

https://user-images.githubusercontent.com/101431780/160949853-507a5381-061d-4baf-a593-869322eb9c5a.mp4

and here is **Go to symbol in Editor** in **vscode**:

https://user-images.githubusercontent.com/101431780/160949908-243340b3-9945-4a10-9ba9-687f3c572bff.mp4

in **vscode** all the variables, arguments, methods, **classes** presented as a plain list, no ability to show\hide inherited members (with visual accents for better scanning) and the most important - no Hierarchical Structure to get quick "mental model" for the source relations.

**Comment by TylerLeonhardt** [comment]
We have a similar feature to this in the outline which you can see here in the outline view:
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/2644648/161366101-2dbacc0d-edab-48ca-86a4-25681c92e2fa.png">

> If you can't find it, run this command: `Focus on Outline View`

That view also has a search feature which you can see me demonstrate here. All you have to do is click inside of it and start typing... then you can choose to filter the tree if you want.
![outline](https://user-images.githubusercontent.com/2644648/161366173-478ad089-b3dd-45c4-a863-7989fd0cd494.gif)

The outline view is also viewable here in the breadcrumbs:
<img width="936" alt="image" src="https://user-images.githubusercontent.com/2644648/161366204-0cbc84bf-ff1f-4b3d-8658-7293acb34686.png">

**Comment by TylerLeonhardt** [comment]
cc @jrieken in case you have anything to add

**Comment by TylerLeonhardt** [comment]
Closing as answered
