### ISSUE TITLE
Source control repository missed a repository if we have multiple with same name

### ISSUE THREAD

**Issue by sssteja5** [microsoft/vscode#146396]
Issue Type: <b>Bug</b>

With the recent update 1.66, where the release note mentions that repositories are listed in alphabetical order in source control tab.

But, this created another bug where if we have 2 repros with same name under a folder, one of them will miss in the list.

Steps to reproduce:
1) Create root folder and project1 and project2 as sub folder under it
2) Create a git  repo name with 'test' under each project1/2
3) Now add root folder to the project explorer. And you will notice only one test git repo listed under source control tab

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-90-generic

**Comment by gjsjohnmurray** [comment]
@lszomoru I've already pointed one duplicate to this. I think a fix needs to be considered for recovery.

**Comment by lszomoru** [comment]
@gjsjohnmurray, yeah, I am currently looking at this and I will make sure that it is in the next recovery release.
