### ISSUE TITLE
Menu stays open after ALT + F in fullscreen mode

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#14637]
- VSCode Version: 1.6.1
- OS Version: Windows 10 Anniversary Update

Steps to Reproduce:
1. Open VS Code and enter Fullscreen mode (F11)
2. Hit `ALT + F`, then `ESC`
3. Notice that the menu stays open, at the top of the screen

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by bpasero** [comment]
We will change to custom menus on Windows. For now you can set `"window.titleBarStyle": "custom"`.
