### ISSUE TITLE
The native UI framework is exposed on win11 after 1.66.0

### ISSUE THREAD

**Issue by ericbrownz** [microsoft/vscode#146383]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0 (user setup)
- OS Version: Windows_NT x64 10.0.22000 (22000.593)

Steps to Reproduce:

1. Just open (without any other vscode windows)
2. The same issue when all extensions are disabled.

https://user-images.githubusercontent.com/34184767/160970347-cbfa5ee8-be31-4cad-bbd6-0ce8df6844fd.mp4

**Comment by eddiezato** [comment]
Same:

https://user-images.githubusercontent.com/11173476/160979232-bed0ba11-0728-49cc-a68e-b3e10e564a7d.mp4

**Comment by azusachino** [comment]
Same on win10 (21H2), kinda sucks
![image](https://user-images.githubusercontent.com/18746830/160984399-f4000f05-9a5f-4c7d-8dcf-57128780567d.png)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/146683
