### ISSUE TITLE
It seems that the text rendering engine has been changed in version 1.66

### ISSUE THREAD

**Issue by clzoc** [microsoft/vscode#146387]
Usually, I set the value of **_editor.fontweight_** as **_bold_** to activate the fake bold function of text rendering engine. It works well in version 1.65. However, the behavior of editor has changed in version 1.66. Two images are listed below to demonstrate my problem intuitively. 

The first image corresponding to version 1.65. 
![2](https://user-images.githubusercontent.com/62627722/160981344-d620225e-0d99-4828-afd2-4c3c455fc4d9.png)

The second image corresponding to version 1.66.
![3](https://user-images.githubusercontent.com/62627722/160981424-a076a5cf-d2c5-4d57-9b74-09fd669ff82d.png)

It seems that the text rendering engine of version 1.65 tend to stretch the width rather than increase the font weight like version 1.66. I prefer the former. Besides, I need the updates in version 1.66 such as **_Local History_** . Is it possible to select the old text rendering engine in version 1.66.

**Comment by deepak1556** [comment]
Does the issue repro with https://vscode.dev/ under similar font settings ?

**Comment by clzoc** [comment]
> Does the issue repro with https://vscode.dev/ under similar font settings ?
I try reproducing the issue with https://vscode.dev/, however I can't find the method to switch the version of the web vscode. Would you mind tell me how to reset the version to 1.65 on the web vscode? With the same font settings, it looks like below. I can't understand the tag **_needs version info_** you have added, because I have recorded the version information both in issue title and initial description.  

![1](https://user-images.githubusercontent.com/62627722/161076155-5aa66189-0df3-43b7-9e69-5216e52e4a94.png)

**Comment by deepak1556** [comment]
Thanks for the detailed repro steps, it helps! merging to https://github.com/microsoft/vscode/issues/146399. Please subscribe to that issue for updates.
