### ISSUE TITLE
VS Code Figma toolkit improvements

### ISSUE THREAD

**Issue by lychung7** [microsoft/vscode#146365]
Here are some of the improvements and updates that will be added to the VS Code Figma toolkit:

- [x] Update the quick pick component to include multi-select scenarios
- [x] Add left + right placement of panels
- [x] Update the Settings UI template to include the new hover state for the light theme 
- [x] Fix a few bugs in the Settings UI template
- [x] Fix button hover interaction

**Comment by TylerLeonhardt** [comment]
Moved this out but maybe it's actually done?
