### ISSUE TITLE
Share a file via vscode.dev link

### ISSUE THREAD

**Issue by tcz717** [microsoft/vscode#146309]
Hi team,

I noticed it is very useful to share a file link to a remote repo. So that if we'd like to send someone a part of your code in chat or emails, they can quickly identify which code you are talking about.

Eg: we can share code via https://vscode.dev/github/microsoft/vscode/main/src/main.js?l18

I found we have permalink support for GitHub, but it will be better to have it in Azure repo and support adding code range

**Comment by lychung7** [comment]
An idea is to add a share menu item in the File menu and bring over all the Copy As.. items into here along with a new Copy vscode.dev link. 

<img width="612" alt="Screen Shot 2022-04-22 at 10 21 53 AM" src="https://user-images.githubusercontent.com/60596156/164763823-2fdffa71-b7c1-4bdf-af80-b08ebc028758.png">

Currently, users receive no confirmation after clicking on any of the copy link items. It would be nice to validate that the link has been copied to their clipboard.

<img width="612" alt="Screen Shot 2022-04-22 at 10 22 07 AM" src="https://user-images.githubusercontent.com/60596156/164763820-2cb95146-ed5e-4583-b43a-11e7cd442f55.png">
