### ISSUE TITLE
Adopt to new `include` option in `IFileService.watch`

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#146335]
`IFileService.watch` method now supports a new `include` option that works like `exclude` but negated: only register to events that match a glob pattern. It doesnt really help for cases where you watch a folder and want to track for any change within, only when you watch a folder where you know other files are in that might change that you do not care about.

**Comment by bpasero** [comment]
Just to clarify: `IFileService.onDidChangeFile` does still fire events as before for every watcher that is registered in the system, so every listener still needs to check for the path it gets and only handle for paths it cares about. However, where the `include` pattern helps is really to reduce the number of events that will get emitted for everyone, so when you know exactly which files to watch in a folder, it should be used.

**Comment by sandy081** [comment]
While watching, if I have to include first level files, does it works if I just pass the base name of the files? For eg., if I am watching a directory for `settings.json` file, can I include `settings.json` as includes?

**Comment by bpasero** [comment]
@sandy081 no the same rule applies as for `files.watcherExclude`: the glob pattern will be matched on the full absolute path of the changed file.

**Comment by bpasero** [comment]
Refs:

https://github.com/microsoft/vscode/blob/b826b377cc0bddd46ca3e78d85f5d06e83cdc14a/src/vs/platform/files/node/watcher/nodejs/nodejsWatcherLib.ts#L372-L383

**Comment by sandy081** [comment]
Just to be sure, can you please confirm if following is correct?

`this.fileService.watch(extUri.dirname(this.userSettingsResource), { includes: [this.userSettingsResource.path], excludes: [], recursive: false })`

This is watching directory of settings resource and options include settings resource.

**Comment by sandy081** [comment]
FYI watch options are not exposed in `watch` method

https://github.com/microsoft/vscode/blob/b826b377cc0bddd46ca3e78d85f5d06e83cdc14a/src/vs/platform/files/common/files.ts#L241

**Comment by bpasero** [comment]
If you only care about `this.userSettingsResource.path`, why not watch it? Why watch its parent?

**Comment by sandy081** [comment]
In case if file does not exist, I have to watch the parent for the file creation

**Comment by bpasero** [comment]
I have added the watch options. 

One issue with the glob pattern being the literal path is that you have to make sure the path casing is the same as you pass it in when watching, but I guess you do that.

**Comment by sandy081** [comment]
I might need your help here. Following is not triggering the change event for the file I included

`this._register(this.fileService.watch(this.extUri.dirname(file), { includes: [file.path], recursive: false, excludes: [] }));`

**Comment by bpasero** [comment]
Careful, don't you have to use `uriToFsPath´method and not `file.path`, otherwise you might end up with the wrong variant?

**Comment by sandy081** [comment]
But I cannot use this `uriToFsPath` method in all environments right? Like this might not work in web for example?

**Comment by bpasero** [comment]
The method was specifically made so that it works in all environments. I.e. it would use `.fsPath` for `file` scheme.

**Comment by bpasero** [comment]
Hm, maybe we should rather allow for `IRelativePattern` in the watch API because that solves the issue of combining a glob pattern with a path. We introduced that specifically to avoid having to join paths with patterns because you never know which format to use. I can look into that.

**Comment by bpasero** [comment]
Working on this I noticed that the file watcher is being disposed right after startup, filed https://github.com/microsoft/vscode/issues/147499

As for providing the option to use relative pattern, work happens in https://github.com/microsoft/vscode/commit/502b9fe644c01cabbd0f11aee8713c109eb76bdd

**Comment by bpasero** [comment]
Pushed https://github.com/microsoft/vscode/commit/e6d98a13fcd3bf928d0e755eaae873ac200a98bd to allow for relative pattern in `include`. This should be possible now:

```ts
const userSettingsFolder = extUri.dirname(this.userSettingsResource);
this._register(this.fileService.watch(userSettingsFolder, { includes: [{ base: userSettingsFolder.fsPath, pattern: basename(this.userSettingsResource) }], excludes: [], recursive: false }));
```

Still requires the fix for https://github.com/microsoft/vscode/issues/147499
