### ISSUE TITLE
[css] Add CSS formatting option to place open brace on new line

### ISSUE THREAD

**Issue by brunnerh** [microsoft/vscode#146398]
It would be nice if the CSS formatter had an option analogous to the JS/TS options to place open braces on a new line.

```jsonc
{
	// Existing brace options:
	"typescript.format.placeOpenBraceOnNewLineForFunctions": true,
	"typescript.format.placeOpenBraceOnNewLineForControlBlocks": true,
	"javascript.format.placeOpenBraceOnNewLineForFunctions": true,
	"javascript.format.placeOpenBraceOnNewLineForControlBlocks": true
}
```

The underlying CSS formatter Beautify has an option to do this:
`brace-style` needs to be set to `expand` (default is `collapse`).

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying CSS formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?

**Comment by brunnerh** [comment]
@aeschli Please re-read the issue description. This is **not** about an issue in Beautify itself, but VS Code not having an option to control its behavior.

I explicitly noted that Beautify already has the required capabilities:
> The underlying CSS formatter Beautify has an option to do this:
> `brace-style` needs to be set to `expand` (default is `collapse`).

**Comment by aeschli** [comment]
Sorry for missing your last sentence, I wasn't aware that this also is supported for css
