### ISSUE TITLE
annoying three dots show and disappear at the top left of a lua file when typing   

### ISSUE THREAD

**Issue by xiangnanscu** [microsoft/vscode#146379]
Issue Type: <b>Bug</b>

1. open a lua file, type any characters
2. three dots show for seconds and then disappear
![vscode bug](https://user-images.githubusercontent.com/8246344/160960024-66a472cf-0bff-4227-99f9-4a44c8088309.png)

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200G with Radeon Vega Graphics     (4 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|29.93GB (19.65GB free)|
|Process Argv|--crash-reporter-id daaa0b00-9e11-414d-9f6c-c917ae577c8c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|AMD Ryzen 3 3200G with Radeon Vega Graphics (4 x 3593)|
|Memory (System)|23.43GB (19.72GB free)|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
bracket-pair-colorizer|Coe|1.0.62
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vue-snippets|hol|1.0.4
remote-containers|ms-|0.231.0
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.78.0
remote-wsl|ms-|0.66.0
vscode-remote-extensionpack|ms-|0.21.0
JavaScriptSnippets|xab|1.8.0
pgformatter|bra|1.18.0
npm-intellisense|chr|1.4.1
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.5
vscode-html-css|ecm|1.11.0
vscode-npm-script|eg2|0.3.24
vs-code-xml-format|fab|0.1.5
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.11.7
vue-snippets|hol|1.0.4
vscode-lua-format|Koi|1.3.8
python|ms-|2022.4.0
vscode-pylance|ms-|2022.3.4
vuejs-extension-pack|mub|1.6.0
vetur|oct|0.35.0
prisma|Pri|3.11.0
lua|sum|2.6.7
prettier-plus|svi|4.2.2
intellicode-api-usage-examples|Vis|0.0.10
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvid2:30447481
pynewfile477:30463512

```

</details>

**Comment by xiangnanscu** [comment]
this cause the entire file content up and down, really annoying

**Comment by xiangnanscu** [comment]
More info, it seems  that this issue only exists in lua file whose content is small (below 30 llines).

**Comment by FierceJDM** [comment]
I found that this problem can be fixed by disabling `GitLens>CodeLens>RecentChange` in Settings.

src : https://stackoverflow.com/questions/66294274/vscode-three-dots-at-the-top-of-the-editor

**Comment by xiangnanscu** [comment]
@FierceJDM Thanks. I disabled gitlens and problem solved.
