### ISSUE TITLE
Support `inline` as config value for `editor.suggestOnTriggerCharacters`

### ISSUE THREAD

**Issue by bdch1234** [microsoft/vscode#146405]
First of all I think the new feature for showing quick-suggestions inline is fantastic. I was expecting it to also work for class-members though, is it intentional that it falls back to the widget in that case?
![image](https://user-images.githubusercontent.com/46796385/161019761-ce79335f-4c7a-415e-a399-7513935be1ef.png)
![image](https://user-images.githubusercontent.com/46796385/161019842-9afdea9a-f120-4aca-9d06-fbf38ceffd5f.png)

**Comment by jrieken** [comment]
You can control this to some extend: set `editor.suggestOnTriggerCharacters` to `false` and then start typing. Tho, there is no `"inline"` option for that setting.

**Comment by bdch1234** [comment]
That works, thanks @jrieken.

**Comment by jrieken** [comment]
Re-opening for a small tweak, e.g to honor trigger character for inline suggest too

**Comment by jrieken** [comment]
To verify:

* have the settings below
* open a typescript file
* type `console.`
* ensure that after the `.` inline suggestions are shown

```
    "editor.suggestOnTriggerCharacters": true,
    "editor.quickSuggestions": {
        "other": "inline",
        "comments": "off",
        "strings": "off"
    },
```

**Comment by byehack** [comment]
Hello @bdch1234
How did you set `.` as trigger charater for python files?

**Comment by jrieken** [comment]
To verify:

* use TypeScript
* enable inline quick suggestions (see below)
* type `console.`
* make sure that after the `.` inline quick suggestions appear


```
"editor.quickSuggestions": {
		"other": "inline",
		"comments": "inline",
		"strings": "inline"
	},
```

**Comment by alexr00** [comment]
I still see the suggest widget show using the verification steps with the settings set.
