### ISSUE TITLE
TypeScript completion is very slow and needs press shortcuts more.

### ISSUE THREAD

**Issue by yamachu** [microsoft/vscode#146407]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.67.0-insider (Universal) Commit: 95e8ecaa65bf2d790a4e3b586e843435fc5c0f77
- OS Version: macOS 12.2.1（21D62）

Steps to Reproduce:

1. Write a code with complex object in TypeScript
2. Use code completion

Insiders
![insiders](https://user-images.githubusercontent.com/1955233/161021206-a0c6d6e4-a03f-4585-a166-03706045eb69.gif)

Stable
![stable](https://user-images.githubusercontent.com/1955233/161021239-13bc4334-4fe0-43fe-af29-5fbb5d25ad5f.gif)

The Insiders version outputs the completion as soon as the bracket `{` is entered.
This is great, but it appears that only snippets that do not match the context of the code are being displayed. (ex, object member)
It seems to me that displaying something that does not match the context of the code is noise.

**Comment by mjbvz** [comment]
Please share a project that demonstrates this issue

**Comment by yamachu** [comment]
https://github.com/yamachu/repro-vscode-146407

I made a sample project

**Comment by mjbvz** [comment]
Thanks for the example project

In the latest insiders, suggestions should not show up when you press space inside the `brackets`. Instead they will show with you type `h` or `f` (or manually trigger suggestions using ctrl+space)

This seems like the expected behavior to me. Is this different than what you expect?

**Comment by yamachu** [comment]
It is just what I expected.
The experience is great as contextual suggestions are displayed.
Thanks!

**Comment by mjbvz** [comment]
Closing as it sounds like this not longer is reproducible
