### ISSUE TITLE
TreeItem does not display `folder` theme icon

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#146479]
It looks like specifying `folder` in the icon path does not render the icon in a `TreeItem`:

```this.iconPath = new ThemeIcon("folder");```
<img width="318" alt="CleanShot 2022-03-31 at 15 15 35@2x" src="https://user-images.githubusercontent.com/25163139/161158647-66b6260f-5b5f-4356-94ac-935822bff0d7.png">

I was able to work around this with an alias pointing to the same icon for now:

```this.iconPath = new ThemeIcon("file-directory");```
<img width="334" alt="CleanShot 2022-03-31 at 15 05 17@2x" src="https://user-images.githubusercontent.com/25163139/161156948-b6cae495-239a-416d-b687-aa5fd253be93.png">

**Comment by misolori** [comment]
@joaomoreno I talked to @aeschli about this and it appears like this is a bug on tree view for specifying folders:

> In resource trees, `folder` refers to the folder icon from the current file icon theme.
But if the file icon theme has no folder icon, it should fall back to the codicon folder icon.

**Comment by alexr00** [comment]
If the tree item represents a resource then we should still respect the file icon theme's choice about whether to show a folder icon.

However, for non-resources, we should show the folder icon.

**Comment by daviddossett** [comment]
Thanks for fixing @alexr00!

**Comment by JacksonKearl** [comment]
Verified? 
<img width="659" alt="image" src="https://user-images.githubusercontent.com/8586769/165813730-695680db-ae73-41f7-b779-45d4a84f43cd.png">

Looks like the theme's folder icon is not getting used when `treeItem.iconPath = new vscode.ThemeIcon("folder");` is set for a non resource tree view item, instead falling back to the generic codicon. Not sure if this is intended.

**Comment by alexr00** [comment]
Yes, that's intended. Thank you for verifying!
