### ISSUE TITLE
Container error 

### ISSUE THREAD

**Issue by jinsi286** [microsoft/vscode#146460]
ADD ISSUE DESCRIPTION HERE

Error occurring in my codespace since I updated it. It is a container error. And everytime I open the codespace it prompts to make changes in creation.log and then run rebuild container command.
I dont know what to do. Please help.

Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
Embedder: codespaces

**Comment by lramos15** [comment]
Codespaces support can either be obtained here https://support.github.com/request/codespaces?tags=hubberfy_codespaces
