### ISSUE TITLE
Update Theme API Doc.

### ISSUE THREAD

**Issue by Samyak-Bumb** [microsoft/vscode#146495]
- VS Code Version: 1.66.0
- OS Version: Windows 10

Steps to Reproduce:

1. https://code.visualstudio.com/api/references/theme-color

Update the Theme API of new properties which are added in **March 2022 (version 1.66)**:-
Example - `comments.resolved.border`, `comments.unresolved.border` etc.

**Comment by aeschli** [comment]
The names of the colors need to be improved first. See https://github.com/microsoft/vscode/issues/146813
