### ISSUE TITLE
Default terminal.integrated.defaultProfile.* value is invalid

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#146437]
Open default settings JSON:

![image](https://user-images.githubusercontent.com/2193314/161079185-5e23b42d-988b-4293-956a-05de2f518d28.png)

Version: 1.67.0-insider (user setup)
Commit: https://github.com/microsoft/vscode/commit/909602cf04e0fa42528d692676d0d4e15e67bba2
Date: 2022-03-31T11:00:49.798Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by meganrogge** [comment]
windows and linux issue only - works on mac
<img width="481" alt="Screen Shot 2022-03-31 at 11 16 55 AM" src="https://user-images.githubusercontent.com/29464607/161090326-05394648-f7de-4205-95a7-a04e718c4354.png">

**Comment by meganrogge** [comment]
but not in the settings editor actually

**Comment by Tyriar** [comment]
I think it happens on mac too, was originally reported for .osx

**Comment by meganrogge** [comment]
@rzhao271 any thoughts as I know you did some work related to enum settings?

**Comment by rzhao271** [comment]
Not sure, but I get a mysterious result `%debug.terminal.label%` in the suggestions:
![Terminal suggestions](https://user-images.githubusercontent.com/7199958/161152617-c78ad35e-84ee-4413-bb8b-fd908b71a449.PNG)

**Comment by meganrogge** [comment]
yeah that should be `JavaScript Debug Terminal`

**Comment by aeschli** [comment]
@Tyriar You need to add `null` as a valid value to the enums as well.

**Comment by meganrogge** [comment]
> windows and linux issue only - works on mac
> 
> <img width="481" alt="Screen Shot 2022-03-31 at 11 16 55 AM" src="https://user-images.githubusercontent.com/29464607/161090326-05394648-f7de-4205-95a7-a04e718c4354.png">
> 
> 

@aeschli I believe null is already one of the enum values

**Comment by aeschli** [comment]
The completion values are composed of enum, default and more.
The validation only looks at at enum values.

So I'm quite sure the num values don't contain null, as the hover shows:
![image](https://user-images.githubusercontent.com/6461412/161239421-92e1d4d8-6f23-4c45-abaa-54925fe4b9f8.png)
