### ISSUE TITLE
`github.dev` Insiders broken

### ISSUE THREAD

**Issue by filiptronicek** [microsoft/vscode#146452]
Hello everyone from the VS Code team 👋!

I have run into some issues since today with the Insiders version of github.dev. This renders github.dev unable to load some crucial parts due to `NetworkError`s.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.0-insider (909602cf04e0fa42528d692676d0d4e15e67bba2)
- OS Version: macOS 12.3
- Browsers tested: Firefox (v98 & v100), Brave (v1.36.122)

Steps to Reproduce:

1. Open a repo in github.dev and change to Insiders with the cog icon on the bottom of the page (e.g. https://github.dev/github/dev)
2. Observe the UI not loading (file tree has a loading indicator)

Attached logs from Firefox:
[console-export-2022-3-31_18-33-48.txt](https://github.com/microsoft/vscode/files/8391631/console-export-2022-3-31_18-33-48.txt)

I think this might be due to the change of the WebView CDN in https://github.com/microsoft/vscode/commit/a3e739fee9a63c932bf2d9578547f52bc6a59a62.

![image](https://user-images.githubusercontent.com/29888641/161110985-51fde441-e62b-4df3-a037-df1863b37633.png)

I hope this is the right repo to publish this on, and if this is not something that you work on in the Code team, I would kindly ask you to forward it to the correct team @ GH.

**Comment by misolori** [comment]
Seeing the same thing today:

https://user-images.githubusercontent.com/35271042/161117174-8e585195-64b8-466c-bbb2-41d101500214.mp4

**Comment by filiptronicek** [comment]
Many thanks for the video repro @misolori 🙏

**Comment by joaomoreno** [comment]
We're handling this issue in an GitHub internal repository. Closing as a duplicate. Mitigation is on its way.
