### ISSUE TITLE
Inline suggestions respect completeFunctionCalls setting

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#146468]
It would be awesome if inline suggestions: `editor.quickSuggestions: inline` could respect:

```
  "javascript.suggest.completeFunctionCalls": true,
  "typescript.suggest.completeFunctionCalls": true,
```

So when inline suggest appears and it is function call by pressing tab it would add missing `()` or other arguments as usual.

**Comment by jrieken** [comment]
From TS/JS I am receiving the completion without the "call snippet" part, e.g receiving `log`, not `log($1)$0`. @mjbvz Do you know why that is? Does function call snippet completion only work when doing trigger character completions? Or does the completion need to be resolved for it?

**Comment by mjbvz** [comment]
Yes completion does need to be resolved. We need the extra info from resolve to determine if function call completions should be enabled or not

**Comment by jrieken** [comment]
This should now be working as good as with normal suggest. Saying "as good as" because very quick typing and accepting might still hit the case when an item isn't resolved yet

**Comment by svipas** [comment]
@jrieken Thank you very much! 🎉

**Comment by jrieken** [comment]
To verify

* use TypeScript
* enable inline quick suggestions
* enable `"typescript.suggest.completeFunctionCalls": true,`
* type `console.l`
* make sure that `log` is suggested as ghost test and that it includes the parameter
