### ISSUE TITLE
Debug: breakpoint gets deleted when removing leading whitespace

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14643]
I have code like this:

```javascript
var text = "some text";

setTimeout(function () {
    console.log(text);
}, 0);
```

I have a breakpoint in the line of the `console.log` statement and when I delete the leading whitespace, the breakpoint is gone for me.

![editors](https://cloud.githubusercontent.com/assets/900690/19798560/24f746b2-9cf2-11e6-9633-7fbf5ba8e86a.gif)

**Comment by isidorn** [comment]
Weird bug, reprodcues with stable -> November
