### ISSUE TITLE
VSCode keep not responding when opening large project/files

### ISSUE THREAD

**Issue by baadillahnabil** [Microsoft/vscode#14640]
- VSCode Version: 1.6.1
- OS Version: Windows 10 64-bit build 14393

my visual studio code is always not responding or crashes when i opening my project. i use laravel framework, so that mean it contains a lots of files including the files that i created my own.. it always stuck after 5-10 mins after my project is opened.. 

buttons "Keep Waiting" and "Reopen" also doesn't work, i already tried to keep waiting, but it's never responding again. i tried reopen, but it's also not reopening vscode.. 

hope you guys can fix this, because i really love this editor :) 

Right now i use sublime text or atom until vscode is normal again.. 

Additional informations : 
- i have about 20 plugins/extentions installed
- my project size is about 20MB and about 5000+ files
- i also use git (just information)

and i apologize if my english is not very good, but i tried my best.. Thank You guys, keep spirit :)

**Comment by bpasero** [comment]
Here is a **checklist** to find out more about the freeze/slow/crash
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] there is no suspicious output when running from the command line (`code --verbose`)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line)
- [ ] it reproduces after deleting `<appdata>/User/keybindings.json` and `<appdata>/User/settings.json` (backup first! see below for paths)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`

**Comment by baadillahnabil** [comment]
Here is a checklist to find out more about the freeze/slow/crash

- [ ]  it was not happening in the previous stable release (it's happening in previous stable release)
- [x]   it reproduces in insiders builds
- [ ]  there is no suspicious output when running from the command line (code --verbose)
      (i don't know about this, so i just run it and paste it here) 
>`←[93m[main 9:02:06 PM]←[0m Sending env to running instance...`
>`←[93m[main 9:02:06 PM]←[0m Sent env to running instance. Terminating...`

- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console) (actually, there is, it's shows some warnings and errors, this is the screenshoots : )
![image](https://cloud.githubusercontent.com/assets/12659161/19809400/66bbc454-9d53-11e6-809f-cca051cdd744.png)

- [x]  it reproduces on Windows, Linux and Mac (i use windows as i mentioned before)
- [x]  it reproduces with extensions disabled (code --disable-extensions from the command line)
- [x]  it reproduces after deleting <appdata>/User/keybindings.json and <appdata>/User/settings.json (backup first! see below for paths) (tried after and before, same result)
- [ ]  it reproduces when opening empty (code -n from the command line) ( if just one file opened and it's also empty or just few lines of code it's alright, nothing's wrong, but when open large project and bunch of files it's get stuck)
 - [ ] it reproduces opening any folder
- [ ]  it reproduces opening any file
- [ ]  it reproduces when only having a single window open
- [ ]  it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control (i use git in my project)
- [ ]  it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (code --disable-gpu)
- [ ]  it reproduces when being offline (i'm always online when i use my laptop)
- [ ]  it reproduces when disabling the file watching (set files.watcherExclude to "**/**": true)
- [ ]  it reproduces after uninstalling and reinstalling
- [ ]  it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ]  I have not played around with permissions or ran Code as administrator (already tried that, still no luck)
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments) (i don't know about this)
- [x] I am seeing Code consuming lots of memory in a short time (in the task manager, memory consuming is not too bad, but somehow it's freeze)


Additional Informations : 
- i often see the cursor still blinking when the editor is freeze, and it's also doesn't show "not responding" title in title bar.. 
- i use in my laptop that have AMD A10 processor, 4GB RAM, HD Radeon Dual graphics and still have a lot of free space storage

**Comment by bpasero** [comment]
@baadillahnabil are you able to share this workspace with me?

**Comment by bpasero** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by baadillahnabil** [comment]
good news @bpasero , i found out what causing the high load, it because an extention called "HTML CSS Class Completion" , it loads every class in my css files inside my project and that is what cause this laggy.. i don't mean to "disfigure" the extention, i just telling the truth that that extention is causing this laggy, after i uninstall that extention, it works smooth now.. :) 

just my opinion : that extention is great, i like what that extention can do, but it's eating performance and causing lag/crash/freeze in vscode.. 

and thank you very much @bpasero , because you are really kind to me, even though my english is bad, but u still can understand what i'm trying to say :D

**Comment by mrmlnc** [comment]
Well, I will help to author of this extension, because this extension creates a lot of problems.

**Comment by bpasero** [comment]
@baadillahnabil one of the steps of the checklist asks to run with extensions disabled, maybe you skipped it? This is one of the first suspicious things to try out.

Otherwise please report against the extension 👍

**Comment by baadillahnabil** [comment]
Thank you @mrmlnc  :D 

@bpasero i tried that but i ran it in the terminal built in inside vscode, nothing happend, so i assume that doesn't work.. but i serach online and i found out that that command have to run in standalone terminal/cmd in order to open vscode without extentions...
