### ISSUE TITLE
Debian packages for 1.66 missing from apt repository

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [microsoft/vscode#146430]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66
- OS Version: Debian Stable

Steps to Reproduce:

1. Install vscode 1.65
2. Wait for vscode 1.66 to be released
3. Wait for another day
4. `sudo apt update`
5. `apt policy code | head`

Expected result: vscode 1.66 is available to upgrade via apt

Actual result: The latest available version via apt is 1.65.2:
```
     1.65.2-1646927742 500
        500 https://packages.microsoft.com/repos/code stable/main amd64 Packages
```

**Comment by vasudev-gm** [comment]
I have similar issue on Ubuntu 20.04.4 with vscode deb repo as well.

**Comment by carstencodes** [comment]
Same here on Linux Mint 20.3. 

On https://code.visualstudio.com I can download the file via https://az764295.vo.msecnd.net/stable/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/code_1.66.0-1648620611_amd64.deb.

**Comment by carstencodes** [comment]
@Tyriar The index is up to date. The package for amd64 is entirely missing in https://packages.microsoft.com/repos/code/pool/main/c/code/ while armhf and arm64 are present.

**Comment by Tyriar** [comment]
@carstencodes I don't know if index is the correct term, but that's the page that I know it's absent from and I believe it's on their end that it isn't showing up as we definitely did publish the amd64 package.

**Comment by carstencodes** [comment]
Ah, ok, the index is stored at https://packages.microsoft.com/repos/code/dists/stable/main/binary-amd64/Packages

**Comment by SE2Dev** [comment]
It's showing up now.

**Comment by RossBoylan** [comment]
I can get the update too :+1:

**Comment by Tyriar** [comment]
They republished the package which fixed it 👍

**Comment by shungo27** [comment]
arm64 has stopped at 1.65.0.

code / stable, now 1.65.0-1646219639 arm64

raspberry pi os 64bit lite bullseye
gnome 3.38

source.list
deb http://deb.debian.org/debian bullseye main contrib non-free
deb http://security.debian.org/debian-security bullseye-security main contrib non-free
deb http://deb.debian.org/debian bullseye-updates main contrib non-free
deb http://archive.raspberrypi.org/debian/ bullseye main
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x bullseye main
