### ISSUE TITLE
Alt + Shift + O does not work to type Ó in Polish Keyboard

### ISSUE THREAD

**Issue by tomkowz** [Microsoft/vscode#14641]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 15.6.0
- Extensions: donjayamanne.python-0.3.21, magicstack.MagicPython-0.5.15, ms-vscode.cpptools-0.9.2, tht13.python-0.2.3

Steps to Reproduce:
1. Change Keyboard on Mac to "Polish Pro"
2. Open Visual Studio Code
3. Type Alt + Shift + O to type Ó.

Observed: See no character typed.
Expected: Ó should be typed.

**Comment by alexandrudima** [comment]
@tomkowz Can you please try the exact same steps I recommend to try in https://github.com/Microsoft/vscode/issues/4712#issuecomment-256851526 and report here.

Of course, with your keyboard layout and with your specific key combination `Alt+ Shift + O` and reporting here the results.

**Comment by tomkowz** [comment]
@alexandrudima Sure, here is my screenshot.

![screen shot 2016-10-28 at 11 06 07](https://cloud.githubusercontent.com/assets/2303177/19801343/2aeb7e1e-9cff-11e6-8a39-e435163cd653.png)

**Comment by alexandrudima** [comment]
@tomkowz Thank you. Can you also do the next two headings in the comment:

### Check what we detect

### Check who binds this keybinding

**Comment by tomkowz** [comment]
@alexandrudima, sorry for the delay. Here is the other info you need.

### Check what we detect
![screen shot 2016-11-08 at 11 40 56](https://cloud.githubusercontent.com/assets/2303177/20096013/3ee03d86-a5a8-11e6-9fa3-06bfb503433d.png)

### Check who binds this keybinding
```
{ "key": "alt+o",                 "command": "C_Cpp.SwitchHeaderSource",
                                     "when": "editorTextFocus" }
```

**Comment by alexandrudima** [comment]
@tomkowz Thanks for following up on this. Looks like that keybinding comes from an extension.

You can change your `keybindings.json` and add the following to be sure `alt+o` and `shift+alt+o` are not handled by anyone (i.e. are allowed to produce Ó):

```
// Place your key bindings in this file to overwrite the defaults
[
  { "key": "alt+o" }
  { "key": "shift+alt+o" }
]
```

**Comment by tomkowz** [comment]
Thanks, it works now. Do you plan to make it available for all users or still other Polish users of the app will have to do that in order to be able to type this polish character?

**Comment by alexandrudima** [comment]
Specifically, in this case the keybinding comes from an extension. What we plan to do in the core of vs code is to allow end users to review what extensions contribute and disable/enable specific contribution points. e.g. in this case you could toggle that the extension that introduces `C_Cpp.SwitchHeaderSource` is allowed to contribute a keybinding or not. I don't think we have an issue tracking this at this point, but it is something we want to do.

On the long term, the best way to serve different keyboard layout users is through implementing #1240. That means that we would allow the extension that introduces `C_Cpp.SwitchHeaderSource` to `alt+o` to express something like: "on all keyboard layouts, bind this to alt+o, but on the Polish keyboard layout bind it to ctrl+o, or whatever".

On our side, there is nothing actionable to do from this issue, I cannot block extensions from binding "alt+o", for example. You can file an issue against the extension that introduces `C_Cpp.SwitchHeaderSource` and upvote #1240 such that it moves up the backlock from a priority point of view.

Therefore, closing for now...

**Comment by tomkowz** [comment]
Okay, thanks!
