### ISSUE TITLE
Update broke pymaker extention

### ISSUE THREAD

**Issue by Ladybrinx** [microsoft/vscode#146418]
Issue Type: <b>Bug</b>

I installed the March 2022 version of VS code and now pymaker won't connect to my serial port... it doesn't seem to be working at all, I uninstalled and reinstalled it and it doesn't fix anything. I also installed the pymaker v2 alpha, also doesn't connect to my device.

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.15GB free)|
|Process Argv|--crash-reporter-id 36ea55df-4518-4083-b2ef-d629823a6a63|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.4.0
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.9.7
pymakr|pyc|1.1.17
pymakr-preview|Pyc|2.8.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvidc:30447482
pynewfile477:30463512

```

</details>

**Comment by gjsjohnmurray** [comment]
@Ladybrinx have you reported this to the extension repo? If so, please add the link here. Extension author is best placed to determine what changed in 1.66 to cause your problem.

**Comment by Ladybrinx** [comment]
Sorry no, I just clicked the Help->Report issue and it brought me here. Thanks, I'll try that

**Comment by schmt16** [comment]
Same conditions, same problem.
@Ladybrinx Downgrade to VScode 1.65 solved the issue for me. (Turn off autoupdate)
Seems a common issue, VScode updated remap serial code bindings and break pymakr. There are multiple times the same issue over years...

**Comment by schmt16** [comment]
@Tyriar, @gjsjohnmurray  sorry, i'm clueless at this level of software engineering. according to the number of same issues i found here and at the pymakr extension, this problem exists since years. can i ask you: 
-why has vscode to remap serial port bindings with updates?
-is there any chance for the developers of the pymakr extension to automate their process of capture and implement this remaping?
thank you for your information

**Comment by Ladybrinx** [comment]
@schmt16 I did the same think, rolled back to the Feb Version and it works fine, I assume they will update this version too eventually

**Comment by Tyriar** [comment]
Sometimes when VS Code updates and extension may break for various reasons, this latest version updated the Electron version which bumps the node version an extension would use which is likely the problem. The extension needs to be updated to be compatible, there's nothing we can do on our end.

**Comment by jakobrosenberg** [comment]
The issue is likely solved by uninstalling and reinstalling Pymakr, which should redownload / rebuild correct bindings.

There's also a preview version of [Pymakr 2](https://marketplace.visualstudio.com/items?itemName=pycom.pymakr-preview), which uses N-API bindings. These should be more reliable.

Backstory: Node can't communicate with the serial port directly, so we need to build binaries that handle this. These bindings have to match the Node / Electron environment, which occasionally changes with VSCode updates.

**Comment by Tyriar** [comment]
@jakobrosenberg could the extension catch the failure and give a good error message for node module version mismatches?

**Comment by Ladybrinx** [comment]
> The issue is likely solved by uninstalling and reinstalling Pymakr, which should redownload / rebuild correct bindings.
> 
> There's also a preview version of [Pymakr 2](https://marketplace.visualstudio.com/items?itemName=pycom.pymakr-preview), which uses N-API bindings. These should be more reliable.
> 
> Backstory: Node can't communicate with the serial port directly, so we need to build binaries that handle this. These bindings have to match the Node / Electron environment, which occasionally changes with VSCode updates.

Uninstalling and reinstalling didn't work, I tried that first... I also tried the Pymakr 2, also didn't work.  The only thing that worked was rolling back to the Feb 2022 update.  I appreciate everyone's input here though.  added this before searching the web and finding the issue... I guess I should have waited.  I see that this is a common problem when there is an update.

**Comment by jakobrosenberg** [comment]
@Tyriar the plugin should automatically rebuild the bindings if they aren't working, but for some reason it can't run command any longer. I'll have to look into the cause of this.

@Ladybrinx do you remember what error you got with the Pymakr 2 preview?

**Comment by Ladybrinx** [comment]
@jakobrosenberg  sorry I don't remember, I should have taken a screen shot, it was similar to the pymakr one but not as detailed, still talking about not being able to find the device.
