### ISSUE TITLE
Repl console height is off

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#14649]
#14429 talks about the arrow being off center. But now, the whole row is off center, vertically: a single line is much shorter than the space reserved for it:

![image](https://cloud.githubusercontent.com/assets/22350/19799738/84e1cfba-9cf8-11e6-965c-e36921d6b31c.png)

**Comment by isidorn** [comment]
It is not that it is not vertically centered but the we somehow layout the editor wrongly so more than one line is visible. Once an expression is entered it gets into a nice one line state again

**Comment by isidorn** [comment]
@alexandrudima after investigating it seems like the editor is sending a wrong scroll change event when vscode window resizes to a smaller size.

To reproduce
1. Open debug repl
2. Reduce the size of the whole vscode window 
3. Notice that even if the debug input is empty the editor is emitting scroll change events with `scrollHeight = 28` [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/repl.ts#L191)

**Comment by alexandrudima** [comment]
@isidorn Let's debug this together
