### ISSUE TITLE
how to make the font italic

### ISSUE THREAD

**Issue by Chinazhouwy** [Microsoft/vscode#14642]
How to make the font italic?

**Comment by alexandrudima** [comment]
@Chinazhouwy That is controlled by themes. i.e. themes have the ability to select certain scopes and give the text color, boldness or italics. You can create a custom theme either by starting from scratch or from taking an existing theme and customizing it.

Further information in the docs page: https://code.visualstudio.com/docs/customization/themes#_creating-a-custom-theme
