### ISSUE TITLE
Color Difference between active and inactive menu lost

### ISSUE THREAD

**Issue by krishvk** [microsoft/vscode#146491]
Issue Type: <b>Bug</b>

With the latest update, active and inactive menu in settings UI does not look any different from each other

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1127.10.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (4.56GB free)|
|Process Argv|--file-uri vscode-remote://ssh-remote%2Bde02/u/kasula/snps/git/de02.code-workspace --crash-reporter-id 92166129-bdaf-465c-bdcc-6df28a903283|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: de02|
|OS|Linux x64 3.10.0-1127.10.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 5218R CPU @ 2.10GHz (2 x 2100)|
|Memory (System)|7.62GB (2.00GB free)|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
LogFileHighlighter|emi|2.15.0
remotehub|Git|0.28.0
better-cpp-syntax|jef|1.15.13
blockman|leo|1.5.7
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.231.1
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.78.0
remote-wsl|ms-|0.66.0
remote-repositories|ms-|0.4.0
material-icon-theme|PKi|4.15.0
rewrap|stk|1.16.3
vscode-icons|vsc|11.10.0
vscode-todo-highlight|way|1.0.5
path-intellisense|chr|2.8.0
vscode-clock|Com|0.0.1
gitlens|eam|12.0.5
systemverilog|eir|0.12.1
prettier-vscode|esb|9.5.0
seito-openfile|Fr4|1.8.8
html-preview-vscode|geo|0.2.5
jira-plugin|gio|0.22.2
gitlab-workflow|Git|3.41.2
gc-excelviewer|Gra|4.2.54
beautify|Hoo|1.5.0
path-autocomplete|ion|1.19.1
svg|joc|1.4.17
vscode-jira|Kni|0.6.0
restructuredtext|lex|183.0.0
python|ms-|2022.4.0
vscode-pylance|ms-|2022.3.4
jupyter|ms-|2022.3.1000901801
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.9.7
veriloghdl|msh|1.5.3
subtle-brackets|raf|3.0.0
LiveServer|rit|5.7.5
code-spell-checker|str|2.1.11
vscode-input-sequence|tom|0.2.0
simple-rst|tro|1.5.2
vscodeintellicode|Vis|1.2.17
better-align|wwm|1.1.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
pythonvsnew555:30457759
vscscmwlcmt:30438805
pynewfile477:30463512

```

</details>

**Comment by krishvk** [comment]
![gif](https://user-images.githubusercontent.com/7437418/161199424-0c17a50c-a770-4a94-8212-132b96d4ea04.gif)
![1 user](https://user-images.githubusercontent.com/7437418/161199436-ee41de00-054f-41f0-a094-b0c965388553.png)
![2 remote](https://user-images.githubusercontent.com/7437418/161199437-739d2bef-748e-4345-aeaa-ee24377c1ea8.png)
![3 workspace](https://user-images.githubusercontent.com/7437418/161199439-6fba9ed0-f246-4108-975b-3ff3c416a752.png)

**Comment by gjsjohnmurray** [comment]
By "active and inactive menu" I assume you are referring to the tabs labelled "User", "Remote", "Workspace" etc.

Which color theme are you using?

Do you also see the issue when using the default themes (Light+ and Dark+)?

**Comment by krishvk** [comment]
Yeah, I am referring to "User", "Remote", "Workspace" etc.

I am using Night Owl Light Theme

**Comment by rzhao271** [comment]
Does this problem occur when you don't have a multi-root workspace open?

**Comment by krishvk** [comment]
The issue is seen only with a multi-root workspace. Is it a known issue?
