### ISSUE TITLE
CSS formatter problem when using tailwindcss

### ISSUE THREAD

**Issue by onjunPenguin** [microsoft/vscode#146484]
Hi,

The build-in CSS formatter inserts unnecessary spaces when using tailwindcss, causing errors when building.
An example is below.

`/* Before */`
`@apply flex flex-col lg:flex-row space-y-3 lg:space-x-12 items-start;`
`@apply text-[clamp(0.75rem,0.5625rem+0.3906vw,0.875rem)];`

`/* After */`
`@apply flex flex-col lg: flex-row space-y-3 lg:space-x-12 items-start;`
`@apply text-[clamp(0.75rem, 0.5625rem+0.3906vw, 0.875rem)];`

Tailwindcss is indispensable and it would be great if you could fix it.
Thanks.

**Comment by onjunPenguin** [comment]
Sounds like a js-beautify issue perhaps.

**Comment by aeschli** [comment]
Yes, thanks, please file against https://github.com/beautify-web/js-beautify.
