### ISSUE TITLE
Broken Flutter hot reloads in 1.66

### ISSUE THREAD

**Issue by incloudss** [microsoft/vscode#146448]
Issue Type: <b>Bug</b>

Hot reload works flawlessly on 1.64.2, and cause diconnecting from debug mode on 1.66

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (10.59GB free)|
|Process Argv|--crash-reporter-id 02c876f5-b53a-4335-aef0-05f4fb34e101|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
freezed|bla|0.9.6
very-smart-select|clo|0.3.0
dart-code|Dar|3.36.0
flutter|Dar|3.36.0
Lua|key|0.0.9
awesome-flutter-snippets|Nas|3.0.3
flutter-riverpod-snippets|rob|1.1.0
cs-poco-to-dart|thi|0.0.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvid2:30447481
pynewfile477:30463512

```

</details>

**Comment by DanTup** [comment]
Some additional info in case others hit this (or see it with other extensions), the cause was that the latest VS Code shipped with an updated electron/node which terminates the process on any unhandled promise (as it's been threatening to do for some time), and there's a bug in the Dart DA that could have unhandled rejected promises if you had breakpoints set and your app spawned additional isolates (threads).
