### ISSUE TITLE
Timeline (Local History) - It should not create a new local history entry if the file has no changes after a file save action has been performed

### ISSUE THREAD

**Issue by tommai78101** [microsoft/vscode#146461]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.66
- OS Version: Windows 11 Pro 64-bit Version 21H2 Build 22000.556

Steps to Reproduce:

1. Create a new text file.
2. Save the blank text file to a temporary location.
3. Type "Hello world".
4. Save the text file. A local history will be created.
5. Add a newline and type "Goodbye" after "Hello world".
6. Save the text file. A new local history will be created.
7. Peek at the first local history. You will notice both "Hello world" and "Goodbye" will appear.
8. Peek at the second local history. You will notice there are no differences shown.

Either when the file save action is done, it should not create a new local history.
Or, there might be an error where it's putting the most recent changes in the previous local history.

**Comment by tommai78101** [comment]
First local history:

![image](https://user-images.githubusercontent.com/6444116/161129747-39c27465-bd38-446a-9491-28aeb3f1e2a4.png)

It is expected that the first sentence, "Hello world.", is highlighted, and "asd" should not appear. However, both "Hello world." and "asd" are both highlighted, which is wrong.

Second local history:

![image](https://user-images.githubusercontent.com/6444116/161129796-b641c594-3d9c-4615-b7c5-7b4f803403a6.png)

It is expected "asd" should be highlighted, but nothing is highlighted.

In my opinion, I'm expected the Local History to preserve changes in between the previous file save action and the current file save action.

**Comment by bpasero** [comment]
The way it works is intentional.

/duplicate https://github.com/microsoft/vscode/issues/145706

**Comment by tommai78101** [comment]
You have to really go and click on a lot of links just to get to this answer:

> The top entry always matches the version on disk, so you don't see any change.

This explains why the first local history always show no changes. That's all I wanted to know on why there's this discrepancy. Maybe, to us, it's a discrepancy, I guess.
