### ISSUE TITLE
edge debugger no longer works

### ISSUE THREAD

**Issue by leelhn2345** [microsoft/vscode#146410]
Issue Type: <b>Bug</b>

prior to the update, this setting works. 
but after the update, it no longer works.

```json
        {
            "name": "frontend",
            "port": 9222,
            "request": "attach",
            "type": "pwa-msedge",
            "webRoot": "${workspaceFolder}/frontend",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "url": "http://localhost:3000",
        },
```

i've downloaded the previous version to test it out, and it works. 
this bug is only from this version.

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 4900HS with Radeon Graphics          (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|39.42GB (21.85GB free)|
|Process Argv|--crash-reporter-id 02915e01-829c-4992-b28f-82fece3a3a70|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 4900HS with Radeon Graphics (16 x 2994)|
|Memory (System)|19.25GB (16.38GB free)|
|VM|0%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
c-cpp-makefile-project|adr|1.1.0
es7-react-js-snippets|dsz|4.4.3
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
remotehub|Git|0.28.0
fluent-icons|mig|0.0.17
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.20
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.231.0
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.78.0
remote-wsl|ms-|0.66.0
remote-repositories|ms-|0.4.0
debugger-for-edge|msj|1.0.15
material-icon-theme|PKi|4.15.0
rewrap|stk|1.16.3
highlight-matching-tag|vin|0.10.1
JavaScriptSnippets|xab|1.8.0
toml|be5|0.6.0
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
vscode-markdownlint|Dav|0.46.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
gitlens|eam|12.0.5
vscode-html-css|ecm|1.11.0
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.5.0
code-runner|for|0.11.7
vscode-pull-request-github|Git|0.40.0
gc-excelviewer|Gra|4.2.54
todo-tree|Gru|0.0.215
vscode-test-explorer|hbe|2.21.1
latex-workshop|Jam|8.23.0
vsc-python-indent|Kev|1.15.0
vscode-python-test-adapter|lit|0.7.0
rust-analyzer|mat|0.2.993
vscode-docker|ms-|1.21.0
python|ms-|2022.4.0
vscode-pylance|ms-|2022.3.4
jupyter|ms-|2022.3.1000901801
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.9.7
test-adapter-converter|ms-|0.1.5
vsliveshare|ms-|1.0.5449
color-highlight|nau|2.5.0
autodocstring|njp|0.6.1
indent-rainbow|ode|8.2.2
vscode-css-peek|pra|4.2.0
prisma|Pri|3.11.0
vscode-yaml|red|1.6.0
crates|ser|0.5.10
vscode-rustfmt|sta|0.1.2
vscode-lldb|vad|1.7.0
vscodeintellicode|Vis|1.2.17
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details>

**Comment by leelhn2345** [comment]
> Ok, thanks for the details. Can you let me know what command you're using to launch Edge when you try to attach to it?

i used desktop shortcut to launch edge. I've included the flag `--remote-debugging-port=9222` in the target properties.

**Comment by connor4312** [comment]
We recommend using a separate `--user-data-dir` when launching a browser in debug mode, since otherwise if a browser is already running the `--remote-debugging-port` will not be applied.

Additionally, if you don't use a --user-data-dir on Edge, you may have also have interference with startup boost https://github.com/microsoft/vscode-js-debug/issues/1189. In the future, Edge will add a CLI warning when this happens.

**Comment by leelhn2345** [comment]
on vscode 1.66, i've tested with startup boost on/off, and added `--remote-debugging-port=9222 --user-data-dir=<directory>`. But it still doesnt work as intended -  no `console.log` in debug console, break points don't work.

when i rolled back to vscode 1.65, with startup boost on, and started MS-Edge with just `--remote-debugging-port=9222` , the debugger works as expected. 

i truly think this issue is from the latest vscode release.

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-js-debug-companion/commit/35fc25a533b0afd367d3608562e649ea2963233c. This'll be in the [Insiders build](https://code.visualstudio.com/insiders/) later this week (Wednesday/Thursday)
