### ISSUE TITLE
Wrong usage of fs.utimes

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#14645]
@bpasero Node's documentation says

> The value should be a Unix timestamp in seconds. For example, Date.now() returns milliseconds, so it should be divided by 1000 before passing it in.

You seem to [not be doing that](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L327), which could explain the `EPERM`.

Furthermore, [pfs.utimes](https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/pfs.ts#L104) parameters should be `number`, not `Date`.

**Comment by Tyriar** [comment]
Verified by code review
