### ISSUE TITLE
command decorations overlaid on reload of window after running a command

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#146426]
<img width="334" alt="Screen Shot 2022-03-31 at 8 02 16 AM" src="https://user-images.githubusercontent.com/29464607/161050369-5e95dfc6-c2ec-4f21-a679-1e8f491eadb2.png">

**Comment by Tyriar** [comment]
Similar to https://github.com/microsoft/vscode/issues/144597, that isn't on reload though.

**Comment by meganrogge** [comment]
doesn't repro at least on Mac anymore.
