### ISSUE TITLE
Activity bar border not displayed on vscode.dev on Safari

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#146466]
Looks like `activityBar.border` is not displayed on vscode.dev when using Safari. Noticed this on Insiders when testing the new light HC theme.

## Safari
<img width="117" alt="CleanShot 2022-02-22 at 11 11 32@2x" src="https://user-images.githubusercontent.com/25163139/155202352-bfbda4c7-2014-4969-9929-4ac75950045b.png">

## Edge
<img width="108" alt="CleanShot 2022-02-22 at 11 15 23@2x" src="https://user-images.githubusercontent.com/25163139/155202825-5e1a20b6-9166-4052-b34b-c06b9a00ee42.png">

**Comment by sbatten** [comment]
this is fixed now
