### ISSUE TITLE
Ignoring configured affinity for 'pub.name' because the extension is unknown or cannot execute

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#146412]
This message always shows because the setting `extensions.experimental.affinity` is defined incorrectly at https://github.com/microsoft/vscode/blob/8864c16a1a60d0868e5d8c4dc0aceaa1627be009/src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts#L217-L219

Other than an info log statement, there are no bad side-effects.

fyi @joaomoreno

**Comment by rzhao271** [comment]
What are some verification steps for this issue?

**Comment by bpasero** [comment]
Not seeing related log message anymore.
