### ISSUE TITLE
Repl cursor at position 0 is cropped

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#14647]
Notice how the top-left corner of the cursor is cropped by a single pixel:

![image](https://cloud.githubusercontent.com/assets/22350/19799658/195a210c-9cf8-11e6-86ac-8f6f3e2c48f4.png)
 
This might be the _hidden_ text area.

**Comment by isidorn** [comment]
Thanks for the tip that it is the hidden text area, though dup of https://github.com/Microsoft/vscode/issues/13067
