### ISSUE TITLE
Tips for git modification

### ISSUE THREAD

**Issue by YuanzheTian** [microsoft/vscode#146487]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- 
![image](https://user-images.githubusercontent.com/44792821/161183004-d38bc645-0713-4c88-8005-6b49dd68fffa.png)

this is git plugin version
![image](https://user-images.githubusercontent.com/44792821/161183068-29d3dca1-8153-43a9-a3d6-5c2eaa6b5861.png)

- OS Version:
- Windows platform

Steps to Reproduce:

I don't know if this is a bug.
When I insert, delete and modify code, there will be different prompts.
But when I insert, delete or modify two operations in two consecutive lines.There is only one hint

Modify code, Insert code, Delete code. Not consecutive lines
![image](https://user-images.githubusercontent.com/44792821/161183318-d4fce42e-f1c6-41ef-8341-730cd21e1c61.png)

Continuous modification and addition
![image](https://user-images.githubusercontent.com/44792821/161183417-c5d66f98-7eca-4f1e-896a-45acc657172f.png)

Continuous modification and delete.
![image](https://user-images.githubusercontent.com/44792821/161183548-ee2cca45-a1d4-4ab2-ad32-bbf9794f692e.png)

Any continuous modification, deletion or addition will be considered as modification.

1.
2.

**Comment by IllusionMH** [comment]
You shouldn't report issues with Gitlens in this repo, not sure why that screenshot necessary. Ideally reports should be with all extensions disabled.

This is expected behavior. Try to check `git diff` in CLI

removed lines (`-`) - red triangle, added lines (`+`) - green line, modified lines (consecutive set of `+` and `-` lines without unchanged lines between) - blue line.

**Comment by YuanzheTian** [comment]
Git extensions have been disabled.
![image](https://user-images.githubusercontent.com/44792821/161257990-0c2a55f5-d481-439d-9611-c51c897bc6a5.png)
When these three modifications are not together, It looks right

![image](https://user-images.githubusercontent.com/44792821/161258382-014919f4-4db7-4fd2-9aa6-cefba6666992.png)
However, when deletion and modification are combined, only the modified blue flag will be displayed

I don't know if it's a bug or if it's designed like that.

**Comment by IllusionMH** [comment]
It's usual design for diff decorations.
Even single line modification is combination of deletion and addition. Therefore any continues combinations of deletions followed by additions is treated as modified part of content.

Additions/deletions that are separated by unmodified lines can be treated and are treated as separate additions/deletions with corresponding decorations.
