### ISSUE TITLE
update to 1.66 doesn't allow user to type input on devcontainer initializeCommand

### ISSUE THREAD

**Issue by ewhitesides** [microsoft/vscode#146429]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66
- OS Version: WSL2, also see this issue on Mac

Steps to Reproduce:
i have a devcontainer that runs a shell script on initializeCommand parameter.  the script would prompt the user to enter some credentials, and in 1.65, this worked fine, but in 1.66 it seems the user is not able to type in any input into the terminal during this phase.

**Comment by ewhitesides** [comment]
studying the issue some more, it looks like initializeCommand isn't getting "pushed" into a new interactive terminal window like it used to. it stays just in the devcontainer logging terminal window and hangs.

if i move the commands to postAttachCommand, it gets "pushed" into the interactive terminal window.

**Comment by akutruff** [comment]
The execution path seems to be different as well.  

`	"postCreateCommand": "bash .devcontainer/post-create-command.sh" `

now yields this error:

`postCreateCommand failed with exit code 127. Skipping any further user-provided commands.`

**Comment by chrmarti** [comment]
Fixed in v0.231.3 and v0.232.3-pre-release.

@akutruff Do you still see this in the latest version? If so: Could you open a new issue with your devcontainer.json included?
