### ISSUE TITLE
Integrated terminal text black on black baground

### ISSUE THREAD

**Issue by bonjourjoel** [microsoft/vscode#146506]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version:
**Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044**

- OS Version:
**Windows 10 Home**

- Steps to Reproduce:

1. I have an automatic compiling task:
`
        {
            "label": "compile ts app ; ~ compile ts WATCH @server",
            "type": "shell",
            "command": "node",
            "args": [
                "app-dev-utils/bin/app-dev-utils/src/vsc-task-run/VscTaskRun.js",
                "~ compile ts WATCH @server",
                "tsc-watch --noClear -p app-src/.compilets/tsconfig-server-app.json",
            ],
            "problemMatcher": ["$tsc-watch"],
            "isBackground": true,
            "runOptions": {
                "runOn": "folderOpen",
            }
        },
`
2. Since a rencent update of vscode, the text that was previously showing in white, now shows in black, thus making it almost invisible. I haven't changed any setting since the update causing this. I am not using themes or any color customization. I am using a MS-DOS terminal and these are my terminal settings:
`		"terminal.integrated.automationProfile.windows": {
			"path": "C:/Windows/system32/cmd.exe"
		},
		"terminal.integrated.defaultProfile.windows": "Command Prompt",
		"terminal.integrated.gpuAcceleration": "canvas",
`
I have tried to change gpuAcceleration to all the possible values and it doesn't change anything about the color. I have this setting because it's a workaround for another vs code bug mentionned in another unrelated issue.

3. This is a screenshot of the bug:
![bug-color-terminal](https://user-images.githubusercontent.com/78134277/161213280-e7ac2fa6-1503-413c-9bcd-0d1249a12b4d.png)
I outlined the black text, barely visible, because it's black on a black background. Again I left all the themes options by default.

**Comment by Tyriar** [comment]
@bonjourjoel do you know how I can reproduce that line starting with `TSFILE:`? I tried in cmd and pwwsh and it works just like tsc, don't think I've ever seen tsc output `TSFILE: ...`:

![image](https://user-images.githubusercontent.com/2193314/161239676-d8ff31bf-f820-4bad-a768-d5e65fbc5b22.png)

The main change we made in this area was to change the default value of terminal.integrated.minimumContrastRatio from 1 to 4.5, reverting this in settings may workaround your issue.

**Comment by bonjourjoel** [comment]
I realized based on your comment that it's not a vscode bug, but a 3rd party lib called "tsc-watch" that made an update causing this. Sorry for the mistake. Regards.
