### ISSUE TITLE
Find all usages of a props in React

### ISSUE THREAD

**Issue by nvmnghia** [microsoft/vscode#146530]
I want to find all usage of a props of a component in React. For example, I have a `<CustomComponent>` that takes a lot of optional props, and want to know where the (optional) props is used/passed.

**Comment by mjbvz** [comment]
Please share an example  project with steps to follow that demonstrates the issue

**Comment by nvmnghia** [comment]
Hi, this is a feature request. For example, I have this component:

```js
const Component = (props) => {
  const {optionalA, optionalB} = props;

  if (optionalA !== undefined) // do something

  return ...
}
```

Now if I use `Find References` on `optionalA`, I want it to also show these:

```js
<Component optionalA>
```

but not these:

```js
<Component /* optionalA not used */ >
```

**Comment by mjbvz** [comment]
This is already supported if you add JSDoc type annotations to `props` (notice how the inferred type is `any` without them, meaning we don't understand the shape of the types being used):

```js
/**
 * @param {{
 *  optionalA: string | undefined,
 *  optionalB: string | undefined
 * }} props 
 */
const Component = (props) => {
    const { optionalA, optionalB } = props;
...
}
```
