### ISSUE TITLE
Call out contributors by name

### ISSUE THREAD

**Issue by jwulf** [Microsoft/vscode#1465]
Hi, thanks for all the work for the December release!

In the release notes a number of new features are called out as thanks to "a community contribution". It would be cool to call out the contributors by name. For example:

Thanks to @akamud , there is now a `Show Outdated Extensions` command that shows all outdated extensions and lets you quickly install their updates.

**Comment by egamma** [comment]
CC @chrisdias 

@jwulf I'm responsible for this and I'm happy to change this, but here is my reasoning... 
A pull request is almost always a collaboration between a contributor and a core team member, sometimes another community member chimes in. I found it strange to only give credits to the initiator of the PR but not the team member and others that contributed to the PR until it got merged. Enumerating all contributors to the PR is strange as well. For this reason I decided to only include the link to the Pull Request. In this way seeing the collaboration on the PR is only a click away.

Does this reasoning make sense to you?

Another idea was to have a page with all the contributors on the web site.

**Comment by jwulf** [comment]
I guess the simple thing is that "what gets recognised gets repeated". 

So you can reward contributions with recognition and it's an easy and infinite currency for you to spend on building the community. :-)

Here's an example from a Red Hat security update: https://rhn.redhat.com/errata/RHSA-2015-1539.html

The original issue trackers are still restricted under the security embargo, but I'd wager that David Jorm raised the issue, and it got addressed by a combination of people from there. And Red Hat want their user community to engage with them around security issues they discover, so they use recognition to drive that.

**Comment by jwulf** [comment]
So one possibility would look like: 

"Thanks to a request by @akamud, there is now...."

"Thanks to an idea from @akamud, there is now..."

"Thanks to a contribution from @akamud, there is now...."

"Thanks to a suggestion from @akamud, and code contributions from X and Y, there is now...."

It's about recognising the behaviours that you want repeated in a visible way. People will get ideas from seeing that...

**Comment by egamma** [comment]
>I guess the simple thing is that "what gets recognised gets repeated". 

I like this and we will definitely work on improving the recognition with our next update, thanks much for your feedback.

**Comment by jwulf** [comment]
You're welcome! :-)

**Comment by egamma** [comment]
Closing - the january release notes recognize PRs.
