### ISSUE TITLE
Flush local history before shutdown when connected to a remote

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#146554]
Because the remote connection can drop at any time, it is somewhat dangerous to flush local history only on shutdown.

Refs: https://github.com/github/codespaces/issues/7228

**Comment by bpasero** [comment]
@jkeech can you verify this using insiders with Codespaces? Thanks!

**Comment by bpasero** [comment]
**Verification:**
* open timeline for a file
* save the file and notice a local history entry
* edit the entry, give it a different name
* disconnect from the remote
* connect again and ensure the history entry name is still there

**Comment by jkeech** [comment]
Verified on Insiders in Codespaces. Thanks for the fix! ❤️
