### ISSUE TITLE
Multiline comments 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#146510]
The comments widget currently only allows commenting on a single line. For some use-cases of comments, such as code review comments, commenting on a range is not only beneficial, it's already supported by the underlying tooling (see GitHub pull requests for example). We should support a way to comment on a range. This support will require:

- API that allows comments to be made on a range
- UX that indicates commenting on a range is possible
- UX that shows that an existing comment is on a range 
  - In the editor for the comments widget
  - In the Comments view

**Comment by alexr00** [comment]
@rebornix FYI since I think you also want this in notebooks and @laurentlb since I know you were interested in this.

**Comment by alexr00** [comment]
@rebornix yes, the API does currently support this! I was just outlining all the parts.

**Comment by alexr00** [comment]
First pass at UX for leaving a comment on a range and indicating that an existing comment is on a range:

![Recording 2022-04-12 at 14 49 14](https://user-images.githubusercontent.com/38270282/162966221-edfe9bbe-9d90-4bae-b244-00c8f3e43c5e.gif)

**Comment by IllusionMH** [comment]
Looks great!

Is it possible to add explicit lines range to the header of comment as it is in GH with "Commenting on lines 63 to 66" as well?
For example: "Start discussion on lines 15 to 20" or "Start discussion (lines 15-20)" in your example

**Comment by alexr00** [comment]
> Is it possible to add explicit lines range to the header of comment...

I do want to add this information somewhere, but the content of the header/title of the comment thread is owned by the extension that provides the comment. I will try adding the range info somewhere else in the comments widget.

**Comment by alexr00** [comment]
I've tried out adding line numbers in the comment thread title area, but I haven't found a place that I like it. 
Example right aligned:
![image](https://user-images.githubusercontent.com/38270282/164475467-32546d00-b680-4b45-8974-a063fa56552f.png)
Example left aligned:
![image](https://user-images.githubusercontent.com/38270282/164475543-83f78a77-7d71-4731-acf7-3ed5f7a0c69d.png)

Since the extension controls the contents of the title, all we can do is append it in there, and it just ends up looking out of place. Individual extension can of course put the line numbers in their in an integrated way themselves. The rest of the widget is comment node focused, not comment thread focused, so it doesn't belong there either. 

Happy to have suggestions for where else to put it, but for now I will leave it out since the editor decoration already provides this info.

**Comment by IllusionMH** [comment]
@alexr00 is it possible to extend comment block at the top for multiline comments as GH does? So it will be part of thread and displayed above extension controlled title 
![image](https://user-images.githubusercontent.com/1312662/164485229-a37bc018-89e8-4bc8-ae5a-4f3dbf73e82b.png)

**Comment by alexr00** [comment]
@brianjmurrell this does indeed open the door for the suggestion feature: https://github.com/microsoft/vscode-pull-request-github/issues/603

**Comment by brianjmurrell** [comment]
@alexr00 Ha!  That's the one, and yes, I am subscribed to it already.  Too bad GitHub's tool to find all of your subscriptions is not listing anything from this repo.

Thanks for the pointer!

**Comment by brianjmurrell** [comment]
Hrm.  This does not seem to be working for me.  I try to click and drag but I just get a plus-sign that moves with my mouse cursor, no multi-line selecting for comment.

**Comment by alexr00** [comment]
Clicking and dragging on the + is not currently supported. Instead you make a text selection then click the +: https://github.com/microsoft/vscode/issues/148214

**Comment by brianjmurrell** [comment]
Ahhh.  I see.  Thanks @alexr00!

**Comment by noalbalint** [comment]
hey @alexr00 thanks for implementing this, works really well!

just noticed one UX issue: when the comment is collapsed, it still shows the background and border on the code... fairly unpleasant to look at 😬 

<img width="1470" alt="Screen Shot 2022-05-24 at 10 15 13 AM" src="https://user-images.githubusercontent.com/45208632/170095723-3bab4ba3-e0d9-47e4-bd70-39f0cee806a7.png">

ideally, that styling should only display if the comment is expanded, right? :)

**Comment by alexr00** [comment]
I intentionally left the background and border when the comment is collapsed so that there was a strong indication that the comment is there and it's how other code review tools I've used in the past have worked. 

However, this is your code editor too and not just a code review tool. If there's lots of feedback that this is undesirable then we can change it. I could also have a separate theme color for when the comment is collapsed so that you could essentially hide the background and border in this case.

**Comment by laurentlb** [comment]
I suspect it can be annoying to have the region always highlighted, in particular when the comment is resolved.

I don't have data or user feedback yet, I can share it in the future.
cc @albertelo

**Comment by hermannloose** [comment]
I find the highlight distracting even with the comment card open. I would prefer a setting for the highlight to only show up when the comment card is moused over or focused.

**Comment by alexr00** [comment]
Just FYI, https://github.com/microsoft/vscode/issues/152067 will hide the range highlight when the thread is collapsed.
