### ISSUE TITLE
Electron smoke test failures on linux with ECONNREFUSED

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#146535]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=164480&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=f434ff82-bf7d-5375-d19c-a40b1bd2e1c5
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=164491&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=d61c32fd-93f0-5126-b44d-dcf4920dede7
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=164499&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=d61c32fd-93f0-5126-b44d-dcf4920dede7
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=164587&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=f434ff82-bf7d-5375-d19c-a40b1bd2e1c5
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=164578&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=f434ff82-bf7d-5375-d19c-a40b1bd2e1c5
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=164552&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=f434ff82-bf7d-5375-d19c-a40b1bd2e1c5

First started in this commit range https://github.com/Microsoft/vscode/compare/95e8eca...6dde517

We do have an electron update in this range https://github.com/electron/electron/releases/tag/v17.3.0 but there is nothing linux specific that should have affected. Needs investigation.

**Comment by bpasero** [comment]
I can take it from here and drag you in as needed.

**Comment by bpasero** [comment]
Pushed a change to switch over to `playwright` for Electron smoke tests which should solve this.
