### ISSUE TITLE
Allow extension developers to update the mouse cursor/pointer

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode#146593]
It would be nice if extension developers could update the mouse pointer, or cursor, during long-running actions, like if a compilation is occurring, for example.

It would be really, really nice if we could add a subscript to that cursor on completion that reflects whether the long-running action, compilation in this case, completed successfully, like with a checkmark, or if the long-running action failed, with a temporary red `x` indicating failure as a subscript on the cursor.

What are other people's thoughts on this?

**Comment by mjbvz** [comment]
Giving extensions direct control over the cursor goes against VS Code's api philosophy: https://code.visualstudio.com/api/extension-capabilities/overview

Instead please open feature requests for individual cases you'd like to see supported. For a long running operation for example, typically extensions would hand VS Code a long running task and then we would figure out how to present process status to the user. That way it's consistent across extensions and languages

**Comment by hamirmahal** [comment]
Hmm... I'm not sure if I understand correctly. How far is #146594 from what a feature request should look like?
