### ISSUE TITLE
Debugging into function goes to a different place

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#146512]
[Recording 2022-04-01 at 10.19.11.gif.zip](https://github.com/microsoft/vscode/files/8395914/Recording.2022-04-01.at.10.19.11.gif.zip)

**Comment by bpasero** [comment]
**Steps:**
* debug test `encoding updates with language based configuration`
* add breakpoint into [this line](https://github.com/microsoft/vscode/blob/eeb9632e749e2322b86bde5378c3b89d1f9b4e31/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L1076)
* debug test
* try to step into `await this.forceResolveFromFile();`

**Comment by connor4312** [comment]
This is a bug in Chrome, which is surprisingly easy to reproduce. It's probably already opened, but I could not find an issue on their tracker, so I made a new one: https://bugs.chromium.org/p/chromium/issues/detail?id=1319019
