### ISSUE TITLE
Intermittent remote integration test failures with code: 1006

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#146532]
Runs:
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=164342&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=636c104c-b909-5cac-59f5-95c1f9c594ad
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=164106&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=636c104c-b909-5cac-59f5-95c1f9c594ad

```
[main 2022-03-31T01:28:05.527Z] Waiting for extension host with pid 22406 to exit.
[remote-connection][Management   ][12b01…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
An unknown error occurred. Please consult the log for more details.
[remote-connection][Management   ][12b01…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[main 2022-03-31T01:28:05.621Z] Extension host with pid 22406 exited with code: 0, signal: null.
The STDIO streams did not close within 10 seconds of the exit event from process '/bin/bash'. This may indicate a child process inherited the STDIO streams and has not yet exited.
##[error]The task has timed out.
```

**Comment by joaomoreno** [comment]
Is this the same? https://dev.azure.com/monacotools/Monaco/_build/results?buildId=167148&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=636c104c-b909-5cac-59f5-95c1f9c594ad

**Comment by alexdima** [comment]
The code 1006 just means that the WebSocket connection got broken, it is a symptom and not a cause. Given our recent green build streak, I will optimistically close this.
