### ISSUE TITLE
Terminal find widget always reveals find result into view

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#146591]
Issue Type: <b>Bug</b>

* Open a terminal
* Run a few commands to fill more than one viewport
* Search text which exists at the top of the buffer
* Scroll to the bottom
* Type

The find widget always reveals to the very top instead of sticking to the last line of the buffer

VS Code version: Code - Insiders 1.67.0-insider (Universal) (8b7086afdbfd42bf6e7b8c0bb586530bf7cf1396, 2022-04-01T05:16:51.251Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (1.11GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --enable-proposed-api donjayamanne.jupyterpowertools --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api rchiodo.jupyter-tools --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (75)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.1
github-markdown-preview|bie|0.2.0
markdown-emoji|bie|0.2.1
markdown-footnotes|bie|0.0.7
markdown-preview-github-styles|bie|1.0.1
vscode-eslint|dba|2.2.2
kusto|don|0.3.8
gitlens|eam|12.0.5
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.5.0
codespaces|Git|1.5.7
copilot|Git|1.11.5453
remotehub|Git|0.28.0
vscode-pull-request-github|Git|0.41.2022033109
vscode-drawio|hed|1.6.4
handydandy-notebook|jak|0.1.0
github-graphql-nb|joy|0.0.8
fluent-icons|mig|0.0.17
vscode-fluent-icons|mig|0.0.1
theme-monokai-pro-vscode|mon|1.1.20
vscode-azurefunctions|ms-|1.6.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestaticwebapps|ms-|0.10.0
vscode-docker|ms-|1.21.0
vscode-language-pack-zh-hans|MS-|1.66.1
python|ms-|2022.3.1931132634-dev
vscode-pylance|ms-|2022.3.5-pre.1
jupyter|ms-|2022.4.1000912146
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
notebook-renderers|ms-|0.0.1
remote-containers|ms-|0.232.2
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.78.0
azure-account|ms-|0.10.1
azure-repos|ms-|0.8.0
hexeditor|ms-|1.9.5
js-debug-nightly|ms-|2022.3.2817
powershell-preview|ms-|2022.3.1
remote-repositories|ms-|0.4.0
remotehub-insiders|ms-|2021.6.302
vscode-github-issue-notebooks|ms-|0.0.116
vscode-js-profile-flame|ms-|1.0.0
vscode-markdown-notebook|ms-|0.0.26
vscode-notebook-history|ms-|0.0.1
vscode-selfhost-test-provider|ms-|0.3.9
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.1.0-dev
debugger-for-chrome|msj|4.13.0
vetur|oct|0.35.0
excalidraw-editor|pom|2.0.9
geo-data-viewer|Ran|2.5.0
jupyter-tools|rch|0.0.1
better-jupyter-errors|reb|0.0.1
toggle|reb|0.0.2
typing-practice|reb|0.0.1
vscode-code-renderer|reb|0.0.2
java|red|1.4.0
kuskus-extensions-pack|ros|1.0.10
kuskus-kusto-language-server|ros|1.0.23
kuskus-kusto-syntax-highlighting|ros|1.1.20
vsc-nwjs|rua|1.0.18
rust|rus|0.7.8
rest-book|tan|6.0.1
tldraw-vscode|tld|1.8.4
luna-paint|Tyr|0.13.2
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.7.0
vscode-java-debug|vsc|0.40.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.2
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
notebook-editing|vsc|1.0.0
vscode-test-resolver|vsc|0.0.1

(6 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
https://user-images.githubusercontent.com/876920/161598532-@meganrogge  59-2fe9-440f-8c0c-9afd78f4775d.mov

@meganPlease see above screen recording

**Comment by meganrogge** [comment]
@rebornix thanks for the gif. we scroll to the match when it's not in the viewport by design. Is that what you mean?

**Comment by rzhao271** [comment]
I just encountered the same issue. The power of the terminal to locate the match is too powerful&mdash;I'm unable to see what I'm typing clearly.
![Screencap showing the terminal constantly scrolling back to the find result](https://user-images.githubusercontent.com/7199958/161605192-d3b96abb-ec1b-4131-a164-a72716bfb996.gif)

**Comment by meganrogge** [comment]
What's going on there @rzhao271 ? how are you keeping the find widget focused while typing 🤔

**Comment by rzhao271** [comment]
Another screencap on Windows 10. This time, I searched for something first, then closed the find widget, scrolled down, and reopened the find widget. I then try manually scrolling down and typing more.
![Screencap](https://user-images.githubusercontent.com/7199958/161608277-f8123d60-f524-4073-abd8-b297fb59990e.gif)

**Comment by rebornix** [comment]
@meganrogge may I ask why the original issue is not a `bug`? When the focus is not in the find widget, typing in the last line of the terminal should not scroll automatically, right?

**Comment by meganrogge** [comment]
Fixed already once there's a new build released

**Comment by meganrogge** [comment]
Don't recall why I removed that at the time, but yes it is a bug. @rebornix

**Comment by meganrogge** [comment]
This is fixed
