### ISSUE TITLE
CRITICAL:  New Github Online VScode using too much CPU !!!!

### ISSUE THREAD

**Issue by arita37** [microsoft/vscode#146597]
ADD ISSUE DESCRIPTION HERE

Latest version make the CPU usage too high....

Please revert to previous versions.

Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
Embedder: github.dev

**Comment by sidcha** [comment]
I can confirm this behaviour on Chrome, running on a M1 MacBook Pro (MacOS Monterey 12.3). The CPU usage of the chrome Helper is constantly above 100% when the tab is in foreground.

<img width="592" alt="Screenshot 2022-04-02 at 10 34 19" src="https://user-images.githubusercontent.com/2995609/161367365-15c7fc8f-af50-4eca-a8e2-a79a567dc1d7.png">
Note: The first peak was when the tab was in foreground and second peak was when it was in background.

**Comment by sidcha** [comment]
@arita37, I suggest changing the title to "Github Online VScode using too much **CPU**" for better visibility.

**Comment by arita37** [comment]
Thanks, new releas just killed VScode web...

**Comment by lszomoru** [comment]
@arita37, are you able to reproduce this on a public repository? If so, could you please share the link so that we try to reproduce and collect additional information? Also, I was wondering if you are able to reproduce the same problem using https://vscode.dev or https://insiders.vscode.dev?
