### ISSUE TITLE
Accessibility: Larger click zones for easier panel resizing.

### ISSUE THREAD

**Issue by bean5** [microsoft/vscode#146558]
Shaky hands make it hard to click and resize panels. Sometimes I use my keyboard to move the mouse. Although more stable, the smallest incremental movement often passes right over a click target for resizing a panel. This means that in order to click a target, I need to pass over, keep going, then double back. It is strange, but not surprising. I could make my mouse move less, but then I have to click 'twice' as much to move long distances.

I looked for duplicates and did not see this request.

**Comment by isidorn** [comment]
@bean5 thanks for your feedback.
In order to make it possible to change the view size without the mouse we have the commands "Increase Current View Size" and "Decrease Current View Size". I suggest you assign a keyboard shortcut to them and try them out. It should work nicely I think. Let us know!

**Comment by isidorn** [comment]
Closing this issue as there is a workaround as I have described in my previous comment. Thanks!
