### ISSUE TITLE
Unit test failure with SQLite Storage Library

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#146536]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=164517&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=821d316a-2fa3-581f-c34c-57a961b8e328

```
  1) SQLite Storage Library
       "after each" hook for "basics (open multiple times)":

      Error: EBUSY: resource busy or locked, unlink 'C:\Users\CLOUDT~1\AppData\Local\Temp\vsctests\storagelibrary\epCHJ2Uf\storage.db'
      + expected - actual
```

FYI, there was only this run that the failure.

**Comment by bpasero** [comment]
Funky, I thought I had reverted my change to test `VACUUM` support sufficiently enough to not see issues like this one, but maybe we are onto something and `VACUUM` was totally unrelated...

**Comment by bpasero** [comment]
I checked and nothing changed in the storage lib, it also does not fail lately anymore, will close and watch for future issues in case this happens again. I hope it is not an issue stemming from the node.js update in Electron 17 🤞
