### ISSUE TITLE
Inline suggestions shouldn't appear when moving cursor

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#146529]
This might be a duplicate of https://github.com/microsoft/vscode/issues/146524 , but it appears to be slightly different

https://github.com/microsoft/vscode/blob/4fcd6376131a484046ce91b663ab19249c668ecc/src/vs/editor/contrib/linesOperations/test/browser/moveLinesCommand.test.ts#L384

```
Version: 1.67.0-insider
Commit: 909602cf04e0fa42528d692676d0d4e15e67bba2
```

* duplicate line up
* delete `Configuration` from the identifier
* do arrow right to move to the type
* observe that inline suggestions show after doing arrow right, which is unexpected for me
* moving to the line below and back again up doesn't show the inline completion, as expected

https://user-images.githubusercontent.com/5047891/161246860-39641ac4-67e1-412c-b659-95654c2c7da2.mp4

**Comment by alexdima** [comment]
Here's a slight variation, where inline suggestions show on double click after a deletion in an unrelated word on the line:

* delete `Configuration`
* double click on `languageService`

https://user-images.githubusercontent.com/5047891/161247433-267f1369-570c-4b2a-8d45-6f1ceaac01d5.mp4

**Comment by hediet** [comment]
Currently, an inline completion session is started for a single but whole line.
If you edit something in that line, it gets triggered. If you move the cursor in that line, the provider is asked again.
That causes the observed behavior.

Should the inline completion session be canceled on cursor change events?

**Comment by jrieken** [comment]
fyi @bpasero

**Comment by alexdima** [comment]
This was causing unit test failures, so I reverted it via https://github.com/microsoft/vscode/commit/e2b873e1af23a412f85a82998cf7d2a007a82238
