### ISSUE TITLE
Adding backward debugging

### ISSUE THREAD

**Issue by lohraspco** [microsoft/vscode#146592]
Hi, 
I would like to suggest some features for debugging. 
**The ability to go backward while debugging:** Assume that we are debugging a code (e.g., code below) and a breakpoint or  line by line debugging took us to line 6. Now if we want to try or check something at line 5 we need to run the debugging from the beginning. If we have the ability to go backward during the debugging that would be time saving. 
```
1 import pandas as pd
2
3 ds = pd.Series([1,2,3], index=[1,2,3])
4 df = ds.to_frame("test")
5 df = df * 2 
6 df = df + 3
7
8 
```

Another feature is to change the code while debugging. I am not sure that we can have that capability. But if we for example are at a breakpoint in line 6 and we wan to change that line from `df = df + 3` to `df = df + 4` then we have to run the code again. It will be nice if we can change the code and see the results in the code (it can be done using debug console, but it is a little bit work to test there and then change the code)

**Comment by gjsjohnmurray** [comment]
/extPython

All debugging in VS Code is provided by extensions.

**Comment by weinand** [comment]
VS Code's generic debugger UI already supports "backward debugging". But the debugger specific implementation must come from the debug extension.
