### ISSUE TITLE
Unable to uninstall this extension

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14654]
Steps to Reproduce:

1. install this extension: https://marketplace.visualstudio.com/items?itemName=wk-j.screen-recorder
2. restart and notice the thing in the status bar
3. try to uninstall

Uninstall never finishes...

![image](https://cloud.githubusercontent.com/assets/900690/19803965/cc393fb6-9d0b-11e6-8dc1-bf6f4b11304f.png)

**Comment by sandy081** [comment]
@bpasero It works for me and uninstall happens with uninstalling changes to reload + install option. 
- Have you done any specific steps to get into this state?
- Does the uninstall happened and it still shows Uninstalling?

**Comment by bpasero** [comment]
@sandy081 yes it shows "Uninstalling". The only thing I did once was to click the status bar icon to try the extension.

**Comment by bpasero** [comment]
Cannot reproduce anymore :-(

**Comment by sandy081** [comment]
Me neither. Tried uninstalling it when the record is running and it works.

I will close it and lets reopen it when we see it again.
