### ISSUE TITLE
MacOS & Invert Colors do not play nicely with updated version (1.66.0)

### ISSUE THREAD

**Issue by ludwick** [microsoft/vscode#146579]
Does this issue occur when all extensions are disabled?: Yes/No

About dialog copy:

Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:04.419Z (2 days ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Turn on Invert Colors in MacOS System Accessibility settings. Enable the shortcut key (control-opt-cmd-8) to swap back and forth
2. Invert colors and launch VS Code
3. Set theme to "Light+ (default)" (how it appears in menu Code | Preferences | Color Theme). It should be colors on dark background everywhere.
4. Press control-pot-cmd-8. See the windows turn to dark colors on white.
5. Press control-pot-cmd-8. Window will briefly flicker to light on dark but then back to dark with white background.

This did NOT occur in the previous version (I had closed and reopened VS Code this morning). Since I use OS-wide invert colors, I typically do not use application-specific light/dark modes as such but pick the theme setting that, when system invert is on, works for my vision issues.

(Note: tried to use the Help menu "Report Issue" but it just opened an entirely blank GitHub issue so if I'm missing information here that would be important, I'm sorry!)

**Comment by aeschli** [comment]
Do you have `window.autoDetectHighContrast` enabled?
We use `invert colors` as the signal to know that the OS is now in a high contrast mode. With the setting enabled, we switch to the  preferred dark or light High contrast theme as specified by `workbench.preferredDarkColorTheme` or `workbench.preferredHighContrastColorTheme`

**Comment by aeschli** [comment]
That setting we always had and it's on by default. I have to find out what has changed.

**Comment by aeschli** [comment]
duplicate of https://github.com/microsoft/vscode/issues/155243
