### ISSUE TITLE
Inline completions should prefer ranking single-line suggestions

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#146531]
```
Version: 1.67.0-insider
Commit: 909602cf04e0fa42528d692676d0d4e15e67bba2
```

When typing `public`, I often get the suggestion for `public override dispose():void {\n\n}` instead of the `public` keyword. This is annoying because it makes the code jump a lot. I tried to understand why this would happen, but when opening the suggest widget, the preferred suggestion changes to the `public` keyword:

https://user-images.githubusercontent.com/5047891/161250747-61a01be8-9bba-4774-998e-aa4b653a708b.mp4

**Comment by jrieken** [comment]
> I tried to understand why this would happen, but when opening the suggest widget, the preferred suggestion changes to the public keyword:

The suggest widget honours the `"editor.suggestSelection"`-setting but the same logic isn't applied with using inline completions.

**Comment by jrieken** [comment]
I have pushed a change that makes sure inline suggest also honours the suggest selection (setting and state). That also makes it honour the `preselect` flag of items. 

@alexdima This should ease your pain but it isn't a custom matching logic based on line count. I not yet ready to go down that road and I want to keep sorting/ranking the same as they are done for widget suggestions
