### ISSUE TITLE
Confusing "editor.snippetSuggestions" setting behavior blocks snippet usage

### ISSUE THREAD

**Issue by af4jm** [microsoft/vscode#146585]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64 & newer

There's 2 distinct popup menus, IntelliSense, and a different one for "hey, you just invoked a snippet, but there's more than one that match, so here's a menu for you to pick which one you want"

v1.64 introduced the `editor.snippetSuggestions` setting, which, per documentation, determines if snippets show up in IntelliSense, and if so in what order

However, if that new setting is "none" then snippets are also removed from the snippet disambiguation menu, meaning that instead of getting a menu to pick which snippet, you'll get a menu that tells you "no suggestions"

I would prefer to have it set to "none" because I don't want IntelliSense popping up in Markdown files every time I type a character that happens to start a snippet shortcut... but I have to enable that annoyance, because if I don't I have to make sure that none of my snippet shortcuts overlap because they'll be unusable if they do (e.g. I use "--" for an en-dash and "---" for an em-dash... so if I'm trying to invoke the longer one, I get the menu, and if the "none" setting empties the menu, then it's impossible for me to invoke that snippet)

**Comment by jrieken** [comment]
Closing because this has already been fixed 👯 

To verify

* have the settings below
* have the snippets below
* type `casing`
* press `Tab`
* ensure that you have choice of two snippets


#### settings
```json
    "editor.tabCompletion": "onlySnippets",
    "editor.snippetSuggestions": "none",
    "editor.suggest.showSnippets": false,
```


#### snippets
```
{
	"Casing": {
		"prefix": "casing",
		"body": "ONE"
	},
	"Casing2": {
		"prefix": "casing",
		"body": "TWO"
	}
}
```

**Comment by TylerLeonhardt** [comment]
![image](https://user-images.githubusercontent.com/2644648/214708892-4ac08bd1-be77-41e6-890d-6eb2edfe65ce.png)

looks good
