### ISSUE TITLE
https://aka.ms/vscode-server-keyring link points nowhere

### ISSUE THREAD

**Issue by imphil** [microsoft/vscode#146580]
I see a number of log messages on VS Code Server 1.66.0 like this one:

```
[11:02:46] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
```
The link https://aka.ms/vscode-server-keyring is pointing to https://github.com/bamurtaugh/server-docs/blob/main/docs/server-doc.md#how-can-i-set-up-a-keyring, which doesn't exist (any more).

It's coming from here:
https://github.com/microsoft/vscode/blob/acab0012379071c89da9141f51344a2b12c0ec9d/src/vs/platform/credentials/node/credentialsMainService.ts#L43

What's the right documentation piece to point to, and can someone update the aka.ms link (or I can do a PR to update the code with something).

CC @bamurtaugh

**Comment by bamurtaugh** [comment]
Thank you for filing! Updated the aka.ms link [to where](https://code.visualstudio.com/docs/remote/faq#_how-do-the-remote-development-extensions-work) this type of info is included.

**Comment by imphil** [comment]
@bamurtaugh thanks for the link update.

I had a look at the page https://aka.ms/vscode-server-keyring but I couldn't find any information related to keyrings. Where can I find something that's useful to resolve the error message "[09:34:57] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached"?

**Comment by bamurtaugh** [comment]
Hey @imphil, we have info on keyrings here: https://code.visualstudio.com/docs/editor/settings-sync#_troubleshooting-keychain-issues.

**Comment by imphil** [comment]
@bamurtaugh Great, thanks! 

Would it make sense to let https://aka.ms/vscode-server-keyring redirect to https://code.visualstudio.com/docs/editor/settings-sync#_troubleshooting-keychain-issues (instead of https://code.visualstudio.com/docs/remote/faq#_how-do-the-remote-development-extensions-work)?

**Comment by bamurtaugh** [comment]
Just updated, thanks!
