### ISSUE TITLE
RTL text positioning faulty (v1.66)

### ISSUE THREAD

**Issue by Gabriel-Peimer** [microsoft/vscode#146533]
Issue Type: <b>Bug</b>

In an HTML/JSX file use plain Hebrew text (not in the form of a string, className etc.). The Hebrew text will automatically appear on the left with the tabs appearing to its right. This has not been an issue in previous releases (i.e., the tabs would appear to the right of the text normally), and started for me today with version 1.66 of VSCode (first time I opened the editor with the new version).

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (9.13GB free)|
|Process Argv|--crash-reporter-id f48c3ef1-d788-4f84-83d1-6e277ad4b5ab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.36.0
flutter|Dar|3.36.0
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|9.5.0
vscode-docker|ms-|1.21.0
python|ms-|2022.4.0
vscode-pylance|ms-|2022.3.4
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
prisma|Pri|3.11.0
LiveServer|rit|5.7.5
material-ui-snippets|vsc|3.3.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvid2:30447481
pynewfile477:30463512

```

</details>

**Comment by merfankarami** [comment]
+1 same here

**Comment by alexdima** [comment]
@Gabriel-Peimer Could you please provide a screenshot and text that I could copy-paste? I think you might be running into https://github.com/microsoft/vscode/issues/99589 . Are you using `editor.renderWhitespace` : `all` or `selection` ?

**Comment by ahmadi-akbar** [comment]
same here

**Comment by ahmadi-akbar** [comment]
## Solution
   change 
   ```
"editor.renderWhitespace": "all"
   ```
   to
   ```
"editor.renderWhitespace": "selection"
   ``` 

## Problem
Setting "editor.renderWhitespace" to "all"  will messed up text rendering
here is an example

| "editor.renderWhitespace": "all" | "editor.renderWhitespace": "selection" |
|-----|--------------|
| ![image](https://user-images.githubusercontent.com/48069695/161610036-00720bc9-7450-4410-9522-580d6297a5e4.png) | ![image](https://user-images.githubusercontent.com/48069695/161608627-1cfc3cf0-7b75-4e73-bf78-5ca5317e6623.png)|



@alexdima  thank you for your response

**Comment by Gabriel-Peimer** [comment]
> @Gabriel-Peimer Could you please provide a screenshot and text that I could copy-paste? I think you might be running into #99589 . Are you using `editor.renderWhitespace` : `all` or `selection` ?

Hi @alexdima, thanks for the response.

I am currently using `editor.renderWhitespace: selection` as it is the default setting.
Example text used in photos (Hebrew): טקסט לדוגמה

When using `editor.renderWhitespace: selection`, _text not selected_ appears correctly but in wrong location:
![bug1](https://user-images.githubusercontent.com/68541361/161778033-534c1894-5d20-4a36-83a4-d25792a6b487.PNG)

When using `editor.renderWhitespace: selection`, _text is selected_ appears incorrectly, words reversed, but in correct location:
![bug2](https://user-images.githubusercontent.com/68541361/161778311-5c97d4d6-1221-435a-8f48-8b86686232ff.PNG)

When using `editor.renderWhitespace: all`, _text not selected_ appears incorrectly, words reversed, but in correct location:
![bug3](https://user-images.githubusercontent.com/68541361/161778552-6258655e-b1f4-44fb-b855-29ed2c2aab2f.PNG)

**Comment by alexdima** [comment]
Thank you for your reply. The render whitespace in selection problem is #99589 , the whitespace disabled problem is #146354 . Tomorrow's insiders will contain fixes for both issues.
