### ISSUE TITLE
inline hint spacing is inconsistent between left and right

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#146575]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.67.0-insider (user setup)
Commit: 909602cf04e0fa42528d692676d0d4e15e67bba2
Date: 2022-03-31T11:00:49.798Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

Apologies if this is raised in the wrong place, but my understanding is Rust Analyzer [now uses](https://rust-analyzer.github.io/thisweek/2022/03/14/changelog-120.html#new-features) the native inline hints.

Steps to Reproduce:

1. Open https://github.com/boa-dev/boa with Rust Analyzer installed
2. navigate to https://github.com/jasonwilliams/boa/blob/main/boa_engine/src/builtins/typed_array/mod.rs

When the inline hint is on the right of the subject it almost overlaps with the subject itself; I.E there's no spacing between the subject and the hint. When the inline hint is on the left it is fine.

<img width="852" alt="spacing issue" src="https://user-images.githubusercontent.com/936006/161317611-1ef7779b-2f5d-4320-8c35-94ef5c87f335.png">

In the below example I would expect there to be a space between obj and ` :&JsObject`. Also I don't think there needs to be a space between the colon and the `&jsObject` (similar to `message:` below).
<img width="722" alt="spacing issue 2" src="https://user-images.githubusercontent.com/936006/161317884-a3ea24cf-28e3-4d8d-8850-ee9dc8a3f26e.png">

Related: https://github.com/microsoft/vscode/issues/145191

**Comment by jhgg** [comment]
As far as I can tell this is working as intended. Insofar as, this is the intended effect of the new compact display style for inlay hints. If you want there to be more padding around things, the "standard" display style might better suite your needs.

**Comment by jhgg** [comment]
The intent of the inlay hint that adds a type ascription is intentionally not padded so that it looks like correct rust syntax. The left hand side inlay hint is not actually rust syntax which is why it has a bit of padding.

**Comment by jhgg** [comment]
Either way though, the control of padding in these cases lie directly within the language server itself (rust-analyzer) and not vscode. So perhaps a discussion would be better had on the rust analyzer repository itself.

**Comment by jasonwilliams** [comment]
Raised https://github.com/rust-analyzer/rust-analyzer/issues/11873

**Comment by jrieken** [comment]
The padding "around" hints is controlled by extensions, the padding "inside" hints is controlled via the new user setting
