### ISSUE TITLE
reintroduce Reveal in side bar

### ISSUE THREAD

**Issue by salda** [microsoft/vscode#146527]
The option on open files "Reveal in side bar" is now missing, it was a feature that I used very often :(
So now it only automatically show the files from open folder in the side bar, but I usually care about those not in the folder.

**Comment by gjsjohnmurray** [comment]
In 1.66 it was retitled `Reveal in Explorer View`

**Comment by JacksonKearl** [comment]
https://github.com/microsoft/vscode/commit/9df43c72d9504169159185291fe47471ba9500ee
