### ISSUE TITLE
vs code stuck in beginning with white appearance like below

### ISSUE THREAD

**Issue by jose-jordan** [microsoft/vscode#146571]
![image](https://user-images.githubusercontent.com/102205327/161314375-57e17a87-3a55-463a-ac0e-7987e876b38e.png)

**Comment by Spritea** [comment]
same issue on win10 for the latest version 1.66.0.

**Comment by jose-jordan** [comment]
why no one ready to help to solve this problem.

**Comment by jose-jordan** [comment]
> same issue on win10 for the latest version 1.66.0.

how you solved?

**Comment by deepak1556** [comment]
Can you quit all open instance of the application and run `code --verbose` from the terminal, attach the terminal output here once the blank screen is rendered. Thanks!

**Comment by Spritea** [comment]
Attached in the txt file blow since it's too long.
[vscode_verbose.txt](https://github.com/microsoft/vscode/files/8406693/vscode_verbose.txt)

**Comment by deepak1556** [comment]
the output is cut off, can you redirect the output streams to file instead `code --verbose 1> vcode_verbose.txt 2>&1`. Also what version of windows OS is this ?

**Comment by jose-jordan** [comment]
![Uploading image.png…]()

**Comment by jose-jordan** [comment]
![image](https://user-images.githubusercontent.com/102205327/161477947-98d96c77-a4d9-4e55-9f13-aee22cc58e12.png)

**Comment by jose-jordan** [comment]
you can see in setting there is notification when i update this notification then this notification again launch vs code and then vs code stuck in beginning like above comments.

**Comment by jose-jordan** [comment]
i havd issued this is too that in terminal i cannot write anything and there is not bash path showing in terminal please solve this problem also.
![image](https://user-images.githubusercontent.com/102205327/161478327-9a0f8bd2-81a3-493c-8392-224ab04b1e0f.png)

**Comment by jose-jordan** [comment]
bawa@jass-pc MINGW32 ~/Desktop , this line is not showing in terminal i want to solve this issue and want to start coding.

**Comment by deepak1556** [comment]
Windows 7 is no longer officially supported by our desktop application https://code.visualstudio.com/Docs/supporting/requirements#_platforms since the underlying components of our runtime dropped support for it https://github.com/nodejs/node/issues/29269

You can try our desktop application with windows 8 or higher, if not you can also try our web version https://vscode.dev/ in your current setup.

**Comment by jose-jordan** [comment]
![image](https://user-images.githubusercontent.com/102205327/161490153-8cd1eb7d-7753-475a-bd99-5ec73b47eed9.png)

**Comment by jose-jordan** [comment]
![image](https://user-images.githubusercontent.com/102205327/161490255-4380d0e2-9742-42eb-8704-50513ced57db.png)

**Comment by jose-jordan** [comment]
![image](https://user-images.githubusercontent.com/102205327/161490420-6f3e89a2-9acd-47f6-a3e3-5c92e72c137c.png)

**Comment by jose-jordan** [comment]
git bash this path line not showing in vs code terminal and i am unable to write anything in terminal.please solve this problem.
![image](https://user-images.githubusercontent.com/102205327/161490902-47f11f66-2e9f-42c0-8dca-fb33a3cf517d.png)

**Comment by jose-jordan** [comment]
How to run terminal in vs code dev
![image](https://user-images.githubusercontent.com/102205327/161504999-dd037dc4-0fac-4584-89ea-0922e55fd006.png)

**Comment by deepak1556** [comment]
Terminal support does not currently exist on the web version and is on our roadmap https://github.com/microsoft/vscode/issues/135565, you can follow that issue for updates.

**Comment by jose-jordan** [comment]
so then how i can use vs code for coding in vs code terminal unable to write and in web version terminal is not exist.

**Comment by jose-jordan** [comment]
everything is going good then why vs code stop supporting in windows 7.in vs code terminal there is no path of gitbash showing and i cannot write anything in terminal.very bad update

**Comment by deepak1556** [comment]
> everything is going good then why vs code stop supporting in windows 7

Windows 7 is EOL officially since January 2020 https://www.microsoft.com/en-US/windows/windows-7-end-of-life-support-information and as mentioned in https://github.com/microsoft/vscode/issues/146571#issuecomment-1087140682 please update to a newer version of the OS for using VSCode.

**Comment by jose-jordan** [comment]
i have been using it from april 2021 there is no problem. very bad exprience. i am closing the issue and not satisfied.
