### ISSUE TITLE
Add variable to tasks.json for foldername

### ISSUE THREAD

**Issue by JuHo1117** [Microsoft/vscode#14651]
"${folderName}.exe" as project name.

**Comment by weinand** [comment]
Please explain the semantics of `folderName`. What folder?

**Comment by JuHo1117** [comment]
${folderName} is the base name of ${workspaceRoot};
if ${workspaceRoot} is "X:\aa\bb\cc",${folderName} is "cc".

**Comment by JuHo1117** [comment]
or call it "${workspaceRootBaseName}"

**Comment by isidorn** [comment]
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configurationResolver/node/configurationResolverService.ts#L24

**Comment by weinand** [comment]
Why is `workspaceRootBaseName` useful? 
I don't understand the purpose of "${workspaceRootBaseName}.exe" (your example from above).

**Comment by dbaeumer** [comment]
This exists and the variable is called ${workspaceRootFolderName}

**Comment by weinand** [comment]
@dbaeumer ${workspaceRootFolderName} is missing from the documentation: https://code.visualstudio.com/docs/editor/tasks

**Comment by JuHo1117** [comment]
use ${workspaceRootFolderName} as Project Name in "tasks.json"

**Comment by JuHo1117** [comment]
@weinand 
For example

in `settings.json`
set `"HOME_MINGW": "x:/mingw32"`

in `tasks.json`
set `"command": "${config.HOME_MINGW}/bin/make.exe"`
set `"args": ["PROJECT_NAME=${workspaceRootFolderName}"]`
in makefile, set $(POJECT_NAME) as project name

in `launch.json`
set "MIDebuggerPath": "${config.HOME_MINGW}/bin/gdb.exe"
set "program": "${workspaceRoot}/${workspaceRootFolderName}.exe",

**Comment by JuHo1117** [comment]
but 
in c_cpp_properties.json
set "includePath": ["${config.HOME_MINGW}/include"]
not work for me

**Comment by weinand** [comment]
@JuHo1117 is 'HOME_MINGW' an environment variable? If yes, then you have to access it as `${env.HOME_MINGW}`

**Comment by JuHo1117** [comment]
`'HOME_MINGW'` is not an environment variable.
`'HOME_MINGW'` defined in 'settings.json.
So,I can access it as `${config.HOME_MINGW}`

**Comment by weinand** [comment]
@JuHo1117 I don't think that you can introduce your own variables in settings.json. So your 'HOME_MINGW' isn't available in launch.json or tasks.json.

@bpasero is this correct?

**Comment by bpasero** [comment]
Today we do not support any variable substitution for settings.json

**Comment by weinand** [comment]
@bpasero I'm not talking about variable substitution in settings.json.
My question is: can I introduce a new ad-hoc setting in settings.json like this:
```json
"HOME_MINGW": "x:/mingw32"
```
and have this available for variable substitution in 'tasks.json' or 'launch.json'?

**Comment by bpasero** [comment]
@weinand not sure, @isidorn might know since he introduced the config service to deal with variables like that.

**Comment by JuHo1117** [comment]
I already did this.

**Comment by weinand** [comment]
@isidorn didn't know, he referred me to you... ;-)

**Comment by bpasero** [comment]
We do not prevent you from adding keys to settings.json that are unknown so I would assume this works. Maybe just try it out quickly?

**Comment by JuHo1117** [comment]
I'm already doing that,and it works fine for me!!!

**Comment by weinand** [comment]
@JuHo1117 so the only problem that remains is that there is no variable substitution for c_cpp_properties.json.
Since this is is not part of VS Code but a separate extension, please file an issue against the extension's repository.

**Comment by dbaeumer** [comment]
@gregvanl can you add ${workspaceRootFolderName} to the documentation here: https://code.visualstudio.com/docs/editor/tasks

**Comment by visualperception** [comment]
I added ${workspaceRootFolderName} system variable name totasks.md in vscode-docs and issued a pull request.
https://github.com/Microsoft/vscode-docs/pull/686

somehow I managed to do it twice but I think its OK.
