### ISSUE TITLE
F2 renaming not working in Jupyter Notebook

### ISSUE THREAD

**Issue by kameshkotwani** [microsoft/vscode#146505]
Does this issue occur when all extensions are disabled?: Did not check

- VS Code Version: 1.66.0
- OS Version: Windows 11 Build 22000.556

Steps to Reproduce:

1. Open a Jupyter Notebook in vscode.
2. Write some python code and some variables with same name.
3. Press F2 to get refactoring of word.
4. Pressing enter after changing the word does nothing.

Expected:
All the words in the file should be changed to the new word.

Recording has been posted.

https://user-images.githubusercontent.com/36355951/161208575-16910a60-11a7-46ca-872f-581a17ddbc90.mp4

**Comment by gjsjohnmurray** [comment]
/extPython

Maybe https://github.com/microsoft/vscode-python/issues/18834
