### ISSUE TITLE
editor.action.smartSelect.grow does not work with inputs in the editor

### ISSUE THREAD

**Issue by dogmatic69** [Microsoft/vscode#14657]
- VSCode Version:
```
Version 1.6.1
Commit 9e4e44c19e393803e2b05fe2323cf4ed7e36880e
Date 2016-10-13T15:43:46.054Z
Shell 1.3.7
Renderer 52.0.2743.82
Node 6.5.0
```
- OS Version:
```
Linux ubuntu02 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Steps to Reproduce:

I have custom mapped "select all" config that seems to break other inputs within the application. I can still "select all" but I have to specifically `ctrl+shift+a`, 

```
    {
        "key": "ctrl+a",
        "command": "editor.action.smartSelect.grow"
    },
    {
        "key": "ctrl+shift+a",
        "command": "editor.action.selectAll"
    }
```
With this configuration `ctrl+a` no longer works in any other inputs within the application. I can still "select all" but I have to specifically `ctrl+shift+a`, 

Using `editor.action.smartSelect.grow` should select all text in inputs (eg: search, replace etc) as the scope would be the entire field. 

Sublime Text 3 works correctly with this setup :/

**Comment by alexandrudima** [comment]
@dogmatic69 Your keybinding rule does not contain a `when` rule, therefore it will always execute. I suggest adding `"when": "editorTextFocus"`. This means that keybinding rule will be active only when focus resides in the text of an editor.
