### ISSUE TITLE
Why the VScode flashing and quit when I open it?

### ISSUE THREAD

**Issue by MengBowen-328p** [microsoft/vscode#146578]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.66.0
- OS Version: 22000.556

Steps to Reproduce:

1. Double click the shortcut of VScode which on the DESKTOP
2. The software flashing and quit immediately

**Comment by deepak1556** [comment]
Can you run the application from terminal with `code --verbose` and attach the output.

**Comment by MengBowen-328p** [comment]
Thanks for your advice! This problem had solved when I uninstall the vscode and remove all of the user cache and the config file. Then I downloaded the version for system (before I used was the version for user) and install, the problem solved



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月4日(星期一) 晚上11:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/vscode] Why the VScode flashing and quit when I open it? (Issue #146578)





 
Can you run the application from terminal with code --verbose and attach the output.

**Comment by deepak1556** [comment]
Thanks for confirming. Does the issue persist if you try the user install version ?
