### ISSUE TITLE
No way to tell if webview extension is in side panel/auxiliaryBar 

### ISSUE THREAD

**Issue by eric-j** [microsoft/vscode#146583]
This pertains to developing a webview extension for vscode.  

There was a new feature added to vscode mid-February 2022 that allows the user to drag an extension to the "side panel" or auxiliary bar.  There doesn't seem to be any way in the vscode API to tell if said extension is placed in that side panel.

Example of extension in side panel:
![image](https://user-images.githubusercontent.com/10050393/161328078-0dd0a67a-8541-425c-919e-22b9651b238b.png)

Could you add a function to the vscode API to read this setting?

Thank you!

**Comment by mjbvz** [comment]
Previously tracked in #106825

**Comment by mjbvz** [comment]
Can you share a use case for this?

**Comment by mjbvz** [comment]
Closing since we have not heard what the use cases for such an API are
