### ISSUE TITLE
Console Log deletes text

### ISSUE THREAD

**Issue by Dinoraptor101** [microsoft/vscode#146572]
Issue Type: <b>Bug</b>

If you resize the console log post running a NodeJs code, the debug statements disappear. this happens with the max/min arrow in the Terminal pane, but also happens with the main Shell window resize.

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (6.65GB free)|
|Process Argv|--crash-reporter-id 2d581da7-0a87-4ca6-bec5-e5714787055b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.5
vscode-npm-script|eg2|0.3.24
azurecli|ms-|0.5.0
vscodeintellicode|Vis|1.2.17
vscode-java-debug|vsc|0.40.0
vscode-java-dependency|vsc|0.19.0
vscode-icons|vsc|11.10.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
pythonvsnew555:30457759
vscscmwlcmt:30438805
pynewfile477:30463512

```

</details>

**Comment by weinand** [comment]
you are talking about VS Code's integrated terminal and not the debug console, right?

**Comment by Dinoraptor101** [comment]
@weinand  yes thats correct
