### ISSUE TITLE
New SCM diff gutter decorations do not respect the existing SCM gutter width setting

### ISSUE THREAD

**Issue by anthroid** [microsoft/vscode#146574]
Version: 1.66.0 (system setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

New "striped" gutter decorations were added in `1.66`.
These decorations do not respect the existing **SCM: Diff Decorations Gutter Width** setting:
```c
scm.diffDecorationsGutterWidth
```
Changing the above setting has no effect on the new decorations.

**Comment by misolori** [comment]
I think this was an oversight and have a PR that can help address this. Thanks!
