### ISSUE TITLE
Git: creating new branch shows "master" still

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14659]
Steps to Reproduce:

1. I was on vscode master  
2. brought up branch switcher to create release/1.7
3. I saw this in the status bar:

![image](https://cloud.githubusercontent.com/assets/900690/19806614/57cfce5e-9d1c-11e6-8527-8459fd75412c.png)

See video:

![editors](https://cloud.githubusercontent.com/assets/900690/19806632/77598d64-9d1c-11e6-85f3-727a50fae2d5.gif)

**Comment by joaomoreno** [comment]
Great catch. Broken by #12584. We should fix before the end of October.

**Comment by bpasero** [comment]
@joaomoreno feel free to push to master and I can pick it up for another build

**Comment by joaomoreno** [comment]
Done!
