### ISSUE TITLE
Command link for extension with pre-release has uninformative tooltip

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#146595]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67-insider
- OS Version: Windows 11

Steps to Reproduce:

1. In extension pane, hover over the description of an extension which has pre-releases available
2. Hover over the 'pre-release version' link text
3. :bug: the tooltip is just the command link, I would expect something like "Show pre-release version"
 
![image](https://user-images.githubusercontent.com/30305945/161355305-01aea53e-8604-48a7-a43b-9137fefa22ff.png)

**Comment by sandy081** [comment]
@Tyriar May I know how can I set the title for command links in the hover?
