### ISSUE TITLE
Vs code peformance issue

### ISSUE THREAD

**Issue by satyabayagani** [microsoft/vscode#146570]
VS code is responding very slow to any changes in the code and it started after installing an extension named 'vscode-styled-components' and the issue isn't resolved even after uninstalling the extension

**Comment by satyabayagani** [comment]
> /needsMoreInfo
And one more thing is that the prettier v9.5.0 extension has an activation time 3938ms. Can this be the reason of slow response to changes in the code?

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by satyabayagani** [comment]
@jrieken   thank you for providing the guide.  Here is the info that I've collected using the guide.

I've tried running the vs code by disabling the extensions as mentioned in the guide but it didn't work out.
- Here is the profile of the running extensions
[CPU-20220404T080317.792Z.cpuprofile.txt](https://github.com/microsoft/vscode/files/8407858/CPU-20220404T080317.792Z.cpuprofile.txt)
- Information about the running VS Code
![processes_status](https://user-images.githubusercontent.com/58974604/161501256-6ba50776-c963-43a8-b06b-8c70bf6ea704.png)

**Comment by jrieken** [comment]
Sorry, there is nothing suspicious in the attached profile nor in the screen capture. Please try this again when things are slow. Also, note that you only profiled the extension host process but the renderer/main process. Please follow the respective guides for that

**Comment by satyabayagani** [comment]
Profiles of renderer process:
- profile with non-empty settings.json file
[CPU-20220404T143743.txt](https://github.com/microsoft/vscode/files/8408458/CPU-20220404T143743.txt)
- profile with empty settings.json file
[CPU-20220404T144036.txt](https://github.com/microsoft/vscode/files/8408484/CPU-20220404T144036.txt)
- profile of a random file
[CPU-20220404T144959.txt](https://github.com/microsoft/vscode/files/8408502/CPU-20220404T144959.txt)
- Profiles of vs code start-up
[prof-Wir9LIHQ.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/8408528/prof-Wir9LIHQ.extHost.cpuprofile.txt)
[prof-Wir9LIHQ.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/8408529/prof-Wir9LIHQ.main.cpuprofile.txt)
[prof-Wir9LIHQ.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/8408530/prof-Wir9LIHQ.renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
Sorry, but none of the profiles hint to performance problem. It all looks normal.
