### ISSUE TITLE
Extension throws 'not found' error for commands after publishing.

### ISSUE THREAD

**Issue by AkashGutha** [Microsoft/vscode#14650]
- VSCode Version: 1.6.1
- OS Version: win 7

Steps to Reproduce:
1. make a extension in js.
2. debug it it will work.
3. publish it and install or make vsix and install.
4. run a command. it doesnt work.

**Comment by jrieken** [comment]
@AkashGutha Please update this issue with *precise* steps that allow me to reproduce. Like, the actual extension snippet that is causing this and an actual error message.

**Comment by AkashGutha** [comment]
it was problem with package.json . i had the dependecies as devependencies instead of dependencies.

now it's fixed. it's not a problem with vscode
