### ISSUE TITLE
How to Go To Definition / open file in JavaScript import statements?

### ISSUE THREAD

**Issue by toffler** [microsoft/vscode#146502]
I have a html file with JavaScript module in it, like so:

```
<script type="module">

    import * as LOADER from './path/loader.js'

    import { add } from '/path/ui.js'

  </script>
```

I run a server at localhost, so I have a local folder set as a root (under Win10) and the file works perfectly in the browser.

When I open this file in VS Code, it doesn't understand paths mentioned in import statements, relative or absolute, I can't use Go To Definition or Peek or open imported .js files.

Is it possible to make VS Code work with import statements?

I created **jsconfig.json** file in the same folder as the html file:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "baseUrl": ".",
    "paths": {
      "/*": ["./*"]
    }
  },
  "include": ["/path/*"]
}
```

but it doesn't make any difference.

![vscode](https://user-images.githubusercontent.com/5369085/161229362-4874565b-0462-4612-821f-88f2b50e6641.jpg)

**Comment by jpbnetley** [comment]
I hade the same problem, but got it working by changing the `jsconfig.json` to just reference the baseUrl.
```json
{
  "compilerOptions": {
    "baseUrl": "src"
  }
}
```

I guess if you want to do the same, it might look like this
```json
{
  "compilerOptions": {
    "baseUrl": "."
  }
}
```

Hope this helps.

**Comment by toffler** [comment]
> I hade the same problem, but got it working by changing the `jsconfig.json` to just reference the baseUrl.
> ...
> Hope this helps.

As you can see from the file I currently have, I already put baseUrl in it and it doesn't help.

**Comment by aeschli** [comment]
We currently don't follow import statements in embedded JavaScript.
Covered by #114115
