### ISSUE TITLE
Binary files being opened in staged diff view throws

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#14658]
Steps to Reproduce:
1.  Have a binary file, for instance a gif
2. Open it in vscode - notice that the editor nicely says it is binary and can not be opened
3. Open git viewlet and stage it -> once you try to open it staged it throws an exception

**Comment by joaomoreno** [comment]
Is this the error?

```
Unable to open 'diagonal-fill.png (index) ↔ diagonal-fill.png': File seems to be binary and cannot be opened as text (2 errors in total).
```

**Comment by bpasero** [comment]
There are lots of issues opening binary files from the git viewlet. I think there are more scenarios:
* binary file on index (added or deleted)
* binary file with outgoing changes from working files
* binary file with outgoing changes from index

I think the biggest problem is that the binary editor (either diff or normal) wants to show the image using HTML but we do not have the binary bits on disk anywhere to show the "before" version.

**Comment by isidorn** [comment]
@joaomoreno yeah that is the error

**Comment by joaomoreno** [comment]
I think @isidorn doesn't expect the file to be opened at all. He seems to be referring to the fact that the user gets an error instead of the editor simply saying `can't open this`. We can do that.

**Comment by bpasero** [comment]
Yeah we can fail more gracefully.
