### ISSUE TITLE
Getting false errors in VScode! Please help!

### ISSUE THREAD

**Issue by Velcro3** [microsoft/vscode#146565]
Does this issue occur when all extensions are disabled?: **Yes**/No

- VS Code Version: 1.66.0
- OS Version: Ubuntu 20.04
I have a CSS file with 2 margins and the second one is causing 2 problems.
However, the errors are fake!
- it is expecting a semicolon
- it is expecting a selector

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Please post a a minimal code sample.

**Comment by Velcro3** [comment]
Going to edit

**Comment by Velcro3** [comment]
Wait... I DON'T REMEMBER THE CODE!!!
