### ISSUE TITLE
Support vscode.dev in Firefox using the 'webkitdirectory' attribute

### ISSUE THREAD

**Issue by theres-waldo** [microsoft/vscode#146694]
While Firefox does not support the nonstandard File System Access API which vscode.dev currently requires, based on [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1762110#c1) it would be possible to get vscode.dev to work in Firefox a different way, using a normal `<input>` element with the [webkitdirectory](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory) attribute.

Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0
Embedder: vscode.dev

**Comment by shz42** [comment]
According to [File System Access API - browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API#browser_compatibility), Firefox 111+ added support for the File System Access API, although without `queryPermission`, `remove`, `requestPermission` which doesn't seem to effect the general functionality. Maybe reconsider adding the support for Firefox?

**Comment by joaomoreno** [comment]
Great to see Firefox joining the party. Closing this feature request which is specific about `webkitdirectory`.
