### ISSUE TITLE
can't solve whitespace issue while commiting

### ISSUE THREAD

**Issue by sagarsheregar** [microsoft/vscode#146699]
Issue Type: <b>Bug</b>

vs code is showing whitespace changes also in git changes

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:41.156Z)
OS version: Linux x64 5.4.0-107-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3664)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 1, 1|
|Memory (System)|15.52GB (8.85GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 7096b59d-7357-406a-bdfc-183f2259ed50|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-extra-intellisense|ami|0.6.2
vscode-intelephense-client|bme|1.2.0
laravel-goto-view|cod|1.3.7
githistory|don|0.6.19
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
laravel-create-view|gli|0.0.6
laravel-blade-wrapper|IHu|1.0.1
dotenv|mik|1.0.1
laravel-goto-components|nao|1.2.0
laravel-blade|one|1.32.0
laravel-extension-pack|one|1.1.0
laravel5-snippets|one|1.15.0
laravel-artisan|rya|0.0.28
vscode-blade-formatter|shu|0.13.16

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrc:30451274
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvid1:30447480
pynewfile477:30463512

```

</details>

**Comment by lszomoru** [comment]
@sagarsheregar, could you please provide detailed repro steps of the issue that you are facing. Thanks!
