### ISSUE TITLE
Docs: GitHub Actions script for prebuilding devcontainer with cli fails

### ISSUE THREAD

**Issue by marcusturewicz** [microsoft/vscode#146681]
The given [script on the docs site](https://code.visualstudio.com/docs/remote/devcontainer-cli#_adding-automation) to create a GitHub Action for prebuilding devcontainer images has recently (last month) started failing. You can see a [failed run here](https://github.com/GigLocal/devcontainer/runs/5797858251?check_suite_focus=true) where I am using the script essentially verbatim, with a few names changed to suit my project. I think this is due to a breaking change in the CLI, since I [rolled back](https://github.com/GigLocal/devcontainer/runs/5805310679?check_suite_focus=true) to @vscode/dev-container-cli@0.217.1 and my script is working again.

The docs should be updated to reflect any CLI changes.

Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: N/A
- OS Version: N/A

Steps to Reproduce:

1. Go to https://code.visualstudio.com/docs/remote/devcontainer-cli#_adding-automation
2. Copy the script and put into a GitHub Action
3. Try build action, see that it fails

**Comment by chrmarti** [comment]
Tracking as https://github.com/microsoft/vscode-remote-release/issues/6549.
