### ISSUE TITLE
JSON snippets show up twice in package.json intellisense

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14669]
Probably similar to #13835 -
1. Add a JSON snippet. Mine is 

```
"test snippet": {
  "prefix": "test",
  "body": [
    ""
  ],
  "description": "test"
}
```
1. Open package.json, put the cursor in "dependencies"
   - It doesn't repro elsewhere
2. Type "test"
   - If I type fast, I only see the snippet. If I type a little slower, I see the snippet and npm packages, and this is more likely to repro
3. Often see two copies of "test"
4. If not, alt+backspace and type "test" again
   ![image](https://cloud.githubusercontent.com/assets/323878/19816283/83d97a84-9cfb-11e6-8a8a-2224cf259856.png)

Sometimes, I get into a state where I see another instance of "test" added each time I repeat steps 3-5.

![image](https://cloud.githubusercontent.com/assets/323878/19816460/321a6036-9cfc-11e6-907b-8370c8ea2ebe.png)

It also seems like a bug that when I type "test" quickly, I don't see the npm packages.

**Comment by jrieken** [comment]
Doesn't repo after fixing #13835. Closing as dupe
