### ISSUE TITLE
Uniform tab size for opened editors

### ISSUE THREAD

**Issue by ChitturiSaiSuman** [microsoft/vscode#146689]
Hi, I would like to bring to your notice that the tab size for opened editors is not uniform. Say, if I open more than 5 files and would like to close them after all the work is done, then it requires moving the mouse cursor to close tabs of different sizes (please refer to the attached files). It would be better if we can have a uniform tab size (width). For instance, chrome tabs have uniform width irrespective of the title of the tab. This helps close tabs faster when quitting.

https://user-images.githubusercontent.com/56757878/161468806-ed5cda82-3106-4f36-925f-3cf4d7a60934.mp4

https://user-images.githubusercontent.com/56757878/161468812-145ec437-1170-4898-a499-dd7779ba9c77.mp4

**Comment by gjsjohnmurray** [comment]
Did you try the `"workbench.editor.tabSizing": "shrink"` setting?
