### ISSUE TITLE
syntax highlighting and code autocompletion not working

### ISSUE THREAD

**Issue by Laxmi530** [microsoft/vscode#146625]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66
- OS Version: Windows 10 Pro 21H2

Steps to Reproduce:

1. Syntax highlighting and code auto-completion is not 
![Screenshot 2022-04-02 204910](https://user-images.githubusercontent.com/76505459/161389837-deb90e6a-aeaa-4899-9568-1cabc22abbd9.jpg)
working neither in jupyter notebook nor in normal python file post update to version 1.66.
2. I restarted my system and cleared the catch memory still facing the same issue. Can anyone please help me with how to fix the issue?

**Comment by DonJayamanne** [comment]
This should be fixed now.
