### ISSUE TITLE
is there anyone to solve the issues or not? i submit my issue from two days but no one helped me.

### ISSUE THREAD

**Issue by jose-jordan** [microsoft/vscode#146630]
vs code stuck in begining like this
![image](https://user-images.githubusercontent.com/102205327/161394917-eeaf62be-4fcc-44b1-b3d3-b6e180423ac7.png)

**Comment by gjsjohnmurray** [comment]
Related to #146571

@jose-jordan what response time does your SLA guarantee?

**Comment by jose-jordan** [comment]
I don't know

**Comment by jose-jordan** [comment]
> Related to #146571
> 
> @jose-jordan what response time does your SLA guarantee?

please help sir my vs code terminal is unable to write anything.

**Comment by TylerLeonhardt** [comment]
> please help sir my vs code terminal is unable to write anything.

this doesn't sound like the same issue as the one you talk about above. For this, can you please open a new issue and provide a gif or recording or something so that we have a better idea of what you're seeing.
