### ISSUE TITLE
findFiles with RelativePattern returns empty array on vscode.dev with local folder

### ISSUE THREAD

**Issue by lewisl9029** [microsoft/vscode#146641]
Version: 1.67.0-insider
Commit: 8b7086afdbfd42bf6e7b8c0bb586530bf7cf1396
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
Embedder: vscode.dev

Steps to repro:

1. Open a local folder on vscode.dev
2. Create the following file: `app/main.js`
3. Create a new extension that attempts to use the `vscode.workspace.findFiles` API with `vscode.RelativePattern`, like below:

```js
import * as vscode from 'vscode'

export const activate = (context) => {
  const uris = await vscode.workspace.findFiles(
    new vscode.RelativePattern(
      vscode.workspace.workspaceFolders[0],
      'app/**/*',
    ),
  )

  console.log(uris)
}
```

4. Inspect console logs

Expected:
Array with the URI for `app/main.js` is logged.

Actual:
Empty array is logged.

I tested on vscode.dev and insiders.vscode.dev, using Chrome on both macOS and Windows.

Happy to provide any more info to help debug. Thanks!

**Comment by JacksonKearl** [comment]
Fixed, though I noticed fileSearch triggered from an extension always disregards ignore files:
https://github.com/microsoft/vscode/blob/bf1c9e93913714c85b0db6f2e2690b0bddbab7e4/src/vs/workbench/api/browser/mainThreadWorkspace.ts#L151
@roblourens is this expected? The docs for the fileSearch api say that if the `exclude` parameter is `undefined` then ignore files will be used, they should only be disregarded when it's `null`.

**Comment by roblourens** [comment]
Yes, for the same reason that we use files.exclude but not search.exclude, although many users would probably want all the excludes. The search API needs to be revamped to give this flexibility.
