### ISSUE TITLE
SignatureHelp below IntelliSense window

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#14668]
- scroll a line towards the top of the screen
- invoke signature help and intellisense
- 🐛 signature help shows below intellisense

<img width="685" alt="screen shot 2016-10-28 at 18 07 25" src="https://cloud.githubusercontent.com/assets/1794099/19813305/708515e0-9d39-11e6-8a30-1fb099a8383f.png">

**Comment by joaomoreno** [comment]
What's the expected behaviour here? One solution would be to render the hover on top of the suggest. The other, to be aware of multiple widgets and just lay them out in ways that they don't overlap.

**Comment by jrieken** [comment]
Yeah, I would always keep the above, below layout when both widgets show

**Comment by rcjsuen** [comment]
Just got hit by this. I thought there was something wrong with my language server. :O

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
