### ISSUE TITLE
Using GDB Enhanced Features (GEF) in Integrated Debug Console

### ISSUE THREAD

**Issue by MartinLoeper** [microsoft/vscode#146673]
I do not understand why VSCode's integrated debug console escapes all output from GDB's enhanced features extension (GEF).
Attached below, you find a screenshot that shows how the integrated console displays the ASCII sequence and secondly how the debug console displays it.

Correct Rendering in Integrated Terminal:
![vscode-integrated-terminal](https://user-images.githubusercontent.com/5209395/161447518-86cb1eb9-07cc-4762-9087-51e8ec4b0ee0.png)

Bad Rendering in Debug Console:
![vscode-integrated-debug-terminal](https://user-images.githubusercontent.com/5209395/161447586-9d7dd5eb-1d6e-420f-9804-6a3ff137afa9.png)

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: Arch; Linux version 5.16.16-zen1-1-zen (linux-zen@archlinux) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.38)

Steps to Reproduce:

1. Configure launch.json to launch gdb and connect to a remote gdbserver using GEF remote command 
2. Use GEF's *context* command

**Comment by weinand** [comment]
VS Code's Debug Console is not an Integrated Terminal and has limitations which results in the issues you are seeing.
There are no plans to fix this because the issues can be avoided by using the Integrated Terminal.

**Comment by MartinLoeper** [comment]
Thanks for pointing that out! It seems like the cppdbg debugger does **not support the integrated terminal**. Opened an issue in the C/C++ extension repository: https://github.com/microsoft/vscode-cpptools/issues/9132
