### ISSUE TITLE
emulator not working

### ISSUE THREAD

**Issue by Ginalim** [microsoft/vscode#146650]
Hi, I am new to coding and visual studio code. My problem is after I launch the android emulator and try to change the color but the emulator did not work. So after u change the code did it change by itself or u have to click some run button to make the emulator work. Btw I'm so sorry for my poor English cause its not my first language...

**Comment by Ginalim** [comment]
> /causedByExtension

Thank you. Do you know how to fix it ?

**Comment by rzhao271** [comment]
Which android emulator extension are you using? Can you paste the extension ID?

**Comment by Ginalim** [comment]
> Which android emulator extension are you using? Can you paste the extension ID?

Thank you so much for trying to help but the problem is already solve now !🤣😁
