### ISSUE TITLE
Last-registered controller becomes 'suggested' if no other notebook affinity is set

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#146666]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Have a notebook extension that registers multiple controllers, e.g. https://insiders.vscode.dev/github/joyceerhl/vscode-controller-bug
2. Click on the kernel selector
3. :bug: the last controller that was created shows up as 'suggested' (moreover this behavior supersedes an extension-configured NotebookControllerAffinity of Default)
![image](https://user-images.githubusercontent.com/30305945/161438648-bb918ed0-b751-44f7-b475-119572f4e336.png)

 
If the extension did not register an affinity for these controllers, IMO no controller should be suggested.

**Comment by rebornix** [comment]
Already fixed and not reproduceable in latest VS Code.

**Comment by joyceerhl** [comment]
Running the same sample from above, I now get two steps:

![image](https://user-images.githubusercontent.com/30305945/214964272-5df1c504-e568-4ecc-839c-ee5c9287e77d.png)
![image](https://user-images.githubusercontent.com/30305945/214964285-cc8ffbe7-e2b7-417b-92bf-357a8a58188f.png)
