### ISSUE TITLE
[html] Provide a Jinja2 template file formatter

### ISSUE THREAD

**Issue by shibang** [Microsoft/vscode#14665]
- VSCode Version: 1.6.1
- OS Version: All

Steps to Reproduce:
Any Jinja2 template files such as show_entries.html in the picture below:
![show_entries.html](http://7xsjcr.com1.z0.glb.clouddn.com/sp20161028_221728.png)
As you can see, this format is awful.
I hope the code can support for formatting this kind of files,Thanks :)

**Comment by shibang** [comment]
Use this snippet to reproduce:
```html
{% extends "layout.html" %} {% block body %} {% if session.logged_in %}
<form action="{{ url_for('add_entry') }}" method=post class=add-entry>
	<dl>
		<dt>Title:
			<dd><input type=text size=30 name=title>
				<dt>Text:
					<dd><textarea name=text rows=5 cols=40></textarea>
						<dd><input type=submit value=Share>
	</dl>
</form>
{% endif %}
<ul class=entries>
	{% for entry in entries %}
	<li>
		<h2>{{ entry.title }}</h2>{{ entry.text|safe }} {% else %}
		<li><em>Unbelievable.  No entries here so far</em> {% endfor %}
</ul>
{% endblock %}
```
Copy and paste the code above to VSCode and press `Ctrl`+`Shift`+`I`to format it.

**Comment by aeschli** [comment]
Our built-in HTML formatter (based on jsbeautify) doesn't know about Jinja2 directives.

That would be a good opportunity for an extension...

**Comment by totkeks** [comment]
I got the same issue with another HTML templating language (go html/template used for example in Hugo). The question is, should this all be covered by one extension for html templates or should there be an extension (and therefore an issue requesting it) for each type?

```
<ul class="actions pagination">
    {{ if .Paginator.HasPrev }}
        <li><a href="{{ .Paginator.Prev.URL }}"
                class="button big previous">Previous Page</a></li>
    {{ else }}
        <li><a href="#" class="disabled button big previous">Previous Page</a></li>
    {{ end }}

    {{ if .Paginator.HasNext }}
        <li><a href="{{ .Paginator.Next.URL }}"
                class="button big next">Next Page</a></li>
    {{ else }}
        <li><a href="#" class="disabled button big next">Next Page</a></li>
    {{ end }}
</ul>
```

**Comment by york-xtrem** [comment]
There are many template languages based on Curly brackets or braces.

I think a basic general support would not be bad.

**Comment by mjbvz** [comment]
Closing as extension candidate. Please see [this guide](https://code.visualstudio.com/docs/extensions/overview) for information about authoring a language extension
