### ISSUE TITLE
Vs Code won't open v1.66

### ISSUE THREAD

**Issue by Igris-1** [microsoft/vscode#146669]
Vs Code won't open, same with the insider build, I reinstall Vs Code but still does not work

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66
- OS Version: Windows 11 insider build 22581

Steps to Reproduce:

1. Just try to open Vs Code

$ code --verbose
`[9012:0403/143546.738:ERROR:gpu_process_host.cc(983)] GPU process exited unexpectedly: exit_code=-1073741515
[9012:0403/143546.739:WARNING:gpu_process_host.cc(1288)] The GPU process has crashed 1 time(s)
[main 2022-04-03T17:35:46.842Z] [File Watcher (node.js)] Request to start watching: c:\Users\Marce\AppData\Roaming\Code\User (excludes: <none>),c:\Users\Marce\AppData\Roaming\Code\User\settings.json (excludes: <none>)
[main 2022-04-03T17:35:46.958Z] Starting VS Code
[main 2022-04-03T17:35:46.959Z] from: s:\Microsoft VS Code\resources\app
[main 2022-04-03T17:35:46.959Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  'pre-release': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  'ms-enable-electron-run-as-node': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': '16be864a-1504-4585-8ac0-2a574796bd85',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  'disable-dev-shm-usage': false,
  logsPath: 'C:\\Users\\Marce\\AppData\\Roaming\\Code\\logs\\20220403T143546'
}
[main 2022-04-03T17:35:46.963Z] Resolving machine identifier...
[main 2022-04-03T17:35:46.964Z] Resolved machine identifier: 92c8ed3700b62aa2021ea4848d328b378a427b9b08282555ac113763d582b300
[main 2022-04-03T17:35:46.968Z] Main->SharedProcess#connect
[main 2022-04-03T17:35:46.996Z] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat 'c:\Users\Marce\AppData\Roaming\Code\User\settings.json'
[main 2022-04-03T17:35:47.004Z] [File Watcher (node.js)] Started watching: 'c:\Users\Marce\AppData\Roaming\Code\User'
[main 2022-04-03T17:35:47.006Z] StorageMainService: creating global storage
[main 2022-04-03T17:35:47.023Z] lifecycle (main): phase changed (value: 2)
[main 2022-04-03T17:35:47.026Z] windowsManager#open
[main 2022-04-03T17:35:47.027Z] windowsManager#open pathsToOpen [ [Object: null prototype] {} ]
[main 2022-04-03T17:35:47.028Z] windowsManager#doOpenEmpty {
  restore: false,
  remoteAuthority: undefined,
  filesToOpen: undefined,
  forceNewWindow: false
}
[main 2022-04-03T17:35:47.032Z] IPC Object URL: Registered new channel vscode:06143066-a2f9-44df-9756-0fb9961d0ef5.
[main 2022-04-03T17:35:47.032Z] window#validateWindowState: validating window state on 1 display(s) {
  width: 1024,
  height: 768,
  mode: 1,
  x: 128,
  y: -24,
  hasDefaultState: true
}
[main 2022-04-03T17:35:47.033Z] window#validateWindowState: 1 monitor working area { x: 0, y: 0, width: 1280, height: 720 }
[main 2022-04-03T17:35:47.033Z] window#ctor: using window state {
  width: 1024,
  height: 720,
  mode: 1,
  x: 128,
  y: 0,
  hasDefaultState: true
}
[main 2022-04-03T17:35:47.149Z] window#load: attempt to load window (id: 1)
[main 2022-04-03T17:35:47.192Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 0, emptyToOpen: 1)
[main 2022-04-03T17:35:47.193Z] lifecycle (main): phase changed (value: 3)
[main 2022-04-03T17:35:47.230Z] update#setState idle
[main 2022-04-03T17:35:47.230Z] resolveShellEnv(): skipped (Windows)
[main 2022-04-03T17:35:47.356Z] ExtensionHostStarterWorker created
[9012:0403/143547.824:ERROR:gpu_process_host.cc(983)] GPU process exited unexpectedly: exit_code=-1073741515
[9012:0403/143547.824:WARNING:gpu_process_host.cc(1288)] The GPU process has crashed 2 time(s)
[main 2022-04-03T17:35:47.833Z] [File Watcher (node.js)] [raw] ["change"] globalStorage
[main 2022-04-03T17:35:47.833Z] [File Watcher (node.js)] [CHANGED] c:\Users\Marce\AppData\Roaming\Code\User\globalStorage
[main 2022-04-03T17:35:47.838Z] [File Watcher (node.js)] [raw] ["change"] globalStorage
[main 2022-04-03T17:35:47.839Z] [File Watcher (node.js)] [CHANGED] c:\Users\Marce\AppData\Roaming\Code\User\globalStorage
[main 2022-04-03T17:35:47.890Z] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\Marce\AppData\Roaming\Code\User\globalStorage
[9012:0403/143548.538:ERROR:gpu_process_host.cc(983)] GPU process exited unexpectedly: exit_code=-1073741515
[9012:0403/143548.538:WARNING:gpu_process_host.cc(1288)] The GPU process has crashed 3 time(s)
[9012:0403/143548.726:ERROR:gpu_process_host.cc(983)] GPU process exited unexpectedly: exit_code=-1073741515
[9012:0403/143548.727:WARNING:gpu_process_host.cc(1288)] The GPU process has crashed 4 time(s)
[9012:0403/143549.035:ERROR:gpu_process_host.cc(983)] GPU process exited unexpectedly: exit_code=-1073741515
[9012:0403/143549.035:WARNING:gpu_process_host.cc(1288)] The GPU process has crashed 5 time(s)
[9012:0403/143549.221:ERROR:gpu_process_host.cc(983)] GPU process exited unexpectedly: exit_code=-1073741515
[9012:0403/143549.221:WARNING:gpu_process_host.cc(1288)] The GPU process has crashed 6 time(s)
[9012:0403/143549.409:ERROR:gpu_process_host.cc(983)] GPU process exited unexpectedly: exit_code=-1073741515
[9012:0403/143549.409:WARNING:gpu_process_host.cc(1288)] The GPU process has crashed 7 time(s)
[9012:0403/143549.694:ERROR:gpu_process_host.cc(983)] GPU process exited unexpectedly: exit_code=-1073741515
[9012:0403/143549.694:WARNING:gpu_process_host.cc(1288)] The GPU process has crashed 8 time(s)
[9012:0403/143550.613:ERROR:gpu_process_host.cc(983)] GPU process exited unexpectedly: exit_code=-1073741515
[9012:0403/143550.614:WARNING:gpu_process_host.cc(1288)] The GPU process has crashed 9 time(s)
[9012:0403/143550.614:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.`

**Comment by sheridanjoe** [comment]
I had the same issue and "--no-sandbox" worked for me.  YMMV

**Comment by deepak1556** [comment]
Can you attach the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports.

Also to confirm,

* Does the application run fine with `1.65` without additional flags ?
* Does running with `code --disable-gpu` help ?

**Comment by Igris-1** [comment]
*.dmp file with out "--disable-gpu"

- [Report_1.zip](https://github.com/microsoft/vscode/files/8414550/Report_1.zip)

*.dmp file with "--disable-gpu" (same issue)

- [Report_2.zip](https://github.com/microsoft/vscode/files/8414568/Report_2.zip)


It was running fine with 1.65

**Comment by hizeph** [comment]
Same thing happening to me, on Ubuntu 20.04 (5.13.039), worked just fine on `1.65`
Runs fine with `--disable-gpu`, though.

[report.zip](https://github.com/microsoft/vscode/files/8417566/report.zip)

**Comment by joepio** [comment]
Both `--no-sandbox` and `--no-gpu` don't seem to work for me.

```sh
# code --version
1.66.1
8dfae7a5cd50421d10cd99cb873990460525a898
arm64
```
