### ISSUE TITLE
Consider a message and button limit for notifications and dialogs

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#146678]
Refs https://github.com/dotnet/vscode-dotnet-runtime/issues/427

<img width="467" alt="CleanShot 2022-04-03 at 16 46 57@2x" src="https://user-images.githubusercontent.com/35271042/161454258-a90c0529-ed97-45d7-99d0-b0aa08db31be.png">

This is a bad notification but it also seems like we should at least have better limitations so that extensions don't do this in the future. Maybe decreasing the line limit and number of actions?

**Comment by bpasero** [comment]
I am not sure 🤷 , if an extension decides to do this, then why not? If a user thinks this is bad, the user can file a bug or even uninstall the extension. 

I think whatever limit we come up with we might break an extension in some way because either we do not show enough information or hide some buttons arbitrarily. 

What is the recommendation?

**Comment by misolori** [comment]
My question is whether we want to strictly enforce the amount of lines and buttons shown? Like instead of 12 lines going with 8 and instead of 5 buttons maximize at 3? Something that would force extensions to think more carefully about what information is shown to users.

Here's what it looks like if you push notifications to the limit:

<img width="475" alt="CleanShot 2022-04-04 at 09 36 32@2x" src="https://user-images.githubusercontent.com/35271042/161590769-af2a4d58-3e36-4461-8b31-f0db7863f895.png">

**Comment by bpasero** [comment]
Have we tried to reach out to the example above to ask whether they could improve that case?

**Comment by daviddossett** [comment]
Is there any sort of precedent for showing some sort of warning in the code for situations like this? E.g. if someone uses five buttons, we wouldn't necessarily break the extension, but it could show up as a suggestion. I could see that being useful for other areas too.

Character count or line numbers could be tricky depending on zoom, language, etc.

**Comment by misolori** [comment]
@bpasero yes, already filed https://github.com/dotnet/vscode-dotnet-runtime/issues/427

**Comment by bpasero** [comment]
Wouldn't this then have to apply for dialogs as well? Here is a custom dialog with lots of text:

![image](https://user-images.githubusercontent.com/900690/161686285-60d8e1e5-79f8-4fd4-a0e6-290442acec11.png)

And here is a macOS native dialog where the buttons do not seem to have a limit but the content starts to show a scrollbar:

![image](https://user-images.githubusercontent.com/900690/161686363-5e06773d-c229-4a5d-aa06-3f9d950114da.png)

**Comment by bpasero** [comment]
Turning into a UX item, happy to implement when there is consensus what to do with dialogs and notifications. The areas are:
* notifications (toast)
* notifications (center) -> if we wanted to distinguish
* custom dialogs
* native dialogs (Windows, Linux, macOS)

**Comment by misolori** [comment]
I think given that macOS does not limit the message and buttons and handles the overflow, I'm fine closing out this issue since we handle this decently already.
