### ISSUE TITLE
Strange default pick of Intellisense

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#14660]
Intellisense currently has an odd way of picking the default:

![bug](https://cloud.githubusercontent.com/assets/22350/19807607/2cb1c876-9d21-11e6-9fb6-9fda31fb7986.gif)

As I type exactly the beginning (`-moz`) of the first pick when nothing has been typed (`-moz-animation`), I expect the default pick to not change at all.

**Comment by jrieken** [comment]
We currently weight them like this *number of case sensitive matching characters*, *number of case-insensitive matching character*, *distance from start*, and *number of not matching characters*. That it changes is expected and enabling things like cancel case matching, however, the *distance from start* should be weight stronger

**Comment by chrmarti** [comment]
@jrieken It's hard to not find it confusing that `-moz-columns` should be the winner. The lexically earlier `-moz-animation` should get the same ranking based on your description. I cannot mark this as verified, reopening for clarification.

**Comment by jrieken** [comment]
The rule is that the shortest wins when all other scores are equal
