### ISSUE TITLE
Not reflecting changes in source control when using a symbolic link directory

### ISSUE THREAD

**Issue by lorenzohanssens** [microsoft/vscode#146611]
Issue Type: <b>Bug</b>

I have 2 folders, one that runs a webserver for testing purposes (folder A). 
And another one where I edit the code (folder B).
These folders are linked with the "mklink" command in cmd.
(mklink /D "C:\Users\username\Desktop\B" "C:\xampp\A") 

When I open folder B in VSC, everything *seems* to be working properly. 
Until I start editing the code. VSC doesn't seem to pickup any of the changes for Git's source control.

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.22581
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3400G with Radeon Vega Graphics     (8 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.95GB (6.57GB free)|
|Process Argv|C:\\xampp\\htdocs --crash-reporter-id 2def5c9d-aa94-4b68-b7fb-3b1e1e4b27a7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.2
phpserver|bra|3.0.2
bracket-pair-colorizer|Coe|1.0.62
es7-react-js-snippets|dsz|4.4.3
apacheconf-snippets|eim|1.3.0
prettier-vscode|esb|9.5.0
auto-close-tag|for|0.5.14
ftp-sync|luk|0.3.9
rainbow-csv|mec|2.2.0
python|ms-|2022.4.0
vscode-pylance|ms-|2022.3.4
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
powershell|ms-|2021.12.0
csv-to-table|php|1.4.0
material-icon-theme|PKi|4.15.0
vscode-xml|red|0.20.0
vscodeintellicode|Vis|1.2.18

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by lszomoru** [comment]
Thanks for reporting this issue. I was able to reproduce the issue when I open folder B using the CLI (ex: `code .`, or `code B`), but not when I first start VS Code, and then use "File -> Open Folder" and open folder B. This difference in behaviour is related [to these changes](https://github.com/microsoft/vscode/issues/18837#issuecomment-418342604). Then opening a folder using the CLI, the symbolic link is *not resolved*, while when you open the folder using "File -> Open Folder", the symbolic link is *resolved*. 

As it was called it in [this comment](https://github.com/microsoft/vscode/issues/18837#issuecomment-418647766), at the moment the git extension determines the path of the git repository by calling `git --rev-parse --show-toplevel`, which *resolves* symbolic links. I will investigate to see whether there is anything that we can do in the git extension but for the time being you would have to use the workaround to open the folder though the "File -> Open Folder" menu.

**Comment by pacifi5t** [comment]
I have a similar problem. I store my projects inside `$HOME/Projects/path/to/specific/project`. If I create link with `ln -sf $HOME/Projects $HOME/Link` and then open project by navigating through this link, git won't show diffs. This happens regardless of whether I open it using CLI, or using File > Open Folder inside the VS Code.

**Comment by lszomoru** [comment]
The work to add support for symbolic links is tracked in this issue https://github.com/microsoft/vscode/issues/5970. 
I would suggest that you subscribe to that issue in oder to receive notifications when the work is being scheduled.
