### ISSUE TITLE
Comment shortcut in SCSS now using CSS style comments

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#14661]
In prior releases, using the comment/uncomment shortcut (cmd+/) would add SCSS-style line comments in SCSS files `//`.

In this weeks release, the same key command now uses CSS-style comments `/* */`, which I do not want to use.  The `//` comments are not passed through to the final CSS but the other type is.
- VSCode Version: Code - Insiders 1.7.0-insider (1d2d5e089a8261ebb6ad6dfb2e847e5aa1c16f9d, 2016-10-28T11:10:40.281Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

| Extension | Author | Version |
| --- | --- | --- |
| theme-realgithub | NoHomey | 1.0.7 |
| code-settings-sync | Shan | 2.3.3 |
| sort-lines | Tyriar | 1.1.0 |
| html-css-class-completion | Zignd | 1.0.3 |
| html-snippets | abusaidm | 0.0.18 |
| Bookmarks | alefragnani | 0.9.2 |
| project-manager | alefragnani | 0.12.0 |
| theme-atom-one-dark | andischerer | 0.0.1 |
| one-monokai | azemoh | 0.1.14 |
| htmltagwrap | bradgashler | 0.0.3 |
| path-intellisense | christian-kohler | 1.1.0 |
| vscode-eslint | dbaeumer | 1.0.8 |
| tslint | eg2 | 0.5.39 |
| auto-close-tag | formulahendry | 0.3.4 |
| auto-rename-tag | formulahendry | 0.0.7 |
| Angular1 | johnpapa | 0.1.16 |
| vscode-stylefmt | mrmlnc | 2.0.0 |
| nonbreakingspace | smlombardi | 0.0.1 |
| vscode-icons | robertohuertasm | 3.0.6 |
| Theme-GitHubCleanWhite | saviorisdead | 0.0.3 |
| stylelint | shinnn | 0.18.0 |
| theme-tesla | smlombardi | 0.0.1 |
| theme-ayu | smlombardi | 0.0.1 |
| theme-gruvbox | none | 0.0.1 |
| theme-kuroirtheme | none | 0.0.1 |
| theme-firewatch | ulthes | 1.0.2 |
| bootstrap-3-snippets | wcwhitehead | 0.0.7 |
| change-case | wmaurer | 0.4.1 |
| Material-theme | zhuangtongfa | 1.0.3 |

**Comment by aeschli** [comment]
I'm able to reproduce.
model.getModeIdAtPosition returns 'css' for every line. Problem is that the scss to level scope name is 'source.css.scss' and is the top level scope on the stack.
@alexandrudima Just guessing here, but when trying to find an embedded scope, all matches need to be looked at and the longest matching would win, e.g source.css.scss is more specific than source.css

**Comment by alexandrudima** [comment]
Also pushed fix to the `release/1.7` branch.

**Comment by alexandrudima** [comment]
To the verifier:
* Please verify this issue (ctrl+/ in SCSS)
* Please also verify #14962 (div| with tab is no-op in a test.js file with mode JavaScript, div| with tab triggers emmet in a test.js file with mode JavaScriptReact)
* Please also double check that ctrl+/ comments with the correct characters in HTML (with embedded CSS, JavaScript) and in PHP (with php code blocks, with embedded CSS, JavaScript)
