### ISSUE TITLE
Can not debug python code with Anaconda.

### ISSUE THREAD

**Issue by lloydztw** [microsoft/vscode#146602]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66
- OS Version: Windows 10

Steps to Reproduce:

1. install Anaconda
2. use vs code create a .py file just with a single line print('hello world!')
3. press "F5"
4. nothing happens.  the debug action won't start.

**Comment by gjsjohnmurray** [comment]
/extPython

All debugging in VS Code is the responsibility of an extension.
