### ISSUE TITLE
PHP Built In Functions Highlight Bug

### ISSUE THREAD

**Issue by DinosDev** [microsoft/vscode#146659]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Add The Color Customization In VSC Configurations:
```json
    "editor.tokenColorCustomizations": {
        "variables": {
            "foreground": "#bf72e6",
        }
    },
```
2. Create This Simple Class:
```php
<?php

namespace Project\Src;

class Test
{
    public function test()
    {
        $Int = 0;

        return boolval($Int);
    }
}
```

The Syntax Highlight In `boolval($Int)` Will Be Incorrect.

The Dolar Sign ($) Will Be In White

![image](https://user-images.githubusercontent.com/71853418/161433293-3d8ec49c-355c-456d-b539-99814740bf3e.png)

**Comment by JacksonKearl** [comment]
This seems to be specific to the theme you are using. When I try the same in the default theme I see the correct behavior. You can try using `Developer: Inspect Editor Tokens and Scopes` to see if a different color is being applied to the `$`. 

<img width="949" alt="image" src="https://user-images.githubusercontent.com/8586769/161638954-7204dafc-083e-4944-9733-a7451e0e347a.png">
