### ISSUE TITLE
Context Menu Underline Letters

### ISSUE THREAD

**Issue by Sunrise-Sea** [microsoft/vscode#146665]
Issue Type: <b>Feature Request</b>

Hi, 

I wanted a request for a little feature in which the context menu item names could be underlined by letter, like we do in Alt key presses in which after the press, the menubar item words' letters get highlighted which can be accessed through pressing that specific key. Like that, I would appreciate if you add a similar feature in the VS Code's right-click context menu items so that after we press Shift+F10 or even a conventional right-click, the inputs of the keyboard would be accepted by it.

Regards,

Pratyush

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/1792
