### ISSUE TITLE
Markdown Syntax of Strikethrough Highlighting mismatch with preview.

### ISSUE THREAD

**Issue by laazy** [microsoft/vscode#146610]
We have written the needed data int
Issue Type: <b>Bug</b>

1. type `~delete word~`
2. it displayed in editor as ~~delete word~~, same as the github deal with single tilde
3. click `open preview`, it shows as `~delete word~`

As vscode [documents](https://code.visualstudio.com/docs/languages/markdown#_does-vs-code-support-github-flavored-markdown) mentioned, 

> VS Code targets the [CommonMark](https://commonmark.org/) Markdown specification using the [markdown-it](https://github.com/markdown-it/markdown-it) library.

Vscode editor should not treat single tilde as strikethroug according to [markdown-it](https://github.com/markdown-it/markdown-it), and it should act same with preview window.

VS Code version: Code - Insiders 1.67.0-insider (8b7086afdbfd42bf6e7b8c0bb586530bf7cf1396, 2022-04-01T05:16:02.350Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (1.94GB free)|
|Process Argv|--crash-reporter-id 3ca66572-e046-4df9-bfdd-5f4e15550577|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
o your clipboard because it was too large to send. Please paste.

**Comment by laazy** [comment]
what it looks like:
![image](https://user-images.githubusercontent.com/27678339/161674933-5d4b4c9e-36a2-4f0b-8d37-9ce7b4ad59cd.png)

**Comment by babakks** [comment]
@mjbvz I've just submitted a PR for this.

**Comment by Lemmingh** [comment]
Though I also feel very strange about this single-tilde-strikethrough, there are explicit test cases for it.

* <https://github.com/microsoft/vscode-markdown-tm-grammar/pull/101>

I guess it would be best to discuss with the original contributor first, even if it's just a mistake.

**Comment by mjbvz** [comment]
@Lemmingh It's likely an oversight. If the common mark spec says to use two tildes, that's what we should support

**Comment by Lemmingh** [comment]
Yeah, GFM requires two tildes:
https://github.github.com/gfm/#strikethrough-extension-

**Comment by Lemmingh** [comment]
Um, interesting fact:

GFM requires "two tildes", but `cmark-gfm` still accepts "single tilde", which is an intentional mismatch for backward compatibility and causes confusion between implementations.

* <https://github.com/github/cmark-gfm/blob/cf7577d2f74289cb83de0a652afc1a8b08a37036/test/extensions.txt#L502-L533>
* <https://github.com/github/cmark-gfm/issues/71>
* <https://github.com/markedjs/marked/issues/1561#issuecomment-548844317>

Still, aligning with the spec should be the right way.
