### ISSUE TITLE
`editor.debug.action.selectionToRepl` is not available in Command Palette

### ISSUE THREAD

**Issue by ZhuangQu** [microsoft/vscode#146679]
When I press Ctrl+Shift+P to open the command panel and type ">editor.debug.action.selectionToRepl", it shows "No matching commands". So I can't execute this command by Ctrl+Shift+P. I can only bind a shortcut key to this command and then execute it via the shortcut key. I think this is a bug that the command panel search is incomplete.

**Comment by gjsjohnmurray** [comment]
Please edit this issue title to become:
```
`editor.debug.action.selectionToRepl` is not available in Command Palette
```

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/95395#issuecomment-614754776 indicates it may already be there and you just need to know what the command text is.

**Comment by ZhuangQu** [comment]
> Please edit this issue title to become:
> 
> ```
> `editor.debug.action.selectionToRepl` is not available in Command Palette
> ```

OK, but according to my observation, there are other commands that cannot be found in the panel. For example, "repl.action.copyAll".

**Comment by ZhuangQu** [comment]
> [#95395 (comment)](https://github.com/microsoft/vscode/issues/95395#issuecomment-614754776) indicates it may already be there and you just need to know what the command text is.

The problem I raised is different from him. His problem is that the shortcut key does not work after binding. My problem is that I can't find the command in the command panel. In fact, some other commands cannot be found, indicating that the search of the command panel is incomplete.

**Comment by gjsjohnmurray** [comment]
Some commands never appear in the Command Palette because they define their `when` clause as `false`

**Comment by ZhuangQu** [comment]
> Some commands never appear in the Command Palette because they define their `when` clause as `false`

I open the page where I set the keyboard shortcut and see that their when clause is - not false.

**Comment by gjsjohnmurray** [comment]
Sorry, I wasn't clear. This is what I am referring to.

https://code.visualstudio.com/api/references/contribution-points#Context-specific-visibility-of-Command-Palette-menu-items

**Comment by ZhuangQu** [comment]
> Sorry, I wasn't clear. This is what I am referring to.
> 
> https://code.visualstudio.com/api/references/contribution-points#Context-specific-visibility-of-Command-Palette-menu-items

I read your link and I probably understand. Please set the when clause of "editor.debug.action.selectionToRepl" to "inDebugMode" instead of false. This is more in line with our needs.

**Comment by gjsjohnmurray** [comment]
Looks like that command is missing from here:

https://github.com/microsoft/vscode/blob/d6e89ba74f5c36b765fd1a47fbc12a8ec441c070/src/vs/workbench/contrib/debug/browser/debug.contribution.ts#L102-L119

`editor.debug.action.selectionToWatch` is also missing.

**Comment by gjsjohnmurray** [comment]
I will submit a PR

**Comment by ZhuangQu** [comment]
> I will submit a PR
Thanks!

**Comment by ZhuangQu** [comment]
> I will submit a PR

Thanks!
