### ISSUE TITLE
Debug Console line height too small and cutting off text

### ISSUE THREAD

**Issue by neelkarma** [microsoft/vscode#146652]
Issue Type: <b>Bug</b>

1. Run any task that prints to the debug console.
2. Observe.

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.94GB (0.90GB free)|
|Process Argv|. --crash-reporter-id eef08711-51c9-4626-a958-f234e2ce714c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.24.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by neelkarma** [comment]
Screenshot for more context:
![image](https://user-images.githubusercontent.com/59462098/161429220-45157173-9093-47d0-b341-10396fe63ce4.png)
This is running with only the C# extension enabled. However, the same issue happens with Flutter workspaces, or any workspace that uses the debug console.

Also, this issue isn't specific to the latest release, I've been having it for a while now.

**Comment by roblourens** [comment]
Can you share your settings? Are you sure you don't have `debug.console.lineHeight` set?

**Comment by neelkarma** [comment]
Turns out I had `debug.console.lineHeight` set to 6 and that was causing everything. Thanks and sorry for the inconvenience.
