### ISSUE TITLE
Format on Save, makes JSON file growing more and more

### ISSUE THREAD

**Issue by ThePlenkov** [Microsoft/vscode#14667]
- VSCode Version: 1.6.1
- OS Version: Windows 7

Steps to Reproduce:
1. Open Settings.json
2.  Press Alt+Shift+F, some empty lines are added between parameters
3. Press again - it's starts stretching more

**Comment by aeschli** [comment]
@ThePlenkov Can you paste the content of the settings.json where I can reproduce this. What are the tab and new line settings?

**Comment by aeschli** [comment]
Same as #14623?

**Comment by ThePlenkov** [comment]
Hi Martin!

Yes - it's exactly same problem.

**Comment by aeschli** [comment]
Thanks. Marking as duplicate of #14623
