### ISSUE TITLE
Sync User Snippet doesn't work

### ISSUE THREAD

**Issue by fschenkun22** [microsoft/vscode#146645]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.660 (user setup)
- OS Version:Windows11 专业版 22H2  OS version 22581.200 

Steps to Reproduce:

1.Build a new code snippets on this computer
2.Check the configuration:Settings Sync Configure ,User Snippets is ON
3.Turn on sync on another computer，New code snippet not found
PS:Other synchronizations such as Themes are well synchronized, only the code snippets are out of sync, and there is no prompt for failure

**Comment by sandy081** [comment]
> Build a new code snippets on this computer

May I know how are you creating the snippets? Can you please check if these snippets exist in the location where your user settings file is located?
