### ISSUE TITLE
Cannot paste content in terminal using mouse's middle key (scroll key)

### ISSUE THREAD

**Issue by NewtMa** [microsoft/vscode#146603]
Issue Type: <b>Bug</b>

1. double click some content elsewhere to hightlight/select it.
2. click mouses's middle key to try to paste the content into the terminal.

The expected result is the content is paste in the terminal, which is expected from most terminals.

The actual result is nothing happened.

I think this is a regression. 

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.36.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.72GB (34.86GB free)|
|Process Argv|--crash-reporter-id f7c2a68f-41ba-4829-8fcb-5c986209fdb6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|ssh-remote+7b22686f73744e616d65223a2243656e744f535f375f456167616e227d|
|OS|Linux x64 3.10.0-1160.36.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz (2 x 2593)|
|Memory (System)|7.64GB (5.47GB free)|
|VM|100%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.1
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.2.2
docs-article-templates|doc|0.2.12
docs-markdown|doc|0.2.110
docs-preview|doc|0.3.58
githistory|don|0.6.19
gitlens|eam|12.0.5
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
comment-anchors|Exo|1.9.6
vscode-firefox-debug|fir|2.9.6
code-runner|for|0.11.7
shell-format|fox|7.2.2
linuxkeybindings|fre|1.58.0
remotehub|Git|0.28.0
go|gol|0.32.0
CppSnippets|har|0.0.15
vue-snippets|hol|1.0.4
plantuml|jeb|2.17.2
better-cpp-syntax|jef|1.15.13
svg|joc|1.4.17
vscode-leetcode|Lee|0.18.0
bash-ide-vscode|mad|1.12.1
python|ms-|2022.4.0
vscode-pylance|ms-|2022.3.4
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.2
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.78.0
remote-wsl|ms-|0.66.0
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
hexeditor|ms-|1.9.5
remote-repositories|ms-|0.4.0
autodocstring|njp|0.6.1
vetur|oct|0.35.0
vscode-commons|red|0.0.6
vscode-xml|red|0.20.0
LiveServer|rit|5.7.5
bash-debug|rog|0.3.9
vue-helper|she|2.4.7
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.18
vscode-icons|vsc|11.10.0
markdown-all-in-one|yzh|3.4.0

(2 theme extensions excluded)

</details>

**Comment by meganrogge** [comment]
I don't see anything like this for the terminals in the panel. That's likely the issue

https://github.com/microsoft/vscode/blob/86cc884a9e1742a3fddd4e8c36b20cbf198d7260/src/vs/workbench/contrib/terminal/browser/terminalEditor.ts#L134-L140
