### ISSUE TITLE
IntelliSense doesn't work depending on direction of selection

### ISSUE THREAD

**Issue by safrankamate** [microsoft/vscode#146637]
Issue Type: <b>Bug</b>

Happy path:
1. Open a file with any code where IntelliSense can be used
2. Highlight an identifier, moving the cursor from LEFT to RIGHT
3. Press Ctrl + Space
4. IntelliSense will open and offer the correct and relevant suggestions

Steps to reproduce bug:
1. Open a file with any code where IntelliSense can be used
2. Highlight an identifier, moving the cursor from RIGHT to LEFT
3. Press Ctrl + Space
4. IntelliSense will open but the suggestions will be irrelevant to the selection

Language used: JavaScript / TypeScript
Extension: none, built-in support.

Code sample: Any amount of JavaScript code containing an identifier. E.g:
```
document
```

Upon highlighting the identifier `document` from left to right and pressing Ctrl+Space, the IntelliSense suggestions are:
```
document
Document
DocumentFragment
DocumentTimeline
DocumentType
```

Upon highlighting the identifier from right to left and pressing Ctrl+Space, the IntelliSense suggestions are sometimes a list of all global identifiers, and sometimes just seemingly random. This happens with any identifier.

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:41.156Z)
OS version: Linux x64 5.13.0-37-generic snap

**Comment by jrieken** [comment]
Missing: small code sample and language used, extension providing intellisense

**Comment by safrankamate** [comment]
Updated description

**Comment by jrieken** [comment]
Thanks for the update, I understand what you mean

> Upon highlighting the identifier from right to left and pressing Ctrl+Space, the IntelliSense suggestions are sometimes a list of all global identifiers, and sometimes just seemingly random. This happens with any identifier.

IntelliSense works with a position, not a selection. So when selecting RTL the position that's being used is in front of an identifier (`document` in this case), not at a word end when selecting LTR. This is how it usually works because by default IntelliSense only overwrites word starts, not word ends. Still forwarding @mjbvz to see if there is anything specific for JS/TS and this case

**Comment by mjbvz** [comment]
This sounds like the expected behavior to me for the reason @jrieken explained: intellisense is based on the current position and not a selection. I don't think we would want to specialize this behavior only in JS/TS
