### ISSUE TITLE
Support cell-level custom context from extensions

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#146686]
Notebook extensions often need to set a cell-level context for actions that are different per-cell. Currently there is no way to do that, except for workarounds like changing the global context based on the currently selected cell.

Examples: Run by line, https://github.com/microsoft/vscode/issues/146353

Currently extensions can use the `setContext` command to set global context values. Custom trees allow setting a single context value on individual items with the `contextValue` property. I think that only the tree provider can set this. In notebooks we would ideally allow different extensions to set different context key/values on a cell.

**Comment by roblourens** [comment]
We could do a low-impact thing like extending the setContext command to allow setting a value within a certain cell sub-context.

```ts
commands.executeCommand('setContext', 'jupyter.runByLineInProgress', true, { cellUri: cell.uri });
```

Or real API on NotebookCell

```ts
export interface NotebookCell {
	setContext(key: string, value: any): void;
}
```

**Comment by roblourens** [comment]
It was pointed out that we can pretty much do this without new API, maybe using an array context key and the "in" operator: https://code.visualstudio.com/api/references/when-clause-contexts#in-conditional-operator

We have a set of 'resource' context keys which are bound to the editor resource URI, but not the cell URI. Cell URIs are the document URI plus some fragment. I could bind those keys to the cell URI, or add a new set (like `resource` -> `cellResource`) if it might interfere, like if cell URIs diverge more from the document URI.

Also, the fragment is not exposed. The `resource` key is a URI but I can't use this with a custom context key from `setContext` because it can only do object-equality. That can be fixed.

So to give an example, one scenario is 

- VS Code binds the existing resource keys to the cell URI
- the extension contributes a menu item with `"when": "resource in jupyter.runByLineCells"`
- the extension runs something like
`executeCommand('setContext', 'jupyter.runByLineCells', [cell.uri])`
- and the menu item shows up in the cell toolbar

**Comment by jrieken** [comment]
@roblourens Do you want this to be something per notebook document or per notebook editor?

**Comment by roblourens** [comment]
Per document. So the same cell in split editors gets the same menu items.

**Comment by roblourens** [comment]
I think I would actually add a new context key, `cellResource`, as the cell's URI, just to make sure that there is never a conflict with `resource`, for adding a menu item to the cell menu based on the notebook document's URI.

**Comment by roblourens** [comment]
Verification: use "inspect context keys" to check that there is a cellResource key on the cell, and is a toString'd cell URI with fragment

**Comment by connor4312** [comment]
Verified there was a variable `notebookCellResource`
