### ISSUE TITLE
Disable inserting spaces around leading semicolon

### ISSUE THREAD

**Issue by ackvf** [microsoft/vscode#146620]
With vscode formatting setting
```
"typescript.format.semicolons": "remove"
```
and eslint rules,
```
"semi-style": ["error", "first"],
"semi-spacing": "error"
"indent": ["error", 2],
```

I get this automatic `eslint --fix`,

```ts
// before
console.log('hi');
(something ??= {_default: 0})[key] = 1

// after 
console.log('hi')
;(something ??= {_default: 0})[key] = 1
^ ..... this is desired
```

which is then auto-formatted by vscode to this,
```ts
console.log('hi')
  ; (something ??= {_default: 0})[key] = 1
^^ ^ ..... spaces inserted, undesired
```

which in turn raises this eslint error.
```
Expected indentation of 14 spaces but found 16. eslint(indent)
```

https://github.com/eslint/eslint/issues/15752 Rule Change: semi-spacing for leading semicolon

**Comment by mjbvz** [comment]
Formatting is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
