### ISSUE TITLE
Opening random file erases editor state

### ISSUE THREAD

**Issue by MattGrdinic** [microsoft/vscode#146668]
Issue Type: <b>Bug</b>

Say you've been working on a project and have a multiple editors active, some split vertically, some pinned, etc. If you restart using the icon in the dock / TaskBar the editor state is maintained for that project, aka everything remains the same with regard to open editors, layout, and so on. 

Now quite VS Code and open a random file using VS Code as the target. 

Instead of VS code opening that file within the conetxt of the project it
maintains the EXPLORER window showing your projects folder contents, but every editor window has been closed and only the file you've just opened is displayed. 

What should happen is the application asks before it closes your custom layout, or it simply opens this new file as a new tab in say.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (16.66GB free)|
|Process Argv|-psn_0_520319 --crash-reporter-id 003c8b33-7671-417a-832e-8c09d7f0354c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.4
vscode-intelephense-client|bme|1.8.2
xml|Dot|2.5.1
vscode-great-icons|emm|2.1.84
php-debug|xde|1.25.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
pynewfile477cf:30450039

```

</details>

**Comment by bpasero** [comment]
Try: `window.restoreWindows: "preserve"`

**Comment by MattGrdinic** [comment]
From that settings' description it sounds like it's exactly what I'm after, so thank you for that! 

If I had to nit the Restore Windows option names of `all` (default) and `preserve` are a bit intuitive. If the option names can't be revisited I'd say a much safer option would be to default to `preserve`.
