### ISSUE TITLE
User settings Issue

### ISSUE THREAD

**Issue by AjayBoreddy** [microsoft/vscode#146619]
Issue Type: <b>Performance Issue</b>

Hello,
In my users settings.json file, I am facing an issue with the editor.tokencolorCustomizations continuously shows issues whenever I install any extensions regarding my project. Even I tried to reinstall it again but it shows the same error " End of file expected " i am not understanding this error.Could you please help me out the with the issue?

Thanks,
Ajay Kumar 

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.42GB free)|
|Process Argv|--crash-reporter-id b814e811-32b3-4681-8363-340576772a76|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    3	   100	 13608	code main
    0	   119	  3668	   extensionHost
    0	     4	  2932	     cmd /s /c ""c:\Users\bored\.vscode\extensions\ms-dotnettools.csharp-1.24.3\.omnisharp\1.38.2\OmniSharp.exe" -z -s "c:\ASP PROJECTS\Data structures" --hostPID 3668 DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin c:\Users\bored\.vscode\extensions\ms-dotnettools.csharp-1.24.3\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll FileOptions:SystemExcludeSearchPatterns:0=**/.git FileOptions:SystemExcludeSearchPatterns:1=**/.svn FileOptions:SystemExcludeSearchPatterns:2=**/.hg FileOptions:SystemExcludeSearchPatterns:3=**/CVS FileOptions:SystemExcludeSearchPatterns:4=**/.DS_Store FileOptions:SystemExcludeSearchPatterns:5=**/Thumbs.db FormattingOptions:EnableEditorConfigSupport=true formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4"
    0	    85	 12784	       "c:\Users\bored\.vscode\extensions\ms-dotnettools.csharp-1.24.3\.omnisharp\1.38.2\OmniSharp.exe"  -z -s "c:\ASP PROJECTS\Data structures" --hostPID 3668 DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin c:\Users\bored\.vscode\extensions\ms-dotnettools.csharp-1.24.3\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll FileOptions:SystemExcludeSearchPatterns:0=**/.git FileOptions:SystemExcludeSearchPatterns:1=**/.svn FileOptions:SystemExcludeSearchPatterns:2=**/.hg FileOptions:SystemExcludeSearchPatterns:3=**/CVS FileOptions:SystemExcludeSearchPatterns:4=**/.DS_Store FileOptions:SystemExcludeSearchPatterns:5=**/Thumbs.db FormattingOptions:EnableEditorConfigSupport=true formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
    0	    11	 14344	       console-window-host (Windows internal process)
    0	    87	  6884	     "C:\Users\bored\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\bored\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=3668
    0	    99	  8592	   shared-process
    0	    72	 12464	     ptyHost
    0	    77	 15020	     fileWatcher
    0	    40	  8976	   utility-network-service
    0	   185	 11160	   window (settings.json - Data structures - Visual Studio Code)
    1	   147	 11392	   gpu-process
    0	    26	 12776	   crashpad-handler
    3	    88	 13132	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (settings.json - Data structures - Visual Studio Code)
|    Folder (Data structures): 1 files
|      File types: cs(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
csharp|ms-|1.24.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30465022
pynewfile477:30463512

```

</details>

**Comment by rzhao271** [comment]
\gifPlease

**Comment by AjayBoreddy** [comment]
Thanks for the quick response. I have recorded my issue and hope you may understand the issue that I am facing. Let me know if you need any clarification on the issue.

Please find the attachment
![Recording 2022-04-05 at 10 06 33](https://user-images.githubusercontent.com/96489284/161680039-736e0fc3-c4ab-4370-9ff1-0a69147effb4.gif)

**Comment by rzhao271** [comment]
The setting needs to go in an object. Can you try wrapping what you have in your settings.json with {} characters? Example:
```json
{
   "editor.tokencolorCustomizations": {
    }
}
```
