### ISSUE TITLE
Test state not getting reset after test run ends

### ISSUE THREAD

**Issue by KaravolisL** [microsoft/vscode#146623]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.67.0-insider (user setup)
Commit: 8b7086afdbfd42bf6e7b8c0bb586530bf7cf1396
Date: 2022-04-01T05:16:02.350Z
Electron: 17.3.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:
I have an extension that is creating a TestController object and creating a few TestItems. I have an additional contributed menu item (inline) that triggers a command for the selected TestItem. In this command, I am creating a TestRunRequest with the clicked TestItem in this included tests. I'm then creating a TestRun with the request and ending the run.

The documentation for `end` states "Any tests included in the run whose states have not been updated will have their state reset." I'd expect that the clicked test item's state would be reset in this case, but it isn't.

I've uploaded a simple extension that demonstrates the problem here: https://github.com/KaravolisL/simple-test-extension
Please let me know if any more information is needed. Thanks!

**Comment by connor4312** [comment]
Hi, thanks for the issue and repro! I'm not sure I see what you're seeing -- when I run the item, its state remains in the default state after a run:

![Recording 2022-05-02 at 15 35 20](https://user-images.githubusercontent.com/2230985/166337761-3465d7fb-1f35-40e1-b5e7-30226fd744b0.gif)
 
Note that if you had _previously_ run the test, then whatever state it was in before will be remain shown. The default state is called "unset", and for each test VS Code will shown the most recent _not_ unset state as its result. Could that explain what you're seeing?

**Comment by KaravolisL** [comment]
I should have been more specific with my steps. I'm first running the test by clicking the "play" button. This causes the test's state to change to passed in this case. When I click the additional menu item, I expected the test's state to go back to "unset" since it's state had not been updated in the test run.

Your last note seems to suggest my understanding is incorrect, and it's expected that the test will maintain it's previous state. Is there any way for an extension to set a test item's state back to "unset" then?

**Comment by connor4312** [comment]
Not right now. Most test runners update the test states to "skipped" if they didn't get run. Will think about this.
