### ISSUE TITLE
autocomplete is very slow

### ISSUE THREAD

**Issue by Ivanivy** [microsoft/vscode#146635]
Issue Type: <b>Performance Issue</b>

When i'm typing now specificaly coding in react auto complete is really slow, it was not the case before and i have not added a particular extension, i just synced my old extension

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz (6 x 2195)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.18GB free)|
|Process Argv|--crash-reporter-id 0f37a409-78ad-4db3-8aee-fee5c3469522|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   102	  9648	code main
    0	   254	  2164	   window (● DashboardPage.jsx - dr_manager - Visual Studio Code)
    1	   371	  6384	   extensionHost
    0	    86	  3164	     "C:\Users\ivan\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\ivan\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js --node-ipc --clientProcessId=6384
   16	    33	  8968	     c:\Users\ivan\.vscode\extensions\ms-vscode.cpptools-1.9.7\bin\cpptools.exe
    0	    10	 11720	       console-window-host (Windows internal process)
    0	   316	 12280	     "C:\Users\ivan\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\ivan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\ivan\AppData\Local\Temp\vscode-typescript\1e4416fcec86447a97d4\tscancellation-b4569e16d050dd7fda66.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	    97	 12076	       "C:\Users\ivan\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:/Users/ivan/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/ivan/AppData/Local/Microsoft/TypeScript/4.6 --enableTelemetry --typesMapLocation "c:/Users/ivan/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typesMap.json" --validateDefaultNpmLocation
    0	   134	 15228	     "C:\Users\ivan\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\ivan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName C:\Users\ivan\AppData\Local\Temp\vscode-typescript\1e4416fcec86447a97d4\tscancellation-9e8526692068b412fe33.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	    31	  9376	   crashpad-handler
    0	   100	 10776	   shared-process
    0	    58	  3132	     ptyHost
    0	    83	  5148	     fileWatcher
    0	    40	 11092	   utility-network-service
    1	   120	 11116	   gpu-process
    1	    86	 14272	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● DashboardPage.jsx - dr_manager - Visual Studio Code)
|    Folder (dr_manager): 58 files
|      File types: ttf(12) js(8) png(7) jsx(7) json(2) gitignore(1) ico(1)
|                  html(1) txt(1) md(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
vscode-sqlite|ale|0.14.0
laravel-extra-intellisense|ami|0.6.2
beautify-blade|api|1.0.1
vscode-twig-pack|baj|1.1.0
vscode-intelephense-client|bme|1.8.2
laravel-goto-view|cod|1.3.7
doxdocgen|csc|1.4.0
bulma|dem|0.0.9
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.5
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
bulma-snippets|fia|0.0.4
laravel-create-view|gli|0.0.6
todo-tree|Gru|0.0.215
laravel-blade-wrapper|IHu|1.0.1
better-cpp-syntax|jef|1.15.13
vscode-JS-CSS-HTML-formatter|lon|0.2.3
dotenv|mik|1.0.1
python|ms-|2022.4.0
remote-containers|ms-|0.231.2
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.78.0
remote-wsl|ms-|0.66.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5449
vscode-react-native|msj|1.9.2
sqltools|mtx|0.23.0
sqltools-driver-sqlite|mtx|0.2.0
laravel-goto-components|nao|1.2.0
laravel-blade|one|1.32.0
laravel-extension-pack|one|1.1.0
laravel5-snippets|one|1.15.0
material-icon-theme|PKi|4.15.0
LiveServer|rit|5.7.5
laravel-artisan|rya|0.0.28
vscode-blade-formatter|shu|0.13.15
vscode-smoothtype|spi|1.2.0
cmake|twx|0.0.17
vscode-arduino|vsc|0.4.11
php-debug|xde|1.25.0
material-theme|zhu|3.13.20
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by yotam707** [comment]
+1

**Comment by brown-chris** [comment]
+1 
Especially evident/painful if running in a VM and it appears to be 'Code Helper (Renderer)' that is pegging the CPU?

Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:04.419Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 19.6.0

**Comment by mjbvz** [comment]
@yotam707 Please open a separate issue to track your case

**Comment by Ivanivy** [comment]
Thanks for your concern, my vscode is always updating and up-to-date,  but i'll try to do so. But recently i discovered that the issue is linked to the react version. I  recently opened an old react project folder, things are going normally inside but the newer one no. Sorry for my english i'm actually a french man.

**Comment by mjbvz** [comment]
@Ivanivy Can you please share a list of steps we can follow to see the issue? Also please try creating a small project we can download for testing this
