### ISSUE TITLE
Go to definition not works in nodejs

### ISSUE THREAD

**Issue by DDavo** [Microsoft/vscode#1466]
In sublime if you have two files open and if you have a function in one and use "go to definition" option it finds in the open files and it puts the cursor there.

**Comment by bpasero** [comment]
@DDavo are you saying you expect goto definition to go to the second editor or is it not working at all in VS Code? Can you attach samples?

**Comment by DDavo** [comment]
It not working in VS Code. I do click in goto definition and nothing occurs

**Comment by bpasero** [comment]
@DDavo can you attach the files where you expect it to work?

**Comment by DDavo** [comment]
I have my function1 

![sin titulo](https://cloud.githubusercontent.com/assets/5210735/11914704/c350e95c-a654-11e5-9bc0-16586a852d43.png)

and my function1 is in another file there

![sin titulo](https://cloud.githubusercontent.com/assets/5210735/11914738/149d7e56-a655-11e5-80de-65fdea58887c.png)


I expect that if in the first file I do click "goto definition"  in function1  it goes to the second file (that should  it is already opened) and it puts the cursor in the function1

**Comment by bpasero** [comment]
@DDavo thanks, can you attach the full source too, it would be interesting to see the lines to the top where you define imports.

**Comment by jrieken** [comment]
Our current JS language service cannot do that yet

**Comment by jrieken** [comment]
As we now ship with project Salsa this should work.
