### ISSUE TITLE
[html] unnecessary 'semicolon expected' errors

### ISSUE THREAD

**Issue by yxranger** [microsoft/vscode#146607]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

After install the latest update, I got errors like this:
![360截图20220402161117812](https://user-images.githubusercontent.com/102851798/161373783-c40e7449-e615-4b24-951a-ed4077665b58.png)
But it's totally fake errors !
this problem confuse me several day 
needs help

**Comment by aeschli** [comment]
Caused by https://github.com/microsoft/vscode/commit/56661ec16af5c0f61a05fdd3ca86efa997016e7b
