### ISSUE TITLE
jsdoc typedef (strange behaviour)

### ISSUE THREAD

**Issue by udarkness** [Microsoft/vscode#14664]
I cannot autocomplete a property of an object after its first use
- VSCode Version: 1.6.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. Write this code in a Js file:

```
/**
 * @typedef {Object} My
 * @property {boolean} yes
 */

/**
 * @param {My} my
 */
function a(my) {
    my.yes
}
/**
 * @param {My} my
 */
function b(my) {
    my.
}
```
1. try to autocomplete in the function a. Works fine, as expected
2. try to autocomplete in the function b. It doesn't work at all

**Comment by waderyan** [comment]
@udarkness thank you for opening this issue. I have reproduced this using the latest Insider build. Migrating to the JavaScript language service repo (TypeScript).

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#12004
