### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by EngNASRELDEEN** [microsoft/vscode#146640]
Thank you for your great application (visual studio code), my feedback "i wish if you can make me arrange the style code css by alfh bet a b c d e f g ..etc by one click or order in the app  it will be very useful"

**Comment by anthroid** [comment]
Try installing the [Sort Lines](https://marketplace.visualstudio.com/items?itemName=Tyriar.sort-lines) extension. You can select several lines and right-click > Sort Lines, or press `F9`. For CSS specifically, you could try [Sort CSS Properties](https://marketplace.visualstudio.com/items?itemName=apriliandi246.css-sort) and see if it does what you need.
