### ISSUE TITLE
A feature in the search tab that is about ignoring search results if they contain a certain string

### ISSUE THREAD

**Issue by ollie-iterators** [microsoft/vscode#146664]
Sometimes, I am searching though the code to fix some code by searching for all instances of the code. Sometimes when I fix the code that I want to be fixed, then the result is still there in the list of search results. It would be good if there were a feature that could have the text that I want it to change into so that it could ignore the changed code so that the code is not accidentally altered again.

For example, if you were commenting out some code by searching for it, you could say ignore the search results: # code that you are searching for, or whatever method that there is of commenting out a single line of code in the programming language that is being used.

**Comment by roblourens** [comment]
You can write a regex that matches your query and doesn't match what it will change into. Or, use the X button to delete results.

We also have this request which is related: https://github.com/microsoft/vscode/issues/118128
