### ISSUE TITLE
A wired behavior with Arabic text

### ISSUE THREAD

**Issue by WatheqAlshowaiter** [microsoft/vscode#146674]
Issue Type: <b>Bug</b>

I noticed wired behavior with Arabic text, with selection, editing, and writing.. 

it was fone in VS Code but now it is bad. I hope you fix it as soon as possible.

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin x64 20.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 11, 13|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|2.7.0
vscode-css-formatter|aes|1.0.2
laravel-model-snippets|ahi|2.0.0
Bookmarks|ale|13.2.4
vsc-export|asl|1.2.0
vscode-intelephense-client|bme|1.8.2
path-intellisense|chr|2.8.0
laravel-goto-view|cod|1.3.7
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|4.4.3
vscode-babel-coloring|dza|0.0.4
gitlens|eam|12.0.5
vscode-html-css|ecm|1.11.0
EditorConfig|Edi|0.16.4
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|9.5.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
copilot|Git|1.11.5453
todo-tree|Gru|0.0.215
vue|jcb|0.1.5
vscode-peacock|joh|4.0.1
php-cs-fixer|jun|0.2.10
advanced-arabic-lorem|Kam|1.0.0
php-constructor|Meh|0.1.2
php-namespace-resolver|Meh|1.1.8
laravel-intellisense|moh|0.2.0
vscode-docker|ms-|1.21.0
python|ms-|2022.4.0
vscode-pylance|ms-|2022.3.4
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.2
vscode-typescript-tslint-plugin|ms-|1.3.4
php-docblocker|nei|2.7.0
vscode-extension-auto-import|Nuc|1.4.3
vetur|oct|0.35.0
laravel-blade|one|1.32.0
laravel5-snippets|one|1.15.0
material-icon-theme|PKi|4.15.0
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.7.5
partial-diff|ryu|1.4.3
vscode-blade-formatter|shu|0.13.15
sonarlint-vscode|Son|3.3.3
autoimport|ste|1.5.4
code-spell-checker|str|2.1.11
rainbow-tags|vol|0.4.1
blox|vsb|1.0.5
vscode-wakatime|Wak|18.0.8
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.25.0

</details>

**Comment by gjsjohnmurray** [comment]
Is https://github.com/microsoft/vscode/issues/146537#issuecomment-1085919167 relevant?

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/99589 . I believe you are running into a problem that is caused by the way whitespace is rendered (inline with the actual text) and is triggered when using `editor.renderWhitespace` : `all` or `selection`. The workaround is to configure `editor.renderWhitespace` : `boundary`, `trailing` or `none`.

**Comment by WatheqAlshowaiter** [comment]
@gjsjohnmurray  Yes it is the same problem.
