### ISSUE TITLE
Messing up RTL strings after selecting

### ISSUE THREAD

**Issue by AmirHKiani98** [microsoft/vscode#146682]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.65.2 (user setup) 
- OS Version: Windows_NT x64 10.0.22000 (Windows 11)

Steps to Reproduce:

1. Write a Persian/Arabic/Any other RTL language string
2. Select them! you will see the selection is not 

Explanation:

There are lots of reported issues regarding RTL here. Therefore, there is a slight chance that I miss some of them.

Recently, I had to reinstall windows 11 on my machine. So, after that, I had to install VSCode again (therefore, I have the most recent version of VSCode).

Now, whenever I select any Persian sentences (strings) in my code, the IDE shows a messed-up string that is far away from the correct one. I can not show the correct and incorrect sentences as texts here because copying and pasting results in the correct format. Therefore, I have to provide them as images. (Sorry for any inconvenience, in advance)

#### Correct Persian Sentence
[![Correct Image][1]][1]

#### Incorrect Persian Sentence (After selecting)
[![Incorrect Image][2]][2]

This might be a little bit tricky to understand for people who are not familiar with the Persian Language. The difference can be understood by looking at the first word after `$creatorId` in both images.

This also might happen if we wanted to write in Arabic or other right-to-left languages.

It would be highly appreciated if you could suggest anything to avoid this.

  [1]: https://i.stack.imgur.com/AQEDk.png
  [2]: https://i.stack.imgur.com/nrr6K.png

**Comment by gjsjohnmurray** [comment]
Is https://github.com/microsoft/vscode/issues/146537#issuecomment-1085919167 relevant?

**Comment by alexdima** [comment]
@saeed410 The render whitespace in selection is tracked at https://github.com/microsoft/vscode/issues/99589 and the indentation being to the right is tracked at https://github.com/microsoft/vscode/issues/146354
