### ISSUE TITLE
Explore how to better intergrate remote file system providers

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#146688]
Tracking UX explorations for improving the integration of remote fs providers such as OneDrive or Google Drive.

Ref: [OneDrive Browser extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.onedrive-browser)

**Comment by daviddossett** [comment]
Exploring some early ideas that builds off the existing Remote Repositories contribution to the Explorer's welcome view:

## Quick Pick

This basically outlines a flow where an extension could add items to the quick pick launched via the Remote Repositories extension. The extension would contribute the quick pick item and then handle auth from there. After that, it basically looks like any other remote folder opened up in restricted mode:

https://user-images.githubusercontent.com/25163139/162332162-7ecaeb50-a7f6-4c80-b206-c3cfc32b526a.mp4

## Split Button

Alternatively, there could be a version where we use a split button to expose the remote folder/repo options. I don't think this would scale quite as well, but it's worth including here in case it inspires any other idea:

<img width="563" alt="CleanShot 2022-04-07 at 15 53 57@2x" src="https://user-images.githubusercontent.com/25163139/162332496-b9ce7915-5928-4cc5-b597-bf2f583d0500.png">

cc @misolori — I may be somewhat off the mark here re: integrating with the Remote Repositories extension. I don't know if it makes sense to somehow allow extensions to contribute to that extensions quick pick. Maybe it needs to be extracted out to core and all extensions, including remote repos, contribute to a generic quick pick? Not sure yet.

**Comment by gjsjohnmurray** [comment]
What about the scenario where I already have a local folder open and I want to add a FileSystemProvider folder to it? Will the OneDrive / Google Drive extensions support such hybrid multi-root workspaces?

Two extensions I contribute to add commands to the Explorer context menu adjacent to the standard "Add Folder to Workspace..." one:

![image](https://user-images.githubusercontent.com/6726799/162393897-02a84a22-41e6-47ee-b96b-6db7aee6f5e6.png)

To handle the "no folder open" case they contribute to Explorer's welcome view:

![image](https://user-images.githubusercontent.com/6726799/162395865-9f76a7c7-878b-4da8-8c92-11dba53a0bd8.png)


One of these (Serenji) also contributes to the quickpick which appears when clicking on the "Open a Remote Window" panel on the status bar.

Here are its entries when no folder/workspace is yet open:

![image](https://user-images.githubusercontent.com/6726799/162394619-7677ea80-19dd-4b41-ad32-893e713621ea.png)

And here when a folder is already open:

![image](https://user-images.githubusercontent.com/6726799/162395070-f3ebd8a2-efd5-42a9-b2b6-8a317bd15c13.png)

@daviddossett I wonder if your split button idea would better suit the "Open Folder" button. Clicking the main part of the button would continue to open the Open Folder dialog for the local workstation. The dropdown part would list contributions from extensions such as the two I work on.

**Comment by daviddossett** [comment]
@gjsjohnmurray Yeah, I wonder if things like OneDrive/Google Drive should instead be considered folders like your examples above. That makes more sense since these aren't really repositories in a formal sense. It also means we can keep the existing multi-root patterns in place.

If that were the case, extending the "Open Folder" contribution(s) would make sense. That could look something like:

![CleanShot 2022-04-08 at 11 30 54](https://user-images.githubusercontent.com/25163139/162500999-debcad86-8ade-4de3-ac5d-0f1b5388f317.gif)

Alternatively, it could use the quick pick like this. I wouldn't prefer this option since the 80%+ case suffers from the second step of adding a quick pick. Worse, if no extensions contribute to that quick pick, we would probably need to default to the behavior today (e.g. just opening the local fs) which would be more efficient, but not very predictable if you had interacted with both flows.

![CleanShot 2022-04-08 at 11 38 58](https://user-images.githubusercontent.com/25163139/162501953-34cb9b01-dada-438e-990a-8024a124e0bb.gif)

Lastly, we could also think about folding the "Open Remote Repository" button into the split button options. This ends up as a bit of a kitchen sink but I'm exploring how we could have something of an "Open anything" model.

![CleanShot 2022-04-08 at 11 49 18](https://user-images.githubusercontent.com/25163139/162503516-4fae60f1-d5c8-4141-ab12-839bcf8a06e8.gif)

**Comment by gjsjohnmurray** [comment]
I like the split button rather than the quickpick.

I think "Clone Repository" is significantly different from the other options, in that its effects on your local workstation persist after VS Code is closed (there's a cloned folder in the local filesystem).

**Comment by daviddossett** [comment]
Yep, good point 👍

**Comment by daviddossett** [comment]
Closing given no other activity here. Will reopen if we revisit it in the future.
