### ISSUE TITLE
strcmp in vs code windows

### ISSUE THREAD

**Issue by thuwalk** [microsoft/vscode#146618]
I'm getting 1 as the output in the program below.
#include <stdio.h>
#include <string.h>

int main() {int i=0;
    char str1[] = "gggg";
    char str2[] = "aaaa";
    i=strcmp(str1,str2);
    printf("%d\n",i);

    return 0;
}
'strcmp' is only outputing -1,0 and 1.
Can anyone help.

**Comment by roblourens** [comment]
This sounds like an issue with your program, not with vscode, sorry.
