### ISSUE TITLE
Extensions are not loading even after several restarts.

### ISSUE THREAD

**Issue by datablazor** [microsoft/vscode#146752]
We have written the needed data into your clipboard because it was too large to send. Please paste.

<img width="1598" alt="Screen Shot 2022-04-04 at 1 33 15 PM" src="https://user-images.githubusercontent.com/23362828/161599548-91c91820-fae4-4671-9ffa-62d2787e7e7e.png">

**Comment by datablazor** [comment]
It worked once I uninstalled the Application and re-installed it. It would be great if it gets fixed as well in the next release.

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to identify which extension is causing this. Then report the issue to the extension author. The Report Issue option on the Start menu can help if you pick the correct entry from the "File on" dropdown.
