### ISSUE TITLE
Inconsistent nomenclature SCM <-> "Source Control"

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode#146723]
Within the UI in VS Code there are differing names for the SCM view depending on whereabouts you are in the UI.

Under the "View Menu" there is an entry from "SCM" but everywhere else it is referred to as Source Control. (Hovering over the icon in the activity bar names it Source Control, the view container title says Source Control and in the command palette, the command is listed as "Source Control: Focus on Source Control View".)

Then under settings there is a group "Features > SCM"

For consistency, it would be better to keep with a single (user facing) name that is used in all places.

**Comment by Z-E-D** [comment]
I don't like using of abbreviations in the program GUI, especially if they are not as much popular and known. It took me a while to understand what is that SCM thing.

**Comment by joaomoreno** [comment]
Yeah the correct term is _Source Control_. SCM is just an internal name, should not be surfaced.

**Comment by a-stewart** [comment]
I've pushed a small PR that should rename this in all the places I could find.

**Comment by lszomoru** [comment]
Merged! @a-stewart, thank you very much for the contribution!
