### ISSUE TITLE
Unable to get installed npm package completions via IntelliSense

### ISSUE THREAD

**Issue by harryio** [Microsoft/vscode#14673]
Although I've created a default jsconfig.json file in the project root. Using VsCode version 1.6.1!

Edit:
VScode Version: 1.6.1
OS: ArchLinux

Steps to reproduce:
Initialize a demo project with npm init
Save lodash with npm install --save lodash
Open the folder in vscode
Initialize default jsconfig.json
Restart VSCode
Try CTRL + Space but no suggestions after requiring lodash as a variable

**Comment by weinand** [comment]
@harryio please provide VSCode Version, OS Version, and most importantly: steps for how to reproduce.

**Comment by harryio** [comment]
@weinand updated the description!

**Comment by waderyan** [comment]
@harryio thank you for opening this issue. Can you share your workspace so I can reproduce on my end?  It looks like you have not installed types for lodash. 

You can install lodash typings with this command

```
npm install --save @types/lodash
```

As described in this blog. 
https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

**Comment by harryio** [comment]
@waderyan seems to work after installing the typings! Is there a way to automate this?

**Comment by waderyan** [comment]
Not in 1.6 but in 1.7 there will be. Look for the new release later today!

**Comment by harryio** [comment]
Some timing.
