### ISSUE TITLE
 After a long time, the window pops up and does not respond

### ISSUE THREAD

**Issue by jumploop** [microsoft/vscode#146794]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.66.0 (user setup)
- OS Version:Windows_NT x64 10.0.19043

Steps to Reproduce:

1.Open multiple windows
2.wait
![image](https://user-images.githubusercontent.com/38637799/161686788-1363deb4-7f62-45d5-8870-36f89dcbe913.png)

**Comment by gjsjohnmurray** [comment]
> Does this issue occur when all extensions are disabled?: Yes/No

/needsMoreInfo (see above)
