### ISSUE TITLE
Mac trackpad behaving like Windows

### ISSUE THREAD

**Issue by temocj** [microsoft/vscode#146745]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0
- OS Version: macOS 12.3

Rapid trackpad taps within the editor (to select a word or line) followed by dragging with 1 finger causes the selection to be expanded as I drag.

Note: this is with the **Tap to click** (tap without pushing the trackpad button) system setting enabled.

**No other Mac software behaves like this.** Dragging to change a selection normally requires pushing down on the trackpad button or using 3 fingers! This issue is slowing me down.

Steps to Reproduce:

1. Quickly tap two or three times on some code.
2. Quickly start dragging on the trackpad.

What I expect: to select a word (2 taps) or line (3 taps) and then move the cursor (1-finger drag).
What happens: a word or line is selected, but then the selection keeps changing along with the cursor's position, until I let go of the trackpad.

**Comment by fk1blow** [comment]
i can confirm that this is happening to me as well, and worked correctly on macOS 12.3, prior to vscode 1.66.0.
Related to this bug, i found out that there's some sort of a timeout which disables drag to selection after a short amount of time(although it 's still frustrating to have to wait so i don't get selection expanded).

**Comment by alexdima** [comment]
Let's track in #146486
