### ISSUE TITLE
Timeline: Long commit message pushes important info out of view

### ISSUE THREAD

**Issue by RandScullard** [microsoft/vscode#146747]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0
- OS Version: Windows 10 Pro 21H2

When you edit a file and display the Timeline panel, if there is a long commit message for the file, the message pushes the author and date/time information out of view to the right. You need to scroll to the right to see this important info:

![image](https://user-images.githubusercontent.com/4718759/161592336-4071911f-b2f9-4bd5-8c39-b77473876f38.png)
![image](https://user-images.githubusercontent.com/4718759/161592786-a07674b2-d2b0-4042-aeee-ba93b3e81a03.png)

The Timeline should truncate long commit messages to avoid this. Sometimes I work on projects where best practice on commit messages has not always been followed. Even a single long commit message is enough to make the Timeline much more awkward to work with.

Note: If you're only interested in local file history, you can work around this problem by turning off Git History in the Timeline panel, but this is not an ideal solution.

**Comment by lramos15** [comment]
I'm having trouble reproducing this. Here's my timeline with a local history entry and a super long commit message.
<img width="695" alt="image" src="https://user-images.githubusercontent.com/4544166/162791331-3ba9a838-f82b-4f0d-80a4-5faf2301ac66.png">

**Comment by JacksonKearl** [comment]
Agree,
<img width="866" alt="image" src="https://user-images.githubusercontent.com/8586769/162793188-b10f2190-6f4e-4768-b0d3-cbd8f12f0ebe.png">

<img width="680" alt="image" src="https://user-images.githubusercontent.com/8586769/162793246-5bf1d02a-7658-4e54-b382-91aa5edeb16e.png">

**Comment by JacksonKearl** [comment]
@RandScullard if you still see this on latest Insiders we can reopen and look into what might be different in your case.

**Comment by RandScullard** [comment]
@JacksonKearl I just tried it on Insiders and the problem does not appear there. Looks like it is already fixed. Thanks for your help!
