### ISSUE TITLE
Terminal tabs: should reset the tab name to the default value when no name is provided

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#146796]
```
  1) VSCode Smoke Tests (Electron)
       Terminal
         Terminal Tabs
           should reset the tab name to the default value when no name is provided:
     Error: Timeout: get element '.single-terminal-tab' after 20 seconds.
      at poll (D:\a\_work\1\s\test\automation\src\code.ts:120:10)
      at Code.waitForElement (D:\a\_work\1\s\test\automation\src\code.ts:264:10)
      at Terminal.assertTabExpected (D:\a\_work\1\s\test\automation\src\terminal.ts:191:5)
      at Terminal.assertSingleTab (D:\a\_work\1\s\test\automation\src\terminal.ts:126:3)
      at Context.<anonymous> (src\areas\terminal\terminal-tabs.test.ts:68:4)
```

Here are some builds (Windows, desktop):
* https://dev.azure.com/monacotools/Monaco/_build/results?buildId=164879&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=d239d20c-b192-5a3e-69bb-696f63b250a5&l=117
* https://dev.azure.com/monacotools/Monaco/_build/results?buildId=165000&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=d239d20c-b192-5a3e-69bb-696f63b250a5&l=117
* https://dev.azure.com/monacotools/Monaco/_build/results?buildId=164929&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=d239d20c-b192-5a3e-69bb-696f63b250a5&l=117

And found actually one in browsers:
* https://dev.azure.com/monacotools/Monaco/_build/results?buildId=164887&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=0699ae84-7245-5a45-5eee-80b086af2725&l=103

**Comment by bpasero** [comment]
Interestingly this test seems to flake more in the new playwright based desktop tests, but I was lucky to find a web case too.

**Comment by bpasero** [comment]
[playwright-trace-1-should_reset_the_tab_name_to_the_default_value_when_no_name_is_provided.zip](https://github.com/microsoft/vscode/files/8415570/playwright-trace-1-should_reset_the_tab_name_to_the_default_value_when_no_name_is_provided.zip)

**Comment by deepak1556** [comment]
@meganrogge this test has failed again in a recent run https://dev.azure.com/monacotools/Monaco/_build/results?buildId=277305&view=logs&j=4801dce2-64f3-53d6-b366-d49a1977c639&t=d3816dfe-5f5f-5b74-f77f-0a43291213b6. Reopening for triage.

**Comment by meganrogge** [comment]
terminal panel never even opens 🤔 

![Image](https://github.com/user-attachments/assets/b55a1581-84bc-4468-974f-cf260b5c90ee)
