### ISSUE TITLE
Remote Extension Host keeps terminating

### ISSUE THREAD

**Issue by elizaench16** [microsoft/vscode#146791]
Issue Type: <b>Bug</b>

Every time I ssh into my school's HW server, as soon as I open a folder, I get a notice that "Remote Extension Host has terminated 3 times in the past 5 minutes", which usually leads to me losing connection to the server, which sometimes in turn make VSCode crash

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.53.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (4.45GB free)|
|Process Argv|--crash-reporter-id 16a4786a-daec-4367-9e2a-3db0b52bf955|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: homework.cs.tufts.edu|
|OS|Linux x64 3.10.0-1160.53.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4214Y CPU @ 2.20GHz (6 x 2194)|
|Memory (System)|15.51GB (1.46GB free)|
|VM|100%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
latex-workshop|Jam|8.24.1
vsliveshare|ms-|1.0.5449
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vscode-scheme|sjh|0.4.0
vscode-better-sml|sto|0.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by alexdima** [comment]
@elizaench16 Could you please provide the following logs:
* show the output panel using `View > Output`
* from the dropdown in the output panel:
  * Log (Window)
  * Log (Remote Server) 
  * Log (Remote Extension Host)

**Comment by elizaench16** [comment]
I deleted the vscode server on remote and set it back up and it seems to work now

**Comment by alexdima** [comment]
@elizaench16 Thank you for your reply. Please let us know if this happens again, and if it does, please try to capture the logs I mentioned above, as those might be revealing of what could be going on.
