### ISSUE TITLE
Error installing extension behind corporate proxy

### ISSUE THREAD

**Issue by nickletgo** [Microsoft/vscode#14672]
- VSCode Version: 1.6.1
- OS Version: Win7 SP1

Error message:

> write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:c:\jenkins\workspace\electron-win-ia32\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:794:

Steps to Reproduce:
1. Added http.proxy in workspace settings 
2. added http.proxyStrictSSL= false
3. Click to install an extension from marketplace

What I've tried:
1. Tried `npm config set registry http://registry.npmjs.org/`
2. Tried with and without "http.proxyStrictSSL": false
3. both npm and git works with the http.proxy settings, only VS code is not working

![image](https://cloud.githubusercontent.com/assets/3857964/19818580/5f8ba800-9d1e-11e6-8618-1b8f41a02c41.png)

**Comment by joaomoreno** [comment]
What does your `http.proxy` setting look like?

**Comment by nickletgo** [comment]
It is just like what is in the screenshot, however, I can't give you the exact proxy url due to company policy. And I used the same proxy for github and npm. They both work so I'm not sure why it doesn't for vs code.

**Comment by joaomoreno** [comment]
Make sure that if you have an HTTPS proxy you use that instead of the HTTP proxy. Confirm the `http.proxy` value with your network administrator.

More reading:

- http://stackoverflow.com/questions/15421050/node-request-getting-error-ssl23-get-server-hellounknown-protocol
- https://github.com/request/request/issues/478
- http://stackoverflow.com/questions/15166950/unable-to-establish-ssl-connection-how-do-i-fix-my-ssl-cert

**Comment by nickletgo** [comment]
Thanks, I will check with my network admin, but can you please help me understand what the issue is by answering my several questions?

- Is the vs code extension (e.g. the C# extension) installed via npm? 
- If it is npm, does vs code use a shipped version of npm instance or the one already installed in my OS? If it is the former case, can I directly configure proxy to that shipped version of npm and make it work? If it is latter case, why it doesn't work for vs code when my local copy of npm is already configured with proxy and works in visual studio 2015 and command line. 
- Does vs code extension installation have to be a https request? which means I have to have a https proxy to make it work?

**Comment by joaomoreno** [comment]
The issue seems to be that you configured an HTTP proxy, but Code is accessing HTTPS resources. So there is a protocol error (`EPROTO`).

Extensions are not installed via npm, but via Code itself.

**Comment by nickletgo** [comment]
Got it. So does it mean I have to use a https proxy and configure "https.proxy" in order to in order to install extensions? Does Code have a http resource for extension installation?

**Comment by joaomoreno** [comment]
No, just `http.proxy` will do. Just make sure your proxy handles HTTPS.

**Comment by markdav** [comment]
I have the same problem..   workspace setting is:

// Place your settings in this file to overwrite default and user settings.
{
    "http.proxy": "http://myproxy:8080",
    "http.proxyStrictSSL": false
}

VS Code: 1.8.1

**Comment by maxbet1507** [comment]
I have the same problem under my Windows and vscode 1.10.

Seems,
- gallary use internet explorer proxy configuration, and need to input username and password.
  buf vscode doesn't have such dialog. so always failed.
- http.proxy and http.proxyStrictSSL configuretions will be used only for installling extention...

**Comment by joaomoreno** [comment]
Can you help us out in #22214 ?
