### ISSUE TITLE
VSCode 1.66 slow, laggy when re-focusing/switching back to editing from another window or program

### ISSUE THREAD

**Issue by lorand-horvath** [microsoft/vscode#146737]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0
- OS Version: Windows 7 SP1 x64

Steps to Reproduce:

1. Open any JS file and then switch window/focus to another app (e.g. a browser)
2. Switch/focus back to VSCode JS file and it takes about 2 seconds to be able to edit. It's some kind of lag, it takes time until you can start editing again.

**Comment by lorand-horvath** [comment]
Also this popup appears when I try to close VSCode, it stays on for 20-30 seconds. This has never occurred with 1.65.x or older versions.
![image](https://user-images.githubusercontent.com/72015221/161729168-5c08d5a4-f4e1-4033-995a-c2a1ff346732.png)

**Comment by lorand-horvath** [comment]
@sandy081 @deepak1556 Latest VSCode 1.66.0 is getting ridiculously slow after a while, there must be some kind of memory leak happening. It's unresponsive for a few seconds when I click back into the editor from another program.

Is there anything to be done? How can I help? I don't want to reinstall the previous version 1.65.2, which did not exhibit this slow responsiveness. Nothing changed in my setup since 1.65.2, only change was the VSCode update to 1.66.0.

**Comment by deepak1556** [comment]
Can you start the application with `--disable-features=CalculateNativeWinOcclusion` commandline flag and check if the issue repros. It is very likely the process is put into a suspended state due to the occlusion tracker from the runtime.

**Comment by lorand-horvath** [comment]
@deepak1556 Will do. In the meantime, I've checked the Performance tab in vscode devtools and I think I've found the task that takes 2+ seconds when I re-focus in the main vscode editor window.
It's called `xterm-addon-webgl.js` https://www.npmjs.com/package/xterm-addon-webgl

**Comment by lorand-horvath** [comment]
@deepak1556 I've tested with `> code --disable-features=CalculateNativeWinOcclusion`
It seems to be quite faster to re-focus from another program, so that seems to do the trick. But I've also noticed it is very slow to open a file if I right click in Windows Explorer on a file and Open with VScode - it takes about 3-4 seconds to open it in VSCode.

Why is the CalculateNativeWinOcclusion feature slowing things down when re-focusing? What can be done to fix the slowness?

**Comment by lorand-horvath** [comment]
Can we please add this issue to March 2022 Recovery (1.66.1) milestone?

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/123257

**Comment by lorand-horvath** [comment]
@deepak1556 I think the issues reported in the merged ticket #123257 are not the same problems that I reported here, because the slugish behavior only started with VSCode 1.66 and I haven't noticed any of that in previous versions.

Can we keep this issue opened independently from #123257 please? At least until the problem is tracked down properly.
Or I might have to revert to 1.65.2 in order to be able to work on my projects at all.

**Comment by xPaw** [comment]
I'm seeing the same problem on 1.66 which is new. Another thing that happens is while Code is starting, it first looks like a Windows 7 titlebar until it finally loads, as well as the "closing the window is taking a bit longer".

Neither of these issues happened before.

**Comment by deepak1556** [comment]
titlebar issue is captured in https://github.com/microsoft/vscode/issues/146683, please follow that issue for updates.

**Comment by lorand-horvath** [comment]
@deepak1556 Do you think the bump to Electron 17.4.0 https://github.com/microsoft/vscode/commit/10ab34ddd888b852c92ba9516959ee9e786226db will help? Quite a few relevant bugs fixed... https://github.com/electron/electron/releases/tag/v17.4.0

**Comment by deepak1556** [comment]
Nope they are unrelated, occlusion tracking for windows is performed by https://source.chromium.org/chromium/chromium/src/+/main:ui/aura/native_window_occlusion_tracker_win.cc and there have been some changes between Chromium 91 and Chromium 98 which would have caused this regression.

Can you share a screen capture of the exact steps that show the issue, it would help me to repro the issue on my end. Also, are you running VSCode in a virtual desktop environment ?

**Comment by lorand-horvath** [comment]
@deepak1556 It would be difficult to show the issue with a screen capture. It's actually very simple: click away from VSCode into another window, e.g. the Chrome browser and then click back from Chrome into VSCode on a particular workspace tab and it takes about 2-3 seconds for it to become active and to be able to edit anything.
Also, when I close the main VSCode window, a `Closing the window is taking a bit longer...` message appears as I mentioned https://github.com/microsoft/vscode/issues/146737#issuecomment-1088504285 and @xPaw confirmed https://github.com/microsoft/vscode/issues/146737#issuecomment-1090717425

I'm not running VSCode in a virtual desktop environment. It's just a dual monitor Win 7 x64 setup, nothing fancy.

I have just tried with the updated version 1.66.1, still it has the same behavior. I've noticed it's still using Electron 17.2 which is known to be buggy. You bumped it up to 17.4 yesterday https://github.com/microsoft/vscode/commit/10ab34ddd888b852c92ba9516959ee9e786226db - why is it not included in the latest release? Will it at least be included in April's 1.67 release?
I might just have to revert to 1.65.2 until May.

**Comment by lorand-horvath** [comment]
This is really getting frustratingly slow! Not only is it slow on re-focus to the main window, but very sluggish when opening a current working folder.... first, it starts with showing the dreaded `Closing the window is taking a bit longer...` for a few seconds and then it takes 10-15 more seconds to open a folder.

This software used to be quick and snappy and I'm not sure what exactly happened with the 1.66.x version - you cannot use it in production anymore. Is it not bothering anyone else?

**Comment by lorand-horvath** [comment]
Downgraded to 1.65.2 (Electron 13.5.2 and Chromium 91) - it's fast and responsive.

**Comment by deepak1556** [comment]
@lorand-horvath can you open a separate issue for the terminal rendering issue, it is unrelated to the occlusion tracker causing the render process to be suspended for extended period.

**Comment by lorand-horvath** [comment]
@deepak1556 I can, of course, but I think the issues I'm seeing are actually caused by the WebGL2 not being supported for some reason in 1.66 and not the occlusion tracker.

VSCode 1.65 did not warn about missing WebGL2 support. Any ideas?

**Comment by deepak1556** [comment]
In https://github.com/microsoft/vscode/issues/146737#issuecomment-1090060681 you had indicated that `--disable-features=CalculateNativeWinOcclusion` helps with the response time, is that not the case ?

WebGL2 support depends on whether your gpu is blacklisted by chromium or not, you can check by launching with `--ignore-gpu-blacklist`

**Comment by lorand-horvath** [comment]
@deepak1556 @bpasero  Alright, I've been testing thoroughly today... 1.66.0 and 1.66.2 comparatively.

1.66.0 was very slow to react when switching from a browser to VSCode - approx 2-3 seconds lag. Then, as I mentioned above, starting with `code --disable-features=CalculateNativeWinOcclusion` improved the situation, the lag was barely noticeable.

1.66.2 behaves a bit differently. The default behavior out of the box shows some improvement, the lag is about 1 second when starting with `code`. But disabling the occlusion calculation with `code --disable-features=CalculateNativeWinOcclusion` does not seem to help much. The 1 second lag is still present, maybe a tad bit more responsive, I can't really tell the difference.

So things have been improved visibly from 1.66.0 to 1.66.2, but still not as responsive as 1.65.2 was.

On the other hand, restarting my computer solved the WebGL2 problem. DeveloperTools doesn't show the missing WebGL2 support warning. So, as you said, the GPU blacklist has nothing to do with this slowness/lag behavior.

If I can provide more information, please let me know.

**Comment by lorand-horvath** [comment]
@deepak1556 ?

**Comment by icedterminal** [comment]
> I might have to revert to 1.65.2 in order to be able to work on my projects at all.

This does indeed work around the sluggish nature. 

Startup takes 3x as long, showing the window frame without comp.

https://user-images.githubusercontent.com/4755734/163755597-6585edd6-bb1d-443d-b723-f7ebf766c186.mp4

[I too get this often](#issuecomment-1088504285). One of the reasons I adore this app is because it's so fast. I have no slouch of a system (3700X/2080) so this kind of performance degradation is definitely poor code.

**Comment by deepak1556** [comment]
@lorand-horvath can you share a screen recording comparing what you see as lag between `1.65` and `1.66`, from the original issue there is lag when switching between instances caused by the occlusion tracker, if there is also an issue with startup performance can you share the numbers following https://github.com/microsoft/vscode/wiki/Performance-Issues#read-the-startup-timers for both `1.65` and `1.66`

**Comment by j3mdamas** [comment]
Hi,
I use vscode and 1.66.2 was impossible to use, like described here. I've downgraded to 1.65.2 like @lorand-horvath suggested, and it's perfect. I am using snap, and at some point during an upgrade, it became like this. I thought it was on NFS, so I didn't pay attention to it, but now I tested more and it was sluggish an any GUI action, basically unusable.
I am a bit tight on time until next Tuesday to reinstall 1.66.2 and provide the logs for Performance issues, but I'll try to come back then with them. For now, I'll have to work with the version revert.

**Comment by lorand-horvath** [comment]
@deepak1556 I've already said that it's difficult to show the lag in a video. I will wait for 1.67 to be released, I guess it will come with the newer Electron version that hopefully fixes the issues. Otherwise, 1.65.2 it is!

**Comment by deepak1556** [comment]
I will merge this to https://github.com/microsoft/vscode/issues/123257 for the occlusion tracker related regressions, although the issue here started with Electron 17 update, we will have more of these regressions as long as the renderer throttling is aggressive. I will see if we can make it less aggressive for the desktop application.

**Comment by lorand-horvath** [comment]
@deepak1556 Is there anything to be done about this other problem, which seems to be somewhat related to the lag issues? Namely, when closing VSCode, it takes about 20 seconds with this spinner waiting for something:

![image](https://user-images.githubusercontent.com/72015221/165715538-a66b6948-a0bf-4bb6-a93e-71e19f6255b3.png)

**Comment by deepak1556** [comment]
/cc @bpasero for the above dialog

@lorand-horvath can you check if the dialog appears with https://code.visualstudio.com/insiders ?

**Comment by bpasero** [comment]
The two main components that contribute to this dialog have either moved out of the window into the majn process (storage), or now store periodically (timeline history), so I would expect insiders to improve this situation.

Besides, in insiders you now see the name of the component that slows down shutdown.

**Comment by lorand-horvath** [comment]
@deepak1556 @bpasero I've just tested 1.67 and sorry to say, the lag and slowness when switching from Chrome to a VSCode tab is exactly the same as in 1.66+. Last version without this issue is 1.65.2.

Just checked 1.67 comes with Electron 17.4.1, but there are newer versions 17.4.2 and even 17.4.3.... wonder if it could be updated?

**Comment by lorand-horvath** [comment]
Electron 17.4.3 https://github.com/electron/electron/releases/tag/v17.4.3

**Comment by vhscom** [comment]
This just began happening to me in a big way today. I'd thumbs up the issue but it's blocking my entire programming workflow and downgrading to March had no effect. I'm using Monterey 12.4 beta 4 on a 2019 MBP.

**Comment by vhscom** [comment]
> Also this popup appears when I try to close VSCode, it stays on for 20-30 seconds.

Started seeing this pop-up over the last few weeks time-to-time on a 2019 MBP. When I bumped up to the April 2022 release I started seeing it consistently when closing windows. And I'm also getting about a 10 second lag between code changes and visual feedback in TypeScript on the same machine running the April (and March, after I tried a rollback) releases.

**Comment by isidorn** [comment]
Thanks for filling this issue, but it seems to be reported for Win7 which we do not support https://code.visualstudio.com/docs/supporting/requirements#_platforms

Can you reproduce with Win11 or Win10?
Thanks!

**Comment by lorand-horvath** [comment]
@isidorn Ouch, it seems you've silently dropped support for Win 7 between February and April, at least according to web.archive

I will try Windows 10 maybe next year... but for now I'll stay on Win 7 and revert to VSCode 1.65.2. Thanks for the heads up!

**Comment by j3mdamas** [comment]
I experience it on Ubuntu, through snap install.

**Comment by lorand-horvath** [comment]
> I experience it on Ubuntu, through snap install.

That's interesting, tell us more details, please.

**Comment by icedterminal** [comment]
@lorand-horvath I'm not sure why Windows 7 was even brought up. Doubtful of the relevance of this statement. This is quite perplexing to me. If you think about, I wouldn't be in this thread if I weren't having the issues already outlined. I use Windows 10. Gave an example video showing how much slower the current release got on launch. That is 100% reproducible. The pop up saying it's taking longer to close and the lagging is sporadic in nature and not 100% reproducible. It can happen within 10 minutes of being open or it can take several hours. When you pointed out a specific version to use, I reverted and have yet to experience what's been outlined.

I'll have to upgrade to the current release and keep a replay buffer going recording my working sessions.

**Comment by lorand-horvath** [comment]
@icedterminal I agree with what you're saying/observing. Windows 7 has nothing to do with this issue. It can be convenient to sweep the issue under the "Windows 7 is not supported anymore" rug, now that support has been silently and suddenly dropped for it (VSCode 1.66+ sometimes around April 2022).

Since upgrading to 1.67 I don't get the "Closing the window is taking a bit longer" popup anymore, which is good. But the 2 second lag & slowness to respond when re-focusing from another program onto a VSCode tab is still there and it's honestly starting to drive me nuts. Anybody can imagine testing your bundled JS code in Chrome and when you click back to VSCode to edit your code, well... you have to wait 2 seconds for it to become responsive. Every. Single. Time. It's just crazy!

Note 1: Starting VSCode with `code --disable-features=CalculateNativeWinOcclusion` doesn't help at all anymore. It only worked in 1.66 which used Electron 17.2 Since VSCode 1.67 with Electron 17.4 it just doesn't make any difference whether you add the flag or not.

Note 2: Is there any way for me to reopen this issue? It has been closed by @deepak1556 and now I can't open it anymore, even if I was the one opening it in the first place. Please don't tell me to open another issue.... that's just not a productive way of tracking down and fixing bugs.

**Comment by lorand-horvath** [comment]
> I will merge this to #123257 for the occlusion tracker related regressions, although the issue here started with Electron 17 update, we will have more of these regressions as long as the renderer throttling is aggressive. I will see if we can make it less aggressive for the desktop application.

@deepak1556 Can you please reopen this issue, since it's not caused by the native occlusion tracker, it seems. Please read my comment right above this one. Is there anything to be done about this problem, which, as you can see, occurs also under Windows 10 and Ubuntu as mentioned above. Can we try Electron 16 or 18 or even roll back to 13.5.2 which didn't have any slowness up to VSCode 1.65.2?

**Comment by deepak1556** [comment]
@icedterminal please open a separate issue for the slow startup issue and provide the numbers following the steps at https://github.com/microsoft/vscode/wiki/Performance-Issues#read-the-startup-timers. This issue was originally opened for unresponsiveness when focusing VSCode from another application which is different from the issue you are describing.

@lorand-horvath as mentioned in https://github.com/microsoft/vscode/issues/146737#issuecomment-1123622008 if you can repro the issue on newer windows then we can reopen the issue to further investigate it with ETW profiles. Windows 7 is not officially supported by Nodejs or Electron, so there could be other system calls added in newer versions that could cause the slowdown in your case, occlusion tracker was just one element to the cause to be tested.

**Comment by icedterminal** [comment]
@deepak1556 Thanks for the response

> This issue was originally opened for unresponsiveness when focusing VSCode from another application

I realise that. Nuking `%AppData%\Code` which had ballooned to 300mib solved the slow down on launch with v1.66 and later, where as it didn't matter with 1.65 and earlier.

That said I still do experience the lag between application focusing (Alt + Tab) and taking longer to close. It's just so random and inconsistent. I have installed 1.67 and will use a replay buffer to catch it when and if it happens.

**Comment by lorand-horvath** [comment]
> Nuking `%AppData%\Code` which had ballooned to 300mib solved the slow down on launch with v1.66 and later, where as it didn't matter with 1.65 and earlier.
> 
@icedterminal Good point! I'll uninstall VSCode completely and nuke the `%AppData%/Code` as well - it's 360 MB in my case... lots and lots of cached files in there AFAICS. Then will do a clean install of 1.67.2 when it comes out, hopefully today.

**Comment by lorand-horvath** [comment]
@deepak1556 As you can see, this issue happens on Linux and Windows 10 as well, so blaming it on Windows 7 is not a solution.

**Comment by isidorn** [comment]
@skaldesh thanks for commenting. Can you please open a new issue following steps from https://github.com/microsoft/vscode/wiki/Performance-Issues#read-the-startup-timers
Feel free to ping me on the new issue @isidorn and then we can take it from there. Thanks a lot!

**Comment by lorand-horvath** [comment]
@isidorn Thanks for your comment, but this is not about the startup lag. I see several comments from you and other developers asking for the startup performance assessment, but we have to first realize that what I reported here is about focusing back to VSCode from another program, after VSCode has been started. It has nothing to do with any startup lag or startup-related issues.

**Comment by lorand-horvath** [comment]
@deepak1556 Can you create an insiders build with Electron 18 or 19 so we can test? I bet the problem is caused by Electron 17 specifically, since it only appeared since Electron 17 has been in use.

**Comment by skaldesh** [comment]
@lorand-horvath is right, the startup of VSCode is fast. Refocusing to an already started instance is what causes the freezes

**Comment by isidorn** [comment]
@lorand-horvath you are correct, this might not be about startup lag. So @skaldesh when filling a new issue you do not have to strictly follow those steps, just provide as much detail as possible. Thank you

As for the Electron 18 and 19 build, this is something which we have on the plan in the future. This will be reflected on our iteration plan. As soon as we have something you should be able to try it out. Thanks!

**Comment by skaldesh** [comment]
Will do :) Thanks

**Comment by lorand-horvath** [comment]
> As for the Electron 18 and 19 build, this is something which we have on the plan in the future. This will be reflected on our iteration plan. As soon as we have something you should be able to try it out. Thanks!

@isidorn Thanks for this information, I'm definitely looking forward to testing a VSCode based on Electron 18+

**Comment by lorand-horvath** [comment]
@deepak1556 @isidorn I have good news - I have finally managed to solve this problem on Windows 7 x64.

The solution to get rid of the slowness and get back the snappiness and quick reaction when focusing back to VSCode from another program is to uninstall VSCode, restart the PC and completely remove the folder `C:\Users\[User]\AppData\Roaming\Code`, which in my case had 380 MB and several thousand files cached in it. The folder has grown so much during 2 years of daily VSCode use, with regular upgrading to newest version as soon as it was released.

After reinstalling VSCode, that folder is now only 80 MB and contains 550 files. Working with VSCode is a breeze again...

**Comment by lorand-horvath** [comment]
@deepak1556 @isidorn I have good news - I have finally managed to solve this problem on Windows 7 x64.

The solution to get rid of the slowness and get back the snappiness and quick reaction when focusing back to VSCode from another program is to uninstall VSCode, restart the PC and completely remove the folder `C:\Users\[User]\AppData\Roaming\Code`, which in my case had 380 MB and several thousand files cached in it. The folder has grown so much during 2 years of daily VSCode use, with regular upgrading to newest version as soon as it was released. I've also removed the VSCode extensions folder `C:\Users\[User]\.vscode`, I'm not sure whether this helped or not.

After reinstalling VSCode I had to reconfigure everything from scratch and install all extensions, but that cache folder is now only 80 MB and contains 550 files. Working with VSCode is a breeze again...

*Credit goes to @icedterminal https://github.com/microsoft/vscode/issues/146737#issuecomment-1124494187 - thanks for the idea!

*Cross-referencing possibly related issues, perhaps this helps someone else not noticing this solution: https://github.com/microsoft/vscode/issues/123257 https://github.com/microsoft/vscode/issues/147151 https://github.com/microsoft/vscode/issues/147188 https://github.com/microsoft/vscode/issues/123257

**Comment by kombasltd** [comment]
@lorand-horvath I don't see that as a solution - at most a temporary one.
Deleting, reinstalling and reconfiguring everything can't be in the inventor's spirit and what about it in a few months? This happens again?
