### ISSUE TITLE
Can we add distinguish between text editor and Notebook cell editor settings in the settings.json?

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/vscode#146765]
For example:

I added this in the settings.json file:

```
  "[python]": {
    "editor.rulers": [79, 120]
  },
```

It will be also applied to the jupyter notebook, but I want to avoid it.

Can we add `jupyter notebook` as language support too?

**Comment by rebornix** [comment]
You can customize by `notebook.editorOptionsCustomizations`.
