### ISSUE TITLE
Environment resolution for alternate shells, like fish?

### ISSUE THREAD

**Issue by mojotx** [microsoft/vscode#146719]
Issue Type: <b>Bug</b>

I have noticed that recently, when I start VSCode, I get an error about the resolving the shell environment. I use the [fish shell](https://fishshell.com/) as my login shell. 

How can I help VSCode access the environment? 

The actual error notification says:
> Unable to resolve your shell environment: Unexpected exit code from spawned shell (code null, signal SIGSEGV)

By design, the fish shell is NOT compatible with Bash, Zsh, Ksh, etc. However, if someone can point me to documentation about what VSCode is trying to do, I can probably help create a portable solution. 

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 0e820dbb-1797-49e5-a352-eb7943de52b4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
go-outliner|766|0.1.20
project-manager|ale|12.5.0
QML|bbe|1.0.0
vscode-fish|bma|1.0.27
better-toml|bun|0.3.2
gitignore|cod|0.7.0
vscode-mysql-client2|cwe|5.0.7
vscode-markdownlint|Dav|0.47.0
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|12.0.5
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
go|gol|0.32.0
beautify|Hoo|1.5.0
vscode-gnupg-tool|JHe|1.3.9
fish-ide|lun|0.4.0
Lisp|mat|0.1.12
git-graph|mhu|1.30.0
vscode-docker|ms-|1.21.0
vscode-kubernetes-tools|ms-|1.3.7
python|ms-|2022.4.0
vscode-pylance|ms-|2022.3.4
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.2
cpptools|ms-|1.9.7
go-doc|msy|1.0.1
java|red|1.4.0
vscode-yaml|red|1.6.0
rust|rus|0.7.8
crates|ser|0.5.10
markdown-preview-enhanced|shd|0.6.2
fish-vscode|sky|0.2.1
rust-pack|Swe|0.2.29
vscodeintellicode|Vis|1.2.18
vscode-java-debug|vsc|0.40.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.2
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
vim|vsc|1.22.2
gitblame|wad|8.1.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.13.20
vscode-open-in-github|ziy|1.3.6
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvid1:30447480
vscaac:30438847
pynewfile477:30463512

```

</details>

**Comment by meganrogge** [comment]
This type of issue is typically related to environment differences between VS Code's terminal and the external terminal. You can try diffing the two environments by printing them and investigating any differences.

**Comment by mojotx** [comment]
The problem is the error message when starting up.

<img width="1279" alt="Screen Shot 2022-04-05 at 6 07 20 AM" src="https://user-images.githubusercontent.com/5694899/161741342-2bbfda79-fa2d-4873-aaf6-3f8e0faecd77.png">

The terminal works just fine if I launch it from within VSCode. 
<img width="1392" alt="Screen Shot 2022-04-05 at 6 09 18 AM" src="https://user-images.githubusercontent.com/5694899/161741375-a75a73d2-9a4d-40b4-869f-dbc126d3a7ee.png">

What is VSCode doing when it tries spawning a shell to get the environment? I suspect that it is making an assumption that the user is using a somewhat POSIX-compatible shell, like Bash or Zsh, since those shells are mentioned in the [help documentation](https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fails) if you click "Learn More" on the error message.

Specifically, the documentation says:

> Resolving shell environment fails[#](https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fails)
> This section applies to macOS and Linux environments only.
> 
> When VS Code is launched from a terminal (for example, via code .), it has access to environment settings defined in your .bashrc or .zshrc files. This means features like tasks or debug targets also have access to those settings.
> 
> However, when launching from your platform's user interface (for example, the VS Code icon in the macOS dock), you normally are not running in the context of a shell and you don't have access to those environment settings. This means that depending on how you launch VS Code, you may not have the same environment.
> 
> To work around this, when launched via a UI gesture, VS Code will start a small process to run (or "resolve") the shell environment defined in your .bashrc or .zshrc files. If, after 10 seconds, the shell environment has still not been resolved or resolving failed for any other reason, VS Code will abort the "resolve" process, launch without your shell's environment settings, and you will see an error like the following:  [snip]

The last line says:
> If you see other errors, please create an [issue](https://github.com/microsoft/vscode/issues) to get help.

So that is what I am doing. 🙂

**Comment by mojotx** [comment]
I am looking through https://github.com/microsoft/vscode/blob/main/src/vs/platform/shell/node/shellEnv.ts, but I have not worked with TypeScript before.

**Comment by ktprograms** [comment]
Could you try looking at the logs and seeing if there's a more detailed error message?

**Comment by meganrogge** [comment]
Did some research and 

> SIGSEGV is triggered by the operating system, which detects that a process is carrying out a memory violation, and may terminate it as a result.

Might be a permissions issue - did this start happening for you recently or has it always happened?

**Comment by meganrogge** [comment]
@mojotx I see you've opened a new one, so will keep this one closed but otherwise would've reopened it.

**Comment by mojotx** [comment]
Yes, @meganrogge, I took it as an opportunity to hopefully present the issue more clearly, and give a more detailed description of what I have learned by reading through the code. 

Thank you!
