### ISSUE TITLE
 EXEC : error : getaddrinfo ENOENT dc.services.visualstudio.com

### ISSUE THREAD

**Issue by Vaclavkocourek** [microsoft/vscode#146743]
Hi there,

I'm unable to build my solution. 
The following error:  EXEC : error : getaddrinfo ENOENT dc.services.visualstudio.com appears to be a cause of build failing everytime. 

 ApplicationInsights:CorrelationIdManager [
EXEC : error : getaddrinfo ENOENT dc.services.visualstudio.com [C:\Solutions\CustomNTONPCFMultiselectLookup\NToNMultiSelect.pcfproj]
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
        at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -4058,
      code: 'ENOENT',
      syscall: 'getaddrinfo',
      hostname: 'dc.services.visualstudio.com'
    }
  ]

The issue follows:
 [C:\Solutions\CustomNTONPCFMultiselectLookup\NToNMultiSelect.pcfproj]
C:\Users\xxxx\.nuget\packages\microsoft.powerapps.msbuild.pcf\1.13.6\build\Microsoft.PowerApps.MSBuild.Pcf.targets(61,5):
error MSB3073: The command "npm run build -- --noColor --buildMode development --o 
utDir "C:\Solutions\CustomNTONPCFMultiselectLookup\out\controls" --buildSource MSBuild" exited with code -1. 

Connected to org VPN via DirectAccess

**Comment by meganrogge** [comment]
Looks like you're trying to use visual studio and this is visual studio code. you will need to file an issue in their repo
