### ISSUE TITLE
fixed Modal for Extension API 

### ISSUE THREAD

**Issue by dbwodlf3** [microsoft/vscode#146798]
Ctrl + F12 key is open a TextDocument without open a window like below (But this is not absolutely fixed).

![image](https://user-images.githubusercontent.com/22485292/161697111-f304b493-5aa9-4dff-89b6-23581551a4ea.png)

it is hard to scrolling in same file just one tab.. scroll up, and scroll down.. it makes me crazy.

I would like to just add some comment (@reference Something), and just open reference modal like above.
Also if it can be moved then it would be helpful.

**Comment by jrieken** [comment]
> I would like to just add some comment (@reference Something), and just open reference modal like above.
Also if it can be moved then it would be helpful.

Sorry, I have trouble understand what this means. Please clarify. Thanks
