### ISSUE TITLE
Unable to revert code to git version (only to local history)

### ISSUE THREAD

**Issue by MatejSkrbis** [microsoft/vscode#146717]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0
- OS Version: Windows 10 x64 - 19041

Unable to revert code to git source (only to latest local change)

Steps to Reproduce:

1. Make some changes to the code while git history is enabled
2. Close the editor and re-open it
3. Disable local history ![image](https://user-images.githubusercontent.com/13940777/161527178-3d4394ce-68d2-4df5-8d00-33a6d3d19371.png)
4. When trying to revert changes to the git version of the code, there is only option to revert to previous local version instead (in git repository there was number 6, in local history 11 and later changed to 9)
![image](https://user-images.githubusercontent.com/13940777/161528127-93b2a5ca-31b9-4291-9e22-7453365f0587.png)

**Comment by lszomoru** [comment]
@MatejSkrbis, I am trying to reproduce the issue and I was wondering if you could provide some further clarifications. In step 1) are you committing the changes, or you are just making changes to the file but not committing them. Given that in step 3) you have disabled local history, so the timeline should not be showing local history item any more. Are you saying that you are still seeing local history items in the timeline after you have disabled local history?

**Comment by MatejSkrbis** [comment]
I've tried updating VS Code to 1.66.1 and could no longer reproduce the issue as I described earlier.
