### ISSUE TITLE
Freezing when opening a folder with vs code

### ISSUE THREAD

**Issue by Niknu** [microsoft/vscode#146795]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:41.156Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.4.0-107-generic snap

Steps to Reproduce:

1. Click on Open Folder...
2. Now VS code is freezing

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by Niknu** [comment]
I made a mistake ( sorry for that) and the extended information is here:
https://github.com/microsoft/vscode/issues/146809

**Comment by jrieken** [comment]
closing to continue in #146809
