### ISSUE TITLE
OmniSharp invalid CIL

### ISSUE THREAD

**Issue by darkoverlordofdata** [Microsoft/vscode#14676]
- VSCode Version: 1.6.1
- OS Version: elementary OS 0.4 Loki (64-bit) - Built on "Ubuntu 16.04 LTS"

Steps to Reproduce:

1. Followed instructions at [https://www.microsoft.com/net/core#ubuntu](https://www.microsoft.com/net/core#ubuntul)
2. Restart VSCode

Get the following output:
Starting OmniSharp server at 10/28/2016, 1:22:37 PM
    Target: /home/bruce/Downloads/WindowsExplorer_C/WindowsExplorer_C.sln

OmniSharp server started wth Mono
    Path: /home/bruce/Applications/omnisharp-ubuntu16-x64-netcoreapp1.0/OmniSharp
    PID: 23323

Cannot open assembly '/home/bruce/Applications/omnisharp-ubuntu16-x64-netcoreapp1.0/OmniSharp': File does not contain a valid CIL image.
[ERROR] Error: Failed to start OmniSharp

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#853
