### ISSUE TITLE
Search Editor: number input box & Toggle Context Lines button suggestions

### ISSUE THREAD

**Issue by Z-E-D** [microsoft/vscode#146706]
Several related suggestions for Search Editor:
1. add tooltip for the number of context lines input box;
2. swap position of the number input box and the Toggle Context Lines button;
3. change tooltip text for that button to "Context Lines";
4. disable the number input box when the Context Lines button is switched off;
5. add border line around the Context Lines button when it is switched on, use the same line as it is around Match Case / Match Whole Word / RegEx buttons when they are switched on.

Currently, it is not always clear enough if the context lines option is switched on or off just by looking at the displayed resulting lines. If you see just one line with the search result: it could be that the button is switched off, or in some rare cases, it could be that the file with the matched line has just single line of text and no surrounding lines.

**Comment by JacksonKearl** [comment]
They're reasonable suggestions but I do not have capacity to take this on at the moment. Thus moving to backlog and marking as help wanted.

**Comment by quanzhuo** [comment]
I'd like to take this

**Comment by JacksonKearl** [comment]
@quanzhuo thanks! Let me know if you need any pointers.

**Comment by Z-E-D** [comment]
@[quanzhuo](https://github.com/quanzhuo) If you are going to implement these suggestions, maybe you could also take a look at this related bug: #140612.

**Comment by quanzhuo** [comment]
@Z-E-D OK. Got it

**Comment by eleanorjboyd** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue. PRs are welcome so you can create a PR that fixes this if you are passionate about getting this feature across the finish line. Thanks!
