### ISSUE TITLE
Legacy smoke test failure: Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#146771]
```
  1) VSCode Smoke Tests (Electron (legacy))
       Multiroot
         "before all" hook for "shows results from all folders":
     Error: connect ECONNREFUSED /tmp/tmp-31216-DJ4MDLuvP6YL
      at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)

```

Legacy smoke test is flaky due to this error https://dev.azure.com/monacotools/Monaco/_build/results?buildId=165000&view=logs&jobId=963754b8-394e-5caf-de5d-2790b068caec&j=963754b8-394e-5caf-de5d-2790b068caec&t=3f9a8987-2bdd-59aa-e288-445ec20a3fd1

**Comment by bpasero** [comment]
This only seems to happen on Linux and I pushed a change to not use legacy driver on Linux and macOS via https://github.com/microsoft/vscode/commit/6508a29d23f1c6a8a32e0a01051e598e4b6091de
