### ISSUE TITLE
Terminal: Click on other terminal should focus it

### ISSUE THREAD

**Issue by robinheidrich** [microsoft/vscode#146725]
In the terminal, when you click another "tab" on the right, it is selected instead of the terminal. 

You have to click on the terminal first to be able to write there.

![capture](https://user-images.githubusercontent.com/23118399/161552931-90c113f4-4f1c-4c12-bb66-a4f230c0664e.gif)

**Comment by meganrogge** [comment]
`terminal.integrated.tabs.focusMode` allows you to customize that behavior
