### ISSUE TITLE
[python] syntax highlighting breaks on function annotations, async, and await

### ISSUE THREAD

**Issue by nchammas** [Microsoft/vscode#1467]
At some point recently, Python syntax highlighting went awry:

![screen shot 2015-12-18 at 10 13 02 pm](https://cloud.githubusercontent.com/assets/1039369/11910960/91ec729e-a5d4-11e5-8e73-465e1b3db73e.png)

Specifically, it looks like function annotations in Python 3 mess it up. The first docstring should be highlighted like the second.

This used to work until recently. I'm running 0.10.3.

**Comment by nchammas** [comment]
It also seems that highlighting for Python built-in functions is broken:

![screen shot 2015-12-26 at 8 11 23 pm](https://cloud.githubusercontent.com/assets/1039369/12008492/e340c1e8-ac0c-11e5-902c-94b94334d519.png)

This is on Code 0.10.6.

**Comment by aeschli** [comment]
As you mention, the cause seems to be the function annotation. Remove it results in correct colorization.

For tokenizing we use the tokenizer from
https://github.com/textmate/python.tmbundle/blob/master/Syntaxes/Python.tmLanguage

**Comment by aeschli** [comment]
I created https://github.com/textmate/python.tmbundle/issues/51

**Comment by nchammas** [comment]
@aeschli - What about Python built-in functions? Should those not be highlighted anymore?

Also, did VS Code recently change how it does syntax highlighting? Because both these examples (function annotations & Python built-ins) used to highlight correctly until a few releases ago.

**Comment by aeschli** [comment]
@nchammas That depends on the theme that you choose. The default light and dark themes typically don't highlight function or method references.

**Comment by nchammas** [comment]
I have never modified my theme from the default. Did the default theme change recently?

**Comment by aeschli** [comment]
Yes, there has been changes to the default themes to make them more consistent to the Visual Studio default themes. I guess that's when the change happend. Sorry for that.

**Comment by nchammas** [comment]
Another syntax highlighting issue (not sure if this should go in a separate issue):

The new [`async` and `await` syntax](https://www.python.org/dev/peps/pep-0492/#asynchronous-context-managers-and-async-with) in Python 3.5 is not highlighted correctly.

**Comment by aeschli** [comment]
@nchammas Please also file this against https://github.com/textmate/python.tmbundle and please add a code snippet as well. Thanks!

**Comment by infininight** [comment]
This has been corrected in the TextMate repository, but I have not tested the changes in VSCode.

**Comment by aeschli** [comment]
@infininight Great, I updated our grammar. The original issue seems to be fixed. thanks!

One comment mentions the async and await syntax. This seems to be still open. I created https://github.com/textmate/python.tmbundle/issues/53
