### ISSUE TITLE
Case sensitivity of nesting parents

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#146761]
@JacksonKearl thanks for looking into this! I just want to clarify if this issue is supposed to be fixed on 1.66.0 stable.

If it is, then the bug is still present (I'm on Version: 1.66.0 - Commit: e18005f0f1b33c29e81d732535d8c0e47).

I'm testing with these settings:
```json
  "explorer.experimental.fileNesting.patterns": {
      "Gemfile": "Gemfile.lock"
  }
```

If I change it to this, the nesting works (notice only the parent needs to be lowercase):
```json
  "explorer.experimental.fileNesting.patterns": {
      "gemfile": "Gemfile.lock"
  }
```

Tested on macOS 11.6.5.

Looking at the code, it seems `this.getPlatformAwareName()` also needs to be applied to `parentPattern`.

Let me know if I need to create a new issue.

_Originally posted by @rafasoares in https://github.com/microsoft/vscode/issues/142390#issuecomment-1087497856_

**Comment by rafasoares** [comment]
@JacksonKearl dude! I just want show you my appreciation for how quickly you addressed this!

Thanks for your time!

You rock 😄

**Comment by JacksonKearl** [comment]
It's easy when you do the work for me :)
