### ISSUE TITLE
Vscode Revert Html Tags In Wrong Order

### ISSUE THREAD

**Issue by pooooriya** [microsoft/vscode#146704]
Hi After Upgrading to The last version of vscode after typing RTL Languages like Farsi , HTML tags had been reverted in the wrong order 
![image](https://user-images.githubusercontent.com/65160744/161490918-097a8634-b6a3-474d-8948-be1b2c49bc14.png)
I Ask This Question From Other Developers And This Bug Occurs In Their Devices Too!
-------
Windows 10
Vscode Latest Version
-------

**Comment by alexdima** [comment]
@pooooriya Could you please provide the text above in a copy-paste friendly format?

**Comment by ahmadi-akbar** [comment]
same here

**Comment by ahmadi-akbar** [comment]
@merfankarami , @pooooriya 
check out https://github.com/microsoft/vscode/issues/146533 for solution

**Comment by mohammadkamrannn** [comment]
@aeschli  and @alexdima This is a bug in the new version 1.66
I had to go back to version 1.65

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/146354 and https://github.com/microsoft/vscode/issues/99589
