### ISSUE TITLE
Support to prevent defaultEvent

### ISSUE THREAD

**Issue by saltylassi** [microsoft/vscode#146705]
Hi, I make some extension using customEditor API, and I'd like to prevent defaultEventHandler like **event.preventDefault** on web.

**like this :** 

![event](https://user-images.githubusercontent.com/77769802/161491429-841d5e3c-6dee-4b44-87c5-2a3a8de320d6.png)

I've checked extension APIs and github issues, but what I found is **out of scope** label.

I think this feature is really useful, is there any plan to implement this?

or there is any API I can use?

**Comment by mjbvz** [comment]
Why do you want to prevent default?

**Comment by saltylassi** [comment]
> Why do you want to prevent default?

In my customTextEditor(sorry, it's **customTextEditor.** not customEditor), I have to handle some untitled files like **editable** virtual document.

**Comment by saltylassi** [comment]
> Why do you want to prevent default?

@mjbvz 

This is what I want to make.


**1. I have a html file, like this :**

![1](https://user-images.githubusercontent.com/77769802/161647136-43ded099-8bb8-417e-8d2b-3d5345c9bb0e.png)


**2. when open html file on vscode, my customTextEditor extension render it.**

![2](https://user-images.githubusercontent.com/77769802/161647279-5005fbd3-a605-4bbc-b403-c59cf6e72b03.png)

**3. when execute myExtension\.splitFile command, extension separates htmlFile into html(without script tag) and script file.**

![3](https://user-images.githubusercontent.com/77769802/161647477-0742d083-01be-428d-b5c4-e0a423787a45.png)


at this point, those two files are untitled. (like **virtual document**)

**4. If I edit and save on untitled file, update original file**
![4](https://user-images.githubusercontent.com/77769802/161647726-7c2188d8-6985-432d-b1d8-fb2d7502d5c5.png)
![5](https://user-images.githubusercontent.com/77769802/161647730-21ae2c81-cf07-47c1-a07f-71791532a07a.png)

problem occurs, because js file is untitled, **save dialog pop out.** This is why I want to prevent defaultEvent.


I tried virtual document API, but it is **read-only,** I can't edit file.

and I checked eventEmitter API with custom event, but I can't find custom event constructor on vscode API docs.

It seems there is no API can help this...

**Comment by mjbvz** [comment]
`CustomTextEditor` is meant to handle all basic file operations for you, including such as saving and backups

For more advanced  use cases, try using the standard `CustomEditor` api which gives you full control over saving (but first, really think about if you need your own on save behavior)
