### ISSUE TITLE
Allow renaming files in markdown

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#146777]
Follow up on #146291

## Feature request

For the markdown:

```md
![desc](path/to/img.png)
```

We should support pressing `f2` on `path/to/img.png` to rename that file (along with updating other markdown references to that file)

**Comment by mjbvz** [comment]
A few other points:

### You should be able to rename links to files that don't exist on disk

If we trigger a rename on a file we can't resolve on disk, we should simply update all other references that file 

### You should be able to rename a header in a file and a file separately

```md
[text](/path/to/file.md#some-header)
```

Should support renames on both `/path/to/file.md` and `#some-header`. The rename on `/path/to/file.md` should rename the file while the rename on the header should simply rename the header


### Supported locations
Renaming file paths should be supported in the follow places:

```md
[text](/path.md)

[ref]: /path.md
```

**Comment by mjbvz** [comment]
Marking as help wanted as the most difficult part of this change (finding the references to a given file) is already done

The relevant code is:

https://github.com/microsoft/vscode/blob/d0767451a93039ee458570b5c11579e585156fb3/extensions/markdown-language-features/src/languageFeatures/rename.ts#L15

With the tests (and you should add lots of them ;) here:

https://github.com/microsoft/vscode/blob/d0767451a93039ee458570b5c11579e585156fb3/extensions/markdown-language-features/src/test/rename.test.ts

**Comment by weartist** [comment]
I'd like to take this

**Comment by babakks** [comment]
@mjbvz I'd like to take this. Is there any work in progress?

**Comment by mjbvz** [comment]
Actually this was somewhat complicated so I ended up fixing it 0ac39e800d3d4de7b9612118559ece9af9cda5cb (and a few follow ups) You can help test this new feature in the next insiders build

/fixedBy 0ac39e800d3d4de7b9612118559ece9af9cda5cb
