### ISSUE TITLE
Calling `editor.action.rename` from the server doesn't respect arguments

### ISSUE THREAD

**Issue by ilyailya** [microsoft/vscode#146767]
Hey!

I'm trying to execute the `editor.action.rename` command from the server, but it doesn't work as expected. I'm using the code actions [capability to call the commands](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeAction) after applying the edits:

```
export interface CodeAction {
	...
	
	/**
	 * A command this code action executes. If a code action
	 * provides an edit and a command, first the edit is
	 * executed and then the command.
	 */
	command?: Command;
}
```
If I pass `editor.action.rename` in the `command` field as a response to the `textDocument/codeAction` request, the client will actually make the `textDocument/rename` request at the cursor location. But I didn't manage to find a way to pass arguments to the command. 

My baseline was this issue https://github.com/microsoft/vscode/issues/50856, which proposed to call the rename command from the client with the URI and the position objects:

```javascript
vscode.commands.executeCommand(
  'editor.action.rename',
  [vscode.Uri.file('/Users/jrieken/Code/_samples/ConsoleAppDnx/ts/test.ts'), new vscode.Position(14, 7)]
)
```
The difference with my use case is in I want to call the rename command from the server via JSON RPC. The `command` field in the `CodeAction` should trigger it.

I've tried to serialize `vscode.Uri.file` and `vscode.Position` to JSON, and send a data with the same shape in the `data` field of the `Command`. Unfortunately, that approach didn't yield any result.

Common workaround for this behaviour is to introduce a custom command in the client which will call the `editor.action.rename` from the client. For example, the java eclipse language server does it:

1. [The server returns a custom command with a code action](https://github.com/eclipse/eclipse.jdt.ls/blob/44097253601c0781003981a0ffe8afbd73840b46/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GetRefactorEditHandler.java#L139-L140)
2. [The client wraps a call to the `editor.action.rename` in a custom command](https://github.com/redhat-developer/vscode-java/blob/8aadf21949409e82e5d9f89d319750937352fa32/src/refactorAction.ts#L15-L33)

The desired behaviour for me would be an ability to call the rename command and also to specify the location in the file for the rename. Obviously there would be some limitations like the file should be in the active editor at the moment. 

### How to reproduce
1. Trigger an editor to send a `textDocument/codeAction` request
2. Return a `CodeAction` with a `command` shaped like this
```json
{
"title": "Rename",
"command": "editor.action.rename",
"data": [{"path": "[/path/to/a/file.js]", "scheme": "file"}, {"line":5,"character":11}]
}

```

### Expected result
The "Rename Symbol" action will be executed on a the specified position in the specified file, if the file is in the active editor at the moment

### Actual result
The "Rename Symbol" action will be executed will be executed on the cursor location or will not be executed at all

Please let me know if you have any questions, I'd be glad to answer any of them.

Thanks!

**Comment by jrieken** [comment]
> Return a CodeAction with a editor.action.rename string in the command field and the data field shaped like this from the server

Passing `{"line":5,"character":11}` isn't recognised as `vscode.Position` because we do an `instanceof` check (the same is true for `Uri`). We can relax this a little but you should be unblocked by using instances of the corresponding classes

**Comment by ilyailya** [comment]
hey @jrieken, thanks for replying!

I think I didn't state my intentions clearly enough. 
Unfortunately, I can't initialize the `{"line":5,"character":11}` as `vscode.Position`, because it's happening on the server side, and the server is implemented in C++. So the server doesn't know about the `vscode.Position`, it can only replicate the same JSON structure. The communication with the client is done via JSON RPC, so the data would be translated to JSON anyway. The communication schema looks like this:

1. User selects refactoring in the editor
2. Client sends a `textDocument/codeAction` request to the server via JSON RPC
3. Server replies with a `CodeAction` structure as it stated in [the spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeAction). The server populates the `command` property as I described above
4. The rename command is called on the client, but the arguments are ignored

>we do an instanceof check (the same is true for Uri)

That makes total sense to me. However, I can't instantiate this exact structures using the RPC, because they're translated to JSON. Would it make sense to attempt to parse the input data and create an instance of the `Uri` and `Position` before doing the `instanceof` checks? This way we could handle not only client only calls to the function, but also RPC calls from the server.

P.S. I reread my initial original message, and I had a confusion about the `data` field (I've wrote about the `CodeAction`'s field, however I meant the field with the same name on the `Command`). The initial message is updated, and should be more clear now. Sorry about that!

**Comment by jrieken** [comment]
> Unfortunately, I can't initialize the {"line":5,"character":11} as vscode.Position, because it's happening on the server side, and the server is implemented in C++. So the server doesn't know about the vscode.Position, it can only replicate the same JSON structure.

I understand that but the RPC data is received by the extension host (via the LSP client) and that ends up interacting with the VS Code API and its types. We can maybe be a little more graceful there but we cannot attempt to parse arbitrary data into types
