### ISSUE TITLE
TypeScript and JavaScript Language features

### ISSUE THREAD

**Issue by datablazor** [microsoft/vscode#146738]
We have written the needed data into your clipboard because it was too large to send. Please paste
<img width="931" alt="Screen Shot 2022-04-04 at 11 37 04 AM" src="https://user-images.githubusercontent.com/23362828/161580061-cd683147-1300-4a99-bbae-5c498cff6ce8.png">
.

**Comment by micleyman** [comment]
Disabling the TSLint extension fixed this for me, after it started popping up a few days ago.
Looks like it's deprecated anyway.

**Comment by datablazor** [comment]
It worked once I uninstalled the Application and re-installed it. It would be great if it gets fixed as well in the next release.
