### ISSUE TITLE
Export and import user profiles

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#146729]
Initial profile support for settings, extensions, activity bar, views, view container, status bar
- [x] Support to export a profile from the current workbench
- [x] Support to import a profile from a file/URL
- [x] Enable profile support in the storage service

**Comment by sandy081** [comment]
@bpasero Moving this back to April since I have the implementation ready. Planning to push changes on Monday.

**Comment by bpasero** [comment]
Oh nice, sorry didn't know that 👏

**Comment by sandy081** [comment]
Here is the quick demo of exporting and importing profiles - Settings, Extensions and UI state is exported/imported

## Exporting

![Recording 2022-04-23 at 17 47 00](https://user-images.githubusercontent.com/10746682/164894582-d633d598-521b-4c5c-8611-fd9dc5288f25.gif)

## Importing

https://user-images.githubusercontent.com/10746682/164894744-96a1770b-8a82-4535-b98e-fe3566de2256.mov

**Comment by ChaseKnowlden** [comment]
I've seen an extension by Aaron Powell that is similar to this feature

**Comment by lostintangent** [comment]
This is awesome! ❤️ Out of curiosity: is there a way for an extension to programmatically export a profile as a string, and then headlessly import it via a URI? I'd love to update [GistPad](https://aka.ms/Gistpad) to allow saving/restoring/sharing profiles via GitHub Gists, without the user needing to manually generate the profile file, and then create a gist from it.

**Comment by sandy081** [comment]
> is there a way for an extension to programmatically export a profile as a string, and then headlessly import it via a URI?

Nope. But we are planning to extend this feature to extensions by allowing them to contribute profiles just like themes.
