### ISSUE TITLE
Unable to see some files/folders in visual code explorer

### ISSUE THREAD

**Issue by geversoncarvalho** [Microsoft/vscode#14671]
- VSCode Version: 1.3.1
- OS Version: Windows 7 Entriprise - Service Pack 1

Steps to Reproduce:
1. I'm running the application in an virtual machine in a restrict access environment.
2. The project is versioned using SVN.

Some files and folders inside the Project Files Panel are not being displayed... I've tried to delete .vscode folders to check whether it was a configuration/cache issue, but nothing I've done has solved the problem. Opening the same project in atom has worked perfectly.

Unfortunately, I can't paste here any log or file, as the Visual Code is running in an restrict environment which I can't extract any file.

**Comment by weinand** [comment]
@geversoncarvalho what do you mean by 'Project Files Panel'? VS Code's Explorer:

![2016-10-28_20-59-44](https://cloud.githubusercontent.com/assets/1898161/19818762/82233b8e-9d51-11e6-940e-89834ab8ece7.png)

**Comment by geversoncarvalho** [comment]
Yes, exactly... The explorer is not displaying some files and when I opened one of these files through the File > Open File, the 'invisible' file becomes visible in the explorer until I restart the Visual Code. I tried several approaches as reopen the folder through File > Open Folder or removing .vscode folders, but nothing solved the problem.

**Comment by bpasero** [comment]
@geversoncarvalho could be a permission problem. are these files files or folders that do not show up? do you see output printed to the developer console (Help > Toggle Developer Tools).

**Comment by geversoncarvalho** [comment]
The Developer Tools didn't display any log, but after File > Close Folder and File > Open Recent > ..., the folders returned to the Explorer... I don't know exactly what was the problem's cause, but at least it working fine now. Thanks anyway.
