### ISSUE TITLE
Shortcut Ctrl + S, Ctrl + F are not working please hep!

### ISSUE THREAD

**Issue by setsenbat** [microsoft/vscode#146790]
Issue Type: <b>Feature Request</b>

Dear all,

I have checked with Keyboard Shortcuts. Everything looks good also I haven't changed anything but last 2 days my Ctrl + S and Ctrl + F are not working. Could you please suggest and help with this issue!

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Have you been through the information and suggestions at https://github.com/microsoft/vscode/wiki/Keybinding-Issues yet?
