### ISSUE TITLE
applciation/json output is not working in vscode notebooks

### ISSUE THREAD

**Issue by colombod** [microsoft/vscode#146750]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0 (user setup)
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. open a notebook with .NET Interactive
2. Create a javascript cell
3. enter the following code 
```javascript
const getMethods = (obj) => {
    let properties = new Set()
    let currentObj = obj
    do {
      Object.getOwnPropertyNames(currentObj).map(item => properties.add(item))
    } while ((currentObj = Object.getPrototypeOf(currentObj)))
    return [...properties.keys()].filter(item => typeof obj[item] === 'function')
  }

let methods = getMethods(kernel.root.findKernelByName("javascript"));
console.log(JSON.stringify( methods));
```
4. run code
5. applcaition/json mimetype doesn't have a renderer
reported also [here](https://github.com/dotnet/interactive/issues/1950)

**Comment by rebornix** [comment]
It's now being replaced by `text/x-json`.

**Comment by colombod** [comment]
What is the fix for this?

**Comment by rebornix** [comment]
Discussed offline and the impact is high for .NET notebook users, so we are going to add this back to the builtin renderer.

**Comment by gjsjohnmurray** [comment]
See also #143300

I'm pleased it is being addressed.

**Comment by rebornix** [comment]
* Create a `test.ipynb` file in file explorer
* Right click and click "Open with...", pick "Text Editor"
* Paste following content
```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/json": {
       "a": 123
      },
      "text/plain": [
       "<IPython.core.display.JSON object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "1b517e8d77d7050d46a4e4c25419b0e0293937b147b46538d7513cd42288caeb"
  },
  "kernelspec": {
   "display_name": "Python 3.8.5 64-bit ('3.8.5')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.8.5"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```
* Close editor
* Click the file from the file explorer to open again (it should now open in notebook editor by default)
* Check if it renders `{ "a": 123 }` in the notebook cell output

**Comment by rchiodo** [comment]
Works for me too.

**Comment by colombod** [comment]
all good!
