### ISSUE TITLE
Lagging Scroll on Surface Book Touchpad

### ISSUE THREAD

**Issue by Daibolic** [Microsoft/vscode#14670]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: donjayamanne.python-0.3.23, ms-vscode.cpptools-0.9.2

Steps to Reproduce:
1. Open any file
2. Using the touchpad of my surface book, the scrolling is lagging to the point of unusable

**Comment by zhengbli** [comment]
I have the same problem on a yoga 910 laptop. Add "--disable-gpu" seems to hep.

**Comment by mrmlnc** [comment]
@zhengbli, please, try to use latest Insiders. As far as I know, this should be fixed.

**Comment by alexandrudima** [comment]
It appears to be an upstream issue with Chromium (we recently updated to Electron 1.3.8 that comes with Chromium 52). Apparently Chromium 54 has fixed the issue already. Let's track in #13612
