### ISSUE TITLE
Removing the notebook concat text document API proposal 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#146781]
The Notebook Concat Text Document api is not currently on track for finalization. Instead of having this functionality as part of VS Code core, we believe that individual extensions/languages are better equipped to build their own virtual document model of notebooks (in cases where such a model makes sense)

We plan to remove this proposed API once all current consumers have migrated off of it. The only known consumers today are:

- [x] Jupyter @DonJayamanne 
- [x] Dot Net Interactive @brettfo, @colombod https://github.com/dotnet/interactive/issues/1966

Please let me know if you are still consuming this API and if there are any blockers that would prevent migrating off of it

**Comment by DonJayamanne** [comment]
> Please let me know if you are still consuming this API and if there are any blockers that would prevent migrating off of it

Yes. we're still consuming this API.
@rchiodo Please could you update @mjbvz on the status of migrating away from this (I believe Pylance needs to adopt notebook support. But we'd still need this for Jedi)

**Comment by rchiodo** [comment]
Actually I don't think we need this anymore as we have our own version: https://github.com/microsoft/lsp-notebook-concat

We can just remove this from our list of proposed APIs.

**Comment by DonJayamanne** [comment]
> We can just remove this from our list of proposed APIs.

I don't think we can. lets discuss.

**Comment by DonJayamanne** [comment]
@mjbvz confirmed, we can remove Jupyter from that list, we'll update our package.json accordingly.

**Comment by mjbvz** [comment]
Thanks @DonJayamanne and @rchiodo! Removing from `product.json` for the next insiders

cc @jrieken

**Comment by mjbvz** [comment]
Confirmed the Dot Net Interactive does not use this API so we can safely delete it. I'll update the api enablement list and then look into deleting the api entirely
