### ISSUE TITLE
Support for React 18

### ISSUE THREAD

**Issue by Oya-Tomo** [microsoft/vscode#146707]
Issue Type: <b>Feature Request</b>

 I made a React project with cra and tried to use 'createRoot()' and 'useTransition()'.
But Auto-completion didn't work.
 These functions were added to React18 from React18 release.

Auto-completion of VScode is very useful to code.
So, I want you to make VScode support for React 18.

Sorry for no good English.😅

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by IllusionMH** [comment]
/quesion

VS Code doesn't have special support for React.
Completions are relying on `@types/react` (which are usually installed for TS projects and pulled by Automatic Types Acquisition for JS)

This package doesn't have release update for React 18 yet

**Comment by IllusionMH** [comment]
/question

VS Code doesn't have special support for React.
Completions are relying on `@types/react` (which are usually installed for TS projects and pulled by Automatic Types Acquisition for JS)

This package doesn't have release update for React 18 yet

UPD. Sorry for the second notification

**Comment by Oya-Tomo** [comment]
Thank you for your response.
 I’ll wait for the support of @ types / react and resume development.
