### ISSUE TITLE
Intellisense in package.json shows packages inconsistently

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14679]
From https://github.com/Microsoft/vscode/issues/13835#issuecomment-256813527,

When typing quickly, I'm selecting packages by initials (or something), but when I type slowly, I'm selecting packages by prefix:
1. Open package.json
2. Put the cursor in "dependencies"
3. ctrl+space, then esc (It doesn't repro unless the intellisense window has been shown on this line)
4. type `blu` quickly
5. The intellisense window appears again and I expect to see suggestions for all packages that match. Instead I only see "blackbaud-npi-datamart-ux", with the 'blu' highlighted. It's always this one package.

If you type `blu` more slowly, then it shows 'blu', 'blu-css', 'blu-generator' ...

Another example -
Typing "blah" quickly
![image](https://cloud.githubusercontent.com/assets/323878/19823534/d9c6238a-9d1d-11e6-9b21-fe2ce214a419.png)

Slowly:
![image](https://cloud.githubusercontent.com/assets/323878/19823537/e229d0d0-9d1d-11e6-8fe6-8dd5ce894e88.png)

The first type of fuzzy matching would be useful but it should be more consistent.

**Comment by roblourens** [comment]
And if you don't see the behavior when typing fast, or it stops reproing, try deleting the line so that the cursor is on the previous line, then press return to start a new line, and start over.

**Comment by jrieken** [comment]
Problem is that we don't retriever completion when the very first request yields an incomplete result - so basically we ignore everything which was typed while the request is going. The fix is to check for incomplete during `onNewContext`
