### ISSUE TITLE
Could we provide more details of the variable when debug like the PyCharm does?

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/vscode#146748]
![InkedCapture_LI](https://user-images.githubusercontent.com/21306413/149445197-8ccb1f0d-da08-407b-b4b6-8a53d2f84829.jpg)
![InkedCapture2_LI](https://user-images.githubusercontent.com/21306413/149445207-df2e06ae-24c1-4db3-92ed-17a1c2627120.jpg)

I know, we can get more details through clicking the arrow to get into the variable or through some expression in the WATCH panel. But it will be better to act as the PyCharm does.

**Comment by Ashark** [comment]
> > In pycharm even position of the debug window is better. It is on the bottom with more width. In vscode we are stuck, can't move it anywhere.
> 
> @ghuname that's not entirely true, you can drag your variables elsewhere:
> 
> ![image](https://user-images.githubusercontent.com/117621/153929198-fa458456-e46e-4bfa-bd5d-1fbb8605104a.png)

Advise fot those who use wayland: such drag does not work currently. To drag that panel I restarted vscodium without `--enable-features=UseOzonePlatform --ozone-platform=wayland `, and then I could drag that.

**Comment by weinand** [comment]
Suggestion form @int19h:
VS Code setting to display the type in the Variables pane

**Comment by lyjdwh** [comment]
Is there a way to customize the order of variables? If so we can put the shape and type on the top of the  list!

**Comment by PengjuYan** [comment]
Any progress on this issue? When I talked about this problem, people around me say "vscode is great, and PyCharm is much better". LOL

Really looking forward to solve it before people turn away.

**Comment by connor4312** [comment]
Missed this feature duplication, this was implemented in https://github.com/microsoft/vscode/pull/214315 and can be turned on via the `debug.showVariableTypes` setting

**Comment by thorinf-orca** [comment]
> Missed this feature duplication, this was implemented in #214315 and can be turned on via the `debug.showVariableTypes` setting.
> 
> I realize we also forgot to mention that on last month's release notes, I'll get it on the ones for this month so people are aware :)

Is there any option for shapes too?

**Comment by pdima** [comment]
In my opinion, shapes are much more useful to display for numpy arrays, torch tensors etc. To a lesser extent - dtypes. Next - to be able to visualise the data.
