### ISSUE TITLE
In the quick search (cmd + p) panel, typing "view" then space bar, switched into the command view instead of continuing search files with "view" as the file name

### ISSUE THREAD

**Issue by iprastha** [microsoft/vscode#146793]
Issue Type: <b>Bug</b>

In the latest release, open file search (cmd + p)
type "view" then press spacebar
Previously it keeps searching any file name with the string "view", but in this latest release, it switches into Open View commands and stopped searching files

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
laravel-extra-intellisense|ami|0.6.2
ci-snippets2|Ani|1.0.1
toml|be5|0.6.0
vscode-intelephense-client|bme|1.8.2
dart-code|Dar|3.38.0
flutter|Dar|3.38.0
vscode-eslint|dba|2.2.2
jquerysnippets|don|0.0.1
gitlens|eam|12.0.5
EditorConfig|Edi|0.16.4
vue-snippets|hol|1.0.4
vscode-env|Iro|0.1.0
git-graph|mhu|1.30.0
vscode-deploy-reloaded|mkl|0.89.0
php-docblocker|nei|2.7.0
vetur|oct|0.35.0
es6-css-minify|olb|3.3.3
laravel-blade|one|1.32.0
laravel5-snippets|one|1.15.0
vscode-thunder-client|ran|1.14.4
laravel-artisan|rya|0.0.28
code-settings-sync|Sha|3.4.3
php-ci|sma|0.4.2
pdf|tom|1.2.0
better-align|wwm|1.1.6
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details>

**Comment by iprastha** [comment]
https://user-images.githubusercontent.com/7000558/161677540-df9709e7-ac6e-427d-97bb-33e52c9e1f5a.mp4

**Comment by roblourens** [comment]
This is a feature of the quick open, it has been this way for a long time. You will get the same results without the space
