### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by chety** [microsoft/vscode#146721]
Issue Type: <b>Bug</b>

The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

VS Code version: Code 1.66.0 (Universal) (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 7|
|Memory (System)|32.00GB (6.29GB free)|
|Process Argv|--crash-reporter-id 8f812c0e-6b86-40a8-990f-02cb3fce5cc7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
jest-snippets|and|1.8.0
ng-template|Ang|13.3.0
simple-react-snippets|bur|1.2.6
path-intellisense|chr|2.8.0
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.5
vscode-great-icons|emm|2.1.84
prettier-vscode|esb|9.5.0
vscode-jest-runner|fir|0.4.48
code-runner|for|0.11.7
copilot|Git|1.11.5453
go|gol|0.32.0
rest-client|hum|0.24.6
RelativePath|jak|1.4.1
vscode-codemetrics|kis|1.24.0
json-to-ts|Mar|1.7.5
vscode-language-babel|mgm|0.0.36
fluent-icons|mig|0.0.17
vscode-docker|ms-|1.21.0
csharp|ms-|1.24.3
python|ms-|2022.4.0
vscode-pylance|ms-|2022.3.4
remote-containers|ms-|0.231.2
js-debug-nightly|ms-|2022.4.117
vscode-typescript-tslint-plugin|ms-|1.3.4
vscode-jest|Ort|4.2.1
material-icon-theme|PKi|4.15.0
tsimporter|pmn|2.0.1
LiveServer|rit|5.7.5
ava|sam|0.6.0
markdown-preview-enhanced|shd|0.6.2
ayu|tea|1.0.5
best-dark-themes-pack|the|1.0.2
errorlens|use|3.4.2
code-navigation|vik|0.2.0
vscodeintellicode|Vis|1.2.18
vscode-maven|vsc|0.35.1
glean|wix|5.2.2
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.13.20

(10 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by mjbvz** [comment]
Thanks for checking. Either insiders fixed it or one of your extensions was causing this

Closing as not-reproducible
