### ISSUE TITLE
Link misinterpreted in code blocks in markdown file 

### ISSUE THREAD

**Issue by AkatQuas** [microsoft/vscode#146714]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Write any code blocks in any markdown file

<img width="570" alt="image" src="https://user-images.githubusercontent.com/24731539/161518825-5cf6ca1d-eff9-40f0-980d-891f391db2d6.png">

<img width="389" alt="image" src="https://user-images.githubusercontent.com/24731539/161789189-43c5a3d8-340d-45cc-a1a6-3ad969c5395d.png">

2. It looks like all these properties are interpreted as links in reference style. Indeed, you could `command+click` them, which of course leads to the wrong address.

---

> codes for copy 

\`\`\`js
const double = 'double';
const bb = 'bb';
const x = {
  [double]: [bb],
};
\`\`\`

\`\`\`ts
interface Fruit {
    [key]: number;
}
\`\`\`

\`\`\`python
dict = {
    [a]: "number";
}
\`\`\`

**Comment by wannieman98** [comment]
Hi, I am quite new to open source contributing but as a vs code user I wish to give this issue a try! Could you help with how to go about this issue? Thank you!

**Comment by mjbvz** [comment]
The relevant code is:

https://github.com/microsoft/vscode/blob/baa7434480b28d5acf1608715a8e8cf3e47c6847/extensions/markdown-language-features/src/languageFeatures/documentLinkProvider.ts#L206

There's already code that checks if some links occur inside code blocks. This simply needs to be extended to cover all links

The relevant tests are in:

https://github.com/microsoft/vscode/blob/0e65adbda8f3b605d240b341dd8623203e16997d/extensions/markdown-language-features/src/test/documentLinkProvider.test.ts#L17

**Comment by wannieman98** [comment]
> The relevant code is:
> 
> 
> 
> https://github.com/microsoft/vscode/blob/baa7434480b28d5acf1608715a8e8cf3e47c6847/extensions/markdown-language-features/src/languageFeatures/documentLinkProvider.ts#L206
> 
> 
> 
> There's already code that checks if some links occur inside code blocks. This simply needs to be extended to cover all links
> 
> 
> 
> The relevant tests are in:
> 
> 
> 
> https://github.com/microsoft/vscode/blob/0e65adbda8f3b605d240b341dd8623203e16997d/extensions/markdown-language-features/src/test/documentLinkProvider.test.ts#L17

Will get to work, thank you!
