### ISSUE TITLE
Enable terminal smoke tests on desktop

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#146811]
With support for `playwright` for Electron tests, we should enable terminal tests:

https://github.com/microsoft/vscode/blob/a90f57b4a9267b53aa25552c6624bc82050f37c9/test/smoke/src/main.ts#L380

I eagerly had enabled them but since we don't know whether Electron smoke tests with `playwright` are stable, I moved back to only running them in web.

We should not enable these tests until we are sure, smoke tests are stable, so maybe this should only happen in May.

**Comment by bpasero** [comment]
Failing macOS run for reference: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=165082&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=2912d057-d0f3-5270-1d09-777eeaba2eea&l=51

**Comment by Tyriar** [comment]
Still not passing, deferring to a debt week https://github.com/microsoft/vscode/issues/152451
