### ISSUE TITLE
Copying a file from a file manager on Linux and pasting it into latest VS Code no longer gives the file path

### ISSUE THREAD

**Issue by hengwang322** [microsoft/vscode#146867]
Does this issue occur when all extensions are disabled?: Yes

On Linux, copying a file from file manager (e.g. nautilus) and pasting it into any text editor will paste the file path instead. This was also the case for previous versions of VS Code. However, in the latest version 1.66.0-1648620611, copying a file and pasting it into VS Code gives nothing. (But pasting into other text editor still works as intended). For now I have reverted back to 1.65.2-1646927742.

- VS Code Version: 1.66.0-1648620611
- OS Version: Ubuntu 18.04.6 LTS
- Nautilus Version 1:3.26.4-0~ubuntu18.04.5

Steps to Reproduce:

1. In nautilus, single click on a file to highlight/select it and hit Ctrl + C
2. In VS Code, create a new file and hit Ctrl + V
3. Expected behaviour: the file path of the selected file is pasted into VS Code.
4. Actual behaviour: nothing is pasted into VS Code.

**Comment by JacksonKearl** [comment]
Also seeing this on Mac.

**Comment by JacksonKearl** [comment]
I see we use `const result = document.execCommand('paste');` [here ](https://github.com/microsoft/vscode/blob/35f8ba6f6678a818f8d3e994643bd9f167c9c422/src/vs/editor/contrib/clipboard/browser/clipboard.ts#L226), which seems to not properly paste the file name anymore?

**Comment by deepak1556** [comment]
Only chromium change that went between 91 and 98 wrt to clipboard commands was https://chromium-review.googlesource.com/c/chromium/src/+/2927390 , do we use [EditContext](https://github.com/w3c/editing/blob/gh-pages/docs/EditContext/explainer.md) for our editor ?

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/146770
