### ISSUE TITLE
html editor cant beautify some code 

### ISSUE THREAD

**Issue by okansarica** [Microsoft/vscode#14689]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: danwahlin.angular2-snippets-0.10.4, robertohuertasm.vscode-icons-2.0.5

Steps to Reproduce:

1.write to code below to an html file and beautify it by ctrl k + ctrl d
<div class="row">
        <div class="col-sm-3">
            <select class="form-control">
        <option value="">Hour</option>
        <option value="00">00</option>
2.you will see that vscode doesnt indent option rows

**Comment by aeschli** [comment]
'select' is on the list of tags that should not be formatted (as a change can impact the rendered html).
See setting "html.format.unformatted" for the list and remove select there if you know what you do.
