### ISSUE TITLE
Typescript breaking

### ISSUE THREAD

**Issue by UlrikSandberg** [microsoft/vscode#146805]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Typescript not working

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.14.0-1029-oem
Restricted Mode: No
Remote OS version: Linux x64 5.14.0-1029-oem
Remote OS version: Linux x64 5.14.0-1029-oem
Remote OS version: Linux x64 5.14.0-1029-oem
Remote OS version: Linux x64 5.14.0-1029-oem

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|31.02GB (5.51GB free)|
|Process Argv|--unity-launch --crash-reporter-id 786a493e-0056-43ca-b459-7c62135d9446|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Container uni-compose_cloud-api2 (uni-compose_cloud-api2_1)|
|OS|Linux x64 5.14.0-1029-oem|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2600)|
|Memory (System)|31.02GB (5.51GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container uni-compose_cloud-backend (uni-compose_cloud-backend_1)|
|OS|Linux x64 5.14.0-1029-oem|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 3223)|
|Memory (System)|31.02GB (5.51GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container uni-compose_cloud-frontend (uni-compose_cloud-frontend_1)|
|OS|Linux x64 5.14.0-1029-oem|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2600)|
|Memory (System)|31.02GB (5.52GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container uni-compose_cloud-ui2 (uni-compose_cloud-ui2_1)|
|OS|Linux x64 5.14.0-1029-oem|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2600)|
|Memory (System)|31.02GB (5.55GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.231.3
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.5
prettier-vscode|esb|9.5.0
todo-tree|Gru|0.0.215
vscode-docker|ms-|1.21.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by mjbvz** [comment]
> Typescript not working

What does this mean?

/needsMoreInfo
