### ISSUE TITLE
What did you change in the webview url scheme?

### ISSUE THREAD

**Issue by bobbytreed** [microsoft/vscode#146830]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Attempt to fetch a file that exists in the extensions own directory using https://file+.vscode-resource.vscode-webview.net/c%3A/
2. Failure

It broke an hour ago, so it must be a recent change from what I can see. What's odd is that within the JS file loaded from the locally hosted html, it's able to import JS files using relative paths "../../node-modules/" which is what I need to build out the webview.

I don't know how or why the url scheme changed as I now get ERR_NAME_NOT_RESOLVED.  I looked through PRs and Issues, but it's not evident that the scheme changed.

**Comment by mjbvz** [comment]
Please fill in the issue template and describe the issue and provide steps to reproduce it 

/needsMoreInfo

**Comment by bobbytreed** [comment]
I can simplify it with a question.  

What is the current URL scheme as of the latest build for retrieving a local resource on disk within the workspace.

Is it still  https://file+.vscode-resource.vscode-webview.net/??
Because that is not working for me currently

**Comment by bobbytreed** [comment]
I mean this URL format, maybe I'm not being clear. Apologies.

https://code.visualstudio.com/api/extension-guides/webview#loading-local-content

Is this url scheme for loading local files still accurate?

The urls I receive back from  panel.webview.asWebviewUri(onDiskPath);

are not resolving anymore within the webview.
