### ISSUE TITLE
Reload window

### ISSUE THREAD

**Issue by Miko321** [microsoft/vscode#146845]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.65.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file and type anything.
2. Press Ctrl+Shift+P -> Reload Window.

Now the undo history (ctrl+z) is lost.
Is it a bug or a default behavior? If it's a default, how do I keep my undo history after calling `Reload Window?`

**Comment by connor4312** [comment]
This is as designed, but you may be interested in Local History that has been added in 1.66 https://code.visualstudio.com/updates/v1_66#_local-history

**Comment by Miko321** [comment]
I'm saving/editing a file, and nothing is showing in the TimeLine.
I've downloaded the 1.66 version, I'm testing with a file of only 100kb.

```
    "workbench.localHistory.enabled": true,
    "workbench.localHistory.maxFileSize": 9999,
```

@connor4312 does this work with any type of file? 
do I need to enable anything else?
