### ISSUE TITLE
TS Server stops while editing Typescript file(s)

### ISSUE THREAD

**Issue by crubach** [microsoft/vscode#146837]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

TS Server stops while editing Typescript file(s)

VS Code version: Code 1.66.0 (Universal) (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 6, 5|
|Memory (System)|16.00GB (0.56GB free)|
|Process Argv|. --crash-reporter-id 9d29530f-e1f9-41a4-875f-8456c9b39e22|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.37.0
atlascode|atl|2.10.11
vscode-perl|cfg|1.18.0
npm-intellisense|chr|1.4.1
perl-toolbox|d97|1.4.0
vscode-markdownlint|Dav|0.47.0
jshint|dba|0.11.0
vscode-eslint|dba|2.2.2
javascript-ejs-support|Dig|1.3.1
gitlens|eam|12.0.5
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.5.0
vscode-firefox-debug|fir|2.9.6
vscode-jest-runner|fir|0.4.48
code-runner|for|0.11.7
headwind|hey|1.7.0
perl-outline|hit|0.0.7
beautify|Hoo|1.5.0
jq-syntax-highlighting|jq-|0.0.2
vscode-position|jtr|1.1.2
node-module-intellisense|lei|1.5.0
nodejs-repl|los|0.5.15
openapi-lint|mer|1.2.0
file-downloader|min|1.0.11
vscode-docker|ms-|1.21.0
remote-containers|ms-|0.231.3
vscode-typescript-tslint-plugin|ms-|1.3.4
angular-console|nrw|17.14.1
vscode-jest|Ort|4.2.1
java|red|1.4.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.6.0
perl|ric|2.3.0
code-spell-checker|str|2.1.11
vscode-stylelint|sty|1.2.2
vscodeintellicode|Vis|1.2.18
vscode-java-debug|vsc|0.40.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.2
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
openapi-preview|zoe|1.7.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by crubach** [comment]
Not confirmed yet, but will download and test later today.

**Comment by jguerinet** [comment]
This was happening to me as well, found the solution here: #146473. Might be your case as well @crubach.

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this
