### ISSUE TITLE
Cannot update VSCode (Insider System Installer)

### ISSUE THREAD

**Issue by omidshojaee** [microsoft/vscode#146880]
Does this issue occur when all extensions are disabled?: Yes/No
Not related to extensions

- VS Code Version:
- OS Version: Windows 10 Pro 19044.1620

Steps to Reproduce:

1. Try to update the VSCode Insider to the current available version
2.

This is **not** a duplicate of other update issues because this is happening to the "System Installer" version.

I switched to "System Installer" version around 2 months ago because the "User Installer" version couldn't be updated and developers closed the issue without any fix.

Now this is happening again for System Installer version (Insider build).

![Screenshot 2022-04-06 105020](https://user-images.githubusercontent.com/31741561/161911355-87eec02c-32ef-45fc-89f8-b4dcbeb91a3f.png)

**Comment by joaomoreno** [comment]
/duplicate #47841

This issue is independent of System vs User installers. Please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by omidshojaee** [comment]
How about you fix the issue like hundreds of millions of Windows software and applications we can update for years?
