### ISSUE TITLE
Scroll sensitivity too high with Mac trackpad

### ISSUE THREAD

**Issue by teomor** [microsoft/vscode#146835]
Older versions had normal scroll sensitivity, but since I updated a few days ago  (I have actually re-installed the newest version because I upgraded my MacBook from a 13" Pro to the new 14" Pro and I installed everything from scratch) the sensitivity when scrolling with the trackpad is higher and it's a bit TOO high.

**Comment by charlesharries** [comment]
Looks like this is being addressed in #146403—waiting on some log output but for the moment the recommendation is to set the `workbench.list.mouseWheelScrollSensitivity` and `editor.mouseWheelScrollSensitivity` settings to ~0.4.

**Comment by teomor** [comment]
OK, sorry for reporting. I did try to find open issues on this topic, but somehow missed that one. I will close this issue and try the workaround.
Thank you!
