### ISSUE TITLE
Build fails on a clean clone of repo with SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by natenovielli** [Microsoft/vscode#14683]
- VSCode Version: Synced from Master
- OS Version:  Windows 10 

Steps to Reproduce:

1. Sync from master
2. Install all build dependencies from https://github.com/Microsoft/vscode/wiki/How-to-Contribute 
3. Run gulp

Gulp fails with 

> C:\src\vscode\build\gulpfile.vscode.js:213
                        ...builtInExtensions.map(e => `!extensions/${e.name}/**`)
                        ^^^

>SyntaxError: Unexpected token ...
>    at exports.runInThisContext (vm.js:53:16)
>    at Module._compile (module.js:373:25)
>    at Object.Module._extensions..js (module.js:416:10)
>    at Module.load (module.js:343:32)
>    at Function.Module._load (module.js:300:12)
>    at Module.require (module.js:353:17)
>    at require (internal/module.js:12:17)
>    at C:\src\vscode\gulpfile.js:70:17
>    at Array.forEach (native)
>    at Object.<anonymous> (C:\src\vscode\gulpfile.js:70:4)
>    at Module._compile (module.js:409:26)
>    at Object.Module._extensions..js (module.js:416:10)
>    at Module.load (module.js:343:32)
>    at Function.Module._load (module.js:300:12)
>    at Module.require (module.js:353:17)
>    at require (internal/module.js:12:17)

**Comment by octref** [comment]
What's your node version? If possible can you update node.

Seems your node doesn't support spread yet.

**Comment by natenovielli** [comment]
6.9.1 I'll try to update it and let you know how it goes.

**Comment by natenovielli** [comment]
Updated to 7.0.0 and am getting the same error.

**Comment by octref** [comment]
Both your versions should have object spread.

Are you running `gulp vscode-win32`?

Also, right before you run `gulp` on the CLI, can you run `node -v`? Maybe you don't have the correct `PATH` for node, and it's not using the latest version.

**Comment by natenovielli** [comment]
That was it!  Another set of dev tools I had installed earlier installed an old build of node and put it in the env variables.  Thanks for the help!

**Comment by natenovielli** [comment]
A tip if anyone runs into something similar, the "where" command in cmd was very helpful.  Type 'where node' in the command prompt, or 'where.exe node' in the powershell prompt and it will list all the directories where node is installed and registered with an env variable.  For me, I could see that my other dev tools were listed above the version of node that I installed.
