### ISSUE TITLE
TypeScrip: Support forward commands between ts plugin and ts server. 

### ISSUE THREAD

**Issue by Kingwl** [microsoft/vscode#146879]
We have issues: https://github.com/microsoft/vscode/issues/119489 and PRs: https://github.com/microsoft/vscode/pull/129382, https://github.com/microsoft/vscode/pull/146608

And in the ts side. There's already implemented add custom handler in ts plugin via https://github.com/microsoft/TypeScript/pull/44291.

I think It's better to register a builtin command such as `forwardTsServer` or others. 
And with that, we can shell command in our own vscode extension to send some command into tsserver. And handle the command in ts plugin.   
In this way, we can share the current ts program instance rather than create a new tsserver. And we can avoid tons of config/setup for the new tsserver which nearly no one can do that.

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/6831019/161909342-d321ee77-153c-4679-bbe6-34b2af58a1e7.png">

**Comment by mjbvz** [comment]
@kingwl For inline values, I assumed that we were going to add this functionality to VS Code's built-in TypeScript extension. Were you planning this ship this as a separate extension instead? Or do you have additional use cases for allowing a VS Code extension talk directly to a TS Server plugin?

**Comment by Kingwl** [comment]
> For inline values, I assumed that we were going to add this functionality to VS Code's built-in TypeScript extension. Were you planning this ship this as a separate extension instead?  

I'm ok with both of them.

> Or do you have additional use cases for allowing a VS Code extension talk directly to a TS Server plugin?

Basically, it's like this one: Do something what VSCode builtin extension does not implemented yet. 
For example,  `inline completions support`(before VSCode's and TypeScript support), `inlay hints preview` (before VSCode's support), `code lens` (using type informations), or some other standard lsp features who TypeScript does not provided yet.

For developers, It's more powerful for TypeScript and VSCode's integration.

And there's also a additional gift for VSCode's team and TypeScript team is: preview / early access editor features by provide some offical VSCode's extension. rather than follow the release schedule.

**Comment by mjbvz** [comment]
Thanks for the details.

I think we inline values support should be built into VS Code. However I can see how this might be useful for other extensions, although we should probably hold off on adding this until we have more concrete use cases 

When I discussed this with the TS team, we also had a few concerns:

- We want to prevent extensions from corrupting the TS server's state

    We likely want want to block any standard tsserver commands that could modify the server state, such as `updateOpene`

- How does an extension know if a custom command is available or not? (basically, how do you tell if the TS Server plugin is loaded?)

    Do we just let extensions make the request and have it fail? Do we also need some way where extensions can tell us the minimum TS version they require?

- For debugging and diagnostic purposes, we should include a flag that lets us tell if a command comes from VS Code or from an extension 

Anything I missed from our discussion @DanielRosenwasser?

**Comment by Kingwl** [comment]
Well... I just realized that we can start a tcp/websocket between ts plugin and vscode extensions.

So this feature request will not be required.

**Comment by Kingwl** [comment]
> preview / early access editor features by provide some offical VSCode's extension. rather than follow the release schedule.

For example :
![screen](https://user-images.githubusercontent.com/6831019/163381244-b6dea5eb-1d26-4efb-9791-f49f10ca2a77.gif)

https://github.com/Kingwl/power-ts-plugin
