### ISSUE TITLE
Cloud (☁️) emoji not rendering in terminal or editor on macOS Monterey 12.3.1

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode#146893]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.0
- OS Version: macOS Monterey 12.3.1

Steps to Reproduce:

1. Copy to either the terminal or editor: "☁️".
2. It won't render correctly:
    <img width="24" alt="image" src="https://user-images.githubusercontent.com/24731903/161929771-0f53f291-7000-457b-a988-25cfd063c120.png">

This happens with both `editor.fontFamily` set to the default and with `"editor.fontFamily": "'Meslo LG M for Powerline', Menlo, Monaco, 'Courier New', monospace"`.

![6bkl4h](https://user-images.githubusercontent.com/24731903/161930706-1bdd64bf-cb85-4cd7-b94a-8d0d3cc1b9df.jpg)

**Comment by Tyriar** [comment]
This depends on the font, the default shows the small blue one for me and my normal setup works fine:

```
"editor.fontFamily": "Hack, 'Powerline Extra Symbols', 'Hack NF'",
```
