### ISSUE TITLE
Bash syntax defect

### ISSUE THREAD

**Issue by canfoderiskii** [Microsoft/vscode#14686]
- VSCode Version: 1.6.1
- OS Version: Ubuntu 16.04

The defect looks like this:
![vscode](https://cloud.githubusercontent.com/assets/10685920/19827131/15b4e106-9dd2-11e6-927a-72d5268f41f8.png)

The single quote inside the string for `cat` affects the syntax parsing.

**Comment by aeschli** [comment]
This issue was moved to textmate/shellscript.tmbundle#33
