### ISSUE TITLE
Debug adapter type traceability

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14680]
I saw a couple SO questions where a user mentioned errors they saw while debugging, but could not say which extension was responsible for the debugging. Someone should be able to figure it out, but I noticed that there isn't really good traceability from launch config to extension and vice versa. And you could have 5 extensions installed for X, with two different debuggers, and it's not obvious which you're using to debug. Example:

Here's my launch config, which extension am I using? Maybe hovering over the value here could show the extension display name.
![image](https://cloud.githubusercontent.com/assets/323878/19824410/ed53d3c4-9d23-11e6-80e3-3a166cf2f55a.png)

(Also opened #14681 to track this)-> Which debug types are supported? I have to read the readme (I'm not sure someone in this situation would look at this page, but it might be good to have the debug adapter "type" here).
![image](https://cloud.githubusercontent.com/assets/323878/19824372/a30e97b8-9d23-11e6-968b-4c8ead9f8235.png)

**Comment by octref** [comment]
cmd-click -> goes to extension page might also be a good addition.
