### ISSUE TITLE
JavaScript use strict

### ISSUE THREAD

**Issue by zengbinsi** [Microsoft/vscode#14688]
- VSCode Version:1.4.0
- OS Version: mac OSX 10.12

Steps to Reproduce:

1. 编写js代码，在文件头输入'use strict'。
2. 编写不够严谨的js代码，运行没有任何提示，这不是一个友好的现象。

**Comment by octref** [comment]
linting is provided by extensions like:
https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint
