### ISSUE TITLE
Show/hide panel buttons missing

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#146898]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66
- OS Version: Windows 10

Steps to Reproduce:

1. Start VScode

There are now panel buttons (or whatever they are called) in the title bar:
![image](https://user-images.githubusercontent.com/152227/161935243-7b1282cc-9885-460a-9c60-e8c4c539719e.png)

Without the possibility to hide them. In my eyes, they add only noise, because I would use them once to set up the window layout to my liking, and then never having to use them ever again.

So:
1. There wasn't a need to have them *that* prominently in plain view.
2. I can't hide them, which IMO is a big oversight. Big enough to warrant a bug report.

**Comment by thany** [comment]
(or maybe I *can* hide them, but without so much as a single word about these new buttons in the release notes, I have no way of knowing if there's a setting for this, one that might go by a name I'm not imagining, or one that's not available through the settings GUI - in which case I still couldn't possibly know how to set this setting, should it exist)

**Comment by IllusionMH** [comment]
/question

These are features from 1.65 (February)
Please see feature description and how to control feature and it's display https://code.visualstudio.com/updates/v1_65#_new-layout-control-options

**Comment by IllusionMH** [comment]
Feature and settigns were added in 1.65. Only default was changed in 1.66 https://github.com/microsoft/vscode/commit/58966a9814a3b2c488d11af1a332832acadf887d

/cc @sbatten

**Comment by thany** [comment]
It doesn't matter when they were *technically* added. For users who don't or can't or shouldn't play with experimental features, they effectively don't exist until they are considered stable and suddenly appear.

The *least* thing that should've been done, is mention them in 1.66 release notes. Even as little as a link to 1.65 release notes. But definitely **not nothing**.
