### ISSUE TITLE
strange color of Oh-my-Zsh + p10k in vscode terminal on macbook

### ISSUE THREAD

**Issue by FischLu** [microsoft/vscode#146827]
I am using Oh-my-Zsh + p10k on a macbook, there are working fine in iterm2, but in vscode's terminal I see the color of the triangle before the git icon is strange, you can see here

<img width="423" alt="image" src="https://user-images.githubusercontent.com/10261662/161787651-7e1cb453-d615-40f2-ad58-e43ed6768f61.png">

However the triangle after the apple logo is correct. 

For the same path, what it looks like in iterm2 is

<img width="377" alt="image" src="https://user-images.githubusercontent.com/10261662/161787850-856f4ea5-4739-496d-983b-3a1a5b8ab6d1.png">

My relative configuration of vscode
```
"terminal.integrated.fontFamily": "MesloLGS NF",
"terminal.integrated.fontWeight": "normal",
"terminal.integrated.fontSize": 13,
"editor.fontSize": 15,
"window.zoomLevel": 0.85,
```
My iterm2 uses same font and size. Anyone can help me? Thank you.

**Comment by DuroCodes** [comment]
i have the same issue using starship, not sure how to fix sorry
