### ISSUE TITLE
cant sign in to vs code github across google chrome. error code NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by Tibades** [microsoft/vscode#146829]
Issue Type: <b>Bug</b>

cant sign in to github across google chrome. error code NET::ERR_CERT_AUTHORITY_INVALID

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:49:49.448Z)
OS version: Windows_NT ia32 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Atom(TM) CPU N550   @ 1.50GHz (4 x 1496)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|1.99GB (0.99GB free)|
|Process Argv|--crash-reporter-id 694a64da-0cfb-4ea5-974c-39dea4ac7bdf|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by TylerLeonhardt** [comment]
Quoting @deepak1556 from another issue with a similar title:

This would be a case of missing CA cert from your system certificate store. Did this break only with version 1.66 or is this an issue with older versions too ?

Can you attach the log following these steps:

* Clear any http(s)_proxy settings in vscode
* launch vscode with code.cmd --log-net-log=<some-absolute-path>/netlog.json
* Add the proxy settings
* Search for extensions
* Quit the application
* Attach the generated netlog.json, thanks!
