### ISSUE TITLE
VSCode randomly entered the word I was writting multiple times.

### ISSUE THREAD

**Issue by Corallus-Caninus** [microsoft/vscode#146861]
Issue Type: <b>Bug</b>

I didn't press any additional keys but the word I was typing was repeated 5 times for no apparent reason. please let me know how I can help further.

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 4650)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (6.86GB free)|
|Process Argv|--crash-reporter-id 4c606e35-4955-4935-a611-91bbfcc0cee1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
better-toml|bun|0.3.2
vscode-npm-script|eg2|0.3.24
copilot|Git|1.12.5517
vscode-pull-request-github|Git|0.40.0
todo-tree|Gru|0.0.215
rust-analyzer|mat|0.2.1002
git-graph|mhu|1.30.0
vscode-docker|ms-|1.21.0
vscode-edge-devtools|ms-|1.4.6
python|ms-|2022.4.0
vscode-pylance|ms-|2022.3.4
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.3
powershell|ms-|2021.12.0
java|red|1.4.0
vscode-yaml|red|1.6.0
bash-beautify|sha|0.1.1
even-better-toml|tam|0.14.2
vscode-lldb|vad|1.7.0
vscodeintellicode|Vis|1.2.18
vscode-java-debug|vsc|0.40.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.2
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
vim|vsc|1.22.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
pynewfile477:30463512

```

</details>

**Comment by gjsjohnmurray** [comment]
We're you accidentally setting multiple cursors? 

https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor

If you can reproduce the issue please use the Start Extension Bisect command to investigate whether one of your extensions is causing it.
