### ISSUE TITLE
Setting fails to return to unmodified state

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#146895]
1. In settings, search for `scm.diffDecorationsGutterPattern`
2. Uncheck the second checkbox
3. Check it again

🐛 Setting keeps displayed as having been modified

![Recording 2022-04-06 at 10 35 24](https://user-images.githubusercontent.com/22350/161932643-91bde7b0-cf38-4e74-915c-b8187b7de4b4.gif)

cc @lszomoru

**Comment by rzhao271** [comment]
\closedWith 6f7c121
