### ISSUE TITLE
vscode output and console  accented

### ISSUE THREAD

**Issue by mazhan465** [Microsoft/vscode#14687]
When I TRY build my .c file,the output window show '"C:/Program Files (x86)/Microsoft Visual C++ Build Tools/vcbuildtools.exe"' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by weinand** [comment]
@mazhan465 if you run your build script in a regular command prompt (instead in VS Code), what do you see there?

**Comment by mazhan465** [comment]
Sorry,I have been uninstall vcbuildtools and install GDB.So I can't remember theh output.

**Comment by weinand** [comment]
Without this information we cannot investigate.
