### ISSUE TITLE
There is a delay in displaying the entered text

### ISSUE THREAD

**Issue by ph3nac** [microsoft/vscode#146807]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0(intel chip)
- OS Version: macOS Catalina (10.15.7)

Steps to Reproduce:

1. enable quickSuggestions

    "editor.quickSuggestions": {
        "other": "on",
        "comments": "off",
        "strings": "off"
    },

2. Edit the JavaScript file

For example, when typing "const ", "cons" is displayed first and the remaining characters are displayed after a delay of several hundred milliseconds.
The delay in displaying the input text is perceptible, so editing the text is not smooth.

This issue does not occur when "editor.quickSuggestions.other" is set to "inline" or "off", or if "editor.quickSuggestionsDelay" is set to about 300 ms.

This issue does not occur with vscode version 1.65.2

**Comment by jrieken** [comment]
> "cons" is displayed first and the remaining characters are displayed after a delay of several hundred milliseconds.

Display where? In the suggest widget or as ghost text?

**Comment by ph3nac** [comment]
My English is not fluent and I do not know what "ghost text" means. Also, It is not the display in the Suggest widget.
It is the display in the editor line.
Here is how it behaves when actually typing.

This gif is a screen recording played back at 50% speed.
The upper half of the gif shows the behavior with vscode version 1.65.
The lower half of the gif shows the behavior with version 1.66.

The speed of keystrokes is almost the same.
In v1.65, "const " is displayed smoothly, while in v1.66, "cons" is displayed smoothly, but there is a lag after that and "t " is displayed (I am not intentionally slowing down the typing).

This lag is perceptible and makes typing difficult


![result](https://user-images.githubusercontent.com/100564304/161997790-47b178f8-99fd-4a50-ad84-a39f9158fae4.gif)

**Comment by jrieken** [comment]
Can you retry with `"editor.suggest.preview": false`?

**Comment by ph3nac** [comment]
The same problem occurs when "editor.suggest.preview":false is set.

The same problem occurs if all extensions are disabled and nothing is specified in settings.json.

**Comment by jrieken** [comment]
> enable quickSuggestions

And this doesn't reproduce with quick suggestions off?

**Comment by ph3nac** [comment]
> > enable quickSuggestions
> 
> And this doesn't reproduce with quick suggestions off?

Setting quickSuggestions to "off" does not cause this problem

**Comment by jrieken** [comment]
For me this doesn't show. So please prepare a full repo sample, e.g file/project where this can be seen in isolation. Also create a CPU profile of the renderer please, this explains how to do so: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

**Comment by ph3nac** [comment]
This was caused by the vscode integration of [fig](https://github.com/withfig/fig). Disabling fig solved the problem.
Thanks for your support so far.
