### ISSUE TITLE
[Bug] Text highlighting/bold text while typing text on Google IME

### ISSUE THREAD

**Issue by yuis-ice** [microsoft/vscode#146814]
Does this issue occur when all extensions are disabled?: Yes/No

Yes

- VS Code Version:

 v1.64.2

- OS Version:

Windows 10 Pro v2009

Steps to Reproduce:

After I accidentally updated vscode to v1.64.2 from v1.62.x, I started to get this weird text highlighting (or bold text, weighted text) while I type text through Google IME (for example the Google Japanese Input Tool) 

[![enter image description here][1]][1]

As a comparison this is something you see when the text is not highlighted. 

[![enter image description here][2]][2]

(* I mean the second line on the image the issue is. The first line is highlighted in yellow but this is just a "find" highlighting I forgot to close before taking the screenshots

I believe this is a bug, I'd like to know how to fix this, or in the case this is a new feature, I'd like to know how to disable it and I believe it would help the community and people who have the same problem. Thanks.

  [1]: https://i.stack.imgur.com/LdcdD.png
  [2]: https://i.stack.imgur.com/G124z.png

**Comment by alexdima** [comment]
@yuis-ice Please update to the latest vscode version, we have fixed a lot of IME issues in the recent months.

**Comment by imyzf** [comment]
<img width="199" alt="image" src="https://user-images.githubusercontent.com/8298849/167358214-2e078708-711b-437f-9c6e-e2c0cd0ff55a.png">
<img width="391" alt="image" src="https://user-images.githubusercontent.com/8298849/167358223-29fedd2f-c011-4a3b-b628-277e5e58a301.png">

Similar issue after update to 1.67.0，using Sogou Chinese input in macOS. @alexdima
