### ISSUE TITLE
Remove the notebookEditorDecorationType api proposal

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#146838]
The `notebookEditorDecorationType` currently is not on track for finalization. In order to decide what to do with it, we would like to know how this api is currently being used and if there would be any big concerns around removing it

Here are the current consumers:

- [x] Jupyter @rchiodo @DonJayamanne 
- [x] Jupyter powertoys @rchiodo @DonJayamanne 
- [x] Dot Net Interactive @brettfo, @colombod

Please check if your extension is using this api. If it is, can you explain how the api is used today and if there are alternative approach you could use to implement the functionality?

**Comment by mjbvz** [comment]
Thanks @rchiodo! Should I open an issue against Jupyter tracking its removal?

**Comment by rchiodo** [comment]
Good idea. Just did :)

**Comment by mjbvz** [comment]
Confirmed dot net is not using this

**Comment by mjbvz** [comment]
Ah looks like Jupyter powertoys started using this now too? @rchiodo Can you please let me know if this was just copy/pasted over or if this is a real user

**Comment by rchiodo** [comment]
I don't think it is? The enabled list is this:

https://github.com/microsoft/vscode-jupyter-powertoys/blob/2dfc5d244f6259a4298d8b817c9b04d559f02fe1/package.json#L46
```
    "enabledApiProposals": [
        "notebookEditor",
        "notebookEditorEdit"
    ],
```

This issue is about the 'notebookEditorDecorationType', I think?

**Comment by mjbvz** [comment]
Great! Thanks for confirming. I'll go ahead and update its list of proposed apis to match what I see in the `package.json`

**Comment by mjbvz** [comment]
All consumers have now been removed but we'll hold of on removing this API until a new version of Jupyter is published

**Comment by mjbvz** [comment]
@alyssajotice Can you please let me know if liveshare is using this api? It's not listed as an official consumer but @rebornix thought you may still be using it to render user names on cells

**Comment by alyssajotice** [comment]
Live Share does not use this API.

**Comment by mjbvz** [comment]
All users have now been removed and we've also removed the implementation

Thanks for the help everyone!

**Comment by rdeline** [comment]
I'm not an official customer, but we have a prototype in Microsoft Research that uses this feature to indicate which of several cell outputs is currently visible (eyeball below). Is there any suggested substitute for this feature?

![image](https://user-images.githubusercontent.com/109971/173658896-e26e49e0-c367-46a2-869a-ab10ae14fca1.png)

**Comment by mjbvz** [comment]
@rdeline Is the eyeball shown for a specific line or for the entire cell?

**Comment by rdeline** [comment]
The eyeball is shown for a specific line (line 7 above). In this image, only line 7 has the decoration, but in general we allow users to select an arbitrary set of lines. If you're curious, there's an output render below the code (not shown) that is sensitive to which line(s) the user has selected. The output render shows visualizations specific to those chosen lines. (It makes our notebooks really compact, while still allowing quick access to every visual output.)

**Comment by mjbvz** [comment]
@rebornix Would the standard editor decorators apis work for their use case?

**Comment by rebornix** [comment]
@mjbvz @rdeline the editor decorations api is responsible for this feature, I don't think we need to use the notebook one.
