### ISSUE TITLE
typescript dies while trying to activate intelisense

### ISSUE THREAD

**Issue by gheiler-on** [microsoft/vscode#146828]
Issue Type: <b>Bug</b>

After doing some copy pasting of folders and start replacing some class names typescript start dying while trying to activate intelisense

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|11, 9, 7|
|Memory (System)|16.00GB (0.38GB free)|
|Process Argv|--crash-reporter-id 38b8ae4f-f2f6-46d0-ab22-d7ea9149c3ee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.19.9
path-intellisense|chr|2.8.0
codestream|Cod|12.14.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.2
sync-env|don|1.0.6
xml|Dot|2.5.1
gitlens|eam|12.0.5
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
vscode-jest-runner|fir|0.4.48
vscode-pull-request-github|Git|0.40.0
terraform|has|2.21.0
beautify|Hoo|1.5.0
vscode-edit-csv|jan|0.6.8
vscode-gutter-preview|kis|0.30.0
code-groovy|mar|0.1.2
dotenv|mik|1.0.1
vscode-azureappservice|ms-|0.23.1
vscode-azurefunctions|ms-|1.6.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.13.0
vscode-azurevirtualmachines|ms-|0.5.0
vscode-bicep|ms-|0.4.1318
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.21.0
csharp|ms-|1.24.3
vscode-dotnet-runtime|ms-|1.5.0
data-workspace-vscode|ms-|0.1.1
mssql|ms-|1.13.0
sql-database-projects-vscode|ms-|0.14.1
azure-account|ms-|0.10.1
azurecli|ms-|0.5.0
test-adapter-converter|ms-|0.1.5
vscode-node-azure-pack|ms-|0.2.1
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5449
azurerm-vscode-tools|msa|0.15.6
vetur|oct|0.35.0
tslint-vue|pro|1.5.6
typescript-hero|rbb|3.0.0
salesforcedx-vscode-soql|sal|54.6.1
quokka-vscode|Wal|1.0.455
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
vscaat:30438848
pynewfile477:30463512

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by gheiler-on** [comment]
@mjbvz  That is actually the case.

**Comment by mjbvz** [comment]
Thanks for checking. Closing as not reproducible. The most likely cause is one of your extensions
