### ISSUE TITLE
Error while turning on Setting Sync

### ISSUE THREAD

**Issue by Hardik-Kushwaha** [microsoft/vscode#146819]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.0
- OS Version: Ubuntu 20.04.4
Signed in to GitHub but while turning on setting sync it showing error message "Error while turning on Settings Sync. Cancelled"
![Screenshot from 2022-04-05 18-47-58](https://user-images.githubusercontent.com/72149298/161762983-4fe229e0-58c1-4138-8956-614694dc4c30.png)

**Comment by sandy081** [comment]
May I know if you able to sing in to GitHub successfully?

**Comment by Hardik-Kushwaha** [comment]
Issue solved by re-installing VS Code
