### ISSUE TITLE
Prevent auto-closing feature from auto closing if the character next to the caret is a space or an end of line.

### ISSUE THREAD

**Issue by vdegenne** [microsoft/vscode#146812]
Everything is in the title.
There is this annoying behavior, the **auto-closing** feature will auto-close parenthesis, brackets, etc... on code reformation.
By code reformation I mean when you're not following your line of thoughts, and go back somewhere in your code to perform a modification. **auto-closing** is great and keep your right little pinky finger from doing extra workout in the former.
But in the latter you usually do not want it.
One basic example is when you want to enclose a chunk of code into brackets.
You go back before what is to be enclosed and then you start typing your function and then this happens :

```javascript
console.log()myvariable
```

Everyone who uses vim know that this is seriously counter-productive. It looks like it's nothing, but any good programmers also know that it's the little details prevented from being repeated over and over that makes the biggest time savings and give you overall satisfaction about your code.

**Comment by hediet** [comment]
Can you share a gif? Thanks!

**Comment by vdegenne** [comment]
![ezgif-5-3eca1cc612](https://user-images.githubusercontent.com/2827383/162194708-c543e242-18a9-40ce-8510-b4487c1fa74d.gif)

**Comment by vdegenne** [comment]
As a heads-up, IDE such as WebStorm are already implementing this behavior.
I thought I'd give a little taste to be sure you understand what I am referring to, also just to showcase how smooth it is to write code with such little improvements.

https://user-images.githubusercontent.com/2827383/163384280-ac21b1c6-d3cc-4f2c-9f4d-5aa5126a5c64.mp4

**Comment by hediet** [comment]
You mean "Prevent auto-closing feature from auto closing **unless** the character next to the caret is a space or an end of line. ", right?

**Comment by vdegenne** [comment]
> You mean "Prevent auto-closing feature from auto closing **unless** the character next to the caret is a space or an end of line. ", right?
> 
> Thanks for the gifs btw!

Sorry so much trouble just to realize this option was already implemented (`beforeWhiteSpace`).
