### ISSUE TITLE
offline vscode install intellicode model

### ISSUE THREAD

**Issue by yuqingzhijie** [microsoft/vscode#146870]
my computer is offline.when i install some extensions, such as todo highlight, vscode has a error message, "couldn't download intellicode model. please check your network connectivity or fire wall settings. "So i suggest that  vscode support install intellicode model offline

**Comment by sandy081** [comment]
I am wondering how are you able to search extensions from Marketplace when you are offline?

**Comment by yuqingzhijie** [comment]
I can upload files in some ways
But I can't access the network normally and am restricted by the team leader

**Comment by sandy081** [comment]
It seems you are having network access but behind some proxy set up. I am not sure if we can do anything here.
