### ISSUE TITLE
launchservicesd CPU usage on MacOS Sierra

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14685]
I have been seeing this for at least few days but I just made the connection to vscode. Possibly since updating to 10.12.1. Would be great if someone else can try to repro.

I'll have several instances of Insiders open, not doing anything unusual, then notice that I'm using a ton of CPU of launchservicesd, Dock, and loginwindow.

Like this -
![image](https://cloud.githubusercontent.com/assets/323878/19825999/22a0ac7a-9d36-11e6-829f-3834ba2af521.png)

The flat part of this graph, I was not touching the computer. When it goes up, I opened one more vscode instance. Then I cmd+q the whole thing and it all goes away.
![image](https://cloud.githubusercontent.com/assets/323878/19826004/31191580-9d36-11e6-82b5-30d3c64a401e.png)

And those processes are not used so much anymore
![image](https://cloud.githubusercontent.com/assets/323878/19826002/2c626bc2-9d36-11e6-8956-b16cb26a7b29.png)

The next plateau is opening some project in insiders, and a few empty workspaces
![image](https://cloud.githubusercontent.com/assets/323878/19826021/801e74c2-9d36-11e6-9f86-4ce2e94ca94e.png)

And closing that, then there is a small spike at the right - that's opening the same project and empty workspaces in stable Code, and it stays pretty flat after this.
![image](https://cloud.githubusercontent.com/assets/323878/19826032/afaaa4d6-9d36-11e6-86a7-75fee7b1ac6b.png)

This is with four empty workspaces open, closing them slowly one by one - 
![image](https://cloud.githubusercontent.com/assets/323878/19826080/b0574942-9d37-11e6-9b39-5aeaba3c31c3.png)

I can't find anything relevant about these processes. I can't repro with atom or atom beta, but they are using earlier electron versions.

**Comment by roblourens** [comment]
And I don't notice any slowness, I only noticed because the macbook fan kept running loudly.

**Comment by roblourens** [comment]
It's an extension...

**Comment by roblourens** [comment]
It's the spotify extension...

**Comment by ndbroadbent** [comment]
Wow, thanks @roblourens. This extension was also killing my laptop, and it's not the most critical thing :)

**Comment by bdesmarez** [comment]
Same here, thanks for finding this !
