### ISSUE TITLE
Codelens references broken after March update

### ISSUE THREAD

**Issue by buondevid** [microsoft/vscode#146818]
Does this issue occur when all extensions are disabled?:  Yes, I tried with all the extensions disabled and restarted VSCode as well

- VS Code Version: 1.66
- OS Version: MacOS Monterey 12.0.1

Steps to Reproduce:

1. Downgrade VSCode to February (1.65) version
2. Activate this option: 
![image](https://user-images.githubusercontent.com/36935593/161761321-be334817-a5fd-476d-b84a-b62240832d0c.png)
3. Check that references above exports are displayed correctly

Then:

1. Upgrade to March (1.66) version
2. Keep the option still On
3. Check that references above `export`s don't show up anymore

**Comment by buondevid** [comment]
Thanks for the help!

So I've just installed the Insiders Build, no extensions were added and only 2 settings activated to try them:

Result: I still don't get references above exports anymore. 
![image](https://user-images.githubusercontent.com/36935593/161969788-de89fb0e-1d10-42cf-83e7-847e0b6a864a.png)![image](https://user-images.githubusercontent.com/36935593/161969667-fdf2be9f-1031-4ddf-be4a-eaf4d178332b.png)

Am I doing something wrong?

**Comment by mjbvz** [comment]
Please share a self contain code sample (as text) that detonates the issue so we can investigate

**Comment by veken1199** [comment]
I can confirm that my own extension also is experiencing this issue on Version: 1.66.0 (Universal). I have yet to dig into what is actually causing the issue.

**Comment by buondevid** [comment]
@mjbvz 

```js
// ./LabelBadgeSlider.js
import cx from 'classnames';
import PropTypes from 'prop-types';
import { useRef, useEffect, useState } from 'react';

import styles from './LabelBadgeSlider.scss';

/**
 * Colored label badge that automatically scrolls long text on hover.
 */
function LabelBadgeSlider({ labelName, labelColor, labelBackground, htmlFor, className, isClickable }) {
  const [labelCalcs, setLabelCalcs] = useState({ isLabelOverflowing: false, labelWidth: '100%' });
  const span = useRef();
  const label = useRef();

  useEffect(() => {
    const isLabelOverflowing = span.current.scrollWidth > span.current.offsetWidth;
    const labelWidth = isLabelOverflowing ? `${label.current.offsetWidth * 0.75}px` : '100%';
    setLabelCalcs({ isLabelOverflowing, labelWidth });
  }, []);

  return (
    <label
      className={cx(styles.label, { [styles.clickable]: isClickable }, className)}
      htmlFor={htmlFor}
      style={{
        '--_label-color': labelColor,
        '--_label-background-color': labelBackground,
        '--_label-overflow-delta': labelCalcs.labelWidth,
      }}
      ref={label}
    >
      <span className={styles.dot} />

      <span ref={span} className={styles.text}>
        {labelName}
      </span>
    </label>
  );
}

LabelBadgeSlider.propTypes = {
  /** If true, style the label as clickable (e.g. cursor: pointer). */
  isClickable: PropTypes.bool,
  /** The label name. */
  labelName: PropTypes.string.isRequired,
  /** The color of the dot. */
  labelColor: PropTypes.string,
  /** The background color of the label. */
  labelBackground: PropTypes.string,
  /** The html `for` attribute to bind the label to an input. */
  htmlFor: PropTypes.string,
  className: PropTypes.string,
};

export default LabelBadgeSlider;
```
![Screenshot 2022-04-07 at 10 17 08](https://user-images.githubusercontent.com/36935593/162153593-f94e70cb-850a-4cbe-9644-97a43855f24b.png)
![Screenshot 2022-04-07 at 10 18 03](https://user-images.githubusercontent.com/36935593/162153600-37b2a035-8548-4d4d-a224-03b4ea4df7e4.png)
![Screenshot 2022-04-07 at 10 18 12](https://user-images.githubusercontent.com/36935593/162153602-34549a0f-2a1d-4d78-a152-c297ccb0a709.png)

**Comment by buondevid** [comment]
@mjbvz Tested a bit more and it looks like it's not broken but there was a UI change with the new version: **the references are now showing above the function declaration and not on the exports anymore**.

The problem of this when using React is that often the components are declared with a `const` declaration using _arrow functions_ and apparently, VSCode doesn't understand that that is a function and doesn't give references.

![Screen Recording 2022-04-07 at 11 37 17](https://user-images.githubusercontent.com/36935593/162170006-4d300204-bdbe-4f71-a2d6-3093c125311f.gif)

So the problem is a combination of the:
- new Ui behavior of references
- React components declared with arrows functions (and, in general, all the exported arrow functions won't get references even when exported)

**Comment by mjbvz** [comment]
Can you please share a code snippet that demonstrates the issue?

**Comment by buondevid** [comment]
> Can you please share a code snippet that demonstrates the issue?
@mjbvz 
```jsx
import cx from 'classnames';
import PropTypes from 'prop-types';
import { useRef, useEffect, useState } from 'react';

import styles from './LabelBadgeSlider.scss';

/**
 * Colored label badge that automatically scrolls on hover long text .
 */
const LabelBadgeSlider = ({ labelName, labelColor, labelBackground, htmlFor, className, isClickable }) => {
  const [labelCalcs, setLabelCalcs] = useState({ isLabelOverflowing: false, labelWidth: '100%' });
  const span = useRef();
  const label = useRef();

  useEffect(() => {
    const isLabelOverflowing = span.current.scrollWidth > span.current.offsetWidth;
    const labelWidth = isLabelOverflowing ? `${label.current.offsetWidth * 0.75}px` : '100%';
    setLabelCalcs({ isLabelOverflowing, labelWidth });
  }, []);

  return (
    <label
      className={cx(styles.label, { [styles.clickable]: isClickable }, className)}
      htmlFor={htmlFor}
      style={{
        '--_label-color': labelColor,
        '--_label-background-color': labelBackground,
        '--_label-overflow-delta': labelCalcs.labelWidth,
      }}
      ref={label}
    >
      <svg viewBox="0 0 6 6" xmlns="http://www.w3.org/2000/svg" className={styles.dot}>
        <circle cx="3" cy="3" r="3" />
      </svg>
      <span ref={span} className={styles.text}>
        {labelName}
      </span>
    </label>
  );
}

LabelBadgeSlider.propTypes = {
  /** If true, style the label as clickable (e.g. cursor: pointer). */
  isClickable: PropTypes.bool,
  /** The label name. */
  labelName: PropTypes.string.isRequired,
  /** The color of the dot. */
  labelColor: PropTypes.string,
  /** The background color of the label. */
  labelBackground: PropTypes.string,
  /** The html `for` attribute to bind the label to an input. */
  htmlFor: PropTypes.string,
  className: PropTypes.string,
};

export default LabelBadgeSlider;
```

https://user-images.githubusercontent.com/36935593/162404860-c4879c26-9ecf-44de-9af4-ad938f2ded95.mov

![Screenshot 2022-04-08 at 11 11 50](https://user-images.githubusercontent.com/36935593/162404923-e69802a3-9ed4-4e6a-aed9-8e4463627ba6.png)
![Screenshot 2022-04-08 at 11 12 01](https://user-images.githubusercontent.com/36935593/162404962-88e2ac8b-990a-499b-a35a-885c77fae0df.png)
