### ISSUE TITLE
Stack trace doesn't show up (in a very specific case)

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14684]
First off, this reproes in 1.6.1 and 1.7-insiders
- Open a new vs code window, because this only reproes in the first debugging session
- Open the file explorer in the sidebar
- Hide the sidebar (if the debug panel was the open pane when hiding it, this doesn't repro)
- Start debugging
- Hit a breakpoint
- Open the debug panel
- There is no stack trace

If you step, the stack trace and everything works as normal. If you do anything different from those steps, it doesn't repro. But with those steps it happens 100% of the time on OSX and Windows.

![image](https://cloud.githubusercontent.com/assets/323878/19825818/4a55840a-9d33-11e6-8bae-cdf6ceb3094d.png)

**Comment by octref** [comment]
Have seen this too. A bit annoying.
