### ISSUE TITLE
Wrong behavior when right-click on a open file

### ISSUE THREAD

**Issue by casmelad** [microsoft/vscode#146843]
Issue Type: <b>Bug</b>

ubuntu 20.04

Sometimes when you right-click on a file open the contextual menu does not stay open, I am not really sure what i need to do in order to reproduce the issue, but it is really anoying.

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:41.156Z)
OS version: Linux x64 5.14.0-1031-oem snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1700)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 1, 1|
|Memory (System)|15.37GB (0.54GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch /home/adrian.castan/Documents/projects/go/cfa-items-api --crash-reporter-id ef060483-f4dc-4a3e-9a7a-d7074a18f51c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.9.3
atlascode|atl|2.10.11
vscode-intelephense-client|bme|1.8.2
githistory|don|0.6.19
go|gol|0.32.0
vscode-ksdiff|kal|1.0.0
diff-merge|mos|0.6.1
vscode-docker|ms-|1.21.0
remote-containers|ms-|0.231.3
remote-wsl|ms-|0.66.0
vscode-yaml|red|1.6.0
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe #113175

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/113175
