### ISSUE TITLE
sudo with user-data-dir results in white screen.

### ISSUE THREAD

**Issue by Henripru** [microsoft/vscode#146847]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66
- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:

1. launch code from terminal with command `sudo code . -user-data-dir /home/user/`. CWD is /root/somedir
2. Result is a completely white window. (Popups partially work, and window title updating as I ctrl+w to close files)
3. This has always worked in the past. 

Edit: 
adding --no-sandbox argument has no effect

**Comment by gjsjohnmurray** [comment]
See also #146836

**Comment by hello-smile6** [comment]
coder/code-server#5067 may be related

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/146445

VSCode cannot be run as sudo due to the application sandbox https://code.visualstudio.com/updates/v1_59#_progress-for-electron-sandbox-support

**Comment by michaelmoy** [comment]
It looks like it started in rev 1.66 on my Linux systems.

I uninstalled and installed 1.65 from here:

https://code.visualstudio.com/updates/v1_65
