### ISSUE TITLE
White page when open Vscode

### ISSUE THREAD

**Issue by estebanchi** [microsoft/vscode#146836]
im trying open VSCODE with command `sudo code --user-data-dir --no-sandbox`
and get white page in the workspace
![image](https://user-images.githubusercontent.com/57762372/161807938-01366081-8d96-462b-946f-c5ba86dd678f.png)
my OS System version Ubuntu 20.04
this bug happens after update 1.66 march version

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/146445

VSCode cannot be run as sudo due to the application sandbox https://code.visualstudio.com/updates/v1_59#_progress-for-electron-sandbox-support
