### ISSUE TITLE
Socket hang up when deploying Azure Functions

### ISSUE THREAD

**Issue by lainean** [microsoft/vscode#146885]
Deployment using Azure Functions Extension (Deploy to Function App...) fails with VSCode version 1.66. When changed to previous version 1.65.2 of VSCode, everything works fine.

Azure Functions output logs:
9:45:47 AM xx-functions: Starting deployment...
9:45:51 AM xx-functions: Creating zip package...
9:46:06 AM xx-functions: Zip package size: 20.2 MB
10:01:42 AM: Error: request to https://xx-functions.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: socket hang up

**Comment by rolfback** [comment]
Same here. Restarted deployment slot. Created new deployment slot. Restarted computer. Nothing helped except downgrading VS Code to 1.65.2 that I downloaded from [here](https://code.visualstudio.com/updates/v1_65#_workbench).

**Comment by mjbvz** [comment]
Please file this against the Azure Functions Extension

**Comment by leobastin** [comment]
Socket hang up while deploying to azure functions 

VS Code Version: 1.66.0
OS: Darwin x64 21.3.0 (Mac OS Monterey 12.2.1) 

11:46:39 AM Starting deployment...
11:46:46 AM Creating zip package...
11:46:49 AM Zip package size: 1.27 MB
12:02:58 PM: Error: request to https://<appname>.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: socket hang up

**Comment by oliver-sharplin** [comment]
> Same here. Restarted deployment slot. Created new deployment slot. Restarted computer. Nothing helped except downgrading VS Code to 1.65.2 that I downloaded from [here](https://code.visualstudio.com/updates/v1_65#_workbench).

Thank you!
