### ISSUE TITLE
Remote extension host does not respect trace log

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#146897]
Steps to Reproduce:

1. run `yarn smoketest --web --verbose`
2. cd `.build/logs/smoke-tests-browser/exthost1`
3. look at `exthost.log`

🐛  no tracing is enabled

I am passing `--log trace` here:

https://github.com/microsoft/vscode/blob/18377e6ee2484f76c4ed3f185ef4561e29b70bfb/test/automation/src/playwrightBrowser.ts#L62-L64

**Comment by alexdima** [comment]
@aeschli I think perhaps the test resolver could launch the server with the verbose flag [here](https://github.com/microsoft/vscode/blob/91d0063ff3983fde0cd0f15c0dea51c5c25f62a3/extensions/vscode-test-resolver/src/extension.ts#L106) ?

**Comment by aeschli** [comment]
There's currently no vscode API except for an internal command `_extensionTests.getLogLevel`

**Comment by aeschli** [comment]
I added an env variable TESTRESOLVER_LOG_LEVEL for the test resolver.

But Ben's issue is not about the test resolver. the web smoke tests start the code server directly.
I think the log level passed to the code server is only for the server process. The extension host process gets the log level from the connected window. For web, I believe the log level can be set in the browser URL with `?logLevel=trace`.

**Comment by alexdima** [comment]
> But Ben's issue is not about the test resolver. the web smoke tests start the code server directly.

Sorry, I missed that this is about the web. I tried looking, but I'm having a bit of a trouble finding where exactly we're spawning the server for the browser smoke tests. @bpasero the spawn location could pass the `--verbose` CLI argument to the server.

**Comment by aeschli** [comment]
I verified that adding `payload=[["logLevel","trace"]]` to the browser URL turns on the extension host trace logs.
Starting `code-server --verbose` still only gets you info logs.
