### ISSUE TITLE
Incorrect "Variable assigned but never used" error flagged

### ISSUE THREAD

**Issue by jimb2g** [microsoft/vscode#146877]
$Columns = 6    # display data across n columns
'abcdefghijklmnopqrsyuvwxyz' -split '' |  # test strings  
  ForEach-Object  -Begin { $n = 0 } -Process { Write-Host $_.padright(8) -NoNewline; if( $n % $Columns -eq 0 ) { Write-Host }; $n++ } -End { Write-Host }

The above code runs but shows a problem "Variable n assigned but never used."  In fact, $n is used in the Process code but this is not detected. 

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by Lemmingh** [comment]
/extPowershell

* <https://github.com/PowerShell/PSScriptAnalyzer/issues/1163>
