### ISSUE TITLE
Explore improving the discoverability of filtering in tree views

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#146806]
Refs https://github.com/microsoft/vscode/issues/140601

During the last iteration we explore how we could improve the discoverability of filtering in tree views, so this issue aims to bring the discussion around the specific design interaction. Currently you have to place your focus in a tree view and then start typing. In this exploration, we'll propose to surface an entry point in the view toolbar via a dedicated action. We could alternatively add this to an ellipsis menu to reduce the visual clutter. Lastly, we'll look at simplifying the filtering options and only filter the results (as opposed to highlighting the matches).

https://user-images.githubusercontent.com/35271042/161711088-f19a1344-4768-4ceb-8376-16de84d00a15.mp4

@joaomoreno would love feedback here on the proposal and any additional options we can explore.

Related Issue
- #70646
- #140563

**Comment by joaomoreno** [comment]
Coincidence: https://github.com/microsoft/vscode/issues/146821

I really like the sketched video. Unsure if it's clear given your description, but we do have a setting to change from highlighting to filtering `workbench.list.keyboardNavigation`... maybe you meant changing its default?

**Comment by misolori** [comment]
I do wonder how many people navigate the tree with the typical "type `A`" pattern as I've used those patterns before in lists, but they tend to be more ephemeral and not stick around. In the current feature, if you type to navigate and then continue clicking to your target, the filter stays visible which is different from other patterns. Would love to experiment to see if there is a way to balance between the two. I think a more natural progression is to still navigate on keypress but don't use the filter UI (which more closely mirrors Finder/Windows Explorer). Here's a few other ideas:

## Option A

This one closely mirrors what we already have except it shows a cursor to indicate the focus of input and has an icon as the entry point.

https://user-images.githubusercontent.com/35271042/164558850-6c85eb55-98eb-4577-a338-75a5d030f629.mp4

## Option B

This one explores if we had a "mode" where it strictly filters the results (what I would expect to be the default behavior).

https://user-images.githubusercontent.com/35271042/164558993-7ec58f1d-e7ba-4030-8cc8-6759b0b20475.mp4

**Comment by misolori** [comment]
Here's the latest version where we try to use the find widget interaction to make it much more clearer how to use it. I also explore moving the collapse folder and filter actions into an ellipsis.

https://user-images.githubusercontent.com/35271042/167702888-691733d5-a3ca-431b-88af-74bdd388842e.mp4
