### ISSUE TITLE
Local file history is preserved even after checking out another Git branch and the file content is different.

### ISSUE THREAD

**Issue by infinnie** [microsoft/vscode#146878]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.0
- OS Version: Windows 7

Steps to Reproduce:

1. Make local changes to a certain file and save for multiple times.
2. Commit the file.
3. Switch to another branch where the file exists and is not changed.
4. The local history still preserves the changes made in step 1.

**Comment by bpasero** [comment]
Not sure what you expect here, the local history feature is actually very simple:
* when a file is saved (from the editor, not from anywhere else like e.g. git)
* make a copy of the file contents in the history folder

**Comment by infinnie** [comment]
When a Git operation overrides the local history, discard it instead of keeping it.

**Comment by bpasero** [comment]
> discard the local history

😱 , the idea of local history is to allow you to get back to previous contents. discarding any entry in local history would be against the idea of the feature in general.

**Comment by infinnie** [comment]
> > discard the local history
> 
> :scream: , the idea of local history is to allow you to get back to previous contents. discarding any entry in local history would be against the idea of the feature in general.

Thanks for explanation.
