### ISSUE TITLE
Keyboard not working correctly (only some keys work)

### ISSUE THREAD

**Issue by MR-T77** [microsoft/vscode#146825]
This bug has been happening for some time (a few months), and it just makes the keyboard inoperable on VSCode.
E.g. some keys don't work (Enter, Backspace, Delete,...)
I can't define exact steps to reproduce, as this happens only sometimes.
What I usually do is restart VSCode, and the problem disappears, only to get back after a while. Out of VSCode, keyboard works well with all other applications.

Seems similar to Issue #67013.

- VS Code Version:1.66.0
- OS Version: macOS Monterey (Mac M1)

**Comment by gjsjohnmurray** [comment]
Next time it happens please use advice at https://github.com/microsoft/vscode/wiki/Keybinding-Issues to investigate.

**Comment by alexdima** [comment]
@MR-T77 Does this issue reproduce when disabling all extensions?

**Comment by MR-T77** [comment]
I really don't know as this only happens after a while programming, and I need the extensions enabled when I'm programming.
But this is happening a lot and it is really upsetting.
Any other way for me to try to investigate this?

**Comment by jroosameresco** [comment]
I have this issue or a small variation -- my backspace key sometimes stops working but all other keypresses work fine.  All I have to do is Alt-Tab to another app and Alt-Tab back and it resolves it.  Completely random (to me) when it happens but it's typically a few times a day during heavy use.

**Comment by MR-T77** [comment]
Unfortunately, this is a dead-end. As soon as I run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting` the problem stops. This is the way I usually circumvent the issue. But the problem is there...

**Comment by alexdima** [comment]
@MR-T77 The command doesn't change anything in the implementation, but it is possible that by opening the command palette you end up moving the focus, and that triggers something to "repair itself". You could do the following:
* always run this action at the beginning and run with it. It doesn't impact the keybinding dispatching behaviour
* (or) bind it to a keybinding, e.g. `cmd+shift+t` or something and then you just press the keys when the problem reproduces and you can enable it without moving the focus.
