### ISSUE TITLE
[Typescript] JSDoc should provide type information for functions if possible

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode#146801]
In typescript, the current JSDoc snippet provides completions but does not provide type information in the comment even if its is available in the function implementation as seen below:

![image](https://user-images.githubusercontent.com/44413557/161700177-edd7ed6c-329e-4dc0-a18f-f6aa78f34f59.png)

Instead, it should provide something like this:
![image](https://user-images.githubusercontent.com/44413557/161700378-867da9f4-6538-42c2-a78f-b4d1b2a84f7b.png)

There is an existing extension which does that namely [vscode-comment](https://marketplace.visualstudio.com/items?itemName=stevencl.addDocComments#:~:text=vscode%2Dcomment&text=In%20a%20typescript%20or%20javascript,Hit%20enter.)), it would be nice if VSCode supports it natively

**Comment by mjbvz** [comment]
This seems expected. If you're writing TS code, JSDoc types are ignored. Adding them would be worse than useless as not only adding them needlessly duplicate the types, the JSDoc types are not checked by the compiler and can easily get out of date
