### ISSUE TITLE
Prompted to sign into GitHub Repositories in github.dev

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#146832]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:48:56.452Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15

Steps to Reproduce:

Filing on behalf of @jkeech 

1. Access github.dev
2. :bug: Get prompted to sign in (this is after reverting the credentials provider change that added duplicate sessions with the same scopes)

The logs say that GitHub Authentication extension was unable to find credentials.
```
[Info  - 16:10:53.389] Reading sessions from keychain...
[Error  - 16:10:53.393] Getting token failed: Error: Cannot get password
[Info  - 16:10:53.393] Getting sessions for user:email...
[Info  - 16:10:53.393] Got 0 sessions for user:email...
[Info  - 16:10:53.397] Getting sessions for read:user,repo,user:email...
[Info  - 16:10:53.397] Got 0 sessions for read:user,repo,user:email...
[Info  - 16:10:53.397] Getting sessions for read:user,repo,user:email...
[Info  - 16:10:53.397] Got 0 sessions for read:user,repo,user:email...
[Info  - 16:10:53.397] Getting sessions for repo,workflow...
[Info  - 16:10:53.397] Got 0 sessions for repo,workflow...
[Info  - 16:10:53.489] Getting sessions for all scopes...
[Info  - 16:10:53.490] Got 0 sessions for ...
[Info  - 16:14:09.211] Getting sessions for repo,workflow...
[Info  - 16:14:09.211] Got 0 sessions for repo,workflow...
```

**Comment by jkeech** [comment]
This doesn't reproduce on new/fresh browser states, but I have an existing browser session on github.dev in Safari that is now prompting me to sign in to GitHub Repositories when I load the page, such as `https://github.dev/microsoft/vscode`.

**Comment by joyceerhl** [comment]
Seems like we failed to parse the decrypted token info https://github.com/microsoft/vscode/blob/9ff54fa29a8963459103618c1c9e6821d78c4190/src/vs/workbench/api/browser/mainThreadSecretState.ts#L41-L48

**Comment by TylerLeonhardt** [comment]
Talked to @jkeech offline. Likely a result of getting into a bad state from the infinite loop that affected us the other day in github.dev.

He will be making some changes in the github.dev CredentialsProvider to be more robust here.

There's no action item on vscode besides the item we already have to prevent getting into that loop in the future.
