### ISSUE TITLE
Mouse 4 and 5 buttons (forward and back for editor navigation history) are broken after update

### ISSUE THREAD

**Issue by callum-stripe** [microsoft/vscode#146949]
Issue Type: <b>Bug</b>

Hi there, after updating my vscode, my forward and back buttons on my mouse no longer traverse navigation history. This works in all other applications (chrome, slack etc.) so not a problem with the mouse. I see this update includes some updates to editor navigation history, wondering if that could be the cause. 

Tried modifying `workbench.editor.navigationScope` but to no avail. Also launched without extensions as you can see below and still broken.

Happy to provide whatever info is needed

VS Code version: Code 1.65.2 (Universal) (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (3.29GB free)|
|Process Argv|. --disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by bpasero** [comment]
🤷  works fine for me on macOS.

Does it reproduce on https://insiders.vscode.dev/ ?

**Comment by callum-stripe** [comment]
Yes it does repro on https://insiders.vscode.dev/

**Comment by callum-stripe** [comment]
The key binding `^-` works as expected, but the mouse buttons do not. In other chrome tabs the mouse buttons work as expected

**Comment by bpasero** [comment]
@callum-stripe can you:
* open https://insiders.vscode.dev/
* open dev tools sources tab
* add a breakpoint to `historyService.ts` line 130 ([here](https://github.com/microsoft/vscode/blob/7263ea5308fd224efc972d0a7ebccd4711b6a9a5/src/vs/workbench/services/history/browser/historyService.ts#L130))
* click buttons 3 and 4 and see if the breakpoint is hit?

**Comment by callum-stripe** [comment]
All the code is minified, I think I need a source map.

Do your mouse 4 and 5 buttons work inside https://insiders.vscode.dev/? I've noticed when I navigate in the current tab to https://insiders.vscode.dev/ the mouse 4 and 5 buttons are captured by the browser and not propagated to the current page, resulting in a forwards or backwards navigation (back to this github issue for example). However when I open https://insiders.vscode.dev/ in a new tab there's no history to nav to, but I'm not sure if the browser then propagates the input to the page. A quick Google search does not reveal a setting to propagate mouse 4 and 5 input to the page

**Comment by bpasero** [comment]
Source maps are provided and will load shortly after. 

I think as long as focus is inside an editor, the mouse buttons can be captured by us.

**Comment by callum-stripe** [comment]
Am I doing this right? Doesn't look like historyService.ts is showing up as a file
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/102820516/162768689-d18701b2-66ce-43ae-81f0-02d0607daf85.png">

**Comment by callum-stripe** [comment]
Looks like it failed to load some source maps, they look mostly for extensions though:
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/102820516/162768975-85014e5e-5655-40cd-a69b-8853d4ab2728.png">

**Comment by bpasero** [comment]
Ok thanks, this sounds like an upstream problem then and not with VSCode. We rely on the buttons getting through.

**Comment by callum-stripe** [comment]
Got it, so likely a chromium issue?

**Comment by bpasero** [comment]
If you can reproduce this in Chrome, then I suggest to report this at https://bugs.chromium.org/p/chromium/issues/list
