### ISSUE TITLE
Leaking actions when using DropdownWithPrimaryActionViewItem

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#146972]
I was trying to understand the usage of `DropdownWithPrimaryActionViewItem` and the lifecycle of actions created while creating it. I think this originated with the terminal, so looked at the terminal code, but it seems like the problem isn't solved here either.

https://github.com/microsoft/vscode/blob/a57c64f9c0e589d9cd8d1580109194e19b7f346d/src/vs/workbench/contrib/terminal/browser/terminalView.ts#L233

`getTerminalActionBarArgs` instantiates some Actions which extend Disposable, but they are never tracked or disposed.

The ActionViewItems returned from `getActionViewItem` are apparently owned by whatever calls that and get disposed, but not these extra actions that we have to create. So, one solution would be for them to be owned and disposed by `DropdownWithPrimaryActionViewItem` although that feels unexpected. But otherwise, there isn't a technically correct way for the code in `getActionViewItem` to know when they should be disposed.

Wondering whether I'm missing something or if you have any thoughts.

**Comment by meganrogge** [comment]
I spent some time investigating this and the issue is that we use `IAction` in some places and `Action` in others. Only the latter is disposable. This would be a bit involved to rework
