### ISSUE TITLE
Razor view intelligence

### ISSUE THREAD

**Issue by FarzadJM** [microsoft/vscode#146926]
Issue Type: <b>Bug</b>

Razor view intelligence doesn't get updated unless there be a change in csproj file! For example, I added a custom tag Helper class and razor intelligence didn't show any autocomplete until I made a change into csproj file (just a space) and then I had my tag in Autocomplete drop-down list.

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by meganrogge** [comment]
Pls create an issue in the extension's repo responsible for this
