### ISSUE TITLE
Hot Exit: Untitled files with no content should be restored

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14690]
It would probably feel better if Untitled files with no content were also restored upon launch/reload.

**Comment by bpasero** [comment]
If we have a factory for untitled editors (see comment https://github.com/Microsoft/vscode/issues/14116#issuecomment-257134093), this would come for free.

**Comment by bpasero** [comment]
This will be fixed with https://github.com/Microsoft/vscode/issues/15498
