### ISSUE TITLE
Running all tests that match a query: "0/0 Tests Passed: 0.00%"

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#146928]
IN vscode repo, query the test view for "fileService", then run all tests. At first this worked and showed ~281 tests pass, but on subsequent attempts it just shows 0/0.
![Recording 2022-04-06 at 10 12 18](https://user-images.githubusercontent.com/8586769/162030448-2f44cc68-0ebb-407f-b83d-374a34d627d3.gif)

**Comment by JacksonKearl** [comment]
In logs:

./scripts/test test/unit/electron/index.js --no-sandbox --disable-dev-shm-usage --use-gl=swiftshader --reporter full-json-stream --grep /^(WorkingCopyFileService |Files \- NativeTextFileService shutdown joins on pending saves$|Files \- NativeTextFileService i/o |Files \- TextFileService |Files \- BrowserTextFileService i/o |TerminalProfileService |Disk File Service |IndexedDBFileSystemProvider |File Service )/ --run src/vs/workbench/services/textfile/test/common/textFileService.io.test.ts
[8333:0406/101419.862939:INFO:CONSOLE(33)] "The vm module of Node.js is deprecated in the renderer process and will be removed.", source: node:electron/js2c/renderer_init (33)


> Test run finished at 4/6/2022, 10:14:20 AM <

**Comment by JacksonKearl** [comment]
If I add a filter for only executed tests: `fileService @executed`, it works as expected.

**Comment by connor4312** [comment]
> --run src/vs/workbench/services/textfile/test/common/textFileService.io.test.ts

Seems like for some reason it's trying to only run tests in that file.

**Comment by JacksonKearl** [comment]
I may have clicked into that file or tried to manually run it at some point, but of course the whole suite is skipped on my platform.
