### ISSUE TITLE
"Extract to function in module scope" behavior

### ISSUE THREAD

**Issue by enguerran** [microsoft/vscode#146905]
Issue Type: <b>Feature Request</b>

"Extract to function in module scope" should extract the function above the source rather than below.

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

**Comment by mjbvz** [comment]
Why? Please list some perceived benefits

**Comment by enguerran** [comment]
vscode should follow eslint configuration: https://eslint.org/docs/rules/no-use-before-define

> `functions` (`boolean`) - The flag which shows whether or not this rule checks function declarations. If this is `true`, this rule warns every reference to a function before the function declaration. Otherwise, ignores those references. Function declarations are hoisted, so it's safe. Default is `true`.

For instance, [airbnb configuration](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/variables.js#L54) enables this rule.

I don't have other elements, so if the list is too thin to change this behavior, feel free to close the issue.

**Comment by mjbvz** [comment]
Thanks. Yes this sounds like a style choice so I'm going to close it

The current behavior is consistent with what we do for `extract method`. In that case, the rational is that extracting code typically means extracting an implementation detail. When reading the code top to bottom, it typically makes more sense to have the top level method first and then have the methods it calls afterwards

Given that we haven't had any other feedback on this behavior in 5 years, I don't think it's worth adding a configuration option for this

**Comment by enguerran** [comment]
> When reading the code top to bottom, it typically makes more sense to have the top level method first and then have the methods it calls afterwards

Thank you for this comment which is very wise.
