### ISSUE TITLE
Can't get the Outline to show just what I want

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#146937]
Trying to use the secondary sidebar and outline more, but I've never been able to get just what I want.

I basically want to see the "interface" of a file and class - so top-level members and methods. But I can't hide inner variables without hiding outer variables, and I can't hide anonymous callbacks without hiding top-level functions. Is there some way to do this?

```js
export const myVariable = 1;

export function myFunction() {
    let y = 2;

    setTimeout(() => {
    }, 0);
}

export class myClass {
    
}
```

<img width="210" alt="image" src="https://user-images.githubusercontent.com/323878/162037785-e27efb9a-e058-4652-89ed-9090a2d6f822.png">

I want to see myVariable, myFunction, and myClass. If I disable showFunctions, I lose the callback but also myFunction. If I disable showVariables I lose y but also myVariable.

This is very language-dependent and also personal, is there an issue for this or another way to do it?

**Comment by jrieken** [comment]
Yeah, outline itself doesn't know about global variables vs local variables and I am unsure if it wants to. One idea would be to extend the existing [symbol tags](https://github.com/microsoft/vscode/blob/b261d64b68c6c6a5d261f7088d59dedba51a04d3/src/vscode-dts/vscode.d.ts#L3146) and to allow extension to say "this symbol is exported/public or global etc" and outline could use that information to filter. This will yield interesting configuration challenges, like filter global variables but not exported global ones and not global functions etc...

Alternatively, this is done with a bunch of settings inside the TS extensions (likely less ideal) or a combination of both approaches..

**Comment by UltimateBrent** [comment]
I know this is old, but it still bugs me. Would love the ability to just right click on items in the outline and hide that type of item, especially callbacks / anonymous functions kind of stuff.

**Comment by c-claeys** [comment]
Hey @jrieken I'm curious if you'd consider this issue canonical for [103305](https://github.com/microsoft/vscode/issues/103305)? I also found [157461](https://github.com/microsoft/vscode/issues/157461) but it doesn't look like as good of a match IMO.
