### ISSUE TITLE
The first terminal output extra prompt when create second termial

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#146904]
Does this issue occur when all extensions are disabled?: Yes/No
Yes.

MacOS: 12.3.1
VSCode: 1.67.0-insider

Steps to Reproduce:

1. open the terminal, the is one line prompt
2. `cmd + \` to create the second terminal, the first terminal will output extra prompt

![image](https://user-images.githubusercontent.com/41773861/161953976-59cb715e-b1e5-4016-8b3d-f6156531249f.png)

**Comment by meganrogge** [comment]
I can't reproduce this. Does running the terminal split command reproduce this? Can you try disabling your extensions and attaching a gif?

**Comment by tjx666** [comment]
@meganrogge
https://user-images.githubusercontent.com/41773861/162372750-cc04b2ad-eee7-4a78-b704-e80c7c907fcf.mov

**Comment by tjx666** [comment]
or a simple one:


https://user-images.githubusercontent.com/41773861/162373002-d7c24da3-9b80-4e8b-be7e-744c529be309.mov

**Comment by tjx666** [comment]
not related with splt terminal，cmd shift + j to create second  terminal also can occur this issue

**Comment by tjx666** [comment]
I think this should an issue with powerlever10k: https://github.com/romkatv/powerlevel10k/issues/1841
