### ISSUE TITLE
Activity bar not visible after exiting zen-mode

### ISSUE THREAD

**Issue by aalbaali** [microsoft/vscode#146939]
Issue Type: <b>Bug</b>

Actions to reproduce the problem:
- Open vscode in regular mode (i.e., not zen or full screen)
- Ensure *Activity Bar* is checked in `View>Appearance` (activity bar should be visible)
- Enter zen mode (the statur bar can no longer be seen, which is normal)
- Exit zen mode: the Activity Bar *cannot* be seen, which is unexpected
- Reload window: the Activity Bar pops back

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:41.156Z)
OS version: Linux x64 5.13.0-39-generic snap
Restricted Mode: No

<details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
cppincludeguard|aki|1.6.0
atlascode|atl|2.10.11
vscode-django|bat|1.10.0
Doxygen|bbe|1.0.0
doxdocgen|csc|1.4.0
c-cpp-compile-run|dan|1.0.15
python-environment-manager|don|1.0.3
python-extension-pack|don|1.7.0
gitlens|eam|12.0.5
prettier-vscode|esb|9.5.0
docker-explorer|for|0.1.7
c-cpp-runner|fra|3.2.4
vscode-drawio|hed|1.6.4
monkey-patch|ioc|0.1.16
vscode-ros2|Jae|0.0.8
latex-workshop|Jam|8.24.1
better-cpp-syntax|jef|1.15.13
julia-debug|Jud|0.0.32
language-julia|jul|1.6.15
auto-comment-blocks|kev|1.0.1
vsc-python-indent|Kev|1.15.0
vscode-clangd|llv|0.1.15
vscode-docker|ms-|1.21.0
python|ms-|2022.4.0
vscode-pylance|ms-|2022.3.4
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.4
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
latex-formatter|nic|1.0.5
autodocstring|njp|0.6.1
vscode-yaml|red|1.6.0
vscode-julia-formatter|sin|0.6.3
rewrap|stk|1.16.3
latex-utilities|tec|0.3.7
latex-support|tor|3.10.0
cmake|twx|0.0.17
vscode-lldb|vad|1.7.0
vscodeintellicode|Vis|1.2.18
vscode-icons|vsc|11.10.0
jinja|who|0.0.8
clang-format|xav|1.9.0
markdown-all-in-one|yzh|3.4.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
pynewfile477:30463512

```

</details>

**Comment by aalbaali** [comment]
My bad, it was a typo. Just fixed the description.

**Comment by mechtaev** [comment]
I have a related issue. My activity bar is disabled with `"workbench.activityBar.visible": false`. When I enter and exit Zen mode, the activity bar appear, and I am not able to hide it until I restart the window.

**Comment by sbatten** [comment]
I am unable to reproduce. Can you try with extensions disabled?

**Comment by mechtaev** [comment]
I have tried to disable extensions with `--disable-extensions`, and still can reproduce the problem. I realised that to reproduce it reliably, I need to first create a new window using "New Window" command, and the enter/exit zen mode in this new window. Here are additional details:

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.16.18-100.fc34.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|11.58GB (0.52GB free)|
|Process Argv|--disable-extensions test3 --crash-reporter-id 97e417ba-4f03-47cb-8130-cd3bd14caa32|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by mechtaev** [comment]
Here is a video where I reproduce the problem: https://youtu.be/5swyiF9homs

**Comment by sbatten** [comment]
@mechtaev ah yes, I can reproduce your issue, since it is slightly different, can you please file a separate issue?

**Comment by mechtaev** [comment]
@sbatten great, done: #148862

**Comment by paksnuk** [comment]
I have the "opposite" issue: after hiding the activity bar and going into zen mode and exiting it again, the activity bar is visible and cannot be removed again. The checkmark in the menu is also missing. (MacOS and Linux)

**Comment by aalbaali** [comment]
> @aalbaali can you still reproduce this issue with the latest 1.68?

No, I can no longer reproduce the issue with the latest update. I'll close the ticket, thanks.
