### ISSUE TITLE
Normal text select choppy after update

### ISSUE THREAD

**Issue by jimsnab** [microsoft/vscode#146947]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:41.156Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.13.0-39-generic

- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Open a source file.
2. Using the mouse, try to select complete lines. (I usually select backwards, end to start, but it is an issue either way)

Expected: while dragging the mouse selection, pointing to the area beyond the left side of the window should continue to update the selection area.

Actual: while selecting and moving over the new diff bar, the diff bar will process the mouse movements as its own, and the text selection will be robbed of the movements. So unlike before, there is now a very narrow box where the mouse must point in order to select a full line, and it's irritating.

Selecting a full line is an extremely frequent operation.

When a mouse drag starts in the editor window, all mouse movements should go to the editor window, even those outside the window boundary. This will make the selection mechanism work like most text editors.

**Comment by NBS-LLC** [comment]
I'm observing the same issue, except I don't have to make code changes (step 1 from the original comment).

**Comment by alexdima** [comment]
@jimsnab @NBS-LLC I cannot reproduce:

https://user-images.githubusercontent.com/5047891/162150261-edab93f9-e693-486f-8127-d7bf9d6cd332.mp4


Are you perhaps running into https://github.com/microsoft/vscode/issues/83568 , https://github.com/microsoft/vscode/issues/113630 or https://github.com/microsoft/vscode/issues/124895 ?

**Comment by keithgairnvm** [comment]
I can reproduce this on Ubuntu 20.04. The text selection does not continue when the mouse pointer is in the left hand gutter.

Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:41.156Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.13.0-39-generic

https://user-images.githubusercontent.com/31654274/162173565-3fed9dd2-3275-469a-bdfd-f19a970c35e8.mp4

It does not happen on Windows 10.

Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19042

https://user-images.githubusercontent.com/31654274/162173919-d2d3f415-26fd-4d09-84c5-70b45cb3a76f.mp4

**Comment by gralpli** [comment]
I have the same problem. Text selection does stop as soon as the mouse pointer is further to the left than the text, for example, over the line numbers.

VSCode 1.66, Debian 11, Wayland
