### ISSUE TITLE
I am unable to click to select text in vscode. 

### ISSUE THREAD

**Issue by James4645** [microsoft/vscode#146973]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0
- OS Version: Windows 11Pro 21H2, Build # 22000.556 with Windows Feature Experience Pack 1000.22000.556.0

From VS Code About:
Version: 1.66.0 (system setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

I can double click to select a line but I can not click and drag to select an arbitrary chunk of text. Problem persists even with no extensions installed on a fresh vs code install. Issue is specific to vs code, selecting works fine everywhere else. Even works in the vscode instance for github.dev

![image](https://i.postimg.cc/15hRhYDn/cant-select.gif)

Steps to Reproduce:

1. Hold down left mouse button in any text based file opened in vs code and drag to attempt to select text

**Comment by alexdima** [comment]
@James4645 Are you able to drag the slider of the scrollbar?

**Comment by James4645** [comment]
Yes the scroll bar works fine. As far as I can tell only text selection is broken.

**Comment by alexdima** [comment]
@James4645 Could you please try opening https://jsfiddle.net/6eu0safo/ in Chrome or Edge and let me know if you can drag the blue box over there? If not, I would like to please see the console output (Ctrl+Shift+I)

**Comment by James4645** [comment]
I can move it along the X axis, but not the Y axis. Not sure if that's by design or not, so here's the output from me trying to move along the Y axis.

[yaxis-movement.log](https://github.com/microsoft/vscode/files/8452121/yaxis-movement.log)

**Comment by James4645** [comment]
As of today seems to be working as expected now. Not sure if there was an auto update with vscode, or windows or what. But the issue is no longer persisting.
