### ISSUE TITLE
VCS Panel: Repositories with the same names are ignored

### ISSUE THREAD

**Issue by efim-a-efim** [microsoft/vscode#146903]
Issue Type: <b>Bug</b>

1. Create 2 or more Git repositories in separate directories
2. Add all the directories into a workspace, save the workspace
3. In all the repositories from previous step, create (or clone) Git submodules. The submodules directory names (and names in `.gitmodules`) must be the same in all directories, but the actual submodule repos must be different
4. Close the workspace and open it again.
5. Select VCS panel and check the repositories list

**Expected behavior:** there are several records in the VCS panel corresponding to the submodules from the step 3. This records have the same name, but different paths and content.

**Actual behavior:** only 1 submodule is shown (the first one that was discovered by the VSCode), all other submodules are ignored.

**Note:** This behavior is probably related to the repositories alphabetical sorting feature. While sorting, it ignores repositories with the same "name". But it's possible that some people (like me) will use directories structure like:

```
infrastructure/ <-- this is infra-related code
infrastructure/configs <-- this is configs for infra, it's in a separate repo
applications/ <-- this is application code
applications/configs <-- this is applications configs and it's a separate repo, but it's also named "configs"
```

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (5.53GB free)|
|Process Argv|--crash-reporter-id 8f0b1bef-da94-4bd4-92a5-c1b045a74f2a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1991)|
|Memory (System)|24.92GB (13.75GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1991)|
|Memory (System)|24.92GB (13.75GB free)|
|VM|0%|
</details><details><summary>Extensions (77)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.2.4
project-manager|ale|12.5.0
language-prometheus|caa|0.1.2
gotemplate|cas|0.4.0
scad|efb|1.0.1
vscode-great-icons|emm|2.1.85
terraform|has|2.21.0
output-colorizer|IBM|0.1.2
saltstack|kor|0.0.9
autoconf|mae|0.1.0
VS-code-vagrantfile|mar|0.0.7
dotenv|mik|1.0.1
nc-gcode|ML|0.13.0
remote-containers|ms-|0.231.3
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-ssh-explorer|ms-|0.56.0
remote-wsl|ms-|0.66.0
vscode-remote-extensionpack|ms-|0.21.0
makefiles-support-for-vscode|nae|0.0.3
material-icon-theme|PKi|4.15.0
vscode-ansible-linter|rup|0.14.0
jinjahtml|sam|0.17.0
jenkinsfile-support|sec|0.1.0
gitconfig|sid|2.0.1
ayu|tea|1.0.5
vscode-icons|vsc|11.10.0
jinja|who|0.0.8
vscode-ruby|win|0.28.0
atlascode|atl|2.10.11
vagrant|bbe|0.5.0
better-toml|bun|0.3.2
chef|che|2.1.0
gitignore|cod|0.7.0
vscode-markdownlint|Dav|0.47.0
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|12.0.5
EditorConfig|Edi|0.16.4
json-tools|eri|1.0.2
code-runner|for|0.11.7
shell-format|fox|7.2.2
referenceshelper|gay|0.2.3
go|gol|0.32.0
terraform|has|2.21.0
jenkinsfile-support|ivo|1.1.0
vscode-go-template|jin|0.2.1
json-escaper|jos|1.1.2
file-downloader|min|1.0.11
mindaro|min|1.0.120220125
ecdc|mit|1.4.0
vscode-docker|ms-|1.21.0
vscode-kubernetes-tools|ms-|1.3.7
python|ms-|2022.4.0
vscode-pylance|ms-|2022.3.4
powershell|ms-|2021.12.0
gremlins|nho|0.26.0
indent-rainbow|ode|8.2.2
ruby|reb|0.28.1
ansible|red|0.8.1
vscode-commons|red|0.0.6
vscode-yaml|red|1.6.0
bash-debug|rog|0.3.9
vscode-ansible-linter|rup|0.14.0
snooty|sno|0.9.9
shellcheck|tim|0.19.0
vt100-syntax-highlighting|Tob|1.0.1
json2yaml|tux|0.2.0
terminal-tabs|Tyr|0.2.1
vscodeintellicode|Vis|1.2.18
vscode-maven|vsc|0.35.1
docker|vsc|1.0.0
sql|vsc|1.0.0
yaml|vsc|1.0.0
salt-lint|war|0.1.0
vscode-ruby|win|0.28.0

(3 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate and will be fixed in upcoming 1.66.1 recovery release
