### ISSUE TITLE
Bad screen partial repaint issues making VSCode very unpleasant to use

### ISSUE THREAD

**Issue by doliver3** [Microsoft/vscode#14692]
- VSCode Version: 1.6.1
- OS Version: Mac OS Sierra 10.12

Steps to Reproduce:

1. Open any file 
2. Code areas appear in dark black while huge blocks where the text is not at appear in gray black so there is not in any way a uniform background color

![image](https://cloud.githubusercontent.com/assets/98346/19830188/653d6354-9dc0-11e6-9705-2075c5d02761.png)

![image](https://cloud.githubusercontent.com/assets/98346/19830193/7cafa506-9dc0-11e6-887e-3be778bd412e.png)

**Comment by mrmlnc** [comment]
Please, use search before create new issue.

See official release notes: http://code.visualstudio.com/updates#_macos-sierra-support
See alredy created issues: #12473, #12474, #12523, #12571, #13175, #13192, #13959, #14233, #14540

**Comment by octref** [comment]
#12473
