### ISSUE TITLE
Declare folder support in Info.plist on macOS

### ISSUE THREAD

**Issue by sindresorhus** [microsoft/vscode#146977]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.66
- OS Version: macOS 12.3

VS Code supports opening folders directly, but it does not declare folder support in `CFBundleDocumentTypes` in `Info.plist`. This means apps with a "Open With" functionality cannot automatically list VS Code in a list of apps for users to choose from.

Solution: Add `public.folder` to supported document types.
Example: https://github.com/ImageOptim/ImageOptim/blob/d8d6bc528f0b19253585d824851e320db3261d03/imageoptim/Info.plist#L107-L118

**Comment by bpasero** [comment]
/duplicate https://github.com/microsoft/vscode/issues/1223

cc @joaomoreno @deepak1556

**Comment by sindresorhus** [comment]
@bpasero This is not a duplicate of that issue. That issue is about adding a custom menu item to the right-click menu in Finder, which is completely different.

**Comment by bpasero** [comment]
Oh yeah sorry!

**Comment by bpasero** [comment]
@sindresorhus btw not sure if you know anything about it, but I was never able to figure out how an Electron application can declare these services to work:

![image](https://user-images.githubusercontent.com/900690/162196731-6555ab08-8aa7-4ad0-a855-6b96730ba7a8.png)

vs VSCode:

![image](https://user-images.githubusercontent.com/900690/162196778-20c15cb1-61ec-4c2b-b6de-d3ee7266b9f2.png)

Maybe there is a related `Info.plist` entry to declare text editor capabilities? Not sure you know anything about it.

**Comment by sindresorhus** [comment]
> but I was never able to figure out how an Electron application can declare these services to work for text:

It's something you get for free when using `NSTextView`. You can declare support yourself with https://developer.apple.com/documentation/appkit/nswindow/1419454-validrequestor#

**Comment by bpasero** [comment]
I gave the suggestion to do what https://github.com/ImageOptim/ImageOptim/blob/d8d6bc528f0b19253585d824851e320db3261d03/imageoptim/Info.plist#L107-L118 does a try but cannot make it work. Even when I install `ImageOptim`, I see no entry in the folder context menu to open the folder with the app, so I wonder if this actually is still supported in macOS?

To clarify: when I try to copy the `Info.plist` entry over, I can no longer start VSCode, so maybe there is more to it than just changing the info file, maybe it requires some native code too?

I could not find any docs about this oddly, would be great to have blessing from Apple that this is still possible.

I was hoping this could have maybe fixed https://github.com/microsoft/vscode/issues/1223

**Comment by deepak1556** [comment]
@bpasero did you re-sign the package after making changes to the plist file ? This would require changes to https://github.com/microsoft/vscode/blob/main/build/lib/electron.ts so that relevant categories are filled under https://github.com/joaomoreno/gulp-atom-electron/blob/536f5dba32336beb56446be18de3eb5b73a4379f/src/darwin.js#L134-L143

**Comment by bpasero** [comment]
Oh yeah let me try that, however I have little hope given that `ImageOptim` was not showing up in the context menu either...

**Comment by sindresorhus** [comment]
> I see no entry in the folder context menu to open the folder with the app, so I wonder if this actually is still supported in macOS?

Finder does not support opening folders, but other apps do:
- https://www.cocoatech.io
- https://sindresorhus.com/folder-peek (It hard-codes VS Code because of this issue)
  - Here's a special build that does not hard-code VS Code so you can test it: [Folder Peek.app.zip](https://github.com/microsoft/vscode/files/8510675/Folder.Peek.app.zip)

**Comment by sindresorhus** [comment]
I have also sent a feature request to Apple to get a "Open With" menu in Finder for folders too: https://github.com/feedback-assistant/reports/issues/301

**Comment by bpasero** [comment]
@sindresorhus if you want to test a build, I have https://az764295.vo.msecnd.net/insider/011c0a5bfa08544eec98cfb3d455c952d09d5fab/VSCode-darwin-universal.zip ready with the following entry:

```xml
<dict>
	<key>CFBundleTypeIconFile</key>
	<string>default.icns</string>
	<key>CFBundleTypeName</key>
	<string>Folder</string>
	<key>CFBundleTypeOSTypes</key>
	<string>CFBundleTypeExtensions</string>
	<key>CFBundleTypeRole</key>
	<string>Editor</string>
	<key>LSItemContentTypes</key>
	<array>
		<string>public.folder</string>
	</array>
</dict>
```

Before trying, make sure to configure `update.mode: none`, otherwise the automated update would download the previous build again.

One thing that is not clear to me: we use a few more properties when declaring `CFBundleDocumentTypes` such as:

```xml
<key>CFBundleTypeOSTypes</key>
<array>
	<string>TEXT</string>
	<string>utxt</string>
	<string>TUTX</string>
	<string>****</string>
</array>
```

Wonder if that would cause any harm for a folder?

**Comment by sindresorhus** [comment]
`CFBundleTypeOSTypes` was deprecated in macOS 10.5. You should use `LSItemContentTypes` instead.

https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

**Comment by bpasero** [comment]
I suggest to deal with `CFBundleTypeOSTypes` in a separate issue.

Opened PR https://github.com/microsoft/vscode/pull/147686 to add `public.folder`, seems to work fine with the "Path Finder" app.

**Comment by bpasero** [comment]
**Verification:**
* install an app that supports this (https://www.cocoatech.io/ -> path finder)
* make sure you can right click on a folder in the path finder app and select VSCode to open

**Comment by connor4312** [comment]
Verified. Path Finder looks cool 👀

**Comment by bpasero** [comment]
Yeah thought the same!
