### ISSUE TITLE
VSCode cannot load any font other than monospace

### ISSUE THREAD

**Issue by calebvisage** [microsoft/vscode#146983]
Issue Type: <b>Bug</b>

VSCode fails to load custom font families, only uses monospace, but seems to somehow resolve itself after a few hours. Have reinstalled VSCode, the font itself, and it has worked every day till now except on startup where I have to wait for it to resolve itself. A total mystery.

- [x] Editor Font Family (User/Workspace/Container): 'Fira Code', 'Fira Mono', 'JetBrains Mono', 'Courier New', monospace
- [x] Extensions disabled (Yes I disabled it after submitting the Issue)
- [x] Other IDE's can use the font just fine 

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz (12 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (4.50GB free)|
|Process Argv|--crash-reporter-id 336fdae8-d287-440d-a98a-6e889ab01086|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.4
vscode-django|bat|1.10.0
vscode-intelephense-client|bme|1.8.2
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.5
vscode-html-css|ecm|1.11.0
vscode-npm-script|eg2|0.3.24
copilot|Git|1.12.5517
vscode-pull-request-github|Git|0.40.0
go|gol|0.32.0
svg|joc|1.4.17
git-graph|mhu|1.30.0
vscode-docker|ms-|1.21.0
python|ms-|2022.4.0
vscode-pylance|ms-|2022.4.0
remote-containers|ms-|0.231.4
remote-ssh|ms-|0.78.0
remote-wsl|ms-|0.66.0
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.9.7
vscode-typescript-tslint-plugin|ms-|1.3.4
color-highlight|nau|2.5.0
vscode-thunder-client|ran|1.14.4
synthwave-vscode|Rob|0.1.11
rust|rus|0.7.8
doki-theme|unt|78.1.2
vscode-icons|vsc|11.10.0
markdown-all-in-one|yzh|3.4.0

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
vscaac:30438847
pynewfile477:30463512

```

</details>

**Comment by calebvisage** [comment]
Consolas font works, user-installed fonts do not.

**Comment by calebvisage** [comment]
My font settings:

"terminal.integrated.fontFamily": "'Fira Code', 'Consolas', 'Courier New', monospace",
"editor.fontFamily": "'Fira Code', 'Consolas', 'Courier New', monospace",

After restarting for the fifth time, the integrated terminal's font settings is correct ('Fira Code') but the editor fontFamily is 'Consolas' instead of 'Fira Code'.

**Comment by alexdima** [comment]
@calebvisage I think I have seen a very similar issue in the past. After a lot of back and forward, a complete uninstall of the problematic font and its variants, followed by a PC restart, followed by a complete install led to things working again.

**Comment by calebvisage** [comment]
Okay that works **except** for the project session that was in memory before (the project that gets restored when vscode opens). Even after fully closing the project and window, still opens with the Consolas font instead of Fira Code.

Is there a way to clear sessions/cache?

**Comment by calebvisage** [comment]
Resolved it by deleting the project's ```.vscode``` folder (for others reading this with the same issue, the culprit lies in **project's** settings.json)
