### ISSUE TITLE
VSCode is wiping out my search

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#14693]
- VSCode Version: 1.6.1
- OS Version: Windows 10 Anniversary Update

Steps to Reproduce:
1. Start with an empty text file
2. Perform a regex search / replace (`CTRL + H`), for example `an$`
3. Paste in some text, where the _end_ of the text matches the search in step 1 (eg. `Trevor Sullivan`)
4. Hit `CTRL + H` to perform another search / replace
5. The regex search you performed is replaced with the word directly preceding the matching text

Let me know if you need help reproducing this behavior. I was able to do it myself several times.

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by alexandrudima** [comment]
Possibly related #10386

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/20768 and already fixed via adding a new option for seedSearchStringFromSelection.
