### ISSUE TITLE
Always show path information even for non-focus editor

### ISSUE THREAD

**Issue by harangue** [Microsoft/vscode#1469]
Here's how it currently is.
![](http://i.imgur.com/5UVVFsS.png)
Here's as it should be.
![](http://i.imgur.com/tafVbwv.png)

The relevance of this distinguisher doesn't change even with a blurred pane - I think it should always be visible.

**Comment by bpasero** [comment]
We did this decision so that the active editor stands out more strongly.

@stevencl fyi

**Comment by fluffynuts** [comment]
+1
This would be especially helpful when you're trying to import / require from a spec outside of the system source tree; ie when I have the folders src/ and test/ where test/* mirrors source/* like:
src
 /folder
  /file.ts
test
 /folder
  /file.spec.ts

Not being able to see both paths when I have the files side-by-side makes the import with all the required preceding ../'s a mission )':
