### ISSUE TITLE
CTRL + ALT + ENTER not working to Replace All

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#14695]
- VSCode Version: 1.6.1
- OS Version: Windows 10 Anniversary Update

Steps to Reproduce:
1. Perform a regex search/replace using `CTRL + H`
2. Press `CTRL + ALT + ENTER` to perform the replacement operation
3. The replacement operation does not occur

**NOTE**: When I use the mouse to hover over the **Replace All** button, it specifically mentions a `CTRL + ALT + ENTER` keyboard shortcut, hence the expectation is that, that keyboard shortcut would invoke the Replace All operation.

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by alexandrudima** [comment]
@pcgeek86 I cannot reproduce.

I have tried pressing ctrl+alt+enter with focus both in the replace field and inside the editor. All 6 matches are replaced for me.

![ctrl-alt-enter](https://cloud.githubusercontent.com/assets/5047891/19850119/0ce7f960-9f57-11e6-9d97-f12bf5750b8f.gif)

**Comment by pcgeek86** [comment]
I narrowed it down to the Python extension. Sorry for the trouble.

Just a suggestion: It might be a good idea to have some kind of "export extensions" guidance, for easy debugging / inclusion in bug reports! Is there a way to do this?

**Comment by pcgeek86** [comment]
I reported the issue here: https://github.com/DonJayamanne/pythonVSCode/issues

**Comment by alexandrudima** [comment]
@pcgeek86 Have you tried

![image](https://cloud.githubusercontent.com/assets/5047891/19855610/cde53682-9f75-11e6-82e2-a8662316dcbb.png)

It produces something like this for me:

- VSCode Version: Code - Insiders 1.7.0-insider (0706b425537d8cfe2766eac00662ecf988c7ed7f, 2016-10-28T13:10:55.168Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|copy-relative-path|alexdima|0.0.1|
|vscode-lcov|alexdima|0.2.0|
|vscode-eslint|dbaeumer|1.0.8|
|tslint|eg2|0.5.39|
|vsc-travis-ci-status|felixrieseberg|1.0.5|
|debugger-for-chrome|msjsdiag|2.1.0|
|vscode-versionlens|pflannery|0.8.0|
|vscode-open-in-github|sysoev|1.2.1|

---

Steps to Reproduce:

1.
2.

**Comment by pcgeek86** [comment]
@alexandrudima Awesome, didn't know about that. I prefer the Command Palette version though. :)
