### ISSUE TITLE
Dark mode detection broken with GNOME 42

### ISSUE THREAD

**Issue by victorz** [microsoft/vscode#146999]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:41.156Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.17.1-arch1-1
```

- OS Version: Arch Linux :shrug:

I used to use the following method to trigger dark/light theme in GTK/GNOME apps, before GNOME 42 came out.

- Set light theme: `gsettings set org.gnome.desktop.interface gtk-theme Adwaita`
- Set dark theme: `gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark`

Now it seems like the correct way to trigger the theme change is this, as far as GTK/GNOME apps are concerned:

- Set light theme: `gsettings set org.gnome.desktop.interface color-scheme prefer-light`
- Set dark theme: `gsettings set org.gnome.desktop.interface color-scheme prefer-dark`

This also works with Firefox. This does **not** seem to work for vscode. Nothing happens when I use the latter method.

I use the i3 window manager, so I'm not 100 percent sure what a fully integrated GNOME desktop environment would do to toggle light/dark mode under the hood. If I'm way off, please divert me to better methods! :pray:

For now, I will probably use a combination of the two methods until vscode supports the new(?) way.

**Comment by aeschli** [comment]
The support needs to come from Electron: Issue https://github.com/electron/electron/issues/33635.
Marking as duplicate.

**Comment by hoteit** [comment]
my workaround is to install gnome-themes-extra and enable Adwaita-dark under Themes -> Appearance -> Legacy Applications. That took care of the dark theme for vscode

**Comment by victorz** [comment]
> my workaround is to install gnome-themes-extra and enable Adwaita-dark under Themes -> Appearance -> Legacy Applications. That took care of the dark theme for vscode 

Right, that's pretty much what I was doing with the command

`gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark`

**Comment by je4npw** [comment]
> `gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark`

This save my day. Thankx
