### ISSUE TITLE
`lib/tsserver.js` and `typescript/lib/typingsInstaller.js` lurk around

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#146944]
I have recently enabled logging of processes in our CI and I have a log for after our integration tests:

https://gist.github.com/bpasero/3de5e01bd32f57c845253af07e19d27a

From https://dev.azure.com/monacotools/Monaco/_build/results?buildId=165478&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=79e950e2-ae58-5fea-a241-0229f56d23a3

Notice these:

```
/__w/1/vscode-reh-web-linux-x64/node --max-old-space-size=3072 /__w/1/vscode-reh-web-linux-x64/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --enableTelemetry --cancellationPipeName /tmp/vscode-typescript1000/8ef3a9a595f292584b78/tscancellation-3d884c073fbecb888c67.tmp* --locale en-US --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
```

and

```
/__w/1/vscode-reh-web-linux-x64/node /__w/1/s/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /home/builduser/.cache/typescript/4.6 --enableTelemetry --typesMapLocation /__w/1/s/extensions/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation
```

It seems the automated typings acquisition is getting orphaned and still runs. 

As a bandaid I had tried to disable automated typings aquisition via setting, e.g.:

https://github.com/microsoft/vscode/blob/8e8b3026fcdbdd4855dcfa3c96e24d1058779aea/extensions/vscode-api-tests/testWorkspace/.vscode/settings.json#L10

And this seems to be passed to TS (via `disableAutomaticTypingAcquisition`) but does not seem to help.

Not sure this is an extension problem in TS or in the extension host. My feeling is:
* we kill the main process 
* the extension host has no more parent
* extension host self terminates
* TS extension does not check for parent process to go away

**Comment by alexdima** [comment]
I've pushed a change to deactivate extensions after tests are run, so it should now be possible to for extensions to better clean up.

**Comment by alexdima** [comment]
Looks like that was the root problem and that the processes are gone in https://dev.azure.com/monacotools/Monaco/_build/results?buildId=165758&view=logs&jobId=963754b8-394e-5caf-de5d-2790b068caec&j=963754b8-394e-5caf-de5d-2790b068caec&t=79e950e2-ae58-5fea-a241-0229f56d23a3

**Comment by bpasero** [comment]
@alexdima thank you 💯
