### ISSUE TITLE
Viewport for Extensions doesn't scale on high resolution displays

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#14697]
- VSCode Version: 1.6.1
- OS Version: Windows 10 Anniversary Update
- Device: Dell XPS 9350 QHD IPS (3200 x 1800)

Steps to Reproduce:
1. Open VSCode
2. Change into the **Extensions** context
3. Perform an extension search, and select one
4. Use `CTRL + +` to increase the editor font size
5. Notice the poor scaling of the description area of the extension viewport (screenshot included below)

![image](https://cloud.githubusercontent.com/assets/466713/19831585/4152644a-9dd3-11e6-83be-5558d6f02441.png)

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by joaomoreno** [comment]
#5745
