### ISSUE TITLE
Cannot drop file from OS onto notebook or webview to open it

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#146967]
Issue Type: <b>Bug</b>

**Repro**
1. Open a notebook in VS Code
1. From OS, try dropping a text file into the notebook editor area (when done on a normal editor, this should open the file)

**Bug**
Nothing happens

VS Code version: Code - Insiders 1.67.0-insider (Universal) (f050b17dacedba13962244b13c70084a473d08f7, 2022-04-06T05:15:27.397Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 4|
|Memory (System)|32.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
salesforce-soql-editor|all|1.8.0
tsl-problem-matcher|amo|0.6.2
comment-tagged-templates|bie|0.3.1
completions-sample|bie|0.0.2
docs-view|bie|0.0.10
emojisense|bie|0.9.0
folder-source-actions|bie|0.2.1
jsdoc-markdown-highlighting|bie|0.0.1
markdown-checkbox|bie|0.3.2
vscode-eslint|dba|2.2.2
typescript-notebook|don|2.0.6
gitlens|eam|12.0.5
EditorConfig|Edi|0.16.4
codespaces|Git|1.5.9
copilot|Git|1.12.5517
remotehub|Git|0.31.2022040601
vscode-pull-request-github|Git|0.41.2022040609
vscode-mocha-test-adapter|hbe|2.13.3
vscode-test-explorer|hbe|2.21.1
vscode-drawio|hed|1.6.4
vscode-postfix-ts|ipa|1.9.4
latex-workshop|Jam|8.24.1
vscode-platform-specific-sample|joa|1.15.0
vscode-memfs|jri|0.0.3
vscode-position|jtr|1.1.2
template-string-converter|meg|0.6.0
git-graph|mhu|1.30.0
vscode-azurefunctions|ms-|1.6.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.21.0
vscode-language-pack-de|MS-|1.66.2
python|ms-|2022.5.10961002
vscode-pylance|ms-|2022.3.3
jupyter|ms-|2022.4.1000971004
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.232.4
remote-ssh|ms-|0.79.2022040616
remote-ssh-edit|ms-|0.80.0
azure-account|ms-|0.10.1
hexeditor|ms-|1.9.5
js-debug-nightly|ms-|2022.4.417
live-server|ms-|0.2.12
remote-repositories|ms-|0.5.2022040601
test-adapter-converter|ms-|0.1.5
vscode-github-issue-notebooks|ms-|0.0.117
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5449
debugger-for-chrome|msj|4.13.0
vetur|oct|0.35.0
java|red|1.4.0
code-spell-checker|str|2.1.11
rest-book|tan|6.0.1
ayu|tea|1.0.5
luna-paint|Tyr|0.13.2
sort-lines|Tyr|1.9.1
vscode-java-debug|vsc|0.40.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.2
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
No unfortunately not. I'll take a quick look through to see if I can figure out what is going on

**Comment by mjbvz** [comment]
Ugh as usual iframes are the root cause of this. From what I can tell, when a file is dragged over an iframe, the outer page will never see the drag events. Workarounds:

- Disable pointer events on the iframe. This is not feasible since it also disables basic operations such as clicking links

- In the inner iframe, listen to the drags and post them back to the editor. Then create a transparent overlay on top of the iframe to intercept future drag events

Here's the code I used to prototype this second approach:

<details>

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <style>
        html,
        body {
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            background-color: blue;
        }

        #frame-wrapper {
            height: 100%;
            width: 50%;
            position: absolute;
            left: 50%;
            top: 0;
        }

        #frame {
            height: 100%;
            width: 100%;
        }

        #frame-wrapper.inner-dragging::after {
            content: "drop blocker";
            font-weight: bold;
            background-color: #f00a;
            display: flex;
            justify-content: center;
            align-items: center;
            width: 100%;
            height: 100%;
            position: absolute;
            top: 0;
            left: 0;
        }
    </style>
</head>

<body>
    <h1 draggable="true">Outer (drag me)</h1>

    <div id="frame-wrapper">
        <iframe id="frame" sandbox=""></iframe>
    </div>

    <script>
        const wrapper = document.getElementById('frame-wrapper');
        /** @type {HTMLIframeElement} */
        const frame = document.getElementById('frame');
        frame.setAttribute('srcdoc', `
            <!DOCTYPE html>
            <html lang='en'>
            <head>
                <meta charset='UTF-8'>
            </head>
            <body style="background-color: green;">
                <a href="http:://example.com">link</a>
                <${'script'}>
                    window.addEventListener('dragenter', (e) => {
                        console.log('dragenter inner');
                        e.preventDefault();
                        window.parent.postMessage({ type: 'dragenter' }, '*');
                    });
                    window.addEventListener('dragover', (e) => {
                        console.log('dragover inner');
                        e.preventDefault();
                        window.parent.postMessage({ type: 'dragenter' }, '*');
                    });
                    window.addEventListener('drop', (e) => {
                        console.log('drop inner');
                        e.preventDefault();
                    });
                </${'script'}>
            </body>
            </html>`);

        document.body.addEventListener('dragenter', (e) => {
            console.log('dragenter outer');
            e.preventDefault();
        });
        document.body.addEventListener('dragover', (e) => {
            console.log('dragover outer');
            e.preventDefault();
        });
        document.body.addEventListener('drop', (e) => {
            console.log('drop outer');
            e.preventDefault();
        });


        window.addEventListener('message', e => {
            switch (e.data.type) {
                case 'dragenter': {
                    wrapper.classList.add('inner-dragging');
                    break;
                }
            }
        });

        document.getElementsByTagName('h1')[0].addEventListener('drag', e => {
            e.dataTransfer.setData('text', 'bla');
            e.dataTransfer.dropEffect = "link";
        });



        wrapper.addEventListener('dragstart', (e) => {
            console.log('dragstart wrapper');
        });
        wrapper.addEventListener('dragenter', (e) => {
            console.log('dragenter wrapper');
        });
        wrapper.addEventListener('dragover', (e) => {
            console.log('dragover wrapper');
        });

        wrapper.addEventListener('dragleave', (e) => {
            console.log('dragleave wrapper');
            wrapper.classList.remove('inner-dragging');
            e.preventDefault();
        });
        wrapper.addEventListener('drop', (e) => {
            wrapper.classList.remove('inner-dragging');
            e.preventDefault();
        });
    </script>
</body>

</html>
```

</details>

Unfortunately this second approach only works when scripts are enabled inside the iframe. If scripts are disabled, I'm not sure if there's anything we can do

**Comment by mjbvz** [comment]
Ran into this bug while trying to fix this: https://bugs.chromium.org/p/chromium/issues/detail?id=923651&q=iframe%20drag%20drop&can=2

[This GitHub repo](https://github.com/mjbvz/chrome-iframe-drop-bug) demonstrates the approach I was using (adding a drag interceptor element). The works on Firefox and Safari, but not in Chromium

Will see if I can instead programmatically disable pointer events on the iframe while dragging

**Comment by mjbvz** [comment]
For verification: 

1. Try dragging a file from the desktop onto a notebook to open it in the editor
2. Try dragging a file from the desktop onto the markdown preview to open it in the editor

**Comment by Ark-kun** [comment]
@mjbvz  Is dropping files on WebView from VSCode file tree supposed to work the same as for the OS files? Dropping from OS seems to work for me, but dropping from VSCode does not trigger WebView drag events and just opens the file in another VSCode tab instead:

![image](https://user-images.githubusercontent.com/1829149/164149260-84f61c19-b6be-45d0-ab90-d594291cce6b.png)

Sorry if this is not the relevant thread.

**Comment by mjbvz** [comment]
@Ark-kun You need to use insiders for testing this. If you notice problems on insiders, please open a new issue as this one is unrelated to what you are describing

**Comment by rchiodo** [comment]
/verified, dragging and dropping any file on top of a notebook or interactive window will open the file.
