### ISSUE TITLE
Add a blank line at the end of the Search results view.

### ISSUE THREAD

**Issue by teo-tsirpanis** [microsoft/vscode#146935]
VSCode's Explorer file view has a blank line at the end to alow deselecting the current file. Unfortunately the Search results view does not have it, and it can be frustrating because almost always one file's match count will be hidden.

![image](https://user-images.githubusercontent.com/12659251/162033670-7480a43e-df24-4c67-9961-dca701b3716a.png)
![image](https://user-images.githubusercontent.com/12659251/162033714-38557a47-6017-41ef-9fb8-a97956a242a5.png)

**Comment by roblourens** [comment]
Sure, easy enough

**Comment by teo-tsirpanis** [comment]
That was super fast, thank you!
