### ISSUE TITLE
space bar not working

### ISSUE THREAD

**Issue by manojsai9** [microsoft/vscode#146941]
Issue Type: <b>Bug</b>

when I was click on space bar it showing like this in status bar. 
The key combination (Space, Space) is not a command.
(Space) was pressed. Waiting for second key of chord....

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.22GB free)|
|Process Argv|--crash-reporter-id 1fce4265-c273-451c-a5f5-26833dea71ce|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.7
python|ms-|2022.4.0
vscode-pylance|ms-|2022.3.4
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.9.7
swdc-vscode|sof|2.6.29

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
testflight:30433670
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
vscaac:30438847
pynewfile477:30463512

```

</details>

**Comment by gjsjohnmurray** [comment]
1. Open the Keyboard Shortcuts editor (one way is from the gearwheel menu at the bottom of the Activity Bar).
2. Type `"space"` into the filter field.
3. Look for a row whose Keybinding cell starts with <kbd>Space</kbd> and is followed by something else.
4. Right-click on it and choose `Reset Keybinding`
