### ISSUE TITLE
Fail to launch integrated terminal in a folder its name contains a non-ASCII character

### ISSUE THREAD

**Issue by mandel59** [Microsoft/vscode#14691]
- VSCode Version: 1.6.1 (commit 9e4e44c19e393803e2b05fe2323cf4ed7e36880e)
- OS Version: Windows 10 Pro

Steps to Reproduce:
1. Open a folder its name contains a non-ASCII (yet in Unicode) character.
2. Open integrated terminal.

Expected: The terminal appears.
Actual: The terminal process exits with exit-status 1:
![integratedterminal](https://cloud.githubusercontent.com/assets/1079715/19829664/a60ce9ba-9e22-11e6-8f42-4b5b409f5006.PNG)

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
