### ISSUE TITLE
Aggressive inline completions when typing within line

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#146948]
![Recording 2022-04-06 at 12 44 48](https://user-images.githubusercontent.com/323878/162058423-4fd3e498-c9d7-4de0-9eae-90c6c298da4b.gif)

Is this how it's supposed to work? I sometimes see inline completions show up just when moving the cursor around, and it moves the whole line around and is distracting. But it doesn't happen every time, seems to be just when I was recently editing or maybe after triggering suggestions. After a bit, it will stop happening.

**Comment by jrieken** [comment]
Pushed a fix for not doing inline quick suggest when inside words. The other part of this issue is tracked in https://github.com/microsoft/vscode/issues/146529

**Comment by jrieken** [comment]
fyi @bpasero
