### ISSUE TITLE
Refresh Explorer command in `workbench.view.explorer` also reveals active file in explorer

### ISSUE THREAD

**Issue by zardoy** [microsoft/vscode#146917]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.67.0-insider (Universal)
Commit: f050b17dacedba13962244b13c70084a473d08f7
Date: 2022-04-06T05:15:27.397Z
Electron: 17.3.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 20.6.0

Steps to Reproduce:

1. Focus some folder
2. Click *Refresh Explorer* button or execute command with the same name

Expected:

Focus on the same folder

Actual:

Explorer focus moves to the active fiile

---

This is especially annoying as if I'm in big node_modules folder, vscode's watcher doesn't pick any changes from fs and I need to trigger this command. In case if focus was on empty package folder, I need to remember where I was.

**Comment by JacksonKearl** [comment]
As designed, see https://github.com/microsoft/vscode/issues/67118

You can disable `explorer.autoReveal` to get rid of this behaviour.

**Comment by zardoy** [comment]
This works, but disabling auto reveal means I lose the track of active file whenever I switch active tab. Luckily `"explorer.autoReveal": "focusNoScroll"` is more what I want, but I think *no scroll* behavior will turn into annoyance over time.

To be honest, I still don't really understand the usecase from https://github.com/microsoft/vscode/issues/67118#issuecomment-458177911. For now, `Refresh Action` more looks like a shortcut for two actions for some specific workflow. This workflow doesn't suit my needs as you can see from my first comment.

**Comment by zardoy** [comment]
👆 @JacksonKear //cc @bpasero
