### ISSUE TITLE
half of code in html file has lost syntax coloring

### ISSUE THREAD

**Issue by andrewgale1** [Microsoft/vscode#14696]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 16.1.0
- Extensions: ms-vscode.csharp-1.4.1

most code is red in color, file is fine and there are no errors. have tried new files with code pasted in etc. and have not been able to remedy. ?

**Comment by aeschli** [comment]
@andrewgale1 Can you add a source example and let us know which color theme you are using?

**Comment by andrewgale1** [comment]
![screen shot 2016-11-01 at 10 19 57 am](https://cloud.githubusercontent.com/assets/21045477/19899388/31b1bf4e-a01d-11e6-83b5-71eb473d0b31.png)

theme is dark+

**Comment by andrewgale1** [comment]
Hi,
earlier I posted a screenshot and theme.. but I figured it out. super embarrassing, it was an extra set of quotation marks.
this was the first thing I suspected when this started happening, and I checked and CHECKED and checked and could not find anything amiss. but today I saw that extra “.
i apologize for wasting your time.
all is well, thank you

**Comment by aeschli** [comment]
@andrewgale1 No problem. Can you also paste the source code that shows the problem? What's interesting is where the red color starts.

**Comment by aeschli** [comment]
Closing due to lack of information
