### ISSUE TITLE
Renamed file title not updated in the tab

### ISSUE THREAD

**Issue by LoyalPotato** [microsoft/vscode#146998]
Issue Type: <b>Bug</b>

Not sure how I achieved this behaviour but I had renamed the file and noticed the next day, after opening my laptop from sleep mode, that the tab is still with the old file name.

In the explorer:
![image](https://user-images.githubusercontent.com/10759876/162192691-7464fd9d-e6dc-4444-bb2e-386c01271971.png)

In the tab:
![image](https://user-images.githubusercontent.com/10759876/162192716-1197fb61-bb01-41e8-ba12-f3ed5b589ab3.png)

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 2a9627bd-c53a-4898-ad5b-247ffb230da4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
add-reference|adr|1.0.2
namespace|adr|1.1.2
user-secrets|adr|2.0.1
Bookmarks|ale|13.2.4
project-manager|ale|12.5.0
quitcontrol-vscode|art|4.0.0
npm-intellisense|chr|1.4.1
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|12.0.5
vscode-html-css|ecm|1.11.0
vsc-material-theme|Equ|33.4.0
prettier-vscode|esb|9.5.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
dotnet|for|0.0.4
vscode-pull-request-github|Git|0.40.0
todo-tree|Gru|0.0.215
output-colorizer|IBM|0.1.2
csharpextensions|jch|1.3.1
vscode-nuget-package-manager|jmr|1.1.6
vscode-csharp-snippets|jor|1.1.0
axios-snippets|loy|1.0.2
azure-pipelines|ms-|1.202.0
vscode-azureappservice|ms-|0.23.1
vscode-azurefunctions|ms-|1.6.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.13.0
vscode-cosmosdb|ms-|0.18.1
csharp|ms-|1.24.3
vscode-dotnet-runtime|ms-|1.5.0
data-workspace-vscode|ms-|0.1.1
mssql|ms-|1.13.0
sql-database-projects-vscode|ms-|0.14.1
anaconda-extension-pack|ms-|1.0.1
azure-account|ms-|0.10.1
azurecli|ms-|0.5.0
docthis|oou|0.8.2
vscode-nuget-gallery|pat|0.0.24
material-icon-theme|PKi|4.15.0
vscode-css-peek|pra|4.2.0
java|red|1.4.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.6.0
LiveServer|rit|5.7.5
code-settings-sync|Sha|3.4.3
vscode-taskexplorer|spm|2.9.1
autoimport|ste|1.5.4
errorlens|use|3.4.2
gitflow|vec|1.2.1
vscode-java-debug|vsc|0.40.0
vscode-todo-highlight|way|1.0.5
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.13.20
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
The file system is case insensitive, so the file was never really renamed. cc @bpasero anyways.

**Comment by bpasero** [comment]
No, the rename works fine on disk. Here is how to get out of it:
* close the tab
* close vscode
* start vscode
* open the tab
