### ISSUE TITLE
Terminal doesn't run in 1 single python file on Xubuntu in VSCode 1.65&1.66

### ISSUE THREAD

**Issue by OlofSigling** [microsoft/vscode#146901]
Hi, I'm very new to coding and VSCode in general, but am encountering a really annoying bug that has been pestering me on and off for 2 days now. I'm running VSCode on Xubuntu 20.04. I'm writing in Python and trying to run my code in the terminal in VScode to check its output and stuff. However, what I've been encountering now is that for some reason, there's a 50% chance when I start a new session of VScode of my terminal never starting or running 1 specific python file. If I open another python file, it will run fine, but if I switch back to the first one, it will just not run anything. For some weird reason though, when I use "Run selection/line in terminal", it does work! But this gives me the terminal with ">>>" (which I'm not really sure what is the difference), which doesn't allow me to navigate the filesystem, outputs the full file to the terminal which is just not readably useful and I cant find out how to cancel it. Furthermore, when I try to close VSCode after trying to run a terminal, it will always give me a "Closing the window is taking longer than expected..." window, which never ends, meaning I have to force quit VScode. I tried running the file from the actual terminal by typing it in, but this just makes my terminal unusable because nothing happens and keyboard interrupt doesnt work anymore either. I also tried commenting out all my code and even deleting it, but this doesnt work either, so its not related to my code, as also moving the code to another file solves the issue (for the time being). 

Last time this all happened, I solved it by rolling back from 1.66 to 1.65. Then, it happened again, and I solved it by migrating my code to another file. I'm kind of tired of having to remake files again and again each time, so I wanted to know if this issue can be solved some other way. Apologies if it has already been answered somewhere, but I could not find this question relating to it only happening on 1 file at a certain time. Thanks in advance!

**Comment by meganrogge** [comment]
When you see >>> you can use ctrl c to exit that and it will get you back to a state where you can run commands
