### ISSUE TITLE
Comments(single-line and multi-line ) in TypeScript file is switching color.

### ISSUE THREAD

**Issue by SyedMohammad-Hasan** [microsoft/vscode#146982]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.0-insider
- OS Version: Linux x64 5.16.15-76051615-generic

https://user-images.githubusercontent.com/98533939/162159831-11aa82c7-db6f-48bb-8cc7-56fb01604065.mp4

**Comment by alexdima** [comment]
Most likely caused by https://github.com/microsoft/vscode/pull/146552

**Comment by alexdima** [comment]
Most likely this is already fixed by https://github.com/microsoft/vscode/commit/1f202b0f2ef1aeba463a1fe39291456f253e79a1

**Comment by SyedMohammad-Hasan** [comment]
When this fix will be released in code-insiders.

**Comment by SyedMohammad-Hasan** [comment]
This issue has been fixed in latest code-insiders release. 
Thanks to all the contributors.
