### ISSUE TITLE
Allow extensions to skip selecting the debugger type during F5 and "Run and debug"

### ISSUE THREAD

**Issue by jureid** [microsoft/vscode#146956]
We have two types of debuggers for cpptools: cppdbg and cppvsdbg.
https://github.com/microsoft/vscode-cpptools/blob/main/Extension/package.json#L2755

Currently, when users press F5, they have to select the debugger type:
![image](https://user-images.githubusercontent.com/44306969/162075052-a9a8e259-f01a-4a48-b4f5-0fa480d0ece4.png)
After selecting the type of debugger, the user can choose from a list of detected predefined configurations. The configurations in this list are only for the type of debugger selected in the previous step. For example, if the user selected GDB/LLDB (cppdbg), then they won't see any configurations for cl.exe (which is cppvsdbg):
![image](https://user-images.githubusercontent.com/44306969/162075316-51c32fa5-d563-4051-b97c-3727b1e6df58.png)

We recently shipped a new play button run/debug experience (as an A/B test), where users don't need to pick a debugger type. After they click the play button, they see a list of detected predefined configurations from both debugger types. Notice how both cl.exe (cppvsdbg) and gcc/clang (cppdbg) are in this list:

![image](https://user-images.githubusercontent.com/44306969/162075473-ad710c9c-4fac-4fcd-be80-7ffb330a8739.png)

We want F5 to have the same experience as the play button to a) reduce the number of steps for the first-time run/debug and b) provide consistent experiences within the editor. 

Is it possible to skip the step of selecting the debugger type and instead provide a list of configurations across all debugger types?

cc @elahehrashedi

**Comment by weinand** [comment]
Please continue the discussion in #146338
