### ISSUE TITLE
Install update issue

### ISSUE THREAD

**Issue by AS2324** [microsoft/vscode#146980]
When I try to update the VSCode to the latest version it says installing update but it never completes and also does not give any clue if it is failed.

![image](https://user-images.githubusercontent.com/71608542/162148472-0dc75b74-4da9-4499-93ab-d08248351464.png)

![image](https://user-images.githubusercontent.com/71608542/162148579-69f90884-6c35-4729-b22e-d2530349990b.png)

**Comment by gjsjohnmurray** [comment]
Please use the About option from the Help menu, then the Copy button on the popup, then paste the info here.
