### ISSUE TITLE
How can I using auto reply to send ctrl + c

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#146908]
When I running webpack-dev-server:

![image](https://user-images.githubusercontent.com/41773861/161959758-7af64018-9009-43cf-8130-1a2df10f1dbd.png)

If I press `ctrl + c` to stop the server:

![image](https://user-images.githubusercontent.com/41773861/161959876-73c61ae9-3241-4595-90ea-5133a3fb9007.png)

I can't see the suggestion if I type yarn:

![image](https://user-images.githubusercontent.com/41773861/161960132-47e9e590-2fb0-46e4-badb-7ce9ff93e80d.png)

But If I press `ctrl + c` again, I will get the suggestion:

![image](https://user-images.githubusercontent.com/41773861/161960234-15b4d78b-7241-45e8-a435-d797137e6415.png)

So, I want to using the terminal to auto reply `ctrl + c`:
I try set:

```jsonc
{
    "terminal.integrated.autoReplies": {
        // auto reply ctrl + c
        "<i> [webpack-dev-server] Gracefully shutting down. To force exit, press ^C again. Please wait...": "\u0003C"
    },
}
```

But seems not work.

@meganrogge @Tyriar

**Comment by Lemmingh** [comment]
`CTRL+C` is SIGINT (Signal Interrupt).

If I recall correctly, it is not treated as keyboard input, but captured by OS and passed to the signal handler of target process.
