### ISSUE TITLE
Cannot close a ipynb file that does not exist

### ISSUE THREAD

**Issue by jrounds** [microsoft/vscode#146940]
Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19042

I don't know if I am going to be able to give you affirmative steps to reproduce, so feel free to close.  Thought I would report it though.

I have had an open ipynb for some time in vscode.   Sometime ago there was some triming of my repo and the path to that open ipynb no longer exist. I don't use vscode as my primary IDE, so the file just sat open in my vscode workspace for some time.

I went to experiment with some dev in vscode, and I closed all on open files, but I can't get past this open ipynb.  vscode refuses to close it.

It starts like this:
1. open ipynb file has no contents but shows text "The editor could not be opened. Try Again"
2. Try Again clicked. Popup from vscode "Unable to resolve filesystem provide with relative file path <snip old path to file>.
3.  Popup offers no solutions. close the popup.
4. Right click file tab close file. 
5. Two popups.  One lower right in grey says "Unable to resolve filesystem provide with relative file path <snip old path to file>.
6. Second standard looking popup says "Do you want to save changes you made to <file>."
7. Click "Don't Save".
8. GOTO 1 nothing has changed.  Loop forever through 1 to 8.

Thats my state.  Think I have to get rid of the workspace to get rid of the open file?

**Comment by bpasero** [comment]
Sounds like https://github.com/microsoft/vscode/issues/140667. I would need exact steps for how to reproduce, preferably with a fresh `--user-data-dir` and fresh `--extensions-dir` to start from zero. These steps should include which extension to install and which file to create and then possibly delete?
