### ISSUE TITLE
No outline in workspace

### ISSUE THREAD

**Issue by XIAOHEDEHE** [microsoft/vscode#146978]
Issue Type: <b>Bug</b>

I use vscode to edit my latex, but recently I can not find my outline in the workspace, it told me:"file not recognized: File format not ". But it is avaliable last version.

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.94GB (2.29GB free)|
|Process Argv|D:\\OneDrive\\1-学习\\现代控制笔记 --crash-reporter-id ecf89590-f8ed-4b8d-943c-d5fc42a0da3c|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
code-runner|for|0.11.7
latex-workshop|Jam|8.24.1
better-cpp-syntax|jef|1.15.13
vscode-language-pack-zh-hans|MS-|1.66.2
python|ms-|2022.4.0
vscode-pylance|ms-|2022.4.0
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.4
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
vscaat:30438848
pynewfile477:30463512

```

</details>

**Comment by jrieken** [comment]
Please attach the file and a screen capture

**Comment by XIAOHEDEHE** [comment]
> Please attach the file and a screen capture
![Screenshot 2022-04-07 150829](https://user-images.githubusercontent.com/68885970/162140763-5f9ebd78-6882-4f50-a7f4-4c83eea03bfd.png)
[note .txt](https://github.com/microsoft/vscode/files/8440436/note.txt)

**Comment by jrieken** [comment]
Thanks, please file against the latex extension
