### ISSUE TITLE
import completion should not triggered by dot

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#14698]
- VSCode Version: 1.6.1
- OS Version: Windows Server 2012 R2

Steps to Reproduce:

```
// type the following
import { something } form '[cursor here]

// then type in a dot (".")
```

expected: no completion. Users may want to do ".." for parent folder.
actual: completion triggered and list installed npm packages

![image](https://cloud.githubusercontent.com/assets/3254987/19831903/3911615e-9dca-11e6-8d32-c181e3e84a6e.png)

So what happen is if user wants to reference parent folder (".."), it will end up like this:

![image](https://cloud.githubusercontent.com/assets/3254987/19831910/59d135ea-9dca-11e6-8621-d1db245464bd.png)

**Comment by waderyan** [comment]
I believe this is fixed now. https://github.com/Microsoft/TypeScript/issues/11044

Can you try on [Insiders build](https://code.visualstudio.com/insiders) and see if it reproduces for you? I just tried and it worked using the setup you provided in your description. Ping me and I'll reopen if it doesn't work.
