### ISSUE TITLE
Duplicate completion item when search extensions by category

### ISSUE THREAD

**Issue by quanzhuo** [microsoft/vscode#146987]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0
- OS Version: Windows 11 22000.593

Steps to Reproduce:

![duplicateCompletionItem](https://user-images.githubusercontent.com/8767119/162164694-5ddf8577-c51c-4ca3-b4ed-d280d0c28189.gif)

**Comment by jrieken** [comment]
@sandy081 what kind of the completion result is this? complete or incomplete?

**Comment by sandy081** [comment]
I do not know about that - I use `SuggestEnabledInput` and pass suggest results through `SuggestResultsProvider`. Wondering why this is not happening out of sources.

**Comment by jrieken** [comment]
This is an actual bug in suggest land. When having suggestions and when typing into a new word, then we trigger suggest again. We do this to give other completion providers a chance to join the current session. Now there is a bug when there is just one provider - we will re-trigger it _and_ re-use its completions


Good news is that for https://github.com/microsoft/vscode/issues/167242 I have pushed a change that fixes this. Therefore closing as "accidentally" fixed
