### ISSUE TITLE
black screen when visual studio code launches

### ISSUE THREAD

**Issue by shelby313** [microsoft/vscode#146995]
Does this issue occur when all extensions are enabled  or disabled?: Yes

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. 1.66.0
2. 64bit
![ext](https://user-images.githubusercontent.com/103187309/162188561-fdef2929-5ece-4b9f-a0e6-af371bed6896.PNG)
![vscode](https://user-images.githubusercontent.com/103187309/162188570-73bc6041-db01-443e-92cd-ad47a052e935.PNG)

**Comment by deepak1556** [comment]
Can you provide the output of `code --verbose`
