### ISSUE TITLE
Copying filename in macOS Finder does not paste into VS Code

### ISSUE THREAD

**Issue by joshuaiz** [microsoft/vscode#146936]
Issue Type: <b>Bug</b>

1. Copy filename in macOS Finder
2. Use CMD+V to paste in VS Code file
3. Nothing happens

This used to work before the last VS Code update. Have tried with all extensions off and with latest VS Code Insiders and issue persists.

VS Code version: Code 1.66.0 (Universal) (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|64.00GB (18.68GB free)|
|Process Argv|--crash-reporter-id 0e788102-c0a0-4700-91e5-4dbfc2df58a8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.4
numbered-bookmarks|ale|8.2.0
copy-relative-path|ale|0.0.2
astro-vscode|ast|0.13.4
vscode-custom-css|be5|6.0.2
htmltagwrap|bra|0.0.7
vscode-tailwindcss|bra|0.7.7
vscode-toggle-quotes|Bri|0.3.6
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
woocommerce|cla|1.1.0
vscode-eslint|dba|2.2.2
vscode-dash|dee|2.4.0
vscode-babel-coloring|dza|0.0.4
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.5.0
vscode-svelte-snippets|fiv|0.5.0
code-runner|for|0.11.7
copilot|Git|1.12.5517
vscode-graphql|Gra|0.3.53
customize-ui|ioc|0.1.61
monkey-patch|ioc|0.1.16
RelativePath|jak|1.4.1
vscode-liquid-snippets|kil|2.0.3
graphql-for-vscode|kum|1.15.3
tailwind-sass-syntax|mac|1.3.0
prettify-json|moh|0.0.3
vscode-duplicate|mrm|1.2.1
live-server|ms-|0.2.12
sublime-keybindings|ms-|4.0.10
php-docblocker|nei|2.7.0
push|njp|0.8.21
savebackup|pur|0.0.4
toggle|reb|0.0.2
postcss|ric|2.0.0
rome|rom|0.4.2
vscode-paste-and-indent|Rub|0.0.8
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.0
shopify-liquid|sis|2.3.0
vscode-fileutils|sle|3.5.0
vscode-html-to-css|tau|1.2.0
markdown-links|tch|0.8.0
vscodeintellicode|Vis|1.2.18
vscode-icons|vsc|11.10.0
branch-in-window-title|wis|0.1.2
local-history|xyz|1.8.1

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by joshuaiz** [comment]
<img width="848" alt="CleanShot 2022-04-06 at 12 40 44@2x" src="https://user-images.githubusercontent.com/1096738/162035457-104b2592-acb5-4ff0-8d0e-fe61a76939a5.png">

^^ copying filename directly in Finder. When I paste into VS Code nothing happens.

Copying text within VS Code works. There are no key command conflicts.

**Comment by JacksonKearl** [comment]
same as #146867

**Comment by joshuaiz** [comment]
Sorry did not see the other issue.

**Comment by JacksonKearl** [comment]
Same issue affecting all platforms AFAIK
