### ISSUE TITLE
Better java, gradle support

### ISSUE THREAD

**Issue by scgm11** [Microsoft/vscode#14702]
- VSCode Version:1.6.1
- OS Version: MacOS Sierra

We would like a more out of the box java support without relying on maven or eclipse.

1) open a java project (gradle if possible)  and be able to execute gradle tasks out of the box
2) be able to compile and run java apps
3) be able to local and most important remote debug java applications
4) keep on improving git support!

plugins existing now are not giving a good experience working with them in such a way.
This features would make vscode the one ide to rull them all, thanks for the excellent work!

**Comment by octref** [comment]
1, 2, 3 can be done by extension. Try opening an issue for https://github.com/redhat-developer/vscode-java

If you have concrete points where we can improve git, feel free to open another issue.
