### ISSUE TITLE
Save As doesn't work for notebooks

### ISSUE THREAD

**Issue by notuntoward** [microsoft/vscode#147032]
Issue Type: <b>Bug</b>

File --> Save As doesn't work when I'm trying to save a jupyter notebook.  By default, the VSC menu selects the JSON extension, which I guess must mean .ipynb, since .ipynb is a JSON format, and there's no file format option for "notebook" or "ipynb."   If I try to save as JSON, I get a failure message, saying that <new file name>.JSON is not supported by .ipynb files. (screenshot below)

Saving as .html fails similarly.

![image](https://user-images.githubusercontent.com/3851891/162270273-3a814d4b-1cef-4d6d-abe2-a11e1e97d744.png)

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (1.51GB free)|
|Process Argv|--crash-reporter-id 3002f579-7dd2-47a2-90cb-6aed048314d1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.4
atlascode|atl|2.10.11
markdown-mermaid|bie|1.13.2
mermaid-markdown-syntax-highlighting|bpr|1.2.3
vscode-jupytext|con|0.1.2
auto-dark-mode-windows|dan|1.0.11
gitlens|eam|12.0.5
vscode-drawio|hed|1.6.4
Python-autopep8|him|1.0.2
cyberbrain|lai|0.2.1
zotero|mbl|0.1.10
document|min|2.1.8
vscode-docker|ms-|1.21.0
python|ms-|2022.4.0
vscode-pylance|ms-|2022.4.0
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.4
remote-wsl|ms-|0.66.0
vscode-drawio-plugin-mermaid|nop|0.1.5
vscode-yaml|red|1.6.0
vscode-mermaid-editor|tom|0.14.0
emacs-mcx|tut|0.41.2
vscodeintellicode|Vis|1.2.18
vscode-mermaid-preview|vst|1.6.2
vscode-todo-highlight|way|1.0.5

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by StephaneKazmierczak** [comment]
Regular save is also having some issue for notebook, I am working on a remote machine, sometime saving take minutes, sometime it is not even saving and I loose my work. It is super annoying

**Comment by rebornix** [comment]
This issue should be gone now. Please try the latest VS Code.
