### ISSUE TITLE
'NPM Script' is missing

### ISSUE THREAD

**Issue by susiwen8** [microsoft/vscode#147077]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.66.1 (Universal)
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:49:47.400Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 20.5.0

Steps to Reproduce:

This is no 'NPM Script' option
<img width="191" alt="Screen Shot 2022-04-08 at 8 06 02 PM" src="https://user-images.githubusercontent.com/20318608/162432299-af0c2f98-e80b-41da-bffe-a9a79dc343c1.png">

**Comment by IllusionMH** [comment]
do you have `package.json` in root of your workspace?
May be #119868

**Comment by susiwen8** [comment]
<img width="310" alt="Screen Shot 2022-04-08 at 8 20 18 PM" src="https://user-images.githubusercontent.com/20318608/162434365-539dd25b-b554-4dde-b2b0-e90d01b524d1.png">
of course

**Comment by IllusionMH** [comment]
Do you see  `Focus on NPM Scripts View` in Command palette (<kbd>Ctrl/Cmd</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)? Try to run it

**Comment by susiwen8** [comment]
> Do you see `Focus on NPM Scripts View` in Command palette (Ctrl/Cmd+Shift+P)? Try to run it

Yes, Thanks!!!!! But I want to move it in `explorer`

**Comment by IllusionMH** [comment]
> But I want to move it in explorer

![image](https://user-images.githubusercontent.com/1312662/162449330-10233af5-5bbc-4e1a-970b-f5565a12c8c8.png)

Just drag'n'drop it to Explorer view or right click on NPM Scripts header and pick Reset Location

**Comment by susiwen8** [comment]
> Just drag'n'drop it to Explorer view or right click on NPM Scripts header and pick Reset Location

It work!!! Many thanks!!!!!! You are life saver!

**Comment by susiwen8** [comment]
> Just drag'n'drop it to Explorer view or right click on NPM Scripts header and pick Reset Location

It work!!! Many thanks!!!!!! You are life saver!
