### ISSUE TITLE
SCM - Arrow up in git history does not put cursor at end

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#147057]
Talking about the git commit box. Compare that with search input box.

**Comment by gjsjohnmurray** [comment]
If it put the cursor at the end wouldn't you then have to arrow up more times (at least once more) to get to the previous commit message? The first would take you from end to beginning if a single-line message. For a wrapped message each arror up moves you to the line above. Only when at the top will arrow up take you to the start of the message, from where the next arrow up moves you to the previous commit message.

**Comment by bpasero** [comment]
I do not understand the previous message. This issue is for consistency in other places. An alternative is to select all, so that you can "over type" to remove.

**Comment by gjsjohnmurray** [comment]
@bpasero in the recording below I am using arrow up to review commit messages for this repo. The first section of the recording (up to the fade to black) is current behaviour. In the second section I simulate arrow up having put the cursor at the end of the previous message (I do this by clicking there each time). When the message takes only one line it now requires two arrow ups to go to the previous one. For wrapping messages it takes more.
![junk](https://user-images.githubusercontent.com/6726799/162425395-6361ff60-9ed9-4772-9e71-845dbc0e240d.gif)

**Comment by joaomoreno** [comment]
@bpasero, @gjsjohnmurray hits it straight: while search is optimized for single line history entries, SCM is optimized for multiple lines. The likelihood that you'll see a multi-line entry in SCM is not only higher than Search, but just high in general, so we have fine tuned the UX to behave better in those cases.

If you want to experience a bad scenario Search can't handle well:

1. Search for a single word
2. Search for a 3-line expression (use Shift Enter)
3. Search for a single word

Now navigate back in history. When you get to the 3-line suggestion, you have to press <kbd>UpArrow</kbd> multiple times before you get to see the first single word in history.

I don't know what the fix here is. Consistency is good, so we could align either example with the other. But I also don't want to un-optimize flows for either case.
