### ISSUE TITLE
Typescript autocompletion stop working

### ISSUE THREAD

**Issue by agorhub** [microsoft/vscode#147019]
Issue Type: <b>Bug</b>

I just open my angular project, I work... after a while the message "TypeScript Language Features died unexpectedly 5 times in 5 minutes" appears.
No more errors, autocompletion, etc. works.

Thanks

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 80e98117-905f-4047-b157-0449db866526|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.5.0
gitignore|cod|0.7.0
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|12.0.5
rightclick-git|Eve|2.0.0
php-intellisense|fel|2.3.14
angular-bootstrap|her|4.0.9
vscode-nuget-package-manager|jmr|1.1.6
Angular2|joh|13.0.0
git-graph|mhu|1.30.0
Angular-BeastCode|Mik|10.0.3
csharp|ms-|1.24.3
anaconda-extension-pack|ms-|1.0.1
python|ms-|2022.4.0
vscode-pylance|ms-|2022.4.0
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.9.7
vscode-typescript-tslint-plugin|ms-|1.3.4
material-icon-theme|PKi|4.15.0
platformio-ide|pla|2.4.3
java|red|1.4.0
vscode-yaml|red|1.6.0
vscodeintellicode|Vis|1.2.18
vscode-java-debug|vsc|0.40.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.2
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
gitblame|wad|8.1.0
debug|web|0.25.1
php-debug|xde|1.25.0
php-pack|xde|1.0.3
vscode-open-in-github|ziy|1.3.6
php-intellisense|zob|1.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
pynewfile477:30463512

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
