### ISSUE TITLE
Improve vscode.dev local file system warning

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#147025]
![image](https://user-images.githubusercontent.com/8599/162248667-ba52c761-3239-44df-b19e-16a57b51cbe9.png)

1. `Local File System Access` is probably not the final spec name and doesn't help users to understand what is working and why. It is also misleading, as [parts of the API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API#browser_compatibility=) are supported. `Your browser doesn't support opening local folders` would be clearer.
2. `Open Files …` seems like it should not be working, according to the text above? Maybe `Open single Files …` is a better wording?
3. As a user tried to open a file, could `Open single Files …` also be the primary action and not remote?
4. Lastly, `Learn More` sits between the 2 opening actions. Could it be in the text or as the left-most button?

cc @bamurtaugh 

<hr>

Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0
Embedder: vscode.dev

**Comment by bamurtaugh** [comment]
1. Agreed - just by that warning alone, it'd seem like anything local isn't supported. 
2. Maybe `Open a file...`?
3. +1 to your suggestion.
4. The button progression `Learn more` `Open Remote...` `Open a file`, with the last being the primary

cc @joaomoreno

**Comment by bpasero** [comment]
Erich is out, so I will go ahead and close this since I like the reasoning: opening loose files on old browsers is not a good experience so I like that we drive users towards the full experience.

**Comment by connor4312** [comment]
It seems like the "Open Files" and "Learn More"'s functionalities are swapped

![Recording 2022-04-26 at 15 26 21](https://user-images.githubusercontent.com/2230985/165402995-fb336087-b180-4ed3-a1bc-f87b9e267034.gif)

**Comment by bpasero** [comment]
🤦

**Comment by jrieken** [comment]
_"Your current browser doesn't support..."_ read weird. The "current" assumes that I am changing my browser. I would suggest 

* Your browser doesn't...
* The browser that you are using doesn't...
* This browser doesn't...

**Comment by bpasero** [comment]
Yeah good point, I removed "current".
