### ISSUE TITLE
Terminal flaky tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#147063]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=165808&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=d239d20c-b192-5a3e-69bb-696f63b250a5&l=102

Lately terminal tests became flaky with:

```
  1) VSCode Smoke Tests (Web)
       Terminal
         Terminal Editors
           should update color of the tab:
     Error: Timeout: is active element '.quick-input-widget .quick-input-box input' after 20 seconds.
      at Code.poll (D:\a\_work\1\s\test\automation\src\code.ts:296:11)
      at Code.waitForActiveElement (D:\a\_work\1\s\test\automation\src\code.ts:232:3)
      at QuickInput.waitForQuickInputOpened (D:\a\_work\1\s\test\automation\src\quickinput.ts:20:3)
      at Terminal.runCommandWithValue (D:\a\_work\1\s\test\automation\src\terminal.ts:88:3)
      at Context.<anonymous> (src\areas\terminal\terminal-editors.test.ts:21:4)
```

This tests uses `runCommandWithValue` and there is a somewhat questionable line here:

https://github.com/microsoft/vscode/blob/921264bfe3ffbbfe5ec8c4b08214b88e2148fa3e/test/automation/src/terminal.ts#L83-L88

Fyi we had updated playwright to latest.

I will go ahead and skip tests for now that use this method.

**Comment by bpasero** [comment]
Oh, that method is used in almost all tests it seems 😢

**Comment by bpasero** [comment]
Since this seems to happen almost in every run now, skipped the tests.

**Comment by bpasero** [comment]
My attempt to fix and enable them again is pushed. In 

https://github.com/microsoft/vscode/commit/d9db5d10ec9925c18f3ac118d9fa902fd918316d#diff-8a3952cf8d0bca4af99d53039db65e935a66ed022c95ce04d1b040a50b7974efR76-R77

Note how I added more commands for when we want to `_waitForTerminal`. My feeling is this happens:
* we open a terminal via quick pick
* we want to run a command e.g. to change tab color
* we expect a picker to open to ask for color
* however meanwhile in the background the terminal managed to open and grabs focus

**Comment by meganrogge** [comment]
fixed with https://github.com/microsoft/vscode/pull/148918/files#diff-673c11233fee33ba66e78ed424b385b00a13679777d129f8d7e22204700e8b2b by @Tyriar
