### ISSUE TITLE
F12 preview window gets in way of actual Go To Definition

### ISSUE THREAD

**Issue by Murtaya** [microsoft/vscode#147030]
Issue Type: <b>Bug</b>

When I hit F12, I want to go to the definition of what the cursor is on.  However, VSCode always pops open some preview window which is not useful and just an unnecessary road block in development.  I'm also not seeing a way to turn it off; if there is one, it's not obvious (I would argue it should be off by default).

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2255 CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.69GB (41.54GB free)|
|Process Argv|--crash-reporter-id f53a4338-faa4-4c22-8800-ef494cfc4959|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.5.0
vs-keybindings|ms-|0.2.1
vscode-typescript-tslint-plugin|ms-|1.3.4
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.9.2
vscode-jest|Ort|4.2.1
save-and-run|wk-|0.0.22

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

You should get peek preview instead of navigation when there are multiple locations where you can be navigated. For single locations you should be navigated right away.

Is it a behavior that you are observing?

Also you might want to tune "family" of `editor.gotoLocation` settings that control this behavior.
