### ISSUE TITLE
unable to remove a contributor

### ISSUE THREAD

**Issue by 1000milesdrunk** [microsoft/vscode#147004]
Issue Type: <b>Feature Request</b>

my current laptop belonged to somene before now i am using it all the commits i did using the source control on vs code is in his name instead of mine it is giving me option to add myself as a co author but i am unable to remove him he is not there in git hub personal repo as a contributor but all my commits are with his name 

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

**Comment by lszomoru** [comment]
The name and email address is being stored in various git config settings. Use the following docs to update these:
* https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git
* https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address
