### ISSUE TITLE
PHP syntax highlighting does not correctly detect end of string

### ISSUE THREAD

**Issue by pedroterzero** [microsoft/vscode#147037]
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:41.156Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.13.0-39-generic snap
```

OS is Ubuntu 20.04

Description
==
When I use a string variable formatted as in the example, code after the variable is incorrectly coloured

This is what it ends up looking like for me:
![Screenshot from 2022-04-07 20-48-23](https://user-images.githubusercontent.com/72469659/162275230-dcd9fbc2-e2c6-441f-9a05-cf06824e6136.png)

I'd expect this to parse the string correctly. The output should look more like this:
![Screenshot from 2022-04-07 20-50-07](https://user-images.githubusercontent.com/72469659/162275551-bda185f8-5b21-4dd2-ae22-3e50a062caee.png)

Test case:
==
```php
<?php

$test = 'AND [' . $foo['bar'];

// hi i am a comment
if (true) {
    print 'test';
}
```

Steps to Reproduce:

Create a test file, test.php with the contents from the test case

**Comment by alexr00** [comment]
@pedroterzero it looks like the PHP grammar we use assumes that strings that start with `AND` are sql. Is it your intent that `$test` is sql?

**Comment by pedroterzero** [comment]
> @pedroterzero it looks like the PHP grammar we use assumes that strings that start with `AND` are sql. Is it your intent that `$test` is sql?

In this particular instance it happened to be a SOLR query. It's a legacy project.

**Comment by alexr00** [comment]
Thanks! I've moved this issue to the upstream repo that we get our PHP syntax highlighting grammar from: https://github.com/atom/language-php/issues/453
