### ISSUE TITLE
JSON editing - empty object & array snippet block schema suggestions

### ISSUE THREAD

**Issue by rewrking** [microsoft/vscode#147006]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0
- OS Version: Windows 10 (10.0.19041.1415) - probably all OS's though

Steps to Reproduce:

1. Edit a json file that uses a schema & has suggestions when editing objects (package.json in node.js projects for example)
2. Enter a key name for an object (`bugs` works well) - `"` `b` `u` (suggestions should show by now) `enter`
3. Cursor should be here:

```json
{
  "name": "nodejs-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "bugs": {|}, // cursor
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

4. Hit `enter` to expand the object. The cursor is now here

```json
{
  ...
  "bugs": {
    |    // cursor
  }, 
  ...
}
```

Before typing anything else, note where there's selections - white space before and after the cursor. This tells me that it's some kind of snippet, but I'm not 100% sure. It's like the snippet for this has a `$1` where it should have `$0` if that makes sense.

5. Type `"`. I would expect suggestions for `email` and `url`, but nothing comes up because I'm still seemingly 'inside of a snippet'.
6. Now, manually move the cursor somewhere, and back into the `bugs` object and type `"` again. You should now see the suggestions.

This bug comes up quite a bit and I have to do step 6 all the time in order to see the suggestions.

I believe this also comes up with arrays where in the schema, the array items are enum strings, but I don't have a good test for it at the moment.

Edit: This behavior only happens with the setting:

```json
"editor.autoClosingQuotes": "never"
```

**Comment by aeschli** [comment]
Here is what I see with the latest insiders and no user settings (all default)

![json-code-complete-in-snippet](https://user-images.githubusercontent.com/6461412/162246653-8e2da04d-c636-4bad-8350-48755b7d8975.gif)

**Comment by aeschli** [comment]
There's a setting `editor.suggest.snippetsPreventQuickSuggestions` which is on by default, but it doesn't see to impact the suggestions here.

So not sure what the expected behaviour is.

**Comment by rewrking** [comment]
Found the setting that causes this behavior. It happens with: 

```json
"editor.autoClosingQuotes": "never"
```

Would be nice to keep this setting and still get suggestions. I don't like having end quotes automatically inserted.

**Comment by jrieken** [comment]
> Type ". I would expect suggestions for email and url, but nothing comes up because I'm still seemingly 'inside of a snippet'.

Yes, JSON completes with snippets by default and that's something that I believe isn't configurable. This means accepting a snippet puts you into snippet mode which suppresses quick suggestions. The reason for that is that the <kbd>Tab</kbd>-key accepts completions _and_ navigates through snippet placeholders which means quick suggestion effectively "block" snippet mode. 

JSON does use `"` as trigger character but _also_ as word character. That weakens the stronger trigger character condition and the normal quick suggest flow is expected (which is suppressed in this snippet case). The difference with `autoClosingQuotes` is that `"|"` (`|` is the cursor, `"` auto inserted) is still a word but the cursor is "inside" a word which makes it not be a quick suggest case and allowing the trigger character flow. 

Potential workarounds

* have an extension that re-defines the JSON word definition to not include `"`
* add a setting to the JSON language service to not complete with snippet mode (similar to TS/JS settings for that)
