### ISSUE TITLE
Hitting backspace doesn't move cursor to previous indent column.

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#14708]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:43:46.054Z)
- OS Version: Linux x64 4.4.0-45-generic
- Extensions: DavidAnson.vscode-markdownlint-0.5.0, EditorConfig.EditorConfig-0.3.4, ajhyndman.jslint-1.2.1, dbaeumer.jshint-0.10.15, dbaeumer.vscode-eslint-1.0.8, eg2.tslint-0.5.39, jakethashi.vscode-angular2-emmet-1.0.9, ms-vscode.cpptools-0.9.2, msjsdiag.debugger-for-chrome-2.1.1, vscodevim.vim-0.4.0

Steps to Reproduce:
1. Type a line, hit return
2. press Tab
3. press backspace

Cursor moves back single space, doesn't move back to previous indent column.

This also happens with exiting code, html tags and inside backticks.

You can use the following code see this.

``` js
@Component({
  selector: 'lifecycle',
  template: `
    <h1 *ngIf="showTitle">
      {{title}}
    </h1>
    <div>
      <ng-content></ng-content>
    </div>
    Count: {{count}}
    <div>
      <button (click)="showTitle=!showTitle">Toggle Title</button>
    </div>
    <div>
      <button (click)="incCount()">+</button>
    </div>
  `,
  styles: []
})
```

**Comment by alexandrudima** [comment]
@rajinder-yadav 

I cannot reproduce. Here I've made a test.js file with the template content. The editor identifies it is indented with spaces @ 2.

Hitting backspace removes two spaces.

![backspace](https://cloud.githubusercontent.com/assets/5047891/19850004/795ef504-9f56-11e6-9930-5ed58c40d756.gif)

There might be an issue with:
* you might have turned this feature off via `editor.useTabStops`
* the indentation detection code might not be working as expected for your file (i.e. check the bottom right corner)

**Comment by rajinder-yadav** [comment]
Closing, I think it's VIM plugin, I tested without plugins and it's work file!
