### ISSUE TITLE
macOS dictionary shortcut is not working on `vscode`.

### ISSUE THREAD

**Issue by luceat-lux-vestra** [microsoft/vscode#147056]
It was requested before but it's not accepted.
I want macOS's built-int `lookup a word` function,  
`Ctrl+Cmd+D` or `three finger dictionary` work fine on `vscode`.

Thanks.
https://github.com/microsoft/vscode/issues/84292#issue-520139053

**Comment by lramos15** [comment]
If #84292 can get to 20 upvotes we will revisit this.

**Comment by luceat-lux-vestra** [comment]
I can't react with that issue.
Please check.
https://github.com/microsoft/vscode/issues/84292

**Comment by ushuz** [comment]
Well, #31047 has 24 upvotes, and it's already in the backlog.

**Comment by lramos15** [comment]
I guess #31047 is the same. I was confused reading it at first as they seemed to say it did work just with the wrong tokens. Now I guess it doesn't work at all. As seeing as #31047 is already over the threshold and is basically the same issue. We will close this as a duplicate and just track #31047.
