### ISSUE TITLE
vs

### ISSUE THREAD

**Issue by yiminghuang** [Microsoft/vscode#14700]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 15.5.0
- Extensions: donjayamanne.githistory-0.1.0, ms-vscode.cpptools-0.9.2, robertohuertasm.vscode-icons-3.0.7

Steps to Reproduce:

1.
2.

**Comment by octref** [comment]
Whatever your problem is, try reinstall your VSCode. `vscode-icons` modifies VSCode source code and can cause problems.
