### ISSUE TITLE
TypeScript and JavaScript feature breaks 5 times in 5second

### ISSUE THREAD

**Issue by krupalpatel92** [microsoft/vscode#147082]
Issue Type: <b>Bug</b>

TypeScript and JavaScript feature breaks 5 times in 5second

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz (4 x 1100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|209, 125, 63|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id d2a2f4a7-7d1e-468e-82f5-a29733d38fe2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
expressjs|ama|2.0.0
vscode-intelephense-client|bme|1.8.2
vscode-tailwindcss|bra|0.7.7
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
cssrem|cip|3.0.0
gitignore|cod|0.7.0
jshint|dba|0.11.0
vscode-eslint|dba|2.2.2
javascript-ejs-support|Dig|1.3.1
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.5
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.5.0
vscode-env|Iro|0.1.0
search-node-modules|jas|1.3.0
twig-language-2|mbl|0.9.2
dotenv|mik|1.0.1
vscode-typescript-next|ms-|4.7.20220406
vscode-typescript-tslint-plugin|ms-|1.3.4
material-icon-theme|PKi|4.15.0
vscode-scss-formatter|sib|2.4.2
mdx|sil|0.1.0
prettier-vscode|Sim|2.0.7
js-jsx-snippets|sky|11.0.0
php-ci|sma|0.4.2
code-spell-checker|str|2.1.11
twig|wha|1.0.2
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
local-history|xyz|1.8.1
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
pynewfile477:30463512

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
