### ISSUE TITLE
Failed to open VS Code from Xilinx Vivado IDE

### ISSUE THREAD

**Issue by eepro-bt** [microsoft/vscode#147052]
On Windows10, when using Xilinx Vivado IDE to open VS Code Editor, this command is used:
d:/program/Microsoft VS Code/Code.exe -g [file name]:[line number]

this command worked fine until version 1.66
now the above command opened VS Code window with nothing but only black

**Comment by aeschli** [comment]
Tested with Version: 1.66.1 (user setup)
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:50:12.141Z

works for me. Tested with various files from the command line.

Does it it work for you from the command line?

**Comment by yizakat** [comment]
I can confirm this is also happening to me with Vivado.

When code is specified as an external editor with the command line file:line, it invokes correctly but displays either a blank black screen or an empty screen with the path of the file at the top and a continually moving progress indicator.  This runs indefinitely.

Eventually, the application has to be killed.

I note the earlier comment from someone with it working fine.  It works fine from the command line directly.  Wondering if it has to do with either trust of workspaces/folders, in this case the folder is created by Vivado so not in a trusted location perhaps, or whether it is trying to load an old workspace.

**Comment by aeschli** [comment]
The folder/file that is opened by Vivado, is it a regular file/folder on the disk? Opening the same file/folder from the terminal does not reproduce the problem?

**Comment by yizakat** [comment]
It is a regular folder, it can be opened by code directly from the command line.  There is an open issue also tracking this problem which should probably be used for any further info:

[https://github.com/microsoft/vscode/issues/147541]

**Comment by aeschli** [comment]
ok, thanks, marking as dup of #147541
