### ISSUE TITLE
Terminal activate conda base environment just after activating the right environment

### ISSUE THREAD

**Issue by Lawiss** [microsoft/vscode#147016]
Does this issue occur when all extensions are disabled?: Yes/No

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.9
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: false
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "black"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2022.4.0
VS Code version: Code 1.66.0 (Universal) (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id a129d0b2-ecd6-4f0a-8ff3-d67e5b6507fa|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
testflight:30433670
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
pynewfile477:30463512

```

</details>

# Behaviour
## Expected vs. Actual

Hello,
When I select my conda env for the workspace, I expect that each terminal session activate this environment. In the past it worked well. But since a few days I have a strange behaviour : the terminal execute the command `conda activate myenv` then just after `source /Users/luis/miniforge3/bin/activate` reactivating base env. (see in screenshoot)

## Steps to reproduce:
![Enregistrement de l’écran 2022-04-06 à 12 03 22(1)](https://user-images.githubusercontent.com/30115537/161980990-9f437397-0e65-4023-a666-0fb3217c20ec.gif)

**Comment by meganrogge** [comment]
@karthiknadig any thoughts?

**Comment by karthiknadig** [comment]
@meganrogge This was filed here in response to this comment: https://github.com/microsoft/vscode-python/issues/18868#issuecomment-1090501106

Even though python extension is sending the commands in the order:
```
source /Users/luis/miniforge3/bin/activate
conda activate velov
```
The second command is executed first.

/cc @karrtikr

**Comment by meganrogge** [comment]
Thanks, how are those currently being sent ? Via send text to terminal? @karthiknadig

**Comment by karrtikr** [comment]
Yep, right here:
https://github.com/microsoft/vscode-python/blob/db8e1e2460e9754ec0672d958789382b6d15c5aa/src/client/common/terminal/activator/base.ts#L31-L36

**Comment by meganrogge** [comment]
@karrtikr I could be wrong, but it appears in the gif above that the commands run in the terminal in the correct order. Does this also happen in bash?

If we had this API, you could more reliably know when a command is finished
#145234

**Comment by karrtikr** [comment]
I assume this means that this is a bug with zsh shell itself. Can you provide the steps to simulate sending commands outside of VSCode? Ideally this should be reported there before it's closed.

**Comment by meganrogge** [comment]
Does the issue reproduce in bash?

**Comment by karrtikr** [comment]
For me it doesn't, also we only received issues for ZSH.

@Lawiss Can you confirm if using bash has the same issue?

**Comment by Lawiss** [comment]
Hello @karrtikr @meganrogge,

Indeed, I can reproduce the issue only on zsh, commandes are fired in the correct order on bash.
