### ISSUE TITLE
Jupyter Interactive Window Scroll Bar Not Clickable

### ISSUE THREAD

**Issue by wei-lingfeng** [microsoft/vscode#147027]
## Environment data

-   VS Code version: 1.66.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.3.1000901801
-   Python Extension version (available under the Extensions sidebar): v2022.4.0
-   OS (Windows | Mac | Linux distro) and version: Windows 10 21H2
-   Python and/or Anaconda version: Python 3.9.7, Miniconda 4.12.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): python & conda environment both have this problem.
-   Jupyter server running: Local & Remote both have this problem.

## Expected behaviour
Click and drag the vertical scroll bar should be able to scroll the window vertically.

## Actual behaviour

When hover the mouse over the scroll bar, it does not respond to click and drag. Touchpad works though.

## Steps to reproduce:

1. Create jupyter interactive window.
2. Run the following code: `for i in range(20): print(i)`
3. Try click and drag the vertical scroll bar on the right. It does not work.

**Comment by rchiodo** [comment]
@roblourens I can no longer click on the scrollbar for the interactive window? Would this be your area?

**Comment by roblourens** [comment]
@rebornix I see this, only in the interactive window and not a normal notebook, seems like something must be covering the scrollbar but I can't figure out what

**Comment by wei-lingfeng** [comment]
Same as issue https://github.com/microsoft/vscode/issues/146715

**Comment by moonj94** [comment]
Hey I was wondering if there is a solution to this? I am being confronted with the same issue.
