### ISSUE TITLE
Native Notebooks - Outline (aka Table of Contents or TOC) does not display header numbers

### ISSUE THREAD

**Issue by brunolajoie** [microsoft/vscode#147008]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.0
- OS: MacOS Monterey 12.3, Darwin x64 21.4.0

Steps to Reproduce:

1. Open new notebook.ipynb
2. Create new markdown cell, name it for instance `# 1) My First Header` or `# 1. My First Header`
3. Outline will only show `My First Header` and have deleted the 1) or 1. written manually

**Comment by Yoyokrazy** [comment]
cc @mjbvz -- It looks like this is being sanitized out of md strings. A markdown cell containing `# 1. Main Section` will be sanitized to render as `Main Section`. It seems to be happening at the following:

https://github.com/microsoft/vscode/blob/ed85cfdbe898b160a0d8aa6e3ecfbd3d2af46316/src/vs/workbench/contrib/notebook/browser/viewModel/foldingModel.ts#L315-L324

https://github.com/microsoft/vscode/blob/ed85cfdbe898b160a0d8aa6e3ecfbd3d2af46316/src/vs/base/browser/markdownRenderer.ts#L488-L498
