### ISSUE TITLE
Edge accessibility warnings

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#147036]
1. [x] ARIA attributes must conform to valid names: Invalid ARIA attribute name: aria-description
```
<div draggable="true" role="tab" class="tab tab-actions-right sizing-fit has-icon active tab-border-bottom tab-border-top" aria-label="notebooks.excalidraw, preview" aria-description="" title="rebornix/notebooks/notebooks.excalidraw" data-resource-name="notebooks.excalidraw" aria-selected="true" tabindex="0" style="left: auto; border-right: 1px solid rgb(225, 228, 232); background-color: rgb(255, 255, 255); --tab-border-bottom-color:#ffffff; --tab-border-top-color:#f9826c; color: rgb(47, 54, 61);">
```

2. [x]  (7) Certain ARIA roles must be contained by particular parents: Required ARIA parent role not present: tablist 

```
<li class="action-item icon" role="tab" draggable="true" aria-label="" aria-expanded="false" aria-selected="false" tabindex="0" style="--insert-border-color:#2f363d;">

<li class="action-item icon" role="tab" draggable="true" aria-label="" aria-expanded="false" aria-selected="false" style="--insert-border-color:#2f363d;">

<li class="action-item icon" role="tab" draggable="true" aria-label="Source Control (⌃⇧G) - 1 pending changes" aria-expanded="false" aria-selected="false" style="--insert-border-color:#2f363d;">

<li class="action-item icon" role="tab" draggable="true" aria-label="" aria-expanded="false" aria-selected="false" style="--insert-border-color:#2f363d;">

...
```

3. [x]  Frames must have an accessible name: Element has no title attribute

```
<iframe class="web-worker-ext-host-iframe" sandbox="allow-scripts allow-same-origin" src="https://v--1vk1s8frt9vra7aqv2ia0o0i3vas1mralutakk6geck7ms4v08cg.vscode-webview.net/insider/521a3d858570ebc9ce9d5602802f4525a02e045c/out/vs/workbench/services/extensions/worker/webWorkerExtensionHostIframe.html?parentOrigin=https%3A%2F%2Fgithub.dev&amp;salt=15783f24-9603-4ed1-b381-007d008a8d9a&amp;vscodeWebWorkerExtHostId=cf82c2a4-5850-4ca6-8283-dedd46b5ac22" style="display: none;">
```

4. [ ] id attribute value must be unique: Document has multiple static elements with the same id attribute: status.scm

```
<div id="status.scm" class="statusbar-item left" aria-label="main*, notebooks (rebornix/notebooks) - 3818471">
```

5. [x] Interactive controls must not be nested

```
<div draggable="true" role="tab" class="tab tab-actions-right sizing-fit has-icon active tab-border-bottom tab-border-top" aria-label="notebooks.excalidraw, preview" aria-description="" title="rebornix/notebooks/notebooks.excalidraw" data-resource-name="notebooks.excalidraw" aria-selected="true" tabindex="0" style="left: auto; border-right: 1px solid rgb(225, 228, 232); background-color: rgb(255, 255, 255); --tab-border-bottom-color:#ffffff; --tab-border-top-color:#f9826c; color: rgb(47, 54, 61);">
```

@isidorn here are 5 common accessibility warnings I'm seeing while using github.dev, some of them do make sense to me.

**Comment by isidorn** [comment]
First item is fine, we added aria-description since some screen readers support it even though it is not official yet (Orca supports it).
Second item - I have pushed a fix da8af6c5fc4
Third item - @mjbvz can you please look into adding a title attribute for the iframe? I am not 100% sure what iframe is this @rebornix 
Fourth item - @lszomoru is it possible to introduce a different id, so there is no overlap between `status.scm`
Last item - I would leave this as it is for now

**Comment by mjbvz** [comment]
@alexdima This is the web worker iframe, which is hidden from users. We already set `display: none` on it so I don't think this is a real issue.  Maybe just add a placeholder title to make the edge accessibility checks happy

**Comment by isidorn** [comment]
Or maybe add `aria-hidden` on it.

**Comment by isidorn** [comment]
Let's assign to May debt week. This might be low hanging.

**Comment by isidorn** [comment]
Thanks all for tackling this 👏
