### ISSUE TITLE
Alt action precondition isn't respected

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#147024]
- Register an action with an "alt" action that has a precondition of `ContextKeyExpr.false`
- Hover it, press alt, it still shows the alt action

I don't think this has ever been used, but I need it for https://github.com/microsoft/vscode/issues/145650

cc @jrieken am I missing something?

**Comment by jrieken** [comment]
> Hover it, press alt, it still shows the alt action

I would have thought that the _alt_ernative action renders disabled, not disabling it altogether. Tho, it makes sense when implemented somewhere [here](https://github.com/microsoft/vscode/blob/dafc40bca5439520d7e8b1c4a5c15c744bf69c10/src/vs/platform/actions/browser/menuEntryActionViewItem.ts#L174)

**Comment by rchiodo** [comment]
@roblourens I'm not sure how to test this?

**Comment by roblourens** [comment]
It could be done with a registration from an extension, but also it is used in the stop button on the debug toolbar, so if pressing alt doesn't have an effect there with js-debug, it is working
