### ISSUE TITLE
Typescript keeps crashing

### ISSUE THREAD

**Issue by alexlopezit** [microsoft/vscode#147051]
Issue Type: <b>Bug</b>

just editing files

VS Code version: Code 1.66.1 (Universal) (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:49:47.400Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 14, 20|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id a7c44270-ee65-49de-adca-5e7e8ffe35b9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
Nix|bbe|1.0.1
vscode-tailwindcss|bra|0.7.7
laravel-blade|cjh|1.1.2
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|12.0.5
vscode-html-css|ecm|1.11.0
EditorConfig|Edi|0.16.4
phpunit|ema|4.1.1
prettier-vscode|esb|9.5.0
vscode-jest-runner|fir|0.4.48
kotlin|fwc|0.2.24
copilot|Git|1.12.5517
vscode-graphql|Gra|0.4.1
composer|ika|0.8.0
phpcs|ika|1.0.5
plantuml|jeb|2.17.2
vscode-phpfmt|kok|1.0.31
coffeelinter|lky|1.4.0
Kotlin|mat|1.7.1
openapi-lint|mer|1.2.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.21.0
vscode-dotnet-runtime|ms-|1.5.0
remote-containers|ms-|0.231.4
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
vscode-remote-extensionpack|ms-|0.21.0
vscode-typescript-tslint-plugin|ms-|1.3.4
debugger-for-chrome|msj|4.13.0
php-docblocker|nei|2.7.0
vetur|oct|0.35.0
java|red|1.4.0
vscode-yaml|red|1.6.0
scala|sca|0.5.5
vscode-scss-formatter|sib|2.4.2
code-spell-checker|str|2.1.11
vscode-stylelint|sty|1.2.2
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.2.18
vscode-java-debug|vsc|0.40.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.2
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
gitblame|wad|8.1.0
markdown-all-in-one|yzh|3.4.0
php-intellisense|zob|1.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
