### ISSUE TITLE
Can't restore hidden editor view when I execute command "View : toggle Editor Area Visibility"

### ISSUE THREAD

**Issue by softmare** [microsoft/vscode#147042]
Issue Type: <b>Bug</b>

when I execute the command "view : toggle editor area visibility", editor view is hidden as well. However, running the command again does not restore the Editor view.

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:49:52.288Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.73GB free)|
|Process Argv|--crash-reporter-id f545d751-4918-4489-b3bc-aeb914445f09|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
conflict-squeezer|ang|1.0.1
github-markdown-preview|bie|0.2.0
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-footnotes|bie|0.0.7
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
dart-code|Dar|3.38.0
flutter|Dar|3.38.1
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.5
code-runner|for|0.11.7
remotehub|Git|0.30.0
gitpod-desktop|git|0.0.29
gitpod-remote-ssh|git|0.0.28
vscode-test-explorer|hbe|2.21.1
better-cpp-syntax|jef|1.15.13
rust-analyzer|mat|0.2.1002
git-graph|mhu|1.30.0
vscode-docker|ms-|1.21.0
csharp|ms-|1.24.3
remote-containers|ms-|0.231.4
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
remote-repositories|ms-|0.4.0
test-adapter-converter|ms-|0.1.5
vsliveshare|ms-|1.0.5449
color-highlight|nau|2.5.0
abracadabra|nic|6.12.0
colmak-vim|oll|1.21.10
vscode-thunder-client|ran|1.14.4
LiveServer|rit|5.7.5
code-settings-sync|Sha|3.4.3
sass-indented|syl|1.8.19
cmake|twx|0.0.17
shell-launcher|Tyr|0.4.1
vscode-lldb|vad|1.7.0
vscodeintellicode|Vis|1.2.18
clang-format|xav|1.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
pynewfile477:30463512

```

</details>

**Comment by softmare** [comment]
![Recording 2022-04-11 at 22 36 16 (1)](https://user-images.githubusercontent.com/64849750/162757221-49c324df-62e4-4d46-a77e-7897e98624a6.gif)
What I expected was that the editor window show up again after I turn off it using "view : toggle editor area visibility" command, but nothing happen. 
Even I turn off the project window than open the folder as project again, still editor and terminal window doesn't show up.

**Comment by softmare** [comment]
@sbatten After I changed the panel alignment to center then executed the command again then editor window showed up. After setting, toggling is working well. I missed your last sentence so I didn't check what the panel setting was exactly, It wasn't set to center. When the panel setting set to left or right, the issue is still happening.

**Comment by sbatten** [comment]
@softmare thanks for the information. this command actually shouldn't be exposed in the case where the panel is not "center-aligned" due to a grid limitation. The command should be hidden in the next insiders.
