### ISSUE TITLE
Typescript Bug

### ISSUE THREAD

**Issue by BillDelvin** [microsoft/vscode#147047]
Issue Type: <b>Bug</b>

The TypeScript language service died 5 times right after it got started. The service will not be restarted.

the error keep showing this message

VS Code version: Code 1.66.0 (Universal) (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|--crash-reporter-id 7bf66937-8ddc-4934-b55a-7a8d5bd76096|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.8.0
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.2
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|4.4.3
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.5.0
auto-rename-tag|for|0.1.10
dotenv|mik|1.0.1
vscode-typescript-next|ms-|4.7.20220406
vscode-typescript-tslint-plugin|ms-|1.3.4
indent-rainbow|ode|8.2.2
material-icon-theme|PKi|4.15.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.5
markdown-preview-enhanced|shd|0.6.2
vscode-scss-formatter|sib|2.4.2
material-theme|zhu|3.13.20

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by indooorsman** [comment]
@mjbvz I've tried latest insiders build, this issue still happens. btw, everytime I'm writing **generics** typescript server seems to hang up and IntelliSense keep loading

<img width="651" alt="screenshot" src="https://user-images.githubusercontent.com/4919405/162377256-f635ca1c-5ad5-454e-903a-666f44c76b9b.png">
g

**Comment by BillDelvin** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

yeah it's reproduce in the  [latest VS Code insiders build](https://code.visualstudio.com/insiders/), but all my extension still enabled

**Comment by indooorsman** [comment]
> > Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
> 
> yeah it's reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/), but all my extension still enabled
> 
> should I disabled the extensions?

I tried with all extensions disabled, still have this issue

**Comment by BillDelvin** [comment]
> > > Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
> > 
> > 
> > yeah it's reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/), but all my extension still enabled
> > should I disabled the extensions?
> 
> I tried with all extensions disabled, still have this issue

sorry I think I'm not realy carefully to read what @mjbvz mention before,  this [VS Code insiders build](https://code.visualstudio.com/insiders/) not same with VS Code that I'm using before, but when I used it, it's FIX my problem, that bug no longer show again. thankss to @mjbvz 

did u have try this [VS Code insiders build](https://code.visualstudio.com/insiders/) @indooorsman ?

**Comment by indooorsman** [comment]
> > > > Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
> > > 
> > > 
> > > yeah it's reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/), but all my extension still enabled
> > > should I disabled the extensions?
> > 
> > 
> > I tried with all extensions disabled, still have this issue
> 
> sorry I think I'm not carefully to read what @mjbvz mention before, this [VS Code insiders build](https://code.visualstudio.com/insiders/) not same with VS Code that I'm using before, but when I used it, it's FIX my problem, that bug no longer show again. thankss to @mjbvz
> 
> did u have try this [VS Code insiders build](https://code.visualstudio.com/insiders/) @indooorsman ?

@BillDelvin yes, i do try the insiders build
