### ISSUE TITLE
Make it possible to show a hidden character 

### ISSUE THREAD

**Issue by JDJGInc** [microsoft/vscode#147093]
I want to be able to see U+2800 again

**Comment by JDJGInc** [comment]
[![unknown-1.png](https://user-images.githubusercontent.com/22802640/162470584-310108c4-b313-47dc-9595-5d9d7982201b.png)
I.e. the info was there
But I did not see it now

**Comment by JDJGInc** [comment]
Okay i had to eat my config for this, but I have a feeling there should be an easy get to button.

**Comment by hediet** [comment]
Can I close this issue then?

Please create another issue for making the config more visible.
