### ISSUE TITLE
vscode chrome attach unable to connect after some time

### ISSUE THREAD

**Issue by yuis-ice** [microsoft/vscode#147050]
Does this issue occur when all extensions are disabled?: Yes/No

No. because in order to reproduce the issue, at least it requires the Remote SSH packages. 

- VS Code Version:

1.64.2
1.65.2
1.66.1 (the latest) 

Tested on the all above versions as below mentioned

- OS Version:

Windows 10 Pro     2009

--- 

I have a really wired bug on vscode. I can "attach chrome" debugging totally fine usually, 

but after some random time connecting to the chrome instance (may be a couple of hours or 8 hours, like I left it connected while I'm sleeping), it automatically disconnect the debugging, 

then when I try to re-run attach chrome to reconnect it, for some weird reason it doesn't connect to the instance. 

It's not a failed, it's not like "cannot connect to the port 9222", it's infinitely trying to connect showing the left up side blue indicator left to right. 

This is my second time to encounter this weird problem. For the first time I even don't know how I solved the issue. maybe I just waited its reconnect for an hour or like that. 

The first things I happened to think from the problem is simply its port conflict. So I checked vscode side's (I mean I use vscode in the remote ssh mode from Windows to Linux Ubuntu) port and process, used htop to filter port "9222" or process "chrome", but I didn't find anything stucking there. So I assume in the linux side the debugging process is exiting successfully. 

So I did the same on the Windows side, I used resource monitor to check port "9222", no running process. If I re-open a 9222 debugging enable chrome, then it appears. closing, it disappears. It seems there is no problem here as well. 

I then checked vscode's version. I was using vscode 1.64.2 so I side-installed 1.65.2 and 1.66.1 (the latest) and tested it. Doesn't work. 

"refreshing the window" doesn't work. closing the window and re-open, doesn't work. 

So what can I do?

**Comment by connor4312** [comment]
Because refreshing the window doesn't work, I have a feeling this might be in the port forwarding side / remote server -- a port is forwarded from the remote side for the browser debug connection. The remote server stays running on the SSH side, and forwarded ports (which we use to establish debugging) _can_ be remembered. But js-debug doesn't keep much of any context over window reloads, so that suggests to me the problem is not there.

@alexr00 / @eleanorjboyd have seen any similar issues over the past few months?

**Comment by alexr00** [comment]
I don't recall hearing about anything like this.

> The first things I happened to think from the problem is simply its port conflict. So I checked vscode side's (I mean I use vscode in the remote ssh mode from Windows to Linux Ubuntu) port and process, used htop to filter port "9222" or process "chrome", but I didn't find anything stucking there. So I assume in the linux side the debugging process is exiting successfully.

@yuis-ice does 9222 show in the Ports view in VS Code?

**Comment by connor4312** [comment]
Merging into https://github.com/microsoft/vscode/issues/174033
