### ISSUE TITLE
Notify the user that backups exist but have not been restored if the folder to be restored no longer exists

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14705]
Moving this over from #14063

After https://github.com/Microsoft/vscode/commit/62ec04bb71d6185653aed6592e7c3245060e1ab4 the backups are not restored if the workspace directory doesn't exist anymore. The workspace is no longer tracked but the backups are kept around in the backup directory should they be needed later.

**Comment by bpasero** [comment]
Tricky.... I would expect an empty window to open with those files dirty. This might require some work on the area of restoring on empty workspaces. Have not thought about this longer yet.

**Comment by bpasero** [comment]
Marking as important because this means data loss if the folder is deleted on disk.

**Comment by bpasero** [comment]
@Tyriar maybe this should be done on the main side on startup similarly to https://github.com/Microsoft/vscode/issues/14054. If a folder no longer exists, convert it into an empty workspace backup and let it open as empty window.

**Comment by Tyriar** [comment]
On test plan: https://github.com/Microsoft/vscode/issues/16544
