### ISSUE TITLE
VS Code turns emo?!?!?!😔🖤🔪⛓

### ISSUE THREAD

**Issue by tibidegamebaas** [microsoft/vscode#147069]
Issue Type: <b>Bug</b>

Every time I open VS Code, a window pops up after a few seconds showing he is trying to uninstall itself. Fortunately, it's a warning saying "access denied". Please help is he emo😔😖😞🖤🖤🔪🔫🔫🔫?
Edit: This only happens if it is the first windows of VS Code opening. If another window is already open, this won't happen.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A9-9425 RADEON R5, 5 COMPUTE CORES 2C+3G    (2 x 3094)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.45GB (3.36GB free)|
|Process Argv|C:\\Users\\Thibaud Van Wilder\\OneDrive\\Documenten\\Python projects\\Extract.py --crash-reporter-id a20acb8c-5df7-48b9-b5b2-95c2ecf1b8cc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.0
jupyter|ms-|2022.2.1030672458

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
pynewfile477:30463512

```

</details>

![image](https://user-images.githubusercontent.com/59932612/162396413-9e15bd5a-4e7d-4726-b1b5-18674a83cdcf.png)

**Comment by IllusionMH** [comment]
I guess you should switch UI to light theme.

On the serious note - have you used user installer to point it to Program Files? Looks like VS Code tries to update to 1.66 and doesn't have access.
See similar report https://github.com/microsoft/vscode/issues/75367

**Comment by tibidegamebaas** [comment]
Alright, I guess I'll just reinstall it in AppData then.

**Comment by tibidegamebaas** [comment]
That worked, thanks!
