### ISSUE TITLE
"editor.tabsize" does not support per-language configuration.

### ISSUE THREAD

**Issue by zicjin** [microsoft/vscode#147046]
"editor.tabsize" does not support per-language configuration.

_Originally posted by @BenjaVR in https://github.com/microsoft/vscode/issues/23933#issuecomment-291849166_

**Comment by BenjaVR** [comment]
@zicjin originally posted by me?

**Comment by alexdima** [comment]
@zicjin What are the steps to reproduce?

**Comment by zicjin** [comment]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/199482/162396003-01cbaf52-40b1-4c7d-a7b5-f1e379514806.png">
Obviously this feature is not currently supported

**Comment by BenjaVR** [comment]
@zicjin you have to use `editor.tabSize` instead of `editor.tabsize`.
