### ISSUE TITLE
Code formatting doesn't work on long lines with commas.

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#14703]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:43:46.054Z)
- OS Version: Linux x64 4.4.0-45-generic
- Extensions: DavidAnson.vscode-markdownlint-0.5.0, EditorConfig.EditorConfig-0.3.4, ajhyndman.jslint-1.2.1, dbaeumer.jshint-0.10.15, dbaeumer.vscode-eslint-1.0.8, eg2.tslint-0.5.39, jakethashi.vscode-angular2-emmet-1.0.9, ms-vscode.cpptools-0.9.2, msjsdiag.debugger-for-chrome-2.1.1, vscodevim.vim-0.4.0

Steps to Reproduce:
1. Type following line in code

``` js
import { Component, OnInit, OnChanges, DoCheck, AfterContentInit, AfterContentChecked, AfterViewInit, AfterViewChecked } from '@angular/core';
```
1. Format code, nothing happen. I expect "column formating" after the commas like this:

``` js
import { Component, 
         OnInit,
         OnChanges, 
         DoCheck, 
         AfterContentInit, 
         AfterContentChecked,
         AfterViewInit, 
         AfterViewChecked } from '@angular/core';
```

**Comment by akintundejr4** [comment]
What typescript version are you using?

**Comment by rajinder-yadav** [comment]
~:$ tsc -v
Version 2.0.3

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#12003
