### ISSUE TITLE
VS Code in a missing drive, can't reinstall.

### ISSUE THREAD

**Issue by DiThi** [microsoft/vscode#147041]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Latest (user mode)
- OS Version: Windows

I no longer have the drive I had VS Code in, it could be lost, crashed, broken, corrupted, doesn't matter. I can't reinstall VS Code. The installer has no option to select a different drive and it says:

    The drive or UNC share you selected does not exist or is not accessible. Please select another.

Steps to Reproduce:

1. Install VS Code in a drive you can remove.
2. Remove the drive.
3. Try to uninstall or reinstall VS Code.

Workaround for people that find this issue:

1. Open regedit
2. Copy and paste this in the address bar, press enter.

    Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1

4. Delete selected key (right click on folder, delete).

I wrote this issue to at least have people find it with a workaround that works. Note that there are other issues with the same title, **some are irrelevant and others don't have the fix.** I put searchable keywords in the issue.

**Comment by joaomoreno** [comment]
AFAIK There's no good fix here. How do other applications deal with this? Basically the location where they were installed no longer exists.

**Comment by DiThi** [comment]
> AFAIK There's no good fix here. How do other applications deal with this? Basically the location where they were installed no longer exists.

Any other application lets you reinstall it in a different location! VS Code is the first one I've ever encountered that doesn't let you reinstall it elsewhere.
