### ISSUE TITLE
express static folder and go to definition

### ISSUE THREAD

**Issue by CodeGenTeam** [Microsoft/vscode#14709]
1. 1.6.1
2. Windows 10

I have in express:
app.use(express.static(__dirname + '/../public'));
In html file I cannot go to definition. But It's correct, when I run app.
![image](https://cloud.githubusercontent.com/assets/11016041/19833752/6334818a-9e67-11e6-9e4e-b72cf28e5900.png)
Where I can fix this problem?

**Comment by aeschli** [comment]
Sorry, we can only open the link is the css is at a location relative to the html file.
