### ISSUE TITLE
[themes] Dark theme in 0.10.5 less colorful than in 0.10.3

### ISSUE THREAD

**Issue by gpbl** [Microsoft/vscode#1470]
I've upgraded from 0.10.3 to 0.10.5, and the javascript syntax highlighting doesn't work as well as before (OSX El Capitan):

from this:
<img width="264" alt="screen shot 2015-12-19 at 10 36 26" src="https://cloud.githubusercontent.com/assets/120693/11912441/d67bc7b2-a63c-11e5-9ab1-05bfc22ee527.png">

to this:
<img width="230" alt="screen shot 2015-12-19 at 10 38 59" src="https://cloud.githubusercontent.com/assets/120693/11912442/d9c21f2a-a63c-11e5-9a76-2e90f76c8b41.png">

I also removed any extension I've installed, but it didn't fix it...

**Comment by lcrespom** [comment]
I am using Monokai, where function parameters are displayed in orange, but with this update the parameters are displayed in gray although the Monokai.tmTheme clearly states that parameters should be orange (#FD971F).

This may seem like nitpicking, but good syntax highlighting is my top criterion for selecting one or other code editor.

**Comment by bgse** [comment]
Same issue exists on Linux version.

**Comment by bgse** [comment]
![vscode_jshighlighting_0105](https://cloud.githubusercontent.com/assets/8385202/11913199/85019536-a65c-11e5-8428-53e3fd534b73.png)

More on this, look at how missing space in for-loop breaks even more of following highlighting in 0.10.5, below the same in 0.10.3 which is perfect: 

![vscode_jshighlighting_0103](https://cloud.githubusercontent.com/assets/8385202/11913203/ba04a9bc-a65c-11e5-9ab3-2d5d13e4be4f.png)

**Comment by adnan333bd** [comment]
![image](https://cloud.githubusercontent.com/assets/15263521/11914301/10f7ee2e-a6a7-11e5-93db-eefdbcdc4e84.png)

Facing same issue with typescript, class names and interface names are not colored as expected ...

**Comment by MacKentoch** [comment]
So now I feel less alone with syntax highlighting.

Got same issues with **javascript ES6**.
As an example `import` (was red before) is now just grey...

**Comment by irakliy81** [comment]
+1 with TypeScript on Windows 10 - some keywords such as `typeof` and `instanceof` are not highlighted at all

**Comment by egamma** [comment]
Apologies for all the inconveniences. There are several different issues in this issue that we need to untangle. 

First some background... 
* Between 0.9.0 and 0.10.3 we switched to textmate grammars for all languages. 
* In 0.10.5 we have switched to another grammar for JS coloring. To support ES6 in JS we are now using the same grammar that is used for TypeScript for JS. 

These changes have impacted the default Dark and Light theme. As described in the [test plan](https://github.com/Microsoft/vscode/wiki/December-Test-Plan#dark-and-light-theme-polish) our goal was to get back as close as possible to what we had in 0.9.0. The reasoning was that there are many more colorful themes provided (e.g. monokai) if users want more color.

Now to the different issues:

@gpbl in 0.9.0 the dark theme was less colorful and it matched the Dark theme of Visual Studio. We went back to this one. Obviously you got used to the coloring we had in 0.10.3. My suggestion is to provide a Dark* theme as an extension that is aligned with what 0.10.3 provided as soon as possible. We can then decide to switch the default Dark theme. Let's keep this issue open to track this problem. I've adjusted the title. Can you try to use another dark theme in the mean time.

@lcrespom this looks like a bug in how in the Monokai theme extracted into issue #1504

>More on this, look at how missing space in for-loop breaks even more of following highlighting in 0.10.5

@bgse This is issue Microsoft/TypeScript-TmLanguage#17 as you figured.

@adnan333bd the loss of color in the Dark theme also shows up in TypeScript.

@MacKentoch this looks like a bug in the TypeScript grammar. Extracted into Microsoft/TypeScript-TmLanguage#32

@irakliy81 this looks like an issue in the TypeScript grammar. Can you please report in Microsoft/TypeScript-TmLanguage with a snippet illustrating the issue.

**Comment by adnan333bd** [comment]
thanks @egamma , I rather use Solarized Light. Thanks, you guys are doing great!

**Comment by rakkarage** [comment]
Ya, miss the more colorful version.

**Comment by ricmed205** [comment]
+1

**Comment by gpbl** [comment]
Thanks @egamma for the clarification! I wasn't aware about that test plan 😄.
The `Dark` and `Light` default themes were very nice in 0.10.3, I'm already missing them.

**Comment by Wosi** [comment]
I face similar issues using the default dark theme with the OmniPascal plugin. Method names (`entity.name.function`) used to be yellow and operators (`keyword.operator`) used to be gray. Now it's all white. The default theme of the previous version looked better.

**Comment by ricmed205** [comment]
I've seen that many (maybe all) of the themes are not rendering the same as before the update. EG: not rendering the function parameters, or not rendering the object method keys. I've tried with a few (EG: tomorrow night eighties).

**Comment by egamma** [comment]
@wosi how does it look with OmniPascal when you use a more colorful theme, e.g, Monokai?

**Comment by Wosi** [comment]
@egamma In Monokai function names are displayed in green. But type names aren't colored using that theme. I couldn't find a theme that colors function names **and** type names.

**Comment by bgse** [comment]
Maybe the themes should come in two variants per theme, one variant offering a relatively flat coloring, and a more colorful variant, but both using the same base color scheme.

While extensions can do this, I'd argue the themes delivered with the base product should not force the user to decide between flat and rich coloring while they decide which color scheme works best for them, as those are (in my personal opinion) two decisions that are not necessarily linked.

**Comment by ddotlic** [comment]
> Maybe the themes should come in two variants per theme, one variant offering a relatively flat coloring, and a more colorful variant, but both using the same base color scheme.

If possible, this please.

Typescript colorization was great in 0.10.4, it's now again blend and dull in 0.10.5.

From @egamma comments I understand that this is intentional?

I'll use Monokai in the meantime (which I generally like), but please do consider having default themes as colorful as they were prior to 0.10.5, IMHO they strike great balance between "too much" and "too little" colors.

Thanks for this wonderful editor!

**Comment by lcrespom** [comment]
Sorry for nagging, but could you give an approximate fix date for this bug?

**Comment by egamma** [comment]
The intent is to make separate Light/Dark* theme extensions as described in this [comment](https://github.com/Microsoft/vscode/issues/1470#issuecomment-166111410) available first week of January.

**Comment by lcrespom** [comment]
Thank you very much :-).

Will that fix propagate to fix [#1504](https://github.com/Microsoft/vscode/issues/1504) also?

**Comment by egamma** [comment]
The new more colorful default themes are now available as an extension.
Please see issue #1849 for background and for how to install them.

**Comment by aeschli** [comment]
Closing as fixed. The colorful default themes will be part of VSCode in the January build. It is no longer needed to install these themes as extensions from the marketplace. In fact, everybody who has installed them can uninstall the extensions to avoid duplicated entries in the theme selection dialog.

**Comment by ddotlic** [comment]
Any timeframe on availability of VSCode January build? I see nothing even on insiders channel. Thanks!

**Comment by egamma** [comment]
We will make the Jan update available early next week.
