### ISSUE TITLE
Terminal's sendText adds extra empty lines in CRLF mode on Windows

### ISSUE THREAD

**Issue by kirill-gerasimenko** [Microsoft/vscode#14701]
Hi,
Here is the description of my findings. If it's not complete I can add what's needed. 
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: alefragnani.Bookmarks-0.9.2, christian-kohler.path-intellisense-1.1.0, donjayamanne.githistory-0.1.0, Ionide.Ionide-FAKE-1.1.0, Ionide.Ionide-fsharp-2.8.8, Ionide.Ionide-Paket-1.3.2, mohsen1.prettify-json-0.0.3, ms-vscode.csharp-1.4.1, ms-vscode.PowerShell-0.7.2, ms-vscode.Theme-1337-0.1.2, robertohuertasm.vscode-icons-3.0.7

Steps to Reproduce:
1. Get Ionide-fsharp addon
2. Create .fsx file (in CRLF mode)
3. Enter valid F# multi-line value, for example:

``` fsharp
"(* some text
on multiple
lines in comment*)"
```
1. Select typed text
2. Press Alt-Enter -> which is bound to command FSI: Send selection
3. See FSI terminal opens and prints out the selected text

The problem is that when file is in CRLF mode - terminal outputs extra lines, when in LF mode - terminal outputs the same text that was sent to it. 

I tracked it down in the Ionide-fsharp plugin to make sure that it is not the plugin messes things up. 
Here's selected text:

![image](https://cloud.githubusercontent.com/assets/3036330/19832186/301f0cec-9e1d-11e6-965c-73e2912f49be.png)

Next the point in code where the text gets sent to Terminal object (which is `fp` on the screen):

![image](https://cloud.githubusercontent.com/assets/3036330/19832194/56db0552-9e1d-11e6-904a-4a98dd5fd3cb.png)

The `msg_1` variable is evaluated to "            @\"(\* starts\r\n            let x = 10\r\n            *)\" \n;;\n"

This is what gets echoed: 

![image](https://cloud.githubusercontent.com/assets/3036330/19832214/ae867372-9e1d-11e6-89eb-ec9aca680182.png)

You can see that it's got empty lines between the ones which were sent.

If I change the file to LF mode and perform same actions I get correct result: 

![image](https://cloud.githubusercontent.com/assets/3036330/19832222/13de5f28-9e1e-11e6-9d68-b4390852447b.png)

Thanks

**Comment by Tyriar** [comment]
I think this was fixed a long time ago.
