### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by firattale** [microsoft/vscode#147003]
Issue Type: <b>Bug</b>

The TypeScript language service died unexpectedly 5 times in the last 5 Minutes. It just happened, I dont know the reason.

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|17, 18, 15|
|Memory (System)|16.00GB (0.49GB free)|
|Process Argv|--crash-reporter-id 508ca210-79dc-4283-9a38-670ddefa0422|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
jest-snippets|and|1.8.0
gitstash|art|5.1.0
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
denigma|den|0.0.14
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.5
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.5.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
copilot|Git|1.12.5517
gc-excelviewer|Gra|4.2.54
vscode-graphql|Gra|0.3.53
terraform|has|2.21.0
vscode-react-typescript|inf|1.3.1
plantuml|jeb|2.17.2
solidity|Jua|0.0.137
vscode-colorize|kam|0.11.1
vscode-codemetrics|kis|1.24.0
vscode-language-babel|mgm|0.0.36
dotenv|mik|1.0.1
vscode-docker|ms-|1.21.0
vscode-typescript-tslint-plugin|ms-|1.3.4
abracadabra|nic|6.12.0
hardhat-solidity|Nom|0.2.2
vscode-versionlens|pfl|1.0.9
polacode|pnp|0.3.4
vscode-css-peek|pra|4.2.0
code-settings-sync|Sha|3.4.3
vscode-scss-formatter|sib|2.4.2
autoimport|ste|1.5.4
swyx-react-typescript-snippets|swy|1.0.19
sass-indented|syl|1.8.19
language-stylus|sys|1.15.0
graphviz-interactive-preview|tin|0.1.2
solidity-visual-auditor|tin|0.1.1
vscode-ethover|tin|0.0.7
vscode-inline-bookmarks|tin|0.0.25
vscode-solidity-flattener|tin|0.0.11
vscode-solidity-language|tin|0.0.6
pdf|tom|1.2.0
sort-lines|Tyr|1.9.1
vscode-icons|vsc|11.10.0
vscode-import-cost|wix|3.1.0
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
vscaac:30438847
pynewfile477:30463512

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Jbz797** [comment]
I had the same problem at home:

• With the latest VS Code insiders build : **Fail**

• After deactivating all the extensions, then reactivating them one by one, it turns out that the Tslint extension is the problem.

**Comment by Jbz797** [comment]
https://github.com/microsoft/vscode-typescript-tslint-plugin/issues/146

**Comment by firattale** [comment]
This morning, I updated VS Code to the latest version, and it seems like the problem has disappeared on my Mac.
