### ISSUE TITLE
Crash/hang on file explorer dialogue open (e.g. open file/folder or save file)

### ISSUE THREAD

**Issue by Sean-Katagiri** [microsoft/vscode#147010]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0
- OS Version: ubuntu 18.04

Steps to Reproduce:

1. start VS Code with --disable-extensions flag enabled
2. anything that brings up the file explorer e.g. opening a file/folder, saving a new file or save existing file as will cause vscode to hang.
 I've noticed that the text indicator continues to flash in the editor, but everything is uninteractive and eventually the only option is to force quit.

**Comment by JacksonKearl** [comment]
Sounds a bit like #146425
